### ISSUE TITLE
esp_wpa2.h functions not storing wpa2-ent credentials to nvs for auto-reconnect after reset in IDF v4.2 (IDFGH-8569)

### ISSUE THREAD

**Issue by debajyotisarkarhome** [espressif/esp-idf#10019]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

So, I'm using esp_wifi_sta_wpa2_ent_set_identity() ,esp_wifi_sta_wpa2_ent_set_username(), esp_wifi_sta_wpa2_ent_set_password()  to configure my esp32 to connect to a wpa2-ent network, it's getting connected successfully but not connecting automatically after reset.
IDF : v4.2

**Comment by kapilkedawat** [comment]
Hi @debajyotisarkarhome, since certificates are passed as pointers to WiFi APIs, we don't think its a good idea to save those pointers, therefore the Enterprise credentials won't be saved.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, feel free to reopen.
