### ISSUE TITLE
Documentation: remove outdated WEP (IDFGH-8564)

### ISSUE THREAD

**Issue by Rotzbua** [espressif/esp-idf#10014]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

The documentation mentions WEP as security mode. WEP is deprecated and not connectable by default. So it should be removed.

**Comment by mhdong** [comment]
Hi @Rotzbua 
Issue solved with https://github.com/espressif/esp-idf/commit/7ae5822f0e1592a0e46baeb5138f4632e9e82548

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, feel free to reopen.
