### ISSUE TITLE
CONFIG_ESP_SYSTEM_PANIC_GDBSTUB suppress CONFIG_ESP_COREDUMP_ENABLE in panic.c but the menuconfig does not specify the conflict (IDFGH-8567)

### ISSUE THREAD

**Issue by wuyuanyi135** [espressif/esp-idf#10017]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

I just realized that when CONFIG_ESP_SYSTEM_PANIC_GDBSTUB is checked (Under ` Component config → ESP System Settings → Panic handler behaviour`) the core-dump-to-flash did not generate any data.

https://github.com/espressif/esp-idf/blob/e9d7340f3be080927b79c8ea57171e6bed6deca6/components/esp_system/panic.c#L348-L349

Clearly, core dump is not enabled when GDB Stub is in use. I think those two options should be linked with Kconfig dependencies.

**Comment by ESP-Marius** [comment]
Thanks for reporting this. 

Actually, I cant think of a good reason why you shouldnt be allowed to use both. We have merged an internal MR to allow these features to be used together now.
