### ISSUE TITLE
inappropriate IPv4 address offered by DHCP server  (IDFGH-8574)

### ISSUE THREAD

**Issue by sergioaiello** [espressif/esp-idf#10024]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Hope this problem has not been previously flagged.

Based on AP networking configuration 
        IP4_ADDR(&ipInfo.ip, 192,168,200,9);
	IP4_ADDR(&ipInfo.gw, 192,168,200,9);
	IP4_ADDR(&ipInfo.netmask, 255,255,255,248);
the addresses 192.168.200.8 and 192.168.200.15 should be reserved
Vice versa the HDCP server of the ESP32 AP tried to assign it. The STA does not answer and does not associate.
Note that only three IP addresses has been assigned on 5 available:
- 192.168.200.12
- 13
- 14

I (743059) esp_netif_lwip: DHCP server assigned IP to a station, IP is: 192.168.200.15
D (743059) event: no handlers have been registered for event IP_EVENT:2 posted to loop 0x3ffbdc18
D (744349) esp_netif_lwip: esp_netif_get_ip_info esp_netif:0x3ffbeb44
D (744489) esp_netif_lwip: esp_netif_get_ip_info esp_netif:0x3ffbeb44
I (744489) esp_netif_lwip: DHCP server assigned IP to a station, IP is: 192.168.200.15
D (744499) event: no handlers have been registered for event IP_EVENT:2 posted to loop 0x3ffbdc18
D (745739) esp_netif_lwip: esp_netif_get_ip_info esp_netif:0x3ffbeb44
D (745929) esp_netif_lwip: esp_netif_get_ip_info esp_netif:0x3ffbeb44

I can't clarify the reason why the AP's DHCP svr does not consider the two addresses 192.168.200.10 and .11 (usually they are assigned as expected)

The wireshark trace reports, similarly to lwip's log. a DHCP offer of the 192.168.200.15 address. The STA does not answer to AP's HDCP MSGs

**Comment by xueyunfei998** [comment]
![image](https://user-images.githubusercontent.com/52622915/197525941-32811850-618f-40d7-8dc5-20c3a527b5b1.png)

**Comment by xueyunfei998** [comment]
![image](https://user-images.githubusercontent.com/52622915/197526011-6c4f0115-a2a3-48d8-b442-255d4d81ef57.png)

**Comment by sergioaiello** [comment]
@xueyunfei998 / "I can receive 10 addresses for the test here"
Are you saying the DHCP server does offer the IP address to 10 STAs?
If so, I think it is an error since only 8 IP addresses can be used in a /29 subnet. And on top of 8 IP addresses, the DHCP server can offer to STAs only 5.
Please, clarify
Thank you

**Comment by xueyunfei998** [comment]
hi  @sergioaiello 

I mean: according to your configuration, softap can be allocated from the address of 192.168.200.10, not to 10 stas.
![image](https://user-images.githubusercontent.com/52622915/197671015-2a53098f-fbdb-41b0-97f3-aad1fd43bc7c.png)

**Comment by sergioaiello** [comment]
hi xueyunfei998,
ok, clear thank you.
Have you checked to IPv4 address range?
I experienced that AP does not stop after .14. It offers also .15. That's a bug to me. Isn't it?

**Comment by xueyunfei998** [comment]
hi @sergioaiello 

Why can't this address 192.168.200.15 be assigned,

The address space allocated by AP is 192.168.200.9~192.168.200.73.

**Comment by xueyunfei998** [comment]
hi @sergioaiello 
Yes, the subnet mask you set has no effect on idf. This should be a bug.

**Comment by xueyunfei998** [comment]
hi @sergioaiello 

Yes, the subnet mask you set has no effect on idf.

**Comment by sergioaiello** [comment]
@xueyunfei998
is a /29 mask allowed? will a patch be released?
thank you

**Comment by xueyunfei998** [comment]
[0001-lwip-bugfix-softap-excedes-the-range-of-subnet.txt](https://github.com/espressif/esp-idf/files/9878786/0001-lwip-bugfix-softap-excedes-the-range-of-subnet.txt)
hi @sergioaiello 
Use this patch test.

**Comment by sergioaiello** [comment]
Hi xueyunfei998,
thank you for the patch. I see my "dhcpserver.c" is different (I'm using IDF release 4.4)
Please, see here below an excerpt with the "dhcps_poll_set" function.
How can apply your patch?
Thank you.

static void dhcps_poll_set(u32_t ip)
{
    u32_t softap_ip = 0, local_ip = 0;
    u32_t start_ip = 0;
    u32_t end_ip = 0;

    if (dhcps_poll.enable == true) {
        softap_ip = htonl(ip);
        start_ip = htonl(dhcps_poll.start_ip.addr);
        end_ip = htonl(dhcps_poll.end_ip.addr);

        /*config ip information can't contain local ip*/
        if ((start_ip <= softap_ip) && (softap_ip <= end_ip)) {
            dhcps_poll.enable = false;
        } else {
            /*config ip information must be in the same segment as the local ip*/
            softap_ip >>= 8;

            if (((start_ip >> 8 != softap_ip) || (end_ip >> 8 != softap_ip))
                    || (end_ip - start_ip > DHCPS_MAX_LEASE)) {
                dhcps_poll.enable = false;
            }
        }
    }

    if (dhcps_poll.enable == false) {
        local_ip = softap_ip = htonl(ip);
        softap_ip &= 0xFFFFFF00;
        local_ip &= 0xFF;

        if (local_ip >= 0x80) {
            local_ip -= DHCPS_MAX_LEASE;
        } else {
            local_ip ++;
        }

        bzero(&dhcps_poll, sizeof(dhcps_poll));
        dhcps_poll.start_ip.addr = softap_ip | local_ip;
        dhcps_poll.end_ip.addr = softap_ip | (local_ip + DHCPS_MAX_LEASE - 1);
        dhcps_poll.start_ip.addr = htonl(dhcps_poll.start_ip.addr);
        dhcps_poll.end_ip.addr = htonl(dhcps_poll.end_ip.addr);
    }

}

**Comment by AxelLin** [comment]
@xueyunfei998  Any update on this fix?

**Comment by sergioaiello** [comment]
sorry, to enter even though your question was @xueyunfei998, but I'm on hold waiting for a support to test the fix (please, see comment on Nov 19th. Thank you.

**Comment by sergioaiello** [comment]
Hi, just loaded ESP-IDF 5.0 I'll test the patch soon.
Thank you.

**Comment by AxelLin** [comment]
> Hi, just loaded ESP-IDF 5.0 I'll test the patch soon. Thank you.

@sergioaiello 
Any update for the test result?

**Comment by sergioaiello** [comment]
Hi, the issue is still there :(
In the "C:\Users\sergi\esp\esp-idf\components\lwip\apps\dhcpserver" folder I edited the file "dhcpserver.c"/"dhcps_poll_set" as follows:
"
....
static void dhcps_poll_set(dhcps_t *dhcps, u32_t ip)
{
    u32_t softap_ip = 0, local_ip = 0, temp_local_ip = 0; // u32_t softap_ip = 0, local_ip = 0;
    u32_t start_ip = 0;
    u32_t end_ip = 0;
    dhcps_lease_t *dhcps_poll = &dhcps->dhcps_poll;
    if (dhcps_poll->enable == true) {
        softap_ip = htonl(ip);
        start_ip = htonl(dhcps_poll->start_ip.addr);
        end_ip = htonl(dhcps_poll->end_ip.addr);

        /*config ip information can't contain local ip*/
        if ((start_ip <= softap_ip) && (softap_ip <= end_ip)) {
            dhcps_poll->enable = false;
        } else {
            /*config ip information must be in the same segment as the local ip*/
            softap_ip >>= 8;

            if (((start_ip >> 8 != softap_ip) || (end_ip >> 8 != softap_ip))
                    || (end_ip - start_ip > DHCPS_MAX_LEASE)) {
                dhcps_poll->enable = false;
            }
        }
    }

    if (dhcps_poll->enable == false) {
        local_ip = softap_ip = htonl(ip);
        softap_ip &= 0xFFFFFF00;
        temp_local_ip = local_ip &= 0xFF; // local_ip &= 0xFF;

        if (local_ip >= 0x80) {
            local_ip -= DHCPS_MAX_LEASE;
        } else {
            local_ip ++;
        }

        bzero(dhcps_poll, sizeof(*dhcps_poll));
        dhcps_poll->start_ip.addr = softap_ip | local_ip;
        dhcps_poll->end_ip.addr = softap_ip | (temp_local_ip + 0xFFFFFFFF- htonl(dhcps->dhcps_mask.addr) - 1); // dhcps_poll->end_ip.addr = softap_ip | (local_ip + DHCPS_MAX_LEASE - 1);
        dhcps_poll->start_ip.addr = htonl(dhcps_poll->start_ip.addr);
        dhcps_poll->end_ip.addr = htonl(dhcps_poll->end_ip.addr);
    }

}
......
"
Is that correct?
If not, please, provide me a document that explains how-to test patches.
Thank you.

**Comment by AxelLin** [comment]
@xueyunfei998 
Any update? This issue was marked as "Resolution: Done" 3 weeks ago, but I still cannot find the fix in any branch.

**Comment by xueyunfei998** [comment]
[dhcpserver.txt](https://github.com/espressif/esp-idf/files/10799822/dhcpserver.txt)
hi @sergioaiello 

Sorry for not replying in time.

The above is a complete pacth based on version 4.4.

**Comment by sergioaiello** [comment]
Please, let me know what to test in IDF v5.0
My last test  (about one month ago) was not successful (the patch did not solve the issue ... on the opposite I found an other problem that I did not investigate since not relevant with this case and limited time)

Is the file [dhcpserver.txt](https://github.com/espressif/esp-idf/files/10799822/dhcpserver.txt) also relevant for IDF v5.0?
Should it be tested?
Thank you

**Comment by AxelLin** [comment]
@xueyunfei998 This bug is also in v4.3: cab17c7, please backport the fix for v4.3.

**Comment by AxelLin** [comment]
@xueyunfei998 v4.3.5 still has this bug.

**Comment by xueyunfei998** [comment]
hi @sergioaiello 

The dhcp address pool allocation algorithm has been revised again. Please use the master version to test it.

hi @AxelLin 

dhcp server's new memory pool allocation algorithm has been backport to 4.3.please test

**Comment by AxelLin** [comment]
@xueyunfei998 @mhdong 

I have a question regarding the change in https://github.com/espressif/esp-lwip/commit/4f24c9baf9101634b7c690802f424b197b3bb685 ,
the commit log tells nothing about what was fixed.

Does this commit fix any issue?
If yes, why not mention it in commit log? and what was actually fixed?
If no, what is the reason to lower the retry backoff time?
