### ISSUE TITLE
[TW#15471] uart_wait_tx_done exit with buffer not empty

### ISSUE THREAD

**Issue by imotion-software** [espressif/esp-idf#1002]
We use uart_wait_tx_done to wait for serial transmission completed.
It happens sometimes that function returns immediately even though buffer is still full.

It happens normally once every hundreds of cycles. I know there's no interaction between serial and bluetooth, but we can reproduce problem only when there's an heavy traffic on Bluetooth (didn't figure out the reason).

**Comment by costaud** [comment]
Would you please provide some pieces of your uart test code? That would help a lot for us to solve this quickly.

**Comment by FayeY** [comment]
If your problem is still unsolved, please provide your test code, and feel free to reopen it.
