### ISSUE TITLE
Workarounds for TWAI Errata are disabled by default even though the documentation says otherwise (IDFGH-8590)

### ISSUE THREAD

**Issue by Delzye** [espressif/esp-idf#10037]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

The documentation states: "The software workarounds are enabled by default and it is recommended that users keep this workarounds enabled"

But when generating a new project (e.g. by using sample_project as a template in the VSCode extension), the workarounds are disabled.

**Comment by suda-morris** [comment]
The errata workaround was enabled by default since IDF5.0. I guess you're using IDF 4.4. FYI: https://github.com/espressif/esp-idf/commit/2f2df82bc5d622f4e9ad1d3c93db8284bfc06657

**Comment by brianignacio5** [comment]
You can use the `ESP-IDF: Doctor command` to generate a report in your system clipboard (just paste it in any editor) to see your current ESP-IDF version.

**Comment by Delzye** [comment]
Damn, I always forget that a doc link found via google opens as master (latest) and not stable...

Closing due to my incompetence...
