### ISSUE TITLE
Typo in wifi_enterprise README.md (IDFGH-8595)

### ISSUE THREAD

**Issue by smchan514** [espressif/esp-idf#10042]
Many thanks to the various authors for the `wifi_enterprise` example. It has been a big help to get me started with WPA-EAP using ESP32. There is however a typo in the command to generate client certificate in `README.md` in the section _Steps to create enterprise openssl certs_. The command in question is:

```
openssl ca -batch -keyfile ca.key -cert ca.pem -in client.csr -key (password) -out client.crt -extensions xpserver_ext -extfile xpextensions
```

The option `-extensions` should be `xpclient_ext` (it was correct prior to commit `cd85c79d`):

```
openssl ca -batch -keyfile ca.key -cert ca.pem -in client.csr -key (password) -out client.crt -extensions xpclient_ext -extfile xpextensions
```

In my tests where I used a Linux AP running `hostapd` version 2.9.0, having the incorrect X509 extension in the client cert will prevent `hostapd` from authenticating the client when using EAP-TLS.

Ref: https://github.com/espressif/esp-idf/blob/daf3da5e4bcd001fb339c2d5424077d819fc8051/examples/wifi/wifi_enterprise/README.md?plain=1#L74

**Comment by sarveshb14** [comment]
Hi @smchan514 , Thank you for reporting the issue.
