### ISSUE TITLE
Cannot connect to wpa2 enterprise wifi for firmware update over the air (FOTA) (IDFGH-8603)

### ISSUE THREAD

**Issue by sab240** [espressif/esp-idf#10050]
Hello,

I'm struggling to connect to a wpa2 enterprise wifi with the ota examples on git (i'm using the advanced https ota). Has anyone got an idea on how to do that? Or has a code that could help me? On menuconfig, I put the connection on wpa2 enterprise but it still doesn't ask for the idf, username and password. Then it can connect, it only shows : disconnected over and over again.

Thank you

**Comment by vik-gokhale** [comment]
hi @sab240,
Could you please enable Supplicant, mBedTLS and debug traces and share the logs for the failure?

regards,
Vikram

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to short of feedback, feel free to reopen with more updates.
