### ISSUE TITLE
Is there a way to output DAC  on esp32s3 (IDFGH-8605)

### ISSUE THREAD

**Issue by casitelwithdean** [espressif/esp-idf#10052]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Hello,I want to use DAC on esp32s3.
I built this example example->peripherals->wave_gen,but failed .it showed that it doesn't support esp32s3.
Then I bulilt this exmaple example->peripherals->i2s->i2s_dac_adc,but still failed.
So is there a way to output DAC on esp32s3?
Thanks!

**Comment by L-KAYA** [comment]
Sorry, we only have DAC peripheral on ESP32 and ESP32-S2
