### ISSUE TITLE
ESP32-S3 BLE LoadProhibited when calling esp_ble_gatts_add_char() from ESP_GATTS_ADD_CHAR_EVT (IDFGH-8636)

### ISSUE THREAD

**Issue by spkurtzweil** [espressif/esp-idf#10081]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v4.4.2

### Operating System used.

Windows

### How did you build your project?

VS Code IDE

### Development Kit.

ESP32-S3-Devkit-C1

### Power Supply used.

USB

### What is the expected behavior?

I expect it to add the characteristic, complete the function, and call the GATT callback again with a ADD_CHAR_EVT.

### What is the actual behavior?

Crashes after finishing execution of the callback and before executing the next callback.

### Steps to reproduce.

1. Enable Bluetooth in SDKConfig
2. Add target_compile_options(${COMPONENT_LIB} PRIVATE -Wno-error=missing-braces) to CMakeLists.txt
3. Build, flash, and monitor code. It will happen almost immediately after beginning execution.
4. Data structures to define GATT structure are above app_main, GATT callback is at the bottom of main.c.
//Steven Kurtzweil
//28 Oct 2022
//ESP32-S3

#include <stdio.h>
#include <string.h>
#include "sdkconfig.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "freertos/semphr.h"
#include "driver/adc.h"
#include "esp_timer.h"
// #include "esp_spi_flash.h"
#include "esp_partition.h" //partition functions used to access flash instead of spi_flash in case partition table changes
#include "esp_adc_cal.h"

#include "nvs_flash.h" //required for BT
#include "esp_bt.h"
#include "esp_bt_main.h"
#include "esp_gap_ble_api.h"
#include "esp_gatts_api.h"
#include "esp_gatt_defs.h"
#include "driver/gpio.h"

static void adc_init(const adc1_channel_t *channels, uint32_t freq, uint8_t num_channels, uint32_t max_stored_bytes, uint16_t adc1_mask, uint16_t adc2_mask, esp_adc_cal_characteristics_t *cal_data);

static void bt_init();

static void bt_set_addr();

static void gap_event_handler(esp_gap_ble_cb_event_t event, esp_ble_gap_cb_param_t *param);

static void gatt_event_handler(esp_gatts_cb_event_t event, esp_gatt_if_t gatts_if, esp_ble_gatts_cb_param_t *param);

static esp_ble_adv_data_t adv_data = {
    .set_scan_rsp = false,
    .include_name = true,
    .include_txpower = false,
    .min_interval = 0x800,
    .max_interval = 0x800,
    .appearance = 0x00,
    .manufacturer_len = 0,
    .p_manufacturer_data = NULL,
    .service_data_len = 0,
    .p_service_data = NULL,
    //.service_uuid_len = 32,
    //.p_service_data = test_service_uuid128,
    .flag = ESP_BLE_ADV_FLAG_GEN_DISC
};

static esp_ble_adv_params_t adv_param = {
    .adv_int_min = 0x800,
    .adv_int_max = 0x800,
    .adv_type = ADV_TYPE_IND,
    .own_addr_type = BLE_ADDR_TYPE_RANDOM,
    .channel_map = ADV_CHNL_ALL,
    .adv_filter_policy = ADV_FILTER_ALLOW_SCAN_ANY_CON_ANY
};

struct gatts_descr_inst {
    uint16_t descr_handle;
    esp_bt_uuid_t descr_uuid;
    esp_gatt_perm_t perm;
    esp_attr_control_t ctrl;
    esp_attr_value_t* val;
};

struct gatts_char_inst {
    uint16_t char_handle;
    esp_bt_uuid_t char_uuid;
    esp_gatt_perm_t perm;
    esp_gatt_char_prop_t property;
    esp_attr_control_t ctrl;
    esp_attr_value_t* val;
    uint8_t num_descr;
    struct gatts_descr_inst* descr[];
};

struct gatts_service_inst {
    uint16_t service_handle;
    esp_gatt_srvc_id_t service_uuid;
    esp_gatt_perm_t perm;
    uint8_t num_chars;
    struct gatts_char_inst* chars[];
};

struct gatts_profile_inst {
    uint16_t gatts_if;
    uint16_t app_id;
    uint16_t conn_id;
    uint8_t num_serv;
    struct gatts_service_inst* services[];
};

esp_attr_value_t sdt_flt_ctrl_value = {
    .attr_max_len = 0x02,
    .attr_len = 0x02,
    .attr_value = 0x0000
};

static struct gatts_char_inst sdt_flt_ctrl = {
    .char_uuid = {
        .len = ESP_UUID_LEN_128,
        .uuid = {.uuid128 = {0x78, 0x68, 0x2D, 0x53, 0x74, 0x61, 0x44, 0x49, 0x53, 0x43, 0x74, 0x69, 0x63, 0x73, 0xDA, 0xC0}}
    },
    .perm = ESP_GATT_PERM_READ,
    .property = ESP_GATT_CHAR_PROP_BIT_WRITE | ESP_GATT_CHAR_PROP_BIT_READ,
    .ctrl = ESP_GATT_AUTO_RSP,
    .val = &sdt_flt_ctrl_value,
    .num_descr = 0,
};

uint8_t rot_z_value[12] = {'1','5','0','0','.','0','0','0',' ','R','P','M'};
esp_attr_value_t sdt_attr_rot_z_value = {
    .attr_max_len = 0x60,
    .attr_len = sizeof(rot_z_value),
    .attr_value = rot_z_value
};

static struct gatts_char_inst sdt_rot_z = {
    .char_uuid = {
        .len = ESP_UUID_LEN_16, 
        .uuid = {.uuid16 = 0xFFCC}
    },
    .perm = ESP_GATT_PERM_READ,
    .property = ESP_GATT_CHAR_PROP_BIT_READ,
    .ctrl = ESP_GATT_AUTO_RSP,
    .val = &sdt_attr_rot_z_value,
    .num_descr = 0
};

static struct gatts_service_inst sdt_disc_flight_stats = {
    .service_uuid = {
        .id.uuid.len = ESP_UUID_LEN_128,
        .id.uuid.uuid = {.uuid128 = {0x78, 0x64, 0x2D, 0x53, 0x74, 0x61, 0x44, 0x49, 0x53, 0x43, 0x74, 0x69, 0x63, 0x73, 0xDA, 0xC0}},
        .is_primary = true,
        .id.inst_id = 0x00
    },
    .perm = ESP_GATT_PERM_READ,
    .num_chars = 2,
    .chars = {&sdt_rot_z,
                &sdt_flt_ctrl}
};

static struct gatts_profile_inst sdt_profile = {
    .gatts_if = ESP_GATT_IF_NONE,
    .num_serv = 1,
    .services = {&sdt_disc_flight_stats}
};

gpio_num_t max_reset = GPIO_NUM_38;
const uint64_t GPIO_MASK = 0x4000000000;

gpio_config_t discrete_in = {
    .pin_bit_mask = GPIO_MASK,
    .mode = GPIO_MODE_INPUT,
    .pull_up_en = GPIO_PULLUP_ENABLE,
    .pull_down_en = GPIO_PULLDOWN_DISABLE,
    .intr_type = GPIO_INTR_DISABLE
};

uint64_t unique_flash_ID = 0;

int app_main(void)
{
    const float ACC_RAD_M = .0691;
    const float G = 9.81;
    const float PI = 3.14159;
    const float C1 = .0000001;
    const float R1 = 1000000;
    const float R2 = 47000;
    

    const uint16_t ADC1_MASK = 0b1100000001; //set a 1 for each ADC channel you intend to use
    const uint16_t ADC2_MASK = 0b0000000000;
    const uint32_t AQUISITION_FREQ = 1000; //frequency of each ADC channel in Hz
    const uint32_t AQUISITION_PERIOD = 3;  //max period of aquisition in seconds
    const uint32_t ADC_DATA_BYTES = 4; //number of bytes stored by DMA per conversion
    const uint32_t BUFF_SIZE = 400;

    //to configure channels, change the size argument and add the enums of the channels you want
    const adc1_channel_t CHANNELS[1] = {
        ADC1_CHANNEL_0              
    };

    uint8_t num_channels = sizeof(CHANNELS)/sizeof(adc2_channel_t);
    
    uint32_t max_stored_bytes = ADC_DATA_BYTES * num_channels * AQUISITION_FREQ * AQUISITION_PERIOD;

    gpio_config(&discrete_in);

    const esp_partition_t *flight_data = esp_partition_get(esp_partition_find(ESP_PARTITION_TYPE_ANY, ESP_PARTITION_SUBTYPE_ANY, "flight_data"));

    esp_adc_cal_characteristics_t adc_cal_data = {0};

    esp_err_t ret;
    uint32_t ret_num = 0;
    uint32_t ret_num_total = 0;
    uint8_t result[BUFF_SIZE];
    memset(result, 0xcc, BUFF_SIZE);

    esp_err_t flash_err = ESP_OK;

    uint32_t temp_raw_data;
    // uint32_t temp_cal_volt;
    adc_digi_output_data_t *temp_data;
    // uint32_t temp_cal_avg;
    float rot_z;
    char float_conv_buff[8];
    uint8_t rot_z_leading_zeroes;

    //variables used to track time elapsed for certain operations
    int start_time;

    adc_init(CHANNELS, AQUISITION_FREQ, num_channels, max_stored_bytes, ADC1_MASK, ADC2_MASK, &adc_cal_data);

    esp_flash_read_unique_chip_id(flight_data->flash_chip, &unique_flash_ID);
    printf("flash ID: %llx\n", unique_flash_ID);
    bt_init();

    uint32_t raw_v_ref;

    esp_adc_cal_get_voltage(ADC_CHANNEL_9, &adc_cal_data, &raw_v_ref);
    float acc_v_0g = (float)raw_v_ref / 1000;

    // esp_adc_cal_get_voltage(ADC_CHANNEL_8, &adc_cal_data, &raw_v_ref);
    float v_supply = 2*acc_v_0g;

    float max_v = acc_v_0g;
    float v_to_out_scale = (G*3.0)/(.057*v_supply)*(60/(2*PI*ACC_RAD_M))*((R1*R1*C1)/(R1+R2))*2;
    
    printf("IDF Version: %s\n", IDF_VER);
    printf("ADC Gradient: %u\n", adc_cal_data.coeff_a);
    printf("Offset Voltage: %f\n", acc_v_0g);
    printf("Supply Voltage: %f\n", v_supply);

    //attempt to erase flash in flight data partition
    flash_err = esp_partition_erase_range(flight_data, 0, (max_stored_bytes / 4096) * 4096 + 4096);
    
    //if erase successful begin data aquisition
    if (flash_err == ESP_OK) {

        start_time = esp_timer_get_time(); //get_time is time since boot in uS
        
        adc_digi_start(); //start DMA conversion
        printf("starting data aquisition\n");

        //this section will read the DMA buffer every 100 ms and write the average value to the rot_z_value variable
        while (1) {
            start_time = esp_timer_get_time();
            adc_digi_read_bytes(result, BUFF_SIZE, &ret_num, 10);
            temp_data = (void *) &result[0];
            temp_raw_data = temp_data->type2.data;
            // temp_cal_avg = esp_adc_cal_raw_to_voltage(temp_raw_data, &adc_cal_data);
            for (int i = 4; i < ret_num; i+= 4) {
                temp_data = (void *) &result[i];
                temp_raw_data = temp_data->type2.data;
                if (gpio_get_level(max_reset) ==  0) max_v = acc_v_0g;
                if ((float)esp_adc_cal_raw_to_voltage(temp_raw_data, &adc_cal_data)/1000 > max_v) max_v = (float)esp_adc_cal_raw_to_voltage(temp_raw_data, &adc_cal_data)/1000;
                // temp_cal_avg += esp_adc_cal_raw_to_voltage(temp_raw_data, &adc_cal_data);
                // temp_cal_avg /= 2;
            }
            //printf("max_input: %f reset_state: %d\n", max_v, gpio_get_level(max_reset));
            rot_z = v_to_out_scale * (max_v-acc_v_0g);
            // rot_z = (float)temp_cal_avg/1000;
            snprintf(float_conv_buff, sizeof(rot_z_value)+1, "%4.3f", rot_z);
            if (float_conv_buff[5] == 0x00) { //case where string is 5 chars long
                rot_z_leading_zeroes = 3;
                rot_z_value[0] = ' ';
                rot_z_value[1] = ' ';
                rot_z_value[2] = ' ';
            }
            else if (float_conv_buff[6] == 0x00) { //case where string is 6 chars long
                rot_z_leading_zeroes = 2;
                rot_z_value[0] = ' ';
                rot_z_value[1] = ' ';
            }
            else if (float_conv_buff[7] == 0x00) { //case where string is 7 chars long
                rot_z_leading_zeroes = 1;
                rot_z_value[0] = ' ';
            }
            else { //case where string is 8 chars long (experimentally, string is never less than 5 chars)
                rot_z_leading_zeroes = 0;
            }
            for (int i = rot_z_leading_zeroes; i < 8; i++) {
                rot_z_value[i] = (char) float_conv_buff[i-rot_z_leading_zeroes];                
            }
            // printf("calc value %s\n", rot_z_value);
            esp_ble_gatts_set_attr_value(sdt_rot_z.char_handle, sizeof(rot_z_value), rot_z_value);
            while(esp_timer_get_time() - start_time < 100000) vTaskDelay(1);
        }

        adc_digi_stop(); //stop DMA conversion

        // printf("Starting %d second data aquisition period\n", AQUISITION_PERIOD);

        // vTaskDelay(AQUISITION_PERIOD*1000/portTICK_PERIOD_MS); //simply wait for the set time period while the DMA fills up the memory buffer
        //NOTE: I have discovered that tracking time with vTaskDelay is not as accurate as esp_timer

        

        // printf("Done! Elapsed time: %f seconds\n", (float) (esp_timer_get_time() - start_time) / 1000000);

        // start_time = esp_timer_get_time();

        //adc_digi_read_bytes fetches data from the DMA buffer and puts it in another buffer (result)
        //it will not return ESP_OK if the buffer is empty
        //in case something breaks, there's also a max number of bytes it can read
        // while (adc_digi_read_bytes(result, BUFF_SIZE, &ret_num, 10) == ESP_OK && ret_num_total < max_stored_bytes) {
        //     //after fetching a small number of bytes from the DMA buffer, transfer those to flash, starting at the partition start
        //     esp_partition_write_raw(flight_data, ret_num_total, result, BUFF_SIZE);
        //     ret_num_total += ret_num;
        //     //loop until DMA buffer is empty
        // }

        printf("Wrote %u bytes to flash in %f seconds\n", ret_num_total, (float) (esp_timer_get_time() - start_time) / 1000000);

        //this delay exists to give me time to read the above outputs before a bunch of data is vomited to the terminal
        vTaskDelay(5000/portTICK_PERIOD_MS);

        // while(1) {
        // //the number of bytes transferred to flash is known, simply iterate through those 4 bytes at a time and print the ADC data
        //     for (int i = 0; i < ret_num_total; i += 4) {
        //         esp_partition_read_raw(flight_data, i, (void*) &temp_raw_data, sizeof(uint32_t));
        //         temp_data = (void*) &temp_raw_data;
        //         temp_cal_volt = esp_adc_cal_raw_to_voltage(temp_raw_data, &adc_cal_data);
        //         //printf ("%d, RPM: %f\n", i/4, (float)temp_cal_volt/1000/ACC_RAD_M*9.5493);
        //     }
        // // vTaskDelay(5000/portTICK_PERIOD_MS);
        //}

        

    }
    else {
        printf("Error erasing flash %s\n", esp_err_to_name(flash_err));
    }

    ret = adc_digi_deinitialize();
    esp_ble_gap_stop_advertising();
    assert(ret == ESP_OK);

    return 0;
}

static void adc_init(const adc1_channel_t *channels, uint32_t freq, uint8_t num_channels, uint32_t max_stored_bytes, uint16_t adc1_mask, uint16_t adc2_mask, esp_adc_cal_characteristics_t *cal_data) {
    adc_digi_convert_mode_t mode = ADC_CONV_SINGLE_UNIT_1; //enum of DMA conversion modes
    adc_digi_output_format_t data_format = ADC_DIGI_OUTPUT_FORMAT_TYPE2; //enum of data type (only type 2 supported on ESP32-S3)

    //declare a struct of type adc_digi_config_t that sets DMA parameters
    adc_digi_init_config_t adc_dma_config = {
        .max_store_buf_size = max_stored_bytes, //as far as I understand, the number of bytes that are stored in memory without being read
        .conv_num_each_intr = 6*num_channels, //how many bytes can be converted during 1 interrupt (whatever that means)
        .adc1_chan_mask = adc1_mask,
        .adc2_chan_mask = adc2_mask,
    };
    adc_digi_initialize(&adc_dma_config); //pass the config struct to the initialize function

    adc_digi_pattern_config_t adc_pattern[SOC_ADC_PATT_LEN_MAX] = {0}; //initialize array of "patterns" with a max length specified by the constant provided by the driver
    
    //fill the pattern array for each channel being used
    for (int i = 0; i < num_channels; i++) {
        uint8_t unit = channels[i] >> 3 & 0x1;  //this is what the example does to parse the unit and channel num from the enum
        uint8_t ch = channels[i] & 0x7;         //Seems to be masking a 4 bit number where bit 3 is the unit number and bits 2-0 are the channel number
        adc_pattern[i].atten = ADC_ATTEN_DB_11; //set attenuation that will allow measurement up to 2.5V (S2) and 3.1V (S3)
        adc_pattern[i].channel = ch;
        adc_pattern[i].unit = unit;
        adc_pattern[i].bit_width = SOC_ADC_DIGI_MAX_BITWIDTH; //width of data a given by the driver (S3 = 12 bit)
    }

    //declare a struct of type adc_digi_configuration_t that sets ADC controller parameters
    adc_digi_configuration_t adc_ctr_config = {
        .conv_limit_en = true,
        .conv_limit_num = 255,
        .pattern_num = num_channels,
        .adc_pattern = adc_pattern,
        .sample_freq_hz = num_channels*freq, //make each channel sample at 1kHz
        .conv_mode = mode,
        .format = data_format,
    };
    adc_digi_controller_configure(&adc_ctr_config); //pass the config to the initialize function

    esp_adc_cal_characterize(ADC_UNIT_1, ADC_ATTEN_DB_11, ADC_WIDTH_BIT_12, 1100, cal_data); //fetch calibration data  
}

static void bt_init() {
    esp_err_t bt_err;

    

    //NVS is required for bluetooth, this is what the example program does
    bt_err = nvs_flash_init();
    if (bt_err == ESP_ERR_NVS_NO_FREE_PAGES || bt_err == ESP_ERR_NVS_NEW_VERSION_FOUND) {
        ESP_ERROR_CHECK(nvs_flash_erase());
        bt_err = nvs_flash_init();
    }
    
    esp_bt_controller_config_t bt_cfg = BT_CONTROLLER_INIT_CONFIG_DEFAULT();
    
    bt_err = esp_bt_controller_init(&bt_cfg);
    if (bt_err) {
        printf("Error initializing BT controller: %s\n", esp_err_to_name(bt_err));
        return;
    }
    bt_err = esp_bt_controller_enable(ESP_BT_MODE_BLE);
    if(bt_err) {
        printf("Error enabling BT controller: %s\n", esp_err_to_name(bt_err));
        return;
    }
    bt_err = esp_bluedroid_init();
    if (bt_err) {
        printf("Error initializing Bluedroid: %s\n", esp_err_to_name(bt_err));
        return;
    }
    bt_err = esp_bluedroid_enable();
    if (bt_err) {
        printf("Error enabling Bluedroid: %s\n", esp_err_to_name(bt_err));
        return;
    }

    esp_ble_gap_register_callback(gap_event_handler);

    esp_ble_gatts_register_callback(gatt_event_handler);

    esp_ble_gatts_app_register(0);

}

static void bt_set_addr() {
    esp_ble_gap_set_device_name("Stadisctics");
    esp_bd_addr_t bt_addr = {((unique_flash_ID & 0xFF0000000000) >> 40) | 0xC0, 
                                (unique_flash_ID & 0xFF00000000) >> 32, 
                                  (unique_flash_ID & 0xFF000000) >> 24, 
                                    (unique_flash_ID & 0xFF0000) >> 16, 
                                      (unique_flash_ID & 0xFF00) >> 8, 
                                         unique_flash_ID & 0xFF}; //set device address to lower 48 bits of flash ID (should be somewhat unique)
                                                        //but force upper 2 bits to be 11 (static random address)
    esp_ble_gap_set_rand_addr(bt_addr);
}

static void gap_event_handler(esp_gap_ble_cb_event_t event, esp_ble_gap_cb_param_t *param) {
    switch (event) {
    case ESP_GAP_BLE_SET_STATIC_RAND_ADDR_EVT:
        printf("Rand addr set, status %d\n", param->ext_adv_set_rand_addr.status);
        esp_ble_gap_config_adv_data(&adv_data);
        break;
    case ESP_GAP_BLE_ADV_DATA_SET_COMPLETE_EVT:
        printf("adv data set, status %d\n", param->ext_adv_set_rand_addr.status);
        esp_ble_gap_start_advertising(&adv_param);
        break;
    case ESP_GAP_BLE_ADV_START_COMPLETE_EVT:
        printf("adv started, status %d\n", param->ext_adv_set_rand_addr.status);
        break;
    case ESP_GAP_BLE_ADV_STOP_COMPLETE_EVT:
        printf("adv stopped, status %d\n", param->ext_adv_set_rand_addr.status);
        break;
    default:
        break;
    }
}

static void gatt_event_handler(esp_gatts_cb_event_t event, esp_gatt_if_t gatts_if, esp_ble_gatts_cb_param_t *param){
    esp_err_t gatt_err = 0;

    static uint8_t s = 0;
    static uint8_t c;
    static uint8_t d;

    switch (event) {
    case ESP_GATTS_REG_EVT:
        if (param->reg.status == ESP_GATT_OK) {
            sdt_profile.gatts_if = gatts_if; 

            printf("creating service %d\n", s);
            esp_ble_gatts_create_service(gatts_if, 
                                        &sdt_profile.services[s]->service_uuid, 
                                        s+20);            
        }
        else {
            printf ("error reg profile, status %d\n", param->reg.status); 
        }
        break;
    case ESP_GATTS_CREATE_EVT:
        sdt_profile.services[s]->service_handle = param->create.service_handle;
        esp_ble_gatts_start_service(param->create.service_handle);
        if (gatt_err) printf("error starting serv: %s\n", esp_err_to_name(gatt_err));
        break;
    case ESP_GATTS_START_EVT: {
        c = 0;
        printf("Started serv 0x%x\n", param->start.service_handle);
        printf("adding char %d\n", c);
        gatt_err = esp_ble_gatts_add_char(sdt_profile.services[s]->service_handle, 
                                            &sdt_profile.services[s]->chars[c]->char_uuid, 
                                            sdt_profile.services[s]->chars[c]->perm, 
                                            sdt_profile.services[s]->chars[c]->property, 
                                            sdt_profile.services[s]->chars[c]->val, 
                                            &sdt_profile.services[s]->chars[c]->ctrl);
        if (gatt_err) printf("error adding char: %s\n", esp_err_to_name(gatt_err));    
        break;
    }
    case ESP_GATTS_ADD_CHAR_EVT:
        printf("entered add char evt\n");
        sdt_profile.services[s]->chars[c]->char_handle = param->add_char.attr_handle;
        printf("Added char 0x%x\n", param->add_char.attr_handle);
        if (sdt_profile.services[s]->chars[c]->num_descr) {
            d = 0;
            printf("adding descr %d\n", d);
            gatt_err = esp_ble_gatts_add_char_descr(sdt_profile.services[s]->service_handle,
                                                    &sdt_profile.services[s]->chars[c]->descr[d]->descr_uuid, 
                                                    sdt_profile.services[s]->chars[c]->descr[d]->perm, 
                                                    sdt_profile.services[s]->chars[c]->descr[d]->val, 
                                                    &sdt_profile.services[s]->chars[c]->descr[d]->ctrl);
            if (gatt_err) printf("error adding char desc: %s\n", esp_err_to_name(gatt_err));
        }
        else if (c < sdt_profile.services[s]->num_chars - 1) {
            ++c;
            printf("adding char %d\n", c);
            gatt_err = esp_ble_gatts_add_char(sdt_profile.services[s]->service_handle, 
                                                &sdt_profile.services[s]->chars[c]->char_uuid, 
                                                sdt_profile.services[s]->chars[c]->perm, 
                                                sdt_profile.services[s]->chars[c]->property, 
                                                sdt_profile.services[s]->chars[c]->val, 
                                                &sdt_profile.services[s]->chars[c]->ctrl);
            if (gatt_err) printf("error adding char: %s\n", esp_err_to_name(gatt_err));
        }
        else if (s < sdt_profile.num_serv - 1) {
            ++s;
            printf("creating service %d\n", s);
            esp_ble_gatts_create_service(gatts_if, 
                                        &sdt_profile.services[s]->service_uuid, 
                                        s+20);
        }
        else {
            bt_set_addr();
        }
        printf("exited add char evt\n");
        break;
    case ESP_GATTS_ADD_CHAR_DESCR_EVT: {
        sdt_profile.services[s]->chars[c]->descr[d]->descr_handle = param->add_char_descr.attr_handle;
        printf("Added descr 0x%x\n", param->add_char_descr.attr_handle);
        if (d < sdt_profile.services[s]->chars[c]->num_descr - 1) {
            ++d;
            printf("adding descr %d\n", d);
            gatt_err = esp_ble_gatts_add_char_descr(sdt_profile.services[s]->service_handle,
                                                    &sdt_profile.services[s]->chars[c]->descr[d]->descr_uuid, 
                                                    sdt_profile.services[s]->chars[c]->descr[d]->perm, 
                                                    sdt_profile.services[s]->chars[c]->descr[d]->val, 
                                                    &sdt_profile.services[s]->chars[c]->descr[d]->ctrl);
            if (gatt_err) printf("error adding char desc: %s\n", esp_err_to_name(gatt_err));
        }
        else if (c < sdt_profile.services[s]->num_chars - 1) {
            ++c;
            printf("adding char %d\n", c);
            gatt_err = esp_ble_gatts_add_char(sdt_profile.services[s]->service_handle, 
                                                &sdt_profile.services[s]->chars[c]->char_uuid, 
                                                sdt_profile.services[s]->chars[c]->perm, 
                                                sdt_profile.services[s]->chars[c]->property, 
                                                sdt_profile.services[s]->chars[c]->val, 
                                                &sdt_profile.services[s]->chars[c]->ctrl);
            if (gatt_err) printf("error adding char: %s\n", esp_err_to_name(gatt_err));
        }
        else if (s < sdt_profile.num_serv - 1) {
            ++s;
            printf("creating service %d\n", s);
            esp_ble_gatts_create_service(gatts_if, 
                                        &sdt_profile.services[s]->service_uuid, 
                                        s+20);
        }
        else {
            bt_set_addr();
        }
        break;
    }
    case ESP_GATTS_CONNECT_EVT: {
        esp_ble_conn_update_params_t conn_params = {0};
        memcpy(conn_params.bda, param->connect.remote_bda, sizeof(esp_bd_addr_t));
        conn_params.latency = 0;
        conn_params.max_int = 0x30;
        conn_params.min_int = 0x10;
        conn_params.timeout = 400;
        printf("Connected, conn_id %d, remote %02x:%02x:%02x:%02x:%02x:%02x \n",  
             param->connect.conn_id,  
             param->connect.remote_bda[0],  
             param->connect.remote_bda[1],  
             param->connect.remote_bda[2],  
             param->connect.remote_bda[3],  
             param->connect.remote_bda[4],  
             param->connect.remote_bda[5]);
        sdt_profile.conn_id = param->connect.conn_id;
        esp_ble_gap_update_conn_params(&conn_params);
        break;
    }
    case ESP_GATTS_DISCONNECT_EVT: 
        printf("Disconnected...\n");
        esp_ble_gap_start_advertising(&adv_param);

    default:
        break;
    }

}

### Debug Logs.

```plain
Rebooting...
ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0xc (RTC_SW_CPU_RST),boot:0x8 (SPI_FAST_FLASH_BOOT)
Saved PC:0x40375850
0x40375850: esp_restart_noos at C:/Users/spkur/esp/esp-idf/components/esp_system/port/soc/esp32s3/system_internal.c:143 (discriminator 1)

SPIWP:0xee
mode:DIO, clock div:1
load:0x3fce3808,len:0x1650
load:0x403c9700,len:0xbb8
load:0x403cc700,len:0x2f88
entry 0x403c9954
I (29) boot: ESP-IDF v4.4.2 2nd stage bootloader
I (29) boot: compile time 17:46:30
I (29) boot: chip revision: 0
I (31) boot.esp32s3: Boot SPI Speed : 80MHz
I (36) boot.esp32s3: SPI Mode       : DIO
I (40) boot.esp32s3: SPI Flash Size : 8MB
I (45) boot: Enabling RNG early entropy source...
I (50) boot: Partition Table:
I (54) boot: ## Label            Usage          Type ST Offset   Length
I (61) boot:  0 nvs              WiFi data        01 02 00009000 00004000
I (69) boot:  1 phy_init         RF data          01 01 0000f000 00001000
I (76) boot:  2 code             factory app      00 00 00010000 00100000
I (84) boot:  3 flight_data      Unknown data     01 06 00110000 0058c000
I (91) boot: End of partition table
I (95) esp_image: segment 0: paddr=00010020 vaddr=3c070020 size=1c0b8h (114872) map
I (124) esp_image: segment 1: paddr=0002c0e0 vaddr=3fc95470 size=039d0h ( 14800) load
I (128) esp_image: segment 2: paddr=0002fab8 vaddr=40374000 size=00560h (  1376) load
I (130) esp_image: segment 3: paddr=00030020 vaddr=42000020 size=62ea0h (405152) map
I (211) esp_image: segment 4: paddr=00092ec8 vaddr=40374560 size=10f04h ( 69380) load
I (227) esp_image: segment 5: paddr=000a3dd4 vaddr=50000000 size=00010h (    16) load
I (234) boot: Loaded app from partition at offset 0x10000
I (234) boot: Disabling RNG early entropy source...
I (247) cpu_start: Pro cpu up.
I (247) cpu_start: Starting app cpu, entry point is 0x40375288
0x40375288: call_start_cpu1 at C:/Users/spkur/esp/esp-idf/components/esp_system/port/cpu_start.c:160

I (225) cpu_start: App cpu up.
I (261) cpu_start: Pro cpu start user code
I (261) cpu_start: cpu freq: 160000000
I (261) cpu_start: Application information:
I (264) cpu_start: Project name:     code
I (269) cpu_start: App version:      d42a3db-dirty
I (274) cpu_start: Compile time:     Oct 30 2022 21:50:01
I (280) cpu_start: ELF file SHA256:  e2adf6ee14e03f7a...
I (286) cpu_start: ESP-IDF:          v4.4.2
I (291) heap_init: Initializing. RAM available for dynamic allocation:
I (298) heap_init: At 3FC9C600 len 00043A00 (270 KiB): D/IRAM
I (305) heap_init: At 3FCE0000 len 0000EE34 (59 KiB): STACK/DRAM
I (311) heap_init: At 3FCF0000 len 00008000 (32 KiB): DRAM
I (318) heap_init: At 600FE000 len 00002000 (8 KiB): RTCRAM
I (325) spi_flash: detected chip: generic
I (329) spi_flash: flash io: dio
I (333) sleep: Configure to isolate all GPIO pins in sleep state
I (340) sleep: Enable automatic switching of GPIO sleep configuration
I (347) coexist: coexist rom version e7ae62f
I (352) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.
I (372) gpio: GPIO[38]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 
I (382) gpio: GPIO[1]| InputEn: 0| OutputEn: 0| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 
I (382) gpio: GPIO[9]| InputEn: 0| OutputEn: 0| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 
I (392) gpio: GPIO[10]| InputEn: 0| OutputEn: 0| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 
flash ID: 123b0c151c80b5c7
I (412) BT_INIT: BT controller compile version [05195c9]
I (412) phy_init: phy_version 503,13653eb,Jun  1 2022,17:47:08
I (452) system_api: Base MAC address is not set
I (462) system_api: read default base MAC address from EFUSE
I (462) BT_INIT: Bluetooth MAC: 60:55:f9:f5:25:fa

creating service 0
Started serv 0x28
adding char 0
entered add char evt
Added char 0x2a
adding char 1
exited add char evt
Guru Meditation Error: Core  0 panic'ed (LoadProhibited). Exception was unhandled.

Core  0 register dump:
PC      : 0x40056f9c  PS      : 0x00060f30  A0      : 0x82027e3e  A1      : 0x3fced2b0
A2      : 0x3fced8d4  A3      : 0x00000000  A4      : 0x00000002  A5      : 0x3fced8d4  
A6      : 0x69744353  A7      : 0x00000000  A8      : 0x00000000  A9      : 0x3fced280
A10     : 0x3fced8d4  A11     : 0x00000002  A12     : 0x00060120  A13     : 0x00060123  
A14     : 0x69744353  A15     : 0xc0da7363  SAR     : 0x0000001d  EXCCAUSE: 0x0000001c
EXCVADDR: 0x00000000  LBEG    : 0x40056f5c  LEND    : 0x40056f72  LCOUNT  : 0xffffffff  


Backtrace:0x40056f99:0x3fced2b0 |<-CORRUPTED




ELF file SHA256: e2adf6ee14e03f7a
```

**Comment by xiewenxiang** [comment]
Hi @spkurtzweil 
I cann't access this URL https://github.com/spkurtzweil/Senior-Design-Project/blob/39ddd83f439d7b89f54378004723c76781c0be72/Microcontroller/code/main/main.c

**Comment by spkurtzweil** [comment]
Apologies. Having permissions issues with that repository. Copied the code directly. I'm very inexperienced with github, so sorry in advance for formatting or procedural errors.

**Comment by xiewenxiang** [comment]
@spkurtzweil You can paste your code directly into the attachment.

**Comment by xiewenxiang** [comment]
The attachment is sample code.

I found a problems in the code you provided, the `attr_value` point will be `NULL`:

```c
esp_attr_value_t sdt_flt_ctrl_value = {
    .attr_max_len = 0x02,
    .attr_len = 0x02,
    .attr_value = 0x0000
};
```

```c
typedef struct
{
    uint16_t attr_max_len;                                  /*!<  attribute max value length */
    uint16_t attr_len;                                      /*!<  attribute current value length */
    uint8_t  *attr_value;                                   /*!<  the pointer to attribute value */
} esp_attr_value_t;
```


[gatts_demo.c.zip](https://github.com/espressif/esp-idf/files/9899804/gatts_demo.c.zip)

**Comment by spkurtzweil** [comment]
Gah so simple. I was looking in the completely wrong place.

That fixed it, thanks.
