### ISSUE TITLE
Change LWIP_MAX_SOCKETS value or error message about it (IDFGH-8663)

### ISSUE THREAD

**Issue by stonefoxes** [espressif/esp-idf#10108]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Hello, I want to suggest more straightforward number for `CONFIG_LWIP_MAX_SOCKETS`.

Steps to reproduce:
- `idf.py menuconfig` inside project
- set `CONFIG_LWIP_MAX_SOCKETS` to 16
- set `httpd_config_t` with `max_open_sockets = 16`

Expected behavior:
16 sockets are available for user needs

Actual behavior:
Got error
```
httpd: Configuration option max_open_sockets is too large (max allowed 13)
Either decrease this or configure LWIP_MAX_SOCKETS to a larger value
```

Proposal:
Set higher bound for `CONFIG_LWIP_MAX_SOCKETS` in `menuconfig` to 13 or change error message according to comment from httpd_start() which states that 3 sockets used for internal needs of ESP.

**Comment by Xiehanxin** [comment]
hi @stonefoxes   please let me know your IDF version, as I try the release/v4.4, the range is 1 to 16
![image](https://user-images.githubusercontent.com/37785066/201311109-b73f2c9b-5f78-4303-b11c-81388c00bc6f.png)
and if you use early version, you can change it by youreself in componts/lwip/kconifg to change the range to 16
