### ISSUE TITLE
BLE Scanner example is not scanning continuously (IDFGH-8656)

### ISSUE THREAD

**Issue by mohamed-jasim** [espressif/esp-idf#10102]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

IDF-Version : 4.4.2
SoC : ESP32-C3
I've two esp32-c3 dev kit. In one of them I flashed gatt_server example and gatt_client example in the second. gatt server is advertising with 40ms interval and gat client is scanning with 60ms scan window and 60ms scan interval. Also scan duration 0 for infinite scanning. With this configuration gattc should find gatts 16 times in a second ideally. But it is taking more than 30 seconds to detect after the first scan result event. Need help in solving this.
Config
====
![image](https://user-images.githubusercontent.com/57757243/199661796-76877ff7-2cdf-417c-8edd-7f5c9596e1e9.png)

Logs
===
![Screenshot (804)](https://user-images.githubusercontent.com/57757243/199661873-3702e45b-0819-43dc-94ef-37dab000ae3f.png)

**Comment by xiewenxiang** [comment]
@mohamed-jasim 
Please turn off `BLE Scan Duplicate Options` and try is again.

```c
make menuconfig -> component config -> Bluetooth -> Controller options -> BLE Scan Duplicate Options
```

**Comment by mohamed-jasim** [comment]
@xiewenxiang BLE duplicate scanning was disabled by default in SDK config
![image](https://user-images.githubusercontent.com/57757243/199684373-e58d50e4-8b81-4df4-b73a-01f780886d28.png)
But was enabled in scan params of example code. After disabling in code, the scan result was coming in expected interval.

**Comment by xiewenxiang** [comment]
Yes, there is also a scan duplicate option in scan parameters.

**Comment by mohamed-jasim** [comment]
Correct me if I'm wrong. In my understanding scan duplicate is applicable for a particular scan window. And this is to restrict multiple appearances of a device which is having shorter advertising interval in a bigger scan window. So this duplicate mac id filter enabled shouldn't delay the scan result event. In my case my advertiser is advertising in 1000ms and the scanner is detecting the advertiser in 30 seconds and more

**Comment by mohamed-jasim** [comment]
I'm able to see multiple events for MAC IDs in same scan window even after enabling Duplicate filtering for mac id. Attaching the scan params, config and output logs
![Screenshot (812)](https://user-images.githubusercontent.com/57757243/200791209-559cc399-4a61-473e-bd47-ecc119aa4545.png)
![Screenshot (811)](https://user-images.githubusercontent.com/57757243/200791243-f257e1df-710e-498b-b83d-48d3aadb3e3c.png)

**Comment by xiewenxiang** [comment]
If enable duplicate scan filtering, it's not mean the same device will be reported only once per scan window. It just means that the same device will be reported only once durning a certain time interval.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to short of feedback, feel free to reopen with more updates. Thanks.
