### ISSUE TITLE
[TW#15677] RMT channel 0 with full 512x32-bit memory fails

### ISSUE THREAD

**Issue by loboris** [espressif/esp-idf#1011]
I have an issue when using RMT channel 0 with 8 memory blocks (512x32-bit). The operation fails with **"RMT EVT THRESH ERR"** error.
I think it is caused by the bug in **rmt_set_tx_thr_intr_en** function (_esp-idf/components/driver/rmt.c_)

Here is the short analysis of the problem:

**mem_block_num** config option sets the number of the memory blocks (64*32 bits) to be usesd for the RMT channel.
> Channel0 can use at most 8 blocks of memory, accordingly channel7 can only use one memory block.

If we use 8 memory blocks for the channel 0, it passes the check in **rmt_config()** (_rmt.c_, line 393):
> RMT_CHECK((mem_cnt + channel <= 8 && mem_cnt > 0), RMT_MEM_CNT_ERROR_STR, ESP_ERR_INVALID_ARG);

In function **rmt_write_items()** (_rmt.c_, line 721) _item_sub_len_ is calculated to the value of **256** (8*64 /  2).
> int block_num = RMT.conf_ch[channel].conf0.mem_size;
int item_block_len = block_num * RMT_MEM_ITEM_NUM;
int item_sub_len = block_num * RMT_MEM_ITEM_NUM / 2;

**rmt_set_tx_thr_intr_en(channel, 1, item_sub_len)** function is called (_rmt.c_, line 733) with that value, and **fails** because of the the check (_rmt.c_, line 354):
> RMT_CHECK(evt_thresh < 256, "RMT EVT THRESH ERR", ESP_ERR_INVALID_ARG);

If the check is changed to:
`RMT_CHECK(evt_thresh `**<=**` 256, "RMT EVT THRESH ERR", ESP_ERR_INVALID_ARG);`
everything works as expected.

**Comment by FayeY** [comment]
Please have a try with the latest IDF, and feel free to reopen it if your problem is still unsolved.
