### ISSUE TITLE
idf.py coredump-info --help command is not working on  ESP IDF 4.4.1 

### ISSUE THREAD

**Issue by Noushadalik** [espressif/esp-idf#10124]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

V4.4.1

### Operating System used.

Windows

### How did you build your project?

VS Code IDE

### If you are using Windows, please specify command line type.

PowerShell

### Development Kit.

ESP32-WROOM-32D

### Power Supply used.

External 3.3V

### What is the expected behavior?

PS C:\Users\rhmna\esp_wkspce\test_core_dump\template-app> idf.py coredump-info --help 
while running this command  to get more details on usage

### What is the actual behavior?

PS C:\Users\rhmna\esp_wkspce\test_core_dump\template-app> idf.py coredump-info --help
Usage: idf.py coredump-info [OPTIONS]

  Execute targets that are not explicitly known to idf.py

Options:
  --help  Show this message and exit.

### Steps to reproduce.

1. Open powerShell terminal in vscode
2. "idf.py coredump-info --help"   Run this command

### Debug Logs.

```plain
PS C:\Users\rhmna\esp_wkspce\test_core_dump\template-app> idf.py coredump-info --help
Usage: idf.py coredump-info [OPTIONS]

  Execute targets that are not explicitly known to idf.py

Options:
  --help  Show this message and exit.
```

**Comment by dobairoland** [comment]
Hi @Noushadalik. I assume you are reading this page: https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/core_dump.html which is for the upcoming ESP-IDF v5.1 version. This command was introduced just recently and not available in your version of ESP-IDF.

You can use `espcoredump.py` for v4.4 as per the instructions on this page: https://docs.espressif.com/projects/esp-idf/en/v4.4.2/esp32/api-guides/core_dump.html

(Note that there is dropdown menu box at the documentation page - in the top left corner - to select between ESP-IDF versions)

**Comment by Noushadalik** [comment]
Thanks
