### ISSUE TITLE
Generic debug log not working with SPIFFS 

### ISSUE THREAD

**Issue by BertaViktor** [espressif/esp-idf#1013]
Hi!
Debug log not working with SPIFFS when enabled.
Reason: in spiffs_config.h there is typing error.
CONGIG_SPIFFS... instead of CONFIG_SPIFFS...
Thx!

Viktor

**Comment by me-no-dev** [comment]
Thanks for reporting :) bugfix coming

**Comment by igrr** [comment]
Fixed in https://github.com/espressif/esp-idf/commit/14b12a27cf8072f38bda7c5dbdc8ed1e5c40583d.
