### ISSUE TITLE
Enable Bluetooth Legacy Pairing during runtime (IDFGH-8706)

### ISSUE THREAD

**Issue by pad52** [espressif/esp-idf#10148]
### Is your feature request related to a problem?

In case we would like to enable the fixed PIN pairing mode (AKA Legacy Pairing) in Bluetooth Classic the only way is disabling the Secure simple pairing in the sdkconfig.

In an application where I need to change the pairing method during runtime (enabling or disabling the fixed PIN code with a jumper/configuration/whatever) the only way I could achieve this is building my program two times: 
- one program has the CONFIG_BT_SSP_ENABLED enabled and one don't.
- then I exchange the programs during runtime using OTA API and reset my esp.

### Describe the solution you'd like.

I would like to call a function to enable or disable CONFIG_BT_SSP_ENABLED: not a macro!

**Comment by boblane1** [comment]
Hi @pad52,

We have added this feature in release/v5.2, you can choose one of the pairing mode at run time by calling `esp_bluedroid_init_with_cfg`.

**Comment by pad52** [comment]
Wow! Thank you that's amazing!
