### ISSUE TITLE
esp_mqtt_client_enqueue, len parameter documentation and behaviour is in conflict (IDFGH-8725)

### ISSUE THREAD

**Issue by tpataky** [espressif/esp-idf#10166]
The documentation states that if the `len` parameter is set to 0, length is calculated from payload string. This is clearly not the case, at least not in version 4.4.2. Either the documentation need to be updated or the code.

**Comment by euripedesrocha** [comment]
Hi @tpataky, thanks for reporting. This is a known issue that was fixed in 4.4.3.
