### ISSUE TITLE
BLE communication speed is random. (IDFGH-8738)

### ISSUE THREAD

**Issue by hyojincha** [espressif/esp-idf#10178]
I created a loop below the BLE GATTS server example and executed esp_ble_gatts_send_indicate every 100mS.
Each time the power is turned on or the ESP is reset, the communication speed seems to change.
When communication is good, data is received relatively evenly every 100mS to the Android phone.
When communication is unstable, 100~500mS randomly comes in. At this time, there is a phenomenon that packets that have not been transmitted before are received at the same time.

It's not a problem with the connection process, but the performance is different every time the power is turned on or reset. In both cases, the logo is the same, so I can't find a difference.

**Comment by xiewenxiang** [comment]
BLE's communication mechanism is based on connection intervals, Every connection interval, the matser will initiate a packet, and then the slave will reply to a packet. If who have data to be transferred, then the PDU will be carried. 

Therefore, the communication rate and delay, mainly depends on these aspects:

1. connection parameters, longer connection interval can slow down the communication rate, and different phones have different default connection parameters
2. MTU size, If the MTU is too small, the long packet will be divided and sent multiple times
3. Is there 2.4G wireless interference？ otherwise there will be too much retransmission

**Comment by hyojincha** [comment]
> BLE's communication mechanism is based on connection intervals, Every connection interval, the matser will initiate a packet, and then the slave will reply to a packet. If who have data to be transferred, then the PDU will be carried.
> 
> Therefore, the communication rate and delay, mainly depends on these aspects:
> 
> 1. connection parameters, longer connection interval can slow down the communication rate, and different phones have different default connection parameters
> 2. MTU size, If the MTU is too small, the long packet will be divided and sent multiple times
    The data sent by the ESP32 is currently less than 10 bytes for testing purposes. The problem occurs regardless of the MTU size.
> 3. Is there 2.4G wireless interference？ otherwise there will be too much retransmission
   Yes. There is 2.4G wireless interference. However, if you reset it when things go wrong, communication may work well. It has nothing to do with whether or not pairing is reconnected, and when it works perfectly, if you reset it, the performance will drop again afterwards. When performance is slow, pairing also doesn't work well, logo says "lld_pdu_get_tx_flush_nb HCI packet count mismatch (0, 1)"
RF calibration is fully calibrated every time. There may be a problem with the calibration process.

**Comment by xiewenxiang** [comment]
Could you make this change and test it again:

1. Update connection params(conn interval: 12, latency: 0, timeout: 400)  after the connection has been established. Use the API:
```c
esp_err_t esp_ble_gap_update_conn_params(esp_ble_conn_update_params_t *params);
```

2. Add a flow control mechanism to send indicate
After sending a indicate package, wait until the confirm event (`ESP_GATTS_CONF_EVT`) comes back before sending the next package.

If the above two methods can not be improved, I hope to get your test code, I need to test it locally.

**Comment by hyojincha** [comment]
https://github.com/hyojincha/test/tree/master

Uploaded the test code to the URL.
ESP32 module is ESP32-WROOM-32D. and The board is self-made.

Please confirm operation. Thank you.

**Comment by xiewenxiang** [comment]
I used the `ESP32-WROOM-32` and `ESP32-WROVER-E` test the [sample code]( https://github.com/hyojincha/test/tree/master) you provided.

The APP is also provided by you, I tested it more than one hundred times, and it came up only one time，In this fail case, I did not capture the connection request from the phone. It is possible that the air hit the bag.

What was the failure rate in your tests?

**Comment by hyojincha** [comment]
Perhaps it was a problem with my smartphone, or something was not matching between the ESP32 and my phone's BLE.
As a result of testing with 2-3 other Android phones, the above problem does not occur at all.
For reference, the smartphone with the problem is the LG X5.
thank you.
