### ISSUE TITLE
[TW#15679] AP mode doesn't work

### ISSUE THREAD

**Issue by kimdowan84** [espressif/esp-idf#1018]
Dear MR.

I do not know from what version the wifi is not working correctly, 
but found that v3.0-dev-710 is not work at AP mode.

The sysdrome is that client can't get ip address.
Reference [TW#14352]

Thank you.

**Comment by tetious** [comment]
I'm also seeing this in current master, when using SOFTAP+STA. I think the DHCP server is no longer working.

This was not a problem at commit 969f1bb.

**Comment by tetious** [comment]
This is almost certainly related to DHCP. If I use a static IP matching the usual DHCP configuration, it works fine. 

I use 
```
IP: 192.168.4.2
Netmask: 255.255.255.0
Gateway 192.168.4.1
```

**Comment by liuzfesp** [comment]
HI @tetious this issue already fixed in IDF master branch, please check it.

**Comment by kimdowan84** [comment]
Yes, 806 version is OK!
