### ISSUE TITLE
As part of new release versions, BLE_GATT_MAX_PROCS is included to be configured via menuconfig. Closing this issue. (IDFGH-8755)

### ISSUE THREAD

**Issue by JonasAxelsson** [espressif/esp-idf#10188]
As part of new release versions, BLE_GATT_MAX_PROCS is included to be configured via menuconfig. Closing this issue.

_Originally posted by @rahult-github in https://github.com/espressif/esp-idf/issues/7639#issuecomment-1252075506_
     

In which version of the IDF is the fix included?

**Comment by rahult-github** [comment]
@JonasAxelsson , change is already put on master development branch. Going forward, expect it to be part of release/v5.x .

**Comment by AxelLin** [comment]
@JonasAxelsson @rahult-github 
This should be closed?
