### ISSUE TITLE
E (767) vfs_fat_sdmmc: slot init failed (0x103). (IDFGH-8749)

### ISSUE THREAD

**Issue by Sunlu2333** [espressif/esp-idf#10183]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

IDF_VER: v4.4.1-405-g6c5fb29c2c

### Operating System used.

Linux

### How did you build your project?

Command line with idf.py

### What is the expected behavior?

I want to store CSI collected by AP to SD card through SPI.

### What is the actual behavior?

E (767) vfs_fat_sdmmc: slot init failed (0x103).
E (768) sd.h: Failed to initialize the card (ESP_ERR_INVALID_STATE).   If you do not have an SD card attached, please ignore this message.  Make sure SD card lines have pull-up resistors in place.

### Steps to reproduce.

I have refer to demo code at ESP32-WROOM-32D, I try setting for SPI pins.
#define PIN_NUM_MISO    2
#define PIN_NUM_CLK    14
#define PIN_NUM_MOSI    15
#define PIN_NUM_CS     13
Its not worked for me, giving error
E (767) vfs_fat_sdmmc: slot init failed (0x103).
E (768) sd.h: Failed to initialize the card (ESP_ERR_INVALID_STATE).   If you do not have an SD card attached, please ignore this message.  Make sure SD card lines have pull-up resistors in place.

I study SPI Pins for ESP-WROOM-32 that are
(VSPI (MISO, CLK, MOSI, CS)=(19, 18, 23, 5))
(HSPI (MISO, CLK, MOSI, CS)=(12, 14, 13, 15))
Also test using VSPI pins, also not work for me. I have used Kingston micro SD 64 GB.

### Build or installation Logs.

```plain
rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:6676
load:0x40078000,len:14848
ho 0 tail 12 room 4
load:0x40080400,len:3792
0x40080400: _init at ??:?

entry 0x40080694
I (28) boot: ESP-IDF v4.4.1-405-g6c5fb29c2c 2nd stage bootloader
I (28) boot: compile time 20:27:28
I (28) boot: chip revision: 1
I (32) boot_comm: chip revision: 1, min. bootloader chip revision: 0
I (39) boot.esp32: SPI Speed      : 40MHz
I (44) boot.esp32: SPI Mode       : DIO
I (49) boot.esp32: SPI Flash Size : 2MB
I (53) boot: Enabling RNG early entropy source...
I (59) boot: Partition Table:
I (62) boot: ## Label            Usage          Type ST Offset   Length
I (69) boot:  0 nvs              WiFi data        01 02 00009000 00006000
I (77) boot:  1 phy_init         RF data          01 01 0000f000 00001000
I (84) boot:  2 factory          factory app      00 00 00010000 00100000
I (92) boot: End of partition table
I (96) boot_comm: chip revision: 1, min. application chip revision: 0
I (103) esp_image: segment 0: paddr=00010020 vaddr=3f400020 size=293c4h (168900) map
I (173) esp_image: segment 1: paddr=000393ec vaddr=3ffb0000 size=03a1ch ( 14876) load
I (179) esp_image: segment 2: paddr=0003ce10 vaddr=40080000 size=03208h ( 12808) load
I (184) esp_image: segment 3: paddr=00040020 vaddr=400d0020 size=a31a8h (668072) map
I (429) esp_image: segment 4: paddr=000e31d0 vaddr=40083208 size=12c4ch ( 76876) load
I (461) esp_image: segment 5: paddr=000f5e24 vaddr=50000000 size=00010h (    16) load
I (472) boot: Loaded app from partition at offset 0x10000
I (472) boot: Disabling RNG early entropy source...
I (483) cpu_start: Pro cpu up.
I (484) cpu_start: Starting app cpu, entry point is 0x4008137c
0x4008137c: call_start_cpu1 at /home/ssr-zenan/esp/esp-idf/components/esp_system/port/cpu_start.c:160

I (0) cpu_start: App cpu up.
I (500) cpu_start: Pro cpu start user code
I (500) cpu_start: cpu freq: 160000000
I (500) cpu_start: Application information:
I (504) cpu_start: Project name:     active-ap
I (509) cpu_start: App version:      1
I (514) cpu_start: Compile time:     Nov 15 2022 20:27:23
I (520) cpu_start: ELF file SHA256:  2d870ad44feb58a3...
I (526) cpu_start: ESP-IDF:          v4.4.1-405-g6c5fb29c2c
I (532) heap_init: Initializing. RAM available for dynamic allocation:
I (539) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM
I (546) heap_init: At 3FFB8DC8 len 00027238 (156 KiB): DRAM
I (552) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM
I (558) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
I (565) heap_init: At 40095E54 len 0000A1AC (40 KiB): IRAM
I (572) spi_flash: detected chip: generic
I (575) spi_flash: flash io: dio
W (579) spi_flash: Detected size(4096k) larger than the size in the binary image header(2048k). Using the size in the binary image header.
I (597) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.








-----------------------
ESP32 CSI Tool Settings
-----------------------
PROJECT_NAME: ACTIVE_AP
CONFIG_ESPTOOLPY_MONITOR_BAUD: 115200
CONFIG_ESP_CONSOLE_UART_BAUDRATE: 115200
IDF_VER: v4.4.1-405-g6c5fb29c2c
-----------------------
WIFI_CHANNEL: 4
ESP_WIFI_SSID: myssid
ESP_WIFI_PASSWORD: mypassword
SHOULD_COLLECT_CSI: 1
SHOULD_COLLECT_ONLY_LLTF: 1
SEND_CSI_TO_SERIAL: 0
SEND_CSI_TO_SD: 1
-----------------------








E (767) vfs_fat_sdmmc: slot init failed (0x103).
E (768) sd.h: Failed to initialize the card (ESP_ERR_INVALID_STATE).   If you do not have an SD card attached, please ignore this message.  Make sure SD card lines have pull-up resistors in place.
I (784) wifi:wifi driver task: 3ffc1b24, prio:23, stack:6656, core=0
I (787) system_api: Base MAC address is not set
I (792) system_api: read default base MAC address from EFUSE
I (818) wifi:wifi firmware version: 84ed08c
I (818) wifi:wifi certification version: v7.0
I (818) wifi:config NVS flash: enabled
I (818) wifi:config nano formating: disabled
I (822) wifi:Init data frame dynamic rx buffer num: 32
I (827) wifi:Init management frame dynamic rx buffer num: 32
I (832) wifi:Init management short buffer num: 32
I (837) wifi:Init dynamic tx buffer num: 32
I (841) wifi:Init static rx buffer size: 2212
I (845) wifi:Init static rx buffer num: 10
I (849) wifi:Init dynamic rx buffer num: 32
I (853) wifi_init: rx ba win: 6
I (856) wifi_init: tcpip mbox: 32
I (860) wifi_init: udp mbox: 6
I (864) wifi_init: tcp mbox: 6
I (868) wifi_init: tcp tx win: 5744
I (872) wifi_init: tcp rx win: 5744
I (876) wifi_init: tcp mss: 1440
I (880) wifi_init: WiFi IRAM OP enabled
I (885) wifi_init: WiFi RX IRAM OP enabled
I (896) phy_init: phy_version 4670,719f9f6,Feb 18 2021,17:07:07
I (995) wifi:mode : softAP (94:e6:86:66:85:2d)
I (999) wifi:Total power save buffer number: 16
I (1000) wifi:Init max length of beacon: 752/752
I (1000) wifi:Init max length of beacon: 752/752
I (1003) wifi:Set ps type: 0
```

### More Information.

#ifndef ESP32_CSI_SD_COMPONENT_H
#define ESP32_CSI_SD_COMPONENT_H

#include <stdio.h>
#include <string.h>
#include <sys/unistd.h>
#include <sys/stat.h>
#include "esp_err.h"
#include "esp_log.h"
#include "esp_vfs_fat.h"
#include "driver/sdspi_host.h"
#include "driver/sdmmc_host.h"
#include "driver/spi_common.h"
#include "sdmmc_cmd.h"

#define MOUNT_POINT "/sdcard"

#define SPI_DMA_CHAN    1

#define PIN_NUM_MISO    4
#define PIN_NUM_MOSI    15
#define PIN_NUM_CLK     14
#define PIN_NUM_CS      25

FILE *f;
char filename[24] = {0};

void _sd_pick_next_file() {
    int i = -1;
    struct stat st;
    while (true) {
        i++;
        printf("Checking %i.csv\n", i);
        sprintf(filename, "/sdcard/%i.csv", i);

        if (stat(filename, &st) != 0) {
            break;
        }

        printf("File size: %li\n", st.st_size);
    }
}

void sd_init() {
#ifdef CONFIG_SEND_CSI_TO_SD
    esp_err_t ret;
 
    esp_vfs_fat_sdmmc_mount_config_t mount_config = {
        .format_if_mount_failed = false,
        .max_files = 1,
        .allocation_unit_size = 16 * 1024
    };

    sdmmc_card_t *card;
    const char mount_point[] = MOUNT_POINT;
    ESP_LOGI("sd.h","Initializing SD card");
    
    sdmmc_host_t host = SDSPI_HOST_DEFAULT();

    //host.slot = SPI3_HOST;

    spi_bus_config_t bus_cfg = {
        .mosi_io_num = PIN_NUM_MOSI,
	.miso_io_num = PIN_NUM_MISO,
	.sclk_io_num = PIN_NUM_CLK,
	.quadwp_io_num = -1,
	.quadhd_io_num = -1,
	.max_transfer_sz = 4000
    };

    // SPI总线初始化
    
    ret = spi_bus_initialize(host.slot, &bus_cfg, SDSPI_DEFAULT_DMA);
    if (ret != ESP_OK) {
	ESP_LOGE("sd.h","Failed to initialize bus.");
	return;
    }
    // 这将初始化没有卡检测（CD）和写保护（WP）信号的插槽。
    // 如果您的主板有这些信号，请修改slot_config.gpio_cd和slot_config.gpio_wp。
    sdspi_device_config_t slot_config = SDSPI_DEVICE_CONFIG_DEFAULT();
    slot_config.gpio_cs = PIN_NUM_CS;
    slot_config.host_id = host.slot;

    // 挂载文件系统
    ret = esp_vfs_fat_sdspi_mount(mount_point, &host, &slot_config, &mount_config, &card);

    if (ret != ESP_OK) {
        if (ret == ESP_FAIL) {
	    ESP_LOGE("sd.h",
                "Failed to mount filesystem."
		"If you want the card to be formatted, set the EXAMPLE_FORMAT_IF_MOUNT_FAILED menuconfig option.");
	} else {
	    ESP_LOGE("sd.h",
                "Failed to initialize the card(%s)."
	        "Make sure SD card lines have pull-up resistors in place.", esp_err_to_name(ret));
	}
	return;
    }
        
    sdmmc_card_print_info(stdout, card);
    _sd_pick_next_file();
    f = fopen(filename, "a");
        
    // 卸载分区并禁用SDMMC或SPI外设
    //esp_vfs_fat_sdcard_unmount(mount_point, card);
    //卸载总线
    //spi_bus_free(host.slot);

#endif
}

/*
 * Printf for both serial AND sd card (if available and configured)
 */
void outprintf(const char *format, ...) {
    va_list args;
    va_start(args, format);

#ifdef CONFIG_SEND_CSI_TO_SERIAL
    vprintf(format, args);
#endif

#ifdef CONFIG_SEND_CSI_TO_SD
    if (f != NULL) {
        vfprintf(f, format, args);
    }
#endif

    va_end(args);
}

void sd_flush() {
#ifdef CONFIG_SEND_CSI_TO_SD
    fflush(f);
    fclose(f);
    f = fopen(filename, "a");
#endif
}

#endif //ESP32_CSI_SD_COMPONENT_H

**Comment by RathiSonika** [comment]
@Sunlu2333  thank you for reporting the issue here, however I was not able to replicate it on my setup (ESP32-WROOM-32 with SD card adapter) with default SPI pin settings
`#define PIN_NUM_MISO 2`
`#define PIN_NUM_CLK 14`
`#define PIN_NUM_MOSI 15`
`#define PIN_NUM_CS 13`
This [demo example](https://github.com/espressif/esp-idf/tree/release/v4.4/examples/storage/sd_card/sdspi) worked for me.
Can you please again refer [README.md](https://github.com/espressif/esp-idf/blob/release/v4.4/examples/storage/sd_card/sdspi/README.md) to cross check pull up requirement and pin configurations as from above logs and error message, 

`E (767) vfs_fat_sdmmc: slot init failed (0x103).`
`E (768) sd.h: Failed to initialize the card (ESP_ERR_INVALID_STATE). If you do not have an SD card attached, please ignore this message. Make sure SD card lines have pull-up resistors in place.`

I can see, there must be some issue with pull-up resistors. 
Please refer above README.md and let me know for any further query.

**Comment by RathiSonika** [comment]
Thank you for reporting the issue on GitHub. Closing this issue as of now as we have not received any update. If you encounter this issue again or have any additional information to share, please don't hesitate to reopen the issue or create a new one. We will be more than happy to assist you further and work towards a resolution.
