### ISSUE TITLE
I2S driver typo (Philip) (IDFGH-8764)

### ISSUE THREAD

**Issue by zjanosy** [espressif/esp-idf#10197]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

The I2S driver uses the word "Philip" instead of "Philips" everywhere.

**Comment by L-KAYA** [comment]
Thanks! It'll fix soon.
