### ISSUE TITLE
About ROM Library (IDFGH-8759)

### ISSUE THREAD

**Issue by nopnop2002** [espressif/esp-idf#10192]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

I used ESP-IDF V5.1 to compile the code below.
```
#include <stdio.h>
#include <string.h>
#include "rom/miniz.h"
#include "rom/ets_sys.h"
#include "rom/tjpgd.h"
#include "rom/md5_hash.h"

void app_main()
{
    uint8_t buf[64];
    memset(buf, 0, sizeof(buf));
    mz_crc32(MZ_CRC32_INIT, (const mz_uint8 *)(buf), 4);
}
```

For some reason, only miniz is a warning.
```
$ idf.py --version
ESP-IDF v5.1-dev-1840-gaad600c9ca

$ idf.py set-target esp32

$ idf.py build

    7 | #warning "{target}/rom/miniz.h is deprecated, please use (#include "miniz.h") instead"
      |  ^~
```

Reference:
https://github.com/espressif/esp-idf/issues/10177

**Comment by gm-jiang** [comment]
@nopnop2002 please use `#include` "miniz.h" instead.

**Comment by nopnop2002** [comment]
@gm-jiang 


#include "miniz" is not a warning.

I wonder why only miniz becomes a warning.

**Comment by gm-jiang** [comment]
@nopnop2002  Since this is a small breaking change that we move `esp_rom/include/{target}/rom/miniz.h` to `esp_rom/include/miniz.h` . In case the user outside has already used `rom/miniz.h` or `esp32/rom/miniz.h`, we put a waring code in original miniz.h for notice that changes.
```
#warning "{target}/rom/miniz.h is deprecated, please use (#include "miniz.h") instead"
#include "../../miniz.h"
```

**Comment by nopnop2002** [comment]
@gm-jiang 

Thank you.

small breaking change!!
