### ISSUE TITLE
ESP_IDF of v4.4 have problems receiving ack in promiscuous mode (IDFGH-8798)

### ISSUE THREAD

**Issue by goudanshi** [espressif/esp-idf#10229]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

In our project, we used two ESP32 to communicate through the wifi 802.11b/g/n protocol and want to obtain the csi data of both sides. The above process can be implemented normally in the ESP_IDF v4.2, but it cannot work normally with the  ESP_IDF v4.4. After debugging, it is found that the source of the problem is that  ESP_IDF v4.4 cannot receive ack frames normally in the promiscuous mode, which causes the frame number not to be updated, thus causing the csi not to be printed. Please instruct me how to solve this problem.

**Comment by zhangyanjiaoesp** [comment]
@goudanshi Do you still have this problem? Can you provide a demo for us to test?

**Comment by Sherry616** [comment]
Thanks for reporting, will close due to short of feedback, feel free to reopen with more updates. 
Thanks for using our Espressif product!
