### ISSUE TITLE
[TW#15682] Use bluedroid from Google to improve profile support.

### ISSUE THREAD

**Issue by fanthos** [espressif/esp-idf#1023]
Google using a patched(improved?) version of bluedroid in Android device.
The version from Google has more complete AVRC and other stack.
https://android.googlesource.com/platform/system/bt/
[Mirror](https://github.com/AospExtended/platform_system_bt)

**Comment by fanthos** [comment]
From LineageOS(CynagonMod)
New: https://github.com/LineageOS/android_system_bt
Old: https://github.com/LineageOS/android_external_bluetooth_bluedroid

**Comment by fanthos** [comment]
Seems that complete support in https://github.com/LineageOS/android_system_bt/tree/lineage-15.0 using `.cc` instead of `.c`.

**Comment by Yulong-espressif** [comment]
@fanthos Thanks for your suggestions, we have change the bluedroid stack code to the 7.1.2 version now.
