### ISSUE TITLE
ESP_GAP_BLE_CHANNEL_SELECT_ALGORITHM_EVT (IDFGH-8799)

### ISSUE THREAD

**Issue by hyojincha** [espressif/esp-idf#10230]
Currently using version 4.2,
I confirmed that ESP_GAP_BLE_CHANNEL_SELECT_ALGORITHM_EVT has been added to the BLE_GAP event since version 4.4.
Is the current channel selection algorithm actually working?

**Comment by xiewenxiang** [comment]
It should not be valid at present.

**Comment by hyojincha** [comment]
> It should not be valid at present.

thank you
