### ISSUE TITLE
spi_lcd_touch example: wrong colors with ILI9341 display (IDFGH-8811)

### ISSUE THREAD

**Issue by abusca** [espressif/esp-idf#10242]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [x] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v5.0-rc1

### Operating System used.

macOS

### How did you build your project?

Eclipse IDE

### Development Kit.

ESP32-2432S028

### Power Supply used.

USB

### What is the expected behavior?

I expected to see the dash board with correct colors. For example, the arc and tick lines at the end of the scale should be red.

### What is the actual behavior?

Some colors are not correct. For example, the arc and tick lines at the end of the scale are shown yellow.

### Steps to reproduce.

I took `spi_lcd_touch` example and I only modified LCD pinout defines with the ones of ESP32-2432S028 board.

**Comment by suda-morris** [comment]
please try to turn on or off the `CONFIG_LV_COLOR_16_SWAP` option

**Comment by abusca** [comment]
`CONFIG_LV_COLOR_16_SWAP` is enabled by default. If I turn it off, I see even weirder colors.

CONFIG_LV_COLOR_16_SWAP ON:
![CONFIG_LV_COLOR_16_SWAP ON](https://user-images.githubusercontent.com/2101783/203992826-c5bfaf9c-5dac-43e9-b0c9-5ffe39506b41.JPG)

CONFIG_LV_COLOR_16_SWAP OFF:
![CONFIG_LV_COLOR_16_SWAP OFF](https://user-images.githubusercontent.com/2101783/203992668-08e9501b-336c-4c5d-8159-555043fdc5ff.JPG)

**Comment by espzav** [comment]
@abusca The first image looks good. I have it same:
![20221125_145251](https://user-images.githubusercontent.com/98878239/204000006-488cbe89-a7f0-4f0f-bb0f-35d0266c6f8a.JPG)

**Comment by espzav** [comment]
@abusca The example is universal for two LCD controllers and the default `CONFIG_LV_COLOR_16_SWAP` is disabled for another LCD controller. If you enable it, it is ok for ILI9341.

**Comment by abusca** [comment]
> @abusca The first image looks good. I have it same:
> ![20221125_145251](https://user-images.githubusercontent.com/98878239/204000006-488cbe89-a7f0-4f0f-bb0f-35d0266c6f8a.JPG)

Shouldn't those lines and arc be in red?
https://github.com/espressif/esp-idf/blob/3f2f35bd5e1c3bab12def58de48c83fd8e93e431/examples/peripherals/lcd/spi_lcd_touch/main/lvgl_demo_ui.c#L60

**Comment by espzav** [comment]
@abusca I tried another project with image and you are right, there is some problem with colors. I am sorry, I didn't see before. I will fix it soon.

**Comment by espzav** [comment]
Hi @abusca, the component ILI9341 was fixed, but the example has still bad rgb_endian. The merge request of the example is waiting for approve. You should use this `.rgb_endian = LCD_RGB_ENDIAN_BGR,` in the example. 
The `CONFIG_LV_COLOR_16_SWAP` should be enabled (as default in example).

This is the new fixed result:
![20221128_092748](https://user-images.githubusercontent.com/98878239/204229790-69fb7454-3586-4ab5-a15c-3f5cda3a8851.JPG)

**Comment by abusca** [comment]
Thank you @espzav

**Comment by espzav** [comment]
@abusca You are welcome.

**Comment by Alvin1Zhang** [comment]
Thanks for sharing the updates, fix on master branch is available at https://github.com/espressif/esp-idf/commit/2e3c72a5d1ca52df1b4ec68661022bb50034c444. Thanks.
