### ISSUE TITLE
Esp32-C2 boudrate output error  (IDFGH-8827)

### ISSUE THREAD

**Issue by Eltopinovatif** [espressif/esp-idf#10255]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

esp32-c2 Uart error Does not match, standard boudrate is 115200 but actual is 74880. Test for example "Uart event" boudrate is changed to a value other than 115200 resulting in corrupt data output. can anyone help with the above problem
![boudrate](https://user-images.githubusercontent.com/50918515/204109537-277a95cc-fad0-4f1b-b43a-870483aa64b1.jpg)

**Comment by nopnop2002** [comment]
Try changing the crystal frequency to 26MHz in the following menuconfig menu:

![espc2-12-xtal](https://user-images.githubusercontent.com/6020549/204506204-05ee89a0-038e-4dd7-b095-214f2784524b.jpg)

**Comment by Eltopinovatif** [comment]
Thanks @ nopnop 2002.
the problem was resolved after the Xtal frequency config setting was changed to 26MHZ.
![esp-c2_set config](https://user-images.githubusercontent.com/50918515/204844588-65e9f583-a0a3-49bd-bcff-542e78bf14bc.jpg)
