### ISSUE TITLE
[ESP32S3] Incomprehensible offset if "CONFIG_ESP32S3_USE_FIXED_STATIC_RAM_SIZE" is used (IDFGH-8850)

### ISSUE THREAD

**Issue by sbithinx** [espressif/esp-idf#10271]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Hi,
if the KConfig option "CONFIG_ESP32S3_USE_FIXED_STATIC_RAM_SIZE" is used later in the [memory.ld file](https://github.com/espressif/esp-idf/blob/439a709c4298b0f613d09b47fc0b7b9728fc5733/components/esp_system/ld/esp32s3/memory.ld) the following lines can be found:

https://github.com/espressif/esp-idf/blob/439a709c4298b0f613d09b47fc0b7b9728fc5733/components/esp_system/ld/esp32s3/memory.ld.in#L120-L125

The used offset `0x3FCA0000` is incomprehensible. This not the beginning of any memory region of the ESP32S3. Could you please explain the used address? If not this seems to be a bug.

This may also related to the issue #10270. At least it can be analyzed of fixed together.

Greetings
Sebastian

**Comment by Alvin1Zhang** [comment]
Thanks for reporting.
