### ISSUE TITLE
esp_task_wdt_reset called when the task list is empty (IDFGH-8877)

### ISSUE THREAD

**Issue by norventa** [espressif/esp-idf#10298]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v5.0 rc1

### Operating System used.

Windows

### How did you build your project?

VS Code IDE

### If you are using Windows, please specify command line type.

None

### Development Kit.

ESP32 Custom board

### Power Supply used.

External 3.3V

### What is the expected behavior?

Not throw multiple wobblys.

### What is the actual behavior?

esp_task_wdt_reset in task_wdt.c is called repeatedly (correct). Many times after calling find_entry_from_task_handle_and_check_all_reset entry is NULL. handle is not NULL (how?). There are 5 tasks shown whilst debuging in the CALL STACK panel.

`esp_err_t esp_task_wdt_reset(void)
{
    ESP_RETURN_ON_FALSE(p_twdt_obj != NULL, ESP_ERR_INVALID_STATE, TAG, "TWDT was never initialized");
    esp_err_t ret;
    TaskHandle_t handle = xTaskGetCurrentTaskHandle();
    portENTER_CRITICAL(&spinlock);
    // Find entry from task handle
    bool all_reset;
    twdt_entry_t *entry;
    entry = find_entry_from_task_handle_and_check_all_reset(handle, &all_reset);
    ESP_GOTO_ON_FALSE_ISR((entry != NULL), ESP_ERR_NOT_FOUND, err, TAG, "task not found");
    // Mark entry as reset and issue timer reset if all entries have been reset
    entry->has_reset = true;    // Reset the task if it's on the task list
    if (all_reset) {    // Reset if all other tasks in list have reset in
        task_wdt_timer_feed();
    }
    ret = ESP_OK;
err:
    portEXIT_CRITICAL(&spinlock);
    return ret;
}`

### Steps to reproduce.

Simply by running my application. After initialization of various classes a SPIFFs partition is read. It is then that the following error message repeats:

E (xx) task_wdt: esp_task_wdt_reset(793): task not found

### Debug Logs.

```plain
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Users\Dougi\Documents\Projects\KilnESP32> set IDF_PATH=C:
\Users\Dougi\esp\esp-idf
PS C:\Users\Dougi\Documents\Projects\KilnESP32> C:\Users\Dougi\
.espressif\python_env\idf5.1_py3.8_env\Scripts\python.exe C:\Us
ers\Dougi\esp\esp-idf\tools\idf_monitor.py -p COM2 -b 115200 --
toolchain-prefix xtensa-esp32-elf- --target esp32 c:\Users\Doug
i\Documents\Projects\KilnESP32\build\KilnESP32.elf
--- WARNING: GDB cannot open serial ports accessed as COMx
--- Using \\.\COM2 instead...
--- idf_monitor on \\.\COM2 115200 ---
--- Quit: Ctrl+] | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl
+H ---
YׁJun  8 2016 00:22:57

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_
drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:6976
load:0x40078000,len:15492
ho 0 tail 12 room 4
load:0x40080400,len:3844
0x40080400: _init at ??:?

entry 0x4008064c
I (29) boot: ESP-IDF v5.1-dev-1881-gdcaa753f37-dirty 2nd stage 
bootloader
I (29) boot: compile time Dec  2 2022 13:28:34
I (31) boot: chip revision: v1.0
I (35) boot.esp32: SPI Speed      : 40MHz     
I (40) boot.esp32: SPI Mode       : DIO       
I (44) boot.esp32: SPI Flash Size : 16MB      
I (49) boot: Enabling RNG early entropy source...
I (54) boot: Partition Table:
I (58) boot: ## Label            Usage          Type ST Offset 
  Length
I (65) boot:  0 nvs              WiFi data        01 02 0000900
0 00004000
I (73) boot:  1 nvs_key          NVS keys         01 04 0000d00
0 00001000
I (80) boot:  2 otadata          OTA data         01 00 0000e00
0 00002000
I (88) boot:  3 app0             OTA app          00 10 0001000
0 00200000
I (95) boot:  4 app1             OTA app          00 11 0021000
0 00200000
I (103) boot:  5 app2             OTA app          00 12 004100
00 00200000
I (110) boot:  6 storage          Unknown data     01 82 006100
00 001f0000
I (118) boot: End of partition table
I (122) esp_image: segment 0: paddr=00010020 vaddr=3f400020 siz
e=34b90h (215952) map
I (175) esp_image: segment 1: paddr=00044bb8 vaddr=3ffb0000 siz
e=03efch ( 16124) load
I (179) esp_image: segment 2: paddr=00048abc vaddr=40080000 siz
e=0755ch ( 30044) load
I (189) esp_image: segment 3: paddr=00050020 vaddr=400d0020 siz
e=b566ch (743020) map
I (342) esp_image: segment 4: paddr=00105694 vaddr=4008755c siz
e=108a0h ( 67744) load
I (372) boot: Loaded app from partition at offset 0x10000
I (372) boot: Disabling RNG early entropy source...
I (384) cpu_start: Pro cpu up.
I (384) cpu_start: Starting app cpu, entry point is 0x40081574
0x40081574: call_start_cpu1 at C:/Users/Dougi/esp/esp-idf/compo
nents/esp_system/port/cpu_start.c:145

I (0) cpu_start: App cpu up.
I (400) cpu_start: Pro cpu start user code
I (400) cpu_start: cpu freq: 160000000 Hz
I (400) cpu_start: Application information:
I (405) cpu_start: Project name:     KilnESP32
I (410) cpu_start: App version:      1
I (414) cpu_start: Compile time:     Dec  2 2022 13:27:37
I (420) cpu_start: ELF file SHA256:  e81ab4aae0ab4af8...
I (426) cpu_start: ESP-IDF:          v5.1-dev-1881-gdcaa753f37-
dirty
I (433) cpu_start: Min chip rev:     v0.0
I (438) cpu_start: Max chip rev:     v3.99 
I (443) cpu_start: Chip rev:         v1.0
I (448) heap_init: Initializing. RAM available for dynamic allo
cation:
I (455) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM
I (461) heap_init: At 3FFB8C80 len 00027380 (156 KiB): DRAM
I (467) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM
I (474) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM  
I (480) heap_init: At 40097DFC len 00008204 (32 KiB): IRAM     
I (488) spi_flash: detected chip: generic
I (491) spi_flash: flash io: dio
I (498) THERMOCOUPLE: Name:  None
I (500) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.
E (32) E (571) task_wdt: esp_task_wdt_reset(793): task not foun
d
I (571) KILN: After Serial Init
I (572) KILN: IDF E (572) task_wdt: esp_task_wdt_reset(793): ta
sk not found
E (578) task_wdt: esp_task_wdt_reset(793): task not found      
version: vE (585) task_wdt: esp_task_wdt_reset(793): task not f
ound
E (591) task_wdt: esp_task_wdt_reset(793): task not found      
5.1-dev-18E (598) task_wdt: esp_task_wdt_reset(793): task not f
ound
E (604) task_wdt: esp_task_wdt_reset(793): task not found
81-gdcaa75E (611) task_wdt: esp_task_wdt_reset(793): task not f
ound
3f37-dirtyE (618) task_wdt: esp_task_wdt_reset(793): task not f
ound
E (624) task_wdt: esp_task_wdt_reset(793): task not found

E (631) task_wdt: esp_task_wdt_reset(793): task not found
E (633) task_wdt: esp_task_wdt_reset(793): task not found
E (633) task_wdt: esp_task_wdt_reset(793): task not found      
...
```

### More Information.

I have ported this working c++ application from platformio idf v4 to vscode/espressif extension. I have disabled one or two things in the original application: a GATT server and OTA code.

Here is the Doctor report:

---------------------------------------------- ESP-IDF Extension for Visual Studio Code report ---------------------------------------------
OS win32 x64 10.0.19045 
System environment variable IDF_PYTHON_ENV_PATH 
 undefined 
System environment variable PATH 
 C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files (x86)\dotnet\;C:\Program Files\Git\cmd;C:<HOMEPATH>\AppData\Local\Microsoft\WindowsApps;C:<HOMEPATH>\.dotnet\tools;;C:<HOMEPATH>\AppData\Local\Programs\Microsoft VS Code\bin 
System environment variable PYTHON 
 undefined 
Visual Studio Code version 1.73.1 
Visual Studio Code language en 
Visual Studio Code shell C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe 
ESP-IDF Extension version 1.5.1 
Workspace folder c:<HOMEPATH>\Documents\Projects\KilnESP32 
---------------------------------------------------- Extension configuration settings ------------------------------------------------------
ESP-ADF Path (idf.espAdfPath) ${env:ADF_PATH}
ESP-IDF Path (idf.espIdfPath) C:<HOMEPATH>\esp\esp-idf
ESP-MDF Path (idf.espMdfPath) ${env:MDF_PATH}
ESP-Matter Path (idf.espMatterPath) ${env:ESP_MATTER_PATH}
Custom extra paths (idf.customExtraPaths) C:<HOMEPATH>\.espressif\tools\xtensa-esp-elf-gdb\12.1_20221002\xtensa-esp-elf-gdb\bin;C:<HOMEPATH>\.espressif\tools\riscv32-esp-elf-gdb\12.1_20221002\riscv32-esp-elf-gdb\bin;C:<HOMEPATH>\.espressif\tools\xtensa-esp32-elf\esp-2022r1-11.2.0\xtensa-esp32-elf\bin;C:<HOMEPATH>\.espressif\tools\xtensa-esp32s2-elf\esp-2022r1-11.2.0\xtensa-esp32s2-elf\bin;C:<HOMEPATH>\.espressif\tools\xtensa-esp32s3-elf\esp-2022r1-11.2.0\xtensa-esp32s3-elf\bin;C:<HOMEPATH>\.espressif\tools\riscv32-esp-elf\esp-2022r1-11.2.0\riscv32-esp-elf\bin;C:<HOMEPATH>\.espressif\tools\esp32ulp-elf\2.35_20220830\esp32ulp-elf\bin;C:<HOMEPATH>\.espressif\tools\cmake\3.24.0\bin;C:<HOMEPATH>\.espressif\tools\openocd-esp32\v0.11.0-esp32-20221026\openocd-esp32\bin;C:<HOMEPATH>\.espressif\tools\ninja\1.10.2;C:<HOMEPATH>\.espressif\tools\idf-exe\1.0.3;C:<HOMEPATH>\.espressif\tools\ccache\4.6.2\ccache-4.6.2-windows-x86_64;C:<HOMEPATH>\.espressif\tools\dfu-util\0.9\dfu-util-0.9-win64;C:<HOMEPATH>\.espressif\tools\esp-rom-elfs\20220823
Custom extra vars (idf.customExtraVars) {"OPENOCD_SCRIPTS":"C:\\Users\\Dougi\\.espressif\\tools\\openocd-esp32\\v0.11.0-esp32-20221026/openocd-esp32/share/openocd/scripts","IDF_CCACHE_ENABLE":"1","ESP_ROM_ELF_DIR":"C:\\Users\\Dougi\\.espressif\\tools\\esp-rom-elfs\\20220823/"}
Virtual env Python Path (idf.pythonBinPath) C:<HOMEPATH>\.espressif\python_env\idf5.1_py3.8_env\Scripts\python.exe
Serial port (idf.port) COM2
OpenOCD Configs (idf.openOcdConfigs) interface/ftdi/iot-bus-jtag.cfg,target/esp32.cfg
ESP-IDF Tools Path (idf.toolsPath) C:<HOMEPATH>\.espressif
Git Path (idf.gitPath) C:<HOMEPATH>\.espressif\tools\idf-git\2.30.1\cmd\git.exe
-------------------------------------------------------- Configurations access -------------------------------------------------------------
Access to ESP-ADF Path (idf.espAdfPath) false
Access to ESP-IDF Path (idf.espIdfPath) true
Access to ESP-MDF Path (idf.espMdfPath) false
Access to ESP-Matter Path (idf.espMatterPath) false
Access to ESP-IDF Custom extra paths
Access to C:<HOMEPATH>\.espressif\tools\xtensa-esp-elf-gdb\12.1_20221002\xtensa-esp-elf-gdb\bin: true
Access to C:<HOMEPATH>\.espressif\tools\riscv32-esp-elf-gdb\12.1_20221002\riscv32-esp-elf-gdb\bin: true
Access to C:<HOMEPATH>\.espressif\tools\xtensa-esp32-elf\esp-2022r1-11.2.0\xtensa-esp32-elf\bin: true
Access to C:<HOMEPATH>\.espressif\tools\xtensa-esp32s2-elf\esp-2022r1-11.2.0\xtensa-esp32s2-elf\bin: true
Access to C:<HOMEPATH>\.espressif\tools\xtensa-esp32s3-elf\esp-2022r1-11.2.0\xtensa-esp32s3-elf\bin: true
Access to C:<HOMEPATH>\.espressif\tools\riscv32-esp-elf\esp-2022r1-11.2.0\riscv32-esp-elf\bin: true
Access to C:<HOMEPATH>\.espressif\tools\esp32ulp-elf\2.35_20220830\esp32ulp-elf\bin: true
Access to C:<HOMEPATH>\.espressif\tools\cmake\3.24.0\bin: true
Access to C:<HOMEPATH>\.espressif\tools\openocd-esp32\v0.11.0-esp32-20221026\openocd-esp32\bin: true
Access to C:<HOMEPATH>\.espressif\tools\ninja\1.10.2: true
Access to C:<HOMEPATH>\.espressif\tools\idf-exe\1.0.3: true
Access to C:<HOMEPATH>\.espressif\tools\ccache\4.6.2\ccache-4.6.2-windows-x86_64: true
Access to C:<HOMEPATH>\.espressif\tools\dfu-util\0.9\dfu-util-0.9-win64: true
Access to C:<HOMEPATH>\.espressif\tools\esp-rom-elfs\20220823: true
Access to Virtual env Python Path (idf.pythonBinPath) true
Access to CMake in environment PATH undefined
Access to Ninja in environment PATH undefined
Access to ESP-IDF Tools Path (idf.toolsPath) true
-------------------------------------------------------- Configurations has spaces -------------------------------------------------------------
Spaces in system environment Path true
Spaces in ESP-ADF Path (idf.espAdfPath) false
Spaces in ESP-IDF Path (idf.espIdfPath) false
Spaces in ESP-MDF Path (idf.espMdfPath) false
Spaces in ESP-Matter Path (idf.espMatterPath) false
Spaces in ESP-IDF Custom extra paths
Spaces in C:<HOMEPATH>\.espressif\tools\xtensa-esp-elf-gdb\12.1_20221002\xtensa-esp-elf-gdb\bin: false
Spaces in C:<HOMEPATH>\.espressif\tools\riscv32-esp-elf-gdb\12.1_20221002\riscv32-esp-elf-gdb\bin: false
Spaces in C:<HOMEPATH>\.espressif\tools\xtensa-esp32-elf\esp-2022r1-11.2.0\xtensa-esp32-elf\bin: false
Spaces in C:<HOMEPATH>\.espressif\tools\xtensa-esp32s2-elf\esp-2022r1-11.2.0\xtensa-esp32s2-elf\bin: false
Spaces in C:<HOMEPATH>\.espressif\tools\xtensa-esp32s3-elf\esp-2022r1-11.2.0\xtensa-esp32s3-elf\bin: false
Spaces in C:<HOMEPATH>\.espressif\tools\riscv32-esp-elf\esp-2022r1-11.2.0\riscv32-esp-elf\bin: false
Spaces in C:<HOMEPATH>\.espressif\tools\esp32ulp-elf\2.35_20220830\esp32ulp-elf\bin: false
Spaces in C:<HOMEPATH>\.espressif\tools\cmake\3.24.0\bin: false
Spaces in C:<HOMEPATH>\.espressif\tools\openocd-esp32\v0.11.0-esp32-20221026\openocd-esp32\bin: false
Spaces in C:<HOMEPATH>\.espressif\tools\ninja\1.10.2: false
Spaces in C:<HOMEPATH>\.espressif\tools\idf-exe\1.0.3: false
Spaces in C:<HOMEPATH>\.espressif\tools\ccache\4.6.2\ccache-4.6.2-windows-x86_64: false
Spaces in C:<HOMEPATH>\.espressif\tools\dfu-util\0.9\dfu-util-0.9-win64: false
Spaces in C:<HOMEPATH>\.espressif\tools\esp-rom-elfs\20220823: false
Spaces in Virtual env Python Path (idf.pythonBinPath) false
Spaces in ESP-IDF Tools Path (idf.toolsPath) false
----------------------------------------------------------- Executables Versions -----------------------------------------------------------
Git version 2.30.1.windows.1
ESP-IDF version 5.1
Python version 3.8.7
Python's pip version 22.3.1
-------------------------------------------------- Python packages in idf.pythonBinPath ----------------------------------------------------
bitstring version: 4.0.1
certifi version: 2022.9.24
cffi version: 1.15.1
charset-normalizer version: 2.1.1
click version: 8.1.3
colorama version: 0.4.6
construct version: 2.10.68
contextlib2 version: 21.6.0
cryptography version: 38.0.3
ecdsa version: 0.18.0
esp-coredump version: 1.4.1
esp-idf-kconfig version: 1.0.0
esptool version: 4.3
freertos-gdb version: 1.0.1
future version: 0.18.2
gcovr version: 5.2
idf-component-manager version: 1.1.4
idna version: 3.4
Jinja2 version: 3.0.3
kconfiglib version: 14.1.0
lxml version: 4.9.1
MarkupSafe version: 2.1.1
pip version: 22.3.1
psutil version: 5.9.4
pycparser version: 2.21
pyelftools version: 0.29
pygdbmi version: 0.9.0.2
Pygments version: 2.13.0
pyparsing version: 3.0.9
pyserial version: 3.5
pywin32 version: 305
PyYAML version: 6.0
reedsolo version: 1.5.4
requests version: 2.28.1
requests-toolbelt version: 0.10.1
schema version: 0.7.5
setuptools version: 65.6.0
six version: 1.16.0
tqdm version: 4.64.1
urllib3 version: 1.26.12
websocket-client version: 1.4.2
wheel version: 0.36.2
xmlrunner version: 1.7.7
---------------------------------------------------- Check ESP-IDF python requirements.txt -------------------------------------------------
Check ESP-IDF Python packages Python requirements are satisfied.
---------------------------------------------------- Check extension requirements.txt ------------------------------------------------------
Check Extension Python packages Python requirements are satisfied.
---------------------------------------------------- Check ESP-IDF debug adapter requirements.txt ------------------------------------------
Check Debug AdapterPython packages Python requirements are satisfied.
---------------------------------------------------- Visual Studio Code launch.json --------------------------------------------------------
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "espidf",
      "name": "Launch",
      "request": "launch"
    }
  ]
} 
---------------------------------------------------- Visual Studio Code c_cpp_properties.json ----------------------------------------------
{
    "configurations": [
        {
            "name": "ESP-IDF",
            "compilerPath": "C:\\Users\\Dougi\\.espressif\\tools\\xtensa-esp32-elf\\esp-2022r1-11.2.0\\xtensa-esp32-elf\\bin\\xtensa-esp32-elf-gcc.exe",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "includePath": [
                "${config:idf.espIdfPath}/components/**",
                "${config:idf.espIdfPathWin}/components/**",
                "${config:idf.espAdfPath}/components/**",
                "${config:idf.espAdfPathWin}/components/**",
                "${workspaceFolder}/**"
            ],
            "browse": {
                "path": [
                    "${config:idf.espIdfPath}/components",
                    "${config:idf.espIdfPathWin}/components",
                    "${config:idf.espAdfPath}/components/**",
                    "${config:idf.espAdfPathWin}/components/**",
                    "${workspaceFolder}"
                ],
                "limitSymbolsToIncludedHeaders": false
            },
            "compileCommands": "${workspaceFolder}/build/compile_commands.json"
        }
    ],
    "version": 4
} 
--------------------------------------------------------------------------------------------------------------------------------------------

**Comment by norventa** [comment]
The watchdog code has changed and this was the cause of the problem. By calling esp_task_wdt_delete with a task handle something strange happens in that (I believe) the list of handles gets updated by zeroing the task list array item rather than getting removed from the array.

**Comment by CraigeHales** [comment]
Similar issue, using a highest-priority hard loop on cpu 1, using printf, with watchdog disabled on cpu1. Many different weird behaviors. Same _find_entry_from_task_handle_and_check_all_reset_/_task-not-found_ and some other issues, eventually including _out-of-stack-space_ as I tried different ideas.
Works great with more stack space requested when launching the task. 
`xTaskCreatePinnedToCore(cpu_burn_task, "cpu_burn_task", 1024 * 10 /* stack, 2K is too small */, 
                 NULL /*parm*/, configMAX_PRIORITIES - 1, NULL /*taskhandle*/, 1 /*core*/);`
