### ISSUE TITLE
Initializers missing in esp_https_server (IDFGH-8885)

### ISSUE THREAD

**Issue by dannybackx** [espressif/esp-idf#10306]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

5.0

### Operating System used.

Linux

### How did you build your project?

Command line with Make

### If you are using Windows, please specify command line type.

None

### What is the expected behavior?

Compile without warning

### What is the actual behavior?

Warning about missing fields

### Steps to reproduce.

1. Step
2. Step
3. Step
...

### More Information.

``
hp: {1984} diff -c /home/danny/src/github/esp32/esp-idf-v5.0/components/esp_https_server/include/esp_https_server.h.orig  /home/danny/src/github/esp32/esp-idf-v5.0/components/esp_https_server/include/esp_https_server.h
*** /home/danny/src/github/esp32/esp-idf-v5.0/components/esp_https_server/include/esp_https_server.h.orig       2022-12-02 03:43:36.000000000 +0100
--- /home/danny/src/github/esp32/esp-idf-v5.0/components/esp_https_server/include/esp_https_server.h    2022-12-04 15:56:56.961906906 +0100
***************
*** 129,134 ****
--- 129,136 ----
          .global_user_ctx_free_fn = NULL,          \
          .global_transport_ctx = NULL,             \
          .global_transport_ctx_free_fn = NULL,     \
+       .enable_so_linger = false,                \
+       .linger_timeout = 0,                      \
          .open_fn = NULL,                          \
          .close_fn = NULL,                         \
          .uri_match_fn = NULL                      \

**Comment by ESP-YJM** [comment]
@dannybackx Thanks for reporting it. We will fix it immediately.
