### ISSUE TITLE
MCPWM don't reset GPIO (IDFGH-8916)

### ISSUE THREAD

**Issue by dizcza** [espressif/esp-idf#10327]
### Is your feature request related to a problem?

This is half proposal half issue report.

It's a proposal because I'm asking for a change in the MCPWM code.

It's an issue report because I found inconsistency in how different drivers are deinitialized in ESP32. 

MCPWM GPIO is shared with other peripheries. Hence I can call neither `mcpwm_del_capture_channel` nor `mcpwm_del_capture_timer`.

https://github.com/espressif/esp-idf/blob/454aeb3a48ac2b92cfa9d8b6a01d1b53179ec50a/components/driver/mcpwm/mcpwm_cap.c#L300

Moreover, the behavior - resetting the pin - is not even listed in `mcpwm_del_capture_channel` docs.

Moreover, some periphery (for instance, UART) do not reset GPIO while others like MCPWM do. There should be consistency in how a driver is deinitialized.

### Describe the solution you'd like.

I'm suggesting NOT resetting GPIO in any driver. At least in MCPWM.

### Describe alternatives you've considered.

Make `mcpwm_cap_channel_handle_t` open.

I'm forced to call

```c
mcpwm_cap_channel_handle_t channel;
// ...
memset((void*)channel + sizeof(int) + sizeof(void*) + sizeof(uint32_t), 0, sizeof(int));
mcpwm_del_capture_channel(channel);  // won't reset the pin
```

and rely on your implementation of this function that checks for a non-zero GPIO to reset it.

this is silly. And error-prone.

**Comment by suda-morris** [comment]
@dizcza Hi, could you give a use case for why you don't want to reset the GPIO when the driver is uninstalled?  e.g. if the same GPIO is used by both MCPWM and another peripheral A, when we used up the MCPWM, do you wish the peripheral A to be still workable?
