### ISSUE TITLE
esp_pm_impl_dump_stats fprintf wrong format (IDFGH-8930)

### ISSUE THREAD

**Issue by dizcza** [espressif/esp-idf#10347]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

master branch

### Operating System used.

Linux

### How did you build your project?

Command line with idf.py

### If you are using Windows, please specify command line type.

None

### What is the expected behavior?

It builds successfully.

### What is the actual behavior?
```
/home/dizcza/tools/esp-idf/components/esp_pm/pm_impl.c: In function 'esp_pm_impl_dump_stats':
/home/dizcza/tools/esp-idf/components/esp_pm/pm_impl.c:707:32: error: format '%d' expects argument of type 'int', but argument 4 has type 'uint32_t' {aka 'long unsigned int'} [-Werror=format=]
  707 |         fprintf(out, "%-8s  %-3dM%-7s %-10lld  %-2d%%\n",
      |                             ~~~^
      |                                |
      |                                int
      |                             %-3ld
  708 |                 s_mode_names[i],
  709 |                 s_cpu_freq_by_mode[i].freq_mhz,
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                      |
      |                                      uint32_t {aka long unsigned int}
cc1: some warnings being treated as errors
[692/803] Building CXX object esp-idf/wear_levelling/CMakeFiles/__idf_wear_levelling.dir/WL_Flash.cpp.objninja: build stopped: subcommand failed.
HINT: The issue is better to resolve by replacing format specifiers to 'PRI'-family macros (include <inttypes.h> header file).
```

### Steps to reproduce.

Enable PM profiling in menuconfig.

**Comment by ESP-Marius** [comment]
You are right!

We already have an internal MR that fixes this issue and i'll link this issue to it.

If you wanna fix it yourself quickly before commit is synced to Github you could change the line to:

`fprintf(out, "%-8s  %-3"PRIu32"M%-7s %-10lld  %-2d%%\n",`
