### ISSUE TITLE
esp32-s3 esp-idfv5.0 tinyusb issues in generated managed_components (IDFGH-8931)

### ISSUE THREAD

**Issue by LMBooth** [espressif/esp-idf#10348]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v5.0

### Operating System used.

Windows

### How did you build your project?

VS Code IDE

### If you are using Windows, please specify command line type.

CMD

### What is the expected behavior?

I'm building an esp32-s3 project with usb communications, recently updated to version 5.0. I expect the project to build succesfully when the following headers are added:
#include "tusb_cdc_acm.h"
#include "tinyusb.h"
#include "tusb_console.h"

### What is the actual behavior?

I get two errors on the generated managed_components files, shown in the build or installation logs section: 
1. #define CFG_TUD_CDC_RX_BUFSIZE      CONFIG_TINYUSB_CDC_RX_BUFSIZE in tusb_config.h,, 

 2. the other  is to do with the following error  -> error: expected specifier-qualifier-list before 'cdc_line_coding_t' in tusb_cdc_acm.c.

i have selected usb serial/jtag controller for channel console output in the sdk config ( though i can no longer see tinyusb specific settings, is this just me?). 

### Steps to reproduce.

1. Step install version esp-idf 5.0 in vscode
2.  add libraries: #include "tusb_cdc_acm.h"
#include "tinyusb.h"
#include "tusb_console.h"
3. Step build the project
4. Step see if errors occur in managed_components folder, seen in Build or installation Logs.

### Build or installation Logs.

```plain
C:/Users/Liam/Documents/Espressif_Workspace/AD7779_rev0b/managed_components/espressif__esp_tinyusb/include/tusb_cdc_acm.h:51:5: error: expected specifier-qualifier-list before 'cdc_line_coding_t'
   51 |     cdc_line_coding_t const *p_line_coding; /*!< New line coding value */
and 
C:/Users/Liam/Documents/Espressif_Workspace/AD7779_rev0b/managed_components/espressif__esp_tinyusb/include/tusb_config.h:90:37: error: 'CONFIG_TINYUSB_CDC_RX_BUFSIZE' undeclared here (not in a function); did you mean 'CFG_TUD_CDC_RX_BUFSIZE'?
   90 | #define CFG_TUD_CDC_RX_BUFSIZE      CONFIG_TINYUSB_CDC_RX_BUFSIZE
```

**Comment by nopnop2002** [comment]
From Ver5, esp_tinyusb has been moved to Component Manager.

Ver5 requires idf_component.yml.

https://github.com/espressif/esp-idf/blob/master/examples/peripherals/usb/device/tusb_console/main/idf_component.yml

**Comment by kenji-fukasawa** [comment]
![image](https://user-images.githubusercontent.com/2205422/206931591-2dcedc1b-b421-4612-9f66-da3b5be2dcc6.png)

I actually ran into a similar issue.  After a quick `diff` between my project and the USB example project, I noticed that there is a `CONFIG_USB_CDC_ENABLED` config option.  Open up the `menuconfig` in vscode and search for `cdc`.  Once I enabled that, my build was able to complete without error.

**Comment by tore-espressif** [comment]
Hello @LMBooth ,
as @kenji-fukasawa pointed out, the problem should be solved by enabling the CDC feature in TinyUSB menuconfig.

Please let us know, whether it fixes the problem in your case. I can add more user-friendly error messages if it helps.

**Comment by LMBooth** [comment]
How did i not see it!!! i could have sworn i typed in cdc and couldn't see the option for the tinyusb stack, sorry for having a dim moment and thanks to you guys for being so quick on the response!
