### ISSUE TITLE
[TW#15686] uart_read_bytes and uart_write_bytes has different buffer data type

### ISSUE THREAD

**Issue by fanthos** [espressif/esp-idf#1034]
These functions using different type for buffer.
Defined at:
`esp-idf/components/driver/include/driver/uart.h`
The read function using `unsigned char *` and write function using `char *`.

`int uart_read_bytes(uart_port_t uart_num, uint8_t* buf, uint32_t length, TickType_t ticks_to_wait);`
`int uart_write_bytes(uart_port_t uart_num, const char* src, size_t size);`

**Comment by FayeY** [comment]
Hi @fanthos , thanks for your reporting! This issue should have been solved in the latest IDF. If it is not, please feel free to reopen this issue. Thanks.

**Comment by Quentinb** [comment]
It looks like this is still the case? Checked the code in the master branch and release 4 and both are still different types.
![image](https://user-images.githubusercontent.com/5852237/71290676-1a734b80-2379-11ea-9f72-65fd11953f83.png)
![image](https://user-images.githubusercontent.com/5852237/71290715-3840b080-2379-11ea-87e1-3622b7cce415.png)
