### ISSUE TITLE
SPI_HOST_MAX for ESP32C2/C3 is incorrect (IDFGH-8932)

### ISSUE THREAD

**Issue by nopnop2002** [espressif/esp-idf#10349]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

ESP32C2/C3 has hardware limitations compared to ESP32.

The number of hardware can be checked with the following constants.
```
SPI_HOST_MAX
I2C_NUM_MAX
UART_NUM_MAX
```

But the SPI_HOST_MAX of the ESP32C2/C3 is incorrect.

# Version of ESP-IDF
```
$ idf.py --version
ESP-IDF v5.1-dev-1840-gaad600c9ca-dirty
```

# Test code
```
#include <stdio.h>
#include "driver/i2c.h"
#include "driver/spi_master.h"
#include "driver/uart.h"


void app_main()
{
    printf("SPI_HOST_MAX=%d\n", SPI_HOST_MAX);
    printf("I2C_NUM_MAX=%d\n", I2C_NUM_MAX);
    printf("UART_NUM_MAX=%d\n", UART_NUM_MAX);
}
```

# ESP32
SPI_HOST_MAX=3
I2C_NUM_MAX=2
UART_NUM_MAX=3

# ESP32C2
SPI_HOST_MAX=3 ---> incorrect
I2C_NUM_MAX=1
UART_NUM_MAX=2

# ESP32C3
SPI_HOST_MAX=3 ---> incorrect
I2C_NUM_MAX=1
UART_NUM_MAX=2

**Comment by suda-morris** [comment]
Hi @nopnop2002 Thanks for reporting.

Yes, the enum `spi_host_device_t` should reflect the `SOC_SPI_PERIPH_NUM` macro, we will fix it ASAP.

**Comment by nopnop2002** [comment]
@suda-morris 


The ESP32C2 and ESP32C3 documents have the following description.

This description may be misleading as SPI3 is available.

![ESP32C2](https://user-images.githubusercontent.com/6020549/207177548-aa660cd1-e258-4c03-89de-de2d4b616882.jpg)



![ESP32C3](https://user-images.githubusercontent.com/6020549/207177603-c7ed20fe-e75e-4114-b5c0-f787d06605da.jpg)

**Comment by AxelLin** [comment]
This was reported 1 year ago: https://github.com/espressif/esp-idf/issues/8144
