### ISSUE TITLE
esp_get_idf_version() returns a wrong version string (IDFGH-8925)

### ISSUE THREAD

**Issue by ataweg** [espressif/esp-idf#10342]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v4.4.3-313-ge86181704a

### Operating System used.

Windows

### How did you build your project?

Command line with CMake

### If you are using Windows, please specify command line type.

CMD

### What is the expected behavior?

esp_get_idf_version() should return the correct ESP_IDF version string

### What is the actual behavior?

I (867) cpu_start(429): ESP-IDF:          -128-NOTFOUND

### Steps to reproduce.

build the project

### Build or installation Logs.

```plain
ets Jun  8 2016 00:22:57

rst:0x1 (POWERON_R▒ets Jun  8 2016 00:22:57

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:5628
ho 0 tail 12 room 4
load:0x40078000,len:14864
load:0x40080400,len:4052
entry 0x4008064c
I (822) cpu_start(414): Pro cpu up.
I (822) cpu_start(208): Starting app cpu, entry point is 0x40081538
I (0) cpu_start(172): App cpu up.
I (837) cpu_start(406): Pro cpu start user code
I (837) cpu_start(408): cpu freq: 240000000
I (837) cpu_start(413): Application information:
I (843) cpu_start(415): Project name:     Wifi-WeatherStation
I (850) cpu_start(418): App version:      1
I (855) cpu_start(424): Compile time:     Dec 10 2022 00:13:54
I (861) cpu_start(428): ELF file SHA256:  59ccd4d412097d8c...
I (867) cpu_start(429): ESP-IDF:          -128-NOTFOUND
```

### More Information.

one of the compiler options set IDF_VER with the wrong value
-DIDF_VER=\"-128-NOTFOUND\"

**Comment by ataweg** [comment]
C:\Espressif\frameworks\esp-idf-v5.0>git describe --always --dirty --match v*.*
fatal: bad object HEAD
fatal: 'git status --porcelain=2' failed in submodule vendor/c_exception
fatal: 'git status --porcelain=2' failed in submodule components/cmock/CMock

C:\Espressif\frameworks\esp-idf-v5.0>cd ..

C:\Espressif\frameworks>cd esp-idf-v4.4

C:\Espressif\frameworks\esp-idf-v4.4>git describe --always --dirty --match v*.*
fatal: bad object HEAD
fatal: 'git status --porcelain=2' failed in submodule vendor/c_exception
fatal: 'git status --porcelain=2' failed in submodule components/cmock/CMock

C:\Espressif\frameworks\esp-idf-v4.4>cd ..

C:\Espressif\frameworks>cd esp-idf-v4.4.2

C:\Espressif\frameworks\esp-idf-v4.4.2>git describe --always --dirty --match v*.*
v4.4.2-dirty

**Comment by ataweg** [comment]
C:\Espressif\frameworks\esp-idf-v5.0>git describe --match v*.*
fatal: No tags can describe '75c3a69feba6ef0da54955fa67db34a78373d3a6'.
Try --always, or create some tags.

C:\Espressif\frameworks\esp-idf-v5.0>git describe --always --match v*.*
75c3a69feb

**Comment by igrr** [comment]
Hi @ataweg,

It looks like your esp-idf-v5.0 repository has been cloned without git tags.

As a workaround to get the correct behavior, please try running `git fetch origin v5.0`. After this, `git describe` should work correctly.

How did you download ESP-IDF? Did you do this manually or using the ESP-IDF Tools Installer for Windows? If you have used the installer, which version did you choose? (v5.0 tag or release/v5.0 branch?)

**Comment by ataweg** [comment]
I used the windows install first with "release/v5.0". Then I did a 2git pull".

**Comment by ataweg** [comment]
I did not work:

c:\Espressif\frameworks>cd esp-idf-v5.0

c:\Espressif\frameworks\esp-idf-v5.0>git describe
fatal: No tags can describe '75c3a69feba6ef0da54955fa67db34a78373d3a6'.
Try --always, or create some tags.

c:\Espressif\frameworks\esp-idf-v5.0>cd ../esp-idf-v4.4

c:\Espressif\frameworks\esp-idf-v4.4>git describe
v4.4.3-313-ge86181704a

c:\Espressif\frameworks\esp-idf-v4.4>git describe --always --dirty --match v*.*
fatal: bad object HEAD
fatal: 'git status --porcelain=2' failed in submodule vendor/c_exception
fatal: 'git status --porcelain=2' failed in submodule components/cmock/CMock

c:\Espressif\frameworks\esp-idf-v4.4>git fetch origin v4.4
From https://github.com/espressif/esp-idf
 * tag                     v4.4       -> FETCH_HEAD

c:\Espressif\frameworks\esp-idf-v4.4>git describe --always --dirty --match v*.*
fatal: bad object HEAD
fatal: 'git status --porcelain=2' failed in submodule vendor/c_exception
fatal: 'git status --porcelain=2' failed in submodule components/cmock/CMock

c:\Espressif\frameworks\esp-idf-v4.4>git describe
v4.4.3-313-ge86181704a

c:\Espressif\frameworks\esp-idf-v4.4>cd ../esp-idf-v5.0

c:\Espressif\frameworks\esp-idf-v5.0>git describe --always --dirty --match v*.*
fatal: bad object HEAD
fatal: 'git status --porcelain=2' failed in submodule vendor/c_exception
fatal: 'git status --porcelain=2' failed in submodule components/cmock/CMock

c:\Espressif\frameworks\esp-idf-v5.0>git describe
fatal: No tags can describe '75c3a69feba6ef0da54955fa67db34a78373d3a6'.
Try --always, or create some tags.

c:\Espressif\frameworks\esp-idf-v5.0>git fetch origin v5.0
From https://github.com/espressif/esp-idf
 * tag                     v5.0       -> FETCH_HEAD

c:\Espressif\frameworks\esp-idf-v5.0>git describe
fatal: No tags can describe '75c3a69feba6ef0da54955fa67db34a78373d3a6'.
Try --always, or create some tags.

c:\Espressif\frameworks\esp-idf-v5.0>

**Comment by ataweg** [comment]
after update to latest version with "git pull" and "git submodule update --init --recursive":
c:\Espressif\frameworks\esp-idf-v5.0>git describe
v5.0-259-g23dda413a5

issue still the afer rebuild the project
I (438) cpu_start(429):  ESP-IDF:          -128-NOTFOUND
--------------
also for esp-idf-v4.4 the issue is still there

**Comment by ataweg** [comment]
for esp-idf-v4.4 see C:\Espressif\frameworks\esp-idf-v4.4\make\project.mk line 348
the --dirty option make here trouble

c:\Espressif\frameworks\esp-idf-v4.4>git describe --always --dirty
fatal: bad object HEAD
fatal: 'git status --porcelain=2' failed in submodule vendor/c_exception
fatal: 'git status --porcelain=2' failed in submodule components/cmock/CMock

c:\Espressif\frameworks\esp-idf-v4.4>git describe --always --match v*.*
v4.4.3-313-ge86181704a

**Comment by georgik** [comment]
Solved by switching from `--depth 1` to `--single-branch`  when cloning repo.
Please, test the latest idf-installer 2.19: https://github.com/espressif/idf-installer/releases

Feel free to reopen in case of issue.
