### ISSUE TITLE
[idf.py] 'flash' command does not support Flash Encryption (Release) Mode, just soft bricks device (IDFGH-8923)

### ISSUE THREAD

**Issue by chipweinberger** [espressif/esp-idf#10340]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v4.4.3-215-g9f3f82f54b

### Operating System used.

macOS

### How did you build your project?

Command line with idf.py

### Related Issues

**esptool.py:** https://github.com/espressif/esptool/issues/809
**VSC Extension:** https://github.com/espressif/vscode-esp-idf-extension/issues/853

### What is the expected behavior?

`idf.py flash` should detect when your chip in Secure Download Mode and help the user flash an encrypted binary.

### What is the actual behavior?

`idf.py flash` flashes the binary as plaintext, causing the device to not boot.

### My Suggested Behavior

**Goal**: `idf.py flash` should be a 1 line command that can flash a device despite the state of Flash Encryption.

`idf.py flash` should detect when your chip has Flash Encryption enabled using `esptool.py get_security_info` and force you to specify a flag `--host-generated-key-file /path/to/key.bin`, or `--force-flash-raw` otherwise return an error.

**Note**: `--host-generated-key-file` flag would do nothing unless Flash Encryption was detected. This way, when specified, we'll have a 1 line command that can alway flash a device despite the state of Flash Encryption.

**Note:** `idf.py encrypted-flash` does not support release mode and returns an error when tried. IMO, encryption should be supported in the normal `idf.py flash` command too. We need a single command that aways works.

To automate further, we could have a KConfig for specifying the location of the keyfile, similar to custom partition tables. A `keyfile_path.txt` will then be written into the build folder.`idf.py flash` would then consult this file, when it detects it needs to apply encryption. This would make `idf.py flash` work seamlessly despite the mode of the device.

### Steps to reproduce.

1. Enable Flash Encryption (Release)
2. burn all relevant device fuses
3. use 'idf.py flash'

**Comment by mahavirj** [comment]
>  If that was true, it should be simple to detect when flash encryption is enabled, and return an error asking to specify a keyfile.

That won't help in the 1st workflow I described in my earlier comment. So idea here is that, once "release" mode of the flash enc is enabled (and it happens on the manufacturing line), only way remains to update the firmware is over the OTA update channel. If we are really need a way to update the firmware over UART DL mode then I think that can always happen using "Development" mode of the flash enc feature.

**Comment by chipweinberger** [comment]
Right, for the 1st workflow it would still report an error, telling you to specify a keyfile (which you do not have). or a --force-flash command, to flash anyway (which would hard brick the device).

This still seems like a big improvement. Especially for the 1st workflow, where you do not have the key and could ruin your device.

**Use Case:**  Of course "Development" Mode (3rd workflow...), is the most ideal for development. But I want to produce beta devices for users that use Release Mode (development mode is not secure), and want to retain the ability to fully update them over UART (bootloader, partition table, etc, if I need to.). For this, the current `idf.py` tools  are not ergonomic.

**Comment by mahavirj** [comment]
@chipweinberger 

> Use Case 2: Not hard bricking device in 1st workflow. Am I wrong in saying that for the 1st workflow, accidentally calling idf.py flash will ruin your device without warning? I have never tried...

Yes. We have now added a fix for this in the esptool through https://github.com/espressif/esptool/commit/0be5fcd903bdcad5bcb4d16dd13321787ad0a59c

Please check once, and it that looks good then probably we can close this ticket (implementing the host key based encryption can be handled in the project specific IDF extension, as I had commented earlier)

**Comment by chipweinberger** [comment]
That PR looks wonderful!

Thank you for circling back and fixing this. That's a great improvement.


> "WARNING: Detected flash encryption and "
"secure download mode enabled."
"Flashing plaintext binary may brick your device! "
"Use --force to override the warning."

I would say: 

"

> "WARNING: Detected flash encryption and "
"secure download mode enabled."
"Flashing plaintext binary may brick your device!"
"Use --force to override this warning after you've ensured the binary is pre-encrypted with host generated keys."

**Comment by mahavirj** [comment]
I will put this feedback internally. Interim, docs have bit more information with dedicated section for this: https://docs.espressif.com/projects/esptool/en/latest/esp32/esptool/basic-commands.html#encrypted-flash-protection

Thank you for your feedback and suggestions :+1: 

CC @Harshal5

**Comment by mahavirj** [comment]
> question - why does secure download mode matter? I would expect we just check for flash encryption release mode. Perhaps that is how we check for release vs development mode?

Yes, the change primarily detects if encrypted writes are still supported through UART DL mode or not. In case, they are supported then potentially device could be recovered, irrespective of the FLASH_CRYPT_CNT state.
