### ISSUE TITLE
ESP32-S3-DevKitC-1 FreeRTOS automatic sleep high current consumption (IDFGH-8956)

### ISSUE THREAD

**Issue by Bogdan-Vasile** [espressif/esp-idf#10368]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v5.0

### Operating System used.

Linux

### How did you build your project?

Command line with idf.py

### If you are using Windows, please specify command line type.

None

### Development Kit.

ESP32-S3-DevKitC-1

### Power Supply used.

USB

### What is the expected behavior?

I switched from ESP IDF v4.4.3 to v5.0 and wanted to test the light sleep power consumption on a ESP32-S3-DevKitC-1.

So I modified the default blink example to include automatic light sleep
`	esp_pm_config_esp32s3_t pm_config_ls_enable = {
                .max_freq_mhz = 80,
                .min_freq_mhz = 80,
                .light_sleep_enable = true
        };
        ....
	ESP_ERROR_CHECK(esp_pm_configure(&pm_config_ls_enable));
        ....
`
I checked that the CONFIG_FREERTOS_USE_TICKLESS_IDLE and CONFIG_PM_ENABLE sdkconfig options are enabled.

I was expecting that the power consumption would drop to 2 or 3 mA when powered via USB, like it does in v4.4.3.

### What is the actual behavior?

The current drawn from the USB port stays high, at about 42 mA, just like the default version of the blink app (without sleep enabled).

### Steps to reproduce.

Build and flash the attached projects.
...
[blinkSleep.zip](https://github.com/espressif/esp-idf/files/10226828/blinkSleep.zip)
[blink.zip](https://github.com/espressif/esp-idf/files/10226829/blink.zip)

### Debug Logs.

```plain
ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0x1 (POWERON),boot:0x8 (SPI_FAST_FLASH_BOOT)
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fce3810,len:0x167c
load:0x403c9700,len:0xbe8
load:0x403cc700,len:0x2e98
entry 0x403c9904
I (25) boot: ESP-IDF v5.0 2nd stage bootloader
I (25) boot: compile time 11:46:45
I (25) boot: chip revision: v0.1
I (26) boot_comm: chip revision: 1, min. bootloader chip revision: 0
I (33) boot.esp32s3: Boot SPI Speed : 80MHz
I (38) boot.esp32s3: SPI Mode       : DIO
I (43) boot.esp32s3: SPI Flash Size : 2MB
I (48) boot: Enabling RNG early entropy source...
I (53) boot: Partition Table:
I (57) boot: ## Label            Usage          Type ST Offset   Length
I (64) boot:  0 nvs              WiFi data        01 02 00009000 00006000
I (71) boot:  1 phy_init         RF data          01 01 0000f000 00001000
I (79) boot:  2 factory          factory app      00 00 00010000 00100000
I (86) boot: End of partition table
I (91) boot_comm: chip revision: 1, min. application chip revision: 0
I (98) esp_image: segment 0: paddr=00010020 vaddr=3c020020 size=0acd4h ( 44244) map
I (114) esp_image: segment 1: paddr=0001acfc vaddr=3fc93b00 size=02c58h ( 11352) load
I (117) esp_image: segment 2: paddr=0001d95c vaddr=40374000 size=026bch (  9916) load
I (125) esp_image: segment 3: paddr=00020020 vaddr=42000020 size=1f664h (128612) map
I (155) esp_image: segment 4: paddr=0003f68c vaddr=403766bc size=0d3a4h ( 54180) load
I (167) esp_image: segment 5: paddr=0004ca38 vaddr=50000000 size=00010h (    16) load
I (167) esp_image: segment 6: paddr=0004ca50 vaddr=600fe000 size=00034h (    52) load
I (179) boot: Loaded app from partition at offset 0x10000
I (179) boot: Disabling RNG early entropy source...
I (195) cpu_start: Pro cpu up.
I (196) cpu_start: Starting app cpu, entry point is 0x403753b0
0x403753b0: call_start_cpu1 at /data/esp-idf_v5.0/esp-idf/components/esp_system/port/cpu_start.c:142

I (0) cpu_start: App cpu up.
I (210) cpu_start: Pro cpu start user code
I (210) cpu_start: cpu freq: 160000000 Hz
I (210) cpu_start: Application information:
I (213) cpu_start: Project name:     blinkSleep
I (218) cpu_start: App version:      1
I (223) cpu_start: Compile time:     Dec 14 2022 11:46:40
I (229) cpu_start: ELF file SHA256:  a8116e8cd921045f...
I (235) cpu_start: ESP-IDF:          v5.0
I (240) heap_init: Initializing. RAM available for dynamic allocation:
I (247) heap_init: At 3FC97210 len 00052500 (329 KiB): D/IRAM
I (253) heap_init: At 3FCE9710 len 00005724 (21 KiB): STACK/DRAM
I (260) heap_init: At 3FCF0000 len 00008000 (32 KiB): DRAM
I (266) heap_init: At 600FE034 len 00001FCC (7 KiB): RTCRAM
I (273) spi_flash: detected chip: generic
I (277) spi_flash: flash io: dio
W (281) spi_flash: Detected size(8192k) larger than the size in the binary image header(2048k). Using the size in the binary image header.
I (305) sleep: Configure to isolate all GPIO pins in sleep state
I (306) pm: Frequency switching config: CPU_MAX: 160, APB_MAX: 80, APB_MIN: 40, Light sleep: DISABLED
I (311) sleep: Disable automatic switching of GPIO sleep configuration
I (318) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.
I (339) example: Starting esp_pm_configure!
I (339) pm: Frequency switching config: CPU_MAX: 160, APB_MAX: 160, APB_MIN: 160, Light sleep: ENABLED
I (349) sleep: Enable automatic switching of GPIO sleep configuration
I (359) sleep: Code start at 42000020, total 125.60 KiB, data start at 3c020020, total 43.21 KiB
I (369) example: Finished esp_pm_configure!
I (369) example: Example configured to blink addressable LED!
I (379) gpio: GPIO[48]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 
I (389) example: Turning the LED OFF!
I (1389) example: Turning the LED ON!
I (2389) example: Turning the LED OFF!
I (3389) example: Turning the LED ON!
```

**Comment by suda-morris** [comment]
Hi @Bogdan-Vasile Your test result is as expected because on esp32s3, we're using the [led_strip component](https://components.espressif.com/components/espressif/led_strip) to blink the WS2812, which relies on the RMT driver. And in the RMT driver, with the default clock source selection, the drive will acquire a power management lock, which in result can forbid you go into light sleep. 

We would suggest to use the hello-world example to test the light sleep, instead of the blink. But if you have to, please choose the  **Blink LED Type** to **GPIO** in blink example's menuconfig:

![image](https://user-images.githubusercontent.com/8869469/208890558-9c68ae6d-8785-4fbd-80cd-46623257eed8.png)

So that you will bypass the RMT driver. (however, in that case, you won't see the LED blinking)

**Comment by lennyJL** [comment]
Hi @Bogdan-Vasile, after [this PR](https://github.com/espressif/idf-extra-components/pull/119), you can choose the RMT clock source when calling `led_strip_new_rmt_device`.

**Comment by Bogdan-Vasile** [comment]
Hi @lennyJL, I used the code in your PR and set the clock source to RMT_CLK_SRC_RC_FAST and RMT_CLK_SRC_XTAL, but I see no change in the power consumption. Also, enabling and disabling DMA makes no difference. Should I try something else?

**Comment by lennyJL** [comment]
Hi @Bogdan-Vasile, can you try `CONFIG_BLINK_LED_GPIO` via menuconfig(ensure `CONFIG_FREERTOS_USE_TICKLESS_IDLE` and `CONFIG_PM_ENABLE` enabled). There is still a bug about using `RMT` during light sleep, we are looking into the bug.

**Comment by Bogdan-Vasile** [comment]
Hi @lennyJL, with CONFIG_BLINK_LED_GPIO the power consumption does drop, but the onboard led is not functioning. I'll wait for the RMT light sleep bug to be fixed. Is there a separate bug report for it?

**Comment by lennyJL** [comment]
Hi @Bogdan-Vasile, we have internally reported this issue, and we are working on improving `RMT with light sleep`. As soon as there is new progress, I will synchronize with you immediately.

**Comment by lennyJL** [comment]
Hi @Bogdan-Vasile, you can try this patch for **idf**:

> diff --git a/components/driver/rmt/rmt_common.c b/components/driver/rmt/rmt_common.c
> index 33af3fc8fa..24da4b6f02 100644
> --- a/components/driver/rmt/rmt_common.c
> +++ b/components/driver/rmt/rmt_common.c
> @@ -156,6 +156,14 @@ esp_err_t rmt_select_periph_clock(rmt_channel_handle_t chan, rmt_clock_source_t
>  #if SOC_RMT_SUPPORT_XTAL
>      case RMT_CLK_SRC_XTAL:
>          periph_src_clk_hz = esp_clk_xtal_freq();
> +#if CONFIG_PM_ENABLE
> +        sprintf(chan->pm_lock_name, "rmt_%d_%d", group->group_id, channel_id); // e.g. rmt_0_0
> +        // XTAL will be power down in the light sleep (predefined low power modes)
> +        // acquire a NO_LIGHT_SLEEP lock here to prevent the system go into light sleep automatically
> +        ret  = esp_pm_lock_create(ESP_PM_NO_LIGHT_SLEEP, 0, chan->pm_lock_name, &chan->pm_lock);
> +        ESP_RETURN_ON_ERROR(ret, TAG, "create NO_LIGHT_SLEEP lock failed");
> +        ESP_LOGD(TAG, "install NO_LIGHT_SLEEP lock for RMT channel (%d,%d)", group->group_id, channel_id);
> +#endif // CONFIG_PM_ENABLE
>          break;
>  #endif // SOC_RMT_SUPPORT_XTAL
>  #if SOC_RMT_SUPPORT_REF_TICK
> -- 

with latest PR: https://github.com/espressif/idf-extra-components/pull/119.

And use `RMT_CLK_SRC_XTAL`. Also remember to config  `CONFIG_FREERTOS_USE_TICKLESS_IDLE` and `CONFIG_PM_ENABLE` via menuconfig.

**Comment by Bogdan-Vasile** [comment]
Hi @lennyJL , I tested the updated versions and I can confirm that the CPU now enters light sleep and the power consumption drops as expected.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting and sharing the updates, fix is available at https://github.com/espressif/esp-idf/commit/bcc307cf7bb3aea138a9577c3eae2aec65ba7da2, feel free to reopen.
