### ISSUE TITLE
no documentation on how to wake up esp32-s3 from light sleep using bluetooth (IDFGH-8950)

### ISSUE THREAD

**Issue by jonathanMerlingPal** [espressif/esp-idf#10362]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Hi,

I'm using ESP32-S3-Eye and I would like to put the device in light sleep with bt_wakeup.
I noticed there is the function `esp_sleep_enable_bt_wakeup();` which returned `ESP_OK;` but I don't know how to proceed from here since there is no documentation or examples using it.

I've tried:
Connecting the device to a Ble server and registering for notification. 
The result is that the device doesn't wakeup from light sleep when the server sends notification.

Is there any documentation/example on how to wake up a device from light sleep using Bluetooth?

**Comment by esp-cjh** [comment]
@jonathanMerlingPal Please refer to the following documents:
https://docs.espressif.com/projects/esp-idf/en/latest/esp32s3/api-reference/system/sleep_modes.html

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to short of feedback, feel free to reopen with more updates. Thanks.
