### ISSUE TITLE
workaround for esp_wifi_set_channel when connected to AP (IDFGH-8957)

### ISSUE THREAD

**Issue by davnec** [espressif/esp-idf#10369]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

I'm working on ewfactoring of an old firmware based on IDF <3.3

The situation that cause the issue is:

Esp connected in STA mode to AP and use a dynamic channell

I need to change the channel for a short period using 

`esp_wifi_set_channel `

and send a message, in my case esp-now packet on specific channel and back to the ap channel

I've read that this situation in recent IDF version is not permitted when STA is connected to AP, but this new situation casuse a big impact to the project.

Now I need to know if there is a workaround to permitt to change the channel in IDF 4.x or better 5

I read a lot of messages about the issue but without a clear indication about the possibility.

Thanks

(I'm sorry for posting in various channels, but I have a big project on hold for this issue and I have to communicate something clear to the customer)

**Comment by zhangyanjiaoesp** [comment]
@davnec Do you mean that you ESP-NOW devices are on channel A, and the STA connects to AP on channel B, you need to change channel to A to send ESP-NOW data, and then change back to channel B?

**Comment by Sherry616** [comment]
Thanks for reporting, will close due to short of feedback, feel free to reopen with more updates.
