### ISSUE TITLE
Wi-Fi Multiple Antennas question (IDFGH-8963)

### ISSUE THREAD

**Issue by WangShuoran** [espressif/esp-idf#10375]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

When I use WIFI Multiple Antennas(SWITCH), I have any question which can not find in network:
1. In wifi_ant_gpio_t struct, what function is gpio_select? In document show "If GPIO[x] is connected to antenna_select[x], then gpio_config->gpio_cfg[x].gpio_select should be set to 1", But the field have not significance, because I set the "gpio_num" is ok, so gpio_select==0 have any mean? or it only use to set 1?
2. In wifi_ant_gpio_config_t struct, the first content is point to the antenna_select[3:0]'s lowest position? I want to confirm. because the document is very obscure.
3. In document show "Currently, Bluetooth® does not support the multiple antennas feature, so please do not use multiple antennas related APIs.", I want to know does WIFI Multiple Antennas is affects the normal operation of Bluetooth(BT/BLE)? Or BT/BLE is not affected, only BT/BLE does not control SWITCH? I want to use Blufi and WIFI Multiple Antennas at same time.
4. Is it true that only two of the maximum 16 antennas will be used after once configuration? If I want to use more antennas, we need to be configured via esp_wifi_set_ant() again.

**Comment by mhdong** [comment]
Hi @WangShuoran 
We have updated Multiple Antennas apis and docs, please reference
https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/phy.html

**Comment by Sherry616** [comment]
Thanks for reporting, we will close this issue. Feel free to reopen if have more updates. 
Thanks for using our Espressif product!
