### ISSUE TITLE
Modify HTTP Restful API Server Example to use WIFI_MODE_AP mode instead of WIFI_MODE_STA (IDFGH-8968)

### ISSUE THREAD

**Issue by bmkuter** [espressif/esp-idf#10380]
### Is your feature request related to a problem?

No.

### Describe the solution you'd like.

I am trying to expand the HTTP Restful API Server Example to use the esp32-c3 in access point mode instead of station mode, so the restful API frontend from the example can be accessed by a device connecting to the esp32 AP. 

Example in question:
https://github.com/espressif/esp-idf/tree/edd815af2e7d541b25ff3a74c59a7fe0612df42d/examples/protocols/http_server/restful_server

### Describe alternatives you've considered.

I found this old post, but no followup:
https://github.com/espressif/esp-idf/issues/5706

**Comment by hmalpani** [comment]
Hello @bmkuter 
I am sharing a patch here that you can use for your use-case.
[IDFGH-8968.txt](https://github.com/espressif/esp-idf/files/10313211/IDFGH-8968.txt)

As it only requires some modifications, we are not planning to expand the example in IDF to support SoftAP mode. I hope this patch helps you. Closing the issue. Please feel free to reopen
