### ISSUE TITLE
[TW#15689] undefined reference to `multi_heap_get_info'

### ISSUE THREAD

**Issue by ataweg** [espressif/esp-idf#1038]
I got this compile error:
C:/Espressif/esp-idf/components/heap/heap_caps.c:273: undefined reference to `multi_heap_get_info'

I found in components/heap/multi_heap.c the name of the requested function was misspelt. So I 
changed the name from "multi_get_heap_info" to "multi_heap_get_info" and all is fine now.
Also changed in file components/heap/include/multi_heap.h

Viele Gruesse
Axel

**Comment by rojer** [comment]
https://github.com/espressif/esp-idf/pull/1039 fixes it
