### ISSUE TITLE
MCPWM ESP32 ( huzzah ) function: mcpwm_set_duty_in_us(),  gives wrong duty (IDFGH-8985)

### ISSUE THREAD

**Issue by fbd-ss** [espressif/esp-idf#10397]
see code below, when setting the "duty_in_us" parameter, the mcpwm_get_duty_in_us() function returns 20, but the actual duty period is 200 us, somewhere the period is getting multiplied by 10.
![image](https://user-images.githubusercontent.com/68264164/208318382-cfcabc2b-7749-40a6-830d-81565a28b2d7.png)

`              mcpwm_config_t pwm_config{
                       .frequency = 10000,
                       .cmpr_a = 0,
                       .cmpr_b = 0,
                       .duty_mode = MCPWM_DUTY_MODE_0,
                       .counter_mode = MCPWM_UP_COUNTER
               };

               mcpwm_init( _pwm_unit,
                           _pwm_timer,
                           &pwm_config );

               mcpwm_set_duty_in_us( _pwm_unit,
                                     _pwm_timer,
                                     _pwm_generator,
                                     _on_phase_usecs ); <-------- 20

               mcpwm_gpio_init( _pwm_unit, _pwm_io_signal, _pin_number );

               auto dt = mcpwm_get_duty_in_us(_pwm_unit,
                                              _pwm_timer,
                                              _pwm_generator);`

**Comment by suda-morris** [comment]
@fbd-ss  I tested your code but can't reproduce it on the master branch. Please tell us which IDF release you're referring to. And please upgrade your SDK to the latest release version in case there're some bugfixes missed in your current SDK.

```c
#include <stdio.h>
#include <inttypes.h>
#include "driver/mcpwm.h"

void app_main(void)
{
    mcpwm_config_t pwm_config = {
        .frequency = 10000,
        .cmpr_a = 0,
        .cmpr_b = 0,
        .duty_mode = MCPWM_DUTY_MODE_0,
        .counter_mode = MCPWM_UP_COUNTER
    };

    mcpwm_init(MCPWM_UNIT_0, MCPWM_TIMER_0, &pwm_config);

    mcpwm_set_duty_in_us(MCPWM_UNIT_0, MCPWM_TIMER_0, MCPWM_OPR_A, 20);
    mcpwm_gpio_init(MCPWM_UNIT_0, MCPWM0A, 0);

    uint32_t duty_us = mcpwm_get_duty_in_us(MCPWM_UNIT_0, MCPWM_TIMER_0, MCPWM_OPR_A);
    printf("Duty: %" PRIu32 " us\r\n", duty_us);
}
```

Console output:

```
I (326) app_start: Starting scheduler on CPU0
I (331) app_start: Starting scheduler on CPU1
I (331) main_task: Started on CPU0
I (341) main_task: Calling app_main()
Duty: 20 us
I (341) main_task: Returned from app_main()
```

![image](https://user-images.githubusercontent.com/8869469/208363496-dfd6a09a-3385-4894-a02e-d64172672303.png)

**Comment by Alvin1Zhang** [comment]
@fbd-ss Thanks for reporting, would you please help share if any further updates for the issue? Thanks.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to short of feedback, feel free to reopen with more updates. Thanks.
