### ISSUE TITLE
gpio_uninstall_isr_service appears to leak memory (IDFGH-8984)

### ISSUE THREAD

**Issue by kbsriram** [espressif/esp-idf#10396]
running the standalone heap tracer around this pair of calls:
```
gpio_install_isr_service(0);
gpio_uninstall_isr_service();
```
results in a reported missing free as follows:
```
1 allocations trace (10 entry buffer)
12 bytes (@ 0x3fc90fb8) allocated CPU 0 ccount 0x027bc30c caller 
12 bytes 'leaked' in trace (1 allocations)
total allocations 3 total frees 2
```
Full log: [log.txt](https://github.com/espressif/esp-idf/files/10254077/log.txt)
Additional information:
```
Target: esp32c3
Board: DFRobot Beetle ESP32 - C3 (https://www.dfrobot.com/product-2566.html)
ESP-ROM: esp32c3-api1-20210207
idf.py --version: ESP-IDF v5.1-dev-1768-g6bb28c4cdc-dirty
Host os: Linux kbs-personal 4.15.0-200-generic #211-Ubuntu SMP
```

Sample code with configuration attached:
[memory_leak.zip](https://github.com/espressif/esp-idf/files/10254022/memory_leak.zip)

**Comment by kayzen9** [comment]
it's by design to speed up further int alloc... (@kbsriram)

https://github.com/espressif/esp-idf/blob/edd815af2e7d541b25ff3a74c59a7fe0612df42d/components/esp_hw_support/intr_alloc.c#L752-L754

**Comment by kbsriram** [comment]
Ah, interesting! Thanks for the pointer @kayzen9 - I'll close this out as WAI.

**Comment by AxelLin** [comment]
> it's by design to speed up further int alloc... (@kbsriram)


Do you expect the intr_alloc/intr_free to be called in critical path?
If not, why you need the hack for speedup?

**Comment by kbsriram** [comment]
@songruo - gotcha - and thank you for the follow-up.
