### ISSUE TITLE
Sniff ESPNOW traffic (IDFGH-8981)

### ISSUE THREAD

**Issue by AmirHmZz** [espressif/esp-idf#10394]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

I have two questions : 

1. How does random bytes prevent relay attacks?
2. I know ESPNOW traffic can be inspected by tools like wireshark If I don't use action frame encryption. But, can an attacker generate and send ESPNow messages? Is there anything that verifies messages are surely sent from an esp device and they are not sent by an attacker with these [tools](https://wiki.wireshark.org/Tools#traffic-generators)?

**Comment by AmirHmZz** [comment]
Any updates on this question?

**Comment by AmirHmZz** [comment]
Any updates on this question?

**Comment by zhangyanjiaoesp** [comment]
@AmirHmZz 
1. Currently, the random bytes  can only check the retransmit packets with the `Retry` bit set to 1 in the `Frame Control` field.
2. If the ESPNOW data is unencrypted, an attacker can generate and send ESPNOW, and there isn't a good way to tell if the packet was sent from the ESP device or from the attacker.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to short of feedback, feel free to reopen with more updates.
