### ISSUE TITLE
esp_execute_shared_stack_function: random Watchpoint 1 panics without CONFIG_FREERTOS_WATCHPOINT_END_OF_STACK (IDFGH-9003)

### ISSUE THREAD

**Issue by DirtYiCE** [espressif/esp-idf#10414]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v5.0-378-g5278cc7de0

### Operating System used.

Linux

### How did you build your project?

Command line with idf.py

### If you are using Windows, please specify command line type.

None

### Development Kit.

LILYGO T-Embed ESP32-S3

### Power Supply used.

USB

### What is the expected behavior?

The program continues to work after calling `esp_execute_shared_stack_function`

### What is the actual behavior?

Random panics:
```
Guru Meditation Error: Core  0 panic'ed (Unhandled debug exception). 
Debug exception reason: Watchpoint 1 triggered 
```
usually from malloc code, but randomly from other places too.

### Steps to reproduce.

1. Call `esp_execute_shared_stack_function` (just with a noop function)
2. Delete the task
3. Wait

### More Information.

Here it sets the watchpoint to the shared stack:
https://github.com/espressif/esp-idf/blob/5278cc7de077e06a241dc415c24e50e7e5fcb5eb/components/esp_system/port/arch/xtensa/expression_with_stack.c#L46-L48
And it resets here after returning:
https://github.com/espressif/esp-idf/blob/5278cc7de077e06a241dc415c24e50e7e5fcb5eb/components/esp_system/port/arch/xtensa/expression_with_stack.c#L78
Please not that there is no `#if CONFIG_FREERTOS_WATCHPOINT_END_OF_STACK` here. And without that config, normally nothing sets watchpoint 1, which means if later anything accesses that memory (for example because the task was deleted and its memory was reused for something else), it will panic. Adding that missing `#if` seems to fix the problem.

Also here it sets `pxDummy6` (aka `pxStack`) to the shared stack's beginning, shouldn't it also set `pxEndOfStack`?
https://github.com/espressif/esp-idf/blob/5278cc7de077e06a241dc415c24e50e7e5fcb5eb/components/esp_system/port/arch/xtensa/expression_with_stack.c#L39

From a quick look, it looks like riscv implementation has the same problem, but I never tried to use that.

**Comment by 0xjakob** [comment]
@DirtYiCE Thanks for reporting this issue! It seems that you're right and the second watch point setting needs to be wrapped in ifdefs as well. We'll fix this.
