### ISSUE TITLE
ESP32S3 RMT rmt_tx_done_event_data_t num_symbols off by 1 (IDFGH-9026)

### ISSUE THREAD

**Issue by higaski** [espressif/esp-idf#10435]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v5.0

### Operating System used.

Linux

### How did you build your project?

Command line with idf.py

### If you are using Windows, please specify command line type.

None

### Development Kit.

Custom Board

### Power Supply used.

USB

### What is the expected behavior?

The `num_symbols` value of the [rmt_tx_done_event_data_t](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/peripherals/rmt.html#_CPPv424rmt_tx_done_event_data_t) struct is always off by +1 if red inside a RMT TX transmission done callback.

E.g. transmitting 32 symbols results in the num_symbols value 33

### What is the actual behavior?

`num_symbols` value is off by +1

### Steps to reproduce.

1.) Upload any RMT TX example to the board.
2.) Read the `num_symbols` value inside the TX callback

**Comment by suda-morris** [comment]
Sorry for confusing you, but this result is as expected. The driver will append an "EOF symbol" to the end of each TX transaction, as this is required by the RMT hardware to mark the end of a transaction.

FYI, we have a test to check that `num_symbols` in the tx callback: https://github.com/espressif/esp-idf/blob/master/components/driver/test_apps/rmt/main/test_rmt_tx.c#L211

We should mention that thing in our programming guide. Thanks for reporting.
