### ISSUE TITLE
install.sh fails to download packages (IDFGH-9041)

### ISSUE THREAD

**Issue by Na2l** [espressif/esp-idf#10447]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v5.1-dev-2509-gcfef24863f

### Operating System used.

Windows

### How did you build your project?

Command line with Make

### If you are using Windows, please specify command line type.

None

### What is the expected behavior?

install to be finished w/o warnings download failures

### What is the actual behavior?

Extracting /home/naal/.espressif/dist/riscv32-esp-elf-gcc8_4_0-esp-2021r2-linux-amd64.tar.gz to /home/naal/.espressif/tools/riscv32-esp-elf/esp-2021r2-8.4.0
Installing esp32s2ulp-elf@2.28.51-esp-20191205
Downloading binutils-esp32s2ulp-linux-amd64-2.28.51-esp-20191205.tar.gz to /home/naal/.espressif/dist/binutils-esp32s2ulp-linux-amd64-2.28.51-esp-20191205.tar.gz.tmp
**WARNING: Download failure HTTP Error 503: Egress is over the account limit.
**WARNING: Failed to download https://github.com/espressif/binutils-esp32ulp/releases/download/v2.28.51-esp-20191205/binutils-esp32s2ulp-linux-amd64-2.28.51-esp-20191205.tar.gz to /home/naal/.espressif/dist/binutils-esp32s2ulp-linux-amd64-2.28.51-esp-20191205.tar.gz.tmp****
Downloading binutils-esp32s2ulp-linux-amd64-2.28.51-esp-20191205.tar.gz to /home/naal/.espressif/dist/binutils-esp32s2ulp-linux-amd64-2.28.51-esp-20191205.tar.gz.tmp
**WARNING: Download failure HTTP Error 503: Egress is over the account limit.
WARNING: Failed to download https://github.com/espressif/binutils-esp32ulp/releases/download/v2.28.51-esp-20191205/binutils-esp32s2ulp-linux-amd64-2.28.51-esp-20191205.tar.gz to /home/naal/.espressif/dist/binutils-esp32s2ulp-linux-amd64-2.28.51-esp-20191205.tar.gz.tmp**
Downloading binutils-esp32s2ulp-linux-amd64-2.28.51-esp-20191205.tar.gz to /home/naal/.espressif/dist/binutils-esp32s2ulp-linux-amd64-2.28.51-esp-20191205.tar.gz.tmp
Done

### Steps to reproduce.

1. Clone the repo (with --recurse)
2. Run ./install.sh esp32s3
3. 

### Build or installation Logs.

```plain
.
```

### More Information.

.

**Comment by 0xjakob** [comment]
@Na2l This looks a bit like a github server problem to me (see also [this issue in a completely different repo](https://github.com/lovell/sharp-libvips/issues/121)). If the problem persists, could you try to use [Alternative File Downloads](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/get-started/linux-macos-setup.html#alternative-file-downloads) and let us know if this helps?
