### ISSUE TITLE
Description of setting IDF_TOOLS_PATH (.espressif) (IDFGH-9044)

### ISSUE THREAD

**Issue by hwk-3boon1** [espressif/esp-idf#10451]
### Is your feature request related to a problem?

OS: Windows 10
IDF ver: v5.0 dirty ( - I edited idf_tools.py)

I'm in non-english country, so non-ascii characters is in my HOME path.
It maybe be cause of many struggle problems. So I installed on the root path (`C:/esp`)

Installing is successful, but some errors occurred during to run `export.bat`.

```
Adding ESP-IDF tools to PATH...
ERROR: tool xtensa-esp-elf-gdb has no installed versions. Please run 'C:\esp\esp-idf\install.bat' to
 install it.
ERROR: tool riscv32-esp-elf-gdb has no installed versions. Please run 'C:\esp\esp-idf\install.bat' t
o install it.
ERROR: tool xtensa-esp32-elf has no installed versions. Please run 'C:\esp\esp-idf\install.bat' to i
nstall it.
ERROR: tool xtensa-esp32s2-elf has no installed versions. Please run 'C:\esp\esp-idf\install.bat' to
 install it.
ERROR: tool xtensa-esp32s3-elf has no installed versions. Please run 'C:\esp\esp-idf\install.bat' to
 install it.
ERROR: tool riscv32-esp-elf has no installed versions. Please run 'C:\esp\esp-idf\install.bat' to in
stall it.
ERROR: tool esp32ulp-elf has no installed versions. Please run 'C:\esp\esp-idf\install.bat' to insta
ll it.
...(skip)
```

I caught the problem is path of `.espressif`, but didn't know where to fix it.
Edited `IDF_TOOLS_PATH_DEFAULT` global variable to `os.path.join('C:\\esp', '.espressif')` in `idf_tools.py` temporary.
But this isn't good way.

### Describe the solution you'd like.

I think there would be to ways.

1. Add description of `IDF_TOOLS_PATH` to '[Get Started](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/get-started/index.html)'
  - If still using `IDF_TOOLS_PATH` env variable, it could be clearly understanded and applied.
2. Add parameter about `tool path` to `idf_tools.py`
  - It already have `IDF_PATH` parameter. I think it is not that hard to add another path parameter.

### Describe alternatives you've considered.

It is just add the clean way to customize `IDF_TOOLS_PATH`.

**Comment by dobairoland** [comment]
Hi @hwk-3boon1. When you follow the linked getting started guide then it will suggest to you to use the Windows tool installer. It will set up a working environment and will not use the `.espressif` folder which is causing you the trouble. The getting started guide should be simple and satisfying for the needs of most of the users. Explaining `IDF_TOOLS_PATH` at that stage would confuse most of the users.

This kind of advanced information can be found at https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/tools/idf-tools.html.
