### ISSUE TITLE
ESP32S2 toolchain-esp32s2ulp build support on linux_aarch64/arm64 (IDFGH-9059)

### ISSUE THREAD

**Issue by hostirosti** [espressif/esp-idf#10463]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

1.22851.0

### Operating System used.

Linux

### How did you build your project?

Other (please specify in More Information)

### If you are using Windows, please specify command line type.

None

### What is the expected behavior?

Build esp32s2 esphome project on rpi4 64-bit OS.

Is there support for arm64 for platformio/toolchain-esp32s2ulp planned?

### What is the actual behavior?

According to https://registry.platformio.org/tools/platformio/toolchain-esp32s2ulp/compatibility `arm64` is not supported.

INFO Installing platformio/toolchain-esp32s2ulp @ ~1.22851.0
Error: Could not find the package with 'platformio/toolchain-esp32s2ulp @ ~1.22851.0' requirements for your system 'linux_aarch64'

### Steps to reproduce.

esphome config with

```
esp32:
  board: esp32-s2-saola-1
  framework:
    type: esp-idf
    version: recommended
```

### Build or installation Logs.

```plain
...
INFO Installing platformio/toolchain-esp32s2ulp @ ~1.22851.0
Error: Could not find the package with 'platformio/toolchain-esp32s2ulp @ ~1.22851.0' requirements for your system 'linux_aarch64'
...
```
```


### More Information.

_No response_

**Comment by igrr** [comment]
The ULP toolchain for arm64 Linux hosts is available on `master`, `release/v5.0` and `release/v4.4` branches of IDF. The release is also available here: https://github.com/espressif/binutils-gdb/releases/tag/esp32ulp-elf-v2.35_20220830

Regarding support in downstream projects, there were some comments in the original issue, please see if that helps: https://github.com/espressif/esp-idf/issues/6432#issuecomment-1279766713
