### ISSUE TITLE
Not able to store the characters "!", "@", "#" in flash (IDFGH-9057)

### ISSUE THREAD

**Issue by sriha99** [espressif/esp-idf#10461]
Hi, 

I am using esp-idf version 4.4.0. I am submitting an HTML form through a webpage hosted by the esp32 and storing the form's content in esp32's flash. I am not able to store special characters like "!", "@", and "#" in esp32 flash. Instead, their ASCII equivalent numbers are stored in flash. For example, if I submit the password as "!@#", it is getting received as "%21%40%23" when I submit through the form, and am not able to connect to the MQTT broker because of it. Can someone help me resolve this? I have attached the code where I extract data from the submitted HTML form.  Intention behind this form is to connect to mqtt broker with the credentials provided by the user.

`	char* mode = strtok(buf, "&");
	char* slaveId = strtok(NULL, "&");
	char* host = strtok(NULL, "&");
	char* port = strtok(NULL, "&");
	char* user = strtok(NULL, "&");
	char* pwd = strtok(NULL, "&");

	char* mode_key = strtok(mode,"=");
	char* mode_value = strtok(NULL,"=");
	ESP_LOGI(TAG,"%s:%s",mode_key, mode_value);

	char* slaveId_key = strtok(slaveId, "=");
	char* slaveId_value = strtok(NULL, "=");

	char* host_key = strtok(host, "=");
	char* host_value = strtok(NULL, "=");

	char* port_key = strtok(port, "=");
	char* port_value = strtok(NULL, "=");

	char* user_key = strtok(user, "=");
	char* user_value = strtok(NULL, "=");

	char* pwd_key = strtok(pwd, "=");
	char* pwd_value = strtok(NULL, "=");`

**Comment by chegewara** [comment]
The problem is not with storing special characters, which you can test storing it from code, without using website.
It is problem with your code, because you have encode/decode special characters received from web page.

https://github.com/zenmanenergy/ESP8266-Arduino-Examples/blob/master/helloWorld_urlencoded/urlencode.ino#L17

**Comment by sriha99** [comment]
Thank you for pointing out the mistake @chegewara. Will try to implement this in my code and get back to you.

**Comment by laukik-hase** [comment]
Closed with https://github.com/espressif/esp-idf/commit/167618d6a4e2cfcaab967ba2ba920df64fb4795d
