### ISSUE TITLE
fatal error: esp_crt_bundle.h: No such file or directory (IDFGH-9060)

### ISSUE THREAD

**Issue by kotyara12** [espressif/esp-idf#10464]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

4.4.3

### Operating System used.

Windows

### How did you build your project?

Command line with Make

### If you are using Windows, please specify command line type.

None

### What is the expected behavior?

After updating ESP-IDF from version 4.4.1 to version 4.4.3, the project stopped building:  fatal error: esp_crt_bundle.h: No such file or directory

### What is the actual behavior?

C:/PlatformIO/libs/clouds/reTgSend/src/reTgSend.cpp:63:12: fatal error: esp_crt_bundle.h: No such file or directory

************************************************************************
* Looking for esp_crt_bundle.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:esp_crt_bundle.h"
* Web  > https://registry.platformio.org/search?q=header:esp_crt_bundle.h
*
************************************************************************

   #include "esp_crt_bundle.h"
            ^~~~~~~~~~~~~~~~~~
compilation terminated.
*** [.pio\build\esp32dev\libdc6\reTgSend\reTgSend.o] Error 1

### Steps to reproduce.

**In PlatformIO** 
Update ESP-IDF from 4.4.1 to 4.4.3

**Comment by mahavirj** [comment]
@kotyara12 Can you please confirm that you have `CONFIG_MBEDTLS_CERTIFICATE_BUNDLE` enabled in your `sdkconfig`?
