### ISSUE TITLE
How does Provisioner know if a node in the mesh network is offline (IDFGH-9073)

### ISSUE THREAD

**Issue by Vanperdung** [espressif/esp-idf#10476]
### Answers checklist.

- [x] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

In section 1.19 in the [FAQ](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/esp-ble-mesh/ble-mesh-faq.html), it talk about how to detect an offline node in the mesh network.
How can Node send Heartbeat to Provisioner? I haven't found API related to it yet.

**Comment by Vanperdung** [comment]
Does anyone help me?

**Comment by JiaLWang** [comment]
Hi @Vanperdung ，

You can send `config heartbeat publication set` message to enable the node send heartbeats.

**Comment by Vanperdung** [comment]
Can you explain why this log "Ignoring old SeqAuth" appear? When I provision many Nodes, this log appears.

![Screenshot 2023-01-04 180417](https://user-images.githubusercontent.com/82029273/210542289-b9fb77ca-120d-407c-b5f8-1426b5577938.png)

**Comment by JiaLWang** [comment]
Means the node received an old SeqAuth packet and it will be discarded.

**Comment by Vanperdung** [comment]
When Provisioner sends Config heartbeat publication set, Node print "BLE_MESH: Ignoring heartbeat to non-subscribed destination". Did I do it wrong? Here is the code of provisioner: 
![Screenshot 2023-01-07 151325](https://user-images.githubusercontent.com/82029273/211140917-f27386d8-b323-4e7b-acef-8421324e4e8b.png)

**Comment by Vanperdung** [comment]
I fixed it. But where is the event ESP_BLE_MESH_MODEL_OP_HEARTBEAT_PUB_SET handled? I see it doesn't handle in config server callback.

**Comment by forx157** [comment]
Hi @Vanperdung ,
function `heartbeat_pub_set` in the `cfg_srv.c` will be trigged when a node receive the `ESP_BLE_MESH_MODEL_OP_HEARTBEAT_PUB_SET `, and update the heartbeat attribute  which was filled in the pub set msg you send. 
So the key issues have been handled internally, we don't need to handle it.
in addition, ESP_BLE_MESH_MODEL_OP_HEARTBEAT_PUB_SET is a opcode not a event.

**Comment by Vanperdung** [comment]
Hi @forx157 
Thanks for your answer.
Now I want nodes to be able to know when the provisioner is offline. I plan to have the provisioner publish to a group periodically and nodes subscribe to this group. Is there any other way?

**Comment by forx157** [comment]
@Vanperdung 
It depends on that how the provisioner goes to offline.
If it  is intentionally, you can send a msg to notify other node.
If it is unexpected, sending heatbeat msg periodically this is the only way I can think of.

**Comment by Vanperdung** [comment]
@forx157 
How can Provisioner send heartbeat to Nodes?

**Comment by forx157** [comment]
Hi @Vanperdung .
As mentioned above.
Node should use config client model send a heartbeat publication set message to provisioner to enable and set some attributes of  heartbeat, such as published destination, period, count and so on.
Then provisioner node's config server model  will handle that message, and start to send heartbeat message with the destination, period, and some other attributes which you set in the heartbeat set message.
Finally a node which could receive that destination the heartbeat send to will trigger a event `ESP_BLE_HEARTBEAT_MESSAGE_RECV_EVT` in the `bt_mesh_prov_cb` function when that node receive a heartbeat message.

**Comment by lebrislo** [comment]
> When Provisioner sends Config heartbeat publication set, Node print "BLE_MESH: Ignoring heartbeat to non-subscribed destination". Did I do it wrong? Here is the code of provisioner: ![Screenshot 2023-01-07 151325](https://user-images.githubusercontent.com/82029273/211140917-f27386d8-b323-4e7b-acef-8421324e4e8b.png)

Hi,

I have the same issue as you had "BLE_MESH: Ignoring heartbeat to non-subscribed destination". I see that you fixed that point. How did you manage to do so ?
