### ISSUE TITLE
binutils-gdb esp-gdb-v12.1_20221002 tag xtensaconfig submodule ref doesn't exist (IDFGH-9091)

### ISSUE THREAD

**Issue by noahp** [espressif/esp-idf#10495]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v5.0

### Operating System used.

Linux

### How did you build your project?

Command line with idf.py

### If you are using Windows, please specify command line type.

None

### What is the expected behavior?

Cloning this tag should succeed:
https://github.com/espressif/binutils-gdb/tree/esp-gdb-v12.1_20221002

### What is the actual behavior?

The `xtensaconfig` submodule ref from that tag does not exist on the remote:

```plaintext
fatal: remote error: upload-pack: not our ref 6b5601cbaa4abeaf0f379286a0b4160ffa6f0ed6
fatal: Fetched in submodule path 'xtensaconfig', but it did not contain 6b5601cbaa4abeaf0f379286a0b4160ffa6f0ed6. Direct fetching of that commit failed.
```

https://github.com/espressif/esp-xtensaconfig-lib/tree/6b5601cbaa4abeaf0f379286a0b4160ffa6f0ed6

### Steps to reproduce.

```bash
❯ git clone -b esp-gdb-v12.1_20221002 --recursive --depth=1 https://github.com/espressif/binutils-gdb.git
```

**Comment by antmak** [comment]
@noahp thank you for feedback, fixed now
