### ISSUE TITLE
ESP_LOG with no newline ?  (IDFGH-9090)

### ISSUE THREAD

**Issue by franz-ms-muc** [espressif/esp-idf#10494]
### Is your feature request related to a problem?

https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/log.html

this Logging Library always add a "\n" to every Printout. 
is there a way to not add such ?

**Comment by igrr** [comment]
Not really. ESP_LOG is assumed to output a single "log message", and the formatting is handled by the log library.
You can use printf or other stdio functions if you need to get specific output format for some custom message.

**Comment by KonstantinKondrashov** [comment]
I close this issue as no response, you can use printf or other stdio functions to implement any specific output format, feel free to reopen it.

**Comment by savenlid** [comment]
I also would like to be able to suppress new-line for ESP_LOGx

Maybe a ESP_LOGx_NONEWLINE(xxxx, xxxx)
