### ISSUE TITLE
uart.h:  Some function prototypes look inconsistent

### ISSUE THREAD

**Issue by krzychb** [espressif/esp-idf#105]
Hi,

Thank you for mass update of in-line documentation for `uart.h` in https://github.com/espressif/esp-idf/commit/d7599ab16d1504e2d75211f05562548665d905d3
I find it easier to follow now - http://esp-idf.readthedocs.io/en/latest/api/uart.html

I have question regarding "sister" function prototypes like below;

```c
esp_err_t uart_set_baudrate(uart_port_t uart_num, uint32_t baud_rate);
esp_err_t uart_get_baudrate(uart_port_t uart_num, uint32_t* baudrate);

esp_err_t uart_set_stop_bits(uart_port_t uart_num, uart_stop_bits_t bit_num);
esp_err_t uart_get_stop_bits(uart_port_t uart_num, uart_stop_bits_t* stop_bit);
```
Is there a reason for different name of baud rate or stop bits?

**Comment by igrr** [comment]
Fixed in 79482bbee7e74fdb754ccccf33370a4f13a4a727.
