### ISSUE TITLE
Unable to Connect 2 ESP32 via Serial Connection

### ISSUE THREAD

**Issue by lBenji** [espressif/esp-idf#1050]
1 ESP32
`int incomingByte = 0;
HardwareSerial Serial1(1);

#define SERIAL1_RXPIN 12
#define SERIAL1_TXPIN 13
void setup() {
  pinMode(inPin, INPUT);
  Serial.begin(115220); // opens serial port, sets data rate to 9600 bps
  Serial1.begin(9600, c, SERIAL1_RXPIN, SERIAL1_TXPIN);
}

void loop() {
if (Serial1.available() > 0) {
Serial.println("Data:");
incomingByte = Serial1.read(); // read the incoming byte:
Serial.println(incomingByte);
}
}`

2 ESP32
`
HardwareSerial Serial1(1);
#define SERIAL1_RXPIN 12
#define SERIAL1_TXPIN 13
void setup() {
  Serial1.begin(9600, SERIAL_8N1, SERIAL1_RXPIN, SERIAL1_TXPIN);
  Serial.begin(115220); 
}

void loop() {
  Serial.println("sending");
  Serial1.print("da");
  delay(500);
}`

At some time the Connection is working, but at the most time one of the ESPs printing:

_rst:0x10 (RTCWDT_RTC_RESET),boot:0x33 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
cmd len -1
Falling back to built-in command interpreter.
OK
_

**Comment by pufstudio** [comment]
Try using yield() in a loop on the 1st ESP.

**Comment by FayeY** [comment]
Hi @lBenji , did the above suggestion help you resolve the issue?
