### ISSUE TITLE
[TW#15697] Connecting issue with slave based on 4.1 core

### ISSUE THREAD

**Issue by kukushonok1987** [espressif/esp-idf#1051]
Hello
We are developing ble<-> wifi gateway and today we have faced with the following problem:
esp32 well works (in central role) with slaves which based on 4.0 and 4.2 cores but doesn't work with 4.1 devices. I have tested the following devices:
1. BlueNRG (core 4.0) - works well
2. BlueNRG-MS (core 4.1) doesn't work
3. EFR32BG1 (core 4.2) works well
4. Renesas chip RL78 (4.0) works well
5. Intel® Curie™ Module (4.2) works well

Please find attached sniffer logs for all mentioned devices. The common behavior for the 4.1 devices the following: after LL_Version_Ind response the exchange is stopped and event ESP_GATTC_OPEN_EVT don't occur. And after ~40 second I get disconnection with 0x0022 reason. Please help me to find the solution and please let me know if I can help to figure out the cause of the problem

[ble_sniffer_logs.zip](https://github.com/espressif/esp-idf/files/1344268/ble_sniffer_logs.zip)
![bluenrg_ms core 4 1](https://user-images.githubusercontent.com/26811132/31015153-5950489e-a527-11e7-83fb-675cff172e0d.jpg)
![blunnrg core_4 0](https://user-images.githubusercontent.com/26811132/31015154-5978a6ae-a527-11e7-94d5-aa27da855276.jpg)

Bluetooth logs:

E (45824) BT: BTM_InqDbRead: bd addr [000b5740a2bf]

E (45824) BT: btm_find_dev_type - device_type = 2 addr_type = 0
E (45824) BT: btm_find_or_alloc_dev

E (51084) BT: status = 0, handle = 0, role = 0, bda_type = 0
E (51084) BT: btm_identity_addr_to_random_pseudo
E (51084) BT: btm_ble_connected
E (51084) BT: btm_find_or_alloc_dev

E (51094) BT: btm_acl_created hci_handle=0 link_role=0  transport=2

E (51104) BT: btm_bda_to_acl found

E (51104) BT: device_type=0x2

E (51104) BT: btm_bda_to_acl found

E (51144) BT: btm_ble_read_remote_features_complete

E (91144) BT: btm_read_remote_version_complete

E (91144) BT: btm_bda_to_acl found

E (91144) BT: btm_establish_continue

E (91144) BT: btm_acl_update_busy_level

E (91154) BT: BTM_BLI_ACL_UP_EVT

E (91154) BT: btm_sec_is_a_bonded_dev() is_bonded=0

E (91164) BT: btm_sec_is_a_bonded_dev() is_bonded=0

E (91164) BT: bta_gattc_conn_cback() - cif=3 connected=0 conn_id=3 reason=0x0022
E (91174) BT: btm_acl_removed

E (91184) BT: btm_bda_to_acl found

E (91184) BT: btm_acl_report_role_change

E (91194) BT: btm_acl_update_busy_level

E (91194) BT: BTM_BLI_ACL_DOWN_EVT

E (91194) BT: acl hci_handle=0 transport=2 connectable_mode=0x0 link_role=0

E (91204) BT: before update p_dev_rec->sec_flags=0x80

E (91214) BT: LE link down

E (91214) BT: Not Bonded

E (91224) BT:

Thanks in advance,
Andrei Kukenov

**Comment by rrusak** [comment]
I have the same issue with Bluetooth based on 4.1 core, but I just switched to the devices with 4.2. It would be great to know the root of this issue. If you have solve this issue please contact me.
Thanks.

**Comment by kukushonok1987** [comment]
Hello, In additional
I have commented **btsnd_hcic_rmt_ver_req** and directly call **l2cble_notify_le_connection** and now all working fine but better to figure out why ll_version response of 4.1 devices causes the stack of hang

**Comment by Weijian-Espressif** [comment]
@kukushonok1987 , we will buy one BlueNRG-MS (core 4.1) and test.

**Comment by kukushonok1987** [comment]
@Weijian-Espressif, Thanks a lot, please, let me know if I can help you

**Comment by Weijian-Espressif** [comment]
@kukushonok1987  OK, thanks.

**Comment by Weijian-Espressif** [comment]
@kukushonok1987 , I have tested  BlueNRG-MS, I build stm32 SensorDemo and flash. it works Work very well.  can you update to the latest master and retry? 

I (3757) GATTC_DEMO: searched device BlueNRG                                    
                                                                                
I (3767) GATTC_DEMO: 4f 1c c7 7f dd 00                                          
I (3767) GATTC_DEMO: searched Adv Data Len 30, Scan Response Len 0              
I (3777) GATTC_DEMO: searched Device Name Len 0                                 
I (3777) GATTC_DEMO:                                                            
                                                                                
I (3777) GATTC_DEMO: 4f 1c c7 7f dd 00                                          
I (3787) GATTC_DEMO: searched Adv Data Len 30, Scan Response Len 0              
I (3797) GATTC_DEMO: searched Device Name Len 0                                 
I (3797) GATTC_DEMO:                                                            
                                                                                
I (3797) GATTC_DEMO: stop scan successfully                                     
I (3857) GATTC_DEMO: ESP_GATTC_CONNECT_EVT conn_id 0, if 3, status 0            
I (3867) GATTC_DEMO: REMOTE BDA:                                                
I (3867) GATTC_DEMO: 02 80 e1 00 34 12                                          
I (3867) GATTC_DEMO: open success                                               
I (4607) GATTC_DEMO: ESP_GATTC_SEARCH_RES_EVT                                   
I (4607) GATTC_DEMO: 1801                                                       
I (4607) GATTC_DEMO: ESP_GATTC_SEARCH_RES_EVT                                   
I (4607) GATTC_DEMO: 1800                                                       
I (4617) GATTC_DEMO: ESP_GATTC_SEARCH_RES_EVT                                   
I (4617) GATTC_DEMO: 1b c5 d5 a5 02 00 b4 9a e1 11 3a cf 80 6e 36 02            
I (4627) GATTC_DEMO: ESP_GATTC_SEARCH_RES_EVT                                   
I (4637) GATTC_DEMO: 1b c5 d5 a5 02 00 d0 82 e2 11 77 e4 40 1a 82 42            
I (4637) GATTC_DEMO: ESP_GATTC_SEARCH_CMPL_EVT

**Comment by Weijian-Espressif** [comment]
@kukushonok1987 Can you provide your hex files?

**Comment by kukushonok1987** [comment]
@ Weijian-Espressif Sorry for inconvenience, now I am in vacation I will be able to support you next week. Thanks a lot and sorry again

**Comment by Weijian-Espressif** [comment]
@kukushonok1987 thanks,. Now i have a X-NUCLEO-IDB05A1 and a STM32L053 board. What should I do to recurrence this issue?

**Comment by kukushonok1987** [comment]
@Weijian-Espressif  Hello, Today I have tested my app with new esp-idf and issue still reproduced:
ST provides some examples for bluenrg-ms board, could you start "SensorDemo_New" (for instance) and try to connect esp32 to bluerng-ms?

**Comment by Weijian-Espressif** [comment]
@kukushonok1987  Could you provide the  download link ?

**Comment by kukushonok1987** [comment]
@Weijian-Espressif please find link below, just pay attention that registration required 
https://my.st.com/content/ccc/resource/technical/software/application_sw/3a/37/97/ad/f6/47/47/d2/STSW-BLUENRG-DK.zip/files/STSW-BLUENRG-DK.zip/jcr:content/translations/en.STSW-BLUENRG-DK.zip

**Comment by Weijian-Espressif** [comment]
@kukushonok1987  Could you help me to test the issue? add some logs in btm_read_remote_version_complete() in btm_acl.c, line 888,  check if this function is called and then called l2cble_notify_le_connection().  Thanks.

**Comment by kukushonok1987** [comment]
@Weijian-Espressif  Sorry for delaying, now I am in busyness trip, I will provide log next week to you. Thanks a lot

**Comment by kukushonok1987** [comment]
@Weijian-Espressif  I have checked function btm_read_remote_version_complete is not called, please let me know if you need any help

**Comment by Weijian-Espressif** [comment]
@kukushonok1987 Thanks for your help. as you know, ESP32 as master will send btsnd_hcic_rmt_ver_req() when received feature response.Then ESP32 will send a connection success notification to the upper layer when get btm_read_remote_version_complete event.  

BlueNRG-MS send wrong ll_version_ind when exchange ble version, PDU_Length should be 6, controller throw away the wrong packet, so connection is timeout.
![default](https://user-images.githubusercontent.com/16891442/32940711-662456c4-cbbe-11e7-8135-0aeace62bfa2.PNG)

**Comment by kukushonok1987** [comment]
@Weijian-Espressif  ooo, thanks a lot for your help!

**Comment by AlpinProgrammer** [comment]
Hello,
As I understand it is an issue on the BlueNRG-MS's part.
How is it possible to solve the problem by modifying the ESP32 code ?
By commenting the following, it seems that it should resolve the issue. However, it does not solve the problem.
https://github.com/espressif/esp-idf/blob/463a9d8b7f9af8205222b80707f9bdbba7c530e1/components/bt/host/bluedroid/stack/btm/btm_ble_gap.c#L4110-L4126

Thanks in advance
