### ISSUE TITLE
Only one STA can join the SoftAP otherwise "max connection, deauth!" (IDFGH-9108)

### ISSUE THREAD

**Issue by wuyuanyi135** [espressif/esp-idf#10511]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v5.1-dev-2669-gd152d007c6

### Operating System used.

Windows

### How did you build your project?

Command line with idf.py

### If you are using Windows, please specify command line type.

PowerShell

### Development Kit.

ESP32-S3-WROOM-1-N16R2

### Power Supply used.

USB

### What is the expected behavior?

I created a softAP with the following code (SSID and password omitted)
```
wifi_config_t wifi_config = {};
wifi_config.ap.max_connection = 15;
wifi_config.ap.authmode = WIFI_AUTH_WPA2_PSK;
wifi_config.ap.ssid_hidden = 1;
```
Then 
```
esp_wifi_set_config(WIFI_IF_AP, &wifi_config);
esp_wifi_start();
```

I would like see multiple STA could join this AP

### What is the actual behavior?

After first STA joins, if the second one tried to join, the SoftAP gives 
```
W (82022) wifi: [ieee80211_hostap.c,1339] max connection, deauth!
```

### Steps to reproduce.

1. Flash the SoftAP code
2. let multiple client join the AP

**Comment by wuyuanyi135** [comment]
I bisected the issue. In `Component config → Wi-Fi` if ` Maximum espnow encrypt peers number` is set to `N` then the maximum number of client is implicitly limited to `17 - N`. For example, if `N=17`, no sta can associate to the AP. if `N=16`, only one sta can join the AP.

Is this a documentation issue or design flaw? I believe the inherent relation between ESPNOW peer number and STA limit is not documented yet.

**Comment by Xiehanxin** [comment]
![image](https://user-images.githubusercontent.com/37785066/211714731-b62c9c96-4e8e-4d98-a9cd-408031e7b3d2.png)
maybe your max_connection is too large.

**Comment by wuyuanyi135** [comment]
@Xiehanxin No. In `master` branch the maximum allowed connection for ESP32S3 is 15. I also tried set it to a lower number like 5, but it behaved the same. `Maximum espnow encrypt peers` still affects the number of clients.

**Comment by mhdong** [comment]
Hi @wuyuanyi135 
I'm very sorry for not responding in a timely manner. The document has been updated.
https://github.com/espressif/esp-idf/blob/5f4249357372f209fdd57288265741aaba21a2b1/docs/en/api-guides/wifi.rst#L1347

**Comment by Sherry616** [comment]
Thanks for reporting, we will close this issue. Feel free to reopen if have more updates.
