### ISSUE TITLE
settimeofday() availability  (IDFGH-9111) (IDFGH-9112)

### ISSUE THREAD

**Issue by sergioaiello** [espressif/esp-idf#10513]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

V5.0

### Operating System used.

Windows

### How did you build your project?

VS Code IDE

### If you are using Windows, please specify command line type.

None

### What is the expected behavior?

I'm using the function "settimeofday()" in a project.
In IDF V4.4 compiles correctly.
I expect similarly within V5.0.

### What is the actual behavior?

Within IDF V5.0 environment I got "implicit declaration of function 'settimeofday"

Which header file should I include?

### Steps to reproduce.

1. Step
2. Step
3. Step
...

**Comment by igrr** [comment]
https://github.com/espressif/esp-idf/issues/10413#issuecomment-1360666477

(https://linux.die.net/man/2/settimeofday)

**Comment by sergioaiello** [comment]
#include <[sys/time.h]>
Thank you
