### ISSUE TITLE
[TW#15699] EMAC Watchdog failed

### ISSUE THREAD

**Issue by welinkio** [espressif/esp-idf#1053]
Keep running http request or plug & unplug LAN, emacT task watchdog triggered.

Task watchdog CPU 0: emacT
Task watchdog got triggered. The following tasks did not feed the watchdog in time:
Tasks currently running:

Task watchdog got triggered. The following tasks did not feed the watchdog in time:
Tasks currently running:
CPU 0: emacT

**Comment by FayeY** [comment]
Hi, GPIO0 is the CLK for ethernet, so please do not use the GPIO0, use other GPIO instead.
