### ISSUE TITLE
How do I get the 64-byte ECDSA signature from ATECC608B?  (IDFGH-9166)

### ISSUE THREAD

**Issue by davmoz** [espressif/esp-idf#10562]
I'm trying to get the 64-byte ECDSA signature after signing from `signature`, but the returned size (`olen`) varies between 70-72 bytes. 
```
ESP_LOGI(TAG, " Generating ECDSA Signature...");
ret = mbedtls_pk_sign(&pkey, MBEDTLS_MD_SHA256, hash, 0, signature, MBEDTLS_MPI_MAX_SIZE, olen,
                          mbedtls_ctr_drbg_random, &ctr_drbg);
if (ret != 0)
{
    ESP_LOGI(TAG, " failed ! mbedtls_pk_sign returned -0x%04x", -ret);
    goto exit;
}

ESP_LOGI(TAG, " ok");
```
I'm using the following configuration:
```
CONFIG_MBEDTLS_ECP_DP_SECP256R1_ENABLED=y
```

I have also configured the project according to the instructions in this [example](https://github.com/espressif/esp-idf/tree/master/examples/peripherals/secure_element/atecc608_ecdsa), which currently I'm using. 

Any reason/pointers as to why the resulting signature size is not 64 bytes?

**Comment by mahavirj** [comment]
@davmoz 

ECDSA signature with [ASN.1 DER](https://www.rfc-editor.org/rfc/rfc3279#section-2.2.3) encoding can have its size up-to 73 bytes. Format looks like below:

```
 6  byte  | DER encoding overhead
 32 byte  | r-value
(1  byte) | r-value padding (if needed)
 32 byte  | S-value
(1  byte) | S-value padding (if needed)
 1  byte  | Signature Hash
```

APIs from `mbedtls/asn1.h` should help if you are looking for the actual `r` and `S` values from this format (probably `mbedtls_asn1_get_mpi`).

Side note: for general questions, please prefer using esp32.com forum
