### ISSUE TITLE
Using ADC single mode with a Faster clock on esp32s3 (IDFGH-9165)

### ISSUE THREAD

**Issue by 5ami** [espressif/esp-idf#10561]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Hi All, 
Is there a possibility to use the ADC single conversion with the DIG ADC  
as only The  RTC controllers can be used for single conversion mode.  the RTC controller runs on slow clock which makes the ADC reading super slow.
I am using ESP-IDF v5.0 and esp32s3

**Comment by suda-morris** [comment]
The TRMs says
![image](https://user-images.githubusercontent.com/8869469/213074792-fc4aa392-04f4-45dc-af76-df73e46617a5.png)

We use the RTC controller to do the single conversions.

**Comment by 5ami** [comment]
Is there a way to do a single reading using the continuous ADC mode ? is there is resource from Espressif explaining how the continuous mode works, the example shown in IDF5.0 didn't give stable values , and I couldn't get the idea of using a circular buffer why cant be a simple as triggering the ADC measurement according to the pattern table and read value from a register.

**Comment by 5ami** [comment]
Hi @suda-morris  also Why is there settings related changing the digital Controllers. 

[esp-idf](https://github.com/espressif/esp-idf)/[components](https://github.com/espressif/esp-idf/tree/master/components)/[hal](https://github.com/espressif/esp-idf/tree/master/components/hal)/adc_oneshot_hal.c
