### ISSUE TITLE
main task pointer (IDFGH-9175)

### ISSUE THREAD

**Issue by hyojincha** [espressif/esp-idf#10570]
I want to apply vTaskSuspend and vTaskReume to MainTask. How can I find the main task pointer?

**Comment by igrr** [comment]
You can call `xTaskGetCurrentTaskHandle()` from `app_main()` and store the resulting handle somewhere for later use.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to short of feedback, feel free to reopen with more updates. Thanks.
