### ISSUE TITLE
spp_server example question/issue (IDFGH-9207)

### ISSUE THREAD

**Issue by bheestandLMT** [espressif/esp-idf#10597]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

When running the example code for the spp_server under Nimbke BLE, I receive an error when a device is disconnected and a notification is sent.

Once a device disconnects, and I send a notification, I get error #7 for the disconnected device notification. (Other connected devices receive the notification OK)
  
I see an array is made to keep track of the connected devices 
`uint16_t connection_handle[CONFIG_BT_NIMBLE_MAX_CONNECTIONS];`

and that array is populated when a device connects:
`connection_handle[event->connect.conn_handle - 1] = event->connect.conn_handle;`

The connection never gets deleted from the connect_handle array on disconnect.
What is the proper way to remove the particular connection_handle when a device disconnects so that error #7 is not thrown when sending notifications.

Thanks!

**Comment by IshaESP** [comment]
Hi @bheestandLMT ,
Can you tell me on which chip you are facing this issue?

After disconnecting with one device, the connection_handle array is not being updated and while sending notifications it's giving error as the connection is not present. 
Can you try these two things:
1. In disconnect event, set connection_handle[event->connect.conn_handle - 1] as -1
2. Before sending notifications, add a check that if connection_handle[event->connect.conn_handle - 1] == -1 don't send the notification.

If the above doesn't work, can you please share the error logs with us?
Thank You.
