### ISSUE TITLE
ble_rpa_get_num_peer_dev_records() returned 0 even after bonding (IDFGH-9201)

### ISSUE THREAD

**Issue by veneno-529** [espressif/esp-idf#10591]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Development Kit: ESP32 Do it board
Module or chip used: ESP32
IDF version: v4.4.3
Build System: idf.py
Compiler version: xtensa-esp32-elf-gcc (crosstool-NG esp-2021r1) 8.4.0
Operating System: Windows
Using an IDE?: Yes (VS Code withe Platformio extension)
NimBLE version : 1.3.0

Problem Description
I am having problems with BLE bonding on android device.

Basically, what happens is that, after bonding one phone to the same ESP32 ( Android 12 phone). Everything works fine once bonded for first time. When I disconnect and connect it again the bonding fails and The only way to reconnect is to delete the old bond and reconnect. Still, the error will appear again.

The maximum number of bonds is set to 3.

I have noticed that peer device records restored displays zero. Even after bonding it.

Expected Behavior
After bonding was done, even after disconnecting and reconnecting again (Bond info still maintained on android) connection should be successful.

Actual Behavior
After bonding and disconnecting, then trying to reconnect it fails to connect successfully.

### Steps to reproduce
This is easily reproducible.

Bond Android 13 / Iphone
Once connected, Disconnect again. (Do not delete bond information from phone).
Try to reconnect again.
Code to reproduce this issue
I managed to reproduce the problem using the [bleprph ](https://github.com/espressif/esp-idf/tree/master/examples/bluetooth/nimble/bleprph)example. I have only added RPA address resolution to that example and I have attached the project files:
[bleprph.zip](https://github.com/espressif/esp-idf/files/10367600/bleprph.zip)

### Debug Logs
Logs : After erasing flash, uploading firmware, booting for first time and connecting android phone for first time
D (2601) NIMBLE_NVS: ble_store_config_cccds restored 0 bonds
D (2611) nvs: nvs_open_from_partition nimble_bond 1
D (2611) nvs: nvs_get_str_or_blob p_dev_rec_1
D (2621) nvs: nvs_close 40
D (2621) nvs: nvs_open_from_partition nimble_bond 1
D (2621) nvs: nvs_get_str_or_blob p_dev_rec_2
D (2631) nvs: nvs_close 41
D (2631) nvs: nvs_open_from_partition nimble_bond 1
D (2641) nvs: nvs_get_str_or_blob p_dev_rec_3
D (2641) nvs: nvs_close 42
D (2641) nvs: nvs_open_from_partition nimble_bond 1
D (2651) nvs: nvs_get_str_or_blob p_dev_rec_4
D (2651) nvs: nvs_close 43
D (2661) NIMBLE_NVS: peer_dev_rec restored 0 records
I (2661) NimBLE_BLE_PRPH: BLE Host Task Started
D (2671) NimBLE: registered service 0x1800 with handle=1

D (2671) NimBLE: registering characteristic 0x2a00 with def_handle=2 val_handle=3

D (2681) NimBLE: registering characteristic 0x2a01 with def_handle=4 val_handle=5

D (2691) NimBLE: registered service 0x1801 with handle=6

D (2691) NimBLE: registering characteristic 0x2a05 with def_handle=7 val_handle=8

D (2701) NimBLE: registered service 59462f12-9543-9999-12c8-58b459a2712d with handle=10

D (2711) NimBLE: registering characteristic 5c3a659e-897e-45e1-b016-007107c96df6 with def_handle=11 val_handle=12

D (2721) NimBLE: registering characteristic 5c3a659e-897e-45e1-b016-007107c96df7 with def_handle=13 val_handle=14

I (2731) uart: queue free spaces: 8
V (2731) intr_alloc: esp_intr_alloc_intrstatus (cpu 1): checking args
V (2741) intr_alloc: esp_intr_alloc_intrstatus (cpu 1): Args okay. Resulting flags 0xE
D (2751) intr_alloc: Connected src 34 to int 3 (cpu 1)
I (2771) NimBLE: Device Address:
I (2771) NimBLE: 5b:13:6d:d2:73:35
I (2771) NimBLE:

I (2781) NimBLE: GAP procedure initiated: advertise;
I (2781) NimBLE: disc_mode=2
I (2781) NimBLE: adv_channel_map=0 own_addr_type=1 adv_filter_policy=0 adv_itvl_min=0 adv_itvl_max=0
I (2791) NimBLE:

I (15311) NimBLE: connection established; status=0
I (15321) NimBLE: handle=0 our_ota_addr_type=1 our_ota_addr=
I (15321) NimBLE: 5b:13:6d:d2:73:35
I (15321) NimBLE: our_id_addr_type=1 our_id_addr=
I (15331) NimBLE: 5b:13:6d:d2:73:35
I (15331) NimBLE: peer_ota_addr_type=0 peer_ota_addr=
I (15341) NimBLE: 2c:be:eb:27:93:6f
I (15341) NimBLE: peer_id_addr_type=0 peer_id_addr=
I (15341) NimBLE: 2c:be:eb:27:93:6f
I (15351) NimBLE: conn_itvl=24 conn_latency=0 supervision_timeout=500 encrypted=0 authenticated=0 bonded=0

I (15361) NimBLE:

I (15811) NimBLE: connection updated; status=0
I (15811) NimBLE: handle=0 our_ota_addr_type=1 our_ota_addr=
I (15811) NimBLE: 5b:13:6d:d2:73:35
I (15821) NimBLE: our_id_addr_type=1 our_id_addr=
I (15821) NimBLE: 5b:13:6d:d2:73:35
I (15831) NimBLE: peer_ota_addr_type=0 peer_ota_addr=
I (15831) NimBLE: 2c:be:eb:27:93:6f
I (15841) NimBLE: peer_id_addr_type=0 peer_id_addr=
I (15841) NimBLE: 2c:be:eb:27:93:6f
I (15851) NimBLE: conn_itvl=6 conn_latency=0 supervision_timeout=500 encrypted=0 authenticated=0 bonded=0

I (15861) NimBLE:

I (16071) NimBLE: connection updated; status=0
I (16071) NimBLE: handle=0 our_ota_addr_type=1 our_ota_addr=
I (16071) NimBLE: 5b:13:6d:d2:73:35
I (16071) NimBLE: our_id_addr_type=1 our_id_addr=
I (16081) NimBLE: 5b:13:6d:d2:73:35
I (16081) NimBLE: peer_ota_addr_type=0 peer_ota_addr=
I (16091) NimBLE: 2c:be:eb:27:93:6f
I (16091) NimBLE: peer_id_addr_type=0 peer_id_addr=
I (16101) NimBLE: 2c:be:eb:27:93:6f
I (16101) NimBLE: conn_itvl=24 conn_latency=0 supervision_timeout=500 encrypted=0 authenticated=0 bonded=0

I (16111) NimBLE:

I (22681) NimBLE: encryption change event; status=0
I (22681) NimBLE: handle=0 our_ota_addr_type=1 our_ota_addr=
I (22681) NimBLE: 5b:13:6d:d2:73:35
I (22691) NimBLE: our_id_addr_type=1 our_id_addr=
I (22691) NimBLE: 5b:13:6d:d2:73:35
I (22701) NimBLE: peer_ota_addr_type=0 peer_ota_addr=
I (22701) NimBLE: 2c:be:eb:27:93:6f
I (22711) NimBLE: peer_id_addr_type=0 peer_id_addr=
I (22711) NimBLE: 2c:be:eb:27:93:6f
I (22721) NimBLE: conn_itvl=24 conn_latency=0 supervision_timeout=500 encrypted=1 authenticated=0 bonded=1

**Logs : After disconnecting **
I (68012) NimBLE: subscribe event; conn_handle=0 attr_handle=8 reason=2 prevn=0 curn=0 previ=1 curi=0

I (68012) NimBLE: disconnect; reason=531
I (68022) NimBLE: handle=0 our_ota_addr_type=1 our_ota_addr=
I (68022) NimBLE: 7a:3a:2b:f1:0b:84
I (68032) NimBLE: our_id_addr_type=0 our_id_addr=
I (68032) NimBLE: 0c:b8:15:f6:92:f2
I (68042) NimBLE: peer_ota_addr_type=0 peer_ota_addr=
I (68042) NimBLE: 2c:be:eb:27:93:6f
I (68052) NimBLE: peer_id_addr_type=0 peer_id_addr=
I (68052) NimBLE: 2c:be:eb:27:93:6f
I (68062) NimBLE: conn_itvl=24 conn_latency=0 supervision_timeout=500 encrypted=1 authenticated=0 bonded=1

I (68072) NimBLE:

E (68072) NimBLE_BLE_PRPH: ble_rpa_get_num_peer_dev_records() returned 0
I (68082) NimBLE: GAP procedure initiated: advertise;
I (68082) NimBLE: disc_mode=2
I (68092) NimBLE: adv_channel_map=0 own_addr_type=1 adv_filter_policy=0 adv_itvl_min=0 adv_itvl_max=0
I (68102) NimBLE:

LOG : After reconnecting
I (406681) NimBLE: connection established; status=0
I (406681) NimBLE: handle=0 our_ota_addr_type=1 our_ota_addr=
I (406681) NimBLE: 60:7b:29:00:45:0b
I (406681) NimBLE: our_id_addr_type=1 our_id_addr=
I (406691) NimBLE: 60:7b:29:00:45:0b
I (406691) NimBLE: peer_ota_addr_type=1 peer_ota_addr=
I (406701) NimBLE: 68:bc:48:03:92:84
I (406701) NimBLE: peer_id_addr_type=1 peer_id_addr=
I (406711) NimBLE: 68:bc:48:03:92:84
I (406711) NimBLE: conn_itvl=24 conn_latency=0 supervision_timeout=500 encrypted=0 authenticated=0 bonded=0

I (406731) NimBLE:

I (407171) NimBLE: connection updated; status=0
I (407181) NimBLE: handle=0 our_ota_addr_type=1 our_ota_addr=
I (407181) NimBLE: 60:7b:29:00:45:0b
I (407181) NimBLE: our_id_addr_type=1 our_id_addr=
I (407191) NimBLE: 60:7b:29:00:45:0b
I (407191) NimBLE: peer_ota_addr_type=1 peer_ota_addr=
I (407201) NimBLE: 68:bc:48:03:92:84
I (407201) NimBLE: peer_id_addr_type=1 peer_id_addr=
I (407211) NimBLE: 68:bc:48:03:92:84
I (407211) NimBLE: conn_itvl=6 conn_latency=0 supervision_timeout=500 encrypted=0 authenticated=0 bonded=0

I (407221) NimBLE:

lld_pdu_get_tx_flush_nb HCI packet count mismatch (0, 1)
I (408921) NimBLE: disconnect; reason=543
I (408921) NimBLE: handle=0 our_ota_addr_type=1 our_ota_addr=
I (408921) NimBLE: 60:7b:29:00:45:0b
I (408931) NimBLE: our_id_addr_type=1 our_id_addr=
I (408931) NimBLE: 60:7b:29:00:45:0b
I (408941) NimBLE: peer_ota_addr_type=1 peer_ota_addr=
I (408941) NimBLE: 68:bc:48:03:92:84
I (408951) NimBLE: peer_id_addr_type=1 peer_id_addr=
I (408951) NimBLE: 68:bc:48:03:92:84
I (408961) NimBLE: conn_itvl=6 conn_latency=0 supervision_timeout=500 encrypted=0 authenticated=0 bonded=0

I (408971) NimBLE:

I (408981) NimBLE: GAP procedure initiated: advertise;
I (408981) NimBLE: disc_mode=2
I (408981) NimBLE: adv_channel_map=0 own_addr_type=1 adv_filter_policy=0 adv_itvl_min=0 adv_itvl_max=0
I (408991) NimBLE:

Log : After restarting ESP32 (Bond info not deleted from android)

D (2151) nvs: nvs_open_from_partition nimble_bond 1
D (2151) nvs: nvs_get_str_or_blob our_sec_1
D (2151) nvs: nvs_get_str_or_blob our_sec_1
D (2151) nvs: nvs_close 2
D (2151) NIMBLE_NVS: KEY in RAM is filled up from NVS index = 1
D (2161) nvs: nvs_open_from_partition nimble_bond 1
D (2161) nvs: nvs_get_str_or_blob our_sec_2
D (2171) nvs: nvs_close 3
D (2171) nvs: nvs_open_from_partition nimble_bond 1
D (2171) nvs: nvs_get_str_or_blob our_sec_3
D (2181) nvs: nvs_close 4
D (2181) NIMBLE_NVS: ble_store_config_our_secs restored 1 bonds
D (2191) nvs: nvs_open_from_partition nimble_bond 1
D (2191) nvs: nvs_get_str_or_blob peer_sec_1
D (2201) nvs: nvs_get_str_or_blob peer_sec_1
D (2201) nvs: nvs_close 5
D (2201) NIMBLE_NVS: KEY in RAM is filled up from NVS index = 1
D (2211) nvs: nvs_open_from_partition nimble_bond 1
D (2211) nvs: nvs_get_str_or_blob peer_sec_2
D (2221) nvs: nvs_close 6
D (2221) nvs: nvs_open_from_partition nimble_bond 1
D (2231) nvs: nvs_get_str_or_blob peer_sec_3
D (2231) nvs: nvs_close 7
D (2231) NIMBLE_NVS: ble_store_config_peer_secs restored 1 bonds
D (2241) nvs: nvs_open_from_partition nimble_bond 1
D (2241) nvs: nvs_get_str_or_blob cccd_sec_1
D (2251) nvs: nvs_get_str_or_blob cccd_sec_1
D (2251) nvs: nvs_close 8
D (2261) NIMBLE_NVS: CCCD in RAM is filled up from NVS index = 1
D (2261) nvs: nvs_open_from_partition nimble_bond 1
D (2271) nvs: nvs_get_str_or_blob cccd_sec_2
D (2271) nvs: nvs_close 9
D (2271) nvs: nvs_open_from_partition nimble_bond 1
D (2281) nvs: nvs_get_str_or_blob cccd_sec_3
D (2281) nvs: nvs_close 10
D (2291) nvs: nvs_open_from_partition nimble_bond 1
D (2291) nvs: nvs_get_str_or_blob cccd_sec_4
D (2301) nvs: nvs_close 11
D (2301) nvs: nvs_open_from_partition nimble_bond 1
D (2301) nvs: nvs_get_str_or_blob cccd_sec_5
D (2311) nvs: nvs_close 12
D (2311) nvs: nvs_open_from_partition nimble_bond 1
D (2311) nvs: nvs_get_str_or_blob cccd_sec_6
D (2321) nvs: nvs_close 13
D (2321) nvs: nvs_open_from_partition nimble_bond 1
D (2331) nvs: nvs_get_str_or_blob cccd_sec_7
D (2331) nvs: nvs_close 14
D (2331) nvs: nvs_open_from_partition nimble_bond 1
D (2341) nvs: nvs_get_str_or_blob cccd_sec_8
D (2341) nvs: nvs_close 15
D (2351) nvs: nvs_open_from_partition nimble_bond 1
D (2351) nvs: nvs_get_str_or_blob cccd_sec_9
D (2361) nvs: nvs_close 16
D (2361) nvs: nvs_open_from_partition nimble_bond 1
D (2361) nvs: nvs_get_str_or_blob cccd_sec_10
D (2371) nvs: nvs_close 17
D (2371) nvs: nvs_open_from_partition nimble_bond 1
D (2381) nvs: nvs_get_str_or_blob cccd_sec_11
D (2381) nvs: nvs_close 18
D (2381) nvs: nvs_open_from_partition nimble_bond 1
D (2391) nvs: nvs_get_str_or_blob cccd_sec_12
D (2391) nvs: nvs_close 19
D (2391) nvs: nvs_open_from_partition nimble_bond 1
D (2401) nvs: nvs_get_str_or_blob cccd_sec_13
D (2401) nvs: nvs_close 20
D (2411) nvs: nvs_open_from_partition nimble_bond 1
D (2411) nvs: nvs_get_str_or_blob cccd_sec_14
D (2421) nvs: nvs_close 21
D (2421) nvs: nvs_open_from_partition nimble_bond 1
D (2421) nvs: nvs_get_str_or_blob cccd_sec_15
D (2431) nvs: nvs_close 22
D (2431) nvs: nvs_open_from_partition nimble_bond 1
D (2441) nvs: nvs_get_str_or_blob cccd_sec_16
D (2441) nvs: nvs_close 23
D (2441) nvs: nvs_open_from_partition nimble_bond 1
D (2451) nvs: nvs_get_str_or_blob cccd_sec_17
D (2451) nvs: nvs_close 24
D (2461) nvs: nvs_open_from_partition nimble_bond 1
D (2461) nvs: nvs_get_str_or_blob cccd_sec_18
D (2461) nvs: nvs_close 25
D (2471) nvs: nvs_open_from_partition nimble_bond 1
D (2471) nvs: nvs_get_str_or_blob cccd_sec_19
D (2481) nvs: nvs_close 26
D (2481) nvs: nvs_open_from_partition nimble_bond 1
D (2481) nvs: nvs_get_str_or_blob cccd_sec_20
D (2491) nvs: nvs_close 27
D (2491) nvs: nvs_open_from_partition nimble_bond 1
D (2501) nvs: nvs_get_str_or_blob cccd_sec_21
D (2501) nvs: nvs_close 28
D (2501) nvs: nvs_open_from_partition nimble_bond 1
D (2511) nvs: nvs_get_str_or_blob cccd_sec_22
D (2511) nvs: nvs_close 29
D (2521) nvs: nvs_open_from_partition nimble_bond 1
D (2521) nvs: nvs_get_str_or_blob cccd_sec_23
D (2531) nvs: nvs_close 30
D (2531) nvs: nvs_open_from_partition nimble_bond 1
D (2531) nvs: nvs_get_str_or_blob cccd_sec_24
D (2541) nvs: nvs_close 31
D (2541) nvs: nvs_open_from_partition nimble_bond 1
D (2551) nvs: nvs_get_str_or_blob cccd_sec_25
D (2551) nvs: nvs_close 32
D (2551) nvs: nvs_open_from_partition nimble_bond 1
D (2561) nvs: nvs_get_str_or_blob cccd_sec_26
D (2561) nvs: nvs_close 33
D (2561) nvs: nvs_open_from_partition nimble_bond 1
D (2571) nvs: nvs_get_str_or_blob cccd_sec_27
D (2571) nvs: nvs_close 34
D (2581) nvs: nvs_open_from_partition nimble_bond 1
D (2581) nvs: nvs_get_str_or_blob cccd_sec_28
D (2591) nvs: nvs_close 35
D (2591) nvs: nvs_open_from_partition nimble_bond 1
D (2591) nvs: nvs_get_str_or_blob cccd_sec_29
D (2601) nvs: nvs_close 36
D (2601) nvs: nvs_open_from_partition nimble_bond 1
D (2611) nvs: nvs_get_str_or_blob cccd_sec_30
D (2611) nvs: nvs_close 37
D (2611) nvs: nvs_open_from_partition nimble_bond 1
D (2621) nvs: nvs_get_str_or_blob cccd_sec_31
D (2621) nvs: nvs_close 38
D (2631) nvs: nvs_open_from_partition nimble_bond 1
D (2631) nvs: nvs_get_str_or_blob cccd_sec_32
D (2631) nvs: nvs_close 39
D (2641) NIMBLE_NVS: ble_store_config_cccds restored 1 bonds
D (2641) nvs: nvs_open_from_partition nimble_bond 1
D (2651) nvs: nvs_get_str_or_blob p_dev_rec_1
D (2651) nvs: nvs_close 40
D (2661) nvs: nvs_open_from_partition nimble_bond 1
D (2661) nvs: nvs_get_str_or_blob p_dev_rec_2
D (2661) nvs: nvs_close 41
D (2671) nvs: nvs_open_from_partition nimble_bond 1
D (2671) nvs: nvs_get_str_or_blob p_dev_rec_3
D (2681) nvs: nvs_close 42
D (2681) nvs: nvs_open_from_partition nimble_bond 1
D (2681) nvs: nvs_get_str_or_blob p_dev_rec_4
D (2691) nvs: nvs_close 43
D (2691) NIMBLE_NVS: peer_dev_rec restored 0 records
I (2701) NimBLE_BLE_PRPH: BLE Host Task Started
D (2701) NimBLE: registered service 0x1800 with handle=1

D (2711) NimBLE: registering characteristic 0x2a00 with def_handle=2 val_handle=3

D (2721) NimBLE: registering characteristic 0x2a01 with def_handle=4 val_handle=5

D (2721) NimBLE: registered service 0x1801 with handle=6

D (2731) NimBLE: registering characteristic 0x2a05 with def_handle=7 val_handle=8

D (2741) NimBLE: registered service 59462f12-9543-9999-12c8-58b459a2712d with handle=10

D (2741) NimBLE: registering characteristic 5c3a659e-897e-45e1-b016-007107c96df6 with def_handle=11 val_handle=12

D (2761) NimBLE: registering characteristic 5c3a659e-897e-45e1-b016-007107c96df7 with def_handle=13 val_handle=14

I (2771) uart: queue free spaces: 8
V (2771) intr_alloc: esp_intr_alloc_intrstatus (cpu 1): checking args
V (2781) intr_alloc: esp_intr_alloc_intrstatus (cpu 1): Args okay. Resulting flags 0xE
D (2781) intr_alloc: Connected src 34 to int 3 (cpu 1)
I (2811) NimBLE: Device Address:
I (2811) NimBLE: 5d:4f:bc:40:76:32
I (2811) NimBLE:

I (2821) NimBLE: GAP procedure initiated: advertise;
I (2821) NimBLE: disc_mode=2
I (2821) NimBLE: adv_channel_map=0 own_addr_type=1 adv_filter_policy=0 adv_itvl_min=0 adv_itvl_max=0
I (2831) NimBLE

Notice that even after device was bonded peer records restored is 0.

**Comment by IshaESP** [comment]
Hi,
I tried reproducing the issue locally using ESP32 and android 13 phone. But it is working without any error.
Can you send me sdkconfig of the application?

Also I can't find `E (68072) NimBLE_BLE_PRPH: ble_rpa_get_num_peer_dev_records() returned 0` this print in the application shared on github. Is something else being done apart from the code shared?

**Comment by veneno-529** [comment]
Hi @IshaESP 
I hope you have used the code from the zip file attached. I have added only RPA feature to the bleprph example which is there on github. I tried it with esp ide as well as platform io too. Can you share your code or maybe details of esp idf version and nimble version?

**Comment by IshaESP** [comment]
Hey @veneno-529 
Steps I used to reproduce the issue:

- idf.py erase_flash
- Connect using nrf application
- Bond with esp32 from nrf app (There is a 'bond' option in collapsible tab indicated using 3 vertical dots at top right corner of the application)
- Disconnect
- Reconnect 
- Disconnect again
- Boot esp32
- Connect again

After executing these steps it connects successfully.

IDF version : v4.4.3 (commit - 6407ecb3f8d2cc07c4c230e7e64f2046af5c86f7)
NimBLE version : v1.3.0 (commit - ed8a4b14ad43d88f2ec8913aab5af919208722e5)

I am attaching debug prints patch and output of the same zip file code shared: [IDFGH-10591.zip](https://github.com/espressif/esp-idf/files/10755252/IDFGH-10591.zip)

**Comment by veneno-529** [comment]
> 

Hello @IshaESP 
I just upgraded to ESP-IDF 5.0 and Nimble v1.4.0 and everything works fine now.
I will still try your patch and check if I'm getting the same output as yours.
Thanks for your response!

**Comment by veneno-529** [comment]
It turns out that the below feature highlighted in menuconfig needs to be enabled.
![image](https://user-images.githubusercontent.com/68317284/219871558-e94ca3ba-6652-4b5f-961f-2b5d438d4323.png)
Now I got the logs same as yours and device connects and reconnects successfully even after restarting it.
