### ISSUE TITLE
system_deep_sleep works?

### ISSUE THREAD

**Issue by jolivepetrus** [espressif/esp-idf#106]
I attach a test code, extracted from 06_sntp example. In previous comments we cloud enter  the CPU in sleep mode in a similar way as exposed in test code.

In test code CPU doesn't enter in deep sleep.

[sdkconfig.txt](https://github.com/espressif/esp-idf/files/597500/sdkconfig.txt)
[sntp_main.txt](https://github.com/espressif/esp-idf/files/597501/sntp_main.txt)

**Comment by igrr** [comment]
@jolivepetrus, please try running the example with the latest code in master. `system_deep_sleep` has been rewritten and the example is working in my tests.

**Comment by jolivepetrus** [comment]
Perfect, I confirm that with latest code in master system_deep_sleep works fine.

Thanks.
