### ISSUE TITLE
examples\system\sysview_tracing unstable openocd connection in dual core  (IDFGH-9216)

### ISSUE THREAD

**Issue by antoDimaggio** [espressif/esp-idf#10604]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

**IDF version.**
master

**Operating System used.**
Windows

**How did you build your project?**
Command line with idf.py

**If you are using Windows, please specify command line type.**
ESP-IDF CMD

**Hardware**
ESP32-S3-DevKitC-1

**Issue description**
I made two very little modification to the sysview tracing example:
1. I increased the timers frequency by 10.
`event_data[i].period = 100000 * (i + 1);`
3. I increased the number of iterations in order to let it run forever:
`if (tim_arg->count++ < INT_MAX) {`

I compiled in dual core mode.

Than I flashed, started a monitor, launched openocd with:
`openocd -f board/esp32s3-builtin.cfg`
And after started sysvire tracing via telnet 
`esp sysview start pro-cpu.SVDat app-cpu.SVDat 1 -1 -1`

After a while (10 to 100 seconds) openocd exits with error:
```
1395454
1395707
1395960
Error: Incomplete block sz 2, wr 56
```
I increased the verbosity of openocd but I did non find more info.

**Other Info**
I have the same problem on IDF v4.4.3
I changed JTAG clock frequency from default (40M) to 10M and 20MHz.
Rising the verbosity of the terminal I can see that the target is running and stacked in apptrace module code.

**Comment by KonssnoK** [comment]
could you tell us when it's going to be propagated to 4.4.5 ? thanks

**Comment by antoDimaggio** [comment]
The issue should be reopened.
I tested the bug fix and had the same bahaviour.
I also tried to update the esp-idf and to re-run the example but than I got different errors reported on this new issue
https://github.com/espressif/esp-idf/issues/12268
We are not yet able to reliably perform tracing on ESP32-S3
