### ISSUE TITLE
ESP v5.0 removed mdns Why? (IDFGH-9213)

### ISSUE THREAD

**Issue by versamodule** [espressif/esp-idf#10601]
In v4.4.3 we had mdns which I was using.
Upgraded to v5.0 and its gone.
Why did they remove it from the components folder, and examples ?

**Comment by wuyuanyi135** [comment]
https://components.espressif.com/components/espressif/mdns

**Comment by dobairoland** [comment]
I have replied here: https://esp32.com/viewtopic.php?f=2&t=31770
