### ISSUE TITLE
IDF 5.0 Sending RMT symbols directly without using any encoder (IDFGH-9229)

### ISSUE THREAD

**Issue by blacksmith0040** [espressif/esp-idf#10616]
### Is your feature request related to a problem?

The problem is IDF 5.0 doesn't support sending RMT symbols directly. I don't want to manually enter a hexcode and use encoder. Because I already captured data with RMT receiver and I'd like to send those RMT symbols.

### Describe the solution you'd like.

Sending RMT symbols is supported on previous versions. I need this support in IDF 5.0

### Describe alternatives you've considered.

I've thought porting my project back to 4.4&4.3 but that's impossible for security reasons. 

### Additional context.

Thanks in advance.

**Comment by suda-morris** [comment]
I think you can use the [copy encoder](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/peripherals/rmt.html#copy-encoder) to send your raw RMT symbols, similar to the way used in the legacy driver.
