### ISSUE TITLE
Wifi : "wifi:m f null" losing connection. (IDFGH-9263)

### ISSUE THREAD

**Issue by Coffeeye** [espressif/esp-idf#10646]
Fixed... sorry

**Comment by LeBellier** [comment]
I still have this problem. Can you share the commit containing the fix?

**Comment by Coffeeye** [comment]
> I still have this problem. Can you share the commit containing the fix?

It all strictly reference to actual debug prints of your wifi module. I had no other prints than this one, nothing about memory allocation or whatsoever. In fact I still didnt manage to completly avoid the issue.
