### ISSUE TITLE
COMMUNICATION LATENCY ON HTTP SERVER doesn't go down below 30 ms. (IDFGH-9281)

### ISSUE THREAD

**Issue by Inverter-Jo** [espressif/esp-idf#10665]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

In tcp server, the average of communication latency is less than 7 ms.

I am using http server.
I call on the local network, but it doesn't go down below 30 ms.
What options do I need to see?

I checked ...
esp_wifi_set_ps(false);
CONFIG_ESP32_WIFI_AMPDU_TX_ENABLED = y -> false;
CONFIG_ESP32_WIFI_AMPDU_RX_ENABLED = y -> false;

**Comment by Inverter-Jo** [comment]
checked...
CONFIG_HTTPD_ERR_RESP_NO_DELAY= false

**Comment by hmalpani** [comment]
Hello @Inverter-Jo
This might help you improve the performance: https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/performance/speed.html#improving-network-speed

Closing this issue. Please feel free to reopen.
