### ISSUE TITLE
Host name while connecting Wi-Fi

### ISSUE THREAD

**Issue by xarrange** [espressif/esp-idf#1066]
Hi,
Is there any normal way to change DHCP hostname other then editing "port/netif/wlanif.c"?
If not, I guess it's worth to add it

**Comment by projectgus** [comment]
Yes, the value set here is only a default. You can call tcpip_adapter_set_hostname() to change it for a particular interface:
https://github.com/espressif/esp-idf/blob/master/components/tcpip_adapter/include/tcpip_adapter.h#L523

This header's API is not the in the documentation, but should be - I'll raise an issue internally for that.

Angus
