### ISSUE TITLE
Add ESP_IDF_VERSION=4.4 to the environment settings in up-coming ESP-IDF v4.4.4 (IDFGH-9295)

### ISSUE THREAD

**Issue by JBHunterI** [espressif/esp-idf#10677]
### Is your feature request related to a problem?

Please add ESP_IDF_VERSION=4.4 to the environment settings in IDF v4.4.4, as is done in IDF v5.0 and thus making it easier to use scripts between those 2 versions of ESP-IDF. 

### Describe the solution you'd like.

Upon starting any ESP-IDF v4.4.4 command shell, the use can rely on the environment variable ESP_IDF_VERSION being set to 4.4 for any scrips to use.

### Describe alternatives you've considered.
At the very least, at the very bottom of %IDF_PATH%\export.bat, please add:
if %ERRORLEVEL% NEQ 0 (
    echo error %ERRORLEVEL% occured, end this script, leave this cmd window
    goto :eof
)
:: Check for a user customization script is present, and skip it if one is not.
if NOT EXIST ..\user_customization.cmd    goto :eof

:: Clear return code then call user customization script.
set "ERRORLEVEL=1"
set "ERRORLEVEL="
(call )
echo a customization script exists, calling it now that return code was cleared to %ERRORLEVEL%
call ..\user_customization.cmd
echo customization script returned %ERRORLEVEL%
if %ERRORLEVEL% GTR 0 (
    echo user customization succeeded with %ERRORLEVEL%, closing this cmd window
    exit
)
if %ERRORLEVEL% LSS 0 (
    echo user customization failed with error %ERRORLEVEL%
)
:: else %ERRORLEVEL% EQU 0 leaving this cmd window open

Ideally, both this and ESP_IDF_VERSION=4.4 would be added to the IDF v4.4.4 release & the current IDF v5.0 release branch.

**Comment by mfialaf** [comment]
The environment variable was added in b5b0b4d.
