### ISSUE TITLE
如何更新Lvgl的版本？ (IDFGH-9288)

### ISSUE THREAD

**Issue by Szeroy** [espressif/esp-idf#10671]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

使用idfv5.0里面的例程，但是例程使用的是Lvgl v8.2的版本，Lvgl组件还有版本保护的，我应该如何更新到v8.3的版本呢？

**Comment by suda-morris** [comment]
https://github.com/espressif/esp-idf/blob/master/examples/peripherals/lcd/spi_lcd_touch/main/idf_component.yml#L3
