### ISSUE TITLE
API for querying RMT TX FSM state (IDFGH-9298)

### ISSUE THREAD

**Issue by wuyuanyi135** [espressif/esp-idf#10679]
### Is your feature request related to a problem?

When sending infinite loop RMT sequences (loop_count=-1), we need to call rmt_disable and rmt_enable to reset the channel. However, if the channel is not enabled yet, rmt_disable will print an error log to the console. 

### Describe the solution you'd like.

Either 
1) making rmt_disable silently ignore the error when the channel was not enabled before

Or
2) provide an API to query the RMT channel state, so we can invoke the disable API on demand.

**Comment by suda-morris** [comment]
Even if the driver doesn't expose the FSM state, the caller should also know whether it's enabled or disabled, because the FSM state change is controlled by the caller instead of by hardware. I would suggest the caller to use enable/disable in a pair.
