### ISSUE TITLE
lightsleep power consumption regression (IDFGH-9300)

### ISSUE THREAD

**Issue by AxelLin** [espressif/esp-idf#10681]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v5.1-dev-3153-g2707c95a5f

### Operating System used.

Linux

### How did you build your project?

Command line with idf.py

### If you are using Windows, please specify command line type.

None

### Development Kit.

esp32-c3 Custom Board

### Power Supply used.

USB

### What is the expected behavior?

The lightsleep takes too much power if build with current master tree.

### What is the actual behavior?

Test on esp32-c3  custom board.
Build my application with v5.1-dev-2938-g8bf18b76ac, measure the power consumption when lightsleep I got about 470 uA.
Build the same application with v5.1-dev-3153-g2707c95a5f, measure the power consumption when lightsleep I got about 1.98 mA.
I also verify with v5.0 branch (v5.0-494-g490216a2ac), I got 450 uA.

Obviously a regression in current master tree.

### Steps to reproduce.

I think you can verify the issue using light_sleep example code. (compare power consumption with v5.0 and master tree)

**Comment by esp-wzh** [comment]
@AxelLin Thanks for your report!
This bug was introduced in [commit](https://github.com/espressif/esp-idf/commit/33ae2e1073f468fc281b92c91afc7bf7a2fc3b06#diff-52f8aaebd93e20b2a9e774041fa9430e9f358f3380f08ec73297feeb19d77406), we have fixed it and will sync to github soon, if your development depends on some new features on master, you can revert this commit first
