### ISSUE TITLE
Making ESP32-S3 Pins HIGH During BootLooading? (IDFGH-9315)

### ISSUE THREAD

**Issue by SenelCanik** [espressif/esp-idf#10695]
We have to make HIGH the GPIO4 pin of ESP32-S3 during boot.

We use esptool.exe in Windows to lood "bootloader.bin" or similar. But we don't know how to edit/change "bootloader.bin" file. Also we don't have any experience to make HIGH or LOW a pin of ESP32-S3 during bootloading. 

Can someone help us? 

Thank you.

**Comment by igrr** [comment]
Hi @SenelCanik,
ESP-IDF provides an example project showing how to customize the bootloader: https://github.com/espressif/esp-idf/tree/master/examples/custom_bootloader/bootloader_hooks. In a custom bootloader hook, you can change the GPIO levels using `gpio_hal_set_level` function from `hal/gpio_hal.h`.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, feel free to reopen.
