### ISSUE TITLE
[TW#15754] Missing C++ guards in esp_vfs_dev.h

### ISSUE THREAD

**Issue by nkolban** [espressif/esp-idf#1069]
While attempting to use the esp_vfs_dev.h header file in a C++ class, it was found that this header doesn't have C++ guards ... i.e.

```
extern "C {
...
}
```

see ... 

https://github.com/espressif/esp-idf/blob/master/components/vfs/include/esp_vfs_dev.h

**Comment by projectgus** [comment]
Thanks @nkolban, will fix!
