### ISSUE TITLE
CONFIG_ESP32_WIFI_ENABLED=n for BLE only ?  (IDFGH-9323)

### ISSUE THREAD

**Issue by f-hoepfinger-hr-agrartechnik** [espressif/esp-idf#10703]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Hi, 

can we set CONFIG_ESP32_WIFI_ENABLED=n for a BLE only Application ? 

Thanks, 
Franz

**Comment by xiewenxiang** [comment]
@f-hoepfinger-hr-agrartechnik 
Yes, you can set the `CONFIG_ESP32_WIFI_ENABLED=n` for a BLE only Application.

**Comment by f-hoepfinger-hr-agrartechnik** [comment]
i was thinking so yes. 

but did not take it.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to short of feedback, feel free to reopen with more updates.
