### ISSUE TITLE
IDF v.5.0 - problem with ASYNCIO (IDFGH-9333)

### ISSUE THREAD

**Issue by jacek12345** [espressif/esp-idf#10712]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v5.0-541-g885e501d99

### Operating System used.

Windows

### How did you build your project?

Command line with idf.py

### If you are using Windows, please specify command line type.

CMD

### What is the expected behavior?

building

### What is the actual behavior?

F:\GitHub\esp-rainmaker\examples\fan>idf.py build
Executing action: all (aliases: build)
Running ninja in directory f:\github\esp-rainmaker\examples\fan\build
Executing "ninja all"...
ERROR: C:\Users\jacek\.espressif\python_env\idf5.0_py3.7_env\Scripts\python.exe doesn't support asyncio. The issue can be worked around by re-running idf.py with the "--no-hints" argument.

### Steps to reproduce.

standard compiling of Rainmaker example.

### More Information.

It works in v.4.4.3
I found that in v5. breaking changes:
`ASIO: Internal ASIO component and ASIO examples were migrated from IDF to https://github.com/espressif/esp-protocols/components/asio`
But still don't know what should do with it? (BTW: link is wrong)
Always have to type "--no-hints" ?

**Comment by elektronika-ba** [comment]
I am having the same problems. I had to re-install ESP-IDF 2 times now, this will be the third time.

This issue appears every time I use Espressif -> IDF Tools Manager -> Install Tools ... or do anything with the tools.

Don't know how to fix this so will re-install AGAIN.

**Comment by dobairoland** [comment]
This has nothing to do with the linked ASIO breaking change.

Please use the Windows tool installer in order to set up a working environment: https://dl.espressif.com/dl/esp-idf/. It will deploy among others a working Python 3.8 environment. Please don't select from the installer the Python 3.7 already available on your system. It is clearly broken because Python 3.7 should support asyncio (it was introduced in 3.4).

**Comment by jacek12345** [comment]
Thnak You, resolved by installing with online installer instead of cloning.
