### ISSUE TITLE
BLE GATT server heating up on esp32s3 (IDFGH-9348)

### ISSUE THREAD

**Issue by nikhil-robinson** [espressif/esp-idf#10725]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Description: The ESP32s3 is overheating when the BLE GATT server is enabled. The temperature rises to 56°C, which is higher than the normal operating temperature. The overheating issue is only observed when the GATT server example  is used and no other examples have reported the same issue.

Steps to Reproduce:

Enable the BLE GATT server on esp32s3 board.
Observe the temperature of the ESP32s3 and measure it using a thermometer or temperature sensor.

Expected Results: The ESP32s3 should not overheat when the BLE GATT server is enabled. The temperature should remain within the normal operating range.

Actual Results: The ESP32s3 overheats and the temperature rises to 56°C.

Environment: The issue was observed on a custom board with ESP32s3 WROOM 1, running the latest firmware. No other examples have reported the same issue.

Troubleshooting Steps:

We tried different frequency settings and enabled Modem Sleep, but the issue still persists.
We tried the code on an ESP32 Eye original development board, but the issue still persists.
Conclusion: The overheating issue of the ESP32s3 when the BLE GATT server is enabled remains unresolved despite our troubleshooting efforts.

SDK :
ESP-IDF v4.4.3-173-g1f63dc70b8-dirty

**Comment by xiewenxiang** [comment]
Because demo does not turn on sleep by default, so the temperature may be higher.
