### ISSUE TITLE
tusb_msc Sample running on one device and on another not (IDFGH-9349)

### ISSUE THREAD

**Issue by franz-ms-muc** [espressif/esp-idf#10727]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

ESP-IDF Release v5.0

### Operating System used.

Linux

### How did you build your project?

Eclipse IDE

### If you are using Windows, please specify command line type.

None

### Development Kit.

DevkitC

### Power Supply used.

USB

### What is the expected behavior?

https://github.com/espressif/esp-idf/tree/master/examples/peripherals/usb/device/tusb_msc

this Sample run fine on a Devkit C

### What is the actual behavior?

on a other ESP32S3 Board it fails. 
no mass Memory detected by Windows

### Steps to reproduce.

flash the Sample to 2 Boards, 
Test both. 

### Debug Logs.

```plain
i can provide a lot of logs.
[failing board device.usblog.txt](https://github.com/espressif/esp-idf/files/10686123/failing.board.device.usblog.txt)
[devkitdevice.usblog.txt](https://github.com/espressif/esp-idf/files/10686124/devkitdevice.usblog.txt)
[devkitdevice.zip](https://github.com/espressif/esp-idf/files/10686131/devkitdevice.zip)
[failing board device.zip](https://github.com/espressif/esp-idf/files/10686132/failing.board.device.zip)

```

**Comment by franz-ms-muc** [comment]
the main Information might be this: 

the FAILING Chip has this print on the Module. 

![](https://user-images.githubusercontent.com/69573151/217547557-6279498e-a93c-426a-98d7-9deedb5806ce.jpg)

**Comment by franz-ms-muc** [comment]
so, after getting a suitable Barcode Reader, i can read some codes: 

Working: 

Failing:

**Comment by franz-ms-muc** [comment]
#10837

**Comment by tore-espressif** [comment]
Hello @franz-ms-muc ,
I'm sorry we couldn't get to you sooner. Is the issue resolved? Does the example work on all modules now?

**Comment by franz-ms-muc** [comment]
we still make tests. Hold on.

**Comment by tore-espressif** [comment]
Ok, since you have already closed the issue, feel free to reopen

**Comment by esp-saurabhbansal** [comment]
Hello,

Just for your information, We have recently released USB Device MSC driver. Please check if it is useful to you. We highly appreciate the feedback.

The driver makes ESP based device recognizable by USB-hosts as a USB Mass Storage Device.
It either allows the embedded application to access the partition or Host PC accesses the partition over USB MSC. They can't be allowed to access the partition at the same time.

The driver supports storage media of two types:
1. SPI Flash
2. SD MMC Card

Driver can be found [here](https://github.com/espressif/idf-extra-components/blob/master/usb/esp_tinyusb/tusb_msc_storage.c).
Sample application can be found [here](https://github.com/espressif/esp-idf/tree/master/examples/peripherals/usb/device/tusb_msc).

Thanks.
