### ISSUE TITLE
Is there a way to quickly notify a Core 0 FreeRTOS task from ulp? (IDFGH-9362)

### ISSUE THREAD

**Issue by Rainbow-Cai** [espressif/esp-idf#10737]
### Is your feature request related to a problem?

Hi @ESP-Marius  Could you please gaveme some help？

Since release 5.0 of esp idf, driver/rtc_cntl.h has been moved to esp_private/rtc_cntl.h.
Does ESP IDF 5.0 offer an alternative (of rtc_isr_register()) in order to raise an ISR from ulp coprocessor and handle it in the main C program on CP0?

I tried ETS_RTC_CORE_INTR_SOURCE, but the esp_intr_alloc() call failed.
Is there a way to quickly notify a Core 0 FreeRTOS task from ulp?

I couldn’t find any definition of “RTC_CNTL_RTC_SW_CPU_INT” in the esp-idf-v5.0 folder.
Do you have an example of triggering this interrupt from ulp assembly code ?
Do you have an example of handling this interrupt in core 0 C code ?
For memory I use ESP IDF V5 framework, on a ESP32-U4WDH chip.

**Comment by ESP-Marius** [comment]
Hi,

On ESP32 it seems like `ULP_CP_INT` would be usable for this purpose. As of now there is no ULP API wrapper for this interrupt, so you still need to use `rtc_isr_register`.

But I agree that we should provide a wrapper for this, as ideally `#include "esp_private/rtc_ctrl.h"` shouldn't be used in user code.

How about changing this issue to be a generic feature request for this feature?
