### ISSUE TITLE
Guru Meditation Error: Core  0 panic'ed (Interrupt wdt timeout on CPU0). (IDFGH-9369)

### ISSUE THREAD

**Issue by HyoChangKim** [espressif/esp-idf#10743]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

1) CODE
    gpio_config_t io_conf;
    memset((void *)&io_conf, 0, sizeof(io_conf));
    io_conf.mode = GPIO_MODE_INPUT;
    io_conf.pin_bit_mask = (1ULL << c.pir_pin);
    io_conf.intr_type = GPIO_INTR_POSEDGE;
    io_conf.pull_up_en = GPIO_PULLUP_ENABLE;
    gpio_config(&io_conf);
    gpio_install_isr_service(0);
    gpio_isr_handler_add((gpio_num_t)c.pir_pin, pir_handler, NULL);
    **gpio_wakeup_enable((gpio_num_t)c.pir_pin, GPIO_INTR_HIGH_LEVEL); // error**
    esp_sleep_enable_gpio_wakeup();
    pmsub_update(false);

2) TERMINAL
␛[0;32mI (0) cpu_start: Starting scheduler on APP CPU.␛[0m
␛[0;32mI (322) gpio: GPIO[17]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 ␛[0m
␛[0;32mI (332) gpio: GPIO[18]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 0| Pulldown: 1| Intr:0 ␛[0m
␛[0;32mI (342) gpio: GPIO[19]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 0| Pulldown: 1| Intr:3 ␛[0m
**Guru Meditation Error: Core  0 panic'ed (Interrupt wdt timeout on CPU0).** 

Core  0 register dump:
PC      : 0x40081252  PS      : 0x00050034  A0      : 0x40083074  A1      : 0x3ffb0720
A2      : 0x3ffb0028  A3      : 0x3ffb0040  A4      : 0x3ffaffa4  A5      : 0x40086a60  
A6      : 0x00000000  A7      : 0x3ffaffc8  A8      : 0x3ffb70a8  A9      : 0x00000000  
A10     : 0x00000010  A11     : 0x00000013  A12     : 0x80083328  A13     : 0x3ffaf9e0  
A14     : 0x3ffb71dc  A15     : 0x3ffb71dc  SAR     : 0x0000001c  EXCCAUSE: 0x00000005  
EXCVADDR: 0x00000000  LBEG    : 0x00000000  LEND    : 0x00000000  LCOUNT  : 0x00000000  
Core  0 was running in ISR context:
EPC1    : 0x400d872f  EPC2    : 0x00000000  EPC3    : 0x00000000  EPC4    : 0x40081252

Backtrace: 0x4008124f:0x3ffb0720 0x40083071:0x3ffb0750 0x4000bfed:0x3ffafa30 0x40089c3a:0x3ffafa40 0x400d6abb:0x3ffafa60 0x400d6b19:0x3ffafaa0 0x400d349d:0x3ffafad0 0x40081eed:0x3ffafaf0 0x40089989:0x3ffafb10

Core  1 register dump:
PC      : 0x400e9992  PS      : 0x00060334  A0      : 0x800d7d92  A1      : 0x3ffb6de0  
A2      : 0x00000000  A3      : 0x00040008  A4      : 0x80089c3d  A5      : 0x3ffb3d50  
A6      : 0x00000003  A7      : 0x00060423  A8      : 0x800dc1c2  A9      : 0x3ffb6db0  
A10     : 0x00000000  A11     : 0x01ce843f  A12     : 0x00000019  A13     : 0x00000034  
A14     : 0x00000000  A15     : 0x3ffe7cc4  SAR     : 0x00000000  EXCCAUSE: 0x00000005
EXCVADDR: 0x00000000  LBEG    : 0x00000000  LEND    : 0x00000000  LCOUNT  : 0x00000000  

Backtrace: 0x400e998f:0x3ffb6de0 0x400d7d8f:0x3ffb6e00 0x400880d6:0x3ffb6e20 0x40089989:0x3ffb6e40

ELF file SHA256: 7677d43b1f82c29f

Rebooting...
ets Jun  8 2016 00:22:57

**Comment by HyoChangKim** [comment]
sorry.
my hardware error.

**Comment by JayS0223** [comment]
Hey, @HyoChangKim can you tell me how did you overcome this error??
As I am getting the same error, when tried running the audio and video task together.
