### ISSUE TITLE
使用rmt通道和电机驱动时，rmt的2812灯闪烁 (IDFGH-9367)

### ISSUE THREAD

**Issue by Zhengqinze05** [espressif/esp-idf#10741]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

![image](https://user-images.githubusercontent.com/92145359/218020646-7532ea3f-c366-425f-b929-6f8c1f2efefb.png)
![image](https://user-images.githubusercontent.com/92145359/218021042-a8d75457-e933-4d54-961d-5edd880392cc.png)
![image](https://user-images.githubusercontent.com/92145359/218021054-388d84e3-80c4-4706-bec0-7f015093ee7a.png)
当我使用rmt控制2812的灯的同时，步进电机也在运动切换速度，没有点亮的2812的灯会时不时闪烁一下，特别是它隔着一个灯闪烁，我点亮1号灯，1号灯亮是对的，但是3号灯会乱闪。
并且当我的程序中有其他的驱动，像I2S和WiFi以及usb驱动时，他的出错闪烁频率更高

**Comment by suda-morris** [comment]
@Zhengqinze05 
You may want to increase the [mem_block_num](https://docs.espressif.com/projects/esp-idf/en/v4.4.4/esp32/api-reference/peripherals/rmt.html#_CPPv4N12rmt_config_t13mem_block_numE) to e.g. `4`.
