### ISSUE TITLE
Check if factory reset occurs in app? (IDFGH-9379)

### ISSUE THREAD

**Issue by wuyuanyi135** [espressif/esp-idf#10753]
### Is your feature request related to a problem?

I need to perform some extra initialization after factory reset. I want to check if factory reset occurs in the app. 

### Describe the solution you'd like.

Provide an API to tell if this is the first boot-up after factory reset.

### Describe alternatives you've considered.

I have considered using a dummy nvs partition that will be set after boot. On factory reset this partition will be erased, so that the app will know this is the first boot after factory reset. However, this solution seems a bit tedious.

**Comment by igrr** [comment]
> I have considered using a dummy nvs partition that will be set after boot. On factory reset this partition will be erased, so that the app will know this is the first boot after factory reset. However, this solution seems a bit tedious.

Unfortunately I don't think there's anything significantly simpler in terms of the underlying implementation. You could replace an NVS partition with a single-sector data partition, and write data into it as a token of the "first boot". But if you are using NVS for any other purpose, it's probably easier to reuse that partition and store the "first boot" token there.

**Comment by wuyuanyi135** [comment]
@igrr Thanks for confirming!

**Comment by chipweinberger** [comment]
I personally use a boot count.

I increment the nvs boot count setting on each boot.

If zero, i know it's the first boot after reset.

**Comment by wuyuanyi135** [comment]
> nt.
> 
> I increment the nvs boot count setting on each boot.
> 
> If zero, i know it's the first boo

Thanks for your suggestion!
