### ISSUE TITLE
components/esp-tls/esp_tls.h is missing includes (IDFGH-9392)

### ISSUE THREAD

**Issue by rkit1** [espressif/esp-idf#10765]
When CONFIG_ESP_TLS_SERVER_SESSION_TICKETS is enabled

```
C:/.espressif/frameworks/esp-idf-v5.0/components/esp-tls/esp_tls.h:191:5: error: unknown type name 'mbedtls_entropy_context'
  191 |     mbedtls_entropy_context entropy;                                            /*!< mbedTLS entropy context structure */
      |     ^~~~~~~~~~~~~~~~~~~~~~~
C:/.espressif/frameworks/esp-idf-v5.0/components/esp-tls/esp_tls.h:193:5: error: unknown type name 'mbedtls_ctr_drbg_context'
  193 |     mbedtls_ctr_drbg_context ctr_drbg;                                          /*!< mbedTLS ctr drbg context structure.
      |     ^~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by AdityaHPatwardhan** [comment]
Hi @rkit1,
Thanks for the issue.
I agree that it is a bug.
I think it was introduced when we restructured the esp_tls.h file some
time back.
Can you please check if the patch that I have attached fixes your issue?
Thanks,
Aditya

[server_session_ticket_build_issue.patch.zip](https://github.com/espressif/esp-idf/files/10739454/server_session_ticket_build_issue.patch.zip)

**Comment by rkit1** [comment]
Yes it fixed the issue.
