### ISSUE TITLE
add support for single pair Ethernet PHY (IDFGH-9431)

### ISSUE THREAD

**Issue by gkasprow** [espressif/esp-idf#10799]
### Is your feature request related to a problem?

10Base-T1S becomes more and more popular as a CAN replacement in industry and automotive.
It's an ideal solution for short-range IoT networks, epecially where 2.4GHz band is overcorowded

### Describe the solution you'd like.

Support for either LAN8670 PHY or NCN26010 MAC+PHY

### Describe alternatives you've considered.

Of course standard Ethernet works fine but it requires switch and a lot of cabling if one needs to build a sensor network with let's say 16 devices.

### Additional context.

Here is the use case - a photonic sensor where SPE is used for both data transfer and power
https://github.com/sinara-hw/DiPho/issues/18

**Comment by kostaond** [comment]
Hi @gkasprow, thanks for submitting the feature request. It really could be interesting to support 10Base-T1S. Could you please check this [article](https://blog.espressif.com/esp-idf-custom-ethernet-phy-driver-quick-guide-45f9d23de0ad) first?  Would it be applicable to 10Base-T1S PHY chips?

**Comment by gkasprow** [comment]
It looks so. These chips have a standard RMII interface. Only registers differ.

**Comment by gkasprow** [comment]
I have [LAN8670 eval](https://eu.mouser.com/ProductDetail/Microchip-Technology/EV06P90A?qs=tlsG%2FOw5FFhZQakMhwEgnQ%3D%3D) in my lab as well as [USB dongle](https://eu.mouser.com/new/microchip/microchip-evb-lan8670-usb-board/)
we are curently developing open source PoE router based on RPI 0.

**Comment by morgana2313** [comment]
@gkasprow: we also want to use the LAN8670 with esp-idf. Is there any code available from https://github.com/sinara-hw/DiPho/issues/18 available, from which we can learn how to setup the proper LAN8670 chip registers ?

We have the EVB-LAN8670-USB working with Linux raspberry pi.

**Comment by gkasprow** [comment]
We were using NCN26010 with STM32 eval board.
There is example code for STM32 and other platforms provided by Onsemi
https://www.onsemi.com/pub/Collateral/EXAMPLE%20SOFTWARE:%20STM32%20IMPLEMENTATION%20.ZIP

**Comment by morgana2313** [comment]
We got an ESP32 + LAN8551 replying to ping packets send by the RPi with the *LAN8650/1 OPEN Alliance TC6 Driver*. It gives ping times of ±50ms. Between two RPi's the SPE ping times are ±1ms.

What would be normal ping times for a 10Base-T1S network?

**Comment by gkasprow** [comment]
It depends on how the ICMP stack is implemented. Did you use polling or interrupts?
With interrupts, it should be a much lower value. If you use polling, 50ms could be possible.

**Comment by morgana2313** [comment]
Dank voor uw bericht.

Ik ben afwezig tot 7 augustus 2023 en lees sporadisch mijn mail.

Voor dringende zaken kunt u contact opnemen met mijn collega's via 070 891 9 891 of via ***@***.***

**Comment by baybal** [comment]
> Hi @gkasprow, thanks for submitting the feature request. It really could be interesting to support 10Base-T1S. Could you please check this [article](https://blog.espressif.com/esp-idf-custom-ethernet-phy-driver-quick-guide-45f9d23de0ad) first? Would it be applicable to 10Base-T1S PHY chips?

Current chip revisions of LAN867* have buggy PLCA. I was recommended NCN26000, but it's nowhere to be found.

**Comment by gkasprow** [comment]
NCN26010 chips are easily available [now](https://www.digikey.com/en/products/detail/NCN26010XMNTXG/488-NCN26010XMNTXGCT-ND/17038954?curr=usd&utm_campaign=buynow&utm_medium=aggregator&utm_source=octopart). Availability issue was a few months ago.
Devkits are also [available ](https://octopart.com/ncn26010xmnevb-onsemi-129969137?r=sp).

**Comment by baybal** [comment]
> NCN26010 chips are easily available [now](https://www.digikey.com/en/products/detail/NCN26010XMNTXG/488-NCN26010XMNTXGCT-ND/17038954?curr=usd&utm_campaign=buynow&utm_medium=aggregator&utm_source=octopart). Availability issue was a few months ago. Devkits are also [available ](https://octopart.com/ncn26010xmnevb-onsemi-129969137?r=sp).

NCN26010 is SPI and NCN26000 is MII. You can only realistically use it with a much higher end MCU, while RMII is a lingua franca for ethernet in microcontrollers, including sub $1 ones.

**Comment by gkasprow** [comment]
Oh,I didn't know Onsemi has RMII version. I thought you made a typoo. Anyway, SPI is better because RMII consumes most of ESP32 IOs.

**Comment by baybal** [comment]
> Oh,I didn't know Onsemi has RMII version. I thought you made a typoo. Anyway, SPI is better because RMII consumes most of ESP32 IOs.

But then you lose all the power & performance benefit of the onboard MAC

**Comment by gkasprow** [comment]
We arr limited to 10Mbit anyway so that is not critical.

**Comment by kostaond** [comment]
https://github.com/espressif/esp-eth-drivers/pull/19

**Comment by Indastri** [comment]
The fix was merged. Closing the issue. If there will be any more problems do not hesiate to reopen this or create a new issue.
Cheers!
