### ISSUE TITLE
how to minimize bin size? (IDFGH-9471)

### ISSUE THREAD

**Issue by casitelwithdean** [espressif/esp-idf#10836]
### Is your feature request related to a problem?

NO

### Describe the solution you'd like.

In my project(esp32s3-wroom1),I used blufi,esp-dsp and so on .Its bin size exceeds my need，so is there any way to minimize bin size?Thanks a lot!

**Comment by dobairoland** [comment]
Have you seen https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/performance/size.html?

**Comment by casitelwithdean** [comment]
> Have you seen https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/performance/size.html?

thank  you very much!
