### ISSUE TITLE
[TW#15767] BLE Connection error 133 (Command disallowed)

### ISSUE THREAD

**Issue by imotion-software** [espressif/esp-idf#1083]
Hi!

we're trying to connect ESP32 via BLE to a board with a Nordic NRF52 on board.
We can successfully connect to Nordic module from any kind of device (such as iOS App, Android and more), but ESP32 seems to fail connect half the time.

The Bluetooth connect fails with error 133, which is something of quite common and generic, but going deeper on the connection flow, we found that ESP32 gets from Nordic device a status 12 (command disallowed) after sending HCI_BLE_READ_REMOTE_FEAT command.

This is something that happens half the time, sometimes connect (and communication) works, sometimes it doesn't. Below some ESP32 log of a failure:

```
E (19453) BT: btc_transfer_context msg 0 3 2 0x3ffeda78
E (19457) BT: btc_task msg 0 3 2 0x3ffd9af0
E (19467) BT: BTA got event 0x1f00
E (19473) BT: HCI Enqueue Comamnd opcode=0x200d
E (19477) BT: Receive packet event_code=0xf
E (19481) BT: Received status code: 0
E (19467) BT: btc_gattc_arg_deep_free Unhandled deep free 2
E (19485) BT: alarm_cbs_lookfor_available 3 0x3ffc9dc4
E (20086) BT: Receive packet event_code=0x3e
E (20092) BT: HCI Enqueue Comamnd opcode=0x2016
E (20170) BT: Receive packet event_code=0xf
E (20173) BT: Received status code: 12
E (20176) BT: Receive packet event_code=0x5
E (20180) BT: bta_gatts_conn_cback gatt_if=3 conn_id=3 connected=0 reason = 0x0062
E (20184) BT: bta_gatts_conn_cback  bda :ef-10-50-df-d1-a3 
E (20190) BT: btc_transfer_context msg 1 2 15 0x3ffe2210
E (20197) BT: bta_gattc_conn_cback() - cif=4 connected=0 conn_id=4 reason=0x003e
E (20205) BT: p_conn is NULL in bta_gattc_conn_cback
E (20211) BT: BTA got event 0x1f11
E (20215) BT: btc_transfer_context msg 1 3 36 0x3ffe20d0
E (20197) BT: btc_task msg 1 2 15 0x3ffd9af0
E (20221) BT: btc_transfer_context msg 1 3 2 0x3ffe20b0
E (20232) BT: btc_task msg 1 3 36 0x3ffd958c
E (20237) BT: btc_task msg 1 3 2 0x3ffedd24
```

Is there any possibile reason for this unpredictable error?

**Comment by Yulong-espressif** [comment]
@imotion-software Do you mean the ESP32 cannot connect to the NRF52 always or just sometimes?
