### ISSUE TITLE
blecent crash after fail to allocate ACL buffers (IDFGH-9487)

### ISSUE THREAD

**Issue by embedded-sm** [espressif/esp-idf#10849]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

IDF version: v5.0.1
DevKit: ESP32-C3-DevKit

if bleprph send multiple notify to blecent, the blecent crash with error loop:
`NimBLE: ble_hci_rx_acl failed to allocate ACL buffers; increase ACL_BUF_COUNT`

is possible to reproduce with the example:
https://github.com/espressif/esp-idf/tree/master/examples/bluetooth/nimble/throughput_app

need to setup the example to use NOTIFY instead the READ

**Comment by zztiger123** [comment]
Hi @embedded-sm 

Actually this is happening because 
Our sample applications are based on what upstream nimble applications provide and they are more of a demo purpose to show usage of APIs . Since we target embedded device , as a generic solution , we provide a memory configuration that should suffice majority of the use case .it looks like your case needs pushing packets at a rate faster than the speed at which packets are getting freed up . So, to suit your case, you can increase the buffer count such that they are sufficient enough to handle the scenario. 

However, plz note that increasing buffer counts will increase the memory footprint

**Comment by embedded-sm** [comment]
unfortunately increasing the buffer count not solve the issue (only postpone a bit).
adding a delay between send on the peripheral can partially solve the problem, but is required big delay, that ruin the performance.
furthermore if the peripheral "flood" the ble central, the message should drop and is not acceptable that it can not recover from that status.
with the example is not easy to reproduce, but in our project when this issue happen it create guru meditation or watchdog trigger.
did you have opportunity to test it?

**Comment by rahult-github** [comment]
Hi @embedded-sm  ,
 
  If putting delay also is not helping in your case, then another suggestion i have is that in case buffer is not allocated, instead of processing and going ahead, attempt to re-allocate packet. At some point of time, there will definitely be a freed packet, and hence allocation will happen. This is similar to introducing delay, as it is just trying to find memory , whenever applicable. 
  
In the throughput app, with default memory setting, "NimBLE: ble_hci_rx_acl failed to allocate ACL buffers; increase ACL_BUF_COUNT" print is  visible. But there is no crash, since in sometime buffer are available and the test case goes ahead. 

In your setup, when above scenario is hit, what is the next processing step being done, that is leading to crash ?

**Comment by embedded-sm** [comment]
> If putting delay also is not helping in your case, then another suggestion i have is that in case buffer is not allocated, instead of processing and going ahead, attempt to re-allocate packet. At some point of time, there will definitely be a freed packet, and hence allocation will happen. This is similar to introducing delay, as it is just trying to find memory , whenever applicable.

your theory is right, but if you try the example you will notice that the behaviors is different
after the first "failed to allocate ACL buffers" if bleprph regular send message, the blecent not receive anymore messages and it never stop the error loop until bleprph stop for long time (>500ms)

**Comment by rahult-github** [comment]
Hi @embedded-sm  ,

I tried the throughput_app example for notify.  I see below behaviour:

on blecent side:

> I (88280) blecent_throughput: received notification; conn_handle = 1 attr_handle = 14 attr_len = 500 ; Total length = 1345000
E (88290) NimBLE: ble_hci_rx_acl failed to allocate ACL buffers; increase ACL_BUF_COUNT
I (88290) blecent_throughput: received notification; conn_handle = 1 attr_handle = 14 attr_len = 500 ; Total length = 1345500
E (88310) NimBLE: ble_hci_rx_acl failed to allocate ACL buffers; increase ACL_BUF_COUNT

and then, once buffers start to deplete, more such prints:

> E (88330) NimBLE: ble_hci_rx_acl failed to allocate ACL buffers; increase ACL_BUF_COUNT
E (88340) NimBLE: ble_hci_rx_acl failed to allocate ACL buffers; increase ACL_BUF_COUNT
E (88350) NimBLE: ble_hci_rx_acl failed to allocate ACL buffers; increase ACL_BUF_COUNT
E (88350) NimBLE: ble_hci_rx_acl failed to allocate ACL buffers; increase ACL_BUF_COUNT
E (88360) NimBLE: ble_hci_rx_acl failed to allocate ACL buffers; increase ACL_BUF_COUNT
E (88380) NimBLE: ble_hci_rx_acl failed to allocate ACL buffers; increase ACL_BUF_COUNT
E (88390) NimBLE: ble_hci_rx_acl failed to allocate ACL buffers; increase ACL_BUF_COUNT



However, on bleprph side:

Initially logs show 

> I (88865) NimBLE: GATT procedure initiated: notify; 
I (88865) NimBLE: att_handle=14
I (88865) NimBLE: GATT procedure initiated: notify; 
I (88875) NimBLE: att_handle=14
I (88875) NimBLE: GATT procedure initiated: notify; 
I (88885) NimBLE: att_handle=14
I (88885) NimBLE: GATT procedure initiated: notify; 
I (88895) NimBLE: att_handle=14
I (88895) NimBLE: GATT procedure initiated: notify; 
I (88905) NimBLE: att_handle=14
 

But then, buffers start to deplete. So, prints shown are:

> E (89215) bleprph_throughput: No MBUFs available from pool, retry..
I (89325) NimBLE: GATT procedure initiated: notify; 
I (89325) NimBLE: att_handle=14
I (89325) NimBLE: GATT procedure initiated: notify; 
I (89325) NimBLE: att_handle=14
I (89325) NimBLE: GATT procedure initiated: notify; 
I (89335) NimBLE: att_handle=14


But , the test keeps running and such prints occur on both central and peripheral side. 

Eventually the test finishes and we see :

On bleprph: 

> I (148365) NimBLE: GATT procedure initiated: notify; 
I (148375) NimBLE: att_handle=14
*********************************
I (148385) bleprph_throughput: Notify throughput = 154866 bps, count = 2323
*********************************

And on blecent side:

> E (148480) NimBLE: ble_hci_rx_acl failed to allocate ACL buffers; increase ACL_BUF_COUNT
E (148490) NimBLE: ble_hci_rx_acl failed to allocate ACL buffers; increase ACL_BUF_COUNT
I (88320) blecent_throughput: received notification; conn_handle = 1 attr_handle = 14 attr_len = 500 ; Total length = 1346000
I (148510) blecent_throughput: received notification; conn_handle = 1 attr_handle = 14 attr_len = 500 ; Total length = 1346500
I (148520) blecent_throughput: received notification; conn_handle = 1 attr_handle = 14 attr_len = 500 ; Total length = 1347000
I (148530) blecent_throughput: received notification; conn_handle = 1 attr_handle = 14 attr_len = 500 ; Total length = 1347500
I (148540) blecent_throughput: received notification; conn_handle = 1 attr_handle = 14 attr_len = 500 ; Total length = 1348000


The above behaviour doesn't match to the observation you have mentioned : 

> if you try the example you will notice that the behaviors is different
after the first "failed to allocate ACL buffers" if bleprph regular send message, the blecent not receive anymore messages and it never stop the error loop until bleprph stop for long time (>500ms)


If the application behaviour at your end needs to be debugged, can you please let me know:

1. The steps you are using while running the application where above behaviour is seen 
2. The commit id you are currently on ?   " Please share the output of  ` git describe --tags ` "
3. The sdkconfig being used at your end ( for both the blecent / bleprph )

**Comment by embedded-sm** [comment]
> The above behaviour doesn't match to the observation you have mentioned :

why you say that not match the my description?
look that at your side the ACL_BUF_COUNT error is repeated for the full duration of 60s of test (except for the first messages )
and blecent recover from that state only when bleprph stop, as here

> 1. The steps you are using while running the application where above behaviour is seen

on blecent i only change:

```
if (!cli_receive_key(test_data)) {
    /* No command supplied, start with reading */
    test_data[0] = NOTIFY_THROUGHPUT;
    test_data[1] = 60;
    ESP_LOGI(tag, "No command received from user, start with READ op"
             " with 60 seconds test time");
}
```

on bleprph i change different delay here:

```
/* Memory not available for mbuf */
ESP_LOGE(tag, "No MBUFs available from pool, retry..");
vTaskDelay(100 / portTICK_PERIOD_MS); //over 500ms, blecent recover from error loop
om = ble_hs_mbuf_from_flat(payload, sizeof(payload));
assert(om != NULL);
```

> 2. The commit id you are currently on ? " Please share the output of git describe --tags "

v5.0.1-3-g886e98a2c1
if need i can back to that V5.0.1 tag

> 3. The sdkconfig being used at your end ( for both the blecent / bleprph )

[sdkconfig_both.zip](https://github.com/espressif/esp-idf/files/10861789/sdkconfig_both.zip)


i notice a details, from your log (i verify it the same here) the timestamp of the log is wrong, when it recovers it has the same timestamp present at the begin of loop error (as some ble thread, take extra resource):
<img width="667" alt="image" src="https://user-images.githubusercontent.com/68000309/222163046-91416e7d-a1ea-4e66-972c-1445c001c664.png">
<img width="579" alt="image" src="https://user-images.githubusercontent.com/68000309/222163444-76306287-5b22-4925-bd0e-8063eea878a5.png">

**Comment by embedded-sm** [comment]
sorry i forgot to remove a extra log (incremental number) exchanged between blecent and bleprph, (without there are the same behaviors)

**Comment by rahult-github** [comment]
Hi @embedded-sm ,  can you please check if attached patch helps ? 
[fast_notify.txt](https://github.com/espressif/esp-idf/files/10878982/fast_notify.txt)

The patch needs to be applied at $IDF_PATH.

**Comment by embedded-sm** [comment]
thanks, this patch prevent the example to stuck as before.
this is a clue that the issue loop take resource and due to the high priority of the task all the rest of the code have problem, correct or if im wrong?

this delay is it only a test to understand the direction for a final fix, right? did you plan to keep improving this fix properly?

**Comment by rahult-github** [comment]
Hi @embedded-sm ,

Thanks for confirming. So, the controller task priority is higher compared to stack and in this use case, the Rx packets are coming at a very fast rate. This is causing no chance to host stack to process and hence free up packets. Will review this change internally and fix this.

**Comment by mikebwilliams** [comment]
I had a similar issue with large data transfers coming from Android, and ultimately needed to enable flow control for NimBLE. Bluedroid already supports flow control in ESP-IDF as far as I can tell, so the patch is basically just enable it between NimBLE and the VHCI.

NimBLE patch:
```
diff --git i/nimble/host/src/ble_att_cmd.c w/nimble/host/src/ble_att_cmd.c
index a5617da66..0a6cfc8ca 100644
--- i/nimble/host/src/ble_att_cmd.c
+++ w/nimble/host/src/ble_att_cmd.c
@@ -21,6 +21,7 @@
 #include <string.h>
 #include "os/os.h"
 #include "nimble/ble.h"
+#include "esp_rom_sys.h"
 #include "ble_hs_priv.h"
 #include "host/ble_att.h"
 #include "host/ble_uuid.h"
@@ -60,6 +61,9 @@ ble_att_tx_with_conn(struct ble_hs_conn *conn, struct ble_l2cap_chan *chan, stru
     int rc;
     bool is_request;
     struct os_mbuf_pkthdr *omp;
+    uint8_t opcode;
+    uint8_t handle_bytes[2];
+    uint16_t attr_handle = 0;
 
     if (!txom) {
         if (conn->client_att_busy) {
@@ -76,7 +80,14 @@ ble_att_tx_with_conn(struct ble_hs_conn *conn, struct ble_l2cap_chan *chan, stru
 
     BLE_HS_DBG_ASSERT_EVAL(txom->om_len >= 1);
 
-    is_request = ble_att_is_request_op(txom->om_data[0]);
+    opcode = txom->om_data[0];
+    if (OS_MBUF_PKTLEN(txom) >= 3 &&
+        os_mbuf_copydata(txom, 1, sizeof(handle_bytes), handle_bytes) == 0) {
+        attr_handle = (uint16_t)handle_bytes[0] |
+                      ((uint16_t)handle_bytes[1] << 8);
+    }
+
+    is_request = ble_att_is_request_op(opcode);
 
     if (is_request) {
         if (conn->client_att_busy) {
@@ -90,9 +101,15 @@ ble_att_tx_with_conn(struct ble_hs_conn *conn, struct ble_l2cap_chan *chan, stru
     ble_att_inc_tx_stat(txom->om_data[0]);
 
     ble_att_truncate_to_mtu(chan, txom);
-    /* Save is_request before ble_l2cap_tx, which frees txom */
+    /* Save is_request before ble_l2cap_tx, which frees txom. */
     rc = ble_l2cap_tx(conn, chan, txom);
     if (rc != 0) {
+        esp_rom_printf("ble_att_tx_with_conn: fatal transmit result "
+                       "rc=%d opcode=0x%02x attr_handle=%u conn=%u cid=%u "
+                       "outstanding=%u hci_avail=%u msys_free=%d\n",
+                       rc, opcode, attr_handle, conn->bhc_handle, chan->dcid,
+                       conn->bhc_outstanding_pkts, ble_hs_hci_avail_pkts,
+                       os_msys_num_free());
         if (is_request) {
             conn->client_att_busy = false;
         }
diff --git i/nimble/host/src/ble_hs_flow.c w/nimble/host/src/ble_hs_flow.c
index 0d47b15a4..96f5096af 100644
--- i/nimble/host/src/ble_hs_flow.c
+++ w/nimble/host/src/ble_hs_flow.c
@@ -20,6 +20,11 @@
 #include "syscfg/syscfg.h"
 #include "ble_hs_priv.h"
 
+#if SOC_ESP_NIMBLE_CONTROLLER && CONFIG_BT_CONTROLLER_ENABLED && \
+    !CONFIG_BT_NIMBLE_LEGACY_VHCI_ENABLE
+#include "esp_hci_internal.h"
+#endif
+
 #if MYNEWT_VAL(BLE_HS_FLOW_CTRL)
 
 #define BLE_HS_FLOW_ITVL_TICKS  \
@@ -272,11 +277,24 @@ ble_hs_flow_startup(void)
 
     /* Flow control successfully enabled. */
     ble_hs_flow_num_completed_pkts = 0;
-#if SOC_ESP_NIMBLE_CONTROLLER && CONFIG_BT_CONTROLLER_ENABLED
-    ble_hci_trans_set_acl_free_cb(ble_hs_flow_acl_free, NULL);
+#if SOC_ESP_NIMBLE_CONTROLLER && CONFIG_BT_CONTROLLER_ENABLED && \
+    !CONFIG_BT_NIMBLE_LEGACY_VHCI_ENABLE
+    rc = r_ble_hci_trans_set_acl_free_cb(ble_hs_flow_acl_free, NULL);
 #else
-    ble_transport_register_put_acl_from_ll_cb(ble_hs_flow_acl_free);
+    rc = ble_transport_register_put_acl_from_ll_cb(ble_hs_flow_acl_free);
 #endif
+    if (rc != 0) {
+        enable_cmd.enable = BLE_HCI_CTLR_TO_HOST_FC_OFF;
+        ble_hs_hci_cmd_tx(BLE_HCI_OP(BLE_HCI_OGF_CTLR_BASEBAND,
+                                     BLE_HCI_OCF_CB_SET_CTLR_TO_HOST_FC),
+                          &enable_cmd, sizeof(enable_cmd), NULL, 0);
+        return rc;
+    }
+
+    BLE_HS_LOG(INFO, "Controller-to-host ACL flow control enabled: "
+                     "buffers=%u size=%u\n",
+               MYNEWT_VAL(BLE_TRANSPORT_ACL_FROM_LL_COUNT),
+               MYNEWT_VAL(BLE_TRANSPORT_ACL_SIZE));
     ble_npl_callout_init(&ble_hs_flow_timer, ble_hs_evq_get(),
                          ble_hs_flow_event_cb, NULL);
 #endif
diff --git i/nimble/host/src/ble_hs_startup.c w/nimble/host/src/ble_hs_startup.c
index 3c5badf23..8f1f0db39 100644
--- i/nimble/host/src/ble_hs_startup.c
+++ w/nimble/host/src/ble_hs_startup.c
@@ -582,7 +582,10 @@ ble_hs_startup_go(void)
     }
 
     /* If flow control is enabled, configure the controller to use it. */
-    ble_hs_flow_startup();
+    rc = ble_hs_flow_startup();
+    if (rc != 0) {
+        return rc;
+    }
 
     return 0;
 }
diff --git i/nimble/host/src/ble_l2cap.c w/nimble/host/src/ble_l2cap.c
index de3d674d3..918d6588b 100644
--- i/nimble/host/src/ble_l2cap.c
+++ w/nimble/host/src/ble_l2cap.c
@@ -24,6 +24,7 @@
 #include "host/ble_l2cap.h"
 #include "nimble/ble.h"
 #include "nimble/hci_common.h"
+#include "esp_rom_sys.h"
 #include "ble_hs_priv.h"
 #include "ble_l2cap_coc_priv.h"
 
@@ -483,6 +484,9 @@ ble_l2cap_tx(struct ble_hs_conn *conn, struct ble_l2cap_chan *chan,
 
     txom = ble_l2cap_prepend_hdr(txom, chan->dcid, OS_MBUF_PKTLEN(txom));
     if (txom == NULL) {
+        esp_rom_printf("ble_l2cap_tx: header allocation failed "
+                       "conn=%u cid=%u msys_free=%d\n",
+                       conn->bhc_handle, chan->dcid, os_msys_num_free());
         return BLE_HS_ENOMEM;
     }
 
@@ -499,6 +503,12 @@ ble_l2cap_tx(struct ble_hs_conn *conn, struct ble_l2cap_chan *chan,
 
     default:
         /* Error. */
+        esp_rom_printf("ble_l2cap_tx: HCI ACL transmit failed "
+                       "rc=%d conn=%u cid=%u outstanding=%u hci_avail=%u "
+                       "msys_free=%d\n",
+                       rc, conn->bhc_handle, chan->dcid,
+                       conn->bhc_outstanding_pkts, ble_hs_hci_avail_pkts,
+                       os_msys_num_free());
         return rc;
     }
 }
```

ESP-IDF patch:
```
diff --git i/components/bt/host/nimble/Kconfig.in w/components/bt/host/nimble/Kconfig.in
index d816de18408..7a1d7c49711 100644
--- i/components/bt/host/nimble/Kconfig.in
+++ w/components/bt/host/nimble/Kconfig.in
@@ -345,11 +345,13 @@ menu "GAP / GATT / Device Settings"
 
     config BT_NIMBLE_HS_FLOW_CTRL
         bool "Enable Host Flow control"
-        depends on BT_NIMBLE_ENABLED && !SOC_ESP_NIMBLE_CONTROLLER
+        depends on BT_NIMBLE_ENABLED
+        depends on !SOC_ESP_NIMBLE_CONTROLLER || BT_NIMBLE_LEGACY_VHCI_ENABLE
         default y if IDF_TARGET_ESP32
         default n
         help
-            Enable Host Flow control
+            Enable standard HCI controller-to-host ACL flow control. Legacy
+            VHCI targets use the host transport pool for receive credits.
 
     config BT_NIMBLE_HS_FLOW_CTRL_ITVL
         int "Host Flow control interval"
diff --git i/components/bt/host/nimble/esp-hci/src/esp_nimble_hci.c w/components/bt/host/nimble/esp-hci/src/esp_nimble_hci.c
index bffd7ee1403..ab3dec99e38 100644
--- i/components/bt/host/nimble/esp-hci/src/esp_nimble_hci.c
+++ w/components/bt/host/nimble/esp-hci/src/esp_nimble_hci.c
@@ -5,7 +5,9 @@
  */
 
 #include <assert.h>
+#include <string.h>
 #include "sysinit/sysinit.h"
+#include "os/os_mempool.h"
 #include "nimble/hci_common.h"
 #if CONFIG_BT_NIMBLE_ENABLED
 #include "host/ble_hs.h"
@@ -56,6 +58,28 @@ int os_msys_buf_alloc(void);
 void os_msys_buf_free(void);
 extern uint8_t ble_hs_enabled_state;
 
+static void ble_hci_log_acl_alloc_failure(void)
+{
+    struct os_mempool_info info;
+    struct os_mempool *pool = NULL;
+
+    while ((pool = os_mempool_info_get_next(pool, &info)) != NULL) {
+        if (strcmp(info.omi_name, "transport_pool_acl") == 0) {
+            esp_rom_printf("ACL rx alloc failed "
+                           "transport_pool_acl(free=%d min=%d blocks=%d size=%d) "
+                           "msys_free=%d\n",
+                           info.omi_num_free, info.omi_min_free,
+                           info.omi_num_blocks, info.omi_block_size,
+                           os_msys_num_free());
+            return;
+        }
+    }
+
+    esp_rom_printf("ACL rx alloc failed "
+                   "transport_pool_acl(not found) msys_free=%d\n",
+                   os_msys_num_free());
+}
+
 void ble_hci_trans_cfg_hs(ble_hci_trans_rx_cmd_fn *cmd_cb,
                           void *cmd_arg,
                           ble_hci_trans_rx_acl_fn *acl_cb,
@@ -167,32 +191,19 @@ static void ble_hci_rx_acl(uint8_t *data, uint16_t len)
     int rc;
     int sr;
 
-    int retry_count = 1;
-
     if (len < BLE_HCI_DATA_HDR_SZ || len > MYNEWT_VAL(BLE_TRANSPORT_ACL_SIZE)) {
         return;
     }
 
-
-   do {
-        m = ble_transport_alloc_acl_from_ll();
-
-        if (!m) {
-            if (retry_count % 5) {
-                esp_rom_printf("ACL buf alloc failed %d times\n", retry_count);
-                esp_rom_printf("Free ACL mbufs: %d\n", os_msys_num_free());
-            }
-
-            vTaskDelay(1);
-            retry_count++;
-
-            if (retry_count >= 30) {
-		esp_rom_printf("MBUF alloc stuck");
-                return;
-            }
-	}
-    } while (!m);
-
+    m = ble_transport_alloc_acl_from_ll();
+    if (!m) {
+        /* This runs in the controller's VHCI receive callback.  Waiting here
+         * prevents the host from freeing a buffer and returning its credit.
+         */
+        ble_hci_log_acl_alloc_failure();
+        ble_hs_sched_reset(BLE_HS_ECONTROLLER);
+        return;
+    }
 
     if ((rc = os_mbuf_append(m, data, len)) != 0) {
         esp_rom_printf("%s failed to os_mbuf_append; rc = %d", __func__, rc);
diff --git i/components/bt/host/nimble/nimble w/components/bt/host/nimble/nimble
--- i/components/bt/host/nimble/nimble
+++ w/components/bt/host/nimble/nimble
@@ -1 +1 @@
-Subproject commit 7cbddc218696c5accd1ef62943dd829d72600dd3
+Subproject commit 7cbddc218696c5accd1ef62943dd829d72600dd3-dirty
```
