### ISSUE TITLE
Unsubscribing and resubscribing to an event from running event handler causes crashes (IDFGH-9486)

### ISSUE THREAD

**Issue by rkit1** [espressif/esp-idf#10848]
```
#include <string.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "freertos/event_groups.h"
#include "esp_system.h"
#include "esp_wifi.h"
#include "esp_event.h"
#include "esp_log.h"
#include "nvs_flash.h"

#include "lwip/err.h"
#include "lwip/sys.h"

esp_event_handler_instance_t instance;

void event_handler(void* event_handler_arg, esp_event_base_t event_base, int32_t event_id, void* event_data) {
	ESP_ERROR_CHECK(esp_event_handler_instance_unregister(IP_EVENT, IP_EVENT_AP_STAIPASSIGNED, instance));
	ESP_ERROR_CHECK(esp_event_handler_instance_register(IP_EVENT, IP_EVENT_AP_STAIPASSIGNED, event_handler, NULL, instance));
}

void app_main(void) {
    ESP_ERROR_CHECK(esp_netif_init());
    ESP_ERROR_CHECK(esp_event_loop_create_default());
    ESP_ERROR_CHECK(esp_event_handler_instance_register(IP_EVENT, IP_EVENT_AP_STAIPASSIGNED, event_handler, NULL, instance));
    ESP_ERROR_CHECK(esp_event_post(IP_EVENT, IP_EVENT_AP_STAIPASSIGNED, 0, 0, portMAX_DELAY));
    ESP_ERROR_CHECK(esp_event_post(IP_EVENT, IP_EVENT_AP_STAIPASSIGNED, 0, 0, portMAX_DELAY));
}

```
esp32-s3
esp-idf 5.0.1

base_node seems to be corrupted around here in esp_event_loop_run in esp_event.c
```
            SLIST_FOREACH_SAFE(base_node, &(loop_node->base_nodes), next, temp_base) {
                if (base_node->base == post.base) {
```

**Comment by 0xjakob** [comment]
@rkit1 Thanks, we'll take a look into this. 

Meanwhile, have you tried using the "non-instance" API, i.e., `esp_event_handler_register()` and `esp_event_handler_unregister()`? The "instance" API (`esp_event_handler_instance_register()`, `esp_event_handler_instance_unregister()`) is mostly for third-party libraries where it's not clear if registration functions will be called twice or from a different component or user.

**Comment by 0xjakob** [comment]
@rkit1 Have you tried using the pointer of `instance` in the registration functions? The function signature is `esp_event_handler_instance_register(..., esp_event_handler_instance_t *instance)`, so a pointer to the instance must be used.

If I change your code accordingly, it works.

**Comment by rkit1** [comment]
Sorry, my bad with the example. My main code is correct and I still get crashes. Will try to pin it down later.

While messing with the example I found this weird interaction. Event handler gets called one extra time at the start of the program. 

```
#include <string.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "freertos/event_groups.h"
#include "esp_system.h"
#include "esp_wifi.h"
#include "esp_event.h"
#include "esp_log.h"
#include "nvs_flash.h"

#include "lwip/err.h"
#include "lwip/sys.h"

esp_event_handler_instance_t instance1;
esp_event_handler_instance_t instance2;
void event_handler(void* event_handler_arg, esp_event_base_t event_base, int32_t event_id, void* event_data) {
	int arg = (int)event_handler_arg;
	printf("base=%s event_id=%lu arg=%d\n", event_base, event_id, arg);
	if (arg == 500) {
		return;
	}
	ESP_ERROR_CHECK(esp_event_handler_instance_unregister(IP_EVENT, IP_EVENT_AP_STAIPASSIGNED, instance1));
	ESP_ERROR_CHECK(esp_event_handler_instance_register(IP_EVENT, IP_EVENT_AP_STAIPASSIGNED, event_handler, (void*)++arg, &instance1));
}

void app_main(void) {
    ESP_ERROR_CHECK(esp_event_loop_create_default());
    ESP_ERROR_CHECK(esp_event_handler_instance_register(IP_EVENT, IP_EVENT_AP_STAIPASSIGNED, event_handler, (void*)0, &instance1));
    ESP_ERROR_CHECK(esp_event_handler_instance_register(WIFI_EVENT, WIFI_EVENT_AP_PROBEREQRECVED, event_handler, (void*)500, &instance2));
    while(true) {
		ESP_ERROR_CHECK(esp_event_post(IP_EVENT, IP_EVENT_AP_STAIPASSIGNED, 0, 0, portMAX_DELAY));
		ESP_ERROR_CHECK(esp_event_post(WIFI_EVENT, WIFI_EVENT_AP_PROBEREQRECVED, 0, 0, portMAX_DELAY));
		ESP_ERROR_CHECK(esp_event_post(IP_EVENT, IP_EVENT_AP_STAIPASSIGNED, 0, 0, portMAX_DELAY));
		printf("\n");
		vTaskDelay(1000);
    }
}
```

```
I (0) cpu_start: Starting scheduler on APP CPU.
base=IP_EVENT event_id=2 arg=0
base=IP_EVENT event_id=2 arg=1
base=WIFI_EVENT event_id=16 arg=500
base=IP_EVENT event_id=2 arg=2

base=IP_EVENT event_id=2 arg=3
base=WIFI_EVENT event_id=16 arg=500
base=IP_EVENT event_id=2 arg=4

base=IP_EVENT event_id=2 arg=5
base=WIFI_EVENT event_id=16 arg=500
base=IP_EVENT event_id=2 arg=6

base=IP_EVENT event_id=2 arg=7
base=WIFI_EVENT event_id=16 arg=500
base=IP_EVENT event_id=2 arg=8
```

**Comment by 0xjakob** [comment]
@rkit1 I could also see that on my side. We will take a look.

**Comment by 0xjakob** [comment]
@rkit1 In general, the `esp_event` system was not designed to register new event callbacks from an event handler of the same loop. Unfortunately, the documentation does not really reflect this. At the moment, it is unspecified, which we will change in the future. We do have tests for unregistering event handlers from handlers of the same loop and this usually works, but it can create non-deterministic behavior depending on when the handlers have been registered and what other handlers have been registered.

The non-determinism is also the reason why you see one more event handler invocation in your example. Depending on how the handlers are stored, unregistering and registering them again can let them re-appear while `esp_event_loop_run()` is going over all the handlers.

Maybe you can tell us more about your use case so we can find a different solution rather than registering event handlers from a handler of the same loop.

Furthermore, is there any update regarding the crashes?

**Comment by rkit1** [comment]
I will have to use static handlers and route events to handlers myself then. 
No update yet. You can close the issue.

**Comment by 0xjakob** [comment]
@rkit1 Thanks for the information. If you notice any crash in the future, please let us know by re-opening this issue if it is related or by opening a new issue.
