### ISSUE TITLE
ESP32 Wrover B Board is nonresponsive . Lily Go T Relay (IDFGH-9483)

### ISSUE THREAD

**Issue by Bigdave318** [espressif/esp-idf#10845]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Please understand that I am very new to this. I don't even code.  I am learning. However, I bought a Lilygo T Relay board (1board-4relays)

I loaded a Basic.ino and now my board wont even light up under power. Pressing the boot button does nothing. My serial Monitor will only display this now,.
"06:56:29.133 -> rst:0x10 (RTCWDT_RTC_RESET),boot:0x12 (SPI_FAST_FLASH_BOOT)
06:56:29.180 -> flash read err, 1000
06:56:29.180 -> ets_main.c 371 
06:56:29.494 -> ets Jun  8 2016 00:22:57
06:56:29.494 -> 
06:56:29.494 -> rst:0x10 (RTCWDT_RTC_RESET),boot:0x12 (SPI_FAST_FLASH_BOOT)
06:56:29.494 -> flash read err, 1000
06:56:29.494 -> ets_main.c 371 
06:56:29.870 -> ets Jun  8 2016 00:22:57
06:56:29.870 -> 
06:56:29.870 -> rst:0x10 (RTCWDT_RTC_RESET),boot:0x12 (SPI_FAST_FLASH_BOOT)
06:56:29.870 -> flash read err, 1000
06:56:29.870 -> ets_main.c 371 
06:56:30.200 -> ets Jun  8 2016 00:22:57"

The  .ino gave from the relay boards git. and i only changed the SSID and Password info.
[ESP-DASH-master.zip](https://github.com/espressif/esp-idf/files/10831625/ESP-DASH-master.zip)

**Comment by igrr** [comment]
```
06:56:29.870 -> flash read err, 1000
06:56:29.870 -> ets_main.c 371
```
This message usually indicates that no valid binary was found at flash address 0x1000.

Can you describe the steps you did to "load a Basic.ino"? (For example: did you use Arduino IDE? If yes, which version of the ESP32 Arduino core? Or did you use something else, like Platformio?) What was the log output you got while loading the program to the board?

As is, the issue does not seem to be related to this project's repository, but if you provide enough information we can try to point you in the right direction.
