### ISSUE TITLE
ESP32-C3 mbedtls aes GCM (IDFGH-9488)

### ISSUE THREAD

**Issue by samuelbles07** [espressif/esp-idf#10850]
### Additional context.

Hi, 

I just try esp32-c3 but my need is implement aes gcm. When i try just a sample encryption, it thrown an error at `mbedtls_gcm_setkey()` returning `-114` which i check is `MBEDTLS_ERR_PLATFORM_FEATURE_UNSUPPORTED`.

```c
    int keyBits = 192;
    std::string key = "testtesttesttesttesttest"; // 24 char
    // Initialize gcm object
    mbedtls_gcm_context ctx;
    mbedtls_gcm_init(&ctx);
    int ret = mbedtls_gcm_setkey(&ctx, MBEDTLS_CIPHER_ID_AES, (const unsigned char*)key.c_str(), keyBits);
    if( ret != 0 ){
        mbedtls_gcm_free(&ctx);
        ESP_LOGI(TAG, "mbedtls_gcm_setkey error: %d", ret);
        return false;
    }
```

I try using esp-idf v4.4.4 and v5.0.1 but it has the same result. On the other hand, using the same code with esp32 it works. Is something missing or really still not supported?

Thanks!

**Comment by Harshal5** [comment]
Hello @samuelbles07,

As mentioned in the ESP32C3's [SoC capabilities](https://github.com/espressif/esp-idf/blob/master/components/soc/esp32c3/include/soc/soc_caps.h#L75), its AES-DMA hardware supports key sizes of 128 and 256 bits, whereas, in the case of ESP32 and ESP32S2, the AES-DMA hardware supports key sizes of 128, 192 and 256 bits.

You can still use the 192 bits key on ESP32C3 by disabling the hardware AES acceleration (`MBEDTLS_HARDWARE_AES`) config.

Thanks!
