### ISSUE TITLE
Control content of flash 64k pages (instructions/data) / weird 5X performance drops (IDFGH-9509)

### ISSUE THREAD

**Issue by greenaddress** [espressif/esp-idf#10867]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

I was wondering if it is possible to choose what goes in each or at least some 64k flash pages for instructions/data.

For example, one could choose to put functions and data needed in certain context in the same page (s) and minimize or remove any superfluous flash cache map miss/stall? I checked the documentation but I haven't found something quite like this.

Sometimes when building a project, if I add more functionality some other unrelated code (which now I use as a perf measure) may get faster, and likewise when I remove some functionality the code becomes slower, which is non intuitive but could maybe be explained by excessive access to many different flash 64k pages and things shifting around in the binary.

For example I disabled BT/radio and the code became slower. Or I changed from 240mhz to 160mhz and the code run faster. I enabled more heap protections and the code was faster though not the fastest it can be alone in a main function without any heap protection enabled).

In general, more or less, between fast/slow I have available the same amount if dram/iram left and freeing more iram from config generally only slightly alleviates the issue.

If I run the code I use for performance alone in main I get a baseline speed, if I run the same code in main before anything else start with the rest of the code *after* it takes  2-6X longer and looking with perf mon I see a ton of stalls (both data and instructions) which may be explained by a different arrangement of iram/dram/flash static instructions/data and (consequently?) the heaps.

I can't put everything in iram/dram. Using idf 4.4.4 at the moment but same happens with idf 5.0.1 (but it is better than 4.4.4).

We use psram (but not in the performance test), eco v3. In at least an occasion seems for a given commit fast and slow each, enabling flash encryption makes the difference a lot less drastic (1.3X longer for slow vs fast)

This is something I haven't seen before and I still haven't quite pin pointed the cause nor found a solid solution. Thanks.

**Comment by Spritetm** [comment]
What particular code are you talking about that needs the performance? Is it a small routine that is heavily optimized, or are we talking about an entire app worth of code?

**Comment by Alvin1Zhang** [comment]
@greenaddress Thanks for reporting, would you please help share if any updates for the issue? Thanks.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to short of feedback, feel free to reopen with more updates. Thanks.
