### ISSUE TITLE
esp_adc/adc_oneshot.h missing and cannot complie. (IDFGH-9523)

### ISSUE THREAD

**Issue by ua100k** [espressif/esp-idf#10878]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

esp-idf-v4.4

### Operating System used.

Windows

### How did you build your project?

Eclipse IDE

### If you are using Windows, please specify command line type.

None

### What is the expected behavior?

**This is in main.c**
#include "esp_adc/adc_oneshot.h"
#include "esp_adc/adc_continuous.h"
#include "esp_adc/adc_cali.h"
#include "esp_adc/adc_cali_scheme.h"

**This is the failed line.** 
FAILED: esp-idf/main/CMakeFiles/__idf_main.dir/main.c.obj 
ccache C:\Espressif\tools\xtensa-esp32-elf\esp-2021r2-patch2-8.4.0\xtensa-esp32-elf\bin\xtensa-esp32-elf-gcc.exe -DHAVE_CONFIG_H -DMBEDTLS_CONFIG_FILE=\"mbedtls/esp_config.h\" -DUNITY_INCLUDE_CONFIG_H -DWITH_POSIX -Iconfig -I../../../components/newlib/platform_include -I../../../components/freertos/include -I../../../components/freertos/include/esp_additions/freertos -I../../../components/freertos/port/xtensa/include -I../../../components/freertos/include/esp_additions -I../../../components/esp_hw_support/include -I../../../components/esp_hw_support/include/soc -I../../../components/esp_hw_support/include/soc/esp32 -I../../../components/esp_hw_support/port/esp32/. -I../../../components/heap/include -I../../../components/log/include -I../../../components/lwip/include/apps -I../../../components/lwip/include/apps/sntp -I../../../components/lwip/lwip/src/include -I../../../components/lwip/port/esp32/include -I../../../components/lwip/port/esp32/include/arch -I../../../components/soc/include -I../../../components/soc/esp32/. -I../../../components/soc/esp32/include -I../../../components/hal/esp32/include -I../../../components/hal/include -I../../../components/hal/platform_port/include -I../../../components/esp_rom/include -I../../../components/esp_rom/include/esp32 -I../../../components/esp_rom/esp32 -I../../../components/esp_common/include -I../../../components/esp_system/include -I../../../components/esp_system/port/soc -I../../../components/esp_system/port/public_compat -I../../../components/esp32/include -I../../../components/xtensa/include -I../../../components/xtensa/esp32/include -I../../../components/driver/include -I../../../components/driver/esp32/include -I../../../components/esp_pm/include -I../../../components/esp_ringbuf/include -I../../../components/efuse/include -I../../../components/efuse/esp32/include -I../../../components/vfs/include -I../../../components/esp_wifi/include -I../../../components/esp_event/include -I../../../components/esp_netif/include -I../../../components/esp_eth/include -I../../../components/tcpip_adapter/include -I../../../components/esp_phy/include -I../../../components/esp_phy/esp32/include -I../../../components/esp_ipc/include -I../../../components/app_trace/include -I../../../components/esp_timer/include -I../../../components/mbedtls/port/include -I../../../components/mbedtls/mbedtls/include -I../../../components/mbedtls/esp_crt_bundle/include -I../../../components/app_update/include -I../../../components/spi_flash/include -I../../../components/bootloader_support/include -I../../../components/nvs_flash/include -I../../../components/pthread/include -I../../../components/esp_gdbstub/include -I../../../components/esp_gdbstub/xtensa -I../../../components/esp_gdbstub/esp32 -I../../../components/espcoredump/include -I../../../components/espcoredump/include/port/xtensa -I../../../components/wpa_supplicant/include -I../../../components/wpa_supplicant/port/include -I../../../components/wpa_supplicant/esp_supplicant/include -I../../../components/ieee802154/include -I../../../components/console -I../../../components/asio/asio/asio/include -I../../../components/asio/port/include -I../../../components/bt/common/osi/include -I../../../components/bt/include/esp32/include -I../../../components/bt/common/api/include/api -I../../../components/bt/common/btc/profile/esp/blufi/include -I../../../components/bt/common/btc/profile/esp/include -I../../../components/bt/host/bluedroid/api/include/api -I../../../components/cbor/port/include -I../../../components/unity/include -I../../../components/unity/unity/src -I../../../components/cmock/CMock/src -I../../../components/coap/port/include -I../../../components/coap/libcoap/include -I../../../components/nghttp/port/include -I../../../components/nghttp/nghttp2/lib/includes -I../../../components/esp-tls -I../../../components/esp-tls/esp-tls-crypto -I../../../components/esp_adc_cal/include -I../../../components/esp_hid/include -I../../../components/tcp_transport/include -I../../../components/esp_http_client/include -I../../../components/esp_http_server/include -I../../../components/esp_https_ota/include -I../../../components/esp_lcd/include -I../../../components/esp_lcd/interface -I../../../components/protobuf-c/protobuf-c -I../../../components/protocomm/include/common -I../../../components/protocomm/include/security -I../../../components/protocomm/include/transports -I../../../components/mdns/include -I../../../components/esp_local_ctrl/include -I../../../components/sdmmc/include -I../../../components/esp_serial_slave_link/include -I../../../components/esp_websocket_client/include -I../../../components/expat/expat/expat/lib -I../../../components/expat/port/include -I../../../components/wear_levelling/include -I../../../components/fatfs/diskio -I../../../components/fatfs/vfs -I../../../components/fatfs/src -I../../../components/freemodbus/common/include -I../../../components/idf_test/include -I../../../components/idf_test/include/esp32 -I../../../components/jsmn/include -I../../../components/json/cJSON -I../../../components/libsodium/libsodium/src/libsodium/include -I../../../components/libsodium/port_include -I../../../components/mqtt/esp-mqtt/include -I../../../components/openssl/include -I../../../components/perfmon/include -I../../../components/spiffs/include -I../../../components/ulp/include -I../../../components/wifi_provisioning/include -mlongcalls -Wno-frame-address -ffunction-sections -fdata-sections -Wall -Werror=all -Wno-error=unused-function -Wno-error=unused-variable -Wno-error=deprecated-declarations -Wextra -Wno-unused-parameter -Wno-sign-compare -ggdb -Og -fmacro-prefix-map=C:/Espressif/frameworks/esp-idf-v4.4/workspace/DisplayBoard-1_02_31_2023=. -fmacro-prefix-map=C:/Espressif/frameworks/esp-idf-v4.4=IDF -fstrict-volatile-bitfields -Wno-error=unused-but-set-variable -fno-jump-tables -fno-tree-switch-conversion -std=gnu99 -Wno-old-style-declaration -D_GNU_SOURCE -DIDF_VER=\"v4.4\" -DESP_PLATFORM -D_POSIX_READER_WRITER_LOCKS -MD -MT esp-idf/main/CMakeFiles/__idf_main.dir/main.c.obj -MF esp-idf\main\CMakeFiles\__idf_main.dir\main.c.obj.d -o esp-idf/main/CMakeFiles/__idf_main.dir/main.c.obj -c ../main/main.c
../main/main.c:32:10: fatal error: esp_adc/adc_oneshot.h: No such file or directory
 #include "esp_adc/adc_oneshot.h"

**This is the documentation.**
https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/peripherals/adc_oneshot.html

### What is the actual behavior?

**This is in main.c**
#include "esp_adc/adc_oneshot.h"
#include "esp_adc/adc_continuous.h"
#include "esp_adc/adc_cali.h"
#include "esp_adc/adc_cali_scheme.h"

**This is the failed line.** 
FAILED: esp-idf/main/CMakeFiles/__idf_main.dir/main.c.obj 
ccache C:\Espressif\tools\xtensa-esp32-elf\esp-2021r2-patch2-8.4.0\xtensa-esp32-elf\bin\xtensa-esp32-elf-gcc.exe -DHAVE_CONFIG_H -DMBEDTLS_CONFIG_FILE=\"mbedtls/esp_config.h\" -DUNITY_INCLUDE_CONFIG_H -DWITH_POSIX -Iconfig -I../../../components/newlib/platform_include -I../../../components/freertos/include -I../../../components/freertos/include/esp_additions/freertos -I../../../components/freertos/port/xtensa/include -I../../../components/freertos/include/esp_additions -I../../../components/esp_hw_support/include -I../../../components/esp_hw_support/include/soc -I../../../components/esp_hw_support/include/soc/esp32 -I../../../components/esp_hw_support/port/esp32/. -I../../../components/heap/include -I../../../components/log/include -I../../../components/lwip/include/apps -I../../../components/lwip/include/apps/sntp -I../../../components/lwip/lwip/src/include -I../../../components/lwip/port/esp32/include -I../../../components/lwip/port/esp32/include/arch -I../../../components/soc/include -I../../../components/soc/esp32/. -I../../../components/soc/esp32/include -I../../../components/hal/esp32/include -I../../../components/hal/include -I../../../components/hal/platform_port/include -I../../../components/esp_rom/include -I../../../components/esp_rom/include/esp32 -I../../../components/esp_rom/esp32 -I../../../components/esp_common/include -I../../../components/esp_system/include -I../../../components/esp_system/port/soc -I../../../components/esp_system/port/public_compat -I../../../components/esp32/include -I../../../components/xtensa/include -I../../../components/xtensa/esp32/include -I../../../components/driver/include -I../../../components/driver/esp32/include -I../../../components/esp_pm/include -I../../../components/esp_ringbuf/include -I../../../components/efuse/include -I../../../components/efuse/esp32/include -I../../../components/vfs/include -I../../../components/esp_wifi/include -I../../../components/esp_event/include -I../../../components/esp_netif/include -I../../../components/esp_eth/include -I../../../components/tcpip_adapter/include -I../../../components/esp_phy/include -I../../../components/esp_phy/esp32/include -I../../../components/esp_ipc/include -I../../../components/app_trace/include -I../../../components/esp_timer/include -I../../../components/mbedtls/port/include -I../../../components/mbedtls/mbedtls/include -I../../../components/mbedtls/esp_crt_bundle/include -I../../../components/app_update/include -I../../../components/spi_flash/include -I../../../components/bootloader_support/include -I../../../components/nvs_flash/include -I../../../components/pthread/include -I../../../components/esp_gdbstub/include -I../../../components/esp_gdbstub/xtensa -I../../../components/esp_gdbstub/esp32 -I../../../components/espcoredump/include -I../../../components/espcoredump/include/port/xtensa -I../../../components/wpa_supplicant/include -I../../../components/wpa_supplicant/port/include -I../../../components/wpa_supplicant/esp_supplicant/include -I../../../components/ieee802154/include -I../../../components/console -I../../../components/asio/asio/asio/include -I../../../components/asio/port/include -I../../../components/bt/common/osi/include -I../../../components/bt/include/esp32/include -I../../../components/bt/common/api/include/api -I../../../components/bt/common/btc/profile/esp/blufi/include -I../../../components/bt/common/btc/profile/esp/include -I../../../components/bt/host/bluedroid/api/include/api -I../../../components/cbor/port/include -I../../../components/unity/include -I../../../components/unity/unity/src -I../../../components/cmock/CMock/src -I../../../components/coap/port/include -I../../../components/coap/libcoap/include -I../../../components/nghttp/port/include -I../../../components/nghttp/nghttp2/lib/includes -I../../../components/esp-tls -I../../../components/esp-tls/esp-tls-crypto -I../../../components/esp_adc_cal/include -I../../../components/esp_hid/include -I../../../components/tcp_transport/include -I../../../components/esp_http_client/include -I../../../components/esp_http_server/include -I../../../components/esp_https_ota/include -I../../../components/esp_lcd/include -I../../../components/esp_lcd/interface -I../../../components/protobuf-c/protobuf-c -I../../../components/protocomm/include/common -I../../../components/protocomm/include/security -I../../../components/protocomm/include/transports -I../../../components/mdns/include -I../../../components/esp_local_ctrl/include -I../../../components/sdmmc/include -I../../../components/esp_serial_slave_link/include -I../../../components/esp_websocket_client/include -I../../../components/expat/expat/expat/lib -I../../../components/expat/port/include -I../../../components/wear_levelling/include -I../../../components/fatfs/diskio -I../../../components/fatfs/vfs -I../../../components/fatfs/src -I../../../components/freemodbus/common/include -I../../../components/idf_test/include -I../../../components/idf_test/include/esp32 -I../../../components/jsmn/include -I../../../components/json/cJSON -I../../../components/libsodium/libsodium/src/libsodium/include -I../../../components/libsodium/port_include -I../../../components/mqtt/esp-mqtt/include -I../../../components/openssl/include -I../../../components/perfmon/include -I../../../components/spiffs/include -I../../../components/ulp/include -I../../../components/wifi_provisioning/include -mlongcalls -Wno-frame-address -ffunction-sections -fdata-sections -Wall -Werror=all -Wno-error=unused-function -Wno-error=unused-variable -Wno-error=deprecated-declarations -Wextra -Wno-unused-parameter -Wno-sign-compare -ggdb -Og -fmacro-prefix-map=C:/Espressif/frameworks/esp-idf-v4.4/workspace/DisplayBoard-1_02_31_2023=. -fmacro-prefix-map=C:/Espressif/frameworks/esp-idf-v4.4=IDF -fstrict-volatile-bitfields -Wno-error=unused-but-set-variable -fno-jump-tables -fno-tree-switch-conversion -std=gnu99 -Wno-old-style-declaration -D_GNU_SOURCE -DIDF_VER=\"v4.4\" -DESP_PLATFORM -D_POSIX_READER_WRITER_LOCKS -MD -MT esp-idf/main/CMakeFiles/__idf_main.dir/main.c.obj -MF esp-idf\main\CMakeFiles\__idf_main.dir\main.c.obj.d -o esp-idf/main/CMakeFiles/__idf_main.dir/main.c.obj -c ../main/main.c
../main/main.c:32:10: fatal error: esp_adc/adc_oneshot.h: No such file or directory
 #include "esp_adc/adc_oneshot.h"

**This is the documentation.**
https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/peripherals/adc_oneshot.html

### Steps to reproduce.

1.  Include this in the main.c
2.  Hit the hammer button in the idf
3.  See the failure.
...

### Build or installation Logs.

```plain
Building in: C:\Espressif\frameworks\esp-idf-v4.4\workspace\DisplayBoard-1_02_31_2023\build
cmake --build . -- -v
[1/10] cmd.exe /C "cd /D C:\Espressif\frameworks\esp-idf-v4.4\workspace\DisplayBoard-1_02_31_2023\build\bootloader && C:\Espressif\tools\cmake\3.20.3\bin\cmake.exe --build ."
[1/1] cmd.exe /C "cd /D C:\Espressif\frameworks\esp-idf-v4.4\workspace\DisplayBoard-1_02_31_2023\build\bootloader\esp-idf\esptool_py && python C:/Espressif/frameworks/esp-idf-v4.4/components/partition_table/check_sizes.py --offset 0x8000 bootloader 0x1000 C:/Espressif/frameworks/esp-idf-v4.4/workspace/DisplayBoard-1_02_31_2023/build/bootloader/bootloader.bin"
Bootloader binary size 0x62c0 bytes. 0xd40 bytes (12%) free.
[2/8] ccache C:\Espressif\tools\xtensa-esp32-elf\esp-2021r2-patch2-8.4.0\xtensa-esp32-elf\bin\xtensa-esp32-elf-gcc.exe -DHAVE_CONFIG_H -DMBEDTLS_CONFIG_FILE=\"mbedtls/esp_config.h\" -DUNITY_INCLUDE_CONFIG_H -DWITH_POSIX -Iconfig -I../../../components/newlib/platform_include -I../../../components/freertos/include -I../../../components/freertos/include/esp_additions/freertos -I../../../components/freertos/port/xtensa/include -I../../../components/freertos/include/esp_additions -I../../../components/esp_hw_support/include -I../../../components/esp_hw_support/include/soc -I../../../components/esp_hw_support/include/soc/esp32 -I../../../components/esp_hw_support/port/esp32/. -I../../../components/heap/include -I../../../components/log/include -I../../../components/lwip/include/apps -I../../../components/lwip/include/apps/sntp -I../../../components/lwip/lwip/src/include -I../../../components/lwip/port/esp32/include -I../../../components/lwip/port/esp32/include/arch -I../../../components/soc/include -I../../../components/soc/esp32/. -I../../../components/soc/esp32/include -I../../../components/hal/esp32/include -I../../../components/hal/include -I../../../components/hal/platform_port/include -I../../../components/esp_rom/include -I../../../components/esp_rom/include/esp32 -I../../../components/esp_rom/esp32 -I../../../components/esp_common/include -I../../../components/esp_system/include -I../../../components/esp_system/port/soc -I../../../components/esp_system/port/public_compat -I../../../components/esp32/include -I../../../components/xtensa/include -I../../../components/xtensa/esp32/include -I../../../components/driver/include -I../../../components/driver/esp32/include -I../../../components/esp_pm/include -I../../../components/esp_ringbuf/include -I../../../components/efuse/include -I../../../components/efuse/esp32/include -I../../../components/vfs/include -I../../../components/esp_wifi/include -I../../../components/esp_event/include -I../../../components/esp_netif/include -I../../../components/esp_eth/include -I../../../components/tcpip_adapter/include -I../../../components/esp_phy/include -I../../../components/esp_phy/esp32/include -I../../../components/esp_ipc/include -I../../../components/app_trace/include -I../../../components/esp_timer/include -I../../../components/mbedtls/port/include -I../../../components/mbedtls/mbedtls/include -I../../../components/mbedtls/esp_crt_bundle/include -I../../../components/app_update/include -I../../../components/spi_flash/include -I../../../components/bootloader_support/include -I../../../components/nvs_flash/include -I../../../components/pthread/include -I../../../components/esp_gdbstub/include -I../../../components/esp_gdbstub/xtensa -I../../../components/esp_gdbstub/esp32 -I../../../components/espcoredump/include -I../../../components/espcoredump/include/port/xtensa -I../../../components/wpa_supplicant/include -I../../../components/wpa_supplicant/port/include -I../../../components/wpa_supplicant/esp_supplicant/include -I../../../components/ieee802154/include -I../../../components/console -I../../../components/asio/asio/asio/include -I../../../components/asio/port/include -I../../../components/bt/common/osi/include -I../../../components/bt/include/esp32/include -I../../../components/bt/common/api/include/api -I../../../components/bt/common/btc/profile/esp/blufi/include -I../../../components/bt/common/btc/profile/esp/include -I../../../components/bt/host/bluedroid/api/include/api -I../../../components/cbor/port/include -I../../../components/unity/include -I../../../components/unity/unity/src -I../../../components/cmock/CMock/src -I../../../components/coap/port/include -I../../../components/coap/libcoap/include -I../../../components/nghttp/port/include -I../../../components/nghttp/nghttp2/lib/includes -I../../../components/esp-tls -I../../../components/esp-tls/esp-tls-crypto -I../../../components/esp_adc_cal/include -I../../../components/esp_hid/include -I../../../components/tcp_transport/include -I../../../components/esp_http_client/include -I../../../components/esp_http_server/include -I../../../components/esp_https_ota/include -I../../../components/esp_lcd/include -I../../../components/esp_lcd/interface -I../../../components/protobuf-c/protobuf-c -I../../../components/protocomm/include/common -I../../../components/protocomm/include/security -I../../../components/protocomm/include/transports -I../../../components/mdns/include -I../../../components/esp_local_ctrl/include -I../../../components/sdmmc/include -I../../../components/esp_serial_slave_link/include -I../../../components/esp_websocket_client/include -I../../../components/expat/expat/expat/lib -I../../../components/expat/port/include -I../../../components/wear_levelling/include -I../../../components/fatfs/diskio -I../../../components/fatfs/vfs -I../../../components/fatfs/src -I../../../components/freemodbus/common/include -I../../../components/idf_test/include -I../../../components/idf_test/include/esp32 -I../../../components/jsmn/include -I../../../components/json/cJSON -I../../../components/libsodium/libsodium/src/libsodium/include -I../../../components/libsodium/port_include -I../../../components/mqtt/esp-mqtt/include -I../../../components/openssl/include -I../../../components/perfmon/include -I../../../components/spiffs/include -I../../../components/ulp/include -I../../../components/wifi_provisioning/include -mlongcalls -Wno-frame-address -ffunction-sections -fdata-sections -Wall -Werror=all -Wno-error=unused-function -Wno-error=unused-variable -Wno-error=deprecated-declarations -Wextra -Wno-unused-parameter -Wno-sign-compare -ggdb -Og -fmacro-prefix-map=C:/Espressif/frameworks/esp-idf-v4.4/workspace/DisplayBoard-1_02_31_2023=. -fmacro-prefix-map=C:/Espressif/frameworks/esp-idf-v4.4=IDF -fstrict-volatile-bitfields -Wno-error=unused-but-set-variable -fno-jump-tables -fno-tree-switch-conversion -std=gnu99 -Wno-old-style-declaration -D_GNU_SOURCE -DIDF_VER=\"v4.4\" -DESP_PLATFORM -D_POSIX_READER_WRITER_LOCKS -MD -MT esp-idf/main/CMakeFiles/__idf_main.dir/main.c.obj -MF esp-idf\main\CMakeFiles\__idf_main.dir\main.c.obj.d -o esp-idf/main/CMakeFiles/__idf_main.dir/main.c.obj -c ../main/main.c
FAILED: esp-idf/main/CMakeFiles/__idf_main.dir/main.c.obj 
ccache C:\Espressif\tools\xtensa-esp32-elf\esp-2021r2-patch2-8.4.0\xtensa-esp32-elf\bin\xtensa-esp32-elf-gcc.exe -DHAVE_CONFIG_H -DMBEDTLS_CONFIG_FILE=\"mbedtls/esp_config.h\" -DUNITY_INCLUDE_CONFIG_H -DWITH_POSIX -Iconfig -I../../../components/newlib/platform_include -I../../../components/freertos/include -I../../../components/freertos/include/esp_additions/freertos -I../../../components/freertos/port/xtensa/include -I../../../components/freertos/include/esp_additions -I../../../components/esp_hw_support/include -I../../../components/esp_hw_support/include/soc -I../../../components/esp_hw_support/include/soc/esp32 -I../../../components/esp_hw_support/port/esp32/. -I../../../components/heap/include -I../../../components/log/include -I../../../components/lwip/include/apps -I../../../components/lwip/include/apps/sntp -I../../../components/lwip/lwip/src/include -I../../../components/lwip/port/esp32/include -I../../../components/lwip/port/esp32/include/arch -I../../../components/soc/include -I../../../components/soc/esp32/. -I../../../components/soc/esp32/include -I../../../components/hal/esp32/include -I../../../components/hal/include -I../../../components/hal/platform_port/include -I../../../components/esp_rom/include -I../../../components/esp_rom/include/esp32 -I../../../components/esp_rom/esp32 -I../../../components/esp_common/include -I../../../components/esp_system/include -I../../../components/esp_system/port/soc -I../../../components/esp_system/port/public_compat -I../../../components/esp32/include -I../../../components/xtensa/include -I../../../components/xtensa/esp32/include -I../../../components/driver/include -I../../../components/driver/esp32/include -I../../../components/esp_pm/include -I../../../components/esp_ringbuf/include -I../../../components/efuse/include -I../../../components/efuse/esp32/include -I../../../components/vfs/include -I../../../components/esp_wifi/include -I../../../components/esp_event/include -I../../../components/esp_netif/include -I../../../components/esp_eth/include -I../../../components/tcpip_adapter/include -I../../../components/esp_phy/include -I../../../components/esp_phy/esp32/include -I../../../components/esp_ipc/include -I../../../components/app_trace/include -I../../../components/esp_timer/include -I../../../components/mbedtls/port/include -I../../../components/mbedtls/mbedtls/include -I../../../components/mbedtls/esp_crt_bundle/include -I../../../components/app_update/include -I../../../components/spi_flash/include -I../../../components/bootloader_support/include -I../../../components/nvs_flash/include -I../../../components/pthread/include -I../../../components/esp_gdbstub/include -I../../../components/esp_gdbstub/xtensa -I../../../components/esp_gdbstub/esp32 -I../../../components/espcoredump/include -I../../../components/espcoredump/include/port/xtensa -I../../../components/wpa_supplicant/include -I../../../components/wpa_supplicant/port/include -I../../../components/wpa_supplicant/esp_supplicant/include -I../../../components/ieee802154/include -I../../../components/console -I../../../components/asio/asio/asio/include -I../../../components/asio/port/include -I../../../components/bt/common/osi/include -I../../../components/bt/include/esp32/include -I../../../components/bt/common/api/include/api -I../../../components/bt/common/btc/profile/esp/blufi/include -I../../../components/bt/common/btc/profile/esp/include -I../../../components/bt/host/bluedroid/api/include/api -I../../../components/cbor/port/include -I../../../components/unity/include -I../../../components/unity/unity/src -I../../../components/cmock/CMock/src -I../../../components/coap/port/include -I../../../components/coap/libcoap/include -I../../../components/nghttp/port/include -I../../../components/nghttp/nghttp2/lib/includes -I../../../components/esp-tls -I../../../components/esp-tls/esp-tls-crypto -I../../../components/esp_adc_cal/include -I../../../components/esp_hid/include -I../../../components/tcp_transport/include -I../../../components/esp_http_client/include -I../../../components/esp_http_server/include -I../../../components/esp_https_ota/include -I../../../components/esp_lcd/include -I../../../components/esp_lcd/interface -I../../../components/protobuf-c/protobuf-c -I../../../components/protocomm/include/common -I../../../components/protocomm/include/security -I../../../components/protocomm/include/transports -I../../../components/mdns/include -I../../../components/esp_local_ctrl/include -I../../../components/sdmmc/include -I../../../components/esp_serial_slave_link/include -I../../../components/esp_websocket_client/include -I../../../components/expat/expat/expat/lib -I../../../components/expat/port/include -I../../../components/wear_levelling/include -I../../../components/fatfs/diskio -I../../../components/fatfs/vfs -I../../../components/fatfs/src -I../../../components/freemodbus/common/include -I../../../components/idf_test/include -I../../../components/idf_test/include/esp32 -I../../../components/jsmn/include -I../../../components/json/cJSON -I../../../components/libsodium/libsodium/src/libsodium/include -I../../../components/libsodium/port_include -I../../../components/mqtt/esp-mqtt/include -I../../../components/openssl/include -I../../../components/perfmon/include -I../../../components/spiffs/include -I../../../components/ulp/include -I../../../components/wifi_provisioning/include -mlongcalls -Wno-frame-address -ffunction-sections -fdata-sections -Wall -Werror=all -Wno-error=unused-function -Wno-error=unused-variable -Wno-error=deprecated-declarations -Wextra -Wno-unused-parameter -Wno-sign-compare -ggdb -Og -fmacro-prefix-map=C:/Espressif/frameworks/esp-idf-v4.4/workspace/DisplayBoard-1_02_31_2023=. -fmacro-prefix-map=C:/Espressif/frameworks/esp-idf-v4.4=IDF -fstrict-volatile-bitfields -Wno-error=unused-but-set-variable -fno-jump-tables -fno-tree-switch-conversion -std=gnu99 -Wno-old-style-declaration -D_GNU_SOURCE -DIDF_VER=\"v4.4\" -DESP_PLATFORM -D_POSIX_READER_WRITER_LOCKS -MD -MT esp-idf/main/CMakeFiles/__idf_main.dir/main.c.obj -MF esp-idf\main\CMakeFiles\__idf_main.dir\main.c.obj.d -o esp-idf/main/CMakeFiles/__idf_main.dir/main.c.obj -c ../main/main.c
../main/main.c:32:10: fatal error: esp_adc/adc_oneshot.h: No such file or directory
 #include "esp_adc/adc_oneshot.h"
          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
Build complete (1 errors, 0 warnings): C:\Espressif\frameworks\esp-idf-v4.4\workspace\DisplayBoard-1_02_31_2023\build
C:\Espressif\python_env\idf4.4_py3.8_env\Scripts\python.exe C:\Espressif\frameworks\esp-idf-v4.4\tools\idf_size.py C:/Espressif/frameworks/esp-idf-v4.4/workspace/DisplayBoard-1_02_31_2023/build/DisplayBoard-1_02_31_2023.map
C:\Espressif\python_env\idf4.4_py3.8_env\Scripts\python.exe C:/Espressif/frameworks/esp-idf-v4.4//components/partition_table/gen_esp32part.py C:/Espressif/frameworks/esp-idf-v4.4/workspace/DisplayBoard-1_02_31_2023/build/partition_table/partition-table.bin
Total time taken to build the project: 2,506 ms
```

### More Information.

works on linux.

**Comment by Icarus113** [comment]
Hi @ua100k , these headers are newly added on v5.0. For v4.4, you still have to use this [header](https://github.com/espressif/esp-idf/blob/release/v4.4/examples/peripherals/adc/single_read/single_read/main/single_read.c#L20)
```
#include "esp_adc/adc_oneshot.h"
#include "esp_adc/adc_continuous.h"
#include "esp_adc/adc_cali.h"
#include "esp_adc/adc_cali_scheme.h"
```

**Comment by ua100k** [comment]
Thank you. this worked.
