### ISSUE TITLE
Missing Kconfig checker (IDFGH-9516)

### ISSUE THREAD

**Issue by tadejg** [espressif/esp-idf#10872]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Documentation mentions a Kconfig checker script [here](https://docs.espressif.com/projects/esp-idf/en/v5.0.1/esp32c3/api-reference/kconfig.html#format-checker).

This script appears to have been removed in version v4.3.
Still exists in v4.2: https://github.com/espressif/esp-idf/blob/release/v4.2/tools/check_kconfigs.py
Doesn't exist in v4.3: https://github.com/espressif/esp-idf/blob/release/v4.3/tools/check_kconfigs.py

**EDIT:** As a workaround, I simply downloaded the script from version v4.2 into `esp-idf/tools/check_kconfigs.py` and ran it in my project using `check_kconfigs.py -d .`. Seems to work as expected.

**Comment by dobairoland** [comment]
The script has been moved from the `tools` to the `tools/ci` directory. Thanks for the report!

Also one doesn't have to use this directly. If the contribution guide is followed then the check should be part of the automatic pre-commit checks. The documentation clearly has to be updated and the corrections backported.

So @tadejg. If you do [this part](https://docs.espressif.com/projects/esp-idf/en/v5.0.1/esp32c3/contribute/install-pre-commit-hook.html) then the checker is run (together with others) when you make a git commit.

**Comment by igrr** [comment]
I think the key point here is

> and ran it in my project using check_kconfigs.py -d .. Seems to work as expected.

so the use case, as i understand, is not to check commits in IDF repo, but to use the same tool to check the commits in a custom IDF-based project.

Perhaps we could make the tool available as part of https://github.com/espressif/esp-idf-kconfig package?
