### ISSUE TITLE
How to use dma during rmt? (IDFGH-9527)

### ISSUE THREAD

**Issue by casitelwithdean** [espressif/esp-idf#10881]
### Is your feature request related to a problem?
My chip is esp32s3wroom1
I am using rmt to blink ws2812，but it blinks in a mess sometimes.So how to use dma during rmt-tx to avoid this problem?
Thanks

**Comment by suda-morris** [comment]
The [programming guide](https://docs.espressif.com/projects/esp-idf/en/latest/esp32s3/api-reference/peripherals/rmt.html#install-rmt-tx-channel) says there's a config option  [rmt_tx_channel_config_t::with_dma](https://docs.espressif.com/projects/esp-idf/en/latest/esp32s3/api-reference/peripherals/rmt.html#_CPPv4N23rmt_tx_channel_config_t8with_dmaE).

if you're using the [led_strip component](https://components.espressif.com/components/espressif/led_strip), you can enable the DMA feature [here](https://github.com/espressif/idf-extra-components/blob/master/led_strip/include/led_strip_rmt.h#L25)
