### ISSUE TITLE
All Wifi IDF4.4 Demo Not working for ESP32S3? All connected wifi failed!!!!!! (IDFGH-9540)

### ISSUE THREAD

**Issue by edword01** [espressif/esp-idf#10894]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Why all the IDF4.4 demos relative to wifi are not working ok!!!!!???? I try to make may esp32s3-devkitC to connect wifi,  all fail.
Please help me up.  i am sure hardware has no problem with that,  and config SSID, and password is ok. 

And I try the same demo on ESP32 board, not ESP32S3, is working ok,  that was really confused.
I try 2.4G wifi and 5G wifi both for ESP32S3.

Please tell me how to get ESP32S3 connect to the normal WIFi..

**Comment by Xiehanxin** [comment]
hi @edword01 , could you please share your log? Like when you run the station example. And just try 2.4 GHz wifi, 5G is not supprt.

**Comment by edword01** [comment]
![image](https://user-images.githubusercontent.com/26646966/222694298-08ab74c5-489e-4932-a335-9cb0515ebaf7.png)

**Comment by Xiehanxin** [comment]
Yes, the log shows that the ESP32-S3 has tried five times but can't connect to internet, as this is a just simple station demo, I think it might be caused by 2 reasons: 1. wrong ssid or password 2. hardware detect.
You could try these steps for further confirm: 1.use the examples/wifi/scan demo to see if it can print the nearby wifi 2. use another ESP32-S3 devkit board for test

**Comment by edword01** [comment]
i have 3 new board , all fail to connect wifi,  could u give a verified demo of esp32s3  to me?

**Comment by Xiehanxin** [comment]
hi, here is my test bin, I set the ssid same SSID and password as yours, here is my log and bin, you just need to burn it to address 0.
![image](https://user-images.githubusercontent.com/37785066/223004139-2cdff97c-5bec-41f1-bc91-faa45eddafce.png)
[test.zip](https://github.com/espressif/esp-idf/files/10893786/test.zip)

**Comment by edword01** [comment]
hello Xiehanxin, this is my try of your test.bin
![image](https://user-images.githubusercontent.com/26646966/223615192-579feafb-d862-464e-a0da-c6393db9e0c2.png)

**Comment by Xiehanxin** [comment]
strange..could you please try this
[s3scan.zip](https://github.com/espressif/esp-idf/files/10942301/s3scan.zip)

**Comment by Sherry616** [comment]
Hi @edword01, do you still have this problem? Any updates on this? Thanks.

**Comment by Sherry616** [comment]
Thanks for reporting, will close due to short of feedback, feel free to reopen with more updates.
