### ISSUE TITLE
ESP32C6 code execution freeze (IDFGH-9544)

### ISSUE THREAD

**Issue by RuslanSpartak** [espressif/esp-idf#10898]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

I know that esp-idf for esp32c6 not ready, but just to let you know that at some point code execution freeze without any error or hard fault.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, would you please help share more details as per the [template](https://github.com/espressif/esp-idf/issues/new/choose)? Thanks.
