### ISSUE TITLE
[question] hci over usb on S3 (IDFGH-9570)

### ISSUE THREAD

**Issue by chegewara** [espressif/esp-idf#10919]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Hi,
sorry for noob-ish question, and probably i should ask on forum, but is it possible to implement HCI over USB or is there plan to add it?

Thanks

**Comment by roma-jam** [comment]
@chegewara, 
Hi.
Isn't USB Host interface already available can fulfil your requirement? 
Have you checked it? 

https://github.com/espressif/esp-idf/blob/master/components/usb/include/usb/usb_host.h

Thanks.

**Comment by chegewara** [comment]
Hi,
i just realized that my question was not precise.
What i am asking is BLE HCI over USB, just like in this example over UART:
https://github.com/espressif/esp-idf/tree/master/examples/bluetooth/hci/controller_hci_uart_esp32c3_and_esp32s3

Thanks

**Comment by xiewenxiang** [comment]
Yes, you can refer to https://github.com/espressif/esp-iot-solution/tree/usb/add_usb_solutions/examples/usb/device/usb_dongle

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to short of feedback, feel free to reopen with more updates. Thanks.
