### ISSUE TITLE
[TW#15773] Wrong error flag uart.c

### ISSUE THREAD

**Issue by metx** [espressif/esp-idf#1091]
At beginning of uart_read_bytes()function the second assertion check should return a "buffer is null" error or similar, instead of "uart_num error":

```
int uart_read_bytes(uart_port_t uart_num, uint8_t* buf, uint32_t length, TickType_t ticks_to_wait)
{
   UART_CHECK((uart_num < UART_NUM_MAX), "uart_num error", (-1));
   UART_CHECK((buf), "uart_num error", (-1)); //<-- Incorrect
    ....
}
```

**Comment by krzychb** [comment]
Hi @metx,
Thank you for reporting this issue :+1:
I am preparing an update of the UART documentation and will include this correction.
