### ISSUE TITLE
Documentation seems wrong about ULP FSM's JUMPR instruction (IDFGH-9574)

### ISSUE THREAD

**Issue by agarof** [espressif/esp-idf#10923]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

There seems to have been an erroneous change in the ULP JUMPR instruction's documentation in v4.4.

In the [ESP32 v4.3.4 documentation](https://docs.espressif.com/projects/esp-idf/en/v4.3.4/esp32/api-guides/ulp_instruction_set.html#jumpr-jump-to-a-relative-offset-condition-based-on-r0)
> Conditions LT, GE, LE and GT: 2 cycles to execute, 2 cycles to fetch next instruction
> Conditions LE and GT are implemented in the assembler using one JUMPR instructions:
> [...]
> Conditions EQ is implemented in the assembler using two JUMPR instructions:

In the [ESP32 v4.4.4 documentation](https://docs.espressif.com/projects/esp-idf/en/v4.4.4/esp32/api-guides/ulp_instruction_set.html#jumpr-jump-to-a-relative-offset-condition-based-on-r0)
> Conditions EQ, GT and LT: 2 cycles to execute, 2 cycles to fetch next instruction Conditions LE and GE are implemented in the assembler using two JUMPR instructions:

The [ESP32 v5.0.1 documentation](https://docs.espressif.com/projects/esp-idf/en/v5.0.1/esp32/api-reference/system/ulp_instruction_set.html#jumpr-jump-to-a-relative-offset-condition-based-on-r0) seems unchanged from v4.4.4.

Using a very minimal ulp program, I checked what code was generated for the ESP32 chip in both v4.3.4 and v5.0.1, which resulted in identical output for both versions.
```asm
    .text
    jumpr stop,1,CONDITION
stop:
    halt
```

Here are the code sections of the resulting `bin.S` files:
CONDITION = `lt`:
```asm
.byte 0x75, 0x6c, 0x70, 0x00, 0x0c, 0x00, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x02, 0x82
.byte 0x00, 0x00, 0x00, 0xb0
```
CONDITION = `gt`:
```asm
.byte 0x75, 0x6c, 0x70, 0x00, 0x0c, 0x00, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x03, 0x82
.byte 0x00, 0x00, 0x00, 0xb0
```
CONDITION = `le`:
```asm
.byte 0x75, 0x6c, 0x70, 0x00, 0x0c, 0x00, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x02, 0x82
.byte 0x00, 0x00, 0x00, 0xb0
```
CONDITION = `ge`:
```asm
.byte 0x75, 0x6c, 0x70, 0x00, 0x0c, 0x00, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x03, 0x82
.byte 0x00, 0x00, 0x00, 0xb0
```
CONDITION = `eq`:
```asm
.byte 0x75, 0x6c, 0x70, 0x00, 0x0c, 0x00, 0x0c, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x05, 0x82
.byte 0x01, 0x00, 0x03, 0x82, 0x00, 0x00, 0x00, 0xb0
```

The `eq` version is one instruction (4 bytes) longer than the others, matching the v4.3.4 documentation.

**Comment by sudeep-mohanty** [comment]
Hi @agarof,
Thanks for bringing this discrepancy to our notice. Indeed, the description for `JUMPR` instruction for `esp32` has been incorrect since v4.4. We will be updating the docs shortly and also back port the changes. Thank you!
