### ISSUE TITLE
aws_iot: failed! mbedtls_net_connect returned -0x52 (IDFGH-9585)

### ISSUE THREAD

**Issue by RuslanSpartak** [espressif/esp-idf#10934]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

After some time esp32c6 not able to connnect via mqtt library.
(2036778) aws_iot: failed! mbedtls_net_connect returned -0x52
(2036778) MQTT: Error (-23) - NETWORK_ERR_NET_UNKNOWN_HOST connecting to ***.amazonaws.com:8883: Returned when the server is unknown

**Comment by laukik-hase** [comment]
Closing this issue, feel free to reopen with more updates.
