### ISSUE TITLE
ESP32-I2C通信时，ACK信号之后、STOP信号之前SDA上会出现一个未知原因引起的脉冲 (IDFGH-9584)

### ISSUE THREAD

**Issue by luckyxinshidai** [espressif/esp-idf#10933]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

ESP32-I2C通信时，ACK信号之后、STOP信号之前SDA上会出现一个未知原因引起的脉冲，如下图所示：
![image](https://user-images.githubusercontent.com/20281176/223363960-a22e2825-52c1-4e2a-9a27-525c9b46c466.png)

**Comment by mythbuster5** [comment]
ACK 之后 STOP之前的脉冲是因为主从交互产生的，是正常现象
