### ISSUE TITLE
cla-assistant.io displayed agreement differ from source-code (IDFGH-9589)

### ISSUE THREAD

**Issue by MarcFinetRtone** [espressif/esp-idf#10937]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Hello,

While trying to submit a PR, I've been asked by the CLA assistant to sign the Contributor Agreement.
However:
- the text does not match what's found in the repository (https://github.com/espressif/esp-idf/blob/master/docs/en/contribute/contributor-agreement.rst), not even a previous version.
- the rendering is not correct (e.g. code-blocks) and makes it difficult to read
- the link  https://github.com/espressif/esp-idf/blob/master/CONTRIBUTING.rst is broken

It seems that the gist used by cla-assistant.io (https://gist.github.com/wujiangang/eb9de1d5fa93d2da6a21e16393780f46 ?) is out of date.

Screenshot: 
![screenshot-2023-03-08-15:25:24](https://user-images.githubusercontent.com/51125295/223738836-92dbee34-7c77-4d4a-88f6-fe5320abb3d3.png)

**Comment by zikalino** [comment]
@MarcFinetRtone this issue should be fixed now in CLA Assistant.
Additional small fixes should be synced with the version of agreement on master branch here very soon.
