### ISSUE TITLE
Nimble BLE SPP Server Documentation correction (IDFGH-9581)

### ISSUE THREAD

**Issue by felixcollins** [espressif/esp-idf#10930]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

In the md documentation for the SPP Server it says... 

"This example creates GATT client and performs passive scan, it then connects to peripheral device if the device advertises connectability and the write characteristic.

It performs three GATT operations against the specified peer:

    Discover all services,characteristics and descriptors.

    After the discovery is completed, take UART input from user and write characteristic."

Surely that should say "GATT Server"? Also... the Server advertises rather than doing a scan. It seems that the documentation has copy paste errors from the client doc. It needs careful checking.

**Comment by IshaESP** [comment]
Thank you for pointing this out. An internal fix for the same is raised.
