### ISSUE TITLE
rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT) (IDFGH-9598)

### ISSUE THREAD

**Issue by Achudh** [espressif/esp-idf#10948]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
invalid header: 0x88a0f530
invalid header: 0x88a0f530
invalid header: 0x88a0f530
invalid header: 0x88a0f530
invalid header: 0x88a0f530
invalid header: 0x88a0f530
invalid header: 0x88a0f530

**Comment by ESP-Marius** [comment]
This is the error you would typically see if you have enabled flash encryption, but the flash contains a plaintext binary (or vice versa). Or if you flashed something that is not a valid bootloader to where the chip expects to find its secondary bootloader.

1. How did you flash your software?
2. Did you enable flash encryption? (you can check with `espefuse.py summary`)

**Comment by Alvin1Zhang** [comment]
@Achudh Thanks for reporting, will you please help share if any updates for the issue? Thanks.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to short of feedback, feel free to reopen with more updates. Thanks.
