### ISSUE TITLE
ANCS suports only ios but for android (IDFGH-9612)

### ISSUE THREAD

**Issue by saitez** [espressif/esp-idf#10960]
Hi iam working on esp32s3 , iam using ANCS example to display notifications of the mobile calls etc .

The current example only supports iphone kindly share the info about android also
thanks

**Comment by saitez** [comment]
Can you people look into this we have urgency

**Comment by saitez** [comment]
> ANCS is an Apple feature, it may not exist for Android devices as-is. 

Oh got it Thanks for your response

**Comment by Alvin1Zhang** [comment]
Thanks for reporting and sharing the updates, feel free to reopen.
