### ISSUE TITLE
The IDF 4.4.2 project build error after installed IDF 4.4.3 (IDFGH-9617)

### ISSUE THREAD

**Issue by robbinlu-ayla** [espressif/esp-idf#10965]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

4.4.2

### Operating System used.

Linux

### How did you build your project?

Command line with idf.py

### If you are using Windows, please specify command line type.

None

### What is the expected behavior?

IDF 4.4.2 project could build success after installed IDF 4.4.3.

### What is the actual behavior?

IDF 4.4.2 project built failed after installed IDF 4.4.3.

### Steps to reproduce.

1. Install IDF 4.4.2
2. Install IDF 4.4.3
3. Build 4.4.2 project
...

### Build or installation Logs.

```plain
Checking "python" ...
Python 3.8.10
"python" has been detected
Adding ESP-IDF tools to PATH...
Traceback (most recent call last):
  File ".../espressif/tools/idf_tools.py", line 1860, in <module>
    main(sys.argv[1:])
  File ".../espressif/tools/idf_tools.py", line 1856, in main
    action_func(args)
  File ".../espressif/tools/idf_tools.py", line 1177, in action_export
    tools_info = filter_tools_info(tools_info)
  File ".../espressif/tools/idf_tools.py", line 1119, in filter_tools_info
    targets = get_user_defined_targets()
  File ".../espressif/tools/idf_tools.py", line 1099, in get_user_defined_targets
    if env == idf_env_json['idfSelectedId']:
KeyError: 'idfSelectedId'
```

### More Information.

Deleted all files(except dist folder) in ~/.espressif/, and run the install.sh in IDF 4.4.2 to install IDF tool again, then build IDF 4.4.2 project, it could build success.

**Comment by dobairoland** [comment]
There was a regression for switching but it has been fixed in v4.4.4. 

The workaround if you want to switch from 4.4.2 to 4.4.3 is to remove `~/.espressif/idf-env.json` and rerun the install and export scripts.

But as always, we recommend to use the latest bugfix release, i.e. v4.4.4 at this moment.
