### ISSUE TITLE
macos_idf.py_error (IDFGH-9628)

### ISSUE THREAD

**Issue by liker292** [espressif/esp-idf#10975]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

V5.0

### Operating System used.

macOS

### How did you build your project?

Command line with idf.py

### If you are using Windows, please specify command line type.

None

### What is the expected behavior?

aa@zzz hello_world % idf.py
###   **_File "/Users/zmz/esp/esp-idf/tools/idf.py", line 46
    print('Please use idf.py only in an ESP-IDF shell environment.', file=sys.stderr)
                                                                         ^
SyntaxError: invalid syntax_**

Any body know How to deal with the error,please?

### What is the actual behavior?

ssssss

### Steps to reproduce.

1. Step
2. Step
3. Step
...
sssss

### More Information.

ssss

**Comment by dobairoland** [comment]
Please follow the guide how to setup a working environment: https://docs.espressif.com/projects/esp-idf/en/latest/esp32/get-started/linux-macos-setup.html

I would guess that you use Python 2.7. Youl will need Python 3. See: https://docs.espressif.com/projects/esp-idf/en/latest/esp32/get-started/linux-macos-setup.html#installing-python-3
