### ISSUE TITLE
Bridge between wifi and ethernet，wifi send error (IDFGH-9647)

### ISSUE THREAD

**Issue by ICENacl** [espressif/esp-idf#10991]
### Is your feature request related to a problem?

i am using **eth2ap** example to finish my work and i meet some problem when i am changing some code. i am using ESP-IDF v4.4.4.
In my work, one ESP32 work as "master node" and another node work as "slave node"，the master node connect with slave node with ethernet. As the master node, it connect to router(pc hotspot) at the same time to access network, so bridge need to be implemented between ethernet and wifi in the master node. When the whole system start, the slave node become a DHCP client and send DHCP packet to master node through ethernet, the master node receive the packet and send it to the router throught wifi by using the bridge. In the end, the slave get its IP address.
In the **eth2ap** example, the data from ethernet is sent by **esp_wifi_internal_tx** in the **eth2wifi_flow_control_task** function , i am using WireShark to capture packets. My problem is that the DHCP DISCOVER packet that sent by **esp_wifi_internal_tx** dont capture by WireShark，Is there anything wrong with my systen architecture?

**Comment by kostaond** [comment]
Hi @ICENacl, just to summarize to be sure that I understand to your issue correctly:
* ESP32 `Master` is realized by **eth2ap** example
* ESP32 `Slave` is realized by (I presume)**Ethernet Basic** or similar example
* The `Slave` gets IP address in such configuration => **so the system works as expected**
* The only problem is to capture traffic

Where is the DHCP Server running? In the router or on your PC which is connected  to the router? Where do you try to capture the traffic by WireShark?

**Comment by ICENacl** [comment]
@kostaond, Sorry to see your reply after a few weeks, I have sovled the problem by using ip forwarding and NAT, thank you for your reply.
