### ISSUE TITLE
Pullup is not configured by gpio_config 

### ISSUE THREAD

**Issue by ggsubs** [espressif/esp-idf#110]
The following config is not enabling pullup:

```
	 gpio_config_t io_conf;
	 io_conf.intr_type = GPIO_INTR_NEGEDGE; 
	 io_conf.mode = GPIO_MODE_INPUT; 
	 io_conf.pin_bit_mask = GPIO_SEL_21;
	 io_conf.pull_down_en = 0; 
	 io_conf.pull_up_en = 1; 
	 gpio_config(&io_conf); 
```
Implicit gpio_set_pull_mode is needed after gpio_config to enable pull-up:

```gpio_set_pull_mode(21, GPIO_PULLUP_ONLY);```

**Comment by igrr** [comment]
Thanks @ggsubs, your fix has been merged into master.
