### ISSUE TITLE
BROWNOUT esp32c6 (IDFGH-9672)

### ISSUE THREAD

**Issue by RuslanSpartak** [espressif/esp-idf#11013]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

I want to know how much maximum current esp32c6 use when all is enabled, like periphery, ble and wifi. Because after a while I have brownouts reboots.

**Comment by esp-lis** [comment]
You can try to modify the brownout threshold to increase the threshold voltage, the location of `brownout volatage level` option is **(TOP) -> Component config -> ESP System Settings ->Brownout Detector -> Hardware brownout detect & reset -> Brownout voltage level**.

**Comment by RuslanSpartak** [comment]
I disable that. And it still brownout.

**Comment by mythbuster5** [comment]
So... Can you show your logs after you disabled brownout but there is still a brownout reset? I can't see this on my board @RuslanSpartak

**Comment by krzychb** [comment]
> I want to know how much maximum current esp32c6 use when all is enabled, like periphery, ble and wifi.

Hi @RuslanSpartak, [according to ESP32-C6 Dataseet](https://www.espressif.com/sites/default/files/documentation/esp32-c6_datasheet_en.pdf) the power supply to the chip should provide at least 500 mA. If there are other devices connected to the board then respective current requirements should be added on top of that.

![WeChatWorkScreenshot_a6b5d361-9a6b-466e-951c-dc0a964970a5](https://user-images.githubusercontent.com/12953787/226887898-8e69c47c-6221-4fd5-8404-197da69add99.png)

**Comment by RuslanSpartak** [comment]
> So... Can you show your logs after you disabled brownout but there is still a brownout reset? I can't see this on my board @RuslanSpartak

Sorry for late responce. So we can disable detecting brownout. But I still get brownout reboots.
![image](https://user-images.githubusercontent.com/64797883/227472913-cec0df3a-f344-41d6-9b8e-74cb9cd575c1.png)

**Comment by mythbuster5** [comment]
> Any updates on this issue?

Still in progress, will inform you if there is any updates.

**Comment by mythbuster5** [comment]
@RuslanSpartak Hi, this issue is pretty weird. I want to get more information? What modules are you using? Do you both use wifi and bluetooth together?

**Comment by RuslanSpartak** [comment]
> @RuslanSpartak Hi, this issue is pretty weird. I want to get more information? What modules are you using? Do you both use wifi and bluetooth together?

I'm using esp32-c6-devkitc-1. Also module from it. I use wifi and ble together (blufi).

**Comment by RuslanSpartak** [comment]
So any updates with brownout issue?

**Comment by RuslanSpartak** [comment]
![brownout](https://user-images.githubusercontent.com/64797883/236403407-1504d889-2198-41e3-83dd-c671c54956d0.jpg)
I time to time have brownouts with latest master sdk

**Comment by AxelLin** [comment]
> > Any updates on this issue?
> 
> Still in progress, will inform you if there is any updates.

@mythbuster5 @mahavirj  Any new finding?

**Comment by ginkgm** [comment]
Hi @RuslanSpartak @AxelLin ,

We suspect this issue is fixed in latest PHY, please upgrade IDF to HEAD of IDF release/v5.1 and have a try again.

**Comment by RuslanSpartak** [comment]
> Hi @RuslanSpartak @AxelLin ,
> 
> We suspect this issue is fixed in latest PHY, please upgrade IDF to HEAD of IDF release/v5.1 and have a try again.

Yes. All is fine with latest sdk. Thanks.
