### ISSUE TITLE
[MESH] v4.4, cannot specify MESH running core (IDFGH-9682)

### ISSUE THREAD

**Issue by KonssnoK** [espressif/esp-idf#11023]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

as per title, 
it's currently not possible to specify the core affinity for internal MESH tasks.

this makes the system to be non reproducible.

Specifically the following tasks
```
W (00:00:13.166) stats:  MTXBLK      13     0     0   1224    7   2147483647
W (00:00:13.174) stats:     MTX      14     0     0   1428   13   2147483647
W (00:00:13.182) stats:   MTXON      15     0     0   2104   13   2147483647
W (00:00:13.189) stats:     MRX      16     0     0   2268   13   2147483647
W (00:00:13.204) stats:    MNWK      17     0     0   1968   15   2147483647
```

**Comment by zhangyanjiaoesp** [comment]
@KonssnoK Currently,  the mesh does not specify the core when creating a task, and we have no plan to change it.

**Comment by KonssnoK** [comment]
@zhangyanjiaoesp but this can impact any testing scenario, since different timings might make the tasks run on different cores.. basically it becomes much harder to reproduce any given scenario... 🤔

**Comment by zhangyanjiaoesp** [comment]
@KonssnoK 
The mesh code call `_task_create` to create tasks, if you really want to specify the core for mesh tasks, you can change the code in `esp_adapter.c` as the following:

![image](https://user-images.githubusercontent.com/30309181/226850181-3349fa92-c149-4b41-ad9b-942bac9f8d04.png)
If the task name is mesh task, then specify the core.

**Comment by KonssnoK** [comment]
thanks! that seems a good workaround! :)

**Comment by KonssnoK** [comment]
i create an internal ticket, i'll close this issue when we proceed, i guess 1 week time

**Comment by KonssnoK** [comment]
so i did try the following piece of code

```
static int32_t task_create_wrapper(void *task_func, const char *name, uint32_t stack_depth, void *param, uint32_t prio, void *task_handle)
{
    size_t len = strlen(name);
    if( !memcmp(name, "MTXBLK", len) ||
        !memcmp(name, "MTX"   , len) ||
        !memcmp(name, "MTXON" , len) ||
        !memcmp(name, "MRX"   , len) ||
        !memcmp(name, "MNWK"  , len) ){
        return (uint32_t)xTaskCreatePinnedToCore(task_func, name, stack_depth, param, prio, task_handle, 1);
    }
    return (uint32_t)xTaskCreate(task_func, name, stack_depth, param, prio, task_handle);
}
```

but it didn't work as expected.
This issue is being postponed by the other ones we currently have :)

**Comment by zhangyanjiaoesp** [comment]
@KonssnoK You need to change the code in `components/esp_wifi/esp32s3/esp_adapter.c`.  I have tested locally, it can works.

**Comment by Sherry616** [comment]
Hi @KonssnoK, do you still have this problem? Could you share the latest update? Thanks.

**Comment by KonssnoK** [comment]
Hello @Sherry616 , sadly we didn't have time to follow this topic because of all the other issues that we currently have open.
It's still on our list tho, we will face it at some point.

**Comment by zhangyanjiaoesp** [comment]
@KonssnoK can we close this ?

**Comment by KonssnoK** [comment]
Yes, we know how to do it, we just have no time to try it out.
An option on the sdkconfig would be great tho @zhangyanjiaoesp
