### ISSUE TITLE
Unexpected chip id in image for esp32h2 (IDFGH-9681)

### ISSUE THREAD

**Issue by gl-chenxiaosheng** [espressif/esp-idf#11022]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

I use IDF release v5.0, compiled the firmware and flash it into esp32h2. I found the following message:
```shell
Unexpected chip id in image. Expected 16 but value was 14. Is this image for a different chip model?
```
And I see the Kconfig in IDF release v5.0 as follow:
```
    config IDF_FIRMWARE_CHIP_ID
        hex
        default 0x0000 if IDF_TARGET_ESP32
        default 0x0002 if IDF_TARGET_ESP32S2
        default 0x0005 if IDF_TARGET_ESP32C3
        default 0x0009 if IDF_TARGET_ESP32S3
        default 0x000C if IDF_TARGET_ESP32C2
        default 0x000A if IDF_TARGET_ESP32H2_BETA_VERSION_1
        default 0x000E if IDF_TARGET_ESP32H2_BETA_VERSION_2 # ESP32H2-TODO: IDF-3475
        default 0xFFFF
```

And I see the Kconfig in IDF master as follow:
```
    config IDF_FIRMWARE_CHIP_ID
        hex
        default 0x0000 if IDF_TARGET_ESP32
        default 0x0002 if IDF_TARGET_ESP32S2
        default 0x0005 if IDF_TARGET_ESP32C3
        default 0x0009 if IDF_TARGET_ESP32S3
        default 0x000A if IDF_TARGET_ESP32H4_BETA_VERSION_1
        default 0x000C if IDF_TARGET_ESP32C2
        default 0x000D if IDF_TARGET_ESP32C6
        default 0x000E if IDF_TARGET_ESP32H4_BETA_VERSION_2 # ESP32-TODO: IDF-3475
        default 0x0010 if IDF_TARGET_ESP32H2
        default 0xFFFF
```
So I checkout to master, it work normally.
When do you plan to merge the configuration of the esp32h2 chip id into the release branch? Please tell me what you plan?

**Comment by igrr** [comment]
> When do you plan to merge the configuration of the esp32h2 chip id into the release branch? Please tell me what you plan?

@gl-chenxiaosheng In `master`, `release/v5.1` and later release branches we will only support the mass production version of ESP32-H2 (chip IDF 16).

release/v5.0 branch will still contain the preview support for ESP32-H2-beta1 and ESP32-H2-beta2 (chip IDs 10 and 14). We don not plan backporting support for ESP32-H2 mass production chip to release/v5.0.

Please refer to https://github.com/espressif/esp-idf/issues/11038 for the information about ESP32-H2 support status and plan.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, feel free to reopen.
