### ISSUE TITLE
ESP32S3 BLE Advertise On Single Channel (IDFGH-9688)

### ISSUE THREAD

**Issue by TGiles1998** [espressif/esp-idf#11029]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

V4.4

### Operating System used.

macOS

### How did you build your project?

Command line with idf.py

### If you are using Windows, please specify command line type.

None

### What is the expected behavior?

How can I make the ESP32S3 only transmit on a single channel, e.g. channel 37?

### What is the actual behavior?

How can I make the ESP32S3 only transmit on a single channel, e.g. channel 37?

### Steps to reproduce.

How can I make the ESP32S3 only transmit on a single channel, e.g. channel 37?

### Build or installation Logs.

How can I make the ESP32S3 only transmit on a single channel, e.g. channel **37?**

### More Information.

How can I make the ESP32S3 only transmit on a single channel, e.g. channel 37?

**Comment by xiewenxiang** [comment]
The `adv params` contains `channel_map` member  variable, such as below:

```c
typedef struct {
    uint16_t                adv_int_min;        /*!< Minimum advertising interval for
                                                  undirected and low duty cycle directed advertising.
                                                  Range: 0x0020 to 0x4000 Default: N = 0x0800 (1.28 second)
                                                  Time = N * 0.625 msec Time Range: 20 ms to 10.24 sec */
    uint16_t                adv_int_max;        /*!< Maximum advertising interval for
                                                  undirected and low duty cycle directed advertising.
                                                  Range: 0x0020 to 0x4000 Default: N = 0x0800 (1.28 second)
                                                  Time = N * 0.625 msec Time Range: 20 ms to 10.24 sec Advertising max interval */
    esp_ble_adv_type_t      adv_type;           /*!< Advertising type */
    esp_ble_addr_type_t     own_addr_type;      /*!< Owner bluetooth device address type */
    esp_bd_addr_t           peer_addr;          /*!< Peer device bluetooth device address */
    esp_ble_addr_type_t     peer_addr_type;     /*!< Peer device bluetooth device address type, only support public address type and random address type */
    esp_ble_adv_channel_t   channel_map;        /*!< Advertising channel map */
    esp_ble_adv_filter_t    adv_filter_policy;  /*!< Advertising filter policy */
} esp_ble_adv_params_t;
```

If you want to fix channel 37, you need to set this value to 0x1.

<img width="799" alt="image" src="https://user-images.githubusercontent.com/26754847/227696610-629d9432-a875-49fe-bb6d-d98476b08faa.png">

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, feel free to reopen.
