### ISSUE TITLE
ESP32-H2 support status (IDFGH-9697)

### ISSUE THREAD

**Issue by igrr** [espressif/esp-idf#11038]
# ESP32-H2 support status in ESP-IDF

ESP-IDF v5.1, currently in development, will include initial support for the mass production version of the ESP32-H2 chip.

In the list below, supported features are marked with a checked checkbox, unsupported features have an unchecked checkbox. An internal issue reference (such as "IDF-1234") is listed at the end of the feature description to help us keep this list up to date:

- [ ] Unsupported feature (IDF-1234)
- [X] Supported feature

This list will be updated as the support for ESP32-H2 is being developed.

## Reporting issues about ESP32-H2

If you have an issue to report about any of the ESP32-H2 features, please create a separate issue. This issue is only intended for announcements of ESP32-H2 support status.

## Support for ESP32-H2 engineering sample revisions

In the past, Espressif has distributed a limited number of engineering samples of ESP32-H2 chip: ESP32-H2-beta1 and ESP32-H2-beta2. Preview support for these chip revisions is available in release/v5.0 branch.

These engineering sample revisions of the chip will *not* be supported in IDF v5.1. Likewise, support for the mass production version of ESP32-H2 will only be available in IDF v5.1 and later. It will not be backported to IDF v5.0.x.

---

### 802.15.4
- [X] 802.15.4 Mac
- [X] 802.15.4 CSL
### Thread
- [X] Thread FTD/MTD
- [X] Thread RCP
### Zigbee
- [X] Zigbee 3.0 Home Automation
- [X] Zigbee RCP
### Coexistence
- [X] Coexistence of Bluetooth LE and 802.15.4
- [ ] Coexist API IRAM timing optimization (TZ-82)
- [X] 802.15.4 & BT Coexistence Scheme
- [X] 802.15.4 External Coexistence
### Bluetooth LE
- [X] Bluetooth 5 Controller (Bluetooth 5.3 Certified)
- [X] Bluedroid Host
- [X] NimBLE Host
- [X] ESP-BLE-MESH
- [X] BLE Modem Sleep and Light Sleep
- [X] Bluetooth Power Control
- [X] HCI - Supported
### Peripherals
- ADC
  - [X] ADC Calibration
  - [X] ADC continuous mode driver
  - [X] ADC oneshot mode driver
- [X] Dedicated GPIO driver
- Ethernet driver
  - [x] SPI Ethernet driver
- [X] Event Task Matrix
- [X] GDMA
- [X] GPIO driver
  - [X] Analog Comparator
  - [X] Glitch Filter
  - [X] Hysteresis
- [X] GPIO sigma delta driver
- GPSPI
  - [X] SPI Master driver
  - [X] SPI Slave HD driver
  - [X] SPI Slave driver
- [X] GPTimer driver
- I2C
  - [X] I2C master driver
  - [X] I2C slave driver
- [X] I2S driver
  - I2S PDM rx mode
  - I2S PDM tx mode
  - I2S STD mode
  - I2S TDM mode
- [X] LCD driver
  - I2C LCD driver
  - SPI LCD driver
- [X] LEDC driver
  - [X] Gamma Curve Generation
- [X] MCPWM driver
- [X] PCNT driver
- Parallel IO
  - [ ] Parallel IO RX Driver (IDF-7038)
  - [X] Parallel IO TX Driver
- [X] RMT driver
- SD/SDIO/MMC driver
  - [X] SDSPI Host driver
- [X] SPI Flash driver
- Systimer driver
  - [X] Esptimer implementation over systimer
  - [X] OS tick port over systimer
- [X] TWAI driver
- [X] Temperature Sensor driver
- UART
  - [X] UART FIFO mode driver
  - [ ] UHCI (UART DMA mode) driver (IDF-6248)
- [X] USB Serial JTAG
- [X] memory copy by DMA
### Power management
- [X] Auto Light Sleep
- [X] Deep Sleep
- [X] Dynamic Frequency Switch
- [X] Light Sleep
### Security Features
- [X] AES accelerator
- [X] Digital Signature driver
- [X] ECC accelerator
- [X] ECDSA driver
- [X] Flash encryption
- [X] HMAC driver
- [X] Permission Control
- [X] RNG
- [X] RSA hardware accelerator driver
- [X] SHA accelerator
- [X] Secure boot
- Trusted Execution Environment
  - [X] Access Permission Management
  - [X] TEE Controller
### System Features
- [X] Brownout Detector
- Cache
  - [X] Cache Driver
- [X] Efuse controller driver
- Heap
- [X] MMU
- MSPI
  - [ ] MSPI tuning (Flash & PSRAM DDR and/or over 80 MHz) (IDF-6256)
  - [X] SPI Flash auto suspend
- Panic Handling Features
  - [ ] Bus Access Timeout Protection (IDF-6250)
  - [x] Core Dump
  - [x] GDB Stub
  - [X] Panic Handler
- [X] Watch Dog Timers

*Note: Nested features can be considered as supported, if the parent feature is shown as "Supported", and it's not explicitly mentioned as "Not supported".*

**Comment by igrr** [comment]
Zigbee features are now supported on ESP32-H2.

**Comment by hipal31** [comment]
`A fatal error occurred: This chip is ESP32-H2(beta2) not ESP32-H2. Wrong --chip argument?`
@igrr 
Which branch should I use for ESP32-H2(beta2)?

**Comment by igrr** [comment]
GDB Stub, Core Dump, SPI Ethernet support has been added.

**Comment by shinasys** [comment]
Does this provide APIs for not only the Zigbee 3.0 stack but also the 802.15.4 MAC? Or is there a plan to provide such APIs?
The reason is that I wanted it to be compatible with the 802.15.4 MAC device I developed in the past.

**Comment by lygstate** [comment]
Does ESP32-H2 support for PSRAM DDR?

**Comment by andylinpersonal** [comment]
Or at least any native support for memory-mapped read/write to external SPI PSRAM.

**Comment by jack0c** [comment]
updated:
- [X] Auto Light Sleep
- [X] Deep Sleep
- [X] Dynamic Frequency Switch
- [X] Light Sleep

**Comment by tom-borcin** [comment]
Update 2024/01/17:
- 802.15.4 & BT Coexistence Scheme is Done
- 802.15.4 External Coexistence is Done
- BLE Modem Sleep and Light Sleep is Done
- Bluetooth Power Control is Done
- ADC Calibration is Done
- SPI Flash auto suspend is Done

Only remaining items are:
- Coexist API IRAM timing optimization
- Parallel IO RX Driver
- UHCI (UART DMA mode) 
- MSPI tuning (Flash & PSRAM DDR and/or over 80 MHz)
- Bus Access Timeout Protection

These remaining items will be supported based on customer requests. We are closing the issue and unpinning it. Please open new issue if you have a feature request, question or any other problem.
