### ISSUE TITLE
Ask for passkey straight after connection (NimBLE) (IDFGH-9695)

### ISSUE THREAD

**Issue by rbruneau-altyor** [espressif/esp-idf#11036]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Hello, 

I have been using the **bleprph** example from ESP-IDF v4.3.3 and something is disturbing me when it comes to passkey usage:

If I set IO capability of my device to BLE_HS_IO_DISPLAY_ONLY, I am able to use a passkey to pair and bond with the ESP32 from NRF Connect. The problem is, the BLE_GAP_EVENT_PASSKEY_ACTION event only starts when I try to access an encrypted characteristic (one with the BLE_GATT_CHR_F_WRITE_ENC or BLE_GATT_CHR_F_READ_ENC flag. 
If I just stay connected but do not ask to access a characteristic, I can stay connected as long as I want without being asked to enter the passkey.

Is there a way to cleanly start BLE_GAP_EVENT_PASSKEY_ACTION straight after connecting to the BLE device ?

Thank you for your help

**Comment by rahult-github** [comment]
Existing example shows a demo that if gatt read / write is performed on a characteristic that needs link encryption , then it will ensure link is encrypted , for which pairing is to be performed .


If you want to force pairing after connection , you can call the ble_gap_security_initiate( conn handle ) after the connect event is received in the gap callback. This will initiate pairing procedure.  Ensure link is not encrypted already or linkkey was not stored earlier. In such case it should result in pairing.

**Comment by rbruneau-altyor** [comment]
Thank you for your answer @rahult-github. Could you tell me where to put the **ble_sm_inject_io()** function to set up the passkey I want to use? I am a bit confused as the **ble_gap_security_initiate(conn handle)** function only notifies me that the pairing is require, but does not actually set up the the secure key to proceed such connection...

**Comment by rbruneau-altyor** [comment]
Well actually it does trigger BLE_GAP_EVENT_PASSKEY_ACTION event after calling **ble_gap_security_initiate()**, but I get 2 notifications on my phone: 
- the first one only asks me if I want to accept/reject the connection, then triggers the BLE_GAP_EVENT_PASSKEY_ACTION  event if I accept
- the second one does actually ask me to enter the passkey, which is what I wanted

Is it possible to get only the passkey notification straightaway after connecting?

**Comment by rbruneau-altyor** [comment]
Indeed, the behavior is the same using another phone: I get 2 connection notifications, one with and one without passkey entry. 

Here are the logs I get whileexecuting the firmware (advertising is triggered by pushing a button):

`I (2093) system_api: Base MAC address is not set
I (2093) system_api: read default base MAC address from EFUSE
I (2093) BT_INIT: Bluetooth MAC: dc:54:75:c2:34:4e

I (2103) NimBLE: registered service 0x1800 with handle=1

I (2113) NimBLE: registering characteristic 0x2a00 with def_handle=2 val_handle=3

I (2123) NimBLE: registering characteristic 0x2a01 with def_handle=4 val_handle=5

I (2133) NimBLE: registered service 0x1801 with handle=6

I (2133) NimBLE: registering characteristic 0x2a05 with def_handle=7 val_handle=8

I (2143) NimBLE: registered service 0x180a with handle=10

I (2153) NimBLE: registering characteristic 0x2a29 with def_handle=11 val_handle=12

I (2153) NimBLE: registering characteristic 0x2a24 with def_handle=13 val_handle=14

I (2163) NimBLE: registered service 09c64988-69ab-11ed-a1eb-0242ac120002 with handle=15

I (2173) NimBLE: registering characteristic 29c64988-69ab-11ed-a1eb-0242ac120002 with def_handle=16 val_handle=17

I (2183) NimBLE: registering characteristic 19c64988-69ab-11ed-a1eb-0242ac120002 with def_handle=19 val_handle=20

I (2193) NimBLE: registered service 49d90650-69ab-11ed-a1eb-0242ac120002 with handle=21

I (2203) NimBLE: registering characteristic 59d90650-69ab-11ed-a1eb-0242ac120002 with def_handle=22 val_handle=23

I (2213) NimBLE: registering characteristic 69d90650-69ab-11ed-a1eb-0242ac120002 with def_handle=25 val_handle=26

I (2223) NimBLE: registered service 8b99b1ec-69a7-11ed-a1eb-0242ac120002 with handle=27

I (2233) NimBLE: registering characteristic 9b99b1ec-69a7-11ed-a1eb-0242ac120002 with def_handle=28 val_handle=29

I (2243) NimBLE: registering characteristic ab99b1ec-69a7-11ed-a1eb-0242ac120002 with def_handle=31 val_handle=32

I (2263) NimBLE: GAP procedure initiated: stop advertising.

I (2263) NimBLE: Device Address: 
I (2273) NimBLE: dc:54:75:c2:34:4e
I (2273) NimBLE: 

**Advertising button pressed**

I (14773) BLE_HNDL: Start advertising
I (14773) NimBLE: GAP procedure initiated: advertise; 
I (14773) NimBLE: disc_mode=2
I (14773) NimBLE:  adv_channel_map=0 own_addr_type=0 adv_filter_policy=0 adv_itvl_min=0 adv_itvl_max=0
I (14783) NimBLE: 

I (20873) NimBLE: connection established; status=0

I (20873) NimBLE: GAP procedure initiated: stop advertising.

I (20883) NimBLE: GAP procedure initiated: stop advertising.

I (21493) NimBLE: connection updated; status=0 
I (21493) NimBLE: handle=1 our_ota_addr_type=0 our_ota_addr=
I (21493) NimBLE: dc:54:75:c2:34:4e
I (21493) NimBLE:  our_id_addr_type=0 our_id_addr=
I (21503) NimBLE: dc:54:75:c2:34:4e
I (21503) NimBLE:  peer_ota_addr_type=1 peer_ota_addr=
I (21513) NimBLE: 5d:e4:d0:88:20:f8
I (21513) NimBLE:  peer_id_addr_type=1 peer_id_addr=
I (21523) NimBLE: 5d:e4:d0:88:20:f8
I (21523) NimBLE:  conn_itvl=6 conn_latency=0 supervision_timeout=500 encrypted=0 authenticated=0 bonded=0

I (21533) NimBLE: 

W (21743) APP_PBI: Communication timeout occured!
I (22023) NimBLE: connection updated; status=0 
I (22023) NimBLE: handle=1 our_ota_addr_type=0 our_ota_addr=
I (22023) NimBLE: dc:54:75:c2:34:4e
I (22033) NimBLE:  our_id_addr_type=0 our_id_addr=
I (22033) NimBLE: dc:54:75:c2:34:4e
I (22043) NimBLE:  peer_ota_addr_type=1 peer_ota_addr=
I (22043) NimBLE: 5d:e4:d0:88:20:f8
I (22053) NimBLE:  peer_id_addr_type=1 peer_id_addr=
I (22053) NimBLE: 5d:e4:d0:88:20:f8
I (22063) NimBLE:  conn_itvl=36 conn_latency=0 supervision_timeout=500 encrypted=0 authenticated=0 bonded=0

I (22073) NimBLE: 

I (27033) BLE_GAP: PASSKEY_ACTION_EVENT started 

I (27033) BLE_GAP: Enter passkey 123456 on the peer side
I (27033) BLE_GAP: ble_sm_inject_io result: 0

I (39123) NimBLE: encryption change event; status=0 
I (39123) NimBLE: handle=1 our_ota_addr_type=0 our_ota_addr=
I (39123) NimBLE: dc:54:75:c2:34:4e
I (39133) NimBLE:  our_id_addr_type=0 our_id_addr=
I (39133) NimBLE: dc:54:75:c2:34:4e
I (39143) NimBLE:  peer_ota_addr_type=1 peer_ota_addr=
I (39143) NimBLE: 5d:e4:d0:88:20:f8
I (39153) NimBLE:  peer_id_addr_type=1 peer_id_addr=
I (39153) NimBLE: 5d:e4:d0:88:20:f8
I (39163) NimBLE:  conn_itvl=36 conn_latency=0 supervision_timeout=500 encrypted=1 authenticated=1 bonded=1

I (39173) NimBLE: 

I (39713) NimBLE: subscribe event; cur_notify=0
 value handle; val_handle=8

I (39713) BLE_GAP_SUBSCRIBE_EVENT: conn_handle from subscribe=1`

Accepting connection with first notification on phone triggers the PASSKEY_ACTION_EVENT

**Comment by rahult-github** [comment]
Hi @rbruneau-altyor  ,

 I misunderstood your statement initially. This is normal behaviour, where phones ask if pairing should be allowed and once user says yes, the phone, based on the IO capability will then either ask user to enter key OR display pin code OR give a yes/no kind of pop-up for authentication.

**Comment by rbruneau-altyor** [comment]
Alright, thank you @rahult-github, I will close the issue
