### ISSUE TITLE
[mesh] v4.4 disconnecting with multiple non-mapped errors (IDFGH-9705)

### ISSUE THREAD

**Issue by KonssnoK** [espressif/esp-idf#11042]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Hello,
we have devices that are disconnecting from the mesh for hours. When they connect back (if they don't reset) they report the following errors seen during offline period:

<MESH_EVENT_PARENT_DISCONNECTED>reason: 101 ERROR
<MESH_EVENT_PARENT_DISCONNECTED>reason: 105 ERROR

I tried to find these errors in the components but without success.
Any help? Why do they occur? Why does the device not connect back for hours?

Were these errors touched in the library of https://github.com/espressif/esp-idf/issues/9955 ?

We also see a lot of the followings:

<MESH_EVENT_PARENT_DISCONNECTED>reason: 2 WIFI_REASON_AUTH_EXPIR
<MESH_EVENT_PARENT_DISCONNECTED>reason: 15 WIFI_REASON_4WAY_HANDSHAKE_TIMEOUT

thanks

**Comment by zhangyanjiaoesp** [comment]
@KonssnoK 
`<MESH_EVENT_PARENT_DISCONNECTED>reason: 101` represents parent is idle.
`<MESH_EVENT_PARENT_DISCONNECTED>reason: 105` represents parent is stopped.
These errors wasn't touched in the library of https://github.com/espressif/esp-idf/issues/9955 .

**Comment by KonssnoK** [comment]
> @KonssnoK `<MESH_EVENT_PARENT_DISCONNECTED>reason: 101` represents parent is idle. `<MESH_EVENT_PARENT_DISCONNECTED>reason: 105` represents parent is stopped. These errors wasn't touched in the library of #9955 .

Thanks,
could they be added to the list of MESH errors?
what can we do when they happen?

Consider that what we currently see is that sometimes devices go offline and remain offline for hours.
This is mainly triggered when we do a firmware update, so it might improve with new library and heap fix, but sometimes it happens also on untouched devices (which may still be related to using the old library).

To workaround this we implemented a one hour watchdog on the MESH_EVENT_PARENT_DISCONNECTED event.
But it's clear that it's not a solution (especially if it's the root that is idle or stopped 🤔 )

Here an example:
![image](https://user-images.githubusercontent.com/10288926/227439928-98e68e69-cdae-4b4f-b8e3-4ee4e4c9a907.png)

**Comment by KonssnoK** [comment]
@zhangyanjiaoesp could you please give me also these codes:

```
<MESH_EVENT_PARENT_DISCONNECTED>reason: 106 ERROR
<MESH_EVENT_PARENT_DISCONNECTED>reason: 32 ERROR
```
and all the missing ones?

yesterday we had our first LTE handover and only 5 out of 9 devices were able to join the fixed mesh network.
We'll work on our reporting in order to understand what is going on.

**Comment by zhangyanjiaoesp** [comment]
@KonssnoK the mesh parent disconnect reason code is here
https://github.com/espressif/esp-idf/blob/9b4ccdc911039383b69ebb41322d13353ed493a5/components/esp_wifi/include/esp_mesh.h#L264

**Comment by KonssnoK** [comment]
aha, thanks
