### ISSUE TITLE
Get RSA public key from DS peripheral (IDFGH-9710)

### ISSUE THREAD

**Issue by tadejg** [espressif/esp-idf#11047]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

How can I get the public key of the RSA private key used by the digital signature peripheral? I would like to be able to verify the signature made by the DS peripheral.
I'm using the ESP32C3 with ESP-IDF v.5.0.1.

**Comment by chipweinberger** [comment]
afaik, you can't.

You need to store the public key elsewhere, yourself. The DS peripheral only uses/needs the private key.

**Comment by mahavirj** [comment]
@tadejg 

DS Peripheral only supports the signing operation, please see its API reference [here]( https://docs.espressif.com/projects/esp-idf/en/latest/esp32s2/api-reference/peripherals/ds.html).

Please follow the [esp_secure_cert_app](https://github.com/espressif/esp_secure_cert_mgr/tree/main/examples/esp_secure_cert_app) example and especially this [part](https://github.com/espressif/esp_secure_cert_mgr/blob/1fed2bf855e66dac9c47fdf65bc566e6e259d58f/examples/esp_secure_cert_app/main/app_main.c#L32-L80) to understand the verification related workflow (done in software).
