### ISSUE TITLE
ESP32 eFuses - fileds in BLK3 in the custom efuse table intersect with the common table (IDFGH-9715)

### ISSUE THREAD

**Issue by mgagic** [espressif/esp-idf#11051]
ESP-IDF v4.4
ESP32

I want to use BLK3 eFuses in a custom efuse table, but they overlap with MAC_CUSTOM* and ADC* fields from the common esp_efuse_table.csv.
The same issue was dealt with [here](https://github.com/espressif/esp-idf/issues/8810), but for ESP32-S3, which has a different esp_efuse_table.

Is there a way to define custom eFuses in the entire BLK3 without changing the common esp_efuse_table.csv?
Adding unrelated values as structured fields in one of the existing ones seems messy, and it's not suitable if the number of bits is larger.

I guess one way of doing it would be to use burn_bit and read the whole register, but that's not ideal and I hope there's a cleaner solution.

**Comment by chipweinberger** [comment]
AFAICT, your only option is to do things like this:

```
MAC_CUSTOM_CRC.JSERIAL_NUMBER,                   EFUSE_BLK3,    0,  4,   
MAC_CUSTOM_CRC.JMODEL_NUMBER,                   EFUSE_BLK3,    4,  4,  
MAC_CUSTOM.JHARDWARE_REV_MAJ,                    EFUSE_BLK3,    8, 6,  
MAC_CUSTOM.JHARDWARE_REV_MIN,                     EFUSE_BLK3,    14, 6,  
```

I agree it's messy and limiting. Changing the [common table](https://github.com/espressif/esp-idf/blob/master/components/efuse/esp32/esp_efuse_table.csv) is probably your best option.

**Comment by mgagic** [comment]
Hi @chipweinberger @KonstantinKondrashov thanks for your help.

In the end, it seems like I can fit the necessary info in the available bits between the already defined fields so I defined the new fields in a custom csv.

@KonstantinKondrashov  I have done 3) and I have the .c and .h files with my newly defined fields. Now my question is - how do I burn these?

In the efuse_custom_table.csv (dummy values just for the example):
`MY_FUSE_NAME,             EFUSE_BLK3,         56,         32,           My custom efuse`

and the for burning, I tried
`espefuse.py --port /dev/ttyUSB0 burn_efuse MY_FUSE_NAME  42`
but I get the error

```
A fatal error occurred: Invalid the efuse name 'MY_FUSE_NAME'. Available the efuse names: ['WR_DIS', 'RD_DIS', 'CODING_SCHEME', 'KEY_STATUS', 'MAC', 'MAC_CRC', 'CHIP_VER_REV1', 'CHIP_VER_REV2',
'WAFER_VERSION_MINOR', 'CHIP_PACKAGE', 'CHIP_PACKAGE_4BIT', 'XPD_SDIO_FORCE', 'XPD_SDIO_REG',
'XPD_SDIO_TIEH', 'CLK8M_FREQ', 'SPI_PAD_CONFIG_CLK', 'SPI_PAD_CONFIG_Q', 'SPI_PAD_CONFIG_D',
'SPI_PAD_CONFIG_HD', 'SPI_PAD_CONFIG_CS0', 'DISABLE_SDIO_HOST', 'FLASH_CRYPT_CNT',
'UART_DOWNLOAD_DIS', 'FLASH_CRYPT_CONFIG', 'CONSOLE_DEBUG_DISABLE', 'ABS_DONE_0', 'ABS_DONE_1',
'JTAG_DISABLE', 'DISABLE_DL_ENCRYPT', 'DISABLE_DL_DECRYPT', 'DISABLE_DL_CACHE', 'BLK3_PART_RESERVE',
'ADC_VREF', 'MAC_VERSION', 'BLOCK1', 'BLOCK2', 'BLOCK3', 'WAFER_VERSION_MAJOR', 'PKG_VERSION']
espefuse.py v4.5.1
```

Have I missed a step or should I use something else for the burning? I'd like to avoid using burn_bit as the value will be 32b and I also need to do it outside of the firmware itself (not calling something like esp_efuse_write_field_blob) since I would like to have a "production" script that will flash the firmware and burn the efuses.

**Comment by KonstantinKondrashov** [comment]
@mgagic! All of these points are related to IDF and do not affect espefuse.py.  You can use esp_efuse_write... APIs from IDF to burn them.

Regarding  `espefuse.py burn_efuse MY_FUSE_NAME  42`. The tool can not use customer efuse fields. The custom csv file from IDF is not passed to espefuse.py.
I am thinking about a new feature for the espefuse tool. It will be able to take a custom efuse csv or yaml file to extend the efuses.

But for now, if you have **constant data per chip** then you can take the entire efuse block (read back and save) and then burn the efuse block with cmd:
- espefuse.py dump --file_name backup/blk3.bin 
   (https://docs.espressif.com/projects/esptool/en/latest/esp32/espefuse/dump-cmd.html#save-dump-to-files)
- espefuse.py -p PORT burn_block_data BLOCK3 backup/blk3.bin (https://docs.espressif.com/projects/esptool/en/latest/esp32/espefuse/burn-block-data-cmd.html#burn-block-data)

The only way that I can suggest for now.

**Comment by j4m3s** [comment]
> I am thinking about a new feature for the espefuse tool. It will be able to take a custom efuse csv or yaml file to extend the efuses. But this work is not done yet.

I'd be very interested in that enhancement too @KonstantinKondrashov.  Would you be able to post something on this ticket thread if you implement it?  It would be super-helpful and would significantly reduce the chance of errors that are quite likely when using `burn_bit`.  The `efuse_table_gen.py` tool makes a massive difference in minimising errors in reading from the efuses.

**Comment by mgagic** [comment]
Until that is available, maybe somebody finds this useful. In my case, the info in efuses consisted of two values (32b and 16b) so writing them using burn_bit would be unrealistic especially because we needed a user-friendly script that could be called with the arguments in decimal representation.

My custom table had this defined (fits inside the already defined efuses so there was no need to change the common table):
```
ART_NUMBER,             EFUSE_BLK3,         56,         32,         Article number
HW_REVISION,            EFUSE_BLK3,         160,        16,         Hardware revision
```
After playing around with the efuses in the virtual environment by calling efuses API from the firmware and checking how the values would be written (_note for the espressif people_ - documentation on this is quite confusing and could be improved with better clarification and examples), I created a python script that takes the decimal values that need to be burned, creates a binary file and then uses that to burn the efuses with burn_block_data, as KonstantinKondrashov suggested.

Please note that the following is cut out of a larger script so **test for your specific case before burning any fuses for real**. I'm not claiming that it would work for your specific use-case.

```
OUTPUT_FILE_NAME_BASE   = "efuses_"
BITS_TO_BYTES           = 8
# following values are defined in efuses_custom_table.csv
# the file could be parsed to find out the values instead of hardcoding them here
ART_NUMBER_START_BIT    = 56
ART_NUMBER_LEN_BITS     = 32
HW_REVISION_START_BIT   = 160
HW_REVISION_LEN_BITS    = 16


def create_efuses_bin(art_number, hw_rev_num):
    efuses_data = bytearray(32)

    # Calculate the starting byte-index to insert the number
    # The number should be inserted at defined bits (left to right)
    # adding (<>_LEN_BITS // BITS_TO_BYTES - 1) to start from the last position
    # and write the bytes in reverse
    start_index_artnum = ART_NUMBER_START_BIT // BITS_TO_BYTES + (ART_NUMBER_LEN_BITS / BITS_TO_BYTES - 1)
    start_index_hwrev = HW_REVISION_START_BIT // BITS_TO_BYTES + (HW_REVISION_LEN_BITS / BITS_TO_BYTES - 1)

    # Convert the article number to bytes in little-endian format
    bytes_art_num = art_number.to_bytes(ART_NUMBER_LEN_BITS / BITS_TO_BYTES, byteorder='little')

    # Insert the bytes of the number in reverse order starting from bit ART_NUMBER_START_BIT
    for i, b in enumerate(bytes_art_num[::-1]):
        efuses_data[start_index_artnum - i] = b

    # Convert the hw revision number to bytes in little-endian format
    bytes_hw_rev_num = hw_rev_num.to_bytes(HW_REVISION_LEN_BITS / BITS_TO_BYTES, byteorder='little')

    # Insert the bytes of the number in reverse order starting from bit 56
    for i, b in enumerate(bytes_hw_rev_num[::-1]):
        efuses_data[start_index_hwrev - i] = b

    # Write the byte array to a binary file
    output_file = OUTPUT_FILE_NAME_BASE + str(art_number) + '_' + str(hw_rev_num) + '.bin'
    with open(output_file, "wb") as f:
        f.write(efuses_data)

    return output_file

# create the efuses binary
efuses_bin = create_efuses_bin(art_number, hw_rev_num)    
# for burning, it would be called like this
subprocess.run("espefuse.py --port /dev/ttyUSB0 burn_block_data BLOCK3 " +  os.path.abspath(efuses_bin), shell=True)

```

as an example, I had to write numbers 539670 (article number) and 676 (hw revision) and when I virtually burned those using efuses API
```
#ifdef CONFIG_EFUSE_VIRTUAL
    g_device_desc.article_number = 539670; // 0x00083c16
    g_device_desc.hw_revision = 676; // 0x2a4
    write_efuse_fields(&g_device_desc);
    const unsigned blk_len_bit = 256;
    uint8_t key[32];
    esp_err_t err = esp_efuse_read_block(EFUSE_BLK3, &key, 0, blk_len_bit);
    ESP_LOG_BUFFER_HEXDUMP("EFUSES_TEST", key, sizeof(key), ESP_LOG_INFO);
#endif
```
the resulting block3 looked like this
EFUSES_TEST: (0x3ffc0370)  00 00 00 00 00 00 00 16 3c 08 00 00 00 00 00 00 00 00 00 00 a4 02 00 00 00 00 00 00 00 00 00 00

which is the same content generated by the script above and written to the binary file
![image](https://user-images.githubusercontent.com/97739167/232401776-971ddb0b-885e-45c7-83cc-0d3efb11abbe.png)

**Comment by j4m3s** [comment]
Thanks for sharing @mgagic!
