### ISSUE TITLE
ESP32s2 ULP-RISCV ADC in deep sleep the variable is loosing its value after ULP-RISCV sleep (IDFGH-9716)

### ISSUE THREAD

**Issue by naelNajjar** [espressif/esp-idf#11052]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

I am working on a project in which I am using ESP32s2.
The ULP_RISCV is utilized to read ADC data from the light sensor during deep sleep as shown here in ulp_main.c file.

        raw_data = ulp_riscv_adc_read_channel(ADC_UNIT_1, ADC_CHANNEL_1);
	/*if the new light_sensor value is greater than threshold A or lower than threshold B*/
	if((500 > raw_data) || (2000 < raw_data))
	{
		/* set the prev_light_data to the previous reading */
		prev_light_data = light_data;
		light_data = raw_data ;
	}
	
then we compare prev_light_data and light_data with specific threshold to decide whether to rise waking_flag or not.
The ULP will wake the main CPU when light sensor data exceeds a specific threshold.

	if((waking_flag == 1))
	{
		ulp_riscv_wakeup_main_processor();
	}
Also, the ULP is working with the ULP timer.
here is the initiate of ulp in main.c file

```
ulp_riscv_adc_cfg_t cfg = {
			.adc_n = ADC_UNIT_1,
			.channel = ADC_CHANNEL_1,
			.width = ADC_BITWIDTH_DEFAULT,
			.atten = ADC_ATTEN_DB_11,
	};
	ESP_ERROR_CHECK(ulp_riscv_adc_init(&cfg));
	 esp_err_t err = ulp_riscv_load_binary(ulp_main_bin_start, (ulp_main_bin_end - ulp_main_bin_start));
	 ESP_ERROR_CHECK(err);

	 ulp_set_wakeup_period(0, 20000);

	 err = ulp_riscv_run();
	 ESP_ERROR_CHECK(err);
```
The problem is when ULP finishes executing its code and goes to sleep (waiting for its next wake-up from the ULP-Timer), all ULP's global variables are re-initialized with different values than before sleeping.
![image](https://user-images.githubusercontent.com/116096235/227611412-4e611584-ea3f-44cc-8afe-1b94470d8012.png)

So, how can I save the contents of ULP global variables so that when ULP goes to sleep and then wakes up (from the ULP-Timer) its global variables don't lose the contents/values that they were holding before sleep?

**Comment by ESP-Marius** [comment]
Hi,

All variables used by the ULP is placed in RTC memory and should keep their value even during sleep. I suspect your issue is actually related to something else.

There is an in-progress issue internally for a known problem with S2 ULP ADC in deep sleep related to some power configurations (it gives the wrong results when reading). I'll remind them that we still have users asking for support with this...
