### ISSUE TITLE
esp-mqtt folder is empty in V5.0, V5.1, and master brances. (IDFGH-9735)

### ISSUE THREAD

**Issue by ksanger3838** [espressif/esp-idf#11069]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

esp-idf-release-v5.0.zip esp-idf-release-v5.1.zip esp-idf-master.zip

### Operating System used.

Linux

### How did you build your project?

Other (please specify in More Information)

### If you are using Windows, please specify command line type.

None

### What is the expected behavior?

sourcing export.sh in the target folder, then running idf.py set-target esp32 I expect the target to be set.   running idf.py menuconfig we expect to get a menu to appear.

### What is the actual behavior?

In master and V5.1 branches we get an error that /home/me/esp-idf-release-v5.1/components/msqtt/esp-msqtt MakeLists.txt is not found.   For V5.0, V5.1, and Master branches the zip file does not contain any files here.

In V5.0 running idf.py menuconfig or idf.py set-target esp32  we get /home/me/esp-idf-release-v5.0/components/mbedtls/mbedtls/include is not a directory.

### Steps to reproduce.

1.  Download Master, V5.1, or V5.0 zip file.
2.  Exract files to home directory
3. change to esp-idf-xxx folder
4. execute ./install.sh
5. cd to workspace folder 
6. execute the command source /home/me/esp-idf-xxx/export.sh
7. execute idf.py set-target esp32  or the command idf.py menuconfig
8. crash and burn.

### Build or installation Logs.

```plain
For V5.0 we get...

more idf_py_stderr_output_13151 
fatal: not a git repository (or any of the parent directories): .git
CMake Error at /home/kurt/esp-idf-release-v5.0/tools/cmake/component.cmake:312 (message):
  Include directory
  '/home/kurt/esp-idf-release-v5.0/components/mbedtls/mbedtls/include' is not
  a directory.
Call Stack (most recent call first):
  /home/kurt/esp-idf-release-v5.0/tools/cmake/component.cmake:486 (__component_add_include_dirs)
  /home/kurt/esp-idf-release-v5.0/components/mbedtls/CMakeLists.txt:18 (idf_component_register)

more idf_py_stdout_output_13151 
-- Found Git: /usr/bin/git (found version "2.34.1") 
-- Component directory /home/kurt/Workspace/esp32/pthread/components/components does not contain a CMakeLists.txt file. No component will be added
-- The C compiler identification is GNU 11.2.0
-- The CXX compiler identification is GNU 11.2.0
-- The ASM compiler identification is GNU
-- Found assembler: /home/kurt/.espressif/tools/xtensa-esp32-elf/esp-2022r1-11.2.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /home/kurt/.espressif/tools/xtensa-esp32-elf/esp-2022r1-11.2.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /home/kurt/.espressif/tools/xtensa-esp32-elf/esp-2022r1-11.2.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Project is not inside a git repository, or git repository has no commits; will not use 'git describe' to determine PROJECT_VER.
-- Building ESP-IDF components for target esp32
-- Project sdkconfig file /home/kurt/Workspace/esp32/pthread/sdkconfig
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of time_t
-- Check size of time_t - done
-- Configuring incomplete, errors occurred!
See also "/home/kurt/Workspace/esp32/pthread/build/CMakeFiles/CMakeOutput.log".
kurt@pop-os:~/Workspace/esp32/pthread/build/log$
```

### More Information.

V4 was working on linux.   Updated as I wanted my portable  Win 10 and heavy Linux laptops to be at the same level so that I could code outside of the home.   Also I'm using the CXX examples and was thinking that V5 may be more up to date with c++.

**Comment by igrr** [comment]
@ksanger3838 How have you downloaded ESP-IDF? If you have used the "download the .zip archive" feature on Github, it won't work because the project uses Git submodules. Github doesn't include the content of Git submodules when downloading the .zip archive of the repository.

Please try t follow the getting started instructions found here: https://docs.espressif.com/projects/esp-idf/en/latest/esp32/get-started/linux-macos-setup.html to install IDF.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to short of feedback, feel free to reopen with more updates.
