### ISSUE TITLE
May I ask which channel estimation algorithm is used by ESP32-WROOM-32U to obtain channel state information(CSI)？ (IDFGH-9734)

### ISSUE THREAD

**Issue by ogleede** [espressif/esp-idf#11068]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

May I ask which channel estimation algorithm is used by ESP32-WROOM-32U to obtain channel state information(CSI)？

**Comment by CC-MASTER05** [comment]
Please refer https://www.esp32.com/viewtopic.php?t=9733

**Comment by ogleede** [comment]
> Please refer https://www.esp32.com/viewtopic.php?t=9733

thank you！Sorry I didn't explain my problem clearly. What I want to ask is, what algorithm is used for channel measurement, LS or MMSE?

**Comment by MaxwellAlan** [comment]
Hi @ogleede 

We use LS :)

**Comment by Sherry616** [comment]
Thanks for reporting, we will close this issue. Feel free to reopen if have more updates. 
Thanks for using our Espressif product!
