### ISSUE TITLE
How to initialize a FAT partition in SPIFFS partition table slot  (IDFGH-9743)

### ISSUE THREAD

**Issue by yaswanth-17** [espressif/esp-idf#11076]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v4.4.1

### Operating System used.

Windows

### How did you build your project?

Eclipse IDE

### If you are using Windows, please specify command line type.

NONE

### What is the expected behavior?

Hi everyone i have some doubts about the spiffs and fatfs file storage system. actually, iam using esp32 wrover-b and my binary size has been increased due to the large HTML files , so as i analyzed the partition table there is a lot of empty space in spiffs which I not using in our project so I have implemented spiffs storage system and mount those files to spiffs but unfortunately due to flash encryption I am not able to mount or create spiffs storage, so next way is to create a fatfs storage to access the html page, is it possible to use my spiffs partition for fatfs which I declare in my partition table, is there any way to store the file in fatfs  without modifying the partition table,

Is it possible to use the spiffs partition for fatfs to store files and access files?

### What is the actual behavior?

Need to store the HTML in fatfs without modifying the partition table and by using the existing spiffs storage.

### Steps to reproduce.

Just creating a partition table consisting of spiff storage and assigning it fatfs is possible in espidf if it possible is there any example on it?

**Comment by igrr** [comment]
@yaswanth-17 Are your devices already in the field? Is flash encryption already enabled on these devices? Or are you still in development phase?

If you are in development phase, you can simply update the partition table to use a fatfs partition instead of spiffs.

If the devices are already in the field, how did you use the SPIFFS partition before? Looks like this shouldn't be possible due to flash encryption being enabled.

**Comment by Alvin1Zhang** [comment]
@yaswanth-17 Thanks for reporting, would you please help share if any updates for the issue? Thanks.

**Comment by adokitkat** [comment]
Closing this as there is no answer. Fell free to reopen if you have any more questions.
