### ISSUE TITLE
Android notification service  (IDFGH-9752)

### ISSUE THREAD

**Issue by Saiteja-Vellanki** [espressif/esp-idf#11085]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

How can i program esp32 s3 to notify android sms/call alerts like ancs apple example.
Is there any guidance is there any android app required for that .
Kindly provide me the information.

**Comment by xiewenxiang** [comment]
ANCS is an Apple feature, it doesn't adapt to android.
