### ISSUE TITLE
[TW#15834] ulp_adc current measurment is not correct

### ISSUE THREAD

**Issue by baoshi** [espressif/esp-idf#1108]
In the examples\system\ulp_adc
The claimed current draw @ 10Hz is 80uA
I found it is can be much less at round 39uA (below scope capture from uCurrent, 1mV=1uA)
![ds1104z_ds1za185054406_2017-10-12_09 04 07](https://user-images.githubusercontent.com/2027396/31474284-5259eefa-af2c-11e7-907d-c6ac174369d4.png)
This is possibly because GPIO15 has internal PU enabled but the pin is grounded to suppress boot message.
Add
`rtc_gpio_pullup_dis(GPIO_NUM_15);`
at beginning of the code resolves this issue.

**Comment by igrr** [comment]
Just to clarify, do you get 39uA with or without this extra rtc_gpio_pullup_dis line?

**Comment by baoshi** [comment]
Without rtc_gpio_pullup_dis, with GPIO15 tired to gnd-> 80uA
With rtc_gpio_pullup_dis, without GPIO15 tired to gnd -> 39uA
With/without rtc_gpio_pullup_dis, GPIO15 floating -> 39uA

**Comment by negativekelvin** [comment]
Avg current with spikes probably at least +10ua?
