### ISSUE TITLE
Can Bluetooth pairing skip the scanning process？ (IDFGH-9751)

### ISSUE THREAD

**Issue by jjj19950710** [espressif/esp-idf#11084]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

I don't want to scan the device before every pairing.Can Bluetooth pairing skip the scanning phase and directly hardcode the address and other relevant data obtained through scanning into the program?

**Comment by xiewenxiang** [comment]
If you can ensure that the peer device is broadcast connectable packets, you can initiate a connection request directly.
After the connection is established, initiate pairing again.

**Comment by zhp0406** [comment]
@jjj19950710 
Have you resolved the issue?

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to short of feedback, feel free to reopen.
