### ISSUE TITLE
How can I create a fat image in cmakelists.txt from file (IDFGH-9763)

### ISSUE THREAD

**Issue by waruqi** [espressif/esp-idf#11095]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

I am porting https://github.com/espressif/esp-skainet/blob/master/examples/chinese_tts to my project.

but it use flash_voicedata.sh to flash voice data to partition. 

https://github.com/espressif/esp-skainet/blob/master/examples/chinese_tts/flash_voicedata.sh#L19

I want to use cmake to create and flash it when I run `idy.py flash`

I found fatfs_create_rawflash_image api but it does not support to create partiton from data file. just support base directory.

```
fatfs_create_rawflash_image(<partition> <base_dir> [FLASH_IN_PROJECT])
```

but I want to use 

```
fatfs_create_rawflash_image(voice_data ../esp_tts_voice_data_xiaole.dat FLASH_IN_PROJECT)
```

**Comment by igrr** [comment]
@waruqi Can you explain what you would like to see in the resulting partition? A root directory with that single file? If yes, you can simply move the file into a subdirectory and point fatfs_create_rawflash_image to that subdirectory.
If you want to keep the file where it currently is in your project, simply create that subdirectory at build time somewhere under CMAKE_CURRENT_BINARY_DIR and then copy the file there. Then point fatfs_create_rawflash_image to that generated directory.

**Comment by waruqi** [comment]
I think `esp_tts_voice_data_xiaoxin.dat` should be a whole partition data file, not a file in fs.

because it will be flashed to the given partition directly.

```
python ${IDF_PATH}/components/esptool_py/esptool/esptool.py \
        --port $port --baud $baud --before default_reset --after hard_reset write_flash \
        --flash_mode dio --flash_freq 40m --flash_size detect 0x410000 esp_tts_voice_data_xiaoxin.dat
```

https://github.com/espressif/esp-skainet/blob/master/examples/chinese_tts/esp_tts_voice_data_xiaoxin.dat

**Comment by igrr** [comment]
I see. In that case, looks like there is no FAT filesystem at all, you just need to flash the file to the partition. You can refer to what esp-sr already does with models: https://github.com/espressif/esp-sr/blob/1f3692bbd947bb5a6263929155f0f7264f52b71d/CMakeLists.txt#L115

**Comment by waruqi** [comment]
Thanks!
