### ISSUE TITLE
Error when building blufi example (IDFGH-9762)

### ISSUE THREAD

**Issue by Ether-YiTseWu** [espressif/esp-idf#11096]
### Answers checklist.

- [x] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

 v5.0.1

### Operating System used.

Linux

### How did you build your project?

Command line with idf.py

### If you are using Windows, please specify command line type.

None

### What is the expected behavior?

Build Successfully

### What is the actual behavior?

When the command `idf.py build` is executed, there are several red lines as the following text shows.

_**undefined reference to `mbedtls_dhm_free'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.**_

### Steps to reproduce.

Type the command as the tutorial shows

**Comment by lablabla** [comment]
I had the same issue. 
This link help solved it https://community.platformio.org/t/linking-problem-with-the-blufi-example/30365/

You need to modify the `blufi_security.c` file and add
```
#include "mbedtls/esp_config.h"
```

before
```
#include "mbedtls/aes.h"
```

It seems like a bug, but at least this workaround solves it for now

**Comment by mahavirj** [comment]
@Ether-YiTseWu  Can you please confirm your build environment? Are you using platformio, if yes then I would suggest that you file issue on their forum. From IDF perspective, I have not been able to recreate this build failure locally.

**Comment by mahavirj** [comment]
Closing due to lack of update. Please drop a comment if you have any additional details to share..
