### ISSUE TITLE
How can I control 6 servo's at the same time for idf 4.4.4? (IDFGH-9769)

### ISSUE THREAD

**Issue by waruqi** [espressif/esp-idf#11103]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

I am using idf 4.4.4 to manipulate pwm to control a servo and I need to control 6 servos at the same time, but I see that idf 4.4.4's pwm can only control a maximum of 2

```
typedef enum {
    MCPWM_UNIT_0,   /*!<MCPWM unit0 selected*/
    MCPWM_UNIT_1,   /*!<MCPWM unit1 selected*/
    MCPWM_UNIT_MAX, /*!<Max number of MCPWM units*/
} mcpwm_unit_t;

typedef enum {
    MCPWM_TIMER_0,   /*!<Select MCPWM timer0*/
    MCPWM_TIMER_1,   /*!<Select MCPWM timer1*/
    MCPWM_TIMER_2,   /*!<Select MCPWM timer2*/
    MCPWM_TIMER_MAX, /*!<Max number of timers in a unit*/
} mcpwm_timer_t;

    mcpwm_gpio_init(MCPWM_UNIT_0, MCPWM0A, SERVO_PULSE_GPIO); // To drive a RC servo, one MCPWM generator is enough

    mcpwm_config_t pwm_config = {
        .frequency = 50, // frequency = 50Hz, i.e. for every servo motor time period should be 20ms
        .cmpr_a = 0,     // duty cycle of PWMxA = 0
        .counter_mode = MCPWM_UP_COUNTER,
        .duty_mode = MCPWM_DUTY_MODE_0,
    };
    mcpwm_init(MCPWM_UNIT_0, MCPWM_TIMER_0, &pwm_config);

```

Although I am aware of idf 5.x support, 5.x is not yet compatible with many components and my project does not yet compile on 5.x. I have to continue using idf 4.4.4

**Comment by waruqi** [comment]
components/soc/esp32s3/include/soc/soc_caps.h

```
#define SOC_MCPWM_GROUPS                     (2)    ///< 2 MCPWM groups on the chip (i.e., the number of independent MCPWM peripherals)
```

The esp32s3 can only control two servos? But why can I control 6 of them at the same time with micropython for same chip?

**Comment by suda-morris** [comment]
To drive an RC servo, you need (MCPWM_UNITx, MCPWM_TIMERy), where x belongs to [0,1], y belongs to [0,2], that's 2*3=6 in total.

**Comment by waruqi** [comment]
But when binding the gpio pin, we use the mcpwm_gpio_init interface to bind the servo's pin, but only pass MCPWM_UNIT_0, I don't see the timer id parameter set.

How can I set different servo gpio pins according to different timers?

```
    mcpwm_gpio_init(MCPWM_UNIT_0, MCPWM0A, SERVO_PULSE_GPIO); // To drive a RC servo, one MCPWM generator is enough

    mcpwm_config_t pwm_config = {
        .frequency = 50, // frequency = 50Hz, i.e. for every servo motor time period should be 20ms
        .cmpr_a = 0,     // duty cycle of PWMxA = 0
        .counter_mode = MCPWM_UP_COUNTER,
        .duty_mode = MCPWM_DUTY_MODE_0,
    };
    mcpwm_init(MCPWM_UNIT_0, MCPWM_TIMER_0, &pwm_config);
```

**Comment by waruqi** [comment]
Should I use the ledc interface instead of the mcpwm interface?

```
static void example_ledc_init(void)
{
    // Prepare and then apply the LEDC PWM timer configuration
    ledc_timer_config_t ledc_timer = {
        .speed_mode       = LEDC_MODE,
        .timer_num        = LEDC_TIMER,
        .duty_resolution  = LEDC_DUTY_RES,
        .freq_hz          = LEDC_FREQUENCY,  // Set output frequency at 5 kHz
        .clk_cfg          = LEDC_AUTO_CLK
    };
    ESP_ERROR_CHECK(ledc_timer_config(&ledc_timer));

    // Prepare and then apply the LEDC PWM channel configuration
    ledc_channel_config_t ledc_channel = {
        .speed_mode     = LEDC_MODE,
        .channel        = LEDC_CHANNEL,
        .timer_sel      = LEDC_TIMER,
        .intr_type      = LEDC_INTR_DISABLE,
        .gpio_num       = LEDC_OUTPUT_IO,
        .duty           = 0, // Set duty to 0%
        .hpoint         = 0
    };
    ESP_ERROR_CHECK(ledc_channel_config(&ledc_channel));
}

void app_main(void)
{
    // Set the LEDC peripheral configuration
    example_ledc_init();
    // Set duty to 50%
    ESP_ERROR_CHECK(ledc_set_duty(LEDC_MODE, LEDC_CHANNEL, LEDC_DUTY));
    // Update duty to apply the new value
    ESP_ERROR_CHECK(ledc_update_duty(LEDC_MODE, LEDC_CHANNEL));
}
```

**Comment by suda-morris** [comment]
> How can I set different servo gpio pins according to different timers?

You may want to try e.g. ` mcpwm_gpio_init(MCPWM_UNIT_0, MCPWM1A, SERVO_PULSE_GPIO);` for timer1, and MCPWM2A for timer2.

**Comment by waruqi** [comment]
> > How can I set different servo gpio pins according to different timers?
> 
> You may want to try e.g. ` mcpwm_gpio_init(MCPWM_UNIT_0, MCPWM1A, SERVO_PULSE_GPIO);` for timer1, and MCPWM2A for timer2.

so I can always use same unit (MCPWM_UNIT_0), then set different output pins (max 6 pins) to control 6 servos at same time?

```
    MCPWM0A = 0,        /*!<PWM0A output pin*/
    MCPWM0B,            /*!<PWM0B output pin*/
    MCPWM1A,            /*!<PWM1A output pin*/
    MCPWM1B,            /*!<PWM1B output pin*/
    MCPWM2A,            /*!<PWM2A output pin*/
    MCPWM2B,            /*!<PWM2B output pin*/
```

**Comment by suda-morris** [comment]
No. The legacy MCPWM driver has a **wrong** assumption that it timer-x is used to drive operator-x. (see https://github.com/espressif/esp-idf/blob/master/components/driver/deprecated/mcpwm_legacy.c#L327)

So the relationship is, MCPWM_TIMER_0  controls MCPWM0A and MCPWM0B. MCPWM_TIMER_1 controls MCPWM1A and MCPWM1B, etc.

**Comment by waruqi** [comment]
so should I configure 6 servos, like this?

```
static ot_servo_config_t g_servo_configs[OT_SERVO_MAX] = {
    { MCPWM_UNIT_0, MCPWM_TIMER_0, MCPWM0A, MCPWM_GEN_A },
    { MCPWM_UNIT_0, MCPWM_TIMER_1, MCPWM1A, MCPWM_GEN_A },
    { MCPWM_UNIT_0, MCPWM_TIMER_2, MCPWM2A, MCPWM_GEN_A },
    { MCPWM_UNIT_1, MCPWM_TIMER_0, MCPWM0B, MCPWM_GEN_B },
    { MCPWM_UNIT_1, MCPWM_TIMER_1, MCPWM1B, MCPWM_GEN_B },
    { MCPWM_UNIT_1, MCPWM_TIMER_2, MCPWM2B, MCPWM_GEN_B },
};

for (int idx =0; idx < 6; idx++) {
    ot_servo_config_t const* config = &g_servo_configs[idx];
    mcpwm_gpio_init(config->unit, config->generator, pin);
    mcpwm_config_t pwm_config = {
        .frequency = OT_SERVO_FREQ,
        .cmpr_a = 0, // duty cycle of PWMxA = 0
        .counter_mode = MCPWM_UP_COUNTER,
        .duty_mode = MCPWM_DUTY_MODE_0,
    };
    mcpwm_init(config->unit, config->timer, &pwm_config);
    mcpwm_set_duty_in_us(config->unit, config->timer, config->generator_op, us);
}

```

**Comment by suda-morris** [comment]
yeah, it should be able to. But it doesn't mean MCPWM_GEN_B is for MCPMW_UNIT_1, you can still use MCPWM_GEN_A in MCPWM_UNIT_A configuration.

**Comment by waruqi** [comment]
It's my mistable, I misconfigured some gpio pin numbers.
