### ISSUE TITLE
Can not upload any FW to Adafruit ESP32S3 feather after upgrading from ESP-IDF V4.4.3 to V5.0.1 (IDFGH-9780)

### ISSUE THREAD

**Issue by idea--list** [espressif/esp-idf#11115]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

Release V5.0.1

### Operating System used.

Windows

### How did you build your project?

Command line with idf.py

### If you are using Windows, please specify command line type.

PowerShell

### What is the expected behavior?

I am expecting that i can upload FW images to my board.

### What is the actual behavior?

After upgrading from ESP-IDF V4.4.3 to V5.0.1 i can not upload any FW to my Adafruit ESP32S3 board.
Used the Offline installer of ESP-IDF for windows, so did not pull the latest master from github.

I remember i reported a similar change for [arduino-esp32 project](https://github.com/espressif/arduino-esp32/issues/7882).
Downloaded the latest esptool suggested there (V4.5.1), extracted the esptool folder inside the zip to `c:\Espressif\python_env\idf5.0_py3.8_env\Lib\site-packages\` and since then uploads work fine again.

Not sure if the latest release/master available on github already addresses this, but it seems the offline installer [here](https://dl.espressif.com/dl/esp-idf/) does not include the fix yet.

### Steps to reproduce.

Step 1: Install ESP-IDF V5.0.1 on your Windows 10 machine
Step 2: Try to upload any FW to an Adafruit ESP32S3 Feather board (probably also Lillygo TdisplayS3 is affected)

**Comment by dobairoland** [comment]
I assume that the reason why an older esptool is bundled with the ESP-IDF v5.0.1 offline installer is that it was released on the 17th February (the installer 1-2 days later) while esptool v4.5.1 only later, on the 1st of March. So I expect that ESP-IDF v5.0.2 will be bundled with esptool v4.5.1 (or newer).

cc @georgik Please correct me if I'm wrong.

BTW, if your installation is not completely offline then you can run `install.ps1` at any time which should upgrade esptool to the latest version (among other similar tools).
