### ISSUE TITLE
btc_spp_write unable to find RFCOMM slot! (IDFGH-9786)

### ISSUE THREAD

**Issue by rnd0011** [espressif/esp-idf#11122]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

unable to write data using esp_spp_write ............i tried few things and same response
****btc_spp_write unable to find RFCOMM slot!****

**Comment by rnd0011** [comment]
The issue occurs when i try to write the data which is available in uart to bluetooth, i was using SPP_acceptor as reference code.

https://github.com/rnd0011/bt.git

**Comment by rnd0011** [comment]
Even with the write_bt function i am facing same issue

**Comment by xiongweichao** [comment]
Hi @rnd0011 ,

I think there is no problem if you use write_bt. BTW, the [esp_spp_write](https://github.com/espressif/esp-idf/blob/42261df71f12b0b995774d103ce68e40e8fba529/components/bt/host/bluedroid/api/include/api/esp_spp_api.h#L391) function must be called after the connection is established.

Thanks

**Comment by rnd0011** [comment]
case ESP_SPP_WRITE_EVT:
    //ESP_LOGI(SPP_TAG, "ESP_SPP_WRITE_EVT");
    writeHandle = param->write.handle;
    if(!param->write.cong) {
       // Write data received on UART to the Bluetooth device
       write_bt(param->srv_open.handle);
   }

i am facing same with writebt, is there any error in above code

in UART_DATA_Event i am calling write_bt(writeHandle )

**Comment by xiongweichao** [comment]
@rnd0011 When the connection completion event comes up, have you assigned a value to writeHandle? If not, writeHandle is always an invalid value.

**Comment by rnd0011** [comment]
@xiongweichao  Thanks for the input, the issue has been resolved now

**Comment by ELondonoO** [comment]
> @xiongweichao Thanks for the input, the issue has been resolved now
Hello rnd0011

I am having the same Issue, I began to develop with the ESP32 few day ago,  comming from Microchip with more than 20 years expirience.

I am tied up with the same issue, after the acceptor agree the connection my solution have to send information, after somes transmitionsthe ESP32 give the log "btc_spp_write unable to find RFCOMM slot!"

could you let me know a little more else how you solved this situation.

thank you soo much in advance for any comment you could give me.

**Comment by xiongweichao** [comment]
Hi @ELondonoO ,

I do not quite understand you. Has the acceptor ever received the data?

Thanks

**Comment by ELondonoO** [comment]
Hello

The reception is working amazing, receiving large amounts of data and being processed without any problem.
on the event "ESP_SPP_DATA_IND_EVT" the reception data is add to my buffer and process outside on my own task.
the solution is working fine.
but the transmission is complete opsitive, crashing all the time "btc_spp_write unable to find RFCOMM slot!"

thank you for your soon reply.


Esteban Londoño
***@***.***
www.speedsol.com

________________________________
De: xiongweichao ***@***.***>
Enviado: Monday, April 10, 2023 6:36:17 AM
Para: espressif/esp-idf ***@***.***>
Cc: Esteban Londono Ortiz ***@***.***>; Mention ***@***.***>
Asunto: Re: [espressif/esp-idf] btc_spp_write unable to find RFCOMM slot! (IDFGH-9786) (Issue #11122)


Hi @ELondonoO<https://github.com/ELondonoO> ,

I do not quite understand you. Has the acceptor ever received the data?

Thanks

-

**Comment by xiongweichao** [comment]
@ELondonoO Is the handle used by [esp_spp_write](https://github.com/espressif/esp-idf/blob/42261df71f12b0b995774d103ce68e40e8fba529/components/bt/host/bluedroid/api/include/api/esp_spp_api.h#L401) correct?

**Comment by ELondonoO** [comment]
On any event I get the handler to watch any change,
I supposed that this is my problem but I can not find a function to get the handler.

What is your advise to get the write handler to be use out side the spp event call back handler.



Esteban Londoño
***@***.***
www.speedsol.com

________________________________
De: xiongweichao ***@***.***>
Enviado: Monday, April 10, 2023 7:20:02 AM
Para: espressif/esp-idf ***@***.***>
Cc: Esteban Londono Ortiz ***@***.***>; Mention ***@***.***>
Asunto: Re: [espressif/esp-idf] btc_spp_write unable to find RFCOMM slot! (IDFGH-9786) (Issue #11122)


@ELondonoO<https://github.com/ELondonoO> Is the handle used by esp_spp_write<https://github.com/espressif/esp-idf/blob/42261df71f12b0b995774d103ce68e40e8fba529/components/bt/host/bluedroid/api/include/api/esp_spp_api.h#L401> correct?

**Comment by ELondonoO** [comment]
Are you using the vfs solution?

Sorry to bother you

***@***.***

**Comment by xiongweichao** [comment]
Hi @ELondonoO ，

I don't know what problem you are encountering, you can create a new issue and preferably provide a reproducible demo.

Thanks
