### ISSUE TITLE
Release Plans for ESP-IDF Past 5.0.1 (IDFGH-9788)

### ISSUE THREAD

**Issue by franz-ms-muc** [espressif/esp-idf#11126]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Hello, 

We plan to go into Production with a new Product, 
which we are currently developing at 5.0 RC 1. 

so the Question is as 5.0.1 is currently latest, 
are the shortly planned Bugfix Releases of 5.0 
or is 5.1 already on the Horizont ? 

Thanks, 
Franz

**Comment by dobairoland** [comment]
v5.1 is being tested and is expected to be released in 2-3 months depending on the number of discovered issues during the testing.
