### ISSUE TITLE
Blufi takes too much ram (IDFGH-9795)

### ISSUE THREAD

**Issue by casitelwithdean** [espressif/esp-idf#11132]
### Is your feature request related to a problem?

Hi,I am using esp32s3 n8r8 ，and using blufi to just config wifi,but it takes so much ram .
I find that there are two modes in blufi,one is bludroid  ,the other is nimble ,which one  will take less ram usage?
I already tried "Use dynamic memory allocation in BT/BLE stack " and "BT/BLE will first malloc the memory from the PSRAM" in menuconfig,but not much effect 
So is there a way to minimize blufi ram usage?
Thanks a lot

**Comment by xiewenxiang** [comment]
Nimble blufi will take less ram usage.

**Comment by casitelwithdean** [comment]
> Nimble blufi will take less ram usage.

thank u a lot.
