### ISSUE TITLE
Installing a domain instead of a local Ip with APSTA (IDFGH-9833)

### ISSUE THREAD

**Issue by drozdoff-dev** [espressif/esp-idf#11162]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

I am implementing the first major project on the esp32-s3 board, and switched from the arduino ide to esp-idf vs code, which seemed to me a more correct, more functional, albeit complex solution.
I ran into a problem:
It took the implementation of connecting the board to Wi-Fi and creating an access point so that the board could communicate with itself over a local network and, if there was a WiFi connection, discover additional features and functionality in the work of the original project.
I successfully coped with this task and implemented WebSocket and the server API via tls protocol on different secure ports, which also works, but the code requires improvements, but for now I put it aside.
Now my main problem is
It was necessary to make a domain for the address of the board in Wi Fi and AP, for which I used the esp_netif_set_hostname(net if, "esp") function - and this works fine for WiFi, while SoftAP only works on the static ip address 192.168.4.1. There was an idea to do redirection using the DNS settings on the board, but not I was able to find the proper information in the documentation and other sites with the help of how it is possible to implement.
Please help with solving this problem, because it is very important in two modes to have the same domain to communicate with the board's web.

**Comment by david-cermak** [comment]
@drozdoff-dev Could you please describe you problem with mdns?

> and it no longer works from a mobile device (

Are you trying to access the webserver using mdns name from your mobile phone? I think the mDNS would work seamlessly only on iPhones, on Android phones you'd have to install some application or service, e.g. Service-Browser or similar.
