### ISSUE TITLE
Missing  esp_websocket_client component in IDF version 5.0 (IDFGH-9853)

### ISSUE THREAD

**Issue by Ramakrishna247** [espressif/esp-idf#11179]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Hi,
We have developed our application with IDF 4.4.3 for ESP32 S3 board ,  we are using esp_websocket_client component , now we have moved to IDF version V5.0 , but surprisingly we see that there is no  esp_websocket_client component. 

Is  esp_websocket_client component  name got modified (i have searched components folder i didn't find any related library) ? or is is got deprecated ?

**Comment by dobairoland** [comment]
Please read the migration guide: https://docs.espressif.com/projects/esp-idf/en/latest/esp32/migration-guides/release-5.x/5.0/index.html, in particular https://docs.espressif.com/projects/esp-idf/en/latest/esp32/migration-guides/release-5.x/5.0/removed-components.html#components-moved-to-idf-component-registry.
