### ISSUE TITLE
WiFi never actually disables by calling esp_wifi_stop()  (IDFGH-9844)

### ISSUE THREAD

**Issue by BitBricker** [espressif/esp-idf#11171]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

Master 5.0

### Operating System used.

Windows

### How did you build your project?

Command line with idf.py

### If you are using Windows, please specify command line type.

CMD

### Development Kit.

ESP32-Wroom-S3

### Power Supply used.

External 3.3V

### What is the expected behavior?

Ability to truly disable/turn off WiFi module at runtime after it has been initiated.

### What is the actual behavior?

WiFi still runs and burns energy after being turned off.

### Steps to reproduce.

1. Simple code just enable WiFi config as AP, and perform esp_wifi_start().
2. Perform esp_wifi_stop() and esp_wifi_deinit()
3. Monitor power usage.
...

### More Information.

There seems to be an issue with the ability to turn off WiFi completely. On my test setup, I have tried these two scenarios with results.

Test platform 1:
1) Build sketch, initialize wifi with basic AP settings, and DO NOT perform esp_wifi_start. Last WiFi functions are set_mode and set_config. 
2) Power consumption is 0.05amp at 4.8v supply.
3) Monitor "core" temp with temperature_sensor_get_celsius and the result is 45c

Test platform 2:
1) Build sketch, initialize wifi with basic AP settings, and perform esp_wifi_start(). 
2) Power consumption is 0.11amp at 4.7v supply.
3) Monitor "core" temp with temperature_sensor_get_celsius and the result is 78c

Test platform 3:
1) Build sketch, initialize wifi with basic AP settings, and perform esp_wifi_start(). 
2) Wait 2 seconds esp_wifi_stop() and/or (no difference)  esp_wifi_deinit().
2) Power consumption is 0.07amp at 4.7v supply.
3) Monitor "core" temp with temperature_sensor_get_celsius and the result is 70c

Its clear that once esp_wifi_start() is called, WiFi is turned on and operational. Once we call deinit and/or stop (tried every combination), the AP disappeared from the list, WiFi lowers power consumption by about 0.04amp which results in 8c drop in core temp. Without calling wifi_start, the power consumption is at .05 and 45c core temps. 
This shows that esp_wifi_stop() never truelly turned off wifi and is till running on background and being in online mode.

**Comment by esp-lis** [comment]
@BitBricker I see that the wifi power domain is powered off in `esp_wifi_deinit` function (refer to [here](https://github.com/espressif/esp-idf/blob/master/components/esp_wifi/src/wifi_init.c#L166)), it final calling [esp_wifi_bt_power_domain_off](https://github.com/espressif/esp-idf/blob/master/components/esp_phy/src/phy_init.c#L332-L344). It doesn't power on or off in `esp_wifi_stop`.

**Comment by Espressif-liuuuu** [comment]
Hi @BitBricker, sorry for late reply.   
Did you solve this issue on lastest release/v5.0? I did the test as you mentioned on sdk bcca6898 (v5.0.6) and everything seems OK:  
> 1. no wifi start: 0.041amp  
> 2. wifi start: 0.110amp  
> 3. wifi init - wifi start - wifi stop - wifi deinit: 0.037amp  

the sdkconfig is attached below, could you pls retest on v5.0.6 to see if this issue fixed?
[sdkconfig.zip](https://github.com/espressif/esp-idf/files/14635305/sdkconfig.zip)

**Comment by Sherry616** [comment]
Thanks for reporting, will close due to short of feedback, feel free to reopen with more updates. 
Thanks for using our Espressif product!
