### ISSUE TITLE
[v5.1] [Heap Trace Standalone] hash map uses doubly linked list, but single linked would be better (IDFGH-9846)

### ISSUE THREAD

**Issue by chipweinberger** [espressif/esp-idf#11173]
@SoucheSouche 

Again, thanks for your work on [this PR.](https://github.com/espressif/esp-idf/pull/10793)

It looks like the hash map entries are storing a doubly linked list. i.e. TAILQ

```
/* Define struct: linked list of records */
TAILQ_HEAD(heap_trace_record_list_struct_t, heap_trace_record_t); 
typedef struct heap_trace_record_list_struct_t heap_trace_record_list_t;
static heap_trace_hash_list_t hash_map[(size_t)CONFIG_HEAP_TRACE_HASH_MAP_SIZE]; // Buffer used for hashmap entries
```

AFAICT, a singly linked list is all we need, and would save 50% of the memory.

`SLIST_HEAD(heap_trace_record_list_struct_t, heap_trace_record_t*);`

Thanks again.

**Comment by chipweinberger** [comment]
Actually, I think my TAILQ knowledge is mistaken. Looks like the pointer is implied. 

```
#define TAILQ_HEAD(name, type)						\
struct name {								\
	struct type *tqh_first;	/* first element */			\
	struct type **tqh_last;	/* addr of last next element */		\
}
```

**Comment by chipweinberger** [comment]
I edited this issue. Hopefully your internal issue tracker supports edits.

**Comment by chipweinberger** [comment]
Note, the records themselves are doubly linked because:
- during freeing, we traverse backwards
- during printing, we traverse forwards (chronological)

But the hash map does not need this feature.

**Comment by SoucheSouche** [comment]
Hi @chipweinberger, thanks for reporting this. It is true that we could use a singly linked list in the hashmap. I update the feature and get back to you with perf results.

**Comment by SoucheSouche** [comment]
So it seems that the `SLIST` has a complexity of O(n) when removing elements from the list. Meanwhile, `TAILQ` has a complexity of O(1) while removing. To get the same perf with the `SLIST` has we have with the `TAILQ`, we have to increase the size of the hashmap in a way that results in taking more memory space than with `TAILQ`.

**Comment by chipweinberger** [comment]
STAILQ is more appropriate than SLIST

it lets you remove from the end in O(1)

**Comment by SoucheSouche** [comment]
`SLIST_REMOVE` and `STAILQ_REMOVE` are traversing the entire list. Only `TAILQ_REMOVE` allows for O91) removal from the list. So I will keep using the doubly linked list.

**Comment by chipweinberger** [comment]
Ya, thats a good point. Looking at the code, you are right.

Closing this.

**Comment by chipweinberger** [comment]
Just to circle back, if we wanted to use SLIST without hurting perf, we would need to replace `map_find` (which does a linear traversal),  with `map_find_and_remove`, that way we can find the record and remove it at the same time.

This would require a small code rewrite.

**Comment by SoucheSouche** [comment]
Hi @chipweinberger, I am finally back from me extended leave! I will take a look at that idea as soon as I can :) I'll keep you posted!

**Comment by chipweinberger** [comment]
Wow nice to hear from you! I was wondering what happened to you =P

Hope you enjoyed your time off!

**Comment by SoucheSouche** [comment]
yes I did very much! I was on paternity leave :)

**Comment by SoucheSouche** [comment]
@chipweinberger , I had a look at the code. I am not sure I follow you here. Are you suggesting to make only hash_map a singly linked list?

**Comment by chipweinberger** [comment]
correct

```
Note, the records themselves are doubly linked because:
- during freeing, we traverse backwards
- during printing, we traverse forwards (chronological)

But the hash map does not need this feature.

Also, because the hash map should be large as possible to avoid collisions, we care more that each entry is as small as possible.
```

**Comment by SoucheSouche** [comment]
I will update hash_map to a singly linked list.

**Comment by SoucheSouche** [comment]
The update of the hash map was merged internally.

**Comment by chipweinberger** [comment]
awesome! glad it worked out!

**Comment by SoucheSouche** [comment]
the update will be available on next github sync. I will close the issue now.
