### ISSUE TITLE
When does idf version 5.0 or higher adapt to Ali Cloud components (IDFGH-9852)

### ISSUE THREAD

**Issue by LHYYSY** [espressif/esp-idf#11178]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

The latest version uses Aliyun

**Comment by wujiangang** [comment]
It's not under our plan to adapt newer aliyun SDK with newer IDF version, you can do this update by yourself.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, feel free to reopen.
