### ISSUE TITLE
-DIDF_SDKCONFIG_DEFAULTS not working (IDFGH-9859)

### ISSUE THREAD

**Issue by mbastida123** [espressif/esp-idf#11184]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v4.4.4

### Operating System used.

Windows

### How did you build your project?

Command line with idf.py

### If you are using Windows, please specify command line type.

CMD

### What is the expected behavior?

I want to be able to dinamycally build projects based on different sdckonfig.defaults files.

Looking on other pages (mainly this one: https://forums.freertos.org/t/using-a-custom-sdkconfig-defaults-file/11908) I have found that the key is to set `IDF_SDKCONFIG_DEFAULTS` to the path of the sdkconfig.defaults file I want to use.

### What is the actual behavior?

The compiler should pick the sdkconfig.defaults file passed.

### Steps to reproduce.

So far I have tried:

> set IDF_SDKCONFIG_DEFAULTS=c:\Users\Marti\Documents\Repos\hmi-fw-esp32\sdkconfig_copy.defaults
> echo %IDF_SDKCONFIG_DEFAULTS%
>       c:\Users\Marti\Documents\Repos\hmi-fw-esp32\sdkconfig_copy.defaults
and then:
> idf.py build

but when I look at the output I see a line with:

> Loading defaults file C:/Users/Marti/Documents/Repos/hmi-fw-esp32/sdkconfig.defaults...

So the env variable is not being used.

I have also tried:

> cmake -G Ninja -DPYTHON_DEPS_CHECKED=1 -DESP_PLATFORM=1 -DIDF_SDKCONFIG_DEFAULTS=c:\Users\Marti\Documents\Repos\hmi-fw-esp32\sdkconfig_copy.defaults -S c:\Users\Marti\Documents\Repos\hmi-fw-esp32 -B c:\Users\Marti\Documents\Repos\hmi-fw-esp32\build
> idf.py build

with the same results

**Comment by igrr** [comment]
@mbastida123 The actual name of this CMake variable is `SDKCONFIG_DEFAULTS`, not `IDF_SDKCONFIG_DEFAULTS`. Please refer to the docs [here](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/build-system.html#custom-sdkconfig-defaults) and an example of multiple build configurations [here](https://github.com/espressif/esp-idf/tree/master/examples/build_system/cmake/multi_config).

Please note that `SDKCONFIG_DEFAULTS` is documented as a CMake variable, not an environment variable. That is, you need to pass it to `idf.py` as `idf.py -D SDKCONFIG_DEFAULTS=name build`.

The build system does actually support reading `SDKCONFIG_DEFAULTS` from the environment, but until very recently this was not tested and did not properly work. We have merged a fix for that recently (https://github.com/espressif/esp-idf/commit/fbef416c3690d55ebca1bded4dc9ffe5cf0cf14b (master), https://github.com/espressif/esp-idf/commit/9f01d9aa2cce492cf685175261c898b75e33d33a (release/v5.0), https://github.com/espressif/esp-idf/commit/43ad48e43f67914d09b5b316efbb42e800675650 (release/v4.4)). v4.4.4 release which you are using does not contain this fix, so please avoid setting `SDKCONFIG_DEFAULTS` in the environment (using `set`) and pass it to `idf.py` instead.

**Comment by mbastida123** [comment]
> @mbastida123 The actual name of this CMake variable is `SDKCONFIG_DEFAULTS`, not `IDF_SDKCONFIG_DEFAULTS`. Please refer to the docs [here](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/build-system.html#custom-sdkconfig-defaults) and an example of multiple build configurations [here](https://github.com/espressif/esp-idf/tree/master/examples/build_system/cmake/multi_config).
> 
> (IDF_SDKCONFIG_DEFAULTS is the name using in AWS FreeRTOS distribution only, not in ESP-IDF.)
> 
> Please note that `SDKCONFIG_DEFAULTS` is documented as a CMake variable, not an environment variable. That is, you need to pass it to `idf.py` as `idf.py -D SDKCONFIG_DEFAULTS=name build`.
> 
> The build system does actually support reading `SDKCONFIG_DEFAULTS` from the environment, but until very recently this was not tested and did not properly work. We have merged a fix for that recently ([fbef416](https://github.com/espressif/esp-idf/commit/fbef416c3690d55ebca1bded4dc9ffe5cf0cf14b) (master), [9f01d9a](https://github.com/espressif/esp-idf/commit/9f01d9aa2cce492cf685175261c898b75e33d33a) (release/v5.0), [43ad48e](https://github.com/espressif/esp-idf/commit/43ad48e43f67914d09b5b316efbb42e800675650) (release/v4.4)). v4.4.4 release which you are using does not contain this fix, so please avoid setting `SDKCONFIG_DEFAULTS` in the environment (using `set`) and pass it to `idf.py` instead.

Hi @igrr and sorry, I searched on google but I didn't search directly on the idf repo.

Thank you!
