### ISSUE TITLE
esp_blufi_adv_start函数需要增加参数name (IDFGH-9858)

### ISSUE THREAD

**Issue by Leadrive** [espressif/esp-idf#11183]
### Is your feature request related to a problem?

原函数的名字，是写死在配置中的，无法动态设置名字

### Describe the solution you'd like.

void esp_blufi_adv_start(char *name)
增加一个参数name
````c
void esp_blufi_adv_start(char *name)
{
    if (name!=NULL && strlen(name)>0) {
        esp_ble_gap_set_device_name(name);
    } else {
        esp_ble_gap_set_device_name(BLUFI_DEVICE_NAME);
    }
    esp_ble_gap_config_adv_data(&blufi_adv_data);
}
````

### Describe alternatives you've considered.

无

### Additional context.

无

**Comment by Leadrive** [comment]
esp_blufi.c Line 371

**Comment by zhp0406** [comment]
@Leadrive 
感谢报告问题，
我们目前已经支持了该功能，可以在配置项中设置 name，具体的 commit 是 cf03aee0bc9115b27e00ac0437774eeb13c0db02

**Comment by Leadrive** [comment]
@Alvin1Zhang 如何重新open这个issue，问题没解决啊。

**Comment by zhp0406** [comment]
@Leadrive 
你直接调用这两个 API 就可以完成你的功能 esp_bt_dev_set_device_name esp_ble_gap_config_adv_data

**Comment by Leadrive** [comment]
@zhp0406 
用esp_bt_dev_set_device_name 不好使啊，我也不知道问题出在哪。
我现在是改了esp_blufi_adv_start，好用。多加参数 char *name。
相应的其它几个小地方也要改一下。

**Comment by zhp0406** [comment]
@Leadrive 
void esp_blufi_adv_start(char *name)
{
    if (name!=NULL && strlen(name)>0) {
        esp_ble_gap_set_device_name(name);
    } else {
        esp_ble_gap_set_device_name(BLUFI_DEVICE_NAME);
    }
    esp_ble_gap_config_adv_data(&blufi_adv_data);
}

你的这种修改方法你本地使用没有任何问题，我没有提交到 IDF 的原因是我要考虑到原有的用户，如果提交到 IDF，之前用户升级 IDF 版本后就可能出现编译不过的问题，相当于 API 已经改变了。

**Comment by Leadrive** [comment]
@zhp0406
好的，谢谢，我把这函数复制出来，单独用即可。

**Comment by zhp0406** [comment]
@Leadrive 
感谢你的理解，如果使用过程中有其他问题，请再联系我们。

**Comment by hachi** [comment]
@esp-zhp I cannot read most of the text in this thread, but I think I want the feature that was proposed here... was it ever added?

Specifically I want to be able to set my device name when using the blufi component. The name is a #define constant in header only, can't even configure in menuconfig, nor via function call.

A commit hash of cf03aee0bc9115b27e00ac0437774eeb13c0db02 is referenced but doesn't exist (never merged)
