### ISSUE TITLE
[TW#15842] Preferences Library getString problem

### ISSUE THREAD

**Issue by shashankkhare** [espressif/esp-idf#1120]
Reading a string from Preferences library through getString(char *, char *, size_t nmax) without giving third argument causes it to fail. I am using latest esp32 Preferences lib which I downloaded yesterday. 

Thanks
Shashank

**Comment by me-no-dev** [comment]
Maybe you meant to post this in the Arduino repo? Those arguments do not have default values, so you need to provide them all.

**Comment by igrr** [comment]
Closing as not IDF related.
