### ISSUE TITLE
Invalid assignment to rmt_encode_state_t for RMT led strip encoder example (IDFGH-9881) (IDFGH-9882)

### ISSUE THREAD

**Issue by fschuetz** [espressif/esp-idf#11200]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v5.1-dev

### Operating System used.

macOS

### How did you build your project?

VS Code IDE

### If you are using Windows, please specify command line type.

None

### What is the expected behavior?

Example should compile.

### What is the actual behavior?

Example does not compile.

### Steps to reproduce.

Try to compile using strict compiler settings. I embedded it in a c++ project and adapted the example, removing the "extern C". This will not allow the assignment due to strict type checking.

In the examples/peripherals/rmt/led_strip/main/led_strip_encoder.c on line 25 and 26 the following assignment is done:
```
    rmt_encode_state_t session_state = 0;
    rmt_encode_state_t state = 0;
```

However, the rmt_encode_state_t is defined in components/driver/rmt/include/driver/rmt_encoder.h as
```
typedef enum {
    RMT_ENCODING_COMPLETE = (1 << 0), /*!< The encoding session is finished, the caller can continue with subsequent encoding */
    RMT_ENCODING_MEM_FULL = (1 << 1), /*!< The encoding artifact memory is full, the caller should return from current encoding session */
} rmt_encode_state_t;
```

This means it cannot be assigned 0 and thus the example does not work, as the fields of rmt_encode_state_t are 1 and 2. It might be useful to adapt rmt_encode_state_t to include a field RMT_ENCODING_OK = 0 (which I think would be the right thing to do as this type serves to hold the return code from the rmt encoders) or the example needs to be adapted.

### Build or installation Logs.

```plain
examples/peripherals/rmt/led_strip/main/led_strip_encoder.c:26:40: error: invalid conversion from 'int' to 'rmt_encode_state_t' [-fpermissive]
 25   |     rmt_encode_state_t session_state = 0;
      |                                        ^
      |                                        |
      |                                        int
examples/peripherals/rmt/led_strip/main/led_strip_encoder.c:27:32: error: invalid conversion from 'int' to 'rmt_encode_state_t' [-fpermissive]
 26   |     rmt_encode_state_t state = 0;
      |                                ^
      |                                |
      |                                int
```

**Comment by suda-morris** [comment]
Thanks for reporting. Yes, this is something we can do better in the esp-idf side. We will introduce a new enum variant `RMT_ENCODING_INIT = 0` in the `rmt_encode_state_t`
