### ISSUE TITLE
ESP32蓝牙 ble多连接 (IDFGH-10002)

### ISSUE THREAD

**Issue by ledisOFF** [espressif/esp-idf#11219]
### Is your feature request related to a problem?

实现使用3个ESP32通过蓝牙连接通信，一个做主机，另外两个做从机，主机从机自己可以互相通信，两个从机之间不做要求

**Comment by zhp0406** [comment]
在 client 连接 server 后，server 继续保持广播即可实现多连接的功能，其他 client 可以进一步连接 server。具体而言，可以在“ESP_GATTS_CONNECT_EVT”事件中开启广播来完成此功能。在 esp-idf 中，可通过 esp_ble_gap_start_advertising(esp_ble_adv_params_t *adv_params) API 打开广播。

**Comment by ledisOFF** [comment]
很感谢您的解答，我以按您的思路实现了这个做法



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月27日(周四) 下午2:17
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [espressif/esp-idf] ESP32蓝牙 ble多连接 (Issue #11219)




 
在 client 连接 server 后，server 继续保持广播即可实现多连接的功能，其他 client 可以进一步连接 server。具体而言，可以在“ESP_GATTS_CONNECT_EVT”事件中开启广播来完成此功能。在 esp-idf 中，可通过 esp_ble_gap_start_advertising(esp_ble_adv_params_t *adv_params) API 打开广播。
