### ISSUE TITLE
[TW#15913] How to communicate with the blufi example

### ISSUE THREAD

**Issue by jvandewync** [espressif/esp-idf#1122]
Hello,

First of all, the blufi example works just fine with the EspBlufi Android app. However, when I try to create a swift application (iOS) for communicating a custom SSID and password, I'm not sure what to send. I have tried to send some strings such as "ssid:my_ssid", "passwd:my_passwd", "confirm:", but it is not working. Is it possible to have a more complete documentation on how to communicate with the blufi example?

**Comment by Weijian-Espressif** [comment]
hi @jvandewync , you can refer Esp-blufi ios code, you can use the lib directly,here is the link. https://github.com/EspressifApp/EspBlufiForiOS

**Comment by n0p** [comment]
But what if we want to implement blufi in anything that's not iOS or Android native (for example linux or even ionic)
A protocol reference would be nice

**Comment by jvandewync** [comment]
I have already investigated the iOS code, but thanks for the link @Weijian-Espressif. Similarly, I was wondering if Espressif could provide a protocol documentation.

**Comment by Weijian-Espressif** [comment]
The document is not open,  please tell us if there are other needs

**Comment by ravitej-BLR457** [comment]
Hi , While trying this Blufi ios .. getting this error.  Request you to help.

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_PacketCommand", referenced from:
      objc-class-ref in BLEViewController.o
  "_OBJC_CLASS_$_DH_AES", referenced from:
      objc-class-ref in BLEViewController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by Weijian-Espressif** [comment]
@ravitej-BLR457  I test my project, everything is OK. it seem like that your library path  is wrong, please check.

**Comment by ravitej-BLR457** [comment]
Hi , Thanks for the reply . The sample is working. 
I'm trying to use for one of our app , can you please point to some doc or code how to import this library and use for customisation.  Does this support Swift code?

**Comment by jvandewync** [comment]
It is working fine for me in Swift.

**Comment by ravitej-BLR457** [comment]
Hi,

Request you to share some sample using the same lib in Swift. Will be very
helpful.

If any doc to integrate and test also helps.

Thanks in advance.

Regards
Ravitej Tatipamula
Ph: 9342883292

**Comment by ravitej-BLR457** [comment]
Hi , Do we have any document or sample swift code suing the library specific to  ios . It will be a great help.
