### ISSUE TITLE
CHIP_FEATURE_EMB_PSRAM not set on ESP32-PICO-V3-02 (IDFGH-9938)

### ISSUE THREAD

**Issue by mmrein** [espressif/esp-idf#11233]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Quite simply, I would expect the `esp_chip_info()` to return CHIP_FEATURE_EMB_PSRAM bit set for ESP32-PICO-V3-02 (EFUSE_RD_CHIP_VER_PKG_ESP32PICOV302) as it has 2MB PSRAM included in same package. But this bit is only set for EFUSE_RD_CHIP_VER_PKG_ESP32D0WDR2V3 as we can see here:

https://github.com/espressif/esp-idf/blob/df9310ada26123d8d478bcfa203f874d8c21d654/components/esp_hw_support/port/esp32/chip_info.c#L31-L40

In case the Embedded PSRAM feature bit has different meaning then it would be good to clarify that in documentation.

### Edit:

The esptool (IDF v4.4.4) does report Embedded PSRAM correctly, so it really seems like the issue in `esp_chip_info()`:

```
esptool.py v3.3.2
Serial port /dev/ttyUSB1
Connecting....
Chip is ESP32-PICO-V3-02 (revision 3)
Features: WiFi, BT, Dual Core, 240MHz, Embedded Flash, Embedded PSRAM, VRef calibration in efuse, Coding Scheme None
Crystal is 40MHz
```

in which case I suppose correct if statement would be:

```c
    if(package == EFUSE_RD_CHIP_VER_PKG_ESP32D0WDR2V3 ||
       package == EFUSE_RD_CHIP_VER_PKG_ESP32PICOV302) {
        out_info->features |= CHIP_FEATURE_EMB_PSRAM;
    }
```

**Comment by ESP-Marius** [comment]
@mmrein you are right, seems like we might have missed adding it to the list.

We'll fix it, thanks!
