### ISSUE TITLE
Can't use the std::vector - fatal error: vector: No such file or directory (IDFGH-9955)

### ISSUE THREAD

**Issue by RJSDevel** [espressif/esp-idf#11248]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

I tryed to use the vector but it isn't available
with enabled cpp via target_compile_options(${COMPONENT_LIB} PRIVATE -std=gnu++20), the same problem
How to get it?

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, would you please help provide more details as per [the issue template](https://github.com/espressif/esp-idf/issues/new/choose)? Thanks.

**Comment by 0xjakob** [comment]
@RJSDevel `std::vector` is indeed available, we are actually [using `std::vector`](https://github.com/espressif/esp-idf-cxx/blob/main/include/i2c_cxx.hpp#L140) in [ESP-IDF-C++](https://github.com/espressif/esp-idf-cxx). Do you have a minimal reproducer for the build error? Could you provide the full compiler call that is executed? It looks a bit as if the include path to the toolchain is missing.

**Comment by RJSDevel** [comment]
@0xjakob I've got the project just from LEDC example, and if i add #include <vector> than appears the error fatal error: vector: No such file or directory

**Comment by RJSDevel** [comment]
![image](https://user-images.githubusercontent.com/12229274/233835495-2789e466-e249-45ec-a412-323ed0357ac4.png)

**Comment by RJSDevel** [comment]
![image](https://user-images.githubusercontent.com/12229274/233835557-67650ad1-5176-478d-8f24-aaba48897733.png)

**Comment by RJSDevel** [comment]
I tryed to add to any projects from examples and the result the same

**Comment by erhankur** [comment]
@RJSDevel For any given input file, the file name suffix determines what kind of compilation is done. In your case, GCC recognizes C files and will use C compilation instead of C++. So, basically, first of all, you need to change your file extension to `.cpp`  And second add the `extern "C"` directive to the `app_main`  function to make it visible in the C namespace.

**Comment by RJSDevel** [comment]
@erhankur Thank you a lot! I've finally got vector, but too got other errors
![image](https://user-images.githubusercontent.com/12229274/233964621-d6969ea9-2c43-4493-a0b0-2b60a6e52030.png)

**Comment by erhankur** [comment]
C++ has own its huge rule set that differs then C. Of course, you have to make the necessary changes when you switch to C++. I think error messages are pretty clear to understand and fix the errors.

**Comment by RJSDevel** [comment]
@erhankur yes, I think I will manage to it, thank you 😊
