### ISSUE TITLE
BLE UUID: readability (IDFGH-9949)

### ISSUE THREAD

**Issue by eiffel31** [espressif/esp-idf#11243]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Is there any rationale in writing ".uuid = &some_uuid.u" instead of ".uuid = &some_uuid"?
The ".u" is quite confusing, it does suggest that only the type is needed and not the value, which is wrong.
The root cause is uuid field declaration in ble_gatt_svc_def: it is "ble_uuid_t *uuid;" where it should be "ble_uuid_any_t *uuid". (what is really needed is the UUID value, not it's type)

components/bt/host/nimble/nimble/apps/bleprph/src/gatt_svr.c:        .uuid = &gatt_svr_svc_sec_test_uuid.u,
components/bt/host/nimble/nimble/apps/bleprph/src/gatt_svr.c:            .uuid = &gatt_svr_chr_sec_test_rand_uuid.u,
components/bt/host/nimble/nimble/apps/bleprph/src/gatt_svr.c:            .uuid = &gatt_svr_chr_sec_test_static_uuid.u,
components/bt/host/nimble/nimble/apps/btshell/src/gatt_svr.c:        .uuid = &gatt_svr_svc_sec_test_uuid.u,
components/bt/host/nimble/nimble/apps/btshell/src/gatt_svr.c:            .uuid = &gatt_svr_chr_sec_test_rand_uuid.u,
components/bt/host/nimble/nimble/apps/btshell/src/gatt_svr.c:            .uuid = &gatt_svr_chr_sec_test_static_uuid.u,
components/bt/host/nimble/nimble/apps/btshell/src/gatt_svr.c:            .uuid = &gatt_svr_chr_sec_test_static_auth_uuid.u,
components/bt/host/nimble/nimble/apps/mesh_badge/src/gatt_svr.c:        .uuid = &name_uuid.u,
components/bt/host/nimble/nimble/apps/mesh_badge/src/gatt_svr.c:            .uuid = &name_enc_uuid.u,
components/bt/host/nimble/nimble/apps/mesh_badge/src/gatt_svr.c:                    .uuid = &gatt_cud_uuid.u,
components/bt/host/nimble/nimble/apps/mesh_badge/src/gatt_svr.c:                    .uuid = &gatt_cpf_uuid.u,
components/bt/host/nimble/nimble/nimble/host/services/bleuart/src/bleuart.c:        .uuid = &gatt_svr_svc_uart_uuid.u,
components/bt/host/nimble/nimble/nimble/host/services/bleuart/src/bleuart.c:            .uuid = &gatt_svr_chr_uart_read_uuid.u,
components/bt/host/nimble/nimble/nimble/host/services/bleuart/src/bleuart.c:            .uuid = &gatt_svr_chr_uart_write_uuid.u,
examples/bluetooth/nimble/ble_spp/spp_server/main/gatt_svr.c:        .uuid = &gatt_svr_svc_sec_test_uuid.u,
examples/bluetooth/nimble/ble_spp/spp_server/main/gatt_svr.c:                .uuid = &gatt_svr_chr_sec_test_rand_uuid.u,
examples/bluetooth/nimble/ble_spp/spp_server/main/gatt_svr.c:                .uuid = &gatt_svr_chr_sec_test_static_uuid.u,
examples/bluetooth/nimble/bleprph/main/gatt_svr.c:        .uuid = &gatt_svr_svc_sec_test_uuid.u,
examples/bluetooth/nimble/bleprph/main/gatt_svr.c:                .uuid = &gatt_svr_chr_sec_test_rand_uuid.u,
examples/bluetooth/nimble/bleprph/main/gatt_svr.c:                .uuid = &gatt_svr_chr_sec_test_static_uuid.u,
examples/bluetooth/nimble/bleprph_wifi_coex/main/gatt_svr.c:        .uuid = &gatt_svr_svc_sec_test_uuid.u,
examples/bluetooth/nimble/bleprph_wifi_coex/main/gatt_svr.c:                .uuid = &gatt_svr_chr_sec_test_rand_uuid.u,
examples/bluetooth/nimble/bleprph_wifi_coex/main/gatt_svr.c:                .uuid = &gatt_svr_chr_sec_test_static_uuid.u,
examples/system/ota/advanced_https_ota/main/ble_helper/nimble_gatts.c:        .uuid = &gatt_svr_svc_sec_test_uuid.u,
examples/system/ota/advanced_https_ota/main/ble_helper/nimble_gatts.c:            .uuid = &gatt_svr_chr_sec_test_rand_uuid.u,

Most parts of the code use BLE_UUIDxx_DECLARE like this:
.uuid = BLE_UUID16_DECLARE(GATT_DEVICE_INFO_UUID)
In the lines listed above, BLE_UUIDxx_INIT is used.

So 2 forms are used:
ble_uuid_any_t my_uuid = BLE_UUIDxx_INIT(0x...)
.uuid = &my_uuid
And
#define MY_UUID 0x...
.uuid = BLE_UUIDxx_DECLARE(MY_UUID)

Mixing the 2 forms is not ideal and may be confusing.

Which form is best?
Form 1:
- the typing system is used
- my_uuid is really an UUID
- the information length is local to the declaration

Form 2:
- MY_UUID is not an UUID, this is just an untyped, unchecked definition
- each time MY_UUID is used, it is required to check it's definition to know which BLE_UUIDxx_DECLARE to use (how many bits?)

Looks like form 1 is a clear winner.

Form 1 allows to write:
#define MY_UUID BLE_UUIDxx_INIT(0x...)
and use it: .uuid = &MY_UUID

Note: Here I consider BLE_UUIDxx_INIT macro are changed to "return" ble_uuid_any_t.
ble_uuid_t will probably disapear from function prototypes to be replaced by ble_uuid_any_t

Hope all this is clear and makes sense :-)

**Comment by rahult-github** [comment]
Closing issue. Please feel free to reopen is more queries.
