### ISSUE TITLE
ESP-IDF  ESP-32 hellow_world Monitor error issues Help me.

### ISSUE THREAD

**Issue by DaftpunkK** [espressif/esp-idf#1124]
my spec:  sparkfun ESP32 Thing
                windows 10 64bit
                mingw32 installed
                make monitor baud rate : 115200 bps

I have tried some simple examples(hello_world..etc) using esp-idf.

The make flash part works fine.

However, when I run make monitor, the strange characters appear in all examples.

> ets Jun  8 2016 00:22:57

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
ets Jun  8 2016 00:22:57

rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:3
load:0x3fff0010,len:4
load:0x3fff0014,len:5568
ho 0 tail 12 room 4
load:0x40078000,len:0
load:0x40078000,len:12476
xȜ
  ߎݘP4t H
         H
          .ں
nrl╝b

     nnb
        l'    l╝ b$bĒܒb$lbl8l8l8 | < 8~nnn܉bnln#`8ln╚İl 8~nb

n╚1n╚n܀l8nc`8ln╚0l 8~nb
                       n#ܸn $|ې l╚b8╗nb?╗╗n#<b8n#`8ln╚0l 8~nb

       l6

       l6   <

            <;Ʊrnln#`89ln╚İl 8~nb
                                 ؉l$lnĒ

                                            #l8n#`89
ln╚İl 8~nb
             lĐ8╗n6bb
                       ;`nln#`8ln╚İ
                                   l 8~nb
                                         1Onnn╗Ip
                                                 n#8n#`89ln╚İ

l 8~nb

       l#܉n╝

                 |╗╗

                         ╗╗     I lǒ╗
                                      pn╗n8n#`89ln
╚İll 8~nb

There is no separate error indication.
I think it probably works.
But the characters are broken.
Is there anyone who knows about the problem?

**Comment by ShendoXT** [comment]
Crystal frequency used to be set to auto-detect but that has been [changed recently](https://www.esp32.com/viewtopic.php?f=13&t=2800).
Your board probably has a 26 Mhz crystal.

Run make menuconfig and select a frequency manually.

**Comment by DaftpunkK** [comment]
thank you ShendoXT
