### ISSUE TITLE
[TW#15915] Wrong event dispatch on dhcp

### ISSUE THREAD

**Issue by thiker5** [espressif/esp-idf#1125]
the function tcpip_adapter_dhcpc_cb only triggers the event SYSTEM_EVENT_STA_GOT_IP , even though the right event on Ethernet should be "SYSTEM_EVENT_ETH_GOT_IP" . there is no check what adapter got the IP address to generate the  event.
I add these lines of code and it seems to work right by now, but not sure if this will cause any issue:
            if(tcpip_if == TCPIP_ADAPTER_IF_ETH)
            	evt.event_id = SYSTEM_EVENT_ETH_GOT_IP;
            else
            	evt.event_id = SYSTEM_EVENT_STA_GOT_IP;

**Comment by liuzfesp** [comment]
Hi @thiker5 this issue already be fixed by 99f29967795d13d8f6e178435fe81ebdf7e82aa3
