### ISSUE TITLE
Documentation for cam_clk_sel in LCD_CAM doesn't match the ESP32-S3 Technical Reference Manual (IDFGH-9972)

### ISSUE THREAD

**Issue by macksal** [espressif/esp-idf#11257]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v5.0.1

### Operating System used.

Windows

### How did you build your project?

VS Code IDE

### If you are using Windows, please specify command line type.

PowerShell

### What is the expected behavior?

The ESP32-S3 Technical Reference Manual has the following section on the clocks for the LCD_CAM module. 
![image](https://user-images.githubusercontent.com/33101443/233814873-9778f1c0-ec26-4525-a74f-3d4c8f4ba2b9.png)

I'd expect this to be documented in code, but the docstring/intellisense for the cam_clk_sel value within the LCD_CAM specifies the following options instead: https://github.com/espressif/esp-idf/blob/a4afa44435ef4488d018399e1de50ad2ee964be8/components/soc/esp32s3/include/soc/lcd_cam_struct.h#L519

I believe the same applies to the `lcd_clk_sel` field further up in the file too.

### What is the actual behavior?

Expected consistency between the reference manual and the code/docs.

From my testing I haven't been able to tell with certainty which is the correct option, but I am almost sure the reference manual is correct and the docstring is out of date or was written in error.

### Steps to reproduce.

N/A

**Comment by suda-morris** [comment]
the TRM is correct. The register description is sometimes out-of-sync in the early chip bringup, we will fix the discrepancy.
