### ISSUE TITLE
The idf-V4.4.2 routine (tcp_client_multi_net) is used, but restarts all the time once connected (IDFGH-9958)

### ISSUE THREAD

**Issue by jiguangchao** [espressif/esp-idf#11251]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

V4.4.2

### Operating System used.

Windows

### How did you build your project?

Command line with Make

### If you are using Windows, please specify command line type.

None

### What is the expected behavior?

I use the idf-V4.4.2 routine (tcp_client_multi_net). I modified the WiFi ID and password, there is no error after compilation, but after burning successfully, always restart. It won't restart if it's not connected to WiFi.

### What is the actual behavior?

<img width="773" alt="1682152585953" src="https://user-images.githubusercontent.com/59786485/233773187-2b65e0b0-7295-4913-a451-07a97c1df30f.png">

The error message is shown in the figure above

### Steps to reproduce.

1. Use idf-V4.4.2 routines (tcp client multi net).
2. Change the wifi ID and password
3. Compile the program and burn it

**Comment by Alvin1Zhang** [comment]
Thanks for reporting and sorry for the slow turnaround, fix is available at https://github.com/espressif/esp-idf/commit/61a0c12c29c1920738d05c0db3f6c174eef04542, feel free to reopen.
