### ISSUE TITLE
can ESP32C3 support directly execute code on PSRAM as S3 does (IDFGH-9981)

### ISSUE THREAD

**Issue by xhackerustc** [espressif/esp-idf#11266]
### Is your feature request related to a problem?

I connect an external PSRAM64H chip to ESP32C3 SPI pins, reading and writing from/to the PSRAM works perfectly, I want to know can ESP32C3 directly execute code on the PSRAM as S3 does?

### Describe the solution you'd like.

I'd like to to use the external PSRAM on ESP32C3 as ESP32S3 does, e.g directly execute code on the psram, read/write in mmap way.

**Comment by igrr** [comment]
ESP32-C3 cannot execute code from PSRAM as S3 does. Memory mapping PSRAM for data access is also not possible on ESP32-C3, this question was recently answered in https://github.com/espressif/esp-idf/issues/11193.
