### ISSUE TITLE
How to allocate dma buffer in external PSRAM (esp32s3) (IDFGH-9984)

### ISSUE THREAD

**Issue by ch-duan** [espressif/esp-idf#11269]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

[esp-idf]: version v5.0.1
[chip]: esp32s3
![esp_malloc_log](https://user-images.githubusercontent.com/52442848/234161989-6315caed-a1aa-4b01-98b0-d00f6d265986.jpg)
I have used bluetooth blufi, bluetooth adv、WIFI、SPI、USB in my project. These use too much internal DMA memory.
How to allocate dma buffer in external PSRAM？

**Comment by suda-morris** [comment]
This depends on whether the DMA used by the peripheral is able to access the PSRAM. For example, the SPI uses GDMA, and GDMA itself does support fetching data from PSRAM, so that means, on esp32s3, the SPI is able to transfer a PSRAM buffer. The USB is using a dedicated DMA engine, which is not possible to access the PSRAM.

**Comment by ch-duan** [comment]
> This depends on whether the DMA used by the peripheral is able to access the PSRAM. For example, the SPI uses GDMA, and GDMA itself does support fetching data from PSRAM, so that means, on esp32s3, the SPI is able to transfer a PSRAM buffer. The USB is using a dedicated DMA engine, which is not possible to access the PSRAM.

Can I allocate internal memory used by bluetooth and wifi to psram?
How does spi use the dma buffer allocated by external psram?
![esp_spi_dma_malloc](https://user-images.githubusercontent.com/52442848/234257333-7a9f894e-a019-43a0-8a63-cac44b45150a.jpg)
I tried to allocate the dma buffer received by spi to MALLOC_CAP_32BIT, but the received data will be wrong.
Can you give me some examples or documentation?

**Comment by suda-morris** [comment]
> How does spi use the dma buffer allocated by external psram?

SPI **driver** currently doesn't support this feature, but it's WIP. In the esp-idf, the LCD driver is using the PSRAM DMA buffer heavily. e.g. https://github.com/espressif/esp-idf/blob/master/components/esp_lcd/src/esp_lcd_panel_io_i80.c#L475

**Comment by ch-duan** [comment]
I will try to use GDMA. Is there any plan for ESP32 to support all the memory used by Bluetooth, WIFI, and USB in external PSRAM?

**Comment by gm-jiang** [comment]
@ch-duan The ESP32 hardware does not support WiFI Bluetooth data to directly access PSRAM through DMA, also the ESP32 has no USB peripheral. For ESP32-s3 I think you can first receive the data to internal RAM through DMA, and then do the data transfer from internal memory to PSRAM through EDMA.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to short feedback, feel free to reopen.
