### ISSUE TITLE
how could i get a server ip address on udp client? (IDFGH-9978)

### ISSUE THREAD

**Issue by Inverter-Jo** [espressif/esp-idf#11263]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

i need some help.

i checked broadcasting on client operate well. 
but on udp server, i can't sending response message to client 
what's the problem?
here are codes that make problems.

server //

    udp_sock = socket(PF_INET, SOCK_DGRAM, 0);
    if (udp_sock < 0) {
        ESP_LOGE(TAG, "Unable to create socket: errno %d", errno);
        return ESP_ERR_INVALID_STATE;
    }

    struct sockaddr_in *dest_addr_ip4 = (struct sockaddr_in *)&dest_addr;
    dest_addr_ip4->sin_addr.s_addr = htonl(IPADDR_ANY);//?
    dest_addr_ip4->sin_family = AF_INET;
    dest_addr_ip4->sin_port = htons(PORT);
    err = bind(udp_sock, (struct sockaddr *)&dest_addr, sizeof(dest_addr));
    if(err != 0) {
        ESP_LOGE(TAG, "Socket unable to bind: errno %d", errno);
        //ESP_LOGE(TAG, "IPPROTO: %d", addr_family);
        return ESP_ERR_INVALID_STATE;
    }
    ESP_LOGI(TAG, "Socket bound(udp), port %d", PORT);    
    
    uint8_t udp_send[max_len];
    uint8_t udp_recv[max_len];   
    uint8_t udp_recv_len = 0;
    //while
    while(1){
        vTaskDelay(1);
        if(dev_flag.udp_sock_on){
            udp_recv_len = recvfrom(udp_sock, udp_recv, max_len, 0, NULL, 0);
            if(udp_recv_len > 0)
            {
                ESP_LOGI(TAG,"recv_udp : %x", udp_recv_len);  
                sendto(udp_sock, udp_send, max_len, 0, (struct sockaddr *)&dest_addr, sizeof(dest_addr));
            } 

client//

	int udp_sock = socket(PF_INET, SOCK_DGRAM, 0);
	int retval = setsockopt(udp_sock, SOL_SOCKET, SO_BROADCAST, (char *) &opt, sizeof(opt));
	if (retval == -1)ESP_LOGI(TAG,"error");
	struct sockaddr_storage dest_addr;
	struct sockaddr_in *dest_addr_ip4 = (struct sockaddr_in *)&dest_addr;
        dest_addr_ip4->sin_addr.s_addr = htonl(IPADDR_BROADCAST);
	dest_addr_ip4->sin_family = AF_INET;
	dest_addr_ip4->sin_port = htons(PORT);
	while(1){
		if(brc_cnt % 10 == 0){
	        	sendto(udp_sock, udp_send, max_len, 0, (struct sockaddr *)&dest_addr, sizeof(dest_addr));
	        }
	        else{
	        	udp_recv_len = recvfrom(udp_sock, udp_recv, max_len, 0, NULL, 0); // here!
	        	if(udp_recv_len > 0){
	        	...

below are what i can see on wireshark.
 
![image](https://user-images.githubusercontent.com/58662375/233992103-e4c60683-429d-4f30-9136-b529d195a09d.png)
upper packet is broadcasting packet, so that makes below response packet.
but as you can see, i can't take response message on client server.

**Comment by Inverter-Jo** [comment]
i should take a two sock (recv, send_broadcast) on client
and when i did it, problem is gone!

**Comment by Alvin1Zhang** [comment]
Good to hear that the issue is resolved. For further question, you could also create a post on forum https://esp32.com. Thanks.
