### ISSUE TITLE
Esp32 GPIO 27 gpio_get_level returned 0  (IDFGH-9983)

### ISSUE THREAD

**Issue by cyberumut** [espressif/esp-idf#11268]
i connected button gpio 27 but always returned 0 

how can i check gpio27 high or low ? 

gpio_set_direction(BUTTON2, GPIO_MODE_INPUT_OUTPUT);
gpio_get_level(BUTTON2);

**Comment by AxelLin** [comment]
https://github.com/espressif/esp-idf/blob/master/components/driver/gpio/include/driver/gpio.h#L145
