### ISSUE TITLE
connecting ESP32 to HiveMQ cloud with SSL (IDFGH-10026)

### ISSUE THREAD

**Issue by Jimis333** [espressif/esp-idf#11303]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

I can't connect my ESP32 to the HiveMQ cloud with SSL. 

I downloaded the CA certificate file according to this [post](https://community.hivemq.com/t/frequently-asked-questions/514) but it seems I need to add somewhere the username and password for the HiveMQ MQTT broker. **I don't see in the [example code](https://github.com/espressif/esp-idf/blob/v5.0.1/examples/protocols/mqtt/ssl/main/app_main.c) where I can add the username and password.**

**Comment by Jimis333** [comment]
I have been busting my head all day with this. I thought to ask GPT and voila ! 
![image](https://user-images.githubusercontent.com/73533611/235366898-f2e1d4e5-592d-4abe-afd6-c01d03c7ac3c.png)

There seems to be a place for the username and password in that structure but they aren't in the example code.

**Comment by Jimis333** [comment]
Found the problem.Stupid mistake. I had copy-pasted the same url twice in the appropriate field in menu config but couldn’t see it because the field is too small. I realized it when I moused over the uri variable.

**Comment by Alvin1Zhang** [comment]
Thanks for sharing the updates, feel free to reopen.
