### ISSUE TITLE
Hi all, (IDFGH-10040)

### ISSUE THREAD

**Issue by kailasvadak1178** [espressif/esp-idf#11317]
Error:- "W (1453994) wifi: [ieee80211_output.c,5195] m f null"
I am Kailas Vadak, i am facing below issue for "AWS fleet provisioning" project for ESP-Wrover kit 4.1 and IDF version is v5.0. 

Error:- "W (1453994) wifi: [ieee80211_output.c,5195] m f null"

i also confirmed the components/esp_wifi/esp32/esp_adapter.c and components/bt/controller/esp32/bt.c file changes for "MALLOC_CAP_8BIT", still i have a out of memory issue.

Note: 1. i also use the BLE for mobile at the same and it is working fine after getting above error.
2. I also use wifi for Modbus TCP/IP Server and it socket get closed after getting above error.

Please reply ASAP.

_Originally posted by @kailasvadak1178 in https://github.com/espressif/esp-idf/issues/3592#issuecomment-1524725870_

**Comment by Xiehanxin** [comment]
hi, @kailasvadak1178 ,the example you use is this: https://github.com/espressif/esp-aws-iot/tree/master/examples/fleet_provisioning/fleet_provisioning_with_csr

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, feel free to reopen.
