### ISSUE TITLE
ESP32 GSM modem UART sync failed (IDFGH-10052)

### ISSUE THREAD

**Issue by Noushadalik** [espressif/esp-idf#11329]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

I am using an ESP32-WROOM-32D microcontroller with a GSM modem(SIM7600) connected to UART0 (pins 1 and 3). When trying to initialize the modem, I am getting the following error message:

E (44288) esp-modem: esp_modem_dte_send_cmd(256): process command timeout
E (44288) dce_service: esp_modem_dce_sync(225): send command failed
E (44288) bg96: bg96_init(167): sync failed

UART configuration :
#define ESP_MODEM_DTE_DEFAULT_CONFIG()
{
.port_num = UART_NUM_0,
.data_bits = UART_DATA_8_BITS,
.stop_bits = UART_STOP_BITS_1,
.parity = UART_PARITY_DISABLE,
.baud_rate = 115200,
.flow_control = MODEM_FLOW_CONTROL_NONE,
.tx_io_num = 01,
.rx_io_num = 03,
.rts_io_num = UART_PIN_NO_CHANGE,
.cts_io_num = UART_PIN_NO_CHANGE,
.rx_buffer_size = 1024,
.tx_buffer_size = 512,
.event_queue_size = 30,
.event_task_stack_size = 2048,
.event_task_priority = 5,
.dte_buffer_size = 512
}
I have checked the wiring and the modem initialization settings, and they seem to be correct. The modem firmware is also up to date. However, I am still getting the error.

I have also tried moving the modem to a different UART(UART 1, PIN 25 AND PIN 26), but the issue does not exist modem sync successfully.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to short of feedback, feel free to reopen with more updates.
