### ISSUE TITLE
ESP32-S3-DEVKITC-1 PSRAM REBOOT PROBLEM (IDFGH-10073)

### ISSUE THREAD

**Issue by cyberumut** [espressif/esp-idf#11349]
i m using esp32-s3-devkitc-1 with idf 4.4 but when psram enabled always reboot .

what should I do? 

![image](https://user-images.githubusercontent.com/105754498/236702965-5e249819-37ae-4a46-bf94-5e58cf1df582.png)

![image](https://user-images.githubusercontent.com/105754498/236703003-86ac4e4a-4f28-4432-8301-8db86d9140f1.png)
![image](https://user-images.githubusercontent.com/105754498/236703013-983bb5ae-f663-40f7-a4d6-48ee3fcdddde.png)

**Comment by Icarus113** [comment]
Hi @cyberumut Could you provide the full console log?
