### ISSUE TITLE
[TW#15934] Clarification on BT GATTC MTU size

### ISSUE THREAD

**Issue by rojer** [espressif/esp-idf#1135]
`esp_ble_gattc_send_mtu_req` sets MTU per connection but does not actually take MTU size as parameter.
instead, it instructs us to use `esp_ble_gatt_set_local_mtu`, however, that one is global - does not take connection id.

since i expect to be talking to potentially different devices, requiring different MTU sizes, how can i use different MTU on different connections?

**Comment by Weijian-Espressif** [comment]
@rojer esp_ble_gatt_set_local_mtu() set the local support maximum MTU value, you can set the maximum MTU size of slave, the connection will use the Minimum value of two .

**Comment by rojer** [comment]
that's clear enough. the question is: how to set different MTUs for different connections?
i want the esp32 device to have 517 MTU (maximum possible), but not all the clients i connect to may support MTU this big.

**Comment by negativekelvin** [comment]
@rojer I believe esp_ble_gattc_send_mtu_req will negotiate the MTU and automatically reduce it per connection if necessary

**Comment by rojer** [comment]
no, what it does is it sends mtu request for the value set by `esp_ble_gatt_set_local_mtu`. which makes sense, except that it is global, so if i have to set different values for different connections... what then?
if `esp_ble_gatt_set_local_mtu` took connection id as parameter and only acted on that connection, it would make more sense.

**Comment by negativekelvin** [comment]
It will send request for global size but if server will respond with lower value then mtu will be reduced.  But you are saying you want to self-limit mtu on different connections independent of what the connected device says?

**Comment by Weijian-Espressif** [comment]
esp_ble_gatt_set_local_mtu only set the maximum MTU value supported by the device. The real use MTU size of every connection  is the minimum value that the two devices support.

for example:
one client  set  esp_ble_gatt_set_local_mtu(500)  , one server set esp_ble_gatt_set_local_mtu(300), The real MTU value is 300 after connection. Another server set esp_ble_gatt_set_local_mtu(27), The real MTU value is 27 after connection.

**Comment by rojer** [comment]
ok, if that's how it works, then it's fine. thanks!
