### ISSUE TITLE
Connecting ESP32 MQTT device to HiveMQ Cloud (IDFGH-10079)

### ISSUE THREAD

**Issue by krupis** [espressif/esp-idf#11354]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Hello. I have been learning about MQTT and programming ESP32 MQTT for a couple of weeks now.

I have tested it with the default mqtt broker (eclipse) as well as test. mosquitto.org and that seem to work fine. I can establish connection and publish to topics without any issues. Example ```esp_mqtt_client_config_t ``` I use when connecting to the test.mosquitto org:
```
    esp_mqtt_client_config_t mqtt5_cfg = {
        .broker.address.uri = "mqtt://test.mosquitto.org",
        .broker.address.port = 1883,
        .network.disable_auto_reconnect = false,
        .session.protocol_ver = MQTT_PROTOCOL_V_5,
        .session.last_will.topic = will_topic,
        .session.last_will.msg = "Disconnected",
        .session.last_will.msg_len = 12,
        .session.last_will.qos = 1,
        .session.last_will.retain = true,
        .session.keepalive = 5, // inform that the client is still active every 2 seconds
        
    };
```

Now I want to step it up a little and connect my MQTT devices to a Cloud MQTT broker for example HiveMQ cloud.
https://www.hivemq.com/mqtt-cloud-broker/

After creating HiveMQ account, I have managed to create a MQTT cluster
![image](https://user-images.githubusercontent.com/22237034/236794613-d9ddc180-8b20-4fb2-a299-3be797619fce.png)

For that cluster, I have created a couple of access credentials:

![image](https://user-images.githubusercontent.com/22237034/236794752-f1f2c498-66f1-4679-bc1b-6a28ef8e3369.png)

I cannot wrap my head around how can I connect to this MQTT cluster with my ESP32 device. I have changed the ```esp_mqtt_client_config_t ``` as below:
![image](https://user-images.githubusercontent.com/22237034/236795732-29f4dd2e-217f-4666-bb4a-a2581a595411.png)

But not able to connect succesfully. The logs show:
```
2023/05/08 12:59:10: [1B][0;32mI (3260) ethernet_connect: Waiting for IP(s).[1B][0m
[1B][0;32mI (3260) ethernet_connect: Ethernet Link Up[1B][0m
2023/05/08 12:59:11: [1B][0;32mI (4260) esp_netif_handlers: example_netif_eth ip: 192.168.64.106, mask: 255.255.254.0, gw: 192.168.65.254[1B][0m
[1B][0;32mI (4260) ethernet_connect: Got IPv4 event: Interface "example_netif_eth" address: 192.168.64.106[1B][0m
[1B][0;32mI (4530) ethernet_connect: Got IPv6 event: Interface "example_netif_eth" address: fe80:0000:0000:0000:c6dd:57ff:fe5f:290b, type: ESP_IP6_ADDR_IS_LINK_LOCAL[1B][0m
[1B][0;32mI (4530) example_common: Connected to example_netif_eth[1B][0m
[1B][0;32mI (4540) example_common: - IPv4 address: 192.168.64.106,[1B][0m
[1B][0;32mI (4540) example_common: - IPv6 address: fe80:0000:0000:0000:c6dd:57ff:fe5f:290b, type: ESP_IP6_ADDR_IS_LINK_LOCAL[1B][0m
[1B][0;31mE (4550) MQTT5: CELL_NUM = 1 [1B][0m
will_topic = cell/1/will 
ping_request_topic = cell/1/ping/request 
ping_response_topic = cell/1/ping/response 
[1B][0;32mI (4570) MQTT5: Other event id:7[1B][0m
[1B][0;31mE (4680) transport_base: tcp_read error, errno=Socket is not connected[1B][0m
[1B][0;31mE (4680) mqtt_client: esp_mqtt_handle_transport_read_error: transport_read() error: errno=128[1B][0m
[1B][0;32mI (4680) MQTT5: MQTT_EVENT_ERROR[1B][0m
[1B][0;32mI (4690) MQTT5: MQTT5 return code is 0[1B][0m
[1B][0;31mE (4690) MQTT5: Last error reported from esp-tls: 0x8008[1B][0m
[1B][0;31mE (4700) MQTT5: Last error captured as transport's socket errno: 0x80[1B][0m
[1B][0;32mI (4700) MQTT5: Last errno string (Socket is not connected)[1B][0m
[1B][0;31mE (4710) mqtt_client: esp_mqtt_connect: mqtt_message_receive() returned -1[1B][0m
[1B][0;31mE (4720) mqtt_client: MQTT connect failed[1B][0m
[1B][0;32mI (4720) MQTT5: MQTT_EVENT_DISCONNECTED[1B][0m
```

I have initially thought that there might be some issues with HiveMQ MQTT cluster, but I have tried free MQTT client online:
https://testclient-cloud.mqtt.cool/

![image](https://user-images.githubusercontent.com/22237034/236796003-3da24d36-339c-4201-8e82-91da85a04b04.png)

And managed to connect without any issues and even published some messages and tested it and received it on the HiveMQ side. So that confirms that everything is okay from HiveMQ side.

I have read ESP documentation about MQTT however it is still unclear which MQTT protocol should I use:
![image](https://user-images.githubusercontent.com/22237034/236813983-b1886c64-dc31-424f-926f-96ed6c6d6899.png)

Most examples that use port 8883 connect to MQTT broker using certificate. However, the HiveMQ did  not provide a certificate for me. It only gives the URL. This is my main confusion.

I hope someone can clarify to me how to connect successfully to HiveMQ cloud MQTT cluster via 8883 port without a certificate. Thanks in advance

**Comment by nopnop2002** [comment]
You can get certificate using this.

```
openssl s_client -showcerts -connect xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.s2.eu.hivemq.cloud:8883
```

**Comment by RexRashid** [comment]
@euripedesrocha please explain your answer in detail especially about splitting the URL. Also, the HiveMQ supports MQTT v5. As you mentioned that mqtt5 example is for TCP, can you provide an example for websocket on port 8884 (supported by HiveMQ) and how to download certificate.

**Comment by euripedesrocha** [comment]
@RexRashid, the details are in the documentation link provided. 
We have a websocket secure example that you can use as reference and just enable MQTT5, you will likely need to reference both examples to gather the information you need. 
I don't have a HiveMQ account to point you where to get your certificates from, but I believe that they may provide some documentation and support on the matter. 

If you have any questions about the process, please open a question on our forum. If you do find some bug feel free to open an issue on esp-mqtt repository.

**Comment by joelv1964** [comment]
@RexRashid, Hi, Like you, I have been looking for a long time how to do it. Here are some answers that can help you I hope. You can download the root certificate here : [https://letsencrypt.org/certs/isrgrootx1.pem](url)
This will create a file called “isrgrootx1.pem”, which you can use as “Server Certiciate”.
Use websocket on port 8883.
Example on Github : Search "ESP32-HiveMQ".
Joël

**Comment by euripedesrocha** [comment]
@krupis I'm closing this one, If you have something to add feel free to reopen the issue.
