### ISSUE TITLE
IDF4.4 can not install idf4.4_py3.9_env (IDFGH-10086)

### ISSUE THREAD

**Issue by hzhh110** [espressif/esp-idf#11361]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v4.4

### Operating System used.

macOS

### How did you build your project?

Eclipse IDE

### If you are using Windows, please specify command line type.

None

### What is the expected behavior?

Installing Python environment and packages
ERROR: This script was called from a virtual environment, can not create a virtual environment again

sudo ./install.sh
Detecting the Python interpreter
Checking "python" ...
Python 3.9.16
"python" has been detected
Installing ESP-IDF tools
Current system platform: macos
Selected targets are: esp32c3, esp32s3, esp32h2, esp32, esp32s2
Installing tools: xtensa-esp-elf-gdb, riscv32-esp-elf-gdb, xtensa-esp32-elf, xtensa-esp32s2-elf, xtensa-esp32s3-elf, riscv32-esp-elf, esp32ulp-elf, openocd-esp32
Skipping xtensa-esp-elf-gdb@11.2_20220823 (already installed)
Skipping riscv32-esp-elf-gdb@11.2_20220823 (already installed)
Skipping xtensa-esp32-elf@esp-2021r2-patch5-8.4.0 (already installed)
Skipping xtensa-esp32s2-elf@esp-2021r2-patch5-8.4.0 (already installed)
Skipping xtensa-esp32s3-elf@esp-2021r2-patch5-8.4.0 (already installed)
Skipping riscv32-esp-elf@esp-2021r2-patch5-8.4.0 (already installed)
Skipping esp32ulp-elf@2.35_20220830 (already installed)
Skipping openocd-esp32@v0.11.0-esp32-20221026 (already installed)
Installing Python environment and packages
ERROR: This script was called from a virtual environment, can not create a virtual environment again

### What is the actual behavior?

Installing Python environment and packages
ERROR: This script was called from a virtual environment, can not create a virtual environment again

### Steps to reproduce.

Installing Python environment and packages
ERROR: This script was called from a virtual environment, can not create a virtual environment again

**Comment by dobairoland** [comment]
Please follow https://github.com/espressif/idf-eclipse-plugin#Installation in order to setup ESP-IDF with Eclipse. If you encounter an issue then please report it in that repository.

> ERROR: This script was called from a virtual environment, can not create a virtual environment again

This explains the issue. You have an environment already active in your terminal. The install script cannot be run from there.
