### ISSUE TITLE
Crash triggered by `esp_mbedtls_handshake` in https_client (IDFGH-10091)

### ISSUE THREAD

**Issue by DCSBL** [espressif/esp-idf#11366]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v5.0

### Operating System used.

macOS

### How did you build your project?

Command line with idf.py

### If you are using Windows, please specify command line type.

None

### Development Kit.

ESP32S3-WROOM-1 MON16R8

### Power Supply used.

External 3.3V

### What is the expected behavior?

No crashes.

### What is the actual behavior?

The ESP crashes sometimes while setting up a https session. It happens for no apparent reason (randomly)

### Steps to reproduce.

Hard to say, but what we do:

1. Connect to a https server with mutual TLS enabled (.cert_pem, .client_cert_pem and .client_key_pem set)
2. Fetch data..

### Debug Logs.

We only have some limited core-dumps, all have a the same stacktrace.

```plain
Task: http_client_tsk
0x403764e6: panic_abort at ~/esp/esp-idf-v5.0/components/esp_system/panic.c:412
0x4037f659: esp_system_abort at ~/esp/esp-idf-v5.0/components/esp_system/esp_system.c:135
0x403871c1: __assert_func at ~/esp/esp-idf-v5.0/components/newlib/assert.c:78
0x420774b5: mpi_mult_mpi_failover_mod_mult at ~/esp/esp-idf-v5.0/components/mbedtls/port/esp_bignum.c:651 (inlined by) mbedtls_mpi_mul_mpi at ~/esp/esp-idf-v5.0/components/mbedtls/port/esp_bignum.c:522
0x42077591: mbedtls_mpi_mul_int at ~/esp/esp-idf-v5.0/components/mbedtls/port/esp_bignum.c:557
0x4206af99: mbedtls_mpi_div_mpi at ~/esp/esp-idf-v5.0/components/mbedtls/mbedtls/library/bignum.c:1690
0x4206b1a2: mbedtls_mpi_mod_mpi at ~/esp/esp-idf-v5.0/components/mbedtls/mbedtls/library/bignum.c:1760
0x420749fc: rsa_prepare_blinding at ~/esp/esp-idf-v5.0/components/mbedtls/mbedtls/library/rsa.c:818 (inlined by) mbedtls_rsa_private at ~/esp/esp-idf-v5.0/components/mbedtls/mbedtls/library/rsa.c:964
0x42075474: mbedtls_rsa_rsassa_pkcs1_v15_sign at ~/esp/esp-idf-v5.0/components/mbedtls/mbedtls/library/rsa.c:1883 (inlined by) mbedtls_rsa_rsassa_pkcs1_v15_sign at ~/esp/esp-idf-v5.0/components/mbedtls/mbedtls/library/rsa.c:1838
0x4207551d: mbedtls_rsa_pkcs1_sign at ~/esp/esp-idf-v5.0/components/mbedtls/mbedtls/library/rsa.c:1927
0x42072c45: rsa_sign_wrap at ~/esp/esp-idf-v5.0/components/mbedtls/mbedtls/library/pk_wrap.c:357
0x42072a1d: mbedtls_pk_sign_restartable at ~/esp/esp-idf-v5.0/components/mbedtls/mbedtls/library/pk.c:627
0x42067e06: ssl_write_certificate_verify at ~/esp/esp-idf-v5.0/components/mbedtls/mbedtls/library/ssl_tls12_client.c:3464 (inlined by) mbedtls_ssl_handshake_client_step at ~/esp/esp-idf-v5.0/components/mbedtls/mbedtls/library/ssl_tls12_client.c:3690
0x42065bbf: mbedtls_ssl_handshake_step at ~/esp/esp-idf-v5.0/components/mbedtls/mbedtls/library/ssl_tls.c:3027 (inlined by) mbedtls_ssl_handshake_step at ~/esp/esp-idf-v5.0/components/mbedtls/mbedtls/library/ssl_tls.c:2984
0x42065c18: mbedtls_ssl_handshake at ~/esp/esp-idf-v5.0/components/mbedtls/mbedtls/library/ssl_tls.c:3092 (inlined by) mbedtls_ssl_handshake at ~/esp/esp-idf-v5.0/components/mbedtls/mbedtls/library/ssl_tls.c:3068
0x4205d9fe: esp_mbedtls_handshake at ~/esp/esp-idf-v5.0/components/esp-tls/esp_tls_mbedtls.c:192
0x00000011: ?? ??:0
```

### More Information.

Hardware: We use the ESP32S3 with external PSRAM while driving a LCD screen (using this RAM).

This issue seems to be related to https://github.com/espressif/esp-idf/issues/10403

When looking at that issue, it seems that this was caused by: "[Cache disabled but cached memory region accessed](https://github.com/espressif/esp-idf/issues/10403#issuecomment-1440762286)".

I am not sure if the HTTPS client is triggering this, or that something (completely) unrelated triggers this while the client is just doing its best. Please let me know in what direction I can look and how I can give additional context.

**Comment by AxelLin** [comment]
d53d4ec is already in v5.0 branch. (It's fixed **after** v5.0.1)
