### ISSUE TITLE
蓝牙MESH 广播包内容编辑 (IDFGH-10147)

### ISSUE THREAD

**Issue by 2815918642** [espressif/esp-idf#11418]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

求助：蓝牙mesh 广播包 的内容可以像 普通蓝牙广播包 里的内容一样根据格式自定义吗？

**Comment by gnameg** [comment]
You can use the following API to send regular advertising when using mesh.
```
esp_err_t esp_ble_mesh_start_ble_advertising(const esp_ble_mesh_ble_adv_param_t *param,
                                             const esp_ble_mesh_ble_adv_data_t *data);
```
