### ISSUE TITLE
HTTPS x509 Bundle Example not working (IDFGH-10174)

### ISSUE THREAD

**Issue by herculanodavi** [espressif/esp-idf#11443]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v5.0.1

### Operating System used.

macOS

### How did you build your project?

Command line with idf.py

### If you are using Windows, please specify command line type.

None

### Development Kit.

ESP32-S3-DevkitC-1

### Power Supply used.

USB

### What is the expected behavior?

When running the test, this is the expected behavior of runnning the example:

```
I (0) cpu_start: Starting scheduler on APP CPU.
I (491) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE
I (4051) example_connect: Ethernet Link Up
I (5971) esp_netif_handlers: eth ip: 192.168.2.137, mask: 255.255.255.0, gw: 192.168.2.2
I (5971) example_connect: Connected to Ethernet
I (5971) example_connect: IPv4 address: 192.168.2.137
I (5971) example_connect: IPv6 address: fe80:0000:0000:0000:bedd:c2ff:fed4:a92b
I (5981) example: Connecting to 2 URLs
I (7100) esp-x509-crt-bundle: Certificate validated
I (8371) example: Connection established to https://www.howsmyssl.com/a/check
I (11730) esp-x509-crt-bundle: Certificate validated
I (11821) example: Connection established to https://espressif.com
I (12821) example: Completed 2 connections
I (12821) example: Starting over again...
```

### What is the actual behavior?

Connection to espressif.com not validated. Maybe the certificate in the repository is expired?

```
I (8169) example: Connecting to 2 URLs
I (8699) esp-x509-crt-bundle: Certificate validated
I (9699) example: Connection established to https://www.howsmyssl.com/a/check
E (10799) esp-x509-crt-bundle: Failed to verify certificate
E (10809) esp-tls-mbedtls: mbedtls_ssl_handshake returned -0x3000
E (10809) esp-tls: Failed to open new connection
E (10809) example: Could not connect to https://espressif.com
I (11819) example: Completed 1 connections
I (11819) example: Starting over again...
I (11819) example: Connecting to 2 URLs
I (12399) esp-x509-crt-bundle: Certificate validated
I (13439) example: Connection established to https://www.howsmyssl.com/a/check
E (14529) esp-x509-crt-bundle: Failed to verify certificate
E (14529) esp-tls-mbedtls: mbedtls_ssl_handshake returned -0x3000
E (14529) esp-tls: Failed to open new connection
E (14539) example: Could not connect to https://espressif.com
```

### Steps to reproduce.

1. Build, flash and run the examples/protocols/https_x509_bundle example.

### More Information.

I also tried to check this for Amazon Root CA's and it did not work:

```c++
#include "esp_crt_bundle.h"
#include "esp_tls.h"
#include "simple_wifi.hpp"
#include <esp_log.h>
#include <freertos/FreeRTOS.h>
#include <freertos/task.h>

#include <span>

constexpr std::array URLS{"https://good.sca0a.amazontrust.com/",
                          "https://good.sca1a.amazontrust.com/",
                          "https://good.sca2a.amazontrust.com/",
                          "https://good.sca3a.amazontrust.com/",
                          "https://good.sca4a.amazontrust.com/",
                          "https://www.howsmyssl.com/a/check",
                          "https://espressif.com"};

constexpr const char* TAG = "APP";

void httpsGetTask(void*) {
  while (true) {
    int conn_count = 0;
    ESP_LOGI(TAG, "Connecting to %d URLs", URLS.size());

    for (auto url : URLS) {
      esp_tls_cfg_t cfg = {
          .crt_bundle_attach = esp_crt_bundle_attach,
      };

      esp_tls_t* tls = esp_tls_init();
      if (tls) {
        if (esp_tls_conn_http_new_sync(url, &cfg, tls) == 1) {
          ESP_LOGI(TAG, "Connection established to %s", url);
          conn_count++;
        } else {
          ESP_LOGE(TAG, "Could not connect to %s", url);
        }
        esp_tls_conn_destroy(tls);
      } else {
        ESP_LOGE(TAG, "Failed to allocate esp_tls handle!");
      }

      vTaskDelay(1000 / portTICK_PERIOD_MS);
    }

    ESP_LOGI(TAG, "Completed %d connections", conn_count);
    ESP_LOGI(TAG, "Starting over again in 5s...");
    vTaskDelay(5000 / portTICK_PERIOD_MS);
  }
}

extern "C" void app_main(void) {
  wifi::connect();

  xTaskCreate(&httpsGetTask, "https_get_task", 8192, NULL, 5, NULL);
}
```

I got Amazon certificates from https://www.amazontrust.com/repository/

**Comment by mahavirj** [comment]
@herculanodavi 

- Issue with `https_x509_bundle` example should be fixed with https://github.com/espressif/esp-idf/commit/2688dfe982be1ba82912a466e7ddd6acb4a5878d
- Please try enabling `CONFIG_MBEDTLS_CERTIFICATE_BUNDLE_DEFAULT_FULL` , this will include in full Root cert bundle, giving the maximum coverage. ([Reference](https://docs.espressif.com/projects/esp-idf/en/latest/esp32c3/api-reference/protocols/esp_crt_bundle.html#configuration))

**Comment by herculanodavi** [comment]
Thank you @mahavirj. Would you have any feedback about the AWS root CA issue?

**Comment by herculanodavi** [comment]
Yes, I understand your suggestion: the `CONFIG_MBEDTLS_CERTIFICATE_BUNDLE_DEFAULT_CMN` will put some certificates (the AWS ones are there) in the bundle and this should work without any problems, aside from the fact that this is not the optimal way to reduce flash size.

But what doesn't work is: when I don't select the pre-done bundles (imagine I want to only bundle the certs from my `certs` folder but not any others), the validation doesn't work.

When I:
1. Activate the `CONFIG_MBEDTLS_CERTIFICATE_BUNDLE_DEFAULT_FULL` flag, my `mbedtls.a` component is around 90kB big -- works with Amazon because the certs are in the bundle
2. Activate the `CONFIG_MBEDTLS_CERTIFICATE_BUNDLE_DEFAULT_CMN` flag, my `mbedtls.a`component is around 60kB big -- works with Amazon because the certs are in the bundle
3. Set the:

```CONFIG_MBEDTLS_CERTIFICATE_BUNDLE_DEFAULT_NONE=y
CONFIG_MBEDTLS_CUSTOM_CERTIFICATE_BUNDLE=y
CONFIG_MBEDTLS_CUSTOM_CERTIFICATE_BUNDLE_PATH="certs"``` 

configurations and download the .pem files from the Amazon url cited above, my `mbedtls.a` component is now around 30kB big -- does not work with Amazon, even though the compilation shows that certificates were bundled.

Please consider the use of Amazon certificates as an example, since they provide the certificates an all types of links (valid, revoked and invalid). My final use case could be that I want my application to only validate URLs with the set of certificates I've chosen, and with the tiniest amount of flash overhead possible.

Should this be possible? If so, is there a bug or am I doing something wrong?

**Comment by herculanodavi** [comment]
Thanks a lot! This solves my issue.
