### ISSUE TITLE
Removing spurious \n in ESP_LOG calls? (IDFGH-10197)

### ISSUE THREAD

**Issue by mickeyl** [espressif/esp-idf#11465]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

I noticed some of the components calling ESP_LOGx with '\n' as the last character, e.g.:

```
./bt/controller/esp32c3/bt.c:    ESP_LOGI(BT_LOG_TAG, "Bluetooth MAC: %02x:%02x:%02x:%02x:%02x:%02x\n",
```

This leads to unwanted empty lines in the log. My guess is that they have been (auto-)converted from `printf` without adjusting the line ending. Would you accept a pull request that removes these additional line feed characters?

**Comment by kriegste** [comment]
I remember, a while ago I enabled lwip debugging and there were a lot of empty lines in the log, too.
