### ISSUE TITLE
Build crosstool-ng on MACOS

### ISSUE THREAD

**Issue by lesnerd** [espressif/esp-idf#1147]
I try to build on MacOS High Sierra but I get the same error each time.

`Running autoconf...`
`./bootstrap: line 5: autoconf: command not found`
`make: *** [build/esp32/Makefile] Error 127`

I added to my bash_profile these:

export PATH=$PATH:$/Users/lesnerd/LunaNodeESP32/toolchains/esp32/bin
export PATH=$PATH:$/Users/lesnerd/LunaNodeESP32/toolchains/esp32/xtensa-esp32-elf/bin
export IDF_PATH=$/Users/lesnerd/LunaNodeESP32/toolchains/esp-idf

What am I missing?

**Comment by igrr** [comment]
You are missing dependencies for crosstool-NG. These are mentioned in the setup guide, under "install dependencies":
http://esp-idf.readthedocs.io/en/latest/get-started/macos-setup-scratch.html#compile-the-toolchain-from-source
