### ISSUE TITLE
esp_log_level_set() isn't taking effect, but problem is deeper than the function itself

### ISSUE THREAD

**Issue by moefear85** [espressif/esp-idf#11473]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

latest mater

### Operating System used.

Linux

### How did you build your project?

VS Code IDE

### If you are using Windows, please specify command line type.

None

### Development Kit.

esp32 rev1 module

### Power Supply used.

External 3.3V

### What is the expected behavior?

When I call esp_log_level_set(...), I expect it to immediately set the log level or save the name.

### What is the actual behavior?

Instead it sometimes takes effect, in others it doesn't.

### Steps to reproduce.

I don't currently have a minimal example, but I have a parser loop that takes statements from the serial line, and if a certain command tells it to set the log level for a specific tag to some value, then `esp_log_level_set()` is called on that tag name and the given level is set. I'm coding in C++. However I realized it doesn't take effect when called from within that particular parser loop except for a single specific tag, which is the tag that the parser loop itself uses to log its behavior to serial.

It isn't crashing the system, but it's strange. I've placed many extensive logging statements within the parser loop before and after the call to `esp_log_level_set` to ensure that I am actually passing the correct tag name and level that I think I am, so I'm absolutely sure I'm not making any mistake. I'm passing valid tag pointers to the function, but not seeing any effect until a restart, when the main() function applies the same level settings to all the tags at start.

I inserted some printf() statements into the esp_log_level_set() function, to determine what is going on. I'm calling it several times for the exact same tag and level. See the output under Debug Logs.

You'll notice, it is finding the entry, but the first time at index 16. After that it consistently finds it at another index 7. This pattern repeats itself even after restarting the system multiple times. I'm not changing anything during the tests, and the entries count is remaining constant.

Either way, it is having no effect. At startup, for this particular tag, it is initially set to verbose. Even after setting it to level 2 (warn), that tag continues to produce log outputs at the level of verbose.

### Debug Logs.

log: match found
log: searching cache. entries: 31
log: cache entry found, i: 16. set level to: 2
...

log: match found
log: searching cache. entries: 31
log: cache entry found, i: 7. set level to: 2

...

log: match found
log: searching cache. entries: 31
log: cache entry found, i: 7. set level to: 2

### More Information.

Here are the inserted printf() statements:

```

void esp_log_level_set(const char *tag, esp_log_level_t level)
{
    esp_log_impl_lock();

    // for wildcard tag, remove all linked list items and clear the cache
    if (strcmp(tag, "*") == 0) {
        esp_log_default_level = level;
        clear_log_level_list();
        esp_log_impl_unlock();
        return;
    }

    // search for existing tag
    uncached_tag_entry_t *it = NULL;
    SLIST_FOREACH(it, &s_log_tags, entries)
    {
        if (strcmp(it->tag, tag) == 0)
        {
            printf("log: match found\n");
            // one tag in the linked list matched, update the level
            it->level = level;
            // quit with it != NULL
            break;
        }
    }
    // no existing tag, append new one
    if (it == NULL)
    {
        printf("log: match not found\n");
        // allocate new linked list entry and append it to the head of the list
        size_t tag_len = strlen(tag) + 1;
        size_t entry_size = offsetof(uncached_tag_entry_t, tag) + tag_len;
        printf("log: tag_len: %u, entry_size: %u\n",tag_len,entry_size);
        uncached_tag_entry_t *new_entry = (uncached_tag_entry_t *) malloc(entry_size);
        if (!new_entry) {
            esp_log_impl_unlock();
            return;
        }
        new_entry->level = (uint8_t) level;
        memcpy(new_entry->tag, tag, tag_len); // we know the size and strncpy would trigger a compiler warning here
        SLIST_INSERT_HEAD(&s_log_tags, new_entry, entries);
    }

    // search in the cache and update the entry it if exists
    printf("log: searching cache. entries: %lu\n",s_log_cache_entry_count);
    for (uint32_t i = 0; i < s_log_cache_entry_count; ++i)
    {
#ifdef LOG_BUILTIN_CHECKS
        assert(i == 0 || s_log_cache[(i - 1) / 2].generation < s_log_cache[i].generation);
#endif
        if (strcmp(s_log_cache[i].tag, tag) == 0)
        {
            s_log_cache[i].level = level;
            printf("log: cache entry found, i: %lu. set level to: %u\n",i,level);
            break;
        }
    }
    esp_log_impl_unlock();
}
``

_No response_

**Comment by moefear85** [comment]
When `esp_log_level_set()` actually uses the passed name to set the level, does it actually compare the string literals themselves, or does it just look at the address of the pointer?

**Comment by igrr** [comment]
This sounds very similar to https://github.com/espressif/esp-idf/issues/8567, which has been reported a while ago but we haven't found way of reproducing, IIRC.

(There has been an issue of comparing tag pointers rather than values, however it was fixed a long time ago in 750c8c00c89f3911692c37494c2eb8401cd5308e)

**Comment by moefear85** [comment]
@igrr 

I modified the issue. Please read the updates.

**Comment by moefear85** [comment]
fine, but please mark that as active & reproducible, as it is corroborated by more than one user

**Comment by igrr** [comment]
Yeah, that other one is "Selected for development", just the priority is relatively low because it relates to a non-standard use of ESP_LOG (dynamic tag strings).
