### ISSUE TITLE
USB Mass Storage Class example doesn't flash properly (IDFGH-10215)

### ISSUE THREAD

**Issue by fulalas** [espressif/esp-idf#11481]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v5.2-dev-703-gefe919275e

### Operating System used.

Linux

### How did you build your project?

Command line with idf.py

### If you are using Windows, please specify command line type.

None

### Development Kit.

ESP32-S3

### Power Supply used.

USB

### What is the expected behavior?

I compiled [this project](https://github.com/espressif/esp-idf/tree/efe919275e8f4516ffd5f99f9a59e9d3efbae281/examples/peripherals/usb/host/msc) and successfully flashed it to /dev/ttyACM0, but then it seems the ESP32-S3 didn't restart properly (blank screen) and the build process got stuck waiting for the device to restart. I tried to unplug ESP32-S3 and plug again, but nothing changed. I can't flash the project anymore because /dev/ttyACM0 doesn't exist anymore (`A fatal error occurred: Could not open /dev/ttyACM0, the port doesn't exist`).

### What is the actual behavior?

The program should run and read the text file from the USB stick that is connected to ESP32-S3.

### Steps to reproduce.

Just install the dev enviroment and build [this project](https://github.com/espressif/esp-idf/tree/efe919275e8f4516ffd5f99f9a59e9d3efbae281/examples/peripherals/usb/host/msc) using `idf.py -p /dev/ttyACM0 flash monitor`

### More Information.

I'm using Slackware 15.0.

**Comment by tore-espressif** [comment]
Hello @fulalas , what development board did you use? The symptoms indicate that you flash the program via USB-Serial-JTAG.

USB features and USB-Serial-JTAG are mutually exclusive. Either you use USB for flashing of ESP32-S3, or you use USB-OTG features, such as the MSC driver

**Comment by fulalas** [comment]
Hi! I have the [ESP32-S3-USB-OTG_SUB V2.0](https://espressif-docs.readthedocs-hosted.com/projects/esp-dev-kits/en/latest/esp32s3/esp32-s3-usb-otg/user_guide.html) one.

Yeah, there's a USB dev and a USB-UART0 (mini-USB) ports. I'm not sure how to proceed.

**Comment by tore-espressif** [comment]
For this particular case, you have to use the USB-UART0 connector for program flashing, and the USB host connector for interfacing your flash drive.

As you can see from the [schematic](https://espressif-docs.readthedocs-hosted.com/projects/esp-dev-kits/en/latest/_static/esp32-s3-usb-otg/schematics/SCH_ESP32-S3_USB_OTG.pdf) you will need extra steps to configure your board for USB Host mode. We provide helper function in ESP32-S3-USB-OTG [Board Support Package](https://github.com/espressif/esp-bsp/blob/master/esp32_s3_usb_otg/esp32_s3_usb_otg.c). 
You must call `bsp_usb_mode_select_host()` and `bsp_usb_host_power_mode(BSP_USB_HOST_POWER_MODE_USB_DEV, true)`

I'm sorry for the inconvenience, we are working on more seamless experimenting with USB Host examples

**Comment by fulalas** [comment]
OK. I adapted the code to include the 2 methods you mentioned. This is the relevant part (hint: `// Configure board for host mode`):

```
void app_main(void)
{
    msc_host_device_handle_t msc_device;
    msc_host_vfs_handle_t vfs_handle;
    msc_host_device_info_t info;
    BaseType_t task_created;

    const gpio_config_t input_pin = {
        .pin_bit_mask = BIT64(USB_DISCONNECT_PIN),
        .mode = GPIO_MODE_INPUT,
        .pull_up_en = GPIO_PULLUP_ENABLE,
    };
    ESP_ERROR_CHECK( gpio_config(&input_pin) );

    usb_flags = xEventGroupCreate();
    assert(usb_flags);
    
    // Configure board for host mode
    bsp_usb_mode_select_host();
    bsp_usb_host_power_mode(BSP_USB_HOST_POWER_MODE_USB_DEV, false);

    [...]
```

It compiles and flashes to the device, however the output is stuck at `I (467) example: Waiting for USB stick to be connected`. I tried to unplug and plug the USB stick and also resetting the device, but the output doesn't change.

**Comment by tore-espressif** [comment]
Could you please set the second argument of this call `bspp_usb_host_power_mode(BSP_USB_HOST_POWER_MODE_USB_DEV, false);` to true?

**Comment by fulalas** [comment]
I tried it, but the result is the same. :(

**Comment by tore-espressif** [comment]
> I tried it, but the result is the same. :(

I'm sorry I forgot one last thing: this call `bsp_usb_host_power_mode(BSP_USB_HOST_POWER_MODE_USB_DEV, true);` configures the board that the USB host port is powered from USB device port. So in your case you must:

1. Plug the USB device connector to PC
2. Connect to USB-UART0 connector with USB cable to PC
3. Plug USB flash disk to USB host connector

**Comment by fulalas** [comment]
I see now. It's working, finally! So the USB A connector powers the USB stick while the mini-USB is to flash the application?

**Comment by tore-espressif** [comment]
> I see now. It's working, finally! So the USB A connector powers the USB stick while the mini-USB is to flash the application?

Correct, I'm happy it works now :) Can we close this issue?

**Comment by fulalas** [comment]
Sure. Thanks!

**Comment by porteux** [comment]
Sorry to bring this up again, but is there any similar example using Rust?

**Comment by georgik** [comment]
@porteux Regarding Rust no_std, you can find some examples with initial USB support here: https://github.com/esp-rs/esp-hal/tree/main/esp32s3-hal/examples
The implementation is still in progress. The current state of support for Rust Bare Metal peripherals is here: https://github.com/esp-rs/esp-hal/issues/19

If you're targeting Rust std with ESP-IDF, then it should be possible to use API from ESP-IDF, but no USB-related examples have been published by the community yet: https://github.com/esp-rs/esp-idf-hal/tree/master/examples

**Comment by porteux** [comment]
@georgik, thanks a lot!

**Comment by Ina1413** [comment]
sorry to reopen, but how do you interface a ESP32-S3-WROOM-1 with the tusb msc example (https://github.com/espressif/esp-idf/tree/master/examples/peripherals/usb/device/tusb_msc)? 

Under my assumption, I can flash with a USB cable connected to the microUSB port and then that same cable will allow me to access the board as a mass storage device on my PC.

I've also been looking into this example: https://github.com/espressif/esp-iot-solution/tree/master/examples/usb/device/usb_msc_wireless_disk but have the same questions on physical setup.

Essentially, can I use the same cable for flashing and accessing as MSC or do I have to hook up one of these: https://a.co/d/62fJOIy to the ESP board and then plug it into my laptop.

Any clarification would help so much thanks!

**Comment by tore-espressif** [comment]
@Ina1413 Almost all S3 devkits have 2 USB ports. One is for flashing/logging the other one offers USB functionality.

![Image](https://github.com/user-attachments/assets/7dac1e69-5cb6-4d29-9e87-640e7d48a6d9)

If your devkit does not have 2 USB ports, you will have to connect an external USB connector to pins 19 and 20
