### ISSUE TITLE
How can we have a better development experience? (IDFGH-10234)

### ISSUE THREAD

**Issue by hzhh110** [espressif/esp-idf#11498]
### Is your feature request related to a problem?

![Snip20230525_4](https://github.com/espressif/esp-idf/assets/19906209/1e9fcb35-336d-4593-88fe-2ee74afb7204)

How can we have a better development experience?With VSCODE + IDF,Found all kinds of explosion, indeed can also be compiled, but this development experience is very bad, how can we jump to the function, and less explosion?

**Comment by suda-morris** [comment]
> how can we jump to the function

You may need to read this https://code.visualstudio.com/docs/cpp/c-cpp-properties-schema-reference first, pay attention to the `compileCommands`, it should be set to the path of the `compile_commands.json` file that generated by the esp-idf build system. e.g. `"${workspaceFolder}/examples/peripherals/lcd/mipi/build/compile_commands.json"`
