### ISSUE TITLE
ESP32 C3 mini computer connection (IDFGH-10230)

### ISSUE THREAD

**Issue by TorciaElettrica** [espressif/esp-idf#11495]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Hello everyone,
I have a pcb with a usb c connector and an esp32 c3 mini.
I would like to insert a code into the esp32 using arduino but my computer does not recognise the pcb connected by usb c. I have tried using different computers and different usb c's on mac and windows. 
What could the problem be?

thanks in advance.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, please create a post on our forum at https://esp32.com. Will close now. Thanks.
