### ISSUE TITLE
`esp_get_idf_version()` gives incorrect SDK version (IDFGH-10229)

### ISSUE THREAD

**Issue by ascillato** [espressif/esp-idf#11493]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

Release v5.0.2

### Operating System used.

Linux

### How did you build your project?

VS Code IDE

### If you are using Windows, please specify command line type.

None

### Development Kit.

ESP32-WROOM-32E

### Power Supply used.

USB

### What is the expected behavior?

In the esp-idf **v5.0.2**, the command `esp_get_idf_version()` gives **5.0.1** but ESP_IDF_VERSION_MAJOR, ESP_IDF_VERSION_MINOR, ESP_IDF_VERSION_PATCH gives **5.0.2**

Seems to be some sort of bug on `esp_get_idf_version()`

### What is the actual behavior?

That `esp_get_idf_version()` and ESP_IDF_VERSION_MAJOR, ESP_IDF_VERSION_MINOR, ESP_IDF_VERSION_PATCH gave the same esp-idf version

### Steps to reproduce.

printf the output of `esp_get_idf_version()` and ESP_IDF_VERSION_MAJOR, ESP_IDF_VERSION_MINOR, ESP_IDF_VERSION_PATCH and compare the outputs

### Debug Logs.

```plain
esp_get_idf_version() gives 5.0.1

ESP_IDF_VERSION_MAJOR, ESP_IDF_VERSION_MINOR, ESP_IDF_VERSION_PATCH gives 5.0.2
```

**Comment by ESP-Marius** [comment]
Not sure how you would end up with `5.0.1`, `esp_get_idf_version()` just gets the output from `git describe` (and gives `5.0.2` on v5.0.2 when I tested right now).

What do you get when you run `git describe` in your `esp-idf` repo? Do you by any chance have `version.txt` file in your idf folder? (this can override the git describe output)

**Comment by ascillato** [comment]
> Do you by any chance have version.txt file in your idf folder? (this can override the git describe output)

oh, you are right. removing that solves this issue. Thank you so much for your fast response. Closing.
