### ISSUE TITLE
Suggestion: Rename the rmt_set_evt_intr_en() function

### ISSUE THREAD

**Issue by nkolban** [espressif/esp-idf#115]
Examining the new RMT driver APIs I find the function called "rmt_set_evt_intr_en()".  If I am understanding this correctly, this causes an interrupt to be generated when the transmitter passes a threshold of sent items so that we can populate new buffer data before running out of data to send.  Looking in the Technical Reference, we seem to see that the name of this is event is `RMT_CHn_TX_THR_EVENT_INT`.    Accordingly,  the "type" of interrupt is a "Threshold Event" or a "THR_EVENT" interrupt.  The pattern of names for the functions to enable an interrupt appears to be `rmt_set_<NAME>_intr_en`.   As such, the currently chosen name of the format `rmt_set_evt_intr_en` would lead us to believe that this is an "event" interrupt ... which is very vague.   I'd like to suggest the following as possible alternative names:

* `rmt_set_thr_evt_intr_en()`
or
* `rmt_set_thr_intr_en()`
or
* `rmt_set_thresh_intr_en()`

**Comment by negativekelvin** [comment]
Or just try to match the bit name

`rmt_set_tx_thr_evt_intr_en`
