### ISSUE TITLE
Missing free in ws_echo_server (IDFGH-10244)

### ISSUE THREAD

**Issue by masterxq** [espressif/esp-idf#11507]
https://github.com/espressif/esp-idf/blob/f8d2c0894cf3c12dc231dafebf75d3f1002b312c/examples/protocols/http_server/ws_echo_server/main/ws_echo_server.c#L60

If function fails the memory is lost and will never be freed.

**Comment by ESP-YJM** [comment]
@masterxq Thanks for reporting. We will fix it.
