### ISSUE TITLE
I NEED TO TM1621 EXAMPLE FOR ESP-IDF (IDFGH-10258)

### ISSUE THREAD

**Issue by cyberumut** [espressif/esp-idf#11520]
IS ESP IDF DRIVER AVAILABLE FOR TM1621

**Comment by wujiangang** [comment]
Hi, @cyberumut, we can consider adding this to our development queue. However, we currently do not have any plans to support this LCD controller in the coming months.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, feel free to reopen.
