### ISSUE TITLE
wifi endless reconnects & missing hostname-length asserts/checks in dhcp module & sdkconfig, causing crash (IDFGH-10263)

### ISSUE THREAD

**Issue by moefear85** [espressif/esp-idf#11525]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

latest master

### Operating System used.

Windows

### How did you build your project?

VS Code IDE

### If you are using Windows, please specify command line type.

None

### Development Kit.

esp32s2 module

### Power Supply used.

External 3.3V

### What is the expected behavior?

run

### What is the actual behavior?

crashes

### Steps to reproduce.

I simply flashed the standard wifi-sta example without any modifications, but using my own sdkconfig, where I enable heap debugging. It exposed a memory leak, see logs.
[debug.txt](https://github.com/espressif/esp-idf/files/11585267/debug.txt)
[sdkconfig.txt](https://github.com/espressif/esp-idf/files/11585269/sdkconfig.txt)

### More Information.

There seem to be multiple factors at play here.  First of all, I've noticed that I frequently get linker errors about missing symbols (functions can't be found), that didn't happen before, even when the code is right. Sometimes small irrelevant changes in code or attempts to recompile resolve it, but I've hit a case where it won't go away. 
    I flashed a wifi-sta example on to one esp32s2, and wifi-ap example on to another. After various small changes here and there, the wifi-ap project stopped compiling due to the linker error. See the attached code files. The AP project is in the state where it stopped linking. See the log "error - AP linking.log". The code file is below.
    This leads me to the feature request, of separating changes to the compilers/toolkit, from changes to the sdk. Because when pulling a new commit, one often is forced to use new compilers/toolkit, such that when problems arise, it is hard to know if this is because of the compilers/toolkit, or because of logic errors in the sdk. This case here might be easy to attribute to the compiler, but see below for the Guru Meditation Issue, which isn't so clear.

[error- AP linking.log](https://github.com/espressif/esp-idf/files/11585599/error-.AP.linking.log)

   Another problem, is that after several successful reconnection attempts by the STA to the AP (usually after reflashing or resetting the chip), then it gets stuck in a reconnection loop. see the code files & logs. This isn't supposed to be happening, since nothing is changing. I wonder if the AP is hitting its max connected client limit, but here these are all the same station, identifiable by its mac address, and it is only one. So either the AP is unable to differentiate resets/reconnects of the same node, or there is another bug somewhere. This is hard to find as the wifi libraries are binary.

[softap_example_main.c.txt](https://github.com/espressif/esp-idf/files/11585596/softap_example_main.c.txt)
[station_example_main.c.txt](https://github.com/espressif/esp-idf/files/11585597/station_example_main.c.txt)
[error - Reconnect.log](https://github.com/espressif/esp-idf/files/11585640/error.-.Reconnect.log)

  Now comes the Guru Meditation Problem. There seems to be a bug in dhcp, because often in this example project, but also in another project I'm working on, that also connects to this particular AP, then given it often gets stuck in a reconnect loop as mentioned above, but when a connection succeeds, it is then immediately followed by a crash. In fact it was the crashing that led me to create a simple AP<->STA test based on the examples, to rule out errors in my own project.
    I turned on heap debugging and that's what exposed this. It is possible to get the project to not crash in most cases, when I disable all the safeguards. There are no other running tasks, and all the code does is attempt to connect to wifi. Everything else is commented out. Yet still it crashes.

[error 3 - Guru Meditation Error.log](https://github.com/espressif/esp-idf/files/11585652/error.3.-.Guru.Meditation.Error.log)
[error 2 - Guru Meditation Error.log](https://github.com/espressif/esp-idf/files/11585653/error.2.-.Guru.Meditation.Error.log)
[error - Guru Meditation Error.log](https://github.com/espressif/esp-idf/files/11585654/error.-.Guru.Meditation.Error.log)

I'll try other branches/commits later and mention anything relevant.

This morning I tried my original project with v5.1. Am I using the event subsystem wrong? To be exact, the error happens here (at the STA) when the AP is reset after a successful connection.
[source.cpp.txt](https://github.com/espressif/esp-idf/files/11590048/source.cpp.txt)
[error.log](https://github.com/espressif/esp-idf/files/11590050/error.log)
[handlers.cpp.txt](https://github.com/espressif/esp-idf/files/11590084/handlers.cpp.txt)

hmmm... After trying v4.4 on my project, it throws a dhcp assert error that states my hostname is too long. After shortening it just enough, it worked flawlessly, as did latest master. I'm not sure all above issues are reducible to just that, but it is clear v5 has lost an important assert present in v4.4. Even better would be an sdkconfig rule to limit the length.

Nope.. nope... I can confirm... the crashing is gone.. but the STA still gets stuck in a reconnect loop after a certain number of restarts, and it is the AP that is responsible. It is not a hostname-length issue.

Some re-searching revealed, the reconnect issue might have the same cause as other heap corruption issues on wifi reconnect, in that the AP does't recognize that the same station has reconnected, if the station resets and reconnects too fast. Is it too difficult to make the AP look at the MAC and be aware that a station might reset and reconnect at any moment, and properly react to that situation, so that the station can reset indefinately often without problems?

**Comment by xueyunfei998** [comment]
hi @moefear85 
To sum up your first question above.
1 The problem of stepping on memory
2 The hostname is too long, which leads to assert. 

rigth？

**Comment by moefear85** [comment]
nr.2 is correct, leads to heap corruption, missing assert.

nr.2: there is bug in AP logic, so after several successful reconnects of a sta, the AP begins endlessly rejecting further reconnects for no reason (despite only 2 stations). I don't know if it is because memory issue, but it is present even when hostname is proper length.
