### ISSUE TITLE
adc_continuos.h no such file or directory (IDFGH-10267)

### ISSUE THREAD

**Issue by monurbstnc** [espressif/esp-idf#11530]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Hello,

When I try to use adc with tinyusb example I got error  
No such file or directory
   17 | #include "esp_adc/adc_continuous.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~

I have also tinyusb component in my project. Should I configure some settings? How should I solve this problem?
IDF version : 5.1

Update: I tried a new adc example which is adc continuos reading, It worked but when I try to configure adc with tiny usb project I got same error.
Thanks for your helps

**Comment by suda-morris** [comment]
From which component are you initializing the ADC driver? Can you check if that component has added the `esp_adc` as its requirement? usually, it will look like this:

```
idf_component_register(SRCS ${srcs}
                       INCLUDE_DIRS ${includes}
                       REQUIRES driver esp_adc)
```

**Comment by monurbstnc** [comment]
> From which component are you initializing the ADC driver? Can you check if that component has added the `esp_adc` as its requirement? usually, it will look like this:
> 
> ```
> idf_component_register(SRCS ${srcs}
>                        INCLUDE_DIRS ${includes}
>                        REQUIRES driver esp_adc)
> ```

Thank you ıt worked for me
