### ISSUE TITLE
Set OTA on NINA W106 00B (IDFGH-10292)

### ISSUE THREAD

**Issue by zapsalis** [espressif/esp-idf#11553]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Hi,

I am currently using an evalkit **Nina W106-00B** board that incorporates an **ESP32-D0WD-V3**, I use **esp-idf tools 2.16**.

I am desperately trying to implement OTA (Over-The-Air) updates.

I started by modifying my partitions.csv file, which looks like this (without OTA) and works well:

```
nvs, data, nvs, 0x9000, 0x6000,
phy_init, data, phy, 0xf000, 0x1000,
factory, app, factory, 0x10000, 1M,
storage, data, spiffs, , 0xF0000,
```

The “factory” partition corresponds to my .bin file containing the code.
The “storage” partition corresponds to my .bin file containing the web pages and .js files.

I tried to modify it so that when I add a new .bin file containing the code, it goes into the “ota_0” partition, for example, and then boots without using the “factory” partition.

This is what it looks like now:

```
nvs, data, nvs, 0x9000, 0x6000,
otadata, data, ota, 0xf000, 0x2000,
phy_init, data, phy, 0x11000, 0x1000,
factory, app, factory, 0x20000, 1M,
storage, data, spiffs, 0x120000, 0xF0000,
ota_0, app, ota_0, 0x210000, 1M,
ota_1, app, ota_1, 0x310000, 1M,
```

I can compile and flash it, but when I start my board, an error message appears in the logs:

```
ELF file SHA256: 73241a5f6639ca7a

Rebooting…
ets Jul 29 2019 12:21:46

rst:0xc (SW_CPU_RESET),boot:0x33 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1256
load:0x40078000,len:13276
ho 0 tail 12 room 4
load:0x40080400,len:3032
entry 0x40080598

assert failed: do_core_init startup.c:339 (flash_ret == ESP_OK)

Backtrace: 0x40081ee2:0x3ffe3a90 0x4008a4bd:0x3ffe3ab0 0x40090fdd:0x3ffe3ad0 0x400d2a13:0x3ffe3bf0 0x400d2abe:0x3ffe3c10 0x4008165e:0x3ffe3c40 0x4007927e:0x3ffe3c90 |<-CORRUPTED
```

This message keeps looping, and the board attempts to restart without success.

I attach my [sdkconfig](https://github.com/espressif/esp-idf/files/11610613/sdkconfig.txt).

How should I modify my partitions.csv file for it to work correctly?

Thanks,
Zapsalis

**Comment by hmalpani** [comment]
Hello @zapsalis 

I tried building an example with the above mentioned partition table and the sdkconfig file you shared. I was able to build and run it successfully. I didn't get the assert failure which you are experiencing. Can you share the idf version on which you are facing this issue?

**Comment by zapsalis** [comment]
Hi @hmalpani,

Thanks for your answer, i found my problem, i had 8MB config for my flashsize instead of 4MB.

Now I'm trying to download a binary file, but i can't download a file more than 100Ko else my malloc() not work and go to NULL.

**Comment by hmalpani** [comment]
Hello @zapsalis 
Can you try building and running the [simple_ota_example](https://github.com/espressif/esp-idf/tree/master/examples/system/ota/simple_ota_example) present in idf on your setup and let me know if that works? 
Can you also share the example you are trying to build and run?

**Comment by hmalpani** [comment]
Hello @zapsalis 
Any updates on this?

**Comment by hmalpani** [comment]
Closing this issue. Please feel free to reopen

**Comment by zapsalis** [comment]
Hello @hmalpani,

Sorry to answer late, I had moved on to another part of the project and had therefore set aside the fota.

I can show you my example i try to build, but I don't know if it will help you to find my problem.

I have a html et js part, which create the button on the web page to download my file.

Once done, my download data is send to the http server with post request.

When i get the data i try this : 

`static esp_err_t cb_root_post_handler(httpd_req_t *i_psHttpRequestContent)
{
	char lac_buf[10] ="";

	ESP_LOGI(TAG, "cb_root_post_handler i_psHttpRequestContent->uri=[%s]", i_psHttpRequestContent->uri);

	// Check if the request method is POST
	if (i_psHttpRequestContent->method != HTTP_POST)
	{
		// Return 405 if the method is not allowed
		ESP_LOGI(TAG, "not post request, [%d]", i_psHttpRequestContent->method);
		return ESP_ERR_INVALID_RESPONSE;
	}
	else
	{
		ESP_LOGI(TAG, "OK post request, [%d]", i_psHttpRequestContent->method);
	}

	ESP_LOGI(TAG, "cb_root_post_handler content length %d", i_psHttpRequestContent->content_len);

	char *l_pcDataBuffer = malloc(i_psHttpRequestContent->content_len + 1);
	
	...
	...
	...
}`

But the problem is there `char *l_pcDataBuffer = malloc(i_psHttpRequestContent->content_len + 1);`
Because when my file is 100 MB or less that's good but if it's higher the malloc not work.

Here the Handler for the post : 

`/* URI handler for post */

	httpd_uri_t _cb_root_post_handler = {
		.uri = "/post/*",
		.method = HTTP_POST,
		.handler = cb_root_post_handler,
		//.user_ctx  = server_data	// Pass server data as context
	};
	httpd_register_uri_handler(server, &_cb_root_post_handler);`

And this handler is in http_start_server() and this one is called in the http_server_task() called like that : 
`xTaskCreate(http_server_task, "http_server_task", 1024*6, (void *)cparam0, 2, NULL);`

Thanks very much,
Zapsalis.

**Comment by hmalpani** [comment]
Hello @zapsalis 

If I understand your problem above, you are creating a HTTP server on ESP32 and then posting the new firmware image to the server. I think you can refer to [HTTP Server OTA](https://github.com/hmalpani/HTTP_Server_OTA) where I have implemented a similar way to do OTA.

Please let me know if I misunderstood the problem you are facing or if the suggestion works for you.

**Comment by zapsalis** [comment]
Hello @hmalpani 

Yes you understood what i try. I have created HTTP server on Nina W106 (ESP32 embedeed), and i try to dowload new binay on web page.

But the problem was the size of the binay. So in js when i upload a binay more than 50KB I chunk it and i send only 50KB chunk, and  in the header i send if it's the last chunk or not to know if i need to restart the modem.

When i try with a 80KB file (txt file) for example it success and i get each time the parameters to know if it's the last chunk or not and I got "fasle" for the first one and "true" for the second one (last one), but if I try with binary file I have failure because, in the binary can have 'NUL' char, so I need to send in javascript to my server the binary file.

My function in js to send : 

```
function UploadFile(element) {
	return new Promise((resolve, reject) => {
		document.getElementById("waiting-text").innerHTML = "Uploading file. Please wait...";
		document.getElementById("loading-bar").classList.remove('hide');
		document.getElementById("overlay").classList.add('show');
		if (element.hasAttribute('ref')) {
			try {
				const file = document.getElementById(element.getAttribute('ref')).files[0];

				if (file == undefined) {
					reject({message:"No file selected!", reason:"Error 500"});
				} else {
					delete fetchOptions['headers'];
					const chunkSize = 50000;
					const apiURL	= isDev ? '/' : '/post/file';
					
					for (let start = 0; start < file.size; start += chunkSize) {
						const chunk = file.slice(start, start + chunkSize);
						const fd = new FormData();
						fd.set('name', element.getAttribute('ref'));
						fd.set('data', chunk);
						fd.set('lastChunk', start+chunkSize <= file.size?"false":"true");
						// console.log(`Chunk size: ${chunk.size}, last chunk: ${!(start+chunkSize <= file.size)}`);
						fetchWithTimeout(addToken(apiURL), {
							...fetchOptions,
							...{method: 'POST', mode: 'no-cors', credentials: 'omit', body: fd}
						})
						.then((response) => {
							console.log(response);
						})
						.catch((err) => {
							reject(err);
						});
					}
					// 3001 because animated progress bar lasts 3 sec (defined in CSS)
					setTimeout(function() {
						resolve("File successfully uploaded");
					}, 3001);
				}
			} catch (err) {
				reject({message:"An error occured while uploading file!", reason:err});
			}
		} else {
			reject({message:"An error occured while uploading file!", reason:"Error 500"});
		}
	});
}
```

```
async function fetchWithTimeout(resource, options = {}) {
	const { timeout = 5000 } = options; // 5 seconds

	const controller = new AbortController();
	const id = setTimeout(() => controller.abort(), timeout);
	const response = await fetch(resource, {
		...options,
		signal: controller.signal
	});
	clearTimeout(id);
	return response;
}
```

Thanks very much.
Zapsalis

**Comment by zapsalis** [comment]
Hi everyone,

I managed to recover my binary data sent by my js.

The problem was that I was processing with strstr, or strlen, except my data had '\0' in it, so that was a problem.

So I created a function strstr_bin allowing to look character by character (for loop), so that the '\0', are not a concern.

I can now write to my partition thanks to esp_ota_write(), however when I try to end the update with: esp_ota_end(), I have these errors in my logs:

```
esp_image: segment 0: paddr=00200020 vaddr=3f400020 size=254b0h (152752)
esp_image: segment 1: paddr=002254d8 vaddr=00000000 size=00000h (     0)  
esp_image: segment 2: paddr=002254e0 vaddr=00000000 size=00000h (     0)  
esp_image: segment 3: paddr=002254e8 vaddr=00000000 size=00000h (     0)  
esp_image: segment 4: paddr=002254f0 vaddr=00000000 size=00000h (     0)  
esp_image: segment 5: paddr=002254f8 vaddr=00000000 size=00000h (     0)  
esp_image: segment 6: paddr=00225500 vaddr=00000000 size=00000h (     0)  
esp_image: segment 7: paddr=00225508 vaddr=00000000 size=00000h (     0)  
esp_image: Checksum failed. Calculated 0x67 read 0x0
```

Thanks very much.
Zapsalis

**Comment by zapsalis** [comment]
Hi everyone, I update this post.

I found and solved my problem, the problem is that when retrieving my binary data, I searched for terminals, but one of these terminals was in the binary data. So I only had part of my file written in the partition, and therefore a false checksum.

Thanks very much everyone,
Zapsalis
