### ISSUE TITLE
Any BLE Mobile apps that support File Transfer Protocol with ESP32? (IDFGH-10307)

### ISSUE THREAD

**Issue by Vamshi253** [espressif/esp-idf#11566]
Hi, Are there any generic ble android apps that support file transfer protocol with ESP32? The apps that I have found on ios/Android are capable of just write/read data from/to ESP32. I know that in case of BLE, one need to send the whole file in chunks of data from/to between ESP32 and mobile app. Is there any app from Espressif or other vendors that can read all the chunks of data and assembles all the chunks into a file by default?

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to short of feedback, feel free to reopen with more updates.
