### ISSUE TITLE
ESP32 gets no IP and returns no error if esp_netif_create_default_wifi_sta() called before esp_event_loop_create_default() (IDFGH-10321)

### ISSUE THREAD

**Issue by mik13ST** [espressif/esp-idf#11580]
I am learning ESP32 and ESP-IDF. I was trying to make it connect to WiFi. I looked at the https://github.com/espressif/esp-idf/tree/master/examples/wifi/getting_started/station example and copied relevant method calls until things started working. In this code
```c
void wifi_init_sta(void)
{
    s_wifi_event_group = xEventGroupCreate();

    ESP_ERROR_CHECK(esp_netif_init());

    ESP_ERROR_CHECK(esp_event_loop_create_default());
    esp_netif_create_default_wifi_sta();

    wifi_init_config_t cfg = WIFI_INIT_CONFIG_DEFAULT();
    ESP_ERROR_CHECK(esp_wifi_init(&cfg));
```
I skipped `esp_event_loop_create_default()` because I didn't know why I need it at first. At a later point I found out why and added this call somewhere before `esp_event_handler_instance_register()` calls. This worked, I got the `WIFI_EVENT_STA_CONNECTED` event in my event handler (again, derived from the example), but I never got the `IP_EVENT_STA_GOT_IP` nor the device ever asked for IP (checked on my router). No runtime errors or warning logs were generated that would hint this being the problem.

I think this should result in an error of sorts. It's not obvious there is a tight coupling (or dependency) between these two methods and the example doesn't mention this tight coupling either. This was very difficult to troubleshoot for a beginner like me, I spent a couple of hours on this.

The reason for this call order requirement is because `esp_netif_create_default_wifi_sta()` calls `esp_event_handler_register()` which as a result relies on already existing event loop created by the user.

Also, the `esp_netif_create_default_wifi_sta` [documentation ](https://docs.espressif.com/projects/esp-idf/en/v5.0.2/esp32/api-reference/network/esp_netif.html#_CPPv433esp_netif_create_default_wifi_stav)doesn't mention this requirement either.

The implementation looks like [this](https://github.com/espressif/esp-idf/blob/903af13e847cd301e476d8b16b4ee1c21b30b5c6/components/esp_wifi/src/wifi_default.c#L382):
```c
/**
 * @brief User init default station (official API)
 */
esp_netif_t* esp_netif_create_default_wifi_sta(void)
{
    esp_netif_config_t cfg = ESP_NETIF_DEFAULT_WIFI_STA();
    esp_netif_t *netif = esp_netif_new(&cfg);
    assert(netif);
    esp_netif_attach_wifi_station(netif);
    esp_wifi_set_default_wifi_sta_handlers();
    return netif;
}
```

The `esp_wifi_set_default_wifi_sta_handlers()` call internally returns errors but this function doesn't handle them in any way. I think even `assert()` as seen in `assert(netif)` would be better than this. Please don't ignore errors.

An alternative could be the `esp_wifi_set_default_wifi_sta_handlers` function would create its own event loop so it wouldn't depend on the user's event loop.

**Comment by KaeLL** [comment]
Good point. Wi-Fi deinitialization has the same issue, where the order of function calls isn't clear.
