### ISSUE TITLE
rgb_panel_draw_bitmap ignores swap_xy and mirror options when bytes_per_pixel = 1  (IDFGH-10322)

### ISSUE THREAD

**Issue by omandine** [espressif/esp-idf#11581]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

5.0.2 and master

### Operating System used.

Windows

### How did you build your project?

Command line with idf.py

### If you are using Windows, please specify command line type.

CMD

### Development Kit.

Custom Board

### Power Supply used.

USB

### What is the expected behavior?

I have a 480x800 RGB module with 1 color byte per pixel  ; I want to use this screen in Landscape mode.
LVGL is configured to render image for 800x480 format.
ESP32 panel driver is configured with `.data_width = 8` and with` swap_xy `and `mirror x` to compute final position of pixels provided by LVGL buffer before saving them in its Frame Buffer.

**rgb_panel_draw_bitmap**() must swap_xy and mirror x when bytes_per_pixel = 1

### What is the actual behavior?

no copy done when _1 == bytes_per_pixel_.

_See current code:_
`if (do_copy) {`
..
`     if (2 == bytes_per_pixel) {`
... copy to frame buffer
`     } else if (3 == bytes_per_pixel) {`
... copy to frame buffer   
`    }`
`}`

Just add:
`__attribute__((always_inline))`
`static inline void copy_pixel_8bpp(uint8_t *to, const uint8_t *from)`
`{`
`    *to++ = *from++;`
`}`

and missing case for `if (2 == bytes_per_pixel) {` using `copy_pixel_8bpp()`

### Steps to reproduce.

1 - configure rgb pannel with  .data_width = 8
2 -  ESP_ERROR_CHECK(esp_lcd_panel_swap_xy(panel_handle,true));
       ESP_ERROR_CHECK(esp_lcd_panel_mirror(panel_handle,true,false));
3 - rgb_panel_draw_bitmap(...)

**Comment by suda-morris** [comment]
@omandine Thanks for reporting the issue and the detailed reproduce steps.
