### ISSUE TITLE
Bluetooth Modem Sleep Cannot be Enabled with 32kHz External Oscillator (IDFGH-10324)

### ISSUE THREAD

**Issue by therealergo** [espressif/esp-idf#11583]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v4.4.4

### Operating System used.

Windows

### How did you build your project?

Command line with idf.py

### If you are using Windows, please specify command line type.

PowerShell

### Development Kit.

N/A

### Power Supply used.

USB

### What is the expected behavior?

I should be able to enable Bluetooth Light Sleep using the external 32.768kHz clock when "External 32kHz oscillator at 32K_XN pin" is selected for "RTC clock source," since external 32kHz oscillators are precise enough to be used as a Bluetooth sleep clock source.

### What is the actual behavior?

Bluetooth Light Sleep may be enabled only when "RTC clock source" is set to "External 32kHz crystal."

### Steps to reproduce.

1. Set "RTC clock source" to "External 32kHz oscillator at 32K_XN pin."
2. Attempt to enable Bluetooth Light Sleep.

### More Information.

See [here](https://github.com/espressif/esp-idf/blob/903af13e847cd301e476d8b16b4ee1c21b30b5c6/components/bt/controller/esp32c3/Kconfig.in#L393)

**Comment by xiongweichao** [comment]
Hi @therealergo ,

Could you please provide the log and sdkconfig?

Thanks

**Comment by therealergo** [comment]
Hi @xiongweichao ,

I don't have any useful log to provide, and this will happen with the default (or any) sdkconfig.
To clarify, you cannot enable the Bluetooth Light Sleep option from menuconfig when "External 32kHz oscillator at 32K_XN pin" is selected for "RTC clock source."

If you look at the KConfig file linked under "More Information," this is because "RTC_CLK_SRC_EXT_CRYS" is marked as the dependency, even though the "External 32kHz oscillator at 32K_XN pin" option sets a different config value.

**Comment by xiongweichao** [comment]
Hi @therealergo ,

Since we haven't tested this feature, we can't guarantee that bluetooth will work properly. If necessary, you can implement this feature by modifying dependencies.

Thanks

**Comment by therealergo** [comment]
Hi @xiongweichao 

Is there any reason to believe that this is any different from the 32kHz crystal option w.r.t. Bluetooth? It is just different source settings for the exact same clock.

As far as I'm aware, there's no good way for me to sync in-source changes to ESP-IDF with my development team when using Espressif's tools (e.g. the ESP-IDF VS Code extension). Do you have any recommendations there?

**Comment by therealergo** [comment]
@xiongweichao

Yes -- We've tested this pretty extensively over the last year on a set of custom boards that use an external 20ppm tolerance 32.768kHz MEMS oscillator. No issues to report with Bluetooth connectivity.

**Comment by therealergo** [comment]
@xiongweichao Are there any plans to fix this issue?

**Comment by xiongweichao** [comment]
@therealergo Sorry for the late reply. This issue has been fixed in the [master](https://github.com/espressif/esp-idf/blob/master/components/bt/controller/esp32c3/Kconfig.in#L407) branch.

**Comment by therealergo** [comment]
@xiongweichao No worries, thanks for getting that fix in.
