### ISSUE TITLE
Define breaks c++ compilation (IDFGH-10376)

### ISSUE THREAD

**Issue by rfortunatov** [espressif/esp-idf#11634]
https://github.com/espressif/esp-idf/blob/4bc762621db30f253742bd3c439f80500fda0fb0/components/bt/porting/nimble/include/os/os.h#LL42C36-L42C36

This define break c++ compilation due to redefinition of standard macro. Purposing to rename this to MIN/MAX in order to preserve c++ standard macros and fix compilation

**Comment by rahult-github** [comment]
Hi @rfortunatov , 

We recently made a [fix](https://github.com/espressif/esp-idf/commit/6ace246ba2f7452a3f8d78006327870fe7d90600#diff-5e4c05aaba7ccef774ae7e7e6b604d9f14c1bee109db598f6624f0f3d75809fd) to handle this . Please sync to latest code.
