### ISSUE TITLE
ESP32 - Windows Setup Issue (IDFGH-10375)

### ISSUE THREAD

**Issue by ShizaShakeel-eaton** [espressif/esp-idf#11633]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Hi there,

      I am trying to setup the Espressif on Windows laptop. I am getting following error when I run the install.bat command:
![image](https://github.com/espressif/esp-idf/assets/134631464/80634243-9b0b-4c57-886d-16facce1284d)

I have made the following edit in the requirements.txt file:
![image](https://github.com/espressif/esp-idf/assets/134631464/c8221854-7760-486f-b563-050586603abe)

After following these steps, I am still getting the same error. 

**For convenience, Here is what in my requirements file:**

![image](https://github.com/espressif/esp-idf/assets/134631464/4d4f8b05-8a5b-4ad2-9b69-e43b5094bda0)

Can anyone please assist with this issue?

**Comment by dobairoland** [comment]
Probably this is what you are looking for: https://github.com/espressif/esp-idf/blob/release/v4.4/requirements.txt

But be aware, v4.3 is in maintenance period, that means it is not recommended for new designs. If you can then consider using a newer version which is still in service period.

**Comment by dobairoland** [comment]
I have double-checked that the fix has been backported to v4.3 as well: https://github.com/espressif/esp-idf/blob/release/v4.3/requirements.txt, here: https://github.com/espressif/esp-idf/commit/f9e52727279180f5f5ec4acb7996f01e92b40e06.
