### ISSUE TITLE
Abnormal exit while installing idf-driver-esp32-usb-jtag,Exit code: 0x2a (IDFGH-10382)

### ISSUE THREAD

**Issue by Huyuxizheng** [espressif/esp-idf#11639]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v5.0

### Operating System used.

Windows

### How did you build your project?

Command line with Make

### If you are using Windows, please specify command line type.

None

### What is the expected behavior?

Install the idf-driver-esp32-usb-jtag

### What is the actual behavior?

Connect the JTAG port of the ESP32C3 development board to the computer, if JTAG cannot be recognized, then use the powershell command “Install using Invoke-WebRequest 'https://dl.espressif.com/dl/idf-env/idf-env.exe' -OutFile .\idf-env.exe; .\idf-env.exe driver install --espressif” failed to install driver, exit code: 0x2a
Use espressif-ide-setup-2.9.1-with-esp-idf-5.0.1.exe to install the JTAG driver, but the installation also fails

### Steps to reproduce.

Install using Invoke-WebRequest 'https://dl.espressif.com/dl/idf-env/idf-env.exe' -OutFile .\idf-env.exe; .\idf-env.exe driver install --espressif 
Exit code: 0x2a

### Build or installation Logs.

```plain
>Invoke-WebRequest 'https://dl.espressif.com/dl/idf-env/idf-env.exe' -OutFile .\idf-env.exe; .\idf-env.exe driver install --espressif
Using cached archive: idf-driver-esp32-usb-jtag-2021-07-15.zip
Requesting elevation of privileges for: C:\Users\YU\idf-env.exe driver install --espressif --no-download
Exit code: 0x2a
```

### More Information.

win10

**Comment by kwcrawford** [comment]
Do Espressif ever research and fix these issues before closing?
