### ISSUE TITLE
IDF-v4.4.5 build warning in esp_ptr_in_drom (IDFGH-10398)

### ISSUE THREAD

**Issue by Andste82** [espressif/esp-idf#11653]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

a small bug has sneaked into the IDF v4.4.5, which leads to ugly warnings when building:

```bash
/esp-idf/components/soc/include/soc/soc_memory_types.h:140:25: warning: comparison of integer expressions of different signedness: 'intptr_t' {aka 'int'} and 'uint32_t' {aka 'unsigned int'} [-Wsign-compare]
     return ((intptr_t)p >= drom_start_addr && (intptr_t)p < SOC_DROM_HIGH);
             ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
```

**Comment by laukik-hase** [comment]
Hello, @Andste82!

Thank you for sending the issue report. I was investigating this issue but unfortunately could not reproduce it on the ESP-IDF `v4.4.5` tag.

We have suppressed all `Wsign-compare` warnings [here](https://github.com/espressif/esp-idf/blob/ac5d805d0eda75442dd17cfea5baaca9748f8215/tools/cmake/build.cmake#L105) - are you using any special C/CXX flags while compiling your example?

**Comment by Andste82** [comment]
Hi @laukik-hase 
thanks for you're response.

i use "vanilla" cmake in my projects because i don't like the "component magic" when using idf.py very well.
since the file with the warning is a header file, it is possible that my libs, with unsuppressed warnings, includes it. 

i usually build my libs as follows:
```cmake
target_compile_options(fancylib
	PRIVATE -Wall -Wextra -Wno-unused-parameter
)
```

the warning is not too bad, but since i want to handle every warning, and the headerfile is often included, the waning pops up very often during the build process.
