### ISSUE TITLE
cmake error (IDFGH-10403)

### ISSUE THREAD

**Issue by prabhu012** [espressif/esp-idf#11657]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v4.4

### Operating System used.

Windows

### How did you build your project?

Command line with Make

### If you are using Windows, please specify command line type.
cmd
### What is the expected behavior?

i am trying to make esp like alexa

### What is the actual behavior?
when I am trying to build i am getting this error

-- AUDIO_BOARD_PATH not defined
-- Configuring done
CMake Error:
  The detected version of Ninja () is less than the version of Ninja required
  by CMake (1.3).

CMake Warning:
  Manually-specified variables were not used by the project:

    CCACHE_ENABLE
    ESP_PLATFORM
    PYTHON_DEPS_CHECKED

CMake Generate step failed.  Build files cannot be regenerated correctly.
cmake failed with exit code 1

### Steps to reproduce.

1. Step
2. Step
3. Step
...

### Build or installation Logs.

C:\esp_idf\components\esp-va-sdk\examples\google_voice_assistant>idf.py build
Executing action: all (aliases: build)
Running cmake in directory C:\esp_idf\components\esp-va-sdk\examples\google_voice_assistant\build
Executing "cmake -G Ninja -DPYTHON_DEPS_CHECKED=1 -DESP_PLATFORM=1 -DCCACHE_ENABLE=1 C:\esp_idf\components\esp-va-sdk\examples\google_voice_assistant"...
-- AUDIO_BOARD_PATH not defined
-- Configuring done
CMake Error:
  The detected version of Ninja () is less than the version of Ninja required
  by CMake (1.3).

CMake Warning:
  Manually-specified variables were not used by the project:

    CCACHE_ENABLE
    ESP_PLATFORM
    PYTHON_DEPS_CHECKED

CMake Generate step failed.  Build files cannot be regenerated correctly.
cmake failed with exit code 1

C:\esp_idf\components\esp-va-sdk\examples\google_voice_assistant>

_No response_

**Comment by 9305128621** [comment]
> -- AUDIO_BOARD_PATH not defined
-- Configuring done
CMake Error:
  The detected version of Ninja () is less than the version of Ninja required
  by CMake (1.3).


CMake Warning:
  Manually-specified variables were not used by the project:

    ESP_PLATFORM
    PYTHON_DEPS_CHECKED

**Comment by prabhu012** [comment]
Thankyou Zikalino for replying

I have found it
ESP_PLATFORM:UNINITIALIZED=1
PYTHON_DEPS_CHECKED:UNINITIALIZED=1

Can you please explain in brief, what parameter I have to change to solve this error? I am new to this.

Thank you.

**Comment by sudeep-mohanty** [comment]
@9305128621 @prabhu012 Please try the solution suggested [here](https://github.com/espressif/esp-idf/issues/11730#issuecomment-1610946303)

**Comment by sudeep-mohanty** [comment]
Closing this issue with the resolution suggested [here](https://github.com/espressif/esp-idf/issues/11730#issuecomment-1610946303). Please feel free to open a new ticket for further reporting any new problems.
