### ISSUE TITLE
hostname settable for Wifi but apparently not for Ethernet (IDFGH-10422)

### ISSUE THREAD

**Issue by hagenbuch** [espressif/esp-idf#11676]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

I am using micropython but people tell me the issue has to do with the Espressif-API, so I ended up here:

I am able to set my own hostname

    network.hostname("myhostname")

which is then correctly used in the DHCP dialogue if I use Wifi.

On an ESP32, I can use Wifi and Ethernet at the same time but the Ethernet dialogue always uses "ESP32-POE" which seems to be set by Olimex, this is their product name of the hardware I am using (Olimex ESP32-POE Rev. b)

If you're not responsible, coould you kindly point my to some repo or forum where I could get help in fixing this?

Thank you for your great work at Espressif!

**Comment by nopnop2002** [comment]
Set the hostname of an interface.

esp_netif_set_hostname()
