### ISSUE TITLE
idf monitor: cyrillic symbols are broken (IDFGH-10437)

### ISSUE THREAD

**Issue by dibalavs** [espressif/esp-idf#11689]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v5.1-rc1-36-g4bc762621d

### Operating System used.

Windows

### How did you build your project?

Command line with idf.py

### If you are using Windows, please specify command line type.

PowerShell

### Development Kit.

custom board

### Power Supply used.

USB

### What is the expected behavior?

In idf.py monitor output - all cyrillic symbols are visible

### What is the actual behavior?

Instead of cyrillic symbols I got ?? symbols:

> ##CLI.NAMESET#: 8 ???????????? FM

### Steps to reproduce.

1. do export.ps1
2. idf.py monitor

### Debug Logs.

```plain
Also I tried to use idf.py script from platformio:

 "name": "framework-espidf",  
 "title": "Espressif IoT Development Framework", 
"version": "3.50000.0",   

With this version - all symbols are visible, no ?? symbols.
```

**Comment by radimkarnis** [comment]
We will take care of this in the [esp-idf-monitor](https://github.com/espressif/esp-idf-monitor/) project, please follow this issue: https://github.com/espressif/esp-idf-monitor/issues/1
