### ISSUE TITLE
MQTT Broker (IDFGH-10434)

### ISSUE THREAD

**Issue by JonRobo** [espressif/esp-idf#11687]
### Is your feature request related to a problem?

The esp idf mqtt component is fantastic as an mqtt client, but there is no support to make an mqtt broker

### Describe the solution you'd like.

Expand on the esp idf mqtt component to create an mqtt broker with at least MQTT version 3.1.1, using mqtt, websockets, and websocket secure.

The ESP32-WROVER modules can be especially good candidates for this application because of their increased RAM sizes, they should be able to support 50+ clients using small payloads.

### Describe alternatives you've considered.

The only way to achieve something like this today is with the help of the mongoose network library, but this is not at all optimized for the esp32 and requires a lot of work to configure correctly.

**Comment by AxelLin** [comment]
https://github.com/espressif/esp-idf/issues/10766
