### ISSUE TITLE
components/mdns: case insensitivity

### ISSUE THREAD

**Issue by SiarheiVolkau** [espressif/esp-idf#1169]
According to RFC 6762 all string should be case insensitive for US-ASCII codes only (see https://tools.ietf.org/html/rfc6762#section-16).

So, instead of strcmp you should use strcasecmp or convert all strings to lowercase before comparison.

**Comment by FayeY** [comment]
Hi, this issue will be fixed in the new mdns that is coming. Thanks for your reporting!
