### ISSUE TITLE
How to configure GPIOs in example code esp_http_client. (IDFGH-10472)

### ISSUE THREAD

**Issue by radhikaalpha** [espressif/esp-idf#11719]
I have installed eclipse ide. The versions of all related installed software are as follow,
Operating System: windows 10
            Java Runtime Version: 17.0.7+8-LTS-224
            Eclipse Version: 4.27.0.v20230302-0300
            Eclipse CDT Version: 11.1.1.202303201356
            IDF Eclipse Plugin Version: 2.10.0.202306060331

Created a project using existing example code esp_http_client for ESP32-S3-DevKitM-1.
I need to configure GPIOs in this project. Can you please share any reference for how to add/configure the pins in this example code.

**Comment by hmalpani** [comment]
Hello @radhikaalpha 
You can refer to [gpio examples](https://github.com/espressif/esp-idf/tree/master/examples/peripherals/gpio/) present in ESP-IDF to configure GPIOs.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, feel free to reopen.
