### ISSUE TITLE
esp_tls_conn_write() - TLS->SSL.conf set to 0? (IDFGH-10469)

### ISSUE THREAD

**Issue by bmkuter** [espressif/esp-idf#11716]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

I am trying to write via a TLS connection. I have previously run esp_tls_init() and esp_tls_conn_http_new_sync(), both of which returned successfully per their error codes. 

However when I try esp_tls_conn_write it returns with 0x7100 for bad parameters. Stepping into  the function, I see that eventually within esp_mbedtls_write() -> mbedtls_ssl_write(), the SSL member of the TLS pointer is set to 0, despite passing the init section without error. 

I based this code off of the https_request example, which ran with no errors. 

Anyone have any ideas?

**Comment by AdityaHPatwardhan** [comment]
Hi @bmkuter Can you please provide a sample code that is able to reproduce your issue correctly?

I think it would be better to take a look at the application before inferring about the cause of the issue.

I would suggest you make sure of following thing
1) Configuration structure for esp-tls has been set appropriately
2) Return values of `esp_tls_init()` and `esp_tls_conn_http_new_sync()` are checked correctly.
3) Try connecting with the same server using `openssl` and see if it responds correctly to your queries.
