### ISSUE TITLE
Static allocation and ringbuf.h build issue - wrong size in static assert. (IDFGH-10479)

### ISSUE THREAD

**Issue by phelter** [espressif/esp-idf#11726]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v5.1-rc1

### Operating System used.

Linux

### How did you build your project?

Command line with CMake

### If you are using Windows, please specify command line type.

None

### What is the expected behavior?

When SUPPORT_STATIC_ALLOCATION=1:

The [esp_ringbuf/include/freertos/ringbuf.h definition of StaticRingbuffer_t](https://github.com/espressif/esp-idf/blob/03d4fa28694ee15ccfd5a97447575de2d1655026/components/esp_ringbuf/include/freertos/ringbuf.h#L56-L66) does not match the Ringbuffer_t definition when it comes to size.  So when compiling with GNU the [assertion here](https://github.com/espressif/esp-idf/blob/03d4fa28694ee15ccfd5a97447575de2d1655026/components/esp_ringbuf/ringbuf.c#L76-L78) fails.

### What is the actual behavior?

Asserts the static assertion when building with STATIC_ALLOCATION - [here](https://github.com/espressif/esp-idf/blob/03d4fa28694ee15ccfd5a97447575de2d1655026/components/esp_ringbuf/ringbuf.c#L76-L78)

### Steps to reproduce.

Not providing reproduce steps that I used to find the issue, as I am building natively (linux) to mock out the ESP-IDF environment and consuming the headers inside the mocks for googletest and this is where the issue is identified.

Possible steps to reproduce.
1. Enable SUPPORT_STATIC_ALLOCATION
2. Build a main that uses the ringbuf.h with static allocation with GNU compiler newer than 4.6.

### Build or installation Logs.

```plain
esp_idf-src/components/esp_ringbuf/ringbuf.c:77:1: error: static assertion failed: "StaticRingbuffer_t != Ringbuffer_t"
   77 | _Static_assert(sizeof(StaticRingbuffer_t) == sizeof(Ringbuffer_t), "StaticRingbuffer_t != Ringbuffer_t");
      | ^~~~~~~~~~~~~~
```

### More Information.

This is fixed when the definition of the StaticRingbuffer_t is changed to:

```
#if (configSUPPORT_STATIC_ALLOCATION == 1)
typedef struct xSTATIC_RINGBUFFER
{
    /** @cond */ //Doxygen command to hide this structure from API Reference
    size_t      xDummy1[2];
    UBaseType_t uxDummy2;
    void       *pvDummy3[11]; // Note swap here must be in same order in case of padding.
    BaseType_t  xDummy4;
    // StaticSemaphore_t xDummy5[2];
    List_t       xDummy5[2]; // TaskWaitingtosend/receive
    void        *xDummy6;    // QueueSet
    portMUX_TYPE muxDummy;
    /** @endcond */
} StaticRingbuffer_t;
#endif
```

Also please add:

```
#if (configSUPPORT_STATIC_ALLOCATION == 1)
RingbufHandle_t xRingbufferCreateStatic(size_t xBufferSize, 
                                        RingbufferType_t xBufferType, 
                                        uint8_t *pucRingbufferStorage,
                                        StaticRingbuffer_t *pxStaticRingbuffer);
#endif
```
check for SUPPORT_STATIC_ALLOCATION as the xRingbufferCreateStatic OR add some build level check that it is not used when SUPPORT_STATIC_ALLOCATION = 0.

**Comment by Dazza0** [comment]
@phelter 

Thanks for catching this. Fix is pending merge on master and backport to v5.1.
