### ISSUE TITLE
static const in a c++ Class goes to .bss instead of flash (IDFGH-10535)

### ISSUE THREAD

**Issue by diplfranzhoepfinger** [espressif/esp-idf#11779]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v5.1-rc2

### Operating System used.

Linux

### How did you build your project?

Eclipse IDE

### If you are using Windows, please specify command line type.

None

### What is the expected behavior?

i will provide a minimal code Snippet for it. 

static const should go to flash not .bss

### What is the actual behavior?

it goes to .bss

### Steps to reproduce.

https://github.com/diplfranzhoepfinger/testSegments
see File: 
https://github.com/diplfranzhoepfinger/testSegments/blob/master/testSegments/build/main.map

there the scm_anDataInputNames goes to  .rodata.
which is correct. 

but if you look to my Application build: https://drive.google.com/file/d/18ipyh7MXLLX3u7MXW2JF8M5VJW1UuSBh/view?usp=drive_link (sorry, map File has over 50MB) you see: 

Code is here: 
https://gitlab.com/meisterschulen-am-ostbahnhof-munchen/org.eclipse.4diac.forte/-/tree/develop_me3?ref_type=heads

the scm_anDataInputNames go to the .bss segment. (and this 1374 times). so what is worng there ?

**Comment by diplfranzhoepfinger** [comment]
i have a Idea: 

it might come from the Build-Script: 

[https://gitlab.com/meisterschulen-am-ostbahnhof-munchen/org.eclipse.4diac.forte/-/blob/develop_me3/setup_esp32_isobus_DualOut.sh](https://gitlab.com/meisterschulen-am-ostbahnhof-munchen/org.eclipse.4diac.forte/-/blob/develop_me3/setup_esp32_isobus_DualOut.sh)

Line 82..91

**Comment by diplfranzhoepfinger** [comment]
@igrr 
@azoitl
i am Pretty sure the way we build it is the Reason. 

so let me explain you: 

1. Step we call "setup_esp32_isobus_DualOut.sh" which produces a libforte-static.a
2. Step this libforte-static.a is linked to a normal esp-idf project: https://gitlab.com/meisterschulen-am-ostbahnhof-munchen/4diac-forte-esp32-component/-/blob/feature/no_lua/CMakeLists.txt

**Comment by diplfranzhoepfinger** [comment]
@igrr
@azoitl

i have made same as a Lib and App Architecture: 

it still works right. 
https://github.com/diplfranzhoepfinger/testSegments/tree/as_lib


so it must be some specifics of not using idf.py for the lib build, some Command-line Params etc.. ?

**Comment by diplfranzhoepfinger** [comment]
one more Information: 

i have a "older" Project with the same Build Schema, but not using esp-idf v5.1-rc2 but 5.0.2, 
and the issue is the same. 

as well i have a "fully open Source" Project, 
here: https://gitlab.com/meisterschulen-am-ostbahnhof-munchen/esp32-4diac-example-application

and here: 
https://gitlab.com/meisterschulen-am-ostbahnhof-munchen/esp32-4diac-example-application-no-lua

where the same occurs.

**Comment by igrr** [comment]
Hi @diplfranzhoepfinger, we can accept this as a bug report if you provide a simple example (similar to your testSegments project) which demonstrates the issue. Troubleshooting a complex third party project is not the type of support we can offer in this issue tracker.

**Comment by franz-hoepfinger-at-hm-edu** [comment]
Hi @igrr this is very clear. I was more expecting a Simple hint from you what I could try to solve this issue. 
I have 2 big Projects now. esp-idf and eclipse 4diac... Both say check your settings...

For example: what is the Compiler Command Line esp-idf is using ?
Then I could test this.

**Comment by franz-hoepfinger-at-hm-edu** [comment]
Other way round: is there a paid support who could debug the complex Project? Like buy a Ticket (CoDeSys offers such things)

**Comment by igrr** [comment]
> what is the Compiler Command Line esp-idf is using ?

You can find the commands esp-idf is using in build/compile_commands.json.

As for the troubleshooting suggestion, here's one I can think of:

Try to find the object file corresponding to the .cpp file where this variable is defined. The object files are in the build directory. Run objdump -t on this file and look for the section into which the variable is placed. Is it in rodata?

**Comment by diplfranzhoepfinger** [comment]
> Try to find the object file corresponding to the .cpp file where this variable is defined. The object files are in the build directory. Run objdump -t on this file and look for the section into which the variable is placed. Is it in rodata?

very cool hint thanks. 

i learn more and more about Compiler building. I had "Compilerbau" in School, but this is far away from practice.

**Comment by diplfranzhoepfinger** [comment]
[https://gist.github.com/diplfranzhoepfinger/3ee2a01620de1febbb1d2f2648030d60](https://gist.github.com/diplfranzhoepfinger/3ee2a01620de1febbb1d2f2648030d60)

DualHysteresys.cpp --> source Code

DualHysteresys.cpp.obj.txt --> output of objdump -t DualHysteresys.cpp.obj

**Comment by diplfranzhoepfinger** [comment]
so, @igrr as you expected: the Error is already in the very first stage of Compilation. not later.

**Comment by diplfranzhoepfinger** [comment]
so, found it: 

the Constants in my Sample are in the cpp File. 

so the Compiler can see them. 

in the 4diac Project they are in the extra cpp File, not in a header. 

so the Compiler can only reserve space and not replace the Constants with the Values.

**Comment by diplfranzhoepfinger** [comment]
i have reported this to eclipse 4diac.

if i experimentally copy in the Values, 

it moves the Data to the rodata segment instead of bss

![image.png](https://matrix.eclipse.org/_matrix/media/r0/download/matrix-media-repo.eclipsecontent.org/cb10138407ad9f779d2bd06d37545da4863b3701)

![](https://github.com/espressif/esp-idf/assets/37779037/59488e62-b60f-4801-8296-73adce3763ae)

**Comment by diplfranzhoepfinger** [comment]
solved: 

there is a Option: 

    -DFORTE\_LINKED\_STRINGDICT=OFF \\

if you set this, the Segment goes to rodata instead of bss. 

@igrr thanks for your help. 

as always Espressif Support outperforms even big players!
