### ISSUE TITLE
BLE HID Device: mouse button not working on macOS (working properly on Windows) (IDFGH-10540)

### ISSUE THREAD

**Issue by CorsairCat** [espressif/esp-idf#11784]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v5.1-rc2

### Operating System used.

macOS

### How did you build your project?

VS Code IDE

### If you are using Windows, please specify command line type.

None

### Development Kit.

ESP32S3-DevKit1c

### Power Supply used.

USB

### What is the expected behavior?

While sending the left button signal of mouse, the left click should be performed on computer. the x and y axis input should work the same.

### What is the actual behavior?

Not respond to any button commands in the HID mouse first button region, including left click, right click and middle click. the axis x, y, all works fine.
This behavior only appears on macOS. It works perfectly on windows.

### Steps to reproduce.

1. compile the ble hid device demo under bludroid, modify the demo function to:
```
void hid_demo_task(void *pvParameters)
{
    vTaskDelay(1000 / portTICK_PERIOD_MS);
    send_volum_up = true;
    while(1) {
        vTaskDelay(300 / portTICK_PERIOD_MS);
        if (sec_conn) {
              esp_hidd_send_mouse_value(hid_conn_id, 1, 0, 0, 0);
        }
    }
}
```
2. flash it to board and connect it from the macOS, wait for it to perform left click;

### Debug Logs.

```plain
Nothing strange on log, I even checked with the x,y axis and they both work
```

### More Information.

also checked with iPad and it seems not working on all Apple devices

**Comment by CorsairCat** [comment]
I tried to capture the raw hid data received by Mac, and appears as following:
```
Handle Value Notification - Handle:0x0039 - Report - Value: 0001 0000
```
I also tried to reverse the bit order, and appears as 
```
Handle Value Notification - Handle:0x0039 - Report - Value: 8000 0000
```
Both of them can not trigger a click on macOS

**Comment by CorsairCat** [comment]
Solved, I tried disable the hid descriptor of the part I didn't use, seems to be the consumer device part is affecting the mouse button on macOS.

**Comment by zhp0406** [comment]
It seems that when the consumer device component is enabled, Apple devices classify the HID as a consumer device rather than a mouse.

**Comment by zhp0406** [comment]
We have fixed the issue with the BLE HID device. Please use the latest branch.

Alternatively, you can also use the following commits:

Commit https://github.com/espressif/esp-idf/commit/c73d7c0b600517221e11b5fe54fe9e3c160a0963 improves the compatibility of the HID device on the Windows platform.
Commit https://github.com/espressif/esp-idf/commit/5727802497b0504167216932af6d08a392845c6e enhances compatibility with iOS and macOS.
Commit https://github.com/espressif/esp-idf/commit/b90dc6a515f69d9b9a2a9401f873186167f5562f adds support for the HID device control point feature.
Commit https://github.com/espressif/esp-idf/commit/f7e174e9487cc218b92cffee9dc5953e962e0ff4 improves compatibility with Android versions after 10.
