### ISSUE TITLE
Why PPP still new/experimental in menuconfig at IDFv5.0.2? (IDFGH-11385)

### ISSUE THREAD

**Issue by WangShuoran** [espressif/esp-idf#11807]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Hello, In #10249 issue, @david-cermak say:

> Sorry for the late reply. The PPP is officially supported by Espressif, sorry for the confusion. We forgot to remove this note about the experimental status.

But at IDFv4.4.4 and v5.0.2 the menuconfig still have the question:
![image](https://github.com/espressif/esp-idf/assets/43474491/2bce3ae4-2016-4415-90e5-3644541c1d2d)

Why?

**Comment by WangShuoran** [comment]
In IDF v5.1.1 this feature is stable, and SLIP why not stable?

**Comment by WangShuoran** [comment]
@methodmissing Can you help me? The SLIP is very old protocol, I want to use this protocol.

**Comment by david-cermak** [comment]
@WangShuoran We removed the experimental note from PPPoS option in `v5.1`.

> Why?

This hasn't been tested properly, and when introduced it was marked as experimental.

> The SLIP is very old protocol, I want to use this protocol.

You can check this example: https://github.com/espressif/esp-protocols/tree/master/examples/esp_netif/slip_custom_netif

**Comment by david-cermak** [comment]
Hope it's been answered. Please reopen if not.
