### ISSUE TITLE
multitasking preemptive or cooperative ? (IDFGH-10571)

### ISSUE THREAD

**Issue by diplfranzhoepfinger** [espressif/esp-idf#11812]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/freertos_idf.html

Hello, 

after Reading this, 
it is still unclear for me if the Task Scheduler is preemptive or cooperative ? 

Thanks, 
Franz

**Comment by KaeLL** [comment]
Priority-based preemptive with the dual-core mods.

**Comment by ESP-Marius** [comment]
@KaeLL is correct.

Described in more details [here](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/freertos_idf.html#smp-scheduler)

**Comment by diplfranzhoepfinger** [comment]
TNX
