### ISSUE TITLE
ble_hid_device_demo don't work on windows, but work on linux and phone (IDFGH-10570)

### ISSUE THREAD

**Issue by joye-wang** [espressif/esp-idf#11811]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Clone the repository, cd `esp-idf\examples\bluetooth\bluedroid\ble\ble_hid_device_demo`, then build and flash it to esp32s3.

My ESP-IDF version is `idf5.1`

The `HID` bluetooth device is successfully advertising, and can be connected in all system(windows, linux, phone)
![image](https://github.com/espressif/esp-idf/assets/23148429/adbe7e49-e36d-4a39-8571-eba9adb62cba)

The demo will send `increase volume` to PC after connected, but nothing happened in Windows System. 
And the demo is worked in Linux System and iPhone. Here is a screenshot that I receive the `increase volumn` in my iPhone after I connected the bluetooth device `HID`
![image](https://github.com/espressif/esp-idf/assets/23148429/e129475f-510b-4db8-bda1-702e7a324e4e)

I use `Wireshark` to capture the bluetooth data between ESP32S3 and Windows, the Info shows `Unknown`
![image](https://github.com/espressif/esp-idf/assets/23148429/42a1689e-4aff-4e67-be54-1aade1d71f21)

Here is how to capture bluetooth data:
1. download bluetooth test tool in windows: 
https://learn.microsoft.com/en-us/windows-hardware/drivers/bluetooth/testing-btp-setup-package?source=recommendations
(direct download link)https://download.microsoft.com/download/e/e/e/eeed3cd5-bdbd-47db-9b8e-ca9d2df2cd29/BluetoothTestPlatformPack-1.14.0.msi
2. download wireshark, dont choose portable version
3. open cmd : `c:\BTP\v1.14.0\x86>btvs.exe -Mode Wireshark`  ,thats all

The attachment is capture data in wireshark, you can open it with wireshark after unzip it.
[ble_data.zip](https://github.com/espressif/esp-idf/files/11958665/ble_data.zip)

Here is the `elf` file which I built from official code `esp-idf\examples\bluetooth\bluedroid\ble\ble_hid_device_demo`, you can  do some tests with it.
[ble_hid_device_demo_elf.zip](https://github.com/espressif/esp-idf/files/11966765/ble_hid_device_demo_elf.zip)

Please check the problem, Thanks!

**Comment by joye-wang** [comment]
And here is the serial port log:
```
�����ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0x1 (POWERON),boot:0x8 (SPI_FAST_FLASH_BOOT)
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fce3818,len:0x16e8
load:0x403c9700,len:0x4
load:0x403c9704,len:0xc00
load:0x403cc700,len:0x2eb0
entry 0x403c9908
[0;32mI (27) boot: ESP-IDF v5.1-rc1-dirty 2nd stage bootloader[0m
[0;32mI (27) boot: compile time Jul  5 2023 21:02:34[0m
[0;32mI (27) boot: Multicore bootloader[0m
[0;32mI (31) boot: chip revision: v0.1[0m
[0;32mI (34) boot.esp32s3: Boot SPI Speed : 80MHz[0m
[0;32mI (39) boot.esp32s3: SPI Mode       : DIO[0m
[0;32mI (44) boot.esp32s3: SPI Flash Size : 2MB[0m
[0;32mI (49) boot: Enabling RNG early entropy source...[0m
[0;32mI (54) boot: Partition Table:[0m
[0;32mI (58) boot: ## Label            Usage          Type ST Offset   Length[0m
[0;32mI (65) boot:  0 nvs              WiFi data        01 02 00009000 00006000[0m
[0;32mI (72) boot:  1 phy_init         RF data          01 01 0000f000 00001000[0m
[0;32mI (80) boot:  2 factory          factory app      00 00 00010000 00100000[0m
[0;32mI (87) boot: End of partition table[0m
[0;32mI (92) esp_image: segment 0: paddr=00010020 vaddr=3c080020 size=20cc8h (134344) map[0m
[0;32mI (124) esp_image: segment 1: paddr=00030cf0 vaddr=3fc96d00 size=03f58h ( 16216) load[0m
[0;32mI (128) esp_image: segment 2: paddr=00034c50 vaddr=40374000 size=0b3c8h ( 46024) load[0m
[0;32mI (140) esp_image: segment 3: paddr=00040020 vaddr=42000020 size=789c8h (494024) map[0m
[0;32mI (229) esp_image: segment 4: paddr=000b89f0 vaddr=4037f3c8 size=0783ch ( 30780) load[0m
[0;32mI (244) boot: Loaded app from partition at offset 0x10000[0m
[0;32mI (244) boot: Disabling RNG early entropy source...[0m
[0;32mI (256) cpu_start: Multicore app[0m
[0;32mI (256) cpu_start: Pro cpu up.[0m
[0;32mI (256) cpu_start: Starting app cpu, entry point is 0x4037541c[0m
[0;32mI (0) cpu_start: App cpu up.[0m
[0;32mI (274) cpu_start: Pro cpu start user code[0m
[0;32mI (274) cpu_start: cpu freq: 160000000 Hz[0m
[0;32mI (274) cpu_start: Application information:[0m
[0;32mI (277) cpu_start: Project name:     hidd_demos[0m
[0;32mI (283) cpu_start: App version:      v5.2-dev-1349-gcf7e743a9b[0m
[0;32mI (289) cpu_start: Compile time:     Jul  5 2023 21:02:11[0m
[0;32mI (295) cpu_start: ELF file SHA256:  5570521cbd7f9149...[0m
[0;32mI (301) cpu_start: ESP-IDF:          v5.1-rc1-dirty[0m
[0;32mI (307) cpu_start: Min chip rev:     v0.0[0m
[0;32mI (311) cpu_start: Max chip rev:     v0.99 [0m
[0;32mI (316) cpu_start: Chip rev:         v0.1[0m
[0;32mI (321) heap_init: Initializing. RAM available for dynamic allocation:[0m
[0;32mI (328) heap_init: At 3FC9ED20 len 0004A9F0 (298 KiB): DRAM[0m
[0;32mI (334) heap_init: At 3FCE9710 len 00005724 (21 KiB): STACK/DRAM[0m
[0;32mI (341) heap_init: At 3FCF0000 len 00008000 (32 KiB): DRAM[0m
[0;32mI (347) heap_init: At 600FE010 len 00001FF0 (7 KiB): RTCRAM[0m
[0;32mI (354) spi_flash: detected chip: gd[0m
[0;32mI (358) spi_flash: flash io: dio[0m
[0;33mW (362) spi_flash: Detected size(16384k) larger than the size in the binary image header(2048k). Using the size in the binary image header.[0m
[0;32mI (375) sleep: Configure to isolate all GPIO pins in sleep state[0m
[0;32mI (382) sleep: Enable automatic switching of GPIO sleep configuration[0m
[0;32mI (389) coexist: coex firmware version: ebddf30[0m
[0;32mI (394) coexist: coexist rom version e7ae62f[0m
[0;32mI (399) app_start: Starting scheduler on CPU0[0m
[0;32mI (404) app_start: Starting scheduler on CPU1[0m
[0;32mI (404) main_task: Started on CPU0[0m
[0;32mI (414) main_task: Calling app_main()[0m
[0;32mI (424) BLE_INIT: BT controller compile version [85b425c][0m
[0;32mI (424) phy_init: phy_version 601,fe52df4,May 10 2023,17:26:54[0m
[0;32mI (464) BLE_INIT: Bluetooth MAC: 34:85:18:46:05:5a
[0m
[0;32mI (514) HID_LE_PRF: esp_hidd_prf_cb_hdl(), start added the hid service to the stack database. incl_handle = 40[0m
[0;32mI (514) HID_LE_PRF: hid svc handle = 2d[0m
[0;32mI (524) main_task: Returned from app_main()[0m
[0;32mI (10104) HID_DEMO: remote BD_ADDR: 0a61010556f6[0m
[0;32mI (10104) HID_DEMO: address type = 0[0m
[0;32mI (10104) HID_DEMO: pair status = success[0m
[0;32mI (10164) HID_LE_PRF: HID connection establish, conn_id = 0[0m
[0;32mI (10164) HID_DEMO: ESP_HIDD_EVENT_BLE_CONNECT[0m
[0;32mI (11524) HID_DEMO: Send the volume[0m
[0;32mI (19524) HID_DEMO: Send the volume[0m
[0;32mI (27524) HID_DEMO: Send the volume[0m
[0;32mI (35524) HID_DEMO: Send the volume[0m
[0;32mI (43524) HID_DEMO: Send the volume[0m
[0;32mI (51524) HID_DEMO: Send the volume[0m
[0;32mI (59524) HID_DEMO: Send the volume[0m
[0;32mI (67524) HID_DEMO: Send the volume[0m
[0;32mI (75524) HID_DEMO: Send the volume[0m
[0;32mI (83524) HID_DEMO: Send the volume[0m
[0;32mI (91524) HID_DEMO: Send the volume[0m
[0;32mI (99524) HID_DEMO: Send the volume[0m

```

**Comment by jeremyherbert** [comment]
I also have this same issue with the example https://github.com/espressif/esp-idf/tree/v5.1/examples/bluetooth/esp_hid_device on the esp32c3 and IDF v5.1

It seems that windows is not loading the HID keyboard driver, as the ESP32 doesn't show up in the "Mouse, keyboard, & pen", and there is no new HID device in device manager.

@zhp0406 have you had a chance to look at this?

**Comment by zhp0406** [comment]
@jeremyherbert 
ok,I will check it as soon as possible.

**Comment by jeremyherbert** [comment]
I just tried with IDF v4.4.4 and the BLE device enumerates correctly on windows. So it seems to be a problem somewhere between v4.4.4 and v5.1.

**Comment by jeremyherbert** [comment]
also works fine in v5.0 tag. So regression is between v5.0 and v5.1.

**Comment by joye-wang** [comment]
v5.0.2 also works for me.  It really helps! Thank you @jeremyherbert .

I wish you can solve the problem in latest version too.

**Comment by zhp0406** [comment]
@jeremyherbert @joye-wang 
I'm sorry for the delay in finding the cause of the issue. The problem is caused by compatibility issues between the Win10 operating system and the new version of the BLE 5.3 protocol. In order to ensure it doesn't disrupt your normal usage, you can apply the following patch. We will provide updates for all versions of the IDF in the future.
[0001-fix-bt-bluedroid-Fix-ble-hid-bugs-draft.zip](https://github.com/espressif/esp-idf/files/12696189/0001-fix-bt-bluedroid-Fix-ble-hid-bugs-draft.zip)

**Comment by zhp0406** [comment]
We have fixed the issue with the BLE HID device. Please use the latest branch.

Alternatively, you can also use the following commits:

Commit https://github.com/espressif/esp-idf/commit/c73d7c0b600517221e11b5fe54fe9e3c160a0963 improves the compatibility of the HID device on the Windows platform.
Commit https://github.com/espressif/esp-idf/commit/5727802497b0504167216932af6d08a392845c6e enhances compatibility with iOS and macOS.
Commit https://github.com/espressif/esp-idf/commit/b90dc6a515f69d9b9a2a9401f873186167f5562f adds support for the HID device control point feature.
Commit https://github.com/espressif/esp-idf/commit/f7e174e9487cc218b92cffee9dc5953e962e0ff4 improves compatibility with Android versions after 10.
