### ISSUE TITLE
Allow inclusion of *_hal headers in .cpp files (IDFGH-10573)

### ISSUE THREAD

**Issue by higaski** [espressif/esp-idf#11813]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

ESP-IDF v5.2-dev-1349-gcf7e743a9b

### Operating System used.

Linux

### How did you build your project?

Command line with Make

### If you are using Windows, please specify command line type.

None

### What is the expected behavior?

Commit 921713fff40fa76dd89564f7dd22121ca4ce7a94 broke a build of mine which relies on one of the low level routines in [uart_ll.h ](https://github.com/espressif/esp-idf/blob/921713fff40fa76dd89564f7dd22121ca4ce7a94/components/hal/esp32/include/hal/uart_ll.h)
From that commit on the header can no longer be included in a .cpp file because of C++s stronger typing. 

```sh
/home/vinci/esp/esp-idf/components/hal/esp32s3/include/hal/uart_ll.h:112:27: error: cannot convert 'soc_periph_uart_clk_src_legacy_t' to 'soc_module_clk_t' in assignment
  112 |             *source_clk = UART_SCLK_APB;
      |                           ^~~~~~~~~~~~~
      |                           |
      |                           soc_periph_uart_clk_src_legacy_t
compilation terminated due to -Wfatal-errors.
```

I'd appreciate it if compatibility could be restored by adding a cast.

### What is the actual behavior?

.

### Steps to reproduce.

.

**Comment by 0xjakob** [comment]
@higaski Thanks for letting us know! We'll add this cast and come back to you here.
