### ISSUE TITLE
RTC timer preservation after reset (IDFGH-10576)

### ISSUE THREAD

**Issue by diplfranzhoepfinger** [espressif/esp-idf#11815]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

due to this: 
https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/system_time.html#overview

This timer allows time keeping in various sleep modes, and can also persist time keeping across any resets (with the exception of power-on resets which reset the RTC timer).

it should work like proposed. 

https://github.com/diplfranzhoepfinger/RTC-timer-preservation-after-reset

**Comment by diplfranzhoepfinger** [comment]
and it works like proposed: 

see: [https://gist.github.com/diplfranzhoepfinger/937d60cc8bb981f24b59edc52885f094](https://gist.github.com/diplfranzhoepfinger/937d60cc8bb981f24b59edc52885f094)

it preserves Time during the Reset.

**Comment by diplfranzhoepfinger** [comment]
there are 2 ways where the RTC timer is not preserved: 

Power on

Reset by Pressing Reset on the Devboard.

**Comment by diplfranzhoepfinger** [comment]
[https://github.com/diplfranzhoepfinger/RTC-timer-preservation-after-reset/tree/feature/reset_with_assert](https://github.com/diplfranzhoepfinger/RTC-timer-preservation-after-reset/tree/feature/reset_with_assert)

simulates a assert catched: 

also time is preserved.

**Comment by KaeLL** [comment]
What's your question?

**Comment by franz-hoepfinger-at-hm-edu** [comment]
Currently no Question. 
My Customer will test this code on his side. If it works perfectly we will close the Ticket. If it doesn't work we will add the Question here.

**Comment by ESP-Marius** [comment]
If there are no issues i'll just close this one then. Feel free to re-open if you do encounter anything.
