### ISSUE TITLE
espressif/idf:v5.1 docker image is missing (IDFGH-10590)

### ISSUE THREAD

**Issue by chriz2600** [espressif/esp-idf#11827]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Current stable version `v5.1` (according to [documentation](https://docs.espressif.com/projects/esp-idf/en/v5.1/esp32/api-guides/tools/idf-docker-image.html?highlight=docker)) isn't available as docker image (`v5.1` tag does not exist)

**Comment by igrr** [comment]
Thanks for noticing! Looks like there was a timeout when pushing the image. Now it's available: https://hub.docker.com/layers/espressif/idf/v5.1/images/sha256-41a6db60cbe3dc0fce17c7f703fe18ac254cfa12ce36fb03a916b3e8d1826fff?context=explore
