### ISSUE TITLE
blufi@nimble:  ble_gatts_notify_custom()  undefined (IDFGH-10611)

### ISSUE THREAD

**Issue by LeoYan** [espressif/esp-idf#11847]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

- esp-idf V4.4.5
- ESP32
- Issue
  the output of  idf.py build:

```
esp-idf/components/bt/common/btc/profile/esp/blufi/nimble_host/esp_blufi.c:435:10: error: implicit declaration of function 'ble_gatts_notify_custom'; did you mean 'ble_gattc_notify_custom'? [-Werror=implicit-function-declaration]
     rc = ble_gatts_notify_custom(blufi_env.conn_id, gatt_values[1].val_handle, om);
          ^~~~~~~~~~~~~~~~~~~~~~~
          ble_gattc_notify_custom
```

- Suggest :
should  use  ble_gattc_notify_custom() 

- Reference
 [https://mynewt.apache.org/latest/network/ble_hs/ble_gatts.html?highlight=ble_gattc_notify_custom#c.ble_gattc_notify_custom](url)

```
int ble_gattc_notify_custom()
Deprecated.
Should not be used. Use ble_gatts_notify_custom instead.
```

**Comment by rahult-github** [comment]
Thanks. Change is already committed to github [here](https://github.com/espressif/esp-idf/commit/aca729aea61a35a86f26d3873cc1b19992a4dc84).
