### ISSUE TITLE
[TW#16282] Console Echo

### ISSUE THREAD

**Issue by ardiehl** [espressif/esp-idf#1185]
when connecting via minicom/gtkterm/... no echo of typed characters will be shown. Pressing enter or after entered 128 chars, the entered chars will be shown. Looks like buffering of stdout ?
This is different than for the esp8266, there is works as expected.

**Comment by igrr** [comment]
Just to clarify, are you seeing this with `examples/system/console` example, or some other application?

**Comment by igrr** [comment]
Closing due to lack of response, please reopen if this is still an issue.
