### ISSUE TITLE
esp-tls-mbedtls: mbedtls_ssl_setup returned -0x7F00 (IDFGH-10619)

### ISSUE THREAD

**Issue by weilan-915** [espressif/esp-idf#11854]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

V5.1

### Operating System used.

Linux

### How did you build your project?

Command line with idf.py

### If you are using Windows, please specify command line type.

None

### Development Kit.

ESP32-C3-MINI-1U

### Power Supply used.

USB

### What is the expected behavior?

Expected firmware to be able to upgrade OTA normally

### What is the actual behavior?

mbedtls_ssl_setup returned -0x7F00

### Steps to reproduce.

1. Using Bluetooth network distribution
2. Log in to MQTT after connecting to the network
3. Upgrade by issuing ota urls through mqtt
...

### Debug Logs.

```plain
../main/src/app_ota_info.c[70]: [APP] Free memory: 56308 bytes

../main/src/app_ota_info.c[71]: Starting Advanced OTA example
E (39341) esp-tls-mbedtls: mbedtls_ssl_setup returned -0x7F00
E (39351) esp-tls: create_ssl_handle failed
E (39351) esp-tls: Failed to open new connection
E (39351) transport_base: Failed to open a new connection
E (39361) HTTP_CLIENT: Connection failed, sock < 0
E (39361) esp_https_ota: Failed to open HTTP connection: ESP_ERR_HTTP_CONNECT
E (39371) esp_https_ota: Failed to establish HTTP connection
../main/src/app_ota_info.c[98]: ESP HTTPS OTA Begin failed
```

**Comment by AdityaHPatwardhan** [comment]
Hi @weilan-915 Can you share following details
1) Can you print the output of `esp_get_free_internal_heap_size();` and also `esp_get_minimum_free_heap_size()` after the message `ESP HTTPS OTA Begin failed` ?
2) Can you share your sdkconfig file?
3) Can you reproduce similar error on [advanced_https_ota](https://github.com/espressif/esp-idf/tree/master/examples/system/ota/advanced_https_ota) example ?
4) Is it possible for you to share a small test code which can reproduce the issue?

This error is `MBEDTLS_ERR_SSL_ALLOC_FAILED`, which is related to the memory allocation.
I think we should find out why the memory allocation failed.

**Comment by weilan-915** [comment]
1.
`../main/src/app_ota_info.c[71]: esp_get_free_internal_heap_size Free memory: 42368 bytes`
`../main/src/app_ota_info.c[72]: esp_get_minimum_free_heap_size Free memory: 32412 bytes`
`../main/src/app_ota_info.c[73]: Starting Advanced OTA example`
`I (59114) esp_https_ota: max_http_request_size=32768`
`E (59594) esp-tls-mbedtls: mbedtls_ssl_setup returned -0x7F00`
`E (59594) esp-tls: create_ssl_handle failed`
`E (59594) esp-tls: Failed to open new connection`
`E (59604) transport_base: Failed to open a new connection`
`E (59604) HTTP_CLIENT: Connection failed, sock < 0`
`E (59614) esp_https_ota: Failed to open HTTP connection: ESP_ERR_HTTP_CONNECT`
`E (59624) esp_https_ota: Failed to establish HTTP connection`
`../main/src/app_ota_info.c[100]: ESP HTTPS OTA Begin failed`
`../main/src/app_ota_info.c[101]: esp_get_free_internal_heap_size Free memory: 53272 bytes`
`../main/src/app_ota_info.c[102]: esp_get_minimum_free_heap_size Free memory: 32412 bytes`
2.I don't know how to share;
3.Using this example alone will not result in errors;
4.Sorry, this is integrated on the project and cannot be shared;

Other:
1.How much memory is required for ota upgrade;
2.I can upgrade normally by turning off the mqtt function before ota, but I am not allowed to do so in terms of functionality.

**Comment by weilan-915** [comment]
@AdityaHPatwardhan 
1.
../main/src/app_ota_info.c[71]: esp_get_free_internal_heap_size Free memory: 42368 bytes
../main/src/app_ota_info.c[72]: esp_get_minimum_free_heap_size Free memory: 32412 bytes
../main/src/app_ota_info.c[73]: Starting Advanced OTA example
I (59114) esp_https_ota: max_http_request_size=32768
E (59594) esp-tls-mbedtls: mbedtls_ssl_setup returned -0x7F00
E (59594) esp-tls: create_ssl_handle failed
E (59594) esp-tls: Failed to open new connection
E (59604) transport_base: Failed to open a new connection
E (59604) HTTP_CLIENT: Connection failed, sock < 0
E (59614) esp_https_ota: Failed to open HTTP connection: ESP_ERR_HTTP_CONNECT
E (59624) esp_https_ota: Failed to establish HTTP connection
../main/src/app_ota_info.c[100]: ESP HTTPS OTA Begin failed
../main/src/app_ota_info.c[101]: esp_get_free_internal_heap_size Free memory: 53272 bytes
../main/src/app_ota_info.c[102]: esp_get_minimum_free_heap_size Free memory: 32412 bytes
2.I don't know how to share;
3.Using this example alone will not result in errors;
4.Sorry, this is integrated on the project and cannot be shared;

Other:
1.How much memory is required for ota upgrade;
2.I can upgrade normally by turning off the mqtt function before ota, but I am not allowed to do so in terms of functionality.

**Comment by LHYYSY** [comment]
I made the same mistake. What's the problem?

**Comment by laukik-hase** [comment]
Hello, @weilan-915 and @LHYYSY!

- As @AdityaHPatwardhan mentioned, the error code `0x6C00` is `MBEDTLS_ERR_SSL_ALLOC_FAILED` - meaning you have fallen short of heap memory to allocate Mbed TLS resources. For debugging the heap memory allocations and potential leaks, you can refer to [Heap Memory Debugging](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/heap_debug.html) docs.

- You can find the typical memory usage of a TLS connection and ways to optimise it [here](
https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/protocols/mbedtls.html#reducing-heap-usage).

**Comment by laukik-hase** [comment]
Hello, @weilan-915 and @LHYYSY!
Closing this issue due to lack of feedback, feel free to reopen with more updates. Thanks.
