### ISSUE TITLE
How do I configure a WPA2-Enterprise Wi-Fi network via BluFi? (IDFGH-10630)

### ISSUE THREAD

**Issue by marco711** [espressif/esp-idf#11863]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

In the [Blufi](https://github.com/espressif/esp-idf/blob/master/examples/bluetooth/blufi/main/blufi_example_main.c) example, in the `example_event_callback` function, which is the event where we should send the WPA2-Enterprise's Identity and Password? I suppose that the Identity is sent in the `ESP_BLUFI_EVENT_RECV_USERNAME` event and the type of security must be sent in the `ESP_BLUFI_EVENT_RECV_SOFTAP_AUTH_MODE` event. Is this correct?

**Comment by zhp0406** [comment]
Currently not supported.
