### ISSUE TITLE
Log system time include date (IDFGH-10635)

### ISSUE THREAD

**Issue by dizcza** [espressif/esp-idf#11868]
### Is your feature request related to a problem?

As I run my apps for more than 24H, I'd like to see the date in the logs.

### Describe the solution you'd like.

If the "System time" logging option is chosen, add the systime ISO log format

`%Y-%m-%d %H:%M%:S.%f` by default.

### Describe alternatives you've considered.

Alternatively, add a chooser:
* with date
* without date (hours only)

**Comment by nopnop2002** [comment]
Interesting idea.

I made it in a hurry.

https://github.com/nopnop2002/esp-idf-time-logging

**Comment by KonstantinKondrashov** [comment]
Hi @dizcza!
I am working on esp_log version 2 which will be able to add any timestamp formats by a user. This work has not finished yet, for now, I can suggest trying to redefine [esp_log_system_timestamp()](https://github.com/espressif/esp-idf/blob/master/components/log/log_freertos.c#L59-L97) to see how to do it [here](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/build-system.html#wrappers-to-redefine-or-extend-existing-functions). It will help you to set any timestamp format what you want (just do not forget to increase the `buffer[18]`).
Thanks.

**Comment by KonstantinKondrashov** [comment]
I close this issue, feel free to re-open it. This feature will be added in log version 2.
