### ISSUE TITLE
unable to get more than 13 simultaneous tcp connections despite LWIP_MAX_SOCKETS=16 (IDFGH-10651)

### ISSUE THREAD

**Issue by albrownwood** [espressif/esp-idf#11882]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

using the tcp_server example provided here: https://github.com/espressif/esp-idf/blob/master/examples/protocols/sockets/tcp_server/main/tcp_server.c

Open tcp 13 connections from a computer.
when opening the 11th connections the following error is logged on esp32: 
E (39868) tcp_server: Unable to accept connection: errno 23

in sdkconfig, I have bumped the LWIP_MAX_SOCKETS to 16

<img width="460" alt="image" src="https://github.com/espressif/esp-idf/assets/65631701/37fe53d2-f235-4879-a4ac-e35455e484f0">

**Comment by chipweinberger** [comment]
i think some sockets are used for internal implementation details. not sure though.
