### ISSUE TITLE
ESP-IDF make  error (IDFGH-10669)

### ISSUE THREAD

**Issue by Shivdoke39** [espressif/esp-idf#11898]
lnv173@DESKTOP-5FHABSQ MINGW32 ~/esp32-ota
# make menuconfig
Makefile:8: C:/msys32/home/lnv173/esp/esp-idf/make/project.mk: No such file or directory
make: *** No rule to make target 'C:/msys32/home/lnv173/esp/esp-idf/make/project.mk'.  Stop.

lnv173@DESKTOP-5FHABSQ MINGW32 ~/esp32-ota
# printenv IDF_PATH
C:/msys32/home/lnv173/esp/esp-idf

lnv173@DESKTOP-5FHABSQ MINGW32 ~/esp32-ota
# make menuconfig
Makefile:8: C:/msys32/home/lnv173/esp/esp-idf/make/project.mk: No such file or directory
make: *** No rule to make target 'C:/msys32/home/lnv173/esp/esp-idf/make/project.mk'.  Stop.

**Comment by igrr** [comment]
Looks like you are trying to build the project which uses the legacy GNU Make based build system using a version of IDF which doesn't support it anymore. Please check the [migration guide](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/migration-guides/release-5.x/5.0/build-system.html#migrating-from-gnu-make-build-system) regarding migration to the CMake based build system. v4.x versions of IDF include a helper script which can help you migrate the project from Make to CMake.

**Comment by Alvin1Zhang** [comment]
@Shivdoke39 Thanks for reporting, would you please help share if any further updates for the issue? Thanks.

**Comment by ESP-Marius** [comment]
Closing this as there hasnt been any updates, feel free to re-open if you are still having this issue and need help resolving it.
