### ISSUE TITLE
Zigbee Examples persist network after reboot (IDFGH-10677)

### ISSUE THREAD

**Issue by muc-martin** [espressif/esp-idf#11904]
### Is your feature request related to a problem?

I tried the [HA_on_off_light](https://github.com/espressif/esp-idf/tree/master/examples/zigbee/light_sample/HA_on_off_light) [HA_on_off_switch](https://github.com/espressif/esp-idf/tree/master/examples/zigbee/light_sample/HA_on_off_switch)
examples and compiled them for the ESP32-H2 everything worked. But after a reboot of the coordinator the light-node needs to reboot as well otherwise commands are not transferred.

### Describe the solution you'd like.

Add a example how to persist the zigbee network state for both devices after reboot.

**Comment by xieqinan** [comment]
Hi @muc-martin ,
The Zigbee network still exists after the coordinator reboots. The reason why commands are not transferred is that the switch example uses a volatile variable to store the light (end device) device information. When the switch (coordinator) resets, the device information is cleared from the switch's RAM, resulting in the commands not being transferred.

The esp-zigbee-sdk provides the `esp_zb_zdo_device_bind_req()` API to bind two devices. By doing so, the device information can be stored into flash and recovered by the device, which can be referred to in the [esp-zigbee-sdk](https://github.com/espressif/esp-zigbee-sdk/blob/main/examples/esp_zigbee_customized_devices/customized_client/main/esp_HA_customized_switch.c#L115C57-L115C61)

Besides, more practical examples  will be added to esp-idf zigbee.

**Comment by muc-martin** [comment]
Hi @xieqinan,

thank you for the info.
It would be great if you could add an example how to connect and use a commercially available zigbee wall switch (e.g. [switch](https://content.paulmann.com/media/4c/fa/89/1647010755/50134_V01.pdf) to receive and process commands on the ESP32 board and perform custom actions depending on which button was pressed.

Thanks.

**Comment by chshu** [comment]
@muc-martin We have updated the examples in the esp-zigbee-sdk to store the network and binding information persistently: https://github.com/espressif/esp-zigbee-sdk/tree/main/examples/esp_zigbee_HA_sample

So after the reboot, the devices will continue to work together.

**Comment by allexoK** [comment]
Hello, sorry for stupid question, how exactly can I retrieve stored info from memory?

**Comment by chshu** [comment]
> Hello, sorry for stupid question, how exactly can I retrieve stored info from memory?

The Zigbee Stack related information is maintained within SDK, the SDK will do the store and retrieve by itself. User applicaion only handles the application specific info.
