### ISSUE TITLE
SPIFFS config size

### ISSUE THREAD

**Issue by forthlightning** [espressif/esp-idf#1190]
Hi, wondering if it would be possible to add a Kconfig menu option to the spiffs component which will allow customization of size?

Looking at line 217 in spiffs config.h 

```
#ifndef SPIFFS_CFG_PHYS_SZ
#define SPIFFS_CFG_PHYS_SZ(ignore)        (1024*1536)
#endif
```

**Comment by me-no-dev** [comment]
customization in size is done in the partitions configuration :)
See: https://github.com/espressif/esp-idf/blob/master/examples/storage/spiffs/partitions_example.csv#L6

**Comment by forthlightning** [comment]
Oh, so it will detect the size from the partition table? Pretty snazzy! So if I made a change in the config file there will be no effect?

I was reading into the component and it looks like there are 2 config files... One in default and the other in include. Seems like it may create confusion when including.

**Comment by me-no-dev** [comment]
only the one in include is used. And yes :) it reads the partition table and uses the size there.
