### ISSUE TITLE
Bad head at 0x3ffd3e08. Expected 0xabba1234 got 0x00000000 ???

### ISSUE THREAD

**Issue by YvedD** [espressif/esp-idf#1191]
Hi @YvedD,

I believe the problem is here:
```
      free(&data);
```

All the `data` structures are declared on the task's stacks so you don't need to free them. You only need to free something you allocate from the heap with "malloc". Sending/receiving from a queue copies the data in and out of the queue, so it's never allocated or freed.

The heap implementation can't always tell if you are freeing something incorrectly, until the heap corruption detector kicks in.

For future reference of anyone who finds this issue but has a different underlying cause, the best place to look for advice debugging CORRUPT HEAP messages is: https://esp-idf.readthedocs.io/en/latest/api-reference/system/heap_debug.html

**Comment by projectgus** [comment]
Hi @YvedD ,

I apologise, I just edited your comment instead of replying to it! I don't seem to be able to revert the edit, but hopefully it answers your question...

Angus

**Comment by YvedD** [comment]
No Problem Angus,

I the meantime i had solved it already by myself (that was a home run for me as a newbie :-) )
I am still not out of the woods with what i am doing, it is all so new for me

now i am looking for something like a "xTaskCreateFromISRPinnedToCore" or something like that
Thanks anyway for the help offered

Yves

**Comment by projectgus** [comment]
> now i am looking for something like a "xTaskCreateFromISRPinnedToCore" or something like that

You probably want to somehow give a semaphore or set an event group bit from the ISR and then create the task in another task. Or pre-create the task and have it block one one of these before it starts executing.

For general questions about IDF, the https://esp32.com forums are a great place to post.
