### ISSUE TITLE
Socket send error (IDFGH-10689)

### ISSUE THREAD

**Issue by Coloryr** [espressif/esp-idf#11914]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v5.0.3-182-gf2973dc4c6

### Operating System used.

Windows

### How did you build your project?

Command line with idf.py

### If you are using Windows, please specify command line type.

CMD

### Development Kit.

ESP32-CAM

### Power Supply used.

USB

### What is the expected behavior?

![image](https://github.com/espressif/esp-idf/assets/26276037/840a0fc8-188a-41ca-ac16-4bb511b5b8de)

### What is the actual behavior?

Socket send data not restart

### Steps to reproduce.

1. Run
2. Open `Socket`
3. Send data

### More Information.

![image](https://github.com/espressif/esp-idf/assets/26276037/b4e24b40-9795-4148-8d7f-fbbeb97f7702)
![image](https://github.com/espressif/esp-idf/assets/26276037/fc587edb-16c7-4926-b515-e2c8c8d90bc0)
![image](https://github.com/espressif/esp-idf/assets/26276037/12054b97-9fb3-40af-8268-f76e6619356e)

**Comment by espressif-abhikroy** [comment]
It appears that there might be an issue with an invalid address being sent in one of the ```socket_server_send()``` calls. 
Kindly investigate the matter thoroughly. 
If the problem persists, I would appreciate it if you could provide a simple example that can help recreate the issue, facilitating further troubleshooting. 

Thank you.

**Comment by Coloryr** [comment]
> It appears that there might be an issue with an invalid address being sent in one of the `socket_server_send()` calls. Kindly investigate the matter thoroughly. If the problem persists, I would appreciate it if you could provide a simple example that can help recreate the issue, facilitating further troubleshooting.
> 
> Thank you.

[softAP.zip](https://github.com/espressif/esp-idf/files/12259001/softAP.zip)

**Comment by Coloryr** [comment]
Is look like the `pic->buf` is NULL.
