### ISSUE TITLE
Large Text File Compression to .zip Format  (IDFGH-10694)

### ISSUE THREAD

**Issue by Noushadalik** [espressif/esp-idf#11919]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

We are using the ESP32 WROOM 32D with a 16 MB flash size and want to implement a feature that compresses a large text file from the SD card and sends it to the cloud through HTTPS.
Is there any library for Esp idf to compress a text file to zip format?

**Comment by igrr** [comment]
I'm not aware of an IDF library specifically for handling zip format, but there is a port of standard zlib library to ESP-IDF which you can use to implement Deflate: https://components.espressif.com/components/espressif/zlib.

**Comment by hayschan** [comment]
Came across a similar requirement: decompressing (aka unzipping) a `.zip` file located on a connected SD card. The SD card is connected to the ESP32 via SDMMC.

**Comment by adcr8iv** [comment]
> Came across a similar requirement: decompressing (aka unzipping) a `.zip` file located on a connected SD card. The SD card is connected to the ESP32 via SDMMC.

@hayschan what did you end up using?

**Comment by anujdeshpande** [comment]
> Came across a similar requirement: decompressing (aka unzipping) a `.zip` file located on a connected SD card. The SD card is connected to the ESP32 via SDMMC.

@hayschan what did you end up using?

**Comment by hayschan** [comment]
> > Came across a similar requirement: decompressing (aka unzipping) a `.zip` file located on a connected SD card. The SD card is connected to the ESP32 via SDMMC.
> 
> 
> 
> @hayschan what did you end up using?

I took another technical route by not using zip compression.
