### ISSUE TITLE
[Secure Boot V2] Unable to flash signed App binary after flashing signed bootloader. (IDFGH-10705)

### ISSUE THREAD

**Issue by robokrishan** [espressif/esp-idf#11928]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

## Context:

I am trying to configure **Secure Boot V2** on my ESP32-S3 (*N8R8*) chip. I followed the steps mentioned in the documentation i.e.:
1. Checking the box for `Enable hardware Secure Boot in bootloader` in `Menuconfig` -> `App Signing Scheme`
2. Selecting `Enable Secure Boot version 2` in `Menuconfig` -> `Select secure boot version`
3. Specifying the path to my signing key (ECDSA private key)
4. Selecting `Permanently switch to Secure mode` in `Menuconfig` -> `UART ROM download mode`
5. Building the signed app binary, OTA, and partition table with `idf.py build`
6. Building the signed bootloader with `idf.py bootloader`
7. Flashing the signed bootloader with `idf.py bootloader-flash`

Everything works until this point. The problem arises when I try to flash the app binary, partition table and OTA using `idf.py flash`.

I get the following error logs when I run `idf.py flash`:

```
esptool esp32s3 -p /dev/ttyUSB0 -b 460800 --before=default_reset --after=no_reset --no-stub write_flash --flash_mode dio --flash_freq 80m --flash_size keep 0x100000 embed-reader-firmware-2.bin 0x10000 partition_table/partition-table.bin 0x11000 ota_data_initial.bin
esptool.py v4.5.1
Serial port /dev/ttyUSB0
Connecting....
Chip is ESP32-S3 (revision v0.1)
Features: WiFi, BLE
Crystal is 40MHz
MAC: f4:12:fa:df:30:10
Changing baud rate to 460800
Changed.
Enabling default SPI flash mode...
Configuring flash size...
Flash will be erased from 0x00100000 to 0x00280fff...
Flash will be erased from 0x00010000 to 0x00010fff...
Flash will be erased from 0x00011000 to 0x00012fff...
Erasing flash...

A fatal error occurred: Failed to enter Flash download mode (result was 01060000: Operation or feature not supported)
CMake Error at run_serial_tool.cmake:55 (message):
  
  /home/****/.espressif/python_env/idf5.0_py3.10_env/bin/python;;/home/****/esp/esp-idf/components/esptool_py/esptool/esptool.py;--chip;esp32s3
  failed
```

I have also tried manually entering the command with the `--force` option but I get the same output as above.

**Have I missed a step in configuring Secure Boot V2?**

**Comment by mahavirj** [comment]
@robokrishan 

Please try replacing `--flash_size keep` with the specific flash capacity on your dev board (e.g., `--flash_size 4MB`) and that should fix this issue. Please see prior discussion on this topic here https://github.com/espressif/esp-idf/issues/10959#issuecomment-1519369823
