### ISSUE TITLE
ESP32 does not recover after going below -30ºC (IDFGH-10704)

### ISSUE THREAD

**Issue by jrHernandezSio** [espressif/esp-idf#11927]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

ENVIRONMENT:
espressif32@5.1.1 -> - framework-espidf @ 3.40401.0 (4.4.1)

Chip is ESP32-D0WD (revision 1)

DESCRIPTION:

ESP32 is specified to operate up to -40ºC, but we are experiencing some trouble around -30ºC.
This problem may be related to battery voltage/current drop under these conditions, but the point is the ESP32 does no rocover anymore after temperature goes back to ambient again (25ºC). If there is a problem with the battery the system is supposed to perform a brownout reset (BOR) and start again as soon as the voltage is recovered, but the BOR is not performed.

The system is recovered if the battery is unplugged and plugged again.

Any clue about this?

Regards, Ramon.

**Comment by MaxwellAlan** [comment]
@jrHernandezSio 
Thanks for your reporting.
We have met related issue in some other chips or modules and have fixed these days. Will check for ESP32-D0WD (revision 1).
Thanks.

**Comment by MaxwellAlan** [comment]
Hi @jrHernandezSio 
> This problem may be related to battery voltage/current drop under these conditions, but the point is the ESP32 does no rocover anymore after temperature goes back to ambient again (25ºC).

Could you share some more detail steps to reproduce this issue. 
Our QA team using ESP32-D0WD (revision 1) and IDF v4.4.1 try to reproduce this issue in  -30ºC env, we can not reproduce your issues. Needing some more help from you.
Thanks.

**Comment by jrHernandezSio** [comment]
Hi,

Thanks for the info.

We have detected (under this scenario) a problem with SPI transaction of a NFC transceiver that made the system enter in an infinite loop inside a task. This triggered TWDT, but the system was not reset.

We will disable the NFC in the program and test again at -30ºC.

Regards.

**Comment by MaxwellAlan** [comment]
Hi @jrHernandezSio 

Welcome to reopen if you still meet this issue :)
