### ISSUE TITLE
BLE GATT auto-response is capturing a value, rather than dereferencing the provided value pointer.  (IDFGH-10708)

### ISSUE THREAD

**Issue by cwahn** [espressif/esp-idf#11931]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

I am making a BLE GATT server application with the Blueroid BLE implementation of ESP-IDF. 

I am referencing to BLE HID device [example](https://github.com/espressif/esp-idf/blob/master/examples/bluetooth/bluedroid/ble/ble_hid_device_demo/main/hid_device_le_prf.c#L295). Per the example, it seems like the pointer of the characteristic value(i.e. `battery_lev` ) is what gets returned at the read event if, `ESP_GATT_AUTO_RSP` is set. It did work like that.
 
https://github.com/espressif/esp-idf/blob/9a1cc59338aa151bc6333f85c8169d36a478fe2a/examples/bluetooth/bluedroid/ble/ble_hid_device_demo/main/hid_device_le_prf.c#L295-L309

However, I find out that the response value is static and does not change as the global static value changes. I could debug a bit more and managed to find out that the response is somewhat snapshotting the value some were around the call of `esp_ble_gatts_start_service`. e.g.

```
        ...

        case ESP_GATTS_REG_EVT:
        {
            *ptr = 0x2f;
            auto &services = gatts_profiles[param->reg.app_id].services;
            gatts_ifs[param->reg.app_id] = gatts_if;

            auto create_service = [&](auto service)
            {
                ESP_LOGI(ble_log_tag, "number of service of service %u", service.size());
                *ptr = 0x30;
                esp_ble_gatts_create_attr_tab(&service[0], gatts_if, service.size(), 0);
                *ptr = 0x31;
            };

            for_each(create_service, services);
            *ptr = 0x32;

            break;
        }
        case ESP_GATTS_CREAT_ATTR_TAB_EVT:
        {
            const auto service_handle = *param->add_attr_tab.handles;
            *ptr = 0x33;

            ESP_LOGI(ble_log_tag, "starting svc handle = %x", service_handle);
            esp_ble_gatts_start_service(service_handle);
            *ptr = 0x34;

            break;
        }
        
        ...
```

The characteristic value of concern is holding to pointer the same with `ptr`. And her response is constant `0x34`, even though there are some more mutations for other events.

I suspect that the update of `0x34` is because of the asynchronousness of the implementation, and the value of characteristics is dereferenced and copied by invoking `esp_ble_gatts_start_service` for auto response. 

So, Is this the intended behavior or a bug? Should mutable responses be forged manually at read events and auto-response is for static and constant value only? If the latter is the case, I see the example is somewhat misleading since battery level is definitely dynamic information, not a constant.

**Comment by zhp0406** [comment]
@cwahn 
It is intended behavior.
you can use API "esp_ble_gatts_set_attr_value" to change the value in server database.
