### ISSUE TITLE
[TW#16325] esp_heap_caps.h needs C++ guards

### ISSUE THREAD

**Issue by nkolban** [espressif/esp-idf#1195]
The header file "esp_heap_caps.h" needs C++ guards for usage in C++ apps ...

```
extern "C" {
...
}
```

**Comment by chanibal** [comment]
+1, not having them caused very interesting linker errors for me, today.

**Comment by projectgus** [comment]
This was fixed in fff482ac, sorry we forgot to link the issue when it was merged.

Some related fixes for other heap headers will be merged in the next couple of days.
