### ISSUE TITLE
"coc_bleprph" example program crashes. (IDFGH-10733)

### ISSUE THREAD

**Issue by tony-921** [espressif/esp-idf#11951]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v5.2-dev-1736-ga2d76ad38a

### Operating System used.

Linux

### How did you build your project?

Command line with idf.py

### If you are using Windows, please specify command line type.

None

### Development Kit.

esp32-devkitC-32e

### Power Supply used.

USB

### What is the expected behavior?

The "coc_blerph" shall display all received data .

### What is the actual behavior?

The "coc_blerph" displays a crash trace and reboot.

### Steps to reproduce.

1) Build example "coc_blerph" and "coc"blecent" (ensure to follow "idf.py menuconfig" in the readme.MD file)
2) Have 2 ESP32 kits, with one flashed "coc_blerph", and another with "coc_blecent". 
3) Have the 2 ESP32 devices up. 
4) Once each paired, the "coc_blecent" transmits 512 bytes of data to "coc_blerph" over BLE/L2CAP channel.

The "coc_bleprh" crashes as copied in the "debug logs".

### Debug Logs.

```plain
LE CoC accepting, chan: 0x3ffc357c, peer_mtu 512
LE COC connected, conn: 0, chan: 0x3ffc357c, psm: 0x1002, scid: 0x0040, dcid: 0x0040, our_mps: 248, our_mtu: 512, peer_mps: 248, peer_mtu: 512
Guru Meditation Error: Core  0 panic'ed (LoadProhibited). Exception was unhandled.

Core  0 register dump:
PC      : 0x400e56d3  PS      : 0x00060a30  A0      : 0x800d83c1  A1      : 0x3ffcbcb0  
0x400e56d3: ble_l2cap_coc_rx_fn at /home/tishigami/esp/esp-idf/components/bt/host/nimble/nimble/nimble/host/src/ble_l2cap_coc.c:200

A2      : 0x3ffc358c  A3      : 0x3ffc357c  A4      : 0x000000ca  A5      : 0x3ffcbce4  
A6      : 0x3ffc9218  A7      : 0xb33fffff  A8      : 0x800d79fe  A9      : 0x3ffcbca0  
A10     : 0x00000000  A11     : 0x3ffc9218  A12     : 0x3ffc9344  A13     : 0x3ffcbce4  
A14     : 0x3ffc45ac  A15     : 0xb33fffff  SAR     : 0x00000010  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x00000010  LBEG    : 0x4000c349  LEND    : 0x4000c36b  LCOUNT  : 0x00000000
```

### More Information.

If the data size is reduced down to 10 bytes, the crash is not observed.

The crash is still observed if I replace the "coc_blecent" with a Android phone.

**Comment by rahult-github** [comment]
Hi @tony-921  , we recently made a [fix](https://github.com/espressif/esp-idf/commit/335d707a63c3fb3dbf86764c803ce2dce6c9a9aa) to handle large data  packets for coc application . Can you please try with latest code and confirm ?
