### ISSUE TITLE
What is the status of domain: esp32.info ? (IDFGH-10754)

### ISSUE THREAD

**Issue by gojimmypi** [espressif/esp-idf#11970]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

I have several documentation references to the `esp32.info` domain that appears to now no longer be a valid.

Was that ever an official Espressif domain?

**Comment by igrr** [comment]
Probably not an official one, no... I think it was first posted by Neil Kolban here: https://www.esp32.com/viewtopic.php?t=267#p1152, so I guess it was his initiative at that time. The updates you did in wolfSSL/wolfssl look correct to me!

**Comment by gojimmypi** [comment]
Ok, thanks for the info! Cheers
