### ISSUE TITLE
How to flash .bin file to ESP32-S3 using JTAG pins? (IDFGH-10768)

### ISSUE THREAD

**Issue by radhikaalpha** [espressif/esp-idf#11983]
How to flash .bin file to ESP32-S3 using following JTAG pins?
GPIO39 - MTCK
GPIO40 - MTD0
GPIO41 - MTDI
GPIO42 - MTMS

Which programming utility should be used?
Which programmer supports flashing .bin file using JTAG pins?

**Comment by igrr** [comment]
@radhikaalpha This repository is for bug reports and feature requests for ESP-IDF project, not a general Q&A forum for everything ESP-related. For "how do I..." type of questions, please use [esp32.com](https://esp32.com/) forum.
