### ISSUE TITLE
Correct location of partition table in flash ...

### ISSUE THREAD

**Issue by nkolban** [espressif/esp-idf#120]
I have a gut feel that the partition table is located in flash at flash address 0x8000.  This seems to contradict the address 0x4000 that is listed in the documentation as of the date of this post ... that article can be found here.

http://esp-idf.readthedocs.io/en/latest/partition-tables.html

**Comment by projectgus** [comment]
Thanks @nkolban . We moved the partition table a couple of weeks ago and missed this documentation point.

There's an update in the pipeline for this.

**Comment by nkolban** [comment]
I also seem to find that the old address of 0x4000 is documented in the ESP32-DevKitC getting started guide ... see ... https://espressif.com/sites/default/files/documentation/esp32-devkitc_getting_started_guide_en.pdf

**Comment by projectgus** [comment]
Thanks for reporting that and sorry for the slow turnaround. I've relayed this to the documentation team, the Getting Started guide should be updated soon.
