### ISSUE TITLE
Sample for File Signature (IDFGH-10794)

### ISSUE THREAD

**Issue by franz-ms-muc** [espressif/esp-idf#12005]
### Is your feature request related to a problem?

ESP-IDF Supports several signature verification like for OTA and others. 

### Describe the solution you'd like.

it would be nice to have a Demo how to use this for a custom File. 
so any File with signature, Simple Sample, how to verify.

**Comment by diplfranzhoepfinger** [comment]
I have the Problem that this code: 

https://github.com/diplfranzhoepfinger/example-cpp-cryptographic-license-files/blob/495618b455aa636da35e482b268ccbc17d453e98/cryptographic-license-files/components/cryptographic/main.cpp#L281

does not compile in esp-idf. 

i think i must be rewritten.

**Comment by diplfranzhoepfinger** [comment]
ahhhhhhhhh ... 
using wolfssl like described in the docs, this Code Compiles.

**Comment by mahavirj** [comment]
@franz-ms-muc 

Please refer to mbedTLS [samples apps](https://github.com/Mbed-TLS/mbedtls/blob/development/programs/README.md#ecdsa-and-rsa-signature-examples) that highlights RSA or ECDSA based signature schemes. I think it should be pretty straight forward to implement the verification scheme using the mbedTLS interface. Good part is, if the hardware accelerators are enabled then the corresponding computation shall be handled in the peripheral (as per applicability).

Hope this helps.

**Comment by franz-ms-muc** [comment]
Thanks to your great Support i was able to convert this Calls into mbedTLS: 

[https://github.com/diplfranzhoepfinger/example-cpp-cryptographic-license-files](https://github.com/diplfranzhoepfinger/example-cpp-cryptographic-license-files)  
 

[https://github.com/diplfranzhoepfinger/example-cpp-cryptographic-license-files/blob/9d39fcfbd54817e7267833fc3d7a913c359ca80f/cryptographic-license-files/components/cryptographic/cryptographic_main.cpp#L286C1-L292C26](https://github.com/diplfranzhoepfinger/example-cpp-cryptographic-license-files/blob/9d39fcfbd54817e7267833fc3d7a913c359ca80f/cryptographic-license-files/components/cryptographic/cryptographic_main.cpp#L286C1-L292C26)
