### ISSUE TITLE
BT: How to respond to long/reliable write requests?

### ISSUE THREAD

**Issue by rojer** [espressif/esp-idf#1200]
ESP32 is a GATT server. Client (actually, another ESP32) is trying to perform a Long Write request.
It sends a Prepare Write request (`write.is_prep = 1`) for the first MTU-3 bytes and, according to the BT spec, the server should respond with Prepare Write Response replaying the same data.
however, `esp_ble_gatts_send_response` does not take the value argument and seemingly does not do what is necessary either, since client gives up and sends an Execute Write with `exec_write.exec_write_flag = 0`, aka `ESP_GATT_PREP_WRITE_CANCEL`.

so the question is: how to respond to prepare write requests properly?

**Comment by negativekelvin** [comment]
https://github.com/espressif/esp-idf/blob/master/examples/bluetooth/gatt_server/main/gatts_demo.c#L274

**Comment by rojer** [comment]
oh, good. thanks!
