### ISSUE TITLE
vs code虚拟环境在4.4.5分支出现安装失败问题 (IDFGH-10793)

### ISSUE THREAD

**Issue by caidamao** [espressif/esp-idf#12004]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v4.4.5

### Operating System used.

Windows

### How did you build your project?

Command line with Make

### If you are using Windows, please specify command line type.

None

### What is the expected behavior?

正常安装v4.4.5

### What is the actual behavior?

除python虚拟环境外，所有组件均安装完成

### Steps to reproduce.

1. 使用vs code插件配置功能，采用EXPRESS选项
2. 选中v4.4.5
3. 开始安装，截止虚拟环境前，都正常安装
4. 出现异常Command '['c:\\IDF\\IDF445\\Espressif\\tools\\idf-python\\3.11.2\\python.exe', '-m', 'pip', 'install', '--user', 'virtualenv']' returned non-zero exit status 2.

### More Information.

1.win10专业版本 win11专业版均尝试过，问题可复现
2.v4.3.5似乎也存在此问题。
3.v5.0以上分支是正常可用的

**Comment by dobairoland** [comment]
This has been reported at https://github.com/espressif/vscode-esp-idf-extension/issues/1015 and will be fixed in the vscode plugin. Please follow that issue to get updates.
