### ISSUE TITLE
Unable to erase_flash for ESP32-S3-WROOM-1-N4R2 bare module. (IDFGH-10814)

### ISSUE THREAD

**Issue by whatdtech** [espressif/esp-idf#12025]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Product link is [https://www.digikey.in/en/products/detail/espressif-systems/ESP32-S3-WROOM-1-N4R2/16162643](url).

used commands : `esptool --port COM6 erase_flash`, `esptool --chip esp32s3beta2 --port COM6 erase_flash`, `esptool --chip esp32s3 --port COM7 erase_flash`

Before flash serial output is: 
**rst:0x1 (POWERON),boot:0x3 (DOWNLOAD(USB/UART0))**

while flashing error is: 
**A fatal error occurred: Failed to connect to Espressif device: Timed out waiting for packet header**

As per the documentation 
GPIO 0 & GPIO 46 Connected to ground.

tried by grounding GPIO3 & 45 and some other SPI CS pins too, but no use.

os: windows 10, esptool version 4.6.2
Please suggest me a solution.

**Comment by dobairoland** [comment]
Duplicates https://github.com/espressif/esptool/issues/906
