### ISSUE TITLE
venv gerenation fails on python installed using the nix package manager (IDFGH-10828)

### ISSUE THREAD

**Issue by LukasACH** [espressif/esp-idf#12036]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v5.1

### Operating System used.

macOS

### How did you build your project?

Other (please specify in More Information)

### If you are using Windows, please specify command line type.

None

### What is the expected behavior?

The check for virtual environments should pass, and it should create the virtual environment and not fail with the error `ERROR: This script was called from a virtual environment, can not create a virtual environment again`.

### What is the actual behavior?

The check for a virtual environment in the file idf_tools.py on line 2035 (v5.1) fails when using python installed using the nix package manager, at least on macOS. This is the line that evalutates to `True` where it should probably be `False`, or at least have an additional check before outright failing to create the virtualenv.
```python
is_virtualenv = hasattr(sys, 'real_prefix') or (hasattr(sys, 'base_prefix') and sys.base_prefix != sys.prefix)
```

The paths sys.base_prefix and sys.prefix are not the same, even if no virtual environment is activated.
In a fresh python session, the REPL output looks like this:
```
Python 3.10.12 (main, Jul 18 2023, 17:17:22) [Clang 11.1.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.base_prefix
'/nix/store/bq1q4gk52gsx4fg4pf07f2kxqgazkcls-python3-3.10.12'
>>> sys.prefix
'/nix/store/3f0019fqza36pp2f2znj5sbndhwddpi8-python3-3.10.12-env'
```

### Steps to reproduce.

How to reproduce the bug:
1. Install python using the nix package manager
2. Try to use esp-idf while the above installed python is the default

Workaround:
1. Replace the line with `is_virtualenv = False`
2. Everything works as it should.

### Build or installation Logs.

```plain
Compiling bindgen v0.63.0
   Compiling embuild v0.31.2
   Compiling esp-idf-sys v0.33.1
   Compiling esp-idf-hal v0.41.2
   Compiling esp-idf-svc v0.46.2
   Compiling esp32s2-ctl101-influxdb-bridge-rust v0.1.0 (/path/to/project)
error: failed to run custom build command for `esp-idf-sys v0.33.1`

Caused by:
  process didn't exit successfully: `/path/to/project/target/debug/build/esp-idf-sys-3df210f5f514226e/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-env-changed=ESP_IDF_TOOLS_INSTALL_DIR
  cargo:rerun-if-env-changed=ESP_IDF_SDKCONFIG
  cargo:rerun-if-env-changed=ESP_IDF_SDKCONFIG_DEFAULTS
  cargo:rerun-if-env-changed=MCU
  cargo:rerun-if-env-changed=ESP_IDF_SYS_ROOT_CRATE
  cargo:rerun-if-env-changed=ESP_IDF_VERSION
  cargo:rerun-if-env-changed=ESP_IDF_REPOSITORY
  cargo:rerun-if-env-changed=ESP_IDF_CMAKE_GENERATOR
  cargo:rerun-if-env-changed=IDF_PATH
  cargo:rerun-if-env-changed=EXTRA-COMPONENTS
  cargo:rerun-if-env-changed=ESP_IDF_COMPONENTS
  ESP_IDF_VERSION=5.1
  PATH=/path/to/project/.embuild/espressif/tools/esp32ulp-elf/2.35_20220830/esp32ulp-elf/bin:/path/to/project/.embuild/espressif/tools/cmake/3.24.0/CMake.app/Contents/bin:/path/to/project/.embuild/espressif/tools/ninja/1.10.2/:/path/to/project/.embuild/espressif/esp-idf/v5.1/tools:$PATH
  IDF_DEACTIVATE_FILE_PATH=/var/folders/z1/755fhsss0rv3hqdd686r71xm0000gn/T/tmpg63y2z0ridf_20572

  --- stderr
  Build configuration: BuildConfig {
      esp_idf_tools_install_dir: None,
      esp_idf_sdkconfig: None,
      esp_idf_sdkconfig_defaults: None,
      mcu: None,
      native: NativeConfig {
          esp_idf_version: Some(
              Tag(
                  "v5.1",
              ),
          ),
          esp_idf_repository: None,
          esp_idf_cmake_generator: None,
          idf_path: None,
          extra_components: [],
          esp_idf_components: None,
      },
      esp_idf_sys_root_crate: None,
  }
  Using managed esp-idf repository: RemoteSdk { repo_url: None, git_ref: Tag("v5.1") }
  ERROR: This script was called from a virtual environment, can not create a virtual environment again
  Error: Could not install esp-idf

  Caused by:
      command 'IDF_TOOLS_PATH="/path/to/project/.embuild/espressif" "python3" "/path/to/project/.embuild/espressif/esp-idf/v5.1/tools/idf_tools.py" "--idf-path" "/path/to/project/.embuild/espressif/esp-idf/v5.1" "--non-interactive" "install-python-env"' exited with non-zero status code 1
```

### More Information.

I use esp-idf only as a build dependency while using cargo with esp-rs. The workaround works here as well without any problems. But I have also reproduced the bug using idf.py.

**Comment by DNedic** [comment]
Hello @LukasACH, thank you for your submission. To my knowledge, the cause of this error is the way the Nix package manager works: considering you can have any number of python derivations installed at the same time (different versions of python, with different packages included using `.withPackages` like explained [in the Wiki](https://nixos.wiki/wiki/Python)) using Nix, the Nix package manager creates separate environments for each derivation and installing packages with pip is not supported. 

You can read more about it [here](https://github.com/FRidh/python-on-nix/blob/master/tutorial.md) and [here](https://nixos.org/manual/nixpkgs/stable/#using-python).

If you want to use ESP-IDF with Nix, I would suggest reading the [ESP-IDF wiki page](https://nixos.wiki/wiki/ESP-IDF) and using one of the suggestions, for instance (nixpkgs-esp-dev)[https://github.com/mirrexagon/nixpkgs-esp-dev] flakes or Nix shell files.
This will also give you a fully reproducible environment as a bonus.
