### ISSUE TITLE
Enable to run wifi mesh with ethernet (IDFGH-10833)

### ISSUE THREAD

**Issue by PES-SARJU** [espressif/esp-idf#12040]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Hi experts!
I have an issue in my project, my project have wifi and ethernet together which is working well, now i want to add wifi mesh to it. wifi mesh program is working separately. while merging this code to the wifi and ethernet one, giving an error. my code is attached below please help me how can i do that or any reference to do so.

`static esp_netif_t* wifi_start(void) {
	char *desc;

	/*  tcpip initialization */
	ESP_ERROR_CHECK(esp_netif_init());
	/*  event initialization */
	ESP_ERROR_CHECK(esp_event_loop_create_default());
//	/*  create network interfaces for mesh (only station instance saved for further manipulation, soft AP instance ignored */
	ESP_ERROR_CHECK(esp_netif_create_default_wifi_mesh_netifs(&netif, NULL));

	/*  wifi initialization */
	wifi_init_config_t cfg = WIFI_INIT_CONFIG_DEFAULT();
	ESP_ERROR_CHECK(esp_wifi_init(&cfg));

//    /*
	esp_netif_inherent_config_t esp_netif_config =
			ESP_NETIF_INHERENT_DEFAULT_WIFI_STA();

//    esp_netif_config.if_desc = "STATION";

// Prefix the interface description with the module TAG
// Warning: the interface desc is used in tests to capture actual connection details (IP, gw, mask)
	asprintf(&desc, "%s: %s", WiFi_TAG, esp_netif_config.if_desc);

	ESP_LOGI("", "desc = %s", desc);
	ESP_LOGI("", " esp_netif_config.if_desc = %s", esp_netif_config.if_desc);

	esp_netif_config.if_desc = desc;
	esp_netif_config.route_prio = 128;
	esp_netif_t *netif = esp_netif_create_wifi(WIFI_IF_STA, &esp_netif_config);
	free(desc);

	esp_wifi_set_default_wifi_sta_handlers();
//    */

//    ESP_ERROR_CHECK(esp_event_handler_register(WIFI_EVENT, WIFI_EVENT_STA_DISCONNECTED, &on_wifi_disconnect, NULL));
//    ESP_ERROR_CHECK(esp_event_handler_register(IP_EVENT, IP_EVENT_STA_GOT_IP, &on_got_ip, NULL));

	ESP_ERROR_CHECK(
			esp_event_handler_register(WIFI_EVENT, WIFI_EVENT_STA_DISCONNECTED, &event_handler, NULL));
	ESP_ERROR_CHECK(
			esp_event_handler_register(IP_EVENT, IP_EVENT_STA_GOT_IP, &event_handler, NULL));

#ifdef CONFIG_EXAMPLE_CONNECT_IPV6
    ESP_ERROR_CHECK(esp_event_handler_register(WIFI_EVENT, WIFI_EVENT_STA_CONNECTED, &on_wifi_connect, netif));
    ESP_ERROR_CHECK(esp_event_handler_register(IP_EVENT, IP_EVENT_GOT_IP6, &on_got_ipv6, NULL));
#endif

	ESP_ERROR_CHECK(esp_wifi_set_storage(WIFI_STORAGE_FLASH));
	wifi_config_t wifi_config = { .sta = {
//            .ssid = STR(SPIFFS_STRUCT.SSID),
//            .password = STR(SPIFFS_STRUCT.PASS),
			.scan_method = EXAMPLE_WIFI_SCAN_METHOD, .sort_method =
					EXAMPLE_WIFI_CONNECT_AP_SORT_METHOD, .threshold.rssi =
					CONFIG_EXAMPLE_WIFI_SCAN_RSSI_THRESHOLD,
			.threshold.authmode = EXAMPLE_WIFI_SCAN_AUTH_MODE_THRESHOLD, }, };

	memcpy((wifi_config.sta.ssid), (SPIFFS_STRUCT.SSID),
			sizeof(SPIFFS_STRUCT.SSID));
	memcpy((wifi_config.sta.password), (SPIFFS_STRUCT.PASS),
			sizeof(SPIFFS_STRUCT.SSID));

	char *hostname;

	// Dynamically allocate memory using calloc()
	hostname = (char*) calloc(20, sizeof(char));

	// Check if the memory has been successfully
	// allocated by calloc or not
	if (hostname == NULL) {

		printf("Memory not allocated for hostname");

		exit(0);
	} else {
		printf("\n\nMemory successfully allocated using calloc for hostname\n");

		strcpy(hostname, "DC_");
		strcat(hostname, CHG_STATION_ID);
		esp_netif_set_hostname(netif, hostname);
		free(hostname);

	}

	wifi_event_group = xEventGroupCreate();

	ESP_LOGI(MAIN_TAG, "Connecting to %s...", wifi_config.sta.ssid);
	ESP_ERROR_CHECK(esp_wifi_set_mode(WIFI_MODE_STA));
	ESP_ERROR_CHECK(esp_wifi_set_config(WIFI_IF_STA, &wifi_config));
	ESP_ERROR_CHECK(esp_wifi_start());
	esp_wifi_connect();

	int bits = xEventGroupWaitBits(wifi_event_group, CONNECTED_BIT,
	pdFALSE, pdTRUE, WIFI_CONNECT_TIMEOUT / portTICK_PERIOD_MS);
	ESP_LOGI(WiFi_TAG, "bits=%x", bits);
	if (bits) {
		ESP_LOGI(WiFi_TAG, "WIFI_MODE_STA connected. SSID:%s password:%s",
				wifi_config.sta.ssid, wifi_config.sta.password);
	} else {
		ESP_LOGI(WiFi_TAG,
				"WIFI_MODE_STA can't connected. SSID :%s password:%s",
				wifi_config.sta.ssid, wifi_config.sta.password);
	}

	return netif;
}
`

`static esp_netif_t* eth_start(void) {
	char *desc;

#if DHCP_SERVER == 1

	esp_netif_inherent_config_t esp_netif_config =
			ESP_NETIF_INHERENT_DEFAULT_ETH()
	;

	char *ip = "192.168.1.177";
	char *gateway = "192.168.1.1";
	char *netmask = "255.255.255.0";
	esp_netif_ip_info_t info_t;

	// ip4addr_aton(const char *cp, ip4_addr_t *addr)
	memset(&info_t, 0, sizeof(esp_netif_ip_info_t));
	ip4addr_aton((const char*) ip, &info_t.ip);
	ip4addr_aton((const char*) gateway, &info_t.gw);
	ip4addr_aton((const char*) netmask, &info_t.netmask);

	esp_netif_config.ip_info = &info_t;

	// Prefix the interface description with the module TAG
	// Warning: the interface desc is used in tests to capture actual connection details (IP, gw, mask)
	asprintf(&desc, "%s: %s", ETH_TAG, esp_netif_config.if_desc);

	//       esp_netif_config.get_ip_event = IP_EVENT_ETH_GOT_IP,
//       esp_netif_config.lost_ip_event = 0,

//       /*
	ESP_LOGI("", "desc = %s", desc);
	ESP_LOGI("", " esp_netif_config.if_desc = %s", esp_netif_config.if_desc);

	esp_netif_config.if_desc = desc;
	//  esp_netif_config.route_prio = 128;
	esp_netif_config.flags = ESP_NETIF_DHCP_SERVER | ESP_NETIF_FLAG_AUTOUP;

	esp_netif_config_t netif_config = { .base = &esp_netif_config, .stack =
			ESP_NETIF_NETSTACK_DEFAULT_ETH

	};

	netif = esp_netif_new(&netif_config);
	assert(netif);
	free(desc);
	esp_netif_dhcpc_stop(netif);

	esp_netif_set_ip_info(netif, &info_t);
//*/

#elif DHCP_SERVER == 0

    esp_netif_inherent_config_t esp_netif_config = ESP_NETIF_INHERENT_DEFAULT_ETH();

    // Prefix the interface description with the module TAG
    // Warning: the interface desc is used in tests to capture actual connection details (IP, gw, mask)
    asprintf(&desc, "%s: %s", ETH_TAG, esp_netif_config.if_desc);
    esp_netif_config.if_desc = desc;
    esp_netif_config.route_prio = 64;
    esp_netif_config_t netif_config = {
        .base = &esp_netif_config,
        .stack = ESP_NETIF_NETSTACK_DEFAULT_ETH
    };
    esp_netif_t *netif = esp_netif_new(&netif_config);
    assert(netif);
    free(desc);
#endif

	eth_mac_config_t mac_config = ETH_MAC_DEFAULT_CONFIG();
	mac_config.rx_task_stack_size = 4096;

	eth_phy_config_t phy_config = ETH_PHY_DEFAULT_CONFIG();
	phy_config.phy_addr = CONFIG_EXAMPLE_ETH_PHY_ADDR;
	phy_config.reset_gpio_num = W5500_PHY_RST_GPIO;

#if CONFIG_EXAMPLE_USE_INTERNAL_ETHERNET
    mac_config.smi_mdc_gpio_num = CONFIG_EXAMPLE_ETH_MDC_GPIO;
    mac_config.smi_mdio_gpio_num = CONFIG_EXAMPLE_ETH_MDIO_GPIO;
    s_mac = esp_eth_mac_new_esp32(&mac_config);
#if CONFIG_EXAMPLE_ETH_PHY_IP101
    s_phy = esp_eth_phy_new_ip101(&phy_config);
#elif CONFIG_EXAMPLE_ETH_PHY_RTL8201
    s_phy = esp_eth_phy_new_rtl8201(&phy_config);
#elif CONFIG_EXAMPLE_ETH_PHY_LAN87XX
    s_phy = esp_eth_phy_new_lan87xx(&phy_config);
#elif CONFIG_EXAMPLE_ETH_PHY_DP83848
    s_phy = esp_eth_phy_new_dp83848(&phy_config);
#endif
#elif CONFIG_EXAMPLE_USE_SPI_ETHERNET

	gpio_install_isr_service(0);
	spi_device_handle_t spi_handle = NULL;
	spi_bus_config_t buscfg = { .miso_io_num = W5500_SPI_MISO_GPIO,
			.mosi_io_num = W5500_SPI_MOSI_GPIO, .sclk_io_num =
					W5500_SPI_SCLK_GPIO, .quadwp_io_num = -1, .quadhd_io_num =
					-1, };
	ESP_ERROR_CHECK(
			spi_bus_initialize(CONFIG_EXAMPLE_ETH_SPI_HOST, &buscfg, W5500_SPI_DMA_CHANNEL));
#if CONFIG_EXAMPLE_USE_DM9051
    spi_device_interface_config_t devcfg = {
        .command_bits = 1,
        .address_bits = 7,
        .mode = 0,
        .clock_speed_hz = CONFIG_EXAMPLE_ETH_SPI_CLOCK_MHZ * 1000 * 1000,
        .spics_io_num = CONFIG_EXAMPLE_ETH_SPI_CS_GPIO,
        .queue_size = 20
    };
    ESP_ERROR_CHECK(spi_bus_add_device(CONFIG_EXAMPLE_ETH_SPI_HOST, &devcfg, &spi_handle));
    /* dm9051 ethernet driver is based on spi driver */
    eth_dm9051_config_t dm9051_config = ETH_DM9051_DEFAULT_CONFIG(spi_handle);
    dm9051_config.int_gpio_num = CONFIG_EXAMPLE_ETH_SPI_INT_GPIO;
    s_mac = esp_eth_mac_new_dm9051(&dm9051_config, &mac_config);
    s_phy = esp_eth_phy_new_dm9051(&phy_config);
#elif CONFIG_EXAMPLE_USE_W5500
	spi_device_interface_config_t devcfg = {
			.command_bits = 16, // Actually it's the address phase in W5500 SPI frame
			.address_bits = 8, // Actually it's the control phase in W5500 SPI frame
			.mode = 0, .clock_speed_hz = W5500_SPI_CLOCK_MHZ * 1000 * 1000,
			.spics_io_num = W5500_SPI_CS_GPIO, .queue_size = 20 };
	ESP_ERROR_CHECK(
			spi_bus_add_device(CONFIG_EXAMPLE_ETH_SPI_HOST, &devcfg, &spi_handle));
	/* w5500 ethernet driver is based on spi driver */
	eth_w5500_config_t w5500_config = ETH_W5500_DEFAULT_CONFIG(spi_handle);
	w5500_config.int_gpio_num = W5500_SPI_INT_GPIO;

	s_mac = esp_eth_mac_new_w5500(&w5500_config, &mac_config);
	s_phy = esp_eth_phy_new_w5500(&phy_config);
#endif
#elif CONFIG_EXAMPLE_USE_OPENETH
    phy_config.autonego_timeout_ms = 100;
    s_mac = esp_eth_mac_new_openeth(&mac_config);
    s_phy = esp_eth_phy_new_dp83848(&phy_config);
#endif

	// Install Ethernet driver
	esp_eth_config_t config = ETH_DEFAULT_CONFIG(s_mac, s_phy);
	ESP_ERROR_CHECK(esp_eth_driver_install(&config, &s_eth_handle));
#if !CONFIG_EXAMPLE_USE_INTERNAL_ETHERNET
	/* The SPI Ethernet module might doesn't have a burned factory MAC address, we cat to set it manually.
	 02:00:00 is a Locally Administered OUI range so should not be used except when testing on a LAN under your control.
	 */
	ESP_ERROR_CHECK(
			esp_eth_ioctl(s_eth_handle, ETH_CMD_S_MAC_ADDR, (uint8_t[] ) { 0x02,
							0x00, 0x00, 0x12, 0x34, 0x56 }));
#endif
	// combine driver with netif
	s_eth_glue = esp_eth_new_netif_glue(s_eth_handle);
	esp_netif_attach(netif, s_eth_glue);

	// Register user defined event handers
	//  ESP_ERROR_CHECK(esp_event_handler_register(IP_EVENT, IP_EVENT_ETH_GOT_IP, &on_got_ip, NULL));

	/*  ESP_ERROR_CHECK(esp_event_handler_instance_register(IP_EVENT,
	 ESP_EVENT_ANY_ID,
	 &ETHERNET_EVENT_HANDLER,
	 NULL,
	 NULL));
	 */

	ESP_ERROR_CHECK(
			esp_event_handler_instance_register(ETH_EVENT, ETHERNET_EVENT_CONNECTED, &eth_connection_status, NULL,NULL));
	ESP_ERROR_CHECK(
			esp_event_handler_instance_register(ETH_EVENT, ETHERNET_EVENT_DISCONNECTED, &eth_connection_status, NULL,NULL));
	ESP_ERROR_CHECK(
			esp_event_handler_instance_register(IP_EVENT, IP_EVENT_AP_STAIPASSIGNED, &eth_event_handler, NULL, NULL));

#ifdef CONFIG_EXAMPLE_CONNECT_IPV6
    ESP_ERROR_CHECK(esp_event_handler_register(ETH_EVENT, ETHERNET_EVENT_CONNECTED, &on_eth_event, netif));
    ESP_ERROR_CHECK(esp_event_handler_register(IP_EVENT, IP_EVENT_GOT_IP6, &on_got_ipv6, NULL));
#endif

	esp_eth_start(s_eth_handle);
	return netif;
}
`

`/* set up connection, Wi-Fi and/or Ethernet */
static void start(void) {

#if CONFIG_EXAMPLE_CONNECT_WIFI

	wifi_start();

// s_active_interfaces++;
#endif

#if CONFIG_EXAMPLE_CONNECT_ETHERNET
	s_example_esp_netif = eth_start();
	s_active_interfaces++;
#endif

//#if CONFIG_EXAMPLE_CONNECT_WIFI && CONFIG_EXAMPLE_CONNECT_ETHERNET
//    /* if both intefaces at once, clear out to indicate that multiple netifs are active */
//    s_example_esp_netif = NULL;
//#endif

#if EXAMPLE_DO_CONNECT
	/* create semaphore if at least one interface is active */
	s_semph_get_ip_addrs = xSemaphoreCreateCounting(
			NR_OF_IP_ADDRESSES_TO_WAIT_FOR, 0);
#endif
}`

`esp_err_t example1_connect(void) {
#if EXAMPLE_DO_CONNECT
	if (s_semph_get_ip_addrs != NULL) {
		return ESP_ERR_INVALID_STATE;
	}
#endif

//    ESP_ERROR_CHECK(esp_netif_init());
//    ESP_ERROR_CHECK(esp_event_loop_create_default());

	start();

	ESP_ERROR_CHECK(esp_register_shutdown_handler(&stop));

	ESP_LOGI(MAIN_TAG, "Configuring IP");

#if DHCP_SERVER == 0
    for (int i = 0; i < NR_OF_IP_ADDRESSES_TO_WAIT_FOR; ++i) {
        xSemaphoreTake(s_semph_get_ip_addrs, portMAX_DELAY);
    }

    // iterate over active interfaces, and print out IPs of "our" netifs
    esp_netif_t *netif = NULL;
    esp_netif_ip_info_t ip;

    for (int i = 0; i < esp_netif_get_nr_of_ifs(); ++i) {
        netif = esp_netif_next(netif);
        if (is_our_netif(ETH_TAG, netif)) {
            ESP_LOGI(ETH_TAG, "CONNECT.C : Connected to %s", esp_netif_get_desc(netif));
            ESP_ERROR_CHECK(esp_netif_get_ip_info(netif, &ip));
        //    ETHERNET_IPV4_ADDRESS = ip.ip.addr;
            ESP_LOGI(ETH_TAG, "CONNECT.C : - IPv4 address: " IPSTR, IP2STR(&ip.ip));

#ifdef CONFIG_EXAMPLE_CONNECT_IPV6
            esp_ip6_addr_t ip6[MAX_IP6_ADDRS_PER_NETIF];
            int ip6_addrs = esp_netif_get_all_ip6(netif, ip6);
            for (int j = 0; j < ip6_addrs; ++j) {
                esp_ip6_addr_type_t ipv6_type = esp_netif_ip6_get_addr_type(&(ip6[j]));
                ESP_LOGI(TAG, "- IPv6 address: " IPV6STR ", type: %s", IPV62STR(ip6[j]), s_ipv6_addr_types[ipv6_type]);
            }
#endif

        }
    }
#endif

	return ESP_OK;
}`

`void WIFI_MESH_INIT(void)
{
#if 0
    /*  tcpip initialization */
    ESP_ERROR_CHECK(esp_netif_init());
    /*  event initialization */
    ESP_ERROR_CHECK(esp_event_loop_create_default());
    /*  create network interfaces for mesh (only station instance saved for further manipulation, soft AP instance ignored */
    ESP_ERROR_CHECK(esp_netif_create_default_wifi_mesh_netifs(&netif, NULL));

    /* wifi initialization */
    wifi_init_config_t config = WIFI_INIT_CONFIG_DEFAULT();
    ESP_ERROR_CHECK(esp_wifi_init(&config));
    ESP_ERROR_CHECK(esp_event_handler_register(IP_EVENT, IP_EVENT_STA_GOT_IP, &ip_event_handler, NULL));
    ESP_ERROR_CHECK(esp_wifi_set_storage(WIFI_STORAGE_FLASH));
    ESP_ERROR_CHECK(esp_wifi_start());

#else
	ESP_ERROR_CHECK(example1_connect());

	while(!IS_WIFI_GOT_IP) // waits until mesh is not connected.
	{
		vTaskDelay(1000 / portTICK_RATE_MS);
	}

#endif

	/*  mesh initialization */
	ESP_ERROR_CHECK(esp_mesh_init());
	ESP_ERROR_CHECK(
			esp_event_handler_register(MESH_EVENT, ESP_EVENT_ANY_ID,
					&mesh_event_handler, NULL));

	/*  set mesh topology */
	ESP_ERROR_CHECK(esp_mesh_set_topology(CONFIG_MESH_TOPOLOGY));
	/*  set mesh max layer according to the topology */
	ESP_ERROR_CHECK(esp_mesh_set_max_layer(CONFIG_MESH_MAX_LAYER));
	ESP_ERROR_CHECK(esp_mesh_set_vote_percentage(1));
	ESP_ERROR_CHECK(esp_mesh_set_xon_qsize(128));

#ifdef CONFIG_MESH_ENABLE_PS
	/* Enable mesh PS function */
	ESP_ERROR_CHECK(esp_mesh_enable_ps());
	/* better to increase the associate expired time, if a small duty cycle is set. */
	ESP_ERROR_CHECK(esp_mesh_set_ap_assoc_expire(10));//60
	/* better to increase the announce interval to avoid too much management traffic, if a small duty cycle is set. */
	ESP_ERROR_CHECK(esp_mesh_set_announce_interval(500, 3000));// (600,3300));
#else
	/* Disable mesh PS function */
	ESP_ERROR_CHECK(esp_mesh_disable_ps());
	ESP_ERROR_CHECK(esp_mesh_set_ap_assoc_expire(10));
#endif

	mesh_cfg_t cfg = MESH_INIT_CONFIG_DEFAULT();
	/* mesh ID */
	memcpy((uint8_t*) &cfg.mesh_id, MESH_ID, 6);
	/* router */
	cfg.channel = CONFIG_MESH_CHANNEL;
	cfg.router.ssid_len = strlen((SPIFFS_STRUCT.SSID));
	memcpy((uint8_t*) &cfg.router.ssid, (SPIFFS_STRUCT.SSID),
			cfg.router.ssid_len);
	memcpy((uint8_t*) &cfg.router.password, (SPIFFS_STRUCT.PASS),
			strlen(SPIFFS_STRUCT.PASS));
	/* mesh softAP */
	ESP_ERROR_CHECK(esp_mesh_set_ap_authmode(CONFIG_MESH_AP_AUTHMODE));
	cfg.mesh_ap.max_connection = CONFIG_MESH_AP_CONNECTIONS;
	cfg.mesh_ap.nonmesh_max_connection = CONFIG_MESH_NON_MESH_AP_CONNECTIONS;
	memcpy((uint8_t*) &cfg.mesh_ap.password, CONFIG_MESH_AP_PASSWD,
			strlen(CONFIG_MESH_AP_PASSWD));
	ESP_ERROR_CHECK(esp_mesh_set_config(&cfg));
	/* mesh start */
	ESP_ERROR_CHECK(esp_mesh_start());
#ifdef CONFIG_MESH_ENABLE_PS
    /* set the device active duty cycle. (default:10, MESH_PS_DEVICE_DUTY_REQUEST) */
    ESP_ERROR_CHECK(esp_mesh_set_active_duty_cycle(CONFIG_MESH_PS_DEV_DUTY, CONFIG_MESH_PS_DEV_DUTY_TYPE));
    /* set the network active duty cycle. (default:10, -1, MESH_PS_NETWORK_DUTY_APPLIED_ENTIRE) */
    ESP_ERROR_CHECK(esp_mesh_set_network_duty_cycle(CONFIG_MESH_PS_NWK_DUTY, CONFIG_MESH_PS_NWK_DUTY_DURATION, CONFIG_MESH_PS_NWK_DUTY_RULE));
#endif
	ESP_LOGI(MESH_TAG, "mesh starts successfully, heap:%d, %s<%d>%s, ps:%d\n",
			esp_get_minimum_free_heap_size(),
			esp_mesh_is_root_fixed() ? "root fixed" : "root not fixed",
			esp_mesh_get_topology(),
			esp_mesh_get_topology() ? "(chain)" : "(tree)",
			esp_mesh_is_ps_enabled());
}
`
Thanks in advance,
sarju

**Comment by PES-SARJU** [comment]
here is the error which i'm getting and after that controller is restarting again and again.

error " E (2791) esp_netif_lwip: esp_netif_new: Failed to configure netif with config=0x3ffc2120 (config or if_key is NULL or duplicate key) error"

**Comment by PES-SARJU** [comment]
@mahavirj  please reply.

Thanks in advance.

**Comment by kostaond** [comment]
It seems that ESP Netif with key `WIFI_STA_DEF` has been already created by `ESP_ERROR_CHECK(esp_netif_create_default_wifi_mesh_netifs(&netif, NULL));` which you called prior `esp_netif_t *netif = esp_netif_create_wifi(WIFI_IF_STA, &esp_netif_config);`

**Comment by kostaond** [comment]
@PES-SARJU have you checked my observation above? You are trying to initialize STA netif twice.

**Comment by PES-SARJU** [comment]
Thanks for reply @kostaond, I'll get back to you after checking.

**Comment by kostaond** [comment]
I am closing the issue since the problem seems to be in the user's code. @PES-SARJU feel free to reopen if you think there is an issue with ESP-IDF and provide more detailed description. If you need a general advice, it is preferred way to ask on ESP32 forum at www.esp32.com.  Thank you for understanding.
