### ISSUE TITLE
esp32-C6 无法对 ADC 电压进行校准 (IDFGH-10837)

### ISSUE THREAD

**Issue by woshiwstt50123** [espressif/esp-idf#12044]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

https://docs.espressif.com/projects/esp-idf/zh_CN/v5.1/esp32c6/api-reference/peripherals/adc_calibration.html

这篇文章里提到的校准驱动器无法应用到 esp32-C6 上，esp32-C6 只能获得 ADC 读到的数字而不能获得和数值对应的电压值。

**Comment by ginkgm** [comment]
Hi @woshiwstt50123,
我们怀疑你手上的ESP32-C6芯片是未经校准的样片。请按照以下方法进行检查：

`espefuse.py summary --port  [your port] `

如果显示的 BLK_VERSION_MINOR, BLK_VERSION_MAJOR 均为0，则代表您拿到的是未经校准的样片。

 ESP32-C6 系列批量出货已进行 ADC校准，前期样品销售的产品尚未进行ADC校准。 您可以查看采购平台，是否有样品或未ADC校准的标识说明；开发板实物底部有 sample 标签为未 ADC校准。如有其他疑问，可以联系乐鑫客户支持团队（sales@espressif.com) ，告知采购平台、采购记录、产品实物图片等信息，进一步确认和处理。  

I guess your ESP32-C6 is a non-calibrated sample. Please check with the following process:

`espefuse.py summary --port  [your port] `

It means your product is a non-calibrated sample, if the displayed BLK_VERSION_MINOR, BLK_VERSION_MAJOR are both 0.

Mass production version of ESP32-C6 series has already provided the calibration characteristics. However, earlier products sold as samples hasn't been calibrated yet. You may check the sales channel to see if your products have marks like "Sample" or "Not calibrated". If your development board have "sample" label, it also mean that it's not calibrated yet.

If you have other questions, you may also contact customer Espressif support team (sales@espressif.com), providing your sales channel, record, and pictures of your product, we will help you check it.
