### ISSUE TITLE
BT GATTS: How to tell when client subscribed to notifications?

### ISSUE THREAD

**Issue by rojer** [espressif/esp-idf#1204]
My application is a GATT server and it can send notifications in certain cases.
However, i would like to know if the client actually subscribed/registered to receive them, as i don't want to waste resources unless client is actually subscribed.
I don't see any GATTS event raised when client registers for notifications, so - is there any other way to tell?

**Comment by negativekelvin** [comment]
It should come as ESP_GATTS_WRITE_EVT for CCCD

**Comment by rojer** [comment]
i have handlers for all the GATTS events and notification reg/unreg do not seem trigger any of them at present.

**Comment by negativekelvin** [comment]
A writable descriptor that allows client to configure notifications for that characteristic

**Comment by rojer** [comment]
um... so, as a service, am i supposed to do anything special to receive those events?
notifications themselves work fine - when i send them (blindly), the clients receives them just fine.
but i don't get any GATTS events when client regs/unregs.

**Comment by negativekelvin** [comment]
https://github.com/espressif/esp-idf/blob/master/examples/bluetooth/gatt_server/main/gatts_demo.c#L367

**Comment by rojer** [comment]
that... is not obvious :)
but really, i should re-examine the examples again, looks like they've changed a lot.

but i'm definitely not seeing write events, i would've. weird. but i need to verify that my client (BLE Scanner app) actually sends them.

**Comment by negativekelvin** [comment]
Client will not register if it doesn't discover CCCD

**Comment by rojer** [comment]
figured it out, thanks!
