### ISSUE TITLE
WIFI MESH update mesh_data_t size with received bytes when using esp_mesh_recv()  (IDFGH-10850)

### ISSUE THREAD

**Issue by DarmorGamz** [espressif/esp-idf#12054]
### Is your feature request related to a problem?

Requiring a checksum byte in every packet to verify payload size. Can be prevented/assisted if received bytes was available.

### Describe the solution you'd like.

Can be prevented if mesh_data_t size is buffer size as an input, and received bytes as an output.

**Comment by zhangyanjiaoesp** [comment]
@DarmorGamz There is CRC check in the WiFi MAC layer to ensure data integrity and reliability. We won't add the checksum byte in the `mesh_data_t`. If you really want it, you can add this check on the application layer.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, feel free to reopen.
