### ISSUE TITLE
ESP32-S3 Does not boot and keeps cycling before entering user code (IDFGH-10847)

### ISSUE THREAD

**Issue by Divraj-Dev** [espressif/esp-idf#12051]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v5.0.2

### Operating System used.

Windows

### How did you build your project?

VS Code IDE

### If you are using Windows, please specify command line type.

PowerShell

### Development Kit.

ESP32-S3-WROOM1

### Power Supply used.

USB

### What is the expected behavior?

The device should boot the helloWorld Example.

### What is the actual behavior?

I have two identical ESP32-S3 boards running the same helloWorld program. After flashing the program, one of the devices shows  repeats the following error:

`ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0x15 (USB_UART_CHIP_RESET),boot:0x28 (SPI_FAST_FLASH_BOOT)
Saved PC:0x403cf2cb
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fce3810,len:0x1658
load:0x403c9700,len:0xbe0
load:0x403cc700,len:0x2d9c
entry 0x403c9900`

The log above keeps repeating.

### Steps to reproduce.

1. Steps may be hard to reproduce as this does not happen to my second device

### Debug Logs.

```plain
`ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0x15 (USB_UART_CHIP_RESET),boot:0x28 (SPI_FAST_FLASH_BOOT)
Saved PC:0x403cf2cb
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fce3810,len:0x1658
load:0x403c9700,len:0xbe0
load:0x403cc700,len:0x2d9c
entry 0x403c9900`
```

### More Information.

Is this a faulty Chip? 

I tried running my own code, this worked for the device that is always working but did not for this faulty one, however addtionally i saw that the device disconnects from the computer aswell as rebooting (which it doesnt with the helloworld one)

**Comment by sudeep-mohanty** [comment]
Closing this issue as it doesn't seem to be a bug with ESP-IDF. Please feel free to open a new issue if further support is needed. Thanks.
