### ISSUE TITLE
Wi-Fi antenna soft switch example has a runtime fault, also doesn't work on ESP32-S3 (IDFGH-10851)

### ISSUE THREAD

**Issue by sbuto1** [espressif/esp-idf#12055]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v5.1

### Operating System used.

Linux

### How did you build your project?

VS Code IDE

### If you are using Windows, please specify command line type.

None

### Development Kit.

ESP32-S3-DevKitC-1U v1.0

### Power Supply used.

USB

### What is the expected behavior?

The WiFi antenna soft switch example runs as described in the example README; antenna control GPIO lines are set to appropriate levels and switch as during RX/TX based on the current antenna control configuration. 

### What is the actual behavior?

For the (default) esp32 target, the program compiles but encounters a critical error and reboots once it reaches antenna_switch_example_main.c" line 183:
`esp_wifi_set_ant_soft_switch(&wifi_antenna_auto_switch_config)`

The error occurs in antenna_switch.c, line 279: 
`ESP_RETURN_ON_FALSE(config->ant_num < ANT_TOTAL_MAX, ESP_ERR_INVALID_ARG, TAG, "antenna nunmbers error!");`

The input is 3, while ANT_TOTAL_MAX is 2 (defined in the ant_mun_t enum in antenna_switch.h), which fails the assertion.

In addition, the antenna pin control does not work when the target is switched to the ESP32-S3, at least when tested on a ESP32-S3-DevKitC-1U v1.0 development kit (based on the ESP32-S3-WROOM-1U-N8R2 module). The specified GPIOs simply remain in their default state, which is typically low. 

### Steps to reproduce.

1. Run the Wi-Fi antenna soft switch Example: https://github.com/espressif/esp-idf/tree/release/v5.1/examples/wifi/antenna
2. Observe the console output.
3. After applying the suggested fix, observe the antenna control GPIO pins

### Debug Logs.

```plain
Rebooting...
ets Jul 29 2019 12:21:46

rst:0xc (SW_CPU_RESET),boot:0x1e (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:7084
ho 0 tail 12 room 4
load:0x40078000,len:15576
ho 0 tail 12 room 4
load:0x40080400,len:4
0x40080400: _init at ??:?

load:0x40080404,len:3876
entry 0x4008064c
I (32) boot: ESP-IDF v5.1-dirty 2nd stage bootloader
I (33) boot: compile time Aug 10 2023 14:20:52
I (33) boot: Multicore bootloader
I (37) boot: chip revision: v3.0
I (41) boot.esp32: SPI Speed      : 40MHz
I (46) boot.esp32: SPI Mode       : DIO
I (50) boot.esp32: SPI Flash Size : 2MB
I (55) boot: Enabling RNG early entropy source...
I (60) boot: Partition Table:
I (64) boot: ## Label            Usage          Type ST Offset   Length
I (71) boot:  0 nvs              WiFi data        01 02 00009000 00006000
I (79) boot:  1 phy_init         RF data          01 01 0000f000 00001000
I (86) boot:  2 factory          factory app      00 00 00010000 00100000
I (94) boot: End of partition table
I (98) esp_image: segment 0: paddr=00010020 vaddr=3f400020 size=20004h (131076) map
I (154) esp_image: segment 1: paddr=0003002c vaddr=3ffb0000 size=036c8h ( 14024) load
I (160) esp_image: segment 2: paddr=000336fc vaddr=40080000 size=0c91ch ( 51484) load
I (181) esp_image: segment 3: paddr=00040020 vaddr=400d0020 size=7fa9ch (522908) map
I (370) esp_image: segment 4: paddr=000bfac4 vaddr=4008c91c size=08ca0h ( 36000) load
I (396) boot: Loaded app from partition at offset 0x10000
I (396) boot: Disabling RNG early entropy source...
I (408) cpu_start: Multicore app
I (408) cpu_start: Pro cpu up.
I (408) cpu_start: Starting app cpu, entry point is 0x4008136c
0x4008136c: call_start_cpu1 at /home/test/esp-idf/components/esp_system/port/cpu_start.c:154

I (395) cpu_start: App cpu up.
I (426) cpu_start: Pro cpu start user code
I (426) cpu_start: cpu freq: 160000000 Hz
I (426) cpu_start: Application information:
I (431) cpu_start: Project name:     wifi_antenna
I (436) cpu_start: App version:      1
I (441) cpu_start: Compile time:     Aug 10 2023 14:20:44
I (447) cpu_start: ELF file SHA256:  95a9fc38c892c323...
I (453) cpu_start: ESP-IDF:          v5.1-dirty
I (458) cpu_start: Min chip rev:     v0.0
I (463) cpu_start: Max chip rev:     v3.99 
I (468) cpu_start: Chip rev:         v3.0
I (472) heap_init: Initializing. RAM available for dynamic allocation:
I (480) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM
I (486) heap_init: At 3FFB7788 len 00028878 (162 KiB): DRAM
I (492) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM
I (498) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
I (505) heap_init: At 400955BC len 0000AA44 (42 KiB): IRAM
I (512) spi_flash: detected chip: generic
I (515) spi_flash: flash io: dio
W (519) spi_flash: Detected size(4096k) larger than the size in the binary image header(2048k). Using the size in the binary image header.
I (533) app_start: Starting scheduler on CPU0
I (538) app_start: Starting scheduler on CPU1
I (538) main_task: Started on CPU0
I (548) main_task: Calling app_main()
I (598) multi-antenna example: ESP_WIFI_MODE_STA
I (608) wifi:wifi driver task: 3ffbf90c, prio:23, stack:6656, core=0
I (628) wifi:wifi firmware version: b2f1f86
I (628) wifi:wifi certification version: v7.0
I (628) wifi:config NVS flash: enabled
I (628) wifi:config nano formating: disabled
I (638) wifi:Init data frame dynamic rx buffer num: 32
I (638) wifi:Init management frame dynamic rx buffer num: 32
I (648) wifi:Init management short buffer num: 32
I (648) wifi:Init dynamic tx buffer num: 32
I (658) wifi:Init static rx buffer size: 1600
I (658) wifi:Init static rx buffer num: 10
I (658) wifi:Init dynamic rx buffer num: 32
I (668) wifi_init: rx ba win: 6
I (668) wifi_init: tcpip mbox: 32
I (678) wifi_init: udp mbox: 6
I (678) wifi_init: tcp mbox: 6
I (678) wifi_init: tcp tx win: 5744
I (688) wifi_init: tcp rx win: 5744
I (688) wifi_init: tcp mss: 1440
I (698) wifi_init: WiFi IRAM OP enabled
I (698) wifi_init: WiFi RX IRAM OP enabled
I (708) phy_init: phy_version 4670,719f9f6,Feb 18 2021,17:07:07
I (808) wifi:mode : sta (a8:03:2a:ec:00:78)
I (808) wifi:enable tsf
I (808) multi-antenna example: wifi_init_sta finished.
I (818) wifi:new:<11,0>, old:<1,0>, ap:<255,255>, sta:<11,0>, prof:8
I (818) wifi:state: init -> auth (b0)
I (828) wifi:state: auth -> assoc (0)
E (828) wifi:Association refused temporarily, comeback time 1499 mSec
I (2328) wifi:state: assoc -> assoc (0)
I (2348) wifi:state: assoc -> init (6c0)
I (2348) wifi:new:<11,0>, old:<11,0>, ap:<255,255>, sta:<11,0>, prof:8
I (2348) multi-antenna example: retry to connect to the AP
I (2348) multi-antenna example: connect to the AP fail
I (4758) multi-antenna example: retry to connect to the AP
I (4758) multi-antenna example: connect to the AP fail
I (4768) wifi:new:<11,0>, old:<11,0>, ap:<255,255>, sta:<11,0>, prof:8
I (4768) wifi:state: init -> auth (b0)
I (4778) wifi:state: auth -> assoc (0)
I (4788) wifi:state: assoc -> run (10)
I (4838) wifi:connected with myssid, aid = 1, channel 11, BW20, bssid = 6a:5e:33:21:ad:64
I (4848) wifi:security: WPA2-PSK, phy: bgn, rssi: -29
I (4848) wifi:pm start, type: 1

I (4878) wifi:<ba-add>idx:0 (ifx:0, 6a:5e:33:21:ad:64), tid:0, ssn:0, winSize:64
I (4908) wifi:AP's beacon interval = 102400 us, DTIM period = 2
I (5848) esp_netif_handlers: sta ip: 192.168.50.57, mask: 255.255.255.0, gw: 192.168.50.87
I (5848) multi-antenna example: got ip:192.168.50.57
I (5848) multi-antenna example: connected to ap SSID:myssid password:mypassword
I (5858) multi-antenna example: GPIO: [0].pin = 21, [1].pin = 22
E (5868) ANTENNA_SWITCH_EXAMPLE: esp_wifi_set_ant_soft_switch(279): antenna nunmbers error!
ESP_ERROR_CHECK failed: esp_err_t 0x102 (ESP_ERR_INVALID_ARG) at 0x400d5bb9
0x400d5bb9: app_main at /home/test/ESP32/antenna/main/antenna_switch_example_main.c:183 (discriminator 1)

file: "./main/antenna_switch_example_main.c" line 183
func: app_main
expression: esp_wifi_set_ant_soft_switch(&wifi_antenna_auto_switch_config)

abort() was called at PC 0x40088c43 on core 0
0x40088c43: _esp_error_check_failed at /home/test/esp-idf/components/esp_system/esp_err.c:50



Backtrace: 0x400819c2:0x3ffb9950 0x40088c4d:0x3ffb9970 0x4008fc1a:0x3ffb9990 0x40088c43:0x3ffb9a00 0x400d5bb9:0x3ffb9a30 0x4014dc63:0x3ffb9a80 0x4008b62d:0x3ffb9ab0
0x400819c2: panic_abort at /home/test/esp-idf/components/esp_system/panic.c:452

0x40088c4d: esp_system_abort at /home/test/esp-idf/components/esp_system/port/esp_system_chip.c:84

0x4008fc1a: abort at /home/test/esp-idf/components/newlib/abort.c:38

0x40088c43: _esp_error_check_failed at /home/test/esp-idf/components/esp_system/esp_err.c:50

0x400d5bb9: app_main at /home/test/ESP32/antenna/main/antenna_switch_example_main.c:183 (discriminator 1)

0x4014dc63: main_task at /home/test/esp-idf/components/freertos/app_startup.c:208 (discriminator 13)

0x4008b62d: vPortTaskWrapper at /home/test/esp-idf/components/freertos/FreeRTOS-Kernel/portable/xtensa/port.c:162
```

### More Information.

There appears to be an error in the Wi-Fi antenna soft switch example that was added in ESP-IDF v5.1:, https://github.com/espressif/esp-idf/tree/release/v5.1/examples/wifi/antenna

For the (default) esp32 target, the program compiles but encounters a critical error and reboots as described above.

There are a few possible ways to fix this but I think the simplest might be to simply update antenna_switch_example_main.c line 178 from "wifi_antenna_auto_switch_config.ant_num = 3;" to "wifi_antenna_auto_switch_config.ant_num = ANT_TOTAL_THREE;"

After this fix the wifi antenna control appears to work as expected on the ESP-WROVER-KIT V4.1 development board (Note that GPIO pins set in 'ant_gpio_config' may need to be updated depending on dev board used).

The antenna pin control does not work when the target is switched to the ESP32-S3, at least when tested on a ESP32-S3-DevKitC-1U v1.0 development kit (based on the ESP32-S3-WROOM-1U-N8R2 module). The specified GPIOs simply remain in their default state, which is typically low. Various GPIO output pins were tried without any sign of WiFi control.  This has previously been noted in as an ESP32-S3 issue, see: https://github.com/espressif/esp-idf/issues/10385 (IDFGH-8972), which has not yet received any feedback.

A related question -When successfully running this example on the ESP-WROVER-KIT V4.1, it appears that the antenna GPIOs will default to output low when the device is not in either RX or TX mode - is this correct? For an example, see the antenna control outputs while monitoring antenna two; in this case TX and RX both use ANT1, which is 'ant_two'=0x0011, which sets both GPIO control lines high.  Note that the GPIOs do go high while in TX or RX, but otherwise spend much of the time low.

**Comment by mhdong** [comment]
Hi @sbuto1  fix on master branch is available at https://github.com/espressif/esp-idf/commit/16ec59907e9abf95981e87ca3c9154be2325e245, we are also back porting to other release branches.
Will update further if any progress. Thanks.
