### ISSUE TITLE
Flashing issues on docker using Mac M2 chip  (IDFGH-10856)

### ISSUE THREAD

**Issue by luarss** [espressif/esp-idf#12060]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

**System Specs**
Apple Mac M2, ESP32-C3, IDF V5.0 (Docker)

**Summary**
I am trying to follow the instructions to flash esp-idf onto the board using this [guide](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/tools/idf-docker-image.html). There seems to be a disconnecting issue for `esp_rfc2217_server.py`.

**To replicate**
First build using 
- Directory; `esp-idf/examples/get-started/hello-world`
- `docker run --rm -v $PWD:/project -w /project espressif/idf:release-v5.0 idf.py build`  

Host
- `esp_rfc2217_server.py -v -p 4000 /dev/cu.usbserial-120`

Docker image
- `docker run --rm -v $PWD:/project -w /project espressif/idf:release-v5.0 idf.py --port rfc2217://host.docker.internal:4000?ign_set_control flash`  But this code doesn't work as it returns an error as follows:
`zsh: no matches found: rfc2217://host.docker.internal:4000?ign_set_control`

- `docker run --rm -v $PWD:/project -w /project espressif/idf:release-v5.0 idf.py --port rfc2217://host.docker.internal:4000 flash` this works, but it crashes the `esp_rfc2217_server` with the output:

esp_rfc2217_server
![image](https://github.com/espressif/esp-idf/assets/39641663/e4e1d0da-e6d1-4ad3-9c9a-0a1f34277cdc)

docker
![image](https://github.com/espressif/esp-idf/assets/39641663/7acbeedb-6cd8-4d32-99b7-6f3423e89375)

**Similar Issue**
https://github.com/espressif/esp-idf/issues/10617 - but doesn't cover Mac M2

Any tips will be greatly appreciated.

**Comment by radimkarnis** [comment]
Hello @luarss,

the `zsh: no matches found: rfc2217://host.docker.internal:4000?ign_set_control` error is a result of the zsh shell interpreting the `?` in the port name as a globbing wildcard.

You can wrap it in quotes as `'rfc2217://host.docker.internal:4000?ign_set_control'`, running the command `docker run --rm -v $PWD:/project -w /project espressif/idf:release-v5.0 idf.py --port 'rfc2217://host.docker.internal:4000?ign_set_control' flash` - that should help!
