### ISSUE TITLE
pcnt quadrature question (IDFGH-10870)

### ISSUE THREAD

**Issue by onurdof** [espressif/esp-idf#12072]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Hello I have an encoder which has A B Z and /A /B /Z outputs. I want to detect the direction and tick count using pcnt but I did not find any solution. I alredy looked the pcnt example, in pcnt example, it detect pulses very good but I also need direction like left or right. Thanks for your helps

**Comment by suda-morris** [comment]
@onurdof you can define the direction by either

* the sign of the count value
* the change of the value (getting bigger or smaller)

The PCNT peripheral doesn't have a hardware feature to tell the direction, you have to calculate it by software.

**Comment by suda-morris** [comment]
BTW, for such application questions, the [ESP32 forum](https://esp32.com/viewforum.php?f=13) is absolutely a better place for you to refer to.

**Comment by monurbstnc** [comment]
> BTW, for such application questions, the [ESP32 forum](https://esp32.com/viewforum.php?f=13) is absolutely a better place for you to refer to.

Thank you so much.
