### ISSUE TITLE
EspTouch with RSA encryption (IDFGH-10878)

### ISSUE THREAD

**Issue by offgrid88** [espressif/esp-idf#12080]
### Is your feature request related to a problem?

To securely broadcast wifi credentials I use smartconfigv2 but hard-coding the encryption key is not that secure and can be compromised at all time

### Describe the solution you'd like.

Is there a possibility this would be added as smartconfigv3 for example. I can make the implementation but I fear I messed it up as I am not experienced with mbedtls. If there is no chance that this feature will be available, It'll be helpful to have some guidelines on how to implement it the right way.

### Describe alternatives you've considered.

I considered BluFi but I am trying to make multiple devices connect to the same wifi

**Comment by Xiehanxin** [comment]
hi @offgrid88 , I would like to clarify your use case. Are you looking to have multiple devices connect to the internet simultaneously？

**Comment by offgrid88** [comment]
Yes I am trying to connected a big number of devices to the network simultaneously and I want to encrypt the SSID and PASSWORD of the AP using Asymmetric Encryption .
