### ISSUE TITLE
Compiler warning when compiling project with FatFS (IDFGH-10887)

### ISSUE THREAD

**Issue by thanhminhmr** [espressif/esp-idf#12089]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v5.2-dev-2164-g3befd5fff7

### Operating System used.

Linux

### How did you build your project?

Command line with idf.py

### If you are using Windows, please specify command line type.

None

### What is the expected behavior?

I expected it to build without any compiler warning.

### What is the actual behavior?

When config `CONFIG_FATFS_VOLUME_COUNT` to 1, the build always have this compiler warning.
```
[.../...] Building C object esp-idf/fatfs/CMakeFiles/__idf_fatfs.dir/diskio/diskio.c.obj
~/esp/esp-idf/components/fatfs/diskio/diskio.c:24:5: warning: excess elements in array initializer
   24 |     {1, 0},    /* Logical drive 1 ==> Physical drive 1, auto detection */
      |     ^
~/esp/esp-idf/components/fatfs/diskio/diskio.c:24:5: note: (near initialization for 'VolToPart')
```

### Steps to reproduce.

1. Create/get any project that use FatFS.
2. Set `CONFIG_FATFS_VOLUME_COUNT` to 1. (Note: valid range reported in `idf.py menuconfig` is 1-10)
3. Build with `idf.py build`. The warning should be visible.

### More Information.

https://github.com/espressif/esp-idf/blob/3befd5fff72aa6980514454a50233037718b611f/components/fatfs/diskio/diskio.c#L24

The warning is from this line, caused by `FF_VOLUMES` equals 1 is not considered by the code. Either limit the range from menuconfig or edit the code to support `FF_VOLUMES` equals 1 will fix this issue.
Note that `FF_VOLUMES` is defined to be equals to `CONFIG_FATFS_VOLUME_COUNT`.

**Comment by adokitkat** [comment]
Hello @thanhminhmr. Thank you for reporting this issue.
