### ISSUE TITLE
[TW#16354] ledc_set_fade_with_step scale attribute is not checked by division by zero

### ISSUE THREAD

**Issue by zilizii** [espressif/esp-idf#1211]
Hello

In the 
esp_err_t ledc_set_fade_with_step(ledc_mode_t speed_mode, ledc_channel_t channel, int target_duty, int scale, int cycle_num) fnc the scale valus is not checked before the division. Please update, because of the esp32 in this case will be crashed,

step_num = (duty_cur - target_duty) / scale;  --> Division by zero was not checked before the division.

Thank you.

**Comment by FayeY** [comment]
Hi, this issue should have been solved in the latest IDF. Please have a try, and feel free to reopen it if your problem is still unsolved. Thanks.
