### ISSUE TITLE
USB MSC Device Example (IDFGH-10935)

### ISSUE THREAD

**Issue by Sotung96** [espressif/esp-idf#12129]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Hi all,

I have a project that I need to check the msc eject action. 
I'm trying to test the msc device example. I uesd the default code to test it but when I eject the msc in PC. There are nothing change. I still can't accesses the ESP MSC by application example. The states is "Storage exposed over USB". Do anyone know how to fix it?
Thanks.

**Comment by tore-espressif** [comment]
Hello @Sotung96 ,
I assume that by 'eject' you mean 'disconnect'.

If you want to catch 'usb disconnect' events in your self-powered device, you must implement VBUS monitoring in your hardware. Please refer to this section of our docs : https://docs.espressif.com/projects/esp-idf/en/latest/esp32s2/api-reference/peripherals/usb_device.html#self-powered-device

You can also experiment with  software 'eject' in windows: 
![image](https://github.com/espressif/esp-idf/assets/77206109/43be1b8f-fec5-45ce-99b3-8061f12f02be)

Clicking on 'Eject' in Windows should trigger the disconnect action in  you application
