### ISSUE TITLE
idf.py 是怎么做到按tab按键能够子命令补全的 (IDFGH-10928)

### ISSUE THREAD

**Issue by m986883511** [espressif/esp-idf#12122]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

拜读了一下idf.py，但是没找到哪里实现了子命令补全，我想学习一下这个技术，希望不吝赐教

**Comment by fhrbata** [comment]
Hello @m986883511 , 

my understanding is that the shell completion code is generated by `click` https://click.palletsprojects.com/en/8.1.x/shell-completion/ , which is used by `idf.py` , and included in e.g. `export.sh`  with `__enable_autocomplete()`. The completion is handled by shell. HTH

**Comment by m986883511** [comment]
> 

very thank you
