### ISSUE TITLE
[TW#16357] ESP32 BLE characteristics

### ISSUE THREAD

**Issue by Goutham8128** [espressif/esp-idf#1213]
Hi

I executed the ESP 32 BLE gateway code using arduino IDE.I didnt get any errors.In my case i am using a BLE sensor dongle and i want the ESP 32 module to retrieve the services and characteristics of the BLE sensor dongle which i am using.The BLE sensor dongle has a temperature,pressure and Accelerometer sensor.Each sensor has specific UUID's. When i open the serial monitor after executing the code the serial monitor is not displaying the sensor data.I am not getting sensor data.

**Comment by nkolban** [comment]
I don't think there is enough information in the report to provide good assistance.  Perhaps if you pasted your Arduino script to a pastebin and posted a link to it?

**Comment by Goutham8128** [comment]
Hi

Sorry for not giving the information correctly.I am using a sensor dongle which has sensor information in it. It is acting as a BLE server. I am using ESP32 acting as a BLE client module.I upload the BLE client code into the esp32 but after its execution it is just displaying the BLE server name and its service UUID. It is not able to read the characteristics of the BLE server. I want to read the characteristics of the BLE server in the serial monitor. Can u help me out with this?

**Comment by Yulong-espressif** [comment]
@Goutham8128 You can try our BLE server demo to connect to the BLE client demo first. Thanks.

**Comment by Goutham8128** [comment]
Thanks for the response. Where can I find the one which you are referring?

**Comment by FayeY** [comment]
Could those [examples](https://github.com/espressif/esp-idf/tree/master/examples/bluetooth) in IDF help?

**Comment by Goutham8128** [comment]
No

The code is running but the sensor which i am using as a BLE server is not being received by the BLE client i.e Esp32. I couldn't find any source for this.

**Comment by chegewara** [comment]
What is this sensor? Maybe it would be better to ask on forum or forum related to this sensor?

**Comment by Goutham8128** [comment]
The one which we discussed previously which Mr. Kolban has bought.

**Comment by FayeY** [comment]
Sorry that maybe I misunderstood it. It seems to be a problem of the sensor. 
How about using a mobile phone as a BLE client? 
Could a mobile phone read the characteristics of your sensor?

**Comment by Goutham8128** [comment]
U mean that the Server code running on DA14583 which is advertising the data should be modified?.
If the services of the module are read by nrfconnect then why the client program running on esp32 is not able to read the services?

**Comment by Weijian-Espressif** [comment]
@Goutham8128 Can you use lightblue APP or nrf connect APP to test the sensor,  do the APP work well?

**Comment by FayeY** [comment]
Closing due to lack of response, please feel free to reopen if this is still an issue you can supply more details. Thanks.
