### ISSUE TITLE
BLE_HID_DEVICE example error  (IDFGH-10957)

### ISSUE THREAD

**Issue by monurbstnc** [espressif/esp-idf#12149]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Hello I am trying to build something using bluetooth/esp_hid_device example. But when I am try to build this I got undefined reference to `esp_bt_gap_set_cod' error. I define to enable hid_device
#define CONFIG_BT_HID_DEVICE_ENABLED 1 
Thanks for your helps
I am using ESP32s3 devkitc-1.

**Comment by zhp0406** [comment]
@monurbstnc 
thanks for report the issue,
I am using the master branch (commit a1c0d9c3a1d1bea876f57c9229065ecd7f048b33), and everything is working fine.
What version of ESP-IDF are you using?

**Comment by zhp0406** [comment]
@monurbstnc 
Can you provide me with the complete log, please?

**Comment by monurbstnc** [comment]
I solve the problem, thanks for the helps.
