### ISSUE TITLE
APP Version信息是如何生成的？ (IDFGH-10954)

### ISSUE THREAD

**Issue by RealNee** [espressif/esp-idf#12146]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

启动时，在Log信息中有这么一项内容
```
I (1181) cpu_start: Application information:
I (1181) cpu_start: Project name:     factory_demo
I (1181) cpu_start: App version:      v0.5.0-4-g9444158
I (1181) cpu_start: Compile time:     Aug 28 2023 07:05:05
I (1182) cpu_start: ELF file SHA256:  88aecc34...
```
其中`App version: v0.5.0-4-g9444158`是根据什么生成的，又该如何修改这项内容呢？

**Comment by suda-morris** [comment]
https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/misc_system_api.html#app-version

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, feel free to reopen.
