### ISSUE TITLE
nvs_find_key(nvs_handle_t handle, const char *key) (IDFGH-10963)

### ISSUE THREAD

**Issue by ddomnik** [espressif/esp-idf#12155]
### Is your feature request related to a problem?

I just read the doc for NVS and did not find a function like nvs_find_key(nvs_handle_t handle, const char *key).

### Describe the solution you'd like.

Simple function called something like 
`esp_err_t nvs_find_key(nvs_handle_t handle, const char *key)`
which return ESP_OK if found or ESP_ERR_NVS_NOT_FOUND if not.

### Describe alternatives you've considered.

If I want to check if a particular key exists, I would have to implement my own method using either an iterator with nvs_entry_find() or write my own algorithm utilizing ESP_ERR_NVS_NOT_FOUND with all nvs_get_<type> functions (which is the fastest way).

The iterator approach seems to be very costly, as I have to compare each key as strings.

**Comment by pacucha42** [comment]
Hi @ddomnik, thank you for the report. We will consider providing some type of comfortable API that would give you the information required. We will keep you posted

**Comment by rrtandler** [comment]
Hi @ddomnik,
We are now creating the nvs_find_key inspired by your feature request. The function will optionally also return the data type of entry if the key was found. I'll let you know, when the implementation will be merged into the master branch.
