### ISSUE TITLE
GPIO feature: Add gpio_get_direction() and gpio_get_pull_mode() (IDFGH-10987)

### ISSUE THREAD

**Issue by IhorNehrutsa** [espressif/esp-idf#12176]
It is useful to have functions that return the current setting of a pin:

**1)** getter 
```
esp_err_t gpio_get_direction(gpio_num_t gpio_num, gpio_mode_t *mode);
```
like the setter:
```
esp_err_t gpio_set_direction(gpio_num_t gpio_num, gpio_mode_t mode);
```
https://github.com/espressif/esp-idf/blob/82cceabc6e6a0a2d8c40e2249bc59917cc5e577a/components/driver/gpio/include/driver/gpio.h#L169C11-L169C29

**2)** getter 
```
esp_err_t gpio_get_pull_mode(gpio_num_t gpio_num, gpio_pull_mode_t *pull);
```
like the setter:
```
esp_err_t gpio_set_pull_mode(gpio_num_t gpio_num, gpio_pull_mode_t pull);
```
https://github.com/espressif/esp-idf/blob/82cceabc6e6a0a2d8c40e2249bc59917cc5e577a/components/driver/gpio/include/driver/gpio.h#L184C11-L184C29

**Comment by IhorNehrutsa** [comment]
@songruo 
Hi.
Will you work on this issue?
Thanks.

**Comment by songruo** [comment]
@IhorNehrutsa  If I introduce a dump API that could dump out all information on the requested IO, including input_en = 0/1, output_en = 0/1, pullup_en = 0/1, pulldown_en = 0/1, func_sel, signal_connected, etc. together, instead of separate APIs for every characteristic. Will it work for you?

**Comment by IhorNehrutsa** [comment]
@songruo Yes, perfect.
Thanks.

I need this feature in v5.0.2 ESP-IDF and later.
Thanks.

**Comment by KaeLL** [comment]
@songruo Maybe make `gpio_config` call this function in order to show gpio cfg? That would be less redundant.

**Comment by IhorNehrutsa** [comment]
@songruo Is any progress ?

**Comment by songruo** [comment]
@IhorNehrutsa It has been merged to master, please wait for its sync to Github. However, we are not considering backporting the new feature to previous IDF versions. You could help yourself to pick the commit!
