### ISSUE TITLE
ECDSA signing issue (IDFGH-10981)

### ISSUE THREAD

**Issue by Jimis333** [espressif/esp-idf#12170]
Hi
I try to sign my build with a signing key file but it fails. For my board version [WROOM ](https://www.sparkfun.com/products/17381) there is only the EDCSA option in the menuconfig so I need to create a file with the following command
openssl ecparam -name secp256k1 -genkey -noout -out secure_boot_signing_key_jim.pem

This returns an error during build
FAILED: signature_verification_key.bin....
A fatal error occurred: Supports NIST192p and NIST256p keys only

If I use the other command with RSA key it fails also 
openssl ecparam -name prime256v1 -genkey -noout -out secure_boot_signing_key_jim.pem
![Screenshot_3](https://github.com/espressif/esp-idf/assets/73533611/e7e40bae-f2ae-46ed-be5b-0455e6a91c1b)

Thanks in advance

**Comment by AdityaHPatwardhan** [comment]
@Jimis333 Can you also share the output of `esptool.py chip_id` command.
I would like to know the ECO version for your chip.
If it is ECO3 then you may use Secure Boot Version 2 instead of Secure Boot version 1.
You would be able to execute the above command from an IDF environment since esptool script should be available there.

**Comment by Jimis333** [comment]
After a lot of searching I did the following steps to make it work

Step 1: check chip version
![a](https://github.com/espressif/esp-idf/assets/73533611/0074fa7a-1e47-4bce-852d-1f1defd2e715)

Step 2: set the minimum chip revision in menuconfig (this limits your options in security features on next step)
![b](https://github.com/espressif/esp-idf/assets/73533611/4d472526-078b-4493-97c2-23c5ff266967)

Step 3: set the security features (RSA)
![c](https://github.com/espressif/esp-idf/assets/73533611/546920c3-a606-42c7-b630-9c48df380947)

Step 4: generate the key (RSA)
openssl ecparam -name prime256v1 -genkey -noout -out secure_boot_signing_key_jim.pem

Thank you for your replies

**Comment by AdityaHPatwardhan** [comment]
@Jimis333 
Its good that the issue got resolved.
I was wondering about the chip revision that you are using. Looking at the [link](https://www.sparkfun.com/products/17381) I was under the impression that you have the old modules with `ECO < 3`.
I see that you have used RSA signing for secure boot V2, yes that is the expected way.
For secure Boot V2 ECDSA signing is not an option for esp32.

Also when you mention this 

> Step 4: generate the key (RSA)
openssl ecparam -name prime256v1 -genkey -noout -out secure_boot_signing_key_jim.pem

Just wanted to note that the command generates an ECDSA key and not an RSA key.
Thanks for closing the issue

**Comment by Jimis333** [comment]
@AdityaHPatwardhan 

You just saved me a lot of trouble with your mention ! I'm not very familiar with certifications and the command I used was indeed for ECDSA. This was the answer to my other opened issue ! https://github.com/espressif/esp-idf/issues/12148
A proper command would be e.g
openssl genrsa -out private-key.pem 3072

Thanks a lot !

**Comment by AdityaHPatwardhan** [comment]
You can also use the standard commands provided by `espsecure.py`

``` 
espsecure.py generate_signing_key --version 2 --scheme rsa3072 secure_boot_signing_key.pem
```
It takes care of all the versions and respective algorithm requirements so we dont even have to worry about using a wrong algorithm which is not supported.

**Comment by Jimis333** [comment]
I don't generally use py commands I try to let VS code do those automatically. For that particular command I get error

espsecure.py generate_signing_key --version 2 --scheme rsa3072 secure_boot_signing_key.pe 
  File "<stdin>", line 1
    espsecure.py generate_signing_key --version 2 --scheme rsa3072 secure_boot_signing_key.pe
                 ^^^^^^^^^^^^^^^^^^^^
SyntaxError: invalid syntax

**Comment by AdityaHPatwardhan** [comment]
The command works correctly on my side.
Do you have espsecure.py script available in your environment?

Can you try `espsecure.py --help`?

**Comment by Jimis333** [comment]
espsecure.py --help
espsecure.py : The term 'espsecure.py' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify 
that the path is correct and try again.
At line:1 char:1
+ espsecure.py --help
+ ~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (espsecure.py:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by Jimis333** [comment]
Yes you are right, but I think I have it uninstalled at some point. 
If I install the extension in VSCode I don't know what is the reason of installing it in windows also. It's a bit confusing. I guess it should work on VScode terminal environment but maybe not everything is supported there.

**Comment by Jimis333** [comment]
It still didn't work. I removed the .py from the command and it worked
espsecure generate_signing_key --version 2 --scheme rsa3072 secure_boot_signing_key.pem
instead of 
espsecure.py generate_signing_key --version 2 --scheme rsa3072 secure_boot_signing_key.pem
