### ISSUE TITLE
Removal of e-Tugra root certificate (IDFGH-10992)

### ISSUE THREAD

**Issue by nagaripratap** [espressif/esp-idf#12181]
**Description**
Certifi 2023.07.22 removes root certificates from "e-Tugra" from the root store. These are in the process of being removed from Mozilla's trust store.

e-Tugra's root certificates are being removed pursuant to an investigation prompted by reporting of security issues in their systems. Conclusions of Mozilla's investigation can be found here.

**Information**

Manifest Path : [components/mbedtls/esp_crt_bundle/cacrt_all.pem](https://github.com/espressif/esp-idf/blob/82cceabc6e6a0a2d8c40e2249bc59917cc5e577a/components/mbedtls/esp_crt_bundle/cacrt_all.pem#L1267)

**Comment by mahavirj** [comment]
Fixed with 7441cdb82bf5fafcf24ea1743ed7fd7fc76ffe43
