### ISSUE TITLE
[TW#16355] COAP experiment between two esp32 as server/client 

### ISSUE THREAD

**Issue by singhp6** [espressif/esp-idf#1218]
I am trying the coap experiment between two esp32 as server/client and I am able to connect both esp32(server and client) to wifi access point. However, I am not sure what 'URI' exactly (or in which syntax) should I use to get the coap communication going between the two esp32. What exactly should the "Target uri" be for two boards to start communicating over wifi (for coap experiment)? I am using the syntax at client as 'coap://ip address(of server)' in "make menuconfig --> example configuration"...For example coap://10.13.215.134/ (see 1.PNG) but getting an error 'DNS lookup failed' (see 2.PNG). I am not so sure if thats the right way of doing it. Am I doing anything wrong here? I tried different URI's to see if it works or not, like the "coap://californium.eclipse.org/" or "coap://coap.me/", but could get anything with this. I got the same error.

![1](https://user-images.githubusercontent.com/27331214/32353492-11a565e8-bffc-11e7-929c-a5dd95647874.PNG)
![2](https://user-images.githubusercontent.com/27331214/32353493-11b54b20-bffc-11e7-91fa-614c309cfe8a.PNG)

**Comment by 0xff007** [comment]
the coap experiment between esp32 client and libcoap-server.
![2017-11-04 13-05-15](https://user-images.githubusercontent.com/26567451/32402527-0225b332-c161-11e7-87ff-4545b3c17d7c.png)
![2017-11-04 13-01-31](https://user-images.githubusercontent.com/26567451/32402494-577291e4-c160-11e7-8910-c225f2d253b8.png)
and I try to capture with WireShark.
![2017-11-04 13-04-14](https://user-images.githubusercontent.com/26567451/32402509-b7a56e56-c160-11e7-8a0a-8ec10756deb3.png)

reset esp32 Restart multiple times,
![2017-11-04 13-08-06](https://user-images.githubusercontent.com/26567451/32402644-94767ea4-c163-11e7-87d4-eba6ec339263.png)
![2017-11-04 13-23-10](https://user-images.githubusercontent.com/26567451/32402645-9604d7ac-c163-11e7-9931-9aeca92a55e0.png)

I guess it's response processing error. 
I don't know how to solve it.):

**Comment by singhp6** [comment]
Did you make one esp32 as a server? What is the libcoap server that you have? Also, how did you run both server and client? I used "make flash monitor". I want to know what is the "URI" and in what format we should be using it.

**Comment by singhp6** [comment]
Questions:

1) Did you make one esp32 as a server? What is the libcoap server that you have?
2) How did you run both server and client? I used "make flash monitor". It seems you ran libcoap server a bit differently.
3) I want to know what is the "URI" and in what format we should be using it.

**Comment by 0xff007** [comment]
@singhp6 
1. I made my pc as a server by running the example server of libcoap 。
2. I made one esp32 as  a client, url is coap://10,.1.1.129 , 
as you see，libcoapserver register resouce “NULL" , then, send response to client with payload INDEX 
![_20171105154429](https://user-images.githubusercontent.com/26567451/32412971-7cfcc614-c241-11e7-948e-411925072857.png)
![_20171105154513](https://user-images.githubusercontent.com/26567451/32412972-7fc9ef8e-c241-11e7-9fb5-a0ac1bedb129.png)

Making sure that runing a coap server correct ，then ， making one esp32 as a client。
 3. I test URI in format ”coap://serverdomainorip/path" 

in a word , i think it is response processing error.
now ,i'm reviewing the code of [libcoap](https://github.com/obgm/libcoap) and the example of [coap-client](https://github.com/espressif/esp-idf/blob/master/examples/protocols/coap_client/main/coap_client_example_main.c).

next ,i'll try to make one esp32 as server , use my pc send request .

I hope I can find a solution.

**Comment by zhang-jun-hao** [comment]
Hi @singhp6  @0xff007 

The sever url is coap://x.x.x.x/Espressif

Please change the line code:
    result = select( FD_SETSIZE, &readfds, 0, 0, &tv ); 
to:  
    result = select( ctx->sockfd+1, &readfds, 0, 0, &tv );
in file coap_client_example_main.c and coap_server_example_main.c.

Or use the attached demo file:
[coap_client.tar.gz](https://github.com/espressif/esp-idf/files/1473616/coap_client.tar.gz)
[coap_server.tar.gz](https://github.com/espressif/esp-idf/files/1473617/coap_server.tar.gz)

Thanks!

**Comment by singhp6** [comment]
@0xff007 Hi,

Did you get the solution for the problem which you were looking for (above)? If yes, could you please explain what did you do? are you now not getting the response processing error? Was there a problem with the URI that you were taking?
