### ISSUE TITLE
ESP32-S2 SPI QPI Mode (IDFGH-10999)

### ISSUE THREAD

**Issue by Sotung96** [espressif/esp-idf#12187]
### Answers checklist.

- [x] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Hi Everyone,

I'm going to do project which is using the spi qpi mode but I can't find any example on it. Do anyone know how to read register on esp32-s2? Because I find there are a register in SPI_USER_REG is showing is esp32-s2 go into qpi mode but I can't find any register like that in idf. Thanks

**Comment by wanckl** [comment]
Hi @Sotung96 Refer to the [technical reference manual](https://www.espressif.com/sites/default/files/documentation/esp32-s2_technical_reference_manual_en.pdf), the QPI mode may need some additional command configuration, This mode is temporary not supported and tested in IDF, but we are fortunatly also disscuse about it recently !      
If you are interested, you can have two way to access this registers by your self:     
```c
# way 1: using macro REG_SET/GET/CLEAR_BIT
REG_SET_BIT(SPI_USER_REG, SPI_QPI_MODE_M);

#way 2: using struct
spi_dev_t *dev = SPI_LL_GET_HW(your_host_id);
dev->user.qpi_mode = 1;   //enable, or 0:disable
```
you can fix include header file to pass the build and ,,,have fun~

**Comment by Sotung96** [comment]
Hi @wanckl, Thanks for your help. is user.qpi_mode in spi_struct.h file? because I can't find qpi_mode. 

```c
struct {
            uint32_t doutdin:           1;                  /*Set the bit to enable full duplex communication. 1: enable 0: disable.*/
            uint32_t reserved1:         3;                  /*reserved*/
            uint32_t cs_hold:           1;                  /*spi cs keep low when spi is in ,done, phase. 1: enable 0: disable.*/
            uint32_t cs_setup:          1;                  /*spi cs is enable when spi is in ,prepare, phase. 1: enable 0: disable.*/
            uint32_t ck_i_edge:         1;                  /*In the slave mode  the bit is same as spi_ck_out_edge in master mode. It is combined with  spi_miso_delay_mode bits.*/
            uint32_t ck_out_edge:       1;                  /*the bit combined with spi_mosi_delay_mode bits to set mosi signal delay mode.*/
            uint32_t reserved8:         2;                  /*reserved*/
            uint32_t rd_byte_order:     1;                  /*In read-data (MISO) phase 1: big-endian 0: little_endian*/
            uint32_t wr_byte_order:     1;                  /*In command address write-data (MOSI) phases 1: big-endian 0: litte_endian*/
            uint32_t fwrite_dual:       1;                  /*In the write operations read-data phase apply 2 signals*/
            uint32_t fwrite_quad:       1;                  /*In the write operations read-data phase apply 4 signals*/
            uint32_t fwrite_dio:        1;                  /*In the write operations address phase and read-data phase apply 2 signals.*/
            uint32_t fwrite_qio:        1;                  /*In the write operations address phase and read-data phase apply 4 signals.*/
            uint32_t sio:               1;                  /*Set the bit to enable 3-line half duplex communication  mosi and miso signals share the same pin. 1: enable 0: disable.*/
            uint32_t usr_hold_pol:      1;                  /*It is combined with hold bits to set the polarity of spi hold line  1: spi will be held when spi hold line is high  0: spi will be held when spi hold line is low*/
            uint32_t usr_dout_hold:     1;                  /*spi is hold at data out state  the bit combined with spi_usr_hold_pol bit.*/
            uint32_t usr_din_hold:      1;                  /*spi is hold at data in state  the bit combined with spi_usr_hold_pol bit.*/
            uint32_t usr_dummy_hold:    1;                  /*spi is hold at dummy state  the bit combined with spi_usr_hold_pol bit.*/
            uint32_t usr_addr_hold:     1;                  /*spi is hold at address state  the bit combined with spi_usr_hold_pol bit.*/
            uint32_t usr_cmd_hold:      1;                  /*spi is hold at command state  the bit combined with spi_usr_hold_pol bit.*/
            uint32_t usr_prep_hold:     1;                  /*spi is hold at prepare state  the bit combined with spi_usr_hold_pol bit.*/
            uint32_t usr_miso_highpart: 1;                  /*read-data phase only access to high-part of the buffer spi_w8~spi_w15. 1: enable 0: disable.*/
            uint32_t usr_mosi_highpart: 1;                  /*write-data phase only access to high-part of the buffer spi_w8~spi_w15. 1: enable 0: disable.*/
            uint32_t usr_dummy_idle:    1;                  /*spi clock is disable in dummy phase when the bit is enable.*/
            uint32_t usr_mosi:          1;                  /*This bit enable the write-data phase of an operation.*/
            uint32_t usr_miso:          1;                  /*This bit enable the read-data phase of an operation.*/
            uint32_t usr_dummy:         1;                  /*This bit enable the dummy phase of an operation.*/
            uint32_t usr_addr:          1;                  /*This bit enable the address phase of an operation.*/
            uint32_t usr_command:       1;                  /*This bit enable the command phase of an operation.*/
        };
        uint32_t val;
    } user;
```

**Comment by wanckl** [comment]
@Sotung96 you may find `spi_struct.h` for your target (esp32s2)

**Comment by Sotung96** [comment]
I found it. Thanks a lot.

**Comment by Sotung96** [comment]
@wanckl I have one more question. A define to use SPI2_HOST in my code and I try to use struct to enable qpi mode. However, it show me error about 
```c
error: invalid initializer
   42 | #define SPI_LL_GET_HW(ID) ((ID)==0? ({abort();NULL;}):((ID)==1? &GPSPI2 : &GPSPI3))
``` 
how to fix it?

**Comment by Sotung96** [comment]
@wanckl, Is it only need to do the config for the slave? How do I let Master know is using QPI Mode?

**Comment by Sotung96** [comment]
@wanckl I can use QPI mode now. Thanks for your help. But I got other problem now. I cannot use essl_spi_rdbuf to read slave data. 
```c
static esp_err_t wait_for_slave_ready(spi_device_handle_t spi)
{
    esp_err_t ret;
    uint32_t slave_ready_flag = 0;

    while (1) {
        //Master sends CMD2 to get slave configuration
        //The first byte is a flag assigned by slave as a start signal, here it's 0xee
        ret = essl_spi_rdbuf(spi, (uint8_t *)&slave_ready_flag, SLAVE_READY_FLAG_REG, sizeof(slave_ready_flag), SPI_TRANS_MODE_QIO | SPI_TRANS_MODE_DIOQIO_ADDR);
        printf("address = %d, data = 0x%.2lX\n", SLAVE_READY_FLAG_REG, slave_ready_flag);
        if (ret != ESP_OK) {
            return ret;
        }

        if (slave_ready_flag != SLAVE_READY_FLAG) {
            printf("wait slave ready...\n");
            vTaskDelay(1000 / portTICK_PERIOD_MS);
        } else if (slave_ready_flag == SLAVE_READY_FLAG) {
            return ESP_OK;
        }
    }
}
``` 
In this function, I should get the data from SLAVE_READY_FLAG_REG but it read the wrong data. However, if i change it to 1-bit mode. It can get the right data. I don't know what's going wrong.

**Comment by wanckl** [comment]
@Sotung96 Nice to here this, but are you enter QPI mode by simply set the `qpi_mode` bit ? is some other cmd or configure needed ?    

Besides, Refer to the [technical reference manual](https://www.espressif.com/sites/default/files/documentation/esp32-s2_technical_reference_manual_en.pdf), In QPI mode, all state of phases are in 4-bit mode, so I guess you may need change something in your ESSL component: calling `essl_spi_rdbuf` with flag `SPI_TRANS_MODE_QIO | SPI_TRANS_MULTILINE_CMD | SPI_TRANS_MULTILINE_ADDR`

**Comment by Sotung96** [comment]
@wanckl, I ues
```c
spi_dev_t *dev = SPI_LL_GET_HW(your_host_id);
dev->user.qpi_mode = 1; 
``` 
on master and slave for the config. Then it goes into QPI Mode but only the cmd will use 4bits. I need to call the API with flag. Then address and data will use 4mits as well. 

I tried to call API with flag but it still the same. I'm using **SEG_Master** example. I see a common before it call the API. It said 
" Master sends CMD2 to get slave configuration. The first byte is a flag assigned by slave as a start signal, here it's 0xee "

Refer to the [technical reference manual](https://www.espressif.com/sites/default/files/documentation/esp32-s2_technical_reference_manual_en.pdf), It will have a Mask in cmd. Will it doesn't read the buffer because of the wrong Mask?
After I use QPI Mode, the mask is 0xA2. I tried to return to 1bit mode. It read the buffer and read the right data.

**Comment by Sotung96** [comment]
@wanckl sorry, I got 1 more problem. I want to know how the esp32-s2 (slave) check the cmd from esp32-s3(master)?

**Comment by wanckl** [comment]
@Sotung96 Sorry, what your question?   

which mode the master and slave is, and which mode want to be?    
In my opinion QPI mode is for slave, and due to your test above, the slave has 2 ways to enter QPI mode, set `qpi_mode` register, or triggered by `EN_QPI` cmd (described in TRM) sending from master.     

If the 2nd way: by `EN_QPI` cmd, master should send this cmd in **1-bit** mode, then slave enter QPI mode, then the follow cmd or addr or data, all should send in **4-bit** mode, include the `EXIT_QPI` cmd.      

The slave should interacted only by **cmd** it received, no matter who the master is.

**Comment by Sotung96** [comment]
@wanckl I'm using QPI mode. My question is how the slave read the cmd from master. For example, Master call ```essl_spi_rdbuf``` API to read the buffer that share from slave. So, how the slave know the cmd is 0xA2? Because I checked even the slave doesn't call ```spi_slave_hd_write_buffer``` API, Slave still go to ```cb_buffer_tx``` when Master send 0xA2. But if I change the cmd which is not using 0xA2 but still using ```spi_slave_hd_write_buffer``` API. Slave won't go to the ```cb_buffer_tx```.

Also, is it possiable to change the standard cmd to my own cmd?

**Comment by Sotung96** [comment]
@wanckl Also, how can I change the dummy phase to 32 bits (8 cycle). Right now I'm setting 32bit dummy phase on Master and Slave. However, the Slave was not in the right time to read to data.

**Comment by Sotung96** [comment]
@wanckl Can you help me to fix this problem? I want to use Slave to send out data by dma but I don't know why master can't receive a right data. here is the code:

```c
static bool get_tx_data(uint8_t *data, uint32_t max_len, uint32_t *out_len)
{
    //uint32_t SendBuff[3];
    //SendBuff[0] = 0xBB; //elements[0].Address; 
    //SendBuff[1] = elements[0].ElementType;
    //SendBuff[2] = elements[0].InterfaceType;
    //SendBuff[3] = elements[0].SerialNumber;

    *data = 0xBB; //SendBuff[0];
    printf("data = %" PRIX8 "\n", *data);
    return true;
}

data_ready = get_tx_data(SendBuff[descriptor_id], send_buf_size, 4);
    printf("SendBuff[descriptor_id] = %X\n", *SendBuff[descriptor_id]);
    
    while(data_ready)
    {
        slave_trans[descriptor_id].data = SendBuff[descriptor_id];
        slave_trans[descriptor_id].len = 4;
        printf("slave_trans = %X\n", *slave_trans[descriptor_id].data);
        ESP_ERROR_CHECK(spi_slave_hd_queue_trans(SLAVE_HOST, SPI_SLAVE_CHAN_TX, &slave_trans[descriptor_id].data, portMAX_DELAY));
        descriptor_id = (descriptor_id + 1) % QUEUE_SIZE;

        vTaskDelay(1);

        err = spi_slave_hd_get_trans_res(SLAVE_HOST, SPI_SLAVE_CHAN_TX, &ret_trans, 0);
        if (err != ESP_OK) 
        {
            assert(err == ESP_ERR_TIMEOUT);
                //Recycle all the used descriptors until there is no in-the-flight descriptor
            break;
        }
    }
    
``` 
the log is print out 0xBB but it show 0xFF in master that way.

**Comment by wanckl** [comment]
@Sotung96    

> how the slave read the cmd from master
When slave in HD(half duplex) mode, slave recognize the cmd by hardware automatically, this is the hardware designed protocol for slave, can refer to [GUIDE](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/protocols/esp_spi_slave_protocol.html), most of SPI slave have this mechanism.

> about how shared buffer works
`share buffer` is a block of registers in slave's chip, so every time slave call `spi_slave_hd_write/read_buffer` will change buffer directly. how ever every time master start a `essl_spi_rdbuf`, will send the specific `cmd` through SPI bus, read/write the share buffer, and notify a specific event, so your `cb_buffer_tx` got excused.

cache `cmd` will trigger a specific event, then if you registered callback, driver will call into it when received correct cmd.

**Comment by Sotung96** [comment]
Thanks for you reply. I make a lot of change. Now, I still using QPI mode and 40MHz. Master send the data to the Slave, then Slave will send back the data which is from Master to Master . Then Master will compare two data. one is send from Slave, one is master sent out. But when I print out the data which is Master got, it print out a lot of 0xbb. Do you know why? I tried the slow down the clock speed to 30MHz. It was fine.

**Comment by wanckl** [comment]
@Sotung96 can you have a scope, not logic analyzer, to see what happen on 40MHz. If it is OK on low speed, it may hardware/analog issue, you may need enhance your connection, especially the GND, and your power supply.

**Comment by Sotung96** [comment]
@wanckl, I work now after I test the code on PCB. Thanks very much.
