### ISSUE TITLE
Bluetooth connection without using an app (IDFGH-11013)

### ISSUE THREAD

**Issue by Talha-Babar** [espressif/esp-idf#12197]
### Is your feature request related to a problem?

I want to connect my esp32 with cell phone without using an app. I don't want to exchange any data, i just only want to connect it. Is this possible?

### Describe the solution you'd like.

If yes, kindly elaborate how can i achieve this task?

**Comment by zhp0406** [comment]
@Talha-Babar 
Hi,ESP32 supports classic Bluetooth and low-energy Bluetooth. Do you want to use classic Bluetooth or low-energy Bluetooth?
If you are using BLE, you can refer to [esp-idf/examples/bluetooth/bluedroid/ble/gatt_security_server](https://github.com/espressif/esp-idf/tree/master/examples/bluetooth/bluedroid/ble/gatt_security_server). With an Android phone, you can directly discover the device and initiate a connection.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to inactivity, feel free to reopen with more updates.
