### ISSUE TITLE
[TW#16358] SPI SLAVE receives data instability

### ISSUE THREAD

**Issue by L-eeX** [espressif/esp-idf#1220]
The data received by the spi slave is very unstable.I used the spi slave development project, and I've been plagued by this problem for half a month.I want to know when I can fix it?

**Comment by yake827** [comment]
Hi @L-eeX , Can you describe your specific phenomenon for us to analysis

**Comment by L-eeX** [comment]
@yake827 Download the example
**# Slave machine prints information：**
Received: ゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥ?
Received: ゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥ?
Received: ゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥ?
Received: ゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥゥ?
**# Host printing information**
Received: 
Received: 
Received: 
Received:

**Comment by L-eeX** [comment]
@yake827 This is my own code
# Slave machine prints information：
Received: 11 11 11 11
ret: 0
Received: 11 0 0 0
ret: 0
Received: 11 0 0 0
ret: 0
Received: 11 11 11 11
ret: 0
Received: 11 11 11 11
# Host printing information
Received: 42 170 170 170
Received: 42 170 170 170
Received: 42 170 170 170
Received: 42 170 170 170
Received: 11 11 11 11
Received: 41 41 0 200
Received: 42 170 170 170
Received: 42 169 82 16

**Comment by yake827** [comment]
Hi @L-eeX , it seems happen signal loss, I suggest you solder the SPI pins of the master and slave to each other using shorter cables.

**Comment by L-eeX** [comment]
@yake827
I use the dupont line to connect two devices, which should not be a line problem

**Comment by yake827** [comment]
@L-eeX I also test it using the dupont lines firstly, I found when the line is too long , the signal will loss frequently.So shorter dupont line maybe completely eradicate the signal loss.

**Comment by L-eeX** [comment]
Hi @yake827 ,I have just used 10 cm (3.94 inch) dupont line, which should not influence the IIC.

**Comment by yake827** [comment]
@L-eeX Can you tell me your IDF commit? I will test it again.

**Comment by L-eeX** [comment]
# receiver
`/* SPI Slave example, receiver (uses SPI Slave driver to communicate with sender)

   This example code is in the Public Domain (or CC0 licensed, at your option.)

   Unless required by applicable law or agreed to in writing, this
   software is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
   CONDITIONS OF ANY KIND, either express or implied.
*/
#include <stdio.h>
#include <stdint.h>
#include <stddef.h>
#include <string.h>

#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "freertos/semphr.h"
#include "freertos/queue.h"

#include "lwip/sockets.h"
#include "lwip/dns.h"
#include "lwip/netdb.h"
#include "lwip/igmp.h"

#include "esp_wifi.h"
#include "esp_system.h"
#include "esp_event.h"
#include "esp_event_loop.h"
#include "nvs_flash.h"
#include "soc/rtc_cntl_reg.h"
#include "rom/cache.h"
#include "driver/spi_slave.h"
#include "esp_log.h"
#include "esp_spi_flash.h"




/*
SPI receiver (slave) example.

This example is supposed to work together with the SPI sender. It uses the standard SPI pins (MISO, MOSI, SCLK, CS) to 
transmit data over in a full-duplex fashion, that is, while the master puts data on the MOSI pin, the slave puts its own
data on the MISO pin.

This example uses one extra pin: GPIO_HANDSHAKE is used as a handshake pin. After a transmission has been set up and we're
ready to send/receive data, this code uses a callback to set the handshake pin high. The sender will detect this and start
sending a transaction. As soon as the transaction is done, the line gets set low again.
*/

/*
Pins in use. The SPI Master can use the GPIO mux, so feel free to change these if needed.
*/
//#define GPIO_HANDSHAKE 2
#define GPIO_MOSI 12
#define GPIO_MISO 13
#define GPIO_SCLK 15
#define GPIO_CS 14

/*
//Called after a transaction is queued and ready for pickup by master. We use this to set the handshake line high.
void my_post_setup_cb(spi_slave_transaction_t *trans) {
    WRITE_PERI_REG(GPIO_OUT_W1TS_REG, (1<<GPIO_HANDSHAKE));
}

//Called after transaction is sent/received. We use this to set the handshake line low.
void my_post_trans_cb(spi_slave_transaction_t *trans) {
    WRITE_PERI_REG(GPIO_OUT_W1TC_REG, (1<<GPIO_HANDSHAKE));
}
*/

//Main application
void app_main()
{
    esp_err_t ret;

    //Configuration for the SPI bus
    spi_bus_config_t buscfg={
        .mosi_io_num=GPIO_MOSI,
        .miso_io_num=GPIO_MISO,
        .sclk_io_num=GPIO_SCLK
    };

    //Configuration for the SPI slave interface
    spi_slave_interface_config_t slvcfg={
        .mode=0,
        .spics_io_num=GPIO_CS,
        .flags=0,
        .queue_size=3
        //.post_setup_cb=my_post_setup_cb,
        //.post_trans_cb=my_post_trans_cb
    };

 /*   //Configuration for the handshake line
    gpio_config_t io_conf={
        .intr_type=GPIO_INTR_DISABLE,
        .mode=GPIO_MODE_OUTPUT,
        .pin_bit_mask=(1<<GPIO_HANDSHAKE)
    };
*/

    //Configure handshake line as output
    //gpio_config(&io_conf);
    //Enable pull-ups on SPI lines so we don't detect rogue pulses when no master is connected.
    //gpio_set_pull_mode(GPIO_MISO, GPIO_PULLUP_ONLY);
    gpio_set_pull_mode(GPIO_MOSI, GPIO_PULLUP_ONLY);
    gpio_set_pull_mode(GPIO_SCLK, GPIO_PULLUP_ONLY);
    gpio_set_pull_mode(GPIO_CS, GPIO_PULLUP_ONLY);

    //Initialize SPI slave interface
    ret=spi_slave_initialize(HSPI_HOST, &buscfg, &slvcfg, 1);
    assert(ret==ESP_OK);

    uint8_t sendbuf[4]={0xAA,0xAA,0xAA,0xAA};
    uint8_t recvbuf[4]={0xbb,0xbb,0xbb,0xbb};
    //memset(recvbuf, 0xAF, 2);
    spi_slave_transaction_t t;
    memset(&t, 0, sizeof(t));

    while(1) {
        //Clear receive buffer, set send buffer to something sane
        //memset(recvbuf, 0xAF, 2);;
        //sprintf(sendbuf, "This is the receiver, sending data for transmission number %04d.", n);

        //Set up a transaction of 128 bytes to send/receive
        t.length=4*8;
        t.tx_buffer=sendbuf;
        t.rx_buffer=recvbuf;
        /* This call enables the SPI slave interface to send/receive to the sendbuf and recvbuf. The transaction is
        initialized by the SPI master, however, so it will not actually happen until the master starts a hardware transaction
        by pulling CS low and pulsing the clock etc. In this specific example, we use the handshake line, pulled up by the
        .post_setup_cb callback that is called as soon as a transaction is ready, to let the master know it is free to transfer
        data.
        */
        ret=spi_slave_transmit(HSPI_HOST, &t, portMAX_DELAY);
        printf("ret: %d\n",ret);

        //spi_slave_transmit does not return until the master has done a transmission, so by here we have sent our data and
        //received data from the master. Print it.
        printf("Received: %d %d %d %d\n",recvbuf[0],recvbuf[1],recvbuf[2],recvbuf[3]);
    }

}

`

# sender
`/* SPI Slave example, sender (uses SPI master driver)

   This example code is in the Public Domain (or CC0 licensed, at your option.)

   Unless required by applicable law or agreed to in writing, this
   software is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
   CONDITIONS OF ANY KIND, either express or implied.
*/
#include <stdio.h>
#include <stdint.h>
#include <stddef.h>
#include <string.h>

#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "freertos/semphr.h"
#include "freertos/queue.h"

#include "lwip/sockets.h"
#include "lwip/dns.h"
#include "lwip/netdb.h"
#include "lwip/igmp.h"

#include "esp_wifi.h"
#include "esp_system.h"
#include "esp_event.h"
#include "esp_event_loop.h"
#include "nvs_flash.h"
#include "soc/rtc_cntl_reg.h"
#include "rom/cache.h"
#include "driver/spi_master.h"
#include "esp_log.h"
#include "esp_spi_flash.h"

#include "soc/gpio_reg.h"
#include "driver/gpio.h"
#include "esp_intr_alloc.h"


/*
SPI sender (master) example.

This example is supposed to work together with the SPI receiver. It uses the standard SPI pins (MISO, MOSI, SCLK, CS) to 
transmit data over in a full-duplex fashion, that is, while the master puts data on the MOSI pin, the slave puts its own
data on the MISO pin.

This example uses one extra pin: GPIO_HANDSHAKE is used as a handshake pin. The slave makes this pin high as soon as it is
ready to receive/send data. This code connects this line to a GPIO interrupt which gives the rdySem semaphore. The main 
task waits for this semaphore to be given before queueing a transmission.
*/


/*
Pins in use. The SPI Master can use the GPIO mux, so feel free to change these if needed.
*/
//#define GPIO_HANDSHAKE 2
#define GPIO_MOSI 12
#define GPIO_MISO 13
#define GPIO_SCLK 15
#define GPIO_CS 14

//The semaphore indicating the slave is ready to receive stuff.
//static xQueueHandle rdySem;

/*
This ISR is called when the handshake line goes high.
*/
/*
static void IRAM_ATTR gpio_handshake_isr_handler(void* arg)
{
    //Sometimes due to interference or ringing or something, we get two irqs after eachother. This is solved by
    //looking at the time between interrupts and refusing any interrupt too close to another one.
    static uint32_t lasthandshaketime;
    uint32_t currtime=xthal_get_ccount();
    uint32_t diff=currtime-lasthandshaketime;
    if (diff<240000) return; //ignore everything <1ms after an earlier irq
    lasthandshaketime=currtime;

    //Give the semaphore.
    BaseType_t mustYield=false;
    xSemaphoreGiveFromISR(rdySem, &mustYield);
    if (mustYield) portYIELD_FROM_ISR();
}*/


/*
void send(int data)
{
    spi_device_handle_t handle;
    int recvbuf[2]={0xBF};
    int sendbuf[1]={0};
    sendbuf[0]=data;
    spi_transaction_t t;
    memset(&t, 0, sizeof(t));
    
    t.length=1*8; //128 bytes
    t.tx_buffer=sendbuf;
    t.rx_buffer=recvbuf;

    ret=spi_device_transmit(handle, &t);
    //printf("Received: %d\n", recvbuf[0]);
}
*/



//Main application
void app_main()
{
    esp_err_t ret;
    spi_device_handle_t handle;

    //Configuration for the SPI bus
    spi_bus_config_t buscfg={
        .mosi_io_num=GPIO_MOSI,
        .miso_io_num=GPIO_MISO,
        .sclk_io_num=GPIO_SCLK,
        .quadwp_io_num=-1,
        .quadhd_io_num=-1
    };

    //Configuration for the SPI device on the other side of the bus
    spi_device_interface_config_t devcfg={
        .command_bits=0,
        .address_bits=0,
        .dummy_bits=0,
        .clock_speed_hz=9000000,
        .duty_cycle_pos=128,        //50% duty cycle
        .mode=0,
        .spics_io_num=GPIO_CS,
        .cs_ena_posttrans=3,        //Keep the CS low 3 cycles after transaction, to stop slave from missing the last bit when CS has less propagation delay than CLK
        .queue_size=3
    };

    //GPIO config for the handshake line.
    /*gpio_config_t io_conf={
        .intr_type=GPIO_PIN_INTR_POSEDGE,
        .mode=GPIO_MODE_INPUT,
        .pull_up_en=1,
        .pin_bit_mask=(1<<GPIO_HANDSHAKE)
    };*/

    uint8_t sendbuf[4]={0x0b,0x0b,0x0b,0x0b};
    uint8_t recvbuf[4]={0xee,0xee,0xee,0xee};
    spi_transaction_t t;
    memset(&t, 0, sizeof(t));////////////////////////////////

    //Create the semaphore.
    //rdySem=xSemaphoreCreateBinary();

    //Set up handshake line interrupt.
    //gpio_config(&io_conf);
    //gpio_install_isr_service(0);
    //gpio_set_intr_type(GPIO_HANDSHAKE, GPIO_PIN_INTR_POSEDGE);
    //gpio_isr_handler_add(GPIO_HANDSHAKE, gpio_handshake_isr_handler, NULL);

    //Initialize the SPI bus and add the device we want to send stuff to.
    ret=spi_bus_initialize(HSPI_HOST, &buscfg, 1);
    assert(ret==ESP_OK);
    ret=spi_bus_add_device(HSPI_HOST, &devcfg, &handle);
    assert(ret==ESP_OK);

    //Assume the slave is ready for the first transmission: if the slave started up before us, we will not detect 
    //positive edge on the handshake line.
    //xSemaphoreGive(rdySem);

    while(1) {
        //snprintf(sendbuf, 128, "Sender, transmission no. %04i. Last time, I received: \"%s\"", n, recvbuf);
        t.length=4*8; //128 bytes
        t.tx_buffer=sendbuf;
        t.rx_buffer=recvbuf;
        //Wait for slave to be ready for next byte before sending
        //xSemaphoreTake(rdySem, 100); //Wait until slave is ready);//portMAX_DELAY); //Wait until slave is ready
        ret=spi_device_transmit(handle, &t);
        printf("Received: %d %d %d %d\n",recvbuf[0],recvbuf[1],recvbuf[2],recvbuf[3]);
    }

    //Never reached.
    ret=spi_bus_remove_device(handle);
    assert(ret==ESP_OK);
}`

**Comment by yake827** [comment]
Hi @L-eeX , Because you using the 10 cm (3.94 inch) dupont line, I suggest the  clock_speed_hz  less than 3MHz.

**Comment by L-eeX** [comment]
Hi @ yake827，Almost all the frequencies have been tried, and the data cannot be fully received

**Comment by yake827** [comment]
Hi @L-eeX , could you  give me your ESP-IDF commit? I have tested the SPI slave demo using the latest commit and find it is OK.

**Comment by L-eeX** [comment]
Hi @ L-eeX，I downloaded the latest esp-idf，I just changed the spi_slave example，My spi slave code is in the reply above。

**Comment by FayeY** [comment]
Hi @L-eeX , sorry that we cannot reproduce your problem, could you check your hardware? We think that maybe it is a hardware issue.

**Comment by 9599** [comment]
Do you solve the problem. I have the same problem on the example of spi_slave.
