### ISSUE TITLE
Task name IDLE not same as in the documentation (IDFGH-11021)

### ISSUE THREAD

**Issue by Botond-Colop** [espressif/esp-idf#12204]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Hello everyone,

I found a little difference between the documentation and the actual code.

According to the IDF Programming guide, two IDLEs task with different numbers should be started.
![grafik](https://github.com/espressif/esp-idf/assets/144316891/7989bd58-8e74-4f75-8f80-8cda2b7063c6)
Otherwise, the task information cannot be requested from the operating system. (as you can see on this picture with IDLE)
![grafik](https://github.com/espressif/esp-idf/assets/144316891/badd8ca0-9f08-46b0-9358-4b1dd20c0915)
The task list was queried with this function: _vTaskList(taskList)_
As we can see, the two IDLE tasks have the same name.
I am using IDF Version 4.4.2

What is also not optimal is that a task has a space _Tmr Svc_ in its name instead of being separated by an underscore **Tmr_Scv**.

Thank you in advance.

Best regards,
Botond

**Comment by ESP-Marius** [comment]
Yeah, seems like this got changed back in a3c90bf59add3 during a freertos kernel upgrade.

We'll take a look at it!

**Comment by ammaree** [comment]
Can I second the comment on ‘Tmr Svc” becoming “TmrSvc” or similar.

We use the task name as part of our Syslog support and a space in the name breaks the RFC standard!!

Took the issue up with Richard Barry many years ago, he agreed to resolve but probably forgot….

On 23/09/07, 11:20, "ESP-Marius" ***@***.******@***.***>> wrote:


Yeah, seems like this got changed back in a3c90bf<https://github.com/espressif/esp-idf/commit/a3c90bf59add307d3a41f5fb4c17385ee67dcf20> during a freertos kernel upgrade.

We'll take a look at it!

**Comment by Botond-Colop** [comment]
The fact that the Tmr Svc has a space in the name is only a small problem, but the two "IDLE" tasks have the same name, in my opinion it is a bug.
With the same name "IDLE" you are not able to get some separately Task info to the two tasks. You can always query information about the last started task.

**Comment by igrr** [comment]
FWIW there is [xTaskGetIdleTaskHandleForCPU](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/freertos_additions.html?highlight=xtaskgetidletaskhandle#_CPPv428xTaskGetIdleTaskHandleForCPU10BaseType_t) which should allow you to get each of the idle task handles.
