### ISSUE TITLE
ESPNOW ersu send frame (IDFGH-11035)

### ISSUE THREAD

**Issue by MacWyznawca** [espressif/esp-idf#12216]
### Is your feature request related to a problem?

What it is and what the setting changes: **ESPNOW using ersu send frame**?

The documentation and the internet are silent on this subject.

### Describe the solution you'd like.

More info about **ersu** send frame.

**Comment by Xiehanxin** [comment]
hi, @MacWyznawca , ERSU is a transmission mode related to 802.11 ax . another mode in 802.11 ax is SU. this setting means sending ESP-NOW frame is ERSU mode.  ERSU is always usde in long range transmission, and its frame has lower rate compared with SU mode

**Comment by MacWyznawca** [comment]
Thanks, @Xiehanxin. So using this frame with ESP32-S3 and C3 connections only is useless?

**Comment by Xiehanxin** [comment]
@MacWyznawca yes, it is the feature for ESP32-C6

**Comment by MacWyznawca** [comment]
@Xiehanxin Can you add this explanation to the documentation? Because I haven't found anywhere.

**Comment by zhangyanjiaoesp** [comment]
@MacWyznawca will update the doc ASAP.
