### ISSUE TITLE
[v4.4][wifi] wifi:Haven't to connect to a suitable AP now! (IDFGH-11038)

### ISSUE THREAD

**Issue by KonssnoK** [espressif/esp-idf#12219]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

esp32s3 based on b9e8e0ef4eec3984ab471bd496dd84b753123cf2

when device is not connected because it cannot find the access point the device is now reporting this log on every packet sent via LTE...

What is this log supposed to mean?

It did not show up before

```
W (1235910) wifi:Haven't to connect to a suitable AP now!
I (10:29:52.662) mesh_main: <MESH_EVENT_SCAN_DONE>number:42
W (10:29:52.669) mesh_hand: scan_done: found 0, fixed_root 1, has_parent 0
I (10:30:01.220) processor: send (fast) status... (10000ms)
W (1245908) wifi:Haven't to connect to a suitable AP now!
I (10:30:11.221) processor: send (fast) status... (10000ms)
W (1255908) wifi:Haven't to connect to a suitable AP now!
```

**Comment by KonssnoK** [comment]
Hello @Xiehanxin 

we use 
- wifi mesh
- LTE fallback 

Basically if you start the mesh and you cannot find the AP ( no parent found ) or you get disconnected for some time ( invalid password / wrong password ) we fallback on a LTE modem. To do this we simply create a new netif interface with higher priority and start periodically (30s) scanning for WIFI to come back.

To see this log i simply started the device with no hotspot enabled -> no parent found
The wifi will be scanned but without relevant results (the wanted AP is off)

```

V (01:03:07.854) modem_comm: modemcomm_got_ip()
V (01:03:07.859) modem_task: Got MODEM_MSG_GOT_IP message
W (01:03:07.860) network: GOT IP from ppp_sta
V (01:03:07.866) modem_task: Got MODEM_EVT_GOT_IP event
I (01:03:07.871) network: Network connected
I (01:03:07.880) offline: object saved to PSRAM, free 5786
W (188882) wifi:Haven't to connect to a suitable AP now!
I (01:03:07.891) mesh_netif: Interface AP
W (188904) wifi:Haven't to connect to a suitable AP now!
I (01:03:07.902) mesh_netif: Clearing interface <sta>
```

full log attached
[230911_wifi_logs.txt](https://github.com/espressif/esp-idf/files/12575118/230911_wifi_logs.txt)

**Comment by KonssnoK** [comment]
I think i found out where the log is coming from:

`esp_err_t esp_wifi_sta_get_ap_info(wifi_ap_record_t *ap_info);`

This function is generating the log when the ap info is requested without being connected.
Considering the function returns `ESP_ERR_WIFI_NOT_CONNECT `
i don't see the reason for such log.

**Comment by KonssnoK** [comment]
Anybody?

**Comment by zhangyanjiaoesp** [comment]
> I think i found out where the log is coming from:
> 
> `esp_err_t esp_wifi_sta_get_ap_info(wifi_ap_record_t *ap_info);`
> 
> This function is generating the log when the ap info is requested without being connected. Considering the function returns `ESP_ERR_WIFI_NOT_CONNECT ` i don't see the reason for such log as a warning. @Xiehanxin

@KonssnoK Yes, you are right, the `Haven't to connect to a suitable AP now!` warning is shown when you want to get the AP's info without connecting to it.

Have you solved the problem？

**Comment by KonssnoK** [comment]
> > I think i found out where the log is coming from:
> > `esp_err_t esp_wifi_sta_get_ap_info(wifi_ap_record_t *ap_info);`
> > This function is generating the log when the ap info is requested without being connected. Considering the function returns `ESP_ERR_WIFI_NOT_CONNECT ` i don't see the reason for such log as a warning. @Xiehanxin
> 
> @KonssnoK Yes, you are right, the `Haven't to connect to a suitable AP now!` warning is shown when you want to get the AP's info without connecting to it.
> 
> Have you solved the problem？

Hello @zhangyanjiaoesp ,
the log is still there, the question is: are you going to keep it?
It doesn't look like a warning to me.

**Comment by zhangyanjiaoesp** [comment]
yes, we will keep it.

**Comment by nebkat** [comment]
@zhangyanjiaoesp Could this be reconsidered?

I agree with @KonssnoK here that the warning is unnecessary considering `ESP_ERR_WIFI_NOT_CONNECT` is available.

This would be a great way to probe whether WiFi is connected (especially from parts of the program not directly related to WiFi), but instead we need to keep track of `WIFI_EVENT_STA_CONNECTED`/`DISCONNECTED` and share this state globally.

If nothing else the message is rather cryptic and should really be "AP info requested while not connected".
