### ISSUE TITLE
ESP32S3配置SPI过程中，CLK映射失败 (IDFGH-11046)

### ISSUE THREAD

**Issue by weekroom** [espressif/esp-idf#12227]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

idf4.4.4框架下我使用ESP32的SPI2进行SPI通信是正常的，但是我移植到ESP32S3时，我根据IDF文档修改为ESP32S3相关参数，但是CLK配置失败
下面这个是ESP32部分代码
EspHal* hal = new EspHal(18, 19, 23);  //sck,miso,mosi    32 
  // initialize pins
     // initialize pins
      this->pinMode(this->spiSCK, OUTPUT);
      this->pinMode(this->spiMISO, INPUT);
      this->pinMode(this->spiMOSI, OUTPUT);
      gpio_matrix_out(this->spiSCK, HSPICLK_OUT_IDX, false, false);
      gpio_matrix_in(this->spiMISO, HSPIQ_OUT_IDX, false);
      gpio_matrix_out(this->spiMOSI, HSPID_IN_IDX, false, false);
   串口输出代码：
   I (334) gpio: GPIO[18]| InputEn: 1| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 
I (344) gpio: GPIO[19]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0
I (354) gpio: GPIO[23]| InputEn: 1| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 
I (364) gpio: GPIO[5]| InputEn: 1| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0
I (374) gpio: GPIO[4]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 
I (374) gpio: GPIO[32]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 
I (384) gpio: GPIO[14]| InputEn: 1| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0
I (404) SX1280: Initialization successful!

下面这个是ESP32S3的：
相关文档说ESP32S3的SPI2默认引脚是 10 11 12 13    所以我这里是使用11 12 13
EspHal* hal = new EspHal(12, 13, 11);  //sck,miso,mosi     s3
// initialize pins
      this->pinMode(this->spiSCK, OUTPUT);
      this->pinMode(this->spiMISO, INPUT);
      this->pinMode(this->spiMOSI, OUTPUT);
      
      gpio_matrix_out(this->spiSCK, FSPICLK_OUT_IDX, false,  false);
      gpio_matrix_in(this->spiMISO, FSPIQ_OUT_IDX,  false);
      gpio_matrix_out(this->spiMOSI,FSPID_IN_IDX, false,  false);
 串口输出代码：
I (329) gpio: GPIO[12]| InputEn: 1| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0
I (339) gpio: GPIO[13]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 
I (349) gpio: GPIO[11]| InputEn: 1| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0
I (359) gpio: GPIO[10]| InputEn: 1| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 
I (369) gpio: GPIO[5]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0
I (379) gpio: GPIO[9]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 
I (379) gpio: GPIO[6]| InputEn: 1| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 
E (3399) SX1280: Initialization failed with error code -2 

   这里-2是指引脚没设置好
   然后我测试将ESP32的   gpio_matrix_out(this->spiSCK, HSPICLK_OUT_IDX, false, false);这一行注释以后，也会得到-2，从而我推断是CLK配置失败，可是我查阅了ESP32S3的gpio_sig_map.h文件，发现SPI2的设置确实是这些
   #define FSPICLK_IN_IDX                101
#define FSPICLK_OUT_IDX               101
#define FSPIQ_IN_IDX                  102
#define FSPIQ_OUT_IDX                 102
#define FSPID_IN_IDX                  103
#define FSPID_OUT_IDX                 103
#define FSPIHD_IN_IDX                 104
#define FSPIHD_OUT_IDX                104
#define FSPIWP_IN_IDX                 105
#define FSPIWP_OUT_IDX                105
为此我不知道到底是哪里配置导致CLK失败，以及解决办法

**Comment by wanckl** [comment]
@weekroom emmmm,,你可能不知道esp32的gpio有 gpio_matrix 和 iomux 功能，gpio_matrix可以指定任意引脚来用，不需要和默认引脚一一对应，并且实测跑40M没有区别。     
iomux就是只能指定默认引脚，并且一一对应，在老的芯片上这个路径会比gpio_matrix快。     

回到问题，你可以参考 `spi_common.c`里面的 spicommon_bus_initialize_io(), 和 bus_iomux_pins_set_quad()。
