### ISSUE TITLE
ESP32 Auto Light Sleep (IDFGH-11051)

### ISSUE THREAD

**Issue by EUA** [espressif/esp-idf#12232]
### Is your feature request related to a problem?

Use of forced Light Sleep leads connection drops on ESP32 as expected.
So please get us Auto Light Sleep.
ESP8266 has such a feature but ESP32 still missing...
THanks

**Comment by sudeep-mohanty** [comment]
We do support automatic light sleep for ESP32. You can find details about how to use it [here](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/power_management.html#power-management).

**Comment by EUA** [comment]
Oops. Wrong project. I wanted to send into Arduino project instead of here. Thanks!
