### ISSUE TITLE
Failed to erase flash when secure boot enabled (IDFGH-11067)

### ISSUE THREAD

**Issue by eme-bennytang** [espressif/esp-idf#12242]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Hi,

I am using the secure boot + flash encryption features.
But after enabling secure boot, I found that I must flash the program with the --no-stub parameters.

After some digging, that should mean using the ROM code "Limited functions" only.
But when I try to erase-flash / erase-region, the device prompts below error
![image](https://github.com/espressif/esp-idf/assets/52727929/6f56bb12-a585-4b8a-b14f-1e9b4d7063ed)

But that fact that I can still write-flash (means it will erase the region first before writing), makes this very weird.

I don't know if this is an intended design, or did I miss something?
If its intended, is there any "work around" to actually erase some regions?

**Comment by mahavirj** [comment]
@eme-bennytang 

Yes, this is intended behavior. Please see documentation regarding this available [here](https://docs.espressif.com/projects/esp-idf/en/latest/esp32s3/security/security.html#uart-download-mode).

You may create a binary with all `0xFF` contents and use the write_flash command to erase a specific region. This should serve as the work around to selectively erase flash region.
