### ISSUE TITLE
Homekit compatibility

### ISSUE THREAD

**Issue by ToXiiK** [espressif/esp-idf#1225]
Hello,

I heard about homekit sdk in c of expressif , does anyone know how to get this sdk as well as the documentation? because I can not find any information on this sdk on google.

thank you in advance

Cordially

**Comment by negativekelvin** [comment]
If you are mFi approved, contact espressif

**Comment by ToXiiK** [comment]
i am not mfi but as homekit has been open to makers for noncommercial applications, sdk should be available for all?

**Comment by btashton** [comment]
@negativekelvin I have the appropriate paperwork with Apple for MFI development, who in espressif should I reach out to about this?

**Comment by negativekelvin** [comment]
@btashton would suggest you go through your sales contact at sales@espressif.com and ask them to have appropriate person contact you regarding access to Apple homekit software

**Comment by igrr** [comment]
Yes, please contact sales for Homekit SDK related questions.
