### ISSUE TITLE
Download 2 binaries files with OTA on Nina W106 (IDFGH-11081)

### ISSUE THREAD

**Issue by zapsalis** [espressif/esp-idf#12255]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Hi everyone,

I am currently looking to update my Nina via Wifi using OTA.

However, the problem that confronts me is that when I build my project "idf.py build", 2 binaries are generated: The first "web-form.bin" including all the "C" code, and the second "storage .bin", including all html/css/js.

I am currently able to download a "web-form.bin" binary, and it downloads well in my card, and my product resets well on it, the update is therefore done correctly. However, how can I also download the “storage.bin” binary? Because if I modify my web page, I want to be able to update it via wifi too.

Below you can see my partition table : 

> '# Name,   Type, SubType, Offset,  Size, Flags
> '# Note: if you change the phy_init or app partition offset, make sure to change the offset in Kconfig.projbuild
> nvs,      data, nvs,     0x9000,  0x4000,
> otadata,  data, ota,     0xd000,  0x2000
> phy_init, data, phy,     0xf000,  0x1000,
> factory,  app,  factory, 0x10000, 1M,
> storage,  data, spiffs,  ,        0xF0000,
> ota_0,    app,  ota_0,   ,        1M,
> ota_1,    app,  ota_1,   ,        1M,

With factory partition, when i put "web-form.bin" (for the code C), and storage partition when i put "storage.bin" (for the web page code).

If you have ideas for how to update my product when I have 2 binaries, I'm interested.

Thank you so much
Sincerely,
Zapsalis

**Comment by hmalpani** [comment]
Hello @zapsalis 
You can refer to [spiffs example](https://github.com/espressif/esp-idf/tree/master/examples/storage/spiffs) in ESP-IDF for serving your purpose. I recommend you download the storage.bin file using esp_http_client and simultaneously write it into the spiffs partition.

**Comment by zapsalis** [comment]
Hi @hmalpani,

Thanks for your response, I tried this problem.

But finally, with a python script, I convert all my html css and js files to variables to only have one binary to update.

THANKS,
Zapsalis
