### ISSUE TITLE
Power consumption (IDFGH-11140)

### ISSUE THREAD

**Issue by weiwi** [espressif/esp-idf#12309]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Hello,

I am getting similar power consumption to what is in the readme file. I was wondering if a lower power consumption can be achieved using auto lightsleep with wifi monitoring, like shown in the table from expressif. This is for ESP32S3. Thanks.  
![image](https://github.com/espressif/esp-idf/assets/29485018/4c4d74c0-ef84-48d1-8fbe-a2b0910f1da6)

**Comment by esp-lis** [comment]
@weiwi You can use the esp32c3, esp32c2 or esp32c6 for the same function with lower current consumption, The following gives the power test report of esp32c3:
![image](https://github.com/espressif/esp-idf/assets/94179860/79255a98-f14e-44d9-8627-925c09f5cdab)

**Comment by esp-lis** [comment]
esp32c6 current consumption reference is as follows:
![image](https://github.com/espressif/esp-idf/assets/94179860/8322d784-6d68-491d-ad1c-d84bcb617655)

**Comment by Sherry616** [comment]
Thanks for reporting, will close due to short of feedback, feel free to reopen with more updates. 
Thanks for using our Espressif product!
