### ISSUE TITLE
How to choose Android Phones when testing DPP on ESP32 (IDFGH-11164)

### ISSUE THREAD

**Issue by Zilinlin** [espressif/esp-idf#12332]
Hi, I'm a new guy in DPP or EasyConnect research. 
I'm testing the EasyConnect function on ESP-WROOM-32, and the QR code is generated successfully. However, I cannot find functions in Xiaomi 12T with Android 12 to scan the generated QR code.
Could you please give me some advice on how to choose the Android phones to test the EasyConnect functions? It seems like some phones with Android 10+ don't support EastConnect function. Many thanks!

**Comment by kapilkedawat** [comment]
Hi @Zilinlin, vendor may choose not to enable this functionality in their android. I would suggest to go with phones which uses stock or near stock android to use this feature.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, feel free to reopen.
