### ISSUE TITLE
OpenThread - Example for simple end device (IDFGH-11167)

### ISSUE THREAD

**Issue by baylf2000** [espressif/esp-idf#12335]
### Is your feature request related to a problem?

There are no examples currently for thread end devices, like a light or switch.

### Describe the solution you'd like.

It would be very helpful to have some simple examples that might be used for Thread lights, switches, sensors etc.

**Comment by chshu** [comment]
Thread is a network layer protocol, just like Wi-Fi. An application is required to build a Thread products (light, switch, ...).

Matter is the currently the most popular application runs over Thread, please check the light example in esp-matter here: https://github.com/espressif/esp-matter/tree/main/examples/light

If you want to implement some other applicaitons, you can also use the TCP/UDP APIs directly, refer to the udp example: https://github.com/espressif/esp-thread-br/blob/main/components/esp_ot_cli_extension/src/esp_ot_udp_socket.c

**Comment by chshu** [comment]
@baylf2000 Please reopen if any follow up questions.
