### ISSUE TITLE
Functions with 'void' parameter list return "ESP_ERR_INVALID_ARG" (documentation) (IDFGH-11163)

### ISSUE THREAD

**Issue by nkaaf** [espressif/esp-idf#12331]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

I wonder if there is a reason why functions without parameters (void) can return "ESP_ERR_INVALID_ARG" according to the documentation. I found two such functions in "esp_wifi.h", I don't know if there are more functions in the project:

- esp_wifi_start
- esp_wifi_clear_ap_list

If this is because underlaying functions can return the ESP_ERR_INVALID_ARG error, I could understand, but I find it very confusing because the "main" API functions that users call do not take parameters.

**Comment by hansw123** [comment]
hi @nkaaf 
sorry for late reply
It is indeed because the function called inside the api returns ESP_ERR_INVALID_ARG, and we'll discuss whether to change the internal handling or change the description of the api to make it more accurate
