### ISSUE TITLE
When enable nvs encryption, does it encrypt nvs data previously flahsed? (IDFGH-11183)

### ISSUE THREAD

**Issue by junyoun-kim** [espressif/esp-idf#12350]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

I wonder when enable nvs encryption, if it encrypts nvs data previously flahsed.

When I tested, I can see OK logs about nvs key partition generation and nvs flash secure initialization.

But, When I dumped nvs partition after, it's still previous plain text.

Initializing nvs encryption partition process doesn't include encrypting previous plain nvs data?

**Comment by mahavirj** [comment]
@junyoun-kim 

> if it encrypts nvs data previously flahsed

No.

For pre-encrypting the NVS partitions, please refer to this [guide](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/storage/nvs_partition_gen.html#generate-encrypted-nvs-partition).

For secure initialization of the custom NVS partition, please refer to this [example](https://github.com/espressif/esp-idf/blob/272b4091f1f1ff169c84a4ee6b67ded4a005a8a7/examples/security/flash_encryption/main/flash_encrypt_main.c#L74-L88).
