### ISSUE TITLE
如果我的EXAMPLE_I2S_DUPLEX_MODE 配置成1 显示的是0，是哪里的问题？ (IDFGH-11210)

### ISSUE THREAD

**Issue by huangdiajd** [espressif/esp-idf#12376]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

5.0.3

### Espressif SoC revision.

esp32-s3

### Operating System used.

Windows

### How did you build your project?

VS Code IDE

### If you are using Windows, please specify command line type.

None

### Development Kit.

esp32-s3

### Power Supply used.

USB

### What is the expected behavior?

如果我的EXAMPLE_I2S_DUPLEX_MODE 配置成1 显示的是0，是哪里的问题？

### What is the actual behavior?

如果我的EXAMPLE_I2S_DUPLEX_MODE 配置成1 显示的是0，是哪里的问题？

### Steps to reproduce.

如果我的EXAMPLE_I2S_DUPLEX_MODE 配置成1 显示的是0，是哪里的问题？

### Debug Logs.

```plain
如果我的EXAMPLE_I2S_DUPLEX_MODE 配置成1 显示的是0，是哪里的问题？
```

### More Information.

如果我的EXAMPLE_I2S_DUPLEX_MODE 配置成1 显示的是0，是哪里的问题？

**Comment by suda-morris** [comment]
which example? how do you configure the `EXAMPLE_I2S_DUPLEX_MODE`? in the menuconfig or by hard code?
