### ISSUE TITLE
The ESP32S3 runs the i2s_recorder example, and the data of the MEMS microphone cannot be collected (IDFGH-11216)

### ISSUE THREAD

**Issue by huangdiajd** [espressif/esp-idf#12382]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

5.0.3

### Espressif SoC revision.

esp32-s3

### Operating System used.

Windows

### How did you build your project?

VS Code IDE

### If you are using Windows, please specify command line type.

None

### Development Kit.

esp32-s3

### Power Supply used.

USB

### What is the expected behavior?

This is my serial port has been output data, I think it should be the change of data
[0] -30935 [1] -30935 [2] -30935 [3]-30935 ...
[0] -30935 [1] -30935 [2] -30935 [3]-30935 ...
[0] -30935 [1] -30935 [2] -30935 [3]-30935 ...
[0] -30935 [1] -30935 [2] -30935 [3]-30935 ...

### What is the actual behavior?

This is my serial port has been output data, I think it should be the change of data
[0] -30935 [1] -30935 [2] -30935 [3]-30935 ...
[0] -30935 [1] -30935 [2] -30935 [3]-30935 ...
[0] -30935 [1] -30935 [2] -30935 [3]-30935 ...
[0] -30935 [1] -30935 [2] -30935 [3]-30935 ...

### Steps to reproduce.

/*
 * SPDX-FileCopyrightText: 2021-2022 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Unlicense OR CC0-1.0
 */

/* I2S Digital Microphone Recording Example */
#include <stdio.h>
#include <string.h>
#include <math.h>
#include <sys/unistd.h>
#include <sys/stat.h>
#include "sdkconfig.h"
#include "esp_log.h"
#include "esp_err.h"
#include "esp_system.h"
#include "esp_vfs_fat.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "driver/i2s_pdm.h"
#include "driver/gpio.h"
#include "driver/spi_common.h"
#include "sdmmc_cmd.h"
// #include "format_wav.h"

static const char *TAG = "pdm_rec_example";

#define NUM_CHANNELS        1
#define SAMPLE_SIZE         16 * 1024
#define BYTE_RATE           44100 * 2
#define I2S_DATA_GPIO       35
#define I2S_CLK_GPIO        36
#define REC_TIME     15
i2s_chan_handle_t rx_handle = NULL;

static int16_t i2s_readraw_buff[SAMPLE_SIZE];
size_t bytes_read;

void init_microphone(void)
{
    i2s_chan_config_t chan_cfg = I2S_CHANNEL_DEFAULT_CONFIG(I2S_NUM_AUTO, I2S_ROLE_MASTER);
    ESP_ERROR_CHECK(i2s_new_channel(&chan_cfg, NULL, &rx_handle));

    i2s_pdm_rx_config_t pdm_rx_cfg = {
        .clk_cfg = I2S_PDM_RX_CLK_DEFAULT_CONFIG(BYTE_RATE),
        /* The default mono slot is the left slot (whose 'select pin' of the PDM microphone is pulled down) */
        .slot_cfg = I2S_PDM_RX_SLOT_DEFAULT_CONFIG(I2S_DATA_BIT_WIDTH_16BIT, I2S_SLOT_MODE_MONO),
        .gpio_cfg = {
            .clk = I2S_CLK_GPIO,
            .din = I2S_DATA_GPIO,
            .invert_flags = {
                .clk_inv = false,
            },
        },
    };
    ESP_ERROR_CHECK(i2s_channel_init_pdm_rx_mode(rx_handle, &pdm_rx_cfg));
    ESP_ERROR_CHECK(i2s_channel_enable(rx_handle));
}

void app_main(void)
{
    printf("PDM microphone recording example start\n--------------------------------------\n");

    // Acquire a I2S PDM channel for the PDM digital microphone
    init_microphone();
    while (1)
    {
        // Read the RAW samples from the microphone
        if (i2s_channel_read(rx_handle, (char *)i2s_readraw_buff, SAMPLE_SIZE, &bytes_read, 1000) == ESP_OK) {
            printf("[0] %d [1] %d [2] %d [3]%d ...\n", i2s_readraw_buff[0], i2s_readraw_buff[1], i2s_readraw_buff[2], i2s_readraw_buff[3]);
        } else {
            printf("Read Failed!\n");
        }
        vTaskDelay(100/portTICK_PERIOD_MS);
    }
    ESP_LOGI(TAG, "Recording done!");
    // Stop I2S driver and destroy
    ESP_ERROR_CHECK(i2s_channel_disable(rx_handle));
    ESP_ERROR_CHECK(i2s_del_channel(rx_handle));
}

### Debug Logs.

```plain
I (291) sleep: Configure to isolate all GPIO pins in sleep state
I (297) sleep: Enable automatic switching of GPIO sleep configuration
I (305) app_start: Starting scheduler on CPU0
I (309) app_start: Starting scheduler on CPU1
I (309) main_task: Started on CPU0
I (319) main_task: Calling app_main()
PDM microphone recording example start
--------------------------------------
[0] 0 [1] 41 [2] -30273 [3]-31424 ...
[0] -30935 [1] -30935 [2] -30935 [3]-30935 ...
[0] -30935 [1] -30935 [2] -30935 [3]-30935 ...
[0] -30935 [1] -30935 [2] -30935 [3]-30935 ...
[0] -30935 [1] -30935 [2] -30935 [3]-30935 ...
[0] -30935 [1] -30935 [2] -30935 [3]-30935 ...
[0] -30935 [1] -30935 [2] -30935 [3]-30935 ...
[0] -30935 [1] -30935 [2] -30935 [3]-30935 ...
[0] -30935 [1] -30935 [2] -30935 [3]-30935 ...
[0] -30935 [1] -30935 [2] -30935 [3]-30935 ...
```

### More Information.

NO

**Comment by endotronic** [comment]
This isn't helpful, sorry, but I thought I'd chime in that I arrived here by searching "esp32 30935" as it turns out I am having the exact same problem. I have a very basic setup, just following examples, which enables I2S for RX in PDM mode. I've tried various data pins, including one just grounded, and I only ever read this -30935 value.

I also tried the same thing with all Arduino functions (see [here](https://espressif-docs.readthedocs-hosted.com/projects/arduino-esp32/en/latest/api/i2s.html)), and I got the same result.

I'm pretty confused where I'm going wrong since I'm just setting up the very basic functionality.

**Comment by L-KAYA** [comment]
Hi @huangdiajd @endotronic , I've tried the example with 88200Hz sample rate and `35 & 36` GPIO pins, I can receive the correct data like:
![image](https://github.com/espressif/esp-idf/assets/42017963/574b255a-c988-4b1c-9a6e-cf3e48dda1dc)

If the connection of pin is correct, please check whether there are clock and data on the pin via oscilloscope or logic analyzer, some PDM micro phone has limitation of the oversampling rate, while exceed or below the required clock frequency, there won't be data on the data line, you may also need to check the datasheet of the PDM mic.

**Comment by endotronic** [comment]
I really appreciate the reply @L-KAYA.

I've tried pulling the data line high, and I still see only -30935 in the buffer. I also enabled PDM2PCM, expecting that after this transformation, I would see 0 instead of -30935, but even after this, I _still_ get only -30935 in the buffer!
```
  REG_SET_BIT(I2S_RX_CONF_REG(I2S_NUM_0), I2S_RX_PDM2PCM_EN);

  Serial.print("I2S_RX_CONF_REG =");
  Serial.println(REG_READ(I2S_RX_CONF_REG(I2S_NUM_0)), HEX);
```

The value I got for this register was 0x00309404, which looks correct, though I didn't go through every bit.

I have been doing this on non-default pins, and I have been building with PlatformIO instead of ESP-IDF directly. I am going to try to create the simplest possible test with default pins and only ESP-IDF tools, and I'll see what happens.

**Comment by endotronic** [comment]
Alright, I set up ESP-IDF 5.1.1 in VSCode (fresh installation), I created a new project based on the i2s_pdm example, and I changed only the pins used and I forced it into the RX mode. Now running this with a monitor, I am seeing 4 bytes of -30935 and 4 bytes that have some noise but mostly repeat values around -30935 to -18596.

While this is running, I've manually shorted the data pin to power and ground just trying to change the data I'm seeing, but there is no change. I've also tried various other pins for data and clock (EXAMPLE_PDM_RX_CLK_IO and EXAMPLE_PDM_RX_DIN_IO in the example code), including actual data out from a PDM mic, and the data I get is exactly the same. I can't seem to do anything that leads to any change in the values I'm seeing over the serial monitor.

I don't have an oscilloscope or logic analyzer available to me right now (I'm just a hobbyist), but I'll try to get something or borrow one. With that said, I really would have expected shorting the data pin to ground and power to show me something in the output.

**Comment by endotronic** [comment]
You can disregard my comments. I got a logic analyzer, and I can see that my PDM mic is not working.

**Comment by L-KAYA** [comment]
Thanks for your reply! If the PDM mic does not work, these checks might help:

1. Check if there is faulty soldering;
2. Check if the power supply and the ground voltage of the mic are correct;
3. Check if the oversample rate is out of support range (referring to the PDM datasheet);
4. Change a PDM mic to check if the mic is broken;

**Comment by endotronic** [comment]
I appreciate the tips. I'm guessing soldering must be the issue. I got a PDM mic breakout board from Adafruit and it worked immediately, no code changed, worked as expected on the first try.

It probably doesn't matter, but the PDM mic I was trying to use was a IMP34DT05TR. Seems like it should have been fine. Maybe I had the land pattern wrong or something.
