### ISSUE TITLE
Issue with MDNS v1.2.1  (IDFGH-11221)

### ISSUE THREAD

**Issue by krupis** [espressif/esp-idf#12387]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v5.0.1

### Espressif SoC revision.

ESP32-D0WD-V3

### Operating System used.

Windows

### How did you build your project?

VS Code IDE

### If you are using Windows, please specify command line type.

PowerShell

### Development Kit.

Custom Board

### Power Supply used.

USB

### What is the expected behavior?

I expect the mDNS 1.2.1 to work exactly the same as 1.2.0. I did not have any issues with the 1.2.0 as I can reach my webserver by using mDNS instance name.

### What is the actual behavior?

mDNS not working when updated to the latest version (1.2.1) due to ERR_NAME_NOT_RESOLVED error:
![image](https://github.com/espressif/esp-idf/assets/22237034/b6955ff9-a019-4a89-baad-132a4a83e999)

It loads for about 15 seconds and then returns an error:
![image](https://github.com/espressif/esp-idf/assets/22237034/b789a804-2400-4320-8dd2-fafadf282108)

I am able to capture mDNS packets using wire shark but cannot figure out why any browser fails to connect to it:
![image](https://github.com/espressif/esp-idf/assets/22237034/fb307c5d-d2ba-4a58-997e-7168ff63642e)

### Steps to reproduce.

Change the version of the mdns component in idf_component.yml from 1.2.0 to 1.2.1 and rebuild the project.

### Debug Logs.

```plain
N/A
```

### More Information.

We use the following function to setup the mDNS:
```
static void wifi_mdns_init(void) {
    esp_err_t err = ESP_OK;
    err           = mdns_init();
    if (err != ESP_OK) {
        TraceErrWIFI("mDNS INIT: FAILED (%s)", esp_err_to_name(err));
        return;
    }
    err = mdns_hostname_set(CONFIG_LWIP_LOCAL_HOSTNAME);
    if (err != ESP_OK) {
        TraceErrWIFI("HOSTNAME: FAILED (%s)", esp_err_to_name(err));
        return;
    }
    err = mdns_instance_name_set(CONFIG_LWIP_LOCAL_HOSTNAME);
    if (err != ESP_OK) {
        TraceErrWIFI("INSTANCE: FAILED (%s)", esp_err_to_name(err));
        return;
    }
    err = mdns_service_add("XXXXXXX-XXXXX", "_http", "_tcp", 80, NULL, 0);
    if (err != ESP_OK) {
        TraceErrWIFI("SERVICE: FAILED (%s)", esp_err_to_name(err));
        return;
    }
}
```

![image](https://github.com/espressif/esp-idf/assets/22237034/ea79f779-5dc2-44b2-b2b7-e17183d556d5)

I have also noticed that for mdns 1.2.1 , the following flag is used: ```CONFIG_ESP_WIFI_ENABLED``` however this does not even exist in my sdkconfig.h. How is that even possible?
![image](https://github.com/espressif/esp-idf/assets/22237034/ba79c045-61c6-4ca2-a9db-eb95d0a8c7e8)

For now, I am using mDNS version 1.2.0 but I am just really curious what could be an issue with the 1.2.1 and what could cause this failure. Any ideas are appreciated!

**Comment by gabsuren** [comment]
@krupis thank you for reporting. 
As I understand, you want to configure mdns over the WIFI interface, right?
The problem, as you noted, is the absence of `CONFIG_ESP_WIFI_ENABLED` in your `sdkconfig.h`. This is needed to register `mdns` event handlers.
Could you please check if `CONFIG_ESP_WIFI_ENABLED` is enabled in the `sdkconfig` (this file used to generate `sdkconfig.h`) file? If it's not, it should be enabled so that mdns can register events over the `WIFI` interface.

**Comment by krupis** [comment]
@gabsuren 
Thanks for response.

```CONFIG_ESP_WIFI_ENABLED``` also does not exist in my sdkconfig. I am using esp-idf version 5.0.1

**Comment by gabsuren** [comment]
After createing `sdkconfig.defaults`, please executed `idf.py reconfigure` or remove `skconfig` and call `idf.py build/menuconfig` again

**Comment by gabsuren** [comment]
Updated: The issues is coming that `CONFIG_ESP_WIFI_ENABLED` is not exists in `esp-idf 5.0.1`. I will fix it soon. 
For quick fix there are a few options. 
1. Revert this commit `24f7031`  : fix(mdns): fix build issue if CONFIG_ESP_WIFI_ENABLED disabled
2. Add new config in `Kconfig` 
<img width="399" alt="Screen Shot 2023-10-18 at 3 07 03 PM" src="https://github.com/espressif/esp-idf/assets/4272184/1b807b29-7c1c-4c3e-91f4-6f2b6a595156">
3. Use latest `ESP-IDF`

Meanwhile I will fix the issue for official branch

**Comment by krupis** [comment]
I can confirm that adding ```ESP_WIFI_ENABLED ``` in Kconfig fixed the issue.
