### ISSUE TITLE
ESP-IDF HID Examples osal_freertos.h cant include "FreeRTOS.h" (IDFGH-11225)

### ISSUE THREAD

**Issue by OrhanYigitDurmaz** [espressif/esp-idf#12391]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

The HID Example for esp32s3 has the TinyUSB for it, but the bare one, not the Espressif's port. So I added it by simply adding `espressif/tinyusb: "^0.15.0~3"` to the idf_component.yml . This fixed the compiling problem and the #include "tinyusb.h" error. But now tinyusb.h has a include error on it. So i go to tinyusb.h, and i see cant include tusb because its dependency FreeRTOS.h is not found. I go more, and find that its in the osal_freertos.h file it cant include four files: 
```c
#include TU_INCLUDE_PATH(CFG_TUSB_OS_INC_PATH,FreeRTOS.h)
#include TU_INCLUDE_PATH(CFG_TUSB_OS_INC_PATH,semphr.h)
#include TU_INCLUDE_PATH(CFG_TUSB_OS_INC_PATH,queue.h)
#include TU_INCLUDE_PATH(CFG_TUSB_OS_INC_PATH,task.h)
```
it only says: "cannot  open source file"
and i fix it only adding the freertos folder on front of it like this:
```c
#include TU_INCLUDE_PATH(CFG_TUSB_OS_INC_PATH,freertos/FreeRTOS.h)
#include TU_INCLUDE_PATH(CFG_TUSB_OS_INC_PATH,freertos/semphr.h)
#include TU_INCLUDE_PATH(CFG_TUSB_OS_INC_PATH,freertos/queue.h)
#include TU_INCLUDE_PATH(CFG_TUSB_OS_INC_PATH,freertos/task.h)
```

so a pull request to add these lines to the `osal_freertos.h` file and the tinyusb dependency to the idf_component.yml are needed.

**Comment by OrhanYigitDurmaz** [comment]
Using powershell with VSCode IDE and ESP-IDF v5.1.1

**Comment by tore-espressif** [comment]
Hi @OrhanYigitDurmaz 
The [tusb_hid](https://github.com/espressif/esp-idf/tree/master/examples/peripherals/usb/device/tusb_hid) example is pulling [esp_tinyusb](https://components.espressif.com/components/espressif/esp_tinyusb) from ESP registry (this dependency is defined in main/idf_component.yml).
It contains the 'bare' TinyUSB + some configuration specific to ESP chips. The build works OK for me, without any changes.

Could you please share your output of your build command? and content of `dependencies.lock` file, that should be created in root of the examples after successful build? Thanks

**Comment by OrhanYigitDurmaz** [comment]
> Hi @OrhanYigitDurmaz The [tusb_hid](https://github.com/espressif/esp-idf/tree/master/examples/peripherals/usb/device/tusb_hid) example is pulling [esp_tinyusb](https://components.espressif.com/components/espressif/esp_tinyusb) from ESP registry (this dependency is defined in main/idf_component.yml). It contains the 'bare' TinyUSB + some configuration specific to ESP chips. The build works OK for me, without any changes.
> 
> Could you please share your output of your build command? and content of `dependencies.lock` file, that should be created in root of the examples after successful build? Thanks

Sorry for the inconvenience, without the changes the build also works ok for me. The IntelliSense thinks it doesnt exist.

**Comment by OrhanYigitDurmaz** [comment]
> So can we close this issue?

Yes, thanks
