### ISSUE TITLE
tx_stats - edca_retry diminishes in presence of noise.  (IDFGH-11240)

### ISSUE THREAD

**Issue by avrono** [espressif/esp-idf#12403]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

ESP-IDF v5.1.1

### Espressif SoC revision.

ESP32-C6

### Operating System used.

Linux

### How did you build your project?

Command line with idf.py

### If you are using Windows, please specify command line type.

None

### Development Kit.

ESP32-C6-DevKitC-1-N8

### Power Supply used.

USB

### What is the expected behavior?

When I introduce noise into the wifi channel , I expect to see the number of edca_retry to go up

see https://github.com/espressif/esp-idf/blob/8fc8f3f47997aadba21facabc66004c1d22de181/components/esp_wifi/include/esp_private/esp_wifi_he_types_private.h#L218C18-L218C18

### What is the actual behavior?

edca_retry is going down 

### Steps to reproduce.

1. Step enable tx_stats
2. Step Build iperf example code
3. Step Run iperf as UDP client (for example)
3. Add Noise the the wifi channel
4. plot or visually inspect the results. 
...

### Debug Logs.

```plain
![image](https://github.com/espressif/esp-idf/assets/83041/5e35c966-f022-4fd1-9eaf-ac896d1501d7)
```

**Comment by Xiehanxin** [comment]
hi @avrono ，I think the issue lies in statistics being unreasonable. because you're adding noise on the channel, which  leads to an increase in retransmissions. However, you are only counting the number of retransmissions. Due to the noise issue, our transmitted packet count will also decrease, resulting in a significant decrease in the corresponding retransmission count. It would be more reasonable to calculate the percentage instead

**Comment by Sherry616** [comment]
Thanks for reporting, will close due to short of feedback, feel free to reopen with more updates. 
Thanks for using our Espressif product!
