### ISSUE TITLE
Cannot capture images using ov7725 in esp32

### ISSUE THREAD

**Issue by James-sjec** [espressif/esp-idf#1240]
example code loaded : https://github.com/igrr/esp32-cam-demo

Following error occured when started : 
![apc - 2017 11 07 20 05 - 001 3d](https://user-im

ages.githubusercontent.com/32930819/32498994-1a70dbde-c386-11e7-995e-552dfd0f4fa3.jpg)

**Comment by igrr** [comment]
This issue was moved to igrr/esp32-cam-demo#51
