### ISSUE TITLE
[TW#16426] Documentations lacks examples on how to read Hall sensor from ULP co-processor

### ISSUE THREAD

**Issue by baybal** [espressif/esp-idf#1241]
As I understand, before doing readings from pin 0 and 3, you have to set up Hall configuration registers in a certain way. Current register spec does not explain that in detail.

**Comment by igrr** [comment]
Good point about adding such an example, we'll add it along with ULP I2C example.

In the meantime, I think TRM does have the information you are looking for: 

- Pins should be initialized same was as for ADC (see ulp_adc example),
- Hall sensor power on and phase should be controlled by ULP (`SENS_HALL_PHASE_FORCE=0`, `SENS_XPD_HALL_FORCE=0`),
- ADC should be controlled by ULP (`adc1_ulp_enable()`, same as in ulp_adc example). 
- After that you should be able to use ADC instruction of the ULP. Per TRM, Sel=0 (for ADC1), Sar_Mux = 9 returns the result for phase 1, Sar_Mux = 10 returns the result for phase 0.

**Comment by TemcoHeng** [comment]
I make an example here: https://github.com/espressif/esp-iot-solution/tree/master/examples/ulp_examples/ulp_hall_sensor , FYI.

**Comment by bvernoux** [comment]
Does it is possible to have such type of example (especially the Readme.md) in English and not Japanese/Chinese ... ?

**Comment by TemcoHeng** [comment]
@bvernoux  English version doc will be updated soon.

**Comment by TemcoHeng** [comment]
https://github.com/espressif/esp-iot-solution/blob/master/examples/ulp_examples/ulp_hall_sensor/readme_en.md, update english doc.

**Comment by jack0c** [comment]
@FayeY Try to close this issue.
