### ISSUE TITLE
MQTT broker cannot connect (IDFGH-11249)

### ISSUE THREAD

**Issue by SFNFIH** [espressif/esp-idf#12410]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

My ESP-IDF version is v5.1.1-dirty
I used the mqtt case program in examples, but when connecting to the mqtt broker I built, I was prompted with this paragraph:
```
E (4047) mqtt_client: No scheme found
E (4047) mqtt_client: Failed to create transport list
```
Below is my configuration code.
```
static void mqtt_app_start(void)
{
     esp_mqtt_client_config_t mqtt_cfg = {
         .broker.address.hostname = "mqtt://192.168.239.20:1883",
     };
     esp_mqtt_client_handle_t client = esp_mqtt_client_init(&mqtt_cfg);
     /* The last argument may be used to pass data to the event handler, in this example mqtt_event_handler */
     esp_mqtt_client_register_event(client, ESP_EVENT_ANY_ID, mqtt_event_handler, NULL);
     esp_mqtt_client_start(client);
}
```

**Comment by nopnop2002** [comment]
```
     esp_mqtt_client_config_t mqtt_cfg = {
         .broker.address.uri = "mqtt://192.168.239.20",
        .broker.address.port = 1883
     };
```

**Comment by SFNFIH** [comment]
Thank you for your suggestion,i already tried，But still can't connect. @nopnop2002

**Comment by nopnop2002** [comment]
Is your MQTT broker valid?

$ mosquitto_pub -h 192.168.239.20 -p 1883 -t "/test/test" -m "test"

**Comment by SFNFIH** [comment]
I have tested it with mqttx and can connect to the broker.

**Comment by nopnop2002** [comment]
In mosquitto V1.7 and later, allow_anonymous is set to false by default, and external connections are rejected.

**Comment by SFNFIH** [comment]
My MQTT agent is built with EMQX. I didn't configure its connection strategy, and I didn't even set a user name and password.[This is its official website.](https://www.emqx.io/)

**Comment by nopnop2002** [comment]
EMQX mqtt broker allows external connections by default.

There may be a problem with your Proxy

**Comment by SFNFIH** [comment]
But I can connect to the mqtt agent with any mqtt test software on my computer or mobile phone.

**Comment by nopnop2002** [comment]
Can you connect to "mqtt://broker.emqx.io" ?

**Comment by SFNFIH** [comment]
Any proxy that is not in the form of IP can be connected, and a single proxy in the form of IP cannot be connected.

**Comment by nopnop2002** [comment]
Can you connec here.
mqtt://54.244.173.190

**Comment by SFNFIH** [comment]
no，Still can't connect

**Comment by nopnop2002** [comment]
It is your network problem.

Becase broker.emqx.io is 54.244.173.190.

```
ping broker.emqx.io
PING emqx.public-broker.com (54.244.173.190) 56(84) bytes of data.
```

**Comment by SFNFIH** [comment]
I don’t know the reason, but my mqtt broker is built locally, and the connection is also a LAN connection. I tried to connect to mqtt://broker.emqx.io, but the connection was successful.

**Comment by nopnop2002** [comment]
Connect to mqtt://broker.emqx.io ---> Success
Connect to mqtt://54.244.173.190 ---> Fail

I don't know why, but your WiFi router can't connect to the server by IP address.

**Comment by SFNFIH** [comment]
I use the hotspot on my mobile phone to access the Internet，I don't know if it's a problem with the phone

**Comment by nopnop2002** [comment]
Maybe your hotspot doesn't support connections using IP addresses.

**Comment by SFNFIH** [comment]
Why can I connect to the agent with another computer or mobile phone on the same network?

**Comment by SFNFIH** [comment]
Have you tried to connect the proxy with IP?

**Comment by nopnop2002** [comment]
>Why can I connect to the agent with another computer or mobile phone on the same network?

This place is inappropriate for your question.
This place is for ESP-IDF issues.

>Have you tried to connect the proxy with IP?

No.

**Comment by SFNFIH** [comment]
Yes, the computer and mobile phone can be connected normally.

**Comment by SFNFIH** [comment]
```
I (6057) esp_netif_handlers: sta ip: 192.168.38.31, mask: 255.255.255.0, gw: 192.168.38.222
I (6057) MQTT_EXAMPLE: got ip:192.168.38.31
I (6057) WIFI: WIFI连接成功! 马上启动MQTT连接！
```
this is my record.

**Comment by nopnop2002** [comment]
>I (6057) esp_netif_handlers: sta ip: 192.168.38.31, mask: 255.255.255.0, gw: 192.168.38.222

Since the mqtt server (192.168.239.20) is different from Segumen, it is not possible to connect to the mqtt server.

**Comment by SFNFIH** [comment]
So how should I solve this problem? Does ESP-IDF have an API for setting IP?

**Comment by nopnop2002** [comment]
You can't change network segments.

**Comment by SFNFIH** [comment]
Why is the connected hotspot the same, but it is assigned different network segments? This is strange!

**Comment by nopnop2002** [comment]
I don’ｔ know.
