### ISSUE TITLE
build issues amazon_aia on ESP32-LyraTD-SYNA (IDFGH-11270)

### ISSUE THREAD

**Issue by seancmalloy** [espressif/esp-idf#12428]
.espressif/python_env/idf4.2_py3.11_env/lib/python3.11/site-packages/cryptography/hazmat/bindings/_openssl.abi3.so: undefined symbol: FIPS_mode

my build is failing at Generating x509_crt_bundle.  anyone know how to fix this?

rpi3 deb bookworm python3.11 OpenSSL 3.0.11

update -

i compiled openssl with fips module only to discover ossl 3 no longer supports fips_mode. 

update - nuclear option

i downgraded to deb 11 openssl1.0.2 fips 2 mod  pyhton3.9 - and was able to build & flash but using ESP32-LyraTD example which looks like doesnt work with ESP32-LyraTD-SYNA

**Comment by dobairoland** [comment]
I'm sorry but ESP-IDF v4.2 is not supported anymore. I would guess that a relatively very new version of operating system combined with a very old ESP-IDF is causing the problem. The cryptography package is probably linked to older openssl library. You might be able to work around the issue by installing an older openssl library.

Also please consider to upgrade to the latest bugfix release of v4.4. It should contain no breaking changes in comparison with v4.2.

**Comment by Alvin1Zhang** [comment]
This has been tracked in https://github.com/espressif/esp-va-sdk/issues/189, let us follow up there, closing this one, thanks for reporting.
