### ISSUE TITLE
Provision succeed, but seems not saved, require provision again after reboot (IDFGH-11266)

### ISSUE THREAD

**Issue by zzzh** [espressif/esp-idf#12423]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Hi,

I'm using esp32c3, with esp-idf v4.4.2 in ubuntu 20.04.

I'm trying to do wifi provision by a http server, it works well(pass the provision process then works in station mode correctly), but when I reboot the board, it can't find provision info by app_prov_is_provisioned() and require to do provision again.
So seem it can't save the provision info to nvs, which I thought should be done by esp_wifi_set_config(), which had been run successfully in the process of bring station mode up.

I don't want to add custom nvs field for this.

Any ideas?

**Comment by lhr-tom** [comment]
Excuse me , how do you fix it at last,  could you share me please?
