### ISSUE TITLE
Rotary Encoder Example - Broken Link (IDFGH-11286)

### ISSUE THREAD

**Issue by KevScott** [espressif/esp-idf#12442]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

There is a link at https://github.com/espressif/esp-idf/tree/8fc8f3f4799/examples/peripherals/pcnt/rotary_encoder#rotary-encoder-example which is called EC11 and points to an alpsalpine.com page. That link doesnt work. 

I suggest that https://tech.alpsalpine.com/e/products/category/encorder/sub/01/series/ec11e/ should be the replacement.

**Comment by suda-morris** [comment]
Thanks for the suggestion, we will update the link ASAP.
