### ISSUE TITLE
[TW#16429] s_microseconds_offset' undeclared

### ISSUE THREAD

**Issue by ESP32DE** [espressif/esp-idf#1245]
hi
with latest esp-idf i get an undeclared

> .....
> CC build/newlib/reent_init.o
> CC build/newlib/time.o
> C:/msys32/home/sysop/esp-idf/components/newlib/time.c: In function 'get_time_since_boot':
> C:/msys32/home/sysop/esp-idf/components/newlib/time.c:174:20: error: 's_microseconds_offset' undeclared (first use in this function)
>      microseconds = s_microseconds_offset + esp_timer_get_time();
>                     ^
> C:/msys32/home/sysop/esp-idf/components/newlib/time.c:174:20: note: each undeclared identifier is reported only once for each function it appears in
> make[1]: *** [/home/sysop/esp-idf/make/component_wrapper.mk:243: time.o] Fehler 1
> make: *** [C:/msys32/home/sysop/esp-idf/make/project.mk:435: component-newlib-build] Fehler 2
> 

txs
best wishes 
rudi ;-)

**Comment by igrr** [comment]
Hi Rudi, thanks for reporting this bug. We will have a fix for this soon, in the meantime you can set ESP32_TIME_SYSCALL option to FRC1 + RTC.
http://esp-idf.readthedocs.io/en/latest/api-reference/kconfig.html#esp32-time-syscall
