### ISSUE TITLE
"wifi:m f null" issue occurs when the device is running (IDFGH-11340)

### ISSUE THREAD

**Issue by Focalcrest-Madi** [espressif/esp-idf#12488]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

After my ESP32C3 device was running for a period of time, a "wifi:m f null" problem occurred and the WiFi could not connect to the router. After restarting the device, it returned to normal.
My device is using IDF version v4.4.2
Attached is the device log information file.
[ESP-wifi-fail.log](https://github.com/espressif/esp-idf/files/13211842/ESP-wifi-fail.log)

**Comment by AxelLin** [comment]
https://github.com/espressif/esp-idf/issues/11615#issuecomment-1822030053

**Comment by hansw123** [comment]
feel free to reopen @Focalcrest-Madi
