### ISSUE TITLE
[TW#16433] Precise time of data package sending

### ISSUE THREAD

**Issue by liulingliuf** [espressif/esp-idf#1251]
hi,
Recently, I handle a project using ESP32. I desire to get the precise time that a data package sent by WIFI.
How should I get this?
thanks

**Comment by liuzfesp** [comment]
Hi @liulingliuf currently we have no API for this, maybe we can support it in IDF release 3.1.

**Comment by jack0c** [comment]
@liulingliuf Do you mean the packets send by ESP32? If LWIP provides the packets, we need to see where to store the time. Also,the time will not be 100% accurate.

**Comment by liuzfesp** [comment]
@@liulingliuf I'm now considering to support this feature in IDFv3.1, need you help to provide more detailed requirements about this feature. Do you want to get the send time for each packet that sent by LWIP or by esp_wifi_80211_tx?

**Comment by FayeY** [comment]
Closing due to lack of response, please feel free to reopen if this is still an issue and you can supply more details.
Thanks.
