### ISSUE TITLE
Porting arduino wifi library to esp-idf (IDFGH-11390)

### ISSUE THREAD

**Issue by Abhay-2412** [espressif/esp-idf#12529]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Hello

I'm diving into a fun new project but hit a bit of a roadblock. I've successfully migrated my Arduino-based project into ESP-IDF, and things were going smoothly until I encountered some challenges with the Wi-Fi functionalities. I'm missing those familiar` client.connect()` and `client.write()` APIs, and it's got me scratching my head.

I thought of porting just the Wi-Fi library over to ESP-IDF, but alas, I ran into an error. Now, I'm in need of some expert guidance to unravel this mystery. I know it might sound like a newbie question, but we all start somewhere, right?

I would greatly appreciate any assistance you can provide. Let's turn this challenge into an exciting learning experience!

**Comment by igrr** [comment]
> I thought of porting just the Wi-Fi library over to ESP-IDF, but alas, I ran into an error.

This is unfortunately not that simple: the Wi-Fi library in arduino-esp32 project has numerous dependencies on other parts of the Arduino core. It is not easy to "extract" it out of Arduino while keeping the same API. Of course, you can look at the library source code and gradually convert it to remove Arduino dependencies. For example, replace the String class with std::string, replace Stream and other interfaces with some alternatives.

> I would greatly appreciate any assistance you can provide. Let's turn this challenge into an exciting learning experience!

This issue tracker is intended for bug reports and feature requests for ESP-IDF project. I am sorry, but IDF developers don't have bandwidth to help with very general "how do I..." type of coding questions. Guiding you in the process of implementing this idea would likely take someone on the team a fair bit of time — the time which could be better spent addressing more concrete issues reported here.

(FWIW, i've asked ChatGPT if it can convert [WiFiClientBasic.ino](https://github.com/espressif/arduino-esp32/blob/master/libraries/WiFi/examples/WiFiClientBasic/WiFiClientBasic.ino) into ESP-IDF code, and the result it gave was pretty good. This doesn't totally replace learning on your own, but is an option to consider if you are not sure how to start.)
