### ISSUE TITLE
Error -150 while using Sample code provided in MBED tls documentation (IDFGH-11396)

### ISSUE THREAD

**Issue by RuchaVs** [espressif/esp-idf#12534]
I want to perform AES 256 Encryption decryption using algorithm PSA_ALG_CBC_PKCS7.For which i am using sample  code provided in MBED tls documentation as a guideline (https://mbed-tls.readthedocs.io/en/latest/getting_started/psa/#what-is-platform-security-architecture-psa).

My string to be encrypted is :hello i am gamma,welcome . My string is greater than 16 bytes so before passing it to encryption i am breaking it into chunks of 16 byte.output of the encryption function is passed to decryption function. But i am getting  error ( failed to finish operation ,error code(-150)) after hitting function psa_cipher_finish() in Decryption mode.

I wish to get clarity whether i need to pad my input string before passing it to encryption and de-pad it before passing it to decryption or the IDE does this padding/de-padding on its own, when we specify the algorithm as PSA_ALG_CBC_PKCS7 in Encryption-Decryption initialisations .

**Comment by Harshal5** [comment]
Hello @RuchaVs,

This seems to be a question specifically related to the usage of mbedTLS's PSA crypto APIs so probably you could prefer opening an issue in the mbedtls' [repo](https://github.com/Mbed-TLS/mbedtls/issues) or forum.

Regarding the API usage, I think you could refer to the `mbedtls/programs/psa/crypto_examples.c`, that contains [examples](https://github.com/Mbed-TLS/mbedtls/blob/development/programs/psa/crypto_examples.c#L300) for AES CBC encryption for lengths not being multiples of 16.

Moreover, apart from chunking as done [here](https://github.com/Mbed-TLS/mbedtls/blob/development/programs/psa/crypto_examples.c#L61-L73), I don't think you would need to pad the input when specifying the algo `PSA_ALG_CBC_PKCS7`  as padding seems to be handled by mbedtls itself internally [here](https://github.com/Mbed-TLS/mbedtls/blob/development/library/cipher.c#L817-L826).
