### ISSUE TITLE
Failed to resolve component 'mdns' (IDFGH-11408)

### ISSUE THREAD

**Issue by stellna** [espressif/esp-idf#12546]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v.5.1.1

### Operating System used.

Windows

### How did you build your project?

Command line with CMake

### If you are using Windows, please specify command line type.

CMD

### What is the expected behavior?

I expected it to build the code and flash it onto my esp-32 ovo2640 camera.

### What is the actual behavior?

I want to build this code but instead it just keep showing the Error.

The following Error it show is as follow.
CMake Error at C:/Users/whgPd/esp/esp-idf/tools/cmake/build.cmake:266 (message):
  Failed to resolve component 'mdns'.
  

### Steps to reproduce.

1. Download Esp-who-master code and only take example/motion_detection -> use this as a main code and delete all of other example code.
   This is where I download the code : https://github.com/espressif/esp-who/blob/master/README.md 
2. Download Esp-DL and copy/paste of the component to the esp-who-master/components/esp-dl
    This is where I download the code : https://github.com/espressif/esp-dl
3. Download Esp-camera and copy/paste whole folder to esp-who-master/components/esp-camera 
    This is where I download the code : https://github.com/espressif/esp32-camera 
4. Set right including path and Build the code. And there is a following error.

### Build or installation Logs.

```plain
-- Found Git: C:/Users/whgPd/.espressif/tools/idf-git/2.39.2/cmd/git.exe (found version "2.39.2.windows.1") 
-- Component directory C:/Users/whgPd/esp/esp-idf/components/esp32-csi-tool does not contain a CMakeLists.txt 
file. No component will be added
-- Component directory C:/Users/whgPd/OneDrive/Desktop/esp-test/esp-who-master-2/components/esp-sr does not contain a CMakeLists.txt file. No component will be added
-- The C compiler identification is GNU 12.2.0
-- The CXX compiler identification is GNU 12.2.0
-- The ASM compiler identification is GNU
-- Found assembler: C:/Users/whgPd/.espressif/tools/xtensa-esp32-elf/esp-12.2.0_20230208/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc.exe
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Users/whgPd/.espressif/tools/xtensa-esp32-elf/esp-12.2.0_20230208/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Users/whgPd/.espressif/tools/xtensa-esp32-elf/esp-12.2.0_20230208/xtensa-esp32-elf/bin/xtensa-esp32-elf-g++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- git rev-parse returned 'fatal: not a git repository (or any of the parent directories): .git'
-- Could not use 'git describe' to determine PROJECT_VER.
-- Building ESP-IDF components for target esp32
Processing 1 dependencies:
[1/1] idf (5.1.1)
CMake Error at C:/Users/whgPd/esp/esp-idf/tools/cmake/build.cmake:266 (message):
  Failed to resolve component 'mdns'.
Call Stack (most recent call first):
  C:/Users/whgPd/esp/esp-idf/tools/cmake/build.cmake:302 (__build_resolve_and_add_req)
  C:/Users/whgPd/esp/esp-idf/tools/cmake/build.cmake:595 (__build_expand_requirements)
  C:/Users/whgPd/esp/esp-idf/tools/cmake/project.cmake:547 (idf_build_process)
  CMakeLists.txt:8 (project)


-- Configuring incomplete, errors occurred!
See also "C:/Users/whgPd/OneDrive/Desktop/esp-test/esp-who-master-2/build/CMakeFiles/CMakeOutput.log".        

 *  The terminal process "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -Command cmake -G Ninja -DPYTHON_DEPS_CHECKED=1 -DESP_PLATFORM=1 -B c:\Users\whgPd\OneDrive\Desktop\esp-test\esp-who-master-2\build -S c:\Users\whgPd\OneDrive\Desktop\esp-test\esp-who-master-2" terminated with exit code: 1.
```

### More Information.

https://github.com/espressif/arduino-esp32/issues/8740

I have look at this page but it seems that don't related to mine since I used ESP-idf Instead of arduino. I have checked all of the Cmakelist to find is it including mdns but I was unable to find anything related to it.

**Comment by igrr** [comment]
According to ESP-WHO docs, the master branch of that project is only compatible with IDF release/v4.4 branch. It hasn't been upgraded to IDF v5.x.
Please see https://github.com/espressif/esp-who/issues/240 for the possible workaround.

(The error message generally means that the component hasn't been found. `mdns` component  [has been removed](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/migration-guides/release-5.x/5.0/removed-components.html) from IDF in v5.0 release, and should now be installed via the component manager. I think in ESP-WHO, the developers have simply [copied the `mdns` component into the project tree](https://github.com/espressif/esp-who/tree/idfv5.0/components/mdns) instead of adding the dependency.)
