### ISSUE TITLE
espnow example: task watchdog crashing. no usual abort statement. (IDFGH-11402)

### ISSUE THREAD

**Issue by moefear85** [espressif/esp-idf#12540]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

b4268c8

### Espressif SoC revision.

esp32s2

### Operating System used.

Linux

### How did you build your project?

Command line with idf.py

### If you are using Windows, please specify command line type.

None

### Development Kit.

wroom s2 module

### Power Supply used.

External 3.3V

### What is the expected behavior?

Usually the task watchdog would notify that some task exceeded its limits, then call abort if the relevant sdkconfig entry is set.

### What is the actual behavior?

I chose this option, but it looks more like the watchdog is crashing. There is no abort statement. When I turn the watchdog off completely, the example runs fine.

It isn't even clear to me why the watchdog is getting triggered. The function isn't doing heavy processing, and is calling vTaskDelay for long periods of time (5 seconds). This isn't supposed to trigger the watchdog is it?

[sdkconfig.problematic.txt](https://github.com/espressif/esp-idf/files/13285004/sdkconfig.problematic.txt)
[sdkconfig.safe.txt](https://github.com/espressif/esp-idf/files/13285005/sdkconfig.safe.txt)
![Screenshot_20231107_194926](https://github.com/espressif/esp-idf/assets/39313692/37490c5c-e83a-4376-a282-cfb2acd27f71)
![Screenshot_20231107_195420](https://github.com/espressif/esp-idf/assets/39313692/ccdf0bf7-ba7e-4b52-ad2b-4d89c49bfa35)

### Steps to reproduce.

Just compile the espnow example using the provided sdkconfig

**Comment by moefear85** [comment]
I forgot about the chip and left it running. When I came back, it panicked, even though I did not modify the example in any way, and was using `sdkconfig.safe`, ie without task watchdogs at all:

```
I (694337) espnow_example: send data to ff:ff:ff:ff:ff:ff
I (695340) espnow_example: send data to ff:ff:ff:ff:ff:ff
I (696341) espnow_example: send data to ff:ff:ff:ff:ff:ff
I (697342) espnow_example: send data to ff:ff:ff:ff:ff:ff
I (698343) espnow_example: send data to ff:ff:ff:ff:ff:ff
I (699344) espnow_example: send data to ff:ff:ff:ff:ff:ff
I (700345) espnow_example: send data to ff:ff:ff:ff:ff:ff
I (701346) espnow_example: send data to ff:ff:ff:ff:ff:ff
I (702347) espnow_example: send data to ff:ff:ff:ff:ff:ff
I (703348) espnow_example: send data to ff:ff:ff:ff:ff:ff
I (704351) espnow_example: send data to ff:ff:ff:ff:ff:ff
I (705352) espnow_example: send data to ff:ff:ff:ff:ff:ff
I (706353) espnow_example: send data to ff:ff:ff:ff:ff:ff
I (707354) espnow_example: send data to ff:ff:ff:ff:ff:ff
Guru Meditation Error: Core  0 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x4003387c: 21004136 4228fb1d 2232c2bc
0x4003387c: sta_reset_beacon_timeout at ??:?

Core  0 register dump:
PC      : 0x40033880  PS      : 0x00060430  A0      : 0x800b7477  A1      : 0x3ffd5dd0  
0x40033880: sta_reset_beacon_timeout at ??:?

A2      : 0xffffffff  A3      : 0x3ffd5e20  A4      : 0x000003e8  A5      : 0x3f0120ec  
A6      : 0x000ac5db  A7      : 0x400beccc  A8      : 0x800c6bee  A9      : 0x3ffd5d90  
0x400beccc: lwip_cyclic_timer at /media/EXT4/source/esp-idf_master_25.10.23/components/lwip/lwip/src/core/timeouts.c:237

A10     : 0x00000000  A11     : 0x3ffd5e20  A12     : 0x000003e8  A13     : 0x00000000  
A14     : 0x00000001  A15     : 0x3ffd4ff4  SAR     : 0x0000000e  EXCCAUSE: 0x00000000  
EXCVADDR: 0x00000000  LBEG    : 0x000003e8  LEND    : 0x00000000  LCOUNT  : 0x4002692c  
0x4002692c: _xt_handle_exc at /media/EXT4/source/esp-idf_master_25.10.23/components/xtensa/xtensa_vectors.S:739



Backtrace: 0x4003387d:0x3ffd5dd0 0x400b7474:0x3ffd5e00 0x400b7536:0x3ffd5e20 0x4002ecbd:0x3ffd5e50
0x4003387d: sta_reset_beacon_timeout at ??:?

0x400b7474: tcpip_timeouts_mbox_fetch at /media/EXT4/source/esp-idf_master_25.10.23/components/lwip/lwip/src/api/tcpip.c:104

0x400b7536: tcpip_thread at /media/EXT4/source/esp-idf_master_25.10.23/components/lwip/lwip/src/api/tcpip.c:142

0x4002ecbd: vPortTaskWrapper at /media/EXT4/source/esp-idf_master_25.10.23/components/freertos/FreeRTOS-Kernel/portable/xtensa/port.c:137
```

**Comment by zhangyanjiaoesp** [comment]
@moefear85 Do you still have this issue?

**Comment by moefear85** [comment]
i haven't worked on this project in a while, so I can't say.
