### ISSUE TITLE
[TW#16434] [feature request]: Get the current connected WiFi protocol (b/g/n)

### ISSUE THREAD

**Issue by farizadp** [espressif/esp-idf#1254]
Hello,

Is it possible to add functions to get the current associated WiFi protocol (b/g/n)? for both AP and ST mode?
I looked at the wifi stack debug messages that it prints out the WiFi protocol, but could not find this in the source code.

I (25462) wifi: n:1 0, o:1 0, ap:1 1, sta:0 0, prof:1
I (25462) wifi: station: 84:3a:4b:08:2c:d8 join, AID=1, **n,** 20
I (50202) wifi: station: 84:3a:4b:08:2c:d8 leave, AID = 1
I (50202) wifi: n:1 0, o:1 0, ap:1 1, sta:0 0, prof:1
I (116442) wifi: n:1 0, o:1 0, ap:1 1, sta:0 0, prof:1
I (116442) wifi: station: 84:3a:4b:08:2c:d8 join, AID=1, **b,** 20
I (138902) wifi: station: 84:3a:4b:08:2c:d8 leave, AID = 1
I (138902) wifi: n:1 0, o:1 0, ap:1 1, sta:0 0, prof:1

Regards,
Dion

**Comment by farizadp** [comment]
@FayeY , just out of my curiosity. You added the TW hashtag in the title. What does the TW# stands for?

**Comment by FayeY** [comment]
Hi, it is an issue ID in our internal issue tracking system.

**Comment by zhangyanjiaoesp** [comment]
@farizadp  We will add this feature as soon as possible.

**Comment by farizadp** [comment]
@zhangyanjiaoesp Thanks !! Do you know an ETA for this?

**Comment by zyj1993** [comment]
may be 1~2 months

**Comment by zhangyanjiaoesp** [comment]
may be 1~2 months

**Comment by farizadp** [comment]
Hello,

Is there anyone who can give any update on this feature request?

Thanks
Dion

**Comment by zhangyanjiaoesp** [comment]
@farizadp I'm sorry we have so many things to do, so this feature was delayed. We will finish this in on week.

**Comment by farizadp** [comment]
Hello.

Any update regarding this ?

Thanks,
Dion

**Comment by zhangyanjiaoesp** [comment]
@farizadp the code has been finished, but we have something else to be merged together, so it still need some time.

**Comment by FayeY** [comment]
Has merged. Please have a try with the latest IDF.
