### ISSUE TITLE
[solved] gatts_add_char_descr_evt_param struct changes required

### ISSUE THREAD

**Issue by chegewara** [espressif/esp-idf#1258]
With normal situation, one characteristic with distinctive UUID per service, this structure works fine:
https://github.com/espressif/esp-idf/blob/master/components/bt/bluedroid/api/include/esp_gatts_api.h#L161-L166

But when we have 2 or more characteristics with the same UUID in the same service, like here >> https://github.com/nkolban/esp32-snippets/issues/175, then we have a problem. Could we change this structure to identify characteristics by handle?

```
struct gatts_add_char_descr_evt_param {
        esp_gatt_status_t status;       /*!< Operation status */
        uint16_t attr_handle;           /*!< Descriptor attribute handle */
        uint16_t service_handle;        /*!< Service attribute handle */
        esp_bt_uuid_t char_handle;        /*!< Characteristic handle*/  <--- change
        esp_bt_uuid_t char_uuid;        /*!< Characteristic uuid */         <--- left for backward compatibility
    } add_char_descr;                   /*!< Gatt server callback param of ESP_GATTS_ADD_CHAR_DESCR_EVT */

```

**Comment by ManniAT** [comment]
I just found this issue in expressif https://github.com/espressif/esp-idf/issues/1079 which faces the same situation (multiple UUIDs).
