### ISSUE TITLE
pwm does not have 100% output. (IDFGH-11462)

### ISSUE THREAD

**Issue by LHYYSY** [espressif/esp-idf#12593]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

![OE)AVYYS)6Z48FJ6LCJ09~X](https://github.com/espressif/esp-idf/assets/112528246/cdb0f2c0-992a-4cfe-8413-a2e699343c3e)
![image](https://github.com/espressif/esp-idf/assets/112528246/582758d7-5657-4639-be0e-33f4258a71f8)
running the ledc_basic routine without 100% output, where am I not configured well?

**Comment by songruo** [comment]
Hi @LHYYSY, this has been fixed on master (821f7b04988d0721ff7dbb64af43d165e3124718). We will backport to the release branches soon.
