### ISSUE TITLE
Strip build path from log error messages?

### ISSUE THREAD

**Issue by jmattsson** [espressif/esp-idf#126]
`E (4738) GPIO: /home/johny/src/nodemcu-firmware/sdk/esp32-esp-idf/components/driver/./gpio.c:361 (gpio_wakeup_enable):GPIO number error`

I'd rather not have a bunch of largely irrelevant path information embedded into my precious flash. Any chance of tweaking the build to only include the relevant parts? E.g. via `vpath` directives, or perhaps `__BASE_FILE__` (maybe with suitable `-D` override for it)?

Currently there are "only" 22 copies of `/home/johny/src/nodemcu-firmware/sdk/esp32-esp-idf/components`  (~1.3k) in the resulting flash image, but I know you guys are moving more things over to use the logging framework...

Personally I'd be happy with just the `(gpio_wakeup_enable)` part; it's only a `grep` away from there.

**Comment by jmattsson** [comment]
Thanks!

**Comment by negativekelvin** [comment]
https://github.com/espressif/esp-idf/blob/576052e5c28eb462cb5f5dd39b40dfcc7a8dc92d/components/driver/rtc_module.c#L30

https://github.com/espressif/esp-idf/blob/cca883490e3d7142457309d54ab3d692cf5c2d0d/components/driver/sigmadelta.c#L24
