### ISSUE TITLE
ESP32-S3 SPI mode 1 & 2 does not work properly.  (IDFGH-11474)

### ISSUE THREAD

**Issue by seulater** [espressif/esp-idf#12602]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

I am using release v5.1.1

I am reading data from a ADS7822 A/D converter via SPI. 
When I use mode 0, I am receiving data, But technically it should be mode 1. I discovered that if I use mode 1 or 2 I get nothing back from the converter. Only modes 1 & 3 do.  

Here is the code, and below are the scope screen shots for mode 0,1,2,3. 

```
#include <stdio.h>
#include <inttypes.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "driver/gpio.h"
#include "driver/spi_master.h"
#include "esp_system.h"

#define ADS7822_CLK GPIO_NUM_3
#define ADS7822_MISO GPIO_NUM_2
#define ADS7822_CS GPIO_NUM_1


void app_main(void)
{
	esp_err_t ret;

	// SPI device handle
	spi_device_handle_t spi;

	// Configuration for the SPI bus
	spi_bus_config_t buscfg = {
		.miso_io_num = ADS7822_MISO,
		.mosi_io_num = -1, // MOSI not used
		.sclk_io_num = ADS7822_CLK,
		.quadwp_io_num = -1,
		.quadhd_io_num = -1,
		.max_transfer_sz = 0};

	// Configuration for the SPI device on the bus
	spi_device_interface_config_t devcfg = {
		.clock_speed_hz = 4 * 1000 * 1000, // Clock out at 1 MHz
		.mode = 3,						   // SPI mode 1
		.spics_io_num = ADS7822_CS,		   // CS pin
		.queue_size = 7};

	// Initialize the SPI bus
	ret = spi_bus_initialize(SPI3_HOST, &buscfg, SPI_DMA_CH_AUTO);
	assert(ret == ESP_OK);

	// Attach the ADS7822 to the SPI bus
	ret = spi_bus_add_device(SPI3_HOST, &devcfg, &spi);
	assert(ret == ESP_OK);

	// Buffer for reading data
	uint8_t data[2];
	spi_transaction_t t = {
		.length = 16, // ADS7822 sends 12-bit data, but SPI transactions are 8-bit aligned
		.rx_buffer = data};

	while (1)
	{
		// Transaction for receiving data

		// Perform the SPI transaction
		ret = spi_device_transmit(spi, &t);
		assert(ret == ESP_OK);

		// Convert received data to 12-bit value
		uint16_t adc_value = (((data[0] & 0x1F) << 8) | data[1]) >> 1;

		printf("ADS7822 Value: %d\n", adc_value);

		// Delay before the next read
		vTaskDelay(250 / portTICK_PERIOD_MS);
	}
}
```

![mode0](https://github.com/espressif/esp-idf/assets/79600499/435edb8a-f156-4096-b794-4e74141cafac)
![mode1](https://github.com/espressif/esp-idf/assets/79600499/04a6a1c4-2971-4e0c-b3f8-c7def268c0f1)
![mode2](https://github.com/espressif/esp-idf/assets/79600499/80cd3b40-bd6f-46e6-a9a1-6530db7cf67c)
![mode3](https://github.com/espressif/esp-idf/assets/79600499/04b1b94e-9643-4356-a3bd-2b185ba0f482)

**Comment by wanckl** [comment]
@seulater en, Hello, I think:    

Let we just attention on your graph, the 1st and 4th there are data on SPI bus, whoever we can see that both them, MISO line are changed on dec-edge/low-level of clock, and can be sampled on rise-edge/high-level.      

I think you confirm `mode 1` from ADS7822 datasheet, but from figure it not fit `mode 1`, there can some possibilities:   
- ADS7822 designed as mode 1, but as a slave device, it may have some delay on data-out(MISO) pin, cause timing different, you can slowdown clock freq to check it.       
- Your clock happens very quickly after CS active, devices may can't react immediately, or they may have some check on bus level when it is selected, maybe it is why figure 2 and 3 don't have any data. You can increase `spi_device_interface_config_t::cs_ena_pretrans` then try again.    

Waiting for your update, good luck!
