### ISSUE TITLE
How to fix Organic maps CMake android studio Error? (IDFGH-11473)

### ISSUE THREAD

**Issue by LaachirDeeper** [espressif/esp-idf#12601]
**The issue message as below:**

[CXX1429] error when building with cmake using C:\Users\Adm\Downloads\organicmaps-master\CMakeLists.txt: -- The C compiler identification is Clang 17.0.2
-- The CXX compiler identification is Clang 17.0.2
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Users/Adm/AppData/Local/Android/Sdk/tools/ndk/26.1.10909125/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Users/Adm/AppData/Local/Android/Sdk/tools/ndk/26.1.10909125/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using compiler Clang 17.0.2
-- Using Unity Build with batch 50, export UNITY_DISABLE=1 or use -DUNITY_DISABLE=ON to disable it.
-- export COLORS_DISABLE=1 or use -DCOLORS_DISABLE=ON to disable colored compiler output.
-- Build type: Debug
-- Using ld.ldd linker
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- SKIP_TESTS: Skipping subdirectory bsdiff/bsdiff_tests
-- SKIP_TESTS: Skipping subdirectory opening_hours_tests
-- SKIP_TESTS: Skipping subdirectory opening_hours_integration_tests
-- SKIP_TESTS: Skipping subdirectory opening_hours_supported_features_tests
-- Could NOT find Python3 (missing: Python3_EXECUTABLE Interpreter) 
-- Configuring incomplete, errors occurred!
See also "C:/Users/Adm/Downloads/organicmaps-master/android/app/nativeOutputs/Debug/2j68h3u2/arm64-v8a/CMakeFiles/CMakeOutput.log".
See also "C:/Users/Adm/Downloads/organicmaps-master/android/app/nativeOutputs/Debug/2j68h3u2/arm64-v8a/CMakeFiles/CMakeError.log".

C++ build system [configure] failed while executing:
    @echo off
    "C:\\Users\\Adm\\AppData\\Local\\Android\\Sdk\\tools\\cmake\\3.22.1\\bin\\cmake.exe" ^
      "-HC:\\Users\\Adm\\Downloads\\organicmaps-master" ^
      "-DCMAKE_SYSTEM_NAME=Android" ^
      "-DCMAKE_EXPORT_COMPILE_COMMANDS=ON" ^
      "-DCMAKE_SYSTEM_VERSION=21" ^
      "-DANDROID_PLATFORM=android-21" ^
      "-DANDROID_ABI=arm64-v8a" ^
      "-DCMAKE_ANDROID_ARCH_ABI=arm64-v8a" ^
      "-DANDROID_NDK=C:\\Users\\Adm\\AppData\\Local\\Android\\Sdk\\tools\\ndk\\26.1.10909125" ^
      "-DCMAKE_ANDROID_NDK=C:\\Users\\Adm\\AppData\\Local\\Android\\Sdk\\tools\\ndk\\26.1.10909125" ^
      "-DCMAKE_TOOLCHAIN_FILE=C:\\Users\\Adm\\AppData\\Local\\Android\\Sdk\\tools\\ndk\\26.1.10909125\\build\\cmake\\android.toolchain.cmake" ^
      "-DCMAKE_MAKE_PROGRAM=C:\\Users\\Adm\\AppData\\Local\\Android\\Sdk\\tools\\cmake\\3.22.1\\bin\\ninja.exe" ^
      "-DCMAKE_C_FLAGS=-fno-function-sections -fno-data-sections -Wno-extern-c-compat" ^
      "-DCMAKE_CXX_FLAGS=-fexceptions -frtti" ^
      "-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\Adm\\Downloads\\organicmaps-master\\android\\app\\build\\intermediates\\cxx\\Debug\\2j68h3u2\\obj\\arm64-v8a" ^
      "-DCMAKE_RUNTIME_OUTPUT_DIRECTORY=C:\\Users\\Adm\\obj\\arm64-v8a" ^
      "-DCMAKE_BUILD_TYPE=Debug" ^
      "-BC:\\Users\\Adm\\Downloads\\organicmaps-master\\android\\app\\nativeOutputs\\Debug\\2j68h3u2\\arm64-v8a" ^
      -GNinja ^
      "-DANDROID_TOOLCHAIN=clang" ^
      "-DANDROID_STL=c++_static" ^
      "-DOS=windows 10" ^
      "-DSKIP_TESTS=ON" ^
      "-DUSE_PCH=OFF"
  from C:\Users\Adm\Downloads\organicmaps-master\android\app
Setting PLATFORM_ANDROID to true
CMake Error at 3party/CMakeLists.txt:17 (add_subdirectory):
  add_subdirectory given source "expat/expat" which is not an existing
  directory.

CMake Error at 3party/CMakeLists.txt:25 (add_subdirectory):
  The source directory

    C:/Users/Adm/Downloads/organicmaps-master/3party/jansson/jansson

  does not contain a CMakeLists.txt file.

CMake Error at 3party/CMakeLists.txt:26 (target_include_directories):
  Cannot specify include directories for target "jansson" which is not built
  by this project.

CMake Error at 3party/CMakeLists.txt:29 (add_subdirectory):
  The source directory

    C:/Users/Adm/Downloads/organicmaps-master/3party/gflags

  does not contain a CMakeLists.txt file.

CMake Error at 3party/CMakeLists.txt:30 (target_compile_options):
  Cannot specify compile options for target "gflags_nothreads_static" which
  is not built by this project.

CMake Error at 3party/freetype/CMakeLists.txt:4 (add_subdirectory):
  The source directory

    C:/Users/Adm/Downloads/organicmaps-master/3party/freetype/freetype

  does not contain a CMakeLists.txt file.

CMake Error at 3party/freetype/CMakeLists.txt:7 (target_compile_options):
  Cannot specify compile options for target "freetype" which is not built by
  this project.

CMake Error at 3party/freetype/CMakeLists.txt:10 (target_include_directories):
  Cannot specify include directories for target "freetype" which is not built
  by this project.

CMake Error at 3party/freetype/CMakeLists.txt:16 (add_library):
  add_library cannot create ALIAS target "Freetype::Freetype" because target
  "freetype" does not already exist.

CMake Error at CMakeLists.txt:309 (message):
  Could not find python3 to use in qt/, shaders/ and 3party/.

**Comment by igrr** [comment]
Please see https://github.com/organicmaps/organicmaps/issues/4724#issuecomment-1460542109 and https://github.com/organicmaps/organicmaps/issues/4724#issuecomment-1465034783, and for further help with that project please open issues in https://github.com/organicmaps/organicmaps/issues/.

**Comment by Yashbhosale00** [comment]
Hello LaachirDeeper, 
I'm encountering an issue while trying to build this project in Android Studio on my Linux system. Although all setups seem to be working correctly, I'm facing an error: "[CXX1429] error when building with CMake using /home/kalilinux/Desktop/organicmaps/CMakeLists.txt: -- The C compiler identification is Clang 17.0.2". Can you please guide me on how to fix this issue? I'd appreciate any assistance you can provide.

**Comment by Yashbhosale00** [comment]
If anyone is familiar with this issue, could you please provide guidance on how to resolve it? Any assistance would be greatly appreciated.
