### ISSUE TITLE
How can I save many pictures? (IDFGH-11506)

### ISSUE THREAD

**Issue by stellna** [espressif/esp-idf#12631]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Here is part of my camera code :
![image](https://github.com/espressif/esp-idf/assets/141707988/a1d0efcd-034b-45e1-9a7c-6b9237ed0215)

Here is part of my main code :
![image](https://github.com/espressif/esp-idf/assets/141707988/38b747e2-908e-4178-9282-e5ae1a0c6ea8)

The thing is that I want to increase the number of picture into my sd card. Such as pic_1, pic_2, pic_3, pic_4....
Instead, it just keep taking photo and replace it with pic_1.
<img width="960" alt="2 질문" src="https://github.com/espressif/esp-idf/assets/141707988/d0b694cc-031f-4570-bebe-7bc7971878eb">

And sometimes, it shows this problem too.
<img width="960" alt="1 질문" src="https://github.com/espressif/esp-idf/assets/141707988/96860a48-9715-41d4-a4a7-f56e96e48d69">

Any idea to resolve these 2 problem would be appreciate. Thank you!

Further more information
Using ESP-IDF : 5.1.1V
Using Cmake

For more precise code here is my github link : https://github.com/stellna/IOT-camera-learning
The code is mainly compile in the coprocessor folder.

**Comment by WangYuxin-esp** [comment]
@stellna Hi, For the use of SD cards, you can refer to [SD Card example (SDMMC)](https://github.com/espressif/esp-idf/tree/master/examples/storage/sd_card/sdmmc).
And if you want to take multiple pictures at once, please configure the number of `fb_count = pic_nums` when calling esp_camera_init(). Then use it just like:
```
size_t pic_nums = 3;
camera_fb_t *pics[pic_nums];
for(size_t i=0;i<fb_count;i++) {
pic[i] = esp_camera_fb_get();
}
// use pic1、pic2、pic3
...
for(size_t i=0;i<fb_count;i++) {
esp_camera_fb_return(pic[i]);
}
```

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to short of feedback, feel free to reopen with more updates.
