### ISSUE TITLE
ESP32C3: DR_REG_I2S_BASE should be DR_REG_I2S0_BASE? (IDFGH-11518)

### ISSUE THREAD

**Issue by moefear85** [espressif/esp-idf#12643]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

In `soc/esp32c3/include/soc/soc.h:23`
```
#define REG_I2S_BASE(i)                         (DR_REG_I2S_BASE + (i) * 0x1E000)
```

but I'm getting compile errors, because `DR_REG_I2S_BASE` isn't defined anywhere for the C3, unlike 32/S2/S3/C6. What does exist in `soc/esp32c3/include/soc/reg_base.h:44`:
```
#define DR_REG_I2S0_BASE                        0x6002D000
```

If I replace `DR_REG_I2S_BASE` with `DR_REG_I2S0_BASE` in soc.h, it compiles fine. Is this an oversight, or am I missing something here?

**Comment by AxelLin** [comment]
@L-KAYA Any update?

**Comment by L-KAYA** [comment]
Fixing
