### ISSUE TITLE
Need clarification on esp_wifi_sta_get_rssi() (IDFGH-11564)

### ISSUE THREAD

**Issue by kriegste** [espressif/esp-idf#12685]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/network/esp_wifi.html#_CPPv421esp_wifi_sta_get_rssiPi
says
> Get the rssi info after station connected to AP.

Which device is "station" and which is "AP" here? My ESP32 opens an AP and my smartphone connects to it. I need to get the rssi of this connection. Is this the right function call? Because it does not work. What is the correct function?

**Comment by filzek** [comment]
When the ESP32 is connected to a WiFi Network its wireless interface is set to STA, so the function call simple grab the last RSSI frame info and store it, you can use this function to simple return the RSSI information of the ESP32 signal reception to the Router.

There is nothing more than it.

If you want to GET ALL info, you shall use:

`if (esp_wifi_sta_get_ap_info(&ap_wifidata)==0){
          printf("\n\nROUTER MAC=bssid[%02x:%02x:%02x:%02x:%02x:%02x]\r\n", ap_wifidata.bssid[0], ap_wifidata.bssid[1], ap_wifidata.bssid[2], ap_wifidata.bssid[3], ap_wifidata.bssid[4], ap_wifidata.bssid[5]);
          printf("rssi=%d\r\n", ap_wifidata.rssi);
          printf("channel=%d\r\n", ap_wifidata.primary);
          printf("antenna=%d\r\n", ap_wifidata.ant);
          printf("phy_11b:1=%d\r\n", ap_wifidata.phy_11b);
          printf("phy_11g:1=%d\r\n", ap_wifidata.phy_11g);
          printf("phy_11n:1=%d\r\n", ap_wifidata.phy_11n);
          printf("phy_lr:1=%d\r\n", ap_wifidata.phy_lr);
          printf("wps:1=%d\r\n", ap_wifidata.wps);
          printf("country code=[%s] channel_start=[%d] total_channels=[%d] max_power=[%d] policy=[%d]\r\n", ap_wifidata.country.cc,ap_wifidata.country.schan, ap_wifidata.country.nchan,ap_wifidata.country.max_tx_power, ap_wifidata.country.policy);
      }`


gotcha?
