### ISSUE TITLE
NTP on DHCPV6 (IDFGH-11569)

### ISSUE THREAD

**Issue by ElieSKickMaker** [espressif/esp-idf#12690]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

 Hello , 
 I am facing difficulties implementing DHCPv6 stateless configuration on the ESP32 in Ethernet mode. The primary goal is to retrieve the NTP server address from a DHCPv6 server. It seems that there might be a missing definition for LWIP_DHCP6_GET_NTP_SRV. Additionally, I cannot find any debug traces related to DHCPv6.

Code snippet in the on_got_ipv6 callback: 
```c
if (ipv6_type == ESP_IP6_ADDR_IS_LINK_LOCAL)
{
    memcpy(&s_ipv6_addr_linklocal, &event->ip6_info.ip, sizeof(s_ipv6_addr_linklocal));
    if (netif == NULL) {
        ESP_LOGE(TAG, "esp-netif is NULL");
    }
    struct netif *lwip_netif = esp_netif_get_netif_impl(&s_ipv6_addr_linklocal);
    netif_set_flags(lwip_netif, NETIF_FLAG_MLD6);
    netif_set_ip6_autoconfig_enabled(lwip_netif, 1);
    #if CONFIG_LWIP_IPV6_DHCP6
    ESP_ERROR_CHECK(dhcp6_enable_stateless(lwip_netif));
    #endif
}
```

-  Missing Definition for LWIP_DHCP6_GET_NTP_SRV:

I suspect that there might be a missing definition for LWIP_DHCP6_GET_NTP_SRV. This is critical for obtaining the NTP server address from the DHCPv6 server. Could you please confirm if this definition is included in the ESP-IDF?

-  No Debug Traces for DHCPv6:

Despite enabling DHCPv6 stateless configuration, I am unable to find any debug traces related to DHCPv6. This makes troubleshooting and debugging the implementation challenging. Are there specific configurations or additional steps required to enable DHCPv6 debugging?

I appreciate any guidance or insights you can provide to resolve these issues. If there are specific logs or configurations I should check, please let me know.

My esp-idf version is v4.4.1 and I can't update it because it's in production.. 

You can see the log output : 
![image](https://github.com/espressif/esp-idf/assets/92736346/e17d8e05-1e05-4cc1-b99e-fa3c2110535c)

Thank you for your assistance!

**Comment by xueyunfei998** [comment]
hi @ElieSKickMaker 

components/lwip/lwip/src/include/lwip/opt.h

This macro LWIP_DHCP6_GET_NTP_SRV is defined in this header file, and you can open it in this file.

If you want to track dhcpv6 log, you can also open this macro DHCP6_DEBUG in the header file above.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, feel free to reopen.
