### ISSUE TITLE
Divide by zero while setting up deep sleep on devices with PMU (IDFGH-11574)

### ISSUE THREAD

**Issue by bugadani** [espressif/esp-idf#12695]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

[`s_config.fast_clk_cal_period`](https://github.com/espressif/esp-idf/blob/ab03c2ea13ecaac1510b75e93b32cf0c472640fb/components/esp_hw_support/sleep_modes.c#L223C29-L223C29) in `esp_hw_support/sleep_modes.c` is initialized to 0. While setting up deep sleep, this value is not modified, but used in multiple places to convert timing values (using `rtc_time_us_to_fastclk`) for devices that use a PMU (https://github.com/espressif/esp-idf/blob/ab03c2ea13ecaac1510b75e93b32cf0c472640fb/components/esp_hw_support/sleep_modes.c#L725).

Based on some experimenting with an ESP32-C6, if machine code generated for `rtc_time_us_to_fastclk` ever returns 0, devices won't be able to wake up. Because a division by zero is underfined behaviour, this is entirely up to the current mood of the compiler.

**Comment by 0xjakob** [comment]
@bugadani Thanks for noticing this! We will take a look.
