### ISSUE TITLE
希望可以优化编程指南的描述

### ISSUE THREAD

**Issue by caidamao** [espressif/esp-idf#12696]
### Is your feature request related to a problem?

FAQ:https://espressif-docs.readthedocs-hosted.com/projects/esp-faq/zh-cn/latest/software-framework/storage/nvs.html

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, the updated version of the FAQ you mentioned is available at https://docs.espressif.com/projects/espressif-esp-faq/zh_CN/latest/software-framework/storage/nvs.html#nvs-api, feel free to reopen.

**Comment by caidamao** [comment]
> Thanks for reporting, the updated version of the FAQ you mentioned is available at https://docs.espressif.com/projects/espressif-esp-faq/zh_CN/latest/software-framework/storage/nvs.html#nvs-api, feel free to reopen.

thanks！
