### ISSUE TITLE
ESP32-H2 USB JTAG CONSOLE writes into UART1 (IDFGH-11582)

### ISSUE THREAD

**Issue by RJSDevel** [espressif/esp-idf#12701]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v5.1.2, on 5.1.1 the same

### Espressif SoC revision.

ESP32-H2 (revision v0.1)

### Operating System used.

Windows

### How did you build your project?

Eclipse IDE

### If you are using Windows, please specify command line type.

None

### Development Kit.

Custom H2

### Power Supply used.

USB

### What is the expected behavior?

Console Doesn't write into UART1

### What is the actual behavior?

Console writes into UART1

### Steps to reproduce.

1. Select in ESP System Settings -> Channel for console output = USB Serial/JTAG Controller
2. Init UART1 
3. Write into logs

![image](https://github.com/espressif/esp-idf/assets/12229274/8f8f2f76-701e-44a3-b9b5-832f75a7c8bb)
![image](https://github.com/espressif/esp-idf/assets/12229274/9378d42f-5f26-4ad9-8ea8-67763d86af5d)

**Comment by ESP-Marius** [comment]
Seems to work as expected on master after https://github.com/espressif/esp-idf/commit/9e62e32a5b4cd40bc17508670e303c2b3ecf3dee was merged, so marking this as resolved.
