### ISSUE TITLE
请问ble server是否能接受多个client同时连接？  (IDFGH-11588)

### ISSUE THREAD

**Issue by jankens** [espressif/esp-idf#12707]
### Is your feature request related to a problem?

在经典bt，一个server最多可以同时接受7只client连接，我计划使用esp32 c6，请问ble是否能有同样的功能？如果可以，请问在ble project 应用中应该如何设置？谢谢！

**Comment by Halley826** [comment]
examples/bluetooth/bluedroid/ble/gattc_multi_connect

**Comment by Indastri** [comment]
Since there was no response from the user I am closing this issue. If there will be any more problems feel free to reopen this or create a new issue.

Cheers!
