### ISSUE TITLE
The ADC cannot read the correct data when CONFIG_PM_SLP_DISABLE_GPIO=y is enabled (IDFGH-11597)

### ISSUE THREAD

**Issue by KEEPHEADU** [espressif/esp-idf#12715]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

When `CONFIG_PM_SLP_DISABLE_GPIO=y` is enabled, the ADC cannot read the correct data when light_sleep wakes up, and the data is always read out as 4081.

Is there a way to enable `CONFIG_PM_SLP_DISABLE_GPIO=y and` still use the ADC?

**Comment by esp-lis** [comment]
> ![image](https://private-user-images.githubusercontent.com/115463286/287886250-28f48622-5511-48e8-83eb-f79411adda45.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyODU3NDksIm5iZiI6MTcwMjI4NTQ0OSwicGF0aCI6Ii8xMTU0NjMyODYvMjg3ODg2MjUwLTI4ZjQ4NjIyLTU1MTEtNDhlOC04M2ViLWY3OTQxMWFkZGE0NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMVQwOTA0MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kN2M5NTUyYzFiY2RmOTU0NzE0YjJjNjllNDA1NjEzOGZkNzY0M2FhM2QzYmFlZGRmZDMxMGUxNmExNTM3Y2E1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SYRarF1cRtEmvV3x3ZrovbFItxjHyHK_wVIOL4fCpho) And in menuconfig this option is immutable, when I change it to n in sdkconfig, it will be automatically changed to y at compile time.
> 
> Can someone help me.

@KEEPHEADU refer to [Kconfig#L124](https://github.com/espressif/esp-idf/blob/master/components/esp_hw_support/Kconfig#L124), perhaps, it can help you.

**Comment by KEEPHEADU** [comment]
@esp-lis Thanks for your reply, I will try.
