### ISSUE TITLE
[TW#16555] BLE multiple operations in parallel

### ISSUE THREAD

**Issue by dimonomid** [espressif/esp-idf#1271]
When I try to fire, for example, a read of some charateristic, and then before it completes, a write to another characteristic, I get this:

```
E (8087) BT: bta_gattc_enqueue: already has a pending command!!
```

What is worse, despite that message in the log, my callback isn't called at all. So, the fact that the callback isn't called definitely looks like a bug. Other than that, a question: is it intended not to be able to execute parallel requests?

Thanks.

**Comment by mringwal** [comment]
GATT/ATT does not support concurrent requests. I think you may send a write_without_response at any time but you cannot do multiple reads or writes in parallel. Does the gatt write function has an error code? I'm not familiar with Bluedroid. On BTstack, you would get an error for the gatt write function and no callback either.

**Comment by Cicy-Chen** [comment]
Which version of BLE idf do you use，V2.1 or V3.0？

**Comment by Yulong-espressif** [comment]
@dimonomid We have added a command queue in the Host stack now, means that you can send more then one command at the same time. Please update the master.

**Comment by dimonomid** [comment]
@Yulong-espressif thanks a lot!

**Comment by ravdeepboparai** [comment]
Is this command queue in Host stack also implemented for the AT engine of ESP for all the commands?

**Comment by xiewenxiang** [comment]
ESP32-AT is developed based on ESP-IDF, So it behaves like Bluedroid.
