### ISSUE TITLE
ESP32 s3 gets hanged when wifi and ble are simultaneously used (IDFGH-11596)

### ISSUE THREAD

**Issue by VaishSPadiyappanavar** [espressif/esp-idf#12714]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

I am using esp32  gattc_multi_connect example from esp32 IDF. here i have three gatt server. I am establishing a connection with these three servers and then receiving data simultaneously from these and publishing the data of all these three servers to wifi through mqtt. the esp32 s3 is getting hanged when doing this. if there is higher data rates of ble the esp32 s3 gets hanged earlier .whereas if it the ble data rates are lower it gets hanged after long period. is there a hardware limitation that esp32 s3 is not able to handle this? can this be improved?

**Comment by zhp0406** [comment]
1- Does this issue only occur when using both WiFi and BLE together?
2- Could you provide me with the reproducible code, or the complete log?

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to short of feedback, feel free to reopen with more updates.
