### ISSUE TITLE
sdmmc example doesn't work in esp32s3usb-otg (IDFGH-11601)

### ISSUE THREAD

**Issue by suryasid09** [espressif/esp-idf#12719]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v5.2-dev-3775-gb4268c874a

### Espressif SoC revision.

ESP32-S3

### Operating System used.

Windows

### How did you build your project?

Eclipse IDE

### If you are using Windows, please specify command line type.

None

### Development Kit.

ESP32S3 USB OTG

### Power Supply used.

USB

### What is the expected behavior?

The example "sd-mmc" should be working without any changes in esp32s3-usb-otg development board.

### What is the actual behavior?

It doesn't seem to work. 

![sd_mmc](https://github.com/espressif/esp-idf/assets/119737596/476b5836-eb60-4985-806e-22ddb92805c0)

### Steps to reproduce.

I ran the example provided in the IDF version stated above.
I tried giving enabling internal pull-up, still, it didn't work.

**Comment by igrr** [comment]
@suryasid09 The board does have SD card interface, which is usable with SDMMC peripheral: https://docs.espressif.com/projects/espressif-esp-dev-kits/en/latest/esp32s3/esp32-s3-usb-otg/user_guide.html#sd-card-interface. Are you setting the GPIOs correctly?

**Comment by suryasid09** [comment]
I already changed the GPIO pin as described in the website but it doesn't work. 
Also, isn't SDMMC and SDIO different?  I got confused because it doesn't write SDMMC explicitly. 

![image](https://github.com/espressif/esp-idf/assets/119737596/d76f7244-7c36-488f-8a74-f5cec0dfde7c)

**Comment by igrr** [comment]
I have tried this example with the same settings as in your screenshot, and they work on my side with both `master` and `release/v5.2` branches.

Could you please change the log level to "Debug" and post the log in case when the card initialization fails?

**Comment by igrr** [comment]
@feifei112587 Your issue is about a different example (sdio), not related to the topic of the issue. Please open a separate issue for your case.

**Comment by feifei112587** [comment]
I have opened a new issue, but there is no answer



---Original---
From: "Ivan ***@***.***&gt;
Date: Wed, Dec 6, 2023 17:55 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [espressif/esp-idf] sdmmc example doesn't work in esp32s3usb-otg(IDFGH-11601) (Issue #12719)




 
@feifei112587 Your issue is about a different example (sdio), not related to the topic of the issue. Please open a separate issue for your case.

**Comment by adokitkat** [comment]
Cannot reproduce and no response, closing.
