### ISSUE TITLE
Dumping variables on heap (on demand) when generating coredump (IDFGH-11603)

### ISSUE THREAD

**Issue by djytw** [espressif/esp-idf#12721]
### Is your feature request related to a problem?

Currently we can use `COREDUMP_DRAM_ATTR` to dump variables on stack in coredump, but it will not work for heap variables because only pointers but not the pointed heap area saved to the coredump. When trying to read the pointer in gdb, it's nothing.

### Describe the solution you'd like.

An extra step to save the heap. Maybe the ram location can be read out from the current value of the variable, and length can be read out from the heap allocation table.

**Comment by erhankur** [comment]
Implemented in the 3b8191cf5d
