### ISSUE TITLE
When both wifi mesh and ble are enabled, continuously print "wifi: m f null" (IDFGH-11619)

### ISSUE THREAD

**Issue by fzboffice** [espressif/esp-idf#12735]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v5.2

### Espressif SoC revision.

ESP32

### Operating System used.

Windows

### How did you build your project?

Command line with idf.py

### If you are using Windows, please specify command line type.

None

### Development Kit.

ESP32_DEVKIT_V4

### Power Supply used.

USB

### What is the expected behavior?

Don't print "wifi: m f null"

### What is the actual behavior?

When both wifi mesh and ble are enabled, continuously print "wifi: m f null"

### Steps to reproduce.

[internal_communication.zip](https://github.com/espressif/esp-idf/files/13575926/internal_communication.zip)

1. I use esp-idf\examples\mesh\internal_communication project.
2. Enable BT in menuconfig.
3. Init BLE.
4. Call esp_mesh_fix_root(true).
5. Call esp_mesh_set_type(MESH_NODE);(another development board call call esp_mesh_set_type(MESH_ROOT)).
6. Start wifi mesh.
7. Wait 70 seconds,you will see it.

**Comment by MaxwellAlan** [comment]
Duplicated with https://github.com/espressif/esp-idf/issues/12737

Will close this issue.

Thanks.
