### ISSUE TITLE
ESP32-C6 Unable to join Phlips Hue zigbee network (IDFGH-11616)

### ISSUE THREAD

**Issue by Paveldeg** [espressif/esp-idf#12733]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Using ESP-IDF v5.1.2, ESP32-C6 N8 dev board connected via USB to a Macbook.

Using "HA_on_off_light" sample code from the [esp-zigbee-sdk](https://github.com/espressif/esp-zigbee-sdk), my Hue bridge does not see the light, and I get repeating console messages like this 
`" ESP_ZB_ON_OFF_LIGHT: Network steering was not successful (status: ESP_FAIL)"`

Is ESP32-C6 generally compatible with Philips Hue Zigbee bridge?

**Comment by xieqinan** [comment]
Hello @Paveldeg

This issue will be handled [here](https://github.com/espressif/esp-zigbee-sdk/issues/168). please close this one.

**Comment by chshu** [comment]
The issue was addressed by this comment: https://github.com/espressif/esp-zigbee-sdk/issues/168#issuecomment-1952370582
