### ISSUE TITLE
How to properly use SRAM1 as IRAM (IDFGH-11620)

### ISSUE THREAD

**Issue by Abhay-2412** [espressif/esp-idf#12736]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Hello,

My code, utilizing WiFi, BLE, and Arduino as a component, faces IRAM shortage. Despite optimizing and following guides, I still lack sufficient space. Using ESP IDF v4.4.5 with VSCode, I'm seeking clear steps on how to designate SRAM1 as IRAM. Appreciate any assistance.

**Comment by ESP-Marius** [comment]
Hi,

That is not supported on IDF v4.4.5. So your best option is to follow https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/performance/ram-usage.html as well as rethink how your application is using RAM and see if you can think of any other ways to reduce it.
