### ISSUE TITLE
DHCP issue - Not more than 10 connections and disconnections with different devices on ESP32 AP possible (IDFGH-11623)

### ISSUE THREAD

**Issue by MoegerleS** [espressif/esp-idf#12739]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v.4.4.6

### Espressif SoC revision.

ESP32

### Operating System used.

Linux

### How did you build your project?

VS Code IDE

### If you are using Windows, please specify command line type.

None

### Development Kit.

ESP32-WROVER-E

### Power Supply used.

External 5V

### What is the expected behavior?

Open an accesspoint in one ESP32 device and let more than 12 ESP32 devices connect with the AP at the same time.
Only 4 devices needs to stay connected with the AP. All other devices needs to disconnect directly after a successful connection and data transfer.

### What is the actual behavior?

The problem now is that only 10 of 12 devices will connect successfully with the AP. 4 will stay and 6 leave the network successfully. But the remaining 2 devices are still trying to connect with the SoftAP and get no IP address of  the DHCP server (always 0.0.0.0) nor any DHCP ACK.

In wireshark it looked like following. There is always a DISCOVER message of the client. In the top two requests, the DHCP server responds with a NAK. In comparison on the bottom there was a successfull connection of a different client, with an OFFER and an ACK response of the SoftAP.
![Bildschirmfoto vom 2023-12-06 11-53-05](https://github.com/espressif/esp-idf/assets/78904654/15cabe5d-1142-4fa5-9836-bb051bcc80cd)

I've also doublechecked the SoftAP list via esp_wifi_ap_get_sta_list(&clients). Here I got 5 active devices listed (including my Linux PC client) - What would be fine so far.
The max. number of possible SoftAP clients (CONFIG_MWIFI_MAX_CONNECTION) is set to 10 devices.

For me it seems that the DHCP server doesn't release the IP addresses of the disconnected devices and so doesn't accept any further devices. Why does the DHCP server doesn't response with an ACK?

### Steps to reproduce.

1. Selected 10 devices as max. number of clients for SoftAP (CONFIG_MWIFI_MAX_CONNECTION)
2. Let more than 10 devices (different MAC addresses) connect and disconnect with the SoftAP

**Comment by Xiehanxin** [comment]
hi @MoegerleS  in the IDF programming guide, it said that the AP max connection number is also effected by ESP-NOW device number, could you check it  https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/wifi.html#ap-basic-configuration

**Comment by Sherry616** [comment]
Thanks for reporting, will close due to short of feedback, feel free to reopen with more updates.
Thanks for using our Espressif product!
