### ISSUE TITLE
ESP32-S2: The SPI MOSI idle level is not the same between 5.1.2 and 5.2-dev (IDFGH-11646)

### ISSUE THREAD

**Issue by mcaralp** [espressif/esp-idf#12759]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Hi,

I'm currently working on a WS2812b driver using the SPI peripheral.

When using the 5.1.2 version of the SDK, the idle level of the MOSI output is low, but when using the 5.2-dev version of the SDK, the idle level of the MOSI output is high. It is a bit problematic in my case, since I need the idle level of MOSI to be low, as it is used as the reset instruction by the WS2812B LED.

The idle level is low again with the 5.2-dev version using the following code:
```c
esp_rom_gpio_connect_out_signal(gpio, spi_periph_signal[host].spid_out, true, false);
```

But then I need to also invert my output:

```c
data[i] = ~data[i];
```

I got this trick from here: https://esp32.com/viewtopic.php?t=22496

Here is my initialization code of the SPI peripheral:

```c
struct spi_device_handle_t handle;
struct spi_bus_config_t busConfig;
std::memset(&busConfig, 0, sizeof(spi_bus_config_t));
busConfig.miso_io_num = -1;
busConfig.mosi_io_num = GPIO_NUM_39;
busConfig.sclk_io_num = -1;
busConfig.quadwp_io_num = -1;
busConfig.quadhd_io_num = -1;
busConfig.max_transfer_sz = 18000;

struct spi_device_interface_config_t devConfig;
std::memset(&devConfig, 0, sizeof(spi_device_interface_config_t));
devConfig.mode = 0;
devConfig.clock_speed_hz = 2500000;
devConfig.queue_size = 1;
devConfig.spics_io_num = -1;
devConfig.post_cb = cb

spi_bus_initialize(SPI3_HOST, &busConfig, SPI_DMA_CH_AUTO);
spi_bus_add_device(SPI3_HOST, &devConfig, &handle);

// the call resolving the problem for 5.2-dev
esp_rom_gpio_connect_out_signal(GPIO_NUM_39, spi_periph_signal[SPI3_HOST].spid_out, true, false);
```

This call seems a bit hacky, and I'm not sure this is the right solution.
What can I do to tackle this behaviour?

Thanks!

**Comment by suda-morris** [comment]
[8f5851d0646cf7fbccc66929b2e307f0e4b438e3](https://github.com/espressif/esp-idf/blob/release/v5.2/components/hal/spi_hal.c#L71C39-L71C39)

I see the MOSI IDLE level was set to low level already.

**Comment by mcaralp** [comment]
On the 5.2-dev version of this file ([here](https://github.com/espressif/esp-idf/blob/v5.2-dev/components/hal/spi_hal.c)), this line does not exist. What is the difference between the branch release/5.2 and the tag 5.2-dev?

**Comment by suda-morris** [comment]
@mcaralp "5.2-dev" is not a release tag at all. It's just a tag that tells the start point where we're kicking off esp-idf/v5.2. 

BTW, v5.2-beta1 release will be on Github soon. Before a 5.2 release tag was pushed to the Github, I suggest you using the release/v5.2 branch.

**Comment by suda-morris** [comment]
> I'm currently working on a WS2812b driver using the SPI peripheral.

BTW, have you tried https://components.espressif.com/components/espressif/led_strip component? It supports both RMT and SPI as its backend controller

**Comment by mcaralp** [comment]
> @mcaralp "5.2-dev" is not a release tag at all. It's just a tag that tells the start point where we're kicking off esp-idf/v5.2.
> 
> BTW, v5.2-beta1 release will be on Github soon. Before a 5.2 release tag was pushed to the Github, I suggest you using the release/v5.2 branch.

Ok, thanks for the info. I thought it was a release since there is a page for it (https://github.com/espressif/esp-idf/releases/tag/v5.2-dev). It's more clear now.

> BTW, have you tried https://components.espressif.com/components/espressif/led_strip component? It supports both RMT and SPI as its backend controller

I didn't know ESP registry, it's  a nice tool! I will check the ledstrip component, thanks!
