### ISSUE TITLE
What is the time drift on the RTC_SLOW_CLK and RC_FAST_CLK? (IDFGH-11664)

### ISSUE THREAD

**Issue by amrsoll** [espressif/esp-idf#12777]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

I have been unable to find documentation on the precision of the built-in clock sources

- RTC_SLOW_CLK 
- RC_FAST_CLK

I am specifically looking for the specs on the esp32s3 mini 1, but hopefully we can get some specs for all of the chips?

- What is the dependence of the drift to the temperature? Linear, quadratic? How many ppm / C or ppm / C² ?
- What is the over-all deviation?

Thank you for your help.

**Comment by igrr** [comment]
Hi @amrsoll, I would ask you to submit this request using the following form: https://www.espressif.com/en/company/documents/documentation_feedback
We are likely not be able to support this question in ESP-IDF issue tracker since it has to do with hardware more than with ESP-IDF itself.

**Comment by amrsoll** [comment]
Thank you :)
