### ISSUE TITLE
Disabling CONFIG_ESP_CONSOLE_UART results in failure to build on esp32c6 (IDFGH-11671)

### ISSUE THREAD

**Issue by rkit1** [espressif/esp-idf#12783]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

5.1.2

### Operating System used.

Windows

### How did you build your project?

VS Code IDE

### If you are using Windows, please specify command line type.

None

### What is the expected behavior?

Project is expected to build.

### What is the actual behavior?

C:/Users/Victor/esp/esp-idf/components/esp_hw_support/sleep_modes.c: In function 'light_sleep_uart_prepare':
C:/Users/Victor/esp/esp-idf/components/esp_hw_support/sleep_modes.c:152:61: error: 'CONFIG_ESP_CONSOLE_UART_BAUDRATE' undeclared (first use in this function); did you mean 'CONFIG_ESP_CONSOLE_UART_NUM'?
  152 | #define UART_FLUSH_US_PER_CHAR              (10*1000*1000 / CONFIG_ESP_CONSOLE_UART_BAUDRATE)
      |                                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/Users/Victor/esp/esp-idf/components/esp_hw_support/sleep_modes.c:484:113: note: in expansion of macro 'UART_FLUSH_US_PER_CHAR'
  484 |             (sleep_duration < (int64_t)((UART_LL_FIFO_DEF_LEN - uart_ll_get_txfifo_len(CONSOLE_UART_DEV) + 1) * UART_FLUSH_US_PER_CHAR) + SLEEP_UART_FLUSH_DONE_TO_SLEEP_US)) {
      |                                                                                                                 ^~~~~~~~~~~~~~~~~~~~~~
C:/Users/Victor/esp/esp-idf/components/esp_hw_support/sleep_modes.c:152:61: note: each undeclared identifier is reported only once for each function it appears in
  152 | #define UART_FLUSH_US_PER_CHAR              (10*1000*1000 / CONFIG_ESP_CONSOLE_UART_BAUDRATE)
      |                                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/Users/Victor/esp/esp-idf/components/esp_hw_support/sleep_modes.c:484:113: note: in expansion of macro 'UART_FLUSH_US_PER_CHAR'
  484 |             (sleep_duration < (int64_t)((UART_LL_FIFO_DEF_LEN - uart_ll_get_txfifo_len(CONSOLE_UART_DEV) + 1) * UART_FLUSH_US_PER_CHAR) + SLEEP_UART_FLUSH_DONE_TO_SLEEP_US)) {
      |                                                                                                                 ^~~~~~~~~~~~~~~~~~~~~~

### Steps to reproduce.

1. Create a project from hello world template
2. In sdkconfig switch "channel for console output" to none.
3. Project fails to build

**Comment by AxelLin** [comment]
The fix is already in v5.1 branch (after v5.1.2 tag). https://github.com/espressif/esp-idf/issues/12314

**Comment by ESP-Marius** [comment]
As mentioned by @AxelLin this should already have been fixed in `release/v5.1` now (a803c846aaacbc60d3fa5b3d45059616312d65a4) and it will be included in v5.1.3

If you still experience any issues even with that fix applied then please let us know.
