### ISSUE TITLE
Issue on transmit hex bytes over uart2 on esp32-s3 (IDFGH-11672)

### ISSUE THREAD

**Issue by sadeghmojtabaei94** [espressif/esp-idf#12784]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

I am using esp32-s3 WROOM module with esp-idf v5.1.
I write this simple program that want to send some bytes of data over uart2.

`#define UART_NUM    UART_NUM_2
    uart_config_t uart_config = {
        .baud_rate = 115200,
        .data_bits = UART_DATA_8_BITS,
        .parity    = UART_PARITY_DISABLE,
        .stop_bits = UART_STOP_BITS_1,
        .flow_ctrl = UART_HW_FLOWCTRL_DISABLE,
        .source_clk = UART_SCLK_DEFAULT,
    };
    int intr_alloc_flags = 0;

    ESP_ERROR_CHECK(uart_driver_install(UART_NUM, BUF_SIZE * 2, 0, 0, NULL, intr_alloc_flags));
    ESP_ERROR_CHECK(uart_param_config(UART_NUM, &uart_config));
    ESP_ERROR_CHECK(uart_set_pin(UART_NUM, GPIO_NUM_17, GPIO_NUM_18, -1, -1));
    ESP_ERROR_CHECK(uart_set_word_length(UART_NUM,UART_DATA_8_BITS));
    ESP_ERROR_CHECK(uart_set_sw_flow_ctrl(UART_NUM,false,0,0));

    char da[] = {0x80,0xFF,0xFC,0x5F};
    uart_write_bytes(UART_NUM,da,sizeof(da));`

I want to send 0x80,0xFF,0xFC,0x5F through uart. I used a usb/serial to read the data and see that the data send by esp is 0x80,0xFC,0xFD.
It is so strange. why the data is like this? I searched a lot over the internet but it seems it is only my problem and the data is transmitting wrong over the uart. can anyone help me with this? I think there is a bug in hardware or software.

This is the image of my terminal app. I also see the data by osiloscope and it is the same.
![image](https://github.com/espressif/esp-idf/assets/153662995/d8d387c5-18d4-475e-892a-b523e81fe855)

**Comment by Virusmater** [comment]
I have a similar issue; how did you fix it?
