### ISSUE TITLE
Unable to clone release/v4.4 (IDFGH-11695)

### ISSUE THREAD

**Issue by tanyanfei** [espressif/esp-idf#12802]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

release/v4.4

### Operating System used.

macOS

### How did you build your project?

Command line with idf.py

### If you are using Windows, please specify command line type.

None

### What is the expected behavior?

git clone -b release/v4.4 --recursive https://github.com/espressif/esp-idf.git

Download successful

### What is the actual behavior?

git clone -b release/v4.4 --recursive https://github.com/espressif/esp-idf.git

Cloning into 'esp-idf'...
fatal: Remote branch release/v4.4 not found in upstream origin

### Steps to reproduce.

git clone -b release/v4.4 --recursive https://github.com/espressif/esp-idf.git

**Comment by SoucheSouche** [comment]
Hi @tanyanfei,
I am not really sure what is the cause of this error. It seems to be working just fine on our end.
Have you tried to run
`git clone --recursive https://github.com/espressif/esp-idf.git`
followed by
`git checkout releave/v4.4`
to check if this works for you?

**Comment by tanyanfei** [comment]
The same problem.

<img width="819" alt="image" src="https://github.com/espressif/esp-idf/assets/23734716/e36050b3-3b94-43cd-9861-87dbf8c457d8">

**Comment by tanyanfei** [comment]
But the release/v4.3 is ok.

<img width="794" alt="image" src="https://github.com/espressif/esp-idf/assets/23734716/0d4d903e-0458-41bf-9307-8743a9263c81">

**Comment by tanyanfei** [comment]
I need to upgrade to the release/v4.4
Can you tell me how to clone it ?
