### ISSUE TITLE
ESP32-C6 Zigbee HA on/off light pairing issue (IDFGH-11701)

### ISSUE THREAD

**Issue by Tokn59** [espressif/esp-idf#12808]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Hi, I successfully flashed this example. The device is "seen" by HA Zigbee2MQTT but does not pair. How do I enter the device in pairing mode please ?

**Comment by chshu** [comment]
@Tokn59 Could you specify the `pairing mode`? `seen` by HA, does it mean that the steering process is done? The device log maybe helpful to understand the status.

**Comment by Alvin1Zhang** [comment]
@Tokn59 Thanks for reporting, would you please help share if any updates for the issue? Thanks.
