### ISSUE TITLE
How to merge the tcp_client example with power_save example. (IDFGH-11719)

### ISSUE THREAD

**Issue by shlomo-edu** [espressif/esp-idf#12827]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

I am tying to add the power_save example to the tcp_client example.
The problem is that both initialize the WiFi.
So I try to extract some things from the power_save, but it still crash.
Is there a better way to do it?
Will the tcp_client work with power_save.
And also,
I am building a client that needs to connect every 1 minute to the server, but in some cases needs to be connected for several seconds.
How much do I save (percentages) if I am using the default configuration:
`
#define DEFAULT_LISTEN_INTERVAL 3
#define DEFAULT_BEACON_TIMEOUT  6
`
What are the pros and cons of increasing these parameters?

**Comment by 10086loutianhao** [comment]
hello， which type of chip do you use?

**Comment by shlomo-edu** [comment]
I am using the ESP32-S3-WROOM.

**Comment by 10086loutianhao** [comment]
@shlomo-edu hello, What are your specific requirements: what outcome are you expecting to achieve? What is your requirement for the sleep current level? Would you prefer to use our deepsleep or lightsleep mode?

**Comment by shlomo-edu** [comment]
Now I switched to ESP-AT project because I want to transfer the code to STM32.
So I don't know if there is a power_save example for this project.
If you know how to do it (in ESP-AT) then I would like o hear about it.

**Comment by 10086loutianhao** [comment]
emmm, I have not found ESP-AT project in our Gitlab, can you give this project link?

**Comment by shlomo-edu** [comment]
https://github.com/espressif/esp-at

**Comment by 10086loutianhao** [comment]
maybe you can use following code:
`#if CONFIG_PM_ENABLE
    // Configure dynamic frequency scaling:
    // maximum and minimum frequencies are set in sdkconfig,
    // automatic light sleep is enabled if tickless idle support is enabled.
    esp_pm_config_t pm_config = {
            .max_freq_mhz = CONFIG_EXAMPLE_MAX_CPU_FREQ_MHZ,
            .min_freq_mhz = CONFIG_EXAMPLE_MIN_CPU_FREQ_MHZ,
#if CONFIG_FREERTOS_USE_TICKLESS_IDLE
            .light_sleep_enable = true
#endif
    };
    ESP_ERROR_CHECK( esp_pm_configure(&pm_config) );
#endif // CONFIG_PM_ENABLE`

**Comment by 10086loutianhao** [comment]
you can find these codes in IDF wifi power_save example

**Comment by shlomo-edu** [comment]
I is not relevan any more, beccause I switched to ESP-AT project to embed the ESP32-C3 on our STM32 based PCB.
If you can help there, I will appreciate it very much.

**Comment by Xiehanxin** [comment]
hi @shlomo-edu  I think you can just add such codes to TCP programming
![image](https://github.com/espressif/esp-idf/assets/37785066/fdf755a5-b264-42fe-b650-5fe01dffb227)

**Comment by shlomo-edu** [comment]
Eventually I switch to ESP-AT project.
So I am using the AT-Commands that also do the " power consumption" with AT_SLEEP
