### ISSUE TITLE
esp_rom_gpio_connect_out_signal triggers an input level change (IDFGH-11731)

### ISSUE THREAD

**Issue by florentbr** [espressif/esp-idf#12826]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

5.1.2

### Espressif SoC revision.

ESP32 v3.1

### Operating System used.

Linux

### How did you build your project?

VS Code IDE

### If you are using Windows, please specify command line type.

None

### Development Kit.

ESP32-DevKitC V4

### Power Supply used.

USB

### What is the expected behavior?

Connecting the output signal to a pin should not trigger an input change when both are HIGH.

### What is the actual behavior?

For a pin configured as input pullup, calling `esp_rom_gpio_connect_out_signal` triggers a 
input level change even when the output signal and the input pin are both HIGH.

I suspect that `esp_rom_gpio_connect_out_signal` is first enabling the output which would 
set the ouput to LOW (default registry) before switching it back to HIGH at signal level.

### Steps to reproduce.

```c
gpio_num_t pin_a = GPIO_NUM_16;  // input, pull-up
gpio_reset_pin(pin_a);
esp_rom_gpio_pad_select_gpio(pin_a);
gpio_set_direction(pin_a, GPIO_MODE_INPUT);
gpio_set_pull_mode(pin_a, GPIO_PULLUP_ONLY);
esp_rom_gpio_connect_in_signal(pin_a, SIG_IN_FUNC227_IDX, 0);

gpio_num_t pin_b = GPIO_NUM_17;  // input, pull-up
gpio_reset_pin(pin_b);
esp_rom_gpio_pad_select_gpio(pin_b);
gpio_set_direction(pin_b, GPIO_MODE_INPUT);
gpio_set_pull_mode(pin_b, GPIO_PULLUP_ONLY);
gpio_set_intr_type(pin_b, GPIO_INTR_POSEDGE);
gpio_intr_enable(pin_b);

esp_rom_delay_us(10);
printf("Before connect: InputA: %lu  InputB: %lu  IntrStatus:%lu\n"
    , (GPIO.in >> pin_a) & 1, (GPIO.in >> pin_b) & 1, (GPIO.status >> pin_b) & 1);
GPIO.status_w1tc = (1 << pin_b);  // clear interrupts

// connect pin b to pin a
esp_rom_gpio_connect_out_signal(pin_b, SIG_IN_FUNC227_IDX, 0, 0);

esp_rom_delay_us(10);
printf("After connect: InputA: %lu  InputB: %lu  IntrStatus:%lu\n"
    , (GPIO.in >> pin_a) & 1 , (GPIO.in >> pin_b) & 1, (GPIO.status >> pin_b) & 1);
```

### Debug Logs.

```plain
I (1324) gpio: GPIO[16]| InputEn: 0| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 
I (1334) gpio: GPIO[17]| InputEn: 0| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 
Before connect: InputA: 1  InputB: 1  IntrStatus:0
After connect: InputA: 1  InputB: 1  IntrStatus:1
```

### More Information.

I get the expected behaviour by writing the registry directly:

```c
// GPIO_FUNC0_OUT_SEL_CFG_REG
GPIO.func_out_sel_cfg[pin_b].val =
    (SIG_IN_FUNC227_IDX << GPIO_FUNC0_OUT_SEL_S) |
    (0                  << GPIO_FUNC0_OEN_SEL_S) ;  // output enable by  0:signal 1:registry
```

I also get the expected behaviour when I first set the output level to the input:

```c
gpio_ll_set_level(&GPIO, pin_b, gpio_ll_get_level(&GPIO, pin_b));
esp_rom_gpio_connect_out_signal(pin_b, SIG_IN_FUNC227_IDX, 0, 0);
```

**Comment by suda-morris** [comment]
internally what the `esp_rom_gpio_connect_out_signal` done is:

```c
void esp_rom_gpio_connect_out_signal(uint32_t gpio_num, uint32_t signal_idx, bool out_inv, bool oen_inv)
{
    uint32_t value = signal_idx << GPIO_FUNC0_OUT_SEL_S;

    if (out_inv) {
        value |= GPIO_FUNC0_OUT_INV_SEL;
    }
    if (oen_inv) {
        value |= GPIO_FUNC0_OEN_INV_SEL;
    }
    REG_WRITE(GPIO_FUNC0_OUT_SEL_CFG_REG + (gpio_num * 4), value);

    GPIO_REG_WRITE(GPIO_ENABLE_W1TS_REG, (1 << gpio_num));
}
```

Your suspect is correct, that function "helps" enable the output ability.
