### ISSUE TITLE
[TW#16581] Potentially confusing change of dhcps default behaviour in cf7ae81

### ISSUE THREAD

**Issue by Eroc33** [espressif/esp-idf#1285]
Commit cf7ae81 changed dhcps to allow setting a custom dns server, however this seems to have changed the default behaviour for assigning dns ips over dhcp.
Previously the default behaviour was to use the ip of the device itself as the dns server, whereas now the default is to use the ip 0.0.0.0.
I suspect this may have broken captive portal code for many people (particularly if they are using the pattern common in tutorials/examples for arduino-esp32).
While the fix to user code would be relatively minor it seems like changing the default here in the idf is probably as simple as changing https://github.com/espressif/esp-idf/blob/master/components/lwip/apps/dhcpserver.c#L97 to be `static dhcps_offer_t dhcps_dns = 0x00;`

**Comment by liuzfesp** [comment]
Hi @Eroc33 we will check it and make sure the default behavior is not changed @zhangyanjiaoesp

**Comment by zhangyanjiaoesp** [comment]
@Eroc33  Thanks for your good suggestion. 
I have modify the code ,after it is merged ,I will post the commit ID
