### ISSUE TITLE
[Feature] Flashing an ESP32-s3 with WebUSB - is it possible? (IDFGH-11770)

### ISSUE THREAD

**Issue by chipweinberger** [espressif/esp-idf#12868]
Has anyone tried this? Flashing an ESP32-s3 from a web browser?

Any resources for implementing this?

Where should I look into esptool.py for reference?

**Comment by chipweinberger** [comment]
@dobairoland

**Comment by igrr** [comment]
WebSerial: https://github.com/espressif/esptool-js

WebUSB: https://github.com/espressif/esptool-js/issues/109#issue-1844510397

**Comment by chipweinberger** [comment]
That's awesome! I assume WebSerial uses USB under the hood?

Look at us working on Christmas Eve 😅

**Comment by chipweinberger** [comment]
> The Web Serial API provides a way for websites to read from and write to a serial device with JavaScript. Serial devices are connected either through a serial port on the user's system or through removable USB and Bluetooth devices that emulate a serial port

Seems like yes, it will work over USB Serial Jtag
