### ISSUE TITLE
cannot open source file (IDFGH-11768)

### ISSUE THREAD

**Issue by arvind55555** [espressif/esp-idf#12866]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

esp-idf-v5.1.2

### Espressif SoC revision.

esp32

### Operating System used.

Windows

### How did you build your project?

VS Code IDE

### If you are using Windows, please specify command line type.

CMD

### Development Kit.

esp32 pico v4

### Power Supply used.

USB

### What is the expected behavior?

to run examples with no errors.

### What is the actual behavior?

![image](https://github.com/espressif/esp-idf/assets/139859655/c7a4f4c9-c79a-40b2-b098-4586647b4fb6)

i'm always running into this error

### Steps to reproduce.

there's no step's perse. it is the issue with the compiler inside vscode. 

### More Information.

for me when i try to run the examples over esp-idf cmd prompt it runs perfectly. but no matter what i do, no matter what ide i use im not able to run the code without erros. i have tried all the remedies provide on google or youtube but it haven't worked for me

please help me out

**Comment by peter-marcisovsky** [comment]
Hi @arvind55555, the issue you are facing, is a matter of VsCode settings. Try to follow this [doc](https://github.com/espressif/vscode-esp-idf-extension/blob/master/docs/C_CPP_CONFIGURATION.md)
Hope it solves the problem.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, feel free to reopen.
