### ISSUE TITLE
Memory error (leak?) at i2c_master.h (IDFGH-11783)

### ISSUE THREAD

**Issue by CarlosEduardoNovaes** [espressif/esp-idf#12878]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [x] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v5.2-beta1-263-ge49823f10c

### Espressif SoC revision.

ESP32-D0WD-V3 (revision v3.0)

### Operating System used.

Windows

### How did you build your project?

VS Code IDE

### If you are using Windows, please specify command line type.

None

### Development Kit.

DOIT ESP32 - ESP32-WROOM-32D

### Power Supply used.

USB

### What is the expected behavior?

Work whitout memory errors

### What is the actual behavior?

After about 18174 i2c transactions got: Guru Meditation Error: Core 0 panic'ed (StoreProhibited). Exception was unhandled. i2c_master_transmit_receive

### Steps to reproduce.

1. Setup a project and configure i2c master bus with callback and also nonzero trans_queue.
2. Configure i2c callback to increment a counter after each new transaction is completed.
3. Issue new i2c transactions periodically. I using a AS5600 magnetic sensor and calling i2c_master_transmit_receive(as5600_dev_handle, write_buf, 1, read_buf, 2, -1); write_buf and read_buf are alocated only once and remain the same the entire program life.
4. Log transaction counter and read_buf, everything works until about 18174 i2c transactions.

### Debug Logs.

```plain
Timed = 532210 microsseconds :: i2c_transactions = 18015 ===> as5600 read = 61.699219 
... i2c_dev->master_bus->anyc_write_buffer[i2c_dev->master_bus->index] = 3fffffcc
Timed = 532242 microsseconds :: i2c_transactions = 18016 ===> as5600 read = 61.699219 
... i2c_dev->master_bus->anyc_write_buffer[i2c_dev->master_bus->index] = 3fffffdc
Timed = 532269 microsseconds :: i2c_transactions = 18017 ===> as5600 read = 61.699219 
... i2c_dev->master_bus->anyc_write_buffer[i2c_dev->master_bus->index] = 3fffffec
Timed = 532302 microsseconds :: i2c_transactions = 18018 ===> as5600 read = 61.699219 
... i2c_dev->master_bus->anyc_write_buffer[i2c_dev->master_bus->index] = 0
Guru Meditation Error: Core  0 panic'ed (StoreProhibited). Exception was unhandled.

Core  0 register dump:
PC      : 0x4000c333  PS      : 0x00060330  A0      : 0x800d9659  A1      : 0x3ffb4dc0
0x4000c333: memcpy in ROM

A2      : 0x00000000  A3      : 0x3ffb0274  A4      : 0x00000001  A5      : 0x00000000
A6      : 0x0000000c  A7      : 0x00000000  A8      : 0x00000000  A9      : 0x3ffb4a60
A10     : 0x0000004b  A11     : 0x00000000  A12     : 0x00000000  A13     : 0x3f4050f8
A14     : 0x00000001  A15     : 0x00000001  SAR     : 0x00000004  EXCCAUSE: 0x0000001d
EXCVADDR: 0x00000000  LBEG    : 0x4000c2e0  LEND    : 0x4000c2f6  LCOUNT  : 0xffffffff
0x4000c2e0: memcpy in ROM

0x4000c2f6: memcpy in ROM



Backtrace: 0x4000c330:0x3ffb4dc0 0x400d9656:0x3ffb4dd0 0x400d64fc:0x3ffb4e70 0x400eaf38:0x3ffb4ed0 0x400866fd:0x3ffb4f00
0x4000c330: memcpy in ROM

0x400d9656: i2c_master_transmit_receive at C:/Users/carlo/esp/esp-idf/components/driver/i2c/i2c_master.c:990

0x400d64fc: app_main at D:/Documents/Projetos/PCB_CNC/StepperFOC/main/main.cxx:144

0x400eaf38: main_task at C:/Users/carlo/esp/esp-idf/components/freertos/app_startup.c:208

0x400866fd: vPortTaskWrapper at C:/Users/carlo/esp/esp-idf/components/freertos/FreeRTOS-Kernel/portable/xtensa/port.c:134





ELF file SHA256: 69d430d0a

Rebooting...
ets Jul 29 2019 12:21:46

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:7172
load:0x40078000,len:15532
load:0x40080400,len:4
0x40080400: _init at ??:?

load:0x40080404,len:3904
entry 0x40080640
```

### More Information.

I did some research on the error and found out that "i2c_dev->master_bus->anyc_write_buffer[i2c_dev->master_bus->index]" points to a new memory position each time, even after previous transaction was completed. So I suspected that the memory allocated was not being released after sucessfully queueing the i2c transaction. In fact, when the error happens it points to nullptr.

I was not able to track down any futher for when the memory block was suposed to be released, so in a desperated attempt I inserted a line "heap_caps_free(i2c_dev->master_bus->anyc_write_buffer[i2c_dev->master_bus->index]); // <<< free memory BUG?" just after "ESP_RETURN_ON_ERROR(s_i2c_asynchronous_transaction(i2c_dev, i2c_ops, DIM(i2c_ops), xfer_timeout_ms), TAG, "I2C transaction failed");". It seens to solve the problem, but maybe is the wrong solution.

**Comment by CarlosEduardoNovaes** [comment]
It's worth noting that I am not issuing an I2C transaction every 20 us. The timer is inaccurately reporting time in microseconds, with a substantial discrepancy (roughly 500 times larger). This results in an approximately 10 ms delay for each I2C reading.

**Comment by mythbuster5** [comment]
Hi, @CarlosEduardoNovaes Is it possible not to use callback currently? I've already noticed the issue and fixing it.

**Comment by AxelLin** [comment]
@mythbuster5 Can you post the fix here for verifying?

**Comment by mythbuster5** [comment]
@AxelLin It's still in progress now.

**Comment by CarlosEduardoNovaes** [comment]
> Hi, @CarlosEduardoNovaes Is it possible not to use callback currently? I think in blocking method it should work well. I've already noticed the issue and fixing it. But it still need some time,

Hi, @mythbuster5, thanks for your response. It works with the blocking API. I made the switch to a newer esp-idf version to take advantage of the non-blocking API, aiming for readings every millisecond or even faster. However, I understand that this isn't a stable release.

So far, it has been operational for about 20 hours without any issues, thanks to the workaround mentioned in the opening post. This should serve me well for testing and proving the concept in my application. I'm considering switching to an AS5048 with an SPI interface in the next prototype level.

**Comment by EmbeddedDevver** [comment]
Loosing 300bytes of stack everytime the i2c handler fails to contact the i2c slave. 
I did this on purpose by removing the i2c slave and monitoring the Free Stack. it gets degreased by 300 bytes for every call below;

```
    log_i("RTC_DS3231::begin");
    Wire.begin(sdaPin, sclPin, frequency);

    log_i("RTC_DS3231::begin beginTransmission");
    Wire.beginTransmission(DS3231_ADDRESS);

    log_i("RTC_DS3231::begin endTransmission");
    if (Wire.endTransmission() == 0)
    {
        log_i("RTC_DS3231::begin return true");
        return true;
    }

    log_i("RTC_DS3231::begin return false: Warning MemoryLeak!");

    return false;
```

esp32-gateway (platform: espressif32@6.7.0; board: esp32-gateway; framework: arduino)
