### ISSUE TITLE
Is it possible to stop external 40MHz crystal oscillator from running?  (IDFGH-11793)

### ISSUE THREAD

**Issue by F1RST1** [espressif/esp-idf#12888]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [x] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

The chip I am using is esp32s3. 
I've checked the idf-framework and technical reference, and I found a register named SYSTEM_SOC_CLK_SEL. SYSTEM_SOC_CLK_SEL is XTAL_CLK by default. So would external 40MHz crystal oscillator stop running if I change this register to RC_FAST_CLK or PLL_CLK? 
![Snipaste_2023-12-28_19-20-43](https://github.com/espressif/esp-idf/assets/47220608/976d1586-d02e-41ef-a64c-d2045459b802)
![image](https://github.com/espressif/esp-idf/assets/47220608/16822895-4923-4081-bff9-ad84b4283761)

**Comment by songruo** [comment]
Hi @F1RST1, the external XTAL won't stop running even if SYSTEM_SOC_CLK_SEL is set to PLL or RC_FAST. May I ask what are you trying to achieve, and then maybe we can provide some ideas.

**Comment by F1RST1** [comment]
> Hi @F1RST1, the external XTAL won't stop running even if SYSTEM_SOC_CLK_SEL is set to PLL or RC_FAST. May I ask what are you trying to achieve, and then maybe we can provide some ideas.

Sure. The project is RGB lcd display driven by esp32s3. The hardware enginner is trying to pass the EMC test. 
Some critical reports are shown below. Any extra information could I provide to you? 
![Snipaste_2023-12-29_13-52-31](https://github.com/espressif/esp-idf/assets/47220608/e6d604d1-c1b7-48e6-aac7-9c00464006ed)
![Snipaste_2023-12-29_13-52-39](https://github.com/espressif/esp-idf/assets/47220608/fe98f9ef-d600-4bf8-b46c-c554494209ee)
![Snipaste_2023-12-29_13-52-44](https://github.com/espressif/esp-idf/assets/47220608/29f14db3-4e1d-406e-af25-66de9bde0d86)
