### ISSUE TITLE
Show a Popup in Browser (IDFGH-11801)

### ISSUE THREAD

**Issue by diplfranzhoepfinger** [espressif/esp-idf#12896]
### Is your feature request related to a problem?

there is a Function:  
`httpd_resp_send_err`

which can show such a Message in Browser e.g. Chrome:

![](https://github.com/espressif/esp-idf/assets/37779037/2a0c1e7a-72f7-4e7c-92fe-35fe8178a51b)

### Describe the solution you'd like.

_I would like a `httpd_resp_send_msg`_ which does the same as `httpd_resp_send_err` but not show "500 Error!" but e.g. "Success" ...

**Comment by diplfranzhoepfinger** [comment]
would be interesting Solution for https://github.com/espressif/esp-idf/issues/11220

**Comment by hmalpani** [comment]
Hello @diplfranzhoepfinger 
I think this might help you: https://github.com/espressif/esp-idf/blob/master/components/esp_http_server/include/esp_http_server.h#L1318

Please let me know if it works.

Thanks!

**Comment by franz-ms-muc** [comment]
i saw in the File Server you do it this way: 

[https://github.com/espressif/esp-idf/blob/b3f7e2c8a4d354df8ef8558ea7caddc07283a57b/examples/protocols/http_server/file_serving/main/upload_script.html#L49](https://github.com/espressif/esp-idf/blob/b3f7e2c8a4d354df8ef8558ea7caddc07283a57b/examples/protocols/http_server/file_serving/main/upload_script.html#L49)
