### ISSUE TITLE
New ethernet controller chip support (IDFGH-11825)

### ISSUE THREAD

**Issue by mike-2020** [espressif/esp-idf#12918]
### Describe the solution you'd like.

esp-idf includes support for DM9051, W5500 and ksz8851snl for ethernet (SPI interface). But all these chips were designed ten years ago. I'd like suggest esp-idf include support for some most updated chips, such as CH390. These new chips generally require less peripheral components, and consume much less power (much higher power efficiency).

**Comment by sauttefk** [comment]
As the CH390 is a SPI connected Ethernet MAC+PHY, you could try to adopt the DM9051 implementation. The changes should be relatively small, as the basic registers should be the same amongst all PHYs.

**Comment by kostaond** [comment]
@mike-2020, @SergeyKharenko implemented the CH390 driver, see #13306.

**Comment by mike-2020** [comment]
That is a nice job. Thanks for letting me know.在 2024年3月4日，21:58，Ondrej Kosta ***@***.***> 写道：﻿
@mike-2020, @SergeyKharenko implemented the CH390 driver, see #13306.

**Comment by kostaond** [comment]
CH390 driver has been released at https://github.com/espressif/esp-eth-drivers/tree/master/ch390
