### ISSUE TITLE
Named pattern matching in URIs (IDFGH-11847)

### ISSUE THREAD

**Issue by otaxhu** [espressif/esp-idf#12936]
### Is your feature request related to a problem?

My problem is that I need a way to get some "variables" (I don't know if that's a good term, it is also called URL param in other languages) from the URL.

### Describe the solution you'd like.

As an example imagine a REST resource `/things` each of those things have an ID, so you can request it like: `/things/12345`, in your `httpd_uri_t` struct, in the `.uri` field have something like `/things/{id}`, so you can in the handler have a function that extract that id.

I hope that you understand.

### Describe alternatives you've considered.

Maybe use the uri_matcher field from the httpd_config_t, but anyways you will need a function to extract the variable :/

### Additional context.

Example of use of case:
```c
esp_err_t thing_handler(httpd_req_t* r)
{
    // The name that i'm proposing for this function could be esp_get_var_from_uri
    char id[100];
    int bytes_read;
    do {
        bytes_read = esp_get_var_from_uri(r, "id", &id, 100);
        // Copy id variable in the heap or other thing
    } while (bytes_read > 0);
    // Do something with that string
}
```

**Comment by igrr** [comment]
You can try something like this: https://wokwi.com/projects/386111927941684225

See [POSIX regular expressions](https://pubs.opengroup.org/onlinepubs/009696899/functions/regcomp.html) documentation for more information about these functions.

**Comment by otaxhu** [comment]
Not the same problem, not talking about regexp. I was thinking about maybe use the user_ctx in certain way that performs what I'm looking for

**Comment by mahavirj** [comment]
@otaxhu 

Please see code snippet below, it should help for your use-case:

https://github.com/espressif/esp-idf/blob/5524b692ee5d04d7a1000eb0c41640746fc67f3c/examples/protocols/http_server/simple/main/main.c#L205-L231
