### ISSUE TITLE
Docker image for v5.0.5 is not available (IDFGH-11844)

### ISSUE THREAD

**Issue by DvdGiessen** [espressif/esp-idf#12933]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

The image it not available on Docker Hub: https://hub.docker.com/r/espressif/idf/tags?name=v5.0.5

This is because due to a timeout the image for v5.0.5 was not pushed:

https://github.com/espressif/esp-idf/actions/runs/7206956581/job/19632818564#step:7:14

It should probably be manually retried so it gets pushed.

Additionally, I see this happened before (see https://github.com/espressif/esp-idf/issues/11827). Perhaps it could be useful to add "make sure GitHub Actions completed without errors" to the release checklist or something like that?

**Comment by igrr** [comment]
Thank you for the suggestion, I have added this step to the release workflow.

**Comment by igrr** [comment]
And the image has  now been [uploaded](https://hub.docker.com/layers/espressif/idf/v5.0.5/images/sha256-bbd30709afa7d4815bf99a476e33fc4d3c5f032b01fa2ccc82c24b436c5293e7?context=explore)
