### ISSUE TITLE
misprint in example (IDFGH-11853)

### ISSUE THREAD

**Issue by Lagunaxx** [espressif/esp-idf#12942]
https://github.com/espressif/esp-idf/blob/5524b692ee5d04d7a1000eb0c41640746fc67f3c/examples/protocols/sockets/udp_multicast/main/udp_multicast_example_main.c#L135-L136
need to add "err = " at start of line 135

**Comment by espressif-abhikroy** [comment]
Fixed in a13bd2388ba7072235db93d88deda8e44633d4a3.
