### ISSUE TITLE
Bootloader Version (IDFGH-11864)

### ISSUE THREAD

**Issue by diplfranzhoepfinger** [espressif/esp-idf#12949]
### Bootloader Version

Hi,

the Application.bin has a Version, Compile Date, ESP-IDF Version etc.. in the File in the first line. 

But the Bootloader.bin seems not to have such Info. 

is there a way to get out more info about the Bootloader ? 

thanks, 
Franz

**Comment by ESP-Marius** [comment]
It should have the same info, see [bootloader image format](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/bootloader_image_format.html)

or read it directly with e.g. `esptool.py --chip esp32 image_info build/bootloader/bootloader.bin --version 2`

**Comment by ESP-Marius** [comment]
Marking this one as closed, if you feel what I linked to do not cover the feature you requested then feel free to reopen the issue.
