### ISSUE TITLE
Wrong maximum number of LMKs in docs (IDFGH-11890)

### ISSUE THREAD

**Issue by rguca** [espressif/esp-idf#12976]
The docs state the maximum number of LMKs is 6:
https://github.com/espressif/esp-idf/blob/b3f7e2c8a4d354df8ef8558ea7caddc07283a57b/docs/en/api-reference/network/esp_now.rst?plain=1#L56

After some testing, this seems not to be true. The maximum number of LMKs is defined by CONFIG_ESP_WIFI_ESPNOW_MAX_ENCRYPT_NUM.

**Comment by zhangyanjiaoesp** [comment]
@rguca yes, you are right, we will update the doc.
