### ISSUE TITLE
Guru Meditation Error: Core  1 panic'ed (Cache disabled but cached memory region accessed) ESP32 ARDUINO IDE 

### ISSUE THREAD

**Issue by jt040-jetnet** [espressif/esp-idf#1299]
i am using esp32 in arduino core 
i am using touch key feature in interrupt 
getting below error and my esp32 gets restart ,
please suggest how to fix it,
Guru Meditation Error: Core  1 panic'ed (Cache disabled but cached memory region accessed)
Register dump:
PC      : 0x400d13f4  PS      : 0x00060034  A0      : 0x40082388  A1      : 0x3ffc0bf0  
A2      : 0x00000000  A3      : 0x3ffc3590  A4      : 0x00000001  A5      : 0x40086408  
A6      : 0x00000003  A7      : 0x00060e23  A8      : 0x80081142  A9      : 0x04000c01  
A10     : 0x00060e23  A11     : 0x00000000  A12     : 0x00060023  A13     : 0x3ffc0bd0  
A14     : 0x3ffc0c18  A15     : 0x00000001  SAR     : 0x0000001e  EXCCAUSE: 0x00000007  
EXCVADDR: 0x00000000  LBEG    : 0x400014fd  LEND    : 0x4000150d  LCOUNT  : 0xffffffff  

Backtrace: 0x400d13f4:0x3ffc0bf0 0x40082385:0x3ffc0c10 0x4008f54f:0x00000000

Rebooting...
ets Jun  8 2016 00:22:57

rst:0x3 (SW_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0010,len:4
load:0x3fff0014,len:716
load:0x40078000,len:0
load:0x40078000,len:11572
entry 0x40078a14

**Comment by igrr** [comment]
This issue was moved to espressif/arduino-esp32#855
