### ISSUE TITLE
ETS_GPIO_INUM not defined anywhere

### ISSUE THREAD

**Issue by MakerAsia** [espressif/esp-idf#13]
ETS_GPIO_INUM was used in esp_intr.h and ets.sys.h but it does not be defined anywhere.

I tried to do GPIO interrupt and due to no gpio_pin_intr_state_set function available, so, I tried to write the register for this but can not do.

**Comment by igrr** [comment]
Indeed, these definitions were removed, but we forgot to remove their usage from esp_intr.h.

Unlike the 8266, interrupt numbers on each CPU are not connected directly to interrupt sources. Instead, they are routed via an interrupt matrix, which allows connecting arbitrary interrupt source to an arbitrary interrupt input of any of the CPUs.

Possible interrupt numbers (from 0 to 31) and their properties (interrupt level, and trigger mode: edge/level triggered) are defined in this table:
https://github.com/espressif/esp-idf/blob/master/components/esp32/include/soc/soc.h#L259-L294

Apart from the slots which are reserved, you can choose any interrupt number with the level and trigger mode you need, and attach it to the interrupt source. Interrupt sources are defined in the same file:
https://github.com/espressif/esp-idf/blob/master/components/esp32/include/soc/soc.h#L187-L257

Here's the function which allows you to attach interrupt sources to inputs, `intr_matrix_set`:
https://github.com/espressif/esp-idf/tree/master/components/esp32/include/rom/ets_sys.h#L502-L518

Once interrupt is attached, you can use `xt_set_interrupt_handler` and `xt_ints_on` to attach interrupt source and enable interrupt input of the CPU.

In most cases you also need to unmask some of the interrupts in peripheral registers, e.g.
https://github.com/espressif/esp-idf/blob/master/components/esp32/include/soc/gpio_struct.h#L161
