### ISSUE TITLE
[BLE] esp32s3 ends connection after inactivity. `GAP disconnect; reason: 0x0216 hci, CONN_TERM_LOCAL`  (IDFGH-11981)

### ISSUE THREAD

**Issue by chipweinberger** [espressif/esp-idf#13055]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v5.1.2

### Espressif SoC revision.

ESP32-s3

### Power Supply used.

USB

### What is the expected behavior?

The BLE connection should stay forever

### What is the actual behavior?

after some amount of time (few minutes), the ESP32-S3 ends the connection

it sees like it happens after a minute of "inactivity".

### Steps to reproduce.

I am use Nimble, connected to a macOS device

### Debug Logs.

```plain
I (1234713) pd ble: GAP disconnect; reason: 0x0216 hci, CONN_TERM_LOCAL     gapConnHandle: 1
I (1234713) pd ble: Connection Description:
I (1234713) pd ble:   role: Slave
I (1234713) pd ble:   gap connection handle: 1
I (1234713) pd ble:   our id:  Public 10:64:77:65:62:71
I (1234713) pd ble:   our ota: Public 10:64:77:65:62:71
I (1234713) pd ble:   peer id:  Public f8:4d:89:7c:1c:7c
I (1234713) pd ble:   peer ota: Public f8:4d:89:7c:1c:7c
I (1234723) pd ble:   connection interval:     12 (15.000ms)
I (1234723) pd ble:   connection latency:      0 times
I (1234723) pd ble:   supervision timeout:     72 (720ms)
I (1234723) pd ble:   Secure - encrypted:      0
I (1234723) pd ble:   Secure - authenticated:  0
I (1234723) pd ble:   Secure - bonded:         0
I (1234733) pd ble:   Secure - keySize:        0
```

**Comment by chipweinberger** [comment]
What can I do to debug this? thanks.

**Comment by chipweinberger** [comment]
@rahult-github @darshandobariya7

**Comment by chipweinberger** [comment]
note: i have wifi enabled in hotspot mode, but no clients connected.

**Comment by darshan7patel** [comment]
Hi @chipweinberger ,
I'm having trouble to reach this point, in the meantime could you kindly share the nimble debug enabled logs to figure out who terminated the connection?

**Comment by darshan7patel** [comment]
Hii @chipweinberger ,
Any update ?

**Comment by chipweinberger** [comment]
The problem has not happened for a awhile. I'll close this issue for now. 

If the problem happens again, I'll get more logs.

Thanks for asking.
