### ISSUE TITLE
spiffsgen for FAT (IDFGH-11979)

### ISSUE THREAD

**Issue by diplfranzhoepfinger** [espressif/esp-idf#13053]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Hi, 

does this 
https://github.com/espressif/esp-idf/tree/master/examples/storage/spiffsgen

work also if the Partition Type is FAT not SPIFFS ? 

Thanks

**Comment by dobairoland** [comment]
Here you have the FATFS example: https://github.com/espressif/esp-idf/tree/master/examples/storage/fatfsgen
