### ISSUE TITLE
404 for Toolchain Download

### ISSUE THREAD

**Issue by llewellynnu** [espressif/esp-idf#1306]
The Link mentioned in the docs return 404

https://dl.espressif.com/dl/xtensa-esp32-elf-osx-1.22.0-75-gbaf03c2-5.2.0.tar.gz

**Comment by imagineers-guild** [comment]
Hi

I can download from the link.

**Comment by chegewara** [comment]
Fixed.

**Comment by llewellynnu** [comment]
Thank You
