### ISSUE TITLE
ot_sleepy_device can't connect to border router (IDFGH-12014)

### ISSUE THREAD

**Issue by i-kratko** [espressif/esp-idf#13079]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

5.1.2

### Espressif SoC revision.

ESP32-C6

### Operating System used.

Windows

### How did you build your project?

Command line with idf.py

### If you are using Windows, please specify command line type.

CMD

### Development Kit.

ESP32-C6 DevKitM1

### Power Supply used.

USB

### What is the expected behavior?

I am trying to run the light sleep example from ot_sleepy_device and connect it to a thread border router.

### What is the actual behavior?

It does not connect and keeps on retrying. I have tried going into menuconfig and trying to enable joiner but this didn't seem to help.

### Steps to reproduce.

1. Set up the border router
2. Compile the ot_sleepy_device example

### Debug Logs.

```plain
I(7473) OPENTHREAD:[N] Mle-----------: Attach attempt 1 unsuccessful, will try again in 0.270 seconds
I(7753) OPENTHREAD:[N] Mle-----------: Attach attempt 2, AnyPartition
I(11243) OPENTHREAD:[N] Mle-----------: Attach attempt 2 unsuccessful, will try again in 0.531 seconds
I(11785) OPENTHREAD:[N] Mle-----------: Attach attempt 3, AnyPartition
I(15290) OPENTHREAD:[N] Mle-----------: Attach attempt 3 unsuccessful, will try again in 1.006 seconds
```

**Comment by zwx1995esp** [comment]
Hi, you need to check that if the dataset on the BR and the configuration for the light sleep are the same.
For the BR, I suggest that you reform a new thread network after a factoryreset, and set these commands to BR to get the dataset of the BR:
```
first factoryreset 
> factoryreset

.....boot log

> dataset init new
> dataset commit active
> ifconfig up
> thread start

after a while, BR becomes leader

> dataset

Active Timestamp: 1
Channel: 23
Channel Mask: 0x07fff800
Ext PAN ID: de6c75643b10ee30
Mesh Local Prefix: fd79:7567:3d27:7941::/64
Network Key: 300babfb8848858867676fa4f2778013
Network Name: OpenThread-dc52
PAN ID: 0xdc52
PSKc: 16ae34dc51971b88fe6e9a6015bfbf8a
Security Policy: 672 onrc 0
Done
> 
```

On the sleep end device, you need to set the same dataset configuration via idf.py menuconfig(here shows the default config, you need set the same with BR):
```
(Top) → Component config → OpenThread → Thread Operational Dataset

(OpenThread-ESP) OpenThread network name                                                                                                                      
(fd00:db8:a0:0::/64) OpenThread mesh local prefix, format <address>/<plen>                                                                                    
(15) OpenThread network channel                                                                                                                               
(0x1234) OpenThread network pan id                                                                                                                            
(dead00beef00cafe) OpenThread extended pan id                                                                                                                 
(00112233445566778899aabbccddeeff) OpenThread network key                                                                                                     
(104810e2315100afd6bc9215a6bfac53) OpenThread pre-shared commissioner key

```
Then build and flash the code to a C6 
```
$ idf.py build
$ idf.py -p <your-local-port> erase-flash flash monitor
```

Tips: please use the **erase-flash** to erase the original openthread configuration on the sleep device.

**Comment by i-kratko** [comment]
@zwx1995esp Thanks, this worked for me turns out I had one typo.
