### ISSUE TITLE
esp drivers (such as esp_driver_I2C) are missing in release v5.1.2 (IDFGH-12007)

### ISSUE THREAD

**Issue by bharat89bhushan** [espressif/esp-idf#13074]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

I am using esp-idf v5.1.2 and found that esp_driver_I2C (and other esp_driver_*) directory is missing from components directory. Then I switched to master branch I found all the components.

**Comment by suda-morris** [comment]
IDF is splitting the drivers into separate components as you see. https://docs.espressif.com/projects/esp-idf/en/latest/esp32/migration-guides/release-5.x/5.3/peripherals.html#drivers

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, feel free to reopen.
