### ISSUE TITLE
A Panic occured in 'internal\core\properties.rs', at line 323, column 13  (IDFGH-12022)

### ISSUE THREAD

**Issue by tao-a-man** [espressif/esp-idf#13087]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v5.1.2

### Espressif SoC revision.

ESP32-S3

### Operating System used.

Windows

### How did you build your project?

VS Code IDE

### If you are using Windows, please specify command line type.

PowerShell

### Development Kit.

esp-idf-v5.1.2

### Power Supply used.

USB

### What is the expected behavior?

I want call API and update UI with SLint library, I have four Task (picture 1), Function callAPI in Task 1
![Screenshot 2024-01-31 164912](https://github.com/espressif/esp-idf/assets/92592956/9310f971-3519-4e33-b1e4-c06200a2c1e5)

### What is the actual behavior?

I call the api and update UI normally until I call so much times (30 times) then I get issue (picture 1), but another Task still run nomally only Task 1 (task call api) get issue
![Screenshot 2024-01-31 165613](https://github.com/espressif/esp-idf/assets/92592956/050871f9-c972-40ff-b60e-c9c35cd5d67e)
)

### Steps to reproduce.

1. Build (succes)
2. run(success)
3. call api (succes)
4. call api so much times (Task 1 stop)

### Debug Logs.

```plain
A Panic occured in 'internal\core\properties.rs', at line 323, column 13
```

### More Information.

I use T-Displays3 for device and SLint for UI

**Comment by ESP-Marius** [comment]
This assertion seems to be coming from SLint library so I think it would be more appropriate to ask for help there.

From what you posted I can't see anything that implies that this is an issue with ESP-IDF. 

Feel free to re-open if there is any new information that shows any specific issues related to esp-idf
