### ISSUE TITLE
Wifi scan type differs in documentation and library (IDFGH-12031)

### ISSUE THREAD

**Issue by KorotynskiyA** [espressif/esp-idf#13096]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

![library](https://github.com/espressif/esp-idf/assets/58511410/15618d69-3b3b-48c7-9afd-c5eff0f2409b)
![documentation](https://github.com/espressif/esp-idf/assets/58511410/d707437b-36e2-476c-ae6b-ad3a1facde40)

I want to use Background Scan, but you haven't it in library.

**Comment by mhdong** [comment]
Hi @KorotynskiyA 
Background scan is applicable when there is a Wi-Fi connection in station mode or in station/AP mode. Whether it is a foreground scan or background scan **depends on the Wi-Fi driver and cannot be configured by the application**.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, feel free to reopen.
