### ISSUE TITLE
I find it difficult to connect ble devices with coded phy,how to fix it (IDFGH-12030)

### ISSUE THREAD

**Issue by luacerbb** [espressif/esp-idf#13095]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

idf 5.1.2

### Espressif SoC revision.

esp32-s3

### Operating System used.

Linux

### How did you build your project?

Command line with idf.py

### If you are using Windows, please specify command line type.

None

### Development Kit.

custom board

### Power Supply used.

USB

### What is the expected behavior?

I want it easier to connect ble device with coded phy

### What is the actual behavior?

I find it difficult to connect ble devices with coded phy,

### Steps to reproduce.

Place the Bluetooth slave device at a certain distance from the master device,slave devices switch phy broadcasts every 5 minutes. slave devices are easy to connected  when using 1Mphy, but hard to connect to when coded phy is used by master devices

**Comment by zhp0406** [comment]
@luacerbb 
The text seems to be related to two different versions of coded physical layer (coded phy), one at 125k and the other at 500k. Which one are you using?

Could you also provide an example of what you're reproducing and the corresponding print log?

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to short of feedback, feel free to reopen with more updates.
