### ISSUE TITLE
[TW#16673] Can't connect to NetgearWG302 with strictly WPA2

### ISSUE THREAD

**Issue by lollizze** [espressif/esp-idf#1309]
When I have a NetgearWG302 configured with WPA2 PSK, AES CCM i can't connect with my module (IDF v2.1)

It looks like esp32 tries to use TKIP as a group cipher even though the AP sends AES as the group cipher in its probe response 

Same setup with a newer Cisco works

**Comment by XinDeng11** [comment]
@lollizze could you offer the entity sniffer log to analysis?

**Comment by FayeY** [comment]
Closing due to lack of response, please feel free to reopen if this is still an issue and you can supply more details.
