### ISSUE TITLE
Missing GPIO_PIN_MUX_REG mappings

### ISSUE THREAD

**Issue by jolivepetrus** [espressif/esp-idf#131]
In my opinion GPIO_PIN_MUX_REG should have mappings for pins 40 (U0RX), 41 (U0TX).

**Comment by igrr** [comment]
U0RXD and U0TXD are pins 3 and 1. All API functions use GPIO numbers, not package pad numbers.
So the mappings are already there (GPIO_PIN_REG_3 and GPIO_PIN_REG_1).
