### ISSUE TITLE
ESP32-S3 dual CAN (IDFGH-12055)

### ISSUE THREAD

**Issue by GeorgeNegret** [espressif/esp-idf#13118]
ESP32-S3 have only one CAN controller ?
only ESP32-C6 have two ?

**Comment by wanckl** [comment]
@GeorgeNegret  Sadly, S3 really have only one. C6 have 2, and coming P4 have 3, I guess P4 meet your high perform and more TWAI instant. Or use S3 plus C6 :face_in_clouds:

**Comment by bobkim938** [comment]
@wanckl Is it possible to create two CAN nodes with one CAN controller?

**Comment by wanckl** [comment]
@bobkim938 

What you mean a `BUS`, a physical H/L bus?

CAN is type of async communication, basically, different bus have only baud rate different.

TWAI peripheral self actually is able to config/switch baud rate dynamically, Of course, it have time cost and will loss data during switching.     

How ever the point is, if you connect different buses, one baud rate transfer will lead another baud rate node/devices into `BUS_ERROR`, then you need an extra `switch hardware` for H/L line or CAN TX/RX line.       

Or even simulate a `sw_can` by CPU software

Theoretically they are all doable, but no need to. So, impossible!

**Comment by bobkim938** [comment]
@wanckl Thanks!!
