### ISSUE TITLE
When will ESP32C6/ESP32H2 support BLE uart HCI? (IDFGH-12064)

### ISSUE THREAD

**Issue by dreamcmi** [espressif/esp-idf#13126]
### Is your feature request related to a problem?

esp32 esp32c3 esp32s3 already supports uart hci. When will esp32c6 and esp32h2 support it?

**Comment by zhaoweiliang2021** [comment]
You can use the following example: esp-idf/examples/bluetooth/nimble/hci  to test uart hci for ESP32C6 and ESP32H2.

**Comment by Indastri** [comment]
Since there was no response from the user closing this issue. If you will encounter further problems feel free to reopen this or create a new issue.

Cheers!
