### ISSUE TITLE
ERROR: T#366378000000: CBSDSocketInterface: TCP-Socket recv() failed: Socket is not connected (IDFGH-12072)

### ISSUE THREAD

**Issue by diplfranzhoepfinger** [espressif/esp-idf#13133]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

`ERROR: T#366378000000: CBSDSocketInterface: TCP-Socket recv() failed: Socket is not connected`

Log: 

```
ERROR: T#361428000000: CBSDSocketInterface: TCP-Socket recv() failed: Connection reset by peer
ERROR: T#361429000000: CBSDSocketInterface: TCP-Socket recv() failed: Connection reset by peer
ERROR: T#361434000000: CBSDSocketInterface: TCP-Socket recv() failed: Socket is not connected
ERROR: T#361443000000: CBSDSocketInterface: TCP-Socket recv() failed: Socket is not connected
ERROR: T#361451000000: CBSDSocketInterface: TCP-Socket recv() failed: Socket is not connected
ERROR: T#361459000000: CBSDSocketInterface: TCP-Socket recv() failed: Socket is not connected
ERROR: T#361467000000: CBSDSocketInterface: TCP-Socket recv() failed: Socket is not connected
ERROR: T#361476000000: CBSDSocketInterface: TCP-Socket recv() failed: Socket is not connected
ERROR: T#361484000000: CBSDSocketInterface: TCP-Socket recv() failed: Socket is not connected
ERROR: T#361492000000: CBSDSocketInterface: TCP-Socket recv() failed: Socket is not connected
ERROR: T#361501000000: CBSDSocketInterface: TCP-Socket recv() failed: Socket is not connected
ERROR: T#361509000000: CBSDSocketInterface: TCP-Socket recv() failed: Socket is not connected
```

the function recv should return 0 in case of a Shutdown. 

see https://man7.org/linux/man-pages/man2/recv.2.html

but here it returns -1 and a errno of ECONNRESET

**Comment by diplfranzhoepfinger** [comment]
i fixed the Bug:

**Comment by diplfranzhoepfinger** [comment]
4f9bd96b1d333d7d8d48667f5526025fc499f413

[https://gitlab.com/meisterschulen-am-ostbahnhof-munchen/org.eclipse.4diac.forte/-/commit/4f9bd96b1d333d7d8d48667f5526025fc499f413](https://gitlab.com/meisterschulen-am-ostbahnhof-munchen/org.eclipse.4diac.forte/-/commit/4f9bd96b1d333d7d8d48667f5526025fc499f413)

working, Gerrit is coming.

**Comment by diplfranzhoepfinger** [comment]
https://git.eclipse.org/r/c/4diac/org.eclipse.4diac.forte/+/206333

**Comment by david-cermak** [comment]
@diplfranzhoepfinger If I understand correctly the bug wasn't in IDF (assuming the connection wasn't closed cleanly, for more info please read https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/lwip.html#bsd-sockets-api).

Closing this issue, please reopen if my interpretation was wrong.

**Comment by diplfranzhoepfinger** [comment]
https://github.com/eclipse-4diac/4diac-forte/pull/18
