### ISSUE TITLE
ESP32-C3 disconnecting after starting Wi-Fi (IDFGH-12099)

### ISSUE THREAD

**Issue by weiying-chen** [espressif/esp-idf#13157]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

My ESP32-C3 disconnects when I add this Rust code (note: there are no errors whatsoever):

    use embedded_svc::wifi::{ClientConfiguration, Configuration, Wifi};

    let mut wifi_driver = EspWifi::new(peripherals.modem, sys_loop, Some(nvs)).unwrap();
    wifi_driver.start().unwrap(); // more specifically, this line

This is what espmonior sees before my ESP32-C3 disconnects from my mini PC:

```
I (500) wifi:wifi firmware version: 1ba8b6a
I (500) wifi:wifi certification version: v7.0
I (500) wifi:config NVS flash: enabled
I (500) wifi:config nano formating: disabled
I (510) wifi:Init data frame dynamic rx buffer num: 32
I (510) wifi:Init management frame dynamic rx buffer num: 32
I (520) wifi:Init management short buffer num: 32
I (520) wifi:Init dynamic tx buffer num: 32
I (530) wifi:Init static tx FG buffer num: 2
I (530) wifi:Init static rx buffer size: 1600
I (530) wifi:Init static rx buffer num: 10
I (540) wifi:Init dynamic rx buffer num: 32
I (540) wifi_init: rx ba win: 6
I (550) wifi_init: tcpip mbox: 32
I (550) wifi_init: udp mbox: 6
I (550) wifi_init: tcp mbox: 6
I (560) wifi_init: tcp tx win: 5744
I (560) wifi_init: tcp rx win: 5744
I (570) wifi_init: tcp mss: 1440
I (570) wifi_init: WiFi IRAM OP enabled
I (570) wifi_init: WiFi RX IRAM OP enabled
I (585) phy_init: phy_version 1150,7c3c08f,Jan 24 2024,17:32:21
Device disconnected; exiting
```

[This](https://gist.github.com/rajeshpachaikani/2ef7c11b4d7e8a6704dba0f323bcdd6d) is the full code.

Also [posted](https://www.reddit.com/r/embedded/comments/1andhul/esp32c3_disconnecting_after_starting_wifi/) on Reddit

**Comment by MaxwellAlan** [comment]
Hi @weiying-chen 

`Device disconnected; exiting` this log seems from esp-rs framework, suggest move this issue to esp-rs

Thanks.

**Comment by weiying-chen** [comment]
@MaxwellAlan The issue was that my ESP32-C3 was underpowered. Sorry for opening the issue.

**Comment by Alvin1Zhang** [comment]
Thanks for sharing the updates, feel free to reopen.
