### ISSUE TITLE
[TW#16703] Force data rate with esp_wifi_80211_tx

### ISSUE THREAD

**Issue by mic159** [espressif/esp-idf#1319]
Is there a way to send a packet with a forced data rate of 24mbps?

I am sending a data frame (type 2, subtype 0) with `esp_wifi_80211_tx`.

I tried sending a packet to the broadcast MAC, but it sends it at 1mbps.
I also tried sending a packet with the address 1, 2 and 3 all as the chip's MAC, but still only 1mbps.

**Comment by jeanleflambeur** [comment]
I found an undocumented way in one of the issues here. Here are my results:
https://www.esp32.com/viewtopic.php?f=19&t=3017

**Comment by mic159** [comment]
It works, thank you!
