### ISSUE TITLE
ESP32-S3 Unable to enter automatic sleep when RMT is in use (IDFGH-12151)

### ISSUE THREAD

**Issue by timsterc** [espressif/esp-idf#13207]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v5.2

### Espressif SoC revision.

ESP32-S3

### Operating System used.

macOS

### How did you build your project?

Command line with idf.py

### If you are using Windows, please specify command line type.

None

### Development Kit.

Custom Board

### Power Supply used.

USB

### What is the expected behavior?

I expect to be able to use Automatic Light Sleep and have made sure of the following:

I checked that the CONFIG_FREERTOS_USE_TICKLESS_IDLE and CONFIG_PM_ENABLE sdkconfig options are enabled.

I make the following call to configure the PM
```
        esp_pm_config_t pm_config = {
                .max_freq_mhz = 240,
                .min_freq_mhz = 40,
                .light_sleep_enable = true
        };
        ESP_ERROR_CHECK( esp_pm_configure(&pm_config) );
```

### What is the actual behavior?

I'm unable to enter light sleep during a lengthy vTaskDelay - when neither processor is active.  I used the following calls to dump the active locks immediately prior to the call to vTaskDelay

```
            ESP_LOGI("PM Debug", "Dumping active power management locks:");
            esp_pm_dump_locks(stdout);
```

```
Lock stats:
Name            Type            Arg    Active  
wifi                APB_FREQ_MAX    0      0       
sdmmc         APB_FREQ_MAX    0      0       
i2c_driver     APB_FREQ_MAX    0      0       
rmt_0_0       CPU_FREQ_MAX    0      1       
rtos1             CPU_FREQ_MAX    0      0       
rtos0            CPU_FREQ_MAX    0      1      
```

I have tried setting multiple setting for the RMT clock source, but none of them seem to release the lock:

```
    ESP_LOGI(TAG, "Create RMT TX channel");
    rmt_tx_channel_config_t tx_chan_config = {
        .clk_src = RMT_CLK_SRC_DEFAULT, // select source clock
//        .clk_src = RMT_CLK_SRC_XTAL, // select source clock
        .gpio_num = gpio,
        .mem_block_symbols = 64, // increase the block size can make the LED less flickering
        .resolution_hz = RMT_LED_STRIP_RESOLUTION_HZ,
        .trans_queue_depth = 4, // set the number of transactions that can be pending in the background
    };
    ESP_ERROR_CHECK(rmt_new_tx_channel(&tx_chan_config, &led_chan));
```

### Steps to reproduce.

See above.

**Comment by lapinos03** [comment]
I'm facing exactly the same issue. How did you solve it, please ?
