### ISSUE TITLE
How to cleanly destroy a websocket client and start again if needed? (IDFGH-12158)

### ISSUE THREAD

**Issue by hitecSmartHome** [espressif/esp-idf#13214]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

I have a scenario where I start a websocket client connection and at some point at runtime, i have to stop it, destroy the task that associated with it ( i need the heap and stack back from ssl for a couple of minutes ) and re init the whole again.

Currently here is what I'm doing

**WS Client wrapper class**

```cpp
void WebsocketClient::init(){
    client = esp_websocket_client_init(&config);
    esp_websocket_register_events(
        client,
        WEBSOCKET_EVENT_ANY,
        reinterpret_cast<esp_event_handler_t>(eventHandler),
        static_cast<void*>(this)
    );
    esp_websocket_client_start(client);
}

void WebsocketClient::disconnect(){
    esp_websocket_client_stop(client); // Might not be good for clean disconnection
}

void WebsocketClient::stop(){
    esp_websocket_client_destroy(client);
}
```

**Ws client user class**

```cpp
void HsHServerRouter::suspend(){
    webSocket.disconnect(); // dc the ws client
    webSocket.stop(); // stop and destroy the connection so we can get back precious resources
    queue.clear(); // clear the message queue
}

void HsHServerRouter::resume(){
    begin(); // begin all over again ( fill config with default info, call esp_websocket_client_start etc... )
}
```

When `OTA` starts, I call `suspend()`. 
When it ends with error and we don't want to restart the **ESP** I call `resume()`.

Hovewer, there is a problem. When i disconnect and destroy the client, it still tryes to reconnect ( idk how? ) and won't release the resources, therefore i have not enough ram to perform OTA. In fact, the ws never reconnects after a failed OTA update.

**Here are some logs**

```cpp
[HsH_Server] - Connected


[OTA] - Starting.
[SYSTEM] - heap_caps_calloc was called but failed to allocate 16717 bytes with 0x804 capabilities.
[Logger] - (/logs/warning.json) size: 56934 max allowed size: 100000
E (40336) esp-tls-mbedtls: mbedtls_ssl_setup returned -0x7F00

E (40337) esp-tls: create_ssl_handle failed

E (40337) esp-tls: Failed to open new connection

E (40339) TRANSPORT_BASE: Failed to open a new connection

E (40345) TRANSPORT_WS: Error connecting to host hitecsmarthome.onrender.com:443

E (40351) WEBSOCKET_CLIENT: Error transport connect

[HsH_Server] - Disconnected


[HsH_Server] - Connected
```

The flow

1. Connects to websocket server ( with ssl )
2. Connection is healthly and working.
3. OTA starts
4. Calling `suspend()`
5. The rest is error

I have tried in this way

```cpp
void WebsocketClient::disconnect(){
    esp_websocket_client_close(client, portMAX_DELAY); // Clean disconnect
    //esp_websocket_client_stop(client);
}
```

On clean close it won't try to reconnect but fails to init again.

OTA logs in serial

```
15:56:18 [INFO]: Starting on 0.0.0.0:50789
15:56:18 [INFO]: Upload size: 2245424
Sending invitation to hsh 
Authenticating...OK
15:56:19 [INFO]: Waiting for device...
15:56:29 [ERROR]: No response from device
*** [upload] Error 1
```

**Comment by gabsuren** [comment]
@hitecSmartHome Thank you for raising the question, and I apologize for the delayed response. To disable the reconnect feature, please enable the `disable_auto_reconnect` configuration. You can find more details at the following link
https://github.com/espressif/esp-protocols/blob/bd6e12050928464b4357015c7c8c1b215432d580/components/esp_websocket_client/include/esp_websocket_client.h#L101

**Comment by hitecSmartHome** [comment]
Will try it, thank you very much!
