### ISSUE TITLE
Request for FatFS read/write example (IDFGH-123)

### ISSUE THREAD

**Issue by FilbertWong** [espressif/esp-idf#1321]
Hi All,
I'd like to have an example for FatFS write file and read file on SD card. someone can show me?

**Comment by negativekelvin** [comment]
https://github.com/espressif/esp-idf/tree/master/examples/storage/sd_card

**Comment by FilbertWong** [comment]
@negativekelvin : As I know this example is using stdio library in newlib component NOT fatfs component.

**Comment by negativekelvin** [comment]
Any reason you do not want to use vfs adapter?

**Comment by FilbertWong** [comment]
Actually, I'm deploying a file server system on esp32 wrover kit, and I used fatfs for transferring. basically, the function can work on esp idf 2.0 but cannot work on idf 3.0 (master branch). I'm confusing whether my usage is not correct or any different between idf 2.0 and 3.0.

**Comment by projectgus** [comment]
Sorry noone hasn't updated this issue for so long.

The supported way to use FATFS in ESP-IDF is via the VFS layer and standard libc/POSIX I/O.

We're unlikely to ever add an example that uses FATFS API directly on SDMMC or another storage layer, sorry.

Hopefully you had some luck debugging your file server firmware on ESP-IDF V3.0.
