### ISSUE TITLE
components/esp_system/panic.c:58:10: fatal error: esp_gdbstub.h: No such file or directory (IDFGH-12162)

### ISSUE THREAD

**Issue by moefear85** [espressif/esp-idf#13218]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

f68c131

### Operating System used.

Windows

### How did you build your project?

Command line with Make

### If you are using Windows, please specify command line type.

None

### What is the expected behavior?

everything compiles

### What is the actual behavior?

see title

### Steps to reproduce.

`set(COMPONENTS "main")` in CMakeLists.txt, and `CONFIG_ESP_SYSTEM_PANIC_GDBSTUB=y` in sdkconfig

### More Information.

None

**Comment by sudeep-mohanty** [comment]
Thanks for reporting the issue to us @moefear85. I can confirm that this issue is reproducible. We shall work on a fix. Thanks!
