### ISSUE TITLE
Compiler Assembly Output Viewing Feature (IDFGH-12171)

### ISSUE THREAD

**Issue by 5ami** [espressif/esp-idf#13226]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

I sometimes   need to inspect the assembly output generated by the compiler. This is crucial for understanding how the code is translated into machine instructions, optimizing performance, and debugging issues related to compiler optimizations or generated code.
However I cant find it in the Build directory, the only option I can use is by running the Debugger and use GDB, but I would like to see the output assembly without a target. Is that possible to do in ESP-IDF??

**Comment by igrr** [comment]
If you want to get the assembly listings for individual source files of a component, you can use
```
target_compile_options(${COMPONENT_LIB} PRIVATE "-save-temps" "-fverbose-asm")
```

and then find the listings in `<project>/build/esp-idf/<component>/CMakeFiles/__idf_<component>.dir/<filename>.c.s`

Alternatively, you can use `idf_build_set_property(COMPILE_OPTIONS <options ... > APPEND)` if you want to add these flags for all of the components.

Another option is to use `xtensa-esp32-elf-objdump -S build/app.elf` and get the assembly listing of the linked application, which is often more useful than the per-object listings.
