### ISSUE TITLE
[TW#16747] Typo in rtc_io.h

### ISSUE THREAD

**Issue by No-0n3** [espressif/esp-idf#1323]
A typo:

> typedef enum {
>     RTC_GPIO_MODE_INPUT_ONLY , /*!< Pad output */
>     RTC_GPIO_MODE_OUTPUT_ONLY, /*!< Pad input */
>     RTC_GPIO_MODE_INPUT_OUTUT, /*!< Pad pull output + input */ <--- Missing 'P' in OUTPUT
>     RTC_GPIO_MODE_DISABLED,    /*!< Pad (output + input) disable */
> } rtc_gpio_mode_t;

File: https://github.com/espressif/esp-idf/blob/master/components/driver/include/driver/rtc_io.h @

**Comment by krzychb** [comment]
I will get it fixed.
Thanks @No-0n3!

**Comment by krzychb** [comment]
Resolved in https://github.com/espressif/esp-idf/commit/866b84b9f8f50cb7f2a5853c43ee3cf387be1f61
