### ISSUE TITLE
SPI transfers limited to approximately 4KiB

### ISSUE THREAD

**Issue by MrSurly** [espressif/esp-idf#1329]
Attempting to transfer more than 4092 bytes (using DMA) results in `E (63662) spi_master: spi_device_queue_trans(620): txdata transfer > host maximum`.

Solutions, in order of most desirable to least:
* `spi_device_transmit` handles larger blocks transparently
* The SPI code provides a mechanism for user code to query the maximum transfer size
* The SPI documentation is updated to reflect the limitation

**Comment by MrSurly** [comment]
I'd be willing to submit a PR, if there was a reasonable chance it would be accepted.

**Comment by negativekelvin** [comment]
https://github.com/espressif/esp-idf/blob/master/components/driver/spi_master.c#L87

**Comment by negativekelvin** [comment]
https://github.com/espressif/esp-idf/blob/63e1e4e502178ced9d29999e45050c952be29c26/components/driver/include/driver/spi_common.h#L60

**Comment by FayeY** [comment]
Hi @MrSurly , did the above suggestion help you resolve the issue?

**Comment by ginkgm** [comment]
@MrSurly 
As @negativekelvin said, there's a configuration field to set the max transfer size, this is mainly because we have to allocate space for the DMA descriptors at initialization. 
If this field is not set, we only use 1 descriptor which support up to 4094 bytes buffer length.

**Comment by MrSurly** [comment]
@FayeY Yes, that works.  Thanks.

**Comment by bonmotwang** [comment]
I am having the same issue in using SPI to update a LCD module. I need 38400 bytes of DMA buffer in calling spi_device_transmit. It is only around 4000 bytes could be sent at once.

**Comment by ginkgm** [comment]
Hi @bonmotwang ,
Please set the parameter here, and also prepare enough size of *Internal* buffer for RAM

https://espressif-docs.readthedocs-hosted.com/projects/esp-idf/en/latest/api-reference/peripherals/spi_master.html#_CPPv4N16spi_bus_config_t15max_transfer_szE

https://espressif-docs.readthedocs-hosted.com/projects/esp-idf/en/latest/api-reference/system/mem_alloc.html?highlight=heap_caps#_CPPv416heap_caps_malloc6size_t8uint32_t

If the internal RAM is not enough, please split the data into pieces and send by several times.
