### ISSUE TITLE
'xPendedTicksTemp' undeclared (IDFGH-12247)

### ISSUE THREAD

**Issue by endsofinvention** [espressif/esp-idf#13297]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v5.2 (installed via VSCode plugin

### Operating System used.

Linux

### How did you build your project?

VS Code IDE

### If you are using Windows, please specify command line type.

None

### What is the expected behavior?

I expected the IDF code to build.

### What is the actual behavior?

I get the following build error
```
/esp/v5.2/esp-idf/components/freertos/FreeRTOS-Kernel/tasks.c:3322:21: error: 'xPendedTicksTemp' undeclared (first use in this function); did you mean 'xPendedTicks'?
 3322 |                 if( xPendedTicksTemp == ( TickType_t ) 0 )
```
Disabling `configUSE_TICK_HOOK` removes the error. 

### Steps to reproduce.

1. Open example project
2. Enable configUSE_TICK_HOOK
3. build

...

### Build or installation Logs.

```
`/esp/v5.2/esp-idf/components/freertos/FreeRTOS-Kernel/tasks.c:3322:21: error: 'xPendedTicksTemp' undeclared (first use in this function); did you mean 'xPendedTicks'?
 3322 |                 if( xPendedTicksTemp == ( TickType_t ) 0 )`

```

**Comment by Dazza0** [comment]
@endsofinvention Thanks for raising this issue. Will add a fix for this.
