### ISSUE TITLE
rst:0x10 (RTCWDT_RTC_RESET),boot:0x invalid header: Oxffffffff invalid header: Oxffffffff invalid header: 0xffffffff invalid header: 0xffffffff invalid header: 0xffffffff invalid header: Oxffffffff invalid header: 0xffffffff (IDFGH-12255)

### ISSUE THREAD

**Issue by prabhath3** [espressif/esp-idf#13302]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

rst:0x10 (RTCWDT_RTC_RESET),boot:0x
invalid header: Oxffffffff
invalid header: Oxffffffff
invalid header: 0xffffffff
invalid header: 0xffffffff
invalid header: 0xffffffff
invalid header: Oxffffffff
invalid header: 0xffffffff
It's esp32 md cam module 
I tried to upload webcam code to it
Same result when try to factory reset

**Comment by dobairoland** [comment]
All FFs indicate that flashing was unsuccessful (or you flashed the binaries to some address different from where the ESP32 is booting). So check the addresses for flashing and try to flash again.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to short of feedback, feel free to reopen with more updates.
