### ISSUE TITLE
ESP32-C6 Support for External RAM (IDFGH-12253)

### ISSUE THREAD

**Issue by blue-freedom-technologies** [espressif/esp-idf#13300]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

As my understanding the ESP32-C6 has no current support for External PSRAM.
For my current project performance is not critical. But RAM memory is and the ESP32-C6 does not have enough of it. (And we cannot use any other ESP32 alternatives)

In theory if I use a thing like the [SparkFun Thing Plus - ESP32-C6](https://www.sparkfun.com/products/22924) where we have a µSD Card Slot working with the [SPI driver](https://docs.espressif.com/projects/esp-idf/en/stable/esp32c6/api-reference/peripherals/spi_master.html#spi-master-driver). 

I should be able to "extend" the ESP32-C6  RAM using the ESP-IDF framework with things like [heap_caps_malloc_extmem_enable](https://docs.espressif.com/projects/esp-idf/en/stable/esp32/api-reference/system/mem_alloc.html#_CPPv430heap_caps_malloc_extmem_enable6size_t) , etc.

Is this a possible solution or I am taking too far ?

Cheers,

**Comment by igrr** [comment]
Please see https://github.com/espressif/esp-idf/issues/11193, hopefully the comments there will answer your question.

(Note however, Espressif has recently announced the lower-cost ESP32-C61, which will support PSRAM to compensate for the low amount of the internal RAM. When that chip is released, it will be supported by ESP-IDF.)

**Comment by blue-freedom-technologies** [comment]
Understood, thank you @igrr 

And of course the [ESP32-C61](https://www.espressif.com/en/news/ESP32-C61_SoC) will have Quad SPI or Octal SPI, which make the difference for anyone tat needs performance.

Cheers,
