### ISSUE TITLE
LVGL managed component build error (IDFGH-12289)

### ISSUE THREAD

**Issue by mcoracin** [espressif/esp-idf#13329]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v5.1

### Operating System used.

Linux

### How did you build your project?

Command line with idf.py

### If you are using Windows, please specify command line type.

None

### What is the expected behavior?

I'm trying to compile my project in which I'm using LVGL as a managed components.
It is building with no error when using the default options, but I'm trying to enable verbose LVGL logs (enabled with menuconfig), and I get the following build error now:

```
../managed_components/lvgl__lvgl/src/misc/lv_mem.c: In function 'lv_mem_buf_get':
../managed_components/lvgl__lvgl/src/misc/lv_mem.c:280:15: error: format '%d' expects argument of type 'int', but argument 6 has type 'uint32_t' {aka 'long unsigned int'} [-Werror=format=]
```

If I modify the source files to fix the warning, I get another error because managed component hash changed.

So is it possible to disable the "warning as error" for the managed components ?

Thank you.

### What is the actual behavior?

I expect to be able to build with verbose logs enabled.

### Steps to reproduce.

1. Step
2. Step
3. Step
...

**Comment by suda-morris** [comment]
> So is it possible to disable the "warning as error" for the managed components ?

Yes.
```cmake
idf_component_get_property(lvgl_lib lvgl__lvgl COMPONENT_LIB)
target_compile_options(${lvgl_lib} PRIVATE "-Wno-format")
```

Background of these build issues: https://docs.espressif.com/projects/esp-idf/en/latest/esp32/migration-guides/release-5.x/5.0/gcc.html#espressif-toolchain-changes
