### ISSUE TITLE
Old/incorrect info in examples/system/deep_sleep/README.md (IDFGH-12305)

### ISSUE THREAD

**Issue by prabbit237** [espressif/esp-idf#13340]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

The README.md in examples/system/deep_sleep has the following:

ULP: Ultra Low Power Coprocessor which can continue to run during deep sleep. This example utilizes the ULP and constantly sample the chip's temperature and trigger a wake up if the chips temperature exceeds ~5 degrees Celsius.

But the actual code in the example files does not have anything about the ULP and waking from deep sleep. That seems to have been removed sometime around release/v5.0.

**Comment by ESP-Marius** [comment]
You're right, seems like we missed this. We'll update the docs to reflect this!
