### ISSUE TITLE
[docs] Incorrect description of esp_event_post_to() on Docs (IDFGH-12311)

### ISSUE THREAD

**Issue by Tinyu-Zhao** [espressif/esp-idf#13346]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

https://docs.espressif.com/projects/esp-idf/zh_CN/v5.1.2/esp32s3/api-reference/system/esp_event.html?highlight=esp_event_post_to#_CPPv417esp_event_post_to23esp_event_loop_handle_t16esp_event_base_t7int32_tPKv6size_t10TickType_t

"This function behaves in the same manner as esp_event_post_to, except the additional specification of the event loop to post the event to."
Should be 
"This function behaves in the same manner as esp_event_post, except the additional specification of the event loop to post the event to."

<img width="649" alt="image" src="https://github.com/espressif/esp-idf/assets/44396641/99138ec6-5efe-497a-b5cc-3ff9be093fb5">

**Comment by 0xjakob** [comment]
@Tinyu-Zhao Thanks for noticing this mistake! Our fix should appear soon on master.
