### ISSUE TITLE
logic of CONFIG_SPIRAM_MALLOC_ALWAYSINTERNAL doesn't match its document (IDFGH-12318)

### ISSUE THREAD

**Issue by yyjdelete** [espressif/esp-idf#13353]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

The document says 
```c
if (size < threshold) //use internal RAM
else //use external RAM
```
but the code use `<=` instead, so which one is wrong and what's the expected behavior?

https://github.com/espressif/esp-idf/blob/60a2bf6a68867fd468a250966230a067f8d97ea2/docs/en/api-guides/external-ram.rst?plain=1#L103-L104

https://github.com/espressif/esp-idf/blob/60a2bf6a68867fd468a250966230a067f8d97ea2/components/heap/heap_caps.c#L235-L239

**Comment by 0xjakob** [comment]
@yyjdelete We've created a fix for this which will be available on master soon, thanks for noticing!
