### ISSUE TITLE
[TW#16815] GATTC: Typo in an event name

### ISSUE THREAD

**Issue by rojer** [espressif/esp-idf#1337]
`ESP_GATTC_READ_MUTIPLE_EVT` should be `ESP_GATTC_READ_MULTIPLE_EVT` (missing an `L`).

**Comment by Yulong-espressif** [comment]
@rojer Thanks for suggestion, we have released the v3.0 of the SDK, so we will modified it in the next version.

**Comment by Weijian-Espressif** [comment]
@rojer we have fixed the issue, the commit id is fc5b15173e9c67262492dca375f73b169f8e904c, thanks.

**Comment by rojer** [comment]
https://github.com/espressif/esp-idf/commit/fc5b15173e9c67262492dca375f73b169f8e904c is not a valid commit though

**Comment by Weijian-Espressif** [comment]
sorry, The code has not been synchronized to the github, please try tomorrow.

**Comment by FayeY** [comment]
Done.
