### ISSUE TITLE
mbedtls_ssl_setup error - returns 0x7F00 (IDFGH-12398)

### ISSUE THREAD

**Issue by lekshith** [espressif/esp-idf#13424]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

![image](https://github.com/espressif/esp-idf/assets/162119147/60740a02-e66f-4209-9313-1b10ca3827b5)
it failing with above error code, which points to memory allocation failed from ssl error codes.
I have the following memory heap size during runtime
![image](https://github.com/espressif/esp-idf/assets/162119147/d1bd2f74-621d-47ab-8e9c-0c582d2d3307)
Please suggest how to overcome this issue?

**Comment by mahavirj** [comment]
@lekshith 

Please see guidelines provided in https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/protocols/mbedtls.html#reducing-heap-usage.

Alternatively, you can also enable external memory allocation mode for mbedtls case, please see the config option available here: https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/kconfig.html#config-mbedtls-mem-alloc-mode
