### ISSUE TITLE
Accidentally writing to file system when printing to stdout with ESP_LOGx() (IDFGH-12416)

### ISSUE THREAD

**Issue by voedipus** [espressif/esp-idf#13439]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Steps to reproduce:
1. Select "None" as channel for console output 
![image](https://github.com/espressif/esp-idf/assets/132163562/3c355a3e-a68d-4047-b9f4-141c089b91c1)
2. Open a file in file system with **fopen()** and see that it is opened with fileno = 0 (with debugging)
3. Call fopen() once again(to open stdout with fileno = 1)
4. Print something to stdout with ESP_LOGx()
5. Read second opened file and see that ESP_LOGx() write there

If channel for console output is UART0 then fopen() opens first file with fileno = 3

**Comment by igrr** [comment]
@voedipus Would you mind posting the code you used in these two steps?

> Open a file in file system with fopen() and see that it is opened with fileno = 0 (with debugging)
> Call fopen() once again(to open stdout with fileno = 1)

Could you also mention the version of ESP-IDF you are using?

**Comment by voedipus** [comment]
@igrr I used example project named "file_serving" with minor change in app_main:
```c
void app_main(void)
{
    ESP_LOGI(TAG, "Starting example");
    ESP_ERROR_CHECK(nvs_flash_init());
    ESP_ERROR_CHECK(esp_netif_init());
    ESP_ERROR_CHECK(esp_event_loop_create_default());

    /* Initialize file storage */
    const char* base_path = "/data";
    ESP_ERROR_CHECK(example_mount_storage(base_path));

    /* This helper function configures Wi-Fi or Ethernet, as selected in menuconfig.
     * Read "Establishing Wi-Fi or Ethernet Connection" section in
     * examples/protocols/README.md for more information about this function.
     */
    ESP_ERROR_CHECK(example_connect());

    /* Start the file server */
    ESP_ERROR_CHECK(example_start_file_server(base_path));
    ESP_LOGI(TAG, "File server started");
    FILE* first = NULL;
    first = fopen("/data/test1.txt", "w");
    FILE* second = NULL;
    second = fopen("/data/test2.txt", "w");

    while (1){
        ESP_LOGE(TAG, "Is this written to FS?");
        vTaskDelay(200);
    }
}
```

As you can see I open 2 files(test1.txt and test2.txt) and write to stdout using ESP_LOGE()
![image](https://github.com/espressif/esp-idf/assets/132163562/312e3b97-1195-4e17-b8f7-c9ca47875882)

There were no explicit writes to test2.txt, but it's size is more than 0

Contents of the test2.txt file
![image](https://github.com/espressif/esp-idf/assets/132163562/e752c3ba-b0f3-4bda-bf90-478fc9f53d01)
```

**Comment by haberturdeur** [comment]
The issue seems to be that vfs doesn't reserve file descriptors 0 (STDIN), 1(STDOUT) and 2(STDERR):
So when the second file gets open it gets fd 1. Then vprintf in ESP_LOGX assumes that fd 1 is STDOUT, and writes to it...
![image](https://github.com/espressif/esp-idf/assets/30172420/afc205c5-c3b2-4620-9f07-0dc0f5859821)
