### ISSUE TITLE
esp_http_client_set_url() parse failure (IDFGH-12440)

### ISSUE THREAD

**Issue by espradio** [espressif/esp-idf#13459]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

http://croonerradio_classicgold.ice.infomaniak.ch/croonerradio-classicgold-midfi.mp3 URL fails on esp_http_client_set_url()
with ESP_ERR_INVALID_ARG. However, it is a valid URL.

**Comment by espradio** [comment]
Similar issue with https://amorfm_192.streampartner.nl/stream

**Comment by hmalpani** [comment]
Hello @espradio 
http_parser does not support **"_"** i.e **underscore** character in host name part of the URL by default. This is the reason you are getting the error while calling `esp_http_client_set_url()` API for setting the URL. You can enable by adding the following in project's top level CMakeList.txt:
```
idf_component_get_property(http_parser http_parser COMPONENT_LIB)
target_compile_definitions(${http_parser} PRIVATE "-DHTTP_PARSER_STRICT=0")
```

Hope it helps.

**Comment by hmalpani** [comment]
Closing this issue. Please feel free to reopen if the issue persists.

**Comment by espradio** [comment]
@hmalpani Thanks it works.
