### ISSUE TITLE
espefuse -h error (IDFGH-12436)

### ISSUE THREAD

**Issue by eiffel31** [espressif/esp-idf#13456]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

$ espefuse.py burn_efuse -h
espefuse.py v4.7.0
usage: espefuse.py burn_efuse [-h]
                              [EFUSE_NAME VALUE] [WR_DIS VALUE] [RD_DIS VALUE] [FLASH_CRYPT_CNT VALUE] [UART_DOWNLOAD_DIS VALUE] [MAC VALUE]
                              [MAC_CRC VALUE] [DISABLE_APP_CPU VALUE] [DISABLE_BT VALUE] [CHIP_PACKAGE_4BIT VALUE] [DIS_CACHE VALUE]
                              [SPI_PAD_CONFIG_HD VALUE] [CHIP_PACKAGE VALUE] [CHIP_CPU_FREQ_LOW VALUE] [CHIP_CPU_FREQ_RATED VALUE]
                              [BLK3_PART_RESERVE VALUE] [CHIP_VER_REV1 VALUE] [CLK8M_FREQ VALUE] [ADC_VREF VALUE] [XPD_SDIO_REG VALUE]
                              [XPD_SDIO_TIEH VALUE] [XPD_SDIO_FORCE VALUE] [SPI_PAD_CONFIG_CLK VALUE] [SPI_PAD_CONFIG_Q VALUE]
                              [SPI_PAD_CONFIG_D VALUE] [SPI_PAD_CONFIG_CS0 VALUE] [CHIP_VER_REV2 VALUE] [VOL_LEVEL_HP_INV VALUE]
                              [WAFER_VERSION_MINOR VALUE] [FLASH_CRYPT_CONFIG VALUE] [CODING_SCHEME VALUE] [CONSOLE_DEBUG_DISABLE VALUE]
                              [DISABLE_SDIO_HOST VALUE] [ABS_DONE_0 VALUE] [ABS_DONE_1 VALUE] [JTAG_DISABLE VALUE] [DISABLE_DL_ENCRYPT VALUE]
                              [DISABLE_DL_DECRYPT VALUE] [DISABLE_DL_CACHE VALUE] [KEY_STATUS VALUE] [SECURE_VERSION VALUE]
                              [MAC_VERSION VALUE] [BLOCK1 VALUE] [BLOCK2 VALUE] [BLOCK3 VALUE] [CUSTOM_MAC_CRC VALUE] [CUSTOM_MAC VALUE]
                              [ADC1_TP_LOW VALUE] [ADC1_TP_HIGH VALUE] [ADC2_TP_LOW VALUE] [ADC2_TP_HIGH VALUE **@@@@@@@@** [[EFUSE_NAME VALUE]
                              [WR_DIS VALUE] [RD_DIS VALUE] [FLASH_CRYPT_CNT VALUE] [UART_DOWNLOAD_DIS VALUE] [MAC VALUE] [MAC_CRC VALUE]
                              [DISABLE_APP_CPU VALUE] [DISABLE_BT VALUE] [CHIP_PACKAGE_4BIT VALUE] [DIS_CACHE VALUE] [SPI_PAD_CONFIG_HD VALUE]
                              [CHIP_PACKAGE VALUE] [CHIP_CPU_FREQ_LOW VALUE] [CHIP_CPU_FREQ_RATED VALUE] [BLK3_PART_RESERVE VALUE]
                              [CHIP_VER_REV1 VALUE] [CLK8M_FREQ VALUE] [ADC_VREF VALUE] [XPD_SDIO_REG VALUE] [XPD_SDIO_TIEH VALUE]
                              [XPD_SDIO_FORCE VALUE] [SPI_PAD_CONFIG_CLK VALUE] [SPI_PAD_CONFIG_Q VALUE] [SPI_PAD_CONFIG_D VALUE]
                              [SPI_PAD_CONFIG_CS0 VALUE] [CHIP_VER_REV2 VALUE] [VOL_LEVEL_HP_INV VALUE] [WAFER_VERSION_MINOR VALUE]
                              [FLASH_CRYPT_CONFIG VALUE] [CODING_SCHEME VALUE] [CONSOLE_DEBUG_DISABLE VALUE] [DISABLE_SDIO_HOST VALUE]
                              [ABS_DONE_0 VALUE] [ABS_DONE_1 VALUE] [JTAG_DISABLE VALUE] [DISABLE_DL_ENCRYPT VALUE] [DISABLE_DL_DECRYPT VALUE]
                              [DISABLE_DL_CACHE VALUE] [KEY_STATUS VALUE] [SECURE_VERSION VALUE] [MAC_VERSION VALUE] [BLOCK1 VALUE]
                              [BLOCK2 VALUE] [BLOCK3 VALUE] [CUSTOM_MAC_CRC VALUE] [CUSTOM_MAC VALUE] [ADC1_TP_LOW VALUE] [ADC1_TP_HIGH VALUE]
                              [ADC2_TP_LOW VALUE] [ADC2_TP_HIGH VALUE ...]

At the point marked with @@@@@@@@:
- ] is missing
- there is 2 [[
- the list of fuse name is repeated
So, each name is listed twice.

**Comment by KonstantinKondrashov** [comment]
Hi @eiffel31!
I improved it, it will be merged soon. The new help is as follows:

```
usage: espefuse.py burn_efuse [-h] [EFUSE_NAME VALUE] [[EFUSE_NAME VALUE] ...]

positional arguments:
  [EFUSE_NAME VALUE]  Name of efuse field and New value pairs to burn. EFUSE_NAME: [WR_DIS, RD_DIS, FLASH_CRYPT_CNT, UART_DOWNLOAD_DIS, MAC, MAC_CRC, DISABLE_APP_CPU, DISABLE_BT, CHIP_PACKAGE_4BIT, DIS_CACHE, SPI_PAD_CONFIG_HD, CHIP_PACKAGE,
                      CHIP_CPU_FREQ_LOW, CHIP_CPU_FREQ_RATED, BLK3_PART_RESERVE, CHIP_VER_REV1, CLK8M_FREQ, ADC_VREF, XPD_SDIO_REG, XPD_SDIO_TIEH, XPD_SDIO_FORCE, SPI_PAD_CONFIG_CLK, SPI_PAD_CONFIG_Q, SPI_PAD_CONFIG_D, SPI_PAD_CONFIG_CS0,
                      CHIP_VER_REV2, VOL_LEVEL_HP_INV, WAFER_VERSION_MINOR, FLASH_CRYPT_CONFIG, CODING_SCHEME, CONSOLE_DEBUG_DISABLE, DISABLE_SDIO_HOST, ABS_DONE_0, ABS_DONE_1, JTAG_DISABLE, DISABLE_DL_ENCRYPT, DISABLE_DL_DECRYPT,
                      DISABLE_DL_CACHE, KEY_STATUS, SECURE_VERSION, MAC_VERSION, BLOCK1, BLOCK2, BLOCK3, CUSTOM_MAC_CRC, CUSTOM_MAC, ADC1_TP_LOW, ADC1_TP_HIGH, ADC2_TP_LOW, ADC2_TP_HIGH].

options:
  -h, --help          show this help message and exit

```
