### ISSUE TITLE
How do I change DNS to STA access Amazon Cloud using esp32 c3 (IDFGH-12448)

### ISSUE THREAD

**Issue by SeanYang-7** [espressif/esp-idf#13464]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Because sometimes I can't connect to the Amazon cloud, I need to change the dns to Google's

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, would you please help provide more details as per [the issue template](https://github.com/espressif/esp-idf/issues/new/choose)? Thanks.

**Comment by SeanYang-7** [comment]
> Thanks for reporting, would you please help provide more details as per [the issue template](https://github.com/espressif/esp-idf/issues/new/choose)? Thanks.
Thank you very much for your reply, I want to set up the dns connection of my device to find Amazon Cloud after connecting to the router, but I don't know how to do that

**Comment by SeanYang-7** [comment]
<img width="557" alt="9e1ecd087e622bd4bf576cb7892beda6" src="https://github.com/espressif/esp-idf/assets/112528246/de20cc07-4e9e-4f02-900b-c297800c610c">
