### ISSUE TITLE
OpenThread joiner not finding commissioner (IDFGH-12459)

### ISSUE THREAD

**Issue by luisyague** [espressif/esp-idf#13475]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### **General issue report**
**Issue Summary:**
Hi, we are initiating the development of a production-ready Thread Border Router device using an ESP32-C6 (ESP32-C6-DevKitC-1-N8) and a second device which uses an ESP32-h2 (also using a devkit) with the esp-idf version release/v5.2. In our testing phase, we encountered several issues, with the primary having inconsistent results when starting the joiner, we are also getting some warnings: 
![image](https://github.com/espressif/esp-idf/assets/76774818/ea945e16-19d6-4594-8192-c7154023d64d)

**ESP32-H2 Behaviour**
I will paste the whole code bellow, as you will see I have also the possibility to use the CLI. The problem is that it is sometimes finding the commissioner, but other times it doesnt. These are the codes both for the joiner and the comissioner

**Result**
```
I (460) app_start: Starting scheduler on CPU0
I (464) main_task: Started on CPU0
I (464) main_task: Calling app_main()
I (474) OPe��I (494) phy: phy_version: 200,0, 1cef4f4, May 22 2023, 11:57:13
I(504) OPENTHREAD:[I] ChildSupervsn-: Timeout: 0 -> 190
I(554) OPENTHREAD:[I] Settings------: Read NetworkInfo {rloc:0x7000, extaddr:aeee34d5b6af6736, role:leader, mode:0x0f, version:4, keyseq:0x0, ...
I(564) OPENTHREAD:[I] Settings------: ... pid:0x4ffde8f, mlecntr:0x3ef, maccntr:0x3e8, mliid:65d209060d1a9a2a}
I (574) ot_esp_node: joiner starting joiner
I (574) ot_esp_node: After joiner start
I (554) main_task: Returned from app_main()
I(5714) OPENTHREAD:[N] MeshForwarder-: Failed to send IPv6 UDP msg, len:56, chksum:0ee1, ecn:no, to:None, sec:no, error:Abort, prio:net
I(5714) OPENTHREAD:[N] MeshForwarder-:     src:[fe80:0:0:0:88f:5749:6a42:ad9c]:19788
I(5724) OPENTHREAD:[N] MeshForwarder-:     dst:[ff02:0:0:0:0:0:0:2]:19788
I (5734) ot_esp_node: Join failed: no network discovered
```

**Source code for the joiner**
```
static void handleJoinerCompleted(otError aError, void* aContext) {
  switch (aError) {
    case OT_ERROR_NONE:
      ESP_LOGI(TAG, "Join succeeded");
      break;
    case OT_ERROR_SECURITY:
      ESP_LOGI(TAG, "Join failed: pskd does not match");
      break;
    case OT_ERROR_NOT_FOUND:
      ESP_LOGI(TAG, "Join failed: no network discovered");
      break;
    case OT_ERROR_RESPONSE_TIMEOUT:
      ESP_LOGI(TAG, "Join failed: timed out");
      break;
    default:
      break;
  }
}
static void otLoopTask(void *aContext) {
  otInstance* instance = esp_openthread_get_instance();

  // Inconfig up
  esp_openthread_lock_acquire(portMAX_DELAY);
  if (otIp6SetEnabled(instance, true) != OT_ERROR_NONE) {
    ESP_LOGE(TAG, "Failed to enable OpenThread IP6 link");
    abort();
  }
  esp_openthread_lock_release();

  ESP_LOGI(TAG, "joiner starting joiner");
  esp_openthread_lock_acquire(portMAX_DELAY);
  otJoinerStart(instance, "J01NME", NULL, NULL, NULL, NULL , NULL, handleJoinerCompleted, (void*) instance);
  ESP_LOGI(TAG, "After joiner start");
  esp_openthread_lock_release();

  for (;;) {
    vTaskDelay(1000 / portTICK_PERIOD_MS);
  }
}

static void otTaskWorker(void *aContext) {
  otInstance* instance = esp_openthread_get_instance();
  esp_openthread_platform_config_t config = {
    .radio_config = ESP_OPENTHREAD_DEFAULT_RADIO_CONFIG(),
    .host_config = ESP_OPENTHREAD_DEFAULT_HOST_CONFIG(),
    .port_config = ESP_OPENTHREAD_DEFAULT_PORT_CONFIG(),
  };

  esp_netif_t *openthread_netif;
  openthread_netif = init_openthread_netif(&config);
  esp_netif_set_default_netif(openthread_netif);

  // Initialize the OpenThread stack
  ESP_ERROR_CHECK(esp_openthread_init(&config));

  otSetStateChangedCallback(instance, &handleOTStateChange, (void*) instance);

  esp_openthread_lock_acquire(portMAX_DELAY);

  (void)otLoggingSetLevel(CONFIG_LOG_DEFAULT_LEVEL);

  // esp_openthread_cli_init();
  // esp_cli_custom_command_init();

  // createConfigNetwork(instance);
  // launchOpenthreadNetwork(instance);

  esp_openthread_lock_release();

  // esp_openthread_cli_create_task();

  // xTaskCreate(TCPThreadServerTask, "TCPThreadServer", 8192, NULL, 4, NULL);
  // xTaskCreate(TCPThreadClientTask, "TCPThreadClient", 8192, NULL, 4, NULL);

  xTaskCreate(otLoopTask, "otTask", 4096, xTaskGetCurrentTaskHandle(), 4, &sOtTask);
  esp_openthread_launch_mainloop();

  esp_netif_destroy(openthread_netif);
  esp_openthread_netif_glue_deinit();
  esp_vfs_eventfd_unregister();
  vTaskDelete(NULL);
}

void flashInit(void) {
  esp_err_t ret = nvs_flash_init();
  if (ret == ESP_ERR_NVS_NO_FREE_PAGES || ret == ESP_ERR_NVS_NEW_VERSION_FOUND) {
    ESP_ERROR_CHECK(nvs_flash_erase());
    ret = nvs_flash_init();
  }
  ESP_ERROR_CHECK(ret);
}

void eventfdInit(void) {
  // Used eventfds:
  // * netif
  // * task queue
  // * border router
  // * radio driver (A native radio device needs a eventfd for radio driver.)
  esp_vfs_eventfd_config_t eventfd_config = {
    .max_fds = 4,
  };
  ESP_ERROR_CHECK(esp_vfs_eventfd_register(&eventfd_config));
}

void app_main(void)
{
  eventfdInit();
  flashInit();

  ESP_ERROR_CHECK(esp_netif_init());
  ESP_ERROR_CHECK(esp_event_loop_create_default());
  xTaskCreate(otTaskWorker, "ot_node_main", 10240, xTaskGetCurrentTaskHandle(), 5, NULL);
}
```

**Source code for commissioner** 
```

TaskHandle_t sOtTask;

static esp_netif_t *init_openthread_netif(const esp_openthread_platform_config_t *config) {
  esp_netif_config_t cfg = ESP_NETIF_DEFAULT_OPENTHREAD();
  esp_netif_t *netif = esp_netif_new(&cfg);
  assert(netif != NULL);
  ESP_ERROR_CHECK(esp_netif_attach(netif, esp_openthread_netif_glue_init(config)));

  return netif;
}

int hex_digit_to_int(char hex) {
  if ('A' <= hex && hex <= 'F') {
    return 10 + hex - 'A';
  }
  if ('a' <= hex && hex <= 'f') {
    return 10 + hex - 'a';
  }
  if ('0' <= hex && hex <= '9') {
    return hex - '0';
  }
  return -1;
}

size_t hex_string_to_binary(const char *hex_string, uint8_t *buf, size_t buf_size) {
  int num_char = strlen(hex_string);

  if (num_char != buf_size * 2) {
    return 0;
  }
  for (size_t i = 0; i < num_char; i += 2) {
    int digit0 = hex_digit_to_int(hex_string[i]);
    int digit1 = hex_digit_to_int(hex_string[i + 1]);

    if (digit0 < 0 || digit1 < 0) {
      return 0;
    }
    buf[i / 2] = (digit0 << 4) + digit1;
  }

  return buf_size;
}

void printDatasetTlvs(otInstance *instance) {
  // Print dataset
  otOperationalDatasetTlvs datasetTlvs;
  otDatasetGetActiveTlvs(instance, &datasetTlvs);
  char datasetString[256];
  for (uint16_t i = 0; i < datasetTlvs.mLength; i++) {
    sprintf(datasetString + strlen(datasetString), "%02x", datasetTlvs.mTlvs[i]);
  }
  ESP_LOGI(TAG, "%s", datasetString);
}

void createConfigNetwork(otInstance *instance) {
  otOperationalDataset dataset;

  if (otDatasetGetActive(instance, &dataset) == OT_ERROR_NONE) {
    ESP_LOGI(TAG, "Already has network, skip configuring OpenThread network.");
  }

  printDatasetTlvs(instance);

  uint16_t network_name_len = strnlen(CONFIG_OPENTHREAD_NETWORK_NAME, OT_NETWORK_NAME_MAX_SIZE + 1);
  assert(network_name_len <= OT_NETWORK_NAME_MAX_SIZE);

  if (otDatasetCreateNewNetwork(instance, &dataset) != OT_ERROR_NONE) {
    ESP_LOGE(TAG, "Failed to create OpenThread network dataset.");
    abort();
  }
  dataset.mChannel = CONFIG_OPENTHREAD_NETWORK_CHANNEL;
  dataset.mComponents.mIsChannelPresent = true;
  dataset.mPanId = CONFIG_OPENTHREAD_NETWORK_PANID;
  dataset.mComponents.mIsPanIdPresent = true;
  memcpy(dataset.mNetworkName.m8, CONFIG_OPENTHREAD_NETWORK_NAME, network_name_len);
  dataset.mComponents.mIsNetworkNamePresent = true;
  if (hex_string_to_binary(CONFIG_OPENTHREAD_NETWORK_EXTPANID, dataset.mExtendedPanId.m8,
        sizeof(dataset.mExtendedPanId.m8)) != sizeof(dataset.mExtendedPanId.m8)) {
    ESP_LOGE(TAG, "Cannot convert OpenThread extended pan id. Please double-check your config.");
    abort();
  }
  dataset.mComponents.mIsExtendedPanIdPresent = true;
  if (hex_string_to_binary(CONFIG_OPENTHREAD_NETWORK_MASTERKEY, dataset.mNetworkKey.m8,
        sizeof(dataset.mNetworkKey.m8)) != sizeof(dataset.mNetworkKey.m8)) {
    ESP_LOGE(TAG, "Cannot convert OpenThread master key. Please double-check your config.");
    abort();
  }
  dataset.mComponents.mIsNetworkKeyPresent = true;
  if (hex_string_to_binary(CONFIG_OPENTHREAD_NETWORK_PSKC, dataset.mPskc.m8, sizeof(dataset.mPskc.m8)) !=
      sizeof(dataset.mPskc.m8)) {
    ESP_LOGE(TAG, "Cannot convert OpenThread pre-shared commissioner key. Please double-check your config.");
    abort();
  }
  dataset.mComponents.mIsPskcPresent = true;
  otIp6Address prefix;
  otIp6AddressFromString("fd00:db8::", &prefix);
  memcpy(dataset.mMeshLocalPrefix.m8, prefix.mFields.m8, sizeof(prefix.mFields.m8));
  if (otDatasetSetActive(instance, &dataset) != OT_ERROR_NONE) {
    ESP_LOGE(TAG, "Failed to set OpenThread active dataset.");
    abort();
  }
  dataset.mComponents.mIsMeshLocalPrefixPresent = true;

  ESP_LOGI(TAG, "Ends dataset configuration");

  if (otBorderRouterRegister(instance) != OT_ERROR_NONE) {
    ESP_LOGE(TAG, "Failed to register border router.");
    abort();
  }
  return;
}

void launchOpenthreadNetwork(otInstance *instance) {
  if (otIp6SetEnabled(instance, true) != OT_ERROR_NONE) {
    ESP_LOGE(TAG, "Failed to enable OpenThread IP6 link");
    abort();
  }
  if (otThreadSetEnabled(instance, true) != OT_ERROR_NONE) {
    ESP_LOGE(TAG, "Failed to enable OpenThread");
    abort();
  }
  //setStaticIPAddress(instance);
}

static void handleCommissionerStateChanged(otCommissionerState aState, void *aContext) {
  ESP_LOGI(TAG, "Commissioner state changed");
  switch (aState) {
    case OT_COMMISSIONER_STATE_DISABLED:
      ESP_LOGI(TAG, "New state: Disabled");
      break;
    case OT_COMMISSIONER_STATE_PETITION:
      ESP_LOGI(TAG, "New state: Starting");
      break;
    case OT_COMMISSIONER_STATE_ACTIVE:
      ESP_LOGI(TAG, "New state: Active");
      ESP_LOGI(TAG, "Joiner waiting started");
      otCommissionerAddJoiner(esp_openthread_get_instance(), NULL, "J01NME", 600);
      break;
    default:
      ESP_LOGI(TAG, "New state: Unknown");
      break;
  }
}

static void handleJoinerEvent(otCommissionerJoinerEvent aEvent, const otJoinerInfo *aJoinerInfo, const otExtAddress *aJoinerId, void *aContext) {
  ESP_LOGI(TAG, "Joiner event received");

  switch (aEvent){
    case OT_COMMISSIONER_JOINER_START:
      ESP_LOGI(TAG, "OT_COMMISSIONER_JOINER_START");
      break;
    case OT_COMMISSIONER_JOINER_CONNECTED:
      ESP_LOGI(TAG, "OT_COMMISSIONER_JOINER_CONNECTED");
      break;
    case OT_COMMISSIONER_JOINER_FINALIZE:
      ESP_LOGI(TAG, "OT_COMMISSIONER_JOINER_FINALIZE");
      break;
    case OT_COMMISSIONER_JOINER_END:
      ESP_LOGI(TAG, "OT_COMMISSIONER_JOINER_END");
      break;
    case OT_COMMISSIONER_JOINER_REMOVED:
      ESP_LOGI(TAG, "OT_COMMISSIONER_JOINER_REMOVED");      
      break;
  }
}

static void handleOTStateChange(otChangedFlags aFlags, void* aContext) {
  if ((aFlags & OT_CHANGED_THREAD_ROLE) == OT_CHANGED_THREAD_ROLE) {
    ESP_LOGI(TAG, "Thread role changed");
    otDeviceRole role = otThreadGetDeviceRole((otInstance*) aContext);
    if (role != OT_DEVICE_ROLE_DISABLED && role != OT_DEVICE_ROLE_DETACHED) {
      ESP_LOGI(TAG, "Commissioner started");
      esp_openthread_lock_acquire(portMAX_DELAY);
      otCommissionerStart(esp_openthread_get_instance(), &handleCommissionerStateChanged, &handleJoinerEvent, NULL);
      esp_openthread_lock_release();
    }
  }
}

static void otLoopTask(void *aContext) {
  otInstance* instance = esp_openthread_get_instance();

  while(otCommissionerGetState(instance) != OT_COMMISSIONER_STATE_ACTIVE) {
    vTaskDelay(2000 / portTICK_PERIOD_MS);
  }
  ESP_LOGI(TAG, "Commissioner started");

  for (;;) {
    vTaskDelay(1000 / portTICK_PERIOD_MS);
  }
}

static void otTaskWorker(void *aContext) {
  otInstance* instance = esp_openthread_get_instance();
  esp_openthread_platform_config_t config = {
    .radio_config = ESP_OPENTHREAD_DEFAULT_RADIO_CONFIG(),
    .host_config = ESP_OPENTHREAD_DEFAULT_HOST_CONFIG(),
    .port_config = ESP_OPENTHREAD_DEFAULT_PORT_CONFIG(),
  };

  esp_netif_t *openthread_netif;
  openthread_netif = init_openthread_netif(&config);
  esp_netif_set_default_netif(openthread_netif);

  // Initialize the OpenThread stack
  ESP_ERROR_CHECK(esp_openthread_init(&config));

  otSetStateChangedCallback(instance, &handleOTStateChange, (void*) instance);

  // Initialize border routing features
  esp_openthread_lock_acquire(portMAX_DELAY);

  (void)otLoggingSetLevel(CONFIG_LOG_DEFAULT_LEVEL);

  /*
  ESP_ERROR_CHECK(esp_netif_attach(openthread_netif, esp_openthread_netif_glue_init(&config)));

  (void)otLoggingSetLevel(CONFIG_LOG_DEFAULT_LEVEL);
  // esp_openthread_cli_init();

  ESP_ERROR_CHECK(esp_openthread_border_router_init());
  otOperationalDatasetTlvs dataset;
  otError error = otDatasetGetActiveTlvs(esp_openthread_get_instance(), &dataset);
  ESP_ERROR_CHECK(esp_openthread_auto_start((error == OT_ERROR_NONE) ? &dataset : NULL));

  // esp_cli_custom_command_init();
  */
  createConfigNetwork(esp_openthread_get_instance());
  launchOpenthreadNetwork(esp_openthread_get_instance());

  esp_openthread_lock_release();

  // Run the main loop
  // esp_openthread_cli_create_task();
  xTaskCreate(otLoopTask, "otTask", 4096, xTaskGetCurrentTaskHandle(), 4, &sOtTask);
  esp_openthread_launch_mainloop();

  // Clean up
  esp_netif_destroy(openthread_netif);
  esp_openthread_netif_glue_deinit();
  esp_vfs_eventfd_unregister();
  vTaskDelete(NULL);
}

void flashInit(void) {
  esp_err_t ret = nvs_flash_init();
  if (ret == ESP_ERR_NVS_NO_FREE_PAGES || ret == ESP_ERR_NVS_NEW_VERSION_FOUND) {
    ESP_ERROR_CHECK(nvs_flash_erase());
    ret = nvs_flash_init();
  }
  ESP_ERROR_CHECK(ret);
}

void eventfdInit(void) {
  // Used eventfds:
  // * netif
  // * task queue
  // * border router
  // * radio driver (A native radio device needs a eventfd for radio driver.)
  esp_vfs_eventfd_config_t eventfd_config = {
    .max_fds = 4,
  };
  ESP_ERROR_CHECK(esp_vfs_eventfd_register(&eventfd_config));
}

void mdnsInit(void) {
  ESP_ERROR_CHECK(mdns_init());
  ESP_ERROR_CHECK(mdns_hostname_set("esp-ot-br"));
}

void app_main(void)
{
  eventfdInit();
  flashInit();

  ESP_ERROR_CHECK(esp_netif_init());
  ESP_ERROR_CHECK(esp_event_loop_create_default());

  ESP_ERROR_CHECK(example_connect());
  ESP_ERROR_CHECK(esp_wifi_set_ps(WIFI_PS_MIN_MODEM));
  ESP_ERROR_CHECK(esp_coex_wifi_i154_enable());
  esp_openthread_set_backbone_netif(get_example_netif());
  // esp_ot_wifi_netif_init();
  // esp_openthread_set_backbone_netif(esp_netif_get_handle_from_ifkey("WIFI_STA_DEF"));

  mdnsInit();
  xTaskCreate(otTaskWorker, "ot_br_main", 20480, xTaskGetCurrentTaskHandle(), 5, NULL);
}
```

Any guess of which can be the problem? Thank you very much in advance.

**Comment by zwx1995esp** [comment]
> Hello, I am also encountering the same error while using ESP-IDF v5.0.6. My board is ESP32 with the ESP32H2beta2 module.(example: esp-idf/examples/openthread/ot_br)
> 
> > joiner start J01NME
> > Done
> > I(62864) OPENTHREAD:[N] MeshForwarder-: Failed to send IPv6 UDP msg, len:56, chksum:f53b, ecn:no, to:None, sec:no, error:Abort, prio:net
> > I(62864) OPENTHREAD:[N] MeshForwarder-:     src:[fe80:0:0:0:e0f6:b9ce:29d5:ccc1]:19788
> > I(62874) OPENTHREAD:[N] MeshForwarder-:     dst:[ff02:0:0:0:0:0:0:2]:19788
> > Join failed [Security]
> > W(79404) OPENTHREAD:[W] Mle-----------: Failed to process UDP: InvalidState
> > W(108914) OPENTHREAD:[W] Mle-----------: Failed to process UDP: InvalidState
> > W(147234) OPENTHREAD:[W] Mle-----------: Failed to process UDP: InvalidState
> > W(174134) OPENTHREAD:[W] Mle-----------: Failed to process UDP: InvalidState
> > .
> > .
> > .

So did you use the command line or use your own logic? If you use the command line to join a thread network, you can refer to these step:
https://openthread.io/codelabs/esp-openthread-hardware#5

**Comment by Hinalikp** [comment]
> > Hello, I am also encountering the same error while using ESP-IDF v5.0.6. My board is ESP32 with the ESP32H2beta2 module.(example: esp-idf/examples/openthread/ot_br)
> > > joiner start J01NME
> > > Done
> > > I(62864) OPENTHREAD:[N] MeshForwarder-: Failed to send IPv6 UDP msg, len:56, chksum:f53b, ecn:no, to:None, sec:no, error:Abort, prio:net
> > > I(62864) OPENTHREAD:[N] MeshForwarder-:     src:[fe80:0:0:0:e0f6:b9ce:29d5:ccc1]:19788
> > > I(62874) OPENTHREAD:[N] MeshForwarder-:     dst:[ff02:0:0:0:0:0:0:2]:19788
> > > Join failed [Security]
> > > W(79404) OPENTHREAD:[W] Mle-----------: Failed to process UDP: InvalidState
> > > W(108914) OPENTHREAD:[W] Mle-----------: Failed to process UDP: InvalidState
> > > W(147234) OPENTHREAD:[W] Mle-----------: Failed to process UDP: InvalidState
> > > W(174134) OPENTHREAD:[W] Mle-----------: Failed to process UDP: InvalidState
> > > .
> > > .
> > > .
> 
> So did you use the command line or use your own logic? If you use the command line to join a thread network, you can refer to these step: https://openthread.io/codelabs/esp-openthread-hardware#5



I am using command line and tried same command lines which you refereed. But still I am getting:

> dataset pskc 1f8a6515a237085a3c24a388969538fe
Done
> dataset panid 0x70c2
Done
> dataset commit active
Done
> ifconfig up
Done
I (103034) OPENTHREAD: netif up
> eui64
1097bdf0c5c3fcff
Done
> ifconfig up
Done
> joiner start J01NME
Done
> I(175674) OPENTHREAD:[N] MeshForwarder-: Failed to send IPv6 UDP msg, len:56, chksum:5515, ecn:no, to:None, sec:no, error:Abort, prio:net
I(175674) OPENTHREAD:[N] MeshForwarder-:     src:[fe80:0:0:0:d86e:c5b0:f587:9ddb]:19788
I(175684) OPENTHREAD:[N] MeshForwarder-:     dst:[ff02:0:0:0:0:0:0:2]:19788
Join failed [Security]

I am using (esp32s3(ot_br)+esp32h2(ot_rcp) ) as thread border router. And as a joiner I am using esp32h2beta2(ot_cli).

**Comment by zwx1995esp** [comment]
> > > Hello, I am also encountering the same error while using ESP-IDF v5.0.6. My board is ESP32 with the ESP32H2beta2 module.(example: esp-idf/examples/openthread/ot_br)
> > > > joiner start J01NME
> > > > Done
> > > > I(62864) OPENTHREAD:[N] MeshForwarder-: Failed to send IPv6 UDP msg, len:56, chksum:f53b, ecn:no, to:None, sec:no, error:Abort, prio:net
> > > > I(62864) OPENTHREAD:[N] MeshForwarder-:     src:[fe80:0:0:0:e0f6:b9ce:29d5:ccc1]:19788
> > > > I(62874) OPENTHREAD:[N] MeshForwarder-:     dst:[ff02:0:0:0:0:0:0:2]:19788
> > > > Join failed [Security]
> > > > W(79404) OPENTHREAD:[W] Mle-----------: Failed to process UDP: InvalidState
> > > > W(108914) OPENTHREAD:[W] Mle-----------: Failed to process UDP: InvalidState
> > > > W(147234) OPENTHREAD:[W] Mle-----------: Failed to process UDP: InvalidState
> > > > W(174134) OPENTHREAD:[W] Mle-----------: Failed to process UDP: InvalidState
> > > > .
> > > > .
> > > > .
> > 
> > 
> > So did you use the command line or use your own logic? If you use the command line to join a thread network, you can refer to these step: https://openthread.io/codelabs/esp-openthread-hardware#5
> 
> I am using command line and tried same command lines which you recommend . But still I am getting:
> 
> > dataset pskc 1f8a6515a237085a3c24a388969538fe
> > Done
> > dataset panid 0x70c2
> > Done
> > dataset commit active
> > Done
> > ifconfig up
> > Done
> > I (103034) OPENTHREAD: netif up
> > eui64
> > 1097bdf0c5c3fcff
> > Done
> > ifconfig up
> > Done
> > joiner start J01NME
> > Done
> > I(175674) OPENTHREAD:[N] MeshForwarder-: Failed to send IPv6 UDP msg, len:56, chksum:5515, ecn:no, to:None, sec:no, error:Abort, prio:net
> > I(175674) OPENTHREAD:[N] MeshForwarder-:     src:[fe80:0:0:0:d86e:c5b0:f587:9ddb]:19788
> > I(175684) OPENTHREAD:[N] MeshForwarder-:     dst:[ff02:0:0:0:0:0:0:2]:19788
> > Join failed [Security]
> 
> I am using (esp32s3(ot_br)+esp32h2(ot_rcp) ) as thread border router. And as a joiner I am using esp32h2beta2(ot_cli).

So, did you use the latest code? Could you please share the branch you used? Maybe you can have a try with
```
esp-idf: v5.1.3
esp-thread-br: v1.0
```
If you still encounter this issue, please share both the BR and H2 logs.

**Comment by Hinalikp** [comment]
Actually for now, i only have esp32h2beta2 device and esp-idf v5.0 only supports it.  These are the logs:
![BR1](https://github.com/espressif/esp-idf/assets/96226663/a8cf1678-a776-4826-a945-945ce6092ed2)

![BR2](https://github.com/espressif/esp-idf/assets/96226663/ff331ec7-ac19-47ae-97c8-140644564213)

![BR3](https://github.com/espressif/esp-idf/assets/96226663/a1c6d89b-fc3b-4685-be1f-b7a963cd88dd)

![BR4](https://github.com/espressif/esp-idf/assets/96226663/ea7b72a8-3400-425a-b5e1-0e475da44779)

![BR5](https://github.com/espressif/esp-idf/assets/96226663/56740689-b6b5-4db7-b6ae-b59b510a926e)

![joiner](https://github.com/espressif/esp-idf/assets/96226663/2c3b5eaf-4a38-403d-81a9-9a52d36ce87d)

**Comment by zwx1995esp** [comment]
Hi， @Hinalikp , so bad to hear that you only had an esp32h2beta2, this was a preview version and we stopped to support it when IDF v5.1 released...

**Comment by Hinalikp** [comment]
Okay, Thank you for reply.

**Comment by zwx1995esp** [comment]
> Okay, Thank you for reply.

Maybe you can get a MP version of ESP32H2, and play it with the latest IDF. :)

**Comment by zwx1995esp** [comment]
Hi @luisyague Sorry for the delay, for your logs on joiner:
![image](https://github.com/espressif/esp-idf/assets/69466651/46aac1cf-16cf-4ed1-8f06-56abe72e86cd)
From the logs, we can see there is a previous dataset configured in the boards, you need to erase the NVS flash before you want to commission the device.

Second, from your code, I did not see you set the same panid and pskc with the commissioner. In the commissioning process, the joiner and the commissioner should have the same panid and pskc. Panid is used to join the same network, the pskc is used to create the DTLS handshake.

Could you please check and then have a try?

**Comment by luisyague** [comment]
Hi @zwx1995esp, thanks for the reply. They should be the same because they are both configured on the sdkconfig but I will double checkit tomorrow and give you a reply. Thanks!!!

**Comment by chshu** [comment]
@luisyague suppose the issue has been resoved by your side, feel free to reopen if you have any follow up questions.
