### ISSUE TITLE
 DRAM available size decreases (IDFGH-12466)

### ISSUE THREAD

**Issue by gl-chenxiaosheng** [espressif/esp-idf#13481]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Our project use **ESP-IDF: v5.1-dev-6339-gf7b5f31d67-dirty** before, the DRAM available size is 185kB. And the project work fine.
But i chage IDF to tag **ESP-IDF:v5.1.2-dirty**, the DRAM available size is 148kB. And some initialization in our project is fail like ble.

What's the problem? How can I get 185kB in the IDF v5.1.2.

![Snipaste_2024-03-27_19-08-31](https://github.com/espressif/esp-idf/assets/105762715/2df23deb-53ee-4ee9-b8f4-e9c5df154d36)
![Snipaste_2024-03-27_19-08-37](https://github.com/espressif/esp-idf/assets/105762715/f858b790-18fe-40ee-8f29-f2ed79e1269f)

**Comment by ESP-Marius** [comment]
That does indeed sound like big difference. 

You could try using `idf_size.py` to compare the binaries and see where all the extra DRAM went.

See [Measuring-static-size](https://docs.espressif.com/projects/esp-idf/en/stable/esp32/api-guides/performance/size.html#measuring-static-sizes) and [comparing-two-binaries](https://docs.espressif.com/projects/esp-idf/en/stable/esp32/api-guides/performance/size.html#comparing-two-binaries) for more info on how to do this.
