### ISSUE TITLE
ESP32 flash error on PCB

### ISSUE THREAD

**Issue by HuanchengHu** [espressif/esp-idf#1348]
I placed esp32 on PCB and tried to flash it through RX TX and GND wires. I was able to flash two or three times but most of the time I only got random errors like "Response doesn't match the request", "Invalid packet header" and "Fail to target the RAM".  Has somebody encountered the same issue? Thanks!

**Comment by projectgus** [comment]
Hi @HuanchengHu ,

Usually this indicates problems with the hardware supplying power to the chip.

Try some of the things mentioned here: https://github.com/espressif/esptool#troubleshooting

Also, check that you followed the layout recommendations in the datasheet for the ESP32 chip or module you are using. Particularly adequate capacitance.

Reduced the baud rate in esptool.py may help if the hardware performance is marginal.
