### ISSUE TITLE
Boot up time reducing in esp-idf release 4.4 (IDFGH-12484)

### ISSUE THREAD

**Issue by abhinav-embrill** [espressif/esp-idf#13495]
### Is your feature request related to a problem?

I am using esp-idf release 4.4 with ESP32-S3.
Mode of SPI RAM chip in use = Octal
Set RAM clock speed (80MHz clock speed)
The boot logs are off.
I am attaching the sdkconfig for reference. My current boot time is 200 MS. How to reduce this booting time.

### Describe the solution you'd like.

I want to reduce the boot time of my ESP32-S3.

**Comment by ESP-Marius** [comment]
Hi,

We've written a guide on how to [optimize for startup time](https://docs.espressif.com/projects/esp-idf/en/v4.4.7/esp32s3/api-guides/performance/speed.html#improving-startup-time), which should answer your questions.

If you feel like anything is missing then feel free to re-open a ticket with more specific information.

**Comment by abhinav-embrill** [comment]
I have already read and implemented all the mentioned things in the link "optimize for startup time" that you mentioned, but still the bootup time is approximately 200 milliseconds. I want to reduce it further. I am attaching my sdkconfig again in here. Can the bootup time be reduced further or this is the minimum? 
[sdkconfig.txt](https://github.com/espressif/esp-idf/files/14810478/sdkconfig.txt)

**Comment by ESP-Marius** [comment]
From what I can see in your sdkconfig you have not configured all the options mentioned in the guide. Please take another look and consult the example mentioned: https://github.com/espressif/esp-idf/tree/master/examples/system/startup_time
