### ISSUE TITLE
[TW#12280] VFS: Unable to map the whole file system tree using "/"

### ISSUE THREAD

**Issue by nkolban** [espressif/esp-idf#135]
I am finding that I am unable to map the whole file system tree as seen by the Posix APIs using `esp_vfs_register()`.  It appears that if I try and map "/" that returns an error code.  It is as though the `esp_vfs_register()` requires that my mount point be subordinate to root ("/").  I am thinking that this may be too restrictive.  What if I want to use VFS with just a single type of file system (for examples SPIFFS) then I want all paths to map into the SPIFFS file system not just those from a specific prefix.

For example, I want to be able to access `/dir1/file1.txt` and `/dir2/file2.txt` through SPIFFS with both files on the same SPIFFS file system.

**Comment by negativekelvin** [comment]
You have no options to set base path in your code?

**Comment by jmattsson** [comment]
I imagine this is related to the fact the VFS does not support nested mount points, and therefore would break e.g. the `/dev/uart` registration.

**Comment by igrr** [comment]
I can implement nested mount points if there are some use cases for that.

**Comment by rojer** [comment]
i just filed #158 which is related (feel free to dedup) - need to be able to take over the entire vfs.

**Comment by igrr** [comment]
Adding a request from @rojer here: we should support paths which don't start with `/`.

**Comment by rojer** [comment]
fwiw, above is my stab at it.

**Comment by rojer** [comment]
@igrr almost there, but relative paths like `foo` or `conf.json` are not passed to the default VFS.
https://github.com/espressif/esp-idf/pull/726 makes that happen.

**Comment by igrr** [comment]
Good catch, thanks @rojer.
