### ISSUE TITLE
File not being deleted from SPIFFS of ESP32-S3 (IDFGH-12493)

### ISSUE THREAD

**Issue by abhinav-embrill** [espressif/esp-idf#13504]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

I am using ESP32-S3 and I am transferring an image captured by camera through UART. If the image is not transmitted it gets deleted from the SPIFFS using 'remove(file_path)' and 'unlink(file_path)'. But my problem is that the image is not being removed from the SPIFFS. Why?

**Comment by haberturdeur** [comment]
Hi, thank you for the report.
When you remove the file is the file is still accessible using `open()`?

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to inactivity, feel free to reopen with more updates.
