### ISSUE TITLE
generating own CA for AWS IoT and using with subscribe_publish

### ISSUE THREAD

**Issue by shirish47** [espressif/esp-idf#1350]
hi 
I followed above this [link](http://docs.aws.amazon.com/iot/latest/developerguide/device-certs-your-own.html) provided by AWS IoT. I am able to produce all certificates as following image.
![screen shot 2017-12-05 at 5 46 02 pm](https://user-images.githubusercontent.com/6296507/33607212-50561234-d9e6-11e7-8c1d-43797156cd1e.png)
and I have registered CA(rootCA.pem) and Certificate(verificationCert.csr) on AWS IoT after that also generated deviceCert.csr and registered over AWS IoT and attach policy and thing. but I am not sure which files to use? and what format. I can conver t deviceCert.csr to .crt and rename deviceCert.key to private.pem.key and rootCA.pem to aws-root-ca.pem but it does not work. 

out of these which files to use and what format how do I get those formats from this?

I get this 

```
I (1462) wifi: connected with UNICORN, channel 1
I (2182) event: ip: 192.168.1.109, mask: 255.255.255.0, gw: 192.168.1.1
I (2182) subpub: Connecting to AWS...
E (4182) aws_iot: failed! mbedtls_ssl_handshake returned -0x2700
E (4182) aws_iot:     Unable to verify the server's certificate. 
E (4192) subpub: Error(-4) connecting to aofdwnij85jbh.iot.ap-southeast-1.amazonaws.com:8883
E (6402) aws_iot: failed! mbedtls_ssl_handshake returned -0x2700
E (6402) aws_iot:     Unable to verify the server's certificate. 
E (6412) subpub: Error(-4) connecting to aofdwnij85jbh.iot.ap-southeast-1.amazonaws.com:8883
E (8462) aws_iot: failed! mbedtls_ssl_handshake returned -0x2700
E (8462) aws_iot:     Unable to verify the server's certificate. 
E (8472) subpub: Error(-4) connecting to aofdwnij85jbh.iot.ap-southeast-1.amazonaws.com:8883
E (10542) aws_iot: failed! mbedtls_ssl_handshake returned -0x2700
E (10542) aws_iot:     Unable to verify the server's certificate. 
E (10552) subpub: Error(-4) connecting to aofdwnij85jbh.iot.ap-southeast-1.amazonaws.com:8883
I (11442) wifi: pm start, type:0

```

**Comment by projectgus** [comment]
I noticed that you asked this question simultaneously on the forums:
https://esp32.com/viewtopic.php?f=2&t=3832

I'm going to reply to you there instead of here, as I don't think this is an issue in ESP-IDF itself.
