### ISSUE TITLE
Cannot install default firmware and function to ESP32-S3-EYE (IDFGH-12515)

### ISSUE THREAD

**Issue by SamHall** [espressif/esp-idf#13522]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

esp-idf-v5.2.1

### Operating System used.

Windows

### How did you build your project?

Command line with idf.py

### If you are using Windows, please specify command line type.

CMD

### What is the expected behavior?

Following the [instructions ](https://github.com/espressif/esp-who/blob/master/docs/en/get-started/ESP32-S3-EYE_Getting_Started_Guide.md#17-default-firmware-and-function-test)and via various tools, I've not been able to successfully restore the features it shipped with. Instead, after each attempt, the board is no longer recognized as a USB device (Windows / USB connects/disconnects sounds in a loop).

"Each ESP32-S3-EYE board comes with pre-built [default firmware](https://github.com/espressif/esp-who/tree/master/default_bin/esp32-s3-eye) that allows you to test its functions including voice wake-up, voice command recognition, face detection and recognition."

### What is the actual behavior?

I've not been able to successfully restore the features it shipped with. After each attempt, the board is no longer recognized as a USB device (Windows / USB connects/disconnects sounds in a loop).

### Steps to reproduce.

Using \esp-idf-v5.2.1>esptool.py
Erased and uploaded default .bin shown in documentation.

### Build or installation Logs.

```plain
C:\Espressif\frameworks\esp-idf-v5.2.1>esptool.py --chip ESP32-S3 --port COM3 --baud 460800 write_flash -z 0x0 esp32-s3-eye-v2.2-firmware-v0.2.0-en.bin
esptool.py v4.7.0
Serial port COM3
Connecting...
Chip is ESP32-S3 (QFN56) (revision v0.1)
Features: WiFi, BLE, Embedded PSRAM 8MB (AP_3v3)
Crystal is 40MHz
MAC: 34:85:18:8c:44:20
Uploading stub...
Running stub...
Stub running...
Changing baud rate to 460800
Changed.
Configuring flash size...
Flash will be erased from 0x00000000 to 0x00066fff...
Compressed 418768 bytes to 61514...
Wrote 418768 bytes (61514 compressed) at 0x00000000 in 3.2 seconds (effective 1060.2 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting via RTS pin...

C:\Espressif\frameworks\esp-idf-v5.2.1>esptool.py flash_id
esptool.py v4.7.0
Found 1 serial ports
Serial port COM3
Connecting...
Detecting chip type... ESP32-S3
Chip is ESP32-S3 (QFN56) (revision v0.1)
Features: WiFi, BLE, Embedded PSRAM 8MB (AP_3v3)
Crystal is 40MHz
MAC: 34:85:18:8c:44:20
Uploading stub...
Running stub...
Stub running...
Manufacturer: 20
Device: 4017
Detected flash size: 8MB
Flash type set in eFuse: quad (4 data lines)
Hard resetting via RTS pin...

C:\Espressif\frameworks\esp-idf-v5.2.1>
```

**Comment by Indastri** [comment]
duplicate issue https://github.com/espressif/esp-who/issues/288 closing. Also this is most probably HW issue the user was instructed to apply for HW exchange.

Cheers!
