### ISSUE TITLE
pppos example missing (IDFGH-12531)

### ISSUE THREAD

**Issue by hazad** [espressif/esp-idf#13537]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

The pppos_client example is no longer available. Its mentioned in esp modem and other places in documentation. The link is also mentioned in some older tickets, but the link is not longer working. Has it been moved to some other path/repo?

https://github.com/espressif/esp-idf/tree/master/examples/protocols/pppos_client

Example old ticket providing this url:
https://github.com/espressif/esp-lwip/issues/1

**Comment by hazad** [comment]
Found details of new link in esp modem component.

idf.py create-project-from-example "espressif/esp_modem^1.1.0:pppos_client"

**Comment by leeebo** [comment]
@hazad Thanks to the [ESP-IDF Component Manager](https://components.espressif.com/), many components now no longer need to be maintained in ESP-IDF. esp-modem now maintained in https://github.com/espressif/esp-protocols/tree/master/components.
