### ISSUE TITLE
esp_vfs_usb_serial_jtag_use_driver not found on esp32s2

### ISSUE THREAD

**Issue by nopnop2002** [espressif/esp-idf#13576]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v5.2.1-210-gcf7b9bed4c

### Espressif SoC revision.

esp32s2 development board

### Operating System used.

Linux

### How did you build your project?

Command line with CMake

### If you are using Windows, please specify command line type.

None

### Development Kit.

esp32s2 development board

### Power Supply used.

USB

### What is the expected behavior?

esp_vfs_usb_serial_jtag_use_driver found on esp32s2

### What is the actual behavior?

From what I understand, the ESP32S2 has a USB Serial/JTAG Controller Console.
esp_vfs_usb_serial_jtag_use_driver not found on esp32s2

### Steps to reproduce.
build this code on esp2s2
```
#include <stdio.h>
#include "sdkconfig.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "esp_system.h"
#include "esp_spi_flash.h"
#include "nvs_flash.h"

#include "driver/usb_serial_jtag.h"
#include "esp_vfs_usb_serial_jtag.h"
#include "esp_vfs_dev.h"

void app_main(void)
{
    esp_err_t ret;
    ret = nvs_flash_init();
    if (ret == ESP_ERR_NVS_NO_FREE_PAGES || ret == ESP_ERR_NVS_NEW_VERSION_FOUND) {
        ESP_ERROR_CHECK(nvs_flash_erase());
        ret = nvs_flash_init();
    }

    usb_serial_jtag_driver_config_t usb_serial_jtag_config;
    usb_serial_jtag_config.rx_buffer_size = 1024;
    usb_serial_jtag_config.tx_buffer_size = 1024;

    /* Install USB-SERIAL-JTAG driver for interrupt-driven reads and writes */
    ret = usb_serial_jtag_driver_install(&usb_serial_jtag_config);
    if (ret != ESP_OK) {
        return;
    }

    /* Tell vfs to use usb-serial-jtag driver */
    esp_vfs_usb_serial_jtag_use_driver();

}
```

### Debug Logs.

```plain
/home/nop/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20230928/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: /home/nop/rtos/jtag_control_console/main/main.c:29:(.text.app_main+0x48): undefined reference to `esp_vfs_usb_serial_jtag_use_driver'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
ninja failed with exit code 1, output of the command is in the /home/nop/rtos/jtag_control_console/build/log/idf_py_stderr_output_3679878 and /home/nop/rtos/jtag_control_console/build/log/idf_py_stdout_output_3679878
```
```


### More Information.

esp_vfs_usb_serial_jtag_use_driver found on esp32s3/c3/c6

**Comment by suda-morris** [comment]
> From what I understand, the ESP32S2 has a USB Serial/JTAG Controller Console.

Sadly, USB Serial JTAG doesn't exist on ESP32S2.
