### ISSUE TITLE
[Question] Is there a jig / socket adapter for esp32s3 modules? (IDFGH-12585)

### ISSUE THREAD

**Issue by chipweinberger** [espressif/esp-idf#13586]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Is there a jig I can buy or build to program raw esp32s3 modules?

<img width="408" alt="Screen Shot 2022-12-14 at 1 26 09 AM" src="https://github.com/espressif/esp-idf/assets/1863934/4a2b7600-00a1-40f5-9f77-f808cf7880d9">

<img width="408" src="https://github.com/espressif/esp-idf/assets/1863934/2622975f-6cf3-4a73-b3ce-97e57cfa2372">

apologies for asking on github. I've always preferred Github's UI.

**Comment by chipweinberger** [comment]
I've found this for esp32, but nothing for s3

<img width="1098" alt="Screenshot 2024-04-10 at 3 22 10 PM" src="https://github.com/espressif/esp-idf/assets/1863934/0a44f4b3-90f6-40f7-98aa-434aa0303c66">

**Comment by chipweinberger** [comment]
Looking at the pinout, it looks to be *mostly compatible* with s3. Just missing connections for GPIO3 & GPIO45 (which are strapping pins so most people don't use those anyways.)

**esp32:**
<img width="946" alt="Screenshot 2024-04-10 at 3 31 01 PM" src="https://github.com/espressif/esp-idf/assets/1863934/729a17db-217a-4061-81a4-26dc7731c3a4">

**esp32s3:**
<img width="605" alt="Screenshot 2024-04-10 at 3 31 32 PM" src="https://github.com/espressif/esp-idf/assets/1863934/afe0ec39-627d-4fa4-a85d-82fceadb72c5">

**Comment by dobairoland** [comment]
@chipweinberger Here is a link: https://www.espressif.com/en/products/equipment/production-testing-equipment/overview

For example, clicking on the first, you can find the list of compatible modules: https://docs.espressif.com/projects/espressif-esp-dev-kits/zh_CN/latest/other/esp-module-prog-1-r/user_guide.html#id1
