### ISSUE TITLE
Iterating over running tasks (IDFGH-12582)

### ISSUE THREAD

**Issue by hitecSmartHome** [espressif/esp-idf#13583]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

4.4.6 2nd stage bootloader

### Espressif SoC revision.

ESP-32 Wrover-E revision v3.0

### Operating System used.

Windows

### How did you build your project?

VS Code IDE

### If you are using Windows, please specify command line type.

None

### Development Kit.

ESP-32 Wrover-E

### Power Supply used.

External 3.3V

### What is the expected behavior?

loop should iterate over the tasks and should get the information

### What is the actual behavior?

ESP crashes

### Steps to reproduce.

void getTaskInfo() {
    // Take a snapshot of the running tasks
    UBaseType_t uxArraySize = uxTaskGetNumberOfTasks();

    // For computing runtime percentages / task in the future...
    //uxTaskGetSystemState( pxTaskStatusArray, uxArraySize, &ulTotalRunTime );

    for (UBaseType_t i = 0; i < uxArraySize; i++) {
        TaskStatus_t taskStatus;
        vTaskGetInfo((TaskHandle_t)i, &taskStatus, pdTRUE, eInvalid);
        printf("Name: %s\n",taskStatus.pcTaskName);
    }
}

### Debug Logs.

```plain
Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was 
unhandled.

Core  1 register dump:
PC      : 0x40090eac  PS      : 0x00060330  A0      : 0x80187966  A1    
  : 0x3ffdee50  
A2      : 0x00000001  A3      : 0x3ffdee70  A4      : 0x00000001  A5    
  : 0x00000005  
A6      : 0x00000000  A7      : 0x00000044  A8      : 0x00000039  A9    
  : 0x3ffdeda0  
A10     : 0x3f80e814  A11     : 0x3ffdef50  A12     : 0x3ffb14f8  A13   
  : 0x0000ff00  
A14     : 0x00ff0000  A15     : 0xff000000  SAR     : 0x00000011  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x00000031  LBEG    : 0x4008bf0d  LEND    : 0x4008bf1d  LCOUNT  : 0xfffffffe  


Backtrace: 0x40090ea9:0x3ffdee50 0x40187963:0x3ffdee70 0x401879d2:0x3ffdeed0 0x40187a53:0x3ffdef00 0x4016a2c4:0x3ffdef50 0x401a6243:0x3ffdefe0 0x401a6a7e:0x3ffdf040 0x401d274a:0x3ffdf0c0 0x401d13f3:0x3ffdf100 0x401d1c8a:0x3ffdf1b0 0x401d05e0:0x3ffdf1d0 0x40274eee:0x3ffdf1f0 0x401d0705:0x3ffdf210

  #0  0x40090ea9:0x3ffdee50 in vTaskGetInfo at C:\Users\Pc\.platformio\packages\framework-espidf@3.40406.240122\components\freertos/tasks.c:4298 (discriminator 4)
  #1  0x40187963:0x3ffdee70 in Sys::getTaskInfo(ArduinoJson::V700PB2::JsonArray&) at src/System/SystemInfo.cpp:132




ELF file SHA256: 7d4dd8fcce8ae18e
```

### More Information.

I want to get raw task data like state,priority, run time in percentages.
I don't want to print it to serial, I want to send it.

The crash is on this line `vTaskGetInfo((TaskHandle_t)i, &taskStatus, pdTRUE, eInvalid);`
Maybe I have to retrive the `TaskHandle_t` differently?

**Comment by hitecSmartHome** [comment]
Yeah, i think i figured it out meanwhile, Thank you very much.

```cpp
void TaskInfo::get() {
    UBaseType_t uxArraySize;
    TaskStatus_t *taskStatusArray;
    uint32_t ulTotalRunTime,ulStatsAsPercentage;
    uxArraySize = uxTaskGetNumberOfTasks();
    taskStatusArray = (TaskStatus_t *)pvPortMalloc(uxArraySize * sizeof(TaskStatus_t));
    if (taskStatusArray != NULL) {
        uxArraySize = uxTaskGetSystemState(taskStatusArray, uxArraySize, &ulTotalRunTime);
        ulTotalRunTime /= 100UL;

        for (UBaseType_t i = 0; i < uxArraySize; i++) {
            ulStatsAsPercentage = taskStatusArray[i].ulRunTimeCounter / ulTotalRunTime;
            printf("Name: %s\n",taskStatusArray[i].pcTaskName);
            printf("Run time percentage: %d\n",ulStatsAsPercentage);
        }

        vPortFree(taskStatusArray);
    }
}
```

**Comment by ESP-Marius** [comment]
Did you take a look [freertos/real_time_stats example](https://github.com/espressif/esp-idf/tree/master/examples/system/freertos/real_time_stats)? It seems to be something close to what you are trying to achieve.

**Comment by hitecSmartHome** [comment]
Yeah, it is very similar. I want to build a UI for this to show the system load. I gather memory information, firmware info and task statuses. I don't know if my calculation is right regarding the run time percentage / task. I will take a look at your link. Thank you very much!

**Comment by hitecSmartHome** [comment]
I'm really surprised that there is no library for this.
We have to craft our own solution but it is the same on every esp32.

**Comment by KaeLL** [comment]
I suspect most of us working on non-trivial projects have this in some way, shape or form.

**Comment by SoucheSouche** [comment]
Hi @hitecSmartHome, I will close this ticket since your initial request was answered.
