### ISSUE TITLE
Timer synchronise with zero crossing

### ISSUE THREAD

**Issue by Rajkumar181** [espressif/esp-idf#1359]
Hi,
I am trying to perform dimming of AC light by synchronising timer with zero crossing detector.please some buddy suggest me if already done, something like this done before .

**Comment by igrr** [comment]
Hello, please use esp32.com forum when seeking such advice, rather than this issue tracker. I would suggest looking into PCNT and MCPWM peripherals, but the details are best discussed on the forum.

**Comment by Rajkumar181** [comment]
Thanks for suggestion ..
