### ISSUE TITLE
Bluetooth HFP Audio Gate PCM waveform mode I2S (esp-idf-v5.2) (IDFGH-12609)

### ISSUE THREAD

**Issue by Ageofenigma** [espressif/esp-idf#13607]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

I want to use PCM mode in the I2S interface for Bluetooth HFP Audio Gate Example to be a slave for SIMCom modem.  Simcom supports only PCM waveform mode ( 256 kHz clock, mono, short 16 bit ). Is it possible to rebuild lib to be able to use this mode? (esp-idf-v5.2)

**Comment by esp-qing** [comment]
OK, I will send you the lib file later.

**Comment by esp-qing** [comment]
Hi, according to your requirements _[256 kHz clock, mono, short 16 bit],_ this is the corresponding lib file based on idf version v5.2.
[libbtdm_app.zip](https://github.com/espressif/esp-idf/files/14978118/libbtdm_app.zip)
The requirement about slave role can be configured in esp-idf.
If you have any questions, feel free to ask.

**Comment by esp-qing** [comment]
This lib file corresponds to esp-idf version 5.2.1. Could you please confirm which version of esp-idf you are using? You can view the log output from the compilation of the previous lib file.

**Comment by Ageofenigma** [comment]
**idf.py --version** shows ESP-IDF v5.2.1-dirty

**Comment by esp-qing** [comment]
Hi, this is the new lib file corresponding to idf version 5.2.1(commit a322e6bd), please try again. 
[libbtdm_app.zip](https://github.com/espressif/esp-idf/files/14994843/libbtdm_app.zip)

**Comment by Ageofenigma** [comment]
It works thanks, but I figured out that the SimCom clock is 2048 KHz and looks like this:
![SIMCOM_PCM](https://github.com/espressif/esp-idf/assets/48919030/bf0d7d5c-258f-4c20-9a62-49c0fac95ec1)
Could you change it to 2048 KHz clock? Will it work for such a waveform?

**Comment by Ageofenigma** [comment]
Is it possible to rebuild it to 2048 KHz clock?

**Comment by esp-qing** [comment]
Hi, the default synchronization clock of esp-idf is 8kHZ, and the default data clock is 256kHZ. I guess the clock you want to modify is the data clock.
There has never been a requirement to modify the clock before.  Sorry, after trying, It cannot be directly modified to 2048kHZ at the moment and It will take some time to improve this feature. Maybe you can try modifying the SimCom clock?
If you have any further questions please feel free to ask.

**Comment by Ageofenigma** [comment]
Hi, with new firmware switched simcom to a standart I2S mode, but it generates data only for one channel, ESP32 doesn't accept it, what can you advise? ![i2s](https://github.com/espressif/esp-idf/assets/48919030/adf44608-6259-4e91-b193-2aef73482489)

**Comment by Ageofenigma** [comment]
Could you enable mono mode so data comes when the SYNC signal is low?
