### ISSUE TITLE
SSE Server-Sent-Events Example (IDFGH-12605)

### ISSUE THREAD

**Issue by CharlesMcBaker** [espressif/esp-idf#13603]
### Is your feature request related to a problem?

I tried creating **Server-Sent-Events SSE** from the examples withouth any succes.

**Server-Sent Events (SSE)** is a [server push](https://en.wikipedia.org/wiki/Server_push) technology enabling a client to receive automatic updates from a server via an HTTP connection, and describes how servers can initiate data transmission towards clients once an initial client connection has been established. 

They are commonly used to send message updates or continuous data streams to a browser client and designed to enhance native, cross-browser streaming through a JavaScript API called EventSource, through which a client requests a particular URL in order to receive an event stream. 

### Describe the solution you'd like.

**An Example**, how to open a connection, and async listen for data with a callback that is trigger once new data arrives that the server is sending. The current examples are too blury as a starting point.

I think it's a great feature, and its supported by firebase.

### Describe alternatives you've considered.

Tried modifying the examples with no succes.

### Additional context.

Creates the ability for serverless IoT unidirectional communication Server->ESP32

**Comment by shraiwi** [comment]
How did you end up implementing it? I'm currently trying to use SSE as well.

**Comment by AdityaHPatwardhan** [comment]
Hi @CharlesMcBaker Thanks for the issue.
Based on your comment you have already successfully implemented the example.
Is it possible for you to share your code by raising a pull request in esp-idf.
It would be helpful for others who are interested in the same feature.
You can follow the [guidelines](https://docs.espressif.com/projects/esp-idf/en/stable/esp32/contribute/index.html) for contributing to esp-idf. Please let me know if you need any help for raising up a PR.

**Comment by AdityaHPatwardhan** [comment]
@gudvinr, Thanks for your response. 
To share an update from the last time, We have already implemented the SSE handler, the MR is in progress to be merged internally.
Thanks for your inputs.

**Comment by chegewara** [comment]
Hi,
it seems to work nicely, event reconnecting, just i have one question:
- when for some reason connection is lost and data are still pushed to event source request (i am testing with P4 and usb-netif now and i unplug usb cable to simulate connection lost), the data is buffered and sent after reconnecting
- the question is for how long data are buffered, how connection timeout is detected or handled, how to prevent memory issues in such case

Thanks

**Comment by idolpx** [comment]
I'm interested in seeing an example of this implemented too.
