### ISSUE TITLE
Example esp_hid_device EDR can not be found on IPAD (IDFGH-12624)

### ISSUE THREAD

**Issue by jankens** [espressif/esp-idf#13622]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

5.1

### Espressif SoC revision.

ESP32 PICO

### Operating System used.

Windows

### How did you build your project?

Command line with idf.py

### If you are using Windows, please specify command line type.

CMD

### Development Kit.

ESP32-PICO-MINI-02

### Power Supply used.

USB

### What is the expected behavior?

I use example "esp_hid_device" to implement a hid keyboard device, I found that BLE device works well on all host including WIN11, Android Phone, IPhone;  But the EDR device works well only on WIN11 and Android Phone, on IPHONE, the host could not discover the hid device. how can I deal with this problem?

here is the report infomation
const unsigned char keybdReportMap[] = {
                0x05, 0x01,             //     USAGE_PAGE (Generic Desktop)
		0x09, 0x06,             //     USAGE (Keyboard)
		0xa1, 0x01,             //     COLLECTION (Application)

	   	0x85, 0x01,             // Report ID

		0x05, 0x07,             //     USAGE PAGE (Key Codes)
		0x19, 0xe0,             //     USAGE MINIMUM (224)
		0x29, 0xe7,             //     USAGE MAXIMUM (231)
		0x15, 0x00,             //     LOGICAL_MINIMUM (0)
		0x25, 0x01,             //     LOGICAL_MAXIMUM (1)

		0x75, 0x01,             //     REPORT_SIZE (1)
		0x95, 0x08,             //     REPORT_COUNT (8)
		0x81, 0x02,             //     INPUT (Data,Var,Abs); Modifier byte

		0x95, 0x01,             //     REPORT_COUNT (1)
		0x75, 0x08,             //     REPORT_SIZE (8)
		0x81, 0x01,             //     INPUT (Constant); Reserved byte

		0x95, 0x05,             //     REPORT_COUNT (5)
		0x75, 0x01,             //     REPORT_SIZE (1)
		0x05, 0x08,             //     USAGE PAGE (Page# for LEDs)
		0x19, 0x01,             //     USAGE MINIMUM (1)
		0x29, 0x05,             //     USAGE MAXIMUM (5)
		0x91, 0x02,             //     OUTPUT (Data, Variable, Absolute); LED report

		0x95, 0x01,             //     REPORT_COUNT (1)
		0x75, 0x03,             //     REPORT_SIZE (3)
		0x91, 0x01,             //     OUTPUT (Constant); LED report padding

		0x95, 0x06,             //     REPORT_COUNT (6)
		0x75, 0x08,             //     REPORT_SIZE (8)
		0x15, 0x00,             //     LOGICAL_MINIMUM (0)
		0x26, 0xff, 0x00,  //0x25, 0xff,//0x25, 0x65,             //     LOGICAL_MAXIMUM (101)
		0x05, 0x07,             //     USAGE PAGE (Key Codes)
		0x19, 0x00,             //     USAGE MINIMUM (0)
		0x29, 0xff,             //     USAGE MAXIMUM (101)
		0x81, 0x00,             //     INPUT (Data, Array); Key arrays (6 bytes)  

		0xc0,
};

### What is the actual behavior?

Iphone cannot discover and list the EDR hid device

### Steps to reproduce.

1. Step
2. Step
3. Step
...

**Comment by zhp0406** [comment]
@jankens 
The issue seems to be related to the iPhone. I tried versions 15.5 and 17.4.1 of iOS, and found that version 15.5 works fine, but version 17.4.1 cannot detect ESP32 devices.
What version of iPad are you using? Could you try different versions of iPad or phone devices?

**Comment by jankens** [comment]
@zhp0406 
I am using a iPad with iPadOS 17.4.1. could you please help me to resolve this problem cause IOS will force upgrade to the latest version. and it is not acceptable for us to announce that our product could not be connected by a newer iphone. thanks!

**Comment by zhp0406** [comment]
@jankens 
Yes, we will fix the issue as soon as possible.

**Comment by zhp0406** [comment]
@jankens 
Has your product been released yet, or is it about to be released?

**Comment by zhp0406** [comment]
@jankens 
Can you test with the latest release/v5.1 version?

**Comment by zhp0406** [comment]
We previously fixed compatibility issues with **Android devices** (before iOS 17.4.1 was released), and I tested that the fix also works for iOS 17.4.1 devices. The commit that addressed this in the release/5.1 branch is 17752f970ad2e545e54b4f043b6cb954ad625ac2.

**Comment by jankens** [comment]
@zhp0406 
I am using the latest release/v5.1 version. 

here is the git log message:
commit e088c3766ba440e72268b458a68f27b6e7d63986 (tag: v5.1.1)
Author: Aditya Patwardhan <aditya.patwardhan@espressif.com>
Date:   Mon Aug 21 14:24:40 2023 +0550

    versions: Update version to 5.1.1

commit 8d2dbd461fc7a31b3d3e55ec12149e53130c13f6
Merge: 5d78511eac feecbad7db
Author: Jiang Jiang Jian <jack@espressif.com>
Date:   Fri Aug 18 14:36:25 2023 +0800

    Merge branch 'bugfix/eapol_txdone_cb_issue_v5.1' into 'release/v5.1'

**Comment by zhp0406** [comment]
@jankens 
Version 5.1.1 does not include the fix. Please try the latest version instead.

**Comment by zhp0406** [comment]
It‘s ok，this is my test log：

I (31) boot: ESP-IDF **v5.1.3-467-gc686e23038** 2nd stage bootloader
I (31) boot: compile time Apr 18 2024 16:01:26
I (33) boot: Multicore bootloader
I (37) boot: chip revision: v3.0
I (40) boot.esp32: SPI Speed      : 40MHz
I (45) boot.esp32: SPI Mode       : DIO
I (50) boot.esp32: SPI Flash Size : 2MB
I (54) boot: Enabling RNG early entropy source...
I (60) boot: Partition Table:
I (63) boot: ## Label            Usage          Type ST Offset   Length
I (71) boot:  0 nvs              WiFi data        01 02 00009000 00006000
I (78) boot:  1 phy_init         RF data          01 01 0000f000 00001000
I (85) boot:  2 factory          factory app      00 00 00010000 00100000
I (93) boot: End of partition table
I (97) esp_image: segment 0: paddr=00010020 vaddr=3f400020 size=28404h (164868) map
I (165) esp_image: segment 1: paddr=0003842c vaddr=3ffbdb60 size=04980h ( 18816) load
I (173) esp_image: segment 2: paddr=0003cdb4 vaddr=40080000 size=03264h ( 12900) load
I (178) esp_image: segment 3: paddr=00040020 vaddr=400d0020 size=9a864h (632932) map
I (408) esp_image: segment 4: paddr=000da88c vaddr=40083264 size=15a2ch ( 88620) load
I (457) boot: Loaded app from partition at offset 0x10000
I (458) boot: Disabling RNG early entropy source...
I (469) cpu_start: Multicore app
I (469) cpu_start: Pro cpu up.
I (470) cpu_start: Starting app cpu, entry point is 0x40081384
0x40081384: call_start_cpu1 at /home/zhanghaipeng/esp/esp-idf/components/esp_system/port/cpu_start.c:159

I (0) cpu_start: App cpu up.
I (487) cpu_start: Pro cpu start user code
I (487) cpu_start: cpu freq: 160000000 Hz
I (487) cpu_start: Application information:
I (492) cpu_start: Project name:     esp_hid_device
I (498) cpu_start: App version:      qa-test-v5.1.4-20240412-7-gc686
I (505) cpu_start: Compile time:     Apr 18 2024 16:01:22
I (511) cpu_start: ELF file SHA256:  9fe11aa9c050513b...
I (517) cpu_start: ESP-IDF:          v5.1.3-467-gc686e23038
I (523) cpu_start: Min chip rev:     v0.0
I (528) cpu_start: Max chip rev:     v3.99 
I (533) cpu_start: Chip rev:         v3.0
I (538) heap_init: Initializing. RAM available for dynamic allocation:
I (545) heap_init: At 3FFAFF10 len 000000F0 (0 KiB): DRAM
I (551) heap_init: At 3FFB6388 len 00001C78 (7 KiB): DRAM
I (557) heap_init: At 3FFB9A20 len 00004108 (16 KiB): DRAM
I (563) heap_init: At 3FFC8278 len 00017D88 (95 KiB): DRAM
I (569) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM
I (575) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
I (582) heap_init: At 40098C90 len 00007370 (28 KiB): IRAM
I (590) spi_flash: detected chip: generic
I (593) spi_flash: flash io: dio
W (597) spi_flash: Detected size(8192k) larger than the size in the binary image header(2048k). Using the size in the binary image header.
I (610) coexist: coex firmware version: d96c1e51f
I (616) app_start: Starting scheduler on CPU0
I (620) app_start: Starting scheduler on CPU1
mI (620) main_task: Started on CPU0
I (630) main_task: Calling app_main()
I (650) HID_DEV_DEMO: setting hid gap, mode:3
I (650) BTDM_INIT: BT controller compile version [1175e0a]
I (650) BTDM_INIT: Bluetooth MAC: 34:94:54:b7:0d:9e
I (660) phy_init: phy_version 4791,2c4672b,Dec 20 2023,16:06:06
W (660) phy_init: failed to load RF calibration data (0xffffffff), falling back to full calibration
W (1440) BT_BTM: BTM_BleWriteAdvData, Partial data write into ADV
I (1440) HID_DEV_DEMO: setting ble device
I (1460) HID_DEV_DEMO: setting device name
I (1460) HID_DEV_BLE: START
I (1460) HID_DEV_DEMO: setting cod major, peripheral
I (2460) HID_DEV_DEMO: setting bt device
I (2460) HID_DEV_BT: START OK
I (2460) HID_DEV_BT: Setting to connectable, discoverable
I (2460) main_task: Returned from app_main()
I (73970) HID_DEV_BLE: CONNECT
E (74930) BT_SMP: Value for numeric comparison = 364615
I (74940) ESP_HID_GAP: BLE GAP NC_REQ passkey:364615
E (75860) BT_GATT: gatts_write_attr_perm_check - GATT_INSUF_ENCRYPTION,handle:0x0041
W (76790) BT_SMP: FOR LE SC LTK IS USED INSTEAD OF STK
I (76910) ESP_HID_GAP: BLE GAP KEY type = ESP_LE_KEY_LENC
I (76910) ESP_HID_GAP: BLE GAP KEY type = ESP_LE_KEY_PENC
I (76910) ESP_HID_GAP: BLE GAP KEY type = ESP_LE_KEY_LID
I (77070) ESP_HID_GAP: BLE GAP KEY type = ESP_LE_KEY_PID
I (77130) ESP_HID_GAP: BLE GAP AUTH SUCCESS
I (77130) HID_DEV_DEMO: Send the volume
I (79230) HID_DEV_DEMO: Send the volume
I (81330) HID_DEV_DEMO: Send the volume
I (83430) HID_DEV_DEMO: Send the volume
I (85530) HID_DEV_DEMO: Send the volume
I (87630) HID_DEV_DEMO: Send the volume
I (89730) HID_DEV_DEMO: Send the volume
I (91830) HID_DEV_DEMO: Send the volume
I (93930) HID_DEV_DEMO: Send the volume

**Comment by jankens** [comment]
@zhp0406 
you mean's I need to update to Tag/v5.1.3? let me try and get back to you.

**Comment by zhp0406** [comment]
@jankens 
yes，please test ASAP

**Comment by jankens** [comment]
@zhp0406 
My application combine serval examples and also change some code in component directory, so please give me sometime.

**Comment by zhp0406** [comment]
For your convenience in testing, I have provided the library. You can directly replace the library at the following location: esp-idf/components/esp_phy/lib/esp32/libphy.a
[IDFGH-12624.zip](https://github.com/espressif/esp-idf/files/15021961/IDFGH-12624.zip)

**Comment by jankens** [comment]
@zhp0406 
I build my project in v5.1.3 environment, but got som linker error for missing esp_spp function:

cmd.exe /C "cd . && E:\Espressif\tools\xtensa-esp32-elf\esp-12.2.0_20230208\xtensa-esp32-elf\bin\xtensa-esp32-elf-g++.exe -mlongcalls -Wno-frame-address -Wl,--cref -Wl,--defsym=IDF_TARGET_ESP32=0 -Wl,--Map=E:/Espressif/frameworks/esp-idf-v5.1.1/dev/cino_esp32/build/cino_esp32.map -Wl,--no-warn-rwx-segments -fno-rtti -fno-lto -Wl,--gc-sections -Wl,--warn-common -T esp32.peripherals.ld -T esp32.rom.ld -T esp32.rom.api.ld -T esp32.rom.libgcc.ld -T esp32.rom.newlib-data.ld -T esp32.rom.syscalls.ld -T esp32.rom.newlib-funcs.ld -T memory.ld -T sections.ld @CMakeFiles\cino_esp32.elf.rsp -o cino_esp32.elf  && cd ."
e:/espressif/tools/xtensa-esp32-elf/esp-12.2.0_20230208/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/12.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: esp-idf/main/libmain.a(bt_spp_acceptor_main.c.obj):(.literal.esp_spp_cb+0x38): undefined reference to `esp_spp_vfs_register'
e:/espressif/tools/xtensa-esp32-elf/esp-12.2.0_20230208/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/12.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: esp-idf/main/libmain.a(bt_spp_acceptor_main.c.obj):(.literal.esp_spp_cb+0x3c): undefined reference to `esp_spp_start_srv'
e:/espressif/tools/xtensa-esp32-elf/esp-12.2.0_20230208/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/12.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: esp-idf/main/libmain.a(bt_spp_acceptor_main.c.obj):(.literal.bt_spp_acceptor_app_main+0x50): undefined reference to `esp_spp_register_callback'
e:/espressif/tools/xtensa-esp32-elf/esp-12.2.0_20230208/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/12.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: esp-idf/main/libmain.a(bt_spp_acceptor_main.c.obj):(.literal.bt_spp_acceptor_app_main+0x54): undefined reference to `esp_spp_enhanced_init'
e:/espressif/tools/xtensa-esp32-elf/esp-12.2.0_20230208/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/12.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: esp-idf/main/libmain.a(bt_spp_acceptor_main.c.obj):(.literal.bt_spp_acceptor_app_main+0x58): undefined reference to `esp_spp_data_ind_register_callback'
e:/espressif/tools/xtensa-esp32-elf/esp-12.2.0_20230208/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/12.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: esp-idf/main/libmain.a(bt_spp_acceptor_main.c.obj): in function `esp_spp_cb':
E:/Espressif/frameworks/esp-idf-v5.1.1/dev/cino_esp32/main/bt_spp_acceptor_main.c:136: undefined reference to `esp_spp_vfs_register'
e:/espressif/tools/xtensa-esp32-elf/esp-12.2.0_20230208/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/12.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: E:/Espressif/frameworks/esp-idf-v5.1.1/dev/cino_esp32/main/bt_spp_acceptor_main.c:168: undefined reference to `esp_spp_start_srv'
e:/espressif/tools/xtensa-esp32-elf/esp-12.2.0_20230208/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/12.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: esp-idf/main/libmain.a(bt_spp_acceptor_main.c.obj): in function `bt_spp_acceptor_app_main':
E:/Espressif/frameworks/esp-idf-v5.1.1/dev/cino_esp32/main/bt_spp_acceptor_main.c:296: undefined reference to `esp_spp_register_callback'
e:/espressif/tools/xtensa-esp32-elf/esp-12.2.0_20230208/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/12.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: E:/Espressif/frameworks/esp-idf-v5.1.1/dev/cino_esp32/main/bt_spp_acceptor_main.c:300: undefined reference to `esp_spp_enhanced_init'
e:/espressif/tools/xtensa-esp32-elf/esp-12.2.0_20230208/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/12.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: E:/Espressif/frameworks/esp-idf-v5.1.1/dev/cino_esp32/main/bt_spp_acceptor_main.c:305: undefined reference to `esp_spp_data_ind_register_callback'
e:/espressif/tools/xtensa-esp32-elf/esp-12.2.0_20230208/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/12.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: esp-idf/main/libmain.a(bt_spp_initiator_main.c.obj):(.literal.esp_bt_gap_cb+0x4c): undefined reference to `esp_spp_start_discovery'
e:/espressif/tools/xtensa-esp32-elf/esp-12.2.0_20230208/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/12.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: esp-idf/main/libmain.a(bt_spp_initiator_main.c.obj):(.literal.esp_spp_cb+0x44): undefined reference to `esp_spp_connect'
e:/espressif/tools/xtensa-esp32-elf/esp-12.2.0_20230208/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/12.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: esp-idf/main/libmain.a(bt_spp_initiator_main.c.obj): in function `esp_bt_gap_cb':
E:/Espressif/frameworks/esp-idf-v5.1.1/dev/cino_esp32/main/bt_spp_initiator_main.c:256: undefined reference to `esp_spp_start_discovery'
e:/espressif/tools/xtensa-esp32-elf/esp-12.2.0_20230208/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/12.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: esp-idf/main/libmain.a(bt_spp_initiator_main.c.obj): in function `esp_spp_cb':
E:/Espressif/frameworks/esp-idf-v5.1.1/dev/cino_esp32/main/bt_spp_initiator_main.c:177: undefined reference to `esp_spp_vfs_register'
e:/espressif/tools/xtensa-esp32-elf/esp-12.2.0_20230208/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/12.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: E:/Espressif/frameworks/esp-idf-v5.1.1/dev/cino_esp32/main/bt_spp_initiator_main.c:187: undefined reference to `esp_spp_connect'
e:/espressif/tools/xtensa-esp32-elf/esp-12.2.0_20230208/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/12.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: E:/Espressif/frameworks/esp-idf-v5.1.1/dev/cino_esp32/main/bt_spp_initiator_main.c:195: undefined reference to `esp_spp_connect'
e:/espressif/tools/xtensa-esp32-elf/esp-12.2.0_20230208/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/12.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: esp-idf/main/libmain.a(bt_spp_initiator_main.c.obj): in function `bt_spp_initiator_app_main':
E:/Espressif/frameworks/esp-idf-v5.1.1/dev/cino_esp32/main/bt_spp_initiator_main.c:373: undefined reference to `esp_spp_register_callback'
e:/espressif/tools/xtensa-esp32-elf/esp-12.2.0_20230208/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/12.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: E:/Espressif/frameworks/esp-idf-v5.1.1/dev/cino_esp32/main/bt_spp_initiator_main.c:379: undefined reference to `esp_spp_enhanced_init'
e:/espressif/tools/xtensa-esp32-elf/esp-12.2.0_20230208/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/12.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: E:/Espressif/frameworks/esp-idf-v5.1.1/dev/cino_esp32/main/bt_spp_initiator_main.c:383: undefined reference to `esp_spp_data_ind_register_callback'
e:/espressif/tools/xtensa-esp32-elf/esp-12.2.0_20230208/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/12.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: esp-idf/main/libmain.a(bt_l2cap_main.c.obj):(.literal.esp_hdl_sdp_cb_evt+0x34): undefined reference to `esp_sdp_create_record'
e:/espressif/tools/xtensa-esp32-elf/esp-12.2.0_20230208/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/12.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: esp-idf/main/libmain.a(bt_l2cap_main.c.obj):(.literal.esp_hdl_sdp_cb_evt+0x38): undefined reference to `esp_bt_l2cap_connect'
e:/espressif/tools/xtensa-esp32-elf/esp-12.2.0_20230208/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/12.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: esp-idf/main/libmain.a(bt_l2cap_main.c.obj):(.literal.esp_hdl_bt_l2cap_cb_evt+0x30): undefined reference to `esp_bt_l2cap_vfs_register'
e:/espressif/tools/xtensa-esp32-elf/esp-12.2.0_20230208/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/12.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: esp-idf/main/libmain.a(bt_l2cap_main.c.obj):(.literal.bt_l2cap_app_main+0x4c): undefined reference to `esp_bt_l2cap_register_callback'
e:/espressif/tools/xtensa-esp32-elf/esp-12.2.0_20230208/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/12.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: esp-idf/main/libmain.a(bt_l2cap_main.c.obj):(.literal.bt_l2cap_app_main+0x50): undefined reference to `esp_bt_l2cap_init'
e:/espressif/tools/xtensa-esp32-elf/esp-12.2.0_20230208/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/12.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: esp-idf/main/libmain.a(bt_l2cap_main.c.obj):(.literal.bt_l2cap_app_main+0x54): undefined reference to `esp_sdp_register_callback'
e:/espressif/tools/xtensa-esp32-elf/esp-12.2.0_20230208/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/12.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: esp-idf/main/libmain.a(bt_l2cap_main.c.obj):(.literal.bt_l2cap_app_main+0x58): undefined reference to `esp_sdp_init'
e:/espressif/tools/xtensa-esp32-elf/esp-12.2.0_20230208/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/12.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: esp-idf/main/libmain.a(bt_l2cap_main.c.obj):(.literal.bt_l2cap_app_main+0x5c): undefined reference to `esp_btc_l2cap_data_ind_register_callback'
e:/espressif/tools/xtensa-esp32-elf/esp-12.2.0_20230208/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/12.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: esp-idf/main/libmain.a(bt_l2cap_main.c.obj): in function `esp_hdl_sdp_cb_evt':
E:/Espressif/frameworks/esp-idf-v5.1.1/dev/cino_esp32/main/bt_l2cap_main.c:398: undefined reference to `esp_sdp_create_record'
e:/espressif/tools/xtensa-esp32-elf/esp-12.2.0_20230208/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/12.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: E:/Espressif/frameworks/esp-idf-v5.1.1/dev/cino_esp32/main/bt_l2cap_main.c:410: undefined reference to `esp_bt_l2cap_connect'
e:/espressif/tools/xtensa-esp32-elf/esp-12.2.0_20230208/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/12.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: esp-idf/main/libmain.a(bt_l2cap_main.c.obj): in function `esp_hdl_bt_l2cap_cb_evt':
E:/Espressif/frameworks/esp-idf-v5.1.1/dev/cino_esp32/main/bt_l2cap_main.c:321: undefined reference to `esp_bt_l2cap_vfs_register'
e:/espressif/tools/xtensa-esp32-elf/esp-12.2.0_20230208/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/12.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: E:/Espressif/frameworks/esp-idf-v5.1.1/dev/cino_esp32/main/bt_l2cap_main.c:339: undefined reference to `esp_bt_l2cap_connect'
e:/espressif/tools/xtensa-esp32-elf/esp-12.2.0_20230208/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/12.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: esp-idf/main/libmain.a(bt_l2cap_main.c.obj): in function `filter_inquiry_scan_result':
E:/Espressif/frameworks/esp-idf-v5.1.1/dev/cino_esp32/main/bt_l2cap_main.c:146: undefined reference to `esp_bt_l2cap_connect'
e:/espressif/tools/xtensa-esp32-elf/esp-12.2.0_20230208/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/12.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: esp-idf/main/libmain.a(bt_l2cap_main.c.obj): in function `bt_l2cap_app_main':
E:/Espressif/frameworks/esp-idf-v5.1.1/dev/cino_esp32/main/bt_l2cap_main.c:467: undefined reference to `esp_bt_l2cap_register_callback'
e:/espressif/tools/xtensa-esp32-elf/esp-12.2.0_20230208/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/12.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: E:/Espressif/frameworks/esp-idf-v5.1.1/dev/cino_esp32/main/bt_l2cap_main.c:474: undefined reference to `esp_bt_l2cap_init'
e:/espressif/tools/xtensa-esp32-elf/esp-12.2.0_20230208/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/12.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: E:/Espressif/frameworks/esp-idf-v5.1.1/dev/cino_esp32/main/bt_l2cap_main.c:479: undefined reference to `esp_sdp_register_callback'
e:/espressif/tools/xtensa-esp32-elf/esp-12.2.0_20230208/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/12.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: E:/Espressif/frameworks/esp-idf-v5.1.1/dev/cino_esp32/main/bt_l2cap_main.c:484: undefined reference to `esp_sdp_init'
e:/espressif/tools/xtensa-esp32-elf/esp-12.2.0_20230208/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/12.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: E:/Espressif/frameworks/esp-idf-v5.1.1/dev/cino_esp32/main/bt_l2cap_main.c:488: undefined reference to `esp_btc_l2cap_data_ind_register_callback'
collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
ninja failed with exit code 1, output of the command is in the E:\Espressif\frameworks\esp-idf-v5.1.1\dev\cino_esp32\build\log\idf_py_stderr_output_15400 and E:\Espressif\frameworks\esp-idf-v5.1.1\dev\cino_esp32\build\log\idf_py_stdout_output_15400

which component should I add to the CMakeLists.txt?

**Comment by zhp0406** [comment]
@jankens 
You can directly replace the phy lib with v5.1.1,

**Comment by jankens** [comment]
@zhp0406 
After tracing the inquiry data and process, I found that my iPad with ios17.4.1 could not detect the devices (including other bt devices) which response EIR data for host scanning. the response is something as follow:
2f ff 01 b6  23 19 1c 06  10 01 00 00  05 00 81 2f  d0 0c 09 41  37 38 30 42  54 2d 32 33  31 32 03 03
24 11 01 05  01 07 00 ... (257 bytes)
 
Our device which could be detect by my iPad use Standard Inquiry Mode and just response data as follow.
07 ff 00 56  34 76 45 ce  25 46 36 38  30 42 54 2d  33 34 35 36  00 ... (257 byte)
  
I found that ESP32 can set the Inquiry Mode by the follow function:
tBTM_STATUS BTM_SetInquiryMode (UINT8 mode)
{
    ...
}

but I cound not found how to set the response data without EIR data.
Could you help me about how my app use standard response data for the host inquiry? thanks!!!

**Comment by jankens** [comment]
@boblane1 
Can I set the inquiry mode to BTM_INQ_RESULT_STANDARD and set inquiry data only with bt address and device name?

**Comment by boblane1** [comment]
@jankens device name can only be exposed in extended inquiry response. BTW, BTM_INQ_RESULT_STANDARD is the default inquiry mode. If you don't want to use EIR, you can disable these two macros in `hcidefs.h`.

``` C
#define HCI_LMP_INQ_RSSI_SUPPORTED(x)   (0)
#define HCI_EXT_INQ_RSP_SUPPORTED(x)   (0)
```

**Comment by jankens** [comment]
@boblane1 
I tried to disable the macro macros you mantion, but the inquiry response doesn't change.

**Comment by boblane1** [comment]
@jankens,

The Inquiry_Mode configuration parameter indicates whether inquiry returns Inquiry Result events in the standard format, with RSSI, or with RSSI and extended inquiry response information. This parameter doesn't affect the EIR which the peer device has sent. After disabling `HCI_EXT_INQ_RSP_SUPPORTED`, `BTM_WriteEIR` will not work, so the local EIR will not be set.

**Comment by boblane1** [comment]
Hi @jankens, 

The PC captured standard inquiry response doesn't affect the peer device sending EIR response. As I said before, the Inquiry_Mode configuration parameter only change the format of the returned Inquiry Result events. BTW, is the captured data the raw data of HCI_Inquiry_Result? Can you provide the captured inquiry response data(with EIR) of both ESP32 and CSR8811?

**Comment by jankens** [comment]
@boblane1
do you have any plan to fix the problem about discovering ESP32 HID device on the latest version of IOS? please let me known, thanks a lot!!

**Comment by boblane1** [comment]
@jankens 

We will fix this issue in the second half of the year.
