### ISSUE TITLE
Update BLE appearance values according to bluetooth-SIG  (IDFGH-12628)

### ISSUE THREAD

**Issue by PocketPi** [espressif/esp-idf#13626]
### Is your feature request related to a problem?

I was trying to set the appearance value to 0x0841 (Audio Sink - Standalone Speaker) but got and error with the api: `esp_ble_gap_config_local_icon`

```
esp_err_t icon_err = esp_ble_gap_config_local_icon(0x0841);
if (icon_err) {
    ESP_LOGE(BLE_TAG, "set icon failed, error code = %x", icon_err);
}
```

I dug into the code and saw that only a subset of appearance values are allowed.

https://github.com/espressif/esp-idf/blob/5a40bb8746633477c07ff9a3e90016c37fa0dc0c/components/bt/host/bluedroid/api/esp_gap_ble_api.c#L243

### Describe the solution you'd like.

Either keep the list of allowed values up to date. Or make an interface for using all values

**Comment by zhp0406** [comment]
![image](https://github.com/espressif/esp-idf/assets/131946088/5c17fa73-932c-4850-9d6b-72662f1454fb)
![image](https://github.com/espressif/esp-idf/assets/131946088/3e1ea5c3-cf4f-4a4e-a7da-7afae08a481e)
![image](https://github.com/espressif/esp-idf/assets/131946088/1db7fca6-ab10-4904-8467-bd8c364d4c73)

**Comment by zhp0406** [comment]
@PocketPi 
You're right, we will update it. For your normal usage, you can first add 0x0841.thanks for reporting the issue.

**Comment by zhp0406** [comment]
Fix commit will coming soon:
master d1b47cf1ac67d8b6a0eb3c36de86cc226ecd567e
v5.2 ad67e5de59a4f556d272ce83edd3ce01048395fd
v5.1 b0532006c6ed809e3ec7e72d71a4e437d0484d05
v5.0 2af74e428a0f011b6ed211c53005716e2fb38c83
v4.4 3c9ecf56692b7881ac53a9b27e25cb9040e45550

**Comment by PocketPi** [comment]
Super thanks,

**Comment by Indastri** [comment]
Closing as the issue was solved.

Cheers!
