### ISSUE TITLE
 How to perform OTA with only one partition (IDFGH-12627)

### ISSUE THREAD

**Issue by WOLEN6914183** [espressif/esp-idf#13625]
### Is your feature request related to a problem?

I have checked the ESP documentation and found that OTA updates require two OTA partitions. However, in the actual project, the program size has already reached around 2.5MB. My module's flash space is 4MB. Obviously, according to the documentation, OTA updates are not possible in this scenario. Is it possible to directly flash the new firmware into the current 2.5MB space?

### Describe alternatives you've considered.

I have considered alternative solutions, but the company wants to control costs and cannot use an 8MB flash

**Comment by SolidStateLEDLighting** [comment]
I worked on a fairly large application all last year, and with 22 tasks running AWS IOT, Wifi, Blufi, Camera, RFID, and a few other items, we kept the binary down to 1.8MB.

The right answer might be to embrace the newest framework version you can -- and make sure everything is component oriented and that you're using as many espressif standard techniques as possible -- so you can shrink down your executable.

If you're loading Arduino -- that has to go.   You'll need to shed as many third party libraries that you can and favor native IDF approaches.

I just took a peek at your Github account.   I see you have an open issue with Matter.   I have not used Matter myself, so if you're also using Matter, then there may not be a way to get the build size down.   I expect that Matter would be bulky.
