### ISSUE TITLE
Unable to compile i2c_oled for ESP32-S3-Touch-LCD-1.28 (IDFGH-12633)

### ISSUE THREAD

**Issue by oshmykov-dev** [espressif/esp-idf#13630]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v5.3-dev-3225-g5a40bb8746

### Operating System used.

Windows

### How did you build your project?

Command line with idf.py

### If you are using Windows, please specify command line type.

CMD

### What is the expected behavior?

It should compile

### What is the actual behavior?

error: unknown type name 'esp_lcd_panel_ssd1306_config_t'; did you mean 'esp_lcd_panel_dev_config_t'?

### Steps to reproduce.

1. cd %userprofile%\esp
2. xcopy /e /i %userprofile%\git\esp-idf\examples\peripherals\lcd\i2c_oled i2c_oled
3. idf.py set-target esp32s3
4. idf.py build

### Build or installation Logs.

```plain
map=C:/Users/oshmy/esp/i2c_oled=. -fmacro-prefix-map=C:/Espressif/frameworks/esp-idf-v5.2.1=/IDF -fstrict-volatile-bitfields -fno-jump-tables -fno-tree-switch-conversion -std=gnu17 -Wno-old-style-declaration -MD -MT esp-idf/main/CMakeFiles/__idf_main.dir/i2c_oled_example_main.c.obj -MF esp-idf\main\CMakeFiles\__idf_main.dir\i2c_oled_example_main.c.obj.d -o esp-idf/main/CMakeFiles/__idf_main.dir/i2c_oled_example_main.c.obj -c C:/Users/oshmy/esp/i2c_oled/main/i2c_oled_example_main.c
C:/Users/oshmy/esp/i2c_oled/main/i2c_oled_example_main.c: In function 'app_main':
C:/Users/oshmy/esp/i2c_oled/main/i2c_oled_example_main.c:92:5: error: unknown type name 'esp_lcd_panel_ssd1306_config_t'; did you mean 'esp_lcd_panel_dev_config_t'?
   92 |     esp_lcd_panel_ssd1306_config_t ssd1306_config = {
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |     esp_lcd_panel_dev_config_t
C:/Users/oshmy/esp/i2c_oled/main/i2c_oled_example_main.c:93:9: error: field name not in record or union initializer
   93 |         .height = EXAMPLE_LCD_V_RES,
      |         ^
C:/Users/oshmy/esp/i2c_oled/main/i2c_oled_example_main.c:93:9: note: (near initialization for 'ssd1306_config')
[1319/1327] Building C object esp-idf/espressif__esp_lvgl_port/CMakeFiles/__idf_espressif__esp_lvgl_port.dir/esp_lvgl_port.c.obj
```

**Comment by suda-morris** [comment]
Maybe you copied the example from master branch and build it against your local 5.2.1 IDF. Where the `esp_lcd_panel_ssd1306_config_t` does not exist in esp-idf v5.2.1

**Comment by oshmykov-dev** [comment]
Exactly. I did the "Get Started" guide and then the Hello World example and now I am trying other projects from the esp-idf/examples. Is it something I forgot to configure?
