### ISSUE TITLE
esp_http_client: redirect_counter is never reset, will lead to redirection error if client is reused (IDFGH-12636)

### ISSUE THREAD

**Issue by hurricanefrog** [espressif/esp-idf#13633]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v4.4.7

### Espressif SoC revision.

ESP32

### Operating System used.

Windows

### How did you build your project?

Command line with idf.py

### If you are using Windows, please specify command line type.

PowerShell

### Development Kit.

Custom Board

### Power Supply used.

USB

### What is the expected behavior?

I expect `esp_http_client_perform` to reset `esp_http_client_handle_t.redirect_counter` so I can re-use the http_client handle multiple times.

### What is the actual behavior?

`esp_http_client_handle_t.redirect_counter`  is never reset.

### Steps to reproduce.

1. Create an http client using `esp_http_client_init`
2. Set connection info / URL.
3. Call `esp_http_client_perform` multiple times, with the endpoint returning a 301 / 302 redirect
4. After 10 times, the error will appear. `esp_http_client_perform` fails.

```
E (88888) HTTP_CLIENT: Error, reach max_redirection_count count=10
E (88889) HTTP_CLIENT: Error response
```

### More Information.

I'm not sure if this is intended. I want to avoid creating a new http client handle every time, so I'm reusing the client handle. The endpoint/server always stays the same. I just change the POSTed content using `esp_http_client_set_post_field`.

Use case: POST to a server using `http`, but if the server returns a redirect to https, it should be followed. I guess the "ideal solution" would probably be to use the https URL in the first place, so change it on my code?

**Comment by hmalpani** [comment]
Hello @hurricanefrog 
Thanks for reporting the issue. I have created a patch to fix this issue. Can you please check and let me know if the patch helps you in resolving the issue?
Thanks!
[IDFGH-12636.txt](https://github.com/espressif/esp-idf/files/15197773/IDFGH-12636.txt)
