### ISSUE TITLE
ESP32 with ATECC608A using esp-idf v5.0 up to v5.2 does not build with same config as v4.4.4  (IDFGH-12653)

### ISSUE THREAD

**Issue by dragomat** [espressif/esp-idf#13645]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v5.0 up to v5.2

### Operating System used.

Linux

### How did you build your project?

Command line with idf.py

### If you are using Windows, please specify command line type.

None

### What is the expected behavior?

After updating esp-cryptoauthlib, to build with the same (default) options enabled for IDF v4.4.4.

### What is the actual behavior?

After updating esp-cryptoauthlib, code does not build with the same (default) options enabled for idf v4.4.4, but gives

`error: #error "MBEDTLS_ECP_RESTARTABLE defined, but it cannot coexist with an alternative or PSA-based ECP implementation"`

### Steps to reproduce.

I could use my ATECC608A secure element trhough esp-cryptoauthlib with esp-idf v4.4.4, but as I tried to compile with v5.0 (and even newer versions) the compiler returned `error: #error "MBEDTLS_ECP_RESTARTABLE defined, but it cannot coexist with an alternative or PSA-based ECP implementation"`.

As pointed out alread in issue #11061, with no further follow up, the error is triggered because both `MBEDTLS_ECP_RESTARTABLE`and `MBEDTLS_ECDSA_SIGN_ALT` and `MBEDTLS_ECDSA_VERIFY_ALT` are defined.

Problem disappears if we unset both `BT_NIMBLE_CRYPTO_STACK_MBEDTLS` and `MBEDTLS_ECP_RESTARTABLE` in the menuconfig, but is that the only right approach? Are there any drawbacks in using TinyCrypt instead of MbedTLS in Nimble (considering that they dropped maintenance a couple of months ago)? 

### More Information.

Issue very similar to #11061 which was closed but did not provide any solution to the specific problem.

**Comment by rahult-github** [comment]
[This](https://github.com/espressif/esp-idf/commit/4b4602d84636ce630724300ac74e2d0deb32851f) commit has the fix for the issue.   

Please feel free to reopen, in case issue still observed.
