### ISSUE TITLE
esp32 Reconnect issue (IDFGH-12657)

### ISSUE THREAD

**Issue by fatimatayyab71** [espressif/esp-idf#13649]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

I have programmed the esp32-wroom-32 with BLE-ANCS example code, it can connect with apple device but when I want to reconnect it it do not reconnect automatically, rather i have to forget the device and pair it again. but when i programmed the same code to esp32-s3 it reconnects automatically. 
On the hardware description on espressif site it is written that not recommended for new designs, does it means that it is not compatible with apple devices or something else is the reason?

**Comment by fatimatayyab71** [comment]
Also BLE 4.2 is disabled in default configuration for esp32 while for esp32s3 it is enabled and added during built, how can we add it into the configuration?

**Comment by zhp0406** [comment]
You can use "idf.py menuconfig" to decide whether the 4.2 feature is enabled or not.
(Top) → Component config → Bluetooth → Bluedroid Options
[*] Enable BLE 4.2 features

**Comment by zhp0406** [comment]
What version of IDF are you using?

**Comment by AxelLin** [comment]
@fatimatayyab71 
Could you share your esp-idf version? (git describe --tags)
Could you share the sdkconfig for both esp32 and esp32s3?

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to inactivity, feel free to reopen with more updates or if the issue still happens.
