### ISSUE TITLE
Does the esp32 c3 Bluetooth HID support Lighting And Illumination Page (0x59) (IDFGH-12685)

### ISSUE THREAD

**Issue by SeanYang-7** [espressif/esp-idf#13676]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Does the device support Bluetooth HID? Lighting And Illumination Page (0x59)

**Comment by zhp0406** [comment]
https://github.com/espressif/esp-idf/tree/master/examples/bluetooth/bluedroid/ble/ble_hid_device_demo
