### ISSUE TITLE
GATT server splits write data by 18 bytes

### ISSUE THREAD

**Issue by xarrange** [espressif/esp-idf#1367]
Can be reproduced with GATT server demo and any Adnroid BLE app that allows writing
When ESP_GATTS_WRITE_EVT comes param->write.len=18 and param->write.offset increments by 18

This happens regardless of MTU being set to 517

BTW the MTU topic is not covered by current documentation

**Comment by negativekelvin** [comment]
Some Android devices don't change mtu

**Comment by xarrange** [comment]
Indeed, this is Android issue. 
Have to requestMTU(500) after gatt connected.
