### ISSUE TITLE
How do I configure reports for specific classes in ble_hid_device_demo (IDFGH-12687)

### ISSUE THREAD

**Issue by SeanYang-7** [espressif/esp-idf#13677]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v5.1.1

### Operating System used.

Windows

### How did you build your project?

Command line with Make

### If you are using Windows, please specify command line type.

None

### What is the expected behavior?

The host sends specific class commands

### What is the actual behavior?

The host is not delivered, and the driver is normal

### Steps to reproduce.

1. Step
2. Step
3. Step
...

### More Information.

hid configuration：
[test_HID.txt](https://github.com/espressif/esp-idf/files/15074458/test_HID.txt)

**Comment by weiyuhannnn** [comment]
Hello @SeanYang-7, thanks for using our Espressif product! May I know which chip do you use?

**Comment by SeanYang-7** [comment]
> Hello @SeanYang-7, thanks for using our Espressif product! May I know which chip do you use?

Thanks for your reply. the chip used is ESP32 C3

**Comment by SeanYang-7** [comment]
Hello @weiyuhannnn Is there a solution?

**Comment by zhp0406** [comment]
please ref "hidReportMap" in esp-idf/examples/bluetooth/bluedroid/ble/ble_hid_device_demo/main/hid_device_le_prf.c
and usb hid spec https://www.usb.org/hid

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to inactivity, feel free to reopen if the issue still happens. Thanks.
