### ISSUE TITLE
ESP32-C5 ant ESP-NOW (IDFGH-12695)

### ISSUE THREAD

**Issue by MacWyznawca** [espressif/esp-idf#13685]
Will the ESP32-C5 be able to communicate with other ESP32-C5s in the 5 GHz band using the **ESP-NOW** protocol?
Will **ESP-NOW** work in **5 GHz**?

**Comment by zhangyanjiaoesp** [comment]
@MacWyznawca yes, it has been supported since f0365ba6b5d832a2e5999fda56b89c1f18c02858

**Comment by MacWyznawca** [comment]
Thanks!
