### ISSUE TITLE
Failed to allocate RSA interrupt 261 (IDFGH-12612) (IDFGH-12694)

### ISSUE THREAD

**Issue by lekshith** [espressif/esp-idf#13684]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Hi, 
Sorry for the late response on the issue #13610, I've opened this new one to follow up on that.
I'm not able to cherry-pick the fix you've suggested into my version of ESP. FYI, I'm using esp-idf in visual studio code. I'm getting the following error:
PS C:\CompiledProject\MDC-V2> git cherry-pick -x https://github.com/espressif/esp-idf/commit/4c30f2a4a0229979b4700c6acb34d49705fb6670
fatal: bad revision '4c30f2a'
my git version is up to date and I am in the main branch when I'm trying to commit. I'm quite new to esp-idf, please advise.

**Comment by lekshith** [comment]
![image](https://github.com/espressif/esp-idf/assets/162119147/9892e8f9-b87b-440e-8a92-de2112a1cc40)

**Comment by Harshal5** [comment]
Reopening the older issue to save the context of our discussion.
Closing this one.
