### ISSUE TITLE
Build system uses a lot of undefined make variables

### ISSUE THREAD

**Issue by rojer** [espressif/esp-idf#137]
I am integrating ESP32 IDF build into our own build system, which runs with `--warn-undefined-variables` in `MAKEFLAGS`. I find it very useful and would rather keep it enabled. I also like esp-idf build system, it looks promising, but currently is extremely "--w-u-v dirty" and produces a lot of noise.

Is there a specific reason why you `--warn-undefined-variables` is not used?

**Comment by rojer** [comment]
FWIW, #138 is my attempt at doing it. seems fairly non-invasive, and i think `--w-u-v` help keeps one's sanity while writing make rules.

**Comment by projectgus** [comment]
Closing in favour of ongoing discussion/PR in #138.
