### ISSUE TITLE
xtaskcreate error  (IDFGH-12716)

### ISSUE THREAD

**Issue by cyberumut** [espressif/esp-idf#13701]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

![WhatsApp Image 2024-04-26 at 15 10 14_29554fc5](https://github.com/espressif/esp-idf/assets/105754498/0a1df565-adf6-4d7f-a831-64febf394c1d)

every time I try to start a task I get an insufficient memory error 
I have enough memory space as shown in the picture  4.7MB PSRAM   263BYTE INTERNAL RAM

**Comment by Alvin1Zhang** [comment]
Would you please help share more details as per [the template](https://github.com/espressif/esp-idf/issues/new/choose)? Thanks.

**Comment by ESP-Marius** [comment]
Since PSRAM memory comes with some restrictions, task stacks by default allocate from internal memory. But it is possible provide a PSRAM stack manually with `xTaskCreateStatic` if [CONFIG_SPIRAM_ALLOW_STACK_EXTERNAL_MEMORY](https://docs.espressif.com/projects/esp-idf/en/stable/esp32/api-reference/kconfig.html#config-spiram-allow-stack-external-memory) is enabled.

**Comment by cyberumut** [comment]
> Since PSRAM memory comes with some restrictions, task stacks by default allocate from internal memory. But it is possible provide a PSRAM stack manually with `xTaskCreateStatic` if [CONFIG_SPIRAM_ALLOW_STACK_EXTERNAL_MEMORY](https://docs.espressif.com/projects/esp-idf/en/stable/esp32/api-reference/kconfig.html#config-spiram-allow-stack-external-memory) is enabled.

yes already enabled

**Comment by ESP-Marius** [comment]
> yes already enabled

As I said:
> Since PSRAM memory comes with some restrictions, task stacks by default allocate from internal memory. But it is possible provide a PSRAM stack manually with xTaskCreateStatic

**Comment by ESP-Marius** [comment]
Marking this one as resolved, please reopen it if there is still any outstanding issues.
