### ISSUE TITLE
MQTT V5 empty payload causes broker disconnection (IDFGH-12751)

### ISSUE THREAD

**Issue by HassanSaied** [espressif/esp-idf#13733]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v5.1.1

### Espressif SoC revision.

ESP32-S3

### Operating System used.

Windows

### How did you build your project?

Command line with idf.py

### If you are using Windows, please specify command line type.

PowerShell

### Development Kit.

ESP32-Wrover 1 on Custom board

### Power Supply used.

External 3.3V

### What is the expected behavior?

When MQTT v5 is used, On sending a mqtt publish message with empty payload, an error happens that causes the device to disconnect from the MQTT broker

### What is the actual behavior?

We shouldn't disconnect from the broker, instead an event should be published with the event

### Steps to reproduce.

1. start ESP-IDF MQTT V5 example
2. Comment the line with the unsubscribe to let it run indefinitely
3. Send a message from any other MQTT v5 client with an empty payload

### More Information.

This is caused by this check in mqtt5_client.c
```
     if (*msg_data_len == 0 || *msg_data == NULL) {
        ESP_LOGE(TAG, "%s: mqtt5_get_publish_property_payload() failed", __func__);
        return ESP_FAIL;
    }
```
and removing the check for msg_data_len solves the issue

**Comment by euripedesrocha** [comment]
Hi @HassanSaied this is already fixed in 5.1.2, could you try the more recent version?
