### ISSUE TITLE
Documentation issue on xRingbufferSendAcquire() (IDFGH-12748)

### ISSUE THREAD

**Issue by huming2207** [espressif/esp-idf#13730]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Hi all,

I was trying to use the FreeRTOS ring buffer for one of our storage library's write buffer. I had a look on the API `xRingbufferSendAcquire()` and my understanding for this is like a "malloc" but instead of allocates on heap, it "prepares" a contiguous RAM buffer for the consumer to directly modify (e.g. `memcpy()` from other stuff) on it, and then call `xRingbufferSendComplete()` to tell the ring buffer my modification on that particular piece of buffer is done. 

But the ring buffer documentation below declares `dma_item_t item` instead of `dma_item_t *item`. Have I misunderstood anything?

![image](https://github.com/espressif/esp-idf/assets/4463497/7010a04a-710c-4cd7-88ea-8f40b73228d4)

Regards,
Jackson

**Comment by 0xjakob** [comment]
@huming2207 I think you're right. The documentation looks incorrect. Indeed, the code would give a warning when it is compiled. We'll take a look and fix this.

**Comment by 0xjakob** [comment]
The fix has been merged to our internal code base. It should appear soon on the master branch here on github.

**Comment by huming2207** [comment]
> The fix has been merged to our internal code base. It should appear soon on the master branch here on github.

Nice, thanks for the fix!
