### ISSUE TITLE
Description Failed to configure Feature Reports using ble_hid device _demo

### ISSUE THREAD

**Issue by SeanYang-7** [espressif/esp-idf#13740]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v5.1.1

### Espressif SoC revision.

ESP32 C3

### Operating System used.

Windows

### How did you build your project?

Command line with Make

### If you are using Windows, please specify command line type.

None

### Development Kit.

ESP32-C3-13

### Power Supply used.

USB

### What is the expected behavior?

host sends the Feature Reports command

### What is the actual behavior?

Not received or otherwise

### Steps to reproduce.

1. Step
2. Step
3. Step
...

### More Information.

[ble_hid_device_demo.zip](https://github.com/espressif/esp-idf/files/15209116/ble_hid_device_demo.zip)

**Comment by esp-zhp** [comment]
Has your issue been resolved? What is the peer device?

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, feel free to reopen if the issue still happens. Thanks.
