### ISSUE TITLE
蓝牙不稳定，有时候有，有时候没有，定位不到具体的问题，有时候能发现蓝牙，有时候发下不了蓝牙

### ISSUE THREAD

**Issue by tomsean** [espressif/esp-idf#1374]

**Comment by Yulong-espressif** [comment]
@tomsean Can you describe in some detail the problems it? What is the IDF verstion you using it? What is the demo you are testing? Is the client or server you are testing? Have you use the packet capture tools?

**Comment by FayeY** [comment]
@tomsean , 你好，请问，这个问题目前仍然存在吗？如果仍然存在，能否提供以上信息，以供查证？谢谢！
