### ISSUE TITLE
smart_config (IDFGH-12793)

### ISSUE THREAD

**Issue by LYL14** [espressif/esp-idf#13771]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

espidf使用smart_config例子，手机连接的WIFI为2.4g和5G二合一，使用EspTouch无法给esp32c3配网。

**Comment by zhangyanjiaoesp** [comment]
@LYL14 把 5G关掉试一下

**Comment by zhangyanjiaoesp** [comment]
@LYL14 你的问题还存在吗？

**Comment by Sherry616** [comment]
Thanks for reporting, will close due to short of feedback, feel free to reopen with more updates. 
Thanks for using our Espressif product!
