### ISSUE TITLE
ESP32-C3 CAN Bus (TWAI) Filter (IDFGH-12845)

### ISSUE THREAD

**Issue by procoderer** [espressif/esp-idf#13811]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Can someone help me calculate the acceptance code and acceptance mask for receiving as close to possible only CAN messages with Standard IDs 0x355 and 0x356?

I already tried 
  acceptance code: 0x354 << 21
  acceptance mask: 0x003 << 21
which accepted 0x356 but not 0x355

Thanks

**Comment by wanckl** [comment]
@procoderer You remain only one step to success!

![image](https://github.com/espressif/esp-idf/assets/24585118/a70b352e-2e34-442a-8312-411cb02d72ac)

Refer to programming guide, using single filter mode for std-id, it can filter out not only ID phase but also some data bytes,, 

So if you only care about the ID, you need bypass data check in mask like: `(0x3 << 21) | 0x1FFFFF`

**Comment by nopnop2002** [comment]
@procoderer 
https://www.esp32.com/viewtopic.php?t=16575

**Comment by procoderer** [comment]
> @procoderer You remain only one step to success!
> 
> ![image](https://private-user-images.githubusercontent.com/24585118/332321125-a70b352e-2e34-442a-8312-411cb02d72ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyODM4MzEsIm5iZiI6MTcxNjI4MzUzMSwicGF0aCI6Ii8yNDU4NTExOC8zMzIzMjExMjUtYTcwYjM1MmUtMmUzNC00NDJhLTgzMTItNDExY2IwMmQ3MmFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDA5MjUzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjMDc2NDA2NjgzMTU4NDg2YjhiZGQ2ODc0ZmMxY2MwOTk0ZmUwMzFmOTQ4YjhhNjA4OWFhMDAwNDI0NGYyOWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EVHRoCf28wcGOu9LfcYamBH-drvoFp49dwG1vhMuXJI)
> 
> Refer to programming guide, using single filter mode for std-id, it can filter out not only ID phase but also some data bytes,,
> 
> So if you only care about the ID, you need bypass data check in mask like: `(0x3 << 21) | 0x1FFFFF`

Thank you. This seems to work perfectly. 

Would you say that anytime I want to bypass data check I should also just add on `| 0x1FFFFF`?

**Comment by wanckl** [comment]
@procoderer 
`| 0x1FFFFF` in mask means bypass check for all other bits except ID domain, If you using ext-id or daul-filter mode, you change the bits position and number relatively

**Comment by wanckl** [comment]
@nopnop2002  can you help closing this issue if no more question, thanks

**Comment by nopnop2002** [comment]
@wanckl 

I am not the owner of this issue, so I cannot close it.
