### ISSUE TITLE
bootloader Flashing over OTA (IDFGH-12860)

### ISSUE THREAD

**Issue by diplfranzhoepfinger** [espressif/esp-idf#13824]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Here: 
https://docs.espressif.com/projects/esp-idf/en/release-v4.2/esp32/api-guides/bootloader.html

> The OTA (over the air) update process can flash new apps in the field but cannot flash a new bootloader.

here: 
https://docs.espressif.com/projects/esp-idf/en/stable/esp32s3/api-guides/bootloader.html

> The OTA (over the air) update process can flash new apps in the field but cannot flash a new bootloader.

so, there is no way to update the Bootloader other than using RX/TX Wires ? 

Thanks, 
Franz

**Comment by sudeep-mohanty** [comment]
Hi @diplfranzhoepfinger, We have the OTA update of the bootloader in our roadmap already. You can follow the ticket here https://github.com/espressif/esp-idf/issues/13272
