### ISSUE TITLE
NO_AP_FOUND_IN_AUTHMODE_THRESHOLD while threshold's condition is respected (IDFGH-12863)

### ISSUE THREAD

**Issue by evoon** [espressif/esp-idf#13827]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v5.2.1

### Espressif SoC revision.

ESP32-C6 v0.0

### Operating System used.

Windows

### How did you build your project?

VS Code IDE

### If you are using Windows, please specify command line type.

None

### Development Kit.

ESP32-C6-WROOM-1

### Power Supply used.

USB

### What is the expected behavior?

I expect the ESP32 STA to connect to the AP, as the STA threshold is set to WIFI_AUTH_WPA2 and the AP's authmode is set to >WPA2.

### What is the actual behavior?

I am getting NO_AP_FOUND_IN_AUTHMODE_THRESHOLD, while the authmode.threshold in the STA is greater than AP's one.
No matter what threshold i put in authmode.threshold, the only AP configuration that it will connect to is WPA3

### Steps to reproduce.

1. Set station config's authmode.threshold to anything/don't set it
2. Connect to a wifi network with a security inferior to WPA3

### Debug Logs.

```plain
SCAN RESULT : SSID=TestReseau, AUTHMODE=3

I (241251) http_server: POST /connect.json
I (241261) http_server: ssid: TestReseau, password: Password1!
I (241261) wifi_manager: MESSAGE: ORDER_CONNECT_STA
I (241271) wifi_manager: wifi_sta_config: ssid:TestReseau password:Password1!
I (241281) wifi_manager: wifi_sta_config: sta_authmode 3
I (241291) wifi_manager: wifi_sta_config: RM enabled 1
I (241291) wifi_manager: wifi_sta_config: BTM enabled 1
I (241301) wifi_manager: wifi_sta_config: MBO enabled 1
I (241311) wifi_manager: wifi_sta_config: FT enabled 1
I (241311) wifi_manager: wifi_sta_config: OWE enabled 1
I (241321) wifi_manager: wifi_sta_config: PMF capable enabled 1
I (241331) wifi_manager: wifi_sta_config: PMF required enabled 0
I (241341) wifi_manager: wifi_sta_config: transition_disable enabled 0
I (244171) wifi_manager: WIFI_EVENT_STA_DISCONNECTED
I (244171) wifi_manager: MESSAGE: EVENT_STA_DISCONNECTED with Reason code: 211
I (244181) wifi_manager: MESSAGE: EVENT_STA_DISCONNECTED with rssi: -128
I (244181) wifi_manager: Set STA IP String to: 0.0.0.0
```
```


### More Information.

I have tried setting OWE to 1 in the STA config, and also setting transition_disable to 1 in the STA config.
Ultimately, the STA will only connect to the AP if the security of the AP is set to WPA3

**Comment by vik-gokhale** [comment]
Hi @evoon 
Could you please enable WIFI debug print and share the log?

CONFIG_WPA_DEBUG_PRINT=y
CONFIG_MBEDTLS_DEBUG=y
CONFIG_MBEDTLS_DEBUG_LEVEL_VERBOSE=y
CONFIG_MBEDTLS_DEBUG_LEVEL=4
CONFIG_LOG_DEFAULT_LEVEL_DEBUG=y
CONFIG_LOG_DEFAULT_LEVEL=4
