### ISSUE TITLE
esp_partition_mmap() to read unencrypted partition (IDFGH-12858)

### ISSUE THREAD

**Issue by hyansuper** [espressif/esp-idf#13823]
### Is your feature request related to a problem?

https://docs.espressif.com/projects/esp-idf/en/stable/esp32/security/flash-encryption.html#scope-of-flash-encryption

When flash encryption is enabled, esp_partition_read() can transparently read both encrypted / unencrypted partition, but why can’t esp_partition_mmap()?

Is the doc linked above saying esp_partiton_mmap (which calls spi_flash_mmap) will “decrypt” even unencrypted partition, why so?

**Comment by hyansuper** [comment]
Is there a way to access unencrypted data partition, but I don't want to use esp_partition_read() to read large amount of data, because it involves copying

**Comment by igrr** [comment]
This is a hardware limitation / design choice in all of the currently available ESP32 series chips. When flash encryption is enabled, memory-mapped access to Flash will always go through the hardware decryption engine, regardless of the address. So if you need to access data stored in an unencrypted partition, esp_partition_read is the only available option.

**Comment by hyansuper** [comment]
@igrr thank you for clarifying. 

But I still need access data via memory mapping rather than reading. Maybe a workaround is to add the "encrypted" flag to data partition, so it will decrypt correctly when mmap-ed, right? 

Will it bring any performance issues for accessing large data? For example, an image data

**Comment by igrr** [comment]
No, hardware decryption module can decrypt data as fast as SPI flash will supply it. So there shouldn't be any overhead due to decryption. I think this approach (making the data partition encrypted) should work.

**Comment by hyansuper** [comment]
Great! Did a simple test and it all looks good
