### ISSUE TITLE
The issue about the frequency band wifi (2.4G or 5G) than ESP32 supports (IDFGH-12874)

### ISSUE THREAD

**Issue by NormanLuo** [espressif/esp-idf#13837]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

ESP32 supports to connect with 2.4G frequency band wifi,If a wifi is 2.4G and 5G mixing,Can the ESP32 stably connect with it?

**Comment by NormanLuo** [comment]
Please Every Excellent Egineers Give me a solution

**Comment by MaxwellAlan** [comment]
Hi @NormanLuo 

Yes, if Router's WiFi in mixed 2.4G and 5G mode, as long as the 2.4G band is functioning normally, the ESP32 can work with it.

Thanks.

**Comment by NormanLuo** [comment]
> Hi @NormanLuo
> 
> Yes, if Router's WiFi in mixed 2.4G and 5G mode, as long as the 2.4G band is functioning normally, the ESP32 can work with it.
> 
> Thanks.

MaxwellAlan,Thanks for your answer

**Comment by Sherry616** [comment]
Thanks for reporting, we will close this issue. Feel free to reopen if have more updates. 
Thanks for using our Espressif product!
