### ISSUE TITLE
[TW#17078] ble_ibeacon IBEACON_SENDER (ESP-IDF Pre-release 3.0-rc1)

### ISSUE THREAD

**Issue by Daivyge** [espressif/esp-idf#1383]
HI all;
         Use ble_ibeacon demo code in example (IBEACON_SENDER)  I try to send ibeacon adv. 
        After burning and reboot i can receive the device adv with my iphone, but adv data is empty.
        if I change the company id,then I can see the adv data ,but i know this isn't iBeacon.

**Comment by TianHao-Espressif** [comment]
@Daivyge , Please do not use nRF connect or LightBlue in IOS. I have tried it, the application in IOS cannot recognize the IBeacon. But  nRF connect on Android can recognize it. I have tried with ESP32 IBeacon demo and other device named RadBeacon. I don't know why the application in IOS cannot recognize it, I guess that the company doesn't register IBeacon service with Apple.

**Comment by Daivyge** [comment]
@TianHao-Espressif ,
OK, I get it.
Thanks very much.
