### ISSUE TITLE
Cannot connect to WPA2 networks that have 802.11r enabled (IDFGH-12888)

### ISSUE THREAD

**Issue by evoon** [espressif/esp-idf#13849]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v5.2.1

### Espressif SoC revision.

ESP32-C6 (v0.0)

### Operating System used.

Windows

### How did you build your project?

VS Code IDE

### If you are using Windows, please specify command line type.

PowerShell

### Development Kit.

ESP32-C6-WROOM-1

### Power Supply used.

USB

### What is the expected behavior?

The setup is a TP-LINK router with a WPA2-PSK AES network, with 802.11r support (that I can turn ON/OFF).
Code used is roaming/roaming_11kvr from the 5.2.1 examples, no modifications.
ESP32 has 802.11r enabled in STA config, so I expect it to be able to connect to networks with 802.11r enabled.

### What is the actual behavior?

Actual behavior is very strange : 
- When I let 802.11r off in router's config, the ESP32 connects without problem to the network
- When I enable 802.11r in the router's config, the ESP32 sta disconnects with reason code 211 (NO_AP_FOUND_IN_AUTHMODE_THRESHOLD) which has no sense because the station config is the same and the security of the network has not changed ?

### Steps to reproduce.

- flash roaming_11kvr example
- configure a wifi network in WPA2PSK with 802.11r activated.
- try to connect

Below are the logs with 802.11r enabled or not in the network config
[log_wpa2_80211rOFF.txt](https://github.com/espressif/esp-idf/files/15436028/log_wpa2_80211rOFF.txt)
[log_wpa2_80211rON.txt](https://github.com/espressif/esp-idf/files/15436050/log_wpa2_80211rON.txt)

**Comment by jgujarathi** [comment]
Hi @evoon ,
Thanks for reporting :) We have managed to reproduce this within the roaming example and this issue is already fixed on latest versions of the IDF. Please try some 5.3> based version and this issue should not occur.  The fix for this version is being backported and will be out soon. 

Additionally, please note that there is no roaming_11kvr example on the mentioned tag [(5.2.1)](https://github.com/espressif/esp-idf/tree/v5.2.1/examples/wifi/roaming). The roaming_11kvr example you are using is most probably a remnant of a time you had used a 5.3 > version of IDF. So please do make sure you are building and flashing a application that is consistent.

**Comment by AxelLin** [comment]
@jgujarathi 
5.3 is not a stable release, so we cannot use it.
We probably need to  cherry-pick the fix if it's not yet in v5.2 branch. Could you share the commit for this fix?

**Comment by jgujarathi** [comment]
Hi @AxelLin , 
This is the commit in 5.3 that fixes it c3f1c3fcdef2b14a358e494d5beb9a36a252f0bd. However it is quite unlikely that you will be able to cherry-pick and use this commit as is on release/v5.2.1. We are working on backporting the issue to releases that are facing this issue.

**Comment by AxelLin** [comment]
> Hi @AxelLin ,  We are working on backporting the issue to releases that are facing this issue.

@jgujarathi 
The fix is not yet available in 5.2 branch?

**Comment by kapilkedawat** [comment]
@AxelLin  was merged in https://github.com/espressif/esp-idf/commit/5f8ac78e59bc5aabdda2dfaeb4ab6044a0c35f02
