### ISSUE TITLE
BUG when transmition big data from host to esp32 var L2CAP layer (IDFGH-12886)

### ISSUE THREAD

**Issue by jankens** [espressif/esp-idf#13847]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

esp32 v5.1.3

### Espressif SoC revision.

ESP32-pico

### Operating System used.

Windows

### How did you build your project?

Command line with Make

### If you are using Windows, please specify command line type.

CMD

### Development Kit.

ESP32-pico-mini-02

### Power Supply used.

USB

### What is the expected behavior?

I found a bug when using l2cap to communication for big data transimit.
here is the diff result:
void btc_l2cap_cb_handler(btc_msg_t *msg)
 {
     esp_bt_l2cap_cb_param_t param;
@@ -922,6 +923,7 @@ void btc_l2cap_cb_handler(btc_msg_t *msg)
             }
         }
         osi_mutex_unlock(&l2cap_local_param.l2cap_slot_mutex);
+        post_bt_cradle_data_in();
         break;
     case BTA_JV_L2CAP_CONG_EVT:
         osi_mutex_lock(&l2cap_local_param.l2cap_slot_mutex, OSI_MUTEX_MAX_TIMEOUT);
@@ -957,7 +959,7 @@ void btc_l2cap_cb_handler(btc_msg_t *msg)
                 break; // to do disconnect
             }
             memset(p_data_buf, 0, count + sizeof(BT_HDR));
-            p_data_buf->len = BTA_JvL2capRead(p_data->data_ind.handle, slot->id, p_data_buf->data, count);
+            p_data_buf->len = BTA_JvL2capRead(p_data->l2c_read.handle, slot->id, p_data_buf->data, count);
             if (p_data_buf->len > 0) {
                 fixed_queue_enqueue(slot->rx.queue, p_data_buf, FIXED_QUEUE_MAX_TIMEOUT);
             } else {
@@ -966,6 +968,7 @@ void btc_l2cap_cb_handler(btc_msg_t *msg)
             }
         }
         osi_mutex_unlock(&l2cap_local_param.l2cap_slot_mutex);
+        post_bt_cradle_data_in();
         break;
     case BTA_JV_L2CAP_WRITE_EVT:
         osi_mutex_lock(&l2cap_local_param.l2cap_slot_mutex, OSI_MUTEX_MAX_TIMEOUT);

I think it should use p_data->**l2c_read.handle** instead of p_data->**data_ind.handle** for the BTA_JV_L2CAP_READ_EVT event
please confirm!!.
thanks

### What is the actual behavior?

when transition big data from host to esp32. p_data_buf->len is negative number and data is wrong. 

### Steps to reproduce.

1. Step
2. Step
3. Step
...

**Comment by xiongweichao** [comment]
Hi @jankens , Thank you for reporting the issue. You are right, we will fix this issue as soon as possible.
