### ISSUE TITLE
"5.2.1 Bug in Deinitializing and Reinitializing NimBLE - It fails and doesn't advertise the name anymore." (IDFGH-12891)

### ISSUE THREAD

**Issue by filzek** [espressif/esp-idf#13852]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Nimble Stack has some problem to DEINIT and REINIT, after DEINIT the system cannot re-enable it, using the example as of in spp_server.

`int rc = ble_gap_adv_stop();
          if (rc != 0) {
              printf("Failed to stop advertising: %d\n", rc);
          }

          // Terminate all connections
          struct ble_gap_conn_desc desc;
          uint16_t conn_handle = 0;
          while (ble_gap_conn_find(conn_handle, &desc) == 0) {
               ble_gap_terminate(conn_handle, BLE_ERR_REM_USER_CONN_TERM);
          }

          // Stop the NimBLE host
          int ret = nimble_port_stop();
          if (ret != 0) {
              printf("Failed to stop NimBLE host: %d\n", ret);
              // Handle error appropriately
          } else {
              printf("NimBLE host stopped successfully\n");
          }

          // Deinitialize the NimBLE stack
          ret = nimble_port_deinit();
          if (ret != 0) {
              printf("Failed to deinitialize NimBLE stack: %d\n", ret);
              // Handle error appropriately
          } else {
              printf("NimBLE stack deinitialized successfully\n");
          }`

The function disable entire the NIMBLE correctly.

But when try to enable it again it the BLE Nimble start but doesnt advertise or anything, so, become useless.

Please advise for fix the deinit and reinit it.

**Comment by rahult-github** [comment]
Hi @filzek  ,

Can you please help share more information .

1. What IDF version is being tried ?
2. Which chipset is being tried ? 


Can you have a look at [this](https://github.com/espressif/esp-idf/blob/master/examples/bluetooth/nimble/blecent/main/main.c#L968)   which showcases  stack init / deinit in a loop . I simply modified this example to initiate blecent_scan and put some prints to see if any device is discovered and it works correctly.   
[console_log.txt](https://github.com/espressif/esp-idf/files/15441966/console_log.txt)



If the above is not helpful, may i request you to please share a minimal example code that we can use at our end to reproduce the issue you referring to.

**Comment by filzek** [comment]
> Hi @filzek ,
> 
> Can you please help share more information .
> 
> 1. What IDF version is being tried ?
> 2. Which chipset is being tried ?
> 
> Can you have a look at [this](https://github.com/espressif/esp-idf/blob/master/examples/bluetooth/nimble/blecent/main/main.c#L968) which showcases stack init / deinit in a loop . I simply modified this example to initiate blecent_scan and put some prints to see if any device is discovered and it works correctly. [console_log.txt](https://github.com/espressif/esp-idf/files/15441966/console_log.txt)
> 
> If the above is not helpful, may i request you to please share a minimal example code that we can use at our end to reproduce the issue you referring to.

IDF 5.2.1
commit https://github.com/espressif/esp-idf/commit/70fc0e3037b240aacaf665d2c6f622ad54b510c0 (HEAD -> release/v5.2, origin/release/v5.2)
Merge: https://github.com/espressif/esp-idf/commit/3b15317109087fc30f8b043c51fea0e865c929bb https://github.com/espressif/esp-idf/commit/2fc047d61d1bbb10ba59e242d05487f6b2ee0cc8
Author: Jiang Jiang Jian [jack@espressif.com](mailto:jack@espressif.com)
Date: Mon May 13 22:13:32 2024 +0800

Merge branch 'fix/some_fix_for_openthread_backport_5_2' into 'release/v5.2'

Fix/some fix for openthread (backport v5.2)

See merge request espressif/esp-idf!30796

Chipset ESP32 V3.0 with PSIRAM

**Comment by filzek** [comment]
I will run the test on monday as per resquest.

**Comment by AxelLin** [comment]
> I will run the test on monday as per resquest.

How is your test result?

**Comment by filzek** [comment]
In SDK 5.2 commit before 5.2.2 the init problem was solved.

We can deinit and reinit it without problem!

**Comment by filzek** [comment]
We conducted a two-day testing period. During this time, the deinitialization and reinitialization processes worked perfectly without any issues. Additionally, there were no memory leaks observed in the BLE so far. This toppic should be closed as solved.
