### ISSUE TITLE
BLE Security parameter "AuthOpt_u8" doesn't get reset after the BLE was disabled/re-enabled. (IDFGH-12909)

### ISSUE THREAD

**Issue by sergiutigu** [espressif/esp-idf#13869]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v4.3

### Espressif SoC revision.

ESP32

### Operating System used.

Windows

### How did you build your project?

VS Code IDE

### If you are using Windows, please specify command line type.

None

### Development Kit.

custom board

### Power Supply used.

USB

### What is the expected behavior?

the value of the BLE security parameter "AuthOpt_u8" should be cleared after cycles of BLE enable/disable.

### What is the actual behavior?

the value of the BLE security parameter "AuthOpt_u8" is stored between cycles of BLE enabling /disabling.

### Steps to reproduce.

1. Enable BLE
    esp_bt_controller_config_t NPI_BT_ControllerConfig_st = BT_CONTROLLER_INIT_CONFIG_DEFAULT();

    ErrorCode_s32 = esp_bt_controller_init(&NPI_BT_ControllerConfig_st);
    if (ErrorCode_s32 != ESP_OK) {
      //error message
          }

    ErrorCode_s32 = esp_bt_controller_enable(ESP_BT_MODE_BLE);
    if (ErrorCode_s32 != ESP_OK) {
      //error message
      }

    ErrorCode_s32 = esp_ble_config_file_path_update((char_t*)NPI_BT_Filename_pac);
    if (ErrorCode_s32 != ESP_OK) {
      //error message
      }

    ErrorCode_s32 = esp_bluedroid_init();
    if (ErrorCode_s32 != ESP_OK) {
      //error message
      }

    ErrorCode_s32 = esp_bluedroid_enable();
    if (ErrorCode_s32 != ESP_OK) {
      //error message
    }
2. Set AuthOpt_u8 = ESP_BLE_ONLY_ACCEPT_SPECIFIED_AUTH_ENABLE;
3. Disable BLE
4.     esp_err_t ErrorCode_s32;
    // Before deinit, disable ble first
    ErrorCode_s32 = esp_bluedroid_disable();
    if (ErrorCode_s32 != ESP_OK) {
      //error message
    }
    // Deinit and free the stack for ble
    ErrorCode_s32 = esp_bluedroid_deinit();
    if (ErrorCode_s32 != ESP_OK) {
      //error message    }
    // Disable the bt controller
    ErrorCode_s32 = esp_bt_controller_disable();
    if (ErrorCode_s32 != ESP_OK) {
      //error message    }
    // Deinit the bt controller
    ErrorCode_s32 = esp_bt_controller_deinit();
    if (ErrorCode_s32 != ESP_OK) {
      //error message    }
5. Enable BLE again like in step 1. 
6.  The value of  AuthOpt_u8 = ESP_BLE_ONLY_ACCEPT_SPECIFIED_AUTH_ENABLE is still as set before.
7. This is not the case if you reboot the board.
8. In order to fix this you need to explicit clear this settings.
...

**Comment by zhp0406** [comment]
The BLE security parameter "AuthOpt_u8" does not get reset after the BLE is disabled and then re-enabled.

Could you please explain what impact this might have on usage if the security parameter "AuthOpt_u8" is not cleared?

**Comment by exilat** [comment]
Well actually it is a problem. For instance you can run as a server and then you run as a client. Now the AuthOpt_u8 from the server are applied to the Client also. And also i am no longer confident that like disabling and enabling again the BLE stack is actually reseting to initial configuration. This is clearly software bug since it disapears if you do a hardware reset.
I do not consider that this issue is done

**Comment by zhp0406** [comment]
Thank you for your report. We have now fixed the issue.

The fix has been committed to the master branch with commit ID: 42ca04b5866dbe59a0cbe1f725708db6a75608e6.

Once testing is complete, we will sync it to GitHub and other branch.

**Comment by zhp0406** [comment]
[0001-fix-ble-bluedroid-Fixed-BLE-set-adv-param-check.zip](https://github.com/user-attachments/files/15833071/0001-fix-ble-bluedroid-Fixed-BLE-set-adv-param-check.zip)

**Comment by Indastri** [comment]
Closing the issue as the user did not reply. If you will encounter any problems, feel free to reopen this one or create a new issues.

Cheers!
