### ISSUE TITLE
I2C default pins as GPIO 21 and 22 ?

### ISSUE THREAD

**Issue by sjoteppagol** [espressif/esp-idf#1388]
Is there any particular bit set by default in ESP32, internally sets GPIO 21 and 22 as I2C pins. Even though i am using GPIO 21 as interrupt pin(push button) and GPIO 22 as normal GPIO(LED)?

Whenever i use both I2C and interrupt code, i get I2C read error.

**Comment by Spritetm** [comment]
Closing as this is duplicate with #1389.
