### ISSUE TITLE
esp_now_peer_info.priv is always null (IDFGH-12921)

### ISSUE THREAD

**Issue by TixoRebel** [espressif/esp-idf#13880]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v5.2.1

### Espressif SoC revision.

ESP32-C3 (QFN32) (revision v0.4)

### Operating System used.

Linux

### How did you build your project?

VS Code IDE

### If you are using Windows, please specify command line type.

None

### Development Kit.

Custom Board with ESP32-C3-MINI

### Power Supply used.

USB

### What is the expected behavior?

I expect that when I write to esp_now_peer_info.priv and call esp_now_add_peer, when I later call esp_now_get_peer to retrieve the same peer the value that I previously wrote to esp_now_peer_info.priv is retained.

### What is the actual behavior?

Instead, when I write to esp_now_peer_info.priv and later call esp_now_get_peer, the value of esp_now_peer_info.priv is null.

### Steps to reproduce.

Add a esp-now peer with a non-zero esp_now_peer_info.priv field. Retrieve the peer and observe that esp_now_peer_info.priv is null.

**Comment by zhangyanjiaoesp** [comment]
@TixoRebel This has been solved in https://github.com/espressif/esp-idf/commit/8710a192c4471cdb55933b663e744952aec62cbb, and we will merge it in v5.2 ASAP.
