### ISSUE TITLE
[Linux target] ESP_ERROR_CHECK_WITHOUT_ABORT not  available on Linux target (IDFGH-12933)

### ISSUE THREAD

**Issue by matthew-8925** [espressif/esp-idf#13893]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v5.2, master

### Operating System used.

Linux

### How did you build your project?

Command line with idf.py

### If you are using Windows, please specify command line type.

None

### What is the expected behavior?

Successful compile when using ESP_ERROR_CHECK_WITHOUT_ABORT()

```C
#include "esp_err.h"

esp_err_t f() { return ESP_OK; }

void a(){
ESP_ERROR_CHECK_WITHOUT_ABORT(f());
}
```

```
idf.py --preview set-target linux
idf.py build
```

### What is the actual behavior?

Fails to build with 
```
/usr/bin/ld: esp-idf/main/libmain.a(main.c.o): in function `app_main':
/opt/esp/idf/examples/protocols/http_server/simple/main/main.c:464:(.text.app_main+0xc8): undefined reference to `_esp_error_check_failed_without_abort'
```

### Steps to reproduce.

Write a program using ESP_ERROR_CHECK_WITHOUT_ABORT() and try to compile with the Linux target

```
idf.py --preview set-target linux
idf.py build
```

### More Information.

Minor issue, but would be nice to be fixed as we use that function a bit.

Also, wishlist for the Linux target would be an [optional] 32 bit Linux build to match the ESP's 32 bit CPU.

This fix / work around looks something like this.

```patch
diff --git a/components/esp_system/CMakeLists.txt b/components/esp_system/CMakeLists.txt
index c63a27d..ce74143 100644
--- a/components/esp_system/CMakeLists.txt
+++ b/components/esp_system/CMakeLists.txt
@@ -2,7 +2,7 @@ idf_build_get_property(target IDF_TARGET)
 
 # On Linux, we only support a few features, hence this simple component registration
 if(${target} STREQUAL "linux")
-    idf_component_register(SRCS "esp_system.c"
+    idf_component_register(SRCS "esp_system.c" "esp_err.c"
                         "port/soc/linux/reset_reason.c"
                         "port/soc/linux/system_internal.c"
                         "port/esp_system_linux.c"
diff --git a/components/esp_system/esp_err.c b/components/esp_system/esp_err.c
index ecc3de9..9ff88fd 100644
--- a/components/esp_system/esp_err.c
+++ b/components/esp_system/esp_err.c
@@ -8,8 +8,10 @@
 #include <string.h>
 
 #include "esp_err.h"
+#ifndef CONFIG_IDF_TARGET_LINUX
 #include "spi_flash_mmap.h"
 #include "esp_private/cache_utils.h"
+#endif
 
 #include "esp_rom_sys.h"
 
@@ -32,7 +34,9 @@ static void esp_error_check_failed_print(const char *msg, esp_err_t rc, const ch
 #endif //CONFIG_ESP_ERR_TO_NAME_LOOKUP
     esp_rom_printf(" at 0x%08x\n", esp_cpu_get_call_addr(addr));
 #if !CONFIG_APP_BUILD_TYPE_PURE_RAM_APP
+#ifndef CONFIG_IDF_TARGET_LINUX
     if (spi_flash_cache_enabled())  // strings may be in flash cache
+#endif
 #endif
     {
         esp_rom_printf("file: \"%s\" line %d\nfunc: %s\nexpression: %s\n", file, line, function, expression);
(END)
```

**Comment by KonstantinKondrashov** [comment]
Hi @matthew-8925!
I will help to fix this issue, the changes will go to the master, but we will not backport it because the Linux target is still a preview.
