### ISSUE TITLE
softAP多AP实现 (IDFGH-12949)

### ISSUE THREAD

**Issue by hnhkj** [espressif/esp-idf#13905]
### Is your feature request related to a problem?

我们现在有一个需求，希望能够通过softAP模拟多个WIFI热点（2-3）。不知道是否可以实现？我们只是需要AP广播相应的MAC数据。不知道softAP是否可以实现？或是有什么好的建议？

**Comment by MaxwellAlan** [comment]
Hi @hnhkj 

Due to the limitation of hardware and software resources, multiple AP functions cannot be realized on existing chips.

Thanks.

**Comment by Sherry616** [comment]
Thanks for reporting, will close due to short of feedback, feel free to reopen with more updates. 
Thanks for using our Espressif product!
