### ISSUE TITLE
esp32-s3 how to transmit large data with  triggers on both edges (IDFGH-12948)

### ISSUE THREAD

**Issue by WeiTianlia** [espressif/esp-idf#13904]
I want to make a dot matrix screen using AG5958 as the selector and mbi5268 as the data device. I want to use SPI to simulate sending data, but I found that SPI does not have the ability to support "double edge triggered" in the application. However, mbi5268 only supports this triggering mode. I don't know if anyone has a way to use SPI to send matching data to mbi5268,ths
![1717467390093](https://github.com/espressif/esp-idf/assets/161804209/981fd6e0-fe55-439e-84b8-3654bff16752)

**Comment by wanckl** [comment]
@WeiTianlia 
Hi, FMY, GPSPI2 on esp32s3 is actually support DDR mode in hardware,    
But haven't supported in IDF yet     

maybe they can support later as an device flag is enough~   
for now you can have a try to config registers as bellow after `spi_bus_add_device`   
```c
GPSPI2.misc.clk_data_dtr_en = 1;
GPSPI2.misc.data_dtr_en = 1;
```

then you'll find your transactions become DDR mode!!

**Comment by WeiTianlia** [comment]
> @WeiTianlia Hi, FMY, GPSPI2 on esp32s3 is actually support DDR mode in hardware, But haven't supported in IDF yet
> 
> maybe they can support later as an device flag is enough~ for now you can have a try to config registers as bellow after `spi_bus_add_device`
> 
> ```c
> #include "soc/spi_struct.h"
> ...
> GPSPI2.misc.clk_data_dtr_en = 1;
> GPSPI2.misc.data_dtr_en = 1;
> ```
> 
> then you'll find your transactions become DDR mode!!

that is right,had Verified
data[]={0b10101010,0b10101010,0b10101010,0b10101010},actal spi,4 cycle
![image](https://github.com/espressif/esp-idf/assets/161804209/1876072f-6433-491b-848a-c6b4e833ae8c)

**Comment by wanckl** [comment]
@WeiTianlia Hi, this feature is recently ready to integrate in esp-idf, but we don't have this DCLK chip for testing,  can you have a look and help testing the driver? here is patch for master `28044f8fdb`

[0001-feat-driver_spi-master-driver-support-DDR-DTR-clock-.patch](https://github.com/user-attachments/files/29374960/0001-feat-driver_spi-master-driver-support-DDR-DTR-clock-.patch)
