### ISSUE TITLE
Port USB Device Stack to esp32 (IDFGH-12985)

### ISSUE THREAD

**Issue by Slion** [espressif/esp-idf#13936]
### Is your feature request related to a problem?

For my project I would need both Classic Bluetooth and USB Device Stack

### Describe the solution you'd like.

Is there any chance the USB Device Stack could support esp32 targets instead of just esp32s2 and esp32s3?
I don't mind if it breaks the serial port, to reflash it I could still reset to bootloader right?

### Additional context.

I don't mind doing the port myself but I'm still a new to esp-idf so it could take a while but with some help I guess I could get it done.

**Comment by Dazza0** [comment]
@Slion 

> Is there any chance the USB Device Stack could support esp32 targets instead of just esp32s2 and esp32s3?

Only if you use some sort of external USB device controller chip. The s2 and s3 contain a USB controller peripheral, meaning you can program the s2/s3 to whatever USB device you want. The esp32 does not have such a peripheral so you'll need to select some sort of external USB device controller chip that interfaces with the esp32 over I2C/SPI.
