### ISSUE TITLE
coredump and watchdog reset (IDF-459)

### ISSUE THREAD

**Issue by michprev** [espressif/esp-idf#1394]
Hello,
I am experiencing a problem when I try to read coredump from flash memory when watchdog reset occured.
I am getting:
```
espcoredump.py v0.1-dev
esptool.py v2.1
Connecting.....
Chip is ESP32D0WDQ6 (revision 0)
Uploading stub...
Running stub...
Stub running...
16 (100 %)
16 (100 %)
Read 16 bytes at 0x110000 in 0.0 seconds (13.2 kbit/s)...
Hard resetting...

esptool.py v2.1
Connecting....
Chip is ESP32D0WDQ6 (revision 0)
Uploading stub...
Running stub...
Stub running...
16956 (100 %)
16956 (100 %)
Read 16956 bytes at 0x110000 in 1.5 seconds (89.1 kbit/s)...
Hard resetting...


A fatal error occurred: Can not add overlapping region [3ffb2668..3ffb27cb] to ELF file. Conflict with existing [3ffb04e0..3ffb3a23].
```
I have prepared example project at https://github.com/michprev/flyhero-esp32/tree/issue_coredump/The_Eye.
Especially I have set following settings:
Component config -> ESP32-specific -> Invoke panic handler on Task Watchdog timeout
Component config -> ESP32-specific -> Watch CPU0 Idle Task
Component config -> ESP32-specific -> Core dump destination -> Flash

I am running
`"$IDF_PATH"/components/espcoredump/espcoredump.py -p /dev/ttyUSB0 info_corefile The_Eye/build/The_Eye.elf`

When I run assert(0) before watchdog reset I experience no problems with reading core dump.

**Comment by michprev** [comment]
I have created dump of flash memory at 0x110000 (according to https://github.com/espressif/esp-idf/blob/master/components/partition_table/partitions_singleapp_coredump.csv).

[dump.txt](https://github.com/espressif/esp-idf/files/1565171/dump.txt)

**Comment by michprev** [comment]
I believe that the problem occurs whenever abort() is called from an isr

**Comment by nevercast** [comment]
I'm seeing this message `A fatal error occurred: Can not add overlapping region [3ffe13a0..3ffe1857] to ELF file. Conflict with existing [3ffe1700..3ffe2c5b].` while trying to analyse a b64 dump file with `info_corefile`. All I have in UART is `abort() was called at PC 0x4008d4a8 on core 1` followed by the Core Dump. 

Is this related? I don't believe abort is being called from an isr but without the core dump working it is difficult to check.

**Comment by michprev** [comment]
You can check here is abort called from an isr:
https://github.com/espressif/esp-idf/blob/e1a6e71486440de4df2916b9e534e4a6b0909575/components/esp32/task_wdt.c#L158

task_wdt_isr function is assigned as watchdog timeout isr here:
https://github.com/espressif/esp-idf/blob/e1a6e71486440de4df2916b9e534e4a6b0909575/components/esp32/task_wdt.c#L183

**Comment by Alvin1Zhang** [comment]
Fixed via https://github.com/espressif/esp-idf/commit/f64ee5aba32843b5c5b9ddf845c7db7f43f30ce7.
