### ISSUE TITLE
compiling error for esp32s3(Failed to resolve component 'esp32s3') (IDFGH-13009)

### ISSUE THREAD

**Issue by arunkm490** [espressif/esp-idf#13959]
i get this error .....Failed to resolve component 'esp32s3'
 when i run this command make BOARD=GENERIC_S3

this is for lv_micropython (lvgl binding with micropython)

**Comment by dobairoland** [comment]
@arunkm490 I don't think that this is right place for this report. We don't support "make BOARD" nor micropython directly in ESP-IDF. Can you please explain more what you are using and how so I can direct to you the right place?

**Comment by dobairoland** [comment]
Ok, I think https://github.com/micropython/micropython/issues might be the right place to report this. 

If I'm not mistaken then `make BOARD=GENERIC_S3` is a build command for micropython.

**Comment by arunkm490** [comment]
thank u

**Comment by ESP-Marius** [comment]
Closing this since it seems unrelated to esp-idf
