### ISSUE TITLE
WIFI-NAN for ESP32-S3 (IDFGH-13023)

### ISSUE THREAD

**Issue by QingyaZ** [espressif/esp-idf#13970]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Does the example provided in this link (https://docs.espressif.com/projects/esp-idf/en/stable/esp32/api-reference/network/esp_nan.html) support ESP32-S3 chip?

I tried the subscriber for ESP32 and ESP 32-s2. It can build projects successfully. However, the build project for ESP32-S3 failed.

**Comment by AxelLin** [comment]
https://github.com/espressif/esp-idf/issues/12987#issuecomment-1916423246

**Comment by kapilkedawat** [comment]
Hi @QingyaZ, NaN is not supported in ESP32S3 at the moment. You can see the supported targets in the [readme](https://github.com/espressif/esp-idf/blob/master/examples/wifi/wifi_aware/nan_console/README.md) of example.

**Comment by Sherry616** [comment]
Thanks for reporting, will close due to short of feedback, feel free to reopen with more updates. 
Thanks for using our Espressif product!
