### ISSUE TITLE
S&quot;,&quot;label&quot;:null}" id="item-405f808c-6517-4568-b92b-b9fd800a2a17" href="/issues" data-view-component="true" class="ActionListContent ActionListContent--visual16"> (IDFGH-13037)

### ISSUE THREAD

**Issue by erenuludemir** [espressif/esp-idf#13983]
undefined

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to short of details. If there is still issue, please help follow [the template](https://github.com/espressif/esp-idf/issues/new/choose) in creating a new issue, thanks.

**Comment by erenuludemir** [comment]
<img width="1248" alt="image" src="https://github.com/espressif/esp-idf/assets/169570558/c04f7675-062d-43e9-a2c1-32308d851b1a">

sorry, cancel help me please.
