### ISSUE TITLE
esp_hid_host_main should suto relink when disconnecting (IDFGH-13048)

### ISSUE THREAD

**Issue by username0occupied** [espressif/esp-idf#13994]
### Is your feature request related to a problem?

I found that after slave disconnected, the chip could not reconnect automatically.

### Additional context.

Such as my Logitech Pebble Mouse, if it disconnected due to weak signal, the esp32c3 would close the connect. But this would not happened on my phone.
And esp32c3 could not connect my Logi K580 Keyboard after rebooting too. I think esp32c3 cannot reconnect devices needing PASSKEY or the Keyboard hid itself. And this would not happened on my phone.

**Comment by esp-zhp** [comment]
What is the disconnection error code you mentioned? If the disconnection is due to a timeout, the code will be 0x08 (timeout). You can try reconnecting at the application layer.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, feel free to reopen if the issue still happens. Thanks.
