### ISSUE TITLE
make: *** [/home/Vima/esp-idf/components/esptool_py/Makefile.projbuild:55: flash] Error 1	

### ISSUE THREAD

**Issue by mkvn** [espressif/esp-idf#1399]
Hi, 
I try to bild my project for Esp32 development board. When I Build my project (before doing make flash) in eclipse (inside windows), I see this error in tab Problems of eclipse:

make: *** [/home/Vima/esp-idf/components/esptool_py/Makefile.projbuild:55: flash] Error 1	
mentioned resource is : esp-idf-template		 	

I have googled it but couldn't undrestand how to solve it, I appreciate any solution or suggestion.

**Comment by FayeY** [comment]
Duplicate issue of #1398 .
