### ISSUE TITLE
PRs: cla-assistant isn't works for me (IDFGH-13047)

### ISSUE THREAD

**Issue by denizzzka** [espressif/esp-idf#13993]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

cla-assistant just isn't works

I tried to disable adv-cutting and privacy plugins on my browser

I tried cookies cleanup, re-signup to cla-assistant site, re-creation of CLA on cla-assistant site

Two my PRs stalled because of this:
https://github.com/espressif/esp-idf/pull/13992
https://github.com/espressif/esp-idf/pull/13613

**Comment by denizzzka** [comment]
> cla-assistant just isn't works

It displays all theese texts like: "Please agree to the CLA for espressif/esp-idf" and "You have agreed to the CLA for espressif/esp-idf"

Then it redirects me: "We are now taking you back to GitHub"

But I still see yellow circle and "license/cla Pending — Contributor License Agreement is not signed yet."

And not seen msg from bot like:

_[CLAassistant](https://github.com/CLAassistant) commented on Apr 8 • 
CLA assistant check
All committers have signed the CLA._


I use Google Chrome browser

**Comment by igrr** [comment]
Most likely you have committed using an email which isn't added to your GitHub account as a verified one.

From cla-assistant comment in your PR:

> Denis Feklushkin seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please add the email address used for this commit to your account.

(Last sentence)

**Comment by denizzzka** [comment]
@igrr That's exactly what it was! And there also need to click "recheck" link

Thank you!
