### ISSUE TITLE
[TW#17089] Enhancement: Query and return the list of white listed BLE addresses

### ISSUE THREAD

**Issue by nkolban** [espressif/esp-idf#1401]
We have APIs to add a BLE address and remove a BLE address from the BLE white list ... however we don't seem to have an API to query the list of BLE addresses on the white list.  This issue asks for the consideration of an additional API to return the white list set.

**Comment by blueMoods** [comment]
Bluedroid does not provide this command, so we do not intend to increase this API, thank you for your advice.
/home/baohongde/Desktop/Screenshot from 2017-12-25 10-47-40.png

**Comment by blueMoods** [comment]
Bluedroid does not provide this command, so we do not intend to increase this API, thank you for your advice.

**Comment by blueMoods** [comment]
![screenshot from 2017-12-25 10-47-40](https://user-images.githubusercontent.com/30062326/34331477-1caa84ac-e962-11e7-9283-29cb8109d8e2.png)

**Comment by nkolban** [comment]
Thank you sir.  I guess if the underlying environment doesn't provide it, that's the end of the story.
