### ISSUE TITLE
[TW#17090] Typo: esp_ble_wl_opration to esp_ble_wl_operation_t

### ISSUE THREAD

**Issue by nkolban** [espressif/esp-idf#1402]
There is a pretty bad typo in a typedef.  The typedef is currently named `esp_ble_wl_opration` and should be `esp_ble_wl_operation_t`.

See:

https://github.com/espressif/esp-idf/blob/master/components/bt/bluedroid/api/include/esp_gap_ble_api.h#L479

**Comment by blueMoodBHD** [comment]
Have changed and merged into master, thanks for your suggestion.
