### ISSUE TITLE
[TW#17091] Enhancement: Rename event ESP_GAP_BLE_ADD_WHITELIST_COMPLETE_EVT

### ISSUE THREAD

**Issue by nkolban** [espressif/esp-idf#1403]
There is an API called `esp_ble_gap_update_whitelist()` which updates the BLE white list by either adding or removing an entry.  When complete, an event is raised.  The event is called ESP_GAP_BLE_ADD_WHITELIST_COMPLETE_EVT.  As you can maybe see, this is not a great name as the event can also be seen when we remove a white list entry.  I suggest that the event be renamed to match the function and be called

`ESP_GAP_BLE_UPDATE_WHITELIST_COMPLETE_EVT`

**Comment by blueMoodBHD** [comment]
Have changed and merged into master, thanks for your suggestion.
