### ISSUE TITLE
Command to show dependency tree of components (IDFGH-13098)

### ISSUE THREAD

**Issue by stkw0** [espressif/esp-idf#14045]
### Is your feature request related to a problem?

We had a somewhat complex image. We were facing some bugs and wanted to reduce it so it can fit into RAM memory and boot it directly from RAM. Using "size", "size-files" and "size-components" we have seen which components contribute more to the final size. The component that affects more, is a dependency of some other components. Hence, having the possibility to show the dependency tree would be very useful.

### Describe the solution you'd like.

Having a new command that shows the dependency tree of components.

**Comment by ESP-Marius** [comment]
I think what you are looking for is already possible.

See https://github.com/espressif/esp-idf/tree/master/tools/test_apps/system/g1_components#component-dependencies-graph-component_depsdot for an example where we do this.

**Comment by stkw0** [comment]
Oh, thank you very much! I missed that.
