### ISSUE TITLE
fatal error: esp_nimble_hci.h: No such file or directory (IDFGH-13110)

### ISSUE THREAD

**Issue by zzzh** [espressif/esp-idf#14057]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v5.2.1

### Operating System used.

Linux

### How did you build your project?

Command line with idf.py

### If you are using Windows, please specify command line type.

None

### What is the expected behavior?

no error

### What is the actual behavior?

fatal error: esp_nimble_hci.h: No such file or directory

### Steps to reproduce.

1. #include "esp_nimble_hci.h" in a c file.
2. idf.py set-target esp32c2
3. idf.py menuconfig, enable vluetooth and select NimBLE - BLE only
4. idf.py build

### Build or installation Logs.

```plain
../main/ble1.c:22:10: fatal error: esp_nimble_hci.h: No such file or directory
   22 | #include "esp_nimble_hci.h"
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by rahult-github** [comment]
Hi @zzzh ,

 > #include "esp_nimble_hci.h" in a c file. 
 
 This step is incorrect. May i know why you are explicitly including this file ?  The VHCI interface is not used in esp32c2 and hence this file won't be found during compilation for esp32c2.

**Comment by rahult-github** [comment]
Hi @zzzh ,

 > #include "esp_nimble_hci.h" in a c file. 
 
 This step is incorrect. May i know why you are explicitly including this file ?  The VHCI interface is not used in esp32c2 and hence this file won't be found during compilation for esp32c2.

**Comment by rahult-github** [comment]
Closing this issue. Please feel free to reopen if issue still exists.

**Comment by ihmpartners** [comment]
The ESP-IDF demo nimble bluetooth example includes this file so this is not helpful! 

I am trying to build the demo and run into the same issue!

**Comment by rahult-github** [comment]
Hi @ihmpartners ,

> The ESP-IDF demo nimble bluetooth example includes this file so this is not helpful!

May i know on which branch and which bluetooth example are you running to face this issue on ?
