### ISSUE TITLE
[TW#17312] BT: How to find out local BT MAC?

### ISSUE THREAD

**Issue by rojer** [espressif/esp-idf#1405]
Maybe i'm blind, but i don't see a function to get the address used by BT controller.
we have `esp_ble_gap_set_rand_addr` to set random address, but i'd rather use `esp_ble_gap_config_local_privacy` to have IDF generate it for me. the problem is, there doesn't seem to be a way to find out the value after it's generated.

**Comment by nkolban** [comment]
Howdy my friend.  Might the function called `esp_bt_dev_get_address()` be what you are looking for?

See:

http://esp-idf.readthedocs.io/en/latest/api-reference/bluetooth/esp_bt_device.html?highlight=esp_bt_dev_get_address#_CPPv222esp_bt_dev_get_addressv

**Comment by FayeY** [comment]
Hi @rojer , did the above suggestion help you resolve the issue?

**Comment by rojer** [comment]
yes, thanks!

**Comment by rojer** [comment]
it seems to always return the public address (`24:0a:...`), even if random address is enabled (`esp_ble_gap_config_local_privacy(true)`).

**Comment by chegewara** [comment]
Check this esp-idf example. I think you need to set advertising param flag to BLE_ADDR_TYPE_RANDOM. This example for sure setup randomized MAC

https://github.com/espressif/esp-idf/blob/master/examples/bluetooth/gatt_security_server/main/example_ble_sec_gatts_demo.c#L90

**Comment by rojer** [comment]
@chegewara yes, i set addr type to random in the adv params. in general, i have no trouble setting up the address - it's random, and clients can connect, no problem. but i need to find out what the address _is_, once it's set up.

**Comment by negativekelvin** [comment]
Random address is updated based on timer so you also would have to be aware of timer when showing user what the "current" random address is.

**Comment by chegewara** [comment]
@rojer I did not check it but maybe try to read local mac with esp_bt_dev_get_address() during this event:
https://github.com/espressif/esp-idf/blob/master/examples/bluetooth/gatt_security_server/main/example_ble_sec_gatts_demo.c#L338

**Comment by rojer** [comment]
@negativekelvin still, it would be nice to find out what the current address is.
@chegewara that's exactly what i did and it still returned the public address.

**Comment by TianHao-Espressif** [comment]
esp_bt_dev_get_address() always return the real(public) address. Or you want to get the random address which is in used, right?

**Comment by rojer** [comment]
@TianHao-Espressif yes

**Comment by Weijian-Espressif** [comment]
@rojer sorry there is no such interface yet.

**Comment by Weijian-Espressif** [comment]
@rojer We have added this API, and we are testing it now. We will merge to master later.

**Comment by rojer** [comment]
@Weijian-Espressif thank you!

**Comment by FayeY** [comment]
It has been merged, please have a try. Thanks.

**Comment by rojer** [comment]
finally got to try this. the API is `esp_ble_gap_get_local_used_addr()` and it works ok. thank you!
