### ISSUE TITLE
ESP32H2 Change Console Uart device reboot (IDFGH-13104)

### ISSUE THREAD

**Issue by wensenl** [espressif/esp-idf#14051]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

esp-ide-master/esp-idf-v5.3-beta2

### Espressif SoC revision.

ESP32H2

### Operating System used.

macOS

### How did you build your project?

Command line with Make

### If you are using Windows, please specify command line type.

None

### Development Kit.

ESP Thread Border Router/Zigbee Gateway

### Power Supply used.

USB

### What is the expected behavior?

I change the console log output to USB Serial/JTAG Controller, expected it can output success.
<img width="774" alt="1" src="https://github.com/espressif/esp-idf/assets/10335692/ce1c5b0f-71da-45f2-a316-d94defc69190">

### What is the actual behavior?

device reboot always.

### Steps to reproduce.

normal build 

### Debug Logs.

```plain
esp32h2 usb output log:
SPIWP:0xee
mode:DIO, clock div:1
load:0x408460f0,len:0x12f4
load:0x4083cad0,len:0xe00
load:0x4083efd0,len:0x2998
entry 0x4083cada
ESP-ROM:esp32h2-20221101
Build:Nov  1 2022
rst:0xc (SW_CPU),boot:0xe (SPI_FAST_FLASH_BOOT)
Saved PC:0x400031b6
0x400031b6: __call_r_ble_util_buf_acl_tx_elt_get in ROM
```

**Comment by wensenl** [comment]
the test demo is:
1、esp32s3 run esp-zigbee-sdk-main/examples/esp_zigbee_gateway
2、esp32h2 run esp-idf-master/examples/openthread/ot_rcp

**Comment by gytxxsy** [comment]
`ot_rcp` does not support `USB Serial/JTAG Controller`. In fact, if you need to debug ot_rcp and output some logs from ot_rcp to the computer while running the Gateway, we do not recommend using the `ESP Thread Border Router/Zigbee Gateway` board. In this case, we recommend using an ESP32S3 and an ESP32-H2, connecting them manually, and modifying some configurations of `ot_rcp`. As shown below:
![image](https://github.com/user-attachments/assets/ff474733-e6e2-4811-8cd0-ba7adaa1cfc9)
![image](https://github.com/user-attachments/assets/f9f5dfb7-b49a-4d31-9b19-f6060cc112e1)

**Comment by chshu** [comment]
Closing the issue as it's answered, @wensenl feel free to reopen if any follow up questions.
