### ISSUE TITLE
Remove /dev/tty.Bluetooth-Incoming-Port from serial port list in idf.py and esptool.py on macOS (IDFGH-13111)

### ISSUE THREAD

**Issue by clashman** [espressif/esp-idf#14058]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

MacOS has a default serial port at /dev/cu.Bluetooth-Incoming-Port.

It would be nice if esptool.py and idf.py would not try to connect to this port if no others are found.

i.e. in for idf.py command (tools/idf_py_actions/tools.py:131):
ports = list(sorted(p.device for p in serial.tools.list_ports.comports() **if not 'Bluetooth-Incoming-Port' in p.device**))

**Comment by radimkarnis** [comment]
Hi @clashman,
I agree, this can be very annoying. We'll filter out the `Bluetooth-Incoming-Port` and `wlan-debug` ports in our tools!
