### ISSUE TITLE
thread RCP build does not correctly pass through TIME_SYNC and CSL options (IDFGH-13112)

### ISSUE THREAD

**Issue by no2chem** [espressif/esp-idf#14059]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

When building a RCP, it appears that OPENTHREAD_CONFIG_TIME_SYNC_ENABLE (and the related CSL options) are never passed through because they are not set properly in `openthread-core-esp32x-radio-config.h`.

This causes a RCP build without TIME_SYNC and MAC IE header support, even though the menuconfig option is set.

 I will add a PR which fix this, however, I note that even with these options set it seems that the RCP crashes anyway whenever the host sends a frame with IE fields.

**Comment by chshu** [comment]
@no2chem It has been fixed in the latest code base, thanks for reporting the issue.
