### ISSUE TITLE
Http OTA failed using "simple_ota_example" (IDFGH-13139)

### ISSUE THREAD

**Issue by mahoneinsh** [espressif/esp-idf#14079]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [ ] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

V5.2.1

### Espressif SoC revision.

ESP32-C6

### Operating System used.

Windows

### How did you build your project?

VS Code IDE

### If you are using Windows, please specify command line type.

CMD

### Development Kit.

My board

### Power Supply used.

USB

### What is the expected behavior?

I want to download app bin file from http server (pc) into esp32-c6 board through wifi.  

### What is the actual behavior?

I have modified the SDK configuration, created the http server on my pc, and tried to download but failed at the last step, as shown below.
![1](https://github.com/espressif/esp-idf/assets/44339835/2371e324-f5fa-41c8-906d-f060127b9b40)

### Steps to reproduce.

1. ESP32 project configuration
![image](https://github.com/espressif/esp-idf/assets/44339835/3157cdfb-7de1-4e76-ad9a-ecc7cc3d88b5)
![image](https://github.com/espressif/esp-idf/assets/44339835/d0b57b01-1c09-49dd-a888-ab8bd04923c6)
2.HTTP server
![image](https://github.com/espressif/esp-idf/assets/44339835/3d25455f-c590-4a09-8f12-4a482aa31ea1)
![image](https://github.com/espressif/esp-idf/assets/44339835/8b0475c1-b1a7-48e6-b1d9-e0bcf64d90c3)
3.Example project build, flash and monitor 
![image](https://github.com/espressif/esp-idf/assets/44339835/f5677e3f-9e31-4dfa-a255-0f0469af8c1b)

**Comment by mahoneinsh** [comment]
Follow ESP32 FAE's advice, i also mask the following code
![image](https://github.com/espressif/esp-idf/assets/44339835/c06f970f-d97f-4675-b355-4b340fc216e5)

**Comment by nileshkale123** [comment]
Hi @mahoneinsh ,

Thank you for bringing this issue to my attention.

I've just tested the program on my end, and it executed successfully. To help troubleshoot your issue, could you please provide some more details? Specifically:

    1. The steps you followed in detail to execute the program
    2. Any specific environment or configuration details (like sdkconfig ) that might be relevant

With this information, I'll be better able to assist you in resolving the problem.

Thank you for your patience and cooperation.

**Comment by nileshkale123** [comment]
I reviewed your logs and noticed that the HTTP server and the ESP device are on different networks. The server is on 192.168.159.x, while the ESP device is on 192.168.137.x.

Please ensure both devices are on the same network to resolve the connection issue. Try connecting both devices ESP device and PC where the server is running to the same router.
