### ISSUE TITLE
esp32c3 GPIO in wake Stub --> Missing function inside components/esp_rom/include/esp32c3/rom/gpio.h (IDFGH-13168)

### ISSUE THREAD

**Issue by JustTrying-Arduino** [espressif/esp-idf#14108]
### Is your feature request related to a problem?

Hello, 

Since the 5.0 version, the function  `GPIO_OUTPUT_SET(gpio_no, bit_value)` and `GPIO_INPUT_GET(gpio_no)` disappear of the file [esp32c3/rom/gpio.h](https://github.com/espressif/esp-idf/blob/release/v5.0/components/esp_rom/include/esp32c3/rom/gpio.h)

### Describe the solution you'd like.

These functions simplify the use of GPIO inside Wake Stub. 
I wander if they could reappear. 

Thanks you

**Comment by ESP-Marius** [comment]
Hi,

These wrappers were actually wrong on C3, they are meant to choose between `gpio_output_set` and `gpio_output_set_high` when you have more than 32 GPIOs.

C3 doesn't, hence `gpio_output_set_high` doesnt even exist. You can simpy use `gpio_output_set` directly.
