### ISSUE TITLE
extract Version into Filename (IDFGH-13165)

### ISSUE THREAD

**Issue by diplfranzhoepfinger** [espressif/esp-idf#14105]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

extract Version into Filename

e.g. if Version is v1.4, can it be that the Filename of the bin then is Application_v1.4.bin and the merged Flash bin is merged-flash_v1.4.bin.bin

if yes, how to do this ? 

thanks,

**Comment by diplfranzhoepfinger** [comment]
could this be the base: 

```
get_filename_component(ProjectId ${CMAKE_CURRENT_LIST_DIR} NAME)
string(REPLACE " " "_" ProjectId ${ProjectId})
project(${ProjectId})

```

**Comment by KonstantinKondrashov** [comment]
Hi @diplfranzhoepfinger!
You can create your own cmd. Here is an example below. `idf.py my-release-cmd`.
Put this code into your CMakeLists.txt file.

https://docs.espressif.com/projects/esp-idf/en/stable/esp32/api-guides/build-system.html#build-project-variables
```cmake
idf_build_get_property(project_ver PROJECT_VER)
idf_build_get_property(project_name PROJECT_NAME)
add_custom_target(my-release-cmd
                    COMMAND ${CMAKE_COMMAND} -E copy "${build_dir}/${project_name}.bin" "${build_dir}/${project_name}_${project_ver}.bin"
                    COMMENT "Release binary"
                )

````
It produces a file like this `app_v5.4-dev-1638-gec3e3724ad-dirty.bin`.

There is topic - the https://esp32.com/viewtopic.php?t=19274

**Comment by diplfranzhoepfinger** [comment]
[@KonstantinKondrashov ](https://github.com/KonstantinKondrashov) cool! i will test.

**Comment by KonstantinKondrashov** [comment]
I close this issue, feel free to reopen it if needed. Thanks.
