### ISSUE TITLE
How to connect new BLE device with preventing automatically connected by already paired device? (IDFGH-13202)

### ISSUE THREAD

**Issue by Junanjunan** [espressif/esp-idf#14139]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

When one BLE-paired device exists, how do I prevent an existing paired device from automatically connecting when I try to connect a new device by advertising it?

I am using this function for advertising in components/bt/host/bluedroid/api/esp_gap_ble_api.c
```c
  esp_err_t esp_ble_gap_start_advertising(esp_ble_adv_params_t *adv_params)
```

**Comment by esp-zhp** [comment]
BLE does not support blacklists.
However, BLE supports whitelists.
BLE has a feature that allows you to set adv_filter.
You can check out esp_ble_adv_filter_t in components/bt/host/bluedroid/api/include/api/esp_gap_ble_api.h.

Add other devices to the whitelist, and if pairing is successful, remove them from the whitelist.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, feel free to reopen if the issue still happens. Thanks.
