### ISSUE TITLE
[TW#17150] Feature Request: RFCOMM/SPP for Bluetooth Classic

### ISSUE THREAD

**Issue by LosDeiblos** [espressif/esp-idf#1413]
Will there be support for RFCOMM/SPP for classic Bluetooth in the near future?

**Comment by blueMoodBHD** [comment]
Yes, we will support SPP for classic BT,and it is almost completed, will be released soon.

**Comment by spmp** [comment]
@blueMoodBHD Can you give an indication of the timescale of soon and a link to the current branch/docs/headers/examples(if any) where this work is being done so we can get a head start please?
Cheers

**Comment by blueMoodBHD** [comment]
@spmp We will merge to master in one or two week, please wait patiently, thanks for your understanding.

**Comment by blueMoodBHD** [comment]
@spmp @LosDeiblos The SPP have merged into master, Please refer to esp-idf/examples/bluetooth/bt_spp_acceptor & esp-idf/examples/bluetooth/bt_spp_initiator
