### ISSUE TITLE
esp_wifi_beacon_monitor_configure does not apply early wakeup parameter (IDFGH-13198)

### ISSUE THREAD

**Issue by dariocorna** [espressif/esp-idf#14135]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v5.1.4

### Espressif SoC revision.

ESP32-C6

### Operating System used.

Linux

### How did you build your project?

VS Code IDE

### If you are using Windows, please specify command line type.

None

### Development Kit.

ESP32-C6 MINI

### Power Supply used.

USB

### What is the expected behavior?

in wifi_init.c there is the possibility to change delta_intr_early (even if it is not in configuration).
there reason to change it is that on some router (ie fritzbox 7530) the power consumption is very high due to an high percentage of beacon loss.
This happens because it seems like beacon is drifted by a few microseconds in advance.
What i would reach with this modification it to accept an average higher consumption in ideal situation by stay alive a few milliseconds more for every beacon window, but at the same time grant an average consumption acceptable in all situations.

### What is the actual behavior?

delta_intr_early parameter is not applyed at all

### Steps to reproduce.

I'm using power_save example in wifi folder.

sdkconfig differences:
CONFIG_EXAMPLE_POWER_SAVE_MAX_MODEM=y 
CONFIG_ESP_WIFI_SLP_BEACON_LOST_OPT=y
CONFIG_ESP_WIFI_SLP_BEACON_LOST_TIMEOUT=25
CONFIG_ESP_WIFI_SLP_BEACON_LOST_THRESHOLD=0

 modfying wifi_init.c beacon monitor parameters manually in source code.

![image](https://github.com/espressif/esp-idf/assets/20624134/b6d3809e-6432-4e14-8100-ffd0c149121a)

**Comment by dariocorna** [comment]
Attached the same test on esp32-S2, that anticipate wakeup by 2ms by default and does not miss a beacon, this would be perfecly ok to me, even if the wakeup time is longer

![image](https://github.com/espressif/esp-idf/assets/20624134/75f5f36f-d9f2-4a6c-a998-db2253443f8f)
![image](https://github.com/espressif/esp-idf/assets/20624134/ee5b159b-612a-4e0d-9961-135c8a3baf9d)

**Comment by esp-lis** [comment]
recv beacon window = default tbtt interrupt early time (builtin) + delta_intr_early * loss_counter + delta_timeout * loss_counter

loss_counter++ if beacon is lost and loss_counter < loss_threshold

CONFIG_ESP_WIFI_SLP_BEACON_LOST_THRESHOLD=0 means loss_counter is always 0

**Comment by dariocorna** [comment]
ok this mean that with the following parameters and a tbtt of 204800 considering listening interval 2 I should get a window anticipated up to 192ms, instead is always 204 as you can see, there are also some other parameters nbt clears to me, like tsf_time_sync_deviation

`# define WIFI_BEACON_MONITOR_CONFIG_DEFAULT(ena)   { \
    .enable = (ena), \
    .loss_timeout = 50, \
    .loss_threshold = 5, \
    .delta_intr_early = 99, \
    .delta_loss_timeout = 0, \
    .beacon_abort = 1, \
    .broadcast_wakeup = 0, \
    .tsf_time_sync_deviation = 5, \
    .modem_state_consecutive = 10, \
    .rf_ctrl_wait_cycle = 20 \
}`

![image](https://github.com/espressif/esp-idf/assets/20624134/3a7dbdf4-9355-49ee-8f42-a0d498907fe6)

**Comment by esp-lis** [comment]
> ok this mean that with the following parameters and a tbtt of 204800 considering listening interval 2 I should get a window anticipated up to 192ms, instead is always 204 as you can see, there are also some other parameters nbt clears to me, like tsf_time_sync_deviation
> 
> `# define WIFI_BEACON_MONITOR_CONFIG_DEFAULT(ena) { \ .enable = (ena), \ .loss_timeout = 50, \ .loss_threshold = 5, \ .delta_intr_early = 99, \ .delta_loss_timeout = 0, \ .beacon_abort = 1, \ .broadcast_wakeup = 0, \ .tsf_time_sync_deviation = 5, \ .modem_state_consecutive = 10, \ .rf_ctrl_wait_cycle = 20 \ }`
> 
> ![image](https://private-user-images.githubusercontent.com/20624134/346956740-3a7dbdf4-9355-49ee-8f42-a0d498907fe6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1OTc0MzYsIm5iZiI6MTcyMDU5NzEzNiwicGF0aCI6Ii8yMDYyNDEzNC8zNDY5NTY3NDAtM2E3ZGJkZjQtOTM1NS00OWVlLThmNDItYTBkNDk4OTA3ZmU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDA3Mzg1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjMWQ5OWUxY2Y1ODEyMzY2YmQ5ODliZjU0ZjdlNTc1MzE4MDg0YzE3YTRlYzFmZmRkYzU4ZDkyZmZlNTM1MDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wNFQc-4skWRsrD6JiZt1EWSIi6b1IQ8iyTPGNnfbbzI)

pls refer to [wifi_types.h#L44-L62](https://gitlab.espressif.cn:6688/espressif/esp-idf/-/blob/master/components/esp_wifi/include/esp_private/wifi_types.h?ref_type=heads#L44-L62).

>> ok this mean that with the following parameters and a tbtt of 204800 considering listening interval 2 I should get a window  anticipated up to 192ms, instead is always 204 as you can see

I can not understand these description, Can you add more details describe?

**Comment by dariocorna** [comment]
> pls refer to [wifi_types.h#L44-L62](https://github.com/espressif/esp-idf/blob/master/components/esp_wifi/include/esp_private/wifi_types.h#L44).
> 

Comments are useful for sure, it would be better to me to understand how those parameter impact on beacon window, ie. tsf deviation is a percentage or a value, if value is ms ms^2 or us?

> > > ok this mean that with the following parameters and a tbtt of 204800 considering listening interval 2 I should get a window  anticipated up to 192ms, instead is always 204 as you can see
> 
> I can not understand these description, Can you add more details describe?

I mean whatever i set the beacoun window does not move, it is always on tbtt time (102400 ms * LISTEN_INTERVAL).
I'd just need to anticipate it a bit to obtain an average wake up time waiting for the beacon up to 5ms with a strong confidence to don't miss it. This works on esp32-S2 actually.

It seems like the algorithm works better when the router grant a drift on beacon window of less than 100us, it doesn't works when it is higher.

**Comment by Sherry616** [comment]
Thanks for reporting, will close due to short of feedback, feel free to reopen with more updates. 
Thanks for using our Espressif product!
