### ISSUE TITLE
IDF_TARGET_LINUX defined multiple times (IDFGH-13208)

### ISSUE THREAD

**Issue by dacut** [espressif/esp-idf#14145]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

`IDF_TARGET_LINUX` is defined multiple times in Kconfig:
* [Lines 82-84](https://github.com/espressif/esp-idf/blob/master/Kconfig#L82-L84)
* [Lines 144-146](https://github.com/espressif/esp-idf/blob/master/Kconfig#L144-L146)

It looks like the Python-based parser that `idf.py` uses (kconfiglib) deals with this ok, but it caused an issue on a parser I'm working on (simplify sdkconfig handling in Rust). I've worked around it, but it would be nice to not have the duplicate.

**Comment by sudeep-mohanty** [comment]
Thanks for pointing this out @dacut! We will fix it!
