### ISSUE TITLE
[TW#17151] ESPNOW tx power configuration

### ISSUE THREAD

**Issue by jobidon** [espressif/esp-idf#1414]
I am trying to set the max TX power for ESPNOW communications. I have tried to set the max TX power for WiFi, hoping that it would also apply to ESPNOW comms, but it doesn't seem to be the case. In fact setting WiFi power requires the wifi to be both initialized and started, while ESPNOW won't start if wifi is started first. However both technologies use the same communications mechanism, so there must be a way to control that as well.
So is there a way to control TX power and RX sensitivity for ESPNOW communications using the current API?

**Comment by TimXia** [comment]
Before using ESPNOW, wifi should start first in station or softap mode or both. You can do it like this:
...
esp_wifi_init();
esp_wifi_set_mode(WIFI_MODE_STA);
esp_wifi_start();
esp_now_init();
...
And you can control TX power after wifi started, the API is
esp_wifi_set_max_tx_power(int8_t power)
We haven't API to control RX sensitivity yet.
