### ISSUE TITLE
NVS Method nvs_set_str(nvs_handle, key, value) Causes Application Crash When Task Stack is in External Memory (IDFGH-13214)

### ISSUE THREAD

**Issue by Vinayaksma** [espressif/esp-idf#14151]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [ ] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v5.1.2

### Espressif SoC revision.

ESP32-S3

### Operating System used.

Windows

### How did you build your project?

Command line with idf.py

### If you are using Windows, please specify command line type.

PowerShell

### Development Kit.

ESP32-S3-WROOM-1

### Power Supply used.

Battery

### What is the expected behavior?

nvs_set_str(nvs_handle, key, value) should work properly  on Task with stack memory on External RAM (MALLOC_CAP_SPIRAM) 

### What is the actual behavior?

When the method `nvs_set_str(nvs_handle, key, value)` is executed on a task with stack memory allocated in internal memory, it works properly without any crashes. However, if the stack memory of the task is allocated in external memory `(MALLOC_CAP_SPIRAM)`, executing the `nvs_set_str(nvs_handle, key, value)` method causes it to crash.

Task with Stack memory on Internal Memory and it works fine.
``` 
TaskHandle_t taskHandle = xTaskCreate(&https_request_task, "https_get_task", 1024 * 6, NULL, 5, NULL);
```
 
 Task with Stack memory on External Memory and it crashes
 
 ```
StackType_t *stack_for_task = (StackType_t *) heap_caps_malloc(event_loop_args->task_stack_size, MALLOC_CAP_SPIRAM);
        StaticTask_t *xTaskBuffer= (StaticTask_t *)malloc(sizeof(StaticTask_t));
        loop->task = xTaskCreateStaticPinnedToCore(
                                            esp_event_loop_run_task, 
                                            event_loop_args->task_name,
                                            event_loop_args->task_stack_size, 
                                            (void*) loop,
                                            event_loop_args->task_priority, 
                                            stack_for_task,
                                            xTaskBuffer,
                                            event_loop_args->task_core_id
                                       );
```
I have attached the screenshot of the crash logs.

![image](https://github.com/espressif/esp-idf/assets/38756582/434fe734-f9ee-48a0-b3fd-412399c7e898)

### Steps to reproduce.

1. Create a task with stack memory on External memory (MALLOC_CAPS_SPIRAM). 
2. Inside task handler, do operation on NVS.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, feel free to reopen.
