### ISSUE TITLE
Websocket write function ignore const for input buffer which can result in a crash (IDFGH-13225)

### ISSUE THREAD

**Issue by thomasweichselbaumer** [espressif/esp-idf#14160]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

4.4.1, 5.3.0

### Espressif SoC revision.

esp32

### Operating System used.

Windows

### How did you build your project?

Command line with CMake

### If you are using Windows, please specify command line type.

None

### Development Kit.

-

### Power Supply used.

External 3.3V

### What is the expected behavior?

the function `static int _ws_write(esp_transport_handle_t t, int opcode, int mask_flag, const char *b, int len, int timeout_ms)` should not modify the pointer `*b`.

### What is the actual behavior?

the function` static int _ws_write(esp_transport_handle_t t, int opcode, int mask_flag, const char *b, int len, int timeout_ms)` modifies the pointer `*b`.

```
static int _ws_write(esp_transport_handle_t t, int opcode, int mask_flag, const char *b, int len, int timeout_ms)
{
   ...
    char *buffer = (char *)b;
  ...
        for (i = 0; i < len; ++i) {
            buffer[i] = (buffer[i] ^ mask[i % 4]);
        }
    }

```

### Steps to reproduce.

-

### Debug Logs.

```plain
-
```

### More Information.

If the data buffer is pointing to program code, the program will crash.

**Comment by euripedesrocha** [comment]
Hi @thomasweichselbaumer you are correct that we break `const` in the websocket transport write function. 
This happens to avoid a copy of the payload since client frames must be masked. Of course this means that this buffer must be in a memory region that we are allowed to write. 

We'll work on documenting the transport API better and will add the information.
