### ISSUE TITLE
archive with submodules isn't published (IDFGH-13230)

### ISSUE THREAD

**Issue by dannybackx** [espressif/esp-idf#14165]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Yesterday's mail with the 5.3-rc1 announcement includes a paragraph saying you can download a complete archive, as usually.

It's now 23 hours later and the archive still isn't there.
```
Download an archive with submodules included

Attached to this release is an esp-idf-v5.3-rc1.zip archive. It includes .git directory and all the submodules, so can be used out of the box. This archive is provided for users who have connectivity issues preventing them from cloning from GitHub.

This archive can also be downloaded from Espressif's download server: https://dl.espressif.com/github_assets/espressif/esp-idf/releases/download/v5.3-rc1/esp-idf-v5.3-rc1.zip
```

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, and sorry for the inconvenience, the issue has been fixed. Thanks.
