### ISSUE TITLE
[TW#17195] AWS IoT MQTT continuously disconnects

### ISSUE THREAD

**Issue by seopyoon** [espressif/esp-idf#1416]
I have my own application, which keeps on disconnecting.  (It used to operate much longer without disconnection before -- not aware since which update)  

So, I tested with the AWS IoT subscribe_publish example from the esp-idf git repo.  And it still behaves similarly.

But when it disconnects, there is no way of knowing what caused it.  Could it be the WiFi / Router problem? Or is it the firmware? 

And also, at launch, it the handshake failes once or twice before successfully connecting.  (Does not take too long to establish connection though).

Please help!  Or, if anyone is experiencing a similar problem, please comment.

![2017-12-21 12 06 05](https://user-images.githubusercontent.com/8359372/34238941-c95801ca-e647-11e7-91fa-b7de84a5f9af.png)

**Comment by satishIoT** [comment]
@seopyoon 
pl check https://github.com/espressif/esp-idf/issues/1695
this suggestion form negativekelvin had worked for me.

**Comment by projectgus** [comment]
Closing due to lack of update. Hopefully the linked issue solved the problem.
