### ISSUE TITLE
Error: All app partitions are too small for binary  (IDFGH-13249)

### ISSUE THREAD

**Issue by RJSDevel** [espressif/esp-idf#14183]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

esp-idf-v5.3-2

### Espressif SoC revision.

ESP32-C6 (QFN40) (revision v0.0)

### Operating System used.

Windows

### How did you build your project?

Command line with Make

### If you are using Windows, please specify command line type.

None

### Development Kit.

Custom 4MB Flash

### Power Supply used.

External 5V

### What is the expected behavior?

Build project

### What is the actual behavior?

![image](https://github.com/user-attachments/assets/ac9703d3-ef93-4680-9bff-3f99d714799e)

### Steps to reproduce.

Build project

### Debug Logs.

```plain
Building in: C:\Users\Developer\espressif\HA_switch_1_gang_wt0132c6-s6\build
cmake --build . -- -v
[1/4] cmd.exe /C "cd /D C:\Users\Developer\espressif\HA_switch_1_gang_wt0132c6-s6\build\esp-idf\esptool_py && D:\Espressif\python_env\idf5.3_py3.11_env\Scripts\python.exe C:/Espressif/frameworks/esp-idf-v5.3-2/components/partition_table/check_sizes.py --offset 0x8000 partition --type app C:/Users/Developer/espressif/HA_switch_1_gang_wt0132c6-s6/build/partition_table/partition-table.bin C:/Users/Developer/espressif/HA_switch_1_gang_wt0132c6-s6/build/switch_1_gang_wt0132c6_s5.bin"
FAILED: esp-idf/esptool_py/CMakeFiles/app_check_size C:/Users/Developer/espressif/HA_switch_1_gang_wt0132c6-s6/build/esp-idf/esptool_py/CMakeFiles/app_check_size 
cmd.exe /C "cd /D C:\Users\Developer\espressif\HA_switch_1_gang_wt0132c6-s6\build\esp-idf\esptool_py && D:\Espressif\python_env\idf5.3_py3.11_env\Scripts\python.exe C:/Espressif/frameworks/esp-idf-v5.3-2/components/partition_table/check_sizes.py --offset 0x8000 partition --type app C:/Users/Developer/espressif/HA_switch_1_gang_wt0132c6-s6/build/partition_table/partition-table.bin C:/Users/Developer/espressif/HA_switch_1_gang_wt0132c6-s6/build/switch_1_gang_wt0132c6_s5.bin"
Error: All app partitions are too small for binary switch_1_gang_wt0132c6_s5.bin size 0x131800:

  - Part 'factory' 0/0 @ 0x10000 size 0x80000 (overflow 0xb1800)

  - Part 'ota_0' 0/16 @ 0x90000 size 0x80000 (overflow 0xb1800)

  - Part 'ota_1' 0/17 @ 0x110000 size 0x80000 (overflow 0xb1800)

[2/4] cmd.exe /C "cd /D C:\Users\Developer\espressif\HA_switch_1_gang_wt0132c6-s6\build\bootloader && D:\Espressif\tools\cmake\3.24.0\bin\cmake.exe --build ."
[1/1] cmd.exe /C "cd /D C:\Users\Developer\espressif\HA_switch_1_gang_wt0132c6-s6\build\bootloader\esp-idf\esptool_py && D:\Espressif\python_env\idf5.3_py3.11_env\Scripts\python.exe C:/Espressif/frameworks/esp-idf-v5.3-2/components/partition_table/check_sizes.py --offset 0x8000 bootloader 0x0 C:/Users/Developer/espressif/HA_switch_1_gang_wt0132c6-s6/build/bootloader/bootloader.bin"

Bootloader binary size 0x54f0 bytes. 0x2b10 bytes (34%) free.


ninja: build stopped: subcommand failed.
Build complete (1 errors, 0 warnings): C:\Users\Developer\espressif\HA_switch_1_gang_wt0132c6-s6\build
Total time taken to build the project: 239 ms
```

### More Information.

Executing C:\Users\Developer\AppData\Local\Microsoft\WindowsApps\python3.EXE C:\Espressif\frameworks\esp-idf-v5.3-2\tools\idf_tools.py list
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
ErrorError

CDT Build environment variables
PATH: D:\Espressif\tools\xtensa-esp-elf-gdb\14.2_20240403\xtensa-esp-elf-gdb\bin;D:\Espressif\tools\riscv32-esp-elf-gdb\14.2_20240403\riscv32-esp-elf-gdb\bin;D:\Espressif\tools\xtensa-esp-elf\esp-13.2.0_20240530\xtensa-esp-elf\bin;D:\Espressif\tools\esp-clang\16.0.1-fe4f10a809\esp-clang\bin;D:\Espressif\tools\riscv32-esp-elf\esp-13.2.0_20240530\riscv32-esp-elf\bin;D:\Espressif\tools\esp32ulp-elf\2.38_20240113\esp32ulp-elf\bin;D:\Espressif\tools\cmake\3.24.0\bin;D:\Espressif\tools\openocd-esp32\v0.12.0-esp32-20240318\openocd-esp32\bin;D:\Espressif\tools\ninja\1.11.1\;D:\Espressif\tools\idf-exe\1.0.3\;D:\Espressif\tools\ccache\4.8\ccache-4.8-windows-x86_64;D:\Espressif\tools\dfu-util\0.11\dfu-util-0.11-win64;D:\Espressif\tools\qemu-xtensa\esp_develop_8.2.0_20240122\qemu\bin;D:\Espressif\tools\qemu-riscv32\esp_develop_8.2.0_20240122\qemu\bin;D:\Espressif\python_env\idf5.3_py3.11_env\Scripts;C:\Espressif\frameworks\esp-idf-v5.3-2\tools;C:\Program Files\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;D:\TelinkSDK\bin;C:\Users\Developer\AppData\Local\Programs\Python\Python311\Scripts\;C:\Users\Developer\AppData\Local\Programs\Python\Python311\;C:\Users\Developer\AppData\Local\Microsoft\WindowsApps;C:\Users\Developer\AppData\Roaming\npm;C:\Program Files\JetBrains\WebStorm 2023.2.4\bin;;C:\Users\Developer\AppData\Local\Programs\Microsoft VS Code\bin;D:\Program Files\SDCC\bin;C:\Program Files\JetBrains\PyCharm Community Edition 2023.2.5\bin;;C:\Users\Developer\AppData\Local\Android\Sdk\platform-tools;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2023.3\bin;;C:\cygwin64\OpenOCD-20231002-0.12.0\bin;D:\TelinkSDK\bin;C:\Program Files (x86)\SDCC\bin
USERDOMAIN_ROAMINGPROFILE: DESKTOP
PROCESSOR_LEVEL: 6
SESSIONNAME: Console
ALLUSERSPROFILE: C:\ProgramData
PROCESSOR_ARCHITECTURE: AMD64
ESP_IDF_VERSION: 5.3
PSModulePath: C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules
SystemDrive: C:
OPENOCD_SCRIPTS: D:\Espressif\tools\openocd-esp32\v0.12.0-esp32-20240318\openocd-esp32\share\openocd\scripts
IDF_COMPONENT_STORAGE_URL: file:///D:/Espressif/registry;default
USERNAME: Developer
ProgramFiles(x86): C:\Program Files (x86)
MOSQUITTO_DIR: C:\Program Files\mosquitto
PATHEXT: .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
DriverData: C:\Windows\System32\Drivers\DriverData
IntelliJ IDEA Community Edition: C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2023.3\bin
PyCharm Community Edition: C:\Program Files\JetBrains\PyCharm Community Edition 2023.2.5\bin
ProgramData: C:\ProgramData
IDF_COMPONENT_MANAGER: 1
ProgramW6432: C:\Program Files
SRFPROG: C:\Program Files (x86)\Texas Instruments\SmartRF Tools\Flash Programmer\bin
HOMEPATH: \Users\Developer
PROCESSOR_IDENTIFIER: Intel64 Family 6 Model 191 Stepping 2, GenuineIntel
PYTHON_EXE_PATH: D:/Espressif/python_env/idf5.3_py3.11_env/Scripts/python.exe
ProgramFiles: C:\Program Files
PUBLIC: C:\Users\Public
windir: C:\Windows
=::: ::\
ZES_ENABLE_SYSMAN: 1
EFC_8180: 1
IGCCSVC_DB: AQAAANCMnd8BFdERjHoAwE/Cl+sBAAAAz0RQFIuRnU+7kKYvf/SaowQAAAACAAAAAAAQZgAAAAEAACAAAADssMse3/mLXMt2JR09y2V6U+oPxVjEl0csmkMq6uY6XAAAAAAOgAAAAAIAACAAAACFGloyxUaD9+VB+WNqPMpmPw3H3OCeQzIuryt+gOC6jGAAAACyos5F2duCPJxSZ8WgoTfstBRukMG4MQ/3MhEVmoO+vsVwibEr6+b7zgN3e6WU7Zzuv/Z2gR0r2hTKlvap8q4r1may2K1jTzyP8luIl2rn3uUWX11ZIYt9OKnGrFrlF7RAAAAAOqji3kEs71IQ8cDfwJU/+J1YkIL7Bj7+sBlGOjgDCV/9LegVHk9HXpf1lYOrH5JoHDcqFhwP6PSZ96NyV6Oi3g==
LOCALAPPDATA: C:\Users\Developer\AppData\Local
ChocolateyLastPathUpdate: 133428995669946355
GIT_PATH: D:/Espressif/tools/idf-git/2.44.0/cmd/git.exe
USERDOMAIN: DESKTOP
LOGONSERVER: \\DESKTOP
WebStorm: C:\Program Files\JetBrains\WebStorm 2023.2.4\bin
IDF_TOOLS_PATH: D:\Espressif
OneDrive: C:\Users\Developer\OneDrive
APPDATA: C:\Users\Developer\AppData\Roaming
ChocolateyInstall: C:\ProgramData\chocolatey
VBOX_MSI_INSTALL_PATH: C:\Program Files\Oracle\VirtualBox\
CommonProgramFiles: C:\Program Files\Common Files
OS: Windows_NT
COMPUTERNAME: DESKTOP
IDF_PATH: C:/Espressif/frameworks/esp-idf-v5.3-2/
PROCESSOR_REVISION: bf02
CommonProgramW6432: C:\Program Files\Common Files
ComSpec: C:\Windows\system32\cmd.exe
SRFPROG2: C:\Program Files (x86)\Texas Instruments\SmartRF Tools\Flash Programmer 2\bin
IDF_MAINTAINER: 1
TEMP: C:\Users\DEVELO~1\AppData\Local\Temp
SystemRoot: C:\Windows
HOMEDRIVE: C:
USERPROFILE: C:\Users\Developer
TMP: C:\Users\DEVELO~1\AppData\Local\Temp
CommonProgramFiles(x86): C:\Program Files (x86)\Common Files
NUMBER_OF_PROCESSORS: 16
IDF_PYTHON_ENV_PATH: D:\Espressif\python_env\idf5.3_py3.11_env

Operating System: windows 11
Java Runtime Version: 17.0.6+10-LTS
Eclipse Version: 4.30.0.v20231201-0110
Eclipse CDT Version: 11.4.0.202309142347
IDF Eclipse Plugin Version: 3.0.0.202406051940
ESP-IDF v5.3-rc1
Python set for IDF_PYTHON_ENV: Python 3.11.2

**Comment by pacucha42** [comment]
Please, extend the partition definitions in your partition-table.csv exactly as mentioned in the logs - your binary size is 1222kB and thus cannot fit into 512kB space. Mind the partition offsets too, they must be updated accordingly.
Let us know if you need more details. Thanks for testing
