### ISSUE TITLE
simple_ota_example  (esp_https_ota: Mismatch chip id, expected 0, found 18242) (IDFGH-13253)

### ISSUE THREAD

**Issue by leehakgun** [espressif/esp-idf#14187]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

esp-idf v5.2.2

### Espressif SoC revision.

ESP32 Revision 1

### Operating System used.

Windows

### How did you build your project?

VS Code IDE

### If you are using Windows, please specify command line type.

None

### Development Kit.

ESP_EYE

### Power Supply used.

USB

### What is the expected behavior?

Firmware expected an update as described in the example

### What is the actual behavior?

E (8826) esp_https_ota: Mismatch chip id, expected 0, found 18242
E (8836) simple_ota_example: Firmware upgrade failed
This error has occurred

### Steps to reproduce.

#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "esp_system.h"
#include "esp_event.h"
#include "esp_log.h"
#include "esp_ota_ops.h"
#include "esp_http_client.h"
#include "esp_https_ota.h"
#include "protocol_examples_common.h"
#include "string.h"
#ifdef CONFIG_EXAMPLE_USE_CERT_BUNDLE
#include "esp_crt_bundle.h"
#endif

#include "nvs.h"
#include "nvs_flash.h"
#include "protocol_examples_common.h"
#include <sys/socket.h>
#if CONFIG_EXAMPLE_CONNECT_WIFI
#include "esp_wifi.h"
#endif

#define HASH_LEN 32

#ifdef CONFIG_EXAMPLE_FIRMWARE_UPGRADE_BIND_IF
/* The interface name value can refer to if_desc in esp_netif_defaults.h */
#if CONFIG_EXAMPLE_FIRMWARE_UPGRADE_BIND_IF_ETH
static const char *bind_interface_name = EXAMPLE_NETIF_DESC_ETH;
#elif CONFIG_EXAMPLE_FIRMWARE_UPGRADE_BIND_IF_STA
static const char *bind_interface_name = EXAMPLE_NETIF_DESC_STA;
#endif
#endif

static const char *TAG = "simple_ota_example";
extern const uint8_t server_cert_pem_start[] asm("_binary_ca_cert_pem_start");
extern const uint8_t server_cert_pem_end[] asm("_binary_ca_cert_pem_end");

static void print_mem_info(void) {
    multi_heap_info_t info;
    heap_caps_get_info(&info, MALLOC_CAP_DEFAULT);
    ESP_LOGI(TAG, "Total free memory: %d", info.total_free_bytes);
    ESP_LOGI(TAG, "Largest free block: %d", info.largest_free_block);
}

#define OTA_URL_SIZE 1024

esp_err_t _http_event_handler(esp_http_client_event_t *evt)
{
    switch (evt->event_id) {
    case HTTP_EVENT_ERROR:
        ESP_LOGD(TAG, "HTTP_EVENT_ERROR");
        break;
    case HTTP_EVENT_ON_CONNECTED:
        ESP_LOGD(TAG, "HTTP_EVENT_ON_CONNECTED");
        break;
    case HTTP_EVENT_HEADER_SENT:
        ESP_LOGD(TAG, "HTTP_EVENT_HEADER_SENT");
        break;
    case HTTP_EVENT_ON_HEADER:
        ESP_LOGD(TAG, "HTTP_EVENT_ON_HEADER, key=%s, value=%s", evt->header_key, evt->header_value);
        break;
    case HTTP_EVENT_ON_DATA:
        ESP_LOGD(TAG, "HTTP_EVENT_ON_DATA, len=%d", evt->data_len);
        break;
    case HTTP_EVENT_ON_FINISH:
        ESP_LOGD(TAG, "HTTP_EVENT_ON_FINISH");
        break;
    case HTTP_EVENT_DISCONNECTED:
        ESP_LOGD(TAG, "HTTP_EVENT_DISCONNECTED");
        break;
    case HTTP_EVENT_REDIRECT:
        ESP_LOGD(TAG, "HTTP_EVENT_REDIRECT");
        break;
    }
    return ESP_OK;
}

void simple_ota_example_task(void *pvParameter)
{
    ESP_LOGI(TAG, "Starting OTA example task");
#ifdef CONFIG_EXAMPLE_FIRMWARE_UPGRADE_BIND_IF
    esp_netif_t *netif = get_example_netif_from_desc(bind_interface_name);
    if (netif == NULL) {
        ESP_LOGE(TAG, "Can't find netif from interface description");
        abort();
    }
    struct ifreq ifr;
    esp_netif_get_netif_impl_name(netif, ifr.ifr_name);
    ESP_LOGI(TAG, "Bind interface name is %s", ifr.ifr_name);
#endif
    esp_http_client_config_t config = {
        .url = "https://192.168.10.78:8070/hello_world.bin",
        .timeout_ms = 10000,
        .transport_type = HTTP_TRANSPORT_OVER_SSL,
#ifdef CONFIG_EXAMPLE_USE_CERT_BUNDLE
        .crt_bundle_attach = esp_crt_bundle_attach,
#else
        .cert_pem = (char *)server_cert_pem_start,
#endif /* CONFIG_EXAMPLE_USE_CERT_BUNDLE */
        .event_handler = _http_event_handler,
        .keep_alive_enable = true,
#ifdef CONFIG_EXAMPLE_FIRMWARE_UPGRADE_BIND_IF
        .if_name = &ifr,
#endif
    };

#ifdef CONFIG_EXAMPLE_FIRMWARE_UPGRADE_URL_FROM_STDIN
    char url_buf[OTA_URL_SIZE];
    if (strcmp(config.url, "FROM_STDIN") == 0) {
        example_configure_stdin_stdout();
        fgets(url_buf, OTA_URL_SIZE, stdin);
        int len = strlen(url_buf);
        url_buf[len - 1] = '\0';
        config.url = url_buf;
    } else {
        ESP_LOGE(TAG, "Configuration mismatch: wrong firmware upgrade image url");
        abort();
    }
#endif

#ifdef CONFIG_EXAMPLE_SKIP_COMMON_NAME_CHECK
    config.skip_cert_common_name_check = true;
#endif

    esp_https_ota_config_t ota_config = {
        .http_config = &config,
    };
    ESP_LOGI(TAG, "Attempting to download update from %s", config.url);
    print_mem_info();
    esp_err_t ret = esp_https_ota(&ota_config);
    if (ret == ESP_OK) {
        ESP_LOGI(TAG, "OTA Succeed, Rebooting...");
        esp_restart();
    } else {
        ESP_LOGE(TAG, "Firmware upgrade failed");
    }
    while (1) {
        vTaskDelay(1000 / portTICK_PERIOD_MS);
    }
}

static void print_sha256(const uint8_t *image_hash, const char *label)
{
    char hash_print[HASH_LEN * 2 + 1];
    hash_print[HASH_LEN * 2] = 0;
    for (int i = 0; i < HASH_LEN; ++i) {
        sprintf(&hash_print[i * 2], "%02x", image_hash[i]);
    }
    ESP_LOGI(TAG, "%s %s", label, hash_print);
}

static void get_sha256_of_partitions(void)
{
    uint8_t sha_256[HASH_LEN] = { 0 };
    esp_partition_t partition;

    // get sha256 digest for bootloader
    partition.address   = ESP_BOOTLOADER_OFFSET;
    partition.size      = ESP_PARTITION_TABLE_OFFSET;
    partition.type      = ESP_PARTITION_TYPE_APP;
    esp_partition_get_sha256(&partition, sha_256);
    print_sha256(sha_256, "SHA-256 for bootloader: ");

    // get sha256 digest for running partition
    esp_partition_get_sha256(esp_ota_get_running_partition(), sha_256);
    print_sha256(sha_256, "SHA-256 for current firmware: ");
}

void app_main(void)
{
    ESP_LOGI(TAG, "OTA example app_main start");

    esp_log_level_set("*", ESP_LOG_DEBUG);
    // Initialize NVS.
    esp_err_t err = nvs_flash_init();
    if (err == ESP_ERR_NVS_NO_FREE_PAGES || err == ESP_ERR_NVS_NEW_VERSION_FOUND) {
        // 1.OTA app partition table has a smaller NVS partition size than the non-OTA
        // partition table. This size mismatch may cause NVS initialization to fail.
        // 2.NVS partition contains data in new format and cannot be recognized by this version of code.
        // If this happens, we erase NVS partition and initialize NVS again.
        ESP_ERROR_CHECK(nvs_flash_erase());
        err = nvs_flash_init();
    }
    ESP_ERROR_CHECK(err);

    get_sha256_of_partitions();

    ESP_ERROR_CHECK(esp_netif_init());
    ESP_ERROR_CHECK(esp_event_loop_create_default());

    /* This helper function configures Wi-Fi or Ethernet, as selected in menuconfig.
     * Read "Establishing Wi-Fi or Ethernet Connection" section in
     * examples/protocols/README.md for more information about this function.
     */
    ESP_ERROR_CHECK(example_connect());

#if CONFIG_EXAMPLE_CONNECT_WIFI
    /* Ensure to disable any WiFi power save mode, this allows best throughput
     * and hence timings for overall OTA operation.
     */
    esp_wifi_set_ps(WIFI_PS_NONE);
#endif // CONFIG_EXAMPLE_CONNECT_WIFI

    xTaskCreate(&simple_ota_example_task, "ota_example_task", 8192, NULL, 5, NULL);
}

### Debug Logs.

```plain
I (5366) simple_ota_example: Total free memory: 222552
I (5366) simple_ota_example: Largest free block: 110592
I (5376) main_task: Returned from app_main()
I (5626) mbedtls: ssl_tls.c:4606 => handshake

I (5626) mbedtls: ssl_msg.c:2353 => flush output

I (5626) mbedtls: ssl_msg.c:2362 <= flush output

I (5626) mbedtls: ssl_tls.c:4525 client state: MBEDTLS_SSL_HELLO_REQUEST

I (5636) mbedtls: ssl_msg.c:2353 => flush output

I (5646) mbedtls: ssl_msg.c:2362 <= flush output

I (5646) mbedtls: ssl_tls.c:4525 client state: MBEDTLS_SSL_CLIENT_HELLO

I (5656) mbedtls: ssl_client.c:919 => write client hello

I (5666) mbedtls: ssl_msg.c:2783 => write handshake message

I (5666) mbedtls: ssl_msg.c:2943 => write record

I (5676) mbedtls: ssl_msg.c:3080 <= write record

I (5676) mbedtls: ssl_msg.c:2904 <= write handshake message

I (5686) mbedtls: ssl_client.c:1012 <= write client hello

I (5696) mbedtls: ssl_msg.c:2353 => flush output

I (5696) mbedtls: ssl_msg.c:2367 message length: 246, out_left: 246

I (5706) mbedtls: ssl_msg.c:2374 ssl->f_send() returned 246 (-0xffffff0a)

I (5716) mbedtls: ssl_msg.c:2401 <= flush output

I (5716) mbedtls: ssl_tls.c:4525 client state: MBEDTLS_SSL_SERVER_HELLO

I (5726) mbedtls: ssl_tls12_client.c:1193 => parse server hello

I (5736) mbedtls: ssl_msg.c:4189 => read record

I (5736) mbedtls: ssl_msg.c:2155 => fetch input

I (5746) mbedtls: ssl_msg.c:2295 in_left: 0, nb_want: 5

I (5746) mbedtls: ssl_msg.c:2315 in_left: 0, nb_want: 5

I (5756) mbedtls: ssl_msg.c:2318 ssl->f_recv(_timeout)() returned 5 (-0xfffffffb)

I (5766) mbedtls: ssl_msg.c:2340 <= fetch input

I (5766) mbedtls: ssl_msg.c:2155 => fetch input

I (5776) mbedtls: ssl_msg.c:2295 in_left: 5, nb_want: 70

I (5786) mbedtls: ssl_msg.c:2315 in_left: 5, nb_want: 70

I (5786) mbedtls: ssl_msg.c:2318 ssl->f_recv(_timeout)() returned 65 (-0xffffffbf)

I (5796) mbedtls: ssl_msg.c:2340 <= fetch input

I (5806) mbedtls: ssl_msg.c:4261 <= read record

I (5806) mbedtls: ssl_tls12_client.c:1445 server hello, total extension length: 21

I (5816) mbedtls: ssl_tls12_client.c:1659 <= parse server hello

I (5826) mbedtls: ssl_msg.c:2353 => flush output

I (5826) mbedtls: ssl_msg.c:2362 <= flush output

I (5836) mbedtls: ssl_tls.c:4525 client state: MBEDTLS_SSL_SERVER_CERTIFICATE      

I (5836) mbedtls: ssl_tls.c:8186 => parse certificate

I (5846) mbedtls: ssl_msg.c:4189 => read record

I (5856) mbedtls: ssl_msg.c:2155 => fetch input

I (5856) mbedtls: ssl_msg.c:2295 in_left: 0, nb_want: 5

I (5866) mbedtls: ssl_msg.c:2315 in_left: 0, nb_want: 5

I (5866) mbedtls: ssl_msg.c:2318 ssl->f_recv(_timeout)() returned 5 (-0xfffffffb)

I (5876) mbedtls: ssl_msg.c:2340 <= fetch input

I (5886) mbedtls: ssl_msg.c:2155 => fetch input

I (5886) mbedtls: ssl_msg.c:2295 in_left: 5, nb_want: 1038

I (5896) mbedtls: ssl_msg.c:2315 in_left: 5, nb_want: 1038

I (5906) mbedtls: ssl_msg.c:2318 ssl->f_recv(_timeout)() returned 1033 (-0xfffffbf7)

I (5906) mbedtls: ssl_msg.c:2340 <= fetch input

I (5926) mbedtls: ssl_msg.c:4261 <= read record

I (5956) esp-x509-crt-bundle: Certificate validated
I (5956) mbedtls: ssl_tls.c:8299 <= parse certificate

I (5956) mbedtls: ssl_msg.c:2353 => flush output

I (5966) mbedtls: ssl_msg.c:2362 <= flush output

I (5966) mbedtls: ssl_tls.c:4525 client state: MBEDTLS_SSL_SERVER_KEY_EXCHANGE

I (5976) mbedtls: ssl_tls12_client.c:2087 => parse server key exchange

I (5986) mbedtls: ssl_msg.c:4189 => read record

I (5986) mbedtls: ssl_msg.c:2155 => fetch input

I (5996) mbedtls: ssl_msg.c:2295 in_left: 0, nb_want: 5

I (6006) mbedtls: ssl_msg.c:2315 in_left: 0, nb_want: 5

I (6006) mbedtls: ssl_msg.c:2318 ssl->f_recv(_timeout)() returned 5 (-0xfffffffb)

I (6016) mbedtls: ssl_msg.c:2340 <= fetch input

I (6026) mbedtls: ssl_msg.c:2155 => fetch input

I (6026) mbedtls: ssl_msg.c:2295 in_left: 5, nb_want: 305

I (6036) mbedtls: ssl_msg.c:2315 in_left: 5, nb_want: 305

I (6036) mbedtls: ssl_msg.c:2318 ssl->f_recv(_timeout)() returned 300 (-0xfffffed4)

I (6046) mbedtls: ssl_msg.c:2340 <= fetch input

I (6056) mbedtls: ssl_msg.c:4261 <= read record

I (6066) mbedtls: ssl_tls12_client.c:1803 ECDH curve: x25519

I (6096) mbedtls: ssl_tls12_client.c:2457 <= parse server key exchange

I (6096) mbedtls: ssl_msg.c:2353 => flush output

I (6096) mbedtls: ssl_msg.c:2362 <= flush output

I (6106) mbedtls: ssl_tls.c:4525 client state: MBEDTLS_SSL_CERTIFICATE_REQUEST

I (6116) mbedtls: ssl_tls12_client.c:2496 => parse certificate request

I (6116) mbedtls: ssl_msg.c:4189 => read record

I (6126) mbedtls: ssl_msg.c:2155 => fetch input

I (6126) mbedtls: ssl_msg.c:2295 in_left: 0, nb_want: 5

I (6136) mbedtls: ssl_msg.c:2315 in_left: 0, nb_want: 5

I (6146) mbedtls: ssl_msg.c:2318 ssl->f_recv(_timeout)() returned 5 (-0xfffffffb)  

I (6146) mbedtls: ssl_msg.c:2340 <= fetch input

I (6156) mbedtls: ssl_msg.c:2155 => fetch input

I (6166) mbedtls: ssl_msg.c:2295 in_left: 5, nb_want: 9

I (6166) mbedtls: ssl_msg.c:2315 in_left: 5, nb_want: 9

I (6176) mbedtls: ssl_msg.c:2318 ssl->f_recv(_timeout)() returned 4 (-0xfffffffc)

I (6186) mbedtls: ssl_msg.c:2340 <= fetch input

I (6186) mbedtls: ssl_msg.c:4261 <= read record

I (6196) mbedtls: ssl_tls12_client.c:2658 <= parse certificate request

I (6196) mbedtls: ssl_msg.c:2353 => flush output

I (6206) mbedtls: ssl_msg.c:2362 <= flush output

I (6206) mbedtls: ssl_tls.c:4525 client state: MBEDTLS_SSL_SERVER_HELLO_DONE

I (6216) mbedtls: ssl_tls12_client.c:2669 => parse server hello done

I (6226) mbedtls: ssl_msg.c:4189 => read record

I (6236) mbedtls: ssl_msg.c:4257 reuse previously read message

I (6236) mbedtls: ssl_msg.c:4261 <= read record

I (6246) mbedtls: ssl_tls12_client.c:2697 <= parse server hello done

I (6246) mbedtls: ssl_msg.c:2353 => flush output

I (6256) mbedtls: ssl_msg.c:2362 <= flush output

I (6266) mbedtls: ssl_tls.c:4525 client state: MBEDTLS_SSL_CLIENT_CERTIFICATE      

I (6266) mbedtls: ssl_tls.c:7592 => write certificate

I (6276) mbedtls: ssl_tls.c:7603 <= skip write certificate

I (6286) mbedtls: ssl_msg.c:2353 => flush output

I (6286) mbedtls: ssl_msg.c:2362 <= flush output

I (6296) mbedtls: ssl_tls.c:4525 client state: MBEDTLS_SSL_CLIENT_KEY_EXCHANGE

I (6296) mbedtls: ssl_tls12_client.c:2712 => write client key exchange

I (6656) mbedtls: ssl_msg.c:2783 => write handshake message

I (6656) mbedtls: ssl_msg.c:2943 => write record

I (6656) mbedtls: ssl_msg.c:2353 => flush output

I (6666) mbedtls: ssl_msg.c:2367 message length: 42, out_left: 42

I (6676) mbedtls: ssl_msg.c:2374 ssl->f_send() returned 42 (-0xffffffd6)

I (6676) mbedtls: ssl_msg.c:2401 <= flush output

I (6686) mbedtls: ssl_msg.c:3080 <= write record

I (6686) mbedtls: ssl_msg.c:2904 <= write handshake message

I (6696) mbedtls: ssl_tls12_client.c:3207 <= write client key exchange

I (6706) mbedtls: ssl_msg.c:2353 => flush output

I (6706) mbedtls: ssl_msg.c:2362 <= flush output

I (6716) mbedtls: ssl_tls.c:4525 client state: MBEDTLS_SSL_CERTIFICATE_VERIFY      

I (6716) mbedtls: ssl_tls12_client.c:3255 => write certificate verify

I (6726) mbedtls: ssl_tls.c:7206 => derive keys

I (6736) mbedtls: ssl_tls.c:7330 => calc verify

I (6736) mbedtls: ssl_tls.c:7349 <= calc verify

I (6756) mbedtls: ssl_tls.c:7257 <= derive keys

I (6756) mbedtls: ssl_tls12_client.c:3277 <= skip write certificate verify

I (6766) mbedtls: ssl_msg.c:2353 => flush output

I (6766) mbedtls: ssl_msg.c:2362 <= flush output

I (6776) mbedtls: ssl_tls.c:4525 client state: MBEDTLS_SSL_CLIENT_CHANGE_CIPHER_SPEC

I (6786) mbedtls: ssl_msg.c:5189 => write change cipher spec

I (6786) mbedtls: ssl_msg.c:2783 => write handshake message

I (6796) mbedtls: ssl_msg.c:2943 => write record

I (6796) mbedtls: ssl_msg.c:2353 => flush output

I (6806) mbedtls: ssl_msg.c:2367 message length: 6, out_left: 6

I (6816) mbedtls: ssl_msg.c:2374 ssl->f_send() returned 6 (-0xfffffffa)

I (6816) mbedtls: ssl_msg.c:2401 <= flush output

I (6826) mbedtls: ssl_msg.c:3080 <= write record

I (6826) mbedtls: ssl_msg.c:2904 <= write handshake message

I (6836) mbedtls: ssl_msg.c:5202 <= write change cipher spec

I (6846) mbedtls: ssl_msg.c:2353 => flush output

I (6846) mbedtls: ssl_msg.c:2362 <= flush output

I (6856) mbedtls: ssl_tls.c:4525 client state: MBEDTLS_SSL_CLIENT_FINISHED

I (6866) mbedtls: ssl_tls.c:8530 => write finished

I (6866) mbedtls: ssl_tls.c:8364 => calc finished tls

I (6876) mbedtls: ssl_tls.c:8395 <= calc finished

I (6876) mbedtls: ssl_msg.c:2783 => write handshake message

I (6886) mbedtls: ssl_msg.c:2943 => write record

I (6896) mbedtls: ssl_msg.c:935 => encrypt buf

I (6896) mbedtls: ssl_msg.c:1474 <= encrypt buf

I (6906) mbedtls: ssl_msg.c:2353 => flush output

I (6906) mbedtls: ssl_msg.c:2367 message length: 45, out_left: 45

I (6916) mbedtls: ssl_msg.c:2374 ssl->f_send() returned 45 (-0xffffffd3)

I (6926) mbedtls: ssl_msg.c:2401 <= flush output

I (6926) mbedtls: ssl_msg.c:3080 <= write record

I (6936) mbedtls: ssl_msg.c:2904 <= write handshake message

I (6936) mbedtls: ssl_tls.c:8632 <= write finished

I (6946) mbedtls: ssl_msg.c:2353 => flush output

I (6946) mbedtls: ssl_msg.c:2362 <= flush output

I (6956) mbedtls: ssl_tls.c:4525 client state: MBEDTLS_SSL_SERVER_CHANGE_CIPHER_SPEC

I (6966) mbedtls: ssl_tls12_client.c:3383 => parse new session ticket

I (6976) mbedtls: ssl_msg.c:4189 => read record

I (6976) mbedtls: ssl_msg.c:2155 => fetch input

I (6986) mbedtls: ssl_msg.c:2295 in_left: 0, nb_want: 5

I (8256) mbedtls: ssl_msg.c:2315 in_left: 0, nb_want: 5

I (8266) mbedtls: ssl_msg.c:2318 ssl->f_recv(_timeout)() returned 5 (-0xfffffffb)  

I (8266) mbedtls: ssl_msg.c:2340 <= fetch input

I (8266) mbedtls: ssl_msg.c:2155 => fetch input

I (8276) mbedtls: ssl_msg.c:2295 in_left: 5, nb_want: 191

I (8286) mbedtls: ssl_msg.c:2315 in_left: 5, nb_want: 191

I (8286) mbedtls: ssl_msg.c:2318 ssl->f_recv(_timeout)() returned 186 (-0xffffff46)

I (8296) mbedtls: ssl_msg.c:2340 <= fetch input

I (8306) mbedtls: ssl_msg.c:4261 <= read record

I (8306) mbedtls: ssl_tls12_client.c:3477 <= parse new session ticket

I (8316) mbedtls: ssl_msg.c:2353 => flush output

I (8316) mbedtls: ssl_msg.c:2362 <= flush output

I (8326) mbedtls: ssl_tls.c:4525 client state: MBEDTLS_SSL_SERVER_CHANGE_CIPHER_SPEC

I (8336) mbedtls: ssl_msg.c:5211 => parse change cipher spec

I (8336) mbedtls: ssl_msg.c:4189 => read record

I (8346) mbedtls: ssl_msg.c:2155 => fetch input

I (8346) mbedtls: ssl_msg.c:2295 in_left: 0, nb_want: 5

I (8356) mbedtls: ssl_msg.c:2315 in_left: 0, nb_want: 5

I (8366) mbedtls: ssl_msg.c:2318 ssl->f_recv(_timeout)() returned 5 (-0xfffffffb)  

I (8376) mbedtls: ssl_msg.c:2340 <= fetch input

I (8376) mbedtls: ssl_msg.c:2155 => fetch input

I (8386) mbedtls: ssl_msg.c:2295 in_left: 5, nb_want: 6

I (8386) mbedtls: ssl_msg.c:2315 in_left: 5, nb_want: 6

I (8396) mbedtls: ssl_msg.c:2318 ssl->f_recv(_timeout)() returned 1 (-0xffffffff)

I (8406) mbedtls: ssl_msg.c:2340 <= fetch input

I (8406) mbedtls: ssl_msg.c:4261 <= read record

I (8416) mbedtls: ssl_msg.c:5259 <= parse change cipher spec

I (8416) mbedtls: ssl_msg.c:2353 => flush output

I (8426) mbedtls: ssl_msg.c:2362 <= flush output

I (8426) mbedtls: ssl_tls.c:4525 client state: MBEDTLS_SSL_SERVER_FINISHED

I (8436) mbedtls: ssl_tls.c:8645 => parse finished

I (8446) mbedtls: ssl_tls.c:8364 => calc finished tls

I (8456) mbedtls: ssl_tls.c:8395 <= calc finished

I (8456) mbedtls: ssl_msg.c:4189 => read record

I (8456) mbedtls: ssl_msg.c:2155 => fetch input

I (8466) mbedtls: ssl_msg.c:2295 in_left: 0, nb_want: 5

I (8476) mbedtls: ssl_msg.c:2315 in_left: 0, nb_want: 5

I (8476) mbedtls: ssl_msg.c:2318 ssl->f_recv(_timeout)() returned 5 (-0xfffffffb)  

I (8486) mbedtls: ssl_msg.c:2340 <= fetch input

I (8496) mbedtls: ssl_msg.c:2155 => fetch input

I (8496) mbedtls: ssl_msg.c:2295 in_left: 5, nb_want: 45

I (8506) mbedtls: ssl_msg.c:2315 in_left: 5, nb_want: 45

I (8506) mbedtls: ssl_msg.c:2318 ssl->f_recv(_timeout)() returned 40 (-0xffffffd8)

I (8516) mbedtls: ssl_msg.c:2340 <= fetch input

I (8526) mbedtls: ssl_msg.c:1510 => decrypt buf

I (8526) mbedtls: ssl_msg.c:2121 <= decrypt buf

I (8536) mbedtls: ssl_msg.c:4261 <= read record

I (8536) mbedtls: ssl_tls.c:8715 <= parse finished

I (8546) mbedtls: ssl_msg.c:2353 => flush output

I (8546) mbedtls: ssl_msg.c:2362 <= flush output

I (8556) mbedtls: ssl_tls.c:4525 client state: MBEDTLS_SSL_FLUSH_BUFFERS

I (8566) mbedtls: ssl_tls12_client.c:3585 handshake: done

I (8566) mbedtls: ssl_msg.c:2353 => flush output

I (8576) mbedtls: ssl_msg.c:2362 <= flush output

I (8586) mbedtls: ssl_tls.c:4525 client state: MBEDTLS_SSL_HANDSHAKE_WRAPUP        

I (8586) mbedtls: ssl_tls.c:4617 <= handshake

I (8596) mbedtls: ssl_msg.c:6044 => write

I (8596) mbedtls: ssl_msg.c:2943 => write record

I (8606) mbedtls: ssl_msg.c:935 => encrypt buf

I (8616) mbedtls: ssl_msg.c:1474 <= encrypt buf

I (8616) mbedtls: ssl_msg.c:2353 => flush output

I (8616) mbedtls: ssl_msg.c:2367 message length: 142, out_left: 142

I (8626) mbedtls: ssl_msg.c:2374 ssl->f_send() returned 142 (-0xffffff72)

I (8636) mbedtls: ssl_msg.c:2401 <= flush output

I (8636) mbedtls: ssl_msg.c:3080 <= write record

I (8646) mbedtls: ssl_msg.c:6066 <= write

I (8656) mbedtls: ssl_msg.c:5782 => read

I (8656) mbedtls: ssl_msg.c:4189 => read record

I (8666) mbedtls: ssl_msg.c:2155 => fetch input

I (8666) mbedtls: ssl_msg.c:2295 in_left: 0, nb_want: 5

I (8676) mbedtls: ssl_msg.c:2315 in_left: 0, nb_want: 5

I (8676) mbedtls: ssl_msg.c:2318 ssl->f_recv(_timeout)() returned 5 (-0xfffffffb)  

I (8686) mbedtls: ssl_msg.c:2340 <= fetch input

I (8696) mbedtls: ssl_msg.c:2155 => fetch input

I (8696) mbedtls: ssl_msg.c:2295 in_left: 5, nb_want: 4429

I (8706) mbedtls: ssl_msg.c:2315 in_left: 5, nb_want: 4429

I (8706) mbedtls: ssl_msg.c:2318 ssl->f_recv(_timeout)() returned 4424 (-0xffffeeb8)

I (8716) mbedtls: ssl_msg.c:2340 <= fetch input

I (8756) mbedtls: ssl_msg.c:1510 => decrypt buf

I (8766) mbedtls: ssl_msg.c:2121 <= decrypt buf

I (8796) mbedtls: ssl_msg.c:4261 <= read record

I (8796) mbedtls: ssl_msg.c:5942 <= read

I (8796) esp_https_ota: Starting OTA...
I (8796) esp_https_ota: Writing to partition subtype 16 at offset 0x110000
I (8806) mbedtls: ssl_msg.c:5782 => read

I (8816) mbedtls: ssl_msg.c:5942 <= read

I (8816) mbedtls: ssl_msg.c:5782 => read

I (8816) mbedtls: ssl_msg.c:5942 <= read

E (8826) esp_https_ota: Mismatch chip id, expected 0, found 18242
E (8836) simple_ota_example: Firmware upgrade failed
```

**Comment by nileshkale123** [comment]
Could you please verify if the OTA image is downloadable from a browser on a device within the same network?

**Comment by AxelLin** [comment]
@nileshkale123 What was fixed?

**Comment by nileshkale123** [comment]
@AxelLin , we were unable to reproduce this issue on our end, and we have not received the requested files from @leehakgun . To confirm, we tested this example ourselves and it executed successfully. Therefore, we have closed this issue.

If you encounter this issue again, please feel free to reopen it and provide the necessary files and details about your work environment.
