### ISSUE TITLE
Certification Test Example for ESP32S2 Chip (IDFGH-13267)

### ISSUE THREAD

**Issue by bitmerse** [espressif/esp-idf#14199]
### Is your feature request related to a problem?

Can you please add support for the ESP32S2 chip in the Certification Test Example? We need it for RF certification testing our custom hardware solution with ESP32S2 chip.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, sorry for slow turnaround, for certification related issues, please help check https://www.espressif.com/en/support/services#certification, thanks.
