### ISSUE TITLE
Crash on STA mode

### ISSUE THREAD

**Issue by abiliojr** [espressif/esp-idf#142]
Connecting to a network in STA mode causes guru meditation errors after a few seconds.

For more detail on users reporting it, [see this](https://forum.pycom.io/topic/343/crash-when-connecting-to-my-home-wifi-router.)

The reports point that this started happening after some changes to the IDF a few weeks ago.

**Comment by ether42** [comment]
FYI, I already linked this thread in #133.

**Comment by espuser** [comment]
Hi,
see issue 119, was 21 Nov up to now WiFi is not usable for me

**Comment by igrr** [comment]
Fixed in master.
