### ISSUE TITLE
[ESP-WIFI-MESH] Mesh devices stop working when Root Node is in mesh sleep mode. (IDFGH-13271)

### ISSUE THREAD

**Issue by andy-danieal** [espressif/esp-idf#14202]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

The problem seems to be with the **Root Node's sleep mode**. If I Set SLEEP MODE on ROOT Node, then this issue occurs, but **if Remove SLEEP MODE on ROOT Node, then devices work properly.** Can anyone please help me understand what might be happening?

**Note:-** Only added sleep mode in Root Node.

**Old code**

ESP_ERROR_CHECK(esp_mesh_disable_ps());

**New code**

ESP_ERROR_CHECK(esp_mesh_enable_ps());

/**  After Mesh esp_mesh_start() **/
ESP_ERROR_CHECK(esp_mesh_set_active_duty_cycle(50, MESH_PS_DEVICE_DUTY_REQUEST));
ESP_ERROR_CHECK(esp_mesh_set_network_duty_cycle(50, -1, MESH_PS_NETWORK_DUTY_APPLIED_ENTIRE));

**Comment by zhangyanjiaoesp** [comment]
@andy-danieal 
Do you enable PS on root device only? Or both root and node devices?
what do you mean by saying `stop working` ? Can you provide a log to illustrate the problem ?

**Comment by andy-danieal** [comment]
@zhangyanjiaoesp 

>Do you enable PS on root device only? Or both root and node devices?

Yes, Enable PS **ONLY on Root device**.

>what do you mean by saying stop working ? Can you provide a log to illustrate the problem ?

Not connected to Mesh network. 


We have attached child node logs with Enable PS mode and Disable PS Mode
[Disable-PS-Child-Mode.log](https://github.com/user-attachments/files/16280417/Disable-PS-Child-Mode.log)
[Enable-PS-Child-Mode.log](https://github.com/user-attachments/files/16280418/Enable-PS-Child-Mode.log)

**Comment by zhangyanjiaoesp** [comment]
@andy-danieal When you enable the mesh PS on the root device, you should also enable the mesh PS on the node device, otherwise the node device can't find the root.

**Comment by andy-danieal** [comment]
> @zhangyanjiaoesp mentioned in the comments that enabling mesh PS on the root device also requires enabling mesh PS on the child node device. 
**This is not mentioned in the [ESP-WIFI-MESH documentation](https://docs.espressif.com/projects/esp-idf/en/stable/esp32/api-reference/network/esp-wifi-mesh.html).**

Could you please explain Why is this happening?

**Comment by zhangyanjiaoesp** [comment]
@andy-danieal When the node device receive the mesh AP's beacon, it will check the mesh PS state, only when both the mesh AP and myself support mesh PS, or neither supports mesh PS, a mesh network can be formed.
we will update the mesh documentation.
