### ISSUE TITLE
[TW#17198] BLE client search and AWS simultaneously

### ISSUE THREAD

**Issue by denyip** [espressif/esp-idf#1420]
i found that when I perform BLE client search, AWS MQTT will disconnect, and after the ble client search finished, the mqtt will be re-connected again, is it normal?

**Comment by TianHao-Espressif** [comment]
Please try to make scan interval - scan window >= 150ms, and the scan window <600ms, please.

**Comment by FayeY** [comment]
Closing due to lack of response, please feel free to reopen if this is still an issue. Thanks.
