### ISSUE TITLE
[ESP-WIFI-MESH] Too much Heap used in ESP-WIFI-Mesh Root node (IDFGH-13302)

### ISSUE THREAD

**Issue by andy-danieal** [espressif/esp-idf#14229]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

ESP32-S2 available RAM size is **154KB**. and ESP-WIFI-MESH API takes up approx **88KB**. and my other tasks will need another *16KB*. 
**That leaves just 50KB of heap space.**

**As per the attached logs,**
[gw-heap-log.txt](https://github.com/user-attachments/files/16332320/gw-heap-log.txt)

I've been having an issue where each child node in the ESP-IDF Mesh stack uses **2KB of heap memory once it's connected to the root node.** This doesn't seem right and is causing memory issues for me. 

This is important for me to know to ensure 100 devices have enough memory to connect Root node. Thanks!

**Comment by zhangyanjiaoesp** [comment]
@andy-danieal 
The max connection of the softAP is 10, the 2KB heap memory is only for the STAs that are diectly connected. If there are 100 devices in the mesh network, other nodes can share the memory pressure.

**Comment by zhangyanjiaoesp** [comment]
@andy-danieal Can we close this issue?
