### ISSUE TITLE
Please answer / reopen https://github.com/espressif/esp-idf/issues/6270 (IDFGH-13330)

### ISSUE THREAD

**Issue by dannybackx** [espressif/esp-idf#14249]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Questions about https://github.com/espressif/esp-idf/issues/6270 , see latest comment.
Please revisit.

I am posting this in a new issue because I can't reopen the old issue, and I'm not sure if the comments on a closed issue go anywhere except to /dev/null .

**Comment by david-cermak** [comment]
Have reopened the original issue, closing this one.
