### ISSUE TITLE
[TW#17222] Low Power Amplifier

### ISSUE THREAD

**Issue by hberjanin** [espressif/esp-idf#1427]
Hello, 
I will like to know when will be available the low noise amplifier: example code and schematics. Thanks in advance

**Comment by ginkgm** [comment]
we're working on this, but it seems to be long before release.

are you sure your signal is in the range of +/- 2mV?

**Comment by hberjanin** [comment]
It is lower than that level. it should be in uVolts.

**Comment by ginkgm** [comment]
okay, in that case LNA would help.

**Comment by igrr** [comment]
Closing as duplicate of https://github.com/espressif/esp-idf/issues/814.
