### ISSUE TITLE
ESP32-S3 miscommunication with IP101GRI Ethernet PHY (IDFGH-13383)

### ISSUE THREAD

**Issue by ViliusZalenas** [espressif/esp-idf#14293]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Hi,

First of all, I am complete beginner to the github. Main purpose of this post is ask for help rather than to report an obvious bug, so if its not the best place for such post, please excuse my inexperience and redirect me to the more appropriate place Thank you in advance.

I am trying to replicate ESP Ethernet DEV kit (at least the ethernet part of if) on my custom PCB that I will be using for Ethernet application. I consistently followed the manufacturer's schematic (in the attachments.)  All the wiring is tested like a 100 times. I absolutely guarantee that everything you see in my schematics is indeed implemented on the PCB (Schematics are in the attachments). The ESP part works flawlessly, it flashes and runs perfectly. However my problems occur in the ESP-PHY communication level. The ESP can not fully initialize the PHY, I get false logs (for example, I sometimes get ,,Ethernet link up" log when there is no ethernet cable attached etc.) The logs related with PHY are completely unpredictable. One exact log example is in the attachments.

I am testing my board with manufacturers provided ESP code (ESP-IDF->examples->ethernet->basic). That code has to send a dynamic IP request to the DHCP server and obtain it, but as you can tell, my ESP is not obtaining the dynamic IP. I am absolutely sure that all the connections are right, and my DHCP server is up and running. If I test the exact same code with the ESP Ethernet Dev kit, it works perfectly.

Hope I explained the problem well enough so far. I tried both running the 50 MHz clock from the PHY CLKO as the reference, but I settled on sourcing the 50 MHz clock from the ESP GPIO0 pin and using an inverter right before the PHY's CLKI pin. In any case, I made sure I get nice and continuous real and the inverted 50 MHz clocks (picture in the attachments.) I also probed the MDIO and MDC lines. I can capture occasional MDIO packets, but the clock line MDC always stays low. That is an obvious problem but I guess that is a consequence of some other mistake, rather than the cause. In any case, I have settled on this problem for a couple of weeks now and I am absolutely out of clue what could be wrong, what else can I try. Any observations about the MDC or any other possible solutions are highly appreciated.

P.S. If I missed some crucial details about this problem, just let me know.

![50MHz_clocks](https://github.com/user-attachments/assets/23aadf80-2f07-457a-9a09-aeea496f03e9)
[ESP32_Ethernet_schematics.pdf](https://github.com/user-attachments/files/16468104/ESP32_Ethernet_schematics.pdf)
[logs.txt](https://github.com/user-attachments/files/16468106/logs.txt)
![Schematics](https://github.com/user-attachments/assets/18ba019c-171f-4ac8-b34c-345fcce7db30)
![Schematics2](https://github.com/user-attachments/assets/1082dfc6-f920-4dfd-b6c4-de56361f346d)

**Comment by kostaond** [comment]
This exact issue has been already actively discussed on the [forum](https://www.esp32.com/viewtopic.php?f=2&t=40785).
