### ISSUE TITLE
Get status code from Esp OTA HTTP (IDFGH-13394)

### ISSUE THREAD

**Issue by LouisMaiaDev** [espressif/esp-idf#14302]
### Is your feature request related to a problem?

Running HTTP OTA for Esp, the "esp_https_ota_perform()" function does not return the status code. If you make a firmware image available on a host server and remove it, the function will show the log "File not found" but will continue to try to download the image. In fact, it is possible to notice that even when faced with this error, if you call the "esp_https_ota_get_image_len_read()" function after the "esp_https_ota_perform()" function you will notice that it will continue to return a value greater than 0; this doesn't make any sense, since there is no more image available on the server.

### Describe the solution you'd like.

The solution is simple: create the public funtion esp_https_ota_get_status_code(esp_https_ota_handle_t * http_ota_handle) to allow get the last status code logged. This will allow the developer to make precise interventions in their code.

**Comment by JasonYan324** [comment]
focus on this issue, wating for the reslut

**Comment by nileshkale123** [comment]
@LouisMaiaDev 

Thank you for reporting this issue. 

I attempted to reproduce the behavior on my setup by hosting a local Python-based server using [python based server](https://github.com/espressif/esp-idf/tree/master/examples/system/ota#python-based-server) but I was unable to replicate the problem. 

Could you please share more details about your setup or any specific steps you followed that might help in reproducing the issue? This information will be crucial for us to investigate further.

**Comment by LouisMaiaDev** [comment]
Yes, I can!
It's quite simple. Host the Esp firmware image on Google Drive or AWS (which is the way I'm using it) and launch Esp FOTA. If you still cannot reproduce the error, post here and I will publish the image that proves the existence of this error. As a solution, I had to implement the solution mentioned above in Espressif's HAL and this way I was able to intervene and handle this error appropriately.

**Comment by nileshkale123** [comment]
Hello @LouisMaiaDev ,

Could you please share the respective OTA image? I could not reproduce the issue using the image uploaded to Google Drive, which is approximately 960KB in size.

Additionally, it would be greatly appreciated if you could share the patch detailing the changes you made to the file, as mentioned above.

**Comment by nileshkale123** [comment]
Hi @LouisMaiaDev 

I have created a patch to address the issue. Please review it and let me know if this meets your requirements or if any additional changes are needed. 

[api_to_get_last_status_logged.txt](https://github.com/user-attachments/files/16884753/api_to_get_last_status_logged.txt)

Thanks.

**Comment by LouisMaiaDev** [comment]
Show, good! Very good @nileshkale123 !
