### ISSUE TITLE
JTAG stepping through code ... SIGTRAP in xQueueGenericReceive

### ISSUE THREAD

**Issue by nkolban** [espressif/esp-idf#1432]
While using JTAG with a WROVER DevKit V3, I am able to step through my code ... however at random times in any given session, my debugging stops with gdb jumping me to a SIGTRAP reported as:

```
Program received signal SIGTRAP, Trace/breakpoint trap.
[Switching to Thread 1073412716]
xQueueGenericReceive (xQueue=0x3ffaea14, pvBuffer=0x0, xTicksToWait=4294967295, xJustPeeking=0)
    at /home/kolban/particle_esp32/esp-idf-v3.0-rc1/components/freertos/./queue.c:1455
1455			taskENTER_CRITICAL(&pxQueue->mux);
(gdb) 
```

For example ...
If I start my app using gdb and then place a break at main and continue the app, I wake up in main just fine.  If I then step over the next statements after some time (it may be the first statement, it may be the 10th statement), this SIGTRAP occurs.

Is there a recipe to ignore this or otherwise properly handle it?  I can recreate at will and will be delighted to provide any diagnostics needed.

**Comment by igrr** [comment]
Hi @nkolban, this part of the documentation mentions how to generate log files from OpenOCD and GDB: http://esp-idf.readthedocs.io/en/latest/api-guides/jtag-debugging/tips-and-quirks.html#jtag-debugging-tip-reporting-issues

**Comment by nkolban** [comment]
Thank you sir.  Will review and repost the extra details within 24 hours.  Many thanks again.

**Comment by nkolban** [comment]
Closing issue here ... and will open on the correct repository found here:

https://github.com/espressif/openocd-esp32/issues
