### ISSUE TITLE
GPIO34 as RX for GPS TX (IDFGH-13450)

### ISSUE THREAD

**Issue by smjacques** [espressif/esp-idf#14356]
### Answers checklist.

- [x] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

I'm using the ESP32-Wrover-E to develop a device using multiple sensors and a GPS module (Quectel L76L-M33). As I'm running out of GPIOs, I'm looking to use the GPS TX connected to the GPIO34 as the RX. Something like this:

![image](https://github.com/user-attachments/assets/02e4e93e-2280-44a4-8f12-fceb787f067c)

Could I use input only as RX? Should it be done using pull-up resistor?

**Comment by songruo** [comment]
Yes, GPIO34 can be used as the RX. And external pull-up resistor is not necessary.
