### ISSUE TITLE
[TW#17251] Feature Request: FreeRTOS 10 -- Stream Buffers & Message Buffers

### ISSUE THREAD

**Issue by hchaudhary1** [espressif/esp-idf#1436]
ESP-IDF team:
Is it possible to backport these amazing new features of FreeRTOS 10?

https://www.freertos.org/RTOS-stream-buffer-API.html
https://www.freertos.org/RTOS-message-buffer-API.html

**Comment by RichardBarry** [comment]
You may be able to just include the stream_buffer.c and stream_buffer.h files from V10 in a V9 project.  That will give you the API.  I think the only dependency is Direct To Task Notifications, were are also available in V9 (assuming that it the base version you are wishing to back port to)..

**Comment by hchaudhary1** [comment]
Do I need to allocate any functions to the IRAM, or is executing these kernel level functions flash ok?

**Comment by hchaudhary1** [comment]
does not work..
looks like notify functionality is missing in the latest IDF.. base FreeRTOS version is v8

**Comment by hchaudhary1** [comment]
got it to work... pull request added #1447 
https://github.com/espressif/esp-idf/pull/1447
