### ISSUE TITLE
[doc error] minimum esp32c3 chip version to support secure boot v2  (IDFGH-13478)

### ISSUE THREAD

**Issue by xiongyu0523** [espressif/esp-idf#14377]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

the docs says secure boot v2 support esp32c3 chip ver v3.0 onward, but the latest esp32c3 chip ver is v1.1. I guess it is a copy bug from older esp document. Please correct and let us know what is minimum version to support this feature for esp32c3

https://github.com/espressif/esp-idf/blob/d7ca8b94/docs/en/security/secure-boot-v2.rst

**Comment by mahavirj** [comment]
@xiongyu0523 

Minimum supported version for ESP32-C3 should be v0.3 (ECO3). We will fix the documentation part.
