### ISSUE TITLE
Add esp_pthread function implementations for linux target (IDFGH-13489)

### ISSUE THREAD

**Issue by cristianfunes79** [espressif/esp-idf#14387]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Current esp32 implementations for linux target are just empty functions. This issue is to add functionality to such functions.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting and contribution again, changes have been merged withhttps://github.com/espressif/esp-idf/commit/4c7d9f9859e13bfed9137ef59418a06b18e848c8 in PR https://github.com/espressif/esp-idf/pull/14384.
