### ISSUE TITLE
Question regarding to rtc_gpio_isolate() (IDFGH-13481)

### ISSUE THREAD

**Issue by mike-2020** [espressif/esp-idf#14380]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

5.2.2

### Espressif SoC revision.

ESP32S3

### Operating System used.

Linux

### How did you build your project?

Command line with CMake

### If you are using Windows, please specify command line type.

None

### Development Kit.

ESP32S3, with 8M PSRAM

### Power Supply used.

USB

### What is the expected behavior?

The document mentions that rtc_gpio_isolate() can be used to reduce current leakage for those PINs which have external pullup. But this function only works for RTC GPIOs. What about those non-RTC GPIOs? I2C PINs do have external pullup. How can I avoid current leakage for I2C PINs during deep sleep?

### What is the actual behavior?

See previous section.

### Steps to reproduce.

See previous section.

**Comment by songruo** [comment]
Are you sure your I2C pins have current leakage in deep sleep? IDF should have guaranteed no leakage from the digital IOs except for the ones that you have configured to be hold during the deep sleep.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to inactivity, feel free to reopen with more updates.
