### ISSUE TITLE
I2C will always fail to read data as master

### ISSUE THREAD

**Issue by FlavioBayer** [espressif/esp-idf#1440]
Commit d78be97154590ae5d48ebbb900182711c035274e has introduced a check in order to assert the number of bytes to read using I2C when acting as master: https://github.com/espressif/esp-idf/blob/d78be97154590ae5d48ebbb900182711c035274e/components/driver/i2c.c#L1008

This assertion will only consider length less than 1 (0 bytes to read) as valid, which obviosly make no sense and is not the expected behavior.
If something, it should assert data_len>0 or data_len>=0 (which is not required since it is unsigned anyways and the assertion would not be needed).

**Comment by PerMalmberg** [comment]
There is already a PR for this, merge pending.. https://github.com/espressif/esp-idf/pull/1443

**Comment by projectgus** [comment]
Fixed in master now (backport to v3.0 branch coming soon), sorry for the inconvenience.
