### ISSUE TITLE
Include application version in CoreDump (IDFGH-13525)

### ISSUE THREAD

**Issue by valkuc** [espressif/esp-idf#14416]
### Is your feature request related to a problem?

In situations when you have multiple devices with different software versions it is not possible to distinguish to with version core dump is related. The device even can be updated from version 1.0 to 1.1, but the stored core dump in flash will be collected earlier for the previous version.

### Describe the solution you'd like.

Include software version (result of call to `esp_app_get_description()`) in core dump.

**Comment by valkuc** [comment]
I just figured out that the CodeDump has ELF sha-256 checksum. I think this is more than enough to match core dump with corresponding ELF file.
I guess feature request can be closed.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting and sharing the updates, feel free to reopen.
