### ISSUE TITLE
GATTS enhancement request

### ISSUE THREAD

**Issue by chegewara** [espressif/esp-idf#1441]
I would like to ask to add option in GATTS stack that will allow us to response on GATT_MTU_EVT with our own value or at least to setup max MTU allowed value with which bluedroid stack could have respond on request from client. Right now we dont even have an option to deny MTU request, so we relly on client code which not always is our own code.
Thanks.

**Comment by heyinling** [comment]
maybe `esp_ble_gatt_set_local_mtu` could do the job

**Comment by chegewara** [comment]
This function is not documented yet, but yes it seems to works. 
Now im missing just one function, to retrieve local mtu value.
