### ISSUE TITLE
The programming guide does not contain any description of the flash and PSRAM speed rates for the ESP32-S3-FH4R2 model.编程指南内，没有关于ESP32-S3-FH4R2关于flash与psram速率的描述 (IDFGH-13542)

### ISSUE THREAD

**Issue by caidamao** [espressif/esp-idf#14432]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

我翻阅了编程指南，关于S3中关于flash与psram速率的章节，只提及了F8R8\F4R8\F4R4三种规格。但是我期望使用的型号是FH4R2，编程指南及技术手册内没有明确写清楚支持的flash速率。
I have gone through the programming guide, specifically the section regarding flash and PSRAM speed rates for the S3, and it only mentions the F8R8, F4R8, and F4R4 specifications. However, the model I intend to use is FH4R2, and the programming guide as well as the technical manual do not clearly state the supported flash speed rates for this model.
![image](https://github.com/user-attachments/assets/40840690-0814-4831-b44a-44df963eac33)
![image](https://github.com/user-attachments/assets/7e72339b-0be5-480b-8189-3261d448209f)

这个是对应文档的链接：https://docs.espressif.com/projects/esp-idf/zh_CN/latest/esp32s3/api-guides/flash_psram_config.html#f8r8

**Comment by Icarus113** [comment]
In the programming guide chapter you referred (https://docs.espressif.com/projects/esp-idf/zh_CN/latest/esp32s3/api-guides/flash_psram_config.html#f8r8), there is a [terminology](https://docs.espressif.com/projects/esp-idf/zh_CN/latest/esp32s3/api-guides/flash_psram_config.html#id1), which says 
```
F stands for flash, R stands for PSRAM, x stands for line mode. e.g., F4R4 stands for an ESP32-S3 with Quad flash and Quad PSRAM.
```

So here in this doc the FxRx is not referring to the chip ordering code.

WRT the ESP32-S3FH4R2, it falls in F4R4 type.
