### ISSUE TITLE
BT: Security Manager

### ISSUE THREAD

**Issue by chegewara** [espressif/esp-idf#1446]
Is it just log message or its error message?

`E (289410) BT: Security Manager: BTM_SetEncryption busy, enqueue request`

**Comment by Yulong-espressif** [comment]
@chegewara This message means the last time encryption has not been completed, but also launched a second encryption.

**Comment by chegewara** [comment]
Its seems to be my issue. Im trying to connect windows laptop to esp32-HID device. I have setup in my esp32 server:
- ESP_GATTS_CONNECT_EVT with call to esp_ble_set_encryption(param->connect.remote_bda, ESP_BLE_SEC_ENCRYPT_NO_MITM)
- since windows is trying to connect with security request and im doing the same, then we have mentioned message

Thanks
