### ISSUE TITLE
Bootloader update/upgrade on new ESP-IDF major version (IDFGH-13587)

### ISSUE THREAD

**Issue by eriksl** [espressif/esp-idf#14474]
### Is your feature request related to a problem?

This is not really a feature request (although it might be, depending on your answer). I could not find any documentation on this.

When IDF is upgraded from v5 to v6 at some time in the future, will the (v5) boot loader still be able to load v6 images?

This is something I will need, because my ESP32s will be at unreachable places, where I cannot simply put an USB plug in.

Or alternatively, will there be an API that allows the boot loader to be upgraded OTA? I know I can come up with something like that myself, just overwrite the flash sectors. But it feels a bit odd to use the OTA system for the image and then have to kludge something myself for the boot loader.

**Comment by KaeLL** [comment]
#14195

**Comment by KonstantinKondrashov** [comment]
Hi @eriksl!
> will the (v5) boot loader still be able to load v6 images?

Yes, the v5.x bootloader will be able to load a v6.x application.

> Or alternatively, will there be an API that allows the boot loader to be upgraded OTA?

We are working on this feature. It will be possible to do it, but with some limitations. Bootloader OTA update can not be done safely, if power is dropped in the middle of the writing to the bootloader partition then the device will become unbootable.

> I know I can come up with something like that myself, just overwrite the flash sectors. But it feels a bit odd to use the OTA system for the image and then have to kludge something myself for the boot loader.

Yes, you are right the current OTA component requires not too many changes to support it for bootloader.

**Comment by eriksl** [comment]
That is great news, thanks!

**Comment by KonstantinKondrashov** [comment]
I close this issue. When the bootloader OTA update feature is released then you will see it in #14195. Thanks.
