### ISSUE TITLE
unable to upload file using ota inside esphome (IDFGH-13597)

### ISSUE THREAD

**Issue by jpmangoit** [espressif/esp-idf#14484]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

I'm getting an error when trying to upload firmware using the ESPHome OTA process. Here are the error logs:
Starting update from 192.168.168.182...
[16:23:31][W][esphome.ota:130]: Magic bytes do not match! 0x50-0x4F-0x53-0x54-0x20
[16:23:31][E][component:164]: Component esphome.ota set Error flag: unspecified
[16:23:34][E][component:176]: Component esphome.ota cleared Error flag

when i'm uploading the same file using arduino framwork it uploads successfully but with esp-idf. i 'm always gettting this error.

this is my yaml file :
  name: livingroom
## ESP32 Configuration - ESP-IDF for SSL support
esp32:
  board: esp32dev
  framework:
    type: esp-idf
# Enable Home Assistant
api:
  encryption:
    key: ${API_KEY}
ota:
  password: ${OTA_PASSWORD}
  platform: esphome

## Enable logging
logger:
  level: WARN
## WIFI Configuration
wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}
  power_save_mode: none
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${AP_ssid}
    password: ${AP_password}

captive_portal:

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, this issue is not directly related to ESP-IDF and hence we are closing. Please feel to report to the relevant project. Thanks.
