### ISSUE TITLE
How to use other components in the ULP core (IDFGH-13625)

### ISSUE THREAD

**Issue by Tinyu-Zhao** [espressif/esp-idf#14510]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

My idf version is v5.4-dev-2620-g6673376297-dirty

I would like to try to read the data of the sths34pf80 in the ULP core, but the sths34pf80 will have a lot of extra operations to read/write some registers, and it will take a lot of time if the components are not used.

My main/lp_core has the following directory tree
<img width="320" alt="image" src="https://github.com/user-attachments/assets/85965ccc-f082-41b6-a5af-97bb8b170e12">

where main/lp_core/lpsths34pf80/CMakeLists.txt has the following contents
```
set(EXTRA_COMPONENT_DIRS /Users/tinyu/esp/master/esp-idf/components/ulp)
set(EXTRA_COMPONENT_DIRS /Users/tinyu/esp/master/esp-idf/components/esp_timer)

idf_component_register(SRCS
                        "sths34pf80.c"
                        "sths34pf80-pid/sths34pf80_reg.c"
                    INCLUDE_DIRS
                        "include"
                        "sths34pf80-pid"
                        "/Users/tinyu/esp/master/esp-idf/components/ulp/lp_core/lp_core/include"
						"/Users/tinyu/esp/master/esp-idf/components/esp_timer"
                    REQUIRES
                        esp_timer
                        ulp)
```
The contents of main/CMakeLists.txt are

```
file(GLOB BMI_SRCS BMI270-Sensor-API/*.c)

file(GLOB BMP_SRCS "${CMAKE_SOURCE_DIR}/components/esp-idf-bmx280/*.c")

file(GLOB ESP32ENCODER_SRCS "${CMAKE_SOURCE_DIR}/components/ESP32Encoder/*.c")

set(CMAKE_VERBOSE_MAKEFILE ON)

idf_component_register(
                    SRCS
                        "main.cpp"
                        "i2c_bus.c"
                        "ir_nec_encoder.c"
                        "ir_test.c"
                        "mesh_stick_pink.c"
                        "mesh_stick_green.c"
                        ${BMI_SRCS}
                        ${BMP_SRCS}
                        ${ESP32ENCODER_SRCS}
                    INCLUDE_DIRS
                        ""
                        "BMI270-Sensor-API"
                        "lp_core/lpsths34pf80/include"
                        "lp_core/lpsths34pf80/sths34pf80-pid"
                        "${CMAKE_SOURCE_DIR}/components/ESP32Encoder"
                        "${CMAKE_SOURCE_DIR}/components/esp-idf-bmx280"
						"$ENV{IDF_PATH}/components/driver/i2c/include/driver"
                    REQUIRES
                        ulp spi_flash esp_timer esp_wifi nvs_flash ra01s ESP32Encoder esp-idf-bmx280 esp_driver_i2c driver
                    WHOLE_ARCHIVE esp_timer)

#
# ULP support additions to component CMakeLists.txt.
#
# 1. The LP Core app name must be unique (if multiple components use LP Core).
set(ulp_app_name lp_core_${COMPONENT_NAME})
#
# 2. Specify all C files.
#    Files should be placed into a separate directory (in this case, lp_core/),
#    which should not be added to COMPONENT_SRCS.
set(ulp_lp_core_sources "lp_core/main.c" "lp_core/lpsths34pf80/sths34pf80.c" "lp_core/lpsths34pf80/sths34pf80-pid/lpsths34pf80_reg.c")

#
# 3. List all the component source files which include automatically
#    generated LP Core export file, ${ulp_app_name}.h:
set(ulp_exp_dep_srcs "lp_i2c_main.c")

#
# 4. Call function to build ULP binary and embed in project using the argument
#    values above.
ulp_embed_binary(${ulp_app_name} "${ulp_lp_core_sources}" "${ulp_exp_dep_srcs}")

# ulp_add_project("ulp_build_system_example" "${CMAKE_SOURCE_DIR}/main/lp_core/")
```

Why do I still get a lot of errors when executing esp_timer even though I've requisitioned it in CMakeLists.txt of sth32pf80, and why do I get a lot of errors when executing it?
```
/Users/tinyu/.espressif/tools/riscv32-esp-elf/esp-13.2.0_20240530/riscv32-esp-elf/bin/../lib/gcc/riscv32-esp-elf/13.2.0/../../../../riscv32-esp-elf/bin/ld: CMakeFiles/lp_core_main.dir/Users/tinyu/Developer/Develop/OneBtn/OneBtn_IDF/main/lp_core/lpsths34pf80/sths34pf80.c.obj: in function `delay_ms':
/Users/tinyu/Developer/Develop/OneBtn/OneBtn_IDF/main/lp_core/lpsths34pf80/sths34pf80.c:153:(.text.delay_ms+0x10): undefined reference to `esp_timer_get_time'
/Users/tinyu/.espressif/tools/riscv32-esp-elf/esp-13.2.0_20240530/riscv32-esp-elf/bin/../lib/gcc/riscv32-esp-elf/13.2.0/../../../../riscv32-esp-elf/bin/ld: /Users/tinyu/Developer/Develop/OneBtn/OneBtn_IDF/main/lp_core/lpsths34pf80/sths34pf80.c:164:(.text.delay_ms+0x30): undefined reference to `esp_timer_get_time'
/Users/tinyu/.espressif/tools/riscv32-esp-elf/esp-13.2.0_20240530/riscv32-esp-elf/bin/../lib/gcc/riscv32-esp-elf/13.2.0/../../../../riscv32-esp-elf/bin/ld: /Users/tinyu/Developer/Develop/OneBtn/OneBtn_IDF/main/lp_core/lpsths34pf80/sths34pf80.c:159:(.text.delay_ms+0x50): undefined reference to `esp_timer_get_time'
/Users/tinyu/.espressif/tools/riscv32-esp-elf/esp-13.2.0_20240530/riscv32-esp-elf/bin/../lib/gcc/riscv32-esp-elf/13.2.0/../../../../riscv32-esp-elf/bin/ld: CMakeFiles/lp_core_main.dir/Users/tinyu/Developer/Develop/OneBtn/OneBtn_IDF/main/lp_core/lpsths34pf80/sths34pf80.c.obj: in function `sths34pf80_set_odr':
/Users/tinyu/Developer/Develop/OneBtn/OneBtn_IDF/main/lp_core/lpsths34pf80/sths34pf80.c:128:(.text.sths34pf80_set_odr+0x8): undefined reference to `esp_log_timestamp'
/Users/tinyu/.espressif/tools/riscv32-esp-elf/esp-13.2.0_20240530/riscv32-esp-elf/bin/../lib/gcc/riscv32-esp-elf/13.2.0/../../../../riscv32-esp-elf/bin/ld: /Users/tinyu/Developer/Develop/OneBtn/OneBtn_IDF/main/lp_core/lpsths34pf80/sths34pf80.c:129:(.text.sths34pf80_set_odr+0x28): undefined reference to `esp_log_write'
/Users/tinyu/.espressif/tools/riscv32-esp-elf/esp-13.2.0_20240530/riscv32-esp-elf/bin/../lib/gcc/riscv32-esp-elf/13.2.0/../../../../riscv32-esp-elf/bin/ld: CMakeFiles/lp_core_main.dir/Users/tinyu/Developer/Develop/OneBtn/OneBtn_IDF/main/lp_core/lpsths34pf80/sths34pf80.c.obj: in function `sths34pf80_init':
/Users/tinyu/Developer/Develop/OneBtn/OneBtn_IDF/main/lp_core/lpsths34pf80/sths34pf80.c:80:(.text.sths34pf80_init+0x54): undefined reference to `esp_log_timestamp'
/Users/tinyu/.espressif/tools/riscv32-esp-elf/esp-13.2.0_20240530/riscv32-esp-elf/bin/../lib/gcc/riscv32-esp-elf/13.2.0/../../../../riscv32-esp-elf/bin/ld: /Users/tinyu/Developer/Develop/OneBtn/OneBtn_IDF/main/lp_core/lpsths34pf80/sths34pf80.c:81:(.text.sths34pf80_init+0x74): undefined reference to `esp_log_write'
collect2: error: ld returned 1 exit status
```
Is it like the ulp core where you can't use the normal i2c driver but have to use lp_i2c using esp_log, esp_timer....?

**Comment by Tinyu-Zhao** [comment]
I solved the problem with ulp_lp_core_delay_us alternative esp_timer_get_time and lp_core_printf substitution ESP_LOGX, but where should I find support for ULP cores in the official ESP components, I don't see it in the documentation.

**Comment by SoucheSouche** [comment]
Hi @Tinyu-Zhao, 
you can find all the information concerning the API under "API Reference" > "System API". Then depending on your target you will Have a dedicated ULP section:
- "ULP Coprocesseur Programming" e.g., [on esp32](https://docs.espressif.com/projects/esp-idf/en/v5.3.1/esp32/api-reference/system/ulp.html#ulp-coprocessor-programming)
- "ULP LP-Core Coprocesseur programming" e.g., [on esp32c6](https://docs.espressif.com/projects/esp-idf/en/v5.3.1/esp32/api-reference/system/ulp.html#api-reference)

At the end of the section you will find the subsection "API Reference" like [on esp32c6](https://docs.espressif.com/projects/esp-idf/en/v5.3.1/esp32/api-reference/system/ulp.html#api-reference) for example, where all the API functions are described.

**Comment by Tinyu-Zhao** [comment]
> Hi @Tinyu-Zhao, you can find all the information concerning the API under "API Reference" > "System API". Then depending on your target you will Have a dedicated ULP section:
> 
> * "ULP Coprocesseur Programming" e.g., [on esp32](https://docs.espressif.com/projects/esp-idf/en/v5.3.1/esp32/api-reference/system/ulp.html#ulp-coprocessor-programming)
> * "ULP LP-Core Coprocesseur programming" e.g., [on esp32c6](https://docs.espressif.com/projects/esp-idf/en/v5.3.1/esp32/api-reference/system/ulp.html#api-reference)
> 
> At the end of the section you will find the subsection "API Reference" like [on esp32c6](https://docs.espressif.com/projects/esp-idf/en/v5.3.1/esp32/api-reference/system/ulp.html#api-reference) for example, where all the API functions are described.
> 
> There you should find all supported features on the ULP core.您应该可以在此处找到 ULP 内核上支持的所有功能。

Thank you for your reply.
