### ISSUE TITLE
Encountered strange issues while debugging the serial port with the C6 ULP core (IDFGH-13650)

### ISSUE THREAD

**Issue by Tinyu-Zhao** [espressif/esp-idf#14530]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

I encountered a strange problem when using the ULP core to debug with the serial port, the same code, but the placement is different, there is no other information in the middle, one line is indeed normal output information 'safe_power 125 ccc', the other line is garbled `saæ}ÿpoW.
ª`, and the result of multiple attempts is the same.

<img width="1643" alt="image" src="https://github.com/user-attachments/assets/76f5b74a-67fd-4d9c-80e9-cf5cac3f9526">

**Comment by SoucheSouche** [comment]
Hi @Tinyu-Zhao,
This is strange indeed. We will take a look and come back to you.

**Comment by Tinyu-Zhao** [comment]
> Hi @Tinyu-Zhao, This is strange indeed. We will take a look and come back to you.

Thank you and I will be happy to provide more information.
Current IDF Version is :ESP-IDF v5.4-dev-2620-g6673376297-dirty

**Comment by sudeep-mohanty** [comment]
Hi @Tinyu-Zhao,
What you are observing is likely an issue with the lp_uart driver which does not wait for the UART Tx FIFO to flush out before printing the next string/character. Could you please apply the following patch and let us know if it resolves the issue?

[lp_uart.patch](https://github.com/user-attachments/files/16930554/lp_uart.patch)

**Comment by Tinyu-Zhao** [comment]
> Hi @Tinyu-Zhao, What you are observing is likely an issue with the lp_uart driver which does not wait for the UART Tx FIFO to flush out before printing the next string/character. Could you please apply the following patch and let us know if it resolves the issue?
> 
> [lp_uart.patch](https://github.com/user-attachments/files/16930554/lp_uart.patch)

Thank you for the quick response, it worked properly!
<img width="363" alt="image" src="https://github.com/user-attachments/assets/03faa55a-67d6-45ee-82df-27a18831510f">

**Comment by sudeep-mohanty** [comment]
Thanks for the confirmation @Tinyu-Zhao. I shall do some more tests and make a change.
