### ISSUE TITLE
ESP32S3 with BLK_VERSION_MINOR=3 increased deep sleep / ulp current (IDFGH-13655)

### ISSUE THREAD

**Issue by mindnever** [espressif/esp-idf#14534]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v5.2.2

### Espressif SoC revision.

ESP32-S3 (QFN56) (revision v0.2)

### Operating System used.

macOS

### How did you build your project?

Command line with idf.py

### If you are using Windows, please specify command line type.

None

### Development Kit.

Custom Board

### Power Supply used.

External 5V

### What is the expected behavior?

Have same current consumption as with BLK_VERSION_MINOR=2 chips. 

During sleep, with ulp active and not doing anything but halt instruction every 20ms, with our custom board, consumption should be around **30uA**.

### What is the actual behavior?

Newer esp32s3 chips with BLK_VERSION_MINOR=3 (note that this is the only noticeable difference. Chip version is the same, rom and all the other numbers also match) have increased current of **60uA**.

### Steps to reproduce.

ESP code:

```
#include <stdio.h>
#include <string.h>
#include <inttypes.h>
#include "esp_sleep.h"
#include "ulp.h"
#include "ulp_main.h"
#include "ulp_adc.h"
#include "hal/efuse_hal.h"

extern const uint8_t ulp_main_bin_start[] asm("_binary_ulp_main_bin_start");
extern const uint8_t ulp_main_bin_end[]   asm("_binary_ulp_main_bin_end");

void app_main(void)
{
    printf("CHIP_VERSION: %" PRIu32 "\n", efuse_hal_chip_revision());
    printf("BLK_VERSION: %" PRIu32 "\n", efuse_hal_blk_version());

    ESP_ERROR_CHECK(ulp_load_binary(0, ulp_main_bin_start,
            (ulp_main_bin_end - ulp_main_bin_start) / sizeof(uint32_t)));

    ulp_adc_cfg_t cfg = {
        .adc_n    = 0,
        .channel  = 6,
        .width    = 0,
        .atten    = 3,
        .ulp_mode = ADC_ULP_MODE_FSM,
    };

    ESP_ERROR_CHECK(ulp_adc_init(&cfg));

    ESP_ERROR_CHECK(ulp_set_wakeup_period(0, 20000));

    ESP_ERROR_CHECK(ulp_run(&ulp_entry - RTC_SLOW_MEM));

    ESP_ERROR_CHECK(esp_sleep_enable_ulp_wakeup());

    esp_sleep_pd_config(ESP_PD_DOMAIN_RTC_PERIPH, ESP_PD_OPTION_ON);

    esp_deep_sleep_start();
}
```

ULP code:

```
	.text
	.global entry
entry:
	halt
```

### More Information.

1. The bug is directly related to enabling ADC function, even without actually using it.

2. Additionally, current consumption is also affected by value stored into `RTC_CNTL_BIAS_CONF_REG.RTC_CNTL_DBG_ATTEN_DEEP_SLP` . Current drops to expected 30uA if I forcibly write `RTC_CNTL_DBG_ATTEN_DEEPSLEEP_ULTRA_LOW` value there just before going to sleep (for example in `rtc_sleep_start()`), but since this register and values are completely undocumented, it doesn't seem to be correct way of fixing it.

**Comment by esp-wzh** [comment]
Hi~ @mindnever  

We reviewed this block version update and confirmed that it does not affect power consumption.

1. Can you test a few more chips to rule out individual differences?
2. If ULP is not used and only do deepsleep, is there any difference in their base current?
3. If the chip keep powered but set CHIP_EN to low, is there a difference in their base current?

**Comment by Sherry616** [comment]
Thanks for reporting, will close due to short of feedback, feel free to reopen with more updates. 
Thanks for using our Espressif product!
