### ISSUE TITLE
NVS Encryption Bug - symmetric key not generated inside device and image not encrypted (IDFGH-13675)

### ISSUE THREAD

**Issue by lnayman** [espressif/esp-idf#14551]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v5.3.1

### Espressif SoC revision.

ESP32 WROVER - 8MB PSRAM version

### Operating System used.

Linux

### How did you build your project?

Command line with idf.py

### If you are using Windows, please specify command line type.

None

### Development Kit.

ESP32 WROVER - 8MB PSRAM version

### Power Supply used.

USB

### What is the expected behavior?

When NVS encryption is enabled and I generate the NVS image in plain text outside of the device and then program it to device, the ESP32 fails to generate its own key and this causes the NVS section to NOT be encrypted.

I would expect that if I enable the correct options, that once the NVS plain-text image is programmed, that the device will generate its own key (never seen outside of the device) and allow NVS section to be encrypted

**Here are things that do work:**
- Generating the key outside of the system and then pre-encrypting the NVS and writing the keys and NVS does allow NVS to be encrypted
- Not programming the NVS image into the device BUT instead just having the code do NVS read() /writes() and enabling NVS encryption does manage to generate the key inside the device and encrypt.

### What is the actual behavior?

When NVS encryption is enabled and I generate the NVS image in plain text outside of the device and then program it to device, the ESP32 fails to generate its own key and this causes the NVS section to NOT be encrypted.

### Steps to reproduce.

1. Use python nvs_partition_gen.py generate <nvs key-value pairs file> static_config.bin 0x6000
2. Above will generate a file called static_config.bin that can be programmed to 0x12000 (or whatever address you set up for the NVS partition
3. Make sure in the sdkconfig you enable : CONFIG_NVS_ENCRYPTION=y
4. boot device and notice encryption key does not get generated and NVS section is not encrypted
5. You can use  esp's read flash utility to look at the memory

**Comment by mahavirj** [comment]
@lnayman  

Relevant https://github.com/espressif/esp-idf/issues/12350

If you would like to pre-flash encrypted NVS contents then you can generate the NVS encryption key on the host and then encrypt the partition using the generated key. NVS component does not encrypt the pre-flashed contents which already exist in the NVS partition. 

Please refer to this [guide](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/security/security-features-enablement-workflows.html#enable-nvs-encryption-based-on-flash-encryption) for generating the NVS key partition and encrypted data partition on the host machine. 

Hope this helps!
