### ISSUE TITLE
OpenThread building problem (IDFGH-13689)

### ISSUE THREAD

**Issue by marcokldm02** [espressif/esp-idf#14564]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Hi everyone, 
I'm trying to build an OpenThread Border Router with an Esp32 C6 and an Esp32 H2. I did the installation of ot_br on Esp32 C6 without problems, but when I install ot_rcp on Esp32 H2, I get an error: "RCP is only supported for the SoCs which have IEEE 802.15.4 module".

Can anyone help me? Thank you

**Comment by zwx1995esp** [comment]
Hi @marcokldm02  Which examples did you build? And did you set the target `esp32h2` for building OT_RCP?

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, would you please help share if any updates for the issue? Thanks.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to inactivity, feel free to reopen with more updates.
