### ISSUE TITLE
Add compatibility between VScode and C++ code (IDFGH-13744)

### ISSUE THREAD

**Issue by Bonv1Arnaud** [espressif/esp-idf#14607]
### Is your feature request related to a problem?

Now we can only programme in python ESP from VS code with the espressif library. It will be a good input to add compatibility with C++ code.

### Describe the solution you'd like.

It will be a good input to add compatibility with C++ code.

### Describe alternatives you've considered.

Add reference to follow to allow C++ program with VScode and esspresif environnement

**Comment by ermacv** [comment]
Hello!
Have you checked the C++ examples included in the IDF:
https://github.com/espressif/esp-idf/tree/master/examples%2Fcxx

**Comment by o-marshmallow** [comment]
Hello @Bonv1Arnaud ,

ESP-IDF supports C++, please check the documentation to find all the details: https://docs.espressif.com/projects/esp-idf/en/stable/esp32/api-guides/cplusplus.html

**Comment by sudeep-mohanty** [comment]
Closing the issue as no update is needed in ESP-IDF for it. Please feel free to open a new ticket for further support. Thanks.
