### ISSUE TITLE
LWIP recvmsg IP_PKTINFO support (IDFGH-768)

### ISSUE THREAD

**Issue by SStorm** [espressif/esp-idf#1460]
The later versions of LwIP implement support for recvmsg using IP_PKTINFO, which is very useful when you want to get the actual destination address for received UDP packets. Are there any plans to upgrade the LwIP impl that's bundled with esp-idf at this stage, or should I be looking for alternative solutions? Thanks!

**Comment by TimXia** [comment]
Yes, we are planing to synchronize the latest official LwIP with that in esp-idf. Maybe in the next version.

**Comment by SStorm** [comment]
Are there any milestones for this, i.e. when could this be reasonably expected? i.e. is this 1-2 months or 6+ months away? Thanks!

**Comment by TimXia** [comment]
Maybe 3~4 months.

**Comment by liuzfesp** [comment]
@SStorm LWIP will update to latest version in v3.1 @zhangyanjiaoesp

**Comment by SStorm** [comment]
@zhangyanjiaoesp There's a lot of usages in https://github.com/yarrick/lwip/, i.e. https://github.com/yarrick/lwip/blob/5ee77262bc6003c869b77ea606a4d80b2285d049/src/api/sockets.c

**Comment by zhangyanjiaoesp** [comment]
I will update the lwip master and check it , thanks.

**Comment by SStorm** [comment]
Hi guys, just wanted to check if there's any updated on this? I'm guessing my PR isn't going to be accepted at all?..

**Comment by TimXia** [comment]
@SStorm We are working on it. It will be done in IDF v3.2.

**Comment by zhangyanjiaoesp** [comment]
@SStorm We have update the lwIP in the lastest master, and add the function [lwip_recvmsg](https://github.com/espressif/esp-lwip/blob/18548d1e256f7651fb4da48dbd770556e0eca8ce/src/api/sockets.c#L1256) . You can test if it's useful for you. 
Sorry for replying so later.

**Comment by SStorm** [comment]
@zhangyanjiaoesp thanks! Will try it out as soon as I have a moment.

**Comment by projectgus** [comment]
Reopening as the support for recvmsg() is in ESP-IDF master but we don't have support for IP_PKTINFO yet.

ESP-IDF currently uses a [version of LWIP based on v2.0.3](https://github.com/espressif/esp-lwip) in master. Support for PKTINFO was added to LWIP in commit [2f117add7](http://git.savannah.nongnu.org/cgit/lwip.git/commit/?id=2f117add7) and released in LWIP v2.1.0.

Unfortunately, ESP-IDF will probably not add support for IP_PKTINFO until after we update ESP-LWIP to LWIP v2.1.0 or newer.

**Comment by Alvin1Zhang** [comment]
@projectgus Thanks for the update.

**Comment by freakyxue** [comment]
hi @SStorm 
LwIP 2.1.2 has added this function, we will discuss whether to add this function in LwIP 2.0.3

**Comment by freakyxue** [comment]
hi @SStorm
 LwIP 2.1.2 has added this function，LwIP version of release 4.0 has been upgraded to 2.1.2

**Comment by Alvin1Zhang** [comment]
@SStorm Thanks for reporting. This feature has been supported in ESP-IDF v4.0. If you any other feature/issue request, please help file another ticket. Thanks.
