### ISSUE TITLE
esp32 module,phone read service  cmd,esp32 no response (IDFGH-13753)

### ISSUE THREAD

**Issue by luacerbb** [espressif/esp-idf#14615]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

idf_v4.4.4

### Espressif SoC revision.

ESP32

### Operating System used.

Windows

### How did you build your project?

Command line with idf.py

### If you are using Windows, please specify command line type.

None

### Development Kit.

custom board

### Power Supply used.

USB

### What is the expected behavior?

read ble dev service success

### What is the actual behavior?

read ble dev service no response

### Steps to reproduce.

![23ca0703e90a5c551d4cf777996778a5_compress](https://github.com/user-attachments/assets/87d01e7f-08c5-4fc2-b99a-c0713116594b)

![图片](https://github.com/user-attachments/assets/c8a09500-f6f4-400b-8b35-993a9ee32bef)

wireshark log:

[蓝牙通信异常0828_143459.zip](https://github.com/user-attachments/files/17095739/0828_143459.zip)

**Comment by esp-zhp** [comment]
Does this issue occur every time? Could you provide a method to reproduce the problem?

**Comment by luacerbb** [comment]
> Does this issue occur every time? Could you provide a method to reproduce the problem?

not occur every time,but once occur,esp32 dev need restart to restore normal.I just test connect and disconnect

**Comment by rahult-github** [comment]
Hi @luacerbb , 

 I quickly tried the same at my end, but haven't seen the issue so far. May i request you to please share your sdkconfig also , so we can debug more ?

**Comment by luacerbb** [comment]
[sdkconfig.zip](https://github.com/user-attachments/files/17285864/sdkconfig.zip)

**Comment by rahult-github** [comment]
Hi @luacerbb ,  release/v4.4 is EOL.  Am closing this issue. If you observe it on any other existing branches, please feel free to reopen it.
