### ISSUE TITLE
ESP32-C5 Border Router - OpenThread (IDFGH-13757)

### ISSUE THREAD

**Issue by JonRobo** [espressif/esp-idf#14619]
### Is your feature request related to a problem?

Currently it looks like an open thread border router needs to use 2 ESP32 modules, an H2 to join the OpenThread network and a WiFi module to receive data over a wired communication to then be transmitted over MQTT or any other protocol.

Will the ESP32-C5 be able to support coexistence between WiFi 2.4GHz / 5GHz  and OpenThread?

### Describe the solution you'd like.

Ability to make an OpenThread border router with just 1 ESP32 module

**Comment by chshu** [comment]
Similar to C6, there is only one RF path in C5, so Wi-Fi and Thread can't receive simultaneously, it has a significant impact on performance. Hence the two SoCs solution is recommended.
