### ISSUE TITLE
Is two way communication possible using ESP Now?

### ISSUE THREAD

**Issue by timkoers** [espressif/esp-idf#1461]
I'm trying to setup two way communication with ESP Now.
Since there are no samples that do this, it's a bit of a hassle. 

I've used the provided ESP Now samples and I've merged them together. 

So data received callback on both, on the 'slave' the master is registered as a peer, but when I try to send data from the slave, I get an Internal error.

The master is able to send data to the slave.

The master uses channel 3 and the slave channel 1.

Does the softAP of the master need to be on as well? If yes, does the SSID matter?

**Comment by TimXia** [comment]
It has nothing to do with softAP or SSID. The master and slave should be on the same channel now. We may support different channel in the future.
