### ISSUE TITLE
FAILED: partition_table/partition-table.bin (IDFGH-13763)

### ISSUE THREAD

**Issue by sova32** [espressif/esp-idf#14624]
your oficial code in the doc:
![image](https://github.com/user-attachments/assets/fbf6f5d4-8755-4261-af52-057e9dc98f2c)

![image](https://github.com/user-attachments/assets/44c650d9-fbab-4bca-a587-5d9e40e74823)

what the fuck?!
its not first shit in your doc!

**Comment by igrr** [comment]
@sova32 From the error message, looks like the partition table is okay, but the Flash size is set to 2MB in menuconfig. This partition table requires more space than 2MB. Could you please try switching to 4MB Flash size (CONFIG_ESPTOOLPY_FLASHSIZE_4MB=y)?
