### ISSUE TITLE
uint64_t strange issue

### ISSUE THREAD

**Issue by chegewara** [espressif/esp-idf#1462]
Im having very strange issue. This is my function declaration and as we can see arg is type uint64:
`esp_err_t init(uint64_t arg, gpio_int_type_t); `
but with left shift >=32 im getting warning and bits are not set:
```
warning: left shift count >= width of type [-Wshift-count-overflow]
   enc->init(1<<GPIO_NUM_12 | 1<<GPIO_NUM_13 | 1<<GPIO_NUM_32 | 1<<GPIO_NUM_33, (gpio_int_type_t)GPIO_PIN_INTR_ANYEDGE
```

**Comment by negativekelvin** [comment]
1 is 32-bit, 1ULL is 64-bit

**Comment by chegewara** [comment]
Problem is not with 1, problem is with shifting it by 32 bits. uint64 is treated as 32 bit value.

**Comment by negativekelvin** [comment]
Try it

**Comment by chegewara** [comment]
Thanks, i would never guess it, but it works.
