### ISSUE TITLE
error: empty enum is invalid (IDFGH-13845)

### ISSUE THREAD

**Issue by RDobrinov** [espressif/esp-idf#14694]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v5.3.1 & 5.4-dev ( master branch )

### Operating System used.

Linux

### How did you build your project?

VS Code IDE

### If you are using Windows, please specify command line type.

None

### What is the expected behavior?

Compile without errors

### What is the actual behavior?

Error thrown v5.3.1/esp-idf/components/wifi_provisioning/include/wifi_provisioning/manager.h:214:1: error: empty enum is invalid

### Steps to reproduce.

Disable all protocomm configuration in menuconfig

### Build or installation Logs.

```plain
In file included from /home/xxxxxx/esp/v5.3.1/esp-idf/components/wifi_provisioning/include/wifi_provisioning/scheme_softap.h:20,
                 from /home/xxxxxx/esp/v5.3.1/esp-idf/components/wifi_provisioning/src/scheme_softap.c:16:
/home/xxxxxx/esp/v5.3.1/esp-idf/components/wifi_provisioning/include/wifi_provisioning/manager.h:214:1: error: empty enum is invalid
  214 | } wifi_prov_security_t;
      | ^
```

### More Information.

[bugged code](https://github.com/espressif/esp-idf/blob/6e5a178b3120dced7fa5c29c655cc22ea182df3d/components/wifi_provisioning/include/wifi_provisioning/manager.h#L197-L221)
manager.h define empty enum when all protocomm security versions are unchecked in Component config → Protocomm

**Comment by hrushikesh430** [comment]
Hello @RDobrinov could you please let me know what is your use case? If you want no security you can enable CONFIG_ESP_PROTOCOMM_SUPPORT_SECURITY_VERSION_0 which is equivalent to no security.

**Comment by hrushikesh430** [comment]
Hello @RDobrinov, closing this issue to due no response, please feel free to reopen the issue if you have any queries or issues further.
