### ISSUE TITLE
OpenThread Minimal Thread Device (MTD) for ESP32x devices does not support COAP client (IDFGH-13847)

### ISSUE THREAD

**Issue by simondean** [espressif/esp-idf#14696]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v5.4

### Operating System used.

macOS

### How did you build your project?

Command line with idf.py

### If you are using Windows, please specify command line type.

None

### What is the expected behavior?

When using OpenThread on a ESP32x device (e.g. esp32h2 or esp32c6), with the Minimal Thread Device (MTD) profile, the COAP client should be supported

### What is the actual behavior?

The COAP client cannot be used due to the linker not being able to find any of the implementations of the COAP Client API functions

### Steps to reproduce.

1. Enable the MTD profile via the `CONFIG_OPENTHREAD_MTD=y` setting
2. Include `<openthread/coap.h>`
3. Add a call to `otCoapNewMessage()`
4. Try to build the project and the linker will complain that no implementation is available for that function

### More Information.

I've created a PR with a potential fix for the issue here: https://github.com/espressif/esp-idf/pull/14676

COAP Client is already enabled in ESP IDF's https://github.com/espressif/esp-idf/blob/master/components/openthread/CMakeLists.txt#L48-L54 :

```
    if(CONFIG_OPENTHREAD_FTD OR CONFIG_OPENTHREAD_MTD)
        list(APPEND src_dirs
            "openthread/src/core/backbone_router"
            "openthread/src/core/coap"
            "openthread/src/core/meshcop"
            "openthread/src/core/net"
            "openthread/src/lib/platform")
```

But at the same time, ESP IDF does not enable COAP Client for MTD in https://github.com/espressif/esp-idf/blob/master/components/openthread/private_include/openthread-core-esp32x-mtd-config.h because it does not define `OPENTHREAD_CONFIG_COAP_API_ENABLE 1`

**Comment by chshu** [comment]
https://github.com/espressif/esp-idf/pull/14676#issuecomment-2472337443, closing
