### ISSUE TITLE
Esp32 USB WIFI (IDFGH-13852)

### ISSUE THREAD

**Issue by maaamcube** [espressif/esp-idf#14701]
### Is your feature request related to a problem?

Hi everyone,
Is it possible to add an example to send USB devices through WIFI ? (and many USB's and HUBs when it will be available)
Thanks.

### Describe the solution you'd like.
The Esp32 USB will be a host and can send USB devices through wifi.

_No response_

**Comment by tore-espressif** [comment]
@maaamcube Please don't create multiple tickets for the same requests. Tracked here https://github.com/espressif/esp-idf/issues/14682

**Comment by maaamcube** [comment]
Hi @tore-espressif,
This feature request is for sending USB through WIFI, not for adding multi usb devices and hubs support.
