### ISSUE TITLE
BLE_MESH_SUPPORT_BLE_ADV sends incorrect data since v5.2.2 for both Bluedroid and NimBLE on ESP32 (IDFGH-13873)

### ISSUE THREAD

**Issue by buganini** [espressif/esp-idf#14719]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Last working version: v5.2.1
Target: ESP32
Bluetooth Stack: Both Bluedroid and Nimble

BLE_MESH_SUPPORT_BLE_ADV (ESP BLE Mesh Support → BLE Mesh and BLE coexistence support → Support sending normal BLE advertising packets) sends incorrect data since v5.2.2
With v5.2.1 I can see both adv_data/scan_rsp_data and mesh adv in Android nRF Connect app.
With v5.2.2 I can only see scan_rsp_data and no mesh adv in Android nRF Connect app.

ESP32-C3 is fine with v5.3

**Comment by forx157** [comment]
Hi, @buganini 

Are you saying that the issue only occurs when using ESP32 with IDFv5.2.2? That other chips with different IDF versions do not have any problems?

**Comment by buganini** [comment]
I've only tested on ESP32/ESP32-C3 with different code base, but roughly yes, I think to problem is only on ESP32 with v5.2.2+

**Comment by buganini** [comment]
BTW, on ESP32-C3, I have both legacy/ext adv working fine. ESP32 can only do legacy adv, the issue may be related to switching multiple adv.
