### ISSUE TITLE
Plz add pixiewps libary plzz (IDFGH-13871)

### ISSUE THREAD

**Issue by Rahad1069** [espressif/esp-idf#14717]

**Comment by Rahad1069** [comment]
We want to perform pixie dust attack for cracking wps pin by esp32/esp8266. So that's why, we need the pixiewps libary

**Comment by kapilkedawat** [comment]
Hi @Rahad1069, this is not in our roadplan and will not be part of ESP-IDF.

**Comment by Sherry616** [comment]
Thanks for reporting, we will close this issue. 
Thanks for using our Espressif product!

**Comment by Naster17** [comment]
> ### Is your feature request related to a problem?
> 
> _No response_
> 
> ### Describe the solution you'd like.
> 
> _No response_
> 
> ### Describe alternatives you've considered.
> 
> _No response_
> 
> ### Additional context.
> 
> _No response_

Oh no cringe

**Comment by Naster17** [comment]
> We want to perform pixie dust attack for cracking wps pin by esp32/esp8266. So that's why, we need the pixiewps libary

Oh no cringe
