### ISSUE TITLE
ESP_GAP_BLE_SCAN_TIMEOUT_EVT not called after esp_ble_gap_start_scanning expired duration (IDFGH-13895)

### ISSUE THREAD

**Issue by ezamp** [espressif/esp-idf#14737]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v5.3

### Espressif SoC revision.

ESP32-S3 

### Operating System used.

macOS

### How did you build your project?

VS Code IDE

### If you are using Windows, please specify command line type.

None

### Development Kit.

Custom board

### Power Supply used.

USB

### What is the expected behavior?

After calling the esp_ble_gap_start_scanning(30), I expect that after 30 seconds the ESP_GAP_BLE_SCAN_TIMEOUT_EVT event will be generated. This does not happen, after 30 seconds no event is generated.

### What is the actual behavior?

After 30 seconds, no event is generated

### Steps to reproduce.

1. call the function esp_ble_gap_start_scanning(30)
2. wait until the event generation

**Comment by demayn** [comment]
Hi, I seem to be facing the same issue. How was the issue resolved?

**Comment by ezamp** [comment]
Hi, When the scan finishes, the event  “ESP_GAP_BLE_SCAN_RESULT_EVT” is generated (as for any scan result).
To distinguish a result from the end of the scan you have to check the value of _scan_rst.search_evt_, if it is "ESP_GAP_SEARCH_INQ_RES_EVT" then the event is a result, if it is "ESP_GAP_SEARCH_INQ_CMPL_EVT" then the event is a scan end.

An extract of my code is:
```
case ESP_GAP_BLE_SCAN_RESULT_EVT:
        {
            esp_ble_gap_cb_param_t *scanResult = (esp_ble_gap_cb_param_t *)param;

            [some code]

            if(scanResult->scan_rst.search_evt == ESP_GAP_SEARCH_INQ_RES_EVT)
            {            
                //Is a result
                
                [some code]

            }
            else if(scanResult->scan_rst.search_evt == ESP_GAP_SEARCH_INQ_CMPL_EVT)
            {
               //Is end scan

               [some code]
          
            }
            break;
        }
```

I hope it can be useful to you.

**Comment by demayn** [comment]
thank you very much for the quick reply, that's great!

**Comment by esp-zhp** [comment]
we will update document,thanks for report the issue.
in fact,ESP_GAP_BLE_SCAN_TIMEOUT_EVT is for BLE50 scan.
