### ISSUE TITLE
Console over IP ? (IDFGH-13907)

### ISSUE THREAD

**Issue by diplfranzhoepfinger** [espressif/esp-idf#14747]
# Console over IP ?

Serial Console is quite VERY COOL in ESP32, boosing it over many ohther Platforms which do not have a Serial Console. 

Question: 

if i have a IP Connection but not attatched to Serial Port U0, 

is there a way to see the Console ? Telnet, Web-Client or whatever ? 

Thanks, 

Franz

**Comment by nopnop2002** [comment]
Is this what you mean by Serial Console?

[Console Component](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/console.html#console)

**Comment by diplfranzhoepfinger** [comment]
> By serial console, do you mean Console Component?
> 
> [Console Component](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/console.html#console)
> 

No


> Or do you mean the output destination of ESP_LOGx?

Yes. 
Log by ESP_LOGx and printf.

**Comment by nopnop2002** [comment]
How to redirect ESP_LOGx.

https://github.com/nopnop2002/esp-idf-net-logging

**Comment by diplfranzhoepfinger** [comment]
> How to redirect ESP_LOGx.
> 
> https://github.com/nopnop2002/esp-idf-net-logging

that is what i searched. 
Continue Discussion here: https://github.com/nopnop2002/esp-idf-net-logging/issues/5

**Comment by sudeep-mohanty** [comment]
Closing the issue as this feature-request could be handled outside of IDF. Please feel free to reopen the ticket or open a new one for further support. Thank you.
