### ISSUE TITLE
How do I enable both 2.4G and 5G AP capabilities on the ESP32-C5 (IDFGH-13908)

### ISSUE THREAD

**Issue by Sail-211010** [espressif/esp-idf#14748]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

How do I enable both 2.4G and 5G AP capabilities on the ESP32-C5，
And in the use of automatic switching or need to be in the program at a certain interval to switch channels

**Comment by MaxwellAlan** [comment]
Hi @Sail-211010 

ESP32-C5 only support DBSC (Dual-Band Single Concurrent) not support DBDC (Dual-Band Dual Concurrent).

Thanks.

**Comment by Sail-211010** [comment]
OK,Understood. Thank you.
