### ISSUE TITLE
Toolchain HTTPS Cert invalid (https://dl.espressif.com/dl/xtensa-esp32-elf-linux64-1.22.0-75-gbaf03c2-5.2.0.tar.gz)

### ISSUE THREAD

**Issue by Curclamas** [espressif/esp-idf#1475]
Hello, the certificate for the toolchain-URL (https://dl.espressif.com/dl/xtensa-esp32-elf-linux64-1.22.0-75-gbaf03c2-5.2.0.tar.gz) seams to be invalid as of today.
This breaks our CI-Workflow and raises security concerns. See attached picture:

![image](https://user-images.githubusercontent.com/3130187/34650093-3f4b5c76-f3bb-11e7-80c8-0afc30e09a44.png)

**Comment by Curclamas** [comment]
Issue seams to be fixed!

**Comment by dbagnara** [comment]
Issue seems to be back again. Invalid certificate.
I am not an expert but could the *.espressif.com certificate be used instead of the Lets Encrypt certificate.

![image](https://user-images.githubusercontent.com/8944096/55267808-cdc27e80-52d8-11e9-8aea-53c73f81a32a.png)

**Comment by dbagnara** [comment]
Fixed
