### ISSUE TITLE
ESP-IDF V5.2.3 Bug or Miss Interpret in Compiler at Printf level (IDFGH-13927)

### ISSUE THREAD

**Issue by filzek** [espressif/esp-idf#14766]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

There is an error inside the Printf compiler optmizations and also with the stub.

unsigned long sensor_received = 12345647;
		unsigned long last_sensorid_received = 12345649;
		unsigned long sensor_length = 0;
		struct timeval tv2;
		gettimeofday( & tv2, NULL);
		printf("Time: %ld seconds\n", tv2.tv_sec);  // Separate print for tv.tv_sec

		printf("Before first printf: sensor_received = [%lu]\n", sensor_received);
		printf("RECEIVED [%lu]\n", sensor_received);
		printf("Before second printf: sensor_received = [%lu]\n", sensor_received);

		printf("[%d] [%ld] RX433 Received: SENSOR [%lu] - last_sensorid_received [%lu]\n",
       __LINE__, tv2.tv_sec, sensor_received, last_sensorid_received);

		printf("[%d] RX433 Received: SENSOR [%lu] - last_sensorid_received [%lu]\n",
					 __LINE__, sensor_received, last_sensorid_received);

		printf("RX433 Received: SENSOR [%lu] - last_sensorid_received [%lu]\n",
					 sensor_received, last_sensorid_received);
					 
					 
to validate all kind of possible acttions the code try all kinds.

Before first printf: sensor_received = [12345647]
RECEIVED [12345647]
Before second printf: sensor_received = [12345647]
[1526] [0] RX433 Received: SENSOR [0] - last_sensorid_received [12345647]
[1529] RX433 Received: SENSOR [12345647] - last_sensorid_received [12345649]
RX433 Received: SENSOR [12345647] - last_sensorid_received [12345649]

1526] [0] RX433 Received: SENSOR [0] - last_sensorid_received [12345647]

this could be related to the %ld type not being correct alligned with the compiler in this arguments?

as of using
		 printf("[%d] [%" PRId64 "] RX433 Received: SENSOR [%lu] - last_sensorid_received [%lu]\n",
	        __LINE__, tv2.tv_sec, sensor_received, last_sensorid_received);
	        
this prints correct, so, why in the esp-idf the type is PRId64 ?

**Comment by Lapshin** [comment]
@filzek , please refer to https://github.com/espressif/crosstool-NG/issues/62#issuecomment-2302593315
