### ISSUE TITLE
UART RX PULL-UP leads to Bit Flips on certain circuits

### ISSUE THREAD

**Issue by stk84** [espressif/esp-idf#1477]
Hello everyone, 

  I am working on a project where our Dev Board includes an ESP32 as well as another Microcontroller.  Both controllers communicate with each other via UART. 

  In order to prevent damage to the controllers, the UART RX and TX connections between the controllers include a 1K resistor each.   With this setup i encountered the issue, that the ESP’s RX Pin voltage will not go down to a solid 0V for Logic Level Low.  Instead it will be at around 0.7V. This leads to the fact that some of the bits flip and the communication is not reliable. 

  To my surprise, a simple Arduino sketch, utilizing HardwareSerial, works fine and the Voltage for Logic Low Level is at 0V.  Comparing the Arduino Library and ESP-IDF i found out that the RX Pin in **/esp-idf/components/driver/uart.c** to is explicitly set to `GPIO_PULLUP_ONLY` 

 The Arduino Library does not set the internal Pull-Up Resistor, leaving the RX Pin Floating.   When manually patching the ESP-IDF’s **/esp-idf/components/driver/uart.c** to:  

`gpio_set_pull_mode(rx_io_num, GPIO_FLOATING);`

 the RX Pin Voltage is also at solid 0V!

  My request is: Can you consider changing the HAL Implementation to set the RX Pin to floating instead of activating the Pull-Up Resistor?

**Comment by igrr** [comment]
Hi @stk84, this suggestion has been discussed internally some time ago, and the decision was that the use case for having a pullup on UART RX pin is more common than the not having it.

For specific hardware which requires this, please call `gpio_pullup_dis` function to disable pullup on RX pin, after initializing UART driver.
