### ISSUE TITLE
Pin Incoherence between example and Datasheet (ESP32-C3) (IDFGH-13934)

### ISSUE THREAD

**Issue by Terrazed** [espressif/esp-idf#14772]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

I believe there is an incoherence in the pins assignments between the ESP32-C3 Datasheet and the readme in the SD spi example.
In [the example](https://github.com/espressif/esp-idf/tree/v5.2.3/examples/storage/sd_card/sdspi#pin-assignments) it is said : 

![Screenshot_20241023_165651](https://github.com/user-attachments/assets/818aa057-9a9c-434e-aac5-652212952a09)

But in [the Datasheet (Table 2-4)](https://www.espressif.com/sites/default/files/documentation/esp32-c3_datasheet_en.pdf) it is written :

![Screenshot_20241023_170049](https://github.com/user-attachments/assets/2ece013a-d496-4748-8e1d-af24f6272ee9)

So in the example it is said that :
- the MISO should go on the GPIO6, which is the FSPICLK on the datasheet
- the CS is ok
- the SCK should go on the GPIO5 which is th FSPIWP on the datasheet
- the MOSI should go on the GPIO4 which is the FSPIHD on the datasheet

Is it a problem of the readme or the datasheet (or a misunderstanding from me) ?

Have a nice day !

**Comment by igrr** [comment]
SPI peripheral on ESP32-C3 can be connected to GPIOs  using either IO MUX or GPIO matrix. The latter method allows using arbitrary GPIOs. Since SD card only needs 40 MHz clock, it's okay to use GPIO matrix in this case.
