### ISSUE TITLE
USB Host Wifi example (IDFGH-13940)

### ISSUE THREAD

**Issue by maaamcube** [espressif/esp-idf#14776]
### Is your feature request related to a problem?

Hello everyone,
I'm looking for an example if it can be added, to send USB's devices through Wifi.
Thanks.

### Describe the solution you'd like.

Send through wifi USB's devices using esp32 s3 or ideally esp32 p4 and receive it in a computer through software for example to test it.

### Describe alternatives you've considered.

USB IP technologie using linux.

**Comment by roma-jam** [comment]
Hi @maaamcube, 

Currently, we don't have the plans for implementing such feature.
But there is already one ticket opened, which is related to the same feature request: https://github.com/espressif/esp-idf/issues/13307

So I will close this ticket as duplicated. 
If there will any news or wish to contribute, please relate it to the [ticket](https://github.com/espressif/esp-idf/issues/13307) mentioned before.
