### ISSUE TITLE
[TW#17598] SPI_DEVICE_BIT_LSBFIRST syntax error : contains semicolon

### ISSUE THREAD

**Issue by vonnieda** [espressif/esp-idf#1480]
The SPI_DEVICE_BIT_LSBFIRST macro at https://github.com/espressif/esp-idf/blob/master/components/driver/include/driver/spi_master.h#L33 contains a semicolon, making it a syntax error to include it in a bitmask of flags.

**Comment by ginkgm** [comment]
thanks.
