### ISSUE TITLE
GPIO: Wrong mask for PIN PULL UP/DOWN in gpio_ll_get_io_config() (IDFGH-14072)

### ISSUE THREAD

**Issue by IhorNehrutsa** [espressif/esp-idf#14886]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

In all MCU soc and hal:
Defined as bit:
```
#define FUN_PD_M (BIT(7))
#define FUN_PU_M (BIT(8))
```
Used as mask:
```
    *pu = (iomux_reg_val & FUN_PU_M) >> FUN_PU_S;
    *pd = (iomux_reg_val & FUN_PD_M) >> FUN_PD_S;
```
![image](https://github.com/user-attachments/assets/5ff3bfad-9ce2-41e3-962f-5f211bfe0160)

Also, need to check BIT or MASK:

![image](https://github.com/user-attachments/assets/42056038-0485-4a52-912c-b5c004768cad)

**Comment by suda-morris** [comment]
Not sure if I understood your question. But

```c
#define BIT(nr)                 (1UL << (nr))
```

It's a mask, not a bit.
