### ISSUE TITLE
wifi 802.11 tx on channel 1 only (IDFGH-14111)

### ISSUE THREAD

**Issue by chegewara** [espressif/esp-idf#14919]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Hi team,
sorry for posting this on github issues instead of forum, but its important in my project.

We have 802.11 beaconing which is sending CCX, IBSS and WDS packets on different channels, but wireshark can catch packets only on channel 1 and im not sure if its issue with wireshark or esp32.

Logic:
- run wifi in STA mode
- not associated with any STA
- TX on channels 1, 6, 11

esp-idf 5.3 and master

Thanks

**Comment by zhangyanjiaoesp** [comment]
@chegewara 
Are you calling `esp_wifi_set_channel()` and then calling  `esp_wifi_80211_tx()` ?

**Comment by zhangyanjiaoesp** [comment]
Are you using ESP32?

**Comment by chegewara** [comment]
Yes, its esp32 pico V2

**Comment by zhangyanjiaoesp** [comment]
Hi, I just test on the master branch, using the `station` example, on ESP32. When the channel change to 6/11, I can capture the packets on channel 6/11.
![Screenshot from 2024-11-26 15-09-16](https://github.com/user-attachments/assets/406755a0-7aa9-476c-8b94-aaddcc8d795c)
![Screenshot from 2024-11-26 15-08-54](https://github.com/user-attachments/assets/5521938e-b37e-4c84-ad09-9179c4131cbe)
![Screenshot from 2024-11-26 15-10-17](https://github.com/user-attachments/assets/24b1ce65-fbd8-494d-a0ca-67d4280e1355)

**Comment by chegewara** [comment]
Thank you for confirming this.
Have a nice weekend.
