### ISSUE TITLE
Use esp32 to drive a 0.96-inch screen (IDFGH-14131)

### ISSUE THREAD

**Issue by swang4415** [espressif/esp-idf#14935]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

5.2.1

### Espressif SoC revision.

ESP32C3

### Operating System used.

Linux

### How did you build your project?

VS Code IDE

### If you are using Windows, please specify command line type.

None

### Development Kit.

ESP32C3-WROOM

### Power Supply used.

USB

### What is the expected behavior?

I am using ESP32C3 to develop a controller for a Matter device. I want to add an OLED screen to this controller using the IIC protocol. I added two rotary encoders to the ESP to control the device's switch and dimming. I hope the OLED can display information such as the device's address status.

### What is the actual behavior?

The fact is that when I initialize the oled, the screen is usable. It can display the information I want. But when the knob encoder is turned, the oled does not change at all. I am sure that I have called the refresh function and written the information I want. And the refresh function shows that everything is normal and is called normally. In addition, the time consumed from clearing the screen to displaying the information is too long, about 10 seconds. I don't know why this is the case. I hope someone can give me some advice.
Below is my code for oled：

static void ENCA_timer_callback(void *arg)
{
    uint8_t ENC_A = gpio_get_level(GPIO_A);
    uint8_t ENC_B = gpio_get_level(GPIO_B);

    if (ENC_A == 0)
    {
        if (ENC_A != ENC_B)  // 顺时针旋转
        {
            current_node_index++;
            if (current_node_index > max_node_index)
            {
                current_node_index = 0;  // 回到第一个灯具
            }
            ESP_LOGI(TAG, "旋钮 A 顺时针旋转，选择的灯具 NodeID: 0x%llX", node_ids[current_node_index]); 
            ESP_LOGI(TAG, "current_node_index: %d", current_node_index);
            OLED_CMD_PRINT();
        }
        else
        {
             ESP_LOGI(TAG, "旋钮 A 未检测到旋转!!");
        }
    }   
        
}

void OLED_CMD_PRINT(void) {
    // 获取当前节点 ID
    chip::NodeId currentNodeId = node_ids[current_node_index];

    // 更新地址信息
    static char addrBuffer[20];
    snprintf(addrBuffer, sizeof(addrBuffer), "Addr: 0x%llX", currentNodeId);
    oledaddr = addrBuffer;

    // 从 `lightStateTable` 获取当前节点状态和亮度
    auto it = lightStateTable.find(currentNodeId);
    if (it != lightStateTable.end()) {
        LightState &light = it->second;

        // 设置开关状态
        if (light.lightA.isOn || light.lightB.isOn) {
            oledstate = "State:Open";
        } else {
            oledstate = "State:Close";
        }

        // 分别显示两盏灯的亮度
        snprintf(oledvalue, sizeof(oledvalue), "Yellow:%d Blue:%d",
                 light.lightA.brightness, light.lightB.brightness);
    } else {
        // 当前节点不在状态表中，设置为未知
        oledstate = "State:Unknown";
        snprintf(oledvalue, sizeof(oledvalue), "Yellow:N/A Blue:N/A");
    }

    // 日志调试信息
    ESP_LOGI("OLED_DEBUG", "刷新数据: Addr=%s, State=%s, Mode=%s, Value=%s", oledaddr, oledstate, oledmode, oledvalue);

    // 刷新显示
    oled_refresh(oledaddr, oledstate, oledmode, oledvalue);
}

void oled_refresh(char* addr,char* state,char* mode,char* value){

	OLEDDisplay_clear(oled);
   
	OLEDDisplay_setTextAlignment(oled,TEXT_ALIGN_CENTER);
	
	OLEDDisplay_setFont(oled,ArialMT_Plain_16);
	OLEDDisplay_drawString(oled,64, 00, addr);

	OLEDDisplay_setFont(oled,ArialMT_Plain_16);
	OLEDDisplay_drawString(oled,64, 15, state);

	OLEDDisplay_setFont(oled,ArialMT_Plain_16);
	OLEDDisplay_drawString(oled,64, 30, mode);

	OLEDDisplay_setFont(oled,ArialMT_Plain_16);
	OLEDDisplay_drawString(oled,64, 45, value);

	OLEDDisplay_display(oled);

}
extern "C" void app_main()
{
    esp_err_t err = ESP_OK;
    esp_log_level_set("*", ESP_LOG_INFO);

    ESP_ERROR_CHECK(initNVS());

    loadLightStateFromNVS(); // 从 NVS 中加载灯具状态

    /* 初始化 GPIO */
    GPIO_Init();
    TIMER_Init();

    oled = OLEDDisplay_init(I2C_MASTER_NUM, 0x78, I2C_MASTER_SDA_IO, I2C_MASTER_SCL_IO);
    if (!oled) {
        ESP_LOGE("APP_MAIN", "OLED 初始化失败");
        return;
    }
    OLEDDisplay_flipScreenVertically(oled);
    oled_refresh(block, matterconnect, block2, auth);

    app_buttons_t buttons = app_driver_switch_init();

    node::config_t node_config;
    node_t *node = node::create(&node_config, app_attribute_update_cb, app_identification_cb);
    ABORT_APP_ON_FAILURE(node != nullptr, ESP_LOGE("APP_MAIN", "Failed to create Matter node"));

    on_off_switch::config_t switch_config;
    endpoint_t *endpoint = on_off_switch::create(node, &switch_config, ENDPOINT_FLAG_NONE, buttons.switch_button);
    ABORT_APP_ON_FAILURE(endpoint != nullptr, ESP_LOGE("APP_MAIN", "Failed to create on off switch endpoint"));

    /* Matter start */
    err = esp_matter::start(app_event_cb);
    ABORT_APP_ON_FAILURE(err == ESP_OK, ESP_LOGE("APP_MAIN", "Failed to start Matter, err:%d", err));

}

### Steps to reproduce.

The screen does not respond when I rotate or press the encoder
...

### Debug Logs.

```plain
I (9298) MatterController: 旋钮 B 逆时针旋转，选择的灯具 NodeID: 0xFF
I (9298) MatterController: current_node_index: 3
I (9298) OLED_DEBUG: 刷新数据: Addr=State:Open, State=State:Unknown, Mode=Mode:Brightness, Value=Yellow:N/A Blue:N/A
I (9308) oled_refresh: 刷新参数: Addr=State:Open, State=State:Unknown, Mode=Mode:Brightness, Value=Yellow:N/A Blue:N/A
I (23328) oled_refresh: 屏幕刷新完成！
I (23328) MatterController: 旋钮 A 未检测到旋转!!
I (35858) MatterController: 旋钮 B 逆时针旋转，选择的灯具 NodeID: 0x5
I (35858) MatterController: current_node_index: 2
I (35858) OLED_DEBUG: 刷新数据: Addr=State:Open, State=State:Close, Mode=Mode:Brightness, Value=Yellow:50 Blue:50
I (35868) oled_refresh: 刷新参数: Addr=State:Open, State=State:Close, Mode=Mode:Brightness, Value=Yellow:50 Blue:50
I (47888) oled_refresh: 屏幕刷新完成！
I (47888) MatterController: 旋钮 A 未检测到旋转!!
```

### More Information.

Although the display refresh is complete, there is no change on the screen

**Comment by suda-morris** [comment]
I'm afraid this is really hard for us to reproduce your issue. I would suggest you to also ask help in the forum place: https://esp32.com/viewforum.php?f=23&sid=69a4ffb9ab3514d9899171dd6fe2662e

It looks like you're not using the oled driver from the esp-idf, right? So I can hardly give my suggestion on that part.
How do you drive the rotary encoder when ESP32C3 doesn't have the PCNT peripheral? If uisng a timer, gptimer or esp_timer?

> In addition, the time consumed from clearing the screen to displaying the information is too long, about 10 seconds

Is there any warning or error information in the log? What happened on the I2C bus? Using a logic analyzer can also help.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to inactivity, feel free to reopen with more updates.
