### ISSUE TITLE
[TW#17758] blufi配置wifi文档

### ISSUE THREAD

**Issue by tomsean** [espressif/esp-idf#1493]
blufi配置wifi传输的数据是使用了加密的算法，能把加密算法公布下吗？或者是每次配置wifi过程中写入的数据数据格式有没有不是加密的，现在编写客户端程序的时候使用的“EspBlufi”sdk并没有开源出来。或者是能不能把最基础的数据格式说明文档说明下

**Comment by Weijian-Espressif** [comment]
@tomsean app app端数据加密的部分目前还没有开源的的计划. 我们再blufi demo 在应用层将加解密的接口留了出来, 您可以使用我们提供的加密算法, 也可以自定义加解密算法, 只需将加解密函数注册到
tatic esp_blufi_callbacks_t example_callbacks = {
    .event_cb = example_event_callback,
    .negotiate_data_handler = blufi_dh_negotiate_data_handler,
    .encrypt_func = blufi_aes_encrypt,
    .decrypt_func = blufi_aes_decrypt,
    .checksum_func = blufi_crc_checksum,
};

**Comment by Weijian-Espressif** [comment]
我们正在做开源的工作, 稍后会开放所有源码.

**Comment by Weijian-Espressif** [comment]
ios 源码已经开放, 安卓稍后开放

**Comment by Weijian-Espressif** [comment]
@FayeY done , please close the issue.
