### ISSUE TITLE
Add partition support to write_flash command. (IDFGH-138)

### ISSUE THREAD

**Issue by OtherCrashOverride** [espressif/esp-idf#1494]
As directed by espressif/esptool#262, I am opening this issue here.

> Currently, a fixed offset must be specified for the write_flash command. An option to specify ESP32 partition name or ID should be added. This would allow either an offset that does not change or a partition that potentially changes to be used.

>A real world example is the case of a SPIFFS filesystem partition. In the case where only the filesystem is to be updated, the offset where it resides needs to found and may vary across different builds and/or app revisions. It is not possible to OTA update in all environments where an ESP32 may be deployed.

**Comment by renzbagaporo** [comment]
Hi @OtherCrashOverride, sorry for the late response on this. We added a tool called `parttool.py` that does exactly just this. 

```
parttool.py [some-args] write_partition [some-args]
```

Tool is here: https://github.com/espressif/esp-idf/blob/master/components/partition_table/parttool.py. This can be used from the command line.

(Though there is a pending update to this that makes this available from Python and the command-line as well)
