### ISSUE TITLE
Unnecesary semicolon in macro SPI_DEVICE_BIT_LSBFIRST

### ISSUE THREAD

**Issue by mciej** [espressif/esp-idf#1495]
Hi,
please remove semicolon in:
`#define SPI_DEVICE_BIT_LSBFIRST            (SPI_DEVICE_TXBIT_LSBFIRST|SPI_DEVICE_RXBIT_LSBFIRST); ///< Transmit and receive LSB first`
It's causing compilation errors.

Regards,
Maciej

**Comment by krzychb** [comment]
https://github.com/espressif/esp-idf/issues/1480
