### ISSUE TITLE
ESP-IDF v5.2.2 ESP32s3 GAP E (459) BT_BTM: LE EA SetParams: cmd err=0x12 (IDFGH-14163)

### ISSUE THREAD

**Issue by emofalling** [espressif/esp-idf#14965]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

When code run to the line `ERROR_CHECK(esp_ble_gap_ext_adv_set_params(1, &adv_params));`, error:
`E (459) BT_BTM: LE EA SetParams: cmd err=0x12`
Then run to the line `ERROR_CHECK(esp_ble_gap_ext_adv_start(1, &adv_cfg));`, error:
`E (469) BT_BTM: LE EA En=1: cmd err=0x42`
The All code is:
```c
// Standard
#include <stdio.h>
// esp
#include "esp_task_wdt.h"
#include "esp_log.h"
// FreeRTOS
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
// NVS
#include "nvs.h"
#include "nvs_flash.h"
// Bluetooth 5
#include "esp_bt.h"
#include "esp_bt_main.h"
#include "esp_gap_ble_api.h"
#include "esp_gattc_api.h"
#include "esp_bt_main.h"

#define ERROR_CHECK(x) ESP_ERROR_CHECK(x)

// BLE run to core 0, Motor controller run to core 1

const char *device_name = "Remote control car for ESP32s3";
esp_bt_controller_config_t bt_cfg = BT_CONTROLLER_INIT_CONFIG_DEFAULT();
/*
esp_ble_adv_params_t adv_params = {
    .adv_int_min    = 0x3000,
    .adv_int_max    = 0x4000,
    .adv_type       = ADV_TYPE_IND,
    .own_addr_type  = BLE_ADDR_TYPE_PUBLIC,
    .peer_addr      = {0}, // not used
    .peer_addr_type = BLE_ADDR_TYPE_PUBLIC,
    .channel_map    = ADV_CHNL_ALL,
    .adv_filter_policy = ADV_FILTER_ALLOW_SCAN_ANY_CON_ANY,
};
*/
esp_ble_gap_ext_adv_params_t adv_params = {
    .type = ESP_BLE_GAP_SET_EXT_ADV_PROP_LEGACY_IND,
    .interval_min   = 0x4000,
    .interval_max   = 0x4000,
    .channel_map    = ADV_CHNL_ALL,
    .own_addr_type  = BLE_ADDR_TYPE_PUBLIC,
    .peer_addr_type = BLE_ADDR_TYPE_PUBLIC, 
    .peer_addr      = {0}, // not used
    .filter_policy  = ADV_FILTER_ALLOW_SCAN_ANY_CON_ANY,
    .tx_power       = +20, //dBm
    .primary_phy    = ESP_BLE_GAP_PRI_PHY_CODED,
    .max_skip       = 0,
    .secondary_phy  = ESP_BLE_GAP_PHY_CODED,
    .sid            = 0x0,
    .scan_req_notif = true,
    /*
    .type = ESP_BLE_GAP_SET_EXT_ADV_PROP_SCANNABLE,
    .interval_min = 0x40,
    .interval_max = 0x40,
    .channel_map = ADV_CHNL_ALL,
    .filter_policy = ADV_FILTER_ALLOW_SCAN_ANY_CON_ANY,
    .primary_phy = ESP_BLE_GAP_PHY_1M,
    .max_skip = 0,
    .secondary_phy = ESP_BLE_GAP_PHY_2M,
    .sid = 1,
    .scan_req_notif = false,
    .own_addr_type = BLE_ADDR_TYPE_RANDOM,
    .tx_power = EXT_ADV_TX_PWR_NO_PREFERENCE,
    */
};
esp_ble_gap_ext_adv_t adv_cfg = {
    .instance = 0,
    .max_events = 1,
    .duration = 0,
};
bool bool_changed = false;
void task_blecon(void *pvParameters){
    const char* TAG = "task_blecon";
    ESP_LOGI(TAG, "Start BLE task");
    // NVS Init
    ESP_LOGI(TAG, "Init NVS");
    ERROR_CHECK(nvs_flash_init());
    // Controller Release RAM

    ESP_LOGI(TAG, "Controller Release RAM");
    ERROR_CHECK(esp_bt_controller_mem_release(ESP_BT_MODE_CLASSIC_BT));
    // Start Controller
    ESP_LOGI(TAG, "Start Controller");
    ERROR_CHECK(esp_bt_controller_init(&bt_cfg));
    // Enable Controller
    ESP_LOGI(TAG, "Enable Controller");
    ERROR_CHECK(esp_bt_controller_enable(ESP_BT_MODE_BLE));
    // Start Bluedroid
    ESP_LOGI(TAG, "Start Bluedroid");
    ERROR_CHECK(esp_bluedroid_init());
    // Enable Bluedroid
    ESP_LOGI(TAG, "Enable Bluedroid");
    ERROR_CHECK(esp_bluedroid_enable());
    // Set Device Name
    ESP_LOGI(TAG, "Set Device Name");
    ERROR_CHECK(esp_ble_gap_set_device_name(device_name));
    // Set adversiting args
    ESP_LOGI(TAG, "Set advertising args");
    ERROR_CHECK(esp_ble_gap_ext_adv_set_params(1, &adv_params));
    // Start advertising
    ESP_LOGI(TAG, "Start Advertising");
    ERROR_CHECK(esp_ble_gap_ext_adv_start(1, &adv_cfg));
}
void task_motorcon(void *pvParameters){
    // Do something
    while(true){
        // Do something
    }
    vTaskDelete(NULL);
}
void app_main(void){
    // Disable WDT
    esp_task_wdt_deinit();
    // Create BLE task
    //xTaskCreatePinnedToCore(task_blecon, "task_blecon", 4096, NULL, 5, NULL, 0);
    task_blecon(NULL);
    // Create motor controller task
    xTaskCreatePinnedToCore(task_motorcon, "task_motorcon", 4096, NULL, 5, NULL, 1);
}
```

**Comment by esp-zhp** [comment]
![image](https://github.com/user-attachments/assets/5d503139-8217-452f-9462-2cfa2d15b535)

The issue originates from the controller reporting error 0x12 during the `esp_ble_gap_ext_adv_set_params` call, indicating invalid parameter settings. Specifically, the advertising interval values you configured do not comply with the Bluetooth specification. Here's the detailed analysis:

### Advertising Interval Issue
Your current configuration:
```c
.interval_min = 0x4000, // 10240 ms
.interval_max = 0x4000, // 10240 ms
```

According to the **Bluetooth Core Specification Version 5.4 (Vol 4, Part E, Page 2450)**:
- The **minimum advertising interval** (`interval_min`) must be in the range `0x0020` to `0xFFFFFF` (20 ms to 10,485.759375 s).
- The **maximum advertising interval** (`interval_max`) must also fall within the same range and should not be less than `interval_min`.

In your case, while the values are within the valid range, `0x4000` corresponds to an unusually large interval (10240 ms), which might not be supported by your controller in the current configuration.

### Recommendations
1. Adjust the advertising intervals to more standard values, such as:
   ```c
   .interval_min = 0x0030, // 30 ms
   .interval_max = 0x0030, // 30 ms
   ```
2. Verify other parameters for compatibility, such as  `primary_phy`, and `secondary_phy`. Ensure these settings are supported by your specific ESP32 controller and firmware.

### Reference Material
Refer to the **Bluetooth Core Specification Version 5.4 | Vol 4, Part E, Page 2450** for parameter descriptions and valid ranges.
![image](https://github.com/user-attachments/assets/2f998adc-6fd4-4b2e-9ee0-2d94ff5137a8)

These adjustments should resolve the errors you're encountering.

Additionally, we plan to improve the documentation in the future to ensure parameter descriptions are clear and unambiguous.

**Comment by emofalling** [comment]
Thank you for your reply. Finally found the problem:line    
`primary_phy    = ESP_BLE_GAP_PRI_PHY_CODED`  needs to be changed to :   
`primary_phy    = ESP_BLE_GAP_PRI_1M`.
