### ISSUE TITLE
SPI Transmission Issue: Last Byte Sent at the Beginning of Next Transfer (IDFGH-14188)

### ISSUE THREAD

**Issue by MesutHodja** [espressif/esp-idf#14987]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v5.3.2

### Espressif SoC revision.

ESP32-WROOM

### Operating System used.

Windows

### How did you build your project?

Eclipse IDE

### If you are using Windows, please specify command line type.

None

### Development Kit.

Custom Board

### Power Supply used.

External 3.3V

### What is the expected behavior?

The expected behavior is that the SPI peripheral should correctly transmit all bytes in the data packet during a single transfer. Specifically:

1. Complete Transmission: Every byte in the data array, including the last byte, should be transmitted during the same SPI transaction.
2. No Overlap: The last byte of the current data packet should not appear at the start of the next data packet.
3. Consistent Data Integrity: The transmitted and received data should align perfectly with the data buffer provided for each SPI transaction.
4. Accurate Chip Select Timing: The /CS (chip select) line should remain low (active) for the duration of the entire transfer and should not affect the transmission of any byte.

This behavior ensures that SPI communication adheres to standard protocols and data packets are transferred as expected without any misalignment or data corruption.

### What is the actual behavior?

The actual behavior deviates from the expected SPI protocol in the following ways:

1. Last Byte Not Transmitted: During a single SPI transfer, the last byte of the data packet is not transmitted as part of the current transfer.
2. Last Byte Shifted: The missing last byte appears at the beginning of the subsequent transfer, effectively shifting the data stream and causing misalignment between the transmitted and received data.
3. Persistent Issue: This behavior occurs consistently, regardless of:
        - SPI mode (e.g., Mode 0, Mode 1, etc.).
        - Whether DMA is enabled or disabled.
        - The size of the data packet.
4. Impact on Communication: The misalignment caused by this issue leads to data corruption, making it impossible to maintain accurate and reliable communication between the SPI master and slave.

This behavior disrupts the intended SPI communication and violates the expected protocol for transferring data in discrete packets.

### Steps to reproduce.

In my circuit using the ESP32-WROOM module, I have four devices connected to the same SPI bus: an OLED display (SSD1309), a TRF7970A, an STM32 (as SPI slave), and four 74HC595 shift registers. During development, I occasionally noticed flickering on the OLED display. To investigate the issue, I disabled all other SPI transfers and focused solely on sending data to the 74HC595 shift registers. I monitored the SPI communication using a logic analyzer and tested all possible SPI modes.

My codes:

SemaphoreHandle_t spiMutexHandle;

//simple codes for spi testing
//in my task, this is called in 100ms periodically.
static void LEDS_Update(TaskId_TypeEnum taskId)
{
	static bool toggle = 0;
	uint8_t buffer[8];
	
	if(toggle)
	{
		toggle = 0;
		buffer[0] = 0x11;
		buffer[1] = 0x22;
		buffer[2] = 0x33;
		buffer[3] = 0x44;
		buffer[4] = 0x55;
		buffer[5] = 0x66;
		buffer[6] = 0x77;
		buffer[7] = 0x88;
	} else  {
		toggle = 1;
		buffer[0] = 0x12;
		buffer[1] = 0x34;
		buffer[2] = 0x56;
		buffer[3] = 0x78;
		buffer[4] = 0x9A;
		buffer[5] = 0xBC;
		buffer[6] = 0xDE;
		buffer[7] = 0xF1;
	}

	//send
	LEDS_SendData(buffer, 4);
}

esp_err_t SPI_SendData(uint8_t *data, size_t length) 
{
	esp_err_t result = ESP_FAIL;
	    
    if(xSemaphoreTake(spiMutexHandle, 50) == pdTRUE)
    {
		spi_transaction_t trans = {
	        .length = length * 8,
	        .tx_buffer = data,
	    };
		// latch is low
	    gpio_set_level(SR_LATCH, 0);
	    // send data
	    ESP_ERROR_CHECK(spi_device_transmit(spiLeds, &trans));
	    // latch is high
	    gpio_set_level(SR_LATCH, 1);
		// give mutex
		xSemaphoreGive(spiMutexHandle); 
		
		result = ESP_OK;
	}
	return result;   		
}

void SPI_Init(void)
{	
	spiMutexHandle = xSemaphoreCreateMutex();
	
	spi_bus_config_t buscfg = {
        .mosi_io_num = SPI_MOSI,
        .miso_io_num = SPI_MISO,        
        .sclk_io_num = SPI_CLK,
        .quadwp_io_num = -1,
        .quadhd_io_num = -1,
        .max_transfer_sz = 4096,   
    };

    ESP_ERROR_CHECK(spi_bus_initialize(SPI2_HOST, &buscfg, SPI_DMA_CH_AUTO));
	
		spi_device_interface_config_t devcfgLeds = {
        .clock_speed_hz = 100000,  	// 100 kHz SPI speed
        .mode = 0,                  // SPI mod 0
        .spics_io_num = -1,         // CS pin manually controlled
        .queue_size = 1,
        .pre_cb = NULL,     
    };
    // SPI cihazı ekle
    ESP_ERROR_CHECK(spi_bus_add_device(SPI2_HOST, &devcfgLeds, &spiLeds));
}

![packet1](https://github.com/user-attachments/assets/ff003a49-f93c-4b07-bac5-a358fe5a0a31)
![packet2](https://github.com/user-attachments/assets/e7741216-ab9e-4d54-8e6a-1bb33edf776a)

### Debug Logs.

```plain
No crash occurred.
```

**Comment by Maksons** [comment]
Sorry, was there any solution?
