### ISSUE TITLE
SPI Ethernet W5500 can not ping larget packet（>=2048byte） (IDFGH-14196)

### ISSUE THREAD

**Issue by wensenl** [espressif/esp-idf#14994]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

esp-idf-v5.3.1

### Espressif SoC revision.

ESP32S3

### Operating System used.

macOS

### How did you build your project?

Command line with idf.py

### If you are using Windows, please specify command line type.

None

### Development Kit.

ESP Thread Boarder Router

### Power Supply used.

USB

### What is the expected behavior?

1、can ping larget packet（>=2048byte）
2、What is the maximum configuration limit for SPI clock?

### What is the actual behavior?

when pc ping larget packet to esp32s3，pc Request timeout for icmp_seq 0.
ping -s 2048 -c 100 192.168.168.114
PING 192.168.168.114 (192.168.168.114): 2048 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
Request timeout for icmp_seq 3

### Steps to reproduce.

1、pc ping to esp32s3
2、ping cmd
ping -s 2048 -c 100 192.168.168.114

3、spirit Ethernet config
<img width="651" alt="spi eth config" src="https://github.com/user-attachments/assets/6cf38001-b7a4-47e2-98b6-09658b74fa61">

**Comment by kostaond** [comment]
As defined by the IEEE 802.3 standard, Ethernet have a payload size limit of 1,500 bytes, plus additional overhead for headers and checksums. ESP-IDF drivers are written to follow the standard. In addition, it seems that W5500 does not support jumbo frames at all. Therefore there is not even theoretical option to support sizes bigger than standard.
