### ISSUE TITLE
Documentation issue on xRingbufferSendComplete() (IDFGH-14191)

### ISSUE THREAD

**Issue by adam-hotait** [espressif/esp-idf#14990]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Following issue #13730, where the xRingbufferSendAcquire function was called with a variable of the type`void *pvItem` instead of `void **pvItem` in the documentation (now fixed), there is now an issue in the documentation on the call of xRingbufferSendComplete which is called with `void pvItem` instead of `void pvItem`.

Documentation link: [Here](https://docs.espressif.com/projects/esp-idf/en/v5.3.1/esp32/api-reference/system/freertos_additions.html#usage)

Screenshot of issue:
<img width="715" alt="Screenshot 2024-12-06 at 20 52 09" src="https://github.com/user-attachments/assets/8552c024-820d-435b-adc9-762a24766bc7">

Proposed change:
```diff
-res = xRingbufferSendComplete(buf_handle, &item);
+res = xRingbufferSendComplete(buf_handle, item);
```

**Comment by sudeep-mohanty** [comment]
Thanks for reporting the error, @adam-hotait! We shall fix it.
