### ISSUE TITLE
Lwip - error: storage size of 'server_ip' isn't known

### ISSUE THREAD

**Issue by feelfreelinux** [espressif/esp-idf#15]
Hi. I'm trying to setup tcp server on esp32. But, when i'm defining `struct ip_addr server_ip;` i got error: 

> error: storage size of 'server_ip' isn't known

I'm including lwip/tcp.h and lwip/ip_addr.h

**Comment by projectgus** [comment]
This has been renamed to `ip_addr_t` in recent LWIP. Try:

```
ip_addr_t server_ip;
```

**Comment by feelfreelinux** [comment]
Thanks! My mistake!
