### ISSUE TITLE
[TW#17767] OTA example strange behavior

### ISSUE THREAD

**Issue by chegewara** [espressif/esp-idf#1500]
Few weeks ago i changed a little ota example to resolve IP address from domain name and all worked fine. Now it still working just i have some strange behavior. After reading whole bin file app stuck for about 40 seconds somewhere in here https://github.com/espressif/esp-idf/blob/master/examples/system/ota/main/ota_example_main.c#L269-L272

```
I (22290) ota: Have written image length 1754512
I (62512) ota: Connection closed, all packets received
I (62514) ota: Total Write binary data length : 1754512
D (62514) esp_image: reading image header @ 0x110000
D (62518) esp_image: image header: 0xe9 0x07 0x02 0x02 40081060
```

```
I (13220) ota: Have written image length 1434416
I (13222) ota: Have written image length 1435392
I (13224) ota: Have written image length 1435792
I (63211) ota: Connection closed, all packets received
I (63213) ota: Total Write binary data length : 1435792
D (63215) esp_image: reading image header @ 0x110000
D (63217) esp_image: image header: 0xe9 0x07 0x02 0x02 40080e8c
```

**Comment by negativekelvin** [comment]
Must be stuck at https://github.com/espressif/esp-idf/blob/master/examples/system/ota/main/ota_example_main.c#L253

**Comment by FayeY** [comment]
Any update about this issue?

**Comment by chegewara** [comment]
Not from my side, i dont know what i can do. Its esp-idf example.

**Comment by FayeY** [comment]
Could you provide tcp packet capture for debugging?

**Comment by chegewara** [comment]
Not really, i cant configure wireshark in promiscuse mode on my laptop. But this code can be used to recreate it:
https://github.com/chegewara/esp32-ota-with-ble-setup
