### ISSUE TITLE
WT-ETH01 module: Failed to initialize ethernet connection (IDFGH-14206)

### ISSUE THREAD

**Issue by Melek-Cherif** [espressif/esp-idf#15004]
Hello, I am trying to activate an Ethernet connection using the basic Ethernet example of the ETH.h library. I got two boards, and I am having the same error after debug:

**E (2211) esp.emac: emac_esp32_init(371): reset timeout
E (2211) esp_eth: esp_eth_driver_install(228): init mac failed**

I changed the configurations of the clock and physical address and added different delays before initialization, but I always have this problem. Is there any

**Comment by Melek-Cherif** [comment]
I tried it but I am having the same error again and again. I am using the same config 
![Screenshot from 2024-12-10 10-34-24](https://github.com/user-attachments/assets/f6513080-16ea-45b6-9be7-befed1c353a3)
![Screenshot from 2024-12-10 10-29-04](https://github.com/user-attachments/assets/d6a8fc10-dc4a-48f1-ab80-3ef5faa95d78)

**Comment by kostaond** [comment]
Have you enabled the external oscillator as I suggested in forum https://www.esp32.com/viewtopic.php?f=2&t=43405? Anyway, I'm closing this issue since it's unrelated to ESP-IDF SW issues.

**Comment by kostaond** [comment]
I see, @nopnop2002 uses the trick to enable OSC by reset. OK, it's bit hacky but it should do its job. How's your REF RMII CLK configured? Is it set to external?

**Comment by Melek-Cherif** [comment]
> I see, @nopnop2002 uses trick to enable OSC by reset. OK, it's bit hacky but it should do its job. How's your REF RMII CLK configured? Is it set to external?

I tried both configuration for the clock input from external and the inverse. That only gave me one less error.
![Screenshot from 2024-12-10 10-26-06](https://github.com/user-attachments/assets/9b0091e4-b416-40d0-8aad-577e8a19d4fa)

![Screenshot from 2024-12-10 10-29-04](https://github.com/user-attachments/assets/973d47e6-5ecb-4fb9-ac7a-0c0086e8d37a)

**Comment by Melek-Cherif** [comment]
Also I found out that my hardware is different from the WT32-ETH01 module. It contains an esp32-wroom-32 chip instead of WT32-S1 chip. which raises my doubts about the hardware.

**Comment by kostaond** [comment]
Do you have oscilloscope? Modify code to not reset on the Ethernet init error and measure if you see 50 MHz signal at GPIO0.

**Comment by nopnop2002** [comment]
>It contains an esp32-wroom-32 chip instead of WT32-S1 chip.

Can you obtain the schematic for your hardware?

WT32-ETH01's schematic is here.
https://github.com/ldijkman/WT32-ETH01-LAN-8720-RJ45-/blob/main/WT32_ETH01_V2.schematic.pdf
