### ISSUE TITLE
I2S example is wrong at 1st 16bit output (IDFGH-140)

### ISSUE THREAD

**Issue by MhageGH** [espressif/esp-idf#1501]
I2S example(i2s_example_main.c) is wrong at 1st 16bit output as the image. It should change output resolution every 5 second. I think there is error concerned with DMA buffer in I2S library according to some own tests.
![default](https://user-images.githubusercontent.com/29541803/34915478-d7c1b978-f96a-11e7-9445-d4b52e4bf1dd.PNG)

**Comment by tuanpmt** [comment]
Hello @MhageGH 
You may encounter the same situation here
https://github.com/espressif/esp-idf/issues/300#issuecomment-277605202

> Because i2s tx faster than sinwave/triangle calculation. Please re-calculate to a buffer first, then using i2s_write_bytes

**Comment by MhageGH** [comment]
Hello @tuanpmt 
Thank you for your comment. 
However the present i2s_example_main.c already forms as same as the resolved code in #300 (comment). 
https://github.com/espressif/esp-idf/blob/master/examples/peripherals/i2s/main/i2s_example_main.c
I think it is other problem.

**Comment by projectgus** [comment]
Hi @MhageGH ,

Thanks for being patient, sorry that noone got back to you about this issue for such a long time.

Do you happen to still have the I2S test code that produced the waveforms shown in the graphs?

Angus

**Comment by costaud** [comment]
I'll close this issue for now, feel free to reopen if you get further information.
