### ISSUE TITLE
How to blink an led when ota updating? (IDFGH-14224)

### ISSUE THREAD

**Issue by EternityFOR** [espressif/esp-idf#15020]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

How to blink an led when OTA updating?

**Comment by mahavirj** [comment]
@EternityFOR 

You may use advanced OTA APIs that allows an application finer control during OTA update process. Please plug in your application specific code in `advanced_https_ota` example below:

https://github.com/espressif/esp-idf/blob/cb3ac7429c73b6e7c6d79ae05de480d4b6706770/examples/system/ota/advanced_https_ota/main/advanced_https_ota_example.c#L183-L192
