### ISSUE TITLE
PX4 install error on windows (IDFGH-14229)

### ISSUE THREAD

**Issue by Lee-beep086** [espressif/esp-idf#15025]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v1.11.2

### Operating System used.

Windows

### How did you build your project?

Command line with Make

### If you are using Windows, please specify command line type.

None

### What is the expected behavior?

success

### What is the actual behavior?

![微信图片_20241213162148](https://github.com/user-attachments/assets/b6261720-0e0a-479a-be25-4515d04f3f61)

### Steps to reproduce.

1. I changed the downloaded firmware version from 1.9.1 to 1.15.1, and there were issues with different versions, but the problems that occurred were slightly different
2. When the firmware version is 1.12.1, the problem that occurs is shown in the following figure
![微信图片_20241213162557](https://github.com/user-attachments/assets/3d0e8dff-6b55-42cc-b5f2-5eeb48f04d0a)

...

### Build or installation Logs.

```plain
please help me
```

**Comment by igrr** [comment]
@Lee-beep086 You probably need to report this issue in the correct repository: https://github.com/PX4/PX4-Autopilot/issues.
