### ISSUE TITLE
版本错误 (IDFGH-14241)

### ISSUE THREAD

**Issue by UF4OVER** [espressif/esp-idf#15037]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

我在git拉取仓库，并没有指定版本。直到我是用Clion配置完成后，我才想起来查看版本，但是输出的版本是5.5.0的版本？这个版本是正常的吗？
这是version.cmake中的数据：
```cmake
set(IDF_VERSION_MAJOR 5)
set(IDF_VERSION_MINOR 5)
set(IDF_VERSION_PATCH 0)

set(ENV{IDF_VERSION} "${IDF_VERSION_MAJOR}.${IDF_VERSION_MINOR}.${IDF_VERSION_PATCH}")
```

这是PowerShell中的输出
```bash
> cd D:\esp-idf
> git describe
v5.5-dev-847-gcb3ac7429c
> export.bat
Activating ESP-IDF 5.5
Setting IDF_PATH to 'D:\esp-idf'.
* Checking python version ... 3.12.4
* Checking python dependencies ... OK
* Deactivating the current ESP-IDF environment (if any) ... OK
* Establishing a new ESP-IDF environment ... OK
* Identifying shell ... cmd.exe
* Detecting outdated tools in system ... Found tools that are not used by active ESP-IDF version.
For removing old versions of ble, bt, catch, ci, cmake, docker, esp_app_trace, esp_prov, export_utils, gen_soc_caps_kconfig, idf_py_actions, kconfig_new, ldgen, legacy_exports, mass_mfg, mocks, requirements, templates, test_apps, test_build_system,
test_idf_py, test_idf_size, test_idf_tools, test_mkdfu, unit-test-app, __pycache__ use command 'python.exe D:\esp-idf\tools\idf_tools.py uninstall'
To free up even more space, remove installation packages of those tools.
Use option python.exe D:\esp-idf\tools\idf_tools.py uninstall --remove-archives.

Done! You can now compile ESP-IDF projects.
Go to the project directory and run:

  idf.py build

>
```

**Comment by dobairoland** [comment]
Yes, that is normal for the master branch. It is currently set to the upcoming v5.5 version. You can `git checkout` a more stable release tag or release branch. You can read about the versions here: https://docs.espressif.com/projects/esp-idf/zh_CN/latest/esp32/versions.html
