### ISSUE TITLE
Flashing nvs during production

### ISSUE THREAD

**Issue by a-soft-dev** [espressif/esp-idf#1505]
Hallo,

I hope this is the right place for a question like this.

I want to include a serial number in the ESP32 in our production. If i'm correct it should be possible to flash a binary at the NVS address just like you flash an app on the app address, correct?

Is there a way to make a binary in which I could place a key value pair?

Thanks.

**Comment by FayeY** [comment]
Hi, the [Technical Support on ESP website](http://www.espressif.com/en/company/contact/technical-inquiries-category) is a better place to ask about production issues. An internal engineer will be assigned to answer your question about production. Thanks.
