### ISSUE TITLE
Would it be possible to get the raw scrambled bitstream? (IDFGH-14259)

### ISSUE THREAD

**Issue by doragasu** [espressif/esp-idf#15053]
### Is your feature request related to a problem?

We are developing an application using 1Mbps 802.11b mode in which we can extract valid information from very noisy/corrupted frames that would be normally discarded by the driver. For this we use the promiscuous mode reception with the feature allowing to obtain FCS failed frames.

This works, but for this application, we would be able to improve the reception even more if we were able to obtain the raw/unscrambled bitstream (because when a bit in the stream is corrupted, the descrambler can cause that 6 additional bits get also corrupted).

I understand this is a weird request and might not be possible, but well, have to at least try ^_^

### Describe the solution you'd like.

We would like to have a promiscuous rx mode in which we can get the scrambled bitstream (i.e. the received bitstream before it goes through the descrambler). We only need it for the 802.11b mode, but if it can be used for other modes two, it doesn't bother.

### Describe alternatives you've considered.

For our experimental receiver we use a Blade-RF SDR, that allows us getting the scrambled bitstream. But we would like to be able to achieve it using ESP32-XX MCUs.

**Comment by MaxwellAlan** [comment]
Hi @doragasu 

Thanks for the feature request.

ESP32 series do not support dump bitstream from RF.
