### ISSUE TITLE
[TW#17769] BLE security - episod 3

### ISSUE THREAD

**Issue by chegewara** [espressif/esp-idf#1507]
Most setting and expected results i understand, but im still learning, so if im wrong then im sorry. Bluetooth le server application:
- few characteristics with ESP_GATT_PERM_READ_ENCRYPTED | ESP_GATT_PERM_WRITE_ENCRYPTED, i know what this means
- server is setup without seting up esp_ble_set_encryption() (on purpose)
- no other security options are setup (on purpose)

Now application behavior:
- first connection with no encryption, server and client does not require encryption or bonding` (ESP_OK)`
- first reading from characteristic with ESP_GATT_PERM_READ_ENCRYPTED | ESP_GATT_PERM_WRITE_ENCRYPTED, ESP_GAP_BLE_SEC_REQ_EVT is fired and keys are exchange, bond connection etc` (ESP_OK)`
- disconnect devices `(ESP_OK)`
- connect bonded devices `(ESP_OK)`
- read characteristics with ESP_GATT_PERM_READ_ENCRYPTED | ESP_GATT_PERM_WRITE_ENCRYPTED, now im expecting authenticating connection even if keys are stored and devices are bonded, but i have just regular ESP_GATTS_READ_EVT event `(ESP_ERR?)`

I would expect at least ESP_GAP_BLE_AUTH_CMPL_EVT event to be fired.

**Comment by Weijian-Espressif** [comment]
@chegewara  The first time the device is connected, the encryption key is saved to flash, ESP_GAP_BLE_AUTH_CMPL_EVT is triggered. when you connect again, the encryption key is load from falsh ,there is no ESP_GAP_BLE_AUTH_CMPL_EVT. of course, you can delete encryption key before connection again.
