### ISSUE TITLE
[TW#17863] eclipse-retup.rst: ambiguous instructions

### ISSUE THREAD

**Issue by plasticuser** [espressif/esp-idf#1509]
https://github.com/espressif/esp-idf/blob/master/docs/get-started/eclipse-setup.rst

In project properties, it says "Edit the PATH environment variable. Keep the current value, and append the path to the Xtensa toolchain that will installed as part of IDF setup (something/xtensa-esp32-elf/bin) if this is not already listed on the PATH."

Of five of us here, not one of us knows what that means. Is it added comma separated? Is "something" the $PATH$?

**Comment by chegewara** [comment]
http://esp-idf.readthedocs.io/en/latest/get-started/index.html#setup-path-to-esp-idf

**Comment by krzychb** [comment]
> Of five of us here, not one of us knows what that means. Is it added comma separated? Is "something" the $PATH$?

* Yes, it is added comma separated
* "something" means full path to "xtensa-esp32-elf/bin"

In my case (Linux) the PATH looks as follows:

```
/bin:/home/krzysztof/bin:/home/krzysztof/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/usr/games:/usr/local/games:/snap/bin:/home/krzysztof/esp/xtensa-esp32-elf/bin
```

![image](https://user-images.githubusercontent.com/12953787/34955869-b2b135ac-fa26-11e7-82ae-338e4b61925c.png)

**Comment by projectgus** [comment]
Reopening as I think we can reword this section to be clearer.
