### ISSUE TITLE
[TW#17847] Duplicate symbol definition from ESP32 - system_restore

### ISSUE THREAD

**Issue by nkolban** [espressif/esp-idf#1520]
Examining the current ESP-IDF as of the date of this post, we seem to find two functions ... both called system_restore.   One is found in here:

https://github.com/espressif/esp-idf/blob/master/components/esp32/restore.c#L21

and the other here:

https://github.com/espressif/esp-idf/blob/master/components/esp32/system_api.c#L358

This is causing a "multiple definition" in some tests of esoteric linking.  I believe that in code, we should only have one export of a given named symbol.

**Comment by negativekelvin** [comment]
Per comments it was intended to be removed from system_api.c but wasn't
