### ISSUE TITLE
Problems with ble encryption on Devices with bluetooth Version < 4.2

### ISSUE THREAD

**Issue by ManODi** [espressif/esp-idf#1521]
Hello,

I changed the gatt_security_server example on the ESP_WROOM_32 adding a static public mac address with:  esp_base_mac_addr_set(macAddress); 
and set:  esp_ble_gap_config_local_privacy(false);
I also changed the mac type to public in advertising.

Using a device with bluetooth Version >= 4.2 it works fine. I have to do bonding once and then i can reconnect.
But using an older device with a lower version it seems to fail at esp_ble_set_encryption(param->connect.remote_bda, ESP_BLE_SEC_ENCRYPT);

When I try to reconnect the message is:
E (1080965) BT: l2cble_start_conn_update, the last connection update command still pending.

Did anyone else encounter this Problem? Or do I have to change some settings for compatibility?

Tanks in advance

**Comment by negativekelvin** [comment]
https://github.com/espressif/esp-idf/issues/1471

**Comment by chegewara** [comment]
https://github.com/espressif/esp-idf/issues/1364

**Comment by FayeY** [comment]
Closing this, as this issue is a duplicate issue. Please follow the issues mentioned above instead.
