### ISSUE TITLE
[TW#17867] Bluetooth dual mode issue

### ISSUE THREAD

**Issue by andrewvoznytsa** [espressif/esp-idf#1523]
Hi guys,

I'm trying to run BLE and BTC in parallel. And it does not work. My sample code is attached. It is based on your GATTS server and A2DP sink examples.

Idea is simple - I run GATTS server, then sleep for 15 seconds, then run A2DP sink. I expect that both of them will be working.

When I run sample code I see that BLE part starts advertising, then after 15 seconds, A2DP sink becomes active and BLE part is not accessible.

Is it supposed to work (BLE and BTC in parallel)? If yes, and if it is not my bug, then could you please let me know when do you expect to fix that? If this is my bug - could you please give me hint how to fix?

**Comment by mringwal** [comment]
Quick try with spp_and_le_counter from BTstack seems to work as expected: the test message is sent via GATT to my iPhone and SPP to my Mac.
