### ISSUE TITLE
SPI latency between transactions. Is there a faster way

### ISSUE THREAD

**Issue by versamodule** [espressif/esp-idf#1524]
The SPI for me works just fine, but the transaction to transaction time is terrible using esp-idf directly. 
I ran 2 tests (one using esp-idf directly and the other using Arduino code).  Both tests send 2 transactions back to back.  With  esp-idf directly it was 112us until the next transaction, with Arduino code, it was a mere 1.2us. 

using esp-idf directly: Calling this routine 2x

`
    uint8_t temp[2];
    esp_err_t ret;
    spi_transaction_t t;

    temp[0]=0xaa;
    
    memset(&t, 0, sizeof(t));       //Zero out the transaction
    t.length=8;                 //Len is in bytes, transaction length is in bits.
    t.tx_buffer=&temp;               //Data

     ret=spi_device_transmit(lcd_spi, &t);  //Transmit!
     assert(ret==ESP_OK);            //Should have had no issues.
`
as can be seen here. 

![img_20180119_141821](https://user-images.githubusercontent.com/6456652/35170645-9409811a-fd26-11e7-94ea-0f1ad4eb1b42.jpg)

Yet doing the same thing with Arduino code, its magnitudes faster. only taking 1.2us. 

`
    digitalWrite(chipSelectPin, LOW);
    SPI.transfer(0x55);
    digitalWrite(chipSelectPin, HIGH);
`
as can be seen here. 

![img_20180119_141656](https://user-images.githubusercontent.com/6456652/35170743-de353cd4-fd26-11e7-85ac-c0516e2f3566.jpg)

The problem is I do not want to use Arduino code, is there another solution that would dramatically shorten transaction time?   How is Arduino able to pull this off.

**Comment by negativekelvin** [comment]
spi_device_queue_trans or https://github.com/loboris/ESP32_NEW_SPI_MASTER_EXAMPLE

**Comment by versamodule** [comment]
Thanks, I'll give it a try tonight.

**Comment by FayeY** [comment]
Hi @versamodule , did the above suggestion help you resolve the issue?

**Comment by versamodule** [comment]
I ran into a deadline issue, and have not had the time to try it yet.

Sincerely,

Jimp@Versamodule.com

**Comment by FayeY** [comment]
Closing for now. Please feel free to reopen it if this issue persists.
