### ISSUE TITLE
example for COMPONENT_OWNBUILDTARGET

### ISSUE THREAD

**Issue by bbbsg** [espressif/esp-idf#1525]
I would like to use a third party library that comes with its own building steps

`./autogen.sh && ./configure --enable-this --disable-that && make `

From https://github.com/espressif/esp-idf/blob/master/docs/api-guides/build-system.rst it appears using `COMPONENT_OWNBUILDTARGET` in the library's component.mk is the way to go.

pointers or examples would help

**Comment by negativekelvin** [comment]
https://github.com/mruby-esp32/mruby-esp32/blob/3c2bfbc240d8a5a914dbe7e0f3df74f93d4e10b5/components/mruby_component/component.mk

**Comment by bbbsg** [comment]
thank you @negativekelvin
