### ISSUE TITLE
Loading application from openOCD

### ISSUE THREAD

**Issue by dumarjo** [espressif/esp-idf#153]
Hi,
Is it possible to upload the firmware through GDB ? When I try it, I got this error from openOCD

Error: esp32.cpu0: xtensa_write_memory (line 1024): DSR (8020CC13) indicates DIR instruction generated an exception! Warn : esp32.cpu0: Failed writing 4096 bytes at address 0x3F400010

Regards

Jonathan

**Comment by Spritetm** [comment]
Not yet; OpenOCD is not aware that the application lives in flash and will try to write to the flash as if it's RAM. Remedying this is on our ToDo-list, but we haven't gotten around to this.

**Comment by dumarjo** [comment]
Hi,

Thanx for the Info. 

Jonathan

**Comment by dantonets** [comment]
Hi,
I got this problem as well. The extensa-gdb works OK when start from the command line. But it fails with this message when I try start it from eclipse (Neon.3) - it try write to the drom0_0_seg, and, obviously fails - it read-only memory.  So, can somebody point me to the eclipse configuration for avoid this write?
Thanks.

**Comment by dantonets** [comment]
Never mind, I find a fix for that ..Thanks.
