### ISSUE TITLE
[TW#17877] 编写Pwm控制舵机程序，舵机无反应，但是led有闪烁 

### ISSUE THREAD

**Issue by liuyang77886** [espressif/esp-idf#1531]
编写Pwm控制舵机程序，舵机无反应，但是led有闪烁 
根据资料http://wiki.ai-thinker.com/esp32从官网下载固件
git clone --recursive https://github.com/espressif/esp-idf.git
拷贝官方例子get-started的hello_world
编写Pwm控制舵机程序，1毫秒高电平19毫秒低电平，舵机转向为45度，舵机有单独供电5V3A电源，接线信号线（橙色）、5V电源正（红）、电源负（棕，与esp32共地）
程序文件testgpio.c，主要代码如下：
hw_gpio_init();
gpio_set_level(GPIO_BLUE_LED, 0);
        vTaskDelay(2000 / portTICK_RATE_MS); 
        gpio_set_level(GPIO_BLUE_LED, 1);
        vTaskDelay(1);//1毫秒高电平
        gpio_set_level(GPIO_BLUE_LED, 0);
        vTaskDelay(5000 / portTICK_RATE_MS);//5秒低电平

testgpio.c：
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "freertos/queue.h"
#include "driver/gpio.h"

#include "esp_system.h"
#include "esp_err.h"
#include "esp_event_loop.h"
#include "esp_event.h"
#include "esp_attr.h"
#include "esp_log.h"
#include "esp_eth.h"
#include "testgpio.h"

#define GPIO_BLUE_LED 16

static const char *TAG = "GPIO_Example";

void hw_gpio_init(void)
{
    gpio_config_t io_conf;

    //disable interrupt
    io_conf.intr_type = GPIO_PIN_INTR_DISABLE;
    //set as output mode
    io_conf.mode = GPIO_MODE_OUTPUT;
    //bit mask of the pins that you want to set,e.g.GPIO16
    io_conf.pin_bit_mask = (1<<GPIO_BLUE_LED);
    //disable pull-down mode
    io_conf.pull_down_en = 0;
    //disable pull-up mode
    io_conf.pull_up_en = 1;
    //configure GPIO with the given settings
    gpio_config(&io_conf);
}

void hw_gpio_main()
{
    hw_gpio_init();
    for (int i = 100; i >= 0; i--) {
           printf("===========gpio in %d seconds...\n", i);

        gpio_set_level(GPIO_BLUE_LED, 0);
        vTaskDelay(2000 / portTICK_RATE_MS);

        gpio_set_level(GPIO_BLUE_LED, 1);
        vTaskDelay(1);
        gpio_set_level(GPIO_BLUE_LED, 0);
        vTaskDelay(5000 / portTICK_RATE_MS);

        gpio_set_level(GPIO_BLUE_LED, 1);
        vTaskDelay(2);
        gpio_set_level(GPIO_BLUE_LED, 0);
        vTaskDelay(3000 / portTICK_RATE_MS);
    }
}

**Comment by costaud** [comment]
Please do use hardware module, like LEDC or MCPWM, to generate a PWM signal. You can refer to the corresponding examples in example/peripherals.

In addition, the FreeRTOS vTaskDelay should not be used to generate a precise timing, especially the tick frequency is 100Hz by default in menuconfig.

**Comment by FayeY** [comment]
Hi @liuyang77886 , did the above suggestion help you resolve the issue?
