### ISSUE TITLE
[TW#17879] 编写连接wifi程序，程序运行报错。

### ISSUE THREAD

**Issue by liuyang77886** [espressif/esp-idf#1532]
编写连接wifi程序，程序运行报错。
根据资料http://wiki.ai-thinker.com/esp32从官网下载固件
调试发现是在esp_wifi_init(&cfg)这里报错，我发现esp_wifi_init调用esp_wifi_init_internal，但是没有esp_wifi_init这个方法，只有在esp_wifi_internal.h里有定义没有实现。
程序文件testwifi.c，主要代码如下：
tcpip_adapter_init();
    ESP_ERROR_CHECK(esp_event_loop_init(event_handler, NULL));
    ESP_LOGI(TAG, "==========a");
    wifi_init_config_t cfg = WIFI_INIT_CONFIG_DEFAULT();
    ESP_LOGI(TAG, "==========b");
    ESP_ERROR_CHECK(esp_wifi_init(&cfg));
    ESP_LOGI(TAG, "==========c");
运行报错如下：
[0;32mI (22146) ========: ==========3[0m
[0;32mI (22146) ========: ==========4[0m
[0;32mI (22146) ========: ==========a[0m
[0;32mI (22146) ========: ==========b[0m
I (22146) wifi: wifi firmware version: 403db1d
I (22156) wifi: config NVS flash: enabled
I (22156) wifi: config nano formating: disabled
[0;32mIGuru Meditation Error: Core  1 panic'ed (LoadStoreError)
. Exception was unhandled.

testwifi.c：
#include "freertos/FreeRTOS.h"
#include "freertos/event_groups.h"
#include "esp_wifi.h"
#include "esp_log.h"
#include "esp_event_loop.h"
#include "nvs_flash.h"

/*Set the SSID and Password via "make menuconfig"*/
#define DEFAULT_SSID "ffff"
#define DEFAULT_PWD "ffffffff"

#define DEFAULT_SCAN_METHOD WIFI_FAST_SCAN

//#define DEFAULT_SORT_METHOD WIFI_CONNECT_AP_BY_SECURITY

#define DEFAULT_SORT_METHOD WIFI_CONNECT_AP_BY_SIGNAL

#define DEFAULT_AUTHMODE WIFI_AUTH_WPA2_PSK

#define DEFAULT_RSSI -127

static const char *TAG = "========";

static esp_err_t event_handler(void *ctx, system_event_t *event)
{
    switch (event->event_id) {
        case SYSTEM_EVENT_STA_START:
            ESP_LOGI(TAG, "SYSTEM_EVENT_STA_START");
            ESP_ERROR_CHECK(esp_wifi_connect());
            break;
        case SYSTEM_EVENT_STA_GOT_IP:
            ESP_LOGI(TAG, "SYSTEM_EVENT_STA_GOT_IP");
            ESP_LOGI(TAG, "Got IP: %s\n",
                     ip4addr_ntoa(&event->event_info.got_ip.ip_info.ip));
            break;
        case SYSTEM_EVENT_STA_DISCONNECTED:
            ESP_LOGI(TAG, "SYSTEM_EVENT_STA_DISCONNECTED");
            ESP_ERROR_CHECK(esp_wifi_connect());
            break;
        default:
            break;
    }
    return ESP_OK;
}

/* Initialize Wi-Fi as sta and set scan method */
static void wifi_scan(void)
{
    tcpip_adapter_init();
    ESP_ERROR_CHECK(esp_event_loop_init(event_handler, NULL));
    ESP_LOGI(TAG, "==========a");
    wifi_init_config_t cfg = WIFI_INIT_CONFIG_DEFAULT();
    ESP_LOGI(TAG, "==========b");
    ESP_ERROR_CHECK(esp_wifi_init(&cfg));
    ESP_LOGI(TAG, "==========c");
    wifi_config_t wifi_config = {
        .sta = {
            .ssid = DEFAULT_SSID,
            .password = DEFAULT_PWD,
            .scan_method = DEFAULT_SCAN_METHOD,
            .sort_method = DEFAULT_SORT_METHOD,
            .threshold.rssi = DEFAULT_RSSI,
            .threshold.authmode = DEFAULT_AUTHMODE,
        },
    };
    ESP_LOGI(TAG, "==========d");
    ESP_ERROR_CHECK(esp_wifi_set_mode(WIFI_MODE_STA));
    ESP_ERROR_CHECK(esp_wifi_set_config(ESP_IF_WIFI_STA, &wifi_config));
    ESP_LOGI(TAG, "==========e");
    ESP_ERROR_CHECK(esp_wifi_start());
    ESP_LOGI(TAG, "==========f");
}

void wifi_mainTask()
{
    // Initialize NVS
    esp_err_t ret = nvs_flash_init();
    if (ret == ESP_ERR_NVS_NO_FREE_PAGES) {
        ESP_ERROR_CHECK(nvs_flash_erase());
        ret = nvs_flash_init();
    }else{
    	 ESP_LOGI(TAG, "==========3");
    }
    ESP_ERROR_CHECK( ret );
    ESP_LOGI(TAG, "==========4");
    wifi_scan();
}

**Comment by TimXia** [comment]
@liuyang77886 The demo has no problem on my borad. Could you please provide the full log of the crash including backtrace. You can also erase flash before burn the bin file.

**Comment by FayeY** [comment]
Closing due to lack of response, please feel free to reopen if this is still an issue and you can supply more details. Thanks.
