### ISSUE TITLE
[TW#17984] SPI_TRANS_MODE_DIOQIO_ADDR and SPI_TRANS_VARIABLE_CMD use same bit

### ISSUE THREAD

**Issue by lllucius** [espressif/esp-idf#1549]
In spi_master.h, the same bit mask is used for the SPI_TRANS_MODE_DIOQIO_ADDR and SPI_TRANS_VARIABLE_CMD flags.

This happened in #654.

**Comment by ginkgm** [comment]
sorry, we'll fix this soon.

**Comment by lllucius** [comment]
While you're in there working on it, it would be nice (but not required) to add SPI_TRANS_VARIABLE_DUMMY and corresponding spi_transaction_ext_t field as well.  There's a way go do per transaction without having the option, but it would just be easier.
