### ISSUE TITLE
[TW#17997] Make is paused when TTY is paused

### ISSUE THREAD

**Issue by paulreimer** [espressif/esp-idf#1551]
I use `screen` to manage multiple terminal windows, for example one terminal just to run `make`.

When I use the "scrollback" feature in screen (which pauses the console output), then it seems the esp-idf build process gets paused, too. (it stops compiling, until scrollback is exited)

Minimal repro:
```
$ screen
$ make
<hit Ctrl-A then Esc == enter scrollback mode>
<wait any amount of time, e.g. 10min>
<hit Esc == exit scrollback mode>
```

You would expect the build to be finished in 10min (I've tried leaving it for 1 hour!), but it is still roughly at the point where you entered scrollback mode.

FYI I am using macOS.

**Comment by DavidAntliff** [comment]
If it helps, I tried this on Linux and I confirm what you see.

Here's a simple example that shows how screen's "scrollback" mode (actually called "Copy mode") doesn't pause all underlying processes:

```while ((1)) ; do echo $i; i=$((i+1)); sleep 0.1; done```

Let it run for a second, then enter scrollback mode and note the last number displayed. Wait 10 seconds then exit scrollback mode and you'll see the numbers have advanced in the meantime.

However I tried it with `make` on another, unrelated C project and it blocks there too.

But this one doesn't block (each line starts with a tab):

```
.PSEUDO: count
count:
    number=1 ; while (true) ; do \
        echo $$number ; \
        number=$$((number + 1)) ; \
        sleep 0.1 ; \
    done
```

This is an interesting problem, because it seems to block some processes (like ESP-IDF make) but not others. A Ctrl-A+Q does not "unblock" the terminal either, so I don't think it's a rogue XON character.

Anyway, FWIW.

**Comment by DavidAntliff** [comment]
BTW, there must be a limit as to how much output GNU screen can buffer before it has to stop the inner processes, because memory isn't infinite. Have you seen GNU screen not block with other programs that have copious output? I'm not sure how large the output buffer is, but 256 to 8192 bytes comes to mind (see `obuflimit` which is 256, maximum 8192), which isn't enough to store the entire compilation output. Perhaps this is just how screen works and you're used to only seeing small amounts of output, which don't hit obuflimit and therefore don't cause screen to block the processes?

**Comment by paulreimer** [comment]
I can say anecdotally that I have never perceived this before, and I used to be several `screen`s deep building Yocto images which can be incredibly verbose. The underlying `screen` in that case might have always been on a Linux though. Still, no reason to suspect `screen` as the culprit (yet). I am accustomed to holding `screen` in "copy mode" in several tabs while I am inspecting the output, and usually when I resume there is a wall of text for me to inspect. I've long since set my copy buffer length at 10000 lines, so my operating value may be very large such that I wouldn't notice without a stopwatch.

**Comment by projectgus** [comment]
Hi folks,

That is an interesting observation! Unfortunately I believe it is a limitation of screen, and I'm not sure it's limited to GNU make. Here's some quick poking around I did:

For the simple "infinite white loop" bash example, you can demonstrate this more quickly by removing the "sleep 0.1" from the loop so it prints numbers at maximum speed.

* Run the infinite while loop in a screen session.
* Outside the screen session (ie different terminal), check top or htop and see that the bash process is pinning a CPU.
* If you `sudo strace -p PID_OF_BASH` then you'll see lots of write() system calls streaming past:
   ```
  write(1, "4066532\n", 8)                = 8
  write(1, "4066533\n", 8)                = 8 
  write(1, "4066534\n", 8)                = 8
  write(1, "4066535\n", 8)                = 8
  write(1, "4066536\n", 8)                = 8
  ```
* If you go back to screen and enter Copy mode, you'll see them suddenly stop a little while later as the write() system call suddenly blocks.
* In my case, I calculated (`(last number printed before blocking)-(last number shown in Copy mode) * 8 chars per write`) that there's about 10KB of buffering on my system before the write() blocks.

lsof tells us that (on Linux at least) stdout of a screen child process is a PTY. Some quick Google searches failed to turn up if there's a way to change the internal PTY buffer size on Linux, although apparently it used to be 4KB so it's changed a bit somewhere along the line! YMMV on different Linux distros or if you're using MSYS or macOS... A quick hunt in the Linux source may also turn up an answer to this.

Maybe there is some way to make stdout non-blocking (pipe the output of make to something which just echoes to a non-blocking stdout, which will drop data once the PTY is full). Or screen could find a way to drop bytes from the PTY while in Copy mode, as there's more there than the scrollback can handle anyhow. Or perhaps tmux doesn't have this problem...

Anyway, that was interesting to explore but I'm going to close this Issue as I don't think it's an issue in ESP-IDF. Please reopen if you think that's not the case.

**Comment by projectgus** [comment]
(For the record, I did the same thing with make - ran `make` then outside screen `strace -f -p PIDOF_TOPLEVEL_MAKE` to trace make and its child processes (this doesn't trace existing child processes, but it starts from the next child the make jobserver forks). Same behaviour, eventually the write() syscall blocks writing to stdout. Unblocks when you leave Copy mode.

(I had to `make VERBOSE=1` to get enough output for it to block on my system, though. I guess normal verbosity doesn't fill up the 10KB buffer. Again, YMMV.)

**Comment by projectgus** [comment]
Oops, I missed you were using macOS. Maybe PTY buffers are smaller on macOS? Dtruss can probably get some insight, if you care enough to dig around :)

**Comment by paulreimer** [comment]
OK thanks, that is helpful! My specific workflow is to run `make flash monitor` within a `screen` terminal, and I very frequently also want to scrollback and review something in the output from the previous `monitor`'s output (might as well do _something_ while compiling). But in so doing, that stalls the `make`. So I guess my goal here is to reduce the chattiness of the `make flash` process or find a better workflow.

I very rarely want to review anything from `make`'s stdout, and perhaps something like the percentages that esptool are writing is generating more write activity that I don't need. I'll start fiddling with flags over time to find something that works for me!

**Comment by projectgus** [comment]
Ah, yes. esptool.py does do quite a lot of writes displaying the percentages so that might be part of it.

It might be worth checking out tmux, at least to see if this problem exists there as well?

**Comment by paulreimer** [comment]
Yup, seems others have reported similar issues with `tmux`.
https://stackoverflow.com/questions/13924365/rails-freezes-when-searching-through-tmux-output-buffer

It seems like it is just a limitation of a finite buffer, so I can increase the buffer size or decrease the verbosity.

FWIW, I know some tools that output progress bars have a CI-friendly mode that doesn't spam the log with all the (re)writes. Some, it must detect if it doesn't get the right kind of TTY (somehow?) Others, it's either an env var or --flag (this seems easiest). Still others, I guess must avoid re-writes like that in the output just by design of the output? Maybe esptool could use an option like that?

**Comment by DavidAntliff** [comment]
It is possible for a process to determine whether a TTY (or PTY) is present on stdout. I've used this to detect a TTY or PTY in Jenkins CI jobs:

```
if [ -t 1 ]; then
    TTY_PRESENT=1
else
    TTY_PRESENT=0
fi
```

**Comment by projectgus** [comment]
> FWIW, I know some tools that output progress bars have a CI-friendly mode that doesn't spam the log with all the (re)writes. Some, it must detect if it doesn't get the right kind of TTY (somehow?) Others, it's either an env var or --flag (this seems easiest). Still others, I guess must avoid re-writes like that in the output just by design of the output (e.g. the dots/dashes in the handshake part of the esptool device connection)? Maybe esptool could use an option like that for the flashing?

Yes, feel free to open a feature request on the esptool repo for an option like this. (Or a PR always welcome, I guess!)

> It is possible for a process to determine whether a TTY (or PTY) is present on stdout. 

Yes. In this case, it may be a bit difficult because screen *is* a TTY so I think it's indistinguishable from a bona fide interactive session, in this way...

**Comment by projectgus** [comment]
You could probably work around this on a case-by-case basis by writing a small shell script or program that redirects stdout to a temporary file, and simultaneously reads from that file to stdout. The file will keep growing if writing to stdout starts blocking, but because the blocking happens in the script/program it doesn't block whatever is producing the output in the first place.

**Comment by paulreimer** [comment]
FWIW I have changed my workflow to use vim8's `Term` features. (well, I use `neovim` but it's similar). I still use this setup in a terminal within a `screen`, but vim's approach (unlike `screen`/`tmux`) seems to be a ringbuffer, so old lines get lost. The downside seems to be that for long traces or whatnot, the default buffer size means important lines are lost. Also, two sets of keyboard shortcuts.

Anyway, now I have tools using both approaches, so I can try to pick the right one for the occasion.

**Comment by projectgus** [comment]
There's always reptyr for when you get it wrong :D https://github.com/nelhage/reptyr#reptyr---a-tool-for-re-ptying-programs
