### ISSUE TITLE
[TW#18310] ble security error

### ISSUE THREAD

**Issue by JoonDong2** [espressif/esp-idf#1561]
I tested gatt_securty_server example in the esp-idf on some android version and iOS.

It works well on android nougat(7.x.x) and iOS but not on android kitkat(4.x.x) and marshmallow(6.x.x).

On kitkat, it worked up to bonding but disconnected with gatt error 0x81(gatt internal error) when reconnected.

On marshmallow, it did not even bond with 0x89(related with authentication) error.

I had a similar question before, but I was told that it was reported to the development team.

Is this a bug?? If this is a bug, are you fixing it?

**Comment by Yulong-espressif** [comment]
@JoonDong2 what does the IDF version you using it?

**Comment by JoonDong2** [comment]
I tested by using latest version. I re-installed esp-idf yesterday.

**Comment by Weijian-Espressif** [comment]
@JoonDong2  sorry for being late, We are fixing a bug about securty, you will be notified later.

**Comment by EspressifApp** [comment]
@JoonDong2 please update to the latest IDF, and try?

**Comment by JoonDong2** [comment]
@EspressifApp I tried it and it worked well on Android 4.4.4(Kitkat) and 6.0.1(Marchmallow).
