### ISSUE TITLE
[TW#18311] Bluetooth transmission problem

### ISSUE THREAD

**Issue by wangweidaai** [espressif/esp-idf#1562]
use a2dp_source example，When you turn off the bluetooth headset, esp32 reports the error and restarts the program.

**Comment by Weijian-Espressif** [comment]
@blueMoodBHD please help review the issue.

**Comment by blueMoodBHD** [comment]
@wangweidaai Because I did not reproduce the problem, can you provide the relevant log? Thanks

**Comment by FayeY** [comment]
Closing as can't reproduce. Please reopen if the issue persists and you can supply more details. Thanks.
