### ISSUE TITLE
[TW#18495] Is SYSTEM_EVENT_AP_PROBEREQRECVED has been enabled? 

### ISSUE THREAD

**Issue by Avi-TelnT** [espressif/esp-idf#1564]
Is SYSTEM_EVENT_AP_PROBEREQRECVED has been enabled in the last esp-IDF?
If not, what is the expect date to let be enabled?
Is there any way to get this events be register to wifi init ? 
        Can someone point me to any sample?

**Comment by TimXia** [comment]
@Avi-TelnT Sorry it has not been ready yet. It will be done in the next two weeks.

**Comment by Avi-TelnT** [comment]
Thank you @TimXia 
My coworker Dr. Nissim Zur will send you email why SYSTEM_EVENT_AP_PROBEREQRECVED  is important to IOT Artificial Intelligence.
