### ISSUE TITLE
[TW#18497] How to set or get class of device of bluetooth classic

### ISSUE THREAD

**Issue by my-abousamra** [espressif/esp-idf#1565]
Hi,

How to set or get class of device of bluetooth classic for my device as I only find functions to process class of device to get major/minor device

Regards

**Comment by Weijian-Espressif** [comment]
@blueMoodBHD Please help solve this problem.

**Comment by blueMoodBHD** [comment]
@my-abousamra 
Call function  esp_bt_gap_cancel_discovery();
Then esp_bt_gap_cb_t will is called with ESP_BT_GAP_DISC_RES_EVT, in param->disc_res.prop[],if there is one that param->disc_res.prop[i].type == ESP_BT_GAP_DEV_PROP_COD, then param->disc_res.prop[i].val is the class of device.

**Comment by my-abousamra** [comment]
@blueMoodBHD 
1.  Is this the way to get the current running device COD, not a remote one? I thought it is a usual function to get it.  
2.  How to set it to my device?

**Comment by blueMoodBHD** [comment]
@my-abousamra We do not have the APIs to set and read cod at this moment, we will provide those APIs as soon as possible, Thanks

**Comment by blueMoodBHD** [comment]
@my-abousamra Now, there is no API to set and get  the current running device COD, and we will add the APIs ASAP.

**Comment by my-abousamra** [comment]
@blueMoodBHD any updates, please?

**Comment by blueMoodBHD** [comment]
@my-abousamra We will try to finish this in v3.1, thanks.

**Comment by my-abousamra** [comment]
@blueMoodBHD when will it be released, please?

**Comment by my-abousamra** [comment]
Works fine, Thanks!
