### ISSUE TITLE
different type for struct member unicast in mdns? (IDFGH-717)

### ISSUE THREAD

**Issue by devyte** [espressif/esp-idf#1568]
Hi,

in mdns/private_include/mdns_private.h, there are two structs that are almost identical:
```
typedef struct mdns_parsed_question_s {
    struct mdns_parsed_question_s * next;
    uint16_t type;
    bool unicast;   /* <--- */
    char * host;
    char * service;
    char * proto;
    char * domain;
} mdns_parsed_question_t;
```

vs.

```
typedef struct mdns_out_question_s {
    struct mdns_out_question_s * next;
    uint16_t type;
    uint8_t unicast;   /* <--- */
    const char * host;
    const char * service;
    const char * proto;
    const char * domain;
} mdns_out_question_t;
```

Besides the char* const-ness difference, the unicast type isn't the same. Is this last intentional?
Considering this is C, the bool is probably a typedef to a uint8, in which case this is just cosmetic, but it struck me as odd.

**Comment by david-cermak** [comment]
Hi @devyte 

I think the original intention was to differentiate between a struct formed from an incoming packet building a little of a logical abstraction and the one used to generate outgoing packet with more focus on bit fields in the binary packet. However in this case of `unicast` field, as you have mentioned, there is (almost) no difference and moreover in the mdns code the `mdns_out_question_s::unicast` field is treated as boolean everywhere, so it's safe (and a good idea) to update  it.

Thank you for pointing out this inconsistency!
