### ISSUE TITLE
cJSON: Update to get rid of memory bug

### ISSUE THREAD

**Issue by PerMalmberg** [espressif/esp-idf#1577]
cJSON 1.6.0 contains a bug causing a too small buffer being allocated, this has been fxed in 1.7.1.

https://github.com/DaveGamble/cJSON/compare/v1.6.0...master#diff-f81629e70775a711645d6df20d975bf5L1118

**Comment by projectgus** [comment]
Thanks for the heads-up! I think a few people have been reporting issues around this. Will update.
