### ISSUE TITLE
Windows install instructions contain an error related to ~/esp

### ISSUE THREAD

**Issue by mike-rankin** [espressif/esp-idf#1579]
I'm following the Windows install instructions as written and see it mention that files will be written to ~/esp but nowhere does it say to create /esp anywhere.
Please update the Windows install instrucions/

**Comment by igrr** [comment]
This is currently mentioned in http://esp-idf.readthedocs.io/en/latest/get-started/index.html:

We are using ~/esp directory to install the prebuilt toolchain, ESP-IDF and sample applications. You can use different directory, but need to adjust respective commands.

**Comment by FayeY** [comment]
Hi @mike-rankin , did the above suggestion help you resolve the issue?
