### ISSUE TITLE
[TW#18508] Configurable binary name

### ISSUE THREAD

**Issue by SteveOfTheStow** [espressif/esp-idf#1583]
Looking at project.mk, the name of the project binary appears to be hardcoded:

`APP_ELF:=$(BUILD_DIR_BASE)/$(PROJECT_NAME).elf
APP_MAP:=$(APP_ELF:.elf=.map)
APP_BIN:=$(APP_ELF:.elf=.bin)`

I'd like to append a version to my binary filename, which is sourced from a file in my project, but no obvious way to do it in my Makefile.
I can submit a pull request to enable it to be overridden but wanted to check I haven't missed some already implemented or planned functionality?

**Comment by igrr** [comment]
The easiest option would be to set `PROJECT_NAME` variable in your project makefile to include the version. Would that work for your case?

**Comment by igrr** [comment]
@SteveOfTheStow Please feel free to reopen if the suggested approach does not work for you.
