### ISSUE TITLE
lwip_close does not work

### ISSUE THREAD

**Issue by ManuTester** [espressif/esp-idf#1592]
I copied some snippets from some example code,
It was using lwip_socket() and lwip_close(). I thought that it is the same as socket() and close().
I found out that it would only work a few times, after that, creating a socket fails with -1.
It took me some time to find out, that the lwip_close() is the problem. It does not free the socket, although it compiles fine and does also not return any error.
lwip_socket() and socket() seems to be interchangeable though, or not?

Here is some example code:

> static int wifi_cmd_bugcheck(int argc, char** argv)
> {
>     int s,i,ret;
>     for(i=0;i<10000;i++) {
>         if ((s = lwip_socket(AF_INET, SOCK_RAW, IP_PROTO_ICMP)) < 0) {
>             printf("Error %d creating socket after doing so successfully %d times\n",s,i);
>             return 1;
>         }
>         if((ret=lwip_close(s)) < 0) {
>             printf("Error %d closing socket\n",ret);
>         }
>     }
>     printf("Socket open/close seems ok %d times\n",i);
>     return 0;
> }

Replace lwip_close with close, and it will work.
I can circumvent the problem now, but any kind of warning not to use lwip_close would have been VERY useful!

I'm using the latest esp-idf (pulled today) and toolchain 20180110.

**Comment by negativekelvin** [comment]
See comments https://github.com/espressif/esp-idf/pull/537

**Comment by FayeY** [comment]
Hi @ManuTester , did the above suggestion help you resolve the issue?
