### ISSUE TITLE
ESP32 unexpectedly disconnected from WiFi AP 

### ISSUE THREAD

**Issue by MakerAsia** [espressif/esp-idf#16]
I connect ESP32 board to WiFi and do HTTP POST the sensor data to cloud server every 30 seconds. It works fine for around 6 minutes then it show messages:

rbk
bcn_timout,ap_probe_send_start
ap_probe_send over, rest wifi status to disassoc
state: 5 -> 0 (1)
n:6 0, o:6 0, ap:255 255, sta:6 2, prof:1

Then ESP32 was disconnected from WiFi and could not reconnect.

**Comment by projectgus** [comment]
Thanks for reporting this @MakerAsia . We're tracking this one on our internal issue tracker as well, we'll update you ASAP once we have a fix.

**Comment by igrr** [comment]
Fixed in 4f93b49e.
