### ISSUE TITLE
Docs: Mixed languages

### ISSUE THREAD

**Issue by PerMalmberg** [espressif/esp-idf#1602]
The English version of the getting started guide for the Pico kit has a mixed (what I presume is) Chinese and English navigation area.

http://esp-idf.readthedocs.io/en/latest/get-started/get-started-pico-kit.html

Update: It seems the mix is present in other pages as well:
http://esp-idf.readthedocs.io/en/latest/get-started/idf-monitor.html?highlight=jtag

This is how it looks for me
![image](https://user-images.githubusercontent.com/2729388/36016531-c234ed9c-0d73-11e8-9209-088c4860b84a.png)

**Comment by krzychb** [comment]
Hi @PerMalmberg,

Thank you for pointing this out. 
I have submitted a pull request to get it resolved.

**Comment by igrr** [comment]
Languages can now be chosen using pop-up panel at the bottom of the navigation area.
