### ISSUE TITLE
Docs: Searching for JTAG leads to a dead end. (IDFGH-221)

### ISSUE THREAD

**Issue by PerMalmberg** [espressif/esp-idf#1603]
Searching for [JTAG](http://esp-idf.readthedocs.io/en/latest/search.html?q=jtag&check_keywords=yes&area=default#) gives a list of pages. The interesting one, labeld "Debugging" goes to a 404 page: http://esp-idf.readthedocs.io/en/latest/api-guides/openocd.html?highlight=jtag

**Comment by krzychb** [comment]
Hi @PerMalmberg,

This is a good point!

The issue with "Debugging" has been reported some time ago as https://github.com/rtfd/readthedocs.org/issues/3108.

I will check with Read the Doc team what are the options to get it resolved.

**Comment by krzychb** [comment]
I do not see this issue anymore. @PerMalmberg please feel free to reopen if it persists.
