### ISSUE TITLE
ESP-IDF A2DP-SOURCE demo: WORK VERY GOOD！Cloud be connect to WIN7 realtek Audio?

### ISSUE THREAD

**Issue by mxwang101** [espressif/esp-idf#1624]
I do connect to my Blue Speaker and heard the random noise! 

Could you please give us somg code, so we can send the real  PCM media data form Win7 Realtek High Definition Audio over esp32 A2dp_source to the Blue Speaker?

Thanks!

**Comment by ESP32DE** [comment]
@mxwang101 
do you have an Issues with A2dp-source or do you want make a **talk/discussion/request** to/for a code example?
if you want talk/discussion/request over a code example perhabs better this to open on [esp32 forum](http://esp32.com) with a new post in [general discussion](https://esp32.com/viewforum.php?f=2) ?

note: 

> send the real PCM media data form Win7 Realtek High Definition Audio over esp32 A2dp_source to the Blue Speaker?

you can switch on BT on your Win7 Realtek High Definition Audio PC and send real PCM media data to the Blue Speaker. For this you need not the A2dp-source. 
If you want send this Data from your esp32 as A2dp-source you can use for source sd card, spiffs, wifi web content and so on - So not sure, what you want to do at end in detail, so it is better for discussion on the [esp32 forum](http://esp32.com) and close this "talk" in the Issues Arena. 

happy spring festival!
