### ISSUE TITLE
Poor WiFi AP performance on Rev 1 chips on specific channels

### ISSUE THREAD

**Issue by mill1000** [espressif/esp-idf#1625]
I am observing poor AP performance on Rev 1 chips, when the channel is set to 2, 4 or 5. The same code operates well on Rev 0 chips. The WiFi environment on those channels is relatively free from interference.

Wireshark shows occasional TCP re-transmissions, but additional testing showed TCP and UDP to be equally effected.

Currently building with esp-idf commit cf2600a

Edit: A co-worker has confirmed that his Rev 1 chips do not show the same behavior. If it is indeed the WiFi environment causing the issue, why are Rev 0 chips not effected?

**Comment by negativekelvin** [comment]
Did you try to erase flash or force full calibration?

**Comment by mill1000** [comment]
I have performed make erase_flash. Is there another method of triggering calibration?

**Comment by negativekelvin** [comment]
There is a menuconfig option to not store calibration so it will be performed every boot

**Comment by mill1000** [comment]
Additional testing has found that this problem only occurs in some of my modules. Is it likely a result of their installation, and not an underlying issue with the Rev 1 chip.

Apologies, I jumped the gun on this one.
