### ISSUE TITLE
no download available for window tool chain

### ISSUE THREAD

**Issue by Mr-Techtron** [espressif/esp-idf#1633]
https://dl.espressif.com/dl/esp32_win32_msys2_environment_and_toolchain-20170111.zip
though I tried to download through above link, no download process is initiated and always showed me "Problem loading page" as if the link is down. Has anybody encountered this recently?

**Comment by negativekelvin** [comment]
https://esp-idf.readthedocs.io/en/latest/get-started/index.html#setup-toolchain

**Comment by Mr-Techtron** [comment]
Thanks. I think there was a problem with my laptop. When I tried in my desktop it worked fine.
