### ISSUE TITLE
[TW#18647] Failed Directed Advertising doesn't generate an LE Connection Complete 

### ISSUE THREAD

**Issue by jakkra** [espressif/esp-idf#1645]
A HCI connection complete event is not received after performing a directed advertisement which fails to create a connection.

According to the [v5.0 core spec, page 1260](https://www.bluetooth.org/DocMan/handlers/DownloadDoc.ashx?doc_id=421043)

> If the Advertising_Type parameter is 0x01 (ADV_DIRECT_IND, high duty
cycle) and the directed advertising fails to create a connection, an LE
Connection Complete or LE Enhanced Connection Complete event shall be
generated with the Status code set to Advertising Timeout (0x3C).

HCI LOG:
```
CMD => 0A 20 01 00 // Disable advertise
EVT <= 0E 04 05 0A 20 00 //Success
CMD => 06 20 0F 40 06 D0 07 01 00 00 35 60 83 F3 12 00 07 00 // Set Adv Params, type 0x01 (directed to dummy address)
EVT <= 0E 04 05 06 20 00 // Success
CMD => 0A 20 01 01 // Enable advertise
EVT <= 0E 04 05 0A 20 00 // Success
We never get a LE Connection Complete here.
```

ESP-IDF 3.0

**Comment by Weijian-Espressif** [comment]
@jakkra How to reproduce this issue?

**Comment by jakkra** [comment]
Hi!

Start an advertisement of type `ADV_DIRECT_IND, high duty cycle`. According to the spec a LE Connection Complete HCI event shall be generated if no device connects to us within some timeout, with Status code 0x3C. 

We aren't using the Bluedroid stack, but this problem should affect it too, since this is in the HCI layer. I don't have an example application for you, because I think it should be easy enough to reproduce.

I guess using the bluedroid stack, all you need to do is to start directed advertising with high duty cycle and then watch the HCI log, correct behaviour is a LE connection complete with status code 0x3c.

**Comment by Weijian-Espressif** [comment]
@jakkra thanks for your help , Our controller will generate a LE connection complete with status code 0x3c.  you can add log in btm_ble_conn_complete() of btm_ble.c in line 1995.

**Comment by jakkra** [comment]
@Weijian-Espressif Thanks!
