### ISSUE TITLE
[TW#18660] AVRCP. Connection from speaker with esp32 to smartfone

### ISSUE THREAD

**Issue by KryvosheyaIvan** [espressif/esp-idf#1647]
There is an example a2dp_sink by means of which one can establish communication between smartfone and esp32. But what about if i want to play/stop/backward/pause/etc by means of buttons located on speaker?
I know it could be done own to bluetooth avrcp. Is it right?
Are there any examples ?

**Comment by Weijian-Espressif** [comment]
@blueMoodBHD Please help to answer the question.

**Comment by blueMoodBHD** [comment]
@KryvosheyaIvan Yes,it could be done own to bluetooth avrcp. These audio-related features we will open in another project, but now is not convenient to provide, thank you for understanding.

**Comment by blueMoodBHD** [comment]
@KryvosheyaIvan Is there any other problem? if not , can we close this issue?

**Comment by KryvosheyaIvan** [comment]
@blueMoodBHD, all OK!
