### ISSUE TITLE
what is UART_DATA_BITS_MAX?How many bits?

### ISSUE THREAD

**Issue by shq2333** [espressif/esp-idf#1654]
https://github.com/espressif/esp-idf/blob/d89542eb2b41d867882b822ed3e1c7cb6c97f05c/components/driver/include/driver/uart.h#L57

What is UART_DATA_BITS_MAX?
How many bits?
Is esp-idf support 9bits ?

**Comment by koobest** [comment]
Hi, @shq2333 
This is an upper limit value, the data width can not exceed or equal this value. the maximum data width is 8 bits in uart,  9bits are not supported.

**Comment by shq2333** [comment]
Thanks!I got it.
