### ISSUE TITLE
[TW#18782] ESP32 Tech Ref: Typo DPORT_APP_CAHCE_CTRL_REG

### ISSUE THREAD

**Issue by nkolban** [espressif/esp-idf#1655]
In the ESP32 Technical Reference v2.9:

In the first paragraph of 1.3.4 we read:

> PROCPU uses bit PRO_CACHE_ENABLE in register **DPORT_PRO_CAHCE_CTRL_REG** to enable the Cache, while APP CPU uses bit APP_CACHE_ENABLE in register **DPORT_APP_CAHCE_CTRL_REG** to enable the same function.

I believe the bold text to be a typo and should be **DPORT_PRO_CACHE_CTRL_REG**.

**Comment by igrr** [comment]
Thanks @nkolban, i have forwarded this to the documentation team, this will be fixed in the upcoming release of the TRM.
