### ISSUE TITLE
[TW#18946] i2s_adc_dac

### ISSUE THREAD

**Issue by joicetm** [espressif/esp-idf#1664]
Hi,

I have just tried the i2s_adc_dac example and it is working fine. it recorded the audio and played well :)
But i do not know how to save  the data from flash. should i use SPIFFS and write the data to a file or is there any other way which is already implemented somewhere ? 
i need to save the recorded data for some analysis, how should i proceed?

**Comment by panfeng-espressif** [comment]
Hi,
What do you want to save in flash, an audio file or other data? If it is an audio file, what format is it?

**Comment by joicetm** [comment]
Hi panfeng-espressif,

Thanks for the reply.
Actually i forgot to close this issue. I was reading the data from microphone through adc and wanted to do some analysis of the data. 
now i am sending the data through a tcp connection and using a python script on my system to do the analysis.
Anyway once again thanks for the support, is it okay if i re-open this issue in case of any help in future?
