### ISSUE TITLE
[TW#18952] Deactivate wakeup trigger

### ISSUE THREAD

**Issue by PRosenb** [espressif/esp-idf#1677]
Assume we want to do the following:
- start ESP32
- light sleep 1 minute
- do some work
- light sleep until an external interrupt occurs

For the first sleep we can do:
```c++
esp_sleep_enable_timer_wakeup(60 * 1000 * 1000L);
esp_light_sleep_start();
```

How can I deactivate the timer trigger for the second sleep?
When I do the following, the CPU wakes up after one minute.
```c++
pinMode(4, INPUT_PULLUP);
esp_sleep_enable_ext0_wakeup(GPIO_NUM_4, 0);
esp_light_sleep_start();
```
A workaround is to do that:
```c++
esp_sleep_enable_timer_wakeup(UINT64_MAX);
pinMode(4, INPUT_PULLUP);
esp_sleep_enable_ext0_wakeup(GPIO_NUM_4, 0);
esp_light_sleep_start();
```

To me it looks like such a function is missing in esp_sleep.h.

**Comment by liuzfesp** [comment]
@TimXia  help please.
