### ISSUE TITLE
Ability to disable make monitor 0x4xxx xxxx address decoding (IDFGH-180)

### ISSUE THREAD

**Issue by nkolban** [espressif/esp-idf#1679]
I'm a big fan of ESP-IDF "make monitor".  I also appreciate the decode of executable addresses to source statements when an address in the range 0x4xxx xxxx is detected.  This issue/request asks that we have an option to disable this decoding at execution time.  For example:

```
export MONITOR_DECODE=0
make monitor
```

... or some other definition.  In the work I am doing, I am actively debugging MMU and ESP32 address processing and in my "make monitor" output, I am seeing decoded addresses everywhere when I actually don't want to see any (at this time).

**Comment by jkhax0r** [comment]
Its a really cool option but would be nice to see something where we can ignore the false positive results during normal messages whenever printing any other standard hex value.  I haven't looked, but for example maybe all actual LOG messages can be modified to be prefixed with 0x whereas the stack dump isn't (or vice-versa).

**Comment by FHFS** [comment]
Quick and dirty comment https://github.com/espressif/esp-idf/blob/master/tools/idf_monitor.py#L425
