### ISSUE TITLE
After every 9 sec ESP32 rebooting with message mbedtls_ssl_handshake returned -0x10

### ISSUE THREAD

**Issue by sjoteppagol** [espressif/esp-idf#1695]
Hello All,
This is very strange issue I am facing from few days, I tried to resolve but I couldn't .
Here I am not actually getting root cause for this issue.
I have 

 `    xTaskCreate(main_task, "main_task", 2048+1024, NULL, 10, NULL);    

//  xTaskCreate(sensor_task, "sensor_task", 2048, NULL, 10, NULL) ; // This task causing issue
    xTaskCreatePinnedToCore(aws_iot_task, "aws_iot_task", 15 * 1024, NULL, 15, NULL, 1);
    xTaskCreate(power_task, "power_task", 2048, NULL, 15, NULL);
    xTaskCreate(rx_task, "uart_rx_task", 2048, NULL, 10, NULL);
    ble_task();`

**E (16056) aws_iot: failed! mbedtls_ssl_handshake returned -0x10
E (16056) APP_DEBUG: aws_iot_shadow_connect returned error -4, aborting...
abort() was called at PC 0x4010cd7b on core 1**

**Backtrace: 0x4008c5f4:0x3ffdf930 0x4008c6f3:0x3ffdf950 0x4010cd7b:0x3ffdf970**

Thank you
Shridhar

**Comment by negativekelvin** [comment]
https://github.com/espressif/esp-idf/issues/346

**Comment by FayeY** [comment]
Hi, did the above suggestion help you resolve the issue?

**Comment by sjoteppagol** [comment]
Hello FayeY,
I keep getting reboot once I get 
**E (12125) aws_iot: failed! mbedtls_ssl_handshake returned -0x4310
E (12135) APP_DEBUG: aws_iot_shadow_connect returned error -4, aborting...
abort() was called at PC 0x400d50bf on core 1**
I have attached the log for your reference.
Please advice
Thank you
![error](https://user-images.githubusercontent.com/34569563/37584876-21af09f2-2b7d-11e8-829b-761d67ec2024.PNG)

**Comment by negativekelvin** [comment]
Did you read the other issue about running out of memory when using aws_iot and Bluetooth together?

**Comment by sjoteppagol** [comment]
Hello negativekelvin,
Yes. But how to overcome this issue !?

**Comment by sjoteppagol** [comment]
Hello Negativekelvin,
Thank you. I gone through your provided link one more time and tried to decrease mbedTLS message length size and it is working now.

Thank you once again.
