### ISSUE TITLE
[TW#19272] Random crash on start of ota process (Wroom 32)

### ISSUE THREAD

**Issue by onb3891** [espressif/esp-idf#1697]
Wroom 32 (without PSRAM). 

My Application had GattClient enabled and active. 
When OTA process starts randomly. If BT Client is connected, crash happens quite consistently in (1 in 2 times)
Logs 1:

Guru Meditation Error: Core  0 panic'ed (Cache disabled but cached memory region accessed)
Register dump:
PC      : 0x40196f8c  PS      : 0x00060234  A0      : 0x800466c6  A1      : 0x3ffc0540  
0x40196f8c: r_dump_data at ??:?

A2      : 0x00000000  A3      : 0x40196f8c  A4      : 0x00000000  A5      : 0x00000010  
0x40196f8c: r_dump_data at ??:?

A6      : 0x3ffb93cc  A7      : 0x3ffb8360  A8      : 0x80019fb8  A9      : 0x000044a8  
A10     : 0xf2f2f2f2  A11     : 0x00000000  A12     : 0x0003f02d  A13     : 0x00000022  
A14     : 0x000023f0  A15     : 0x3ffb8360  SAR     : 0x0000001f  EXCCAUSE: 0x00000007  
EXCVADDR: 0x00000000  LBEG    : 0x00000000  LEND    : 0x00000000  LCOUNT  : 0x00000000  

Backtrace: 0x40196f8c:0x3ffc0540 0x400466c3:0x3ffc0570 0x400484ae:0x3ffc0590 0x40048672:0x3ffc05b0 0x4008784e:0x3ffc05d0 0x40087d07:0x3ffc05f0 0x40082b3d:0x3ffc0610 0x40083d2e:0x00000000
0x40196f8c: r_dump_data at ??:?

0x4008784e: r_rwble_isr at ??:?

0x40087d07: r_rwbtdm_isr_wrapper at intc.c:?

0x40082b3d: _xt_lowint1 at esp-idf/components/freertos/./xtensa_vectors.S:1105

0x40083d2e: spi_flash_op_block_func at esp-idf/components/spi_flash/./cache_utils.c:81

Log 2:
Guru Meditation Error: Core  0 panic'ed (Cache disabled but cached memory region accessed)
Register dump:
PC      : 0x40196f30  PS      : 0x00060834  A0      : 0x80086e7e  A1      : 0x3ffc0530  
0x40196f30: r_platform_reset at ??:?

A2      : 0x00000000  A3      : 0x40196f30  A4      : 0x00000000  A5      : 0x00000014  
0x40196f30: r_platform_reset at ??:?

A6      : 0x3ffb93cc  A7      : 0x3ffb8360  A8      : 0x80019fb8  A9      : 0x000044bc  
A10     : 0xf2f2f2f2  A11     : 0x0000a55a  A12     : 0x0003f02d  A13     : 0x00000020  
A14     : 0x000002d0  A15     : 0x40083d10  SAR     : 0x00000019  EXCCAUSE: 0x00000007  
0x40083d10: spi_flash_op_block_func at esp-idf/components/spi_flash/./cache_utils.c:71

EXCVADDR: 0x00000000  LBEG    : 0x00000000  LEND    : 0x00000000  LCOUNT  : 0x00000000  

Backtrace: 0x40196f30:0x3ffc0530 0x40086e7b:0x3ffc0560 0x40048566:0x3ffc0590 0x40048672:0x3ffc05b0 0x4008784e:0x3ffc05d0 0x40087d07:0x3ffc05f0 0x40082b3d:0x3ffc0610 0x40083d2e:0x00000000
0x40196f30: r_platform_reset at ??:?

0x40086e7b: r_lld_pdu_rx_handler at ??:?

0x4008784e: r_rwble_isr at ??:?

0x40087d07: r_rwbtdm_isr_wrapper at intc.c:?

0x40082b3d: _xt_lowint1 at esp-idf/components/freertos/./xtensa_vectors.S:1105

0x40083d2e: spi_flash_op_block_func at esp-idf/components/spi_flash/./cache_utils.c:81

**Comment by projectgus** [comment]
Hi @onb3891 ,

I'm really sorry noone got back to you about this. I think the underlying issue is the same one which was fixed in the linked issue. If you're still seeing this problem with IDF master branch, please let us know.
