### ISSUE TITLE
Windows Zip File Doesn't Contain ESP directory

### ISSUE THREAD

**Issue by mrmonteith** [espressif/esp-idf#1702]
When you download:
[https://dl.espressif.com/dl/esp32_win32_msys2_environment_and_toolchain-20180110.zip](url)
When you run the shell there is no MINGW32 ~esp 
directory.

**Comment by krzychb** [comment]
Hi @mrmonteith,
You are right, there is no such directory created. The idea was not to impose specific location for the ESP-IDF. An update will be added to documentation asking user to create a directory after downloading MSYS2.

**Comment by mrmonteith** [comment]
Yes. I created it manually.  Thanks
