### ISSUE TITLE
ulp.h: stage count register related ops missing

### ISSUE THREAD

**Issue by ThomasWaldmann** [espressif/esp-idf#1706]
could not find anything for it in ulp.h.

or any other docs that describe the instructions' layout on a bit level.

**Comment by igrr** [comment]
Please refer to the "ULP coprocessor" chapter of the ESP32 Technical Reference Manual, section "instruction formats", "operations with stage count register".

Also we don't plan to update ulp.h (the macros part, that is) anymore. This approach has been deprecated in favour of using the binutils to generate ULP coprocessor code.

**Comment by ThomasWaldmann** [comment]
Thanks for the hint, looks like it is SUB_OPCODE_ALU_CNT there.

Yeah, I know it is deprecated, was just searching for instruction layout specs.

Trying to implement a simple assembler in micropython.
https://github.com/ThomasWaldmann/py-esp32-ulp

**Comment by igrr** [comment]
Looks like a very useful project @ThomasWaldmann!
