### ISSUE TITLE
Does it‘s possible that esp32 work in ad-hoc mode?

### ISSUE THREAD

**Issue by noticeable** [espressif/esp-idf#1712]
Hello,
i'didn't found any mentions in the documentation or examples of ad-hoc wifi mode.is there any way of using it?

**Comment by negativekelvin** [comment]
https://github.com/espressif/esp-idf/issues/989

**Comment by noticeable** [comment]
may i ask when you will  release idf3.1?I'm looking forward to have try it in esp32!thx

**Comment by noticeable** [comment]
may i ask when will you release idf3.1?I'm looking forward to have try it in esp32!thx

**Comment by liuzfesp** [comment]
@noticeable  I'm afraid I also don't know the exact released time, it will be released when all features are delivered and all scheduled bugs are fixed.
