### ISSUE TITLE
[TW#19288] http2 client (using sh2lib/nghttp2)

### ISSUE THREAD

**Issue by gerardbos** [espressif/esp-idf#1717]
I'm working on an HTTP2 client on the ESP32 platform. As a basis, I use the sh2lib component from the examples folder (examples/protocols/http2_request/). 

This works fine when I use a golang HTTP(2) server: 

> D (7626) sh2lib: [frame-send] frame type SETTINGS
> D (7626) sh2lib: [frame-send] frame type HEADERS
> D (7626) sh2lib: [frame-send] C ----------------------------> S (HEADERS)
> D (7626) sh2lib: [frame-send] headers nv-len = 3
> D (7636) sh2lib: [frame-send] :method : GET
> D (7636) sh2lib: [frame-send] :scheme : https
> D (7646) sh2lib: [frame-send] :path : /kakulightbulb/desk
> D (7656) sh2lib: [frame-recv][sid: 0] frame type  SETTINGS
> D (7656) sh2lib: [frame-recv][sid: 0] frame type  other
> D (7676) sh2lib: [frame-send] frame type SETTINGS
> D (7696) sh2lib: [frame-recv][sid: 0] frame type  SETTINGS
> D (7716) sh2lib: [hdr-recv][sid:1] :status : 200
> D (7716) sh2lib: [hdr-recv][sid:1] content-type : application/json; charset=UTF-8
> D (7716) sh2lib: [hdr-recv][sid:1] content-length : 174
> D (7716) sh2lib: [hdr-recv][sid:1] date : Tue, 13 Mar 2018 14:51:48 GMT
> D (7726) sh2lib: [frame-recv][sid: 1] frame type  HEADERS
> D (7736) sh2lib: [data-chunk][sid:1]
> D (7736) sh2lib: [data-chunk] C <---------------------------- S (DATA chunk)174 bytes

When I do the same with data from an Apache server that  supports http2: 

> D (6296) sh2lib: [frame-send] frame type SETTINGS
> D (6296) sh2lib: [frame-send] frame type HEADERS
> D (6296) sh2lib: [frame-send] C ----------------------------> S (HEADERS)
> D (6296) sh2lib: [frame-send] headers nv-len = 3
> D (6306) sh2lib: [frame-send] :method : GET
> D (6306) sh2lib: [frame-send] :scheme : https
> D (6316) sh2lib: [frame-send] :path : /test.json
> D (6316) sh2lib: [frame-recv][sid: 0] frame type  SETTINGS
> D (6326) sh2lib: [frame-recv][sid: 0] frame type  other
> D (6346) sh2lib: [frame-send] frame type SETTINGS
> D (6426) sh2lib: [frame-recv][sid: 0] frame type  SETTINGS
> D (6426) sh2lib: [frame-recv][sid: 1] frame type  RST_STREAM
> D (6426) sh2lib: [stream-close][sid 1]

Which results in no data transferred to the ESP32. When I use other HTTP2 clients, I do not see the problem (for example using curl, which also uses nghttp2 as a HTTP2 library).

**Comment by kedars** [comment]
It seems the server expects the :authority field in the headers. Could you try by quickly adding the following entry in the `nva[]` array in the function sh2lib_do_get():

```
 SH2LIB_MAKE_NV(":authority", "your-hostname"),
```

I will raise an MR in IDF with the fix
