### ISSUE TITLE
Confusing docs for mdns_init (IDFGH-772)

### ISSUE THREAD

**Issue by ChristianRomberg** [espressif/esp-idf#1718]
Hi.
The function mdns_init has a confusing docstring. The function takes 0 parameters and still can throw an ESP_ERR_INVALID_ARG. I think the docstring needs an update.
https://github.com/espressif/esp-idf/blob/77eae33a7ec6c4d42552b07f3dc2f51d0ff4e49c/components/mdns/include/mdns.h#L83-L93

**Comment by negativekelvin** [comment]
Well IMO it should work that way so I vote for updating the code to match the docs but @me-no-dev knows that already

**Comment by david-cermak** [comment]
Hi @ChristianRomberg 

Thanks for raising this issue. 
Will update the docs.
