### ISSUE TITLE
[TW#19294] Peripheral server reconnection

### ISSUE THREAD

**Issue by doryashar** [espressif/esp-idf#1727]
Hi,
i'm writing a code for esp32 to act as a ble peripheral with the gatt secure server.
after a while, i want the esp32 to deep sleep and then initiate a reconnection to the client. -  the server already bond with the client and has its info in the table.
so how do i make the server prompt for a reconnection from the client?

Thanks

**Comment by Weijian-Espressif** [comment]
you should add reconnection in the client.
