### ISSUE TITLE
Softlock crash

### ISSUE THREAD

**Issue by jappies** [espressif/esp-idf#1728]
Seemingly random crash with interesting dump.
Has anyone seen this before?
https://pastebin.com/7N3w8vWJ

The only readable part:
![image](https://user-images.githubusercontent.com/14204210/37517978-99e71f3e-2913-11e8-9b64-81fa6b898a35.png)

**Comment by igrr** [comment]
@jappies Can you share some code which reproduces this issue, or at least describe the sequence of events which leads to this?

**Comment by FayeY** [comment]
Closing due to lack of response, please feel free to reopen if this is still an issue and you can supply more details. Thanks.
