### ISSUE TITLE
[TW#19298] i2s_adc_dac example i2s ADC read values inverted

### ISSUE THREAD

**Issue by javicordon** [espressif/esp-idf#1731]
I've been testing the current i2s_adc_dac example and I do get readings from ADC but they are inverted in value.

The only part I added to the code in order to get the the samples from ADC in decimal is marked in bold in the following function:

> /**
>  * @brief debug buffer data
>  */
> void example_disp_buf(uint8_t* buf, int length)
> {
> uint32_t adc_value = 0;
> #if EXAMPLE_I2S_BUF_DEBUG
>     printf("======\n");
>     for (int i = 0; i < length; i++) {
>         printf("%02x ", buf[i]);
>         if ((i + 1) % 8 == 0) {
>             printf("\n");
>         }
>     }
**>     printf("======\n");
>     for (int i = 0; i < length; i+=2) {
>             adc_value = ((((uint16_t) (buf[i + 1] & 0xf) << 8) | ((buf[i + 0]))));
>             printf("%u ", adc_value);
>             if ((i + 1) % 9 == 0) {
>                 printf("\n");
>             }
>         }**
>     printf("======\n");
> #endif
> }

So when I have 3.3V in ADC1_CHANNEL_0 I get the value: 0, and when I have 0V I get the value 4096.
Is this a bug or it was intended to be this way?
I supposed it had no attenuation set, so max input value should have been 1.1V. Instead, i2s ADC is able to read 0V up to 3.3V by default.
(I commented the task adc_read_task for testing purposes)

Thanks

**Comment by koobest** [comment]
Hi, @javicordon 
This is not a bug, we have invert the result of AD conversion.
See the source code https://github.com/espressif/esp-idf/blob/da2781631455b2c87c01704503f70443799a5187/components/driver/rtc_module.c#L1218

**Comment by koobest** [comment]
Hi, @javicordon Does your problem have been solved? If there is any questions, you can leave a message here. thanks !!
