### ISSUE TITLE
pcTaskGetName

### ISSUE THREAD

**Issue by Reiner1210** [espressif/esp-idf#1738]
It would be nice if pcTaskGetName is avlaible in the RTOS port.

**Comment by igrr** [comment]
Hi @Reiner1210, thanks for the pointer. Until this name change is done, you can use [pcTaskGetTaskName](http://esp-idf.readthedocs.io/en/latest/api-reference/system/freertos.html#_CPPv217pcTaskGetTaskName12TaskHandle_t).

**Comment by Reiner1210** [comment]
Ok,

but I get a note on compiling

/home/reiner/data/programm/esp/esp-idf/components/freertos/include/freertos/task.h:1323:7: 
note: declared here
  char *pcTaskGetTaskName( TaskHandle_t xTaskToQuery ) 
PRIVILEGED_FUNCTION; /*lint !e971 Unqualified char types are allowed for 
strings and s
