### ISSUE TITLE
esp_wifi_set_ps

### ISSUE THREAD

**Issue by Reiner1210** [espressif/esp-idf#1754]
I have a funny thing here

I use esp_wifi_get_ps(WIFI_PS_MODEM).
It works fine when the device is connected via a normal USB cable to the computer.
When I use a power only cable I does not work (go not to sleep). There is also a blue mini LED on the board blinking the whole time

Board is this one:
https://www.amazon.de/gp/product/B074RGW2VQ/ref=oh_aui_detailpage_o02_s00?ie=UTF8&psc=1

Any idea whats going on ?
I have already tried to disable log outputs no success.

**Comment by jack0c** [comment]
Any other difference?  Did you connect to an AP when you `use a power only cable`.

**Comment by Reiner1210** [comment]
Yes the same in both cases.

I assume that the UART - USB chip intrrrupts the esp because he can not 
establish connection

Am 21. März 2018 04:26:08 schrieb jack0c <notifications@github.com>:
Any other difference? Did you connect to an AP when you use a power only cable.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


Mit AquaMail Android
https://www.mobisystems.com/aqua-mail

**Comment by TimXia** [comment]
@Reiner1210 Did your device connect to computor or outlet with power only cable?

**Comment by Reiner1210** [comment]
I tried it with a power only cable on computer and 5V USB chrager. When I 
do the same with a full USB cabke it works fine. I assume that the open 
data wires from USB disturbe and it stucks in bootloader

Am 23. März 2018 04:05:19 schrieb TimXia <notifications@github.com>:
@Reiner1210 Did your device connect to computor or outlet with power only 
cable?
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


Mit AquaMail Android
https://www.mobisystems.com/aqua-mail
