### ISSUE TITLE
file read in flash very slow (IDFGH-196)

### ISSUE THREAD

**Issue by iampkuhz** [espressif/esp-idf#1756]
hi, I'm developing a prog in esp32. However, I found that the read speed is extremely slow (~200kb/s). the file is store in flash. BTW, when `fseek` in a file (~1.5MB), it's extremely slow (400-600ms).

I'm wondering it's the flash speed limitation or my wrong implement. Is this the normal speed?

**Comment by igrr** [comment]
Are you using FATFS or SPIFFS?

**Comment by iampkuhz** [comment]
SPIFFS

**Comment by igrr** [comment]
Sorry for the late update. Please see the explanation in https://github.com/espressif/esp-idf/issues/3277#issuecomment-480826052. You may try using FATFS to improve the speed, somewhat.
