### ISSUE TITLE
[TW#19692] BLE Advertising rate is incorrect (too fast)

### ISSUE THREAD

**Issue by mws-rmain** [espressif/esp-idf#1764]
From GATT_SERVER example:
In gatts_demo.c, line 104, min advertising interval is set to 0x20. This should set minimum advertising interval to 20ms (per BLE specification, 0.625ms x 32 = 20ms).

However, the screen capture below (from wireshark) shows advertising packets occuring at 2ms rate (first at t=29.168, next at t=29.170). The rate appears to be 10x too fast (?)

Each line reflects an advertising packet, on sequential channels (37,38,39,37,38,...), so even if the specification was interpreted as meaning minimum interval for a packet on the same channel, the capture shows the first packet at t=29.168, and the next packet on this channel (3 lines down) at t=29.174 (6ms later).

[](<a href="http://tinypic.com?ref=2z59i14" target="_blank"><img src="http://i67.tinypic.com/2z59i14.jpg" border="0" alt="Image and video hosting by TinyPic"></a>)

**Comment by Weijian-Espressif** [comment]
I set adv params with
 static esp_ble_adv_params_t adv_params = {
    .adv_int_min         = 0x20,
    .adv_int_max         = 0x20,
    .adv_type            = ADV_TYPE_IND,
    .own_addr_type       = BLE_ADDR_TYPE_PUBLIC,
    .channel_map         = ADV_CHNL_ALL,
    .adv_filter_policy   = ADV_FILTER_ALLOW_SCAN_ANY_CON_ANY,
};

this is the result:
捕获.PNG
