### ISSUE TITLE
ESP-IDF 3.1 release date

### ISSUE THREAD

**Issue by jemdiggity** [espressif/esp-idf#1769]
The lack of low power mode for BLE is a major blocker for my company.

Is low power BLE supported in ESP-IDF 3.1?
Can we get an estimated release date?

#1242 
#947

Thanks!

**Comment by vonnieda** [comment]
Very important for me as well. Forum threads and issues have gone unanswered on this for many weeks now, where previously it was stated that this would be available near end of February. Can we please get an update?

**Comment by jemdiggity** [comment]
I contacted Espressif via email and they said April/May timeframe
