### ISSUE TITLE
[TW#19851] make menuconfig: CONFIG_LWIP_MAX_SOCKETS - 16 or 32?

### ISSUE THREAD

**Issue by nkolban** [espressif/esp-idf#1781]
Probably a small typo ... but was looking at the help for CONFIG_LWIP_MAX_SOCKETS and came across:

![image](https://user-images.githubusercontent.com/3421732/37977782-1c4c584c-31aa-11e8-85e8-f7198e1b62fe.png)

I think we can only have 16 sockets but the range property would indicate we can have 32?

**Comment by TimXia** [comment]
@nkolban Sorry, it's a mistake. We will fix it ASAP.
