### ISSUE TITLE
Error (-28) (IDFGH-203)

### ISSUE THREAD

**Issue by kmakhil90** [espressif/esp-idf#1786]
Hi, 
I am trying to connect the esp32 to aws core. I have genearted and activated all the certificates in aws console which mentioned in the procedure. But still it is not connecting with mqtt and giving error -28.
Please suggest a workaround for this.

Akhil.

**Comment by negativekelvin** [comment]
https://forums.aws.amazon.com/thread.jspa?messageID=753782&tstart=0

**Comment by kmakhil90** [comment]
Hi,

Thanks.
I tried the change in timeout value as well as my policy contains all publish,receive,subscribe and connect permission as explained in above thread. 
then what else would be the problem here?

Akhil.

**Comment by kmakhil90** [comment]
Hi:

Means i need to give the policy name start with iot*?

**Comment by makefitter** [comment]
iot* means all permissions connect, publish, subscribe, delete. It's an option not a name.

**Comment by kmakhil90** [comment]
i added this one too (iot*) also into my policy and connected in certificates but still error it is same

**Comment by mahavirj** [comment]
@kmakhil90 Is this issue still exists? If not can this be closed?
