### ISSUE TITLE
System Crash

### ISSUE THREAD

**Issue by hvishu** [espressif/esp-idf#1787]
Hi, When I keep my system running for long time, I get below crash.

I was wondering if there any tool like addr2line or others to get the call trace that caused this crash.

Guru Meditation Error: Core  1 panic'ed (IllegalInstruction)
. Exception was unhandled.
Register dump:
PC      : 0x400e8c14  PS      : 0x00060330  A0      : 0x800e8fa0  A1      : 0x3fff0130  
A2      : 0x3fff8f78  A3      : 0x3ffc64b8  A4      : 0x00000001  A5      : 0x00000001  
A6      : 0x00000001  A7      : 0x0455792c  A8      : 0x045707ac  A9      : 0x3fff0110  
A10     : 0x045577ac  A11     : 0x00000000  A12     : 0x00000000  A13     : 0x00000000  
A14     : 0x00007328  A15     : 0x00000005  SAR     : 0x0000000f  EXCCAUSE: 0x00000000  
EXCVADDR: 0x00000000  LBEG    : 0x4000c2e0  LEND    : 0x4000c2f6  LCOUNT  : 0xffffffff  

Backtrace: 0x400e8c14:0x3fff0130 0x400e8f9d:0x3fff0160

Boot-up prints

rst:0x7 (TG0WDT_SYS_RESET),boot:0x17 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:5708
load:0x40078000,len:0
load:0x40078000,len:13804
entry 0x40079030
I (69) boot: Detected ESP32
W (32) boot: PRO CPU has been reset by WDT.
W (32) boot: WDT reset info: PRO CPU PC=0xc06fa51b
W (32) boot: WDT reset info: APP CPU PC=0x60e54f4a
I (38) boot: ESP-IDF v3.0-dev-1392-g579201bc-dirty 2nd stage bootloader
I (45) boot: compile time 19:02:27
I (50) boot: Enabling RNG early entropy source...
I (55) boot: SPI Speed      : 40MHz
I (59) boot: SPI Mode       : DIO
I (63) boot: SPI Flash Size : 4MB
I (67) boot: Partition Table:
I (71) boot: ## Label            Usage          Type ST Offset   Length
I (78) boot:  0 nvs              WiFi data        01 02 00009000 00006000
I (85) boot:  1 phy_init         RF data          01 01 0000f000 00001000
I (93) boot:  2 filt_cong        unknown          41 00 00010000 00001000
I (100) boot:  3 aws_cert         unknown          40 00 00011000 00002000
I (108) boot:  4 factory          factory app      00 00 00020000 00140000
I (116) boot: End of partition table
I (120) esp_image: segment 0: paddr=0x00020020 vaddr=0x3f400020 size=0x481a8 (295336) map
I (231) esp_image: segment 1: paddr=0x000681d0 vaddr=0x3ffc0000 size=0x047f4 ( 18420) load
I (239) esp_image: segment 2: paddr=0x0006c9cc vaddr=0x40080000 size=0x00400 (  1024) load
I (240) esp_image: segment 3: paddr=0x0006cdd4 vaddr=0x40080400 size=0x0323c ( 12860) load
I (252) esp_image: segment 4: paddr=0x00070018 vaddr=0x400d0018 size=0xd6c0c (879628) map
I (561) esp_image: segment 5: paddr=0x00146c2c vaddr=0x4008363c size=0x12998 ( 76184) load
I (593) esp_image: segment 6: paddr=0x001595cc vaddr=0x400c0000 size=0x00064 (   100) load
I (593) esp_image: segment 7: paddr=0x00159638 vaddr=0x50000000 size=0x00008 (     8) load
I (613) boot: Loaded app from partition at offset 0x20000
I (613) boot: Disabling RNG early entropy source...
I (614) cpu_start: Pro cpu up.
I (617) cpu_start: Starting app cpu, entry point is 0x400810f8
I (0) cpu_start: App cpu up.
I (628) heap_init: Initializing. RAM available for dynamic allocation:
I (634) heap_init: At 3FFAFF10 len 000000F0 (0 KiB): DRAM
I (640) heap_init: At 3FFD4FA8 len 0000B058 (44 KiB): DRAM
I (647) heap_init: At 3FFE0440 len 00003BC0 (14 KiB): D/IRAM
I (653) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
I (659) heap_init: At 40095FD4 len 0000A02C (40 KiB): IRAM
I (666) cpu_start: Pro cpu start user code
I (12) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.

**Comment by mahavirj** [comment]
@hvishu Please refer [here](http://esp-idf.readthedocs.io/en/latest/get-started/idf-monitor.html?highlight=backtrace#automatically-decoding-addresses)
