### ISSUE TITLE
SD card / FAT - file not visible on computer

### ISSUE THREAD

**Issue by Reiner1210** [espressif/esp-idf#1794]
Hello,

I have connected a SD card via SPI. I used the example code.
Card is detected an write and stat work.

BUT when I connect the SD card on my computer I do not see the file the ESP32 has created.
The SD card was formatted under Linux with mkfs.vfat /dev/sdf1. Partition type is 0xc.

Any ideas what is going on ..... ?

**Comment by Reiner1210** [comment]
An other interesting fact: open / write does not work - only fopen / fwrite.
I assume that open /write will be in conflict with lwip which defines open / write & Co.

**Comment by igrr** [comment]
Could you please post the non-working code with open/write? Conflicts with LwIP have been resolved a few months ago, so that shouldn't be a problem. Suggest checking the return values of these functions and `errno` variable.

**Comment by Reiner1210** [comment]
It's tricky. No errors, but now file on the SDCard. I can remake an example.

Am 31. März 2018 04:01:21 schrieb Ivan Grokhotkov <notifications@github.com>:
Could you please post the non-working code with open/write? Conflicts with 
LwIP have been resolved a few months ago, so that shouldn't be a problem. 
Suggest checking the return values of these functions and errno variable.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


Mit AquaMail Android
https://www.mobisystems.com/aqua-mail

**Comment by Reiner1210** [comment]
I tried it again - and it works !
I think I tried it on a FAT32 created by Linux - neither fopen nor open was able to create a file in this case (no error codes but no file on card).  Now I tried this again - and it works. So I will close this issue because I can not reproduce it
