### ISSUE TITLE
25 warnings for the Getting Started project

### ISSUE THREAD

**Issue by krzychb** [espressif/esp-idf#18]
Running `make` on [Toolchain for Windows](https://github.com/espressif/esp-idf/blob/master/docs/windows-setup.rst#step-1-toolchain-for-windows-quick-steps) for the bare [Getting Started project](https://github.com/espressif/esp-idf/blob/master/docs/windows-setup.rst#step-3-starting-a-project) completes successfully and shows 25 warnings. Below is the list taken from Eclipse for easier reading:

![image](https://cloud.githubusercontent.com/assets/12953787/18670421/230dd9c6-7f40-11e6-8b48-825662540c32.png)

Do you see the same?

**Comment by igrr** [comment]
Yes, we also see this. Will clean up.

**Comment by igrr** [comment]
Fixed in master, compiling the template app shouldn't produce any warnings now.

**Comment by dsptech** [comment]
I mistyped the issue number, so, I erroneusly regferenced this issue. Sorry.
dsptech
