### ISSUE TITLE
read ADC2 will trigger other GPIO Pin's interrupt

### ISSUE THREAD

**Issue by adherent88** [espressif/esp-idf#1806]
Hi all, 

I encountered a very weird issue.

I am using esp wrover as development kit. 

I registered ISR for 4 GPIO pins to respond to falling and rising edge, simplified code as following:
`
    //install gpio isr service
    gpio_install_isr_service(ESP_INTR_FLAG_DEFAULT);

    //hook isr handler for specific gpio pin
    gpio_isr_handler_add(34, gpio_isr_handler, (void*) 34);
    gpio_isr_handler_add(35, gpio_isr_handler, (void*) 35);
    gpio_isr_handler_add(36, gpio_isr_handler, (void*) 36);
    gpio_isr_handler_add(39, gpio_isr_handler, (void*) 39);
`

And I observed that as soon as I try to read one ADC channel, ISR gpio_isr_handler is triggered, whatever GPIO pin it is. e.g.:
`
    int temp;
    adc2_get_raw( ADC2_CHANNEL_2, ADC_WIDTH_12Bit, &temp);
`

Here ADC2_CHANNEL_2 is GPIO2, I tried also with other channels, e.g. channel7(GPIO27), channel8(GPIO25), the behavior is the same.

Only GPIO36 and GPIO39 have the weird behavior, 34, 35 seem ok. And the level of GPIO36 and 39 remain high, no level change at all, but still the ISR is triggered.

Any idea or hint will be highly appreciated!

**Comment by krzychb** [comment]
> Any idea or hint will be highly appreciated!

Please see https://github.com/espressif/esp-idf/issues/1096 and [Silicon Errata (PDF)](https://www.espressif.com/sites/default/files/documentation/eco_and_workarounds_for_bugs_in_esp32_en.pdf)

**Comment by adherent88** [comment]
Thanks!
