### ISSUE TITLE
Query on aws example

### ISSUE THREAD

**Issue by hvishu** [espressif/esp-idf#1810]
From the examples/aws_iot/thing_shadow/main/thing_shadow_sample.c

in aws_iot_task(), I see below line
    while(NETWORK_ATTEMPTING_RECONNECT == rc || NETWORK_RECONNECTED == rc || SUCCESS == rc) {
...
...
}
Seems if the error returned is "NETWORK_ATTEMPTING_RECONNECT" or "NETWORK_RECONNECTED", attempt will be made to connect and be in while loop.  

The list of errors in IoT_Error_t, is quite a few.  Are there any of these errors possible?  If so, what is the sequence to recover from tem?

**Comment by mahavirj** [comment]
@hvishu This looks to be more relevant to AWS IoT SDK, could you please ask [here](https://github.com/aws/aws-iot-device-sdk-embedded-C)

**Comment by hvishu** [comment]
Raised this query in AWS IoT SDK, closing this issue here...
