### ISSUE TITLE
rtc_clk_cpu_freq_set(RTC_CPU_FREQ_XTAL) breaks uart

### ISSUE THREAD

**Issue by maierkomor** [espressif/esp-idf#1823]
Switching CPU frequency with rtc_clk_cpu_freq_set works well for 80, 160, 240 MHz, but breaks UART communication on serial monitor when using RTC_CPU_FREQ_XTAL. Device seems to continue to run, but output on serial console seems to switch to a different baudrate.

**Comment by negativekelvin** [comment]
The apb frequency will drop to 40mhz so you have to call uart_set_baudrate again or configure uart to use ref_tick.

**Comment by Reiner1210** [comment]
What exactly is the  xtal freq ?
