### ISSUE TITLE
gpio_intr_enable can cause an invalid call to the ISR

### ISSUE THREAD

**Issue by Si03** [espressif/esp-idf#1825]
If the event happens while the interrupt is disabled then the ISR is called upon enabling the interrupt again.

I'm doing a gpio falling edge interrupt
Output pin linked to interrupt input pin with pull up.
- call gpio_intr_disable
- toggle the output gpio down/up
- call gpio_intr_enable
ISR fires and is logged in the handling task after 10 logging ticks (via xSemaphore).

Is this an issue or is it me doing something wrong? I can supply example code if this is a new issue.
Many thanks.

**Comment by koobest** [comment]
Hi, @Si03  You can try it as below：
```
gpio_config_t io_conf = {
    ...
   .intr_type = 0;
   ...
};
gpio_config(&io_conf);
gpio_install_isr_service(ESP_INTR_FLAG_DEFAULT);
```
call  `interrupt gpio_set_intr_type(your_gpio, your_trigger_mode); ` when you need to open the interrupt. Hope it can helps you.
