### ISSUE TITLE
Define tow RTC IO as a wakeup GPIO .

### ISSUE THREAD

**Issue by javiisanchez** [espressif/esp-idf#1833]
Hi all,  I have one  question:

When I am trying to define two pins to wake up the ESP32, exactly the GPIO 37 and 39. I see that the ESP32 only wake up when tha GPIO39 is HIGH, and when I change the order the ESP wake up when the GPIO37 is HIGH. I am using arduino IDE.

Do you know how I can define the two pins from software?

My part of code:

```
esp_sleep_enable_ext0_wakeup(GPIO_NUM_37,1); 
esp_sleep_enable_ext0_wakeup(GPIO_NUM_39,1);
```

**Comment by negativekelvin** [comment]
You have to use ext1_wakeup

**Comment by koobest** [comment]
The ext1 wakes-up  mode  wakes the chip up using multiple GPIO combinations， when configured GPIOs are both high or low, the chip will be woken up.
