### ISSUE TITLE
[TW#20027] Bluetooth Controller: Crash on invalid LE Connection Parameters

### ISSUE THREAD

**Issue by mringwal** [espressif/esp-idf#1834]
When responding to an LE Remote Connection Parameter Update Request with an LE Remote Connection Paramater Request Reply, with conn min = conn max = 0, the Bluetooth Controller crashes.

Of course, the connection interval parameter are invalid, but it would be better if the controller would respond with a HCI Command Complete - INVALID_HCI_COMMAND_PARAMETERS instead of crashing. Given that the parameters are not validated, I guess related commands might cause similar behaviour.

Log snippet
--
...
Incoming Connection
[00:00:01.617] EVT <= 3E 13 01 00 00 00 01 00 D2 1B 6D 34 FE 18 18 00 04 00 48 00 01
[00:00:01.618] LOG -- hci.c.2280: LE Connection_complete (status=0) type 0, 18:FE:34:6D:1B:D2
..
LE Remote Connection Parameter Update Request
[00:00:03.276] EVT <= 3E 0B 06 00 00 0C 00 0C 00 04 00 64 00

LE Remote Connection Paramater Request Reply, with conn min = conn max = 0
[00:00:03.277] CMD => 20 20 0E 00 00 00 00 00 00 04 00 64 00 00 00 FF FF

Guru Meditation Error: Core  0 panic'ed (IntegerDivideByZero)
. Exception was unhandled.
Core 0 register dump:
PC      : 0x4004ba16  PS      : 0x00060730  A0      : 0x80049e7c  A1      : 0x3ffd0a80
A2      : 0x00000000  A3      : 0x00000000  A4      : 0x000011c0  A5      : 0x00000030
A6      : 0x00000078  A7      : 0x00000000  A8      : 0x00000003  A9      : 0x00000000
A10     : 0x3ffc0a88  A11     : 0x00060323  A12     : 0x00060320  A13     : 0x00000000
A14     : 0x00000001  A15     : 0x00000000  SAR     : 0x0000001d  EXCCAUSE: 0x00000006
EXCVADDR: 0x00000000  LBEG    : 0x4000c46c  LEND    : 0x4000c477  LCOUNT  : 0xffffffff

Backtrace: 0x4004ba16:0x3ffd0a80 0x40049e79:0x3ffd0aa0 0x40041b7b:0x3ffd0af0 0x40042386:0x3ffd0b20 0x4001a637:0x3ffd0b40 0x40019d11:0x3ffd0b70 0x40055b4d:0x3ffd0b90 0x400ea55b:0x3ffd0bb0 0x400ea5ab:0x3ffd0bd0
0x400ea55b: r_rw_schedule at ??:?

0x400ea5ab: btdm_controller_task at ??:?

================= CORE DUMP START =================
9BUAAAYAAAB0AQAA
bAz9P8AJ/T9kDP0/
8An9PwAM/T+jfy4oYDP8P2Az/D9sDP0/WDP8PwIAAAA0/Pw/NPz8P2wM/T8AAAAA
FwAAAGj8/D9idENvbnRyb2xsZXIAEvcAAAAAAGQM/T8AAAAAIAcGABcAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADSq/D+cqvw/BKv8PwAAAAAAAAAA
AQAAAAAAAABMKEA/AAAAAEgdAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKZiM
DQAAABa6BEAwBwYAfJ4EgIAK/T8AAAAAAAAAAMARAAAwAAAAeAAAAAAAAAADAAAA
AAAAAIgK/D8jAwYAIAMGAAAAAAABAAAAAAAAAB0AAAAGAAAAAAAAAGzEAEB3xABA
/////yADBgAAAAAA0B0IQKhF/D8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAKhF/D8AAAAAAAAAAAAAAAB+GwSAoAr9PwAAAABU2fs/
AAAAAAAAAAAAAAAAAAAAAIkjBIDwCv0/DOf6P+y3+z8AAAAAAwAAAAMAAD98JgE/
IB4IQHC0CEAAAAYAAwAAAAAAAAABAAAAAAAAAA4AAACst/s/DOf6P8yT+z8AAAAA
OqYBgCAL/T8AAAAA7Lf7PyAgAAAAAAAAAwAAACMGBgAGAAAAAJ4EQIDY+z+st/s/
FJ0BgEAL/T/gt/s/YIP7PwYAAAAgIAAAZAAAAAEAAABQWwWAcAv9P5SkAUCkgfs/
UFsFgHAL/T+EdQFApIH7PwUIAABo/fo/8Ir5PwAAAABepQ6AkAv9PwEAAAAAAAAA
HwAAAAAAAAAAAAAAsAX8P66lDoCwC/0/AQAAANAL/T9U/Pw/AAAAAFz8/D+wBfw/
AAAAANAL/T9YJvw/fCb8P/////9sDP0/AQAAAAAAAAAAAAAAAAz9PwAAAAAAAAAA
AQAAAAAAAAAAAAAAAAAAAAAAAAB4Jvw/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAMDP0/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAA==
5Nj8P5DU/D/c2Pw/
kNT8P3DY/D/UlUEAqDH8P6gx/D/k2Pw/oDH8PxgAAABPOvIAHKLAz+TY/D8AAAAA
AQAAAODG/D9tYWluAIhR1U2lvQxKZdkAAAAAANzY/D8AAAAAIwYGAAEAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADSq/D+cqvw/BKv8PwAAAAAAAAAA
AQAAAAAAAABMKEA/AAAAAEgdAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA38Lw
IB4IQKk4CEAwCQYAtXEIgFDV/D8AAAAABwAAADAO/T8AAAAAAAAAAAEAAACpOAiA
MNX8P4AAAAAAAAAAAAAAAAAAAAACAAAAAAAA/xkAAACnjAWAENX8P+DCAED2wgBA
AAAAABkgCEAAAAAATLYIQBgS/D8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAJyq/D8AAAAAAgAAAAAAAP/CEA+AcNX8P0Ar/D9e7fw/
nKr8P0DS/D9A0vw/AQAAACOhDoCQ1fw/AAAAAAIAAAASAAAAUiv8P///AABkAAAA
+BkOgLDV/D9M7fw/EgAAAPAv/D8AAAAATO38PwEAAAB3OQ6A0NX8PwEAAABN7fw/
Te38PxEAAAACAAAAcNf8Pww6DoDw1fw/Te38PxEAAAARAAAAEQAAAAEAAAAAAAD/
MDoOgCDW/D9N7fw/gNb8P4DW/D9g1vw/KAAAAIDW/D/oGQ5AMgAAAF3t/D8BAAAA
CEkOgFDW/D8oXkA/AAAAAIDW/D9g1vw/BAAAAAAAAABg1vw/BAAAACheQD8EAAAA
QlsOgKDW/D+UDv0///8AAIDW/D9g1vw/BAAAAAAAAAABAAAAAAAAAAAAAAAAAAAA
BAAAAGQAAAAAAAAADQAAAAAAAAAAAAAABAAAAGQAAABxXg6AENf8P303/D8+AAAA
AAAAAP//AAB9N/w/DQAAAP////8ZIAhABAAAAEy2CEAAAAAAbPT8PwAAAAAMAAAA
cV4OgBDX/D99N/w/DQAAAAEAAABIm/w/rJz8PwAAAAACAAAABAAAAGQAAAANAAAA
RxsOgHDX/D8EAAAAfTf8Pw0AAAADAAAAFAEAAIS3+z9cXg6AUNcGAIAMAAD0AQoA
gAz8Pw0AAAADAAAAIwAGAGQAAABw1/w/BAAAAH03/D8E7fw/AgAAAAwAAAAMAAAA
mBsOgJDX/D9IXg5AeDf8Pw0AAAAAAAAAAAAAAAAAAACsag6AwNf8P2g3/D8BAAAA
DgAAAA4A/D/kCPw//////3w3/D+AAAAAAQAAAAAAAAAEZw6A4Nf8PwAAAACcqvw/
AAAAAP////8AAAAAAAAAAMscDoAQ2Pw/CgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
cJX8P7j0/D8MAAAAewAAAF0WDYAw2Pw/sBkOQAAAAACADAAAnJX8PzTr/D8jAAYA
AAAAAFDY/D8AAAAAAAAAAAAAAADk2Pw/AQAAAAAAAAAAAAAAcNj8PwAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHzY/D8AAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
PN/8P9Dd/D803/w/
0N38P9De/D/EXWKclDH8P5Qx/D883/w/jDH8PxkAAABZX08qbN7pUjzf/D8AAAAA
AAAAADjb/D9JRExFAAmyf7mcRU8c9uQAAAAAADTf/D8AAAAAIwIGAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADSq/D+cqvw/BKv8PwAAAAAAAAAA
AQAAAAAAAABMKEA/AAAAAEgdAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/cGB
IB4IQB4nDUAwDwYACKEIgJDe/D8IAAAAAAAAAAEAAAA83/w/AQAAAAAAAADQMPw/
tDD8PwAAAAAjAAYAIwAGAIDW/D8BAAAAAAAAAAAAAACQ3vw/AAAAAAAAAAAAAAAA
AAAAABkgCECA1vw/TLYIQHgY/D8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAsN78PwAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAADQ3vw/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA3N78PwAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAA=
sOn8PyDo/D+o6fw/
IOj8P0Dp/D8AAAAAbDH8P2wx/D+w6fw/ZDH8PxgAAADg4Pw/4OD8P7Dp/D/Y4Pw/
AQAAAKzh/D9UbXIgU3ZjAKKg73L09UMAAAAAAKjp/D8AAAAAIQAGAAEAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADSq/D+cqvw/BKv8PwAAAAAAAAAA
AQAAAAAAAABMKEA/AAAAAEgdAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMFrd
IB4IQOK7CEAwCQYA17wIgODo/D+UM/w/AAAAAAEAAADk2Pw/AQAAAAAAAADiuwiA
wOj8PwAAAAAAMfw/AOH8PwAAAAAAAAAAAwAAAAAAAAClpaWlpaWlpQAAAAAAAAAA
AAAAABkgCEAAAAAATLYIQOgi/D8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEOn8PwAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAOgi/D8AAAAAAAAAAAAAAAAAAAAAQOn8PwAAAAAAAAAA
AQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAABM6fw/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAA=
NL78P6C8/D8svvw/
oLz8P8C9/D9y3R/DJDH8P3DF/D80vvw/HDH8PwMAAAAErPw/BKz8PzS+/D/8q/w/
FgAAADCs/D9lc3BfdGltZXIAEpEe73sAAAAAACy+/D8AAAAAIQAGABYAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADSq/D+cqvw/BKv8PwAAAAAAAAAA
AQAAAAAAAABMKEA/AAAAAEgdAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA1bxy
IB4IQHC0CEAwAAYAKx0NgGC9/D/Yq/w/AAAAACSs/D8AAAAAAQAAAAAAAABwtAiA
QL38PwAAAACAM/w/gDP8P0DE/D/ECPw/AQAAAAAAAAClpaWlpaWlpQAAAAAAAAAA
AAAAABkgCEBAxPw/TLYIQGj3+z8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAoL38PwAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAP////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAMC9/D8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAADMvfw/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAA
aMX8P+DD/D9gxfw/
4MP8PwDF/D9H6ftdPL78PyQx/D9oxfw/HDH8PwEAAAA4wfw/OMH8P2jF/D8wwfw/
GAAAAGTB/D9pcGMwANMXxawRcytCKkAAAAAAAGDF/D8AAAAAIQAGABgAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADSq/D+cqvw/BKv8PwAAAAAAAAAA
AQAAAAAAAABMKEA/AAAAAEgdAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAzB1/
IB4IQHC0CEAwAAYAJxYIgKDE/D8Mwfw/AAAAAFjB/D8AAAAAAQAAAAAAAABwtAiA
gMT8PwAAAACAM/w/gDP8P/A6/j/kCPw/AgAAAAAAAAClpaWlpaWlpQAAAAAAAAAA
AAAAABkgCEDwOv4/TLYIQKj++z8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4MT8PwAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAP////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAADF/D8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBDgiAoDv+Pwgx/D/MM/w/
AAAAAAAAAAAMxfw/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
================= CORE DUMP END =================
CPU halted.

**Comment by Weijian-Espressif** [comment]
sorry, I will fix it as soon as possable.

**Comment by mringwal** [comment]
No problem - BTstack isn't sending invalid conn intervals usually. Please check if there are other ways to run into this crash (e.g. in a le create connection command or similar)

**Comment by FayeY** [comment]
It has been merged into the latest master, please have a try. Thanks.
