### ISSUE TITLE
Is there a way to toggle an I/O on wifi transmit? (IDFGH-215)

### ISSUE THREAD

**Issue by S-March** [espressif/esp-idf#1844]
I have a product that I am developing that has very tight battery requirements, it also requires an amplifier on the TX side of a WiFi transmit. I would ideally like to keep the amplifier off during the RX side. 

Is there a way to expose an I/O to toggle on/off during transmit so I can enable my amplifier?

**Comment by negativekelvin** [comment]
It should be possible using an antenna select gpio signal but I don't know if it is supported.

**Comment by negativekelvin** [comment]
@liuzfesp he means external PA

**Comment by S-March** [comment]
Exactly. Looking for a way to expose an IO to toggle an external PA on TX only.

**Comment by liuzfesp** [comment]
@S-March, ESP32's GPIO_matrix can mux out the function to 1~4 IOs to control external PA and RF switch, the API hasn't been ready yet.

**Comment by negativekelvin** [comment]
https://github.com/espressif/esp-idf/commit/04c74efedd62ef50beddca7e1050beba9d21f419
