### ISSUE TITLE
[TW#20519] Is the documentation on xRingbufferAddToQueueSetRead and friends inverted?

### ISSUE THREAD

**Issue by cranphin** [espressif/esp-idf#1846]
See: https://github.com/espressif/esp-idf/blob/bae9709a7950e2ee08e14c65be27831bcb547105/components/freertos/include/freertos/ringbuf.h#L304

It says for xRingbufferRemoveFromQueueSetRead: This specifically removes the semaphore that indicates more space has become available in the ringbuffer.
Isn't that the wrong way round? It's the semaphore that indicates something has been written to the ringbuffer (which we can now read).

Same for all 4 methods there.

**Comment by Dazza0** [comment]
Ringbuffers will be reworked as part of the upcoming release 3.1
