### ISSUE TITLE
How to disable wifi's rx function,only enable tx function

### ISSUE THREAD

**Issue by jixunx** [espressif/esp-idf#1849]
I am using esp_wifi_80211_tx to send packets.Packets type is data without ack.So I don't want the wifi's rx funtion.How to disable wifi's rx function.

**Comment by liuzfesp** [comment]
目前 esp_wifi_80211_tx 做不到这点， 因为 WiFi 每发出一个包之后会依据是否收到对方的 802.11 Ack 而决定是否重传， 这也是协议标准的要求。 依据目前的 release 计划， idf v3.0 版本中应该不会实现你说的这个功能。

**Comment by jixunx** [comment]
谢谢你的回复！
