### ISSUE TITLE
[TW#20523] removing "phy: phy_version: 383.0, 79a622c, Jan 30 2018, 15:38:06, 0, 0" debug (IDFGH-2043)

### ISSUE THREAD

**Issue by davctv** [espressif/esp-idf#1855]
Hi,
I'm not able to remove the 

`phy: phy_version: 383.0, 79a622c, Jan 30 2018, 15:38:06, 0, 0`

information debug. It seems in libphy.a library. This debug is always printed even if all the logs are disabled at very startup of app_main() using function

`esp_log_level_set("*", ESP_LOG_NONE);`

Can you please remove it?

Thanks.

**Comment by davctv** [comment]
Hi @FayeY,

Is there any update regarding this issue?

Thanks

**Comment by TimXia** [comment]
@davctv You can substitute function `in phy_printf(const char* format, ...)` with an empty function in components/esp32/lib_printf.c to solve your problem.

**Comment by davctv** [comment]
@TimXia Thank you. I will do a test and let you know.

**Comment by davctv** [comment]
@TimXia your suggestion worked. I close the issue. Thanks

**Comment by gunarkroeger** [comment]
This should not be closed i think, and should be a Bug. Reproduced with esp-idf-v3.3

**Comment by Alvin1Zhang** [comment]
We have a fix under internal reviewing and the issue will close automatically once the fix is available on GitHub, thanks.
