### ISSUE TITLE
spi_bus_add_device SPI_CECK 

### ISSUE THREAD

**Issue by tcmichals** [espressif/esp-idf#1866]
There is an error with:

SPI_CHECK(dev_config->spics_io_num < 0 || GPIO_IS_VALID_OUTPUT_GPIO(dev_config->spics_io_num), "spics pin invalid", ESP_ERR_INVALID_ARG);

It should be:
SPI_CHECK(dev_config->spics_io_num > 0 && GPIO_IS_VALID_OUTPUT_GPIO(dev_config->spics_io_num), "spics pin invalid", ESP_ERR_INVALID_ARG);

The issue is dev_config->spics_io_num < 0 if the pin is defined and it does not check the validity of the pin.

**Comment by negativekelvin** [comment]
The intent is that either the value is either -1 or a valid gpio output number

**Comment by ginkgm** [comment]
agree with @negativekelvin , -1 is also a valid value, SPI will work without CS output in this case.

**Comment by tcmichals** [comment]
The issue is, IO35, it is only an input, so, the dev_config->spics_io_num < 0  passes and  GPIO_IS_VALID_OUTPUT_GPIO(dev_config->spics_io_num) does not. 

If the user does not have a logic analyzer or some way to look at the CS, then how is to know something is wrong?

**Comment by negativekelvin** [comment]
35 is less than zero?

**Comment by FayeY** [comment]
Closing this, please feel free to reopen it if your problem is still unsolved. Thanks.
