### ISSUE TITLE
[TW#20536] warning: undefined variable `MD5_OPT'

### ISSUE THREAD

**Issue by slcasner** [espressif/esp-idf#1867]
If CONFIG_PARTITION_TABLE_MD5=y then on every boot the following warning appears:

.../esp-idf/components/partition_table/Makefile.projbuild:16: warning: undefined variable `MD5_OPT'

This file needs to define MD5_OPT as empty in this case.

**Comment by projectgus** [comment]
Thanks @slcasner ! I happened to make an unrelated change that provided an opportunity to fix this.

(This change also happened to break make 3.81 support, a fix for that is coming shortly!)
