### ISSUE TITLE
[TW#20538] uart_write_bytes_with_break() - 'brk_len' parameter

### ISSUE THREAD

**Issue by loboris** [espressif/esp-idf#1871]
While testing the function, I've found that the **unit** of `brk_len` parameter is actually a **bit** length.

>  * @param brk_len break signal length (unit: the time it takes to send a complete byte
>                   including start, stop and parity bits at current_baudrate)
> 
should be corrected. Also the parameter description should mention that the maximum `brk_len` value is 255.

```
/**
 * @brief Send data to the UART port from a given buffer and length.
 *
 * If the UART driver's parameter 'tx_buffer_size' is set to zero:
 * This function will not return until all the data and the break signal have been sent out.
 * After all data is sent out, send a break signal.
 *
 * Otherwise, if the 'tx_buffer_size' > 0, this function will return after copying all the data to tx ring buffer,
 * UART ISR will then move data from the ring buffer to TX FIFO gradually.
 * After all data sent out, send a break signal.
 *
 * @param uart_num UART_NUM_0, UART_NUM_1 or UART_NUM_2
 * @param src   data buffer address
 * @param size  data length to send
 * @param brk_len break signal length (unit: the time it takes to send a complete byte
                  including start, stop and parity bits at current_baudrate)
 *
 * @return
 *     - (-1) Parameter error
 *     - OTHERS (>=0) The number of bytes pushed to the TX FIFO
 */
int uart_write_bytes_with_break(uart_port_t uart_num, const char* src, size_t size, int brk_len brk_len);
```
Testing with logic analyzer proves that it is actually the bit length:

Sending `0x5A` character with no break (using `uart_write_bytes()` :
![uart_5a_nobreak](https://user-images.githubusercontent.com/6280349/38925591-60d22dfe-4300-11e8-9050-983e4aa579ec.png)

Sending `0x5A` character with 1 break (`brk_len = 1`):
As the **break length is 1 bit** it is actually accepted as **start** signal.
![uart_5a_1_break](https://user-images.githubusercontent.com/6280349/38925744-ca27e140-4300-11e8-9127-fd247e1f5c94.png)

Sending `0x5A` character with 10 breaks (`brk_len = 10`, minimal value to be recognized as **break**):
![uart_5a_10_break](https://user-images.githubusercontent.com/6280349/38925770-dcc076d2-4300-11e8-8805-aac4b59d89a4.png)

**Comment by costaud** [comment]
Working on this, once confirmed, we will update the documentation.
