### ISSUE TITLE
[TW#20539] Is it possible to disable the Wi-Fi re-transmit?

### ISSUE THREAD

**Issue by lubingxian** [espressif/esp-idf#1872]
I found that ESP32 WiFi driver will re-transmit the unicast packet.
Is it possible to disable the re-transmit or change the max re-transmit time?

**Comment by liuzfesp** [comment]
@lubingxian currently we don't have such kind of API to set the re-transmit counter and max re-transmit time, it's hard-coded in WiFi driver.

**Comment by liuzfesp** [comment]
@lubingxian currently we don't have such kind of API to set the re-transmit counter and max re-transmit time, it's hard-coded in WiFi driver.

**Comment by lubingxian** [comment]
@liuzfesp Many thanks for your reply!
Will this function be easy to implement? Since we really need this function in our research project, could you make a prototype for us?

**Comment by lubingxian** [comment]
@liuzfesp What we need is a WiFi driver without the re-transmit. Thank you!

**Comment by liuzfesp** [comment]
@lubingxian I'm afraid that currently we don't have API to disable the WiFi retransmit.
