### ISSUE TITLE
Running our script when "make" is triggered

### ISSUE THREAD

**Issue by hvishu** [espressif/esp-idf#1875]
In our product, we have to run some .sh script that creates and copies binaries used as part of "make flash".  Right now we are running this script manually once the "make" command is done and before "make flash".
My question is, can we have this script automatically run when "make" command is triggered?  I would like to keep my changes as part of my project in example/folder.

**Comment by negativekelvin** [comment]
https://github.com/loboris/MicroPython_ESP32_psRAM_LoBo/blob/master/MicroPython_BUILD/Makefile
