### ISSUE TITLE
[TW#12239] BLE: Suggestions for improvements in GATT error codes

### ISSUE THREAD

**Issue by nkolban** [espressif/esp-idf#188]
If we look at the data types for BLE/GATT, we find a data type called `esp_gatt_status_t`.  This can be found here:

https://github.com/espressif/esp-idf/blob/87d0eb0fdb00b84987f5fed1d6316868dc420896/components/bt/bluedroid/api/include/esp_gatt_defs.h#L175

This is an enum with a large number of possibilities.   This suggestion asks for the consideration of including the word "STATUS" or "ERR" in the enum name.  For example ... instead of the current `ESP_GATT_NO_RESOURCES`, the suggestion would be to have one of:

* `ESP_GATT_STATUS_NO_RESOURCES`
* `ESP_GATT_ERR_NO_RESOURCES`

We are already very rich in the namespace of symbols that begin `ESP_GATT_*` and having some syntactical namespacing to identify status/error types would be very helpful (opinion).

**Comment by TianHao-Espressif** [comment]
Thank you for the suggestion. The name is from original bluedroid BTA_xxx.  We do the minimal modification. But it is a good suggestion, we will consider that.
