### ISSUE TITLE
Compilation fails if CONFIG_HEAP_TASK_TRACKING=y

### ISSUE THREAD

**Issue by slcasner** [espressif/esp-idf#1886]
Commit 573ea385b433c3c0e0397f15f4f5c1866edad3aa removed #include <freertos/task.h> from components/heap/multi_heap_platform.h.  That causes compilation to fail if CONFIG_HEAP_TASK_TRACKING=y because there are references to TaskHandle_t and TaskGetCurrentTaskHandle().

**Comment by chegewara** [comment]
https://github.com/espressif/esp-idf/issues/1881

**Comment by slcasner** [comment]
Sorry for the duplicate.
