### ISSUE TITLE
[TW#20801] Piconet Example

### ISSUE THREAD

**Issue by Kolsha** [espressif/esp-idf#1890]
Hi guys, saw in the source code of the makings of piconet, but the implementation examples are nowhere to be found.
I will be glad if you show me how to do this or give links to already existing options.
Thank you!
P.S. I already sought in Google and on your forum.

**Comment by Kolsha** [comment]
Anybody?

**Comment by Weijian-Espressif** [comment]
where is the source code of the makings of piconet ? is it about  wifi or bt  piconet ?

**Comment by Kolsha** [comment]
So, I solved my problem in this way: https://github.com/Kolsha/ESP32-SPP-QT
I will be glad to criticism and suggestions.

**Comment by blueMoodBHD** [comment]
@Kolsha Thanks for your demo very mush. It's great!

P.S. **bt_spp_acceptor** and **bt_spp_initiator** in ESP_IDF examples, can connect more than 1 device.

And, is there any problems more?

**Comment by Kolsha** [comment]
No, thank you!
