### ISSUE TITLE
Support STA333BW power-amplifier IC

### ISSUE THREAD

**Issue by renne** [espressif/esp-idf#1894]
Today I received a [STA333BW](http://www.st.com/resource/en/datasheet/sta333bw.pdf)-based [13$ USB power-amplifier](https://de.aliexpress.com/item/DC16V-20W-20W-CM108-USB-I2S-STA333W-pure-digital-power-amplifier-board-With-USB-sound-card/32816241272.html) with 2x20W. It sounds pretty well. In my opinion ESP32 and [STA333BW](http://www.st.com/resource/en/datasheet/sta333bw.pdf) would make quite a couple. With two [STA333BW](http://www.st.com/resource/en/datasheet/sta333bw.pdf)s on the  two I2S-outputs of the ESP32 it would even be possible to drive Bi-Amp speakers. And with four I2S microphones far-field filtering would be great. This would be quite a voice-assistant and multi-room audio platform.

**Comment by FayeY** [comment]
Closing this, as this issue tracker is not the right place for hardware design discussion. Please use esp32.com forum instead.

**Comment by renne** [comment]
OK. The issue was about I²C-API/library support in the ESP-32 IDF.

**Comment by krzychb** [comment]
Hi @renne,

Please check [ESP-ADF](https://github.com/espressif/esp-adf) that provides  I²C-API/library support in with ESP32 IDF.

There are two audio boards by Espressif available that support speakers and microphones. 
* [ESP32-LyraT](https://esp-adf.readthedocs.io/en/latest/get-started/get-started-esp32-lyrat.html) - already supported by ESP-ADF
* [ESP32-LyraTD-MSC](https://www.espressif.com/sites/default/files/documentation/esp32-lyratd-msc_user_guide_en.pdf) - API support is coming

Maybe you will find them interesting or inspiring to bootstrap a solution with STA333BW.

**Comment by renne** [comment]
I created a [new issue](https://github.com/espressif/esp-adf/issues/14) in [ESP-ADF](https://github.com/espressif/esp-adf) as a starting point for more powerful amplifiers than on the LyraT.
