### ISSUE TITLE
RTC_CNTL_DBIAS shifted by 0.05V

### ISSUE THREAD

**Issue by michprev** [espressif/esp-idf#1899]
RTC_CNTL_DBIAS voltage values are shifted by 0.05V. According to technical reference it should be within range 0.85V - 1.2V 
https://github.com/espressif/esp-idf/blob/051d8d69000839985e9b6a281e89ccfe6c16080e/components/soc/esp32/include/soc/rtc_cntl_reg.h#L1142-L1149

**Comment by igrr** [comment]
Thanks for reporting this @michprev, I've passed this to the documentation team to fix in TRM. Values in listed IDF are the correct ones.
