### ISSUE TITLE
Release 3.0 Assets missing complete .zip file

### ISSUE THREAD

**Issue by BrettGoldbach** [espressif/esp-idf#1903]
I am having trouble cloning the 3.0 release and would like to try just downloading the .zip instead but when I went to the release assets there is only the source code files available.

This is the only recent release that doesn't have the complete zip file with .git and submodules etc. Is there a reason for this? And can it be added to the release assets?

Thanks
- Brett

**Comment by igrr** [comment]
Thanks for reporting this @BrettGoldbach, the missing file has been added.
