### ISSUE TITLE
[TW#20810] CMake: Sign the tools installer

### ISSUE THREAD

**Issue by robotdad** [espressif/esp-idf#1909]
## Environment
- Development Kit:      [n/a]
- Kit version (for WroverKit/PicoKit/DevKitC): n/a
- Core (if using chip or module): n/a
- IDF version n/a
- Development Env:		[Arduino IDE|Make|Eclipse|other]
- Operating System:		[Windows]
- Power Supply:         n/a

## Problem Description

Maybe this isn't the right issue list, but please sign the esp-idf-tools-setup-1.0.exe. Unsigned binaries will present a lot of warning dialogs on Windows that are increasingly difficult, intentionally, to navigate through. I haven't checked other platforms, but I presume this impacts at least MacOS as well but I haven't checked there if your tools are singed or not. Not being able to be sure of the provenance of tools used to build your IoT applications really is not a good thing.

**Comment by projectgus** [comment]
Will do. Signing the installer was always part of the plan, but I wanted to get the Preview out ASAP. :)

We don't ship a dedicated Tools installer on any other platforms right now, just Windows+CMake.
