### ISSUE TITLE
esp_log_set_vprintf simply does not work ?

### ISSUE THREAD

**Issue by psykokwak-com** [espressif/esp-idf#1916]
## Environment

- Development Kit: ESP32-Wrover
- Core (if using chip or module): ESP32-Wrover-I
- IDF version : 1424b6d
- Development Env:		Visual Studio Micro (Arduino environment)
- Operating System:		Windows
- Power Supply:         External 3.3v

## Problem Description

I try to redirect logging text but it does not work.

### Expected Behavior

"After" should not be displayed and replaced by "Nop nop nop".

### Code to reproduce this issue

```cpp
static int debugOutputHandler(const char *v, va_list l)
{
  return Serial.println("Nop nop nop");
}

void setup() {
  Serial.begin(115200);
  Serial.println("OK, lets see :)");
  log_e("Before");
  esp_log_set_vprintf(debugOutputHandler);
  log_e("After");

}

void loop() {
  // put your main code here, to run repeatedly:

}
```

## Debug Logs

```
ets Jun  8 2016 00:22:57

rst:0x1 (POWERON_RESET),boot:0x33 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:956
load:0x40078000,len:0
load:0x40078000,len:13268
entry 0x40078a94
OK, lets see :)
[E][sketch_may04a.ino:9] setup(): Before
[E][sketch_may04a.ino:11] setup(): After

```

**Comment by negativekelvin** [comment]
Arduino has its own log implementation that bypasses it so you should move this issue to https://github.com/espressif/arduino-esp32
