### ISSUE TITLE
eclipse IDE toolchain error

### ISSUE THREAD

**Issue by ahmedawais** [espressif/esp-idf#1920]
i am getting the following error in eclipse IDE which is running in Ubuntu. i followed the instruction of  koblan book step by step. please resolve this error

 **** Build of configuration Default for project myapp ****
make all 
/opt/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc: 1: /opt/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc: Syntax error: "(" unexpected
/opt/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc: 1: /opt/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc: Syntax error: "(" unexpected
WARNING: Failed to find Xtensa toolchain, may need to alter PATH or set one in the configuration menu
/opt/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc: 1: /opt/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc: Syntax error: "(" unexpected
/opt/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc: 1: /opt/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc: Syntax error: "(" unexpected
WARNING: Failed to find Xtensa toolchain, may need to alter PATH or set one in the configuration menu
CC /home/awais/esp32/apps/myapp/build/bootloader/bootloader_support/src/efuse.o
/opt/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc: 1: /opt/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc: Syntax error: "(" unexpected
/home/awais/esp32/esp-idf/make/component_wrapper.mk:285: recipe for target 'src/efuse.o' failed
make[2]: *** [src/efuse.o] Error 2
make[1]: *** [component-bootloader_support-build] Error 2
make: *** [/home/awais/esp32/apps/myapp/build/bootloader/bootloader.bin] Error 2
/home/awais/esp32/esp-idf/make/project.mk:467: recipe for target 'component-bootloader_support-build' failed
/home/awais/esp32/esp-idf/components/bootloader/Makefile.projbuild:40: recipe for target '/home/awais/esp32/apps/myapp/build/bootloader/bootloader.bin' failed

**Comment by anujdeshpande** [comment]
What version of the toolchain & IDF are you using?
