### ISSUE TITLE
why the sample no the AirKiss to show?

### ISSUE THREAD

**Issue by xuhongv** [espressif/esp-idf#1927]
why the sample no the AirKiss to show?

为什么给出的demo中没有 airkiss的配网代码呢？

**Comment by negativekelvin** [comment]
https://github.com/espressif/esp-idf/blob/87d0eb0fdb00b84987f5fed1d6316868dc420896/components/esp32/include/esp_smartconfig.h#L36

https://github.com/espressif/esp-idf/blob/0d65f3b7f9a1dace8853719871d920d80aa3604b/examples/wifi/smart_config/main/smartconfig_main.c#L106
