### ISSUE TITLE
[TW#22510] esp_deep_sleep_start does not work in master

### ISSUE THREAD

**Issue by OtherCrashOverride** [espressif/esp-idf#1931]
The following commit breaks deep sleep:
https://github.com/espressif/esp-idf/commit/0d65f3b7f9a1dace8853719871d920d80aa3604b

The device immediately wakes regardless of wake condition (ext0/ext1) settings.  Reverting the commit resolves the issue.

Reproducible with https://github.com/espressif/esp-idf/tree/master/examples/system/deep_sleep

**Comment by igrr** [comment]
Sorry, I can't reproduce the issue with deep_sleep example. I observe device waking up after 20 seconds or when connecting GPIO25/26 to VCC. This is with WROVER_KIT board (rev1 chip) and DevKit-C (rev0 chip).

Could you please mention the hardware you use, as suggested in the issue template? Could you please also enable "Debug" log level and attach the log output you get, along with your sdkconfig file? Thanks.

**Comment by OtherCrashOverride** [comment]
Hardware is a custom board with WROVER module.  IO13 is the only wake up source.  It has internal pull-up enabled and a switch connected to GND.  Deep sleep fails regardless of whether the Ext0 wake condition is "1" or "0".

A debug log may be provided in the future if time permits.  This post is done as a courtesy to others that may encounter the issue.  Reverting the commit resolves the issue for me.
