### ISSUE TITLE
[TW#22511] Typo

### ISSUE THREAD

**Issue by mcccol** [espressif/esp-idf#1932]
https://github.com/espressif/esp-idf/blob/0d65f3b7f9a1dace8853719871d920d80aa3604b/components/bt/bluedroid/bta/gatt/bta_gattc_co.c#L78

This should be: static const char *cache_key = "gattc_cache_key";

Not 'gattc_cahe_key'

**Comment by Weijian-Espressif** [comment]
@mcccol Thanks for your reminder, I will fix the error. thanks.

**Comment by FayeY** [comment]
Fixed. Thanks for reporting this.
