### ISSUE TITLE
Support: plan for cmake build system

### ISSUE THREAD

**Issue by nicola-lunghi** [espressif/esp-idf#1938]
Dear espressif,
we are about to start evaluating esp32 for a product.
We see that you have a features/cmake branch on this git repository that support cmake (and we like cmake)
1) what are your plan regarding cmake? did you plan to switch from the Makefile based system to cmake or only to use it on the windows build?
2) idf.py : this is needed? can we call cmake directly (more useful in automated build)?
4) is flash encryption and secure boot supported also with cmake?
5) can you please generate the documentation on readthedocs also for the cmake branch? 
Thanks
Nicola Lunghi

**Comment by projectgus** [comment]
Hi @nicola-lunghi ,

Very glad to hear you're interested in the CMake support! The CMake-based build system is currently in a preview release. There is an announcemnt on our forum with more details (it's not linked from Github, unfortunately):
https://esp32.com/viewtopic.php?f=13&t=5559&p=24109

I think the forum post addresses the questions you have here, but I'll repeat answers below just in case:

1. We plan to merge the CMake-based build system into our master branch after the upcoming IDF v3.1 release candidate. At this point, CMake will become the default build system. However we will continue to also support the older GNU Make based system for IDF v3.x and possibly longer, depending on how the migration goes.
2. `idf.py` is not needed, it's a wrapper to automate some non-build-related functions (like flashing) for command line users. However CMake can be called directly. [You can find some more details about this here](https://docs.espressif.com/projects/esp-idf/en/feature-cmake/api-guides/build-system.html#using-cmake-directly).
3. Flash encryption and Secure Boot are currently not supported (the implementation is there in parts, but the full workflow for enabling these features is not complete). Support will be added ASAP.
4. You can find docs for the CMake branch here: https://docs.espressif.com/projects/esp-idf/en/feature-cmake/ (the Getting Started guides and Build System API Guide both deal with the CMake build system, exclusively.)

**Comment by nicola-lunghi** [comment]
Nice!
Thank you for your response.

**Comment by projectgus** [comment]
No problems. If you use the CMake branch and encounter any problems, please raise issues on github and we'll take a look ASAP. Or if you have any more questions I'm happy to answer them, here or on the forum.

The forum post will be updated once some of the missing support (secure boot, flash encryption, etc) is available in CMake.
