### ISSUE TITLE
MQTT TLS support

### ISSUE THREAD

**Issue by nicola-lunghi** [espressif/esp-idf#1939]
Hi
do you currently support MQTT protocol in the esp-idf sdk?
Also I read that there are issue with the sdk with MQTT TLS connection with the Arduino framework related to some problem in the esp-idf is TLS usable?
Do  you have some examples about using MQTT (better if with TLS) with the esp-idf framework?
Thanks
Nicola Lunghi

**Comment by chegewara** [comment]
I have not test it with TLS yet, but this repo seems to be good:
https://github.com/tuanpmt/esp32-mqtt

**Comment by nicola-lunghi** [comment]
so I can send
homie/super-car/$homie → "3.x.x" ?

**Comment by nicola-lunghi** [comment]
Nice
the project has moved to https://github.com/tuanpmt/espmqtt/
I will test it
Thanks
