### ISSUE TITLE
make monitor shows up in new terminal but code is unreadable

### ISSUE THREAD

**Issue by ahmedawais** [espressif/esp-idf#1949]
Hi,
  i am trying to use the Bluetooth of esp32 and running the code in eclipse IDE which is installed on virtual machine Ubuntu. the code is running fine but when i build target of make monitor in eclipse it runs but after that is shows an unreadable code. please help

**Comment by ahmedawais** [comment]
yes in menuconfig FLASH SPI is 26 Mhz

**Comment by negativekelvin** [comment]
Not spi speed, Main XTAL frequency

**Comment by ahmedawais** [comment]
where is the option in menuconfig to set this XTAL frequency ?

**Comment by negativekelvin** [comment]
https://esp-idf.readthedocs.io/en/latest/get-started/index.html#monitor

**Comment by ahmedawais** [comment]
thanks @negativekelvin  code is working now. but the ESP32 bluetooth is not appearing in the andriod phone i am using nRF UART app. do you have any idea ?

**Comment by nkolban** [comment]
@ahmedawais You are likely going to want to create a new issue for a completely different topic or else post a question to the ESP32 forum found here:

https://esp32.com/index.php

**Comment by projectgus** [comment]
@ahmedawais , yes please ask this question on the forum. Provide as many details there as you can.
