### ISSUE TITLE
Whether the wifi-lib contains wifi-p2p mode?

### ISSUE THREAD

**Issue by long585** [espressif/esp-idf#195]
At present this version wifi mode only have  WIFI_MODE_STA,  WIFI_MODE_AP,   WIFI_MODE_APSTA.
 Whether it can provide wifi-p2p mode?
@projectgus @bvernoux @rojer @MalteJ @sandeepmistry

**Comment by igrr** [comment]
Answered in the forum post: http://esp32.com/viewtopic.php?f=2&t=862
