### ISSUE TITLE
[TW#22876] esp_wifi_set_auto_connect is deprecated

### ISSUE THREAD

**Issue by Reiner1210** [espressif/esp-idf#1960]
What should be used instead - docu is missing

**Comment by negativekelvin** [comment]
https://github.com/espressif/esp-idf/issues/1377

**Comment by Reiner1210** [comment]
I still not know which function I can use to get rid of the dammed auto connect

**Comment by liuzfesp** [comment]
Hi @Reiner1210, although esp_wifi_set_auto_connect() is marked as deprecated, you can still use it. Just keep this in mind: esp_wifi_set_auto_connect() only set the auto connect flag in flash, it doesn't really do the auto connect!
