### ISSUE TITLE
CMake: Arrow keys in idf.py menuconfig have no effect

### ISSUE THREAD

**Issue by hak8or** [espressif/esp-idf#1969]
- [x] I have read the documentation [ESP-IDF Programming Guide](http://esp-idf.readthedocs.io/en/latest/) and the issue is not addressed there.
- [x] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [x] I have searched the issue tracker for a similar issue and not found a similar issue.

## Environment

- Windows:  10.0.17134 Build 17134
- Development Kit:      [ESP32-DevKitC]
- Kit version (for WroverKit/PicoKit/DevKitC): [v1|v2|v3|v4]
- Core (if using chip or module): [ESP32-Wrover-I|ESP32-Wrover|ESP32-PICO-D4|ESP32-SOLO-I|ESP32-WROOM-32U|ESP-WROOM-32D|ESP-WROOM32|ESP32]
- IDF version (``git rev-parse --short HEAD`` to get the commit id.): 829e6c4
- Development Env:		[CLion/CLI]
- Operating System:		[Windows]
- Power Supply:         [USB]

## Problem Description

Running ```idf.py menuconfig``` in windows command prompt creates the correct menuconfig display, but for some weird reason though, arrow keys don't seem to work in it. I am able to use the letter keys, for example pressing "B" to enter "Bootloader Config", and the Tab key to go through "Select", "Exit", "Load", etc also works. Pressing the escape key and enter key also works. It seems to just be arrow keys which aren't working. This was first noticed in #1967 

I tried to do this in power shell as well. It seems something in idf.py wants to create a new command prompt window, in which this behavior also exists.

### Expected Behavior

Arrow keys in menuconfig should change the selection.

### Actual Behavior

No effect.

### Steps to repropduce

```bash
# Create a folder for this
mkdir issue
cd issue

# Copy an example from IDF
 cp -r ..\idf\examples\get-started\blink\* .

# This gives: Python 2.7.15
python -v

# This gives: cmake version 3.11.1
cmake --version

# This gives: 1.8.2
ninja --version

# This gives: IDF_PATH=C:\code\BookKeeper\idf
c:\code\BookKeeper>set IDF_PATH

# Arrow keys in here do not seem to work.
idf.py menuconfig
```

**Comment by hak8or** [comment]
Ugh, sorry for wasting your time with this issue. Doing deleting the old ```build``` folder seems to have resolved it for some reason. I can also confirm I can use arrow keys with no issues in my personal project now too. Feel free to close this if you wish.

**Comment by projectgus** [comment]
That's weird! I'm glad you found a fix for it. I'll close for now but if you manage to trigger this again, please reopen and let us know.

**Comment by hak8or** [comment]
You got it! And thanks again for helping out with the previous issue! I have to say, I think y'all are the best silicon vendor provided supporting software out there, miles beyond what Atmel/Analog Devices/ST/etc provide. Especially for CMake support, this is golden in CLion and other IDE's that work with CMake. Y'all are awesome!

**Comment by projectgus** [comment]
Thanks, much appreciated! There's still a lot we'd like to improve, but I'm glad that CMake is working out for you so far. :smile:
