### ISSUE TITLE
Question: HotSpot 2.0 release 2 support? (IDFGH-48)

### ISSUE THREAD

**Issue by ivanO86** [espressif/esp-idf#197]
Hi,

first of all, thanks for all the job supporting the ESP32. I have a question about the possibility of add new feature to the wireless support. Passpoint (HS 2.0) could be a good solution to provisioning and on boarding processes for IoT devices. Are you thinking about to add this feature to your WiFi library in a future release?. It would be great to have this feature in this board. 

Thanks again, best regards.

**Comment by jack0c** [comment]
@ivanO86 Hotspot will not be in our recent TODO list.
