### ISSUE TITLE
Windows paths in msys32 environment

### ISSUE THREAD

**Issue by paccerdk** [espressif/esp-idf#1972]
The Windows instructions at:
[https://github.com/espressif/esp-idf/blob/master/docs/en/get-started/add-idf_path-to-profile.rst#windows](https://github.com/espressif/esp-idf/blob/master/docs/en/get-started/add-idf_path-to-profile.rst#windows)

Instructs the user to use windows paths in the msys32 environment:
> export IDF_PATH="C:/msys32/home/user-name/esp/esp-idf"

This will not work within the msys32 shell, and should probably be same as the linux instructions:
> export IDF_PATH=~/esp/esp-idf

**Comment by projectgus** [comment]
Is using a Windows-style path here not working?

We do some "magic" in the Makefiles to convert these paths, so Windows users can use a more familiar path style if they prefer: https://github.com/espressif/esp-idf/blob/master/make/project.mk#L75

**Comment by FayeY** [comment]
Hi @paccerdk , did the above suggestion help you resolve the issue?
