### ISSUE TITLE
[TW#22880] SSL (HTTPS)

### ISSUE THREAD

**Issue by snahmad** [espressif/esp-idf#1973]
I need to get my .bin binary file over the air using https/ssl.
Any example?

Also I need to  do http get web files as well. 
Have some one written C/C++ routine to do both .bin and and any web file and write to SD card file system as file using secured http.

**Comment by mahavirj** [comment]
@snahmad Multiple examples are available in ESP-IDF, e.g. `https_request`, `https_mbedtls` for showing TLS communication with server. You may take that as starting point for adding support for writing image/file to SD card. Please note that, for how-to related questions, please prefer using https://www.esp32.com forum
