### ISSUE TITLE
[TW#22881] In Wroom module can IO22 usage as PWM

### ISSUE THREAD

**Issue by hvishu** [espressif/esp-idf#1974]
In Wroom module could IO22 (pin36) usage as PWM? IO0(pin21), works fine, we wanted to replace IO0 by IO22, but the same code is not working with IO22.  Could you confirm?

**Comment by hvishu** [comment]
Can be used.  Tried with ledc test app and found to be working

**Comment by costaud** [comment]
Any GPIO that is able to be configured as output(except the IOs attached to FLASH or pSRAM) , can be used as LEDC(PWM).
