### ISSUE TITLE
Cannot ping the modem.. PPP (IDFGH-238)

### ISSUE THREAD

**Issue by sarpdaltaban** [espressif/esp-idf#1976]
Thanks to the examples, established the IP and the network mask right now; however, I cannot ping the modem even the LWIP_ICMP module activation is enabled over STM32CubeMX.
Does it need a function to be called to  enable pings?

**Comment by liuzfesp** [comment]
@sarpdaltaban could you let me know the detailed steps to reproduce this issue?

**Comment by sarpdaltaban** [comment]
You must enable outgoing and incoming checksum for ICMP as well as
activating module on STM32CubeMX

2018-06-04 9:04 GMT+03:00 liuzfesp <notifications@github.com>:

**Comment by liuzfesp** [comment]
@sarpdaltaban sorry for late response,  we don't have STM32CubeMX, is it possible for you to reproduce this issue without STM32CubeMX? E.g. with PC etc.

**Comment by Alvin1Zhang** [comment]
@sarpdaltaban Thanks for reporting the issue. Is it possible for you to reproduce this issue without STM32CubeMX? E.g. with PC etc.? Thanks.

**Comment by Alvin1Zhang** [comment]
@sarpdaltaban Thanks for reporting. For third party issue or "how" questions, please help submit a post at our forum at https://esp32.com. Thanks.
