### ISSUE TITLE
How to create and build an ESP-IDF static library?

### ISSUE THREAD

**Issue by janoist1** [espressif/esp-idf#1978]
I'm learning ESP-IDF platform and now want to create a library in order to be able to structure my code properly in the future.

I've done some research and found few things, for instance a [library][1] that could be as an example. The only issue with it being too large, I can't clearly see what's the bare minimum for the simplest library code.

What is the minimum configuration for an ESP-IDF static library that can be built into a `.a` file?

  [1]: https://github.com/Gfast2/open62541_port/tree/master/components/open62541

**Comment by projectgus** [comment]
For structure & modularity, IDF has the concept of "components". Each component is built into a static library as part of the build process.

The smallest possible component would contain one source file only, as well as a component.mk file to define the component and describe the location of that source file.

You can find documentation about the build system and creating components here:
https://esp-idf.readthedocs.io/en/latest/api-guides/build-system.html

I'm going to close this as it's not an issue with ESP-IDF itself. For questions like this, feel free to start a discussion thread over at the https://esp32.com/ forums.
