### ISSUE TITLE
[TW#22884] truncate function not defined in unistd.h library

### ISSUE THREAD

**Issue by davctv** [espressif/esp-idf#1980]
Hi,

I would like to use "truncate" function of unistd.h to reduce the length of a file. However it seems not available/defined. The following link is a thread on esp32.com

https://esp32.com/viewtopic.php?f=13&t=5760&p=25136#p25136

Is it possible to introduce it in newlib library?

Thank you

**Comment by davctv** [comment]
Hello @FayeY. Is there any update on this issue?

Thanks

**Comment by renzbagaporo** [comment]
Hi @davctv, what filesystem are you working with? We have something (ongoing) with truncating files on fatfs, but spiffs might follow a bit later.

**Comment by davctv** [comment]
Hi @renzbagaporo, I'm using FATfs component. Do you have an estimation time for implementing the truncate function?

Thanks

**Comment by renzbagaporo** [comment]
It's an open MR in our internal repo and just passed initial review and test. Hopefully it'll get merged by the end of the week @davctv.

**Comment by davctv** [comment]
Good. Thank you. I look forward for merging and to test it.

**Comment by davctv** [comment]
The function is now included (commit c77f84e788819a5070a9ea63b9a73fb0aea6df15) and it seems to work correctly. Thanks.

**Comment by dizcza** [comment]
@davctv thanks for bringing in the `truncate` function. Wouldn't it be nice to have `ftruncate` as well? :) Implementing it by myself is beyond my capabilities.

**Comment by Rajssss** [comment]
@dizcza I am looking for the same, did you find anything useful regarding this anywhere?

**Comment by dizcza** [comment]
@Rajssss nope.

**Comment by igrr** [comment]
@Rajssss @dizcza I have opened a feature request: https://github.com/espressif/esp-idf/issues/8279
