### ISSUE TITLE
SPIFFS mount fails when flash encryption is enabled

### ISSUE THREAD

**Issue by Buffalchill** [espressif/esp-idf#2001]
I tried the SPIFFS example while flash encryption was enabled. 
the .bin file was encrypted with a pre-generated-key from espsecure.py 
and uploaded with the esptool.py

The result was: mount fail. Isn't it possible to use Spiffs if flash encryption is enabled ?

![spiffserror_example](https://user-images.githubusercontent.com/25742400/40541229-3a450890-601b-11e8-8b60-ed0f0fefc018.JPG)

**Comment by me-no-dev** [comment]
SPIFFS is not supported when flash encryption is enabled. You can use FATFS instead

**Comment by Buffalchill** [comment]
but FATFS is only for SD card right ?

**Comment by me-no-dev** [comment]
FATFS is supported on the flash as well. https://github.com/espressif/esp-idf/tree/master/examples/storage/wear_levelling it's the wear leveling lib that makes it possible to be used when flash is encrypted.

**Comment by Buffalchill** [comment]
Thank you ! Is this also available in the Arduino-Esp32 ? (I didn't find a sketch or a example, yet)

**Comment by Buffalchill** [comment]
I tried the FATFS wear leveling example from the esp-idf but it doesn't seem to work with flash encryption.
I also tried the arduino-esp32 EEPROM example which doesn't work too.
It seems like there is no way to store data, without loosing it when esp32 shuts down  🌊 

![fatfs](https://user-images.githubusercontent.com/25742400/40567107-47696120-6074-11e8-9fc3-2ea952a041bb.JPG)
encryption

**Comment by Buffalchill** [comment]
Spiffs and Preferences work with encryption enanbled. Just didn't have the right partition table on my board

**Comment by bastianhjaeger** [comment]
> Spiffs and Preferences work with encryption enanbled. Just didn't have the right partition table on my board
I do not see how SPIFFS can work with encryption (but I am trying to) if I see:

![Screenshot from 2020-06-15 11-19-25](https://user-images.githubusercontent.com/26868917/84640595-30159800-aefa-11ea-8db1-f5e56d309cfb.png)
https://github.com/espressif/esp-idf/blob/master/components/spiffs/esp_spiffs.c#L166

@Buffalchill Could you elaborat this, please?
