### ISSUE TITLE
build failed by file system is not *case-sensitive* but it is

### ISSUE THREAD

**Issue by iGyver** [espressif/esp-idf#2006]
I'm at the end of the toolchain setup from the sratch for MacOS. Actually there is just an issue with the last step the build.

* The file system is Case Sensitiv.
* The build procedure doesn't accept it.

Unfortunately I'm stuck now.

![esp_32_macos_casesensitiv_hfs_issue](https://user-images.githubusercontent.com/14597258/40579157-b2fdecaa-6121-11e8-8ab0-a6a43ccbd5e2.png)

**Comment by projectgus** [comment]
Hi Kay,

The "ctng" filesystem in the screenshot is mounted at `/Volumes/ctng` but the path in the error is `/Users/xxx/esp/crosstool-NG` which is part of your main filesystem.

Is there a symlink from one to the other? If so, a workaround might be to change `cd` into the "real" mount point directory and run ct-ng from there.

Angus

**Comment by FayeY** [comment]
Hi @iGyver , did the above suggestion help you resolve the issue?

**Comment by MGonzalez506** [comment]
I have the same error, I think I did @projectgus suggestion but nothing happened. (Using High Sierra 10.13.6)

<img width="455" alt="screen shot 2018-09-16 at 07 00 51" src="https://user-images.githubusercontent.com/25613690/45596791-dd065e00-b97e-11e8-922a-a26f7c748022.png">
