### ISSUE TITLE
[TW#23133] Support RFC 8106 IPv6 RA Recursive DNS server configuration

### ISSUE THREAD

**Issue by praseodym** [espressif/esp-idf#2008]
IPv6 Router Advertisment messages can contain Recursive DNS servers as defined in [RFC 8106](https://tools.ietf.org/html/rfc8106), so that DNS can be configured without DHCP(v4/v6). This is currently not supported in LWIP, but is a requirement for ESP32 devices to work in IPv6-only networks.

**Comment by projectgus** [comment]
@praseodym a little bit of extra context: We're in the process of updating the ESP-IDF LWIP to V2.0.3, and probably won't merge any changes to LWIP functionality until after this is done (planning for a matter of weeks not months).

It looks like these patches should apply to upstream V2.0.3 as well though, so we can take a look some time after this change lands. Thanks very much for sending these improvements to us.

**Comment by negativekelvin** [comment]
https://github.com/espressif/esp-idf/pull/2009

@liuzfesp note that lwip 2.0.1+ also supports this

**Comment by liuzfesp** [comment]
HI @praseodym this feature already in IDF master since the LWIP is upgrade to v2.0.3.
