### ISSUE TITLE
[TW#23134] "localhost:3333: The system tried to join a drive to a directory on a joined drive." GDB Debugging how to resolve this 

### ISSUE THREAD

**Issue by jegajith** [espressif/esp-idf#2010]
Hi I am getting this following error when I am trying to debug the ESP32 with a FTDI 2232HL Adapter 

"localhost:3333: The system tried to join a drive to a directory on a joined drive."
How to resolve this issue 

![eclipsegdberror](https://user-images.githubusercontent.com/39734675/40661742-27b5e514-6372-11e8-830e-fdb5c21bf22a.PNG)

**Comment by igrr** [comment]
Please make sure that openocd is running when GDB is started, and that local port 3333 is not blocked by a firewall. This error indicates that GDB can not open port 3333.

**Comment by jegajith** [comment]
Thank  you Ivan , for your reply. Its not able to detect the driver,  I have changed the Windows Driver using the below Software. 

![image](https://user-images.githubusercontent.com/39734675/41016438-efae8012-696c-11e8-820d-13c9466387ba.png)

Now its working ! , But i observed one thing  the GDB debugging is inconsistent, often it will go offline , Every time i need to restart the GDB.  

Do you recommend any other JTAG Device ?

**Comment by igrr** [comment]
We are working on improvements to JTAG debugging reliability. Please follow updates to OpenOCD releases, and file issues in OpenOCD repository if you see incorrect behavior.

**Comment by jegajith** [comment]
Thanks  for your support .

**Comment by Waldkircher** [comment]
Hello, 
I am using the ESP-WROVER-KIT together with eclipse and I have configured the toolchain and eclipse as described in the manual from espressif on Windows 10. 

https://dl.espressif.com/doc/esp-idf/latest/api-guides/jtag-debugging/using-debugger.html#jtag-debugging-using-debugger-eclipse

But if I am starting the debugger I was always getting the following error message (seen on screenshot below)... Do you have any idea what`s wrong ???

![errormsg_eclipse](https://user-images.githubusercontent.com/41914009/44463283-8758c300-a617-11e8-810b-468b978124ae.jpg)

Open OCD seems to be OK..
![openocd](https://user-images.githubusercontent.com/41914009/44463606-955b1380-a618-11e8-849a-ea0f3382dae8.jpg)


Configuration of Eclipse is OK..
![eclipse debugger](https://user-images.githubusercontent.com/41914009/44463294-963f7580-a617-11e8-806c-b627906781d5.PNG)

USB Driver is OK...
![zadig](https://user-images.githubusercontent.com/41914009/44463314-a192a100-a617-11e8-92f5-63ef200d7c20.PNG)

**Comment by vgonet** [comment]
Hello, 
I've exactly the same issue. Have you an idea how to solve it ?
Best regards.
