### ISSUE TITLE
[TW#23135] How to setup ESP32 BLE Class 1?

### ISSUE THREAD

**Issue by mxwang101** [espressif/esp-idf#2011]
How to setup ESP32 BLE Class 1?

ESP32 BLE works well. But looklike BLE class 2, only coverage small area.

Could you tell me how to setup ESP32 BLE Class 1?

**Comment by negativekelvin** [comment]
Datasheet lists +12dbm but settings only available for +7dbm 
https://github.com/espressif/esp-idf/blob/92c469b5993b001a21970f0e58b25acd3f375807/components/bt/include/esp_bt.h#L165

**Comment by Weijian-Espressif** [comment]
@negativekelvin Sorry, now our ESP32 does not support higher power.

**Comment by negativekelvin** [comment]
@Weijian-Espressif is that a hardware or software limitation? What is the recommendation to build a long range btle/wifi gateway? Use external PA for BT only?
