### ISSUE TITLE
[TW#23136] Wifi Channel State Information : data : missing documentation

### ISSUE THREAD

**Issue by jonathanmuller** [espressif/esp-idf#2012]
Hello, 
Recently the Channel State Informations (CSI) were added with a callback to gather them, it is a huge improvement and opens the door to a lot of new possibilities !

## Goal 
Extract phase and/or amplitude and/or frequency from CSI packets ( wifi_csi_info_t -> buff)

## Problem

Because it was added recently, there is no documentation or explanation on what is contained on the buffer part of the structure wifi_csi_info_t [except from that](http://esp-idf.readthedocs.io/en/latest/api-reference/wifi/esp_wifi.html#_CPPv215wifi_csi_info_t), it is hard to extract information from those packets

I believe it should follow that format : 
![csi](https://user-images.githubusercontent.com/2054002/40726204-8e19356e-6425-11e8-918b-c8c575842214.png)

And this is what it look like : (  - are zeros and | are ones)
(CSI configuration is set to automatic)
----------------------|--------|-----|--------------------||||||---------------------------------------------|------------------|||||||||||||||||||||||||||||||||||||||||||||||||||||||||-|-||||||||||||||||||||||||||||||||||||||||||||||||||||||||||-||||||||-
So i can relatively clearely see the :
- Pilot subcarrier
- Null subcarrier
- data subcarrier

## Questions 
Why is there sometimes a pilot/data subcarrier to 1/0?
What is following the data subcarrier
How does one extract informations from this field, particularly the frequency matching ?

## Expected
Maybe you could add a bit of documentation on that field, or even share the frequency matching algorithm ?

Thank you and have a good day

Bests,
Jonathan

**Comment by jonathanmuller** [comment]
Awesome, I could not ask for a faster answer, thank you again !

For anyone searching for the same information see "Wi-Fi Channel State Information" section on "wifi.rst"

**Comment by MAT0RIX** [comment]
Hi Jonathan.
I am currently doing projects on CSI, luckily find your post here. Even though I check the document above I cant find a tutorial on how to collect data with ESP32's wifi option.
Kindly could you show me how to use the wifi option?
thx

**Comment by jonathanmuller** [comment]
Hi @MAT0RIX ,

What exactly is your problem ? 

If it is that you don't fully understand how to use the espressif SDK then you should check the documentation.
If you aren't able to get a CSI frame with the provided callback then explain exactly what you did and provide code sample.

Good day

**Comment by Dpunkt** [comment]
We also would like to use the csi values. 
But it is unclear when this data is updated.
The promicuous callback is called more often then the csi callback.
After reading the documentation i thought it would be updated on every incomming packet?

Can you please clarify this?

**Comment by xueyao1220** [comment]
Hi @jonathanmuller,

I am also trying to get CSI Infomation with ESP32. However, I am very lack of experience in programming with ESP32. Based on the IoT example pedestrian_flow, I modified the code to get CSI buffer.  However, it doesn't work at all. Could you please give me some hints to make it work? Thank you very much!

Best Regards,
Yao 


[app_main.txt](https://github.com/espressif/esp-idf/files/2394317/app_main.txt)

```
static esp_err_t wifi_event_handler(void *ctx, system_event_t *event)
{
    switch (event->event_id) {
    case SYSTEM_EVENT_STA_START:
        esp_wifi_connect();
        break;
    case SYSTEM_EVENT_STA_GOT_IP:
        xEventGroupSetBits(wifi_event_group, CONNECTED_BIT);
                if (!g_station_list) {
            g_station_list = malloc(sizeof(station_info_t));
            g_station_list->next = NULL;
            ESP_ERROR_CHECK(esp_wifi_set_promiscuous_rx_cb(wifi_sniffer_cb));
            ESP_ERROR_CHECK(esp_wifi_set_csi_rx_cb(wifi_csi_cb, NULL));
            ESP_ERROR_CHECK(esp_wifi_set_promiscuous(1));
        }
        break;
    case SYSTEM_EVENT_STA_DISCONNECTED:
        esp_wifi_connect();
        xEventGroupClearBits(wifi_event_group, CONNECTED_BIT);
        break;
    default:
        break;
    }
    return ESP_OK;
}

/*The callback function of CSI Reading*/
void wifi_csi_cb(void *data)
{
	wifi_csi_info_t *csi_data = (wifi_csi_info_t*)data;
	if(!csi_info){
	csi_info =  malloc(sizeof(wifi_csi_info_t));

	}

	csi_info->mac = csi_data->mac;
	csi_info->len = csi_data->len;
	csi_info->buf = csi_data->buf;

	printf("MAC: 0x%02X.",csi_info->*mac);
	printf("CSI data length: 0x%02X.",csi_info->len);


}
```

**Comment by jonathanmuller** [comment]
@xueyao1220 

Here is a pseudocode for your application :

init()
register wifi promiscious callback function
register wifi CSI callback function
enable csi (esp_wifi_set_csi)
enable promiscious mode (esp_wifi_set_promiscuous)
scan all channels (try to display the name of all your surrounding WiFi for example, the goal is to CONTINUOUSLY scan over all channels)

What could be missing from your example is :
enable CSI with the "esp_wifi_set_csi" function
enable CSI in menuconfig -> component config -> wifi -> wifi csi (channel state information)
enable promiscuous
switch channel continuously (1s over each channel for example)

**Comment by jonathanmuller** [comment]
It is not necessary but is a good idea for debug so you can see if there are compatible AP on any channel.

Are you sure, for example, that your AP sends CSI frames ?

In addition if I remember correctly you can’t be connected to an AP and AND be in promiscuous mode at the same time, they are exclusive modes. But I might be wrong.

**Comment by jonathanmuller** [comment]
@xueyao1220 
Maybe you can post your application basic code so people with the same problem can compare/use it.

That question is not really CSI related .. anyway : no I didn't log it on an SD card but on my computer.
I have the ESP32 dev board connected by USB to my computer so I have live output on my screen by reading /dev/ttyUSB0.
If you got question my email is available on my profil bio

**Comment by jonathanmuller** [comment]
Attached a working example.
Feel free to clean it and merge it via pull request or ask for details.
[scan_csi_frames.zip](https://github.com/espressif/esp-idf/files/2505340/scan_csi_frames.zip)

**Comment by christojoby** [comment]
> 
> 
> Hi @jonathanmuller,
> 
> I am also trying to get CSI Infomation with ESP32. However, I am very lack of experience in programming with ESP32. Based on the IoT example pedestrian_flow, I modified the code to get CSI buffer. However, it doesn't work at all. Could you please give me some hints to make it work? Thank you very much!
> 
> Best Regards,
> Yao
> 
> [app_main.txt](https://github.com/espressif/esp-idf/files/2394317/app_main.txt)
> 
> ```
> static esp_err_t wifi_event_handler(void *ctx, system_event_t *event)
> {
>     switch (event->event_id) {
>     case SYSTEM_EVENT_STA_START:
>         esp_wifi_connect();
>         break;
>     case SYSTEM_EVENT_STA_GOT_IP:
>         xEventGroupSetBits(wifi_event_group, CONNECTED_BIT);
>                 if (!g_station_list) {
>             g_station_list = malloc(sizeof(station_info_t));
>             g_station_list->next = NULL;
>             ESP_ERROR_CHECK(esp_wifi_set_promiscuous_rx_cb(wifi_sniffer_cb));
>             ESP_ERROR_CHECK(esp_wifi_set_csi_rx_cb(wifi_csi_cb, NULL));
>             ESP_ERROR_CHECK(esp_wifi_set_promiscuous(1));
>         }
>         break;
>     case SYSTEM_EVENT_STA_DISCONNECTED:
>         esp_wifi_connect();
>         xEventGroupClearBits(wifi_event_group, CONNECTED_BIT);
>         break;
>     default:
>         break;
>     }
>     return ESP_OK;
> }
> 
> /*The callback function of CSI Reading*/
> void wifi_csi_cb(void *data)
> {
> 	wifi_csi_info_t *csi_data = (wifi_csi_info_t*)data;
> 	if(!csi_info){
> 	csi_info =  malloc(sizeof(wifi_csi_info_t));
> 
> 	}
> 
> 	csi_info->mac = csi_data->mac;
> 	csi_info->len = csi_data->len;
> 	csi_info->buf = csi_data->buf;
> 
> 	printf("MAC: 0x%02X.",csi_info->*mac);
> 	printf("CSI data length: 0x%02X.",csi_info->len);
> 
> 
> }
> ```

Were you able to record Channel State Information with this on the ESP32 chipset?
