### ISSUE TITLE
[TW#23137] ESP-MESH Problem!

### ISSUE THREAD

**Issue by akshar001** [espressif/esp-idf#2014]
Hello,
I am using internal_reciever example for two days,
And there's one problem i am facing is it sometimes stucks at 

(1806) mesh: 2626<MESH_NEW_ROOT_VOTE_DONE>MESH_VOTE_STOP_FROM_HEALING, s_vote_scan_times:0

sometimes it connects to the wifi router but many times it is not?!
I have read the documentation several times but MESH_VOTE_STOP_FROM_HEALING is not mentioned anywhere...
here's the log..

`I (1296) mesh_main: <MESH_EVENT_STARTED>ID:77:77:77:77:77:77
W (1296) mesh: [mesh_set_io_process,1359] MESH_IO_CFG_SELF_ORGANIZED
W (1306) mesh: [mesh_nwk_task_main,3102] <MESH_NWK_IO_CFG>MESH_IO_CFG_SELF_ORGANIZED
I (1306) mesh: <3141>self organized disabled
I (1316) mesh: [SCAN][ch:6]AP:1, otherID:0, idle:0, mAP:1, root:0, top mAP:0[Layer:0/0.ing]router found
I (1326) mesh: 916, [SCAN]init rc[30:ae:a4:45:b1:ad,-48], mine:0, voter:0
I (1326) mesh: 952, vote myself, router rssi:-48 > voted rc_rssi:-120
I (1336) mesh: [SCAN:1/10]rc[128][30:ae:a4:45:b1:ad,-48], self[30:ae:a4:45:b1:ac,-48,reason:0,votes:1,idle][mine:1,voter:1(1.00)percent:0.90][128,1,30:ae:a4:45:b1:ad]

I (1356) mesh: [SCAN][ch:6]AP:0, otherID:0, idle:0, mAP:0, root:0, top mAP:0[Layer:0/1.ing]
I (1356) mesh: [FAIL][2]root:1, fail:1, normal:0
I (1366) mesh_main: mesh starts successfully, heap:193828, root not fixed

I (1716) mesh: 2019<scan>self-organized is disabled, users shall read out scan results by themselves.
I (1716) mesh_main: <MESH_EVENT_SCAN_DONE>number:5
I (1716) mesh_main: [0]VEGG, 28:3b:82:65:b7:19, channel:6, rssi:-44
I (1726) mesh_main: [1]WiFi Link Studio, 98:de:d0:4a:63:68, channel:6, rssi:-95
I (1736) mesh_main: [2]ARIZONA, ec:01:ee:bc:c7:19, channel:6, rssi:-89
I (1736) mesh_main: [3]jp consultancy, 00:1e:a6:a8:5e:00, channel:6, rssi:-88
I (1746) mesh_main: [4]SMWIFI, 00:17:7c:7e:22:a1, channel:6, rssi:-84
W (1756) mesh_main: no parent found, enable self-organized networking.
I (2126) mesh: [SCAN][ch:6]AP:6, otherID:0, idle:0, mAP:1, root:0, top mAP:0[Layer:0/1.ing]router found
I (2126) mesh: 916, [SCAN]init rc[30:ae:a4:45:b1:ad,-49], mine:0, voter:0
I (2126) mesh: [SCAN:2/10]rc[128][30:ae:a4:45:b1:ad,-49], self[30:ae:a4:45:b1:ac,-49,reason:0,votes:1,idle][mine:1,voter:1(1.00)percent:0.90][128,1,30:ae:a4:45:b1:ad]

I (2506) mesh: [SCAN][ch:6]AP:5, otherID:0, idle:0, mAP:1, root:0, top mAP:0[Layer:0/1.ing]router found
I (2506) mesh: 916, [SCAN]init rc[30:ae:a4:45:b1:ad,-64], mine:0, voter:0
I (2516) mesh: [SCAN:3/10]rc[128][30:ae:a4:45:b1:ad,-64], self[30:ae:a4:45:b1:ac,-64,reason:0,votes:1,idle][mine:1,voter:1(1.00)percent:0.90][128,1,30:ae:a4:45:b1:ad]

I (2886) mesh: [SCAN][ch:6]AP:5, otherID:0, idle:0, mAP:1, root:0, top mAP:0[Layer:0/1.ing]router found
I (2886) mesh: 916, [SCAN]init rc[30:ae:a4:45:b1:ad,-58], mine:0, voter:0
I (2896) mesh: [SCAN:4/10]rc[128][30:ae:a4:45:b1:ad,-58], self[30:ae:a4:45:b1:ac,-58,reason:0,votes:1,idle][mine:1,voter:1(1.00)percent:0.90][128,1,30:ae:a4:45:b1:ad]

I (3266) mesh: [SCAN][ch:6]AP:6, otherID:0, idle:0, mAP:1, root:0, top mAP:0[Layer:0/1.ing]router found
I (3266) mesh: 916, [SCAN]init rc[30:ae:a4:45:b1:ad,-52], mine:0, voter:0
I (3276) mesh: [SCAN:5/10]rc[128][30:ae:a4:45:b1:ad,-52], self[30:ae:a4:45:b1:ac,-52,reason:0,votes:1,idle][mine:1,voter:1(1.00)percent:0.90][128,1,30:ae:a4:45:b1:ad]

I (3646) mesh: [SCAN][ch:6]AP:6, otherID:0, idle:0, mAP:1, root:0, top mAP:0[Layer:0/1.ing]router found
I (3656) mesh: 916, [SCAN]init rc[30:ae:a4:45:b1:ad,-41], mine:0, voter:0
I (3656) mesh: [SCAN:6/10]rc[128][30:ae:a4:45:b1:ad,-41], self[30:ae:a4:45:b1:ac,-41,reason:0,votes:1,idle][mine:1,voter:1(1.00)percent:0.90][128,1,30:ae:a4:45:b1:ad]

I (4036) mesh: [SCAN][ch:6]AP:4, otherID:0, idle:0, mAP:1, root:0, top mAP:0[Layer:0/1.ing]router found
I (4036) mesh: 916, [SCAN]init rc[30:ae:a4:45:b1:ad,-42], mine:0, voter:0
I (4036) mesh: [SCAN:7/10]rc[128][30:ae:a4:45:b1:ad,-42], self[30:ae:a4:45:b1:ac,-42,reason:0,votes:1,idle][mine:1,voter:1(1.00)percent:0.90][128,1,30:ae:a4:45:b1:ad]

I (4416) mesh: [VOTE][ch:6]AP:3, otherID:0, idle:0, mAP:1, root:0, [Layer:1]router found
I (4416) mesh: 2626<MESH_NEW_ROOT_VOTE_DONE>MESH_VOTE_STOP_FROM_HEALING, s_vote_scan_times:0
ets Jun  8 2016 00:22:57

`

**# And here's the connected log after i do reset?**
`I (1305) mesh_main: <MESH_EVENT_STARTED>ID:77:77:77:77:77:77
W (1305) mesh: [mesh_set_io_process,1359] MESH_IO_CFG_SELF_ORGANIZED
W (1305) mesh: [mesh_nwk_task_main,3102] <MESH_NWK_IO_CFG>MESH_IO_CFG_SELF_ORGANIZED
I (1315) mesh: <3141>self organized disabled
I (1315) mesh: [SCAN][ch:6]AP:1, otherID:0, idle:0, mAP:1, root:0, top mAP:0[Layer:0/0.ing]router found
I (1325) mesh_main: mesh starts successfully, heap:193940, root not fixed

I (1325) mesh: 916, [SCAN]init rc[30:ae:a4:45:b1:ad,-54], mine:0, voter:0
I (1335) mesh: 952, vote myself, router rssi:-54 > voted rc_rssi:-120
I (1345) mesh: [SCAN:1/10]rc[128][30:ae:a4:45:b1:ad,-54], self[30:ae:a4:45:b1:ac,-54,reason:0,votes:1,idle][mine:1,voter:1(1.00)percent:0.90][128,1,30:ae:a4:45:b1:ad]

I (1365) mesh: [SCAN][ch:6]AP:0, otherID:0, idle:0, mAP:0, root:0, top mAP:0[Layer:0/1.ing]
I (1365) mesh: [FAIL][2]root:1, fail:1, normal:0
I (1725) mesh: 2019<scan>self-organized is disabled, users shall read out scan results by themselves.
I (1725) mesh_main: <MESH_EVENT_SCAN_DONE>number:8
I (1725) mesh_main: [0]WiFi Link Studio, 98:de:d0:4a:63:68, channel:6, rssi:-90
I (1735) mesh_main: [1]SMWIFI, 00:17:7c:7e:22:a1, channel:6, rssi:-91
I (1745) mesh_main: [2]VEGG, 28:3b:82:65:b7:19, channel:6, rssi:-52
I (1745) mesh_main: [3]DIGISOL, 00:17:7c:6b:fb:42, channel:6, rssi:-94
I (1755) mesh_main: [4]jp consultancy, 00:1e:a6:a8:5e:00, channel:6, rssi:-90
I (1765) mesh_main: [5], 00:17:7c:6b:fb:43, channel:6, rssi:-91
I (1775) mesh_main: [6]ARIZONA, ec:01:ee:bc:c7:19, channel:6, rssi:-90
I (1775) mesh_main: [7]GMB GROUP, 00:17:7c:7e:55:c6, channel:6, rssi:-91
W (1785) mesh_main: no parent found, enable self-organized networking.
I (2155) mesh: [SCAN][ch:6]AP:8, otherID:0, idle:0, mAP:1, root:0, top mAP:0[Layer:0/1.ing]router found
I (2155) mesh: 916, [SCAN]init rc[30:ae:a4:45:b1:ad,-52], mine:0, voter:0
I (2165) mesh: [SCAN:2/10]rc[128][30:ae:a4:45:b1:ad,-52], self[30:ae:a4:45:b1:ac,-52,reason:0,votes:1,idle][mine:1,voter:1(1.00)percent:0.90][128,1,30:ae:a4:45:b1:ad]

I (2535) mesh: [SCAN][ch:6]AP:7, otherID:0, idle:0, mAP:1, root:0, top mAP:0[Layer:0/1.ing]router found
I (2535) mesh: 916, [SCAN]init rc[30:ae:a4:45:b1:ad,-50], mine:0, voter:0
I (2545) mesh: [SCAN:3/10]rc[128][30:ae:a4:45:b1:ad,-50], self[30:ae:a4:45:b1:ac,-50,reason:0,votes:1,idle][mine:1,voter:1(1.00)percent:0.90][128,1,30:ae:a4:45:b1:ad]

I (2915) mesh: [SCAN][ch:6]AP:6, otherID:0, idle:0, mAP:1, root:0, top mAP:0[Layer:0/1.ing]router found
I (2915) mesh: 916, [SCAN]init rc[30:ae:a4:45:b1:ad,-50], mine:0, voter:0
I (2925) mesh: [SCAN:4/10]rc[128][30:ae:a4:45:b1:ad,-48], self[30:ae:a4:45:b1:ac,-50,reason:0,votes:1,idle][mine:1,voter:1(1.00)percent:0.90][128,1,30:ae:a4:45:b1:ad]

I (3295) mesh: [SCAN][ch:6]AP:5, otherID:0, idle:0, mAP:1, root:0, top mAP:0[Layer:0/1.ing]router found
I (3305) mesh: 916, [SCAN]init rc[30:ae:a4:45:b1:ad,-47], mine:0, voter:0
I (3305) mesh: [SCAN:5/10]rc[128][30:ae:a4:45:b1:ad,-47], self[30:ae:a4:45:b1:ac,-47,reason:0,votes:1,idle][mine:1,voter:1(1.00)percent:0.90][128,1,30:ae:a4:45:b1:ad]

I (3685) mesh: [SCAN][ch:6]AP:1, otherID:0, idle:0, mAP:1, root:0, top mAP:0[Layer:0/1.ing]router found
I (3685) mesh: 916, [SCAN]init rc[30:ae:a4:45:b1:ad,-69], mine:0, voter:0
I (3685) mesh: [SCAN:6/10]rc[128][30:ae:a4:45:b1:ad,-69], self[30:ae:a4:45:b1:ac,-69,reason:0,votes:1,idle][mine:1,voter:1(1.00)percent:0.90][128,1,30:ae:a4:45:b1:ad]

I (4065) mesh: [SCAN][ch:6]AP:1, otherID:0, idle:0, mAP:1, root:0, top mAP:0[Layer:0/1.ing]router found
I (4065) mesh: 916, [SCAN]init rc[30:ae:a4:45:b1:ad,-70], mine:0, voter:0
I (4065) mesh: [SCAN:7/10]rc[128][30:ae:a4:45:b1:ad,-70], self[30:ae:a4:45:b1:ac,-70,reason:0,votes:1,idle][mine:1,voter:1(1.00)percent:0.90][128,1,30:ae:a4:45:b1:ad]

I (4445) mesh: [SCAN][ch:6]AP:1, otherID:0, idle:0, mAP:1, root:0, top mAP:0[Layer:0/1.ing]router found
I (4445) mesh: 916, [SCAN]init rc[30:ae:a4:45:b1:ad,-81], mine:0, voter:0
I (4445) mesh: [SCAN:8/10]rc[128][30:ae:a4:45:b1:ad,-81], self[30:ae:a4:45:b1:ac,-81,reason:0,votes:1,idle][mine:1,voter:1(1.00)percent:0.90][128,1,30:ae:a4:45:b1:ad]

I (4825) mesh: [SCAN][ch:6]AP:1, otherID:0, idle:0, mAP:1, root:0, top mAP:0[Layer:0/1.ing]router found
I (4825) mesh: 916, [SCAN]init rc[30:ae:a4:45:b1:ad,-79], mine:0, voter:0
I (4835) mesh: [SCAN:9/10]rc[128][30:ae:a4:45:b1:ad,-79], self[30:ae:a4:45:b1:ac,-79,reason:0,votes:1,idle][mine:1,voter:1(1.00)percent:0.90][128,1,30:ae:a4:45:b1:ad]

I (5205) mesh: [SCAN][ch:6]AP:1, otherID:0, idle:0, mAP:1, root:0, top mAP:0[Layer:0/1.ing]router found
I (5205) mesh: 916, [SCAN]init rc[30:ae:a4:45:b1:ad,-77], mine:0, voter:0
I (5215) mesh: 936, [0]my_vote_num:0, voter_num:0
I (5215) mesh: [SCAN:10/13+extra+]rc[128][30:ae:a4:45:b1:ad,-77], self[30:ae:a4:45:b1:ac,-77,reason:0,votes:1,idle][mine:1,voter:1(1.00)percent:0.90][128,1,30:ae:a4:45:b1:ad]

I (5595) mesh: [SCAN][ch:6]AP:1, otherID:0, idle:0, mAP:1, root:0, top mAP:0[Layer:0/1.ing]router found
I (5595) mesh: 916, [SCAN]init rc[30:ae:a4:45:b1:ad,-76], mine:0, voter:0
I (5595) mesh: [SCAN:11/13+extra+]rc[128][30:ae:a4:45:b1:ad,-76], self[30:ae:a4:45:b1:ac,-76,reason:0,votes:1,idle][mine:1,voter:1(1.00)percent:0.90][128,1,30:ae:a4:45:b1:ad]

I (5975) mesh: [SCAN][ch:6]AP:1, otherID:0, idle:0, mAP:1, root:0, top mAP:0[Layer:0/1.ing]router found
I (5975) mesh: 916, [SCAN]init rc[30:ae:a4:45:b1:ad,-73], mine:0, voter:0
I (5985) mesh: [SCAN:12/13+extra+]rc[128][30:ae:a4:45:b1:ad,-73], self[30:ae:a4:45:b1:ac,-73,reason:0,votes:1,idle][mine:1,voter:1(1.00)percent:0.90][128,1,30:ae:a4:45:b1:ad]

I (6355) mesh: [SCAN][ch:6]AP:1, otherID:0, idle:0, mAP:1, root:0, top mAP:0[Layer:0/1.ing]router found
I (6355) mesh: 916, [SCAN]init rc[30:ae:a4:45:b1:ad,-78], mine:0, voter:0
I (6365) mesh: [SCAN:13/13+extra+]rc[128][30:ae:a4:45:b1:ad,-78], self[30:ae:a4:45:b1:ac,-78,reason:0,votes:1,idle][mine:1,voter:1(1.00)percent:0.90][128,1,30:ae:a4:45:b1:ad]

I (6375) mesh: [DONE]connect to router:VEGG, rssi:-78, 28:3b:82:65:b7:19[layer:1], rc[30:ae:a4:45:b1:ad/-78]
I (12525) wifi: ap channel adjust o:6,1 n:6,2
I (12525) wifi: n:6 2, o:6 0, ap:6 2, sta:6 2, prof:6
I (13505) wifi: state: init -> auth (b0)
I (13515) wifi: state: auth -> assoc (0)
I (13525) wifi: state: assoc -> run (10)
I (13595) wifi: connected with VEGG, channel 6
I (13595) wifi: pm start, type: 0

E (13595) event: invalid static ip
I (13595) mesh_main: <MESH_EVENT_PARENT_CONNECTED>layer:0-->1, parent:28:3b:82:65:b7:19<ROOT>, ID:77:77:77:77:77:77
I (13605) mesh_main: <MESH_EVENT_ROOT_ADDRESS>root address:30:ae:a4:45:b1:ad
I (15625) mesh_main: <MESH_EVENT_ROOT_GOT_IP>sta ip: 192.168.0.9, mask: 255.255.255.0, gw: 192.168.0.1
I (15625) event: sta ip: 192.168.0.9, mask: 255.255.255.0, gw: 192.168.0.1

`

**Comment by yudongchen95** [comment]
BUG

**Comment by akshar001** [comment]
Yes bug has been fixed...

**Comment by rockineagle** [comment]
How ?
