### ISSUE TITLE
addrinfo error: DNS lookup failed err=201 res=0x0

### ISSUE THREAD

**Issue by KryvosheyaIvan** [espressif/esp-idf#2015]
Hello!
I am using example http_request and everything was ok!

But recently I had to choose different Wi-Fi router and I faced the following issue:

`        int err = getaddrinfo(WEB_SERVER, "WEB_PORT", &hints, &res);		

	printf("\n Error getaddrinfo = %d !\n", err);

        if(err != 0 || res == NULL) {
            ESP_LOGE(TAG, "DNS lookup failed err=%d res=%p", err, res);
            vTaskDelay(1000 / portTICK_PERIOD_MS);
            continue;
        }`

It prints out:
`E (71016) example: DNS lookup failed err=201 res=0x0`

And I have no idea what is it a problem and how to solve it!
Also i have noy founded 201 error code in the Internet as well as in the getaddrinfo declaration.
Can anyone help me?

**Comment by negativekelvin** [comment]
https://gcc.gnu.org/onlinedocs/gcc-4.8.5/cpp/Stringification.html

**Comment by KryvosheyaIvan** [comment]
@negativekelvin, please explain how it can help me?
I mean how it relates to my problem?

**Comment by igrr** [comment]
You are passing literally "WEBPORT" for the port, there is no macro expansion happening.

**Comment by FayeY** [comment]
Hi, did the above suggestion help you resolve the issue?

**Comment by KryvosheyaIvan** [comment]
@FayeY , yes! Thank you!
