### ISSUE TITLE
RAM constaints

### ISSUE THREAD

**Issue by hvishu** [espressif/esp-idf#2016]
In our project with ESP32 WROOM module (using IDF 3.0 release), we are using BLE+MQTT.  While using it we faced some RAM constraints.  Looking at online help, we got information that
CONFIG_MBEDTLS_SSL_MAX_CONTENT_LEN can be changed to 4900 from 16384.  Things are working fine with this value, could you let us know what could be the side effects lowering value?

The second Question is that for OTA "binary is received over https protocol from AWS S3 bucket."  So we need to use https, with this value of 4900 is not working, 16384 works.  In the final product all three BLE+MQTT+HTTPS required to be present, but we don't need them working together.  i.e  when OTA starts, BLE not required.  We are not sure how to release the RAM allocated to BLE (from this CONFIG_BT_RESERVE_DRAM=0x10000, it seems it is reserved) when OTA starts.
Please give your suggestions.  Also, do let us know if you required more information.

**Comment by chegewara** [comment]
Have you free some of RAM from classic bluetooth (only if you dont use it):
esp_bt_controller_mem_release(ESP_BT_MODE_CLASSIC_BT);

**Comment by mahavirj** [comment]
@hvishu 

- TLS maximum fragment length gets negotiated between client and server (with help of extension). It is recommended to modify default value (16384) only if you have control over both server and client side. Please note that AWS supports 16384, so it will not work if you modify this value.
- During OTA, you may disable Bluetooth completely (non-reversible operation) using `esp_bt_controller_deinit` followed up by freeing up (approx 70K) memory using  `esp_bt_controller_mem_release` [refer_here](https://esp-idf.readthedocs.io/en/latest/api-reference/bluetooth/controller_vhci.html#_CPPv229esp_bt_controller_mem_release13esp_bt_mode_t)

**Comment by hvishu** [comment]
Thank you will try these and let you know if face any problems.
