### ISSUE TITLE
Rebooting ESP32 again and again

### ISSUE THREAD

**Issue by MagicOAk** [espressif/esp-idf#2017]
Whenever I am adding WiFi.begin in my code I'm getting this error- 

Guru Meditation Error: Core  1 panic'ed (IllegalInstruction)
. Exception was unhandled.
Core 1 register dump:
PC      : 0x400d188d  PS      : 0x00060230  A0      : 0x00000000  A1      : 0x3ffda070  
A2      : 0x000003e8  A3      : 0x3ffc38c4  A4      : 0x00000000  A5      : 0x00000000  
A6      : 0x00000000  A7      : 0x00000000  A8      : 0x800d188d  A9      : 0x3ffda050  
A10     : 0x0000000a  A11     : 0x4d87aef6  A12     : 0x3ffc4194  A13     : 0x3ffda050  
A14     : 0x00003a98  A15     : 0x3ffda030  SAR     : 0x0000000a  EXCCAUSE: 0x00000000  
EXCVADDR: 0x00000000  LBEG    : 0x4000c2e0  LEND    : 0x4000c2f6  LCOUNT  : 0xffffffff  

Backtrace: 0x400d188d:0x3ffda070 0x7ffffffd:0x3ffda0b0

Rebooting...
ets Jun  8 2016 00:22:57

**Comment by me-no-dev** [comment]
Please submit this to the [Arduino](https://github.com/espressif/arduino-esp32) repository instead.
And I have to say that WiFi.begin is working fine, so maybe get [EspExceptionDecoder](https://github.com/me-no-dev/EspExceptionDecoder) and decode that stack trace to help us help you debug this issue.
