### ISSUE TITLE
[TW#12286] make monitor fails

### ISSUE THREAD

**Issue by shtirlic** [espressif/esp-idf#202]
```
make monitor
Usage: miniterm.py [options] [port [baudrate]]

miniterm.py: error: no such option: --raw
make: *** [monitor] Error 2
```
```
uname -a
16.3.0 Darwin Kernel Version 16.3.0: Thu Nov 17 20:23:58 PST 2016; root:xnu-3789.31.2~1/RELEASE_X86_64 x86_64

```
```
python --version
Python 2.7.13

```

**Comment by negativekelvin** [comment]
Maybe update pyserial?

**Comment by seopyoon** [comment]
I navigated to the makefile, located at ```esp-idf/components/esptool_py/Makefile.projbuild``` and deleted ```--raw``` towards the very bottom and it works.  

```make monitor``` failure did not happen on my Mac, but happened on Ubuntu running on Virtualbox on Windows machine.

**Comment by projectgus** [comment]
@seopyoon which version of Ubuntu, and which version of pyserial do you have? On Ubuntu, you should be able to check this with `dpkg -l python-serial`

**Comment by cmason1978** [comment]
This is also failing for me and updating pyserial to 2.7 fixed it!  Thanks @negativekelvin !

**Comment by projectgus** [comment]
Thanks for letting us know. The `--raw` option is necessary on newer pyserial otherwise the colour highlighting from log output is not rendered properly. However we should add a note to the README about this error and what causes it.

**Comment by grisevg** [comment]
How to upgrade `python-serial` to 2.7 on Ubuntu 14.04?
Latest package in 14.04 repository is `pyserial 2.6-1build1`

**Comment by projectgus** [comment]
This error should be taken care of now:

* "make monitor" will use idf_monitor.py not miniterm monitor, only "simple_monitor" uses miniterm.
* [requirements.txt file](https://github.com/espressif/esp-idf/blob/master/requirements.txt#L8) requires pyserial v3.0 or newer, which will support the `--raw` argument on miniterm.py.

Upgrading pyserial is the solution - either via pip, or via distribution package manager for Linux users.
