### ISSUE TITLE
SD card can only be initialized after flashing (using WROVER KIT)

### ISSUE THREAD

**Issue by adherent88** [espressif/esp-idf#2025]
## Environment

- Development Kit:      ESP32-Wrover-Kit
- Core (if using chip or module): [ESP32-Wrover-I]
- IDF version: latest release
- Development Env:		[Eclipse]
- Operating System:		[Windows]
- Power Supply:         [USB]

## Problem Description
The SD card can only be initialized if I first flashed the chip. Without flashing, if I simply power off then power on the board, SD card cannot be initialized with the following error:

`SD Card: Initializing SD card`
`SD Card: Using SDMMC peripheral`
`sdmmc_cmd: sdmmc_card_init: send_scr (1) returned 0x109`
`vfs_fat_sdmmc: sdmmc_card_init failed 0x(109)`
`SD Card: Failed to initialize the card (ESP_ERR_INVALID_CRC). Make sure SD card lines have pull-up resistors in place`

Now if I want to program properly wok I have to flash ESP32 each time even there is no change in the firmware......

I assume it has something to do with the bootstrapping pin GPIO2 and GPIO12, as stated in the SD card example:

> GPIO2 pin is used as a bootstrapping pin, and should be low to enter UART download mode. One way to do this is to connect GPIO0 and GPIO2 using a jumper, and then the auto-reset circuit on most development boards will pull GPIO2 low along with GPIO0, when entering download mode.

> GPIO12 is used as a bootstrapping pin to select output voltage of an internal regulator which powers the flash chip (VDD_SDIO). This pin has an internal pulldown so if left unconnected it will read low at reset (selecting default 3.3V operation). 

Can someone point me out how should I solve this issue?

Thanks!

**Comment by adherent88** [comment]
@igrr 

thanks for the reply. I inserted some codes to print out all 5 GPIO pin level before and after SD card initialization.(I also checked the voltage, it is consistent with my printouts)

In the working case (download mode): 
all 5 pins are at high level.

In the failing case(simply reset, without flashing):
before initialization:
`
[0;32mI (10288) SD Card: Level of GPIO_NUM_2 = 0[0m
[0;32mI (10298) SD Card: Level of GPIO_NUM_4 = 1[0m
[0;32mI (10298) SD Card: Level of GPIO_NUM_12 = 1[0m
[0;32mI (10298) SD Card: Level of GPIO_NUM_13 = 1[0m
[0;32mI (10308) SD Card: Level of GPIO_NUM_15 = 1[0m
`
after initialization:
`
[0;32mI (10438) SD Card: Level of GPIO_NUM_2 = 1[0m
[0;32mI (10438) SD Card: Level of GPIO_NUM_4 = 1[0m
[0;32mI (10448) SD Card: Level of GPIO_NUM_12 = 1[0m
[0;32mI (10448) SD Card: Level of GPIO_NUM_13 = 0[0m
[0;32mI (10458) SD Card: Level of GPIO_NUM_15 = 1[0m
`
Before initialization I added the following:
`
gpio_set_pull_mode(all 5 gpio pins, GPIO_PULLUP_ONLY); 
gpio_pullup_en(all 5 gpio pins);

    gpio_set_level(GPIO_NUM_2, 1);
    gpio_set_level(GPIO_NUM_13, 1);
`

And I did not force GPIO2 to low anywhere in my code. Strangely sometimes I can see the level of gpio2 or 13 are also low after flashing, but SD card initialization still succeeds. 

Any hint? Thanks.

**Comment by igrr** [comment]
Please verify that your PC terminal software is not setting DTR/RTS levels such that GPIO2 is pulled low by the auto-download circuit. Setting DTR=1 RTS=1 or DTR=0 and RTS=0 should work.

**Comment by adherent88** [comment]
You are right, thanks a lot!

After enabling DTR and RTS, SD card could be correctly initialized after reset.
