### ISSUE TITLE
[TW#23299] ESP32D0WDQ6 (revision 1) in AP Mode can't see the network

### ISSUE THREAD

**Issue by Agusss19** [espressif/esp-idf#2034]
I had that esp32 chip and i follow the tutorial "simple_wifi" to put microcontroller in APMode, but i can see the network. Sorry for my English.

**Comment by liuzfesp** [comment]
Hi @Agusss19 everything looks good for me, could you change the "WiFi SSID" via the menuconfig and try again please? If it still not work, please help to paste the sdkconfig, IDF commit ID, and log here, then I can analyze it.

**Comment by liuzfesp** [comment]
@Agusss19 any feedback about this issue?

**Comment by FayeY** [comment]
Closing due to lack of response, please feel free to reopen if this is still an issue and you can supply more details.
Thanks.
