### ISSUE TITLE
i2c_ack_type_t I2C_MASTER_ACK mismatch with ACK_EN in i²C examples/

### ISSUE THREAD

**Issue by ShellAddicted** [espressif/esp-idf#2037]
## Environment

- Development Kit: ESP32-DevKitC
- Kit version: revision 1
- Core (if using chip or module): ESP32D0WDQ6
- IDF version: d441dd32
- Development Env:		other 
- Operating System:		Arch
- Power Supply:         USB 5V

## Problem Description
Checking i2c examples I see that to enable acknoledgement ACK_EN(ABLE) is equal to 0x01
instead i2c_ack_type_t (I2C_MASTER_ACK) [here](https://github.com/espressif/esp-idf/blob/master/components/driver/include/driver/i2c.h) is equal to 0x00

working with an i²c device (PCA9685) if i disconnect the device while i²c is active (to cause error).
with I2C_MASTER_ACK (0x00) -> i don't get any error (return of i2c_master_cmd_begin() == 0)
with I2C_MASTER_NACK (0x01) > i get an error as expected
shouldn't be the opposite?

**Comment by negativekelvin** [comment]
https://github.com/espressif/esp-idf/blob/master/examples/peripherals/i2c/main/i2c_example_main.c#L154-L156

Can you be more specific in what values and lines of source code you are referring to?
