### ISSUE TITLE
[TW#23305] References to non-existant function esp_http_client_finalize_open()

### ISSUE THREAD

**Issue by nkolban** [espressif/esp-idf#2040]
If we study the documentation of the esp_http_client component found here:

http://esp-idf.readthedocs.io/en/latest/api-reference/protocols/esp_http_client.html

And search it for "esp_http_client_finalize_open", we will find references to this function which is not documented and/or doesn't exist.

**Comment by tuanpmt** [comment]
Hi @nkolban 

This function renamed to `esp_http_client_fetch_headers`, but the document still has the old name. We will revise the document soon.

Thanks
