### ISSUE TITLE
[TW#23308] prf_defs.h not found

### ISSUE THREAD

**Issue by kashyap-ravichandran97** [espressif/esp-idf#2044]
Hey, I am trying to create a bluetooth HID mouse. I tried to use the code present under tools>sdk>include>bluedroid>hid_le_prf.h

However when i try to compile the code, the IDE throws an error saying that prf_defs.h is not a valid file or header.
what am i doing wrong?
Hardware:

Board: ESP32 Dev Module
Core Installation/update date: 06-06-2018
-I-DE name: Arduino IDE
Flash Frequency: 80Mhz
Upload Speed: 921600

I am redirected from : https://github.com/espressif/arduino-esp32/issues/1479

**Comment by Weijian-Espressif** [comment]
This header is deprecated, please refer to our BLE HID device demo in IDF.
