### ISSUE TITLE
Raspbian hello_world project not working

### ISSUE THREAD

**Issue by Bobrow** [espressif/esp-idf#2045]
## Environment

- Development Kit:      HiLetGo ESP-WROOM32
- Core (if using chip or module): ESP-WROOM32
- IDF version Latest
- Development Env:		Make
- Operating System:		Raspbian
- Power Supply:         USB

## Problem Description

When I go to run `make menuconfig` on the hello_world project it tells me this:
`Makefile:8: /make/project.mk: No such file or directory
make: *** No rule to make target '/make/project.mk'.  Stop.`

### Expected Behavior

It should just build and show the menu

### Steps to repropduce

follow the getting started wiki

**Comment by negativekelvin** [comment]
Check your IDF_PATH

**Comment by FayeY** [comment]
Hi @Bobrow , did the above suggestion help you resolve the issue?
