### ISSUE TITLE
Any socket examples for PPPoS?

### ISSUE THREAD

**Issue by sarpdaltaban** [espressif/esp-idf#2046]
PPPoS example is clearly working; however, 
     when I try to open socket as a SERVER, clients return incorrect ACK number,
     when I try to act as a CLIENT, I can send data till ppp_output_callback buffer stucks at the size 584,

Do you have any PPPoS socket example that works with/without RTOS?

**Comment by xiongyumail** [comment]
Hi,
There's a good project here!<https://github.com/loboris/ESP32-PPPOS-EXAMPLE.git>

**Comment by sarpdaltaban** [comment]
Sir, thank you very much, I am working on the example.

Sent from Mail for Windows 10
