### ISSUE TITLE
[TW#23418] cannot wake up using touch pad

### ISSUE THREAD

**Issue by infotrino** [espressif/esp-idf#2052]
## Environment

- Development Kit:      ESP32-Wrover : custom board from infotron
- Kit version : v1
- Core (if using chip or module): ESP32-Wrover
- IDF version (``git rev-parse --short HEAD`` to get the commit id.): d6ab395
- Development Env:		Make
- Operating System:		Windows
- Power Supply:         USB

## Problem Description
I cannot wake up from light sleep using touch pad (and also from deep sleep).
If I use esp-idf (20180505 version), there is no problem.
So I tried to replace two files to previous version, and problem was solved!
    (1. esp-idf/components/driver/rtc_module.c, 
     2. esp-idf/components/driver/include/driver/touch_pad.h)

### Steps to repropduce
1. copy deep_sleep folder from ''esp-idf/examples/system/deep_sleep''
2. enable touch pad wake up from menu config
3. make flash monitor
4. esp32 goes to deep sleep.  and you cannot wake up from deep sleep using touch pad.

5. roll back two files to previous version (1. esp-idf/components/driver/rtc_module.c, 
     2. esp-idf/components/driver/include/driver/touch_pad.h)
6. recomplie and make flash monitor
7. You can see that problem is solved.  When you touch the pad, esp32 is wake up.

### Code to reproduce this issue
almost same as esp-idf/examples/system/deep_sleep

**Comment by negativekelvin** [comment]
Try calling` touch_pad_set_fsm_mode(TOUCH_FSM_MODE_TIMER);` after  `touch_pad_init();`

**Comment by infotrino** [comment]
That works well. 
Thank you ~

**Comment by negativekelvin** [comment]
Usage note is ok but how about check mode in esp_sleep_enable_touchpad_wakeup and either set or print error?
