### ISSUE TITLE
[TW#23408] Count number of BLE advertising packets (from slave side)

### ISSUE THREAD

**Issue by kaofishy** [espressif/esp-idf#2053]
Hi,

I'm currently trying to implement an Eddystone-TLM beacon using the VHCI interface. One of the requirements of the spec is to embed a count of all advertising packets broadcasted by the beacon since power-up/reboot in each advertising packet. However, I could not find anything in the Core Bluetooth spec that would give me this information, and when I looked into what other BLE vendors do (TI, Nordic Semi etc) they either create their own vender specific HCI event or count the number of times the radio has been active. Is there similar functionality in the ESP32 low level BT stack?

Thanks,
Tony

**Comment by Weijian-Espressif** [comment]
sorry, we do not have the similar functionality in the ESP32, Maybe you can start a timer to calculate the number of  adv packets.
