### ISSUE TITLE
Data from ESP32 to AWS S3

### ISSUE THREAD

**Issue by hiteshpratyushv** [espressif/esp-idf#2058]
Can someone here help me out with code to send data from esp32 to aws s3 storage ?
I am new to aws so any help would be good.

**Comment by negativekelvin** [comment]
> If your issue is a general question, starts similar to "How do I..", or is related to 3rd party development kits/libs, please discuss this on our community forum at esp32.com instead.

**Comment by projectgus** [comment]
As @negativekelvin has quoted from the Issue template, please post questions on the forum instead.
