### ISSUE TITLE
[TW#24197] Ethernet in esp32

### ISSUE THREAD

**Issue by KrrishnaShah** [espressif/esp-idf#2059]
I'm unable to initiate ethernet in esp32 using example code.
I'm using platformIO ESP-IDF sdk for testing Ethernet in esp32.

please guide me through this:
my test code is

	/* ethernet Example

	   This example code is in the Public Domain (or CC0 licensed, at your option.)

	   Unless required by applicable law or agreed to in writing, this
	   software is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
	   CONDITIONS OF ANY KIND, either express or implied.
	*/
	#include <stdio.h>
	#include <string.h>

	#include "freertos/FreeRTOS.h"
	#include "freertos/task.h"

	#include "esp_system.h"
	#include "esp_err.h"
	#include "esp_event_loop.h"
	#include "esp_event.h"
	#include "esp_attr.h"
	#include "esp_log.h"
	#include "esp_eth.h"

	#include "rom/ets_sys.h"
	#include "rom/gpio.h"

	#include "soc/dport_reg.h"
	#include "soc/io_mux_reg.h"
	#include "soc/rtc_cntl_reg.h"
	#include "soc/gpio_reg.h"
	#include "soc/gpio_sig_map.h"

	#include "tcpip_adapter.h"
	#include "nvs_flash.h"
	#include "driver/gpio.h"

	#include "soc/emac_ex_reg.h"
	#include "driver/periph_ctrl.h"

	#include "../../lib/debug/debug.h"
	#include "eth_phy/phy_lan8720.h"

	#define DEFAULT_ETHERNET_PHY_CONFIG phy_lan8720_default_ethernet_config

	#define CONFIG_PHY_ADDRESS  0
	#define PIN_SMI_MDC         23
	#define PIN_SMI_MDIO        18

	static void eth_task(void *pvParameter);
	static void eth_gpio_config_rmii(void);
	static void phy_device_power_enable_via_gpio(bool enable);

	void app_main(void)
	{
		esp_err_t ret = ESP_OK;
		tcpip_adapter_init();
		esp_event_loop_init(NULL, NULL);

		eth_config_t config; // = DEFAULT_ETHERNET_PHY_CONFIG;
		memcpy(&config, &DEFAULT_ETHERNET_PHY_CONFIG, sizeof(eth_config_t));
		/* Set the PHY address in the example configuration */
		config.phy_addr = CONFIG_PHY_ADDRESS;
		config.gpio_config = eth_gpio_config_rmii;
		config.tcpip_input = tcpip_adapter_eth_input;
		config.phy_power_enable = phy_device_power_enable_via_gpio;

	#ifdef CONFIG_PHY_USE_POWER_PIN
		/* Replace the default 'power enable' function with an example-specific
		   one that toggles a power GPIO. */
		config.phy_power_enable = phy_device_power_enable_via_gpio;
	#endif

		ret = esp_eth_init(&config);

		char * prnt = ret == ESP_OK ? "\nesp_eth_init success.\n" : "\nesp_eth_init failed.\n";
		TRACE("%s", prnt);

		if(ret == ESP_OK)
		{
			esp_eth_enable();
			xTaskCreate(eth_task, "eth_task", 2048, NULL, (tskIDLE_PRIORITY + 2), NULL);
		}

	}

	static void eth_task(void *pvParameter)
	{
		tcpip_adapter_ip_info_t ip;
		memset(&ip, 0, sizeof(tcpip_adapter_ip_info_t));
		vTaskDelay(2000 / portTICK_PERIOD_MS);

		while (1)
		{
			vTaskDelay(2000 / portTICK_PERIOD_MS);

			if (tcpip_adapter_get_ip_info(ESP_IF_ETH, &ip) == ESP_OK)
			{
				TRACE("\n~~~~~~~~~~~");
				TRACE("ETHIP:"IPSTR, IP2STR(&ip.ip));
				TRACE("ETHPMASK:"IPSTR, IP2STR(&ip.netmask));
				TRACE("ETHPGW:"IPSTR, IP2STR(&ip.gw));
				TRACE("~~~~~~~~~~~");
			}
		}
	}

	static void eth_gpio_config_rmii(void)
	{
		// RMII data pins are fixed:
		// TXD0 = GPIO19
		// TXD1 = GPIO22
		// TX_EN = GPIO21
		// RXD0 = GPIO25
		// RXD1 = GPIO26
		// CLK == GPIO0
		phy_rmii_configure_data_interface_pins();
		// MDC is GPIO 23, MDIO is GPIO 18
		phy_rmii_smi_configure_pins(PIN_SMI_MDC, PIN_SMI_MDIO);
	}

	static void phy_device_power_enable_via_gpio(bool enable)
	{

	}

	#ifdef CONFIG_PHY_USE_POWER_PIN
	/* This replaces the default PHY power on/off function with one that
	   also uses a GPIO for power on/off.

	   If this GPIO is not connected on your device (and PHY is always powered), you can use the default PHY-specific power
	   on/off function rather than overriding with this one.
	*/
	static void phy_device_power_enable_via_gpio(bool enable)
	{
		assert(DEFAULT_ETHERNET_PHY_CONFIG.phy_power_enable);

		if (!enable) {
			/* Do the PHY-specific power_enable(false) function before powering down */
			DEFAULT_ETHERNET_PHY_CONFIG.phy_power_enable(false);
		}

		gpio_pad_select_gpio(PIN_PHY_POWER);
		gpio_set_direction(PIN_PHY_POWER,GPIO_MODE_OUTPUT);
		if(enable == true) {
			gpio_set_level(PIN_PHY_POWER, 1);
			ESP_LOGD(TAG, "phy_device_power_enable(TRUE)");
		} else {
			gpio_set_level(PIN_PHY_POWER, 0);
			ESP_LOGD(TAG, "power_enable(FALSE)");
		}

		// Allow the power up/down to take effect, min 300us
		vTaskDelay(1);

		if (enable) {
			/* Run the PHY-specific power on operations now the PHY has power */
			DEFAULT_ETHERNET_PHY_CONFIG.phy_power_enable(true);
		}
	}
	#endif

output is:

	16:42:15.736> ets Jun  8 2016 00:22:57
	16:42:15.736> 
	16:42:15.736> rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
	16:42:15.736> configsip: 0, SPIWP:0xee
	16:42:15.736> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
	16:42:15.736> mode:DIO, clock div:2
	16:42:15.736> load:0x3fff0018,len:4
	16:42:15.736> load:0x3fff001c,len:5528
	16:42:15.736> load:0x40078000,len:0
	16:42:15.736> ho 12 tail 0 room 4
	16:42:15.736> load:0x40078000,len:12488
	16:42:15.736> entry 0x40078fd4
	16:42:15.736> [0;32mI (30) boot: ESP-IDF 2.300.0 2nd stage bootloader[0m
	16:42:15.736> [0;32mI (30) boot: compile time 14:53:41[0m
	16:42:15.736> [0;32mI (30) boot: Enabling RNG early entropy source...[0m
	16:42:15.736> [0;32mI (35) boot: SPI Speed      : 40MHz[0m
	16:42:15.736> [0;32mI (39) boot: SPI Mode       : DIO[0m
	16:42:15.736> [0;32mI (43) boot: SPI Flash Size : 4MB[0m
	16:42:15.736> [0;32mI (47) boot: Partition Table:[0m
	16:42:15.736> [0;32mI (50) boot: ## Label            Usage          Type ST Offset   Length[0m
	16:42:15.736> [0;32mI (58) boot:  0 nvs              WiFi data        01 02 00009000 00006000[0m
	16:42:15.736> [0;32mI (65) boot:  1 phy_init         RF data          01 01 0000f000 00001000[0m
	16:42:15.736> [0;32mI (73) boot:  2 factory          factory app      00 00 00010000 00100000[0m
	16:42:15.736> [0;32mI (80) boot: End of partition table[0m
	16:42:15.736> [0;32mI (84) esp_image: segment 0: paddr=0x00010020 vaddr=0x3f400020 size=0x0ad38 ( 44344) map[0m
	16:42:15.736> [0;32mI (109) esp_image: segment 1: paddr=0x0001ad60 vaddr=0x3ffc0000 size=0x01f14 (  7956) load[0m
	16:42:15.736> [0;32mI (112) esp_image: segment 2: paddr=0x0001cc7c vaddr=0x40080000 size=0x00400 (  1024) load[0m
	16:42:15.736> [0;32mI (116) esp_image: segment 3: paddr=0x0001d084 vaddr=0x40080400 size=0x02f8c ( 12172) load[0m
	16:42:15.736> [0;32mI (129) esp_image: segment 4: paddr=0x00020018 vaddr=0x400d0018 size=0x25d58 (154968) map[0m
	16:42:16.339> [0;32mI (187) esp_image: segment 5: paddr=0x00045d78 vaddr=0x4008338c size=0x04a6c ( 19052) load[0m
	16:42:16.339> [0;32mI (195) esp_image: segment 6: paddr=0x0004a7ec vaddr=0x400c0000 size=0x00000 (     0) load[0m
	16:42:16.339> [0;32mI (200) boot: Loaded app from partition at offset 0x10000[0m
	16:42:16.339> [0;32mI (201) boot: Disabling RNG early entropy source...[0m
	16:42:16.339> [0;32mI (206) cpu_start: Pro cpu up.[0m
	16:42:16.339> [0;32mI (209) cpu_start: Starting app cpu, entry point is 0x40080e74[0m
	16:42:16.339> [0;32mI (0) cpu_start: App cpu up.[0m
	16:42:16.339> [0;32mI (220) heap_init: Initializing. RAM available for dynamic allocation:[0m
	16:42:16.339> [0;32mI (227) heap_init: At 3FFAFF10 len 000000F0 (0 KiB): DRAM[0m
	16:42:16.339> [0;32mI (233) heap_init: At 3FFCB790 len 00014870 (82 KiB): DRAM[0m
	16:42:16.339> [0;32mI (239) heap_init: At 3FFE0440 len 00003BC0 (14 KiB): D/IRAM[0m
	16:42:16.339> [0;32mI (245) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM[0m
	16:42:16.339> [0;32mI (252) heap_init: At 40087DF8 len 00018208 (96 KiB): IRAM[0m
	16:42:16.339> [0;32mI (258) cpu_start: Pro cpu start user code[0m
	16:42:16.339> [0;32mI (276) cpu_start: Starting scheduler on PRO CPU.[0m
	16:42:16.339> [0;32mI (0) cpu_start: Starting scheduler on APP CPU.[0m
	16:42:16.339> [0;32mI (463) emac: mac version 1137a[0m
	16:42:16.339> [0;32mI (463) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE[0m
	16:42:16.339> 
	16:42:16.339> esp_eth_init success.
	16:42:16.339> 
	16:42:16.339> [0;32mI (473) emac: emac start !!!
	16:42:16.339> [0m
	16:42:16.339> [0;32mI (473) emac: emac reset done[0m
	16:42:17.092> [0;31mE (1473) emac: Timed out waiting for PHY register 0x2 to have value 0x0007 (mask 0xffff). Current value 0xffff[0m
	16:42:17.984> [0;31mE (2473) emac: Timed out waiting for PHY register 0x3 to have value 0xc0f0 (mask 0xfff0). Current value 0xffff[0m
	16:42:18.983> [0;31mE (3473) emac: Timed out waiting for PHY register 0x2 to have value 0x0007 (mask 0xffff). Current value 0xffff[0m
	16:42:19.983> [0;31mE (4473) emac: Timed out waiting for PHY register 0x3 to have value 0xc0f0 (mask 0xfff0). Current value 0xffff[0m
	16:42:20.983> [0;31mE (5473) emac: Timed out waiting for PHY register 0x2 to have value 0x0007 (mask 0xffff). Current value 0xffff[0m
	16:42:21.985> [0;31mE (6473) emac: Timed out waiting for PHY register 0x3 to have value 0xc0f0 (mask 0xfff0). Current value 0xffff[0m
	16:42:22.983> [0;31mE (7473) emac: Timed out waiting for PHY register 0x2 to have value 0x0007 (mask 0xffff). Current value 0xffff[0m

**Comment by negativekelvin** [comment]
You didn't say anything about hardware or if you verified phy address setting

**Comment by KrrishnaShah** [comment]
My hardware is ESP32-WROM-32
Interfaced with LAN8720  (MDIO-18, MDC-23)
Phyter address is 0.

schematic:
![image](https://user-images.githubusercontent.com/13435158/41358453-1eeebce4-6f48-11e8-8a20-713bc059291d.png)
![image](https://user-images.githubusercontent.com/13435158/41358604-70feb3cc-6f48-11e8-9cd0-5d980ac12ccb.png)

**Comment by sauttefk** [comment]
The problem could be the 74VC04 inverter in your clock signal.

**Comment by KrrishnaShah** [comment]
Dear all,
The above issue has been solved (solution: phyter address = 1).
But Now my device is unable to get IP.
Is there any thing else I've to add to get IP like dhcp_start() or something ?

**Comment by KrrishnaShah** [comment]
I removed 74VC04 and and changed R83 to 0 ohm and shorted. Also changed GPIO0 pull up from 330K to 4.7K.

Still no IP.

I'm unable to find what is the problem.
Please help me !!!

**Comment by versamodule** [comment]
This is what I am using and it works just fine. Code is not cleaned up and used for something else to prototype with, but maybe there is something in there that may help. 
![example](https://user-images.githubusercontent.com/6456652/41548255-f7178004-72e7-11e8-82f0-e5dc259cc986.jpg)
[main.zip](https://github.com/espressif/esp-idf/files/2112055/main.zip)

**Comment by sauttefk** [comment]
@KrrishnaShah: Your schematic does not show a critical part: Is LED2/nINTSEL pulled low so that nINT/
REFCLKO is configured as clock output? (e.g. is the LED connected to GND or VDD?)

From the data sheet:
>  When nINTSEL is floated or pulled toVDD2A, nINT is selected for operation on the nINT/REFCLKO pin (default).
• When nINTSEL is pulled low to VSS, REFCLKO is selected for operation on the nINT/REFCLKO pin.

**Comment by Matheus-Garbelini** [comment]
@sauttefk I wanted to know this also. It appears that REFCLKO or nINT is not used as the same clock from the crystal goes to the esp32 in the GPIO0 pin.

Another thing that I'm corious: for what porpoise there are 2 33Ohms resistors in series with the CLKIN pin? Is something to do with high speed, impedance matching or signal isolation?

**Comment by KrrishnaShah** [comment]
@sauttefk My phyter LED schematic is as : 

![image](https://user-images.githubusercontent.com/13435158/42555183-25e403e0-8507-11e8-9b0a-534369a90044.png)

**Comment by KrrishnaShah** [comment]
Thanks everyone 
The issue has been solved.

Problem:  was the interference in clock and signals , 
Solution: Track redesign and done
