### ISSUE TITLE
[TW#23411] Changing  number of losed beacons before AP kicks off the station

### ISSUE THREAD

**Issue by KryvosheyaIvan** [espressif/esp-idf#2061]
![issue](https://user-images.githubusercontent.com/23324355/41358770-c4089234-6f31-11e8-9f76-5e7ae073b2a9.png)

Hello!
Please tell me where can I change number of losed beacons before AP kicks off the station.

**Comment by liuzfesp** [comment]
Hi @KryvosheyaIvan, we have no API to configure the number of losed beacons before AP kicks off the station. Could you describe the issue in detailed?

**Comment by KryvosheyaIvan** [comment]
Hi @liuzfesp, there many issues on github and questions on esp32.com concerning esp32 specific error
`WIFI_REASON_BEACON_TIMEOUT = 200`
Although, developers of esp-idf are very active and interested in solving problems, there are no solution to that problem at all !
The problem loocks as follows: at first all is ok. WiFi is initialized (and BLE by the way). Then I periodically make request to some server and then, though WiFi signal is good, the 200 error arises followed by 201
`WIFI_REASON_NO_AP_FOUND = 201`. But what is of great concern is that after I get Disconnect event It cant just reconnect by means of `esp_wifi_connect()`. Also, as well as other users I cant reinit wifi because esp32 unexpectedly reboot every time. So in my product I am forced to reboot esp32 by means of `esp_restart()` after several times of unsuccessful attemts to just reconnect. Interesting fact - after rebooting esp32 connects perfectly at the very first attempt. So think that problem is somewhere at the lower level...

**Comment by KryvosheyaIvan** [comment]
@heyinling , I switched off BLE and faced the same problem! It disconnects every 5 minutes. The result the same as it described previously.
How can I find out what IDF commit I use?

**Comment by KryvosheyaIvan** [comment]
@heyinling, Here is IDF commit I use:
c3bec5b103888217d53527924e5185d49f9636ea

**Comment by liuzfesp** [comment]
HI @KryvosheyaIvan just can't reproduce your issue with the commit c3bec5b, could you show me the detailed info of the AP to which the esp32 station is connected? Moreover, does this issue happen if there is no "periodically make request to some server"? Also does this issue happen on one specific board or on every board you have?

**Comment by KryvosheyaIvan** [comment]
@liuzfesp , I founded where was the problem!
It was in using libcurl library: https://github.com/loboris/ESP32_curl_example .
I don`t know whether it was my fault, or it was in library, but when I rewrite the requests using sockets,
the issue gone.
