### ISSUE TITLE
Year 2038 bug.  time_t should be 64bits (currently long / 32bits)

### ISSUE THREAD

**Issue by starlino** [espressif/esp-idf#2066]
time_t  should be  64bits not 32bits 

https://github.com/espressif/esp-idf/blob/4480ab6c8ce70778df4948e587e712540de237eb/components/newlib/include/machine/types.h#L14

following assert fails: 
//check for year 2038 problem - ESP32 fails !!!
static_assert( sizeof(time_t) == sizeof(int64_t), "sizeof(time_t) == sizeof(int64_t)" ); 

See:
https://en.wikipedia.org/wiki/Year_2038_problem

**Comment by negativekelvin** [comment]
https://github.com/espressif/esp-idf/issues/584

**Comment by igrr** [comment]
@starlino This issue is tracked in #584, please follow the link and click "Subscribe" to receive further updates.
