### ISSUE TITLE
API to allow Bluetooth COD (Class-of-Device) to be changed

### ISSUE THREAD

**Issue by gohai** [espressif/esp-idf#2069]
As noted in https://github.com/espressif/arduino-esp32/issues/1304, even the SPP ("Serial") profile is currently using the hard-coded Class-of-Device `BTA_DM_COD_LOUDSPEAKER`, which makes certain hosts - such as macOS - not accept the SPP device.

Could either esp_spp_api.c be changed to automatically use a compatible COD, or, a function be added to the SDK so that the COD can be set to an user-defined value at runtime?

**Comment by negativekelvin** [comment]
https://github.com/espressif/esp-idf/commit/789edc0b52b3a21a7ddd7a47f5d0d7b203eeac4d

**Comment by gohai** [comment]
Thanks @negativekelvin
