### ISSUE TITLE
Why the method "ESP_LOGE()" nerver normality printf the data !?

### ISSUE THREAD

**Issue by xuhongv** [espressif/esp-idf#2075]
![3 myg lg0sg3 d x4e z7](https://user-images.githubusercontent.com/25237870/41575425-eae1bb24-73b4-11e8-859c-19202f7c6574.png)

------------------------------------------------------------------------------------

- 上面的截图是 UDP 发送到 ESP32 ，并且打印在串口数据上，但是我发现和我在这边发送的内容不一样！我尝试换了方法，用 printf（）打印数据，结果是正常的。虽然没有保证了数据准确性，但是没有正常显示出来，这点显示得很不专业！请问这个可以解决吗！？

**Comment by malaimoo** [comment]
这个是因为你的串口工具不支持类似于终端的颜色显示，前面的乱码一样的字母其实是颜色。你尝试在终端里面直接 make monitor 试一下。

**Comment by xuhongv** [comment]
@malaimoo 秒懂！非常感谢 !
