### ISSUE TITLE
Memory leak in 08_nvs_rw_blob example when error situation

### ISSUE THREAD

**Issue by MarkoN-Hexele** [espressif/esp-idf#209]
Function: 
esp_err_t save_run_time(void)

free(run_time) is not called in error cases (err != ESP_OK). Only when read and write are OK.

    // Read previously saved blob if available
    uint32_t* run_time = malloc(required_size + sizeof(uint32_t));
    if (required_size > 0) {
        err = nvs_get_blob(my_handle, "run_time", run_time, &required_size);
        if (err != ESP_OK) return err;
    }

    // Write value including previously saved blob if available
    required_size += sizeof(uint32_t);
    run_time[required_size / sizeof(uint32_t) - 1] = xTaskGetTickCount() * portTICK_PERIOD_MS;
    err = nvs_set_blob(my_handle, "run_time", run_time, required_size);
    if (err != ESP_OK) return err;

    free(run_time);

    // Commit

**Comment by krzychb** [comment]
@MarkoN-Hexele thank you noticing and  documenting this issue.
It has been resolved in 8aa5082baae0db503b1bfb6876b63a03e5d458fc
