### ISSUE TITLE
Function esp_http_client_set_post_field Overrides Content-Type with no checks 

### ISSUE THREAD

**Issue by DavidMora** [espressif/esp-idf#2092]
## Environment

- Development Kit:     Any
- Kit version (for WroverKit/PicoKit/DevKitC): Any
- Core (if using chip or module): Any
- IDF version (``git rev-parse --short HEAD`` to get the commit id.): 
   64ce589f6f6c0013c6d2c59677913c87e3748782 May 22. 
- Development Env:		Any
- Operating System:		Any
- Power Supply:       Any

## Problem Description

Component esp_http_client defines function esp_http_client_set_post_field on line 948 commit 64ce589f6f6c0013c6d2c59677913c87e3748782 May 22. 

The function sets the post field for a request, it always assumes the http body is an application/x-www-form-urlencoded. But there are other options that can be set by using the esp_http_client_set_header option. However, the esp_http_client_set_post_field function has a side-effect of changing this setting if it is set before the call. 

### Expected Behavior

Type detection would be nice, if it is an overkill then document function header to specify this behavior and tell the programmer to call esp_http_client_set_header after the esp_http_client_set_post_field call.

### Actual Behavior

Content-type gets override

### Code on component
```
esp_err_t esp_http_client_set_post_field(esp_http_client_handle_t client, const char *data, int len)
{
    esp_err_t err = ESP_OK;
    client->post_data = (char *)data;
    client->post_len = len;
    ESP_LOGD(TAG, "set post file length = %d", len);
    if (client->post_data) {
        err = esp_http_client_set_header(client, "Content-Type", "application/x-www-form-urlencoded");
    } else {
        client->post_len = 0;
        err = esp_http_client_set_header(client, "Content-Type", NULL);
    }
    return err;
}
```

**Comment by mahavirj** [comment]
@DavidMora 
Also reported here https://github.com/espressif/esp-idf/issues/2047. Fix for this will be available soon in ESP-IDF.

**Comment by DavidMora** [comment]
Thanks :)
