### ISSUE TITLE
[TW#23634] esp_ping API should have a userdata pointer...?

### ISSUE THREAD

**Issue by paulreimer** [espressif/esp-idf#2094]
## Environment

- IDF version (``git rev-parse --short HEAD`` to get the commit id.): 
    4b91c82c

## Problem Description
Using the esp_ping_* API to provide info of whether the network state is good (so application can take action to repair the connection).

### Expected Behavior
There should be a way to provide a user-specified userdata pointer, as well as the callback function pointer. That way the callback can check the userdata, e.g. to send the ping result data somewhere outside of the callback.

### Actual Behavior
There isn't a way to do this with the current esp_ping API.

**Comment by liuzfesp** [comment]
@paulreimer yes, we don't support it. I'm afraid we don't have plan to support this feature in short term.
