### ISSUE TITLE
[TW#23851] Slight inconsistency in pad naming in TRM

### ISSUE THREAD

**Issue by nkolban** [espressif/esp-idf#2099]
Very small stuff ... 

In the Technical Reference Manual (TRM) on page 56 in 4.10 in Table 19 we see the list of pad names in column 2.  Pay attention to the pad names associated with GPIOs 32 through 39.

Now look at the names of the registers beginning IO_MUX_* on page 59 (4.12).  We see that the names of the registers are `IO_MUX_<PadName>_REG` ... except that the names associated GPIOs 32-39 are called 32-39 and not by their pad names.

For example.

We have a register called `IO_MUX_GPIO36_REG` as opposed to a register called `IO_MUX_SENSOR_VP_REG`.  It feels like we are not consistent.

**Comment by negativekelvin** [comment]
The problem is that SENSOR_VP function is in the analog/rtc subsystem so has nothing to do with iomux.  Wouldn't it be more confusing if the register was called IO_MUX_SENSOR_VP_REG since no value of that register is going to cause it to have the SENSOR_VP function?

**Comment by negativekelvin** [comment]
Well it is better to stick with the pad name _when possible_ since in schematics and docs you are more likely to see the pad name.

**Comment by xiongyumail** [comment]
Hi @nkolban 
Thank you for your advice.

In `io_mux_reg.h` we use the `Function 1` to express registers.
Instead of the PAD name.
