### ISSUE TITLE
[TW#23852] Integrate MQTT (espmqtt) library into the framework

### ISSUE THREAD

**Issue by nicola-lunghi** [espressif/esp-idf#2106]
Dear developer, 

I think that having a generic mqtt library in the esp-idf framework could be useful

I just found this and seems good

https://github.com/tuanpmt/espmqtt/

Maybe you can integrate it into the framework and with time rewrite the aws iot library to use this (is more generic)

Regards
Nicola Lunghi

**Comment by FayeY** [comment]
This issue has been solved in the latest master, please have a try.
