### ISSUE TITLE
ISR related code not in IRAM (esp32/crosscore_int.c)

### ISSUE THREAD

**Issue by nathanjel** [espressif/esp-idf#211]
Hello!

I have run into this issue in my program where I extensively use UART and it's interrupts, and at the same time need to do some SPI Flash read/write operations. It crashed with InvalidInstruction during writes, and I traced it back to a piece of code which is being used by the UART interrupt handling code, thru FreeRTOS libraries. It's `void esp_crosscore_int_send_yield(int coreId);` in file [components/esp32/crosscore_int.c](https://github.com/espressif/esp-idf/blob/master/components/esp32/crosscore_int.c).

I have resolved this issue by asking the linker to put the crosscore_int.o module into IRAM. Not sure if the whole module is needed in IRAM, but this works perfectly. Suggest to get the esp-idf updated accordingly - pull request #212 created.

**Comment by igrr** [comment]
Thanks for reporting this issue! We have a fix for it in review, which includes moving the ISR into IRAM using `IRAM_ATTR` and adding a sanity check to esp_intr_alloc. This fix should appear in master today.
