### ISSUE TITLE
using ccache with esp-idf

### ISSUE THREAD

**Issue by nicola-lunghi** [espressif/esp-idf#2114]
Hi all, 

is possible to use ccache to speed up the build?

Thanks
Nicola Lunghi

**Comment by me-no-dev** [comment]
totally you can ;) many of us already use it :)

**Comment by nicola-lunghi** [comment]
ok i managed to create a directory called bin-ccache in the xtensa installation directory and link all the executables in bin to ccache

then I've added the xtensa bin-ccache folder to path before the bin folder itself.

and ccache works perfectly

**Comment by projectgus** [comment]
Hi @nicola-lunghi ,

Just FYI, if you're still using the cmake branch then you should get ccache enabled automatically if it's on your PATH:
https://github.com/espressif/esp-idf/blob/feature/cmake/tools/cmake/idf_functions.cmake#L101

(But setting up links in the way you mention will also work - I have this set on my local system as well.)

Angus
