### ISSUE TITLE
ubuntu Eclipse neon header file issue 

### ISSUE THREAD

**Issue by ahmedawais** [espressif/esp-idf#2117]
I am using Eclipse neon and trying to build a BLE project which send and receive data from andriod phone. for this i am using neil kolban libary of BLE       https://github.com/nkolban/ESP32_BLE_Arduino   
i have added all the necessay header path into the main folder of project and also into C/C++ general path and symbols but still i am getting this error. BLEDevice.h No such file or directory. Bluetooth is enable in menuconfig and paths have been added in both GNU C  and GNU C++. 
![terminal](https://user-images.githubusercontent.com/34267577/42023144-70df6ca6-7abf-11e8-9a7f-5587e1ede543.PNG)
![path](https://user-images.githubusercontent.com/34267577/42023164-79327a74-7abf-11e8-9139-0854ffbab0ea.PNG)
![path2](https://user-images.githubusercontent.com/34267577/42023170-7cf97658-7abf-11e8-9a5d-1f44958313f1.PNG)
![main](https://user-images.githubusercontent.com/34267577/42023177-815c7f92-7abf-11e8-94e5-d4d50a9eabc8.PNG)

please suggest i am a newbie 
thanks

**Comment by Dazza0** [comment]
Did you also copy the ``src`` directory of the repository?

**Comment by ahmedawais** [comment]
I copied the  whole tool chain of esp 32 from github repository. Can
explain a bit ?

**Comment by Dazza0** [comment]
I'm referring to the [src](https://github.com/nkolban/ESP32_BLE_Arduino/tree/master/src) directory in the repo you linked above. ``BLEDevice.h`` doesn't exist in ESP-IDF

**Comment by ahmedawais** [comment]
yes  i copied src directory path and also added its path in Path ans symbols

**Comment by Dazza0** [comment]
Adding the paths to Eclipse has no effect on the build. I suggest you either make those sources a separate component by adding a ``component.mk`` file into the ``src`` directory (see ESP-IDF components for examples), or directly putting those source files in the same directory as your ``main.cpp``

**Comment by FayeY** [comment]
Any update? Is this issue solved now?
