### ISSUE TITLE
[TW#23952] esp_pthread.h not C++ compatible

### ISSUE THREAD

**Issue by snej** [espressif/esp-idf#2121]
[esp_pthread.h](https://github.com/espressif/esp-idf/blob/master/components/pthread/include/esp_pthread.h) is missing the necessary `extern "C"{ ... }` wrapper to be compatible with C++. The result is link errors when you call its functions from C++ code, because the compiler generates mangled names.

(I'm assuming that IDF headers are all meant to be C++ compatible, since this is the only header I've had to use this workaround with.)

#### Workaround:
In your C++ source file, use
```C++
extern "C" {
#include "esp_pthread.h"
}
```

**Comment by suda-morris** [comment]
Thanks for your suggestion, we have fixed this problem, and it will be available soon.
