### ISSUE TITLE
Feature Request: mDNS Service Query callback (IDFGH-264)

### ISSUE THREAD

**Issue by paulreimer** [espressif/esp-idf#2123]
It would be very handy to have a e.g. a new event type in the event loop handler, which is triggered whenever an mDNS service is returned in response to a query from the network.

As an example use-case, using this hook would make it possible to start a service on demand, whenever a specific mDNS service is queried. (So you could have functionality for e.g. an HTTP server, that is always published to mDNS, but the actual server is only activated when it is scanned by another device).

**Comment by liuzfesp** [comment]
Hi @paulreimer, we have no plan to support this event in short time, such as IDF v3.2. We will consider it in future release plan.

**Comment by david-cermak** [comment]
@paulreimer I agree that this feature might be quite useful for some usecases, but since this is pretty old request let me check with you first if this is still something you would find meaningful feature for IDF to support?

**Comment by Alvin1Zhang** [comment]
@paulreimer Thanks for reporting, feel free to reopen if needed, thanks.
