### ISSUE TITLE
[TW#24051] i2s driver problem since esp-idf V3.0

### ISSUE THREAD

**Issue by karawin** [espressif/esp-idf#2124]
## Environment

- Development Env:		[Make]
- Operating System:		[Windows]
- Power Supply:         [USB]

## Problem Description

i2s driver of the latest esp-idf V3.0 and V3.1 with or without the new API use is failing. The sound is distorted and not in the right tone.
Replacing the driver with the one of the V3.0 rc1 to retrieve a good sound on i2s output to an external  dac.
The project used:  https://github.com/karawin/Ka-Radio32

All init and use code checked.
To reproduce, simply recompile the project on a board with a dac.

### Actual Behavior
At least, the same behavior as the old driver.

**Comment by karawin** [comment]
https://github.com/karawin/Ka-Radio32/issues/36

**Comment by costaud** [comment]
@karawin
Hi, did you try the example in idf? https://github.com/espressif/esp-idf/tree/master/examples/peripherals/i2s_adc_dac

**Comment by karawin** [comment]
The problem is not the i2s itself but with the new API pushing a single sample takes too long for a real time decoding.

**Comment by costaud** [comment]
Oh, you are using external DAC, sorry for the misleading.

**Comment by karawin** [comment]
No problem, the bug is the same (and worst) with the embedded DAC.

**Comment by karawin** [comment]
I close this issue because it is partially wrong. It is only a problem of performance when sending a single sample at a time.
Too bad, but with a little buffering, it is ok.
