### ISSUE TITLE
[TW#24052] no SYSTEM_EVENT_STA_DISCONNECTED on continuous WIFI_SCAN_TYPE_PASSIVE (background)

### ISSUE THREAD

**Issue by hchaudhary1** [espressif/esp-idf#2125]
## Environment
- Development Kit:      ESP32-PICO-Kit
- IDF version v3.0 and v3.1
- Development Env: Make
- Operating System: Windows
- Power Supply: USB

## Problem Description

Tested on v3.0 and v3.1, SYSTEM_EVENT_STA_DISCONNECTED not received while doing continuous "background" wifi scans. As the scans are running, and I pull the plug on my connected access point (router), I do NOT get the SYSTEM_EVENT_STA_DISCONNECTED event.

### Expected Behavior
When the AP is powered off, the should get SYSTEM_EVENT_STA_DISCONNECTED callback.

### Actual Behavior
While continuously running "WIFI_SCAN_TYPE_PASSIVE" while connected to my access point, I do not get the SYSTEM_EVENT_STA_DISCONNECTED callback when the AP is powered off.

### Steps to repropduce

1. connect to your AP in station mode
2. create a new thread that is continuously running WIFI_SCAN_TYPE_PASSIVE
3. after 5 seconds, power off your AP

**Comment by XinDeng11** [comment]
Hi @hchaudhary1, this is due to start scan continuously would infulence the judge of update connected beacon, and we still can not found a better way to workaround in driver, may be you can start the scan per a while rather than everytime, this would be better

**Comment by hchaudhary1** [comment]
@XinDeng11 
Ok. Another option is to use promiscuous mode call back and look at the beacon packets manually.

**Comment by XinDeng11** [comment]
@negativekelvin yes， you are right, and that's what we have done in our scan mechnaism after connect. However, hchaudhary1 issue not relate to this

**Comment by negativekelvin** [comment]
@XinDeng11 if that's what it does then why doesn't it emit SYSTEM_EVENT_STA_DISCONNECTED after beacon timeout and reassoc fail?

**Comment by XinDeng11** [comment]
@negativekelvin that because user's continuously scan would influence our connected beacon update. however, the scan per a while didn't influence

**Comment by negativekelvin** [comment]
@XinDeng11 it doesn't make sense, if "scan 1 channel in between 1 (or 2) beacon intervals, then return to AP channel for beacon, then scan next channel. If STA misses too many beacons it has to reassoc or disconnect" then why does it matter if continuous or not?

**Comment by XinDeng11** [comment]
@negativekelvin our scan would come back to home channel for a few time after scan one channel before scan next channel after connected. But why continuous scan can cause that phenmenon and per a while not is relate to our detail and secret, I couldn't tell you more.

**Comment by negativekelvin** [comment]
Secret bug. Ok don't tell me just fix it.

**Comment by hchaudhary1** [comment]
ESP team, I understand that this is not fixable, however, the RST documentation should at least be updated to cover this. Thanks

**Comment by negativekelvin** [comment]
There is no overlap with https://github.com/espressif/esp32-wifi-lib/commit/a1f6b6716ece17153596e57e0294366bb8a217ba ? I don't know why there can't be a timer to expire the station at a higher level. There is no way to poll or get callback from low level beacon report?

**Comment by XinDeng11** [comment]
The change in the a1f6b67 have no relationship with this issue, it is another bug.

**Comment by zavovi** [comment]
Hi,
please is this now fixed? Is it possible scan WiFi networks, when the device is connected to the AP?

Thank you.
Vilem
