### ISSUE TITLE
[TW#24053] Guru Meditation Error with release version (wifi power save example)

### ISSUE THREAD

**Issue by infotrino** [espressif/esp-idf#2127]
## Environment

- Development Kit:    custom board from infotron (Wrover)
- Core (if using chip or module): ESP32-Wrover
- IDF version: v3.1-beta
- Development Env:		Make
- Operating System:		Windows
- Power Supply:         USB

## Problem Description
If I compile "wifi power save example" as release version, I meet guru meditation error.
(No problem with debug version)

### Steps to repropduce
1.  copy power_save from example folder
2. make menu config: debug --> release

### monitor error report
rst:0x1 (POWERON_RESET),boot:0x33 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:5616
ho 0 tail 12 room 4
load:0x40078000,len:6568
ho 0 tail 12 room 4
load:0x40080000,len:7056
0x40080000: _iram_start at D:/ghlee/18.esp32/esp-idf/components/freertos/xtensa_vectors.S:1685

entry 0x40080384
0x40080384: _UserExceptionVector at ??:?

I (32) boot: ESP-IDF v3.1-beta1-dirty 2nd stage bootloader
I (32) boot: compile time 12:03:18
I (38) boot: Enabling RNG early entropy source...
I (38) boot: SPI Speed      : 40MHz
I (41) boot: SPI Mode       : DIO
I (45) boot: SPI Flash Size : 4MB
I (50) boot: Partition Table:
I (53) boot: ## Label            Usage          Type ST Offset   Length
I (60) boot:  0 nvs              WiFi data        01 02 00009000 00004000
I (68) boot:  1 otadata          OTA data         01 00 0000d000 00002000
I (75) boot:  2 phy_init         RF data          01 01 0000f000 00001000
I (83) boot:  3 factory          factory app      00 00 00010000 001a0000
I (90) boot:  4 ota_0            OTA app          00 10 001b0000 000b0000
I (98) boot:  5 ota_1            OTA app          00 11 00260000 000b0000
I (105) boot: End of partition table
I (109) boot: Defaulting to factory image
I (114) esp_image: segment 0: paddr=0x00010020 vaddr=0x3f400020 size=0x10a64 ( 68196) map
I (147) esp_image: segment 1: paddr=0x00020a8c vaddr=0x3ffb0000 size=0x0375c ( 14172) load
I (153) esp_image: segment 2: paddr=0x000241f0 vaddr=0x3ffb375c size=0x00000 (     0) load
I (154) esp_image: segment 3: paddr=0x000241f8 vaddr=0x40080000 size=0x00400 (  1024) load
0x40080000: _iram_start at D:/ghlee/18.esp32/esp-idf/components/freertos/xtensa_vectors.S:1685

I (163) esp_image: segment 4: paddr=0x00024600 vaddr=0x40080400 size=0x0ba10 ( 47632) load
I (191) esp_image: segment 5: paddr=0x00030018 vaddr=0x400d0018 size=0x5d9cc (383436) map
0x400d0018: _stext at ??:?

I (325) esp_image: segment 6: paddr=0x0008d9ec vaddr=0x4008be10 size=0x046f4 ( 18164) load
0x4008be10: vTaskPlaceOnUnorderedEventList at D:/ghlee/18.esp32/esp-idf/components/freertos/tasks.c:3564

I (333) esp_image: segment 7: paddr=0x000920e8 vaddr=0x400c0000 size=0x00064 (   100) load
I (333) esp_image: segment 8: paddr=0x00092154 vaddr=0x50000000 size=0x00000 (     0) load
I (351) boot: Loaded app from partition at offset 0x10000
I (351) boot: Disabling RNG early entropy source...
I (353) cpu_start: Pro cpu up.
I (356) cpu_start: Starting app cpu, entry point is 0x40081178
0x40081178: call_start_cpu1 at D:/ghlee/18.esp32/esp-idf/components/esp32/cpu_start.c:225

I (0) cpu_start: App cpu up.
I (367) heap_init: Initializing. RAM available for dynamic allocation:
I (373) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM
I (379) heap_init: At 3FFB9BC0 len 00026440 (153 KiB): DRAM
I (386) heap_init: At 3FFE0440 len 00003BC0 (14 KiB): D/IRAM
I (392) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
I (398) heap_init: At 40090504 len 0000FAFC (62 KiB): IRAM
I (405) cpu_start: Pro cpu start user code
I (423) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.
I (513) pm_esp32: Frequency switching config: CPU_MAX: 80, APB_MAX: 80, APB_MIN: XTAL, Light sleep: ENABLED
I (523) wifi: wifi driver task: 3ffc1154, prio:23, stack:4096, core=0
I (523) wifi: wifi firmware version: b65dd05
I (523) wifi: config NVS flash: enabled
I (533) wifi: config nano formating: disabled
I (533) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE
I (543) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE
I (583) wifi: Init dynamic tx buffer num: 32
I (583) wifi: Init data frame dynamic rx buffer num: 32
I (583) wifi: Init management frame dynamic rx buffer num: 32
I (593) wifi: Init static rx buffer size: 1600
I (593) wifi: Init static rx buffer num: 10
I (593) wifi: Init dynamic rx buffer num: 32
I (693) phy: phy_version: 3910, c0c45a3, May 21 2018, 18:07:06, 0, 0
I (693) wifi: mode : sta (30:ae:a4:43:40:40)
I (693) power_save: esp_wifi_set_ps().
I (693) power_save: SYSTEM_EVENT_STA_START
I (703) wifi: Set ps type: 1

I (1063) wifi: n:12 2, o:1 0, ap:255 255, sta:12 2, prof:1
I (2743) wifi: state: init -> auth (b0)
I (2743) wifi: state: auth -> assoc (0)
I (2763) wifi: state: assoc -> run (10)
I (2873) wifi: connected with infotron_office, channel 12
I (2883) wifi: pm start, type: 1

Guru Meditation Error: Core  0 panic'ed (Interrupt wdt timeout on CPU0)
Core 0 register dump:
PC      : 0x40081c4b  PS      : 0x00060134  A0      : 0x8008b99c  A1      : 0x3ffbc160
0x40081c4b: vApplicationSleep at D:/ghlee/18.esp32/esp-idf/components/esp32/pm_esp32.c:507

A2      : 0x00018008  A3      : 0x002a9be5  A4      : 0x3ffb1060  A5      : 0x00000000
A6      : 0x002a9b80  A7      : 0x3ffb4148  A8      : 0x80081c3c  A9      : 0x3ffbc140
A10     : 0x00000117  A11     : 0x3ffb10c0  A12     : 0x00000000  A13     : 0x00000000
A14     : 0x3ff480a4  A15     : 0x8001f880  SAR     : 0x0000000e  EXCCAUSE: 0x00000005
EXCVADDR: 0x00000000  LBEG    : 0x4008b868  LEND    : 0x4008b86f  LCOUNT  : 0x00000000
0x4008b868: xHaveReadyTasks at D:/ghlee/18.esp32/esp-idf/components/freertos/tasks.c:3564
 (inlined by) prvGetExpectedIdleTime at D:/ghlee/18.esp32/esp-idf/components/freertos/tasks.c:2187

0x4008b86f: xHaveReadyTasks at D:/ghlee/18.esp32/esp-idf/components/freertos/tasks.c:3564
 (inlined by) prvGetExpectedIdleTime at D:/ghlee/18.esp32/esp-idf/components/freertos/tasks.c:2187

Backtrace: 0x40081c4b:0x3ffbc160 0x4008b999:0x3ffbc180
0x40081c4b: vApplicationSleep at D:/ghlee/18.esp32/esp-idf/components/esp32/pm_esp32.c:507

0x4008b999: prvIdleTask at D:/ghlee/18.esp32/esp-idf/components/freertos/tasks.c:3564

Core 1 register dump:
PC      : 0x4008b375  PS      : 0x00060b34  A0      : 0x8008b969  A1      : 0x3ffbc8d0
0x4008b375: uxPortCompareSet at D:/ghlee/18.esp32/esp-idf/components/freertos/tasks.c:3564
 (inlined by) vPortCPUAcquireMutexIntsDisabledInternal at D:/ghlee/18.esp32/esp-idf/components/freertos/portmux_i
mpl.inc.h:86
 (inlined by) vPortCPUAcquireMutexIntsDisabled at D:/ghlee/18.esp32/esp-idf/components/freertos/portmux_impl.h:98

 (inlined by) vTaskEnterCritical at D:/ghlee/18.esp32/esp-idf/components/freertos/tasks.c:4254

A2      : 0x3ffb10c8  A3      : 0x3ffb10c8  A4      : 0x3ffb10c0  A5      : 0x3ffb4084
A6      : 0x002a059c  A7      : 0x3ffb4148  A8      : 0x0000cdcd  A9      : 0xb33fffff
A10     : 0x0000abab  A11     : 0x00060b20  A12     : 0x00060b20  A13     : 0x00000001
A14     : 0x0000abab  A15     : 0x00000000  SAR     : 0x0000001d  EXCCAUSE: 0x00000005
EXCVADDR: 0x00000000  LBEG    : 0x4008b868  LEND    : 0x4008b86f  LCOUNT  : 0x00000000
0x4008b868: xHaveReadyTasks at D:/ghlee/18.esp32/esp-idf/components/freertos/tasks.c:3564
 (inlined by) prvGetExpectedIdleTime at D:/ghlee/18.esp32/esp-idf/components/freertos/tasks.c:2187

0x4008b86f: xHaveReadyTasks at D:/ghlee/18.esp32/esp-idf/components/freertos/tasks.c:3564
 (inlined by) prvGetExpectedIdleTime at D:/ghlee/18.esp32/esp-idf/components/freertos/tasks.c:2187

Backtrace: 0x4008b375:0x3ffbc8d0 0x4008b966:0x3ffbc8f0
0x4008b375: uxPortCompareSet at D:/ghlee/18.esp32/esp-idf/components/freertos/tasks.c:3564
 (inlined by) vPortCPUAcquireMutexIntsDisabledInternal at D:/ghlee/18.esp32/esp-idf/components/freertos/portmux_i
mpl.inc.h:86
 (inlined by) vPortCPUAcquireMutexIntsDisabled at D:/ghlee/18.esp32/esp-idf/components/freertos/portmux_impl.h:98

 (inlined by) vTaskEnterCritical at D:/ghlee/18.esp32/esp-idf/components/freertos/tasks.c:4254

0x4008b966: prvIdleTask at D:/ghlee/18.esp32/esp-idf/components/freertos/tasks.c:3564

#####################################################################
sdkconfig file:
/*
 *
 * Automatically generated file; DO NOT EDIT.
 * Espressif IoT Development Framework Configuration
 *
 */
#define CONFIG_ESP32_PHY_MAX_TX_POWER 20
#define CONFIG_TRACEMEM_RESERVE_DRAM 0x0
#define CONFIG_FREERTOS_MAX_TASK_NAME_LEN 16
#define CONFIG_FATFS_LFN_NONE 1
#define CONFIG_TCP_RECVMBOX_SIZE 6
#define CONFIG_FATFS_CODEPAGE_437 1
#define CONFIG_LWIP_ETHARP_TRUST_IP_MAC 1
#define CONFIG_TCP_WND_DEFAULT 5744
#define CONFIG_PARTITION_TABLE_OFFSET 0x8000
#define CONFIG_SPIFFS_USE_MAGIC_LENGTH 1
#define CONFIG_ESPTOOLPY_FLASHSIZE_4MB 1
#define CONFIG_IPC_TASK_STACK_SIZE 1024
#define CONFIG_FATFS_PER_FILE_CACHE 1
#define CONFIG_ESPTOOLPY_FLASHFREQ "40m"
#define CONFIG_MBEDTLS_KEY_EXCHANGE_RSA 1
#define CONFIG_UDP_RECVMBOX_SIZE 6
#define CONFIG_FREERTOS_QUEUE_REGISTRY_SIZE 0
#define CONFIG_MBEDTLS_AES_C 1
#define CONFIG_MBEDTLS_ECP_DP_SECP521R1_ENABLED 1
#define CONFIG_MBEDTLS_GCM_C 1
#define CONFIG_ESPTOOLPY_FLASHSIZE "4MB"
#define CONFIG_HEAP_POISONING_DISABLED 1
#define CONFIG_SPIFFS_CACHE_WR 1
#define CONFIG_BROWNOUT_DET_LVL_SEL_0 1
#define CONFIG_ESP32_WIFI_DYNAMIC_TX_BUFFER 1
#define CONFIG_SPIFFS_CACHE 1
#define CONFIG_INT_WDT 1
#define CONFIG_MBEDTLS_SSL_PROTO_TLS1 1
#define CONFIG_MBEDTLS_ECDSA_C 1
#define CONFIG_ESPTOOLPY_FLASHFREQ_40M 1
#define CONFIG_LOG_BOOTLOADER_LEVEL_INFO 1
#define CONFIG_BTDM_CONTROLLER_PINNED_TO_CORE 0
#define CONFIG_FREERTOS_THREAD_LOCAL_STORAGE_POINTERS 1
#define CONFIG_MBEDTLS_ECDH_C 1
#define CONFIG_MBEDTLS_KEY_EXCHANGE_ELLIPTIC_CURVE 1
#define CONFIG_ESP32_WIFI_STATIC_RX_BUFFER_NUM 10
#define CONFIG_MBEDTLS_SSL_ALPN 1
#define CONFIG_MBEDTLS_PEM_WRITE_C 1
#define CONFIG_LOG_DEFAULT_LEVEL_INFO 1
#define CONFIG_BT_RESERVE_DRAM 0x0
#define CONFIG_FATFS_FS_LOCK 0
#define CONFIG_IP_LOST_TIMER_INTERVAL 120
#define CONFIG_SPIFFS_META_LENGTH 4
#define CONFIG_ESP32_PANIC_PRINT_REBOOT 1
#define CONFIG_MBEDTLS_ECP_DP_BP384R1_ENABLED 1
#define CONFIG_MBEDTLS_ECP_DP_SECP256K1_ENABLED 1
#define CONFIG_CONSOLE_UART_BAUDRATE 115200
#define CONFIG_LWIP_MAX_SOCKETS 10
#define CONFIG_LWIP_NETIF_LOOPBACK 1
#define CONFIG_EMAC_TASK_PRIORITY 20
#define CONFIG_TIMER_TASK_STACK_DEPTH 2048
#define CONFIG_TCP_MSS 1436
#define CONFIG_MBEDTLS_ECP_DP_CURVE25519_ENABLED 1
#define CONFIG_FATFS_CODEPAGE 437
#define CONFIG_ULP_COPROC_RESERVE_MEM 0
#define CONFIG_LWIP_MAX_UDP_PCBS 16
#define CONFIG_ESPTOOLPY_BAUD 115200
#define CONFIG_INT_WDT_CHECK_CPU1 1
#define CONFIG_ADC_CAL_LUT_ENABLE 1
#define CONFIG_FLASHMODE_DIO 1
#define CONFIG_ESPTOOLPY_AFTER_RESET 1
#define CONFIG_OPTIMIZATION_ASSERTIONS_ENABLED 1
#define CONFIG_LWIP_DHCPS_MAX_STATION_NUM 8
#define CONFIG_TOOLPREFIX "xtensa-esp32-elf-"
#define CONFIG_MBEDTLS_ECP_C 1
#define CONFIG_FREERTOS_IDLE_TASK_STACKSIZE 1536
#define CONFIG_MBEDTLS_RC4_DISABLED 1
#define CONFIG_FREERTOS_USE_TICKLESS_IDLE 1
#define CONFIG_CONSOLE_UART_NUM 0
#define CONFIG_ESP32_APPTRACE_LOCK_ENABLE 1
#define CONFIG_ESP32_RTC_CLOCK_SOURCE_INTERNAL_RC 1
#define CONFIG_ESPTOOLPY_BAUD_115200B 1
#define CONFIG_TCP_OVERSIZE_MSS 1
#define CONFIG_FOUR_UNIVERSAL_MAC_ADDRESS 1
#define CONFIG_CONSOLE_UART_DEFAULT 1
#define CONFIG_MBEDTLS_SSL_MAX_CONTENT_LEN 16384
#define CONFIG_NUMBER_OF_UNIVERSAL_MAC_ADDRESS 4
#define CONFIG_ESPTOOLPY_FLASHSIZE_DETECT 1
#define CONFIG_WIFI_LISTEN_INTERVAL 3
#define CONFIG_PARTITION_TABLE_CUSTOM 1
#define CONFIG_TIMER_TASK_STACK_SIZE 3584
#define CONFIG_ESP32_ENABLE_COREDUMP_TO_NONE 1
#define CONFIG_MBEDTLS_X509_CRL_PARSE_C 1
#define CONFIG_LWIP_DHCPS_LEASE_UNIT 60
#define CONFIG_SPIFFS_USE_MAGIC 1
#define CONFIG_TCPIP_TASK_STACK_SIZE 2048
#define CONFIG_TASK_WDT 1
#define CONFIG_MAIN_TASK_STACK_SIZE 3584
#define CONFIG_SPIFFS_PAGE_CHECK 1
#define CONFIG_ESP32_WIFI_TASK_PINNED_TO_CORE_0 1
#define CONFIG_LWIP_MAX_ACTIVE_TCP 16
#define CONFIG_TASK_WDT_TIMEOUT_S 5
#define CONFIG_POWER_SAVE_MIN_MODEM 1
#define CONFIG_INT_WDT_TIMEOUT_MS 300
#define CONFIG_ESPTOOLPY_FLASHMODE "dio"
#define CONFIG_NEWLIB_STDIN_LINE_ENDING_CR 1
#define CONFIG_MBEDTLS_KEY_EXCHANGE_ECDH_RSA 1
#define CONFIG_ESPTOOLPY_BEFORE "default_reset"
#define CONFIG_ADC2_DISABLE_DAC 1
#define CONFIG_LOG_DEFAULT_LEVEL 3
#define CONFIG_FREERTOS_ASSERT_ON_UNTESTED_FUNCTION 1
#define CONFIG_TIMER_QUEUE_LENGTH 10
#define CONFIG_SUPPRESS_SELECT_DEBUG_OUTPUT 1
#define CONFIG_MAKE_WARN_UNDEFINED_VARIABLES 1
#define CONFIG_FATFS_TIMEOUT_MS 10000
#define CONFIG_ESP32_WIFI_DYNAMIC_RX_BUFFER_NUM 32
#define CONFIG_ESP_HTTP_CLIENT_ENABLE_HTTPS 1
#define CONFIG_MBEDTLS_CCM_C 1
#define CONFIG_PM_USE_RTC_TIMER_REF 1
#define CONFIG_SPI_MASTER_ISR_IN_IRAM 1
#define CONFIG_ESP32_PHY_MAX_WIFI_TX_POWER 20
#define CONFIG_ESP32_RTC_CLK_CAL_CYCLES 1024
#define CONFIG_ESP32_WIFI_TX_BA_WIN 6
#define CONFIG_ESP32_WIFI_NVS_ENABLED 1
#define CONFIG_MBEDTLS_ECP_DP_SECP224R1_ENABLED 1
#define CONFIG_LIBSODIUM_USE_MBEDTLS_SHA 1
#define CONFIG_DMA_RX_BUF_NUM 10
#define CONFIG_MBEDTLS_ECP_DP_SECP384R1_ENABLED 1
#define CONFIG_TCP_SYNMAXRTX 6
#define CONFIG_MBEDTLS_KEY_EXCHANGE_ECDHE_ECDSA 1
#define CONFIG_PYTHON "python"
#define CONFIG_MBEDTLS_ECP_NIST_OPTIM 1
#define CONFIG_ESP32_TIME_SYSCALL_USE_RTC_FRC1 1
#define CONFIG_ESPTOOLPY_COMPRESSED 1
#define CONFIG_PARTITION_TABLE_FILENAME "partitions.csv"
#define CONFIG_TCP_SND_BUF_DEFAULT 5744
#define CONFIG_LWIP_DHCP_MAX_NTP_SERVERS 1
#define CONFIG_TCP_MSL 60000
#define CONFIG_MBEDTLS_SSL_PROTO_TLS1_1 1
#define CONFIG_LWIP_SO_REUSE_RXTOALL 1
#define CONFIG_WIFI_SSID "myssid"
#define CONFIG_ESP32_WIFI_RX_BA_WIN 6
#define CONFIG_MBEDTLS_X509_CSR_PARSE_C 1
#define CONFIG_SPIFFS_USE_MTIME 1
#define CONFIG_MBEDTLS_KEY_EXCHANGE_ECDHE_RSA 1
#define CONFIG_LWIP_DHCP_DOES_ARP_CHECK 1
#define CONFIG_SYSTEM_EVENT_TASK_STACK_SIZE 2304
#define CONFIG_BOOTLOADER_VDDSDIO_BOOST_1_9V 1
#define CONFIG_ESP32_DEEP_SLEEP_WAKEUP_DELAY 2000
#define CONFIG_BROWNOUT_DET_LVL 0
#define CONFIG_MBEDTLS_PEM_PARSE_C 1
#define CONFIG_SPIFFS_GC_MAX_RUNS 10
#define CONFIG_ESP32_APPTRACE_DEST_NONE 1
#define CONFIG_MBEDTLS_SSL_PROTO_TLS1_2 1
#define CONFIG_MBEDTLS_KEY_EXCHANGE_DHE_RSA 1
#define CONFIG_ESP32_WIFI_DYNAMIC_TX_BUFFER_NUM 32
#define CONFIG_MBEDTLS_ECP_DP_BP256R1_ENABLED 1
#define CONFIG_MBEDTLS_ECP_DP_SECP224K1_ENABLED 1
#define CONFIG_TASK_WDT_CHECK_IDLE_TASK_CPU1 1
#define CONFIG_ESP32_DEFAULT_CPU_FREQ_MHZ 80
#define CONFIG_MBEDTLS_HARDWARE_AES 1
#define CONFIG_FREERTOS_HZ 100
#define CONFIG_LOG_COLORS 1
#define CONFIG_ESP32_PHY_CALIBRATION_AND_DATA_STORAGE 1
#define CONFIG_STACK_CHECK_NONE 1
#define CONFIG_ADC_CAL_EFUSE_TP_ENABLE 1
#define CONFIG_FREERTOS_ASSERT_FAIL_ABORT 1
#define CONFIG_BROWNOUT_DET 1
#define CONFIG_ESP32_XTAL_FREQ 40
#define CONFIG_MONITOR_BAUD_115200B 1
#define CONFIG_LOG_BOOTLOADER_LEVEL 3
#define CONFIG_MBEDTLS_TLS_ENABLED 1
#define CONFIG_LWIP_MAX_RAW_PCBS 16
#define CONFIG_PM_ENABLE 1
#define CONFIG_MBEDTLS_SSL_SESSION_TICKETS 1
#define CONFIG_SPIFFS_MAX_PARTITIONS 3
#define CONFIG_ESP_ERR_TO_NAME_LOOKUP 1
#define CONFIG_MBEDTLS_SSL_RENEGOTIATION 1
#define CONFIG_ESPTOOLPY_BEFORE_RESET 1
#define CONFIG_ESPTOOLPY_BAUD_OTHER_VAL 115200
#define CONFIG_SPIFFS_OBJ_NAME_LEN 32
#define CONFIG_ESP32_PTHREAD_TASK_PRIO_DEFAULT 5
#define CONFIG_PARTITION_TABLE_MD5 1
#define CONFIG_TCPIP_RECVMBOX_SIZE 32
#define CONFIG_TCP_MAXRTX 12
#define CONFIG_ESPTOOLPY_AFTER "hard_reset"
#define CONFIG_LWIP_SO_REUSE 1
#define CONFIG_ESP32_XTAL_FREQ_40 1
#define CONFIG_DMA_TX_BUF_NUM 10
#define CONFIG_LWIP_MAX_LISTENING_TCP 16
#define CONFIG_FREERTOS_INTERRUPT_BACKTRACE 1
#define CONFIG_WL_SECTOR_SIZE 4096
#define CONFIG_ESP32_DEBUG_OCDAWARE 1
#define CONFIG_TIMER_TASK_PRIORITY 1
#define CONFIG_MBEDTLS_TLS_CLIENT 1
#define CONFIG_MBEDTLS_ECP_DP_SECP256R1_ENABLED 1
#define CONFIG_MONITOR_BAUD 115200
#define CONFIG_ESP32_DEBUG_STUBS_ENABLE 1
#define CONFIG_FREERTOS_CORETIMER_0 1
#define CONFIG_PARTITION_TABLE_CUSTOM_FILENAME "partitions.csv"
#define CONFIG_MBEDTLS_HAVE_TIME 1
#define CONFIG_FREERTOS_CHECK_STACKOVERFLOW_CANARY 1
#define CONFIG_TCP_QUEUE_OOSEQ 1
#define CONFIG_ADC_CAL_EFUSE_VREF_ENABLE 1
#define CONFIG_MBEDTLS_TLS_SERVER 1
#define CONFIG_MBEDTLS_TLS_SERVER_AND_CLIENT 1
#define CONFIG_FREERTOS_ISR_STACKSIZE 1536
#define CONFIG_OPENSSL_ASSERT_DO_NOTHING 1
#define CONFIG_WL_SECTOR_SIZE_4096 1
#define CONFIG_ESP32_WIFI_AMPDU_TX_ENABLED 1
#define CONFIG_MBEDTLS_ECP_DP_SECP192R1_ENABLED 1
#define CONFIG_MBEDTLS_ECP_DP_BP512R1_ENABLED 1
#define CONFIG_MBEDTLS_KEY_EXCHANGE_ECDH_ECDSA 1
#define CONFIG_WIFI_PASSWORD "mypassword"
#define CONFIG_SYSTEM_EVENT_QUEUE_SIZE 32
#define CONFIG_ESP32_WIFI_TX_BUFFER_TYPE 1
#define CONFIG_ESP32_WIFI_AMPDU_RX_ENABLED 1
#define CONFIG_LWIP_LOOPBACK_MAX_PBUFS 8
#define CONFIG_ESP32_DEFAULT_CPU_FREQ_80 1
#define CONFIG_FREERTOS_IDLE_TIME_BEFORE_SLEEP 3
#define CONFIG_SPI_FLASH_ROM_DRIVER_PATCH 1
#define CONFIG_SPIFFS_PAGE_SIZE 256
#define CONFIG_MBEDTLS_ECP_DP_SECP192K1_ENABLED 1
#define CONFIG_TASK_WDT_CHECK_IDLE_TASK_CPU0 1
#define CONFIG_ESP32_PTHREAD_TASK_STACK_SIZE_DEFAULT 3072
#define CONFIG_MONITOR_BAUD_OTHER_VAL 115200
#define CONFIG_NEWLIB_STDOUT_LINE_ENDING_CRLF 1
#define CONFIG_ESPTOOLPY_PORT "com3"
#define CONFIG_SPI_FLASH_WRITING_DANGEROUS_REGIONS_ABORTS 1
#define CONFIG_OPTIMIZATION_LEVEL_RELEASE 1

**Comment by igrr** [comment]
Thanks for the comprehensive report @infotrino. We will have the fix for this soon. In the meantime, you may apply the following change locally to work around the issue:

```patch
From 8878a65bf04ec3925b814532ba91fa181609d36f Mon Sep 17 00:00:00 2001
From: Ivan Grokhotkov <ivan@espressif.com>
Date: Fri, 29 Jun 2018 22:30:32 +0800
Subject: [PATCH] xtensa: make XTHAL_GET_INTERRUPT volatile

---
 components/esp32/include/xtensa/core-macros.h | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/components/esp32/include/xtensa/core-macros.h b/components/esp32/include/xtensa/core-macros.h
index c8f7e3476..c2eb4a646 100644
--- a/components/esp32/include/xtensa/core-macros.h
+++ b/components/esp32/include/xtensa/core-macros.h
@@ -335,7 +335,7 @@
 			__asm__ __volatile__("wsr.intenable %0" :: "a"(__intenable):"memory"); \
 				} while(0)
 # define XTHAL_GET_INTERRUPT()	({ int __interrupt; \
-				__asm__("rsr.interrupt %0" : "=a"(__interrupt)); \
+				__asm__ __volatile__ ("rsr.interrupt %0" : "=a"(__interrupt)); \
 				__interrupt; })
 # define XTHAL_SET_INTSET(v)	do { int __interrupt = (int)(v); \
 			__asm__ __volatile__("wsr.intset %0" :: "a"(__interrupt):"memory"); \
-- 
2.16.0.windows.2

```

**Comment by infotrino** [comment]
That works well.

Thank you igrr.
