### ISSUE TITLE
Kconfiglib 2 can generate much nicer Kconfig docs

### ISSUE THREAD

**Issue by ulfalizer** [espressif/esp-idf#2131]
Hello,

Just as a note, Kconfiglib 2 can generate much nicer Kconfig documentation compared to Kconfiglib 1, including clickable cross-references (Espressif has Kconfiglib 1 in the `docs/` directory).

Example symbol reference page:

![skarmbild fran 2018-06-29 13-34-35](https://user-images.githubusercontent.com/154768/42090394-99e4ff0c-7ba1-11e8-8a3d-e01cf09dbeb8.png)

You can play around with the output at http://docs.zephyrproject.org/reference/kconfig/index.html (warning: heavy page, lots of symbols).

The script that generates those docs is at https://github.com/zephyrproject-rtos/zephyr/blob/master/doc/scripts/genrest.py.

Kconfiglib works well as a standalone Kconfig implementation now too (it's used like that in Zephyr). See https://asciinema.org/a/Q4UNFVPF5zd62KqjrG95mowkG for a demo of the menuconfig.

I also tweaked it to not require those `option env` "bounce" symbols. IIRC, Espressif does that too.

**Comment by ulfalizer** [comment]
CC @igrr

**Comment by igrr** [comment]
Hi @ulfalizer, thanks for info and for awesome work on the library! Our CMake branch (feature/cmake), which is currently in preview status, uses a slightly modified Kconfiglib 2.1.0: https://github.com/espressif/esp-idf/blob/feature/cmake/tools/kconfig_new/kconfiglib.py. (Another copy in docs directory is still there, but will be removed eventually).
New command line tools look very neat!
For GUI and IDE integration we are planning to use configuration server written by @projectgus: https://docs.espressif.com/projects/esp-idf/en/feature-cmake/api-guides/build-system.html#json-configuration-server.

**Comment by ulfalizer** [comment]
Alright, cool!

Kconfiglib now has a globbing `gsource` statement (`T_GSOURCE`) by the way (it was needed to replace a patch to the C tools in Zephyr... seems everyone tweaks Kconfig a bit). Maybe it doesn't cover all the cases needed in Espressif though.

I had never heard of `wordexp(3)` until now to be honest.

Been thinking of adding something like the `walk_menu()` helper. The latest version of `write_autoconf()`  uses a loop over `defined_syms` by the way.

**Comment by ulfalizer** [comment]
Hmm... thinking about it, a better design might've been to have `source` work like `include` in Make and accept glob patterns and multiple files, requiring at least one match.

Could've had an `osource` (optional source) corresponding to `-include` in Make then as well.

Always annoying when you can't change stuff willy-nilly due to backwards compatibility. :P

If you discover any API issues, useful helpers, etc., feel free to submit them upstream.

Closing to despam the issue list. :)

**Comment by projectgus** [comment]
Hi @ulfalizer,

Thanks for getting in touch! Much appreciate your work on kconfiglib.

There are some small tweaks that you may be interested in. I will send you some PRs ASAP.

Regarding `gsource`, that does solve one of our problems. The catch for us is that we still need to support our patched C-based `mconf` (which is patched to have a globbing "source"). However, we can probably patch the C mconf to add an `gsource` keyword, which puts us one step closer to using kconfiglib unpatched. I'll take a look.

Thanks again,

Angus

**Comment by ulfalizer** [comment]
@projectgus 
I've changed the standard `source` to be globbing now (and require some file to match). There's `osource` now as well for when you don't care whether any files match.

See https://github.com/ulfalizer/Kconfiglib/commit/7a428aa415606820a44291f475248b08e3952c4b.

Turned out to be possible to maintain backwards compatibility with some aliases, so that's nice. The new design is better.

**Comment by ulfalizer** [comment]
Finally got around to adding an iteration helper too, thanks to Mitja Horvat (pinkfluid): https://github.com/ulfalizer/Kconfiglib/blob/818478527ea811a85517cbf60d15342b37693321/kconfiglib.py#L1362

**Comment by projectgus** [comment]
Ah, very nice @ulfalizer ! I'm sorry I haven't had time to either send you some PRs or update to upstream now, although it looks like there may be not be anything left for me to send you. :)
