### ISSUE TITLE
symbol 'configMAX_PRIORITIES could not be resolved'

### ISSUE THREAD

**Issue by ahmedawais** [espressif/esp-idf#2139]
i am running the examples on ECLIPSE IDE(neon) on ubuntu but facing the error as symbol 'configMAX_PRIORITIES could not be resolved' can anybody tell what is missing ? Although program is able to build but with error
![clienterror](https://user-images.githubusercontent.com/34267577/42185818-a453ad98-7e4a-11e8-91d0-5fc3b28eab21.PNG)

**Comment by negativekelvin** [comment]
freertos/FreeRTOS.h

**Comment by projectgus** [comment]
Hi @ahmedawais,

If the project builds despite these errors, it means that Eclipse isn't able to parse information out of the build to learn about which header paths are included.

Double check all of the items shown here are set as shown (we recently changed/clarified a couple of these, as well):
https://docs.espressif.com/projects/esp-idf/en/latest/get-started/eclipse-setup.html#project-properties

If you change any setting, you may have to do a clean build of the project to refresh Eclipse's cache of header paths.


Angus

**Comment by chegewara** [comment]
Remember to add {$PROJECT}/build/something(dont remember full path) to your path, its where sdkconfig.h will be stored when you first time build project.

**Comment by ahmedawais** [comment]
Thanks by adding freeRTOS it worked.
