### ISSUE TITLE
hardware validation test (IDFGH-162)

### ISSUE THREAD

**Issue by andrei-ivanov** [espressif/esp-idf#215]
Since there are a lot of cases where the chip/board might have a hardware issue, it would be helpful to have some sort of validation test, maybe something like Memtest86+ is for memory.
One test that I'm interested in particular is regarding the WiFi, which either doesn't work at all or is very unstable. Maybe Bluetooth too...
But I can't say for certain what is the issue, if it's software (see #207), or broken hardware (chip, antennae) or not enough power (I should have, since it's powered both by USB and by a LiPo battery).

What do you think? Is that doable? Or maybe not as useful as I think?

**Comment by FayeY** [comment]
FYI, we are helping our customer review their PCB design now.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, feel free to reopen.
