### ISSUE TITLE
gatt_server_service_table exmaple 

### ISSUE THREAD

**Issue by ahmedawais** [espressif/esp-idf#2150]
is this example implementation BLE ?  if yes the why in void main () they are initializing BT Classic 

ESP_ERROR_CHECK(esp_bt_controller_mem_release(ESP_BT_MODE_CLASSIC_BT));

please explain ?

i need to write a program using BLE whiich can send and receive  floating number and text with time values.i have my own customize android app

**Comment by negativekelvin** [comment]
esp_bt_controller_mem_release **frees** ESP_BT_MODE_CLASSIC_BT memory because it is **not** being used
