### ISSUE TITLE
[TW#24565] PWM - frequency

### ISSUE THREAD

**Issue by Reiner1210** [espressif/esp-idf#2154]
ledc_timer_config_t timer;
memset(&timer, 0, sizeof(timer));
timer.freq_hz = 100;
timer.duty_resolution = 10;
timer.speed_mode = LEDC_HIGH_SPEED_MODE;
timer.timer_num = LEDC_TIMER_0;

I expected that this leads to a 100 Hz frequency, But the result is a 50 Hz frequency. Why the factor 2 ???

**Comment by costaud** [comment]
I've tested your code, but the frequency seems correct according to the logic analyser.

**Comment by FayeY** [comment]
@Reiner1210 , is there any update? Could you provide a test project so we can reproduce your problem?

**Comment by Reiner1210** [comment]
I will retry it - tomorrow

Am 12. Juli 2018 5:21:28 vorm. schrieb FayeY <notifications@github.com>:
> @Reiner1210 , is there any update? Could you provide a test project so we 
> can reproduce your problem?
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.


Mit AquaMail Android
https://www.mobisystems.com/aqua-mail

**Comment by Reiner1210** [comment]
I use the following
	timer.freq_hz = 1000;
	timer.duty_resolution = 10;
	timer.speed_mode = LEDC_HIGH_SPEED_MODE;
	timer.timer_num = LEDC_TIMER_0;
	uint32_t duty = (uint32_t)((float)(1<<timer.duty_resolution) * 0.25f + .5f);

This leads to the following:
![pwm_small](https://user-images.githubusercontent.com/11994659/42675607-20ec40c2-8675-11e8-8f62-ce152d8b231b.jpg)

**Comment by xiongyumail** [comment]
Hi @Reiner1210 ,
Have you changed the frequency when config, Could you provide more code ?

**Comment by Alvin1Zhang** [comment]
@Reiner1210 Could you help provide some updates? Thanks.

**Comment by Alvin1Zhang** [comment]
@Reiner1210 Could you help share if any updates for this issue? Thanks.
