### ISSUE TITLE
[TW#24181] [Question] Brownout flag, Is there register address to read brownout flag after reboot?

### ISSUE THREAD

**Issue by farizadp** [espressif/esp-idf#2155]
Hi,

Is there register bit which is set (non-volatile) by the ESP32 if brownout occurs? And can be read after next reboot?

Regards,
Dion

**Comment by negativekelvin** [comment]
https://github.com/espressif/esp-idf/blob/c4edb2a4398aef32822b1f917157e402cc246e64/components/esp32/include/rom/rtc.h#L95

**Comment by farizadp** [comment]
@negativekelvin : CMIIW. So I can call rtc_get_reset_reason() from application?

Is this flag overwritten by esp_restart_noos() ? Because, the standard rtc_brownout_isr_handler() calls esp_restart_noos().

**Comment by farizadp** [comment]
Anyone can answer my question @FayeY or @negativekelvin  ? What is brownout workaround? Is there newer chip revision already?

**Comment by negativekelvin** [comment]
The brownout "workaround" as I called it IS the rtc_brownout_isr_handler calling esp_restart_noos instead of returning

**Comment by farizadp** [comment]
@negativekelvin :
Do you know whether it is safe to do nvs_write_* inside this isr handler?
Do you also know if there's newer chip revision for PICO-D4?

**Comment by negativekelvin** [comment]
No, and writing to flash in general is probably not a good idea since flash may not operate properly during brownout.
Rev 1 is newest afaik

**Comment by farizadp** [comment]
Is there update regarding this issue?
Is it now possible to get brownout reset cause when brownout occurs?
