### ISSUE TITLE
ulp program compiling issue

### ISSUE THREAD

**Issue by forthe94** [espressif/esp-idf#2157]
## Environment

- Development Kit:      ESP32-DevKitC
- Kit version: v1
- Core: ESP-WROOM32
- IDF version: a3c4325
- Development Env:		Make
- Operating System:	        Linux Mint
- Power Supply:         USB

## Problem Description
I was trying to attach ulp program to wifi manager https://github.com/tonyp7/esp32-wifi-manager. Followed the instruction from Programming Guide, but when I tried to compile it got errors with undefined reference.

## Debug Logs

/home/tetenkov/esp/esp32-wifi-manager/wifi_manager/build/main/libmain.a(baremetal.o):(.literal.init_ulp_program+0x0): undefined reference to `_binary_ulp_main_bin_end'
/home/tetenkov/esp/esp32-wifi-manager/wifi_manager/build/main/libmain.a(baremetal.o):(.literal.init_ulp_program+0x4): undefined reference to `_binary_ulp_main_bin_start'

**Comment by igrr** [comment]
Hi @forthe94, could you please attach the component.mk file of your main component, and also the output of full build with V=1 (`make clean; make V=1`)?

**Comment by forthe94** [comment]
@igrr thank you for answer.
[output.txt](https://github.com/espressif/esp-idf/files/2175556/output.txt)
[component.mk.txt](https://github.com/espressif/esp-idf/files/2175560/component.mk.txt)

**Comment by igrr** [comment]
Please try changing `COMPONENT_EMBED_FILES := <files>` to `COMPONENT_EMBED_FILES += <files>`. ULP binary is embedded here: https://github.com/espressif/esp-idf/blob/a3c43251b4b37bc3ec105a10f2e1413b14420da3/components/ulp/component_ulp_common.mk#L94, so the additional COMPONENT_EMBED_FILES line you have overrides the one set in component_ulp_common.mk.

**Comment by forthe94** [comment]
Thank a lot, that worked out! Спасибо =)!
