### ISSUE TITLE
IP Address in wifi_sta_list_t of stations when esp is in soft_ap mode?

### ISSUE THREAD

**Issue by akshar001** [espressif/esp-idf#2159]
Hello,
Can we add the ip address in wifi_sta_list struct wifi_sta_info_t ?
There should be an very easy way to get it but if it is mentioned in this sturcutre it would be best

**Comment by negativekelvin** [comment]
No it is already in tcpip_adapter_sta_list_t returned by tcpip_adapter_get_sta_list

**Comment by TimXia** [comment]
WiFi and LWIP are different network layer. WiFi is layer2 and LWIP is layer3. They should be seperate.
