### ISSUE TITLE
[TW#24183] openssl - ssl_pm_reload_crt() is incorrectly mapping verify_mode values to mbedtls modes

### ISSUE THREAD

**Issue by chmorgan** [espressif/esp-idf#2163]
The code was treating the verify_mode as a value, it is actually a flag that can consist of several or'ed together values. It was also mapping SSL_VERIFY_FAIL_IF_NO_PEER_CERT to MBEDTLS_SSL_VERIFY_OPTIONAL but SSL_VERIFY_FAIL_IF_NO_PEER_CERT means that the verification is NOT optional.

Pull request to fix the issue at: https://github.com/espressif/esp-idf/pull/2162

Other people have caught the same issue with the openssl to mbedtls mapping but not sure that they are using esp-idf or not, https://github.com/warmcat/libwebsockets/blob/master/lib/tls/mbedtls/mbedtls-server.c#L38

**Comment by igrr** [comment]
Closing since PR #2162 has been merged.
