### ISSUE TITLE
[TW#24187] OTA : Old Delta Message received

### ISSUE THREAD

**Issue by satishIoT** [espressif/esp-idf#2178]
Experts ,

When i view this message in my log "aws_iot: Old Delta Message received - Ignoring rx: 1037 local: 1037" ota never takes place. Why ? , even if the ota code ( .bin ) is pushed immediately from cloud - ota fails.. 

To make work i had to change flag shadowDiscardOldDeltaFlag from true to false . What will be impact of this flag ? during ota or non ota code. 

thank,

**Comment by mahavirj** [comment]
@satishIoT 
This seems like more of question on AWS IoT device SDK side, could you please ask at respective support forum?
