### ISSUE TITLE
Issue building hello world example, LD bootloader.elf

### ISSUE THREAD

**Issue by Halfshellher0** [espressif/esp-idf#218]
Hello,

I'm having an issue building any of the examples.
I've haven't had trouble building these examples in the past, so I'm sure I'm doing something newbie.

I'm using the latest MSYS environment / ESP32 toolchain provided on the Windows setup guide:
[https://dl.espressif.com/dl/esp32_win32_msys2_environment_and_toolchain-20160816.zip](https://dl.espressif.com/dl/esp32_win32_msys2_environment_and_toolchain-20160816.zip)

when I try do a make all in the hello_world example directory (or any example) I get this error when it gets to LD bootloader.elf:

`Matt@Matt-PC MSYS /e/ESP32/esp-idf/examples/01_hello_world
$ make all
LD bootloader.elf
e:/msys/opt/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/4.8.5/../../../../xtensa-esp32-elf/bin/ld.exe: cannot find -lrtc
collect2.exe: error: ld returned 1 exit status
make[1]: *** [/e/ESP32/esp-idf/make/project.mk:310: /e/ESP32/esp-idf/examples/01_hello_world/build/bootloader/bootloader.elf] Error 1
make: *** [/e/ESP32/esp-idf/components/bootloader/Makefile.projbuild:31: /e/ESP32/esp-idf/examples/01_hello_world/build/bootloader/bootloader.bin] Error 2
`

I've tried doing a make clean, tried re-cloning the esp-idf from github, and tried with a fresh unzip of the MSYS/Toolchain provided, but nothing seems to fix the error. 
I'm not sure what's causing this error, if anyone could help it would be greatly appreciated, and if anyone could explain whats happening it would be even better.

Thanks.

**Comment by projectgus** [comment]
Hi @Halfshellher0,

Did you close thie issue because you figured the problem out? If it's possible to share what the solution was, it may help someone else who has the same problem in the future.

Angus
