### ISSUE TITLE
[TW#24573] BLE advertising and scan response packets not working simultaneously with advertising interval parameters

### ISSUE THREAD

**Issue by menesesleonardo** [espressif/esp-idf#2185]
## Environment
- Core (if using chip or module): [ESP32-Wrover-I & ESP-WROOM32]
- IDF version IDF version: v3.1-dev-601-gda278163-dirty
- Development Env:		[Make & Eclipse]
- Operating System:		[Windows & Ubuntu]
- Power Supply:         [USB & Battery]

## Problem Description

Hello everyone, I'm having an issue when setting a Beacon with both advertising packet and scan response.
(https://gist.github.com/menesesleonardo/9eb56f19fde6379165843ea36e5ed244)

And I'm having a problem particularly with the advertising parameters here.

`
// data advertising parameters.
// TODO error with min. and max
static esp_ble_adv_params_t ble_adv_params = {
      .adv_int_min = 32,
      .adv_int_max = 32,
      .adv_type = ADV_TYPE_NONCONN_IND,
      .own_addr_type  = BLE_ADDR_TYPE_PUBLIC,
      .channel_map = ADV_CHNL_ALL,
      .adv_filter_policy  = ADV_FILTER_ALLOW_SCAN_ANY_CON_ANY,
};
`

### Expected Behavior

According to the ble_gap_api.h struct, the advertising min and max interval should be 20ms, the minimum possible. However, looking through nrf connect the actual interval is the default provided by the API, 1.28 SECONDS.

![ok](https://user-images.githubusercontent.com/33615982/42605770-6243f196-853f-11e8-8a0b-475bdc8998b4.png)

**Unfortunately, this setting is the only way for advertising packet an scan response packet to coexist. Setting the interval to any value different from 20ms breaks the scan response functionality.**

Now, the 1.2 second interval is not appropriate for advertising because only powerfull devices would catch the information. Looking for advertising normative in Apple iBeacon (https://developer.apple.com/ibeacon/) shows an appropriate value of 100ms for stability, and Goggle Eddystone says 200ms for a little more power-efficiency.

Here can be seen trials for 100ms as min and max interval, that is, iBeacon recommended interval
![ibeacon](https://user-images.githubusercontent.com/33615982/42605846-cc349ba0-853f-11e8-8345-967643596ad7.png)

and eddystone interval, 200ms as min and max.

![eddystone](https://user-images.githubusercontent.com/33615982/42605862-e20b39f2-853f-11e8-9434-8252e8922f18.png)

All of them with no success advertising scan response packet.

### Code to reproduce this issue

(https://gist.github.com/menesesleonardo/9eb56f19fde6379165843ea36e5ed244)

**Comment by Weijian-Espressif** [comment]
![img_0016](https://user-images.githubusercontent.com/16891442/43436925-19bac9e8-94b9-11e8-96fb-e7e1b485674a.PNG)
@menesesleonardo   this is my test result in iPhonex, the prrams are 
static esp_ble_adv_params_t heart_rate_adv_params = {
    .adv_int_min        = 32,
    .adv_int_max        = 32,
    .adv_type           = ADV_TYPE_NONCONN_IND,
    .own_addr_type      = BLE_ADDR_TYPE_PUBLIC,
    .channel_map        = ADV_CHNL_ALL,
    .adv_filter_policy = ADV_FILTER_ALLOW_SCAN_ANY_CON_ANY,
};

**Comment by Weijian-Espressif** [comment]
@chegewara  It  may be related to the scan parameters of the Samsung phones . I test it with iPhone X,  the adv params of ESP32 works very well. you can test it with iPhones.

**Comment by chegewara** [comment]
@Weijian-Espressif Sorry but im not using apple shit, and like i said when i bond esp32 with smartphone times are ok, but when i erase_flash and flash new app times are 1200+. But ok, i dont want to argue, i can live with that and i dont have reputation to tell if this is issue or not.

**Comment by Weijian-Espressif** [comment]
Hi @chegewara , when  bluedroid get adv packet, it will not report immediately, bluedroid must get scan response and adv packet before reporting to the application layer.   If you use encryption, it also need to resolve adv address. Those will take some time.

**Comment by chegewara** [comment]
@Weijian-Espressif The thing is i am not using encryption in test app, what i do is manually bonding in nRF connect or connecting with windows 10 laptop which also create bonding (its how windows 10 works).
