### ISSUE TITLE
[TW#24574] ulp pulse counter not working with other pins except gpio0

### ISSUE THREAD

**Issue by Mr-Techtron** [espressif/esp-idf#2186]
- [√ ] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [ √] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [ √] I have searched the issue tracker for a similar issue and not found a similar issue.

If the issue cannot be solved after the steps before, please follow these instructions so we can get the needed information to help you in a quick and effective fashion.

## Environment

- Development Kit:      ESP32-DevKit by DoIt
- Kit version (for WroverKit/PicoKit/DevKitC): v1
- Core (if using chip or module): ESP-WROOM32
- IDF version (``git rev-parse --short HEAD`` to get the commit id.): 04caff2f
- Development Env:	Eclipse
- Operating System:	Windows
- Power Supply:  USB

## Problem Description

In the example of ulp, pulse counting only works with GPIO0 pin. When I tried with other pins, it does not take any effect. I've only changed ulp_io_number and gpio_num accordingly in the given example and set ulp_debounce_counter and ulp_debounce_max_count to 1.

**Comment by negativekelvin** [comment]
https://github.com/espressif/esp-idf/blob/master/examples/system/ulp/main/ulp_example_main.c#L61

**Comment by negativekelvin** [comment]
What values did you try?

**Comment by Mr-Techtron** [comment]
gpio1,gpio3 & gpio16

**Comment by negativekelvin** [comment]
None of those pins are rtcio pins

**Comment by Mr-Techtron** [comment]
i mean to say rtc_gpio1, rtc_gpio3, rtc_gpio16

**Comment by negativekelvin** [comment]
Rtc_gpio1 is not even available on wroom32

**Comment by Mr-Techtron** [comment]
![capture](https://user-images.githubusercontent.com/30310925/42672397-8c651378-8685-11e8-9e2d-3d298b53a9e6.PNG)

**Comment by negativekelvin** [comment]
Yes I know but gpio37 and gpio38 are not brought out to pads on wroom32.

**Comment by igrr** [comment]
Thanks @negativekelvin for submitting the fix in https://github.com/espressif/esp-idf/pull/2190!

In addition to that, example is missing `rtc_gpio_init(gpio_num)` call before the `rtc_gpio_set_direction`. Will update example to fix that and simplify GPIO setup (automatically look up RTC IO number based on GPIO number).

**Comment by Mr-Techtron** [comment]
@negativekelvin Oh I see but later i tried RTC_GPIO10 & RTC_GPIO12, it didnt work either; thanks for your help :)

**Comment by igrr** [comment]
Issues reported here have been fixed in #2190 and 4b97a1edb25bc5368157ba4dcc884741fb347e58
