### ISSUE TITLE
Update esptool.py to v2.5.0 in esp-idf

### ISSUE THREAD

**Issue by davctv** [espressif/esp-idf#2199]
Hi everybody,

Is it planned to include esptool.py v2.5.0 in components/esptool_py?

Currently it is v.2.3.1 which has a bug on "chip_id" command. As a workaround I downloaded the esptool using "pip" but i think it could be merged in master branch.

Thanks

**Comment by davctv** [comment]
Thank you @projectgus.

I will wait for update.

**Comment by projectgus** [comment]
esptool.py has been updating to v2.5.0 in master, as part of 57b601ab7
