### ISSUE TITLE
[TW#24585] Memory leak while running udp_multicast_example_main.c

### ISSUE THREAD

**Issue by JetIgniter2k** [espressif/esp-idf#2201]
## Environment

- Development Kit:      [ESP-WROOM-32]

### Description:

I found a slow memory leak while running udp_multicast_example_main.c
After about 700 loops I run out of heap space and the system crashes.  I was losing 324 bytes per loop.
Adding freeaddrinfo(res); between lines 536 and 537 in udp_multicast_example_main.c seems to fix the problem.

**Comment by zhangyanjiaoesp** [comment]
@projectgus please take a look.

**Comment by projectgus** [comment]
Hi @JetIgniter2k ,

Thanks very much for reporting this. I can confirm you are correct, a call for freeaddrinfo() is needed in the place you report and also in a second place if IPV4 is enable in the example config.

A fix should be able shortly.

Angus
