### ISSUE TITLE
I2C slave driver problems (IDFGH-297)

### ISSUE THREAD

**Issue by Ostantric** [espressif/esp-idf#2202]
Has anyone been working on I2C slave ? I needed to setup the ESP as a slave yesterday and I realized driver is bad.

**Comment by xiongyumail** [comment]
Hi @Ostantric ,
Can you tell us where I2C slave is wrong and what happened?  
If it's convenient, give us a log.  
The use of slave is included in <https://github.com/espressif/esp-idf/tree/master/examples/peripherals/i2c>

**Comment by Ostantric** [comment]
I don't have any problems, I had to create my own driver to handle slave routine and it works fine. I saw that example and its not good.  I was just wondering if there is a plan to update the slave driver.

**Comment by loboris** [comment]
@Ostantric
You should realy try to explain in more details what is **not good** or what is **bad**.
Just stating that something is not good will hardly help to make things better.

I'm also not satisfied with how the slave driver works and I have [proposed](https://github.com/espressif/esp-idf/pull/2096) some modifications to the driver to make it more convenient to use.

**Comment by Ostantric** [comment]
@loboris nice work I would use yours after i test it. 
Example is bad because that's not how slave device works. They timed everything perfectly. You don't know when to expect I2C master read/write and I don't see queues or ISR interrupts in the example. 
I see that they have isr_default_handler and slave write/read in i2c.c but the implementation is missing features. It causes issues such as missing register commands, sending gargabe info to the master and  ACK/NACK issues. Hardware is there(even though i found some architectural problems or maybe I missed something in the reference manual), we just need to handle the interrupts.

**Comment by costaud** [comment]
@Ostantric  If what you want is just to handle the interrupts, you can simply register your own ISR handler by calling i2c_isr_register. But we will improve the I2C slave driver anyway. 

@loboris, Thanks for your PR, we will start reviewing and try to merge it.

**Comment by asafs932** [comment]
> @Ostantric
> You should realy try to explain in more details what is **not good** or what is **bad**.
> Just stating that something is not good will hardly help to make things better.
> 
> I'm also not satisfied with how the slave driver works and I have [proposed](https://github.com/espressif/esp-idf/pull/2096) some modifications to the driver to make it more convenient to use.

i am having issues with original esp code for reading 16bit register for example regAdr = 0x0003.
with my custom 16bit function it outputs wrong value of 0x01, and with 8bit function it outputs the correct value.
can you tell whats wrong with my custom 16bit function?

esp_err_t I2C_read_focus(uint16_t regAdr, uint8_t *readVal) {

    i2c_master_init();
    i2c_cmd_handle_t cmd = i2c_cmd_link_create();

    i2c_master_start(cmd);

    i2c_master_write_byte(cmd, (I2C_ADDR_FOCUS << 1) | WRITE_BIT, ACK_CHECK_EN);	// Write I2C 8bit Camera address
    i2c_master_write_byte(cmd, ((regAdr & 0xFF00) >> 8)         , ACK_VAL);	// Write Register 16bit Num to read from.
    i2c_master_write_byte(cmd,  (regAdr & 0x00FF)               , NACK_VAL);

    i2c_master_start(cmd);

    i2c_master_write_byte(cmd, (I2C_ADDR_FOCUS << 1) | READ_BIT, ACK_CHECK_EN);
    i2c_master_read_byte (cmd, readVal, NACK_VAL);

    i2c_master_stop(cmd);

    esp_err_t ret = i2c_master_cmd_begin(I2C_PORT_NUM, cmd, 1000 / portTICK_RATE_MS);

    i2c_cmd_link_delete(cmd);
    i2c_master_release();
    return ret;
}


and when i use the following 8bit function regAdr = 0x03 , output is correct value :


 esp_err_t I2C_read(uint8_t i2cAddr, uint8_t regAdr, uint8_t *readVal) {
    

	i2c_master_init();

    i2c_cmd_handle_t cmd = i2c_cmd_link_create();

    i2c_master_start(cmd);

    i2c_master_write_byte(cmd,(i2cAddr << 1) | WRITE_BIT, ACK_CHECK_EN);	// Write I2C 8bit Camera address
    i2c_master_write_byte(cmd, regAdr, ACK_CHECK_EN);

    i2c_master_start(cmd);

    i2c_master_write_byte(cmd, (i2cAddr << 1) | READ_BIT, ACK_CHECK_EN);
    i2c_master_read_byte (cmd, readVal, NACK_VAL);

    i2c_master_stop(cmd);

    esp_err_t ret = i2c_master_cmd_begin(I2C_PORT_NUM, cmd, 1000 / portTICK_RATE_MS);

    i2c_cmd_link_delete(cmd);
	
	i2c_master_release();

    return ret;
}

**Comment by costaud** [comment]
@asafs932 Just guess, Maybe you are using a wrong address in 16bit function, which is always I2C_ADDR_FOCUS?

**Comment by asafs932** [comment]
> @asafs932 Just guess, Maybe you are using a wrong address in 16bit function, which is always I2C_ADDR_FOCUS?

yes, this is how i execute these functions:
I2C_read_focus(0x0003, &readVal);   --> readVal output is not correct
I2C_read(I2C_ADDR_FOCUS, 0x0003, &readVal);   --> readVal output is correct

what is the difference?

**Comment by o-marshmallow** [comment]
I2C API has been enriched in newer versions.

Closing this issue, create a new one if the problem persists.
