### ISSUE TITLE
ping the ESP-WROOM-32(ap) and appear "Request timeout(请求超时)"

### ISSUE THREAD

**Issue by denny97104** [espressif/esp-idf#2203]
I want use ESP-WROOM-32 as ap. 
I complied the esp32 wifi example "simple_wifi",and download bin to the  ESP-WROOM-32.
My computer connect  ESP-WROOM-32 with wifi.
I ping the  ESP-WROOM-32 such as : ping 192.168.4.1 -t.
But more or less there will be "Request timeout".

the ping content:
来自 192.168.4.1 的回复: 字节=32 时间=1ms TTL=255
来自 192.168.4.1 的回复: 字节=32 时间=3ms TTL=255
请求超时。
来自 192.168.4.1 的回复: 字节=32 时间=2ms TTL=255
请求超时。
来自 192.168.4.1 的回复: 字节=32 时间=7ms TTL=255
来自 192.168.4.1 的回复: 字节=32 时间=1ms TTL=255
来自 192.168.4.1 的回复: 字节=32 时间=1ms TTL=255
...

192.168.4.1 的 Ping 统计信息:
    数据包: 已发送 = 12732，已接收 = 12460，丢失 = 272 (2% 丢失)，
往返行程的估计时间(以毫秒为单位):
    最短 = 1ms，最长 = 1004ms，平均 = 3ms

anyone help me?

**Comment by FayeY** [comment]
See [why “Request timeout” when I ping the ESP-WROOM-32?](https://esp32.com/viewtopic.php?f=13&t=6468&p=27801#p27801)
