### ISSUE TITLE
[TW#24597] I2C doesn`t want to work 

### ISSUE THREAD

**Issue by KryvosheyaIvan** [espressif/esp-idf#2220]
Hello!
I want to use BME 280 sensor in my project. 
It is controlled through I2C interface.
I use standart I2C example in esp-idf and unfortunately nothing works.
Please, help me. Test code is provided.
Also, I am using some bme280 arduino example and it works. There other pins used but I think that problem is not in pins.

P.S.
My code consists of init function and single function that reads CHIP_ID register, whicn must be 0x60.
But I don`t get any result.

[ForDevelopers.zip](https://github.com/espressif/esp-idf/files/2222690/ForDevelopers.zip)

**Comment by benjaminaigner** [comment]
Although you enabled the internal pull-ups, I think you should try it with external pullups on SDA/SCL (just to be sure).

Did you used the arduino example on this ESP32 or on a different Arduino board?

**Comment by KryvosheyaIvan** [comment]
@benjaminaigner , I use the same board. And using arduino code, there are simply two i2C wires without pull ups. I think that problem is in misusing standard esp-idf i2c driver.

**Comment by negativekelvin** [comment]
https://github.com/espressif/esp-iot-solution/blob/master/components/i2c_devices/sensor/bme280/bme280.c

**Comment by akbarhash** [comment]
https://github.com/akbarhash/esp32/tree/master/bme280
try this 
it works.

**Comment by KryvosheyaIvan** [comment]
@negativekelvin , @akbarhash Thanks a lot!
