### ISSUE TITLE
[TW#24740] aws-iot-device-sdk-embedded-C - buffer overrun / security issue

### ISSUE THREAD

**Issue by stuarthatchbaby** [espressif/esp-idf#2224]
aws/aws-iot-device-sdk-embedded-C has a buffer overrun issue in its JSON parser, addressed here: https://github.com/aws/aws-iot-device-sdk-embedded-C/issues/151 .

This has been fixed on the AWS side but the IDF is several commits behind. The issue is probably critical enough that the IDF fork should be updated with some urgency.

**Comment by anujdeshpande** [comment]
@stuarthatchbaby thanks for pointing this out - I'll update this ASAP
