### ISSUE TITLE
[TW#24741] Migrate some memory allocations of mesh to external SPIRAM

### ISSUE THREAD

**Issue by YanMinge** [espressif/esp-idf#2225]
On release esp-idf version V3.1,  if I enable both Bluetooth and mesh functions，it will crash with therse log, I use module ESP32-WROVER, and I also enable external SPIRAM, it seems that mesh and Bluetooth have inline effects in memory.

if I don't call wifi_mesh_start() or I don't enable bluetooth, Individual functions are all valid.
```
I (2197) mesh: 323<stop>
W (2197) mesh: [esp_mesh_stop,326] <stop>vendor ie
W (2202) mesh: [esp_mesh_stop,329] <stop>send block
W (2202) mesh: [esp_mesh_stop,332] <stop>rx task
I (2202) mesh: 1761<flush>xon:0, mgmt:0, bcast:0, down:0, donw-be:0
W (2207) mesh: [mesh_tx_task_main,1830] <break>
I (2212) mesh: 1761<flush>xon:0, mgmt:0, bcast:0, down:0, donw-be:0
W (2217) mesh: [mesh_tx_task_main,2114] <done>MESH_STOP_EVENT_BIT_TX
W (2222) mesh: [mesh_tx_task_main,2115] <stop>tx
I (2232) mesh: 1780<flush>up:0, up-be:0
W (2232) mesh: [mesh_xon_task_main,2313] <break>
I (2237) mesh: 1780<flush>up:0, up-be:0
W (2237) mesh: [mesh_xon_task_main,2625] <done>MESH_STOP_EVENT_BIT_XON
W (2247) mesh: [mesh_xon_task_main,2626] <stop>xon
script name main.py
execute user script
W (2257) mesh: [esp_mesh_stop,335] <stop>tx task
W (2257) mesh: [esp_mesh_stop,338] <stop>nwk task
W (2272) mesh: [esp_mesh_stop,341] <stop>wifi event
W (2272) mesh: [esp_mesh_stop,345] <stop>route
W (2272) mesh: [esp_mesh_stop,348] <stop>s_mesh_recv_wait_xmit:0
W (2277) mesh: [esp_mesh_stop,372] <stop>free mesh_myself_mbox
W (2282) mesh: [esp_mesh_stop,383] <stop>free mesh_tcpip_mbox
W (2287) mesh: [esp_mesh_stop,386] <stop>s_mesh_send_wait_xmit:0
W (2297) mesh: [esp_mesh_stop,397] <stop>free mesh_xmit_state_mbox
D (2307) nvs: nvs_close 7
W (2312) mesh: [esp_mesh_stop,408] <stop>nvs task
D (2312) nvs: nvs_set_blob ap.ssid 36
D (2312) nvs: nvs_set_blob ap.passwd 65
D (2312) nvs: nvs_set ap.authmode 1 0
D (2317) nvs: nvs_set ap.chan 1 6
D (2322) nvs: nvs_set ap.hidden 1 1
D (2322) nvs: nvs_set ap.max.conn 1 3
D (2327) nvs: nvs_set bcn.interval 2 100
D (2332) event: SYSTEM_EVENT_AP_STOP
D (2332) event: SYSTEM_EVENT_AP_START
I (2337) mesh: 445<end>
D (2337) WIFI_MESH: esp_event_handler:1
I (2347) WIFI_MESH: <MESH_EVENT_STOPPED>
ESP_ERROR_CHECK failed: esp_err_t 0xffffffff at 0x4012fb3a
file: "main.c" line 144
func: app_main
expression: esp_mesh_start()

Backtrace: 0x40095a3f:0x3ffda8a0 0x40095fdd:0x3ffda8c0 0x4012fb3a:0x3ffda8e0 0x400debf8:0x3ffdaa60
```

**Comment by YanMinge** [comment]
Has this issue been confirmed? Do I need to provide further information？

**Comment by dongdong004** [comment]
Hi @YanMinge ,
I wonder whether there is enough free heap to run mesh. Could you please print the free heap size before `esp_mesh_start`?
* All free heap: `esp_get_free_heap_size()`
* **Internal free heap** : `heap_caps_get_free_size(MALLOC_CAP_INTERNAL|MALLOC_CAP_DEFAULT)`

**Comment by dongdong004** [comment]
> but seems mesh need 80k+ internal RAM
I test it and ESP-MESH could start in 40K internal RAM.

**Comment by YanMinge** [comment]
here are all free heap log for 
【before user code starts】 
【after wifi mesh init】
【after wifi mesh start】
```
before user code start!
free heap 8bit size is 116972,
 32bit size is 3330140,
 psram size is 3170260

after wifi mesh init!
free heap 8bit size is 78440,
 32bit size is 3282832,
 psram size is 3161484

after wifi mesh start!
free heap 8bit size is 19348,
 32bit size is 3223304,
 psram size is 3161048
```
my function code is

```
void wifi_mesh_init(void)
{
  printf("wifi_mesh_init\r\n");

  esp_log_level_set("mesh", ESP_LOG_NONE);

  /*  tcpip initialization */
  tcpip_adapter_init();

  /* for mesh
   * stop DHCP server on softAP interface by default
   * stop DHCP client on station interface by default
   * */
  ESP_ERROR_CHECK(tcpip_adapter_dhcps_stop(TCPIP_ADAPTER_IF_AP));
  ESP_ERROR_CHECK(tcpip_adapter_dhcpc_stop(TCPIP_ADAPTER_IF_STA));

  // /*  wifi initialization */
  ESP_ERROR_CHECK(esp_event_loop_init(NULL, NULL));
  wifi_init_config_t config = WIFI_INIT_CONFIG_DEFAULT();
  ESP_ERROR_CHECK(esp_wifi_init(&config));
  ESP_ERROR_CHECK(esp_wifi_set_storage(WIFI_STORAGE_RAM));
  ESP_ERROR_CHECK(esp_wifi_start());

  /*  mesh initialization */
  ESP_ERROR_CHECK(esp_mesh_init());
  ESP_ERROR_CHECK(esp_mesh_set_max_layer(CONFIG_MESH_MAX_LAYER));
  ESP_ERROR_CHECK(esp_mesh_set_ap_authmode(CONFIG_MESH_AP_AUTHMODE));
  ESP_ERROR_CHECK(esp_mesh_set_vote_percentage(1));
  ESP_ERROR_CHECK(esp_mesh_set_ap_assoc_expire(10));

  ESP_ERROR_CHECK(esp_mesh_fix_root(true));
  esp_wifi_get_mac(ESP_IF_WIFI_STA, self_sta_mac);
  ESP_LOGW(MESH_TAG, "self_sta_mac: %x %x %x %x %x %x",self_sta_mac[0],self_sta_mac[1],self_sta_mac[2],self_sta_mac[3],self_sta_mac[4],self_sta_mac[5]);
  set_wifi_mesh_config_default();
}
```

```
void wifi_mesh_start(void)
{
  printf("wifi_mesh_start\r\n");

  esp_mesh_set_config(&mesh_configuration);
  /* mesh start */
  ESP_ERROR_CHECK(esp_mesh_start());
  ESP_LOGI(MESH_TAG, "mesh starts successfully, heap:%d\n",  esp_get_free_heap_size());
  ESP_ERROR_CHECK(esp_mesh_set_self_organized(1, 0));
  mesh_send_sem = xSemaphoreCreateMutex();
  mesh_receive_sem = xSemaphoreCreateMutex();
}
```

**Comment by dongdong004** [comment]
There must be some internal RAM for BT,WIFI and ESP-MESH.
* `When disabling flash cache (for example, because the flash is being written to), the external RAM also becomes inaccessible; any reads from or writes to it will lead to an illegal cache access exception. This is also the reason that ESP-IDF will never allocate a tasks stack in external RAM.`

But there should be more than 200K internal RAM in ESP32. So could you recheck where's the other 100K internal RAM? And if try to move some of them to external RAM if possible.
* See the Restrictions of external RAM: https://docs.espressif.com/projects/esp-idf/en/latest/api-guides/external-ram.html

**Comment by YanMinge** [comment]
Because I have a user thread that needs to run a parser, it probably consumes 80K of memory. 
But you can see that when start the mesh, The memory from 110K+ to less than 20K-, this consumption is really big. 

I have optimized my memory usage now, and I also enable CONFIG_BT_ALLOCATION_FROM_SPIRAM_FIRST, and now BLE and mesh can work at the same time. But I think if you can also optimize the memory on your side, it will be better,  ringbuf, array, data cache can be allocated from the external SPIRAM, I think the remaining 40K internal RAM is possible. just like CONFIG_BT_ALLOCATION_FROM_SPIRAM_FIRST, I holp we have a CONFIG_MESH_ALLOCATION_FROM_SPIRAM_FIRST

**Comment by dongdong004** [comment]
Yes, we should guarantee optimization memory use and we already have the `CONFIG_WIFI_LWIP_ALLOCATION_FROM_SPIRAM_FIRST` in menuconfig. I think it could be better in later versions.

By the way, wifi and mesh are different tasks, so the memory is not only used by mesh when you "start the mesh".
