### ISSUE TITLE
 implicit declaration of function 'unlink'

### ISSUE THREAD

**Issue by tdesmet** [espressif/esp-idf#224]
Hello im trying to use vfs with spiffs. I can open and write files but when I add unlink to my code I get the following error:

>  error: implicit declaration of function 'unlink' [-Werror=implicit-function-declaration]
   unlink("/data/foo.txt");
   ^

other functions like fopen, fclose, stat and rename work.

**Comment by negativekelvin** [comment]
Maybe `#include <sys/unistd.h>`

**Comment by tdesmet** [comment]
Thanks, that did it.
