### ISSUE TITLE
ESP32 - ADC

### ISSUE THREAD

**Issue by chlo12345678** [espressif/esp-idf#2240]
For esp32's ADC,

How to config the esp32 to measure voltage level with full range 0 - 3.3V?

How to do this in code?

Also, can I set any adc voltage reference myself?

**Comment by junhuanchen** [comment]
Hi,

**Comment by junhuanchen** [comment]
Hi

**Comment by junhuanchen** [comment]
Hi

You should see this [esp-idf adc](https://esp-idf.readthedocs.io/en/latest/api-reference/peripherals/adc.html#_CPPv225adc1_config_channel_atten14adc1_channel_t11adc_atten_t)

About 11dB attenuation (ADC_ATTEN_DB_11) gives full-scale voltage 3.9V (see note below).

You can try 3.9V map 3.3V.

**Comment by chlo12345678** [comment]
Thanks for your reply. 
what does it mean by setting 11dB attenuation? 
How does it related to measuring voltage level?

**Comment by junhuanchen** [comment]
This is an attenuation of the basic knowledge of the circuit. 

You need to refer to the relevant information about DB and attenuation.

Just a few words can't explain
