### ISSUE TITLE
[TW#24915] Problem with switching between Ethernet, WIFI and gsm

### ISSUE THREAD

**Issue by Arthedian** [espressif/esp-idf#2244]
## Environment

- Development Kit:      ESP32-DevKitC
- Kit version  - I dont know
- IDF version 561884b6
- Development Env: other - sublime text
- Operating System: debian
- Power Supply: USB

## Problem Description

I am trying to get WIFI, Ethernet and GSM working at the same time. If I switch between WIFI and Ethernet or between GSM and WIFI, then everything is ok. If I connect to Ethernet, wifi, GSM, Ethernet and then to GSM, it stops on sending file to server.

### Expected Behavior

switch between WIFI, Ethernet and GSM and automatically choose the connection for sending file.

### Actual Behavior

For first switch it is working, but for the second and other times it wont send file. It gives a long timeout/

### Steps to repropduce

I have connected ethernet module according to recomendation here on github. I have separate power supply for gsm module and rest (common ground).

### Code to reproduce this issue
I am running this function before sending file to server. 
```cpp
void data_connect() {
    if(statusIP==3){
        printf("test 1\n");
        ppposDisconnect(0, 0);
        printf("test 2\n");
        ethernet_init();
    }
    else if(statusIP==2){
        ESP_ERROR_CHECK(esp_wifi_stop());
    }
    if(statusIP!=1){
        printf("test 3\n");
        ESP_ERROR_CHECK(esp_eth_enable());
        printf("test 4\n");
    }
    
    uint8_t connected = false;
    tcpip_adapter_ip_info_t ip;
    memset(&ip, 0, sizeof(tcpip_adapter_ip_info_t));
    for (int i = 0; i < 5; ++i)
    {

        if (tcpip_adapter_get_ip_info(ESP_IF_ETH, &ip) == 0) {
            ESP_LOGI(TAG, "~~~~~~~~~~~");
            ESP_LOGI(TAG, "ETHIP:"IPSTR, IP2STR(&ip.ip));
            ESP_LOGI(TAG, "ETHPMASK:"IPSTR, IP2STR(&ip.netmask));
            ESP_LOGI(TAG, "ETHPGW:"IPSTR, IP2STR(&ip.gw));
            ESP_LOGI(TAG, "~~~~~~~~~~~");
            if(ip.ip.addr!=0){
                printf("connected to ethernet\n");
                connected=true;
                statusIP=1;
                break;
            }
        }
        vTaskDelay(2000 / portTICK_PERIOD_MS);
    }
    if (connected){
        return;
    }
    ESP_ERROR_CHECK(esp_eth_disable());
    ESP_ERROR_CHECK(esp_wifi_start());
    vTaskDelay(1000 / portTICK_PERIOD_MS);
    while(!wifi_status){
        printf("cekam na pripojeni\n");
        vTaskDelay(1000 / portTICK_PERIOD_MS);
    }
    if(wifi_status==2){
        printf("connected to a wifi\n");
        statusIP=2;
        return;
    }
    printf("test 1\n");
    ESP_ERROR_CHECK(esp_wifi_stop());
    printf("test 2\n");
    if(ppposInit()==0){
        printf("not connected\n");
        statusIP=255;
    }
    else{
        while (ppposStatus() != GSM_STATE_CONNECTED) {
            printf("still disconnected to GSM\n");
            vTaskDelay(1000 / portTICK_RATE_MS);
        }
        statusIP=3;
        printf("connected\n");
        return;
    }
    statusIP=0;
    printf("not connected\n");
    return;
}

```

**Comment by akbarhash** [comment]
```
if ((gotwificonfig) && (wificonnection) && (!settowifi))
{
	printf("case2\n");
	for (struct netif *pri = netif_list; pri != NULL; pri = pri->next)
	{
		if ((pri->name[0] == 's') && (pri->name[1] == 't'))
		{
			pausenetworkdependanttasks();
			netif_set_default(pri);
			resumenetworkdependanttasks();
			ESP_LOGI(SMARTCONFIGTAG, "Interface priority has been set to %c%c%d (" IPSTR "/" IPSTR " gateway " IPSTR ")",
				 pri->name[0], pri->name[1], pri->num,
				 IP2STR(&pri->ip_addr.u_addr.ip4), IP2STR(&pri->netmask.u_addr.ip4), IP2STR(&pri->gw.u_addr.ip4));
		}
	}
	settowifi = 1; 
	settopppos = 0;
}

if ((!wificonnection) && (ppposconnection) && (!settopppos))
{
	printf("case3\n");
	for (struct netif *pri = netif_list; pri != NULL; pri = pri->next)
	{
		if ((pri->name[0] == 'p') && (pri->name[1] == 'p'))
		{
			pausenetworkdependanttasks();
			netif_set_default(pri);
			resumenetworkdependanttasks();
			ESP_LOGI(SMARTCONFIGTAG, "Interface priority has been set to %c%c%d (" IPSTR "/" IPSTR " gateway " IPSTR ")",
				 pri->name[0], pri->name[1], pri->num,
				 IP2STR(&pri->ip_addr.u_addr.ip4), IP2STR(&pri->netmask.u_addr.ip4), IP2STR(&pri->gw.u_addr.ip4));
		}
	}
	settowifi = 0; 
	settopppos = 1;
}
```
Do this to change interfaces when new interface is connected.

**Comment by Ritesh236** [comment]
Hi,

Anyone has any update regarding same?

**Comment by Ritesh236** [comment]
Hi,

Anyone has any update regarding this feature or not? Let me know regarding this as soon as possible.

**Comment by akbarhash** [comment]
this is not a support forum. if anyone has any information to share they will. asking for it will not yield results.

**Comment by Ritesh236** [comment]
Ok. Sorry for multiple comments asking for same.

**Comment by xiongyumail** [comment]
Hi @akbarhash 
Have you found a way in the LWIP level? Maybe the LWIP adapter layer needs some modifications for your application.

**Comment by akbarhash** [comment]
It could be possible to get it to work from the LWIP level but when i tried it I found this to be the easier solution.

**Comment by akbarhash** [comment]
in my case there is no ethernet only gsm and wifi. and the code to switch between the two is already give above in my comment.

posted here again for clarity.

`if ((gotwificonfig) && (wificonnection) && (!settowifi))
{
	printf("case2\n");
	for (struct netif *pri = netif_list; pri != NULL; pri = pri->next)
	{
		if ((pri->name[0] == 's') && (pri->name[1] == 't'))
		{
			pausenetworkdependanttasks();
			netif_set_default(pri);
			resumenetworkdependanttasks();
			ESP_LOGI(SMARTCONFIGTAG, "Interface priority has been set to %c%c%d (" IPSTR "/" IPSTR " gateway " IPSTR ")",
				 pri->name[0], pri->name[1], pri->num,
				 IP2STR(&pri->ip_addr.u_addr.ip4), IP2STR(&pri->netmask.u_addr.ip4), IP2STR(&pri->gw.u_addr.ip4));
		}
	}
	settowifi = 1; 
	settopppos = 0;
}

if ((!wificonnection) && (ppposconnection) && (!settopppos))
{
	printf("case3\n");
	for (struct netif *pri = netif_list; pri != NULL; pri = pri->next)
	{
		if ((pri->name[0] == 'p') && (pri->name[1] == 'p'))
		{
			pausenetworkdependanttasks();
			netif_set_default(pri);
			resumenetworkdependanttasks();
			ESP_LOGI(SMARTCONFIGTAG, "Interface priority has been set to %c%c%d (" IPSTR "/" IPSTR " gateway " IPSTR ")",
				 pri->name[0], pri->name[1], pri->num,
				 IP2STR(&pri->ip_addr.u_addr.ip4), IP2STR(&pri->netmask.u_addr.ip4), IP2STR(&pri->gw.u_addr.ip4));
		}
	}
	settowifi = 0; 
	settopppos = 1;
}`

**Comment by Ritesh236** [comment]
Thanks for providing code and details for that

**Comment by TobeChan** [comment]
hi everyone:
Can you tell me how to using ethernet interface as a server communicate with the lower computer
Thanks~

**Comment by gtec2** [comment]
> in my case there is no ethernet only gsm and wifi. the code to switch between the two is already given above in my comment.
> 
> posted here again for clarity.
> 
> ```
> if ((gotwificonfig) && (wificonnection) && (!settowifi))
> {
> 	printf("case2\n");
> 	for (struct netif *pri = netif_list; pri != NULL; pri = pri->next)
> 	{
> 		if ((pri->name[0] == 's') && (pri->name[1] == 't'))
> 		{
> 			pausenetworkdependanttasks();
> 			netif_set_default(pri);
> 			resumenetworkdependanttasks();
> 			ESP_LOGI(SMARTCONFIGTAG, "Interface priority has been set to %c%c%d (" IPSTR "/" IPSTR " gateway " IPSTR ")",
> 				 pri->name[0], pri->name[1], pri->num,
> 				 IP2STR(&pri->ip_addr.u_addr.ip4), IP2STR(&pri->netmask.u_addr.ip4), IP2STR(&pri->gw.u_addr.ip4));
> 		}
> 	}
> 	settowifi = 1; 
> 	settopppos = 0;
> }
> 
> if ((!wificonnection) && (ppposconnection) && (!settopppos))
> {
> 	printf("case3\n");
> 	for (struct netif *pri = netif_list; pri != NULL; pri = pri->next)
> 	{
> 		if ((pri->name[0] == 'p') && (pri->name[1] == 'p'))
> 		{
> 			pausenetworkdependanttasks();
> 			netif_set_default(pri);
> 			resumenetworkdependanttasks();
> 			ESP_LOGI(SMARTCONFIGTAG, "Interface priority has been set to %c%c%d (" IPSTR "/" IPSTR " gateway " IPSTR ")",
> 				 pri->name[0], pri->name[1], pri->num,
> 				 IP2STR(&pri->ip_addr.u_addr.ip4), IP2STR(&pri->netmask.u_addr.ip4), IP2STR(&pri->gw.u_addr.ip4));
> 		}
> 	}
> 	settowifi = 0; 
> 	settopppos = 1;
> }
> ```

Thanks for code!! Can you explain what accions do in pausenetworkdependanttasks() function?

**Comment by akbarhash** [comment]
that is just a function to stop the mqtt from trying to publish when there is no connection. in your case it could be anything that requires an internet connection.

**Comment by akbarhash** [comment]
> > in my case there is no ethernet only gsm and wifi. the code to switch between the two is already given above in my comment.
> > posted here again for clarity.
> > ```
> > if ((gotwificonfig) && (wificonnection) && (!settowifi))
> > {
> > 	printf("case2\n");
> > 	for (struct netif *pri = netif_list; pri != NULL; pri = pri->next)
> > 	{
> > 		if ((pri->name[0] == 's') && (pri->name[1] == 't'))
> > 		{
> > 			pausenetworkdependanttasks();
> > 			netif_set_default(pri);
> > 			resumenetworkdependanttasks();
> > 			ESP_LOGI(SMARTCONFIGTAG, "Interface priority has been set to %c%c%d (" IPSTR "/" IPSTR " gateway " IPSTR ")",
> > 				 pri->name[0], pri->name[1], pri->num,
> > 				 IP2STR(&pri->ip_addr.u_addr.ip4), IP2STR(&pri->netmask.u_addr.ip4), IP2STR(&pri->gw.u_addr.ip4));
> > 		}
> > 	}
> > 	settowifi = 1; 
> > 	settopppos = 0;
> > }
> > 
> > if ((!wificonnection) && (ppposconnection) && (!settopppos))
> > {
> > 	printf("case3\n");
> > 	for (struct netif *pri = netif_list; pri != NULL; pri = pri->next)
> > 	{
> > 		if ((pri->name[0] == 'p') && (pri->name[1] == 'p'))
> > 		{
> > 			pausenetworkdependanttasks();
> > 			netif_set_default(pri);
> > 			resumenetworkdependanttasks();
> > 			ESP_LOGI(SMARTCONFIGTAG, "Interface priority has been set to %c%c%d (" IPSTR "/" IPSTR " gateway " IPSTR ")",
> > 				 pri->name[0], pri->name[1], pri->num,
> > 				 IP2STR(&pri->ip_addr.u_addr.ip4), IP2STR(&pri->netmask.u_addr.ip4), IP2STR(&pri->gw.u_addr.ip4));
> > 		}
> > 	}
> > 	settowifi = 0; 
> > 	settopppos = 1;
> > }
> > ```
> 
> Thanks for code!! Can you explain what accions do in pausenetworkdependanttasks() function?

that is just a function to stop the mqtt from trying to publish when there is no connection. in your case it could be anything that requires an internet connection.

**Comment by gtec2** [comment]
Thanks!

**Comment by gtec2** [comment]
> > > in my case there is no ethernet only gsm and wifi. the code to switch between the two is already given above in my comment.
> > > posted here again for clarity.
> > > ```
> > > if ((gotwificonfig) && (wificonnection) && (!settowifi))
> > > {
> > > 	printf("case2\n");
> > > 	for (struct netif *pri = netif_list; pri != NULL; pri = pri->next)
> > > 	{
> > > 		if ((pri->name[0] == 's') && (pri->name[1] == 't'))
> > > 		{
> > > 			pausenetworkdependanttasks();
> > > 			netif_set_default(pri);
> > > 			resumenetworkdependanttasks();
> > > 			ESP_LOGI(SMARTCONFIGTAG, "Interface priority has been set to %c%c%d (" IPSTR "/" IPSTR " gateway " IPSTR ")",
> > > 				 pri->name[0], pri->name[1], pri->num,
> > > 				 IP2STR(&pri->ip_addr.u_addr.ip4), IP2STR(&pri->netmask.u_addr.ip4), IP2STR(&pri->gw.u_addr.ip4));
> > > 		}
> > > 	}
> > > 	settowifi = 1; 
> > > 	settopppos = 0;
> > > }
> > > 
> > > if ((!wificonnection) && (ppposconnection) && (!settopppos))
> > > {
> > > 	printf("case3\n");
> > > 	for (struct netif *pri = netif_list; pri != NULL; pri = pri->next)
> > > 	{
> > > 		if ((pri->name[0] == 'p') && (pri->name[1] == 'p'))
> > > 		{
> > > 			pausenetworkdependanttasks();
> > > 			netif_set_default(pri);
> > > 			resumenetworkdependanttasks();
> > > 			ESP_LOGI(SMARTCONFIGTAG, "Interface priority has been set to %c%c%d (" IPSTR "/" IPSTR " gateway " IPSTR ")",
> > > 				 pri->name[0], pri->name[1], pri->num,
> > > 				 IP2STR(&pri->ip_addr.u_addr.ip4), IP2STR(&pri->netmask.u_addr.ip4), IP2STR(&pri->gw.u_addr.ip4));
> > > 		}
> > > 	}
> > > 	settowifi = 0; 
> > > 	settopppos = 1;
> > > }
> > > ```
> > 
> > 
> > Thanks for code!! Can you explain what accions do in pausenetworkdependanttasks() function?
> 
> that is just a function to stop the mqtt from trying to publish when there is no connection. in your case it could be anything that requires an internet connection.

Thanks! It works fine!

**Comment by Gamelauncher** [comment]
My apologies for dragging up an old issue but I am running into a problem with this. I am using the Arduino-ide and while it looks like it's working, it's not.

```
#include <lwip/netif.h>

void changePriority() {
  for (struct netif *pri = netif_list; pri != NULL; pri = pri->next) {
    
    if ((wifi_connected) && (!eth_connected)) {
      if ((pri->name[0] == 's') && (pri->name[1] == 't')) {
        netif_set_default(pri);
        Serial.printf("Interface priority has been set to %c%c%d (" IPSTR "/" IPSTR " gateway " IPSTR ")\n",
           pri->name[0], pri->name[1], pri->num,
           IP2STR(&pri->ip_addr.u_addr.ip4), IP2STR(&pri->netmask.u_addr.ip4), IP2STR(&pri->gw.u_addr.ip4));
      }
    }

    if (eth_connected) {
      if ((pri->name[0] == 'e') && (pri->name[1] == 'n')) {
        netif_set_default(pri);
        Serial.printf("Interface priority has been set to %c%c%d (" IPSTR "/" IPSTR " gateway " IPSTR ")\n",
           pri->name[0], pri->name[1], pri->num,
           IP2STR(&pri->ip_addr.u_addr.ip4), IP2STR(&pri->netmask.u_addr.ip4), IP2STR(&pri->gw.u_addr.ip4));
      }
    }

  }
  checkDefaultInterface();
}

void checkDefaultInterface() {
  if (netif_default) {
    Serial.printf("\nDefault Interface: %c%c%d (" IPSTR "/" IPSTR " gateway " IPSTR ")\n",
    netif_default->name[0], netif_default->name[1], netif_default->num,
    IP2STR(&netif_default->ip_addr.u_addr.ip4),
    IP2STR(&netif_default->netmask.u_addr.ip4),
    IP2STR(&netif_default->gw.u_addr.ip4));
  } else {
    Serial.println("\nNo default interface\n");
  }
}
```

Output

```
22:04:38.870 -> [WiFi-event] event: 7
22:04:38.870 -> WiFi connected
22:04:38.904 -> RSSI: -43
22:04:38.904 -> IP IPv4: 192.168.1.238
22:04:38.904 -> Interface priority has been set to st2 (192.168.1.238/255.255.255.0 gateway 192.168.1.1)
22:04:38.904 -> Default Interface: st2 (192.168.1.238/255.255.255.0 gateway 192.168.1.1)
22:04:42.645 -> [WiFi-event] event: 25
22:04:42.645 -> Interface priority has been set to en1 (192.168.1.239/255.255.255.0 gateway 192.168.1.1)
22:04:42.681 -> Default Interface: en1 (192.168.1.239/255.255.255.0 gateway 192.168.1.1)
```

Calling changePriority() seems to yield the result I need ... but on building up an outgoing connection with ESPAsyncMQTT, it still uses wifi. Any idea why?

My guess it's because of the separate inclusion of lwip.h instead of using:

```
extern "C" {
  extern char *netif_list;
}
```

But above just gives me error's, a little help in the right direction would be greatly appreciated!

**Comment by Hemant7777** [comment]
Hi, I am currently working on a project where I have to put wifi and GPRS, I've already managed to operate the two module (ESP01,SIM800L) separately.  Now what I want to do is combine the two.  If for example if there is no wifi, it goes to gprs and if the wifi is available it goes back to the wifi  i.  I do not have too many ideas how can I do it, do you have any suggestions?  Thank you
