### ISSUE TITLE
how to get default factory wifi MAC or the chip ID

### ISSUE THREAD

**Issue by 4867896** [espressif/esp-idf#2249]
how to get default factory wifi MAC or the chip ID，i can`t find something in the SDK , so i need your help .thank you！

**Comment by shahpiyushv** [comment]
Ist his what you are looking for: https://github.com/espressif/esp-idf/blob/1c7a8b3b712c4020562551f692d0ced8f7470d2c/components/esp32/include/esp_wifi.h#L623

**Comment by sukeshak** [comment]
Can this be used to uniquely identify a device with ESP32?

**Comment by shahpiyushv** [comment]
MAC addresses are unique and so ideally, this should work as a unique identifier. If in case you find the MACs to be same, you should actually get unique MAC addresses programmed before using the chips commercially.

**Comment by sukeshak** [comment]
How would I know if there are same MAC address out there in the wild?
I am working on a commercial product.

**Comment by shahpiyushv** [comment]
There wouldn't be duplication of MAC addresses if you are directly procuring modules as it is the responsibility of the module manufacturer to ensure uniqueness of MAC. However, some product manufacturers also prefer chips without a MAC address pre programmed and later program their own MACs if they have a registered "Organisationally Unique Identifier".

In short, MAC addresses will be unique, unless you explicitly procure chips without a MAC address.

**Comment by sukeshak** [comment]
Ok thank you. Will speak to the manufacturer 👍

**Comment by sukeshak** [comment]
I am adding STSAFE-A100 so this is not an issue anymore 😊
