### ISSUE TITLE
[TW#24916] Mention cmake branch in master "Getting Started" docs

### ISSUE THREAD

**Issue by twelve12pm** [espressif/esp-idf#2252]
I recommend to mention the feature/cmake branch in master "Getting Started" document.

Rationale: I am developing on Windows. I purchased my ESP32-WROVER-KIT board from Digi-Key, who provide a link to latest ESP-IDF Programming Guide. Basically this was my "landing page" for connecting and working with the board. I followed those instructions to setup MSYS2. My development machine already has Git for Windows (with git bash etc), CMake, Python27, etc. The installation of MSYS2 basically means redundant copies of UNIX tools (including redundant git, python, etc -- and different versions of these utilities than what I already had). Had I known about the CMake branch and plans to make CMake the default in future, I would have started directly with that branch.

Therefore I recommend under "Toolchain Setup" to mention the possibility to checkout feature/cmake and use that instead.

**Comment by projectgus** [comment]
Hi @twelve12pm ,

Sorry noone ever got back to you about this.

The ESP IDF Programming Guide now has a whole separate set of Getting Started guides for CMake. We will be making this the default soon, to be released in IDF V4.0.
