### ISSUE TITLE
[TW#24918] Management of client configuration descriptor

### ISSUE THREAD

**Issue by huguesBouvier** [espressif/esp-idf#2253]
## Environment
- Development Kit:      ESP32-Wrover-Kit
- Kit version: v4
- IDF version: v3.0.2
- Development Env:Eclipse
- Operating System:Ubuntu
- Power Supply:  USB

## Problem Description
My question pertain the handling of client characteristic descriptor.
As per Bluetooth specification (v5), if notify property is set,then the client configuration descriptor shall exist.  

Is the client configuration description automatically handled inside the ESP32 Bluetooth stack or should that be handled in the user app?
For each client connection, if the characteristic supports notify or indicate, should the different instances of the client configuration descriptor be handled by the user?

If not, I think this behavior could be automated inside the stack. The drawback of having it handled in the user app is that:
- The management of the list is very tedious
- Slow since it has to be bubbled up to the user app whenever a client wants to write a client characteristic descriptor. 

Thank you,

Best,

Hugues

**Comment by Weijian-Espressif** [comment]
@huguesBouvier ,  The configuration description should that be handled in the user app. You can refer to our gatt_server_service_table demo.
