### ISSUE TITLE
[TW#24921] BLE gatt client. Unable to establish connection for the second time

### ISSUE THREAD

**Issue by KryvosheyaIvan** [espressif/esp-idf#2257]
Hello!
I use standard gatt_client example and it works well. But there the principle "open BLE connection and wait for notify" is used. In my case it is needed to open connection, write necessary characteristics and close connection. I have problems with it: I couldnt establish connection for the second time. It means I open connection, write what I want ( test led blinks) then I close connection. Then after several seconds a try to do the same actions but I cant connect! 

I use the following sequence of API:
1. esp_ble_gattc_open() --> wait for open event
2. esp_ble_gap_update_conn_params()
3. esp_ble_gattc_send_mtu_req() --> wait for MTU_CFG
4. all necessary functions to write chars (that works well)
5. esp_ble_gattc_close()--> wait for close event

Could someone tell me what is wrong?

Also, interesting fact is that when I try to connect to server for the second time. The update connection parameters event occurs, though I do not call any function to update connection parameters. 
`I (255870) GATTC_DEMO: update connection params status = 0, min_int = 6, max_int = 6,conn_int = 6,latency = 0, timeout = 600`

**Comment by Weijian-Espressif** [comment]
@KryvosheyaIvan  please provide the test log

**Comment by FayeY** [comment]
See #2167
