### ISSUE TITLE
Why is the order in the partitions file important?

### ISSUE THREAD

**Issue by korstiaanS** [espressif/esp-idf#2258]
Hi,

I have a setup with a spiffs partition (name: storage) and a second nvs partition (name: my data) with some data.
If I make my partitions.cvs file like this:

```
# Name,         Type,   SubType,    Offset,     Size
# Note: if you change the phy_init or app partition offset, make sure to change the offset in Kconfig.projbuild
nvs,            data,   nvs,        0x9000,     0x4000
otadata,        data,   ota,        0xd000,     0x2000
phy_init,       data,   phy,        0xf000,     0x1000
ota_0,          app,    ota_0,      0x10000,    2M
ota_1,          app,    ota_1,      ,           2M
mydata,         data,   nvs,        ,           10K
storage,        data,   spiffs,     ,           2M
```

make commands like `make menuconfig` keeps on working and everything works fine.

But if I do it like this (change the order of the last 2 lines):

```
# Name,         Type,   SubType,    Offset,     Size
# Note: if you change the phy_init or app partition offset, make sure to change the offset in Kconfig.projbuild
nvs,            data,   nvs,        0x9000,     0x4000
otadata,        data,   ota,        0xd000,     0x2000
phy_init,       data,   phy,        0xf000,     0x1000
ota_0,          app,    ota_0,      0x10000,    2M
ota_1,          app,    ota_1,      ,           2M
storage,        data,   spiffs,     ,           2M
mydata,         data,   nvs,        ,           10K
```

I get on every make command the following error:

```
/Users/skor/esp/myProjects/WarehouseEpaper/components/spiffs_image/Makefile.projbuild:13:
/Users/skor/esp/myProjects/WarehouseEpaper/components/spiffs_image/spiffs_param.mk: 
No such file or directory
make: *** No rule to make target
Users/skor/esp/myProjects/WarehouseEpaper/components/spiffs_image/spiffs_param.mk'.  Stop.
```

In the last case the spiffs_param.mk gets deleted as soon as I do a make command (even like make menuconfig).
Changing the 10K to 100K or 1M does not help.

Any idea why the order of these 2 lines are important?

**Comment by igrr** [comment]
Could you please point to the source of spiffs_image component?

**Comment by korstiaanS** [comment]
[https://github.com/loboris/ESP32_spiffs_example](https://github.com/loboris/ESP32_spiffs_example)

**Comment by negativekelvin** [comment]
https://github.com/loboris/ESP32_spiffs_example/blob/3ad8078cdcc8c42ad9ff0fe683b6277139b84748/components/spiffs_image/spiffs_part_info.py#L277

**Comment by korstiaanS** [comment]
@negativekelvin yes, and then what?
Why is the .mk file not generated if the 2 lines are swapped?

**Comment by igrr** [comment]
@korstiaanS  The script which @negativekelvin linked in the comment above assumes that SPIFFS partition is the last item in the partition table, and that the name is "storage". 
```python
    lastpart = table[len(table)-1]
    if lastpart.name == 'storage':
        ...
```
If the 'storage' partition is not the last one, spiffs_param.mk will not be generated.
Closing the issue here, please follow up in ESP32_spiffs_example project.
