### ISSUE TITLE
VisualGDB get ESP-IDF error

### ISSUE THREAD

**Issue by jade111** [espressif/esp-idf#2264]
不能更新ESP-IDF的资源库，

**Comment by FayeY** [comment]
Hi @jade111 , is this issue solved now? If not, could you provide more details about it?
Screenshots and more issue description can be very helpful.
Thanks.

**Comment by FayeY** [comment]
Closing due to lack of response, please feel free to reopen if this is still an issue and you can supply more details.
Thanks.

**Comment by jade111** [comment]
Hi FayeY,

I am sorry for reply latter. I have get the code from github. May there are some issues becouse of internet.
