### ISSUE TITLE
Any examples with TCP server for LwIP? (IDFGH-323)

### ISSUE THREAD

**Issue by sarpdaltaban** [espressif/esp-idf#2271]
PPPoS is working great and thank you for the example.

However, when I try to implement a TCP server over PPPoS, Incorrect ack number returns to the Clients who try to connect.

When I try to implement a TCP client over PPPoS, client can connect to a server but can send data until a TCP window size is reached. The window must be refreshed per send, but it doesn't and overloads..

I tried to use Raw API(LwIP), Netconn API and  BSD Socket API in a second thread and results are the same..

**Comment by liuzfesp** [comment]
@sarpdaltaban we don't have example for TCP server yet.

Could you provide your code which is based on Socket API here, then we can check it.

**Comment by Alvin1Zhang** [comment]
@sarpdaltaban Could you help provide some inputs? Thanks.

**Comment by Alvin1Zhang** [comment]
@sarpdaltaban Thanks for reporting the issue, could you please help provide some more inputs? Thanks.

**Comment by liuzfesp** [comment]
@@sarpdaltaban, we already have TCP examples in $IDF_PATH/examples/protocols/sockets/tcp_server, please check it please.

**Comment by Alvin1Zhang** [comment]
@sarpdaltaban Thanks for reporting the issue, feel free to reopen the ticket if the issue still happens, thanks.
