### ISSUE TITLE
There are some bug need to be fixed when we use the Up-to-date esp32 lib on Arduino

### ISSUE THREAD

**Issue by watson8544** [espressif/esp-idf#2275]
## Environment

- Core (if using chip or module):  ESP-WROOM32
- IDF version   b85e8e10b90ab7089ec7989ba513f7a2235f9ea4
- Development Env:		Arduino IDE
- Operating System:		Windows
- Power Supply:         USB

## Problem Description

After i updated the hareware/espressif/esp32  directory  using "git pull". Then the I2C module is halted whenever i used the I2C module on Arduino IDE.

The default I2C module has some bug. Maybe it is I2C0. The I2C module will be halted.

Please fix it quickly. Thank you！

**Comment by stickbreaker** [comment]
The current Arduino release has a bug with ReSTART operations, I have a fix pending [pr 1717](https://github.com/espressif/arduino-esp32/pull/1717) That fixes this problem. 

Chuck.
