### ISSUE TITLE
fig

### ISSUE THREAD

**Issue by maramb81** [espressif/esp-idf#2276]
## Environment

esp32-devkitc v4
ESP-IDF
esp-idf.readthedocs.io/en/latest/get-started/get-started-devkitc.html

## Problem Description

i can't flash my board

VAIO MINGW32 ~/esp/hello_world
$ make flash
Flashing binaries to serial port COM7 (app at offset 0x10000 )...
esptool.py v2.5.0
Serial port COM7
Connecting........_____....._____....._____....._____....._____....._____....._____

A fatal error occurred: Failed to connect to ESP32: Invalid head of packet (0x77)
make: *** [/home/esp/esp-idf/components/esptool_py/Makefile.projbuild:63: flash] Error 2

**Comment by v1993** [comment]
WTF is it?

**Comment by maramb81** [comment]
it was a cheap usb cable, it did not give enough power to the module, when I changed the cable, I flashed the module without problems

SOLVED
