### ISSUE TITLE
SNTP manual interval request in the application (IDFGH-337)

### ISSUE THREAD

**Issue by Trubochkin** [espressif/esp-idf#2277]
The SNTP component [provides public methods](https://github.com/espressif/esp-idf/blob/master/components/lwip/include/lwip/apps/sntp/sntp.h) sntp_init and sntp_stop, but does not provide the method sntp_request publicly. Also, I see that request interval is set by [define](https://github.com/espressif/esp-idf/blob/4480ab6c8ce70778df4948e587e712540de237eb/components/lwip/include/lwip/apps/sntp/sntp_opts.h#L129). I need to set the request interval manually in my application. How can I do this?

**Comment by liuzfesp** [comment]
@Trubochkin currently LWIP SNTP doesn't provide API to manually set the polling interval. However, you can change the polling interval by changing SNTP_UPDATE_DELAY in lwipopts.h, the default polling interval is 3600000 milliseconds.

**Comment by Alvin1Zhang** [comment]
@Trubochkin Could you help share if any updates for this issue? Thanks.

**Comment by X-Ryl669** [comment]
@Trubochkin  You have an error in your code, you're busy waiting for sntp_enabled (probably a zealous ';' here). You probably need #2349 to be fixed too to avoid waiting 500ms for nothing, and instead be informed when the time has been changed.

**Comment by KonstantinKondrashov** [comment]
Hi @Trubochkin! We will add the Kconfig option to change `SNTP_UPDATE_DELAY`.  It will be merged soon.
