### ISSUE TITLE
How do I use blue LEDs on ESP32-LyraTD-MSC_A?

### ISSUE THREAD

**Issue by linzai1992** [espressif/esp-idf#2283]
What is the GPIO number of blue LEDs on this board?

**Comment by homeoflittlewolf** [comment]
The I/O of this ESP32-LyraTD-MSC board LEDs are GPIO18, GPIO23;
Please check Espressif official user guide for detailed schematics: https://www.espressif.com/zh-hans/products/hardware/esp32-lyratd-msc

**Comment by FayeY** [comment]
If the problem is still unsolved, please post to https://github.com/espressif/esp-adf/issues instead. Thanks.
