### ISSUE TITLE
[TW#25618] ble tx power hardcoded advertised value

### ISSUE THREAD

**Issue by chegewara** [espressif/esp-idf#2284]
Is bluetooth TX power hardcoded to value 0xEB (-21dB)?
https://github.com/nkolban/esp32-snippets/issues/611

**Comment by chegewara** [comment]
@TianHao-Espressif RSSI is changing which mean radio power is adjusted, but there is TX power advertised if this value is set to true:
https://github.com/espressif/esp-idf/blob/master/examples/bluetooth/gatt_server_service_table/main/gatts_table_creat_demo.c#L94

Tx power is advertised with this opcode `ESP_BLE_AD_TYPE_TX_PWR` and is always set to value 0xEB which is equal to -21dBm (tested with nRF connect and with esp32 client app).

**Comment by TianHao-Espressif** [comment]
@chegewara , thanks. I fixed the bug. Please wait for IDF update.

**Comment by chegewara** [comment]
no problem, thanks for fixing it.

**Comment by ehsanmqn** [comment]
@chegewara Does the problem solved? Am I able to adjust tx power now?

**Comment by chegewara** [comment]
Yes, tx power you can adjust, but advertising packet is still bugged and peer device will see TX power value -21 dBm.

**Comment by ehsanmqn** [comment]
Thank you. I have a question. I am using esp32 as BLE station to receive iBeacons from BLE tags. But I founded that it doesn't receive data from tags that are in locations with more than 2 meter distance. Can you guide me please how I can increase esp32 sensitivity?

**Comment by chegewara** [comment]
Try with other esp32, this can be damaged

**Comment by ehsanmqn** [comment]
@chegewara I have 3 ESP-WROOM-32. But receiving is weak.

**Comment by chegewara** [comment]
Like i said, it can be broken. To test it just flash it with ble server example and check with nRF connect rssi and distance it can be discovered (straight line, no obstacles).

**Comment by chegewara** [comment]
Seems to be fixed in master. Thanks.
