### ISSUE TITLE
Error while forcing data rate (LoadProhibited)

### ISSUE THREAD

**Issue by bureto** [espressif/esp-idf#2287]
## Environment

- Development Kit:      [ESP32-DevKitC]
- Kit version: [v1]
- Core (if using chip or module): [ESP-WROOM32]
- IDF version (``git rev-parse --short HEAD`` to get the commit id.): 
    //bd6ea4393c7d2f059fc4decc70f1ec3eb3597268
- Development Env:		[Arduino IDE]
- Operating System:		[Windows]
- Power Supply:         [USB]

## Problem Description

I get `Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.` error when forcing data rate. I actually got code from [here](https://github.com/mic159/ESP32CameraI2S/tree/master/ESP32_I2S_Camera).

### Expected Behavior
Code should work.

### Actual Behavior
Gives error, reboots, and repeats.
### Steps to repropduce

1. Upload code to ESP-32 module.
2. Power it up and look through serial monitor.

### Code to reproduce this issue

```cpp
// throws error here (line 53 ESP32_I2S_Camera.ino)
  esp_wifi_internal_set_rate(100, 1, 4, &rate);
```

Code is from [here](https://github.com/mic159/ESP32CameraI2S/tree/master/ESP32_I2S_Camera)

## Debug Logs

Exception Decoder:
```
PC: 0x400d7157
EXCVADDR: 0x0000000c

Decoding stack results
0x400d14d5: setup() at C:\Users\Brett\Documents\Arduino\ESP32_I2S_Camera/ESP32_I2S_Camera.ino line 53
0x4013232b: loopTask(void*) at C:\Users\Brett\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.0\cores\esp32\main.cpp line 15
```

Serial Monitor:
```
⸮⸮⸮⸮⸮⸮⸮⸮0x40080310
Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.
Core 1 register dump:
PC      : 0x400d7157  PS      : 0x00060530  A0      : 0x800d788c  A1      : 0x3ffb1e40  
A2      : 0x3ffc4494  A3      : 0x00000000  A4      : 0x0000001c  A5      : 0x0000001c  
A6      : 0x00000000  A7      : 0x00000001  A8      : 0x00000007  A9      : 0x3ffb1df0  
A10     : 0x0000001c  A11     : 0x0000001c  A12     : 0x00000000  A13     : 0x00000000  
A14     : 0x00060920  A15     : 0x00000000  SAR     : 0x0000001f  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x0000000c  LBEG    : 0x4000c2e0  LEND    : 0x4000c2f6  LCOUNT  : 0x00000000  

Backtrace: 0x400d7157:0x3ffb1e40 0x400d7889:0x3ffb1e70 0x400d7a3f:0x3ffb1e90 0x400d14d5:0x3ffb1eb0 0x4013232b:0x3ffb1fa0

Rebooting...
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:952
load:0x40078000,len:6084
load:0x40080000,len:7936
entry 0x40080310

```

**Comment by igrr** [comment]
Hi @bureto, first of all you are including `esp_wifi_internal.h` which has the following comment: https://github.com/espressif/esp-idf/blob/30545f4cccec7460634b656d278782dd7151098e/components/esp32/include/esp_wifi_internal.h#L16-L18

Second, `esp_wifi_internal_set_rate` is not declared in that header file, `esp_wifi_internal_set_fix_rate` is. It is likely that the signature of `esp_wifi_internal_set_rate` function has changed (since this is an internal function) and calling it like you do is not working anymore.
