### ISSUE TITLE
aws_iot_mqtt_init returned error: -2

### ISSUE THREAD

**Issue by sheikhumar93** [espressif/esp-idf#2291]
- IDF version: ee3f64cb
- Development Env: Make
- Operating System: macOS
- Power Supply: USB

## Problem Description
I have been trying to implement the aws-iot subscribe_publish IDF example in my project, but run into the error "aws_iot_mqtt_init returned error: -2" in the aws_iot_task() method in the example. I have followed the readme at protocols/aws-iot to create the thing, certificates and policies in AWS IOT and have copied those certificates to the main/certs directory in my project and renamed them to "aws-root-ca.pem", "certificate.pem.crt" and "private.pem.key". Although I am a bit confused as to which of the root certs I have to download. [AWS docs](https://docs.aws.amazon.com/iot/latest/developerguide/managing-device-certs.html#server-authentication) say that ideally you need all of these certificates, but I have added only the first one "VeriSign Class 3" into my directory and renamed it to "aws-root-ca.pem". I then ran `make menuconfig` and under `Component Config`, I first checked `Amazon Web Services IoT Platform`, under which I added my Endpoint Hostname from my AWS account leaving all the rest of the options set to default . `AWS IoT MQTT Port` is set to 8883.
I then run `make app-flash monitor`, it compiles just fine, my code already has the example setup to get the time from NTP servers and it successfully gets that time but after that it throws me the error I have mentioned above and AWS does not work. What am I doing wrong here?

### Code to reproduce this issue

[main.cpp](https://gist.github.com/sheikhumar93/aac65b274b149f03a28a5b04590f01c6)

## Debug Logs

```
D (1492) event: SYSTEM_EVENT_STA_CONNECTED, ssid:Sheikh's Ground, ssid_len:15, bssid:14:d6:4d:36:e8:36, channel:2, authmode:3
D (1500) tcpip_adapter: dhcp client init ip/mask/gw to all-0
D (1505) tcpip_adapter: if0 start ip lost tmr: enter
D (1510) tcpip_adapter: if0 start ip lost tmr: no need start because netif=0x3ffc5d34 interval=120 ip=0
D (1521) tcpip_adapter: dhcp client start successfully
D (3221) tcpip_adapter: if0 dhcpc cb
D (3222) tcpip_adapter: if0 ip changed=1
D (3222) event: SYSTEM_EVENT_STA_GOT_IP, ip:192.168.0.105, mask:255.255.255.0, gw:192.168.0.1
I (3227) event: sta ip: 192.168.0.105, mask: 255.255.255.0, gw: 192.168.0.1
I (3234) Example: Initializing SNTP
I (3240) Example: Waiting for system time to be set... (1/10)
I (5245) Example: The current date/time in Pakistan is: Sun Aug 12 17:39:48 2018
I (5245) Example: AWS IoT SDK Version 3.0.1-
E (5252) Example: aws_iot_mqtt_init returned error : -2
abort() was called at PC 0x400d3210 on core 1
```

**Comment by mahavirj** [comment]
@sheikhumar93 
Returned error -2 indicates `null value for required parameter`. Could you please check along those lines at https://github.com/espressif/aws-iot-device-sdk-embedded-C/blob/299183238ffe7a3e6a5ca0af9db19c10eaca62cf/src/aws_iot_mqtt_client.c#L215
