### ISSUE TITLE
[TW#25604] Tx Power in BLE ADV data not updated when Tx Power is changed.

### ISSUE THREAD

**Issue by mws-rmain** [espressif/esp-idf#2304]
When configuring BLE advertising data, and the flag is set to include TxPower:
`esp_ble_adv_data_t m_advData;
m_advData.include_txpower = true;`

... and Tx Power for advertisment is set with (for instance):
`esp_ble_tx_power_set( ESP_BLE_PWR_TYPE_ADV, ESP_PWR_LVL_P9 );`
(NOTE: the call above to set TxPower is made BEFORE advertising starts).

The TxPower value that is included in BLE advertising data is NOT the (correct) updated TxPower; it remains at -21dBm (apparently the default value).

This has been verified with latest commit esp-idf (020ade6).

See also #2284 

Further details [here](https://esp32.com/viewtopic.php?f=13&t=6553&p=29201#p29201).

**Comment by TianHao-Espressif** [comment]
Please see #2284, it's resolved.
