### ISSUE TITLE
[TW#25601] Bug in esp-idf\components\driver\spi_common.c

### ISSUE THREAD

**Issue by karawin** [espressif/esp-idf#2307]
## Environment

- Development Kit:      [ESP32-Wrover-Kit|]
- Kit version (for WroverKit/PicoKit/DevKitC): [v1|v2|v3|v4]
- Core (if using chip or module): [ESP32-Wrover-I|ESP32-Wrover|ESP32-PICO-D4|ESP32-SOLO-I|ESP32-WROOM-32U|ESP-WROOM-32D|ESP-WROOM32|ESP32]
- IDF version (``git rev-parse --short HEAD`` to get the commit id.): 020ade652
    //bd6ea4393c7d2f059fc4decc70f1ec3eb3597268
- Development Env:		[other]
- Operating System:		[Windows|Ubuntu|MacOS]
- Power Supply:         [USB|external 5V|]

## Problem Description
Cache disabled but cached memory region accessed on time to time on spi master

Diagnostic:
A call to void  spicommon_setup_dma_desc_links(lldesc_t *dmadesc, int len, const uint8_t *data, bool isrx)
in static void SPI_MASTER_ISR_ATTR spi_intr(void *arg)  fails because spicommon_setup_dma_desc_links is not an IRAM_ATTR function.
This function is called in spi_intr on line  641 and 670

Adding IRAM_ATTR in esp-idf\components\driver\spi_common.c
line 333 ie:
void IRAM_ATTR spicommon_setup_dma_desc_links(lldesc_t *dmadesc, int len, const uint8_t *data, bool isrx)
solved the problem.

**Comment by ginkgm** [comment]
Hi @karawin .
Thanks for reporting this, we'll fix it.
