### ISSUE TITLE
Build error with 'do while' loop on release optimization level (IDFGH-324)

### ISSUE THREAD

**Issue by laszlopataki** [espressif/esp-idf#2308]
## Environment

- Development Kit:      none
- IDF version: //020ade65
- Development Env:		Make
- Operating System:		Windows

## Problem Description

The following error message is returned when I was using a 'do while' loop and have put an array in the test expression.
The problem only exists if I compile on release optimization level.

```sh
$ make
...
CC build/main/loop_failure_main.o
C:\msys32\tmp\ccfLtEqO.s: Assembler messages:
C:\msys32\tmp\ccfLtEqO.s:59: Error: unknown opcode or format name 'lsiu'
make[1]: *** [.../esp/esp-idf/make/component_wrapper.mk:286: loop_failure_main.o] Error 1
make: *** [.../esp/esp-idf/make/project.mk:472: component-main-build] Error 2
```

### Expected Behavior

The project successfully builds.

### Actual Behavior

The assembler returns error.

### Steps to repropduce

1. Copy the code snippet into an empty project
2. Set the optimization level to release. 
3. Build with make

### Code to reproduce this issue

```cpp
#include <stdio.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "esp_system.h"
#include "esp_spi_flash.h"


void app_main()
{
	uint8_t i = 0;
	float sum = 0.0f;
	float samples[64] = {1.0, 2.0, 3.0, 4.0, 5.0};
	do{
		sum += samples[i];
		i++;
		printf("Loop\n");
	}while (i < 64 && samples[i] != 0);
    //It works with while() loop or without the 'samples[i] != 0' expression.
}
```

**Comment by igrr** [comment]
Preview release of the toolchain which fixes this issue is now available, see https://www.esp32.com/viewtopic.php?f=10&t=7400&p=31257#p41667.
