### ISSUE TITLE
Crash when using std::type_info::name()

### ISSUE THREAD

**Issue by v1993** [espressif/esp-idf#2309]
## Environment

- Development Kit:      noname
- Core (if using chip or module: ESP32D0WDQ6
- IDF version (``git rev-parse --short HEAD`` to get the commit id.): 30545f4c
- Development Env:		Make+Eclipse
- Operating System:		Ubuntu
- Power Supply:         USB

## Problem Description

I try to get exception type in order to debug, but it cause crash.

### Expected Behavior
`typeid(e).name()` will return type name
### Actual Behavior
`typeid(e).name()` crash system
### Steps to repropduce

1. Enable rtti using `CXXFLAGS += -frtti` in `Makefile.projbuild`
2. Catch exception with `catch(const std::exception& e)`
3. Try to get its type with `typeid(e).name()`
### Code to reproduce this issue

```cpp
} catch(const std::exception& e) {
	std::cout << "Exception of type " << typeid(e).name() << " has been thrown: " << e.what() << std::endl;
}
```

## Debug Logs

```
Guru Meditation Error: Core  0 panic'ed (LoadProhibited). Exception was unhandled.
Core 0 register dump:
PC      : 0x400d99dd  PS      : 0x00060b30  A0      : 0x800d1e3d  A1      : 0x3ffb8000
0x400d99dd: std::type_info::name() const at /home/v/compile/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/typeinfo:100
 (inlined by) app_main at /home/v/compile/esp32-sound-vorbis-test/main/main.cpp:209

A2      : 0x3ffb5e58  A3      : 0x00000000  A4      : 0x3ffba148  A5      : 0x3ffb8150
A6      : 0x00000000  A7      : 0x00000001  A8      : 0x800d99d6  A9      : 0x3ffb7fd0
A10     : 0x3ffb3d30  A11     : 0x00000000  A12     : 0x00000012  A13     : 0x3ffb3d30
A14     : 0x00000000  A15     : 0x3ffb7ea0  SAR     : 0x00000002  EXCCAUSE: 0x0000001c
EXCVADDR: 0x00000004  LBEG    : 0x4000c2e0  LEND    : 0x4000c2f6  LCOUNT  : 0x00000000

Backtrace: 0x400d99dd:0x3ffb8000 0x400d1e3a:0x3ffb80c0
0x400d99dd: std::type_info::name() const at /home/v/compile/xtensa-esp32-elf/xtensa-esp32-elf/include/c++/5.2.0/typeinfo:100
 (inlined by) app_main at /home/v/compile/esp32-sound-vorbis-test/main/main.cpp:209

0x400d1e3a: main_task at /home/v/compile/esp-idf/components/esp32/cpu_start.c:470
```

**Comment by igrr** [comment]
Hi @v1993, enabling RTTI support is tracked in https://github.com/espressif/esp-idf/issues/1684. I'm going to close this one as duplicate. Please follow the link and click "Subscribe" button there to receive further updates.
