### ISSUE TITLE
Asynchronous Websockets for ESP32

### ISSUE THREAD

**Issue by williamesp2015** [espressif/esp-idf#232]
I would like to migrate from ESP8266 to ESP32 using Asynchronous Websockets. Is there any changes to enable ESP32 for Asynchronous Websockets server and client?
Thank you

**Comment by negativekelvin** [comment]
Are you talking about https://github.com/me-no-dev/ESPAsyncWebServer ?

You should ask me-no-dev, post in the proper repo, or post in the arduino forum at esp32.com.  This isn't the best place for discussions about items outside the scope of this sdk.

**Comment by igrr** [comment]
This issue was moved to espressif/arduino-esp32#128
