### ISSUE TITLE
Wi-Fi TimeSync 

### ISSUE THREAD

**Issue by riataman** [espressif/esp-idf#2326]
It would be awesome to support Wi-FI TimeSync (https://www.wi-fi.org/discover-wi-fi/wi-fi-timesync) or some form of of high precision time synchronization (even if it only works between esp32s). I would allow for example to be able to implement multichannel wireless speakers.

**Comment by TimXia** [comment]
@riataman esp32 does not support WiFi TimeSync. It will be supported on next WiFi chip.

**Comment by riataman** [comment]
@TimXia you think espnow would be fast/predictable enough to timesync two devices to 100uS?
