### ISSUE TITLE
Feature request: Parameter or flag to skip bus init for esp_vfs_fat_sdmmc_mount (IDFGH-346)

### ISSUE THREAD

**Issue by TaraHoleInIt** [espressif/esp-idf#2327]
Hi.
This would be great for those of us who have an LCD or some other SPI peripheral attached on the same bus but also want to make use of the fat vfs component.
Of course I am aware that there are no built-in mechanisms to handle multiple devices on the bus, so the programmer would have to make sure to make sure the bus is only in used by one device at a time.

Maybe a new flag in sdmmc_host_t like SDMMC_HOST_FLAG_SKIP_INIT?
It's not elegant but it might be a temporary way to get things going.

**Comment by igrr** [comment]
Sorry for the slow turnaround. This has been implemented in https://github.com/espressif/esp-idf/commit/067f3d21c9f1f3bc76361a0e3cb656216f2583ff and will be part of the next minor release (v4.2).
