### ISSUE TITLE
[TW#25931] Issue with running gdb on ESP32 Wrover Dev Kit

### ISSUE THREAD

**Issue by RA5040** [espressif/esp-idf#2332]
## Environment

- Development Kit:   ESP32-Wrover-Kit

- esp-idf-v3.0.3

 - openocd-esp32-win32-0.10.0-esp32-20180724

- Development Env:		Command line

- Operating System:	Windows

## Problem Description

It appears that to run gdb on the ESP32 DevKit C, it's necessary to do things in this order:

1. Make and flash the program
2. Run OpenOCD
3. Run xtensa-esp32-elf-gdb

If OpenOCD is running before flashing the program nothing works.

The Espressif documentation says that OpenOCD should be running, then the program should be flashed, then gdb should be run: https://esp-idf.readthedocs.io/en/latest/api-guides/jtag-debugging/using-debugger.html#jtag-debugging-using-debugger-command-line

So there's either a bug in the code or a bug in the documentation

### Expected Behavior

OpenOCD should be running before flashing and starting gdb

### Actual Behavior

If OpenOCD is running the gdb fails

### Steps to reproduce

Using a ESP32WroverKit with built-in JTAG, follow the Espressif instructions to debug with JTAG in Windows to the letter, build and flash one of the IDF examples (for example blink), and you should see that dbg does not work.

Flash the program, then run OpenOCD, then run the xtensa gdb and hardware debugging should work.

Here is the gdb log:
===============
GNU gdb (crosstool-NG crosstool-ng-1.22.0-80-g6c4433a5) 7.10
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law. Type "show copying"
and "show warranty" for details.
This GDB was configured as "--host=i686-host_pc-mingw32 --target=xtensa-esp32-elf".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from build/blink.elf...done.
0x400d1ffa in app_main () at C:/msys32/home/Robert/esp/blink/main/blink.c:45
45 vTaskDelay(1000);
JTAG tap: esp32.cpu0 tap/device found: 0x120034e5 (mfg: 0x272 (Tensilica), part: 0x2003, ver: 0x1)
JTAG tap: esp32.cpu1 tap/device found: 0x120034e5 (mfg: 0x272 (Tensilica), part: 0x2003, ver: 0x1)
cpu0: Current bits set: BreakIn BreakOut RunStallIn
cpu1: Current bits set: BreakIn BreakOut RunStallIn
esp32: Debug controller was reset (pwrstat=0x5F, after clear 0x0F).
esp32: Core was reset (pwrstat=0x5F, after clear 0x0F).
Target halted. PRO_CPU: PC=0x5000004B (active) APP_CPU: PC=0x00000000
esp32: Core was reset (pwrstat=0x1F, after clear 0x0F).
Target halted. PRO_CPU: PC=0x40000400 (active) APP_CPU: PC=0x40000400
Hardware assisted breakpoint 1 at 0x400d1fdb: file C:/msys32/home/Robert/esp/blink/main/blink.c, line 43.
Target halted. PRO_CPU: PC=0x400D1FDB (active) APP_CPU: PC=0x400D1816
[New Thread 1073435384]
[New Thread 1073433996]
[New Thread 1073438040]
[New Thread 1073426884]
[New Thread 1073412716]
[New Thread 1073413484]
[New Thread 1073428016]
[Switching to Thread 1073432476]

Temporary breakpoint 1, app_main ()
at C:/msys32/home/Robert/esp/blink/main/blink.c:43
43 xTaskCreate(&blink_task, "blink_task", configMINIMAL_STACK_SIZE, NULL, 5, NULL); 
(gdb)

(note that it says temporary breakpoint at app_main (as per the 'thb app_main' parameter)
----> Now some gdb commands
(gdb) n
Note: automatically using hardware breakpoints for read-only addresses.
Target halted. PRO_CPU: PC=0x400D1FF4 (active) APP_CPU: PC=0x40080340
[New Thread 1073439548]
45 vTaskDelay(1000);
(gdb)

2nd N
(gdb) n
... nothing for quite a while then every 5 seconds or so one of these lines is printed:
Target halted. PRO_CPU: PC=0x400D1FFA (active) APP_CPU: PC=0x400D1816
Target halted. PRO_CPU: PC=0x400D1FFA (active) APP_CPU: PC=0x400D1816
Target halted. PRO_CPU: PC=0x400D1FFA (active) APP_CPU: PC=0x400D1816
Target halted. PRO_CPU: PC=0x400D1FFA (active) APP_CPU: PC=0x400D1816
Target halted. PRO_CPU: PC=0x400D1FFA (active) APP_CPU: PC=0x400D1816
Target halted. PRO_CPU: PC=0x400D1FFA (active) APP_CPU: PC=0x400D1816
Target halted. PRO_CPU: PC=0x400D1FFA (active) APP_CPU: PC=0x400D1816
Target halted. PRO_CPU: PC=0x400D1FFA (active) APP_CPU: PC=0x400D1816
Target halted. PRO_CPU: PC=0x400D1FFA (active) APP_CPU: PC=0x400D1816
=======================

and here is the OpenOCD log:
--------------------------------
Open On-Chip Debugger 0.10.0-dev (2018-07-24-09:39)
Licensed under GNU GPL v2
For bug reports, read
http://openocd.org/doc/doxygen/bugs.html
none separate
adapter speed: 20000 kHz
esp32 interrupt mask on
Info : ftdi: if you experience problems at higher adapter clocks, try the command "ftdi_tdo_sample_edge falling"
Info : clock speed 20000 kHz
Info : JTAG tap: esp32.cpu0 tap/device found: 0x120034e5 (mfg: 0x272 (Tensilica), part: 0x2003, ver: 0x1)
Info : JTAG tap: esp32.cpu1 tap/device found: 0x120034e5 (mfg: 0x272 (Tensilica), part: 0x2003, ver: 0x1)
cpu0: Current bits set: BreakIn BreakOut RunStallIn
cpu1: Current bits set: BreakIn BreakOut RunStallIn

>>>> now run app

Info : accepting 'gdb' connection on tcp/3333
Info : Target halted. PRO_CPU: PC=0x4009170E (active) APP_CPU: PC=0x400D1816
Info : Flash mapping 0: 0x10020 -> 0x3f400020, 23 KB
Info : Flash mapping 1: 0x20018 -> 0x400d0018, 77 KB
Info : Target halted. PRO_CPU: PC=0x4009170E (active) APP_CPU: PC=0x400D1816
Info : Auto-detected flash size 4096 KB
Info : Using flash size 4096 KB
Info : Target halted. PRO_CPU: PC=0x4009170E (active) APP_CPU: PC=0x400D1816
Info : Flash mapping 0: 0x10020 -> 0x3f400020, 23 KB
Info : Flash mapping 1: 0x20018 -> 0x400d0018, 77 KB
Info : Using flash size 80 KB
Info : Target halted. PRO_CPU: PC=0x4009170E (active) APP_CPU: PC=0x400D1816
Info : Flash mapping 0: 0x10020 -> 0x3f400020, 23 KB
Info : Flash mapping 1: 0x20018 -> 0x400d0018, 77 KB
Info : Using flash size 24 KB
Info : JTAG tap: esp32.cpu0 tap/device found: 0x120034e5 (mfg: 0x272 (Tensilica), part: 0x2003, ver: 0x1)
Info : JTAG tap: esp32.cpu1 tap/device found: 0x120034e5 (mfg: 0x272 (Tensilica), part: 0x2003, ver: 0x1)
cpu0: Current bits set: BreakIn BreakOut RunStallIn
cpu1: Current bits set: BreakIn BreakOut RunStallIn
Info : esp32: Debug controller was reset (pwrstat=0x5F, after clear 0x0F).
Info : esp32: Core was reset (pwrstat=0x5F, after clear 0x0F).
Info : Target halted. PRO_CPU: PC=0x5000004B (active) APP_CPU: PC=0x00000000
Info : esp32: Core was reset (pwrstat=0x1F, after clear 0x0F).
Info : Target halted. PRO_CPU: PC=0x40000400 (active) APP_CPU: PC=0x40000400
Info : Target halted. PRO_CPU: PC=0x400D1FDB (active) APP_CPU: PC=0x400D1816

----> After pressing 'N first time:
Info : Target halted. PRO_CPU: PC=0x400D1FF4 (active) APP_CPU: PC=0x40080340

----> After pressing 'N' 2nd time:
nothing for quite a long time then every 5 seconds or so a line is printed:
Info : Target halted. PRO_CPU: PC=0x400D1FFA (active) APP_CPU: PC=0x400D1816
Info : Target halted. PRO_CPU: PC=0x400D1FFA (active) APP_CPU: PC=0x400D1816
Info : Target halted. PRO_CPU: PC=0x400D1FFA (active) APP_CPU: PC=0x400D1816
Info : Target halted. PRO_CPU: PC=0x400D1FFA (active) APP_CPU: PC=0x400D1816
Info : Target halted. PRO_CPU: PC=0x400D1FFA (active) APP_CPU: PC=0x400D1816
Info : Target halted. PRO_CPU: PC=0x400D1FFA (active) APP_CPU: PC=0x400D1816
Info : Target halted. PRO_CPU: PC=0x400D1FFA (active) APP_CPU: PC=0x400D1816

--------------------------------

and here is the Blink code:
********************************
1	/* Blink Example
2	
3	This example code is in the Public Domain (or CC0 licensed, at your option.)
4	
5	Unless required by applicable law or agreed to in writing, this
6	software is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
7	CONDITIONS OF ANY KIND, either express or implied.
8	*/
9	#include <stdio.h>
10	#include "freertos/FreeRTOS.h"
11	#include "freertos/task.h"
12	#include "driver/gpio.h"
13	#include "sdkconfig.h"
14	
15	/* Can run 'make menuconfig' to choose the GPIO to blink,
16	or you can edit the following line and set a number here.
17	*/
18	#define BLINK_GPIO 2
19	
20	void blink_task(void *pvParameter)
21	{
22	/* Configure the IOMUX register for pad BLINK_GPIO (some pads are
23	muxed to GPIO on reset already, but some default to other
24	functions and need to be switched to GPIO. Consult the
25	Technical Reference for a list of pads and their default
26	functions.)
27	*/
28	gpio_pad_select_gpio(BLINK_GPIO);
29	/* Set the GPIO as a push/pull output */
30	gpio_set_direction(BLINK_GPIO, GPIO_MODE_OUTPUT);
31	while(1) {
32	/* Blink off (output low) */
33	gpio_set_level(BLINK_GPIO, 0);
34	vTaskDelay(1000 / portTICK_PERIOD_MS);
35	/* Blink on (output high) */
36	gpio_set_level(BLINK_GPIO, 1);
37	vTaskDelay(1000 / portTICK_PERIOD_MS);
38	}
39	}
40	
41	void app_main()
42	{
43	xTaskCreate(&blink_task, "blink_task", configMINIMAL_STACK_SIZE, NULL, 5, NULL);
44	while(true){
45	vTaskDelay(1000);
46	}
47	}

## Other items if possible

- [ ] sdkconfig file (attach the sdkconfig file from your project folder)
[sdkconfig.zip](https://github.com/espressif/esp-idf/files/2320892/sdkconfig.zip)

- [ ] elf file in the ``build`` folder (**note this may contain all the code details and symbols of your project.**)

[blink.zip](https://github.com/espressif/esp-idf/files/2320891/blink.zip)

**Comment by RA5040** [comment]
I was asked to run this again with -d3 on openocd. I attach the log.
[OpenOCDLog.zip](https://github.com/espressif/esp-idf/files/2321462/OpenOCDLog.zip)

**Comment by igrr** [comment]
This issue was moved to espressif/openocd-esp32#58
