### ISSUE TITLE
2 Questions: 1) Wifi.begin() connection speed 2) External interrupt while wifi.begin (IDFGH-349)

### ISSUE THREAD

**Issue by mojgithub** [espressif/esp-idf#2333]
## Environment

- Core (if using chip or module): [ESP32]
- Development Env:		[Arduino IDE]
- Operating System:		[Windows]
- Power Supply:         [external 3.3V]

## Problem Description

I have 2 questions regarding Wifi.begin().

1) When i start wifi.begin() i usually get connected in 10 seconds. Is this normal or is there any faster way? Why is this problem for me? See below question 2.

2) When wifi.begin() starts in those 10 seconds my external attachInterrupt doesn't trigger. My attachInterrupt works after wifi.begin finishes/connected.

So i those 10 seconds i cant log(rain sensor) attachInterrupt and this is problem for me.

Solutions?

A bit of my code.

### Code to reproduce this issue

```cpp

void IRAM_ATTR handleInterruptRain() {
  portENTER_CRITICAL_ISR(&sensorRain_mux);
  sensorRain_interruptCounter++;
  portEXIT_CRITICAL_ISR(&sensorRain_mux);
}

void setup() {
{

    pinMode(sensorRain_PIN, INPUT_PULLUP);
    attachInterrupt(digitalPinToInterrupt(sensorRain_PIN), handleInterruptRain, FALLING);

    while (WiFi.status() != WL_CONNECTED) {
       WifiSettings();
    }

    wd_timer_rain = timer.setInterval(10, readRain);
}

void readRain() {
    portENTER_CRITICAL(&sensorRain_mux);
    sensorRain_interruptCounter--;
    portEXIT_CRITICAL(&sensorRain_mux);

   do something ...
}

void WifiSettings() {

      WiFi.begin(ssid[RTC_SSID_position], password[RTC_SSID_position]);

      int waitTimeLimit = 15;
      unsigned int startTime = millis()/1000;
      unsigned int endTime= millis()/1000;

      while (WiFi.status() != WL_CONNECTED && (endTime - startTime) <= waitTimeLimit) {
        endTime = millis()/1000;
      }
      
      if (WiFi.status() == WL_CONNECTED) {
        #ifdef DEBUG_WIFI
          Serial.println(String("WIFI - Connected to ") + WiFi.SSID());
        #endif
      }
}

```

**Comment by projectgus** [comment]
Hi @mojgithub,

Sorry noone ever replied to you about this issue. As you're using arduino-esp32, the best place to discuss is the [Arduino subforum of esp32.com](https://esp32.com/viewforum.php?f=19) or the [arduino-esp32 issue tracker](https://github.com/espressif/arduino-esp32/issues/) if you think you've found a bug.
