### ISSUE TITLE
[TW#25934] Enhancement: JTAG docs set HW limits

### ISSUE THREAD

**Issue by michprev** [espressif/esp-idf#2335]
It might be a good idea to add
```
set remote hardware-breakpoint-limit 2
set remote hardware-watchpoint-limit 2
```
to [JTAG command line section](https://esp-idf.readthedocs.io/en/latest/api-guides/jtag-debugging/using-debugger.html#command-line) - gdbinit file (and probably also Eclipse section).

**Comment by gerekon** [comment]
@michprev I think it can be done for watchpoints. For breakpoints it will break SW flash breakpoints functionality, because they are [seen by GDB as HW ones](https://docs.espressif.com/projects/esp-idf/en/latest/api-guides/jtag-debugging/tips-and-quirks.html#jtag-debugging-tip-breakpoints).
