### ISSUE TITLE
[TW#25962] Extend esp_sleep_enable_XX() API to include UART and more

### ISSUE THREAD

**Issue by bearsh** [espressif/esp-idf#2340]
### Problem Description

The current `esp_sleep_enable_XXX()` API only includes support for some wake-up sources but not all like UART.

### Expected Behavior

Support for all wake-up sources (especially UART in my case)

**Comment by igrr** [comment]
This just happens to be in review at the moment, expect to be merged shortly.

**Comment by bearsh** [comment]
this sounds great, do you have a ETA for this?

**Comment by igrr** [comment]
Support for UART and GPIO wakeup has been merged in https://github.com/espressif/esp-idf/commit/13107d5968eb6b376b953dfadab55f903e8915a6.
