### ISSUE TITLE
Make menuconfig not works on Ubuntu 

### ISSUE THREAD

**Issue by augustocadini** [espressif/esp-idf#2356]
I'm follow this tutorial: https://dl.espressif.com/doc/esp-idf/latest/get-started/index.html#connect

But when I enter on the project folder and type `make menuconfig` apparentely the path is not configured, but when I type printenv I can see the paths.

![screenshot from 2018-09-01 12-07-01](https://user-images.githubusercontent.com/18659348/44947178-9261df00-addf-11e8-8cff-5faf87fca17d.png)
I did followed all steps on the espressif official tutorial.
ps. Putty not works too, but in the Arduino windows I Can up firmware.

**Comment by negativekelvin** [comment]
IDF_PATH should be one directory only and PATH should not have entry for project.mk

**Comment by augustocadini** [comment]
Sorry, I don't got it. DO you can help me?

**Comment by negativekelvin** [comment]
export IDF_PATH=/home/augusto/esp/esp-idf

**Comment by augustocadini** [comment]
I updated, my comment, I don't known which file I must edit

**Comment by projectgus** [comment]
If you use bash then you can put it in either .bashrc or .profile

However the setup guide recommends .profile. The full details are in the Getting Started guide for Linux:
https://docs.espressif.com/projects/esp-idf/en/stable/get-started/linux-setup.html#toolchain-setup
https://docs.espressif.com/projects/esp-idf/en/stable/get-started/add-idf_path-to-profile.html#add-idf-path-to-profile-linux-macos

Note that after editing .profile you will need to either log out and back in, or `source ~/.profile` in the current terminal, to get the new values.
