### ISSUE TITLE
python command not found

### ISSUE THREAD

**Issue by Oseihie** [espressif/esp-idf#2364]
Hi,
i have been trying to set up the bare metal development toolchain for windows as directed on this website: https://exploreembedded.com/wiki/Setting_up_Bare_Metal_Development_Toolchain_for_ESP32
and it has worked so far until the last point where you compile the project.
I get the error Python: command not found. i have attached a screenshot of the error message.

![esp32](https://user-images.githubusercontent.com/42789169/45000063-078d0a00-afc2-11e8-9bc6-0c8877105d4f.PNG)

Please, any solution to this?

**Comment by chegewara** [comment]
You have to start msys from file name: mingw32.exe not msys.exe or mingw64.exe

**Comment by projectgus** [comment]
I think following @chegewara's advice will fix this, but if not then please try following the official setup guide and then let us know if you still experience problems:
