### ISSUE TITLE
make monitor crash : UnicodeDecodeError: 'ascii' codec can't decode byte

### ISSUE THREAD

**Issue by psykokwak-com** [espressif/esp-idf#2366]
## Environment

- IDF version: e54f3d961
- Development Env: mingw32
- Operating System: Windows 10

## Problem Description
Since my last IDF update, "make monitor" crashs with the following python callstack

> Traceback (most recent call last):
>   File "C:/msys32/home/Jyce/esp/esp-idf/tools/idf_monitor.py", line 770, in <module>
>     main()
>   File "C:/msys32/home/Jyce/esp/esp-idf/tools/idf_monitor.py", line 685, in main
>     monitor.main_loop()
>   File "C:/msys32/home/Jyce/esp/esp-idf/tools/idf_monitor.py", line 357, in main_loop
>     self.handle_serial_input(data)
>   File "C:/msys32/home/Jyce/esp/esp-idf/tools/idf_monitor.py", line 416, in handle_serial_input
>     self.console.write_bytes(line + b'\n')
>   File "C:/msys32/mingw32/lib/python2.7/site-packages/serial/tools/miniterm.py", line 63, in write_bytes
>     self.byte_output.write(byte_string)
>   File "C:/msys32/home/Jyce/esp/esp-idf/tools/idf_monitor.py", line 737, in write
>     data = data.encode('latin-1')
> UnicodeDecodeError: 'ascii' codec can't decode byte 0xff in position 0: ordinal not in range(128)
> make: *** [/home/Jyce/esp/esp-idf/components/esptool_py/Makefile.projbuild:106: monitor] Error 1

How to fix it ?
Thanks.

**Comment by dobairoland** [comment]
This is a duplicate of https://github.com/espressif/esp-idf/issues/2348. 
The solution can be found here: https://github.com/espressif/esp-idf/issues/2348#issuecomment-417623220 and will be soon in `master`.

**Comment by psykokwak-com** [comment]
Thanks.
