### ISSUE TITLE
'CONFIG_ESP32_PHY_MAX_TX_POWER' undeclared here

### ISSUE THREAD

**Issue by ESP32DE** [espressif/esp-idf#237]
hi 
it seems if we deactivate WiFi 
there is no deactivate in the phy_init_data.h

> CC phy_init.o
> In file included from C:/sdk32/esp-idf/components/esp32/phy_init.c:30:0:
> C:/sdk32/esp-idf/components/esp32/phy_init_data.h:74:37: error: >
>'CONFIG_ESP32_PHY_MAX_TX_POWER' undeclared here (not in a function)
>         .target_power_qdb_0 = LIMIT(CONFIG_ESP32_PHY_MAX_TX_POWER * 4, 0, 78),
>                                                       
> C:/sdk32/esp-idf/components/esp32/phy_init_data.h:20:33: note: in definition of macro 'LIMIT'
>  #define LIMIT(val, low, high) ((val < low) ? low : (val > high) ? high : val)
                                 

workaround for me in the meantime for project without WiFi that compile is simply comment the lines:
https://github.com/espressif/esp-idf/blob/master/components/esp32/phy_init_data.h#L74

![phy_max_tx_power](https://cloud.githubusercontent.com/assets/16070445/21960864/898fa558-daf8-11e6-814f-19f415608d5c.png)

 
best wishes
rudi ;-)

**Comment by negativekelvin** [comment]
https://github.com/espressif/esp-idf/issues/230
