### ISSUE TITLE
[TW#26167] Class of device not set in inquiry scan

### ISSUE THREAD

**Issue by mekm** [espressif/esp-idf#2373]
## Environment

- Development Kit:      [none]
- Kit version (for WroverKit/PicoKit/DevKitC): [-]
- Core (if using chip or module): [ESP32]
- IDF version (``git rev-parse --short HEAD`` to get the commit id.): 
    //d91c425178d4e37b72178c231b5cc50b7ab157e2
- Development Env:		[other]
- Operating System:		[Windows]
- Power Supply:         [external 3.3V]

## Problem Description

Class of device is set on device using HCI-command. Success returned as result. When device shows up in inquiry scan, all fields (mac, name, rssi etc) seems correct, but not the cod - class of device value. It seems not change whatever value is set.

### Expected Behavior

Value that was set with esp_bt_gap_set_cod should be published on inquiry scan result for device

### Actual Behavior
Codvalue is not set. Does not seem to be changed by esp_bt_gap_set_cod, whatever value is set.
Cod shown 0x14042C

### Steps to reproduce

1. use example btt_spp_acceptor 
2. call esp_bt_gap_set_cod(codevalue, esp_set_cod_type)
3. run inquiry scan on other device to read out the cod. invalid value is shown - not the value that was set.

**Comment by blueMoodBHD** [comment]
Hi @mekm , There are some precautions as follow:
1. Should call `esp_bt_gap_set_cod()` before `esp_bt_gap_set_scan_mode()`
2. Pay attention to `esp_bt_cod_mode_t`, refer to the comments in `esp_gap_bt_api.h`

Please check and test again, thanks.
