### ISSUE TITLE
[TW#26168] tcp server can not send keepalive

### ISSUE THREAD

**Issue by 1163167506** [espressif/esp-idf#2374]
Esp32 can't send keepalive messages as tcpserver?

code:
Int keepAlive = 1;
Int keepIdle = 20;
Int keepInterval = 3;
Int keepCount = 3;

Setsockopt (listenfd, SOL_SOCKET, SO_KEEPALIVE, (void*) &keepAlive, sizeof (keepAlive));
Setsockopt (listenfd, IPPROTO_TCP, TCP_KEEPIDLE, (void*) &keepIdle, sizeof (keepIdle));
Setsockopt (listenfd, IPPROTO_TCP, TCP_KEEPINTVL, (void*) &keepInterval, sizeof (keepInterval));
Setsockopt (listenfd, IPPROTO_TCP, TCP_KEEPCNT, (void*) &keepCount, sizeof (keepCount));

I set esp32 as TCP client to send keepalive messages success.

But setting esp32 as TCP server can't send keepalive messages.

**Comment by liuzfesp** [comment]
@1163167506 for TCP server, you need to set the keep alive options to each accepted socket, not set to the listen socket.

**Comment by asidika** [comment]
Hi, currently i m facing with this issue, I could not set keepalive option. 
can anyone share a code snip which enables keep alive socket option?

**Comment by liuzfesp** [comment]
Hi @asidika I think @1163167506 already give the demo code.
