### ISSUE TITLE
[TW#26170] Bluetooth keeps disconnecting < 2 minutes - Bonded devices

### ISSUE THREAD

**Issue by wegunterjr** [espressif/esp-idf#2378]
## Environment

- Core (if using chip or module): [ESP32-Wrover]
- IDF version 3.0.3 Released version   (3.30003.0)
- Development Env:		[PlatformIO]
- Operating System:		[Windows]
- Power Supply:         [USB]

## Problem Description

After successful connection to ESP32 (setup as server), after < 2 minutes, it will disconnect.
I can send messages while it is connected, but will disconnect. I have to find the device again and reconnect. Once connected I can send messages again
.

- [ ] coredump 
`[0;32mI (3268167) GATTS_TABLE: switch ␛[0m
␛[0;32mI (3268167) GATTS_TABLE: remote BD_ADDR: ␛[0m
␛[0;32mI (3268167) GATTS_TABLE: address type = 0␛[0m
␛[0;32mI (3268177) GATTS_TABLE: pair status = fail␛[0m
␛[0;32mI (3268177) GATTS_TABLE: Bonded devices number : 1
␛[0m
␛[0;32mI (3268187) GATTS_TABLE: Bonded devices list : 1
␛[0m
␛[0;32mI (3268187) GATTS_TABLE: ␛[0m
␛[0;31mE (3268287) BT: btm_sec_clr_temp_auth_service() - no dev CB
␛[0m
␛[0;31mE (3268287) BT: Device not found
␛[0m
␛[0;31mE (3268287) BT: BTA got unregistered event id 31
␛[0m
␛[0;31mE (3268287) BT: BTA got unregistered event id 31
␛[0m
heap size after gatts_event_handler = 132324 ...
 this is the event: 0heap size in the gatts idx = 132324 ...`

**Comment by Weijian-Espressif** [comment]
@wegunterjr  from the log,  smp is failed, it will disconnect in 30s. 
1. what your client is ?
2. Can you test with our gatt_security_server demo

**Comment by FayeY** [comment]
Closing due to lack of response, please feel free to reopen if this is still an issue and you can supply more details.
Thanks.
