### ISSUE TITLE
how do i config I2S of HF Client SCO data callback? (IDFGH-359)

### ISSUE THREAD

**Issue by nulldsming** [espressif/esp-idf#2380]
## Environment
- Development Kit:      [ESP32-DevKitC]

**Comment by kewalmshah** [comment]
@nulldsming can you please elaborate your query in a little more detail, Thanks

**Comment by Alvin1Zhang** [comment]
@nulldsming Could you help provide more details? Thanks.

**Comment by Alvin1Zhang** [comment]
@nulldsming Could you help provide more details? Thanks.

**Comment by Alvin1Zhang** [comment]
@nulldsming Could you help share if any updates for this issue? Thanks.

**Comment by Alvin1Zhang** [comment]
Close due to short of feedback.
