### ISSUE TITLE
[TW#26176] update for "install prerequisites"

### ISSUE THREAD

**Issue by csylvain** [espressif/esp-idf#2384]
add "texinfo help2man libtool-bin" to the list of Ubuntu and Debian packages
at https://docs.espressif.com/projects/esp-idf/en/stable/get-started/linux-setup-scratch.html

change:
sudo apt-get install git wget make libncurses-dev flex bison gperf python python-serial

to:
sudo apt-get install git wget make libncurses-dev flex bison gperf python python-serial texinfo help2man libtool-bin python-pip

why? "configure --enable-local" does not complete without them (except python-pip).
python-pip is necessary to "make flash"

**Comment by dobairoland** [comment]
Hello @csylvain. Thank you for pointing out inconsistencies in the documentation. 

Actually, not just the "Install Prerequisites" but also "Install dependencies" from "Compile the Toolchain from Source" should be installed. There are `texinfo`, `help2man` and `libtool-bin` packages included for Ubuntu 16.04. The same commands need to be run for newer Ubuntu releases as well. I tested the commands on a new Ubuntu 18.04 LTS installation and they work well. I corrected this and other inconsistencies in the documentation.

This issue will be closed when my changes get pushed to master (v3.3). The documentation update for v3.2 and v3.1 will be released with some delay (all relevant commits will be referenced here).
