### ISSUE TITLE
scan response with ADV_TYPE_NONCONN_IND mode

### ISSUE THREAD

**Issue by chegewara** [espressif/esp-idf#2412]
Hi @Weijian-Espressif, sorry for my ignorance, but is it correct behavior when scan response is not sent when advertising is set type to `ADV_TYPE_NONCONN_IND`? With `ADV_TYPE_IND` all seems to be ok. Tested with nRF connect.

**Comment by negativekelvin** [comment]
> 4.4.2.6 Non-connectable Undirected Event Type
> When the non-connectable undirected event type is used, non-connectable
> advertising indications (ADV_NONCONN_IND PDU) packets are sent by the
> Link Layer.
> The non-connectable undirected event type allows a scanner to receive
> information contained in the ADV_NONCONN_IND PDU from the advertiser.
> The advertiser shall either move to the next used advertising channel index or
> close the advertising event after each ADV_NONCONN_IND PDU that is sent.
> **The Link Layer does not listen, and therefore cannot receive any requests from
> scanners or initiators.**

**Comment by chegewara** [comment]
thanks
