### ISSUE TITLE
Consideration: remove *_struct.h register files

### ISSUE THREAD

**Issue by michprev** [espressif/esp-idf#2413]
I believe it would be a good idea to completely remove *_struct.h register files for several reasons:

- GCC does not always play nicely with bitfields (https://github.com/espressif/esp-idf/issues/597)

- there is no reason for keeping two files describing the same

- there are many registers missing in *_struct files

**Comment by igrr** [comment]
Hi @michprev,
A lot of existing code uses structs for peripheral register access, and rewriting all that code to use macros for register access might be a quite significant undertaking... especially if we consider projects not written by Espressif.
We are doing some work to reduce differences between registers described in _reg files, _struct files, and the TRM. I can't give any timeline for this yet, but the plan is to have all three consistent.
Regarding #597, we will revisit it and at least try to generate some warning when such situation occurs.
