### ISSUE TITLE
Problem with make flash

### ISSUE THREAD

**Issue by shadow5353** [espressif/esp-idf#2417]
When I use "make flash" I get this error message: https://gist.github.com/shadow5353/72a4dfec0de65b1380551203193d5d33. I am using the Hello_World example, also the code is linked here: https://gist.github.com/shadow5353/72a4dfec0de65b1380551203193d5d33. I can use the command "make simple_monitor" without any error messages.

I have installed xtensa-esp32-elf using this guide: https://docs.espressif.com/projects/esp-idf/en/stable/get-started/linux-setup.html

**Result of printenv IDF_PATH:** /home/jaah/esp/esp-idf
**Result of printenv PATH:** /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/jaah/esp/xtensa-esp32-elf/bin
**OS:** Ubuntu 18.04

I can use "xtensa-esp32-elf-gcc -v" in the terminal.

**Comment by tzxespressio** [comment]
because `make simple_monitor` has not used command  `xtensa-esp32-elf-gcc`,only call some python scripts,you can try to printenv in Makefile when compile object.

**Comment by shadow5353** [comment]
I got make flash to work, seems I only had made the path for my profile only.
