### ISSUE TITLE
how to get music information from avrc (IDFGH-373)

### ISSUE THREAD

**Issue by donny681** [espressif/esp-idf#2418]
`
/// AVRC metadata attribute mask

typedef enum {

    ESP_AVRC_MD_ATTR_TITLE = 0x1,                 /*!< title of the playing track */

    ESP_AVRC_MD_ATTR_ARTIST = 0x2,                /*!< track artist */

    ESP_AVRC_MD_ATTR_ALBUM = 0x4,                 /*!< album name */

    ESP_AVRC_MD_ATTR_TRACK_NUM = 0x8,             /*!< track position on the album */

    ESP_AVRC_MD_ATTR_NUM_TRACKS = 0x10,           /*!< number of tracks on the album */

    ESP_AVRC_MD_ATTR_GENRE = 0x20,                /*!< track genre */

    ESP_AVRC_MD_ATTR_PLAYING_TIME = 0x40          /*!< total album playing time in miliseconds */

} esp_avrc_md_attr_mask_t;`

 I see the enum esp_avrc_md_attr_mask_t in esp_avrc_api.h and I think that it can get the music information by avrc .How can I use the enum?I can't found the demo.

**Comment by mywang-espressif** [comment]
You can refer to the a2dp_sink example in ESP-IDF.

Use the API "esp_avrc_ct_send_metadata_cmd", and then wait for the callback event "ESP_AVRC_CT_METADATA_RSP_EVT" with music information from peer device.

**Comment by donny681** [comment]
Great,But how can I get the lyrics of music?

**Comment by mywang-espressif** [comment]
I am afraid that I don't find the feature of lyric transmission in AVRCP specification. According to the spec. the Metadata Attributes for Current Media Item can be collected on the Controller side, these attributes include:
- title
- artist name
- album name
- track number
- total number of tracks
- genre
- playing time
- default cover art

Most of the attributes in the above list are supported in ESP-IDF, as indicated in enum `esp_avrc_md_attr_mask_t`, but there is no such a "lyric" attribute.

**Comment by Alvin1Zhang** [comment]
@donny681 Thanks for reporting the issue, feel free to reopen if the issue still exists. Thanks.
