### ISSUE TITLE
[TW#26322] Mesh using NVS, crashes IRAM ISR ...

### ISSUE THREAD

**Issue by edjeed** [espressif/esp-idf#2419]
When a layer changes in the MESH network, the new layer is written to NVS by the mesh stack.
All interrupts that run in IRAM are not accessible when writing to NVS, so errors occur....

Is there a way to disable the use of NVS in the MESH stack?

It would be nice if it uses the same storage as the WiFi:
esp_wifi_set_storage(WIFI_STORAGE_RAM);

Edjeed

**Comment by igrr** [comment]
@edjeed Could you please post or attach the crash dump, decoded using idf_monitor (`make monitor`)?
This crash dump will likely point to the function you are calling from an ISR, which is not in IRAM. The rule for ISRs placed into IRAM is that they must not call functions which aren't in IRAM. If you place an ISR into IRAM, then all the code it calls must be in IRAM.

**Comment by edjeed** [comment]
@igrr I changed a lot of code, if the error occurs again I will post the dump... Thanks for the fast reply.
@dongdong004 Thanks!!!

**Comment by Alvin1Zhang** [comment]
@edjeed Could you help share if any updates for this issue? Thanks.

**Comment by Alvin1Zhang** [comment]
Feel free to reopen, thanks. @edjeed
