### ISSUE TITLE
[TW#26343] [question] ble gattc cache data access

### ISSUE THREAD

**Issue by chegewara** [espressif/esp-idf#2422]
In menuconfig is option to save gattc cache data to NVS. Now i have few questions:
- does it use part of nvs partition (im guessing it does),
- how much space its used by cache from nvs partition, its crucial question because we need to consider nvs partition size according to this

**Comment by Weijian-Espressif** [comment]
@chegewara 
Yes, gattc cache will be saved in flash.
Flash size depends on your gatts service. You can refer to config_save() in config.c file.
The value of "w_cnt_total" is the size of the flash consumed.
