### ISSUE TITLE
[TW#26349] How to use the internal_communication example to verify the MESH

### ISSUE THREAD

**Issue by TobeChan** [espressif/esp-idf#2427]
hi everyone:

i have two of ESP32,but i don't know how to use them to verify mesh.i try to use "make menuconfig" to config param, but logging like that:

I (1303) mesh_main: <MESH_EVENT_STARTED>ID:77:77:77:77:77:77
I (1303) mesh_main: mesh starts successfully, heap:186488, root fixed

I (1663) mesh: [SCAN][ch:1]AP:10, otherID:0, MAP:0, idle:0, candidate:0, root:0,
 topMAP:0[c:0,i:0]
I (1663) mesh: [FAIL][1]root:0, fail:1, normal:0, <pre-root>backoff:0

I (2033) mesh: [SCAN][ch:1]AP:13, otherID:0, MAP:0, idle:0, candidate:0, root:0,
 topMAP:0[c:0,i:0]router found
I (2033) mesh: [FAIL][2]root:0, fail:2, normal:0, <pre-root>backoff:0

I (2393) mesh: [SCAN][ch:1]AP:12, otherID:0, MAP:0, idle:0, candidate:0, root:0,
 topMAP:0[c:0,i:0]router found

OR:

I (1314) mesh_main: <MESH_EVENT_STARTED>ID:77:77:77:77:77:77
I (1314) mesh_main: mesh starts successfully, heap:185404, root fixed

W (1674) wifi: scan number 0

I (1674) mesh: [SCAN][ch:12]AP:0, otherID:0, MAP:0, idle:0, candidate:0, root:0,
 topMAP:0[c:0,i:0]
I (1674) mesh: [FAIL][1]root:0, fail:1, normal:0, <pre-root>backoff:0

W (2034) wifi: scan number 0

I (2034) mesh: [SCAN][ch:12]AP:0, otherID:0, MAP:0, idle:0, candidate:0, root:0,
 topMAP:0[c:0,i:0]
I (2034) mesh: [FAIL][2]root:0, fail:2, normal:0, <pre-root>backoff:0

W (2404) wifi: scan number 0

Maybe something was overlooked by me.
can you show me how to verify  it ?Thanks!

**Comment by dongdong004** [comment]
It seems that the device can not find router. Have you config your router correctly?
* Make sure router ssid & password have been configured.
* Router channel must be configured.  `[SCAN][ch:1]` means scaning on channel 1.
* If router is hidden, bssid must be configured.
* `root fixed` shouldn't be set if you want to use self-healing network. `mesh starts successfully, heap:185404, root fixed` 
* `router found` will be printed in the same line with `[SCAN][ch:1]` if the device find the router you set.

**Comment by TobeChan** [comment]
Thanks !I will check it.

**Comment by TobeChan** [comment]
I use WIFI demo to get the WIFI channel,but the monitor show:
I (13051) wifi: state: assoc -> run (10)
I (13321) wifi: connected with Coretest, channel 10
I (13331) wifi: pm start, type: 0

I (13331) mesh: [scan]new scanning time:600ms
W (13331) wifi: [beacon]new interval:300ms
E (13331) event: invalid static ip
W (13331) mesh_main: <MESH_EVENT_ROUTING_TABLE_REMOVE>remove 1, new:1
I (13341) mesh_main: <MESH_EVENT_PARENT_CONNECTED>layer:0-->1, parent:28:6c:07:3
3:aa:74<ROOT>, ID:77:77:77:77:77:77
I (13341) mesh: <nvs>write layer:1
I (13351) mesh_main: <MESH_EVENT_ROOT_ADDRESS>root address:30:ae:a4:17:93:49
W (13361) mesh_main: [#RX:1/1][L:1] parent:28:6c:07:33:aa:74, receive from 30:ae
:a4:17:93:48, size:1460, heap:177540, flag:0[err:0x0, proto:0, tos:0]
I (14231) mesh_main: <MESH_EVENT_ROOT_GOT_IP>sta ip: 192.168.31.95, mask: 255.25
5.255.0, gw: 192.168.31.1
I (14231) event: sta ip: 192.168.31.95, mask: 255.255.255.0, gw: 192.168.31.1
W (14361) mesh_main: [#RX:2/2][L:1] parent:28:6c:07:33:aa:74, receive from 30:ae
:a4:17:93:48, size:1460, heap:178160, flag:0[err:0x0, proto:0, tos:0]
W (15361) mesh_main: [#RX:3/3][L:1] parent:28:6c:07:33:aa:74, receive from 30:ae
:a4:17:93:48, size:1460, heap:176460, flag:0[err:0x0, proto:0, tos:0]
W (16361) mesh_main: [#RX:4/4][L:1] parent:28:6c:07:33:aa:74, receive from 30:ae
:a4:17:93:48, size:1460, heap:178160, flag:0[err:0x0, proto:0, tos:0]

**Comment by TobeChan** [comment]
**E (13331) event: invalid static ip**

**Comment by TobeChan** [comment]
if i use two esp32 run this demo 
One monitor printf:
I (134702) mesh: [tx-wifi]invalid interface
E (134712) mesh_main: [ROOT-2-UNICAST:121][L:1]parent:28:6c:07:33:aa:74 to 30:ae:a4:1e:94:c4, heap:175708[err:0xffffff
ff, proto:0, tos:0]
tx
W (135722) mesh_main: [#RX:122/122][L:1] parent:28:6c:07:33:aa:74, receive from 30:ae:a4:17:93:48, size:1460, heap:175
708, flag:0[err:0x0, proto:0, tos:0]
rx
I (135722) mesh: [tx-wifi]tx not allowed
I (135732) mesh: [tx-wifi]tx post fail
I (135732) mesh: [tx-wifi]tx q full
I (135732) mesh: [tx-wifi]invalid interface
E (135742) mesh_main: [ROOT-2-UNICAST:122][L:1]parent:28:6c:07:33:aa:74 to 30:ae:a4:1e:94:c4, heap:175708[err:0xffffff
ff, proto:0, tos:0]
tx
1 MESH_LIGHT_PINK
W (136752) mesh_main: [#RX:123/123][L:1] parent:28:6c:07:33:aa:74, receive from 30:ae:a4:17:93:48, size:1460, heap:175
708, flag:0[err:0x0, proto:0, tos:0]
rx
I (136752) mesh: [tx-wifi]tx not allowed
I (136762) mesh: [tx-wifi]tx post fail
I (136762) mesh: [tx-wifi]tx q full
I (136762) mesh: [tx-wifi]invalid interface
E (136772) mesh_main: [ROOT-2-UNICAST:123][L:1]parent:28:6c:07:33:aa:74 to 30:ae:a4:1e:94:c4, heap:175708[err:0xffffff
ff, proto:0, tos:0]
Other printf:
I (1382) mesh_main: <MESH_EVENT_STARTED>ID:77:77:77:77:77:77
I (1382) mesh_main: mesh starts successfully, heap:181656, root not fixed

I (1682) mesh: [SCAN][ch:10]AP:5, otherID:0, MAP:1, idle:0, candidate:1, root:1, topMAP:0[c:0,i:0]ro
uter found<>
I (1682) mesh: 5911[selection]try rssi_threshold:-78, backoff times:0, max:5<-78,-82,-85>
I (1692) mesh: [DONE]connect to parent:ESPM_17934, rssi:-32, 30:ae:a4:17:93:49[layer:1, assoc:0], m
y_vote_num:0/voter_num:0, rc[00:00:00:00:00:00/-120]
I (3262) wifi: n:10 2, o:10 0, ap:10 2, sta:10 2, prof:10
I (4252) wifi: state: init -> auth (b0)
I (4252) wifi: state: auth -> assoc (0)
I (4272) wifi: state: assoc -> run (10)
I (7612) mesh: <MESH_NWK_ROOT_ADDR>from system, layer:2, root_addr:30:ae:a4:17:93:49
I (7612) mesh: <MESH_NWK_ROOT_ADDR>idle, layer:2, root_addr:30:ae:a4:17:93:49, conflict_roots.num:0<
>
I (7622) mesh_main: <MESH_EVENT_ROOT_ADDRESS>root address:30:ae:a4:17:93:49
I (14272) wifi: state: run -> init (200)
I (14272) wifi: n:10 0, o:10 2, ap:10 2, sta:10 2, prof:10
I (14272) mesh_main: <MESH_EVENT_PARENT_DISCONNECTED>reason:204
I (14272) wifi: n:10 2, o:10 0, ap:10 2, sta:10 2, prof:10
I (14282) wifi: state: init -> auth (b0)
I (14272) mesh: [wifi]disconnected reason:204(), continuous:0/max:12, non-root, vote(,stopped)<><><>
<>
I (14292) wifi: state: auth -> assoc (0)
I (14292) wifi: state: assoc -> init (0)
I (14302) wifi: n:10 0, o:10 2, ap:10 2, sta:10 2, prof:10
I (14302) mesh_main: <MESH_EVENT_PARENT_DISCONNECTED>reason:202
I (14312) mesh: [wifi]disconnected reason:202(), continuous:1/max:12, non-root, vote(,stopped)<><><>
<>
I (14322) mesh: [wifi]disconnected reason, new:202(), old:204(), force
I (14322) wifi: n:10 2, o:10 0, ap:10 2, sta:10 2, prof:10
I (14332) wifi: state: init -> auth (b0)
I (14342) wifi: state: auth -> assoc (0)
I (14372) wifi: state: assoc -> run (10)
I (15292) mesh: <MESH_NWK_ROOT_ADDR>from system, layer:2, root_addr:30:ae:a4:17:93:49
I (15292) mesh: <MESH_NWK_ROOT_ADDR>idle, layer:2, root_addr:30:ae:a4:17:93:49, conflict_roots.num:0
<>
I (15302) mesh_main: <MESH_EVENT_ROOT_ADDRESS>root address:30:ae:a4:17:93:49
I (24372) wifi: state: run -> init (200)
I (24372) wifi: n:10 0, o:10 2, ap:10 2, sta:10 2, prof:10
I (24372) mesh_main: <MESH_EVENT_PARENT_DISCONNECTED>reason:204
I (24372) wifi: n:10 2, o:10 0, ap:10 2, sta:10 2, prof:10
I (24382) wifi: state: init -> auth (b0)
I (24372) mesh: [wifi]disconnected reason:204(), continuous:0/max:12, non-root, vote(,stopped)<><><>
<>
I (24392) wifi: state: auth -> init (0)
I (24392) wifi: n:10 0, o:10 2, ap:10 2, sta:10 2, prof:10
I (24402) mesh_main: <MESH_EVENT_PARENT_DISCONNECTED>reason:202

**Comment by dongdong004** [comment]
`E (13331) event: invalid static ip` This is because of that dhcp is stopped when establishing mesh network, it's not a issue

**Comment by dongdong004** [comment]
`mesh_main: <MESH_EVENT_PARENT_DISCONNECTED>reason:204`
The reason code 204 mainly caused by incorrect password. Please check the password you set and try again. It's better to use a newer version.

**Comment by Alvin1Zhang** [comment]
@TobeChan Hi, TobeChan, would you help share if your issue have been resolved or not? Thanks.

**Comment by Alvin1Zhang** [comment]
@TobeChan Feel free to reopen the issue, thanks.
