### ISSUE TITLE
Uart.c links are broken

### ISSUE THREAD

**Issue by guillaume55** [espressif/esp-idf#243]

**Comment by igrr** [comment]
Could you please describe which links are broken?

**Comment by guillaume55** [comment]
I'm sorry it was  esp-idf/docs/api/uart.rst : https://github.com/espressif/esp-idf/blob/8bcd341fcae23c534ea98f47d1ba33e1694a9e48/docs/api/uart.rst
The three "instruction" links give error 404

**Comment by igrr** [comment]
RST files don't render well when viewed on GitHub. You may check the actual generated document here: http://esp-idf.readthedocs.io/en/latest/api/uart.html.

Note that the links are just placeholders, they point to the documentation template.
