### ISSUE TITLE
[TW#26379] Can we gracefully disable softap while keeping sta connected with AP, without reconnect again?

### ISSUE THREAD

**Issue by outermanle** [espressif/esp-idf#2433]
## Environment

- Development Kit:      [ESP32-DevKitC]
- Kit version (DevKitC): [v4]
- Core (if using chip or module): [ESP-WROOM-32D]
- IDF version (eea49d250):
- Development Env:		[Make]
- Operating System:		[Ubuntu]
- Power Supply:         [USB]

## Problem Description

We generally use sta+softap mode as configure purpose, we configure station connect to AP with internet and other para to esp nvs. After station connect to AP, we want to disable AP mode and restore to station mode only.

Now, we need to call wifi stop api then set station mode only and reconnect again, this will lead to station disconnect with AP.

Can we gracefully disable softap while keeping station connected with AP, without reconnect again? 
But  I can't find specific api to disable softap mode only in sta+softap mode.

I think many application scenarios will need this api. Thanks a lot.

### Expected Behavior
In sta+soft mode, we can gracefully disable softap while keeping station connected with AP, without reconnect.

### Actual Behavior
Need to stop wifi then set station mode only and reconnect, this will lead to disconnect with AP.

### Steps to repropduce
100%

**Comment by liuzfesp** [comment]
@outermanle, you can call esp_wifi_set_mode(WIFI_MODE_STA) to sta + soft mode to sta only mode, no need to call esp_wifi_stop() to stop WiFi.

**Comment by outermanle** [comment]
I will try, thanks a lot!

**Comment by outermanle** [comment]
test passed，Thanks！

**Comment by ankitdaf** [comment]
Does this also work for all cases ? That is, can we switch from any mode (AP, STA, AP+STA) to any other mode (AP,STA,AP_STA) without calling esp_wifi_stop() followed by esp_wifi_start() ?

**Comment by liuzfesp** [comment]
Sure, @ankitdaf

**Comment by jhoney2016** [comment]
Is it possible to change from AP_STA to AP mode without stopping the soft AP
