### ISSUE TITLE
How can I tell if the current code is in an interrupted context?

### ISSUE THREAD

**Issue by ChampOnBon** [espressif/esp-idf#2435]
Is there a corresponding flag bit in the ESP-IDF or the register client determines whether the current code is in an interrupt context, similar to the IPSR register value obtained by the __get_IPSR() function in the Cortex-M kernel, and the _xt_isr_status variable in the ESP8266 RTOS SDK V2.0.0 value.

**Comment by mahavirj** [comment]
@ChampOnBon 
https://github.com/espressif/esp-idf/blob/master/components/freertos/port.c#L332
