### ISSUE TITLE
Linker scripts in user app

### ISSUE THREAD

**Issue by michprev** [espressif/esp-idf#2436]
Hi,
instead of adding `CONFIG_SPI_MASTER_IN_IRAM` or `CONFIG_SPI_MASTER_ISR_IN_IRAM` wouldn't it be better to have linker scripts in an user app directory (like it is done on ARM)?

Also consider this scenario:

- I want to use `CONFIG_FREERTOS_UNICORE` option

- I want to use interrupts on the core 1

- I need to provide my own interrupt vectors because ESP-IDF vectors use FreeRTOS

- how should I tell linker where to place my vectors?

**Comment by igrr** [comment]
The main problem with linker scripts in application is that sometimes IDF updates need to make changes to these linker scripts. For example, certain WiFi feature has been implemented, and a new rule to place some object file of WiFi library into IRAM is needed. If the user has a custom linker script in their app directory, changes which we need will not get propagated there, and the user will end up with a broken application.

So what we would like to have is a way for multiple components to define rules which place certain input sections or object files into specific output sections, and have linker take all these rules into account.

Such feature has been implemented and has been waiting for the new CMake build system to get merged into the master branch. Now that CMake support is in master branch, we will have this feature merged soon, as well.

**Comment by projectgus** [comment]
The Linker Script Generation feature that @igrr mentioned is now available:
https://docs.espressif.com/projects/esp-idf/en/latest/api-guides/linker-script-generation.html

> I need to provide my own interrupt vectors because ESP-IDF vectors use FreeRTOS
> how should I tell linker where to place my vectors?

Regarding this particular case, Xtensa CPUs are a bit more flexible than ARM. When starting up on CPU1, set the VecBase special register to the address of the interrupt vectors in IRAM. Done! See `components/esp32/cpu_start.c` for a snippet of assembler code which sets VecBase.

**Comment by HrMitrev** [comment]
Hi!
I have another use case for linker scripts in user app.
I am using esp32 in conjunction with stm32 and recently I added a feature to update stm32's firmware through esp32. For that case I need to embed the (up to 16kb) binary of the stm in esp32's firmware and I would like to use this method - https://stackoverflow.com/a/4158997/9145712
Is there a way to do something similar with the current idf release v4.2 ?
Now I use xxd and manually copy the output to a header file.

**Comment by projectgus** [comment]
Hi @HrMitrev,

It's not exactly the method linked there, but ESP-IDF has support for embedding binary data in the firmware as part of the build system. It should "just work":
https://docs.espressif.com/projects/esp-idf/en/v4.2/esp32/api-guides/build-system.html#embedding-binary-data
