### ISSUE TITLE
CURLlib Out of memor

### ISSUE THREAD

**Issue by TobeChan** [espressif/esp-idf#2476]
i have a problem  when use curl PUT method with wifi ,bluetooth,ethernet and openssl
the monitor show:

FTP PUT JPG FILE
 Upload received JPG file back to FTP server
I (4641) tcp: create socket ......
curl_easy_perform failed: Out of memory,27
ERROR: -7 [Out of memory]

if i close ethernet this error will disappear,how can  i fix this problem ?
some task like ethernet ,uart,ota,must be use.  the memory of esp32 was be run out? hope you can give me some suggest.Thanks!

**Comment by projectgus** [comment]
Hi @TobeChan ,

Sorry noone replied to you earlier.

It does look like ESP-IDF ran out of free memory. You can measure the overall free heap with these functions:
https://docs.espressif.com/projects/esp-idf/en/latest/api-reference/system/heap_debug.html#heap-information

We don't include "libcurl" as part of ESP-IDF, and one reason is that its resource usage can be quite high.  Maybe you can discuss this problem with whoever ported libcurl to ESP-IDF and see if they have any tips.

You may also find the new "HTTP Client" module in IDF to be of interest, its resource usage is probably lower than libcurl for similar functionality: https://docs.espressif.com/projects/esp-idf/en/latest/api-reference/protocols/esp_http_client.html
