### ISSUE TITLE
esp-idf v3.2 installation facing problem

### ISSUE THREAD

**Issue by sjoteppagol** [espressif/esp-idf#2486]
## Environment

- Development Kit:      [ESP32-Wrover-Kit|
- Kit version (for WroverKit/PicoKit/DevKitC): [v1|v2|v3|v4]
- Core (if using chip or module): ESP-WROOM-32D
- IDF version (``git rev-parse --short HEAD`` to get the commit id.): 135eef767
- Development Env:		[Make]
- Operating System:		[Windows]
- Power Supply:         [USB|external 5V|external 3.3V|Battery]

## Problem Description
After running make command I am getting this error message
I Have taken toolchain from **https://dl.espressif.com/dl/esp32_win32_msys2_environment_and_toolchain-20180110.zip**

//Detailed problem description goes here.

### Expected Behavior
Make should run normally and produce .elf file

### Actual Behavior
$ make
Toolchain path: /opt/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc
WARNING: Toolchain version is not supported: crosstool-ng-1.22.0-80-g6c4433a5
Expected to see version: crosstool-ng-1.22.0-80-g6c4433a
Please check ESP-IDF setup instructions and update the toolchain, or proceed at your own risk.
Compiler version: 5.2.0
WARNING: Toolchain version is not supported: crosstool-ng-1.22.0-80-g6c4433a5
Expected to see version: crosstool-ng-1.22.0-80-g6c4433a
Please check ESP-IDF setup instructions and update the toolchain, or proceed at your own risk.
The following Python requirements are not satisfied:
future>=0.16.0
cryptography
Please run "C:/ECO_V630_IDF3.2_Test/msys32/mingw32/bin/python.exe -m pip install --user -r C:/ECO_V630_IDF3.2_Test/esp-idf-latest/requirements.txt" for resolving the issue.
make: *** [C:/ECO_V630_IDF3.2_Test/esp-idf-latest/make/project.mk:454: check_python_dependencies] Error 1

### Steps to repropduce

1.	git clone https://github.com/espressif/esp-idf.git esp-idf-latest
2.	cd esp-idf-latest/
3.	git submodule update --init --recursive

// It helps if you attach a picture of your setup/wiring here.

### Code to reproduce this issue

```cpp
// the code should be wrapped in the ```cpp tag so that it will be displayed better.
#include "esp_log.h"

void app_main()
{
    
}

```
// If your code is longer than 30 lines, [GIST](https://gist.github.com) is preferred.

## Debug Logs

```
Debug log goes here, should contain the backtrace, as well as the reset source if it is a crash.
Please copy the plain text here for us to search the error log. Or attach the complete logs but leave the main part here if the log is *too* long.
```

## Other items if possible

- [ ] sdkconfig file (attach the sdkconfig file from your project folder)
- [ ] elf file in the ``build`` folder (**note this may contain all the code details and symbols of your project.**)
- [ ] coredump (This provides stacks of tasks.)

**Comment by dobairoland** [comment]
Have you tried, as the error message says, `run "C:/ECO_V630_IDF3.2_Test/msys32/mingw32/bin/python.exe -m pip install --user -r C:/ECO_V630_IDF3.2_Test/esp-idf-latest/requirements.txt" for resolving the issue.`?

You will have to probably install the `cryptography` package by running
`pacman -S mingw-w64-i686-python2-cryptography`.

**Comment by Milan991** [comment]
I have the same issue like @sjoteppagol. 

I've run following commands:
`python -m pip install --upgrade setuptools
pacman -S mingw-w64-i686-python2-cryptography
python -m pip install --user -r D:/esp-idf/requirements.txt`

After this command I got following error:

> Command "python setup.py egg_info" failed with error code 1 in c:\users\011lab\appdata\local\temp\pip-install-fxrkmd\future\

I can see that some other guys also having this kind of issue.

**Comment by Si03** [comment]
#2474

**Comment by projectgus** [comment]
Turns out `pip --upgrade setuptools` breaks the MSYS2 environment. To fix this, run the commands here:
https://github.com/espressif/esp-idf/issues/2480#issuecomment-425790054

After this and `pacman -S mingw-w64-i686-python2-cryptography`, running any additional steps prompted by the build system should work.

A new version of the MSYS2 environment will be available ASAP.

**Comment by sjoteppagol** [comment]
Thank you all for your quick response. The issue is resolved after running **pacman -S mingw-w64-i686-python2-cryptography** followed by **C:/ECO_V630_IDF3.2_Test/msys32/mingw32/bin/python.exe -m pip install --user -r C:/ECO_V630_IDF3.2_Test/esp-idf-latest/requirements.txt**.

**Comment by squonk11** [comment]
For me the commands needed to be:

- pacman -S mingw-w64-i686-python2-cryptography
- python -m pip install --user -r requirements.txt
