### ISSUE TITLE
[TW#26603] I2C master reset routine doesn't work

### ISSUE THREAD

**Issue by jeremyherbert** [espressif/esp-idf#2494]
Hi,

I have an I2C device which was causing a bus lockup (it contained some undocumented behaviour). However, this caused me to discover that the I2C master reset routine is incorrect. Please see https://github.com/espressif/esp-idf/pull/2493 for an explanation and details of the problem.

**Comment by jeremyherbert** [comment]
related to https://github.com/espressif/esp-idf/issues/680

**Comment by negativekelvin** [comment]
https://github.com/espressif/esp-idf/issues/1503#issuecomment-369445999
https://esp32.com/viewtopic.php?f=13&t=6203
