### ISSUE TITLE
The following Python requirements are not satisfied

### ISSUE THREAD

**Issue by James-sjec** [espressif/esp-idf#2500]
![apc - 2018 10 01 11 19 - 001 3d](https://user-images.githubusercontent.com/32930819/46307473-df1a1080-c56b-11e8-8ee8-37ab7b322aa9.jpg)

**Comment by James-sjec** [comment]
Hai all,
I was able to run esp-idf programs earlier , but after updating the esp-idf , I was getting the above error
I tried reinstalling from first , by installing the toolchains (https://dl.espressif.com/dl/esp32_win32_msys2_environment_and_toolchain-20170918.zip) and esp-idf , but I am getting the same error.

**Comment by chegewara** [comment]
https://github.com/espressif/esp-idf/issues/2480#issuecomment-424931850

**Comment by projectgus** [comment]
In addition to comment linked above, you may also have to remove a pip-installed setuptools. Try these commands: 
https://github.com/espressif/esp-idf/issues/2480#issuecomment-425790054

Updated MSYS2 environment will be available ASAP.

**Comment by James-sjec** [comment]
Thanks to all , for helping me to solve the issue
