### ISSUE TITLE
[question] esp_deep_sleep accuracy

### ISSUE THREAD

**Issue by chegewara** [espressif/esp-idf#2502]
How accurate is `esp_deep_sleep` wake up time? Im doing some other ble tests and in one example i have `esp_deep_sleep(1000000LL * 10);` (arduino project). Occasionally it takes less than set time(is it normal?), usually about 30-40ms longer (im assuming its normal):
**03:12:56.402** <--- before enter deep sleep
**03:13:06.392** <--- after wake up (less than 10s)

```
03:12:56.402 -> [D][BLEAdvertising.cpp:247] stop(): << stop
03:12:56.402 -> enter deep sleep
03:12:56.402 -> [D][BLEUtils.cpp:1091] dumpGapEvent(): Received a GAP event: ESP_GAP_BLE_ADV_STOP_COMPLETE_EVT
03:12:56.402 -> [D][BLEUtils.cpp:1135] dumpGapEvent(): [status: 0]
ets Jun  8 2016 00:22:57
03:13:06.392 -> 
03:13:06.392 -> rst:0x5 (DEEPSLEEP_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
03:13:06.392 -> configsip: 0, SPIWP:0xee
03:13:06.392 -> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
03:13:06.392 -> mode:DIO, clock div:1
03:13:06.392 -> load:0x3fff0018,len:4
03:13:06.392 -> load:0x3fff001c,len:952
03:13:06.392 -> load:0x40078000,len:6084
03:13:06.392 -> load:0x40080000,len:7936
03:13:06.392 -> entry 0x40080310
```

**Comment by igrr** [comment]
Deep sleep time accuracy depends on the RTC clock source. Default option, internal 150kHz crystal, has high temperature drift. If you can use an external 32 kHz crystal, accuracy will be better.
See https://docs.espressif.com/projects/esp-idf/en/latest/api-reference/kconfig.html#config-esp32-rtc-clock-source for details.
