### ISSUE TITLE
[TW#26654] conn_id mismatch in esp_ble_gatts_cb_param_t

### ISSUE THREAD

**Issue by chegewara** [espressif/esp-idf#2514]
Hi @Weijian-Espressif 
I think there is conn_id mismatch in `esp_ble_gatts_cb_param_t` when we get events. As you can see BT_GATT is logging `conn_id=3` and app callback is reporting `conn_id=0`. Test performed with esp-idf gatt_secure example.
```
I (12517) BT_GATT: GATT_GetConnectionInfor conn_id=3
I (12517) BT_L2CAP: L2CA_SendFixedChnlData()  CID: 0x0004  BDA: 5000f4ca1265
I (12520) SEC_GATTS_DEMO: [conn_id: 0, trans_id: 1]
```

**Comment by Weijian-Espressif** [comment]
@chegewara ,
` #define GATT_GET_TCB_IDX(conn_id)  ((UINT8) (((UINT16) (conn_id)) >> 8))
#define GATT_GET_GATT_IF(conn_id)  ((tGATT_IF)((UINT8) (conn_id)))`

in application layer , we will translate `conn_id` to gatt_if.

**Comment by chegewara** [comment]
Ok, so its only debug problem.
