### ISSUE TITLE
[TW#26641] mistaken uart speed at boot when using 26MHz quartz

### ISSUE THREAD

**Issue by neta79** [espressif/esp-idf#2518]
My ESP32 runs on a 26MHz crystal.

My sdkconfig has this:

    CONFIG_CONSOLE_UART_BAUDRATE=115200
    CONFIG_ESP32_XTAL_FREQ_26=y
    CONFIG_ESP32_XTAL_FREQ=26
    CONFIG_PM_ENABLE=

Loaded firmware: examples/get-started/hello_world

What was expected: UART0 running at 115200bps

What happens instead: UART0 actually runs at 74880bps

Notes:
In components/esp32/cpu_start.c, at start_cpu0_default() esp-idf does this:

    const int uart_clk_freq = APB_CLK_FREQ;
    ...
    uart_div_modify(CONFIG_CONSOLE_UART_NUM, (uart_clk_freq << 4) / CONFIG_CONSOLE_UART_BAUDRATE);

I think the problem with this is that APB_CLK_FREQ is a constant, while the frequency of APB_CLK appears to be determined by XTAL_CLK (according to TRM section 3.2.4.1, that seems to be the case).

**Comment by xiongyumail** [comment]
Please set Main XTAL frequency to Autodetect in menuconfig.
`Component config > ESP32-specific > Main XTAL frequency`

**Comment by neta79** [comment]
Followup test. My sdkconfig now contains:

    CONFIG_ESP32_XTAL_FREQ_40=
    CONFIG_ESP32_XTAL_FREQ_26=
    CONFIG_ESP32_XTAL_FREQ_AUTO=y
    CONFIG_ESP32_XTAL_FREQ=0
    CONFIG_CONSOLE_UART_NUM=0
    CONFIG_CONSOLE_UART_BAUDRATE=115200
    CONFIG_PM_ENABLE=

UART0 still working at 74880bps.

**Comment by negativekelvin** [comment]
>I think the problem with this is that APB_CLK_FREQ is a constant, while the frequency of APB_CLK appears to be determined by XTAL_CLK (according to TRM section 3.2.4.1, that seems to be the case).

Apb clk is only xtal clk if cpu clk is xtal clk and by that point cpu clk should be pll clk so apb clk should be a fixed value.

Post your idf version and boot log

**Comment by xiongyumail** [comment]
@neta79 
Have you solved this problem?

**Comment by igrr** [comment]
I can confirm that there is a small amount of ROM bootloader log being printed at incorrect baud rate when 26 MHz XTAL is used. See a bit of garbage after the final line with "load:" and before the welcome message of 2nd stage bootloader.

```
rst:0x1 (POWERON_RESET),boot:0x17 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:6204
load:0x40078000,len:10084
load:0x40080400,len:6536
?A???I (29) boot: ESP-IDF v3.2-dev-1296-g88625a250 2nd stage bootloader
I (29) boot: compile time 16:57:07
I (38) boot: Enabling RNG early entropy source...
I (38) boot: SPI Speed      : 40MHz
I (40) boot: SPI Mode       : DIO
I (44) boot: SPI Flash Size : 4MB
(rest of the log is fine)
```
Is this the issue that you have observed @neta79? If not, please attach the observed boot log and mention the IDF commit ID.

**Comment by neta79** [comment]
Sorry for the late response. This problem used to be steadily reproducible but now I can hardly observe it.

What changed: I obtained a second system (ESP32-GATEWAY, 40MHz XTAL), to cross-check against my initial ESP32 Thing (26MHz) board. I also ditched power via USB and introduced a stabilized power supply.

UART speed at boot seems correct for both board, regardless of CONFIG_ESP32_XTAL_*.

The ESP32 Thing (26MHz) shows sporadic hiccups where the UART outputs at 74880bps instead of 115200 immediately after powerup. The problem however seems to disappear completely by setting the UART speed again from app_main():

    uart_set_baudrate(0, 115200);

I don't think there is ground to treat this problem as an esp-idf bug. Given its erratic nature I bet it's hardware induced.

Thank you.
IMO we can close this. 

@iggr I am unable to reproduce. My boot log seems ok:

    load:0x40078000,len:10996                                                       
    load:0x40080400,len:6852                                                        
    entry 0x400807a0                                                                
    D (67) bootloader_flash: mmu set block paddr=0x00000000 (was 0xffffffff)        
    I (37) boot: ESP-IDF v3.2-dev-1252-g356d6cbf9 2nd stage bootloader              
    I (37) boot: compile time 18:08:09                                              
    D (37) boot: Enabling RTCWDT(9000 ms)
