### ISSUE TITLE
ESP32 version=3.1 last stable release can driver

### ISSUE THREAD

**Issue by snahmad** [espressif/esp-idf#2520]
Hi,

I manage to compile can driver on esp32 version =3.1 by coping can.h and can.c files and can_struct.h. can start ok, but can receive and can transmit not working.

It works with version 3.2. I want to use version=3.1 which last stable release. with latest code. I got some other issues such as SD card mkdir not working on version 3.2

esp-idf/components/driver/can.c

**Comment by Alvin1Zhang** [comment]
Hi, @snahmad Thanks for taking time to report this issue, would you please help provide more details regarding "bu can receive and can transmit not working.", based on the template https://github.com/espressif/esp-idf/blob/master/docs/issue_template.md ? Thanks.

**Comment by snahmad** [comment]
> Hi, @snahmad Thanks for taking time to report this issue, would you please help provide more details regarding "bu can receive and can transmit not working.", based on the template https://github.com/espressif/esp-idf/blob/master/docs/issue_template.md ? Thanks.

sorry miss-spelled.
but can receive and can transmit not working

**Comment by projectgus** [comment]
Hi @snahmad ,

I'm sorry but we don't support individually modified versions of ESP-IDF. To use the CAN driver you'll need to move to the master branch (v3.2-dev) where it is supported. If you're still experiencing issues with an unmodified ESP-IDF, please open a new issue with complete details about the problem.
