### ISSUE TITLE
[TW#26639] [request] esp_ble_gattc_get_service result incompatible with esp_ble_gattc_search_service event result

### ISSUE THREAD

**Issue by chegewara** [espressif/esp-idf#2521]
In most usage cases its not a problem, but when we have peripheral/server with multiple services with the same UUID then get services from cache will return inaccurate data because of lack inst_id.
Could we add inst_id to `esp_gattc_service_elem_t` or make `esp_ble_gattc_get_service` result type of `gattc_search_res_evt_param`?

Unless `inst_id` i local value, in that case i can set inst_id on my own.

**Comment by Weijian-Espressif** [comment]
@chegewara  Sorry, I didn't understand what you mean. What is the error?

**Comment by chegewara** [comment]
@Weijian-Espressif Theoretically when we have multiple services with the same uuid, we can distinguish which is which by `inst_id`. If we have data in cache we can get it with `esp_ble_gattc_get_service` but result returned is without `inst_id`. Now i see it is most likely not required since we can access services by stored handle. It would be useful to have it if for instance application logic require to find service by inst_id, but i missed that we still get `ESP_GATTC_SEARCH_RES_EVT` event even if we have result returned from `esp_ble_gattc_get_service`. I dont know if i explained clear enough what i meant. I will close this issue since its just optional parameter, but not required. You just explained me some information in the other issue about ble data stored in cache.

This is structure from `esp_ble_gattc_get_service` result:
https://docs.espressif.com/projects/esp-idf/en/latest/api-reference/bluetooth/esp_gatt_defs.html#_CPPv224esp_gattc_service_elem_t
and this is from `ESP_GATTC_SEARCH_RES_EVT` event:
https://docs.espressif.com/projects/esp-idf/en/latest/api-reference/bluetooth/esp_gattc.html#_CPPv2N24esp_ble_gattc_cb_param_t26gattc_search_res_evt_paramE

This is what i would like to see in first structure, or at least `inst_id`:
https://docs.espressif.com/projects/esp-idf/en/latest/api-reference/bluetooth/esp_gattc.html#_CPPv2N24esp_ble_gattc_cb_param_t26gattc_search_res_evt_param7srvc_idE
