### ISSUE TITLE
ble connecting more than 3 clients issue

### ISSUE THREAD

**Issue by chegewara** [espressif/esp-idf#2524]
Hi @Weijian-Espressif  @Yulong-espressif 
When i am trying to connect multiple clients i am getting error code 133 (0x85) GATT ERROR in nRF connect when i am trying to connect 4th client (3 clients work). At the same time i dont get even single line in esp32 server device logs that any device is trying to connect.
Server app is flashed onto wrover with 4MB ram, all options to use heap from PSRAM are turned on in menuconfig, few ble log levels are EVENT (HCI, GATT, GAP, SM, L2CAP). Max allowed connected devices in menuconfig set to 7, increased ble stack to 18kB.

https://github.com/NordicSemiconductor/Android-nRF-Toolbox/issues/9#issuecomment-132191406

EDIT from esp32 client `W (11449) BT_APPL: bta_gattc_conn_cback() - cif=3 connected=0 conn_id=3 reason=0x003e`

**Comment by chegewara** [comment]
@Weijian-Espressif I missed this one
`(1) Bluetooth ->Bluetooth controller -> BLE Max Connections`

Thanks

**Comment by chegewara** [comment]
@Weijian-Espressif Even esp-idf multi connection example does not mention about second option:
https://github.com/espressif/esp-idf/blob/master/examples/bluetooth/gattc_multi_connect/README.md

**Comment by dizcza** [comment]
> @chegewara There are two configuration items in menuconfig. please config the max connection at
> (1) Bluetooth ->Bluetooth controller -> BLE Max Connections
> (2) Bluetooth ->Bluedroid enable -> BT/BLE MAX ACL CONNECTIONS

Shouldn't be there only one option for the user to specify? What's the purpose of having two identical (from the user perspective) constants? If one is 2, and the other is 4, what's the max num of Bluetooth clients an ESP board can handle? Same hell for BT classic:
* `Bluetooth ->Bluetooth controller -> BR/EDR ACL Max Connections` (default 2)
* `Bluetooth ->Bluedroid enable -> BT/BLE MAX ACL CONNECTIONS` (default 4)

**Comment by chegewara** [comment]
> > @chegewara There are two configuration items in menuconfig. please config the max connection at
> > (1) Bluetooth ->Bluetooth controller -> BLE Max Connections
> > (2) Bluetooth ->Bluedroid enable -> BT/BLE MAX ACL CONNECTIONS
> 
> Shouldn't be there only one option for the user to specify? What's the purpose of having two identical (from the user perspective) constants? If one is 2, and the other is 4, what's the max num of Bluetooth clients an ESP board can handle? Same hell for BT classic:
> 
> * `Bluetooth ->Bluetooth controller -> BR/EDR ACL Max Connections` (default 2)
> * `Bluetooth ->Bluedroid enable -> BT/BLE MAX ACL CONNECTIONS` (default 4)

Actually those are 2 different settings. When you look closer you can see that one is `BR/EDR` and other is `BT/BLE` (classit BT and BLE). Easy to miss that fact.

**Comment by dizcza** [comment]
> Actually those are 2 different settings. When you look closer you can see that one is `BR/EDR` and other is `BT/BLE` (classit BT and BLE). Easy to miss that fact.

I still don't capture the difference. Let me clarify a bit.

I've set up the Bluetooth in the classic regime. And according to [wiki](https://en.wikipedia.org/wiki/Bluetooth_Low_Energy#Compatibility), which calls Bluetooth Basic Rate/Enhanced Data Rate (BR/EDR) protocol as "classic", I conclude that these constants should be the same. What's the difference? `BT/BLE MAX ACL CONNECTIONS` I treat as the max. no. of connections independently of the protocol - BLE or BT classic.

In my example above, if I want to support 5 clients (BT classic, SPP), how should I set those constants?

Thank you.

**Comment by xiaolongba** [comment]
sorry to jump into this discussion, one similar issue about the max ble connection, **is it possible to connect more than 8 devices at the same time?** I tried to figure out the answer online, it showed me that the max connections esp32 support is only 8.

**Comment by chegewara** [comment]
> sorry to jump into this discussion, one similar issue about the max ble connection, **is it possible to connect more than 8 devices at the same time?** I tried to figure out the answer online, it showed me that the max connections esp32 support is only 8.

not with ble v4.2, this is bluetooth specs. BLE5 says about 20 connections, but i dont know if its implemented or planed in esp-idf.

**Comment by xiaolongba** [comment]
> not with ble v4.2, this is bluetooth specs. BLE5 says about 20 connections, but i dont know if its implemented or planed in esp-idf.


Could you share with me which pages for this description of ble spec? In my understanding, the max connection is out of spec, it depends on the stack or hardware.

**Comment by chegewara** [comment]
sorry, i cant find this now. It was some ble 5 features info and you may be right, it may be minimum number specified by SIG.
In meantime i found few similar questions/answers regarding connections limit in android and even windows, and most of them were around 7 connections and on windows 5.
https://docs.microsoft.com/en-us/answers/questions/452987/how-many-ble-bondingconnection-are-supported-by-wi.html

Sorry for confusion and not giving correct answer.

**Comment by xiaolongba** [comment]
> sorry, i cant find this now. It was some ble 5 features info and you may be right, it may be minimum number specified by SIG.
> In the meantime i found a few similar questions/answers regarding connections limit in android and even windows, and most of them were around 7 connections and on windows 5.
> https://docs.microsoft.com/en-us/answers/questions/452987/how-many-ble-bondingconnection-are-supported-by-wi.html
> 
> Sorry for the confusion and for not giving the correct answer.

Okay, the Nordic &ST platform can support up to more than 20 connections, but it is not the ble 5.0 feature, it depends on their high-performance BLE stack, but I am not sure the esp32 if it can support more than 8 connections? Can espressif guys help us confirm?
