### ISSUE TITLE
Bluetooth Mesh Status

### ISSUE THREAD

**Issue by lucascoxBAF** [espressif/esp-idf#2526]
Hello, esp developers,

I was curious if there is an update on the status of Bluetooth Mesh support. I know Espressif was working on an implementation back in April, but there hasn't been any update in a very long time. Are there still plans to release Bluetooth mesh?

**Comment by chegewara** [comment]
And what is the reason to open new issue?
https://github.com/espressif/esp-idf/issues/819

**Comment by lucascoxBAF** [comment]
@chegewara, I was hoping pushing it to the top of the "issue" list might finally prompt a response from developers. Not sure if I was successful at all or if it was just coincidence.
