### ISSUE TITLE
How to use ethernet interface make static ip

### ISSUE THREAD

**Issue by TobeChan** [espressif/esp-idf#2533]
i did it this way
https://github.com/espressif/esp-idf/pull/657

but still return 

ESP_ERROR_CHECK failed: esp_err_t 0x5007 (ESP_ERR_TCPIP_ADAPTER_DHCP_NOT_STOPPED
) at 0x400ee077

on ESP_ERROR_CHECK(tcpip_adapter_set_ip_info(TCPIP_ADAPTER_IF_ETH, &eth_ip));

and it is my partial code,i'm building on  system_event_eth_start_handle_default

esp_err_t system_event_eth_start_handle_default(system_event_t *event)
{
    tcpip_adapter_ip_info_t eth_ip;
    uint8_t eth_mac[6];

	printf("ethe_start\r\n");
    esp_eth_get_mac(eth_mac);

	ESP_ERROR_CHECK(tcpip_adapter_dhcps_stop(TCPIP_ADAPTER_IF_ETH));
	memset(&eth_ip, 0, sizeof(eth_ip));
	IP4_ADDR(&eth_ip.ip, 192, 168, 18, 1);
	IP4_ADDR(&eth_ip.gw, 192, 168, 254, 1);
	IP4_ADDR(&eth_ip.netmask, 255, 255, 255, 0);
	
	ESP_ERROR_CHECK(tcpip_adapter_set_ip_info(TCPIP_ADAPTER_IF_ETH, &eth_ip));
	
	ESP_ERROR_CHECK(tcpip_adapter_dhcps_start(TCPIP_ADAPTER_IF_ETH));
	
    //tcpip_adapter_get_ip_info(TCPIP_ADAPTER_IF_ETH, &eth_ip);
    tcpip_adapter_eth_start(eth_mac, &eth_ip);

    return ESP_OK;
}

Thanks!!

**Comment by JeanCarloEM** [comment]
This fix, for some reason is not listed as applied to the dhcp server (dhcpS), just for dhcp client (dhcpC), so I applied it manually for the same functions as the DHCP server, and it worked.

It is suggested that such a correction be applied only to dhcpS.
