### ISSUE TITLE
[TW#26679] Incorrect instructions in CMake getting started docs (IDFGH-1193)

### ISSUE THREAD

**Issue by embeddedjim** [espressif/esp-idf#2538]
Hello I am trying to use the CMake tools being tested by espressif but when I follow the clone instructions "git clone --branch feature/cmake --recursive https://github.com/espressif/esp-idf.git" I get the following messages "Cloning into 'esp-idf'..." and then "fatal: Remote branch feature/cmake not found in upstream origin" Can anyone help please

**Comment by mahavirj** [comment]
@embeddedjim `feature/cmake` is already merged in `master` branch, please follow instructions at https://docs.espressif.com/projects/esp-idf/en/latest/get-started-cmake/index.html

**Comment by mahavirj** [comment]
@negativekelvin Thanks for notifying, will fix them.

**Comment by jcabad100** [comment]
Hello everyone, i still have the same problem and the documention https://docs.espressif.com/projects/esp-idf/en/v3.1/get-started-cmake/index.html#get-started-get-esp-idf-cmake still contains the very same instructions "git clone --recursive https://github.com/espressif/esp-idf.git" and i get the very same error as @embeddedjim i.e. "$ git clone --branch feature/cmake --recursive https://github.com/espressif/esp-idf.git
Cloning into 'esp-idf'... 
fatal: Remote branch feature/cmake not found in upstream origin" ...can someone  please tell me how to solve this issue? @mahavirj i don't know what to do with the information you provided "feature/cmake is already merged in master branch" ...can you be more explicit on how to clone the repository? ...thank you!

**Comment by jcabad100** [comment]
@Alvin1Zhang can you please update the documentation on  https://docs.espressif.com/projects/esp-idf/en/v3.1/get-started-cmake/index.html#get-started-get-esp-idf-cmake  indicating how to clone the repository (i am working on Windows 10) and i am deadlocked with "fatal: Remote branch feature/cmake not found in upstream origin" ..thank you.

**Comment by Alvin1Zhang** [comment]
@jcabad100 Thanks for the feedback. We will look into this. Thanks.

**Comment by mahavirj** [comment]
@jcabad100 If you do not have any dependency on IDF v3.1 release then you can refer to latest release (v3.2) documentation at https://docs.espressif.com/projects/esp-idf/en/v3.2/get-started-cmake/index.html#step-2-get-esp-idf. For IDF v3.1, it seems like fix is not yet backported, will ensure that it will get addressed soon.

**Comment by jcabad100** [comment]
@Alvin1Zhang ..i justi solved (on Windows) ,instead of "git clone --recursive https://github.com/espressif/esp-idf.git" i used "git clone --recursive https://github.com/espressif/esp-idf.git " ...and it started/finished cloning...

**Comment by catherinedodge** [comment]
This bug still exists in the docs here: https://docs.espressif.com/projects/esp-idf/en/v3.1.3/get-started-cmake/index.html#get-started-get-esp-idf-cmake which are linked to from the Amazon FreeRTOS page. If someone knows where those docs are generated from, happy to submit a pull request to remove the remote branch argument.

**Comment by krzychb** [comment]
Hi @catherinedodge thank you for pointing it out. I will get it resolved.

**Comment by mahavirj** [comment]
Fixed with https://github.com/espressif/esp-idf/commit/4e25f20c829b32d4cff022fe8c76fc4073672380 (Reflected at https://docs.espressif.com/projects/esp-idf/en/release-v3.1/get-started-cmake/index.html, will also be part of `v3.1.5` documentation with next release)
