### ISSUE TITLE
[TW#26692] lwip_recvfrom return immediately the lenght 0 with errno set to 128

### ISSUE THREAD

**Issue by karawin** [espressif/esp-idf#2540]
## Environment

- Development Kit:      [ESP32]
- Core (if using chip or module): [ESP32-Wrover]
- IDF version (``git rev-parse --short HEAD`` to get the commit id.): 
    54456b1a
- Development Env:		[other]
- Operating System:		[Windows]
- Power Supply:         [USB]

## Problem Description
In a do while loop receiving a stream, sometime recvfrom return -1 with errno 11 due to the SO_RCVTIMEO timeout. Normal
But after a while, recvfrom  return immediately 0 with errno 128. Abnormal, must return -1
Traces:
##CLI.META#: Debbie Gibson - Only In My Dreams
E (4188132) webclient: Client socket: 59  read: -1  errno:11 
W (4188132) webclient: No data in recv. Errno = 11
E (4193142) webclient: Client socket: 59  read: -1  errno:11 
W (4193142) webclient: No data in recv. Errno = 11
W (4199422) webclient: No data in recv. Errno = 128
W (4200432) webclient: No data in recv. Errno = 128
W (4201442) webclient: No data in recv. Errno = 128
W (4202452) webclient: No data in recv. Errno = 128
W (4203462) webclient: No data in recv. Errno = 128
W (4204472) webclient: No data in recv. Errno = 128

and with a return -1
##CLI.META#: Police - Every Little Thing She Does Is Magic
E (12047762) webclient: Client socket: 62  read: -1  errno:113 
W (12047762) webclient: No data in recv. Errno = 113
##CLI.STOPPED# from try restart

Sample of the code;
				do
				{
					bytes_read = recvfrom(sockfd, bufrec,RECEIVE, 0, NULL, NULL);	
					if ( bytes_read < 0 )
					{
						ESP_LOGE(TAG,"Client socket: %d  read: %d  errno:%d ",sockfd, bytes_read,errno);
						if (errno == 11) bytes_read = 0;
					}		
					if ( bytes_read > 0 )
					{
					   // compute the received data
                                            clientReceiveCallback(sockfd,(char*)bufrec, bytes_read);
					}	
					else 
					{
						ESP_LOGW(TAG,"No data in recv. Errno = %d",errno);
						vTaskDelay(100);
					}
					vTaskDelay(1);
				}
				while (( bytes_read > 0 )||(playing && (bytes_read == 0)));

### Expected Behavior
  When errno is set, recvfrom must return -1
### Actual Behavior
 Errno is set to 128 but recvfrom returns immediately 0.
### Steps to repropduce
Hard

## Debug Logs

```
Debug log goes here, should contain the backtrace, as well as the reset source if it is a crash.
Please copy the plain text here for us to search the error log. Or attach the complete logs but leave the main part here if the log is *too* long.
```

## Other items if possible

- [ ] sdkconfig file (attach the sdkconfig file from your project folder)
- [ ] elf file in the ``build`` folder (**note this may contain all the code details and symbols of your project.**)
- [ ] coredump (This provides stacks of tasks.)

**Comment by stickbreaker** [comment]
@karawin looks like it might be a type conversion problem.  What is your declared data type of
`bytes_read`?

If `bytes_read` is defined as `uint8_t bytes_read;` or `byte bytes_read;` the value 128 is accurate. 

You might try changing your definition to:
```c++
int8_t bytes_read; //-128 to 127
//or
int16_t bytes_read; // -32768 to 32767
// or
short bytes_read; // -32768 to 32767
```

Chuck.

**Comment by karawin** [comment]
byte_read is int obviously.
Notice that the if ( bytes_read < 0 ) is ok.

**Comment by negativekelvin** [comment]
```
W (4193142) webclient: No data in recv. Errno = 11
W (4199422) webclient: No data in recv. Errno = 128
```

What happened in the 6 second delay

**Comment by karawin** [comment]
How knows. It is a mp3 stream from a webradio. On errno 11 the stream is discontinued. Sometime it appear again and sometime it end with errno 128 or 113.

**Comment by negativekelvin** [comment]
https://github.com/espressif/esp-lwip/blob/21a1fcb2aebaaae63d87dfeceaff03dc0bae6374/src/api/sockets.c#L1059-L1060

**Comment by karawin** [comment]
Right. But why?
It can be easily tested in app but setting errno without feedback is strange.
Thanks

**Comment by negativekelvin** [comment]
If the connection has been gracefully closed, the return value is zero.

**Comment by karawin** [comment]
But who closed the socket here?
Not the task in the loop and outside every close is logged with a reason.
If the socket is closed for external reason, it must return -1 and errno.

**Comment by negativekelvin** [comment]
If it is a tcp socket the peer can close it.

**Comment by karawin** [comment]
I know all that. I just say that if the socket is dead, an error must be returned when the errno is set and recvfrom or recv is called.
But when i read a linux https://linux.die.net/man/2/recvfrom I see 
"Return Value

These calls return the number of bytes received, or -1 if an error occurred. The return value will be 0 when the peer has performed an orderly shutdown. "

So may be a standard value.
If yes i close the issue.

**Comment by negativekelvin** [comment]
Orderly or graceful shutdown is when the peer will close his tx side first and you detect this by the 0 return value and then you close your tx side.

**Comment by karawin** [comment]
Closing. Can be tested in code
