### ISSUE TITLE
[TW#26698] wifi warning messages meaning?

### ISSUE THREAD

**Issue by negativekelvin** [espressif/esp-idf#2544]
Getting a lot of these warning messages.  What do they mean and what are possible effects/workarounds?

```
W (623478143) wifi: conn=0x3ffcc4cc failed to alloc rx ba index
W (623478143) wifi: rap no hw index, tid=3
```

v3.2-dev-1146-g4ff452326

Maybe related to https://github.com/espressif/esp32-wifi-lib/commit/9790499df4e75709f171cef5d63b5afa6663d058

**Comment by liuzfesp** [comment]
Hi @negativekelvin, this issue has been fixed in 660770ea97d82883700569a7f25f93513f8a436f
