### ISSUE TITLE
[TW#26743] menuconfig option CONFIG_DUPLICATE_SCAN_CACHE_SIZE

### ISSUE THREAD

**Issue by chegewara** [espressif/esp-idf#2556]
@Weijian-Espressif 
Is it possible that setting `CONFIG_DUPLICATE_SCAN_CACHE_SIZE` with minimal possible value (10) is taking almost 50kB from heap? 

I have very simple app for testing purpose (memory leak in ble scan) and without scan duplicates filter im having about 160kB free heap, with filter about 110kB.

**Comment by Weijian-Espressif** [comment]
CONFIG_DUPLICATE_SCAN_CACHE_SIZE only consume controller heap size. I print free heap size with 
scan duplicate enaable and diasble, the free heap size is same.

**Comment by chegewara** [comment]
@Weijian-Espressif I dont know, when i compile app with and without this option i see this difference and in ble library this is never used before. I will do more tests with esp-idf example to confirm. Thanks.

**Comment by Weijian-Espressif** [comment]
@chegewara What is the conmmit id ? It would be better if you could provide the test code.

**Comment by chegewara** [comment]
@Weijian-Espressif I will do all by the book this time. esp-idf example and report all. This is commit:
221eced06daff783afde6e378f6f84a82867f758

**Comment by Weijian-Espressif** [comment]
@chegewara thanks for your help.

**Comment by chegewara** [comment]
Looks like i had to change something else, my bad sorry.
