### ISSUE TITLE
[TW#26741] BLE generating and resolving random mac addresses does not work correctly

### ISSUE THREAD

**Issue by chegewara** [espressif/esp-idf#2559]
@Weijian-Espressif @Yulong-espressif 
I think that values for `esp_ble_addr_type_t` are not correctly enumerated. According to bluetooth specs:
> BLUETOOTH SPECIFICATION Version 5.0 | Vol 6, Part B page 2557
The random device address may be of either of the following two sub-types:
• Static address
• Private address.

>A static address is a 48-bit randomly generated address and shall meet the
following requirements:
• The two most significant bits of the address shall be equal to 1

But all 3 non public types are generating address of type `resolvable private address`. How do i know:
> BLUETOOTH SPECIFICATION Version 5.0 | Vol 6, Part B page 2558
> To generate a resolvable private address, the device must have either the
Local Identity Resolving Key (IRK) or the Peer Identity Resolving Key (IRK).
The resolvable private address shall be generated with the IRK and a randomly
generated 24-bit number. The random number is known as prand and shall
meet the following requirements:
• The two most significant bits of prand shall be equal to 0 and 1 as shown in
Figure 1.4

```
I (739) SampleClient: Advertised Device: Name: ESP32, Address: 48:ed:1c:cf:37:0f, serviceUUID: 00001234-0000-1000-8000-00805f9b34fb, txPower: 3
```
As we can see most significant value is 0x48 which is `0100 1000`. 

Also resolvable private address is recognized as `BLE_ADDR_TYPE_RANDOM`.

**Comment by Weijian-Espressif** [comment]
@chegewara ,  
static device address , The two most significant bits of the address shall be equal to 1 , `11`
Non-resolvable private address, The two most significant bits of the address shall be equal to 0, `00`
resolvable private address, The two most significant bits of prand shall be equal to 0 and 1, `10`
0x48 is `0100 1000`,  `10`  is a resolvable private address.

**Comment by chegewara** [comment]
@Weijian-Espressif I know, thats why i am reporting this issue.
1. no matter what argument i pass `BLE_ADDR_TYPE_RANDOM`, `BLE_ADDR_TYPE_RPA_PUBLIC` or `BLE_ADDR_TYPE_RPA_RANDOM` esp32 with set privacy is always generating address type `BLE_ADDR_TYPE_RPA_RANDOM`
2. esp32 is recognizing address with type resolvable private address (ie 0x48) as `BLE_ADDR_TYPE_RANDOM`

**Comment by Weijian-Espressif** [comment]
@chegewara,  Our controller only receive public and random address type, so we set resolvable private address BLE_ADDR_TYPE_RANDOM. IRK is saved on the host, host will resolve address instead of controller.

**Comment by Weijian-Espressif** [comment]
@chegewara `esp_ble_gap_set_rand_addr` can set random address. 
1. `BLE_ADDR_TYPE_PUBLIC`
  use public address
2. `BLE_ADDR_TYPE_RANDOM`
 use static random address, if not exist, use resolvable address, Otherwise report error
3. `BLE_ADDR_TYPE_RPA_RANDOM` 
use resolvable address, if not exist, use random  address,  Otherwise report error
4. `BLE_ADDR_TYPE_RPA_PUBLIC`
use resolvable address, if not exist, use public  address

you can set adv param or scan param to switch address.

**Comment by chegewara** [comment]
@Weijian-Espressif I might have missing something or maybe i am just dumb. I am using this exact parameter to chose what type of own address i want:
https://github.com/espressif/esp-idf/blob/master/examples/bluetooth/gatt_security_server/main/example_ble_sec_gatts_demo.c#L84

Always when i set different than `BLE_ADDR_TYPE_PUBLIC` i get resolvable random address.

**Comment by Weijian-Espressif** [comment]
@chegewara please get current address after start adv or start scan

**Comment by chegewara** [comment]
@Weijian-Espressif 
I am reading address from nRF connect scan procedure. When do i have to get it if not after start advertising?

**Comment by Weijian-Espressif** [comment]
@chegewara do you set static random address? or your IDF is older?

**Comment by Weijian-Espressif** [comment]
@chegewara 
1. update to the latest IDF
2. set static random address by `esp_ble_gap_set_rand_addr`
3.  set adv address type by `esp_ble_gap_start_advertising`

**Comment by chegewara** [comment]
@Weijian-Espressif i am working always on master branch, i did pull 3-5 days ago, so no ble related commits since then. This is my procedure to change own address type, and i am not setting static address with `esp_ble_gap_set_rand_addr`:
```
void BLEAdvertising::setPrivateAddress(esp_ble_addr_type_t type) {
	m_advParams.own_addr_type = type;  // <-- here i am changing random address type
	esp_ble_gap_config_local_privacy(true);
}
```
Some time after this i amd starting advertising with `esp_ble_gap_start_advertising`.

I am not using `esp_ble_gap_set_rand_addr` because i want to get address to be generated by esp-idf according to `own_addr_type `. It is how i understand this part of API. If i am getting it wrong then its just misunderstanding.

Just dont get me wrong, i dont complain or something, i just trying to help. If you dont want me to stop opening issues to stop wasting your time im fine with that.

**Comment by Weijian-Espressif** [comment]
@chegewara Sorry, `esp_ble_gap_config_local_privacy(true)' is called to generate a resolvable random address. if you want to set static random address, please use `esp_ble_gap_set_rand_addr ()`. 
'own_addr_type'  is to decide which address you use. The premise is that you must set this address, otherwise you will get an error.

**Comment by chegewara** [comment]
@Weijian-Espressif You dont have to feel sorry, like i said it is just a misunderstanding and not understanding API from my side. 

Thank you very much for explaining this to me and for patience.
Just last one question, can you advice me some simple way to generate random address that i could use in `esp_ble_gap_set_rand_addr`. Maybe esp_random() and then hash it?

**Comment by Weijian-Espressif** [comment]
@chegewara Sorry, there is no API to generate a static random address. it is easy to get a static random address.
`A static address is a 48-bit randomly generated address and shall meet the following requirements:
        • The two most significant bits of the address shall be equal to 1
        • All bits of the random part of the address shall not be equal to 1
        • All bits of the random part of the address shall not be equal to 0`

E.g 0xC0 0xx 0xx 0xx 0xx 0xx

**Comment by chegewara** [comment]
@Weijian-Espressif I know bluetooth specs about that. I will try with esp_random(), then hash that and at the and set MSB 2 bits to 1. Thanks for clarification. 
If i may say last one thing, its not complicated algorithm but would be nice to have API in bt stack:
`esp_ble_gap_set_rand_addr(void)`

**Comment by Weijian-Espressif** [comment]
@chegewara Some users prefer to set a custom address, so our API doesn't do auto-generated functionality.

**Comment by chegewara** [comment]
@Weijian-Espressif 
I know, what i mean is to have another API function.

**Comment by chegewara** [comment]
@Weijian-Espressif Most likely there is easier way to do it or more elegant, but this is my address generator. Maybe its not pretty but i think it works just like i expecting:

```
void BLEAdvertising::setPrivateAddress(esp_ble_addr_type_t type) {
	esp_bd_addr_t addr;
	m_advParams.own_addr_type = type;

	if(type == BLE_ADDR_TYPE_RPA_PUBLIC) {
		esp_ble_gap_config_local_privacy(true);
		return;
	}
	else{
		uint32_t _rand = esp_random();
		mbedtls_ctr_drbg_context ctr_drbg;
		mbedtls_entropy_context entropy;
		mbedtls_md_context_t ctx;

		char pers[] = "aes generate key";
		int ret;
		unsigned char key[BLOCK_SIZE] = {0};
		const char inp[] = "random static address";
		unsigned char outp[BLOCK_SIZE/2];

		mbedtls_entropy_init( &entropy );
		mbedtls_ctr_drbg_init( &ctr_drbg );

		if( ( ret = mbedtls_ctr_drbg_seed( &ctr_drbg, mbedtls_entropy_func, &entropy,
			(unsigned char *) pers, strlen( pers ) ) ) != 0 )
		{
			printf( " failed\n ! mbedtls_ctr_drbg_init returned -0x%04x\n", -ret );
			goto exit;
		}

		if( ( ret = mbedtls_ctr_drbg_random( &ctr_drbg, key, BLOCK_SIZE ) ) != 0 )
		{
			printf( " failed\n ! mbedtls_ctr_drbg_random returned -0x%04x\n", -ret );
			goto exit;
		}

		mbedtls_md_init(&ctx);
		mbedtls_md_setup(&ctx, mbedtls_md_info_from_type(HMAC), true);
		mbedtls_md_hmac_starts(&ctx, (const unsigned char *)key, BLOCK_SIZE);
		mbedtls_md_hmac_update(&ctx, (const unsigned char *)inp, strlen(inp));
		mbedtls_md_hmac_finish(&ctx, outp);
		mbedtls_md_free(&ctx);
		ESP_LOG_BUFFER_HEX("random key", key, BLOCK_SIZE);
		ESP_LOG_BUFFER_HEX("HASH step 2", outp, BLOCK_SIZE/2);

		memcpy(addr, outp, 6);
	}
	if(type == BLE_ADDR_TYPE_RANDOM) {
		addr[0] &= 0x3F;  // <--- Format of non-resolvable private address 00xx xxxx
	}
	else{
		addr[0] |= 0xC0;  // <--- Format of static address 11xx xxxx
	}

	esp_ble_gap_set_rand_addr(addr);
	ESP_LOG_BUFFER_HEX("random address", addr, 6);
	exit:
	return;
}
```

**Comment by chegewara** [comment]
btw your time is not wasted, now i ca help other users answering their questions:

https://www.esp32.com/viewtopic.php?f=13&t=7657
