### ISSUE TITLE
esp_timer short time is not triggered

### ISSUE THREAD

**Issue by vgonet** [espressif/esp-idf#2572]
Hello,
I've an issue with the esp_timer library.

## Environment

- Development Kit: NodeMCU-32S
- Core (if using chip or module): ESP-WROOM32|ESP32]
- IDF version: c2b39f4a5
- Development Env: Eclipse
- Operating System:	Windows

## Problem Description
I'm trying to use the esp_timer with a time of 10us to play a sine wave through the DAC but it doesn't work. The smallest time I can set is 50us.

### Expected Behavior
If I set a time of 10us, the callback function shall be called every 10us

### Actual Behavior
If I set a time of 10us, the callback function is called every 50us
If I set a time of 80us, the callback function is called every 80us

### Code to reproduce this issue

```cpp
const esp_timer_create_args_t periodic_timer_args = 
{
  .callback = &periodic_timer_callback,
  // name is optional, but may help identify the timer when debugging
  .name = "periodic"
};
  
ESP_ERROR_CHECK(esp_timer_create(&periodic_timer_args, &periodic_timer));
// The timer has been created but is not running yet

ESP_ERROR_CHECK(esp_timer_start_periodic(periodic_timer, 10));
```

Thank you and best regards

**Comment by igrr** [comment]
Setting a timer for shorter intervals would leave little to no CPU time for other tasks, therefore the minimal period of a periodic esp_timer is limited to 50us. Thanks for pointing this out, this will be documented along with https://github.com/espressif/esp-idf/issues/2350.

For you application, you may consider using DMA to feed data into the DAC. This will free up the CPU and not require a periodic timer. Please see https://github.com/espressif/esp-idf/tree/master/examples/peripherals/i2s_adc_dac example.

Also, ESP32 DAC has a dedicated feature to generate sine waveform, see https://github.com/espressif/esp-idf/blob/master/examples/system/app_trace_to_host/main/app_trace_to_host_test.c#L60-L76 for an example.
