### ISSUE TITLE
[TW#26808] Docs: Missing for esp_tls_conn_new_async

### ISSUE THREAD

**Issue by PerMalmberg** [espressif/esp-idf#2576]
The documentation for [esp_tls_conn_new_async](https://docs.espressif.com/projects/esp-idf/en/latest/api-reference/protocols/esp_tls.html#_CPPv222esp_tls_conn_new_asyncPKciiPK13esp_tls_cfg_tP9esp_tls_t) is missing.

**Comment by jitin17** [comment]
@PerMalmberg Thanks for bringing this to our notice. An internal MR to resolve this has been raised.
