### ISSUE TITLE
Documentation regarding system_event_t queue (IDFGH-413)

### ISSUE THREAD

**Issue by dereks** [espressif/esp-idf#2582]
--------------------------

## Environment

- Development Kit:      [none]
- Core (if using chip or module): [ESP-WROOM32]
- IDF version (``git rev-parse --short HEAD`` to get the commit id.): 11b444b

- Development Env:		[other]
- Operating System:		[|Ubuntu|]
- Power Supply:         [Battery]

## Problem Description

I got burned by a sneaky gotcha. I would like to save others from the debugging I just did. Hopefully there can be a quick mention added to the WiFi docs, or made more visible.

My goal was to block waiting for a successful WiFi connect event or disconnect (failure) event. So, as per the docs, I simply forwarded system events from the WiFi driver's event loop to my own FreeRTOS system_event_t queue, so I can block waiting for a result in my application thread.

```c
// Move system event processing to the calling thread 
// (instead of the WiFi driver's 'Event' thread).
//
// This is used when the caller wants to block, waiting for a response event.
esp_err_t system_event_relay_cb(void *ctx, system_event_t *event) {
    xQueueSend(system_event_queue, event, portMAX_DELAY);
    return ESP_OK;
}
// ...

// And on init, I registered this callback:
ESP_ERROR_CHECK( esp_event_loop_init(system_event_relay_cb, NULL) );
```

Everything seemed fine, until I tried to log the disconnect error reason. My WiFi error reason was always ESP_OK (Success), even on a disconnect event. Further digging showed that the ssid, ssid_len, and bssid fields were also all NULL/zero. The log looked like this:

```py
# The event thread saw the reason 201 just fine: 
D (3127) event: SYSTEM_EVENT_STA_DISCONNECTED, ssid:LinuxRules, ssid_len:10, bssid:00:00:00:00:00:00, reason:201

# But my own thread did not, although, it still got the event_id successfully:
D (3127) main: SYSTEM_EVENT_STA_DISCONNECTED, ssid: , ssid_len:0, bssid:00:00:00:00:00:00, reason:0
```
After debugging I found out why. I had foolishly declared my FreeRTOS queue to hold only a pointer to an event, not an entire copy of an event.  That is:

```c
// DO NOT DO THIS: The pointer will point to the Event queue's RAM, which quickly turns invalid.
system_event_queue = xQueueCreate(5, sizeof(system_event_t *));

// The correct way is to tell FreeRTOS to copy the entire event structure into the application's queue, 
// not just the pointer to the event. (Note the asterisk is now gone.)

// CORRECT
system_event_queue = xQueueCreate(5, sizeof(system_event_t));
```

Although this is just basic C memory management, I got bit by it because I'm used to using just a queue of pointers for my application state machines. That works just fine (because I don't share the events between threads). The line of code above the broken example line is literally
```c
event_queue = xQueueCreate(5, sizeof(app_event_t *));
```
...and this disguised the error from me. (That, and the fact that the event_id was still correctly shown as SYSTEM_EVENT_STA_DISCONNECTED.)

Thus, this is a request to add to the WiFi docs a note reminding users that **if you want to process network events in your own thread, your queue must hold entire copies of system_event_t**, not just a pointer.

(I'd be happy to submit a PR but it will be at least a couple of weeks, I am in crunch mode. Thanks!)

**Comment by liuzfesp** [comment]
HI @dereks , yes, you need to forward the copy of the event to user task because the event is allocated on the stack

```
static void esp_event_loop_task(void *pvParameters)
{
   while (1) {
        system_event_t evt;
        if (xQueueReceive(s_event_queue, &evt, portMAX_DELAY) == pdPASS) {
            esp_err_t ret = esp_event_process_default(&evt);
            if (ret != ESP_OK) {
                ESP_LOGE(TAG, "default event handler failed!");
            }
            ret = esp_event_post_to_user(&evt);
            if (ret != ESP_OK) {
                ESP_LOGE(TAG, "post event to user fail!");
            }
        }
    }
}
```

**Comment by liuzfesp** [comment]
HI @dereks, for this item I think it's the application's responsibility to handle it, so we will not update the document for it.
