### ISSUE TITLE
[TW#26873] How does ESP32 get gateway IP in STA mode？

### ISSUE THREAD

**Issue by ChampOnBon** [espressif/esp-idf#2590]
How does ESP32 get gateway IP in STA mode？Is there a relevant API to use？

**Comment by liuzfesp** [comment]
Hi @ChampOnBon you can call tcpip_adapter_get_ip_info() to get the IP address

**Comment by Alvin1Zhang** [comment]
@ChampOnBon Could you help share if any updates for this issue? Thanks.
