### ISSUE TITLE
[TW#26896] error with unity_config.h

### ISSUE THREAD

**Issue by ray-syrstad** [espressif/esp-idf#2594]
I am having an issue when attempting to compile esp32/app_main.o
Below is the result of the $ make command

$ make
Toolchain path: /opt/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc
Toolchain version: crosstool-ng-1.22.0-80-g6c4433a5
Compiler version: 5.2.0
Python requirements from C:/msys32/home/raymond.syrstad/esp/esp-idf/requirements.txt are satisfied.
CC build/esp32/app_main.o
In file included from C:/msys32/home/raymond.syrstad/esp/esp-idf/components/esp32/include/unity_internals.h:11:0,
                 from C:/msys32/home/raymond.syrstad/esp/esp-idf/components/esp32/include/unity.h:17,
                 from C:/msys32/home/raymond.syrstad/esp/esp-idf/components/esp32/app_main.c:4:
C:/msys32/home/raymond.syrstad/esp/esp-idf/components/esp32/app_main.c: In function 'app_main':
C:/msys32/home/raymond.syrstad/esp/esp-idf/components/esp32/include/unity_config.h:16:35: error: 'UNITY_FREERTOS_STACK_SIZE' undeclared (first use in this function)
 #define UNITY_FREERTOS_STACK_SIZE UNITY_FREERTOS_STACK_SIZE
                                   ^
C:/msys32/home/raymond.syrstad/esp/esp-idf/components/esp32/app_main.c:17:53: note: in expansion of macro 'UNITY_FREERTOS_STACK_SIZE'
     xTaskCreatePinnedToCore(unityTask, "unityTask", UNITY_FREERTOS_STACK_SIZE, NULL,
                                                     ^
C:/msys32/home/raymond.syrstad/esp/esp-idf/components/esp32/include/unity_config.h:16:35: note: each undeclared identifier is reported only once for each function it appears in
 #define UNITY_FREERTOS_STACK_SIZE UNITY_FREERTOS_STACK_SIZE
                                   ^
C:/msys32/home/raymond.syrstad/esp/esp-idf/components/esp32/app_main.c:17:53: note: in expansion of macro 'UNITY_FREERTOS_STACK_SIZE'
     xTaskCreatePinnedToCore(unityTask, "unityTask", UNITY_FREERTOS_STACK_SIZE, NULL,
                                                     ^
C:/msys32/home/raymond.syrstad/esp/esp-idf/components/esp32/include/unity_config.h:14:33: error: 'UNITY_FREERTOS_PRIORITY' undeclared (first use in this function)
 #define UNITY_FREERTOS_PRIORITY UNITY_FREERTOS_PRIORITY
                                 ^
C:/msys32/home/raymond.syrstad/esp/esp-idf/components/esp32/app_main.c:18:29: note: in expansion of macro 'UNITY_FREERTOS_PRIORITY'
                             UNITY_FREERTOS_PRIORITY, NULL, UNITY_FREERTOS_CPU);
                             ^
C:/msys32/home/raymond.syrstad/esp/esp-idf/components/esp32/include/unity_config.h:15:28: error: 'UNITY_FREERTOS_CPU' undeclared (first use in this function)
 #define UNITY_FREERTOS_CPU UNITY_FREERTOS_CPU
                            ^
C:/msys32/home/raymond.syrstad/esp/esp-idf/components/esp32/app_main.c:18:60: note: in expansion of macro 'UNITY_FREERTOS_CPU'
                             UNITY_FREERTOS_PRIORITY, NULL, UNITY_FREERTOS_CPU);
                                                            ^
make[1]: *** [/home/raymond.syrstad/esp/esp-idf/make/component_wrapper.mk:286: app_main.o] Error 1
make: *** [C:/msys32/home/raymond.syrstad/esp/esp-idf/make/project.mk:505: component-esp32-build] Error 2
 
Have tried multiple fixes, but none work.

**Comment by ray-syrstad** [comment]
I am attempting to add in a new library with code.  libplctag.  My hopes are to have the ESP32 communicate with a PLC wirelessly, just to let the PLC know that the device is active
 and is there.  The libplctag code changes a value in a PLC register and then destroys that value to set the PLC to an original state.  I am having issues with integrating this libplctag code into the existing esp-idf.


Thanks,



Raymond Syrstad
Automation Field Service Apprentice| Automation Department


5477 Westridge Court | New Berlin, WI 53151

C: 262-456-9187

pieperpower.com

 



 

SAFETY: Working Together For Tomorrow

**Comment by igrr** [comment]
Hi @ray-syrstad, sorry for the late response. Porting third-party libraries to ESP32 is not something we can help you with in the context of this issue tracker. esp32.com forum might be a better place for such discussion. If you find specific issues in the process of porting the library (such as some functionality not implemented or not working in IDF), please do report these issues here.
