### ISSUE TITLE
Peripheral HW bugs not mentioned in ECO document

### ISSUE THREAD

**Issue by michprev** [espressif/esp-idf#2596]
There are many HW bugs in ESP32 peripherals (SPI, I2C, UART, ...). Why they are not mentioned in the `ECO and Workarounds for Bugs in ESP32` document?

**Comment by loboris** [comment]
Could you describe those **HW bugs** here so that others can benefit from your knowledge.

**Comment by igrr** [comment]
Hi @michprev, while this is certainly a very important topic, please use "Documentation requests" topic on the ESP32 forum (https://esp32.com/viewtopic.php?f=5&t=905) or open a new thread in the Documentation subforum. This issue tracker is specifically for ESP-IDF, not for "everything ESP32 related".
