### ISSUE TITLE
[TW#26938] Name buffer allocation size differs in bluetooth code

### ISSUE THREAD

**Issue by terjeio** [espressif/esp-idf#2615]
spp_slot_t -> char service_name[ESP_SPP_SERVER_NAME_MAX];
btc_spp_args_t -> char name[ESP_SPP_SERVER_NAME_MAX + 1];

In fn _btc_spp_start_srv_ in file _btc_spp.c_ there is a copy between these
```
strcpy(slot->service_name, arg->start_srv.name);
```
that AFAICT may lead to a buffer overrun.

**Comment by blueMoodBHD** [comment]
Hi @terjeio ,
Thanks for your reminder, I will fix it, soon.
