### ISSUE TITLE
[TW#26953] Avoid Magic number in bluetooth `gatt_server_service_table` example

### ISSUE THREAD

**Issue by ThisNameIsNotAllowed** [espressif/esp-idf#2617]
https://github.com/espressif/esp-idf/blob/129d32772e5e5eafe88be5b9eb34687e84a6f8b8/examples/bluetooth/gatt_server_service_table/main/gatts_table_creat_demo.c#L119

Should be replaced by `.service_uuid_len = sizeof(service_uuid),` to avoid magic numbers

**Comment by Weijian-Espressif** [comment]
@ThisNameIsNotAllowed Thanks, I will modify it.
