### ISSUE TITLE
[TW#26961] OTA failed when using ETH.

### ISSUE THREAD

**Issue by welinkio** [espressif/esp-idf#2620]
Download will fail after receive some data. 
test code on commit 129d32772e5e5eafe88be5b9eb34687e84a6f8b8

**Comment by suda-morris** [comment]
Hi, @welinkio Can you show me more info about this issue?like your sdkconfig,partition table, log output?

**Comment by welinkio** [comment]
I am using LAN8720 PHY chip, attached is sdkconfig and partition info，see ota_fail_log.txt.

[ota_fail_log.txt](https://github.com/espressif/esp-idf/files/2515478/ota_fail_log.txt)


[sdkconfig.zip](https://github.com/espressif/esp-idf/files/2515128/sdkconfig.zip)

**Comment by welinkio** [comment]
[native_example_ota_fail.txt](https://github.com/espressif/esp-idf/files/2515560/native_example_ota_fail.txt)

using native ota function log. @suda-morris

**Comment by suda-morris** [comment]
hi @welinkio What if you check on the 
`Component config->Ethernet->Enable copy between Layer2 and Layer3` ?

**Comment by suda-morris** [comment]
@welinkio Thanks again, the bug has been fixed and will be merged into the master branch soon.
