### ISSUE TITLE
[TW#26964] Avoid magic numbers in `bluetooth/gatt_server` example

### ISSUE THREAD

**Issue by ThisNameIsNotAllowed** [espressif/esp-idf#2622]
https://github.com/espressif/esp-idf/blob/129d32772e5e5eafe88be5b9eb34687e84a6f8b8/examples/bluetooth/gatt_server/main/gatts_demo.c#L110

as well as  

https://github.com/espressif/esp-idf/blob/129d32772e5e5eafe88be5b9eb34687e84a6f8b8/examples/bluetooth/gatt_server/main/gatts_demo.c#L126  

Could be replaced by `.service_uuid_len = sizeof(adv_service_uuid128),` to avoid magic numbers.

**Comment by dhrishi** [comment]
That's right. Will fix it.
