### ISSUE TITLE
[TW#26962] esp_http_client crashes with is_async for non-ssl url

### ISSUE THREAD

**Issue by devsaurus** [espressif/esp-idf#2624]
## Environment

- Development Kit:      []
- Core (if using chip or module): [ESP32-Wrover]
- IDF version (``git rev-parse --short HEAD`` to get the commit id.): 7313e39fd
- Development Env:		[Make]
- Operating System:		[openSuse]
- Power Supply:         [USB|Battery]

## Problem Description

I want to access a `http://server/path` url with `esp_http_client` in asynchronous mode but the core crashes.

### Expected Behavior

Server is connected the same way as when `is_async = false`.

### Actual Behavior
```
Guru Meditation Error: Core  0 panic'ed (InstrFetchProhibited). Exception was unhandled.
```

In case of `is_async = true`, function `esp_http_client_connect()` calls `esp_transport_connect_async()`, but the member `_connect_async` is not set for transport_tcp. NULL pointer is dereferenced and core panics.

### Steps to reproduce

Compile the example below and execute. The example is an excerpt from https://github.com/espressif/esp-idf/blob/129d32772e5e5eafe88be5b9eb34687e84a6f8b8/examples/protocols/esp_http_client/main/esp_http_client_example.c

### Code to reproduce this issue

```c
esp_http_client_config_t config = {
  .url = "http://server/path",
  .event_handler = _http_event_handler,
  .is_async = true,
  .timeout_ms = 5000,
};
esp_http_client_handle_t client = esp_http_client_init(&config);
err = esp_http_client_perform(client);
```

**Comment by jitin17** [comment]
@devsaurus Thanks for bringing this to our notice. As of now, only asynchronous HTTPS connections are supported. Though it shouldn't have crashed for `http` URL, which will be resolved soon. And support for async HTTP wasn't added because it involved some changes in existing APIs, but it will be added soon.

**Comment by devsaurus** [comment]
Thanks a lot for looking into this.
