### ISSUE TITLE
[TW#26982] Bluetooth LE: Core 0 panic'ed on bt_controller_disable w. client connected OR esp_ble_set_encryption called

### ISSUE THREAD

**Issue by Xasin** [espressif/esp-idf#2626]
## Environment
- Development Kit:    none
- Core (if using chip or module): ESP32-PICO-D4 rev. 1
- IDF version: 35f9cb070
- Development Env:		Eclipse
- Operating System:		Debian 9
- Power Supply:                external 3.3V

## Problem Description
I have found the exact same error message (see log below) to be caused under two similar circumstances:
1. The ESP BT Controller is disabled via `esp_bt_controller_disable()` while a client is still connected. This does *not* throw any other error about the client connection still being on before it crashes.
2. The ESP *had* a connection with a client, during which a `esp_ble_set_encryption(ID, ESP_BLE_SEC_ENCRYPT)` was called. The client then disconnects without producing an error. On the following `esp_bt_controller_disable()`, the exact same crash is produced.

### Expected Behavior
No crash should happen when disabling the BT Controller. If disabling the BT controller without first disabling the Bluedroid controller is an invalid task, a warning should be attached to the `disable` function, either in the README or during runtime. 

### Actual Behavior
The ESP crashes with an unrelated and hard to trace error message, whose real reason can only be found out with trial and error.

### Steps to repropduce
No external circuitry is needed. Compile the following main:
https://gist.github.com/Xasin/475d2e237f4799ac1980fe481603ceaa
And connect to the ESP at boot-up. *Stay connected* until it disables BT, then observe the crash.

Due to the nature of the error message (`prvGetExpectedIdleTime` is in the logs), Tickless Idle Mode must most likely be enabled for this to work.

## Debug Logs

```
BT: Disabling controller
Guru Meditation Error: Core  0 panic'ed (LoadProhibited). Exception was unhandled.
Core 0 register dump:
PC      : 0x4004baaa  PS      : 0x00060031  A0      : 0x800875ad  A1      : 0x3ffbe650  
A2      : 0x00000000  A3      : 0x00000000  A4      : 0x8008d8b8  A5      : 0x3ffcb120  
A6      : 0x00000003  A7      : 0x00060223  A8      : 0x00000000  A9      : 0x3ffb00d8  
A10     : 0x0000000a  A11     : 0x3ffbc930  A12     : 0x00000000  A13     : 0x3ffbc920  
A14     : 0x3ffbeda0  A15     : 0x00000000  SAR     : 0x00000020  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x00000048  LBEG    : 0x4008ddfa  LEND    : 0x4008de01  LCOUNT  : 0x00000000  
0x4008ddfa: xHaveReadyTasks at /opt/ESP/esp-idf/components/freertos/tasks.c:4961
 (inlined by) prvGetExpectedIdleTime at /opt/ESP/esp-idf/components/freertos/tasks.c:2191

0x4008de01: xHaveReadyTasks at /opt/ESP/esp-idf/components/freertos/tasks.c:4961
 (inlined by) prvGetExpectedIdleTime at /opt/ESP/esp-idf/components/freertos/tasks.c:2191

Core 0 was running in ISR context:
EPC1    : 0x4004baaa  EPC2    : 0x00000000  EPC3    : 0x00000000  EPC4    : 0x00000000

Backtrace: 0x4004baaa:0x3ffbe650 0x400875aa:0x3ffbe670 0x40084f95:0x3ffbe6b0 0x4008871d:0x3ffbe6d0 0x40089437:0x3ffbe6f0 0x40082cba:0x3ffbe710 0x4000bfed:0x00000000
0x400875aa: r_lld_evt_schedule at ??:?

0x40084f95: r_ea_finetimer_isr at ??:?

0x4008871d: r_rwbt_isr at ??:?

0x40089437: r_rwbtdm_isr_wrapper at intc.c:?

0x40082cba: _xt_lowint1 at /opt/ESP/esp-idf/components/freertos/xtensa_vectors.S:1105


Rebooting...
```
## Additional requests
It would be nice to have a BLE implementation that follows the whole "low energy" thing. As such, having the BT controller stack not keep the ABP max frequency lock during the entire time it's enabled, but instead only when needed, would be very nice to have. I would like to inquire if this is doable, or if efforts are already being made in this direction.

**Comment by Weijian-Espressif** [comment]
@Xasin ,Sorry,  I will fix this crash.

**Comment by Weijian-Espressif** [comment]
@Xasin, we have fixed the bug, please updated to the latest IDF and try, thanks.

**Comment by Xasin** [comment]
@Weijian-Espressif, I haven't run into a crash similar to this in a bit, so I would say it's been fixed.
My BLE code is running smoothly now.

I do have a problem with my BT SPP code (crash upon disable then enable), and will have to make another issue about that ^^'
