### ISSUE TITLE
Reboot with server BLE and WIFI (IDFGH-438)

### ISSUE THREAD

**Issue by gigirizzi** [espressif/esp-idf#2637]
hi, i try to utilize  BLE and Wifi server, but ig i start BLE server  i have a loop of reset withi this error.

rst:0x3 (SW_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
Help :(

**Comment by negativekelvin** [comment]
That is not an error, you have to post the log that came before that.

**Comment by me-no-dev** [comment]
Maybe your application got too big and you did not select proper partition scheme? Try one that supports large apps :)

**Comment by Alvin1Zhang** [comment]
@gigirizzi Hi, sorry to get back to you so late. Does your issue still exist? Thanks.

**Comment by Alvin1Zhang** [comment]
@gigirizzi Thanks for reporting the issue. Does your issue still exist? Thanks.

**Comment by Alvin1Zhang** [comment]
@gigirizzi Thanks for reporting the issue, but will close now due to not enough details. Feel free to reopen if the issue happens. Thanks.
