### ISSUE TITLE
[TW#12215] ILI9341 LCD display support for ESP32-WROVER

### ISSUE THREAD

**Issue by Byteschmiede** [espressif/esp-idf#265]
Hi devs,

Is there any ongoing development of an officle SPI Driver for the LCD Display? Espressif is selling the DevKitJ aka ESP32-WROVER-Kit without any offical drivers or api for the onboard display.

I already used the "spi_master" example by rudi but this is very very complex and not even fast enough to do "good" stuff on it. Even to draw text or something is very hard because you have to render it and provide the RGB values of every pixel, line by line.

It would be nice if someone could integrate the Adafruit solution of the ili9341 display.

Have a nice day!

**Comment by projectgus** [comment]
Hi @Byteschmiede,

A high level API for the ILI9341 is coming, and will be supported in ESP-IDF.

There is low-level ILI9341 support in the [NESEMU code](https://github.com/espressif/esp32-nesemu/), and using Arduino libraries (either via the arduino-esp32 esp-idf component or the Arduino IDE) also works but is slow as you note.

We'll update this issue once an integrated option is available.

**Comment by Byteschmiede** [comment]
Hi @projectgus 
Thank you !

**Comment by sfranchin63** [comment]
Hi @projectgus,
you wrote that high-level API for the ILI9341 is coming. Can you tell me when the API will be ready.
Thank yuo

**Comment by sukeshak** [comment]
@Byteschmiede Have you tried this one? Since it says ILI9341 is supported.
https://github.com/loboris/ESP32_TFT_library

By next week I will be testing it... Waiting for my ESP32 to arrive :)

**Comment by krzychb** [comment]
I see ILI9341 LCD display support implemented under https://github.com/espressif/esp-iot-solution/tree/master/components/spi_devices/lcd
