### ISSUE TITLE
[TW#12874] deep sleep wakeup documentation inconsistency

### ISSUE THREAD

**Issue by BurningEnlightenment** [espressif/esp-idf#266]
Within the [External wakeup (ext1) docs](https://esp-idf.readthedocs.io/en/latest/api/system/deep_sleep.html#external-wakeup-ext1) @igrr wrote the following:
> * wake up if any of the selected pins is low
> * wake up if all the selected pins are high

But the `esp_deep_sleep_enable_ext1_wakeup()` and `esp_ext1_wakeup_mode_t` docs state something contrary:
> ESP_EXT1_WAKEUP_ALL_LOW: wake up when all selected GPIOs are low
> ESP_EXT1_WAKEUP_ANY_HIGH: wake up when any of the selected GPIOs is high

**Comment by igrr** [comment]
Thanks for pointing this out. Enum definitions are correct in this case.
I will update the docs.

**Comment by krzychb** [comment]
@FayeY, I do not see this being updated in docs v2.0

![image](https://cloud.githubusercontent.com/assets/12953787/26453101/da60ba46-4162-11e7-8bbb-0f55beda8a1a.png)

**Comment by krzychb** [comment]
@FayeY, this issue is fixed in 2.1 release and  the latest documentation, I would close it.

![screenshot from 2017-06-19 21-51-45](https://user-images.githubusercontent.com/12953787/27303023-9ac6676a-5539-11e7-8877-d540e233f0e8.png)
