### ISSUE TITLE
[TW#27193] convert_to_cmake does not work

### ISSUE THREAD

**Issue by callalilychen** [espressif/esp-idf#2660]
https://github.com/espressif/esp-idf/blob/12b2268ee56dac79988b75dbb49a453629ed8022/tools/cmake/convert_to_cmake.py#L95
produces the following error:

`IndentationError: unexpected indent`

**Comment by igrr** [comment]
Thanks for reporting this @callalilychen, fixed in https://github.com/espressif/esp-idf/commit/f4cfca4353da66be88d04adf059d8d37f1c95b11.
