### ISSUE TITLE
esp-idf V3.0 how to config the component.mk file ?

### ISSUE THREAD

**Issue by 1XiaSheng** [espressif/esp-idf#2665]
![tim 20181105155331](https://user-images.githubusercontent.com/37097029/47984913-076cd000-e113-11e8-92fd-42f23a89bf52.png)
![tim 20181105155338](https://user-images.githubusercontent.com/37097029/47984919-0b98ed80-e113-11e8-8656-478f52e139b7.png)

**Comment by 1XiaSheng** [comment]
Great God, please see the above figure, what configuration is required for each component.mk file in the directory structure?

The correct guidelines are not available at https://docs.espressif.com/projects/esp-idf/en/latest/api-guides/build-system.html.

大神,请看上面的图,目录结构中的各个component.mk文件需要填入什么配置?

在https://docs.espressif.com/projects/esp-idf/en/latest/api-guides/build-system.html 中无法得到正确指引.

**Comment by igrr** [comment]
Hi @1XiaSheng,

ESP-IDF build system does not support nested components. 

What you can do instead is: create a `components` directory in your project, and add `cfg`, `hdw`, and `usr` as component directories. Each of these directories can then include component.mk file. If you want your source files to be in `src` subdirectory and include files in `include` subdirectory of each component, then the component.mk will files look like:
```
COMPONENT_ADD_INCLUDEDIRS := include
COMPONENT_SRCDIRS := src
```

**Comment by 1XiaSheng** [comment]
thanks, i will try it now,see you later, i will reply you when i have test it in your way

**Comment by 1XiaSheng** [comment]
its working good! thanks

**Comment by woiptcs** [comment]
Hello , 
I'm having troubles adding new components to my project.
I've allready added a component directory using CMakelists.txt the esp-idf-libs for asd111x but now I cannot add more libs ... 
If I use an absolute path , than I cannot use relatives ? 
I can add multiple paths? separed by " " space ? 
No combination of CMakeLists.txt and Component.mk is valid for my I think I tried everything posible ..
