### ISSUE TITLE
[TW#27236] Bug in lwip/port/esp32/netif/ethernetif.c

### ISSUE THREAD

**Issue by wayneuroda** [espressif/esp-idf#2670]
There is a memory leak bug in some error handling code in ethernetif.c

```
  /* full packet send to tcpip_thread to process */
if (netif->input(p, netif) != ERR_OK) {
  LWIP_DEBUGF(NETIF_DEBUG, ("ethernetif_input: IP input error\n"));
  p->l2_owner = NULL;
  pbuf_free(p);
}
```

It is not correct to set `p->l2_owner = NULL;` before calling `pbuf_free(p)`. 

The same mistake is not present in wlanif.c.

**Comment by liuzfesp** [comment]
Thanks @wayneuroda for pointing this bug, we will fix it.
