### ISSUE TITLE
ssl_tls.c:5875 alloc(16717 bytes) failed

### ISSUE THREAD

**Issue by zhaochengwei** [espressif/esp-idf#2673]
![image](https://user-images.githubusercontent.com/13081827/48068487-e76e0700-e20d-11e8-8ef8-8ba0f4d88ab4.png)
As you can see, 16384 is TLS maximum message content length.But I met this problem, So what's the problem?
![image](https://user-images.githubusercontent.com/13081827/48068580-22703a80-e20e-11e8-806b-105abd8a1553.png)

esp-idf v3.1

**Comment by zhaochengwei** [comment]
> You probably ran out of free heap. You need 40k to do ssl with full length buffers.

So, how can I enlarge my full length buffers?

**Comment by negativekelvin** [comment]
No, it means there is not enough memory available.  You can try some of the menuconfig option for asymmetric buffers or reduce your app memory usage or use wrover/psram.

**Comment by zhaochengwei** [comment]
> No, it means there is not enough memory available. You can try some of the menuconfig option for asymmetric buffers or reduce your app memory usage or use wrover/psram.

OK，I solved the problem thank you !

**Comment by Jigar3690** [comment]
@zhaochengwei How did you resolved it? I am facing the same issue with exact same number of bytes!
`mbedtls: ssl_tls.c:6893 alloc(16717 bytes) failed` I did enough memory leak analysis already. Tried increasing the stack size as well. But no change.

**Comment by VitoLeo92** [comment]
> > No, it means there is not enough memory available. You can try some of the menuconfig option for asymmetric buffers or reduce your app memory usage or use wrover/psram.
> 
> OK，I solved the problem thank you !


**How did you resolved it?**

**Comment by HamzaHajeir** [comment]
I'm having the exact same issue,
the number is a preprocessor-defined.
My heap is very large at the moment of the call:

```log
                     > altcp_tls: TCP_WND is smaller than the RX decrypion buffer, connection RX might stall!
04:10:41.028 > H4AT:1: H=143412 M=110580 S=4684
04:10:41.029 > IDF/components/mbedtls/mbedtls/library/ssl_tls.c:3857: alloc(16717 bytes) failed
04:10:41.030 > mbedtls_ssl_setup failed
04:10:41.031 > tcp_close: closing in State: CLOSED
```

**Comment by hitecSmartHome** [comment]
Facing the same issue. I also have enough max contigous heap block but calloc fails with mbedtls
