### ISSUE TITLE
No phy recalibration after esp_restart() (IDFGH-448)

### ISSUE THREAD

**Issue by jaracil** [espressif/esp-idf#2677]
Hi all.
After OTA flashing i run esp_restart() to launch the new firmware. I noticed the output BLE power was too low. I suspect the old firmware calibration data is still in use.
If i turn off - on the hardware then issue disappears.
The answer is: How can i reboot by software forcing full re-calibration? 

Thanks.

**Comment by Weijian-Espressif** [comment]
@jaracil, ESP2 reads the calibration value from flash when restarting, If not found, regenerate the calibration value.

**Comment by jaracil** [comment]
@Weijian-Espressif. 
I have CONFIG_ESP32_PHY_CALIBRATION_AND_DATA_STORAGE=n (disabled)
and i suspect the calibration value is not regenerated because after soft reboot (esp_restart) 
BLE output power goes noticeable lower. 
After hard reboot (power off/on) BLE output power goes to normal level.

All this happens when i update firmware (OTA) and the new firmware was compiled with a different IDF version.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, feel free to reopen.
