### ISSUE TITLE
[TW#27381] SPI_CHECK incorrect error message

### ISSUE THREAD

**Issue by michprev** [espressif/esp-idf#2690]
- IDF version (run ``git describe --tags`` to find it): v3.1.1-6-g2aa9a2118

## Problem Description

https://github.com/espressif/esp-idf/blob/fb7ba1baa068a2267ef54b7105cf3c8a004fe4eb/components/driver/spi_master.c#L449-L454

The error message talks only about situation when using SPI via GPIO matrix but the assert fails even when using SPI via native pins (which is correct).

The error message should be changed:
`When GPIO matrix is used in full-duplex ...` -> `When SPI is used in full-duplex ...`

**Comment by ginkgm** [comment]
Hi @michprev ,
thanks for your suggestions for the error message. due to histroical reason, we thought there's no reading problem with IOMUX but actually this is triggered if the MISO delay is long even with IOMUX.

We will improve this but not backporting this to earlier version.
