### ISSUE TITLE
请问在将IDF移植至AliOS Things过程中，遇到连接libbtdm_app.a一些符号表问题

### ISSUE THREAD

**Issue by realonlyme** [espressif/esp-idf#2705]
/home/shineg/sda4/L1_things/build/compiler/gcc-xtensa-esp32/Linux64/bin/../lib/gcc/xtensa-esp32-elf/5.2.0/../../../../xtensa-esp32-elf/bin/ld: out/bleadv@esp32paybox/binary/bleadv@esp32paybox.elf section `.iram0.text' will not fit in region `iram0_0_seg'
/home/shineg/sda4/L1_things/build/compiler/gcc-xtensa-esp32/Linux64/bin/../lib/gcc/xtensa-esp32-elf/5.2.0/../../../../xtensa-esp32-elf/bin/ld: region `iram0_0_seg' overflowed by 12792 bytes
././platform/mcu/esp32/lib/libbtdm_app.a(rwip.o):(.iram1.text+0x8): undefined reference to `rwip_env'
collect2: error: ld returned 1 exit status
build/aos_target_build.mk:337: recipe for target 'out/bleadv@esp32paybox/binary/bleadv@esp32paybox.elf' failed
make[1]: *** [out/bleadv@esp32paybox/binary/bleadv@esp32paybox.elf] Error 1
build/Makefile:265: recipe for target 'main_app' failed

**Comment by Weijian-Espressif** [comment]
请先把 menuconfig 中不需要的功能关掉, 比如 蓝牙log, gattC, smp 等需要的模块关掉, 再重新编译试试.

**Comment by Alvin1Zhang** [comment]
Feel free to reopen, thanks.
