### ISSUE TITLE
[TW#27468] [request] add macro to test peer_addr_type in esp_ble_adv_params_t

### ISSUE THREAD

**Issue by chegewara** [espressif/esp-idf#2714]
What suppose to be size of `esp_ble_adv_params_t`? Because most of the time i am getting `BT_HCI: hci write adv params error 0x30` i started digging and from code i can get `sizeof(esp_ble_adv_params_t)` is 32 but i found this:
https://github.com/espressif/esp-idf/blob/80c5547b971128fdecbbcf6d8178196d35a15b73/examples/bluetooth/ble_adv/main/app_bt.c#L31

EDIT after adding `__attribute__((packed))` to few structures i am able to get `sizeof(esp_ble_adv_params_t)` equal 15, also order of parameters initialized in this example is different than order parameters in structure (maybe in C this is no issue but in C++ code it seems to be):
https://github.com/espressif/esp-idf/blob/80c5547b971128fdecbbcf6d8178196d35a15b73/examples/bluetooth/ble_adv/main/app_bt.c#L105-L112

```
typedef struct {
    uint16_t                adv_int_min;        /*!< Minimum advertising interval for
                                                  undirected and low duty cycle directed advertising.
                                                  Range: 0x0020 to 0x4000 Default: N = 0x0800 (1.28 second)
                                                  Time = N * 0.625 msec Time Range: 20 ms to 10.24 sec */
    uint16_t                adv_int_max;        /*!< Maximum advertising interval for
                                                  undirected and low duty cycle directed advertising.
                                                  Range: 0x0020 to 0x4000 Default: N = 0x0800 (1.28 second)
                                                  Time = N * 0.625 msec Time Range: 20 ms to 10.24 sec Advertising max interval */
    esp_ble_adv_type_t      adv_type;           /*!< Advertising type */
    esp_ble_addr_type_t     own_addr_type;      /*!< Owner bluetooth device address type */
    esp_bd_addr_t           peer_addr;          /*!< Peer device bluetooth device address */
    esp_ble_adv_channel_t   channel_map;        /*!< Advertising channel map */
    esp_ble_adv_filter_t    adv_filter_policy;  /*!< Advertising filter policy */
} esp_ble_adv_params_t;
```

Last one thing i found is peer_addr_type can be only `BLE_ADDR_TYPE_PUBLIC` or `BLE_ADDR_TYPE_RANDOM` with `BLE_ADDR_TYPE_RPA_PUBLIC` -> `BT_HCI: hci write adv params error 0x30`. 
With all described changes in code finally i am able to control advertising params and get rid of `BT_HCI: hci write adv params error 0x30`

PS im not sure yet if all described changes are necessary or only peer_addr_type i messing in here, but most of the time i didnt set peer_adv_type at all; this is how raw adv params looks like with original code(hex dump):
```
W (687) BLEAdvertising: 20 00 40 00 00 00 00 00 00 00 00 00 01 01 01 01
W (700) BLEAdvertising: 01 01 00 00 02 00 00 00 07 00 00 00 00 00 00 00
```

**Comment by chegewara** [comment]
I found the problem. From all steps described above only one is necessary, initializing peer_addr_type with value `BLE_ADDR_TYPE_PUBLIC` or `BLE_ADDR_TYPE_RANDOM` any other value is not valid> Maybe we could add macro to test valid value here:
https://github.com/espressif/esp-idf/blob/master/components/bt/bluedroid/btc/profile/std/gap/btc_gap_ble.c#L498-L502

Thanks

**Comment by Weijian-Espressif** [comment]
@chegewara, Thanks, I will fix it.

**Comment by chegewara** [comment]
closed by https://github.com/espressif/esp-idf/commit/09b2cd7d26bc04a090f73d489266785cd020df60
