### ISSUE TITLE
Request: Add captive portal option to dhcp server (IDFGH-465)

### ISSUE THREAD

**Issue by rapli** [espressif/esp-idf#2723]
In order to automatically connect to a device's SoftAP one could use the dhcp captive portal option (code 160) ([see RFC 7710](https://tools.ietf.org/html/rfc7710)). Right now the dhcp server does not offer the capability to set this dhcp option.
Something that could be considered in this regard is to allow setting **any** DHCP option, not only those currently supported, but at least the captive portal option could be very helpful for any stand alone device offering an access point.

**Comment by liuzfesp** [comment]
@rapli, we have put it into our TODO list.

**Comment by freakyxue** [comment]
hi @rapli 
The code has been synchronized with IDF, and the review is in progress

**Comment by freakyxue** [comment]
hi @rapli 
After internal discussion, this function is not practical, and it is not included in IDF for the time being. If you need this function, I can provide patch. This problem will be closed temporarily. If you have other questions, you can open this issue at any time，thanks！

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, feel free to reopen.

**Comment by septatrix** [comment]
@freakyxue if you still have the patch lying around I would like to get my hands on it.

Issues #4075 and #7099 would also be solved by adding such an option and e.g. Arduino provides an [`DNSServer` library](https://github.com/esp8266/Arduino/tree/master/libraries/DNSServer) which can be used to archive a similar goal so I think the demand for such a feature does exist.

**Comment by siukeung** [comment]
@septatrix I need the DHCP captive portal option (code 160) patch, can you create the patch based on the latest master?

**Comment by septatrix** [comment]
See dd3d27a03c6c0593be9d33e3951e6ef2bd2a62f3

**Comment by bwjohns4** [comment]
Is there a way to add custom DHCP Server Options when in AP mode? I got this to work on ESP8266 per this PR esp8266/Arduino#8451. Does anyone know how to do something similar for ESP32? I'm trying add Option 114 for Captive Portals.
