### ISSUE TITLE
WIFI+BT+BLE (IDFGH-469)

### ISSUE THREAD

**Issue by akshar001** [espressif/esp-idf#2728]
Hello,
We are using BT+BLE+WIFI in one of our project,
BT is specifically used for SPP server to view log over BT.
But There is some RF calibration error showing when all runs at same time?

**Comment by muratsplat** [comment]
@akshar001  Do you want to use BT+BLE at same time ? I don't know that they can work at same time.

**Comment by TianHao-Espressif** [comment]
@akshar001 , could your describe the error with pasting a log?

**Comment by akshar001** [comment]
@TianHao-Espressif i will post all of the things that we will need to analyze. @muratsplat espressif have mentioned that esp32 can run at both mode bt and wifi at the same time. Yes there might not have been achieved or might be but esp32 is capable of that! That's a beauty of it

**Comment by Alvin1Zhang** [comment]
@akshar001 Could you help share any logs regarding this issue? Thanks.

**Comment by Alvin1Zhang** [comment]
Could you help share any logs regarding this issue? Thanks.

**Comment by akshar001** [comment]
Hello @Alvin1Zhang what type of log you want?

**Comment by Alvin1Zhang** [comment]
@akshar001 Thanks for reporting the issue, will close due to short of feedback, feel free to reopen if you still have the issue, thanks.
