### ISSUE TITLE
[TW#12212] VFS and LWIP should share file/socket descriptor space

### ISSUE THREAD

**Issue by rojer** [espressif/esp-idf#273]
Currently some functions of the POSIX file API are routed to VFS and those that are partof the BSD socket API are routed to LWIP. this is very confusing. for example, it is possible to `open` a file, but subsequent `read` will fail because it goes to LWIP.
of course, one can side-step the issue by using buffered file i/o (`fopen`, `fread`), but it's not ideal. it should be possible to route LWIP through VFS and make them share descriptor space.

**Comment by young-mu** [comment]
Hi, @rojer. I think you can consider the LWIP build option **LWIP_SOCKET_OFFSET** to let socket descriptor starting from an offset to avoid the descriptor overlap with VFS file descriptor.

**Comment by rojer** [comment]
the issue is not overlap of descriptor space, but the fact that `read` is routed to LWIP only and cannot be used for operations on VFS files.

**Comment by young-mu** [comment]
Okay.

**Comment by jsarrett** [comment]
I also have run in to this problem.  It's very serious because it means basically that libc is linking unreliably.  It's not at all clear which read or write will be linked to a component.  LWIP_SOCKET_OFFSET should make it easy enough to fix inside of newlib, but that call routing *has* to be done at runtime.

**Comment by chanibal** [comment]
@igrr, in a [forum post from half a year ago](https://www.esp32.com/viewtopic.php?t=2317), you mentioned that you'll fix the LWIP macro issues with this ticket. As far as I see in the closing commit, that was not the case.

I know, there is the `#undef` hack, but frankly it's very annoying to have issues with such common indentifiers. Not only `bind`, but also the lack of `send` is quite annoying.

Any chance to fix this, perhaps attach it to another ticket?

**Comment by projectgus** [comment]
@chanibal
> you mentioned that you'll fix the LWIP macro issues with this ticket. As far as I see in the closing commit, that was not the case.

Sorry we missed this comment on this closed issue until just now. I agree we should fix this properly. Could you please open a new issue to keep track of this one?
