### ISSUE TITLE
[TW#27570] SPI flash FAT partition corruption with esp-idf master

### ISSUE THREAD

**Issue by markwj** [espressif/esp-idf#2730]
## Environment

- Development Kit:      none
- Kit version (for WroverKit/PicoKit/DevKitC): none
- Module or chip used:  ESP32-WROVER 16MB
- IDF version (run ``git describe --tags`` to find it): v3.2-beta1-208-g0d7f2d77c
- Build System:         make
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it): (crosstool-NG crosstool-ng-1.22.0-80-g6c4433a) 5.2.0
- Operating System:     macOS
- Power Supply:         USB

## Problem Description

TLDR: Between May and July 2018 a change was made to esp idf master that is causing corruption on FAT filesystems mounted on SPI flash.

Our project uses a partitions.csv as follows:

```
# Name,   Type, SubType, Offset,   Size
nvs,      data, nvs,     0x9000,  0x4000
otadata,  data, ota,     0xd000,  0x2000
phy_init, data, phy,     0xf000,  0x1000
factory,  app,  factory, 0x10000,  4M
ota_0,    app,  ota_0,   ,         4M
ota_1,    app,  ota_1,   ,         4M
store,    data, fat,     ,         1M
```

The 'store' partition is formatted as FAT, as follows:

```cpp
esp_vfs_fat_mount_config_t m_store_fat;
wl_handle_t m_store_wlh;
memset(&m_store_fat,0,sizeof(esp_vfs_fat_sdmmc_mount_config_t));
m_store_fat.format_if_mount_failed = true;
m_store_fat.max_files = 5;
esp_vfs_fat_spiflash_mount("/store", "store", &m_store_fat, &m_store_wlh);
```

We have previously used a clone of esp idf master, dated around May 22 2018, without issues. The partition is very reliable.

However, on Jul 6 2018, we updated our clone to use the latest esp idf master at that time. Shortly afterwards, users started to report that their 'store' filesystem contents were corrupted. We rolled back.

We have now tried again (updating on Oct 20 2018 to v3.2-beta1-208-g0d7f2d77c) and immediately had the same issue. Random corruption of FAT filesystem in SPI flash.

### Expected Behavior

No corruption of FAT filesystem.

### Actual Behavior

Corruption of FAT filesystem.

### Steps to reproduce

1. Create a partition in SPI flash, and mount FAT filesystem
2. Read and write to files on FAT filesystem
3. Reboot
4. Observe random corruption and unmountable filesystem

### Code to reproduce this issue

```cpp
esp_vfs_fat_mount_config_t m_store_fat;
wl_handle_t m_store_wlh;
memset(&m_store_fat,0,sizeof(esp_vfs_fat_sdmmc_mount_config_t));
m_store_fat.format_if_mount_failed = true;
m_store_fat.max_files = 5;
esp_vfs_fat_spiflash_mount("/store", "store", &m_store_fat, &m_store_wlh);
```

## Debug Logs

n/a

## Other items if possible

Please advise if you need anything further.

**Comment by igrr** [comment]
Hi @markwj if the issue is reproducible, could you please raise log level to Verbose and share relevant logs (where corruption happens and partition is not mountable)? Also, when you say "random corruption", does this only mean that the partition is not mountable, or that partition is mountable but data inside files is corrupted?

**Comment by igrr** [comment]
Also could you possibly attach your sdkconfig? Interested in wear_levelling and FATFS configuration items.

**Comment by dmitry1945** [comment]
Hi @markwj , I have some additional questions: 
how easy is to reproduce the problem, how you check the filesystem and could you please provide a log in debug mode?
We have tried it, and we are not able to reproduce the problem. We need your help.
Regards,
Dmitry

**Comment by markwj** [comment]
Issue is hard to reproduce. It seems random. If we deploy to a dozen devices, it seems that one or two report the corruption within a week. We don't often write to the 'store' FAT partition. Mostly reads (and very few of those).

Corruption seems to make partition unmountable. We think the 'format_if_mount_failed = true' option causes it to be re-formatted on mount so wipes all data.

We will try to reproduce in the lab, By turning off the format_if_mount_failed option, we should be able to see what is going on. But may take some time. Attached is our sdkconfig.

[sdkconfig.txt](https://github.com/espressif/esp-idf/files/2611063/sdkconfig.txt)

**Comment by dexterbg** [comment]
Boot log with level verbose attached. Look for "ovms_main: Mounting CONFIG..."

The mount succeeds on the first boot, the partition is operational.
It fails on the second and all further boots. Last boot in the log is a cold reboot (marked).

[config-corruption.log](https://github.com/espressif/esp-idf/files/2611277/config-corruption.log)

**Comment by dexterbg** [comment]
I'll do some bisecting now to narrow this down.

**Comment by dexterbg** [comment]
Due to the nature of the bug, this is very time consuming; the bug sometimes just disappears, the hardware then needs to be kept powered off for some hours to get it back.

Intermediate status: the bug should originate within this range of commits:

```
balzer@leela:~/esp/esp-idf> git rev-list 9d609af54c63e7f949a4fbc43d4f1c13b57f49d8 ^9d2f7c60d9aef9860c61c2756318ada68c80fddf
9d609af54c63e7f949a4fbc43d4f1c13b57f49d8
f392727abf7d56490c2f33127a59bfac42c937e0
e834d6fffc23a6fcfc0d2e871c9235417a7fb48f
35842d02abb5f574aaab466d46081a232fdd20a6
f05f3fbde87a9ce45c6818f71b49cd13888fd457
a6d6c58ecadb9759a0bacf35cd7332ac641e598d
321b1e02052de95db60ddce87eecce5f9e04e9b8
40486c872345584d34949b3ce83f9e956a7eea13
```

 …with `9d609af54c63e7f949a4fbc43d4f1c13b57f49d8` being the last identified bad commit, and `9d2f7c60d9aef9860c61c2756318ada68c80fddf` being the last good.

I'll try to continue the hunt tomorrow.

**Comment by dmitry1945** [comment]
Thank you @dexterbg, the place is clear.

**Comment by dexterbg** [comment]
Thanks for the fast reply @dmitry1945. Tell me if you'd like me to test a fix.

**Comment by dmitry1945** [comment]
Hi guys!
@dexterbg, @markwj do you see this problem after reset that interrupts access to the file system?

**Comment by dexterbg** [comment]
Our reboot procedure takes care to finish all file system accesses and do proper umounts before executing the actual reset -- you can see that shutdown process in the log.

Sometimes we get a FreeRTOS crash `esp-idf/components/freertos/queue.c:620 (xQueueTakeMutexRecursive)- assert failed!` when shutting down, and I had several other crashes during shutdown while testing the different commit stages.

None of these crashes made a difference for this bug, if it was there before, it persisted, if it wasn't it wouldn't appear from the crash.

**Comment by dmitry1945** [comment]
OK. Thanks, @dexterbg.

**Comment by markwj** [comment]
Note that our application doesn't write to the partition very often. It is primarily used to store configuration values and scripts, so gets written very infrequently (often not for months). Configurations are also cached in ram, so not often accessed. I don't think the issue is related to an unclean shutdown, although this being an embedded system we have very little control over that.

**Comment by dmitry1945** [comment]
Hi guys, 
I need your help with reproducing the problem. 
For that, could you please make next changes and test the result?
I file WL_Flash.cpp line 183:
```
        result = this->updateVersion();
```
please change to
```

//        result = this->updateVersion();
        result = ESP_FAIL;

```
The final code should looks so:
```
        //result = this->updateVersion();
        result = ESP_FAIL;
        if (result == ESP_FAIL) {
            ESP_LOGD(TAG, "%s: init flash sections", __func__);
            result = this->initSections();
            WL_RESULT_CHECK(result);
        }
        result = this->recoverPos();
        WL_RESULT_CHECK(result);
```

That means that we disable the version check just to be sure that the problem is not there.
Thanks,
Dmitry

**Comment by dexterbg** [comment]
Dmitry, sorry for the delay, my module hasn't produced the bug since sunday, so I currently can't verify the workaround. I'll check with the other developers.

**Comment by dmitry1945** [comment]
Thank you, Michael.

**Comment by dexterbg** [comment]
Dmitry, sorry for the long delay, I finally managed to reproduce this.

Assuming this is related to the flash version update I tried specifically formatting with the old idf version and then booting into the new one, and that reliably triggers the bug.

**Unpatched new version, first boot**:

```
I (665) ovms_main: Mounting CONFIG...
V (665) wl_flash: config start_addr=0x00000000, full_mem_size=0x00100000, page_size=0x00001000, sector_size=0x00001000, updaterate=0x00000010, wr_size=0x00000010, version=0x00000002, temp_buff
_size=0x00000020
D (675) wl_flash: config - config result: state_size=0x00002000, cfg_size=0x00001000, addr_cfg=0x000ff000, addr_state1=0x000fb000, addr_state2=0x000fd000, flash_size=0x000fa000
D (695) wl_flash: init - config ID=2, stored ID=1, access_count=0, block_size=4096, max_count=16, pos=0, move_count=0x00000000
D (705) wl_flash: init starts: crc1= 0x07031690, crc2 = 0x07031690, this->state.crc= 0xabba1234, state_copy->crc= 0xabba1234, version=2, read_version=1
D (725) wl_flash: init: try to update version - crc1= 0x07031690, crc2 = 0x07031690, result= 0x00000000
V (725) wl_flash: updateV1_V2 start
D (735) wl_flash: updateV1_V2 - process crc1=0x4c4ef2a6, crc2=0x4c4ef2a6, v1_crc1=0x4c4ef2a6, v1_crc2=0x4c4ef2a6, version=1
I (745) wl_flash: updateV1_V2 Update from V1 to V2, crc=0x4c4ef2a6, 
V (755) wl_flash: updateV1_V2- result= 0x00000000, pos= 0, pos_bits= 0x000000ff
I (755) wl_flash: updateV1_V2 max_pos=251, pos=0, state.ver=1, state2.ver=1
V (885) wl_partition: erase_range - start_address=0x000fb000, size=0x00002000, result=0x00000000
V (995) wl_partition: erase_range - start_address=0x000fd000, size=0x00002000, result=0x00000000
D (995) wl_flash: updateV1_V2 - move_count= 0x00000000, pos= 0x00000000
I (995) wl_flash: updateV1_V2 update result ver=2, pos=0
V (1005) wl_flash: recoverPos start
V (1005) wl_flash: recoverPos - check pos: result=0x00000000, position= 0, pos_bits= 0x00000001
V (1015) wl_flash: recoverPos - check pos: result=0x00000000, position= 1, pos_bits= 0x00000000
D (1025) wl_flash: recoverPos - this->state.pos= 0x00000001, position= 0x00000001, result= 0x00000000, max_pos= 0x000000fb
V (1035) wl_flash: recoverPos done
```

**Unpatched new version, second boot**: it tries to update V1→V2 again, failing to do so:

```
I (665) ovms_main: Mounting CONFIG...
V (665) wl_flash: config start_addr=0x00000000, full_mem_size=0x00100000, page_size=0x00001000, sector_size=0x00001000, updaterate=0x00000010, wr_size=0x00000010, version=0x00000002, temp_buff
_size=0x00000020
D (685) wl_flash: config - config result: state_size=0x00002000, cfg_size=0x00001000, addr_cfg=0x000ff000, addr_state1=0x000fb000, addr_state2=0x000fd000, flash_size=0x000fa000
D (695) wl_flash: init - config ID=2, stored ID=2, access_count=0, block_size=4096, max_count=16, pos=0, move_count=0x00000000
D (705) wl_flash: init starts: crc1= 0x2de60512, crc2 = 0x2de60512, this->state.crc= 0x63e36d6e, state_copy->crc= 0x63e36d6e, version=2, read_version=2
D (725) wl_flash: init: try to update version - crc1= 0x2de60512, crc2 = 0x2de60512, result= 0x00000000
V (735) wl_flash: updateV1_V2 start
D (735) wl_flash: updateV1_V2 - process crc1=0x5efb5d48, crc2=0x5efb5d48, v1_crc1=0xef1fee53, v1_crc2=0xef1fee53, version=2
D (745) wl_flash: init: init flash sections
V (865) wl_partition: erase_range - start_address=0x000fb000, size=0x00002000, result=0x00000000
V (965) wl_partition: erase_range - start_address=0x000fd000, size=0x00002000, result=0x00000000
V (1015) wl_partition: erase_range - start_address=0x000ff000, size=0x00001000, result=0x00000000
D (1015) wl_flash: initSections - this->state->max_count= 0x00000010, this->state->max_pos= 0x000000fb
D (1015) wl_flash: initSections - result= 0x00000000
V (1025) wl_flash: recoverPos start
V (1025) wl_flash: recoverPos - check pos: result=0x00000000, position= 0, pos_bits= 0x00000000
D (1035) wl_flash: recoverPos - this->state.pos= 0x00000000, position= 0x00000000, result= 0x00000000, max_pos= 0x000000fb
V (1045) wl_flash: recoverPos done
D (1045) wl_flash: init - move_count= 0x00000000
D (1055) vfs_fat_spiflash: using pdrv=0
V (1055) ff_diskio_spiflash: ff_wl_ioctl: cmd=2

V (1065) ff_diskio_spiflash: ff_wl_read - pdrv=0, sector=0, count=1

D (1065) wl_flash: read - src_addr= 0x00000000, size= 0x00001000
V (1075) wl_flash: calcAddr - addr= 0x00000000 -> result= 0x00001000, dummy_addr= 0x00000000
W (1085) vfs_fat_spiflash: f_mount failed (13)
I (1085) vfs_fat_spiflash: Formatting FATFS partition, allocation unit size=4096
```

**Patched new version**: patch applied as you suggested, booting with a V1 formatted flash does this:

```
I (664) ovms_main: Mounting CONFIG...
V (664) wl_flash: config start_addr=0x00000000, full_mem_size=0x00100000, page_size=0x00001000, sector_size=0x00001000, updaterate=0x00000010, wr_size=0x00000010, version=0x00000002, temp_buff
_size=0x00000020
D (674) wl_flash: config - config result: state_size=0x00002000, cfg_size=0x00001000, addr_cfg=0x000ff000, addr_state1=0x000fb000, addr_state2=0x000fd000, flash_size=0x000fa000
D (694) wl_flash: init - config ID=2, stored ID=1, access_count=0, block_size=4096, max_count=16, pos=0, move_count=0x00000000
D (704) wl_flash: init starts: crc1= 0xa57a9f09, crc2 = 0xa57a9f09, this->state.crc= 0xffffffff, state_copy->crc= 0xffffffff, version=2, read_version=1
D (724) wl_flash: init: try to update version - crc1= 0xa57a9f09, crc2 = 0xa57a9f09, result= 0x00000000
D (724) wl_flash: init: init flash sections
V (854) wl_partition: erase_range - start_address=0x000fb000, size=0x00002000, result=0x00000000
V (954) wl_partition: erase_range - start_address=0x000fd000, size=0x00002000, result=0x00000000
V (1014) wl_partition: erase_range - start_address=0x000ff000, size=0x00001000, result=0x00000000
D (1014) wl_flash: initSections - this->state->max_count= 0x00000010, this->state->max_pos= 0x000000fb
D (1014) wl_flash: initSections - result= 0x00000000
V (1024) wl_flash: recoverPos start
V (1024) wl_flash: recoverPos - check pos: result=0x00000000, position= 0, pos_bits= 0x00000000
D (1034) wl_flash: recoverPos - this->state.pos= 0x00000000, position= 0x00000000, result= 0x00000000, max_pos= 0x000000fb
V (1044) wl_flash: recoverPos done
D (1044) wl_flash: init - move_count= 0x00000000
D (1054) vfs_fat_spiflash: using pdrv=0
V (1054) ff_diskio_spiflash: ff_wl_ioctl: cmd=2

V (1064) ff_diskio_spiflash: ff_wl_read - pdrv=0, sector=0, count=1

D (1064) wl_flash: read - src_addr= 0x00000000, size= 0x00001000
V (1074) wl_flash: calcAddr - addr= 0x00000000 -> result= 0x00001000, dummy_addr= 0x00000000
V (1084) ff_diskio_spiflash: ff_wl_read - pdrv=0, sector=2, count=1
```

…and everything is working and keeps working over reboots.

So you're right, it's a failure of the V1→V2 update.

I can now easily and reliably reproduce the bug by switching boot partitions, please tell me if you need another test.

Regards,
Michael

**Comment by dmitry1945** [comment]
Thank you Michael,
I will check.

**Comment by dmitry1945** [comment]
Hi Michael!
 Could you please look to your source and check, where you have this line:
In WL_Flash,cpp, method updateV1_V2(), you have:
first:
```
        this->state.version = 2;
        this->state.pos = 0;
===>    this->state.crc = crc32::crc32_le(WL_CFG_CRC_CONST, (uint8_t *)&this->state, offsetof(wl_state_t, crc));
        this->state.device_id = esp_random();
        memset(this->state.reserved, 0, sizeof(this->state.reserved));

```
or second:

```
       this->state.version = 2;
        this->state.pos = 0;
        this->state.device_id = esp_random();
        memset(this->state.reserved, 0, sizeof(this->state.reserved));
===>    this->state.crc = crc32::crc32_le(WL_CFG_CRC_CONST, (uint8_t *)&this->state, WL_STATE_CRC_LEN_V2);

```
Thanks!

**Comment by dexterbg** [comment]
I've got the first version.

**Comment by dmitry1945** [comment]
And actually this is the problem. In master we already have fix this, but I think you have got this version by accident. 
The reason for the problem is next: in your version we calculating CRC and than write new id to the state. Sure the next time you run the program, the CRC will be wrong, and the WL module will initialize it, and fatfs will format it.
Please check that now you have next version of method (this is the actual one):

```
esp_err_t WL_Flash::updateV1_V2()
{
    esp_err_t result = ESP_OK;
    // Check crc for old version and old version
    ESP_LOGV(TAG, "%s start", __func__);
    int check_size = WL_STATE_CRC_LEN_V1;
    // Chech CRC and recover state
    uint32_t crc1 = crc32::crc32_le(WL_CFG_CRC_CONST, (uint8_t *)&this->state, check_size);
    wl_state_t sa_copy;
    wl_state_t *state_copy = &sa_copy;
    result = this->flash_drv->read(this->addr_state2, state_copy, sizeof(wl_state_t));
    WL_RESULT_CHECK(result);
    uint32_t crc2 = crc32::crc32_le(WL_CFG_CRC_CONST, (uint8_t *)state_copy, check_size);

    // For V1 crc in place of device_id and version
    uint32_t v1_crc1 = this->state.device_id;
    uint32_t v1_crc2 = state_copy->device_id;

    ESP_LOGD(TAG, "%s - process crc1=0x%08x, crc2=0x%08x, v1_crc1=0x%08x, v1_crc2=0x%08x, version=%i", __func__, crc1, crc2, v1_crc1, v1_crc2, this->state.version);

    if ((crc1 == v1_crc1) && (crc2 == v1_crc2) && (v1_crc1 == v1_crc2) && (this->state.version == 1) && (state_copy->version == 1)) {
        // Here we have to update all internal structures
        ESP_LOGI(TAG, "%s Update from V1 to V2, crc=0x%08x, ", __func__, crc1);
        uint32_t pos = 0;

        for (size_t i = 0; i < this->state.max_pos; i++) {
            uint8_t pos_bits;
            result = this->flash_drv->read(this->addr_state1 + sizeof(wl_state_t) + i * this->cfg.wr_size, &pos_bits, 1);
            WL_RESULT_CHECK(result);
            ESP_LOGV(TAG, "%s- result= 0x%08x, pos= %i, pos_bits= 0x%08x", __func__, (uint32_t)result, (uint32_t)pos, (uint32_t)pos_bits);
            pos = i;
            if (pos_bits == 0xff) {
                break; // we have found position
            }
        }
        ESP_LOGI(TAG, "%s max_pos=%i, pos=%i, state.ver=%i, state2.ver=%i", __func__, (uint32_t)this->state.max_pos, (uint32_t)pos, (uint32_t)this->state.version, (uint32_t)state_copy->version);
        if (pos == this->state.max_pos) {
            pos--;
        }
        WL_RESULT_CHECK(result);

        this->state.version = 2;
        this->state.pos = 0;
        this->state.device_id = esp_random();
        memset(this->state.reserved, 0, sizeof(this->state.reserved));
        this->state.crc = crc32::crc32_le(WL_CFG_CRC_CONST, (uint8_t *)&this->state, WL_STATE_CRC_LEN_V2);

        result = this->flash_drv->erase_range(this->addr_state1, this->state_size);
        WL_RESULT_CHECK(result);
        result = this->flash_drv->write(this->addr_state1, &this->state, sizeof(wl_state_t));
        WL_RESULT_CHECK(result);

        memset(this->temp_buff, 0, this->cfg.wr_size);
        for (uint32_t i = 0 ; i <= pos; i++) {
            this->fillOkBuff(i);
            result = this->flash_drv->write(this->addr_state1 + sizeof(wl_state_t) + i * this->cfg.wr_size, this->temp_buff, this->cfg.wr_size);
            WL_RESULT_CHECK(result);
        }

        result = this->flash_drv->erase_range(this->addr_state2, this->state_size);
        WL_RESULT_CHECK(result);
        result = this->flash_drv->write(this->addr_state2, &this->state, sizeof(wl_state_t));
        WL_RESULT_CHECK(result);
        ESP_LOGD(TAG, "%s - move_count= 0x%08x, pos= 0x%08x", __func__, this->state.move_count, this->state.pos);

        memset(this->temp_buff, 0, this->cfg.wr_size);
        for (uint32_t i = 0 ; i <= pos; i++) {
            this->fillOkBuff(i);
            result = this->flash_drv->write(this->addr_state2 + sizeof(wl_state_t) + i * this->cfg.wr_size, this->temp_buff, this->cfg.wr_size);
            WL_RESULT_CHECK(result);
        }
        this->state.pos = pos;
        return result;
    }

    return ESP_FAIL;
}
```

**Comment by dexterbg** [comment]
That seems to be the solution, a test build with the current HEAD hasn't shown any issues yet.

…we apparently had a very bad timing, I see you submitted the fix just five days after our merge. Thanks & sorry for wasting your time.

Regards,
Michael

**Comment by dmitry1945** [comment]
No problem!
You are welcome!
