### ISSUE TITLE
[TW#27581] Esp HTTP Client can't use path variable in config

### ISSUE THREAD

**Issue by IBeRyUS** [espressif/esp-idf#2733]
## Environment

- Development Kit:      [custom board]
- Kit version (-)
- Module or chip used:  [ESP32-WROOM-32]
- IDF version (run ``git describe --tags`` to find it): 
    v3.1.1
- Build System:         [Eclipse, make]
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it):
   xtensa-esp32-elf-gcc.exe (crosstool-NG crosstool-ng-1.22.0-80-g6c4433a5) 5.2.0

- Operating System:     [Windows]
- Power Supply:         [onboard 3.3v supply]

## Problem Description

esp_http_client library can't use esp_http_client_config_t structure's path variable. I need to create every URL for config changes. 

### Expected Behavior

```cpp
                esp_http_client_config_t httpConfig;
                httpConfig.host             = "192.168.137.1";
                httpConfig.port             = 8000;
                httpConfig.path             = "/test.json";
```
after this settings url should be ```"http://192.168.137.1:8000/test.json"``` but library doesn't do it. When i check my server logs all requests made without path. Below you can find the response of server for that settings.
```
192.168.137.235 - - [23/Nov/2018 10:30:51] "GET / HTTP/1.1" 200 -
```

### Code to reproduce this issue

```cpp
#include "esp_log.h"
#include <esp_http_client.h>

void app_main()
{
                esp_http_client_config_t httpConfig;
                httpConfig.host             = "192.168.137.1";
                httpConfig.port             = 8000;
                httpConfig.path             = "/test.json";
                httpClient = esp_http_client_init(&httpConfig);
  }

```

**Comment by jitin17** [comment]
@IBeRyUS This problem has been resolved in this [commit](https://github.com/espressif/esp-idf/commit/4a667ee12c87882de950c83c20c27005805c54ac). PTAL.
