### ISSUE TITLE
[TW#27597] BT_BTC: btc_gattc_arg_deep_copy 9 no mem

### ISSUE THREAD

**Issue by chegewara** [espressif/esp-idf#2737]
This error still exists. This error shows when i try to write 0 length value to peer device characteristic:
`BT_BTC: btc_gattc_arg_deep_copy 9 no mem`

**Comment by Weijian-Espressif** [comment]
@chegewara, IDF have a check that value cannot be NULL.

**Comment by Weijian-Espressif** [comment]
We have no time to solve this problem now.

**Comment by chegewara** [comment]
@Weijian-Espressif 
Its not issue to me, it does not have to be solved. Just wanted to report, nothing more than that.
