### ISSUE TITLE
SPI DIO/QIO incorrect SPI_CHECK

### ISSUE THREAD

**Issue by michprev** [espressif/esp-idf#2738]
## Environment

- IDF version: v3.1.1-46-gcdd3131f8, also present in 0d7f2d7

## Problem Description

https://github.com/espressif/esp-idf/blob/0d7f2d77c2eee51dce3fa7c8430a641c65cd9719/components/driver/spi_master.c#L1103

Shouldn't it be 
`SPI_CHECK(!((trans_desc->flags & (SPI_TRANS_MODE_DIO|SPI_TRANS_MODE_QIO)) && (handle->cfg.flags & SPI_DEVICE_HALFDUPLEX)), "incompatible iface params", ESP_ERR_INVALID_ARG);`
?

**Comment by negativekelvin** [comment]
No because the error is when halfduplex is not set which the bAND will give you 0 but you need 1 to complete the AND

**Comment by michprev** [comment]
Yay, I thought that SPI_DEVICE_HALFDUPLEX represents standard 3-wire half duplex mode. Thank you.
