### ISSUE TITLE
[TW#27605] SPI half-duplex and full-duplex same device

### ISSUE THREAD

**Issue by michprev** [espressif/esp-idf#2739]
- IDF version: v3.1.1-46-gcdd3131f8

## Problem Description

It is not possible to use SPI master driver in both half-duplex and full-duplex modes with the same device (spi_device_handle_t). It is needed to remove the device from the bus and it again.

This may be needed when using DIO/QIO transmissions and standard full-duplex transmissions.

**Comment by ginkgm** [comment]
Do you have spec for this kind of chip?

**Comment by Alvin1Zhang** [comment]
@michprev Feel free to reopen this issue if you have any updates. Thanks.
