### ISSUE TITLE
SPI DMA free on error (IDFGH-473)

### ISSUE THREAD

**Issue by michprev** [espressif/esp-idf#2740]
## Environment
- IDF version: v3.1.1-46-gcdd3131f8 (also present in master)

## Problem Description

https://github.com/espressif/esp-idf/blob/0d7f2d77c2eee51dce3fa7c8430a641c65cd9719/components/driver/spi_master.c#L349

It is called even if `dma_chan` is set to 0. Because of this 

https://github.com/espressif/esp-idf/blob/0d7f2d77c2eee51dce3fa7c8430a641c65cd9719/components/driver/spi_common.c#L124

this assert fails.

**Comment by ginkgm** [comment]
Thanks, we'll fix this. This only happens when initialization fails, doesn't affect your normal use.

**Comment by ginkgm** [comment]
I think the master part is fixed in 28b2e113ca4dd28284e2bda07451d36b56356a5d
