### ISSUE TITLE
SPI dummy bits not configurable per transaction (IDFGH-474)

### ISSUE THREAD

**Issue by michprev** [espressif/esp-idf#2741]
## Environment

- IDF version: v3.1.1-46-gcdd3131f8 / master

## Problem Description

https://github.com/espressif/esp-idf/blob/0d7f2d77c2eee51dce3fa7c8430a641c65cd9719/components/driver/include/driver/spi_master.h#L143-L151

Why don't we have dummy bits configurable?

**Comment by ginkgm** [comment]
What's your use case for the configurable dummy bits? Is there any slave needs that?

Currently the dummy bits are used to:
1. fix the timing in the driver
2. match the slave requirement for dummy bits (usually in bytes). And I think most slave devices only requires a fixed length of dummy bits.

**Comment by michprev** [comment]
https://www.winbond.com/resource-files/w25q128fv%20rev.l%2008242015.pdf pages 26, 27, 28 - number of dummy bytes differs
