### ISSUE TITLE
[TW#27710] UART0 not works after setting UART1 as console output

### ISSUE THREAD

**Issue by keelung-yang** [espressif/esp-idf#2775]
* ESP32-PICO-Kit
* Lastest esp-idf for windows
------
I Changed UART port from 1 to 0 and set all pins to UART_PIN_NO_CHANGE in uart_echo example. It works.
But after setting UART1(Tx:18, Rx23) as console output by menuconfig.
It doesn't work: no any response received after sending data to UART0 & UART1.

I also tried UART1(Tx:4, Rx:5) as in uart_echo example, it doesn't work too.

**Comment by keelung-yang** [comment]
@koobest Please check following snapshots, sdkconfig and uart_echo_example_main.c:

![image](https://user-images.githubusercontent.com/20385450/49420773-0d180d00-f7c8-11e8-9a14-455428bc7e16.png)

![image](https://user-images.githubusercontent.com/20385450/49420922-a6472380-f7c8-11e8-83b2-e8acbe6945ab.png)

![image](https://user-images.githubusercontent.com/20385450/49421123-9845d280-f7c9-11e8-861b-19a3e072cf97.png)


[uart_echo_example_main.zip](https://github.com/espressif/esp-idf/files/2642551/uart_echo_example_main.zip)
[sdkconfig.zip](https://github.com/espressif/esp-idf/files/2642553/sdkconfig.zip)

**Comment by koobest** [comment]
@keelung-yang 
When calling `uart_set_pin`, the pin number of UART0 should be specified to put the GPIO in the correct mode. e.g.
```
uart_set_pin(UART_PORT, 1, 3, UART_PIN_NO_CHANGE, UART_PIN_NO_CHANGE);
```
Otherwise you will not be able to accept or send data.  
When UART0 is set to console output, we have already configured  the gpio to the correct mode.

**Comment by keelung-yang** [comment]
@koobest It's works now! Thank you very very much!
