### ISSUE TITLE
[TW#27712] Can't store values after nvs_flash_erase()

### ISSUE THREAD

**Issue by BrianPugh** [espressif/esp-idf#2777]
## Environment

- Development Kit:      ESP32-Wrover-Kit
- Kit version (for WroverKit/PicoKit/DevKitC): [v1|v2|v3|v4]
- Module or chip used:  ESP32-WROOM-32
- IDF version (run ``git describe --tags`` to find it): 
    // v3.2-dev-1148-g96cd3b75c
- Build System:         [Make|]
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it): 1.22.0-80-g6c4433a
- Operating System:     macOS]
- Power Supply:         USB

## Problem Description

After running `nvs_flash_erase()`, I am unable to store key/value pairs (namely blobs) until I restart. Weirdly, all writing functions return "successful". Removing `nvs_flash_erase()` allows for proper rights. In my application i'm trying to perform a "factory reset" and then write in a special values.

**Comment by igrr** [comment]
Could you please share the code snippet which illustrates the issue? Particularly interesting is the sequence in which sequence you call nvs_flash_erase, nvs_flash_init, nvs_open, nvs_write, nvs_commit.

**Comment by igrr** [comment]
Oh, I see now, thanks for the example. Documentation does not mention that `nvs_flash_erase` can only be used when NVS is not initialized, i.e. before `nvs_flash_init` or after `nvs_flash_deinit`. Will update the docs and add corresponding error check.

**Comment by alyf80** [comment]
Just a friendly reminder: there is still no mention of this in either the documentation or the API reference.

Also, in the current IDF 4.0 (haven't checked with 4.1) calling `nvs_flash_erase()` on an initialized partition still returns `ESP_OK` while managing to break things in non-obvious ways.

In my specific case, after calling `nvs_flash_erase()` followed by `nvs_flash_init()` I would be able to write `u8`'s _and read them back successfully_ , with corruption only becoming apparent after the first reboot.
