### ISSUE TITLE
PROJECT_PATH name can be changed to ESP_PROJECT_PATH ?  (IDFGH-488)

### ISSUE THREAD

**Issue by muratsplat** [espressif/esp-idf#2785]
Hello everyone

I am working on automation for building firmware and  when I was investigating a critical bug,  I realized ESP-IDF sdk uses `PROJECT_PATH` as shell environment variable. 

`PROJECT_PATH` is general name used many CI TOOL.
Gitlab-ci tool is ovewrite the variable. That causes Makefile doesn't work  like this:

```sh
firmware is building...
$ make clean
make[1]: Entering directory '/esp/esp-idf/tools/kconfig'
cc -c  -DCURSES_LOC="<ncurses.h>" -DLOCALE -MMD  /esp/esp-idf/tools/kconfig/mconf.c -o mconf.o
flex -L -P zconf -o zconf.lex.c /esp/esp-idf/tools/kconfig/zconf.l
bison -t -l -p zconf -o zconf.tab.c /esp/esp-idf/tools/kconfig/zconf.y
sed -E "s/\\x0D$//" /esp/esp-idf/tools/kconfig/zconf.gperf | gperf -t --output-file zconf.hash.c -a -C -E -g -k '1,3,$' -p -t
cc -I /esp/esp-idf/tools/kconfig -c  -DCURSES_LOC="<ncurses.h>" -DLOCALE -MMD  zconf.tab.c -o zconf.tab.o
/esp/esp-idf/tools/kconfig/lxdialog/check-lxdialog.sh -check cc  -DCURSES_LOC="<ncurses.h>" -DLOCALE -MMD -lncurses
cc -c  -DCURSES_LOC="<ncurses.h>" -DLOCALE -MMD  /esp/esp-idf/tools/kconfig/lxdialog/checklist.c -o lxdialog/checklist.o
cc -c  -DCURSES_LOC="<ncurses.h>" -DLOCALE -MMD  /esp/esp-idf/tools/kconfig/lxdialog/util.c -o lxdialog/util.o
cc -c  -DCURSES_LOC="<ncurses.h>" -DLOCALE -MMD  /esp/esp-idf/tools/kconfig/lxdialog/inputbox.c -o lxdialog/inputbox.o
cc -c  -DCURSES_LOC="<ncurses.h>" -DLOCALE -MMD  /esp/esp-idf/tools/kconfig/lxdialog/textbox.c -o lxdialog/textbox.o
cc -c  -DCURSES_LOC="<ncurses.h>" -DLOCALE -MMD  /esp/esp-idf/tools/kconfig/lxdialog/yesno.c -o lxdialog/yesno.o
cc -c  -DCURSES_LOC="<ncurses.h>" -DLOCALE -MMD  /esp/esp-idf/tools/kconfig/lxdialog/menubox.c -o lxdialog/menubox.o
cc -o mconf-idf mconf.o zconf.tab.o lxdialog/checklist.o lxdialog/util.o lxdialog/inputbox.o lxdialog/textbox.o lxdialog/yesno.o lxdialog/menubox.o -lncurses
cc -c  -DCURSES_LOC="<ncurses.h>" -DLOCALE -MMD  /esp/esp-idf/tools/kconfig/conf.c -o conf.o
cc -o conf-idf conf.o  zconf.tab.o -lncurses
make[1]: Leaving directory '/esp/esp-idf/tools/kconfig'
DEFCONFIG

*** Error during writing of the configuration.

make: *** No rule to make target 'defconfig', needed by 'src/gitlab.com/ideafield/bonair/esp-32-wifi-and-ibeacon/sdkconfig'.  Stop.
```
This conflict makes I have lost a day  🤪

There is simple recommendation for resolve this problem. 

Remove `PROJECT_PATH`variable in gitlab-ci

```sh
unset PROJECT_PATH

make clean
make app
...
```

**Comment by KonstantinKondrashov** [comment]
Hi @muratsplat. Thank you for the report. We have prepared the MR to solve this problem. We will cut this variable (PROJECT_PATH also PROJECT_NAME) to the required length of 32 characters.

**Comment by KonstantinKondrashov** [comment]
Sorry, I was wrong with the branch. My changes touch PROJECT_NAME and PROJECT_VER. (not PROJECT_PATH)

**Comment by igrr** [comment]
@muratsplat It seems that Gitlab CI defines `CI_PROJECT_PATH`, not `PROJECT_PATH` (https://docs.gitlab.com/ee/ci/variables/predefined_variables.html). Are you sure that PROJECT_PATH is not defined somewhere in your .gitlab-ci.yml?

For compatibility reasons, we will not be able to rename this variable for the Make build system. In the new CMake build system, environment variables do not override build system variables, so the issue should not happen anymore.

**Comment by muratsplat** [comment]
@igrr  You are right. `PROJECT_PATH` is not used by Gitlab CI. There is a conflict on my CI code perhaps. Sorry for misinformation..
