### ISSUE TITLE
xtensa-esp32-elf-linux32-1.22.0-61-gab8375a-5.2.0.tar.gz not found on espressif dl server

### ISSUE THREAD

**Issue by bvernoux** [espressif/esp-idf#279]
I'm using latest information to install the latest esp32 toolchain (GCC 5.2) on Ubuntu 32bits from
http://esp-idf.readthedocs.io/en/latest/linux-setup.html#step-1-download-binary-toolchain-for-the-esp32
for 32-bit Linux:
https://dl.espressif.com/dl/xtensa-esp32-elf-linux32-1.22.0-61-gab8375a-5.2.0.tar.gz
Problem is this link returns "404 Not Found"

For information doing it with http://esp-idf.readthedocs.io/en/latest/linux-setup.html#alternative-step-1-compile-the-toolchain-from-source-using-crosstool-ng works perfectly

**Comment by projectgus** [comment]
The 32-bit toolchain download link has been fixed. Sorry for the inconvenience.

**Comment by btukacs** [comment]
Hi, i am following setup process for 3.3: https://docs.espressif.com/projects/esp-idf/en/release-v3.3/get-started/macos-setup.html
https://dl.espressif.com/dl/xtensa-esp32-elf-osx-1.22.0-96-g2852398-5.2.0.tar.gz
gives me also 404. Please repair it asap.

**Comment by Alvin1Zhang** [comment]
@btukacs Thanks for reporting, we will check.
