### ISSUE TITLE
[TW#27760] /bin/sh unexpected operator

### ISSUE THREAD

**Issue by mreutman** [espressif/esp-idf#2791]
## Environment

- Development Kit: none
- Module or chip used: ESP32-WROOM-32
- IDF version (run ``git describe --tags`` to find it): v3.3-dev-343-g7fa98593b
- Build System: Make
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it): xtensa-esp32-elf-gcc (crosstool-NG crosstool-ng-1.22.0-80-g6c4433a) 5.2.0
- Operating System: Linux - Ubuntu 18.04.1 LTS
- Power Supply: USB

## Problem Description

I'm seeing an `/bin/sh: 1: [: !=: unexpected operator` error come up when running `make` and `make flash`. I've tried to figure out where in the build system the error is occurring, but haven't had much luck. Everything seems to build and flash just fine, but that doesn't grantee that it's not skipping something important. Example output included below.

### Expected Behavior

No errors during execution of `make` and `make flash`.

### Actual Behavior

Observation of `/bin/sh: 1: [: !=: unexpected operator` when running `make` and `make flash`.

### Steps to repropduce

1. Clone esp-idf.
2. Build a project that utilizes esp-idf (I used hello_world).
3. Observe error message.

## Debug Logs
```
$ make flash 
Toolchain path: /opt/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc
Toolchain version: crosstool-ng-1.22.0-80-g6c4433a
Compiler version: 5.2.0
Python requirements from /home/mreutman/Development/esp-idf/requirements.txt are satisfied.
/bin/sh: 1: [: !=: unexpected operator
/bin/sh: 1: [: !=: unexpected operator
Flashing binaries to serial port /dev/ttyUSB0 (app at offset 0x10000)...
esptool.py v2.6-beta1
Serial port /dev/ttyUSB0
Connecting....
Chip is ESP32D0WDQ6 (revision 1)
Features: WiFi, BT, Dual Core, Coding Scheme None
MAC: 30:ae:a4:86:c8:a4
Uploading stub...
Running stub...
Stub running...
Configuring flash size...
Auto-detected Flash size: 4MB
Flash params set to 0x0220
Compressed 23024 bytes to 13653...
Wrote 23024 bytes (13653 compressed) at 0x00001000 in 1.2 seconds (effective 152.9 kbit/s)...
Hash of data verified.
Compressed 151376 bytes to 73622...
Wrote 151376 bytes (73622 compressed) at 0x00010000 in 6.5 seconds (effective 186.1 kbit/s)...
Hash of data verified.
Compressed 3072 bytes to 103...
Wrote 3072 bytes (103 compressed) at 0x00008000 in 0.0 seconds (effective 1631.1 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting via RTS pin...
```

**Comment by projectgus** [comment]
Hi @mreutman ,

Thanks for reporting this. We've just merged a fix for this (deaecf164d8da2a8ebf8718f3ab167b597ded480), the commit should be available on GitHub shortly.

Angus

**Comment by mreutman** [comment]
@projectgus, excellent! Thanks for the quick response.

**Comment by projectgus** [comment]
This commit has now been pushed to Github (linked above), closing the issue.
