### ISSUE TITLE
[TW#27786] OSX Blink example fails to Make Menuconfig-All-Flash

### ISSUE THREAD

**Issue by rsnbusa** [espressif/esp-idf#2795]
Wanted to update the esp-idf to the newest version v3.3-dev-386-gf1b4c18c2 (master).
OSX High Sierra 10.13.6
 git clone --recursive https://github.com/espressif/esp-idf.git
All ok.

cd /Users/rsn/esp/esp-idf/examples/get-started/blink 
make menuconfig

a lot of errors and most importantly an Illegal Instruction:4 (not for osx apparently).

Dump below

rsnDesktop:blink rsn$ make menuconfig
cc -c  -DCURSES_LOC="<ncurses.h>" -DKBUILD_NO_NLS -Wno-format-security  -DLOCALE -MMD  /Users/rsn/esp/esp-idf/tools/kconfig/mconf.c -o mconf.o
flex -L -P zconf -o zconf.lex.c /Users/rsn/esp/esp-idf/tools/kconfig/zconf.l
bison -t -l -p zconf -o zconf.tab.c /Users/rsn/esp/esp-idf/tools/kconfig/zconf.y
sed -E "s/\\x0D$//" /Users/rsn/esp/esp-idf/tools/kconfig/zconf.gperf | gperf -t --output-file zconf.hash.c -a -C -E -g -k '1,3,$' -p -t
cc -I /Users/rsn/esp/esp-idf/tools/kconfig -c  -DCURSES_LOC="<ncurses.h>" -DKBUILD_NO_NLS -Wno-format-security  -DLOCALE -MMD  zconf.tab.c -o zconf.tab.o
/Users/rsn/esp/esp-idf/tools/kconfig/lxdialog/check-lxdialog.sh: line 14: 74220 Broken pipe: 13         $cc -print-file-name=lib${lib}.${ext} $extra_libs
     74221 Illegal instruction: 4  | grep -q /
/Users/rsn/esp/esp-idf/tools/kconfig/lxdialog/check-lxdialog.sh: line 14: 74222 Broken pipe: 13         $cc -print-file-name=lib${lib}.${ext} $extra_libs
     74223 Illegal instruction: 4  | grep -q /
/Users/rsn/esp/esp-idf/tools/kconfig/lxdialog/check-lxdialog.sh: line 14: 74224 Broken pipe: 13         $cc -print-file-name=lib${lib}.${ext} $extra_libs
     74225 Illegal instruction: 4  | grep -q /
/Users/rsn/esp/esp-idf/tools/kconfig/lxdialog/check-lxdialog.sh: line 14: 74226 Broken pipe: 13         $cc -print-file-name=lib${lib}.${ext} $extra_libs
     74227 Illegal instruction: 4  | grep -q /
/Users/rsn/esp/esp-idf/tools/kconfig/lxdialog/check-lxdialog.sh: line 14: 74228 Broken pipe: 13         $cc -print-file-name=lib${lib}.${ext} $extra_libs
     74229 Illegal instruction: 4  | grep -q /
/Users/rsn/esp/esp-idf/tools/kconfig/lxdialog/check-lxdialog.sh: line 14: 74230 Broken pipe: 13         $cc -print-file-name=lib${lib}.${ext} $extra_libs
     74231 Illegal instruction: 4  | grep -q /
/Users/rsn/esp/esp-idf/tools/kconfig/lxdialog/check-lxdialog.sh: line 14: 74232 Broken pipe: 13         $cc -print-file-name=lib${lib}.${ext} $extra_libs
     74233 Illegal instruction: 4  | grep -q /
/Users/rsn/esp/esp-idf/tools/kconfig/lxdialog/check-lxdialog.sh: line 14: 74234 Broken pipe: 13         $cc -print-file-name=lib${lib}.${ext} $extra_libs
     74235 Illegal instruction: 4  | grep -q /
/Users/rsn/esp/esp-idf/tools/kconfig/lxdialog/check-lxdialog.sh: line 14: 74236 Broken pipe: 13         $cc -print-file-name=lib${lib}.${ext} $extra_libs
     74237 Illegal instruction: 4  | grep -q /
/Users/rsn/esp/esp-idf/tools/kconfig/lxdialog/check-lxdialog.sh: line 14: 74238 Broken pipe: 13         $cc -print-file-name=lib${lib}.${ext} $extra_libs
     74239 Illegal instruction: 4  | grep -q /
/Users/rsn/esp/esp-idf/tools/kconfig/lxdialog/check-lxdialog.sh: line 14: 74240 Broken pipe: 13         $cc -print-file-name=lib${lib}.${ext} $extra_libs
     74241 Illegal instruction: 4  | grep -q /
/Users/rsn/esp/esp-idf/tools/kconfig/lxdialog/check-lxdialog.sh: line 14: 74242 Broken pipe: 13         $cc -print-file-name=lib${lib}.${ext} $extra_libs
     74243 Illegal instruction: 4  | grep -q /
/Users/rsn/esp/esp-idf/tools/kconfig/lxdialog/check-lxdialog.sh -check cc  -DCURSES_LOC="<ncurses.h>" -DKBUILD_NO_NLS -Wno-format-security  -DLOCALE -MMD -lncurses 
cc -c  -DCURSES_LOC="<ncurses.h>" -DKBUILD_NO_NLS -Wno-format-security  -DLOCALE -MMD  /Users/rsn/esp/esp-idf/tools/kconfig/lxdialog/checklist.c -o lxdialog/checklist.o
cc -c  -DCURSES_LOC="<ncurses.h>" -DKBUILD_NO_NLS -Wno-format-security  -DLOCALE -MMD  /Users/rsn/esp/esp-idf/tools/kconfig/lxdialog/util.c -o lxdialog/util.o
cc -c  -DCURSES_LOC="<ncurses.h>" -DKBUILD_NO_NLS -Wno-format-security  -DLOCALE -MMD  /Users/rsn/esp/esp-idf/tools/kconfig/lxdialog/inputbox.c -o lxdialog/inputbox.o
cc -c  -DCURSES_LOC="<ncurses.h>" -DKBUILD_NO_NLS -Wno-format-security  -DLOCALE -MMD  /Users/rsn/esp/esp-idf/tools/kconfig/lxdialog/textbox.c -o lxdialog/textbox.o
cc -c  -DCURSES_LOC="<ncurses.h>" -DKBUILD_NO_NLS -Wno-format-security  -DLOCALE -MMD  /Users/rsn/esp/esp-idf/tools/kconfig/lxdialog/yesno.c -o lxdialog/yesno.o
cc -c  -DCURSES_LOC="<ncurses.h>" -DKBUILD_NO_NLS -Wno-format-security  -DLOCALE -MMD  /Users/rsn/esp/esp-idf/tools/kconfig/lxdialog/menubox.c -o lxdialog/menubox.o
/Users/rsn/esp/esp-idf/tools/kconfig/lxdialog/check-lxdialog.sh: line 14: 74266 Broken pipe: 13         $cc -print-file-name=lib${lib}.${ext} $extra_libs
     74267 Illegal instruction: 4  | grep -q /
/Users/rsn/esp/esp-idf/tools/kconfig/lxdialog/check-lxdialog.sh: line 14: 74268 Broken pipe: 13         $cc -print-file-name=lib${lib}.${ext} $extra_libs
     74269 Illegal instruction: 4  | grep -q /
/Users/rsn/esp/esp-idf/tools/kconfig/lxdialog/check-lxdialog.sh: line 14: 74270 Broken pipe: 13         $cc -print-file-name=lib${lib}.${ext} $extra_libs
     74271 Illegal instruction: 4  | grep -q /
/Users/rsn/esp/esp-idf/tools/kconfig/lxdialog/check-lxdialog.sh: line 14: 74272 Broken pipe: 13         $cc -print-file-name=lib${lib}.${ext} $extra_libs
     74273 Illegal instruction: 4  | grep -q /
/Users/rsn/esp/esp-idf/tools/kconfig/lxdialog/check-lxdialog.sh: line 14: 74274 Broken pipe: 13         $cc -print-file-name=lib${lib}.${ext} $extra_libs
     74275 Illegal instruction: 4  | grep -q /
/Users/rsn/esp/esp-idf/tools/kconfig/lxdialog/check-lxdialog.sh: line 14: 74276 Broken pipe: 13         $cc -print-file-name=lib${lib}.${ext} $extra_libs
     74277 Illegal instruction: 4  | grep -q /
/Users/rsn/esp/esp-idf/tools/kconfig/lxdialog/check-lxdialog.sh: line 14: 74278 Broken pipe: 13         $cc -print-file-name=lib${lib}.${ext} $extra_libs
     74279 Illegal instruction: 4  | grep -q /
/Users/rsn/esp/esp-idf/tools/kconfig/lxdialog/check-lxdialog.sh: line 14: 74280 Broken pipe: 13         $cc -print-file-name=lib${lib}.${ext} $extra_libs
     74281 Illegal instruction: 4  | grep -q /
/Users/rsn/esp/esp-idf/tools/kconfig/lxdialog/check-lxdialog.sh: line 14: 74282 Broken pipe: 13         $cc -print-file-name=lib${lib}.${ext} $extra_libs
     74283 Illegal instruction: 4  | grep -q /
/Users/rsn/esp/esp-idf/tools/kconfig/lxdialog/check-lxdialog.sh: line 14: 74284 Broken pipe: 13         $cc -print-file-name=lib${lib}.${ext} $extra_libs
     74285 Illegal instruction: 4  | grep -q /
/Users/rsn/esp/esp-idf/tools/kconfig/lxdialog/check-lxdialog.sh: line 14: 74286 Broken pipe: 13         $cc -print-file-name=lib${lib}.${ext} $extra_libs
     74287 Illegal instruction: 4  | grep -q /
/Users/rsn/esp/esp-idf/tools/kconfig/lxdialog/check-lxdialog.sh: line 14: 74288 Broken pipe: 13         $cc -print-file-name=lib${lib}.${ext} $extra_libs
     74289 Illegal instruction: 4  | grep -q /
cc -o mconf-idf mconf.o zconf.tab.o lxdialog/checklist.o lxdialog/util.o lxdialog/inputbox.o lxdialog/textbox.o lxdialog/yesno.o lxdialog/menubox.o -lncurses 
cc -c  -DCURSES_LOC="<ncurses.h>" -DKBUILD_NO_NLS -Wno-format-security  -DLOCALE -MMD  /Users/rsn/esp/esp-idf/tools/kconfig/conf.c -o conf.o
/Users/rsn/esp/esp-idf/tools/kconfig/lxdialog/check-lxdialog.sh: line 14: 74300 Broken pipe: 13         $cc -print-file-name=lib${lib}.${ext} $extra_libs
     74301 Illegal instruction: 4  | grep -q /
/Users/rsn/esp/esp-idf/tools/kconfig/lxdialog/check-lxdialog.sh: line 14: 74302 Broken pipe: 13         $cc -print-file-name=lib${lib}.${ext} $extra_libs
     74303 Illegal instruction: 4  | grep -q /
/Users/rsn/esp/esp-idf/tools/kconfig/lxdialog/check-lxdialog.sh: line 14: 74304 Broken pipe: 13         $cc -print-file-name=lib${lib}.${ext} $extra_libs
     74305 Illegal instruction: 4  | grep -q /
/Users/rsn/esp/esp-idf/tools/kconfig/lxdialog/check-lxdialog.sh: line 14: 74306 Broken pipe: 13         $cc -print-file-name=lib${lib}.${ext} $extra_libs
     74307 Illegal instruction: 4  | grep -q /
/Users/rsn/esp/esp-idf/tools/kconfig/lxdialog/check-lxdialog.sh: line 14: 74308 Broken pipe: 13         $cc -print-file-name=lib${lib}.${ext} $extra_libs
     74309 Illegal instruction: 4  | grep -q /
/Users/rsn/esp/esp-idf/tools/kconfig/lxdialog/check-lxdialog.sh: line 14: 74310 Broken pipe: 13         $cc -print-file-name=lib${lib}.${ext} $extra_libs
     74311 Illegal instruction: 4  | grep -q /
/Users/rsn/esp/esp-idf/tools/kconfig/lxdialog/check-lxdialog.sh: line 14: 74312 Broken pipe: 13         $cc -print-file-name=lib${lib}.${ext} $extra_libs
     74313 Illegal instruction: 4  | grep -q /
/Users/rsn/esp/esp-idf/tools/kconfig/lxdialog/check-lxdialog.sh: line 14: 74314 Broken pipe: 13         $cc -print-file-name=lib${lib}.${ext} $extra_libs
     74315 Illegal instruction: 4  | grep -q /
/Users/rsn/esp/esp-idf/tools/kconfig/lxdialog/check-lxdialog.sh: line 14: 74316 Broken pipe: 13         $cc -print-file-name=lib${lib}.${ext} $extra_libs
     74317 Illegal instruction: 4  | grep -q /
/Users/rsn/esp/esp-idf/tools/kconfig/lxdialog/check-lxdialog.sh: line 14: 74318 Broken pipe: 13         $cc -print-file-name=lib${lib}.${ext} $extra_libs
     74319 Illegal instruction: 4  | grep -q /
/Users/rsn/esp/esp-idf/tools/kconfig/lxdialog/check-lxdialog.sh: line 14: 74320 Broken pipe: 13         $cc -print-file-name=lib${lib}.${ext} $extra_libs
     74321 Illegal instruction: 4  | grep -q /
/Users/rsn/esp/esp-idf/tools/kconfig/lxdialog/check-lxdialog.sh: line 14: 74322 Broken pipe: 13         $cc -print-file-name=lib${lib}.${ext} $extra_libs
     74323 Illegal instruction: 4  | grep -q /
cc -o conf-idf conf.o  zconf.tab.o -lncurses 
DEFCONFIG
#
# configuration written to /Users/rsn/esp/esp-idf/examples/get-started/blink/sdkconfig
#
MENUCONFIG

*** End of the configuration.
*** Execute 'make' to start the build or try 'make help'.

GENCONFIG
App "blink" version: v3.3-dev-386-gf1b4c18c2

The menu eventually shows up, I set the serial interface and speed and try a make all to see what comes up

rsnDesktop:blink rsn$ make all
Toolchain path: /users/rsn/esp/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc
WARNING: Toolchain version is not supported: crosstool-ng-1.22.0-61-gab8375a
Expected to see version: crosstool-ng-1.22.0-80-g6c4433a
Please check ESP-IDF setup instructions and update the toolchain, or proceed at your own risk.
Compiler version: 5.2.0
The following Python requirements are not satisfied:
cryptography>=2.1.4
Please refer to the Get Started section of the ESP-IDF Programming Guide for setting up the required packages. Alternatively, you can run "/usr/bin/python -m pip install --user -r /Users/rsn/esp/esp-idf/requirements.txt" for resolving the issue.
make: *** [check_python_dependencies] Error 1

I had already done the suggested command, but tried again and get

rsnDesktop:blink rsn$ /usr/bin/python -m pip install --user -r /Users/rsn/esp/esp-idf/requirements.txt
You are using pip version 6.1.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Requirement already satisfied (use --upgrade to upgrade): setuptools in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from -r /Users/rsn/esp/esp-idf/requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): pyserial>=3.0 in /Library/Python/2.7/site-packages/pyserial-3.4-py2.7.egg (from -r /Users/rsn/esp/esp-idf/requirements.txt (line 8))
Requirement already satisfied (use --upgrade to upgrade): future>=0.15.2 in /Users/rsn/Library/Python/2.7/lib/python/site-packages (from -r /Users/rsn/esp/esp-idf/requirements.txt (line 9))
Requirement already satisfied (use --upgrade to upgrade): cryptography>=2.1.4 in /Users/rsn/Library/Python/2.7/lib/python/site-packages (from -r /Users/rsn/esp/esp-idf/requirements.txt (line 10))
Requirement already satisfied (use --upgrade to upgrade): pyparsing>=2.0.3 in /Users/rsn/Library/Python/2.7/lib/python/site-packages (from -r /Users/rsn/esp/esp-idf/requirements.txt (line 11))
Requirement already satisfied (use --upgrade to upgrade): idna>=2.1 in /Users/rsn/Library/Python/2.7/lib/python/site-packages (from cryptography>=2.1.4->-r /Users/rsn/esp/esp-idf/requirements.txt (line 10))
Requirement already satisfied (use --upgrade to upgrade): asn1crypto>=0.21.0 in /Users/rsn/Library/Python/2.7/lib/python/site-packages (from cryptography>=2.1.4->-r /Users/rsn/esp/esp-idf/requirements.txt (line 10))
Requirement already satisfied (use --upgrade to upgrade): six>=1.4.1 in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from cryptography>=2.1.4->-r /Users/rsn/esp/esp-idf/requirements.txt (line 10))
Requirement already satisfied (use --upgrade to upgrade): cffi!=1.11.3,>=1.7 in /Users/rsn/Library/Python/2.7/lib/python/site-packages (from cryptography>=2.1.4->-r /Users/rsn/esp/esp-idf/requirements.txt (line 10))
Requirement already satisfied (use --upgrade to upgrade): pycparser in /Users/rsn/Library/Python/2.7/lib/python/site-packages (from cffi!=1.11.3,>=1.7->cryptography>=2.1.4->-r /Users/rsn/esp/esp-idf/requirements.txt (line 10))

SO, what to do?

I returned to the working version of esp-idf (which I VERY wisely saved before committing to a new version which I should have trusted but I would have been screwed!!!! for trusting).

Old version works fine.

Any instructions or this is it for OSX?

**Comment by igrr** [comment]
Hi @rsnbusa, it seems that there are two issues here:

1. tools/kconfig/lxdialog/check-lxdialog.sh is trying to run C compiler on your system, and that fails with "Illegal instruction 4" error
2. Cryptography package seems to be installed, but the build system complains that it isn't.

For the first issue, could you please do two things:

- modify $IDF_PATH/tools/kconfig/Makefile, add `$(info "Kconfig: CC=$(CC)")` line somewhere around line 214 (before the `# Check that we have the required ncurses stuff installed for lxdialog (menuconfig)` comment)
- run `cd $IDF_PATH/tools/kconfig`, then `make clean`, then `make`
- at the top of `make` output, there will be a line `Kconfig: CC=cc` (it might be something other than `cc`)
- run `which cc`, `file $(which cc)`, `cc --version` — replace `cc` with whatever was reported by make in the previous step.
- post the output from the steps above

For the second issue:

- Please try running `which python`, `python --version`, `python -c "import sys; print(sys.path)"`, and post the output you get.

**Comment by projectgus** [comment]
Closing due to a lack of updates.
