### ISSUE TITLE
How to create multiple characteristic on same service(for Bluetooth  GATT server)

### ISSUE THREAD

**Issue by YanMinge** [espressif/esp-idf#280]
I try to add characteristic with "esp_ble_gatts_add_char". but only the first characteristic can be searched.

**Comment by negativekelvin** [comment]
Have you looked to gatt_server_service_table example?

**Comment by divinebird** [comment]
When you use esp_ble_gatts_create_service there is last argument where you set handles count for this service. In example it is 4. I found that for every characteristic use 2 handles as service and descriptor use 1 handler. So if you like to add characteristic you should init service with 6 or more handle number.

**Comment by YanMinge** [comment]
Thanks，it can work now

**Comment by sowmimalu** [comment]
Can you please guide me on gatt  client ??

**Comment by chegewara** [comment]
https://github.com/espressif/esp-idf/blob/master/examples/bluetooth/bluedroid/ble/gatt_client/tutorial/Gatt_Client_Example_Walkthrough.md#getting-characteristics
