### ISSUE TITLE
[TW#27805] Stopping monitor on Mac OS

### ISSUE THREAD

**Issue by ItsRom** [espressif/esp-idf#2800]
## Actions already completed

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [x] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [x] I have searched the issue tracker for a similar issue and not found a similar issue.

## Environment

- IDF version : v3.3-dev-396-g8c7a6be62
- Build System: Make
- Compiler version : xtensa-esp32-elf-gcc (crosstool-NG crosstool-ng-1.22.0-80-g6c4433a) 5.2.0
- Operating System: Mac OS
- Power Supply:  USB

## Problem Description

When a do make monitor to see the hello word flashed on my ESP32, it's worked but the programe restart in infinite loop and I must do Ctrl + ] to stop it but I'm on Mac and Ctrl + ] doesn't worked.
I use Shift + Alt + ) for ] so Ctrl + Shift + Alt + ) but it's doesn't worked. 
I tried Ctrl + C or Cmd + C and lot of others tricks but doesn't work too.

I have this screen in loop.
<img width="780" alt="capture d ecran 2018-12-06 a 17 31 31" src="https://user-images.githubusercontent.com/45665475/49597476-cf101a00-f97c-11e8-956d-e7e09a8c59b5.png">

How can I quit the monitor properly?
Thanks for your help.

Romain.

**Comment by igrr** [comment]
Hi @ItsRom, which terminal application are you using, the default Terminal.app or something else?

**Comment by Nathaniel7687** [comment]
> Hi @ItsRom, which terminal application are you using, the default Terminal.app or something else?

I'm suffering the same problem.
The problem has occurred in "screen" and "make monitor".
The serial communication just stuck while displaying ESP_LOGs and even booting.
So I have to re-connect the serial communication with screen command such as
"screen /dev/cu.SLAB_USBtoUART 115200" to monitor continuously without reboot the ESP32.
Unfortunately, the screen application also doesn't last very long.

**Comment by Nathaniel7687** [comment]
> Hi @ItsRom, which terminal application are you using, the default Terminal.app or something else?

I'm suffering similarly a problem.
The problem has occurred in "screen" and "make monitor".
The serial communication just stuck while displaying ESP_LOGs and even booting (I don't know what about printf).

So I have to re-connect the serial communication with screen command such as
"screen /dev/cu.SLAB_USBtoUART 115200" to monitor continuously without reboot the ESP32.
Unfortunately, the screen application also doesn't last very long.

**Comment by X-Ryl669** [comment]
For me it's `Ctrl + $`(the key that's just on the left of return key, top row)

**Comment by lvx3** [comment]
`Ctrl+]` works for me in iterm2

**Comment by ItsRom** [comment]
Thanks @X-Ryl669 : on Terminal.app Ctrl + $ works too!

**Comment by GilDev** [comment]
Was having the same issue, I type in [Bépo](http://bepo.fr).
For anyone interested, `Ctrl + T` `Ctrl + X` works for me.

**Comment by georgik** [comment]
CTRL+] works for iTerm and Terminal on Big Sur. Thanks @lvturner 
@igrr  Is there a reason why CTRL+C is not accepted?

**Comment by dobairoland** [comment]
@georgik I'm not sure which version are you using but CTRL+C should interrupt the application and invoke GDB Stub.

**Comment by georgik** [comment]
@dobairoland Some additional info:
`idf.py --version`
`ESP-IDF v4.4-dev-1404` - master https://github.com/espressif/esp-idf

Observed behavior on OSes: 
- Linux and macOS is the same. CTRL+C is not accepted
- Windows throws Python exception `KeyboardInterrupt` and terminates

**Comment by sverrisson** [comment]
Note I had the same issue as I am NOT using a USA keyboard.  
I saw the comment above pressing the key next to return at top, so I did press that key on my keyboard. For me this key is '  and it will be different on other international keyboards. 
Please pick a better key for stopping the monitor, that works on other than US keyboards.

**Comment by gavalierm** [comment]
CTRL + T, then X

**Comment by jonasbeltoft** [comment]
Danish keyboards: CTRL + OPTION + Å
