### ISSUE TITLE
[TW#27812] cmake build fail after renaming main folder

### ISSUE THREAD

**Issue by cnshibo** [espressif/esp-idf#2801]
1. rename main dir name to src
2. set(MAIN_SRCS ${${CMAKE_SOURCE_DIR}}/src)
3. idf.py build

output:
esp32/libesp32.a(cpu_start.c.obj):(.literal.main_task+0x18): undefined reference to `app_main'
esp32/libesp32.a(cpu_start.c.obj): In function `main_task':..................................

==============================================================
how to solve this problem if we want to put app_main other than in default main folder?

**Comment by renzbagaporo** [comment]
Hi @cnshibo `MAIN_SRCS` specify source file, not directories. Even then we've actually deprecated the use of `MAIN_SRCS` (there should be a warning during build that indicates this). `main` is now a treated as a component again, just like in `Make`. 

The recommended way to go about this is as follows:

1. Rename `main` to your desired name (let's say `src` as per your example)
2. Add the directory to `EXTRA_COMPONENT_DIRS` in the top-level CMakeLists.txt
3. Modify `src/CMakeLists.txt` to include the necessary dependencies via `COMPONENT_REQUIRES` or `COMPONENT_PRIV_REQUIRES`.

**Comment by cnshibo** [comment]
solved, thx
