### ISSUE TITLE
[TW#27823] PROJECT_NAME is too long for array of chars

### ISSUE THREAD

**Issue by ammaree** [espressif/esp-idf#2803]
I have just upgraded to the latest IDF with the the application info added. PROJECT_NAME is a variable we have long used in our makefile. Since we already embed the build date/time and version into the binary we simply had to add a superfluous PROJECT_VER to the makefile to get the make working.

Up to now we have use the .ELF name to do selective FOTA upgrades by leveraging logic in our firmware to select 1 of 3 firmware options.
Option 1: To upgrade a single specific device look for a file called "x.bin" where x is the 12 hex digit mac address of the device.

Option 2: To upgrade a specific hardware specification we look for a file "y.bin" where y is the 36 digit device hardware specification token.

Option 3: To upgrade a single hardware specification for a specific customer to our cloud service we look for "y-z.bin" where z adds the 36 digit customer token, yielding a 36+1+36 character name.

Both options 2 and 3 result in a build error as below. Can we suggest that the size of PROJECT_NAME field be made configurable, or alternatively that the option to embed this info we removed, since we already have the values embedded in our binary.

Thanks

> <command-line>:0:14: warning: initializer-string for array of chars is too long
C:/Dropbox/devs/ws/z-sdk/esp-idf/components/app_update/esp_app_desc.c:23:21: note: in expansion of macro 'PROJECT_NAME'
     .project_name = PROJECT_NAME,
                     ^
<command-line>:0:14: note: (near initialization for 'esp_app_desc.project_name')
C:/Dropbox/devs/ws/z-sdk/esp-idf/components/app_update/esp_app_desc.c:23:21: note: in expansion of macro 'PROJECT_NAME'
     .project_name = PROJECT_NAME,
                     ^
C:/Dropbox/devs/ws/z-sdk/esp-idf/components/app_update/esp_app_desc.c:44:1: error: static assertion failed: "PROJECT_NAME is longer than project_name field in structure"
 _Static_assert(sizeof(PROJECT_NAME) <= sizeof(esp_app_desc.project_name), "PROJECT_NAME is longer than project_name field in structure");
 ^
make[1]: *** [/c/Dropbox/devs/ws/z-sdk/esp-idf/make/component_wrapper.mk:292: esp_app_desc.o] Error 1
make: *** [C:/Dropbox/devs/ws/z-sdk/esp-idf/make/project.mk:527: component-app_update-build] Error 2

**Comment by KonstantinKondrashov** [comment]
Hi @ammaree!
We have limits for fields `char project_name[32]` and `char version[32]`. 
You can create a `${PROJECT_PATH}/version.txt` file, PROJECT_VER  will get value from it. And do not override the PROJECT_VER variable.
Regarding to `PROJECT_NAME`... Perhaps we can make the length of these fields configurable. Tell your wishes to their size.

Thanks.

**Comment by KonstantinKondrashov** [comment]
Hi @ammaree. We have prepared the MR to solve this problem. We will cut this variable (PROJECT_PATH also PROJECT_NAME) to the required length of 32 characters. You can use these variables as before. 

Info about the added feature https://docs.espressif.com/projects/esp-idf/en/latest/api-guides/build-system.html#preset-component-variables 

Thanks.

**Comment by ammaree** [comment]
@KonstantinKondrashov 

PROJECT_PATH is not a problem for us, that is an unrelated issue #2785 

From what I saw the current length is 32, so cutting the variable to 32 characters does make any difference. We need 1 of 2 options:
a) Preferably make the whole structure optional, in which case we can exclude it; or
b) Change the size to 73 characters, or a variable length (say 32 to 128) characters

But 32 will remain a problem for us...

**Comment by ammaree** [comment]
Also, for PROJECT_VER the documentation does not seem correct. If all 3 the options fail to produce a value, the variable is empty build the build fails.

Surely the build should succed but the variable should be an empty string “” of maybe NULL?

**Comment by ammaree** [comment]
@KonstantinKondrashov 
Have just check the build without PROJECT_VER, it does succeed in building, just gives 2 "fatal" errors at the start when checking Git.

**Comment by KonstantinKondrashov** [comment]
Hi @ammaree.
We cannot make the `esp_app_desc_t` structure optional. Because it is involved in some other features that will be released soon. For us, an acceptable option is to trim up to 32 characters. This solves the problem with the compile error.

What does not suit you with trimming to 32 characters?

I can assume that you do not want the firmware image to change due to a change in the name of the project. Then I can offer an option in Konfig to exclude the project name from the firmware image. Let me know if you need this option. What is the reason for this?

To place user data you can create your own structures and declare it in the `rodata_custom_desc` section. Example: 
```
const __attribute __ ((section (". rodata_custom_desc"))) esp_app_desc_custom_t esp_app_desc_custom = {
    ...
};
```
This section immediately follows ours and has a fixed offset from the beginning of the image file and will be equal to offset = `sizeof (esp_image_header_t) + sizeof (esp_image_segment_header_t) + sizeof (esp_app_desc_t)`. You can use this memory space to store your data.

Thanks.

**Comment by hp027** [comment]
so easy, touch ~/version.txt in workspace

**Comment by ammaree** [comment]
@KonstantinKondrashov 

Our problem is that we use an external IOT platform. All objects in this platform is identified with a 36 character token. If we have to trim the name down it would completely destroy the firmware upgrade logic
For example the hardware specification token can be "02345678-1234-5678-abcd-0123456789AB"
In order to control the sequence/priority for firmware upgrades we name all firmware upgrades to be the same as either
a) the 12 character hex MAC address if intended for a specific device;
b) the 36 character specification token if intended for a specific hardware platform; or
c) an 86 character name that includes various components such as token (36) + Customer(24)+ Site(24) 

Items b and c are the problem, both being larger than 32 character.
Item b we have no control over so we need a minimum of 36 characters.
Item c we have some control over, might be able to bring it down to 72.

If the space can be made larger, as close to 72 as possible, we would be able to use the values in the ESP-IDF structure, if not we will simply have to fill it with dummy/empty values, duplicate the required info in our code, and manually rename the files generated after the make process

Alternatively we will have to find a way (hopefully again through the make file) to override the name of the output files generated by make.

**Comment by KonstantinKondrashov** [comment]
@ammaree. The PROJECT_NAME and PROJECT_VER variables in build system will remain unchanged, do not worry. Try to use this path and let me know if it is ok for you.
[3927_trimm_PROJECT_NAME_and_VER_for_inside_structure.zip](https://github.com/espressif/esp-idf/files/2679595/3927_trimm_PROJECT_NAME_and_VER_for_inside_structure.zip)

You can also disable the placement of the PROJECT_NAME and PROJECT_VER in `esp_app_desc_t` structure, to your image does not depends on them. And disable `CONFIG_APP_COMPILE_TIME_DATE` if you want to time/date stamp will be excluded from app image.

Thanks.

**Comment by ammaree** [comment]
@KonstantinKondrashov 

Since I have never used/applied patches before, just some questions before I invest the time to test this out...
.
Is this patch a temporary fix that will have to be reapplied to each new version of the build system?

Will this patch be incorporated into the build system in a future release?

How do I disable the placement of PROJECT_NAME/VER into the esp_app_desc_t structure?

**Comment by KonstantinKondrashov** [comment]
@ammaree 
There is already an MR in Gitlab now it is reviewed. We will merge it soon. (Perhaps the MR will differ from this patch, but only slightly.)

In the menu of Kconfig, you can find `Application manager` -> `Exclude PROJECT_VER/NAME from firmware image` and `Use time/date stamp for app` if it need.
