### ISSUE TITLE
how to use the long filename in sdcard?

### ISSUE THREAD

**Issue by ashareye** [espressif/esp-idf#2817]
Hi, All:

The filesystem of sdcard is fat32, it supports long filename such as "index.html". But when I stat or open the long name file, it returns wrong.  Can someone tell me how to use the long filename with mmc/sd library? thanks

**Comment by igrr** [comment]
You need to change the `CONFIG_FATFS_LONG_FILENAMES` (https://docs.espressif.com/projects/esp-idf/en/latest/api-reference/kconfig.html#config-fatfs-long-filenames) setting in menuconfig to enable long file names.

**Comment by suda-morris** [comment]
You might also modify the value of `CONFIG_FATFS_MAX_LFN` to make it more suitable for your application.

**Comment by ashareye** [comment]
it works, thank you, igrr and suda-mirris
