### ISSUE TITLE
fflush() does not work

### ISSUE THREAD

**Issue by ashesman** [espressif/esp-idf#2820]
As per [this](https://github.com/espressif/arduino-esp32/issues/1293) issue and [this](https://esp32.com/viewtopic.php?t=6960&p=30372) issue, fflush does not seem to work.  Data is not written to the file until fclose is called.

Using code as per the sd_card example project, if fflush(f) is called in place of fclose(f) then the sd card is removed, the file is never written.  In cases where a long term file is opened and data occasionally written to it, fflush is required to reduce the risk of data loss due to power failure.

`    // First create a file.
    ESP_LOGI(TAG, "Opening file");
    FILE* f = fopen("/sdcard/hello.txt", "w");
    if (f == NULL) {
        ESP_LOGE(TAG, "Failed to open file for writing");
        return;
    }
    fprintf(f, "Hello %s!\n", card->cid.name);
    //fclose(f);
    fflush(f);

    // Pull the card out here...
    while(1){vTaskDelay(1)};

    ESP_LOGI(TAG, "File written");
`

**Comment by ashesman** [comment]
It is unclear if fflush is causing the file contents to be written to the disk or not.  However, calling fsync after fflush causes the file to be written and be valid.

I am unsure if fflush is meant to cause the file metadata to be updated on disc but this is a suitable workaround:

    fflush(f);
    fsync(fileno(f));

**Comment by igrr** [comment]
fflush and fsync serve two different purposes:

fflush ensures that all buffers present in C library layer have been written to the filesystem layer. If you access the file using C library functions, such as fwrite or fprintf, then you may need to call fflush. If you use `write` instead then you don't need to call fflush.

`fsync` tells the filesystem layer to finish all pending writes to the physical disk. It needs to be called both when using C library functions (`fwrite`) and when not using them (`write`).

So your approach to call fflush and then fsync is correct.

**Comment by ashesman** [comment]
Thanks for clarifying that.  It was one of those things that after I worked it out I realised I shouldn't have raised it as an issue!
