### ISSUE TITLE
[TW#28007] compilition fail if PROJECT_VER exceeds 32 bytes

### ISSUE THREAD

**Issue by vwitti** [espressif/esp-idf#2826]
In current master the application version is read in esp-idf/components/app_update/component.mk, line 14 to: 
GET_PROJECT_VER := $(shell cd ${PROJECT_PATH} && git describe --always --tags --dirty || echo "Not found git repo")

compilation fails if GET_PROJECT_VER exceeds limit of 32 characters as defined in esp_image_format.h
If you truncate it to first 31 significant bytes compilations works
...
GET_PROJECT_VER := $(shell cd ${PROJECT_PATH} && git describe --always --tags --dirty || echo "Not found git repo")
# due to limit in esp_app_desc_t for element version[32]
GET_PROJECT_VER := $(shell echo ${GET_PROJECT_VER}|cut -c1-31)
...

We encountered this issue on some special tags. Or you increase version field to 48 bytes
best regards
volker

**Comment by projectgus** [comment]
Hi @vwitti ,

Thanks for reporting this. As it happens, a fix was just merged to master in our internal repo - 78487123bf80852f4ce11c788a3ee7f44b873833 . It should appear on GitHub in the next day or so.

Angus

**Comment by projectgus** [comment]
Hi @vwitti ,

Thanks for reporting this. A fix was just merged to master in our internal repo. It should appear on GitHub in the next day or so.

Angus

**Comment by vwitti** [comment]
Hi Angus,thank you very much .best regards and merry christmasvolkerAngus Gratton <notifications@github.com> hat am 21. Dezember 2018 um 00:47 geschrieben:  Hi @vwitti ,Thanks for reporting this. A fix was just merged to master in our internal repo. It should appear on GitHub in the next day or so.Angus—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by jimparis** [comment]
This can probably be closed thanks to c0f5e58bdc5aa01c04168fc0998fd100445bf081?

**Comment by vwitti** [comment]
Hi,this issue can be closed, as it seems to be resolved. thanksvolkerjimparis <notifications@github.com> hat am 6. März 2019 um 04:26 geschrieben:  This can probably be closed thanks to c0f5e58?—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
