### ISSUE TITLE
[TW#27961] BT: GATTS: Indication response missing attr handle

### ISSUE THREAD

**Issue by rojer** [espressif/esp-idf#2838]
If `esp_ble_gatts_send_indicate` is invoked with need_confirm = true (i.e., actual indication request), `ESP_GATTS_CONF_EVT` is raised with attr handle not set (esp_ble_gatts_cb_param_t.conf.handle = 0).

It works fine for notifications (`esp_ble_gatts_send_indicate(..., false)`) - handle is populated properly.

Tested on latest 3.2 release branch

**Comment by rojer** [comment]
should add that i'm testing with "BLE Scanner" android app.

**Comment by chegewara** [comment]
Its with master about month ago, still without answer:
https://github.com/espressif/esp-idf/issues/2552#issuecomment-437108715

**Comment by Weijian-Espressif** [comment]
@rojer, @chegewara, sorry, I will fix the bug.
@chegewara,  If you find a new bug, please create a new issue.

**Comment by Weijian-Espressif** [comment]
Hi @rojer @chegewara, this bug have fixed, please update to the latest IDF and try, thanks.
