### ISSUE TITLE
[TW#27980] cygpath command not found

### ISSUE THREAD

**Issue by ludo-d** [espressif/esp-idf#2839]
I installed umbutu(18.04) via virtualbox on my desktop computer
installed all python,esp32 and xtensa-esp32-elf modules
my projects are on the host (windows computer) and mounted in umbutu
when I go to a project map (example hello_world) and run make menuconfig, I always get a lot of errors (make: cygpath: Command not found) before  the menu is shown
this happens not only for make menuconfig, but for all make commands.

ludo@ludo-VirtualBox:~/C-esp/hello_world$ make menuconfig
make: cygpath: Command not found
make: cygpath: Command not found
make: cygpath: Command not found
make: cygpath: Command not found
make: cygpath: Command not found
make: cygpath: Command not found
make: cygpath: Command not found
make: cygpath: Command not found
make: cygpath: Command not found
make: cygpath: Command not found
make: cygpath: Command not found
make: cygpath: Command not found
make: cygpath: Command not found
make: cygpath: Command not found
make: cygpath: Command not found
make: cygpath: Command not found
make: cygpath: Command not found
make: cygpath: Command not found
make: cygpath: Command not found
make: cygpath: Command not found
make: cygpath: Command not found
make: cygpath: Command not found
make: cygpath: Command not found
make: cygpath: Command not found
make: cygpath: Command not found
make: cygpath: Command not found
make: cygpath: Command not found
make: cygpath: Command not found
make: cygpath: Command not found
make: cygpath: Command not found
make: cygpath: Command not found
make: cygpath: Command not found
make: cygpath: Command not found
make: cygpath: Command not found
make: cygpath: Command not found
make: cygpath: Command not found
make: cygpath: Command not found
make: cygpath: Command not found
make: cygpath: Command not found
make: cygpath: Command not found
make: cygpath: Command not found
make: cygpath: Command not found
make: cygpath: Command not found
make: cygpath: Command not found
make: cygpath: Command not found
make: cygpath: Command not found
make: cygpath: Command not found
make: cygpath: Command not found
make: cygpath: Command not found
make: cygpath: Command not found
make: cygpath: Command not found
make: cygpath: Command not found
make: cygpath: Command not found
make: cygpath: Command not found
make: cygpath: Command not found
make: cygpath: Command not found
make: cygpath: Command not found
make: cygpath: Command not found
make: cygpath: Command not found
make: cygpath: Command not found
make: cygpath: Command not found
make: cygpath: Command not found
make: cygpath: Command not found
make: cygpath: Command not found
make: cygpath: Command not found
make: cygpath: Command not found
make: cygpath: Command not found
make: cygpath: Command not found
make: cygpath: Command not found
make: cygpath: Command not found
make: cygpath: Command not found
make: cygpath: Command not found
make: cygpath: Command not found
make: cygpath: Command not found
make: cygpath: Command not found
make: cygpath: Command not found
make: cygpath: Command not found
make: cygpath: Command not found
make: cygpath: Command not found
make: cygpath: Command not found
make: cygpath: Command not found
make: cygpath: Command not found
make: cygpath: Command not found
make: cygpath: Command not found
make: cygpath: Command not found
make: cygpath: Command not found
make: cygpath: Command not found
make: cygpath: Command not found
make: cygpath: Command not found
make: cygpath: Command not found
Toolchain path: /home/ludo/esp/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc
Toolchain version: crosstool-ng-1.22.0-80-g6c4433a
Compiler version: 5.2.0
MENUCONFIG

*** End of the configuration.
*** Execute 'make' to start the build or try 'make help'.

does anybody have an Idea what this can cause.
ps: all make  commands work fine, except that they trow these cygpath errors

**Comment by nameofuser1** [comment]
Same bug on Ubuntu 18.04. Reverting to 6cb37ecc57ef07475d9e0167e72c7bc560dad0c1 indeed helps.

**Comment by cesarvizco** [comment]
Guys, I've just updated the esp-idf repo and this message is appearing here....

make: cygpath: Command not found
make: cygpath: Command not found
make: cygpath: Command not found
..
..

**Comment by projectgus** [comment]
The fix for this issue should be pushed to GitHub later today.

In the meantime, you can ignore this output - it doesn't effect the build process at all.
