### ISSUE TITLE
BLE DFS Light Sleep advertising incorrect and unconnectable (IDFGH-506)

### ISSUE THREAD

**Issue by lucazader** [espressif/esp-idf#2844]
## Environment

- Development Kit:       ESP32-DevKitC & custom PICO-D4 based module
- Module or chip used: ESP32-WROOM-32 & ESP32-PICO-D4
- IDF version:               v3.3-beta1-44-gda2116f55
- Build System:            Make
- Compiler version       1.22.0-80-g6c4433a
- Operating System:     Linux
- Power Supply:           external 3.3V

## Problem Description

Hi All,

Trying out the BLE light sleep with DFS that was committed to master in the last few days.
Great that your actively working on it!

When i enable bluetooth light sleep with DFS (using ORIG sleep mode) a few things happen:
- The device will either not be visible to scanners, or it will be visible, but with no advertising name.
- The advertising interval is incorrect: in my application the advertising interval is 200ms, with this enabled it changes to ~365ms
- The device is not connectable. On attempted connection nothing happens.

When i select EVED as the low power mode, the bluetooth works as expected, however it doesnt go to sleep.

I have observed using a (low burden voltage) current shunt and a scope that it appears to be trying to advertise as i see the three current spikes corresponding to the 3 advertising channels. This looks the same as when i change to the EVED with the advertising working correctly.
I can also see that when i attempt to connect using a phone the current wave-forms change briefly, as though it is trying to connect, however they then go back to advertising relatively quickly.

Please let me know what, if any code I should supply, and or sdkconfig settings.

**Comment by igrr** [comment]
Are you enabling light sleep as well, or only frequency scaling? (i.e. what is the configuration passed to esp_pm_config?).

**Comment by igrr** [comment]
I don't think it is. However there is some work in progress to make it compatible with light sleep as well. The bug here is probably that the bluetooth driver is not taking the `ESP_PM_NO_LIGHT_SLEEP` to indicate to the system that it does not support light sleep, yet.

Could you please check if the issues you are observing are gone when you set light_sleep_enable=false?

**Comment by mywang-espressif** [comment]
Hi @lucazader, currently bluetooth modem sleep is compatible with DFS but not readily compatible with light sleep yet. As Ivan said, there is a need to use a pm_lock (ESP_PM_NO_LIGHT_SLEEP) in bluetooth to prevent this case. 

EVED mode is only for internal test and may not function properly, please use ORIG mode. 

As for bluetooth low power clock, CONFIG_BTDM_LPCLK_SEL_MAIN_XTAL can be used if DFS is enabled, but it is not supposed to work during light sleep in the future. We will later provide other clock sources for bluetooth low power clock which can also be used during light sleep and now we are trying to resolve the issue in low power clock and tuning its performance.

**Comment by lucazader** [comment]
@igrr @mywang-espressif 

Thanks for the help so far.
I have tried disabling light sleep in the config printed above, This fixes the issues to do with timing. However i am un-able to see the esp32 advertising.
I have also tried disabling tickless idle in the menuconfig, this didn't change the advertising behaviour.
From the current measurements when in ORIG mode it does seem to be trying to advertise at the correct 200ms interval, but the phone cant see it.

However if I test with eved mode (seems a reliable way for me to quickly test if ble still works and im not going crazy), the peripheral shows up on my phone again.

I have tried deleting my sdkconfig and re-generating it to make sure nothing was hanging around, or was incorrectly configured, and it has the same behaviour.

Let me know if there is anything else I can enable, or disable or double check.

Glad to hear that there is ongoing work with BLE and low power, I am guessing there is no expected ETA when this might be out? We have a product in the pipeline that is on pause until BLE can go into a low power mode. (have contacted through the technical support department about this as well).

**Comment by lucazader** [comment]
@mywang-espressif 

I see you have merged in a PM lock for light sleep for now.

Out of curiosity, is the bluetooth low power clock features currently being worked on supposed to be landing into master soon, or is it more-likely to be months away.
As i said above we are waiting for this feature before we can go to mass production for a product we have designed.
I ased on the official email channel when this fix was supposed to land, and they said that it was supposed to be sometime in december.

Looking forward to hearing back from you.
Thanks,
Lucas

**Comment by lucazader** [comment]
@mywang-espressif @igrr 
Any response to my question above?

**Comment by mywang-espressif** [comment]
@lucazader, I am sorry for the late response. The feature for bluetooth modem sleep under light sleep is likely to be completed months away.
And as for your question that with DFS enabled, you cannot see ESP32 advertising, can you show me the ESP-IDF commit ID you are using and your sdkconfig file? According to my test, the advertising works all right. Please also provide me your advertising parameters as well.
In my test I am using master branch, commit (07645955a2) and the gatt_server_service_table example.

**Comment by lucazader** [comment]
Hi @mywang-espressif 

I have updated the idf and regenerated my sdk file and can no-longer reproduce this bug.

As for the BLE light sleep.
Is there any update on this? Is there any more timing information you can share of when this might land in the github master?

We really need to know a bit more information so we can plan production of product.

Thanks,
Lucas

**Comment by lucazader** [comment]
@mywang-espressif Any progress on this issue?

**Comment by davigr** [comment]
Having the same issue

**Comment by yyan160** [comment]
I'm having the same issue. Been waiting for it for months.

**Comment by jack0c** [comment]
BLE + light sleep with 32K XTAL was supported since idf-v4.0.
BLE + light sleep without 32K XTAL was supported since idf-v4.3, in this case, the XTAL(40MHz) was not power down.

**Comment by jack0c** [comment]
Close this issue
