### ISSUE TITLE
[TW#28005] ESP32 is reset when serial port is closed

### ISSUE THREAD

**Issue by keelung-yang** [espressif/esp-idf#2848]
We want to reuse USB-Serial bridge to reduce connected devices while communicating with PC.

In modbus-slave use case, if we don't reuse it we must buy another USB-Serial device to communicate with PC on modbus RTU. This means there are two USB devices connected to PC, two USB ports occupied on PC, and only one of them as daily using after delivering our ESP32 device to clients.

I know we can use WiFi and modbus TCP. But this solution need too many operations for our clients. And WiFi is not always available on PC.

IMO, bootloader is gone after booting, **it shouldn't run if no requesting, so it shouldn't occupy or response UART**. This is another reason we want to reuse USB-Serial bridge safely in our applications.

But now USB-Serial bridge can not be reused as modbus port, see this closed issue #2821

**Comment by 0rus26** [comment]
is any solution directly on hardware, like cutting out the trace betwen EN and the transistor S8050?
