### ISSUE TITLE
BLE OOB pairing support (IDFGH-509)

### ISSUE THREAD

**Issue by copercini** [espressif/esp-idf#2851]
It's more a documentation issue:

We are planing to pair some BLE servers with ESP32 (as secure BLE client) using NFC OOB... 

There is a recent commit that seems to add OOB support: https://github.com/espressif/esp-idf/commit/4e81705ca28cf453877704a4d83a6326f6f563e4

But on [GATT secure server tutorial](https://github.com/espressif/esp-idf/blob/master/examples/bluetooth/gatt_security_server/tutorial/Gatt_Security_Server_Example_Walkthrough.md#setting-security-parameters) it's clearly saying: `OOB Flag: describes if the device supports Out of Band passkey exchange, for example using NFC or Wi-Fi to exchange keys as TKs. Currently, the ESP32 does not support this feature.`

So, just to confirm before do some hardware, is it supported?

**Comment by chegewara** [comment]
Good question @Weijian-Espressif

**Comment by Weijian-Espressif** [comment]
@copercini @chegewara, Sorry, IDF already supports OOB, the documentation has not been updated yet.
