### ISSUE TITLE
[Improvement] Add normal baudrate names to menuconfig

### ISSUE THREAD

**Issue by keelung-yang** [espressif/esp-idf#2860]
As defined in linux kernel: [termbits.h](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/include/uapi/asm-generic/termbits.h)

![image](https://user-images.githubusercontent.com/20385450/50343306-53f45980-0561-11e9-975f-a923b1f5f595.png)

But in menuconfig:
![image](https://user-images.githubusercontent.com/20385450/50343478-02989a00-0562-11e9-95ba-3597929ea297.png)

**Comment by negativekelvin** [comment]
I don't get it, it is already best human readable version...
