### ISSUE TITLE
esp_ble_mesh_model_publish crashed after it succeed published message

### ISSUE THREAD

**Issue by eminarcissus** [espressif/esp-idf#2862]
Hi,

First thanks for your efforts in bring such a big step forward to have a working bluetooth mesh network 
here. 
I'm now trying to write a app which generate bluetooth mesh setting in the runtime, all settings are exactly the same with example node now, except for all elements/op/models are generate in the runtime, everything seems work like expected, except for publish.
This is the place where it crashes.

`

static void publish_sent(int err, void *user_data)
{
    printf("xa %d\n",err);
    struct bt_mesh_model *mod = user_data;
    s32_t delay;

    BT_DBG("err %d\n", err);
    printf("model %p\n",mod);
    printf("current module pub address %p\n",mod->pub);
    if (mod->pub->count) {
        delay = BT_MESH_PUB_TRANSMIT_INT(mod->pub->retransmit);
    } else {
        delay = next_period(mod);
    }
    printf("xc\n");
    if (delay) {
        BT_DBG("Publishing next time in %dms", delay);
        k_delayed_work_submit(&mod->pub->timer, delay);
    }
}

`

It crashes at mod->pub->count ( a NULL pointer  after I have printed couple a of times)

This is the piece where it publish,
`    

    printf("publish size is %d\n",sizeof(buf.buf));
    printf("publish content is %d\n",buf.buf);
    printf("publish pub addr %p\n",&global_onoff_pub);
    printf("model pub addr %p\n",mod->pub);
    printf("model addr %p\n",mod);
    int err = esp_ble_mesh_model_publish(mod, args[ARG_opcode].u_int,
                                     sizeof(*buf.buf) * buf.len, &buf.buf, ROLE_NODE);
`

This is the log when it crashes

`

current sub id is 0
now role c a is 0,current idx is 0
current sub id is 0
current sub id is 0
now role c a is 0,current idx is 0
current sub id is 0
now role c a is 0,current idx is 0
current sub id is 0
now role c a is 0,current idx is 0
BLE_MODEL_OP
handle event 50
BT Mesh Operation
start handling event 50
start send msg
message sent called,with length 1
send x
current sub id is 0
now role c a is 0,current idx is 0
ESP_BLE_MESH_MODEL_SEND_COMP_EVT
send y
msg sent 0
finished handling event 50
BLE_MODEL_OP
handle event 50
BT Mesh Operation
start handling event 50
start send msg
message sent called,with length 1
send x
current sub id is 0
now role c a is 0,current idx is 0
ESP_BLE_MESH_MODEL_SEND_COMP_EVT
send y
msg sent 0
start pub msg
publish size is 4
publish content is 1066737488
publish pub addr 0x3ffc0a50
model pub addr 0x3ffc0a50
model addr 0x3ffee6f8
message sent called,with length 1
send x
current sub id is 0
ESP_BLE_MESH_MODEL_PUBLISH_COMP_EVT
send y
msg published 0
finished handling event 50
xa 0
model 0x3ffee6f8
xb 0x0

`

The log message is a little bit mess here, I've added a lot of test code in logic to sort out where it really crashes, what really interesting is before I did call publish, the model object have a correct pub addr(esp_ble_mesh_pub_t) which points to 0x3ffc0a50, and model(esp_ble_mesh_model_t) is at 0x3ffee6f8.
After publish function succeed, it somehow crashes at publish_sent function, where at the time model address didn't change(so I do assume bt_mesh_model and esp_ble_mesh_model_t are the same thing), but its pub pointer is being change to 0x0, and publish_sent function is trying to get a publish interval here, and it crashes.
I searched around the code everywhere and didn't find any place it have changed model->pub, so I have no idea what's really happening behind the scene, this did troubled me around a week, so any hints is really appreciated here.

P.S.: Some updates, I've found sometimes this pointer is not NULL,but a runtime data 0x400 start address, I've commented out this part of code which make it works somehow, but I believe this is not the solution here, I would like to know what's really happening to model object between message publish and publish_sent is being called.

**Comment by chegewara** [comment]
Is this suppose to be like that:
`printf("publish size is %d\n",sizeof(buf.buf));` and `sizeof(*buf.buf)`

**Comment by eminarcissus** [comment]
errrrrrr,yes, this part is a bug, but is just for some debug info :)
I'm now trying to dig it a little bit deeper, looks quite interesting somehow.
and also for publish function, I did try to use the model object I created and the object when passed from callback of MODEL_OPERATION, they are not point to the same addr, and the first one will always crash,and the passed one is okay.

**Comment by chegewara** [comment]
Since publish size is 4 as we can see from logs, i believe that this part is with bug:
```
int err = esp_ble_mesh_model_publish(mod, args[ARG_opcode].u_int,
                                 sizeof(*buf.buf) * buf.len, &buf.buf, ROLE_NODE);
```
and is causing crash.
