### ISSUE TITLE
I2S_write blocks with unfilled DMA buffers (IDFGH-519)

### ISSUE THREAD

**Issue by iceman1194** [espressif/esp-idf#2864]
## Environment

- Development Kit:  ESP32-PICO-Kit
- Kit version: v4
- Module or chip used:  ESP32-PICO-D4
- IDF version: v3.3-dev-386-gf1b4c18c2
- Build System: Make
- Compiler version: crosstool-ng-1.22.0-80-g6c4433a
- Operating System:  Linux
- Power Supply: USB

## Problem Description

i2s_write() blocks when space available in buffer. (posted on esp32 forum). Upon further testing and inspecting the i2s.c code, it seems, even if I2S is started, the i2s_write() api allows the filling of only one TX buffer at a time. After a single buffer is filled, a subsequent call will block from filling the next buffer until a i2s_reg->int_st.out_eof interrupt is received. Thus having multiple buffers is pointless.

### Expected Behavior

As per ESP-IDF docs, if space is available in DMA transmit buffer, the function should return.

### Actual Behavior

i2s_write() blocks when DMA buffers available.

### Steps to repropduce

Run code below.

### Code to reproduce this issue

```cpp
#define I2S_NUM (0)
void app_main()
{
size_t bytes_written;
i2s_config_t i2s_config = {
.mode = I2S_MODE_MASTER | I2S_MODE_TX,
.sample_rate = 16000,
.bits_per_sample = 16,
.channel_format = I2S_CHANNEL_FMT_ONLY_LEFT,
.communication_format = I2S_COMM_FORMAT_I2S | I2S_COMM_FORMAT_I2S_MSB,
.dma_buf_count = 8,
.dma_buf_len = 400,
.intr_alloc_flags = ESP_INTR_FLAG_LEVEL1, // Interrupt level 1
};
i2s_pin_config_t pin_config = {
.bck_io_num = 19,
.ws_io_num = 23,
.data_out_num = 22,
.data_in_num = -1
};
i2s_driver_install(I2S_NUM, &i2s_config, 0, NULL);
i2s_set_pin(I2S_NUM, &pin_config);
i2s_stop(I2S_NUM);
ESP_LOGI(TAG, "begin write");
i2s_write(I2S_NUM, "X", 1, &bytes_written, portMAX_DELAY);
ESP_LOGI(TAG, "write complete"); /* never reaches here, even though DMA buffer is not full */
}
```

**Comment by mahavirj** [comment]
@iceman1194 `i2s_stop` before write operation will disable I2S interrupts, that will anyways block any I2S operations. Any specific reason for this, can you try removing it?

**Comment by egnor** [comment]
[this seems obsolete and should probably be closed?]

By inspection of the code and also experimentation, `i2c_write()` can definitely fill more than one DMA buffer. It does fetch each of them in turn from the queue of empty buffers, but that makes sense and is by design. In the example above, the call to `i2s_stop()` does seem like the problem, as @mahavirj pointed out...
