### ISSUE TITLE
[ble mesh]How to restore and save the BLE mesh state in between reboots (IDFGH-521)

### ISSUE THREAD

**Issue by eminarcissus** [espressif/esp-idf#2865]
What kind of information need to stored and restored between reboots? Currently in example we have to re-provision all the device, is there any doc on how to save the state and restore? 
I've noticed there's model keys/group attribute, don't know only save those are sufficient or not.

**Comment by chegewara** [comment]
This info suppose to be stored by mesh stack, but its not implemented yet. You need to store all provisioned data, but to be honest im not sure you can grab those info from application level.

PS could you add `[ble mesh]` in issue title for issues related to this topic, thanks

**Comment by eminarcissus** [comment]
Got it,thx very much :)

**Comment by Isl2017** [comment]
@eminarcissus, We will release a new BLE Mesh Version soon. It will include many new features, including `restoring the provision data of the node device`, `fast provisioning`, `wifi/ble_mesh coexistence`, etc... Please stay tuned!

**Comment by Isl2017** [comment]
New version has been released [here](https://github.com/espressif/esp-idf/tree/ble_mesh_release/esp-ble-mesh-v0.6.1)
