### ISSUE TITLE
[TW#28037] https exemple bad openssl commande

### ISSUE THREAD

**Issue by sifourquier** [espressif/esp-idf#2867]
Hi
In /examples/protocols/https_mbedtls/main/https_mbedtls_example_main.c
or https://github.com/espressif/esp-idf/tree/master/examples/protocols/https_request/main
you say we can use 

`openssl s_client -showcerts -connect www.howsmyssl.com:443 </dev/null`
But in some case we need add -servername

`openssl s_client -showcerts -connect www.howsmyssl.com:443 -servername www.howsmyssl.com </dev/null `

**Comment by sifourquier** [comment]
It s for different domain but sorry i do not can say the domain.
but yes the server share multiple certificate.

But i think you can change the comment for use a command work in any case.

**Comment by mahavirj** [comment]
@sifourquier 

Comment in code is very much specific to domain that is being used in example code and it is for reference purpose only. If you are using custom domain, then it is possible that some customization is required, for that help for `openssl` utility/command can serve as a good reference.
