### ISSUE TITLE
[TW#28039] ESP32 MCPWM Input Capture Problem

### ISSUE THREAD

**Issue by Milan991** [espressif/esp-idf#2868]
This problem is posted on ESP32 forum and there is no answer for months. Guy @steve.kim posted it and here is link to description: https://www.esp32.com/viewtopic.php?f=2&t=6313.

I've faced the same issue. Please give us any answer/feedback.

**Comment by koobest** [comment]
Hi, @Milan991 
Please see https://www.esp32.com/viewtopic.php?f=2&t=6313.
thanks !!

**Comment by Milan991** [comment]
@koobest I've managed to capture distance between rising edges of 125 us, after increasing frequency even further i could not get lower than this value. Is this the limit of capture mode?

Thank you very much for explanation, it had helped me a lot.

**Comment by AadiMehta** [comment]
Can you please comment on following issue also which is also related to mcpwm module.

https://esp32.com/viewtopic.php?f=2&t=6033&p=26085&hilit=mcpwm+sync#p26085

**Comment by Milan991** [comment]
@AadiMehta I already posted comment on forum link mentioned above. I'm waiting for answer.

**Comment by Milan991** [comment]
Hi @koobest,

In attachment is archive with two projects with my test configuration. I'm using two ESP32 DevKits, one is used as MCPWM receiver (folder "mcpwm_basic_config_capture") and other one is generating MCPWM signal (folder "mcpwm_basic_config"). GPIO Pin 23 from DevKit that is used as receiver is connected to GPIO Pin 19 on DevKit that is used as generator.

If you have any question, please ask me. Thank you very much in advance.

[mcpwmTest.zip](https://github.com/espressif/esp-idf/files/2779755/mcpwmTest.zip)

**Comment by koobest** [comment]
Hi, @Milan991
Can you try the way in my attachment?
[mcpwm_basic_config.tar.gz](https://github.com/espressif/esp-idf/files/2781235/mcpwm_basic_config.tar.gz)

thanks !!.

**Comment by Milan991** [comment]
Hi, @koobest,
Thanks men, you really save my time with this solution. It's working perfect. 
Did you consider creating pull request for this solution to be as example for capture mode?
Also if you are interested in capture mode where both edges is detected let me now, I've tested it and it is working fine.

Thank you one more time.

Closing this issue.
