### ISSUE TITLE
BTDM_CONTROLLER_BR_EDR_MAX_ACL_CONN_LIMIT

### ISSUE THREAD

**Issue by samiozen** [espressif/esp-idf#2871]
Is there a way to set BTDM_CONTROLLER_BR_EDR_MAX_ACL_CONN_LIMIT to more than 7 ?

**Comment by Weijian-Espressif** [comment]
Sorry, 7 is the maximum number of connections

**Comment by Alvin1Zhang** [comment]
@samiozen Hi, feel free to reopen the issue if you have more questions, thanks.

**Comment by samiozen** [comment]
Is this about software limitation or hardware limitation ?

If we change the defines in code and compile we can compile it but will it work ?
