### ISSUE TITLE
 Сan i write spi flash via pins esp32 connected to flash memory (IDFGH-526)

### ISSUE THREAD

**Issue by ArTyGill** [espressif/esp-idf#2877]
Hello!

I want to make a board that would be convenient to flash on production, there are several options.

1. Request esp32-wrover manufacturers to write firmware to flash, but I want to be independent of the manufacturer.
2. Flash esp32 through unused pins on the board (connected to spi flash), that would be excellent.
3. The worst option is to flash through uart.

How to flash esp32 via spi pins?

**Comment by costaud** [comment]
Guess you can pull down EN pin of esp32, then, connect flash pins to write firmware.
