### ISSUE TITLE
 ESP32 freezes on ESD (IDFGH-525)

### ISSUE THREAD

**Issue by ArTyGill** [espressif/esp-idf#2879]
After several times I hit the pin tuned to the input (I produce ESD), ESP32 hangs and sends garbage to the UART, even watchful timers do not save. Only restart helps.
How to fix this bug?

Hardware: esp32-wrover-i, with spi RAM enabled. 
spi-flash 4MB 40Mhz.

**Comment by costaud** [comment]
On which pins and at what voltage did you hit the module ?

**Comment by ArTyGill** [comment]
Test on pins io 34, 35, 36, 39
![esd](https://user-images.githubusercontent.com/23123591/50477312-df943d00-09dc-11e9-94ca-c0f3d0228e48.jpg)

**Comment by ArTyGill** [comment]
Does the internal circuit contain protection against electrostatic discharge on pins?

**Comment by ArTyGill** [comment]
@me-no-dev help pls!

**Comment by ArTyGill** [comment]
Yes, it's good, but for this it is enough to run an empty example, and it will hang even if you just knock tweezers on the pins :)
And even the watchdog timer does not save (

**Comment by ArTyGill** [comment]
Even if the pins are set up on the exit and the tightening is turned on this does not help (and these pins can only work as input).
It saves only additional capacity, but it can be a solution that will solve the problem, but for me it is important that the controller does not hang 100%.

**Comment by ArTyGill** [comment]
@me-no-dev  I can provide an oscillogram of what is happening on the pin.
Or just quickly sketch what it looks like.

**Comment by me-no-dev** [comment]
I am trying to reproduce this with code that just prints a message every second to uart. So far I can not reproduce. Will try to find WROVER-I to test with. What version IDF are you using? Commit?

**Comment by ArTyGill** [comment]
I advise you to try to take one end of the wire with your fingers, and with the other end of the wire, knock on the pin of ESP32.

I am using arduino-esp32 without IDF.

**Comment by me-no-dev** [comment]
I got one piece of WROVER-I and will try to replicate with 
```cpp
void setup() {

}

void loop() {
  printf("ping\n");
  delay(1000);
}
```

**Comment by Alvin1Zhang** [comment]
@ArTyGill Hi, sorry that we tried with all different boards and modules that we found but was not able to replicate this issue.

**Comment by ArTyGill** [comment]
![image](https://user-images.githubusercontent.com/23123591/55961727-2cdca780-5c78-11e9-8944-a38c4b38c509.png)

Everything works fine if you install protection against electrostatic discharge. I think it's worth thinking about installing a TVS diode on modules with ESP 32. And you also need protection on the antenna.
