### ISSUE TITLE
[TW#28143] Make MB_INST_MAX_SIZE configurable in menuconfig

### ISSUE THREAD

**Issue by keelung-yang** [espressif/esp-idf#2884]
Our applications depended on modbus heavily. But MB_INST_MAX_SIZE (2048) is too small.
I know I can change it, but thus make esp-idf dirty locally. So it's better to make it configurable.
Lucky, a few code should be changed:

![image](https://user-images.githubusercontent.com/20385450/50420489-d175dd80-0871-11e9-856a-d132ed2726e6.png)

**Comment by alisitsyn** [comment]
@keelung-yang, 

Thank you for your advice. 
Many Modbus software drivers (for Master PCs) were written with the 1 to 9999 register limits and cannot access extended registers in slave devices. Many slave devices do not support maps using the extended registers. The existing instance size limit in Modbus controller is not enough and it was changed to be configurable in KConfig. Does the instance limit = 65535 bytes looks reasonable for you?

The Modbus controller code has been updated and will be merged as soon as possible.

**Comment by keelung-yang** [comment]
@alisitsyn Thanks for your reply!
Yep, the instance limit = 65535 bytes looks reasonable, since 8 * 1024 is used currently in our application, and maybe extend it to 12 * 1024 (=12288 < 9999*2 = 19998) after several years.
