### ISSUE TITLE
[TW#12207] Discrepancy on macro definition values ARG_MAX and PATH_MAX

### ISSUE THREAD

**Issue by nkolban** [espressif/esp-idf#289]
While compiling some 3rd party code, I found warnings about re-definitions of a couple of symbols, namely `ARG_MAX` and `PATH_MAX`.  Searching ESP-IDF, I found both of these defined in `components/newlib/include/limits.h` and `components/newlib/include/sys/syslimits.h`.

In `syslimits.h` there are no redefinition guards.  The values of the pairs of variables are not consistent.  In one ARG_MAX = 4096 while in another ARG_MAX = 65536.  And also PATH_MAX = 4096 while in the other PATH_MAX = 1024.

**Comment by lakidd** [comment]
Did you ever find a solution to this @nkolban ? I've got the same thing with the pcbreflux examples

**Comment by nkolban** [comment]
Thankfully, the warnings are literally that ... warnings ... and other than not getting a pretty compile, all seems to function.  Hopefully the folks at Espressif will continue to track this issue and in good time will offer us an "out of the box" fix.  If you need an immediate workaround, I'd suggest picking one of the header files (probably syslimits.h) and comment out the duplicate symbols.  This will produce a clean compile.  The down-side is that when you bring in a new version of the ESP-IDF, the changes will be undone.

**Comment by lakidd** [comment]
Thanks, I added redefinition guards to syslimits.h and the warnings have gone. I thought it was causing some other issues but wasn't the case
