### ISSUE TITLE
UART not working

### ISSUE THREAD

**Issue by hetvishah08** [espressif/esp-idf#2894]
I am trying to develop an application on ESP32 DevkitC where i need 4 UART ports.I want to use GPIO4 and GPIO5 as my 4th UART port. I am not able to create it in ESP-IDF. 

In Arduino IDE there is a provision to use other GPIOs for UART by using SoftwareSerial library.I have tried it and was successful using those GPIOs.
I couldn't find a way in ESP-IDF. Help me by suggesting a way.

**Comment by Alvin1Zhang** [comment]
@hetvishah08 Hi, hetvishah08, I will temporarily close this issue and advise you could raise a topic on our forum at https://www.esp32.com/index.php Thanks.  For issue in GitHub, please help use ESP-IDF issue template in creating new issues https://github.com/espressif/esp-idf/blob/master/docs/issue_template.md. Thanks.
