### ISSUE TITLE
[TW#28193] BTDM_CONTROLLER_BR_EDR_MAX_ACL_CONN_LIMIT

### ISSUE THREAD

**Issue by samiozen** [espressif/esp-idf#2899]
Sorry issue #2871  is closed and i could not reopen it.

Is there a way to set BTDM_CONTROLLER_BR_EDR_MAX_ACL_CONN_LIMIT to more than 7 ?

Is this about software limitation or hardware limitation ?

If we change the defines in code and compile we can compile it but will it work ?

**Comment by Weijian-Espressif** [comment]
@samiozen, it is hardware limitation.
