### ISSUE TITLE
[TW#28238] Missing APIs to drop messages in tx/rx queues in CAN driver without re-configure or restart

### ISSUE THREAD

**Issue by keelung-yang** [espressif/esp-idf#2906]
In some application scope, we need drop messages in tx/rx queues, such as in  in ISO 14229-1, some request messages should be sent to functional ECUs before enter programming session. Since we don't care responses from functional ECUs including self, we need to drop them.

I know I can reveive and drop them manually, but it's better to add _can_drop_tx_queue()/can_drop_rx_queue()_ APIs to driver.

In our application, all messages in red should be dropped before send 10 02 request. And this is just one example. So it's better if droping APIs added into driver.

![image](https://user-images.githubusercontent.com/20385450/50639806-b3109000-0f9d-11e9-8e39-c5206d6f4cb8.png)

**Comment by jcsbanks** [comment]
Software filtering based on CAN ID could be a useful addition, but conditional filtering like this I put in higher layers and send only the data to the highest layer for which an ISO 15765 conversation is setup.

**Comment by keelung-yang** [comment]
@jcsbanks It's not about filtering, but drop messages after filtering.  

Now just one question: How to clean CAN tx/rx queue?

**Comment by jcsbanks** [comment]
I have a task that processes the Rx queue which copes with a full CAN bus during testing or flashing ECUs, with no filtering and the CPU usage is OK. Do you need to peek the queue and remove items?

**Comment by Dazza0** [comment]
Clearing the queue entirely will risk clearing messages of other IDs as well. To clear messages of a particular ID within a queue will require going through the whole queue item by item which is no different in terms of efficiency when compared to dropping those messages manually.

I think a run-time reconfigurable software filter would be more appropriate. A software filter would ideally be implemented in the CAN driver's ISR, and will prevent unwanted messages from being put into the queue to begin with.

Referring to the screenshot above, a software filter could first be configured to reject messages of ID `0x7EB`, then after sending the request of ID `0x7E3` , the software filter will be reconfigured at run time to being accepting messages of ID `0x7EB`.

**Comment by keelung-yang** [comment]
@jcsbanks I've implemented ISO 15765 on ESP32, as a tester.

@Dazza0 It's not about application scope but driver's APIs design. I checked this with several colleagues who developed applications on several MCUs with CAN controller, most of MCU SDK supply such APIs to clean tx/rx quene.
