### ISSUE TITLE
[TW#28239] Mesh nodes that see the router should directly connect to AP

### ISSUE THREAD

**Issue by mandreyel** [espressif/esp-idf#2908]
I think it's quite common that several nodes other than the root see the Wifi AP, so if they could also act as roots, it would alleviate load on the mesh a great deal, and particularly the root. In our testing the root frequently gets choked under high load, so we'd welcome this feature very much.

**Comment by ESP-MESH-QI** [comment]
API esp_mesh_set_vote_percentage(https://docs.espressif.com/projects/esp-idf/en/latest/api-reference/network/esp_mesh.html) can meet your requirement.

The default percentage is 0.9. If you set a small value, nodes which can hear the router could be easy to  become the root node.

**Comment by Alvin1Zhang** [comment]
@mandreyel Could you help share if any updates for this issue? Thanks

**Comment by mandreyel** [comment]
@Alvin1Zhang We dropped the mesh since then as it wasn't practical under large loads. What updates do you need?

**Comment by Alvin1Zhang** [comment]
Thanks.
