### ISSUE TITLE
模块软重启会导致MULTI_HEAP_ASSERT(b > prev, &prev->next_free); // free blocks should be ascending in address (IDFGH-715)

### ISSUE THREAD

**Issue by xizonghu** [espressif/esp-idf#2911]
模块软重新后是不是整个内存的数据没有重新清空呢，导致malloc失败

**Comment by costaud** [comment]
请问能否提供能够复现问题的测试代码？ 以及完整log？

**Comment by Alvin1Zhang** [comment]
@xizonghu Would you please help provide more details? Thanks.

**Comment by Alvin1Zhang** [comment]
@xizonghu Feel free to reopen this issue, thanks.
