### ISSUE TITLE
esp_image_verify missing in ESP-IDF 3.1.2

### ISSUE THREAD

**Issue by mharizanov** [espressif/esp-idf#2913]
esp_image_verify is missing in ESP-IDF 3.1.2
esp_err_t esp_image_verify(esp_image_load_mode_t mode, const esp_partition_pos_t *part, esp_image_metadata_t *data)

That breaks OTA functionality

Missing here:
https://github.com/espressif/esp-idf/blob/release/v3.1/components/bootloader_support/src/esp_image_format.c

Available here:
https://github.com/espressif/esp-idf/blob/master/components/bootloader_support/src/esp_image_format.c#L266

**Comment by chegewara** [comment]
Thats why it is missing, it has been added in next (3.2 or 3.3) version of esp-idf.

**Comment by mharizanov** [comment]
My bad, what was I thinking...
