### ISSUE TITLE
gattc_if rolls back to 0 (IDFGH-833)

### ISSUE THREAD

**Issue by chegewara** [espressif/esp-idf#2914]
esp-idf bt stack after reaching gattc_if == 8 it rolls back to 0:
```
E (127571) BT_APPL: bta_gattc_process_api_open Failed, unknown client_if: 0
```
Since 0-2 are reserved we can connect only 6 peripherals?

**Comment by Weijian-Espressif** [comment]
@chegewara, Yes,  no more than 6 devices.

**Comment by chegewara** [comment]
@Weijian-Espressif Thanks.
What about this error? Or it is not relevant?

**Comment by Alvin1Zhang** [comment]
@chegewara Thanks for reporting and @Weijian-Espressif please help support, thanks.

**Comment by Weijian-Espressif** [comment]
@chegewara, The maximum number of connections is 6.
