### ISSUE TITLE
how to do multipart post request? is there any example?

### ISSUE THREAD

**Issue by searchingforcode** [espressif/esp-idf#2925]
Hi i cant do multipart post request. Is there any example of multipart post request a image file or any binary file? 
Thanks

**Comment by hchaudhary1** [comment]
here is a project that uses multipart with http2:
https://github.com/MrBuddyCasino/ESP32_Alexa

**Comment by mahavirj** [comment]
Please prefer to use esp32.com forum for `how-to` questions.
