### ISSUE TITLE
Gatt_Client does not see the Gatt_server (IDFGH-550)

### ISSUE THREAD

**Issue by Aalhabashna** [espressif/esp-idf#2933]
I have two ESP32 WROOM-32U boards. I have setup one as a GATT_Server and the other as GATT_Client. When I scan for devices using the nRF connect app, I can see the GATT_server. Also, when I advertise a service with the nRF connect app, it can be seen by the client. However, the GATT_Client cannot see the advertisements from the GATT_Server. I use the ESP-IDF gatt_client and gatt_server examples. Can you please advise what could be the problem?

**Comment by Yulong-espressif** [comment]
It is strange， Can you show the log or code to me?

**Comment by Yulong-espressif** [comment]
@Aalhabashna

**Comment by Yulong-espressif** [comment]
@Aalhabashna, From the log of the client side you provided, there is no log after scan. Can you provide a complete log? Thanks.

**Comment by Aalhabashna** [comment]
The last thing it shows on the client side is (I (654) GATTC_DEMO: scan start success). However, if I run the advertisement from nRF connect app the client will be able to see it. It will show this 

===================
I (27454) GATTC_DEMO: 63 2c f3 03 72 e3
I (27454) GATTC_DEMO: searched Adv Data Len 25, Scan Response Len 7
I (27454) GATTC_DEMO: searched Device Name Len 5
I (27454) GATTC_DEMO: nRF5x
I (27464) GATTC_DEMO:
===================

but it does not see the advertisements from the ESP32 server.

**Comment by Aalhabashna** [comment]
a

**Comment by Aalhabashna** [comment]
@Yulong-espressif 
The last thing it shows on the client side is (I (654) GATTC_DEMO: scan start success). However, if I run the advertisement from nRF connect app the client will be able to see it. It will show this

I (27454) GATTC_DEMO: 63 2c f3 03 72 e3
I (27454) GATTC_DEMO: searched Adv Data Len 25, Scan Response Len 7
I (27454) GATTC_DEMO: searched Device Name Len 5
I (27454) GATTC_DEMO: nRF5x
I (27464) GATTC_DEMO:

but it does not see the advertisements from the ESP32 server.

**Comment by Yulong-espressif** [comment]
@Aalhabashna I haven't reproduce the issue you said on my platform. Can you provide your client-side code?

**Comment by Aalhabashna** [comment]
It seems that the problem is that the antenna of both ESP32 nodes is too weak for them to see each other. When using external antennas, the nodes were able to see each other and establish a connection.

**Comment by Weijian-Espressif** [comment]
@Aalhabashna,
 We have not reproduce the issue. What is your test distance? Can you test with two other ESP32?

**Comment by Alvin1Zhang** [comment]
@Aalhabashna Hi, would you help provide any updates for the issue? Thanks.

**Comment by Alvin1Zhang** [comment]
@Aalhabashna Hi, would you help provide any updates for the issue? Has your issue been fixed? Thanks.

**Comment by Aalhabashna** [comment]
@Alvin1Zhang As I mentioned in a previous comment, when using external antennas, the nodes were able to see each other and establish a connection. I tested with another ESP32 and got the same results. The case can be closed. Thank you!

**Comment by Alvin1Zhang** [comment]
@Aalhabashna Hi, thanks for the feedback.
