### ISSUE TITLE
[TW#28410] feature request: ULP program in C

### ISSUE THREAD

**Issue by dibalavs** [espressif/esp-idf#2946]
Hello,
I found, that ULP can only be programmed on ASM or by using C macros (ASM like style).
What about to use regular C compiler to provide binary file for ULP processor?

I understand that only 8K of memory is available to program.
But I remember time when AVR has 4 KB flash and  also gcc can be used to write simple programs.

Please allow to write ULP programs in C!

**Comment by igrr** [comment]
Hi @dibalavs, the option of porting a C compiler for the ESP32 ULP has been evaluated some time ago, and we decided not to support this. While this is technically possible, the required effort is significant, while code size and instruction set limitations mean that some parts of code will still need to be written in assembly.
I recommend having a look at macros such as https://github.com/tomtor/ulp-i2c/blob/master/main/ulp/stack.S which make writing ULP assembly programs easier.
