### ISSUE TITLE
esp_http_client: corruption of received data (IDFGH-566)

### ISSUE THREAD

**Issue by dibalavs** [espressif/esp-idf#2953]
Hello. 
I try to write domoticz client on ESP32. When I receive sensor information json, it became corrupted.
my esp idf (v3.1): commit 7fe18ef

here log:
```
D (6578) transp_http: HTTP_EVENT_DISCONNECTED
D (6578) transp_http: HTTP_GET: http://192.168.1.137:9000/json.htm?type=command&param=udevice&idx=2&svalue=0&battery=42

D (6598) transp_http: HTTP_EVENT_ON_CONNECTED
D (6618) transp_http: HTTP_EVENT_ON_HEADER, key=Server, value=BaseHTTP/0.6 Python/3.6.5
D (6618) transp_http: HTTP_EVENT_ON_HEADER, key=Date, value=Tue, 15 Jan 2019 20:17:28 GMT
D (6618) transp_http: HTTP_EVENT_ON_HEADER, key=Content-Length, value=1644
D (6628) transp_http: HTTP_EVENT_ON_HEADER, key=Content-Type, value=application/json;charset=UTF-8
D (6638) transp_http: HTTP_EVENT_ON_HEADER, key=Cache-Control, value=no-cache
D (6648) transp_http: HTTP_EVENT_ON_HEADER, key=Access-Control-Allow-Origin, value=*
I (6658) HTTP_CLIENT: output_ptr: 0, len:512, at:0x3ffc7124
D (6658) transp_http: HTTP_EVENT_ON_DATA, len=512, is_chunked:0
I (6668) HTTP_CLIENT: output_ptr: 0, len:512, at:0x3ffc7124
D (6668) transp_http: HTTP_EVENT_ON_DATA, len=512, is_chunked:0
I (6678) HTTP_CLIENT: output_ptr: 0, len:512, at:0x3ffc7124
D (6688) transp_http: HTTP_EVENT_ON_DATA, len=512, is_chunked:0
I (6688) HTTP_CLIENT: output_ptr: 0, len:108, at:0x3ffc7124
D (6698) transp_http: HTTP_EVENT_ON_DATA, len=108, is_chunked:0
D (6708) transp_http: HTTP_EVENT_ON_FINISH
D (6708) transp_http: HTTP_EVENT_DISCONNECTED
I (6708) transp_http: HTTP GET Status = 200, content_length = 1644
D (6718) transp_http: get buffer: ,
         "YOffset" : "0",
         "idx" : "1"
      }
   ],
   "status" : "OK",
   "title" : "Devices"
}
 "PlanIDs" : [ 0 ],
         "Protected" : false,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "SubType" : "RFXMeter 
```

Looks like when ESP receives multiple HTTP_EVENT_ON_DATA events, it does not append new data, but it overwrite existing data in buffer.

B.T.W when I enable full debug logging (enable esp_log_level_set("*", ESP_LOG_DEBUG);) in app_main()) problem disappeared.

here python test server to reproduce issue: [GIST](https://gist.github.com/dibalavs/c1eac8dec0efcb3ce7b929811aa2c858)

here ESP32 example code: [GIST](https://gist.github.com/dibalavs/47e2edd50b98a8571c82388f150a4111)

**Comment by chegewara** [comment]
You are receiving data in 4 chunks (do not confuse with chunked response), because `Content-Length = 1644` which is more than 512 bytes that can be received in one data tranfer:
```
I (6658) HTTP_CLIENT: output_ptr: 0, len:512, at:0x3ffc7124
D (6658) transp_http: HTTP_EVENT_ON_DATA, len=512, is_chunked:0
I (6668) HTTP_CLIENT: output_ptr: 0, len:512, at:0x3ffc7124
D (6668) transp_http: HTTP_EVENT_ON_DATA, len=512, is_chunked:0
I (6678) HTTP_CLIENT: output_ptr: 0, len:512, at:0x3ffc7124
D (6688) transp_http: HTTP_EVENT_ON_DATA, len=512, is_chunked:0
I (6688) HTTP_CLIENT: output_ptr: 0, len:108, at:0x3ffc7124
D (6698) transp_http: HTTP_EVENT_ON_DATA, len=108, is_chunked:0
```
What you have to do is to concatenate all data received in `HTTP_EVENT_ON_DATA`, then you have full response.

**Comment by dibalavs** [comment]
but why this error happened sometimes?
the most of time I receive full content:

```
D (6773) transp_http: HTTP_EVENT_ON_CONNECTED
D (6983) transp_http: HTTP_EVENT_ON_HEADER, key=Content-Length, value=1640
D (6983) transp_http: HTTP_EVENT_ON_HEADER, key=Content-Type, value=application/json;charset=UTF-8
D (6983) transp_http: HTTP_EVENT_ON_HEADER, key=Cache-Control, value=no-cache
D (6993) transp_http: HTTP_EVENT_ON_HEADER, key=Pragma, value=no-cache
D (7003) transp_http: HTTP_EVENT_ON_HEADER, key=Access-Control-Allow-Origin, value=*
I (7013) HTTP_CLIENT: output_ptr: 0, len:1640, at:0x3ffc6422
D (7013) transp_http: HTTP_EVENT_ON_DATA, len=1640, is_chunked:0
D (7023) transp_http: HTTP_EVENT_ON_FINISH
I (7023) transp_http: HTTP GET Status = 200, content_length = 1640
D (7033) transp_http: get buffer(len:1640): {
```

**Comment by dibalavs** [comment]
I understood a problem. Looks like I can fix it in my custom event handler.
But why esp_http itself does not care about concatenation packets? 
Also documentation: https://docs.espressif.com/projects/esp-idf/en/latest/api-reference/protocols/esp_http_client.html
does not say about it.

**Comment by dibalavs** [comment]
> Lets imagine situation you want to download big file (1-2MB)
This is not regular use for such chip. It can be done successfully with custom event handler,
But  more regular usage is communication with short messages (ping or remote server/ send-receive sensor data/ send some binary action like open the door, enable light.

As for me,  most often use-cases such be done in SDK code, to make user code as simple as possible.

**Comment by chegewara** [comment]
This is your point of view because you are using esp32 for IoT. There is a lot issues and topics on forum where people are asking and sharing usage of esp32 with large files.
Library should be generic and it is.

**Comment by dibalavs** [comment]
In my case the size of buffer I passed to config function, large than size of content, pointed by Content-Length header. So esp_http can safe merge all packets.

**Comment by FreakONN** [comment]
I have a similar issue. I'm receiving chunked response data that I need to concatenate into a single string and then store it to spiffs. I would appreciate if someone could show me how to do this since every other option failed to get desired result.

**Comment by jitin17** [comment]
@dibalavs In case the size of the buffer is greater than the content, then you can use esp_http_client the way it is used [here](https://github.com/espressif/esp-idf/blob/70b2c86fff478033f6e6e3049fa437926e92fb34/examples/protocols/esp_http_client/main/esp_http_client_example.c#L420). `esp_http_client_read` API reads the entire data bound to be received and then returns, this might be of help to you.

**Comment by pdemianczuk07** [comment]
Hi, in my app, i've problem to read data from server. I request for example 6kB, but the data is corrupted. I tried set various value of buffor for example config.buffer = 10*1024;
When I use config.event_handler 
i have many problems with heap and WDT.
Do you ever read big frame by esp_http_client componnent?

**Comment by pdemianczuk07** [comment]
Hi, I probably solve the problem. I update IDF to v4.1-dev-1533 from IDF4.0-dec-667. I had to update also toolchain (to esp-2019r2, compiler to 8.2.0), and I havn't problem with memory.
I found out some https://github.com/espressif/esp-idf/commit/9c0844da3f01fc55644bf147147b01d842d2f893#diff-c7c711c57aa3482655dd39165cf29087
fix, but I am not sure is this fix the problem.
Generally, You should check is the component is updated.
I dunno know why, my app had a problem but the most people wasnt.

**Comment by shubhamkulkarni97** [comment]
@dibalavs Do you have any updates for this issue?

**Comment by dibalavs** [comment]
No. I don't have any updates.

**Comment by Alvin1Zhang** [comment]
@dibalavs Thanks for reporting. Feel free to reopen if the issue still happens. Thanks. @shubhamkulkarni97 Thanks for the efforts.
