### ISSUE TITLE
Mass manufacturing utility is not working (IDFGH-567)

### ISSUE THREAD

**Issue by sysizlayan** [espressif/esp-idf#2955]
Hi,
I am trying the mass manufacturing utility under tools section and it is not working properly.
In mfg_gen.py file:
nvs_partition_gen.nvs_part_gen(input_filename = output_csv_file, output_filename = output_bin_file)
This function directly calls the nvs_part_gen function in the nvs_partition_gen.py file under components/nvs_flash/nvs_partition_generator.

This function requires an input size but the size is not given as input in mfg_gen.py.

When the function is called, it returns " 'NoneType' object has no attribute 'split' " error when it tries to parse the input_size parameter.

I could not find an appropriate parameter to give to function. Could you check? I am working with fixed "8KB" size partitions for now.

**Comment by tipnis-shivani** [comment]
The fix for this is under development. It should be available soon.

**Comment by shivani-tipnis** [comment]
Hi,
The fix for this is currently under development. It should be available soon.

**Comment by olegantonyan** [comment]
Any news here? The errors are still in master

**Comment by shivani-tipnis** [comment]
Hi,
The fix is done. Should be merged soon. 
My kind apologies for the delay. 
Will update as soon as its merged on master.

**Comment by shivani-tipnis** [comment]
@olegantonyan 
Hi, the fix is now in master.

**Comment by olegantonyan** [comment]
Great! thank
