### ISSUE TITLE
[TW#28472] Template Keyword used on esp-idf/components/esp_http_server/include/esp_http_server.h 

### ISSUE THREAD

**Issue by oggettone** [espressif/esp-idf#2956]
I'm compiling using C++ esp-idf, very last git pull. 

It seems it is used the keyword template on line 807 of the file  esp-idf/components/esp_http_server/include/esp_http_server.h 

bool httpd_uri_match_wildcard(const char ***template**, const char *uri, size_t len);

That cause a compilation issue, I've tried to change **template** to **p_template** and it works

bool httpd_uri_match_wildcard(const char ***p_template,** const char *uri, size_t len);

**Comment by anurag-kar** [comment]
Thank you @oggettone @gregjesl. Will fix this issue ASAP.
