### ISSUE TITLE
Wifi broken on windows 10 by commit 889c80ec1ca492647769d9348bd58b3159f900c7 (IDFGH-571)

### ISSUE THREAD

**Issue by wayneuroda** [espressif/esp-idf#2968]
## Environment

- Development Kit:      none
- Module or chip used:  ESP32-WROOM-32
- IDF version v3.1-63-g922bae0be
- Build System:         Make
- Compiler version: xtensa-esp32-elf-gcc.exe (crosstool-NG crosstool-ng-1.22.0-80-g6c4433a5) 5.2.0
- Operating System:     Windows 10
- Power Supply:         external 3.3V

## Problem Description

Using the softAp example application present in the latest master branch, windows 10 machine fails to get DHCP address, and also fails to ping ESP32 when manually assigned an address.

The same hardware and binary file though works perfectly with macOS on the same laptop (build and program ESP32 in windows, reboot into macOS, can ping the module now).

The problem seems to have been introduced in commit 889c80ec1ca492647769d9348bd58b3159f900c7 (18/09/2018) "Merge branch 'bugfix/backport_several_wifi_bugfix_v3.1' into 'release/v3.1'"

### Expected Behavior
Wifi softAP should work with windows 10 on the current master branch

### Actual Behavior
Wifi softAP does not work with windows 10 on the current master branch

### Steps to repropduce
1. follow getting started guide for ESP-IDF on windows 10
2. build the example softAP project
3. flash to ESP-WROOM-32
4. connect windows 10 machine to "myssid" wifi network
5. check address assigned to wifi adaptor on windows 10 machine, it will be autoconfig (169.254.x.x) address
6. set wifi IP address manually to 192.168.4.2
7. attempt to ping 192.168.4.1, ping will fail

### Code to reproduce this issue
Please use softAP wifi example project from a62cbfec9ab681bddf8f8e45d9949b1b1f67a2ec

change the serial port under serial flash options, leave all other options as default

**Comment by wayneuroda** [comment]
I can confirm the problem exists in 3.1 release.

**Comment by wayneuroda** [comment]
Sorry I got confused about the commit hash and what branch I was on at the time, I must not have been on the master branch because the hash I stated is not in that branch, but I have a suspicion that the same bug fixes (which seem to be merged into 2 or 3 branches from memory) cause the problem in all branches they have been merged into.

**Comment by wayneuroda** [comment]
The issue also exists at the head of the master branch.

**Comment by BalaVakamalla** [comment]
Has this been fixed now, we are still having problems when reconnecting from windows , it appears the esp32 is not receiving the disconnect message

**Comment by wayneuroda** [comment]
@liuzfesp any update? This must be a pretty critical issue I'd think! In the mean time I am working from commit hash 6519f1833a101fdc05e00e296740d025caed0e9d. There are other bugs present in that version, but I have worked around most of them. Hope it is fixed soon, good luck :)

**Comment by wayneuroda** [comment]
I wanted to try this today but I can't find that commit ID in the public repo, I assume it is not merged yet?

**Comment by liuzfesp** [comment]
@wayneuroda because of China New Year's day, the merging is delayed, it's merged into gitlab yesterday. I guess it will be sync to github automatically next week.

**Comment by liuzfesp** [comment]
HI @wayneuroda could you help to check whether this issue still exists in latest release/v3.1?

**Comment by wayneuroda** [comment]
I will check as soon as I can, I am extremely busy with other work at the moment.

**Comment by wayneuroda** [comment]
I've checked this now, and the problem I was seeing is no longer there - softAP now works on the master branch under windows 10! :)
