### ISSUE TITLE
Simulation feature (IDFGH-817)

### ISSUE THREAD

**Issue by jade111** [espressif/esp-idf#2982]
Hi,
There is a feature about project. I want to test the ESP32 code at pc with win32 or linux. So can you fix it?
Best regards,
jade

**Comment by jade111** [comment]
Hi igrr,
How about it?
Best regards,

**Comment by igrr** [comment]
Being able to build IDF apps for Linux target is something we would like to support, however we don't have capacity to implement this in the upcoming releases. We will keep this issue open and update it when some work on it is started.

**Comment by Alvin1Zhang** [comment]
@jade111 Thanks for report this.

**Comment by jade111** [comment]
Hi igrr，

Can you start this simulation. Or are you planning to do this？

**Comment by igrr** [comment]
No, this is still in the backlog, sorry.

**Comment by igrr** [comment]
We now have QEMU emulator integrated into idf.py tooling (https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/tools/qemu.html) as well as third-party solutions (https://wokwi.com/) so we can close the issue.
