### ISSUE TITLE
I cannot use AVRCP mode without initializing A2DP (IDFGH-580)

### ISSUE THREAD

**Issue by Marc-Aurele** [espressif/esp-idf#2984]
I want to use only the AVRCP mode so i started with the following example : a2dp_gatts_coex
When i flash it onto my board, here is the ouput of bluetoothctl :

```
[bluetooth]# info 20:47:DA:FB:93:65
Device 20:47:DA:FB:93:65 (public)
	Name: ESP_COEX_A2DP_DEMO
	Alias: ESP_COEX_A2DP_DEMO
	Class: 0x002c0414
	Icon: audio-card
	Paired: no
	Trusted: no
	Blocked: no
	Connected: no
	LegacyPairing: no
	UUID: Audio Sink                (0000110b-0000-1000-8000-00805f9b34fb)
	UUID: A/V Remote Control Target (0000110c-0000-1000-8000-00805f9b34fb)
	UUID: A/V Remote Control        (0000110e-0000-1000-8000-00805f9b34fb)
	RSSI: -50
```
That is working nicely enough so far - but now I want to get rid of the A2DP-part. My intuition was to just remove the esp_a2d_

I would have expected to now only see the UUIDs for "A/V Remote Control" - but there is just no UUIDs at all.

Regards,

Aurélien

**Comment by Marc-Aurele** [comment]
Hi,

Is there someone who has already worked on a workaround for this issue. I really need AVRCP without AD2P ? If you have any idea, feel free to share :)

Best regards,

Aurélien

**Comment by Marc-Aurele** [comment]
Here is the kind of configuration i want :
![image](https://user-images.githubusercontent.com/29012552/51823655-4fe5f500-22e0-11e9-8273-86be21247ca3.png)
Do you think it is possible with the current library ?

**Comment by Weijian-Espressif** [comment]
@blueMoodBHD
Please help answer this question, thanks.

**Comment by blueMoodBHD** [comment]
@Marc-Aurele Sorry to tell you that we can't use AVRCP without A2DP, now.

**Comment by Marc-Aurele** [comment]
Hi @blueMoodBHD 
Thank you very much for the reply. Indeed, we were suspecting that, as a result, we have switched on HID over GATT profil.

**Comment by jotkali** [comment]
Is it still the case that the ESP family cannot act as the AVRCP remote controller without consuming the audio as well - implementing BT spec 2.3.1.1 mentioned above? thx
