### ISSUE TITLE
[TW#28647] The variable is never updated on my phone when i read it

### ISSUE THREAD

**Issue by Marc-Aurele** [espressif/esp-idf#3017]
Hi,

I'm facing an issue when i want to read data from the device on my phone. I inspire from the hid demo example and i want to add a custom characteritic. In the gatts_profile_event_handler i added:

` case ESP_GATTS_READ_EVT:
            
    ESP_LOGI(HID_LE_PRF_TAG, "ESP_GATTS_READ_EVT, conn_id %d, trans_id %d, handle %d\n", param->read.conn_id, param->read.trans_id, param->read.handle);
           
     if (param->add_attr_tab.svc_uuid.uuid.uuid16 == CUSTOM_APP_ID) {
                
        esp_ble_gatts_set_attr_value(param->read.handle, sizeof(my_time), my_time);
               
         ESP_LOGI(HID_LE_PRF_TAG, "READ EVENT: %d\n",my_time);
           
     }
     break;`

But the value read on the phone never change whereas "my_time" is supposed to be updated in background task.

I have attached the code if you want to take a look.

Thank you in advance,

Best regards ,

Aurélien
[hid_device_le_prf.zip](https://github.com/espressif/esp-idf/files/2823544/hid_device_le_prf.zip)

**Comment by Marc-Aurele** [comment]
Hello, 

Thank you very much for the reply. What do you mean by setting the value before read ? Actually i can read the first value when the variable has been intialized but then when i launch a read operation onto this variable from my phone, the variable is never updated with its last value that has been changed in a background task.

Regards,

Aurélien

**Comment by Marc-Aurele** [comment]
> @Marc-Aurele, please set attribute value before read.

**Comment by Weijian-Espressif** [comment]
please set the attribute value before your phone read.  When you create attr_db with `ESP_GATT_AUTO_RSP`, ESP32 automatically sends a response. when you get `ESP_GATTS_READ_EVT`, it is too late to set attribute value.
You have two ways:
1.  set the attribute value before your phone read
2.  please create  `attr_db` with `ESP_GATT_RSP_BY_APP`, when you get `ESP_GATTS_READ_EVT`, send a response using `esp_ble_gatts_send_rsp()` with your `my_time`.

**Comment by Marc-Aurele** [comment]
Hi,

Thank you very much for your help. All is working fine now ;)

Regards,

Aurélien
