### ISSUE TITLE
[TW#28651] ASSERT_PARAM(-218959118 0), in arch_main.c at line 325

### ISSUE THREAD

**Issue by lucascoxBAF** [espressif/esp-idf#3020]
## Environment

- Module or chip used:  ESP32-WROOM-32D
- IDF version (v3.3-beta1-326-gd7a7a6835)
- Build System:        CMake
- Compiler version crosstool-ng-1.22.0-73-ge28a011
- Operating System:     Linux

## Problem Description

ASSERT_PARAM(-218959118 0), in arch_main.c at line 325 when running the bluetooth/gatt_client example with no modifications.

### Steps to repropduce

```bash
idf.py build
idf.py flash
```

## Debug Logs
.
.
.

I (7691) GATTC_DEMO: 90 fd 9f 0d 89 bb
I (7691) GATTC_DEMO: searched Adv Data Len 29, Scan Response Len 0
I (7701) GATTC_DEMO: searched Device Name Len 6
I (7701) GATTC_DEMO: BAFCon
I (7711) GATTC_DEMO:

I (7711) GATTC_DEMO: 00 0b 57 80 ec 1d
I (7711) GATTC_DEMO: searched Adv Data Len 29, Scan Response Len 0
I (7721) GATTC_DEMO: searched Device Name Len 6
I (7731) GATTC_DEMO: BAFCon
I (7731) GATTC_DEMO:

I (7731) GATTC_DEMO: 1f 78 50 16 b2 cd
I (7741) GATTC_DEMO: searched Adv Data Len 31, Scan Response Len 0
I (7741) GATTC_DEMO: searched Device Name Len 0
I (7751) GATTC_DEMO:

I (7751) GATTC_DEMO: 09 7d 96 1f c4 19
I (7761) GATTC_DEMO: searched Adv Data Len 31, Scan Response Len 0
I (7761) GATTC_DEMO: searched Device Name Len 0
I (7771) GATTC_DEMO:

I (7771) GATTC_DEMO: 46 df 13 ce a4 60
I (7781) GATTC_DEMO: searched Adv Data Len 28, Scan Response Len 10
I (7781) GATTC_DEMO: searched Device Name Len 0
I (7791) GATTC_DEMO:

ASSERT_PARAM(-218959118 0), in arch_main.c at line 325

**Comment by Weijian-Espressif** [comment]
@lucascoxBAF, Adv packet printing is too slow, controller memory is running out. please  set `.scan_duplicate         = BLE_SCAN_DUPLICATE_DISABLE` when you set scan parameters.

**Comment by lucascoxBAF** [comment]
@Weijian-Espressif, .scan_duplicate is currently set to disable. Note, this code is espressif's example code, not my code. 

The code being run is esp-idf/examples/bluetooth/gatt_client

```C
static esp_ble_scan_params_t ble_scan_params = {
    .scan_type              = BLE_SCAN_TYPE_ACTIVE,
    .own_addr_type          = BLE_ADDR_TYPE_PUBLIC,
    .scan_filter_policy     = BLE_SCAN_FILTER_ALLOW_ALL,
    .scan_interval          = 0x50,
    .scan_window            = 0x30,
    .scan_duplicate         = BLE_SCAN_DUPLICATE_DISABLE
};
```

**Comment by Weijian-Espressif** [comment]
Sorry, please set `.scan_duplicate = BLE_SCAN_DUPLICATE_ENABLE` when you set scan parameters.

**Comment by lucascoxBAF** [comment]
@Weijian-Espressif, that fixed it. You might want to make that change in the esp-idf/examples/bluetooth/gatt_client. Should I go ahead and close this issues.

**Comment by Weijian-Espressif** [comment]
@lucascoxBAF,If it has been fixed, please close the issue. I will modify the gatt_client demo, thanks.

**Comment by jimparis** [comment]
Isn't BLE_SCAN_DUPLICATE_DISABLE just a workaround that is avoiding the real issue: the binary library asserting when events aren't being processed fast enough?

**Comment by Weijian-Espressif** [comment]
@jimparis ,  Isn't BLE_SCAN_DUPLICATE_DISABLE just a workaround that is avoiding the real issue: the binary library asserting when events aren't being processed fast enough?

**Comment by jimparis** [comment]
Maybe already fixed by 75287eb56989d1e3ec6bd3ea7cfc8fd32bb4df61?

**Comment by Weijian-Espressif** [comment]
@jimparis, you are right, plaese update and try, thanks.

**Comment by paulreimer** [comment]
I receive this error in the `feature/nimble-preview` branch as well, would like to request the fix applied to that branch, too, if compatible.

**Comment by Alvin1Zhang** [comment]
@paulreimer Hi, would you help submit a new issue for the error in feature/nimble-preview branch? Thanks.
