### ISSUE TITLE
[TW#28664] SDKCONFIG variables marked as error in Eclipse IDE

### ISSUE THREAD

**Issue by carlessole** [espressif/esp-idf#3026]
I'm using Ubuntu and after following all the steps given in [Build and Flash with Eclipse IDE](https://docs.espressif.com/projects/esp-idf/en/stable/get-started/eclipse-setup.html) everything is OK and I'm able to build and flash my projects properly.
But there is an issue that is bothering me. The case is that eclipse does not find all the "variables" defined in "sdkconfig" file and so, shows as if my project is full of errors:
![image](https://user-images.githubusercontent.com/46353439/52231454-4baa7080-28ba-11e9-9976-3ae1154f264f.png)

Is there any way to solve that?
Thanks!

**Comment by igrr** [comment]
Can you please right click the source file in project tree, and use "Create parser log file" option (somewhere under Index), then attach the file here?

Also, if you add `#include "sdkconfig.h"` to your source file, and then control-click on the include line, does it open the correct sdkconfig.h file (of the project you are working with)?

**Comment by carlessole** [comment]
Thanks @igrr .
I solve that issue adding this include path:

![image](https://user-images.githubusercontent.com/46353439/52566871-244c2a00-2e0b-11e9-8681-baedbf76e3da.png)
