### ISSUE TITLE
[TW#28659]（ESP32/ESP-IDF/platformIO）ESP_ERR_NVS_NEW_VERSION_FOUND

### ISSUE THREAD

**Issue by omkw** [espressif/esp-idf#3027]
Hi.
I want to use example code. (esp-idf/examples/protocols/aws_iot/subscribe_publish/)
I am trouble with error about nvs. (ESP_ERR_NVS_NEW_VERSION_FOUND)
I looked for a solution, but I could not find it.
attached figure shows details.
please help me.

[enviroment info] 
OS:Windows10
IDE: VSC with PlatformIO (Home 2.0.0/Core 3.6.4)
  platform = espressif32( 1.6.0)
  framework = espidf
  board = esp32dev

![esp-idf](https://user-images.githubusercontent.com/47342986/52254036-aab9c500-294e-11e9-91d0-be385e32722e.png)

**Comment by AmrutaCh** [comment]
Check your esp-idf version. In version 3.1 and above, the examples already include proper nvs initialization code. (not sure about older versions.)
You can add following code at the start of `app_main()`

```
    esp_err_t err = nvs_flash_init();
    if ((ESP_ERR_NVS_NO_FREE_PAGES == err) || (ESP_ERR_NVS_NEW_VERSION_FOUND == err))
    {
        ESP_ERROR_CHECK(nvs_flash_erase());
        err = nvs_flash_init();
    }
    ESP_ERROR_CHECK(err);
```

**Comment by omkw** [comment]
it works fine!
thanks so much.

in short, current version of ESP-IDF framework served by Espressif 32(v1.6.0) contains bug I posted. right?

**Comment by AmrutaCh** [comment]
1. v1.6.0 is pretty old
2. Its not bug in SDK but it user code. SDK is already returning the error-code. Its up-to the application, how to handle it.

**Comment by Alvin1Zhang** [comment]
@AmrutaCh Thanks for explaining. @omkw I assume your issue has been resolved, feel free to reopen if your issue still exists. Thanks
