### ISSUE TITLE
Http Server (IDFGH-816)

### ISSUE THREAD

**Issue by snahmad** [espressif/esp-idf#3032]
Is this Http Server better than mongoose. I have having issues with mongoose web server on ESP32 platform. Loading web files of total size=2.7 Mb from SD Card  to server web pages includes 20 files with images takes few seconds.

https://github.com/espressif/esp-idf/blob/abea9e4c02bb17e86298aec4e299780399e4789f/examples/protocols/http_server/file_serving/main/main.c

**Comment by Alvin1Zhang** [comment]
@snahmad Thanks for reporting this issue.

**Comment by mahavirj** [comment]
@snahmad Difficult to comment on this, but if you run into any issues with http server from IDF please feel to file new issue. Closing this one.

**Comment by snahmad** [comment]
ok, not using http server. Mongoose is working for me. Also mongoose is full networking library include TCP and UDP works on other platforms as well. better for our use case.
