### ISSUE TITLE
Last byte from SPI master missing (IDFGH-612)

### ISSUE THREAD

**Issue by tatulea** [espressif/esp-idf#3038]
## Environment

- Development Kit:      ESP32-Wrover-Kit
- Kit version (for WroverKit/PicoKit/DevKitC): v4.1
- Module or chip used:  ESP32-WROVER
- IDF version:  v3.1.2
- Build System:         Make
- Compiler version: 1.22.0-80-g6c4433a
- Operating System:     Linux
- Power Supply:         USB

## Problem Description

I am using SPI master to communicate with an accelerometer. The problem is that spi_device_transmit function fills the rx_buffer without the last byte.
From my debugging, I found out that the missing byte is for rx_buffer and for rx_data as well (is SPI_TRANS_USE_RXDATA flag is used).
The problems appears just if I use rxlength > 8. For rxlength = 8, it returns just one byte and it is ok, but for anything more than that it will loose the last byte, even I have it on the SPI transmission (I am using a logic analyzer and I can see the last byte being in the transmission).

### Code to reproduce this issue

```cpp
#include "esp_log.h"

oid app_main()
{
    esp_err_t ret;

    spi_bus_config_t spi_bus_cfg = {
        .mosi_io_num=MOSI_PIN,
        .miso_io_num=MISO_PIN,
        .sclk_io_num=SCLK_PIN,
        .quadwp_io_num=-1,
        .quadhd_io_num=-1,
        .max_transfer_sz=SPI_MAX_TRANSFER_SIZE
    };

    spi_device_interface_config_t spi_device_cfg = {
        .command_bits=0,
        .address_bits=8,
        .mode=0,
        .clock_speed_hz=1000000,
        .spics_io_num=CS_PIN,
        .queue_size=1,
        .flags = SPI_DEVICE_HALFDUPLEX
    };
   spi_transaction_t t;
   esp_err_t ret;

   uint8_t request[1] = { 0x78 | 0x80 };

   memset(&t, 0, sizeof(t));
   t.addr = request[0];
   t.rxlength = 16;
   t.flags = SPI_TRANS_USE_RXDATA;

   ret = spi_device_transmit(spi, &t);
   assert( ret == ESP_OK );
   printf("%X \t %X \t%X\n", t.rx_data[0], t.rx_data[1]);
```

rx_data[1] will be 0, even if rxlength = 16. If rxlength = 24, then rx_data[1] will have a value, but rx_data[2] is 0.
I tried to set length as well, but is the same problem...

Any help?

Thanks,
Gabriel

**Comment by Alvin1Zhang** [comment]
Thanks for reporting and sorry for slow reply, the fix is available https://github.com/espressif/esp-idf/commit/52a76867d1c46e6a9f8cc771f2a14c1f6ce0238b, feel free to reopen. Thanks.
