### ISSUE TITLE
Menuconfig: BLE_SCAN_DUPLICATE, DUPLICATE_SCAN_CACHE_SIZE, BLE_MESH_SCAN_DUPLICATE_EN, MESH_DUPLICAT (IDFGH-633)

### ISSUE THREAD

**Issue by carlessole** [espressif/esp-idf#3053]
Hello,
First of all, sorry for my ignorance but I don't understand what these configuration parameters mean:

- BLE_SCAN_DUPLICATE
- DUPLICATE_SCAN_CACHE_SIZE
- BLE_MESH_SCAN_DUPLICATE_EN
- MESH_DUPLICATE_SCAN_CACHE_SIZE

Is there somewhere where it's explained with more detail? 
With the info found here (https://docs.espressif.com/projects/esp-idf/en/v3.0.7/api-reference/kconfig.html) I still don't undrestand.

Thanks

**Comment by chegewara** [comment]
https://docs.espressif.com/projects/esp-idf/en/latest/api-reference/bluetooth/esp_gap_ble.html#_CPPv2N21esp_ble_scan_params_t14scan_duplicateE

This should be self explanatory(how many advertised device to  keep track):
* DUPLICATE_SCAN_CACHE_SIZE

Those 2 are related to ble mesh which is not implemented in master yet:
* BLE_MESH_SCAN_DUPLICATE_EN
* MESH_DUPLICATE_SCAN_CACHE_SIZE

**Comment by Weijian-Espressif** [comment]
@chegewara, thanks.
@carlessole, Do you have any other questions?
