### ISSUE TITLE
[TW#28769] send UDP broadcast messages 

### ISSUE THREAD

**Issue by snahmad** [espressif/esp-idf#3056]
I need to send continuous UDP messages to IPv4 broadcast address : 255.255.255.255
Do I need specify port number.

Do I need to connect first.

Is this UDP client . Do I need UDP server.

Kindly give me example using LWIP.

Can multiple UDP application can received/monitor these messages via UDP using same port.

**Comment by liuzfesp** [comment]
@ESP_xiehang please help.

**Comment by negativekelvin** [comment]
Don't ignore this, it's rude

> If your issue is a general question, starts similar to **"How do I.."**, or is related to 3rd party development kits/libs, please discuss this on our community **forum at esp32.com instead**.

**Comment by snahmad** [comment]
ok, thanks.

**Comment by espxiehang** [comment]
Do I need specify port number？ 
Yse.
Do I need to connect first?
No need.
Do I need UDP server？
No need.

These messages can be received as long as the application with the same port number.

**Comment by snahmad** [comment]
ok, undertstood.
