### ISSUE TITLE
[TW#28765] In tcp_client example, process should breack if socket is not connected

### ISSUE THREAD

**Issue by aureq** [espressif/esp-idf#3058]
Hi,

After line 149, there should be a `break;` rather than allow the process to continue as the socket has failed to connect to the remote host.

https://github.com/espressif/esp-idf/blob/abea9e4c02bb17e86298aec4e299780399e4789f/examples/protocols/sockets/tcp_client/main/tcp_client.c#L147-L154

Thank you.

**Comment by liuzfesp** [comment]
Hi @aureq, thanks for pointing out it. We will correct it in IDF master.

**Comment by espxiehang** [comment]
thanks for pointing out it. We correct it as soon as possible.
