### ISSUE TITLE
https_mbedtls example  (IDFGH-636)

### ISSUE THREAD

**Issue by myzhang001** [espressif/esp-idf#3070]
我在使用 https_mbedtls example 时发现我在例程的基础上在创建一个任务 程序就无法运行
代码如下
static void zmy_test_task(void *pvParameters)
{
    while(1)
    {
        ESP_LOGI(TAG,"ZMY TEST");
        vTaskDelay(5000 / portTICK_PERIOD_MS);
    }
}

void app_main()
{
    ESP_ERROR_CHECK( nvs_flash_init() );
    initialise_wifi();

    xTaskCreate(&zmy_test_task, "ZMY TEST ", 1024, NULL, 4, NULL);

    xTaskCreate(&https_get_task, "https_get_task", 8192, NULL, 5, NULL);
}
其余代码为做任何修改  程序一直复位

error log

abort() was called at PC 0x4008be40 on core 1

Backtrace: 0x4008bbfc:0x3ffb9a30 0x4008be29:0x3ffb9a50 0x4008be40:0x3ffb9a70 0x40

Rebooting...
ets Jun  8 2016 00:22:57

**Comment by igrr** [comment]
Try increasing stack size to at least 2048. Stack size of 1024 bytes is not sufficient for printf (which gets called from ESP_LOG.

Also please check IDF Monitor, it will decode backtraces automatically, making it easier to debug crashes: https://docs.espressif.com/projects/esp-idf/zh_CN/latest/get-started/idf-monitor.html

**Comment by mahavirj** [comment]
@myzhang001 Could you please update here? Can this issue be closed?

**Comment by mahavirj** [comment]
Closing due to lack of response. Please feel free to open new issue in case still problem exists.
