### ISSUE TITLE
[TW#28790] how do i reduce image file size

### ISSUE THREAD

**Issue by baicaiaichibaicai** [espressif/esp-idf#3071]
i build  project `examples/wifi/scan` and then `make flash`
```text
App "scan" version: 1
Flashing binaries to serial port /dev/ttyUSB0 (app at offset 0x10000)...
esptool.py v2.6
Serial port /dev/ttyUSB0
Connecting....
Chip is ESP32D0WDQ5 (revision 1)
Features: WiFi, BT, Dual Core, 240MHz, VRef calibration in efuse, BLK3 partially reserved, Coding Scheme 3/4
MAC: 30:ae:a4:cc:2a:2c
Uploading stub...
Running stub...
Stub running...
Configuring flash size...
Auto-detected Flash size: 4MB
Flash params set to 0x0220
Compressed 24224 bytes to 14504...
Wrote 24224 bytes (14504 compressed) at 0x00001000 in 1.3 seconds (effective 151.2 kbit/s)...
Hash of data verified.
Compressed 599968 bytes to 364570...
Wrote 599968 bytes (364570 compressed) at 0x00010000 in 32.2 seconds (effective 148.9 kbit/s)...
Hash of data verified.
Compressed 3072 bytes to 103...
Wrote 3072 bytes (103 compressed) at 0x00008000 in 0.0 seconds (effective 1643.9 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting via RTS pin...

```

it about 600KB of out file and task 32 seconds to download ,i found that it will link a lot of unuse lib in it,how can i optimiza it

**Comment by AmrutaCh** [comment]
@baicaiaichibaicai 
There are many options available in `menuconfig` to optimize size and reduce download time. Take a look

But if you want quick solution check this [discussion](https://www.esp32.com/viewtopic.php?t=6559). It has enough info to reduce overall binary size.

You can increase download speed to reduce the time taken

**Comment by BrianPugh** [comment]
As @AmrutaCh said, if you are just looking to minimize upload time, change your upload baudrate to 921600 or 1500000 (1500000 is about as high as my board will go). Should reduce the upload time of a 600KB binary to about 6 seconds.

**Comment by baicaiaichibaicai** [comment]
@AmrutaCh  @BrianPugh   thank you for respone
