### ISSUE TITLE
BUG: Mesh and espnow interoperability issue (IDFGH-657)

### ISSUE THREAD

**Issue by leenowell** [espressif/esp-idf#3091]
## Environment

* Development Kit:      ESP32-DevKitC
* Kit version (for WroverKit/PicoKit/DevKitC): [v1|v2|v3|v4]
* Module or chip used:  [ESP32-WROOM-32|
* IDF version (run `git describe --tags` to find it): v3.3-beta1-223-ga62cbfe
* Build System:         [Make]
* Compiler version (run `xtensa-esp32-elf-gcc --version` to find it): 1.22.0-73-ge28a011
* Operating System:     [Linux]
* Power Supply:         [USB]
## Problem Description

I have an esp8266 sending an espnow message to an esp32 which is part of a mesh.  On receiving this data, the esp32 sends the data to root. If the node is root then the message sends fine.  If it is not root then the send fails.  Also, during the startup process, the node also sends a message to root and root sends a response message back.  Both these work fine so it appears that calling the mesh send in the espnow receive callback when the node is not root is is the issue.

I have raised this on the forum here
https://www.esp32.com/viewtopic.php?f=21&t=9279

### Expected Behavior
Send should work correctly and send message to root

### Actual Behavior
Depending on the tos value I give during the send I get different error message

MESH_TOS_P2P; I get ESP_ERR_MESH_TIMEOUT
MESH_TOS_DEF; I get ESP_ERR_MESH_ARGUMENT
MESH_TOS_E2E; I get ESP_ERR_NOT_SUPPORT

### Code to reproduce this issue
https://www.esp32.com/viewtopic.php?f=21&t=9279

## Debug Logs
https://www.esp32.com/viewtopic.php?f=21&t=9279

## Other items if possible

- [ ] sdkconfig file (attach the sdkconfig file from your project folder)
- [ ] elf file in the ``build`` folder (**note this may contain all the code details and symbols of your project.**)
- [ ] coredump (This provides stacks of tasks.)

**Comment by dongdong004** [comment]
```
The receiving callback function also runs from WiFi task. So, do not do lengthy operations in the callback function. Instead, post necessary data to a queue and handle it from a lower priority task.
```
See [IDF-DOC](https://docs.espressif.com/projects/esp-idf/en/latest/api-reference/network/esp_now.html?highlight=esp_now#receiving-esp-now-data)
