### ISSUE TITLE
SAE J2716 (aka SENT) SUPPORT ?

### ISSUE THREAD

**Issue by yanzixiang** [espressif/esp-idf#3094]
I'm sorry I don't know if this is the right place to ask this question.
Can ESP32 decode SENT signal on a digital input on gpio ?
Is there any support avalible ？

**Comment by igrr** [comment]
There's no support for this protocol out of the box, but ESP32's RMT peripheral seems to be capable of capturing the incoming waveform to memory. Decoding can then be done in software.

**Comment by projectgus** [comment]
Closing as the question seems to be answered.

To discuss further, suggest posting on the https://esp32.com/ forums.
