### ISSUE TITLE
esp_http_client event HTTP_EVENT_HEADER_SENT never received by the http event handler (IDFGH-655)

### ISSUE THREAD

**Issue by pantaluna** [espressif/esp-idf#3095]
## Environment

- Development Kit:      [Adafruit HUZZAH32]
- Core (if using chip or module): [ESP-WROOM32]
- IDF version (commit id): ESP-IDF v3.1.3 cf5dbadf4f25b395887238a7d4d8251c279afa8c
- Development Env:      [Eclipse]
- Operating System:     [Windows]
- Power Supply:         [USB]

## Problem Description

1. The event HTTP_EVENT_HEADER_SENT is never sent to the http event handler.
2. The documentation of the event HTTP_EVENT_HEADER_SENT states "After sending all the headers to the server". So it would be better to rename the event to HTTP_EVENT_HEADERS_SENT with "s", or send the event after each header is sent.

### Expected Behavior

The event is sent to the event handler.

### Actual Behavior

No event is sent.

### Code to reproduce this issue

The official ESP-IDF example project ./protocols/esp_http_client/

**Comment by mahavirj** [comment]
@pantaluna First part is addressed with https://github.com/espressif/esp-idf/commit/9b0e6e3b49222dd04d81f7e50b68a357fc702156.
