### ISSUE TITLE
esp_https_ota set custom headers

### ISSUE THREAD

**Issue by olegantonyan** [espressif/esp-idf#3097]
Is there a way to add custom header to esp_https_ota request?
From what I see in the source code - no. I have to call `esp_http_client_set_header` before `esp_http_client_open` and there is no way to do so without changing the idf source code. But maybe there's another solution

**Comment by jitin17** [comment]
@olegantonyan This support will be made available in a few weeks. Work to do this and some other features are in progress.

**Comment by olegantonyan** [comment]
Nice! Thanks

**Comment by sidwarkd** [comment]
Was this functionality ever added? If so, where could I find the documentation for it? I have a similar requirement.
