### ISSUE TITLE
FreeRTOS ulRunTimeCounter needed per core (IDFGH-660)

### ISSUE THREAD

**Issue by michprev** [espressif/esp-idf#3098]
## Environment
- IDF version: ed1304146

## Problem Description

Function [uxTaskGetSystemState](https://www.freertos.org/uxTaskGetSystemState.html) can be very useful to get load of the system. It would be nice to see statistics per core (total run time of the the task on a core).

I managed to modify FreeRTOS core to get these statistics. It is needed to tidy vTaskGetRunTimeStats function to work on any number of cores. I am enclosing my diff, feel free to use it / modify it to your needs. It is based on ed1304146.
[stats_per_core.diff.txt](https://github.com/espressif/esp-idf/files/2900816/stats_per_core.diff.txt)

**Comment by sudeep-mohanty** [comment]
Closing this request as it is non-standard and must be made to the upstream FreeRTOS-Kernel [repository](https://github.com/FreeRTOS/FreeRTOS-Kernel).
