### ISSUE TITLE
Integrate ESP Exception Decoder into flasher tool

### ISSUE THREAD

**Issue by forthlightning** [espressif/esp-idf#310]
I realize it's easier said than done but this would make debugging super easy!

**Comment by projectgus** [comment]
It's a very good suggestion, thanks. I have some ideas about doing something like this for esp-idf's `make monitor`, but I haven't had time to work on it yet.

**Comment by forthlightning** [comment]
yes! that is exactly what I was thinking, inline backtraces would be great!. As it is now I go to the arduino IDE and use it from the tools dropdown. I know there is a command line version but I haven't set it up, documentation etc...

**Comment by igrr** [comment]
Has been implemented as part of the new idf_monitor tool.
