### ISSUE TITLE
smart config  reconnected (IDFGH-724)

### ISSUE THREAD

**Issue by myzhang001** [espressif/esp-idf#3147]
我在使用 smart config 时候发现绑定超时后不会 自动连接上一次 保存的 ssid  和 password

**Comment by Alvin1Zhang** [comment]
@TimXia Hi, Tim. Would you help to take a look at this issue? Thanks.

**Comment by TimXia** [comment]
@myzhang001 超时后需要应用层调用 esp_wifi_connect() 去自动连接上一次保存的 ssid。

**Comment by Alvin1Zhang** [comment]
@myzhang001 Hi, has your issue been resolved? Thanks
