### ISSUE TITLE
When will the SBC codec be configurable? (IDFGH-696)

### ISSUE THREAD

**Issue by bootrino** [espressif/esp-idf#3152]
I am using AD2P source to send audio to a bluetooth speaker.

This comment says how to make hard coded changes to the change the SBC codec frequency:

https://github.com/espressif/esp-idf/issues/580#issuecomment-374920448_

When will the IDF include functionality to be able to configure the SBC codec needing to hardcode changes to the IDF?

thanks

**Comment by bootrino** [comment]
Please note I'm using the ADF so I'd like it to be configurable from the ADF thanks.

**Comment by Wth-Esp** [comment]
Hi, @bootrino 

I'm so sorry that we have no plan to implement this now and in the predictable future.
If you really need this, maybe you can raise a PR to do so. ；）

Thanks

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, feel free to reopen.
