### ISSUE TITLE
xEventGroupSetBits and xEventGroupClearBits are used in wifi_event_handler. (IDFGH-704)

### ISSUE THREAD

**Issue by nopnop2002** [espressif/esp-idf#3159]
xEventGroupSetBits and xEventGroupClearBits are used in wifi_event_handler.
Aren't they not xEventGroupSetBits and xEventGroupClearBits, but xEventGroupSetBitsFromISR and xEventGroupClearBitsFromISR?

	static esp_err_t wifi_event_handler(void *ctx, system_event_t *event)
	{
	    switch (event->event_id) {
	        case SYSTEM_EVENT_STA_START:
	            esp_wifi_connect();
	            break;
	        case SYSTEM_EVENT_STA_GOT_IP:
	            xEventGroupSetBits(wifi_event_group, CONNECTED_BIT);

	            break;
	        case SYSTEM_EVENT_STA_DISCONNECTED:
	            esp_wifi_connect();
	            xEventGroupClearBits(wifi_event_group, CONNECTED_BIT);
	            break;
	        default:
	            break;
	    }
	    return ESP_OK;
	}

**Comment by negativekelvin** [comment]
wifi_event_handler doesn't run in isr context

**Comment by nopnop2002** [comment]
Thank you for answer.
OK. 
Please close this issues.

**Comment by Alvin1Zhang** [comment]
Thanks.
