### ISSUE TITLE
Invalid Python invocation on Windows with ESP-IDF 3.3 and CMake (IDFGH-701)

### ISSUE THREAD

**Issue by sysprogs** [espressif/esp-idf#3160]
Trying to build a project based on ESP-IDF 3.3 on Windows using CMake/Ninja triggers an error when invoking Python scripts. This happens because the CMake build files try to invoke the .py files directly. On Windows that would rely on the default system-wide handler for the .py files that is **not** always set to the current ESP-IDF's python executable.

It can be fixed by explicitly invoking ${PYTHON} instead of just the .py file:

**project_include.cmake**:

>add_custom_command(OUTPUT "${IDF_BUILD_ARTIFACTS_DIR}/${unsigned_project_binary}"
>    COMMAND **${PYTHON}** ${ESPTOOLPY} elf2image ${ESPTOOLPY_ELF2IMAGE_FLASH_OPTIONS}
>        -o "${IDF_BUILD_ARTIFACTS_DIR}/${unsigned_project_binary}" "${IDF_PROJECT_EXECUTABLE}"
>    <...>
>    )

**ldgen.cmake**:
>    add_custom_command(
>        OUTPUT ${output}
>        COMMAND **${PYTHON}** ${IDF_PATH}/tools/ldgen/ldgen.py
>        --config    ${SDKCONFIG}
>        <...>
>    )

There might be more instances of this with other custom commands. It would be great if you could update ESP-IDF so Windows users won't have to patch it on their side.

**Comment by projectgus** [comment]
Thanks @sysprogs , will fix. This may be the same root cause as #2936.
