### ISSUE TITLE
aws_iot: difference between ota through https (example in esp-idf) and using mqtt from aws-freertos example (IDFGH-741)

### ISSUE THREAD

**Issue by NgJonesGitHub** [espressif/esp-idf#3178]
Hi,

I would like to OTA from aws iot core. I found there is ota demos in aws-freertos github and esp-idf. What's the difference between them?
Also, is it possible to base on esp-idf to do exactly  the same thing in ota demos of  aws-freertos github?

Jones

**Comment by mahavirj** [comment]
@NgJonesGitHub 

For OTA examples in IDF you may find more information at https://github.com/espressif/esp-idf/tree/master/examples/system/ota

For AFR you may find more information at https://docs.aws.amazon.com/freertos/latest/userguide/freertos-ota-dev.html

Key difference being, in case of AFR, same MQTT connection (used for cloud communication) gets used for OTA as well, however in IDF examples you need separate TLS connection that fetches file over HTTP protocol.

Interim, we recommend esp32.com forum for how-to questions.
