### ISSUE TITLE
Send empty mqtt message to delete retained message. (IDFGH-759)

### ISSUE THREAD

**Issue by Zeni241** [espressif/esp-idf#3186]
How can I send empty mqtt message to broker to delete some retained message?
I tried following but it is not working:
esp_mqtt_client_publish(mqttclient, "mytopic"," ",0, 0, 0);
esp_mqtt_client_publish(mqttclient, "mytopic",NULL,0, 0, 0);
esp_mqtt_client_publish(mqttclient, "mytopic",' ',0, 0, 0);

**Comment by benjaminaigner** [comment]
Short search:
according to http://www.steves-internet-guide.com/mqtt-retained-messages-example/
and https://www.hivemq.com/blog/mqtt-essentials-part-8-retained-messages/

You need to set the retain flag to TRUE and send an empty message.

**Comment by Zeni241** [comment]
Thanks a lot benjaminaigner, I was missing setting retained flag!
Now following deleted retained message on broker:
esp_mqtt_client_publish(mqttclient, "mytopic"," ",0, 0, **1**)

**Comment by benjaminaigner** [comment]
@Zeni241 

I'm glad my hint works :-)
If you are satisfied, please close this issue.
