### ISSUE TITLE
Feature request: make SPIFFS files user available (IDFGH-770)

### ISSUE THREAD

**Issue by michprev** [espressif/esp-idf#3187]
## Environment
- IDF version: v3.1.2
- Build System: Make

## Problem Description

SPIFFS files (located in $IDF_PATH/components/spiffs/spiffs/src) are currently available only to SPIFFS component. It is not possible to include them from user application.

I believe that it would be useful to make SPIFFS API available to user applications with a few changes.

**Comment by pacucha42** [comment]
Closing this task as the internal tracker has been closed long ago
