### ISSUE TITLE
please change phy_init time delta log message to verbose level only (IDFGH-782)

### ISSUE THREAD

**Issue by ecc1** [espressif/esp-idf#3193]
The log message from phy_init.c:100 makes it almost impossible to use DEBUG level log output due the "log spam". Please change its level to verbose.

**Comment by igrr** [comment]
Thanks @ecc1, will consider this. In the meantime you can filter out messages you don't need either from IDF monitor (https://docs.espressif.com/projects/esp-idf/en/latest/api-guides/tools/idf-monitor.html#output-filtering) or from your application using esp_log_level_set function: https://docs.espressif.com/projects/esp-idf/en/latest/api-reference/system/log.html#how-to-use-this-library.
