### ISSUE TITLE
ble, refresh cached attributes (IDFGH-793)

### ISSUE THREAD

**Issue by chegewara** [espressif/esp-idf#3198]
Reading documentations we can see that `esp_ble_gattc_search_service` will request attributes from peer device only when if we dont have this device in cache. There is similar function that is searching services only from cache (`esp_ble_gattc_get_service`). My question is how to refresh attributes from peer device on demand?

https://docs.espressif.com/projects/esp-idf/en/latest/api-reference/bluetooth/esp_gattc.html#_CPPv328esp_ble_gattc_search_service13esp_gatt_if_t8uint16_tP13esp_bt_uuid_t

**Comment by Weijian-Espressif** [comment]
@chegewara, You can call `esp_ble_gattc_cache_refresh(esp_bd_addr_t remote_bda)` to refresh service.
