### ISSUE TITLE
[Wifi APSTA] Fail to connect (STA) while AP on - v3.2-beta3 (IDFGH-805)

### ISSUE THREAD

**Issue by eftimarco** [espressif/esp-idf#3205]
Hello,

Upgrading from 3.1.2-114 to v3.2-beta3 to get http_server, I face a problem I did not get previously.
- Wifi mode is APSTA, AP is working, a telephone is connected to the esp-32.
- I have to test a wifi (ssid - password). This is what I run : 
	wifi_config_t wifi_config_sta;
	strncpy((char *) wifi_config_sta.sta.ssid, ssid_p, WIFI_SSID_MAX);
	strncpy((char *) wifi_config_sta.sta.password, password_p, WIFI_PWD_MAX);
	esp_wifi_set_config(ESP_IF_WIFI_STA, &wifi_config_sta);
	esp_wifi_connect();
I never get neither SYSTEM_EVENT_STA_CONNECTED nor SYSTEM_EVENT_STA_GOT_IP...

The same code was working well on esp-idf 3.1.2-114.

Thanks in advance

**Comment by eftimarco** [comment]
More details on the problem faced :
- Every call get a ESP_OK return 
- I get a SYSTEM_EVENT_STA_DISCONNECTED on the connect, with reason : WIFI_REASON_NO_AP_FOUND
- If I do esp_wifi_stop(), esp_wifi_set_mode(WIFI_MODE_STA), esp_wifi_set_config(ESP_IF_WIFI_STA, &wifi_config) and esp_wifi_start() instead, to test the same wifi (ssid - password) at the same place in code, it is connecting, but telephone connected to esp-32 in AP mode is lost, obviously

**Comment by liuzfesp** [comment]
Hi @eftimarco does this problem exist if wifi_config_sta.sta.scan_method is configured to WIFI_ALL_CHANNEL_SCAN.

**Comment by eftimarco** [comment]
Hi @liuzfesp, 

Same problem (NO_AP_FOUND) with wifi_config_sta.sta.scan_method = WIFI_ALL_CHANNEL_SCAN;

- Other test : Wifi scanning is working well during APSTA mode, when the telephone is connected to esp-32, with that code : 
wifi_scan_config_t scan_config = {
	.ssid = NULL,
	.bssid = NULL,
	.channel = 0,
	.show_hidden = false,
	.scan_type = WIFI_SCAN_TYPE_ACTIVE
};
err = esp_wifi_scan_start(&scan_config, true);
[...]
esp_wifi_scan_get_ap_num(&nb_ap_scaned);
[...]
esp_wifi_scan_get_ap_records(&nb_ap_scaned, wifi_ap_founded);

**Comment by liuzfesp** [comment]
Hi @eftimarco just can't reproduce this issue. Could you let me know the AP type to which the ESP32 is connected?

**Comment by eftimarco** [comment]
@liuzfesp Both the 2 I try to connect to are 802.11n with WPA2-PSK encryption

**Comment by liuzfesp** [comment]
Hi @eftimarco, what I want to know is the vendor name of the AP, for example, the API is TP-LINK TL-WR1043 etc.

**Comment by eftimarco** [comment]
The main one is a tp-link TL-WR802N 
(Second one is an internet box).

**Comment by liuzfesp** [comment]
I just did the test on my TPLINK TL-WR845N, everything looks good. Is it possible for you to write a demo code to produce this issue and paste the demo code here. You can write the demo based on IDF WiFi example, such as $IDF_PATH/examples/wifi/getting_started/station.

**Comment by eftimarco** [comment]
/* WiFi station Example

   This example code is in the Public Domain (or CC0 licensed, at your option.)

   Unless required by applicable law or agreed to in writing, this
   software is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
   CONDITIONS OF ANY KIND, either express or implied.
*/
#include <string.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "freertos/event_groups.h"
#include "esp_system.h"
#include "esp_wifi.h"
#include "esp_event_loop.h"
#include "esp_log.h"
#include "nvs_flash.h"

#include "lwip/err.h"
#include "lwip/sys.h"

/* The examples use WiFi configuration that you can set via 'make menuconfig'.

   If you'd rather not, just change the below entries to strings with
   the config you want - ie #define EXAMPLE_WIFI_SSID "mywifissid"
*/
#define EXAMPLE_ESP_WIFI_SSID      CONFIG_ESP_WIFI_SSID
#define EXAMPLE_ESP_WIFI_PASS      CONFIG_ESP_WIFI_PASSWORD
#define EXAMPLE_ESP_MAXIMUM_RETRY  CONFIG_ESP_MAXIMUM_RETRY

#define EXAMPLE_ESP_WIFI_AP_SSID   "MY_WIFI"
#define EXAMPLE_ESP_WIFI_AP_PASS   "MY_WIFI_PASS"

#define WIFI_SSID_MAX        32
#define WIFI_PWD_MAX         64

/* FreeRTOS event group to signal when we are connected*/
static EventGroupHandle_t s_wifi_event_group;

static system_event_id_t wifi_sta_state = SYSTEM_EVENT_STA_STOP;
static system_event_id_t wifi_ap_state = SYSTEM_EVENT_AP_STOP;

/* The event group allows multiple bits for each event, but we only care about one event 
 * - are we connected to the AP with an IP? */
#define WIFI_CONNECTED_BIT          BIT0
#define WIFI_STOP_BIT               BIT1
#define WIFI_DISCONNECT_DONE_BIT    BIT2
#define WIFI_SCAN_DONE_BIT          BIT3
#define WIFI_PHONE_CONNECTED        BIT4
#define WIFI_AP_STARTED             BIT5

static const char *TAG = "wifi test";

/*
    Associe des actions a chaque changement d'etat du WiFi
*/
static esp_err_t event_handler(void *ctx, system_event_t *event)
{
    switch(event->event_id){

        case SYSTEM_EVENT_WIFI_READY : // Deprecated
        break;

        case SYSTEM_EVENT_SCAN_DONE:
            xEventGroupSetBits(s_wifi_event_group, WIFI_SCAN_DONE_BIT);
            break;

        // STA Part
        case SYSTEM_EVENT_STA_START:
            xEventGroupClearBits(s_wifi_event_group, WIFI_STOP_BIT);
            wifi_sta_state = event->event_id;
            esp_wifi_connect();
            break;

        case SYSTEM_EVENT_STA_STOP:
            xEventGroupSetBits(s_wifi_event_group, WIFI_STOP_BIT);
            wifi_sta_state = event->event_id;
            break;

        case SYSTEM_EVENT_STA_CONNECTED:
            ESP_LOGI(TAG, "SYSTEM_EVENT_STA_CONNECTED");
            wifi_sta_state = event->event_id;
        break;

        case SYSTEM_EVENT_STA_DISCONNECTED: // 
            xEventGroupClearBits(s_wifi_event_group, WIFI_CONNECTED_BIT);
            xEventGroupSetBits(s_wifi_event_group, WIFI_DISCONNECT_DONE_BIT);
            wifi_sta_state = event->event_id;
            ESP_LOGI(TAG, "SYSTEM_EVENT_STA_DISCONNECTED - Disconnection reason : %d\n", event->event_info.disconnected.reason);
            break;

        case SYSTEM_EVENT_STA_GOT_IP:
        case SYSTEM_EVENT_AP_STA_GOT_IP6:
            xEventGroupSetBits(s_wifi_event_group, WIFI_CONNECTED_BIT);
            wifi_sta_state = event->event_id;
            break;
        case SYSTEM_EVENT_STA_LOST_IP:
            // ToDo : reconnect !
            xEventGroupClearBits(s_wifi_event_group, WIFI_CONNECTED_BIT);
            wifi_sta_state = event->event_id;
            break;

        // AP Part
        case SYSTEM_EVENT_AP_START:
            wifi_ap_state = event->event_id;
            //connect_retry = 0;
            xEventGroupSetBits(s_wifi_event_group, WIFI_AP_STARTED);
            break;
        case SYSTEM_EVENT_AP_STOP:
            xEventGroupClearBits(s_wifi_event_group, WIFI_AP_STARTED);
            break;

        case SYSTEM_EVENT_AP_STACONNECTED:
            wifi_ap_state = event->event_id;
            xEventGroupSetBits(s_wifi_event_group, WIFI_PHONE_CONNECTED);
            break;

        case SYSTEM_EVENT_AP_STADISCONNECTED:
            xEventGroupClearBits(s_wifi_event_group, WIFI_PHONE_CONNECTED);
            wifi_ap_state = event->event_id;
            break;

        default:
            break;
    }

    ESP_LOGI(TAG, "Event 0x%X, wifi_sta_state : 0x%X - wifi_ap_state = 0x%X \n", event->event_id, wifi_sta_state, wifi_ap_state);

    return ESP_OK;
}

/*
    Wifi Access Point init
*/
bool WIFI_ap_init()
{
    bool return_value = false;

    ESP_LOGI(TAG, "WIFI_ap_init\n");

    // I tried forcing a virgin config for STA while passing to APSTA mode... same result.
    //wifi_config_t wifi_virgin_config;
    
    wifi_config_t wifi_config = {
        .ap = {
            .ssid = EXAMPLE_ESP_WIFI_AP_SSID,
            .ssid_len = strlen(EXAMPLE_ESP_WIFI_AP_SSID),
            .password = EXAMPLE_ESP_WIFI_AP_PASS, // => if empty : WIFI_AUTH_OPEN
            .authmode = WIFI_AUTH_WPA2_PSK,
            .max_connection = 4,
            .beacon_interval = 100,
            .channel = 5
        }
    };
    if (strlen(EXAMPLE_ESP_WIFI_AP_PASS) == 0) {
        wifi_config.ap.authmode = WIFI_AUTH_OPEN;
    }

    //memset(&wifi_virgin_config, 0, sizeof(wifi_config_t));

    if(esp_wifi_stop() == ESP_OK){
        if( esp_wifi_set_storage(WIFI_STORAGE_RAM) == ESP_OK){
            if(esp_wifi_set_mode(WIFI_MODE_APSTA) == ESP_OK){
                //if( esp_wifi_set_config(ESP_IF_WIFI_STA, &wifi_virgin_config) == ESP_OK){
                    if( esp_wifi_set_config(ESP_IF_WIFI_AP, &wifi_config) == ESP_OK){
                        if( esp_wifi_start() == ESP_OK){
                            return_value = true;
                        }
                        else{
                            ESP_LOGE(TAG, "AP init - Problem in start Wifi");
                        }
                    }
                    else{
                        ESP_LOGE(TAG, "AP init - Problem in set config Wifi AP");
                    }
                //}
                //else{
                //    ESP_LOGE("AP init - Problem in set empty config Wifi STA");
                //}
            }
            else{
                ESP_LOGE(TAG, "AP init - Problem in set mode APSTA");
            }
        }
        else{
            ESP_LOGE(TAG, "AP init - Problem in set storage RAM");
        }
    }
    else{
        ESP_LOGE(TAG, "AP init - Problem in wifi stop");
    }

    return return_value;
}

/*
    Wifi Access Poin Deinit
*/
void WIFI_ap_deinit()
{
    ESP_LOGI(TAG, "WIFI_ap_deinit\n");
    ESP_ERROR_CHECK( esp_wifi_stop() );
}

/*
    Event wifi init
*/
void WIFI_event_init(void)
{
    tcpip_adapter_init();
    ESP_ERROR_CHECK( esp_event_loop_init(event_handler, NULL) );

    ESP_ERROR_CHECK(tcpip_adapter_dhcps_stop(TCPIP_ADAPTER_IF_AP));

    tcpip_adapter_ip_info_t info;
    memset(&info, 0x00, sizeof(info));

    IP4_ADDR(&info.ip, 192, 168, 4, 1);
    IP4_ADDR(&info.gw, 192, 168, 4, 1);
    IP4_ADDR(&info.netmask, 255, 255, 255, 0);
    ESP_ERROR_CHECK(tcpip_adapter_set_ip_info(TCPIP_ADAPTER_IF_AP, &info));

    /* start dhcp server */
    ESP_ERROR_CHECK(tcpip_adapter_dhcps_start(TCPIP_ADAPTER_IF_AP));

    wifi_init_config_t cfg = WIFI_INIT_CONFIG_DEFAULT();
    ESP_ERROR_CHECK( esp_wifi_init(&cfg) );
    s_wifi_event_group = xEventGroupCreate();
}

bool wifi_init_sta()
{
    EventBits_t uxBits;
    wifi_config_t wifi_config;
    bool return_value = false;

    memset(&wifi_config, 0, sizeof(wifi_config_t));

    esp_wifi_stop();
    uxBits = xEventGroupWaitBits(s_wifi_event_group, WIFI_STOP_BIT, pdFALSE, pdFALSE, (300 / portTICK_PERIOD_MS) );

    if(esp_wifi_set_mode(WIFI_MODE_STA) == ESP_OK)
    {
        strncpy((char *) wifi_config.sta.ssid, EXAMPLE_ESP_WIFI_SSID, WIFI_SSID_MAX);
        strncpy((char *) wifi_config.sta.password, EXAMPLE_ESP_WIFI_PASS, WIFI_PWD_MAX);
        if(esp_wifi_set_config(ESP_IF_WIFI_STA, &wifi_config) == ESP_OK){

            xEventGroupClearBits(s_wifi_event_group, WIFI_DISCONNECT_DONE_BIT);
            if(esp_wifi_start() == ESP_OK)
            {
                uxBits = xEventGroupWaitBits(s_wifi_event_group, WIFI_DISCONNECT_DONE_BIT | WIFI_CONNECTED_BIT, pdFALSE, pdFALSE, (8000 / portTICK_PERIOD_MS) );
                if(uxBits & WIFI_DISCONNECT_DONE_BIT)
                {
                    ESP_LOGE(TAG, "Access point not accessible");
                }
                else if(uxBits & WIFI_CONNECTED_BIT )
                {
                    return_value = true;
                }
                else
                {
                    ESP_LOGE(TAG, "Connection to wifi impossible...");
                }
            }
            else
            {
                ESP_LOGI(TAG, "Impossible to start wifi");
            }
        }
        else{
            ESP_LOGI(TAG, "Impossible to set wifi config");
        }
    }
    else
    {
        ESP_LOGI(TAG, "Impossible to change wifi mode");
    }

    return return_value;
}

/*
    Test a wifi 
*/
bool WIFI_test_ssid(char* ssid_p, char* password_p)
{
    EventBits_t uxBits;
    bool return_value = false;
    wifi_config_t wifi_config_sta;

    ESP_LOGI(TAG, "Test du wifi : SSID = '%s' ; password = '%s'\n", ssid_p, password_p);

    // I tried with forcing disconnect first, same result

    // xEventGroupClearBits(s_wifi_event_group, WIFI_DISCONNECT_DONE_BIT);
    // esp_wifi_disconnect();
    // uxBits = xEventGroupWaitBits(s_wifi_event_group, WIFI_DISCONNECT_DONE_BIT, pdFALSE, pdFALSE, (5000 / portTICK_PERIOD_MS) );
    // ESP_LOGI("After disconnection\n");

    strncpy((char *) wifi_config_sta.sta.ssid, ssid_p, WIFI_SSID_MAX);
    strncpy((char *) wifi_config_sta.sta.password, password_p, WIFI_PWD_MAX);
    wifi_config_sta.sta.scan_method = WIFI_ALL_CHANNEL_SCAN;
    if(esp_wifi_set_config(ESP_IF_WIFI_STA, &wifi_config_sta) == ESP_OK){
        if(esp_wifi_connect() == ESP_OK)
        {
            uxBits = xEventGroupWaitBits(s_wifi_event_group, WIFI_CONNECTED_BIT, pdFALSE, pdFALSE, (12000 / portTICK_PERIOD_MS) );
            if(uxBits & WIFI_CONNECTED_BIT)
            {
                return_value = true;
                ESP_LOGI(TAG, "WIFI_test_ssid - wifi test : test ok !");
                xEventGroupClearBits(s_wifi_event_group, WIFI_DISCONNECT_DONE_BIT);
                esp_wifi_disconnect();
                uxBits = xEventGroupWaitBits(s_wifi_event_group, WIFI_DISCONNECT_DONE_BIT, pdFALSE, pdFALSE, (1000 / portTICK_PERIOD_MS) );
            }
            else
            {
                ESP_LOGE(TAG, "Impossible to connect the wifi... (password ?)");
            }
        }
        else
        {
            ESP_LOGI(TAG, "Impossible to connect wifi");
        }
    }
    else
    {
        ESP_LOGI(TAG, "Impossible to set wifi config STA");
    }

    return return_value;
}

void app_main()
{
    EventBits_t uxBits;
    esp_err_t ret = nvs_flash_init();
    if (ret == ESP_ERR_NVS_NO_FREE_PAGES || ret == ESP_ERR_NVS_NEW_VERSION_FOUND) {
      ESP_ERROR_CHECK(nvs_flash_erase());
      ret = nvs_flash_init();
    }
    ESP_ERROR_CHECK(ret);
    
    ESP_LOGI(TAG, "ESP_WIFI_MODE_STA");
    WIFI_event_init();
    // Connecting there to the AP EXAMPLE_ESP_WIFI_SSID, EXAMPLE_ESP_WIFI_PASS in STA MODE works
    //wifi_init_sta(); 
    if(WIFI_ap_init()){
        ESP_LOGI(TAG, "AP INIT Ok - SSID : %s - PASSWORD : %s", EXAMPLE_ESP_WIFI_AP_SSID, EXAMPLE_ESP_WIFI_AP_PASS);
    }
    uxBits = xEventGroupWaitBits(s_wifi_event_group, SYSTEM_EVENT_AP_STACONNECTED, pdTRUE, pdFALSE, (10000 / portTICK_PERIOD_MS) );
    if(uxBits & SYSTEM_EVENT_AP_STACONNECTED){
        ESP_LOGI(TAG, "A device is connected to us (AP mode)");
    }
    else{
        ESP_LOGI(TAG, "We waited 10 sec but no station connect to us (AP mode) - trying connection (STA mode) anyway");
    }
    WIFI_test_ssid(EXAMPLE_ESP_WIFI_SSID, EXAMPLE_ESP_WIFI_PASS);
}

**Comment by eftimarco** [comment]
Here it is :
[station_example_main.txt](https://github.com/espressif/esp-idf/files/2992866/station_example_main.txt)

**Comment by liuzfesp** [comment]
HI @eftimarco， the root cause is because you forget to call memset(&wifi_config_sta, 0, sizeof(wifi_config_sta)) to initialize wifi_config_sta.

BTW, another typepo in app_main() is to wait SYSTEM_EVENT_AP_STACONNECTED, it should be WIFI_PHONE_CONNECTED, anyway I don't think it's a good idea to block the main task before some phones are connected to the ESP32 AP.

**Comment by eftimarco** [comment]
Hello @liuzfesp, 
I tried with the memset : 
```
    memset(&wifi_config_sta, 0, sizeof(wifi_config_sta));
    strncpy((char *) wifi_config_sta.sta.ssid, ssid_p, WIFI_SSID_MAX);
    strncpy((char *) wifi_config_sta.sta.password, password_p, WIFI_PWD_MAX);
    wifi_config_sta.sta.scan_method = WIFI_ALL_CHANNEL_SCAN;
    if(esp_wifi_set_config(ESP_IF_WIFI_STA, &wifi_config_sta) == ESP_OK){
        if(esp_wifi_connect() == ESP_OK)
```

**I still have the same issue** :
```
I (11473) wifi test: Test du wifi : SSID = 'xxx' ; password = 'xxx'
I (14313) wifi test: SYSTEM_EVENT_STA_DISCONNECTED - Disconnection reason : 201
I (14313) wifi test: Event 0x5, wifi_sta_state : 0x5 - wifi_ap_state = 0xD
E (23483) wifi test: Impossible to connect the wifi... (password ?)
```

Right for the mistake SYSTEM_EVENT_AP_STACONNECTED => WIFI_PHONE_CONNECTED !
The blocking was for the example, waiting for the phone to connect, but you're right : we have the same issue if no phone is connected (but the AP configured).
Thank you for your help

**Comment by liuzfesp** [comment]
HI @eftimarco， everything looks good on my side. Please add retry on receiving SYSTEM_EVENT_STA_DISCONNECTED:
static esp_err_t event_handler(void *ctx, system_event_t *event)
{
...
        case SYSTEM_EVENT_STA_DISCONNECTED: //
            xEventGroupClearBits(s_wifi_event_group, WIFI_CONNECTED_BIT);
            xEventGroupSetBits(s_wifi_event_group, WIFI_DISCONNECT_DONE_BIT);
            wifi_sta_state = event->event_id;
            ESP_LOGI(TAG, "SYSTEM_EVENT_STA_DISCONNECTED - Disconnection reason : %d\n", event->event_info.disconnected.reason);
            **_//try again...
            esp_wifi_connect();_**
            break;
...
}

**Comment by eftimarco** [comment]
@liuzfesp First test does not work : 
```
I (14336) wifi test: SYSTEM_EVENT_STA_DISCONNECTED - Disconnection reason : 201
I (14336) wifi test: Event 0x5, wifi_sta_state : 0x5 - wifi_ap_state = 0xD
I (17176) wifi test: SYSTEM_EVENT_STA_DISCONNECTED - Disconnection reason : 201
I (17176) wifi test: Event 0x5, wifi_sta_state : 0x5 - wifi_ap_state = 0xD
I (20016) wifi test: SYSTEM_EVENT_STA_DISCONNECTED - Disconnection reason : 201
I (20016) wifi test: Event 0x5, wifi_sta_state : 0x5 - wifi_ap_state = 0xD
```
I tried unsetting Store phy calibration data in NVS, recompiling and running... same issue...

**Comment by liuzfesp** [comment]
@eftimarco， so it's very strange. Could you double check whether the AP that ESP32 STA tries to connect is correctly configured the SSID and password? Does the AP set to open mode?

**Comment by eftimarco** [comment]
You're right ! The solution was :
```
memset(&wifi_config_sta, 0, sizeof(wifi_config_sta));
```
I had a problem on wifi hub today (that I did not have yesterday) : that solved, it works !
Thanks you @liuzfesp !!!
