### ISSUE TITLE
Separate return type and function name with space in CAN document (IDFGH-809)

### ISSUE THREAD

**Issue by keelung-yang** [espressif/esp-idf#3208]
https://docs.espressif.com/projects/esp-idf/en/latest/api-reference/peripherals/can.html#api-reference

![image](https://user-images.githubusercontent.com/20385450/54655077-7283d580-4afb-11e9-8e30-e3a1607f3787.png)

and so on...

**Comment by keelung-yang** [comment]
The same as in SD document:
![image](https://user-images.githubusercontent.com/20385450/55057558-82278f00-50a4-11e9-9449-8ce5094c5a6c.png)
If I want to copy function name by double click, I got return type and connected funcion name.

IT SO WEIRD why are you always ignore this? 
I'm confused that you tread this such long long time.

**Comment by Dazza0** [comment]
Hi @keelung-yang , thanks for reporting this issue.

I think this may be a HTML/browser rendering issue, as I can only recreate this when using Chrome. A little bit of background, we use Sphinx to auto-generate our web documentation, and Sphinx seems to put non-standard C types such as `esp_err_t`  and function names within HTML `<span>` tags. It seems like Chrome is not does not render any white-space between `<span>` tags.

We'll look into fixing this with a CSS override, and if that doesn't work we can raise this issue with the Sphinx maintainers.
