### ISSUE TITLE
[TW#11595] Clock stretching feature for I2C slave

### ISSUE THREAD

**Issue by devsaurus** [espressif/esp-idf#323]
Related to #189.
While working on slave support for the NodeMCU firmware (WIP at https://github.com/devsaurus/nodemcu-firmware/blob/dev-esp32-i2c_slave/components/modules/i2c_hw_slave.c), I observed that the ESP32 slave responds with invalid data to the master in case the application didn't provide data to the send buffer in time (via `i2c_slave_write_buffer()`).

Does the I2C slave support clock stretching and how can it be enabled to delay a transfer? Specifically for the two cases:
- master reads from slave but slave's TX FIFO is empty
- master writes to slave but slave's RX FIFO is full

**Comment by Spritetm** [comment]
Huh, according to what I can find, the I2C hardware should automatically take care of this. I'll ask the hw dev.

**Comment by FayeY** [comment]
Hi, @devsaurus , I2C does not support HS mode (cannot clock stretching). And if the master allowed frequency and slave allowed frequency are different, the smaller one should be used.

**Comment by devsaurus** [comment]
Thanks for clarifying this point, @FayeY.
