### ISSUE TITLE
Touch driver touch_pad_get_status() returns 1s for inactive channels when above threshold is set, 0 when below threshold is set (IDFGH-895)

### ISSUE THREAD

**Issue by Elijahg** [espressif/esp-idf#3243]
## Environment
- Module or chip used:  ESP32-WROOM-32
- IDF version v3.3-dev-264-g8a69ffc36
- Build System:         Make
- Compiler version: xtensa-esp32-elf-gcc (crosstool-NG crosstool-ng-1.22.0-80-g6c4433a) 5.2.0
- Operating System:     macOS 10.14.4
- Power Supply:         USB

## Problem Description

The touch driver's touch_pad_get_status() function returns zeroes for inactive channels when TOUCH_TRIGGER_BELOW is set, but returns ones for inactive channels when TOUCH_TRIGGER_ABOVE is set.

### Expected Behavior
touch_pad_get_status() should return zeroes for inactive channels when TOUCH_TRIGGER_ABOVE, to be consistent with TOUCH_TRIGGER_BELOW.

### Actual Behavior
touch_pad_get_status() returns ones for inactive channels with TOUCH_TRIGGER_ABOVE set.

### Steps to repropduce

1. Set up several touch channels including channel 0 or 1 (see (#3242)) with ISR attached.
2. Set the thresholds to a reasonable level below the untouched level
3. Set the trigger mode to be below with touch_pad_set_trigger_mode(TOUCH_TRIGGER_BELOW).
4. Touch a button
5. Print the output of touch_pad_get_status()
6. Observe that the bit in the mask from touch_pad_get_status() is 1 only for the activated button

7. Set trigger mode to be above with touch_pad_set_trigger_mode(TOUCH_TRIGGER_ABOVE)
8. Set thresholds to a reasonable level above the touched level
9. Print the output of touch_pad_get_status()
6. Observe that the bits in the mask from touch_pad_get_status() are 1 for inactive channels.

### Code to reproduce this issue

[main.cpp](https://gist.github.com/Elijahg/0fe8788cd89a7e809a9f28879c72ba5c)
[sdkconfig.txt](https://github.com/espressif/esp-idf/files/3032147/sdkconfig.txt)
[touch_pad_interrupt.elf.zip](https://github.com/espressif/esp-idf/files/3032151/touch_pad_interrupt.elf.zip)

**Comment by fuAlex** [comment]
**`touch_pad_get_status`** represents the channel trigger state, the state is 1 when triggered, and the non-trigger state is 0. It has nothing to do with the trigger mode.  
  
Thank you for your suggestion, we will add a more detailed description of this function.
