### ISSUE TITLE
multi_heap.c issue (IDFGH-916)

### ISSUE THREAD

**Issue by Herwey** [espressif/esp-idf#3261]
Hi : 
When I used the demo to see jpg_stream uri in web, it keep running for some time. But the crash down. Is it about the heap malloc, so how to fix it ? Thanks in advance !!!
E (13023) esp_jpg_decode: JPG Decompression Failed! Data format error
E (13023) example:http_jpg: fmt2rgb888 failed
Guru Meditation Error: Core  0 panic'ed (LoadProhibited). Exception was unhandled.
Core 0 register dump:
PC      : 0x4009566b  PS      : 0x00060c33  A0      : 0x80085424  A1      : 0x3ffaf8d0  
0x4009566b: is_free at /home/riki/esp_idf_latest/esp-idf/components/heap/multi_heap.c:380
 (inlined by) multi_heap_malloc_impl at /home/riki/esp_idf_latest/esp-idf/components/heap/multi_heap.c:432

A2      : 0x3ffc6f20  A3      : 0x00000008  A4      : 0x3ffc85b0  A5      : 0x3ffafa7c  
A6      : 0x00000000  A7      : 0x00000001  A8      : 0x00000001  A9      : 0xe0ffd8ff  
A10     : 0x3ffd5a14  A11     : 0x00000000  A12     : 0x3ffd5a18  A13     : 0x3ffc7d6c  
A14     : 0x00000018  A15     : 0x00000000  SAR     : 0x00000000  EXCCAUSE: 0x0000001c  
EXCVADDR: 0xe0ffd8ff  LBEG    : 0x40096ea8  LEND    : 0x40096ed6  LCOUNT  : 0xffffffff

**Comment by igrr** [comment]
Hi @Herwey, this seems to be a heap corruption issue. Most likely an out-of-bounds write has resulted in heap block header to be corrupted. Please follow the steps listed in https://docs.espressif.com/projects/esp-idf/en/latest/api-reference/system/heap_debug.html#heap-corruption-detection to enable heap poisoning, and debug this issue.
