### ISSUE TITLE
Channel State Information (CSI) sig_mode (IDFGH-923)

### ISSUE THREAD

**Issue by kraoa** [espressif/esp-idf#3267]
Hi,
In the CSI call back function, I'm getting frames having sig_mode = 0. This sig_mode = 0 corresponds to 802.11bg (per esp documentation). However I read elsewhere CSI was included in the 802.11 standard only starting at 802.11n which is newer than 802.11bg. So can someone explain why this is happening. Is this is a bug?
Also the CSI results using sig_mode = 1 are quite noisy i.e. the amplitude and phase responses across sub-carriers are not slowly varying but change drastically from one sub-carrier to the next.
I used the toolbox
https://github.com/jonathanmuller/ESP32-gather-channel-state-information-CSI-

and am getting similar results as shown on the above link.
If you compare this with other CSI results acquired using non-esp32 chips , then you get nice results as shown in Figure 3 in
http://www.cs.wm.edu/~yma/files/WiFiSensing_YongsenMa_authorversion.pdf

There are many other papers like the one I showed above in which signal changes slowly across sub carriers.
Karthik

**Comment by TimXia** [comment]
@kraoa CSI is carried by OFDM frame. 11g also uses OFDM. So there is no problem with sig_mode=0. 
For the second question, we will take a look at it.

**Comment by zhangyanjiaoesp** [comment]
@kraoa 
Have you seen the description for the Figure 3 ? I think that is why it is different from the result in https://github.com/jonathanmuller/ESP32-gather-channel-state-information-CSI-.
![image](https://user-images.githubusercontent.com/30309181/97559373-53a82d80-1a18-11eb-9fde-941a7060f91b.png)

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, feel free to reopen.
