### ISSUE TITLE
BLE advertising Bug (IDFGH-925)

### ISSUE THREAD

**Issue by Andy001847** [espressif/esp-idf#3269]
When the esp32 as client and server, use client to receive ble device data, then as a server to advertising some data. It would occur the mistash and do not work any more. The information is "ASSERT_ERR(bt_intcntl_finetgtintmsk_getf() == 1), in ea.c at line 497"

**Comment by Weijian-Espressif** [comment]
@Andy001847, What is the commit id of ESP-IDF ? Could you provide the test log? Thanks.

**Comment by Alvin1Zhang** [comment]
@Andy001847 Hi, would you please help provide commit id of ESP-IDF as well as the test log? Thanks.

**Comment by Alvin1Zhang** [comment]
@Andy001847 Thanks for reporting the issue. Will close this for now due to lack of details. Feel free to reopen and please help provide more details as suggested in the [issue template](https://github.com/espressif/esp-idf/blob/master/docs/issue_template.md). Thanks.
