### ISSUE TITLE
ESP32 support a external PA? (IDFGH-942)

### ISSUE THREAD

**Issue by hdkim** [espressif/esp-idf#3282]
I saw an issue that ESP32 can't support class 1 on [this link](https://github.com/espressif/esp-idf/issues/2011)

I need long range ble for my project.

So I am looking for a way to do it.

I tried to set 7dbm on SDK, it was highest value that ESP32 can support but I think it is not class 1 (20dbm)

So I have found a chipset for external PA ([data sheet](https://www.mouser.com/ds/2/472/SKY66112_11_203225I-1074606.pdf))

Is it possible to apply the chipset(Sky66112) to ESP32? or do you know a better way for it?

Thanks

**Comment by Hubert868** [comment]
did you have any success

**Comment by mhdong** [comment]
Hi @hdkim 
If high transmission power is required, we can provide a libphy that supports high power, so there is no need for external PA.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, feel free to reopen.
