### ISSUE TITLE
500

### ISSUE THREAD

**Issue by krzychb** [espressif/esp-idf#330]
ESP-IDF repository has been avarded 500 :star: 's
Congratulations to Espressif's Team!

![image](https://cloud.githubusercontent.com/assets/12953787/22792039/a34ecf9e-eeeb-11e6-8276-32e5ee61a5fb.png)

**Comment by Spritetm** [comment]
It's already 536 now :) Thanks for the congrats! I'm going to close this issue to keep the issue list clean though.

**Comment by krzychb** [comment]
888 :star: 's yay!
![image](https://user-images.githubusercontent.com/12953787/27855999-d904c2b2-616c-11e7-8563-fb224f6972df.png)

**Comment by krzychb** [comment]
Couldn’t resist
![screenshot from 2017-08-12 15-06-07](https://user-images.githubusercontent.com/12953787/29240949-f48d80de-7f6f-11e7-93f0-746a5fafd94c.png)

**Comment by krzychb** [comment]
1234 :star: 's !
![image](https://user-images.githubusercontent.com/12953787/32122957-ba89786e-bb62-11e7-947c-539a12816097.png)
Congratulations! :clinking_glasses:

**Comment by krzychb** [comment]
Another 1000 :star:'s in 10 months!
![image](https://user-images.githubusercontent.com/12953787/41501876-d2c74ffe-71ac-11e8-8fc2-14b2f4d0f49a.png)

**Comment by krzychb** [comment]
![image](https://user-images.githubusercontent.com/12953787/54071197-ad6b4b00-4269-11e9-85fb-da44796cce7f.png)
Another 1000 :star: 's in 9 months :+1:
