### ISSUE TITLE
Missing information in wifi scan

### ISSUE THREAD

**Issue by lollizze** [espressif/esp-idf#331]
Hi
I noticed that APs with PEAP set as authentication mode is propagating as the enum WIFI_AUTH_MAX, so i can't really distinguish these.
And will it be possible to get Group Cipher and Cipher Suites when scanning?

**Comment by TimXia** [comment]
Good suggestion. We will add a new enum WIFI_AUTH_WPA2_ENTERPRISE to indicate APs with PEAP/TLS/TTLS set as authentication mode. Are Group Cipher and Cipher Suites useful for you?

**Comment by FayeY** [comment]
Hi lollizze, is this problem solved?
