### ISSUE TITLE
How to find out ESP32 Ble transceiver state in BLE mode? (IDFGH-980)

### ISSUE THREAD

**Issue by hdkim** [espressif/esp-idf#3312]
https://github.com/espressif/esp-idf/issues/2853

from this question, The transceiver state in BLE mode is not supported yet from ESP32 sdk.

Do you have any plan to add this API?

**Comment by Alvin1Zhang** [comment]
@hdkim Hi, thanks for reporting the issue, since the issue you opened is same with [#2853](https://github.com/espressif/esp-idf/issues/2853), will close this one and keep [#2853](https://github.com/espressif/esp-idf/issues/2853) open for tracking. Thanks.

**Comment by hdkim** [comment]
Hi, @Alvin1Zhang 

Thank you for respond.

Ok, I will keep track the #2853 issue. please check my question on it.

Thanks
