### ISSUE TITLE
bt_discovery example (IDFGH-982)

### ISSUE THREAD

**Issue by ludo-d** [espressif/esp-idf#3314]
the bt_discovery example doesn't work after running menuconfig and select BR/EDR only in the bleutooth section 
_GENCONFIG

*** Error during update of the configuration._

ps: option listed in README are not valid anymore
Options choose step:
    1. make menuconfig.
    2. enter menuconfig "Component config", choose "Bluetooth"
    3. enter menu Bluetooth, choose "Classic Bluetooth" and do not choose "Release DRAM from Classic BT controller"
    4. choose your options.

**Comment by blueMoodBHD** [comment]
@ludo-d option listed in README are not valid anymore, I will update it later. 
But I enter menuconfig `Component config`, choose `Bluetooth`, choose `Bluetooth controller`, set `Bluetooth controller mode` to `BR/EDR only`. Then it works OK. The version I use is the latest master. What is the version you use?

**Comment by Alvin1Zhang** [comment]
@ludo-d Thanks for reporting the issue. Could you help share which version you are using? Thanks.

**Comment by Alvin1Zhang** [comment]
@ludo-d Thanks for reporting the issue. Could you help share which version you are using? Thanks.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to short of updates, feel free to reopen with more details, thanks.
