### ISSUE TITLE
Allow other make generators in idf.py (IDFGH-1001)

### ISSUE THREAD

**Issue by raldone01** [espressif/esp-idf#3329]
## Environment

- IDF version v3.2
- Build System:         CMake
- Operating System:  Windows

## Problem Description

I want to run idf.py in mintty for the user interface. If idf.py is run in the normal cmd.exe ctrl-a is not working because it selects everything. If I run idf.py in mintty the MSYSTEM environment variable is created forcing me to use MSYS Makefiles.

### Expected Behavior

The -G option should allow any CMake generator.

### Actual Behavior

The -G option shows an error.

### Steps to repropduce

1. open MSYS2 terminal
2. Attempt to use MinGW Makefiles

### Code to reproduce this issue
idf.py:
```
# Make flavors, across the various kinds of Windows environments & POSIX...
if "MSYSTEM" in os.environ:  # MSYS
    MAKE_CMD = "make"
    MAKE_GENERATOR = "MSYS Makefiles"
elif os.name == 'nt':  # other Windows
    MAKE_CMD = "mingw32-make"
    MAKE_GENERATOR = "MinGW Makefiles"
else:
    MAKE_CMD = "make"
    MAKE_GENERATOR = "Unix Makefiles"
```
The above lines show the problem.

## Workaround
I forced the two variables MAKE_CMD and MAKE_GENERATOR to MinGW Makefiles.
Everything is working as expected with MinGW Makefiles although MSYSTEM is defined.

**Comment by dobairoland** [comment]
Hello @raldone01. I'm sorry for the late reply.

If I force to use `mingw32-make` in MSYS then I receive the following error:
```
 $IDF_PATH/tools/idf.py -G "MinGW Makefiles" build
Checking Python dependencies...
Python requirements from C:/Users/Roland/esp/esp-idf/requirements.txt are satisfied.
Running cmake in directory C:/Users/Roland/esp/esp-idf/examples/get-started/hello_world/build
Executing "cmake -G 'MinGW Makefiles' -DPYTHON_DEPS_CHECKED=1 -DESP_PLATFORM=1 --warn-uninitialized C:/Users/Roland/esp/esp-idf/examples/get-started/hell
o_world"...
Warn about uninitialized values.
-- Found Git: C:/msys32/usr/bin/git.exe (found version "2.22.0")
-- IDF_TARGET not set, using default target: esp32
-- Building for target esp32
CMake Error at C:/msys32/mingw32/share/cmake-3.14/Modules/CMakeMinGWFindMake.cmake:12 (message):
  sh.exe was found in your PATH, here:

  C:/msys32/usr/bin/sh.exe

  For MinGW make to work correctly sh.exe must NOT be in your path.

  Run cmake from a shell that does not have sh.exe in your PATH.

  If you want to use a UNIX shell, then use MSYS Makefiles.

Call Stack (most recent call first):
  C:/Users/Roland/esp/esp-idf/tools/cmake/project.cmake:95 (__project)
  CMakeLists.txt:6 (project)


CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_ASM_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
cmake failed with exit code 1
```
I guess that newer `cmake` checks for the existence of `sh.exe` and it fails.

I'm happy that your workaround is fine for you but I don't think this should be "fixed" in IDF because it won't work for everyone. It is intended behavior that `make` is invoked in our MSYS environment. If you have an issue with that then please open a new issue for it.

`idf.py` uses `ninja` by default which is much better (faster) alternative on all platforms. I encourage you to use it in `cmd.exe`  and report any issue you encounter.

> If idf.py is run in the normal cmd.exe ctrl-a is not working because it selects everything.

This has been fixed and accepts "a" as well.
