### ISSUE TITLE
Protocol violation in openssl_server example.

### ISSUE THREAD

**Issue by alexander-sorokin** [espressif/esp-idf#333]
Between responce header and body should be 2 new lines. Now it is only one.
[Here](https://github.com/espressif/esp-idf/blob/master/examples/protocols/openssl_server/main/openssl_server.c#L40):
`                                "Content-Length: 98\r\n" \`
should be
`                                "Content-Length: 98\r\n\r\n" \`

**Comment by projectgus** [comment]
Thanks for reporting this Alexander. A fix for this was contributed in #214, and that fix is now queued for review & merge.
