### ISSUE TITLE
cJSON lib upgarde from 1.7.1 to 1.7.11 (IDFGH-1004)

### ISSUE THREAD

**Issue by no1seman** [espressif/esp-idf#3332]
Hi,

there are some bugs in cJSON 1.7.1 lib included in esp-idf that was fixed by new releases.
The latest one is - 1.7.11. Is it possible to upgrade c JSON lib from 1.7.1 to 1.7.11 in esp-idf?

**Comment by suda-morris** [comment]
Thanks @no1seman we will update the cJSON lib ASAP.
