### ISSUE TITLE
Possible error in idf.py (IDFGH-1005)

### ISSUE THREAD

**Issue by raldone01** [espressif/esp-idf#3333]
## Environment

- IDF version master a20d02b7f196c407bc9f39b781e31a0a4f665968
- Build System:         CMake
- Operating System:  Windows

## Problem
If MinGW Makefiles are used the make executable is called mingw32-make. In the following line the version of the normal make will be printed instead of the mingw32-make version.
https://github.com/espressif/esp-idf/blob/a20d02b7f196c407bc9f39b781e31a0a4f665968/tools/idf.py#L69
## Possible solution
``` python
(MAKE_GENERATOR, [MAKE_CMD, "-j", str(multiprocessing.cpu_count() + 2)], [MAKE_CMD, "--version"], "VERBOSE=1"),
```

**Comment by projectgus** [comment]
Hi @raldone01 ,

Thanks for reporting this. A fix is in internal review and will be merged ASAP.

Angus
