### ISSUE TITLE
missing uuid in esp_gatt_defs.h (IDFGH-1014)

### ISSUE THREAD

**Issue by mohamed-elsabagh** [espressif/esp-idf#3341]
I think you missed Automation IO service UUID 0x1815 https://www.bluetooth.com/specifications/gatt/services I can't find it in file it would be very good if it's added there
Thanks

**Comment by Weijian-Espressif** [comment]
@mohamed-elsabagh ,  I will add it ! Thanks for your reminder.

**Comment by mohamed-elsabagh** [comment]
Thanks so much, I really appreciate your hard work and amazing esp32 keep up the good work
