### ISSUE TITLE
where is esp-idf/examples/protocols/aws_iot ?? (IDFGH-1024)

### ISSUE THREAD

**Issue by wltn928** [espressif/esp-idf#3351]
Hi,
The aws_iot sample disappeared.
Do not support it anymore?

Thanks.

**Comment by mahavirj** [comment]
@wltn928 AWS IoT framework (along with examples) is moved to independent repository at https://github.com/espressif/esp-aws-iot (This is to bring consistency with how we have been maintaining other cloud frameworks like Azure and Google). Thanks.
