### ISSUE TITLE
Feature request: compile-time way to get IDF version components (IDFGH-1032)

### ISSUE THREAD

**Issue by martijnthe** [espressif/esp-idf#3357]
I know there's the `IDF_VER` preprocessor define. But it's a string, so cannot be used in preprocessor conditionals. I would like to have `IDF_VER_MAJOR`, `IDF_VER_MINOR`, `IDF_VER_PATCH`, so that something like this would be possible:

```
#if IDF_VER_MAJOR == 3
#  if IDF_VER_MINOR >= 3
// Code for IDF v3.3.x and above
#  else
// Code for IDF v3.2.x and below
#  endif
#else
#  error "Unsupported IDF version"
#endif
```

I know you can parse the `IDF_VER` string at runtime, but that would drag in all the code paths and bloat the binary size.

**Comment by igrr** [comment]
This is tracked in https://github.com/espressif/esp-idf/issues/2482, please follow the link and click "Subscribe" to receive updates. Closing as duplicate.

**Comment by martijnthe** [comment]
@igrr thanks for pointing out the existing ticket. I’d searched for it but didn’t find it.
