### ISSUE TITLE
spiffs bug (IDFGH-1042)

### ISSUE THREAD

**Issue by Andy001847** [espressif/esp-idf#3367]
Have register file system, Used fseek(file, 0, SEEK_SET), but the file pointer not move file head. It does not work. The frewind function not surpport.

**Comment by Alvin1Zhang** [comment]
@Andy001847 Thanks for reporting the issue. Would you please help provide more details as suggested in the [issue template](https://github.com/espressif/esp-idf/blob/master/docs/issue_template.md)? Thanks.

**Comment by Alvin1Zhang** [comment]
@Andy001847 Hi, will close this issue for the time being, feel free to reopen and please help provide more details suggested in the [issue template](https://github.com/espressif/esp-idf/blob/master/docs/issue_template.md). Thanks.
