### ISSUE TITLE
ESP  loses html requests (IDFGH-1049)

### ISSUE THREAD

**Issue by arnold-b** [espressif/esp-idf#3371]
Hello, 

If there are many File requests over HTML, ESP is losing the requests. 
What can i do to find the problem ?

I´m using 
- ESP-IDF Master
- example https://github.com/espressif/esp-idf/tree/master/examples/protocols/http_server/file_serving
 but i think its not a problem of the sample.

Development: Visual Studio Code

Sometimes the requests are already lost on less files. its randomly 

![image](https://user-images.githubusercontent.com/32824793/56808838-bec8e080-6832-11e9-91bd-a80d9c22c9ff.png)
![image](https://user-images.githubusercontent.com/32824793/56808853-c8524880-6832-11e9-9515-0f3bf8be3644.png)

![image](https://user-images.githubusercontent.com/32824793/56808866-cee0c000-6832-11e9-8ceb-2766f4e8c517.png)

I (8572) tcpip_adapter: sta ip: 192.168.178.111, mask: 255.255.255.0, gw: 192.168.178.1
I (8572) TEST_WIFI: SYSTEM_EVENT_STA_GOT_IP
I (8572) TEST_WIFI: Got IP: '192.168.178.111'
I (8572) [SPIFFS example]: Initializing SNTP
I (8582) [SPIFFS example]: Waiting for system time to be set... (1/10)
I (9592) [SPIFFS example]: System time is set.
I (20872) file_server: /sy.html

I (21052) file_server: Set TYPE ----------------------------------
I (21052) file_server: Compress found /spiffs/sy.html--0

I (21052) file_server: Resp_type =`text/html` 

I (21052) file_server: Sending file : /spiffs/sy.html  (3496 bytes)...
E (21062) file_server: File read 3496
E (21072) file_server: File read 0
I (21072) file_server: File sending complete
I (21102) file_server: /style.css

I (21332) file_server: Set TYPE ----------------------------------
I (21332) file_server: Compress found /spiffs/style.css--0

I (21342) file_server: Resp_type =`text/css` 

I (21342) file_server: Sending file : /spiffs/style.css  (4712 bytes)...
E (21352) file_server: File read 4712
E (21362) file_server: File read 0
I (21362) file_server: File sending complete
I (21372) file_server: /css/bootstrap.css

I (21762) file_server: Set TYPE ----------------------------------
I (21762) file_server: Compress found /spiffs/css/bootstrap.css--1

I (21762) file_server: Resp_type =`text/css` 

I (21772) file_server: Sending file : /spiffs/css/bootstrap.css.gz  (15704 bytes)...
E (21782) file_server: File read 8192
E (21842) file_server: File read 7512
E (21842) file_server: File read 0
I (21842) file_server: File sending complete
I (21852) file_server: /css/menu.css

I (21892) file_server: Set TYPE ----------------------------------
I (21892) file_server: Compress found /spiffs/css/menu.css--0

I (21892) file_server: Resp_type =`text/css` 

I (21892) file_server: Sending file : /spiffs/css/menu.css  (1384 bytes)...
E (21902) file_server: File read 1384
E (21912) file_server: File read 0
I (21912) file_server: File sending complete
I (21922) file_server: /css/tabs.css

I (21932) file_server: Set TYPE ----------------------------------
I (21932) file_server: Compress found /spiffs/css/tabs.css--0

I (21932) file_server: Resp_type =`text/css` 

I (21942) file_server: Sending file : /spiffs/css/tabs.css  (1419 bytes)...
E (21952) file_server: File read 1419
E (21952) file_server: File read 0
I (21962) file_server: File sending complete
I (21962) file_server: /css/modaldlg.css

I (22552) file_server: Set TYPE ----------------------------------
I (22552) file_server: Compress found /spiffs/css/modaldlg.css--0

I (22552) file_server: Resp_type =`text/css` 

I (22562) file_server: Sending file : /spiffs/css/modaldlg.css  (2424 bytes)...
E (22572) file_server: File read 2424
E (22582) file_server: File read 0
I (22582) file_server: File sending complete
I (22592) file_server: /css/wizard.css

I (22602) file_server: Set TYPE ----------------------------------
I (22602) file_server: Compress found /spiffs/css/wizard.css--0

I (22602) file_server: Resp_type =`text/css` 

I (22602) file_server: Sending file : /spiffs/css/wizard.css  (1655 bytes)...
E (22612) file_server: File read 1655
E (22622) file_server: File read 0
I (22622) file_server: File sending complete
I (22632) file_server: /js/SPIFFSdlg.js

I (22802) file_server: Set TYPE ----------------------------------
I (22802) file_server: Compress found /spiffs/js/SPIFFSdlg.js--0

I (22812) file_server: Resp_type =`application/javascript` 

I (22812) file_server: Sending file : /spiffs/js/SPIFFSdlg.js  (9869 bytes)...
E (22832) file_server: File read 8192
E (22842) file_server: File read 1677
E (22852) file_server: File read 0
I (22852) file_server: File sending complete
I (22852) file_server: /js/wizard.js

I (22882) file_server: Set TYPE ----------------------------------
I (22882) file_server: Compress found /spiffs/js/wizard.js--0

I (22882) file_server: Resp_type =`application/javascript` 

I (22892) file_server: Sending file : /spiffs/js/wizard.js  (664 bytes)...
E (22892) file_server: File read 664
E (22902) file_server: File read 0
I (22902) file_server: File sending complete
I (22912) file_server: /js/app.js

I (23062) file_server: Set TYPE ----------------------------------
I (23062) file_server: Compress found /spiffs/js/app.js--0

I (23062) file_server: Resp_type =`application/javascript` 

I (23072) file_server: Sending file : /spiffs/js/app.js  (4752 bytes)...
E (23082) file_server: File read 4752
E (23082) file_server: File read 0
I (23092) file_server: File sending complete
I (23092) file_server: /css/style.css

I (23332) file_server: Set TYPE ----------------------------------
I (23342) file_server: Compress found /spiffs/css/style.css--0

I (23342) file_server: Resp_type =`text/css` 

I (23342) file_server: Sending file : /spiffs/css/style.css  (4542 bytes)...
E (23352) file_server: File read 4542
E (23362) file_server: File read 0
I (23362) file_server: File sending complete
I (23372) file_server: /tools/includes.js

I (23472) file_server: Set TYPE ----------------------------------
I (23472) file_server: Compress found /spiffs/tools/includes.js--0

I (23472) file_server: Resp_type =`application/javascript` 

I (23482) file_server: Sending file : /spiffs/tools/includes.js  (5731 bytes)...
E (23492) file_server: File read 5731
E (23502) file_server: File read 0
I (23502) file_server: File sending complete
I (23502) file_server: /js/http.js

I (23952) file_server: Set TYPE ----------------------------------
I (23952) file_server: Compress found /spiffs/js/http.js--0

I (23952) file_server: Resp_type =`application/javascript` 

I (23962) file_server: Sending file : /spiffs/js/http.js  (3881 bytes)...
E (23972) file_server: File read 3881
E (23972) file_server: File read 0
I (23972) file_server: File sending complete
I (23982) file_server: /js/icons.js

I (24492) file_server: Set TYPE ----------------------------------
I (24502) file_server: Compress found /spiffs/js/icons.js--1

I (24502) file_server: Resp_type =`application/javascript` 

I (24502) file_server: Sending file : /spiffs/js/icons.js.gz  (16732 bytes)...
E (24522) file_server: File read 8192
E (24542) file_server: File read 8192
E (24552) file_server: File read 348
E (24552) file_server: File read 0
I (24552) file_server: File sending complete
I (24822) file_server: /js/camera.js

I (25062) file_server: Set TYPE ----------------------------------
I (25062) file_server: Compress found /spiffs/js/camera.js--0

I (25062) file_server: Resp_type =`application/javascript` 

I (25072) file_server: Sending file : /spiffs/js/camera.js  (3426 bytes)...
E (25082) file_server: File read 3426
E (25092) file_server: File read 0
I (25092) file_server: File sending complete
I (25132) file_server: /js/settings.js

I (25232) file_server: Set TYPE ----------------------------------
I (25232) file_server: Compress found /spiffs/js/settings.js--0

I (25242) file_server: Resp_type =`application/javascript` 

I (25242) file_server: Sending file : /spiffs/js/settings.js  (20373 bytes)...
E (25252) file_server: File read 8192
E (25292) file_server: File read 8192
E (25302) file_server: File read 3989
E (25312) file_server: File read 0
I (25312) file_server: File sending complete
I (25632) file_server: /js/config.js

I (25842) file_server: Set TYPE ----------------------------------
I (25842) file_server: Compress found /spiffs/js/config.js--0

I (25842) file_server: Resp_type =`application/javascript` 

I (25852) file_server: Sending file : /spiffs/js/config.js  (21239 bytes)...
E (25862) file_server: File read 8192
E (25892) file_server: File read 8192
E (25902) file_server: File read 4855
E (25902) file_server: File read 0
I (25902) file_server: File sending complete
I (25922) file_server: /js/tabs.js

I (26212) file_server: Set TYPE ----------------------------------
I (26212) file_server: Compress found /spiffs/js/tabs.js--0

I (26212) file_server: Resp_type =`application/javascript` 

I (26222) file_server: Sending file : /spiffs/js/tabs.js  (526 bytes)...
E (26222) file_server: File read 526
E (26232) file_server: File read 0
I (26232) file_server: File sending complete
I (26512) file_server: /js/alertdlg.js

I (26642) file_server: Set TYPE ----------------------------------
I (26642) file_server: Compress found /spiffs/js/alertdlg.js--0

I (26642) file_server: Resp_type =`application/javascript` 

I (26652) file_server: Sending file : /spiffs/js/alertdlg.js  (377 bytes)...
E (26662) file_server: File read 377
E (26662) file_server: File read 0
I (26672) file_server: File sending complete
I (26992) file_server: /js/confirmdlg.js

I (27002) file_server: Set TYPE ----------------------------------
I (27002) file_server: Compress found /spiffs/js/confirmdlg.js--0

I (27002) file_server: Resp_type =`application/javascript` 

I (27012) file_server: Sending file : /spiffs/js/confirmdlg.js  (382 bytes)...
E (27022) file_server: File read 382
E (27032) file_server: File read 0
I (27032) file_server: File sending complete
I (27302) file_server: /js/logindlg.js

I (27332) file_server: Set TYPE ----------------------------------
I (27332) file_server: Compress found /spiffs/js/logindlg.js--0

I (27332) file_server: Resp_type =`application/javascript` 

I (27342) file_server: Sending file : /spiffs/js/logindlg.js  (4671 bytes)...
E (27352) file_server: File read 4671
E (27362) file_server: File read 0
I (27362) file_server: File sending complete
I (27382) file_server: /js/inputdlg.js

I (27582) file_server: Set TYPE ----------------------------------
I (27582) file_server: Compress found /spiffs/js/inputdlg.js--0

I (27582) file_server: Resp_type =`application/javascript` 

I (27592) file_server: Sending file : /spiffs/js/inputdlg.js  (766 bytes)...
E (27592) file_server: File read 766
E (27602) file_server: File read 0
I (27602) file_server: File sending complete
I (27872) file_server: /js/creditsdlg.js

I (28082) file_server: Set TYPE ----------------------------------
I (28082) file_server: Compress found /spiffs/js/creditsdlg.js--0

I (28082) file_server: Resp_type =`application/javascript` 

I (28092) file_server: Sending file : /spiffs/js/creditsdlg.js  (145 bytes)...
E (28092) file_server: File read 145
E (28102) file_server: File read 0
I (28102) file_server: File sending complete
I (28462) file_server: /js/scanwifidlg.js

I (28502) file_server: Set TYPE ----------------------------------
I (28502) file_server: Compress found /spiffs/js/scanwifidlg.js--0

I (28512) file_server: Resp_type =`application/javascript` 

I (28512) file_server: Sending file : /spiffs/js/scanwifidlg.js  (4554 bytes)...
E (28522) file_server: File read 4554
E (28532) file_server: File read 0
I (28532) file_server: File sending complete
I (28562) file_server: /js/connectdlg.js

I (28712) file_server: Set TYPE ----------------------------------
I (28712) file_server: Compress found /spiffs/js/connectdlg.js--0

I (28712) file_server: Resp_type =`application/javascript` 

I (28722) file_server: Sending file : /spiffs/js/connectdlg.js  (3328 bytes)...
E (28732) file_server: File read 3328
E (28732) file_server: File read 0
I (28742) file_server: File sending complete
I (28752) file_server: /js/restartdlg.js

I (28912) file_server: Set TYPE ----------------------------------
I (28912) file_server: Compress found /spiffs/js/restartdlg.js--0

I (28912) file_server: Resp_type =`application/javascript` 

I (28922) file_server: Sending file : /spiffs/js/restartdlg.js  (1339 bytes)...
E (28932) file_server: File read 1339
E (28932) file_server: File read 0
I (28932) file_server: File sending complete

after this no more request

[sdkconfig.zip](https://github.com/espressif/esp-idf/files/3121362/sdkconfig.zip)

**Comment by anurag-kar** [comment]
@arnold-b  Try increasing `backlog_conn` config option (default 5) in httpd_config_t structure passed to httpd_start()

```
httpd_handle_t server = NULL;
    httpd_config_t config = HTTPD_DEFAULT_CONFIG();
    config.uri_match_fn = httpd_uri_match_wildcard;
    config.backlog_conn = 10;

    ESP_LOGI(TAG, "Starting HTTP Server");
    if (httpd_start(&server, &config) != ESP_OK) {
        ESP_LOGE(TAG, "Failed to start file server!");
        return ESP_FAIL;
    }
```

**Comment by arnold-b** [comment]
OK, thanks

**Comment by arnold-b** [comment]
I´m just now on the way to change on compression and reduce the files. Its faster to load less files even they are bigger. I will test this in 3 hours

**Comment by arnold-b** [comment]
Hello anurag-kar,
i tried 
config.backlog_conn = 10 
and
config.backlog_conn = 20;

both made no change on this. 

How could i debug where the requests are lost

httpd_handle_t server = NULL;
    httpd_config_t config = HTTPD_DEFAULT_CONFIG();

    /* Use the URI wildcard matching function in order to
     * allow the same handler to respond to multiple different
     * target URIs which match the wildcard scheme */
    config.uri_match_fn = httpd_uri_match_wildcard;
    config.backlog_conn = 20;

    ESP_LOGI(TAG_FILESERVER, "Starting HTTP Server");
    if (httpd_start(&server, &config) != ESP_OK) {
        ESP_LOGE(TAG_FILESERVER, "Failed to start file server!");
        return ESP_FAIL;
    }

**Comment by anurag-kar** [comment]
From the log it seems that requests are not even reaching the server. Could
you use wireshark to log the traffic between the device and the host?

**Comment by arnold-b** [comment]
I checked with Wireshark.

You are right. The requests stoped. After i increased the timeout in IE it worked. Its just to slow.
Now in IE it works. in CHrome i don´t find how to increase the Timeout

**Comment by anurag-kar** [comment]
It seems you need to improve your client side JS implementation to limit the number of HTTP GET requests that can be sent at a time. Also handle situations when socket creation fails due to timeout, without changing your default browser settings.

**Comment by arnold-b** [comment]
Hey, 
thats i know. But for me it was a good testing to get on the limits. And it´s more easy during testing. 
For later it will be just 4 or 5 files per load.
