### ISSUE TITLE
documentation or implementation error: httpd_req_get_url_query_str (IDFGH-1052)

### ISSUE THREAD

**Issue by dannybackx** [espressif/esp-idf#3374]
## Environment

- IDF version : 3.2

## Problem Description

The documentation on httpd_req_get_url_query_str specifies how to deal with the buffer and buflen. Spefically : 

> - If output size is greater than input, then the value is truncated, accompanied by truncation error as return value
> - Use httpd_req_get_url_query_len() to know the right buffer length
> 

This is misleading. For meaningful results, you should not use the return value of httpd_req_get_url_query_len() but one more (to accomodate for the 0 terminator of the string).

The documentation should include such a remark. Note that the examples do take this into account, in a slightly strange way.

**Comment by anurag-kar** [comment]
@dannybackx Thanks for pointing out.

It should read
```
Use httpd_req_get_url_query_len() + 1 to know the right buffer length
```
or 

```
Use httpd_req_get_url_query_len() to know the query string length
```
