### ISSUE TITLE
请问什么时候mesh模块可以合并到master上？ (IDFGH-1057)

### ISSUE THREAD

**Issue by xiaodingding** [espressif/esp-idf#3379]
请问什么时候mesh模块可以合并到master上？

**Comment by Alvin1Zhang** [comment]
@xiaodingding Thanks for reporting the issue. Would you please help provide more details as suggested in the [issue template](https://github.com/espressif/esp-idf/blob/master/docs/issue_template.md)? Thanks.

**Comment by Alvin1Zhang** [comment]
@xiaodingding Thanks for reporting the issue. Would you please help provide more details as suggested in the [issue template](https://github.com/espressif/esp-idf/blob/master/docs/issue_template.md)? Thanks.

**Comment by Alvin1Zhang** [comment]
@xiaodingding Feel free to reopen the issue, but please help provide more details, thanks.
