### ISSUE TITLE
[TW#12203] Each install/assign/...  for drivers should have a matching uninstall/unassign/...

### ISSUE THREAD

**Issue by jumjum123** [espressif/esp-idf#338]
For each kind of config/install/assign/enable/create/....
we should have a matching function to reset/uninstall/unassign/disable/delete/....

Similar functions like config, assign, etc, should have similiar naming.

**Comment by FayeY** [comment]
Hi @jumjum123 , thanks for your valuable advice! This feature should have been added in the latest IDF. If it is not, please feel free to reopen this issue. Thanks.
