### ISSUE TITLE
esp32 wifi data frame unreadable by phone (IDFGH-1065)

### ISSUE THREAD

**Issue by tek145** [espressif/esp-idf#3386]
I have to develop an esp32 wifi mesh network,but using esp32's sta+ap mode both.phone is unable to read/decode the original data or unable to connect to internet,please do give any solution.
note-esp32 wifi mesh network(in sta+ap mode)

**Comment by liuzfesp** [comment]
Hi @tek145, sorry for late response, could you describe your problem in more detailed.

**Comment by Alvin1Zhang** [comment]
@tek145 Thanks for reporting the issue. Would you please help provide more details as suggested in the [issue template](https://github.com/espressif/esp-idf/blob/master/docs/issue_template.md)? Information like elf, sdk configuration, backtrace, log outputs, commit ID, hardware and etc. would help us debug further. Thanks.

**Comment by dongdong004** [comment]
Did you mean this issue?
When esp32 in mesh mode, the AP didn't allow non-mesh stations to be connected.
https://github.com/espressif/esp-mdf/issues/43

**Comment by Alvin1Zhang** [comment]
@tek145 Thanks for reporting. Will close due to short of details and feedback, feel free to reopen with more details provided. Thanks.
