### ISSUE TITLE
Latest Master as of 04/29/19 - SPI_MASTER broke cant compile (IDFGH-1066)

### ISSUE THREAD

**Issue by filzek** [espressif/esp-idf#3387]
Hi,

The master update as of  04/29/19 - SPI_MASTER is broke and cant compile

spi_master.c:331:57: error: invalid operands to binary == (have 'struct <anonymous>' and 'void *')
         SPI_CHECK(atomic_load(&spihost[host]->device[x])==NULL, "not all CSses freed", ESP_ERR_INVALID_STATE);

********
and a lot of more errors in same file.

also, doing a make clean, and make will return a final error ldgen_libraries esp32

SDK is complete broken now.

**Comment by sbela** [comment]
I have the same issue with the current version from the git repository

**Comment by ammaree** [comment]
+1 same problem

**Comment by bigbigblue** [comment]
+1 same problem

**Comment by pjalocha** [comment]
+1 same problem

**Comment by ammaree** [comment]
This issue is solved by the patch in #3394 
Thanks

**Comment by ginkgm** [comment]
the fix has been merged into master now, could you have a try? @ammaree

**Comment by ginkgm** [comment]
and also @filzek  @sbela

**Comment by filzek** [comment]
It’s fixed!
