### ISSUE TITLE
esp-idf如何编译自己新建目录中的程序 (IDFGH-1067)

### ISSUE THREAD

**Issue by gufeng224** [espressif/esp-idf#3388]
我想在自己新建的工程目录中，新建vendorapi目录，然后编译里面的程序，应该怎么操作？麻烦帮忙解答一下，谢谢了

**Comment by Alvin1Zhang** [comment]
@gufeng224 Thanks for reporting the issue. Would you please help provide more details as suggested in the [issue template](https://github.com/espressif/esp-idf/blob/master/docs/issue_template.md)? Thanks.

**Comment by huming2207** [comment]
@gufeng224 Please ask this kind of general questions in the forum, not here. Meanwhile, this is GitHub and there are tons of users who can't read Chinese natively. So please do ask your question in English.

In the CMake build system can either try creating your component or put your `vendorapi` to your main component, then add something like this in the main component's CMakeList:

```cmake
file(GLOB_RECURSE VENDOR_API_SOURCES "vendorapi/*.cpp" "vendorapi/include/*.hpp")
file(GLOB_RECURSE VENDOR_API_INCLUDES LIST_DIRECTORIES true "vendorapi/include")

...
...

set(COMPONENT_SRCS "project_main.cpp" ${VENDOR_API_SOURCES})
set(COMPONENT_ADD_INCLUDEDIRS "" ${VENDOR_API_INCLUDES })
register_component()
```

Or alternatively, add your source files one by one to your `COMPONENT_SRCS` instead.
