### ISSUE TITLE
spiffsgen.py incorrect path delimiter on windows (IDFGH-1095)

### ISSUE THREAD

**Issue by vetaldudnik** [espressif/esp-idf#3416]
## Problem Description

spiffsgen.py generates spiffs image with incorrect path delimiters on windows

### Expected Behavior

Expected filename in spiffs filesystem is /spiffs/path/to/file.jpg

### Actual Behavior

Actual filename is /spiffs\path\to\file.jpg

**Comment by renzbagaporo** [comment]
Thanks for reporting this issue @vetaldudnik! A fix for this has been submitted to our internal repo. In the meantime, you can use the patch:

[0001-spiffs-fix-path-issue-with-using-spiffsgen-on-Window.patch.zip](https://github.com/espressif/esp-idf/files/3145105/0001-spiffs-fix-path-issue-with-using-spiffsgen-on-Window.patch.zip)

**Comment by renzbagaporo** [comment]
Sorry, didn't notice the associated PR for this issue. Will be happy to accept that instead! :smile:

**Comment by Alvin1Zhang** [comment]
@vetaldudnik Thanks for reporting. Feel free to reopen if the issue still happens. Thanks.
