### ISSUE TITLE
What is the cpu type for each core (IDFGH-1109)

### ISSUE THREAD

**Issue by Herwey** [espressif/esp-idf#3430]
Hi:
Esp32 has two cores, so what is the type cpu for each core ?
Thanks !

**Comment by negativekelvin** [comment]
> 1.4.1 CPU and Memory
> • Xtensa® single-/dual-core 32-bit LX6 microprocessor(s), up to 600 MIPS (200 MIPS for ESP32-S0WD, 400
> MIPS for ESP32-D2WD)
> • 448 kB ROM
> • 520 kB SRAM
> • 16 kB SRAM in RTC

Read the datasheet

**Comment by Alvin1Zhang** [comment]
Thanks for reporting the issue. Would you please help provide more details as suggested in the [issue template](https://github.com/espressif/esp-idf/blob/master/docs/issue_template.md)? Thanks.

**Comment by Herwey** [comment]
@negativekelvin emm... The datasheet shows the cpu type ? which line is ? include two cores?

**Comment by igrr** [comment]
@Herwey This issue tracker is for bug reports and feature requests related to the ESP-IDF. For general questions about the ESP32, please use esp32.com forum or use the support page on espressif.com website. For hardware documentation related requests (such as Datasheet or TRM), you can also use this forum topic: https://esp32.com/viewtopic.php?f=5&t=905.

(At the same time, @negativekelvin gave the answer: both cores are Xtensa LX6 cores, [identically configured](https://github.com/espressif/esp-idf/blob/master/components/xtensa/esp32/include/xtensa/config/core-isa.h)).

**Comment by negativekelvin** [comment]
Wikipedia shows it too https://en.wikipedia.org/wiki/ESP32
