### ISSUE TITLE
esp_efuse_fields.c: unused variable 'r' (IDFGH-1114)

### ISSUE THREAD

**Issue by vetaldudnik** [espressif/esp-idf#3432]
## Environment

- IDF version: v4.0-dev-483-g6187c58d0
- Build System: Make
- Compiler version: 1.22.0-80-g6c4433a5
- Operating System: Windows 10

## Problem Description

`D:/workspaces/esp_workspace/esp-idf/components/efuse/src/esp_efuse_fields.c:106:19: warning: unused variable 'r' [-Wunused-variable]`

When disabled assertion level in menuconfig

**Comment by mosazahany** [comment]
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-variable"

**Comment by mosazahany** [comment]
i replace push line and error fixed#pragma GCC diagnostic ignored "-Wunused-variable"
#pragma GCC diagnostic push
