### ISSUE TITLE
esp32 可以一边播放一遍录音吗？ (IDFGH-1115)

### ISSUE THREAD

**Issue by gufeng224** [espressif/esp-idf#3433]
请问如何在esp32中实现一遍播放，一遍录音？

**Comment by redchenjs** [comment]
一个task播放，另一个task录音，互不干扰，或者用个while(1)循环同样可以实现

**Comment by gufeng224** [comment]
您好，我是rokid的工程师，目前我们使用esp32做相关的应用。麻烦一边录音，一边播放的例程有吗 ？
------------------------------------------------------



谷丰
153823360089
feng.gu@rokid.com
杭州市西湖区西溪壹号22号楼

**Comment by redchenjs** [comment]
@gufeng224 抱歉，开发环境暂时不在身边，但esp-idf中确实没有同时录放音的i2s样例，建议参考一下esp-adf，里面有很多音频场景的样例，比如这个音频透传的example：https://github.com/espressif/esp-adf/tree/master/examples/audio_processing/pipeline_passthru，原理上是一样的
