### ISSUE TITLE
使用rtos创建任务出现内存泄漏的问题 (IDFGH-1123)

### ISSUE THREAD

**Issue by gufeng224** [espressif/esp-idf#3440]
void blink_task(void *pvParameter)
{
		gpio_pad_select_gpio(BLINK_GPIO);
		gpio_set_direction(BLINK_GPIO, GPIO_MODE_OUTPUT);
		while(1) {
			gpio_set_level(BLINK_GPIO, 0);
			vTaskDelay(1000 / portTICK_PERIOD_MS);
			gpio_set_level(BLINK_GPIO, 1);
			vTaskDelay(1000 / portTICK_PERIOD_MS);
		}

}
void uart_task(void *pvParameter)
{
 static  int i =0;
  while(1)
  {
    printf("hello world11111\n");
	printf("hello world22222 %d\n",i);
	vTaskDelay(1000 / portTICK_PERIOD_MS);
  }
}
void app_main()
{
    
	xTaskCreate(&blink_task,"blink_task",configMINIMAL_STACK_SIZE,NULL,4,NULL);
	xTaskCreate(&uart_task,"uart_task",configMINIMAL_STACK_SIZE,NULL,5,NULL);
}

程序如上所示，当创建两个任务后，程序会启动不起来。打印信息中看到的现象就是循环重启；麻烦帮忙看看，谢谢了。

**Comment by igrr** [comment]
You might need to increase the stack size of your tasks. `configMINIMAL_STACK_SIZE` is not sufficient for `printf` function. Try to set the stack size to at least 2048. In general, it is better to set the stack size to a higher value, initially, get the program to work, and then optimize the stack size if necessary.
