### ISSUE TITLE
如何在程序中创建2个rtos任务 (IDFGH-1124)

### ISSUE THREAD

**Issue by gufeng224** [espressif/esp-idf#3441]
esp32有没有例程，如何创建任务？

**Comment by igrr** [comment]
It seems (from #3440) that you are already familiar with [xTaskCreate](https://www.freertos.org/a00125.html) function. Aside from it, there are some additional APIs to create tasks pinned to a specific CPU (xTaskCreatePinnedToCore), see https://docs.espressif.com/projects/esp-idf/en/latest/api-guides/freertos-smp.html#tasks-and-task-creation.
