### ISSUE TITLE
Can't recive Broadcast message by lwip_recvfrom (IDFGH-1129)

### ISSUE THREAD

**Issue by nopnop2002** [espressif/esp-idf#3445]
My Environment:

	freeRTOS version:V8.2.0
	NEWLIB version:2.2.0
	lwIP version:2-0-3-255
	ESP-IDF version:v4.0-dev-311-g70eda3d22-dirty

	$ git describe --tags
	v4.0-dev-311-g70eda3d22

Problem Description:
Can't recive Broadcast message by lwip_recvfrom

Transmitter Side Source:
Transmitting is sending broadcast UDP every 500Tick.

	#include <string.h>
	#include "freertos/FreeRTOS.h"
	#include "freertos/task.h"
	#include "freertos/event_groups.h"
	#include "esp_system.h"
	#include "esp_wifi.h"
	#include "esp_event_loop.h"
	#include "esp_log.h"
	#include "nvs_flash.h"

	#include "lwip/err.h"
	#include "lwip/sockets.h"
	#include "lwip/sys.h"
	#include "lwip/netdb.h"
	#include "lwip/dns.h"

	/* The examples use WiFi configuration that you can set via 'make menuconfig'.

	   If you'd rather not, just change the below entries to strings with
	   the config you want - ie #define EXAMPLE_WIFI_SSID "mywifissid"
	*/
	#define EXAMPLE_ESP_WIFI_SSID      CONFIG_ESP_WIFI_SSID
	#define EXAMPLE_ESP_WIFI_PASS      CONFIG_ESP_WIFI_PASSWORD
	#define EXAMPLE_MAX_STA_CONN       CONFIG_MAX_STA_CONN

	#define UDP_PORT 9876

	QueueHandle_t xQueue;
	TimerHandle_t timerHandle;
	//static EventGroupHandle_t s_wifi_event_group;

	UBaseType_t uxQueueLength = 10;
	UBaseType_t uxItemSize = 64;

	static const char *TAG = "wifi softAP";

	// Timer call back
	static void timer_cb(TimerHandle_t xTimer)
	{
	    char buffer[uxItemSize];
	    TickType_t nowTick;
	    nowTick = xTaskGetTickCount();
	    ESP_LOGI(pcTaskGetTaskName(0),"Start");
	    sprintf(buffer,"Hello World!! %d",nowTick);
	    xQueueSend(xQueue, &buffer, 0);
	}

	// Bradcast Task
	void BroadSend(void *pvParameters)
	{
	  ESP_LOGI(pcTaskGetTaskName(0),"Start");

	  /* set up address to connect to */
	  struct sockaddr_in addr;
	  memset(&addr, 0, sizeof(addr));
	  addr.sin_family = AF_INET;
	  addr.sin_port = htons(UDP_PORT);
	  addr.sin_addr.s_addr = htonl(INADDR_BROADCAST); /* send message to 255.255.255.255 */

	  /* create the socket */
	  int fd;
	  int ret;
	  fd = lwip_socket(AF_INET, SOCK_DGRAM, IPPROTO_UDP ); // Create a UDP socket.
	  LWIP_ASSERT("fd >= 0", fd >= 0);

	  char buffer[uxItemSize];
	  int buflen;
	  while(1) {
	    if(xQueueReceive(xQueue, &buffer, portMAX_DELAY)) {
	       ESP_LOGI(pcTaskGetTaskName(0),"buffer=[%s]",buffer);
	       buflen = strlen(buffer);
	       ret = lwip_sendto(fd, buffer, buflen, 0, (struct sockaddr *)&addr, sizeof(addr));
	       LWIP_ASSERT("ret == buflen", ret == buflen);
	       ESP_LOGI(pcTaskGetTaskName(0),"lwip_sendto ret=%d",ret);
	    } else {
	       ESP_LOGI(pcTaskGetTaskName(0),"xQueueReceive fail");
	       break;
	    }
	  }

	  /* close */
	  ret = lwip_close(fd);
	  LWIP_ASSERT("ret == 0", ret == 0);
	  vTaskDelete( NULL );

	}
	static esp_err_t event_handler(void *ctx, system_event_t *event)
	{
	    switch(event->event_id) {
	    case SYSTEM_EVENT_AP_STACONNECTED:
	        ESP_LOGI(TAG, "station:"MACSTR" join, AID=%d",
	                 MAC2STR(event->event_info.sta_connected.mac),
	                 event->event_info.sta_connected.aid);
	                // Start timer
	        if (xTimerStart(timerHandle, 0) != pdPASS) {
	          ESP_LOGI(pcTaskGetTaskName(0),"Unable to start Timer ...");
	        } else {
	          ESP_LOGI(pcTaskGetTaskName(0),"Success to start Timer ...");
	        }
	        break;
	    case SYSTEM_EVENT_AP_STADISCONNECTED:
	        ESP_LOGI(TAG, "station:"MACSTR"leave, AID=%d",
	                 MAC2STR(event->event_info.sta_disconnected.mac),
	                 event->event_info.sta_disconnected.aid);
	                // Stop timer
	        if (xTimerStop(timerHandle, 0) != pdPASS) {
	          ESP_LOGI(pcTaskGetTaskName(0),"Unable to stop Timer ...");
	        } else {
	          ESP_LOGI(pcTaskGetTaskName(0),"Success to stop Timer ...");
	        }
	        break;
	    default:
	        break;
	    }
	    return ESP_OK;
	}

	void wifi_init_softap()
	{
	    //s_wifi_event_group = xEventGroupCreate();

	    tcpip_adapter_init();
	    ESP_ERROR_CHECK(esp_event_loop_init(event_handler, NULL));

	    wifi_init_config_t cfg = WIFI_INIT_CONFIG_DEFAULT();
	    ESP_ERROR_CHECK(esp_wifi_init(&cfg));
	    wifi_config_t wifi_config = {
	        .ap = {
	            .ssid = EXAMPLE_ESP_WIFI_SSID,
	            .ssid_len = strlen(EXAMPLE_ESP_WIFI_SSID),
	            .password = EXAMPLE_ESP_WIFI_PASS,
	            .max_connection = EXAMPLE_MAX_STA_CONN,
	            .authmode = WIFI_AUTH_WPA_WPA2_PSK
	        },
	    };
	    if (strlen(EXAMPLE_ESP_WIFI_PASS) == 0) {
	        wifi_config.ap.authmode = WIFI_AUTH_OPEN;
	    }

	    ESP_ERROR_CHECK(esp_wifi_set_mode(WIFI_MODE_AP));
	    ESP_ERROR_CHECK(esp_wifi_set_config(ESP_IF_WIFI_AP, &wifi_config));
	    ESP_ERROR_CHECK(esp_wifi_start());

	    ESP_LOGI(TAG, "wifi_init_softap finished.SSID:%s password:%s",
	             EXAMPLE_ESP_WIFI_SSID, EXAMPLE_ESP_WIFI_PASS);
	}

	void app_main()
	{
	    //Initialize NVS
	    esp_err_t ret = nvs_flash_init();
	    if (ret == ESP_ERR_NVS_NO_FREE_PAGES || ret == ESP_ERR_NVS_NEW_VERSION_FOUND) {
	      ESP_ERROR_CHECK(nvs_flash_erase());
	      ret = nvs_flash_init();
	    }
	    ESP_ERROR_CHECK(ret);

	    /* Create Queue */
	    xQueue = xQueueCreate(uxQueueLength, uxItemSize);
	    /* Check everything was created. */
	    configASSERT( xQueue );

	    // Create Timer
	    timerHandle = xTimerCreate("Trigger", 5000/portTICK_PERIOD_MS, pdTRUE, NULL, timer_cb);
	    configASSERT( timerHandle );

	    ESP_LOGI(TAG, "ESP_WIFI_MODE_AP");
	    wifi_init_softap();

	    // Create Task
	    xTaskCreate(BroadSend, "BroadSend", 2048, NULL, 2, NULL);
	}

Receiver Side Source:
Receiver receive all UDP data from tramsmitter.

	#include <string.h>
	#include "freertos/FreeRTOS.h"
	#include "freertos/task.h"
	#include "freertos/event_groups.h"
	#include "esp_system.h"
	#include "esp_wifi.h"
	#include "esp_event_loop.h"
	#include "esp_log.h"
	#include "nvs_flash.h"

	#include "lwip/err.h"
	#include "lwip/sockets.h"
	#include "lwip/sys.h"
	#include "lwip/netdb.h"
	#include "lwip/dns.h"

	/* The examples use WiFi configuration that you can set via 'make menuconfig'.

	   If you'd rather not, just change the below entries to strings with
	   the config you want - ie #define EXAMPLE_WIFI_SSID "mywifissid"
	*/
	#define EXAMPLE_ESP_WIFI_SSID      CONFIG_ESP_WIFI_SSID
	#define EXAMPLE_ESP_WIFI_PASS      CONFIG_ESP_WIFI_PASSWORD
	#define EXAMPLE_ESP_MAXIMUM_RETRY  CONFIG_ESP_MAXIMUM_RETRY

	#define UDP_PORT 9876

	/* FreeRTOS event group to signal when we are connected*/
	static EventGroupHandle_t xEventGroup;

	/* The event group allows multiple bits for each event, but we only care about one event
	 * - are we connected to the AP with an IP? */
	const int WIFI_CONNECTED_BIT = BIT0;

	static const char *TAG = "wifi station";

	static int s_retry_num = 0;

	// Bradcast Receive Task
	void BroadRead(void *pvParameters)
	{
	  ESP_LOGI(pcTaskGetTaskName(0),"Start");

	  EventBits_t uxBits;
	  while(1) {
	    /* Wait forever for either bit 0 or bit 4 to be set within the event group.
	       Clear the bits before exiting. */
	    uxBits = xEventGroupWaitBits( xEventGroup,
	            WIFI_CONNECTED_BIT,                    /* The bits within the event group to wait for. */
	            pdTRUE,        /* BIT_0 should be cleared before returning. */
	            pdFALSE,       /* Don't wait for both bits, either bit will do. */
	            portMAX_DELAY);/* Wait forever. */
	    if ( ( uxBits & WIFI_CONNECTED_BIT ) == WIFI_CONNECTED_BIT ) {
	      ESP_LOGI(pcTaskGetTaskName(0),"xEventGroupWaitBits WIFI_CONNECTED_BIT");
	      break;
	    }
	    vTaskDelay(1);
	  }

	  /* create the socket */
	  int fd;
	  int ret;
	  fd = lwip_socket(AF_INET, SOCK_DGRAM, IPPROTO_UDP ); // Create a UDP socket.
	  ESP_LOGI(pcTaskGetTaskName(0),"socket fd=%d",fd);
	  LWIP_ASSERT("fd >= 0", fd >= 0);

	#if 0
	  /* set option */
	  int broadcast=1;
	  ret = lwip_setsockopt(fd, SOL_SOCKET, SO_BROADCAST, &broadcast, sizeof(broadcast));
	  LWIP_ASSERT("ret >= 0", ret >= 0);
	#endif

	  /* set up address to recvfrom */
	  struct sockaddr_in addr;
	  memset(&addr, 0, sizeof(addr));
	  addr.sin_family = AF_INET;
	  addr.sin_port = htons(UDP_PORT);
	  addr.sin_addr.s_addr = htonl(INADDR_ANY); /* senderInfo message from ANY */
	  //addr.sin_addr.s_addr = INADDR_ANY; /* senderInfo message from ANY */

	  /* bind socket */
	  ret = lwip_bind(fd, (struct sockaddr *)&addr, sizeof(addr));
	  LWIP_ASSERT("ret >= 0", ret >= 0);

	  /* senderInfo data */
	  char buffer[64];
	  struct sockaddr_in senderInfo;
	  char senderstr[16];
	  while(1) {
	    memset(&senderInfo, 0, sizeof(senderInfo));
	    socklen_t senderInfoLen = sizeof(senderInfo);
	    ret = lwip_recvfrom(fd, buffer, sizeof(buffer), 0, (struct sockaddr*)&senderInfo, &senderInfoLen);
	    LWIP_ASSERT("ret > 0", ret > 0);
	    ESP_LOGI(pcTaskGetTaskName(0),"lwip_recv ret=%d",ret);
	    if (ret > 0) {
	      buffer[ret] = 0;
	      ESP_LOGI(pcTaskGetTaskName(0),"lwip_recv buffer=%s",buffer);
	#if 0
	      inet_ntop(AF_INET, &senderInfo.sin_addr, senderstr, sizeof(senderstr));
	      ESP_LOGI(pcTaskGetTaskName(0),"recvfrom : %s, port=%d\n", senderstr, ntohs(senderInfo.sin_port));
	#endif
	    }
	  }

	  /* close socket. Don't reach here. */
	  ret = lwip_close(fd);
	  LWIP_ASSERT("ret == 0", ret == 0);
	  vTaskDelete( NULL );

	}

	static esp_err_t event_handler(void *ctx, system_event_t *event)
	{
	    switch(event->event_id) {
	    case SYSTEM_EVENT_STA_START:
	        esp_wifi_connect();
	        break;
	    case SYSTEM_EVENT_STA_GOT_IP:
	        ESP_LOGI(TAG, "got ip:%s",
	                 ip4addr_ntoa(&event->event_info.got_ip.ip_info.ip));
	        s_retry_num = 0;
	        xEventGroupSetBits(xEventGroup, WIFI_CONNECTED_BIT);
	        break;
	    case SYSTEM_EVENT_STA_DISCONNECTED:
	        {
	            if (s_retry_num < EXAMPLE_ESP_MAXIMUM_RETRY) {
	                esp_wifi_connect();
	                xEventGroupClearBits(xEventGroup, WIFI_CONNECTED_BIT);
	                s_retry_num++;
	                ESP_LOGI(TAG,"retry to connect to the AP");
	            }
	            ESP_LOGI(TAG,"connect to the AP fail\n");
	            break;
	        }
	    default:
	        break;
	    }
	    return ESP_OK;
	}

	void wifi_init_sta()
	{
	    xEventGroup = xEventGroupCreate();

	    tcpip_adapter_init();
	    ESP_ERROR_CHECK(esp_event_loop_init(event_handler, NULL) );

	    wifi_init_config_t cfg = WIFI_INIT_CONFIG_DEFAULT();
	    ESP_ERROR_CHECK(esp_wifi_init(&cfg));
	    wifi_config_t wifi_config = {
	        .sta = {
	            .ssid = EXAMPLE_ESP_WIFI_SSID,
	            .password = EXAMPLE_ESP_WIFI_PASS
	        },
	    };

	    ESP_ERROR_CHECK(esp_wifi_set_mode(WIFI_MODE_STA) );
	    ESP_ERROR_CHECK(esp_wifi_set_config(ESP_IF_WIFI_STA, &wifi_config) );
	    ESP_ERROR_CHECK(esp_wifi_start() );

	    ESP_LOGI(TAG, "wifi_init_sta finished.");
	    ESP_LOGI(TAG, "connect to ap SSID:%s password:%s",
	             EXAMPLE_ESP_WIFI_SSID, EXAMPLE_ESP_WIFI_PASS);
	}

	void app_main()
	{
	    //Initialize NVS
	    esp_err_t ret = nvs_flash_init();
	    if (ret == ESP_ERR_NVS_NO_FREE_PAGES || ret == ESP_ERR_NVS_NEW_VERSION_FOUND) {
	      ESP_ERROR_CHECK(nvs_flash_erase());
	      ret = nvs_flash_init();
	    }
	    ESP_ERROR_CHECK(ret);

	    ESP_LOGI(TAG, "ESP_WIFI_MODE_STA");
	    wifi_init_sta();

	    // Create Task
	    xTaskCreate(BroadRead, "BroadRead", 2048, NULL, 2, NULL);
	}

Transmit side Log
Transmitting side is sending broadcast UDP every 500Tick.

	I (0) cpu_start: App cpu up.
	I (374) heap_init: Initializing. RAM available for dynamic allocation:
	I (381) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM
	I (387) heap_init: At 3FFB8EB0 len 00027150 (156 KiB): DRAM
	I (393) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM
	I (399) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
	I (406) heap_init: At 4008FBF4 len 0001040C (65 KiB): IRAM
	I (412) cpu_start: Pro cpu start user code
	I (94) cpu_start: Starting scheduler on PRO CPU.
	I (0) cpu_start: Starting scheduler on APP CPU.
	I (157) wifi softAP: ESP_WIFI_MODE_AP
	I (157) wifi: wifi driver task: 3ffc0df4, prio:23, stack:3584, core=0
	I (157) wifi: wifi firmware version: e5a4523
	I (157) wifi: config NVS flash: enabled
	I (157) wifi: config nano formating: disabled
	I (167) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE
	I (177) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE
	I (217) wifi: Init dynamic tx buffer num: 32
	I (217) wifi: Init data frame dynamic rx buffer num: 32
	I (217) wifi: Init management frame dynamic rx buffer num: 32
	I (227) wifi: Init management short buffer num: 32
	I (227) wifi: Init static rx buffer size: 1600
	I (227) wifi: Init static rx buffer num: 10
	I (237) wifi: Init dynamic rx buffer num: 32
	I (357) phy: phy_version: 4100, 2a5dd04, Jan 23 2019, 21:00:07, 0, 0
	I (357) wifi: mode : softAP (30:ae:a4:ff:24:b1)
	I (367) wifi: Init max length of beacon: 752/752
	I (367) wifi: Init max length of beacon: 752/752
	I (367) wifi softAP: wifi_init_softap finished.SSID:PixRacer password:pixracer
	I (377) BroadSend: Start
	I (22527) wifi: new:<1,1>, old:<1,0>, ap:<1,1>, sta:<255,255>, prof:1
	I (22527) wifi: station: 30:ae:a4:ca:e1:40 join, AID=1, bgn, 40U
	I (22557) wifi softAP: station:30:ae:a4:ca:e1:40 join, AID=1
	I (22557) eventTask: Success to start Timer ...
	I (22587) tcpip_adapter: softAP assign IP to station,IP is: 192.168.4.2
	I (27557) Tmr Svc: Start
	I (27557) BroadSend: buffer=[Hello World!! 2743]
	I (27557) BroadSend: lwip_sendto ret=18
	I (32557) Tmr Svc: Start
	I (32557) BroadSend: buffer=[Hello World!! 3243]
	I (32557) BroadSend: lwip_sendto ret=18

Recerver side Log
Receiver side can't receive broadcast UDP.

	I (0) cpu_start: App cpu up.
	I (375) heap_init: Initializing. RAM available for dynamic allocation:
	I (382) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM
	I (388) heap_init: At 3FFB8EB8 len 00027148 (156 KiB): DRAM
	I (394) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM
	I (400) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
	I (407) heap_init: At 4008FB94 len 0001046C (65 KiB): IRAM
	I (413) cpu_start: Pro cpu start user code
	I (96) cpu_start: Starting scheduler on PRO CPU.
	I (0) cpu_start: Starting scheduler on APP CPU.
	I (160) wifi station: ESP_WIFI_MODE_STA
	I (210) wifi: wifi driver task: 3ffc0c48, prio:23, stack:3584, core=0
	I (210) wifi: wifi firmware version: e5a4523
	I (210) wifi: config NVS flash: enabled
	I (210) wifi: config nano formating: disabled
	I (220) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE
	I (230) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE
	I (260) wifi: Init dynamic tx buffer num: 32
	I (260) wifi: Init data frame dynamic rx buffer num: 32
	I (260) wifi: Init management frame dynamic rx buffer num: 32
	I (270) wifi: Init management short buffer num: 32
	I (270) wifi: Init static rx buffer size: 1600
	I (270) wifi: Init static rx buffer num: 10
	I (280) wifi: Init dynamic rx buffer num: 32
	I (380) phy: phy_version: 4100, 2a5dd04, Jan 23 2019, 21:00:07, 0, 0
	I (380) wifi: mode : sta (30:ae:a4:ca:e1:40)
	I (380) wifi station: wifi_init_sta finished.
	I (380) wifi station: connect to ap SSID:PixRacer password:pixracer
	I (390) BroadRead: Start
	I (500) wifi: new:<1,1>, old:<1,0>, ap:<255,255>, sta:<1,1>, prof:1
	I (510) wifi: state: init -> auth (b0)
	I (510) wifi: state: auth -> assoc (0)
	I (520) wifi: state: assoc -> run (10)
	I (540) wifi: connected with PixRacer, channel 1, bssid = 30:ae:a4:ff:24:b1
	I (550) wifi: pm start, type: 1

	I (1160) event: sta ip: 192.168.4.2, mask: 255.255.255.0, gw: 192.168.4.1
	I (1160) wifi station: got ip:192.168.4.2
	I (1160) BroadRead: xEventGroupWaitBits WIFI_CONNECTED_BIT
	I (1170) BroadRead: socket fd=54

**Comment by igrr** [comment]
Can you try calling `esp_wifi_set_ps(WIFI_PS_NONE);` on the receiver side?

**Comment by nopnop2002** [comment]
Thank you for quick replay.
I added esp_wifi_set_ps(WIFI_PS_NONE) in wifi_init_sta().

	void wifi_init_sta()
	{
	    xEventGroup = xEventGroupCreate();

	    tcpip_adapter_init();
	    ESP_ERROR_CHECK(esp_event_loop_init(event_handler, NULL) );

	    wifi_init_config_t cfg = WIFI_INIT_CONFIG_DEFAULT();
	    ESP_ERROR_CHECK(esp_wifi_init(&cfg));
	    wifi_config_t wifi_config = {
	        .sta = {
	            .ssid = EXAMPLE_ESP_WIFI_SSID,
	            .password = EXAMPLE_ESP_WIFI_PASS
	        },
	    };

	    ESP_ERROR_CHECK(esp_wifi_set_mode(WIFI_MODE_STA) );
	    ESP_ERROR_CHECK(esp_wifi_set_config(ESP_IF_WIFI_STA, &wifi_config) );
      //-----------------------------------------------
	    ESP_ERROR_CHECK(esp_wifi_set_ps(WIFI_PS_NONE));
      //-----------------------------------------------
	    ESP_ERROR_CHECK(esp_wifi_start() );

	    ESP_LOGI(TAG, "wifi_init_sta finished.");
	    ESP_LOGI(TAG, "connect to ap SSID:%s password:%s",
	             EXAMPLE_ESP_WIFI_SSID, EXAMPLE_ESP_WIFI_PASS);
	}


It's work fine.
Recerver side Log
Receiver side can receive all broadcast UDP.

	I (0) cpu_start: App cpu up.
	I (383) heap_init: Initializing. RAM available for dynamic allocation:
	I (390) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM
	I (396) heap_init: At 3FFB8E28 len 000271D8 (156 KiB): DRAM
	I (402) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM
	I (408) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
	I (415) heap_init: At 40090F50 len 0000F0B0 (60 KiB): IRAM
	I (421) cpu_start: Pro cpu start user code
	I (103) cpu_start: Starting scheduler on PRO CPU.
	I (0) cpu_start: Starting scheduler on APP CPU.
	I (169) wifi station: ESP_WIFI_MODE_STA
	I (169) wifi: wifi driver task: 3ffc0a0c, prio:23, stack:3584, core=0
	I (169) wifi: wifi firmware version: 955b7af
	I (169) wifi: config NVS flash: enabled
	I (179) wifi: config nano formating: disabled
	I (179) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE
	I (189) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE
	I (219) wifi: Init dynamic tx buffer num: 32
	I (219) wifi: Init data frame dynamic rx buffer num: 32
	I (219) wifi: Init management frame dynamic rx buffer num: 32
	I (229) wifi: Init management short buffer num: 32
	I (229) wifi: Init static rx buffer size: 1600
	I (239) wifi: Init static rx buffer num: 10
	I (239) wifi: Init dynamic rx buffer num: 32
	I (259) wifi: Set ps type: 0

	I (349) phy: phy_version: 4100, 6fa5e27, Jan 25 2019, 17:02:06, 0, 0
	I (349) wifi: mode : sta (30:ae:a4:24:bc:5c)
	I (349) wifi station: wifi_init_sta finished.
	I (359) wifi station: connect to ap SSID:PixRacer password:pixracer
	I (359) BroadRead: Start
	I (479) wifi: new:<1,1>, old:<1,0>, ap:<255,255>, sta:<1,1>, prof:1
	I (1459) wifi: state: init -> auth (b0)
	I (1459) wifi: state: auth -> assoc (0)
	I (1469) wifi: state: assoc -> run (10)
	I (1479) wifi: connected with PixRacer, channel 1, bssid = 3c:71:bf:4f:c1:a1
	I (1489) wifi: pm start, type: 0

	I (2169) event: sta ip: 192.168.4.2, mask: 255.255.255.0, gw: 192.168.4.1
	I (2169) wifi station: got ip:192.168.4.2
	I (2169) BroadRead: xEventGroupWaitBits WIFI_CONNECTED_BIT
	I (2179) BroadRead: socket fd=54
	I (6479) BroadRead: lwip_recv ret=19
	I (6479) BroadRead: lwip_recv buffer=Hello World!! 12590
	I (11479) BroadRead: lwip_recv ret=19
	I (11489) BroadRead: lwip_recv buffer=Hello World!! 13090
	I (16479) BroadRead: lwip_recv ret=19
	I (16479) BroadRead: lwip_recv buffer=Hello World!! 13590
	I (21479) BroadRead: lwip_recv ret=19
	I (21479) BroadRead: lwip_recv buffer=Hello World!! 14090
	I (26479) BroadRead: lwip_recv ret=19
	I (26479) BroadRead: lwip_recv buffer=Hello World!! 14590
	I (31479) BroadRead: lwip_recv ret=19
	I (31479) BroadRead: lwip_recv buffer=Hello World!! 15090


Please close this issues.
Thank you.
