### ISSUE TITLE
esp_http_client_perform never returns if the server does not send anything after connection (IDFGH-1132)

### ISSUE THREAD

**Issue by sysizlayan** [espressif/esp-idf#3447]
- Development Kit:      none
- Module or chip used:  ESP32-WROVER
- IDF version: v3.2
- Build System: Make
- Compiler version: 1.22.0-80-g6c4433a
- Operating System: Linux
- Power Supply: External 3.3V

## Problem Description
All the fields in http client is set and the esp_http_client_perform is called.
The connection is opened but the server does not respond to the device and esp_http_client_perform did not return.
### Expected Behavior
After some time, it must return even if the function failed.
### Actual Behavior
Infinite loop in the esp_http_client_perform function.
### Steps to repropduce

1. Prepare a server which does not respond to any request but accepts tcp requests.
2. Send a request using esp_http_client_perform.

Edit: I need to add that the client is configured as blocking and as TCP connection, not as SSL.

Configuration struct is as follows:
esp_http_client_config_t httpConfig;
memset(&httpConfig, 0, sizeof(esp_http_client_config_t));

httpConfig.url = defaultURL;
httpConfig.method = HTTP_METHOD_PUT;
httpConfig.buffer_size = 8 * 1024;
httpConfig.disable_auto_redirect = false;
httpConfig.is_async = false;
httpConfig.max_redirection_count = 20;
httpConfig.port = 80;
httpConfig.timeout_ms = 5000;
httpConfig.transport_type = HTTP_TRANSPORT_OVER_TCP;
if(uploaderClient.initialize(uploaderClient_name, &httpConfig) != K_OK)
{
	ESP_LOGE(TAG, "uploader client cannot be created!");
	esp_restart();
}

if(esp_http_client_set_url(uploaderClient.client, uploadLocation) != ESP_OK ||
esp_http_client_set_header(uploaderClient.client, "header1", header1) != ESP_OK ||
esp_http_client_set_header(uploaderClient.client, "header2", header2) != ESP_OK ||
esp_http_client_set_post_field(uploaderClient.client, (char*)buffer, strlen(buffer)) != ESP_OK )
     return;

if(esp_http_client_perform(uploaderClient.client) != ESP_OK ||
esp_http_client_get_status_code(uploaderClient.client) != 200}
    return;

We can see HTTP_EVENT_ON_CONNECTED event. Then the code stops there and never logs, esp_http_client_perform does not return.

Thanks in advance.

**Comment by sysizlayan** [comment]
According to the BugFix section of the IDF3.3Beta3, this problem may have been solved. Infinite loop on esp_http_client_fetch_headers may be the reason behind it. The test will be done after the official release of the 3.3.

**Comment by shubhamkulkarni97** [comment]
@sysizlayan I tried to send a request from ESP32 HTTP Client to a HTTP server hosted on another ESP32 which does not respond to any request. 

esp_http_client_perform returns with the following ERROR message:
HTTP_CLIENT: HTTP PUT request failed: ERROR

Can you please check once?
If it works fine, we can close this issue.

**Comment by mahavirj** [comment]
@sysizlayan Closing per above comment, please feel free to reopen if you observe any issues on your side.
