### ISSUE TITLE
airkiss入网成功后，如何让微信发现设备 (IDFGH-1135)

### ISSUE THREAD

**Issue by kixiaomu** [espressif/esp-idf#3450]
通过smart_config例程

`esp_smartconfig_set_type(SC_TYPE_ESPTOUCH_AIRKISS)`

设备能成功入网。但是微信上只会一直显示:**"正在搜索可添加的物联网关"**
![bd73204f2d2aa9391cfbc719af9f65e](https://user-images.githubusercontent.com/26807538/57499019-b1baef80-7310-11e9-87de-c9177f97a795.png)

**Comment by xuhongv** [comment]
- 你所说的是这个搜索发现设备 是近场发现功能。目前esp32还没适配的。
- 目前有 esp8266 适配了 ：https://github.com/xuhongv/xLibEsp8266Rtos3.1AirKiss

**Comment by kixiaomu** [comment]
好的 谢谢

**Comment by MinjunHuang** [comment]
@xuhongv 
你好， ESP32近期有计划支持近场发现功能吗？谢谢。

**Comment by xuhongv** [comment]
这个要等官网的资料。我是个人开发者，不是官网的呢

**Comment by MinjunHuang** [comment]
哦，好，多谢

**Comment by xuhongv** [comment]
- 已经出来了啦！
 xuhongv/xLibEsp32IdfAirKiss: 【持续维护更新】微信公众号airkiss配网以及近场发现功能在esp32 esp-idf框架 sdk的实现。 https://github.com/xuhongv/xLibEsp32IdfAirKiss

@MinjunHuang @kixiaomu

**Comment by YouDONG-ESP** [comment]
Hi @kixiaomu , Airkiss is available now, It can be found in the smart config example https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/network/esp_smartconfig.html?highlight=smart%20config

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, feel free to reopen.
