### ISSUE TITLE
Where I can find the IIC slave demo? (IDFGH-1148)

### ISSUE THREAD

**Issue by Herwey** [espressif/esp-idf#3463]
Hi:
I need the demo that esp32 only be used as IIC slave, no master function. That means it only includes "slave_read_buf" and "slave_write_buf", it's enough. I had found the demo in example, but it includes master and slave :P
Thanks !

**Comment by Alvin1Zhang** [comment]
@Herwey Hi, thanks for reporting the issue. Suggest you could post a thread on our [forum](https://esp32.com). Thanks.
