### ISSUE TITLE
Supervisor problem. (IDFGH-1163)

### ISSUE THREAD

**Issue by ArTyGill** [espressif/esp-idf#3477]
The supervisor does not work well, when the power is turned on, the controller may freeze until it is connected with the Power On pin. How can you programmatically solve the problem?

**Comment by Alvin1Zhang** [comment]
Thanks for reporting the issue. Would you please help provide more details as suggested in the [issue template](https://github.com/espressif/esp-idf/blob/master/docs/issue_template.md)? Thanks.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting the issue. Will close this issue for now due to lack of details. @ArTyGill Feel free to reopen and please help provide more details as suggested in the [issue template](https://github.com/espressif/esp-idf/blob/master/docs/issue_template.md). Thanks.
