### ISSUE TITLE
请问PWM支持的最大频率是多少呢 (IDFGH-1167)

### ISSUE THREAD

**Issue by xizonghu** [espressif/esp-idf#3481]
我想设置频率为1Mhz，但没有输出，100kHz可以输出，想问PWM最大支持多少的频率
pwm_config.frequency = 1024000;  //这个可以输出
pwm_config.frequency = 1024000;  //这个没有输出

**Comment by koobest** [comment]
Hi, @xizonghu 
请把 mcpwm.c 中 这两个宏定义设置小一点 , 比如:
``` 
#define MCPWM_CLK_PRESCL 1       //MCPWM clock prescale 
#define TIMER_CLK_PRESCALE 2    //MCPWM timer prescales
```
就可以输出 1M 的 PWM.

thanks !!

**Comment by Alvin1Zhang** [comment]
@xizonghu Thanks for reporting the issue. Suggest you could visit our [forum](https://esp32.com) and raise questions there. Thanks.
