### ISSUE TITLE
E (22) wifi: wifi_init_in_caller_task 712 ret=4353 (IDFGH-1172)

### ISSUE THREAD

**Issue by isharaux** [espressif/esp-idf#3485]
Cant connect to WiFi using default arduino library #include <WiFi.h>
following error results...

`E (22) wifi: wifi_init_in_caller_task 712 ret=4353`

**Comment by liuzfesp** [comment]
Hi @isharaux could you help to provide following info:

- IDF commit ID
- Steps to reproduce this issue

**Comment by liuzfesp** [comment]
Hi @espxiehang please help.

**Comment by Alvin1Zhang** [comment]
@isharaux Thanks for reporting the issue, will close the issue for now due to not enough details and little feedback. Feel free to reopen if your issue still happens. Thanks.
