### ISSUE TITLE
Wrong documentation or wrong project.mk (IDFGH-1175)

### ISSUE THREAD

**Issue by dsptech** [espressif/esp-idf#3488]
Hi,
in "https://docs.espressif.com/projects/esp-idf/en/latest/api-guides/build-system.html" is written:
"Verbose output (same as V=1, see below). If you don’t want verbose output, also set V=0".

However, the line 505 (current version) in project.mk is:
"$(if $(V),$$(info including $(1)/Makefile.projbuild...))"

but $(if $(V)... check for an empty string and not for a non zero value

I may be wrong, but V=0 cannot work. To avoid verbose output, V need to be unset or empty.

Regards.

**Comment by projectgus** [comment]
Hi @dsptech,

Thanks for point this out. It looks like `V` is checked in a couple of ways, so `V=0` gives more output than `V=` but nowhere near as much as `V=1`. Will fix so that `V=0` and `V=` are equivalent.
