### ISSUE TITLE
GPIO Mux FUNC_U0TXD_EMAC_RXD2 Function Index

### ISSUE THREAD

**Issue by negativekelvin** [espressif/esp-idf#349]
Is this correct?  Should be function 6 (index 5) like all other ethernet pins?

```
#define PERIPHS_IO_MUX_U0TXD_U            (DR_REG_IO_MUX_BASE +0x88)
#define FUNC_U0TXD_EMAC_RXD2                        3
```

https://github.com/espressif/esp-idf/blob/1b25795f5ddaadf5ae37e566645e019a5bcc3686/components/esp32/include/soc/io_mux_reg.h

**Comment by ESP32DE** [comment]
6 days without a state from espressif team?
why .. why?

can you please commet this?
