### ISSUE TITLE
GPIO Interrupts (advice please). (IDFGH-1185)

### ISSUE THREAD

**Issue by JLuisAlcaraz** [espressif/esp-idf#3496]
Hi all,
I'm working with GPIO Interrupts (its my first time) and I really need advice on my code.
The thing is simple: To detect a push button with an interrupt.
The code set the interrupt and when detect the button pressed, disable the interrupt for a time.

Its ok? Is there a better way to do it? Is there a good place to read about it?

Thanks in advance!

`
#include <stdio.h>
#include "esp_timer.h"
#include "driver/gpio.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "freertos/queue.h"

#define BLINK_LED   32  //Just a led blinking
#define BUTTON_LED  25  //This Led light for a second when button is pressed
#define PUSH_BUTTON 27
#define ESP_INTR_FLAG_DEFAULT 0

static int b_presionado = 0;  //a flag: 1 = button pressed, 0 = button released
static int b_letInt = 0;      //a flag: 0 = dont let the interrupt happen, 1 = let it

void triggered_isr(void* instance)
	{
	b_presionado = 1;
	b_letInt = 0;
	gpio_intr_disable(BUTTON_LED);
	}

void app_main(void)
	{
	unsigned long tiempo;
	unsigned long temporizador;
	int estadoLed;
	int estadoPulsador;

	gpio_pad_select_gpio(BLINK_LED);
	gpio_set_direction(BLINK_LED, GPIO_MODE_OUTPUT);

	gpio_pad_select_gpio(BUTTON_LED);
	gpio_set_direction(BUTTON_LED, GPIO_MODE_OUTPUT);

	gpio_pad_select_gpio(PUSH_BUTTON);
	gpio_set_direction(PUSH_BUTTON, GPIO_MODE_INPUT);
	gpio_pullup_en(PUSH_BUTTON);
	gpio_pulldown_dis(PUSH_BUTTON);
	gpio_set_intr_type(PUSH_BUTTON, GPIO_INTR_NEGEDGE);

	gpio_install_isr_service(ESP_INTR_FLAG_DEFAULT);
	gpio_isr_handler_add(PUSH_BUTTON, triggered_isr, (void*) PUSH_BUTTON);
	gpio_intr_enable(PUSH_BUTTON);
	b_letInt = 1;

	tiempo = esp_timer_get_time();
	temporizador = esp_timer_get_time();
	gpio_set_level(BLINK_LED, 1);

	estadoLed = 0;
    while (true)
		{
    	//-------------------------- Keep a led blinking every 0,5s ---------------------------
		if(esp_timer_get_time() - tiempo > 500000 && estadoLed == 0)
			{
			tiempo = esp_timer_get_time();
			gpio_set_level(BLINK_LED, 0);

			estadoLed = 1;
			}

		if(esp_timer_get_time() - tiempo > 500000 && estadoLed == 1)
			{
			tiempo = esp_timer_get_time();
			gpio_set_level(BLINK_LED, 1);

			estadoLed = 0;
			}
		//--------------------------------------------------------------------------------------
		
		//If button is press light a led and start a timer
		if(b_presionado)
			{
			temporizador = esp_timer_get_time();
			b_presionado = 0;
			gpio_set_level(BUTTON_LED, 0);
			}

		//Check the timer for the button led. If greater than 1s, then lights off and let new interrupts
		if(esp_timer_get_time() - temporizador > 1000000)
			{
			gpio_set_level(BUTTON_LED, 1);

			if(!b_letInt)
				{
				b_letInt = 1;
				}
			}

		}
	}
`

**Comment by negativekelvin** [comment]
I can advise you not to ignore the issue template which says

> If your issue is a general question, starts similar to "How do I..", or is related to 3rd party development kits/libs, please discuss this on our community forum at esp32.com instead.
