### ISSUE TITLE
Building with ceedling. (IDFGH-1195)

### ISSUE THREAD

**Issue by coolcodehere** [espressif/esp-idf#3501]
## Environment

- Development Kit:  ESP32-DevKitC
- Module or chip used:  ESP32
- IDF version v3.3-dev-400-gf49e2afe9
- Build System:  Make
- Compiler version -1.22.0-80-g6c4433a
- Operating System:   macOS
- Power Supply:  USB

## Problem Description

I am trying to set up ceedling to build esp32 projects for me but I'm not sure how to call the compiler and linker. In the project's YML file I have the following so far: 

```
:tools:
  :test_compiler:
     :executable: xtensa-esp32-elf-gcc #exists in system search path
     :arguments:
        - -I"$": COLLECTION_PATHS_TEST_TOOLCHAIN_INCLUDE               #expands to -I search paths
        - -I"$": COLLECTION_PATHS_TEST_SUPPORT_SOURCE_INCLUDE_VENDOR   #expands to -I search paths
        - -D$: COLLECTION_DEFINES_TEST_AND_VENDOR  #expands to all -D defined symbols
        - -c ${1}                       #source code input file (Ruby method call param list sub)
        - -o ${2}                       #object file output (Ruby method call param list sub)
  :test_linker:
     :executable: /Users/user/esp/xtensa-esp32-elf/bin/xtensa-esp32-elf-ld   #absolute file path
     :arguments:
        - '"${1}"'
        - -o "${2}"
```

Also, after this how would I get my code to flash to the chip after building?

**Comment by projectgus** [comment]
Hi @coolcodehere ,

Sorry for the extremely long delay in getting back to you. For future reference, this kind of "how do I..." question is better suited to the https://esp32.com forums as this doesn't relate to a bug or feature request for ESP-IDF.

ESP-IDF has its own build system which is quite complex, so there is no simple way to fit another build system like Ceedling around it. You may be able to call the ESP-IDF build system directly from Ceedling, but I'm afraid we can't help support that configuration - and I think most of the benefits of Ceedling would be lost in this case.

Regarding the underlying requirement of being able to mock hardware dependencies, I'm going to close this issue in favour of the linked one. As mentioned there we have some plans regarding CMock, it will be updated once more information is available.

Angus
