### ISSUE TITLE
ble to wifi gateway

### ISSUE THREAD

**Issue by vlachosv** [espressif/esp-idf#351]
Hi, it is possible to read a ble sensor and the same time push sensor data to web via wifi?
(esp32 ble connect to a ble sensor -> esp32 ble read sensor data -> esp32 wifi connect to an access point -> esp32 send sensor data to a web server via http request)

**Comment by tbanasiewicz** [comment]
https://github.com/pcbreflux/espressif/tree/master/esp32/app/ESP32_gatts_mqtt_gateway

See this link

**Comment by vlachosv** [comment]
Thanks for the link

https://www.youtube.com/watch?v=PBYCG-ypvRY

https://gist.github.com/me-no-dev/5f8851e1e1112b7c3d9eefe6e1e1cf9d
