### ISSUE TITLE
undefined reference to `pread' (IDFGH-1211)

### ISSUE THREAD

**Issue by olegantonyan** [espressif/esp-idf#3515]
esp-idf a20d02b7f
trying to use `pread` function from `esp-idf/components/newlib/include/sys/unistd.h` yields a link error:
```
undefined reference to `pread'
```
regular `read` function works fine

**Comment by dobairoland** [comment]
Thanks @olegantonyan. Yes, the implementation of `pread()` is missing from or virtual filesystem layer. We will implement it.
