### ISSUE TITLE
undefined reference to spi_flash_disable_cache  undefined reference to spi_flash_restore_cache

### ISSUE THREAD

**Issue by ESP32DE** [espressif/esp-idf#352]
hi 

try to use
https://github.com/espressif/esp-idf/blob/master/components/spi_flash/cache_utils.h
`#include "../cache_utils.h`

and try to use 
`spi_flash_disable_cache`
`spi_flash_restore_cache`

that are in cache_utils.c
https://github.com/espressif/esp-idf/blob/master/components/spi_flash/cache_utils.c#L35

```
uint32_t cpuid = 1;
uint32_t saved_state = 0;


extern void IRAM_ATTR spi_flash_disable_cache(uint32_t cpuid, uint32_t* saved_state);
extern void IRAM_ATTR spi_flash_restore_cache(uint32_t cpuid, uint32_t saved_state);

extern void spi_flash_disable_interrupts_caches_and_other_cpu();
extern void spi_flash_enable_interrupts_caches_and_other_cpu();

extern void spi_flash_disable_interrupts_caches_and_other_cpu_no_os();
extern void spi_flash_enable_interrupts_caches_no_os();



```
> CC sd_card.o
> AR libmain.a
> LD sd_card.elf
> C:/nod/27_sd_Card_iram/build/main\libmain.a(sd_card.o):(.iram1.literal+0x14): undefined reference to `spi_flash_disable_cache'
> C:/nod/27_sd_Card_iram/build/main\libmain.a(sd_card.o):(.iram1.literal+0x18): undefined reference to `spi_flash_restore_cache'
> C:/nod/27_sd_Card_iram/build/main\libmain.a(sd_card.o): In function `app_main':
> C:/nod/27_sd_Card_iram/main/sd_card.c:98: undefined reference to `spi_flash_disable_cache'
> C:/nod/27_sd_Card_iram/main/sd_card.c:100: undefined reference to `spi_flash_restore_cache'
> 

best wishes
rudi ;-)

**Comment by ESP32DE** [comment]
```
extern void spi_flash_disable_interrupts_caches_and_other_cpu();
extern void spi_flash_enable_interrupts_caches_and_other_cpu();

extern void spi_flash_disable_interrupts_caches_and_other_cpu_no_os();
extern void spi_flash_enable_interrupts_caches_no_os();




/**
 * The following two functions are replacements for Cache_Read_Disable and Cache_Read_Enable
 * function in ROM. They are used to work around a bug where Cache_Read_Disable requires a call to
 * Cache_Flush before Cache_Read_Enable, even if cached data was not modified.
 */

static const uint32_t cache_mask  = DPORT_APP_CACHE_MASK_OPSDRAM | DPORT_APP_CACHE_MASK_DROM0 |
        DPORT_APP_CACHE_MASK_DRAM1 | DPORT_APP_CACHE_MASK_IROM0 |
        DPORT_APP_CACHE_MASK_IRAM1 | DPORT_APP_CACHE_MASK_IRAM0;

static void IRAM_ATTR spi_flash_disable_cache(uint32_t cpuid, uint32_t* saved_state)
{
    uint32_t ret = 0;
    if (cpuid == 0) {
        ret |= GET_PERI_REG_BITS2(DPORT_PRO_CACHE_CTRL1_REG, cache_mask, 0);
        while (GET_PERI_REG_BITS2(DPORT_PRO_DCACHE_DBUG0_REG, DPORT_PRO_CACHE_STATE, DPORT_PRO_CACHE_STATE_S) != 1) {
            ;
        }
        SET_PERI_REG_BITS(DPORT_PRO_CACHE_CTRL_REG, 1, 0, DPORT_PRO_CACHE_ENABLE_S);
    } else {
        ret |= GET_PERI_REG_BITS2(DPORT_APP_CACHE_CTRL1_REG, cache_mask, 0);
        while (GET_PERI_REG_BITS2(DPORT_APP_DCACHE_DBUG0_REG, DPORT_APP_CACHE_STATE, DPORT_APP_CACHE_STATE_S) != 1) {
            ;
        }
        SET_PERI_REG_BITS(DPORT_APP_CACHE_CTRL_REG, 1, 0, DPORT_APP_CACHE_ENABLE_S);
    }
    *saved_state = ret;
}

static void IRAM_ATTR spi_flash_restore_cache(uint32_t cpuid, uint32_t saved_state)
{
    if (cpuid == 0) {
        SET_PERI_REG_BITS(DPORT_PRO_CACHE_CTRL_REG, 1, 1, DPORT_PRO_CACHE_ENABLE_S);
        SET_PERI_REG_BITS(DPORT_PRO_CACHE_CTRL1_REG, cache_mask, saved_state, 0);
    } else {
        SET_PERI_REG_BITS(DPORT_APP_CACHE_CTRL_REG, 1, 1, DPORT_APP_CACHE_ENABLE_S);
        SET_PERI_REG_BITS(DPORT_APP_CACHE_CTRL1_REG, cache_mask, saved_state, 0);
    }
}


```




```
uint32_t cpuid = 1;
    uint32_t* saved_state=0;
	
		
	printf("try disable:..\n\r");
	spi_flash_disable_cache(cpuid, (uint32_t *) saved_state);
	
	printf("try restore:..\n\r");
	spi_flash_restore_cache( cpuid, (uint32_t) saved_state);
	
	printf("go in while..\n\r");
	while (-1) ;


```






> ets Jun  8 2016 00:22:57
> 
> rst:0x1 (POWERON_RESET),boot:0x1b (SPI_FAST_FLASH_BOOT)
> ets Jun  8 2016 00:22:57
> 
> rst:0x10 (RTCWDT_RTC_RESET),boot:0x1b (SPI_FAST_FLASH_BOOT)
> configsip: 0, SPIWP:0x00
> clk_drv:0x0ets Jun  8 2016 00:22:57
> 
> rst:0x10 (RTCWDT_RTC_RESET),boot:0x1b (SPI_FAST_FLASH_BOOT)
> ets Jun  8 2016 00:22:57
> 
> rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
> configsip: 0, SPIWP:0x00
> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
> mode:DIO, clock div:2
> load:0x3fff0008,len:8
> load:0x3fff0010,len:3388
> ho 0 tail 12 room 4
> load:0x40078000,len:7504
> load:0x40080000,len:252
> entry 0x40080034
> I (47) boot: ESP-IDF v2.0-rc1-21-g30a557a 2nd stage bootloader
> I (47) boot: compile time 13:34:58
> I (47) boot: Enabling RNG early entropy source...
> I (67) boot: SPI Speed      : 40MHz
> I (80) boot: SPI Mode       : DIO
> I (92) boot: SPI Flash Size : 4MB
> I (105) boot: Partition Table:
> I (116) boot: ## Label            Usage          Type ST Offset   Length
> I (139) boot:  0 nvs              WiFi data        01 02 00009000 00006000
> I (162) boot:  1 phy_init         RF data          01 01 0000f000 00001000
> I (185) boot:  2 factory          factory app      00 00 00010000 00100000
> I (209) boot: End of partition table
> I (222) boot: Disabling RNG early entropy source...
> I (239) boot: Loading app partition at offset 00010000
> I (511) boot: segment 0: paddr=0x00010018 vaddr=0x00000000 size=0x0ffe8 ( 65512)
> I (512) boot: segment 1: paddr=0x00020008 vaddr=0x3f400010 size=0x02298 (  8856) map
> I (528) boot: segment 2: paddr=0x000222a8 vaddr=0x3ffb0000 size=0x01a98 (  6808) load
> I (557) boot: segment 3: paddr=0x00023d48 vaddr=0x40080000 size=0x00400 (  1024) load
> I (581) boot: segment 4: paddr=0x00024150 vaddr=0x40080400 size=0x07d08 ( 32008) load
> I (622) boot: segment 5: paddr=0x0002be60 vaddr=0x400c0000 size=0x00000 (     0) load
> I (633) boot: segment 6: paddr=0x0002be68 vaddr=0x00000000 size=0x041a0 ( 16800)
> I (658) boot: segment 7: paddr=0x00030010 vaddr=0x400d0018 size=0x0c454 ( 50260) map
> I (684) heap_alloc_caps: Initializing. RAM available for dynamic allocation:
> I (707) heap_alloc_caps: At 3FFB20F8 len 0002DF08 (183 KiB): DRAM
> I (728) heap_alloc_caps: At 3FFE8000 len 00018000 (96 KiB): D/IRAM
> I (749) heap_alloc_caps: At 40088108 len 00017EF8 (95 KiB): IRAM
> I (769) cpu_start: Pro cpu up.
> I (781) cpu_start: Starting app cpu, entry point is 0x40080994
> I (0) cpu_start: App cpu up.
> I (812) cpu_start: Pro cpu start user code
> I (872) cpu_start: Starting scheduler on PRO CPU.
> I (877) example: Initializing SD card
> try disable:..
> GGuru Meditation Error of type IllegalInstruction occurred on core  1. Exception was unhandled.
> Register dump:
> PC      : 0x400d09f6  PS      : 0x00060d33  A0      : 0x800d0cdb  A1      : 0x3ffe7c90
> A2      : 0x0000040e  A3      : 0x00000001  A4      : 0xffffffff  A5      : 0x00000003
> A6      : 0x0000001f  A7      : 0x00000001  A8      : 0x800d0ae3  A9      : 0x00000000
> A10     : 0x00000001  A11     : 0x00000001  A12     : 0x00000000  A13     : 0x3ffe7e30
> A14     : 0x0000abab  A15     : 0x00000001  SAR     : 0x00000000  EXCCAUSE: 0x00000000
> EXCVADDR: 0x00000000  LBEG    : 0x4000c2e0  LEND    : 0x4000c2f6  LCOUNT  : 0x00000000
> 
> Backtrace: 0x400d09f6:0x3ffe7c90 0x400d0cdb:0x3ffe7cd0 0x400d0ebc:0x3ffe7d10 0x400d0934:0x3ffe7d40 0x4008097e:0x3ffe7d60 0x40080a0c:0x3ffe7d80 0x40007c34:0x3ffe7dc0 0x40000740:0x3ffe7e30
> 
> Rebooting...
> uets Jun  8 2016 00:22:57
> 
> rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
> configsip: 0, SPIWP:0x00
> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
> mode:DIO, clock div:2
> load:0x3fff0008,len:8
> load:0x3fff0010,len:3388
> ho 0 tail 12 room 4
> load:0x40078000,len:7504
> load:0x40080000,len:252
> entry 0x40080034
> ets Jun  8 2016 00:22:57
> 
> rst:0x10 (RTCWDT_RTC_RESET),boot:0x1b (SPI_FAST_FLASH_BOOT)
> configsip: 0, SPIWP:0x00
> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
> mode:DIO, clock div:2
> load:0x3fff0008,len:8
> load:0x3fff0010,len:3388
> ho 0 tail 12 room 4
> load:0x40078000,len:7504
> load:0x40080000,len:252
> entry 0x40080034
> I (47) boot: ESP-IDF v2.0-rc1-21-g30a557a 2nd stage bootloader
> I (47) boot: compile time 13:34:58
> I (47) boot: Enabling RNG early entropy source...
> I (67) boot: SPI Speed      : 40MHz
> I (80) boot: SPI Mode       : DIO
> I (92) boot: SPI Flash Size : 4MB
> I (105) boot: Partition Table:
> I (116) boot: ## Label            Usage          Type ST Offset   Length
> I (139) boot:  0 nvs              WiFi data        01 02 00009000 00006000
> I (162) boot:  1 phy_init         RF data          01 01 0000f000 00001000
> I (185) boot:  2 factory          factory app      00 00 00010000 00100000
> I (209) boot: End of partition table
> I (222) boot: Disabling RNG early entropy source...
> I (239) boot: Loading app partition at offset 00010000
> I (511) boot: segment 0: paddr=0x00010018 vaddr=0x00000000 size=0x0ffe8 ( 65512)
> I (512) boot: segment 1: paddr=0x00020008 vaddr=0x3f400010 size=0x02298 (  8856) map
> I (528) boot: segment 2: paddr=0x000222a8 vaddr=0x3ffb0000 size=0x01a98 (  6808) load
> I (557) boot: segment 3: paddr=0x00023d48 vaddr=0x40080000 size=0x00400 (  1024) load
> I (581) boot: segment 4: paddr=0x00024150 vaddr=0x40080400 size=0x07d08 ( 32008) load
> I (622) boot: segment 5: paddr=0x0002be60 vaddr=0x400c0000 size=0x00000 (     0) load
> I (633) boot: segment 6: paddr=0x0002be68 vaddr=0x00000000 size=0x041a0 ( 16800)
> I (657) boot: segment 7: paddr=0x00030010 vaddr=0x400d0018 size=0x0c454 ( 50260) map
> I (684) heap_alloc_caps: Initializing. RAM available for dynamic allocation:
> I (707) heap_alloc_caps: At 3FFB20F8 len 0002DF08 (183 KiB): DRAM
> I (728) heap_alloc_caps: At 3FFE8000 len 00018000 (96 KiB): D/IRAM
> I (749) heap_alloc_caps: At 40088108 len 00017EF8 (95 KiB): IRAM
> I (769) cpu_start: Pro cpu up.
> I (781) cpu_start: Starting app cpu, entry point is 0x40080994
> I (0) cpu_start: App cpu up.
> I (812) cpu_start: Pro cpu start user code
> I (872) cpu_start: Starting scheduler on PRO CPU.
> I (877) example: Initializing SD card
> try disable:..
> GGuru Meditation Error of type IllegalInstruction occurred on core  1. Exception was unhandled.
> Register dump:
> PC      : 0x400d09f6  PS      : 0x00060d33  A0      : 0x800d0cdb  A1      : 0x3ffe7c90
> A2      : 0x0000040e  A3      : 0x00000001  A4      : 0xffffffff  A5      : 0x00000003
> A6      : 0x0000001f  A7      : 0x00000001  A8      : 0x800d0ae3  A9      : 0x00000000
> A10     : 0x00000001  A11     : 0x00000001  A12     : 0x00000000  A13     : 0x3ffe7e30
> A14     : 0x0000abab  A15     : 0x00000001  SAR     : 0x00000000  EXCCAUSE: 0x00000000
> EXCVADDR: 0x00000000  LBEG    : 0x4000c2e0  LEND    : 0x4000c2f6  LCOUNT  : 0x00000000
> 
> Backtrace: 0x400d09f6:0x3ffe7c90 0x400d0cdb:0x3ffe7cd0 0x400d0ebc:0x3ffe7d10 0x400d0934:0x3ffe7d40 0x4008097e:0x3ffe7d60 0x40080a0c:0x3ffe7d80 0x40007c34:0x3ffe7dc0 0x40000740:0x3ffe7e30
> 
> Rebooting...
> uets Jun  8 2016 00:22:57
> 
> rst:0xc (SW_CPU_RESET),boot:0x1b (SPI_FAST_FLASH_BOOT)
> configsip: 0, SPIWP:0x00
> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
> mode:DIO, clock div:2
> load:0x3fff0008,len:8
> load:0x3fff0010,len:3388
> ho 0 tail 12 room 4
> load:0x40078000,len:7504
> load:0x40080000,len:252
> entry 0x40080034
> I (47) boot: ESP-IDF v2.0-rc1-21-g30a557a 2nd stage bootloader
> I (47) boot: compile time 13:34:58
> I (47) boot: Enabling RNG early entropy source...
> I (67) boot: SPI Speed      : 40MHz
> I (80) boot: SPI Mode       : DIO
> I (92) boot: SPI Flash Size : 4MB
> I (105) boot: Partition Table:
> I (116) boot: ## Label            Usage          Type ST Offset   Length
> I (139) boot:  0 nvs              WiFi data        01 02 00009000 00006000
> I (162) boot:  1 phy_init         RF data          01 01 0000f000 00001000
> I (185) boot:  2 factory          factory app      00 00 00010000 00100000
> I (209) boot: End of partition table
> I (221) boot: Disabling RNG early entropy source...
> I (239) boot: Loading app partition at offset 00010000
> I (511) boot: segment 0: paddr=0x00010018 vaddr=0x00000000 size=0x0ffe8 ( 65512)
> I (511) boot: segment 1: paddr=0x00020008 vaddr=0x3f400010 size=0x02298 (  8856) map
> I (527) boot: segment 2: paddr=0x000222a8 vaddr=0x3ffb0000 size=0x01a98 (  6808) load
> I (557) boot: segment 3: paddr=0x00023d48 vaddr=0x40080000 size=0x00400 (  1024) load
> I (581) boot: segment 4: paddr=0x00024150 vaddr=0x40080400 size=0x07d08 ( 32008) load
> I (621) boot: segment 5: paddr=0x0002be60 vaddr=0x400c0000 size=0x00000 (     0) load
> I (632) boot: segment 6: paddr=0x0002be68 vaddr=0x00000000 size=0x041a0 ( 16800)
> I (657) boot: segment 7: paddr=0x00030010 vaddr=0x400d0018 size=0x0c454 ( 50260) map
> I (684) heap_alloc_caps: Initializing. RAM available for dynamic allocation:
> I (707) heap_alloc_caps: At 3FFB20F8 len 0002DF08 (183 KiB): DRAM
> I (728) heap_alloc_caps: At 3FFE8000 len 00018000 (96 KiB): D/IRAM
> I (749) heap_alloc_caps: At 40088108 len 00017EF8 (95 KiB): IRAM
> I (769) cpu_start: Pro cpu up.
> I (781) cpu_start: Starting app cpu, entry point is 0x40080994
> I (0) cpu_start: App cpu up.
> I (812) cpu_start: Pro cpu start user code
> I (871) cpu_start: Starting scheduler on PRO CPU.
> I (877) example: Initializing SD card
> try disable:..
> GGuru Meditation Error of type IllegalInstruction occurred on core  1. Exception was unhandled.
> Register dump:
> PC      : 0x400d09f6  PS      : 0x00060d33  A0      : 0x800d0cdb  A1      : 0x3ffe7c90
> A2      : 0x0000040e  A3      : 0x00000001  A4      : 0xffffffff  A5      : 0x00000003
> A6      : 0x0000001f  A7      : 0x00000001  A8      : 0x800d0ae3  A9      : 0x00000000
> A10     : 0x00000001  A11     : 0x00000001  A12     : 0x00000000  A13     : 0x3ffe7e30
> A14     : 0x0000abab  A15     : 0x00000001  SAR     : 0x00000000  EXCCAUSE: 0x00000000
> EXCVADDR: 0x00000000  LBEG    : 0x4000c2e0  LEND    : 0x4000c2f6  LCOUNT  : 0x00000000
> 
> Backtrace: 0x400d09f6:0x3ffe7c90 0x400d0cdb:0x3ffe7cd0 0x400d0ebc:0x3ffe7d10 0x400d0934:0x3ffe7d40 0x4008097e:0x3ffe7d60 0x40080a0c:0x3ffe7d80 0x40007c34:0x3ffe7dc0 0x40000740:0x3ffe7e30
> 
> Rebooting...
>

**Comment by negativekelvin** [comment]
> extern void spi_flash_disable_interrupts_caches_and_other_cpu();
> extern void spi_flash_enable_interrupts_caches_and_other_cpu();

Already calls 

```
extern void IRAM_ATTR spi_flash_disable_cache(uint32_t cpuid, uint32_t* saved_state);
extern void IRAM_ATTR spi_flash_restore_cache(uint32_t cpuid, uint32_t saved_state);
```

**Comment by ESP32DE** [comment]
thank you @negativekelvin 

https://github.com/espressif/esp-idf/issues/353

have changed the code but this reboots.
just in time search with gdbstub

best wishes
rudi ;-)

**Comment by Spritetm** [comment]
Okay, closing this issue then.
