### ISSUE TITLE
esp-tls.c and CONFIG_MBEDTLS_DEBUG_LEVEL (IDFGH-1219)

### ISSUE THREAD

**Issue by WallaceWilliam** [espressif/esp-idf#3521]
please, replace in esp-tls.c line 331

```
#ifdef CONFIG_MBEDTLS_DEBUG
    mbedtls_esp_enable_debug_log(&tls->conf, 4);
#endif

```
to

```
#ifdef CONFIG_MBEDTLS_DEBUG
    mbedtls_esp_enable_debug_log(&tls->conf, CONFIG_MBEDTLS_DEBUG_LEVEL);
#endif
```

**Comment by mahavirj** [comment]
@WallaceWilliam Any specific reason why you are recommending this? I do not see `MBEDTLS_DEBUG_LEVEL` as config option either.

**Comment by negativekelvin** [comment]
I think he is requesting that the debug threshold be configurable and that includes adding the config option.

**Comment by WallaceWilliam** [comment]
> I think he is requesting that the debug threshold be configurable and that includes adding the config option.

so much
if threshold = 4 a lot of debug information is issued
