### ISSUE TITLE
wishful: std::thread implementation for ESP32 to Arduino API/IDE (IDFGH-1220)

### ISSUE THREAD

**Issue by dsyleixa** [espressif/esp-idf#3522]
wishful IMO for Arduino: 
a std::thread implementation for ESP32, like meanwhile already available for Teensy (TeensyThread):
https://github.com/ftrias/TeensyThreads
or perhaps native C++ `<thread>`

**Comment by igrr** [comment]
Please see https://github.com/espressif/esp-idf/tree/master/examples/system/cpp_pthread

**Comment by dsyleixa** [comment]
> 
> 
> Please see https://github.com/espressif/esp-idf/tree/master/examples/system/cpp_pthread

how can this be used by Arduino IDE? I see no Arduino ino example unfortunately

**Comment by igrr** [comment]
Hi @dsyleixa, for Arduino related issues, please use this tracker: https://github.com/espressif/arduino-esp32/issues

The code mentioned above should also be usable in Arduino, provided you include the same header files.

**Comment by dsyleixa** [comment]
ok, but that is really unclearly ordered here, tbh...

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, let us tracker further in Arduino issue tracker https://github.com/espressif/arduino-esp32/issues.
