### ISSUE TITLE
tcp_transport destroy memory leak (IDFGH-1231)

### ISSUE THREAD

**Issue by WallaceWilliam** [espressif/esp-idf#3531]
trying to use a single tcp_transport_ssl with out esp_transport_list
```
esp_transport_handle_t transport = esp_transport_ssl_init();
esp_transport_connect(transport, web_server, web_port, 5000);
esp_transport_write(transport, buf, len_bytes, 5000);
esp_transport_read(transport, (char *)buf, len, 5000);
esp_transport_close(transport);
esp_transport_destroy(transport));
```
and getting a memory leak
because in esp_transport_destroy ssl_destroy is not called to destroy transport_ssl_t ssl
ssl_destroy is called only in esp_transport_list_clean
please transfer the code
```
         if (item -> _ destroy) {
             item -> _ destroy (item);
         }
```
from esp_transport_list_clean to esp_transport_destroy

**Comment by david-cermak** [comment]
Thank you for raising this issue. will be fixed!
