### ISSUE TITLE
kconfiglib: Tip for avoiding _write_to_conf (IDFGH-1246)

### ISSUE THREAD

**Issue by ulfalizer** [espressif/esp-idf#3543]
Hello,

https://github.com/espressif/esp-idf/blob/81ca1c01395f604972fbf141cfbe49764a746023/tools/kconfig_new/confgen.py#L346

Can do `if sym.config_string:` here instead to avoid the internal variable (though it probably won't go away).

Cheers,
Ulf

**Comment by ulfalizer** [comment]
CC @projectgus

**Comment by dobairoland** [comment]
Thanks @ulfalizer for the suggestion. It will be updated ASAP.
