### ISSUE TITLE
NIMBLE: nimble_port.h uses undefined  CONFIG_NIMBLE_PINNED_TO_CORE symbol (IDFGH-1266)

### ISSUE THREAD

**Issue by ecc1** [espressif/esp-idf#3561]
This file is still using CONFIG_NIMBLE_PINNED_TO_CORE but it looks like it should now be CONFIG_BT_NIMBLE_PINNED_TO_CORE

**Comment by dhrishi** [comment]
@ecc1 Can you please update the NimBLE submodule and check. I can see the updated change here: https://github.com/espressif/esp-nimble/blob/681a639c1cc24ea6b8bdb36c9a571dae8462614d/porting/nimble/include/nimble/nimble_port.h#L25

**Comment by ecc1** [comment]
This was my error due to an out-of-date git submodule. Closing.
