### ISSUE TITLE
NIMBLE: ble_store_config.c includes nonexistent config/config.h and base64/base64.h files (IDFGH-1267)

### ISSUE THREAD

**Issue by ecc1** [espressif/esp-idf#3562]
(Using an SDK config with only BLE peripheral role defined.) These files don't exist.

**Comment by dhrishi** [comment]
@ecc1 Can you please pull the latest `feature/nimble-preview` branch of ESP IDF and update the NimBLE submodule. These headers are already removed from `ble_store_config.c`. See here: https://github.com/espressif/esp-nimble/blob/681a639c1cc24ea6b8bdb36c9a571dae8462614d/nimble/host/store/config/src/ble_store_config.c#L27

**Comment by ecc1** [comment]
Yes, it looks like it was my error with out-of-date git submodules. Closing.
