### ISSUE TITLE
Background feature of esp_ble_gattc_open (IDFGH-1287)

### ISSUE THREAD

**Issue by copercini** [espressif/esp-idf#3582]
Looking the [docs of esp_ble_gattc_open](https://docs.espressif.com/projects/esp-idf/en/latest/api-reference/bluetooth/esp_gattc.html#_CPPv418esp_ble_gattc_open13esp_gatt_if_t13esp_bd_addr_t19esp_ble_addr_type_tb) there is a flag `bool is_direct` to background auto connection, when I know the mac address of the BLE device I want to connect, could I call this function and let it searching in background and when the device enters the range, auto-connect?
or in which case can I use it `is_direct` as false?

Just trying `esp_ble_gattc_open(g_gattc_if, my_mac, BLE_ADDR_TYPE_RANDOM, false);` this doesn't even try to connect even when the device is near, while `esp_ble_gattc_open(g_gattc_if, mac, BLE_ADDR_TYPE_RANDOM, true);` always works, but only when the device is in the range

**Comment by Weijian-Espressif** [comment]
@copercini, Sorry, IDF  doesn't  support background auto connection.

**Comment by 0neblock** [comment]
Hi, is this functionality planned in a future update to esp-idf ?
