### ISSUE TITLE
Unknown CMake command "idf_link_components". (IDFGH-1294)

### ISSUE THREAD

**Issue by tntclaus** [espressif/esp-idf#3588]
## Environment

- Development Kit:      `ESP32-Wrover-Kit`
- Module or chip used:  `ESP32-WROOM-32D`
- IDF version: `v4.0-dev-722-g045aaf6fb`
- Build System:        `CMake`
- Compiler version: `1.22.0-80-g6c4433a`
- Operating System:     macOS
- Power Supply:         `USB`

## Problem Description

I used to compile another version of my firmware with following CMakeLists.txt code:
```
    add_library(renamed_main.elf renamed_main/main.cpp)
    idf_link_components(renamed_main.elf "${components}")
```

But after todays git pull it looks like `idf_link_components` function no longer exists in the toolchain. I checked docs briefly but didn't find anything on this. 

What should I use as a replacement?

**Comment by renzbagaporo** [comment]
Hi @tntclaus. We've revamped using ESP-IDF as a library for 4.0 to allow for more flexibility with linking component libraries with external executables/libraries. The API is documented at https://github.com/espressif/esp-idf/blob/master/docs/en/api-guides/build-system-cmake.rst#esp-idf-cmake-build-system-api.

The example `build_system/cmake/idf_as_lib` has also been updated to reflect this change.

**Comment by tntclaus** [comment]
@renzbagaporo thank you. I figured out what to do and it really seems to be more flexible now. 

For those who want to build multiple versions of the same project here is what you can add to CMakeLists.txt:
```
add_executable(renamed_main.elf renamed_main/main.cpp)
target_link_libraries(renamed_main.elf "${components}")
```
