### ISSUE TITLE
Memory leak in esp_transport_ws_init (IDFGH-1312)

### ISSUE THREAD

**Issue by viettrungluu** [espressif/esp-idf#3602]
There's a memory leak in `esp_transport_ws_init()` in a failure case; spotted while skimming code:

https://github.com/espressif/esp-idf/blob/826ff7186ae07dc81e960a8ea09ebfc5304bfb3b/components/tcp_transport/transport_ws.c#L299

(`ws` is leaked if the `strdup()` fails).

**Comment by david-cermak** [comment]
Hi @viettrungluu 

Thank you for reporting this memory leak, will be fixed!
Please keep this open so it could be closed automatically upon merging the fix, thanks again!
