### ISSUE TITLE
guru meditation error: core 0 panic'ed (cache disabled but cached memory region accessed) when call outbox_enqueue() in mqtt_outbox.c (IDFGH-1316)

### ISSUE THREAD

**Issue by zaazbb** [espressif/esp-idf#3606]
guru meditation error: core 0 panic'ed (cache disabled but cached memory region accessed) when call outbox_enqueue() in mqtt_outbox.c.
and when i am saving my own data use  NVS blobs.

![微信图片_20190610105803](https://user-images.githubusercontent.com/5773083/59169870-a4db2700-8b6e-11e9-8b55-09c10b294b61.png)

i use esp-idf-v3.2, the mqtt lib was Integrated to esp-idf.

what can i do, to avoid this panic?

**Comment by david-cermak** [comment]
Hi @zaazbb 

Can you please include also the missing part of the screen, so that all information from core dump is included?
Also please share the exact version of IDF you use.
Thank you!

**Comment by Alvin1Zhang** [comment]
@zaazbb  Thanks for reporting, would you please help share more details of the issue? Thanks.

**Comment by Alvin1Zhang** [comment]
@zaazbb Thanks for reporting, would you please help share more details of the issue? Any updates ? Thanks.

**Comment by Alvin1Zhang** [comment]
@zaazbb Thanks for reporting. Will close due to short of feedback, feel free to reopen with more details provided. Thanks.
