### ISSUE TITLE
CMake: project() problem (with PROJECT_NAME et al.) in subprojects (IDFGH-1321)

### ISSUE THREAD

**Issue by viettrungluu** [espressif/esp-idf#3611]
## Environment

- IDF version (run ``git describe --tags`` to find it): 
    [latest version on master] 2c55fae6cf8de7f9776840b533acfc31e2de1b24
- Build System: CMake
- Operating System: Linux

## Problem Description

In CMake, after a `project()` in a subproject (added via `add_subdirectory()`), `PROJECT_NAME` (and `PROJECT_VERSION`, etc.) are not set correctly.

I'm happy that the newer versions try to restore `project()`; however, something's not right.

Suppose you modify the hello_world's top-level CMakeLists.txt to::
```
# The following lines of boilerplate have to be in your project's
# CMakeLists in this exact order for cmake to work correctly
cmake_minimum_required(VERSION 3.5)

include($ENV{IDF_PATH}/tools/cmake/project.cmake)
project(hello-world)

add_subdirectory(foo)
```
and you make a foo/CMakeLists.txt file:
```
cmake_minimum_required(VERSION 3.5)

project(foo)
message("PROJECT_NAME = " ${PROJECT_NAME})
```

You get `PROJECT_NAME = hello-world`, instead of `PROJECT_NAME = foo`.

I'm not sure what's going on, but it can be a problem with third-party code. (E.g., code I'm importing has `write_basic_package_version_file()` (from `CMakePackageConfigHelpers`) failing since `PROJECT_VERSION` isn't defined.)

### Expected Behavior

See above.

### Actual Behavior

See above.

### Steps to repropduce

See above.

**Comment by renzbagaporo** [comment]
Thank you for bringing this to our attention. A fix for this is in the works.
