### ISSUE TITLE
How to add my own static library file ( .a file ) for ESP32 to use CMAKE above esp-idf?

### ISSUE THREAD

**Issue by WangYifa** [espressif/esp-idf#3613]

**Comment by WangYifa** [comment]
Can you give me a detailed procedure?

**Comment by renzbagaporo** [comment]
It should be the same as in plain old CMake:

```
add_library(<library-name> STATIC <your-source-files>)
```
That should compile your source files and archive them to a <library-name>.a file. You can then link it to the enclosing component:

```
target_link_libraries(COMPONENT_LIB <PUBLIC|PRIVATE> <library-name>)
```

Or am I missing something with your question?

**Comment by WangYifa** [comment]
I know how to create the .a files.
but I don't know how to add a .a file to my project. 
Can you give me an example base on the HelloWorld project？

**Comment by renzbagaporo** [comment]
You mean a pre-built `.a` file, you want to link that to your project?

**Comment by JasonLrh** [comment]
你可以自己写.mk规则，然后在项目Makefile中添加引用

**Comment by renzbagaporo** [comment]
@WangYifa  Can this be closed?

**Comment by Alvin1Zhang** [comment]
@WangYifa Thanks for reporting this, due to that [IDF issue template](https://github.com/espressif/esp-idf/blob/master/docs/issue_template.md) has been ignored, will close the ticket for now. For questions, you can raise a post on our [forum](https://esp32.com). Thanks.

**Comment by drony** [comment]
I've been dealing with this for a long time. but I couldn't get it to work and finally decided to write here. please make a small "hello world" example.

**Comment by renzbagaporo** [comment]
Ok, will do @drony.

**Comment by drony** [comment]
@renzbagaporo thanks for response. i read everything about this problem. bu i can't get any result. and i'm tired:(

similiar basic sample is here. can you help me/us(i thing lot of people strugling this issue)
https://github.com/espressif/esp-idf/issues/4210

thanks is advance.
