### ISSUE TITLE
What happend when I use I2s with inner ADC and set channel_format to I2S_CHANNEL_FMT_RIGHT_LEFT  (IDFGH-1326)

### ISSUE THREAD

**Issue by l15y** [espressif/esp-idf#3615]
It seems that I read 2 data at one time.
Can I  let the 2 datas from diffent adc channel?

**Comment by Alvin1Zhang** [comment]
Thanks for reporting the issue. Would you please help provide more details as suggested in the [issue template](https://github.com/espressif/esp-idf/blob/master/docs/issue_template.md)? Thanks.

**Comment by pedroluis5** [comment]
I have the same issue, get 2 adc value equals. when I change to I2S_CHANNEL_FMT_ONLY_LEFT solve the problem, but when I increase the sample frequency the problem come back.

**Comment by negativekelvin** [comment]
https://github.com/espressif/esp-idf/issues/3714#issuecomment-508995367

**Comment by L-KAYA** [comment]
ADC + DMA now has dedicated driver and APIs in `adc_continuous.h` since IDF v5.0.

Close this issue since the legacy driver is no longer recommended and the IDF v4.x versions are all end of life.
