### ISSUE TITLE
build fails if build directory is a symlink (IDFGH-1340)

### ISSUE THREAD

**Issue by maierkomor** [espressif/esp-idf#3626]
- [x ] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [ x] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [x ] I have searched the issue tracker for a similar issue and not found a similar issue.

## Environment

- Development Kit:     not relevant
- Kit version not relevant
- Module or chip used:  not relevant
- IDF version  v3.3-beta3-34-g8c57aa024
- Build System:         Make
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it):
    crosstool-ng-1.22.0-80-g6c4433a
- Operating System:     Linux
- Power Supply:         not relevant

## Problem Description

I have a build environment with a shared source directory for multiple targets. So I have been building into symlinked build directories successfully with IDV v3.2. I.e. I prepare a build environment like this:
mkdir build.target1
ln -s build.target1 build

Then I start the build process with make.
This results in the following error:
make: *** No rule to make target "build.target1/esp32/esp32.project.ld"

Then the build process stops before linking, due to the missing .ld file.

Can the build process regarding the generation of the .ld file made agnostic to the presence of symlinks in the build directory? This is a blocker for having builds for multiple tagets...

**Comment by igrr** [comment]
As an alternative to using symlinks, you can set BUILD_DIR_BASE to point to the build directory (see https://docs.espressif.com/projects/esp-idf/en/latest/api-guides/build-system.html#optional-project-variables):

make SDKCONFIG_DEFAULTS=sdkconfig.target1 BUILD_DIR_BASE=build.target1

(or similar)
