### ISSUE TITLE
warning: 'esp_panic_dig_reset' defined but not used in panic.c (IDFGH-1349)

### ISSUE THREAD

**Issue by no1seman** [espressif/esp-idf#3632]
## Environment

- Development Kit:      ESP32-Wrover-Kit
- Kit version (for WroverKit/PicoKit/DevKitC): v4.1
- Module or chip used:  ESP32-WROVER-B
- IDF version (run ``git describe --tags`` to find it): v4.0-dev-837-g58df1d93b
- Build System:         CMake
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it):
    xtensa-esp32-elf-gcc (crosstool-NG esp32-2019r1) 8.2.0
- Operating System:    Linux
- Power Supply:         USB|external 5V&Battery

## Problem Description
On latest esp-idf 4.0 got  warning: 'esp_panic_dig_reset' defined but not used on components/esp32/panic.c:433:13

### Expected Behavior
No warning
### Actual Behavior
Warning present
### Steps to repropduce
Just build any project
### Code to reproduce this issue
Any example
## Debug Logs
...
[348/738] Building C object esp-idf/esp32/CMakeFiles/__idf_esp32.dir/panic.c.obj
/home/user/esp/esp-mdf/esp-idf/components/esp32/panic.c:433:13: warning: 'esp_panic_dig_reset' defined but not used [-Wunused-function]
 static void esp_panic_dig_reset()
             ^~~~~~~~~~~~~~~~~~~
....
## Other items if possible

**Comment by ESP-Marius** [comment]
Came across this issue in our backlog. Sorry for the super late reply....

Seems like this is not an issue anymore in any supported version of IDF, so i'll close this one.
