### ISSUE TITLE
examples/peripherals/rmt_nec_tx_rx don't work correct. (IDFGH-1360)

### ISSUE THREAD

**Issue by nopnop2002** [espressif/esp-idf#3643]
examples/peripherals/rmt_nec_tx_rx don't work correct.

## Environment

	freeRTOS version:V8.2.0
	NEWLIB version:2.2.0
	lwIP version:2-0-3-255
	ESP-IDF version:v4.0-dev-512-g6fd535c98

## Problem Description
I added LOG to the cord.

	/*
	 * @brief Check whether this value represents an NEC header
	 */
	static bool nec_header_if(rmt_item32_t* item)
	{
	    ESP_LOGI(NEC_TAG, "item->level0=%d", item->level0);
	    ESP_LOGI(NEC_TAG, "item->level1=%d", item->level1);
	    ESP_LOGI(NEC_TAG, "item->duration0=%d", item->duration0);
	    ESP_LOGI(NEC_TAG, "item->duration1=%d", item->duration1);
	    if((item->level0 == RMT_RX_ACTIVE_LEVEL && item->level1 != RMT_RX_ACTIVE_LEVEL)
	        && nec_check_in_range(item->duration0, NEC_HEADER_HIGH_US, NEC_BIT_MARGIN)
	        && nec_check_in_range(item->duration1, NEC_HEADER_LOW_US, NEC_BIT_MARGIN)) {
	        return true;
	    }
	    return false;
	}

I launched an IR cord.
It's indicated as follows in esp - idf.

	I (181000) NEC: item->level0=0
	I (181000) NEC: item->level1=1
	I (181000) NEC: item->duration0=7186
	I (181000) NEC: item->duration1=3596
	I (181010) NEC: nec_bit(0) fail
	I (181010) NEC: nec_parse_items res=-1
	I (181050) NEC: xRingbufferReceive
	I (181050) NEC: nec_parse_items res=-1
	I (181880) NEC: xRingbufferReceive
	I (181880) NEC: item->level0=0
	I (181880) NEC: item->level1=1
	I (181880) NEC: item->duration0=7207
	I (181890) NEC: item->duration1=3581
	I (181890) NEC: nec_header_if fail
	I (181900) NEC: nec_parse_items res=-1
	I (181930) NEC: xRingbufferReceive
	I (181930) NEC: nec_parse_items res=-1

I tried Arduino Library.
I launched same IR cord.
It's indicated as follows in Arduino.

	Decoded NEC(1): Value:FFA857 Adrs:0
	Decoded NEC(1): Value:FFA857 Adrs:0 (32 bits) 
	Raw samples(68): Gap:27154
	  Head: m8850  s4500
	0:m500 s650	1:m450 s650		 2:m450 s650	3:m450 s700		 
	4:m450 s650	5:m450 s650		 6:m450 s650	7:m450 s650		 
	8:m500 s1750	9:m450 s1750		 10:m500 s1750	11:m450 s1750		 
	12:m450 s1750	13:m500 s1800		 14:m450 s1700	15:m500 s1750		 

	16:m450 s1800	17:m450 s600		 18:m500 s1800	19:m450 s650		 
	20:m450 s1750	21:m450 s650		 22:m450 s700	23:m450 s600		 
	24:m500 s600	25:m500 s1750		 26:m500 s600	27:m500 s1750		 
	28:m450 s650	29:m450 s1800		 30:m450 s1750	31:m450 s1750		 

	32:m500
	Extent=67200
	Mark  min:450	 max:500
	Space min:600	 max:1800

In Arduino, Header MARK is 8850, and SPACE is 4500.
Spec of NEC-Format:
Header MARK is 9mSec(9000uSec), SPACE is 4.5mSec(4500uSec).

In esp32, Header MARK is 7207, and SPACE is 3581 
duration0 of esp32 and duration1 of esp32 is too small.
Do you have any help ?

---------------------------------------

And nec_build_items() is not correct.
It is converting from LSB.
I modified.

	/*
	 * @brief Build NEC 32bit waveform.
	 */
	static int nec_build_items(int channel, rmt_item32_t* item, int item_num, uint16_t addr, uint16_t cmd_data)
	{
	    ESP_LOGI(NEC_TAG,"nec_build_items addr=%04x cmd_data=%04x",addr,cmd_data);
	    int i = 0, j = 0;
	    if(item_num < NEC_DATA_ITEM_NUM) {
	        return -1;
	    }
	    nec_fill_item_header(item++);
	    i++;
	    uint16_t mask = 0x8000; // Add
	    for(j = 0; j < 16; j++) {
	        //if(addr & 0x1) { // Remove
	        if(addr & mask) { // Add
	            nec_fill_item_bit_one(item);
	        } else {
	            nec_fill_item_bit_zero(item);
	        }
	        item++;
	        i++;
	        //addr >>= 1; // Remove
	        mask >>= 1; // Add
	    }
	    mask = 0x8000; // Add
	    for(j = 0; j < 16; j++) {
	        //if(cmd_data & 0x1) { // Remove
	        if(cmd_data & mask) { // Add
	            nec_fill_item_bit_one(item);
	        } else {
	            nec_fill_item_bit_zero(item);
	        }
	        item++;
	        i++;
	        //cmd_data >>= 1; // Remove
	        mask >>= 1; // Add
	    }
	    nec_fill_item_end(item);
	    i++;
	    return i;
	}

I tested this code.

	/**
	 * @brief RMT transmitter demo, this task will periodically send NEC data. (100 * 32 bits each time.)
	 *
	 */
	static void rmt_example_nec_tx_task()
	{
	    vTaskDelay(10);
	    nec_tx_init();
	    esp_log_level_set(NEC_TAG, ESP_LOG_INFO);
	    int channel = RMT_TX_CHANNEL;
	    uint16_t cmd = 0x12;
	    uint16_t addr = 0x34;
	    //int nec_tx_num = RMT_TX_DATA_NUM;
	    int nec_tx_num = 1;
	    for(;;) {
	        ESP_LOGI(NEC_TAG, "RMT TX DATA");
	        size_t size = (sizeof(rmt_item32_t) * NEC_DATA_ITEM_NUM * nec_tx_num);
	        //each item represent a cycle of waveform.
	        rmt_item32_t* item = (rmt_item32_t*) malloc(size);
	        int item_num = NEC_DATA_ITEM_NUM * nec_tx_num;
	        memset((void*) item, 0, size);
	        int i, offset = 0;
	        i = nec_build_items(channel, item, item_num, ((~addr) << 8) | addr, ((~cmd) << 8) |  cmd);
	        ESP_LOGI(NEC_TAG, "nec_build_items=%d",i);
	        //To send data according to the waveform items.
	        rmt_write_items(channel, item, item_num, true);
	        //Wait until sending is done.
	        rmt_wait_tx_done(channel, portMAX_DELAY);
	        //before we free the data, make sure sending is already done.
	        free(item);
	        vTaskDelay(2000 / portTICK_PERIOD_MS);
	    }
	    vTaskDelete(NULL);
	}

It's indicated as follows in Arduino.
It look good.

	Decoded NEC(1): Value:CB34ED12 Adrs:0
	Decoded NEC(1): Value:CB34ED12 Adrs:0 (32 bits) 
	Raw samples(68): Gap:50256
	  Head: m8900  s4500
	0:m450 s1750	1:m500 s1750		 2:m450 s650	3:m500 s600		 
	4:m450 s1750	5:m550 s600		 6:m450 s1750	7:m550 s1700		 
	8:m450 s650	9:m500 s600		 10:m500 s1750	11:m500 s1700		 
	12:m500 s650	13:m500 s1700		 14:m500 s600	15:m450 s650		 

	16:m550 s1700	17:m450 s1750		 18:m550 s1700	19:m450 s700		 
	20:m500 s1700	21:m450 s1750		 22:m550 s550	23:m500 s1750		 
	24:m500 s600	25:m500 s600		 26:m550 s550	27:m550 s1700		 
	28:m500 s600	29:m550 s550		 30:m450 s1800	31:m500 s600		 

	32:m450
	Extent=67200
	Mark  min:450	 max:550
	Space min:550	 max:1800

**Comment by r1dd1ck** [comment]
@nopnop2002 
> In esp32, Header MARK is 7207, and SPACE is 3581
> duration0 of esp32 and duration1 of esp32 is too small.

Those values are not in **μs** but in **RMT cycles** :exclamation:

and as the divider in the mentioned example is set to **100**, with a base RMT clock of **80MHz**, those values give:

(7207 * 100) / 80000000 = **~9009μs**
(3581 * 100) / 80000000 = **~4476μs**

which, I believe, is **close enough** to the NEC spec :wink:

**Comment by nopnop2002** [comment]
OK.
Those values are not in μs but in RMT cycles.
I added LOG to nec_check_in_range();

	I (840) NEC: xRingbufferReceive
	I (840) NEC: item->level0=0
	I (840) NEC: item->level1=1
	I (840) NEC: item->duration0=7179
	I (850) NEC: item->duration1=3598
	I (850) NEC: duration_ticks=7179[RMT]-->8973[us]
	I (860) NEC: target_us=9000[us] margin_us=20[us]
	I (860) NEC: range(high)=9020[us] range(low)=8980[us]
	I (870) NEC: nec_header_if fail
	I (870) NEC: nec_parse_items res=-1
	I (900) NEC: xRingbufferReceive
	I (900) NEC: nec_parse_items res=-1

I change NEC_BIT_MARGIN from 20 to 100.
I got this.

	I (19860) NEC: RMT RCV --- addr: 0xff00 cmd: 0xea15


How are you thinking about nec_build_items()?

**Comment by nopnop2002** [comment]
I confirmed NEC IR Specification.
NEC IR is begin from LSB.
So your example code is right.
Thank you for your help.
Please close this issues.
![NEC-IR-SPEC](https://user-images.githubusercontent.com/6020549/59664853-c8484680-91ec-11e9-80b1-f26d7484fef5.jpg)

**Comment by r1dd1ck** [comment]
I would suggest to change the divider in the example from 100 to 96. Then the pulses can be generated exactly on spec, with 7500 & 3750 RMT cycles representing the required 9ms & 4.5ms durations.

**Comment by nopnop2002** [comment]
May i change this code?

	//#define RMT_CLK_DIV      100    /*!< RMT counter clock divider */
	#define RMT_CLK_DIV      96     /*!< RMT counter clock divider */

Thank you.

**Comment by koobest** [comment]
@nopnop2002 
Yes, You can create a PR.

thanks !!

**Comment by nopnop2002** [comment]
I close this issues.
Thanks for your support.
