### ISSUE TITLE
why did the esp idf did not use the native freertos tcp/ip stack? (IDFGH-1374)

### ISSUE THREAD

**Issue by 13824125580** [espressif/esp-idf#3656]
as we  know, the freerts has is native implementation of tcp/ip protocol stack and free to use.
and the esp idf is based on the freertos kernel, so, is there any consideration to use  lwip instead of native code?
thanks for  advice!

**Comment by negativekelvin** [comment]
At that time it still required a commercial licence.  Lwip is more popular and was used for esp8266 and known to developers.

**Comment by 13824125580** [comment]
thank you!
i have review the code of freertos protocol stack. it just only pure tcp/ip codes,others such as
mac layer(80211) and wpa supplicant is not exists. so may be this two parts mandatory for porting.
so ,did this common for lwip and native freertos stack in your esp-idf?
