### ISSUE TITLE
Using Xtensa gcc8.20 my project build fails. I could fix it. (IDFGH-1401)

### ISSUE THREAD

**Issue by ataweg** [espressif/esp-idf#3679]
I am using Windows and build my project in a Windows/DOS command shell.
I have to update C:\Espressif\esp-idf\tools\windows\windows_install_prerequisites.sh by set TOOLCHAIN_ZIP=xtensa-esp32-elf-gcc8_2_0-esp32-2019r1-win32.zip
and run in a msys32 shell: 
```
pushd /c/Espressif/esp-idf
tools/windows/windows_install_prerequisites.sh
```
When I now build my project I got a lot of warnings and one error. See details in attached txt-file
[gcc8.20_build.txt](https://github.com/espressif/esp-idf/files/3317006/gcc8.20_build.txt)

I could fix it  by adding to the top level Makefile
```
CFLAGS += -Wno-error=tautological-compare \
          -Wno-implicit-fallthrough
```
**The Error**
C:/Espressif/esp-idf/components/spiffs/spiffs/src/spiffs_nucleus.c: In function 'spiffs_populate_ix_map_v':
C:/Espressif/esp-idf/components/spiffs/spiffs/src/spiffs_nucleus.c:682:346: **error: self-comparison always evaluates to false [-Werror=tautological-compare]**
   SPIFFS_VALIDATE_OBJIX(objix->p_hdr, obj_id, objix->p_hdr.span_ix);

**The first Warnings**
C:/Espressif/esp-idf/components/console/argtable3/argtable3.c: In function 'arg_strptime':
C:/Espressif/esp-idf/components/console/argtable3/argtable3.c:1288:18: **warning: this statement may fall through [-Wimplicit-fallthrough=]**
             LEGAL_ALT(0);
                  ^
C:/Espressif/esp-idf/components/console/argtable3/argtable3.c:1290:9: note: here
         case 'H':
         ^~~~
C:/Espressif/esp-idf/components/console/argtable3/argtable3.c:1297:18: warning: this statement may fall through [-Wimplicit-fallthrough=]
             LEGAL_ALT(0);
                  ^
C:/Espressif/esp-idf/components/console/argtable3/argtable3.c:1299:9: note: here
         case 'I':
         ^~~~
C:/Espressif/esp-idf/components/console/argtable3/argtable3.c: In function 'trex_charnode':
C:/Espressif/esp-idf/components/console/argtable3/argtable3.c:3070:7: warning: this statement may fall through [-Wimplicit-fallthrough=]
     if(!isclass) {
       ^
C:/Espressif/esp-idf/components/console/argtable3/argtable3.c:3077:4: note: here
    default:
    ^~~~~~~

**Comment by antmak** [comment]
@ataweg Please check if you use ccache. You can clear it (`ccache -Cc`) or disable, then try build again. Old versions ccache cause the same problems.

**Comment by ataweg** [comment]
I haven't a ccache. I did a clean build.
The issue was introduced when switching from gcc5.2 to gcc8.2.  At this time, windows_install_prerequisites.sh was also out of date and did not install the gcc8.2 toolchain.

**Comment by antmak** [comment]
Ah, I see, sorry.

There are many changes in windows deployment in last IDF. Please try use https://dl.espressif.com/dl/esp-idf-tools-setup-2.0.exe with latest IDF, and check https://docs.espressif.com/projects/esp-idf/en/latest/get-started/windows-setup.html for details

**Comment by Alvin1Zhang** [comment]
@ataweg Thanks for reporting. Would you please help share if any updates for the issue? Thanks.

**Comment by projectgus** [comment]
Closing due to a lack of updates.
