### ISSUE TITLE
LWIP header missing C++ guards (IDFGH-1403)

### ISSUE THREAD

**Issue by jeremyherbert** [espressif/esp-idf#3681]
Hi,

It seems that lwip/include/netif/ppp/ppp.h and lwip/include/netif/ppp/pppos.h are both missing C++ guards; there could be more, I haven't checked all of the files. Interestingly, these guards are all present in the latest LWIP source from the GNU savannah page.

This of course causes PPPoS to not link properly with C++ code due to name mangling.

**Comment by zhangyanjiaoesp** [comment]
@jeremyherbert Thank you very much for pointing out our problems. We will check the LWIP headers and add the C++ guards.

**Comment by AxelLin** [comment]
This is already fixed in IDF master tree.

**Comment by AxelLin** [comment]
@Alvin1Zhang  This is already fixed and can be closed.
