### ISSUE TITLE
esp_camera_fb_get()  failed (IDFGH-1405)

### ISSUE THREAD

**Issue by Herwey** [espressif/esp-idf#3683]
Hi :
As we know, esp_camera_fb_get() is a api to get the camera buffer. But this api stopped in my main.c. I have check the function. "xQueueReceive(s_state->fb_out, &fb, portMAX_DELAY); " failed. because here is portMAX_DELAY. Can you help me ? Thanks !
```cpp
camera_fb_t* esp_camera_fb_get()
{
    if (s_state == NULL) {
        return NULL;
    }
    if(!I2S0.conf.rx_start) {
        if(s_state->config.fb_count > 1) {
            ESP_LOGD(TAG, "i2s_run");
        }
        i2s_run();
    }
    if(s_state->config.fb_count == 1) {
        xSemaphoreTake(s_state->frame_ready, portMAX_DELAY);
    }
    if(s_state->config.fb_count == 1) {
        return (camera_fb_t*)s_state->fb;
    }
    camera_fb_int_t * fb = NULL;
    if(s_state->fb_out) {
        printf("s_state->fb_out\r\n" );
        xQueueReceive(s_state->fb_out, &fb, portMAX_DELAY);
        printf("s_state->fb_out complete\r\n" );
    }
    return (camera_fb_t*)fb;
}
```

**Comment by me-no-dev** [comment]
maybe your camera is not running? If it times out, then something else is wrong. Please follow this in the esp32-camera repository and not here. The camera driver is not part of IDF :)

**Comment by Herwey** [comment]
@me-no-dev Hi, I thinke the camera works fine. it prints" I (812) camera: i2s_run". And the same camera in another esp32 works fine.

**Comment by me-no-dev** [comment]
moved to esp32-camera repo. closing here
