### ISSUE TITLE
collect2.exe: error: ld returned 1 exit status (IDFGH-1409)

### ISSUE THREAD

**Issue by meteorego** [espressif/esp-idf#3687]
Environment

    Development Kit: ESP32-DevKitC
    Kit version (for DevKitC): v1
    Module or chip used: ESP32-WROOM-32
    IDF version: v4.0-dev-71-g5beb2802e
    Build System: CMake
    Compiler version: 1.22.0-80-g6c4433a5 - 5.2.0
    Operating System: Windows 10
    Power Supply: USB

Problem Description

F:\Work\esp\hello_world>idf.py menuconfig
Checking Python dependencies...
Python requirements from D:\esp\esp-idf\requirements.txt are satisfied.
Executing action: menuconfig
Running cmake in directory f:\work\esp\hello_world\build
Executing "cmake -G Ninja -DPYTHON_DEPS_CHECKED=1 -DESP_PLATFORM=1 --warn-uninitialized f:\work\esp\hello_world"...
Warn about uninitialized values.
-- Found Git: C:/Program Files/Git/cmd/git.exe (found version "2.18.0.windows.1")
-- IDF_TARGET not set, using default target: esp32
-- The C compiler identification is GNU 5.2.0
-- The CXX compiler identification is GNU 5.2.0
-- The ASM compiler identification is GNU
-- Found assembler: C:/Program Files/Espressif/ESP-IDF Tools/tools/bin/xtensa-esp32-elf-gcc.exe
-- Check for working C compiler: C:/Program Files/Espressif/ESP-IDF Tools/tools/bin/xtensa-esp32-elf-gcc.exe
-- Check for working C compiler: C:/Program Files/Espressif/ESP-IDF Tools/tools/bin/xtensa-esp32-elf-gcc.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files/Espressif/ESP-IDF Tools/tools/bin/xtensa-esp32-elf-g++.exe
-- Check for working CXX compiler: C:/Program Files/Espressif/ESP-IDF Tools/tools/bin/xtensa-esp32-elf-g++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Project is not inside a git repository,                         will not use 'git describe' to determine PROJECT_VER.
-- Project version: 1
-- Building ESP-IDF components for target esp32
CMake Warning at D:/esp/esp-idf/tools/cmake/crosstool_version_check.cmake:8 (message):
  Xtensa toolchain C:/Program Files/Espressif/ESP-IDF
  Tools/tools/bin/xtensa-esp32-elf-gcc.exe version 5.2.0 is not the supported
  version 8.2.0.  Check Getting Started documentation or proceed at own risk.
Call Stack (most recent call first):
  D:/esp/esp-idf/components/esp32/project_include.cmake:20 (gcc_version_check)
  D:/esp/esp-idf/tools/cmake/build.cmake:287 (include)
  D:/esp/esp-idf/tools/cmake/build.cmake:440 (__build_process_project_includes)
  D:/esp/esp-idf/tools/cmake/project.cmake:315 (idf_build_process)
  CMakeLists.txt:6 (project)

CMake Warning at D:/esp/esp-idf/tools/cmake/crosstool_version_check.cmake:28 (message):
  Xtensa toolchain C:/Program Files/Espressif/ESP-IDF
  Tools/tools/bin/xtensa-esp32-elf-gcc.exe crosstool-ng version
  crosstool-ng-1.22.0-80-g6c4433a5 doesn't match supported version
  esp32-2019r1.  Check Getting Started documentation or proceed at own risk.
Call Stack (most recent call first):
  D:/esp/esp-idf/components/esp32/project_include.cmake:21 (crosstool_version_check)
  D:/esp/esp-idf/tools/cmake/build.cmake:287 (include)
  D:/esp/esp-idf/tools/cmake/build.cmake:440 (__build_process_project_includes)
  D:/esp/esp-idf/tools/cmake/project.cmake:315 (idf_build_process)
  CMakeLists.txt:6 (project)

-- Found PythonInterp: C:/Python27/python.exe (found version "2.7.14")
-- Could NOT find Perl (missing: PERL_EXECUTABLE)
-- Adding linker script F:/Work/esp/hello_world/build/esp-idf/esp32/esp32_out.ld
-- Adding linker script D:/esp/esp-idf/components/esp32/ld/esp32.project.ld.in
-- Adding linker script D:/esp/esp-idf/components/esp32/ld/esp32.peripherals.ld
-- Adding linker script D:/esp/esp-idf/components/esp_rom/esp32/ld/esp32.rom.ld
-- Adding linker script D:/esp/esp-idf/components/esp_rom/esp32/ld/esp32.rom.libgcc.ld
-- Adding linker script D:/esp/esp-idf/components/esp_rom/esp32/ld/esp32.rom.syscalls.ld
-- Adding linker script D:/esp/esp-idf/components/esp_rom/esp32/ld/esp32.rom.newlib-data.ld
-- Adding linker script D:/esp/esp-idf/components/esp_rom/esp32/ld/esp32.rom.newlib-funcs.ld
-- Adding linker script D:/esp/esp-idf/components/esp_rom/esp32/ld/esp32.rom.newlib-locale.ld
CMake Error: Could not open file for write in copy operation F:/Work/esp/hello_world/build/esp-idf/bootloader/D:/esp/esp-idf/components/bootloader/flash_bootloader_args.in.in2.tmp
CMake Error: : System Error: Invalid argument
CMake Error at D:/esp/esp-idf/components/esptool_py/project_include.cmake:181 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  D:/esp/esp-idf/components/bootloader/CMakeLists.txt:10 (esptool_py_flash_project_args)

-- Components: app_trace app_update asio bootloader bootloader_support bt coap console cxx driver efuse esp-tls esp32 esp_adc_cal esp_common esp_event esp_http_client esp_http_server esp_https_ota esp_https_server esp_ringbuf esp_rom esp_websocket_client esp_wifi espcoredump esptool_py ethernet expat fatfs freemodbus freertos heap idf_test jsmn json libsodium log lwip main mbedtls mdns mqtt newlib nghttp nimble nvs_flash openssl partition_table protobuf-c protocomm pthread sdmmc smartconfig_ack soc spi_flash spiffs tcp_transport tcpip_adapter ulp unity vfs wear_levelling wifi_provisioning wpa_supplicant xtensa
-- Component paths: D:/esp/esp-idf/components/app_trace D:/esp/esp-idf/components/app_update D:/esp/esp-idf/components/asio D:/esp/esp-idf/components/bootloader D:/esp/esp-idf/components/bootloader_support D:/esp/esp-idf/components/bt D:/esp/esp-idf/components/coap D:/esp/esp-idf/components/console D:/esp/esp-idf/components/cxx D:/esp/esp-idf/components/driver D:/esp/esp-idf/components/efuse D:/esp/esp-idf/components/esp-tls D:/esp/esp-idf/components/esp32 D:/esp/esp-idf/components/esp_adc_cal D:/esp/esp-idf/components/esp_common D:/esp/esp-idf/components/esp_event D:/esp/esp-idf/components/esp_http_client D:/esp/esp-idf/components/esp_http_server D:/esp/esp-idf/components/esp_https_ota D:/esp/esp-idf/components/esp_https_server D:/esp/esp-idf/components/esp_ringbuf D:/esp/esp-idf/components/esp_rom D:/esp/esp-idf/components/esp_websocket_client D:/esp/esp-idf/components/esp_wifi D:/esp/esp-idf/components/espcoredump D:/esp/esp-idf/components/esptool_py D:/esp/esp-idf/components/ethernet D:/esp/esp-idf/components/expat D:/esp/esp-idf/components/fatfs D:/esp/esp-idf/components/freemodbus D:/esp/esp-idf/components/freertos D:/esp/esp-idf/components/heap D:/esp/esp-idf/components/idf_test D:/esp/esp-idf/components/jsmn D:/esp/esp-idf/components/json D:/esp/esp-idf/components/libsodium D:/esp/esp-idf/components/log D:/esp/esp-idf/components/lwip F:/Work/esp/hello_world/main D:/esp/esp-idf/components/mbedtls D:/esp/esp-idf/components/mdns D:/esp/esp-idf/components/mqtt D:/esp/esp-idf/components/newlib D:/esp/esp-idf/components/nghttp D:/esp/esp-idf/components/nimble D:/esp/esp-idf/components/nvs_flash D:/esp/esp-idf/components/openssl D:/esp/esp-idf/components/partition_table D:/esp/esp-idf/components/protobuf-c D:/esp/esp-idf/components/protocomm D:/esp/esp-idf/components/pthread D:/esp/esp-idf/components/sdmmc D:/esp/esp-idf/components/smartconfig_ack D:/esp/esp-idf/components/soc D:/esp/esp-idf/components/spi_flash D:/esp/esp-idf/components/spiffs D:/esp/esp-idf/components/tcp_transport D:/esp/esp-idf/components/tcpip_adapter D:/esp/esp-idf/components/ulp D:/esp/esp-idf/components/unity D:/esp/esp-idf/components/vfs D:/esp/esp-idf/components/wear_levelling D:/esp/esp-idf/components/wifi_provisioning D:/esp/esp-idf/components/wpa_supplicant D:/esp/esp-idf/components/xtensa
-- Configuring incomplete, errors occurred!
See also "F:/Work/esp/hello_world/build/CMakeFiles/CMakeOutput.log".
See also "F:/Work/esp/hello_world/build/CMakeFiles/CMakeError.log".
cmake failed with exit code 1

Debug Logs

Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
Compiler: C:/Program Files/Espressif/ESP-IDF Tools/tools/bin/xtensa-esp32-elf-gcc.exe 
Build flags: -mlongcalls;-Wno-frame-address
Id flags:  

The output was:
1
c:/program files/espressif/esp-idf tools/tools/bin/../lib/gcc/xtensa-esp32-elf/5.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: cannot find crt1-sim.o: No such file or directory
c:/program files/espressif/esp-idf tools/tools/bin/../lib/gcc/xtensa-esp32-elf/5.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: cannot find _vectors.o: No such file or directory
c:/program files/espressif/esp-idf tools/tools/bin/../lib/gcc/xtensa-esp32-elf/5.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: cannot find -lsim
c:/program files/espressif/esp-idf tools/tools/bin/../lib/gcc/xtensa-esp32-elf/5.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: cannot find -lhandlers-sim
c:/program files/espressif/esp-idf tools/tools/bin/../lib/gcc/xtensa-esp32-elf/5.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: cannot find -lhal
collect2.exe: error: ld returned 1 exit status

Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
Compiler: C:/Program Files/Espressif/ESP-IDF Tools/tools/bin/xtensa-esp32-elf-g++.exe 
Build flags: -mlongcalls;-Wno-frame-address
Id flags:  

The output was:
1
c:/program files/espressif/esp-idf tools/tools/bin/../lib/gcc/xtensa-esp32-elf/5.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: cannot find crt1-sim.o: No such file or directory
c:/program files/espressif/esp-idf tools/tools/bin/../lib/gcc/xtensa-esp32-elf/5.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: cannot find _vectors.o: No such file or directory
c:/program files/espressif/esp-idf tools/tools/bin/../lib/gcc/xtensa-esp32-elf/5.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: cannot find -lsim
c:/program files/espressif/esp-idf tools/tools/bin/../lib/gcc/xtensa-esp32-elf/5.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: cannot find -lhandlers-sim
c:/program files/espressif/esp-idf tools/tools/bin/../lib/gcc/xtensa-esp32-elf/5.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: cannot find -lhal
collect2.exe: error: ld returned 1 exit status

Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
Compiler: C:/Program Files/Espressif/ESP-IDF Tools/tools/bin/xtensa-esp32-elf-gcc.exe 
Build flags: -mlongcalls;-Wno-frame-address
Id flags:  

The output was:
1
c:/program files/espressif/esp-idf tools/tools/bin/../lib/gcc/xtensa-esp32-elf/5.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: cannot find crt1-sim.o: No such file or directory
c:/program files/espressif/esp-idf tools/tools/bin/../lib/gcc/xtensa-esp32-elf/5.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: cannot find _vectors.o: No such file or directory
c:/program files/espressif/esp-idf tools/tools/bin/../lib/gcc/xtensa-esp32-elf/5.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: cannot find -lsim
c:/program files/espressif/esp-idf tools/tools/bin/../lib/gcc/xtensa-esp32-elf/5.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: cannot find -lhandlers-sim
c:/program files/espressif/esp-idf tools/tools/bin/../lib/gcc/xtensa-esp32-elf/5.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: cannot find -lhal
collect2.exe: error: ld returned 1 exit status

Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
Compiler: C:/Program Files/Espressif/ESP-IDF Tools/tools/bin/xtensa-esp32-elf-g++.exe 
Build flags: -mlongcalls;-Wno-frame-address
Id flags:  

The output was:
1
c:/program files/espressif/esp-idf tools/tools/bin/../lib/gcc/xtensa-esp32-elf/5.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: cannot find crt1-sim.o: No such file or directory
c:/program files/espressif/esp-idf tools/tools/bin/../lib/gcc/xtensa-esp32-elf/5.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: cannot find _vectors.o: No such file or directory
c:/program files/espressif/esp-idf tools/tools/bin/../lib/gcc/xtensa-esp32-elf/5.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: cannot find -lsim
c:/program files/espressif/esp-idf tools/tools/bin/../lib/gcc/xtensa-esp32-elf/5.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: cannot find -lhandlers-sim
c:/program files/espressif/esp-idf tools/tools/bin/../lib/gcc/xtensa-esp32-elf/5.2.0/../../../../xtensa-esp32-elf/bin/ld.exe: cannot find -lhal
collect2.exe: error: ld returned 1 exit status

**Comment by meteorego** [comment]
There have not a directory on your system named C:\esp32\?

**Comment by renzbagaporo** [comment]
Yes, this is an issue with a fix on its way. This was a regression in e8582e9a, in the meantime, you can revert your branch prior to this commit.

**Comment by meteorego** [comment]
@renzbagaporo
The version of esp-idf is the latest, but it is still the above problem, how to solve it?
