### ISSUE TITLE
fnctl( socket, F_GETFL, 0) returns error .. errorno set to 88 (not implemented)

### ISSUE THREAD

**Issue by crgregersen** [espressif/esp-idf#3694]
Problem found in latest release.
Way to reproduce :
create socket
        flags = fcntl(sock->socket, F_GETFL, 0);
flags will be negative and errorno = 88.

Reason to call fcntl is to set the socket in O_NONBLOCK

**Comment by crgregersen** [comment]
NB: Same problem with F_SETFL
I.e. fcntl basically doesn't work currently.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting the issue. Would you please help provide more details as suggested in the [issue template](https://github.com/espressif/esp-idf/blob/master/docs/issue_template.md)? Thanks.

**Comment by crgregersen** [comment]
Its not rocket science, do any call to fnctl() on a socket .. it will return error.
On old sdk it worked.
It is not a High Priority problem for us, we just use the old sdk.

Mvh,
Carsten Rhod Gregersen

**Comment by szmodz** [comment]
It's a problem with the C library in the 8.2.0 toolchain.

https://github.com/espressif/newlib-esp32/blob/esp_based_on_3_0_0/newlib/libc/syscalls/sysfcntl.c

Apparently, HAVE_FCNTL is not defined.

The quick fix is to weaken the symbol and override fcntl.

xtensa-esp32-elf-objcopy -W fcntl libc.a libc-fixed.a
