### ISSUE TITLE
Nothing appearing  on console when debugging with GDB from Eclipse (IDFGH-1418)

### ISSUE THREAD

**Issue by shmpwk** [espressif/esp-idf#3695]
I'm following the guide of debugging with GDB from Eclipse.
 
(https://docs.espressif.com/projects/esp-idf/en/latest/api-guides/jtag-debugging/debugging-examples.html?highlight=eclipse)

In an example, I inserted `printf` something, When starting `resume`, nothing appeared on console view. (On debug console, successfully showing debug log.) 
Others work well.

How can I improved?

**Comment by kolipakakondal** [comment]
Hi @shmpwk 

You should be able to see printf logs in the serial monitor output.

Are you using the IDF Eclipse plugin? If yes, please follow this https://github.com/espressif/idf-eclipse-plugin#ConfigureLaunchTerminal

**Comment by shmpwk** [comment]
Yes, I'm using the IDF Eclipse plugin. 
The explanation helped me a lot. Thank you!
