### ISSUE TITLE
[TW#12200] Small error in rmt_nec_tx_rx example.

### ISSUE THREAD

**Issue by cjsm74** [espressif/esp-idf#370]
A small typo in this file:
https://github.com/espressif/esp-idf/blob/master/examples/peripherals/rmt_nec_tx_rx/main/infrared_nec.c#L46
This line:
#define RMT_CLK_DIV 100 /*!< RMT counter clock divider */
Should reed:
#define RMT_CLK_DIV 80 /*!< RMT counter clock divider */

I was already wondering why all the readings from the ringbuffer were exactly 20% off...

**Comment by nilay994** [comment]
Can you elaborate on "readings from the ringbuffer are 20% off ?" Do you mean the speed of reading ?

**Comment by FayeY** [comment]
Hi @cjsm74 , how about this issue now?
