### ISSUE TITLE
nvs error codes missing from esp_err_to_name... __has_include("nvs.h") is false (IDFGH-1438)

### ISSUE THREAD

**Issue by bpietsch** [espressif/esp-idf#3710]
Using cmake with the esp32-2019r1-rc2 toolchain, #if __has_include("nvs.h") is evaluating to false in esp_err_to_name.c

I have nvs_flash included in my COMPONENT_REQUIRES setting, but the nvs component include directory is not being added to the compile line for esp_err_to_name.c

**Comment by Alvin1Zhang** [comment]
@bpietsch Sorry for getting back to you so late. Thanks for reporting the issue. Would you please help provide more details as suggested in the [issue template](https://github.com/espressif/esp-idf/blob/master/docs/issue_template.md)? Thanks.
