### ISSUE TITLE
I can't build esp-idf/examples/ethernet/iperf  (IDFGH-1439)

### ISSUE THREAD

**Issue by nopnop2002** [espressif/esp-idf#3711]
##  Environment

	freeRTOS version:V8.2.0
	NEWLIB version:2.2.0
	lwIP version:2-0-3-255
	ESP-IDF version:v4.0-dev-1018-gbbafd5066

## Problem Description

I can't build esp-idf/examples/ethernet/iperf 

### Steps to repropduce

My config is:

![config-1](https://user-images.githubusercontent.com/6020549/60391284-df106680-9b25-11e9-8dd7-144d85b6818f.jpg)
![config-2](https://user-images.githubusercontent.com/6020549/60391285-e3d51a80-9b25-11e9-8196-7985b6137f3a.jpg)
![config-3](https://user-images.githubusercontent.com/6020549/60391286-e899ce80-9b25-11e9-980e-593fa0699549.jpg)

	/home/nop/esp-idf/examples/ethernet/iperf/main/cmd_ethernet.c: In function 'phy_device_power_enable_via_gpio':
	/home/nop/esp-idf/examples/ethernet/iperf/main/cmd_ethernet.c:52:5: error: implicit declaration of function 'gpio_pad_select_gpio' [-Werror=implicit-function-declaration]
	     gpio_pad_select_gpio(PIN_PHY_POWER);
	     ^
	/home/nop/esp-idf/examples/ethernet/iperf/main/cmd_ethernet.c:53:5: error: implicit declaration of function 'gpio_set_direction' [-Werror=implicit-function-declaration]
	     gpio_set_direction(PIN_PHY_POWER, GPIO_MODE_OUTPUT);
	     ^
	/home/nop/esp-idf/examples/ethernet/iperf/main/cmd_ethernet.c:53:39: error: 'GPIO_MODE_OUTPUT' undeclared (first use in this function)
	     gpio_set_direction(PIN_PHY_POWER, GPIO_MODE_OUTPUT);
	                                       ^
	/home/nop/esp-idf/examples/ethernet/iperf/main/cmd_ethernet.c:53:39: note: each undeclared identifier is reported only once for each function it appears in
	/home/nop/esp-idf/examples/ethernet/iperf/main/cmd_ethernet.c:55:9: error: implicit declaration of function 'gpio_set_level' [-Werror=implicit-function-declaration]
	         gpio_set_level(PIN_PHY_POWER, 1);
	         ^
	/home/nop/esp-idf/examples/ethernet/iperf/main/cmd_ethernet.c: At top level:
	cc1: warning: unrecognized command line option '-Wno-frame-address'
	cc1: some warnings being treated as errors
	/home/nop/esp-idf/make/component_wrapper.mk:289: recipe for target 'cmd_ethernet.o' failed
	make[1]: *** [cmd_ethernet.o] Error 1
	/home/nop/esp-idf/make/project.mk:582: recipe for target 'component-main-build' failed
	make: *** [component-main-build] Error 2

## solution

I added this line to cmd_ethernet.c:

	#include <stdio.h>
	#include <string.h>
	#include "freertos/FreeRTOS.h"
	#include "freertos/event_groups.h"
	#include "tcpip_adapter.h"
	#include "esp_log.h"
	#include "esp_console.h"
	#include "esp_event.h"
	#include "esp_eth.h"
	#include "argtable3/argtable3.h"
	#include "iperf.h"
	#include "sdkconfig.h"

	#include "driver/gpio.h" // Add nopnop2002

## One more problem

I could build.
But I got this message.

	I (0) cpu_start: App cpu up.
	I (225) heap_init: Initializing. RAM available for dynamic allocation:
	I (232) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM
	I (238) heap_init: At 3FFB4438 len 0002BBC8 (174 KiB): DRAM
	I (244) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM
	I (251) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
	I (257) heap_init: At 4008C12C len 00013ED4 (79 KiB): IRAM
	I (263) cpu_start: Pro cpu start user code
	I (282) spi_flash: detected chip: generic
	I (282) spi_flash: flash io: dio
	I (282) cpu_start: Starting scheduler on PRO CPU.
	I (0) cpu_start: Starting scheduler on APP CPU.
	I (352) phy_device_power_enable_via_gpio: Power On Ethernet PHY
	I (362) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE

	esp32> ethernet start
	I (31672) emac: emac reset done
	esp32> I (36372) tcpip_adapter: eth ip: 192.168.10.118, mask: 255.255.255.0, gw: 192.168.10.1
	esp32>
	esp32> iperf -u -c 192.168.10.41 -i 3 -t 30
	iperf: option "-t" requires an argument
	esp32> iperf -u -c 192.168.10.41 -t 30 -i 3
	iperf: option "-i" requires an argument

**Comment by suda-morris** [comment]
Thanks @nopnop2002 for your effort in the example, we will look into it ASAP.
BTW, the Ethernet driver has been refactored these days, and the build error should be fixed there.

**Comment by nopnop2002** [comment]
Hello.
I canged .max_cmdline_args = 16.
It's OK.
When you fixed example code, please close this isusues.
Thank you for your support.
