### ISSUE TITLE
general Issues on examples with used hardware ( tlk110....)

### ISSUE THREAD

**Issue by ESP32DE** [espressif/esp-idf#373]
hi guys

a please to you developers at espressif who build example code for the idf:

can you please refer to the used hardware in your example
with shematic and used hardware, pins and used ESP32 Board?

there are more ESP32 Boards on the market and each has other hardware reference.

this would help in future us to test and build the same environment on hardware 
and test your examples like you have wrote and thinked in code

cause this is a general theme it will post the same in esp32 forum
https://esp32.com/viewtopic.php?f=2&t=1259

thank you for your understanding!

best wishes
rudi ;-)

**Comment by projectgus** [comment]
Regarding ethernet exmaples & hardware, there will be a reference design available soon (final revision are being done now). Once the reference design is final, the schematic will be published and the examples will refer to this design.

Regarding the other examples, if there are hardware details that are missing from a particular example please let us know and we will add them to the README.
