### ISSUE TITLE
Several bootloaders on esp32 and update bootloaders. (IDFGH-1462)

### ISSUE THREAD

**Issue by ArTyGill** [espressif/esp-idf#3732]
I can create custom bootloader for load two secondary bootloaders(to choose), for OTA1 and OTA2?

I would like the bootloaders to be updated along with the app.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting the issue. Would you please help provide more details as suggested in the [issue template](https://github.com/espressif/esp-idf/blob/master/docs/issue_template.md)? Thanks.

**Comment by negativekelvin** [comment]
You could possibly create 1 custom 2nd stage bootloader and two custom 3rd stage bootloaders, but it is not supported.  Why can't you just put the custom code in the app?  What does your bootloader do?

**Comment by ArTyGill** [comment]
I want update esp-idf with ota.

**Comment by negativekelvin** [comment]
But why do you want to update the bootloader and not just the app?

**Comment by ArTyGill** [comment]
I want to update with ota the bootloader and the application together

**Comment by negativekelvin** [comment]
But what is your reason?

**Comment by ArTyGill** [comment]
@negativekelvin New features and stability enhancement, bug fixes, OTA updates.

**Comment by ArTyGill** [comment]
and do not think about what esp-idf bootloader is installed before the OTA.

**Comment by negativekelvin** [comment]
Bootloader is designed to be minimal, backwards compatible, and never updated.  So unless you need to do something special, it's probably a waste of time.  I don't think there will be an official support for it, but try it yourself if you want.  You may as well make partition table upgradable too.

**Comment by ArTyGill** [comment]
Can I run the standard esp-idf bootloader using my bootloader?

**Comment by negativekelvin** [comment]
Yes, it would be smart to make it work that way

**Comment by ArTyGill** [comment]
I will try to run.
