### ISSUE TITLE
Compile errors in bt/common/osi (config/alaram) with latest dev/master branch (IDFGH-1464)

### ISSUE THREAD

**Issue by kvbulusu** [espressif/esp-idf#3734]
Environment
Development Kit: ESP32-LyraT
Module or chip used: ESP32-WROOM-32
IDF version (run git describe --tags to find it): v4.0-dev-1095-g16014079f
Build System: Make
Compiler version (run xtensa-esp32-elf-gcc --version to find it): xtensa-esp32-elf-gcc (crosstool-NG esp32-2019r1) 8.2.0
Operating System: Linux
Power Supply: USB

Problem Description:
Error while compiling.

esp-idf/components/bt/common/osi/config.c:446:49: error: '%d' directive output may be truncated writing between 1 and 10 bytes into a region of size 7 [-Werror=format-truncation=]
snprintf(keyname, keyname_bufsz, "%s%d", CONFIG_KEY, i);
^~
esp-idf/components/bt/common/osi/alarm.c:85:1: error: 'xyz' undeclared (first use in this function)
xyz
^~~
esp-idf/components/bt/common/osi/alarm.c:85:1: note: each undeclared identifier is reported only once for each function it appears in
esp-idf/components/bt/common/osi/alarm.c:85:4: error: expected ';' before 'if'
xyz
^
;
if ((alarm_cbs = (osi_alarm_t *)osi_malloc(sizeof(osi_alarm_t) * ALARM_CBS_NUM)) == NULL) {

**Comment by blueMoodBHD** [comment]
Hi, @kvbulusu,  Thanks for reporting this.
```
esp-idf/components/bt/common/osi/alarm.c:85:1: note: each undeclared identifier is reported only once for each function it appears in
esp-idf/components/bt/common/osi/alarm.c:85:4: error: expected ';' before 'if'
xyz
```
This one have been fixed, refer to commit a1ae89f8e2b5b85a3371fff4cd2f7a7acc11cfc8

```
esp-idf/components/bt/common/osi/config.c:446:49: error: '%d' directive output may be truncated writing between 1 and 10 bytes into a region of size 7 [-Werror=format-truncation=]
snprintf(keyname, keyname_bufsz, "%s%d", CONFIG_KEY, i);
```
And, I will fix this one, soon.
