### ISSUE TITLE
ESP32-BLE+ETH+OTA (IDFGH-1470)

### ISSUE THREAD

**Issue by robcim** [espressif/esp-idf#3739]
Hi all,
I'm Roberto. I use a ESP32 with BLE and ETH communication. I add the OTA mode (WebUpdate) but he's not work. I have this error in console: [E][WiFiClient.cpp:338] write(): 11

Anyone can help me please.
Thank you

**Comment by negativekelvin** [comment]
WebUpdate and WiFiClient are not part of esp-idf, they are arduino-esp32 code, you need to ask for support here

https://esp32.com/viewforum.php?f=19
https://github.com/espressif/arduino-esp32

**Comment by Alvin1Zhang** [comment]
@negativekelvin Thanks for the notes. @robcim Please help raise an issue in https://github.com/espressif/arduino-esp32 or post a topic in https://esp32.com/viewforum.php?f=19 Thanks.
