### ISSUE TITLE
did the esp32 freertos smp implementation use the IPI(inter processor interrupt) mechanism? (IDFGH-1479)

### ISSUE THREAD

**Issue by 13824125580** [espressif/esp-idf#3748]
IPI usually used for inter-process communication for scheduler or ipc implementation in smp.
so did the freeRTOS smp implementation on ESP32 use the IPI mechanism?
thanks for your reply!

**Comment by negativekelvin** [comment]
https://docs.espressif.com/projects/esp-idf/en/latest/api-reference/system/ipc.html

**Comment by Alvin1Zhang** [comment]
@13824125580 Thanks for reporting the issue. @negativekelvin Thanks for the notes. Feel free to reopen the ticket if you still have questions @13824125580 . Thanks.
