### ISSUE TITLE
how can i change the app start address? 

### ISSUE THREAD

**Issue by chenkaiyao** [espressif/esp-idf#375]
the default app start address is 0x10000.  if i want to change the address to 0x14000,  what should i do?  how should i change the linker files?  thanks!

**Comment by negativekelvin** [comment]
Check partition tables http://esp-idf.readthedocs.io/en/latest/partition-tables.html

**Comment by projectgus** [comment]
I'm going to close this as I think the answer is covered in the partition table docs (if you set a custom partition table CSV then you can also set a matching menuconfig option for the factory app partition offset, and use whatever offset you like the for the factory app.)

Please reopen this doesn't solve the problem for you.

**Comment by chenkaiyao** [comment]
thanks
