### ISSUE TITLE
[Doc] Incorrect opcode for ULP : REG_WR (IDFGH-1481)

### ISSUE THREAD

**Issue by hex007** [espressif/esp-idf#3751]
https://www.espressif.com/sites/default/files/documentation/esp32_technical_reference_manual_en.pdf#180

The op code for `REG_WR` in the technical reference should be `4'd1` and not `4'd2`

![Screenshot from 2019-07-06 14-24-13](https://user-images.githubusercontent.com/1689246/60761261-cd353480-9ff9-11e9-8881-99c4bbf1ec04.png)

![Screenshot from 2019-07-06 14-21-10](https://user-images.githubusercontent.com/1689246/60761241-6a439d80-9ff9-11e9-8e2b-0203b6438b53.png)

**Comment by Esp-Doc** [comment]
Hi, thank you for pointing this out! The Documentation team has fixed the typo. Updated version will soon be released.

**Comment by hex007** [comment]
@Esp-Doc if possible also include what the syntax `4'd1` means. It is not quite apparent to first timers

**Comment by Esp-Doc** [comment]
Will do. Thanks!
