### ISSUE TITLE
Advice wanted about IRAM before rollout (IDFGH-1498)

### ISSUE THREAD

**Issue by korstiaanS** [espressif/esp-idf#3764]
Hi all,

I have a perfect running application (tracking device, using GSM/GPRS/WIFI/BLE) but before I want to rollout to our vehicles I want to make sure that it won't fail.

If I run make size, I see:

Total sizes:
 DRAM .data size:   15508 bytes
 DRAM .bss  size:   55984 bytes
Used static DRAM:   71492 bytes (  53088 available, 57.4% used)
Used static IRAM:  125080 bytes (   5992 available, 95.4% used)
      Flash code:  992689 bytes
    Flash rodata:  245784 bytes
Total image size:~1379061 bytes (.bin may be padded larger)

I'm worried about that 95.4% IRAM used.
Can that be a problem while running? 
Does that mean that I can't get any more code into the ESP?
Are they ways to decrease this?

I already changed the parameter CONFIG_ESP32_WIFI_IRAM_OPT so I gain 10K.
(I only use wifi for OTA)

I have a ESP32 with 4MB SPI RAM.

Thanks for helping/explaining.

Korstiaan

**Comment by projectgus** [comment]
Hi @korstiaanS ,

Thanks for the well explained question.

You won't run out of IRAM while running. Nothing in ESP-IDF itself allocates IRAM dynamically, although it's [possible to do this in your app](https://docs.espressif.com/projects/esp-idf/en/latest/api-reference/system/mem_alloc.html#bit-accessible-memory).

There is a risk that a future ESP-IDF update will increase IRAM usage, as this has happened in the past. However we're making an effort to keep IRAM usage in check, so this should be OK (and 5KB is still a lot of headroom for this).

Probably any code you add in your firmware won't increase IRAM usage, unless you need interrupt handlers to run while flash cache is disabled (ie when writing or erasing flash).

If you only use BLE, you may get some IRAM back by switching to the new NimBLE BLE stack option in ESP-IDF V4.0 (you will certainly reduce overall code size).

Hopefully that answers the question.

For future reference, the best place to ask a question like this (which isn't reporting an issue in ESP-IDF) is the forum: https://esp32.com
