### ISSUE TITLE
Warning error on current version of master branch (IDFGH-1500)

### ISSUE THREAD

**Issue by KaeLL** [espressif/esp-idf#3766]
I get the felling dev's don't build esp-idf prior to pushing changes, do they? LoL

esp-idf/components/bt/common/osi/config.c:446:49: error: '%d' directive output may be truncated writing between 1 and 10 bytes into a region of size 7 [-Werror=format-truncation=]
             snprintf(keyname, keyname_bufsz, "%s%d", CONFIG_KEY, i);

**Comment by Weijian-Espressif** [comment]
@KaeLL, Sorry for that. we have fixed the bug, but have not update to the github.
![企业微信截图_9ff1bd2a-d518-4f6e-80d1-716ca84603a5](https://user-images.githubusercontent.com/16891442/61098767-b461ce80-a492-11e9-9bdc-c23d2373f3bc.png)

**Comment by Weijian-Espressif** [comment]
![企业微信截图_9ff1bd2a-d518-4f6e-80d1-716ca84603a5](https://user-images.githubusercontent.com/16891442/61098806-ce031600-a492-11e9-91e5-991b06f34dc9.png)

**Comment by Alvin1Zhang** [comment]
@KaeLL Thanks for reporting, the issue has been fixed and available. Please help try, and feel free to reopen if the issue still happens. Thanks.
