### ISSUE TITLE
Disabling "Support ESP32 internal EMAC controller" breaks build (IDFGH-1504)

### ISSUE THREAD

**Issue by nifomorph** [espressif/esp-idf#3770]
## Environment

- Development Kit:         none
- Module or chip used:  ESP32
- IDF version:                  v4.0-dev-1195-g38b7744
- Build System:              Make
- Compiler version:       xtensa-esp32-elf-gcc (crosstool-NG esp32-2019r1) 8.2.0
- Operating System:     macOS
- Power Supply:            USB

## Problem Description
Disabling "Support ESP32 internal EMAC controller" breaks build.

### Expected Behavior
ESP-IDF should compile with valid options set in menuconfig.

### Actual Behavior
Build stops on undefined symbols in `components/soc/esp32/emac_hal.c`

### Steps to reproduce
1. make menuconfig
2. De-select `Component config-->Ethernet-->Support ESP32 internal EMAC controller`
3. make all

### Code to reproduce this issue
Any esp-idf based project

## Debug Logs
N/A

## Other items if possible
Excerpt from build log:
```
CC build/bootloader/soc/esp32/emac_hal.o
/Users/nif/Documents/esp/esp-idf/components/soc/esp32/emac_hal.c: In function 'emac_hal_reset_desc_chain':
/Users/nif/Documents/esp/esp-idf/components/soc/esp32/emac_hal.c:141:54: error: 'CONFIG_ETH_DMA_RX_BUFFER_NUM' undeclared (first use in this function); did you mean 'CONFIG_ESP32_WIFI_TX_BUFFER_TYPE'?
                    sizeof(eth_dma_rx_descriptor_t) * CONFIG_ETH_DMA_RX_BUFFER_NUM);
                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                      CONFIG_ESP32_WIFI_TX_BUFFER_TYPE
```

[sdkconfig](https://github.com/espressif/esp-idf/files/3383851/sdkconfig.txt)

**Comment by suda-morris** [comment]
Thank you @nifomorph we will fix it ASAP.
