### ISSUE TITLE
New toolchain required (IDFGH-1533)

### ISSUE THREAD

**Issue by Reiner1210** [espressif/esp-idf#3797]
Hello,

the new IDF requires a new toolchain but the links in you docu are still the old one
I only found this
https://www.esp32.com/viewtopic.php?t=7400

**Comment by negativekelvin** [comment]
https://docs.espressif.com/projects/esp-idf/en/latest/get-started/index.html#get-started-set-up-tools

**Comment by Reiner1210** [comment]
@negativekelvin And where will I find the xtensa compiler for Linux - nothing in your docu!

**Comment by projectgus** [comment]
Hi @Reiner1210,

If you're using the recent ESP-IDF master branch, the gcc 8 toolchain is needed and we've introduced the IDF Tools Installer which can manage user installation of the correct tools including the toolchain. It's mentioned here:
https://docs.espressif.com/projects/esp-idf/en/latest/get-started/index.html#id3

As you probably are familiar, if you're using an ESP-IDF v3.x branch or stable release, the gcc 5 toolchain is standard and the download links are provided directly in the docs:
https://docs.espressif.com/projects/esp-idf/en/stable/get-started/linux-setup.html#toolchain-setup

**Comment by projectgus** [comment]
Will add some description under the Linux and macOS heading so it's clearer what this does (downloads all of the required tools, including the compiler.)

**Comment by Reiner1210** [comment]
Ok. In the meantime I have compiled it from sources :-)

**Comment by projectgus** [comment]
Reopening until we have a fix in the docs for this.

**Comment by igrr** [comment]
Description of the install scripts has been added in https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/tools/idf-tools.html#install-scripts, and the links to the toolchain in https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/tools/idf-tools.html#list-of-idf-tools.
