### ISSUE TITLE
esp32_out.ld dependency breaks when BUILD_DIR_BASE contains subdir

### ISSUE THREAD

**Issue by jmattsson** [espressif/esp-idf#38]
In the NodeMCU CI we use the documented BUILD_DIR_BASE to build different configurations into different output directories (e.g. `build/float` and `build/integer`). With the latest IDF the hardcoded dependency on `../include/sdkconfig.h` breaks, as it would now be ../../include/sdkconfig. That is, this line:
`esp32_out.ld: $(COMPONENT_PATH)/ld/esp32.ld ../include/sdkconfig.h`

More things break if BUILD_DIR_BASE is set to something that isn't part of `build/` as Kconfig appears to ignore BUILD_DIR_BASE and insists on writing to `build/` even if BUILD_DIR_BASE is set to e.g. `/tmp/mybuild`.

I believe the short-term fix would be to add a VPATH (or the lower-case version thereof) for `$(PROJECT_PATH)/build/include`, and list the dependency as simply `sdkconfig.h`.

Edit: on second thought, simply using $(PROJECT_PATH)/build instead of a relative path is probably easier, considering that it needs to be passed to $(CC) as an include as well.

**Comment by projectgus** [comment]
Hi @jmattsson ,

Thanks for reporting this. It looks like there were a few problems preventing building out-of-tree via `BUILD_DIR_BASE`.

I've submitted fixes into our internal test/review system and also added out-of-tree test cases to the automatic build system tests. It might be a little while before those fixes get merged to master, as China is on holidays this week (Golden Week).

So in the meantime I've also pushed the fixes here:
https://github.com/espressif/esp-idf/tree/bugfix/build_dir_base

Please let me know if it fixes this issue.


Angus

**Comment by jmattsson** [comment]
Thanks, it looks like you've done a thorough sweep here! I'll try to give this a spin tomorrow.

**Comment by jmattsson** [comment]
Mixed results:

*  Out-of-tree build worked, but yielded a whole bunch of:
  `make[2]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.`
  On this branch I also get these when not overriding BUILD_DIR_BASE. The master branch does not   have this issue. I build with `-j 8 -l 8` in MAKEFLAGS by default.

* In-tree build with `BUILD_DIR_BASE=build/integer` fails with:
  `make[2]: *** No rule to make target 'build/float/bootloader/bootloader.bin'.  Stop.`

**Comment by projectgus** [comment]
> warning: jobserver unavailable: using -j1. Add '+' to parent make rule.

Interesting, will investigate. We clear MAKEFLAGS when we recurse a couple of times, to avoid other make-related weirdness. Possibly we weren't actually clearing MAKEFLAGS correctly one of those times!

> In-tree build with BUILD_DIR_BASE=build/float fails

Ah, I missed that nuance in the original bug report. Will add support for providing a relative path in this variable.

**Comment by jmattsson** [comment]
Parallel builds have been working great so far, I haven't run into any dependency weirdness (that I've noticed).

**Comment by projectgus** [comment]
The problem wasn't parallel-build related, it was to do with setting other MAKEFLAGS that we didn't want propagating to some submakes.

I think I've taken care of it now. No more jobserver warnings, and I can build when BUILD_DIR_BASE is a relative path. Please let me know how you go!

**Comment by jmattsson** [comment]
Looking good here too, thanks!
