### ISSUE TITLE
When i work in 3.1 branch，WARNING: Failed to find Xtensa toolchain, may need to alter PATH or set one in the configuration menu (IDFGH-1549)

### ISSUE THREAD

**Issue by xuhongv** [espressif/esp-idf#3811]
When i work in 3.1 branch in windows10 , then error message : 

`WARNING: Failed to find Xtensa toolchain, may need to alter PATH or set one in the configuration menu
`

But i checkout in master branch in windows10 , is normal to build ...

**Comment by xuhongv** [comment]
![image](https://user-images.githubusercontent.com/25237870/61676596-2bb71e00-ad2f-11e9-9247-0f1618d2f6ab.png)

**Comment by xuhongv** [comment]
![image](https://user-images.githubusercontent.com/25237870/63253280-1ee10800-c2a4-11e9-859c-40f38fe6b30f.png)

**Comment by mohammedkw11** [comment]
hi @xuhongv , did you find the solution? I'm facing the same problem now.

**Comment by igrr** [comment]
@mohammedkw11 @xuhongv Please refer to the getting started guides for the IDF version you are using. According to the screenshot, the compiler version is 8.2 (release esp32-2019r1), which is used in IDF v4.0 and later. For IDF versions 3.x, the expected compiler version is 5.2. Please check this page for setting up the correct compiler version: https://docs.espressif.com/projects/esp-idf/en/v3.3.1/get-started/windows-setup.html.
