### ISSUE TITLE
fatal error: eth_phy/phy_lan8720.h: No such file or directory (IDFGH-1565)

### ISSUE THREAD

**Issue by manish5897** [espressif/esp-idf#3825]
## Environment
- Module or chip used:  [ESP32-WROOM-32]
- IDF version : v4.0-dev-1287-gd7e659df2
- Build System:         [Make]
- Compiler version : 1.22.0-80-g6c4433a
- Operating System:     [Linux]
- Power Supply:         [USB]

## Problem Description
The library eth_phy/phy_lan8720.h is not found in the esp-idf. May be the library is depreciate. It shows compilation error. 

### Code to reproduce this issue

```cpp
#include "eth_phy/phy_lan8720.h"

void app_main()
{
    
}

```

## Debug Logs

```
/home/manish/esp32_led/main/ethernet.cpp:26:33: fatal error: eth_phy/phy_lan8720.h: No such file or directory
compilation terminated.
/home/manish/esp/esp-idf/make/component_wrapper.mk:291: recipe for target 'ethernet.o' failed
make[1]: *** [ethernet.o] Error 1
/home/manish/esp/esp-idf/make/project.mk:584: recipe for target 'component-main-build' failed

**Comment by suda-morris** [comment]
@manish5897 Yes, Ethernet driver has refactored in v4.0. Now we have a new approach to install the Ethernet driver. https://github.com/espressif/esp-idf/blob/master/examples/ethernet/basic/main/ethernet_example_main.c#L83

**Comment by manish5897** [comment]
Let me know, the stable idf version in which #include "eth_phy/phy_lan8720.h" library is working fine.

**Comment by suda-morris** [comment]
@manish5897 Thank you. If you are going to try the new `esp-eth` driver, feel free to let us know when you come into trouble. Or would you mind to close this issue since it's not a real bug in v4.0?

**Comment by dvogureckiy99** [comment]
Hi, I don't understand, how can I solve this issue ?
