### ISSUE TITLE
Update to the latest version, smart config  still be errors, although the number is very small (IDFGH-1569)

### ISSUE THREAD

**Issue by GitOfLance** [espressif/esp-idf#3829]
### Environment
- Module or chip used: ESP32-WROOM-32
- IDF version : v4.0-dev-728-g826ff7186
- Build System: Make
- Compiler version : xtensa-esp32-elf-
- Operating System: Ubuntu 18.04
- Power Supply: USB

### Problem Description
I used to configure wifi with smartconfig, there was an error, which is described in this [Issues](https://github.com/espressif/esp-idf/issues/3586).
Two days ago, I saw a patch about `wifi stop` and updated the code version.
During these two days of use, smartconfig no longer has an error every time, but an error still occurs that causes the system to crash. There were about 3 errors in 100 uses.
![wifi smartconfig bug](https://user-images.githubusercontent.com/48943389/61873303-34b71380-af18-11e9-950f-934ae40c8d2f.png)

In addition, although the function `esp_wifi_set_storage(WIFI_STORAGE_FLASH)` was successfully called when the wifi was initialized, after the restart, the function `esp_wifi_get_config` was called but no information about wifi was obtained for connecting to wifi.
What if I want to save the wifi information configured via smartconfig and use this information to automatically connect to the next time I start it?

**Comment by filzek** [comment]
One thing is clear, WiFi need to be initialized and full set in the main app or it will always faill since 20 days ago.

**Comment by GitOfLance** [comment]
Can you make it clear?
The wifi initialization function is called in `app_main()`. What about `WiFi need to be initialized and full set in the main app or it will always faill since 20 days ago.` mean?
In this `ISSUSE`[HERE LINK](https://github.com/espressif/esp-idf/issues/3586), isn't that the problem solved? Why is there an error when using smartconfig?
In addition, in the initialization function I call the function "`esp_wifi_set_storage(WIFI_STORAGE_FLASH)`", why does the function "`esp_wifi_get_config(ESP_IF_WIFI_STA, &wifi_staconfig.sta);`" not get ssid and pwd after starting the program and wifi initialization?

**Comment by GitOfLance** [comment]
HI, @filzek 
I synced the `IDF` code on `August 29, 2019` and ran the `example/wifi/smart_conifg` test code you provided. The error is as follows:
![1121](https://user-images.githubusercontent.com/48943389/62354908-7c552500-b540-11e9-9187-3062a3d590a4.png)

Are you sure that the smartconfig demo is working?

**Comment by GitOfLance** [comment]
The chip model I am using is: `ESP32-WROVER-B`, with `8MB PSRAM` and `8MB Flash`. Does this affect?

**Comment by liuzfesp** [comment]
HI @GitOfLance , just can't reproduce this issue with smartconfig example in v4.0-dev-728-g826ff7186. Does this issue happen with default menuconfig?

**Comment by GitOfLance** [comment]
Hi, @liuzfesp 
Yes, I use the `esp32 kit V3` development board and default menuconfig, the example in IDF will be wrong.

**Comment by filzek** [comment]
@GitOfLance there is some real issue with smartconfig, but the example compiles fine and runs okay in some wifi routers (it seens that has problem to found and match sniffer in some wifi routers), there is no problem on build and run in any of our testing boards here, all based on wrover-b modules 4/8 and 8/8mb.

Did you try to redownload the entire master SDK again, maybe there is some broken parts in your sdk that coundnt be fix or upgrade by a simple git pull --rec, so, please advise to uninstall and install it again.

**Comment by GitOfLance** [comment]
Hi, @filzek 
I deleted the `esp-idf` yesterday and pull the repository from github by `git clone --recursive https://github.com/espressif/esp-idf.git`. Use the default menuconfig and the provided demo (`exmaple/wifi/smart_config`).
Run this demo on `esp32-wrover-b`. In most cases, I can configure the wifi through smartconfig, but there will be a certain probability that the system will crash, as shown in the following figure:
![smartconfig-11111](https://user-images.githubusercontent.com/48943389/62543631-dc293400-b890-11e9-8df2-281a358bfb16.png)
I uesd demo and IDF version:
![111111](https://user-images.githubusercontent.com/48943389/62544025-9c168100-b891-11e9-8e1a-f2acb9caeb31.png)

**##So, I can say with certainty that the demo of smartconfig is not completely correct.##**

In addition, I initialized and connected wifi according to the `example/wifi/scan` method, the test result is normal, but my project needs to allow the wifi to be configured repeatedly, so I need the wifi initialization function to be repeatable. Before each initialization, I will call the some functions to release the wifi resource.
wifi init function:
```
void wifi_init_ilock()
{
    int ret = 0;
    
    do {   
        wifi_base_init();       //底层的初始化函数

        /* 适应重复初始化 */
        if (EventGroup_wifiilock)
        {
            ESP_LOGW("wifi init ilock", "wifi deinit");
            wifi_deinit_ilock();
            vEventGroupDelete(EventGroup_wifiilock);
            EventGroup_wifiilock = NULL;
        }
        EventGroup_wifiilock = xEventGroupCreate();
        if (NULL == EventGroup_wifiilock)
        {
            ret = -1;
            ESP_LOGE(__FUNCTION__, "Create wifiilock EventGroup failed");
            break;
        }

        /* 监测base抛出的事件 */
        xTaskCreate(wifi_base_event_monitor, "wifi_monitor", 1024 * 4, NULL, configMAX_PRIORITIES - 2, &wifievent_monitor);  

        if (wifievent_monitor)
            ESP_LOGI("wifi init", "create wifi task success");
        else
            ESP_LOGI("wifi init", "crate wifi task failed");
    }while(0);

    /* 抛出本层的异常 */
    if (ret < 0)        
    {
        if (EventGroup_wifiilock)
            xEventGroupSetBits(EventGroup_wifiilock, wifiilockevent_unavailable);
    }
}



void wifi_base_init()
{
    int ret = 0;     //返回值
    wifi_init_config_t wificonfig = WIFI_INIT_CONFIG_DEFAULT();

    do
    {
        /* 终止上次wifi，并且释放相关资源 */
        /* 创建事件组，如果之前创建过，说明已经初始化过wifi，则删除 */
        if (EventGroup_wifibase)
        {
            wifi_stop_release_sources();        // 终止wifi,释放资源
            vEventGroupDelete(EventGroup_wifibase);     //必须在stop函数后面删除，因为stop函数会设置这个事件组中的事件
            EventGroup_wifibase = NULL;
        }            
        EventGroup_wifibase = xEventGroupCreate();
        if (NULL == EventGroup_wifibase)
        {
            ret = -1;
            ESP_LOGE(__FUNCTION__, "Create EventGroup Failed");
            break;
        }

        /* 开始初始化 */
        tcpip_adapter_init();
        if (ESP_OK != esp_event_loop_create_default())      //创建事件循环组，应用层依赖的核心
        {
            ret = -1;
            ESP_LOGE(__FUNCTION__, "Create Event Loop Failed");
            break;
        }
        //wificonfig = WIFI_INIT_CONFIG_DEFAULT();      //必须定义时才能用这种方式初始化
        if (ESP_OK != esp_wifi_init(&wificonfig))           //使用默认配置初始化wifi底层相关配置和资源
        {
            ret = -1;
            ESP_LOGE(__FUNCTION__, "esp_wifi_init failed");
            break;
        }

        /* 注册监测的默认事件循环中的事件组和事件，以及相应的处理函数 */
        if (ESP_OK != esp_event_handler_register(WIFI_EVENT, ESP_EVENT_ANY_ID, &wifi_base_event_loop_handler, NULL))     //检测wifi事件组的任意事件
        {

            ret = -1;
            ESP_LOGE(__FUNCTION__, "register esp event loop handler for [WIFI_EVENT] failed");
            break;
        }

        if (ESP_OK != esp_event_handler_register(IP_EVENT, IP_EVENT_STA_GOT_IP, &wifi_base_event_loop_handler, NULL))   //监测IP事件组获取到IP事件
        {
            ret = -1;
            ESP_LOGE(__FUNCTION__, "register esp event loop handler for [IP_EVENT] failed");
            break;
        }

        if (ESP_OK != esp_event_handler_register(SC_EVENT, ESP_EVENT_ANY_ID, &wifi_base_event_loop_handler, NULL))      //监测smartconfig事件
        {
            ret = -1;
            ESP_LOGE(__FUNCTION__, "register esp event loop handler for [SC_EVENT] failed");
            break;
        }
        
        /* 配置wifi为站点模式 */
        if (ESP_OK != esp_wifi_set_mode(WIFI_MODE_STA))
        {
            ret = -1;
            ESP_LOGE(__FUNCTION__, "set wifi mode as STA failed");
            break;
        }

        /* 将wifi信息存放在FLASH，实际上时NVS分区 */
        if (ESP_OK != esp_wifi_set_storage(WIFI_STORAGE_FLASH))
        {
            ret = -1;
            ESP_LOGE(__FUNCTION__, "set wifi information save into FLASH(NVS)");
            break;
        }


        /* 启动wifi，进入handler函数 */
        if (ESP_OK != esp_wifi_start())
        {
            ret = -1;
            ESP_LOGE(__FUNCTION__, "start wifi failed");
            break;
        }

        ret = 0;
        ESP_LOGW(__FUNCTION__, "esp wifi base init success!!!");

        /* 释放wifi停止事件，允许断网重连 */
        xEventGroupClearBits(EventGroup_wifibase, wifieventbits_stop);
    }while(0);

    /* 告知上层wifi异常 */
    if (ret < 0)
        xEventGroupSetBits(EventGroup_wifibase, wifieventbits_connectfailed);

    //return ret;
}

```

wifi stop function:

```
void wifi_stop_release_sources()
{
    /* 抛出stop事件，不进行断网重连 */
    xEventGroupSetBits(EventGroup_wifibase, wifieventbits_stop);
    
    esp_event_handler_unregister(WIFI_EVENT, ESP_EVENT_ANY_ID,  wifi_base_event_loop_handler);
    esp_event_handler_unregister(IP_EVENT, IP_EVENT_STA_GOT_IP,  wifi_base_event_loop_handler);
    esp_event_handler_unregister(SC_EVENT, ESP_EVENT_ANY_ID,  wifi_base_event_loop_handler);   
    esp_event_loop_delete_default();
    esp_wifi_disconnect();
    esp_wifi_scan_stop();
    esp_wifi_stop();
    esp_wifi_deinit();
}


/* wifi资源释放，适应重复初始化 */
static void wifi_deinit_ilock()
{
    if (wifievent_monitor)
    {
        ESP_LOGW("WIFI DEINIT", "Delete task by Handler");
        vTaskDelete(wifievent_monitor);
        wifievent_monitor = NULL;
    }
}
```
But the following error message will appear, like the wifi resource is not cleaned up:
![222222](https://user-images.githubusercontent.com/48943389/62544394-44c4e080-b892-11e9-9b6c-686dc7c924c7.png)


I want konw:
1. How can I operate to ensure that wifi initialization is re-callable?
2. Is there a rough time to solve the smartconfig problem?

**Comment by negativekelvin** [comment]
`esp_event_loop_delete_default();`

You call this too early.  Do it last.

**Comment by liuzfesp** [comment]
Hi @GitOfLance, for the smartconfig issue,  the challenge part is that we can't reproduce your issue with same IDF commit id and demo code. Now I suspect it may related to your board, could you change to a different board and check whether the issue still exists?

**Comment by filzek** [comment]
@GitOfLance  we do not have this problem, we can build and run, only problem is that some Routers will not even work with smartconfig, it seens that the router send some ack in the same time APP is running in IOs or Android, so, to make it work you need to restart the router and run smartconfig same time it get back online. It is a problem with the sdk for sure, but not sure where.

Your problem related doesnt happen in wrover-b rev1 3/4 code scheme fuse.

**Comment by GitOfLance** [comment]
Hi, @negativekelvin 
I put this function ( `esp_event_loop_delete_default()` ) at the end of the release resource function, and the problem is solved, although I don't know why, as shown below:
```
void wifi_stop_release_sources()
{
    /* 抛出stop事件，不进行断网重连 */
    xEventGroupSetBits(EventGroup_wifibase, wifieventbits_stop);
    
    esp_event_handler_unregister(WIFI_EVENT, ESP_EVENT_ANY_ID,  wifi_base_event_loop_handler);
    esp_event_handler_unregister(IP_EVENT, IP_EVENT_STA_GOT_IP,  wifi_base_event_loop_handler);
    esp_event_handler_unregister(SC_EVENT, ESP_EVENT_ANY_ID,  wifi_base_event_loop_handler);   
    esp_wifi_disconnect();
    esp_wifi_scan_stop();
    esp_wifi_stop();
    esp_wifi_deinit();
    esp_event_loop_delete_default();        //放最后，测试
}
```
Thanks for your advice.

**Comment by GitOfLance** [comment]
Hi， @liuzfesp @filzek 
The process for making this error appear is as follows:
1. Compile and run the smartconfig demo in the default configuration.
2. When the message appears(`smartconfig: SC version: V2.9.0`), operate the APP to use smartconfig;
3. After the wifi connection is successful, restart the ESP32 through the `restart button` on the board.
4. Then reconfigure the wifi via smartconfig...

Repeat the operation like above and an error message will appear.
You can try to follow this process to see if an error message appears.

![Snipaste_2019-08-07_18-04-12](https://user-images.githubusercontent.com/48943389/62614341-c9b90400-b93d-11e9-9091-d80147ecc215.png)

The top five boards from left to right use the `ESP32-WROVER-B` module, which has `4MB` and `8MB` Flash or PSRAM.
According to the above test method, **ten times a group, calculate the number of errors**.
**The test results are as follows:**
- The first board, test a group, the error is `5 times`, that is, the error probability is `5/10`;
- The second board, testing two groups, once `4/10`, once `3/13`;
- The third board, testing two groups, each time is `4/10`;
- The fourth board, test a group, `5/10`;
- The fifth board, test a group, `3/10`;

**There is no single board to ensure that every smartconfig can be successful, so I think the smartconfig demo should be a hidden bug.**

**Comment by GitOfLance** [comment]
Another problem is that when I get `ssid` and `pwd`, I will directly call the `esp_wifi_connect()` function to connect to wifi. If the account and password are correct, I can connect to wifi. However, if the password account is wrong, the return of the `esp_wifi_connect()` function is still **`ESP_OK`**. The program cannot exit.
The codes:
```
static void wifi_base_connect_ssid_pwd(wifi_config_t wificonfig, bool def)
{  
    int ret = 0;
    
    do {
        /* 参数断言 */
        if ('\0' == wificonfig.sta.ssid[0] || '\0' == wificonfig.sta.password[0])
        {
            ESP_LOGE(__FUNCTION__, "WiFi Config SSID or PWD is NULL");
            ret = -1;
            break;
        }

        /* 使用默认配置 */
        if (true == def)
        {
            wificonfig.sta.scan_method = WIFI_FAST_SCAN;
            wificonfig.sta.bssid_set = 0;
            wificonfig.sta.channel = 0;
            wificonfig.sta.listen_interval = 0;
            wificonfig.sta.sort_method = WIFI_CONNECT_AP_BY_SIGNAL;
            wificonfig.sta.threshold.rssi = -127;
            wificonfig.sta.threshold.authmode = WIFI_AUTH_OPEN;
        }

        ESP_LOGW("WIFI CONNECT", "SSID : %s", wificonfig.sta.ssid);
        ESP_LOGW("WIFI CONNECT", "PWD : %s", wificonfig.sta.password);


        /* 连接网络 */
        esp_wifi_set_config(ESP_IF_WIFI_STA, &wificonfig);
        if (ESP_OK != esp_wifi_connect())
        {
            ESP_LOGE(__FUNCTION__, "Call esp_wifi_connect failed");
            ret = -1;
            break;
        } 
    }while(0);

    /* 配网失败，设置事件 */
    if (ret < 0)
    {
        xEventGroupSetBits(EventGroup_wifibase, wifieventbits_connectfailed);
    }   
}
```
The error message is as follows:
![错误的账号和密码](https://user-images.githubusercontent.com/48943389/62616957-53b79b80-b943-11e9-9923-a566ed9091d1.png)

**Comment by GitOfLance** [comment]
Hi, @liuzfesp @filzek 
Do you have reproduce this issue?

**Comment by liuzfesp** [comment]
@GitOfLance just can't find the time slot to debug this issue these days. Will do more investigation this week.

**Comment by espxiehang** [comment]
hi @GitOfLance  Fix version : 
```
 3638 commit 53d57dd736e4a56c07bf7f763f776058bb801348
 3639 Author: zhangyanjiao <zhangyanjiao@espressif.com>
 3640 Date:   Sun Sep 29 10:16:38 2019 +0800
 3641 
 3642     esp_wifi:
 3643     1. Fixed smartconfig ipc crash
 3644     2. Fix the WiFi init sequence bug
 3645     3. Fixed the bug that WiFi stop leads to task watchdog
 3646 

```

Please help verify that this version will resolve your issue.

**Comment by Alvin1Zhang** [comment]
@GitOfLance Thanks for reporting. And very sorry for the slow turnaround, do you have time to try the details shared by @espxiehang and help share if any updates for the issue? Thanks.
