### ISSUE TITLE
python not found in PATH/ macos (IDFGH-1571)

### ISSUE THREAD

**Issue by erdemirbehiye** [espressif/esp-idf#3831]
I tried to setup ESP32, but the eclipse will not work. I use macos. 
I can build on terminal. And I read documentation but I can't find the answer.

echo $IDF_PATH    /Users/aa/esp/esp-idf
build command: python ${IDF_PATH}/tools/windows/eclipse_make.py

<img width="1242" alt="Screen Shot 2019-07-25 at 21 25 57" src="https://user-images.githubusercontent.com/28511862/61898861-ed825000-af22-11e9-878e-83617dd4ecd9.png">

**Comment by igrr** [comment]
Please make sure your PATH variable includes not only the toolchain directory, but also the standard `/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin` directories.

**Comment by erdemirbehiye** [comment]
@igrr Hi,
When I typed on terminal  echo $PATH :
/Users/aa/esp/esp-idf/components/esptool_py/esptool:/Users/aa/esp/esp-idf/components/espcoredump:/Users/aa/esp/esp-idf/components/partition_table/:/Users/aa/.espressif/tools/xtensa-esp32-elf/esp32-2019r1-8.2.0/xtensa-esp32-elf/bin:/Users/aa/.espressif/tools/esp32ulp-elf/2.28.51.20170517/esp32ulp-elf-binutils/bin:/Users/aa/.espressif/tools/openocd-esp32/v0.10.0-esp32-20190313/openocd-esp32/bin:/Users/aa/.espressif/python_env/idf4.0_py3.7_env/bin:/Users/aa/esp/esp-idf/tools:/Users/aa/anaconda3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/opt/X11/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/aa/esp/xtensa-esp32-elf/bin

I tried that and this: 
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/aa/esp/xtensa-esp32-elf/bin

<img width="819" alt="Screen Shot 2019-07-25 at 21 40 41" src="https://user-images.githubusercontent.com/28511862/61900340-1c4df580-af26-11e9-8cc0-d0e88cca8ce8.png">

<img width="1328" alt="Screen Shot 2019-07-25 at 21 42 42" src="https://user-images.githubusercontent.com/28511862/61900350-1fe17c80-af26-11e9-971b-ead631576ccf.png">

**Comment by igrr** [comment]
Since you are on not using Windows, it may be okay to use `make` command instead of `python .../tools/windows/eclips_make.py flash`?

**Comment by erdemirbehiye** [comment]
@igrr  when i used the make, i faced another problem :

<img width="1291" alt="Screen Shot 2019-07-26 at 07 08 49" src="https://user-images.githubusercontent.com/28511862/61925282-47f7cc80-af74-11e9-91fe-165f54998c09.png">

**Comment by igrr** [comment]
The text in front of `gcc` (should be `xtensa-esp32-elf-`) is set by CONFIG_SDK_TOOLPREFIX menuconfig option. Is there a chance that you have accidentally set it to your serial port (`/dev/tty.usbserial1420`) instead? You can attach your sdkconfig file if you are not sure.

**Comment by erdemirbehiye** [comment]
@igrr you're right. I changed it. It works. Thank you.
