### ISSUE TITLE
"esp_a2d_sink_deinit()" in an endless loop (IDFGH-1575)

### ISSUE THREAD

**Issue by xiruilin** [espressif/esp-idf#3835]
## Problem Description

In "esp_a2d_sink_deinit()" function,
it's call "osi_thread_post()",
this lead to "osi_thread_run()" activation, 
and the process is below:

->"osi_thread_run()"
->"btc_thread_handler()"
->"btc_a2dp_call_handler()"
->"btc_a2d_sink_deinit()"
->"clean_up()"
->"btc_a2dp_sink_shutdown()"

In "btc_a2dp_sink_shutdown()" function, first call
"btc_a2dp_sink_ctrl_post()", then call "future_await()".

In "btc_a2dp_sink_ctrl_post()" function,
it's call "osi_thread_post()" again.
But now is in "osi_thread_run()" process and
"future_await()" will be never get signal.

**Comment by Alvin1Zhang** [comment]
@xiruilin Thanks for reporting, we already have the fix and now under internal reviewing, will be available on GitHub soon. Thanks.

**Comment by xiruilin** [comment]
@Alvin1Zhang 
This problem has been solved in commit, thanks.
