### ISSUE TITLE
WiFi Power Save Documentation (IDFGH-1590)

### ISSUE THREAD

**Issue by gregjesl** [espressif/esp-idf#3847]
In [docs/en/api-guides/wifi.rst](https://github.com/espressif/esp-idf/blob/master/docs/en/api-guides/wifi.rst), I believe
> Call esp_wifi_set_ps(WIFI_PS_MIN_MODEM) to disable modem sleep entirely. 

should read

> Call esp_wifi_set_ps(WIFI_PS_NONE) to disable modem sleep entirely.

**Comment by zhangyanjiaoesp** [comment]
Thanks. We will modify it.

**Comment by zhangyanjiaoesp** [comment]
This has been fix in https://github.com/espressif/esp-idf/commit/16b300bd7aef621073aead97d277ea60bfbf12f1。 This issue can be closed。

**Comment by Alvin1Zhang** [comment]
@gregjesl Thanks for reporting the issue, feel free to reopen if you still have the issue, thanks.
