### ISSUE TITLE
Does esp32 support WeChat near field discovery? (IDFGH-1599)

### ISSUE THREAD

**Issue by xuhongv** [espressif/esp-idf#3855]
- Does esp32 support WeChat near field discovery? I understand that esp8266 is already supported. Below is about "WeChat near-field found" function's website: 

- [https://iot.weixin.qq.com/wiki/new/index.html? Page = 4-1-4](url)

**Comment by jack0c** [comment]
Is it AirKiss? If so, ESP32 support it.

**Comment by jack0c** [comment]
BTW, I can't open the link.
