### ISSUE TITLE
Unprovision node (IDFGH-1606)

### ISSUE THREAD

**Issue by jkockx** [espressif/esp-idf#3861]
## Environment

- Development Kit:      [ESP32-DevKitC]
- Kit version (for WroverKit/PicoKit/DevKitC): [v2]
- Module or chip used:  [ESP32-WROOM-32D]
- IDF version: v4.0-dev-1191-g138c941fa
- Build System:         [Make]
- Compiler version: xtensa-esp32-elf-gcc (crosstool-NG esp32-2019r1) 8.2.0
- Operating System:     [Linux]
- Power Supply:         [USB]

## Problem Description
I'm trying to unprovison a node which I achieved to provision earlier. To do so ,I looked in the configuration model api but I can't find exactly how to do so.  Namely, I can't find the correct input for the function esp_ble_mesh_config_client_set_state to reset the node. It's clear to me I have to use the ESP_BLE_MESH_MODEL_OP_NODE_RESET opcode but I can't find the corresponding esp_ble_mesh_cfg_client_set_state_t union member to pass to esp_ble_mesh_config_client_set_state.
Can someone help me out?

**Comment by Alvin1Zhang** [comment]
Thanks for reporting the issue. Would you please help provide more details as suggested in the [issue template](https://github.com/espressif/esp-idf/blob/master/docs/issue_template.md)? Thanks. @jkockx

**Comment by jkockx** [comment]
OK, I think I have provided as much info as possible. As I think an appropriate esp_ble_mesh_config_client_set_state union member is missing I don't even have some debug log to share.

**Comment by Alvin1Zhang** [comment]
@jkockx Thanks for sharing the details. We will look into this soon. Thanks.

**Comment by WCCWCC** [comment]
Hi jkockx，

    Currently you need to reboot the device.

    `ESP_BLE_MESH_MODEL_OP_NODE_RESET ` : We will provide this API later.

**Comment by Campou** [comment]
Hi @jkockx 

For sending **Config Node Reset** message, because this message has no parameters, hence we only need to set the proper opcode and other information in the parameter `esp_ble_mesh_client_common_param_t`, and for the parameter `esp_ble_mesh_cfg_client_set_state_t`, just define this struct and no parameters need to be changed in it.

Thanks.

**Comment by Campou** [comment]
Hi @jkockx 

Sorry for the late reply. Currently when sending Config Node Reset, and `NULL` can be used as the parameter `esp_ble_mesh_cfg_client_set_state_t`, since the parameter of the Config Node Reset is empty.

Thanks.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close now, feel free to reopen if the issue still happens. Thanks.
