### ISSUE TITLE
Using Classic Bluetooth GAP API, ESP-IDF

### ISSUE THREAD

**Issue by SchKill** [espressif/esp-idf#3878]
I have read all the documentation available, but can't figure out how to use the below API in ESP-IDF template provided.

API Link - https://docs.espressif.com/projects/esp-idf/en/latest/api-reference/bluetooth/esp_gap_bt.html#_CPPv418esp_bt_gap_set_pin17esp_bt_pin_type_t7uint8_t17esp_bt_pin_code_t

Link for template - https://github.com/espressif/esp-idf-template

This is my first project involving micro-controllers. Any help would be really appreciated of how to use such API using esp-idf.

**Comment by Alvin1Zhang** [comment]
Closing as this seems to be a question, and the [issue template](https://github.com/espressif/esp-idf/blob/master/docs/issue_template.md) has been ignored. Questions could be asked on the esp32.com forum in the relevant section(s). Thanks.
