### ISSUE TITLE
AP mode, got error wifi: ampdu: ignore deleting tx BA0

### ISSUE THREAD

**Issue by playGit888** [espressif/esp-idf#3894]
## Environment

- Development Kit:      [ESP32-PICO-D4]
- Kit version: self made
- Module or chip used:  [ESP32-PICO-D4|ESP32]
- IDF version:    v4.0-dev-1346-g1b6010b
- Build System:         [idf.py]
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it): 
xtensa-esp32-elf-gcc (crosstool-NG esp32-2019r1) 8.2.0
- Operating System:     [Linux-ubuntu16.04]
- Power Supply:         [Battery->dc-dc->3.3v]

## Problem Description
I got losts of error like this:
I (614270) wifi: ampdu: ignore deleting tx BA0
I (614270) wifi: ampdu: ignore deleting tx BA0
I (614270) wifi: ampdu: ignore deleting tx BA0
I (615270) wifi: ampdu: ignore deleting tx BA0

Hello, I am using a PICO D4, and trying the example of AP mode.
So far, I don't have the problem in sta mode.
When this error comes up, the data transfering is impossible.
This problem is random. Most of the time, ESP32 works well.

Someone else have the same problem.
https://www.esp32.com/viewtopic.php?f=13&t=10839&p=44403&hilit=wifi%3A+ampdu%3A+ignore+deleting+tx+BA0&sid=4bb8f22bbe5efb2d3911586f0131c3e6#p44403

https://www.esp32.com/viewtopic.php?f=25&t=10873&p=44538&hilit=wifi%3A+ampdu%3A+ignore+deleting+tx+BA0&sid=4bb8f22bbe5efb2d3911586f0131c3e6#p44538

re-produce the error:
1. example: softap
2. combine another example http server
3. make some "post" or "get" data transfer, or just reflesh the home page you set for http server , ESP32 should work well. 
Wait a few mintues, the error may come up.

I guess, this is not about my code, it is about driver or hardware, or wrong config in Kconfig.
But I am not sure what is wrong, and how to fix it.

Thank you, any suggestion will be appreciated

**Comment by zhangyanjiaoesp** [comment]
@playGit888 can you provide  capture packages for further analysis?

**Comment by playGit888** [comment]
I would love to, but I don't know how to capture packages.  Would you give me a hint?

**Comment by playGit888** [comment]
![AMPDU error](https://user-images.githubusercontent.com/53387209/62718243-0ff28e00-ba38-11e9-8382-e8ffce06fcbd.png)
[http_server-simple-softAP.tar.gz](https://github.com/espressif/esp-idf/files/3482617/http_server-simple-softAP.tar.gz)

Here is the sample code.
type http://192.168.1.1/hello to access hello page.
wait a few mintues....the error will occur.

By the way, I am using a computer to connect to softAP. 
Is it my computer to cause the problem?

**Comment by mill1000** [comment]
Also seeing this issue in esp-idf v3.1.5
Client is an iPad Mini 4 running iOS 12.4 (16G77)

Reconnecting the client (iPad) stops the log message from appearing.

**Comment by daniol** [comment]
The current implementation of AMPDU in the ESP32 seems to be wrong as it causes problems with some network adapters. Using UDP over AP causes massive packet drops and TCP over AP causes packet looses and socket timeouts.

I solved this issue disabling AMPDU on the sdkconfig.h as a workaround:

```
#define CONFIG_ESP32_WIFI_AMPDU_TX_ENABLED 0
#define CONFIG_ESP32_WIFI_AMPDU_RX_ENABLED 0
```

**Comment by ppisljar** [comment]
i get the same trying to use esp-who recognition example on esp-who development board.

**Comment by zhangyanjiaoesp** [comment]
We are debugging the `delete tx BA` issue recently , and we will solve it as soon as possible.

**Comment by gabrielrbeiro** [comment]
Any updates ?

**Comment by liuzfesp** [comment]
@gabrielrbeiro the fix now is in reviewing status, it will be merged into IDF this month.

**Comment by cristiansedano** [comment]
> 
> 
> @gabrielrbeiro the fix now is in reviewing status, it will be merged into IDF this month.

thx

**Comment by Alvin1Zhang** [comment]
@playGit888 Thanks for reporting.  Would you please help try the latest master to see whether the issue still happens? Thanks.

**Comment by sosaucily** [comment]
We had been getting this error periodically, but since updating esp-idf to the head of 3.3.1 we no longer see the error message.

**Comment by Alvin1Zhang** [comment]
@playGit888 @sosaucily Thanks for reporting and updates, feel free to reopen if the issue still happens. Thanks.

**Comment by rajneeshsinha** [comment]
> We had been getting this error periodically, but since updating esp-idf to the head of 3.3.1 we no longer see the error message.

Hello

I am facing this issue "**wifi: ampdu: ignore deleting tx BA0**" with ESP-IDF version-3.3.1 in amazon freeRTOS SDK when connecting ESP32 AP to iPhone safari browser.

Can anyone provide the PR link for this issue? I just wanted to check what exact changes made this issue fixed.

**Comment by zhangyanjiaoesp** [comment]
@rajneeshsinha 
this branch c5e37c70737237bf971bde5b532ce49577a316f6 solve the problem.
