### ISSUE TITLE
On Init - How pin PRO to lwip and App to application (IDFGH-1647)

### ISSUE THREAD

**Issue by jhinklejr** [espressif/esp-idf#3896]
I understand how to create a task and pin it to a specific CPU.

I can do that when I create the Application - pin it to APP.

Question is how to pin lwip activity to the PRO cpu - since I don't create that task?

Thanks.

Joe

**Comment by negativekelvin** [comment]
https://github.com/espressif/esp-idf/blob/39f090a4f1dee4e325f8109d880bf3627034d839/components/lwip/Kconfig#L472

**Comment by jhinklejr** [comment]
Thanks
