### ISSUE TITLE
"python -m pip install requirements.txt" results: "Could not find a version that satisfies the requirement requirements.txt" (IDFGH-1670)

### ISSUE THREAD

**Issue by armandr** [espressif/esp-idf#3915]
Typo likely:

The master version of the readme.md:

[Setup Build Environment](https://github.com/espressif/esp-idf#setup-build-environment)
says: 

> Run python -m pip install requirements.txt to install Python dependencies

I get an error doing that,  it seams that pip is trying to install requirements.txt as opposed to reading the contents.

Adding the -r works for me: Run `python -m pip install -r requirements.txt` to install Python dependencies.

**Comment by hdivakar5** [comment]
try to install this  https://dl.espressif.com/dl/esp-idf-tools-setup-2.3.exe
