### ISSUE TITLE
android provisioning app building fails (IDFGH-1687)

### ISSUE THREAD

**Issue by work-media** [espressif/esp-idf#3927]
source code : [provisioning-android](https://github.com/espressif/esp-idf-provisioning-android)
building output tip: Directory '/Users/sagetsang/Destop/esp-idf-provisioning-android-master/app/build/extracted-include-protos/main' specified for property '$3' does not exist
OS: macOS

**Comment by Alvin1Zhang** [comment]
Thanks for reporting the issue. Would you please help provide more details as suggested in the [issue template](https://github.com/espressif/esp-idf/blob/master/docs/issue_template.md)? Thanks. @work-media

**Comment by work-media** [comment]
Could you provide an apk so that I can test wifi provisioning directly?

**Comment by FayeY** [comment]
https://github.com/espressif/esp-idf-provisioning-android/releases
