### ISSUE TITLE
GPIO MATRIX IO MUX (IDFGH-1704)

### ISSUE THREAD

**Issue by Pratikm78** [espressif/esp-idf#3943]
how do i use gpio22 and gpio23 as analog input for adc1. is it possible to use gpio matrix. are there any examples to use gpio matrrix the Technical Reference Manual is confusing

**Comment by krzychb** [comment]
Hi @Pratikm78, 

ADC1 is supports eight channels routed to specific GPIOs, namely GPIO 32 .. 39. It is not possible to use other GPIOs with ADC1, see [Analog to Digital Converter API](https://docs.espressif.com/projects/esp-idf/en/latest/api-reference/peripherals/adc.html).

To get answers to "How do I ... ?" questions please ask them on esp32.com site.
