### ISSUE TITLE
transport_read() error: errno=-128 what's the reason ? (IDFGH-1716)

### ISSUE THREAD

**Issue by InfiniteYuan1** [espressif/esp-idf#3953]
E (326934) MQTT_CLIENT: mqtt_message_receive: transport_read() error: errno=-128
E (326944) MQTT_CLIENT: mqtt_process_receive: mqtt_message_receive() returned -1

Please tell me what's the reason if you know? Thanks.

**Comment by Alvin1Zhang** [comment]
@InfiniteYuan1  Thanks for reporting this, will close this due to the issue template has been ignored. Thanks.
