### ISSUE TITLE
Random Loss of BLE Bonding info (IDFGH-1733)

### ISSUE THREAD

**Issue by bzeeman** [espressif/esp-idf#3968]
## Environment

- Development Kit:      [none]
- Kit version (for WroverKit/PicoKit/DevKitC): [v1|v2|v3|v4]
- Module or chip used:  [ESP32-WROOM-32D|ESP32-WROVER]
- IDF version (run ``git describe --tags`` to find it): 
    // 3.1.3 using platformio Espressif@1.7
- Build System:         [PlatofromIO | arduino-core]
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it):
    // 1.22.0-80-g6c4433a
- Operating System:     [macOS]
- Power Supply:         [USB|external 5V|external 3.3V]

## Problem Description

I have two projects I am working on. One is on Arduino core, but the other is using the IDF through PlaformIO. On both devices there are times when we seem to randomly lose bonding info.

When this occurs it causes some major problems with iOS pairing. iOS will request to pair again with the device, but the link key will fail. At which point the system will ask again. This is the same thing that happens if you try to pair when you have erased the flash and reflashed the esp but then forget to "forget device" in the iOS settings. **To be clear, this is not what is happening, I only mention this because this is the same behavior.**

The problem is that for some reason we see this randomly without erasing anything. In fact, we still seem to have other information that is stored in the NVS and can read it and use it without issue.

The issue is even more baffling because when this occurs I can see that I have 0 bonded devices without having ever removed them from the list through a call to `esp_ble_get_bond_device_num();` 

In this situation I can do a dump of the nvs partition through `./esptool.py read_flash 0x9000 0x5000 ~/nvsdump.dump` and it shows multiple sets of bonding keys, 

This is in the nvs dump 7 times, all identical
\[MAC:ADDR]
AddrType = 1
AuthMode = 9
DevType = 2
LE_KEY_PENC = f81eOBFUSCATED000110
LE_KEY_PID = 4051edOBFUSCATEDa05900586b1462d0ad
LE_KEY_LENC = f81OBFUSCATED17500001001
LE_KEY_LID = 

and this appears identically 37 times

[Adapter]
LE_LOCAL_KEY_IRK = bb22OBFUSCATED8c25
LE_LOCAL_KEY_IR = a7bOBFUSCATEDe1cf
LE_LOCAL_KEY_DHK = e42OBFUSCATEDfae592d
LE_LOCAL_KEY_ER = e699OBFUSCATEDfce4739aace3a1c58

### Expected Behavior
Once a bond has been established, those bonds should remain, through reboots, power downs etc. until removed explicitly.

### Actual Behavior
Device randomly loses the bonding key.
### Steps to repropduce

1. Create a bond with another device, happens using both ESP_LE_AUTH_REQ_SC_BOND and ESP_LE_AUTH_REQ_SC_MITM_BOND
2. Use the device, communicate with it for an indeterminate period of time.
3. MAYBE do an OTA but not strictly required.
4. At some point, the authentication will fail with HCI reason 55

The only clue I have as to how this might happen is that there may be collisions when there is data being set on characteristics. We had a test app and a production App and both were trying to send data over the characteristic at the same time. I am not sure this is this issue, but I know that could be problematic too.

// It helps if you attach a picture of your setup/wiring here.
All other features work as expected, both are proprietary hardware. Schematics can be provided if necessary.

### Code to reproduce this issue

```cpp
Code is proprietary but can be provided on a private basis.
```
// If your code is longer than 30 lines, [GIST](https://gist.github.com) is preferred.

## Debug Logs

So far this has not happened during a session in which we have been able to log.
can produce actual nvs flash dumps if necessary privately.

**Comment by gengyuchao** [comment]
I want to know if your program has the code like the IDF example as follows.
```
    // Initialize NVS.
    ret = nvs_flash_init();
    if (ret == ESP_ERR_NVS_NO_FREE_PAGES || ret == ESP_ERR_NVS_NEW_VERSION_FOUND) {
        ESP_ERROR_CHECK(nvs_flash_erase());
        ret = nvs_flash_init();
    }
```
This code will erase the flash when the nvs has no free pages.

**Comment by GYC-Espressif** [comment]
Hello, I didn't reproduce the problem. Does your problem still exist? If it still exists, please provide the code to help us find the problem. Thank you.

**Comment by Alvin1Zhang** [comment]
@bzeeman Thanks for reporting, would you please help share more details? Thanks.

**Comment by Alvin1Zhang** [comment]
@bzeeman Thanks for reporting, will close due to short of feedback and updates. Feel free to reopen if the issue still happens. Thanks.

**Comment by lazd** [comment]
I had been having the same issue with my Bluedroid implementation of a project. Reported that NimBLE does not suffer from the loss of pairing information issue, so I ported my project over to it and will report back if that fixes it after testing.
