### ISSUE TITLE
Websocket support by the ESP32

### ISSUE THREAD

**Issue by williamesp2015** [espressif/esp-idf#397]
I had websocket on ESP8266 and it was working fin but I can not use ESP32. Could you please provide example for websocket server and client?

**Comment by ESP32DE** [comment]
hi
you can test this example:
https://esp32.com/viewtopic.php?f=17&t=97
and the blog is here
http://www.barth-dev.de/websockets-on-the-esp32/

best wishes
rudi ;-)

**Comment by igrr** [comment]
libesphttpd provides websocket support and is compatible with ESP-IDF (make sure you get 'esp-idf' branch instead of master):
https://github.com/Spritetm/libesphttpd/tree/esp-idf
