### ISSUE TITLE
Intermittently not receiving Ethernet multicast frames (IDFGH-1736)

### ISSUE THREAD

**Issue by jqualie** [espressif/esp-idf#3970]
## Environment
- Development Kit: none (custom hardware)
- Module or chip used:  ESP32-WROVER-B
- IDF version: v3.2
- Build System: make
- Compiler version: xtensa-esp32-elf-gcc.exe (crosstool-NG crosstool-ng-1.22.0-80-g6c4433a5) 5.2.0
- Operating System:  Windows 10 MSYS2
- Power Supply: external 3.3V

## Problem Description

I am using ESP32 WROVER + LAN8742A PHY with ESP-IDF v3.2.

The ESP32 occasionally cannot receive multicast ethernet frames. It can send multicast, send & receive unicast, and send & receive broadcast without problems. The receive multicast problem happens roughly in 1% of startups, and it persists until a power cycle - even a chip reset doesn’t fix the problem. I suspect it is a silicon or driver problem.

I noticed the git commit to the ESP-IDF ethernet driver emac_dev.c in late 2018 that sets the PAM bit enabling all received multicast frames to be passed to the application:
REG_SET_BIT(EMAC_GMACFF_REG, EMAC_PAM);

I checked at runtime and print out to the console the value of this register on every received frame, and I can confirm the register PAM bit is set. However in 1% of the startups the frames are not received.

I suspected this is a silicon or driver setup issue, so I tried clearing and setting the PAM bit on every connect/disconnect of the Ethernet link (achieved by removing and plugging in the CAT5 cable). This seems to address the issue, but the problem happens so rarely it is difficult to recreate.

Has anyone else seen this issue, and could there potentially be a silicon bug?

**Comment by suda-morris** [comment]
Hi @jqualie Thanks for reporting this issue, we will look into it.

**Comment by suda-morris** [comment]
@jqualie Can we try to enable the promiscuous mode by `emac_enable_promiscuous`, to see if this option can reproduce the issue?

**Comment by jqualie** [comment]
1. I tried setting just the EMAC_PAM bit in `emac_mac_init()`. The problem persists.
1. I tried setting just the EMAC_PMODE bit in `emac_mac_init()`. The problem persists.
1. I tried setting the EMAC_PAM bit and the EMAC_PMODE bit in `emac_mac_init()`. The problem persists.
1. I tried setting the EMAC_RECEIVE_ALL bit in `emac_mac_init()`, and the problem goes away. But of course now the device receives all packets even though they aren't destined for it.
1. I tried setting the EMAC_PAM bit in `emac_process_link_updown()` when the Ethernet interface is up, and clearing the bit when the Ethernet interface is down, and the problem goes away. 

I do the bit set after the call to `emac_enable_dma_rx()`, so I wonder if there is a race condition or flaw in the setup of the DMA that affects the ability to receive multicast frames.

Code for `emac_main.c`:
``` C
static void emac_process_link_updown(bool link_status)
{
    system_event_t evt;
    uint8_t i = 0;

    emac_config.phy_link_up = link_status;

    if (link_status) {
        emac_check_phy_init();
        ESP_LOGD(TAG, "eth link_up");
        emac_enable_dma_tx();
        emac_enable_dma_rx();
        for (i = 0; i < PHY_LINK_CHECK_NUM; i++) {
            emac_check_phy_init();
        }

        //@fix EMAC occasionally not receiving multicast frames 
        REG_SET_BIT(EMAC_GMACFF_REG, EMAC_PAM);

        evt.event_id = SYSTEM_EVENT_ETH_CONNECTED;
    } else {
        ESP_LOGD(TAG, "eth link_down");
        emac_disable_dma_tx();
        emac_disable_dma_rx();

        //@fix EMAC occasionally not receiving multicast frames 
        REG_CLR_BIT(EMAC_GMACFF_REG, EMAC_PAM);

        evt.event_id = SYSTEM_EVENT_ETH_DISCONNECTED;
    }

    esp_event_send(&evt);
}
```

**Comment by jqualie** [comment]
I have compelted more testing and I had a fix. It's not the PAM bit. 
It's the startup timing of `emac_process_link_updown()`. When I add a vTaskDelay(10) in the link_up code path, everything works.

Espressif may want to investigate the timing dependencies between the PHY link_up event, emac_process_link_updown(), and the emac_task as it relates to the other tasks. Perhaps there is a critical section that is not isolated adequately.

``` C
static void emac_process_link_updown(bool link_status)
{
    system_event_t evt;
    uint8_t i = 0;

    emac_config.phy_link_up = link_status;

    if (link_status) {
        vTaskDelay(10); // wait for PHY and other tasks to be ready (?)
        emac_check_phy_init();
        ESP_LOGD(TAG, "eth link_up");
        emac_enable_dma_tx();
        emac_enable_dma_rx();
        evt.event_id = SYSTEM_EVENT_ETH_CONNECTED;
    } else {
        ESP_LOGD(TAG, "eth link_down");
        emac_disable_dma_tx();
        emac_disable_dma_rx();
        evt.event_id = SYSTEM_EVENT_ETH_DISCONNECTED;
    }

    esp_event_send(&evt);
}
```

**Comment by suda-morris** [comment]
Hi @jqualie Nice spotted!
But I also wonder if a phy chip reset can help? Logically it makes sense to reset phy chip after re-plugin the cable (because we need a new round of negotiation between two Ethernet endpoint).

```c
static void emac_process_link_updown(bool link_status)
{
    system_event_t evt;
    uint8_t i = 0;

    emac_config.phy_link_up = link_status;

    if (link_status) {
       if (emac_config.phy_init() != ESP_OK) {
          ESP_LOGE(TAG, "Initialise PHY device Timeout");
       }
        emac_check_phy_init();
        ESP_LOGD(TAG, "eth link_up");
        emac_enable_dma_tx();
        emac_enable_dma_rx();
        evt.event_id = SYSTEM_EVENT_ETH_CONNECTED;
    } else {
        ESP_LOGD(TAG, "eth link_down");
        emac_disable_dma_tx();
        emac_disable_dma_rx();
        evt.event_id = SYSTEM_EVENT_ETH_DISCONNECTED;
    }
    esp_event_send(&evt);
}
```

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to short of feedback, feel free to reopen with more updates.
