### ISSUE TITLE
how to get more memory? (IDFGH-1753)

### ISSUE THREAD

**Issue by wjundong** [espressif/esp-idf#3979]
The esp module that I use is said to have an 8m SPRAM, but I fail to get more memory than 120KB with malloc. 
Why, isn't there 8m of memory? 
How can I solve this problem?

**Comment by Alvin1Zhang** [comment]
@negativekelvin Thanks for the notes. @wjundong Please do not ignore the GitHub issue posting guidelines. If your issue is a general question, starts similar to "How do I.." or etc, please discuss this on our community forum at esp32.com instead. Thanks.
