### ISSUE TITLE
Symbol 'ESP_OK' couldn't be resolved (IDFGH-1759)

### ISSUE THREAD

**Issue by MusabAybek** [espressif/esp-idf#3985]
Hi. I'm new to Esp32 IDF programming and Github. Using windows 10. The new version of the IDF (V4.0) is on the espressif's official site right now but I downloaded the old one (Legacy GNU Make) in order to be able to program via Eclipse Environment. I followed the whole get-started instructions but still  getting errors in Eclipse. 

"Symbol 'CONFIG_FREERTOS_HZ' could not be resolved"
"Symbol 'ESP_OK' could not be resolved"
"Symbol 'MALLOC_CAP_DMA' could not be resolved"
"Type 'esp_err_t' could not be resolved"

Getting these errors while trying to apply sample code which is on this link:
https://github.com/loboris/ESP32_TFT_library

Thanks in advance..

**Comment by projectgus** [comment]
Hi @MusabAybek,

Sorry noone has gotten back to you about this for such an incredibly long time.

When using the Legacy GNU Make build system, it's possible to get in a situation where the build is successfully but the IDE Indexer (that also parses all the source files for the IDE features) can't see the build options, so if you choose "Build" it will build but the source files are still full of "errors" from the indexer. This sounds like what has happened.

To resolve the problem, check carefully that the "Indexer" setting and all the other Project Properties are set exactly as described here:
https://docs.espressif.com/projects/esp-idf/en/v4.0/get-started-legacy/eclipse-setup.html#import-new-project

However, a better option which is now available is to move to the official CMake build system and the ESP-IDF Eclipse plugin which has better indexing and also other features:
https://github.com/espressif/idf-eclipse-plugin/
