### ISSUE TITLE
How do I setup my CMake Projekt (IDFGH-1763)

### ISSUE THREAD

**Issue by Nan000** [espressif/esp-idf#3988]
Hi together,

I've just recently switched to the CMake build tool chain and have a lot of problems to set it up for my project structure even with the very good documentation. I hope someone can help me here. Where shall I put the CMakeList.txt files and what should be its content?

My Projekt structure looks as follows:

Projekt
       |
        ------ main
       |            |
       |             ----main.c
        ---- Component_1
                     |
                      ---- Config
                     |          |
                     |          ----- config_1.h
                     |          ----- config_1.c
                     |          ----- config_2.h
                     |          ----- config_1.c
                      ---- Core
                     |           |
                     |           ----- core_1.h
                     |           ----- core_1.c
                     |           ----- core_2.h
                     |           ----- core_1.c
                      ---- Interface
                     |           |
                     |           ----- Interface_1.h
                     |           ----- Interface_1.c
                     |           ----- Interface_2.h
                     |           ----- Interface_2.c
                     |
                     ---- component.h
                     ---- component.c 

Thanks!

**Comment by Alvin1Zhang** [comment]
@Nan000 Thanks for reporting. Please do not ignore the GitHub issue posting guidelines. If your issue is a general question, starts similar to "How do I..", or is related to 3rd party development kits/libs, please discuss this on our community forum at esp32.com instead. Thanks.
