### ISSUE TITLE
Error when compiling large programs despite CONFIG_ULP_COPROC_RESERVE_MEM=8192 (IDFGH-1772)

### ISSUE THREAD

**Issue by nicholas1230** [espressif/esp-idf#3993]
Please fix issue discussed here:
[https://github.com/duff2013/ulptool/issues/21](url)
Editing "../ulp/ld/esp32.ulp.ld" worked! 
As explained by this comment:
[https://github.com/duff2013/ulptool/issues/21#issuecomment-458273726](url)

**Comment by igrr** [comment]
@nicholas1230 The upper part of RTC_SLOW memory is reserved for ESP-IDF use, this limitation is intentional. You can indeed edit the linker script to take advantage of the remaining space, but we can't guarantee that this will keep working in future ESP-IDF versions.

**Comment by negativekelvin** [comment]
Seems like this could be accounted for at compile time such as:
"WARNING: CONFIG_ULP_COPROC_RESERVE_MEM > 4096, automatic app state persistence is DISABLED"
