### ISSUE TITLE
bta_jv_int.h in wrong folder. (IDFGH-1774)

### ISSUE THREAD

**Issue by 2dark4u** [espressif/esp-idf#3994]
File in wrong folder:    esp-idf/components/bt/bluedroid/bta/jv/bta_jv_int.h
Correct path is:    esp-idf/components/bt/bluedroid/bta/include/bta_jv_int.h

**Comment by negativekelvin** [comment]
In what commit?

https://github.com/espressif/esp-idf/tree/master/components/bt/host/bluedroid/bta/jv/include

**Comment by 2dark4u** [comment]
Sorry my mistake, I was accidetially using old 'local' branch. This issue not present in any git branch.
Close issue please.
