### ISSUE TITLE
ESP32 tarefa bloqueia quando uso WiFi e Time ISR (IDFGH-1775)

### ISSUE THREAD

**Issue by elielmarcos** [espressif/esp-idf#3995]
I set the ISR time to 250us for a task on core 0 (for ADC sampling rate) and Wifi on core 1.

But when I use WiFi communication, I realize that when I come back from the timer interrupt, the task at core 0 takes time to get back to work. And when WiFi communication is not being used, it works perfectly.

Why does this happen?

**Comment by Alvin1Zhang** [comment]
Thanks for reporting the issue. Would you please help provide more details as suggested in the [issue template](https://github.com/espressif/esp-idf/blob/master/docs/issue_template.md)? Information like elf, sdk configuration, backtrace, log outputs, commit ID, hardware and etc. would help us debug further. Thanks.

**Comment by elielmarcos** [comment]
I am using ESP32 - DOIT with IDE Arduino and Esp IDF 1.0.1.

I am running a WiFi Loop routine (CORE 1) and a task to process an ADC signal (CORE 0).

The ADC processing task, in the example, only prints the value of a counter that increments (every 250us) each time the ISR Timer is called and incremented each time it prints in Serial.

My simplified code:

/*******************************************************************************
LIBRARIES
*******************************************************************************/
#include <math.h>
#include <stdio.h>
#include <esp_system.h>
#include <driver/adc.h>
#include <esp_adc_cal.h>
#include <esp_task_wdt.h>
#include <Arduino.h>
#include <WiFi.h>
#include <WiFiClient.h>
#include <ESPmDNS.h>
#include <HTTPClient.h>
#include <WebServer.h>
#include <DNSServer.h>
#include <FS.h>
#include <SPIFFS.h>

/*******************************************************************************
CONSTANT DEFINITION
******************************************************************************/
// Device Name
const String DEVICE_NAME = "SmartMeter";
// System Password
const char PASSWORD[] = "12345678";
// WebServer Port
const byte WEBSERVER_PORT = 80;
// DNS Server Port
const byte DNSSERVER_PORT = 53;
// Access Point IP
const IPAddress AP_IP (192, 168, 1, 1);
// WebServer Headers
const char WEBSERVER_HEADER_KEYS[] = {"User-Agent", "Cookie"};

/*******************************************************************************
ENTITIES
*******************************************************************************/
// Web Server
WebServer server(WEBSERVER_PORT);
// DNS Server
DNSServer dnsServer;
// HTTP Client
HTTPClient http;

/*******************************************************************************
VARIABLES
*******************************************************************************/
// Attribute Timer
hw_timer_t * timer = NULL;
// Mutex Timer
portMUX_TYPE timerMux = portMUX_INITIALIZER_UNLOCKED;
// Timer Interrupt Counter
volatile int interruptCounter = 0;

/*******************************************************************************
TASKS
*******************************************************************************/
void SignalProcess( void *pvParameters );

/*******************************************************************************
INTERRUPTIONS
*******************************************************************************/
void IRAM_ATTR onTimer() {
portENTER_CRITICAL_ISR(&timerMux);
interruptCounter++;
portEXIT_CRITICAL_ISR(&timerMux);
}

/*******************************************************************************
WEB REQUESTS HANDLING
*******************************************************************************/
void handleStream(const String f, const String mime) {
// Handle file stream request
File file = SPIFFS.open("/" + f, "r");
if (file) {
server.streamFile(file, mime);
file.close();
Serial.println("WebStream; File: " + f);
} else {
server.send(500, F("text/plain"), F("Stream - ERROR 500"));
Serial.println(F("WebStream; ERRO lendo arquivo "));
}
}

void handleHome(){
handleStream(F("Home.html"), F("text/html"));
}

void handleChartJS(){
handleStream(F("Chart.min.js"), F("application/javascript"));
}

/*******************************************************************************
SETUP
*******************************************************************************/
void setup() {
// Serial
Serial.begin(500000);

// Watchdog
disableCore0WDT();

// File System begin
if (!SPIFFS.begin()) {
Serial.println(F("Boot; SPIFFS ERRO"));
}

// WiFi - Access Point
WiFi.mode(WIFI_AP);
WiFi.softAPConfig(AP_IP, AP_IP, IPAddress(255, 255, 255, 0));
WiFi.softAP(DEVICE_NAME.c_str());

// Enable DNS routing
dnsServer.start(DNSSERVER_PORT, "*", WiFi.softAPIP());

// mDNS
if (!MDNS.begin(DEVICE_NAME.c_str())) {
Serial.println(F("Boot; mDNS ERRO"));
} else {
Serial.println("mDNS: " + DEVICE_NAME + ".local");
}

// WebServer
server.on("/Chart.min.js", handleChartJS);
server.on("/Home.html", handleHome);
server.onNotFound(handleHome);
server.collectHeaders(WEBSERVER_HEADER_KEYS, 2);
server.begin();

// Create Task for Signal Processing
xTaskCreatePinnedToCore(
SignalProcess
, "SigProcess" // A name just for humans
, 10000 // This stack size can be checked & adjusted by reading the Stack Highwater
, NULL
, 3 // Priority, with 3 (configMAX_PRIORITIES - 1) being the highest, and 0 being the lowest.
, NULL
, 0); //Core

}

/*******************************************************************************
LOOP
*******************************************************************************/
void loop() {
// Take care of WatchDog ---------------------------------------------------
yield();
esp_task_wdt_reset();

// DNS Requests ------------------------------------------------------------
dnsServer.processNextRequest();

// Web Requests ------------------------------------------------------------
server.handleClient();
}

/*******************************************************************************
TASK FOR SIGNAL PROCESSING
*******************************************************************************/
void SignalProcess(void *pvParameters)
{
(void) pvParameters;

// ADC - Configure ---------------------------------------------------------
adc1_config_width(ADC_WIDTH_BIT_12); // Resolution
adc1_config_channel_atten(ADC1_CHANNEL_5, ADC_ATTEN_DB_0); // Channel and attenuation (Voltage)
adc1_config_channel_atten(ADC1_CHANNEL_4, ADC_ATTEN_DB_0); // Channel and attenuation (Current)
analogSetClockDiv(1);

// TIMER0 - Configure for interruption -------------------------------------
timer = timerBegin(0, 80, true);
timerAttachInterrupt(timer, &onTimer, true);
timerAlarmWrite(timer, 250, true); // Interval 250us (Sample Rate 4000Hz)
timerAlarmEnable(timer);

// Loop --------------------------------------------------------------------
for(;;)
{

if (interruptCounter > 0)
{
  portENTER_CRITICAL(&timerMux);
 
  /* My code signal process
			:
			:
			:
			:
			:
	*/

  printf("%i \n",interruptCounter);
  interruptCounter--;
  portEXIT_CRITICAL(&timerMux);
}

}
}

// END -----------------------------------------------------------


Arduino serial terminal output:

:
:
:
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
2
2
1
WebStream; File: Home.html
2
1
1
8
8
8
7
9
9
9
11
11
10
9
9
8
7
6
5
4
3
2
1
1
1
1
1
1
1
1
:
:
:


Note that the counter is not decremented while something is being requested via WiFi. At the end it is decremented again and always printed "1".
But the two processes (WiFi and Task SignalProcess) are in different CORE's.

Any solution?

**Comment by negativekelvin** [comment]
Go to the forum for this type of question esp32.com

1. configMAX_PRIORITIES is 25 so yours is too low
2. Use a semaphore not poll a counter
3. Yield from the isr

**Comment by elielmarcos** [comment]
@negativekelvin

Ok Thanks and Sorry!

Delete topic
