### ISSUE TITLE
Ethernet not working after upgrade to v4.x (IDFGH-1777)

### ISSUE THREAD

**Issue by Metmacher** [espressif/esp-idf#3998]
## Environment

- Development Kit: none
- Board: Olimex Gateway Rev. C (Phy is the lan8720 with address 0)
- Kit version (for WroverKit/PicoKit/DevKitC): [v1|v2|v3|v4]
- Module or chip used:  ESP32-WROOM-32
- IDF version (run ``git describe --tags`` to find it): v4.0-dev-1416-gba0f4f17e
- Build System:  Make
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it): 1.22.0-80-g6c4433a
- Operating System: Linux
- Power Supply:   USB

## Problem Description

After update the esp-idf from v3.3 to v4.0 the ethernet won't work anymore. Below is the setup with the ethernet example from the esp-idf.

### Steps to repropduce

Working project ist the esp-idf ethernet example (in v4.0 the basic).

Show working with the esp-idf version 3.3:
![ethernet_example_v3_3](https://user-images.githubusercontent.com/9679606/64097370-5e0f5e80-cd64-11e9-8230-ad016d9e84bc.png)

After switching to version 4.0:
Add the following to the ethernet_example_main.c.
`phy_config.phy_addr=0;`
And then:
![ethernet_example_v4_0](https://user-images.githubusercontent.com/9679606/64098051-24d7ee00-cd66-11e9-837b-e3c3dcbeab20.png)

I tested it also with the actual master branch with the same result.

**Comment by negativekelvin** [comment]
> By default Ethernet driver will assume the PHY address to 1, but you can alway reconfigure this value after eth_phy_config_t phy_config = ETH_PHY_DEFAULT_CONFIG();

**Comment by Metmacher** [comment]
After line 75 which containts `eth_phy_config_t phy_config = ETH_PHY_DEFAULT_CONFIG();` i add `phy_config.phy_addr=0;` (before the compiler if's)

**Comment by suda-morris** [comment]
If you can test the signal on GPIO0? Because from your configuration, Ethernet only get worked when there's a valid RMII clock input to GPIO0. If not, it even can't reset itself. 
And have you also selected the PHY device to LAN8720 from the menuconfig, in the `Example Configuration`?

**Comment by Metmacher** [comment]
Yes I set the example configuration to lan8720:
![ethernet_example_v4_config](https://user-images.githubusercontent.com/9679606/64146664-1816d100-ce1e-11e9-9405-de78146f3c54.png)

The signal on GPIO0 looks with esp-idf-v4 the same like with esp-idf-v3

**Comment by suda-morris** [comment]
What about enlarge the reset timeout value? `phy_config.reset_timeout_ms=1000;`

**Comment by negativekelvin** [comment]
@suda-morris isn't it the Mac reset that times out? 

https://github.com/espressif/esp-idf/blob/f16f4297cd59b981ae39b503cfa491642ef24334/components/esp_eth/include/esp_eth_mac.h#L263

**Comment by Metmacher** [comment]
@suda-morris  Yes I also tried this with `phy_config.reset_timeout_ms=3000;`. Nothing changed.

**Comment by suda-morris** [comment]
hi @negativekelvin Ah sorry, yes, we need to set the internal mac reset timeout.

**Comment by suda-morris** [comment]
> @suda-morris Yes I also tried this with `phy_config.reset_timeout_ms=3000;`. Nothing changed.

Sorry it's my bad, as @negativekelvin mentioned, we should try to enlarge the reset timeout of mac, not phy.

**Comment by Metmacher** [comment]
Thats it, after setting `mac_config.sw_reset_timeout_ms = 2000;` it worked. Thank you a lot @negativekelvin  and @suda-morris !

**Comment by negativekelvin** [comment]
@suda-morris how long does internal Mac reset take and why so long?

**Comment by suda-morris** [comment]
If we can make sure the RMII clock is ready at the time we reset internal mac, then 100ms is enough. The timeout value only gets tested in our ESP32-Ethernet-Kit, and it might vary from boards to boards. But I also don't think it will cost such a long time.
For example, if we initialize the Ethernet driver in the following way:
```c
esp_eth_install();// because phy doen't poweron for now, it gets blocked at the reset timeout checking.
do_something_to_poweron_phy();// after this, we can go on with ethernet driver install
```
In this case, the timeout value will looks very big. 
I would like to suggest to move the specific PHY power control operation into a hook provided by https://github.com/espressif/esp-idf/blob/master/components/esp_eth/include/esp_eth.h#L100
So that we can make sure the RMII clock is ready before we start to reset mac.

**Comment by negativekelvin** [comment]
In this board I think there is 500ms delay from powerup until ext clk is applied to gpio0 so maybe 100ms is too close.  But there is no phy power gpio.
