### ISSUE TITLE
ESP32 keep Coaps DTLS session in deep sleep (IDFGH-1801)

### ISSUE THREAD

**Issue by pegahnikbakht** [espressif/esp-idf#4013]
Hi, 

I'm trying to use coaps protocol, I want esp32 goes to deep sleep without closing the current DTLS session. I have no idea if it is possible in deep sleep mode or not? 
I have to say that I succeeded keeping the DTLS session alive after light sleep and it works as expected. 
can any one guide me for deep sleep mode?

**Comment by Alvin1Zhang** [comment]
@pegahnikbakht Thanks for reporting. Checked that this question is also posted on our forum at https://esp32.com/viewtopic.php?f=13&t=12149. For "how" questions, we suggest posting on our forum, will close this issue and keep the post on forum. Thanks.
