### ISSUE TITLE
tools/mass_mfg/mfg_gen.py生产工具不可用 (IDFGH-1819)

### ISSUE THREAD

**Issue by enric-lee** [espressif/esp-idf#4029]
tools/mass_mfg/mfg_gen.py执行出错，v4.0版本错误log:

> python mfg_gen.py generate multipule_mfg_config.csv multipule_mfg_values.csv scgw 0x4000
> Created CSV file: ===> ./csv/scgw-1.csv
> **'module' object has no attribute 'generate'**

v3.2版本错误log:
> python mfg_gen.py --conf multipule_mfg_config.csv --values  multipule_mfg_values.csv --prefix scgw --size 0x4000
> CSV Generated:  ./csv/scgw-1.csv
> **nvs_part_gen() got an unexpected keyword argument 'input_size'**

multipule_mfg_config.csv文件内容：
scgw-key,namespace,
DeviceName,data,string
DeviceSecret,data,string
ProductKey,data,string

multipule_mfg_values.csv文件内容：
id,DeviceName,DeviceSecret,ProductKey
1,d8905151,Piwto064haIA59x3Z0,a1TGu0u
2,d8905152,Piwto064haIA59x3Z1,a1TGu0u
3,d8905153,Piwto064haIA59x3Z2,a1TGu0u
4,d8905154,Piwto064haIA59x3Z3,a1TGu0u
5,d8905155,Piwto064haIA59x3Z4,a1TGu0u

**Comment by Alvin1Zhang** [comment]
@enric-lee Thanks for reporting this, we have looked into this and will provide updates if available. Thanks.

**Comment by enric-lee** [comment]
It's a good project. I hope it's getting better and better. ^_^

**Comment by shivani-tipnis** [comment]
Hi @enric-lee 
Could you please confirm your IDF_PATH. 
Say if you are running **mfg_gen.py** on **v4.0**, the **IDF_PATH** needs to be set to the **same version(v4.0)**. 
Similarly, if you are running it on **v3.2**, **IDF_PATH** needs to be set to the **same version(v3.2).**

**Comment by Alvin1Zhang** [comment]
@enric-lee Thanks for reporting. Would you please help share if any updates for this issue? Thanks.

**Comment by enric-lee** [comment]
> Hi @enric-lee
> Could you please confirm your IDF_PATH.
> Say if you are running **mfg_gen.py** on **v4.0**, the **IDF_PATH** needs to be set to the **same version(v4.0)**.
> Similarly, if you are running it on **v3.2**, **IDF_PATH** needs to be set to the **same version(v3.2).**


**that's what i do:**

> root@iZuf6bkar79cnzuht5c71uZ:~/esp-idf/esp-idf-v3.2# ls
> root@iZuf6bkar79cnzuht5c71uZ:~/esp-idf/esp-idf-v3.2# git clone --recursive  https://github.com/espressif/esp-idf.git -b v3.2
> Cloning into 'esp-idf'...
> remote: Enumerating objects: 44, done.
> remote: Counting objects: 100% (44/44), done.
> remote: Compressing objects: 100% (36/36), done.
> remote: Total 112379 (delta 8), reused 16 (delta 3), pack-reused 112335
> Receiving objects: 100% (112379/112379), 80.18 MiB | 274.00 KiB/s, done.
> Resolving deltas: 100% (81273/81273), done.
> Checking connectivity... done.
> Note: checking out '286202caa31b61c2182209f37f8069a0b60fb942'.
> 
> You are in 'detached HEAD' state. You can look around, make experimental
> changes and commit them, and you can discard any commits you make in this
> state without impacting any branches by performing another checkout.
> 
> If you want to create a new branch to retain commits you create, you may
> do so (now or later) by using -b with the checkout command again. Example:
> 
>   git checkout -b <new-branch-name>
> 
> Submodule 'components/asio/asio' (https://github.com/espressif/asio.git) registered for path 'components/asio/asio'
> Submodule 'components/aws_iot/aws-iot-device-sdk-embedded-C' (https://github.com/espressif/aws-iot-device-sdk-embedded-C.git) registered for path 'components/aws_iot/a
> Submodule 'components/bt/lib' (https://github.com/espressif/esp32-bt-lib.git) registered for path 'components/bt/lib'
> Submodule 'components/coap/libcoap' (https://github.com/obgm/libcoap.git) registered for path 'components/coap/libcoap'
> Submodule 'components/esp32/lib' (https://github.com/espressif/esp32-wifi-lib.git) registered for path 'components/esp32/lib'
> Submodule 'components/esptool_py/esptool' (https://github.com/espressif/esptool.git) registered for path 'components/esptool_py/esptool'
> Submodule 'components/expat/expat' (https://github.com/libexpat/libexpat.git) registered for path 'components/expat/expat'
> Submodule 'components/json/cJSON' (https://github.com/DaveGamble/cJSON.git) registered for path 'components/json/cJSON'
> Submodule 'components/libsodium/libsodium' (https://github.com/jedisct1/libsodium.git) registered for path 'components/libsodium/libsodium'
> Submodule 'components/lwip/lwip' (https://github.com/espressif/esp-lwip.git) registered for path 'components/lwip/lwip'
> Submodule 'components/mbedtls/mbedtls' (https://github.com/espressif/mbedtls.git) registered for path 'components/mbedtls/mbedtls'
> Submodule 'components/micro-ecc/micro-ecc' (https://github.com/kmackay/micro-ecc.git) registered for path 'components/micro-ecc/micro-ecc'
> Submodule 'components/mqtt/esp-mqtt' (https://github.com/espressif/esp-mqtt.git) registered for path 'components/mqtt/esp-mqtt'
> Submodule 'components/nghttp/nghttp2' (https://github.com/nghttp2/nghttp2.git) registered for path 'components/nghttp/nghttp2'
> Submodule 'components/protobuf-c/protobuf-c' (https://github.com/protobuf-c/protobuf-c) registered for path 'components/protobuf-c/protobuf-c'
> Submodule 'components/spiffs/spiffs' (https://github.com/pellepl/spiffs.git) registered for path 'components/spiffs/spiffs'
> Cloning into 'components/asio/asio'...
> remote: Enumerating objects: 45479, done.
> remote: Total 45479 (delta 0), reused 0 (delta 0), pack-reused 45479
> Receiving objects: 100% (45479/45479), 15.38 MiB | 246.00 KiB/s, done.
> Resolving deltas: 100% (30490/30490), done.
> Checking connectivity... done.
> Submodule path 'components/asio/asio': checked out '55efc179b76139c8f9b44bf22a4aba4803f7a7bd'
> Cloning into 'components/aws_iot/aws-iot-device-sdk-embedded-C'...
> remote: Enumerating objects: 1292, done.
> remote: Total 1292 (delta 0), reused 0 (delta 0), pack-reused 1292
> Receiving objects: 100% (1292/1292), 878.44 KiB | 479.00 KiB/s, done.
> Resolving deltas: 100% (716/716), done.
> Checking connectivity... done.
> Submodule path 'components/aws_iot/aws-iot-device-sdk-embedded-C': checked out '299183238ffe7a3e6a5ca0af9db19c10eaca62cf'
> Cloning into 'components/bt/lib'...
> remote: Enumerating objects: 39, done.
> remote: Counting objects: 100% (39/39), done.
> remote: Compressing objects: 100% (27/27), done.
> remote: Total 652 (delta 25), reused 26 (delta 12), pack-reused 613
> Receiving objects: 100% (652/652), 2.67 MiB | 828.00 KiB/s, done.
> Resolving deltas: 100% (439/439), done.
> Checking connectivity... done.
> Submodule path 'components/bt/lib': checked out '6c3379db92017f5713e807b60208b62c205d2e05'
> Cloning into 'components/coap/libcoap'...
> remote: Enumerating objects: 32, done.
> remote: Counting objects: 100% (32/32), done.
> remote: Compressing objects: 100% (28/28), done.
> remote: Total 8818 (delta 9), reused 14 (delta 3), pack-reused 8786
> Receiving objects: 100% (8818/8818), 3.32 MiB | 193.00 KiB/s, done.
> Resolving deltas: 100% (6210/6210), done.
> Checking connectivity... done.
> Submodule path 'components/coap/libcoap': checked out '6468887a12666f88b8704d797fc176cd4f40ee4c'
> Cloning into 'components/esp32/lib'...
> remote: Enumerating objects: 461, done.
> remote: Counting objects: 100% (461/461), done.
> remote: Compressing objects: 100% (174/174), done.
> remote: Total 6068 (delta 360), reused 365 (delta 287), pack-reused 5607
> Receiving objects: 100% (6068/6068), 58.35 MiB | 190.00 KiB/s, done.
> Resolving deltas: 100% (4950/4950), done.
> Checking connectivity... done.
> Submodule path 'components/esp32/lib': checked out 'eb53491cf6eb18d6cfd98f7b3bb4e09fb241733c'
> Cloning into 'components/esptool_py/esptool'...
> remote: Enumerating objects: 7, done.
> remote: Counting objects: 100% (7/7), done.
> remote: Compressing objects: 100% (7/7), done.
> remote: Total 2032 (delta 0), reused 7 (delta 0), pack-reused 2025
> Receiving objects: 100% (2032/2032), 7.52 MiB | 159.00 KiB/s, done.
> Resolving deltas: 100% (1254/1254), done.
> Checking connectivity... done.
> Submodule path 'components/esptool_py/esptool': checked out '9ad444a6e06e58833d5e6044c1d5f3eb3dd56023'
> Cloning into 'components/expat/expat'...
> remote: Enumerating objects: 102, done.
> remote: Counting objects: 100% (102/102), done.
> remote: Compressing objects: 100% (57/57), done.
> remote: Total 16048 (delta 58), reused 73 (delta 45), pack-reused 15946
> Receiving objects: 100% (16048/16048), 13.57 MiB | 991.00 KiB/s, done.
> Resolving deltas: 100% (11998/11998), done.
> Checking connectivity... done.
> Submodule path 'components/expat/expat': checked out '968b8cc46dbee47b83318d5f31a8e7907199614b'
> Cloning into 'components/json/cJSON'...
> remote: Enumerating objects: 39, done.
> remote: Counting objects: 100% (39/39), done.
> remote: Compressing objects: 100% (31/31), done.
> remote: Total 4080 (delta 16), reused 20 (delta 8), pack-reused 4041
> Receiving objects: 100% (4080/4080), 2.33 MiB | 268.00 KiB/s, done.
> Resolving deltas: 100% (2702/2702), done.
> Checking connectivity... done.
> Submodule path 'components/json/cJSON': checked out '7cc52f60356909b3dd260304c7c50c0693699353'
> Cloning into 'components/libsodium/libsodium'...
> remote: Enumerating objects: 13, done.
> remote: Counting objects: 100% (13/13), done.
> remote: Compressing objects: 100% (13/13), done.
> remote: Total 29879 (delta 2), reused 6 (delta 0), pack-reused 29866
> Receiving objects: 100% (29879/29879), 7.53 MiB | 234.00 KiB/s, done.
> Resolving deltas: 100% (17615/17615), done.
> Checking connectivity... done.
> Submodule path 'components/libsodium/libsodium': checked out '70170c28c844a4786e75efc626e1aeebc93caebc'
> Cloning into 'components/lwip/lwip'...
> remote: Enumerating objects: 1258, done.
> remote: Counting objects: 100% (1258/1258), done.
> remote: Compressing objects: 100% (500/500), done.
> remote: Total 49540 (delta 823), reused 1029 (delta 737), pack-reused 48282
> Receiving objects: 100% (49540/49540), 10.27 MiB | 319.00 KiB/s, done.
> Resolving deltas: 100% (37277/37277), done.
> Checking connectivity... done.
> Submodule path 'components/lwip/lwip': checked out 'fe9a58cb7abdc74e7a2196b7c4e0a29ff9042f88'
> Cloning into 'components/mbedtls/mbedtls'...
> remote: Enumerating objects: 71159, done.
> remote: Total 71159 (delta 0), reused 0 (delta 0), pack-reused 71159
> Receiving objects: 100% (71159/71159), 32.18 MiB | 1019.00 KiB/s, done.
> Resolving deltas: 100% (54829/54829), done.
> Checking connectivity... done.
> Submodule path 'components/mbedtls/mbedtls': checked out '19eb57f7f7b2f4312d497ddbcb5f104fc6877c70'
> Cloning into 'components/micro-ecc/micro-ecc'...
> remote: Enumerating objects: 1086, done.
> remote: Total 1086 (delta 0), reused 0 (delta 0), pack-reused 1086
> Receiving objects: 100% (1086/1086), 647.94 KiB | 117.00 KiB/s, done.
> Resolving deltas: 100% (637/637), done.
> Checking connectivity... done.
> Submodule path 'components/micro-ecc/micro-ecc': checked out 'd037ec89546fad14b5c4d5456c2e23a71e554966'
> Cloning into 'components/mqtt/esp-mqtt'...
> remote: Enumerating objects: 41, done.
> remote: Counting objects: 100% (41/41), done.
> remote: Compressing objects: 100% (29/29), done.
> remote: Total 2015 (delta 16), reused 31 (delta 12), pack-reused 1974
> Receiving objects: 100% (2015/2015), 1.41 MiB | 576.00 KiB/s, done.
> Resolving deltas: 100% (1070/1070), done.
> Checking connectivity... done.
> Submodule path 'components/mqtt/esp-mqtt': checked out 'f08f3b678717865234637164a29ed3a63e756ca7'
> Cloning into 'components/nghttp/nghttp2'...
> remote: Enumerating objects: 139, done.
> remote: Counting objects: 100% (139/139), done.
> remote: Compressing objects: 100% (71/71), done.
> remote: Total 40003 (delta 78), reused 108 (delta 68), pack-reused 39864
> Receiving objects: 100% (40003/40003), 30.95 MiB | 160.00 KiB/s, done.
> Resolving deltas: 100% (29822/29822), done.
> Checking connectivity... done.
> Submodule path 'components/nghttp/nghttp2': checked out '3bcc416e13cc790e2fb45fcfe9111d38609c5032'
> Submodule 'third-party/mruby' (https://github.com/mruby/mruby) registered for path 'third-party/mruby'
> Submodule 'third-party/neverbleed' (https://github.com/h2o/neverbleed.git) registered for path 'third-party/neverbleed'
> Cloning into 'third-party/mruby'...
> remote: Enumerating objects: 7, done.
> remote: Counting objects: 100% (7/7), done.
> remote: Compressing objects: 100% (7/7), done.
> remote: Total 52198 (delta 0), reused 3 (delta 0), pack-reused 52191
> Receiving objects: 100% (52198/52198), 12.66 MiB | 235.00 KiB/s, done.
> Resolving deltas: 100% (32621/32621), done.
> Checking connectivity... done.
> Submodule path 'components/nghttp/nghttp2/third-party/mruby': checked out '22464fe5a0a10f2b077eaba109ce1e912e4a77de'
> Cloning into 'third-party/neverbleed'...
> remote: Enumerating objects: 40, done.
> remote: Counting objects: 100% (40/40), done.
> remote: Compressing objects: 100% (24/24), done.
> remote: Total 272 (delta 23), reused 29 (delta 16), pack-reused 232
> Receiving objects: 100% (272/272), 96.80 KiB | 0 bytes/s, done.
> Resolving deltas: 100% (162/162), done.
> Checking connectivity... done.
> Submodule path 'components/nghttp/nghttp2/third-party/neverbleed': checked out 'da5c2ab419a3bb8a4cc6c37a6c7f3e4bd4b41134'
> Cloning into 'components/protobuf-c/protobuf-c'...
> remote: Enumerating objects: 3239, done.
> remote: Total 3239 (delta 0), reused 0 (delta 0), pack-reused 3239
> Receiving objects: 100% (3239/3239), 1.23 MiB | 556.00 KiB/s, done.
> Resolving deltas: 100% (2060/2060), done.
> Checking connectivity... done.
> Submodule path 'components/protobuf-c/protobuf-c': checked out 'dac1a65feac4ad72f612aab99f487056fbcf5c1a'
> Cloning into 'components/spiffs/spiffs'...
> remote: Enumerating objects: 5, done.
> remote: Counting objects: 100% (5/5), done.
> remote: Compressing objects: 100% (5/5), done.
> remote: Total 1460 (delta 0), reused 2 (delta 0), pack-reused 1455
> Receiving objects: 100% (1460/1460), 1020.41 KiB | 238.00 KiB/s, done.
> Resolving deltas: 100% (1020/1020), done.
> Checking connectivity... done.
> Submodule path 'components/spiffs/spiffs': checked out 'f5e26c4e933189593a71c6b82cda381a7b21e41c'
> 
> root@iZuf6bkar79cnzuht5c71uZ:~/esp-idf/esp-idf-v3.2# export IDF_PATH=~/esp-idf/esp-idf-v3.2/esp-idf
> root@iZuf6bkar79cnzuht5c71uZ:~/esp-idf/esp-idf-v3.2# echo $IDF_PATH
> /root/esp-idf/esp-idf-v3.2/esp-idf
> 
> 
> root@iZuf6bkar79cnzuht5c71uZ:~/esp-idf/esp-idf-v3.2# 
> root@iZuf6bkar79cnzuht5c71uZ:~/esp-idf/esp-idf-v3.2# cd esp-idf/tools/
> catch/            cmake/            esp_prov/         kconfig_new/      test_idf_monitor/ tiny-test-fw/     windows/          
> ci/               esp_app_trace/    kconfig/          mass_mfg/         test_idf_size/    unit-test-app/    
> root@iZuf6bkar79cnzuht5c71uZ:~/esp-idf/esp-idf-v3.2# cd esp-idf/tools/mass_mfg/
> root@iZuf6bkar79cnzuht5c71uZ:~/esp-idf/esp-idf-v3.2/esp-idf/tools/mass_mfg# 
> root@iZuf6bkar79cnzuht5c71uZ:~/esp-idf/esp-idf-v3.2/esp-idf/tools/mass_mfg# ls
> docs  mfg_gen.py  samples
> root@iZuf6bkar79cnzuht5c71uZ:~/esp-idf/esp-idf-v3.2/esp-idf/tools/mass_mfg# vim multipule_mfg_config.csv
> root@iZuf6bkar79cnzuht5c71uZ:~/esp-idf/esp-idf-v3.2/esp-idf/tools/mass_mfg# vim multipule_mfg_values.csv
> root@iZuf6bkar79cnzuht5c71uZ:~/esp-idf/esp-idf-v3.2/esp-idf/tools/mass_mfg# python mfg_gen.py --conf multipule_mfg_config.csv --values multipule_mfg_values.csv --prefix scgw --size 0x4000
> Traceback (most recent call last):
>   File "mfg_gen.py", line 19, in <module>
>     from builtins import range
> ImportError: No module named builtins
> 
> root@iZuf6bkar79cnzuht5c71uZ:~/esp-idf/esp-idf-v3.2/esp-idf/tools/mass_mfg# pip install future
> DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
> Looking in indexes: http://mirrors.cloud.aliyuncs.com/pypi/simple/
> Collecting future
>   Downloading http://mirrors.cloud.aliyuncs.com/pypi/packages/f6/85/c273089eb6efa5644c0a1382ea553554bc0d40e00a46d989ec67f123f8b5/future-0.18.0.tar.gz (830kB)
>      |?𷰿𻓟?𷰿𻓟?𷰿𻓟?𷰿𻓟?𷰿𻓟?𷰿𻓟?𷰿𻓟?𷰿𻓟?𷰿𻓟?𷰿𻓟?𷰿𻓟?𷰿𻓟?𷰿𻓟?𷰿𻓟?𷰿𻓟?𷰿𻓟| 839kB 27.4MB/s 
> Building wheels for collected packages: future
>   Building wheel for future (setup.py) ... done
>   Stored in directory: /root/.cache/pip/wheels/69/f2/01/215805a5c9877b049e4901041c03fc3959252f88179afbabe5
> Successfully built future
> Installing collected packages: future
> Successfully installed future-0.18.0
> WARNING: You are using pip version 19.1.1, however version 19.2.3 is available.
> You should consider upgrading via the 'pip install --upgrade pip' command.
> root@iZuf6bkar79cnzuht5c71uZ:~/esp-idf/esp-idf-v3.2/esp-idf/tools/mass_mfg# pip install pyopenssl
> DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
> Looking in indexes: http://mirrors.cloud.aliyuncs.com/pypi/simple/
> Collecting pyopenssl
>   Downloading http://mirrors.cloud.aliyuncs.com/pypi/packages/01/c8/ceb170d81bd3941cbeb9940fc6cc2ef2ca4288d0ca8929ea4db5905d904d/pyOpenSSL-19.0.0-py2.py3-none-any.whl (53kB)
>      |?𷰿𻓟?𷰿𻓟?𷰿𻓟?𷰿𻓟?𷰿𻓟?𷰿𻓟?𷰿𻓟?𷰿𻓟?𷰿𻓟?𷰿𻓟?𷰿𻓟?𷰿𻓟?𷰿𻓟?𷰿𻓟?𷰿𻓟?𷰿𻓟| 61kB 39.4MB/s 
> Requirement already satisfied: six>=1.5.2 in /usr/local/lib/python2.7/dist-packages (from pyopenssl) (1.12.0)
> Collecting cryptography>=2.3 (from pyopenssl)
>   Downloading http://mirrors.cloud.aliyuncs.com/pypi/packages/e6/68/50698ce24c61db7d44d93a5043c621a0ca7839d4ef9dff913e6ab465fc92/cryptography-2.7-cp27-cp27mu-manylinux1_x86_64.whl (2.3MB)
>      |?𷰿𻓟?𷰿𻓟?𷰿𻓟?𷰿𻓟?𷰿𻓟?𷰿𻓟?𷰿𻓟?𷰿𻓟?𷰿𻓟?𷰿𻓟?𷰿𻓟?𷰿𻓟?𷰿𻓟?𷰿𻓟?𷰿𻓟?𷰿𻓟| 2.3MB 33.2MB/s 
> Collecting enum34; python_version < "3" (from cryptography>=2.3->pyopenssl)
>   Downloading http://mirrors.cloud.aliyuncs.com/pypi/packages/c5/db/e56e6b4bbac7c4a06de1c50de6fe1ef3810018ae11732a50f15f62c7d050/enum34-1.1.6-py2-none-any.whl
> Collecting cffi!=1.11.3,>=1.8 (from cryptography>=2.3->pyopenssl)
>   Downloading http://mirrors.cloud.aliyuncs.com/pypi/packages/8d/e9/0c8afd1579e5cf7bc0f06fbcd7cdb954cbc0baadd505973949a99337da1c/cffi-1.12.3-cp27-cp27mu-manylinux1_x86_64.whl (415kB)
>      |?𷰿𻓟?𷰿𻓟?𷰿𻓟?𷰿𻓟?𷰿𻓟?𷰿𻓟?𷰿𻓟?𷰿𻓟?𷰿𻓟?𷰿𻓟?𷰿𻓟?𷰿𻓟?𷰿𻓟?𷰿𻓟?𷰿𻓟?𷰿𻓟| 419kB 43.8MB/s 
> Collecting asn1crypto>=0.21.0 (from cryptography>=2.3->pyopenssl)
>   Downloading http://mirrors.cloud.aliyuncs.com/pypi/packages/8d/c3/be192e56ab85a7b2439caf83049b9936292aaf0398038a2fe28716f18951/asn1crypto-1.0.1-py2.py3-none-any.whl (103kB)
>      |?𷰿𻓟?𷰿𻓟?𷰿𻓟?𷰿𻓟?𷰿𻓟?𷰿𻓟?𷰿𻓟?𷰿𻓟?𷰿𻓟?𷰿𻓟?𷰿𻓟?𷰿𻓟?𷰿𻓟?𷰿𻓟?𷰿𻓟?𷰿𻓟| 112kB 49.9MB/s 
> Collecting ipaddress; python_version < "3" (from cryptography>=2.3->pyopenssl)
>   Downloading http://mirrors.cloud.aliyuncs.com/pypi/packages/fc/d0/7fc3a811e011d4b388be48a0e381db8d990042df54aa4ef4599a31d39853/ipaddress-1.0.22-py2.py3-none-any.whl
> Collecting pycparser (from cffi!=1.11.3,>=1.8->cryptography>=2.3->pyopenssl)
>   Downloading http://mirrors.cloud.aliyuncs.com/pypi/packages/68/9e/49196946aee219aead1290e00d1e7fdeab8567783e83e1b9ab5585e6206a/pycparser-2.19.tar.gz (158kB)
>      |?𷰿𻓟?𷰿𻓟?𷰿𻓟?𷰿𻓟?𷰿𻓟?𷰿𻓟?𷰿𻓟?𷰿𻓟?𷰿𻓟?𷰿𻓟?𷰿𻓟?𷰿𻓟?𷰿𻓟?𷰿𻓟?𷰿𻓟?𷰿𻓟| 163kB 47.0MB/s 
> Building wheels for collected packages: pycparser
>   Building wheel for pycparser (setup.py) ... done
>   Stored in directory: /root/.cache/pip/wheels/92/a2/51/5ed9eedca157b6decba18a0cf880380c9fd9ed6dca46fa791c
> Successfully built pycparser
> Installing collected packages: enum34, pycparser, cffi, asn1crypto, ipaddress, cryptography, pyopenssl
> Successfully installed asn1crypto-1.0.1 cffi-1.12.3 cryptography-2.7 enum34-1.1.6 ipaddress-1.0.22 pycparser-2.19 pyopenssl-19.0.0
> WARNING: You are using pip version 19.1.1, however version 19.2.3 is available.
> You should consider upgrading via the 'pip install --upgrade pip' command.
> root@iZuf6bkar79cnzuht5c71uZ:~/esp-idf/esp-idf-v3.2/esp-idf/tools/mass_mfg# pip install cryptography
> DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
> Looking in indexes: http://mirrors.cloud.aliyuncs.com/pypi/simple/
> Requirement already satisfied: cryptography in /usr/local/lib/python2.7/dist-packages (2.7)
> Requirement already satisfied: enum34; python_version < "3" in /usr/local/lib/python2.7/dist-packages (from cryptography) (1.1.6)
> Requirement already satisfied: cffi!=1.11.3,>=1.8 in /usr/local/lib/python2.7/dist-packages (from cryptography) (1.12.3)
> Requirement already satisfied: six>=1.4.1 in /usr/local/lib/python2.7/dist-packages (from cryptography) (1.12.0)
> Requirement already satisfied: asn1crypto>=0.21.0 in /usr/local/lib/python2.7/dist-packages (from cryptography) (1.0.1)
> Requirement already satisfied: ipaddress; python_version < "3" in /usr/local/lib/python2.7/dist-packages (from cryptography) (1.0.22)
> Requirement already satisfied: pycparser in /usr/local/lib/python2.7/dist-packages (from cffi!=1.11.3,>=1.8->cryptography) (2.19)
> WARNING: You are using pip version 19.1.1, however version 19.2.3 is available.
> You should consider upgrading via the 'pip install --upgrade pip' command.
> 
> 
> root@iZuf6bkar79cnzuht5c71uZ:~/esp-idf/esp-idf-v3.2/esp-idf/tools/mass_mfg# 
> root@iZuf6bkar79cnzuht5c71uZ:~/esp-idf/esp-idf-v3.2/esp-idf/tools/mass_mfg# python mfg_gen.py --conf multipule_mfg_config.csv --values multipule_mfg_values.csv --prefix scgw --size 0x4000
> CSV Generated:  ./csv/scgw-1.csv
> nvs_part_gen() got an unexpected keyword argument 'input_size'
> root@iZuf6bkar79cnzuht5c71uZ:~/esp-idf/esp-idf-v3.2/esp-idf/tools/mass_mfg#

**Comment by shivani-tipnis** [comment]
Hi @enric-lee 
Thanks for the sending in the steps. 
Could you please checkout to branch release/v3.2 or update to v3.2.3 bugfix release, you should be able to run it then.
Thanks.

**Comment by Alvin1Zhang** [comment]
@enric-lee Thanks for reporting, will close due to short of feedback, feel free to reopen if the issue still exists. Thanks.
