### ISSUE TITLE
ESP32 S2 BETA Programming IDE (IDFGH-1832)

### ISSUE THREAD

**Issue by shveytank** [espressif/esp-idf#4041]
Hi i recently came to know that ESP32 S2 Beta version is released and i've got one, so i was asking which IDE you guys are using to test it or program it.

**Comment by Alvin1Zhang** [comment]
@shveytank Thanks for reporting this.

**Comment by huming2207** [comment]
CLion should work as it's still shares the same CMake build system. VSCode with vscode-cmake-tool plugin also works, but it is kinda outdated (should get updates later this month) and it won't handle the include path correctly sometimes.

**Comment by shveytank** [comment]
@huming2207 would you like to share with me that how you programmed it because i am familiar with Arduino IDE, ESPIDF (a very little), avr studio but not much with VS.

**Comment by huming2207** [comment]
@shveytank Just use `idf.py` in the console separately.

**Comment by shveytank** [comment]
Please Can you provide me a little walk through how to program it. It would be very helpful .
Thanks in advance.

**Comment by aallan** [comment]
Brief walkthrough on using `idf.py` in the console here, https://esp32.com/viewtopic.php?f=13&t=11265

**Comment by igrr** [comment]
Closing as both the VS Code extension (https://github.com/espressif/vscode-esp-idf-extension) and Eclipse plugin (https://github.com/espressif/idf-eclipse-plugin) can be used to develop for ESP32-S2.
