### ISSUE TITLE
The most simple communication between two lolin32 wemos. (IDFGH-1833)

### ISSUE THREAD

**Issue by mintcats** [espressif/esp-idf#4042]
What is the most simple communication between two lolin32 wemos plates (esp32) using esp-idf?

**Comment by Alvin1Zhang** [comment]
Thanks for reporting the issue. Would you please help provide more details as suggested in the [issue template](https://github.com/espressif/esp-idf/blob/master/docs/issue_template.md)? Information like elf, sdk configuration, backtrace, log outputs, commit ID, hardware and etc. would help us debug further. For "how" questions, you could raise a post at our forum https://esp32.com. Thanks. @mintcats
