### ISSUE TITLE
Now esp32 can support wechat airsync ? (IDFGH-1846)

### ISSUE THREAD

**Issue by xuhongv** [espressif/esp-idf#4055]
can esp32 can support wechat airsync now ?

**Comment by TimXia** [comment]
@Weijian-Espressif

**Comment by Weijian-Espressif** [comment]
@xuhongv ESP32 support WeChat airsync. We will merge the airsync example into latest IDF.

**Comment by xuhongv** [comment]
@Weijian-Espressif  Thanks. I am happy about this, please open source as soon as possible.

**Comment by xuhongv** [comment]
@Weijian-Espressif  How long merge the airsync example into latest IDF ？

**Comment by xuhongv** [comment]
@Weijian-Espressif How long merge the airsync example into latest IDF ？

**Comment by Weijian-Espressif** [comment]
@xuhongv we will send you the source code later.

**Comment by xuhongv** [comment]
thanks ， My email :   xuhongv@yeah.net
