### ISSUE TITLE
Wiznet 5500 (IDFGH-1849)

### ISSUE THREAD

**Issue by drdelgado** [espressif/esp-idf#4056]
## Environment

- Development Kit:      [ESP32-Wrover-Kit|ESP32-DevKitC|ESP32-PICO-Kit|ESP32-LyraT|ESP32-LyraTD-MSC|none]
- Kit version (for WroverKit/PicoKit/DevKitC): [v1|v2|v3|v4]
- Module or chip used:  [ESP32-WROOM-32|ESP32-WROOM-32D|ESP32-WROOM-32U|ESP32-WROVER|ESP32-WROVER-I|ESP32-WROVER-B|ESP32-WROVER-IB|ESP32-SOLO-1|ESP32-PICO-D4|ESP32]
- IDF version (run ``git describe --tags`` to find it): 
    // v3.2-dev-1148-g96cd3b75c
- Build System:         [Make|CMake]
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it):
    // 1.22.0-80-g6c4433a
- Operating System:     [Windows|Linux|macOS]
- Power Supply:         [USB|external 5V|external 3.3V|Battery]

## Problem Description

What would be the ESP-IDF approach to adding Adafruit Featherwing Ethernet Wiznet 5500 https://learn.adafruit.com/adafruit-wiz5500-wiznet-ethernet-featherwing/overview 

```
    ESP_ERROR_CHECK(esp_event_loop_create_default());
    ESP_ERROR_CHECK(tcpip_adapter_set_default_eth_handlers());
    ESP_ERROR_CHECK(esp_event_handler_register(ETH_EVENT, ESP_EVENT_ANY_ID, &eth_event_handler, NULL));
    ESP_ERROR_CHECK(esp_event_handler_register(IP_EVENT, IP_EVENT_ETH_GOT_IP, &got_ip_event_handler, NULL));

    eth_mac_config_t mac_config = ETH_MAC_DEFAULT_CONFIG();
    eth_phy_config_t phy_config = ETH_PHY_DEFAULT_CONFIG();
#if CONFIG_EXAMPLE_USE_INTERNAL_ETHERNET
    esp_eth_mac_t *mac = esp_eth_mac_new_esp32(&mac_config);
#if CONFIG_EXAMPLE_ETH_PHY_IP101
    esp_eth_phy_t *phy = esp_eth_phy_new_ip101(&phy_config);
#elif CONFIG_EXAMPLE_ETH_PHY_RTL8201
    esp_eth_phy_t *phy = esp_eth_phy_new_rtl8201(&phy_config);
#elif CONFIG_EXAMPLE_ETH_PHY_LAN8720
    esp_eth_phy_t *phy = esp_eth_phy_new_lan8720(&phy_config);
#elif CONFIG_EXAMPLE_ETH_PHY_DP83848
    esp_eth_phy_t *phy = esp_eth_phy_new_dp83848(&phy_config);
#endif
#elif CONFIG_EXAMPLE_USE_SPI_ETHERNET
```

I noticed you have some `CONFIG_EXAMPLE_USE_SPI_ETHERNET` has any one had any success using this for that chipset?

**Comment by suda-morris** [comment]
Hi @drdelgado W5500 is not compatible with LwIP because W5500=PHY+MAC+TCP/IP, it has a hardware TCP/IP engine. If you want to use Ethernet with less pins, you can give DM9051 a try. Currently it's the only SPI Ethernet we support in idf.

**Comment by negativekelvin** [comment]
@suda-morris I thought we talked about that in the other issue.  There is a valid workaround to have w5500 work with lwip in macraw mode.  It's fine if you don't want to support it, just don't use incompatibility as an excuse :stuck_out_tongue:

**Comment by suda-morris** [comment]
Thanks for correcting me @negativekelvin :sweat_smile: 

W5500 is cool if we can have it in IDF, but I'm sorry it's not in a high priority now. I hope I can do some extra experiment on the macraw mode and bring it to idf.

**Comment by psykokwak-com** [comment]
Hi all,
There is an attempt to add W5500 to the ESP32 LWIP stack : https://github.com/johnnytolengo/w5500lwip
Maybe it's a good starting point

**Comment by am-ar** [comment]
@psykokwak-com at https://github.com/espressif/esp-idf/issues/2303#issuecomment-676798043 has another implementation that works and can be used as a reference when implementing a driver using the MACRAW socket of these chips.
