### ISSUE TITLE
Internet access captive portal (IDFGH-1868)

### ISSUE THREAD

**Issue by AlphaArslan** [espressif/esp-idf#4075]
Hi there
Thanks for the great contribution we really appreciate that.

I'm trying to build on your code by adding captive portal to it.
Can you help me with any tips or directions ?

Captive Portal that allows the user to access the internet. something like what you would see in hotels and so

Thanks

**Comment by Alvin1Zhang** [comment]
@AlphaArslan Thanks for reporting. Would you please help provide more details as suggested in the [issue template](https://github.com/espressif/esp-idf/blob/master/docs/issue_template.md)? Information like elf, sdk configuration, backtrace, log outputs, commit ID, hardware and etc. would help us debug further. And for "how" questions, we suggest you raise a post on our forum at https://esp32.com. Thanks.

**Comment by negativekelvin** [comment]
https://github.com/search?q=esp32+captive

**Comment by septatrix** [comment]
> Would you please help provide more details as suggested... And for "how" questions, we suggest you raise a post on our forum...

I guess details are not necessary as this is mostly a how question. However I would really like to have code for a softAP featuring a captive portal to the examples.
