### ISSUE TITLE
OTA native example problem on master branch (IDFGH-1875)

### ISSUE THREAD

**Issue by pegahnikbakht** [espressif/esp-idf#4080]
## Environment

- Module or chip used:  ESP32-WROOM-32D
- Operating System:     Linux
- Power Supply:         USB

## Problem Description

I tried to run OTA native example without any changes but it fails... 
Is there any fix for this problem? 
You can see the errors below:

## Debug Logs

I (55232) example_connect: IPv4 address: 192.168.49.26
I (55242) example_connect: IPv6 address: fe80:0000:0000:0000:32ae:a4ff:fed3:3470
I (55252) native_ota_example: Starting OTA example
I (55252) native_ota_example: Running partition type 0 subtype 0 (offset 0x00010000)
E (71372) esp-tls: mbedtls_ssl_handshake returned -0x4c
I (71372) esp-tls: Certificate verified.
E (71372) esp-tls: Failed to open new connection
E (71372) TRANS_SSL: Failed to open a new connection
E (71382) HTTP_CLIENT: Connection failed, sock < 0
E (71382) native_ota_example: Failed to open HTTP connection: ERROR
E (71392) native_ota_example: Exiting task due to fatal error...

**Comment by Alvin1Zhang** [comment]
@pegahnikbakht Thanks for reporting, we will look into. Thanks.

**Comment by mahavirj** [comment]
@pegahnikbakht Which IDF version you are using? Can you please try with latest `master` branch? (Please refer https://github.com/espressif/esp-idf/issues/3192#issuecomment-520447135)

**Comment by pegahnikbakht** [comment]
@mahavirj I'm using the latest master branch: v4.1-dev-256-g9f145ff

**Comment by mahavirj** [comment]
@pegahnikbakht 

Can you please try replacing server certificate with one from, https://github.com/espressif/esp-jumpstart/blob/master/6_ota/main/cloud_cfg/github_server.cert and upgrade url to `https://raw.githubusercontent.com/wiki/espressif/esp-jumpstart/images/hello-world.bin`?  (This will upgrade to `hello-world` application hosted on github server instance)

I just tested this out on latest `master` branch and did not encounter any issues.

**Comment by mahavirj** [comment]
@pegahnikbakht Did you get chance to try out above suggestion?

**Comment by pegahnikbakht** [comment]
Sorry, I haven't tried it yet. We solve our problem by moving to stable branch.

**Comment by mahavirj** [comment]
@pegahnikbakht Can you please try against `master` branch once? We have fixed one issue in `native_ota` example with chunked encoded stream from server (https://github.com/espressif/esp-idf/commit/ffdb57e04d454abc478c6f64b7b2c73e94319158).

**Comment by Yuvaraj4041** [comment]
> 
> 
> @pegahnikbakht
> 
> Can you please try replacing server certificate with one from, https://github.com/espressif/esp-jumpstart/blob/master/6_ota/main/cloud_cfg/github_server.cert and upgrade url to `https://raw.githubusercontent.com/wiki/espressif/esp-jumpstart/images/hello-world.bin`? (This will upgrade to `hello-world` application hosted on github server instance)
> 
> I just tested this out on latest `master` branch and did not encounter any issues.
Hi, Thanks, its working.

**Comment by mahavirj** [comment]
Thanks for confirming, closing this issue.
