### ISSUE TITLE
ota_initial_bin (IDFGH-1880)

### ISSUE THREAD

**Issue by hvishu** [espressif/esp-idf#4084]
Hi,
We use external flasher tool to program the ESP.  Before flashing we do erase.  Per my understanding, if we erase the flash we don't need to program the ota_data_initial.bin at 0x1E000.  Could you confirm?

Regards,
Vishwa

**Comment by KonstantinKondrashov** [comment]
Hi @hvishu! Yes, you are right, in your case (erasing all chip), it is not necessary to program the ota_data_initial.bin.

**Comment by Alvin1Zhang** [comment]
@hvishu Thanks for reporting, has your issue been resolved? Thanks.

**Comment by hvishu** [comment]
Thanks my doubt is cleared.
