### ISSUE TITLE
Websocket client can't establish a connection with parameters (IDFGH-1887)

### ISSUE THREAD

**Issue by boriss2oo6** [espressif/esp-idf#4090]
----------------------------- Delete above -----------------------------

## Environment

- Development Kit: ESP32-DevKitC
- Kit version (for WroverKit/PicoKit/DevKitC): v4
- Module or chip used:  ESP32-WROOM-32
- IDF version (run ``git describe --tags`` to find it): master and IDF4.0
- Build System:         [Make|CMake]
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it): (crosstool-NG crosstool-ng-1.22.0-80-g6c4433a5) 5.2.0
- Operating System:    Windows
- Power Supply:         USB

## Problem Description

With the current esp_websocket_client (using the example provided for websocket client) i try to make a connection with my server but to do this i need to establish a connection like: wss://myserverdns.com/CommApiHandler.ashx?DevId=11223344&HwType=X&HwSubType=AA because on server side need to link every connection with a device.

### Expected Behavior

Use the whole url when connecting to websocket

### Actual Behavior

Device is establishing a connection to wss://myserverdns.com:443/ and on server side the connection is closed due to null parameters received and connection couldn't validate.

## Other items if possible

If i change on server side to hard-code the parameters it works and the connection stays alive. 

Thanks in advance.

**Comment by Alvin1Zhang** [comment]
@boriss2oo6 Thanks for reporting, we will look into. Thanks.
