### ISSUE TITLE
Missing #include "esp_err.h" (IDFGH-1897)

### ISSUE THREAD

**Issue by joniaford** [espressif/esp-idf#4100]
## Environment

- Module or chip used:  ESP32
- Build System:   Make
- Operating System: macOS

## Problem Description
Getting the following errors when using `esp_tls.h` in my code

> esp_tls.h:59:5: error: unknown type name 'esp_err_t'
    esp_err_t last_error;               /*!< error code (based on ESP_ERR_ESP_TLS_BASE) of the last occur...
esp_tls.h:472:1: error: unknown type name 'esp_err_t'; did you mean 'esp_tls_t'?
esp_err_t esp_tls_init_global_ca_store(void);
^~~~~~~~~
esp_tls_t
tools/esp-idf/components/esp-tls/esp_tls.h:288:3: note: 'esp_tls_t' declared here
} esp_tls_t;
  ^
tools/esp-idf/components/esp-tls/esp_tls.h:491:1: error: unknown type name 'esp_err_t'; did you mean 'esp_tls_t'?
esp_err_t esp_tls_set_global_ca_store(const unsigned char *cacert_pem_buf, const unsigned int cacert_pem_bytes);
^~~~~~~~~
esp_tls_t
tools/esp-idf/components/esp-tls/esp_tls.h:288:3: note: 'esp_tls_t' declared here
} esp_tls_t;
  ^
tools/esp-idf/components/esp-tls/esp_tls.h:530:1: error: unknown type name 'esp_err_t'; did you mean 'esp_tls_t'?
esp_err_t esp_tls_get_and_clear_last_error(esp_tls_error_handle_t h, int *mbedtls_code, int *mbedtls_flags);
^~~~~~~~~
esp_tls_t
tools/esp-idf/components/esp-tls/esp_tls.h:288:3: note: 'esp_tls_t' declared here
} esp_tls_t;

Fixed by including `#include esp_err.h` in `esp_tls.h`

**Comment by flyingraijin9** [comment]
@joniaford Thank you for reporting , Have added esp_err.h in esp_tls.h, but may I know which  idf_version you are using , also can you list all the header files you are including in your app_main apart from esp_tls.h  and if possible also list the API you are using from esp_tls.h .
