### ISSUE TITLE
Clear WIFI without clearing NV (IDFGH-1907)

### ISSUE THREAD

**Issue by devropes** [espressif/esp-idf#4108]
I wanted to know if there is some sample code to erase the ESP32's WIFI information without clearing all of the NV memory?

Currently, the only method I know of is `nvs_flash_erase()`.

**Comment by negativekelvin** [comment]
Possibly like this

```
nvs_handle_t net80211_handle;
nvs_open("nvs.net80211", NVS_READWRITE, &net80211_handle);
nvs_erase_all(net80211_handle);
nvs_commit(net80211_handle);
nvs_close(net80211_handle);
```

**Comment by sagb2015** [comment]
@devropes - @negativekelvin answer should do it. However,  we will add an API to take care of this as users need not know the internal details such as partition name do perform this operation.

**Comment by sagb2015** [comment]
@devropes We have _esp_wifi_restore_ API to set the WiFi persistent settings to default values. Do you intend to reset the values to default or cleanup to save on the space?

**Comment by devropes** [comment]
Reset values to default.

**Comment by sagb2015** [comment]
"esp_wifi_restore" should work for your requirement then. Please try and let us know.

**Comment by sagb2015** [comment]
Closing the issue. Feel free to open this again if it does not satisfy your criteria.
