### ISSUE TITLE
expose httpd_default_send (IDFGH-1910)

### ISSUE THREAD

**Issue by ppisljar** [espressif/esp-idf#4110]
`httpd_default_send` function (as it can be seen here https://github.com/espressif/esp-idf/blob/master/examples/protocols/http_server/advanced_tests/main/tests.c ) should be added to the header file as its very useful for doing async responses (implementing EventSource for example)

**Comment by chhajedji** [comment]
Hello @ppisljar 

`httpd_default_send` is directly mapped to `send` and could be used by including `lwip/sockets.h`. So I don't think there is any need to do so. Is there anything else I could help you with?

**Comment by Alvin1Zhang** [comment]
@ppisljar Thanks for reporting, feel free to reopen if any updates. Thanks.
