### ISSUE TITLE
dl.espressif.com certificate expired (IDFGH-1911)

### ISSUE THREAD

**Issue by sieren** [espressif/esp-idf#4111]
`This server could not prove that it is dl.espressif.com; its security certificate expired yesterday. This may be caused by a misconfiguration or an attacker intercepting your connection. Your computer's clock is currently set to Tuesday, 24 September 2019. `

Looks like the download server needs to renew its certificate. Running the installation scripts is therefore currently broken due to an invalid certificate.

**Comment by Alvin1Zhang** [comment]
@sieren Thanks for the heads-up. We are now looking into this. Thanks.

**Comment by Alvin1Zhang** [comment]
@sieren Hi. We have fixed the certificate, would you please help try again? Thanks.

**Comment by sieren** [comment]
@Alvin1Zhang Nice one! It's back! Thank you :)
