### ISSUE TITLE
How Do I find Toolchain Setup ? (IDFGH-1919)

### ISSUE THREAD

**Issue by MA92** [espressif/esp-idf#4119]
I followed https://docs.espressif.com/projects/esp-idf/en/stable/get-started/linux-setup.html for linux but in the step Toolchain Setup ( tar -xzf ~/Downloads/xtensa-esp32-elf-linux64-1.22.0-80-g6c4433a-5.2.0.tar.gz),  it give me:  Error is not recoverable:exiting now.
Also I tried  https://docs.espressif.com/projects/esp-idf/en/latest/get-started/index.html  but in step 3 (cd ~/esp/esp-idf  ./install.sh)  it does not continue with the process.

**Comment by AldyKwee** [comment]
what did it output? I got the same issues in windows, when I do install.bat it outputs urllib error. It seems that the link for idf-exe is gone. 

I have raised the issue here: https://github.com/espressif/esp-idf/issues/4118

**Comment by Alvin1Zhang** [comment]
@MA92 @AldyKwee Thanks for reporting, we have noted this issue, and is now fixing. Will update once it is fixed, thanks.

**Comment by Alvin1Zhang** [comment]
@MA92 @AldyKwee We have fixed the issue, would you please try again? Thanks.

**Comment by Mario524** [comment]
it´s working! thanks .

**Comment by Alvin1Zhang** [comment]
@Mario524 Thanks for the notes. @MA92 Would you please help confirm whether your issue has been resolved? Thanks.

**Comment by MA92** [comment]
Yeah, the issue has been  resolved. Thanks

**Comment by Alvin1Zhang** [comment]
@MA92 Thanks for the confirmation, feel free to reopen the issue if it pops up again.
