### ISSUE TITLE
Duplicate definition in spi_common.h (IDFGH-1933)

### ISSUE THREAD

**Issue by jonsmirl** [espressif/esp-idf#4132]
The definition of spicommon_bus_using_iomux(spi_host_device_t host); is duplicated in spi_common.h This is causing micropython tools that process this file to fail.

diff --git a/components/driver/include/driver/spi_common.h b/components/driver/include/driver/spi_common.h
index b44159546..15e91cd45 100644
--- a/components/driver/include/driver/spi_common.h
+++ b/components/driver/include/driver/spi_common.h
@@ -319,7 +319,7 @@ bool spicommon_bus_using_iomux(spi_host_device_t host);
  *
  * @return false if any pins are through the GPIO matrix, otherwise true.
  */
-bool spicommon_bus_using_iomux(spi_host_device_t host);
+//bool spicommon_bus_using_iomux(spi_host_device_t host);
 
 /**
  * @brief Get the IRQ source for a specific SPI host

**Comment by ginkgm** [comment]
Hi @jonsmirl ,

We plan to make this function invisible from public domain, do you use it?

**Comment by jonsmirl** [comment]
We do not use, the duplicate declaration broke a tool used to compile micropython for ESP. The tool has been fixed to all duplicate definitions now.  The tool scans the header files and converts it into Python callable objects.
