### ISSUE TITLE
Find sources and includes automatically  (IDFGH-1936)

### ISSUE THREAD

**Issue by W-M-D** [espressif/esp-idf#4135]
Hello, I was wondering why you guys weren't using cmake to find required sources and includes automatically?

**Comment by igrr** [comment]
Hi @W-M-D, this is explained here: https://docs.espressif.com/projects/esp-idf/en/latest/api-guides/build-system.html#file-globbing-incremental-builds

**Comment by Alvin1Zhang** [comment]
@W-M-D Thanks for reporting, has your issue been resolved? Thanks.

**Comment by Alvin1Zhang** [comment]
@W-M-D Thanks for reporting, has your issue been resolved? Thanks.

**Comment by Alvin1Zhang** [comment]
@W-M-D Thanks for reporting, feel free to reopen if you still have the issue, thanks.
