### ISSUE TITLE
[TW#12187] ledc_get_duty() returns an int when it should return a uint32_t

### ISSUE THREAD

**Issue by nkolban** [espressif/esp-idf#414]
The ESP-IDF driver function called ledc_get_duty() is coded to return an int when it should be returning a uint32_t.  The ledc_set_duty() expects as input a uint32_t.

**Comment by negativekelvin** [comment]
There is a lot of mixed use of int and uint32_t in the driver including 

https://github.com/espressif/esp-idf/blob/8e4a8e17037c51ce2452e55b5b75bbfaecb25838/components/driver/ledc.c#L37

But these are max 24-bit values so shouldn't be much of an issue.  But should be consistent at least for API functions.

**Comment by jack0c** [comment]
@FayeY Maybe we can close this issue.

**Comment by negativekelvin** [comment]
@jack0c it may work, but it is lazy not to maintain consistent types
