### ISSUE TITLE
Persistent provisioner (IDFGH-1944)

### ISSUE THREAD

**Issue by jkockx** [espressif/esp-idf#4141]
## Environment

- Development Kit:      [ESP32-DevKitC]
- Kit version (for WroverKit/PicoKit/DevKitC): [v2]
- Module or chip used:  [ESP32-WROOM-32D]
- IDF version: v4.0-dev-1191-g138c941fa
- Build System:         [Make]
- Compiler version: xtensa-esp32-elf-gcc (crosstool-NG esp32-2019r1) 8.2.0
- Operating System:     [Linux]
- Power Supply:         [USB]

## Problem Description
Hello, I'm working on a project including a BLE mesh provisioner. I would like to be able to reboot the provisioner without losing all BLE mesh provisioning data. However, I've found that the esp-idf doesn't support this functionality (yet?) to store the data in nvs.
Is this to be added in the near future and if not so, are there work arounds for me to implement myself?

**Comment by WCCWCC** [comment]
Hi jkockx,
* The provisioner needs to store a lot of information, and we are implementing this feature.
* The specific time has not yet been fixed.

**Comment by jkockx** [comment]
Thanks for your reply @WCCWCC ,
Even though you're unable to provide a specific date when this will be implemented, would you have any sight on what measure of time you are speaking of. Will this be available one of the following months or will this have to wait more than a year.
That would be very important for me to know as my project pretty much relies on this persistent provisioning.

**Comment by Alvin1Zhang** [comment]
Hi @jkockx Thanks for reporting, since this is duplicate with [4242](https://github.com/espressif/esp-idf/issues/4242), will close this ticket and let us keep tracking in [4242](https://github.com/espressif/esp-idf/issues/4242). Thanks.
