### ISSUE TITLE
Build error in coap_mbedtls.c when ALPN is disabled (IDFGH-1958)

### ISSUE THREAD

**Issue by obgm** [espressif/esp-idf#4156]
## Environment

- Development Kit:      [none]
- Kit version (for WroverKit/PicoKit/DevKitC): [n/a]
- Module or chip used:  [n/a]
- IDF version: `v4.1-dev-369-g4dac7c7df`
- Build System:         [CMake]
- Compiler version: `xtensa-esp32-elf-gcc (crosstool-NG esp32-2019r1) 8.2.0`
- Operating System:     [Linux]
- Power Supply:         [n/a]

## Problem Description

With `CONFIG_MBEDTLS_SSL_ALPN` not set in sdkconfig, `idf.py build` stops building the `get-started/hello_world` example with the following error:

```
/opt/esp-idf/components/coap/port/coap_mbedtls.c: In function 'setup_client_ssl_session':
/opt/esp-idf/components/coap/port/coap_mbedtls.c:1057:13: error: implicit declaration of function 'mbedtls_ssl_conf_alpn_protocols'; did you mean 'mbedtls_ssl_conf_cert_profile'? [-Werror=implicit-function-declaration]
       ret = mbedtls_ssl_conf_alpn_protocols(&m_env->conf, alpn_list);
```

### Expected Behavior

I think that CoAP over DTLS should work independent of the ALPN configuration.

### Actual Behavior

Build succeeds with `CONFIG_MBEDTLS_SSL_ALPN=y` but not if `CONFIG_MBEDTLS_SSL_ALPN` ist disabled.

### Steps to repropduce

1. cd into `examples/get-started/hello_world` and run `idf.py menuconfig`
1. Disable `Component Config | mbedTLS | Support ALPN`
1. run `idf.py build`
```

**Comment by flyingraijin9** [comment]
@obgm , thanks for reporting , appropriate MR has been raised ! should be updated in github in few days
