### ISSUE TITLE
How Do I find Hardware for Programming the module (IDFGH-1962)

### ISSUE THREAD

**Issue by rolandma** [espressif/esp-idf#4160]
Just a quick question, I have a customized board using ESP-WRIIN-32D which I would like to re-program with my own software. Is there any existing hardware programmer/debugger that I can use to do that? I found the software for that, but I need the programmer/debugger. Is a dev board capable to be modified to handle the programming? 

Thanks!

Roland

**Comment by Alvin1Zhang** [comment]
@rolandma Thanks for reporting. For "how" questions, you could raise a post in our forum at https://esp32.com. Thanks.
