### ISSUE TITLE
Memory leak in vfs_fat_sdmmc#esp_vfs_fat_sdmmc_mount  (IDFGH-1969)

### ISSUE THREAD

**Issue by BeckerMarkus** [espressif/esp-idf#4165]
A small amount of memory allocated in `esp_vfs_fat_sdmmc_mount` will never be released, if the proc errors out via `goto fail`.

In esp_vfs_fat_sdmmc_mount, `s_base_path = strdup(base_path)` allocates memory. Then, if there is an error, the function performs a `goto fail` pattern, where all previously allocated resources should be released - it just misses `s_base_path`.

While the leak is small, there are scenarios where `esp_vfs_fat_sdmmc_mount` gets called multiple times and fails because the user inserted an invalid SD card
or the app uses a poor mans strategy to query for a plugged SD card by polling `esp_vfs_fat_sdmmc_mount`.

And easy to fix obviously:
```
--- /tmp/meld-tmpl80zweco
+++ /home/esp32/esp/esp-idf/components/fatfs/src/vfs_fat_sdmmc.c
@@ -158,6 +158,8 @@
     ff_diskio_unregister(pdrv);
     free(s_card);
     s_card = NULL;
+    free( s_base_path);
+    s_base_path = NULL;
     return err;
 }
```

Best,
Markus

**Comment by dobairoland** [comment]
Thank you @BeckerMarkus for reporting this and giving a hint to fix it. We'll look into this...
