### ISSUE TITLE
Port of net_sockets in mbedtls component does not have poll function (IDFGH-1976)

### ISSUE THREAD

**Issue by ghost** [espressif/esp-idf#4172]
The ESP-IDF port of `net_sockets` does not have a port of the `mbedtls_net_poll()` function. This is a requirement of the AWS-SDK v4 mbedtls wrapper, so is there any plan to add this function or is it not possible due to constraints of the ESP32 platform, in which case do you have a recommended solution?

**Comment by mahavirj** [comment]
@crippsJack If you copy/use `mbedtls_net_poll` from https://github.com/espressif/mbedtls/blob/f5f2e5926cd294ae7cb579ff6a12ad9303caeb6e/library/net_sockets.c#L456, does it help to unblock your use-case?

**Comment by crippsJack** [comment]
I will give this a try, thanks

**Comment by mahavirj** [comment]
Closing due to lack of response. Please feel to re-open if any further help is required,

**Comment by dragomat** [comment]
Is there any reason why `mbedtls_net_poll()` has never been included in ESP-IDF? 
I found myself in the same situation as described above (stuck waiting in ssl_write with no possibility of enabling the timeout) and even in the newest IDF versions (5.1 as well) it seems that we need to implement our own version of that function. 

Thanks
