### ISSUE TITLE
new api request for http client (IDFGH-1978)

### ISSUE THREAD

**Issue by w19787** [espressif/esp-idf#4174]
in order to use one http client for multiple http performs, we should have an api to clean up http header settings.

currently, there are only follow methods for header setting:
esp_err_t esp_http_client_delete_header(esp_http_client_handle_t client, const char *key);
esp_err_t esp_http_client_get_header(esp_http_client_handle_t client, const char *key, char **value);
esp_err_t esp_http_client_delete_header(esp_http_client_handle_t client, const char *key);

i would suggest to add an additional api for header:
esp_err_t esp_http_client_cleanup_header(esp_http_client_handle_t client);

thanks

**Comment by shubhamkulkarni97** [comment]
@w19787 Can you share your test-code or use-case which would fail if the suggested api is not implemented?

**Comment by Alvin1Zhang** [comment]
@w19787 Thanks for reporting, would you please help if any updates for this issue? Thanks.

**Comment by Alvin1Zhang** [comment]
@w19787 Thanks for reporting. Will close the ticket due to short of feedback. Feel free to reopen with more details. Thanks.
