### ISSUE TITLE
ESP-NOW and FCC test ?  (IDFGH-1984)

### ISSUE THREAD

**Issue by quangvankts** [espressif/esp-idf#4179]
I intent to do FCC EMC test (the cheap one) for a product contains two FCC certificated ESP8266/ESP32 modules, communicate with each other over ESP-NOW. 
Does using ESP-NOW break the modular certification as it is developed quite recently ?
Thanks

**Comment by negativekelvin** [comment]
No because it still uses 802.11 phy

**Comment by Alvin1Zhang** [comment]
@negativekelvin Thanks for the notes. @quangvankts Thanks for reporting, feel free to reopen if you still have the issue. Thanks.
