### ISSUE TITLE
Can´t compile esp32-webserver (IDFGH-1997)

### ISSUE THREAD

**Issue by yoandresmza** [espressif/esp-idf#4193]
Hi,  I am trying to change the Wi-Fi mode of the FZ2707 (4 realys) module to connect it to my home Wi-Fi. I'm using W10.
I cloned the esp32-webserver and esp-idf repositories from github and installed the ESP tools but I can't build the project! Other projects like "hello_world" are well built.
When I try to build the project I have this error:

![image](https://user-images.githubusercontent.com/55092133/66706111-6f556e80-ed05-11e9-8efd-2120d3e8e1c7.png)

What am I doing wrong? Im new to this, any help would be important to me.
Thank you!

Andres

**Comment by negativekelvin** [comment]
Which esp32-webserver project?

**Comment by yoandresmza** [comment]
This one...
https://github.com/cyoung/esp32-webserver
Is a firmware for a 4 realy (module  FZ2707 from DIYMALL) based on esp-idf frameword

**Comment by negativekelvin** [comment]
That project does not support cmake (idf.py), only make.  And it probably has only been tested on older versions of esp-idf maybe ≤3.2.  If you are asking for help with third party projects please open your issue on their GitHub repo or go to the esp32.com forum.

**Comment by Alvin1Zhang** [comment]
@negativekelvin Thanks for the notes. @yoandresmza Thanks for reporting, for third party issues, please help create a post on our forum at esp32.com. Thanks.
