### ISSUE TITLE
ESP_ERR_FLASH_BASE' undeclared  (IDFGH-2010)

### ISSUE THREAD

**Issue by Somusundram** [espressif/esp-idf#4205]
Dear all,

I have a issue when i 'make flash' for ESP32:

`Esp/esp-idf/components/spi_flash/include/esp_spi_flash.h:28:35: error: 'ESP_ERR_FLASH_BASE' undeclared (first use in this function); did you mean 'ESP_ERR_MESH_BASE'?
 **#define ESP_ERR_FLASH_OP_FAIL    (ESP_ERR_FLASH_BASE + 1)**
`
I can compile the source with idf.py build or idf.py app flash but when i try to 'Make' , it pops up the error like above.

Do let me know if you need more info.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting the issue. Would you please help provide more details as suggested in the [issue template](https://github.com/espressif/esp-idf/blob/master/docs/issue_template.md)? Information like elf, sdk configuration, backtrace, log outputs, commit ID, hardware and etc. would help us debug further. Thanks.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, feel free to reopen with more details. Thanks.
