### ISSUE TITLE
[BLE Mesh] esp_ble_mesh_provisioner_delete_dev does not reset device (IDFGH-2033)

### ISSUE THREAD

**Issue by Piill** [espressif/esp-idf#4222]
## Environment

- Development Kit:    ESP32-DevKitC v4
- IDF version: V4.0-beta1
- Build System: CMake
- Operating System:  Linux
- Power Supply: USB

## Problem Description

After having provisioned and configured a node, `esp_ble_mesh_provisioner_delete_dev` is called using the device UUID. I expect the device to be reset, and no longer part of the network. 

Instead, nothing happens. The device keeps functioning as usual.

**Comment by Campou** [comment]
Hi @Piill 

Currently we recommend to send `Config Node Reset` message to reset a node, and for the API `esp_ble_mesh_provisioner_delete_dev`, we will add the reset funtionality into it.

Thanks.

**Comment by Piill** [comment]
I never noticed that there was a node reset as part of the configuration client. I will use that instead.

Thank you.

**Comment by Campou** [comment]
Hi @Piill 

Yes, you can send the configuration message with the opcode set to `ESP_BLE_MESH_MODEL_OP_NODE_RESET`. Besides the opcode, no other parameters will be needed.

Thanks.

**Comment by Piill** [comment]
Hey @Campou 
i have a quick followup question.
When resetting a node, it never returns the "Config Node Reset Status".
Am i suppose to send that manually before resetting the node?

**Comment by Campou** [comment]
Hi @Piill 

For resetting the node, there is no need to send the corresponding status message manually.
Thanks for the feedback, we are looking into this issue.

Thanks.

**Comment by Campou** [comment]
Hi @Piill 

We have found the root cause of this issue, will resolve it ASAP.

Thanks.

**Comment by Campou** [comment]
Hi @Piill 

In the latest idf, you can send Config Node Reset message without the need to set parameters (since no parameter is included in the message), please have a try.

Thanks.

**Comment by Alvin1Zhang** [comment]
@Piill Thanks for reporting, sorry for slow turnaround. Feel free to reopen if the issue still happens. Thanks.
