### ISSUE TITLE
System crash on mdns TXT query (IDFGH-2035)

### ISSUE THREAD

**Issue by eespi** [espressif/esp-idf#4224]
## Environment
- IDF version:  v3.3-71-g46b12a5
- Build System:         Make
- Compiler version:  1.22.0-80-g6c4433a
- Operating System:    Linux
- Power Supply:         USB

## Problem Description

System crashes on reception on mdns TXT query, by accessing a NULL pointer to a struct. 
Fuction _mdns_append_txt_record assignes str[1] = service->service; but service is NULL.

### Expected Behavior
Device should not crash
### Actual Behavior
System reset
### Steps to repropduce

1. Configure, compile and run mdns example found at examples/protocols/mdns
2. Download Service Browser app for Android [https://play.google.com/store/apps/details?id=com.druk.servicebrowser](url)
3. Scan network for _http._tcp service and tap
4. Tap World Wide Web HTTP
5. Tap on ESP32-WebServer
6. System crash on ESP32

## Debug Logs

```
RX[0][0]: From: 192.168.1.100:5353, To: 224.0.0.251, Packet[222790]: 
    Q: esp32-mdns-EF4A18...local. TXT IN

Guru Meditation Error: Core  0 panic'ed (LoadProhibited). Exception was unhandled.
Core 0 register dump:
PC      : 0x400d63eb  PS      : 0x00060a30  A0      : 0x800d6c24  A1      : 0x3ffbe800  
0x400d63eb: _mdns_append_txt_record at /media/paolo/Data/working/FW/esp32/esp-idf/components/mdns/mdns.c:4712

A2      : 0x3ffb3edc  A3      : 0x3ffbe8a0  A4      : 0x00000000  A5      : 0x00000001  
A6      : 0x00000000  A7      : 0xff000000  A8      : 0x800d63e8  A9      : 0x3ffbe7e0  
A10     : 0x3ffbec50  A11     : 0x00000004  A12     : 0x3ffbe7b4  A13     : 0x3ffae918  
A14     : 0x00000000  A15     : 0x00000000  SAR     : 0x00000004  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x00000004  LBEG    : 0x400014fd  LEND    : 0x4000150d  LCOUNT  : 0xffffffff  

ELF file SHA256: ada1b418cc11f7ee102bb8b5e85d6cfe241b921b956058a6e0d412c1a6b6fa05

Backtrace: 0x400d63eb:0x3ffbe800 0x400d6c21:0x3ffbe850 0x400d7f30:0x3ffbe890 0x400d845d:0x3ffbe8e0 0x400d9528:0x3ffbe910 0x400d98df:0x3ffbe9d0 0x400d9936:0x3ffbea10 0x4008c2e1:0x3ffbea40
0x400d63eb: _mdns_append_txt_record at /media/paolo/Data/working/FW/esp32/esp-idf/components/mdns/mdns.c
```

**Comment by ESP-Marius** [comment]
Thank you for reporting the issue. This has been fixed in our internal master branch now.
