### ISSUE TITLE
Support for Service Class UUID (128-bit) for SPP in SDP (IDFGH-2037)

### ISSUE THREAD

**Issue by piotrkundu** [espressif/esp-idf#4226]
## Environment

- Development Kit:      Adafruit HUZZAH32 - ESP32 Feather
- Module or chip used:  ESP32-WROOM-32
- IDF version : v4.0-dev-1443-g39f090a4f
- Build System:         Make
- Compiler version: (crosstool-NG esp32-2019r1) 8.2.0
- Operating System:     macOS
- Power Supply:         USB

## Problem Description
Currently there is no way to create a SPP Master with a custom 128-bit UUID, instead a Base UUID (16-bit) is always used: 
```
    uint16_t service = UUID_SERVCLASS_SERIAL_PORT;
```
See https://github.com/espressif/esp-idf/blob/master/components/bt/host/bluedroid/bta/jv/bta_jv_act.c#L1032
   
Also SDP_AddServiceClassIdList called from the above `add_spp_sdp()` only support Base UUID (16-bit). If I got it right `BTA_JvCreateRecordByUser` is called from `btc_spp_dm_inter_cb` in `BTA_JV_GET_SCN_EVT`. It sends a `tBTA_JV_API_CREATE_RECORD` message which ends up in 
`bta_jv_create_record` calling `add_spp_sdp`.

## Callstack and Links
**SDP_AddServiceClassIdList**
https://github.com/espressif/esp-idf/blob/master/components/bt/host/bluedroid/stack/sdp/sdp_db.c#L809

**add_spp_sdp()**
https://github.com/espressif/esp-idf/blob/master/components/bt/host/bluedroid/bta/jv/bta_jv_act.c#L1013

**bta_jv_create_record**
https://github.com/espressif/esp-idf/blob/master/components/bt/host/bluedroid/bta/jv/bta_jv_act.c#L1057

**BTA_JvCreateRecordByUser**
https://github.com/espressif/esp-idf/blob/master/components/bt/host/bluedroid/bta/jv/bta_jv_api.c#L287

**BTA_JV_GET_SCN_EVT** in **btc_spp_dm_inter_cb**
https://github.com/espressif/esp-idf/blob/master/components/bt/host/bluedroid/btc/profile/std/spp/btc_spp.c#L284

**#define UUID_SERVCLASS_SERIAL_PORT**
https://github.com/espressif/esp-idf/blob/master/components/bt/host/bluedroid/stack/include/stack/sdpdefs.h#L186

### Expected Behavior
The API stack supports Service Class 128-bit SDP records for SPP.

### Inspiration
https://github.com/bluekitchen/btstack/blob/master/src/classic/spp_server.c#L72

**Comment by Wth-Esp** [comment]
Hi @piotrkundu 

We won't support customized UUID for SPP in the predicted future.

Thanks
Weitianhua
