### ISSUE TITLE
is it possible to create the SSL certificate on ESP32 itself. (IDFGH-2069)

### ISSUE THREAD

**Issue by PranavD10** [espressif/esp-idf#4246]
Hey,
My question is whether it is possible to create the SSL certificate on the ESP32 device during run time using the openssl and wolfssl libraries...??
Thank you,

**Comment by negativekelvin** [comment]
Questions should be posted on the forum at esp32.com

https://github.com/warmcat/libwebsockets/blob/db7e0bef3976ebe510e1f680bd985e47077ceb96/lib/plat/freertos/esp32/esp32-helpers.c#L1131-L1253
