### ISSUE TITLE
No rule to make target 'menuconfig'. Stop. (IDFGH-2076)

### ISSUE THREAD

**Issue by amirjak** [espressif/esp-idf#4250]
**I** download and extract the repository to the **components** folder of **my** ESP-IDF project.
But when I want to **make menuconfig** this happened.
![Annotation 2019-10-25 204656](https://user-images.githubusercontent.com/46311349/67624378-ab77eb80-f83c-11e9-9d66-377d5d2bdb63.png)

**I** use **python 2.7 8** ( windows 10 ) 64 bit

**Comment by dobairoland** [comment]
Hi @amirjak. You are not supposed to run `make` in the components directory. Please create your own project (based on the template or an example application) and set the `IDF_PATH` to your `~/esp-idf`.
`make` should be run in your project folder.

**Comment by amirjak** [comment]
**Thank you very much**
