### ISSUE TITLE
ledcWriteTone (channel, freq);  steals the freedom of memory. (IDFGH-2079)

### ISSUE THREAD

**Issue by ALEX170457** [espressif/esp-idf#4252]
When calling ledcWriteTone (channel, freq)  Memory leaks.
 28 bytes per call.

**Comment by Alvin1Zhang** [comment]
@ALEX170457 Thanks for reporting the issue. Would you please help provide more details as suggested in the [issue template](https://github.com/espressif/esp-idf/blob/master/docs/issue_template.md)? Information like elf, sdk configuration, backtrace, log outputs, commit ID, hardware and etc. would help us debug further. Thanks.

**Comment by Alvin1Zhang** [comment]
@ALEX170457 Thanks for reporting. Will close the ticket due to short of details. Feel free to reopen with more details provided. Thanks.
