### ISSUE TITLE
IP事件回调IP_EVENT_AP_STAIPASSIGNED (IDFGH-2080)

### ISSUE THREAD

**Issue by fzboffice** [espressif/esp-idf#4253]
如果一瞬间很多个sta加入esp32创建的ap，那么IP事件回调IP_EVENT_AP_STAIPASSIGNED似乎缺乏一个标志(例如mac)来唯一确定ip和mac的对应。

**Comment by Alvin1Zhang** [comment]
@fzboffice Thanks for reporting the issue. Would you please help provide more details as suggested in the [issue template](https://github.com/espressif/esp-idf/blob/master/docs/issue_template.md)? Information like elf, sdk configuration, backtrace, log outputs, commit ID, hardware and etc. would help us debug further. Thanks.

**Comment by liuzfesp** [comment]
HI @fzboffice do you mean it's helpful to contain the IP and mac address of STA when report this event?
