### ISSUE TITLE
当我#include <regex.h> 并使用正则表达式时，编译器报错 (IDFGH-2090)

### ISSUE THREAD

**Issue by fzboffice** [espressif/esp-idf#4257]
当我#include <regex.h> 并使用正则表达式时，编译器报错
/esp/xtensa-esp32-elf/xtensa-esp32-elf/sys-include/regex.h:43:9: error: unknown type name 'off_t'  typedef off_t regoff_t;
请问该如何解决

**Comment by antmak** [comment]
A new **esp-2019r2** toolchain will be released soon. The `regex.h` support is introduced there.
