### ISSUE TITLE
ESP32 stall when deep sleep mode and remove the battery (IDFGH-2104)

### ISSUE THREAD

**Issue by welinkio** [espressif/esp-idf#4267]
ESP32 -WROVER without PMU chip.
1. Enter deep sleep mode. 10uA sleep current
2. Remove battery (3 AA and using DC2DC to 3.3V)
3. Capcatity will have some power and reduce from 3.3V VDD to 0  slowly.
4. After 5~10 second insert battery again
5. Wakeup CPU and IO will fail.
6. Remove battery and wait for 60 second utill VDD to 0V and then insert battery will reboot again.

Is this a chip bug?

**Comment by Alvin1Zhang** [comment]
@welinkio Thanks for reporting the issue. Would you please help provide more details as suggested in the [issue template](https://github.com/espressif/esp-idf/blob/master/docs/issue_template.md)? Information like elf, sdk configuration, backtrace, log outputs, commit ID, hardware and etc. would help us debug further. Thanks.

**Comment by negativekelvin** [comment]
https://esp32.com/viewtopic.php?t=3769

**Comment by Alvin1Zhang** [comment]
@welinkio Thanks for reporting, would you please help check two things and help provide the feedback: 1. check the voltage of VDD after 5 ~ 10s; 2. check the voltage of CHIP_PU in 60s after removing battery. Thanks.

**Comment by Alvin1Zhang** [comment]
@welinkio Thanks for reporting, would you please help share any feedback suggested in my last comment? Many thanks.

**Comment by Alvin1Zhang** [comment]
@welinkio Thanks for reporting, would you please help share any feedback suggested in last comment? Many thanks.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to short of feedback, feel free to reopen with more updates. Thanks.
