### ISSUE TITLE
modbus master on IDF V3.3 (IDFGH-2136)

### ISSUE THREAD

**Issue by Pratikm78** [espressif/esp-idf#4294]
I am using v3.3 stable release of the esp-idf however the modbus component only supports slave in that version of the idf. I want to programming using the modbus master component which is part of the newer versions of the idf. 

I have to use v3.3 because a sdk that I am using is only supported by the v3.3 and "make" build not the idf.py found in the newer versions. 

I have copied the modbus component from the v4.0 to v3.3 however i can not build the code

**Comment by alisitsyn** [comment]
Hi Pratikm78,
The v4.0 contains significant changes compare to v.3.3. Did you copy the whole freemodbus folder from v4.0 into your_project/components/freemodbus? The v4.0 example can be compiled with make, but there can be conflicts with changes in some other components. Could you provide the compilation logs? I would recommend you to use latest revision of ESP_IDF.

**Comment by Alvin1Zhang** [comment]
@Pratikm78 Thanks for reporting. Would you please help share if any updates for the issue? Could you help provide the compilation logs? Thanks.

**Comment by Alvin1Zhang** [comment]
@Pratikm78 Thanks for reporting, will close due to short of feedback, feel free to reopen with more details. Thanks.
