### ISSUE TITLE
ESP32 ETHERNET PHY Reset Timeout, init mac failed Error (IDFGH-2141)

### ISSUE THREAD

**Issue by aiden-kim-j** [espressif/esp-idf#4298]
Hello.
I have made a PCB based on the circuit diagram shown in ESP32-ETHERNET-KIT V1.0 developed by your company and I am in the middle of TEST. But there's a problem working on it.
![image](https://user-images.githubusercontent.com/57346835/68385272-bfa4dc80-019c-11ea-8ac3-6df83b92a5e0.png)

I think the problem is that the ESP32-WROVER-B product does not come with the GPIO0 signal, the 50Mhz frequency.
I've tried TEST with 25Mhz CRYSTAL on the outside, but so is this. Can you help me?

Information
- Firmware : Ethernet-Example-basic
- Tool : Mingw32
- PHY : IP101GRI
- Schematic : ESP32-ETHERNET-KIT V1.0

**Comment by suda-morris** [comment]
If you have referenced our official board design, obviously, your GPIO0 didn't get the RMII clock(50MHz) from outside. So the mac can't be initialized successfully.

**Comment by Alvin1Zhang** [comment]
@aiden-kim-j Thanks for reporting.
