### ISSUE TITLE
Support Zephyr

### ISSUE THREAD

**Issue by nvl1109** [espressif/esp-idf#43]
Hi,

Zephyr is very interested, have any plan to porting Zephyr to ESP32?

**Comment by nkolban** [comment]
Comment: You might find that posting this as a question on the ESP32.com community forum might be a better mechanism.  The ESP-IDF issues tracking in Github is (I believe) primarily for defect tracking.

http://esp32.com/

**Comment by nvl1109** [comment]
@nkolban You are right. I'm sorry about this. I will close the issue & create a thread in the ESP32's forum.
