### ISSUE TITLE
[Doc] Is there any CHANGELOG.rst or Migrating Guide? (IDFGH-2147)

### ISSUE THREAD

**Issue by keelung-yang** [espressif/esp-idf#4302]
I'm migrating our project from 3.x to 4.x, but there is no document about it, at least it's not easyly found as in most projects on GitHub.

**Comment by Alvin1Zhang** [comment]
@keelung-yang Thanks for reporting, would you please help take a look at the [release notes](https://github.com/espressif/esp-idf/releases)? Thanks.

**Comment by keelung-yang** [comment]
> @keelung-yang Thanks for reporting, would you please help take a look at the [release notes](https://github.com/espressif/esp-idf/releases)? Thanks.

@Alvin1Zhang I checked, it helps although far away from a migrating guide. But I almost finished my migrating work. Thanks!

**Comment by Alvin1Zhang** [comment]
Thanks for the reporting and feedback, could this ticket be closed? Thanks.

**Comment by chegewara** [comment]
https://docs.espressif.com/projects/esp-idf/en/stable/api-guides/build-system-cmake.html#migrating-from-esp-idf-gnu-make-system

**Comment by keelung-yang** [comment]
> https://docs.espressif.com/projects/esp-idf/en/stable/api-guides/build-system-cmake.html#migrating-from-esp-idf-gnu-make-system

Thanks for your url. It did help. Seems migrating guides are seperated by topics.
