### ISSUE TITLE
idf.py menuconfig always ask confirm saving even no changing (IDFGH-2148)

### ISSUE THREAD

**Issue by keelung-yang** [espressif/esp-idf#4303]
I just type idf.py menuconfig and then exit without any changes, but is still ask confirm saving.
This behavior is not same as in 3.x or most other project using menuconfig

**Comment by Alvin1Zhang** [comment]
@keelung-yang Thanks for reporting.

**Comment by keelung-yang** [comment]
This issue existed in new menuconfig mconf-v4.6.0.0-idf-20190628-win32
