### ISSUE TITLE
Messy characters in idf.py menuconfig on Windows 10 in English (IDFGH-2149)

### ISSUE THREAD

**Issue by keelung-yang** [espressif/esp-idf#4304]
On master branch.

![image](https://user-images.githubusercontent.com/20385450/68467323-f3413e80-0250-11ea-99d3-a935388be280.png)

![image](https://user-images.githubusercontent.com/20385450/68467249-d1e05280-0250-11ea-9306-e7b567d6b9e6.png)

**Comment by dobairoland** [comment]
The next push to Github will replace the old c-based menuconfig with a Python-based one. So these issues will go away.
