### ISSUE TITLE
mdns advertising only supports WebSite (_http)

### ISSUE THREAD

**Issue by johsely1234** [espressif/esp-idf#431]
Mdns advertising seems to only support the _http service. 

Code in example:
ESP_ERROR_CHECK( mdns_service_add(mdns, "_arduino", "_tcp", 3232) );
ESP_ERROR_CHECK( mdns_service_txt_set(mdns, "_arduino", "_tcp", 4, arduTxtData) );
ESP_ERROR_CHECK( mdns_service_add(mdns, "_http", "_tcp", 80) );
ESP_ERROR_CHECK( mdns_service_instance_set(mdns, "_http", "_tcp", "ESP32 WebServer") );
ESP_ERROR_CHECK( mdns_service_add(mdns, "_smb", "_tcp", 445) );

This should mean we get more then one service shown? I tried with avahi on linux:
=   wlo1 IPv4 ESP32 WebServer                               Web Site             local
   hostname = [esp32-mdns.local]
   address = [192.168.43.19]
   port = [80]
   txt = []

only the WebSite ("_http") is shown. I tried to set something different then "_http" but it was not shown.

**Comment by igrr** [comment]
@johsely1234 PR #340 made by @negativekelvin has been merged into master, so avahi should now be able to discover all services.
