### ISSUE TITLE
hello_world example has Windows prohibited directory name (IDFGH-2157)

### ISSUE THREAD

**Issue by DROBNJAK** [espressif/esp-idf#4312]
I installed esp-idf and for some reason I had to remove it. But Windows 7 refused to remove the hello_world directory. After some digging around eventually it was found that there was a sub directory named 'con' which is a reserved/prohibited directory name in Windows environment. 

Can you possibly use different directory name?

**Comment by chegewara** [comment]
https://github.com/espressif/esp-idf/issues/3299

**Comment by projectgus** [comment]
Hi @DROBNJAK ,

Which ESP-IDF version are you using? If it is v3.3 (the current stable release) then this bug will be fixed in v3.3.1, as mentioned in the linked issue.

Angus

**Comment by DROBNJAK** [comment]
That problem happened with v3.3. Since than I replaced it with the latest ESP-IDF version, I don't know which one it is, but it is higher than v3.3. Problem doesn't affect IDF, it only makes hard deleting that directory when you want to re-install everything.

**Comment by projectgus** [comment]
Hi @DROBNJAK ,

Sorry for the delayed reply.

If your first install was v3.3 then it's a known issue that this directory was created and caused this problem with deletion. Sorry for the hassle. As stated above, a fix has been merged and will be in the v3.3.1 release.

Are you still seeing the problem of a "con" directory being created from a newer ESP-IDF install?

Angus

**Comment by DROBNJAK** [comment]
Yeah, I upgraded to a newest version and I guess it's fixed now.
