### ISSUE TITLE
WEBSOCKET_CLIENT: Network error: esp_transport_write() returned 0, errno=0 (IDFGH-2161)

### ISSUE THREAD

**Issue by huazhenjiang** [espressif/esp-idf#4316]
###Environment
Development Kit: ESP32-DevKitC
Kit version (for WroverKit/PicoKit/DevKitC): v2
Module or chip used: ESP32-WROOM-32
IDF version (run git describe --tags to find it): v4.0-master
Operating System: Windows 10
Power Supply: USB

###Problem Description
I clone the lastest esp-idf and patch this
(https://github.com/igrr/esp-idf/commit/7c5011f411b7662feb50fd1e53114bec390d8c2e).

First, I receive a fixed data from UART every 50ms (the packet size is about 2KB ) .
Then put them into a message queue to pass to websocket_client task for the following uploading. But the websocket client is wired when sending data that it can not transfer completed. It shows the 'WEBSOCKET_CLIENT: Network error: esp_transport_write() returned 0, errno=0' frequently.

###Here is the log:
--OK part--
[data 1]tv_now.tv_sec:1573437177,tv_now.tv_usec:803656
[send_start]tv_now.tv_sec:1573437177,tv_now.tv_usec:806688
[send_done]tv_now.tv_sec:1573437177,tv_now.tv_usec:820976

--wired part--
[data 2]tv_now.tv_sec:1573437177,tv_now.tv_usec:854165
[send_start]tv_now.tv_sec:1573437177,tv_now.tv_usec:857829
E (18938) TRANSPORT_WS: Error transport_poll_write
E (18939) WEBSOCKET_CLIENT: Network error: esp_transport_write() returned 0, errno=0
[send_done]tv_now.tv_sec:1573437177,tv_now.tv_usec:876368

[data 3]tv_now.tv_sec:1573437177,tv_now.tv_usec:907445
[send_start]tv_now.tv_sec:1573437177,tv_now.tv_usec:917650
E (18993) TRANSPORT_WS: Error transport_poll_write
E (18997) WEBSOCKET_CLIENT: Network error: esp_transport_write() returned 0, errno=0
[send_done]tv_now.tv_sec:1573437177,tv_now.tv_usec:936186

[data 4]tv_now.tv_sec:1573437177,tv_now.tv_usec:967278
[send_start]tv_now.tv_sec:1573437177,tv_now.tv_usec:977537
E (19053) TRANSPORT_WS: Error transport_poll_write
E (19062) WEBSOCKET_CLIENT: Network error: esp_transport_write() returned 0, errno=0

###Additional Description
The tv_now is system time that provide more detail for debugging.
At OK part, we can see that it costs about 15ms (820976-806688), but it can not work at the wired part. All the above data are the same, but the result is different.
 
After the above case, I decrease the size (about 128 bytes)  which sending through websocket api and the 'WEBSOCKET_CLIENT: Network error: esp_transport_write() returned 0, errno=0' is disappeared.
I do not know what happened. It looks like 'exist upper limit of sending bytes'. 
Any tips for this issue?

**Comment by david-cermak** [comment]
Hi @huazhenjiang 

Thanks for reporting this issue. This is a bug in websocket_client/tcp_transport failing to  correctly process infinite timeouts. Will be fixed soon.

As a workaround, I might suggest using some big number instead of `portMAX_DELAY`.
```
esp_websocket_client_send(client, LONG_STRING, strlen(LONG_STRING), 10000);
```
