### ISSUE TITLE
测试ble mesh代码版本？ (IDFGH-2167)

### ISSUE THREAD

**Issue by Tflgit** [espressif/esp-idf#4321]
你好：

我现在测试ble mesh功能，请问需要使用哪个分支？
我现在有一块ESP32-LyraT V4.3开发板。

**Comment by Campou** [comment]
Hi @Tflgit 

麻烦使用 [release/v4.0](https://github.com/espressif/esp-idf/tree/release/v4.0) 分支进行测试.

谢谢

**Comment by Alvin1Zhang** [comment]
@Tflgit Thanks for reporting, for "how" questions, please help submit a post on our forum at https://esp32.com, thanks.
