### ISSUE TITLE
Not able to read the binary from amazon s3 bucket  (IDFGH-2169)

### ISSUE THREAD

**Issue by ppvastkar** [espressif/esp-idf#4323]
When I am using a simple OTA example code, I am not able to read binary from the server. below is my log.
Does anyone have an idea on how to resolve this issue, and whats going on..?

Device Log:
<DBG><../main/ota_handler.c><85>< http_ota_envet_handler>HTTP_EVENT_ON_HEADER, key=x-amz-id-2, value=1mWt/DtJ55j2t0TBqY9UMwZmWDVYC8YT28kd2GEHr8usz2EU7KuQkvYKR27c61TLuv/wlL3jsmk=
<DBG><../main/ota_handler.c><85>< http_ota_envet_handler>HTTP_EVENT_ON_HEADER, key=x-amz-request-id, value=16394AAE8B6572ED
<DBG><../main/ota_handler.c><85>< http_ota_envet_handler>HTTP_EVENT_ON_HEADER, key=Date, value=Mon, 11 Nov 2019 14:35:45 GMT
<DBG><../main/ota_handler.c><85>< http_ota_envet_handler>HTTP_EVENT_ON_HEADER, key=Last-Modified, value=Mon, 11 Nov 2019 10:11:09 GMT
<DBG><../main/ota_handler.c><85>< http_ota_envet_handler>HTTP_EVENT_ON_HEADER, key=ETag, value="1a6a35824a5050cdd8cc97be24419c97"
<DBG><../main/ota_handler.c><85>< http_ota_envet_handler>HTTP_EVENT_ON_HEADER, key=Accept-Ranges, value=bytes
<DBG><../main/ota_handler.c><85>< http_ota_envet_handler>HTTP_EVENT_ON_HEADER, key=Content-Type, value=application/octet-stream
<DBG><../main/ota_handler.c><85>< http_ota_envet_handler>HTTP_EVENT_ON_HEADER, key=Content-Length, value=1306624
<DBG><../main/ota_handler.c><85>< http_ota_envet_handler>HTTP_EVENT_ON_HEADER, key=Server, value=AmazonS3
<DBG><../main/ota_handler.c><148><cta_https_ota>content length: 1306624
<INFO><../main/ota_handler.c><153><cta_https_ota>Starting OTA...
<INFO><../main/ota_handler.c><164><cta_https_ota>Writing to partition subtype 16 at offset 0x310000
<INFO><../main/ota_handler.c><173><cta_https_ota>esp_ota_begin succeeded
<INFO><../main/ota_handler.c><175><cta_https_ota>Please Wait. This may take time
I (50092) mbedtls: ssl_tls.c:8207 => read

I (50092) mbedtls: ssl_tls.c:4305 => read record

I (50102) mbedtls: ssl_tls.c:2532 => fetch input

I (50102) mbedtls: ssl_tls.c:2693 in_left: 0, nb_want: 5

I (50112) mbedtls: ssl_tls.c:2717 in_left: 0, nb_want: 5

I (50112) mbedtls: ssl_tls.c:2718 ssl->f_recv(_timeout)() returned 5 (-0xfffffffb)

I (50122) mbedtls: ssl_tls.c:2738 <= fetch input

W (50132) mbedtls: ssl_tls.c:4088 bad message length

W (50132) mbedtls: ssl_tls.c:4338 ssl_get_next_record() returned -29184 (-0x7200)

W (50142) mbedtls: ssl_tls.c:8272 mbedtls_ssl_read_record() returned -29184 (-0x7200)

E (50152) esp-tls: read error :-29184:
E (50162) TRANS_SSL: esp_tls_conn_read error, errno=Success
<INFO><../main/ota_handler.c><190><cta_https_ota>Connection closed,all data received
<DBG><../main/ota_handler.c><94>< http_ota_envet_handler>HTTP_EVENT_DISCONNECTED
<DBG><../main/ota_handler.c><94>< http_ota_envet_handler>HTTP_EVENT_DISCONNECTED
<DBG><../main/ota_handler.c><211><cta_https_ota>Total binary data length writen: 0
<ERR><../main/ota_handler.c><219><cta_https_ota>Error: esp_ota_end failed! err=0x258. Image is invalid
<ERR><../main/ota_handler.c><301><OTA_Task>Firmware Upgrades Failed

My Code:
-----------
void OTA_Task( void* pvParameters )
{
	uint32_t NotificationVal = 0;

	while( TRUE) {

		NotificationVal = ulTaskNotifyTake( pdTRUE, ( TickType_t ) 1000 );

		if( NotificationVal > 0 ) {

			DBG_PRINT("Starting OTA...");

			DBG_PRINT("Binary URL: %s",g_ota_url);

			DBG_PRINT("Free Heap Size: %d bytes",xPortGetFreeHeapSize());

			/* Wait for the callback to set the CONNECTED_BIT in the event group. */
			xEventGroupWaitBits(wifi_event_group, CONNECTED_BIT, false, true, portMAX_DELAY);

			DBG_PRINT("Connect to Wifi ! Start to Connect to Server....");

			esp_http_client_config_t config = {

				.url = g_ota_url, //https://otabinfile.s3.ap-south-1.amazonaws.com/xxxx.bin

		        .event_handler = cta_http_ota_event_handler

		    };

			esp_err_t ret = my_https_ota(&config);

			if (ret == ESP_OK) {

				esp_restart();

			} else {

				ERR_PRINT("Firmware Upgrades Failed");

				DBG_PRINT("Free Heap Size: %d bytes",xPortGetFreeHeapSize());

			}

		}//NotificationVal

	}//While
}

esp_err_t my_https_ota(const esp_http_client_config_t *config)
{
    if (!config) {
        ERR_PRINT("esp_http_client config not found");
        return ESP_ERR_INVALID_ARG;
    }

    esp_http_client_handle_t client = esp_http_client_init(config);
    if (client == NULL) {
        ERR_PRINT("Failed to initialize HTTP connection");
        return ESP_FAIL;
    }

    esp_err_t err = esp_http_client_open(client, 0);
    if (err != ESP_OK) {
        esp_http_client_cleanup(client);
        ERR_PRINT("Failed to open HTTP connection: %s", esp_err_to_name(err));
        return err;
    }

    int content_length =  esp_http_client_fetch_headers(client);

    DBG_PRINT("content length: %d",content_length);

    esp_ota_handle_t update_handle = 0;

    const esp_partition_t *update_partition = NULL;
    INFO_PRINT("Starting OTA...");

    update_partition = esp_ota_get_next_update_partition(NULL);

    if (update_partition == NULL) {
        ERR_PRINT("Passive OTA partition not found");
        cta_http_cleanup(client);
        return ESP_FAIL;
    }

    INFO_PRINT("Writing to partition subtype %d at offset 0x%x",
             update_partition->subtype, update_partition->address);

    err = esp_ota_begin(update_partition, OTA_SIZE_UNKNOWN, &update_handle);
    if (err != ESP_OK) {
        ERR_PRINT("esp_ota_begin failed, error=%d", err);
        cta_http_cleanup(client);
        return err;
    }

    INFO_PRINT("esp_ota_begin succeeded");

    INFO_PRINT("Please Wait. This may take time");

    esp_err_t ota_write_err = ESP_OK;

    char upgrade_data_buf[OTA_BUF_SIZE+1];

    int binary_file_len = 0;

    while (1) {

    	memset(upgrade_data_buf, 0x0, sizeof(upgrade_data_buf));

        int data_read = esp_http_client_read(client, upgrade_data_buf, OTA_BUF_SIZE);

        if (data_read == 0) {
            INFO_PRINT("Connection closed,all data received");
            break;
        }

        if (data_read < 0) {
            ERR_PRINT("Error: data read error");
            break;
        }

        if (data_read > 0) {
            ota_write_err = esp_ota_write( update_handle, (const void *)upgrade_data_buf, data_read);
            if (ota_write_err != ESP_OK) {
                break;
            }
            binary_file_len += data_read;
            DBG_PRINT("Written image length %d", binary_file_len);
        }
    }

    http_cleanup(client);

    DBG_PRINT("Total binary data length writen: %d", binary_file_len);

    esp_err_t ota_end_err = esp_ota_end(update_handle);

    if (ota_write_err != ESP_OK) {
        ERR_PRINT("Error: esp_ota_write failed! err=0x%d", err);
        return ota_write_err;
    } else if (ota_end_err != ESP_OK) {
        ERR_PRINT("Error: esp_ota_end failed! err=0x%d. Image is invalid", ota_end_err);
        return ota_end_err;
    }

    err = esp_ota_set_boot_partition(update_partition);
    if (err != ESP_OK) {
        ERR_PRINT("esp_ota_set_boot_partition failed! err=0x%d", err);
        return err;
    }
    INFO_PRINT("esp_ota_set_boot_partition succeeded");

    return ESP_OK;
}

**Comment by ppvastkar** [comment]
By change in menuconfig this issue goes away.

**Comment by lakshmisivareddy** [comment]
HI 
also facing the same issue 
can you please let us know what is the change in menuconfig

**Comment by ppvastkar** [comment]
In your Amazon S3 make sure you have assigned the public access to the file.
Also, make sure you have 2 different partitions in menuconfig. OTA_0 & OTA_1
