### ISSUE TITLE
[BLE Mesh] How should I test the friendship and low power node functions? (IDFGH-2176)

### ISSUE THREAD

**Issue by zhanlej** [espressif/esp-idf#4330]
I simply read your SDK code and think it should support the `friendship` and `low power` functions. But for these two functions I have the following problems:

- Because I don't know much about these two functions, so when I use `menuconfig` to configure these two functions, I don't understand many parameter settings.
- How should the friendship node be designed? Is it only necessary to enable the friendship function?
- How should the low power node be designed? Does the device need to be designed with low power or sleep mode? Does your ESP32 support the above model?

Can you provide new examples for the above mentioned issues and explain in detail?

In which branch is the latest version of the ble mesh code? Is it in the `master` branch or the `ble_mesh_release/esp-ble-mesh-v0.6.1` branch?

**Comment by Campou** [comment]
Hi @zhanlej 

Sorry for the late reply.

Currently for Friend node, it only needs to enable the Friend functionality, and when the Low Power node enters the network, it will try to find proper Friend node and establish a friendship.

For Low Power node, after the friendship is established, the BLE Scan functionality will be disabled currenlty, and it will be re-enabled after a certain delay. The Low Power node is useful when the device is a sensor or some other things which need low power consumption.

We will provide corresponding examples to illustrate how to use the friendship functionality later.

Thanks & Regards

**Comment by Campou** [comment]
Hi @zhanlej 

Sorry for the late reply.

Any updates about the testing progress?

Thanks.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to short of feedback, feel free to reopen with more details. Thanks.

**Comment by Thecave3** [comment]
Hi @Campou , 

> Currently for Friend node, it only needs to enable the Friend functionality, and when the Low Power node enters the network, it will try to find proper Friend node and establish a friendship.
>
> For Low Power node, after the friendship is established, the BLE Scan functionality will be disabled currenlty, and it will be re-enabled after a certain delay. The Low Power node is useful when the device is a sensor or some other things which need low power consumption.

Where this behaviour is described?
Is this behavior compliant with the standard? 
 
> We will provide corresponding examples to illustrate how to use the friendship functionality later.

Are these examples available to everyone? 
Is it possible to have them? 

Thanks & Regards

**Comment by Shane555** [comment]
Hi, are there any ways/examples to test friendship node and LPN? How would i know in a mesh if they are working as expected according to the bluetooth mesh specifications

**Comment by ZacDaMan** [comment]
Are there examples for this yet? I'm similarly stuck.

**Comment by Paramesh19** [comment]
@xiongweichao Hi Is there anyone who worked on LPN and friend node  Kindly provide the feedback on how to use those features...
Thank you in advance....
