### ISSUE TITLE
idf_tools.py error under Mac Catalina or ZSH (IDFGH-2178)

### ISSUE THREAD

**Issue by Francois-Belanger** [espressif/esp-idf#4332]
Hi under latest version, I had to change the line 252 of idf_tools.py to be able to install correctly.

    if filename.endswith('tar.gz') or filename.endswith('tar.gz '):

Don't know why, but file got an extra space at the end...  Doing this made it works.

v4.1-dev-815-ga45e99853
Mac 10.15.1

**Comment by dobairoland** [comment]
This is a duplicate of #4274, #4297, #4299 and #4314.

**Comment by Francois-Belanger** [comment]
ok thanks
