### ISSUE TITLE
How to free the RAM memory? (IDFGH-2181)

### ISSUE THREAD

**Issue by Kirankumar-xenlabs** [espressif/esp-idf#4335]
I want to free the  20kb RAM, how can do it? 

Thanks and Regards 
Kiran

**Comment by negativekelvin** [comment]
Be more specific

**Comment by Kirankumar-xenlabs** [comment]
Thank you for response, I am using esp32, in my project I am using wifi and ble. I am capturing the image and uploading it on google cloud,but It will not happening, for this it needs more RAM, for this task I want to free the some RAM.

**Comment by negativekelvin** [comment]
Please move this discussion to [esp32.com](http://esp32.com) forum

**Comment by Kirankumar-xenlabs** [comment]
I am getting following error,
E (271678) esp-tls: mbedtls_ssl_handshake returned -0x4d80
E (271678) esp-tls: Failed to open new connection
E (271678) TRANS_SSL: Failed to open a new connection
E (271678) HTTP_CLIENT: Connection failed, sock < 0

**Comment by Alvin1Zhang** [comment]
Thanks for reporting the issue. Would you please help provide more details as suggested in the [issue template](https://github.com/espressif/esp-idf/blob/master/docs/issue_template.md)? Information like elf, sdk configuration, backtrace, log outputs, commit ID, hardware and etc. would help us debug further. For "how" questions and third party issues, please help submit a post on our forum at https://esp32.com. Thanks.
