### ISSUE TITLE
Mqtt Ws Issue (IDFGH-2186)

### ISSUE THREAD

**Issue by nikolaskyr** [espressif/esp-idf#4338]
Hello,
I'm trying out an example in the ESP-idf for MQTT and I'm getting this:
![problem](https://user-images.githubusercontent.com/45922282/68840647-cdda8780-06cb-11ea-96e5-ebd459d3bf37.png)

I also get this in the terminal:
![term](https://user-images.githubusercontent.com/45922282/68840842-27db4d00-06cc-11ea-8039-aab0903a6d9e.png)

**Comment by david-cermak** [comment]
Hi @nikolaskyr 

Could you please share the version of your IDF and  debug logs from your board?
What I can see is that your mosqutto is configured for more listeners, and the ESP cannot upgrade HTTP header. Are you connecting to the correct listener?

**Comment by david-cermak** [comment]
@nikolaskyr Thanks for the update. Would you mind closing the issue if you can connect now?
