### ISSUE TITLE
Call i2c_master_cmd_begin after each command? (IDFGH-2188)

### ISSUE THREAD

**Issue by nagyation** [espressif/esp-idf#4340]
It seems that I can't call i2c_master_cmd_begin after each step, I must put the full scenario or data in the queue then call it once, but what I'm trying to do is send each command separately..

**Comment by nagyation** [comment]
Okay from #680 I set timeout using `i2c_set_timeout(i2c_master_port, 1048575);` because it seems I had problem with timeout and by creating new `i2c_cmd_handle_t` for each command seems to solve it, I don't know if this is the best way, but it works..

**Comment by Alvin1Zhang** [comment]
@nagyation Thanks for reporting. Feel free to reopen with more details. Thanks.
