### ISSUE TITLE
idf_monitor baud rate

### ISSUE THREAD

**Issue by jkhax0r** [espressif/esp-idf#436]
Custom baud rates are not working on the new idf_monitor b/c the baud rate flag was left out of the command line.    It defaults to 115200.    

In the file: esp-idf/components/esptool_py/Makefile.projbuild.

I modified the line to add the --baud flag as follows:

`$(MONITOR_PYTHON) $(IDF_PATH)/tools/idf_monitor.py --port $(ESPPORT) --baud $(MONITORBAUD) --make "$(MAKE)" $(APP_ELF)`

Sorry I'm not familiar enough with git to figure out how to do a pull request so hopefully someone can make this tweak.

**Comment by projectgus** [comment]
Oops, thank you! Will fix.
