### ISSUE TITLE
Is there any way to create certificates inside device? (IDFGH-2209)

### ISSUE THREAD

**Issue by Kasuhikdas** [espressif/esp-idf#4360]
Development Kit: [ESP32-Wrover-Kit]
Core (if using chip or module): ESP-WROOM32
Development Env: [Make]
Operating System: [Ubuntu]
Power Supply: [USB|external 5V]

I want to create certificate inside the device and send out the public key in server. 
Is there any way to create certificates?

**Comment by negativekelvin** [comment]
https://github.com/espressif/esp-idf/issues/4246

**Comment by mahavirj** [comment]
Closing this issue, please prefer esp32.com forum for `how-to` questions.
