### ISSUE TITLE
Feature request; OTA over UART/SPI (IDFGH-2220)

### ISSUE THREAD

**Issue by howroyd** [espressif/esp-idf#4370]
Currently, when flashing a firmware update using OTA, the OTA info position is updated to enabled the second stage bootloader to select the entry point of the newest partition.
It would be very handy to be able to replicate this when flashing over UART to one of the OTA positions.
Currently, after flashing to a new partition, you then need to delete the original. Then the second stage bootloader throws a load of errors before selecting the new, and only valid, partition. It's a bit hacky.
Perhaps a flag in esptool to set the active partition ID?

**Comment by igrr** [comment]
You can use otatool.py write-ota-partition and switch-ota-partition commands to do this: https://github.com/espressif/esp-idf/blob/master/examples/system/ota/otatool/otatool_example.sh
