### ISSUE TITLE
How to configure SPI CS to use Active High? (IDFGH-2233)

### ISSUE THREAD

**Issue by nagyation** [espressif/esp-idf#4382]

**Comment by ginkgm** [comment]
@nagyation Please use the device flag: https://espressif-docs.readthedocs-hosted.com/projects/esp-idf/en/latest/api-reference/peripherals/spi_master.html#c.SPI_DEVICE_POSITIVE_CS

**Comment by nagyation** [comment]
> @nagyation Please use the device flag: https://espressif-docs.readthedocs-hosted.com/projects/esp-idf/en/latest/api-reference/peripherals/spi_master.html#c.SPI_DEVICE_POSITIVE_CS

Oh, didn't see that, Thanks
