### ISSUE TITLE
in spi_get_actual_clock, what's exactly the duty cycle param? (IDFGH-2234)

### ISSUE THREAD

**Issue by nagyation** [espressif/esp-idf#4383]
I want to set spi clock nearest to certain frequency, it seems `spi_get_actual_clock` does that, but it's waiting for `duty cycle` as integer number which is really confusing me.. and can't find hints anywhere about what values should I use.

**Comment by Icarus113** [comment]
Hi, the `spi_get_actual_clock` has been deprecated, you can use [`spi_device_get_actual_freq`](https://github.com/espressif/esp-idf/blob/master/components/esp_driver_spi/include/driver/spi_master.h#L356) to get the frequency of the device. In this API, the `duty_cycle` is no longer required.
