### ISSUE TITLE
small memory leak in esp_mqtt_client_init error path (IDFGH-2235)

### ISSUE THREAD

**Issue by AxelLin** [espressif/esp-idf#4384]
In IDF-4.0-beta2.
Need to free client->event.error_handle if create mutex for client->api_lock fails.

`
diff --git a/mqtt_client.c b/mqtt_client.c
index 19458f7dc7aa..2343a5c1c78c 100644
--- a/mqtt_client.c
+++ b/mqtt_client.c
@@ -374,6 +374,7 @@ esp_mqtt_client_handle_t esp_mqtt_client_init(const esp_mqtt_client_config_t *co
     }
     client->api_lock = xSemaphoreCreateMutex();
     if (!client->api_lock) {
+        free(client->event.error_handle);
         free(client);
         return NULL;
     }

`

**Comment by ESP-Marius** [comment]
Thanks for reporting this issue, we'll make sure to fix this in our next MQTT update.
