### ISSUE TITLE
CMake Static library's dependency can't be found (IDFGH-2236)

### ISSUE THREAD

**Issue by drony** [espressif/esp-idf#4385]
MySDK uses my own MyLib and this uses nvs_flash lib. when i export mylib as a static library and when i used in another application as libMylib.a. mylib's give error undefined reference to nvs_flash_init() etc. what i missing?

----

MySDK->MyLib->nvs_flash-> compilation success and i get libmylib.a from build

MyApp->libMyLib.a -> compilation error undefined reference to nvs_flash_init() etc.

<img width="1512" alt="Screen Shot 2019-10-22 at 21 56 48" src="https://user-images.githubusercontent.com/101887/69335104-3649db80-0c6d-11ea-9952-eb6277dc5a91.png">

**Comment by renzbagaporo** [comment]
You need to add `nvs_flash` to the dependencies of the imported library as well.

**Comment by drony** [comment]
> 
> 
> You need to add `nvs_flash` to the dependencies of the imported library as well.

thanks it's resolved bu this time another function required.

` undefined reference to `vsnprintf`

but stdio.h included everywhere but give this error
