### ISSUE TITLE
It's not obvious that sntp re-runs (IDFGH-2237)

### ISSUE THREAD

**Issue by will-emmerson** [espressif/esp-idf#4386]
- IDF version: master

## Problem Description
Maybe I'm just stupid but the sntp example doesn't mention anywhere that synchronization will happen automatically based on delay CONFIG_LWIP_SNTP_UPDATE_DELAY. I had assumed it was one-shot and was calling sntp_init myself on a regular basis.
The example and (non-existant, future?) documentation should mention this, and ideally touch on the accuracy of the internal RTC which would allow a more informed decision about the value of CONFIG_LWIP_SNTP_UPDATE_DELAY.

**Comment by KonstantinKondrashov** [comment]
Thanks, @will-emmerson for your report. You are right we do not have information about CONFIG_LWIP_SNTP_UPDATE_DELAY option except in [Kconfig file related to LWIP/SNTP](https://github.com/espressif/esp-idf/blob/master/components/lwip/Kconfig#L607-L614)
I have created an MR to add a description of this for the example and additional chapter `System time` where provide info about the accuracy of all time sources and RTC clock sources.
The MR is in the stage of review. After merged this issue will be closed automatically.
