### ISSUE TITLE
printf stops printing after first newline

### ISSUE THREAD

**Issue by jmattsson** [espressif/esp-idf#44]
It appears that for some strange reason the regular C `printf()` function stops printing when it encounters the first newline (`\n`) in a string. This can be trivially reproduced by attempting to print two lines in the one call; see below for a patch to the official 01_hello_world example.

```
diff --git i/examples/01_hello_world/main/hello_world_main.c w/examples/01_hello_world/main/hello_world_main.c
index ad2c0ac..ca907ea 100644
--- i/examples/01_hello_world/main/hello_world_main.c
+++ w/examples/01_hello_world/main/hello_world_main.c
@@ -14,7 +14,7 @@
 
 void hello_task(void *pvParameter)
 {
-    printf("Hello world!\n");
+    printf("Hello world!\nHiding in plain sight...\n");
     for (int i = 10; i >= 0; i--) {
         printf("Restarting in %d seconds...\n", i);
         vTaskDelay(1000 / portTICK_RATE_MS);
```
Despite applying the above patch, the output stays at:
```
Hello world!
```

If using the `%s` modifier, a newline in the argument string also causes `printf()` to stop outputting characters, effectively cutting short the output. E.g.
```
printf("Hello%s world!\n", "Hiding\n in plain sight...");
```
yields the following output:
```
HelloHiding
```

**Comment by projectgus** [comment]
That @jmattsson . I committed a patch for this into our review queue yesterday, it's a bug in the write syscall.

Because everyone's on holidays this week I'm not sure if we'll get the merged to github until next week (review policy), but I might be able to pop up a temporary branch.

**Comment by jmattsson** [comment]
Really? I instrumented `_write_r()` but by the time it got there the string had already been truncated at the `\n`.

**Comment by projectgus** [comment]
Yeah it's not an obvious bug though., _write_r should return number of bytes written, but doesn't. Stdout is line buffered by default: so the first line gets sent to _write_r & TXed,, _write_r returns zero, newlib discards the rest of the buffer thinking there was an error.

Fix is incoming now, should be auto-pushed github shortly...

**Comment by jmattsson** [comment]
Ah, sneaky bug! Glad it was an easy fix though.
