### ISSUE TITLE
Feature request: driver installed (IDFGH-2267)

### ISSUE THREAD

**Issue by howroyd** [espressif/esp-idf#4409]
Request for a method in the APIs to check whether a driver has already been installed.

For example, if you have two objects, both using UART_NUM_1, then the object that is created second has no way of knowing if the UART driver is already installed and running, or not.

Would be very useful,

Many thanks

**Comment by koobest** [comment]
Hi, @howroyd 
Thins feature is available on 4.2 ~ 4.0 release version.
