### ISSUE TITLE
esp_http_client memory leak in esp_http_client_set_username/password (IDFGH-2306)

### ISSUE THREAD

**Issue by AxelLin** [espressif/esp-idf#4444]
I'm checking the code in ESP-IDF-4.0-beta2:

In esp_http_client_set_username, it has below code:

    if (username == NULL && client->connection_info.username != NULL) {
        free(client->connection_info.username);
        client->connection_info.username = NULL;
    } else if (username != NULL) {
        client->connection_info.username = strdup(username);
   

Above code can cause memory leak when username != NULL && client->connection_info.username != NULL.
The same issue with esp_http_client_set_password.

e.g.
In esp_http_client/test/test_http_client.c
below test case will have memory leak.

TEST_CASE("Username and password will not reset if new absolute URL doesnot specify auth credentials.", "[ESP HTTP CLIENT]")
{
    esp_http_client_config_t config_with_auth = {
        .host = HOST,
        .path = "/",
        .username = USERNAME,
        .password = PASSWORD
    };
    char *value = NULL;
    esp_http_client_handle_t client = esp_http_client_init(&config_with_auth);
    TEST_ASSERT_NOT_NULL(client);
    esp_err_t r = esp_http_client_get_username(client, &value);
    TEST_ASSERT_EQUAL(ESP_OK, r);
    TEST_ASSERT_NOT_NULL(value);
    TEST_ASSERT_EQUAL_STRING(USERNAME, value);
    esp_http_client_set_url(client, "http://" HOST "/get");
    esp_http_client_set_username(client, value);
    esp_http_client_set_password(client, value);

BTW, since there are APIs to set_url/set_usernam/set_password,
why not also support set_authtype as well?

I post my proposed fix in attached file (including add set_authtype function):
[esp_http_client_fix_memoryleak_and_allow_set_authtype_diff.txt](https://github.com/espressif/esp-idf/files/3924897/esp_http_client_fix_memoryleak_and_allow_set_authtype_diff.txt)

**Comment by mahavirj** [comment]
@AxelLin Is it possible for you to create pull request (based on fix you provided above)?
