### ISSUE TITLE
BLDC MCPWM seems to clash with the strapping pins (IDFGH-2326)

### ISSUE THREAD

**Issue by davidmolony** [espressif/esp-idf#4461]
## Environment

- Module or chip used:  [ESP32-WROOM-32|ESP32-WROOM-32D|ESP32-WROOM-32U|ESP32-WROVER|ESP32-WROVER-I|ESP32-WROVER-B|ESP32-WROVER-IB|ESP32-SOLO-1|ESP32-PICO-D4|ESP32]
- IDF version N/A

## Problem Description

The default setup of the MCPWM for BLDC uses GPIO0 and GPIO4 for the BH and BL drivers... This means that the device will turn on the BH when using the IR2136 and programming, or any other bridge driver might turn it on/off/..? depending on the logic input of the part.

From the basic config, it seems that the GPIO for these functions can be reallocated to any pin, so suggest modifying the example to use e.g. 
GPIO 18&05 for phase U, 
GPIO 17&16 phase V, 
GPIO 02&15 phase W.

This avoids the conflict in the default sketch.

Also, the IR2136 has an "enable" pin, which is not currently allocated... will this sketch actually work on the hardware described?

### Expected Behavior
Expected will have erroneous behaviour on programming/runtime.
### Actual Behavior
N/A, will be as above
### Steps to reproduce
By examination

**Comment by koobest** [comment]
Hi
Thank you for your feedback. Well, this is an example to show you how to use MCPWM. The actual application is to decide which IO to allocate based on the actual hardware.

thanks !!

**Comment by Alvin1Zhang** [comment]
@davidmolony Thanks for reporting and sorry for the slow turnaround for the reply. Feel free to reopen, thanks.
