### ISSUE TITLE
mbedTLS update (IDFGH-2333)

### ISSUE THREAD

**Issue by Keeper-of-the-Keys** [espressif/esp-idf#4466]
The mbedTLS version included with ESP-IDF is relatively old (2.13 - 2018/9) is there any specific bug preventing an update to 2.16.3 (2019/9)?

Thanks!

**Comment by mahavirj** [comment]
@Keeper-of-the-Keys We are already on mbedtls-2.16.2 release (https://github.com/espressif/mbedtls/tree/mbedtls-2.16.2-idf) post ESP-IDF v3.3. In case you are using prior ESP-IDF release, recommend that you upgrade to `v3.3` (or above), we will not be backporting this feature.

**Comment by mahavirj** [comment]
Since there are now followup questions, I will close this issue.
