### ISSUE TITLE
esp_wifi_set_max_tx_power(82) (IDFGH-2348)

### ISSUE THREAD

**Issue by AddisAir** [espressif/esp-idf#4477]
According to the [docs](https://docs.espressif.com/projects/esp-idf/en/latest/api-reference/network/esp_wifi.html#_CPPv425esp_wifi_set_max_tx_power6int8_t), esp_wifi_set_max_tx_power(82) can be set up to 82.

However, when you do that, it just stays on 78. 
Is this a bug? or an error in the documentation? 

I understand there are legal limits for TX power, but there are situations where it doesn't apply.

**Comment by chegewara** [comment]
https://github.com/espressif/esp-idf/issues/4223

**Comment by esp-HarveyRong** [comment]
Hi @AddisAir  At present, the maximum value can only be 78, and values greater than 78 will also be set to 78.

**Comment by Alvin1Zhang** [comment]
@AddisAir Thanks for reporting. Would you please help share if any updates for the issue? Has your issue been resolved? Thanks.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting and sorry for slow turnaround, the fix is available at https://github.com/espressif/esp-idf/commit/695ad84654188ffa970760fa1c307e119178ba8c. Feel free to reopen if the issue still happens. Thanks.
