### ISSUE TITLE
Missing dependencies for fresh install on Raspberry Pi 3B+ with Buster Lite  (IDFGH-2352)

### ISSUE THREAD

**Issue by AloyseTech** [espressif/esp-idf#4480]
## Environment

- IDF version (run ``git describe --tags`` to find it): v4.1-dev-1086-g93a8603c5
- Build System:         CMake
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it): xtensa-esp32-elf-gcc (crosstool-NG esp-2019r2) 8.2.0
- Operating System:     Linux (Raspbian Buster Lite
- Power Supply:         USB

## Problem Description

//Detailed problem description goes here.

### Expected Behavior
when running install.sh, the tools installation should succeed.

### Actual Behavior
Installation fails at 2 stages:
It first miss libffi, then opensslv.

To fix the missing dependencies I've run the following command :

> sudo apt-get install libffi-dev libssl-dev

After installing the 2 additional dependencies, install.sh succeed.

When proceeding to build the hello-world example, the compilation fails with segfault error.
To fix this, I updated the Raspberry Pi firmware using 

> sudo rpi-update

Building works successfully after the update.

### Steps to repropduce

Install a fresh Raspbian Buster Lite on a RPI3B+, follow esp-idf getting started for linux.

**Comment by dobairoland** [comment]
Hi @AloyseTech. Did you install the prerequisites for Debian according to this page https://docs.espressif.com/projects/esp-idf/en/latest/get-started/linux-setup.html?

**Comment by AloyseTech** [comment]
Hi @dobairoland ,
Yes, I followed the getting started guide for linux/debian and installed the following dependencies :
`sudo apt-get install git wget flex bison gperf python python-pip python-setuptools python-serial python-click python-cryptography python-future python-pyparsing python-pyelftools cmake ninja-build ccache`

**Comment by dobairoland** [comment]
Thank you for your report. I'll update the documentation. Newer versions of `apt-get` doesn't install as many packages as older ones and we need to add more and more packages to our list manually. Thanks!

**Comment by AloyseTech** [comment]
Please also note that without updating the Raspberry Pi firmware, the build fails with segfault. I'm not sure what cause the issue though (I tried the firmware update after reading this : https://github.com/esphome/issues/issues/677).

**Comment by dobairoland** [comment]
We don't have recommendations in the documentation regarding to do system update for any operating systems. I just assume (hope) that everyone keeps up-to-date their systems with regular security and bugfix updates.

I'm guessing that `apt-get` installed the latest versions of these packages and the rest of the system was out-of-date and linked against different or older packages.
