### ISSUE TITLE
OPC-N3 reading error by SPI with esp-idf v3.3 (IDFGH-2374)

### ISSUE THREAD

**Issue by AlexVilella** [espressif/esp-idf#4502]
## Environment
Module or chip used:  ESP32-D0WD (16MB)
IDF version: ESP-IDF v3.3-dirty
Compiler: xtensa-esp32-elf-gcc.exe (crosstool-NG crosstool-ng-1.22.0-80-g6c4433a5) 5.2.0
Operating System: Windows 10
Power Supply: USB

## Problem Description

I'm trying to migrate esp-idf to version 3.3, but when I'm going to read the OPC-N3 data by SPI, it doesn't read correctly. I got it to work when I add '**host->hw->user.usr_mosi_highpart=1;**' in the function '**spi_new_trans()**' as it is in version 3.1.3 and I don't know why when I add those two lines the OPC-N3 does work.
I've also had to modify the following:
host->hw->data_buf[(x/32)**+8**]=word'.

Someone can explain to me what those two variables are for and why it fails when they are not there?

In the esp-idf v3.1.3 works without problems.

### Expected Behavior
![esperado](https://user-images.githubusercontent.com/36877888/71006405-96edfc00-20e5-11ea-973c-8f51d9d8a5b6.PNG)

### Actual Behavior
![actual](https://user-images.githubusercontent.com/36877888/71006457-a2412780-20e5-11ea-96f6-71ecbc166606.PNG)

### Code
Lines 850-870 of spi_master.c
```
static void SPI_MASTER_ISR_ATTR spi_new_trans(spi_device_t *dev, spi_trans_priv_t *trans_buf)
{
    ............

    if (trans_buf->buffer_to_send) {
        if (host->dma_chan == 0) {
            //Need to copy data to registers manually
            for (int x=0; x < trans->length; x+=32) {
                //Use memcpy to get around alignment issues for txdata
                uint32_t word;
                memcpy(&word, &trans_buf->buffer_to_send[x/32], 4);
                host->hw->data_buf[(x/32)+8]=word;
            }
	    host->hw->user.usr_mosi_highpart=1;
        } else {
            spicommon_setup_dma_desc_links(host->dmadesc_tx, (trans->length+7)/8, (uint8_t*)trans_buf->buffer_to_send, false);
            host->hw->dma_out_link.addr=(int)(&host->dmadesc_tx[0]) & 0xFFFFF;
            host->hw->dma_out_link.start=1;
        }
    }

    ............
}
```
### Conclusion
The error does not come from my code, because in the esp-idf v3.1.3 does work correctly, the error is migrating to the esp-idf v3.3.

Now with the changes I've made to the spi_master.c it works correctly.

Thank you.

**Comment by ginkgm** [comment]
Hi @AlexVilella ,
ESP32 SPI peripheral has a 64 bytes buffer to use when DMA is not enabled.

highpart=1 means that part uses high 32 bytes region, so you also have to write your data to higher 32 bytes region (+8 word). 

When TX and RX are both highpart=0, they share the whole 64 bytes buffer. The driver will prepare data to send from byte 0, and store received data starting from byte 0. So I guess your receiving data is erased by the data to send.

Do you rely on remaining data in the buffer?

**Comment by Alvin1Zhang** [comment]
@AlexVilella Thanks for reporting, would you please help share if any updates for the issue? Thanks.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to short of feedback, feel free to reopen.
