### ISSUE TITLE
AP does not work with short password (IDFGH-2389)

### ISSUE THREAD

**Issue by Reiner1210** [espressif/esp-idf#4506]
Hello,

an AP does not work with a too short password.
esp_wifi_set_config failed with error code 11.

Best regards
Reiner

**Comment by BonifaceBassey** [comment]
What is the length of your password?
The shortest password allowed with WPA2 is 8 characters long.

**Comment by Alvin1Zhang** [comment]
@Reiner1210 Thanks for reporting. Would you please help share more details, like the brand of the AP and etc would help more. Thanks.

**Comment by Reiner1210** [comment]
Hello, I mean when I use ESP32 as AP

**Comment by TimXia** [comment]
The password length of WPA/WPA2 should not be shorter than eight.

**Comment by Alvin1Zhang** [comment]
@Reiner1210 Thanks for reporting. Please help follow the notes by @TimXia will close the ticket now. Thanks.
