### ISSUE TITLE
The timestamp of the captured packet in sniffer mode is not updated for a long time (IDFGH-2412)

### ISSUE THREAD

**Issue by wgcod** [espressif/esp-idf#4526]
When I use sniffer mode to capture some WiFi packets, I find that sometimes the timestamps of dozens of consecutive packets are the same, lasting even 300ms. Is this normal? Time is not accurate enough? Or ampdu? But I use Wireshark to capture packets on Linux. The time of each packet is different. I want to make sure. Thank you.

**Comment by zhangyanjiaoesp** [comment]
@wgcod Please describe how you call the sniffer API, and provide the logs of your test.

**Comment by wgcod** [comment]
The test is very simple. I used the sniffer demo to output the time stamp of each package in the callback function, as you can see.

**Comment by zhangyanjiaoesp** [comment]
@wgcod Have you enabled the modem sleep or light sleep? There is description in IDF:
 https://github.com/espressif/esp-idf/blob/30372f5a4ff2c0dfdaad95f544dc36bcdda30b75/components/esp_wifi/include/esp_wifi_types.h#L335

**Comment by wgcod** [comment]
No, I test with demo without any modification. Save the data to SD card and open it with Wireshark. Sometimes, a dozen or more packet timestamps are the same. When I capture packets with Wireshark at the same time, I can see that the time of these packets is different, but only 2-3us is related between packets. Is it because the clock is not accurate. If so, is it configurable? You can try it. Just use demo.

**Comment by zhangyanjiaoesp** [comment]
hi @wgcod ,
I have tested with `simple_sniffer` example in IDF, and open the capture packets with Wireshark, for some packets the timestamps are the same, but only about a dozen milliseconds. And the time inaccuracy is  acceptable for ESP32. 
If you want the timing to be particularly accurate, you can try our new chip ESP32S2.
https://www.espressif.com/en/products/socs/esp32-s2

![image](https://user-images.githubusercontent.com/30309181/87525064-8faec100-c6bb-11ea-9573-dcfef28dd97a.png)

**Comment by Alvin1Zhang** [comment]
Thanks for reporting and sorry for slow turnaround, feel free to reopen if the issue still happens. Thanks.
