### ISSUE TITLE
Sending file with chunks, error Recv 104 (IDFGH-2414)

### ISSUE THREAD

**Issue by jcecconi** [espressif/esp-idf#4528]
https://github.com/espressif/esp-idf/blob/30372f5a4ff2c0dfdaad95f544dc36bcdda30b75/examples/protocols/http_server/file_serving/main/file_server.c#L278

This line is not needed because httpd_resp_send_chunk function was called with zero Len last time on line 260.
Calling it again rise the Recv 104 error on Logs.

**Comment by Alvin1Zhang** [comment]
@jcecconi Thanks for reporting. We have already had a fix internally, will inform you when the fix is available on GitHub. Thanks.
