### ISSUE TITLE
led_strip  example only works with Level Shifter (IDFGH-2420)

### ISSUE THREAD

**Issue by ISOMAX** [espressif/esp-idf#4533]
Hello, 

the Example 
https://github.com/espressif/esp-idf/tree/master/examples/peripherals/rmt/led_strip
only works when i add a Level Shifter. 

i use a simple 74AXP1T34GWH from Nexperia along with 2 pieces of 220Ohm Resistors on the Input and output in series. 

this gives a perfect Rainbow.

**Comment by suda-morris** [comment]
Sorry in my hardware WS2812 is 3.3V capable.
From WS2812 datasheet, VIH should not smaller than 0.7VDD, and VIL should not greater than 0.3VDD. 
Maybe your hardware can't meet the limitation?

**Comment by Alvin1Zhang** [comment]
@ISOMAX Thanks for reporting, would you please help share if any updates for this issue? Thanks.

**Comment by Alvin1Zhang** [comment]
@ISOMAX Thanks for reporting, would you please help share if any updates for this issue? Thanks.

**Comment by ISOMAX** [comment]
I will check this again, OK ? 

 

 

Von: Alvin1Zhang <notifications@github.com> 
Gesendet: Dienstag, 7. Januar 2020 04:53
An: espressif/esp-idf <esp-idf@noreply.github.com>
Cc: ISOMAX <franz@isomax.tech>; Mention <mention@noreply.github.com>
Betreff: Re: [espressif/esp-idf] led_strip example only works with Level Shifter (IDFGH-2420) (#4533)

 

@ISOMAX <https://github.com/ISOMAX>  Thanks for reporting, would you please help share if any updates for this issue? Thanks.

**Comment by Alvin1Zhang** [comment]
@ISOMAX Many thanks for the updates.

**Comment by Alvin1Zhang** [comment]
@ISOMAX Thanks for reporting, feel free to reopen if the issue still happens. Thanks.
