### ISSUE TITLE
CAN bus (IDFGH-2421)

### ISSUE THREAD

**Issue by Axel1400** [espressif/esp-idf#4534]
Hi, I'm using CAN peripheral and I want to use the register instead of all functions, but technical reference manual doesn't have any information about CAN Bus, is there a way I can see CAN peripheral registers?

**Comment by collin80** [comment]
Sure, look at the source code. For instance, here:
https://github.com/espressif/esp-idf/blob/master/components/soc/esp32/include/soc/can_struct.h

Also, look at the actual CAN driver in the ESP-IDF. Between all the various
headers and the C source file for the driver you should have everything you
need to do it yourself.

**Comment by negativekelvin** [comment]
Also https://github.com/espressif/esp-idf/issues/4276
