### ISSUE TITLE
Eclipse Error

### ISSUE THREAD

**Issue by sfranchin63** [espressif/esp-idf#454]
Hello guys,
I'm trying to compile the example hello-world with eclipse IDE in win7, but always receive  this error:
/usr/bin/bash: C:/msy32/home/Stefanof/esp-idf/tools/windows/eclipse_make.sh: No such file or directory
I checked the file and directory exist.
Can someone help me.
Thanks
Stefano
![error](https://cloud.githubusercontent.com/assets/23196408/24304219/e7f7b798-10b8-11e7-9267-a695c01c77fe.JPG)

**Comment by ESP32DE** [comment]
@sfranchin63 
[please read the windows setup for eclipse](http://esp-idf.readthedocs.io/en/latest/eclipse-setup-windows.html#eclipse-windows-setup)

[you have forget to](http://esp-idf.readthedocs.io/en/latest/eclipse-setup-windows.html#project-properties) 
- uncheck use default build command
- add python command for the shell..


here is a picture
![neon3_1](https://cloud.githubusercontent.com/assets/16070445/24323490/8ee8c944-1176-11e7-968a-6afe5616f1b5.png)

hope this helps

best wishes
rudi ;-)

**Comment by sfranchin63** [comment]
Hi Rudi, 
I have made change you suggested, but it have failed.
In order to set Eclipse I followed the instructions (Setup Build Variables):
https://exploreembedded.com/wiki/Setting_up_Eclipse_for_ESP-IDF
![error1](https://cloud.githubusercontent.com/assets/23196408/24333663/4bc50bdc-125c-11e7-8dad-244fffa1358c.JPG)
![error3](https://cloud.githubusercontent.com/assets/23196408/24333654/2b497a3c-125c-11e7-83ed-c466ddb0af3a.JPG)
Thanks
Stefano

**Comment by projectgus** [comment]
There's a typo in the path, `msy32` -> `msys32` and it should work.

**Comment by sfranchin63** [comment]
Thanks for your suggestions and with the change of msys32 now it all works .

**Comment by projectgus** [comment]
Glad to hear you got it working.
