### ISSUE TITLE
Windows setup instructions not working (IDFGH-2431)

### ISSUE THREAD

**Issue by vaderj** [espressif/esp-idf#4544]
## Environment

- Development Kit:      |ESP32-PICO-Kit]
- Kit version (for WroverKit/PicoKit/DevKitC): [v1]
- Module or chip used:  [ESP32-PICO-D4]
- IDF version - v4.1-dev-1572-g30372f5a4

- Build System:         |CMake]
- Operating System:     [Windows]

## Problem Description

Using the direction provided here: https://docs.espressif.com/projects/esp-idf/en/latest/get-started/windows-setup.html

Making specific note about this comment:
"Previous versions of ESP-IDF used the Legacy GNU Make Build System and MSYS2 Unix compatibility environment. This is no longer required, ESP-IDF can be used from the Windows Command Prompt."

I am unable to define the IDF_PATH variable.

The ESP-IDF source is stored at c:\src\esp-idf

If my IDF_PATH = "/c/src/esp-idf", and I try running "make menuconfig" from the examples/get-started/hello_world folder, I receive the following error:

Makefile:11: /c/src/esp-idf/make/project.mk: No such file or directory
make: *** No rule to make target '/c/src/esp-idf/make/project.mk'.  Stop.

If I set the IDF_PATH = "/c:/src/esp-idf" and try make menuconfig, I receive:
c:/src/esp-idf/make/project.mk:114: *** IDF_PATH cannot contain colons. If overriding IDF_PATH on Windows, use MSYS Unix-style /c/dir instead of C:/dir.  Stop.

So I am unclear of how the path should be defined as it seems the documentation does not work with the current IDF.

Thanks for your help!

### Expected Behavior
make menuconfig from examples/get-started/hello_world should bring up the menuconfig

### Actual Behavior
No ability to properly define IDF_PATH

### Steps to repropduce

1. Attempt to implement the ESP-IDF
2. make menuconfig

### Code to reproduce this issue
Unable to get this far

**Comment by bitmakk** [comment]
I think, you may be try to using the new CMake based system. If you installed everything, you have to run in a cmd the install.bat and export.bat files (if I remember their names correctly). These will generate you a shortcut with an IDF command prompt. The MSYS will not work with it. The IDF_PATH has to look like this: C:/src/esp-idf
After these, you have to forget everything that is connected to make commands.
You can use instead idf.py menuconfig, idf.py flash, and so on...
And remember: everything is different under CMake-based system.
