### ISSUE TITLE
ESP32 Mdns with Android Chrome (IDFGH-2437)

### ISSUE THREAD

**Issue by DheeranYuvaraj** [espressif/esp-idf#4550]
Hi,

I am trying http web server with mDNS. As per ESP-IDF Programming guide if we want use mDNS with windows browsers **Bonjour** has to be installed.  I followed the same and i am able to access [http://esp32.local/](url) in windows pc.

But in my case i want to open same [http://esp32.local/](url) in android browsers. Is there any way to do it.

**Comment by DheeranYuvaraj** [comment]
Any Updates?

**Comment by negativekelvin** [comment]
No, people have been asking to have this feature on Android for a long time.  You have to make an app or use captive portal if you are in AP mode.

https://bugs.chromium.org/p/chromium/issues/detail?id=405925
https://issuetracker.google.com/issues/36932514
https://issuetracker.google.com/issues/140786115

**Comment by DheeranYuvaraj** [comment]
Dear @negativekelvin 
Thanks for the information. Do you have any app source code?
