### ISSUE TITLE
Compile error on verbose level (IDFGH-2439)

### ISSUE THREAD

**Issue by Reiner1210** [espressif/esp-idf#4552]
Log info to V
`
In file included from /home/reiner/data/programm/esp/esp-idf/components/soc/include/hal/hal_defs.h:17,
                 from /home/reiner/data/programm/esp/esp-idf/components/soc/src/hal/sdio_slave_hal.c:23:
/home/reiner/data/programm/esp/esp-idf/components/soc/src/hal/sdio_slave_hal.c: In function 'sdio_slave_hal_send_reset_counter':
/home/reiner/data/programm/esp/esp-idf/components/log/include/esp_log.h:281:13: error: 'len' may be used uninitialized in this function [-Werror=maybe-uninitialized]
             ets_printf(LOG_FORMAT(log_tag_letter, format), esp_log_timestamp(), tag, ##__VA_ARGS__); \
             ^~~~~~~~~~
/home/reiner/data/programm/esp/esp-idf/components/soc/src/hal/sdio_slave_hal.c:375:14: note: 'len' was declared here
`

**Comment by masterd89** [comment]
Whatching this issue. Happening here as well

**Comment by Reiner1210** [comment]
You only need to initialize the len with zero :-)

**Comment by tritao** [comment]
Getting the same issue on the `hello_world` sample.

**Comment by gshmakov** [comment]
Same issue. Still not fixed.

**Comment by arnowi** [comment]
Hi,

I'm still getting this issue on branch release/v4.1

`In file included from /home/arno/Documents/projects/esp-idf/components/soc/include/hal/hal_defs.h:17,
                 from /home/arno/Documents/projects/esp-idf/components/soc/src/hal/sdio_slave_hal.c:23:
/home/arno/Documents/projects/esp-idf/components/soc/src/hal/sdio_slave_hal.c: In function 'sdio_slave_hal_send_reset_counter':
/home/arno/Documents/projects/esp-idf/components/log/include/esp_log.h:281:13: error: 'len' may be used uninitialized in this function [-Werror=maybe-uninitialized]
             ets_printf(LOG_FORMAT(log_tag_letter, format), esp_log_timestamp(), tag, ##__VA_ARGS__); \
             ^~~~~~~~~~
/home/arno/Documents/projects/esp-idf/components/soc/src/hal/sdio_slave_hal.c:375:14: note: 'len' was declared here
     uint32_t len;
              ^~~
`

**Comment by igrr** [comment]
@arnowi Thanks for the notice, we will backport the fix to release/v4.1 as well
