### ISSUE TITLE
C++ missing libgcc library (IDFGH-2445)

### ISSUE THREAD

**Issue by paoloach** [espressif/esp-idf#4558]
## Environment

- Development Kit:     none
- Module or chip used:  ESP32-WROVER-I
- IDF version :   v4.1-dev-1572-g30372f5a4
- Build System:         CMake
- Compiler version: xtensa-esp32-elf-gcc (crosstool-NG esp-2019r2) 8.2.0
- Operating System:    Linux 
- Power Supply:         USB

## Problem Description

With this repository version, my project, containing c++ files, don't more link
I got a list of undefined symbol as _Unwind_GetTextRelBase, _Unwind_GetRegionStart', etc...

The problem disappears if I add the libgcc to the link command:  
xtensa-esp32-elf-g++  -mlongcalls -Wno-frame-address -O3 -DNDEBUG  .... -lc  ** -lgcc ** 

As workaround I added this library to component.cmake so now I don't more manually execute the link command for adding the libgcc library
.....
438     list(REMOVE_ITEM common_reqs ${component_lib})
439    link_libraries(${common_reqs} **gcc**)
440
---
    
### Expected Behavior

It have to link without problem

### Actual Behavior

When use C++ code, I have undefined symbol because the lack of libgcc

### Steps to repropduce

I not be able to use the example to reproduce it using the example in c++. Can be my project contains some c++ features not present in the simple examples

**Comment by igrr** [comment]
Can you please give a link to upload the project to reproduce this?

If you do idf.py fullclean and the idf.py build again, does the issue still occur?

**Comment by paoloach** [comment]
Great. You are right.
It was enough recreate the build directory.
Thank a lot.

**Comment by paoloach** [comment]
The issue doesn't exist
