### ISSUE TITLE
ESP32添加自己生成的库文件(.a)到工程编译报错 (IDFGH-2447)

### ISSUE THREAD

**Issue by lxdemon** [espressif/esp-idf#4560]
你好：
我有一个项目需要使用自己生成的库文件，但是添加之后编译不过去，报错信息如下：
/home/lixin/workspace/esp32/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/5.2.0/../../../../xtensa-esp32-elf/bin/ld: /home/lixin/workspace/esp32/IR_extender_ESP32/components/ir_handle/ir_engine/libuird.a(irLearnLib.o): Relocations in generic ELF (EM: 40)
/home/lixin/workspace/esp32/IR_extender_ESP32/components/ir_handle/ir_engine/libuird.a: error adding symbols: File in wrong format
collect2: error: ld returned 1 exit status

component.mk添加的配置如下：
COMPONENT_ADD_LDFLAGS += $(COMPONENT_PATH)/ir_handle/ir_engine/libuird.a

生成库文件的环境：
OS: Ubuntu18.04
gcc：arm-none-eabi-gcc

望解答，感谢！

**Comment by igrr** [comment]
The issue happens because the compiler you use to generate the library (arm-none-eabi-gcc) is for the different CPU architecture than the one used in ESP32. To generate a library compatible with the ESP32, you need to use `xtensa-esp32-elf-gcc` and pass `-mlongcalls` flag to it.

**Comment by lxdemon** [comment]
Now it is working, thank you!

**Comment by Alvin1Zhang** [comment]
@lxdemon Thanks for reporting, feel free to reopen if the issue still happens. Thanks.
