### ISSUE TITLE
esp_ble_gattc_open failed when scanning (IDFGH-2449)

### ISSUE THREAD

**Issue by syu-source** [espressif/esp-idf#4562]
Hi all, 

I'm working on esp-idf v4.0-dev-1287-gd7e659df2, with esp32s dev board.
My application requires esp32 to connect to multiple BLE devices. So I need to keep esp32 scanning,  connecting to devices as discovered.

However I have an issue, my app cannot connect to BLE while scanning. 
While scanning,  after esp_ble_gattc_open, the ESP_GATTC_OPEN_EVT comes with open.status == 133(0x85), which is ESP_GATT_ERROR.

Currently I have to do following steps as walkaround:
esp_ble_gap_stop_scanning
esp_ble_gattc_open
if ( got ESP_GATTC_OPEN_EVT )esp_ble_gap_start_scanning

My question is:
Is there anything I missed or is it just normal?

**Comment by GYC-Espressif** [comment]
Yes, the recommended action is to stop scanning while connecting and restart the scan after the connection is established.
If you have the print log in ESP_GAP_BLE_SCAN_RESULT_EVT, please try to reduce the log in this event. That might work too.

**Comment by syu-source** [comment]
Why is log printing related... 
Thanks anyway.

**Comment by GYC-Espressif** [comment]
That's because uart's printing speed is too slow and it may occupy too much time in the Bluetooth Stack. If your issue is resolved, can you close it? Thank you.

**Comment by Alvin1Zhang** [comment]
@syu-source Thanks for reporting, would you please help share if any updates for the issue? Has the issue been resolved? Thanks.

**Comment by Alvin1Zhang** [comment]
@syu-source Thanks for reporting, would you please help share if any updates for the issue? Has the issue been resolved? Thanks.

**Comment by syu-source** [comment]
Stop scanning, connect, restart scanning.
Then everything works. 
I guess scanning reports lots of result and callback may occupy too much time. 
Anyway, issue closed. Thanks.

**Comment by Alvin1Zhang** [comment]
Thanks for sharing the updates.
