### ISSUE TITLE
In Sniffer Mode, Can I get the frame header of MIMO, not just the frame length? (IDFGH-2463)

### ISSUE THREAD

**Issue by wgcod** [espressif/esp-idf#4575]
![image](https://user-images.githubusercontent.com/48508117/71714402-ae98e480-2e48-11ea-9bfb-bfc1d9e1d14b.png)

Third, 
802.11 MIMO frame, for MIMO frame, the sniffer only dumps the length of the frame.
I know that esp32 doesn't support MIMO and won't capture complete packets, but now there is frame length. Can I get the frame header?

**Comment by TimXia** [comment]
Do you mean the MAC header? esp32 can not get the MAC header of MIMO.

**Comment by Alvin1Zhang** [comment]
@wgcod Thanks for reporting. Please help create another ticket if you have more issues, thanks.
