### ISSUE TITLE
[TW#11597] i2s output

### ISSUE THREAD

**Issue by jobidon** [espressif/esp-idf#458]
to help troubleshoot i2s issues, this minimal check could be added. It ensures the pin used for output is a valid **output** pin, not just a valid pin.

components/driver/i2s.c #L401
    if (pin->data_out_num != -1 && !GPIO_IS_VALID_OUTPUT_GPIO(pin->data_out_num)) {

**Comment by FayeY** [comment]
Hi, this issue has been solved in the latest ESP-IDF. Thanks for your reporting!
