### ISSUE TITLE
SPIFFS: failed to read addr 00006a00, size 00000100, err 257 (IDFGH-2483)

### ISSUE THREAD

**Issue by GitOfLance** [espressif/esp-idf#4595]
### Environment
- Module or chip used: ESP32-WROOM-32
- IDF version :  v4.0-dev-1443-g39f090a4f 2nd stage bootloader
- Build System: Make
- Compiler version : xtensa-esp32-elf-
- Operating System: Ubuntu 18.04
- Power Supply: USB

### Problem Description:
Frequent errors occur when writing data to `SPIFFS` or reading data from `SPIFFS`. Error messages are as follows:
![image](https://user-images.githubusercontent.com/48943389/71890709-ddcc9000-317f-11ea-8d9a-10231d4b5d39.png)

ErrorError 2:
![image](https://user-images.githubusercontent.com/48943389/71891294-4700d300-3181-11ea-8856-3fc1a49034cc.png)

Error 3:
![image](https://user-images.githubusercontent.com/48943389/71891327-5da72a00-3181-11ea-9e75-8ee3436e1503.png)

I would like to ask, how to deal with this type of problem, and how to ensure that using SPIFFS to read and write data is almost 100% successful. If you do not use SPIFFS, but directly operate on Flash, will the stability be improved?

**Comment by GitOfLance** [comment]
Is there progress on this issue?

**Comment by Alvin1Zhang** [comment]
@GitOfLance Thanks for reporting and sorry for the late reply. We will look into. Thanks.

**Comment by igrr** [comment]
Hi @GitOfLance, this is very likely the same issue as https://github.com/espressif/esp-idf/issues/4769. The fix for it should be merged shortly. In the meantime you can apply the change mentioned in https://github.com/espressif/esp-idf/issues/4769#issuecomment-586583027 locally.

**Comment by GitOfLance** [comment]
Hi, @Alvin1Zhang @igrr 
It looks like this is a Flash read / write error caused by this bug. Thank you very much for your answers。

**Comment by rebeliousconformist** [comment]
+1 
<pre>W (198897) wifi:alloc eb len=24 type=3 fail, heap:0

W (198897) wifi:m f null</pre>

**Comment by Alvin1Zhang** [comment]
Fix mentioned in https://github.com/espressif/esp-idf/issues/4769 is available on GitHub, feel free to reopen.
