### ISSUE TITLE
how to include dht22 library (import third party library) error in CMakeLists.txt file (IDFGH-2493)

### ISSUE THREAD

**Issue by ravishree19** [espressif/esp-idf#4603]
I have to interface dht22 sensor in ESP32 using esp-idf.I refered https://github.com/UncleRus/esp-idf-lib for dht22 and i was unable to include the dht lib.Can you please help me with the CmakeList.txt file and the Make file to include path.The issue after following the procedure in above link is that esp32 is restarting.I didnt know how CmakeList file works.

**Comment by renzbagaporo** [comment]
Hi @ravishree19, so you are able to build a project using the library you mentioned successfully?

**Comment by ravishree19** [comment]
> Hi @ravishree19, so you are able to build a project using the library you mentioned successfully?

yes bt after flashing esp32 is restarting below are the screenshots.
![Screenshot from 2020-01-09 11-43-07](https://user-images.githubusercontent.com/59655089/72042894-bee01200-32d5-11ea-84bf-5ef326a4cfc2.png)
![Screenshot from 2020-01-09 11-48-24](https://user-images.githubusercontent.com/59655089/72042964-f77feb80-32d5-11ea-9701-43bf827b04ed.png)
![Screenshot from 2020-01-09 11-48-53](https://user-images.githubusercontent.com/59655089/72042997-0797cb00-32d6-11ea-9b84-912c0a593d61.png)

**Comment by renzbagaporo** [comment]
@ravishree19 Since the build succeeds, I would guess that the library you were trying to use got 'imported' correctly. The error at runtime is a totally different issue, and from what I can see in the logs, is with the third-party library.

Unfortunately, you would have to file this issue with the author of the library you were trying to use.

**Comment by Alvin1Zhang** [comment]
@renzbagaporo Thanks for the support. @ravishree19 Thanks for reporting, for "how" question or "third party issues", suggest you could create a post on our forum at https://esp32.com or file the issue with the author of the library you were trying to use. Will close the ticket for now. Thanks.
