### ISSUE TITLE
Add support of start/stop marker and KEEP keyword in linkerscript fragments (IDFGH-2524)

### ISSUE THREAD

**Issue by chapipo** [espressif/esp-idf#4612]
**Is your feature request related to a problem? Please describe.**

I would like to be able to put some struct in a special section in the linker script and put start and stop marker to be able to loop on them. When trying to do this with linkerfragments, I cannot put marker and I cannot force some section to be kept (with the KEEP keyword).

**Describe the solution you'd like**

A modification to be able to put start / stop marker in linkerscript fragments.

**Describe alternatives you've considered**

At the moment, the only way to do this, is to patch est-idf linkerscript.

Linkerscript extract example:
```
 _s_custom_section = ABSOLUTE(.);
KEEP(*(.custom.section))
_e_custom_section = ABSOLUTE(.);
```

I found on esp32 forum a similar request: https://esp32.com/viewtopic.php?t=13102

**Comment by Alvin1Zhang** [comment]
@chapipo Thanks for raising the feature request.

**Comment by renzbagaporo** [comment]
Hi @chapipo, this is also a desirable feature for us internally, so we definitely take this into consideration. However, this is a non-trivial feature so I may not be able to give an exact timeline when this feature will be implemented.

**Comment by renzbagaporo** [comment]
Hi @chapipo, this feature should be merged to master in a couple of weeks. The commit will automatically close this issue.
