### ISSUE TITLE
esp-idf/examples/bluetooth/bluedroid/classic_bt/hfp_hf   example  (IDFGH-2531)

### ISSUE THREAD

**Issue by ACJ-kor** [espressif/esp-idf#4619]
I execute the 'hfp_hf.' example without any modification but i can't see the log outcome of 'Audio Connection and Disconnection'. Please refer my attachment file!!!
![프레젠테이션1](https://user-images.githubusercontent.com/56374944/72141540-66446e00-33d6-11ea-85f7-1c08b9bc5616.png)

**Comment by AbnerFederer** [comment]
![hf_ag_hf_test](https://user-images.githubusercontent.com/37181020/72148351-89255100-33db-11ea-9930-ba165503d7a9.png)

**Comment by ACJ-kor** [comment]
![프레젠테이션1](https://user-images.githubusercontent.com/56374944/72311728-fcbfaa80-36c8-11ea-9d33-d0ad101f905c.png)

When i modified 'BR/EDR Sync(SCO/eSCO)' in menuconfig 0 into 1 then the following picture appears!!!

But 'handle hex' value didn't print value 181 but  value 180.

What do i add more configuration? and What does the diffierence between two values mean? 

also when smartphone is connected to 'ESP32', can i see two devices are disconnected? can you let me know how to keep connecting between smartphone and ESP32?

Specification :
Board: nodemcu (esp-wroom-32)
version: ESP-IDF master
power: usb

![프레젠테이션1](https://user-images.githubusercontent.com/56374944/72312217-c551fd80-36ca-11ea-9e09-8483d9b526d7.png)

**Comment by AbnerFederer** [comment]
Hi @ACJ-kor ,

1. BR/EDR Max Connection means the number of SCO links at your case.
2. Handle is just a number allocated by HCI from 180, it has no other meaning.
3. We have specific disconnected log with disconnecting reason.

Thanks
Abner

**Comment by Alvin1Zhang** [comment]
@ACJ-kor Thanks for reporting. Feel free to reopen if the issue still happens, or help open another issue for new issues. Thanks.
