### ISSUE TITLE
Mesh implementation using nimBLE host stack (IDFGH-2550)

### ISSUE THREAD

**Issue by AlpinProgrammer** [espressif/esp-idf#4636]
Hello all,

I would like to know more about the status of nimBLE mesh implementations.

We are considering this option to develop the BLE mesh functionality with hard constraints of resources (low RAM) and Bluedroid-based mesh won't fit.

Would you advice using nimBLE stack to implement Mesh ? Are there larger functionalities to be added in esp-idf in the future ?

Thanks in advance for your insights,
Regards.

**Comment by dhrishi** [comment]
Hi @AlpinProgrammer, as of now there are 2 options you can choose from:

1. NimBLE BLE Mesh (part of and maintained by NimBLE upstream code, which works directly in ESP-IDF). See here: https://mynewt.apache.org/latest/network/mesh/index.html#bluetooth-mesh

2. ESP-BLE-Mesh with NimBLE host. Details here: https://docs.espressif.com/projects/esp-idf/en/latest/api-guides/esp-ble-mesh/ble-mesh-index.html

**Comment by Alvin1Zhang** [comment]
Thanks for reporting.

**Comment by AlpinProgrammer** [comment]
Thank you for your help !
