### ISSUE TITLE
Unable to read microphone input from ADC2_6 channel using I2S. (IDFGH-2569)

### ISSUE THREAD

**Issue by ankur2854** [espressif/esp-idf#4654]
I am using ADC2_6 channel to read microphone input using I2S. But from the error log we get to know I2S not support ADC2 unit.
Can anyone help me on it. Is there any way to do read microphone input from ADC2 channels? 

Using esp-idf SDK v4.0
Module - esp32 wroom32D
Microphone connect to physical pin 17.

Thanks in advance.

**Comment by koobest** [comment]
Hi, 
Because ADC2 is used by WIFI, so, we do not provide the support.  The attachment may provide some reference for you.

[i2s_adc_scale.tar.gz](https://github.com/espressif/esp-idf/files/4478960/i2s_adc_scale.tar.gz)

thanks !!

**Comment by Alvin1Zhang** [comment]
@ankur2854 Thanks for reporting, free free to reopen if any updates. Thanks.
