### ISSUE TITLE
GPIO - Interrupt reset  (IDFGH-2589)

### ISSUE THREAD

**Issue by Bach-Danielsson** [espressif/esp-idf#4673]
I use the GPIO for read a sensor.
The sensor (hall sensor) seems to send some glitching signals before coming to a stable state.
I would like to be able to delay the reset of raised interrupt.

Example: I have a rotating machine and each revulotion I get a signal from the Hall sensor. The machine has a maximum speed of 900 rpm.
this gives a frequency of (900/60) 15 Hz (66.6 msec).

To only get one interrupt / revolution I would like to wait 30 msec before resetting the interrupt.
The speed is calculated by using the time between two interrupts.

If this could be a part of the GPIO Interupt setup would be greate.

**Comment by costaud** [comment]
Maybe the simplest way is to disable gpio interrupt by calling gpio_set_intr_type(gpio_num, GPIO_INTR_DISABLE), then task_delay 30 seconds and enabled interrupt again ?

**Comment by Alvin1Zhang** [comment]
@Bach-Danielsson Thanks for reporting, would you please help share if any updates for this issue? Thanks.
