### ISSUE TITLE
Sending Objects Over ESP Mesh example “internal communication” (IDFGH-2594)

### ISSUE THREAD

**Issue by ulahijawi** [espressif/esp-idf#4678]
I am currently testing the ESP Mesh example “internal communication”. Would appreciate it a lot to know the following:
1. What are the valid ways to send more than one object simultaneously over the ESP Mesh in the esp_mesh_p2p_tx_main function?
2. The data.data pointer is assigned with tx_buf of type uint8_t, however, it is correct to send and receive an object by casting its type from and to uint8_t?

Appreciating your response, thank you.

**Comment by dongdong004** [comment]
- The first question:
  - the function `esp_mesh_p2p_tx_main` just tells you how to use `esp_mesh_send`. You can send every objects using `esp_mesh_send` one by one.
  - There are other demos in [esp-mdf](https://github.com/espressif/esp-mdf)
- The second question:
  - `esp_mesh_send` always requires an `uint8_t` buffer, but you could cast other types to and from this.

**Comment by Alvin1Zhang** [comment]
@ulahijawi Thanks for reporting, would you please help share if any updates for the issue? Thanks.
