### ISSUE TITLE
CMake macro with version (IDFGH-2595)

### ISSUE THREAD

**Issue by DiegoActionItem** [espressif/esp-idf#4679]
**Is your feature request related to a problem? Please describe.**

I want build configuration to fail on non tested versions.
 
**Describe the solution you'd like**

A CMake macro to test version and the library version to be available on compile time to the code.

**Describe alternatives you've considered**

Tried using `IDF_VER`  but this is not enough (text is not parsable by the C pre-processor)/

Please give as many details as you can. Include suggestions for useful APIs or interfaces if relevant.

I would like a `find_package(ifd32 3.1.1 required)` and `IDF_VER_MAJOR`, `IDF_VER_MINOR`, `IDF_VER_PATCH` to be available to apps.

**Comment by DiegoActionItem** [comment]
I am missing a CMake macro to lock my build to a specific version (like Qt's `find_package(Qt5Core 5.10 REQUIRED)`. Also, a set of macros to know the exact version on runtime. So we can fail both build, and configuration if the wrong version has been checkedout).

**Comment by igrr** [comment]
@DiegoActionItem these macros are available starting from IDF v4.0 release (the final release is not yet available, latest is v4.0-rc). More information: [compile time macros](https://docs.espressif.com/projects/esp-idf/en/latest/api-reference/system/system.html#sdk-version) and [build system variables](https://docs.espressif.com/projects/esp-idf/en/latest/api-guides/build-system.html#build-project-variables).

**Comment by DiegoActionItem** [comment]
@igrr this solves the compilation part, great.
However - there is no solution to abort configuration. (A workaround is to fail compilation using the macros above, not optimal).

**Comment by igrr** [comment]
Do you mean something like this? (in project CMakeLists.txt):

```cmake
cmake_minimum_required(VERSION 3.5)

include($ENV{IDF_PATH}/tools/cmake/project.cmake)
project(my-project)

if (NOT "${IDF_VERSION_MAJOR}.${IDF_VERSION_MINOR}" STREQUAL "4.1")
message(FATAL_ERROR "This version of IDF is not supported by the project")
endif()
```

**Comment by DiegoActionItem** [comment]
yeap, something like this. Lets iterate (untested, as I am using v3.3.1 yet...)
```
# should be in $ENV{IDF_PATH}/tools/cmake/project.cmake)
macro(idf_minimum_required vmaj vmin vpath)
    if (NOT ${IDF_VERSION_MAJOR} EQUAL ${vmaj})
        message(FATAL_ERROR "This version of IDF is not supported by the project")
    endif()

    if (NOT ${IDF_VERSION_MIN} LESS ${vmin})
        message(FATAL_ERROR "This version of IDF is not supported by the project")
    endif()

    if (NOT ${IDF_VERSION_PATCH} LESS ${vpatch})
        message(FATAL_ERROR "This version of IDF is not supported by the project")
    endif()
endmacro()

# example usage: 
idf_minimum_required(3,1,1)

```

**Comment by igrr** [comment]
Unfortunately these variables have been added in v4.0, so for v3.3 this won't work...

**Comment by igrr** [comment]
Backported to 3.3 release in https://github.com/espressif/esp-idf/commit/ca6b009c268a4802157a316cf82ffb9a4315bbf5#diff-b9547c815b64448fe56edb94865e0ddb.
