### ISSUE TITLE
ULP wakeup + EXT0 wakeup (IDFGH-2597)

### ISSUE THREAD

**Issue by chegewara** [espressif/esp-idf#4681]
Hi, 
i am facing problem now that i cant use ULP and EXT0 wakeup at the same time.
I know this note:
https://github.com/espressif/esp-idf/blob/master/components/esp32/include/esp_sleep.h#L91-L101

but there is no option to use ULP + EXT0 wakeup with REV 2 and higher:
https://github.com/espressif/esp-idf/blob/master/components/esp32/sleep_modes.c#L400-L415

BTW the same situation is with touchpad wakeup + EXT0
https://github.com/espressif/esp-idf/blob/master/components/esp32/include/esp_sleep.h#L112-L128

**Comment by igrr** [comment]
Sorry, the comment was not updated to mention rev 2 and higher. There are no changes in any of the silicon revisions to support the use of ULP/Touch and EXT0 wakeup at the same time.

**Comment by chegewara** [comment]
Thanks.

**Comment by mahesh2000** [comment]
hi, was this ever fixed?
