### ISSUE TITLE
Enable Secure boot and flash encryption fail (IDFGH-2612)

### ISSUE THREAD

**Issue by CJ0104** [espressif/esp-idf#4692]
## Environment

- Development Kit:none
- Module or chip used:  ESP32-WROOM-32D
- IDF version (run ``git describe --tags`` to find it):
![image](https://user-images.githubusercontent.com/53108941/73433986-de240980-4380-11ea-9d55-79a39e0a496e.png)

- Build System:         idf.py
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it):
![image](https://user-images.githubusercontent.com/53108941/73434108-1297c580-4381-11ea-816f-be24f885ce59.png)

- Operating System:     Windows
- (Windows only) environment type: Plain Command Prompt
- Using an IDE?: No
- Power Supply:         USB

## Problem Description
I want to open Secure boot and flash encryption.
But my firmware is write by  Arduino .
So I want to try hello_world example,and add code below 
![image](https://user-images.githubusercontent.com/53108941/73434985-b59d0f00-4382-11ea-9860-e045afe9f5e5.png)

And if I successfully open Secure boot and flash encryption ,
I will try move arduino code to esp-idf.

### Expected Behavior
Successfully open Secure boot and flash encryption
### Actual Behavior
![image](https://user-images.githubusercontent.com/53108941/73435321-5c81ab00-4383-11ea-874a-6b3259bf3999.png)
![image](https://user-images.githubusercontent.com/53108941/73435370-728f6b80-4383-11ea-9e85-ccc819e86237.png)

### Steps to reproduce

1. 
![image](https://user-images.githubusercontent.com/53108941/73435491-b3878000-4383-11ea-88a9-3a9403f7fccc.png)
Change Security features like
![image](https://user-images.githubusercontent.com/53108941/73435662-0bbe8200-4384-11ea-963c-052b0b2b25a4.png)
Save and exit.

2.(not really sure)
run espsecure.py generate_flash_encryption_key my_flash_encryption_key.bin
And  I got
![image](https://user-images.githubusercontent.com/53108941/73436092-cea6bf80-4384-11ea-9fbd-b193591a9446.png)

3.
![image](https://user-images.githubusercontent.com/53108941/73436181-ff86f480-4384-11ea-989e-6257ae09751a.png)
![image](https://user-images.githubusercontent.com/53108941/73436311-3d841880-4385-11ea-8c3b-a9f7ad3f2d6d.png)
![image](https://user-images.githubusercontent.com/53108941/73436399-6a383000-4385-11ea-9487-63f0e76f6282.png)

4.
![image](https://user-images.githubusercontent.com/53108941/73436507-9a7fce80-4385-11ea-98b6-488e886884e8.png)
![image](https://user-images.githubusercontent.com/53108941/73436621-d61a9880-4385-11ea-97c2-6de934cae483.png)
5.
![image](https://user-images.githubusercontent.com/53108941/73436681-f3e7fd80-4385-11ea-8ea2-7b5418517b2c.png)
Restart esp32-wroom-32d
![image](https://user-images.githubusercontent.com/53108941/73436787-1b3eca80-4386-11ea-8328-517b0b7b82ca.png)

PS:
![image](https://user-images.githubusercontent.com/53108941/73445327-690eff00-4395-11ea-8c8a-7c28dd323d8e.png)
![image](https://user-images.githubusercontent.com/53108941/73445345-70cea380-4395-11ea-9118-066737c42218.png)

Conclusion:
Please tell me which step was wrong and how to fix it.
And if I open the  Secure boot and flash encryption,Does the SPIFFS work.
I saw the "SPIFFS mount fails when flash encryption is enabled"
ref:https://github.com/espressif/esp-idf/issues/2001
They say "SPIFFS is not supported when flash encryption is enabled".
Is that true?

**Comment by negativekelvin** [comment]
It says "bootloader not flashed automatically"
