### ISSUE TITLE
Support for using noinit variables in SPIRAM (IDFGH-2621)

### ISSUE THREAD

**Issue by devanlai** [espressif/esp-idf#4700]
**Is your feature request related to a problem? Please describe.**

I have an ESP-WROVER module with 8MB PSRAM, which I use to store large logs and debug traces that would not fit in the internal RAM with `CONFIG_SPIRAM_USE_MALLOC` enabled so that I can allocate buffers from SPIRAM. This works great, except that unlike regular internal memory, there's no way for me to statically allocate them and flag them as `noinit` so that they can be recovered after a software reset.

**Describe the solution you'd like**

It would useful to have an attribute macro like `__NOINIT_ATTR` that would work to place the noinit variable in the SPIRAM. I've done some testing to prove out the idea and I ended up making the following changes:

- Add a new linker script to the `esp32` component that defines a new linker section that is placed in the `extern_ram_seg` segment and provides start and end symbols.
- Add a new macro to `esp_attr.h` to place variables in the above linker section.
- Update `esp_spiram_test()` to skip over addresses that fall within the new SPIRAM noinit section.
- Update `esp_spiram_add_to_heapalloc()` to take into account the end of the new linker section when determining where available memory for the heap starts.

If the Espressif team is open to these kind of changes, I could make a pull request with the specific code.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting and sorry for the very slow turnaround, fix is available https://github.com/espressif/esp-idf/commit/0dad76329f9d8e98c02f478026bbf68f25bf0838, feel free to reopen.
