### ISSUE TITLE
Ignore some of the data received by https_requst (IDFGH-2622)

### ISSUE THREAD

**Issue by DheeranYuvaraj** [espressif/esp-idf#4701]
Hi,

I am trying https_requst example code for receiving json from web server. 
I am able to recive the json, but the received json comes along with some data. 

**Example output:**

HTTP/1.1 200 OK
Date: Sun, 02 Feb 2020 13:22:39 GMT
Server: Apache
Connection: close
Content-Type: text/html; charset=UTF-8
xaxmxjx9x{"i":"am001", "i":"am002", "i":"am003", "i":"am009", "i":"am008"}

Some one advice me how to split json({"i":"am001", "i":"am002", "i":"am003", "i":"am009", "i":"am008"} data from this above output.

**Comment by 0xjakob** [comment]
Hi @DheeranYuvaraj!
You can use cJSON. It's available in the IDF components already. 
I also used the http_request example to extract a json a few weeks ago. You just feed the buffer with the response (`buf`) into cjson.
Unfortunately, we don't have a cjson example (or I can't find it right now).
Hope that helps.

**Comment by 0xjakob** [comment]
OK, I think I missunderstood a bit. So to separate the data, something like `char* json = strstr(buf, "{\"")` could work. This is btw a basic programming question and it not specific for the `esp-idf`. Please consider posting in the forum the next time :)

**Comment by DheeranYuvaraj** [comment]
Hi @0xjakob,

Thanks for the information. closing now.
