### ISSUE TITLE
LEDC to DigitalWrite (IDFGH-2624)

### ISSUE THREAD

**Issue by chrisgotboost** [espressif/esp-idf#4703]
Hello, 
I am trying to reset by "default" a pin status. after been init with LEDC i'm no more able to control via DigitalWrite and vis versa....

void V1_init(){
    ESP_LOGI(TAG, "V1 Init");
    gpio_set_direction(DRIVE, GPIO_MODE_OUTPUT);

    ledc_timer_config(&ledc_timer);
    ledc_channel_config(&ledc_channel[0]);
    ledc_set_duty(ledc_channel[0].speed_mode, ledc_channel[0].channel, 0);
    ledc_update_duty(ledc_channel[0].speed_mode, ledc_channel[0].channel);
}

void V2_init(){
    ESP_LOGI(TAG, "V2 Init");
    ledc_stop(ledc_channel[0].speed_mode, ledc_channel[0].channel, 0);
    gpio_set_direction(DRIVE, GPIO_MODE_OUTPUT);

    pinMode(DRIVE, OUTPUT);    // Output mode to drive relay
    digitalWrite(DRIVE, LOW);  // make sure it is off to start
}

**Comment by koobest** [comment]
Hi, @chrisgotboost 
I don't quite understand what you mean. Can you elaborate on your issue?
thanks !!

**Comment by Alvin1Zhang** [comment]
@chrisgotboost Thanks for reporting, will close due to short of feedback, feel free to reopen with more feedback or details. Thanks.
