### ISSUE TITLE
BLE scan weird rssi values (IDFGH-2626)

### ISSUE THREAD

**Issue by muhambykar** [espressif/esp-idf#4705]
Hi everyone! I am working for a location detect system, the tags which have nrf modules from nordic semiconductor make broadcast 20 messages in one second. ESP32 will work as gateway, scans broadcast values and detect rssi values.  Thanks to rssi values, I want to detect its distance from the gateway. I took reliable rssi values, however sometimes it could be wrong. I have also scans the broadcast with nrf module at the same time, it shows always reliable rssi values. Therefore, this situation is normal for ESP32 modules, or it can be correctible situation? 

My outputs like that:

(41965) Device mac: D0:4C:06:8C:C9:51                   rssi: -33  
(41975) Device mac: D0:4C:06:8C:C9:51                   rssi: -32   
(41981) Device mac: D0:4C:06:8C:C9:51                   rssi: -34    
(41986) Device mac: D0:4C:06:8C:C9:51                   rssi: -33    
(41991) Device mac: D0:4C:06:8C:C9:51                   rssi: -32    
(41996) Device mac: D0:4C:06:8C:C9:51                   rssi: -34    
(42001) Device mac: D0:4C:06:8C:C9:51                   rssi: -94    
 detected !!!!!!!!!!   -94
(42010) Device mac: D0:4C:06:8C:C9:51                   rssi: -33    
(42016) Device mac: D0:4C:06:8C:C9:51                   rssi: -33    
(42026) Device mac: D0:4C:06:8C:C9:51                   rssi: -34    
(42031) Device mac: D0:4C:06:8C:C9:51                   rssi: -33    
(42046) Device mac: D0:4C:06:8C:C9:51                   rssi: -33    
(42056) Device mac: D0:4C:06:8C:C9:51                   rssi: -34    
(42060) Device mac: D0:4C:06:8C:C9:51                   rssi: -32    
(42066) Device mac: D0:4C:06:8C:C9:51                   rssi: -32    
(42071) Device mac: D0:4C:06:8C:C9:51                   rssi: -34   
(42076) Device mac: D0:4C:06:8C:C9:51                   rssi: -33    

the tag at next to the gateway, it gives 32-33-34 values which looks normal. However, sometimes it shows values over 70. 
 I am using lastest version of ESP IDF

**Comment by chegewara** [comment]
![Screenshot_20200204-111000_nRF Connect](https://user-images.githubusercontent.com/1406020/73735170-20fa2e80-473f-11ea-88ad-40f3475a8615.jpg)
Yes, difference between 2 consecutive RSSI readings 60dB looks bad, but it may happen (interference).
As you can see from my picture RSSI fluctuating 20dB is nothing unusual.

**Comment by muhambykar** [comment]
hi @chegewara , thanks for your comment.
I have also scanned with android phone as you did. It did not show weird values as ESP32. As I mentioned, I have also scanned with another NRF Bluetooth module, it also showed reliable values. This is why I asked is there any problem with ESP32 for bluetooth scan.

**Comment by WCCWCC** [comment]
Hi @muhambykar ，
 * At present, ESP32 may have a 2db error when scanning. I have two ways to provide accuracy:

 * A: If you scan a single-channel data packet, the rssi value error will be smaller and will not exceed 1db. For example: Configure the ESP32 device to scan only on channel 37.

 * B: I can provide an interface so that you can know the channel and rssi information of the packet.

**Comment by serenchoe** [comment]
Hi @WCCWCC  Could you please provide any method mentioned above? Either A or B would be of great help.

**Comment by WCCWCC** [comment]
Hi ， @serenchoe 

I need the commit information of the idf you are currently using.

I provide a bt_lib to increase the single-channel scan function.

You only need to replace the bt_lib library.

**Comment by serenchoe** [comment]
Hi @WCCWCC, 

Following is git revision of idf that I'm using now. 
6c17e3a64c02eff3a4f726ce4b7248ce11810833

Thanks

**Comment by serenchoe** [comment]
Hi @WCCWCC 
I'm still waiting for your help.

**Comment by WCCWCC** [comment]
Hi @serenchoe ,
Set the method of scanning only on a single channel.
Need to add the following code:

```c
typedef enum
{
   SCAN_ALL_CHANNEL = 0,
   ONLY_SCAN_CHANNEL_37,
   ONLY_SCAN_CHANNEL_38,
   ONLY_SCAN_CHANNEL_39,
}
scan_mode_config_t;
extern scan_mode_config_t scan_channel_setting(scan_mode_config_t scan_mode);
```

Before calling the API(esp_ble_gap_start_scanning), Call function(scan_channel_setting) to set scan channel.

**Comment by serenchoe** [comment]
Hi @WCCWCC 
It works fine. Thanks a lot!

**Comment by Alvin1Zhang** [comment]
Thanks for reporting and glad it works, feel free to reopen.
