### ISSUE TITLE
VS code internal terminal(cmd.exe) arrow key didn't work!  (IDFGH-2629)

### ISSUE THREAD

**Issue by imliubo** [espressif/esp-idf#4708]
## Environment

- Development Kit:     ESP32-DevKitC
- Kit version (for WroverKit/PicoKit/DevKitC): v4
- IDF version (run ``git describe --tags`` to find it):
    v4.0-rc
- Build System:         idf.py
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it):
    1.22.0-80-g6c4433a
- Operating System:     Windows
- (Windows only) environment type:ESP Command Prompt
- Using an IDE?: VS code
- Power Supply:   USB

## Problem Description

I try compile the projects with VS code(just use for code edit),I use the terminal with VS code internal(cmd.exe), build&flash works well,but the  **menuconfig**  has problem,when I config the projects use **idf.py menuconfig** the arrow key didn't work.

Without VS code internal terminal works well.

### Expected Behavior
When I press ↓ key,the menu can move down. 

### Actual Behavior
![image](https://user-images.githubusercontent.com/26544331/73666787-4a36a280-46de-11ea-8542-e9626bbbe9d9.png)
**Tab** key can move the bottom row menu,and **Enter** key can enter menu.

### setting json
```json
{
    "terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\cmd.exe",
    "terminal.integrated.shellArgs.windows":["/K","D:\\LIUBO\\Desktop\\esp-idf-v4.0\\esp-idf-v4.0-rc\\export.bat"]
}
```

**Comment by igrr** [comment]
Hi @imliubo, I recommend having a look at https://github.com/espressif/vscode-esp-idf-extension, which is a dedicated VS Code extension for ESP-IDF projects. It comes with a configuration editor GUI, which may be easier to use than the command-line mconf window.

The problem related to arrow keys in VS Code terminal has been reported before (https://github.com/espressif/vscode-esp-idf-extension/issues/6), but I'm afraid it is out of scope of IDF to debug these terminal related issues.

**Comment by imliubo** [comment]
@igrr 
Thanks,I didn't notice VS Code extension for ESP-IDF projects.I will try it,tnanks for help me.
Have a nice day!

**Comment by Kusanagi242** [comment]
Use the J & K keys for UP/Down instead
