### ISSUE TITLE
ESP SD card error (IDFGH-2634)

### ISSUE THREAD

**Issue by rebeliousconformist** [espressif/esp-idf#4712]
## Environment

- Development Kit:      [ESP32-Wrover-Kit
- Kit version (for WroverKit: [v4]
- Module or chip used:  ESP32-WROVER-B
- IDF version (run ``git describe --tags`` to find it):v4.1-dev-2055-gf5b82c5b1
- Build System:         [Make
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it):
   xtensa-esp32-elf-gcc (crosstool-NG esp-2019r2) 8.2.0

- Operating System:     |Linux

- Power Supply:         [USB|

## Problem Description

//Detailed problem description goes here.

### Actual Behavior

<pre>
Welcome to minicom 2.7.1

OPTIONS: I18n 
Compiled on Aug 13 2017, 15:25:34.
Port /dev/ttyUSB1, 17:29:28

Press CTRL-A Z for help on special keys

ets Jun  8 2016 00:22:57

rst:0x1 (POWERON_RESET),boot:0x1e (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:4
load:0x3fff0034,len:7104
ho 0 tail 12 room 4
load:0x40078000,len:14864
load:0x40080400,len:4568
entry 0x400806f0
I (31) boot: ESP-IDF v4.1-dev-2055-gf5b82c5b1 2nd stage bootloader
I (31) boot: compile time 15:43:58
I (31) boot: chip revision: 1
I (35) boot_comm: chip revision: 1, min. bootloader chip revision: 0
I (42) boot.esp32: SPI Speed      : 40MHz
I (47) boot.esp32: SPI Mode       : DIO
I (51) boot.esp32: SPI Flash Size : 4MB
I (56) boot: Enabling RNG early entropy source...
I (61) boot: Partition Table:
I (65) boot: ## Label            Usage          Type ST Offset   Length
I (72) boot:  0 nvs              WiFi data        01 02 00009000 00006000
I (80) boot:  1 phy_init         RF data          01 01 0000f000 00001000
I (87) boot:  2 factory          factory app      00 00 00010000 00100000
I (95) boot: End of partition table
I (99) boot_comm: chip revision: 1, min. application chip revision: 0
I (106) esp_image: segment 0: paddr=0x00010020 vaddr=0x3f400020 size=0x099ac ( 39340) map
I (129) esp_image: segment 1: paddr=0x000199d4 vaddr=0x3ffb0000 size=0x021c4 (  8644) load
I (133) esp_image: segment 2: paddr=0x0001bba0 vaddr=0x40080000 size=0x00400 (  1024) load
I (136) esp_image: segment 3: paddr=0x0001bfa8 vaddr=0x40080400 size=0x04070 ( 16496) load
I (152) esp_image: segment 4: paddr=0x00020020 vaddr=0x400d0020 size=0x1fec4 (130756) map
I (200) esp_image: segment 5: paddr=0x0003feec vaddr=0x40084470 size=0x064f4 ( 25844) load
I (218) boot: Loaded app from partition at offset 0x10000
I (218) boot: Disabling RNG early entropy source...
I (219) cpu_start: Pro cpu up.
I (222) cpu_start: Application information:
I (227) cpu_start: Project name:     sd_card
I (232) cpu_start: App version:      1
I (237) cpu_start: Compile time:     Feb  4 2020 15:44:01
I (243) cpu_start: ELF file SHA256:  c40d9c979b394ca8...
I (249) cpu_start: ESP-IDF:          v4.1-dev-2055-gf5b82c5b1
I (255) cpu_start: Starting app cpu, entry point is 0x40081074
I (0) cpu_start: App cpu up.
I (266) heap_init: Initializing. RAM available for dynamic allocation:
I (272) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM
I (278) heap_init: At 3FFB2AE8 len 0002D518 (181 KiB): DRAM
I (285) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM
I (291) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
I (297) heap_init: At 4008A964 len 0001569C (85 KiB): IRAM
I (304) cpu_start: Pro cpu start user code
I (322) spi_flash: detected chip: generic
I (322) spi_flash: flash io: dio
I (323) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.
I (331) example: Initializing SD card
I (331) example: Using SDMMC peripheral
I (341) gpio: GPIO[13]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 
E (561) sdmmc_sd: sdmmc_init_sd_scr: send_scr (1) returned 0x109
E (561) example: Failed to initialize the card (ESP_ERR_INVALID_CRC). Make sure SD card lines have pull-up resistors in place.
</pre>

### Steps to reproduce

flash the program 

// If possible, attach a picture of your setup/wiring here.

### Code to reproduce this issue

```cpp
/* SD card and FAT filesystem example.
   This example code is in the Public Domain (or CC0 licensed, at your option.)

   Unless required by applicable law or agreed to in writing, this
   software is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
   CONDITIONS OF ANY KIND, either express or implied.
*/

#include <stdio.h>
#include <string.h>
#include <sys/unistd.h>
#include <sys/stat.h>
#include "esp_err.h"
#include "esp_log.h"
#include "esp_vfs_fat.h"
#include "driver/sdmmc_host.h"
#include "driver/sdspi_host.h"
#include "sdmmc_cmd.h"

static const char *TAG = "example";

// This example can use SDMMC and SPI peripherals to communicate with SD card.
// By default, SDMMC peripheral is used.
// To enable SPI mode, uncomment the following line:

// #define USE_SPI_MODE

// When testing SD and SPI modes, keep in mind that once the card has been
// initialized in SPI mode, it can not be reinitialized in SD mode without
// toggling power to the card.

#ifdef USE_SPI_MODE
// Pin mapping when using SPI mode.
// With this mapping, SD card can be used both in SPI and 1-line SD mode.
// Note that a pull-up on CS line is required in SD mode.
#define PIN_NUM_MISO 2
#define PIN_NUM_MOSI 15
#define PIN_NUM_CLK  14
#define PIN_NUM_CS   13
#endif //USE_SPI_MODE

void app_main(void)
{
    ESP_LOGI(TAG, "Initializing SD card");

#ifndef USE_SPI_MODE
    ESP_LOGI(TAG, "Using SDMMC peripheral");
    sdmmc_host_t host = SDMMC_HOST_DEFAULT();

    // This initializes the slot without card detect (CD) and write protect (WP) signals.
    // Modify slot_config.gpio_cd and slot_config.gpio_wp if your board has these signals.
    sdmmc_slot_config_t slot_config = SDMMC_SLOT_CONFIG_DEFAULT();

    // To use 1-line SD mode, uncomment the following line:
    // slot_config.width = 1;

    // GPIOs 15, 2, 4, 12, 13 should have external 10k pull-ups.
    // Internal pull-ups are not sufficient. However, enabling internal pull-ups
    // does make a difference some boards, so we do that here.
    gpio_set_pull_mode(15, GPIO_PULLUP_ONLY);   // CMD, needed in 4- and 1- line modes
    gpio_set_pull_mode(2, GPIO_PULLUP_ONLY);    // D0, needed in 4- and 1-line modes
    gpio_set_pull_mode(4, GPIO_PULLUP_ONLY);    // D1, needed in 4-line mode only
    gpio_set_pull_mode(12, GPIO_PULLUP_ONLY);   // D2, needed in 4-line mode only
    gpio_set_pull_mode(13, GPIO_PULLUP_ONLY);   // D3, needed in 4- and 1-line modes

#else
    ESP_LOGI(TAG, "Using SPI peripheral");

    sdmmc_host_t host = SDSPI_HOST_DEFAULT();
    sdspi_slot_config_t slot_config = SDSPI_SLOT_CONFIG_DEFAULT();
    slot_config.gpio_miso = PIN_NUM_MISO;
    slot_config.gpio_mosi = PIN_NUM_MOSI;
    slot_config.gpio_sck  = PIN_NUM_CLK;
    slot_config.gpio_cs   = PIN_NUM_CS;
    // This initializes the slot without card detect (CD) and write protect (WP) signals.
    // Modify slot_config.gpio_cd and slot_config.gpio_wp if your board has these signals.
#endif //USE_SPI_MODE

    // Options for mounting the filesystem.
    // If format_if_mount_failed is set to true, SD card will be partitioned and
    // formatted in case when mounting fails.
    esp_vfs_fat_sdmmc_mount_config_t mount_config = {
        .format_if_mount_failed = false,
        .max_files = 5,
        .allocation_unit_size = 16 * 1024
    };

    // Use settings defined above to initialize SD card and mount FAT filesystem.
    // Note: esp_vfs_fat_sdmmc_mount is an all-in-one convenience function.
    // Please check its source code and implement error recovery when developing
    // production applications.
    sdmmc_card_t* card;
    esp_err_t ret = esp_vfs_fat_sdmmc_mount("/sdcard", &host, &slot_config, &mount_config, &card);

    if (ret != ESP_OK) {
        if (ret == ESP_FAIL) {
            ESP_LOGE(TAG, "Failed to mount filesystem. "
                "If you want the card to be formatted, set format_if_mount_failed = true.");
        } else {
            ESP_LOGE(TAG, "Failed to initialize the card (%s). "
                "Make sure SD card lines have pull-up resistors in place.", esp_err_to_name(ret));
        }
        return;
    }

    // Card has been initialized, print its properties
    sdmmc_card_print_info(stdout, card);

    // Use POSIX and C standard library functions to work with files.
    // First create a file.
    ESP_LOGI(TAG, "Opening file");
    FILE* f = fopen("/sdcard/hello.txt", "w");
    if (f == NULL) {
        ESP_LOGE(TAG, "Failed to open file for writing");
        return;
    }
    fprintf(f, "Hello %s!\n", card->cid.name);
    fclose(f);
    ESP_LOGI(TAG, "File written");

    // Check if destination file exists before renaming
    struct stat st;
    if (stat("/sdcard/foo.txt", &st) == 0) {
        // Delete it if it exists
        unlink("/sdcard/foo.txt");
    }

    // Rename original file
    ESP_LOGI(TAG, "Renaming file");
    if (rename("/sdcard/hello.txt", "/sdcard/foo.txt") != 0) {
        ESP_LOGE(TAG, "Rename failed");
        return;
    }

    // Open renamed file for reading
    ESP_LOGI(TAG, "Reading file");
    f = fopen("/sdcard/foo.txt", "r");
    if (f == NULL) {
        ESP_LOGE(TAG, "Failed to open file for reading");
        return;
    }
    char line[64];
    fgets(line, sizeof(line), f);
    fclose(f);
    // strip newline
    char* pos = strchr(line, '\n');
    if (pos) {
        *pos = '\0';
    }
    ESP_LOGI(TAG, "Read from file: '%s'", line);

    // All done, unmount partition and disable SDMMC or SPI peripheral
    esp_vfs_fat_sdmmc_unmount();
    ESP_LOGI(TAG, "Card unmounted");
}

**Comment by igrr** [comment]
Hi @rebeliousconformist, the `ESP_ERR_INVALID_CRC` error usually indicates a signal integrity issue, or signal level issue, between the ESP32 and the SD card.

Please check the troubleshooting section of the sd_card example, in particular the part about the pull-up resistors, and the part about GPIO12 strapping.

If these tips do not help, please attach the schematics of your PCB.

**Comment by rebeliousconformist** [comment]
![IMG_20200205_102005](https://user-images.githubusercontent.com/49409238/73828238-2ddf5680-4801-11ea-85d8-27afe12b81c2.jpg)

**Comment by rebeliousconformist** [comment]
I'm using the stock, out of the box hardware

**Comment by rebeliousconformist** [comment]
Rx Tx and the Cts Dts jumpers are in place

**Comment by rebeliousconformist** [comment]
I tried using the SPI mode in the SD card example
Here is my prompt

<pre>
rst:0x1 (POWERON_RESET),boot:0x1e (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:4
load:0x3fff0034,len:7208
load:0x40078000,len:14864
ho 0 tail 12 room 4
load:0x40080400,len:4568
entry 0x400806f0
I (31) boot: ESP-IDF v4.1-dev-2055-gf5b82c5b1 2nd stage bootloader
I (31) boot: compile time 16:39:57
I (31) boot: chip revision: 1
I (35) boot_comm: chip revision: 1, min. bootloader chip revision: 0
I (42) boot.esp32: SPI Speed      : 40MHz
I (47) boot.esp32: SPI Mode       : DIO
I (51) boot.esp32: SPI Flash Size : 4MB
I (56) boot: Enabling RNG early entropy source...
I (61) boot: Partition Table:
I (65) boot: ## Label            Usage          Type ST Offset   Length
I (72) boot:  0 nvs              WiFi data        01 02 00009000 00006000
I (80) boot:  1 phy_init         RF data          01 01 0000f000 00001000
I (87) boot:  2 factory          factory app      00 00 00010000 00100000
I (95) boot: End of partition table
I (99) boot_comm: chip revision: 1, min. application chip revision: 0
I (106) esp_image: segment 0: paddr=0x00010020 vaddr=0x3f400020 size=0x09e48 ( 40520) map
I (130) esp_image: segment 1: paddr=0x00019e70 vaddr=0x3ffb0000 size=0x021e4 (  8676) load
I (133) esp_image: segment 2: paddr=0x0001c05c vaddr=0x40080000 size=0x00400 (  1024) load
I (137) esp_image: segment 3: paddr=0x0001c464 vaddr=0x40080400 size=0x03bb4 ( 15284) load
I (152) esp_image: segment 4: paddr=0x00020020 vaddr=0x400d0020 size=0x2040c (132108) map
I (201) esp_image: segment 5: paddr=0x00040434 vaddr=0x40083fb4 size=0x06cf8 ( 27896) load
I (220) boot: Loaded app from partition at offset 0x10000
I (220) boot: Disabling RNG early entropy source...
I (221) cpu_start: Pro cpu up.
I (224) cpu_start: Application information:
I (229) cpu_start: Project name:     sd_card
I (234) cpu_start: App version:      1
I (239) cpu_start: Compile time:     Feb  5 2020 16:39:56
I (245) cpu_start: ELF file SHA256:  c4c27a575b879605...
I (251) cpu_start: ESP-IDF:          v4.1-dev-2055-gf5b82c5b1
I (257) cpu_start: Starting app cpu, entry point is 0x400810b0
I (0) cpu_start: App cpu up.
I (267) heap_init: Initializing. RAM available for dynamic allocation:
I (274) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM
I (280) heap_init: At 3FFB2AB0 len 0002D550 (181 KiB): DRAM
I (287) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM
I (293) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
I (299) heap_init: At 4008ACAC len 00015354 (84 KiB): IRAM
I (306) cpu_start: Pro cpu start user code
I (324) spi_flash: detected chip: generic
I (324) spi_flash: flash io: dio
I (325) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.
I (333) example: Initializing SD card
I (333) example: Using SPI peripheral
I (343) gpio: GPIO[13]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 
I (393) sdspi_transaction: cmd=5, R1 response: command not supported
Name: SL16G
Type: SDHC/SDXC
Speed: 20 MHz
Size: 15193MB
I (613) example: Opening file hello95463
E (613) example: Failed to open file for writing
</pre>

Attached is the project

[sd_card.zip](https://github.com/espressif/esp-idf/files/4160469/sd_card.zip)

**Comment by rebeliousconformist** [comment]
[D.zip](https://github.com/espressif/esp-idf/files/4160792/D.zip)
The SD Card contents

**Comment by igrr** [comment]
@rebeliousconformist Thanks a lot for the extra details! Could you please try removing the RTS/CTS jumpers? They connect RTS/CTS signals of the FT2232H to GPIOs 13/15, which are also used for the SD interface. Since your application is not using the UART hardware flow control, you should be able to disconnect these jumpers.

![Screenshot 2020-02-05 at 19 52 33](https://user-images.githubusercontent.com/4349050/73873112-48412080-4851-11ea-9143-42ebc8664515.png)

**Comment by rebeliousconformist** [comment]
hi, it tried it out its still has the same error.

**Comment by igrr** [comment]
Thanks for trying this out. It seems there is some difference between our setups, either in the dev board (possibly a defect) or in the SD card.

In order to rule out some possible issues related to the board, could you please try running the following program on your dev board, removing the SD card first, and report the results?

https://gist.github.com/igrr/11e900beb5797e8448d674cce0b4c86d

**Comment by rebeliousconformist** [comment]
hi @igrr im on vacation at the monent with unfortunately no access to hardware. I shall get back to you as soon as feasible.

**Comment by rebeliousconformist** [comment]
@igrr  here is the output of the gist above.

<pre>
ets Jun  8 2016 00:22:57

rst:0x1 (POWERON_RESET),boot:0x1e (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:4
load:0x3fff0034,len:6884
load:0x40078000,len:13720
load:0x40080400,len:3920
entry 0x40080680
I (29) boot: ESP-IDF v4.2-dev-662-g06fa9476a 2nd stage bootloader
I (29) boot: compile time 23:38:22
I (29) boot: chip revision: 1
I (33) boot_comm: chip revision: 1, min. bootloader chip revision: 0
I (40) boot.esp32: SPI Speed      : 40MHz
I (45) boot.esp32: SPI Mode       : DIO
I (50) boot.esp32: SPI Flash Size : 4MB
I (54) boot: Enabling RNG early entropy source...
I (60) boot: Partition Table:
I (63) boot: ## Label            Usage          Type ST Offset   Length
I (70) boot:  0 nvs              WiFi data        01 02 00009000 00006000
I (78) boot:  1 phy_init         RF data          01 01 0000f000 00001000
I (85) boot:  2 factory          factory app      00 00 00010000 00100000
I (93) boot: End of partition table
I (97) boot_comm: chip revision: 1, min. application chip revision: 0
I (104) esp_image: segment 0: paddr=0x00010020 vaddr=0x3f400020 size=0x06844 ( 26692) map
I (123) esp_image: segment 1: paddr=0x0001686c vaddr=0x3ffb0000 size=0x02194 (  8596) load
I (127) esp_image: segment 2: paddr=0x00018a08 vaddr=0x40080000 size=0x00400 (  1024) load
I (131) esp_image: segment 3: paddr=0x00018e10 vaddr=0x40080400 size=0x07208 ( 29192) load
I (152) esp_image: segment 4: paddr=0x00020020 vaddr=0x400d0020 size=0x13f70 ( 81776) map
I (184) esp_image: segment 5: paddr=0x00033f98 vaddr=0x40087608 size=0x0238c (  9100) load
I (193) boot: Loaded app from partition at offset 0x10000
I (193) boot: Disabling RNG early entropy source...
I (195) cpu_start: Pro cpu up.
I (199) cpu_start: Application information:
I (204) cpu_start: Project name:     sd_card
I (209) cpu_start: App version:      1
I (213) cpu_start: Compile time:     Mar 14 2020 23:38:27
I (219) cpu_start: ELF file SHA256:  d326b0e6fe380587...
I (225) cpu_start: ESP-IDF:          v4.2-dev-662-g06fa9476a
I (232) cpu_start: Starting app cpu, entry point is 0x4008101c
I (0) cpu_start: App cpu up.
I (242) heap_init: Initializing. RAM available for dynamic allocation:
I (249) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM
I (255) heap_init: At 3FFB2980 len 0002D680 (181 KiB): DRAM
I (261) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM
I (267) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
I (274) heap_init: At 40089994 len 0001666C (89 KiB): IRAM
I (280) cpu_start: Pro cpu start user code
I (298) spi_flash: detected chip: generic
I (299) spi_flash: flash io: dio
I (299) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.
start code from ivan
SD Card I/O check. Make sure the SD card is NOT plugged in!

        **** Checking idle levels ****

PIN 12  D2  0.0V
PIN 13  D3  1.6V
PIN 14 CLK  3.3V
PIN 15 CMD  3.3V
PIN  2  D0  3.3V
PIN  4  D1  3.3V

        **** Checking levels with weak pullup ****

PIN 12  D2  2.3V
PIN 13  D3  1.6V
PIN 14 CLK  3.3V
PIN 15 CMD  3.3V
PIN  2  D0  3.3V
PIN  4  D1  3.3V

        **** Checking pin recovery time ****

PIN 12  D2  10011 cycles
PIN 13  D3  10112 cycles
PIN 14 CLK  154 cycles
PIN 15 CMD  156 cycles
PIN  2  D0  326 cycles
PIN  4  D1  326 cycles

        **** Checking pin recovery time with weak pullup ****

PIN 12  D2  342 cycles
PIN 13  D3  170 cycles
PIN 14 CLK  152 cycles
PIN 15 CMD  170 cycles
PIN  2  D0  324 cycles
PIN  4  D1  152 cycles

        **** Checking pin cross-talk ****

               D2    D3   CLK   CMD    D0    D1   
PIN 12  D2     --   1.6V  3.3V  3.3V  3.3V  3.3V  
PIN 13  D3    0.1V   --   3.3V  3.3V  3.3V  3.3V  
PIN 14 CLK    0.3V  1.6V   --   3.3V  3.3V  3.3V  
PIN 15 CMD    0.4V  1.6V  3.3V   --   3.3V  3.3V  
PIN  2  D0    0.4V  1.6V  3.3V  3.3V   --   3.3V  
PIN  4  D1    0.1V  1.6V  3.3V  3.3V  3.3V   --   

        **** Checking pin cross-talk with weak pull-up ****

               D2    D3   CLK   CMD    D0    D1   
PIN 12  D2     --   1.6V  3.3V  3.3V  3.3V  3.3V  
PIN 13  D3    2.3V   --   3.3V  3.3V  3.3V  3.3V  
PIN 14 CLK    2.3V  1.6V   --   3.3V  3.3V  3.3V  
PIN 15 CMD    2.3V  1.6V  3.3V   --   3.3V  3.3V  
PIN  2  D0    2.3V  1.6V  3.3V  3.3V   --   3.3V  
PIN  4  D1    2.1V  1.6V  3.3V  3.3V  3.3V   -- </pre>

**Comment by igrr** [comment]
Thanks. Unfortunately It doesn't bring us closer to finding the issue, as the output is the same as what I get locally. Could you please try adding jumpers on "MTDI" and "MTCK" pin pairs? This should connect extra pull-up resistors to these pins, possibly resolving the issue.

**Comment by rebeliousconformist** [comment]
Hi Igor, 
the card is working .. I had to reformat it to have bs of 512. They of the partition is msdos. 
Im sorry i just dont know what the issue was.
