### ISSUE TITLE
How to enable secure boot with flash encryption? (Windows10) (IDFGH-2636)

### ISSUE THREAD

**Issue by CJ0104** [espressif/esp-idf#4714]
## Environment

- Development Kit:none
- Module or chip used:  [ESP32-WROOM-32D|ESP32-WROOM-32U
- IDF version : v3.3.1
- Build System:         idf.py
- Compiler version :
xtensa-esp32-elf-gcc (crosstool-NG crosstool-ng-1.22.0-80-g6c4433a5) 5.2.0
- Operating System:     Windows
- (Windows only) environment type: Plain Command Prompt
- Using an IDE: No
- Power Supply:         USB

## Problem Description

I saw the #4124 ,#4078,#3302,and I post the #4692 
I follow these steps,and i has been brake three esp32.
And I follow the 
https://docs.espressif.com/projects/esp-idf/en/latest/security/flash-encryption.html
https://docs.espressif.com/projects/esp-idf/en/latest/security/secure-boot.html
Because no one use windows OS,and the guide separate the secure boot and flash encryption.
Could anyone help me ,I want to enable secure boot with flash encryption.
I still have three esp32 wroom 32u.
### Expected Behavior
 enable secure boot with flash encryption.

**Comment by negativekelvin** [comment]
How to question goes on the forum

Use the docs that match your version 
https://docs.espressif.com/projects/esp-idf/en/v3.3.1/security/flash-encryption.html
