### ISSUE TITLE
Enable Secure Boot csum err:0xfa!=0x72(windows) (IDFGH-2639)

### ISSUE THREAD

**Issue by CJ0104** [espressif/esp-idf#4717]
## Environment

- Development Kit:none
- Module or chip used:  [ESP32-WROOM-32D|ESP32-WROOM-32U
- IDF version : v3.3.1
- Build System:         idf.py
- Compiler version :
xtensa-esp32-elf-gcc (crosstool-NG crosstool-ng-1.22.0-80-g6c4433a5) 5.2.0
- Operating System:     Windows
- (Windows only) environment type: Plain Command Prompt
- Using an IDE: No
- Power Supply:         USB

## Problem Description
I follow the https://docs.espressif.com/projects/esp-idf/en/latest/security/secure-boot.html#secure-boot-reflashable.
When I open the monitor it keep showing the
![image](https://user-images.githubusercontent.com/53108941/73838105-e206ce80-484d-11ea-849c-a34fe55b7150.png)

### Expected Behavior
Secure enable and led will blink.
### Actual Behavior
![image](https://user-images.githubusercontent.com/53108941/73838196-15e1f400-484e-11ea-93ff-61efcef97dcf.png)

### Steps to reproduce
1.idf.py menuconfig 
![image](https://user-images.githubusercontent.com/53108941/73838287-4f1a6400-484e-11ea-976f-e0e67c06845f.png)

2.idf.py build
![image](https://user-images.githubusercontent.com/53108941/73838337-71ac7d00-484e-11ea-96dc-36309edc68d0.png)

3.
Python espefuse.py -p com18 burn_key secure_boot D:/ESP32/esp-idf-v3.3.1/blink/build/bootloader/secure-bootloader-key-256.bin
![image](https://user-images.githubusercontent.com/53108941/73838408-930d6900-484e-11ea-88db-3956989a3e9b.png)

4.
Python esptool.py --chip esp32 -p com18 --baud 460800 --before default_reset --after no_reset write_flash --flash_mode dio --flash_freq 40m --flash_size 2MB  -u 0x1000 D:/ESP32/esp-idf-v3.3.1/blink/build/bootloader/bootloader.bin
![image](https://user-images.githubusercontent.com/53108941/73838536-dcf64f00-484e-11ea-9a63-0e21f8a08777.png)

5.
Python esptool.py --chip esp32 -p com18 --baud 460800  --before default_reset --after no_reset write_flash --flash_mode dio --flash_freq 40m --flash_size 2MB  -u 0x0 D:/ESP32/esp-idf-v3.3.1/blink/build/bootloader/bootloader-reflash-digest.bin
![image](https://user-images.githubusercontent.com/53108941/73838579-f1d2e280-484e-11ea-99c1-03e2dbbcefba.png)

6.idf.py flash
![image](https://user-images.githubusercontent.com/53108941/73838634-129b3800-484f-11ea-8680-c042c738afd1.png)

7.idf.py monitor
![image](https://user-images.githubusercontent.com/53108941/73838661-28106200-484f-11ea-9c85-178fed3f5376.png)

PS:python espefuse.py -p com18 summary
![image](https://user-images.githubusercontent.com/53108941/73838975-dddbb080-484f-11ea-9f0e-451e16945ecb.png)
![image](https://user-images.githubusercontent.com/53108941/73839009-eb913600-484f-11ea-8cb2-3bd8d0ebfaa6.png)

### Code to reproduce this issue
![image](https://user-images.githubusercontent.com/53108941/73838740-59892d80-484f-11ea-8bc1-6fcfab519fb3.png)

Please tell me which step I miss or wrong.
I also want to enable the flash encryption ,so what should I do next.
Sorry for bother

**Comment by negativekelvin** [comment]
https://docs.espressif.com/projects/esp-idf/en/v3.3.1/security/secure-boot.html#bootloader-size

**Comment by CJ0104** [comment]
hi @negativekelvin  thank you ,I follow the docs and change like this
![image](https://user-images.githubusercontent.com/53108941/73918195-1769f580-48fc-11ea-82ad-6337bf114ebb.png)
And
![image](https://user-images.githubusercontent.com/53108941/73918219-23ee4e00-48fc-11ea-9ee8-11099c33bb71.png)
Then ,It's work!! 
Thank you so much.
But now I want to enable the flash encryption too,Below it's my action.
I follow the https://docs.espressif.com/projects/esp-idf/en/v3.3.1/security/flash-encryption.html
---------------------------------------------------------------------------------------
1.python espefuse.py -p com18 summary
![image](https://user-images.githubusercontent.com/53108941/73918794-42087e00-48fd-11ea-9e07-c34ef534327e.png)
Secure boot is enable.

And I change code like this
![image](https://user-images.githubusercontent.com/53108941/73921028-885fdc00-4901-11ea-8769-922939e79330.png)


2.
docs said:
![image](https://user-images.githubusercontent.com/53108941/73919290-379ab400-48fe-11ea-9b46-51e257a89916.png)
My action:
![image](https://user-images.githubusercontent.com/53108941/73919341-4e410b00-48fe-11ea-8e22-1eff9d9416f9.png)
3.
idf.py build
![image](https://user-images.githubusercontent.com/53108941/73920243-f60b0880-48ff-11ea-89e6-c6dd948ee302.png)

4.re-flash bootloader
`Python esptool.py --chip esp32 -p com18 --baud 460800 --before default_reset --after no_reset write_flash --flash_mode dio --flash_freq 40m --flash_size 2MB -u 0x0 D:/ESP32/esp-idf-v3.3.1/blink/build/bootloader/bootloader-reflash-digest.bin
`
![image](https://user-images.githubusercontent.com/53108941/73920424-51d59180-4900-11ea-8e03-bab68e4b9fd0.png)

5.idf.py flash monitor
![image](https://user-images.githubusercontent.com/53108941/73921093-b0e7d600-4901-11ea-9a06-54c6d35ae8ae.png)
And the first time restart the esp32 will take about 30 second to 1 minutes.

Thank you @negativekelvin .

**Comment by CJ0104** [comment]
hi @negativekelvin  sorry for bother again.
I sudden run idf.py flash again.
Then the monitor print
![image](https://user-images.githubusercontent.com/53108941/73932230-e21dd180-4914-11ea-9855-0b2dcad941d9.png)
And my summary 
![image](https://user-images.githubusercontent.com/53108941/73932270-f4980b00-4914-11ea-89be-75d45de77a23.png)
![image](https://user-images.githubusercontent.com/53108941/73932287-fc57af80-4914-11ea-91b5-73d1bb6eb0d6.png)

I saw the 
![image](https://user-images.githubusercontent.com/53108941/73932401-33c65c00-4915-11ea-8376-461c58ce1ee8.png)
It's mean Flash encryption mode counter Read Only Right?
So this esp32 was broken Am I right?

**Comment by negativekelvin** [comment]
Yes

**Comment by arunmagesh** [comment]
Hi @CJ0104   
Did you found any fix for the flash read err, 1000. 

I have the same issue. It worked once and I reflashed it and same error and ever since it won't accept even the signed&flash encrypted binary.

**Comment by CJ0104** [comment]
Hi @arunmagesh .
If your esp32 have been encrypted,you can't flash any firmware into that esp32.
If your did the esp32 will broken and keep showing "flash read err, 1000".

And if you didn't flash any encrypted firmware into esp32,please check other issue .
There are a lot of issue about "flash read err, 1000" in this github.
Thank you and sorry about my poor english.
Best regard
