### ISSUE TITLE
Can we enable deep sleep of two rtc gpio pins of ext 0 in esp-idf (IDFGH-2645)

### ISSUE THREAD

**Issue by manojsai17** [espressif/esp-idf#4722]

**Comment by manojsai17** [comment]
Can we enable deep sleep on two rtc gpio pins using  ext 0 in esp-idf .

**Comment by igrr** [comment]
No, EXT0 can provide wakeup on on pin only. Please check if EXT1 wakeup condition can fit your requirement, or you can combine EXT0 and EXT1.

**Comment by Alvin1Zhang** [comment]
@igrr Thanks for the notes. @manojsai17 Thanks for reporting. Feel free to reopen with more details, you could follow some templates [here](https://github.com/espressif/esp-idf/issues/new/choose). Thanks.
