### ISSUE TITLE
downloaded image validation fails when debugger is attached (IDFGH-2660)

### ISSUE THREAD

**Issue by sinope-db** [espressif/esp-idf#4734]
## Environment

- Development Kit:      none
- Module or chip used:  ESP32-WROVER
- IDF version (run ``git describe --tags`` to find it): v3.2.3
- Build System:         Make
- Compiler version : 1.22.0-80-g6c4433a5
- Operating System:     Windows
- (Windows only) environment type: [MSYS2 mingw32|ESP Command Prompt|Plain Command Prompt|PowerShell].
- Using an IDE?: VisualGDB

## Problem Description

I've enabled CONFIG_SECURE_SIGNED_ON_UPDATE_NO_SECURE_BOOT in my project and when I download a firmware image (OTA) with the debugger running, the image fails validation.

The same image with the debugger removed pass.

I'm using esp_ota_begin(), esp_ota_write()  and esp_ota_end() to store the image in flash.

I think the issue is that in image_load(), verify_checksum() is skipped when debugger is attached and it does not adjust image length for the proper offset of the hash / signature.

https://github.com/espressif/esp-idf/blob/ca1e5e5bc52182a577f1706c8dcbb4d9d7afe310/components/bootloader_support/src/esp_image_format.c#L179

Possible fix:
```cpp
// in image_load() alway call checksum validation, but skip error check if debugger is attached
    err = verify_checksum(sha_handle, checksum_word, data);
    if ((err != ESP_OK) && !esp_cpu_in_ocd_debug_mode()) {
        goto err;
    }
```

### Expected Behavior

Image validation can be run with debugger attached

### Actual Behavior

Image validation fails with debugger attached

### Steps to reproduce

1. Enable CONFIG_SECURE_SIGNED_ON_UPDATE_NO_SECURE_BOOT
2. Run project with JTAG debugger
3. Download a valid signed image (verified by esptool.py image_info)

## Debug Logs

```
I (188887) esp_image: segment 0: paddr=0x00800020 vaddr=0x3f400020 size=0x3e218 (254488) map
I (189107) esp_image: segment 1: paddr=0x0083e240 vaddr=0x3ffb0000 size=0x01dd0 (  7632) 
I (189137) esp_image: segment 2: paddr=0x00840018 vaddr=0x400d0018 size=0x1035d8 (1062360) map
I (190007) esp_image: segment 3: paddr=0x009435f8 vaddr=0x3ffb1dd0 size=0x01738 (  5944) 
I (190027) esp_image: segment 4: paddr=0x00944d38 vaddr=0x40080000 size=0x00400 (  1024) 
I (190057) esp_image: segment 5: paddr=0x00945140 vaddr=0x40080400 size=0x1706c ( 94316) 
I (190147) esp_image: segment 6: paddr=0x0095c1b4 vaddr=0x400c0000 size=0x0006c (   108) 
I (190177) esp_image: segment 7: paddr=0x0095c228 vaddr=0x50000000 size=0x00014 (    20) 
I (190197) esp_image: Verifying image signature...
E (190227) secure_boot: image has invalid signature version field 0x04000000  <-- this is the image checksum
E (190237) esp_image: Secure boot signature verification failed
I (190247) esp_image: Calculating simple hash to check for corruption...
E (191337) esp_image: Image hash failed - image is corrupt
W (191347) esp_image: image corrupted on flash
W (191367) httpd: Firmware upload failed! (3)
```

**Comment by projectgus** [comment]
Hi @sinope-db ,

I'm very sorry that noone got back to you about this issue in Feb. 

The underlying problem is that openocd creates "software breakpoints" by writing to flash, and modifying the flash causes the signature check to break.

We've documented this limitation in 4358f3b, but we also plan to update the bootloader so that signature checks are skipped if JTAG is left enabled and is attached (as physical security is not possible in this configuration anyhow). We'll update this issue once that support is available.

Angus
