### ISSUE TITLE
Compilation error of mconf-idf (make menuconfig) (IDFGH-2667)

### ISSUE THREAD

**Issue by luquinhas98** [espressif/esp-idf#4741]
Making menuconfig on the hello_world project gives me this strange error. I have tried to make clean the tools/kconfig directory and get the same. I'm running the command on 32-bit MSYS2.

> $ make menuconfig
> 
> make[1]: Entering directory '/home/lucas/esp/esp-idf/tools/kconfig'
> /usr/bin/gcc -c  -I/usr/include/ncursesw -DCURSES_LOC="<curses.h>"  -DNCURSES_WIDECHAR=1 -DLOCALE -MMD -MP -I "." -I "/home/lucas/e       sp/esp-idf/tools/kconfig"  /home/lucas/esp/esp-idf/tools/kconfig/mconf.c -o mconf.o
> flex -L -Pzconf -ozconf.lex.c /home/lucas/esp/esp-idf/tools/kconfig/zconf.l
> bison -t -l -p zconf -o zconf.tab.c /home/lucas/esp/esp-idf/tools/kconfig/zconf.y
> sed -E "s/\\x0D$//" /home/lucas/esp/esp-idf/tools/kconfig/zconf.gperf | gperf -t --output-file zconf.hash.c -a -C -E -g -k '1,3,$'        -p -t
> /usr/bin/gcc -I /home/lucas/esp/esp-idf/tools/kconfig -c  -I/usr/include/ncursesw -DCURSES_LOC="<curses.h>"  -DNCURSES_WIDECHAR=1 -       DLOCALE -MMD -MP -I "." -I "/home/lucas/esp/esp-idf/tools/kconfig"  zconf.tab.c -o zconf.tab.o
> In file included from zconf.tab.c:2457:0:
> zconf.lex.c:853:2: error: expected identifier or ‘(’ before ‘do’
>         49,   49,   49,   49,   49,   49,   49,   49,   49,   49
>   ^
> zconf.lex.c:873:2: error: expected identifier or ‘(’ before ‘while’
>         11,  -52,  -52,  -52,  -52,  -52,  -52,  -52,  -52,  -52,
>   ^
> zconf.lex.c:1033:27: error: expected identifier or ‘(’ before ‘?’ token
>         12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
>                            ^
> zconf.lex.c:1123:2: error: expected identifier or ‘(’ before ‘{’ token
>   }
>   ^
> zconf.lex.c:1141:2: error: expected identifier or ‘(’ before ‘{’ token
> 
>   ^
> zconf.lex.c:1993:2: warning: data definition has no type or storage class
>   int yy_is_jam;
>   ^
> In file included from zconf.tab.c:2457:0:
> zconf.lex.c:49:16: warning: type defaults to ‘int’ in declaration of ‘zconftext’ [-Wimplicit-int]
>  #endif
>                 ^
> zconf.lex.c:1195:20: note: in expansion of macro ‘yytext’
> 
>                     ^
> zconf.lex.c:1993:3: note: in expansion of macro ‘yytext_ptr’
>   int yy_is_jam;
>    ^~~~~~~~~~
> zconf.lex.c:49:16: error: conflicting types for ‘zconftext’
>  #endif
>                 ^
> zconf.lex.c:1195:20: note: in expansion of macro ‘yytext’
> 
>                     ^
> zconf.lex.c:1993:3: note: in expansion of macro ‘yytext_ptr’
>   int yy_is_jam;
>    ^~~~~~~~~~
> zconf.lex.c:49:16: note: previous declaration of ‘zconftext’ was here
>  #endif
>                 ^
> zconf.lex.c:1187:14: note: in expansion of macro ‘yytext’
> 
>               ^
> In file included from zconf.tab.c:2457:0:
> zconf.lex.c:1993:17: error: ‘yy_bp’ undeclared here (not in a function)
>   int yy_is_jam;
>                  ^
> In file included from zconf.tab.c:2457:0:
> zconf.lex.c:39:16: warning: data definition has no type or storage class
>  #ifdef yy_create_buffer
>                 ^
> zconf.lex.c:1995:2: note: in expansion of macro ‘yyleng’
> 
>   ^
> zconf.lex.c:39:16: warning: type defaults to ‘int’ in declaration of ‘zconfleng’ [-Wimplicit-int]
>  #ifdef yy_create_buffer
>                 ^
> zconf.lex.c:1995:2: note: in expansion of macro ‘yyleng’
> 
>   ^
> In file included from zconf.tab.c:2457:0:
> zconf.lex.c:1995:18: error: ‘yy_cp’ undeclared here (not in a function)
> 
>                   ^
> zconf.lex.c:1997:2: warning: data definition has no type or storage class
>   yy_is_jam = (yy_current_state <= 0);
>   ^
> zconf.lex.c:1997:3: warning: type defaults to ‘int’ in declaration of ‘yy_hold_char’ [-Wimplicit-int]
>   yy_is_jam = (yy_current_state <= 0);
>    ^~~~~~~~~~~~
> zconf.lex.c:1999:2: warning: data definition has no type or storage class
>   if ( ! yy_is_jam )
>   ^
> zconf.lex.c:1999:3: warning: type defaults to ‘int’ in declaration of ‘yy_cp’ [-Wimplicit-int]
>   if ( ! yy_is_jam )
>    ^~~~~
> zconf.lex.c:2001:2: warning: data definition has no type or storage class
>    if ( yy_accept[yy_current_state] )
>   ^
> zconf.lex.c:2001:3: warning: type defaults to ‘int’ in declaration of ‘yy_c_buf_p’ [-Wimplicit-int]
>    if ( yy_accept[yy_current_state] )
>    ^~~~~~~~~~
> zconf.lex.c:2001:3: error: conflicting types for ‘yy_c_buf_p’
> zconf.lex.c:1059:14: note: previous definition of ‘yy_c_buf_p’ was here
> 
>               ^~~~~~~~~~
> zconf.lex.c:2001:17: warning: initialization makes integer from pointer without a cast [-Wint-conversion]
>    if ( yy_accept[yy_current_state] )
>                  ^~~~~
> zconf.lex.c:2001:17: error: initializer element is not constant
> In file included from zconf.tab.c:2457:0:
> zconf.lex.c:2499:2: error: function ‘__errno’ is initialized like a variable
> 
>   ^~~~~
> zconf.lex.c:2501:2: error: expected identifier or ‘(’ before ‘while’
> 
>   ^
> zconf.lex.c: In function ‘zconflex’:
> zconf.lex.c:2671:30: error: expected ‘)’ before ‘{’ token
>    */
>                               ^
> zconf.lex.c:2685:3: error: expected expression before ‘}’ token
>   last_ts = first_ts = 0;
>    ^
> zconf.lex.c:2703:9: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
>  FILE *zconf_fopen(const char *name)
>          ^
> In file included from zconf.tab.c:2457:0:
> zconf.lex.c:2831:14: error: subscripted value is neither array nor pointer nor vector
> zconf.lex.c:875:27: note: in definition of macro ‘unput’
>      },
>                            ^
> zconf.lex.c:875:30: warning: passing argument 2 of ‘yyunput’ makes pointer from integer without a cast [-Wint-conversion]
>      },
>                               ^
> zconf.lex.c:2831:2: note: in expansion of macro ‘unput’
> In file included from zconf.tab.c:2457:0:
> zconf.lex.c:2411:17: note: expected ‘char *’ but argument is of type ‘int’
>   b->yy_is_our_buffer = 0;
>                  ^~~~~~~
> In file included from zconf.tab.c:2457:0:
> zconf.lex.c:49:16: warning: passing argument 1 of ‘kconf_id_lookup’ makes pointer from integer without a cast [-Wint-conversion]
>  #endif
>                 ^
> zconf.lex.c:2847:47: note: in expansion of macro ‘yytext’
> In file included from zconf.tab.c:213:0:
> zconf.hash.c:164:1: note: expected ‘const char *’ but argument is of type ‘int’
>  kconf_id_lookup (register const char *str, register size_t len)
>  ^~~~~~~~~~~~~~~
> In file included from zconf.tab.c:2457:0:
> zconf.lex.c:49:16: warning: passing argument 1 of ‘alloc_string’ makes pointer from integer without a cast [-Wint-conversion]
>  #endif
>                 ^
> zconf.lex.c:2863:16: note: in expansion of macro ‘yytext’
> In file included from zconf.tab.c:2457:0:
> zconf.lex.c:2257:13: note: expected ‘const char *’ but argument is of type ‘int’
>      }
>              ^
> zconf.lex.c:2877:24: error: invalid type argument of unary ‘*’ (have ‘int’)
> zconf.lex.c:2995:15: error: subscripted value is neither array nor pointer nor vector
> In file included from zconf.tab.c:2457:0:
> zconf.lex.c:49:16: warning: passing argument 1 of ‘kconf_id_lookup’ makes pointer from integer without a cast [-Wint-conversion]
>  #endif
>                 ^
> zconf.lex.c:3021:47: note: in expansion of macro ‘yytext’
> In file included from zconf.tab.c:213:0:
> zconf.hash.c:164:1: note: expected ‘const char *’ but argument is of type ‘int’
>  kconf_id_lookup (register const char *str, register size_t len)
>  ^~~~~~~~~~~~~~~
> In file included from zconf.tab.c:2457:0:
> zconf.lex.c:49:16: warning: passing argument 1 of ‘alloc_string’ makes pointer from integer without a cast [-Wint-conversion]
>  #endif
>                 ^
> zconf.lex.c:3031:16: note: in expansion of macro ‘yytext’
> In file included from zconf.tab.c:2457:0:
> zconf.lex.c:2257:13: note: expected ‘const char *’ but argument is of type ‘int’
>      }
>              ^
> zconf.lex.c:3071:24: error: invalid type argument of unary ‘*’ (have ‘int’)
> zconf.lex.c:3095:14: warning: assignment makes integer from pointer without a cast [-Wint-conversion]
> In file included from zconf.tab.c:2457:0:
> zconf.lex.c:49:16: warning: passing argument 1 of ‘append_string’ makes pointer from integer without a cast [-Wint-conversion]
>  #endif
>                 ^
> zconf.lex.c:3103:17: note: in expansion of macro ‘yytext’
> In file included from zconf.tab.c:2457:0:
> zconf.lex.c:2229:13: note: expected ‘const char *’ but argument is of type ‘int’
> 
>              ^
> In file included from zconf.tab.c:2457:0:
> zconf.lex.c:49:16: warning: passing argument 1 of ‘append_string’ makes pointer from integer without a cast [-Wint-conversion]
>  #endif
>                 ^
> zconf.lex.c:3119:17: note: in expansion of macro ‘yytext’
> In file included from zconf.tab.c:2457:0:
> zconf.lex.c:2229:13: note: expected ‘const char *’ but argument is of type ‘int’
> 
>              ^
> zconf.lex.c:3133:14: warning: assignment makes integer from pointer without a cast [-Wint-conversion]
> In file included from zconf.tab.c:2457:0:
> zconf.lex.c:49:16: warning: passing argument 1 of ‘append_string’ makes pointer from integer without a cast [-Wint-conversion]
>  #endif
>                 ^
> zconf.lex.c:3141:17: note: in expansion of macro ‘yytext’
> In file included from zconf.tab.c:2457:0:
> zconf.lex.c:2229:13: note: expected ‘const char *’ but argument is of type ‘int’
> 
>              ^
> In file included from zconf.tab.c:2457:0:
> zconf.lex.c:49:16: warning: passing argument 1 of ‘append_string’ makes pointer from integer without a cast [-Wint-conversion]
>  #endif
>                 ^
> zconf.lex.c:3157:17: note: in expansion of macro ‘yytext’
> In file included from zconf.tab.c:2457:0:
> zconf.lex.c:2229:13: note: expected ‘const char *’ but argument is of type ‘int’
> 
>              ^
> zconf.lex.c:3169:20: error: subscripted value is neither array nor pointer nor vector
> In file included from zconf.tab.c:2457:0:
> zconf.lex.c:49:16: warning: passing argument 1 of ‘append_string’ makes pointer from integer without a cast [-Wint-conversion]
>  #endif
>                 ^
> zconf.lex.c:3179:18: note: in expansion of macro ‘yytext’
> In file included from zconf.tab.c:2457:0:
> zconf.lex.c:2229:13: note: expected ‘const char *’ but argument is of type ‘int’
> 
>              ^
> zconf.lex.c:3227:14: error: subscripted value is neither array nor pointer nor vector
> zconf.lex.c:3275:14: warning: assignment makes integer from pointer without a cast [-Wint-conversion]
> zconf.lex.c:3317:15: error: subscripted value is neither array nor pointer nor vector
> zconf.lex.c:3317:44: error: subscripted value is neither array nor pointer nor vector
> In file included from zconf.tab.c:2457:0:
> zconf.lex.c:49:16: warning: passing argument 1 of ‘append_string’ makes pointer from integer without a cast [-Wint-conversion]
>  #endif
>                 ^
> zconf.lex.c:3325:17: note: in expansion of macro ‘yytext’
> In file included from zconf.tab.c:2457:0:
> zconf.lex.c:2229:13: note: expected ‘const char *’ but argument is of type ‘int’
> 
>              ^
> In file included from zconf.tab.c:2457:0:
> zconf.lex.c:49:16: warning: passing argument 1 of ‘fwrite’ makes pointer from integer without a cast [-Wint-conversion]
>  #endif
>                 ^
> zconf.lex.c:2483:31: note: in expansion of macro ‘yytext’
>  }
>                                ^
> zconf.lex.c:3375:1: note: in expansion of macro ‘ECHO’
> In file included from /usr/include/ctype.h:4:0,
>                  from zconf.tab.c:80:
> /usr/include/stdio.h:224:8: note: expected ‘const void * restrict’ but argument is of type ‘int’
>  size_t _EXFUN(fwrite, (const _PTR __restrict , size_t _size, size_t _n, FILE *));
>         ^
> In file included from zconf.tab.c:2457:0:
> zconf.lex.c:3399:32: error: dereferencing pointer to incomplete type ‘struct yy_buffer_state’
> zconf.lex.c:3483:10: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
> zconf.lex.c:3493:11: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
> zconf.lex.c:3507:11: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
> zconf.lex.c:3591:11: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
> zconf.lex.c:3593:11: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
> zconf.lex.c:3611:11: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
> zconf.lex.c:3613:11: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
> zconf.lex.c: In function ‘yy_get_next_buffer’:
> zconf.lex.c:3661:17: warning: initialization makes pointer from integer without a cast [-Wint-conversion]
> zconf.lex.c: In function ‘yy_get_previous_state’:
> zconf.lex.c:3945:14: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
> zconf.lex.c:3945:50: warning: comparison between pointer and integer
> zconf.lex.c: In function ‘yy_try_NUL_trans’:
> zconf.lex.c:3987:20: warning: initialization makes pointer from integer without a cast [-Wint-conversion]
> zconf.lex.c: In function ‘yyunput’:
> zconf.lex.c:4033:11: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
> zconf.lex.c:4089:15: warning: assignment makes integer from pointer without a cast [-Wint-conversion]
> zconf.lex.c:4093:15: warning: assignment makes integer from pointer without a cast [-Wint-conversion]
> zconf.lex.c: In function ‘zconfrestart’:
> zconf.lex.c:4267:28: error: expected ‘)’ before ‘{’ token
> zconf.tab.c:2463:0: error: expected declaration or statement at end of input
> In file included from zconf.tab.c:2457:0:
> zconf.tab.c: At top level:
> zconf.lex.c:1981:24: warning: ‘yy_fatal_error’ used but never defined
>    }
>                         ^
> In file included from zconf.tab.c:2457:0:
> zconf.lex.c:2207:13: warning: ‘zconf_endhelp’ used but never defined
> 
>              ^~~~~~~~~~~
> zconf.lex.c:2209:13: warning: ‘zconf_endfile’ used but never defined
> 
>              ^
> make[1]: *** [Makefile:179: zconf.tab.o] Error 1
> make[1]: Leaving directory '/home/lucas/esp/esp-idf/tools/kconfig'
> make: *** No rule to make target '/home/lucas/esp/esp-idf/tools/kconfig/conf-idf', needed by '/home/lucas/esp/esp-idf/tools/kconfig       /mconf-idf'.  Stop.
> )

**Comment by dobairoland** [comment]
Hi @luquinhas98. Please give us more information about your system: ESP-IDF version, OS name and version, and the outputs of `flex --version` and `bison --version`.

Please try `make -C /home/lucas/esp/esp-idf/tools/kconfig clean` and see if it helps.

**Comment by dobairoland** [comment]
Hi @luquinhas98. Are you still experiencing this problem?

You can also try the ZIP-ed MSYS environment where everything should work:
https://docs.espressif.com/projects/esp-idf/en/latest/get-started-legacy/windows-setup.html#toolchain-setup (for v4.0 or later versions)

**Comment by luquinhas98** [comment]
Hello, I tried the prepackaged MSYS environment and everything works now. Thank you.
