### ISSUE TITLE
Problem with special characters in sdkconfig.cmake (IDFGH-2677)

### ISSUE THREAD

**Issue by harryzz** [espressif/esp-idf#4751]
Hi
version: ESP-IDF v4.1-dev-1935-g647cb628a-dirty

In my case CONFIG_EXAMPLE_WIFI_PASSWORD has a symbol: " (quotation mark).
With idf.py menuconfig  symbol is correct escaped in $projectdir/sdkconfig file.
But in $projectdir/build/config/sdkconfig.cmake file the special character is not escaped and cmake failed.

br
Zahari

**Comment by dobairoland** [comment]
Thank you for reporting this.
