### ISSUE TITLE
[TW#11596] i2c_master_end(cmd) needed?

### ISSUE THREAD

**Issue by Jorgen-VikingGod** [espressif/esp-idf#476]
Hi we have the method i2c_master_stop(cmd) to finish our command.
But in some situations it would be great to have something like i2c_master_end(cmd):

```
esp_err_t i2c_master_end(i2c_cmd_handle_t cmd_handle)
{
    I2C_CHECK(cmd_handle != NULL, I2C_CMD_LINK_INIT_ERR_STR, ESP_ERR_INVALID_ARG);
    i2c_cmd_t cmd;
    cmd.ack_en = 0;
    cmd.ack_exp = 0;
    cmd.ack_val = 0;
    cmd.byte_num = 0;
    cmd.data = NULL;
    cmd.op_code = I2C_CMD_END;
    return i2c_cmd_link_append(cmd_handle, &cmd);
}
```

I have a scenario where I want to write one byte to slave (register address) and read after this write the data back. (like: write 0x30 to slave 0x10. than read back 11 bytes)
The 0x30 is the internal slave data register address (in my case the geginning of "deviceID") - so the slave will move the pointer to that offset. And on read request it will send 11 bytes back to master.

I used before the ArduinoESP32 and there is a way to hand over "sendStop" flag - which is exactly the same as  ```cmd.op_code = I2C_CMD_END```

So my question is - is this method i2c_master_end needed, or how is it done in ESP32 IDF?

Thx and cheers, 
Jorgen

**Comment by costaud** [comment]
I think it is done already in IDF driver, you may refer to the I2C example that read data from a sensor slave.
