### ISSUE TITLE
RMT interrupt status functions missing 0x (IDFGH-2689)

### ISSUE THREAD

**Issue by stevepenrhiw** [espressif/esp-idf#4760]
Hi

In rmt_ll.h from line 224. The "rmt_ll_get*interrupt_status" functions are missing "0x" from the seventh term mask.

Steve

**Comment by negativekelvin** [comment]
https://github.com/espressif/esp-idf/blob/605da33c3d4fa93c6c98da2622f053ecbe5cfbf4/components/soc/src/esp32/include/hal/rmt_ll.h#L224-L243

**Comment by suda-morris** [comment]
Thanks @stevepenrhiw @negativekelvin  for reporting, will fix it ASAP
