### ISSUE TITLE
ULP instruction REG_WR description (IDFGH-2705)

### ISSUE THREAD

**Issue by boarchuz** [espressif/esp-idf#4776]
https://github.com/espressif/esp-idf/blob/master/docs/en/api-guides/ulp_instruction_set.rst#reg_wr--write-to-peripheral-register
The description for REG_WR is currently:
"The instruction writes up to 8 bits **from a general purpose register** into a peripheral register."

However, it is (unfortunately) impossible to write to a peripheral register from a general purpose register. It should convey something more like  "... up to 8 bits from [the provided]/[an immediate] value ... " instead.

**Comment by boarchuz** [comment]
This is also in the TRM. I realise that this is probably not the right place for documentation feedback but it was unclear how to report this through that link.

**Comment by krzychb** [comment]
Hi @boarchuz, thank you for reporting this issue!
