### ISSUE TITLE
How to transmit NULL character through uart in esp32 (IDFGH-2733)

### ISSUE THREAD

**Issue by manojsai17** [espressif/esp-idf#4802]

**Comment by Alvin1Zhang** [comment]
Thanks for reporting. Would you please help provide more details as suggested in the [issue template](https://github.com/espressif/esp-idf/issues/new/choose)? Information like elf, sdk configuration, backtrace, log outputs, commit ID, hardware and etc. would help us debug further. Thanks. @manojsai17
