### ISSUE TITLE
How to transmit NULL character through uart in esp-idf 3.3 (IDFGH-2735)

### ISSUE THREAD

**Issue by manojsai17** [espressif/esp-idf#4803]
How to transmit NULL(0x00) character through uart in esp-idf 3.3  .
I need to pass a string which contains NULL in middle of strings  .

**Comment by koobest** [comment]
Hi, @manojsai17 

`uart_write_bytes`  can transmit NULL character ,Have you tried？

thanks !!

**Comment by manojsai17** [comment]
ok
