### ISSUE TITLE
WebSocket server component/example (IDFGH-2752)

### ISSUE THREAD

**Issue by fri-sch** [espressif/esp-idf#4819]
**Is your feature request related to a problem? Please describe.**

The framework includes a WebSocket client component/example, but no WebSocket server implementation. For many applications were the ESP32 acts as a host to other devices a WebSocket server is required.

**Describe the solution you'd like**

A WebSocket server component and example, based on the existing code and usable together with the existing HTTP/HTTPS server components.

**Describe alternatives you've considered**

I've been looking for other implementations and examples, but couldn't find anything that integrates with the idf and the HTTP server nicely.

**Comment by huming2207** [comment]
You probably can try my fork, but still waiting to be merged to mainline: https://github.com/espressif/esp-idf/pull/4306

**Comment by AshUK** [comment]
Would like to this supported and maintained as part of the ESP-IDF too +1
