### ISSUE TITLE
getting  bta_gattc_cmpl_cback unknown conn_id =  4, ignore data when trying to close GATT client connection (IDFGH-2759)

### ISSUE THREAD

**Issue by mohamed-elsabagh** [espressif/esp-idf#4826]
I am trying to close GATT client connection gracefully, by calling esp_ble_gattc_close but I am getting on log
```E (45993) BT_APPL: bta_gattc_cmpl_cback unknown conn_id =  4, ignore data```
I know connection id is 0, while my gattc_if is 4, so are they mixed up in low level because I am pretty sure I am sending them right

**Comment by GYC-Espressif** [comment]
Hello, Could you provide your IDF version and commit ID? If you can provide your code which can reproduce this issue, that will be more helpful. Thank you.

**Comment by mohamed-elsabagh** [comment]
I am sorry, it turn out to be problem with the peripheral, I am closing the issue
