### ISSUE TITLE
Flash encryption (IDFGH-2769)

### ISSUE THREAD

**Issue by varunsavita** [espressif/esp-idf#4835]
I selected 
 Enable flash encryption on boot (READ DOCS FIRST)   under security feature.
 Bootloader log verbosity (Info) under bootloader config.
 Partition Table (Single factory app, no OTA)
  (0x9000) Offset of partition table   
@igrr @methodmissing 
** Error **
**idf.py encrypted-app-flash monitor** 

Serial port COM3
Connecting........_____....._____....._____....._____.
Detecting chip type... ESP32
Chip is ESP32D0WDQ6 (revision 1)
Features: WiFi, BT, Dual Core, 240MHz, VRef calibration in efuse, Coding Scheme None
Crystal is 40MHz
MAC: b4:e6:2d:e9:4b:09
Uploading stub...
Running stub...
Stub running...
Changing baud rate to 460800
Changed.
Configuring flash size...
Auto-detected Flash size: 4MB

WARNING: - compress and encrypt options are mutually exclusive
Will flash uncompressed
Writing at 0x00024000... (20 %)
A fatal error occurred: Timed out waiting for packet header
esptool.py failed with exit code 2

**Comment by varunsavita** [comment]
![image](https://user-images.githubusercontent.com/42342764/75253111-ef3b2b80-5803-11ea-9b3a-e3887bf3f28d.png)


Could you please to help me to understand the question mark on pic

**Comment by negativekelvin** [comment]
Question mark means value is read protected.  Encryption is on.

**Comment by varunsavita** [comment]
@negativekelvin 
** Error **
idf.py encrypted-app-flash monitor

Serial port COM3
Connecting........................
Detecting chip type... ESP32
Chip is ESP32D0WDQ6 (revision 1)
Features: WiFi, BT, Dual Core, 240MHz, VRef calibration in efuse, Coding Scheme None
Crystal is 40MHz
MAC: b4:e6:2d:e9:4b:09
Uploading stub...
Running stub...
Stub running...
Changing baud rate to 460800
Changed.
Configuring flash size...
Auto-detected Flash size: 4MB

WARNING: - compress and encrypt options are mutually exclusive
Will flash uncompressed
Writing at 0x00024000... (20 %)
A fatal error occurred: Timed out waiting for packet header
esptool.py failed with exit code 2

**Comment by negativekelvin** [comment]
encrypted-app-flash doesn't work if DISABLE_DL_ENCRYPT=1

**Comment by projectgus** [comment]
That's right, this target depends on configuring flash encrption in "Development Mode" in the project. Was that the case here?

We need to add support in esptool.py to check the flash encryption efuse status before the encrypted upload begins.

**Comment by varunsavita** [comment]
I used flash encryption then is it possible?
Someone can read the sketch code from my esp32 module?

**Comment by projectgus** [comment]
Hi @varunsavita ,

If flash encryption is enabled in Release mode (which seems to be the case in the screenshot you posted of espefuse output), then it's not possible for someone to easily read out the flash contents including the firmware binary.

Does this answer your question?

Angus

**Comment by varunsavita** [comment]
Thank you for your support.
Yes, I got

**Comment by projectgus** [comment]
Hi @varunsavita ,

Good to hear. I'm going to close this issue, then.

For future reference, these kind of questions about ESP-IDF (that aren't reporting an issue or a missing feature) are best asked over at https://esp32.com forum .

Angus

**Comment by varunsavita** [comment]
The first time, I upload encrypted flash on then I saw as an image 
Now I want to upload code.
So how to do?
printing the error flash read err, 1000 - meant that flash encrypted enable
how to change FLASH_CRYPT_CNT  it?

**Comment by projectgus** [comment]
@varunsavita Sorry I didn't see this earlier. Did you end enable Flash Encryption in Release mode or Debug mode?

**Comment by Alvin1Zhang** [comment]
@varunsavita Thanks for reporting. Would you please help share if any updates or details for this issue? Thanks.
