### ISSUE TITLE
Build error when console UART set to None (IDFGH-2780)

### ISSUE THREAD

**Issue by KaeLL** [espressif/esp-idf#4845]
IDF git describe: v4.2-dev-432-gc65b67115
```
esp-idf/components/console/esp_console_repl.c:125:22: error: 'CONFIG_ESP_CONSOLE_UART_BAUDRATE' undeclared
```
The existence of this constant is tied to the default setting, but it's still used in IDF.

**Comment by AxelLin** [comment]
I got the same build error with v4.2-dev-521-g6fd855ab8d00.

**Comment by AxelLin** [comment]
Hi @Alvin1Zhang @suda-morris 

Any chance to fix the build error ASAP? IMHO, a build breakage should be high priority to fix.

BTW, I think esp_console_repl_init() should also takes "const uart_config_t *uart_config" argument
so the caller can use different uart settings.

**Comment by suda-morris** [comment]
@KaeLL Sorry for the delay, we will fix it ASAP. Thanks for your nice suggestion. @AxelLin
