### ISSUE TITLE
fatal: No names found, cannot describe anything (IDFGH-2784)

### ISSUE THREAD

**Issue by PauliNioh** [espressif/esp-idf#4847]
2020-02-27 09:42:55.991   Running command: C:\Users\Paul\AppData\Local\Programs\Python\Python37\python.exe C:\Users\Paul\Desktop\esp32\esp-idf-master\tools\idf_tools.py install-python-env
                          fatal: No names found, cannot describe anything
                          
.
.
.

   WARNING: Git describe was unsuccessul: Command '['git', 'describe', '--tags']' returned non-zero exit status 128.

![image](https://user-images.githubusercontent.com/61537768/75425183-de490200-594a-11ea-82cf-3865742f5ac8.png)

**Comment by Alvin1Zhang** [comment]
Thanks for reporting. Would you please help provide more details as suggested in the [issue template](https://github.com/espressif/esp-idf/issues/new?assignees=&labels=&template=bug_report.md&title=)? Information like elf, sdk configuration, backtrace, log outputs, commit ID, hardware and etc. would help us debug further. Thanks.

**Comment by dobairoland** [comment]
@PauliNioh How the output continues? I assume that everything works as it should be and you get to "Done! You can now compile ESP-IDF projects. Go to the project directory and run: idf.py build". 

If your ESP-IDF is a shallow clone then `git describe --tags` fails but `idf_tools.py` detects the IDF version in a different way.
