### ISSUE TITLE
国内clone中途失败 (IDFGH-2785)

### ISSUE THREAD

**Issue by yhongm** [espressif/esp-idf#4848]
你们只有国外的用户，为什么国内gitee不更新了？国内clone了几天，无数次中途失败，你们这个esp产品只给国外用户用？
error: RPC failed; curl 56 LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54

**Comment by sheldon123z** [comment]
我觉得使用git 克隆github上的在国内也一样用吧...?

**Comment by suda-morris** [comment]
Hi @yhongm 国内访问GitHub慢是一个众所周知的事情，原因相信你一定了解...经过实践发现，如果你连接 4G 热点然后再clone仓库，速度会快上很多，你可以试试看。另外还有一个办法，就是在我们的release页面下载zip源码包(他们位于dl.espressif.com，所以下载速度会很快），解压后可以通过`git fetch`等命令将master分支上的最新提交同步下来（这样你从github上直接clone的数据量会少很多很多）。

我们不使用gitee的一个重要原因是，ESP-IDF中包含了许多**第三方**的子模块（通过 git submodule 进行管理），他们中的绝大部分也都在Github上托管着，我们无法要求这些项目的作者也去Gitee上创建一个镜像仓库，你说对吧？

**Comment by redchenjs** [comment]
确实，即使主仓库托管在gitee上，那些子模块还是会链接到github上，所以也差不了多少

**Comment by yhongm** [comment]
> Hi @yhongm 国内访问GitHub慢是一个众所周知的事情，原因相信你一定了解...经过实践发现，如果你连接 4G 热点然后再clone仓库，速度会快上很多，你可以试试看。另外还有一个办法，就是在我们的release页面下载zip源码包(他们位于dl.espressif.com，所以下载速度会很快），解压后可以通过`git fetch`等命令将master分支上的最新提交同步下来（这样你从github上直接clone的数据量会少很多很多）。
> 
> 我们不使用gitee的一个重要原因是，ESP-IDF中包含了许多**第三方**的子模块（通过 git submodule 进行管理），他们中的绝大部分也都在Github上托管着，我们无法要求这些项目的作者也去Gitee上创建一个镜像仓库，你说对吧？

好吧，谢谢

**Comment by yhongm** [comment]
clone了一个星期了，无论是移动4G，电信4G，宽带。每次clone百分之十几就中途失败。一个星期没干别的，就clone这个了。只能说无语两个字

**Comment by yhongm** [comment]
<img width="593" alt="截屏2020-02-28下午3 47 12" src="https://user-images.githubusercontent.com/3638074/75520932-a53f8900-5a41-11ea-8e75-1ba3d27b4a71.png">
<img width="593" alt="截屏2020-02-28下午3 46 20" src="https://user-images.githubusercontent.com/3638074/75520969-b7212c00-5a41-11ea-84d2-1147865c2f15.png">
我用了github几年，从来没有clone一个项目这么费劲，clone一个星期，无数次失败。

**Comment by yhongm** [comment]
<img width="593" alt="截屏2020-02-28下午4 03 37" src="https://user-images.githubusercontent.com/3638074/75522026-e6d13380-5a43-11ea-8ff0-4835f303d017.png">

**Comment by suda-morris** [comment]
很抱歉因为网络的原因带来不愉快的使用体验 😭

从 release 页面直接下载 zip 包呢，是否可以成功？

另外，国内也有一些提供Github下载加速的网站，比如这个：http://g.widora.io/

**Comment by yhongm** [comment]
> 很抱歉因为网络的原因带来不愉快的使用体验 😭
> 
> 从 release 页面直接下载 zip 包呢，是否可以成功？
> 
> 另外，国内也有一些提供Github下载加速的网站，比如这个：http://g.widora.io/



> 很抱歉因为网络的原因带来不愉快的使用体验 😭
> 
> 从 release 页面直接下载 zip 包呢，是否可以成功？
> 
> 另外，国内也有一些提供Github下载加速的网站，比如这个：http://g.widora.io/

谢谢
