### ISSUE TITLE
[TW#12120] API for getting value of output pin

### ISSUE THREAD

**Issue by kostyan5** [espressif/esp-idf#485]
There doesn't seem to be a function to read the value of a pin set as output.  

gpio_get_level() only returns the status of the "input" parameter.  If you want to toggle an output pin by doing something like this, the value of gpio_get_level(pin) never changes.
```
    uint32_t new_state = 1 - gpio_get_level(pin);
    gpio_set_level(pin, new_state);
```

In order to do a toggle, I had to use
```
  uint32_t new_state = 1 - (GPIO.out >> pin & 0x1);
  gpio_set_level(pin, new_state);
```

**Comment by kewalmshah** [comment]
Hi @kostyan5 in order to get level of gpio set as output, you can set gpio pin mode to GPIO_MODE_INPUT_OUTPUT and then call gpio_get_level(pin)

**Comment by FayeY** [comment]
Hi @kostyan5 , did the above suggestion help you resolve the issue?

**Comment by kostyan5** [comment]
@FayeY Haven't had time to check it out.  I'll update in the next couple of weeks.

**Comment by FayeY** [comment]
Hi @kostyan5 , I'll close this issue. If your problem is still unsolved, please feel free to reopen it.
