### ISSUE TITLE
Is it possible change duty cycle in microsecond (IDFGH-2789)

### ISSUE THREAD

**Issue by TarikAkyuz** [espressif/esp-idf#4852]
I need the signal exactly like 50 microsecond resolution. Is it possible?

[https://i.imgyukle.com/2020/02/28/nUcheQ.png](url)

**Comment by igrr** [comment]
Should be possible with the RMT peripheral!

**Comment by TarikAkyuz** [comment]
> Should be possible with the RMT peripheral!

I also use lan8720 ethernet PHYs. Therefore, I cannot use the 18th pin. Can I use any pin, like pin 2, for this?

**Comment by suda-morris** [comment]
yes, it should be possible @TarikAkyuz
