### ISSUE TITLE
Cmake error (IDFGH-2791)

### ISSUE THREAD

**Issue by PauliNioh** [espressif/esp-idf#4854]
![20200228_120828](https://user-images.githubusercontent.com/61537768/75539609-30f5ed00-5a23-11ea-94cb-563252ca36f5.jpg)

**Comment by dobairoland** [comment]
@PauliNioh Please notice that you have misspelled `menuconfig` and written `menuiconfig`. Also you are not supposed to run `idf.py` from your `esp-idf-master` directory but from a project directory, e.g. `esp-idf-master\examples\get-started\hello_world`.
