### ISSUE TITLE
how to link the ip address or tcp method got from gsm module attached to esp32 module through uart port . and use default mqtt library to send data . (IDFGH-2794)

### ISSUE THREAD

**Issue by manojsai17** [espressif/esp-idf#4857]
we interface the gsm module to esp uart .
I able to data transfer to cloud using wifi with default mqtt library .
So we interfaced gsm module to esp uart .
with traditional at command i able to get the network and ip address .

how to link the ip address or tcp method got from my gsm module to esp module . and use default mqtt library to send data to cloud.
I dont want to use ppos method . because i dont have knowledge exposure on ppos method .

**Comment by negativekelvin** [comment]
1. Do not post duplicate questions here and on the forum.  Only post bug reports here, not questions.

2. You have 9 open issues.  Please close anything that is not a bug report.

3. If you need urgent assistance then email sales@espressif.com and request technical support through your account representative.

**Comment by Alvin1Zhang** [comment]
@negativekelvin Thanks for the notes. @manojsai17 Thanks for reporting. For how questions and third party questions, it is suggested that you could raise a post on our forum at https://esp32.com, thanks. If you have requests about feature, issue and etc, please help follow template [here](https://github.com/espressif/esp-idf/issues/new/choose). Thanks.
