### ISSUE TITLE
Vscode no compiler paths detected (IDFGH-2795)

### ISSUE THREAD

**Issue by PauliNioh** [espressif/esp-idf#4858]
![20200228_211115](https://user-images.githubusercontent.com/61537768/75580216-0bdb9b80-5a70-11ea-9e0a-d35b885c40c0.jpg)

**Comment by brianignacio5** [comment]
Hi there !

Have you tried setting up the compiler path directly in the **c_cpp_properties.json** file in your project's .vscode folder? It is called `compilerPath: /path/to/xtensa/gcc` or setting up the xtensa bin folder in your system environment variable PATH ?

Please consider trying our extension [ESP-IDF Extension](https://marketplace.visualstudio.com/items?itemName=espressif.esp-idf-extension) and check how to configure your C/C++ with [C_CPP_Configuration](https://github.com/espressif/vscode-esp-idf-extension/blob/master/docs/C_CPP_CONFIGURATION.md)
