### ISSUE TITLE
What is UART_RX_BREAK in uart .how to implement it ? (IDFGH-2796)

### ISSUE THREAD

**Issue by manojsai17** [espressif/esp-idf#4859]
What is UART_RX_BREAK in uart .how to implement it ?

**Comment by Alvin1Zhang** [comment]
@manojsai17 Thanks for reporting. For "how" questions and third party questions, it is suggested that you could raise a post on our forum at https://esp32.com, thanks. If you have requests about feature, issue, please help follow template [here](https://github.com/espressif/esp-idf/issues/new/choose). Thanks.
