### ISSUE TITLE
cmake 302 error (IDFGH-2804)

### ISSUE THREAD

**Issue by PauliNioh** [espressif/esp-idf#4867]
![image](https://user-images.githubusercontent.com/61537768/75622822-31ba8a80-5bad-11ea-81ed-3f005cde06d1.png)

**Comment by fafactx** [comment]
maybe its a environment issues。please try it again follow the user guide which suggest by espressif on github.------------------ 原始邮件 ------------------
发件人: "PauliNioh"<notifications@github.com>
发送时间: 2020年3月1日(星期天) 下午5:11
收件人: "espressif/esp-idf"<esp-idf@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [espressif/esp-idf] cmake 302 error (#4867)




 
&mdash;
