### ISSUE TITLE
idf monitor (IDFGH-2806)

### ISSUE THREAD

**Issue by PauliNioh** [espressif/esp-idf#4869]
![image](https://user-images.githubusercontent.com/61537768/75628380-179a9f80-5be1-11ea-96d0-74f13d75faf0.png)

**Comment by Alvin1Zhang** [comment]
Thanks for reporting. Would you please help provide more details as suggested in the [feature template](https://github.com/espressif/esp-idf/issues/new?assignees=&labels=Type%3A+Feature+Request&template=feature_request.md&title=)? Thanks.

**Comment by dobairoland** [comment]
@PauliNioh Do you experience any issue here? That is just a warning and the monitor should work as expected.

Note: Please ask questions on https://esp32.com/ instead of opening a Github issue for everything. This is not a feature request nor an issue.
