### ISSUE TITLE
sha-256 of native_ota_example.c ,sha 256  of running  file is not matching. (IDFGH-2809)

### ISSUE THREAD

**Issue by sahilsoni1** [espressif/esp-idf#4871]

**Comment by Alvin1Zhang** [comment]
Thanks for reporting. Would you please help provide more details as suggested in the [issue template](https://github.com/espressif/esp-idf/issues/new?assignees=&labels=&template=bug_report.md&title=)? Information like elf, sdk configuration, backtrace, log outputs, commit ID, hardware and etc. would help us debug further. Thanks.

**Comment by Alvin1Zhang** [comment]
@sahilsoni1 Thanks for reporting, please help fill in the details required in the [issue template](https://github.com/espressif/esp-idf/issues/new?assignees=&labels=&template=bug_report.md&title=), which could help us in debugging. Currently, will close the issue due to short of feedback, thanks.
