### ISSUE TITLE
OpenOCD does not work properly with "ON_BOOT" Signed App Verification. (IDFGH-2816)

### ISSUE THREAD

**Issue by Fetiu** [espressif/esp-idf#4878]
## Environment

- Development Kit:   ESP32-Ethernet-Kit
- Kit version v1.1 
- Module or chip used:    ESP32-WROVER-B, ESP32-PICO-D4.
- IDF version:    v4.1-dev-474-g2e6398aff
- Build System:    Make, idf.py
- Compiler version:    esp32-2019r1-8.2.0
- Operating System:     macOS
- Using an IDE?:  Yes, VSCode.
- Power Supply:    external 3.3V

## Problem Description

I'm developing an ESP-IDF based firmware upon hardware with ESP32-PICO-D4.
I used J-Link to debug the firmware, but it was almost impossible because whenever I try to connect to the target, the device just showed reset continuously.
But when I loaded `bootloader.elf` into the debug session, I could read where is the last location that is trackable. It was `verify_secure_boot_signature` function.

So I tried reproducing this in reference board `ESP32-Ethernet-Kit` which has built-in FTDI debug interface. The same symptom happened. 
And also I could reproduce it in other examples inside esp-idf.

(Tried the latest master also, but I was not able to run openocd with board settings provided. adapter_khz does not exist from this point. but this is out of scope)

### Expected Behavior

After `mon reset halt`, `flush regs`, `continue`, 
debug session should hit the breakpoint in `app_main` as requested with `thb app_main`

### Actual Behavior

But after continue, it does not seem to enter the expected function.
Not responding, or with some sdkconfig, soft reset occurs constantly.

### Steps to reproduce

1. Setup ESP-IDF and browse into any code example. ( I used `blink` )
2. Run `idf.py menuconfig`. Turn on "Require signed app images" and then "Bootloader verifies app signatures", in Security features.
3. Before building, we should generate a secure boot signing key. run `espsecure.py generate_signing_key secure_boot_signing_key.pem`
4. build and flash into the device.
5. Start debugging with OpenOCD and xtensa-esp32-elf-gdb. And try gdb commands as usual. 

The symptom usually reproduces when target halted, by "continue".
Sometimes could not reach the app_main at all, with no response.
Sometimes soft reset occurs several times (or forever).
To reproduce the reset problem, `sdkconfig` attached would be needed.

### Code to reproduce(resolve) this issue

**I could resolve this symptom in two different ways.**

1. Disable CONFIG_SECURE_SIGNED_ON_BOOT_NO_SECURE_BOOT.
By reverting step 2 above. Okay to leave "on update" as is. 
But it does not solve the root cause.

2. Check `esp_cpu_in_ocd_debug_mode` before `verify_secure_boot_signature` in image_load. line 208 of `esp_image_format.c`
```diff
--- a/components/bootloader_support/src/esp_image_format.c
+++ b/components/bootloader_support/src/esp_image_format.c
@@ -205,7 +205,10 @@ static esp_err_t image_load(esp_image_load_mode_t mode, const esp_partition_pos_
         if (!is_bootloader) {
 #ifdef SECURE_BOOT_CHECK_SIGNATURE
             // secure boot images have a signature appended
-            err = verify_secure_boot_signature(sha_handle, data);
+            if (!esp_cpu_in_ocd_debug_mode())
+            {
+                err = verify_secure_boot_signature(sha_handle, data);
+            }
 #else
             // No secure boot, but SHA-256 can be appended for basic corruption detection
             if (sha_handle != NULL && !esp_cpu_in_ocd_debug_mode()) {
```
## Debug Logs

Logs below were repeated when the symptom is occurring.

1. Continuous reset
- logs from openocd
```
esp32: Debug controller 0 was reset (pwrstat=0x5F, after clear 0x0F).

esp32: Core 0 was reset (pwrstat=0x5F, after clear 0x0F).

esp32: Debug controller 0 was reset (pwrstat=0x5F, after clear 0x0F).

esp32: Core 0 was reset (pwrstat=0x5F, after clear 0x0F).

esp32: Debug controller 0 was reset (pwrstat=0x5F, after clear 0x0F).

esp32: Core 0 was reset (pwrstat=0x5F, after clear 0x0F).
...
```
- log from uart
```
rst:0x3 (SW_RESET),boot:0x12 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:1052
load:0x40078000,len:14696
load:0x40080400,len:3032
entry 0x400805d0
ets Jun  8 2016 00:22:57


rst:0x3 (SW_RESET),boot:0x12 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:1052
load:0x40078000,len:14696
load:0x40080400,len:3032
entry 0x400805d0
...
```
2. when not responding ( blink example with signed key )
```
rst:0x10 (RTCWDT_RTC_RESET),boot:0x32 (SPI_FAST_FLASH_BOOT)
flash read err, 1000
ets_main.c 371 
ets Jun  8 2016 00:22:57


rst:0x10 (RTCWDT_RTC_RESET),boot:0x32 (SPI_FAST_FLASH_BOOT)
flash read err, 1000
ets_main.c 371
...
```

## Other items if possible

patch, sdkconfig, elf, binary files attached.
[debug_signed_on_boot.zip](https://github.com/espressif/esp-idf/files/4287577/debug_signed_on_boot.zip)

**Comment by Alvin1Zhang** [comment]
@Fetiu Thanks for the detailed report. We will look into.
