### ISSUE TITLE
[TW#11598] spi not sendig null

### ISSUE THREAD

**Issue by dannybr** [espressif/esp-idf#488]
sending only nulls does not work!
I'm developing on a esp-wroom-32.

spi_transaction_t t;
t.tx_data[0] = 0
t.length = 8;
t.flags = SPI_TRANS_USE_TXDATA;
spi_device_transmit(spi, &t) returns without error but
the logic analizer shows nothing,

if length is > 1*8, and one of the bytes is NULL it does work!
so is this firmware or hardware issue?

**Comment by jaanh** [comment]
I have the same issue. Below is another example where no data is actually sent (e.g no CS pin toggling or CLK pulses).
```
t[1].tx_data[0] = 0x00;
t[1].tx_data[1] = 0x00;
t[1].tx_data[2] = 0x00;
t[1].length = 3 * 8;
```

I have found a workaround though:
t[1].tx_data[0] = 0x00;
t[1].tx_data[1] = 0x00;
t[1].tx_data[2] = 0x00;
t[1].tx_data[3] = 0x01;
t[1].length = 3 * 8; // Set length to 3 to only send the first 3 bytes

**Comment by dannybr** [comment]
thanks!
