### ISSUE TITLE
nvs_get_blob 这个API设计的并不好 (IDFGH-2818)

### ISSUE THREAD

**Issue by snikeguo** [espressif/esp-idf#4880]
```
size_t required_size = 0;  // value will default to 0, if not set yet in NVS
err = nvs_get_blob(my_handle, "MyConfig", &ReadConfig, &required_size);
```
我看例子，也明白第一次调用nvs_get_blob时用来获取required_size的，可是这个返回值是ESP_ERR_NVS_INVALID_LENGTH
经过看源码，定位到这里:
在nvs_get_str_or_blob函数中
```
if (length == nullptr) {
        return ESP_ERR_NVS_INVALID_LENGTH;
    } else if (out_value == nullptr) {
        *length = dataSize;
        return ESP_OK;
    } else if (*length < dataSize) { //走向了这条分支。
        *length = dataSize;
        return ESP_ERR_NVS_INVALID_LENGTH;
    }
```
我觉得提供类似于这样的API：nvs_get_blob_required_size(my_handle, "MyConfig",&required_size) 可能更好。
另外这个NVS和另外一个库很相似，这个API设计 各位大佬可以看下https://github.com/armink/EasyFlash

**Comment by gaupen1186** [comment]
今天我也遇到了这个 ESP_ERR_NVS_INVALID_LENGTH 的情况。
经过仔细研究，发现这样设计是很严谨的，是我们没搞清楚它的具体用法。
以 esp_err_t nvs_get_str (nvs_handle_t handle, const char* key, char* out_value, size_t* length); 来说，
length 参数是 in & out 类型，当作为 in 传入时，它代表 out_value 的大小，这样能确保你的 out_value 空间不足时，不会出现意外覆盖。当作为 out 传出时，它代表实际读出的长度。

它的大段注释详细解释了这个最后的 length 参数，摘录如下：

nvs_get_str and nvs_get_blob functions support WinAPI-style length queries.

 * \code{c}
 * // Example (without error checking) of using nvs_get_str to get a string into dynamic array:
 * size_t required_size;
 * nvs_get_str(my_handle, "server_name", NULL, &required_size);
 * char* server_name = malloc(required_size);
 * nvs_get_str(my_handle, "server_name", server_name, &required_size);
