### ISSUE TITLE
can example (IDFGH-2842)

### ISSUE THREAD

**Issue by nopnop2002** [espressif/esp-idf#4902]
examples/peripherals/can/can_network/can_network_master and
examples/peripherals/can/can_network/can_network_slave don't work.

My Environment:
```
freeRTOS version:V8.2.0
NEWLIB version:3.0.0
lwIP version:2-1-3-0
ESP-IDF version:v4.1-dev-1935-g647cb628a
```

Transceiver:
SN65HVD230

Wire:
```
    ----------   ----------   --------------  
   |  Master  | |  Slave   | | Listen Only  | 
   |          | |          | |              | 
   | 21    22 | | 21    22 | | 21    22     | 
    ----------   ----------   --------------  
     |      |     |      |     |      |   
     |      |     |      |     |      |   
    ----------   ----------   ----------  
   | D      R | | D      R | | D      R | 
   |          | |          | |          | 
   |  VP230   | |  VP230   | |  VP230   | 
   |          | |          | |          | 
   | H      L | | H      L | | H      L | 
    ----------   ----------   ----------  
     |      |     |      |     |      |   
     |      |     |      |     |      |   
  |--x------|-----x------|-----x------|--| H
            |            |            |
  |---------x------------x------------x--| L

```
Both transceivers have a 120 ohm termination resistor.

Master:
![master](https://user-images.githubusercontent.com/6020549/76126074-804ea580-6041-11ea-9d71-74d7b63d5529.jpg)

Slave:
![slave](https://user-images.githubusercontent.com/6020549/76126080-86448680-6041-11ea-9670-a07182c86798.jpg)

**Comment by Dazza0** [comment]
@nopnop2002 

It means that the CAN Master is not able to ping the slave. The ping is a single shot Data Frame that the CAN master will keep sending until the CAN slaves responds with another Data Frame.

Could you check that the CAN bus and transceivers are connected properly by confirming with a logic analyzer that the RX pin of the CAN Master and CAN Slave are actually receiving data?

**Comment by nopnop2002** [comment]
@Dazzo0
I do not have a logic analyzer.
I will try it on esp-idf Ver3.3 on the weekend.

**Comment by nopnop2002** [comment]
I tried with ESP-IDF Ver3.3 but it doesn't work.

The transmitter is a 5V transceiver and the receiver is a 3.3V transceiver.
There seems to be a problem here.

Sorry for the trouble.

**Comment by xuhongv** [comment]
did you resolve it ? i have the same problem @nopnop2002

**Comment by nopnop2002** [comment]
@xuhongv 

The problem was solved by adjusting the value of the terminating resistor.
