### ISSUE TITLE
[TW#12117] HSPI - No clock at 900KHz

### ISSUE THREAD

**Issue by Searaphim** [espressif/esp-idf#491]
For some reason when we set 900KHz on the HSPI and send data there is no clock on the HSPI CLK pin. The Chip Select pin does work though. HSPI also works on any other frequency we've tried (below or above 900KHz). It seems a bit odd that this behavior shows up only at that specific clock speed.

**Comment by projectgus** [comment]
To clarify, are you using the spi_master driver and `spi_bus_add_device()` to configure the HSPI clock? Do you have a snippet of code that demonstrates the bad settings?

**Comment by Spritetm** [comment]
Smells like a bug in the clock register calculation code... I'll look into this, working on SPI anyway.
