### ISSUE TITLE
I (39) boot: ESP-IDF -128-NOTFOUND 2nd stage bootloader (IDFGH-2857)

### ISSUE THREAD

**Issue by mattkefford** [espressif/esp-idf#4915]
## Environment

- Development Kit: ESP32-Wrover-Kit
- Kit version: v4.1
- Module or chip used: ESP32-WROVER
- IDF version: v4.0
- Build System: CMake
- Compiler version: xtensa-esp32-elf-gcc.exe (crosstool-NG esp-2019r2) 8.2.0
- Operating System: Windows
- (Windows only) environment type: ?
- Using an IDE?: Yes Visual Studio + VisualGDB
- Power Supply: USB

## Problem Description
Recently switched from IDF v3.3.1 to v4.0.
The code compiles and flashes and boots fine, but during boot log I now see the message: 
"I (39) boot: ESP-IDF -128-NOTFOUND 2nd stage bootloader"

Previously this has always managed to pull in the version of IDF being used. 

I have checked my paths and they are correct:
![image](https://user-images.githubusercontent.com/15934099/76413050-9edbd600-638c-11ea-9e9d-472a6c07da03.png)

Anybody have any clue how to fix this? I've looked in the project properties within visual studio and cannot see any other place to specify the tools or IDF path. 

## Debug Logs
![image](https://user-images.githubusercontent.com/15934099/76414579-7ef9e180-638f-11ea-9920-9d633af5b116.png)

**Comment by igrr** [comment]
@mattkefford It's a bit hard to troubleshoot this, since I'm not familiar with VisualGDB internals, but can you check if VisualGDB makes `git` available on the `PATH` when invoking `cmake`? This error may happen if `git` is not present on the PATH.

**Comment by Alvin1Zhang** [comment]
@mattkefford Thanks for reporting. Would you please help share if any updates or details for this issue? Thanks.

**Comment by Alvin1Zhang** [comment]
@mattkefford Thanks for reporting. Would you please help share if any updates or details for this issue? Thanks.

**Comment by projectgus** [comment]
Closing due to a lack of updates.

**Comment by mattkefford** [comment]
My apologies. As you may be aware, there is currently a global pandemic occurring, I have since lost my job. I no longer have access to this build environment or the computer I was using and I am no longer developing for the ESP32.

Thanks for your efforts to debug the issue. I hope it serves as useful for others.

**Comment by projectgus** [comment]
Hi @mattkefford,

Very sorry to hear that. Wish you the best in this tough time, hope you find a new role soon.

Angus
