### ISSUE TITLE
'mem_start' may be used uninitialized in esp_bt_controller_mem_release (IDFGH-2861)

### ISSUE THREAD

**Issue by uname2219** [espressif/esp-idf#4918]
## Environment

- Development Kit:      ESP32-Wrover-Kit
- Kit version (for WroverKit/PicoKit/DevKitC): v4
- Module or chip used:  ESP32-WROVER-B
- IDF version (run ``git describe --tags`` to find it): v4.1-dev-2079-g5dbabae9d
- Build System:         make
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it): xtensa-esp32-elf-gcc (crosstool-NG esp-2019r2) 8.2.0
- Operating System:     linux
- Using an IDE?: No
- Power Supply: usb

## Problem Description

I attempted to build a project that includes Bluetooth with performance optimizations: 
```
CONFIG_COMPILER_OPTIMIZATION_PERF=y
CONFIG_BT_ENABLED=y
CONFIG_BT_CLASSIC_ENABLED=y
CONFIG_BTDM_CTRL_MODE_BTDM=y
```
When I make the project, the build fails inside components/bt/controller/bt.c with:
```
/home/user/Development/esp32/esp-idf-v4.1/components/bt/controller/bt.c: In function 'esp_bt_controller_mem_release':
/home/user/Development/esp32/esp-idf-v4.1/components/bt/controller/bt.c:961:15: error: 'mem_start' may be used uninitialized in this function [-Werror=maybe-uninitialized]
     int ret = heap_caps_add_region(start, end);
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/user/Development/esp32/esp-idf-v4.1/components/bt/controller/bt.c:975:14: note: 'mem_start' was declared here
     intptr_t mem_start, mem_end;
              ^~~~~~~~~
cc1: some warnings being treated as errors
```

### Expected Behavior

Perhaps initializing mem_start to NULL so the compiler can detect it has been initialized? Then the rest of the build can continue. Under default optimizations the project builds without error.

**Comment by Alvin1Zhang** [comment]
@uname2219 Thanks for reporting.

**Comment by AbnerFederer** [comment]
Please apply this patch. 
[optimization_compiler_fix.zip](https://github.com/espressif/esp-idf/files/4323078/optimization_compiler_fix.zip)

**Comment by uname2219** [comment]
Thank you, with this patch the project builds and runs. I look forward to seeing this merged in.

**Comment by Alvin1Zhang** [comment]
@uname2219 Thanks for reporting and updates. We have a fix internally and under reviewing. Will update once the fix gets synchronized into GitHub. Thanks.

**Comment by Alvin1Zhang** [comment]
@uname2219 Thanks for reporting, the fix has been available on GitHub. Thanks.

**Comment by ROYMURLI** [comment]
Facing same issue. How to apply this patch. Guide me. 
OS- Windows using (msys32)
IDF- v4.1-dev-1086-g93a8603c5

**Comment by AbnerFederer** [comment]
@ROYMURLI 

`git apply [route to patch]`
