### ISSUE TITLE
possible issue in mdns (IDFGH-2884)

### ISSUE THREAD

**Issue by chegewara** [espressif/esp-idf#4930]
I have very simple http server serving 2 files with GET and 1 POST link. Also in code i have implemented mdns.

I am assuming it is issue with mdns because:
- all is working fine after reboot, i can access server with esp32.local,
- http server works fine,
- after some time i still can access esp32 with IP, but connecting with esp32.local is printing such logs:
`ip4_output_if: Packets larger than MTU, discarded!!!`

esp-idf v3.3 commit 6f9a7264ce20c6132fbd8309112630d0eb490fe4

**Comment by david-cermak** [comment]
@chegewara Sorry for not responding in more timely manner.
* Are there any other mdns devices in the local network? Is that reproducible also if you have only one device, the esp32.local?
* Could you please enable the IP fragmentation if disabled, to see if the issue still exists? `CONFIG_LWIP_IP_FRAG=y`

**Comment by chegewara** [comment]
Hi @david-cermak 

> * Are there any other mdns devices in the local network? Is that reproducible also if you have only one device, the esp32.local?

yes, there is few more mdns devicesin the same network, but only 1 esp32

> * Could you please enable the IP fragmentation if disabled, to see if the issue still exists? `CONFIG_LWIP_IP_FRAG=y`

enabling this option seems to fix issue

Thanks for help.

**Comment by AxelLin** [comment]
> > * Could you please enable the IP fragmentation if disabled, to see if the issue still exists? `CONFIG_LWIP_IP_FRAG=y`
> 
> enabling this option seems to fix issue

But why mdns needs CONFIG_LWIP_IP_FRAG=y to work?
If mdns really needs CONFIG_LWIP_IP_FRAG=y, had better show some warning if CONFIG_LWIP_IP_FRAG=n.

**Comment by chegewara** [comment]
I found that another option has been enabled, will test if this change anything and report:
`CONFIG_EMAC_L2_TO_L3_RX_BUF_MODE=y`

**Comment by chegewara** [comment]
> I found that another option has been enabled, will test if this change anything and report:
> `CONFIG_EMAC_L2_TO_L3_RX_BUF_MODE=y`

Nope, this option changes nothing, but with `CONFIG_LWIP_IP_FRAG=y` server is working very stable now. (maybe it was not mdns)
