### ISSUE TITLE
Installation has failed with exit code -107374181 (IDFGH-2906)

### ISSUE THREAD

**Issue by 25prithvi** [espressif/esp-idf#4950]
![Capture](https://user-images.githubusercontent.com/30038626/76929946-5d5aa600-690b-11ea-86f6-0da2ab17a621.PNG)

Getting this error while installing ESP-IDF by toolchain_2.2

**Comment by igrr** [comment]
Could you please try 2 things?

1) Use the version 2.3 of the installer: https://dl.espressif.com/dl/esp-idf-tools-setup-2.3.exe

2) Clear the checkbox for Defender exceptions when installing.

**Comment by 25prithvi** [comment]
Thank you. It worked.
