### ISSUE TITLE
Incorrect Erase Size Calculation In esp_ota_begin (IDFGH-2909)

### ISSUE THREAD

**Issue by CDK-Vonkil** [espressif/esp-idf#4953]
In components/app_update/esp_ota_ops.c:
In function esp_ota_begin:

An incorrect erase size is calculated when the caller passes image_size=partition->size.

This is because of an error in the rounding calculation at line 160, which adds an extra sector size:
ret = esp_partition_erase_range(partition, 0, (image_size / SPI_FLASH_SEC_SIZE + 1) * SPI_FLASH_SEC_SIZE);

The correct calculation would be something like:
ret = esp_partition_erase_range(partition, 0, ((image_size + SPI_FLASH_SEC_SIZE - 1) / SPI_FLASH_SEC_SIZE) * SPI_FLASH_SEC_SIZE);

**Comment by Alvin1Zhang** [comment]
@CDK-Vonkil Thanks for reporting, we have a fix internally now under reviewing. Will update once the fix is available on GitHub. Thanks.
