### ISSUE TITLE
Crash when RMT mem_block_num > 1 (IDFGH-2915)

### ISSUE THREAD

**Issue by cskilbeck** [espressif/esp-idf#4959]
## Environment

- Development Kit: `ESP32-WROOM`
- Module or chip used: `ESP32D0WDQ5 (revision 1)`
- IDF version: `v4.1-dev-2079-g5dbabae9d`
- Build System: make
- Compiler version: `xtensa-esp32-elf-gcc (crosstool-NG esp-2019r2) 8.2.0`
- Operating System: Windows subsystem for Linux
- Using an IDE?: No
- Power Supply: external 5V

## Problem Description

When rmt_config is called with rmt_config_t containing mem_block_num value > 1, then a hard crash occurs in rmt translation function.

### Expected Behavior

Using > 1 mem_blocks used to work (I think on v4.0)

### Actual Behavior

Hang, resulting in WDT trigger

### Steps to reproduce

- start with the rmt/led_strip sample
- set RMT_TX_CHANNEL == 0
- add the following at line 83 of led_strip_main.c 
        `config.mem_block_num = 8;`
- build and run

### Code to reproduce this issue

https://gist.github.com/cskilbeck/6ce188fd980637f194f454d5bdd43037

## Debug Log

https://gist.github.com/cskilbeck/56da4ad34c9c9bb4d04efe092b5cb632

## Other items

- sdkconfig https://gist.github.com/cskilbeck/f2dd85b335054355558e3a6deb0bec4f
-elf [led_strip.zip](https://github.com/espressif/esp-idf/files/4355537/led_strip.zip)

**Comment by cskilbeck** [comment]
Init function:
```
void neopixel_init()
{
    rmt_config_t config;
    config.rmt_mode = RMT_MODE_TX;
    config.channel = LED_RMT_TX_CHANNEL;
    config.gpio_num = LED_RMT_TX_GPIO;
    config.mem_block_num = 1;
    config.tx_config.loop_en = false;
    config.tx_config.carrier_en = false;
    config.tx_config.idle_output_en = true;
    config.tx_config.idle_level = RMT_IDLE_LEVEL_HIGH;    // high because level shifter inverts it
    config.clk_div = 2;

    ESP_ERROR_CHECK(rmt_config(&config));
    ESP_ERROR_CHECK(rmt_driver_install(config.channel, 0, ESP_INTR_FLAG_IRAM));
    ESP_ERROR_CHECK(rmt_translator_init(config.channel, rmt_translate));
}
```

write function:
```
    ESP_ERROR_CHECK(rmt_wait_tx_done(LED_RMT_TX_CHANNEL, portMAX_DELAY));
    ESP_ERROR_CHECK(rmt_write_sample(LED_RMT_TX_CHANNEL, rgb, num_leds * 3, false));
```

**Comment by Alvin1Zhang** [comment]
@cskilbeck Thanks for reporting. Would you please help provide more details as suggested in the [issue template](https://github.com/espressif/esp-idf/issues/new?assignees=&labels=&template=bug_report.md&title=)? Information like elf, sdk configuration, backtrace, log outputs, commit ID, hardware and etc. would help us debug further. Thanks.

**Comment by koobest** [comment]
Hi, @cskilbeck 
 Do you want to  drive an WS2812 LED strip with RMT?  you can refer to https://github.com/espressif/esp-idf/tree/master/examples/peripherals/rmt/led_strip
thanks !!

**Comment by cskilbeck** [comment]
I'll see if I can make a minimal repro, hang on

**Comment by cskilbeck** [comment]
OK, the repro is as follows:
- start with the rmt/led_strip sample
- add the following at line 83 `config.mem_block_num = 8;`
- build and run
result is a crash

**Comment by cskilbeck** [comment]
From looking at the debug log, it seems to be having a problem in `rmt_ll_write_memory`, called from line 519 in `driver/rmt.c`

```cpp
static void IRAM_ATTR rmt_fill_memory(rmt_channel_t channel, const rmt_item32_t *item,
                                      uint16_t item_num, uint16_t mem_offset)
{
    RMT_ENTER_CRITICAL();
    rmt_ll_set_mem_owner(p_rmt_obj[channel]->hal.regs, channel, RMT_MEM_OWNER_SW);
    rmt_ll_write_memory(p_rmt_obj[channel]->hal.mem, channel, item, item_num, mem_offset);
    rmt_ll_set_mem_owner(p_rmt_obj[channel]->hal.regs, channel, RMT_MEM_OWNER_HW);
    RMT_EXIT_CRITICAL();
}
```

**Comment by cskilbeck** [comment]
Also worth mentioning (although this is really a separate bug) that when `mem_block_num` == 1 and # of items is large (1200 bytes in this case), occasional flickering occurs, _possibly_ because the ISR is not servicing the RMT peripheral adequately. This is the reason for using 8 mem_blocks, which seemed to fix the flickering.

**Comment by koobest** [comment]
Hi,@cskilbeck
Thanks for reporting this issue, this is a issue introduced by driver refactoring. We will fix it soon.

thansk !!

**Comment by cskilbeck** [comment]
Great, thanks for looking into it, let me know if you want anything tested.

**Comment by atwoz** [comment]
Having the same issue. I think I'm using version 4.0 but I could be wrong. I would happily apply a patch to the driver so as to not wait for a full version release (in case you already have it).

**Comment by cskilbeck** [comment]
I haven't looked into it, sorry, just waiting for a new version.

**Comment by Alvin1Zhang** [comment]
@cskilbeck @atwoz Thanks for reporting and follow-up, we have a fix which is now under internal reviewing, will update once it is available on GitHub. Thanks.

**Comment by koobest** [comment]
Hi, @atwoz
release 4.0 do not have this breaking change, Can you check your IDF version?

**Comment by koobest** [comment]
Hi, @cskilbeck 

the fix of this issue will remove the line 

```length = (off + length) > SOC_RMT_CHANNEL_MEM_WORDS ? (SOC_RMT_CHANNEL_MEM_WORDS - off) : length;```

in 

```static inline void rmt_ll_write_memory(rmt_mem_t *mem, uint32_t channel, const rmt_item32_t *data, uint32_t length, uint32_t off)```

Can you help check if this fix is OK?

@atwoz Can you provide you IDF version?

thanks

**Comment by cskilbeck** [comment]
I'll give it a go and report back.

**Comment by 3miliano** [comment]
@koobest I can confirm that the crash goes away when removing that line. Tested on v4.2.
