### ISSUE TITLE
Cannot exit OTA when disconnect with wifi hostpot (IDFGH-2916)

### ISSUE THREAD

**Issue by binhla** [espressif/esp-idf#4960]
## Environment
- Module or chip used:  ESP32-WROOM-32D
- IDF version: v4.1-dev-2055-gf5b82c5b1
- Build System: Make
- Compiler version: xtensa-esp32-elf-gcc.exe (crosstool-NG esp-2019r2) 8.2.0
- Operating System: Windows
- (Windows only) environment type: MSYS2 mingw32
- Using an IDE: NO
- Power Supply: external 5V

## Problem Description
When tried to FOTA my ESP32 device via a HTTP server, i tested to turn off my wifi hostpot (from my pc). And it seem like ESP32 stucked in this error

> E (53821) TRANS_TCP: tcp_poll_read select error 0, errno = Success, fd = 55
> E (53831) TRANS_TCP: tcp_poll_read select error 0, errno = Success, fd = 55
> E (53831) TRANS_TCP: tcp_poll_read select error 0, errno = Success, fd = 55
> E (53841) TRANS_TCP: tcp_poll_read select error 0, errno = Success, fd = 55
> E (53851) TRANS_TCP: tcp_poll_read select error 0, errno = Success, fd = 55
> E (53861) TRANS_TCP: tcp_poll_read select error 0, errno = Success, fd = 55
> E (53861) TRANS_TCP: tcp_poll_read select error 0, errno = Success, fd = 55

any idea, and how to fix this. I dont want to have reset the ESP32 by reset button or turn off the device

### Steps to reproduce

1. step1: running native ota example with your wifi hostpot or router ssid/pass
2. step2: turn off your hostpot or router

**Comment by Alvin1Zhang** [comment]
@binhla Thanks for reporting. Would you please help provide more details as suggested in the [issue template](https://github.com/espressif/esp-idf/issues/new?assignees=&labels=&template=bug_report.md&title=)? Information like elf, sdk configuration, backtrace, log outputs, commit ID, hardware and etc. would help us debug further. Thanks.

**Comment by binhla** [comment]
> @binhla Thanks for reporting. Would you please help provide more details as suggested in the [issue template](https://github.com/espressif/esp-idf/issues/new?assignees=&labels=&template=bug_report.md&title=)? Information like elf, sdk configuration, backtrace, log outputs, commit ID, hardware and etc. would help us debug further. Thanks.

**Comment by binhla** [comment]
> @binhla Thanks for reporting. Would you please help provide more details as suggested in the [issue template](https://github.com/espressif/esp-idf/issues/new?assignees=&labels=&template=bug_report.md&title=)? Information like elf, sdk configuration, backtrace, log outputs, commit ID, hardware and etc. would help us debug further. Thanks.

Dears, thanks for replying, i added some information, sorry that i cannot share my code

**Comment by Alvin1Zhang** [comment]
@binhla Thanks for reporting, we have a fix internally under reviewing now, will update once it is available on GitHub. Thanks.
