### ISSUE TITLE
BLE MESH sensor server/client example request  (IDFGH-2965)

### ISSUE THREAD

**Issue by sheldon123z** [espressif/esp-idf#4998]
Hi, 
As the topic stated, any BLE mesh sensor server or client examples would be very helpful for developers to develop products with esp-idf framework.   

Thanks!

**Comment by Alvin1Zhang** [comment]
@sheldon123z  Thanks for the feature request, we will look into and evaluate. Thanks.

**Comment by Campou** [comment]
Hi @sheldon123z 

Thanks for the feedback, I will try to provide a sensor model example in the next few weeks.

Thanks.

**Comment by sheldon123z** [comment]
Hi @Campou ,

Thanks for your reply. Since I am using multiple esp32 boards to develop a ble-mesh sensor network, I do want to know if there are specific documents/guidelines that I can use for programming sensor models? 

Much appreciated if you can provide.

Best.

**Comment by nanaadum** [comment]
Hi @Campou, have you made some progress with the sensor model example?  Also, are there any example codes so far that can be edited to become a BLE mesh sensor model?

**Comment by Campou** [comment]
Hi @nanaadum,

The examples about sensor models (client, server and setup server) are ready, waiting to be merged internally. And it will synchronized to Github soon.

Thanks for your patience.

**Comment by nanaadum** [comment]
Hi @Campou,

That's awesome! Thanks for the update.

**Comment by sheldon123z** [comment]
@Campou awesome! I will check it out

**Comment by nanaadum** [comment]
Hi @Campou please can you help me out with where I can find the examples for the sensor models when they come out?
Also please do you have an idea of what day the sensor model code will be synchronized to github?

**Comment by nanaadum** [comment]
Thanks a lot for helping @Campou

**Comment by sheldon123z** [comment]
Hi @Campou , the examples are excellent and they are very helpful!!! Thank you very much! issue closed.

**Comment by nanaadum** [comment]
Hi @Campou thank you so much. Very grateful!!!
