### ISSUE TITLE
MQTT loop strange event triggering (IDFGH-2979)

### ISSUE THREAD

**Issue by rebeliousconformist** [espressif/esp-idf#5011]
Development Kit: [ESP32-Wrover-Kit|

    Kit version (for WroverKit/): [v4]

    Module or chip used: [|ESP32-WROVER-B|

    IDF version :: v4.2-dev-701-g0ae960f2f

    Build System: [|CMake & idf.py]

    Compiler version xtensa-esp32-elf-gcc (crosstool-NG esp-2019r2) 8.2.0

    Operating System: [|Linux|]

    Using an IDE?: [|Yes eclipse & idf.py from command line

    Power Supply: [USB|

## Problem Description

Im trying to achieve the following:
1. connect to a wifi network
2. After the MQTT loop starts then, im starting another parallel task which shall publish MQTT topics.
3. IF the Wifi disconnects, then MQTT client is stopped and the task created should be deleted. 
4. Upon reconnection the  MQTT client shall be restarted and along with the task.

### Expected Behavior
1. Irrespective of disconnection the task shall be delted and recreated without errors.
2. The MQTT event loop events shall be triggered only when the specific event occurs, but they are triggered every instance. 

### Actual Behavior
 Strange behaviour of the event loop. It gets triggered automatically not for a particular event but for all the events mentioned in the event loop enum.

    Development Kit: [ESP32-Wrover-Kit|

    Kit version (for WroverKit/): [v4]

    Module or chip used: [|ESP32-WROVER-B|

    IDF version :: v4.2-dev-701-g0ae960f2f

    Build System: [|CMake & idf.py]

    Compiler version xtensa-esp32-elf-gcc (crosstool-NG esp-2019r2) 8.2.0

    Operating System: [|Linux|]

    Using an IDE?: [|Yes eclipse & idf.py from command line

    Power Supply: [USB|

## Problem Description

Im trying to achieve the following:
1. connect to a wifi network
2. After the MQTT loop starts then, im starting another parallel task which shall publish MQTT topics.
3. IF the Wifi disconnects, then MQTT client is stopped
4. Upon reconnection the  MQTT client shall be restarted and along with the task.

<pre>p: the event id is : 3 
I (101963) MQTT_EXAMPLE: MQTT_EVENT_SUBSCRIBED, msg_id=22790
I (101963) MQTT_EXAMPLE: sent publish successful, msg_id=0
I (101973) HELLO :: sent publish successful, msg_id=272
MQTT loop: the event id is : 5 
I (101983) MQTT_EXAMPLE: MQTT_EVENT_PUBLISHED, msg_id=27724
MQTT loop: the event id is : 6 
I (101993) MQTT_EXAMPLE: MQTT_EVENT_DATA
TOPIC=/topic/qos0
DATA=data
MQTT_EVENT_DATA eventid is=6
MQTT_EVENT_DATA msg_id is=0
MQTT loop: the event id is : 5 
I (102283) MQTT_EXAMPLE: MQTT_EVENT_PUBLISHED, msg_id=29569
MQTT loop: the event id is : 3 
I (102283) MQTT_EXAMPLE: MQTT_EVENT_SUBSCRIBED, msg_id=62414
I (102293) MQTT_EXAMPLE: sent publish successful, msg_id=0
MQTT loop: the event id is : 6 
I (102313) MQTT_EXAMPLE: MQTT_EVENT_DATA
TOPIC=/topic/qos0
DATA=data
MQTT_EVENT_DATA eventid is=6
MQTT_EVENT_DATA msg_id is=0
MQTT loop: the event id is : 5 
I (102323) MQTT_EXAMPLE: MQTT_EVENT_PUBLISHED, msg_id=272
task for loop 963 seconds...
I (102483) HELLO :: sent publish successful, msg_id=47165
I (102483) HELLO :: sent subscribe successful, msg_id=46642
I (102483) HELLO :: sent publish successful, msg_id=3552
MQTT loop: the event id is : 6 
I (102493) MQTT_EXAMPLE: MQTT_EVENT_DATA
TOPIC=/topic/qos0
DATA=data
MQTT_EVENT_DATA eventid is=6
MQTT_EVENT_DATA msg_id is=0
MQTT loop: the event id is : 5 
I (102693) MQTT_EXAMPLE: MQTT_EVENT_PUBLISHED, msg_id=47165
MQTT loop: the event id is : 3 
I (102713) MQTT_EXAMPLE: MQTT_EVENT_SUBSCRIBED, msg_id=46642
I (102713) MQTT_EXAMPLE: sent publish successful, msg_id=0
MQTT loop: the event id is : 5 
I (102903) MQTT_EXAMPLE: MQTT_EVENT_PUBLISHED, msg_id=3552
MQTT loop: the event id is : 6 
I (102923) MQTT_EXAMPLE: MQTT_EVENT_DATA
TOPIC=/topic/qos0
DATA=data
MQTT_EVENT_DATA eventid is=6
MQTT_EVENT_DATA msg_id is=0
task for loop 962 seconds...
I (102993) HELLO :: sent publish successful, msg_id=48502
I (102993) HELLO :: sent subscribe successful, msg_id=40612
I (102993) HELLO :: sent publish successful, msg_id=4225
MQTT loop: the event id is : 5 
I (103303) MQTT_EXAMPLE: MQTT_EVENT_PUBLISHED, msg_id=48502
MQTT loop: the event id is : 3 
I (103313) MQTT_EXAMPLE: MQTT_EVENT_SUBSCRIBED, msg_id=40612
I (103313) MQTT_EXAMPLE: sent publish successful, msg_id=0
MQTT loop: the event id is : 5 
I (103323) MQTT_EXAMPLE: MQTT_EVENT_PUBLISHED, msg_id=4225
task for loop 961 seconds...
I (103503) HELLO :: sent publish successful, msg_id=44214
I (103503) HELLO :: sent subscribe successful, msg_id=51556
I (103503) HELLO :: sent publish successful, msg_id=11990
MQTT loop: the event id is : 6 
I (103513) MQTT_EXAMPLE: MQTT_EVENT_DATA
TOPIC=/topic/qos0
DATA=data
MQTT_EVENT_DATA eventid is=6
MQTT_EVENT_DATA msg_id is=0
task for loop 960 seconds...
I (104013) HELLO :: sent publish successful, msg_id=9799
I (104013) HELLO :: sent subscribe successful, msg_id=19144
I (104013) HELLO :: sent publish successful, msg_id=42805
task for loop 959 seconds...
I (104523) HELLO :: sent publish successful, msg_id=26354
I (104523) HELLO :: sent subscribe successful, msg_id=7084
I (104533) HELLO :: sent publish successful, msg_id=32600
MQTT loop: the event id is : 5 
I (104743) MQTT_EXAMPLE: MQTT_EVENT_PUBLISHED, msg_id=44214
MQTT loop: the event id is : 3 
I (104743) MQTT_EXAMPLE: MQTT_EVENT_SUBSCRIBED, msg_id=51556
I (104753) MQTT_EXAMPLE: sent publish successful, msg_id=0
MQTT loop: the event id is : 5 
I (104753) MQTT_EXAMPLE: MQTT_EVENT_PUBLISHED, msg_id=11990
MQTT loop: the event id is : 5 
I (104763) MQTT_EXAMPLE: MQTT_EVENT_PUBLISHED, msg_id=9799
MQTT loop: the event id is : 3 
I (104773) MQTT_EXAMPLE: MQTT_EVENT_SUBSCRIBED, msg_id=19144
I (104783) MQTT_EXAMPLE: sent publish successful, msg_id=0
MQTT loop: the event id is : 5 
I (104793) MQTT_EXAMPLE: MQTT_EVENT_PUBLISHED, msg_id=42805
MQTT loop: the event id is : 5 
I (104803) MQTT_EXAMPLE: MQTT_EVENT_PUBLISHED, msg_id=26354
MQTT loop: the event id is : 3 
I (104943) MQTT_EXAMPLE: MQTT_EVENT_SUBSCRIBED, msg_id=7084
I (104943) MQTT_EXAMPLE: sent publish successful, msg_id=0
MQTT loop: the event id is : 5 
I (104963) MQTT_EXAMPLE: MQTT_EVENT_PUBLISHED, msg_id=32600
task for loop 958 seconds...
I (105033) HELLO :: sent publish successful, msg_id=13132
I (105033) HELLO :: sent subscribe successful, msg_id=64594
I (105033) HELLO :: sent publish successful, msg_id=31710
MQTT loop: the event id is : 6 
I (105163) MQTT_EXAMPLE: MQTT_EVENT_DATA
TOPIC=/topic/qos0
DATA=data
MQTT_EVENT_DATA eventid is=6
MQTT_EVENT_DATA msg_id is=0
MQTT loop: the event id is : 6 
I (105173) MQTT_EXAMPLE: MQTT_EVENT_DATA
TOPIC=/topic/qos0
DATA=data
MQTT_EVENT_DATA e</pre>

### Expected Behavior
1. The MQTT event loop events shall be triggered only when the specific event occurs, but they are triggered every instance. 

### Actual Behavior
 Strange behaviour of the event loop. It gets triggered automatically not for a particular event but for all the events mentioned in the event loop enum.

<pre>p: the event id is : 3 
I (101963) MQTT_EXAMPLE: MQTT_EVENT_SUBSCRIBED, msg_id=22790
I (101963) MQTT_EXAMPLE: sent publish successful, msg_id=0
I (101973) HELLO :: sent publish successful, msg_id=272
MQTT loop: the event id is : 5 
I (101983) MQTT_EXAMPLE: MQTT_EVENT_PUBLISHED, msg_id=27724
MQTT loop: the event id is : 6 
I (101993) MQTT_EXAMPLE: MQTT_EVENT_DATA
TOPIC=/topic/qos0
DATA=data
MQTT_EVENT_DATA eventid is=6
MQTT_EVENT_DATA msg_id is=0
MQTT loop: the event id is : 5 
I (102283) MQTT_EXAMPLE: MQTT_EVENT_PUBLISHED, msg_id=29569
MQTT loop: the event id is : 3 
I (102283) MQTT_EXAMPLE: MQTT_EVENT_SUBSCRIBED, msg_id=62414
I (102293) MQTT_EXAMPLE: sent publish successful, msg_id=0
MQTT loop: the event id is : 6 
I (102313) MQTT_EXAMPLE: MQTT_EVENT_DATA
TOPIC=/topic/qos0
DATA=data
MQTT_EVENT_DATA eventid is=6
MQTT_EVENT_DATA msg_id is=0
MQTT loop: the event id is : 5 
I (102323) MQTT_EXAMPLE: MQTT_EVENT_PUBLISHED, msg_id=272
task for loop 963 seconds...
I (102483) HELLO :: sent publish successful, msg_id=47165
I (102483) HELLO :: sent subscribe successful, msg_id=46642
I (102483) HELLO :: sent publish successful, msg_id=3552
MQTT loop: the event id is : 6 
I (102493) MQTT_EXAMPLE: MQTT_EVENT_DATA
TOPIC=/topic/qos0
DATA=data
MQTT_EVENT_DATA eventid is=6
MQTT_EVENT_DATA msg_id is=0
MQTT loop: the event id is : 5 
I (102693) MQTT_EXAMPLE: MQTT_EVENT_PUBLISHED, msg_id=47165
MQTT loop: the event id is : 3 
I (102713) MQTT_EXAMPLE: MQTT_EVENT_SUBSCRIBED, msg_id=46642
I (102713) MQTT_EXAMPLE: sent publish successful, msg_id=0
MQTT loop: the event id is : 5 
I (102903) MQTT_EXAMPLE: MQTT_EVENT_PUBLISHED, msg_id=3552
MQTT loop: the event id is : 6 
I (102923) MQTT_EXAMPLE: MQTT_EVENT_DATA
TOPIC=/topic/qos0
DATA=data
MQTT_EVENT_DATA eventid is=6
MQTT_EVENT_DATA msg_id is=0
task for loop 962 seconds...
I (102993) HELLO :: sent publish successful, msg_id=48502
I (102993) HELLO :: sent subscribe successful, msg_id=40612
I (102993) HELLO :: sent publish successful, msg_id=4225
MQTT loop: the event id is : 5 
I (103303) MQTT_EXAMPLE: MQTT_EVENT_PUBLISHED, msg_id=48502
MQTT loop: the event id is : 3 
I (103313) MQTT_EXAMPLE: MQTT_EVENT_SUBSCRIBED, msg_id=40612
I (103313) MQTT_EXAMPLE: sent publish successful, msg_id=0
MQTT loop: the event id is : 5 
I (103323) MQTT_EXAMPLE: MQTT_EVENT_PUBLISHED, msg_id=4225
task for loop 961 seconds...
I (103503) HELLO :: sent publish successful, msg_id=44214
I (103503) HELLO :: sent subscribe successful, msg_id=51556
I (103503) HELLO :: sent publish successful, msg_id=11990
MQTT loop: the event id is : 6 
I (103513) MQTT_EXAMPLE: MQTT_EVENT_DATA
TOPIC=/topic/qos0
DATA=data
MQTT_EVENT_DATA eventid is=6
MQTT_EVENT_DATA msg_id is=0
task for loop 960 seconds...
I (104013) HELLO :: sent publish successful, msg_id=9799
I (104013) HELLO :: sent subscribe successful, msg_id=19144
I (104013) HELLO :: sent publish successful, msg_id=42805
task for loop 959 seconds...
I (104523) HELLO :: sent publish successful, msg_id=26354
I (104523) HELLO :: sent subscribe successful, msg_id=7084
I (104533) HELLO :: sent publish successful, msg_id=32600
MQTT loop: the event id is : 5 
I (104743) MQTT_EXAMPLE: MQTT_EVENT_PUBLISHED, msg_id=44214
MQTT loop: the event id is : 3 
I (104743) MQTT_EXAMPLE: MQTT_EVENT_SUBSCRIBED, msg_id=51556
I (104753) MQTT_EXAMPLE: sent publish successful, msg_id=0
MQTT loop: the event id is : 5 
I (104753) MQTT_EXAMPLE: MQTT_EVENT_PUBLISHED, msg_id=11990
MQTT loop: the event id is : 5 
I (104763) MQTT_EXAMPLE: MQTT_EVENT_PUBLISHED, msg_id=9799
MQTT loop: the event id is : 3 
I (104773) MQTT_EXAMPLE: MQTT_EVENT_SUBSCRIBED, msg_id=19144
I (104783) MQTT_EXAMPLE: sent publish successful, msg_id=0
MQTT loop: the event id is : 5 
I (104793) MQTT_EXAMPLE: MQTT_EVENT_PUBLISHED, msg_id=42805
MQTT loop: the event id is : 5 
I (104803) MQTT_EXAMPLE: MQTT_EVENT_PUBLISHED, msg_id=26354
MQTT loop: the event id is : 3 
I (104943) MQTT_EXAMPLE: MQTT_EVENT_SUBSCRIBED, msg_id=7084
I (104943) MQTT_EXAMPLE: sent publish successful, msg_id=0
MQTT loop: the event id is : 5 
I (104963) MQTT_EXAMPLE: MQTT_EVENT_PUBLISHED, msg_id=32600
task for loop 958 seconds...
I (105033) HELLO :: sent publish successful, msg_id=13132
I (105033) HELLO :: sent subscribe successful, msg_id=64594
I (105033) HELLO :: sent publish successful, msg_id=31710
MQTT loop: the event id is : 6 
I (105163) MQTT_EXAMPLE: MQTT_EVENT_DATA
TOPIC=/topic/qos0
DATA=data
MQTT_EVENT_DATA eventid is=6
MQTT_EVENT_DATA msg_id is=0
MQTT loop: the event id is : 6 
I (105173) MQTT_EXAMPLE: MQTT_EVENT_DATA
TOPIC=/topic/qos0
DATA=data
MQTT_EVENT_DATA e</pre>

### Steps to reproduce
see attached project zip file please. 
[station_issue.zip](https://github.com/espressif/esp-idf/files/4393803/station_issue.zip)

### Steps to reproduce
see attached project zip file please. 
[station_issue.zip](https://github.com/espressif/esp-idf/files/4393803/station_issue.zip)

**Comment by Alvin1Zhang** [comment]
@rebeliousconformist Thanks for reporting, we will look into.

**Comment by david-cermak** [comment]
Hi @rebeliousconformist 

seen your code and it looks like you're calling:
```
    esp_mqtt_client_register_event(client, ESP_EVENT_ANY_ID, mqtt_event_handler, client);
```
to register the event handler for `ESP_EVENT_ANY_ID` (==all events from `MQTT_EVENTS` base).
You might want to register a separate handler just for the specific event id using that event number, for example:
``` cpp
    esp_mqtt_client_register_event(client, MQTT_EVENT_CONNECTED, mqtt_connect_handler, client);
```
For registering a handler only for connection events.

**Comment by Alvin1Zhang** [comment]
@rebeliousconformist Thanks for reporting. Would you please help share if any updates or details for this issue? Thanks.

**Comment by rebeliousconformist** [comment]
@Alvin1Zhang would like to close it as after the new update the events make sense.

**Comment by Alvin1Zhang** [comment]
@rebeliousconformist Thanks for sharing the updates.
