### ISSUE TITLE
Soft AP mode  with  transfer data (IDFGH-2980)

### ISSUE THREAD

**Issue by varunsavita** [espressif/esp-idf#5012]
I am able to connect in soft AP mode but not able to transfer data.
SDK latest version

**Comment by Alvin1Zhang** [comment]
Thanks for reporting. Would you please help provide more details as suggested in the [issue template](https://github.com/espressif/esp-idf/issues/new?assignees=&labels=&template=bug_report.md&title=)? Information like elf, sdk configuration, backtrace, log outputs, commit ID, hardware and etc. would help us debug further. Thanks. @varunsavita

**Comment by varunsavita** [comment]
@Alvin1Zhang  Thanks for the response.
(https://docs.espressif.com/projects/esp-idf/en/latest
IDF branch master
- Development Kit:     ESP32-DevKitC
- Module or chip used:  ESP32-WROOM-32
- Build System:         Make
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it):
- Operating System:     Windows
- (Windows only) environment type: MSYS2 mingw32
- Power Supply:         USB


-----------Code -------------
 

#include <sys/param.h>
#include "esp_netif.h"
#include "esp_eth.h"

#include <esp_http_server.h>

#include <string.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "esp_system.h"
#include "esp_wifi.h"
#include "esp_event.h"
#include "esp_log.h"
#include "nvs_flash.h"

#include "lwip/err.h"
#include "lwip/sys.h"

/* The examples use WiFi configuration that you can set via project configuration menu.

   If you'd rather not, just change the below entries to strings with
   the config you want - ie #define EXAMPLE_WIFI_SSID "mywifissid"
*/
#define EXAMPLE_ESP_WIFI_SSID      CONFIG_ESP_WIFI_SSID
#define EXAMPLE_ESP_WIFI_PASS      CONFIG_ESP_WIFI_PASSWORD
#define EXAMPLE_MAX_STA_CONN       CONFIG_ESP_MAX_STA_CONN

/* A simple example that demonstrates how to create GET and POST
 * handlers for the web server.
 */

static const char *TAG = "wifi_AP_WEBserver";

//------------------------------------------------------------------------------
/* An HTTP GET handler */
static esp_err_t hello_get_handler(httpd_req_t *req)
{
    char*  buf;
    size_t buf_len;

    /* Get header value string length and allocate memory for length + 1,
     * extra byte for null termination */
    buf_len = httpd_req_get_hdr_value_len(req, "Host") + 1;
    if (buf_len > 1)
    {
        buf = malloc(buf_len);
        /* Copy null terminated value string into buffer */
        if (httpd_req_get_hdr_value_str(req, "Host", buf, buf_len) == ESP_OK)
        {
            ESP_LOGI(TAG, "Found header => Host: %s", buf);
        }
        free(buf);
    }

    buf_len = httpd_req_get_hdr_value_len(req, "Test-Header-2") + 1;
    if (buf_len > 1)
    {
        buf = malloc(buf_len);
        if (httpd_req_get_hdr_value_str(req, "Test-Header-2", buf, buf_len) == ESP_OK)
        {
            ESP_LOGI(TAG, "Found header => Test-Header-2: %s", buf);
        }
        free(buf);
    }

    buf_len = httpd_req_get_hdr_value_len(req, "Test-Header-1") + 1;
    if (buf_len > 1)
    {
        buf = malloc(buf_len);
        if (httpd_req_get_hdr_value_str(req, "Test-Header-1", buf, buf_len) == ESP_OK)
        {
            ESP_LOGI(TAG, "Found header => Test-Header-1: %s", buf);
        }
        free(buf);
    }

    /* Read URL query string length and allocate memory for length + 1,
     * extra byte for null termination */
    buf_len = httpd_req_get_url_query_len(req) + 1;
    if (buf_len > 1) {
        buf = malloc(buf_len);
        if (httpd_req_get_url_query_str(req, buf, buf_len) == ESP_OK)
        {
            ESP_LOGI(TAG, "Found URL query => %s", buf);
            char param[32];
            /* Get value of expected key from query string */
            if (httpd_query_key_value(buf, "query1", param, sizeof(param)) == ESP_OK)
            {
                ESP_LOGI(TAG, "Found URL query parameter => query1=%s", param);
            }
            if (httpd_query_key_value(buf, "query3", param, sizeof(param)) == ESP_OK)
            {
                ESP_LOGI(TAG, "Found URL query parameter => query3=%s", param);
            }
            if (httpd_query_key_value(buf, "query2", param, sizeof(param)) == ESP_OK)
            {
                ESP_LOGI(TAG, "Found URL query parameter => query2=%s", param);
            }
        }
        free(buf);
    }

    /* Set some custom headers */
	 // testing --1
    httpd_resp_set_hdr(req, "Custom-Header-2","Access-Control-Allow-Origin: *");
    httpd_resp_set_hdr(req, "Custom-Header-2", "{\"m\":\"3C:71:BF:4C:A9:E5\"}");
	
	//httpd_resp_send(req, "{"m":"3C:71:BF:4C:A9:E5"}", strlen("{"m":"3C:71:BF:4C:A9:E5"}"));
	
    /* Send response with custom headers and body set as the
     * string passed in user context*/
    const char* resp_str = (const char*) req->user_ctx;
    httpd_resp_send(req, resp_str, strlen(resp_str));

    /* After sending the HTTP response the old HTTP request
     * headers are lost. Check if HTTP request headers can be read now. */
    if (httpd_req_get_hdr_value_len(req, "Host") == 0)
    {
        ESP_LOGI(TAG, "Request headers lost");
    }
    return ESP_OK;
}

// static const httpd_uri_t hello = {
    // .uri       = "/hello",
    // .method    = HTTP_GET,
    // .handler   = hello_get_handler,
    // /* Let's pass response string in user
     // * context to demonstrate it's usage */
    // .user_ctx  = "Hello World!"
// };
//char testing[] = "{\"m\":\"3C:71:BF:4C:A9:E5\"}";

static const httpd_uri_t hello = {
    .uri       = "/23",
    .method    = HTTP_GET,
    .handler   = hello_get_handler,
	.user_ctx  = "{\"m\":\"3C:21:BF:AC:A9:E5\"}"
};

/* An HTTP POST handler */

static esp_err_t echo_post_handler(httpd_req_t *req)
{
    char buf[100];
    int ret, remaining = req->content_len;

    while (remaining > 0) {
        /* Read the data for the request */
        if ((ret = httpd_req_recv(req, buf,
                        MIN(remaining, sizeof(buf)))) <= 0) {
            if (ret == HTTPD_SOCK_ERR_TIMEOUT) {
                /* Retry receiving if timeout occurred */
                continue;
            }
            return ESP_FAIL;
        }

        /* Send back the same data */
        httpd_resp_send_chunk(req, buf, ret);
        remaining -= ret;

        /* Log data received */
        ESP_LOGI(TAG, "=========== RECEIVED DATA ==========");
        ESP_LOGI(TAG, "%.*s", ret, buf);
        ESP_LOGI(TAG, "====================================");
    }

    // End response
    httpd_resp_send_chunk(req, NULL, 0);
    return ESP_OK;
}

static const httpd_uri_t echo = {
    .uri       = "/echo",
    .method    = HTTP_POST,
    .handler   = echo_post_handler,
    .user_ctx  = NULL
};


esp_err_t http_404_error_handler(httpd_req_t *req, httpd_err_code_t err)
{
    if (strcmp("/hello", req->uri) == 0) {
        httpd_resp_send_err(req, HTTPD_404_NOT_FOUND, "/hello URI is not available");
        /* Return ESP_OK to keep underlying socket open */
        return ESP_OK;
    } else if (strcmp("/echo", req->uri) == 0) {
        httpd_resp_send_err(req, HTTPD_404_NOT_FOUND, "/echo URI is not available");
        /* Return ESP_FAIL to close underlying socket */
        return ESP_FAIL;
    }
    /* For any other URI send 404 and close socket */
    httpd_resp_send_err(req, HTTPD_404_NOT_FOUND, "Some 404 error message");
    return ESP_FAIL;
}

/* An HTTP PUT handler. This demonstrates realtime
 * registration and deregistration of URI handlers
 */
static esp_err_t ctrl_put_handler(httpd_req_t *req)
{
    char buf;
    int ret;

    if ((ret = httpd_req_recv(req, &buf, 1)) <= 0) {
        if (ret == HTTPD_SOCK_ERR_TIMEOUT) {
            httpd_resp_send_408(req);
        }
        return ESP_FAIL;
    }

    if (buf == '0') {
        /* URI handlers can be unregistered using the uri string */
        ESP_LOGI(TAG, "Unregistering /hello and /echo URIs");
        httpd_unregister_uri(req->handle, "/hello");
        httpd_unregister_uri(req->handle, "/echo");
        /* Register the custom error handler */
        httpd_register_err_handler(req->handle, HTTPD_404_NOT_FOUND, http_404_error_handler);
    }
    else {
        ESP_LOGI(TAG, "Registering /hello and /echo URIs");
        httpd_register_uri_handler(req->handle, &hello);
        httpd_register_uri_handler(req->handle, &echo);
        /* Unregister custom error handler */
        httpd_register_err_handler(req->handle, HTTPD_404_NOT_FOUND, NULL);
    }

    /* Respond with empty body */
    httpd_resp_send(req, NULL, 0);
    return ESP_OK;
}

static const httpd_uri_t ctrl = {
    .uri       = "/ctrl",
    .method    = HTTP_PUT,
    .handler   = ctrl_put_handler,
    .user_ctx  = NULL
};

static httpd_handle_t start_webserver(void)
{
    httpd_handle_t server = NULL;
    httpd_config_t config = HTTPD_DEFAULT_CONFIG();

    // Start the httpd server
    ESP_LOGI(TAG, "Starting server on port: '%d'", config.server_port);
    if (httpd_start(&server, &config) == ESP_OK) {
        // Set URI handlers
        ESP_LOGI(TAG, "Registering URI handlers");
        httpd_register_uri_handler(server, &hello);
        httpd_register_uri_handler(server, &echo);
        httpd_register_uri_handler(server, &ctrl);
        return server;
    }

    ESP_LOGI(TAG, "Error starting server!");
    return NULL;
}


static void wifi_event_handler(void* arg, esp_event_base_t event_base, int32_t event_id, void* event_data)
{
    if (event_id == WIFI_EVENT_AP_STACONNECTED) {
        wifi_event_ap_staconnected_t* event = (wifi_event_ap_staconnected_t*) event_data;
        ESP_LOGI(TAG, "station "MACSTR" join, AID=%d",
                 MAC2STR(event->mac), event->aid);
    } else if (event_id == WIFI_EVENT_AP_STADISCONNECTED) {
        wifi_event_ap_stadisconnected_t* event = (wifi_event_ap_stadisconnected_t*) event_data;
        ESP_LOGI(TAG, "station "MACSTR" leave, AID=%d",
                 MAC2STR(event->mac), event->aid);
    }
}

esp_err_t wifi_init_softap(void)
{
    //esp_netif_init();
    //ESP_ERROR_CHECK(esp_event_loop_create_default());
    esp_netif_create_default_wifi_ap();

    wifi_init_config_t cfg = WIFI_INIT_CONFIG_DEFAULT();
    ESP_ERROR_CHECK(esp_wifi_init(&cfg));

    ESP_ERROR_CHECK(esp_event_handler_register(WIFI_EVENT, ESP_EVENT_ANY_ID, &wifi_event_handler, NULL));

    wifi_config_t wifi_config = {
        .ap = {
            .ssid = EXAMPLE_ESP_WIFI_SSID,
            .ssid_len = strlen(EXAMPLE_ESP_WIFI_SSID),
            .password = EXAMPLE_ESP_WIFI_PASS,
            .max_connection = 1,//EXAMPLE_MAX_STA_CONN,
            .authmode = WIFI_AUTH_WPA_WPA2_PSK
        },
    };
    if (strlen(EXAMPLE_ESP_WIFI_PASS) == 0) {
        wifi_config.ap.authmode = WIFI_AUTH_OPEN;
    }

    ESP_ERROR_CHECK(esp_wifi_set_mode(WIFI_MODE_AP));
    ESP_ERROR_CHECK(esp_wifi_set_config(ESP_IF_WIFI_AP, &wifi_config));
    ESP_ERROR_CHECK(esp_wifi_start());

    ESP_LOGI(TAG, "wifi_init_softap finished. SSID:%s password:%s",
             EXAMPLE_ESP_WIFI_SSID, EXAMPLE_ESP_WIFI_PASS);
    return ESP_OK;
}
//------------------------------------------------------------------------------

void app_main(void)
{
    httpd_handle_t server = NULL;


    ESP_LOGI(TAG, "NVS init");
    ESP_ERROR_CHECK(nvs_flash_init());
    //tcpip_adapter_init();
    esp_netif_init();

    ESP_LOGI(TAG, "Eventloop create");
    ESP_ERROR_CHECK(esp_event_loop_create_default());

    /* This helper function configures Wi-Fi or Ethernet, as selected in menuconfig.
     * Read "Establishing Wi-Fi or Ethernet Connection" section in
     * examples/protocols/README.md for more information about this function.
     */
    //ESP_ERROR_CHECK(example_connect());
    ESP_LOGI(TAG, "init softAP");
    ESP_ERROR_CHECK(wifi_init_softap());

    /* Register event handlers to stop the server when Wi-Fi or Ethernet is disconnected,
     * and re-start it upon connection.
     */
#ifdef CONFIG_EXAMPLE_CONNECT_WIFI
    ESP_ERROR_CHECK(esp_event_handler_register(IP_EVENT, IP_EVENT_STA_GOT_IP, &connect_handler, &server));
    ESP_ERROR_CHECK(esp_event_handler_register(WIFI_EVENT, WIFI_EVENT_STA_DISCONNECTED, &disconnect_handler, &server));
#endif // CONFIG_EXAMPLE_CONNECT_WIFI
#ifdef CONFIG_EXAMPLE_CONNECT_ETHERNET
    ESP_ERROR_CHECK(esp_event_handler_register(IP_EVENT, IP_EVENT_ETH_GOT_IP, &connect_handler, &server));
    ESP_ERROR_CHECK(esp_event_handler_register(ETH_EVENT, ETHERNET_EVENT_DISCONNECTED, &disconnect_handler, &server));
#endif // CONFIG_EXAMPLE_CONNECT_ETHERNET

    /* Start the server for the first time */
    server = start_webserver();
}
![image](https://user-images.githubusercontent.com/42342764/77957572-50698980-72f1-11ea-9c7e-9dd7e1e4a2eb.png)

![image](https://user-images.githubusercontent.com/42342764/77957736-8eff4400-72f1-11ea-9ede-13b5e7e9dbd1.png)

Please guide me where is wrong ..

**Comment by Alvin1Zhang** [comment]
@varunsavita Thanks for providing the details, we will look into. Thanks.

**Comment by varunsavita** [comment]
@Alvin1Zhang 
Please guide me on how to solve it.

**Comment by Alvin1Zhang** [comment]
@varunsavita Thanks for the follow up and sorry for slow turnaround. @mahavirj Please help, thanks.

**Comment by mahavirj** [comment]
@varunsavita 

Per title of issue it seems you could connect to SoftAP interface but could not access `uri` handlers registered with HTTP server.

 - Can you please confirm that you can access `http://<soft-ap-ip>/hello` or `http://<soft-ap-ip>/echo` when you flash default web server example from browser or equivalent HTTP client?
 - If answer to above is yes, maybe explain your problem in more elaborate way, e.g. whether you are trying to register some custom handler, what do you expect from that handler etc. (or maybe post specific code snippet where you think you are facing problem), this will allow for much faster help.

Thanks.

**Comment by varunsavita** [comment]
Hi @mahavirj 
First, I create SoftAP mode with HTTP server(simple code example).
When code uploaded then I have a mobile app,
First< I connected WiFi in SoftAP mode, then send **get request - 192.168.4.1/23** 
I replaced hello by 23
I want to send header response "Access-Control-Allow-Origin:"

**Comment by mahavirj** [comment]
@varunsavita Did you try using `httpd_resp_set_hdr(req, "Access-Control-Allow-Origin",  "<value_string>")`?

**Comment by varunsavita** [comment]
thanks @mahavirj 
I will try 
I got in device 
 I (191756) wifi_AP_WEBserver: Request headers lost
I (193296) wifi_AP_WEBserver: Request headers lost

**Comment by varunsavita** [comment]
@mahavirj 
Thank you for supporting,
Actually, I want to read unregister uri in code but not able.
able to do register uri and taken action accordingly.
I want to do unregister uri to register in code 
Ex- 192.168.4.1\SSID:anything

**Comment by varunsavita** [comment]
@mahavirj @Alvin1Zhang 
Please reply on this topic

**Comment by Alvin1Zhang** [comment]
@varunsavita Thanks for the follow up, but according to your updates, we are still not clear what you would like to achieve and the details are not enough for us to move forward. Would you please help share more details suggested by @mahavirj ? Thanks.

**Comment by varunsavita** [comment]
Thank you for replying,
I have a project - 
**The device(esp32) reads real-time from the sensor and sends it to MQTT**.
Require Part -- WiFi credential change frequently as per client 
I have a mobile app to change the credential 
Ready - Mobile APP
Mobile APP send to 4 API
1:- static IP(AP mode)/23  -- start the config
2:- static IP(AP mode)/SSID: variable string  ---  set SSID 
3:- static IP(AP mode)/password: variable string --- set a password
4:- static IP(AP mode)/0 -- Done

static IP(AP mode)/23  and static IP(AP mode)/0 are fixed API

I used to code for API fixed  

**httpd_register_uri_handler(server, &API);

static const httpd_uri_t API= {
    .uri       = "/23",
    .method    = HTTP_GET,
    .handler   = hello_get_handler,
    .user_ctx  = "Got response"
};**

/*-----  not fixed API ------*/
2:- static IP(AP mode)/SSID: variable string  ---  set SSID 
3:- static IP(AP mode)/password: variable string --- set a password

Ex- /SSID: variable string
/SSID:  -- fixed part
variable string  -- vary part i have to store it.

Error
a:- (186995) httpd_uri: httpd_uri: URI '/PASSWORD:vakd' not found  
b:- httpd_resp_send_err: 404 Not Found - This URI does not exist

**Error-  a** from from   function **esp_err_t httpd_uri(struct httpd_data *hd)**  and file name httpd_uri.c
Error - b from from function **esp_err_t httpd_resp_send_err(httpd_req_t *req, httpd_err_code_t error, const char *usr_msg)** file name httpd_txrx.c

**I want to do unregister uri to register in the main code**
Require -SSID and PASSWORD

Please guide me on how to implement it let me know you require more info.
Please give me another option for a fast conversion ex - skype, WeChat, Whatsapp.

**Comment by shubhamkulkarni97** [comment]
@varunsavita 
>I want to do unregister uri to register in the main code

Why do you need to unregister an uri? Instead you can register multiple URIs.

For sending SSID and password, you can make a simple POST request by registering uri as demonstrated here: https://github.com/espressif/esp-idf/blob/d85d3d969ff4b42e2616fd40973d637ff337fae6/examples/protocols/http_server/simple/main/main.c#L145

Open terminal and run `curl -d "SSID=<your_ssid>" -X POST http://<your_ip>:80/<post_uri>` to send post request.

 
> Please guide me on how to implement it let me know you require more info.
> Please give me another option for a fast conversion ex - skype, WeChat, Whatsapp.

For faster communication you may post the question on ESP32 forum (https://www.esp32.com) instead of GitHub.

**Comment by varunsavita** [comment]
@shubhamkulkarni97 Thank you so much 
> For sending SSID and password, you can make a simple POST request by registering uri as demonstrated here:
Mobile APP is read, and my bad situation, I will have to receive from all get methods.
No choice to change architecture.

**Comment by shubhamkulkarni97** [comment]
@varunsavita 

Can you try `http://<soft_ap_ip>/hello?<ssid>=<your_ssid>` and check if it helps?

**Comment by varunsavita** [comment]
@shubhamkulkarni97 

> http://<soft_ap_ip>/hello?<ssid>=<your_ssid>
where  can I use it in code (device -esp32)

You mean
**static const httpd_uri_t API= {
.uri = "/23?SSID",
.method = HTTP_GET,
.handler = hello_get_handler,
.user_ctx = "Got response"
};** 

> http://<soft_ap_ip>/hello?<ssid>=<**your_ssid**>
Your_ssid came from mobile app.

**Comment by shubhamkulkarni97** [comment]
Can you try following steps:

* Run simple http_server example in ESP-IDF
* Make a GET request from browser/app using `http://<soft_ap_ip>/hello?<ssid>=<your_ssid>` format.

I tried at my side and pasting output here:
```
I (32178) example: Found header => Host: 192.168.43.59
I (32178) example: Found URL query => ssid=Test
```

**Comment by varunsavita** [comment]
![image](https://user-images.githubusercontent.com/42342764/79832726-ab117500-83c7-11ea-9f86-c1afa28b73f9.png)

 **GET request from browser/app using http://<soft_ap_ip>/hello?<ssid>=<your_ssid> format.**
@shubhamkulkarni97 Thank you for the useful info.
I added Screenshot.
My bad situation, Mobile App is ready, 
Get fixed -- static IP/ssid:my_ssid
I will have to work on only Get fixed -- static IP/ssid:my_ssid

**Comment by shubhamkulkarni97** [comment]
> Can we change something like in" Found URL query"
> **? replace by :**
> Then the problem will solve it

@varunsavita This cannot be changed as format is defined by protocol (HTTP)

**Comment by varunsavita** [comment]
@shubhamkulkarni97 
Thank you for the answer,
Please guide me on another way to solve it in the device code.

**Comment by varunsavita** [comment]
Thank you @shubhamkulkarni97  @mahavirj 
Could I read the message (GET request from browser **http://<soft_ap_ip>/SSID:varun.**) in main.c 
Then I filter it from message.
It is not possible then , please guide me on how to solve this problem.

**Comment by varunsavita** [comment]
@Alvin1Zhang @shubhamkulkarni97 @mahavirj 
Please guys, Is it possible to solve it or not?

**Comment by shubhamkulkarni97** [comment]
@varunsavita This change specific to this application cannot be done. Thanks.
