### ISSUE TITLE
BLufi Example on ESP-IDF3? (IDFGH-2983)

### ISSUE THREAD

**Issue by DasVoelkel** [espressif/esp-idf#5015]
Just wanted to ask if the example is still on V3, i assume as much as it wasn't updated since the V4 drop.
Or is V4 backwards compatible with this code?

**Comment by Alvin1Zhang** [comment]
@DasVoelkel Thanks for reporting. Would you please help provide more details as suggested in the [issue template](https://github.com/espressif/esp-idf/issues/new?assignees=&labels=&template=bug_report.md&title=)? Information like elf, sdk configuration, backtrace, log outputs, commit ID, hardware and etc. would help us debug further. Thanks.

**Comment by DasVoelkel** [comment]
Nvm, I think it's just outdated, but it's easy to get to the new version or search for analog functionality
