### ISSUE TITLE
Tools install in eclipse just dies. (IDFGH-2993)

### ISSUE THREAD

**Issue by umfundi** [espressif/esp-idf#5025]
win 10 64, 32g memory

latest copy of esp-idf cloned into local drive.

latest eclipse environment, updated.

running 'Tools Install' 

Nothing, no popups, no error report no feedback.

Running 'list installed tools'  same thing.

**Comment by umfundi** [comment]
esp p[lugin is installed

**Comment by kolipakakondal** [comment]
Hi @umfundi Could you please check this thread https://github.com/espressif/idf-eclipse-plugin/issues/63#issuecomment-605502100 You might be having the same issue.

To check further on this, could you please provide the error log https://github.com/espressif/idf-eclipse-plugin#error-log

Also, provide the Eclipse configuration and plugin details that you're using. Please attach the file.
`Help > About Eclipse >Installation Details > Configuration
`

**Comment by kolipakakondal** [comment]
You can also raise the issues directly here https://github.com/espressif/idf-eclipse-plugin/issues to get a quicker response.

**Comment by umfundi** [comment]
hmmm. Ok that Git path caught me. but it has moved on to a slightly different error now. 

Complaining about something not being a valid win32 executable. Trying to run idf_tools.py itself instead of via the Python interpreter.

Then tried again and switched to Python 3.6 ..... strangely that appears to have worked but still no tools available .... no tools listed when list installed tools is selected - Python path appears to be null.

This was a 'by the book' install, frustrating that it's so broken

**Comment by kolipakakondal** [comment]
Any python versions listed in the install tools dialog? It reads the python versions from the windows registry. Please check.
```
HKEY_CURRENT_USER\SOFTWARE\Python\PythonCore\
HKEY_LOCAL_MACHINE\SOFTWARE\Python\PythonCore\
```

**Comment by umfundi** [comment]
3.8 and 3.6 listed in the dialog
3.8 is in HKEY_CURRENT_USER\SOFTWARE\Python\PythonCore\ along with 2.4,2.6 and a few others
3.6 is in HKEY_LOCAL_MACHINE\SOFTWARE\Python\PythonCore\ and its path leads to the VS location.


exported the 3.8 keys and modified them to HKEY_LOCAL_MACHINE then imported them back to registry. 3.6 deleted.

list tools in eclipse now runs and displays the following on the console.

![image](https://user-images.githubusercontent.com/2498620/77993470-254a5e80-7320-11ea-8bf5-ad7955359b0f.png)

the log file however still says its failing in some way 

![image](https://user-images.githubusercontent.com/2498620/77993570-4ca12b80-7320-11ea-89d7-8970f2d332d1.png)

and the sdkconfig tool is not working.

**Comment by umfundi** [comment]
A project compile however now seems to work.

**Comment by umfundi** [comment]
it looks like the steps I took have got me a working install.
