### ISSUE TITLE
Write to FAT disk return success when disk full (IDFGH-2995)

### ISSUE THREAD

**Issue by mikhail-khalizev** [espressif/esp-idf#5027]
## Environment

- Development Kit:     ESP32-DevKitC
- Kit version (for WroverKit/PicoKit/DevKitC): v4
- Module or chip used:  ESP32-WROOM-32D
- IDF version (run ``git describe --tags`` to find it): v4.0-276-g57a5a486f
- Build System:         Make
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it): xtensa-esp32-elf-gcc (crosstool-NG esp-2019r2) 8.2.0
- Operating System:     Linux
- Using an IDE?: No
- Power Supply:         USB

## Problem Description

When FAT disk full, function `write` return 0.

### Expected Behavior

Function `write` should return -1 with `errno` variable set to `ENOSPC`.

## Other items if possible

I investigate this error. Function `vfs_fat_write` should be fixed. 
Now `f_write` return 0 with `written` equal to 0 when disk full.
`vfs_fat_write` should be considered that.

```
    // Orig code.
    res = f_write(file, data, size, &written);

    // My code to solve issue.
    if (res == 0 && written == 0 && size != 0)
    {
        errno = ENOSPC;
        return -1;
    }
```

**Comment by Alvin1Zhang** [comment]
@mikhail-khalizev Thanks for reporting, we will look into.
