### ISSUE TITLE
http_client: No warning if TX buffer is too small to contain headers  (IDFGH-2996)

### ISSUE THREAD

**Issue by DiegoActionItem** [espressif/esp-idf#5028]
(Tested under IDF4, should be relevant to IDF3 as well)

If you add too much headers to a TCP client, the headers will be silently drop from the connection.

It seems this is a fix for https://github.com/espressif/esp-idf/issues/4617 (see https://github.com/espressif/esp-idf/commit/b7a9f5e115ca8d58186baad061251365c9dededd#diff-c7c711c57aa3482655dd39165cf29087), but IMHO a `LOGW` or `LOGE` should be in place (wasted about 10 hours finding that this was the problem in my code).

**Comment by Alvin1Zhang** [comment]
@DiegoActionItem Thanks for reporting, we have a fix which is now under internal reviewing, will update once it is available on GitHub. Thanks
