### ISSUE TITLE
exceed the default bootloader size esp32 flash encryption  (IDFGH-3014)

### ISSUE THREAD

**Issue by SERIDJ** [espressif/esp-idf#5043]
hi,

i have problem,  when i enabled flah encryption development mode, the size of  bootloader (0x7000 = 28672 BYTE) increase , so to solve that  i increase  the partition table offset from 0x8000 to 0x10000, that work in the first boot, but when i reset esp32 i have this error in  TERMINAL : 

![image](https://user-images.githubusercontent.com/46067255/78076240-54a3ae80-73a6-11ea-97b6-850b69d3282f.png)

i cant comme back bcs the development mode is enabled ...

https://docs.espressif.com/projects/esp-idf/en/latest/esp32/security/secure-boot-v1.html

**Comment by projectgus** [comment]
Hi @SERIDJ,

I need some more information in order to help you debug this:

* What ESP-IDF version do you have?

> that work in the first boot,

* Can you explain exactly what this means, please? What steps did you follow to flash the board, and what output did you see after you did that?

* Can you please run `espefuse.py -p PORT summary` to dump the efuse status for the board you have.

> i cant comme back bcs the development mode is enabled ...
> https://docs.espressif.com/projects/esp-idf/en/latest/esp32/security/secure-boot-v1.html

[Development mode](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/security/flash-encryption.html#flash-enc-development-mode) is a flash encryption mode that is designed to let you reflash (with `make encrypted-flash` or `idf.py encrypted-flash`). Do you mean to say that Secure Boot is also enabled, so you can't reflash the bootloader?

**Comment by SERIDJ** [comment]
hi @projectgus  thanks,

so i use ESP IDF V4.0.

to flash esp32 i use ECLIPSE IDE after instaling Espressif IDF Tools Manager (Git Executable Location + ESP IDF Directory ) 

i  can run espefuse.py -p PORT summary in cmd windows 10 command 

i want to use Development mode  (flash encryption ) so i folow those steps :
 
![image](https://user-images.githubusercontent.com/46067255/78221611-f79e1a80-74c3-11ea-9b9f-5fb1c07ed79e.png)

i cant enable this mode until i change in menuconfig the offset of partition table to 0x10000 and i have in TERMINAL eclipse somthing lik : 
![image](https://user-images.githubusercontent.com/46067255/78221880-801cbb00-74c4-11ea-9f3e-8439daaf787c.png)

that mean Development  mode  is enabled 

so when i reset my esp32 i have this error each 1s 

rst:0x10 (RTCWDT_RTC_RESET),boot:0x1b (SPI_FAST_FLASH_BOOT)
flash read err, 1000
ets_main.c 371 
ets Jun  8 2016 00:22:57

**Comment by SERIDJ** [comment]
for more  information about my menuconfig ; 

![image](https://user-images.githubusercontent.com/46067255/78279725-44abdc00-7518-11ea-920f-278228e7e5d0.png)

![image](https://user-images.githubusercontent.com/46067255/78279783-568d7f00-7518-11ea-93f9-6670cbceb5ac.png)

![image](https://user-images.githubusercontent.com/46067255/78279799-5ee5ba00-7518-11ea-8ff5-81d0f6817a4f.png)

![image](https://user-images.githubusercontent.com/46067255/78279824-6907b880-7518-11ea-8829-291724ad612d.png)

![image](https://user-images.githubusercontent.com/46067255/78279852-72912080-7518-11ea-8adf-3c5be117ffb9.png)

**Comment by igrr** [comment]
I think the trick is that after the first flash, once flash encryption is enabled, you need to use `idf.py encrypted-flash` command instead of `idf.py flash`. You can edit or create a new launch configuration, changing the flash command. Please see https://github.com/espressif/idf-eclipse-plugin#customizeLaunchConfig for details.

**Comment by SERIDJ** [comment]
hi @igrr 
thanks for ur replay, yes thats true i tried  with cmd command using idf.py enccrypted-flash (windows 10) ,  i had  continuously printing the following message 

![image](https://user-images.githubusercontent.com/46067255/78282038-f00a6000-751b-11ea-8f36-2266375b075a.png)

**Comment by igrr** [comment]
It looks like the partition table has not been loaded or generated correctly.
Could you please add the full logs of: `idf.py encrypted-flash` command, and `idf.py partition_table`?

Also, kind request to paste logs as text, rather than screenshots. The text in screenshots is hard to read and impossible to search.

**Comment by SERIDJ** [comment]
yes yes, i know when i change the offset  maybe i need to leave all partition offsets blank in the CSV file but i dont know how i can do that ...

for **idf.py encrypted-flash** work fine : 
![image](https://user-images.githubusercontent.com/46067255/78292899-10401c00-7528-11ea-830a-acab0c591c86.png)

and  **idf.py partition_table**  : 

 C:\Users\mohammed.seridj\Desktop\idfeclipse\flash_encryption>idf.py partition_table
Checking Python dependencies...
Python requirements from C:\Users\mohammed.seridj\esp\esp-idf\requirements.txt are satisfied.
Executing action: partition_table
Running ninja in directory c:\users\mohammed.seridj\desktop\idfeclipse\flash_encryption\build
Executing "ninja partition_table"...
ninja: no work to do.

Partition Table build complete. To flash, run this command:
C:\Users\mohammed.seridj\.espressif\python_env\idf4.0_py3.8_env\Scripts\python.exe ..\..\..\esp\esp-idf\components\esptool_py\esptool\esptool.py -p (PORT) -b 460800 --before default_reset --after no_reset write_flash 0x10000 build\partition_table\partition-table.bin
or run 'idf.py -p (PORT) partition_table-flash'

**Comment by SERIDJ** [comment]
yes i donk know and what i change in this table 

![image](https://user-images.githubusercontent.com/46067255/78295470-7d55b080-752c-11ea-9402-dc1d7b6e9068.png)

![image](https://user-images.githubusercontent.com/46067255/78295735-e2a9a180-752c-11ea-8053-e70a2e8cef71.png)

![image](https://user-images.githubusercontent.com/46067255/78295815-01a83380-752d-11ea-9548-2543ae6985f5.png)

**Comment by SERIDJ** [comment]
i try with blink and hello_world work fine 

![image](https://user-images.githubusercontent.com/46067255/78351438-10cbc780-75a7-11ea-91c7-c49d3b98dad2.png)

![image](https://user-images.githubusercontent.com/46067255/78351454-175a3f00-75a7-11ea-8b4b-066f9b4ce3f4.png)

so i have problem with flash_encryption code roboot automatically ...

**Comment by projectgus** [comment]
Hi @SERIDJ ,

Here is a modified copy of the `partitions_example.csv` file from the `examples/security/flash_encryption` example of IDF:

[partitions_example.csv.txt](https://github.com/espressif/esp-idf/files/4426651/partitions_example.csv.txt)

You should be able to use this with a partition table that has moved to a different offset, such as what you have.

You will need to rename the file as it has the `.txt` extension appended, to be accepted for upload to GitHub.

Remember to use encrypted-flash target if the flash encryption feature has already been enabled in Development mode.

We'll fix this CSV file properly in the example supplied with IDF, and update this issue once that fix has merged.

**Comment by SERIDJ** [comment]
@projectgus  ah ok i understand well thanks, 

so i dont know why i cant run :  espefuse  and esptool : command" is not recognized as an internal or external command, operable program or batch file

i do all that (flash encryption and secure boot ) to hide MQTT keys so waht is the best thing, encrypte all flash esp32 or i can hide only keys (client.crt and client.key)  ? 

and what is the best method to crypte flash memory : 
1-     Using ESP32 Generated Flash Encryption Key (interne) 
2-	Using Host Generated Flash Encryption Key (externe) 



  
![image](https://user-images.githubusercontent.com/46067255/78353717-d49a6600-75aa-11ea-881e-c3ea26feb3cf.png)

**Comment by SERIDJ** [comment]
@igrr hi sir, 
i want to use eclipse but i cant run idf.py encrypted-flash command instead idf.py flash ? 

![image](https://user-images.githubusercontent.com/46067255/78662467-c01edc00-78d0-11ea-8903-9a18af5d53a4.png)

**Comment by igrr** [comment]
There seem to be two issues:

* idf.py is duplicated in the command (`idf.py idf.py`)
* the error reported: `IDF_PATH environment variable is set to c:\users\mohammed.seridj\esp but C:\Users\mohammed.seridj\esp\esp-idf\tools\idf.py path indicates IDF directory c:\users\mohammed.seridj\esp\esp-idf` — make sure IDF_PATH is set correctly in Eclipse, it should point to `c:\users\mohammed.seridj\esp\esp-idf` instead of `c:\users\mohammed.seridj\esp`.

**Comment by SERIDJ** [comment]
@igrr yes thanks, 

I fixed the second issues ( change  IDF_PATH).

The first one ( idf.py is duplicated in the command) , i dont know where i can change or delete this duplicate ?

**Comment by SERIDJ** [comment]
@igrr  yes yes that work fine afther fixe that, thanks

i have another question about eclipse  (windows 10 ) : 
i  can debug ESP32 using JTAG  of  **ESP32-Ethernet-Kit_A_V1.1**  ? 


![image](https://user-images.githubusercontent.com/46067255/78705738-3857c280-790e-11ea-859a-0f0add332a0e.png)

**Comment by Alvin1Zhang** [comment]
@SERIDJ Thanks for reporting and follow up. For **Eclipse** specific issues, you could help raise an issue in our Eclipse repo. at https://github.com/espressif/idf-eclipse-plugin/issues, and for "how" questions or third party issues, you could raise a post on our forum at https://esp32.com. If you have a new issue, suggest you could file a new ticket. Thanks.

**Comment by projectgus** [comment]
Closing as the original issue seems to be resolved. For follow-up questions, please make use of the resources linked by my colleague in the above comment .
