### ISSUE TITLE
[Doc] Duplicated commands in uart_echo document (IDFGH-3022)

### ISSUE THREAD

**Issue by keelung-yang** [espressif/esp-idf#5049]
https://github.com/espressif/esp-idf/tree/master/examples/peripherals/uart/uart_echo

![image](https://user-images.githubusercontent.com/20385450/78225497-e8878e80-74fc-11ea-8b3a-da8911e2521e.png)

**Comment by Alvin1Zhang** [comment]
@keelung-yang Thanks for reporting, we will look into.

**Comment by Alvin1Zhang** [comment]
@keelung-yang Thanks for reporting, we have a fix internally under reviewing. The issue will be closed automatically when the fix is on Github. Thanks.
