### ISSUE TITLE
[BLE_MESH] How to create sensor network using external MCU as the sensor input? (IDFGH-3029)

### ISSUE THREAD

**Issue by dhorninger** [espressif/esp-idf#5055]
**Environment**

- 4 x ESP32-WROVER-B 
- 4 x STM32F051R8T6

**Issue**
I am unsure how to send data to the ESP32-WROVER-B using SPI so that it can be transmitted through a BLE Mesh Network. I am specifically looking for how to modify the input of each node to receive SPI data and communicate that data through the network.

**Desired Solution**

I would like to set up a BLE Mesh network using the ESP32-WROVER-B as an SPI slave. I am using an STM32F051R8T6 to receive sensor data and send it to the ESP32 using SPI. From there, the ESP32 must send the data to an end node to display the sensor data.

**Comment by sheldon123z** [comment]
Hi @dhorninger ,

Have you built a sensor network already? I am basically doing exactly things as you do, but I am stuck at creating sensor models using ESP32. Could you please share how to create sensor models?

Best Regards

**Comment by Campou** [comment]
Hi @sheldon123z ,

I have submitted a MR for sensor server/setup server model examples internally, waiting to be merged. When the MR is merged, it will be synchronized to Github soon.

Thanks for your patience

**Comment by dhorninger** [comment]
Hi @Campou 
When do you expect the update to Github will appear?

**Comment by Campou** [comment]
Hi @sheldon123z @dhorninger 

Please have a try with the latest idf, I have added sensor server related examples.

Thanks.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close now, feel free to reopen with more updates. Thanks.
