### ISSUE TITLE
Unable to get data through NOTIFY_EVT in "gatt_client" example (IDFGH-3031)

### ISSUE THREAD

**Issue by ROYMURLI** [espressif/esp-idf#5057]
ESP_IDF = v3.1.5
OS- Ubuntu

I am using "gatt_client" example to connect to a device(server) and then receive data through it. 
(Server operation is to send data cotinuosly after the BLE connection)

I changed service and notify UUID according to the server and also name. The ESP32 and device is successfully connected but ESP is unable to recieve data.

Through logs, I can figure it out that the example not able to call esp_ble_gattc_register_for_notify_event() function because of "get_server" variable. "get_server = true" condition is in SEARCH_CMPL_EVT which is not called after connection. May be I am giving wrong UUID. Kindly check the UUID part because I used REMOTE_SERVICE_UUID as ESP_UUID_LED_16 and REMOTE_NOTIFY_CHAR_UUID as  ESP_UUID_LED_128.

I am attaching my code, ble scanner screenchot (nrF) and debug logs here.

[gattc_issue_code.zip](https://github.com/espressif/esp-idf/files/4428634/gattc_issue_code.zip)

**Comment by Alvin1Zhang** [comment]
@ROYMURLI Thanks for reporting, we will look into.

**Comment by younglee123** [comment]
You have entered the wrong service UUID and characteristic UUID,so you can't find the CUSTOM SERVICE on your phone.Here is my code,you can refer to it.
ps:Note that the CPU data is stored in little-endian storage mode.[https://blog.csdn.net/favory/article/details/4441361](url)
[gattc_demo.zip](https://github.com/espressif/esp-idf/files/4784224/gattc_demo.zip)
