### ISSUE TITLE
Serial Flasher (IDFGH-3038)

### ISSUE THREAD

**Issue by cococococococo** [espressif/esp-idf#5063]
In ADC examples README you mention : "Set serial port under Serial Flasher Options." in menuconfig
Where is it in the menuconfig I don't see it ?

**Comment by bitmakk** [comment]
If you use idf.py and not make, it is not neccessary

**Comment by Alvin1Zhang** [comment]
@holubcsongor Thanks for the notes. @cococococococo Thanks for reporting, feel free to reopen if you still have the issue. Thanks.
