### ISSUE TITLE
I2S Driver error (IDFGH-3040)

### ISSUE THREAD

**Issue by mucar89** [espressif/esp-idf#5065]
A2DP Sink example is not working because of "I2S communication format invalid." error. I think "!" is missing on "components/driver/i2s.c" file, on line 383.

Example is working if I change that line to this:
`I2S_CHECK(**!**((i2s_config->communication_format & I2S_COMM_FORMAT_I2S) || (i2s_config->communication_format & I2S_COMM_FORMAT_PCM)), "I2S communication format invalid.", ESP_ERR_INVALID_ARG);`

(Reporing an error is not something I am familiar with, sorry for any inconvenience)

**Comment by Alvin1Zhang** [comment]
@mucar89 Thanks for reporting, we have a fix which is now under internal reviewing, will update once it is available on GitHub. Thanks.
