### ISSUE TITLE
examples/protocols/http_server/restful_server doesn't flash correctly when following the instructions (IDFGH-3041)

### ISSUE THREAD

**Issue by NANASHI0X74** [espressif/esp-idf#5066]
## Environment

- Development Kit:     ESP32-DevKitC (v4)
- Module or chip used:  ESP32-WROOM-32D|
- IDF version v4.2-dev-1035-g9f0ef7f88
- Build System:      idf.py
- Compiler version:  8.2.0
- Operating System:     Linux (ubuntu)
- Using an IDE?: No
- Power Supply:         USB

## Problem Description

when I follow the instructions exactly (exec npm run build in frontend dir, run idf.py flash monitor), flash errors because: `no such file or directory: www.bin`. **Running idf.py build fixes this.**

**Comment by suda-morris** [comment]
Sorry I didn't reproduce the issue you met. 
running `idf.py build flash monitor` and `npm run build` should from different dirs.

**Comment by NANASHI0X74** [comment]
if you take a look at https://github.com/espressif/esp-idf/blob/master/examples/protocols/http_server/restful_server/README.md
it says to run idf.py flash monitor, omitting the build step. That's the problem and it tripped me up for a while. I assumed that idf.py flash actually does the build too. And it does seem to do that actually which in most cases works. just in this case the flash step aparently doesn't produce www.bin, which I'm assuming is the bundled web application

**Comment by suda-morris** [comment]
Ah I see now, thanks for reporting @NANASHI0X74 it seems like a regression, we will look into it.

**Comment by renzbagaporo** [comment]
Hi @NANASHI0X74, this was a regression in our build system. A fix has been submitted internally. In the meantime, suggest using the executing `build`.
