### ISSUE TITLE
undefined reference | cmake | eclipse (IDFGH-3048)

### ISSUE THREAD

**Issue by su-Koch** [espressif/esp-idf#5073]
Hei Guys,
I was forced to open this issue because in the forum nobody replies to my question.

I'm a beginner in cmake as I'm working with Visual Studio normally. Now working with esp-idf eclipse plugin.
I'm trying to set up a project with two components, one inherits from the other.

The Structure of the Tree is attached.
The issue is that I get an error "undefined reference" for the Component I want to inherit from.

CMakeLists.txt are:
![Tree](https://user-images.githubusercontent.com/59842051/78601945-e489a280-7855-11ea-96f1-8ac3f5d08ea0.png)
![issue](https://user-images.githubusercontent.com/59842051/78601962-eb181a00-7855-11ea-8166-91a9da1625f1.png)

I2CKeypad:
idf_component_register(SRCS "I2CKeypad.cpp" INCLUDE_DIRS "." "../I2CPeripheral")

I2CPeripheral:
idf_component_register(SRCS "I2CPeripheral.cpp" INCLUDE_DIRS ".")

main:
idf_component_register(SRCS "main.cpp" INCLUDE_DIRS ".")

project:
cmake_minimum_required(VERSION 3.5)
include($ENV{IDF_PATH}/tools/cmake/project.cmake)
project(i2cKeypad)

I2CPeripheral.h is includes in I2CKeypad.h

Hopefully there is a person out there that knows how to solve this.
Please let me know if you need more information.
Thanks.

Edit: 

What I did now:

Changed
CMakeLists.txt of I2CKeypad:
idf_component_register(SRCS "I2CKeypad.cpp" INCLUDE_DIRS "." "../I2CPeripheral")

to
idf_component_register(SRCS "I2CKeypad.cpp" INCLUDE_DIRS "." REQUIRES I2CPeripheral)

but the error is still there.

Thanks Guys. Hope you understand why i did open this issue.
Manuel

**Comment by Alvin1Zhang** [comment]
@su-Koch Thanks for reporting, we will look into.

**Comment by renzbagaporo** [comment]
Hi @su-Koch, when you first asked the question, I thought you were having a linker error. However, with the correction I mentioned, have you tried building the project?

**Comment by su-Koch** [comment]
of Course i tryed Building the Project. With no Success.

**Comment by noweare1** [comment]
Try building the project outside of Eclipse using the directions shown in "getting started" from espressif.   I set up the idf toolchain and installed the latest eclipse and eclipse could not find the include files. It was also telliing me it could not find some of the python tools. Once I just used the command line tools from espressif I could build / down load with no problems. I hate getting bogged down trying to figure out why Eclipse didn't work so maybe I will try something else or try an earlier version of eclipse or VSC or Arduino. What ever works.

**Comment by kolipakakondal** [comment]
> Try building the project outside of Eclipse using the directions shown in "getting started" from espressif. I set up the idf toolchain and installed the latest eclipse and eclipse could not find the include files. It was also telliing me it could not find some of the python tools. Once I just used the command line tools from espressif I could build / down load with no problems. I hate getting bogged down trying to figure out why Eclipse didn't work so maybe I will try something else or try an earlier version of eclipse or VSC or Arduino. What ever works.

As mentioned here https://github.com/espressif/idf-eclipse-plugin/issues/72, your problem could be with a launch target. As suggested, please create an ESP launch target to fix the unresolved issues.

**Comment by kolipakakondal** [comment]
@renzbagaporo Could you help me to get a sample project similar to this. I would like to import into eclipse and see

**Comment by kolipakakondal** [comment]
@su-Koch Does the same project working from the command-line? Could you please run from the terminal first and see what happens - if it's working fine, can you share the sample project with us.

**Comment by su-Koch** [comment]
ok, tell me what i've to run exactly on command line please.

**Comment by noweare1** [comment]
Go to https://docs.espressif.com/projects/esp-idf/en/latest/esp32/ and follow the "getting started" 
which is located at the top. It walks you through installing the tools and at the end builds and flashes a project using the command line instead of using an IDE.

**Comment by noweare1** [comment]
Also I would first try just building one of the example projects first before to confirm the tool chain is working properly this is also shown in the "getting started" documentation.

**Comment by renzbagaporo** [comment]
@su-Koch can you post the build logs here?

**Comment by kolipakakondal** [comment]
Another important thing here is - unresolved references will disappear only after the compilation. Not sure if you're able to compile a project?

**Comment by renzbagaporo** [comment]
Hi @su-Koch, any updates on this issue?

**Comment by su-Koch** [comment]
Hei Renz, I had no time to investigate that. But now I will get deeper into it once more. Coming back to you if I got new experiences. Thanks for your great support.
Manuel

**Comment by Alvin1Zhang** [comment]
@su-Koch Thanks for reporting, would you please help share if any updates? Thanks.
