### ISSUE TITLE
Is there an option that will not display the wifi info message?

### ISSUE THREAD

**Issue by kimdowan84** [espressif/esp-idf#508]
Hello!

I am currently building the iot system with esp32.
The wifi has been completed to some extent, and now we are doing another task.
However, sometimes I do not want to see the wifi info message. Is there an option not to display the wifi info message?

**Comment by igrr** [comment]
You can use [esp_log_level_set](http://esp-idf.readthedocs.io/en/latest/api/system/log.html#_CPPv217esp_log_level_setPKc15esp_log_level_t) function to control logging for different modules. For example, you may set log level for `"wifi"` to `ESP_LOG_NONE`.

**Comment by kimdowan84** [comment]
Thank you very much.

 

Dowan Kim
