### ISSUE TITLE
lan8720 LAN port orange LED blinks rapidly problem while init Ethernet first following init UART (IDFGH-3071)

### ISSUE THREAD

**Issue by andrewcch1226** [espressif/esp-idf#5093]
## Environment

- Module or chip used: ESP32-WROVER and ESP32-WROVER-B
- IDF version (run ``git describe --tags`` to find it):
    v4.1-beta1 and v3.3.1
- Build System:         idf.py and make
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it):
    xtensa-esp32-elf-gcc (crosstool-NG esp-2019r2) 8.2.0 and xtensa-esp32-elf-gcc.exe (crosstool-NG crosstool-ng-1.22.0-80-g6c4433a5) 5.2.0
- Operating System:     Windows
- (Windows only) environment type: ESP Command Prompt and MSYS2 mingw32
- Using an IDE?: No
- Power Supply:  External 5V

## Problem Description

When ESP32 boot up sometime lan8720 LAN port orange LED blinks rapidly and can't ping. and it problem require to restart several times to get rid of it, After find out, this problem can be solved by init UART first only init the ethernet.

//Detailed problem description goes here.

### Steps to reproduce
Init Ethernet first and following init UART will cause this error.

// If possible, attach a picture of your setup/wiring here.

### Code to reproduce this issue

```cpp
// the code should be wrapped in the ```cpp tag so that it will be displayed better.
#include "esp_log.h"

void app_main()
{

}

```
// If your code is longer than 30 lines, [GIST](https://gist.github.com) is preferred.

## Debug Logs

```
Debug log goes here, should contain the backtrace, as well as the reset source if it is a crash.
Please copy the plain text here for us to search the error log. Or attach the complete logs but leave the main part here if the log is *too* long.
```

## Other items if possible

- [ ] sdkconfig file (attach the sdkconfig file from your project folder)
- [ ] elf file in the ``build`` folder (**note this may contain all the code details and symbols of your project.**)
- [ ] coredump (This provides stacks of tasks.)

**Comment by suda-morris** [comment]
Hi @andrewcch1226 Interesting! Can you tell how esp32 and lan8720 is connected (Who generates the RMII clock, which GPIO is used for RMII clock? Did you use PHY reset IO?) And your ethernet initialization step?

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to short of feedback, feel free to reopen.
