### ISSUE TITLE
华为荣耀20 Android 10.0版本配不了网，必现 (IDFGH-3097)

### ISSUE THREAD

**Issue by linux-liu** [espressif/esp-idf#5118]
手机一直发送udp包，但设备端一直收不到数据，设备端联网一直不成功。手机端超时配网失败

**Comment by Alvin1Zhang** [comment]
@linux-liu Thanks for reporting. Would you please help provide more details as suggested in the [issue template](https://github.com/espressif/esp-idf/issues/new?assignees=&labels=&template=bug_report.md&title=)? Information like elf, sdk configuration, backtrace, log outputs, commit ID, hardware and etc. would help us debug further.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting @linux-liu . Would you please help provide more details as suggested in the [issue template](https://github.com/espressif/esp-idf/issues/new?assignees=&labels=&template=bug_report.md&title=)? Information like elf, sdk configuration, backtrace, log outputs, commit ID, hardware and etc. would help us debug further.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to short of feedback, feel free to reopen with more details, thanks.
