### ISSUE TITLE
Compilation fails if `CONFIG_FREERTOS_SUPPORT_STATIC_ALLOCATION=n` (IDFGH-3102)

### ISSUE THREAD

**Issue by BrianPugh** [espressif/esp-idf#5123]
## Problem Description

esp-idf compilation fails if `CONFIG_FREERTOS_SUPPORT_STATIC_ALLOCATION=n`

```
esp-idf/components/driver/spi_bus_lock.c:822:41: error: implicit declaration of function 'xSemaphoreCreateBinaryStatic'
```

There might be other instances of this, but i haven't investigated further.

**Comment by AxelLin** [comment]
This was reported 2 weeks ago: https://github.com/espressif/esp-idf/issues/5046

**Comment by BrianPugh** [comment]
right you are, closing this issue to continue discussion there. Sorry!
