### ISSUE TITLE
I2S driver issues (IDFGH-3106)

### ISSUE THREAD

**Issue by fpgamaster** [espressif/esp-idf#5127]
## Environment
- Kit version ESP32-WROOM-32D (Chip is ESP32D0WDQ5 (revision 1))
- IDF version: v4.2-dev-1097-g2e14149bf
- Build System: Make
- Compiler version: xtensa-esp32-elf-gcc (crosstool-NG esp-2020r1) 8.2.0
- Operating System: Linux
- Power Supply:         USB

## Problem Description
Trying to get a MEMS microphone to work, I2S is configured as follow:

i2s_config.mode = (i2s_mode_t)(I2S_MODE_MASTER | I2S_MODE_RX | I2S_MODE_PDM);
i2s_config.sample_rate = 16000;
i2s_config.bits_per_sample = 16;
i2s_config.channel_format = I2S_CHANNEL_FMT_ONLY_RIGHT;
i2s_config.communication_format = I2S_COMM_FORMAT_PCM;
i2s_config.intr_alloc_flags = ESP_INTR_FLAG_LEVEL1;
i2s_config.use_apll = true;
i2s_config.dma_buf_count = 2;
i2s_config.dma_buf_len = 128;

pin_config.bck_io_num = I2S_PIN_NO_CHANGE;
pin_config.ws_io_num = MIC_CLK_PIN;
pin_config.data_in_num = MIC_DATA_PIN;
pin_config.data_out_num = I2S_PIN_NO_CHANGE;

//Detailed problem description goes here.
From console logs:
I (1501) I2S: PLL_D2: Req RATE: 16000, real rate: 32258.000, BITS: 16, CLKM: 31, BCK: 5, MCLK: 31.250, SCLK: 1032256.000000, diva: 64, divb: 16

APLL is not enabled!? Real rate is strange!? Data received is completely wrong.

Changing sample_rate = 48000 gives:
I (1503) I2S: PLL_D2: Req RATE: 48000, real rate: 100000.000, BITS: 16, CLKM: 10, BCK: 5, MCLK: 10.417, SCLK: 3200000.000000, diva: 64, divb: 26

Also APLL is not enabled!? Real rate is weird but the data comes from mic looks good.

In both cases there is no difference whether I2S_CHANNEL_FMT_ONLY_RIGHT or I2S_CHANNEL_FMT_ONLY_LEFT is used which is weird too since the data coming should be sampled on different clock edges and there is only one mic configured as left by hardware.

So, do I miss something or I2S driver is currently broken?

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, and sorry for slow turnaround. We have a fix internally now under review, will share updates if the fix is available on GitHub.
