### ISSUE TITLE
[TW#12113] RMT support does not provide a way to test if transmist is done

### ISSUE THREAD

**Issue by Makuna** [espressif/esp-idf#514]
rmt_wait_tx_done() will wait for ever.

I suggest exposing a function like...
bool rmt_is_tx_done() 

less interesting but a viable alternative is to modify rmt_wait_tx_done() to take an optional param for the timeout with a default value of portMAX_DELAY.  Further modify it to return the value from the xSemaphoreTake if it fails.

**Comment by jeremyherbert** [comment]
Just tripped on this problem today. Any timeframe on a fix?

**Comment by Makuna** [comment]
Any updates on this?

**Comment by igrr** [comment]
We have a PR which adds the timeout value to `rmt_wait_tx_done` and fixes #274. Will give it a nudge, thanks for the reminder.

**Comment by EBZ-Krisemendt** [comment]
@iggr does closing https://github.com/espressif/esp-idf/issues/274 mean, that this one can be closed, too?

**Comment by igrr** [comment]
Yes, thanks for reminder.
