### ISSUE TITLE
Can't find configuration option in sdkconfig.h (IDFGH-3122)

### ISSUE THREAD

**Issue by romocitto88** [espressif/esp-idf#5141]
## Environment

- Development Kit:      ESP32-DevKitC
- Module or chip used:  ESP32-WROOM-32D
- Operating System:     Windows
- Using an IDE?: PlatformIO

## Problem Description

I'm tring to use the ble usart example, and I want to save power consumption. 
From Espressif API is possible to set CONFIG_BTDM_CONTROLLER_MODEM_SLEEP but I can't found any define in the file sdkconfig.h. Someone can explaine me how to do?

Thank you.

**Comment by dobairoland** [comment]
The configuration value was recently renamed to CONFIG_BTDM_MODEM_SLEEP.

**Comment by Alvin1Zhang** [comment]
@dobairoland Thanks for the notes. @romocitto88 Thanks for reporting, would you please help share if your issue has been resolved? Thanks.

**Comment by Alvin1Zhang** [comment]
@romocitto88 Thanks for reporting, would you please help share if your issue has been resolved? Thanks.

**Comment by romocitto88** [comment]
Thanks @dobairoland 
At the end I use directly CONFIG_BTDM_MODEM_SLEEP_MODE_ORIG or CONFIG_BTDM_MODEM_SLEEP_MODE_EVED to do my test.

**Comment by Alvin1Zhang** [comment]
@romocitto88 Glad that you found the solution, will close the ticket. Thanks.
