### ISSUE TITLE
Ble mesh  (IDFGH-3140)

### ISSUE THREAD

**Issue by gbortnikov** [espressif/esp-idf#5157]
HELLO! I'm trying to use Ble mesh but I can't figure out how to send plain text . In my project, esp 32 will accept text via mqtt and then transmit it over the grid. But now I'm using a phone with the "nrf mesh" app and I want to send a message to esp 32 via it. I don't understand how "vendor model" works. do I need to use it to send text?

**Comment by Campou** [comment]
Hi @gbortnikov 

Sorry for the late reply.

For how vendor models work on esp32, please refer to [the vendor model examples](https://github.com/espressif/esp-idf/tree/master/examples/bluetooth/esp_ble_mesh/ble_mesh_vendor_model).

For nRF Mesh App, I think after it provisioned a device, it can sends a vendor message with the defined vendor opcode.

Thanks.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, feel free to reopen.
