### ISSUE TITLE
esp_spp_write() too slow, any faster alternative? (IDFGH-3141)

### ISSUE THREAD

**Issue by francis2tm** [espressif/esp-idf#5158]
**Is your feature request related to a problem? Please describe.**

I'm using esp_spp_write() to transmit data over classic bluetooth. My specifications require to send 8bytes every 1ms, but the esp_spp_write() takes about 2.5ms to send 8bytes. I noticed that even if I send 100bytes instead of 8 bytes at once, esp_spp_write() also takes about 2.5ms, which made me surprised becaused I thought the duration of transmisstion would be linear with the amount of bytes to be sent.

**Describe the solution you'd like**

I would like a lightweight bt_spp_write function to send data rapidly.

**Describe alternatives you've considered**
Is there any solution to my problem right now?
It looks like the esp_spp_write() waits for something before sending the data
**Additional context**

**Comment by Alvin1Zhang** [comment]
@francis2tm Thanks for reporting, we will evaluate.

**Comment by Wth-Esp** [comment]
Hi @francis2tm 

Could you please describe how the 2.5ms is measured?

Thanks
Weitianhua

**Comment by Alvin1Zhang** [comment]
@francis2tm Thanks for reporting, would you please help share if any updates? Thanks.

**Comment by Wth-Esp** [comment]
Hi @francis2tm 

Please update your IDF and have a try. We have pushed a related commit to improve this delay.

Thanks

**Comment by francis2tm** [comment]
> Hi @francis2tm
> 
> Please update your IDF and have a try. We have pushed a related commit to improve this delay.
> 
> Thanks

Thanks, I will
