### ISSUE TITLE
Example of both Transmitting and Receiving  (IDFGH-3149)

### ISSUE THREAD

**Issue by michaelleuer** [espressif/esp-idf#5166]
**Describe the solution you'd like**

I would like the esp to do both Transmitting and Receiving of Bluetooth at regular intervals, to see if a device is in the area preferred using Bluetooth LE.  The end result would be to detect if another device is around. 

https://github.com/espressif/esp-idf/blob/master/examples/bluetooth/bluedroid/ble/ble_ibeacon/main/ibeacon_demo.c

I have seen this question asked before, and do not know if it can do the transmitting and receiving can be done or looping in time to detect both the transmitter and receiver.

**Comment by Isl2017** [comment]
Hi, Michaelleuer

I don't quite get your requirement? Do you mean that you want to scan(receiver) and advertising(transmitter) simultaneously?

You can start scan with the duration parameter set to 0 (means scan permanently). You don't need to stop scan if you want to do advertising then. The controller will allocate RF resource for both activities automatically.

**Comment by Isl2017** [comment]
So for the iBeacon example you showed, normally you can run the both IBEACON_SENDER mode and IBEACON_RECEIVER mode together.

**Comment by michaelleuer** [comment]
Ok thank you I will try it out today enabling both today.

**Comment by Alvin1Zhang** [comment]
@michaelleuer Thanks for reporting, would you please help share if any updates? Thanks.

**Comment by michaelleuer** [comment]
Worked great.

**Comment by Alvin1Zhang** [comment]
Thanks for sharing the updates, feel free to reopen.
