### ISSUE TITLE
esp_http_client_config_t fields are ignored (.query and likely .path)  (IDFGH-3161)

### ISSUE THREAD

**Issue by maikeriva** [espressif/esp-idf#5174]
## Environment

- Development Kit: custom board
- Module or chip used:  ESP32-WROOM-32
- IDF version: v4.1-beta1-112-g4fe18a925
- Build System: CMake
- Compiler version: xtensa-esp32-elf-gcc (crosstool-NG esp-2019r2) 8.2.0
- Operating System: Linux
- Using an IDE?:  VSCode

## Problem Description
The query parameter in an esp_http_client_config_t is ignored when performing an http connection. This most likely applies to the path parameter (untested).

### Expected Behavior
The query and path parameters should be taken into account for new connections

### Steps to reproduce
Create a new esp_http_client_config_t and define its .query parameter. When performing the connection, such parameter will be ignored.

### Code
Here follows the portion of the code where I believe the problem lies. In esp_http_client.c the following code cleans up the query field (and likely resets the path one) if no corresponding values are parsed from the url field. I guess that should execute on connections reuse, yet it is executed also on new connections:
```cpp
    //Reset path and query if there are no information
    if (purl.field_data[UF_PATH].len) {
        http_utils_assign_string(&client->connection_info.path, url + purl.field_data[UF_PATH].off, purl.field_data[UF_PATH].len);
    } else {
        http_utils_assign_string(&client->connection_info.path, "/", 0);
    }
    HTTP_MEM_CHECK(TAG, client->connection_info.path, return ESP_ERR_NO_MEM);

    if (purl.field_data[UF_QUERY].len) {
        http_utils_assign_string(&client->connection_info.query, url + purl.field_data[UF_QUERY].off, purl.field_data[UF_QUERY].len);
        HTTP_MEM_CHECK(TAG, client->connection_info.query, return ESP_ERR_NO_MEM);
    } else if (client->connection_info.query) {
        free(client->connection_info.query);
        client->connection_info.query = NULL;
    }
```

**Comment by shubhamkulkarni97** [comment]
Hi @maikeriva,

You need to either set all the parameters as configuration or all the parameters in URL.

For instance, if you want to send a GET request to `http://httpbin.org` with a query parameter `test`,

There can be two approaches:

* First approach:
```
esp_http_client_config_t config = {
        .url = "http://httpbin.org/get?test",
    };
```

* Second Approach:
```
esp_http_client_config_t config = {
        .host = "httpbin.org",
        .path = "/get",
        .query = "test",
    };
```

**Comment by maikeriva** [comment]
I see, thanks for the explanation, I will try it out.
That seems pretty counter-intuitive to me though. Shouldn't the two mechanisms compatible?
Also, I can't find any mention of this in the documentation. I believe this should be explicitly stated (it made me lose a fair amount of time).
