### ISSUE TITLE
Error while building aws_iot (thing shadow) example in release/v4.2 SDK. (IDFGH-3181)

### ISSUE THREAD

**Issue by harshithakre38** [espressif/esp-idf#5190]
Hey everybody,
              In the release/v3.3 there exists an aws_iot example which does not exist in release/v4.2 of esp-idf.
              So I copied the aws_iot (thing shadow) example and made desired changes according to my requirement in the thing_shadow.c file and the aws_iot folder in components from v3.3 onto v4.2. But while building the example in the current SDK(v4.2) I am getting the following error. 

ERROR:

WARNING: Missing submodule components/aws_iot/aws-iot-device-sdk-embedded-C...
Attempting 'git submodule update --init components/aws_iot/aws-iot-device-sdk-embedded-C' in esp-idf root directory...
error: pathspec 'components/aws_iot/aws-iot-device-sdk-embedded-C' did not match any file(s) known to git.
/home/harshitha/esp32/esp-idf/make/project.mk:672: recipe for target '/home/harshitha/esp32/esp-idf/components/aws_iot/aws-iot-device-sdk-embedded-C/.git' failed
make: *** [/home/harshitha/esp32/esp-idf/components/aws_iot/aws-iot-device-sdk-embedded-C/.git] Error 1

How would I be able to solve this? Can someone please suggest the desired changes to be done in the current SDK version4.2  in order to solve this problem.

**Comment by mahavirj** [comment]
Please try examples from below repository pointer:

https://docs.espressif.com/projects/esp-idf/en/latest/esp32/libraries-and-frameworks/cloud-
frameworks.html

https://github.com/espressif/esp-aws-iot

**Comment by mahavirj** [comment]
@harshithakre38 I will mark this as resolved, please feel to re-open if you still find any issues with examples in above repository pointer.
