### ISSUE TITLE
OTA_Esp8266 using http (IDFGH-3198)

### ISSUE THREAD

**Issue by sowmimalu** [espressif/esp-idf#5200]
Hi,
 i am using esp8266 development board...i am try to download a file from local server by using http..
In my application i need to update ota  in esp8266 by using http.... I got one example in arduino(webupdater)when i tried with this example webpage has opend i am able to choose a bin file which i want form that i can able to update the bin file by OTA. Now i need  to download a file in my source code by using http ...i tried basic example in ardunio(httpupdate) but its not work ...i got connection refused error ....when I tried to download a bin  file from local server.

**Comment by chegewara** [comment]
Wrong address.

**Comment by sowmimalu** [comment]
can you please suggest me.. to how to download a file  by http from my local server..

http://ip/new/hello_world.bin
 *ip  i have given my system ip as in above command
what is the correct way to download a file and then to update 
Is there any example??

**Comment by sowmimalu** [comment]
sorry, posted in esp8266 github

**Comment by Alvin1Zhang** [comment]
@sowmimalu Tracking in https://github.com/espressif/ESP8266_RTOS_SDK/issues/884, will close this one, thanks.

**Comment by sowmimalu** [comment]
thank you..
