### ISSUE TITLE
multi client in esp32 (IDFGH-3204)

### ISSUE THREAD

**Issue by sowmimalu** [espressif/esp-idf#5203]
hai,
    In my application, esp32 as client (using multi client example) and nrf as server.
i am connecting esp32 with maximum 3- 4 server,which is always in connection mode.
and my question is ,
   in multi client example having 3 profile handler, each sever will connect to one profile like a,b,and c as given in the example.
is it possible to use only one profile to connect upto 3-4 server ???...and also it should always be in connected mode

**Comment by zhp0406** [comment]
@sowmimalu 
Have you resolved the issue?

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, sorry for slow turnaround, feel free to reopen with more updates.
