### ISSUE TITLE
Can't add second characteristic with esp_ble_gatts_add_char (IDFGH-3212)

### ISSUE THREAD

**Issue by saloid** [espressif/esp-idf#5211]
## Environment

- Development Kit:      ESP32-Wrover-Kit
- Kit version: v4.1
- Module or chip used:  ESP32-WROVER
- IDF version: framework-espidf 3.40000.200303 (4.0.0) (in Platformio)
- Build System:         idf.py (Platformio)
- Compiler version: xtensa-esp32-elf-gcc (crosstool-NG esp-2019r2) 8.2.0
- Operating System:     Windows 10
- (Windows only) environment type: Plain Command Prompt.
- Using an IDE: VScode, Platformio
- Power Supply:         USB

## Problem Description
I am trying to add second characteristic with `esp_ble_gatts_add_char` and this not works - I can see only first char. Is this function supposed to add more than single characteristic to every service?

And yes, I've have seen table method for multiple characteristic - I don't need default value for all them (as in example), so I am trying to avoid it now.

### Expected Behavior
Call `esp_ble_gatts_add_char` at second time should add second char

### Actual Behavior
In ble scanner I can see only first char

**Comment by saloid** [comment]
Looks like I should wait callback (ESP_GATTS_ADD_CHAR_EVT) after first char adding and then add second.

**Comment by GitOfLance** [comment]
Hi, @saloid 
At the beginning, I failed to create two Characteristic in `ESP_GATTS_CREATE_EVT` in succession, but the reason is different from yours. When calling `esp_ble_gatts_create_service` to create a service, you need to set the number of request handles. This value is 4 in the demo, because the `service` needs one and the `characteristic` needs three. If you want to add second Characteristic, then the value of `num_handle` needs to be changed to **7**.
The ESP-IDF I am using is v4.0 stable version.You can try this method.

**Comment by saloid** [comment]
Hi, @GitOfLance
Thank you for your reply. In my case it works as I described - just need to create second one in callback. But, in this case I am assuming that single `characteristic` consumes only 2 handles, not 3! In [this](https://github.com/espressif/esp-idf/blob/master/examples/bluetooth/bluedroid/ble/gatt_server/main/gatts_demo.c) example, 4 handlers used only because there also one handler for descriptor.
So single `service` definition looks like this: 1x`service` + 2x`characteristic` + 1x`descriptor`

**Comment by GitOfLance** [comment]
Hi, @saloid
In the subsequent use, it was found that if two Characteristic were created at the same time, the communication would be disordered. For example, the `Listen for notifications` function of `Characteristic_A` was enabled, but the data was received on `Characteristic_B`. Therefore, the correct way to create multiple characteristics should be to create one by one.
I am using this [demo](https://github.com/espressif/esp-idf/tree/master/examples/bluetooth/bluedroid/ble/gatt_server). In its [explanation document](https://github.com/espressif/esp-idf/blob/master/examples/bluetooth/bluedroid/ble/gatt_server/tutorial/Gatt_Server_Example_Walkthrough.md#creating-services), a complete characteristic needs three handles. Use this demo. Once the Characteristic uses less than three handles, an error will be reported. I think you should give up some features of Characteristic, so fewer handles can work.
