### ISSUE TITLE
HTTPS OTA (IDFGH-3220)

### ISSUE THREAD

**Issue by varunsavita** [espressif/esp-idf#5218]
(https://docs.espressif.com/projects/esp-idf/en/latest
IDF branch master

Development Kit: ESP32-DevKitC
Module or chip used: ESP32-WROOM-32
Build System: Make
Compiler version (run xtensa-esp32-elf-gcc --version to find it):
Operating System: Windows
(Windows only) environment type: MSYS2 mingw32
Power Supply: USB

![image](https://user-images.githubusercontent.com/42342764/80685553-038df400-8ae5-11ea-9e49-3db8a2a70f32.png)

![image](https://user-images.githubusercontent.com/42342764/80685731-4354db80-8ae5-11ea-8b85-f78eaf6c4a72.png)
![image](https://user-images.githubusercontent.com/42342764/80685827-63849a80-8ae5-11ea-943a-d6a68f4ac0c8.png)

![image](https://user-images.githubusercontent.com/42342764/80685912-857e1d00-8ae5-11ea-99ed-0d4be34555bf.png)

Error
 No rule to make target '/home/varun/esp32/esp-idf/examples/Varun/https_request/server_certs/certs.pem', needed by 'embed_txt/certs.pem'.  Stop.

I am able to read soon file but I want to download .bin file.

**Comment by mahavirj** [comment]
@varunsavita You are specifying file name in `CMakeLists.txt` as `ca_cert.pem` but actual file name seems to be `certs.pem`?

**Comment by mahavirj** [comment]
@varunsavita Did you happen to solve this? Can we close the issue?
