### ISSUE TITLE
Blank "Bluetooth" option in menuconfig in IDF v4.1-dev-1086-g93a8603c5 (IDFGH-3222)

### ISSUE THREAD

**Issue by ROYMURLI** [espressif/esp-idf#5220]
Hi,
IDF v4.1-dev-1086-g93a8603c5
OS- Windows (msys32)

I am getting black page to configure bluetooth option after "make menuconfig". Screenshots are attached below.

![first](https://user-images.githubusercontent.com/20817125/80711570-313b6300-8b0e-11ea-866d-f43efed569b7.jpg)

![second](https://user-images.githubusercontent.com/20817125/80711583-38627100-8b0e-11ea-9955-1835ea2021f2.jpg)

**Comment by dobairoland** [comment]
Hi @ROYMURLI. Yes, you are right that this is broken in the mentioned commit. I was able to reproduce. Can you please update to a newer version of v4.1? There were a couple of related fixes in v4.1 and I have checked that the latest version of v4.1 doesn't have this issue.

**Comment by ROYMURLI** [comment]
Ok, Thanks for the update. I will update and will check from my side.
