### ISSUE TITLE
HSM based mTLS Authentication (IDFGH-3243)

### ISSUE THREAD

**Issue by swanav** [espressif/esp-idf#5239]
**How to establish mTLS based Mqtt Session when Private Keys are stored in a HSM?** 

Currently the library expects a pointer to private key during init, but my usecase will use a HSM for storing the device keys? How can I use the library in this case?

[mqtt_client.h](https://github.com/espressif/esp-mqtt/blob/master/include/mqtt_client.h#L173)
```
/**
 * MQTT client configuration structure
 */
typedef struct {
...
const char *client_key_pem;             /*!< Pointer to private key data in PEM or DER format for SSL mutual authentication, default is NULL, not required if mutual authentication is not needed. If it is not NULL, also `client_cert_pem` has to be provided. PEM-format must have a terminating NULL-character. DER-format requires the length to be passed in client_key_len */
...
} esp_mqtt_client_config_t;
```

**Comment by Alvin1Zhang** [comment]
@swanav Thanks for reporting the feature request, we will evaluate. Thanks.
