### ISSUE TITLE
ULP Assembler failure (IDFGH-3259)

### ISSUE THREAD

**Issue by stevewms** [espressif/esp-idf#5253]
## Environment

- Development Kit:     Irrelevant - but DevKitC
- Kit version v2
- Module or chip used:  irrelevant, but[ESP32-WROOM-32
- IDF version v4.0-327-gfe67bedee
- Build System:        CMake|idf.py
- Compiler version  xtensa-esp32-elf-gcc (crosstool-NG esp-2019r2) 8.2.0
- Operating System:     Windows 10
- (Windows only) environment type:  ESP Command Promopt
- Using an IDE?:  No
- Power Supply:    irrelevant but USB 

## Problem Description

When I build a project with several components including a ULP component which I have assembled in an isolated unit test environment without error, I get the following error message when built in the environment above.  (This after reporting a bug in assembling ULP addembler code resolved with idf v4.0.1, downloaded as "release/v4.0" earlier today:

> ulp.dir/PartBinULP.S.obj -MF esp-idf\ulp\CMakeFiles\__idf_ulp.dir\PartBinULP.S.obj.d -o esp-idf/ulp/CMakeFiles/__idf_ulp.dir/PartBinULP.S.obj -c ../components/ulp/PartBinULP.S
> ../components/ulp/PartBinULP.S: Assembler messages:
> ../components/ulp/PartBinULP.S:55: Error: unknown pseudo-op: `.bss'
> ../components/ulp/PartBinULP.S:125: Error: unknown opcode or format name 'move'
> ../components/ulp/PartBinULP.S:126: Error: unknown opcode or format name 'ld'
> ../components/ulp/PartBinULP.S:127: Error: bad register name: r0
> ../components/ulp/PartBinULP.S:127: Error: junk at end of line, first unrecognized character is `r'
> ../components/ulp/PartBinULP.S:127: Internal error in ignore_rest_of_line at /builds/idf/crosstool-NG/.build/HOST-i686-w64-mingw32/xtensa-esp32-elf/src/binutils/gas/read.c:3762.
> Please report this bug.
> [4/15] Building C object esp-idf/uart/CMakeFiles/__idf_uart.dir/PartBinUart.c.obj

As instructed in the error message, I'm reporting this bug. 

### Code to reproduce this issue
Too much to include here.
I'm not sure what else to add here.  What do you need?

**Comment by igrr** [comment]
Hi @stevewms, it is a bit hard to understand from the truncated log, but it looks like the ULP assembly file is being passed to the Xtensa compiler. Could you please attach your component CMakeLists.txt file? At the same time, could you compare it to one of the ULP examples in IDF, and see if you are doing something different from the example?

**Comment by stevewms** [comment]
iggr,
Thanks for your reply.  I had tried to organize my app, with about 5 components plus the main program such that the ULP code was a component also.  Using your suggestion, I moved the ULP code under the main directory in a directory called "ulp", following the example in the idf, including the way the main program's CMakeLists.txt file was set up, and now everything works.  Thanks for the pointer to a solution.
But this does bring up the question, is it possible to organize a project such that the ULP code is treated as a component?  If so, how would that work?  Are there any examples anywhere to which you could point me?
I'm ready to close this as a bug.  It's not a bug. But I would like to see any response to the questions I asked about treating a file of ULP code as a component.

**Comment by igrr** [comment]
@stevewms Compared to the main application, the ULP application has a much simpler build process, where all the object files are linked directly into the ULP executable. I don't see a straightforward way to add "components" support to the current ULP build system. It is possible to build multiple ULP applications (i.e. one in each component), and choose which one to load at run time. But combining a ULP app from several components is not possible at the moment.

**Comment by stevewms** [comment]
iggr,
Thanks for your reply.  It makes sense and creating multiple ULP apps for various components is something I'd not even thought of, not that I have any great need for it at this time.
Again, thanks.
