### ISSUE TITLE
为毛搜索不到设备，android的却可以 代码是在哪设置？ (IDFGH-3277)

### ISSUE THREAD

**Issue by AdwardWong** [espressif/esp-idf#5269]
固件版本esp-idf-v3.3，试过各种手机与系统

**Comment by Alvin1Zhang** [comment]
@AdwardWong  Thanks for reporting, for "how" questions and third party issues, please help raise a post on our forum at https://esp32.com, thanks.

**Comment by Alvin1Zhang** [comment]
https://github.com/EspressifApp/EspBlufiForiOS/issues/15

**Comment by Wth-Esp** [comment]
Hi @AdwardWong 

Sorry, I cannot understand your question, please use proper language and manage your words properly.

Thanks
Weitianhaua

**Comment by younglee123** [comment]
Hi @AdwardWong
I gave it a try, and it works with both Android and ios(iPad(Seventh generation)). I don't know why you can't, would you please help provide more details to help me debug further or you can just close this issue.

**Comment by AdwardWong** [comment]
No debugging for now
