### ISSUE TITLE
[TW#12289] BLE GATT - Performing bitwise OR against enums does not result in an enum

### ISSUE THREAD

**Issue by nkolban** [espressif/esp-idf#527]
If we take a look at the following two C enum definitions found here:

https://github.com/espressif/esp-idf/blob/master/components/bt/bluedroid/api/include/esp_gatt_defs.h#L267

and here

https://github.com/espressif/esp-idf/blob/master/components/bt/bluedroid/api/include/esp_gatt_defs.h#L279

We find that they are bit definitions for flags for BLE GATT.  For example, if we look at the `esp_ble_gatts_add_char()` function we find parameters of type `esp_gatt_perm_t` and `esp_gatt_char_prop_t`.  This would imply that we can make a call similar to the following:

```
esp_ble_gatts_add_char(..., ESP_GATT_PERM_READ | ESP_GATT_PERM_WRITE, ....);
```

However, in a strict C/C++ compiler, this fails.  The reason for this is that if we perform a bitwise OR against two enums, we end up with an "int" and not an enum matching the parts of the OR.

For example ... the data type of `ESP_GATT_PERM_READ` is `esp_gatt_perm_t` by the data type of `ESP_GATT_PERM_READ | ESP_GATT_PERM_WRITE` is an `int`.  In the signature of `esp_ble_gatts_add_char()` we expect an instance of `esp_gatt_perm_t` and not an instance of an `int`.  We can work around this by performing an explicit typecast, but I'm thinking that we might want to define the type as an `int` and define the values as `#define` constants.

**Comment by Yulong-espressif** [comment]
@nkolban Thank you so much for your suggestion, we have change it in the new version of SDK. You can get it from the github. Any question, please let me know.
