### ISSUE TITLE
[TW#12106] eclipse : project in .cpp build project also with error

### ISSUE THREAD

**Issue by sfranchin63** [espressif/esp-idf#529]
Hi,
I tried to build a project in cpp. Eclipse tells me that there are some mistakes, but the project is ok and I can download it. How can these errors disappear?
![ili9341 error eclipse](https://cloud.githubusercontent.com/assets/23196408/25137457/19b6e58a-2458-11e7-943e-eb641c356ae7.JPG)

**Comment by projectgus** [comment]
Hi @sfranchin63 ,

It looks like Eclipse may not be configured correctly to find all of the header paths in your system. When this is the case, the build succeeds but the code editor shows errors like this. If you scroll to the top of the file, does it mark the `#include` statements at the top as being errors, also?

If this looks like the problem, make sure to very carefully follow the steps to set up the Eclipse project in Windows, as shown here:
http://esp-idf.readthedocs.io/en/latest/eclipse-setup-windows.html

Some third party tutorials are based on an older version of these steps, and following their steps will not correctly find all search paths.

After checking all the project properties, run Project -> Clean then Project -> Build to allow Eclipse to regenerate its internal cache of search paths.

**Comment by igrr** [comment]
Hi @sfranchin63, did the above suggestion help you resolve the issue?
