### ISSUE TITLE
Missing semicolon in esp_netif_lwip.c (IDFGH-3311)

### ISSUE THREAD

**Issue by maximekli** [espressif/esp-idf#5294]
At the end of line:
https://github.com/espressif/esp-idf/blob/5e436be77f68b1ba7d2ebbefb8aeda34f6c71276/components/esp_netif/lwip/esp_netif_lwip.c#L617

**Comment by AxelLin** [comment]
And there is a typo in the message: woth -> with.

**Comment by Alvin1Zhang** [comment]
@maximekli @AxelLin Thanks for report and letting us know about this. We will look into.

**Comment by Alvin1Zhang** [comment]
@maximekli @AxelLin Thanks for reporting this. We have a fix for this and in our internal review and merge queue, this issue will be updated when they're merged. Thanks.
