### ISSUE TITLE
[ble mesh] typo (IDFGH-3389)

### ISSUE THREAD

**Issue by chegewara** [espressif/esp-idf#5361]
I believe its leftover after refactoring:
https://github.com/espressif/esp-idf/blob/master/components/bt/esp_ble_mesh/mesh_core/include/mesh_access.h#L245

Should be `.model_id = (_id),`

**Comment by Alvin1Zhang** [comment]
@chegewara Thanks for pointing out, we will look into.

**Comment by Campou** [comment]
Hi @chegewara 

https://github.com/espressif/esp-idf/blob/7d75213674b4572f90c68162ad6fe9b16dae65ad/components/bt/esp_ble_mesh/mesh_core/include/mesh_access.h#L404

`id` is a parameter in `struct bt_mesh_model`.

Thanks.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, feel free to reopen if the issue still exists. Thanks.
