### ISSUE TITLE
Wifi: sta connection maximum SSID 31char (IDFGH-3429)

### ISSUE THREAD

**Issue by brazoayeye** [espressif/esp-idf#5392]
Hello, I reported a bug to a side project regarding this topic: maximum password length is 31char but sometimes routers have built-in password longer than 31 chars. 

Isn't possible to increase the maximum size to the standard 63char to avoid problems with strange configurations?

Thanks

https://github.com/martin-ger/esp32_nat_router/issues/17

**Comment by negativekelvin** [comment]
https://github.com/espressif/esp-idf/issues/3762

**Comment by HarveyRong-Esp** [comment]
Hi @brazoayeye，
802.11-2016 stipulates that the maximum SSID is 32, which will not reach 64. At present, the maximum SSID length that can be configured with ESP32 is also 32.
![捕获](https://user-images.githubusercontent.com/53294950/98515629-49065780-22a6-11eb-8a1b-c70857af29c0.PNG)
