### ISSUE TITLE
SCAN OTHER BLE DEVICE IN ESP32 

### ISSUE THREAD

**Issue by erkt** [espressif/esp-idf#540]
it possible to run [example](https://github.com/espressif/esp-idf/tree/master/examples/bluetooth/gatt_server) of Bluetooth in ESP32 using arduino?

**Comment by projectgus** [comment]
This is the IDF project not Arduino for ESP32, so we don't provide support for Arduino here.

It is possible to use IDF code from Arduino, however it will require some tweaking to work.

The best place to ask this question is probably on our forum: https://esp32.com/viewforum.php?f=19&sid=d4f0b4ac9fe48eaa229094c5bbd7f45f

**Comment by tejaswigowda** [comment]
Can you provide example for esp-idf?
