### ISSUE TITLE
ESP32-S2 rev0 APLL setup (IDFGH-3439)

### ISSUE THREAD

**Issue by ikostoski** [espressif/esp-idf#5400]
https://github.com/espressif/esp-idf/blob/c1d0daf36d0dca81c23c226001560edfa51c30ea/components/soc/src/esp32/rtc_clk.c#L250

Code in 'rtc_clk_apll_enable' checks for rev0 of ESP32, however ESP32-S2 rev0 should not have problems with APLL. Isn't this part of code be specific to ESP32 only ?

**Comment by igrr** [comment]
The corresponding function for S2 is here: https://github.com/espressif/esp-idf/blob/c1d0daf36d0dca81c23c226001560edfa51c30ea/components/soc/src/esp32s2/rtc_clk.c#L142

**Comment by ikostoski** [comment]
Thank you. I did not notice there is separate function compiled under S2 tree.
