### ISSUE TITLE
I2S Slave bit set to 1 in Master mode? (IDFGH-3450)

### ISSUE THREAD

**Issue by niclash** [espressif/esp-idf#5403]
https://github.com/espressif/esp-idf/blob/63cd2b06137ddfab9a3df0a9905698b526f4e87d/components/soc/src/hal/i2s_hal.c#L240

Shouldn't both SLAVE bits be set to "0" when in master mode?

**Comment by koobest** [comment]
Hi, @niclash 
In master loop back mode(master TX and RX sharing the same BCK and WS), the receiver should set to slave mode.

**Comment by niclash** [comment]
Ok, but that isn't the only way it can operate, right? 
Nevertheless, is there a complete(!) example of streaming from I2S external encoder, into processing that stream and out to an external I2S encoder?? I can't find one...

**Comment by koobest** [comment]
Hi, @niclash
The driver does not support this feature because the transmitter and receiver may have different sampling rates..  you can use I2S0 for TX and I2S1 for RX on ESP32, but if you use ESP32-S2, the only way is to rewrite the driver.

thanks !!

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, feel free to reopen if you still have the issue, or please help file a new ticket for new issue. Thanks.
