### ISSUE TITLE
Callback parameter for esp_spp_cb_param_t::spp_open_evt_param open in example bluedroid/classic_bt/bt_spp_initiator (IDFGH-3447)

### ISSUE THREAD

**Issue by DrClaudio73** [espressif/esp-idf#5409]
## Environment

- Development Kit:      [none]
- Kit version (
- Module or chip used:  []
- IDF version (run ``git describe --tags`` to find it): v4.2-dev-910-g4fe04f115
- Build System:         Make|CMake|idf.py
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it):
- Operating System:     Windows|Linux|macOS
- Using an IDE?: [Yes (VScode)]
- Power Supply:         USB|external 5V|external 3.3V|Battery

## Problem Description
In file esp-idf/examples/bluetooth/bluedroid/classic_bt/bt_spp_initiator/main/example_spp_initiator_demo.c

at line 119, this instruction:

esp_spp_write(param->srv_open.handle, SPP_DATA_LEN, spp_data);

should be changed with:

esp_spp_write(param->open.handle, SPP_DATA_LEN, spp_data);

as per API reference documentation.

//Detailed problem description goes here.
struct esp_spp_cb_param_t::spp_open_evt_param open
  SPP callback param of ESP_SPP_OPEN_EVT

Thank you for your great work.

**Comment by Alvin1Zhang** [comment]
@DrClaudio73 Thanks for reporting, we will look into.
