### ISSUE TITLE
idf 4.0.1  ble gatt_client  (IDFGH-3466)

### ISSUE THREAD

**Issue by myzhang001** [espressif/esp-idf#5426]
1. Environment
esp32 idf 4.0.1 gatt_client
2. The problem
1. When I use the gatt_client example to build the project, the esp32 ble scan stops after 30 seconds.
2. When the slave device is disconnected from gatt_client, gat_client cannot continue scanning

**Comment by Alvin1Zhang** [comment]
@myzhang001 Thanks for reporting. Would you please help provide more details as suggested in the [issue template](https://github.com/espressif/esp-idf/issues/new?assignees=&labels=&template=bug_report.md&title=)? Information like elf, sdk configuration, backtrace, log outputs, commit ID, hardware and etc. would help us debug further. Thanks.
