### ISSUE TITLE
mcpwm_sync_signal_t missing enums (IDFGH-3469)

### ISSUE THREAD

**Issue by majodi** [espressif/esp-idf#5429]
## Environment

- Development Kit: ESP32-DevKitC
- Kit version: DevKitC
- Module or chip used: ESP32
- IDF version: 4.0.1
- Build System: CMake
- Compiler version: 8.2.0
- Operating System: Linux
- Using an IDE?: VSCode + Platformio
- Power Supply: USB

## Problem Description
I need to generate a symmetrical PWM wave form for driving a BLDC motor using MCPWM. So I would like to sync the PWM0, 1 and 2. To do so I use mcpwm_sync_enable(). For the sync_sig I would like to use a timer (not a GPIO). But the type definition for mcpwm_sync_signal_t only has the options enumerated for GPIO. It starts at 4.

The ESP32 Technical Reference Manual says I need 1, 2 or 3 for syncing with timer:

**1: PWM timer0 sync_out
2: PWM timer1 sync_out
3: PWM timer2 sync_out**
4: SYNC0 from GPIO matrix
5: SYNC1 from GPIO matrix
6: SYNC2 from GPIO matrix
other values: no sync input selected.

I did edit MCPWM.h to add options 1, 2 and 3. I then selected PWM timer0 as sync input and I get exactly what I need; a symmetrical PWM wave form. So the technical reference seems to be correct.

Why are these enums missing? Should I do this in a different way?

### Code to reproduce this issue
```
// setup mcpwm configuration
void setup_mcpwm_configuration(int pwmFreq) {
    mcpwm_config_t pwm_config;
    pwm_config.frequency = pwmFreq;                         // up-down counter results in half of this
    pwm_config.cmpr_a = 50.0;                               // duty cycle of PWMxA = 50.0%
    pwm_config.cmpr_b = 50.0;                               // duty cycle of PWMxB = 50.0%
    pwm_config.counter_mode = MCPWM_UP_DOWN_COUNTER;        // Up-down counter (triangle wave)
    pwm_config.duty_mode = MCPWM_DUTY_MODE_0;               // Active HIGH
    mcpwm_init(MCPWM_UNIT_0, MCPWM_TIMER_0, &pwm_config);   // Configure PWM0A & PWM0B with above settings
    mcpwm_init(MCPWM_UNIT_0, MCPWM_TIMER_1, &pwm_config);   // Configure PWM0A & PWM0B with above settings
    mcpwm_init(MCPWM_UNIT_0, MCPWM_TIMER_2, &pwm_config);   // Configure PWM0A & PWM0B with above settings
    mcpwm_sync_enable(MCPWM_UNIT_0, MCPWM_TIMER_0, MCPWM_SELECT_SYNC_OUT0, 0); // !!! MCPWM_SELECT_SYNC_OUT0 didn't exist in mcpwm.h, had to edit the header
    mcpwm_sync_enable(MCPWM_UNIT_0, MCPWM_TIMER_1, MCPWM_SELECT_SYNC_OUT0, 0); // it sets to sync all timers to timer0
    mcpwm_sync_enable(MCPWM_UNIT_0, MCPWM_TIMER_2, MCPWM_SELECT_SYNC_OUT0, 0); // questions about this posted on esp32.com
    MCPWM0.timer[0].sync.out_sel = 1;                       // timer 0 as sync input (https://github.com/espressif/esp-idf/issues/3567)
    vTaskDelay(500/portTICK_PERIOD_MS);                     // wait long enough for large period PWM (low frequency) to be able to sysnc
    MCPWM0.timer[0].sync.out_sel = 0;                       // done syncing
    mcpwm_set_duty(MCPWM_UNIT_0, MCPWM_TIMER_0, MCPWM_OPR_A, 0);    // set initial duty 0 (disengage motor)
    mcpwm_set_duty(MCPWM_UNIT_0, MCPWM_TIMER_0, MCPWM_OPR_B, 100);  // set enable to continues high
    mcpwm_set_duty(MCPWM_UNIT_0, MCPWM_TIMER_1, MCPWM_OPR_A, 0);
    mcpwm_set_duty(MCPWM_UNIT_0, MCPWM_TIMER_1, MCPWM_OPR_B, 100);
    mcpwm_set_duty(MCPWM_UNIT_0, MCPWM_TIMER_2, MCPWM_OPR_A, 0);
    mcpwm_set_duty(MCPWM_UNIT_0, MCPWM_TIMER_2, MCPWM_OPR_B, 100);
}

```

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, we will look into.

**Comment by koobest** [comment]
Hi, @majodi
I think your configuration is OK if the three timer is correctly initialized.  Since the driver writer has resigned, it is not clear why this feature was missed. We will evaluate whether it can be added to the driver.

thanks !!

**Comment by majodi** [comment]
No problem. Should I close this issue now?
