### ISSUE TITLE
ESP-IDF version 4.0 (IDFGH-3472)

### ISSUE THREAD

**Issue by marina936** [espressif/esp-idf#5432]
Good Morning,

I am using ESP-IDF version 4.0 and I don't find adc.c file. I want to find the body of the function adc_i2s_mode_init(). In another versions like 4.1 and 4.2, this function is included in the adc.c file but I don't know how it works in 4.0 version.

**Comment by igrr** [comment]
It is here, just in a different file:
https://github.com/espressif/esp-idf/blob/4c81978a3e2220674a432a588292a4c860eef27b/components/driver/rtc_module.c#L1383-L1415

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, feel free to reopen if you still have the issue. Thanks.
