### ISSUE TITLE
ESP32s2 无法使用jd_decomp与jd_prepare (IDFGH-3474)

### ISSUE THREAD

**Issue by HoGC** [espressif/esp-idf#5434]
使用ESP-IDF 4.2导入esp32s2/rom/tjpgd.h
编译报错
```
undefined reference to `jd_prepare'
undefined reference to `jd_decomp'
```

**Comment by suda-morris** [comment]
Sorry for the inconvenience, tjpgd library does not exist in ESP32-S2 ROM. 
The header file must be added by accident. We will remove it.
If you want to use tjpgd, you should pull in the source code and add them into your build. See https://github.com/espressif/esp-idf/tree/master/examples/peripherals/spi_master/lcd/components/tjpgd
