### ISSUE TITLE
[TW#12100] CAN Driver

### ISSUE THREAD

**Issue by saeugetier** [espressif/esp-idf#544]
Hi devs,

are there any plans to support a CAN driver in the ESP-IDF. I saw there is no describtion of the CAN interface in the ESP32 technical refence. But for example Simba RTOS has implemented the CAN interface.

**Comment by zelll** [comment]
There isn't a CAN driver in official ESP-IDF, but it seems someone has made one: https://www.esp32.com/viewtopic.php?f=12&t=380

**Comment by igrr** [comment]
@ThomasBarth has written a CAN driver for the ESP32, it is available as a component here:
https://github.com/ThomasBarth/ESP32-CAN-Driver/

I'll keep this issue open, but for now we don't have near term plans for a CAN driver.

**Comment by jolivepetrus** [comment]
A minimal CAN driver is available in Lua RTOS:

https://github.com/whitecatboard/Lua-RTOS-ESP32/blob/master/components/lua_rtos/drivers/can.c
https://github.com/whitecatboard/Lua-RTOS-ESP32/tree/master/components/can

https://github.com/whitecatboard/Lua-RTOS-ESP32/wiki/CAN-module

**Comment by snahmad** [comment]
is can driver is available now officially?
