### ISSUE TITLE
I2S ADC glitches (IDFGH-3486)

### ISSUE THREAD

**Issue by marina936** [espressif/esp-idf#5444]
I am trying to read from ADC with I2S. I configure I2S frequency to 120 KHz, 16 bit and only channel right, like this:

static const i2s_config_t i2s_config = {
.mode = I2S_MODE_MASTER | I2S_MODE_RX | I2S_MODE_ADC_BUILT_IN,
.sample_rate = 120000,
.bits_per_sample = I2S_BITS_PER_SAMPLE_16BIT,
.channel_format = I2S_CHANNEL_FMT_ONLY_RIGHT,
.communication_format = 0,
.intr_alloc_flags = 0, // default interrupt priority
.dma_buf_count = 3,
.dma_buf_len = NUM_SAMPLES,
.use_apll = true,  
.fixed_mclk = 120000
};
I add continuos square signals of 1KHz and amplitude 1V to the ADC.

This is what I receive reading ADC with I2S.

![transitorios_señal](https://user-images.githubusercontent.com/66781072/84497623-73c89180-acaf-11ea-9828-ba984856a5a8.png)

In the signals I receive I show some kind of peaks (transitories) in the edge of the signals.

Can anyone explain why this happens? And how I can delete these peaks?

**Comment by koobest** [comment]
Hi, @marina936
The relationship between data storage order and sampling is：

![image](https://user-images.githubusercontent.com/22807748/84559067-5ad0e680-ad6a-11ea-919c-4a0204612b71.png)

 [ sample1, sample0, sample3, sample2 ...];

**Comment by marina936** [comment]
I don't understand the relation of that with the strange glitches in every signal

**Comment by koobest** [comment]
Hi,@marina936
This is not sample glitches. Can you swap the sample data by software and then draw the waveform?
```
uint16_t *sample_buf;// the buffer userd to store the sample data.
...
...
uint16_t tmp;
...

for (int i = 0; i < sample_cnt; i+=2) {
    tmp = sample_buf[i];
    sample_buf[i] = sample_buf[i+1];
    sample_buf[i+1] = tmp;
}

draw(sample_buf, sample_cnt);
```

thanks

**Comment by marina936** [comment]
Why is necessary to swap sample data?

**Comment by koobest** [comment]
See the reply here: https://github.com/espressif/esp-idf/issues/5444#issuecomment-643563107
