### ISSUE TITLE
Move this to documentation - Event typo (IDFGH-3488)

### ISSUE THREAD

**Issue by dragahassan** [espressif/esp-idf#5446]
I didn't find where to create a request to fix a event name typo, so please remove this or moved to the right place.

**Document link:**
[docs.espressif.com - esp_err_t esp_ble_gatts_create_service()](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/bluetooth/esp_gatts.html#_CPPv428esp_ble_gatts_create_service13esp_gatt_if_tP18esp_gatt_srvc_id_t8uint16_t)

**Typo:**
`callback event BTA_GATTS_CREATE_SRVC_EVT is called to...`

**Fix:**
`callback event ESP_GATTS_CREATE_EVT is called to...`

Thank you.

**Comment by Alvin1Zhang** [comment]
@hassance3 Thanks for reporting and pointing out, we will look into.

**Comment by WCCWCC** [comment]
@hassance3 
We will fix this problem as soon as possible.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting and sorry for slow turnaround, the fix is available at https://github.com/espressif/esp-idf/commit/f73cd1d4f1128c8a66b9f386bde409d08f2ac8fa. Feel free to reopen if the issue still happens.
