### ISSUE TITLE
[S2] USB host (IDFGH-3498)

### ISSUE THREAD

**Issue by chegewara** [espressif/esp-idf#5454]
Hi, just a quick question. 
I know there is topic on forum that is show progress on S2 api development
https://esp32.com/viewtopic.php?f=10&p=56361

but its not updated for quite some time. Is there some progress or timeline on USB host?

Thanks.

**Comment by igrr** [comment]
Hi @chegewara, unfortunately we don't have timeline for the USB Host feature, yet.

**Comment by chegewara** [comment]
Thanks.
Will close it for now.
