### ISSUE TITLE
failing to set duty resolution of ledc timer (IDFGH-3503)

### ISSUE THREAD

**Issue by michox** [espressif/esp-idf#5458]
## Environment

- Development Kit:      [ESP32-DevKitC]
- Kit version (v1]
- Module or chip used:  [ESP32-WROOM-32]
- IDF version latest PlatformIO version
- Build System:         PlatformIO

- Operating System:     [Windows]
- (Windows only) environment type: PlatformIO
- Using an IDE?: [No|PlatformIO]

## Problem Description

I am trying to set the duty resolution like in https://github.com/espressif/esp-idf/blob/7d75213674b4572f90c68162ad6fe9b16dae65ad/examples/peripherals/ledc/main/ledc_example_main.c

### Expected Behavior
shozld be able to set duty resolution
### Actual Behavior
IDE warning: a designator for an anonymous union member can only appear within braces corresponding to that anonymous union. Also, LEDC_AUTO_CLK is undefined even though I implemented all headers from the example
### Steps to reproduce
include header and in some function paste the code

### Code to reproduce this issue

```ledc_timer_config_t ledc_timer = {
        .duty_resolution=LEDC_TIMER_13_BIT,               
        .freq_hz = 0,                       // frequency of PWM signal
        .speed_mode = LEDC_HIGH_SPEED_MODE, // timer mode
        .timer_num = LEDC_TIMER_1,          // timer index
        .clk_cfg = LEDC_AUTO_CLK,           // Auto select the source clock
    };

```
// If your code is longer than 30 lines, [GIST](https://gist.github.com) is preferred.

## Debug Logs
before deleting .clk_cfg = LEDC_AUTO_CLK, 
```
error: 'ledc_timer_config_t' has no non-static data member named 'clk_cfg'
```
after deleting it
```
sorry, unimplemented: non-trivial designated initializers not supported
```

**Comment by Alvin1Zhang** [comment]
Thanks for reporting and letting us know, we will look into.

**Comment by wilhelmw-97** [comment]
a compile time error is ..erm.. probably because of a grammatical error in your code. did you get the struct initialization right?

**Comment by michox** [comment]
should be. after editing the source code and replacing the union by only duty_resolution, it works fine. Unfortunately, I was not able to find how to initialize an anonymous union like this but also the example should be updated to a working one so I thought I will let you know

**Comment by Alvin1Zhang** [comment]
@michox Thanks for reporting, would you please help share if any updates for this issue? Thanks.

**Comment by michox** [comment]
I have given up on this and are using the arduino component instead which works fine

**Comment by rowifi** [comment]
Instead of using 
   .duty_resolution=LEDC_TIMER_13_BIT,  
try taking it out of the structure construct and initialising separately

 structname. duty_resolution=LEDC_TIMER_13_BIT;

**Comment by rowifi** [comment]
Just like ..

```
ledc_timer_config_t ledc_timer;
  ledc_channel_config_t ledc_channel;
 
  ledc_timer.speed_mode   = LEDC_HIGH_SPEED_MODE;
  ledc_timer.timer_num    = LEDC_TIMER_0;
  ledc_timer.duty_resolution       = LEDC_TIMER_8_BIT;// (ledc_timer_bit_t) 1;
  ledc_timer.freq_hz      = 500;
 
  ledc_channel.channel    = LEDC_CHANNEL_0;
  ledc_channel.gpio_num   = LEDA_PIN;
  ledc_channel.speed_mode = LEDC_HIGH_SPEED_MODE;
  ledc_channel.timer_sel  = LEDC_TIMER_0;
  ledc_channel.duty       = 80;
 
  ledc_timer_config(&ledc_timer);
  ledc_channel_config(&ledc_channel);
```

**Comment by ginkgm** [comment]
This issue has been long. If you still find issues, feel free to reopen.
