### ISSUE TITLE
[TW#12099] Wifi PA

### ISSUE THREAD

**Issue by lmagalhaes1337** [espressif/esp-idf#546]
Is it possible to turn off the PA while scanning for APs? Better yet, is it possible to turn off the PA completly before starting the Wifi module?

Thanks,

**Comment by TimXia** [comment]
@lmagalhaes1337 Before starting the WiFi module, the PA is off. It is turned on when calling esp_wifi_start(). You can call esp_wifi_stop() to turn off the PA while scanning for APs.

**Comment by lmagalhaes1337** [comment]
Can you please explain the sequence of commands to do that? I've tried a couple of things and they haven't worked.

```
wifi_scan_config_t scanConfig;
	scanConfig.ssid = 0;
		scanConfig.bssid = 0;
		scanConfig.channel = 0;
		scanConfig.show_hidden = true;
		//scanConfig.scan_type = WIFI_SCAN_TYPE_PASSIVE;
```
Using the passive scan type crashes the CPU.

```
ESP_ERROR_CHECK(esp_wifi_scan_start(&scanConfig, false));
		ESP_ERROR_CHECK(esp_wifi_stop());
		vTaskDelay(1000/portTICK_RATE_MS); // free the CPU for 100ms

		// get the list of APs found in the last scan
			ESP_ERROR_CHECK(esp_wifi_scan_get_ap_records(&apNum, apRecords));
```
This will give an error saying that the wifi is not enabled to get the ap records. Adding a ESP_ERROR_CHECK(esp_wifi_start()); line before the get ap records routine will make the code work but not output any AP. Care to help?

Thanks,

Luis

**Comment by TimXia** [comment]
@lmagalhaes1337 Sorry for some explaining mistake. The PA can not be turned off when scanning for APs. If you want to do something with WiFi like scaning and connecting, you must call esp_wifi_start() first. If you do not need WiFi any more, call esp_wifi_stop() please.

**Comment by TimXia** [comment]
@lmagalhaes1337 Do you mean that esp32 does not send probe request when scan for APs?

**Comment by lmagalhaes1337** [comment]
No, I was just asking if it was possible to turn off the PA while scanning for APs.

**Comment by TimXia** [comment]
@lmagalhaes1337 If esp32 does not send frame, the PA is not turned on.

**Comment by lmagalhaes1337** [comment]
But to send the frame, is it mandatory for the PA to be turned on?

**Comment by TimXia** [comment]
@lmagalhaes1337 Yes.

**Comment by jack0c** [comment]
@lmagalhaes1337 We study this problem again, we can provide this API, but not in idf2.1

**Comment by TimXia** [comment]
@lmagalhaes1337 If ESP32 is sending data, PA is turned on mandatorily. After data is sent out, PA is turned off mandatorily.
