### ISSUE TITLE
VL53L1X with ESP32 (IDFGH-3509)

### ISSUE THREAD

**Issue by marina936** [espressif/esp-idf#5464]
I want to measure distance with the proximity sensor VL53L1X of STMicroelectronics and ESP32.

I configured I2S to read the sensor reference registers and initialize correctly the sensor, but when I want to read a measurement I get this error VL53L1_ERROR_CONTROL_INTERFACE. The next times I want to read a measurement there's no error but data is never ready.

Has anyone work with VL53L1X api and ESP32? It can be an I2C problem?

**Comment by chegewara** [comment]
Hi,
ive been working recently with that sensor and it is very sensitive on i2c physical connection. I had problems with it on my breadboard and client did not when soldered on PCB.

Please try if you have any chance to test with this library:
https://github.com/pololu/vl53l1x-arduino
It is arduino library but its quick way to test connectivity.

Also remember it is not easy sensor to work with, likes to hang when you do something that you should not.
