### ISSUE TITLE
[TW#12088] add eMMC support?

### ISSUE THREAD

**Issue by murraysst** [espressif/esp-idf#547]
Hi, any plans or timeline for supporting eMMC?

**Comment by ESP32DE** [comment]
1+
wait for eMMC  too

best wishes
rudi ;-)

**Comment by igrr** [comment]
Implemented in https://github.com/espressif/esp-idf/commit/31cbd1b251eff20368fe30d8551c71cb46c50a2d based on PRs #1941 and #590.
