### ISSUE TITLE
Reboot after ret esp_vfs_fat_sdspi_mount (IDFGH-3519)

### ISSUE THREAD

**Issue by chuledeco** [espressif/esp-idf#5474]
## Environment

- Development Kit:     Custom board with ESP32-pico-D4
- Module or chip used:  ESP32-PICO-D4
- IDF version ESP-IDF v4.2-dev-1415-ga2263571b-dirty 2nd stage bootloader
- Build System:         idf.py
- Operating System:     Windows
- Using an IDE?: Eclipse
- Power Supply:        external 3.3V

## Problem Description

Hello! I loaded the sd_car_example and it worked with the previous version of esp-idf but now with 4.2 after 
`ret = esp_vfs_fat_sdspi_mount(mount_point, &host, &slot_config, &mount_config, &card);`
 the system reboot with no error message.

Could it be a problem with the latest version of esp-idf?

Thanks

## Debug Logs

```
rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 188777542, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:4
load:0x3fff0034,len:7100
load:0x40078000,len:13696
load:0x40080400,len:4000
entry 0x40080688
I (30) boot: ESP-IDF v4.2-dev-1415-ga2263571b-dirty 2nd stage bootloader
I (30) boot: compile time 18:10:35
I (31) boot: chip revision: 1
I (35) boot_comm: chip revision: 1, min. bootloader chip revision: 0
I (42) boot.esp32: SPI Speed      : 40MHz
I (47) boot.esp32: SPI Mode       : DIO
I (51) boot.esp32: SPI Flash Size : 2MB
I (56) boot: Enabling RNG early entropy source...
I (61) boot: Partition Table:
I (65) boot: ## Label            Usage          Type ST Offset   Length
I (72) boot:  0 nvs              WiFi data        01 02 00009000 00006000
I (80) boot:  1 phy_init         RF data          01 01 0000f000 00001000
I (87) boot:  2 factory          factory app      00 00 00010000 00100000
I (95) boot: End of partition table
I (99) boot_comm: chip revision: 1, min. application chip revision: 0
I (106) esp_image: segment 0: paddr=0x00010020 vaddr=0x3f400020 size=0x0a35c ( 41820) map
I (131) esp_image: segment 1: paddr=0x0001a384 vaddr=0x3ffb0000 size=0x022b8 (  8888) load
I (135) esp_image: segment 2: paddr=0x0001c644 vaddr=0x40080000 size=0x00404 (  1028) load
I (138) esp_image: segment 3: paddr=0x0001ca50 vaddr=0x40080404 size=0x035c8 ( 13768) load
I (152) esp_image: segment 4: paddr=0x00020020 vaddr=0x400d0020 size=0x1d144 (119108) map
I (201) esp_image: segment 5: paddr=0x0003d16c vaddr=0x400839cc size=0x07e40 ( 32320) load
I (221) boot: Loaded app from partition at offset 0x10000
I (221) boot: Disabling RNG early entropy source...
I (222) cpu_start: Pro cpu up.
I (225) cpu_start: Application information:
I (230) cpu_start: Project name:     sd_card
I (235) cpu_start: App version:      1
I (240) cpu_start: Compile time:     Jun 20 2020 18:11:32
I (246) cpu_start: ELF file SHA256:  fb3d03082c472c70...
I (252) cpu_start: ESP-IDF:          v4.2-dev-1415-ga2263571b-dirty
I (259) cpu_start: Starting app cpu, entry point is 0x400816ec
I (0) cpu_start: App cpu up.
I (269) heap_init: Initializing. RAM available for dynamic allocation:
I (276) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM
I (282) heap_init: At 3FFB2B58 len 0002D4A8 (181 KiB): DRAM
I (288) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM
I (295) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
I (301) heap_init: At 4008B80C len 000147F4 (81 KiB): IRAM
I (307) cpu_start: Pro cpu start user code
I (325) spi_flash: detected chip: gd
I (326) spi_flash: flash io: dio
W (326) spi_flash: Detected size(4096k) larger than the size in the binary image header(2048k). Using the size in the binary image header.
I (336) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.
I (347) example: Initializing SD card
I (347) example: Using SPI peripheral
I (2357) example: goto spi_bus_initialize
I (3357) example: done spi_bus_initialize
I (4357) example: goto esp_vfs_fat_sdspi_mount
ets Jun  8 2016 00:22:57

rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 188777542, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:4
load:0x3fff0034,len:7100
load:0x40078000,len:13696
load:0x40080400,len:4000
entry 0x40080688
I (30) boot: ESP-IDF v4.2-dev-1415-ga2263571b-dirty 2nd stage bootloader
```

## Other items if possible

The code to reproduce the error is the example, I just added some more ESP_LOGI for debugging

`/* SD card and FAT filesystem example.
   This example code is in the Public Domain (or CC0 licensed, at your option.)

   Unless required by applicable law or agreed to in writing, this
   software is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
   CONDITIONS OF ANY KIND, either express or implied.
*/

#include <stdio.h>
#include <string.h>
#include <sys/unistd.h>
#include <sys/stat.h>
#include "esp_err.h"
#include "esp_log.h"
#include "esp_vfs_fat.h"
#include "driver/sdmmc_host.h"
#include "driver/sdspi_host.h"
#include "driver/spi_common.h"
#include "sdmmc_cmd.h"

#include "esp_system.h"
#include "esp_event.h"

static const char *TAG = "example";

#define MOUNT_POINT "/sdcard"

// This example can use SDMMC and SPI peripherals to communicate with SD card.
// By default, SDMMC peripheral is used.
// To enable SPI mode, uncomment the following line:

#define USE_SPI_MODE

#define SPI_DMA_CHAN    1

// When testing SD and SPI modes, keep in mind that once the card has been
// initialized in SPI mode, it can not be reinitialized in SD mode without
// toggling power to the card.

#ifdef USE_SPI_MODE
// Pin mapping when using SPI mode.
// With this mapping, SD card can be used both in SPI and 1-line SD mode.
// Note that a pull-up on CS line is required in SD mode.
#define PIN_NUM_MISO 2
#define PIN_NUM_MOSI 15
#define PIN_NUM_CLK  14
#define PIN_NUM_CS   13
//#define PIN_NUM_ADCCS 27
#endif //USE_SPI_MODE

void app_main(void)
{
gpio_set_pull_mode(15, GPIO_PULLUP_ONLY);
gpio_set_pull_mode(2, GPIO_PULLUP_ONLY);
gpio_set_pull_mode(14, GPIO_PULLUP_ONLY);
//gpio_set_pull_mode(27, GPIO_PULLUP_ONLY);
gpio_set_pull_mode(13, GPIO_PULLUP_ONLY);
    esp_err_t ret;
    // Options for mounting the filesystem.
    // If format_if_mount_failed is set to true, SD card will be partitioned and
    // formatted in case when mounting fails.
    esp_vfs_fat_sdmmc_mount_config_t mount_config = {
        .format_if_mount_failed = false,
        .max_files = 5,
        .allocation_unit_size = 16 * 1024
    };
    sdmmc_card_t* card;
    const char mount_point[] = MOUNT_POINT;
    ESP_LOGI(TAG, "Initializing SD card");

    // Use settings defined above to initialize SD card and mount FAT filesystem.
    // Note: esp_vfs_fat_sdmmc/sdspi_mount is all-in-one convenience functions.
    // Please check its source code and implement error recovery when developing
    // production applications.
#ifndef USE_SPI_MODE
    ESP_LOGI(TAG, "Using SDMMC peripheral");
    sdmmc_host_t host = SDMMC_HOST_DEFAULT();

    // This initializes the slot without card detect (CD) and write protect (WP) signals.
    // Modify slot_config.gpio_cd and slot_config.gpio_wp if your board has these signals.
    sdmmc_slot_config_t slot_config = SDMMC_SLOT_CONFIG_DEFAULT();

    // To use 1-line SD mode, uncomment the following line:
    // slot_config.width = 1;

    // GPIOs 15, 2, 4, 12, 13 should have external 10k pull-ups.
    // Internal pull-ups are not sufficient. However, enabling internal pull-ups
    // does make a difference some boards, so we do that here.
    gpio_set_pull_mode(15, GPIO_PULLUP_ONLY);   // CMD, needed in 4- and 1- line modes
    gpio_set_pull_mode(2, GPIO_PULLUP_ONLY);    // D0, needed in 4- and 1-line modes
    gpio_set_pull_mode(4, GPIO_PULLUP_ONLY);    // D1, needed in 4-line mode only
    gpio_set_pull_mode(12, GPIO_PULLUP_ONLY);   // D2, needed in 4-line mode only
    gpio_set_pull_mode(13, GPIO_PULLUP_ONLY);   // D3, needed in 4- and 1-line modes

    ret = esp_vfs_fat_sdmmc_mount(mount_point, &host, &slot_config, &mount_config, &card);
#else
    ESP_LOGI(TAG, "Using SPI peripheral");
    vTaskDelay(1000 / portTICK_PERIOD_MS);

    sdmmc_host_t host = SDSPI_HOST_DEFAULT();

    vTaskDelay(1000 / portTICK_PERIOD_MS);
    host.max_freq_khz = 20000;

    spi_bus_config_t bus_cfg = {
        .mosi_io_num = PIN_NUM_MOSI,
        .miso_io_num = PIN_NUM_MISO,
        .sclk_io_num = PIN_NUM_CLK,
        .quadwp_io_num = -1,
        .quadhd_io_num = -1,
        .max_transfer_sz = 4000,
    };
    ESP_LOGI(TAG, "goto spi_bus_initialize");
    vTaskDelay(1000 / portTICK_PERIOD_MS);

    ret = spi_bus_initialize(host.slot, &bus_cfg, SPI_DMA_CHAN);
    if (ret != ESP_OK) {
        ESP_LOGE(TAG, "Failed to initialize bus.");
        vTaskDelay(1000 / portTICK_PERIOD_MS);
        return;
    }

    ESP_LOGI(TAG, "done spi_bus_initialize");
    vTaskDelay(1000 / portTICK_PERIOD_MS);

    // This initializes the slot without card detect (CD) and write protect (WP) signals.
    // Modify slot_config.gpio_cd and slot_config.gpio_wp if your board has these signals.
    sdspi_device_config_t slot_config = SDSPI_DEVICE_CONFIG_DEFAULT();
    slot_config.gpio_cs   = PIN_NUM_CS;

    ESP_LOGI(TAG, "goto esp_vfs_fat_sdspi_mount");
    vTaskDelay(1000 / portTICK_PERIOD_MS);

    ret = esp_vfs_fat_sdspi_mount(mount_point, &host, &slot_config, &mount_config, &card);

    ESP_LOGI(TAG, "done esp_vfs_fat_sdspi_mount");
    vTaskDelay(1000 / portTICK_PERIOD_MS);
#endif //USE_SPI_MODE

    if (ret != ESP_OK) {
        if (ret == ESP_FAIL) {
            ESP_LOGE(TAG, "Failed to mount filesystem. "
                "If you want the card to be formatted, set format_if_mount_failed = true.");
        } else {
            ESP_LOGE(TAG, "Failed to initialize the card (%s). "
                "Make sure SD card lines have pull-up resistors in place.", esp_err_to_name(ret));
        }
        return;
    }

    // Card has been initialized, print its properties
    sdmmc_card_print_info(stdout, card);

    // Use POSIX and C standard library functions to work with files.
    // First create a file.
    ESP_LOGI(TAG, "Opening file");
    FILE* f = fopen(MOUNT_POINT"/hello.txt", "w");
    if (f == NULL) {
        ESP_LOGE(TAG, "Failed to open file for writing");
        return;
    }
    fprintf(f, "Hello %s!\n", card->cid.name);
    fclose(f);
    ESP_LOGI(TAG, "File written");

    // Check if destination file exists before renaming
    struct stat st;
    if (stat(MOUNT_POINT"/foo.txt", &st) == 0) {
        // Delete it if it exists
        unlink(MOUNT_POINT"/foo.txt");
    }

    // Rename original file
    ESP_LOGI(TAG, "Renaming file");
    if (rename(MOUNT_POINT"/hello.txt", MOUNT_POINT"/foo.txt") != 0) {
        ESP_LOGE(TAG, "Rename failed");
        return;
    }

    // Open renamed file for reading
    ESP_LOGI(TAG, "Reading file");
    f = fopen(MOUNT_POINT"/foo.txt", "r");
    if (f == NULL) {
        ESP_LOGE(TAG, "Failed to open file for reading");
        return;
    }
    char line[64];
    fgets(line, sizeof(line), f);
    fclose(f);
    // strip newline
    char* pos = strchr(line, '\n');
    if (pos) {
        *pos = '\0';
    }
    ESP_LOGI(TAG, "Read from file: '%s'", line);

    // All done, unmount partition and disable SDMMC or SPI peripheral
    esp_vfs_fat_sdcard_unmount(mount_point, card);
    ESP_LOGI(TAG, "Card unmounted");
#ifdef USE_SPI_MODE
    //deinitialize the bus after all devices are removed
    spi_bus_free(host.slot);
#endif
}`

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, we will look into.

**Comment by chuledeco** [comment]
Hi! Any news? Just to tell that commenting :
`#define USE_SPI_MODE`
and uncommenting:
`slot_config.width = 1;`

it works fine
