### ISSUE TITLE
What is the ADC input voltage of esp32S2? (IDFGH-3524)

### ISSUE THREAD

**Issue by lewisxhe** [espressif/esp-idf#5477]
In the actual test, when the input voltage reaches about 0.85, the adc output value is equal to 8192, which is the maximum value of 13 bits. I want to ask whether this function is still being tested?

**Comment by fuAlex** [comment]
@lewisxhe May be you need to set the attenuation of ADC with API `adc1_config_channel_atten()`

**Comment by lewisxhe** [comment]
Thanks, it seems that my settings are wrong.
