### ISSUE TITLE
[S2] Factory reset pin (IDFGH-3537)

### ISSUE THREAD

**Issue by chegewara** [espressif/esp-idf#5489]
Change factory reset pin range to `0 44`, since esp32 S2 is capable to use that range.
Pins 45 and 46 are excluded as bootstrap pins and pin 46 requires externall pull up anyway.

https://github.com/espressif/esp-idf/blob/master/components/bootloader/Kconfig.projbuild#L103

**Comment by Alvin1Zhang** [comment]
Thanks for raising the feature request.
