### ISSUE TITLE
tcpip_adapter_dhcps_get_status doesn't seem to need an interface parameter.

### ISSUE THREAD

**Issue by nkolban** [espressif/esp-idf#55]
I was studying the tcpip_adapter_dhcps_get_status() method and its first parameter is an interface.  But I don't see that this is needed as the DHCP Server component is only applicable to an access point interface.  If this is the case, might we consider removing the need for an interface parameter?

**Comment by igrr** [comment]
We will also have Ethernet supported through tcpip_adapter component in the future, and there is a use case for having DHCP server on ETH interface.
