### ISSUE TITLE
[TW#12226] SPI master sending wrong data to ILI9341-based display

### ISSUE THREAD

**Issue by inxonic** [espressif/esp-idf#551]
Hi,

my application with an ILI9341-based display is broken when compiled with IDF after e9c372bc2dfec648fd3d06a5f96502b77d07bd58.

It runs without errors but the display doesn't show anything.

This can be reproduced with the spi_master example. I could capture this with an oscilloscope (at 100 kHz): 

Before: This is the [`CF 00 83 30`](https://github.com/espressif/esp-idf/blob/07b61d54f7e502bb12527e4b582de121ffa6fa02/examples/peripherals/spi_master/main/spi_master_example_main.c#L54):
![esp_spi_good](https://cloud.githubusercontent.com/assets/4559942/25560512/3b5d9b3c-2d56-11e7-9914-faa23829f1e7.jpg)

After: This seems to be `CF 00 AD 6E`, don't know where it's coming from:
![esp_spi_bad](https://cloud.githubusercontent.com/assets/4559942/25560511/3290eba8-2d56-11e7-8531-30b33cf58544.jpg)

Kind regards
Daniel

**Comment by negativekelvin** [comment]
Just a theory new spi driver can use DMA for smaller transfers so you may have to be careful where your buffers are placed so DMA can access them.

**Comment by inxonic** [comment]
@negativekelvin your guess is correct. The initialization sequence (`static const ili_init_cmd_t ili_init_cmds`) probably gets placed into DROM. I could make it work again by defining the data as `DRAM_ATTR`.

**Comment by negativekelvin** [comment]
@Spritetm could spi driver check ptr address before deciding to use DMA?
