### ISSUE TITLE
WebSocket transport configurable buffer size. (IDFGH-3566)

### ISSUE THREAD

**Issue by klisevich** [espressif/esp-idf#5513]
Hi!
I'm using MQTT over WebSocket to connect to amazon's endpoint with [SigV4 pre-signed URL](https://docs.aws.amazon.com/general/latest/gr/sigv4_signing.html). This URL contains the secure-token parameter that increases the overall URL size up to 1300 bytes. There is DEFAULT_WS_BUFFER define in transport_ws.c that limits buffer size to 1024 bytes and cutting off my URL.
Is it possible to make configurable the DEFAULT_WS_BUFFER value with Kconfig in order to set buffer size?

**Comment by ESP-Marius** [comment]
Hi @klisevich 

Thanks for the feature request, having this makes sense. There's a MR in our pipeline to add this. 

We'll update and close this issue when it has been merged and pushed to github.
