### ISSUE TITLE
example does not compile with -o2 with target esp32s2 (IDFGH-3581)

### ISSUE THREAD

**Issue by wilhelmw201** [espressif/esp-idf#5525]
###  Problem Description
I get a compile time error when building my code. The same error occurs when compiling the freertos example too.

### Actual Behavior
`
[  7%] Building C object esp-idf/freertos/CMakeFiles/__idf_freertos.dir/tasks.c.obj

/blah/components/freertos/tasks.c: In function 'xTaskCreatePinnedToCore':
/blah/components/freertos/tasks.c:648:30: error: array subscript -1 is below array bounds of 'TCB_t * volatile[1]' {aka 'struct tskTaskControlBlock * volatile[1]'} [-Werror=array-bounds]
  TCB_t *curTCB = pxCurrentTCB[xCoreID];
                  ~~~~~~~~~~~~^~~~~~~~~
/blah/components/freertos/tasks.c: In function 'vTaskPrioritySet':
/blah/components/freertos/tasks.c:648:30: error: array subscript [0, 0] is outside array bounds of 'TCB_t * volatile[1]' {aka 'struct tskTaskControlBlock * volatile[1]'} [-Werror=array-bounds]
  TCB_t *curTCB = pxCurrentTCB[xCoreID];
                  ~~~~~~~~~~~~^~~~~~~~~
/blah/components/freertos/tasks.c: In function 'vTaskResume':
/blah/components/freertos/tasks.c:648:30: error: array subscript [0, 0] is outside array bounds of 'TCB_t * volatile[1]' {aka 'struct tskTaskControlBlock * volatile[1]'} [-Werror=array-bounds]
  TCB_t *curTCB = pxCurrentTCB[xCoreID];
                  ~~~~~~~~~~~~^~~~~~~~~
/blah/components/freertos/tasks.c: In function 'xTaskResumeFromISR':
/blah/components/freertos/tasks.c:648:30: error: array subscript [0, 0] is outside array bounds of 'TCB_t * volatile[1]' {aka 'struct tskTaskControlBlock * volatile[1]'} [-Werror=array-bounds]
  TCB_t *curTCB = pxCurrentTCB[xCoreID];
                  ~~~~~~~~~~~~^~~~~~~~~

....

`


### Steps to reproduce

On branch release4.2 and latest master, the following example:
esp-idf/examples/system/freertos/real_time_stats
with target esp32s2: idf.py set-target esp32s2
compiles with normal configuration, but not with compiler flag -o2 in menuconfig

**Comment by projectgus** [comment]
Hi @wilhelmw201 ,

Thanks for reporting this bug and sorry noone got back to you earlier. We have a fix that should be merged soon.

As this issue is now closed for some reason and another issue has been opened with the same bug report, we'll update the other issue from now on. You can click "Subscribe" on the linked issue to receive notifications from it.

Angus
