### ISSUE TITLE
LEDC not working properly in ESP-IDF v4.1-beta2 while working fine in ESP-IDF v4.0 (IDFGH-3600)

### ISSUE THREAD

**Issue by ISOMAX** [espressif/esp-idf#5543]
i have the feeling when working with LEDC that something is not 100% correct in ESP-IDF v4.1-beta2

i will make Measurements and post them here the next day.

**Comment by Alvin1Zhang** [comment]
@ISOMAX  Thanks for reporting, would you please help share if any updates for the issue? Thanks.

**Comment by ISOMAX** [comment]
Yes, will do measurements about this. 

 

Von: Alvin1Zhang <notifications@github.com> 
Gesendet: Montag, 6. Juli 2020 13:29
An: espressif/esp-idf <esp-idf@noreply.github.com>
Cc: ISOMAX <franz@isomax.tech>; Mention <mention@noreply.github.com>
Betreff: Re: [espressif/esp-idf] LEDC not working properly in ESP-IDF v4.1-beta2 while working fine in ESP-IDF v4.0 (IDFGH-3600) (#5543)

 

@ISOMAX <https://github.com/ISOMAX>  Thanks for reporting, would you please help share if any updates for the issue? Thanks.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, would you please help share if any updates for the issue? Thanks.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close now, feel free to reopen with more details provided, thanks.
