### ISSUE TITLE
esp-idf/examples/provisioning/wifi_prov_mgr/.  demo中的蓝牙信号在android上可以看到 在mac系统中，ios中无法看到信号 (IDFGH-3603)

### ISSUE THREAD

**Issue by coffice12** [espressif/esp-idf#5546]
esp-idf/examples/provisioning/wifi_prov_mgr/.  demo中的蓝牙信号在android上可以看到 在mac系统中，ios中无法看到信号

**Comment by Alvin1Zhang** [comment]
@coffice12 Thanks for reporting. Would you please help provide more details as suggested in the [issue template](https://github.com/espressif/esp-idf/issues/new?assignees=&labels=&template=bug_report.md&title=)? Information like elf, sdk configuration, backtrace, log outputs, commit ID, hardware and etc. would help us debug further. Thanks.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, feel free to reopen and provide details as suggested in the [issue template](https://github.com/espressif/esp-idf/issues/new?assignees=&labels=&template=bug_report.md&title=). Information like elf, sdk configuration, backtrace, log outputs, commit ID, hardware and etc. would help us debug further. Thanks.
