### ISSUE TITLE
Error of mbedtls in IDFv4.1-beta2 (IDFGH-3610)

### ISSUE THREAD

**Issue by ROYMURLI** [espressif/esp-idf#5550]
Hi,
I was working with compiler version 5.2.0 and gcc v 6.4.0 in msys2 and was using IDFv4.1-dev-1086-g93a8603c5. Now I upgraded toolchiain to 8.2.0 and gcc v 9.1.0 in msys2 and using IDFv4.2-beta2. I am getting error in medtls components. Tried to include and exclude various components but not working. Screenshoot of error is:-
![Untitled1](https://user-images.githubusercontent.com/20817125/86729143-c2691180-c04a-11ea-93ef-9e42e43cbabc.png)

Suggest me what should be the changes in menuconfig so that it will run. latest SDK config is:-

[sdkconfig1.txt](https://github.com/espressif/esp-idf/files/4882958/sdkconfig1.txt)

**Comment by mahavirj** [comment]
@ROYMURLI Can you please try enabling `MBEDTLS_ECP_C` from https://github.com/espressif/esp-idf/blob/master/components/mbedtls/Kconfig#L639?

**Comment by ROYMURLI** [comment]
Thanks @mahavirj . It worked.
