### ISSUE TITLE
基于blufidemo移植开发，定时器100us获取io电平有时定时器并不准确 (IDFGH-3612)

### ISSUE THREAD

**Issue by lmz13411274381** [espressif/esp-idf#5552]
基于esp_idfV4.0框架
开发环境windos,
同时开启wifi连接路由器mqtt上下行数据和蓝牙广播数据，定时器100us获取io口电平状态，有时定时器并未是100us进去中断获取io状态，或单独在中断中实现100us输出改变一个io状态，示波器抓取波形，有时3ms才改变状态，请问下这个有什么解决方式？

**Comment by costaud** [comment]
请问是用的是哪个定时器？
如果需要精确的定时，可以使用外设timergroup。并且注册timer中断时，添加IRAM_FLAG标志位。(注意，此时中断回调中调用的函数和变量都必须在iram/dram中）
同时，将timer中断与wifi/bt在不同的CPU核进行初始化和运行。

另外，能否描述一下应用场景，可能有更适合的硬件资源可以是用。

**Comment by lmz13411274381** [comment]
@costaud 一个iorf433解码，和两个io 100us获取一次状态接光电感应判断纸带移动位置
