### ISSUE TITLE
Quick start describes ESP32-S2 has having two cores (IDFGH-3616)

### ISSUE THREAD

**Issue by rgl** [espressif/esp-idf#5556]
The guide at https://docs.espressif.com/projects/esp-idf/en/latest/esp32s2/get-started/ has:

> ESP32-S2 is a system on a chip that integrates the following features:
> Dual high performance cores

But that SoC has a single-core.

Maybe you also wanted to say it has two Ultra Low Power co-processors (ulp-risc-v and ulp-fsm)?

**Comment by krzychb** [comment]
Thank you @rgl, we will fix it.
