### ISSUE TITLE
esp_modem.c empty line check improvement (IDFGH-3627)

### ISSUE THREAD

**Issue by kapitan-u** [espressif/esp-idf#5563]
## Environment

idf v4

## Problem Description

esp_modem.c empty line check

in function  esp_dte_handle_line

 
    /* Skip pure "\r\n" lines */
    if (strlen(line) > 2) {

is passing lines consisting of white space only, which is triggering handle line errors

### Solution

bool isempty(const char *s)
{
  while (*s) {
    if (!isspace(*s))
      return false;
    s++;
  }
  return true;
}

and then in 

esp_dte_handle_line(esp_modem_dte_t *esp_dte)

 
    /* Skip pure white space lines */
    if (!isempty(line)) {

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, we will look into.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting and sorry for slow turnaround, we have a fix under internal reviewing now, and the issue will close automatically once the fix is available on GitHub, thanks.
