### ISSUE TITLE
请问下，什么办法解决wifi联网时老是重启的问题，用稳压电源供电能正常启动。 (IDFGH-3628)

### ISSUE THREAD

**Issue by lmz13411274381** [espressif/esp-idf#5564]
环境
开发套件：[ESP32-s模块
套件版本：idfv4.0
使用的模块或芯片：ESP32
IDF版本（运行git describe --tags以查找它）：
// v3.2-dev-1148-g96cd3b75c
构建系统：[Make | CMake | idf.py]
编译器版本（运行xtensa-esp32-elf-gcc --version找到它）：
v4.0
操作系统：[Windows]
（仅Windows）环境类型：[MSYS2 mingw32 | ESP命令提示符|普通命令提示符| PowerShell]。
使用IDE ？：是（请提供详细信息）]
电源：ldo 1117 或直流稳压电源供电
问题描述
//详细的问题描述在这里。

预期行为
能正常启动不会重启，能否修改什么降低
实际行为
在产品中用1117供电出现wifi联网中出现异常
重现步骤
第1步
开关设备

调试日志
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DOUT, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:6944
ho 0 tail 12 room 4
load:0x40078000,len:14032
load:0x40080400,len:4000
entry 0x400806d8
I (76) boot: Chip Revision: 1
I (76) boot_comm: chip revision: 1, min. bootloader chip revision: 0
I (41) boot: ESP-IDF v4.0-dirty 2nd stage bootloader
I (41) boot: compile time 16:35:51
I (41) boot: Enabling RNG early entropy source...
I (47) boot: SPI Speed      : 40MHz
I (51) boot: SPI Mode       : DOUT
I (55) boot: SPI Flash Size : 4MB
I (59) boot: Partition Table:
I (62) boot: ## Label            Usage          Type ST Offset   Length
I (70) boot:  0 nvs              WiFi data        01 02 00009000 00004000
I (77) boot:  1 otadata          OTA data         01 00 0000d000 00002000
I (85) boot:  2 phy_init         RF data          01 01 0000f000 00001000
I (92) boot:  3 factory          factory app      00 00 00010000 00139000
I (100) boot:  4 ota_0            OTA app          00 10 00150000 00139000
I (107) boot:  5 ota_1            OTA app          00 11 00290000 00139000
I (115) boot: End of partition table
I (119) boot: Defaulting to factory image
I (124) boot_comm: chip revision: 1, min. application chip revision: 0
I (131) esp_image: segment 0: paddr=0x00010020 vaddr=0x3f400020 size=0x2bbac (179116) map
I (206) esp_image: segment 1: paddr=0x0003bbd4 vaddr=0x3ffbdb60 size=0x03a8c ( 14988) load
I (213) esp_image: segment 2: paddr=0x0003f668 vaddr=0x40080000 size=0x00400 (  1024) load
0x40080000: _WindowOverflow4 at D:/MyDrivers/msys32/home/admin/esp-idf-v4.0/components/freertos/xtensa_vectors.S:1778

I (213) esp_image: segment 3: paddr=0x0003fa70 vaddr=0x40080400 size=0x005a0 (  1440) load
I (222) esp_image: segment 4: paddr=0x00040018 vaddr=0x400d0018 size=0xc9d00 (826624) map
0x400d0018: _stext at ??:?

I (537) esp_image: segment 5: paddr=0x00109d20 vaddr=0x400809a0 size=0x1b2b8 (111288) load
I (602) boot: Loaded app from partition at offset 0x10000
I (602) boot: Disabling RNG early entropy source...
I (602) cpu_start: Pro cpu up.
I (606) cpu_start: Application information:
I (611) cpu_start: Project name:     blufi_demo
I (616) cpu_start: App version:      v4.0-dirty
I (621) cpu_start: Compile time:     Jul  8 2020 11:59:24
I (627) cpu_start: ELF file SHA256:  3f550fe1c9c399dd...
I (633) cpu_start: ESP-IDF:          v4.0-dirty
I (638) cpu_start: Starting app cpu, entry point is 0x400812a4
0x400812a4: call_start_cpu1 at D:/MyDrivers/msys32/home/admin/esp-idf-v4.0/components/esp32/cpu_start.c:272

I (624) cpu_start: App cpu up.
I (649) heap_init: Initializing. RAM available for dynamic allocation:
I (656) heap_init: At 3FFAFF10 len 000000F0 (0 KiB): DRAM
I (662) heap_init: At 3FFB6388 len 00001C78 (7 KiB): DRAM
I (668) heap_init: At 3FFB9A20 len 00004108 (16 KiB): DRAM
I (674) heap_init: At 3FFBDB5C len 00000004 (0 KiB): DRAM
I (680) heap_init: At 3FFCCD48 len 000132B8 (76 KiB): DRAM
I (686) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM
I (693) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
I (699) heap_init: At 4009BC58 len 000043A8 (16 KiB): IRAM
I (705) cpu_start: Pro cpu start user code
I (724) spi_flash: detected chip: generic
I (725) spi_flash: flash io: dout
I (725) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.
------- EVENT TIME ---
mydata.rf_data=10
I (810) my_flash: get group_myself_read data OK !
I (810) my_flash: get group_myself_read data : [0] =a3
I (810) my_flash: get group_myself_read data : [1] =75
I (820) my_flash: get group_myself_read data : [2] =d3
I (820) my_flash: get group_myself_read data : [3] =bb
I (830) my_flash: get group_myself_read data : [4] =01
I (830) my_flash: get group_myself_read data : [5] =00
I (840) my_flash: get group_myself_read data : [6] =0b
I (840) my_flash: get group_myself_read data : [7] =0f
I (850) my_flash: get group_myself_read data : [8] =24
I (860) my_flash: get group_myself_read data : [9] =28
E (860) my_rfd: addr=0xa3,0x75,0xd3,0xbb,0x1,0
I (870) gpio: GPIO[14]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0
I (880) gpio: GPIO[27]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0
I (890) gpio: GPIO[16]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0
I (900) gpio: GPIO[17]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0
I (900) gpio: GPIO[4]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0
E (910) my_rfd: addr=0xa3,0x75,0xd3,0xbb,0x1,0
------- EVENT TIME --------
I (930) wifi: wifi driver task: 3ffd53b4, prio:23, stack:3584, core=0
I (930) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE
I (940) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE
I (970) wifi: wifi firmware version: 581f422
I (970) wifi: config NVS flash: enabled
I (970) wifi: config nano formating: disabled
I (970) wifi: Init dynamic tx buffer num: 32
I (970) wifi: Init data frame dynamic rx buffer num: 32
I (980) wifi: Init management frame dynamic rx buffer num: 32
I (980) wifi: Init management short buffer num: 32
I (990) wifi: Init static rx buffer size: 1600
I (990) wifi: Init static rx buffer num: 10
I (1000) wifi: Init dynamic rx buffer num: 32

Brownout detector was triggered

ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DOUT, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:6944
ho 0 tail 12 room 4
load:0x40078000,len:14032
load:0x40080400,len:4000
entry 0x400806d8
I (76) boot: Chip Revision: 1
I (76) boot_comm: chip revision: 1, min. bootloader chip revision: 0
I (41) boot: ESP-IDF v4.0-dirty 2nd stage bootloader
I (41) boot: compile time 16:35:51
I (41) boot: Enabling RNG early entropy source...
I (47) boot: SPI Speed      : 40MHz
I (51) boot: SPI Mode       : DOUT
I (55) boot: SPI Flash Size : 4MB
I (59) boot: Partition Table:
I (62) boot: ## Label            Usage          Type ST Offset   Length
I (70) boot:  0 nvs              WiFi data        01 02 00009000 00004000
I (77) boot:  1 otadata          OTA data         01 00 0000d000 00002000
I (85) boot:  2 phy_init         RF data          01 01 0000f000 00001000
I (92) boot:  3 factory          factory app      00 00 00010000 00139000
I (100) boot:  4 ota_0            OTA app          00 10 00150000 00139000
I (107) boot:  5 ota_1            OTA app          00 11 00290000 00139000
I (115) boot: End of partition table
I (119) boot: Defaulting to factory image
I (124) boot_comm: chip revision: 1, min. application chip revision: 0
I (131) esp_image: segment 0: paddr=0x00010020 vaddr=0x3f400020 size=0x2bbac (179116) map
I (206) esp_image: segment 1: paddr=0x0003bbd4 vaddr=0x3ffbdb60 size=0x03a8c ( 14988) load
I (213) esp_image: segment 2: paddr=0x0003f668 vaddr=0x40080000 size=0x00400 (  1024) load
0x40080000: _WindowOverflow4 at D:/MyDrivers/msys32/home/admin/esp-idf-v4.0/components/freertos/xtensa_vectors.S:1778

I (213) esp_image: segment 3: paddr=0x0003fa70 vaddr=0x40080400 size=0x005a0 (  1440) load
I (222) esp_image: segment 4: paddr=0x00040018 vaddr=0x400d0018 size=0xc9d00 (826624) map
0x400d0018: _stext at ??:?

I (537) esp_image: segment 5: paddr=0x00109d20 vaddr=0x400809a0 size=0x1b2b8 (111288) load
I (602) boot: Loaded app from partition at offset 0x10000
I (602) boot: Disabling RNG early entropy source...
I (602) cpu_start: Pro cpu up.
I (606) cpu_start: Application information:
I (611) cpu_start: Project name:     blufi_demo
I (616) cpu_start: App version:      v4.0-dirty
I (621) cpu_start: Compile time:     Jul  8 2020 11:59:24
I (627) cpu_start: ELF file SHA256:  3f550fe1c9c399dd...
I (633) cpu_start: ESP-IDF:          v4.0-dirty
I (638) cpu_start: Starting app cpu, entry point is 0x400812a4
0x400812a4: call_start_cpu1 at D:/MyDrivers/msys32/home/admin/esp-idf-v4.0/components/esp32/cpu_start.c:272

I (624) cpu_start: App cpu up.
I (649) heap_init: Initializing. RAM available for dynamic allocation:
I (656) heap_init: At 3FFAFF10 len 000000F0 (0 KiB): DRAM
I (662) heap_init: At 3FFB6388 len 00001C78 (7 KiB): DRAM
I (668) heap_init: At 3FFB9A20 len 00004108 (16 KiB): DRAM
I (674) heap_init: At 3FFBDB5C len 00000004 (0 KiB): DRAM
I (680) heap_init: At 3FFCCD48 len 000132B8 (76 KiB): DRAM
I (686) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM
I (693) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
I (699) heap_init: At 4009BC58 len 000043A8 (16 KiB): IRAM
I (705) cpu_start: Pro cpu start user code
I (724) spi_flash: detected chip: generic
I (725) spi_flash: flash io: dout
I (725) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.
------- EVENT TIME ---
mydata.rf_data=10
I (810) my_flash: get group_myself_read data OK !
I (810) my_flash: get group_myself_read data : [0] =a3
I (810) my_flash: get group_myself_read data : [1] =75
I (820) my_flash: get group_myself_read data : [2] =d3
I (820) my_flash: get group_myself_read data : [3] =bb
I (830) my_flash: get group_myself_read data : [4] =01
I (830) my_flash: get group_myself_read data : [5] =00
I (840) my_flash: get group_myself_read data : [6] =0b
I (840) my_flash: get group_myself_read data : [7] =0f
I (850) my_flash: get group_myself_read data : [8] =24
I (860) my_flash: get group_myself_read data : [9] =28
E (860) my_rfd: addr=0xa3,0x75,0xd3,0xbb,0x1,0
I (870) gpio: GPIO[14]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0
I (880) gpio: GPIO[27]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0
I (890) gpio: GPIO[16]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0
I (900) gpio: GPIO[17]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0
I (900) gpio: GPIO[4]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0
E (910) my_rfd: addr=0xa3,0x75,0xd3,0xbb,0x1,0
------- EVENT TIME --------
I (930) wifi: wifi driver task: 3ffd53b4, prio:23, stack:3584, core=0
I (930) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE
I (940) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE
I (970) wifi: wifi firmware version: 581f422
I (970) wifi: config NVS flash: enabled
I (970) wifi: config nano formating: disabled
I (970) wifi: Init dynamic tx buffer num: 32
I (970) wifi: Init data frame dynamic rx buffer num: 32
I (980) wifi: Init management frame dynamic rx buffer num: 32
I (980) wifi: Init management short buffer num: 32
I (990) wifi: Init static rx buffer size: 1600
I (990) wifi: Init static rx buffer num: 10
I (1000) wifi: Init dynamic rx buffer num: 32

Brownout detector was triggered

ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DOUT, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:6944
ho 0 tail 12 room 4
load:0x40078000,len:14032
load:0x40080400,len:4000
entry 0x400806d8
I (76) boot: Chip Revision: 1
I (76) boot_comm: chip revision: 1, min. bootloader chip revision: 0
I (41) boot: ESP-IDF v4.0-dirty 2nd stage bootloader
I (41) boot: compile time 16:35:51
I (41) boot: Enabling RNG early entropy source...
I (47) boot: SPI Speed      : 40MHz
I (51) boot: SPI Mode       : DOUT
I (55) boot: SPI Flash Size : 4MB
I (59) boot: Partition Table:
I (62) boot: ## Label            Usage          Type ST Offset   Length
I (70) boot:  0 nvs              WiFi data        01 02 00009000 00004000
I (77) boot:  1 otadata          OTA data         01 00 0000d000 00002000
I (85) boot:  2 phy_init         RF data          01 01 0000f000 00001000
I (92) boot:  3 factory          factory app      00 00 00010000 00139000
I (100) boot:  4 ota_0            OTA app          00 10 00150000 00139000
I (107) boot:  5 ota_1            OTA app          00 11 00290000 00139000
I (115) boot: End of partition table
I (119) boot: Defaulting to factory image
I (124) boot_comm: chip revision: 1, min. application chip revision: 0
I (131) esp_image: segment 0: paddr=0x00010020 vaddr=0x3f400020 size=0x2bbac (179116) map
I (206) esp_image: segment 1: paddr=0x0003bbd4 vaddr=0x3ffbdb60 size=0x03a8c ( 14988) load
I (213) esp_image: segment 2: paddr=0x0003f668 vaddr=0x40080000 size=0x00400 (  1024) load
0x40080000: _WindowOverflow4 at D:/MyDrivers/msys32/home/admin/esp-idf-v4.0/components/freertos/xtensa_vectors.S:1778

I (213) esp_image: segment 3: paddr=0x0003fa70 vaddr=0x40080400 size=0x005a0 (  1440) load
I (222) esp_image: segment 4: paddr=0x00040018 vaddr=0x400d0018 size=0xc9d00 (826624) map
0x400d0018: _stext at ??:?

I (537) esp_image: segment 5: paddr=0x00109d20 vaddr=0x400809a0 size=0x1b2b8 (111288) load
I (602) boot: Loaded app from partition at offset 0x10000
I (602) boot: Disabling RNG early entropy source...
I (602) cpu_start: Pro cpu up.
I (606) cpu_start: Application information:
I (611) cpu_start: Project name:     blufi_demo
I (616) cpu_start: App version:      v4.0-dirty
I (621) cpu_start: Compile time:     Jul  8 2020 11:59:24
I (627) cpu_start: ELF file SHA256:  3f550fe1c9c399dd...
I (633) cpu_start: ESP-IDF:          v4.0-dirty
I (638) cpu_start: Starting app cpu, entry point is 0x400812a4
0x400812a4: call_start_cpu1 at D:/MyDrivers/msys32/home/admin/esp-idf-v4.0/components/esp32/cpu_start.c:272

I (624) cpu_start: App cpu up.
I (649) heap_init: Initializing. RAM available for dynamic allocation:
I (656) heap_init: At 3FFAFF10 len 000000F0 (0 KiB): DRAM
I (662) heap_init: At 3FFB6388 len 00001C78 (7 KiB): DRAM
I (668) heap_init: At 3FFB9A20 len 00004108 (16 KiB): DRAM
I (674) heap_init: At 3FFBDB5C len 00000004 (0 KiB): DRAM
I (680) heap_init: At 3FFCCD48 len 000132B8 (76 KiB): DRAM
I (686) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM
I (693) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
I (699) heap_init: At 4009BC58 len 000043A8 (16 KiB): IRAM
I (705) cpu_start: Pro cpu start user code
I (724) spi_flash: detected chip: generic
I (725) spi_flash: flash io: dout
I (725) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.
------- EVENT TIME ---
mydata.rf_data=10
I (810) my_flash: get group_myself_read data OK !
I (810) my_flash: get group_myself_read data : [0] =a3
I (810) my_flash: get group_myself_read data : [1] =75
I (820) my_flash: get group_myself_read data : [2] =d3
I (820) my_flash: get group_myself_read data : [3] =bb
I (830) my_flash: get group_myself_read data : [4] =01
I (830) my_flash: get group_myself_read data : [5] =00
I (840) my_flash: get group_myself_read data : [6] =0b
I (840) my_flash: get group_myself_read data : [7] =0f
I (850) my_flash: get group_myself_read data : [8] =24
I (860) my_flash: get group_myself_read data : [9] =28
E (860) my_rfd: addr=0xa3,0x75,0xd3,0xbb,0x1,0
I (870) gpio: GPIO[14]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0
I (880) gpio: GPIO[27]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0
I (890) gpio: GPIO[16]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0
I (900) gpio: GPIO[17]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0
I (900) gpio: GPIO[4]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0
E (910) my_rfd: addr=0xa3,0x75,0xd3,0xbb,0x1,0
------- EVENT TIME --------

Brownout detector was triggered

ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DOUT, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:6944
ho 0 tail 12 room 4
load:0x40078000,len:14032

**Comment by costaud** [comment]
现象来看，是出时候wifi时，供电电压跌落。
请检查LDO的供电能力，和硬件连接。
