### ISSUE TITLE
light sleep mode for ESP32 in MicroPython (IDFGH-3629)

### ISSUE THREAD

**Issue by jonohribar** [espressif/esp-idf#5565]
## Environment

- Module or chip used:  [sparkfun ESP32 Thing]
- IDF version: [v4.0.1]
- Build System:         [micropython]
- Operating System:     [Linux]
- Using an IDE?: [No]
- Power Supply:         [USB|external 3.3V]

## Problem Description

Hi,

I'm trying to use light sleep mode on my ESP32 set up with MicroPython. I followed the steps on "[Getting started with MicroPython on the ESP32](https://docs.micropython.org/en/latest/esp32/tutorial/intro.html)" to set up my board, and according to [the documentation](https://docs.micropython.org/en/latest/library/esp.html), ESP32 running Micropython has no light sleep implementation yet. 

Is there any way to access the esp_light_sleep_start() function that ESP-IDF provides through Micropython, perhaps by wrapping the c++ function and simply calling it? Or perhaps a method to follow the [guide](https://github.com/espressif/esp-idf/issues/947#issuecomment-500312453) outlined in #947, but in Micropython?

**Comment by igrr** [comment]
Hi @jonohribar,
This is a question probably best asked on [Micropython forum](https://forum.micropython.org/) or the [issue tracker](https://github.com/micropython/micropython/issues). Brief look at micropython code suggests that light sleep is implemented in micropython for the ESP32: https://github.com/micropython/micropython/blob/246f3f640dd635f67269bfdbebe23408f77cd2b0/ports/esp32/modmachine.c#L94-L139

Light sleep is mentioned in Micropython docs, see capacitive touch section [in the esp32 quick reference](https://docs.micropython.org/en/latest/esp32/quickref.html#capacitive-touch) and [this part of the API guide](https://docs.micropython.org/en/latest/library/machine.html#machine.lightsleep).
