### ISSUE TITLE
Update ESP32-Ethernet-Kit docs for v1.2 (IDFGH-3637)

### ISSUE THREAD

**Issue by yarrick** [espressif/esp-idf#5572]
**Is your feature request related to a problem? Please describe.**

I got an ESP32-Ethernet-Kit v1.2 board and it is not mentioned in the documentation.

**Describe the solution you'd like**

docs/en/hw-reference/esp32/get-started-ethernet-kit.rst describing the v1.2 board and changes from v1.1.

**Comment by krzychb** [comment]
Hi @yarrick, 

I am sorry for missing documentation for this board. 

Here is the list of differences between V1.2 and V1.1:

1. Correct the silkscreen marking at the function switch. Below is respective note from V1.1 documentation
   ![image](https://user-images.githubusercontent.com/12953787/88158183-01cb5c80-cc0c-11ea-8d2a-73131bb8b741.png)

2. Value of C1, C2, C42, and C43 is changed to 20 pF.
3. Replace ESP32-WROVER-B with ESP32-WROVER-E.

Updated schematic of ESP32-Ethernet-Kit_A_V1.2, is attached below.
[SCH_ESP32-Ethernet-Kit_A_V1.2_20200528.pdf](https://github.com/espressif/esp-idf/files/4959010/SCH_ESP32-Ethernet-Kit_A_V1.2_20200528.pdf)

New documentation will be published soon.

**Comment by krzychb** [comment]
Resolved in a6c18343274e349fc5b18e8b73f439b1ad3adad3. 
Thanks @yarrick !
