### ISSUE TITLE
Esp-idf-v4.0.1 Components directory under the support of Zlib?  (IDFGH-3642)

### ISSUE THREAD

**Issue by snailwft** [espressif/esp-idf#5577]
Hi, Esp-idf-v4.0.1 Components directory under the support of Zlib?

**Comment by nopnop2002** [comment]
There is miniz.h.

https://github.com/espressif/esp-idf/blob/master/components/esp_rom/include/esp32/rom/miniz.h

This is subset of Zlib.

**Comment by snailwft** [comment]
ok, thank you!

**Comment by projectgus** [comment]
Yes, as linked above the miniz support in ROM allows working with zlib formatted data.

For "how do I..." questions of this kind, recommend asking on the https://esp32.com rather than opening an issue here on GitHub.
