### ISSUE TITLE
loss "crypto/aes.h" (IDFGH-3646)

### ISSUE THREAD

**Issue by snailwft** [espressif/esp-idf#5581]
Hi, Why does compiling the application in ESP-IDF-v4-0-1 cause this error?I find the idf compents is under/components/wpa_supplicant/SRC/crypto/aes. H of this file!

/home/share/esp32/esp_light/InfoWaterFall/main/middle/include/divoom.h:141:10: fatal error: crypto/aes.h: No such file or directory
 #include "crypto/aes.h"

**Comment by Alvin1Zhang** [comment]
Thanks for reporting @snailwft . Would you please help provide more details as suggested in the [issue template](https://github.com/espressif/esp-idf/issues/new?assignees=&labels=&template=bug_report.md&title=)? Information like elf, sdk configuration, backtrace, log outputs, commit ID, hardware and etc. would help us debug further. Thanks.

**Comment by snailwft** [comment]
Hi, I have a list of things that you can look at.
文档：2020.7.14 基于esp-idf-v4.0.1编译应用...
链接：http://note.youdao.com/noteshare?id=93fa8a58957dde5e2e6d7cc4f63b1a87&sub=F2ADC47A798A4EF3A3533A7451261246

**Comment by snailwft** [comment]
这个问题我已经解决了，谢谢您的支持。
