### ISSUE TITLE
Firmware for compliance testing (RF) (IDFGH-3654)

### ISSUE THREAD

**Issue by renanr2** [espressif/esp-idf#5589]
Hello everyone!

I'm facing a RF test for my project with ESP32 to get a national standard certification by ANATEL (Brazil).

I need to do a few configurations on my device, for each test.

I read the IDF user guide, but i can't found out a way to set the bluetooth modulation between GFSK and 8-DPSK.

It has a kind of default firmware for compliance testing? Or, a way to set bluetooth modulation by API?

Please help me.

**Comment by renanr2** [comment]
I found it at espressif idf tools.
https://www.espressif.com/sites/default/files/tools/ESP32%26ESP8266_RF_Performance_Test_EN.zip

**Comment by mfalconf** [comment]
Hi @renanfgpascoal, Did the ESPRFTestTool help you with the certification requested by ANATEL?

**Comment by menachg** [comment]
do we have the source for the EspRftestTool firmware?
i need it for rf testing in conjunction with other modules enabled

**Comment by natanael127** [comment]
I have the same issues of @mfalconf and @menachg

**Comment by guilhermep-git** [comment]
I have the same issues to set the different types of modulation for Bluetooth Classic, BLE and Wi-Fi  with EspRFTestTool_v3.6 software. Aparently the software not able to choose modultaion. I need this to get certification of my product by ANATEL.

The Certificate of Conformity for ESP32-WROOM-32D in Brazil (ANATEL) show several modulations.
![ANATEL_ESP32_modulations](https://github.com/espressif/esp-idf/assets/61754977/668fe4e0-5392-466a-8820-f3b12d93bda2)

**Comment by DevxMike** [comment]
Hello,
@guilhermep-git @menachg @natanael127 @mfalconf can you please share some insights regarding this topic?

**Comment by guilhermep-git** [comment]
Hello @DevxMike,
ESP RF Test Tool worked in my case. It was used by certification laboratory with success.
The ESP RF Test Guide was used as reference.

**Comment by DevxMike** [comment]
Hello @guilhermep-git ,
Thank you very much.
