### ISSUE TITLE
开启后运行后，蓝牙配网功能运行，LED的亮起，但有些闪烁不稳定。 (IDFGH-3659)

### ISSUE THREAD

**Issue by dgjeffrey123** [espressif/esp-idf#5594]
## Environment

- Development Kit:      [ESP32-Wrover-Kit|ESP32-DevKitC|ESP32-PICO-Kit|ESP32-LyraT|ESP32-LyraTD-MSC|none]
- Kit version (for WroverKit/PicoKit/DevKitC): [v1|v2|v3|v4]
- Module or chip used:  [ESP32-WROOM-32|ESP32-WROOM-32D|ESP32-WROOM-32U|ESP32-WROVER|ESP32-WROVER-I|ESP32-WROVER-B|ESP32-WROVER-IB|ESP32-SOLO-1|ESP32-PICO-D4|ESP32]
- IDF version (run ``git describe --tags`` to find it):
    // v3.2-dev-1148-g96cd3b75c
- Build System:         [Make|CMake|idf.py]
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it):
    // 1.22.0-80-g6c4433a
- Operating System:     [Windows|Linux|macOS]
- (Windows only) environment type: [MSYS2 mingw32|ESP Command Prompt|Plain Command Prompt|PowerShell].
- Using an IDE?: [No|Yes (please give details)]
- Power Supply:         [USB|external 5V|external 3.3V|Battery]

## Problem Description

//Detailed problem description goes here.
我们在..\esp-idf\examples\bluetooth\bluedroid\ble\blufi 的例子上面创建一个定时器：
extern void Led_Scan(void *arg); //矩阵LED扫描函数
esp_timer_create_args_t fw_timer =

{

.callback = &Led_Scan,// 矩阵LED 灯回调函数

.arg = NULL, //参数

.name = "fw_timer" //定时器名称

};
void app_main(void)
{
....
esp_timer_handle_t fw_timer_handle = 0;

esp_err_t err = esp_timer_create(&fw_timer, &fw_timer_handle);

err = esp_timer_start_periodic(fw_timer_handle, 500);// 500us

if(err == ESP_OK)

{
printf("fw timer cteate and start ok!\r\n");
/* 创建一个开关检测任务 ,负责用户任务*/
xTaskCreate(motor_task, "motor_task", 1024 *3, NULL, 3, NULL);// 

}
....
}

 uint8_t led_data[2][6] ={ 0 };  // 全局变量设置LED 初始状态
//矩阵LED控制函数 ,原理简图
/* LED0 LED1 LED2 LED3 LED4 LED5
V1
V0
*/
void Led_Scan(void *arg)
{
uint8_t colNum = 0;
uint16_t i = 0;
for (i = 0; i < ROW_MAX_NUM; i++) //reset row
gpio_set_level(ROW_SCAN_TAB[rowNum], 0);  //   复位 V0  V1
ets_delay_us(35);
rowNum++;
if (rowNum >= ROW_MAX_NUM) //scan row
{
rowNum = 0;
}
gpio_set_level(ROW_SCAN_TAB[rowNum], 1);

for (colNum = 0; colNum < COL_MAX_NUM; colNum++)      //open col
{
	if (led_data[rowNum][colNum] != 0)
	{
		gpio_set_level(COL_SCAN_TAB[colNum], 1);  //LED 设置高，亮

	}
	else
	{
		gpio_set_level(COL_SCAN_TAB[colNum], 0);//LED 设置低，灭
	}
}
}

开启后运行后，蓝牙配网功能运行，LED的亮起，但有些闪烁不稳定。

**Comment by jack0c** [comment]
我觉得主要原因是Wi-Fi/BLE代码优先级比较高，导致LED控制代码时间不稳定。但是如果把 LED 控制代码的优先级提高，可能会导致其他任务无法跑。建议做以下方面的尝试：1. 提高 LED 控制的优先级 2. 使用timer 驱动 LED 变化 3. 通过一些方法使timer间隔不会太大，如改用 LEDC 控制灯

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to short of feedback, feel free to reopen with more updates.
