### ISSUE TITLE
Wrong labels for interrupt names in gpio_wakeup_enable

### ISSUE THREAD

**Issue by nkolban** [espressif/esp-idf#56]
More small stuff.  If we look at the comment on gpio_wakeup_enable found here:

https://github.com/espressif/esp-idf/blob/master/components/driver/include/driver/gpio.h#L345

We see that the choices are GPIO_INTR_LOLEVEL and GPIO_INTR_HILEVEL.  I think these may be the wrong names and are likely to be GPIO_INTR_LOW_LEVEL and GPIO_INTR_HIGH_LEVEL.

**Comment by igrr** [comment]
Fixed in master
