### ISSUE TITLE
Some logs containing __FILE__ are not disabled when NDEBUG is defined. (IDFGH-3709)

### ISSUE THREAD

**Issue by DaividFrank** [espressif/esp-idf#5637]
## Environment

- Development Kit:      ESP32-Wrover-Kit|
- Kit version v4
- Module or chip used:  ESP32-WROOM-32
- IDF version (run ``git describe --tags`` to find it):
   v4.3-dev-472-gcf056a7d0
- Build System:         Make
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it):
    xtensa-esp32-elf-gcc (crosstool-NG esp-2020r2) 8.2.0
- Operating System:     Linux
- Using an IDE?: Yes (Visual Studio Code)
- Power Supply:         USB

## Problem Description

Even after disabling assertions and enabling NDEBUG there are strings in the .bin file containing absolute file paths.

### Expected Behavior

NDEBUG and the specific esp-idf assetion configuartions should make it so no redundant strings, especially not absolute file paths, remain in the binary's strings section.

### Actual Behavior

Some absolute paths still exist in the strings section

### Steps to reproduce

1. make menuconfig -> set COMPILER_OPTIMIZATION_ASSERTION_LEVEL=y and FREERTOS_ASSERT_DISABLE=y
2. make all
3. strings build/$(app_name).bin | grep $(username)

### Code to reproduce this issue

compiling examples/peripherals/i2c/i2c_self_test is one instance.

## Debug Logs

```
daivid@Daivid-Desktop:/mnt/a/Programming/rtos/esp-idf/examples/peripherals/i2c/i2c_self_test$ strings build/i2c-example.bin | grep rtos
/mnt/a/Programming/rtos/esp-idf/components/driver/rtc_io.c
/mnt/a/Programming/rtos/esp-idf/components/driver/i2c.c
```

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, we had a fix under internal reviewing. The issue will be closed automatically once the fix is available on GitHub. Thanks.
