### ISSUE TITLE
Release v4.1 (IDFGH-3716)

### ISSUE THREAD

**Issue by kaizoku-oh** [espressif/esp-idf#5642]
Hi is there some way that we can know the releases timeline and **when the Release v4.1 will be released?**

**Comment by Alvin1Zhang** [comment]
@kaizoku-oh Thanks for reporting and sorry for slow turnaround, IDF v4.1-RC has been released at https://github.com/espressif/esp-idf/releases/tag/v4.1-rc. Thanks.

**Comment by kaizoku-oh** [comment]
Thanks for answering, actually I was referring to the v4.1 **the release** and in the link above it says **pre-release**

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, sorry for slow turnaround, IDF v4.1 final version has been released at https://github.com/espressif/esp-idf/releases/tag/v4.1. Feel free to reopen. Thanks.
