### ISSUE TITLE
Add MQTT_EVENT_ANY = -1 to esp_mqtt_event_id_t enum (IDFGH-3722)

### ISSUE THREAD

**Issue by benas1989** [espressif/esp-idf#5648]
Hello,
i try to register for all mqtt events(esp_mqtt_client_register_event), but always visual studio show error.

<img width="1151" alt="Screenshot 2020-07-26 at 22 53 42" src="https://user-images.githubusercontent.com/6152093/88488052-5ca9de80-cf93-11ea-8d06-3457589f42eb.png">

I added it myself and now it works without problems.

<img width="1170" alt="Screenshot 2020-07-26 at 23 00 31" src="https://user-images.githubusercontent.com/6152093/88488108-db9f1700-cf93-11ea-999b-f6b6cc2050ba.png">

**Comment by david-cermak** [comment]
Hi @benas1989 

Which version of esp-idf or mqtt client are you using? This change has been applied already and referenced to all major IDF releases, please see https://github.com/espressif/esp-mqtt/blob/6bc94add892437d0fd50f26bfabe78c646648c13/include/mqtt_client.h#L40

**Comment by benas1989** [comment]
I don’t remember exactly. I downloaded yesterday through a visual studio add-on. Probably 4.0.1 but I'll see later in the evening

**Comment by benas1989** [comment]
esp-idf-v4.0.1

**Comment by benas1989** [comment]
I feel like something is wrong with the visual studio add-on. Because it shows that it is installing version 4.01 but this update is not available. I copied straight from github and everything is fine now

**Comment by brianignacio5** [comment]
Hi @benas1989  when you visual studio add-on, do you mean our [ESP-IDF extension for Visual Studio Code](https://github.com/espressif/vscode-esp-idf-extension) ? If that's so then can you please share with us some steps to reproduce this behavior by posting an issue there or just describing it to us in the [spectrum chat](https://spectrum.chat/espidf-vsc?tab=posts) ?

**Comment by benas1989** [comment]
Hi,
I think here is the problem that installs version 4.1. I can't choose version 4.2. They are not on the list. :)
<img width="982" alt="Screenshot 2020-07-31 at 20 29 17" src="https://user-images.githubusercontent.com/6152093/89061473-6e153100-d36d-11ea-91d5-9713a142bae1.png">

**Comment by brianignacio5** [comment]
v4.2 is the one corresponding to master (development branch)

**Comment by brianignacio5** [comment]
Can we close this @benas1989  ?

**Comment by benas1989** [comment]
Yes

**Comment by Alvin1Zhang** [comment]
Thanks for sharing updates, feel free to reopen.
