### ISSUE TITLE
[TW#12273] missing c file to header spiram.h for enable_spi_sram()

### ISSUE THREAD

**Issue by ESP32DE** [espressif/esp-idf#565]
hi guys

https://github.com/espressif/esp-idf/blob/02fdf8271de3a6db2ab9d4d6f023c160c84ebdbe/components/esp32/heap_alloc_caps.c#L243

[spiram.h](https://github.com/espressif/esp-idf/blob/02fdf8271de3a6db2ab9d4d6f023c160c84ebdbe/components/esp32/spiram.h) is here, but the c file / lib is missed or can not be found.

thanks
best wishes
rudi ;-)

**Comment by Spritetm** [comment]
Yes, we're aware of this. At the moment, the code to use spiram as memory lives in a separate branch; we have not yet gotten around to merging it yet. (Because of workarounds we need to do, the change is actually pretty significant, including toolchain changes)
