### ISSUE TITLE
I want to configure wifi with Bluetooth (IDFGH-3727)

### ISSUE THREAD

**Issue by snailwft** [espressif/esp-idf#5651]
Hello, I want to configure wifi with Bluetooth, which example is the best for me.

**Comment by laukik-hase** [comment]
You can use the new provisioning example on the master  [ESP-IDF Provisioning Example](https://www.github.com/espressif/esp-idf/tree/master/examples%2Fprovisioning%2Fwifi_prov_mgr) or the legacy BLE provisioning.

**Comment by Alvin1Zhang** [comment]
@laukik-hase Thanks for the notes. @snailwft Thanks for reporting,  questions about ESP-IDF (that aren't reporting an issue or a missing feature) are best asked over at https://esp32.com forum. Will close now, please help raise a post on forum. Thanks.
