### ISSUE TITLE
调用esp_bt_gap_read_rssi_delta,没有事件 ESP_BT_GAP_READ_RSSI_DELTA_EVT

### ISSUE THREAD

**Issue by janky22** [espressif/esp-idf#5660]
我的开发板: ESP32_DevKitc_v4
SDK: idf-v4.0.1

我是用 a2dp_sink 例程修改的。
在回调 bt_app_gap_cb 添加了   
case ESP_BT_GAP_DISC_RES_EVT: { 
        update_device_info(param);
        break;
    }
。。
开一个定时器，5s,10s,20的间隔都试过。。连接上之后定时调用 esp_bt_gap_read_rssi_delta，可以保证传入的地址是对的，返回值是0。请问是什么问题呢？？  我需要1秒没采样几次RSSI， 做自动连接的同时并且判断靠近/远离。

**Comment by boblane1** [comment]
For now, you can resolve this problem by enabling `Component config/Bluetooth/Bluedroid Options/Bluetooth Low Energy` in menuconfig. The root cause of this problem is the wrong use of macro `BLE_INCLUDED`, and we will fix this bug as soon as possible. Thanks for your issue.
