### ISSUE TITLE
UDP Client example issue. (IDFGH-3743)

### ISSUE THREAD

**Issue by nvannote** [espressif/esp-idf#5663]
## Environment

ESP-IDF UDP client example.

## Problem Description

Typo / Bug

File: esp-idf/examples/protocols/sockets/udp_client/main/udp_client.c
Line: 87

The existing code has the following declaration.

```c
struct sockaddr_in source_addr; // Large enough for both IPv4 or IPv6
```

Judging from the other examples, this was probably intended to be...

```c
struct sockaddr_in6 source_addr; // Large enough for both IPv4 or IPv6
```

In a perfect world, all of the combined IPv4/IPv6 examples should probably be using struct sockaddr_storage for these situations;  But I point this single example out as it is an immediate potential issue.

Best Regards

**Comment by liuzfesp** [comment]
Please @freakyxue help to fix it.

**Comment by freakyxue** [comment]
hi @nvannote 
This is really a problem, we should use struct SOCKADDR_ Storage to contain the IPv4 and IPv6 addresses
I will fix this issue later.
