### ISSUE TITLE
MQTT publish causes memory exhaustion if client not connected (IDFGH-3748)

### ISSUE THREAD

**Issue by RazMake** [espressif/esp-idf#5668]
ESP-IDF Version: 4.0.1The code is fairly simple, publish once a minute a (temperature) sensor value to MQTT, with QoS=1.

If the client disconnects (server unavailable, connectivity issues) for some time it looks like outbox grows until it runs out of memory causing problems for the rest of the components. Upon reconnect it looks like the outbox is trimmed, dropping messages older than 30 secs (per mqtt_client.c), freeing all that memory (if it doesn't cause a CoreDump before due to memory exhaustion). Probably the same outbox trimming that happens in connect should happen from time to time in publish/enqueue as well. In my empirical tests I was running out of memory in about 7 hours (obviously varies with payload length, frequency, what other memory is consumed).
 
Also, maybe offer a configuration value to limit outbox usage to no more than X% of memory. Or a number of entries, something that does not allow it to grow unbounded.

**Comment by ESP-Marius** [comment]
Hi , @RazMake,

Thanks for reporting this. I agree, we should definitely do something to prevent. I'll look into it.
