### ISSUE TITLE
ble-gatt-server工程，也就是BLE有连接输入密码配对这一步的说法吗？ (IDFGH-3758)

### ISSUE THREAD

**Issue by iot1688** [espressif/esp-idf#5678]
你好，
ESP32 4.0 SDK版本，
BLE 连接这块，有需要输入密码配对这个说法吗?

**Comment by WCCWCC** [comment]
Hi, @iot1688 
安全加密:
传递加密:

**Comment by WCCWCC** [comment]
Hi，@iot1688

传统配对:
       Just Works
       Passkey Entry
       Out of band

安全配对:
       Just Works
       Numeric Comparison 
       Passkey Entry
       Out of Band

是否需要输入密码配对，主要在于你选择的配对的方式。

**Comment by Alvin1Zhang** [comment]
Thanks for reporting. Feel free to reopen, and for "How" questions and third party issues, please help raise a post on forum at https://esp32.com, thanks.
