### ISSUE TITLE
iperf example bug: SO_REUSEADDR set to uninitialized values. (IDFGH-3761)

### ISSUE THREAD

**Issue by prwang** [espressif/esp-idf#5681]
https://github.com/espressif/esp-idf/blob/fdab15dc76a3464ed10ce03e9b9cf1a5cd2aa0d1/examples/bluetooth/esp_ble_mesh/ble_mesh_wifi_coexist/components/iperf/iperf.c#L131

https://github.com/espressif/esp-idf/blob/fdab15dc76a3464ed10ce03e9b9cf1a5cd2aa0d1/examples/wifi/iperf/components/iperf/iperf.c#L266

and 6 more positions ({BLE, WIFI} x {TCP, UDP} x {Server, Client})

SO_REUSEADDR is a flag-type socket option that should be set with an int of nonzero=true or zero=false.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, sorry for slow turnaround, fix is available at https://github.com/espressif/esp-idf/commit/1abf5c861d1152dd800676f1aa9e3de3ddd6a92a, feel free to reopen.
