### ISSUE TITLE
unnamed prototyped parameters not allowed when body is present (IDFGH-3765)

### ISSUE THREAD

**Issue by benas1989** [espressif/esp-idf#5685]
## Environment

Development Kit:ESP32-Wrover-Kit
Kit version DevKitC
Module or chip used:ESP32-WROVER-B
IDF version: 4.2
Build System: idf.py
Compiler version xtensa-esp32-elf-gcc (crosstool-NG esp-2020r2) 8.2.0
Operating System: macOS
Using an IDE?: Visual studio code
Power Supply: USB

## Problem Description

I try to write function to do write i2c registers.I get error:
unnamed prototyped parameters not allowed when body is present

When I change the name of the variable register no longer indicates an error.
Is the word register reserved in esp-id or c?

### Code to reproduce this issue

```cpp
// the code should be wrapped in the ```cpp tag so that it will be displayed better.
#include "esp_log.h"

esp_err_t i2c_write(uint8_t address, uint8_t register, uint8_t data)
{
    return ESP_OK;   
}
```
<img width="816" alt="Screenshot 2020-08-02 at 19 23 14" src="https://user-images.githubusercontent.com/6152093/89127604-5c5f9500-d4f7-11ea-9029-1a8319e6e122.png">

**Comment by igrr** [comment]
> Is the word register reserved in esp-id or c?

You are right, `register` is a keyword in C language: https://en.cppreference.com/w/c/keyword/register.

**Comment by Alvin1Zhang** [comment]
@benas1989 Thanks for reporting, would you please help check whether your issue has been resolved? Thanks.
