### ISSUE TITLE
"esp_http_server" "ping/pong", "wss", "ALL connected client access" and "server to server communication" support [Feature Requests] (IDFGH-3766)

### ISSUE THREAD

**Issue by baldhead69** [espressif/esp-idf#5686]
Hi,

PING/PONG and Heart Beat support [Feature Request]:

I am trying to implement a websocket server using the esp-idf component "esp_http_server".

I can send and receive from my websockets clients messages of type HTTPD_WS_TYPE_TEXT, all works ok.

When i try to send a reply with a ping frame from server to client using type "HTTPD_WS_TYPE_PING", the client Pong answer
to server and the server has an error: 

***************************************************************************************************************************************
Test one: On javascript running in a chrome browser ( by my searchs the JavaScript websocket api automatically replies with a pong the received pings).

W (40157) httpd_ws: httpd_ws_recv_frame: WS frame is not properly masked.
E (40157) WS_Server: httpd_ws_recv_frame failed with 259
Close socket.

***************************************************************************************************************************************
Test two: On Android studio app using okhttp library(okhttp:4.8.0).

Packet Final Frame = true
Packet type: UNKNOWN
Got packet with message: ar<EBe) T-t����������������������������������������������������������������
Packet lenght: 97

W (78846) httpd_ws: httpd_ws_recv_frame: WS frame is not properly masked.
E (78847) WS_Server: httpd_ws_recv_frame failed with 259
Close socket.

P.S. The packet frame and message are not equal in each new request/answer.

****************************************************************************************************************************************

I want to implement a heart beat algorithm with all the clients connected with the server, but if "esp_http_server" providing support would be nice.
The library supports must provide an interface to application or be public so that the application can consult and perhaps also manage, ie: i would not like the lib to manage completely alone (disconnect the client that does not respond to a ping with a pong). Or the application can set timeout, and the number of ping(s) without answer from client before the server disconnect the client, among other settings.
Or the library should manage disconnections alone due to lack of client ping(pong) response, and warn the server application ??
Needs to be discussed !!!!!

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
Access to all connected clients support [Feature Request]:

I would like to have access to all clients connected to the server(websocket client list), so i can send a message to all clients, without necessarily having a client request.

If there was a way to identify each client it would also be interesting(by name or by session ????).

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
WSS support [Feature Request]:

I would like WSS feature for obvious security reasons.

I believe that it may not be so difficult to implement since there is a esp idf component called HTTPS server, but i am not sure.

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
Server to server communication support [Feature Request]:

I would like to communicate between 2 websockets server.

One websocket server in a local network and one "big" websocket server in the cloud.

The local websocket server would have, for example, 5 clients, and would communicate with the cloud websocket server sporadically at first.
In a server to server communication i think that one or the other server could start the communication. 

Ping/pong support to use "heart beat" here too.

I don't know if this would be possible or if I would need to use another strategy.

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
**Additional context**

Add any other context or screenshots about the feature request here:
https://github.com/espressif/esp-idf/issues/5405
https://github.com/espressif/esp-idf/issues/5406
https://github.com/espressif/esp-idf/issues/5602

My esp idf installed version:  v4.2-dev-1235-g71dc5eb27

Thank's.

**Comment by Alvin1Zhang** [comment]
Thanks for raising this feature request.
