### ISSUE TITLE
怎么用esp32读取json大文件 (IDFGH-3796)

### ISSUE THREAD

**Issue by xpdrycry** [espressif/esp-idf#5712]
esp32没有提供数据库读写的例子，最近有个大文件，无法一次性读出，请问，怎么读取，json中一部分json数组。然后修改完了以后，在写入进去？

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, for "how" questions and third party issues, suggest you could raise a post on our forum at https://esp32.com, will close this ticket now. Thanks.
