### ISSUE TITLE
,

### ISSUE THREAD

**Issue by jarus0** [espressif/esp-idf#5726]

**Comment by ESP-iPENCIL** [comment]
esp_mesh_send does not support Fragmentation. One packet size is limited to MESH_MTU( defined in ./esp-idf/components/esp32/include/esp_mesh.h).
You may need to fragment and reassemble the application data by yourself. Sorry for the convinent.

**Comment by jarus0** [comment]
thanks, problem solved

**Comment by fira-code** [comment]
@jarus0 hey, I'm curious to know how you dealt with the fragmentation issue.
I'm working on it and facing memory issues so if you can share informations on how you did it, it'll be very useful.
thx

**Comment by jarus0** [comment]
So here you have 2 options.( Both working fine)

Option 1 
Switch "esp mesh idf" to "mdf"

Option 2 
Write you own fragments feature.
- Sender first send size of data with CRC.
- Receiver will Merge & verified CRC.
- I also written quene and message identify code so receiver can handle multiple receiving at same time.
