### ISSUE TITLE
undefined reference to xQueueGenericCreateStatic (IDFGH-3832)

### ISSUE THREAD

**Issue by kayleejacob1** [espressif/esp-idf#5741]
I am using the latest IDF in Visual Studio with visual micro 

I have set 
#define configSUPPORT_STATIC_ALLOCATION 1
in FreeRTOSconfig.h

I am using this so that I can allocate memory to the PSRAM.

Code below
TaskHandle_t loopi2cread;
QueueHandle_t readi2cdata;
StaticQueue_t xQueuereadi2cBuffer;
 uint8_t* powerque = (uint8_t*)ps_calloc(2, sizeof(powerdata));
 readi2cdata = xQueueCreateStatic(1, sizeof(powerdata), powerque,&xQueuereadi2cBuffer);

**Comment by Alvin1Zhang** [comment]
@kayleejacob1 Thanks for reporting. Would you please help provide more details as suggested in the [issue template](https://github.com/espressif/esp-idf/issues/new?assignees=&labels=&template=bug_report.md&title=)? Information like elf, sdk configuration, backtrace, log outputs, commit ID, hardware and etc. would help us debug further. Thanks.

**Comment by kayleejacob1** [comment]
I have discovered through more research that I have to recompile idf for
arduino.  But I am having issues doing that in windows I have followed all
steps but seems that it does not save the file anywhere

**Comment by Alvin1Zhang** [comment]
Same with post https://esp32.com/viewtopic.php?f=13&p=63992#p63992

**Comment by kayleejacob1** [comment]
yes that is me

**Comment by Alvin1Zhang** [comment]
@kayleejacob1 Thanks for reporting, there is already a reply in the [post](https://esp32.com/viewtopic.php?f=13&p=63992#p63992), will close this ticket and let us track there. Thanks.
