### ISSUE TITLE
Following Flash Encryption example throws an error (IDFGH-3833)

### ISSUE THREAD

**Issue by achraf-boussaada** [espressif/esp-idf#5742]
## Environment

- Development Kit:    ESP32-DevKitC
- Kit version (DevKitC): [v1|v2|v3|v4] - I'm not sure about the version
- Module or chip used:  ESP32-WROOM-32
- IDF version : ESP-IDF v4.3-dev-771-gc77c4ccf6
- Build System:         idf.py
- Compiler version : (crosstool-NG esp-2020r2) 8.2.0
- Operating System:    Linux
- (Windows only) environment type: [MSYS2 mingw32|ESP Command Prompt|Plain Command Prompt|PowerShell].
- Using an IDE?: yes, visual code studio
- Power Supply:        USB

## Problem Description

I tried to test the following flash encryption [example](https://github.com/espressif/esp-idf/tree/master/examples/security/flash_encryption#configure-the-project) and followed the instructions in README.
When I ran `idf.py flash monitor` for the first time I didn't get the expected result in the README, but I got the following error:

```
rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
flash read err, 1000
ets_main.c 371 
ets Jun  8 2016 00:22:57

rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
flash read err, 1000
ets_main.c 371 
ets Jun  8 2016 00:22:57

rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
flash read err, 1000
ets_main.c 371 
ets Jun  8 2016 00:22:57

rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
flash read err, 1000
ets_main.c 371 
ets Jun  8 2016 00:22:57

rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
flash read err, 1000
ets_main.c 371 
ets Jun  8 2016 00:22:57
```
and it keeps going like that until I manually stop it. Using `espefuse.py summary` `FLASH_CRYPT_CNT` has 1 as value, and the first BLK1 contains the encryption key. That means the configuration was done correctly. 
I can't seem to find where the problem is, since the example and the configurations were straightforward

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, we will look into.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting and updates, feel free to reopen if the issue still happens. Thanks.
