### ISSUE TITLE
ZipKey as a possible option for Wi-Fi configuration (IDFGH-3842)

### ISSUE THREAD

**Issue by gc-ow3** [espressif/esp-idf#5748]
ZipKey is a potential optional component you may wish to consider for the IDF.

The company Cirrent is promoting their method for Wi-Fi configuration that can make configuration of Wi-Fi devices easier for end-users. They claim some RTOS providers have incorporated their device agent into their SDKs as an optional feature.

Cons:
1. This will not be free to implement or deploy - it relies on a server infrastructure provided by Cirrent and "hot spots" enabled by partner Wi-Fi modem providers such as XFinity.
2. Not 100 percent coverage. Cirrent claims currently about 50 percent coverage in the USA. They are probably working on expanding coverage. SoftAP / BLE configuration will still need to be available as a fallback.
3. Changes to back-end processing and production process would be required

Pros:
The consumer experience should be easier for those within coverage areas.

Here they discuss the effort required to implement the ZipKey configuration method.
https://blog.cirrent.com/scoping-the-engineering-effort-to-zipkey-enable-a-connected-product

**Comment by jack0c** [comment]
Sorry, Have discussed with Marketing team, still have no plan about this.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, feel free to reopen.
