### ISSUE TITLE
pppos_client example failed to connect to MQTT broker through BG96 (DCE) (IDFGH-3848)

### ISSUE THREAD

**Issue by ganeshkumarsw** [espressif/esp-idf#5754]
## Environment

Development Kit: ESP32 WROOM 32 Module
Module or chip used: [ESP32-WROOM-32]
IDF version (idf.py --version): ESP-IDF v4.1
Build System: [idf.py]
Compiler version (run xtensa-esp32-elf-gcc --version to find it): xtensa-esp32-elf-gcc (crosstool-NG esp-2020r2) 8.2.0
Operating System: [Windows]
(Windows only) environment type: [ESP Command Prompt].
Using an IDE?: [NO]
Power Supply: [external 3.3V]

## Problem description 

"connection reset by peer" when trying to connect with an MQTT broker.

## Monitor Log

I (31) boot: ESP-IDF v4.1-dirty 2nd stage bootloader
I (31) boot: compile time 08:41:42
I (31) boot: chip revision: 1
I (40) boot.esp32: SPI Speed      : 40MHz
I (40) boot.esp32: SPI Mode       : DIO
I (40) boot.esp32: SPI Flash Size : 4MB
I (41) boot: Enabling RNG early entropy source...
I (42) boot: Partition Table:
I (43) boot: ## Label            Usage          Type ST Offset   Length
I (45) boot:  0 nvs              WiFi data        01 02 00009000 00006000
I (47) boot:  1 phy_init         RF data          01 01 0000f000 00001000
I (49) boot:  2 factory          factory app      00 00 00010000 00100000
I (50) boot: End of partition table
I (52) esp_image: segment 0: paddr=0x00010020 vaddr=0x3f400020 size=0x13748 ( 79688) map
I (84) esp_image: segment 1: paddr=0x00023770 vaddr=0x3ffb0000 size=0x021d0 (  8656) load
I (88) esp_image: segment 2: paddr=0x00025948 vaddr=0x40080000 size=0x00404 (  1028) load
I (89) esp_image: segment 3: paddr=0x00025d54 vaddr=0x40080404 size=0x0a2c4 ( 41668) load
I (108) esp_image: segment 4: paddr=0x00030020 vaddr=0x400d0020 size=0x49920 (301344) map
I (223) esp_image: segment 5: paddr=0x00079948 vaddr=0x4008a6c8 size=0x00bec (  3052) load
I (231) boot: Loaded app from partition at offset 0x10000
I (231) boot: Disabling RNG early entropy source...
I (231) cpu_start: Pro cpu up.
I (232) cpu_start: Application information:
I (233) cpu_start: Project name:     pppos_client
I (234) cpu_start: App version:      v4.1-dirty
I (236) cpu_start: Compile time:     Aug 18 2020 15:45:11
I (237) cpu_start: ELF file SHA256:  ebf2524e4b47e2ab...
I (239) cpu_start: ESP-IDF:          v4.1-dirty
I (240) cpu_start: Starting app cpu, entry point is 0x400812dc
I (226) cpu_start: App cpu up.
I (243) heap_init: Initializing. RAM available for dynamic allocation:
I (244) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM
I (246) heap_init: At 3FFB3B80 len 0002C480 (177 KiB): DRAM
I (247) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM
I (249) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
I (251) heap_init: At 4008B2B4 len 00014D4C (83 KiB): IRAM
I (252) cpu_start: Pro cpu start user code
I (263) spi_flash: detected chip: generic
I (263) spi_flash: flash io: dio
I (272) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.
ppp phase changed[1]: phase=0
I (276) uart: queue free spaces: 30
E (426) esp-modem: esp_dte_handle_line(85): DTE has not yet bind with DCE
E (476) esp-modem: esp_dte_handle_line(85): DTE has not yet bind with DCE
I (4676) pppos_example: Module: BG96
I (4676) pppos_example: Operator: **Valid Operator**
I (4676) pppos_example: IMEI: **Valid IMEI**
I (4676) pppos_example: IMSI: **Valid IMSI**
I (4876) pppos_example: rssi: 15, ber: 99
I (5076) pppos_example: Battery voltage: 3639 mV
I (5276) pppos_example: Modem PPP Started
ppp_connect[1]: holdoff=0
ppp phase changed[1]: phase=3
pppos_connect: unit 1: connecting
ppp_start[1]
ppp phase changed[1]: phase=6
pppos_send_config[1]: out_accm=FF FF FF FF
ppp_send_config[1]
pppos_recv_config[1]: in_accm=FF FF FF FF
ppp_recv_config[1]
ppp: auth protocols: PAP=1 CHAP=0 CHAP_MD5=0 CHAP_MS=0 CHAP_MS2=0
pppos_write[1]: len=24
ppp_start[1]: finished
pppos_input[1]: got 98 bytes
pppos_write[1]: len=12
pppos_input[1]: got 51 bytes
pppos_write[1]: len=28
netif_set_mtu[1]: mtu=1500
pppos_send_config[1]: out_accm=0 0 0 0
ppp_send_config[1]
pppos_recv_config[1]: in_accm=0 0 0 0
ppp_recv_config[1]
ppp phase changed[1]: phase=7
pppos_write[1]: len=24
pppos_input[1]: got 32 bytes
PAP authentication succeeded
ppp phase changed[1]: phase=9
ccp_set[1]: is_open=1, is_up=0, receive_method=0, transmit_method=0
pppos_write[1]: len=32
pppos_input[1]: got 34 bytes
pppos_write[1]: len=32
pppos_input[1]: got 34 bytes
pppos_write[1]: len=32
pppos_input[1]: got 34 bytes
pppos_write[1]: len=32
pppos_input[1]: got 26 bytes
pppos_write[1]: len=14
pppos_write[1]: len=26
pppos_input[1]: got 38 bytes
pppos_write[1]: len=8
pppos_write[1]: len=26
pppos_input[1]: got 28 bytes
Could not determine remote IP address: defaulting to 10.64.64.64
sifvjcomp[1]: VJ compress enable=0 slot=0 max slot=0
sifup[1]: err_code=0
I (8796) esp-netif_lwip-ppp: Connected
I (8796) esp-netif_lwip-ppp: Name Server1: **Valid Addr**
I (8796) esp-netif_lwip-ppp: Name Server2: **Valid Addr**
I (8796) pppos_example: Modem Connect to PPP Server
I (8796) pppos_example: ~~~~~~~~~~~~~~
I (8796) pppos_example: IP          : **Valid IP**
I (8796) pppos_example: Netmask     : 255.255.255.255
I (8806) pppos_example: Gateway     : 10.64.64.64
local  IP address **Valid IP**
I (8806) pppos_example: Name Server1: **Valid Addr**
remote IP address 10.64.64.64
I (8806) pppos_example: Name Server2: **Valid IP**
primary   DNS address **Valid DNS Addr**
I (8806) pppos_example: ~~~~~~~~~~~~~~
secondary DNS address **Valid DNS Addr**
I (8806) pppos_example: GOT ip event!!!
ppp phase changed[1]: phase=10
I (11806) system_api: Base MAC address is not set, read default base MAC address from BLK0 of EFUSE
I (11806) pppos_example: MQTT other event id: 7
pppos_netif_output[1]: proto=0x21, len = 63
pppos_netif_output[1]: proto=0x21, len = 63
pppos_input[1]: got 100 bytes
ppp_input[1]: ip in pbuf len=95
pppos_netif_output[1]: proto=0x21, len = 44
pppos_input[1]: got 100 bytes
ppp_input[1]: ip in pbuf len=95
pppos_netif_output[1]: proto=0x21, len = 56
pppos_input[1]: got 49 bytes
ppp_input[1]: ip in pbuf len=44
pppos_netif_output[1]: proto=0x21, len = 40
pppos_netif_output[1]: proto=0x21, len = 66
pppos_input[1]: got 45 bytes
ppp_input[1]: ip in pbuf len=40
E (13626) TRANS_TCP: tcp_poll_read select error 104, errno = Connection reset by peer, fd = 54
E (13626) MQTT_CLIENT: mqtt_message_receive: transport_read() error: errno=0
E (13626) MQTT_CLIENT: esp_mqtt_connect: mqtt_message_receive() returned -1
E (13626) MQTT_CLIENT: MQTT connect failed
I (13626) pppos_example: MQTT_EVENT_DISCONNECTED
I (23636) pppos_example: MQTT other event id: 7
pppos_netif_output[1]: proto=0x21, len = 44
pppos_input[1]: got 49 bytes
ppp_input[1]: ip in pbuf len=44
pppos_netif_output[1]: proto=0x21, len = 40
pppos_netif_output[1]: proto=0x21, len = 66
pppos_input[1]: got 45 bytes
ppp_input[1]: ip in pbuf len=40
E (24596) TRANS_TCP: tcp_poll_read select error 104, errno = Connection reset by peer, fd = 54
E (24596) MQTT_CLIENT: mqtt_message_receive: transport_read() error: errno=0
E (24596) MQTT_CLIENT: esp_mqtt_connect: mqtt_message_receive() returned -1
E (24596) MQTT_CLIENT: MQTT connect failed
I (24596) pppos_example: MQTT_EVENT_DISCONNECTED
I (39596) pppos_example: MQTT other event id: 7
pppos_netif_output[1]: proto=0x21, len = 44
pppos_input[1]: got 49 bytes
ppp_input[1]: ip in pbuf len=44
pppos_netif_output[1]: proto=0x21, len = 40
pppos_netif_output[1]: proto=0x21, len = 66
pppos_input[1]: got 45 bytes
ppp_input[1]: ip in pbuf len=40
E (40566) TRANS_TCP: tcp_poll_read select error 104, errno = Connection reset by peer, fd = 54
E (40566) MQTT_CLIENT: mqtt_message_receive: transport_read() error: errno=0
E (40566) MQTT_CLIENT: esp_mqtt_connect: mqtt_message_receive() returned -1
E (40566) MQTT_CLIENT: MQTT connect failed
I (40576) pppos_example: MQTT_EVENT_DISCONNECTED
I (55576) pppos_example: MQTT other event id: 7
pppos_netif_output[1]: proto=0x21, len = 44
pppos_input[1]: got 49 bytes
ppp_input[1]: ip in pbuf len=44
pppos_netif_output[1]: proto=0x21, len = 40
pppos_netif_output[1]: proto=0x21, len = 66
pppos_input[1]: got 46 bytes
ppp_input[1]: ip in pbuf len=40
E (56506) TRANS_TCP: tcp_poll_read select error 104, errno = Connection reset by peer, fd = 54
E (56506) MQTT_CLIENT: mqtt_message_receive: transport_read() error: errno=0
E (56506) MQTT_CLIENT: esp_mqtt_connect: mqtt_message_receive() returned -1
E (56516) MQTT_CLIENT: MQTT connect failed
I (56516) pppos_example: MQTT_EVENT_DISCONNECTED
I (71516) pppos_example: MQTT other event id: 7

## Code to reproduce this issue

```c

/* PPPoS Client Example

   This example code is in the Public Domain (or CC0 licensed, at your option.)

   Unless required by applicable law or agreed to in writing, this
   software is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
   CONDITIONS OF ANY KIND, either express or implied.
*/
#include <string.h>
#include "freertos/FreeRTOS.h"
#include "freertos/event_groups.h"
#include "driver/gpio.h"
#include "esp_netif.h"
#include "esp_netif_ppp.h"
#include "mqtt_client.h"
#include "esp_modem.h"
#include "esp_modem_netif.h"
#include "esp_log.h"
#include "sim800.h"
#include "bg96.h"

#define BROKER_URL "mqtt://broker.hivemq.com"

static const char *TAG = "pppos_example";
static EventGroupHandle_t event_group = NULL;
static const int CONNECT_BIT = BIT0;
static const int STOP_BIT = BIT1;
static const int GOT_DATA_BIT = BIT2;

#if CONFIG_EXAMPLE_SEND_MSG
/**
 * @brief This example will also show how to send short message using the infrastructure provided by esp modem library.
 * @note Not all modem support SMG.
 *
 */
static esp_err_t example_default_handle(modem_dce_t *dce, const char *line)
{
    esp_err_t err = ESP_FAIL;
    if (strstr(line, MODEM_RESULT_CODE_SUCCESS)) {
        err = esp_modem_process_command_done(dce, MODEM_STATE_SUCCESS);
    } else if (strstr(line, MODEM_RESULT_CODE_ERROR)) {
        err = esp_modem_process_command_done(dce, MODEM_STATE_FAIL);
    }
    return err;
}

static esp_err_t example_handle_cmgs(modem_dce_t *dce, const char *line)
{
    esp_err_t err = ESP_FAIL;
    if (strstr(line, MODEM_RESULT_CODE_SUCCESS)) {
        err = esp_modem_process_command_done(dce, MODEM_STATE_SUCCESS);
    } else if (strstr(line, MODEM_RESULT_CODE_ERROR)) {
        err = esp_modem_process_command_done(dce, MODEM_STATE_FAIL);
    } else if (!strncmp(line, "+CMGS", strlen("+CMGS"))) {
        err = ESP_OK;
    }
    return err;
}

#define MODEM_SMS_MAX_LENGTH (128)
#define MODEM_COMMAND_TIMEOUT_SMS_MS (120000)
#define MODEM_PROMPT_TIMEOUT_MS (10)

static esp_err_t example_send_message_text(modem_dce_t *dce, const char *phone_num, const char *text)
{
    modem_dte_t *dte = dce->dte;
    dce->handle_line = example_default_handle;
    /* Set text mode */
    if (dte->send_cmd(dte, "AT+CMGF=1\r", MODEM_COMMAND_TIMEOUT_DEFAULT) != ESP_OK) {
        ESP_LOGE(TAG, "send command failed");
        goto err;
    }
    if (dce->state != MODEM_STATE_SUCCESS) {
        ESP_LOGE(TAG, "set message format failed");
        goto err;
    }
    ESP_LOGD(TAG, "set message format ok");
    /* Specify character set */
    dce->handle_line = example_default_handle;
    if (dte->send_cmd(dte, "AT+CSCS=\"GSM\"\r", MODEM_COMMAND_TIMEOUT_DEFAULT) != ESP_OK) {
        ESP_LOGE(TAG, "send command failed");
        goto err;
    }
    if (dce->state != MODEM_STATE_SUCCESS) {
        ESP_LOGE(TAG, "set character set failed");
        goto err;
    }
    ESP_LOGD(TAG, "set character set ok");
    /* send message */
    char command[MODEM_SMS_MAX_LENGTH] = {0};
    int length = snprintf(command, MODEM_SMS_MAX_LENGTH, "AT+CMGS=\"%s\"\r", phone_num);
    /* set phone number and wait for "> " */
    dte->send_wait(dte, command, length, "\r\n> ", MODEM_PROMPT_TIMEOUT_MS);
    /* end with CTRL+Z */
    snprintf(command, MODEM_SMS_MAX_LENGTH, "%s\x1A", text);
    dce->handle_line = example_handle_cmgs;
    if (dte->send_cmd(dte, command, MODEM_COMMAND_TIMEOUT_SMS_MS) != ESP_OK) {
        ESP_LOGE(TAG, "send command failed");
        goto err;
    }
    if (dce->state != MODEM_STATE_SUCCESS) {
        ESP_LOGE(TAG, "send message failed");
        goto err;
    }
    ESP_LOGD(TAG, "send message ok");
    return ESP_OK;
err:
    return ESP_FAIL;
}
#endif

static void modem_event_handler(void *event_handler_arg, esp_event_base_t event_base, int32_t event_id, void *event_data)
{
    switch (event_id) {
    case ESP_MODEM_EVENT_PPP_START:
        ESP_LOGI(TAG, "Modem PPP Started");
        break;
    case ESP_MODEM_EVENT_PPP_STOP:
        ESP_LOGI(TAG, "Modem PPP Stopped");
        xEventGroupSetBits(event_group, STOP_BIT);
        break;
    case ESP_MODEM_EVENT_UNKNOWN:
        ESP_LOGW(TAG, "Unknow line received: %s", (char *)event_data);
        break;
    default:
        break;
    }
}

static esp_err_t mqtt_event_handler(esp_mqtt_event_handle_t event)
{
    esp_mqtt_client_handle_t client = event->client;
    int msg_id;
    switch (event->event_id) {
    case MQTT_EVENT_CONNECTED:
        ESP_LOGI(TAG, "MQTT_EVENT_CONNECTED");
        msg_id = esp_mqtt_client_subscribe(client, "/topic/esp-pppos", 0);
        ESP_LOGI(TAG, "sent subscribe successful, msg_id=%d", msg_id);
        break;
    case MQTT_EVENT_DISCONNECTED:
        ESP_LOGI(TAG, "MQTT_EVENT_DISCONNECTED");
        break;
    case MQTT_EVENT_SUBSCRIBED:
        ESP_LOGI(TAG, "MQTT_EVENT_SUBSCRIBED, msg_id=%d", event->msg_id);
        msg_id = esp_mqtt_client_publish(client, "/topic/esp-pppos", "esp32-pppos", 0, 0, 0);
        ESP_LOGI(TAG, "sent publish successful, msg_id=%d", msg_id);
        break;
    case MQTT_EVENT_UNSUBSCRIBED:
        ESP_LOGI(TAG, "MQTT_EVENT_UNSUBSCRIBED, msg_id=%d", event->msg_id);
        break;
    case MQTT_EVENT_PUBLISHED:
        ESP_LOGI(TAG, "MQTT_EVENT_PUBLISHED, msg_id=%d", event->msg_id);
        break;
    case MQTT_EVENT_DATA:
        ESP_LOGI(TAG, "MQTT_EVENT_DATA");
        printf("TOPIC=%.*s\r\n", event->topic_len, event->topic);
        printf("DATA=%.*s\r\n", event->data_len, event->data);
        xEventGroupSetBits(event_group, GOT_DATA_BIT);
        break;
    case MQTT_EVENT_ERROR:
        ESP_LOGI(TAG, "MQTT_EVENT_ERROR");
        break;
    default:
        ESP_LOGI(TAG, "MQTT other event id: %d", event->event_id);
        break;
    }
    return ESP_OK;
}

static void on_ppp_changed(void *arg, esp_event_base_t event_base,
                        int32_t event_id, void *event_data)
{
    ESP_LOGI(TAG, "PPP state changed event %d", event_id);
    if (event_id == NETIF_PPP_ERRORUSER) {
        /* User interrupted event from esp-netif */
        esp_netif_t *netif = event_data;
        ESP_LOGI(TAG, "User interrupted event from netif:%p", netif);
    }
}


static void on_ip_event(void *arg, esp_event_base_t event_base,
                      int32_t event_id, void *event_data)
{
    ESP_LOGD(TAG, "IP event! %d", event_id);
    if (event_id == IP_EVENT_PPP_GOT_IP) {
        esp_netif_dns_info_t dns_info;

        ip_event_got_ip_t *event = (ip_event_got_ip_t *)event_data;
        esp_netif_t *netif = event->esp_netif;

        ESP_LOGI(TAG, "Modem Connect to PPP Server");
        ESP_LOGI(TAG, "~~~~~~~~~~~~~~");
        ESP_LOGI(TAG, "IP          : " IPSTR, IP2STR(&event->ip_info.ip));
        ESP_LOGI(TAG, "Netmask     : " IPSTR, IP2STR(&event->ip_info.netmask));
        ESP_LOGI(TAG, "Gateway     : " IPSTR, IP2STR(&event->ip_info.gw));
        esp_netif_get_dns_info(netif, 0, &dns_info);
        ESP_LOGI(TAG, "Name Server1: " IPSTR, IP2STR(&dns_info.ip.u_addr.ip4));
        esp_netif_get_dns_info(netif, 1, &dns_info);
        ESP_LOGI(TAG, "Name Server2: " IPSTR, IP2STR(&dns_info.ip.u_addr.ip4));
        ESP_LOGI(TAG, "~~~~~~~~~~~~~~");
        xEventGroupSetBits(event_group, CONNECT_BIT);

        ESP_LOGI(TAG, "GOT ip event!!!");
    } else if (event_id == IP_EVENT_PPP_LOST_IP) {
        ESP_LOGI(TAG, "Modem Disconnect from PPP Server");
    } else if (event_id == IP_EVENT_GOT_IP6) {
        ESP_LOGI(TAG, "GOT IPv6 event!");

        ip_event_got_ip6_t *event = (ip_event_got_ip6_t *)event_data;
        ESP_LOGI(TAG, "Got IPv6 address " IPV6STR, IPV62STR(event->ip6_info.ip));
    }
}

void app_main(void)
{
#if CONFIG_LWIP_PPP_PAP_SUPPORT
    esp_netif_auth_type_t auth_type = NETIF_PPP_AUTHTYPE_PAP;
#elif CONFIG_LWIP_PPP_CHAP_SUPPORT
    esp_netif_auth_type_t auth_type = NETIF_PPP_AUTHTYPE_CHAP;
#else
#error "Unsupported AUTH Negotiation"
#endif

    gpio_pad_select_gpio(CONFIG_EXAMPLE_UART_MODEM_RTS_PIN);
    /* Set the GPIO as a push/pull output */
    gpio_set_direction(CONFIG_EXAMPLE_UART_MODEM_RTS_PIN, GPIO_MODE_OUTPUT);

    ESP_ERROR_CHECK(esp_netif_init());
    ESP_ERROR_CHECK(esp_event_loop_create_default());
    ESP_ERROR_CHECK(esp_event_handler_register(IP_EVENT, ESP_EVENT_ANY_ID, &on_ip_event, NULL));
    ESP_ERROR_CHECK(esp_event_handler_register(NETIF_PPP_STATUS, ESP_EVENT_ANY_ID, &on_ppp_changed, NULL));

    event_group = xEventGroupCreate();

    // Init netif object
    esp_netif_config_t cfg = ESP_NETIF_DEFAULT_PPP();
    esp_netif_t *esp_netif = esp_netif_new(&cfg);
    assert(esp_netif);

    /* create dte object */
    esp_modem_dte_config_t config = ESP_MODEM_DTE_DEFAULT_CONFIG();
    modem_dte_t *dte = esp_modem_dte_init(&config);
    /* Register event handler */
    ESP_ERROR_CHECK(esp_modem_set_event_handler(dte, modem_event_handler, ESP_EVENT_ANY_ID, NULL));
    /* create dce object */
#if CONFIG_EXAMPLE_MODEM_DEVICE_SIM800
    modem_dce_t *dce = sim800_init(dte);
#elif CONFIG_EXAMPLE_MODEM_DEVICE_BG96
    modem_dce_t *dce = NULL; 
    while(dce == NULL)
    {
        gpio_set_level(CONFIG_EXAMPLE_UART_MODEM_RTS_PIN, 0);
        vTaskDelay(200 / portTICK_PERIOD_MS);
        gpio_set_level(CONFIG_EXAMPLE_UART_MODEM_RTS_PIN, 1);
        vTaskDelay(3000 / portTICK_PERIOD_MS);
        dce = bg96_init(dte);
    }
#else
#error "Unsupported DCE"
#endif
    ESP_ERROR_CHECK(dce->set_flow_ctrl(dce, MODEM_FLOW_CONTROL_NONE));
    ESP_ERROR_CHECK(dce->store_profile(dce));
    /* Print Module ID, Operator, IMEI, IMSI */
    ESP_LOGI(TAG, "Module: %s", dce->name);
    ESP_LOGI(TAG, "Operator: %s", dce->oper);
    ESP_LOGI(TAG, "IMEI: %s", dce->imei);
    ESP_LOGI(TAG, "IMSI: %s", dce->imsi);
    /* Get signal quality */
    uint32_t rssi = 0, ber = 0;
    ESP_ERROR_CHECK(dce->get_signal_quality(dce, &rssi, &ber));
    ESP_LOGI(TAG, "rssi: %d, ber: %d", rssi, ber);
    /* Get battery voltage */
    uint32_t voltage = 0, bcs = 0, bcl = 0;
    ESP_ERROR_CHECK(dce->get_battery_status(dce, &bcs, &bcl, &voltage));
    ESP_LOGI(TAG, "Battery voltage: %d mV", voltage);
    /* setup PPPoS network parameters */
    esp_netif_ppp_set_auth(esp_netif, auth_type, CONFIG_EXAMPLE_MODEM_PPP_AUTH_USERNAME, CONFIG_EXAMPLE_MODEM_PPP_AUTH_PASSWORD);
    void *modem_netif_adapter = esp_modem_netif_setup(dte);
    esp_modem_netif_set_default_handlers(modem_netif_adapter, esp_netif);
    /* attach the modem to the network interface */
    esp_netif_attach(esp_netif, modem_netif_adapter);
    /* Wait for IP address */
    xEventGroupWaitBits(event_group, CONNECT_BIT, pdTRUE, pdTRUE, portMAX_DELAY);
    vTaskDelay(3000 / portTICK_PERIOD_MS);
    /* Config MQTT */
    esp_mqtt_client_config_t mqtt_config = {
        .uri = BROKER_URL,
        .port = 1883,
        .keepalive = 3600,
        .event_handle = mqtt_event_handler,
    };
    esp_mqtt_client_handle_t mqtt_client = esp_mqtt_client_init(&mqtt_config);
    esp_mqtt_client_start(mqtt_client);
    xEventGroupWaitBits(event_group, GOT_DATA_BIT, pdTRUE, pdTRUE, portMAX_DELAY);
    esp_mqtt_client_destroy(mqtt_client);
    /* Exit PPP mode */
    ESP_ERROR_CHECK(esp_modem_stop_ppp(dte));
    /* Destroy the netif adapter withe events, which internally frees also the esp-netif instance */
    esp_modem_netif_clear_default_handlers(modem_netif_adapter);
    esp_modem_netif_teardown(modem_netif_adapter);
    xEventGroupWaitBits(event_group, STOP_BIT, pdTRUE, pdTRUE, portMAX_DELAY);
#if CONFIG_EXAMPLE_SEND_MSG
    const char *message = "Welcome to ESP32!";
    ESP_ERROR_CHECK(example_send_message_text(dce, CONFIG_EXAMPLE_SEND_MSG_PEER_PHONE_NUMBER, message));
    ESP_LOGI(TAG, "Send send message [%s] ok", message);
#endif
    /* Power down module */
    ESP_ERROR_CHECK(dce->power_down(dce));
    ESP_LOGI(TAG, "Power down");
    ESP_ERROR_CHECK(dce->deinit(dce));
    ESP_ERROR_CHECK(dte->deinit(dte));
}

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, we will look into.

**Comment by david-cermak** [comment]
Hi @ganeshkumarsw 

Could you connect to any other broker? (have you tried the default `mqtt.eclipse.org`)
I've tested your example with `mqtt://broker.hivemq.com` and it connected to the server correctly. Might the `hivemq.com` refuse connections from some geo-locations or form your internet provider?

Could you please quickly test if the connection works when sending AT commands to the module in a manual way? It should be very easy to test using TCP command, such as:
```
AT+QIOPEN=1,0,"TCP","broker.hivemq.com",....
```

**Comment by ganeshkumarsw** [comment]
Hi,

I tried other brokers as well but still no luck. Using AT commands for MQTT it works seamlessly but not in PPP mode.

**Comment by david-cermak** [comment]
Thanks for the answers. In general I would suggest asking your operator for any possible restrictions, maybe in PPP mode?

> To my surprise, the example works for SIM868 but not for bg96.

AFAICT the SIM868 modem is a `2G` device, so might seem that the connection works okay over `2G` network, but doesn't over `LTE`? Probably also a question to your internet provider.

**Comment by slechta** [comment]
I have very similar issue with SIM800 modem. PPP initializes and I get IP, mask, gateway and dns.
(Then I get the "Got IP Event")
The issue is that I do not get any connection.
