### ISSUE TITLE
Incorrect description for rtcio_hal_ext0_set_wakeup_pin (IDFGH-3868)

### ISSUE THREAD

**Issue by boarchuz** [espressif/esp-idf#5770]
The comment for rtcio_hal_ext0_set_wakeup_pin has not been updated, instead describing the previous function (rtcio_hal_wakeup_disable):
https://github.com/espressif/esp-idf/blob/754782039331cb4fe9aa3ef8cdda7d6784d35983/components/soc/include/hal/rtc_io_hal.h#L222-L227

**Comment by Alvin1Zhang** [comment]
@boarchuz Thanks for reporting, we will look into.
