### ISSUE TITLE
produces incorrect output ESP32-S2-F2 instead embeddedflash shows external flash (IDFGH-3872)

### ISSUE THREAD

**Issue by ESP32DE** [espressif/esp-idf#5774]
hi guys

not real a Bug - ( Info ) only a wrong bit

Hardware : ESP32-S2-F2 ( ESP32-S2-FH16 )
Hello World shows "external flash" instead "embedded flash"
ESP-IDF: ESP-IDF v4.3-dev-771-gc77c4ccf6-dirty

esptool v3.0 is workig well:

![grafik](https://user-images.githubusercontent.com/16070445/90945577-f1361e00-e425-11ea-8fb5-ea16b10d8ffd.png)

only 

```
printf("%dMB %s flash\n", spi_flash_get_chip_size() / (1024 * 1024),
            (chip_info.features & CHIP_FEATURE_EMB_FLASH) ? "embedded" : "external");
```

shows external instead embedded

![grafik](https://user-images.githubusercontent.com/16070445/90945688-abc62080-e426-11ea-863e-00b915dd1c7d.png)

best wishes
rudi ;-)

btw:
[ESP32-PICO-V3-02](https://twitter.com/eMbeddedHome/status/1294988777367187457) is working [well](https://twitter.com/eMbeddedHome/status/1294812933118140416)

**Comment by projectgus** [comment]
Hi @ESP32DE,

Thanks Rudi, looks like we missed a spot! Will fix ASAP.

Angus
