### ISSUE TITLE
Odd or possible incorrect behaviour of ESP32 i2c  (IDFGH-3875)

### ISSUE THREAD

**Issue by MarkOliver1959** [espressif/esp-idf#5776]
## Environment

- Development Kit:      ESP32-Wrover-Kit and ESP32-DevKitC
- Kit version for WroverKit v4.1
- Module or chip used:  Both |ESP32-WROVER and ESP32-WROOM-32
- IDF version 4.1, 4.2 and latest :
- Build System:         both CMake and idf.py
- Compiler version 8.2.0 
- Operating System:     Windows  and macOS
-  CMD and PowerShell and via the VSCode ESP32 plugin.
- Using an IDE?: Yes VSCode with  Espressif IDF 0.4.0
- Power Supply:         USB
## Problem Description
I2C interface. The Master mode clock stretching isn't compatible with the STM32F042 and STM32FO72 implementations.
The STM32 devices are configured as slaves and work when driven/addressed by either a Raspberry Pi 3b or via Texas Instruments Tiva (Arm Core) with TMC1294 and also other Ti chips such as the MSP430 series.

## Detailed problem description.
System setup. - The I2c Bus is running at 100Khz with 2.2Kohm pullups. A single STM32 device is sitting on this bus within a 10 centimeters of wiring. Both devices are running at 3.3volts.
 
Any I2C command from the ESP32 regardless of read or write, made to the STM32 device will result in a timeout response from the ESP32.
The STM32 will clock stretch on the Read/Write bit of the command whilst it processes. This clock stretch is usually within 300 microseconds. At which point it releases the clock and waits for the data component that will follow the address. Instead there is no clock to read-in / clock-in the Address ACK and instead waits till either end times out, which is about 2.2 milliseconds. 

### Expected Behavior
After the clock has been released the ESP32 should provide a clock to read the Address ACK then if the ACK is correct (Low) then should continue to clock in the data until size or NAK is reached.

### Actual Behavior
ESP32 doesn't provide a clock after the clock has been released as though it hasn't detected the rising edge of the clock.

### Steps to reproduce
Can only be reproduced against our STM32 products.

// If possible, attach a picture of your setup/wiring here.
![Clock_Stretch_Fault](https://user-images.githubusercontent.com/44792882/90974754-850c0500-e560-11ea-8e1b-6f0b18759da3.png)

**Comment by Ethan-CYQ** [comment]
Hi, @MarkOliver1959 

I have some problems in your waveform:
- You used 100KHz i2c bus in your description, but it seems that it was 10kHz from the waveform. Did you open the Dynamic Frequency Scaling(DFS)?
![image](https://user-images.githubusercontent.com/69230009/91010369-f86f4e80-e614-11ea-95b0-5faebc3eaca8.png)
- Can you provide a correct waveform for our reference?

**Comment by MarkOliver1959** [comment]
Hi, @Ethan-CYQ,

The capture was at 10KHz which was one of several attempts down to 1KHz which intermittently worked. Originally I received this some test code from a colleague whom had thought it was working, but they had set the rate as 1KHz. I changed the rate to 100KHz and it failed continuously. 
I then attempted dozens of code and parameter variations of both the STM32 and the ESP32 code to isolate the exact problem, as I wasn't sure if it was timing, sequencing or what.  It wasn't until I disabled the clock stretching on the STM32 that I discovered that that was the issue. We have over 40,000 STM32 based units in the field, so I'm not about to change the way they work. 

As a workaround solution I'm now using a software I2C bit bang mode. Although we may have to choose a different processor.

**Comment by Ethan-CYQ** [comment]
Hi, @MarkOliver1959 

I think maybe some timing error in the read/write bit. The SDA should be pulled down within the read/write time in normal. But in your waveform, the SDA falling edge is too close to the SCL rising edge, causing the ESP32 I2C state machine to an error state. 
![image](https://user-images.githubusercontent.com/69230009/91046826-af86bc80-e64b-11ea-9dd9-5b3194c05ccb.png)
You can try to set the SDA sample time to 300 by `i2c_set_data_timing(YOUR_I2C_NUM, 300, 200)` when the I2C bus at 100KHz.

**Comment by MarkOliver1959** [comment]
Hi @Ethan-CYQ,
Thank you I'll give that a try tomorrow morning  (10 hours away).

**Comment by MarkOliver1959** [comment]
Hi @Ethan-CYQ,
I tried the i2c_set_data_timing() with 300,200 and also other variations  such as 511,200. None worked. Occasionally I'd get a slight variation of the write timing compared to the clock but nothing that yielded a positive outcome. I modified the STM32 in various ways such as increased it's clock rate to reduce the stretch time, but again no repeatable positive result.
So I'll continue with the "Bit bang" method and see how optimised I can get that, then run that as a task on a separate core.

![ESP32_toSTM32_write_at_100KHz 2 with 511_200](https://user-images.githubusercontent.com/44792882/91171941-f9d07200-e70d-11ea-8197-34baa2aea2a8.jpg)
![ESP32_toSTM32_write_at_100KHz_300_200](https://user-images.githubusercontent.com/44792882/91171953-ffc65300-e70d-11ea-9b9b-6699a1db7006.jpg)

**Comment by Ethan-CYQ** [comment]
Hi, @MarkOliver1959 

It more obvious from your waveform now. But the SCL seems stand in low-level so long that may cause timeout. Can you try to use `i2c_set_timeout(YOUR_I2C_NUM, 0xfffff)` to extend the timeout?

**Comment by MarkOliver1959** [comment]
hi @Ethan-CYQ 
The above i2c_set_timeout(I2C_NUM,0xfffff) function worked perfectly :-D

Thank you. 

I can now move ahead with the messaging and API  for the ESP32 to STM32 device.

Regards,
Mark

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, feel free to reopen.
