### ISSUE TITLE
Has esp_vfs_fat_sdspi_mount been defined? (IDFGH-3895)

### ISSUE THREAD

**Issue by rglissmann** [espressif/esp-idf#5793]
I see a declaration for esp_vfs_fat_sdspi_mount in fatfs/vfs/esp_vfs_fat.h but no vfs_fat_sdspi.c file (or other code) to implement it.

**Comment by dobairoland** [comment]
Hi @rglissmann. It is implemented in `components/fatfs/vfs/vfs_fat_sdmmc.c` [here](https://github.com/espressif/esp-idf/blob/master/components/fatfs/vfs/vfs_fat_sdmmc.c#L277).
