### ISSUE TITLE
Cannot connect socket Client to Server (IDFGH-3904)

### ISSUE THREAD

**Issue by federicoscata** [espressif/esp-idf#5802]
## Environment

- Development Kit: ESP32-DevKitC
- Kit version DevKitC: v4
- Module or chip used: ESP32-WROOM-32D
- IDF version:
- Build System:         idf.py
- Compiler version:
- Operating System:     Windows
- (Windows only) environment type: 
- Using an IDE?: Yes, Visual Studio 2019
- Power Supply:         USB

## Problem Description

I'm having a problem to connect my ESP-W-Room 32d to a socket Server. I'm sure the problem is on Client, because with another Client in C# it works.
"Socket" is created correctly. When the code execute the function "connect(sock, (struct sockaddr *)&dest_addr, sizeof(dest_addr))", it returns "ESP_LOGE(TAG, "Socket unable to connect: errno %d", errno)"

### Code to reproduce this issue

```
#define HOST_IP_ADDR "127.0.0.1"
#define PORT 11000

static const char *TAG = "example";
static const char *payload = "Message from ESP32 ";

static void tcp_client_task(void *pvParameters)
{
	char rx_buffer[128];
	char addr_str[128];
	int addr_family;
	int ip_protocol;

	while (1) {

		struct sockaddr_in dest_addr;
		dest_addr.sin_addr.s_addr = inet_addr(HOST_IP_ADDR);
		dest_addr.sin_family = AF_INET;
		dest_addr.sin_port = htons(PORT);
		addr_family = AF_INET;
		ip_protocol = IPPROTO_IP;

		
		int sock =  socket(addr_family, SOCK_STREAM, ip_protocol);
		if (sock < 0) {
			ESP_LOGE(TAG, "Unable to create socket: errno %d", errno);
			break;
		}
		ESP_LOGI(TAG, "Socket created, connecting to %s:%d", HOST_IP_ADDR, PORT);

		int err = connect(sock, (struct sockaddr_in*)&dest_addr, sizeof(dest_addr));
		if (err != 0) {
			ESP_LOGE(TAG, "Socket unable to connect: errno %d", errno);
		}
		ESP_LOGI(TAG, "Successfully connected");

		while (1) {
			int err = send(sock, payload, strlen(payload), 0);
			if (err < 0) {
				ESP_LOGE(TAG, "Error occurred during sending: errno %d", errno);
				break;
			}

			int len = recv(sock, rx_buffer, sizeof(rx_buffer) - 1, 0);
			// Error occurred during receiving
			if(len < 0) {
				ESP_LOGE(TAG, "recv failed: errno %d", errno);
				break;
			}
			// Data received
			else {
				rx_buffer[len] = 0;  // Null-terminate whatever we received and treat like a string
				ESP_LOGI(TAG, "Received %d bytes from %s:", len, addr_str);
				ESP_LOGI(TAG, "%s", rx_buffer);
			}

			vTaskDelay(2000 / portTICK_PERIOD_MS);
		}

		if (sock != -1) {
			ESP_LOGE(TAG, "Shutting down socket and restarting...");
			shutdown(sock, 0);
			close(sock);
		}
	}
	vTaskDelete(NULL);
}
```

```
static esp_err_t event_handler(void *ctx, system_event_t *event)
{
	httpd_handle_t *server = (httpd_handle_t *) ctx;
	switch (event->event_id) {
	...........................................................................
	case SYSTEM_EVENT_STA_CONNECTED:
		xTaskCreate(tcp_client_task, "tcp_client", 4096, NULL, 5, NULL);
	default:
		break;
	}
	return ESP_OK;
}

```

**Comment by Alvin1Zhang** [comment]
Thanks for reporting. Would you please help provide more details as suggested in the [issue template](https://github.com/espressif/esp-idf/issues/new?assignees=&labels=&template=bug_report.md&title=)? Information like elf, sdk configuration, backtrace, log outputs, commit ID, hardware and etc. would help us debug further. Thanks.

**Comment by Alvin1Zhang** [comment]
Thanks for updating the details, we will look into.

**Comment by YouDONG-ESP** [comment]
Hi federicoscata, I tried your code and it works. Only thing I changed is inet_addr(), i used esp_ip4addr_aton(). You can try to replace this function.


#include "esp_netif.h"
#define HOST_IP_ADDR "192.168.10.161"
#define PORT 5001

static const char *payload = "Message from ESP32 ";

static void tcp_client_task(void *pvParameters)
{
	char rx_buffer[128];
	char addr_str[128];
	int addr_family;
	int ip_protocol;

	while (1) {
        
		struct sockaddr_in dest_addr;
		dest_addr.sin_addr.s_addr = esp_ip4addr_aton(HOST_IP_ADDR);
		dest_addr.sin_family = AF_INET;
		dest_addr.sin_port = htons(PORT);
		addr_family = AF_INET;
		ip_protocol = 0;
		
		int sockfd =  socket(AF_INET, SOCK_STREAM, IPPROTO_IP);
		if (sockfd < 0) {
			ESP_LOGE(TAG, "Unable to create socket: errno %d", errno);
			break;
		}
		ESP_LOGI(TAG, "Socket created, connecting to %s:%d", HOST_IP_ADDR, PORT);

		int err = connect(sockfd, (struct sockaddr*)&dest_addr, sizeof(dest_addr));
		if (err != 0) {
			ESP_LOGE(TAG, "Socket unable to connect: errno %d", errno);
		}
		ESP_LOGI(TAG, "Successfully connected");

		while (1) {
			int err = send(sockfd, payload, strlen(payload), 0);
			if (err < 0) {
				ESP_LOGE(TAG, "Error occurred during sending: errno %d", errno);
				break;
			}

			int len = recv(sockfd, rx_buffer, sizeof(rx_buffer) - 1, 0);
			// Error occurred during receiving
			if(len < 0) {
				ESP_LOGE(TAG, "recv failed: errno %d", errno);
				break;
			}
			// Data received
			else {
				rx_buffer[len] = 0;  // Null-terminate whatever we received and treat like a string
				ESP_LOGI(TAG, "Received %d bytes from %s:", len, addr_str);
				ESP_LOGI(TAG, "%s", rx_buffer);
			}

			vTaskDelay(2000 / portTICK_PERIOD_MS);
		}

		if (sockfd != -1) {
			ESP_LOGE(TAG, "Shutting down socket and restarting...");
			shutdown(sockfd, 0);
			close(sockfd);
		}

        vTaskDelay(500/portTICK_PERIOD_MS);
	}
	vTaskDelete(NULL);
}

		


void test(void)
{
    printf("test\n");
    xTaskCreate(tcp_client_task, "tcp_client", 4096, NULL, 5, NULL);
    printf("task done \n");
    while(1){

    }
}

LOG:
I (9049) tag: Socket created, connecting to 192.168.10.161:5001
I (9067) tag: Successfully connected
I (9080) tag: Received 28 bytes from �����������������@(@0:
I (9081) tag:

**Comment by YouDONG-ESP** [comment]
Considering you didn't give the esp-idf commit, I used latesst version of master.

**Comment by liuzfesp** [comment]
HI @federicoscata does the suggestion helpful for you?

**Comment by federicoscata** [comment]
Yes, my code works correctly, I found out that there was a problem with the server ip.

Thanks.
