### ISSUE TITLE
Having trouble with importing files in an Espressif project in Eclipse (IDFGH-3908)

### ISSUE THREAD

**Issue by huzzziiii** [espressif/esp-idf#5804]
Created an Espressif project in Eclipse but running into a few issues:

- The files that are included in `main` can't seem to be included in other source files. For e.g, neither of the following includes work in any other source file.
```#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "freertos/event_groups.h"

#include "esp_system.h"
#include "esp_wifi.h"
#include "esp_event.h"
#include "esp_log.h"
#include "nvs_flash.h"

#include "lwip/sockets.h"
#include "lwip/err.h"
#include "lwip/sys.h"
#include "stdbool.h"
```

- Can't seem to include any other source file in `main` file. 

- Don't have a `C/C++ Build` section in Properties.
https://imgur.com/a/boT3pyh

Do these issues arise from a different relative path being used that probably is pointing to a local espressif directory?

**Comment by brianignacio5** [comment]
Hi @huzzziiii Have you tried using our [Eclipse plugin for ESP-IDF](https://github.com/espressif/idf-eclipse-plugin) ?

It provides you many options such as Header resolution as you requested.

**Comment by Alvin1Zhang** [comment]
@huzzziiii Thanks for reporting, would you please help share if any updates for the issue? Thanks.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to short of feedback, feel free to reopen.
