### ISSUE TITLE
[question] ble transfer slow after ble mesh deinit (IDFGH-3912)

### ISSUE THREAD

**Issue by chegewara** [espressif/esp-idf#5806]
@Campou is there a way to stop, deinit, pause bluedroid ble mesh somehow? It would be useful in case of OTA update, which now takes about 10 minutes, which normally would be less than 1 minute.

Thanks

**Comment by Campou** [comment]
Hi @chegewara 

Currently BLE Mesh provides a function `esp_ble_mesh_deinit` for de-initializing the whole mesh stack, and the parameter of this function can be used to decide whether erasing the mesh information from flash.

Thanks.

**Comment by chegewara** [comment]
Yes, i know @Campou thanks, but this does not solved problem with stopping transfer every few seconds. It is better, but OTA still takes 5+ minutes, which usually takes about 1 minute.

**Comment by AxelLin** [comment]
Is it possible to improve the title?

**Comment by Campou** [comment]
Hi @chegewara 

So even if the mesh stack is de-initialized, there is still no big improvement for the OTA speed.

Just one more question here, I didn't understand `stopping transfer every few seconds` very clearly, did you mean the BLE transfer is just stopped every few seconds?

Thanks.

**Comment by chegewara** [comment]
Ok, seems it is some other problem with transfer being paused every few seconds. Its strange, because i didnt have it with the same code in other apps using the same or similar ionic app.
I did some test and i disabled ble mesh completely and still OTA update is stopping every few seconds.
I think i can close issue for now, since i dont know where is the real problem, esp32 or android ionic app.

Thanks
