### ISSUE TITLE
How to disable wifi (IDFGH-3918)

### ISSUE THREAD

**Issue by zhengjianxing** [espressif/esp-idf#5812]
HI,How to disable wifi, switch wifi like mobile phone. The user wants to turn off the wifi while the chip is running to save power

**Comment by liuzfesp** [comment]
Hi @zhengjianxing, `esp_wifi_disable` is similar as mobile phone WiFi off button.
However, if you want to keep WiFi connection, you use WiFi modem sleep, see: https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/wifi.html#esp32-wi-fi-power-saving-mode

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, for "how" questions, you could help raise a post on our forum at https://esp32.com, will close this ticket now. Thanks.
