### ISSUE TITLE
Failed at mbedtls_ctr_drbg_seed with error code : -0x34 (IDFGH-3941)

### ISSUE THREAD

**Issue by jkent** [espressif/esp-idf#5830]
## Environment

- Development Kit:      ESP32-Wrover-Kit
- Kit version (for WroverKit/PicoKit/DevKitC): v4.1
- Module or chip used:  ESP32-WROVER-B
- IDF version (run ``git describe --tags`` to find it):
    v4.3-dev-914-g456134ea0
- Build System:         idf.py
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it):
    xtensa-esp32-elf-gcc (crosstool-NG esp-2020r2) 8.2.0

- Operating System:     Linux

- Using an IDE?: Yes: Visual Studio Code
- Power Supply:         USB

## Problem Description

Trying to use wifi_prov_mgr with MBEDTLS_THREADING_ALT turned on.

### Expected Behavior

To run without error.  I may be missing something.

### Actual Behavior

The entropy source fails:
E (32790) security1: Failed at mbedtls_ctr_drbg_seed with error code : -0x34

### Steps to reproduce

1. Use slightly modified esp-idf (for threading_alt.h to be included...)
    https://github.com/jkent/esp-idf/tree/coreone
    (located in components/aws-iot-device-sdk-embedded-C/port/include/threading_alt.h)
2. Enable MBEDTLS_THREADING_ALT
3. Build, flash and run example wifi_prov_mgr
4. Try to provision using BLE using Android app

## Debug Logs

```
I (950) BTDM_INIT: BT controller compile version [270f54d]
I (1200) protocomm_nimble: BLE Host Task Started
I (1210) wifi_prov_mgr: Provisioning started with service name : PROV_450558 
I (1210) app: Provisioning started
GAP procedure initiated: advertise; disc_mode=2 adv_channel_map=0 own_addr_type=0 adv_filter_policy=0 adv_itvl_min=256 adv_itvl_max=256
E (32790) security1: Failed at mbedtls_ctr_drbg_seed with error code : -0x34
E (32790) security1: Session setup error -1
E (32790) protocomm_nimble: Invalid content received, killing connection
```

**Comment by mahavirj** [comment]
@jkent I have not checked your fork but can you please confirm that you have call to `mbedtls_threading_set_alt` in your application startup code (Ref: https://tls.mbed.org/kb/development/thread-safety-and-multi-threading)? Additional reference for implementation can be found at: https://github.com/aws/amazon-freertos/blob/master/libraries/freertos_plus/standard/crypto/src/iot_crypto.c#L255
