### ISSUE TITLE
Problem with ESP32 Wrover-B with wifi TCP/IP connection - high latency and anser to cloud connection in HTTP/POST-REST (IDFGH-3960)

### ISSUE THREAD

**Issue by filzek** [espressif/esp-idf#5846]
Using release v4.1 the wifi seens to be stable and we havent seen disconnection but the TCP/IP stack seens to become lazy and with a very high latency to answer, connection to a http request takes longer and longer until connection become very unstable even with very good rssi and wifi connection.

Seens that somehow the TCP/IP stack and wifi arent working correct.

We will try to reproduce the issues and report it more complete tomorrow, but the problem exist so far.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting. Would you please help provide more details as suggested in the [issue template](https://github.com/espressif/esp-idf/issues/new?assignees=&labels=&template=bug_report.md&title=)? Information like elf, sdk configuration, backtrace, log outputs, commit ID, hardware and etc. would help us debug further. Thanks.

**Comment by Alvin1Zhang** [comment]
@filzek Thanks for reporting, would you please help share if more updates for this issue? Thanks.

**Comment by Alvin1Zhang** [comment]
@filzek Thanks for reporting, would you please help share if more updates for this issue? Thanks.

**Comment by filzek** [comment]
We will prepare a working example for this problem so can test it and check where problem relays.

**Comment by Alvin1Zhang** [comment]
Thanks for the updates.

**Comment by lhespress** [comment]
@filzek Does this issue still exist?

**Comment by maikeriva** [comment]
I am experiencing similar problems on IDF v4.0.2. I performed various tests on my custom code and high latency seems to occur within the lwip or wifi stack. Interestingly enough, that does seem to happen only when the ESP module receives data, and not when it sends to the server.

Will try to create a working code stub in the next days.

**Comment by lhespress** [comment]
@maikeriva 

Thanks for the updates, you also can check it on IDF v4.2. It's better to share the code when reproduce the issue again.

**Comment by maikeriva** [comment]
Turns out in my case that turning off WiFi power saving did the trick.

`esp_wifi_set_ps(WIFI_PS_NONE)`

It was particularly hard to find out since the latency issue does not appear when stress-testing by firing multiple requests to the ESP32, but only with sparse requests every now and then.

**Comment by filzek** [comment]
I can try it tomorrow to check performance and later return for the results, as far latest v4.2 release still having this problem so far, but lets test this solution idea.

**Comment by filzek** [comment]
Problem was that is almost impossible to remove the code to provide one working example, but we test with IIS, NGIX and some other and the problem happen randomly.

We have found out that the answer when the problem happen from the server is correct but the esp32 reads ZERO in the answer, so is something with internal lwip and esp32, so the package was really lost and the content was unread.

**Comment by lhespress** [comment]
@filzek the esp32 reads ZERO means that the connection is inactive, Could you enable the `SOCKETS_DEBUG` in `lwipopts.h` file and test again? if output the log as follows:

```
lwip_recv_tcp: p == NULL, error is "Connection closed."!
```
It means that the server close the connection actively.

**Comment by filzek** [comment]
Hi @lhespress I have enable it in:
esp-idf\components\lwip\port\esp32\include\lwipopts.h

 #define SOCKETS_DEBUG                   LWIP_DBG_ON

Is that right or do I need to change it somewhere else?

**Comment by filzek** [comment]
Log says:

lwip_recv_tcp: netconn_recv err=-3, pbuf=0x0
lwip_recv_tcp: p == NULL, error is "Timeout."!
lwip_recvfrom(55):  addr=xxx.xxx.xxx.xxx port=80 len=-1
lwip_close(55)
SIZE OF RECEIVED [0] DATA[] is not higher than 0 so, will restart loop

**Comment by lhespress** [comment]
@filzek  It shows that recv data timeout from the log, the recvmbox maybe full, could you modify the `CONFIG_LWIP_TCP_RECVMBOX_SIZE`, `CONFIG_LWIP_TCPIP_RECVMBOX_SIZE` and check again?

**Comment by lhespress** [comment]
@filzek In addition to that, what did you call `setsockopt` on `SO_RCVTIMEO` for change the recv timeout value from zero (default) to the other value.

**Comment by lhespress** [comment]
In addition to that you also can modify the timeout value as follow steps:
```
esp_http_client_config_t config = {
        .host = "httpbin.org",
        .path = "/get",
        .query = "esp",
        .event_handler = _http_event_handler,
        .user_data = local_response_buffer,        // Pass address of local buffer to get response
        .disable_auto_redirect = true,
        .timeout_ms = 15000,
    };
   esp_http_client_handle_t client = esp_http_client_init(&config);
```

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, feel free to reopen.

**Comment by baldhead69** [comment]
So, how was this problem solved ?

**Comment by filzek** [comment]
Not sure how we solve it, but it was solved


Em sáb., 28 de ago. de 2021 00:03, baldhead69 ***@***.***>
escreveu:

**Comment by lhespress** [comment]
@filzek 

Did you modify the timeout value as follow steps:

```
struct timeval receiving_timeout;
        receiving_timeout.tv_sec = 15;
        receiving_timeout.tv_usec = 0;
        if (setsockopt(s, SOL_SOCKET, SO_RCVTIMEO, &receiving_timeout,
                sizeof(receiving_timeout)) < 0) {
            ESP_LOGE(TAG, "... failed to set socket receiving timeout");
            close(s);
            vTaskDelay(4000 / portTICK_PERIOD_MS);
            continue;
        }
```

@baldhead69 Could you check it again?

**Comment by baldhead69** [comment]
Where to put this ?
