### ISSUE TITLE
ESP32 DevKit C V4 crashes when using peripherals/adc example | not usable anymore (IDFGH-3970)

### ISSUE THREAD

**Issue by PhilZu** [espressif/esp-idf#5855]
## Environment

- Development Kit:        ESP32-DevKitC
- Kit version:                 v4
- Module or chip used:  ESP32-WROOM-32D
- IDF version:                4.1
- Build System:              CMake
- Compiler version        
- Operating System:      Windows
- environment type:      ESP Command Prompt
- Using an IDE?:            Eclipse IDE Version: 2020-06 (4.16.0)
- Power Supply:            USB | labratory power supply for the potentiometer with 1.0 V and 0.01A

## Problem Description

Dear Ladies and Gentleman, 

I am currently getting started with the ESP32. So I got myself an ESP32 DevKitC V4 Board. I wanted to try the analog-to-digital-converter, and somehow my ESP32 got completely wasted. 
After uploading the unchanged sketch from https://github.com/espressif/esp-idf/tree/c77c4cc/examples/peripherals/adc, the values were pretty switching every second. So I connected the GPIO34 to ground, the values got to 0, the expected Value. After that I connected GPIO34 to the 3.3V and got the expected value of 4095. 

So I wanted to start to measure something in between and read the value of a potentiometer. So I connected the middle Pin of the 10kOhm Potentiometer to the GPIO34, used an 1.00V and 0,01A labratory power supply for the rest of the potentiometer. The ESP32 immediately lost the connection, the terminal in eclipse closed. 

Right now the esp32 is getting really hot when connected to the PC. I can't flash any new programs to the ESP32. It looks like it is trapped in something like a bootloop. 

I have alread tried the suggested solutions in this github: https://github.com/espressif/arduino-esp32/issues/2630. 
I have already tried to flash the ESP32 with Arduino, tried to remove the flash with esptool.py or idf.py, nothing works. I can't even connect to the board. 

Does anybody have an idea or a solution proposal? I guess this couldn't be an electrical issue, the potentiometer resistance is almost like the maufacturer's information. In the minimum position the resistance is about 0 Ohm, in the maximum position the resistance is about 10.000 Ohm. 

Thanks in advance,

Philipp

### Expected Behavior

Printing out the different ADC-Values in the serial monitor.

### Actual Behavior

ESP32-Module not usable anymore. The Chip itself get's hot, no flashing possible.

### Steps to reproduce

1. Flash the peripherals/adc1 without changing a single line of Code.
2. Power the potentiometer with the labratory power supply. The position of the potentiometer was almost in the middle between the maximum positions.
3. Connect the middle wire of a 10 kOhm potentiometer to GPIO34. 

https://i1.wp.com/randomnerdtutorials.com/wp-content/uploads/2019/05/Analog_Input_Potentiometer-700px.jpg?ssl=1

### Code to reproduce this issue

https://github.com/espressif/esp-idf/tree/c77c4cc/examples/peripherals/adc

## Other items if possible

**Comment by Ethan-CYQ** [comment]
Hi, @PhilZu 
Can you provide some information from the terminal when you try to flash and monitor ESP32(the crash one)?

**Comment by Alvin1Zhang** [comment]
@PhilZu Thanks for reporting, would you please help share if any updates for this issue? Thanks.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to short of feedback, feel free to reopen with more updates. Thanks.
