### ISSUE TITLE
esp32s2 csi bug (IDFGH-3972)

### ISSUE THREAD

**Issue by ydspace** [espressif/esp-idf#5857]
Esp32s2 WiFi CSI does not call back the data, esp32 is valid. 
The code is the same.

**Comment by zhangyanjiaoesp** [comment]
hi @ydspace ,
Can you please provide a demo to reproduce this issue ?
And please  update the infomation according to the template, thanks.
https://github.com/espressif/esp-idf/issues/new?assignees=&labels=&template=bug_report.md&title=

**Comment by zhangyanjiaoesp** [comment]
@ydspace 
I have reproduce this issue locally, and we will solve the problem as soon as possible.

**Comment by Alvin1Zhang** [comment]
We have a fix under internal reviewing and the issue will close automatically once the fix is available on GitHub, thanks.
