### ISSUE TITLE
it wasn't supposed to be wss here ? (IDFGH-3994)

### ISSUE THREAD

**Issue by baldhead69** [espressif/esp-idf#5874]
it wasn't supposed to be wss here, instead of ws ?

https://github.com/espressif/esp-idf/blob/8bc19ba893e5544d571a753d82b44a84799b94b1/examples/protocols/https_server/wss_server/main/wss_server_example.c#L83

**Comment by baldhead69** [comment]
Sorry, 

I ended up getting confused. 

it is only the uri. 
I thought it was the scheme (protocol).

**Comment by david-cermak** [comment]
@baldhead69 Yes, this is only the path portion of the uri. Could you please close the issue now?
