### ISSUE TITLE
In 'secure_boot.h' a 'extern "C" {' statement is missing a closing '}' resulting in failed compilation esp-idf-v4.1 (IDFGH-3998)

### ISSUE THREAD

**Issue by GuyMinibrew** [espressif/esp-idf#5878]
## Environment

- Development Kit:      [none]
- Kit version (for WroverKit/PicoKit/DevKitC): [v4]
- Module or chip used:  [ESP32]
- IDF version (run ``git describe --tags`` to find it): v4.1-273-g94cb7e8b8
- Build System:         [idf.py]
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it): xtensa-esp32-elf-gcc (crosstool-NG esp-2019r2) 8.2.0
- Operating System:     [macOS]
- Using an IDE?: [No]
- Power Supply:         [5V]

## Problem Description

Quite simply, on commit: 60fed38c0f6de00d93ace8fedd81d3b3fc51693a

File path: 
esp-idf/components/esp_rom/include/esp32/rom/secure_boot.h

This statement was deleted:
**_#ifdef __cplusplus
}
#endif_**

But this statement still remains unchanged:
**_#ifdef __cplusplus
extern "C" {
#endif_**

This results in missing "}" clause, causing havoc if secure boot is used in ESP-IDF-v4.
See compilation output below.

### Expected Behavior
Compilation successful.

### Actual Behavior
Compilation fails.

### Steps to reproduce
Compile with secure boot enabled and include <esp_secure_boot.h>

## Debug Logs

```
../main/Machine.cpp:1538:1: error: expected '}' at end of input
 }
 ^
In file included from ../esp/esp-idf/components/bootloader_support/include/esp_secure_boot.h:25,
                 from ../main/Machine.cpp:34:
../esp/esp-idf/components/esp_rom/include/esp32/rom/secure_boot.h:23:12: note: to match this '{'
 extern "C" {
            ^
ninja: build stopped: subcommand failed.
ninja failed with exit code 1

```

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, we will look into.
