### ISSUE TITLE
Classic bluetooth acl data stall when ble get connected (IDFGH-4008)

### ISSUE THREAD

**Issue by limithsieh** [espressif/esp-idf#5887]
## Environment

- Module or chip used:  [ESP32-WROOM-32]
- IDF version (run ``git describe --tags`` to find it):  release/v4.0
- Build System:         [Make]
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it): xtensa-esp32-elf-gcc (crosstool-NG esp-2019r2) 8.2.0
- Operating System:     [Linux]
- Using an IDE?: [No]
- Power Supply:  [external 5V]

## Problem Description

My application is base on bluechicken BTstack. When running Bluetooth classic hid_mouse_demo with BLE gatt service(dual mode). Bt mouse will enter sniff mode after connected with smartphone. 

The problem is Mouse data would get stuck randomly after BLE connect to smartphone. At the same time, BLE data transmission works fine. I found out that controller will not send HCI_EVENT_NUMBER_OF_COMPLETED_PACKETS to host when sending mouse data.

If my classic bluetooth mouse didn't enter sniff mode, everything works fine. I am wondering HCI command "enter_sniff_mode" has parameter "Sniff_Timeout". It should flush the mouse data in controller when timeout occure. I also try HCI command "hci_flush" when mouse data get stuck but still not works.

### Expected Behavior
Classic bluetooth acl data transmit normal when BLE connected

### Actual Behavior
Classic bluetooth acl data got stuckl when BLE connected
### Steps to reproduce

1. BTstack hid_mouse_demo add ble gatt service
2. connect bt mouse and ble gatt service to smartphone
3. after a while, mouse data will not send to smartphone

**Comment by Wth-Esp** [comment]
Hi

When BT is transporting data with the peer device, it should stay in active mode, sniff mode would affect the throughput. Like when you connect the a2dp and the audio stream is working, sniff will cause a severe click sound.

Thanks

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, feel free to reopen.
