### ISSUE TITLE
The Socket's function of send() or recv() takes too  much time sometimes (IDFGH-4015)

### ISSUE THREAD

**Issue by helittr** [espressif/esp-idf#5894]
# Recently, I am completing a project about Low power consumption. And I've got a sticky problem.

My needs is that when the **ESP32** wakes up from deep sleep mode, send some data to server by WIFI.

But, sometimes, the function of `send()` or `recv()` takes time that is up to about 4 seconds. And sometimes, it  takes less than one seconds. All tests were performed when the WIFI signal was greater than **-60dbm**.

Is there any way to optimize this problem?
## Environment
Module or chip used: ESP32-WROOM-32U
IDF version : v4.0.1
Build System: idf.py
Operating System:Windows
Using an IDE: Eclipse CDT
Power Supply: external 3.3V
## Code snippet
```
int8_t send_to_server(server_handle_t handle, uint32_t len, uint8_t *pdata)
{
	/* 发送数据区 */
	int16_t tmp = 0;
	uint16_t cnt = 0;
        time_t useTime = time(NULL);
	while(len >= 1024)
	{
		tmp = send(handle->sock, pdata + cnt * 1024, 1024, 0);
		if(tmp < 0)
		{
			ESP_LOGE(TAG, "send_to_server:Error occurred during send: errno %d", errno);
			return -2;
		}
		len -= 1024;
		cnt++;
	}

	if(len != 0)
	{
		tmp = send(handle->sock, pdata + cnt * 1024, len, 0);
		if(tmp < 0)
		{
			ESP_LOGE(TAG, "send_to_server:Error occurred during send: errno %d", errno);
			return -2;
		}
	}

	ESP_LOGI(TAG, "send_to_server:Send OK!");
        ESP_LOGW(TAG,"Used time : %d s\n",(int)(time(NULL) - useTime));
	return 0;
}
```	
## Debug Output
W (5315) MIAN: Used time : 2 s
W (5315) MIAN: Used time : 1 s
W (5315) MIAN: Used time : 1 s
W (5315) MIAN: Used time : 1 s
W (5315) MIAN: Used time : 1 s
W (5315) MIAN: Used time : 1 s
W (5315) MIAN: Used time : 1 s
W (5315) MIAN: Used time : 3 s
W (5315) MIAN: Used time : 1 s
W (5315) MIAN: Used time : 1 s
W (5315) MIAN: Used time : 1 s
W (5315) MIAN: Used time : 1 s
W (5315) MIAN: Used time : 4 s
Thankyou.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting. Would you please help provide more details as suggested in the [issue template](https://github.com/espressif/esp-idf/issues/new?assignees=&labels=&template=bug_report.md&title=)? Information like elf, sdk configuration, backtrace, log outputs, commit ID, hardware and etc. would help us debug further. Thanks.

**Comment by david-cermak** [comment]
Hi @helittr 

Could you please explain a bit your environment? Are you sending the data to a local server, which is *always* available or to an internet, how much data you're sending, get these data fragmented, are they sent in multiple packets?
As you know the TCP is not real time so might be tricky with the predictable throughput based on WiFi signal.
There are ways of course to adjust the TCP parameters, but need to understand what's happening on the network. In general we could:
* Disable naggling  (`TCP_NODELAY`)
* Adjusting buffer sizes
* Adjusting low level TCP params, like time to retransmit, re-trasmit period, etc..
