### ISSUE TITLE
flash read err, 1000 (IDFGH-4022)

### ISSUE THREAD

**Issue by tayph** [espressif/esp-idf#5898]
## Environment

    Development Kit: [ESP32-DevKitC]
    Kit version (DevKitC): [v4]
    Module or chip used: 32-WROVER-B
    IDF version (run git describe --tags to find it):
    v4.1
    Build System: [idf.py]
    Compiler version (run xtensa-esp32-elf-gcc --version to find it):
    (crosstool-NG esp-2020r2) 8.2.0
    Operating System: [Windows]
    (Windows only) environment type: ESP Command Prompt
    Using an IDE?: [vs code]
    Power Supply: [USB]

## Problem Description

After try the example flash encryption I'm getting an error  and i try the flash another working project but result same.
i searched some post and try hard reset but doesnt work. 
A little help would be great thanks.

## Debug Logs
rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
flash read err, 1000
ets_main.c 371
ets Jun  8 2016 00:22:57

rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
flash read err, 1000
ets_main.c 371
ets Jun  8 2016 00:22:57

**Comment by negativekelvin** [comment]
You have to disable encryption or flash using encrypt option
