### ISSUE TITLE
DFS(dynamic frequency scaling) changes pwm frequency (IDFGH-4034)

### ISSUE THREAD

**Issue by thedayu** [espressif/esp-idf#5907]
## Environment

- Development Kit:      ESP32-DevKitC
- Kit version v4
- Module or chip used:ESP32-WROOM-32U|ESP32-WROVER
- IDF version (run ``git describe --tags`` to find it):
v4.0
- Build System:         CMake|idf.py
- Operating System:     Linux
- Using an IDE: VSCODE
- Power Supply:         USB

## Problem Description

PWM frequency changes over time.

//Detailed problem description goes here.

### Expected Behavior

API should do as it says, and PWM freq should not change.
` uint32_t freq_hz;                      /*!< LEDC timer frequency (Hz) */
`

### Actual Behavior

Changes when open when BLE scan/WIFI data, etc.

### Steps to reproduce

Enable DFS, produce pwm output, use a oscilloscope to monitor pin accordingly.

LEDC CODE:
```
ledc_timer_config_t conf = {
			.duty_resolution = LEDC_TIMER_8_BIT,
			.freq_hz = 1000,
			.speed_mode = LEDC_HIGH_SPEED_MODE,
			.timer_num = 0
	};
	ERROR_CHECK(ledc_timer_config(&conf));
	ledc_channel_config_t conf = {
		.channel    = 0,
		.duty       = 128,
		.gpio_num   = pin,
		.speed_mode = LEDC_HIGH_SPEED_MODE,
		.hpoint     = 0,
		.timer_sel  = 0
	};
	ledc_channel_config(&conf);
```

BLE SCAN PARAM：
following code will cause pwm freq change during every scan_interval.
```
	static esp_ble_scan_params_t ble_scan_params = {
		.scan_type = BLE_SCAN_TYPE_PASSIVE,
		.own_addr_type = BLE_ADDR_TYPE_PUBLIC,
		.scan_filter_policy = BLE_SCAN_FILTER_ALLOW_ALL,

		.scan_interval = 0x50,        //<<<<<<<<<<<<<<<<<<<<<<<<<<
		.scan_window = 0x20,        //<<<<<<<<<<<<<<<<<<<<<<<<<<
		.scan_duplicate = BLE_SCAN_DUPLICATE_DISABLE};
	ERROR_CHECK(esp_ble_gap_set_scan_params(&ble_scan_params));
```

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, we will look into.

**Comment by igrr** [comment]
Hi @thedayu, as mentioned in https://docs.espressif.com/projects/esp-idf/en/v4.0.1/api-reference/system/power_management.html#dynamic-frequency-scaling-and-peripheral-drivers, LEDC can be configured with REF_TICK clock source to prevent the frequency changing when DFS is enabled. You can set LEDC_USE_REF_TICK value for clk_cfg in the ledc_timer_config_t structure.

**Comment by thedayu** [comment]
@igrr That's it. Thanks for quick reply.

**Comment by InfiniteYuan** [comment]
@igrr When the LEDC_USE_REF_TICK clock source is configured for LEDC to prevent frequency changes, the frequency of LEDC clock source is reduced to 1MHz. 

The frequency of LEDC clock source is not meet my application needs. 

Do you have a good way?

**Comment by igrr** [comment]
Per the docs, "For low speed channels, you can also specify the source clock using LEDC_USE_RTC8M_CLK, in this case, all low speed channel’s source clock must be RTC8M_CLK". This should raise the frequency to ~8 MHz. Higher LEDC clock frequencies are not possible when APB clock frequency of the ESP32 is changing, I'm afraid.
