### ISSUE TITLE
[TW#12631] false positives with CONFIG_BLUEDROID_MEM_DEBUG enabled

### ISSUE THREAD

**Issue by thomaspugliese** [espressif/esp-idf#592]
If I enable CONFIG_BLUEDROID_MEM_DEBUG in menuconfig, I see the following error when running the bluetooth/gatt_client example.

E (522) BT: osi_mem_dbg_clean full future_free 98 !!

This error suggests a double free caused by the future_await call in esp_bluedroid_init, but in fact it is a false positive because bte_main_boot_entry is calling osi_mem_dbg_init after the future_new in esp_bluedroid_init.  This clears the reference to the future_new allocation, so when future_await frees it, it is not found in the mem_debug table.

The following patch fixes the issue although it may not be the optimal solution.

[mem_debug_patch.txt](https://github.com/espressif/esp-idf/files/993083/mem_debug_patch.txt)

There are other double frees detected as well, but I haven't determined their cause yet.

**Comment by Yulong-espressif** [comment]
@thomaspugliese Thanks so much to find this issues in the SDK, we have fixed this bug in the new SDK, you can get it from the github.
