### ISSUE TITLE
Can't build bootloader using idf.py (IDFGH-4070)

### ISSUE THREAD

**Issue by skywa04885** [espressif/esp-idf#5941]
Now I really cannot deal with this issue, have to make something working in a short amount of time, and it literally just does not work.

When executing idf.py i get this error:

`xtensa-esp32-elf-gcc: error: Drive/Projects/ESP/hello_world/build/bootloader/bootloader.map: No such file or directory
ninja: build stopped: subcommand failed.
[3/360] Linking CXX static library esp-idf/e`

I just installed IDF and followed the installation guide exactly. Please help !

**Comment by igrr** [comment]
Hi @skywa04885, could you please fill in the issue template you were offered when creating the issue? Information such as: operating system, ESP-IDF version, compiler version, full output from the build process can all help to find the issue.

From the brief excerpt you have shared, I suspect that your project folder has spaces in its path. This isn't supported by the ESP-IDF build system, yet. Please try to copy the hello_world project into a different directory, and do `idf.py fullclean`, and then build again.

If you are interested in support for spaces in project path, please visit https://github.com/espressif/esp-idf/issues/5576 and click "Subscribe" button to receive notifications.

**Comment by Alvin1Zhang** [comment]
@skywa04885 Thanks for reporting, would you please help share more details of the issue per the issue template? Thanks.

**Comment by Alvin1Zhang** [comment]
@skywa04885 Thanks for reporting, would you please help share more details of the issue per the issue template? Thanks.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to short of feedback, feel free to reopen.
