### ISSUE TITLE
Does esp-idf have tools to create project scaffolding? It allows me to quickly start a new project. (IDFGH-4084)

### ISSUE THREAD

**Issue by ICLXL** [espressif/esp-idf#5955]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

Please give as many details as you can. Include suggestions for useful APIs or interfaces if relevant.

**Additional context**

**Comment by igrr** [comment]
Hi @ICLXL, `idf.py create-project` command has been recently implemented and will be available on Github soon. We'll update this issue when the feature is released.

**Comment by igrr** [comment]
Added in https://github.com/espressif/esp-idf/commit/b599f127b5e6ee9af12f4de20ac41e66fdf60e1c.
