### ISSUE TITLE
gpio_get_level() incorrect after 2 deep sleep

### ISSUE THREAD

**Issue by johnnorbury** [espressif/esp-idf#596]
Hello,

Using the deep sleep functionnality for a dry contact device I noticed

> gpio_get_level( GPIO_INPUT_IO_TRIGGER );

Isn't returning the correct value after 2 deep sleep cycles. Below is the code:

`#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "freertos/queue.h"
#include "driver/gpio.h"
#include "driver/adc.h"
#include "esp_log.h"
#include "driver/rtc_io.h"

#include <math.h>
#include "sdkconfig.h"
#include "esp_deep_sleep.h"

#define GPIO_INPUT_IO_TRIGGER     15 

RTC_DATA_ATTR int valueToWakeUp;
RTC_DATA_ATTR int wake_count = 0;

void RTC_IRAM_ATTR esp_wake_deep_sleep(void) {
    esp_default_wake_deep_sleep();
    wake_count++;
}

void app_main(void)
{

    ESP_LOGI("ESP32","Woken Up");

    int gpio_level = gpio_get_level( GPIO_INPUT_IO_TRIGGER );
    ESP_LOGE("ESP", "GPIO State: %d\n", gpio_level );

    int nextWakeUpState = -1;

    switch (esp_deep_sleep_get_wakeup_cause()) {
        case ESP_DEEP_SLEEP_WAKEUP_EXT0: {

            ESP_LOGI("ESP32","Woken from deep sleep (%d)",wake_count);
            ESP_LOGE("ESP", "Previous GPIO state: %d\n", valueToWakeUp );

            valueToWakeUp = ((valueToWakeUp + 1) % 2);
            nextWakeUpState = valueToWakeUp;

            break;
        }
        case ESP_DEEP_SLEEP_WAKEUP_UNDEFINED:
        default:

            ESP_LOGI("ESP32","First start (%d)",wake_count);
            ESP_LOGE("ESP", "Undefined wake up\n");

            nextWakeUpState = ((gpio_level + 1) % 2);
            valueToWakeUp = nextWakeUpState;
    }

    esp_deep_sleep_pd_config(ESP_PD_DOMAIN_RTC_PERIPH, ESP_PD_OPTION_AUTO); //!< Keep power domain enabled in deep sleep, if it is needed by one of the wakeup options. Otherwise power it down.
    gpio_pullup_en(GPIO_INPUT_IO_TRIGGER);      // use pullup on GPIO
    gpio_pulldown_dis(GPIO_INPUT_IO_TRIGGER);       // not use pulldown on GPIO

    ESP_LOGI("ESP","State to trigger next wakeup: %d\n", nextWakeUpState );
    esp_deep_sleep_enable_ext0_wakeup(GPIO_INPUT_IO_TRIGGER,  nextWakeUpState); // Wake if GPIO is low

    ESP_LOGE("ESP", "deep sleep\n");
    esp_deep_sleep_start();

}`

I use an RTC variable 'valueToWakeUp' as a workaround for the gpio_get_level() which always returns 0 (low).

> .[0;32mI (1176) ESP32: Woken Up.[0m
> .[0;31mE (1176) ESP: GPIO State: 1
> .[0m
> .[0;32mI (1176) ESP32: First start (0).[0m
> .[0;31mE (1186) ESP: Undefined wake up
> .[0m
> .[0;32mI (1186) ESP: State to trigger next wakeup: 0
> .[0m
> .[0;31mE (1196) ESP: deep sleep
> .[0m

> .[0;32mI (1175) ESP32: Woken Up.[0m
> .[0;31mE (1175) ESP: GPIO State: 0
> .[0m
> .[0;32mI (1175) ESP32: Woken from deep sleep (1).[0m
> .[0;31mE (1185) ESP: Previous GPIO state: 0
> .[0m
> .[0;32mI (1185) ESP: State to trigger next wakeup: 1
> .[0m
> .[0;31mE (1195) ESP: deep sleep
> .[0m
> 

> .[0;32mI (1175) ESP32: Woken Up.[0m
> .[0;31mE (1175) ESP: GPIO State: 0
> .[0m
> .[0;32mI (1175) ESP32: Woken from deep sleep (2).[0m
> .[0;31mE (1185) ESP: Previous GPIO state: 1
> .[0m
> .[0;32mI (1185) ESP: State to trigger next wakeup: 0
> .[0m
> .[0;31mE (1195) ESP: deep sleep
> .[0m

> .[0;32mI (1175) ESP32: Woken Up.[0m
> .[0;31mE (1175) ESP: GPIO State: 0
> .[0m
> .[0;32mI (1175) ESP32: Woken from deep sleep (3).[0m
> .[0;31mE (1185) ESP: Previous GPIO state: 0
> .[0m
> .[0;32mI (1185) ESP: State to trigger next wakeup: 1
> .[0m
> .[0;31mE (1195) ESP: deep sleep
> .[0m

> .[0;32mI (1175) ESP32: Woken Up.[0m
> .[0;31mE (1175) ESP: GPIO State: 0
> .[0m
> .[0;32mI (1175) ESP32: Woken from deep sleep (4).[0m
> .[0;31mE (1185) ESP: Previous GPIO state: 1
> .[0m
> .[0;32mI (1185) ESP: State to trigger next wakeup: 0
> .[0m
> .[0;31mE (1195) ESP: deep sleep
> .[0m

Any advice please?

**Comment by negativekelvin** [comment]
https://github.com/espressif/esp-idf/issues/245

**Comment by johnnorbury** [comment]
Thanks!
