### ISSUE TITLE
It seems it's impossible to remove the WPA3 code from the build. (IDFGH-4103)

### ISSUE THREAD

**Issue by erikcorry** [espressif/esp-idf#5971]
Development Kit: Custom
Kit version: Custom
Module or chip used: [ESP32-WROOM-32|ESP32-WROOM-32D|ESP32-WROOM-32U|ESP32-WROVER|ESP32-WROVER-I|ESP32-WROVER-B|ESP32-WROVER-IB|ESP32-SOLO-1|ESP32-PICO-D4|ESP32]
IDF version (run git describe --tags to find it):
// v4.1-357-gc249ed646 - based off 7b7c641
Build System: CMake
Compiler version (run xtensa-esp32-elf-gcc --version to find it):
// xtensa-esp32-elf-gcc (crosstool-NG esp-2019r2) 8.2.0
Operating System: Linux
Using an IDE?: No

## Problem Description

I tried to omit the WPA3 support in v4.1, but I still got a lot of new code.

Can you really omit the WPA3 support in the Wifi, which pulls in a bunch of things from MbedTLS?  There's a config option CONFIG_ESP32_WIFI_ENABLE_WPA3_SAE, but it looks like the code bloat is controlled by CONFIG_WPA3_SAE which is hard coded and not available in sdkconfig.

**Comment by erikcorry** [comment]
[sdkconfig.zip](https://github.com/espressif/esp-idf/files/5371817/sdkconfig.zip)

**Comment by sagb2015** [comment]
@erikcorry You are right that CONFIG_WPA3_SAE cannot be controlled by CONFIG_ESP32_WIFI_ENABLE_WPA3_SAE. The purpose of CONFIG_ESP32_WIFI_ENABLE_WPA3_SAE flag is to just control additional stack size needed by WiFi task.  We are in progress of adding this control and update here once done.
