### ISSUE TITLE
esp 32s2 download helloworld.bin failed (IDFGH-4118)

### ISSUE THREAD

**Issue by simzhangbest** [espressif/esp-idf#5985]
![图片](https://user-images.githubusercontent.com/24918900/96201163-6c333500-0f8e-11eb-9ac4-8accf26b6e3d.png)

when I finish build hello world then flash bin file with COM but failed. how does it mean?

**Comment by chegewara** [comment]
`idf.py set-target esp32s2`

**Comment by projectgus** [comment]
Hi @simzhangbest,

The ESP32-S2 doesn't seem to be resetting into download mode.

* If your board has a "BOOT" button try holding it down while flashing.
* If there is a "RST" button try pressing and releasing it while also holding down the BOOT button, then run the flash step.
* If that isn't possible, try finding a way to connect GPIO0 to Ground.

If none of this is working, please provide some more details about your hardware setup.

PS @chegewara I think the target is set correctly, it says "esp32s2" in the screenshot.

**Comment by chegewara** [comment]
Ah, thats may be true. I got fooled by invalid head of packet error. Sorry.

**Comment by projectgus** [comment]
@simzhangbest Did you manage to get your board flashing OK?

**Comment by Alvin1Zhang** [comment]
@simzhangbest Thanks for reporting, would you please help share if any updates for this issue? Thanks.

**Comment by projectgus** [comment]
Closing due to lack of updates.
