### ISSUE TITLE
蓝牙死循环BUG @esp-idf/components/bt/host/bluedroid/stack/l2cap/l2c_api.c:2325 (IDFGH-4124)

### ISSUE THREAD

**Issue by leoandshaw** [espressif/esp-idf#5991]
esp-idf/components/bt/host/bluedroid/stack/l2cap/l2c_api.c:2325
原代码为：
UINT8 tcb_idx = param->conn_id;
因更正为：
UINT8 tcb_idx = GATT_GET_TCB_IDX(param->conn_id);

上述bug造成以下代码死循环。
esp-idf/components/bt/host/bluedroid/btc/profile/esp/blufi/blufi_prf.c:540 

retry:
        if (esp_ble_get_cur_sendable_packets_num(blufi_env.conn_id) > 0) {
            btc_blufi_send_notify((uint8_t *)hdr,
                ((hdr->fc & BLUFI_FC_CHECK) ?
                 hdr->data_len + sizeof(struct blufi_hdr) + 2 :
                 hdr->data_len + sizeof(struct blufi_hdr)));
        } else if(re_count > 0){
            BTC_TRACE_WARNING("%s wait to send blufi custom data\n", __func__);
            vTaskDelay(pdMS_TO_TICKS(10));
            goto retry;
        }

**Comment by xiewenxiang** [comment]
@leoandshaw 

Thansk for your feedback,  these issues all have fixed.
