### ISSUE TITLE
[TW#12612] LEDC: Docs: Range of frequency value

### ISSUE THREAD

**Issue by nkolban** [espressif/esp-idf#600]
In the LEDC API we can specify a frequency measured in Hz.  However, we don't seem to document the allowable range of the frequency (specifically the upper bound).  This issue asks for documentation amendment to include the upper bound of the frequency.

**Comment by krzychb** [comment]
Hi @nkolban, does recently updated [LED Control API Reference](https://esp-idf.readthedocs.io/en/latest/api-reference/peripherals/ledc.html#supported-range-of-frequency-and-duty-resolution) satisfy this request?

**Comment by nkolban** [comment]
Looks great my friend.
