### ISSUE TITLE
CMakeList.txt not found in project diretory /home/sui/src/esp_idf/tools (IDFGH-4145)

### ISSUE THREAD

**Issue by suijunqiang** [espressif/esp-idf#6007]
there is no CMakeList.txt under **/tools, after ./idf.py menuconfig

the message showing as below:
sui@sui-mxp:~/src/esp-idf/tools$ ./idf.py menuconfig
Executing action: menuconfig
CMakeLists.txt not found in project directory /home/sui/src/esp-idf/tools

**Comment by suijunqiang** [comment]
@suda-morris 
Yep,  it is able to generate.

Thanks, by the way may I have your Wechat or QQ please?

Thanks & Best Regards
Sui

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, feel free to reopen.
