### ISSUE TITLE
Example Request (IDFGH-4160)

### ISSUE THREAD

**Issue by hackintoshlover** [espressif/esp-idf#6022]
Any example to develop CTL_Server model for ESP32 BLE MESH

**Comment by InfiniteYuan** [comment]
[ble_mesh_ctl_hsl_server.zip](https://github.com/espressif/esp-idf/files/5509469/ble_mesh_ctl_hsl_server.zip)

This is an example about BLE Mesh Lighting CTL server model and Lighting HSL server model. Please focus mainly on usage.

Please feel free to contact me.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, feel free to reopen.
