### ISSUE TITLE
Can't TCP buffer size changed anymore by setsockopt(TCP_SNDBUF) ? (IDFGH-4185)

### ISSUE THREAD

**Issue by JB-DX** [espressif/esp-idf#6045]
[this reply from 2017](https://esp32.com/viewtopic.php?t=2378#p11231) tells that the tcp send buffer size can be set individually via  setsockopt(TCP_SNDBUF) 
I just tried it and it doesn't work because TCP_SNDBUF isn't defined anymore.
I looked into sockets.c and don't find anything either.

Has it been replaced by a different constant or has the entire functionality been removed?

**Comment by david-cermak** [comment]
@JB-DX Sorry for the late answer. 
These non-standard additions to lwip were removed back in `v3.1`, in the effort to move closer to the upstream versions (`v3.2` already uses lwip as a submodule). Current versions of IDF do not support configuring these options (send buffer, window size) per sockets.

It is possible to set this option in the project configuration menu using `CONFIG_LWIP_TCP_SND_BUF_DEFAULT` value:
```
(Top) → Component config → LWIP → TCP
              (5744) Default send buffer size
```

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, feel free to reopen.
