### ISSUE TITLE
esp_wifi_restart missing from header files (IDFGH-4190)

### ISSUE THREAD

**Issue by niemeyer** [espressif/esp-idf#6049]
Hello there,

The function esp_wifi_restart is tersely mentioned in the [docs](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/wifi.html):

> When esp_wifi_disconnect(), or esp_wifi_stop(), or esp_wifi_deinit(), or esp_wifi_restart() is called and the station is already connected to the AP.

It doesn't seem documented or included in the header files, though.

What does it do exactly and why isn't it declared in the header files?  Shouldn't it be?

Thanks.

**Comment by YouDONG-ESP** [comment]
Hi @niemeyer, this api has been removed, thanks for reporting, we will update it.
