### ISSUE TITLE
ESP32-E SecureBoot V2 (IDFGH-4191)

### ISSUE THREAD

**Issue by lajollalerner** [espressif/esp-idf#6050]
Environment V4.2beta1 running on custom hardware using the ESP32-VROOM-E (V3 chip) and on DEVkit-ESP32-E

Hi all,

I followed the manual procedures for signing and buring the efuses for V2 secure boot. I am able to verify that the signed code (both bootloader and app) are signed using the espsecure verify_signature command. my two questions are,

1. Do I use espsecure.py sign_data on the bootloader.bin and the app.bin or is there a different way to sign the bootloader.bin?

`python espsecure.py sign_data -v 2 -k testkey.pem -o bootloader_signed.bin bootloader.bin`

2. When I used espefuse.py burn_key I noticed the printout of blk2 data is reversed from the bin file produced by espsecure.py digest_rsa_public_key. Is that correct?

BIN File:
00000000:  4d 89 59 e2 d5 b3 58 4e 0b d2 64 9b 86 78 bd 60  :M.Y...XN..d..x.`
00000010:  58 6b 58 a0 0b e7 f5 c6 10 9f c2 db 72 40 df 8b  :XkX.........r@..

Output of `python espefuse.py -p COMx burn_key secure_boot pub.bin`:

Burn keys to blocks:
 - BLK2 -> [8b df 40 72 db c2 9f 10 c6 f5 e7 0b a0 58 6b 58 60 bd 78 86 9b 64 d2 0b 4e 58 b3 d5 e2 59 89 4d]
        Disabling read to key block
        Disabling write to key block

Burn keys in efuse blocksThe key block will be read and write protected (no further changes or readback)

The device serial output is:
rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:2, clock div:2
secure boot v2 enabled
Sig block 0 invalid: Image digest does not match
secure boot verification failed

Thank you,
Ian

**Comment by Alvin1Zhang** [comment]
Thanks for reporting.

**Comment by supreetd21** [comment]
Hi @lajollalerner,
Question 1: `python espsecure.py sign_data -v 2` is the right method to sign your application and bootloader binaries.

With regards to question 2, your observation is correct, using the `secure boot` parameter to `burn_key` reverses & r/w protects the digest to be programmed. The `secure boot` parameter is relevant for secure boot v1, though.

Secure boot v2 does not require the digest to be reverse programmed or to be read-protected.
Thus, for secure boot v2, you can use -
1. `python espefuse.py -p COMx burn_key BLK2 pub.bin`
2. `python espefuse.py burn_key_digest secure_boot_signing_key.pem`

Thank you for reporting, will add a helper note regarding its usage.

**Comment by lajollalerner** [comment]
Hi all,

Using the `python espefuse.py burn_key_digest secure_boot_signing_key.pem` still produced a reverse order in the espefuse summary output. I continue to get the following after using espsecure sign_data -v 2 -k mykey.pem.

```
rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:4
load:0x3fff0034,len:9348
load:0x40078000,len:16376
load:0x40080400,len:4000
entry 0x40080688
[0;32mI (29) boot: ESP-IDF v4.2-beta1-dirty 2nd stage bootloader[0m
[0;32mI (29) boot: compile time 10:02:07[0m
[0;32mI (29) boot: chip revision: 3[0m
[0;32mI (33) boot.esp32: SPI Speed      : 40MHz[0m
[0;32mI (38) boot.esp32: SPI Mode       : DIO[0m
[0;32mI (42) boot.esp32: SPI Flash Size : 8MB[0m
[0;32mI (47) boot: Enabling RNG early entropy source...[0m
[0;32mI (52) boot: Partition Table:[0m
[0;32mI (56) boot: ## Label            Usage          Type ST Offset   Length[0m
[0;32mI (63) boot:  0 nvs              WiFi data        01 02 0000b000 00002000[0m
[0;32mI (70) boot:  1 otadata          OTA data         01 00 0000d000 00002000[0m
[0;32mI (78) boot:  2 phy_init         RF data          01 01 0000f000 00001000[0m
[0;32mI (85) boot:  3 app0             OTA app          00 10 00010000 001e0000[0m
[0;32mI (93) boot:  4 app1             OTA app          00 11 001f0000 001e0000[0m
[0;32mI (100) boot:  5 spiffs           Unknown data     01 82 003d0000 00010000[0m
[0;32mI (108) boot: End of partition table[0m
[0;32mI (112) esp_image: segment 0: paddr=0x00010020 vaddr=0x3f400020 size=0x291d0 (168400) map[0m
[0;32mI (185) esp_image: segment 1: paddr=0x000391f8 vaddr=0x3ffbdb60 size=0x04440 ( 17472) load[0m
[0;32mI (193) esp_image: segment 2: paddr=0x0003d640 vaddr=0x40080000 size=0x00404 (  1028) load[0m
[0;32mI (194) esp_image: segment 3: paddr=0x0003da4c vaddr=0x40080404 size=0x025cc (  9676) load[0m
[0;32mI (205) esp_image: segment 4: paddr=0x00040020 vaddr=0x400d0020 size=0xf0430 (984112) map[0m
[0;32mI (584) esp_image: segment 5: paddr=0x00130458 vaddr=0x400829d0 size=0x1cb8c (117644) load[0m
[0;32mI (636) esp_image: segment 6: paddr=0x0014cfec vaddr=0x00000000 size=0x02fe4 ( 12260) [0m
[0;32mI (641) esp_image: Verifying image signature...[0m
[0;32mI (641) secure_boot: Secure Boot eFuse bit(ABS_DONE_1) not yet programmed.[0m
[0;32mI (646) secure_boot: Verifying with RSA-PSS...[0m
[0;32mI (672) boot: Loaded app from partition at offset 0x10000[0m
[0;32mI (672) secure_boot_v2: enabling secure boot v2...[0m
[0;32mI (672) esp_image: segment 0: paddr=0x00001020 vaddr=0x3fff0030 size=0x00004 (     4) [0m
[0;32mI (681) esp_image: segment 1: paddr=0x0000102c vaddr=0x3fff0034 size=0x02484 (  9348) [0m
[0;32mI (693) esp_image: segment 2: paddr=0x000034b8 vaddr=0x40078000 size=0x03ff8 ( 16376) [0m
[0;32mI (704) esp_image: segment 3: paddr=0x000074b8 vaddr=0x40080400 size=0x00fa0 (  4000) [0m
[0;32mI (708) esp_image: Verifying image signature...[0m
[0;32mI (713) secure_boot: Secure Boot eFuse bit(ABS_DONE_1) not yet programmed.[0m
[0;32mI (720) secure_boot: Verifying with RSA-PSS...[0m
Sig block 0 invalid: Image digest does not match
[0;31mE (729) secure_boot: Secure Boot V2 verification failed.[0m
[0;31mE (735) esp_image: Secure boot signature verification failed[0m
[0;32mI (741) esp_image: Calculating simple hash to check for corruption...[0m
[0;31mE (757) esp_image: Image hash failed - image is corrupt[0m
[0;33mW (757) esp_image: image corrupted on flash[0m
[0;31mE (759) secure_boot_v2: bootloader image appears invalid! error 8194[0m
[0;31mE (766) boot: Secure Boot v2 failed (8194)[0m
[0;31mE (771) boot: OTA app partition slot 0 is not bootable[0m
[0;32mI (777) esp_image: segment 0: paddr=0x001f0020 vaddr=0x3f400020 size=0x291d0 (168400) map[0m
[0;32mI (850) esp_image: segment 1: paddr=0x002191f8 vaddr=0x3ffbdb60 size=0x04440 ( 17472) load[0m
[0;32mI (857) esp_image: segment 2: paddr=0x0021d640 vaddr=0x40080000 size=0x00404 (  1028) load[0m
[0;32mI (858) esp_image: segment 3: paddr=0x0021da4c vaddr=0x40080404 size=0x025cc (  9676) load[0m
[0;32mI (870) esp_image: segment 4: paddr=0x00220020 vaddr=0x400d0020 size=0xf0430 (984112) map[0m
[0;32mI (1249) esp_image: segment 5: paddr=0x00310458 vaddr=0x400829d0 size=0x1cb8c (117644) load[0m
[0;32mI (1300) esp_image: segment 6: paddr=0x0032cfec vaddr=0x00000000 size=0x02fe4 ( 12260) [0m
[0;32mI (1305) esp_image: Verifying image signature...[0m
[0;32mI (1305) secure_boot: Secure Boot eFuse bit(ABS_DONE_1) not yet programmed.[0m
[0;32mI (1311) secure_boot: Verifying with RSA-PSS...[0m
[0;32mI (1337) boot: Loaded app from partition at offset 0x1f0000[0m
[0;32mI (1337) secure_boot_v2: enabling secure boot v2...[0m
[0;32mI (1337) esp_image: segment 0: paddr=0x00001020 vaddr=0x3fff0030 size=0x00004 (     4) [0m
[0;32mI (1346) esp_image: segment 1: paddr=0x0000102c vaddr=0x3fff0034 size=0x02484 (  9348) [0m
[0;32mI (1358) esp_image: segment 2: paddr=0x000034b8 vaddr=0x40078000 size=0x03ff8 ( 16376) [0m
[0;32mI (1369) esp_image: segment 3: paddr=0x000074b8 vaddr=0x40080400 size=0x00fa0 (  4000) [0m
[0;32mI (1373) esp_image: Verifying image signature...[0m
[0;32mI (1378) secure_boot: Secure Boot eFuse bit(ABS_DONE_1) not yet programmed.[0m
[0;32mI (1385) secure_boot: Verifying with RSA-PSS...[0m
Sig block 0 invalid: Image digest does not match
[0;31mE (1394) secure_boot: Secure Boot V2 verification failed.[0m
[0;31mE (1400) esp_image: Secure boot signature verification failed[0m
[0;32mI (1407) esp_image: Calculating simple hash to check for corruption...[0m
[0;31mE (1423) esp_image: Image hash failed - image is corrupt[0m
[0;33mW (1423) esp_image: image corrupted on flash[0m
[0;31mE (1425) secure_boot_v2: bootloader image appears invalid! error 8194[0m
[0;31mE (1432) boot: Secure Boot v2 failed (8194)[0m
[0;31mE (1437) boot: OTA app partition slot 1 is not bootable[0m
[0;31mE (1443) boot: No bootable app partitions in the partition table[0m
```

**Comment by lajollalerner** [comment]
Hi All,

Any update on this? I sure could use some guidance. 

Thanks,
Ian

**Comment by supreetd21** [comment]
Hi @lajollalerner,
Okay, got the issue from the logs. I could reproduce the issue on my end.

There seems to be an issue in the software bootloader handling the app verification during the first boot after manually enabled secure boot v2 on ESP32 V3. Can you check if the attached patch solves your problem? It will also be available upstream soon.

The key burnt through `python espefuse.py burn_key_digest secure_boot_signing_key.pem` has the apt order and with the patch, should not be the reason for stopping the booting of the app.

[0001-Secure-Boot-V2-Fix-an-issue-leading-to-manual-enable.txt](https://github.com/espressif/esp-idf/files/5507428/0001-Secure-Boot-V2-Fix-an-issue-leading-to-manual-enable.txt)

**Comment by 08Sahil** [comment]
Hii sir, 
can you help me in this 

sahil@theorax-vivobook:~/esp/hello_world$ espefuse -p /dev/ttyUSB0 summary
espefuse v5.3.dev3
Connecting...
Detecting chip type... ESP32

=== Run "summary" command ===
EFUSE_NAME (Block) Description  = [Meaningful Value] [Readable/Writeable] (Hex Value)
----------------------------------------------------------------------------------------
Calibration fuses:
ADC_VREF (BLOCK0)                                  True ADC reference voltage                         = 1086 R/W (0b10010)

Config fuses:
WR_DIS (BLOCK0)                                    Efuse write disable mask                           = 384 R/W (0x0180)
RD_DIS (BLOCK0)                                    Disable reading from BlOCK1-3                      = 3 R/W (0x3)
DISABLE_APP_CPU (BLOCK0)                           Disables APP CPU                                   = False R/W (0b0)
DISABLE_BT (BLOCK0)                                Disables Bluetooth                                 = False R/W (0b0)
DIS_CACHE (BLOCK0)                                 Disables cache                                     = False R/W (0b0)
CHIP_CPU_FREQ_LOW (BLOCK0)                         If set alongside EFUSE_RD_CHIP_CPU_FREQ_RATED; the = False R/W (0b0)
                                                    ESP32's max CPU frequency is rated for 160MHz. 24
                                                   0MHz otherwise                                    
CHIP_CPU_FREQ_RATED (BLOCK0)                       If set; the ESP32's maximum CPU frequency has been = True R/W (0b1)
                                                    rated                                            
BLK3_PART_RESERVE (BLOCK0)                         BLOCK3 partially served for ADC calibration data   = False R/W (0b0)
CLK8M_FREQ (BLOCK0)                                8MHz clock freq override                           = 52 R/W (0x34)
VOL_LEVEL_HP_INV (BLOCK0)                          This field stores the voltage level for CPU to run = 0 R/W (0b00)
                                                    at 240 MHz; or for flash/PSRAM to run at 80 MHz.0
                                                   x0: level 7; 0x1: level 6; 0x2: level 5; 0x3: leve
                                                   l 4. (RO)                                         
CODING_SCHEME (BLOCK0)                             Efuse variable block length scheme                
   = NONE (BLK1-3 len=256 bits) R/W (0b00)
CONSOLE_DEBUG_DISABLE (BLOCK0)                     Disable ROM BASIC interpreter fallback             = True R/W (0b1)
DISABLE_SDIO_HOST (BLOCK0)                                                                            = False R/W (0b0)
DISABLE_DL_CACHE (BLOCK0)                          Disable flash cache in UART bootloader             = True R/W (0b1)

Flash fuses:
FLASH_CRYPT_CNT (BLOCK0)                           Flash encryption is enabled if this field has an o = 7 R/W (0b0000111)
                                                   dd number of bits set                             
FLASH_CRYPT_CONFIG (BLOCK0)                        Flash encryption config (key tweak bits)           = 15 R/W (0xf)

Identity fuses:
CHIP_PACKAGE_4BIT (BLOCK0)                         Chip package identifier #4bit                      = False R/W (0b0)
CHIP_PACKAGE (BLOCK0)                              Chip package identifier                            = 1 R/W (0b001)
CHIP_VER_REV1 (BLOCK0)                             bit is set to 1 for rev1 silicon                   = True R/W (0b1)
CHIP_VER_REV2 (BLOCK0)                                                                                = False R/W (0b0)
WAFER_VERSION_MINOR (BLOCK0)                                                                          = 1 R/W (0b01)
WAFER_VERSION_MAJOR (BLOCK0)                       calc WAFER VERSION MAJOR from CHIP_VER_REV1 and CH = 1 R/W (0b001)
                                                   IP_VER_REV2 and apb_ctl_date (read only)          
PKG_VERSION (BLOCK0)                               calc Chip package = CHIP_PACKAGE_4BIT << 3 + CHIP_ = 1 R/W (0x1)
                                                   PACKAGE (read only)                               

Jtag fuses:
JTAG_DISABLE (BLOCK0)                              Disable JTAG                                       = True R/W (0b1)

Mac fuses:
MAC (BLOCK0)                                       MAC address                                       
   = fc:b4:67:62:9f:0c (CRC 0xdb OK) R/W 
MAC_CRC (BLOCK0)                                   CRC8 for MAC address                               = 219 R/W (0xdb)
MAC_VERSION (BLOCK3)                               Version of the MAC field                           = 0 R/W (0x00)
CUSTOM_MAC_CRC (BLOCK3)                            CRC8 for custom MAC address                        = 0 R/W (0x00)
CUSTOM_MAC (BLOCK3)                                Custom MAC address                                
   = 00:00:00:00:00:00 (CRC 0x00 OK) R/W 

Security fuses:
UART_DOWNLOAD_DIS (BLOCK0)                         Disable UART download mode. Valid for ESP32 V3 and = False R/W (0b0)
                                                    newer; only                                      
ABS_DONE_0 (BLOCK0)                                Secure boot V1 is enabled for bootloader image     = False R/W (0b0)
ABS_DONE_1 (BLOCK0)                                Secure boot V2 is enabled for bootloader image     = False R/W (0b0)
DISABLE_DL_ENCRYPT (BLOCK0)                        Disable flash encryption in UART bootloader        = False R/W (0b0)
DISABLE_DL_DECRYPT (BLOCK0)                        Disable flash decryption in UART bootloader        = True R/W (0b1)
KEY_STATUS (BLOCK0)                                Usage of efuse block 3 (reserved)                  = False R/W (0b0)
SECURE_VERSION (BLOCK3)                            Secure version for anti-rollback                   = 0 R/W (0x00000000)
BLOCK1 (BLOCK1)                                    Flash encryption key                              
   = ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? -/- 
BLOCK2 (BLOCK2)                                    Security boot key                                 
   = ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? ?? -/- 
BLOCK3 (BLOCK3)                                    Variable Block 3                                  
   = 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 R/W 

Spi Pad fuses:
SPI_PAD_CONFIG_HD (BLOCK0)                         read for SPI_pad_config_hd                         = 0 R/W (0b00000)
SPI_PAD_CONFIG_CLK (BLOCK0)                        Override SD_CLK pad (GPIO6/SPICLK)                 = 0 R/W (0b00000)
SPI_PAD_CONFIG_Q (BLOCK0)                          Override SD_DATA_0 pad (GPIO7/SPIQ)                = 0 R/W (0b00000)
SPI_PAD_CONFIG_D (BLOCK0)                          Override SD_DATA_1 pad (GPIO8/SPID)                = 0 R/W (0b00000)
SPI_PAD_CONFIG_CS0 (BLOCK0)                        Override SD_CMD pad (GPIO11/SPICS0)                = 0 R/W (0b00000)

Vdd fuses:
XPD_SDIO_REG (BLOCK0)                              read for XPD_SDIO_REG                              = False R/W (0b0)
XPD_SDIO_TIEH (BLOCK0)                             If XPD_SDIO_FORCE & XPD_SDIO_REG                   = 1.8V R/W (0b0)
XPD_SDIO_FORCE (BLOCK0)                            Ignore MTDI pin (GPIO12) for VDD_SDIO on reset     = False R/W (0b0)

Flash voltage (VDD_SDIO) determined by GPIO12 on reset (High for 1.8V, Low/NC for 3.3V)

**Comment by 08Sahil** [comment]
I am unable to enable secure boot V1 in my esp32 having chip version 1.1. I am following the same procedure of SV-ESP32.

**Comment by 08Sahil** [comment]
Issue resolved after performing this command

espefuse -p /dev/ttyUSB0 burn-efuse ABS_DONE_0
