### ISSUE TITLE
BG96 PPP switch between data and command mode (IDFGH-4199)

### ISSUE THREAD

**Issue by iscapla** [espressif/esp-idf#6058]
Hello,

Using example [pppos_client](https://github.com/espressif/esp-idf/tree/master/examples/protocols/pppos_client), I have some problems trying to change between data mode to command mode and them go back to data mode without finishing active connections (e.g. MQTT in the example).

Modem used is BG96 and after reading PPP Application Notes, Quectel indicates that to achieve this goal users mush follow a concrete steps. Basically a buffer of "+++" characters should be send within a time sequence. Also, it indicates that to return to data mode (after executing an AT command),  users should send "ATO\r" (in some documents appears as "ATO0\r").

Could you add this feature to the modem libraries to be compatible with your stack? Now it sends other data that mush not be there (APN configuration).

As the source code is uploaded, I'm going to work on this. If I find a "pretty" solution to doing it, I will share it.

Thanks.

**Comment by Alvin1Zhang** [comment]
Thanks for raising this feature request.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting and sorry for slow turnaround, we have a fix under internal reviewing now, and the issue will close automatically once the fix is available on GitHub, thanks.
