### ISSUE TITLE
[TW#12618] I2C module: problems with STOP operation after END

### ISSUE THREAD

**Issue by rojer** [espressif/esp-idf#606]
My code performs a long read operation in several READ/END, READ/END, ..., READ/STOP operations.
It all works as expected, until the last batch, which ends in STOP, where I2C master behaves weirdly: it gets stuck, generating SCL continuously.
 
Here's a logic capture of the operation: 
![screenshot from 2017-05-15 14-43-07](https://cloud.githubusercontent.com/assets/531307/26056182/d5f5e33e-397c-11e7-86f9-2abe68c59fe6.png)
Input1 is SDA, Input2 is SCL, Input3 is a debugging aid: it is toggled before command pipeline is submitted for execution (`ctr.trans_start` is set) and after we are done waiting for completion (either one of the terminal interrupts are asserted or we do 10000 iterations).  
The operation involves reading 34 bytes in 5 transactions:
1) Start, address 0x60, for reading, read 1 byte (which is the length of the packet): 
![screenshot from 2017-05-15 14-45-16](https://cloud.githubusercontent.com/assets/531307/26056232/224c6ece-397d-11e7-8a90-e19611e2de6e.png)
2) Read 10 bytes, continue (ends with an END opcode): 
![screenshot from 2017-05-15 14-46-13](https://cloud.githubusercontent.com/assets/531307/26056280/51037de8-397d-11e7-9e10-b28395f3d931.png)
3) Same as 2 (read 10, END): 
![screenshot from 2017-05-15 14-47-49](https://cloud.githubusercontent.com/assets/531307/26056325/81841fcc-397d-11e7-8573-2fc659b72d3c.png)
4) One more: 
![screenshot from 2017-05-15 14-48-31](https://cloud.githubusercontent.com/assets/531307/26056341/94817c28-397d-11e7-9b4c-b536161a8845.png)
5) And final transaction, which is going to be the last one, consists of the following op pipeline:
```
esp32_i2c_exec           00001003 2
esp32_i2c_exec           00001401 2
esp32_i2c_exec           00001800 3
```
which is READ 3 bytes with ack, then READ 1 with a NAK (as per the spec, final byte should be NAK'd by the master) and a STOP. However, it does not go as planned and instead i see this on the logic analyzer: 
![screenshot from 2017-05-15 14-51-12](https://cloud.githubusercontent.com/assets/531307/26056421/f40df144-397d-11e7-9b14-9a166146dc35.png)

This is bizarre. a START condition, followed by continuous SCL pulsing.
The execution of the commands continues ad infinitum, however, my waiting loop terminates after 10000 iterations and i see this:
```
esp32_i2c_exec         10000 loops, ok? 0, ints 0x00000242 -> 0x00000242, tx_fifo 0/-1 rx_fifo 0/4, status 0x33000010
esp32_i2c_exec           00001003 2
esp32_i2c_exec           00001401 2
esp32_i2c_exec           00001800 3
```
no commands completed, nothing received.

i found a workaround for this: do not end the sequence with STOP, finish with END, and then execute a STOP as a single-command pipeline. strangely, i also had to remove the "read with NAK" operation, because is also somehow confuses the FSM.
so, for final step i have tried these pipelines:
a) 1003, 1401, 1800 -> SCL stuck
b) 1003, 1401, 2000 -> SCL stuck
c) 1004, 1800 -> SCL stuck
d) 1004, 2000 -> ok, then in separate transaction 1800 -> ok
FWIW, this last option produces the expected result on the analyzer: 
![READ 4](https://cloud.githubusercontent.com/assets/531307/26057417/4612f2e2-3982-11e7-925c-c9674b17750e.png) and 
![STOP](https://cloud.githubusercontent.com/assets/531307/26057441/628a76ac-3982-11e7-81b8-200f65c5c941.png)

**Comment by rojer** [comment]
fwiw, i'm attaching full capture file which can be examined with the [SIGMA software](http://www.asix.net/dwnld_sigma-omega.htm)

[stop_bug.stf.zip](https://github.com/espressif/esp-idf/files/1001338/stop_bug.stf.zip)

**Comment by rojer** [comment]
happens on write too

**Comment by kewalmshah** [comment]
Hi @rojer Was just going through your issue! Can I have a look at your test code please ? It seems to have some changes in i2c.c driver file, is it ?

**Comment by rojer** [comment]
our I2C driver is completely different and does not use IDF's i2c.c in any way. [here](https://github.com/cesanta/mongoose-os/blob/05b136d73abb58b461794380c2f31d1219ee01d9/fw/platforms/esp32/src/esp32_i2c_master.c) it is.

**Comment by PerMalmberg** [comment]
+1 for this. I've seen the same thing symptom, though I haven't been able to determine why it happens.

**Comment by stickbreaker** [comment]
@PerMalmberg I have rewritten the I2C driver for the arduino-esp32. [Here](https://github.com/stickbreaker/arduino-esp32) It solves this problem.

I believe you are running into a querk of the i2c Statemachine.  When you used the `END` command, you cannot reuse that position when you refill the queue.  It has to remain an `END` command.  Also, it is illegal to have a `START` precede a `END`. my I2C rewrite uses an ISR to service the StateMachine(SM), the fillCmdQueue() function enforces these rules.  

@rojer Your original problem can be explained if during your last fill of the Command[] queue, you reused the `END` entry with a `STOP`.  It is easy to duplicate.

Chuck.

**Comment by rojer** [comment]
@stickbreaker thanks Chuck. i actually noticed updated language in the latest update to the TRM about clearing the end ints and also not reusing the position previosuly used by the end command. i made a note to revisit my driver, but haven't got around to it yet. it's good to get a confirmation that the issue can be solved, thanks!

**Comment by stickbreaker** [comment]
What is TRM?  I am from the Arduino fork.

Chuck.

**Comment by rojer** [comment]
[ESP32 techinical reference manual](http://espressif.com/sites/default/files/documentation/esp32_technical_reference_manual_en.pdf).
latest update was about I2C and mentions this quirk.

**Comment by stickbreaker** [comment]
Thanks

Chuck.

**Comment by rojer** [comment]
ok, i'm going to close this issue, since the cause and workaround is now known.

**Comment by stickbreaker** [comment]
Wow, they really butchered it.  I read a previous version, this version has changed the definitions for the interrupt registers, It looks like they are removing all references to FIFO.

The Fifo_conf register only describe NON fifo usage.
And the interrupt control registers int_* omit rx_fifo_Full,tx_fifo_empty,rx_fifo_ovf, slave_tran_comp

Are the deleting the Fifo from the hardware?

Chuck.
