### ISSUE TITLE
strange link error in Windows: xtensa-esp32-elf-g++.exe: error: CreateProcess: No such file or directory (IDFGH-4202)

### ISSUE THREAD

**Issue by versaloon** [espressif/esp-idf#6061]
##  Environment

- Development Kit:      [none, using qemu, no hardware]
- Kit version (for WroverKit/PicoKit/DevKitC): [none]
- Module or chip used:  [ESP32]
- IDF version (run ``git describe --tags`` to find it):
    v4.3-dev-1561-g357a27760
- Build System:         [CMake]
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it):
    xtensa-esp32-elf-gcc (crosstool-NG esp-2020r3) 8.4.0
- Operating System:     [Windows]
- (Windows only) environment type: [ESP Command Prompt&Plain Command Prompt].
- Using an IDE?: [No]
- Power Supply:         [None]

## Problem Description

Compiles OK under Ubuntu(wsl2), but failed on windows command line.
below is the error log:
[1284/1288] Linking CXX executable hello-world.elf
FAILED: hello-world.elf
cmd.exe /C "cd . && C:\Users\SimonQian\.espressif\tools\xtensa-esp32-elf\esp-2020r3-8.4.0\xtensa-esp32-elf\bin\xtensa-esp32-elf-g++.exe  -mlongcalls -Wno-frame-address   @CMakeFiles\hello-world.elf.rsp  -o hello-world.elf  && cd ."
xtensa-esp32-elf-g++.exe: error: CreateProcess: No such file or directory

if I remove some unused .o files in CMakeFiles\hello-world.elf.rsp, link will pass.

### Expected Behavior

Link OK.

### Actual Behavior

Link failed

### Steps to reproduce

1. clone vsf(I'm porting vsf to esp32):
git clone https://github.com/vsfteam/vsf.git
2. set VSF_PATH
set VSF_PATH=PATH_TO_VSF_CLONED
3. extract esp_vsf_demo I provided
4. cd esp_vsf_demo
5. mkdir build
6. cd build
7. cmake -G Ninja ..
8. cmake --build .

## Other items if possible

- [ ] sdkconfig file (attach the sdkconfig file from your project folder)
- [ ] elf file in the ``build`` folder (**note this may contain all the code details and symbols of your project.**)
- [ ] coredump (This provides stacks of tasks.)

**Comment by versaloon** [comment]
[esp_vsf_demo.zip](https://github.com/espressif/esp-idf/files/5477195/esp_vsf_demo.zip)
This is the esp_vsf_demo I mentioned.

**Comment by versaloon** [comment]
I switched to wsl2 Ubuntu, everything runs OK(and much more faster) now.

**Comment by georgik** [comment]
Hi @versaloon . Thank you for reporting the issue and we're sorry to responding so late to the issue with ESP-IDF 4.4 (master).

I was trying to replicate the behavior on Windows and Ubuntu with provided file, but it failed with error like:
```
CMake Error at C:/Users/georgik/Desktop/esp-idf/tools/cmake/component.cmake:305 (message):
  Include directory 'C:/projects/tmp/vsf/source/vsf' is not a directory.
Call Stack (most recent call first):
  C:/Users/georgik/Desktop/esp-idf/tools/cmake/component.cmake:485 (__component_add_include_dirs)
  C:/projects/tmp/vsf/CMakeLists.txt:1 (idf_component_register)
```

vsf source code in latest commit does not contain `source/vsf`.

It seems that project https://github.com/vsfteam/vsf moved quite a lot. Is the esp_vsf_demo source code still relevant?

**Comment by versaloon** [comment]
yes, there are changes in vsf, and esp32 project is not updated.
esp32 support in vsf is not maintained now, so just ignore the issue.
