### ISSUE TITLE
section placement error while using __attribute__((section("xxxx"))) to decorate functions (IDFGH-4203)

### ISSUE THREAD

**Issue by versaloon** [espressif/esp-idf#6062]
## Environment

- Development Kit:      [none]
- Kit version (for WroverKit/PicoKit/DevKitC): [none]
- Module or chip used:  [ESP32]
- IDF version (run ``git describe --tags`` to find it):
    v4.3-dev-1561-g357a27760
- Build System:         [CMake]
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it):
    xtensa-esp32-elf-gcc (crosstool-NG esp-2020r3) 8.4.0
- Operating System:     [Windows]
- (Windows only) environment type: [ESP Command Prompt].
- Using an IDE?: [No]
- Power Supply:         [none]

## Problem Description

while using __attribute__((section("xxxx"))) to decorate functions, section placement will fail with log like:
A fatal error occurred: Segment loaded at 0x400e379c lands in same 64KB flash mapping as segment loaded at 0x400e3788. Can't generate binary. Suggest changing linker script or ELF to merge sections.
ninja: build stopped: subcommand failed.

### Code to reproduce this issue

```c
#include <stdio.h>
#include "sdkconfig.h"
#include "freertos/FreeRTOS.h"

__attribute__((section("text.test_print_info")))
void test_print_info(void)
{
    esp_chip_info_t chip_info;
    esp_chip_info(&chip_info);
    printf("This is %s chip with %d CPU cores, WiFi%s%s, ",
            CONFIG_IDF_TARGET,
            chip_info.cores,
            (chip_info.features & CHIP_FEATURE_BT) ? "/BT" : "",
            (chip_info.features & CHIP_FEATURE_BLE) ? "/BLE" : "");
}

__attribute__((section("text.test_restart")))
void test_restart(void)
{
    fflush(stdout);
    esp_restart();
}

void app_main(void)
{
    test_print_info();
    test_restart();
}
```

## Debug Logs

related sections from xtensa-esp32-elf-objdump
12 text.test_print_info.literal 00000014  400e3788  400e3788  00028788  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, CODE
 13 text.test_restart.literal 00000004  400e379c  400e379c  0002879c  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, CODE
 14 text.test_print_info 00000033  400e37a0  400e37a0  000287a0  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, CODE
 15 text.test_restart 00000011  400e37d4  400e37d4  000287d4  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, CODE

## Other items if possible

- [ ] sdkconfig file (attach the sdkconfig file from your project folder)
- [ ] elf file in the ``build`` folder (**note this may contain all the code details and symbols of your project.**)
- [ ] coredump (This provides stacks of tasks.)

**Comment by igrr** [comment]
@versaloon The default project linker script only catches `.text` and `.text.*`, so the section `text.test_print_info` is probably not getting placed into the .flash_text section as it should be. Can you try changing the section name to `.text.test_print_info`?

**Comment by versaloon** [comment]
> @versaloon The default project linker script only catches `.text` and `.text.*`, so the section `text.test_print_info` is probably not getting placed into the .flash_text section as it should be. Can you try changing the section name to `.text.test_print_info`?

The section names are `.text.test_print_info` and "text.test_restart", and the according to the section list, the address is 0x400exxxx, is the address in flash? I'm new to esp32.

**Comment by versaloon** [comment]
> @versaloon The default project linker script only catches `.text` and `.text.*`, so the section `text.test_print_info` is probably not getting placed into the .flash_text section as it should be. Can you try changing the section name to `.text.test_print_info`?

Thanks, it works.

**Comment by igrr** [comment]
There is a "Close issue" button just right below the comment field. I'll close this one for you.
