### ISSUE TITLE
Blinds (servo or stepper motors) (IDFGH-4215)

### ISSUE THREAD

**Issue by exrector** [espressif/esp-idf#6074]
Hello dear developers!  Can I ask you to make examples on servo or stepper motors control?  Ideally, these are blinds.  PLEASE!  There is no information on the internet.  It is very difficult for a beginner to understand the examples of other platforms (arduino, esp8266 etc)

**Comment by costaud** [comment]
Maybe you can refer to this: <br>
https://github.com/espressif/esp-iot-solution/tree/master/components/motor/servo/servo_motor

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, feel free to reopen.
