### ISSUE TITLE
Bluetooth Classic sending packet loss at "high" throughput (IDFGH-4225)

### ISSUE THREAD

**Issue by francis2tm** [espressif/esp-idf#6084]
## Environment

- Development Kit:      [ESP32-DevKitC]
- Kit version (v3]
- Module or chip used:  [ESP32-WROOM-32]
- IDF version (run ``git describe --tags`` to find it):
    v4.3-dev-1720-g494a124d9
- Build System:         [idf.py]
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it):
    xtensa-esp32-elf-gcc (crosstool-NG esp-2020r3) 8.4.0
- Operating System:     [Linux]
- Power Supply:         [USB]

## Problem Description

I'm using the esp_spp_write() function to send data over bluetooth classic. My application requires esp to send at most 8bytes every 1ms -> throughput of 64kbps (less than what esp32 is capable of). I noticed that when I send data every 1ms, I get packets lost in the receiver side, a laptop or a smartphone (tried with both of them), I know this because I put a sequence number in every frame I send. I think it's a problem with the bt API, because in the ESP side I check if the sequence number is correct in every frame that has been sent and it never accuses a sequence number error, only at the receiver side.
I've tried reducing the amount of bytes per frame to 3bytes, the incorrect behavior remains. If I send data every 10ms or 100ms, I don't have frames lost.
The way I send data is this: I accumulate frames to be sent in a buffer and every time ESP_SPP_WRITE_EVT happens, it sends the data existing in the buffer (in order to prevent congestion). The buffers never overflow of data, the bt sends can keep up with the data generation.

I'm using the latest esp-idf. I tried using using another board too, with the most recent esp32-wroom-32 SoC, problem remains.

## Other items if possible
[sdkconfig.zip](https://github.com/espressif/esp-idf/files/5504858/sdkconfig.zip)

**Comment by Alvin1Zhang** [comment]
Thanks for reporting.

**Comment by Wth-Esp** [comment]
Hi @francis2tm,

We have optimized the spp flow control, but I'm not sure it can solve your issue. And here are my suggestions to help us with solving this issue:

1. Could you please provide your simplified demo? This would help us with reproducing and debugging the issue.
2. Please try the SPP VFS mode in IDF first to see whether the issue is still there. This is very helpful, will help us to diagnose the flow control side codes of SPP common mode.
3. Please pay attention to the  `ESP_SPP_CONG_EVT` event add some log to help us to diagnose the issue.

Thanks
Weitianhua

**Comment by Alvin1Zhang** [comment]
@francis2tm Thanks for reporting, would you please help share if any updates for this issue? Thanks.

**Comment by francis2tm** [comment]
Yes, I'm having esp_spp_cb: ESP_SPP_CONG_EVT when the packets are lost

**Comment by francis2tm** [comment]
@Alvin1Zhang  @Wth-Esp Any news?

**Comment by francis2tm** [comment]
Okay I have updates.
Now I prevented congestion by only making esp_spp_write when the previous write has been finished (ESP_SPP_WRITE_EVT) and when param->cong.cong == 0 (in ESP_SPP_CONG_EVT). Now, it works well with 8kBytes/s throughput for some 200s. Then, my production buffers overflow-> meaning, the bluetooth sends can't keep up with the data production (8kBytes/s).

`case ESP_SPP_CONG_EVT:                          //connection congestion status changed
        if(param->cong.cong == 0 && cong_flag == 2){
            cong_flag = 0;
        }
        break;
    case ESP_SPP_WRITE_EVT:                         //write operation completed (quando um envio foi completado)
        if(param->write.cong == 0){
            cong_flag = 0;
        }else{
            cong_flag = 2;
        }
        break;`

And every 1ms, I check: 
`if(!cong_flag){
                sendData();
            }`

**Comment by Wth-Esp** [comment]
Hi @francis2tm,

4Mbps is the maximum baud rate via UART port to BT controller not the baud rate of BREDR. The BREDR transmission bandwidth is generally 1Mbps. The theoretical maximum peak value is 3 Mbps, and this value cannot be reached continuously and stably. From our test between two ESP32-WROVER-B DevKit, the throughput of  SPP is about 1900 kbps.

Could you provide your demo for us to retest the real throughput?

Thanks
Weitianhua

**Comment by francis2tm** [comment]
[Embedded.zip](https://github.com/espressif/esp-idf/files/5662092/Embedded.zip)
Here is the demo!

**Comment by boblane1** [comment]
Hi @francis2tm, 
1. I suggest you to reduce the priority of task 'initBt', because the max priority of ESP32 is 25. And also, you can raise the task 'acqAdc1Task' properly.

2. I recommend you to use SPP vfs write in ‘acqAdc1Task’, and it will make your application code much easier. You can refer the demo in https://github.com/espressif/esp-idf/tree/master/examples/bluetooth/bluedroid/classic_bt/bt_spp_vfs_initiator. However, if you don't want to use this mode, I offer you some suggestion.

**Comment by francis2tm** [comment]
Hey @boblane1 ,
Thanks for your reply.
a) Isn't VFS less efficient? Since you have an extra layer for the virtual file system which increases overhead?
b) Isn't lists/queues also less efficient than the 2 fixed sized arrays? Because that way I always need to alloc/free memory in every iteration, which also seems to increase the overheads.

**Comment by boblane1** [comment]
Hi @francis2tm,
a) Yes, VFS will be less efficient, but you don't need to care about the flow control.
b) Lists/queues will increase the overheads, but it is convenient to resend the failed written packet.

If it is unnecessary to send ADC data every 1ms, you can accumulate the data as much as ESP_SPP_MAX_MTU to send. It is not recommended sending a small amount of data at high frequency. The flow control is not affected by the amount of data but also the number of packets.

**Comment by francis2tm** [comment]
> Hi @francis2tm,
> a) Yes, VFS will be less efficient, but you don't need to care about the flow control.
> b) Lists/queues will increase the overheads, but it is convenient to resend the failed written packet.
> 
> If it is unnecessary to send ADC data every 1ms, you can accumulate the data as much as ESP_SPP_MAX_MTU to send. It is not recommended sending a small amount of data at high frequency. The flow control is not affected by the amount of data but also the number of packets.

Okay I see, But I think by adding your suggestions my flow control will be correct right?
Because I really want to achieve the most bluetooth throughput possible in esp-wroom-32. That being said, is my approach the best one to achieve the best throughput possible in esp-wroom-32?

Thanks for your help

**Comment by boblane1** [comment]
Hi @francis2tm,

If you want to achieve the most Bluetooth throughput possible in esp-wroom-32, I think you can send much more data(but not exceed ESP_SPP_MAX_MTU) when the spp is not congest. For example, you can send 80bytes every 10ms rather than 8 bytes every 1ms.

**Comment by francis2tm** [comment]
Thanks @boblane1 , your suggestions worked!
