### ISSUE TITLE
examples/protocols/smtp_client (IDFGH-4240)

### ISSUE THREAD

**Issue by nopnop2002** [espressif/esp-idf#6098]
## Environment

	freeRTOS version:V8.2.0
	NEWLIB version:3.0.0
	lwIP version:2-1-3-0
	ESP-IDF version:v4.3-dev-1197-g8bc19ba89

## Problem Description

Incorrect email header.

Incorrect:
There is no line feed code between the header and the body.
Incorrect Contet-Type.

```
--XYZabcd1234
Content-Type: image/image/png;name=esp_logo.png
Content-Transfer-Encoding: base64
Content-Disposition:attachment;filename="esp_logo.png"
iVBORw0KGgoAAAANSUhEUgAAARgAAAEYCAIAAAAI7H7bAAB4yElEQVR4nOxdBWBU9R9/eZ3rYME2YrSCKAYWBhio2GBgI4piYf7FwMZWsFAMBEVsRVQUW0SlB2OM
```

Correct:

```
--XYZabcd1234
Content-Type: image/png;name=esp_logo.png
Content-Transfer-Encoding: base64
Content-Disposition:attachment;filename="esp_logo.png"

iVBORw0KGgoAAAANSUhEUgAAARgAAAEYCAIAAAAI7H7bAAB4yElEQVR4nOxdBWBU9R9/eZ3rYME2YrSCKAYWBhio2GBgI4piYf7FwMZWsFAMBEVsRVQUW0SlB2OM
```

**Comment by Alvin1Zhang** [comment]
@nopnop2002 Thanks for reporting and sorry for late reply, we have a fix under internal reviewing and this issue will be closed automatically once the fix is available on GitHub. Thanks.
