### ISSUE TITLE
FreeRTOS/coreMQTT Support (IDFGH-4261)

### ISSUE THREAD

**Issue by AshUK** [espressif/esp-idf#6112]
Currently, the MQTT component makes use of the esp-mqtt library supported and maintained by espressif. Although this is a feature-rich library it does lack the many of qualities of CoreMQTT such as the extensive unit test code coverage and code quality.

Now that FreeRTOS/coreMQTT has reached released will there be planned support or an option to switch out the current component?

FreeRTOS/coreMQTT#98

**Comment by Alvin1Zhang** [comment]
Thanks for raising the feature request.

**Comment by lhespress** [comment]
@AshUK 
Please replace **esp-idf/components/mqtt** and **esp-idf/examples/protocols/mqtt/ssl** to the attached files.

[FreeRTOS:coreMQTT.zip](https://github.com/espressif/esp-idf/files/5629126/FreeRTOS.coreMQTT.zip)

**Comment by AshUK** [comment]
@lhespress Thanks very much for this port, I really was not expecting a response so soon.

I have tested and it appears to be working as expected. 

Free heap during a active MQTTS connection:
FreeRTOS=198068
ESP=192672

A saving of 5396 bytes seems promising.

**Comment by KaeLL** [comment]
@AshUK will you submit a PR?

**Comment by AshUK** [comment]
@KaeLL It wouldn't be my place to submit the PR as @lhespress has done all work.

@lhespress Do you know if there there is a plan to add this to the IDF ?

**Comment by lhespress** [comment]
@AshUK 

I have submit a MR for reviewing.

**Comment by lhespress** [comment]
@AshUK Hi, freertos coremqtt has been pushed on github, please check https://github.com/espressif/esp-freertos-coremqtt

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, feel free to reopen.
