### ISSUE TITLE
Missing support for xTaskGetIdleRunTimeCounter() (IDFGH-4264)

### ISSUE THREAD

**Issue by drws** [espressif/esp-idf#6115]
It seems the esp-idf does not support FreeRTOS's xTaskGetIdleRunTimeCounter() function. It would probably need some dual-core adaptation or just return the idle task stats for the core it runs on. Are there any other reasons this particular function support is missing?

Alternatively, the vTaskGetRunTimeStats() can provide the relevant information, but it populates a large buffer which needs to be parsed afterwards, which seems like a bulky solution to obtain a single value (or two).

**Comment by Alvin1Zhang** [comment]
Thanks for raising this feature.

**Comment by Dazza0** [comment]
@drws ESP-IDF updated to FreeRTOS 10 as of commit a3c90bf.  `xTaskGetIdleRunTimeCounter()` should be supported (defined as a macro to `ulTaskGetIdleRunTimeCounter()`.
