### ISSUE TITLE
MQTT Connection Failed after changing Azure IoT Hub Certificate (IDFGH-4282)

### ISSUE THREAD

**Issue by eduhash-kimyk** [espressif/esp-idf#6129]
## Environment

Module or chip used : ESP32-WROOM-32U
IDF version : v4.0-dev-1443-g39f090a4f-dirty
Build System : Make
Compiler version : 5.2.0
Operating System : Linux
Using an IDE? : No
Power Supply : USB, external 5V

## Problem Description

Hi all, we're using MQTT connection with MS Azure IoT Hub from last year.
From last week, our firmware doesn't connected to IoT Hub with CORRUPT HEAP dump.
1. We heard that IoT Hub's server certificate was changed last week like below link :
   https://techcommunity.microsoft.com/t5/internet-of-things/azure-iot-tls-changes-are-coming-and-why-you-should-care/ba-p/1658456
2. Before changing IoT Hub's certificate, there's no pb to connect with firmware & IoT Hub.
3. MS guaranteed that our certificate file (refer to below link) is no problem to use
   https://cacerts.digicert.com/BaltimoreCyberTrustRoot.crt.pem
4. When we lookup device log with debug mode, we found that CORRUPT HEAP occurred in 'ServerHello' step.
   ( refer to Debug Logs )
5. Our connection flow (in firmware source) describes in 'Code to reproduce this issue' Section

We tried to find similar issues on here, but we cannot found suitable solution.
Could you help me for our issue?

### Expected Behavior
MQTT Connected with MS Azure IoT Hub without any errors

### Actual Behavior
Connection failed with CORRUPT HEAP
(Refer to Device Log)

### Code to reproduce this issue
static void mqtt_app_start(void)
{

    const esp_mqtt_client_config_t mqtt_cfg = {
      .uri = mqtt_url,
      .username = username,
      .client_id  = clientid,
      .password = (char *)sasTokens,
      .cert_pem = (const char *)iot_openit_pem_start,
    };   

    ESP_LOGI(TAG, "[APP] Free memory: %d bytes", esp_get_free_heap_size());
     client = esp_mqtt_client_init(&mqtt_cfg);
    esp_mqtt_client_register_event(client, ESP_EVENT_ANY_ID, mqtt_event_handler, client);
    esp_mqtt_client_start(client); 
};

## Debug Logs

I (11644) eth_example: Ethernet Got IP Address
I (11644) eth_example: ~~~~~~~~~~~
I (11644) eth_example: ETHIP:192.168.XX.XX
I (11654) eth_example: ETHMASK:255.255.255.0
I (11654) eth_example: ETHGW:192.168.XX.XX
I (11664) eth_example: ~~~~~~~~~~~
I (11664) MQTTS: The current date/time in  is: Mon Nov 16 15:12:37 2020
start_sas
 key > (hidden)
decodedBytes(hex)[32] >>> (hidden)
 total_time_sec 1605507157
 key_exp > (hidden)
1606111957
input >>> (hidden)
1606111957
input >>> 64
sha256_HMACBytes >>> (hidden)
hash[44] >> (hidden)
sasTokens >> SharedAccessSignature sr=(hidden)
 I (11734) example: Starting server on port: 80 !!!
W (11744) httpd: httpd_server_init: error enabling SO_REUSEADDR (109)

.... skip (Web Server Log) ...

I (12434) native_ota: SHA-256 for current firmware: : (hidden)
I (12444) MQTTS: [APP] Startup..
I (12444) MQTTS: [APP] Free memory: 104664 bytes
I (12444) MQTTS: [APP] IDF version: v4.0-dev-1443-g39f090a4f-dirty
I (12454) MQTTS: [APP] Free memory: 104724 bytes
D (12464) MQTT_CLIENT: MQTT client_id=(hidden)
D (12464) event: created event loop 0x3ffe6990
D (12474) MQTT_CLIENT: Core selection disabled
D (12474) event: running post MQTT_EVENTS:7 with handler 0x400d9dac on loop 0x3ffe6990
D (12484) httpd: httpd_thread: web server started
D (12484) httpd: httpd_server: doing select maxfd+1 = 56
D (12494) MQTTS: Event dispatched from event loop base=MQTT_EVENTS, event_id=7
I (12504) MQTTS: Other event id:7
I (12504) MQTTS: [mqtt_event_handler_cb] Free memory: 88304 bytes
D (12514) esp-tls: host:(hidden): strlen 30
D (12644) esp-tls: handshake in progress...
I (12654) mbedtls: ssl_tls.c:8084 => handshake

I (12654) mbedtls: ssl_cli.c:3510 client state: 0

I (12654) mbedtls: ssl_tls.c:2755 => flush output

I (12654) mbedtls: ssl_tls.c:2767 <= flush output

I (12664) mbedtls: ssl_cli.c:3510 client state: 1

I (12674) mbedtls: ssl_tls.c:2755 => flush output

I (12674) mbedtls: ssl_tls.c:2767 <= flush output

I (12684) mbedtls: ssl_cli.c:774 => write client hello

D (12684) mbedtls: ssl_cli.c:812 client hello, max version: [3:3]

D (12694) mbedtls: ssl_cli.c:703 client hello, current time: 1605507159

D (12704) mbedtls: ssl_cli.c:821 dumping 'client hello, random bytes' (32 bytes)

D (12704) mbedtls: ssl_cli.c:821 0000:  5f b2 18 57 35 28 8b c5 8d ee 96 ee 7d e6 02 06  _..W5(......}...

D (12714) mbedtls: ssl_cli.c:821 0010:  44 f0 b5 8e 31 de b8 7e 82 a1 9d 33 b8 7f ca 8c  D...1..~...3....

D (12724) mbedtls: ssl_cli.c:874 client hello, session id len.: 0

D (12734) mbedtls: ssl_cli.c:875 dumping 'client hello, session id' (0 bytes)

D (12744) mbedtls: ssl_cli.c:922 client hello, add ciphersuite: c02c

D (12744) mbedtls: ssl_cli.c:922 client hello, add ciphersuite: c030

D (12754) mbedtls: ssl_cli.c:922 client hello, add ciphersuite: 009f

D (12764) mbedtls: ssl_cli.c:922 client hello, add ciphersuite: c0ad

D (12764) mbedtls: ssl_cli.c:922 client hello, add ciphersuite: c09f

D (12774) mbedtls: ssl_cli.c:922 client hello, add ciphersuite: c024

D (12784) mbedtls: ssl_cli.c:922 client hello, add ciphersuite: c028

D (12784) mbedtls: ssl_cli.c:922 client hello, add ciphersuite: 006b

D (12794) mbedtls: ssl_cli.c:922 client hello, add ciphersuite: c00a

D (12804) mbedtls: ssl_cli.c:922 client hello, add ciphersuite: c014

D (12804) mbedtls: ssl_cli.c:922 client hello, add ciphersuite: 0039

D (12814) mbedtls: ssl_cli.c:922 client hello, add ciphersuite: c0af

D (12824) mbedtls: ssl_cli.c:922 client hello, add ciphersuite: c0a3

D (12824) mbedtls: ssl_cli.c:922 client hello, add ciphersuite: c02b

D (12834) mbedtls: ssl_cli.c:922 client hello, add ciphersuite: c02f

D (12844) mbedtls: ssl_cli.c:922 client hello, add ciphersuite: 009e

D (12844) mbedtls: ssl_cli.c:922 client hello, add ciphersuite: c0ac

D (12854) mbedtls: ssl_cli.c:922 client hello, add ciphersuite: c09e

D (12864) mbedtls: ssl_cli.c:922 client hello, add ciphersuite: c023

D (12864) mbedtls: ssl_cli.c:922 client hello, add ciphersuite: c027

D (12874) mbedtls: ssl_cli.c:922 client hello, add ciphersuite: 0067

D (12884) mbedtls: ssl_cli.c:922 client hello, add ciphersuite: c009

D (12884) mbedtls: ssl_cli.c:922 client hello, add ciphersuite: c013

D (12894) mbedtls: ssl_cli.c:922 client hello, add ciphersuite: 0033

D (12904) mbedtls: ssl_cli.c:922 client hello, add ciphersuite: c0ae

D (12904) mbedtls: ssl_cli.c:922 client hello, add ciphersuite: c0a2

D (12914) mbedtls: ssl_cli.c:922 client hello, add ciphersuite: 009d

D (12914) mbedtls: ssl_cli.c:922 client hello, add ciphersuite: c09d

D (12924) mbedtls: ssl_cli.c:922 client hello, add ciphersuite: 003d

D (12934) mbedtls: ssl_cli.c:922 client hello, add ciphersuite: 0035

D (12934) mbedtls: ssl_cli.c:922 client hello, add ciphersuite: c032

D (12944) mbedtls: ssl_cli.c:922 client hello, add ciphersuite: c02a

D (12954) mbedtls: ssl_cli.c:922 client hello, add ciphersuite: c00f

D (12954) mbedtls: ssl_cli.c:922 client hello, add ciphersuite: c02e

D (12964) mbedtls: ssl_cli.c:922 client hello, add ciphersuite: c026

D (12974) mbedtls: ssl_cli.c:922 client hello, add ciphersuite: c005

D (12974) mbedtls: ssl_cli.c:922 client hello, add ciphersuite: c0a1

D (12984) mbedtls: ssl_cli.c:922 client hello, add ciphersuite: 009c

D (12994) mbedtls: ssl_cli.c:922 client hello, add ciphersuite: c09c

D (12994) mbedtls: ssl_cli.c:922 client hello, add ciphersuite: 003c

D (13004) mbedtls: ssl_cli.c:922 client hello, add ciphersuite: 002f

D (13014) mbedtls: ssl_cli.c:922 client hello, add ciphersuite: c031

D (13014) mbedtls: ssl_cli.c:922 client hello, add ciphersuite: c029

D (13024) mbedtls: ssl_cli.c:922 client hello, add ciphersuite: c00e

D (13034) mbedtls: ssl_cli.c:922 client hello, add ciphersuite: c02d

D (13034) mbedtls: ssl_cli.c:922 client hello, add ciphersuite: c025

D (13044) mbedtls: ssl_cli.c:922 client hello, add ciphersuite: c004

D (13054) mbedtls: ssl_cli.c:922 client hello, add ciphersuite: c0a0

D (13054) mbedtls: ssl_cli.c:934 client hello, got 48 ciphersuites (excluding SCSVs)

D (13064) mbedtls: ssl_cli.c:943 adding EMPTY_RENEGOTIATION_INFO_SCSV

D (13074) mbedtls: ssl_cli.c:992 client hello, compress len.: 1

D (13074) mbedtls: ssl_cli.c:994 client hello, compress alg.: 0

D (13084) mbedtls: ssl_cli.c:69 client hello, adding server name extension: (hidden)

D (13094) mbedtls: ssl_cli.c:186 client hello, adding signature_algorithms extension

D (13104) mbedtls: ssl_cli.c:271 client hello, adding supported_elliptic_curves extension

D (13114) mbedtls: ssl_cli.c:336 client hello, adding supported_point_formats extension

D (13124) mbedtls: ssl_cli.c:518 client hello, adding encrypt_then_mac extension

D (13124) mbedtls: ssl_cli.c:552 client hello, adding extended_master_secret extension

D (13134) mbedtls: ssl_cli.c:585 client hello, adding session ticket extension

D (13144) mbedtls: ssl_cli.c:1071 client hello, total extension length: 111

I (13154) mbedtls: ssl_tls.c:3184 => write handshake message

I (13164) mbedtls: ssl_tls.c:3343 => write record

D (13164) mbedtls: ssl_tls.c:3423 output record: msgtype = 22, version = [3:1], msglen = 254

I (13174) mbedtls: ssl_tls.c:2755 => flush output

I (13184) mbedtls: ssl_tls.c:2774 message length: 259, out_left: 259

I (13184) mbedtls: ssl_tls.c:2779 ssl->f_send() returned 259 (-0xfffffefd)

I (13194) mbedtls: ssl_tls.c:2807 <= flush output

I (13204) mbedtls: ssl_tls.c:3476 <= write record

I (13204) mbedtls: ssl_tls.c:3320 <= write handshake message

I (13214) mbedtls: ssl_cli.c:1106 <= write client hello

I (13214) mbedtls: ssl_cli.c:3510 client state: 2

I (13224) mbedtls: ssl_tls.c:2755 => flush output

I (13234) mbedtls: ssl_tls.c:2767 <= flush output

I (13234) mbedtls: ssl_cli.c:1499 => parse server hello

I (13244) mbedtls: ssl_tls.c:4311 => read record

I (13244) mbedtls: ssl_tls.c:2536 => fetch input

I (13254) mbedtls: ssl_tls.c:2697 in_left: 0, nb_want: 5

I (13264) mbedtls: ssl_tls.c:2721 in_left: 0, nb_want: 5

I (13264) mbedtls: ssl_tls.c:2722 ssl->f_recv(_timeout)() returned 5 (-0xfffffffb)

I (13274) mbedtls: ssl_tls.c:2742 <= fetch input

D (13274) mbedtls: ssl_tls.c:4056 input record: msgtype = 22, version = [3:3], msglen = 3844

I (13284) mbedtls: ssl_tls.c:2536 => fetch input

I (13294) mbedtls: ssl_tls.c:2697 in_left: 5, nb_want: 3849

I (13304) mbedtls: ssl_tls.c:2721 in_left: 5, nb_want: 3849

I (13304) mbedtls: ssl_tls.c:2722 ssl->f_recv(_timeout)() returned 1435 (-0xfffffa65)

I (13314) mbedtls: ssl_tls.c:2721 in_left: 1440, nb_want: 3849

I (13324) mbedtls: ssl_tls.c:2722 ssl->f_recv(_timeout)() returned 1440 (-0xfffffa60)

CORRUPT HEAP: multi_heap.c:432 detected at 0x3fff0a98
abort() was called at PC 0x40085337 on core 0

ELF file SHA256: 2744357b4897769bc...

**Comment by david-cermak** [comment]
Hi @eduhash-kimyk 
Could you please turn on the `CONFIG_HEAP_CORRUPTION_DETECTION` config to see more details on the corrupt heap as described here: https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/heap_debug.html#finding-heap-corruption?

**Comment by eduhash-kimyk** [comment]
Hi @david-cermak, nice to meet you.
I’ll ask to our device engineer to turning on config and recapturing log. I’m sorry but it may takes a time due to timezone gap with your location.

**Comment by eduhash-kimyk** [comment]
Hi @david-cermak ,

We're trying to follow your guide but our development environment doesn't work 'Menu config'.
(FYI, we doesn't use Heap tracing mode until now so nobody experienced how to turn on.)
So, our engineer trying to change Heap tracing option using 'sdkconfig.defaults' and it changed 'sdkconfig.h' like below :

<sdkconfig.h>
#define CONFIG_HEAP_POISONING_COMPREHENSIVE 1
#define CONFIG_HEAP_TRACING_STANDALONE 1
#define CONFIG_HEAP_TRACING 1
#define CONFIG_HEAP_TRACING_STACK_DEPTH 2
#define CONFIG_HEAP_TASK_TRACKING 1
#define CONFIG_LOG_DEFAULT_LEVEL_INFO 1
#define CONFIG_LOG_DEFAULT_LEVEL 3

But our firmware still doesn't work Heap tracing until now.

I'm sorry but could you let me know how to change config value of CONFIG_HEAP_CORRUPTION_DETECTION directly in a certain file considering our situation, please?

**Comment by david-cermak** [comment]
To enable basic heap trancing, you can start with these options in your `skdconfig`:
```
CONFIG_HEAP_POISONING_COMPREHENSIVE=y
CONFIG_HEAP_TRACING_STANDALONE=y
CONFIG_HEAP_TRACING=y
CONFIG_HEAP_TRACING_STACK_DEPTH=2
CONFIG_HEAP_TASK_TRACKING=y
```
Which is pretty much the same as what you've mentioned above (but not sure if your options wouldn't get overwritten if set directly in `sdkconfig.h`)

In general, heap corruption issues are very difficult to track down and usually just turning the heap trancing on wouldn't reveal the source of the issue, but could give some pointers. It's also good to periodically call `heap_caps_check_integrity_all()` or set breakpoints to memory location where the corruption happens (using JTAG or with `esp_set_watchpoint()`). All this is described in the documentation I've linked above.

Also from the code snippet you've posted, I can see it sets the `.cert_pem = (const char *)iot_openit_pem_start,` to your server certificate. Where is the certificate located? (in flash, added via makefile or as `const ptr` in the code, allocated on heap, or as a static/global variable)?

**Comment by eduhash-kimyk** [comment]
Thanks for your help, David.

I’ll transfer to our engineer to follow your guide and give information to you about certificate location in our device. FYI, you can find link in ‘Problem Description’ which certificate file we use.

I’m not sure but what I remember is... certificate key value is copied from .pem file and paste to firmware source code as assigning string value to a certain variable.

**Comment by eduhash-kimyk** [comment]
Hi David,

1. We tried to apply 'skdconfig' following your guide on friday, but still we cannot capture heap tracing log until now.
   We'll find more and get back to you with how we tried.

2. Also, I'll explain how to apply certificate file in our device firmware you asked.

   1) Put our certificate file(PEM format) into folder 'project/main/'
   2) Assign certificate file in 'component.mk' like below :
       ![image](https://user-images.githubusercontent.com/66777673/99939207-e08e9e80-2dac-11eb-839f-7876b1b1f91c.png)

   3) Read certificate file in 'project/main/Mqtt_.c' like below :
       ![image](https://user-images.githubusercontent.com/66777673/99939234-f3a16e80-2dac-11eb-83d0-4cc540cb2913.png)


3. FYI, I'll show where ESP-IDF is located in our environment : 
   ![image](https://user-images.githubusercontent.com/66777673/99941812-feaacd80-2db1-11eb-84f7-ae6d6101a4db.png)


If you have any question, please let me know.
Thanks for your great help.

**Comment by eduhash-kimyk** [comment]
Hi David,

We failed to turn on Heap Tracing Mode so we decided to upgrade ESP-IDF module to 4.1 (from 4.0.0).
After upgrading, no more issue occurred until now so we'll apply new version of the firmware to our real devices until next sunday.

For my understanding, do you know which changes are related to solve this issue?

**Comment by david-cermak** [comment]
> do you know which changes are related to solve this issue?

TBH, I expected the heap debugging to show the root cause somewhere in the application code, as the workflow described above is such a *very very common* usecase, that majority of customers use. It is possible though that the issue might have been in the IDF, too, due to the version you used `v4.0-dev-1443-g39f090a4f-dirty`. Please note that it's always better to stick with releases, e.g. there's already a `v4.0.2` release tag, or we recommend to use release branches.

**Comment by eduhash-kimyk** [comment]
Hi David,

We've done rebuilding our firmware using release 4.1 with some minor bug fixes and applied to our devices on weekend.
After that, no more error was occurred on MQTT connection to Azure IoT Hub.
Still we're finding real root cause but we identified that retaining latest version of ESP-IDF is best way to solve unexpected problem as you mentioned.

Thanks for your good coaching. I can close this issue.
