### ISSUE TITLE
[TW#12725] BLE supervision timeout after N read

### ISSUE THREAD

**Issue by frax84** [espressif/esp-idf#613]
I built a BLE gatt client able to correctly connect and exchange data with esp32 gatt server. Everything works fine and data are passed from server to client with the correct values.
Unfortunately, i don't know why, after exactly 2233-2234 exchange of data (read as: 2234 read request/response) i always get a disconnection event due to supervision timeout.

Some considerations:
- Actually i don't know if it's a client or server (esp32) error. I suspect for server, but still...
- The disconnection is indipendent from the payload of the read. I tried with 1B up to 4B and the event always happens after 2233-2234 read request.
- The disconnection is indipendet from time. If i make 1000 request, pause for X minutes and restart the transfer it always happens at 2233-2234th event
- The disconnection is indipendent from connection interval, latency or supervision timeout setting.

This is the report on serial interface:

Guru Meditation Error of type StoreProhibited occurred on core  0. Exception was unhandled.
Register dump:
PC      : 0x40119462  PS      : 0x00060630  A0      : 0x80117af3  A1      : 0x3ffd13c0  
A2      : 0x00000276  A3      : 0x3ffffd9f  A4      : 0x00000255  A5      : 0x3ffd1660  
A6      : 0x00000000  A7      : 0x00000000  A8      : 0x00000001  A9      : 0x3ffd13a0  
A10     : 0x00000000  A11     : 0x00000282  A12     : 0x40081a00  A13     : 0x00000000  
A14     : 0x3ffd13a0  A15     : 0x00000026  SAR     : 0x00000018  EXCCAUSE: 0x0000001d  
EXCVADDR: 0x00000005  LBEG    : 0x4000c349  LEND    : 0x4000c36b  LCOUNT  : 0x00000000  

Backtrace: 0x40119462:0x3ffd13c0 0x40117af3:0x3ffd13e0 0x400e431c:0x3ffd1400 0x400e135c:0x3ffd16a0

Thanks

EDIT: I just noticed that if i change the ESP_GATT_MAX_ATTR_LEN parameter (and hence the memory occupied by the "rsp" variable), i can (slightly) change the number of readings that i'm able to do! i'm speaking of really low changes...few tenths of readings, but it's actually the only parameter i found to affect the number of readings

**Comment by frax84** [comment]
Hello,
here a proper description of the problem: gatt_server example. Advertising, connection and exchange of data through read/response method is ok. The error is reproducible.
This is the code of the read event:

`ESP_LOGI(GATTS_TAG,
				"GATT_READ_EVT, conn_id %d, trans_id %d, handle %d\n",
				param->read.conn_id, param->read.trans_id, param->read.handle);
		esp_gatt_rsp_t rsp;
		memset(&rsp, 0, sizeof(esp_gatt_rsp_t));
		rsp.attr_value.handle = param->read.handle;
		rsp.attr_value.len = 2;
		rsp.attr_value.value[0] = 55; //high byte
		rsp.attr_value.value[1] = 66; //low byte
		esp_ble_gatts_send_response(gatts_if, param->read.conn_id,
				param->read.trans_id, ESP_GATT_OK, &rsp);
		break;`

This is what serial interface gives out:

I (506306) GATTS_DEMO: GATT_READ_EVT, conn_id 0, trans_id 2162, handle 42

I(506376) GATTS_DEMO: GATT_READ_EVT, conn_id 0, trans_id 2163, handle 42   (<--this is the 2163th read/response)

Guru Meditation Error of type StoreProhibited occurred on core  0. Exception was unhandled.
Register dump:
PC      : 0x40119876  PS      : 0x00060630  A0      : 0x80117f07  A1      : 0x3ffd25f0  
A2      : 0x00000276  A3      : 0x3ffffd9f  A4      : 0x00000255  A5      : 0x3ffd2890  
A6      : 0x00000000  A7      : 0x00000000  A8      : 0x00000001  A9      : 0x3ffd25d0  
A10     : 0x00000000  A11     : 0x00000282  A12     : 0x400818a8  A13     : 0x00000000  
A14     : 0x3ffc3af8  A15     : 0x00000026  SAR     : 0x00000018  EXCCAUSE: 0x0000001d  
EXCVADDR: 0x00000005  LBEG    : 0x4000c349  LEND    : 0x4000c36b  LCOUNT  : 0x00000000  

Backtrace: 0x40119876:0x3ffd25f0 0x40117f07:0x3ffd2610 0x400e46fc:0x3ffd2630 0x400e173c:0x3ffd28d0

**Comment by xiewenxiang** [comment]
@frax84 
Hi frax84, I want to repeat the issue，but .. it seems work correctly.
I want to know more details about your code.

**Comment by xiewenxiang** [comment]
Maybe our processing process is different, can you describe your process in detail 
```
\0x1b[0;32mI (10034922) GATTS_DEMO: GATT_READ_EVT, conn_id 0, trans_id 20059, handle 42
\0x1b[0m
\0x1b[0;32mI (10035422) GATTS_DEMO: GATT_READ_EVT, conn_id 0, trans_id 20060, handle 42
\0x1b[0m
\0x1b[0;32mI (10035972) GATTS_DEMO: GATT_READ_EVT, conn_id 0, trans_id 20061, handle 42
\0x1b[0m
\0x1b[0;32mI (10036422) GATTS_DEMO: GATT_READ_EVT, conn_id 0, trans_id 20062, handle 42
\0x1b[0m
\0x1b[0;32mI (10036972) GATTS_DEMO: GATT_READ_EVT, conn_id 0, trans_id 20063, handle 42
\0x1b[0m
\0x1b[0;32mI (10037422) GATTS_DEMO: GATT_READ_EVT, conn_id 0, trans_id 20064, handle 42
\0x1b[0m
\0x1b[0;32mI (10037922) GATTS_DEMO: GATT_READ_EVT, conn_id 0, trans_id 20065, handle 42
\0x1b[0m
\0x1b[0;32mI (10038472) GATTS_DEMO: GATT_READ_EVT, conn_id 0, trans_id 20066, handle 42
\0x1b[0m
\0x1b[0;32mI (10038972) GATTS_DEMO: GATT_READ_EVT, conn_id 0, trans_id 20067, handle 42
\0x1b[0m
\0x1b[0;32mI (10039422) GATTS_DEMO: GATT_READ_EVT, conn_id 0, trans_id 20068, handle 42
\0x1b[0m
\0x1b[0;32mI (10039922) GATTS_DEMO: GATT_READ_EVT, conn_id 0, trans_id 20069, handle 42
\0x1b[0m
\0x1b[0;32mI (10040422) GATTS_DEMO: GATT_READ_EVT, conn_id 0, trans_id 20070, handle 42
\0x1b[0m
\0x1b[0;32mI (10040922) GATTS_DEMO: GATT_READ_EVT, conn_id 0, trans_id 20071, handle 42
\0x1b[0m
\0x1b[0;32mI (10041422) GATTS_DEMO: GATT_READ_EVT, conn_id 0, trans_id 20072, handle 42
\0x1b[0m
\0x1b[0;32mI (10041972) GATTS_DEMO: GATT_READ_EVT, conn_id 0, trans_id 20073, handle 42
\0x1b[0m
\0x1b[0;32mI (10042422) GATTS_DEMO: GATT_READ_EVT, conn_id 0, trans_id 20074, handle 42
\0x1b[0m
\0x1b[0;32mI (10043022) GATTS_DEMO: GATT_READ_EVT, conn_id 0, trans_id 20075, handle 42
\0x1b[0m
\0x1b[0;32mI (10043422) GATTS_DEMO: GATT_READ_EVT, conn_id 0, trans_id 20076, handle 42
\0x1b[0m
\0x1b[0;32mI (10043922) GATTS_DEMO: GATT_READ_EVT, conn_id 0, trans_id 20077, handle 42
\0x1b[0m
\0x1b[0;32mI (10044472) GATTS_DEMO: GATT_READ_EVT, conn_id 0, trans_id 20078, handle 42
\0x1b[0m
\0x1b[0;32mI (10044922) GATTS_DEMO: GATT_READ_EVT, conn_id 0, trans_id 20079, handle 42
\0x1b[0m
```

**Comment by frax84** [comment]
Hi xiewenxiang,
actually my code is pretty simple but i try to add more details to help you to reproduce the issue.
1) I use a gatt client written in Labview enviroment using BLED112 (BLEtoCOM);
2) The gatt client is able to discover correctly the device (name, RSSI, etc.);
3) The device is able to connect to the device and discover all the services and the characteristics obtaining a complete handle table of the gatt server. The connection is made setting these connection parameters:
- Min connection interval =20ms;
- Max connection interval = 50ms;
- Latency = 0;
- Timeout = 1000ms;
NOTE: I have no idea on how these connection data are managed in the gatt server. In fact, even if there is a struct (esp_ble_conn_update_params_t) and a function (esp_ble_gap_update_conn_params(esp_ble_conn_update_params_t *params) i didn't find any call to them in the gatt server code.
4) Pressing a button on my client i'm able to send read-request to gatt server (handle 42) and stream the data.
NOTE: the following read request is made only after a complete reading of the previous request.
5) Data stream follows without problems for the next (about) 2100 request. After that i obtain the Guru Meditation Error (StoreProhibited).

Error is perfectly reproducible. The number of read-request i can make before error is always the same but i noticed that i can slightly influence it (just of few tenths of request) changing these parameters:
- Stack size of the BT: i tried making it the double of the default value -> the number of read before error decreased;
- GATT MAX ATTRIBUTE LENGHT: i tried to change it from its default value (600) to 200, 100, 20, 10 and 2. Always little differences (sometimes higher number of read, sometimes lower).

I tried the code on ESP32-DEVKITC ESP32 Core Board V2 from Olimex and on ESP32 Thing by Sparkfun. I obtain the same behaviour.

If i can provide you more detail on specific elements please tell me.
Thank you for the support,
frax

**Comment by frax84** [comment]
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "freertos/event_groups.h"
#include "esp_system.h"
#include "esp_log.h"
#include "nvs_flash.h"
#include "bt.h"
#include "bta_api.h"

#include "esp_gap_ble_api.h"
#include "esp_gatts_api.h"
#include "esp_bt_defs.h"
#include "esp_bt_main.h"
#include "esp_bt_main.h"

#include "sdkconfig.h"

#define GATTS_TAG "GATTS_DEMO"

///Declare the static function 
static void gatts_profile_a_event_handler(esp_gatts_cb_event_t event,
		esp_gatt_if_t gatts_if, esp_ble_gatts_cb_param_t *param);
static void gatts_profile_b_event_handler(esp_gatts_cb_event_t event,
		esp_gatt_if_t gatts_if, esp_ble_gatts_cb_param_t *param);

#define GATTS_SERVICE_UUID_TEST_A   0x00FF
#define GATTS_CHAR_UUID_TEST_A      0xFF01
#define GATTS_DESCR_UUID_TEST_A     0x3333
#define GATTS_NUM_HANDLE_TEST_A     4

#define GATTS_SERVICE_UUID_TEST_B   0x00DF
#define GATTS_CHAR_UUID_TEST_B      0xDF01
#define GATTS_DESCR_UUID_TEST_B     0x2222
#define GATTS_NUM_HANDLE_TEST_B     4

#define TEST_DEVICE_NAME            "ESP_FRAX"
#define TEST_MANUFACTURER_DATA_LEN  17

#define GATTS_DEMO_CHAR_VAL_LEN_MAX		0x40

uint8_t char1_str[] = { 0x11, 0x22, 0x33 };
esp_attr_value_t gatts_demo_char1_val = { .attr_max_len =
		GATTS_DEMO_CHAR_VAL_LEN_MAX, .attr_len = sizeof(char1_str),
		.attr_value = char1_str, };

#ifdef CONFIG_SET_RAW_ADV_DATA
static uint8_t raw_adv_data[] = {0x0, 0x1, 0x2, 0x3, 0x4, 0x5, 0x6, 0x7, 0x8, 0x9, 0xa, 0xb, 0xc, 0xd, 0xe, 0xf,
	0x0, 0x1, 0x2, 0x3, 0x4, 0x5, 0x6, 0x7, 0x8, 0x9, 0xa, 0xb, 0xc, 0xd, 0xe};
static uint8_t raw_scan_rsp_data[] = {0x7, 0x7, 0x7, 0x7, 0x8, 0x8, 0x8, 0x8, 0x9, 0x9, 0x9, 0x9, 0xa, 0xa, 0xa, 0xa,
	0xb, 0xb, 0xb, 0xb, 0xc, 0xc, 0xc, 0xc, 0xd, 0xd, 0xd, 0xd, 0xe, 0xe, 0xe};
#else
static uint8_t test_service_uuid128[32] = {
		/* LSB <--------------------------------------------------------------------------------> MSB */
		//first uuid, 16bit, [12],[13] is the value
		0xfb, 0x34, 0x9b, 0x5f, 0x80, 0x00, 0x00, 0x80, 0x00, 0x10, 0x00, 0x00,
		0xAB, 0xCD, 0x00, 0x00,
		//second uuid, 32bit, [12], [13], [14], [15] is the value
		0xfb, 0x34, 0x9b, 0x5f, 0x80, 0x00, 0x00, 0x80, 0x00, 0x10, 0x00, 0x00,
		0xAB, 0xCD, 0xAB, 0xCD, };

//static uint8_t test_manufacturer[TEST_MANUFACTURER_DATA_LEN] =  {0x12, 0x23, 0x45, 0x56};
static esp_ble_adv_data_t test_adv_data = { .set_scan_rsp = false,
		.include_name = true, .include_txpower = true, .min_interval = 0x20,
		.max_interval = 0x40, .appearance = 0x00,
		.manufacturer_len = 0, //TEST_MANUFACTURER_DATA_LEN,
		.p_manufacturer_data = NULL, //&test_manufacturer[0],
		.service_data_len = 0, .p_service_data = NULL, .service_uuid_len = 32,
		.p_service_uuid = test_service_uuid128, .flag =
				(ESP_BLE_ADV_FLAG_GEN_DISC | ESP_BLE_ADV_FLAG_BREDR_NOT_SPT), };
#endif /* CONFIG_SET_RAW_ADV_DATA */

static esp_ble_adv_params_t test_adv_params = { .adv_int_min = 0x20,
		.adv_int_max = 0x40, .adv_type = ADV_TYPE_IND, .own_addr_type =
				BLE_ADDR_TYPE_PUBLIC,
		//.peer_addr            =
		//.peer_addr_type       =
		.channel_map = ADV_CHNL_ALL, .adv_filter_policy =
				ADV_FILTER_ALLOW_SCAN_ANY_CON_ANY, };

#define PROFILE_NUM 2
#define PROFILE_A_APP_ID 0
#define PROFILE_B_APP_ID 1

struct gatts_profile_inst {
	esp_gatts_cb_t gatts_cb;
	uint16_t gatts_if;
	uint16_t app_id;
	uint16_t conn_id;
	uint16_t service_handle;
	esp_gatt_srvc_id_t service_id;
	uint16_t char_handle;
	esp_bt_uuid_t char_uuid;
	esp_gatt_perm_t perm;
	esp_gatt_char_prop_t property;
	uint16_t descr_handle;
	esp_bt_uuid_t descr_uuid;
};

esp_bd_addr_t bda;                              /*!< Bluetooth device address */


/* One gatt-based profile one app_id and one gatts_if, this array will store the gatts_if returned by ESP_GATTS_REG_EVT */
static struct gatts_profile_inst gl_profile_tab[PROFILE_NUM] = {
		[PROFILE_A_APP_ID] = { .gatts_cb = gatts_profile_a_event_handler,
				.gatts_if = ESP_GATT_IF_NONE, /* Not get the gatt_if, so initial is ESP_GATT_IF_NONE */
		}, [PROFILE_B_APP_ID] = { .gatts_cb = gatts_profile_b_event_handler, /* This demo does not implement, similar as profile A */
		.gatts_if = ESP_GATT_IF_NONE, /* Not get the gatt_if, so initial is ESP_GATT_IF_NONE */
		}, };

static void gap_event_handler(esp_gap_ble_cb_event_t event,
		esp_ble_gap_cb_param_t *param) {
	switch (event) {
	case ESP_GAP_BLE_ADV_DATA_SET_COMPLETE_EVT:
		esp_ble_gap_start_advertising(&test_adv_params);
		break;
	case ESP_GAP_BLE_ADV_DATA_RAW_SET_COMPLETE_EVT:
		esp_ble_gap_start_advertising(&test_adv_params);
		break;
	case ESP_GAP_BLE_SCAN_RSP_DATA_RAW_SET_COMPLETE_EVT:
		esp_ble_gap_start_advertising(&test_adv_params);
		break;
	default:
		break;
	}
}

static void gatts_profile_a_event_handler(esp_gatts_cb_event_t event,
		esp_gatt_if_t gatts_if, esp_ble_gatts_cb_param_t *param) {
	switch (event) {
	case ESP_GATTS_REG_EVT:
		ESP_LOGI(GATTS_TAG, "REGISTER_APP_EVT, status %d, app_id %d\n",
				param->reg.status, param->reg.app_id)
		;
		gl_profile_tab[PROFILE_A_APP_ID].service_id.is_primary = true;
		gl_profile_tab[PROFILE_A_APP_ID].service_id.id.inst_id = 0x00;
		gl_profile_tab[PROFILE_A_APP_ID].service_id.id.uuid.len =
				ESP_UUID_LEN_16;
		gl_profile_tab[PROFILE_A_APP_ID].service_id.id.uuid.uuid.uuid16 =
				GATTS_SERVICE_UUID_TEST_A;

		esp_ble_gap_set_device_name(TEST_DEVICE_NAME);
#ifdef CONFIG_SET_RAW_ADV_DATA
		esp_ble_gap_config_adv_data_raw(raw_adv_data, sizeof(raw_adv_data));
		esp_ble_gap_config_scan_rsp_data_raw(raw_scan_rsp_data, sizeof(raw_scan_rsp_data));
#else
		esp_ble_gap_config_adv_data(&test_adv_data);
#endif
		esp_ble_gatts_create_service(gatts_if,
				&gl_profile_tab[PROFILE_A_APP_ID].service_id,
				GATTS_NUM_HANDLE_TEST_A);
		break;
	case ESP_GATTS_READ_EVT: {
		ESP_LOGI(GATTS_TAG,
				"GATT_READ_EVT, conn_id %d, trans_id %d, handle %d\n",
				param->read.conn_id, param->read.trans_id, param->read.handle);
		esp_gatt_rsp_t rsp;
		memset(&rsp, 0, sizeof(esp_gatt_rsp_t));
		rsp.attr_value.handle = param->read.handle;
		rsp.attr_value.len = 2;
		rsp.attr_value.value[0] = 55; //val1 >> 8; //high byte
		rsp.attr_value.value[1] = 66; //val1 & 0xff; //low byte
		esp_ble_gatts_send_response(gatts_if, param->read.conn_id,
				param->read.trans_id, ESP_GATT_OK, &rsp);
		break;
	}
	case ESP_GATTS_WRITE_EVT: {
		ESP_LOGI(GATTS_TAG,
				"GATT_WRITE_EVT, conn_id %d, trans_id %d, handle %d\n",
				param->write.conn_id, param->write.trans_id,
				param->write.handle);
		ESP_LOGI(GATTS_TAG, "GATT_WRITE_EVT, value len %d, value %08x\n",
				param->write.len, *(uint32_t * )param->write.value);
		esp_ble_gatts_send_response(gatts_if, param->write.conn_id,
				param->write.trans_id, ESP_GATT_OK, NULL);
	break;
	}
	case ESP_GATTS_EXEC_WRITE_EVT:
	case ESP_GATTS_MTU_EVT:
	case ESP_GATTS_CONF_EVT:
	case ESP_GATTS_UNREG_EVT:
		break;
	case ESP_GATTS_CREATE_EVT:
		ESP_LOGI(GATTS_TAG,
				"CREATE_SERVICE_EVT, status %d,  service_handle %d\n",
				param->create.status, param->create.service_handle)
		;
		gl_profile_tab[PROFILE_A_APP_ID].service_handle =
				param->create.service_handle;
		gl_profile_tab[PROFILE_A_APP_ID].char_uuid.len = ESP_UUID_LEN_16;
		gl_profile_tab[PROFILE_A_APP_ID].char_uuid.uuid.uuid16 =
				GATTS_CHAR_UUID_TEST_A;

		esp_ble_gatts_start_service(
				gl_profile_tab[PROFILE_A_APP_ID].service_handle);

		esp_ble_gatts_add_char(gl_profile_tab[PROFILE_A_APP_ID].service_handle,
				&gl_profile_tab[PROFILE_A_APP_ID].char_uuid,
				ESP_GATT_PERM_READ | ESP_GATT_PERM_WRITE,
				ESP_GATT_CHAR_PROP_BIT_READ | ESP_GATT_CHAR_PROP_BIT_WRITE
						| ESP_GATT_CHAR_PROP_BIT_NOTIFY, &gatts_demo_char1_val,
				NULL);
		break;
	case ESP_GATTS_ADD_INCL_SRVC_EVT:
		break;
	case ESP_GATTS_ADD_CHAR_EVT: {
		uint16_t length = 0;
		const uint8_t *prf_char;

		ESP_LOGI(GATTS_TAG,
				"ADD_CHAR_EVT, status %d,  attr_handle %d, service_handle %d\n",
				param->add_char.status, param->add_char.attr_handle,
				param->add_char.service_handle);
		gl_profile_tab[PROFILE_A_APP_ID].char_handle =
				param->add_char.attr_handle;
		gl_profile_tab[PROFILE_A_APP_ID].descr_uuid.len = ESP_UUID_LEN_16;
		gl_profile_tab[PROFILE_A_APP_ID].descr_uuid.uuid.uuid16 =
				ESP_GATT_UUID_CHAR_CLIENT_CONFIG;
		esp_ble_gatts_get_attr_value(param->add_char.attr_handle, &length,
				&prf_char);

		ESP_LOGI(GATTS_TAG, "the gatts demo char length = %x\n", length);
		for (int i = 0; i < length; i++) {
			ESP_LOGI(GATTS_TAG, "prf_char[%x] =%x\n", i, prf_char[i]);
		}
		esp_ble_gatts_add_char_descr(
				gl_profile_tab[PROFILE_A_APP_ID].service_handle,
				&gl_profile_tab[PROFILE_A_APP_ID].descr_uuid,
				ESP_GATT_PERM_READ | ESP_GATT_PERM_WRITE, NULL, NULL);
		break;
	}
	case ESP_GATTS_ADD_CHAR_DESCR_EVT:
		ESP_LOGI(GATTS_TAG,
				"ADD_DESCR_EVT, status %d, attr_handle %d, service_handle %d\n",
				param->add_char.status, param->add_char.attr_handle,
				param->add_char.service_handle)
		;
		break;
	case ESP_GATTS_DELETE_EVT:
		break;
	case ESP_GATTS_START_EVT:
		ESP_LOGI(GATTS_TAG, "SERVICE_START_EVT, status %d, service_handle %d\n",
				param->start.status, param->start.service_handle)
		;
		break;
	case ESP_GATTS_STOP_EVT:
		break;
	case ESP_GATTS_CONNECT_EVT:
		ESP_LOGI(GATTS_TAG,
				"SERVICE_START_EVT, conn_id %d, remote %02x:%02x:%02x:%02x:%02x:%02x:, is_conn %d\n",
				param->connect.conn_id, param->connect.remote_bda[0],
				param->connect.remote_bda[1], param->connect.remote_bda[2],
				param->connect.remote_bda[3], param->connect.remote_bda[4],
				param->connect.remote_bda[5], param->connect.is_connected)
		;
		gl_profile_tab[PROFILE_A_APP_ID].conn_id = param->connect.conn_id;
		break;
	case ESP_GATTS_DISCONNECT_EVT:
		esp_ble_gap_start_advertising(&test_adv_params);
		break;
	case ESP_GATTS_OPEN_EVT:
	case ESP_GATTS_CANCEL_OPEN_EVT:
	case ESP_GATTS_CLOSE_EVT:
	case ESP_GATTS_LISTEN_EVT:
	case ESP_GATTS_CONGEST_EVT:
	default:
		break;
	}
}

static void gatts_profile_b_event_handler(esp_gatts_cb_event_t event,
		esp_gatt_if_t gatts_if, esp_ble_gatts_cb_param_t *param) {
	switch (event) {
	case ESP_GATTS_REG_EVT:
		ESP_LOGI(GATTS_TAG, "REGISTER_APP_EVT, status %d, app_id %d\n",
				param->reg.status, param->reg.app_id)
		;
		gl_profile_tab[PROFILE_B_APP_ID].service_id.is_primary = true;
		gl_profile_tab[PROFILE_B_APP_ID].service_id.id.inst_id = 0x00;
		gl_profile_tab[PROFILE_B_APP_ID].service_id.id.uuid.len =
				ESP_UUID_LEN_16;
		gl_profile_tab[PROFILE_B_APP_ID].service_id.id.uuid.uuid.uuid16 =
				GATTS_SERVICE_UUID_TEST_B;

		esp_ble_gatts_create_service(gatts_if,
				&gl_profile_tab[PROFILE_B_APP_ID].service_id,
				GATTS_NUM_HANDLE_TEST_B);
		break;
	case ESP_GATTS_READ_EVT: {
		/*ESP_LOGI(GATTS_TAG,
				"GATT_READ_EVT, conn_id %d, trans_id %d, handle %d\n",
				param->read.conn_id, param->read.trans_id, param->read.handle); */
		esp_gatt_rsp_t rsp;
		memset(&rsp, 0, sizeof(esp_gatt_rsp_t));
		rsp.attr_value.handle = param->read.handle;
		rsp.attr_value.len = 4;
		rsp.attr_value.value[0] = 0xde;
		rsp.attr_value.value[1] = 0xed;
		rsp.attr_value.value[2] = 0xbe;
		rsp.attr_value.value[3] = 0xef;
		esp_ble_gatts_send_response(gatts_if, param->read.conn_id,
				param->read.trans_id, ESP_GATT_OK, &rsp);
		break;
	}
	case ESP_GATTS_WRITE_EVT: {
		/*ESP_LOGI(GATTS_TAG,
				"GATT_WRITE_EVT, conn_id %d, trans_id %d, handle %d\n",
				param->write.conn_id, param->write.trans_id,
				param->write.handle);
		ESP_LOGI(GATTS_TAG, "GATT_WRITE_EVT, value len %d, value %08x\n",
				param->write.len, *(uint32_t * )param->write.value);*/

		esp_ble_gatts_send_response(gatts_if, param->write.conn_id,
				param->write.trans_id, ESP_GATT_OK, NULL);
		break;
	}
	case ESP_GATTS_EXEC_WRITE_EVT:
	case ESP_GATTS_MTU_EVT:
	case ESP_GATTS_CONF_EVT:
	case ESP_GATTS_UNREG_EVT:
		break;
	case ESP_GATTS_CREATE_EVT:
		ESP_LOGI(GATTS_TAG,
				"CREATE_SERVICE_EVT, status %d,  service_handle %d\n",
				param->create.status, param->create.service_handle);
		gl_profile_tab[PROFILE_B_APP_ID].service_handle =
				param->create.service_handle;
		gl_profile_tab[PROFILE_B_APP_ID].char_uuid.len = ESP_UUID_LEN_16;
		gl_profile_tab[PROFILE_B_APP_ID].char_uuid.uuid.uuid16 =
				GATTS_CHAR_UUID_TEST_B;

		esp_ble_gatts_start_service(
				gl_profile_tab[PROFILE_B_APP_ID].service_handle);

		esp_ble_gatts_add_char(gl_profile_tab[PROFILE_B_APP_ID].service_handle,
				&gl_profile_tab[PROFILE_B_APP_ID].char_uuid,
				ESP_GATT_PERM_READ | ESP_GATT_PERM_WRITE,
				ESP_GATT_CHAR_PROP_BIT_READ | ESP_GATT_CHAR_PROP_BIT_WRITE
						| ESP_GATT_CHAR_PROP_BIT_NOTIFY,
				NULL, NULL);
		break;
	case ESP_GATTS_ADD_INCL_SRVC_EVT:
		break;
	case ESP_GATTS_ADD_CHAR_EVT:
		ESP_LOGI(GATTS_TAG,
				"ADD_CHAR_EVT, status %d,  attr_handle %d, service_handle %d\n",
				param->add_char.status, param->add_char.attr_handle,
				param->add_char.service_handle)
		;

		gl_profile_tab[PROFILE_B_APP_ID].char_handle =
				param->add_char.attr_handle;
		gl_profile_tab[PROFILE_B_APP_ID].descr_uuid.len = ESP_UUID_LEN_16;
		gl_profile_tab[PROFILE_B_APP_ID].descr_uuid.uuid.uuid16 =
				ESP_GATT_UUID_CHAR_CLIENT_CONFIG;
		esp_ble_gatts_add_char_descr(
				gl_profile_tab[PROFILE_B_APP_ID].service_handle,
				&gl_profile_tab[PROFILE_B_APP_ID].descr_uuid,
				ESP_GATT_PERM_READ | ESP_GATT_PERM_WRITE,
				NULL, NULL);
		break;
	case ESP_GATTS_ADD_CHAR_DESCR_EVT:
		ESP_LOGI(GATTS_TAG,
				"ADD_DESCR_EVT, status %d, attr_handle %d, service_handle %d\n",
				param->add_char.status, param->add_char.attr_handle,
				param->add_char.service_handle)
		;
		break;
	case ESP_GATTS_DELETE_EVT:
		break;
	case ESP_GATTS_START_EVT:
		ESP_LOGI(GATTS_TAG, "SERVICE_START_EVT, status %d, service_handle %d\n",
				param->start.status, param->start.service_handle)
		;
		break;
	case ESP_GATTS_STOP_EVT:
		break;
	case ESP_GATTS_CONNECT_EVT:
		ESP_LOGI(GATTS_TAG,
				"SERVICE_START_EVT, conn_id %d, remote %02x:%02x:%02x:%02x:%02x:%02x:, is_conn %d\n",
				param->connect.conn_id, param->connect.remote_bda[0],
				param->connect.remote_bda[1], param->connect.remote_bda[2],
				param->connect.remote_bda[3], param->connect.remote_bda[4],
				param->connect.remote_bda[5], param->connect.is_connected)
		;
		gl_profile_tab[PROFILE_B_APP_ID].conn_id = param->connect.conn_id;
		break;
	case ESP_GATTS_DISCONNECT_EVT:
	case ESP_GATTS_OPEN_EVT:
	case ESP_GATTS_CANCEL_OPEN_EVT:
	case ESP_GATTS_CLOSE_EVT:
	case ESP_GATTS_LISTEN_EVT:
	case ESP_GATTS_CONGEST_EVT:
	default:
		break;
	}
}

static void gatts_event_handler(esp_gatts_cb_event_t event,
		esp_gatt_if_t gatts_if, esp_ble_gatts_cb_param_t *param) {
	/* If event is register event, store the gatts_if for each profile */
	if (event == ESP_GATTS_REG_EVT) {
		if (param->reg.status == ESP_GATT_OK) {
			gl_profile_tab[param->reg.app_id].gatts_if = gatts_if;
		} else {
			ESP_LOGI(GATTS_TAG, "Reg app failed, app_id %04x, status %d\n",
					param->reg.app_id, param->reg.status);
			return;
		}
	}

	/* If the gatts_if equal to profile A, call profile A cb handler,
	 * so here call each profile's callback */
	do {
		int idx;
		for (idx = 0; idx < PROFILE_NUM; idx++) {
			if (gatts_if == ESP_GATT_IF_NONE || /* ESP_GATT_IF_NONE, not specify a certain gatt_if, need to call every profile cb function */
			gatts_if == gl_profile_tab[idx].gatts_if) {
				if (gl_profile_tab[idx].gatts_cb) {
					gl_profile_tab[idx].gatts_cb(event, gatts_if, param);
				}
			}
		}
	} while (0);
}

void app_main() {
	esp_err_t ret;

	esp_bt_controller_init();

	ret = esp_bluedroid_init();
	if (ret) {
		ESP_LOGE(GATTS_TAG, "%s init bluetooth failed\n", __func__);
		return;
	}
	ret = esp_bluedroid_enable();
	if (ret) {
		ESP_LOGE(GATTS_TAG, "%s enable bluetooth failed\n", __func__);
		return;
	}

	esp_ble_gatts_register_callback(gatts_event_handler);
	esp_ble_gap_register_callback(gap_event_handler);
	esp_ble_gatts_app_register(PROFILE_A_APP_ID);
	esp_ble_gatts_app_register(PROFILE_B_APP_ID);

	return;
}

**Comment by frax84** [comment]
The previous post is the full code i'm using. With this code and with a BT stack set in make config as double of default value i get 2171 readings (all libraries are unchanged)

**Comment by frax84** [comment]
Hi,
i have some news on it. I tried to restart from the beginning. I did a fresh install of ESP-IDF on another PC and tried again the gatt server (ESP32) + gatt client (Labview). Now everything works fine. I tried to compare the old code with the new one. It's identical except for something in the "main" (arguments that now are mandatory). My last IDF update was about 3 weeks ago. Did anything on BT libraries changed in the meantime that can be correlated to this problem?

**Comment by xiewenxiang** [comment]
@frax84  
Hi, maybe somethings was changed in the IDF, but i am not sure.
I will reproduce the issue in the old IDF.
Thanks you for the information.

**Comment by frax84** [comment]
Ty for the support. My code is up in the posts. Let me know if you need something else.

**Comment by FayeY** [comment]
Hi, is this issue still unsolved in the latest IDF?

**Comment by frax84** [comment]
It's solved!
