### ISSUE TITLE
Data-Over-Sound for ESP32&S2 (IDFGH-4290)

### ISSUE THREAD

**Issue by coollofty** [espressif/esp-idf#6135]
Data-Over-Sound for ESP32&S2, may be used for net config, or small data receive ....

**Comment by jason-mao** [comment]
This feature has a relatively narrow application scope, but it is technically feasible to implement. The previously popular ultrasonic network configuration was based on this technology, but it has now been replaced by other network configuration methods.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, feel free to reopen.
