### ISSUE TITLE
Memory leak (IDFGH-4300)

### ISSUE THREAD

**Issue by cas1no** [espressif/esp-idf#6143]
https://github.com/espressif/esp-idf/blob/178b122c145c19e94ac896197a3a4a9d379cd618/components/esp_https_server/src/https_server.c#L162
Memory is allocated, but never freed when error occurs.

**Comment by Alvin1Zhang** [comment]
@cas1no Thanks for reporting. Would you please help provide more details as suggested in the [issue template](https://github.com/espressif/esp-idf/issues/new?assignees=&labels=&template=bug_report.md&title=)? Information like elf, sdk configuration, backtrace, log outputs, commit ID, hardware and etc. would help us debug further. Thanks.

**Comment by negativekelvin** [comment]
@Alvin1Zhang that is not necessary since the problematic code is linked

**Comment by Alvin1Zhang** [comment]
@negativekelvin Thanks for the notes. @cas1no Thanks for reporting, we have a fix under internal reviewing, and the issue will be closed automatically once the issue is available on GitHub. Thanks.
