### ISSUE TITLE
Blufi error on release v4.1 with git pull --rec update (IDFGH-4302)

### ISSUE THREAD

**Issue by filzek** [espressif/esp-idf#6145]
Blufi is completed break in latest release v4.1 with updates pulled in git pull --rec.

Its simple hangs and doesnt reply to any blufi command.

Very eratic error in a stable release version.

Urgent feedback needed.

**Comment by xiewenxiang** [comment]
Could you describe in detail what kind of problems you have encountered.

**Comment by filzek** [comment]
same as latest report, some parts update in ble but the error on past ble problem on packet as of IDFGH-3893, so, the problem still happen.

I will close this as it is redundant.

**Comment by filzek** [comment]
as reported in sep 24, 

@hb-kaertech @filzek @jimwhitfield

If it is urgent, can you make such modification temporarily? We are doing further analysis.

components/bt/host/bluedroid/btc/profile/esp/blufi/blufi_prf.c

esp_ble_get_cur_sendable_packets_num(blufi_env.conn_id) -> esp_ble_get_sendable_packets_num()

this fix temporary the problem.
