### ISSUE TITLE
Can't create/open example project ESP-IDF with Visual Studio 2019 and VisualGDB (IDFGH-4308)

### ISSUE THREAD

**Issue by federicoscata** [espressif/esp-idf#6151]
## Environment

- Development Kit:      [ESP32-DevKitC]
- Kit version (for WroverKit/PicoKit/DevKitC): [v3]
- Module or chip used:  [ESP32-WROOM-32D]
- IDF version (run ``git describe --tags`` to find it): v3.2
- Build System:         [Make|CMake|idf.py]
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it):
- Operating System:     [Windows]
- (Windows only) environment type: [PowerShell].
- Using an IDE?: [Yes, Visual Studio 2019, Version 16.8.2]
- Power Supply:         [USB]

## Problem Description

In Visual Studio 2019, I have a problem to create/open example projects ("blufi" or other).
I follow the instruction here: [https://visualgdb.com/tutorials/esp32/esp-idf/]. When I click on "finish", visual studio can't build the project because of this:

Command exited with code 1
Executable: c:\sysgcc\esp32\usr\bin\bash.exe
Arguments: --login -c "export IDF_PATH=/esp-idf/v3.2 && export BATCH_BUILD=1 && export PATH=/mingw32/bin:/usr/bin:$PATH && export -n PYTHONHOME && export LANG=en_US && cd /C/Users/.../source/repos/EmbeddedProject27 && make defconfig BUILD_DIR_BASE='/C/Users/.../source/repos/EmbeddedProject27/.visualgdb/VisualGDBCache/EmbeddedProject27-Debug-VisualGDB/CodeSenseDir' SDKCONFIG='/C/Users/.../source/repos/EmbeddedProject27/sdkconfig-debug' V=0"
Directory: 
Command-line action failed
Project configuration failed: System.IO.FileNotFoundException: Il file 'C:\Users\...\source\repos\EmbeddedProject27\sdkconfig-debug' not found.
File name: 'C:\Users\...\source\repos\EmbeddedProject27\sdkconfig-debug'
   in System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   in System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   in System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   in a3.e.l_2(k61 a)
   in hc1.e(String a)
   in hc1.p()
   in kg1.j()

**Comment by igrr** [comment]
@federicoscata it looks like VisualGDB is passing this argument to the IDF build system:
```
SDKCONFIG='/C/Users/.../source/repos/EmbeddedProject27/sdkconfig-debug' 
```
I'm not sure of the purpose of this file, or who is expected to create it. It is not part of IDF build system, possibly some custom functionality in VisualGDB. I recommend contacting VisualGDB support for this issue.

By the way, please note that ESP-IDF v3.2 is EOL and is no longer supported: https://github.com/espressif/esp-idf/blob/master/SUPPORT_POLICY.md#existing-releases

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, feel free to reopen.
