### ISSUE TITLE
Files with an extension of more than 4 characters can not be opened by "fopen" on SD card. (IDFGH-4318)

### ISSUE THREAD

**Issue by dr-ksk** [espressif/esp-idf#6160]
At this example (https://github.com/espressif/esp-idf/tree/master/examples/storage/sd_card)
I changed file name "hello.txt" -> "hello.text", then file can not open.

At ESP-IDF monitor, "E (371) example: Failed to open file for writing".

It is occurred by 4 word extension, such as html, text, json, flac etc.

**Comment by negativekelvin** [comment]
https://github.com/espressif/esp-idf/issues/6138
