### ISSUE TITLE
CONFIG_BOOTLOADER_SPI_CUSTOM_WP_PIN=n fails with ESP32-U4WDH (IDFGH-4353)

### ISSUE THREAD

**Issue by m-bruck** [espressif/esp-idf#6191]
- Development Kit: none
- Module or chip used: ESP32-U4WDH
- IDF version: v4.2-rc
- Build System: idf.py
- Compiler version: 2020r3
- Operating System: Windows, ESP Command Prompt
- Using an IDE?: No

The description for CONFIG_BOOTLOADER_SPI_CUSTOM_WP_PIN says _"If this config item is set to N (default), the correct WP pin will be automatically used for any Espressif chip or module with integrated flash."_

However it does not seem to work for U4WDH in combination with QIO. The bootloader fails when checking the partition table.

**Comment by projectgus** [comment]
Hi @m-bruck,

I'm really sorry noone got back to you about this for such a long time.

You're totally right, the automatic WP pin sewlection fails in this case and quad flash modes don't work automatically.

As you probably already know, a manual workaround is to enable `CONFIG_BOOTLOADER_SPI_CUSTOM_WP_PIN` and keep the default choice (7), and it works.

Will have a fix for this ASAP.
