### ISSUE TITLE
Last ESP-IDF recursive ( submodule ) fails

### ISSUE THREAD

**Issue by ESP32DE** [espressif/esp-idf#620]
hi guys

just in time tried, comments 2.638

https://github.com/espressif/esp-idf/commit/d8c0b505f686db8c0f5b5de864918272c1d30836

recursive download fails.

best wishes
rudi ;-)
![last](https://cloud.githubusercontent.com/assets/16070445/26199216/81b79e58-3bc9-11e7-9048-1dd26fa8a8bf.jpg)

**Comment by igrr** [comment]
Please try again, seems to be okay now.

**Comment by ESP32DE** [comment]
hi 
yes now is ok. thank you!
best wishes
rudi ;-)
