### ISSUE TITLE
DeprecationWarning: urllib.parse.splittype() is deprecated as of 3.8, use urllib.parse.urlparse() instead (IDFGH-4364)

### ISSUE THREAD

**Issue by askpatrickw** [espressif/esp-idf#6200]
For when you get around to Python 3.9 support.

https://github.com/espressif/esp-idf/blob/178b122c145c19e94ac896197a3a4a9d379cd618/tools/idf_tools.py#L308

idf_tools.py:308: DeprecationWarning: urllib.parse.splittype() is deprecated as of 3.8, use urllib.parse.urlparse() instead

`url_type, path = splittype(url)` is the current code.

```python
url_type = urllib.parse.urlparse(url)['scheme']
path = urllib.parse.urlparse(url)['path']  # You may also need params and query... not sure. 
```

You may also ned to join netloc and path if its a file.

```python
urllib.parse.splittype(url3)
('file', '//localhost/etc/fstab')

urllib.parse.urlparse(url3)
ParseResult(scheme='file', netloc='localhost', path='/etc/fstab', params='', query='', fragment='')
```

**Comment by Kiznoh** [comment]
Hi Patrick,
Thank you for your report.
