### ISSUE TITLE
WiFi Light Sleep+ WIFI_PS_MAX_MODEM change in power draw (IDFGH-4386)

### ISSUE THREAD

**Issue by patrick277** [espressif/esp-idf#6220]
Hello,

I have some ESP32's ESP-IDF running in automatic light sleep (WIFI_PS_MAX_MODEM) while remaining connected to the internet. This application is battery based and I notice that occasionally the power draw increases (my battery voltage goes down). The code wakes up from light sleep, publishes mqttt and goes back to light sleep every 60s. I enabled the counters from vTaskGetRunTimeStats and I notice they average:
'IDLE1', 'IDLE0', 'sleep_manager', 'mqtt_task', 'tiT', 'TmrSvc', 'ipc1', 'wifi', 'esp_timer', 'sys_evt', 'ipc0', date
63544921 62496503 24613 158418 115500 0 0 466115 233505 0 0 03/12/2020 12:28:27

and change to:
'IDLE1', 'IDLE0', 'sleep_manager', 'mqtt_task', 'tiT', 'TmrSvc', 'ipc1', 'wifi', 'esp_timer', 'sys_evt', 'ipc0', date
63591049 62878982 24345 149548 94302 0 0 262723 115852 0 0 03/12/2020 12:37:57
when the power draw goes up. These counters are the difference in count from the last time it woke up from light sleeo. 

![image](https://user-images.githubusercontent.com/53476329/101366494-41fd4580-3862-11eb-805d-7667f7df5841.png)

If anyone has seen this I would love some Ideas! If there is any other info let me know!

*update
Possibly it could be an issue with the MQTT client because it's mqtt_task went from an average of ~160ms to an average of ~140ms. Could it be that it is waiting for something and keeping the wifi receiver on accidentally. 

Here is another graph of the event, the code does not change operation during this time, but it coeincides exactly when the battery draw starts, each sample is ~63s apart
![image](https://user-images.githubusercontent.com/53476329/101499054-07f77680-392a-11eb-86cb-f5b48e95c79c.png)

**Comment by YouDONG-ESP** [comment]
Hi @patrick277 tell me if I miss understanding the issue, your application run the same MQTT task every 60s, in shows that occasionally MQTT and wifi, esptimer runtime will change right? Could you show me how often dose it happens and how long dose it last？
BTW, I think you should mesure the input current to get the exact power draw.

**Comment by YouDONG-ESP** [comment]
You said each sample is 63s for the second graph, so this issue last for around 400 ~700 min?

**Comment by patrick277** [comment]
> 
> 
> You said each sample is 63s for the second graph, so this issue last for around 400 ~700 min?

That is correct. The way it was resolved initially was by sending a few mqtt publish messages from the server to the device. This seems weird to me. 

It happens randomly, I will try to get a current draw, but from the battery voltage graph, it is ~50mA. 



The operation of the code is as follows:
1. connect to wifi, connect to mqtt wss server, read analogs
2. acquire PM lock
3. publish mqtt message 
4. release PMlock
4b. sleep ~60s
5. wake and acquire PM lock
6. read analogs
7. publish mqtt message
8. release PMlock
9. repeat 4b. thru 8

**Comment by YouDONG-ESP** [comment]
Could you tell me your chip model and the idf verion?

**Comment by patrick277** [comment]
IDF: ESP-IDF v4.1-dirty
Chip is ESP32D0WDQ6 (revision 1)

**Comment by patrick277** [comment]
I ran another test last night 
This time I moved the cpu cores as follows, and as you can see. this time mqtt duty cycle did not change when wifi task and esp_timer task run-time dropped. (the battery also dropped exactly when it happened (second graph pic) it is a 18650 2600mAhr battery .

st_rx_data               core0 ->   core1
IDLE0                         core0
IDLE1               core1
sleep_manager  core0 ->  core 1
mqtt_task          core0 ->   core1
tiT                     core0 ->   core1
Tmr Svc              core0
sys_evt              core0
wifi                    core0
esp_timer           core0
ipc0                   core0
ipc1                  core1

data:
[2020-12-09 overnight test.xlsx](https://github.com/espressif/esp-idf/files/5667369/2020-12-09.overnight.test.xlsx)

battery:
![image](https://user-images.githubusercontent.com/53476329/101659874-bfac8700-3a03-11eb-9b04-8e8659d340e2.png)

**Comment by YouDONG-ESP** [comment]
@patrick277 whats the different between the green curve and the yellow cuve?
Could you change the abscissa of the data to time? If it's still 63 second/sample, the drop time seems not the same.

**Comment by YouDONG-ESP** [comment]
@patrick277 The run time of wifi task in light sleep mode should depand on the environnment. If there are lots of others users, 
sta will wake up more time to compete for the channel.
That means wifi run time and battery consomation may drops during the night because there are less users and the environnment is clean.

**Comment by patrick277** [comment]
> 
> 
> @patrick277 The run time of wifi task in light sleep mode should depand on the environnment. If there are lots of others users, sta will wake up more time to compete for the channel.
> That means wifi run time and battery consomation may drops during the night because there are less users and the environnment is clean.

Is there any way I can monitor how crowded it is or limit how much it tries to compete? so that I protect the battery supply

**Comment by YouDONG-ESP** [comment]
@patrick277 I suggest you do a packet capture to see how crowded the channel is and how many times your device tries to compete.

**Comment by YouDONG-ESP** [comment]
@patrick277 Wifi tasks wakes less than 5% of the time is a normal behavior for power safe mode.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, feel free to reopen.
