### ISSUE TITLE
Console log is printing negative timestamps (IDFGH-4393)

### ISSUE THREAD

**Issue by sinope-db** [espressif/esp-idf#6226]
## Environment

- IDF version: 3.3.4 (still present in master 178b122)

## Problem Description

A negative timestamp is printed in console log when esp_log_timestamp() returns values between 0x80000000 and 0xFFFFFFFF.

https://github.com/espressif/esp-idf/blob/178b122c145c19e94ac896197a3a4a9d379cd618/components/log/include/esp_log.h#L275

Should be %u instead of %d.

### Expected Behavior

A positive timestamp is printed in console log.

### Steps to reproduce

Let program run for more than 24 days 

## Debug Logs

```
W (-843707743) wifi:[beacon]new interval:1000ms
I (-843707743) mesh: [scan]new scanning time:1500ms
W (-843699663) wifi:[beacon]interval:1000ms
```

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, we will look into.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, the fix is currently synchronizing to GitHub, the issue will close once it gets available on GitHub. Thanks.
