### ISSUE TITLE
esp_http_client to support chunked request (IDFGH-4401)

### ISSUE THREAD

**Issue by galah92** [espressif/esp-idf#6234]
**Is your feature request related to a problem? Please describe.**
I'm trying to steam data over a single HTTP request using chunked requests (PUT request).

**Describe the solution you'd like**
Current HTTP-client-API has `esp_http_client_open()` which takes the total size of the request. This prevents from defining a chunked requests and `esp_http_client_write()`ing as much as I want.

**Comment by Alvin1Zhang** [comment]
Thanks for raising this feature request.

**Comment by galah92** [comment]
Just to elaborate - it seems that using a negative `write_len` will add `chunked` "Transfer-Encoding" header, but will also override the method to be `POST`. My use-case is for chunked requests with `PUT` method.

**Comment by shubhamkulkarni97** [comment]
Hi @galah92,

Sorry for slow turnaround. I got the issue where HTTP method gets overwritten to POST while sending chunked request.

Can you try applying patch attached below and check if it works for your use case?

[0001-esp_http_client-Set-HTTP-method-to-POST-only-if-meth.patch.zip](https://github.com/espressif/esp-idf/files/6195671/0001-esp_http_client-Set-HTTP-method-to-POST-only-if-meth.patch.zip)

**Comment by galah92** [comment]
Hi @shubhamkulkarni97. The patch is working, thanks.
Can this be merged to v4.3?

**Comment by galah92** [comment]
@shubhamkulkarni97 will this be included as part of v4.4? Is there an ETA for that?

**Comment by galah92** [comment]
> @shubhamkulkarni97 @Alvin1Zhang will this be included as part of v4.4? Is there an ETA for that?

Any update? Thanks

**Comment by galah92** [comment]
@shubhamkulkarni97 @Alvin1Zhang bumping it again. This bugfix is of great importance for us, thank you.

**Comment by shubhamkulkarni97** [comment]
Hi @galah92,

This fix will be a part of v4.4 release. We are aiming to release IDF v4.4 by end of 2021.
