### ISSUE TITLE
Add a new namespace index (IDFGH-4416)

### ISSUE THREAD

**Issue by rony91jp** [espressif/esp-idf#6247]
Hello 
I am following the below issue and tried to add a new namespace but do not understand how to create. 
Please provide me any reference example which will help me to solve the issue.

https://github.com/open62541/open62541/issues/897#issue-193067984

Thank you.

**Comment by projectgus** [comment]
Hi @rony91jp,

Did you mean to to open this issue on the open62541 repository? This is the ESP-IDF repository, this code isn't part of our project.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting.
