### ISSUE TITLE
[TW#12789] All BT examples except ble_adv not advertising

### ISSUE THREAD

**Issue by xarrange** [espressif/esp-idf#625]
Hi,
Is that me or it's supposed to be so? I just cloned repo and built all BT related examples - none of them  are visible for BT pairing. Except ble_adv, which is visible but can't pair. 
Am I missing something?

**Comment by negativekelvin** [comment]
BLE is different, it doesn't require pairing like BT classic. Try using a ble scanner app like lightblue or nrf connect.

**Comment by YelongHuang** [comment]
Hi, @xarrange If you went to use BLE paring with the smart phone, maybe you can try the gatt_server_sercurity demo, all other BLE demos cannt pairing with the smart phone. Thanks.

**Comment by FayeY** [comment]
Hi @xarrange , is there any update? Is this problem solved now?
