### ISSUE TITLE
wifi-mesh (v4.2): Guru Meditation Error: Core  1 panic'ed (InstrFetchProhibited). Exception was unhandled (IDFGH-4421)

### ISSUE THREAD

**Issue by dshil** [espressif/esp-idf#6252]
## Environment

- Module or chip used:  ESP32-WROVER-B
- IDF version: v4.2
- Build System: idf.py (cmake - the same)
- Compiler version: esp-2020r2-8.2.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc
- Operating System: Linux
- Using an IDE: No
- Power Supply: USB

## Problem Description

I tried v4.2 after it was released. Mesh library is crashing each time the vote process is finished. To reproduce this issue you could flash the example under esp-idf/examples/mesh/ip_internal_network

**Comment by Alvin1Zhang** [comment]
Thanks for reporting and letting us know, we will look into.

**Comment by dshil** [comment]
Ref: https://github.com/espressif/esp-idf/issues/6067
