### ISSUE TITLE
Undefined reference to app_main freertos.a (IDFGH-4422)

### ISSUE THREAD

**Issue by GunashekarG** [espressif/esp-idf#6253]
OS: Ubuntu Mate
IDFV: v4.3-dev-1901-g178b122c1

Example: tusb_serail_device

While compiling I'm getting the error as shown in below screenshot

![Error](https://user-images.githubusercontent.com/31695652/101902335-7f523200-3bd8-11eb-8c7b-48b19898ce0b.png)

sdkconfig file has been attached below.

[sdkconfig.txt](https://github.com/espressif/esp-idf/files/5679063/sdkconfig.txt)

**Comment by igrr** [comment]
Hi @GunashekarG, ESP32-S2 chip is only supported by the CMake build system. It looks like you are using the legacy GNU Make based build system to compile this example. Assuming you want to get this example running on the ESP32-S2 and not on the ESP32 (which doesn't have a USB peripheral), you will need to switch to CMake. Please follow https://docs.espressif.com/projects/esp-idf/en/v4.2/esp32s2/get-started/index.html to get started. CMake specific instructions start at step 8.

**Comment by Alvin1Zhang** [comment]
@GunashekarG Thanks for reporting and please help follow the notes by @igrr , feel free to reopen, thanks.

**Comment by GunashekarG** [comment]
Thanks for the response guys. Will definitely try the lead. Thanks again.

**Comment by GunashekarG** [comment]
OS: Linux(Ubuntu Mate)
ESP-IDF Vesrion: v4.2
Chip used: ESP32-S2
Exapmle: Hello_world

While trying to build the in built example hello world code by selecting the target as esp32s2, I am getting the following error.

![Error_1](https://user-images.githubusercontent.com/31695652/102054232-13a5da00-3e0f-11eb-9b90-230f194af5a6.png)

@igrr can you please help me out with this issue?

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, sorry that we do not support make build system for ESP32-S2, will close the ticket, thanks.
