### ISSUE TITLE
Wrong descrption of Freertos-smp changed in latest documentation. (IDFGH-4428)

### ISSUE THREAD

**Issue by lorddoskias** [espressif/esp-idf#6259]
In the [latest](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/freertos-smp.html#critical-sections-disabling-interrupts) documentation guide  one of the changes related to locking states that all critical section related macros really boil down to calling `vtaskentercritical`. This creates the wrong impression that calling `vtaskentercritical` is the same as calling `taskENTER_CRITICAL`. In fact eps32's related changes are really in `vPortEnterCritical`

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, we will look into.

**Comment by projectgus** [comment]
Hi @lorddoskias,

Thanks for letting us know. I think the functionality has been updated without updating the docs to match, and I notice a comment in portmacro.h is the same. Will fix.
