### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement bidict>=0.21.0 (IDFGH-4431)

### ISSUE THREAD

**Issue by GunashekarG** [espressif/esp-idf#6262]
OS: Ubuntu Mate
Version: v4.2

While installing the ESP-IDF for ESPS2, I am finding an error as shown below.
![Error_installation](https://user-images.githubusercontent.com/31695652/102046299-14377400-3e01-11eb-923c-5d9a9be6df3f.png)

Requirements file is also attached below.

[requirements.txt](https://github.com/espressif/esp-idf/files/5686780/requirements.txt)

My current pip version is: pip 20.3.1 (python 2.7)

Can anyone please solve this issue?

**Comment by linweifu** [comment]
Me too, waiting for a solution

**Comment by fetullah-usr** [comment]
+1

**Comment by dobairoland** [comment]
Hi @GunashekarG & @fetullah-usr. We already fixed this but the change haven't made it into Github yet. The following checksum will become a clickable link when it does: dc98d0aeee8b4766d9b312c6065b503073c42105

Until then the workaround is to add manually the following line into the `requirements.txt`:
`python-socketio<5; python_version<="2.7"`

We are sorry for the inconvenience.

**Comment by dobairoland** [comment]
The long term recommendation is to switch to Python 3: https://docs.espressif.com/projects/esp-idf/en/latest/esp32/get-started/linux-setup.html#setting-up-python-3-as-default-for-ubuntu-and-debian

That will also fix the above issue and avoid future Python 2 incompatibilities.

**Comment by GunashekarG** [comment]
It's working now after updating to Python3. Thank you guys. Cheers.

**Comment by dobairoland** [comment]
Thank you for the feedback. I keep this open for others to see it until the fix will be available.

**Comment by samiralavi** [comment]
Another easy solution could be adding "python3" explicitly in the install.sh script.

**Comment by ellipsistechnology** [comment]
This worked for me also - thanks for the help.
One note (probably only an issue on Mac) if you are having issues convincing it to run with Python3 (as is common on recent version of Mac OS) you can force the `tools/idf_tools.py` script to use Python3 by changing its first line to `#!/usr/bin/env python3` and then run `./install.sh`.

**Comment by dobairoland** [comment]
The fix is available in master now: https://github.com/espressif/esp-idf/commit/dc98d0aeee8b4766d9b312c6065b503073c42105

**Comment by MohamedZaheri** [comment]
@dobairoland , the fix is merged to master but not to the V4.2 release branch, is it? Because I still have same issue using the V4.2 branch.

**Comment by jtchitty** [comment]
> The long term recommendation is to switch to Python 3: https://docs.espressif.com/projects/esp-idf/en/latest/esp32/get-started/linux-setup.html#setting-up-python-3-as-default-for-ubuntu-and-debian
> 
> That will also fix the above issue and avoid future Python 2 incompatibilities.

This is very likely going to cause problems for other things on the system. It has for us, several times. It breaks other things in very subtle and hard-to-debug ways. In fact, this is the one major complaint I have with the ESP-IDF Getting Started for Ubuntu and Debian.

The long-term plan _should_ be to update the ESP-IDF to not require a specific system-wide default. ;)

**Comment by dobairoland** [comment]
@MohamedZaheri The fix is in v4.2 as well: https://github.com/espressif/esp-idf/commit/9ff5f94233d5e8b5a124ab9b58b913f049e47597

**Comment by dobairoland** [comment]
> The long-term plan should be to update the ESP-IDF to not require a specific system-wide default. ;)

@jtchitty Yes, that is on the table.

**Comment by 9ae8sdf76** [comment]
I just downloaded - as of today - ESP-IDF from your website and ran into this problem. Did this fix make its way into the official release? 

After switching the repository to master, I of course had no issues with installation. Thank you.

**Comment by dobairoland** [comment]
@9ae8sdf76 Unfortunately, the fix haven't made into v4.2. It will be included in v4.2.1. 

It is already available in the branch https://github.com/espressif/esp-idf/tree/release/v4.2. You can already use that branch. Or you can manually apply the patch to your v4.2 copy.

We are sorry for the inconvenience.
