### ISSUE TITLE
[TW#12791] Small doc error - SD Card example is now SPI Flash example

### ISSUE THREAD

**Issue by nkolban** [espressif/esp-idf#627]
If we look here

https://github.com/espressif/esp-idf/tree/master/examples/storage/wear_levelling

We find a wear leveling example with the title "SD Card example" ... however my understanding is that the example is SPI flash and not SD Card.

Also ... I believe "leveling" is spelled "leveling" and not "levelling" as is found in some areas of the docs.

**Comment by igrr** [comment]
It seems that levelling is a BrE version which is used in the component name, so renaming it to 'wear_leveling' now may not be easy.
I'll send a fix for the incorrect readme title.
