### ISSUE TITLE
Heap memory is reduced (40 bytes) every time malloc(), free() is repeated. (IDFGH-4448)

### ISSUE THREAD

**Issue by ansee7221** [espressif/esp-idf#6279]
## Environment

- Development Kit:      [ESP32-DevKitC]
- Kit version (for DevKitC): [v1|v2|v3|v4]
- Module or chip used:  [ESP32-WROOM-32D]
- IDF version (run ``git describe --tags`` to find it):
    // v4.3-dev-1521-g0289d1c-dirty
- Build System:         [idf.py]
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it):
    // xtensa-esp32-elf-gcc (crosstool-NG esp-2020r3) 8.4.0
- Operating System:     [Linux]
- (Windows only) environment type: [MSYS2 mingw32|ESP Command Prompt|Plain Command Prompt|PowerShell].
- Using an IDE?: [No]
- Power Supply:         [USB]

## Problem Description
Memory leakage occurs when data is stored periodically in the NVS area.
After malloc(), save to NVS area, free() then heap memory reduced approximately 40 bytes.
  
//Detailed problem description goes here.

### Steps to reproduce

// If possible, attach a picture of your setup/wiring here.

### Code to reproduce this issue

```cpp
// the code should be wrapped in the ```cpp tag so that it will be displayed better.
#include <pthread.h>
#include <stdio.h>
#include <inttypes.h>
#include <signal.h>
#include <string.h>

#include "freertos/FreeRTOS.h"
#include "freertos/semphr.h"
#include "freertos/task.h"
#include "freertos/event_groups.h"
#include "nvs_flash.h"
#include "esp_wifi.h"
#include "esp_event.h"
#include "esp_log.h"
//#include "driver/gpio.h"
//#include "debug_print.h"
#include "esp_system.h"
#include "port/oc_clock.h"


#define EXAMPLE_WIFI_SSID CONFIG_WIFI_SSID
#define EXAMPLE_WIFI_PASS CONFIG_WIFI_PASSWORD
//#define BLINK_GPIO CONFIG_BLINK_GPIO

static EventGroupHandle_t wifi_event_group;

static const int IPV4_CONNECTED_BIT = BIT0;
static const int IPV6_CONNECTED_BIT = BIT1;

static const char *TAG = "iotivity server";

#define SVR_TAG_MAX (32)
#define STORE_PATH_SIZE 64
#define MAX_APP_DATA_SIZE (2048L)		

static char storePath[STORE_PATH_SIZE];
static int storePath_len;
static bool pathSet = false;

uint32_t testCount = 0;

static void sta_start(void *esp_netif, esp_event_base_t event_base,                     
	int32_t event_id, void *event_data) 
{  
	esp_wifi_connect();
}

static void sta_disconnected(void *esp_netif, esp_event_base_t event_base,                             
	int32_t event_id, void *event_data) 
{  
	esp_wifi_connect();  
	xEventGroupClearBits(wifi_event_group, IPV4_CONNECTED_BIT);  
	xEventGroupClearBits(wifi_event_group, IPV6_CONNECTED_BIT);
}

static void sta_connected(void *esp_netif, esp_event_base_t event_base,                          
	int32_t event_id, void *event_data)
{  
	esp_netif_create_ip6_linklocal(esp_netif);
}

static void got_ip(void *esp_netif, esp_event_base_t event_base,                   
	int32_t event_id, void *event_data)
{  
	xEventGroupSetBits(wifi_event_group, IPV4_CONNECTED_BIT);
}

static void got_ip6(void *esp_netif, esp_event_base_t event_base,                    
	int32_t event_id, void *event_data)
{  
	xEventGroupSetBits(wifi_event_group, IPV6_CONNECTED_BIT);
}

static void initialise_wifi(void)
{
  esp_err_t err = esp_event_loop_create_default();  
  if (err != ESP_OK && err != ESP_ERR_INVALID_STATE)  {    
  	ESP_ERROR_CHECK(err);  
  }  
  ESP_ERROR_CHECK(esp_netif_init());  
  char *desc;  
  wifi_init_config_t cfg = WIFI_INIT_CONFIG_DEFAULT();  
  ESP_ERROR_CHECK(esp_wifi_init(&cfg));  
  ESP_ERROR_CHECK(esp_wifi_set_storage(WIFI_STORAGE_RAM));  
  esp_netif_inherent_config_t esp_netif_config = ESP_NETIF_INHERENT_DEFAULT_WIFI_STA();  
  // Prefix the interface description with the module TAG  
  // Warning: the interface desc is used in tests to capture actual connection details (IP, gw, mask)  
  asprintf(&desc, "%s: %s", TAG, esp_netif_config.if_desc);  
  esp_netif_config.if_desc = desc;  
  esp_netif_config.route_prio = 128;  
  esp_netif_t *netif = esp_netif_create_wifi(WIFI_IF_STA, &esp_netif_config);  
  free(desc);  
  ESP_ERROR_CHECK(esp_wifi_set_default_wifi_sta_handlers());  
  wifi_event_group = xEventGroupCreate();  
  ESP_ERROR_CHECK(esp_event_handler_register(WIFI_EVENT, WIFI_EVENT_STA_DISCONNECTED, sta_disconnected, NULL));  
  ESP_ERROR_CHECK(esp_event_handler_register(WIFI_EVENT, WIFI_EVENT_STA_START, sta_start, NULL));  
  ESP_ERROR_CHECK(esp_event_handler_register(WIFI_EVENT, WIFI_EVENT_STA_CONNECTED, sta_connected, netif));  
  ESP_ERROR_CHECK(esp_event_handler_register(IP_EVENT, IP_EVENT_STA_GOT_IP, got_ip, NULL));  
  ESP_ERROR_CHECK(esp_event_handler_register(IP_EVENT, IP_EVENT_GOT_IP6, got_ip6, NULL));  
  wifi_config_t wifi_config = {      
  	.sta = {          
		.ssid = EXAMPLE_WIFI_SSID,          
		.password = EXAMPLE_WIFI_PASS,      
	},  
  };  
  ESP_ERROR_CHECK(esp_wifi_set_mode(WIFI_MODE_STA));  
  ESP_ERROR_CHECK(esp_wifi_set_config(ESP_IF_WIFI_STA, &wifi_config));  
  ESP_ERROR_CHECK(esp_wifi_start());  
}

void heap_dbg(void)
{
	printf("free heap size:%d\n", esp_get_free_heap_size());
	printf("minimum free heap size:%d\n", esp_get_minimum_free_heap_size());
}
static void gen_svr_tag(const char *name, size_t device_index, char *svr_tag)
{
  int svr_tag_len =
    snprintf(svr_tag, SVR_TAG_MAX, "%s_%zd", name, device_index);
  svr_tag_len =
    (svr_tag_len < SVR_TAG_MAX - 1) ? svr_tag_len + 1 : SVR_TAG_MAX - 1;
  svr_tag[svr_tag_len] = '\0';
}

int storage_config(const char *store)
{
  storePath_len = strlen(store);
  if (storePath_len >= STORE_PATH_SIZE) {
    return -ENOENT;
  }

  memcpy(storePath, store, storePath_len);
  storePath[storePath_len] = '\0';
  pathSet = true;

  return 0;
}

long storage_read(const char *store, uint8_t *buf, size_t size)
{
  printf("storage_read: %s\r\n", store);
  if (!pathSet)
  {
    return -ENOENT;
  }
  nvs_handle_t handle;
  esp_err_t err = nvs_open(storePath, NVS_READONLY, &handle);
  if (err != ESP_OK)
  {
    printf("storage_read cannot nvs_open %s: %d\r\n", store, err);
    return -EINVAL;
  }

  err = nvs_get_blob(handle, store, buf, &size);
  if (err != ESP_OK)
  {
    printf("storage_read cannot nvs_get_blob  %s: %d\r\n", store, err);
    nvs_close(handle);
    return -EINVAL;
  }

  nvs_close(handle);
  return size;
}


long storage_write(const char *store, uint8_t *buf, size_t size)
{
  if (!pathSet)
  {
    return -ENOENT;
  }
  nvs_handle_t handle;
  esp_err_t err = nvs_open(storePath, NVS_READWRITE, &handle);
  if (err != ESP_OK)
  {
    printf("storage_write cannot nvs_open  %s: %d\r\n", store, err);
    return -EINVAL;
  }

  err = nvs_set_blob(handle, store, buf, size);
  if (err != ESP_OK)
  {
    printf("storage_write cannot nvs_set_blob  %s: %d\r\n", store, err);
    nvs_close(handle);
    return -EINVAL;
  }

  err = nvs_commit(handle);
  if (err != ESP_OK)
  {
    printf("storage_write cannot nvs_commit  %s: %d\r\n", store, err);
    nvs_close(handle);
    return -EINVAL;
  }

  return size;
}

void Test (void *arg) 
{    
	long ret = 0;
	int size = 0;
	size_t device= 0;
	static const char *TASK_TAG = "Test_TASK";    	
	esp_log_level_set(TASK_TAG, ESP_LOG_INFO);  

	char svr_tag[SVR_TAG_MAX] = {0,};

	tcpip_adapter_ip_info_t ip4_info = {0};
	struct ip6_addr if_ipaddr_ip6 = {0};
	ESP_LOGI(TAG, "iotivity server task started");
	// wait to fetch IPv4 && ipv6 address
	xEventGroupWaitBits(wifi_event_group, IPV4_CONNECTED_BIT | IPV6_CONNECTED_BIT, false, true, portMAX_DELAY);
	xEventGroupWaitBits(wifi_event_group, IPV6_CONNECTED_BIT, false, true, portMAX_DELAY);

	if (tcpip_adapter_get_ip_info(TCPIP_ADAPTER_IF_STA, &ip4_info) != ESP_OK) {
		printf("get IPv4 address failed\r\n");
	} else {
		ESP_LOGI(TAG, "got IPv4 addr:%s", ip4addr_ntoa(&(ip4_info.ip)));
	}

	if (tcpip_adapter_get_ip6_linklocal(TCPIP_ADAPTER_IF_STA, &if_ipaddr_ip6) != ESP_OK) {
		printf("get IPv6 address failed\r\n");
	} else {
		ESP_LOGI(TAG, "got IPv6 addr:%s", ip6addr_ntoa(&if_ipaddr_ip6));
	}	
	
	storage_config("storage");
	
	while (1) { 	
		uint8_t *buf = malloc(MAX_APP_DATA_SIZE);
		if (!buf) {
			printf("memory allocation failed\r\n");
		}

		memcpy(buf, "12345678901234567890", 20);

		gen_svr_tag("doxm", device, svr_tag);
		ret = storage_write(svr_tag, buf, size);
		printf("storage_write(), ret=%ld, %s\r\n", ret, buf);

		free(buf);

		heap_dbg();

		printf("\ntestCount:%d\n", testCount);

		testCount++;

		vTaskDelay(1000 / portTICK_RATE_MS);
	}    
}

void app_main(void)
{
	if (nvs_flash_init() != ESP_OK) {
		printf("nvs_flash_init failed\r\n");
	}

	initialise_wifi();

	// Create the task without using any dynamic memory allocation.
 	if ( xTaskCreate(&Test, "Test", 
		1024*10, 
		NULL, configMAX_PRIORITIES - 2, NULL) != pdPASS ) {
		printf("task create failed(Test)\r\n");
	}	
 }


```
// If your code is longer than 30 lines, [GIST](https://gist.github.com) is preferred.

## Debug Logs
testCount:204
ets Jun  8 2016 00:22:57

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:4
load:0x3fff0034,len:7200
ho 0 tail 12 room 4
load:0x40078000,len:14848
load:0x40080400,len:3068
entry 0x40080600
I (31) boot: ESP-IDF v4.3-dev-1521-g0289d1c-dirty 2nd stage bootloader
I (31) boot: compile time 21:22:04
I (32) boot: chip revision: 1
I (36) boot_comm: chip revision: 1, min. bootloader chip revision: 0
I (43) boot.esp32: SPI Speed      : 40MHz
I (47) boot.esp32: SPI Mode       : DIO
I (52) boot.esp32: SPI Flash Size : 4MB
I (56) boot: Enabling RNG early entropy source...
I (62) boot: Partition Table:
I (65) boot: ## Label            Usage          Type ST Offset   Length
I (73) boot:  0 nvs              WiFi data        01 02 00009000 00006000
I (80) boot:  1 phy_init         RF data          01 01 0000f000 00001000
I (88) boot:  2 factory          factory app      00 00 00010000 00140000
I (95) boot:  3 storage          OTA data         01 00 00150000 00030000
I (103) boot: End of partition table
I (107) boot: Defaulting to factory image
I (112) boot_comm: chip revision: 1, min. application chip revision: 0
I (119) esp_image: segment 0: paddr=0x00010020 vaddr=0x3f400020 size=0x16bcc ( 93132) map
I (163) esp_image: segment 1: paddr=0x00026bf4 vaddr=0x3ffbdb60 size=0x04e9c ( 20124) load
I (172) esp_image: segment 2: paddr=0x0002ba98 vaddr=0x40080000 size=0x00404 (  1028) load
I (173) esp_image: segment 3: paddr=0x0002bea4 vaddr=0x40080404 size=0x04174 ( 16756) load
I (186) esp_image: segment 4: paddr=0x00030020 vaddr=0x400d0020 size=0x71178 (463224) map
I (364) esp_image: segment 5: paddr=0x000a11a0 vaddr=0x40084578 size=0x15ce4 ( 89316) load
I (418) boot: Loaded app from partition at offset 0x10000
I (418) boot: Disabling RNG early entropy source...
I (430) cpu_start: Pro cpu up.
I (430) cpu_start: Starting app cpu, entry point is 0x400815c8
I (0) cpu_start: App cpu up.
I (444) cpu_start: Pro cpu start user code
I (444) cpu_start: cpu freq: 160000000
I (444) cpu_start: Application information:
I (448) cpu_start: Project name:     KD_iotivity_server
I (454) cpu_start: App version:      2.2.0-28-g9fc5ba6-dirty
I (461) cpu_start: Compile time:     Dec 16 2020 14:57:24
I (467) cpu_start: ELF file SHA256:  007967e66e54fdd7...
I (473) cpu_start: ESP-IDF:          v4.3-dev-1521-g0289d1c-dirty
I (480) heap_init: Initializing. RAM available for dynamic allocation:
I (487) heap_init: At 3FFAE6E0 len 0000F480 (61 KiB): DRAM
I (493) heap_init: At 3FFC71F8 len 00018E08 (99 KiB): DRAM
I (499) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM
I (505) heap_init: At 3FFE4350 len 00013CB0 (79 KiB): D/IRAM
I (512) heap_init: At 4009A25C len 00005DA4 (23 KiB): IRAM
I (519) esp_apptrace: Initialized TRAX on CPU0
I (523) spi_flash: detected chip: generic
I (528) spi_flash: flash io: dio
I (533) cpu_start: Starting scheduler on PRO CPU.
I (100) esp_apptrace: Initialized TRAX on CPU1
I (0) cpu_start: Starting scheduler on APP CPU.
I (757) wifi:wifi driver task: 3ffb9704, prio:23, stack:6656, core=0
I (757) system_api: Base MAC address is not set
I (757) system_api: read default base MAC address from EFUSE
I (797) wifi:wifi firmware version: a94a000
I (797) wifi:wifi certification version: v7.0
I (797) wifi:config NVS flash: enabled
I (797) wifi:config nano formating: disabled
I (807) wifi:Init data frame dynamic rx buffer num: 32
I (807) wifi:Init management frame dynamic rx buffer num: 32
I (817) wifi:Init management short buffer num: 32
I (817) wifi:Init static tx buffer num: 16
I (827) wifi:Init static rx buffer size: 1600
I (827) wifi:Init static rx buffer num: 10
I (827) wifi:Init dynamic rx buffer num: 32
I (837) wifi_init: rx ba win: 6
I (837) wifi_init: tcpip mbox: 32
I (847) wifi_init: udp mbox: 6
I (847) wifi_init: tcp mbox: 6
I (847) wifi_init: tcp tx win: 5744
I (857) wifi_init: tcp rx win: 5744
I (857) wifi_init: tcp mss: 1440
I (867) wifi_init: WiFi IRAM OP enabled
I (867) wifi_init: WiFi RX IRAM OP enabled
I (867) wifi_init: LWIP IRAM OP enabled
I (987) phy: phy_version: 4500, 0cd6843, Sep 17 2020, 15:37:07, 0, 0
I (987) wifi:mode : sta (24:6f:28:de:6b:c0)
I (987) wifi:enable tsf
I (987) iotivity server: iotivity server task started
I (1477) wifi:new:<4,0>, old:<1,0>, ap:<255,255>, sta:<4,0>, prof:1
I (2307) wifi:state: init -> auth (b0)
I (2317) wifi:state: auth -> assoc (0)
I (2317) wifi:state: assoc -> init (3c0)
I (2317) wifi:new:<4,0>, old:<4,0>, ap:<255,255>, sta:<4,0>, prof:1
I (4497) wifi:new:<4,0>, old:<4,0>, ap:<255,255>, sta:<4,0>, prof:1
I (4497) wifi:state: init -> auth (b0)
I (4497) wifi:state: auth -> assoc (0)
I (4507) wifi:state: assoc -> run (10)
I (4517) wifi:connected with TP-Link_FC80, aid = 4, channel 4, BW20, bssid = 84:d8:1b:35:fc:7f
I (4517) wifi:security: WPA2-PSK, phy: bgn, rssi: -20
I (4517) wifi:pm start, type: 1

W (4537) wifi:<ba-add>idx:0 (ifx:0, 84:d8:1b:35:fc:7f), tid:5, ssn:2, winSize:64
I (4577) wifi:AP's beacon interval = 102400 us, DTIM period = 1
I (5247) esp_netif_handlers: iotivity server: sta ip: 192.168.0.234, mask: 255.255.255.0, gw: 192.168.0.1
I (5747) iotivity server: got IPv4 addr:192.168.0.234
I (5747) iotivity server: got IPv6 addr:FE80::266F:28FF:FEDE:6BC0
storage_write(), ret=0, 12345678901234567890k?
**free heap size:150300**
minimum free heap size:136388

testCount:0
storage_write(), ret=0, 12345678901234567890
**free heap size:150276**
minimum free heap size:136388

testCount:1
storage_write(), ret=0, 12345678901234567890
**free heap size:150236**
minimum free heap size:136388

testCount:2
storage_write(), ret=0, 12345678901234567890
**free heap size:150196**
minimum free heap size:136388

testCount:3
storage_write(), ret=0, 12345678901234567890
**free heap size:150160**
minimum free heap size:136388

testCount:4
storage_write(), ret=0, 12345678901234567890
**free heap size:150120**
minimum free heap size:136388
```
Debug log goes here, should contain the backtrace, as well as the reset source if it is a crash.
Please copy the plain text here for us to search the error log. Or attach the complete logs but leave the main part here if the log is *too* long.
```

## Other items if possible

- [ ] sdkconfig file (attach the sdkconfig file from your project folder)
[sdkconfig.txt](https://github.com/espressif/esp-idf/files/5701590/sdkconfig.txt)

- [ ] elf file in the ``build`` folder (**note this may contain all the code details and symbols of your project.**)
[KD_iotivity_server.elf.txt](https://github.com/espressif/esp-idf/files/5701593/KD_iotivity_server.elf.txt)

- [ ] coredump (This provides stacks of tasks.)

**Comment by Alvin1Zhang** [comment]
Thanks for the detailed report and letting us know, we will look into.

**Comment by igrr** [comment]
@ansee7221 Could you check `storage_write` function, it seems it calls nvs_open every time, but doesn't call nvs_close in case of success.
For debugging heap memory leaks, please see the instructions in https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/heap_debug.html#heap-tracing.

**Comment by 0xjakob** [comment]
Hi @ansee7221,
Thanks for trying out current code!

Could you try to turn on [stand alone heap tracing](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/heap_debug.html?highlight=memory#heap-tracing) in menuconfig?

There should be some configuration options regarding stack depth, etc., if I remember correctly. You'll get trace output which provide valuable information where (de-)allocations occur. Let us know how it goes.

Thanks,
Jakob

**Comment by boarchuz** [comment]
Your storage_write is missing nvs_close

**Comment by ansee7221** [comment]
@boarchuz, Thanks.
I missed nvs_close.
