### ISSUE TITLE
ESP_TLS_ERR_SSL_WANT_READ undeclared (IDFGH-4456)

### ISSUE THREAD

**Issue by smokezp** [espressif/esp-idf#6287]
Hi, I have issue. I'm trying to install sh2lib.h.
I followed instructions: [https://techtutorialsx.com/2018/11/23/esp32-http-2-get-request-with-continuous-stream-response/](url)
Also I found almost the same instruction on youtube.

## Environment

- Development Kit:      [ESP32-Wrover-Kit|ESP32-DevKitC|ESP32-PICO-Kit|ESP32-LyraT|ESP32-LyraTD-MSC|none]
- Kit version (for WroverKit/PicoKit/DevKitC): [v1|v2|v3|v4]
- Module or chip used:  [ESP32-WROOM-32|ESP32-WROOM-32D|ESP32-WROOM-32U|ESP32-WROVER|ESP32-WROVER-I|ESP32-WROVER-B|ESP32-WROVER-IB|ESP32-SOLO-1|ESP32-PICO-D4|ESP32]
- IDF version (run ``git describe --tags`` to find it):
    // v3.2-dev-1148-g96cd3b75c
- Build System:         [Make|CMake|idf.py]
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it):
    // 1.22.0-80-g6c4433a
- Operating System:     [Windows|Linux|macOS]
- (Windows only) environment type: [MSYS2 mingw32|ESP Command Prompt|Plain Command Prompt|PowerShell].
- Using an IDE?: [No|Yes (please give details)]
- Power Supply:         [USB|external 5V|external 3.3V|Battery]

## Problem Description
I get an error:

libraries/sh2lib/sh2lib.c: In function 'callback_send_inner':
libraries/sh2lib/sh2lib.c:42:19: error: 'ESP_TLS_ERR_SSL_WANT_READ' undeclared (first use in this function)
         if (rv == ESP_TLS_ERR_SSL_WANT_READ || rv == ESP_TLS_ERR_SSL_WANT_WRITE) {
         
It looks like const ESP_TLS_ERR_SSL_WANT_READ is not declared. From where it should come? what am I going wrong?   

### Steps to reproduce

1. Added folder sh2lib with files sh2lib.c and sh2lib.h
2. Upload the code.

### Code to reproduce this issue

```cpp
// the code should be wrapped in the ```cpp tag so that it will be displayed better.

extern "C" {
#include <sh2lib.h>
}

**Comment by mahavirj** [comment]
@smokezp 

This is defined at below:
https://github.com/espressif/esp-idf/blob/b0150615dff529662772a60dcb57d5b559f480e2/components/esp-tls/esp_tls.h#L69

Can you please try with latest IDF release?

**Comment by mahavirj** [comment]
@smokezp Closing the issue, please feel free to re-open if you are still facing issue with latest IDF release

**Comment by raysconcept** [comment]
Hi Mahavirj, I am having the exact samen problem. Can you explain your solution? How should I try the latest IDF release? Thx in advance!

**Comment by mahavirj** [comment]
@raysconcept 

Please see following pointers:

https://docs.espressif.com/projects/esp-idf/en/latest/esp32/get-started/index.html#step-2-get-esp-idf
https://docs.espressif.com/projects/esp-idf/en/latest/esp32/versions.html

**Comment by raysconcept** [comment]
Thank you very much! I am installing that now. 
Though..I have already arduinoIDE, VisualStudio and Eclipse installed. How does IDF relate to any of those?

**Comment by raysconcept** [comment]
![image](https://user-images.githubusercontent.com/7370380/114763072-b42aed00-9d62-11eb-80b7-75f6e070dca0.png)

**Comment by AL5Volgar** [comment]
Hi,

I want to use the sh2lib library for my project.
However i have the same error as the first comment : 
![image](https://user-images.githubusercontent.com/95085363/143584849-82699a35-0a1c-439f-afa6-977c4ffdedda.png)

![InkedCapture_LI](https://user-images.githubusercontent.com/95085363/143584649-c8a1efe3-8c54-4bf5-a342-fac83943d181.jpg)

I'm currently using the Arduino IDE, and I have already installed ESP IDF 4.3

Can you help me ?
