### ISSUE TITLE
ver 4.3 bugs missing interrupt header file and other bugs (IDFGH-4468)

### ISSUE THREAD

**Issue by elo1957** [espressif/esp-idf#6299]
I get this when compiling

C:/Users/osc/Desktop/esp-idf/components/esp32/cache_err_int.c:42:5: error: implicit declaration of function 'ESP_INTR_DISABLE'; did you mean 'ESP_INTR_FLAG_NMI'? [-Werror=implicit-function-declaration]
     ESP_INTR_DISABLE(ETS_MEMACCESS_ERR_INUM);
     ^~~~~~~~~~~~~~~~
     ESP_INTR_FLAG_NMI
C:/Users/osc/Desktop/esp-idf/components/esp32/cache_err_int.c:76:5: error: implicit declaration of function 'ESP_INTR_ENABLE'; did you mean 'INTENABLE'? [-Werror=implicit-function-declaration]
     ESP_INTR_ENABLE(ETS_MEMACCESS_ERR_INUM);
     ^~~~~~~~~~~~~~~
     INTENABLE
I have made  and update from git in the official esp-idf  now and then errors first this file esp_intr_alloc.h where missing in C:\Users\osc\Desktop\esp-idf\components\esp32\include  - i added it found it in the sdk for arduino

**Comment by Alvin1Zhang** [comment]
@elo1957 Thanks for reporting. Would you please help provide more details as suggested in the [issue template](https://github.com/espressif/esp-idf/issues/new?assignees=&labels=&template=bug_report.md&title=)? Information like elf, sdk configuration, backtrace, log outputs, commit ID, hardware and etc. would help us debug further. Thanks.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close now, feel free to reopen with more details provided as per the issue template, thanks.
