### ISSUE TITLE
When using WroverKit PSRAM and Bluetooth, "memory allocation failed" occurs. (IDFGH-4473)

### ISSUE THREAD

**Issue by ansee7221** [espressif/esp-idf#6303]
## Environment

- Development Kit:      [ESP32-Wrover-Kit]
- Kit version (for WroverKit): [v1|v2|v3|v4]
- Module or chip used:  [ESP32-WROVER]
- IDF version (run ``git describe --tags`` to find it):
    // v4.3-dev-1521-g0289d1c-dirty
- Build System:         [Make|CMake|idf.py]
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it):
    // xtensa-esp32-elf-gcc (crosstool-NG esp-2020r3) 8.4.0
- Operating System:     [Linux]
- (Windows only) environment type: [MSYS2 mingw32|ESP Command Prompt|Plain Command Prompt|PowerShell].
- Using an IDE?: [No]
- Power Supply:         [USB]

## Problem Description
When using WROVER PSRAM and Bluetooth, "memory allocation fail" occurs.
If "bluetooth" is not used through menuconfig, it works normally.

//Detailed problem description goes here.

### Steps to reproduce

// If possible, attach a picture of your setup/wiring here.

### Code to reproduce this issue

```cpp
// the code should be wrapped in the ```cpp tag so that it will be displayed better.
#include "esp_log.h"

void heap_dbg(void)
{
	printf("free heap size:%d\n", esp_get_free_heap_size());
	printf("minimum free heap size:%d\n", esp_get_minimum_free_heap_size());
	
	#ifdef EXTERNAL_PSRAM_USE
	printf("free internal memory: %u lifetime minimum: %u\n",
		heap_caps_get_free_size(MALLOC_CAP_INTERNAL|MALLOC_CAP_8BIT),
		heap_caps_get_minimum_free_size(MALLOC_CAP_INTERNAL|MALLOC_CAP_8BIT));
	printf("integrity check: %d\n", heap_caps_check_integrity(MALLOC_CAP_INTERNAL|MALLOC_CAP_8BIT, true));	
	#endif
}

void server_main (void *arg) 
{    
	int init = 0;	
	long ret = 0;
	int size = 0;
	size_t device= 0;

	tcpip_adapter_ip_info_t ip4_info = {0};
	struct ip6_addr if_ipaddr_ip6 = {0};

	printf("iotivity server task started\r\n");
	
	// wait to fetch IPv4 && ipv6 address
	xEventGroupWaitBits(wifi_event_group, IPV4_CONNECTED_BIT | IPV6_CONNECTED_BIT, false, true, portMAX_DELAY);
	xEventGroupWaitBits(wifi_event_group, IPV6_CONNECTED_BIT, false, true, portMAX_DELAY);

	if (tcpip_adapter_get_ip_info(TCPIP_ADAPTER_IF_STA, &ip4_info) != ESP_OK) {
		printf("get IPv4 address failed\r\n");
	} else {
		printf("got IPv4 addr:%s\r\n", ip4addr_ntoa(&(ip4_info.ip)));
	}

	if (tcpip_adapter_get_ip6_linklocal(TCPIP_ADAPTER_IF_STA, &if_ipaddr_ip6) != ESP_OK) {
		printf("get IPv6 address failed\r\n");
	} else {
		printf("got IPv6 addr:%s\r\n", ip6addr_ntoa(&if_ipaddr_ip6));
	}
	
	while (1) { 		
		heap_dbg();
		vTaskDelay(1000*10 / portTICK_RATE_MS);
	}  
}

void app_main(void)
{
	if (nvs_flash_init() != ESP_OK) {
		printf("nvs_flash_init failed\r\n");
	}

	initialise_wifi();

#ifdef BLE_USE
	esp_err_t ret = 0;
	ESP_ERROR_CHECK(esp_bt_controller_mem_release(ESP_BT_MODE_CLASSIC_BT));

	esp_bt_controller_config_t bt_cfg = BT_CONTROLLER_INIT_CONFIG_DEFAULT();
	ret = esp_bt_controller_init(&bt_cfg);
	if (ret) {
		printf("%s initialize bt controller failed: %s\n", __func__, esp_err_to_name(ret));
	}

	ret = esp_bt_controller_enable(ESP_BT_MODE_BLE);
	if (ret) {
		printf("%s enable bt controller failed: %s\n", __func__, esp_err_to_name(ret));
		return;
	}

	ret = esp_bluedroid_init();
	if (ret) {
		printf("%s init bluedroid failed: %s\n", __func__, esp_err_to_name(ret));
		return;
	}

	ret = esp_bluedroid_enable();
	if (ret) {
		printf("%s init bluedroid failed: %s\n", __func__, esp_err_to_name(ret));
		return;
	}

	printf("BD ADDR: "ESP_BD_ADDR_STR"\n", ESP_BD_ADDR_HEX(esp_bt_dev_get_address()));
	printf("BLUFI VERSION %04x\n", esp_blufi_get_version());

	ret = esp_ble_gap_register_callback(gap_event_handler);
	if(ret){
		printf("%s gap register failed, error code = %x\n", __func__, ret);
		return;
	}

	ret = esp_blufi_register_callbacks(&esp_blufi_callbacks);
	if(ret){
		printf("%s blufi register failed, error code = %x\n", __func__, ret);
		return;
	}

	esp_blufi_profile_init();	
#endif // BLE_USE	

#ifdef EXTERNAL_PSRAM_USE
	printf("==== EXTERNAL_PSRAM_USE =====\r\n");
	// Create the task without using any dynamic memory allocation.
	xHandle = xTaskCreateStatic(	  
	server_main,	 // Function that implements the task.		
	"server_main", // Text name for the task.	   
	STACK_SIZE,	  // Stack size in bytes, not words.	  
	NULL, 		 // Parameter passed into the task. 	 
	5, 			// Priority at which the task is created.	   
	xStack,		  // Array to use as the task's stack.		
	&xTaskBuffer); // Variable to hold the task's data structure.

	if (xHandle == NULL) {
		printf("task create failed (server_main)\r\n");
	} 

#endif
 }

```
// If your code is longer than 30 lines, [GIST](https://gist.github.com) is preferred.

## Debug Logs
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x1e (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:4
load:0x3fff0034,len:7136
ho 0 tail 12 room 4
load:0x40078000,len:15316
load:0x40080400,len:3108
entry 0x40080600
I (31) boot: ESP-IDF v4.3-dev-1521-g0289d1c-dirty 2nd stage bootloader
I (31) boot: compile time 10:38:15
I (32) boot: chip revision: 1
I (36) boot_comm: chip revision: 1, min. bootloader chip revision: 0
I (43) boot.esp32: SPI Speed      : 40MHz
I (47) boot.esp32: SPI Mode       : DIO
I (52) boot.esp32: SPI Flash Size : 4MB
I (56) boot: Enabling RNG early entropy source...
I (62) boot: Partition Table:
I (65) boot: ## Label            Usage          Type ST Offset   Length
I (73) boot:  0 nvs              WiFi data        01 02 00009000 00006000
I (80) boot:  1 phy_init         RF data          01 01 0000f000 00001000
I (88) boot:  2 factory          factory app      00 00 00010000 00190000
I (95) boot:  3 storage          OTA data         01 00 001a0000 00030000
I (103) boot: End of partition table
I (107) boot: Defaulting to factory image
I (111) boot_comm: chip revision: 1, min. application chip revision: 0
I (119) esp_image: segment 0: paddr=0x00010020 vaddr=0x3f400020 size=0x2b604 (177668) map
I (202) esp_image: segment 1: paddr=0x0003b62c vaddr=0x3ffbdb60 size=0x049ec ( 18924) load
I (211) esp_image: segment 2: paddr=0x00040020 vaddr=0x400d0020 size=0xd8fd4 (888788) map
I (582) esp_image: segment 3: paddr=0x00118ffc vaddr=0x3ffc254c size=0x00b00 (  2816) load
I (583) esp_image: segment 4: paddr=0x00119b04 vaddr=0x40080000 size=0x00404 (  1028) load
I (589) esp_image: segment 5: paddr=0x00119f10 vaddr=0x40080404 size=0x1b8a0 (112800) load
I (667) boot: Loaded app from partition at offset 0x10000
I (668) boot: Disabling RNG early entropy source...
I (679) psram: This chip is ESP32-D0WD
I (680) spiram: Found 64MBit SPI RAM device
I (680) spiram: SPI RAM mode: flash 40m sram 40m
I (685) spiram: PSRAM initialized, cache is in low/high (2-core) mode.
I (692) cpu_start: Pro cpu up.
I (696) cpu_start: Starting app cpu, entry point is 0x400814cc
I (687) cpu_start: App cpu up.
I (1565) spiram: SPI SRAM memory test OK
I (1573) cpu_start: Pro cpu start user code
I (1573) cpu_start: cpu freq: 160000000
I (1574) cpu_start: Application information:
I (1577) cpu_start: Project name:     KD_iotivity_server
I (1582) cpu_start: App version:      2.2.0-28-g9fc5ba6-dirty
I (1589) cpu_start: Compile time:     Dec 21 2020 14:37:01
I (1595) cpu_start: ELF file SHA256:  002574f1670f654b...
I (1601) cpu_start: ESP-IDF:          v4.3-dev-1521-g0289d1c-dirty
I (1608) heap_init: Initializing. RAM available for dynamic allocation:
I (1615) heap_init: At 3FFAFF10 len 000000F0 (0 KiB): DRAM
I (1621) heap_init: At 3FFB6388 len 00001C78 (7 KiB): DRAM
I (1628) heap_init: At 3FFB9A20 len 00004108 (16 KiB): DRAM
I (1634) heap_init: At 3FFCF808 len 000107F8 (65 KiB): DRAM
I (1640) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM
I (1647) heap_init: At 3FFE4350 len 00013CB0 (79 KiB): D/IRAM
I (1653) heap_init: At 4009BCA4 len 0000435C (16 KiB): IRAM
I (1659) spiram: Adding pool of 4096K of external SPI memory to heap allocator
I (1668) esp_apptrace: Initialized TRAX on CPU0
I (1673) spi_flash: detected chip: generic
I (1677) spi_flash: flash io: dio
I (1683) cpu_start: Starting scheduler on PRO CPU.
I (892) esp_apptrace: Initialized TRAX on CPU1
I (0) cpu_start: Starting scheduler on APP CPU.
I (1947) wifi:wifi driver task: 3ffd6334, prio:23, stack:6656, core=0
I (1947) system_api: Base MAC address is not set
I (1947) system_api: read default base MAC address from EFUSE
I (1997) wifi:wifi firmware version: a94a000-dirty
I (1997) wifi:wifi certification version: v7.0
I (1997) wifi:config NVS flash: enabled
I (1997) wifi:config nano formating: disabled
I (1997) wifi:Init data frame dynamic rx buffer num: 32
I (2007) wifi:Init management frame dynamic rx buffer num: 32
I (2007) wifi:Init management short buffer num: 32
I (2017) wifi:Init static tx buffer num: 16
I (2017) wifi:Init tx cache buffer num: 32
I (2027) wifi:Init static rx buffer size: 1600
I (2027) wifi:Init static rx buffer num: 10
I (2037) wifi:Init dynamic rx buffer num: 32
I (2037) wifi_init: rx ba win: 6
I (2037) wifi_init: tcpip mbox: 32
I (2047) wifi_init: udp mbox: 6
I (2047) wifi_init: tcp mbox: 6
I (2047) wifi_init: tcp tx win: 5744
I (2057) wifi_init: tcp rx win: 5744
I (2057) wifi_init: tcp mss: 1440
I (2067) wifi_init: WiFi/LWIP prefer SPIRAM
I (2177) phy: phy_version: 4500, 0cd6843, Sep 17 2020, 15:37:07, 0, 0
I (2187) wifi:mode : sta (ac:67:b2:71:61:7c)
I (2187) wifi:enable tsf
**I (2187) BTDM_INIT: BT controller compile version [b73c48e]**

**Memory allocation failed**

Backtrace:0x4009399e:0x3ffe5b90 0x400942c5:0x3ffe5bb0 0x400d46cb:0x3ffe5bd0 0x40083906:0x3ffe5bf0 0x40083921:0x3ffe5c20 0x40099cb3:0x3ffe5c40 0x40099cd4:0x3ffe5c60 0x401265f7:0x3ffe5c80 0x400feb48:0x3ffe5ce0 0x400ff0e4:0x3ffe5d00 0x40125a69:0x3ffe5d30 0x40127baf:0x3ffe5d50

ELF file SHA256: 002574f1670f654b

Rebooting...

```
Debug log goes here, should contain the backtrace, as well as the reset source if it is a crash.
Please copy the plain text here for us to search the error log. Or attach the complete logs but leave the main part here if the log is *too* long.
```

## Other items if possible

- [ ] sdkconfig file (attach the sdkconfig file from your project folder) 
[sdkconfig.txt](https://github.com/espressif/esp-idf/files/5722842/sdkconfig.txt)

- [ ] elf file in the ``build`` folder (**note this may contain all the code details and symbols of your project.**) 
[KD_iotivity_server.elf.txt](https://github.com/espressif/esp-idf/files/5722846/KD_iotivity_server.elf.txt)

- [ ] coredump (This provides stacks of tasks.)

**Comment by chegewara** [comment]
Please check in menuconfig option that enables `xTaskCreateStatic` to use PSRAM, its been introduced recently.

**Comment by ansee7221** [comment]
@chegewara, If I set the option to "heap_caps_malloc" in menuconfig, there is no "Allow external memory as an argument to xTaskCreateStatic" item.  
Also, as a result of testing with external PSRAM disabled in menuconfig, a "Memory allocation failed" error occurs. The error does not seem to be related to the use of external PSRAM.

**Comment by chegewara** [comment]
This is new option in v4.3 you have to enable:
```
Name: SPIRAM_ALLOW_STACK_EXTERNAL_MEMORY
Prompt: Allow external memory as an argument to xTaskCreateStatic
Type: bool
Value: n

Help:

  Because some bits of the ESP32 code environment cannot be recompiled with the cache workaround,
  normally tasks cannot be safely run with their stack residing in external memory; for this reason
  xTaskCreate and friends always allocate stack in internal memory and xTaskCreateStatic will check if
  the memory passed to it is in internal memory. If you have a task that needs a large amount of stack
  and does not call on ROM code in any way (no direct calls, but also no Bluetooth/WiFi), you can try to
  disable this and use xTaskCreateStatic to create the tasks stack in external memory.
```

**Comment by boblane1** [comment]
Hi @ansee7221,

I guess your code is developed based on the example of blufi, and the demo can work without any problem. According to the backtrace and .elf file which you gave, it seems that the memory allocation failed when retrieving the configuration in the nvs flash. I suggest you to erase the whole flash first and then download your application code to see if the problem still exists.

Thanks!

**Comment by ansee7221** [comment]
> This is new option in v4.3 you have to enable:
> 
> ```
> Name: SPIRAM_ALLOW_STACK_EXTERNAL_MEMORY
> Prompt: Allow external memory as an argument to xTaskCreateStatic
> Type: bool
> Value: n
> 
> Help:
> 
>   Because some bits of the ESP32 code environment cannot be recompiled with the cache workaround,
>   normally tasks cannot be safely run with their stack residing in external memory; for this reason
>   xTaskCreate and friends always allocate stack in internal memory and xTaskCreateStatic will check if
>   the memory passed to it is in internal memory. If you have a task that needs a large amount of stack
>   and does not call on ROM code in any way (no direct calls, but also no Bluetooth/WiFi), you can try to
>   disable this and use xTaskCreateStatic to create the tasks stack in external memory.
> ```

**Comment by ansee7221** [comment]
> This is new option in v4.3 you have to enable:
> 
> ```
> Name: SPIRAM_ALLOW_STACK_EXTERNAL_MEMORY
> Prompt: Allow external memory as an argument to xTaskCreateStatic
> Type: bool
> Value: n
> 

The following modifications have been made, but the same symptoms will occur.


#
# SPIRAM cache workaround debugging
#
CONFIG_SPIRAM_CACHE_WORKAROUND_STRATEGY_MEMW=y
# CONFIG_SPIRAM_CACHE_WORKAROUND_STRATEGY_DUPLDST is not set
# CONFIG_SPIRAM_CACHE_WORKAROUND_STRATEGY_NOPS is not set
# end of SPIRAM cache workaround debugging

CONFIG_SPIRAM_BANKSWITCH_ENABLE=y
CONFIG_SPIRAM_BANKSWITCH_RESERVE=8
CONFIG_SPIRAM_ALLOW_STACK_EXTERNAL_MEMORY=y




I (1926) wifi_init: rx ba win: 6
I (1926) wifi_init: tcpip mbox: 32
I (1936) wifi_init: udp mbox: 6
I (1936) wifi_init: tcp mbox: 6
I (1936) wifi_init: tcp tx win: 5744
I (1946) wifi_init: tcp rx win: 5744
I (1946) wifi_init: tcp mss: 1440
I (2056) phy: phy_version: 4500, 0cd6843, Sep 17 2020, 15:37:07, 0, 0
I (2066) wifi:mode : sta (ac:67:b2:71:61:7c)
I (2066) wifi:enable tsf
I (2066) BTDM_INIT: BT controller compile version [b73c48e]

Memory allocation failed

Backtrace:0x400938d2:0x3fff74a0 0x40094211:0x3fff74c0 0x400d4753:0x3fff74e0 0x4008395e:0x3fff7500 0x40083987:0x3fff7530 0x40099c8f:0x3fff7550 0x40099cb0:0x3fff7570 0x4012693f:0x3fff7590 0x4011846a:0x3fff75b0 0x40113155:0x3fff7600 0x401133db:0x3fff7620 0x40127577:0x3fff7640

**Comment by ansee7221** [comment]
> Hi @ansee7221,
> 
> I guess your code is developed based on the example of blufi, and the demo can work without any problem. According to the backtrace and .elf file which you gave, it seems that the memory allocation failed when retrieving the configuration in the nvs flash. I suggest you to erase the whole flash first and then download your application code to see if the problem still exists.
> 
> Thanks!

Hi @boblane1, 
I erased the whole flash and then downloaded application code, but "Memory allocation failed" error still occur.

**Comment by boblane1** [comment]
Hi @ansee7221, 

The attached file is my configuration about PSRAM for blufi demo, you can refer it and have a try. Please pay attention to `CONFIG_SPIRAM_USE_MALLOC`.

Thanks!
[Uploading sdkconfig.txt…]()

**Comment by ansee7221** [comment]
> Hi @ansee7221,
> 
> The attached file is my configuration about PSRAM for blufi demo, you can refer it and have a try. Please pay attention to `CONFIG_SPIRAM_USE_MALLOC`.
> 
> Thanks!
> [sdkconfig.txt](https://github.com/espressif/esp-idf/files/5773943/sdkconfig.txt)

Thank you!
I solved problem by setting it as below.
component config > Application Level Tracing > Data Destination (None)  : Yes -> None

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, glad the issue resolved, feel free to reopen. Thanks.
