### ISSUE TITLE
Failed to resolve component (CMake Build System) (IDFGH-4476)

### ISSUE THREAD

**Issue by benjs** [espressif/esp-idf#6305]
## Environment

- Module or chip used:  [ESP32]
- IDF version (run ``git describe --tags`` to find it): `v4.3-dev-2136-gb0150615d`
- Build System:         [idf.py]
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it): `xtensa-esp32-elf-gcc (crosstool-NG esp-2020r3) 8.4.0`
- Operating System:     [Linux]
- Using an IDE?: [No]
- Power Supply:         [USB]

## Problem Description

I try to setup a new project with one custom component and get the following error when trying to build:
`Failed to resolve component 'example_component'.`

### Steps to reproduce

1. `. $IDF_PATH/export.sh`
2. `idf.py create-project example_project --path example_project`
3. `idf.py create-component example_component`
4. Add to `main/CMakeLists.txt` inside `idf_component_register:` `REQUIRES example_component`
5. `idf.py build`

## Debug Logs

<details>
<summary>Compiler log</summary>
 
```
[0/1] Re-running CMake...
-- Project is not inside a git repository, or git repository has no commits; will not use 'git describe' to determine PROJECT_VER.
-- Building ESP-IDF components for target esp32
CMake Error at /home/username/Documents/projects/esp/esp-idf/tools/cmake/build.cmake:187 (message):
  Failed to resolve component 'example_component'.
Call Stack (most recent call first):
  /home/username/Documents/projects/esp/esp-idf/tools/cmake/build.cmake:213 (__build_resolve_and_add_req)
  /home/username/Documents/projects/esp/esp-idf/tools/cmake/build.cmake:427 (__build_expand_requirements)
  /home/username/Documents/projects/esp/esp-idf/tools/cmake/project.cmake:396 (idf_build_process)
  CMakeLists.txt:8 (project)


-- Configuring incomplete, errors occurred!
See also "/home/username/Documents/projects/esp/example_project/build/CMakeFiles/CMakeOutput.log".
FAILED: build.ninja 
/usr/bin/cmake -S/home/username/Documents/projects/esp/example_project -B/home/username/Documents/projects/esp/example_project/build
ninja: error: rebuilding 'build.ninja': subcommand failed
ninja failed with exit code 1
Executing action: all (aliases: build)
Running ninja in directory /home/username/Documents/projects/esp/example_project/build
Executing "ninja all"...

```
</details>

**Comment by boarchuz** [comment]
`idf.py -C example_project/components create-component example_component`

**Comment by benjs** [comment]
Thanks, that worked! 

However, both file trees are equal. What is different with extra parameter `-C components`?

**Comment by boarchuz** [comment]
The build system will look in IDF_PATH/components and PROJECT_DIR/components by default.

You created `/example_component` (at the same depth as `/example_project`); you needed `/example_project/components/example_component`

https://docs.espressif.com/projects/esp-idf/en/stable/esp32/api-guides/build-system.html#example-project

**Comment by egameezakira14** [comment]
CMake Error at C:/Users/User/.platformio/packages/framework-espidf/tools/cmake/component.cmake:440 (message):
  Called idf_component_register from a non-component directory.
Call Stack (most recent call first):
  CMakeLists.txt:5 (idf_component_register)

**Comment by AlexanderSkvortsov** [comment]
Somthing like this : REQUIRES "example_component" maybe?
