### ISSUE TITLE
UDP Client | Loop exit does not work (IDFGH-4488)

### ISSUE THREAD

**Issue by Oleg-Perevyshin** [espressif/esp-idf#6317]
Hello everyone!
I took as a basis the project of their examples udp_client.

I need to send requests to the broadcast address not constantly, but once every 5 seconds and then wait 30 seconds. This part works provided that there is a device on the network that responds to requests.
The essence of the work is as follows:
- I wrapped the data receiving block in a loop while (1)
- I create a task **taskListenExit** to change the flag **receiverLoopFlag** (in order to exit the reception cycle)
- I send a broadcast request and for 2 seconds I am in a receive cycle in order to receive responses from all devices
- after 2 seconds I have to exit the receive loop and send the next request

The problem is, I cannot get out of the receive loop if there are no devices on the network (no response).
Tell me, am I doing something wrong?
```c
/* Receive data cycle status (for forced exit if no responses) */
bool receiverLoopFlag = 1;

/* The task of exiting the loop waiting for responses */
static void taskListenExit() {
  while (1) {
    vTaskDelay(SMALL_PERIOD_SCAN * 1000 / portTICK_PERIOD_MS);
    receiverLoopFlag = 0;
  }
}

static void taskUDPClient(void * pvParameters) {
  char rx_buffer[1024];
  int addr_family = 0;
  int ip_protocol = 0;
  while (1) {
    struct sockaddr_in dest_addr;
    dest_addr.sin_addr.s_addr = inet_addr(HOST_IP_ADDR);
    dest_addr.sin_family = AF_INET;
    dest_addr.sin_port = htons(PORT);
    addr_family = AF_INET;
    ip_protocol = IPPROTO_IP;

    int sock = socket(addr_family, SOCK_DGRAM, ip_protocol);
    if (sock < 0) {
      break;
    }
    int iRequest = NUM_REQUESTS;
    /* Cycle of periodically sending a packet to search for devices */
    while (1) {
      int err = sendto(sock, SEARCH_PHRASE, strlen(SEARCH_PHRASE), 0, (struct sockaddr *)&dest_addr, sizeof(dest_addr));
      if (err < 0) {
        break;
      }
      receiverLoopFlag = 1;
      /* Waiting cycle for responses */
      while (receiverLoopFlag == 1) {
        struct sockaddr_in source_addr;
        socklen_t socklen = sizeof(source_addr);
        int len = recvfrom(sock, rx_buffer, sizeof(rx_buffer) - 1, 0, (struct sockaddr *)&source_addr, &socklen);
        if (len < 0) {
          break;
        }
        if (len > 0) {
          /* Package processing */
        }
      }
      iRequest--;
      if (iRequest > 0) {
        vTaskDelay(SMALL_PERIOD_SCAN * 1000 / portTICK_PERIOD_MS);
      } else {
        vTaskDelay(LONG_PERIOD_SCAN * 1000 / portTICK_PERIOD_MS);
        iRequest = NUM_REQUESTS;
      }
    }
    if (sock != -1) {
      shutdown(sock, 0);
      close(sock);
    }
  }
  vTaskDelete(NULL);
  }
}

// INIT UDP Client
esp_err_t udpClientInit() {
  if (xTaskCreate(taskUDPClient, "taskUDPClient", 4096, NULL, 5, NULL) != pdPASS) {
    return ESP_FAIL;
  }
  if (xTaskCreate(taskListenExit, "taskListenExit", 4096, NULL, 4, NULL) != pdPASS) {
    return ESP_FAIL;
  }
  return ESP_OK;
}
```
1. Why am I not getting out of the loop `while (receiverLoopFlag == 1)`?
I change the flag and the condition becomes **false**
I checked in the function of task `static void taskListenExit()`, it is called correctly and changes the value of the flag.
2. Can I use cJSON inside a while loop (receiverLoopFlag == 1)?
For the test, I displayed the size of free memory and found that there was a leak with each call. Apparently cJSON_Delete (root) doesn't free memory? I removed part of the code to shorten the code, but the code is standard there.
```c
if (len > 0) {
  /* Package processing */
}
```

**Comment by negativekelvin** [comment]
https://stackoverflow.com/questions/15941005/making-recvfrom-function-non-blocking

**Comment by Oleg-Perevyshin** [comment]
I have read the link. The task matches mine!
But there is very little information and I did not understand anything how to implement it.

Is there an example or a more detailed explanation of how to do this?

**Comment by Oleg-Perevyshin** [comment]
Thanks, figured it out!
