### ISSUE TITLE
UDP Server | Memory leak when using cJSON (IDFGH-4492)

### ISSUE THREAD

**Issue by Oleg-Perevyshin** [espressif/esp-idf#6321]
I am using UDP Server based on example.
I want to return JSON.
I found that there is a memory leak that is slightly larger than the data size.
This is part of the task code.
```c
while (1) {
  struct sockaddr_in6 source_addr;
  socklen_t socklen = sizeof(source_addr);
  int len = recvfrom(sock, udpsBuffer, sizeof(udpsBuffer) - 1, 0, (struct sockaddr *)&source_addr, &socklen);
  if (len < 0) {  /* Ошибка при получении */
    sendUART("UDPs", "Error Receiving", NULL);
    break;
  }
  if (len > 0) {
    inet_ntoa_r(((struct sockaddr_in *)&source_addr)->sin_addr.s_addr, addr_str, sizeof(addr_str) - 1);
    udpsBuffer[len] = 0;
    if (strcmp(udpsBuffer, searchPhrase) == 0) {
      cJSON * root = cJSON_CreateObject();
      cJSON_AddStringToObject(root, "DevID", configDev.DevID);
      const char * jsonString = cJSON_PrintUnformatted(root); // Memory leak!!!
      len = strlen(jsonString);
      int err = sendto(sock, jsonString, len, 0, (struct sockaddr *)&source_addr, sizeof(source_addr));
      cJSON_Delete(root);
      if (err < 0) {
        sendUART("UDPs", "Error occurred during sending", NULL);
        break;
      }
    }
  }
}
```
In this loop, I get the data and compare against the phrase searchPhrase.
Next, I form a JSON packet and send it back.
If delete the line with `const char * jsonString = cJSON_PrintUnformatted(root);` and just return the received packet (echo), then there is no leak.
I rechecked everything line by line - this is the place that creates the memory leak.
How can you solve this?

**Comment by negativekelvin** [comment]
https://stackoverflow.com/questions/27394364/should-the-return-value-of-cjson-print-be-freed-by-the-caller

**Comment by Oleg-Perevyshin** [comment]
Yes it helped!
