### ISSUE TITLE
When is the ESP-MESH feature available?

### ISSUE THREAD

**Issue by binsys** [espressif/esp-idf#633]
ESP8266 has this feature。
I think ESP32 should not remove this feature.
Here is offical overview:
http://www.espressif.com/en/products/software/esp-mesh/overview

**Comment by FayeY** [comment]
We are working on ESP32 mesh now. It will be added in the future release. 
Thanks for your interest in ESP32!

**Comment by binsys** [comment]
Thank you for your reply.

**Comment by lixianyu** [comment]
Any news on this ? :)

**Comment by Karusa** [comment]
How will this up updated on already sold chips?

**Comment by Eric24** [comment]
I'd be interested to know if, when released for the ESP32, ESP-MESH will be compatible with the "official" [BLE mesh standard](https://www.bluetooth.com/what-is-bluetooth-technology/how-it-works/le-mesh).

**Comment by binsys** [comment]
@Eric24  ESP-MESH looks based on WIFI.

**Comment by jo-nas** [comment]
Is there any news on this topic?

**Comment by micheljung** [comment]
For bluetooth mesh, see #819

**Comment by micheljung** [comment]
@FayeY is there an issue that tracks the status of ESP-MESH? I'm not sure what "the future release" exactly means :)

**Comment by No-0n3** [comment]
Any news of when it is going to be implemented?

**Comment by lordgort** [comment]
Any News?

**Comment by FayeY** [comment]
Hi, thanks for your interest in the ESP32 and mesh, the ESP-MESH will be released with the IDF V3.1. Thanks.

**Comment by yorickr** [comment]
When will V3.1 be released?
