### ISSUE TITLE
xtensa-esp32-elf-gdb dependency on libpython2.7 (IDFGH-4510)

### ISSUE THREAD

**Issue by KaeLL** [espressif/esp-idf#6334]
Title.
I'm building my code against IDF v4.1, and when I try to run espcoredump on it, it doesn't f work.
Running b015061 espcoredump on it yields this:
```
$ espcoredump.py info_corefile -t b64 -c coredump1 build/app_test.elf 
espcoredump.py v0.4-dev
Traceback (most recent call last):
  File "/esp-idf/components/espcoredump/espcoredump.py", line 1572, in <module>
    main()
  File "/esp-idf/components/espcoredump/espcoredump.py", line 1568, in main
    operation_func(args)
  File "/esp-idf/components/espcoredump/espcoredump.py", line 1376, in info_corefile
    p = gdbmi_start(args.gdb, [rom_sym_cmd], core_filename, args.prog)
  File "/esp-idf/components/espcoredump/espcoredump.py", line 1274, in gdbmi_start
    gdbmi_run_cmd_get_responses(res, "-data-list-register-values x pc", None, "console", multiple=True,
  File "/esp-idf/components/espcoredump/espcoredump.py", line 1243, in gdbmi_run_cmd_get_responses
    more_responses = p.get_gdb_response(timeout_sec=0, raise_error_on_timeout=False)
  File "/tools/python_env/idf4.3_py3.8_env/lib/python3.8/site-packages/pygdbmi/gdbcontroller.py", line 269, in get_gdb_response
    self.verify_valid_gdb_subprocess()
  File "/tools/python_env/idf4.3_py3.8_env/lib/python3.8/site-packages/pygdbmi/gdbcontroller.py", line 175, in verify_valid_gdb_subprocess
    raise NoGdbProcessError(
pygdbmi.gdbcontroller.NoGdbProcessError: gdb process has already finished with return code: 127
```
And both v4.1 and v4.2 yield this:
```
$ espcoredump.py info_corefile -t b64 -c coredump1 build/app_test.elf 
espcoredump.py v0.4-dev
===============================================================
==================== ESP32 CORE DUMP START ====================
Traceback (most recent call last):
  File "/esp-idf/components/espcoredump/espcoredump.py", line 1810, in <module>
    main()
  File "/esp-idf/components/espcoredump/espcoredump.py", line 1805, in main
    operation_func(args)
  File "/esp-idf/components/espcoredump/espcoredump.py", line 1633, in info_corefile
    p,task_name = gdbmi_freertos_get_task_name(p, extra_info[0])
  File "/esp-idf/components/espcoredump/espcoredump.py", line 1532, in gdbmi_freertos_get_task_name
    p,res = gdbmi_data_evaluate_expression(p, "(char*)((TCB_t *)0x%x)->pcTaskName" % tcb_addr)
  File "/esp-idf/components/espcoredump/espcoredump.py", line 1528, in gdbmi_data_evaluate_expression
    p = gdbmi_cmd_exec(p, handlers, "-data-evaluate-expression \"%s\"" % expr)
  File "/esp-idf/components/espcoredump/espcoredump.py", line 1482, in gdbmi_cmd_exec
    p.stdin.write(bytearray("%s\n" % gdbmi_cmd, encoding='utf-8'))
BrokenPipeError: [Errno 32] Broken pipe
```
There's nothing wrong with the coredump file, I even hexdump'ed it to make sure.

**Comment by igrr** [comment]
@KaeLL could you please mention, which OS are you using? Can you run `xtensa-esp32-elf-gdb build/app_test.elf` — does gdb also exit with an error?

In both cases you have posted, it seems that GDB process is returning with an error immediately.

**Comment by KaeLL** [comment]
@igrr 
> which OS are you using?

Kubuntu 20.04

> Can you run `xtensa-esp32-elf-gdb build/app_test.elf` — does gdb also exit with an error?
```
$ xtensa-esp32-elf-gdb build/app_test.elf 
xtensa-esp32-elf-gdb: error while loading shared libraries: libpython2.7.so.1.0: cannot open shared object file: No such file or directory
```

**Comment by igrr** [comment]
Perhaps it is the same issue as was reported in https://github.com/espressif/esp-idf/issues/5284? Could you try installing libpython2.7?

**Comment by dobairoland** [comment]
@KaeLL `xtensa-esp32-elf-gdb --version` doesn't throw the same error? (I'm think about how to check this)

**Comment by KaeLL** [comment]
@dobairoland it does.

**Comment by igrr** [comment]
Reopening as the linked docker related issue #5284 is now closed, and we don't a fix for local installations on Linux yet.

**Comment by igrr** [comment]
To make this issue easier to find: linux builds of riscv32-esp-elf-gdb are affected by the same problem.

**Comment by mrklkrl** [comment]
yall got any more of them bugfixes?

**Comment by AxelLin** [comment]
I hit this issue on Ubuntu 21.10, running application on esp32c3 with v5.0-dev-1689-g66593bf140.

b'riscv32-esp-elf-gdb: error while loading shared libraries: libpython2.7.so.1.0: cannot open shared object file: No such file or directory\n'

**Comment by Lapshin** [comment]
Hi folks,

@mrklkrl, @AxelLin, @KaeLL good news: we have GDB with python support in pre-release state

You could get it from here https://github.com/espressif/binutils-gdb/releases/tag/esp-gdb-v11.1_20220318

P.s: It would be nice to hear your feedback on the new GDB release here :)

**Comment by KaeLL** [comment]
@Lapshin will this be backported to any of the release/v4.X branches? It's a fix after all, isn't it?

**Comment by Lapshin** [comment]
@KaeLL , sorry for the long delay. The backport for release/v4.4 will be available soon after the internal testing

**Comment by StarGate01** [comment]
@Lapshin Hey, any news of the backporting of the Python3 compatible GDP to 4.x ?

**Comment by Lapshin** [comment]
Hi @StarGate01 ,

esp-idf version 4.4.4 has [esp-gdb-v11.2_20220823](https://github.com/espressif/binutils-gdb/releases/tag/esp-gdb-v11.2_20220823)
