### ISSUE TITLE
How to read registers from STPM34 on SPI with ESP32S2? (IDFGH-4511)

### ISSUE THREAD

**Issue by DipaliDh** [espressif/esp-idf#6335]
Hi,
            I am trying to read the register values from STPM34 ic using SPI with ESP32S2. I have initialized it by referring to the example code in espidf, spi master code. Initialization is done but I am not able to read the STPM34 registers. 
            Can you tell me, how to read it by using the transmit function? I want to do it using esp32s2 library functions and not in Arduino. 

Thanks,
Dipali

**Comment by suda-morris** [comment]
Please share your SPI initialization code and the SPI timing sequence required by the STPM34 device.
