### ISSUE TITLE
No support for chain topology in manual mesh networking examples (IDFGH-4524)

### ISSUE THREAD

**Issue by MisterScience5** [espressif/esp-idf#6348]
## Environment

- Development Kit:      none
- Kit version (for WroverKit/PicoKit/DevKitC): none
- Module or chip used: ESP32-WROOM-32U
- IDF version (run ``git describe --tags`` to find it): release/4.2
- Build System:        CMake
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it): xtensa-esp32-elf-gcc.exe (crosstool-NG esp-2020r3) 8.4.0
- Operating System:     Windows
- (Windows only) environment type: PowerShell.
- Using an IDE?: Yes - VS Code with ESP-IDF extension
- Power Supply:         Battery

## Problem Description

When employing chain topology, the networking IE is 62 bytes rather than 58 which does not match the packed struct mesh_assoc_t, causing the code example to be unable to extract assoc_cap, layer2_cap and possibly others causing a scan fail for chain topology AP's.

The example also does not identify chain topology networks as it employs esp_mesh_scan_get_ap_ie_len() to identify mesh AP's, and chain mesh AP's have a longer IE.

Chain topology does work with set_self_organized(true, x);

### Expected Behavior

Manual networking example should be able to identify and connect to chain AP's.

### Steps to reproduce

1. Use code from manual networking to setup ESP-MESH, 
2. Change topology with esp_mesh_set_topology(MESH_TOPO_CHAIN);

### Code to reproduce this issue

void app_main()
{
esp_mesh_set_topology(MESH_TOPO_CHAIN);

mesh_assoc_t assoc;
esp_mesh_scan_get_ap_ie_len(&ie_len);
if (ie_len == sizeof(assoc)) { etc...
}

**Comment by Alvin1Zhang** [comment]
Thanks for reporting.

**Comment by MisterScience5** [comment]
Would it be possible to post what are the changes for tree topology mesh_assoc_t? With those details I should be able to make a workaround quite quickly:)

**Comment by Alvin1Zhang** [comment]
@MisterScience5 Thanks for reporting, fix on release/4.2 is available https://github.com/espressif/esp-idf/commit/fd032425f144d3bda4cc9da35a5a869b8e6c6c32, feel free to reopen.
