### ISSUE TITLE
Add debug log in the do_global_ctors function (to help to debugcustom constructors) (IDFGH-4527)

### ISSUE THREAD

**Issue by niicoooo** [espressif/esp-idf#6351]
Hi,

Could you, please, add some debug log in the do_global_ctors  startup function to help debugging custom constructors during startup.

Like that:
```diff
*** esp-idf/components/esp32/cpu_start.c
--- esp-idf/components/esp32/cpu_start.c.new
***************
*** 531,543 ****
--- 531,545 ----
  static void do_global_ctors(void)
  {
  #ifdef CONFIG_COMPILER_CXX_EXCEPTIONS
      static struct object ob;
      __register_frame_info( __eh_frame, &ob );
  #endif

      void (**p)(void);
      for (p = &__init_array_end - 1; p >= &__init_array_start; --p) {
+         ESP_EARLY_LOGI(TAG, "Start constructor: %p", *p);
          (*p)();
      }
+     ESP_EARLY_LOGI(TAG, "Start constructor done");
  }
```

Thank you!

Nicolas

**Comment by projectgus** [comment]
Hi @niicoooo,

Thanks for sending us this request. We probably would not add such logging at "Info" level, because it would add quite a lot of output to the normal boot process. However I think we could probably add it at the "Debug" level.

Angus
