### ISSUE TITLE
Some System Logs doesn't accept "system time" and turn off (IDFGH-4529)

### ISSUE THREAD

**Issue by drony** [espressif/esp-idf#6353]
![log](https://user-images.githubusercontent.com/101887/103480530-f2208880-4de5-11eb-91ae-ef91741e5f33.JPG)

**Comment by Alvin1Zhang** [comment]
Thanks for reporting. Would you please help provide more details as suggested in the [issue template](https://github.com/espressif/esp-idf/issues/new?assignees=&labels=&template=bug_report.md&title=)? Information like elf, sdk configuration, backtrace, log outputs, commit ID, hardware and etc. would help us debug further. Thanks.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to short of details, please help provide more information as the [issue template](https://github.com/espressif/esp-idf/issues/new?assignees=&labels=&template=bug_report.md&title=), thanks.
