### ISSUE TITLE
ESP32-S2 Octal SPI / LCD driver support (IDFGH-4553)

### ISSUE THREAD

**Issue by OtherCrashOverride** [espressif/esp-idf#6371]
The ESP32-S2 Technical Reference Manual states that "8-bit Octal SPI mode" and "Moto6800/I8080/Parallel RGB interface 8-bit LCD driver" are hardware supported (22.2.1.1 page 545).  The esp-idf does not appear to expose either functionality.  Is there sample code for enabling these features?  Is official support planned?

**Comment by pootinanny** [comment]
Would be great to see this more widely accessible.
