### ISSUE TITLE
Wifi connection got worse after switching from v4.0.1 to v4.0.2 (IDFGH-4557)

### ISSUE THREAD

**Issue by scyomantion** [espressif/esp-idf#6375]
## Environment

- Development Kit:      none
- Module or chip used:  ESP32-WROOM-32
- IDF version (run ``git describe --tags`` to find it):
    v4.0.1 and v4.0.2
- Build System:         idf.py
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it):
    xtensa-esp32-elf-gcc (crosstool-NG esp-2019r2) 8.2.0 (v4.0.1)
    xtensa-esp32-elf-gcc (crosstool-NG esp-2020r3) 8.4.0 (v4.0.2)
- Operating System:     macOS
- Using an IDE?: No (Sublime 3)
- Power Supply:         USB (iPhone charger)

## Problem Description

I have a custom board with ESP32-WROOM-32 module that is powered by LiPo or USB. For this test I powered it with USB. 
The code currently do following:

- reads the Si7021 temperature sensor
- connects to wifi
- connect MQTT over TCP
- sent the temperature, humidity and last online time
- disconnects MQTT and Wifi
- get online time with esp_timer_get_time() and save it in last online time
- go to deep sleep for 30 seconds. 

I build the project with idf.py. Following configuration values are changed from standard values:
```
CONFIG_PARTITION_TABLE_TWO_OTA=y
CONFIG_ESPTOOLPY_FLASHSIZE_4MB=y
CONFIG_ESPTOOLPY_FLASHSIZE="4MB"
CONFIG_COMPILER_OPTIMIZATION_LEVEL_RELEASE=y
CONFIG_OPTIMIZATION_LEVEL_RELEASE=y
CONFIG_ESP32_DEBUG_OCDAWARE=n
CONFIG_ESP32_DEBUG_STUBS_ENABLE=n
CONFIG_LWIP_DHCP_RESTORE_LAST_IP=y
CONFIG_LWIP_DHCP_DOES_ARP_CHECK=n
```
Furthermore the console logging is disabled completely to save time.

With version v4.0.1 I get very constant online times of around 400ms. After upgrading to v4.0.2 this time goes up to a few seconds every few connections. I visualized it in a graph comparing the two versions:

<img width="1612" alt="Bildschirmfoto 2021-01-09 um 11 53 30" src="https://user-images.githubusercontent.com/4846237/104090021-eadcfd00-5273-11eb-9549-eaed4362c256.png">

There are also very few spikes with V4.0.1 but not as much as with v4.0.2. 

Accesspoint is Unifi AP-AC-LR but the ESP32 is in the same room. Encryption is WPA2. 

### Expected Behavior

Wifi stability should be the same as with v4.0.1

### Actual Behavior

Longer wifi times

**Comment by scyomantion** [comment]
I created a minimal example to reproduce it. You can find it at https://github.com/scyomantion/sensor-test

Simply checkout idf version v4.0.1 or v4.0.2, change wifi settings, mqtt address and build the example. 

There are 7 timers in this example
```
1: after initialize nvs
2: after wifi connect
3: after mqtt connect
4: after subscribed
5: after published message
6: after mqtt block
7: after disconnect mqtt + wifi
```

this is the result I get with v4.0.1
<img width="1600" alt="Bildschirmfoto 2021-01-09 um 17 37 51" src="https://user-images.githubusercontent.com/4846237/104103332-cef05000-52a1-11eb-8a13-66dedaca72d2.png">

this is the result with v4.0.2
<img width="1600" alt="Bildschirmfoto 2021-01-09 um 17 38 16" src="https://user-images.githubusercontent.com/4846237/104103341-d9124e80-52a1-11eb-8959-068bb4bae720.png">

or side by side:
<img width="1600" alt="Bildschirmfoto 2021-01-09 um 17 38 32" src="https://user-images.githubusercontent.com/4846237/104103364-f6471d00-52a1-11eb-96fc-8a4e55f50d4a.png">

**Comment by Alvin1Zhang** [comment]
Thanks for reporting and sorry for the inconvenience, we will look into.

**Comment by scyomantion** [comment]
I also tried master branch yesterday and it seems to be the same.

**Comment by YouDONG-ESP** [comment]
Hi @scyomantion, we have found the cause, it's the problem from the router's AMPDU strategy, the packet may be blocked in the wifi layer when the quantity is few which matches your scenario. I suggest you turn off AMPDU (menuconfig->component config-> wi-fi -> wifi AMPDU TX/RX) and this problem should be solved.

**Comment by scyomantion** [comment]
Hi @YouDONG-ESP , I tested to disable the AMPDU setting and it seems that the problem is solved. Thank you very much!
