### ISSUE TITLE
Trouble building the project because of error: Program "make" not found in PATH (IDFGH-4561)

### ISSUE THREAD

**Issue by ehand622** [espressif/esp-idf#6378]
Error:
make all 
Cannot run program "make": Launching failed

Error: Program "make" not found in PATH
PATH=[C:\Users\damon\.espressif\tools\xtensa-esp32-elf\esp-2020r3-8.4.0\xtensa-esp32-elf\bin;

How can I solve this issue?

**Comment by Alvin1Zhang** [comment]
@ehand622 Thanks for reporting. Would you please help provide more details as suggested in the [issue template](https://github.com/espressif/esp-idf/issues/new?assignees=&labels=&template=bug_report.md&title=)? Information like elf, sdk configuration, backtrace, log outputs, commit ID, hardware and etc. would help us debug further. Thanks.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to not enough details provided, feel free to reopen with more details. Thanks.
