### ISSUE TITLE
Need ESP32-S2 USB SCSI host support (IDFGH-4584)

### ISSUE THREAD

**Issue by wojciech-angelo** [espressif/esp-idf#6401]
Hello
I am using ESP32-S2 chip and I need to program USB OTG interface. Unfortunatelu as long as I'm concerned I don't see a libraries for USB OTG, only USB Device. I need to program ESP as a SCSI HOST to handle communication with some SCSI disks. 
Please help, this is really frustuating, and I need this functionality in my job. 
(This would be a big mass production...)
Thank you in advance

Wojciech -AngeloM-

**Comment by Dazza0** [comment]
@wojciech-angelo We currently don't have support for the full MSC SCSI class (or any other USB Host class), however the Host Controller Driver's bulk unit test contains a minimal implementation of an MSC-SCSI class. The test can basically enumerate a connected USB flash driver then read a couple of blocks from it. See the [HCD Bulk unit test](https://github.com/espressif/esp-idf/blob/7f421048936c6007186db00ed382cd989c4b905e/components/usb/test/hcd/test_hcd_bulk.c) for more details.
