### ISSUE TITLE
ESP32 - actually this example uses ADC1_CH0 which is GPIO36, not GPIO34 as documented (IDFGH-4621)

### ISSUE THREAD

**Issue by shachar-limor** [espressif/esp-idf#6435]
Appears in:
adc1_example_main.c line 34
README.md line 17

**Comment by negativekelvin** [comment]
You would have to specify the branch and commit you are on

https://github.com/espressif/esp-idf/blob/526f682397a8cfb74698c601fd2c5b30e1433837/examples/peripherals/adc/main/adc1_example_main.c#L22

**Comment by shachar-limor** [comment]
Hmm, I was using ESP-IDF v4.3-dev-2136-gb0150615d-dirty
Now I'm wondering if I had not changed it locally to ADC_CHANNEL_6 in the past :-(
Closing this, seems like my bad.

**Comment by shachar-limor** [comment]
Closing this, seems like my bad.
