### ISSUE TITLE
SDK BROKEN - any version that update from master ior subtree (IDFGH-4637)

### ISSUE THREAD

**Issue by filzek** [espressif/esp-idf#6451]
error while trying to build

 from D:/esp-idf/components/lwip/lwip/src/core/tcp_in.c:44:
D:/esp-idf/components/lwip/lwip/src/core/tcp_in.c: In function 'tcp_receive':
D:/esp-idf/components/lwip/lwip/src/core/tcp_in.c:1580:25: error: 'TCP_OOSEQ_DEBUG' undeclared (first use in this function); did you mean 'TCP_QLEN_DEBUG'?
             LWIP_DEBUGF(TCP_OOSEQ_DEBUG,
                         ^~~~~~~~~~~~~~~

seens that the header is not include in tcp_in for somehow.

need to clarify how to solve.

**Comment by Alvin1Zhang** [comment]
@filzek Thanks for reporting. Would you please help provide more details as suggested in the [issue template](https://github.com/espressif/esp-idf/issues/new?assignees=&labels=&template=bug_report.md&title=)? Information like elf, sdk configuration, backtrace, log outputs, commit ID, hardware and etc. would help us debug further. Thanks.

**Comment by Martin-Guenther** [comment]
@filzek Did you run `git submodule update --init --recursive` after checking out?
I got the same error after forgetting to checkout recursively.

**Comment by Alvin1Zhang** [comment]
@filzek Thanks for reporting. Would you please help provide more details as suggested in the [issue template](https://github.com/espressif/esp-idf/issues/new?assignees=&labels=&template=bug_report.md&title=)? Information like elf, sdk configuration, backtrace, log outputs, commit ID, hardware and etc. would help us debug further. Thanks.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to short of feedback, feel free to reopen with more updates, thanks.
