### ISSUE TITLE
Typo (IDFGH-4657)

### ISSUE THREAD

**Issue by kluverp** [espressif/esp-idf#6469]
https://github.com/espressif/esp-idf/blob/526f682397a8cfb74698c601fd2c5b30e1433837/components/esp_eth/src/esp_eth_phy_lan8720.c#L112

https://github.com/espressif/esp-idf/blob/526f682397a8cfb74698c601fd2c5b30e1433837/components/esp_eth/src/esp_eth_phy_lan8720.c#L132

I believe this should be "parallel_detect_fault". Minor nitpick, but I noticed it...

**Comment by suda-morris** [comment]
yes, it's a typo, which should not involve a breaking change, will fix it ASAP.
