### ISSUE TITLE
SPI Without CS

### ISSUE THREAD

**Issue by hopkinskong** [espressif/esp-idf#647]

**Comment by Spritetm** [comment]
Yes. As it says in the documentation, passing -1 will disable CS. Note that the check in SPI_CHECK has to be TRUE, otherwise the check fails, so a cs value of -1 will pass the check.

**Comment by hopkinskong** [comment]
@Spritetm Yes, silly me, I just discovered it...lol

**Comment by Spritetm** [comment]
Can you next time not delete/mangle the issue, though? If you just close it, people who run into a similar issue can find your question using a search engine. If you kill the issue like you did here, you're making that impossible. Better to just answer what you found and close it yourself.

**Comment by hopkinskong** [comment]
@Spritetm  Sure, I reverted the question.

**Comment by Spritetm** [comment]
Thanks!

**Comment by Flotschipopotschi** [comment]
> @Spritetm Yes, silly me, I just discovered it...lol
Seems like you are not the only silly person out there... 


> Can you next time not delete/mangle the issue, though? If you just close it, people who run into a similar issue can find your question using a search engine. If you kill the issue like you did here, you're making that impossible. Better to just answer what you found and close it yourself.
Thank you for the comment, this saved me!

**Comment by lanistor** [comment]
@Spritetm  Well, Why `SPI-without-CS` not supported on `release v4.4` anymore?

> Yes. As it says in the documentation, passing -1 will disable CS. Note that the check in SPI_CHECK has to be TRUE, otherwise the check fails, so a cs value of -1 will pass the check.
