### ISSUE TITLE
Task watchdog got triggered

### ISSUE THREAD

**Issue by 3arth** [espressif/esp-idf#648]
CPU 0: loopTask
Task watchdog got triggered. The following tasks did not feed the watchdog in time:
Tasks currently running:

Keeps on coming WTD.

**Comment by Spritetm** [comment]
What is loopTask doing?

**Comment by 3arth** [comment]
Thanks

**Comment by mkonnov** [comment]
Awesome conversation

**Comment by Spritetm** [comment]
...Yeah.
