### ISSUE TITLE
Uart (example project) not work with 9600 baudrate (IDFGH-4673)

### ISSUE THREAD

**Issue by moggiozzi** [espressif/esp-idf#6485]
## Environment

- Development Kit:     ESP32-DevKit
- Kit version (for WroverKit/PicoKit/DevKitC): v1
- Module or chip used:  ESP32-WROOM-32
- IDF version (run ``git describe --tags`` to find it): v4.2-dev-1303-gcd4fa46f5
- Build System:         idf.py
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it): xtensa-esp32-elf-gcc (crosstool-NG esp-2020r1) 8.2.0
- Operating System:     Windows
- (Windows only) environment type: ESP Command Prompt
- Using an IDE?: No
- Power Supply:         USB

## Problem Description
Project from esp-idf\examples\peripherals\uart\uart_echo_rs485\ not work with 9600 baudrate (with 115200 uart work fine).

### Expected Behavior
Uart communicate with 9600
### Actual Behavior
Uart NOT communicate with 9600
### Steps to reproduce
Run project from https://github.com/moggiozzi/esp_uart_echo_rs485

**Comment by moggiozzi** [comment]
Pins connected witch FTDI232 
![esp32_ftdi](https://user-images.githubusercontent.com/1759476/106423136-e40b6980-6470-11eb-942e-81b359e6bcee.png)

**Comment by moggiozzi** [comment]
My mistake.

**Comment by alisitsyn** [comment]
Hi @moggiozzi,

Does 9600 baud this work now in your design? Just to confirm.

**Comment by moggiozzi** [comment]
> Hi @moggiozzi,
> 
> Does 9600 baud work now in your design? Just to confirm.
Yes. But I found other bug: sometimes RTS pin remains in send mode. My workaround: force call uart_set_rts(uartNumber, 1) by timeout if uart driver stopped generate new events.

**Comment by alisitsyn** [comment]
@moggiozzi ,
Sorry, I missed your answer. The similar issue is [here](https://github.com/espressif/esp-idf/issues/6728) and uart_wait_tx_done() fix is updated but still waiting for merge. Let me know if you still have issues with RS485 mode.
