### ISSUE TITLE
esp32-s2   uvc (IDFGH-4681)

### ISSUE THREAD

**Issue by PureHing** [espressif/esp-idf#6493]
@igrr hello，Is it possible to support uvc driver in esp32-s2？

**Comment by igrr** [comment]
It is possible. We are working on adding parts of the USB host support now. Once that is done and the isochronous transfers are supported, we will finish the port of libuvc.

**Comment by PureHing** [comment]
> It is possible. We are working on adding parts of the USB host support now. Once that is done and the isochronous transfers are supported, we will finish the port of libuvc.

@igrr Greate job! BTW,When can it be opened? Because the project is more urgent, is it possible to provide relevant information or give me some advice？Thanks.

**Comment by igrr** [comment]
I'm sorry I can't give you a timeline for this feature yet. We will update this issue when there is some progress.

**Comment by PureHing** [comment]
ok.Thanks

**Comment by weigede** [comment]
你们都是外国人码?聊个天还用英语???母语不舒服吗?

**Comment by yangminglong** [comment]
> 你们都是外国人码?聊个天还用英语???母语不舒服吗?

这个芯片很多外国人用的
