### ISSUE TITLE
esp_ble_gatts_send_service_change_indication bug on IOS idf 4.2 (IDFGH-4696)

### ISSUE THREAD

**Issue by filzek** [espressif/esp-idf#6508]
Hi

We are trying to send a service change notification within the BLE as 2a05 using esp_ble_gatts_send_service_change_indication but it is not working.

What is the correct way to send a service change notification within the BLE?

Please advise.

**Comment by filzek** [comment]
SERVICE CHANGED appears on BLE SCAN on android, but it doesnt appears on IOs, this is a very serious problem.
If you advertise a new name using esp_ble_gap_set_device_name("XXX") IOs will not show this new name, no matter what.

So, we need to clarify correctly the name change using esp_ble_gap_set_device_name and how to set a flag to IOs BLE scan update the cache on it.

Please advise.

**Comment by xiewenxiang** [comment]
@filzek 

<img width="893" alt="WeChatWorkScreenshot_158452be-7bf0-470a-a9d6-b6d77ee8c977" src="https://user-images.githubusercontent.com/26754847/111913947-09991480-8aab-11eb-9076-69ccb3f8ffa6.png">


Service change notification can be configured to send manually or automatically, From your description, it is recommended that you configure it to send manually.

**Comment by Alvin1Zhang** [comment]
@filzek Thanks for reporting, would you please help share if any updates for the issue? Thanks.

**Comment by filzek** [comment]
Apple doesn't allow the BLE name change for an already scanned Mac address while the iPhone still powered on, so, no matter you clean cache in iPhone it always return the first name found.

We had change way of doing it by using exclusive recursive macaddress change to be able to allow it to be found and match to our purpose!
