### ISSUE TITLE
Menuconfig using idf.py is not working as expected (IDFGH-4713)

### ISSUE THREAD

**Issue by ChromaMaster** [espressif/esp-idf#6520]
## Environment

Development Kit: ESP32-DevKitC
Kit version (for WroverKit/PicoKit/DevKitC): [v1|v2|v3|v4]
Module or chip used: ESP32-WROOM-32
IDF version: v3.3.4
Build System: Make & idf.py
Compiler version: 1.22.0-96-g2852398
Operating System: Linux
Using an IDE?: No
Power Supply: USB

## Problem Description

I'm migrating my project from using Make to using CMake (and thus the `idf.py` command). I've noticed that some menuconfig settings are hidden when using idf.py and they cannot be modified. One of the settings that are not shown are security features (secure boot & flash encryption) which I use in my project.

### Expected Behavior

Be able to see and modify the secure boot & flash encryption.

### Actual Behavior

Security features are hidden. Even though I press z to show them, I cannot modify them...

#### Copy the esp-idf hello world example

```
cp -r ~/.esp/esp-idf/examples/get-started/hello_world/ .
cd hello_world
```

1. Enter the menuconfig using make

![imagen](https://user-images.githubusercontent.com/7367209/107400033-b45c0180-6b01-11eb-94f6-e3f2b22e6442.png)

2. Enter the security features menu and see that settings can be changed

![imagen](https://user-images.githubusercontent.com/7367209/107400080-c5a50e00-6b01-11eb-9dcb-1ded78a3786e.png)

3.  Enter the menuconfig using idf.py. See that the "Security Features" menu is not present. Press Z to show it (it's hidden)

![imagen](https://user-images.githubusercontent.com/7367209/107399797-71019300-6b01-11eb-83ee-f2b3a9b5f573.png)

4.  Enter the security features menu and see that the settings cannot be changed at all

![imagen](https://user-images.githubusercontent.com/7367209/107399853-824a9f80-6b01-11eb-9cfa-981f53f9cc02.png)

**Comment by dobairoland** [comment]
Hi @ChromaMaster. 

I'm sorry but the desired functionality is not available for your version of IDF and CMake.

Please read the important notice on https://docs.espressif.com/projects/esp-idf/en/release-v3.3/get-started-cmake/index.html:

```
The following features are not yet supported with the CMake-based build system:

Eclipse IDE Documentation
Secure Boot
Flash Encryption
Support for these features will be available before CMake becomes the default build system.
```

If you want to use Secure Boot and Flash Encryption with v3.3 then please keep using `make`. 

CMake is the default build system from v4.0. You can upgrade your project if the use of `cmake` is desired.
