### ISSUE TITLE
what is the difference between HIFI3/HIFI4/HIFI5/ Core with ESP32 core? did they same on appliction use? (IDFGH-4734)

### ISSUE THREAD

**Issue by 13824125580** [espressif/esp-idf#6540]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

Please give as many details as you can. Include suggestions for useful APIs or interfaces if relevant.

**Additional context**

**Comment by projectgus** [comment]
Hi @13824125580,

For future reference, please ask questions about ESP32 on the https://esp32.com forum. This issue tracker is for issues in the ESP-IDF software.

The HIFI cores you mention are DSP cores with integrated VLIW computation acceleration of various DSP operations. ESP32 doesn't have this, only 32-bit single cycle multiply/accumulate instruction. Although you can do [DSP calculations](https://github.com/espressif/esp-dsp) with ESP32, the performance will not be the same as using a dedicated DSP core.
