### ISSUE TITLE
Add KSZ8851SNL Ethernet driver (IDFGH-4736)

### ISSUE THREAD

**Issue by b1ackviking** [espressif/esp-idf#6542]
**Is your feature request related to a problem? Please describe.**

I'm adding support for [KSZ8851SNL](https://www.microchip.com/wwwproducts/en/KSZ8851), a single-port Ethernet controller with SPI, in one of our company's projects. ESP-IDF does not support it at the moment, but fortunately, I'm allowed to share the code under an open-source license.

**Describe the solution you'd like**

I'm going to develop and contribute the driver for KSZ8851SNL to the ESP-IDF project.

**Describe alternatives you've considered**

We have discussed with our project manager the pros and cons of open-sourcing the driver versus keeping it in-house and came up with the decision to make it public.

**Additional context**

I'm planning to add the driver into the esp_eth component, similar to the other Ethernet controller drivers.

**Comment by suda-morris** [comment]
Cool, nice to have more Ethernet module support.
