### ISSUE TITLE
Packet loss when using A1 router model (IDFGH-4739)

### ISSUE THREAD

**Issue by ZweiEuro** [espressif/esp-idf#6545]
Hi!
This isn't a 'bug' but rather a solution.
I have an A1 hybrid router (the ones where there is a sim additonally to the cable).

My problem was: 
Using this routers wifi, i could connect (got IP addr), but no packet would go over the wifi/lan line to the device; No matter if tcp client from phone or python script or similar.

Solution:
I got so fed up i called A1 support which told me that the internal firewall of the sim chip might be the issue. After removing the firewall settings from it, everything is working fine for now.
These settings are not editable from the normal admin interface in your local network.

These are the device infos from my router, so if you are experiencing similar issues, you might want to give your ISP a call.

```
Product type:HA35-22
Device ID:00E0FC-8NC6R18518918476
Hardware version:AV1HA35M VER.A
Software version:V100R001C22B030
LTE version:21.316.01.17.272
Current Profile:MU
```

**Comment by YouDONG-ESP** [comment]
Hi @ZweiEuro, thanks for your report and the solution you shared, we will close this one, others users should be able to find it when they are facing the same issue.
