### ISSUE TITLE
mbedtls_net_connect failed (IDFGH-4744)

### ISSUE THREAD

**Issue by GunashekarG** [espressif/esp-idf#6549]
OS: Ubuntu Mate(Linux - 20.04)
MCU: ESP Wroom 32
ESP-IDF version: ESP-IDF v4.3-dev-2586-g526f68239

I am trying to interface ESP WROOM 32 with Cavli C10AM LTE module and trying to upload the data from the ESP WROOM 32 to server using LTE module. After initialising the the LTE module via AT commands, I am using mbedtls library for creating SSL/TLS connection. SSL/TLS set up is successful along with the client key parsing for the certificate. But, when I am trying to connect using  mbedtls_net_connect, I am getting 'failed' response. The error screenshot is attached below.

![Error_mbedtls](https://user-images.githubusercontent.com/31695652/108054802-2047e800-7075-11eb-9e49-787851201006.png)

If anyone has the solution for this please let me know ASAP. Thanks in advance.

**Comment by AdityaHPatwardhan** [comment]
Hi @GunashekarG , sorry for the delayed response, can you please send the debug log of the issue, also please send your sdkconfig file . Thank you

**Comment by Alvin1Zhang** [comment]
@GunashekarG Thanks for reporting, and sorry for replying late,  would you please help send the debug log of the issue, also please send your sdkconfig file? Thanks.

**Comment by Alvin1Zhang** [comment]
@GunashekarG Thanks for reporting, will close due to short of feedback, feel free to reopen with more details. Thanks.
