### ISSUE TITLE
BLE Secure connection issue (IDFGH-4746)

### ISSUE THREAD

**Issue by nileshpassi** [espressif/esp-idf#6550]
hi,
I was using esp32 with esp idf version 3.2 and was able to pair the ios application with it but after migrating to 3.3.3 or the latest version we are having an issue with security as shown in the screenshot attached.

How we can solve the issue? using esp32 FW or using modifying the provisioning application?

![image](https://user-images.githubusercontent.com/42533355/108076977-07016480-7092-11eb-9070-75cce4cf2c55.png)

**Comment by xiewenxiang** [comment]
The screenshot is not clear, could you please provide the attachment of the log.

**Comment by Alvin1Zhang** [comment]
@nileshpassi The screenshot is not clear, could you please provide the attachment of the log? Thanks.

**Comment by nileshpassi** [comment]
Hi, I please find the log attached below,

[log.txt](https://github.com/espressif/esp-idf/files/6008191/log.txt)

there is also a reference case posted by some else, #4045

**Comment by nileshpassi** [comment]
Hi @xiewenxiang and @Alvin1Zhang , I have shared the log in text can please review it.
this is the error which i am getting,
 E (48138) BT_SMP: smp_calculate_link_key_from_long_term_key failed to update link_key. Sec Mode = 2, sm4 = 0x00
 E (48138) BT_SMP: smp_derive_link_key_from_long_term_key failed

**Comment by xiewenxiang** [comment]
@nileshpassi 
If the Flash on the ESP32 has been erased, please clear the binding information in the remote device(phone) and re-pair it.

**Comment by xiewenxiang** [comment]
@nileshpassi 

Does this issue still exist?

**Comment by nileshpassi** [comment]
Yes . I am facing this issue in i-phones have iOS version greater then 12

**Comment by xulongzhuang** [comment]
hi @nileshpassi 
Judging from the error on the log, this may be caused by an error in allocating BR/EDR LK from LTK. You need to check the following configuration:
1. Whether the Bluetooth dual mode is turned on, BR/EDR LK can only be exchanged in mixed mode
2. Whether the Secure Simple Pairing (SSP) option is enabled, this can be turned on in menuconfig ——> Component config——> Bluetooth ——> Bluedroid Enable——> Classic Bluetooth ——> Secure Simple Pairing

Hope the above content can help you solve the problem, and also hope your answer, thank you

**Comment by nileshpassi** [comment]
Thanks for your reply, I will verify this things and get back to you as
soon as possible

**Comment by xulongzhuang** [comment]
hi @nileshpassi 
Have you verified this issue recently? Looking forward to your verification results, thanks

**Comment by nileshpassi** [comment]
Yes, it is working.  Thanks for your help

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, and glad it is working, feel free to reopen.

**Comment by sbujnowski** [comment]
Hello
I have the same problem on the ESP32C3 processor, is this option available there? 
    ( Whether the Secure Simple Pairing (SSP) option is enabled, this can be turned on in menuconfig ——> Component     config——> Bluetooth ——> Bluedroid Enable——> Classic Bluetooth ——> Secure Simple Pairing)

**Comment by xulongzhuang** [comment]
Hi, @sbujnowski 
ESP32C3 only supports BLE and does not support classic Bluetooth, so the SSP option cannot be enabled; can you describe the problem in detail and provide a log of the pairing failure? And can you use [gatt_security_server](https://github.com/espressif/esp-idf/tree/master/examples/bluetooth/bluedroid/ble/gatt_security_server) or [ble50_security_server](https://github.com/espressif/esp-idf/tree/master/examples/bluetooth/bluedroid/ble_50/ble50_security_server) to complete pairing with other Bluetooth devices?
