### ISSUE TITLE
Execution Exception from 4.2 to 4.3 (IDFGH-4747)

### ISSUE THREAD

**Issue by filzek** [espressif/esp-idf#6551]
Using the 15/02/2021 release/v4.3 to build a working complete developed build in v4.2 clash.

All log enable do not show where it blows.

**Comment by nopnop2002** [comment]
Try this.

$ rm sdkconfig
$ idy.py build

**Comment by Alvin1Zhang** [comment]
@filzek Thanks for reporting. Would you please help provide more details as suggested in the [issue template](https://github.com/espressif/esp-idf/issues/new?assignees=&labels=&template=bug_report.md&title=)? Information like elf, sdk configuration, backtrace, log outputs, commit ID, hardware and etc. would help us debug further. Thanks.

**Comment by Alvin1Zhang** [comment]
@filzek Thanks for reporting. Would you please help provide more details as suggested in the [issue template](https://github.com/espressif/esp-idf/issues/new?assignees=&labels=&template=bug_report.md&title=)? Information like elf, sdk configuration, backtrace, log outputs, commit ID, hardware and etc. would help us debug further. Thanks.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to short of details, feel free to reopen with more updates. Thanks.
