### ISSUE TITLE
esp-idf WIFI connection several times (IDFGH-4751)

### ISSUE THREAD

**Issue by JosueSanchezEZM** [espressif/esp-idf#6555]
Hi everybody, I am willing to understand the possibility of connecting and disconnecting the WIFI interface using esp-idf 4.2 wifi sta example. I am trying to generate a program in which the user provides a list of ssids and passwords, so my program could connect and disconnect to each network according to user selection. I am testing this functionality in the example project from esp-idf stack but when I do the second attempt to connect it triggers me this error:
![image](https://user-images.githubusercontent.com/76057615/108123478-e9250700-7073-11eb-9ace-ee865ba928cc.png)
I red the documentation about WIFI component and I implemented a "wifi_close" function to end wifi connection appropriately, based on the 3 steps I understood (esp_wifi_disconnect, esp_wifi_stop, esp_wifi_deinit), I am adding also esp_event_loop_delete_default() and esp_netif_destroy(esp_netif_interface_sta) in order to free de loop default handler and to deattach sta interface. I do this because as you can see in the project code I use again the function wifi_init_sta() to connect one more time to the same network with the same credentials (with the same credentials because I am using sta example to test functionality).  My future test case is to change these wifi configuration credentials for new attempts but what I want first is to be sure about why reconnection in the way I am trying to do is not working, despite having into consideration all I mention here.
Doing debug I found that in the second attempt an error appears here:
![image](https://user-images.githubusercontent.com/76057615/108124416-2c33aa00-7075-11eb-8220-17ec4b0fb7a6.png)

This error happens at the invocation of the xEventGroupWaitBits functions.

I will appreciate all the help and feedback you can provide to me.

Project file for this issue: 
https://drive.google.com/file/d/1gzuN4RW7VJ1mx2fh1W6DAT3EKrXk1lgj/view?usp=sharing

**Comment by nopnop2002** [comment]
It is possible to switch access points sequentially:
AP1->AP2->AP1->AP2

https://github.com/nopnop2002/esp-idf-switch-access-points

**Comment by JosueSanchezEZM** [comment]
Thanks @nopnop2002, this example is actually very similar to what I was looking for. The problem is that in this example you break up  wifi init session part from wifi connection session part. I tried to join these parts into one function "wifi_connect_sta". I just add some code to your example in order to achieve my desired code flow but I am getting an error at the same part that I describe in my first post. 

Here (check the code attached here):
![image](https://user-images.githubusercontent.com/76057615/108236555-0958d280-7115-11eb-8612-c4f2c6e55d4c.png)

Code:
https://drive.google.com/file/d/14CRljbsEafYeirZrjcvbPwxuLI_NNtF-/view?usp=sharing

Please may you provide me some feedback about my code flow? I do not know why when it arrives at xEventGroupWaitBits at the second ATTEMP of wifi connect this error appears.

Thanks so much.

**Comment by nopnop2002** [comment]
I tried the same approach as you did at first, but I didn't get the correct results, so I took a different approach.

**Comment by JosueSanchezEZM** [comment]
Ohh I understand, so what do you think? Is that a bug from esp-idf or a bad implementation of functions ?
 I need this approach because y use several netif interfaces and I need to reuse default netif and default loop handler.

**Comment by nopnop2002** [comment]
Probably the WiFi driver unregister procedure is incorrect, but we need to take a closer look at the behavior of these functions.

```
    ESP_ERROR_CHECK(esp_netif_init()); // ADDED

    ESP_ERROR_CHECK(esp_event_loop_create_default()); // ADDED

    esp_netif_interface_sta = esp_netif_create_default_wifi_sta(); // ADDED

    wifi_init_config_t cfg = WIFI_INIT_CONFIG_DEFAULT(); // ADDDED
    ESP_ERROR_CHECK(esp_wifi_init(&cfg)); // ADDED
```

**Comment by JosueSanchezEZM** [comment]
I will check carefully, but I am open to any suggestions. Thanks @nopnop2002 .

**Comment by nopnop2002** [comment]
Here is the source for example_connect().

https://github.com/espressif/esp-idf/tree/master/examples/common_components/protocol_examples_common


So I tried the following code：
It work fine.


```
#include <string.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "freertos/event_groups.h"
#include "esp_system.h"
#include "esp_wifi.h"
#include "esp_event.h"
#include "esp_log.h"
#include "nvs_flash.h"

#include "protocol_examples_common.h"

void app_main(void)
{
    //Initialize NVS
    esp_err_t ret = nvs_flash_init();
    if (ret == ESP_ERR_NVS_NO_FREE_PAGES || ret == ESP_ERR_NVS_NEW_VERSION_FOUND) {
      ESP_ERROR_CHECK(nvs_flash_erase());
      ret = nvs_flash_init();
    }
    ESP_ERROR_CHECK(ret);

    ESP_ERROR_CHECK( nvs_flash_init() );
    ESP_ERROR_CHECK( esp_netif_init() );
    //tcpip_adapter_init();
    ESP_ERROR_CHECK( esp_event_loop_create_default() );

    ESP_LOGI("MAIN", "example_connect()");
    ESP_ERROR_CHECK( example_connect() );
    vTaskDelay(500);

    ESP_LOGI("MAIN", "example_disconnect()");
    ESP_ERROR_CHECK( example_disconnect() );
    vTaskDelay(500);

    ESP_LOGI("MAIN", "example_connect()");
    ESP_ERROR_CHECK( example_connect() );
    vTaskDelay(500);

    ESP_LOGI("MAIN", "example_disconnect()");
    ESP_ERROR_CHECK( example_disconnect() );
    vTaskDelay(500);
}
```

**Comment by YouDONG-ESP** [comment]
Hi @JosueSanchezEZM, dose @nopnop2002 's suggestion solve your problem? If not, could you copy your code directly here instead of google drive?(It's not allow to access in our base). Or show me a compelet log? Thanks.

**Comment by JosueSanchezEZM** [comment]
Hi @YouDONG-ESP, @nopnop2002 suggestion was a solution that not satisfied my approach. I really need to remove wifi interface correctly. Here I attach my code in which you will find that the error occurs when "wifi_connect_sta" is called for the second time.
/* WiFi station Example

   This example code is in the Public Domain (or CC0 licensed, at your option.)

   Unless required by applicable law or agreed to in writing, this
   software is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
   CONDITIONS OF ANY KIND, either express or implied.
*/
#include <string.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "freertos/event_groups.h"
#include "esp_system.h"
#include "esp_wifi.h"
#include "esp_event.h"
#include "esp_log.h"
#include "nvs_flash.h"

/* FreeRTOS event group to signal when we are connected*/
static EventGroupHandle_t s_wifi_event_group;
void wifi_disconnect_sta(void);

/* The event group allows multiple bits for each event, but we only care about two events:
 * - we are connected to the AP with an IP
 * - we failed to connect after the maximum amount of retries */
#define WIFI_CONNECTED_BIT BIT0
#define WIFI_FAIL_BIT	   BIT1

static const char *TAG = "wifi station";
static esp_netif_t *		esp_netif_interface_sta;

int s_retry_num = 0;

static void event_handler(void* arg, esp_event_base_t event_base,
								int32_t event_id, void* event_data)
{
	if (event_base == WIFI_EVENT && event_id == WIFI_EVENT_STA_START) {
		esp_wifi_connect();
	} else if (event_base == WIFI_EVENT && event_id == WIFI_EVENT_STA_DISCONNECTED) {
		if (s_retry_num < CONFIG_ESP_MAXIMUM_RETRY) {
			esp_wifi_connect();
			s_retry_num++;
			ESP_LOGI(TAG, "retry to connect to the AP");
			//wifi_disconnect_sta();
		} else {
			xEventGroupSetBits(s_wifi_event_group, WIFI_FAIL_BIT);
		}
		ESP_LOGI(TAG,"connect to the AP fail");
	} else if (event_base == IP_EVENT && event_id == IP_EVENT_STA_GOT_IP) {
		ip_event_got_ip_t* event = (ip_event_got_ip_t*) event_data;
		ESP_LOGI(TAG, "got ip:" IPSTR, IP2STR(&event->ip_info.ip));
		s_retry_num = 0;
		xEventGroupSetBits(s_wifi_event_group, WIFI_CONNECTED_BIT);
	}
}

void wifi_init_sta(void)
{
	ESP_ERROR_CHECK(esp_netif_init());

	ESP_ERROR_CHECK(esp_event_loop_create_default());

	esp_netif_create_default_wifi_sta();

	wifi_init_config_t cfg = WIFI_INIT_CONFIG_DEFAULT();
	ESP_ERROR_CHECK(esp_wifi_init(&cfg));
}

esp_err_t wifi_connect_sta(char * ssid, char * password)
{
	// Init Inside connection

	ESP_ERROR_CHECK(esp_netif_init()); // ADDED

	ESP_ERROR_CHECK(esp_event_loop_create_default()); // ADDED

	esp_netif_interface_sta = esp_netif_create_default_wifi_sta(); // ADDED

	wifi_init_config_t cfg = WIFI_INIT_CONFIG_DEFAULT(); // ADDDED
	ESP_ERROR_CHECK(esp_wifi_init(&cfg)); // ADDED


	//conection part, original part of this function

	ESP_LOGI(TAG, "wifi_connect_sta");
	s_wifi_event_group = xEventGroupCreate();
	s_retry_num = 0;

	esp_event_handler_instance_t instance_any_id;
	esp_event_handler_instance_t instance_got_ip;
	ESP_ERROR_CHECK(esp_event_handler_instance_register(WIFI_EVENT,
														ESP_EVENT_ANY_ID,
														&event_handler,
														NULL,
														&instance_any_id));
	ESP_ERROR_CHECK(esp_event_handler_instance_register(IP_EVENT,
														IP_EVENT_STA_GOT_IP,
														&event_handler,
														NULL,
														&instance_got_ip));

#if 0
	wifi_config_t wifi_config = {
		.sta = {
			.ssid =_ESP_WIFI_SSID1,
			.password = ESP_WIFI_PASSWORD1,
			/* Setting a password implies station will connect to all security modes including WEP/WPA.
			 * However these modes are deprecated and not advisable to be used. Incase your Access point
			 * doesn't support WPA2, these mode can be enabled by commenting below line */
		 .threshold.authmode = WIFI_AUTH_WPA2_PSK,

			.pmf_cfg = {
				.capable = true,
				.required = false
			},
		},
	};
#endif

	wifi_config_t wifi_config;
	bzero(&wifi_config, sizeof(wifi_config_t));
	strcpy((char *)wifi_config.sta.ssid, ssid);
	strcpy((char *)wifi_config.sta.password, password);
	wifi_config.sta.threshold.authmode = WIFI_AUTH_WPA2_PSK;
	wifi_config.sta.pmf_cfg.capable = true;
	wifi_config.sta.pmf_cfg.required = false;

	ESP_ERROR_CHECK(esp_wifi_set_mode(WIFI_MODE_STA) );
	ESP_ERROR_CHECK(esp_wifi_set_config(ESP_IF_WIFI_STA, &wifi_config));
	ESP_ERROR_CHECK(esp_wifi_start());
	ESP_LOGI(TAG, "wifi_start");


	/* Waiting until either the connection is established (WIFI_CONNECTED_BIT) or connection failed for the maximum
	 * number of re-tries (WIFI_FAIL_BIT). The bits are set by event_handler() (see above) */
	esp_err_t ret_value = ESP_OK;

	EventBits_t bits = xEventGroupWaitBits(s_wifi_event_group,
			WIFI_CONNECTED_BIT | WIFI_FAIL_BIT,
			pdFALSE,
			pdFALSE,
			portMAX_DELAY);

	/* xEventGroupWaitBits() returns the bits before the call returned, hence we can test which event actually
	 * happened. */
	if (bits & WIFI_CONNECTED_BIT) {
		ESP_LOGI(TAG, "connected to ap SSID:%s password:%s", ssid, password);
	} else if (bits & WIFI_FAIL_BIT) {
		ESP_LOGI(TAG, "Failed to connect to SSID:%s, password:%s", ssid, password);
		ret_value = ESP_FAIL;
		//wifi_disconnect_sta();
	} else {
		ESP_LOGE(TAG, "UNEXPECTED EVENT");
		ret_value = ESP_FAIL;
	}

	/* The event will not be processed after unregister */
	ESP_ERROR_CHECK(esp_event_handler_instance_unregister(IP_EVENT, IP_EVENT_STA_GOT_IP, instance_got_ip));
	ESP_ERROR_CHECK(esp_event_handler_instance_unregister(WIFI_EVENT, ESP_EVENT_ANY_ID, instance_any_id));
	vEventGroupDelete(s_wifi_event_group);
	ESP_LOGI(TAG, "wifi_connect_sta finished.");
	return ret_value;
}

void wifi_disconnect_sta(void)
{
	ESP_LOGI(TAG, "wifi_disconnect_sta");
	s_wifi_event_group = xEventGroupCreate();
	s_retry_num = CONFIG_ESP_MAXIMUM_RETRY;

	// Get configuration of specified interface.
	wifi_config_t wifi_config;
	ESP_ERROR_CHECK(esp_wifi_get_config(ESP_IF_WIFI_STA, &wifi_config) );

	esp_event_handler_instance_t instance_any_id;
	esp_event_handler_instance_t instance_got_ip;
	ESP_ERROR_CHECK(esp_event_handler_instance_register(WIFI_EVENT,
														ESP_EVENT_ANY_ID,
														&event_handler,
														NULL,
														&instance_any_id));
	ESP_ERROR_CHECK(esp_event_handler_instance_register(IP_EVENT,
														IP_EVENT_STA_GOT_IP,
														&event_handler,
														NULL,
														&instance_got_ip));
	ESP_ERROR_CHECK(esp_wifi_disconnect());

	/* Waiting until connection failed for the maximum
	 * number of re-tries (WIFI_FAIL_BIT). The bits are set by event_handler() (see above) */
	EventBits_t bits = xEventGroupWaitBits(s_wifi_event_group,
			WIFI_FAIL_BIT,
			pdFALSE,
			pdFALSE,
			portMAX_DELAY);

	/* xEventGroupWaitBits() returns the bits before the call returned, hence we can test which event actually
	 * happened. */
	if (bits & WIFI_FAIL_BIT) {
		ESP_LOGI(TAG, "disconnected to ap SSID:%s password:%s", (char *)wifi_config.sta.ssid, (char *)wifi_config.sta.password);
	} else {
		ESP_LOGE(TAG, "UNEXPECTED EVENT");
	}

	/* The event will not be processed after unregister */
	ESP_ERROR_CHECK(esp_event_handler_instance_unregister(IP_EVENT, IP_EVENT_STA_GOT_IP, instance_got_ip));
	ESP_ERROR_CHECK(esp_event_handler_instance_unregister(WIFI_EVENT, ESP_EVENT_ANY_ID, instance_any_id));
	vEventGroupDelete(s_wifi_event_group);

	esp_err_t err = esp_wifi_stop();

	if (err == ESP_ERR_WIFI_NOT_INIT) {
		return;
	}
	ESP_ERROR_CHECK(err);

	esp_wifi_deinit(); // ADDED

	ESP_LOGI(TAG, "wifi_disconnect_sta finished.");

	esp_event_loop_delete_default(); // ADDED
//
	esp_netif_destroy(esp_netif_interface_sta); // ADDED


}


void app_main(void)
{
	//Initialize NVS
	esp_err_t ret = nvs_flash_init();
	if (ret == ESP_ERR_NVS_NO_FREE_PAGES || ret == ESP_ERR_NVS_NEW_VERSION_FOUND) {
	  ESP_ERROR_CHECK(nvs_flash_erase());
	  ret = nvs_flash_init();
	}
	ESP_ERROR_CHECK(ret);

	ESP_LOGI(TAG, "ESP_WIFI_MODE_STA");
	//wifi_init_sta();

	for(int i=0;i<5;i++) {
		// Connect AP1
		if (wifi_connect_sta("EASYMETERING-2.4", "ezm12345") == ESP_OK) {
			vTaskDelay(500);
			wifi_disconnect_sta();
			vTaskDelay(500);
		}

		// Connect AP2
//		if (wifi_connect_sta("EASYMETERING-2.4", "ezm12345") == ESP_OK) {
//			vTaskDelay(500);
//			wifi_disconnect_sta();
//			vTaskDelay(500);
//		}
	}
	ESP_LOGI(TAG, "ALL Done.");
}

**Comment by JosueSanchezEZM** [comment]
Public Project: https://drive.google.com/file/d/1gzuN4RW7VJ1mx2fh1W6DAT3EKrXk1lgj/view?usp=sharing

**Comment by YouDONG-ESP** [comment]
@JosueSanchezEZM Please add e`sp_wifi_clear_default_wifi_driver_and_handlers()` in your function `wifi_disconnect_sta()` and this issue should be sloved.

**Comment by YouDONG-ESP** [comment]
@JosueSanchezEZM Please add e`sp_wifi_clear_default_wifi_driver_and_handlers()` in your function `wifi_disconnect_sta()` and this issue should be sloved.

**Comment by JosueSanchezEZM** [comment]
Thanks @YouDONG-ESP, issue solved
