### ISSUE TITLE
problem with adding IDF_PATH in mac OS

### ISSUE THREAD

**Issue by shirish47** [espressif/esp-idf#656]
<img width="573" alt="screen shot 2017-05-31 at 4 58 19 pm" src="https://cloud.githubusercontent.com/assets/6296507/26630525/b1bfc098-4624-11e7-87c2-16f4b8fa89f8.png">
I following steps as shown in esp-idf.readthedocs.io but above picture shows the problem. IDF path is not set if I check with printenv IDF_PATH. also echo $IDF_PATH does not show anything.

**Comment by igrr** [comment]
The guide mentions `~/.profile`, not `~/.bash`, is that right? Also don't forget to reopen the terminal after modifying `~/.profile` (or do `. ~/.profile`, note the leading dot).

**Comment by shirish47** [comment]
<img width="925" alt="screen shot 2017-06-01 at 11 53 12 pm" src="https://cloud.githubusercontent.com/assets/6296507/26694593/93bb4f34-4725-11e7-8bf3-eb7e0f0652ba.png"> if its so than there is problem in document.  I have added the file to .profile. its fine I will do other steps later tomorrow I think this is resolved.  Just need to change documentation.

**Comment by jcwren** [comment]
What would be really nice is to move 'env' to 'env.example' in git, so that every time you don't wipe out the env file, and don't end up trying to commit it when you submit a patch.

**Comment by shirish47** [comment]
now having trouble with this .. make menu config even after adding to .profile ..<img width="586" alt="screen shot 2017-06-02 at 8 44 38 pm" src="https://cloud.githubusercontent.com/assets/6296507/26732206/6a29167e-47d4-11e7-9947-b77aa0bc4aa4.png">

**Comment by shirish47** [comment]
my mistake ... ~/esp not ~esp.. sorry ..
