### ISSUE TITLE
 PPP LCP Echo-request and Echo-reply example (IDFGH-4759)

### ISSUE THREAD

**Issue by JosueSanchezEZM** [espressif/esp-idf#6562]
Hello, I would like your help with a solution that espressif could have in order to be sure PPP session works fine. By works fine I mean to check the status of the PPP connection and terminate it if necessary. I am asking about this functionality because when using a serial monitor to analyze the pppos_cliente example, during PPP connection I could not see any echo request and echo reply to validate the state of the PPP session. How would I know if the connection is still alive?

I will appreciate any comment and help you may provide to me.

Thanks

**Comment by AxelLin** [comment]
https://github.com/espressif/esp-idf/issues/5119

**Comment by JosueSanchezEZM** [comment]
Is this functionality already added in the last update of esp-if? I mean esp-idf 4.2 release or maybe 4.3 ? I reply to  the  #5119 issue about my issue using this workaround. Maybe I am implementing it wrong.
![image](https://user-images.githubusercontent.com/76057615/109426883-d4266d00-79bd-11eb-96bf-5ed781aa5e6a.png)
makefile:
![image](https://user-images.githubusercontent.com/76057615/109426890-da1c4e00-79bd-11eb-81bc-f914e02bf43d.png)
