### ISSUE TITLE
Ethernet: Config by code instead KConfig (IDFGH-4761)

### ISSUE THREAD

**Issue by petrkr** [espressif/esp-idf#6564]
Is possible initialize ethernet from code instead from KConfig how that was in IDF 3.x by some easy way than rewrite https://github.com/espressif/esp-idf/blob/v4.2/components/esp_eth/src/esp_eth_mac_esp32.c#L287 from scratch? Namely we need be able choose PHY, MDIO, MDC and CLOCK TYPE from code. It is not possible to maintain more binaries with hard-coded matrix. It's needed for micropython https://github.com/micropython/micropython/issues/5265#issuecomment-781339741

**Comment by igrr** [comment]
@petrkr The MDIO and MDC can be passed in `eth_mac_config_t` structure to esp_eth_mac_new_esp32:
https://github.com/espressif/esp-idf/blob/0bbc721a633f9afe4f3ebe648b9ca99e2f2f6d5f/examples/ethernet/basic/main/ethernet_example_main.c#L88-L89

PHY can also be chosen by calling one of `esp_eth_phy_new_*` functions:
https://github.com/espressif/esp-idf/blob/0bbc721a633f9afe4f3ebe648b9ca99e2f2f6d5f/examples/ethernet/basic/main/ethernet_example_main.c#L92.

The choice between clock modes is indeed compile-only at the moment. Agree that it makes sense to have it run-time configurable.
