### ISSUE TITLE
WPA3 softAP support (IDFGH-4771)

### ISSUE THREAD

**Issue by lanmarc77** [espressif/esp-idf#6574]
The current [documentation ](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/wifi.html )states:
"Currently, WPA3 is supported only in Station mode."
The use of "Currently," kind of implies there is the plan to extend this to softAP as well.
Is there a timeplan for this feature?
Thank you.

**Comment by sagb2015** [comment]
@lanmarc77  We have almost finished PMF implementation for SoftAP (which is mandatory for WPA3). This will be followed by WPA3 feature of SoftAP. The feature will be available by second quarter of 2021 tentatively.

**Comment by lanmarc77** [comment]
Great to hear. I would suggest to leave this "issue" open for others with the same question until the feature is finished. It would be wonderfull to hear the current state on this from time to time.

**Comment by NateZimmer** [comment]
Some companies require this. Is there any update on this @sagb2015 ? When I read the documentation I didn't see this limitation explicitly called out. I tried 4.3, 4.3.1 & master but am still running into issue where it does not accept WPA3 as a valid auth mode.

**Comment by twlawrenceko** [comment]
Is this being updated?

**Comment by lanmarc77** [comment]
I hope so.

**Comment by sakamoto330** [comment]
I hope so too.
In the latest commit on March 9, 2022, WPA3 returns ESP_ERR_INVALID_ARG.

**Comment by sagb2015** [comment]
Hi All, PMF feature for SoftAP is available now. WPA3-SAE will be available soon.

**Comment by bjpellegrino** [comment]
Any updates on when WPA3 will be working?

**Comment by AxelLin** [comment]
> Hi All, PMF feature for SoftAP is available now. WPA3-SAE will be available soon.

@sagb2015 
Since you mentioned WPA3-SAE will be available **soon** on March, how is the status now

**Comment by rimb05** [comment]
Hi, any update on this?  We need WPA3 support in our AP product.  Thank you.

**Comment by AxelLin** [comment]
@kapilkedawat 
How is the status now? (Seems softAP with WPA3_PSK is supported now? https://github.com/espressif/esp-idf/issues/10939 )

**Comment by shreyassheth1** [comment]
yes @AxelLin WPA3 SoftAP is supported now.

**Comment by lanmarc77** [comment]
I have recompiled my SoftAP applications that were using SDK 4.4 with SDK 5.2 and made the very small adjustments to use WPA3 and it works without any problems for me.
Thank you. Supporting also older models longer will not only save the planet but will also keep your customers coming and staying.
