### ISSUE TITLE
ESP-IDF BLUETHOOTH and WIFI example at the same time (IDFGH-4778)

### ISSUE THREAD

**Issue by JosueSanchezEZM** [espressif/esp-idf#6581]
Hi everybody, 

I would like to know if it is possible to raise WIFI interface up, stay connected, raise Bluetooth BLE interface and use them independently. I mean, while being connected to WIFI any task could be sending data to a server and at the same time Bluetooth BLE interface allowing me to access the data stored in profiles, this through any service I could configure in BLE. 

I would  appreciate all your comment and code examples you can provide to me.

**Comment by chegewara** [comment]
https://github.com/espressif/esp-idf/tree/master/examples/bluetooth/nimble/bleprph_wifi_coex

**Comment by Wth-Esp** [comment]
Hi, @JosueSanchezEZM 

You can manually add `wifi_start` to `ble_gattc` or any other example codes to start wifi and configure SSID and password to access your AP. And you can also use [blufi](https://github.com/espressif/esp-idf/tree/master/examples/bluetooth/bluedroid/ble/blufi) example code to use ble obtain the password for a specific SSID.

Thanks
