### ISSUE TITLE
unable to build esp-idf-template in Eclipse

### ISSUE THREAD

**Issue by Eman-Hussein** [espressif/esp-idf#659]
I am trying to build esp-idf-template in eclipse but getting this error
Description	Resource	Path	Location	Type
make: *** [/home/esp-idf/components/bootloader_support/Makefile.projbuild:7: /home/esp_proj_1/secure_boot_signing_key.pem] Error 1	esp_proj_1	
![capture](https://cloud.githubusercontent.com/assets/4370333/26656861/ded4ed42-462e-11e7-84a6-de31f75988ef.PNG)
	 	C/C++ Problem

**Comment by nkolban** [comment]
Also being worked in the forum here:

https://esp32.com/viewtopic.php?f=13&t=1999

**Comment by jumokeaa** [comment]
I'm having the same problem in Ubuntu

**Comment by nkolban** [comment]
@jumokeaa Maybe have a look at the forum post above and post there with your  value of the question asked in the forum?
