### ISSUE TITLE
Open port

### ISSUE THREAD

**Issue by 3arth** [espressif/esp-idf#660]
Why 67/udp open. How to manage inbound and outbound rule.

![udpopenport](https://cloud.githubusercontent.com/assets/2032190/26660900/aa37a146-4698-11e7-9191-3695ac0a26c2.jpg)

**Comment by Spritetm** [comment]
How does your ESP32 get an IP address? Do you use fixed IP addresses or do you use DHCP?

**Comment by Spritetm** [comment]
How does your ESP32 get an IP address? Do you use fixed IP addresses or do you use DHCP? Or do you run the ESP32 as an access point?

**Comment by 3arth** [comment]
As access point

**Comment by Spritetm** [comment]
Do you manually configure the IP of each of the clients of the AP, or do you just select the APs wireless network and let them automatically join and get an IP?

**Comment by 3arth** [comment]
Great! Thanks
