### ISSUE TITLE
Missing doc - logging functions cannot be used in critical section (IDFGH-4799)

### ISSUE THREAD

**Issue by mdvorak** [espressif/esp-idf#6600]
IDF Version: latest

Log functions `ESP_LOG*` can't be used inside critical sections (as mentions e.g. https://github.com/espressif/esp-idf/issues/4412). This is valid behavior, however I did not find anything in the [docs](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/log.html), or in `esp_log.h` file.

It would be great to have such note in the docs (took me a while to figure it out and find that issue with an explanation). Feel free to point it out for me, if I missed it somehow.

**Comment by projectgus** [comment]
Hey @mdvorak,

Sorry noone got back to you about this already.

You're right that this is not clearly documented. Will add it to the docs ASAP, and update this issue once done.
