### ISSUE TITLE
I2S PCM short/long initialization seems to be backwards (IDFGH-4806)

### ISSUE THREAD

**Issue by akmorrison** [espressif/esp-idf#6605]
In i2s_hal_format_config, `i2s_ll_set_{tx,rx}_pcm_short` is called if the format is `I2S_FORMAT_STAND_PCM_LONG` (and vice versa).

This seems backwards, but I haven't tested it on hardware.

https://github.com/espressif/esp-idf/blob/73db142403c6e5b763a0e1c07312200e9b622673/components/hal/i2s_hal.c#L143-L158

**Comment by denmuellner** [comment]
I just tested it. It is definitely backwards.

**Comment by AxelLin** [comment]
Fixed since 2f1247e1c4dd8bb9401d6b1256d34dd7319fbe5c.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting and thanks to @AxelLin for the notes, feel free to reopen.
