### ISSUE TITLE
Green LED should stay off if already provisioned. (IDFGH-4817)

### ISSUE THREAD

**Issue by franz-ms-muc** [espressif/esp-idf#6616]
Green LED is always on at Boot. 

https://github.com/espressif/esp-idf/blob/master/examples/bluetooth/esp_ble_mesh/ble_mesh_node/onoff_server/main/main.c

but if you set CONFIG_BLE_MESH_SETTINGS it is also on if the Device is already provisioned. 

Expected Behavoiur: 
LED stay off if Device is already provisioned.

**Comment by InfiniteYuan** [comment]
This is a sample application logic, you can modify it to your desired behavior.

**Comment by InfiniteYuan** [comment]
If you don't have another question, please close this issue.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to short of feedback, feel free to reopen.
