### ISSUE TITLE
[TW#13066] BLE Write Characteristic esp_ble_gattc_write_char() not working

### ISSUE THREAD

**Issue by timothycoutlakis** [espressif/esp-idf#663]
When I call this function, I get:

`E (33016) BT: BTA got unregistered event id 31`

What is the correct usage of this function?  How can I write to a characteristic?  When can I write?
Please provide an example.

**Comment by FHFS** [comment]
try gattc_demo.c:174 or :271, there I do see esp_ble_gattc_write_char_descr getting called

It looks like the bta_sys_cb for id 31(BTA_ID_GATTC) is not set.
esp-idf/components/bt/bluedroid/bta/sys/bta_sys_main.c:502
esp-idf/components/bt/bluedroid/bta/include/bta_sys.h:91

Any context on your code and what you are trying to accomplish?

**Comment by timothycoutlakis** [comment]
What does that mean?  How can I set that callback?

I looked at gattc_demo.c - I had previously looked at it before, but that function is for setting the descriptor.

Basically I want to make something that can write a value every so often, eg Temperature.

**Comment by Weijian-Espressif** [comment]
@timothycoutlakis , what do you mean? Do you want write to a characteristic in gattc client ? or in gatts server ?

**Comment by timothycoutlakis** [comment]
@Weijian-Espressif Thank you for your reply.

I have an Android BLE client app which connects to the Gatt server on ESP32.
I would like to write to a characteristic from the ESP32 Gatt server, so that the Android client can receive it.

**Comment by Weijian-Espressif** [comment]
hi @timothycoutlakis  In our gatt_server demo,  you can use  esp_ble_gatts_send_indicate(esp_gatt_if_t gatts_if, uint16_t conn_id, uint16_t attr_handle, uint16_t value_len, uint8_t *value, bool need_confirm).
This function is used to  send indicate or notify to GATT client.

**Comment by timothycoutlakis** [comment]
@Weijian-Espressif Thank you for your reply, I will take a look.

**Comment by FayeY** [comment]
Hi @timothycoutlakis , is this problem solved? Can we close this issue?
