### ISSUE TITLE
DMA leak when uart1 used (IDFGH-4848)

### ISSUE THREAD

**Issue by FrGrQuim** [espressif/esp-idf#6638]
## Environment

- Development Kit:      none
- Module or chip used:  ESP32-WROVER-IE
- IDF version (run ``git describe --tags`` to find it):
    v4.0.1
- Build System:        |idf.py
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it):
    xtensa-esp32-elf-gcc (crosstool-NG esp-2019r2) 8.2.0
- Operating System:     Linux
- Using an IDE?: No
- Power Supply:        external 5V

## Problem Description

I Use the ESP to get data from the UART 1 and then send it to device connected to the wifi AP generated by the ESP (via UDP)
In order to debug I implement a check of the memory state and I observe that the DMA become very low after some hours. This lead (I suppose) to wifi problem like those one:

W (793588) wifi:alloc eb len=216 type=2 fail, heap:3508920                                                                                                                                                                          
W (793588) wifi:m f probe rsp l=191    

When I disable the UART 1 the free DMA stay above 15K and when I enable it the free DMA reach less than 100bytes

Here is my UART 1 config

#define UART1_TXD_PIN               18
#define UART1_RXD_PIN               15
#define RX_BUF_SIZE                 512
#define UART_DEFAULT_BAUDRATE               460800
#define UART_QUEUE_SIZE                     20
#define UART_TASK_PRIO                      16

const uart_config_t uart_config = {
        .baud_rate = UART_DEFAULT_BAUDRATE,
        .data_bits = UART_DATA_8_BITS,
        .parity = UART_PARITY_DISABLE,
        .stop_bits = UART_STOP_BITS_1,
        .flow_ctrl = UART_HW_FLOWCTRL_DISABLE
    };

 uart_param_config(UART_NUM_1, &uart_config);
 uart_set_pin(UART_NUM_1, UART1_TXD_PIN, UART1_RXD_PIN, UART_PIN_NO_CHANGE, UART_PIN_NO_CHANGE);

 uart_driver_install(UART_NUM_1, RX_BUF_SIZE, RX_BUF_SIZE, UART_QUEUE_SIZE, &uart_evt_queue, 0);

### Expected Behavior

The free DMA stay above more or less 5K

### Actual Behavior

The free DMA is close to 0 after some hours

### Steps to reproduce

The project on which I work is more complex than a wifi AP and the management of the UART so I'm not sure that only working with those two will lead to the same problem but here is the step I follow on the uart to reproduce it quickly
1. Init the Wifi AP
2. Init The UART 1 with the previous config
3. Connect a device that send at least 700bytes every seconds in buffer of 256 bytes (all buffers send in once and then 1 second of delay)

**Comment by projectgus** [comment]
Hi @FrGrQuim,

It sounds like your project has a memory leak somewhere. (DMA capable memory is the same as internal memory, but default small allocations will prefer internal memory.)

> here is the step I follow on the uart to reproduce it quickly

Do you have a simple project that reproduces this, or do you only reproduce this in your more complex project? If you have a simple project that displays the issue, is it possible to share the full code to it please?

To find out exactly what is leaking memory in a project, the best thing to do is to use the built-in ESP-IDF heap tracing feature in leak check mode:
https://docs.espressif.com/projects/esp-idf/en/v4.0.1/api-reference/system/heap_debug.html#heap-tracing

**Comment by Alvin1Zhang** [comment]
@FrGrQuim Thanks for reporting, would you please help share if any updates for this issue? Thanks.

**Comment by Alvin1Zhang** [comment]
@FrGrQuim Thanks for reporting, would you please help share if any updates for this issue? Thanks.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to short of feedback, feel free to reopen with more updates. Thanks.
