### ISSUE TITLE
[TW#13064] Unable to use opendir() on the mountpoint with a FATFS file system VFS mounted.

### ISSUE THREAD

**Issue by nkolban** [espressif/esp-idf#664]
If I try and use `opendir("/spiflash")` where I have a FATFS file system mounted at `/spiflash`, we get an error (errno=2).  A work around is to use `opendir("/spiflash/")`  however that is not sufficient for my project.  I am raising this issue for formal tracking.

See also:
https://esp32.com/viewtopic.php?f=13&t=1930&p=9140

**Comment by igrr** [comment]
Fixed in https://github.com/espressif/esp-idf/commit/2ccfe3da96cba837c2cf0a9695d1595d377b5b7d.
