### ISSUE TITLE
UDP 通信问题 (IDFGH-4846)

### ISSUE THREAD

**Issue by luacerbb** [espressif/esp-idf#6647]
当softap+station 共存时，softap默认的网段是 192.168.4.X,手机接入esp32，被分配了一个在该段的ip, esp32作为sta 连接的路由器网段也在 192.168.4.X, 这是向手机ip发送udp数据，手机没有收到。我想了解下这种情况发送UDP数据能否指定是向手机还是路由器吗？

**Comment by Alvin1Zhang** [comment]
@luacerbb Thanks for reporting. Would you please help provide more details as suggested in the [issue template](https://github.com/espressif/esp-idf/issues/new?assignees=&labels=&template=bug_report.md&title=)? Information like elf, sdk configuration, backtrace, log outputs, commit ID, hardware and etc. would help us debug further. Thanks.

**Comment by TimXia** [comment]
这取决于 softap 和 station 网络接口的启动顺序，建议将 softap 的网段设置成不同于路由器的网段。

**Comment by Alvin1Zhang** [comment]
@luacerbb Thanks for reporting, would you please help share if any updates? Thanks.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to short of feedback, feel free to reopen with more updates.
