### ISSUE TITLE
esp_modem: racy bug in sending ESP_MODEM_EVENT_UNKNOWN (IDFGH-4858)

### ISSUE THREAD

**Issue by AxelLin** [espressif/esp-idf#6655]
## Environment

- Module or chip used: ESP32-WROOM-32D
- IDF version: v4.4-dev-4-g73db142403c6
- Build System: idf.py
- Compiler version: xtensa-esp32-elf-gcc (crosstool-NG esp-2020r3) 8.4.0
- Operating System: Linux
- Power Supply: USB

## Problem Description

In esp_dte_handle_line() err_handle, the esp_event_post_to() takes "line" as event_data.
const char *line = (const char *)(esp_dte->buffer);

This is wrong because the task running the event_loop_hdl is different from
the one calling esp_dte_handle_line.

So the content of esp_dte->buffer maybe changed before the code running in another task to take event_data.
The pointer does not change, but the content could be no longer valid (not the expected data).

**Comment by david-cermak** [comment]
@AxelLin This should be okay, since the `esp_event_post_to()` takes a copy of the event data:

https://github.com/espressif/esp-idf/blob/master/components/esp_event/include/esp_event.h#L360-L361

Quick test below:
```c
    char line[32] = "line1";
    esp_event_post_to(esp_dte->event_loop_hdl, ESP_MODEM_EVENT, ESP_MODEM_EVENT_UNKNOWN,
                      (void *)line, strlen(line) + 1, pdMS_TO_TICKS(0));
    strcpy(line, "line2");
    esp_event_post_to(esp_dte->event_loop_hdl, ESP_MODEM_EVENT, ESP_MODEM_EVENT_UNKNOWN,
                      (void *)line, strlen(line) + 1, pdMS_TO_TICKS(0));
```

Shows two separate events with different data:
```
D (1023) event: running post ESP_MODEM_EVENT:4 with handler 0x400da678 and context 0x3ffbd398 on loop 0x3ffbbd7c
W (1023) pppos_example: Unknow line received: line1

D (1123) event: running post ESP_MODEM_EVENT:4 with handler 0x400da678 and context 0x3ffbd398 on loop 0x3ffbbd7c
W (1123) pppos_example: Unknow line received: line2
```
