### ISSUE TITLE
Example for changing IP adresse in bound sockets? (IDFGH-4879)

### ISSUE THREAD

**Issue by ZweiEuro** [espressif/esp-idf#6675]
If i have a socket bound to an ip, can i somehow change the address it is bound to or do i need to close the socket?

Rather it'S a bit unclear to me what i am supposed to do with a socket that is stuck on 'accept' when the ip address or network changes, since it's blocking i can't continue either

**Comment by david-cermak** [comment]
@ZweiEuro Would it help to bind the socket to an interface rather then IP? I'm afraid it's not possible to unbind a socket without having it shutdown and closed.

You can use
```c
setsockopt(sock, SOL_SOCKET, SO_BINDTODEVICE,  if_name, sizeof(struct ifreq));
```
for binding the socket to the interface


>  what i am supposed to do with a socket 

You can use non-blocking API 
```c
flags |= O_NONBLOCK;
fcntl(sock, F_SETFL, flags)
```

**Comment by ZweiEuro** [comment]
Thank you ! I will try this
