### ISSUE TITLE
esp_ble_scan_dupilcate_list_flush incorrectly spelled (IDFGH-4886)

### ISSUE THREAD

**Issue by Emill** [espressif/esp-idf#6681]
The function `esp_ble_scan_dupilcate_list_flush` at https://github.com/espressif/esp-idf/blob/0bbc721a633f9afe4f3ebe648b9ca99e2f2f6d5f/components/bt/controller/esp32/bt.c#L1641 is incorrectly spelled.

It should be called esp_ble_scan_**duplicate**_list_flush.

Not really a bug but rather a code quality issue.

**Comment by Alvin1Zhang** [comment]
@Emill Thanks for pointing out, we will look into.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting and sorry for late reply, the fix is available here, feel free to reopen.
