### ISSUE TITLE
Unable to compile the hello world example. (IDFGH-4896)

### ISSUE THREAD

**Issue by ankit-thealchemist** [espressif/esp-idf#6690]
## Environment

- Development Kit:     none
- Kit version (for WroverKit/PicoKit/DevKitC): [v1|v2|v3|v4]
- Module or chip used:  [ESP32-WROOM-32|ESP32-WROOM-32D|ESP32-WROOM-32U|ESP32-WROVER|ESP32-WROVER-I|ESP32-WROVER-B|ESP32-WROVER-IB|ESP32-SOLO-1|ESP32-PICO-D4|ESP32]
- IDF version (run ``git describe --tags`` to find it):
   master
- Build System:         [Make|CMake|idf.py]
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it):
    // 1.22.0-80-g6c4433a
- Operating System:     [Windows
- (Windows only) environment type: [MSYS2 mingw32|ESP Command Prompt|Plain Command Prompt|PowerShell].
- Using an IDE?: |Yes (please give details)] vs code
- Power Supply:         [USB|external 5V|external 3.3V|Battery]

## Problem Description

I was compiling the hello world example, and I am getting a strange error.  
The error I am getting is 

ESP-IDF Custom Terminal
$ cmake
ninja: error: 'D:/IOTCode/framework/esp-idf/components/esp_wifi/lib/esp32/libwapi.a', needed by 'hello-world.elf', missing and no known rule to make it
The terminal process failed to launch (exit code: 1).

Terminal will be reused by tasks, press any key to close it.

### Steps to reproduce

1. step1
2. ...

// If possible, attach a picture of your setup/wiring here.

### Code to reproduce this issue

```cpp
// the code should be wrapped in the ```cpp tag so that it will be displayed better.
#include "esp_log.h"

void app_main()
{

}

```
// If your code is longer than 30 lines, [GIST](https://gist.github.com) is preferred.

## Debug Logs

```
Debug log goes here, should contain the backtrace, as well as the reset source if it is a crash.
Please copy the plain text here for us to search the error log. Or attach the complete logs but leave the main part here if the log is *too* long.
```

## Other items if possible

- [ ] sdkconfig file (attach the sdkconfig file from your project folder)
- [ ] elf file in the ``build`` folder (**note this may contain all the code details and symbols of your project.**)
- [ ] coredump (This provides stacks of tasks.)

**Comment by chegewara** [comment]
Did you install esp-idf with `git clone --recursive` or `git update submodule --init --recursive`?

**Comment by ankit-thealchemist** [comment]
> Did you install esp-idf with `git clone --recursive` or `git update submodule --init --recursive`?

Actually I have downloaded the esp idf about 1 year ago. I just usually does git pull origin master -submodule --recurse  . I also copied that same on the other desktop(about 6 months ago), and I updated the same wit the same git command and it works fine. 
Do I need to  fresh download? thanks in advance!

**Comment by chegewara** [comment]
@ankit-thealchemist sorry, i missed your response somehow. Yes, it would be good if you could update esp-idf, because with 1 year old toolchain you are missing many updates and bug fixes. Also it looks like you are mixing some examples that are from more recent API with some older esp-idf version.

**Comment by ankit-thealchemist** [comment]
> @ankit-thealchemist sorry, i missed your response somehow. Yes, it would be good if you could update esp-idf, because with 1 year old toolchain you are missing many updates and bug fixes. Also it looks like you are mixing some examples that are from more recent API with some older esp-idf version.

Hey thanks for the advice I redownloaded the esp idf and it resolves my problem. Thanks for your support!
