### ISSUE TITLE
What is I2S sample rate actually? (IDFGH-4897)

### ISSUE THREAD

**Issue by ctz16** [espressif/esp-idf#6691]
### Hardware:
|||
|:---|---|
|<B>Board</B>|ESP32 Wrover E|
|<B>Version/Date</B>|today's master|
|<B>IDE name</B>|Arduino IDE|
|<B>Flash Frequency</B>|80Mhz|
|<B>PSRAM enabled</B>|no|
|<B>Upload Speed</B>|115200|
|<B>Computer OS</B>|Windows 10|

### Description:
Hi guys,

I was trying to use I2S with DMA for high frequency ADC sampling, and I want to calculate the frequency of signal sampled by ADC. So I want to know the ADC sample rate. It seems that there is only one rate I can configure, which is the i2s sample rate.

In my understanding,  ADC will write DMA buffer automatically, and we call ``` i2s_read()``` to read DMA buffer at a given rate, which is i2s sample rate, is that right? However, when I set i2s sample rate to 100kHz, it's actually found that the sample rate is much higher. For example, it only cost 20ms to read 10k samples, which is supposed to cost 100ms.

Check and run my code below:

### Sketch:
```cpp

#include <driver/i2s.h>

#define I2S_SAMPLE_RATE 100000
#define ADC_INPUT ADC1_CHANNEL_0 //pin SENSOR_VP
#define SAMPLE_NUM 10000
#define OUTPUT_PIN 27

uint16_t adc_reading[SAMPLE_NUM];
long adc_start_time = 0;
long adc_end_time = 0;

void i2sInit()
{
   i2s_config_t i2s_config = {
    .mode = (i2s_mode_t)(I2S_MODE_MASTER | I2S_MODE_RX | I2S_MODE_ADC_BUILT_IN),
    .sample_rate =  I2S_SAMPLE_RATE, 
    .bits_per_sample = I2S_BITS_PER_SAMPLE_16BIT,
    .channel_format = I2S_CHANNEL_FMT_ALL_LEFT, //signal at left channel
    .communication_format = I2S_COMM_FORMAT_I2S_MSB,
    .intr_alloc_flags = ESP_INTR_FLAG_LEVEL1,
    .dma_buf_count = 4,
    .dma_buf_len = 1000,
    .use_apll = false,
    .tx_desc_auto_clear = false,
    .fixed_mclk = 0
   };
   adc1_config_channel_atten(ADC1_CHANNEL_0,ADC_ATTEN_DB_11);
   adc1_config_width (ADC_WIDTH_12Bit);
   i2s_driver_install(I2S_NUM_0, &i2s_config, 0, NULL);
   i2s_set_adc_mode(ADC_UNIT_1, ADC_INPUT);
}

int adc_read(uint16_t* adc_value){
  size_t num_bytes_read = 0;
  i2s_read( I2S_NUM_0, (void*) adc_value,  SAMPLE_NUM * sizeof (uint16_t), &num_bytes_read, portMAX_DELAY);
  return num_bytes_read;
}

void setup() {
  Serial.begin(115200);
  // generate a 5000Hz signal at pin 27
  uint32_t freq = ledcSetup(0, 5000, 8); // channel, freq, resolution
  Serial.printf("Output frequency: %d\n", freq);
  ledcWrite(0, 100); //channel, duty
  ledcAttachPin(OUTPUT_PIN, 0);
  i2sInit();
}

void loop() {
  i2s_adc_enable(I2S_NUM_0);
  adc_start_time = millis();
  int num_read = adc_read(adc_reading);
  adc_end_time = millis();
  i2s_adc_disable(I2S_NUM_0);
  Serial.print("total time cost: ");
  Serial.println(adc_end_time-adc_start_time);
  Serial.print("bytes read: ");
  Serial.println(num_read);
  delay(10000);
}
```
Output is below:

```
Output frequency: 5000
total time cost: 20
bytes read: 20000
```
So what is the i2s sample rate? And how to know ADC sample rate?

**Comment by me-no-dev** [comment]
Arduino uses the latest ESP-IDF v3.3 branch

**Comment by christophhebeisen** [comment]
Did this ever get resolved?  I am having the same issue .  Changing i2s_config.sample_rate changes the observed sample rate in a random-seeming fashion.  Here are some examples: 
- sample_rate=4000  --> observed sample rate: ~290000 Hz
- sample_rate=8000  --> observed sample rate: ~200000 Hz
- sample_rate=12000  --> observed sample rate: ~300000 Hz
- sample_rate=16000  --> observed sample rate: ~175000 Hz
- sample_rate=20000  --> observed sample rate: ~170000 Hz
- sample_rate=24000  --> observed sample rate: ~600000 Hz
- sample_rate=28000  --> observed sample rate: ~195000 Hz
I am fairly certain that the ADC isn't even capable of completing the conversion at this rate (though the values returned make sense - maybe they are read repeatedly?). Has anybody been successfully set (and verified) the I2S conversion rate when using the internal ADC?

**Comment by christophhebeisen** [comment]
I believe that I2S_RX_BCK_DIV_NUM is not being set correctly to set the actual rate to `i2s_config.sample_rate`. I was able to work around this by setting it myself:
```int d=8e7/(I2S0.clkm_conf.clkm_div_num+I2S0.clkm_conf.clkm_div_b/I2S0.clkm_conf.clkm_div_a)/i2s_config.sample_rate+0.5;
SET_PERI_REG_BITS(I2S_SAMPLE_RATE_CONF_REG(0), I2S_RX_BCK_DIV_NUM, d, I2S_RX_BCK_DIV_NUM_S);```
At least for a single channel and 16 bit samples I now get the correct sample rate after adding these lines.

**Comment by rainvalley** [comment]
> I believe that I2S_RX_BCK_DIV_NUM is not being set correctly to set the actual rate to `i2s_config.sample_rate`. I was able to work around this by setting it myself:
> 
> ```
> int d=8e7/(I2S0.clkm_conf.clkm_div_num+I2S0.clkm_conf.clkm_div_b/I2S0.clkm_conf.clkm_div_a)/i2s_config.sample_rate+0.5;
> SET_PERI_REG_BITS(I2S_SAMPLE_RATE_CONF_REG(0), I2S_RX_BCK_DIV_NUM, d, I2S_RX_BCK_DIV_NUM_S);
> ```
> 
> At least for a single channel and 16 bit samples I now get the correct sample rate after adding these lines.

Hello, I'm now facing the same issues, but your solutions seem to be useless for me. So can you post your entire codes here? thanks.

My configuration is shown as below:
```
#define len_song 160000
uint16_t *song = NULL;

void i2s_init()
{
  i2s_config_t i2s_config = {
    .mode = (i2s_mode_t)(I2S_MODE_MASTER | I2S_MODE_RX | I2S_MODE_ADC_BUILT_IN),
    .sample_rate =  16000,              // The format of the signal using ADC_BUILT_IN
    .bits_per_sample = I2S_BITS_PER_SAMPLE_16BIT, // is fixed at 12bit, stereo, MSB
    .channel_format = I2S_CHANNEL_FMT_ONLY_RIGHT,
    .communication_format = I2S_COMM_FORMAT_I2S_MSB,
    .intr_alloc_flags = ESP_INTR_FLAG_LEVEL1,
    .dma_buf_count = 4,
    .dma_buf_len = 8,
    .use_apll = false,
    .tx_desc_auto_clear = false,
    .fixed_mclk = 0
  };
  i2s_driver_install(I2S_NUM_0, &i2s_config, 0, NULL);
  i2s_set_adc_mode(ADC_UNIT_1, ADC1_CHANNEL_7);
  i2s_adc_enable(I2S_NUM_0);
  int d=8e7/(I2S0.clkm_conf.clkm_div_num+I2S0.clkm_conf.clkm_div_b/I2S0.clkm_conf.clkm_div_a)/i2s_config.sample_rate+0.5;
  SET_PERI_REG_BITS(I2S_SAMPLE_RATE_CONF_REG(0), I2S_RX_BCK_DIV_NUM, d, I2S_RX_BCK_DIV_NUM_S);
}

size_t byte_read;
size_t start_time = micros();
i2s_read(I2S_NUM_0, (void*)song, len_song * 2, &byte_read, portMAX_DELAY);
Serial.print("I2S has read bytes:"); Serial.println(byte_read);
Serial.print("I2S has passed:"); Serial.println(micros() - start_time);
```
The result is as shown below:
[20:43:28.112] I2S has read bytes:320000
I2S has passed:2835732

**Comment by L-KAYA** [comment]
ADC + DMA now has been split from I2S driver and available in `adc_continuous.h` since IDF v5.0. This issue should be fixed in the new driver, and the legacy driver is no longer recommended. So close this issue for now.
