### ISSUE TITLE
how to set serach path in clion ide (IDFGH-4899)

### ISSUE THREAD

**Issue by m986883511** [espressif/esp-idf#6693]
I use clion open esp-idf hello_world project,I can use idf.py build to build this project.
But there is a problem, I can not ctrl+left click to jump, like hearder。

#include <stdio.h>
#include "sdkconfig.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "esp_system.h"
#include "esp_spi_flash.h"

just like it above.

**Comment by Kiznoh** [comment]
Hi @m986883511,

To use `ctrl`+`left click` to jump to a definition or source header, you need to succesfully configure CMake inside CLion.

![clion64_g1qBrPILB4](https://user-images.githubusercontent.com/11771435/128029773-f07d0bf8-1e21-4d70-abd4-f905b0b55542.png)

These are the settings I used:
The selected C and C++ compilers are located inside the `.espressif/tools` folder.

![clion64_4q91UXIjw3](https://user-images.githubusercontent.com/11771435/128027575-efb7e16b-b660-4491-9d38-57d2e5f1f7a2.png)

The only required CMake settings are the environment variables `IDF_PATH`, `IDF_TARGET`, and `PATH`.

![clion64_ybsYyyAWFm](https://user-images.githubusercontent.com/11771435/128027580-68142e1a-17cb-461a-a465-b86af4c49274.png)

`PATH` is set to IDF's python env + compiler bin folder + git cmd folder.

![clion64_brniJbm6a6](https://user-images.githubusercontent.com/11771435/128027579-02d11d72-776b-4e58-ac84-6c63304b01be.png)

Please note, building IDF projects with MSYS or CLion is not officially supported by ESP-IDF.
