### ISSUE TITLE
Suggest for change the order of the creation of the standard streams in cpu_start

### ISSUE THREAD

**Issue by jolivepetrus** [espressif/esp-idf#67]
I suggest to change the order of the creation of the standard streams in cpu_start:

current order:
    _GLOBAL_REENT->_stdout = fopen(default_uart_dev, "w");
    _GLOBAL_REENT->_stderr = fopen(default_uart_dev, "w");
    _GLOBAL_REENT->_stdin  = fopen(default_uart_dev, "r");

proposed order:
    _GLOBAL_REENT->_stdin  = fopen(default_uart_dev, "r");
    _GLOBAL_REENT->_stdout = fopen(default_uart_dev, "w");
    _GLOBAL_REENT->_stderr = fopen(default_uart_dev, "w");

The thing is that with the current order the correspondence between standard streams and standards file descriptors are incorrect:

_stdout has file descriptor 0
_stderr has file descriptor 1
_stdin has file descriptor 2

and the correct file descriptors are:

_stdin has file descriptor 0
_stdout has file descriptor 1
_stderr has file descriptor 2

In posix-compliance code this will be a problem wen using functions that work with file descriptors, such as write, for example:

write(STDOUT_FILENO, "hello world", 11)

will out to STDERR.

**Comment by igrr** [comment]
Fixed master
