### ISSUE TITLE
Failed to compile example of rotary_encoder (IDFGH-4914)

### ISSUE THREAD

**Issue by zsjlovestudy** [espressif/esp-idf#6706]
Could you tell me the solution to this
[2/9] Building C object esp-idf/rotary_encoder/CMakeFiles/__idf_rotary_encoder.dir/src/rotary_encoder_pcnt_ec11.c.obj
FAILED: esp-idf/rotary_encoder/CMakeFiles/__idf_rotary_encoder.dir/src/rotary_encoder_pcnt_ec11.c.obj 

My current environment is version 4.2 esp-idf
But I couldn't find the example of rotary_encoder .

![image](https://user-images.githubusercontent.com/52393677/111023968-1072b800-8417-11eb-8739-48b533e5f1de.png)
![image](https://user-images.githubusercontent.com/52393677/111023982-254f4b80-8417-11eb-913a-399592ae9b80.png)
![image](https://user-images.githubusercontent.com/52393677/111023993-3304d100-8417-11eb-95bf-7814f7458827.png)

**Comment by suda-morris** [comment]
Hi @zsjlovestudy 
That example and the new API was introduced in v4.3, you can switch to release/v4.3 or master branch.

**Comment by zsjlovestudy** [comment]
Thank you for your help！！

**Comment by zsjlovestudy** [comment]
Could you tell me how to do this.
![image](https://user-images.githubusercontent.com/52393677/111453153-3c12dc80-874e-11eb-9dde-3eb0d761093f.png)
![image](https://user-images.githubusercontent.com/52393677/111453254-55b42400-874e-11eb-9fcc-e5bc87befa93.png)

**Comment by brianignacio5** [comment]
It seems something is wrong in the extension.

Can you try to delete:

- Windows: `%USERPROFILE%\.vscode\extensions\espressif.esp-idf-extension-VERSION`
- Linux & MacOSX: `$HOME/.vscode/extensions/espressif.esp-idf-extension-VERSION`

and install [VSIX installer](https://github.com/espressif/vscode-esp-idf-extension/suites/2259097242/artifacts/47026344)

**Comment by zsjlovestudy** [comment]
I am using the VSIX you just sent, The version of the ESP IDF is up to date

![image](https://user-images.githubusercontent.com/52393677/111462608-96fe0100-8759-11eb-9c04-ccab57db63a0.png)

It's the same mistake

![image](https://user-images.githubusercontent.com/52393677/111462660-a715e080-8759-11eb-9952-6eb3b7740b51.png)
![image](https://user-images.githubusercontent.com/52393677/111462797-d0367100-8759-11eb-98a1-899331cf0ffb.png)

In addition, I did not see the release version of 4.3release in these options. 

I chose to Find ESP-IDF in Your System,   and this directory already has the 4.3release file I just downloaded

**Comment by brianignacio5** [comment]
About the version not being part of the list, v4.3 is still in beta.

I'm not sure why this happens. I've tested on Windows 10 and it is working fine, also the connection error is not there.

Maybe you can close this issue (since conversation changed to a vscode extension issue) and open a [new issue](https://github.com/espressif/vscode-esp-idf-extension/issues/new?assignees=&labels=bug-report&template=bug_report.md&title=%5BBug+Report%5D%3A+) with details about your setup (OS, Visual Studio Code information, nodeJS)

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, feel free to reopen.
