### ISSUE TITLE
I2C lcd 1602 display library (IDFGH-4924)

### ISSUE THREAD

**Issue by mvarchdev** [espressif/esp-idf#6716]
**Is your feature request related to a problem? Please describe.**

Hello I searched all internet and have unsuccessfully found anything like library to controll i2c lcd 1602 16x2 display with esp idf.
Is there some example on how to use one? Thanks in advance.

**Describe the solution you'd like**

I would like to see an example of how to use esp idf with i2c lcd 1602 (PCF8574T)

**Describe alternatives you've considered**

Try to create library by my own.

**Comment by Alvin1Zhang** [comment]
Thanks for raising this feature request.

**Comment by igrr** [comment]
@mvarchdev Not sure why this didn't show up in search, please check it out: https://esp-idf-lib.readthedocs.io/en/latest/groups/pcf8574.html. It is part of https://github.com/UncleRus/esp-idf-lib.

**Comment by mvarchdev** [comment]
I meant something more like library with functions "PrintString","BliknCursorOn" etc... I am working on mine library so once it will be done, I will post here repo link.

**Comment by igrr** [comment]
Thanks @mvarchdev, I'm sure others looking for the same library will appreciate a link to your code, when you have it ready.

I'm going to close the issue since we are unlikely to add such peripheral driver components to esp-idf.

**Comment by mvarchdev** [comment]
So here is the link to library -> https://github.com/mvarchdev/lcd_i2c
