### ISSUE TITLE
Configuration options for ESP-BLE-MESH SDK (IDFGH-4930)

### ISSUE THREAD

**Issue by swanav-erangroup** [espressif/esp-idf#6722]
I am working with ESP-BLE-MESH SDK and I commonly find that a lot of parameters in the SDK are not configurable. I would like to be able to change some behaviors of my BLE Mesh Node, without having to make changes to the ESP-BLE-MESH source.

It would be great if there are some mechanisms to allow configuration of the parameters. Maybe menuconfig or simply a header file override.

**Additional context**

I had to change the below line for a project I'm working on and found no way to override this parameter.

https://github.com/espressif/esp-idf/blob/c49d03b8eb9cb2070960927cbd7194645c44a874/components/bt/esp_ble_mesh/mesh_core/beacon.c#L28

**Comment by Alvin1Zhang** [comment]
Thanks for raising this feature request.
