### ISSUE TITLE
[TW#13144] uart_set_line_inverse() can not set mask back to 0

### ISSUE THREAD

**Issue by zelll** [espressif/esp-idf#673]
As mentioned in https://github.com/espressif/esp-idf/pull/489 , `uart_set_line_inverse()` does not allow a `0` mask. Then there is not a way to clear line inverse. Is it a bug?

> UART_CHECK((((inverse_mask & ~UART_LINE_INV_MASK) == 0) && **(inverse_mask != 0)**), "inverse_mask error", ESP_FAIL);

**Comment by hwmaier** [comment]
What would be the use case for having it to clear again?

I would have thought for a given hardware you either set it or don't depending on your physical layer hardware but never have to change it after you done your hardware initialisation.

**Comment by negativekelvin** [comment]
Possibly if you were talking on a multidrop rs485 bus and switching between different phy settings?

**Comment by hwmaier** [comment]
Ok, if you have to change phys during run-time, then it is useful.

Looking at the code it is intended to work, and  uart_set_line_inverse(port, 0) does work and clears it.

**Comment by zelll** [comment]
I'm adding IDF uart driver to nodemcu. I think someone may want to re-configure uart. Maybe a 485 bus, may be uart controlled by switches...

@hwmaier I added some logs to uart_set_line_inverse(), it does return before clearing the register.
```
    ESP_LOGE(UART_TAG, "### 1");
    UART_CHECK((((inverse_mask & ~UART_LINE_INV_MASK) == 0) && (inverse_mask != 0)), "inverse_mask error", ESP_FAIL);
    ESP_LOGE(UART_TAG, "### 2");
```
outputs:
> [0;31mE (2952) uart: ### 1[0m
[0;31mE (2952) uart: uart_set_line_inverse(195): inverse_mask error[0m
[0;32mI (2992) uart: queue free spaces: 3[0m

**Comment by hwmaier** [comment]
Maybe we are using different versions of code? uart_set_line_inverse(UART_NUM_1, 0) does work in head revision and not throw the inverse_mask error assertion. What value are you passing to clear? It should be a zero to clear.

**Comment by hwmaier** [comment]
You are right, this appears to be a bug. I think the logic should be:

     UART_CHECK((((inverse_mask & ~UART_LINE_INV_MASK) == 0) || (inverse_mask == 0)), "ixnverse_mask error", ESP_FAIL);

**Comment by negativekelvin** [comment]
Isn't that redundant though because if inverse_mask=0 the first test will be true

**Comment by hwmaier** [comment]
Yes, so the test could be even more simplified.

**Comment by FayeY** [comment]
Hi @zelll , is this problem solved now? Can we close this issue?
