### ISSUE TITLE
Is it possible to merge any examples of AirSync? (IDFGH-4940)

### ISSUE THREAD

**Issue by shikaiguo** [espressif/esp-idf#6731]
@xuhongv ESP32 support WeChat airsync. We will merge the airsync example into latest IDF.

_Originally posted by @Weijian-Espressif in https://github.com/espressif/esp-idf/issues/4055#issuecomment-532204720_

**Comment by xuhongv** [comment]
- Thanks

**Comment by igrr** [comment]
Not a Bluetooth developer here, just commenting on the airsync issue from my perspective.

Tencent hasn't released airsync code under a license compatible with Apache 2.0 license used by ESP-IDF, and that prevents the code from being merged.

That being said, it doesn't prevent the code from being released as a standalone component under a different license, similar to [WolfSSL](https://github.com/espressif/esp-wolfssl).
