### ISSUE TITLE
Documentation on how to integrate ota, mqtt and wifi_provisioning over ble demos AWS FreeRTOS ESP32 (IDFGH-4950)

### ISSUE THREAD

**Issue by Yoimer** [espressif/esp-idf#6742]
Hello there. Is there any documentation where I could check in order to integrate 
demos from here https://github.com/aws/amazon-freertos/releases/tag/202012.00?

I want to integrate:
https://github.com/Yoimer/aws_freertos_esp32_components/blob/main/demos/coreMQTT/mqtt_demo_mutual_auth.c
https://github.com/Yoimer/aws_freertos_esp32_components/blob/main/demos/ota/aws_iot_ota_update_demo.c
https://github.com/Yoimer/aws_freertos_esp32_components/blob/main/demos/wifi_provisioning/aws_wifi_connect_task.c

What's in this code is not that clear to me https://github.com/Yoimer/aws_freertos_esp32_components/blob/main/demos/include/iot_demo_runner.h, in order to add another tasks as they mention.

Thanks in advance.

**Comment by mahavirj** [comment]
@Yoimer 

This is not right place to ask questions related to amazon-freertos.

Please use following channels:
https://github.com/aws/amazon-freertos/issues
https://forums.freertos.org/

For this case, I already see your issue at https://github.com/aws/amazon-freertos/issues/3056, so I will go ahead and close this one.
