### ISSUE TITLE
Esp-Idf Rtos Port (IDFGH-4954)

### ISSUE THREAD

**Issue by WGR7** [espressif/esp-idf#6746]
Hi,
Is there any guide to port idf to other rtoses? Seems that idf is tightly coupled with freeRtos.

**Comment by igrr** [comment]
Hi @WGR7, I'm afraid we don't have such a porting guide, as ESP-IDF is not built with the intent to be compatible with RTOS kernels other than FreeRTOS.

However ESP32 series of chips can be supported in other RTOSes and frameworks. For example, Espressif participates in development of NuttX and Zephyr projects, you can use the ESP32 in both of them now ([NuttX docs](https://nuttx.apache.org/docs/latest/platforms/xtensa/esp32/index.html), [Zephyr docs](https://docs.zephyrproject.org/latest/boards/xtensa/esp32/doc/index.html)). We can provide guidance to developers of other RTOSes and frameworks who are interested in adding an ESP32 port.
