### ISSUE TITLE
Wrover module will crash with Log verbosity on debug when SPIRAM is enabled. (IDFGH-4964)

### ISSUE THREAD

**Issue by RicoKirstein** [espressif/esp-idf#6756]
While debugging an Issue I had, I could not get the Wrover to boot with spiram enabled while the Log verbosity was set to Debug.
Debugging this, I realized in esp_efuse_utility.c line 71 an incorrect Log function is used and it should be 
`ESP_EARLY_LOGD(TAG, "In EFUSE_BLK%d__DATA%d_REG is used %d bits starting with %d bit"`,
instead of
`ESP_LOGD(TAG, "In EFUSE_BLK%d__DATA%d_REG is used %d bits starting with %d bit"`,

This fixes the problem and might be the same issue as #6155

Cheers
Rico

## Environment

- Development Kit:      ESP32-Wrover Custom board
- Module or chip used:  ESP32-WROVER|
- IDF version :v4.3-beta1-122-gdbb632fe3

- Build System: idf.py
- Compiler version : xtensa-esp32-elf-gcc.exe (crosstool-NG esp-2020r3) 8.4.0
- Operating System:    Windows
- (Windows only) environment type: ESP Command Prompt/poweshell
- Using an IDE?: VSCode with IDF extension 1.01
- Power Supply:      external 5V

Here is my logoutput:
```

Backtrace:0x4008cbe2:0x3ffe3a80 0x400924ce:0x3ffe3ac0 0x4017e7f5:0x3ffe3ae0 0x40092465:0x3ffe3b10 0x40102b45:0x3ffe3b60 0x40102a1d:0x3ffe3bc0 0x401028ed:0x3ffe3be0 0x40083324:0x3ffe3c10 0x400d95d3:0x3ffe3c40 0x4008165a:0x3ffe3c60 0x4007913a:0x3ffe3c90 |<-CORRUPTED
0x4008cbe2: xQueueSemaphoreTake at ../idf/esp-idf/components/freertos/queue.c:1441 (discriminator 1)
0x400924ce: esp_log_impl_lock_timeout at ../idf/esp-idf/components/log/log_freertos.c:45
0x4017e7f5: esp_log_writev at ../idf/esp-idf/components/log/log.c:170
0x40092465: esp_log_write at ../idf/esp-idf/components/log/log.c:199
0x40102b45: esp_efuse_utility_process at ../idf/esp-idf/components/efuse/src/esp_efuse_utility.c:71 (discriminator 9)
0x40102a1d: esp_efuse_read_field_blob at ../idf/esp-idf/components/efuse/src/esp_efuse_api.c:47
0x401028ed: esp_efuse_get_pkg_ver at ../idf/esp-idf/components/efuse/src/esp32/esp_efuse_fields.c:65
0x40083324: psram_enable at ../idf/esp-idf/components/esp32/spiram_psram.c:808
0x400d95d3: esp_spiram_init at ../idf/esp-idf/components/esp32/spiram.c:150
0x4008165a: call_start_cpu0 at ../idf/esp-idf/components/esp_system/port/cpu_start.c:348
```

**Comment by mahavirj** [comment]
@RicoKirstein 

Please see https://github.com/espressif/esp-idf/issues/6660#issuecomment-791264167

I will close this one, fix for #6660 is merged internally and should appear soon on github.
