### ISSUE TITLE
otatool.py improperly reads ota data seq and crc (IDFGH-4983)

### ISSUE THREAD

**Issue by etchove** [espressif/esp-idf#6773]
## Problem Description

The method `_get_otadata_info` is unpacking ota data with `">I"` format but data is packed with `"I"` format in method `switch_ota_partition`. This causes readen data to be invalidated by `is_otadata_info_valid`... so sequence allways restarts to 0.

The otatool.py still works, but doesn't respect ota seq incease.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting. Would you please help provide more details as suggested in the [issue template](https://github.com/espressif/esp-idf/issues/new?assignees=&labels=&template=bug_report.md&title=)? Information like elf, sdk configuration, backtrace, log outputs, commit ID, hardware and etc. would help us debug further. Thanks.

**Comment by KonstantinKondrashov** [comment]
Hi @etchove!
The fix for master is here [12900.zip](https://github.com/espressif/esp-idf/files/6199695/12900.zip)
What is your IDF version? We will provide the backports.
Thanks.

**Comment by etchove** [comment]
Hi,

Thank's for your bugfix, that's perfect ! I'm using idf 4.1.

Etienne

Le 24-03-2021 19:39, Konstantin Kondrashov a écrit :

> Hi @etchove [1]!
> The fix for master is here 12900.zip [2]
> What is your IDF version? We will provide the backports.
> Thanks.
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [3], or unsubscribe 
> [4].



Links:
------
[1] https://github.com/etchove
[2] https://github.com/espressif/esp-idf/files/6199695/12900.zip
[3] 
https://github.com/espressif/esp-idf/issues/6773#issuecomment-806065347
[4]
