### ISSUE TITLE
mqtt examples certificates expired (IDFGH-4986)

### ISSUE THREAD

**Issue by KaeLL** [espressif/esp-idf#6776]
Both `ssl` and `wss` examples' certificates expired a week ago.
`Not After : Mar 17 16:40:46 2021 GMT`

**Comment by Alvin1Zhang** [comment]
Thanks for pointing out, we will look into soon, thanks.

**Comment by Alvin1Zhang** [comment]
@KaeLL Thanks for reporting, we had a fix under internal reviewing. The issue will be closed automatically once the fix is available on GitHub. Thanks.
