### ISSUE TITLE
[TW#13155] Documentation of RS-485 related features

### ISSUE THREAD

**Issue by EndlessDelirium** [espressif/esp-idf#678]
Earlier versions of the datasheet state that there is integrated RS-485 support:
> ESP32 has three UART interfaces, i.e. UART0, UART1 and UART2, which provide asynchronous communication (RS232 and RS485) and IrDA support, and communicate at up to 5 Mbps.

The current technical reference manual (v1.7) still mentions RS-485 support on page 189:
> Supports RS485 Protocol

There is also a very brief documentation of RS-485 related registers.

Due to the very limited documentation, unfortunately no one seems to have managed to successfully use these functionalities yet. Better documentation and an example would therefore be highly appreciated.

This topic is also discussed in the ESP32 forums: https://esp32.com/viewtopic.php?f=13&t=1858

@hwmaier was so kind to provide a software based implementation for the most imminent issue of automated enabling/disabling of the transceiver: https://github.com/espressif/esp-idf/pull/667

Edit (2017-09-17):
Thanks to @pctj101 there is now also an example that makes use of @hwmaier 's pull request. See #1006

**Comment by negativekelvin** [comment]
Also need these docs

**Comment by tusharvb19** [comment]
I also need the docs and sample code..help me
TIA.

**Comment by hrgdavor** [comment]
RS485 support looks like a very nice addition. subscribed to changes on this. Interested to try it when it works :)

**Comment by voxadam** [comment]
Proper RS-485 support would be incredibly useful.

**Comment by bookerdong** [comment]
Proper RS-485 support would be incredibly useful.

**Comment by casmeiron** [comment]
yeah, that would be a gr8 feature to have!

**Comment by igrr** [comment]
RS485 support is included since https://github.com/espressif/esp-idf/commit/909eec9c3b174a080e8fed10c0315d43ded5dfd5.
