### ISSUE TITLE
Can not build ESP-IDF A2DP-SINK demo on ESP32 C3 (IDFGH-5008)

### ISSUE THREAD

**Issue by jassi00713** [espressif/esp-idf#6794]
Can not build ESP-IDF A2DP-SINK demo on ESP32 C3.

While building following error comes up - 

.../hci_layer.c: In function 'hci_layer_init_env':
.../hci_layer.c:184:5: error: implicit declaration of function 'btsnd_hcic_ble_sync_sem_init'; did you mean 'btsnd_hcic_ble_set_phy'? [-Werror=implicit-function-declaration]
     btsnd_hcic_ble_sync_sem_init();
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
     btsnd_hcic_ble_set_phy

Is ESP32 C3 not supported for this Example?

**Comment by Wth-Esp** [comment]
Hi, @jassi00713 

ESP32-C3 supports Low Energy Bluetooth and Wi-Fi, doesn't support Classic BT.
For more information please refer to [ESP32-C3](https://www.espressif.com/en/products/socs/esp32-c3).


Thanks
