### ISSUE TITLE
Bluetooth Audio over ESP32 C3 (IDFGH-5013)

### ISSUE THREAD

**Issue by jassi00713** [espressif/esp-idf#6799]
As ESP32 C3 supports wifi and ble 5.0 and not classic bluetooth.

How can i stream audio from a device to esp32 c3 over ble?
a2dp examples wont work as they are for classic bluetooth.

Kindly suggest the best way to go ahead in this as i am developing a solution involving music streaming over bluetooth and i want to use ESP32 C3.

Thanks

**Comment by Wth-Esp** [comment]
Hi, @jassi00713 

It's impossible to stream audio via LE radio with Bluetooth 5.0. You can stream audio with **Wi-Fi** on ESP32-C3 or you can choose **ESP32** and use Classic BT profile A2DP to stream audio.

**Bluetooth 5.2** features LE Audio will make it possible to stream audio on LE radio.

Thanks

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, feel free to reopen.
