### ISSUE TITLE
nimble build error if CONFIG_BT_NIMBLE_ROLE_BROADCASTER is not set (IDFGH-5020)

### ISSUE THREAD

**Issue by AxelLin** [espressif/esp-idf#6806]
## Environment

Module or chip used: ESP32-WROOM-32E
IDF version: v4.4-dev-479-g1067b28707e5 and v4.3-beta2-2-g9a2d251912fa
Build System: idf.py
Compiler version: xtensa-esp32-elf-gcc (crosstool-NG esp-2020r3) 8.4.0
Operating System: Linux
Power Supply: USB

## Problem Description

I got below build error if CONFIG_BT_NIMBLE_ROLE_BROADCASTER is not set.

/home/axel/esp/esp-idf/components/bt/host/nimble/nimble/nimble/host/src/ble_gap.c: In function 'ble_gap_slave_timer':
/home/axel/esp/esp-idf/components/bt/host/nimble/nimble/nimble/host/src/ble_gap.c:1976:10: error: implicit declaration of function 'ble_gap_adv_enable_tx'; did you mean 'ble_gap_disc_enable_tx'? [-Werror=implicit-function-declaration]
     rc = ble_gap_adv_enable_tx(0);
          ^~~~~~~~~~~~~~~~~~~~~
          ble_gap_disc_enable_tx
cc1: some warnings being treated as errors

However, my application does not advertise at all.

### Code to fix this issue
Below changes add proper #if guard in nimble fixes the build issue.

```
diff --git a/nimble/host/src/ble_gap.c b/nimble/host/src/ble_gap.c
index 9e275c54fd0a..e5ce389a7a17 100644
--- a/nimble/host/src/ble_gap.c
+++ b/nimble/host/src/ble_gap.c
@@ -948,7 +948,7 @@ ble_gap_master_ticks_until_exp(void)
     return 0;
 }
 
-#if !MYNEWT_VAL(BLE_EXT_ADV)
+#if NIMBLE_BLE_ADVERTISE && !MYNEWT_VAL(BLE_EXT_ADV)
 static uint32_t
 ble_gap_slave_ticks_until_exp(void)
 {
@@ -1957,7 +1957,7 @@ ble_gap_master_timer(void)
     return BLE_HS_FOREVER;
 }
 
-#if !MYNEWT_VAL(BLE_EXT_ADV)
+#if NIMBLE_BLE_ADVERTISE && !MYNEWT_VAL(BLE_EXT_ADV)
 static int32_t
 ble_gap_slave_timer(void)
 {
@@ -2056,7 +2056,7 @@ ble_gap_timer(void)
 
     min_ticks = min(master_ticks, update_ticks);
 
-#if !MYNEWT_VAL(BLE_EXT_ADV)
+#if NIMBLE_BLE_ADVERTISE && !MYNEWT_VAL(BLE_EXT_ADV)
     min_ticks = min(min_ticks, ble_gap_slave_timer());
 #endif
 

```

**Comment by dhrishi** [comment]
Hi @AxelLin, Thanks for reporting the issue. Yes, it looks to be a genuine one. The fix for this is already present upstream: 
https://github.com/apache/mynewt-nimble/commit/d11729a60aaee277a9516d93d8fb8fe6be78c5ee

We will add the commit to esp-nimble. Thanks!
