### ISSUE TITLE
Listening Server sent events using esp http client (IDFGH-5029)

### ISSUE THREAD

**Issue by devUsama** [espressif/esp-idf#6815]
esp_http_client library should support listening server sent events
I want to call Firebase Streaming REST API to listen Server-Sent Events on esp32 http client. So that if any other client push changes to server database esp http client get notified for these changes.

Here is the link for firebase Streaming REST API use case documentation:
https://firebase.google.com/docs/database/rest/retrieve-data#section-rest-streaming

In the above documentation the main guide line is to set the client's accept header to text/event-stream. So I want to know is there any support exist for such APIs? If not then is there any plan for the support for streaming APIs in future?

I think its a useful feature and also esp-idf don't have the support for Firebase integration which is a commonly used cloud platform, so if esp-idf support listening server sent events then developers can have Firebase Realtime database integration using Streaming REST APIs for their IoT devices.

**Comment by CharlesMcBaker** [comment]
This would be great
