### ISSUE TITLE
idf.py create-project  fails (IDFGH-5033)

### ISSUE THREAD

**Issue by cbaurtx** [espressif/esp-idf#6819]
installed esp.idf on a linux system and it works great except for:
idf.py create-project myproject

I get this output:

*Executing action: create-project
CMakeLists.txt not found in project directory /home/me/Development/Source/ESP32*

So was this dropped? Is the documentation (Web site) wrong?

**Comment by dobairoland** [comment]
Hi @cbaurtx. This feature is available but maybe not in the IDF version you are using. Please tell us which version are you using, ie. the output of `idf.py --version` or `git describe --tags`.

**Comment by cbaurtx** [comment]
#i got it all working. The latest version of my code builds fine

**Comment by cbaurtx** [comment]
Check out the newest version which is compiling and working

**Comment by dobairoland** [comment]
Thank you for the feedback!

**Comment by mrhempman69** [comment]
This error exists again, such a joke

**Comment by dobairoland** [comment]
> This error exists again, such a joke

If you still experience the issue then open a new one and provide all the necessary information for reproducing it.
