### ISSUE TITLE
Incorrect ethernet initialization sequence. PHY: LAN8720 (IDFGH-5035)

### ISSUE THREAD

**Issue by Sejny** [espressif/esp-idf#6821]
I found bug in IDF ethernet driver. PHY LAN8720 initialization sequence is not correct. PHY clock is supplied by ESP32 (ETH_CLOCK_GPIO17_OUT), tested on ESP-IDF Release v3.3.5

**ESP must deliver PHY clock approx 40 clock cycles before PHY reset go HIGH.**

**Microchip note in LAN8720 datasheet:**
![LAN8720_RstTiming](https://user-images.githubusercontent.com/15101342/113518147-acaa5d80-9584-11eb-858c-a65a3449b39b.png)

**Measured on real setup:**
![LAN8720_ESP32Timing](https://user-images.githubusercontent.com/15101342/113518455-c056c380-9586-11eb-9214-32bd4b878e9a.png)

Iam not skilled for repair this self :(

**Comment by suda-morris** [comment]
Hi @Sejny May I ask how you do the PHY hardware reset in your code? In IDF 3.3, we didn't provide a "reset GPIO" configuration in the ethernet driver.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, fix is available https://github.com/espressif/esp-idf/commit/fc60e0929562fbe9e033ed998eeb8760948c0f02, feel free to reopen.
