### ISSUE TITLE
tinyusb HID class not supported (IDFGH-5054)

### ISSUE THREAD

**Issue by oswaldtoma** [espressif/esp-idf#6839]
## Environment

- Development Kit: ESP32-S2-Saola-1
- Module or chip used:  ESP32-S2WROVER
- IDF version: master
- Build System: idf.py
- Compiler version: xtensa-esp32s2-elf-gcc
- Operating System:     [Windows|Linux|macOS]
- (Windows only) environment type: Plain Command Prompt
- Using an IDE?: Yes (Eclipse with ESP-IDF plugin)
- Power Supply: USB

## Problem Description

The menuconfig accessible from idf.py script, doesn't provide us with an option to turn on HID.

### Expected Behavior

There should be.

### Actual Behavior

There's not.

### Steps to reproduce

Run idf.py menuconfig ¯\_(ツ)_/¯

**Comment by dobairoland** [comment]
Hi @oswaldtoma. This is under development right now and will be available in the future. That is why you cannot find it in the menuconfig.

**Comment by oswaldtoma** [comment]
When can it be expected?

**Comment by abdulwasey7** [comment]
any updates regarding this feature?

**Comment by leeebo** [comment]
@oswaldtoma @abdulwasey7 You can temporary have a try using: https://github.com/iot-components/examples_tinyusb_esp32sx

**Comment by AEFeinstein** [comment]
This weekend I forked the IDF and added an HID option to menuconfig: https://github.com/AEFeinstein/esp-idf/commit/64f4918db0a687e093ad841704f8c9cb6a98db87. Specifically I was working to get an ESP32-S2 to enumerate as a gamepad. My IDF changes are nowhere near ready to be pulled into the main one, but they're relatively simple and they do work on a ESP32-S2-DEVKITC-1R. At a minimum it still needs a way to configure keyboard, mouse, or gamepad via menuconfig. Two callbacks need to be defined in the application code too, which isn't the best design.

@dobairoland, I'm curious how similar your development is to what I did. Is it in a public branch?

**Comment by AachoLoya** [comment]
I also need to create USB HID keyboard/mouse device using ESP32-S2. Any progress on this front?

**Comment by AEFeinstein** [comment]
A tiny bit (pun intended). I learned that components in your ESP32 project will override components from the IDF if they have the same name. So I copied the `tinyusb` component into my `components` folder, made a few tweaks (see my prior comment), and got my USB gamepad working nicely without modifications to the IDF.

See here: https://github.com/AEFeinstein/esp32-c3-playground/tree/main/components/tinyusb

**Comment by AachoLoya** [comment]
So you copied tinyusb as-is from the original git repo into the components folder? The code in additions folder, is that the IDF changes or something specific to your project?

**Comment by AEFeinstein** [comment]
> So you copied tinyusb as-is from the original git repo into the components folder?

Yep

> The code in additions folder, is that the IDF changes or something specific to your project?

That came from the IDF. The changes I made are in a commit which I linked to in my first comment.

**Comment by AEFeinstein** [comment]
It's in https://github.com/AEFeinstein/esp32-c3-playground, though I haven't detailed what hardware you need to run it. Just search the code for `tusb` for now.

**Comment by AEFeinstein** [comment]
Also the project name is a misnomer. I've been working with an S2. I know your asked about S3, but they should be similar enough
