### ISSUE TITLE
[TW#13260] Current consumption not varying for different Transmitter powers

### ISSUE THREAD

**Issue by Raienryu97** [espressif/esp-idf#684]
I tried setting different values from 0 to 20 dBm for the Tx of WiFi radio using the setting  
Under make menuconfig > Component config > PHY >  Max WiFi TX Power, flashed a program and kept checking for the current the board is drawing. I've observed that the current consumption is same for all values of Tx Power.

Can someone verify if they're facing the same issue?
Or am I supposed to change something else too?

Thanks

**Comment by Raienryu97** [comment]
Bump. Any update?

**Comment by jack0c** [comment]
@Raienryu97 Do you select Do phy calibration and store calibration data in NVS?

**Comment by TimXia** [comment]
@Raienryu97 What are the values of current consumption that you have measured before and after setting Max WiFi Tx Power?

**Comment by jack0c** [comment]
@FayeY maybe we can close this issue.

**Comment by FayeY** [comment]
Closing due to lack of response, please feel free to reopen if this is still an issue. Thanks.
