### ISSUE TITLE
How to send data (write char) to BLE without delay?

### ISSUE THREAD

**Issue by lishengzhen123** [espressif/esp-idf#685]
I call the **esp_ble_gattc_write_char()** method to send a command to my BLE device, the command is an uint16_t array contain only 40 data like this:

`uint16_t rawCodes[] = {2550, 950, 350, ……., 600, [300};`

I think my data is small enough, but I still get 500ms delay when I send the command from ESP32 to my BLE device. I found the delay  is almost in the method "esp_ble_gattc_write_char()".  It's too long to me , I hope the delay should not more than 50ms at least.

So maybe I have something wrong with the method called, or I should call another method to send data. I hope you can give me some suggestion on how to send the data without delay, thank you very much!

This is my code that I call the method  "esp_ble_gattc_write_char()" to send my data(rawCodes):

```
sendData(conn_id, (uint8_t*)&rawCodes, sizeof(rawCodes));

void sendData(uint16_t conn_id, uint8_t *value, uint16_t len) {
   esp_ble_gattc_write_char(
     4,                                          
     conn_id,                           
     &service_id,                              
     &tx_rx_id,                                 
     len,                                               
     value,                                               
     ESP_GATT_WRITE_TYPE_RSP,           
     ESP_GATT_AUTH_REQ_NONE);
 }
```
Log Info:
```
**********************GATT CALLBACK  4**************************
WRITE: status 0
sending...
E (220278) BT: value resp op_code = ATT_RSP_PREPARE_WRITE len = 22
E (220378) BT: value resp op_code = ATT_RSP_PREPARE_WRITE len = 22
E (220478) BT: value resp op_code = ATT_RSP_PREPARE_WRITE len = 22
E (220578) BT: value resp op_code = ATT_RSP_PREPARE_WRITE len = 22
E (220678) BT: value resp op_code = ATT_RSP_PREPARE_WRITE len = 16
```

**Comment by ESP32DE** [comment]
@lishengzhen123 

> So maybe I have something wrong with the method called, or I should call another method to send data. I hope you can give me some suggestion on how to send the data without delay, thank you very much!

cause this is not direct an issues with the ESP-IDF
perhabs better this write to the official [esp32 forum here](http://esp32.com) 

best wishes
rudi ;-)
