### ISSUE TITLE
build stopped: subcommand failed. (IDFGH-5073)

### ISSUE THREAD

**Issue by 1289737137** [espressif/esp-idf#6857]
![AID`W~@VRUSA7SWO5Y52%}5](https://user-images.githubusercontent.com/72856241/114303828-a6772c80-9b02-11eb-9425-8b6aba658e44.png)

**Comment by 1289737137** [comment]
idf.py build,failed.

**Comment by Alvin1Zhang** [comment]
@1289737137 Thanks for reporting. Would you please help provide more details as suggested in the [issue template](https://github.com/espressif/esp-idf/issues/new?assignees=&labels=&template=bug_report.md&title=)? Information like elf, sdk configuration, backtrace, log outputs, commit ID, hardware and etc. would help us debug further. Thanks.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to short of feedback, feel free to reopen with more details. Thanks.
