### ISSUE TITLE
BLE Mesh Provisioner generates value 0 outside of Specification for Push, Twist (IDFGH-5079)

### ISSUE THREAD

**Issue by dastarling** [espressif/esp-idf#6863]
## Environment
- Development Kit: ESP32-C3-DevKitM-1
- Kit version [v1.0]
- Module or chip used: ESP32-C3-Mini-1
- IDF version (run git describe --tags to find it):
  v4.4-dev-744-g1cb31e509
- Build System: idf.py
- Compiler version (run xtensa-esp32-elf-gcc --version to find it):
  riscv32-esp-elf-gcc (crosstool-NG 1.24.0.123_64eb9ff) 8.4.0
- Operating System: Linux
- Using an IDE?: Yes VS Code
- Power Supply: USB
- 

## Problem Description
When using the Input OOB Push method, 0 is output sometimes, which is invalid per spec.  Likely an issue with input OOB Blink, Beep, and Vibrate as well in Node device.

**Mesh Profile Spec v1.0.1**
When the Authentication Method 0x03 (Authentication with Input OOB) method is used and when Input OOB Action for the Authentication Action value is equal to Push, then the Provisioner shall select a random integer between 0 and 10 to the power of the Authentication Size exclusive. That random number shall be input by the number of push actions. When Input OOB Action for the Authentication Action value is equal to Twist, then the Provisioner shall select a random integer between 0 and 10 to the power of the Authentication Size exclusive. That random number shall be input by the number of twist actions until the value on the control has been entered.

### Expected Behavior
Push Button OOB to be 1-9

### Actual Behavior
Sometimes it will be 0

### Steps to reproduce

1. Setup Provisioner for BLE Mesh
2. Configure Node on BLE Mesh to use Input Push Button Auth
3. During Auth Procedure Provisioner will sometimes output 0 for Button Presses

### Code to reproduce this issue
See https://github.com/espressif/esp-idf/blob/master/components/bt/esp_ble_mesh/mesh_core/prov.c:753

**Comment by InfiniteYuan** [comment]
@dastarling Can you provide some logs?
