### ISSUE TITLE
Required clarification about the Ble mesh scene server and scene server model  (IDFGH-5087)

### ISSUE THREAD

**Issue by ankit-thealchemist** [espressif/esp-idf#6871]
- Kit version DevKitCv4
- Module or chip used:  [ESP32-WROOM-32]
- IDF version (run ``git describe --tags`` to find it):
    // v4.3-dev-2399-gea9063197
- Build System:         [Make|CMake|idf.py]
- Operating System:     Windows|

## Problem Description

I was implementing the scene server and the scene setup server model. I have 3 elements on the node. I have implement the scene server and the setup server on the primary element. Every thing seems fine . But when I implement the models on the other elements including the primary element, I got the warning that "Ble mesh scene server not found on the primary element" and "ble mesh scene setup server not found on the primary element". My question is that, is the implementation of the scene server and scene setup server is restricted to the primary element only?

**Comment by InfiniteYuan** [comment]
![image](https://user-images.githubusercontent.com/13313946/114982344-e868ef80-9ec1-11eb-89ce-fb7033a30a7e.png)

**Comment by ankit-thealchemist** [comment]
So the conclusion is, implementation of the scene server and setup server  has  only one instance in the node at the primary element only. 

Thanks for support!
