### ISSUE TITLE
IOS connection ESP32 BLE, peripheral name and local name is different (IDFGH-5100)

### ISSUE THREAD

**Issue by liu3216080** [espressif/esp-idf#6884]
### Environment

*Module or chip used: ESP32-WROOM-32D
*IDF version ESP-IDF Release v3.3.5
*The mobile phone used is apple,version 14.4.2
*The BLE test tool is LightBlue
*Official example:gatt_server

### Problem Description
Specific operations :(1) Set BLE name to TS-21C04, start the program 
					 (2) Change BLE name to ESP-GATTS_DEMO, start the program 
					 (3) The final phenomenon is like the picture

How to deal with this problem????

related pictures:
![1111111](https://user-images.githubusercontent.com/31657657/114982635-47c6ff80-9ec2-11eb-89cd-daa879aa9d45.png) 
other pictures:
![8a0e9eefd7e3515183ebcc0e5455fce](https://user-images.githubusercontent.com/31657657/114982790-747b1700-9ec2-11eb-9ac4-e01df9f9ddce.jpg)
![e78a531dd99f89b41c76e691e974cab](https://user-images.githubusercontent.com/31657657/114982820-7cd35200-9ec2-11eb-924d-01d4284c3b3f.jpg)

How to deal with this problem????，Thank you！！！！

**Comment by xiewenxiang** [comment]
@newchangeday 

The device name of BLE are defined in two ways, the one is ADV data and the other is device name characteristic.

If the two definitions are different, the phenomenon will show up.

**Comment by Alvin1Zhang** [comment]
@newchangeday Thanks for reporting. Would you please help share if any updates or details for this issue? Thanks.

**Comment by Alvin1Zhang** [comment]
@newchangeday Thanks for reporting. Would you please help share if any updates or details for this issue? Thanks.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to short of feedback, feel free to reopen with more updates, thanks.
