### ISSUE TITLE
Typo (IDFGH-5103)

### ISSUE THREAD

**Issue by chegewara** [espressif/esp-idf#6887]
https://github.com/espressif/esp-idf/blob/master/components/bt/host/bluedroid/api/include/api/esp_gap_ble_api.h#L873

Typo in struct name `esp_ble_gap_ext_adv_reprot_t` which is reproduced in whole API.

**Comment by chegewara** [comment]
https://github.com/espressif/esp-idf/blob/master/components/bt/host/bluedroid/api/include/api/esp_gap_ble_api.h#L207

`ESP_GAP_BLE_CHANNEL_SELETE_ALGORITHM_EVT`

**Comment by chegewara** [comment]
https://github.com/espressif/esp-idf/blob/master/components/bt/host/bluedroid/api/include/api/esp_gap_ble_api.h#L1145

`peroid_adv_set_params`

**Comment by chegewara** [comment]
Another typo (copy/paste bug):
https://github.com/espressif/esp-idf/blob/master/components/usb/hcd.c#L1451
should be `USB_PRIV_XFER_TYPE_BULK`

**Comment by Dazza0** [comment]
> Another typo (copy/paste bug):
> https://github.com/espressif/esp-idf/blob/master/components/usb/hcd.c#L1451
> should be `USB_PRIV_XFER_TYPE_BULK`

Closed by 7f421048936c6007186db00ed382cd989c4b905e
