### ISSUE TITLE
Failed to use Rotary_encoder_example  (IDFGH-5105)

### ISSUE THREAD

**Issue by zsjlovestudy** [espressif/esp-idf#6889]
Because I used pins 10 and 11 on the PCB , when I changed the GPIO pins in the example, there was an error.

I need to use four rotary encoders simultaneously。However, after I made four copies according to the template of the sample code, he made a mistake of interrupting the repeated registration. Could you please tell me how to solve this?

When I comment out the code that breaks registration, I can run all three at once, except for pins 10 and 11.

![image](https://user-images.githubusercontent.com/52393677/115039047-add37700-9f02-11eb-92c4-ab1b3ea965ff.png)

![image](https://user-images.githubusercontent.com/52393677/115040314-e031a400-9f03-11eb-9b54-247f5c25e4d6.png)

![image](https://user-images.githubusercontent.com/52393677/115040360-efb0ed00-9f03-11eb-9548-b0e0cd9593c6.png)

**Comment by suda-morris** [comment]
GPIO10 and GPIO11 on ESP32 are used by SPI flash by default, please refer to datasheet and  `soc/esp32/include/soc/io_mux_reg.h` for more details.
As for the example itself, if you want to drive multiple encoders with overflow handling (in interrupt handler), you need to alter the example, make sure calling `pcnt_isr_service_install` only once globally. And handle the overflow event for each pcnt unit respectively in the ISR callback.

**Comment by zsjlovestudy** [comment]
Hello, I have read the io_mux_reg.h file, but I don't quite understand it.First I want to know if 10 and 11 can be modified to be used as encoders.Secondly, if possible, how to modify it？

**Comment by suda-morris** [comment]
Hi @zsjlovestudy GPIO11 is `SPI_CS0_GPIO_NUM` you can't use it for other purposes.

**Comment by zsjlovestudy** [comment]
> Hi @zsjlovestudy GPIO11 is `SPI_CS0_GPIO_NUM` you can't use it for other purposes.

Hello, could you please tell me if there are any other pins like 11 pins? Because I need to specify the pin  to PWM and encoder at present.
![image](https://user-images.githubusercontent.com/52393677/115535321-379c8f00-a2cb-11eb-9281-061cb74183a0.png)

**Comment by suda-morris** [comment]
The following GPIOs are used by SPI Flash by default:
```c
#define SPI_CLK_GPIO_NUM                            6
#define SPI_CS0_GPIO_NUM                            11
#define SPI_Q_GPIO_NUM                              7
#define SPI_D_GPIO_NUM                              8
#define SPI_WP_GPIO_NUM                             10
#define SPI_HD_GPIO_NUM                             9
```

**Comment by camrbuss** [comment]
In order to create multiple encoder instances the `ROTARY_CHECK` needs to be avoided from the `pcnt_isr_service_install` call. I added this switch to the "register interrupt handler" section of rotary_encoder_pcnt_ec11.c so that I could have multiple encoder instances.

``` c
	// register interrupt handler
	switch(pcnt_isr_service_install(0))
	{
		case ESP_OK:
			break;
		case ESP_ERR_INVALID_STATE:
			ESP_LOGI(TAG, "pcnt isr already installed");
			break;
		default:
			ROTARY_CHECK(1==0, "install isr service failed", err, ESP_FAIL);
	}
```

Does anyone want a pull request for something like this? Is this component going to be an "official" component one day?

**Comment by suda-morris** [comment]
Hi @camrbuss yes, the issue you found is correct. The interrupt is shared by PCNT channels, it should be installed only once.

>  Is this component going to be an "official" component one day?

We don't have a plan to raise the level of this example component, but we're working on new PCNT driver APIs to make that peripheral more flexible, especially for encoders use cases.

**Comment by yangwc** [comment]
I ran into the same problem. I configured two encoder. 
![image](https://user-images.githubusercontent.com/10265618/125451054-ce4c2d56-10c3-4e01-9e22-91faaa0aff78.png)

![image](https://user-images.githubusercontent.com/10265618/125451205-e3aa5c46-6688-4e69-8152-3370f7719bf1.png)
