### ISSUE TITLE
modus problem. (IDFGH-5108)

### ISSUE THREAD

**Issue by hnhkj** [espressif/esp-idf#6892]
关于modbus主机模式，发现了一个问题：
当主机读取一个指令返回的消息产生一个ESP_ERR_INVALID_RESPONSEE消息后。系统不能清除保留的接收到的数据。造成下次发送读取指令，接收到的是上一个指令的返回数据。返回数据的侦检测是正确的，但是不是当前指令的返回侦，而是上一个指令的返回侦。很苦恼！

**Comment by alisitsyn** [comment]
@hnhkj ,

Please see the response here: https://github.com/espressif/esp-idf/issues/6891

**Comment by Alvin1Zhang** [comment]
@hnhkj Thanks for reporting, would you please help share if any updates for this issue? Thanks.

**Comment by alisitsyn** [comment]
The issue is obsolete and will be closed. The fix is implemented in latest version of esp-modbus. This fixes the issue with the poll cycle and incorrect processing of slave responses after timeout.
