### ISSUE TITLE
[BLE5] extended advertising payload length (IDFGH-5109)

### ISSUE THREAD

**Issue by chegewara** [espressif/esp-idf#6893]
According to `BLUETOOTH SPECIFICATION Version 5.0 | Vol 6, Part B` chapter `2.3.4 Common Extended Advertising Payload Format` (page 2580, figure 2.14) AdvData can be 0-254 bytes length. 
https://github.com/espressif/esp-idf/blob/master/components/bt/host/bluedroid/api/include/api/esp_gap_ble_api.h#L872

**Comment by xiewenxiang** [comment]
If the length of the package exceeds the limit(229 bytes), it will subcontracted and report to host.

**Comment by xiewenxiang** [comment]
BLUETOOTH CORE SPECIFICATION Version 5.2 | Vol 4, Part E
7.7.65.13 LE Extended Advertising Report event

Data_Length[i]:
0 to 229, Length of the Data[i] field for each device which responded

**Comment by Alvin1Zhang** [comment]
@chegewara Thanks for reporting. Would you please help share if any updates or details for this issue? Thanks.
