### ISSUE TITLE
EAP support?

### ISSUE THREAD

**Issue by ivanO86** [espressif/esp-idf#69]
Hi all,

I have just started a new project with an ESP32 board and I need WPA-enterprise support for some applications. It is not a mandatory feature at this moment, but I will need it, and I can not find a solution in your esp_wifi library. Are you thinking about add this encryption support?

Thank you. Best regards

**Comment by negativekelvin** [comment]
> WiFi WPA2-Enterprise and WPS are not supported **yet**

https://github.com/espressif/esp-idf/releases

**Comment by igrr** [comment]
WPS support is going to be added soon (~this week). WPA-enterprise is going to be added somewhere before 1.0 release at the end of this month.

**Comment by ivanO86** [comment]
Thanks for your update.

**Comment by projectgus** [comment]
WPA Enterprise now supports EAP-TLS, PEAP-MSCHAPv2 and TTLS-MSCHAPv2.
