### ISSUE TITLE
调用esp_wifi_sta_get_ap_info后，UDP接收数据丢失 (IDFGH-5126)

### ISSUE THREAD

**Issue by Vinx911** [espressif/esp-idf#6908]
## Environment

- Development Kit: none
- Kit version (for WroverKit/PicoKit/DevKitC):
- Module or chip used:  ESP32S2
- IDF version (run ``git describe --tags`` to find it): v4.4-dev-960-gcf457d412
- Build System: idf.py
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it): xtensa-esp32s2-elf-gcc.exe (crosstool-NG esp-2020r3) 8.4.0
- Operating System:     Windows
- (Windows only) environment type: ESP Command Prompt
- Using an IDE?: Yes (VSCode)]
- Power Supply:         [USB|external 5V|external 3.3V|Battery]

## Problem Description

在UDP接受数据时，定时检测WIFI的rssi会导致UDP接收数据丢失。

上位机以100ms的速度向模块发送UDP数据，不调用esp_wifi_sta_get_ap_info时，数据接收正常。调用esp_wifi_sta_get_ap_info时，接收几秒钟后就会停止，之后过几秒后接收几包数据

### Expected Behavior
每100ms读取一次rssi，UDP数据每200ms发送一次
I (9860) example: rssi = 0
I (9900) example: Received 4 bytes from 192.168.13.102:
I (9960) example: rssi = 0
I (10060) example: rssi = 0
I (10110) example: Received 4 bytes from 192.168.13.102:
I (10160) example: rssi = 0
I (10260) example: rssi = 0
I (10310) example: Received 4 bytes from 192.168.13.102:
I (10360) example: rssi = 0
I (10460) example: rssi = 0
I (10520) example: Received 4 bytes from 192.168.13.102:
I (10560) example: rssi = 0
I (10660) example: rssi = 0
I (10730) example: Received 4 bytes from 192.168.13.102:

### Actual Behavior
每100ms读取一次rssi，UDP数据每200ms发送一次
I (5069) example: rssi = -35
I (5169) example: rssi = -36
I (5269) example: rssi = -36
I (5369) example: rssi = -36
I (5429) example: Received 4 bytes from 192.168.13.102:
I (5429) example: Received 4 bytes from 192.168.13.102:
I (5429) example: Received 4 bytes from 192.168.13.102:
I (5469) example: rssi = -39
I (5569) example: rssi = -39
I (5669) example: rssi = -36
I (5769) example: rssi = -36
I (5869) example: rssi = -39
I (5969) example: rssi = -37
I (6069) example: rssi = -36
I (6129) example: Receyved 4 bytes from 192.168.13.102:
I (6129) example: Received 4 bytes from 192.168.13.102:
I (6129) example: Received 4 bytes from 192.168.13.102:
I (6129) example: Received 4 bytes from 192.168.13.102:
I (6169) example: rssi = -39
I (6269) example: rssi = -36
I (6369) example: rssi = -36
I (6469) example: rssi = -36
I (6569) example: rssi = -35
I (6669) example: rssi = -35
I (6769) example: rssi = -35
I (6869) example: rssi = -35
I (6969) example: rssi = -35
I (7069) example: rssi = -35
I (7169) example: rssi = -35
I (7269) example: rssi = -35
I (7369) example: rssi = -35
I (7469) example: rssi = -34
I (7569) example: rssi = -35
### Steps to reproduce

具体代码如下，使用的模块为 安信可 ESP-12H

### Code to reproduce this issue

```cpp
#include <string.h>
#include <sys/param.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "esp_system.h"
#include "esp_wifi.h"
#include "esp_event.h"
#include "esp_log.h"
#include "nvs_flash.h"
#include "esp_netif.h"
#include "protocol_examples_common.h"

#include "lwip/err.h"
#include "lwip/sockets.h"
#include "lwip/sys.h"
#include <lwip/netdb.h>

#define PORT CONFIG_EXAMPLE_PORT

static const char *TAG = "example";

static void wifi_rssi_task(void *pvParameters) 
{
    wifi_ap_record_t ap_info = {0};
    while (1) {
        esp_wifi_sta_get_ap_info(&ap_info);
       
        ESP_LOGI(TAG, "rssi = %d", ap_info.rssi);

        vTaskDelay(100 / portTICK_PERIOD_MS);
    }
}

static void udp_server_task(void *pvParameters)
{
    char rx_buffer[128];
    char addr_str[128];
    int addr_family = (int)pvParameters;
    int ip_protocol = 0;
    struct sockaddr_in6 dest_addr;

    while (1) {
            struct sockaddr_in *dest_addr_ip4 = (struct sockaddr_in *)&dest_addr;
            dest_addr_ip4->sin_addr.s_addr = htonl(INADDR_ANY);
            dest_addr_ip4->sin_family = AF_INET;
            dest_addr_ip4->sin_port = htons(PORT);
            ip_protocol = IPPROTO_IP;


        int sock = socket(addr_family, SOCK_DGRAM, ip_protocol);
        if (sock < 0) {
            ESP_LOGE(TAG, "Unable to create socket: errno %d", errno);
            break;
        }
        ESP_LOGI(TAG, "Socket created");

        int err = bind(sock, (struct sockaddr *)&dest_addr, sizeof(dest_addr));
        if (err < 0) {
            ESP_LOGE(TAG, "Socket unable to bind: errno %d", errno);
        }
        ESP_LOGI(TAG, "Socket bound, port %d", PORT);

        while (1) {
            struct sockaddr_storage source_addr; // Large enough for both IPv4 or IPv6
            socklen_t socklen = sizeof(source_addr);
            int len = recvfrom(sock, rx_buffer, sizeof(rx_buffer) - 1, 0, (struct sockaddr *)&source_addr, &socklen);

            // Error occurred during receiving
            if (len < 0) {
                ESP_LOGE(TAG, "recvfrom failed: errno %d", errno);
                break;
            }
            // Data received
            else {
                inet_ntoa_r(((struct sockaddr_in *)&source_addr)->sin_addr, addr_str, sizeof(addr_str) - 1);
                rx_buffer[len] = 0; // Null-terminate whatever we received and treat like a string...
                ESP_LOGI(TAG, "Received %d bytes from %s:", len, addr_str);
            }
        }

        if (sock != -1) {
            ESP_LOGE(TAG, "Shutting down socket and restarting...");
            shutdown(sock, 0);
            close(sock);
        }
    }
    vTaskDelete(NULL);
}

void app_main(void)
{
    ESP_ERROR_CHECK(nvs_flash_init());
    ESP_ERROR_CHECK(esp_netif_init());
    ESP_ERROR_CHECK(esp_event_loop_create_default());

    /* This helper function configures Wi-Fi or Ethernet, as selected in menuconfig.
     * Read "Establishing Wi-Fi or Ethernet Connection" section in
     * examples/protocols/README.md for more information about this function.
     */
    ESP_ERROR_CHECK(example_connect());

    xTaskCreate(udp_server_task, "udp_server", 4096, (void*)AF_INET, 5, NULL);
    xTaskCreate(wifi_rssi_task, "wifi_rssi_task", 4096, 0, 5, NULL);
}
```
## Debug Logs

```

```

**Comment by Alvin1Zhang** [comment]
@Vinx911 Thanks for reporting. Would you please help provide more details as suggested in the [issue template](https://github.com/espressif/esp-idf/issues/new?assignees=&labels=&template=bug_report.md&title=)? Information like elf, sdk configuration, backtrace, commit ID, hardware and etc. would help us debug further. Thanks.

**Comment by xueyunfei998** [comment]
hi @Vinx911 
Can you test the two tasks on different cores? I also try to reproduce the problem with your code。

**Comment by Vinx911** [comment]
> hi @Vinx911
> Can you test the two tasks on different cores? I also try to reproduce the problem with your code。

几个版本都进行了测试，都有这样的问题

**Comment by MaxwellAlan** [comment]
hi @Vinx911 ,  try turn off modem sleep and test.
call  esp_wifi_set_ps(WIFI_PS_NONE); after wifi start.
thanks.

**Comment by Vinx911** [comment]
非常感谢，问题已经解决

**Comment by Espressif-liuuuu** [comment]
hi @Vinx911 , The fix have been merge to master internally, https://github.com/espressif/esp-idf/commit/51f6091761be0c69b64d6310dcb72082dd5965d8 , which means you could keep PS_MIN_MODEM without issue. please check if you can find it on GitHub.
