### ISSUE TITLE
Secure boot and flash encryption complete process on fresh device for production. (IDFGH-5137)

### ISSUE THREAD

**Issue by PranavD10** [espressif/esp-idf#6917]
Hi,
How do I create the production grade device using flash encryption, secure boot, using host generated flash encryption key, secure boot signing key and secure bootloader digest. Also what are the efuse bits i need to burn and protect in order for UART access disable and bootloader locking.
Thanks

**Comment by Alvin1Zhang** [comment]
Thanks for reporting. Would you please help provide more details as suggested in the [issue template](https://github.com/espressif/esp-idf/issues/new?assignees=&labels=&template=bug_report.md&title=)? Information like elf, sdk configuration, backtrace, log outputs, commit ID, hardware and etc. would help us debug further. Thanks.

**Comment by PranavD10** [comment]
Hi,
I have resolved my queries about the process in other thread. Thanks to @projectgus .

**Comment by roysG** [comment]
can you share the link for the other thread? thanks

**Comment by PranavD10** [comment]
Here it is... [6916](https://github.com/espressif/esp-idf/issues/6916)
