### ISSUE TITLE
BT_BLE_42_FEATURES_SUPPORTED need IDF_TARGET_ESP32C3 || IDF_TARGET_ESP32S3 in 4.3 (IDFGH-5143)

### ISSUE THREAD

**Issue by GeneKong** [espressif/esp-idf#6921]
I think BLE 4.2 is support in all esp32 version, why in 4.3 version is depends on (IDF_TARGET_ESP32C3 || IDF_TARGET_ESP32S3))?
```
config BT_BLE_50_FEATURES_SUPPORTED
    bool "Enable BLE 5.0 features"
    depends on (BT_BLUEDROID_ENABLED && (IDF_TARGET_ESP32C3 || IDF_TARGET_ESP32S3))
    default y
    help
        This enables BLE 5.0 features, this option only support esp32c3/esp32s3 chip

config BT_BLE_42_FEATURES_SUPPORTED
    bool "Enable BLE 4.2 features"
    depends on (BT_BLUEDROID_ENABLED && (IDF_TARGET_ESP32C3 || IDF_TARGET_ESP32S3))
    default n
    help
        This enables BLE 4.2 features.
```

**Comment by Weijian-Espressif** [comment]
These two options were added for ESPC3 and ESPS3. ESP32 only supports 4.2, so 4.2 is enabled by default

**Comment by GeneKong** [comment]
> SP32 only supports 4.2, so 4.2 is enabled by de

No, this option is not enable, so some function is wrong.

**Comment by Weijian-Espressif** [comment]
ESP32 enable 4.2 features by default

**Comment by Weijian-Espressif** [comment]
If you get any error, please provide your log, thanks.

**Comment by GeneKong** [comment]
OK, I found this in espidf





So there have some other place to open this malloc?




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月22日(星期四) 中午11:51
收件人: ***@***.***&gt;; 
抄送: "Gene ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [espressif/esp-idf] BT_BLE_42_FEATURES_SUPPORTED need IDF_TARGET_ESP32C3 || IDF_TARGET_ESP32S3 in 4.3 (IDFGH-5143) (#6921)





 
ESP32 enable 4.2 features by default
 
&mdash;

**Comment by GeneKong** [comment]
OK, I found this in espidf

![image](https://user-images.githubusercontent.com/1146101/115653663-25b9fb00-a362-11eb-8c84-9e21c834c07b.png)

![image](https://user-images.githubusercontent.com/1146101/115653673-2a7eaf00-a362-11eb-86c1-31cbfe2fb5c9.png)

![image](https://user-images.githubusercontent.com/1146101/115653685-2eaacc80-a362-11eb-8b18-f30a4e6e7748.png)

So there have some other place to open this malloc?

**Comment by GeneKong** [comment]
> If you get any error, please provide your log, thanks.

Just some compile is error, no esp_ble_adv_params_t type found

**Comment by Weijian-Espressif** [comment]
please refer
` #if (UC_BT_BLE_42_FEATURES_SUPPORTED == TRUE || BLE_50_FEATURE_SUPPORT == FALSE)
#define BLE_42_FEATURE_SUPPORT   TRUE
#else
#define BLE_42_FEATURE_SUPPORT   FALSE
#endif`

**Comment by GeneKong** [comment]
OK, bad trace
