### ISSUE TITLE
PPP and WIFI AP MODE with NAT Enabled (IDFGH-5147)

### ISSUE THREAD

**Issue by JosueSanchezEZM** [espressif/esp-idf#6925]
Hi everybody I am trying to implement a code project using PPPoS example to get Internet access but at the same time create a local network using SoftAP example from esp-idf 4.2 version. I would like to know if you can provide to me an example with these considerations, or maybe some guidance to accomplish what I am looking for.
 
I would like to connect devices to the ESP AP Mode and forward the network traffic from that local network to the PPP interface using NAT.
 
I will appreciate all your help and advice you could provide to me.

**Comment by Zmmfly** [comment]
Hi,
You can refer https://github.com/jonask1337/esp-idf-nat-example
First to startup SoftAP, dont's forget set a DHCP dns server, second to startup pppos.
After pppos connected, use `ip_napt_enable` to enable NAT.

**Comment by JosueSanchezEZM** [comment]
Thanks @Zmmfly  for your suggestion. I already implemented an example code based on this project. I will be posting here the project.

**Comment by david-cermak** [comment]
@JosueSanchezEZM The pppos to AP example will be included in the [`esp_modem`](https://components.espressif.com/component/espressif/esp_modem) managed component, which is an external component, not part of IDF (but you can still download and use the component, it's very WIP, though)

Before it's available, you can try to
* check the example and maybe replace the PPP layer with pppos_client example from IDF
* look at the [ip_mesh](https://github.com/espressif/esp-idf/tree/master/examples/mesh/ip_internal_network) example which uses exactly the same NAPT configuration (you can choose some global DNS address, like `8.8.8.8` of the one retrieved from DHCP)
* take a look at this source (this comes from the modem component) and implement these functions:
[ap2pppos_example_main.c.txt](https://github.com/espressif/esp-idf/files/6429364/ap2pppos_example_main.c.txt)

```cpp
esp_err_t modem_init_network(esp_netif_t *netif);
void modem_start_network();
void modem_stop_network();
```

**Comment by JosueSanchezEZM** [comment]
Hi @david-cermak @Zmmfly  thanks for your comments. I actually have an example implemented using PPPoS example and SoftAP too. It works perfectly but when I try to implement this to my project (a custom project with more components and interfaces enabled) I am not having the same expected behavior. 

In the example code I did everything based on your suggestions and now works well, NAPT handles the internal traffic to reach the internet, but when adding this code to my main project, AP works well, PPP too, but NAPT not. I will share with you both code project (example and custom project) logs cases that I am getting. Maybe you can see what I am not seeing about the configuration of my main project (sdkconfig/menuconfig).


Attached you will find log files from the "working" example and the "not working" example (custom project).
Inside the "not working file" log there is a part that I think could the reason why NAPT is not working in my custom Project. This part is between lines  11 and 14 and referees to ACCM Dropping. I will appreciate any suggestion you could have to me to understand why this Dropping case is happening.
[not_working.txt](https://github.com/espressif/esp-idf/files/6454087/not_working.txt)
[working.txt](https://github.com/espressif/esp-idf/files/6454088/working.txt)

**Comment by david-cermak** [comment]
@JosueSanchezEZM The PPP to AP example is available in [`esp_modem`](https://components.espressif.com/component/espressif/esp_modem) component. Could you please check it and close this issue?

**Comment by Alvin1Zhang** [comment]
@JosueSanchezEZM Thanks fo reporting, will close due to short of feedback, feel free to reopen with more updates.
