### ISSUE TITLE
has example of http download files and store to spiffs ?? (IDFGH-5153)

### ISSUE THREAD

**Issue by zheyuejiang** [espressif/esp-idf#6931]
has example of http download files and store to spiffs. ??

**Comment by Alvin1Zhang** [comment]
@zheyuejiang Thanks for raising the feature request, would you please help provide more details as specified in the [feature request template](https://github.com/espressif/esp-idf/issues/new?assignees=&labels=Type%3A+Feature+Request&template=feature_request.md&title=), thanks.

**Comment by Alvin1Zhang** [comment]
@zheyuejiang Thanks for raising the feature request, would you please help provide more details as specified in the [feature request template](https://github.com/espressif/esp-idf/issues/new?assignees=&labels=Type%3A+Feature+Request&template=feature_request.md&title=), thanks.

**Comment by Alvin1Zhang** [comment]
Thanks for raising the feature request, this https://github.com/espressif/esp-idf/tree/master/examples/protocols/http_server/file_serving would help, feel free to reopen. Thanks.
