### ISSUE TITLE
Flashing PPPos(SIM800L) example and getting errors

### ISSUE THREAD

**Issue by Pabmoo** [espressif/esp-idf#6954]
## Environment

- Development Kit:      [ESP32-DevKitC]
- Module or chip used:  [ESP32-WROOM-32D]
- IDF version [4.2]
- Build System:         [Make]
- Operating System:     [macOS]
- Using an IDE?: [No]
- Power Supply:         [USB]

## Problem Description

I'm trying to run PPPos example but it keeps getting these errors as soon as esp32 starts.
The module SIM800L is blinking each 1s and I think the connections are good (Rx 26 ,Tx 25)

## Debug Logs
<img width="758" alt="Captura de pantalla 2021-04-28 a las 11 24 45" src="https://user-images.githubusercontent.com/63499673/116380535-57c0d680-a814-11eb-823a-37cdd04c4e3a.png">

**Comment by ESP-YJM** [comment]
@Pabmoo You can input command `AT+CIMI\r` to your SIM800L and check whether the response could receive. If could receive the response, you can enlarge the `MODEM_COMMAND_TIMEOUT_DEFAULT` 500 to 1000 or larger and try. If this not worked, you also can add cycle logic to get IMSI.
