### ISSUE TITLE
Handling  BTA_HH EVENT: VC_UNPLUG in components/esp_hid/src/bt_hidh.c (IDFGH-5182)

### ISSUE THREAD

**Issue by edwinclement08** [espressif/esp-idf#6956]
**Is your feature request related to a problem? Please describe.**

I was working with Xbox Controller. When I am connected to the controller, and 
I force a re-pairing from the controller side, the esp32 doesn't realise that 
it has disconnected beyond the above message.

BTA_HH EVENT: VC_UNPLUG 

**Describe the solution you'd like**

Handling and sending that event up to the user level so that it can be handled 
with esp_hidh_event_data_t callback

**Describe alternatives you've considered**

Not sure what else can be done to get this event.

**Comment by Wth-Esp** [comment]
Hi, @edwinclement08  

Could you please checkout to the 2078dfe or pull the latest master branch and see whether the issue still exists?
If yes, feel free to reopen this.

Thanks
