### ISSUE TITLE
Error: Invalid value for '[esp32|esp32s2]': invalid choice: esp32c3. (choose from esp32, esp32s2)  (IDFGH-5183)

### ISSUE THREAD

**Issue by liantianji** [espressif/esp-idf#6957]
I try to type idf.py set-target esp32c3 command.But has been a  error.
idf version:4.2
how to resolve？
Thanks.
log:

:\esp-idf\examples\get-started\hello_world>idf.py set-target esp32c3
Usage: idf.py set-target [OPTIONS] [esp32|esp32s2]
Try 'idf.py set-target --help' for help.

Error: Invalid value for '[esp32|esp32s2]': invalid choice: esp32c3. (choose from esp32, esp32s2)

**Comment by suda-morris** [comment]
ESP32-C3 is supported since release/v4.3
