### ISSUE TITLE
esp_netif_receive causes free total heap loss. (IDFGH-5186)

### ISSUE THREAD

**Issue by ToraNova** [espressif/esp-idf#6960]
## Environment

- Development Kit: Cucumber MI ESP32-S2
- Module or chip used: ESP32-S2 WROVER-I
- IDF version: v4.4-dev-1183-g9d34a1cd4
- Build System: idf.py
- Compiler version: xtensa-esp32-elf-gcc (crosstool-NG esp-2020r3) 8.4.0
- Operating System: Linux
- Using an IDE?: No
- Power Supply: USB

## Problem Description

I am trying to get USB-OTG working with the tinyusb library. I managed to get an interface running (I am able to ping through the usb host interface). I notice that each ping packet causes the total free heap to drop (using the xPortGetFreeHeapSize call). I believe its esp_netif_receive that is causing it.

### Expected Behavior

I expect the debugging console to output the same total free heap size (no leaks).

### Actual Behavior

The total free heap size decreases after every iteration. The MCU crashes when the heap size reaches ~(4000-5000).

### Steps to reproduce

1. clone this [repo](https://github.com/ToraNova/esp32s2-usb2pppos).
2. apply the [patch](esp-idf.patch) to allow esp-idf to work with tinyUSB network.
3. compile and run. plug in the usb-otg cable and you should see a RNDIS/ECM interface on your machine (i.e., by using ip a).
4. assign an ip address to that interface (ip a add 169.254.100.101/24 dev <interface>).
5. set the interface up (ip l set <interface> up).
6. try to ping 169.254.100.100 (the device's virtual ip). Open the debug channel and observe the heap size.

[hardware setup.](https://imgur.com/zzgjHNR)

### Code to reproduce this issue

I have the following loop running in my app_main, where tud_rx_buf is global static array filled by a callback, which then sets tud_rx_len to the size of the filled buffer. I based my code off the [network tests](https://github.com/espressif/esp-idf/tree/master/examples/system/network_tests) example.
```cpp
    tud_rx_buf[2048]
    size_t hs;
    while (1){
        if (tud_rx_len > 0){
            hs = MEMHEAP_CHECK();
            //we have smth to read
	    for(size_t i=0; i< tud_rx_len; i++){
	        tbuf[i] = tud_rx_buf[i];
	    }
            esp_netif_receive(netif, tbuf, tud_rx_len, NULL);
            tud_network_recv_renew();
            tud_rx_len = 0; //indicate buf is now read
	    ESP_LOGD(TAG_APP, "esp_netif_recv heap (%u).", hs);
        }else{
            vTaskDelay( 10 / portTICK_PERIOD_MS );
        }
        //sys_check_timeouts(); //TODO: is this important?
    }
```

The tud callback function called by tinyusb when a packet is received (refer to [example code](https://github.com/hathach/tinyusb/tree/master/examples/device/net_lwip_webserver) from tinyusb's repository).
```cpp
bool tud_network_recv_cb(const uint8_t *src, uint16_t size) {
    if (tud_rx_len < 1) {
	    for(size_t i=0; i<size;i++){
		    tud_rx_buf[i] = src[i];
	    }
	    //memcpy(tud_rx_buf, src, size);
	    tud_rx_len = size; //set tud_rx_len ONLY after finish copying
	    return true;
    }else{
	    //unable to receive, busy
	    ESP_LOGW(TAG_ETH, "network_recv_cb busy.");
	    return false;
    }
}
```

## Debug Logs
Heap size decreases over each ping echo.
```
D (378548) main: esp_netif_recv heap (220656).
D (379558) main: esp_netif_recv heap (219136).
D (380558) main: esp_netif_recv heap (217616).
D (381558) main: esp_netif_recv heap (216096).
D (382558) main: esp_netif_recv heap (214576).
D (382608) main: esp_netif_recv heap (213056).
D (383558) main: esp_netif_recv heap (211536).
D (384568) main: esp_netif_recv heap (210016).
D (385568) main: esp_netif_recv heap (208496).
```
crash logs
```
D (1290058) main: esp_netif_recv heap (9376).
D (1290058) main: esp_netif_recv heap (7856).
D (1290068) main: esp_netif_recv heap (6336).
D (1290088) main: esp_netif_recv heap (4816).
Guru Meditation Error: Core  0 panic'ed (LoadProhibited). Exception was unhandled.

Core  0 register dump:
PC      : 0x40086fd7  PS      : 0x00060b30  A0      : 0x80086ffc  A1      : 0x3ffc5680
A2      : 0x00000000  A3      : 0x3ffc7372  A4      : 0x00000036  A5      : 0x000000ff
A6      : 0x00000000  A7      : 0x00000000  A8      : 0x80086fd1  A9      : 0x3ffc5650
A10     : 0x00000000  A11     : 0x3ffc7372  A12     : 0x00000036  A13     : 0x00000000
A14     : 0x00000000  A15     : 0x00000000  SAR     : 0x0000001b  EXCCAUSE: 0x0000001c
EXCVADDR: 0x00000004  LBEG    : 0x00000036  LEND    : 0x00000000  LCOUNT  : 0x4002421d


Backtrace:0x40086fd4:0x3ffc56800x40086ff9:0x3ffc56a0 0x400aa215:0x3ffc56c0 0x4009d6f7:0x3ffc56e0 0x4009d161:0x3ffc5700 0x4009709e:0x3ffc5720 0x4009739a:0x3ffc5740 0x400982f5:0x3ffc5770 0x40098349:0x3ffc57b0 0x40098371:0x3ffc57e0 0x400932fd:0x3ffc5810 0x40093bff:0x3ffc5840 0x40092cdf:0x3ffc5870 0x4009801e:0x3ffc58a0 0x4009d0ba:0x3ffc58c0 0x4008d34d:0x3ffc58e0 0x4008d3cc:0x3ffc5900 0x400289ed:0x3ffc5930
```

**Comment by Alvin1Zhang** [comment]
@ToraNova Thanks for reporting, would you please help share if any updates for the issue? Thanks.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to short of feedback, feel free to reopen with more details.
