### ISSUE TITLE
 build tensorflow lite error (IDFGH-5189)

### ISSUE THREAD

**Issue by coffice12** [espressif/esp-idf#6963]
esp idf 4.2

python 4.3.9

build tensorflow lite     master git branch:
make -f tensorflow/lite/micro/tools/make/Makefile TARGET=esp generate_doorbell_camera_esp_project

erro:
make: *** No rule to make target 'generate_doorbell_camera_esp_project'

**Comment by negativekelvin** [comment]
https://github.com/tensorflow/tensorflow/pull/47063

**Comment by projectgus** [comment]
Hi @coffice12,

Thanks for letting us know about this failure. However, as noted by @negativekelvin this error is coming from the Tensorflow build system so the fix will need to be applied on the Tensorflow side.
