### ISSUE TITLE
sdmmc_card_init failed in SPI Mode 33% of time ! (IDFGH-5193)

### ISSUE THREAD

**Issue by ghost** [espressif/esp-idf#6966]
## Environment

- Module or chip used:  ESP32-WROOM
- IDF version: v4.2-351-gce2c615bb
- Build System:        idf.py
- Compiler version: 8.4.0
- Operating System:     macOS
- Power Supply:        external 3.3V

## Problem Description

We've IOT Devices where SD Card is used to backup the data. In 33% of time, SD Card fails to initialize.

Below is the code - 

```C
        sdmmc_host_t sdcard_host = SDSPI_HOST_DEFAULT();

	sdcard_host.slot = VSPI_HOST;
	sdcard_host.max_freq_khz = SDMMC_FREQ_PROBING;
	sdcard_host.command_timeout_ms = 10;

	spi_bus_config_t bus_cfg = {
            .mosi_io_num = PIN_NUM_MOSI,
            .miso_io_num = PIN_NUM_MISO,
            .sclk_io_num = PIN_NUM_CLK,
            .quadwp_io_num = -1,
            .quadhd_io_num = -1,
            .max_transfer_sz = 5000,
        };

	ret = spi_bus_initialize(sdcard_host.slot, &bus_cfg, 1);
	if (ret != ESP_OK) {
		ESP_LOGE(TAG, "Failed to initialize bus.");
		// return 1;
	}


	sdspi_device_config_t sdspi_dev_config = SDSPI_DEVICE_CONFIG_DEFAULT();
        sdspi_dev_config.gpio_cs = PIN_NUM_CS;

	sdspi_host_init();
	sdspi_host_init_device(&sdspi_dev_config, &sdspi_handle);

	ret = sdmmc_card_init(&sdcard_host, &sd_card);
```

### Expected Behavior

SD Card should work without any problems.

### Actual Behavior

sdmmc_card_init fails to intialize SD Card

**Comment by AxelLin** [comment]
Could you set CONFIG_LOG_DEFAULT_LEVEL_VERBOSE=y and report the whole error log?

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, feel free to reopen.
