### ISSUE TITLE
[TW#13326] SSL_use_certificate and SSL_use_PrivateKey not in openssl/ssl.h

### ISSUE THREAD

**Issue by kevinkessler** [espressif/esp-idf#697]
In order to use client certs with openssl, you needs these two functions, but they are not in openssl/ssl.h.  The SSL_CTX version of these calls are in ssl.h, but I have no idea what you would use them for.

The work around is to simply add
int SSL_use_PrivateKey(SSL *ssl, EVP_PKEY *pkey);
int SSL_use_certificate(SSL *ssl, X509 *x);
 to you code, and you can use these functions.

**Comment by donghengqaz** [comment]
You may can user following API instead of those with transforming data to specific data object:
int SSL_use_PrivateKey_ASN1(int type, SSL *ssl, const unsigned char *d, long len);
int SSL_use_certificate_ASN1(SSL *ssl, int len, const unsigned char *d);

**Comment by FayeY** [comment]
Hi @kevinkessler , did the above suggestion help you resolve the issue?
