### ISSUE TITLE
[TW#13328] The https_request example crashes randomly

### ISSUE THREAD

**Issue by mgleason** [espressif/esp-idf#698]
**Observed behavior**

Running the "esp-idf/examples/protocols/https_request" example (on a ESP-DEV ESP-WROOM-32) plugged into a USB port on my computer. The https_request example basically makes a request via SSL to a web site, waits 10 seconds and repeats.

It seems to run fine for a while, then it panics and reboots the ESP32. It may successfully complete the connect/wait-10-secs cycle 3 times before panic'ing and rebooting - or it might go 20 or 30 cycles.

**Steps to reproduce**

Configure and run the "esp-idf/examples/protocols/https_request" example for a while (an hour?)  It may be quicker to reproduce the issue if you decrease the vTaskDelay from 1000 to 100.  

This [post](https://www.esp32.com/viewtopic.php?f=2&t=2114) describes more of the background.

After 674 completed cycles, counted the following # of crashes and types:

**(#)....Type of crash**
(24)...Guru Meditation Error: Core 0 panic'ed (Interrupt wdt timeout on CPU1)
(24)...Guru Meditation Error: Core 0 panic'ed (Interrupt wdt timeout on CPU0)
(1)......Guru Meditation Error of type LoadProhibited occurred on core 0
(2).....rst:0x8 ( TG1WDT_SYS_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)

**Comment by projectgus** [comment]
Hi @mgleason ,

Sorry noone ever got back to you about this bug report.

It looks like you followed up in #630 and it seems like you worked around the issue there by disabling hardware acceleration. There were some issues with hardware acceleration that have been fixed very recently, code should appear on github in the next few days. I'm going to close this issue in favour of #630, though - please continue watching that issue for updates.
