### ISSUE TITLE
openthread/ot_cli example: support openthread border router  (IDFGH-5208)

### ISSUE THREAD

**Issue by sihan6** [espressif/esp-idf#6981]
do you have any furture plans to add the support for Openthread border router ?

**Comment by chshu** [comment]
Yes, the border router example is under progress, please stay tuned.

**Comment by cahty82008** [comment]
Hi, do you have a time plan for the border router , or a BETA version for the developers to do some tests and developments ?

**Comment by cahty82008** [comment]
thanks for the information, that's perfect

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, feel free to reopen.
