### ISSUE TITLE
Add possibility to adjust HTTP Request timeout without re-creating the HTTP client instance (IDFGH-5211)

### ISSUE THREAD

**Issue by zinke-ct-video** [espressif/esp-idf#6984]
I have an HTTP Client with a definite timeout:
```cpp
esp_http_client_config_t config = {
	.timeout_ms = 3000
};
hHTTPClient = esp_http_client_init(&config);
```
This client is used for multiple requests so that the same connection is reused for speed reasons.

In my use case there are requests which get answered very quickly and some requests which get answered very slowly. That's why I would like to adjust the request timeout for every single request without being forced to re-create the HTTP client with a call to esp_http_client_init.

I suggest creation of the following function in the components/esp_http_client/esp_http_client.c file:

```cpp
esp_err_t esp_http_client_set_timeout(esp_http_client_handle_t client, uint32_t timeout_ms)
{
    client->timeout_ms = timeout_ms;
    return ESP_OK;
}
```

This change would take just a few minutes and would be very helpful.
Best regards!

**Comment by ESP-YJM** [comment]
@zinke-ct-video Thanks for your suggestion. We will implement it.
