### ISSUE TITLE
[TW#13331] ledc.c:ledc_set_fade_with_time -> IntegerDivideByZero Exception with fade time=0

### ISSUE THREAD

**Issue by benjaminaigner** [espressif/esp-idf#699]
If this method is called with a fade time = 0, a IntegerDivideByZero exception occurs.

There should be an additional parameter check for the fade time.

Problem occurs at line 523:
```
scale = (duty_delta + total_cycles - 1) / total_cycles;
```
The value for total_cycles is calculated at line 516:
```
int total_cycles = max_fade_time_ms * freq / 1000;
```

**Comment by FayeY** [comment]
This issue should have been solved on the latest IDF, if it is not, please feel free to reopen it.
