### ISSUE TITLE
Audio samples droped in HFP (CVSD codec, VHCI)  (IDFGH-5224)

### ISSUE THREAD

**Issue by RyanYaoHZ** [espressif/esp-idf#6996]
INSTRUCTIONS
============
We found strange phenomena when using HFP( cvsd codec,vhci)，it is simular to issue IDFGH-731 #3171

![image](https://user-images.githubusercontent.com/26036597/117412940-f4d3eb80-af47-11eb-8d53-d045552c0705.png)

## Environment

- Development Kit:      ESP32-LyraT4.3
- Kit version 
- Module or chip used:  [ESP32-WROVER]
- IDF version 4.2 and 4.2.1

## Problem Description

Run hfp_client example in ESP32-LyraT4.3 and record the voice in handset. The recoded waveform lost 60sample every few seconds.

**Comment by RyanYaoHZ** [comment]
We can see the issue in both directions. It happens more frequently in HFP client incoming side

**Comment by xiongweichao** [comment]
Hi, @RyanYaoHZ 

Could you please provide the log?

Thanks.

**Comment by RyanYaoHZ** [comment]
@xiongweichao 

Add "pkt_status" in btm_route_sco_data:

BTM_TRACE_WARNING("SCO: hdl %x, len %d, pkt_sz %d, pkt_status %d\n", handle, p_msg->len, pkt_size, pkt_status);

log attathed. some packets are in status(2) or status(1). 
.
(25021) BT_BTM: SCO: hdl 180, len 16379, pkt_sz 120, pkt_status 1
.
.
(25511) BT_BTM: SCO: hdl 180, len 16379, pkt_sz 120, pkt_status 2

The explanation in Bluetooth spec " No data received. All data from the baseband received during the (e)SCO interval(s) corresponding to the HCI Synchronous Data packet have beenmarked as "lost data" by the baseband. The Payload data octets shall be set to 0."

Update:  A bug found in our project. The outgoing (hf client --> phone) has no such phenomena. This issue exist only in incoming (phone----> hf client)  direction.
[Receive_20210513130401.zip](https://github.com/espressif/esp-idf/files/6471599/Receive_20210513130401.zip)

**Comment by RyanYaoHZ** [comment]
sdkconfig attached
[sdkconfig.zip](https://github.com/espressif/esp-idf/files/6471652/sdkconfig.zip)

**Comment by xiongweichao** [comment]
Hi, @RyanYaoHZ 

Due to clock drift, the clocks of master and slave are inconsistent, resulting in the phenomenon that the data packet is not received.It's a compatibility issue.

Thanks

**Comment by Wth-Esp** [comment]
Hi, @RyanYaoHZ 

We have provided an fix in https://github.com/espressif/esp-idf/issues/3171 and seems that customer feels good with that fix.
Could you please update your IDF and try that commit?

Thanks

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to short of feedback, feel free to reopen with more updates.
