### ISSUE TITLE
Does ESP32-C3 support stereo PDM microphone input?  (IDFGH-5231)

### ISSUE THREAD

**Issue by eyewy** [espressif/esp-idf#7003]
**Is your feature request related to a problem? Please describe.**

The ESP32-C3 documentation mentions support for PDM TX, but I was not able to infer support for PDM RX. I want to use 2 PDM microphones as stereo input to ESP32-C3, please clarify if this is supported.

**Describe the solution you'd like**

ESP32-IDF example do not include PDM RX example. I would appreciate if you prove an example with ESP32-C3 I2S pin names, as they seem to defer from ESP32.

**Describe alternatives you've considered**

Please give as many details as you can. Include suggestions for useful APIs or interfaces if relevant.

**Additional context**

**Comment by L-KAYA** [comment]
Sorry for the late response. And we are sorry to tell that ESP32-C3 does not support PDM TX mode.
As for the PDM RX example, you can refer to [i2s_audio_recorder_sdcard](https://github.com/espressif/esp-idf/tree/master/examples/peripherals/i2s/i2s_audio_recorder_sdcard) example.

Thank you for your support!
