### ISSUE TITLE
Esp idf issue Importing an existing projects other than examples in eclipse (IDFGH-5248)

### ISSUE THREAD

**Issue by naveedabbasi** [espressif/esp-idf#7017]
I am facing an issue while Importing an existing project other than examples in eclipse Esp idf 2.6 and also in eclipse Esp idf 2.8. both versions run examples and build with no errors,
but whenever I add new > header and C files in the existing example project it is unable to add and find header and C files in the project, I also put these files in the main folder too.
after searching on forums :
I also tried to add these files CMakeLists.txt but the problem not solved.

2nd: whenever I existing project other than examples , all files [.C files and .H files ] are added but this time
eclipse will unable to add these fils in the project ,
#include <stdio.h>
#include "sdkconfig.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "esp_system.h"
#include "esp_spi_flash.h"

and also

c:/users/fuuast/.espressif/tools/xtensa-esp32-elf/esp-2020r3-8.4.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: esp-idf/esp32/libesp32.a(cpu_start.c.obj):(.literal.main_task+0x18): undefined reference to app_main' c:/users/fuuast/.espressif/tools/xtensa-esp32-elf/esp-2020r3-8.4.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: esp-idf/esp32/libesp32.a(cpu_start.c.obj): in function main_task':
C:/Users/FUUAST/Desktop/esp-idf/components/esp32/cpu_start.c:592: undefined reference to `app_main'

is any way I can import my existing projects without facing the problems. I only want to use eclipse right now.

**Comment by projectgus** [comment]
Hi @naveedabbasi,

I noticed you've also opened a Pull Request with this content (#7016) and also via the Eclipse plugin project
https://github.com/espressif/idf-eclipse-plugin/issues/267

As this issue seems to be related to the Eclipse plugin then I suggest we close this duplicates. My colleague should reply to the issue in the Eclipse project, soon.
