### ISSUE TITLE
tjpgd library does not exist in ESP32-S2 ROM. (IDFGH-5263)

### ISSUE THREAD

**Issue by nopnop2002** [espressif/esp-idf#7029]
**Is your feature request related to a problem? Please describe.**

tjpgd library does not exist in ESP32-S2 ROM.

**Describe the solution you'd like**

I want you to include the tjpgd library in the ESP32-S2 ROM.

The tjpeg library needs a lot of memory, but it may work if it is a small image.

**Describe alternatives you've considered**

None.

**Additional context**

I don't have an ESP32-S3 yet, but it may have the same problem.

https://github.com/espressif/esp-idf/issues/5434

**Comment by igrr** [comment]
Hi @nopnop2002, what issues are you facing when linking tjpgd library into your application? If you observe some performance issues when tjpgd is placed into Flash, you can selectively move some of the functions to IRAM to improve performance, using [linker script fragments](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/linker-script-generation.html).
If that still doesn't work, please explain the problem you are facing.

Here is an example of tjpgd being included into the application code for the ESP32-S2, in the esp32-camera project:

https://github.com/espressif/esp32-camera/blob/901c05b431ea615b11fbc65b39a2ed286abe8df8/CMakeLists.txt#L39-L45
https://github.com/espressif/esp32-camera/blob/901c05b431ea615b11fbc65b39a2ed286abe8df8/target/esp32s2/private_include/tjpgd.h
https://github.com/espressif/esp32-camera/blob/901c05b431ea615b11fbc65b39a2ed286abe8df8/target/esp32s2/tjpgd.c

**Comment by nopnop2002** [comment]
@igrr 

Thank you for response.

The reason why this library is not available by default in ESP32S2 (tjpgd must be included into the application code) is strange.

**Comment by negativekelvin** [comment]
>I want you to include the tjpgd library in the ESP32-S2 ROM.

It's not possible to change the ROM.  S2 has a small ROM capacity.  C3 and S3 have those functions in ROM.

**Comment by nopnop2002** [comment]
>It's not possible to change the ROM. S2 has a small ROM capacity. C3 and S3 have those functions in ROM.

OK.
I understood.

**Comment by nopnop2002** [comment]
In ESP-IDF Ver4.4, esp32s2 does not include tjpeg component.

This is due to the small ROM size of esp32s2.

In ESP-IDF Ver5.0, the tjpeg component has been moved to the IDF Component Registry.

Still can't we use the tjpeg component with esp32s2?

**Comment by nopnop2002** [comment]
I found that tjpeg can be used with ESP-IDF Ver5 + esp32s2
