### ISSUE TITLE
No messages shown by any node (IDFGH-5273)

### ISSUE THREAD

**Issue by L30n4rd0-code** [espressif/esp-idf#7038]
I have been testing this example for a couple of weeks, my nodes connect correctly and create an organized network with the root node and four child nodes but there are no messages shown in the serial monitor, whether of a root node or a child node. If I correctly understand, the root node sends messages to all the child nodes, so is in the child node's serial monitor that I should see such messages. How could I manage to have those messages shown in the serial monitor? Any ideas about it?

**Comment by Alvin1Zhang** [comment]
@L30n4rd0-code Thanks for reporting, which example you refer to? Thanks.

**Comment by L30n4rd0-code** [comment]
I'm refering to the _Internal_communication_ example.

**Comment by shenjun7** [comment]
The bug has been fixed in gitlab and is waiting to be synchronized to github.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, and sorry for slow turnaround, fix is available at https://github.com/espressif/esp-idf/commit/d93849baf86b6de5f08a03ae6aa7006dac58a93b, feel free to reopen.
