### ISSUE TITLE
Get Common Name from a certificate loaded in ESP32 automatically. (IDFGH-5312)

### ISSUE THREAD

**Issue by nexstem-siddhant** [espressif/esp-idf#7070]
Is there a method via which I can extract the CN from the certificate in esp directly, instead of manually passing it. Every single device that I have needs to have a separate device certificate and the device name on Azure IOT hub is derived from the common name of the certificate in the device. It is becoming very tedious now, since I have to keep track of more than 50 certificates and their common names, and have to manually change it the firmware before flashing the program onto esp.

A alternative that I am currently exploring is that i create a NVS partition which contains the common name. I can then use the mass_mfg tool to create different nvs partition files for each device using the csv, which is automatically generated by a python script which loops through all the certificates and gets their common name and stores it in the csv.

**Comment by negativekelvin** [comment]
Mbedtls has x509 certificate parsing functions

**Comment by mahavirj** [comment]
@nexstem-siddhant 

> Is there a method via which I can extract the CN from the certificate

Please see following pointer that may help:

https://github.com/espressif/esp-idf/blob/c13afea635adec735435961270d0894ff46eef85/components/coap/port/coap_mbedtls.c#L301


>  I can then use the mass_mfg tool to create different nvs partition files for each device using the csv

This sounds all good and something that we would also recommend.

**Comment by mahavirj** [comment]
Hopefully that answers your question. Please feel free to re-open if you need additional information or raise a topic on esp32.com forum
