### ISSUE TITLE
ESP32可以实现两个SSID/Password, 使用起来如同两个AP吗？ (IDFGH-5317)

### ISSUE THREAD

**Issue by henryv5mesh** [espressif/esp-idf#7074]
**Is your feature request related to a problem? Please describe.**

客户有一个需求，需要两个AP, 两个AP分别连接不同类型IOT设备。

**Describe the solution you'd like**

AP启动后，可以提供两个热点，供其他不同类IOT设备连接

**Describe alternatives you've considered**

可以用软件虚拟2个AP方法来实现吗?

**Additional context**

![image](https://user-images.githubusercontent.com/84823297/119593035-1b30cc80-be0c-11eb-8c41-a2c258243b8d.png)

**Comment by MaxwellAlan** [comment]
@henryv5mesh thanks for your suggestion.
Since ESP32's hardware resource limit, we can not support this feature.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting.
