### ISSUE TITLE
SNI (IDFGH-5321)

### ISSUE THREAD

**Issue by Anouer-Kebir** [espressif/esp-idf#7077]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

Please give as many details as you can. Include suggestions for useful APIs or interfaces if relevant.

**Additional context**

**Comment by Alvin1Zhang** [comment]
@Anouer-Kebir Thanks for raising this feature request, would you please help share more details as described in the [template](https://github.com/espressif/esp-idf/issues/new?assignees=&labels=Type%3A+Feature+Request&template=feature_request.md&title=)? Thanks.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to short of details, feel free to reopen with more details, thanks.
