### ISSUE TITLE
Can remove the rate limitation of esp_wifi_80211_tx in more cases? (IDFGH-5322)

### ISSUE THREAD

**Issue by Ncerzzk** [espressif/esp-idf#7078]
I want to use esp32 in fast image transmission，just like[ Ez-wifibroadcast ](https://github.com/rodizio1/EZ-WifiBroadcast)  ，  
 which use the inject and monitor mode of wifi card.

In esp32, it's ok to run in monitor mode as the receiver. While as a sender, the API guide shows that there would be a rate limitation in 1Mb/s when there is no wifi connection using the func esp_wifi_80211_tx .

Of course, I know that there should be some ways to prevent user doing something unsafe, while if it's possible to remove the limitation in more case? like when I send info to a fixed MAC ID etc.

Thanks, if some other ideas, please comment

**Comment by negativekelvin** [comment]
https://github.com/espressif/esp-idf/issues/6883#issuecomment-826530322
