### ISSUE TITLE
Docker image for v3.3.5 is missing (IDFGH-5340)

### ISSUE THREAD

**Issue by lukecyca** [espressif/esp-idf#7092]
The docker image for release v3.3.5 is missing from https://hub.docker.com/r/espressif/idf/tags

The previous v3.3.x tags are all there, but not v3.3.5.

As a workaround I was following release-3.3 branch, but it may receive new changes anytime and is not the same as v3.3.5.

**Comment by igrr** [comment]
Sorry for the issue, the image should be available now:
https://hub.docker.com/layers/espressif/idf/v3.3.5/images/sha256-1389138f34a8db4e44e88d425921db64d7b8507c3185ef0ae70038a8cbde5195?context=explore
