### ISSUE TITLE
http server url is not resolved (IDFGH-5347)

### ISSUE THREAD

**Issue by zoro9091** [espressif/esp-idf#7099]
Hello,

I have ESP32 working in WIFI AP-STA mode and has a web server.

When I try to connect to AP and request the URL in my laptop browser I can't see any output. "site is unreachable" and no monitor debugging messages.
I assign the URL to httpd_uri_t .uri structure member as a string and I am being very careful to type exactly the same URL in browser. for example I use this string "http://example.com" in browser and code

The only working case is when I use URL in the code as "/test.html" and I type in browser ESP32 AP IP which seems to corresponds to root "/" followed by the remaining path like this "192.168.4.1/test.html"

Do I  need to activate  anything  explicitly  like  mdns to  resolve the website URL?

**Comment by negativekelvin** [comment]
Suggest you research captive portal which will redirect all domains to esp32 ip address.
