### ISSUE TITLE
ESP-IDF 4.X on arduino platform breaks ETH PHY support (IDFGH-5356)

### ISSUE THREAD

**Issue by Simonefardella** [espressif/esp-idf#7107]
Hi guys, as i've reported in the esp32-arduino repo, starting from the IDF 4.x version, there are in place a lot of changes that breaks Ethernet on most of third party boards (Like Olimex, etc...).

For example, the driver initialization doesn't have the CLK GPIO option selectable and nowhere is documented that.

This represent for the overall esp32-arduino users a big problem to face...: here there are all details, scope traces and informations: [ISSUE HERE](https://github.com/espressif/arduino-esp32/issues/5239)

**Comment by negativekelvin** [comment]
It's a compile time option so when libraries are precompiled for Arduino the choice is locked.  I think it could be made configurable at runtime, there's not really any penalty. This could also benefit micropython and other platforms that need to support multiple hardware configurations.  What do you think @suda-morris ?

https://github.com/espressif/esp-idf/blob/1f54d17503ff17d830de75eed4eb47bc6a3aafc3/components/hal/esp32/emac_hal.c#L84-L130

**Comment by atanisoft** [comment]
@negativekelvin in IDF v3.x it was runtime configurable.

**Comment by suda-morris** [comment]
Thanks for reporting, IDF will add that runtime "mac clock config" option back soon.

**Comment by Simonefardella** [comment]
Thanks @suda-morris, we are waiting for that! :)

**Comment by Simonefardella** [comment]
@suda-morris, any news about this issue?

**Comment by kostaond** [comment]
@Simonefardella It's going to be worked very soon. There is EMAC HAL code refactor update pending to be merged which needs to be finished first. It's been already review so we could start "mac clock config" soon. Thank you for your patience.

**Comment by kostaond** [comment]
@Simonefardella just FYI, the update is in review.
