### ISSUE TITLE
ESP_PROV: Crashing when trying to set --custom_data field (IDFGH-5369)

### ISSUE THREAD

**Issue by carlessole** [espressif/esp-idf#7118]
Hi,
I'm running the stable version of ESP-IDF, [v4.2.1](https://github.com/espressif/esp-idf/tree/v4.2.1).
I'm trying the [wifi_prov_mgr example](https://github.com/espressif/esp-idf/tree/v4.2.1/examples/provisioning/wifi_prov_mgr) and testing it against the [python script](https://github.com/espressif/esp-idf/tree/v4.2.1/tools/esp_prov)

If I try to send --custom_data as the readme.md explains:

> Sending Custom Data
> 
> The provisioning manager allows applications to send some custom data during provisioning, which may be required for some other operations like connecting to some cloud service. This is achieved by creating and registering additional endpoints using the below APIs
> 
```
> wifi_prov_mgr_endpoint_create();
> wifi_prov_mgr_endpoint_register();
```
> 
> In this particular example, we have added an endpoint named "custom-data" which can be tested by passing the --custom_data <MyCustomData> option to the esp_prov tool. Following output is expected on success:
> 
```
> ==== Sending Custom data to esp32 ====
> CustomData response: SUCCESS
```

I get this error:

```
~/esp/esp-idf/tools/esp_prov$ python esp_prov.py --transport softap --sec_ver 1 --pop abcd1234 --custom_data "myData"
Connecting to 192.168.4.1:80

==== Starting Session ====
==== Session Established ====

==== Sending Custom data to esp32 ====
Traceback (most recent call last):
  File "esp_prov.py", line 440, in <module>
    if not custom_data(obj_transport, obj_security, args.custom_data):
  File "esp_prov.py", line 191, in custom_data
    message = prov.custom_data_request(sec, custom_data)
  File "/home/intesis/esp/esp-idf/tools/esp_prov/prov/custom_prov.py", line 51, in custom_data_request
    enc_cmd = security_ctx.encrypt_data(data)
  File "/home/intesis/esp/esp-idf/tools/esp_prov/security/security1.py", line 170, in encrypt_data
    return self.cipher.update(data)
  File "/usr/lib/python3/dist-packages/cryptography/hazmat/primitives/ciphers/base.py", line 149, in update
    return self._ctx.update(data)
  File "/usr/lib/python3/dist-packages/cryptography/hazmat/backends/openssl/ciphers.py", line 124, in update
    n = self.update_into(data, buf)
  File "/usr/lib/python3/dist-packages/cryptography/hazmat/backends/openssl/ciphers.py", line 140, in update_into
    self._backend._ffi.from_buffer(data), len(data)
TypeError: from_buffer() cannot return the address of a unicode object
```

Why that is happening? How I can send custom fields using this example?

I also see that in the "esp_prov" [readme](https://github.com/espressif/esp-idf/tree/v4.2.1/tools/esp_prov), **custom_data** field is not documented but "custom_config" is used instead.

Thanks

**Comment by alexhenrie** [comment]
I am having the exact same problem.

**Comment by alexhenrie** [comment]
It looks like this bug has already been fixed. After installing the latest version of ESP-IDF from Git, I had no problems with the `--custom_data` parameter.

**Comment by ESP-YJM** [comment]
@carlessole It seems the latest version of ESP-IDF has fixed the problem. Can this issue be closed?

**Comment by Alvin1Zhang** [comment]
@carlessole Thanks for reporting. Would you please help share if any updates or details for this issue? Thanks.

**Comment by carlessole** [comment]
> 
> 
> @carlessole Thanks for reporting. Would you please help share if any updates or details for this issue? Thanks.

Sorry but I was not able to test it yet.
During this week I will try to test it and I will report my results.
Thanks

**Comment by Alvin1Zhang** [comment]
@carlessole Thanks for reporting, would you please help share if any updates for the issue? Thanks.

**Comment by Alvin1Zhang** [comment]
@carlessole Thanks for reporting, would you please help share if any updates for the issue? Thanks.

**Comment by carlessole** [comment]
@Alvin1Zhang  first of all sorry for the delay in my answer.

And thanks! Using the last ESP-IDF stable version ([4.3](https://github.com/espressif/esp-idf/tree/v4.3)) everything is working fine:

```
C:\esp\esp-idf\tools\esp_prov>python esp_prov.py --transport softap --sec_ver 1 --pop abcd1234 --custom_data "myData"
Connecting to 192.168.4.1:80

==== Starting Session ====
==== Session Established ====

==== Sending Custom data to esp32 ====
CustomData response: b'SUCCESS\x00'
==== Custom data sent successfully ====

==== Scanning Wi-Fi APs ====
++++ Scan process executed in 2.68904709815979 sec
++++ Scan results : 10

++++ Scan finished in 2.824215888977051 sec
==== Wi-Fi Scan results ====
S.N. SSID                              BSSID         CHN RSSI AUTH
[ 1] Iguana.cat-E96E79                 501d93e96e80   11 -36  WPA_WPA2_PSK
[ 2] MOVISTAR_19B2                     e4ab891e19b3    6 -48  WPA2_PSK
[ 3] Iguana.cat-7D00C0                 38eb477d00c8    3 -70  WPA_WPA2_PSK
[ 4] MiFibra-939E                      e051639393a0    1 -88  WPA2_PSK
[ 5] MOVISTAR_8AB4                     c6d4a1138583   11 -89  WPA2_PSK
[ 6] MOVISTAR_8581                     ccd4a1138583   11 -90  WPA2_PSK
[ 7] Iguana.cat-7D00C0_EXT             3c846a2827de    3 -91  WPA_WPA2_PSK
[ 8] DIGIFIBRA-UcpC                    90fd73c43537    1 -91  WPA_WPA2_PSK
[ 9] MiFibra-ED21                      0c8e292bed23    1 -92  WPA2_PSK
[10] devolo-782                        b8bef4577548   11 -94  WPA2_PSK
Select AP by number (0 to rescan) :
```

**Comment by Alvin1Zhang** [comment]
@carlessole Thanks for sharing the updates, and glad to hear everything is working fine, feel free to reopen.
