### ISSUE TITLE
Wifi station/access point example (IDFGH-5374)

### ISSUE THREAD

**Issue by Benedito821** [espressif/esp-idf#7123]
Hello! Is there an example that shows how to configure **wifi in station/access point mode** **with a simple web server**? I runned the **station** example and after this I can'topen the web server by the IP adress.

**Comment by MaxwellAlan** [comment]
hi @Benedito821, You can try example/protocols/http_server/simple example and set in menuconfig using WiFi connection.

**Comment by Benedito821** [comment]
thank you for the tip
I'll check that @MaxwellAlan

**Comment by Benedito821** [comment]
could I use also this example to control my board with some commands(e.g, leds,peripherals,...)?

**Comment by MaxwellAlan** [comment]
hi @Benedito821 yes, you can, but you need to add some more code for your commands, may be you can also refer to other esp-idf/examples.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting and sharing updates, feel free to reopen.
