### ISSUE TITLE
[Doc][Low-Power] Is there a document to detail the comparison and usage of different low power solutions (IDFGH-5384)

### ISSUE THREAD

**Issue by ustccw** [espressif/esp-idf#7132]
As we can see here: https://www.espressif.com/sites/default/files/documentation/9b-esp8266-low_power_solutions__en.pdf

ESP8266 has a good document, which introduces different low-power solutions, and their corresponding power consumption data, different points, application scenarios and usage, and so on.

So here, I wonder if ESP32 or ESP32-C3 can have the same great document to describe different low-power solutions.

Although I have also read some documents about low power consumption, such as:
- https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/power_management.html
- https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/sleep_modes.html
- https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/deep-sleep-stub.html
- ESP32 Datasheet
- ESP32 Technical Reference Manual

But i am always confused by them. For examples:
- what is the light-sleep difference between config by `esp_pm_configure()` and `esp_light_sleep_start()`
- which low-power solution can keep Wi-Fi connections, or all of them can make it
- what is the reference current value of different low power solution
- ...

BRs,
CW

**Comment by MaxwellAlan** [comment]
Hi @ustccw 

Sorry for reply late, IDF docs have already included a power save related docs, please refer to https://docs.espressif.com/projects/esp-idf/zh_CN/latest/esp32/api-guides/wifi.html#id74
