### ISSUE TITLE
installation esp-idf on vs code (IDFGH-5394)

### ISSUE THREAD

**Issue by isakovM** [espressif/esp-idf#7140]
hello dear supporter. i am trying to install esp-idf on vs code. but at the end of the installation some problems are appearing. please have a look at this picture
![idf vscode error](https://user-images.githubusercontent.com/85765819/121745666-85f33080-cab9-11eb-9546-cafbdaee4f59.PNG)

**Comment by dobairoland** [comment]
Hi @isakovM. Thank you for your report. We will fix this. Until then you can avoid this issue by installing `git` and making sure it is available everywhere (not just from git bash). Git can be installed with the [Windows Tool Installer](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/get-started/windows-setup.html#esp-idf-tools-installer) or from https://git-scm.com.

**Comment by brianignacio5** [comment]
Can you try this [vsix installer](https://nightly.link/espressif/vscode-esp-idf-extension/actions/artifacts/69521854.zip)?

[Installing extension from vsix in Visual Studio Code](https://code.visualstudio.com/docs/editor/extension-marketplace#_install-from-a-vsix)

**Comment by isakovM** [comment]
definitely. i will try
