### ISSUE TITLE
Play position changed event declared in a2dp_sink example but no show (IDFGH-5403)

### ISSUE THREAD

**Issue by algavrik** [espressif/esp-idf#7149]
Hello team,
"Play position changed" event declared in a2dp_sink example but no show in a console. Source is iphone xr.
IDF ver 4.2

**Comment by xiongweichao** [comment]
Hi, @algavrik 

I have tested with iPhone Xs. If you want to use this feature, the remote AVRC target （iPhone Xs）should support this bitmask in it's feature list. But from the log, iPhone Xs not support this bit. Please verify whether iPhone XR support this bit.

Thanks

**Comment by Alvin1Zhang** [comment]
@algavrik Thanks for reporting, would you please help share if any updates? Thanks.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to short of feedback, feel free to reopen.
