### ISSUE TITLE
Reboot the  esp32 !

### ISSUE THREAD

**Issue by FFtust** [espressif/esp-idf#715]
HI!
     I want to make a soft reset, does ESP-IDF provide users with such an API? Or is there any solution to make  a soft reset ?

**Comment by igrr** [comment]
Yes, it's called `esp_restart`:
[examples/get-started/hello_world/main/hello_world_main.c#L39](https://github.com/espressif/esp-idf/blob/master/examples/get-started/hello_world/main/hello_world_main.c#L39)
