### ISSUE TITLE
Bug in example 'spi_slave_hd\segment_mode\seg_slave' when -Os or -O2 is set for CC (IDFGH-5420)

### ISSUE THREAD

**Issue by tslabs** [espressif/esp-idf#7163]
## Environment

- Development Kit:      none
- Module or chip used:  ESP32-S2
- IDF version: v4.4-dev-1594-g1d7068e4b
- Build System:         idf.py
- Compiler version: xtensa-esp32-elf-gcc (crosstool-NG esp-2020r3) 8.4.0
- Operating System:    Windows
- (Windows only) environment type: Plain Command Prompt
- Using an IDE?: No
- Power Supply:         any

## Problem Description

The '\examples\peripherals\spi_slave_hd\segment_mode\seg_slave\' contains a bug, which causes the example failure, if the C compiler optimization level is -Os or -O2.

### Expected Behavior
Must work normally.

### Actual Behavior
Throws an exception:
'E (220) SEG_SLAVE: No enough memory!'

### Steps to reproduce

0. Go to '\examples\peripherals\spi_slave_hd\segment_mode\seg_slave\' dir.
1. Run idf.py menuconfig.
2. Go to 'Compiler options', 'Optimisation options'.
4. Set '-Os' or '-O2' level.
5. Compile and flash the example.
6. Get the 'E (220) SEG_SLAVE: Not enough memory!' error.

### Code to reproduce this issue

```cpp
app_main.c

void app_main(void)
{
...
    uint32_t send_buf_size = 5000;
    uint32_t recv_buf_size = 120;
...
    xTaskCreate(sender, "sendTask", 4096, &send_buf_size, 1, NULL);
    xTaskCreate(receiver, "recvTask", 4096, &recv_buf_size, 1, NULL);
}
```
### The bug reason

Quite basic. 
The variables are created on stack which is different when passed to a task. Both void receiver(void *arg) and void sender(void *arg) receive garbage in 'arg'.
What works in -O0 will fail in -Os. The variables should be set to 'static' so that they put in .bss.
This type of bug might be present in other code snippets as well, so I suggest to check them.

### Code fixes

```cpp
void app_main(void)
{
...
    static uint32_t send_buf_size = 5000;
    static uint32_t recv_buf_size = 120;
...
    xTaskCreate(sender, "sendTask", 4096, &send_buf_size, 1, NULL);
    xTaskCreate(receiver, "recvTask", 4096, &recv_buf_size, 1, NULL);
}
```

**Comment by nopnop2002** [comment]
It may not be resolved, but what happens with the code below?

```
void app_main(void)
{
...
    static uint32_t send_buf_size = 5000;
    static uint32_t recv_buf_size = 120;
...
    xTaskCreate(sender, "sendTask", 4096, &send_buf_size, 1, NULL);
    xTaskCreate(receiver, "recvTask", 4096, &recv_buf_size, 1, NULL);
    while(1) {
      vTaskDelay(1);
    }
}
```
