### ISSUE TITLE
bug in idf_monitor.py (IDFGH-5431)

### ISSUE THREAD

**Issue by etay93** [espressif/esp-idf#7172]
Hi,
In version v4.3 you changed:
https://github.com/espressif/esp-idf/blob/1d7068e4be430edd92bb63f2d922036dcf5c3cc1/tools/idf_monitor.py#L652
instead of:
https://github.com/espressif/esp-idf/blob/1e3638390964c86b0e7ef3af02973b30c58ea1be/tools/idf_monitor.py#L892
That's working in Windows OS only if you give port as a parameter.

**Comment by dobairoland** [comment]
Hi @etay93. The automatic port detection was moved from `idf_monitor.py` to `idf.py monitor`. Do you have a good reason to use `idf_monitor.py` directly? I would like to recommend to you to use `idf.py monitor` or define the port by yourself.

**Comment by etay93** [comment]
thank you!
