### ISSUE TITLE
Compile time error using esp32c3.cmake  (IDFGH-5436)

### ISSUE THREAD

**Issue by pn21** [espressif/esp-idf#7177]
## Environment

- Development Kit:   ESP32-C3-DEVKITM-1
- Kit version (for DevKitM): [v1|v2|v3|v4]
- Module or chip used:  [ESP32-C3-MINI
- IDF version (run ``git describe --tags`` to find it): v4.3
- Build System:  CMAKE       [Make|CMake|idf.py]
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it): esp32-c3.cmake
    // 1.22.0-80-g6c4433a 
- Operating System:     Windows
- (Windows only) environment type: Plain Command Prompt 
- Using an IDE?: Yes Eclipse 
- Power Supply:       USB 

## Problem Description

I am getting the following error code when I compile our code using the esp32c3 cmake file:
.espressif\tools\riscv32-esp-elf\1.24.0.123_64eb9ff-8.4.0\riscv32-esp-elf\riscv32-esp-elf\include\c++\8.4.0\cstdlib:232:11: error: '::strtold' has not been declared
   using ::strtold;

My code has a combination of .c & .c++ files. The above error message shows up in all the files. I am using IDF v4.3(stable version). I am already using the foll:
#ifdef __cplusplus
extern "C"
{
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <cstdlib>
}
#endif

Any thoughts on how to resolve this error?

### Expected Behavior
Compile without any issues. Compiler should be able to differentiate the difference between .c & c++ files.

### Actual Behavior
Every time I compile get the following error message:
using the esp32c3 cmake file:
.espressif\tools\riscv32-esp-elf\1.24.0.123_64eb9ff-8.4.0\riscv32-esp-elf\riscv32-esp-elf\include\c++\8.4.0\cstdlib:232:11: error: '::strtold' has not been declared
   using ::strtold;

## Other items if possible

- Attached is the sdkconfig.h file.
[sdkconfig_info.txt](https://github.com/espressif/esp-idf/files/6688646/sdkconfig_info.txt)

**Comment by projectgus** [comment]
Hi @pn21,

I replied to your forum post about this: https://esp32.com/viewtopic.php?f=13&t=21567&p=78611#p78611

**Comment by projectgus** [comment]
Hi @pn21,

Did you make any progress finding a reproducible case for this?

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, sorry we didn't manage to reproduce the issue locally, will close due to short of updates, feel free to reopen with more details. Thanks.
