### ISSUE TITLE
ESP32-C3 support for i2s  (IDFGH-5437)

### ISSUE THREAD

**Issue by nicholasdkunes** [espressif/esp-idf#7178]
When will this be available? Is there a rough timeline. Need to decide if I must downgrade to a lower variant in the series in order to do i2s communication unless it is in the near future.

**Comment by Alvin1Zhang** [comment]
@nicholasdkunes Thanks for raising the feature request, I2S support in ESP32-C3 is available https://github.com/espressif/esp-idf/commit/8131d6f46d690e9cb60cc5cd457863cc5479351f, feel free to reopen.
