### ISSUE TITLE
IDF Monitor loops connecting (IDFGH-5451)

### ISSUE THREAD

**Issue by Prabhuelectro** [espressif/esp-idf#7190]
$ idf.py monitor 

Executing action: monitor
Serial port /dev/ttyUSB0
Connecting........_____....._____.....^C_____....._____
/dev/ttyUSB0 failed to connect: Failed to connect to Espressif device: Invalid head of packet (0x49)
No serial ports found. Connect a device, or use '-p PORT' option to set a specific port.

IDF Monitor can't connect without pressing boot button . When boot button is pressed the bellow come

$ idf.py monitor 
Executing action: monitor
Serial port /dev/ttyUSB0
Connecting........_____.
Detecting chip type... ESP32
Running idf_monitor in directory /home/proz/work/esp32/Projects/Water_Level_Measurement
Executing "/home/proz/.espressif/python_env/idf4.4_py3.8_env/bin/python /home/proz/work/esp32/esp-idf/tools/idf_monitor.py -p /dev/ttyUSB0 -b 115200 --toolchain-prefix xtensa-esp32-elf- --target esp32 --revision 0 /home/proz/work/esp32/Projects/Water_Level_Measurement/build/Water_Level_Measurement.elf -m '/home/proz/.espressif/python_env/idf4.4_py3.8_env/bin/python' '/home/proz/work/esp32/esp-idf/tools/idf.py'"...
--- idf_monitor on /dev/ttyUSB0 115200 ---
--- Quit: Ctrl+] | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---
ets Jun  8 2016 00:22:57

rst:0x1 (POWERON_RESET),boot:0x3 (DOWNLOAD_BOOT(UART0/UART1/SDIO_REI_REO_V2))
waiting for download

**Comment by dobairoland** [comment]
Hi @Prabhuelectro. Thank you for your report. Could you please try to revert back to commit 0bd357b2f14036fa7059da091d7cb6cb63045279 and 38d902f544d020c37c8417214fac2c4cabb26ea4. I suspect the the former will work while latter won't. Thanks!
