### ISSUE TITLE
Senser model and generic on off model not working together (IDFGH-5462)

### ISSUE THREAD

**Issue by nitinbhosaleemb** [espressif/esp-idf#7201]
Sensor client configured as role provisioner and cannot send on/off message to on/off server as required role node

**Comment by Alvin1Zhang** [comment]
Thanks for reporting. Would you please help provide more details as suggested in the [issue template](https://github.com/espressif/esp-idf/issues/new?assignees=&labels=&template=bug_report.md&title=)? Information like elf, sdk configuration, backtrace, log outputs, commit ID, hardware and etc. would help us debug further. Thanks.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to short of details, feel free to reopen with more details.
