### ISSUE TITLE
coap client example does not connect to coap://californium.eclipse.org (IDFGH-5485)

### ISSUE THREAD

**Issue by tiborrr** [espressif/esp-idf#7219]
## Environment

- Development Kit:      ESP32-Ethernet-Kit V1.2
- Module or chip used:  ESP32-WROVER-E
- IDF version (run ``git describe --tags`` to find it):
    8e3e65a47b7d9b5dc4f52eb56660a748fda1884e - v4.4-dev-1849-g8e3e65a47
- Build System:         idf.py
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it):
    xtensa-esp32-elf-gcc (crosstool-NG esp-2021r1) 8.4.0
- Operating System:     Linux
- Using an IDE?: Yes vscode with espressif extension
- Power Supply:         USB/PoE

## Problem Description

DNS can be found but the response is not as displayed in the example.

### Expected Behavior

as presented in the example:
```
I (2582) CoAP_client: DNS lookup succeeded. IP=104.196.15.150
Received:
************************************************************
CoAP RFC 7252                              Cf 2.0.0-SNAPSHOT
************************************************************
This server is using the Eclipse Californium (Cf) CoAP framework
published under EPL+EDL: http://www.eclipse.org/californium/

(c) 2014, 2015, 2016 Institute for Pervasive Computing, ETH Zurich and others
************************************************************
...
```
### Actual Behavior
```
I (184085) CoAP_client: DNS lookup succeeded. IP=198.41.30.194
E (189095) CoAP_client: select timeout
```
### Steps to reproduce

Flash coap client example

**Comment by mrdeep1** [comment]
The URL has changed as of 9th. December 2020.  It should be` coaps://californium.eclipseprojects.io` .  There is a PR waiting to be merged that updates the libcoap version - see #7106 which includes this change.
