### ISSUE TITLE
Unable to install esp-idf on Raspberry PI4 (IDFGH-5516)

### ISSUE THREAD

**Issue by jonathan84clark** [espressif/esp-idf#7245]
## Environment

- Development Kit:      ESP-32 AI-Thinker
- IDF version: v4.4-dev-1849-g8e3e65a47
- Compiler version: Not installing
- Operating System:    Ubuntu 21.04
- Using an IDE: No ide
- Raspberry PI4 8GB with Ubuntu installed

## Problem Description
I am working on installing esp-idf on the Raspberry PI4 running Ubuntu. I have been through a number of forums and looked over the documentation. I went through the following
https://esp32.com/viewtopic.php?t=11577 
https://esp32.com/viewtopic.php?t=256

I attempted to download the ARM toolchain and set the environmental variable however this failed and I am still getting the same errors.

Its clear that the setup scripts are not configured to handle ARM archetecture and there isn't a comprehensive document that goes through the process of getting everything setup manually. I would assume that this will be an EXTREMELY common use case (if it isn't already). 

Here are the errors:

`$ source ~/esp/esp-idf/export.sh
Detecting the Python interpreter
Checking "python" ...
Command 'python' not found, did you mean:
  command 'python3' from deb python3
  command 'python' from deb python-is-python3
Checking "python3" ...
Python 3.9.5
"python3" has been detected
Adding ESP-IDF tools to PATH...
ERROR: tool xtensa-esp32-elf has no installed versions. Please run '/home/jonathan/esp/esp-idf/install.sh' to install it.
ERROR: tool xtensa-esp32s2-elf has no installed versions. Please run '/home/jonathan/esp/esp-idf/install.sh' to install it.
ERROR: tool xtensa-esp32s3-elf has no installed versions. Please run '/home/jonathan/esp/esp-idf/install.sh' to install it.
ERROR: tool riscv32-esp-elf has no installed versions. Please run '/home/jonathan/esp/esp-idf/install.sh' to install it.
ERROR: tool esp32ulp-elf has no installed versions. Please run '/home/jonathan/esp/esp-idf/install.sh' to install it.
ERROR: tool esp32s2ulp-elf has no installed versions. Please run '/home/jonathan/esp/esp-idf/install.sh' to install it.
ERROR: tool openocd-esp32 has no installed versions. Please run '/home/jonathan/esp/esp-idf/install.sh' to install it.
Command 'python' not found, did you mean:
  command 'python3' from deb python3
  command 'python' from deb python-is-python3
env: ‘idf.py’: No such file or directory`

So I ran the following:
`$ ./install.sh
Detecting the Python interpreter
Checking "python" ...
/home/jonathan/esp/esp-idf/tools/detect_python.sh: line 16: python: command not found
Checking "python3" ...
Python 3.9.5
"python3" has been detected
Installing ESP-IDF tools
Installing tools: xtensa-esp32-elf, xtensa-esp32s2-elf, xtensa-esp32s3-elf, riscv32-esp-elf, esp32ulp-elf, esp32s2ulp-elf, openocd-esp32
ERROR: tool xtensa-esp32-elf does not have versions compatible with platform linux-arm64
`

### Expected Behavior
I would expect the install script to automatically detect the system architecture, CPU and OS and download the appropriate packages for that particular system.

### Actual Behavior
The install script requires a very specific system configuration in order to install properly. If its not x86 or x86 and uses ANY other OS besides Linux it fails.

### Steps to reproduce

1. Follow the esp-idf setup steps as documented https://docs.espressif.com/projects/esp-idf/en/latest/esp32/get-started/linux-setup.html on a Raspberry PI3, or Raspberry PI4. You will hit a wall.

I'm not sure where else to go with this. I was really hoping I could tell my company that we don't need a full Linux laptop or desktop to get an ESP workspace up and running. Am I wrong?

Thanks,

Jonathan L Clark

**Comment by dobairoland** [comment]
Hi @jonathan84clark. This feature request is tracked with https://github.com/espressif/esp-idf/issues/6432. Please subscribe to that issue to get notified when it is resolved. Thank you for understanding and the patience.
