### ISSUE TITLE
SMTP example is not working with hotmail.  (IDFGH-5522)

### ISSUE THREAD

**Issue by jerrytry1** [espressif/esp-idf#7250]
under examples/protocols/smtp_client

the example code is working fine with gmail.

However, it is not working with hotmail.

**Comment by nopnop2002** [comment]
Perhaps [this](https://github.com/espressif/esp-idf/blob/master/examples/protocols/smtp_client/main/server_root_cert.pem) data is different for gmail and hotmail.

**Comment by vikramdattu** [comment]
@jerrytry1 please try with certificate replaced as suggested by @nopnop2002

**Comment by jerrytry1** [comment]
openssl s_client -showcerts -connect smtp.googlemail.com:587 -starttls smtp
openssl s_client -showcerts -connect smtp-mail.outlook.com:587 -starttls smtp

**Comment by Alvin1Zhang** [comment]
Thanks for sharing updates, feel free to reopen.
