### ISSUE TITLE
ESP32S2 USB support (IDFGH-5536)

### ISSUE THREAD

**Issue by abdulwasey7** [espressif/esp-idf#7263]
**USB implemetaion  on esp32s2**

I am searching for usb implemetaion on esp32 but couldn't find any implementaion so far.

kindly suggest if there is any working implementaion or not. thanks

**Comment by chegewara** [comment]
What do you mean exactly by USB support?
There is tinyusb component for USB device, esp-idf console over USB, also some support for USB host. So, which USB support do you need?

https://github.com/espressif/esp-iot-solution/tree/usb/add_usb_solutions/components/usb
https://github.com/espressif/esp-idf/blob/master/components/usb/maintainers.md
https://github.com/espressif/esp-idf/tree/master/components/tinyusb

**Comment by abdulwasey7** [comment]
Thanks I have gone through the samples and it did what I want
