### ISSUE TITLE
 gpio: gpio_set_pull_mode(249): GPIO number error

### ISSUE THREAD

**Issue by jigsurfer** [espressif/esp-idf#7276]
void app_main (void)
.....
gpio_config_t io_conf = {};
io_conf.intr_type = GPIO_PIN_INTR_DISABLE;
io_conf.mode = GPIO_MODE_OUTPUT;
io_conf.pin_bit_mask = GPIO_SEL_2 | GPIO_SEL_4 | GPIO_SEL_5 ;
io_conf.pull_down_en = 1;
io_conf.pull_up_en = 0;
gpio_config(&io_conf);

gpio_pad_select_gpio(GPIO_INOUTPUT_IO_1);
gpio_pad_select_gpio(GPIO_INOUTPUT_IO_2);
gpio_pad_select_gpio(GPIO_INOUTPUT_IO_3);

/* Set the GPIO pull mode */
gpio_set_pull_mode(GPIO_INOUTPUT_IO_1, GPIO_PULLDOWN_ONLY);
gpio_set_pull_mode(GPIO_INOUTPUT_IO_2, GPIO_PULLDOWN_ONLY);
gpio_set_pull_mode(GPIO_INOUTPUT_IO_3, GPIO_PULLDOWN_ONLY);

Output:

Slave starting in 3
Slave starting in 2
Slave starting in 1
␛[0;32mI (6301) gpio: GPIO[2]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 1| Intr:0 ␛[0m
␛[0;32mI (6301) gpio: GPIO[4]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 1| Intr:0 ␛[0m
␛[0;32mI (6301) gpio: GPIO[5]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 1| Intr:0 ␛[0m
␛[0;31mE (6431) gpio: gpio_set_pull_mode(249): GPIO number error␛[0m
␛[0;32mI (6441) Device1: Driver installed␛[0m
␛[0;32mI (6441) Device1: Driver started␛[0m

Hi,
i configured almost everything are right but it seem the gpio_set_pull_mode always notifying error. I tried to look for this issue online but unsuccessful.

␛[0;31mE (6431) gpio: gpio_set_pull_mode(249): GPIO number error␛[0m

code running ok in order modules but only stage after bit_mask setting. What is wrong ? plz kindly help!

**Comment by jigsurfer** [comment]
void app_main (void)
.....
    gpio_config_t io_conf = {};
    io_conf.intr_type = GPIO_PIN_INTR_DISABLE;
    io_conf.mode = GPIO_MODE_OUTPUT;
    io_conf.pin_bit_mask = GPIO_SEL_2 | GPIO_SEL_4 | GPIO_SEL_5 ;
    io_conf.pull_down_en = 1;
    io_conf.pull_up_en = 0;
    gpio_config(&io_conf);

    gpio_pad_select_gpio(GPIO_INOUTPUT_IO_1);
    gpio_pad_select_gpio(GPIO_INOUTPUT_IO_2);
    gpio_pad_select_gpio(GPIO_INOUTPUT_IO_3);
 

    /* Set the GPIO pull mode */
    gpio_set_pull_mode(GPIO_INOUTPUT_IO_1, GPIO_PULLDOWN_ONLY);
    gpio_set_pull_mode(GPIO_INOUTPUT_IO_2, GPIO_PULLDOWN_ONLY);
    gpio_set_pull_mode(GPIO_INOUTPUT_IO_3, GPIO_PULLDOWN_ONLY);







Output:

Slave starting in 3
Slave starting in 2
Slave starting in 1
␛[0;32mI (6301) gpio: GPIO[2]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 1| Intr:0 ␛[0m
␛[0;32mI (6301) gpio: GPIO[4]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 1| Intr:0 ␛[0m
␛[0;32mI (6301) gpio: GPIO[5]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 1| Intr:0 ␛[0m
␛[0;31mE (6431) gpio: gpio_set_pull_mode(249): GPIO number error␛[0m
␛[0;32mI (6441) Device1: Driver installed␛[0m
␛[0;32mI (6441) Device1: Driver started␛[0m




Hi,
i configured almost everything are right but it seem the gpio_set_pull_mode always notifying error. I tried to look for this issue online but unsuccessful.

␛[0;31mE (6431) gpio: gpio_set_pull_mode(249): GPIO number error␛[0m 

code running ok in order modules but only stage after bit_mask setting. What is wrong ? plz kindly help!

**Comment by Alvin1Zhang** [comment]
@jigsurfer Thanks for reporting. Would you please help provide more details as suggested in the [issue template](https://github.com/espressif/esp-idf/issues/new?assignees=&labels=&template=bug_report.md&title=)? Information like elf, sdk configuration, backtrace, log outputs, commit ID, hardware and etc. would help us debug further. Thanks.

**Comment by Dazza0** [comment]
@jigsurfer 
```
[0;31mE (6431) gpio: gpio_set_pull_mode(249): GPIO number error␛[0m
```
Seems like you're getting a GPIO number error, meaning you're inputting an invalid GPIO number to `gpio_set_pull_mode()`. I suggest you double check that your `GPIO_INOUTPUT_IO_X` macros define to valid GPIOs. For specifics on valid GPIOs, see the `GPIO_IS_VALID_GPIO` macro [here](https://github.com/espressif/esp-idf/blob/3e370c4296247b349aa3b9a0076c05b9946d47dc/components/driver/include/driver/gpio.h#L50), or refer to the datasheet of the ESP32.

I don't think this is related to the GPIO driver so I'm closing this issue. Please feel free to reopen.
