### ISSUE TITLE
ESP32-C3 I2C read failure results in crash (IDFGH-5558)

### ISSUE THREAD

**Issue by eyewy** [espressif/esp-idf#7281]
On ESP32-C3, if for whatever reason I2C read fails, program crashes with following error code:

E (11861) task_wdt: Task watchdog got triggered. The following tasks did not res
et the watchdog in time:
E (11861) task_wdt:  - IDLE (CPU 0)
E (11861) task_wdt: Tasks currently running:
E (11861) task_wdt: CPU 0: my_i2c_service

where my_i2c_service is a function that writes and reads to I2C interface of a sensor. It has a 1000ms delay inside the while(1) loop. It is used as follows:
xTaskCreate(my_i2c_service, "my_i2c_service", ECHO_TASK_STACK_SIZE, NULL, 5, NULL);

I am using latest ESP-IDF mater branch. 5.1k external pullup resistors. reading from BME680 sensor. The error/crash happens at a random time, and if I2C read fails, otherwise everything is ok.
Also, I used  the nimble blehr example, where I modified the "blehr_tx_hrate" function to read the I2C sensor data and the transmit via BLE in this function. As this is a timed function (runs every 1000ms), I have not added any additional delay. Not sure why WDT is raised at some random time.

**Comment by eyewy** [comment]
closing to gather more info about the issue

**Comment by eyewy** [comment]
closing to gather more info about the issue

**Comment by eyewy** [comment]
As stated above, I tried many combinations and have been able to isolate the issue to I2c.

**Comment by o-marshmallow** [comment]
Hello @eyewy ,
Do you mean that you specified `my_i2c_service` as the callback for `xTaskCreate`?
Can you please provide me a small snippet of code to reproduce this?

**Comment by o-marshmallow** [comment]
@eyewy Any update?

**Comment by AxelLin** [comment]
@eyewy 
Is this still an issue?
It has been a while since you reported, could you try recently updated esp-idf version.

BTW, it's hard to find the exactly commit of the "latest SP-IDF master" on 17 Jul 2021,
please always report esp-idf version using "git describe --tags" command.

**Comment by Sampath-Science** [comment]
I am also facing similar issue. I2C is not working with ESP32C3. I had tried with the i2c_tools example to scan i2c devices but it ended with the below message 
"E (889558) task_wdt: Task watchdog got triggered. The following tasks did not reset the watchdog in time:
E (889558) task_wdt:  - IDLE (CPU 0)
E (889558) task_wdt: Tasks currently running:
E (889558) task_wdt: CPU 0: console_repl
"

Version: IDF 4.4

**Comment by AxelLin** [comment]
@Sampath-Science 
https://github.com/espressif/esp-idf/issues/8120

**Comment by Alvin1Zhang** [comment]
Thanks for reporting and sorry for slow turnaround, fix is available https://github.com/espressif/esp-idf/commit/0b00831703ec351c4c3b1040b004b358e4396067, we are also back porting to release branches. 

Feel free to reopen.
