### ISSUE TITLE
Com Port won't change (IDFGH-5562)

### ISSUE THREAD

**Issue by mparker-landt** [espressif/esp-idf#7285]
I was able to program a Lyrat Dev Board a few days ago. I recently tried flashing the same board and a problem occurred where it would not flash. I can see it's saying Serial port COM2 when the device is on COM3.
I have tried changing the port to COM3 which it says it does but the terminal always says COM2. I have also tried updating idf and managing the existing extension setup with the same result.

The only thing I can think of that's changed is that I updated IDF through Github Desktop before flashing.

**Comment by mparker-landt** [comment]
I have managed to get around this problem by rolling back the idf extension to the last update.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, sorry for slow turnaround, good to hear the issue got around, feel free to reopen.
