### ISSUE TITLE
hd_eeprom example don't work. (IDFGH-5574)

### ISSUE THREAD

**Issue by nopnop2002** [espressif/esp-idf#7297]
## Environment

```
Core is ESP32@160Mhz
freeRTOS version:V10.2.1
NEWLIB version:3.0.0
portTICK_RATE_MS:10 msec/tick
lwIP version:2-1-3-0
ESP-IDF version:v4.4-dev-1183-g9d34a1cd4-dirty
chip model is 1, chip with 2 CPU cores, WiFi/BT/BLE
silicon revision 1
2MB external flash
package is ESP32D0WDQ6
```

## Problem Description
read data not correct.

```
I (0) cpu_start: Starting scheduler on APP CPU.
I (334) main: PIN_NUM_MISO=18 PIN_NUM_MOSI=23 PIN_NUM_CLK=19 PIN_NUM_CS=13
I (344) main: Initializing bus SPI2...
I (344) main: Initializing device...
I (354) gpio: GPIO[13]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0
I (364) main: Write: Hello World!
I (364) main: Read: 
I (364) main: 0x3ffb62d1   ff ff ff ff ff ff ff ff  ff ff ff ff ff 00 00 00  |................|
I (374) main: 0x3ffb62e1   00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
I (384) main: Example finished.
```

### menuconfig

![hd_eeprom](https://user-images.githubusercontent.com/6020549/126423796-c849dc35-91a3-4ddf-af48-a63e7bb3087a.jpg)

### the connections

| 93C46 | ESP32 | 
| ---- | ----- | 
| Host | HSPI  |
| VCC  | 3.3V  |
| GND  | GND   |
| DO   |  18    |
| DI   |  23    | 
| SK   | 19    | 
| CS   | 13    |
| ORG  | GND   |

**Comment by nopnop2002** [comment]
I changed the development board.
solved.
It's a hardware problem.


```
I (0) cpu_start: Starting scheduler on APP CPU.
I (334) main: PIN_NUM_MISO=18 PIN_NUM_MOSI=23 PIN_NUM_CLK=19 PIN_NUM_CS=13
I (344) main: Initializing bus SPI2...
I (344) main: Initializing device...
I (354) gpio: GPIO[13]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0
I (364) main: Write: Hello World!
I (384) main: Read: Hello World!
I (384) main: 0x3ffb6331   48 65 6c 6c 6f 20 57 6f  72 6c 64 21 00 00 00 00  |Hello World!....|
I (394) main: 0x3ffb6341   00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
I (404) main: Example finished.
```

**Comment by charmi4857** [comment]
> ## Environment
> ```
> Core is ESP32@160Mhz
> freeRTOS version:V10.2.1
> NEWLIB version:3.0.0
> portTICK_RATE_MS:10 msec/tick
> lwIP version:2-1-3-0
> ESP-IDF version:v4.4-dev-1183-g9d34a1cd4-dirty
> chip model is 1, chip with 2 CPU cores, WiFi/BT/BLE
> silicon revision 1
> 2MB external flash
> package is ESP32D0WDQ6
> ```
> 
> ## Problem Description
> read data not correct.
> 
> ```
> I (0) cpu_start: Starting scheduler on APP CPU.
> I (334) main: PIN_NUM_MISO=18 PIN_NUM_MOSI=23 PIN_NUM_CLK=19 PIN_NUM_CS=13
> I (344) main: Initializing bus SPI2...
> I (344) main: Initializing device...
> I (354) gpio: GPIO[13]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0
> I (364) main: Write: Hello World!
> I (364) main: Read: 
> I (364) main: 0x3ffb62d1   ff ff ff ff ff ff ff ff  ff ff ff ff ff 00 00 00  |................|
> I (374) main: 0x3ffb62e1   00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
> I (384) main: Example finished.
> ```
> 
> ### menuconfig
> ![hd_eeprom](https://user-images.githubusercontent.com/6020549/126423796-c849dc35-91a3-4ddf-af48-a63e7bb3087a.jpg)
> 
> ### the connections
> 93C46	ESP32
> Host	HSPI
> VCC	3.3V
> GND	GND
> DO	18
> DI	23
> SK	19
> CS	13
> ORG	GND



I got the same problem. Can you tell me, how to solve that.

**Comment by nopnop2002** [comment]
@charmi4857 

I changed the development board.

**Comment by charmi4857** [comment]
But i think, there is no problem in my development board. Did you change
anything in the hd_eeprom code.

**Comment by charmi4857** [comment]
Okk. I understand now.
