### ISSUE TITLE
SPP support with NimBLE (IDFGH-5581)

### ISSUE THREAD

**Issue by venkateshgr-ayla** [espressif/esp-idf#7303]
Hi All,
I wanted to know if SPP can be supported with NimBLE? Currently I am not using Bluedroid. I want to port SPP-Bluedroid to SPP-NimBLE.
Is it technically possible and recommended? 
Does ESP have any plans to support SPP over NimBLE?
Kindly help me with your suggestions on SPP feature with NimBLE.

Thanks,
GR.Venkatesh

**Comment by RahulEspressif** [comment]
Hi @venkateshgr-ayla ,  

 SPP ( Serial Port profile ) is a basically a bluetooth classic profile. Nimble, is BLE only stack. 

 We can however achieve the same by implementing a custom LE service running on top of GATT and simulate the behaviour and achieve SPP functionality in BLE. 

Currently, there is no such custom service implemented for Nimble. We will check internally and plan if we can release this as part of the SDK. 

Thanks,
 Rahul

**Comment by venkateshgr-ayla** [comment]
Hi Rahul,

Thanks for the response. Is it possible for this feature release? If so can I know approximate timeline?

Thanks,
GR.Venkatesh

**Comment by rahult-github** [comment]
Hi @venkateshgr-ayla ,

 We are planning on including this feature and are currently  targeting to include this example in stable release in Q4' 21  quarter. 

Thanks,
 Rahul

**Comment by IshaESP** [comment]
Hi @venkateshgr-ayla,
 
Can you try this patch?
[nimble_spp_patch.txt](https://github.com/espressif/esp-idf/files/7345808/nimble_spp_patch.txt)

Thanks,
Isha

**Comment by Alvin1Zhang** [comment]
@venkateshgr-ayla Thanks for reporting, would you please help share if any updates? Thanks.
