### ISSUE TITLE
CONFIG_SPIRAM_ALLOW_BSS_SEG_EXTERNAL_MEMORY not build for ESP32-S2 target (IDFGH-5582)

### ISSUE THREAD

**Issue by Darsh-Dev** [espressif/esp-idf#7304]
Hi,

I have an **ESP32-S2-WROVER** kit and I am trying to enable **CONFIG_SPIRAM_ALLOW_BSS_SEG_EXTERNAL_MEMORY in **release-4.3****. but it through below error while building the code.

> esp-idf/components/esp_system/port/cpu_start.c: In function 'call_start_cpu0':
esp-idf/components/esp_system/port/cpu_start.c:426:13: error: '_ext_ram_bss_start' undeclared (first use in this function); did you mean '_rtc_bss_start'?
     memset(&_ext_ram_bss_start, 0, (&_ext_ram_bss_end - &_ext_ram_bss_start) * sizeof(_ext_ram_bss_start));
             ^~~~~~~~~~~~~~~~~~
             _rtc_bss_start
/esp-idf/components/esp_system/port/cpu_start.c:426:13: note: each undeclared identifier is reported only once for each function it appears in
/esp-idf/components/esp_system/port/cpu_start.c:426:38: **error: '_ext_ram_bss_end' undeclared (first use in this function); did you mean '_rtc_bss_end'?**
     memset(&_ext_ram_bss_start, 0, (&_ext_ram_bss_end - &_ext_ram_bss_start) * sizeof(_ext_ram_bss_start));
                                      ^~~~~~~~~~~~~~~~
                                      _rtc_bss_end

I am referring to this [link](https://docs.espressif.com/projects/esp-idf/en/release-v4.3/esp32s2/api-guides/external-ram.html?highlight=spiram_allow_bss_seg_external_memory#allow-bss-segment-placed-in-external-memory).

Please help me with how I can enable this config and resolve this build error for **ESP32-S2**.

Thanks.

**Comment by mahavirj** [comment]
@Darsh-Dev 

This feature is not yet supported for S2. As highlighted in https://github.com/espressif/esp-idf/issues/6162, this will be supported soon. I will mark this issue as closed and we can use https://github.com/espressif/esp-idf/issues/6162 to track this further.
