### ISSUE TITLE
Typo in docs/en/COPYRIGHT.rst (IDFGH-5589)

### ISSUE THREAD

**Issue by AxelLin** [espressif/esp-idf#7311]
In docs/en/COPYRIGHT.rst
:component:`ESP-MQTT <mqtt>` MQTT Package (contiki-mqtt) - Copyright (c) 2014, Stephen Robinson, MQTT-ESP - Tuan PM <tuanpm at live dot com> is licensed under Apache License 2,0 as described in :component_file:`LICENSE file <mqtt/esp-mqtt/LICENSE>`.

"Apache License 2,0" should be changed to "Apache License 2.0"

**Comment by Dazza0** [comment]
Closed by commit 999710fd6abece4c563a9e7eddcfb1dff4ea6412
