### ISSUE TITLE
Expose "uint8_t get_ota_partition_count(void)" (IDFGH-5591)

### ISSUE THREAD

**Issue by MartonSipi** [espressif/esp-idf#7313]
**Is your feature request related to a problem? Please describe.**

There is a backward compatibility issue with the old ESP8266, because of the fact that this function was exposed back there, but not anymore.

**Describe the solution you'd like**

Expose "uint8_t get_ota_partition_count(void)" in esp_ota_ops.h

**Comment by Szekyy** [comment]
Hi. I'm having the same issue. Any updates on that?

**Comment by shubhamkulkarni97** [comment]
Hi @Szekyy, fix for this issue is merged in internal repository. It will be available on GitHub once all internal checks are passed.

This issue will be updated once the commit is available on GitHub.
