### ISSUE TITLE
c语言标准 the standard of C language (IDFGH-5601)

### ISSUE THREAD

**Issue by PickaxeHit** [espressif/esp-idf#7322]
esp-idf 用的是c语言的标准？c99还是c11？

Which standard of the C language used in esp-idf? c99 or c11?

**Comment by nopnop2002** [comment]
I think it's C11 because these headers can be used.

```
#include "float.h"
#include "stdalign.h"
#include "complex.h"
```

**Comment by tingjhenjiang** [comment]
how do I set the C standard for the "main" (entire project)? 
I've tried:

rootfolder/CMakeLists.txt
```
cmake_minimum_required(VERSION 3.5)

include($ENV{IDF_PATH}/tools/cmake/project.cmake)
project(my_project)

# Set the C standard to C11
target_compile_options(${CMAKE_PROJECT_NAME} PRIVATE -std=gnu11)
```
OR
```
rootfolder/main/CMakeLists.txt
target_compile_options("." PRIVATE -std=gnu11)
idf_component_register(SRCS "main.c"
                    INCLUDE_DIRS "")
```
both failed.
@Dazza0 Thanks!

**Comment by igrr** [comment]
@tingjhenjiang In main/CMakeLists.txt, you can use this:

```c++
idf_component_register(SRCS main.c INCLUDE_DIRS ".")
target_compile_options(${COMPONENT_LIB} PRIVATE -std=gnu11)
```

However, please note that this is probably unnecessary... C language standard in all currently maintained IDF versions (v5.x) is already `gnu17`.

**Comment by tingjhenjiang** [comment]
> @tingjhenjiang In main/CMakeLists.txt, you can use this:
> 
> ```c++
> idf_component_register(SRCS main.c INCLUDE_DIRS ".")
> target_compile_options(${COMPONENT_LIB} PRIVATE -std=gnu11)
> ```
> 
> However, please note that this is probably unnecessary... C language standard in all currently maintained IDF versions (v5.x) is already `gnu17`.

@igrr It succeeds. Thanks!
Btw, the "gnu11" is simply an example for this post. Anyway Thanks!
