### ISSUE TITLE
Memory exhaust even after increasing CRPL value!!  (IDFGH-5613)

### ISSUE THREAD

**Issue by sumathi98** [espressif/esp-idf#7333]
## Environment

Development Kit : ESP32-DevKitC
Module or chip used: ESP32-WROOM-32U
IDF version : v4.4.0
Build System : idf.py
Compiler version : 8.4.0
Operating System : Linux
Using an IDE? : No
Power Supply : external 5V

## Problem Description
Iam developing a BLE Mesh network. Iam using onoff_client example as the base code. I have implemented both onoff_client model and onoff_server model on same node. Client model for controlling other server nodes and Server model for receiving heartbeat (like I will be publishing a pin state every 5s) from other server nodes. It is working fine for sometime, after sometime it results in out of memory and wifi disconnection.

It seems to be because of RPL entry. So I have increased CRPL value and frequency of RPL getting stored to flash, below is my configuration

#define CONFIG_BLE_MESH_SETTINGS 1
#define CONFIG_BLE_MESH_STORE_TIMEOUT 0
#define CONFIG_BLE_MESH_SEQ_STORE_RATE 10000
#define CONFIG_BLE_MESH_RPL_STORE_TIMEOUT 10000
#define CONFIG_BLE_MESH_SUBNET_COUNT 3
#define CONFIG_BLE_MESH_APP_KEY_COUNT 3
#define CONFIG_BLE_MESH_MODEL_KEY_COUNT 3
#define CONFIG_BLE_MESH_MODEL_GROUP_COUNT 3
#define CONFIG_BLE_MESH_LABEL_COUNT 3
#define CONFIG_BLE_MESH_CRPL 500
#define CONFIG_BLE_MESH_MSG_CACHE_SIZE 8000

Please let know if any other configuration need to be done to solve the issue.

## Debug Logs
ERROR:
<27>[0;31mE (168080) BLE_MESH: bt_mesh_alloc_buf, Out of memory<27>[0m<\r><\n>
<27>[0;31mE (168080) BLE_MESH: sdu_recv, Out of memory<27>[0m<\r><\n>
<27>[0;31mE (168140) BLE_MESH: Failed to set mesh/rpl/0062 data (err 257)<27>[0m<\r><\n>
<27>[0;31mE (168140) BLE_MESH: Failed to store RPL entry 0x0062<27>[0m<\r><\n>
<27>[0;31mE (168140) BLE_MESH: bt_mesh_alloc_buf, Out of memory<27>[0m<\r><\n>
<27>[0;31mE (168140) BLE_MESH: sdu_recv, Out of memory<27>[0m<\r><\n>
<27>[0;31mE (169100) BLE_MESH: Failed to set mesh/rpl/0064 data (err 257)<27>[0m<\r><\n>
<27>[0;31mE (169100) BLE_MESH: Failed to store RPL entry 0x0064<27>[0m<\r><\n>

**Comment by InfiniteYuan** [comment]
Please print the size of available heap, the minimum heap that has ever been available and the size of available internal heap periodically. [Refer](https://github.com/espressif/esp-idf/blob/v4.3/components/esp_system/include/esp_system.h#L114-L139)

**Comment by Alvin1Zhang** [comment]
@sumathi98 Thanks for reporting, would you please help share if any updates for the issue? Thanks.

**Comment by Alvin1Zhang** [comment]
@sumathi98 Thanks for reporting, would you please help share if any updates for the issue? Thanks.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to short of feedback, feel free to reopen with more updates.
