### ISSUE TITLE
Possible problem due to code copy-paste. (IDFGH-5639)

### ISSUE THREAD

**Issue by alexander-sorokin** [espressif/esp-idf#7360]
https://github.com/espressif/esp-idf/blob/58022f8599401740979ac7657a57348285a70374/components/driver/uart.c#L300
Both lines have identical comparison and the same error description:

`ESP_RETURN_ON_FALSE((rx_thresh_xon < SOC_UART_FIFO_LEN), ESP_FAIL, UART_TAG, "rx flow xon thresh error");
ESP_RETURN_ON_FALSE((rx_thresh_xoff < SOC_UART_FIFO_LEN), ESP_FAIL, UART_TAG, "rx flow xon thresh error");`

**Comment by ESP-Marius** [comment]
Woops, seems like a type in the error message there yeah, should be `ESP_RETURN_ON_FALSE((rx_thresh_xoff < SOC_UART_FIFO_LEN), ESP_FAIL, UART_TAG, "rx flow xoff thresh error");`

Will fix it, thanks for reporting this.
