### ISSUE TITLE
mbc_master_get_parameter fails without error when mb_parameter_descriptor_t list has duplicate param_key (IDFGH-5641)

### ISSUE THREAD

**Issue by ToonVanEyck** [espressif/esp-idf#7362]
## Environment

- Development Kit: / 
- Kit version: /
- Module or chip used:  ESP32-WROOM-32D
- IDF version: v4.4-dev-1404-gc13afea63
- Build System: idf.py
- Compiler version xtensa-esp32-elf-gcc (crosstool-NG esp-2020r3) 8.4.0
- Operating System:  Linux
- Using an IDE?: Yes VS Code
- Power Supply:  external 3.3V

## Problem Description

mbc_master_get_parameter does not return an error code, thus I expect the value to contain valid data. Data is unchanged. When examining data transfered on modbus lines no data is observed.

The cause is a duplicate param_key in the mb_parameter_descriptor_t list.

### Expected Behavior

error code

### Actual Behavior

no error

### Steps to reproduce
 change modbus serial master erxample to contain a duplicate param_key string in mb_parameter_descriptor_t .

**Comment by alisitsyn** [comment]
@ToonVanEyck,

Thank you for your issue. I can confirm this as a bug for functions `mbc_serial_master::mbc_serial_master_set_parameter(mbc_serial_master_get_parameter)`. If the function `mbc_serial_master_set_request()`  found the first parameter descriptior with corresponded param_key but we try to get second parameter with the same parameter key the `mbc_serial_master_get_parameter` does not send the request and returns `ESP_OK`.

Please check the patch below:
[The patch 0001_invalid_error_handling_for_duplicate_param_key.diff](https://github.com/espressif/esp-idf/files/6954322/0001_invalid_error_handling_for_duplicate_param_key.diff.log)

**Comment by alisitsyn** [comment]
@ToonVanEyck,

The merge request is in progress. Once it merged the issue will be closed automatically.

**Comment by alisitsyn** [comment]
The fix is merged. It will take some time to sync with github.
