### ISSUE TITLE
esp_ping_new_session can fail returning ESP_OK, losing the reference to allocated memory thus generating a memory leak as a secondary effect (IDFGH-5642)

### ISSUE THREAD

**Issue by DBMTC** [espressif/esp-idf#7363]
## Problem Description

Documentation for function esp_ping_new_session says: "ESP_OK: create ping session successfully, user can take the ping handle to do follow-on jobs", however the first line of the function (line 215 of ping_sock.c) is "esp_err_t ret = ESP_OK;". To return an error code the PING_CHECK macro is used that set the error and perform a goto err witch in turn returns ret.

PINKG_CHECK is not actually used in lines 272-280 and if an interface is selected for the ping and an error is detected there goto err will be performed, but no output is given and ESP_OK is returned thus breaking the API.

```
        if(netif_index_to_name(config->interface, iface.ifr_name) == NULL) {
          goto err;
        }
        if(setsockopt(ep->sock, SOL_SOCKET, SO_BINDTODEVICE, &iface, sizeof(iface) !=0)) {
          goto err;
        }
```

### Expected Behavior

If ESP_OK is returned a subsequent call to esp_ping_start will start the ping.

### Actual Behavior

ESP_OK is returned even if an error preventing esp_ping_start  to work correctly happened.

### Steps to reproduce

Request a ping setting config->interface as a big number.

**Comment by ESP-YJM** [comment]
@DBMTC Thanks for reporting this problem. We will fix it.
