### ISSUE TITLE
How much minimum heap is required for TLS handshake ? (IDFGH-5665)

### ISSUE THREAD

**Issue by MarkEvens** [espressif/esp-idf#7387]
IDF Version 4.2.1
OS Ubuntu
IDE VS-code

I am using BLE + WiFi together and want to do OTA update. But got below error.

How much minimum heap is required ? Because my free heap size is Free "48428" and still I am getting below error.
```
E (61836) esp-tls-mbedtls: mbedtls_ssl_handshake returned -0x10
I (61846) esp-tls-mbedtls: Certificate verified.
E (61846) esp-tls: Failed to open new connection
E (61846) TRANS_SSL: Failed to open a new connection
E (61856) HTTP_CLIENT: Connection failed, sock < 0
E (61856) esp_https_ota: Failed to open HTTP connection: ESP_ERR_HTTP_CONNECT
E (61866) esp_https_ota: Failed to establish HTTP connection
```

_Originally posted by @MarkEvens in https://github.com/espressif/esp-idf/issues/4357#issuecomment-894220622_

**Comment by chegewara** [comment]
70kB+

**Comment by negativekelvin** [comment]
40k can be enough but it depends on how fragmented it is

**Comment by kayzen9** [comment]
https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/protocols/esp_tls.html#comparison-between-mbedtls-and-wolfssl
https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/performance/ram-usage.html#reducing-heap-usage

**Comment by mahavirj** [comment]
@MarkEvens 

Pointers mentioned above have some rough ballpark for memory numbers for TLS connection. One feature that may help to reduce memory further is:

https://github.com/espressif/esp-idf/blob/83956ebbae5b335fbe7537fee737c0784d1cf471/components/mbedtls/Kconfig#L100

You may try enabling this once in your application. Additionally [blog post](https://blog.espressif.com/esp32-memory-analysis-case-study-eacc75fe5431) can be further useful in understanding/optimizing memory for typical TLS enabled cloud application on ESP32.

Hope this helps. If you still face any issues, please feel free to create new issue providing more details along with your sample application.
