### ISSUE TITLE
MD5 of current firmware (IDFGH-5675)

### ISSUE THREAD

**Issue by PratikMistry-cbi** [espressif/esp-idf#7396]
**Is your feature request related to a problem? Please describe.**

Trying to generate MD5 of current firmware. Saw there is code in ardunio famework however looking for easy api call to use in idf framework

**Describe the solution you'd like**

Simple api function to call to generate MD5 hash of current firmware

**Additional context**

OTA functionality with a server requires MD5 in the http header otherwise repeats OTA indefinitely because hash codes dont match

**Comment by mahavirj** [comment]
@PratikMistry-cbi 

For MD5 sum, API reference is available at:

https://github.com/espressif/esp-idf/blob/master/components/esp_rom/include/esp_rom_md5.h

There is no built-in API to retrieve MD5 of current firmware, but you may create one along the lines of SHA256 from:

https://github.com/espressif/esp-idf/blob/166c30e7b2ed1dcaae56179329540a862915208a/components/bootloader_support/src/bootloader_utility.c#L880

**Comment by mahavirj** [comment]
Closing the issue, if there are any additional questions please feel free to start thread at esp32.com
