### ISSUE TITLE
scanning and advertising

### ISSUE THREAD

**Issue by lixianyu** [espressif/esp-idf#741]
Is it possible to scan and advertise at the same time?
也就是说，ESP32即作为client端又做为server端？

**Comment by youyudedasan** [comment]
不能同时广播和扫描，但是可以通过时间片来实现“同时”。
ESP32没有这个例程，可以参考TI的simpleBLEMulti_patch例程

**Comment by lixianyu** [comment]
@youyudedasan ，嗨，您好，感谢。可否提供一下simpleBLEMulti_patch这个例程？^_^
另外这个是CC2640的例程，能用到ESP32上吗？

**Comment by lixianyu** [comment]
Hi, all ,  please see: https://github.com/espressif/esp-idf/issues/404

**Comment by FayeY** [comment]
Hi @lixianyu , is this problem solved now？
