### ISSUE TITLE
esp_bt_get_mac() not found in version 4.3 (esp32C3) (IDFGH-5689)

### ISSUE THREAD

**Issue by wibbler** [espressif/esp-idf#7410]
The function esp_bt_get_mac() has been removed in esp_idf (4.3).
Prototype is still in esp_bt.h and in esp_idf documentation.
suggest either fix by macro or ensuring that it is clear in the documentation, and removing prototype in header file.

**Comment by chhajedji** [comment]
Thanks @wibbler for pointing this out. `esp_bt_get_mac` is no longer present. We'll update it.
