### ISSUE TITLE
mcpwm_capture_hc_sr04  "assert failed: xQueueSendFromISR queue.c" (IDFGH-5699)

### ISSUE THREAD

**Issue by pwgen** [espressif/esp-idf#7419]
This  example creates and initialize the interrupt before the queue is created.
this causes a crash with "assert failed: xQueueSendFromISR queue.c"

moving up  the queue initialisation  before the  isr initialisation  fixed the problem.

cap_queue = xQueueCreate(10,sizeof(uint32_t));
    if (cap_queue == 0) {
        ESP_LOGE(TAG, "failed to alloc cap_queue");
    }
 ESP_ERROR_CHECK(mcpwm_gpio_init(MCPWM_UNIT_0, MCPWM_CAP_0, HC_SR04_PIN_ECHO));
    // enable pull down CAP0, to reduce noise
    ESP_ERROR_CHECK(gpio_pulldown_en(HC_SR04_PIN_ECHO));
    // enable both edge capture on CAP0
    mcpwm_capture_config_t conf = {
        .cap_edge = MCPWM_BOTH_EDGE,
        .cap_prescale = 1,
        .capture_cb = sr04_echo_isr_handler,
        .user_data = NULL
    };
    ESP_ERROR_CHECK(mcpwm_capture_enable_channel(MCPWM_UNIT_0, MCPWM_SELECT_CAP0, &conf));
    ESP_LOGI(TAG, "Echo pin configured");

**Comment by SalimTerryLi** [comment]
Thanks for reporting that :) The fix is coming soon
