### ISSUE TITLE
[TW#13665] A fatal error occurred: Timed out waiting for packet header

### ISSUE THREAD

**Issue by davidm-public** [espressif/esp-idf#744]
```
$ make flash
Flashing binaries to serial port /dev/tty.SLAB_USBtoUART (app at offset 0x10000)...
esptool.py v2.0.1
Connecting........___

A fatal error occurred: Timed out waiting for packet header
make: *** [flash] Error 2
```

OS: macOS Sierra version 10.12.5

Any ideas?

**Comment by elfalko** [comment]
Something similar happened to me when I had some breadboard test configuration attached to the dev kit c. In my case, detaching some wires solved the problem. I permanently evaded the problem by using some different pins.

**Comment by HubbyGitter** [comment]
On Linux, I'll see this if my terminal software is running in parallel.
