### ISSUE TITLE
Support SNTP get servers from DHCP (IDFGH-5724)

### ISSUE THREAD

**Issue by joncmaloney** [espressif/esp-idf#7444]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

Please give as many details as you can. Include suggestions for useful APIs or interfaces if relevant.

**Additional context**

**Comment by joncmaloney** [comment]
There is currently provision in esp-idf/components/lwip/lwip/src/include/lwip/apps/sntp.h for the option SNTP_GET_SERVERS_FROM_DHCP however this feature doesn't seem to link to any menuconfig #defines. 

Is it possible to add support so that lwip can get NTP server address from DHCP options?

**Comment by david-cermak** [comment]
Hi @joncmaloney 

We have this PR https://github.com/espressif/esp-idf/pull/7336 , currently in progress of merging to master, which adds `CONFIG_LWIP_DHCP_GET_NTP_SRV` as the configuration option.

**Comment by joncmaloney** [comment]
Thanks David. Great looking forward to it.
