### ISSUE TITLE
Eclipse Debug session gets cpu reset after app_main() in ESP IDF 4.3 (IDFGH-5725)

### ISSUE THREAD

**Issue by nitinbhosaleemb** [espressif/esp-idf#7445]
Logs of eclipse debug session :

683,468 2-gdb-version
683,469 ~"GNU gdb (crosstool-NG esp-2020r3) 8.1.0.20180627-git\n"
683,469 ~"Copyright (C) 2018 Free Software Foundation, Inc.\n"
683,469 ~"License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>\nThis is fre\
e software: you are free to change and redistribute it.\nThere is NO WARRANTY, to the extent permitt\
ed by law.  Type \"show copying\"\nand \"show warranty\" for details.\n"
683,469 ~"This GDB was configured as \"--host=x86_64-host_w64-mingw32 --target=xtensa-esp32s3-elf\".\
\nType \"show configuration\" for configuration details."
683,469 ~"\nFor bug reporting instructions, please see:\n"
683,469 ~"<http://www.gnu.org/software/gdb/bugs/>.\n"
683,469 ~"Find the GDB manual and other documentation resources online at:\n<http://www.gnu.org/soft\
ware/gdb/documentation/>.\n"
683,469 ~"For help, type \"help\".\n"
683,469 ~"Type \"apropos word\" to search for commands related to \"word\".\n"
683,469 2^done
683,469 (gdb) 
683,470 3-environment-cd C:/Users/e0624432/eclipse-workspace/ble_sensor_server
683,480 3^done
683,480 (gdb) 
683,481 4-gdb-set breakpoint pending on
683,492 4^done
683,492 (gdb) 
683,492 5-enable-pretty-printing
683,503 5^done
683,503 (gdb) 
683,503 6-gdb-set python print-stack none
683,514 6^done
683,514 (gdb) 
683,514 7-gdb-set print object on
683,525 7^done
683,525 (gdb) 
683,525 8-gdb-set print sevenbit-strings on
683,536 8^done
683,536 (gdb) 
683,536 9-gdb-set charset ISO-8859-1
683,547 9^error,msg="Undefined item: \"ISO-8859-1\"."
683,547 (gdb) 
683,547 10-gdb-set dprintf-style gdb
683,558 10^done
683,558 (gdb) 
683,558 11source .gdbinit
683,569 &"source .gdbinit\n"
683,570 &".gdbinit: No such file or directory.\n"
683,570 11^error,msg=".gdbinit: No such file or directory."
683,570 (gdb) 
683,570 12-gdb-set target-async off
683,581 12^done
683,581 (gdb) 
683,581 13-gdb-set auto-solib-add on
683,581 13^done
683,581 (gdb) 
683,583 14symbol-file C:\\Users\\e0624432\\eclipse-workspace\\ble_sensor_server\\build\\sensor_serve\
r.elf

683,593 &"symbol-file C:\\\\Users\\\\e0624432\\\\eclipse-workspace\\\\ble_sensor_server\\\\build\\\\\
sensor_server.elf\n"
683,595 ~"Reading symbols from C:\\Users\\e0624432\\eclipse-workspace\\ble_sensor_server\\build\\sen\
sor_server.elf..."
683,667 ~"done.\n"
683,672 14^done
683,673 (gdb) 
683,673 &"\n"
683,673 ^done
683,673 (gdb) 
683,673 15-target-select remote localhost:3333

683,709 =thread-group-started,id="i1",pid="42000"
683,709 &"warning: No executable has been specified and target does not support\ndetermining executa\
ble automatically.  Try using the \"file\" command."
683,709 &"\n"
683,709 =thread-created,id="1",group-id="i1"
683,719 ~"app_main () at ../main/main.c:979\n"
683,720 ~"979\t    ESP_LOGI(TAG, \"Initializing...\");\n"
683,720 *stopped,frame={addr="0x4200926f",func="app_main",args=[],file="../main/main.c",fullname="c:\
\\users\\e0624432\\eclipse-workspace\\ble_sensor_server\\main\\main.c",line="979"},thread-id="1",sto\
pped-threads="all"
683,754 15^connected
683,754 (gdb) 
683,754 &"\n"
683,754 ^done
683,754 (gdb) 
683,754 16set remote hardware-watchpoint-limit 2
683,754 17mon reset halt
683,754 18flushregs
683,764 &"set remote hardware-watchpoint-limit 2\n"
683,764 =cmd-param-changed,param="remote hardware-watchpoint-limit",value="2"
683,764 16^done
683,764 (gdb) 
683,764 &"mon reset halt\n"
683,773 @"JTAG tap: esp32s3.cpu0 tap/device found: 0x120034e5 (mfg: 0x272 (Tensilica), part: 0x2003,\
 ver: 0x1)\n"
683,780 @"JTAG tap: esp32s3.cpu1 tap/device found: 0x120034e5 (mfg: 0x272 (Tensilica), part: 0x2003,\
 ver: 0x1)\n"
683,900 @"esp32s3.cpu0: Debug controller was reset.\n"
683,903 @"esp32s3.cpu0: Core was reset.\n"
683,912 @"esp32s3.cpu0: Target halted, PC=0x500000C4, debug_reason=00000000\n"
683,917 @"Set GDB target to 'esp32s3.cpu0'\n"
683,927 @"\n"
683,934 @"esp32s3.cpu0: Core was reset.\n"
683,948 @"esp32s3.cpu0: Target halted, PC=0x40000400, debug_reason=00000000\n"
683,953 17^done
683,953 (gdb) 
683,953 &"flushregs\n"
683,953 ~"Register cache flushed.\n"
683,953 18^done
683,953 (gdb) 
683,953 19load C:\\Users\\e0624432\\eclipse-workspace\\ble_sensor_server\\build\\sensor_server.elf 
\

683,964 &"load C:\\\\Users\\\\e0624432\\\\eclipse-workspace\\\\ble_sensor_server\\\\build\\\\sensor_\
server.elf \n"
683,966 ~"Loading section .flash.appdesc, size 0x100 lma 0x3c0a0020\n"
683,966 19+download,{section=".flash.appdesc",section-size="256",total-size="11157180"}
683,967 19+download,{section=".flash.appdesc",section-sent="256",section-size="256",total-sent="256"\
,total-size="11157180"}
683,967 ~"Loading section .flash.rodata, size 0x2aedc lma 0x3c0a0120\n"
683,969 &"Load failed\n"
683,969 19^error,msg="Load failed"
683,969 (gdb) 
683,969 &"\n"
683,969 ^done
683,969 (gdb) 
683,970 20-gdb-show --thread-group i1 language
683,980 20^done,value="auto"
683,980 (gdb) 
683,980 21-gdb-set --thread-group i1 language c
683,990 21^done
683,990 (gdb) 
683,990 22-interpreter-exec --thread-group i1 console "p/x (char)-1"
684,001 ~"$1 = 0xff\n"
684,001 22^done
684,001 (gdb) 
684,001 23-data-evaluate-expression --thread-group i1 "sizeof (void*)"
684,003 23^done,value="4"
684,003 (gdb) 
684,003 24-gdb-set --thread-group i1 language auto
684,014 24^done
684,014 (gdb) 
684,014 25-interpreter-exec --thread-group i1 console "show endian"
684,025 ~"The target endianness is set automatically (currently little endian)\n"
684,025 25^done
684,025 (gdb) 
684,025 26-break-insert -t -f app_main

684,039 26^done,bkpt={number="1",type="breakpoint",disp="del",enabled="y",addr="0x4200926c",func="ap\
p_main",file="../main/main.c",fullname="c:\\users\\e0624432\\eclipse-workspace\\ble_sensor_server\\m\
ain\\main.c",line="976",thread-groups=["i1"],times="0",original-location="app_main"}
684,039 (gdb) 
684,039 &"\n"
684,039 ^done
684,039 (gdb) 
684,040 27-exec-continue

684,051 27^running
684,051 *running,thread-id="all"
684,051 (gdb) 
684,473 @"esp32s3.cpu0: Target halted, PC=0x4200926C, debug_reason=00000001\n"
684,476 @"Set GDB target to 'esp32s3.cpu0'\n"
684,499 =breakpoint-modified,bkpt={number="1",type="breakpoint",disp="del",enabled="y",addr="0x42009\
26c",func="app_main",file="../main/main.c",fullname="c:\\users\\e0624432\\eclipse-workspace\\ble_sen\
sor_server\\main\\main.c",line="976",thread-groups=["i1"],times="1",original-location="app_main"}
684,499 =thread-created,id="2",group-id="i1"
684,499 ~"[New Thread 1070544312]\n"
684,499 =thread-created,id="3",group-id="i1"
684,499 ~"[New Thread 1070537736]\n"
684,499 ~"[Switching to Thread 1070542424]\n"
684,499 ~"\n"
684,499 ~"Thread 1 hit Temporary breakpoint 1, app_main () at ../main/main.c:976\n"
684,500 ~"976\t{\n"
684,500 *stopped,reason="breakpoint-hit",disp="del",bkptno="1",frame={addr="0x4200926c",func="app_ma\
in",args=[],file="../main/main.c",fullname="c:\\users\\e0624432\\eclipse-workspace\\ble_sensor_serve\
r\\main\\main.c",line="976"},thread-id="1",stopped-threads="all"
684,500 =breakpoint-deleted,id="1"
684,501 (gdb) 
684,501 &"\n"
684,501 ^done
684,501 (gdb) 
684,918 28-list-thread-groups i1
684,926 29-list-thread-groups
684,938 28^done,threads=[{id="1",target-id="Thread 1070542424",details="Name: main, State: Running @\
CPU0",frame={level="0",addr="0x4200926c",func="app_main",args=[],file="../main/main.c",fullname="c:\\
\users\\e0624432\\eclipse-workspace\\ble_sensor_server\\main\\main.c",line="976"},state="stopped"},{\
id="2",target-id="Thread 1070544312",details="Name: IDLE",frame={level="0",addr="0x4037d624",func="v\
PortTaskWrapper",args=[{name="pxCode",value="0x0"},{name="pvParameters",value="0x0"}],file="C:/Users\
[message truncated to 5 lines. More lines can be set in the Preference->Debug->GDB eclipse preference page.]
684,938 (gdb) 
684,938 29^done,groups=[{id="i1",type="process",pid="42000"}]
684,938 30-thread-select 1
684,938 31-thread-select 1
684,938 (gdb) 
684,939 30^done,new-thread-id="1",frame={level="0",addr="0x4200926c",func="app_main",args=[],file=".\
./main/main.c",fullname="c:\\users\\e0624432\\eclipse-workspace\\ble_sensor_server\\main\\main.c",li\
ne="976"}
684,939 (gdb) 
684,939 31^done,new-thread-id="1",frame={level="0",addr="0x4200926c",func="app_main",args=[],file=".\
./main/main.c",fullname="c:\\users\\e0624432\\eclipse-workspace\\ble_sensor_server\\main\\main.c",li\
ne="976"}
684,939 (gdb) 
685,546 32-list-thread-groups
685,556 32^done,groups=[{id="i1",type="process",pid="42000"}]
685,556 (gdb) 
685,569 33-stack-info-depth --thread 1 11
685,585 33^done,depth="3"
685,585 (gdb) 
685,597 34-stack-select-frame --thread 1 0
685,606 34^done
685,606 (gdb) 
685,620 35-thread-info 1
685,620 36-thread-info 2
685,620 37-thread-info 3
685,627 35^done,threads=[{id="1",target-id="Thread 1070542424",details="Name: main, State: Running @\
CPU0",frame={level="0",addr="0x4200926c",func="app_main",args=[],file="../main/main.c",fullname="c:\\
\users\\e0624432\\eclipse-workspace\\ble_sensor_server\\main\\main.c",line="976"},state="stopped"}]
685,627 (gdb) 
685,630 36^done,threads=[{id="2",target-id="Thread 1070544312",details="Name: IDLE",frame={level="0"\
,addr="0x4037d624",func="vPortTaskWrapper",args=[{name="pxCode",value="0x0"},{name="pvParameters",va\
lue="0x0"}],file="C:/Users/e0624432/Downloads/ESP-IDF/esp-idf-release-v4.3_master/components/freerto\
s/port/xtensa/port.c",fullname="C:\\Users\\e0624432\\Downloads\\ESP-IDF\\esp-idf-release-v4.3_master\
\\components\\freertos\\port\\xtensa\\port.c",line="167"},state="stopped"}]
685,630 (gdb) 
685,631 37^done,threads=[{id="3",target-id="Thread 1070537736",details="Name: esp_timer",frame={leve\
l="0",addr="0x40054584",func="??",args=[]},state="stopped"}]
685,631 (gdb) 
685,646 38-stack-select-frame --thread 1 0
685,653 38^done
685,653 (gdb) 
685,684 39-stack-list-frames --thread 1
685,695 39^done,stack=[frame={level="0",addr="0x4200926c",func="app_main",file="../main/main.c",full\
name="c:\\users\\e0624432\\eclipse-workspace\\ble_sensor_server\\main\\main.c",line="976"},frame={le\
vel="1",addr="0x420938e7",func="main_task",file="C:/Users/e0624432/Downloads/ESP-IDF/esp-idf-release\
-v4.3_master/components/freertos/port/port_common.c",fullname="C:\\Users\\e0624432\\Downloads\\ESP-I\
DF\\esp-idf-release-v4.3_master\\components\\freertos\\port\\port_common.c",line="134"},frame={level\
[message truncated to 5 lines. More lines can be set in the Preference->Debug->GDB eclipse preference page.]
685,695 (gdb) 
691,441 40-exec-next --thread 1 1
691,451 40^running
691,451 *running,thread-id="all"
691,451 (gdb) 
691,471 &"Remote 'g' packet reply is too long (expected 420 bytes, got 556 bytes): 6f920042230006000\
100000000000000230e0600e7380982f02ccf3f0000000001000000210006007c0100008c010a3c50b3ce3f0000cf3fd02cc\
f3f0000ce3fe0bfc93f001bcf3fe01acf3fe87d0042000000008e530082b02ccf3f0000ce3f20ef000000000000c01acf3f0\
00000000000000074fe3780902ccf3f0000ce3f20ef00001400ce3fa01acf3f601ec93fffffffff6af23780702ccf3fdc06c\
e3fdc06ce3f02000000801acf3f601ec93f0000000000000004d806ce3f34000000e006ce3f0002000000020000000000000\
[message truncated to 5 lines. More lines can be set in the Preference->Debug->GDB eclipse preference page.]
691,995 41-thread-select 1
691,999 41^error,msg="Remote 'g' packet reply is too long (expected 420 bytes, got 556 bytes): 6f920\
042230006000100000000000000230e0600e7380982f02ccf3f0000000001000000210006007c0100008c010a3c50b3ce3f0\
000cf3fd02ccf3f0000ce3fe0bfc93f001bcf3fe01acf3fe87d0042000000008e530082b02ccf3f0000ce3f20ef000000000\
000c01acf3f000000000000000074fe3780902ccf3f0000ce3f20ef00001400ce3fa01acf3f601ec93fffffffff6af237807\
02ccf3fdc06ce3fdc06ce3f02000000801acf3f601ec93f0000000000000004d806ce3f34000000e006ce3f0002000000020\
[message truncated to 5 lines. More lines can be set in the Preference->Debug->GDB eclipse preference page.]
691,999 (gdb) 

Logs  of openocd:
C:\Users\e0624432\.espressif\tools\openocd-esp32\v0.10.0-esp32-20210401\openocd-esp32\bin>openocd -s share/openocd/scripts -f interface/ftdi/esp32s2_kaluga_v1.cfg -f target/esp32s3.cfg
Open On-Chip Debugger  v0.10.0-esp32-20210401 (2021-04-01-15:46)
Licensed under GNU GPL v2
For bug reports, read
        http://openocd.org/doc/doxygen/bugs.html
adapter speed: 20000 kHz

WARNING: ESP flash support is disabled!
WARNING: ESP flash support is disabled!
force hard breakpoints
Info : Listening on port 6666 for tcl connections
Info : Listening on port 4444 for telnet connections
Info : ftdi: if you experience problems at higher adapter clocks, try the command "ftdi_tdo_sample_edge falling"
Info : clock speed 20000 kHz
Info : JTAG tap: esp32s3.cpu0 tap/device found: 0x120034e5 (mfg: 0x272 (Tensilica), part: 0x2003, ver: 0x1)
Info : JTAG tap: esp32s3.cpu1 tap/device found: 0x120034e5 (mfg: 0x272 (Tensilica), part: 0x2003, ver: 0x1)
Info : esp32s3.cpu0: Target halted, PC=0x4200926F, debug_reason=00000004
Info : Listening on port 3333 for gdb connections
Info : accepting 'gdb' connection on tcp/3333
Warn : No symbols for FreeRTOS!
Info : New GDB Connection: 1, Target esp32s3.cpu0, state: halted
Info : JTAG tap: esp32s3.cpu0 tap/device found: 0x120034e5 (mfg: 0x272 (Tensilica), part: 0x2003, ver: 0x1)
Info : JTAG tap: esp32s3.cpu1 tap/device found: 0x120034e5 (mfg: 0x272 (Tensilica), part: 0x2003, ver: 0x1)
Info : esp32s3.cpu0: Debug controller was reset.
Info : esp32s3.cpu0: Core was reset.
Info : esp32s3.cpu0: Target halted, PC=0x500000C4, debug_reason=00000000
Info : Set GDB target to 'esp32s3.cpu0'

Info : esp32s3.cpu0: Core was reset.
Info : esp32s3.cpu0: Target halted, PC=0x40000400, debug_reason=00000000
Warn : address 0x3c0a0020 not writable
Warn : address 0x3c0a0120 not writable
Info : esp32s3.cpu0: Target halted, PC=0x4200926C, debug_reason=00000001
Info : Set GDB target to 'esp32s3.cpu0

**Comment by igrr** [comment]
@nitinbhosaleemb It looks like you might have forgot to uncheck "load image" checkbox in the jtag debugging configuration? (See step 9 in https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/jtag-debugging/using-debugger.html#eclipse).

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to shore of feedback, feel free to reopen wit more updates.
