### ISSUE TITLE
How to add external header directories in Cmake (IDFGH-5739)

### ISSUE THREAD

**Issue by dimpalsharm** [espressif/esp-idf#7456]
How we can add external header directories "esp-idf\components\esp_system\port\CMakeLists.txt" in Cmake.

******************Code****************************

target_include_directories(${COMPONENT_LIB} PRIVATE include)
set(srcs "panic_handler.c" "panic_handler_asm.S")
add_prefix(srcs "${CMAKE_CURRENT_LIST_DIR}/" ${srcs})

target_sources(${COMPONENT_LIB} PRIVATE ${srcs})

idf_build_get_property(target IDF_TARGET)
add_subdirectory(${target})

Tried adding like below Code but are getting error.
*********************Code*************************
target_include_directories(${COMPONENT_LIB} PRIVATE include)

set(srcs "panic_handler.c" "panic_handler_asm.S")
**set (include_dirs "header.h")**
add_prefix(srcs "${CMAKE_CURRENT_LIST_DIR}/" ${srcs})

target_sources(${COMPONENT_LIB} PRIVATE ${srcs})

idf_build_get_property(target IDF_TARGET)
add_subdirectory(${target})

**Comment by igrr** [comment]
@dimpalsharm could you please explain what problem you are trying to solve by adding header files to `esp_system` component?

**Comment by Alvin1Zhang** [comment]
@dimpalsharm Thanks for reporting, any updates per https://github.com/espressif/esp-idf/issues/7456#issuecomment-903583702? Thanks.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to short of feedback, feel free to reopen with more details, thanks.
