### ISSUE TITLE
PCNT Example in the IDF is not working correctly (IDFGH-5743)

### ISSUE THREAD

**Issue by aircable** [espressif/esp-idf#7460]
## Environment

- Development Kit:     custom

- Module or chip used:  ESP32-PICO-V3
- IDF version: v4.4-dev-2594-ga20df743f1 (but also V4.2 release)
- Build System:   IDF
- Compiler version: xtensa-esp32-elf-gcc (crosstool-NG esp-2021r1) 8.4.0
- Operating System:   Linux

## Problem Description

The upper and lower limits when configuring pcnt_config_t are not handled correctly

```
   pcnt_config_t dev_config = {
        .pulse_gpio_num = config->phase_a_gpio_num,
        .ctrl_gpio_num = config->phase_b_gpio_num,
        .channel = PCNT_CHANNEL_0,
        .unit = ec11->pcnt_unit,
        .pos_mode = PCNT_COUNT_DEC,
        .neg_mode = PCNT_COUNT_INC,
        .lctrl_mode = PCNT_MODE_REVERSE,
        .hctrl_mode = PCNT_MODE_KEEP,
        .counter_h_lim = EC11_PCNT_DEFAULT_HIGH_LIMIT,
        .counter_l_lim = EC11_PCNT_DEFAULT_LOW_LIMIT,
    };
```

### Expected Behavior

Since PCNT_MODE_KEEP is being used when the counter reaches the upper or lower limits (counter_x_lim) the counter should not change and stay at the high limit.

### Actual Behavior
But the output (below) shows this. It resets the value at high counter level (101) to zero when counter_h_limit is used.
And it does not honor the lower counter level (-1) and should stay there. In fact there is no lower limit. It completely ignores counter_l_lim.

### Steps to reproduce

1. configure example rotary_encoder/components/rotary_encoder/src/rotary_encoder_pcnt_ec11.c
with your rotary encoder GPIO numbers and use these limits, for example.
```
#define EC11_PCNT_DEFAULT_HIGH_LIMIT (101)
#define EC11_PCNT_DEFAULT_LOW_LIMIT  (-1)
```
Expected behavior is that the counter values should stay between 0 and 100.

## Debug Logs

```
I (316) example: Encoder value: 0
I (1316) example: Encoder value: 0
I (6316) example: Encoder value: 48
I (7316) example: Encoder value: 84
I (8316) example: Encoder value: 92
I (9316) example: Encoder value: 98
I (10316) example: Encoder value: 5
I (11316) example: Encoder value: 16
I (12316) example: Encoder value: -15
I (13316) example: Encoder value: -40
I (14316) example: Encoder value: -96
I (15316) example: Encoder value: -149
I (16316) example: Encoder value: -98
I (17316) example: Encoder value: -53
I (18316) example: Encoder value: -15
I (19316) example: Encoder value: 17
I (20316) example: Encoder value: 32
I (21316) example: Encoder value: 55
I (22316) example: Encoder value: 98
I (23316) example: Encoder value: 127
I (24316) example: Encoder value: 59
I (25316) example: Encoder value: 103
I (26316) example: Encoder value: 123
```

**Comment by aircable** [comment]
WORKAROUND:

define the limits like this:
```
#define EC11_PCNT_DEFAULT_HIGH_LIMIT (1)
#define EC11_PCNT_DEFAULT_LOW_LIMIT  (-1)
```
Then you get interrupts whenever increment or decrement of one count is being recognized.
Implement the interrupt routine like this, with your own global variable `int rotary_value`.
```
static void ec11_pcnt_overflow_handler(void *arg)
{
    if (status & PCNT_EVT_H_LIM) {
        rotary_value++;
    } else if (status & PCNT_EVT_L_LIM) {
        rotary_value--;
    } 
}
```
Manage upper and lower limit in your application code and you can use the PCNT for your rotary encoder.
```
    // limit the values 
    if( rotary_value > ROTARY_MAX_VALUE ) rotary_value = ROTARY_MAX_VALUE;
    if( rotary_value <= ROTARY_MIN_VALUE ) rotary_value = ROTARY_MIN_VALUE;
```

SUGGESTION FOR ESPRESSIF DEVELOPERS:

Since the HAL implementation of the PCNT is not available for normal mortals, just remove the values the PCNT manages, including the managing of the upper and lower limits, and just provide events for the users, so they can manage whatever their application needs. I bet it's simpler and more flexible.

CHEERS
Juergen

**Comment by suda-morris** [comment]
> Since PCNT_MODE_KEEP is being used when the counter reaches the upper or lower limits (counter_x_lim) the counter should not change and stay at the high limit.

I don't think the hardware will act in this way. `PCNT_MODE_KEEP` is saying `keep the current count mode` instead of `hold the count value`. 
If the limit value is reached, it will returns back to zero, it is a hardware behavior.

**Comment by aircable** [comment]
So, you mean, for a rotary encoder implementation, the original example is useless? Jumping back to zero at limit is not what a rotary encoder example would want, correct? Think of e.g. a volume control rotary button.

How would you propose to implement the example then?

**Comment by suda-morris** [comment]
you can make use of the threshold and/or limit interrupt, where you can handle the overflow or saturation by software. The original rotary example is useful for measuring DC motor speed as far as I can tell. See https://github.com/espressif/esp-idf/tree/master/examples/peripherals/mcpwm/mcpwm_brushed_dc_control

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, feel free to reopen.

**Comment by aaaaahaaaaa** [comment]
Facing the same challenge. I have to say that the API doesn't make a lot of sense to me either in terms of value proposition. If the range forbids 0 as a lower bound, always reset to 0 in both direction AND/OR doesn't allow to hold the counter value, then what is the point of configuring the range at all?
