### ISSUE TITLE
Documentation of the esp-prog with esp-boards. (IDFGH-5767)

### ISSUE THREAD

**Issue by Raghav3107** [espressif/esp-idf#7475]
**Is your feature request related to a problem?**
No.

I was doing the set to debug the esp-wroom-32D with esp-prog for that I was searching the document on official esp document sites. But I did't found much documentation on this.

Request:
Can you add documentation to debug esp boards with esp-prog with pics. If possible add some videos for setup and example of debugs.

Regards,
Raghav Jha

**Comment by krzychb** [comment]
Hi @Raghav3107, in case you did not find it already, a generic JTAG debugging documentation is available in:

- [Introduction to the ESP-Prog Board](https://docs.espressif.com/projects/espressif-esp-iot-solution/en/latest/hw-reference/ESP-Prog_guide.html)
- [JTAG Debugging](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/jtag-debugging/index.html)

By "set to debug" do you mean wiring and configuration to debug or something else? By "esp-wroom-32D" do you mean set to debug a separate [module](https://www.espressif.com/en/products/modules) or a [developement board](https://www.espressif.com/en/products/devkits) that contains this module?

**Comment by Raghav3107** [comment]
@krzychb  thanks for the reply.

> * [Introduction to the ESP-Prog Board](https://docs.espressif.com/projects/espressif-esp-iot-solution/en/latest/hw-reference/ESP-Prog_guide.html)
> * [JTAG Debugging](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/jtag-debugging/index.html)

I checked all this documents, i m able to configure the ESP-PROG with esp32.
 But JTAG documents is little bit complicated and  esp-prog documentation have only the intro part.

It will be better if you add some example videos where you show how to configure the jtag and esp-prog with esp32.

Thanks for the help!!
