### ISSUE TITLE
Interrupts

### ISSUE THREAD

**Issue by chegewara** [espressif/esp-idf#748]
I have modified a little bit example gpio to generate interrupts from buttons click and not from gpio state change, also ive changed intr_type from ANYEDGE to POS/NEGEDGE and this is what ive found:
- 1 click button sometimes generates interrupt on both edges, 

Additionally, but maybe its problem with my program sometimes 1 click generates few interrupts.

**Comment by Spritetm** [comment]
Do you debounce your button in hardware? If not, what you're seeing is contact bounce.

**Comment by chegewara** [comment]
What do you mean?

**Comment by Spritetm** [comment]
https://www.google.com.hk/?gws_rd=cr,ssl#safe=strict&q=contact+bounce

**Comment by chegewara** [comment]
Then it not software but hardware issue?

**Comment by Spritetm** [comment]
The issue originates in your hardware, yes.

**Comment by chegewara** [comment]
Thanks.

**Comment by chegewara** [comment]
One more question,  button debouncingdoes not explain why with POS/NEGEDGE intr_type sometimes are generated interrupts on both edges?

**Comment by Spritetm** [comment]
How do you make sure you're not actually feeding positive and negative edges into your GPIO? What is your signal source?

**Comment by chegewara** [comment]
Im not cause its an ordinary cheap button. The point is i want interrupt to be triggered only on one edge, thats why is intr_type parameter for as i understand. But ocasionally vallue read from pin that triggered interrupt is not the one im expecting. 
As i understand, with pin pullup and intr_type=POSEDGE, interrupt could be triggered when pin state is changing from low to high, means pin level=1. Or am i wrong.

**Comment by Spritetm** [comment]
Again, contact bounce. When you close or open a switch, the contact makes (positive edge) and breaks (negative edge) a bunch of times.

**Comment by chegewara** [comment]
Again thanks, and sorry for bothering.
