### ISSUE TITLE
wprintf problem (IDFGH-5772)

### ISSUE THREAD

**Issue by lion1986** [espressif/esp-idf#7480]
demo code:
wchar_t wStr[] = L"demo wchat_t";
wprintf(L"wStr(%d):%s\n", wcslen(wStr), wStr);

print result: 
**wStr(12):d**
just only print the first char,  the string length is right.

**Comment by negativekelvin** [comment]
>%ls shall be used for wide strings (and not %s).

**Comment by Alvin1Zhang** [comment]
Thanks for reporting. Would you please help provide more details as suggested in the [issue template](https://github.com/espressif/esp-idf/issues/new?assignees=&labels=&template=bug_report.md&title=)? Information like elf, sdk configuration, backtrace, log outputs, commit ID, hardware and etc. would help us debug further. Thanks.

**Comment by lion1986** [comment]
> 
> 
> > %ls shall be used for wide strings (and not %s).

When use %ls in wprintf function, the result is right. But when use %ls in printf function, the result is not right(just like %s in wprintf, only print the first char).

**Comment by ESP-Marius** [comment]
> When use %ls in wprintf function, the result is right. But when use %ls in printf function, the result is not right(just like %s in wprintf, only print the first char).

Support for wide character support in streams was  disabled in [0dbbbbf68](https://github.com/espressif/crosstool-NG/commit/0dbbbbf68879ea2af2052b0c76f181cdb29baa39)

Currently there is no specific plans to re-enable this. Closing issue as the original issue regarding `wprintf` was already resolved.
