### ISSUE TITLE
Socket leak on "esp_https_server" component (IDFGH-5778)

### ISSUE THREAD

**Issue by baldhead69** [espressif/esp-idf#7486]
Hi,

I am writing a websocket server and i did some tests opening and closing connections with the server.

After about 9 requests(opening and closing) the server rejects new connections.
The registered closed callback function(closed_socket_handler) is called in all 9 closed sockets.

Error:
```c
    httpd: httpd_accept_conn: error in accept (23)
    httpd: httpd_server: error accepting new connection
```
Config:
```c
    httpd_ssl_config_t config = HTTPD_SSL_CONFIG_DEFAULT();  
    config.httpd.core_id = tskNO_AFFINITY; 
    config.httpd.max_open_sockets = 5;
    config.httpd.task_priority =  tskIDLE_PRIORITY + 5;      
    config.httpd.close_fn = closed_socket_handler;
    config.transport_mode = HTTPD_SSL_TRANSPORT_INSECURE;   
    config.httpd.lru_purge_enable = false;  // The lib limits to 5 openned sockets, but closes oldest socket and opens another if "lru_purge_enable = true".  
```
Why the the server are rejecting new connections if callback "closed_socket_handler" are called in all times ?

Some help are welcome.

Thank's.

**Comment by ESP-YJM** [comment]
@baldhead69 When we close socket, if socket not be closed by `Four-way handshake`, the socket will enter `Time-wait` state, maybe 120s (not sure). In this state,  the socket will not be completely released, and the socket fd will still be occupied. For solve this issue, you can use `SO_LINGER` option and force close the socket.

**Comment by ESP-YJM** [comment]
@baldhead69 Could you please set `lru_purge_enable ` true in `httpd_config_t ` and try.

**Comment by baldhead69** [comment]
> @baldhead69 When we close socket, if socket not be closed by `Four-way handshake`, the socket will enter `Time-wait` state, maybe 120s (not sure). In this state, the socket will not be completely released, and the socket fd will still be occupied. For solve this issue, you can use `SO_LINGER` option and force close the socket.

How to do this and where ?

Thank's.

**Comment by baldhead69** [comment]
I enabled "Enable SO_LINGER processing" in menuconfig "Component config->LWIP", but not solved.

I think i need set SO_LINGER = true and/or TIME_WAIT = 0, but i don't know where or how.

**Comment by baldhead69** [comment]
> @baldhead69 Could you please set `lru_purge_enable ` true in `httpd_config_t ` and try.

Not solved, same problem.

After nine connection:
```c
W (00:00:39.136) httpd: httpd_accept_conn: error in accept (23)
W (00:00:39.136) httpd: httpd_server: error accepting new connection
W (00:00:44.358) httpd: httpd_accept_conn: error in accept (23)
W (00:00:44.358) httpd: httpd_server: error accepting new connection
W (00:03:18.262) httpd: httpd_accept_conn: error in accept (23)
W (00:03:18.262) httpd: httpd_server: error accepting new connection
```
![Jmeter WebSocket close](https://user-images.githubusercontent.com/17574492/131597631-37521944-b6b2-454d-b7b3-bc194d9f373e.png)
![Wireshark WebSocket close](https://user-images.githubusercontent.com/17574492/131597944-b4ea9c82-6099-45e8-a668-f00ab071601c.png)

**Comment by ESP-YJM** [comment]
> 
> 
> I enabled "Enable SO_LINGER processing" in menuconfig "Component config->LWIP", but not solved.
> 
> I think i need set SO_LINGER = true and/or TIME_WAIT = 0, but i don't know where or how.

@baldhead69 You can refer to https://esp32.com/viewtopic.php?f=13&t=20705

**Comment by baldhead69** [comment]
> @baldhead69 When we close socket, if socket not be closed by `Four-way handshake`, the socket will enter `Time-wait` state, maybe 120s (not sure). In this state, the socket will not be completely released, and the socket fd will still be occupied. For solve this issue, you can use `SO_LINGER` option and force close the socket.

Looks like it's solved.

**Comment by baldhead69** [comment]
@ESP-YJM 

I don't know why closing the connection by Jmeter is returning an error, maybe the websocket server is not responding correctly with a closing frame.

I must open a new issue for this ?

**Comment by ESP-YJM** [comment]
> 
> 
> > @baldhead69 When we close socket, if socket not be closed by `Four-way handshake`, the socket will enter `Time-wait` state, maybe 120s (not sure). In this state, the socket will not be completely released, and the socket fd will still be occupied. For solve this issue, you can use `SO_LINGER` option and force close the socket.
> 
> Looks like it's solved.

Glad to hear the good news.  From the wireshark packet, i think the websocket layer close is right. But need check the TCP layer close. I think you can follow this issue and no need open a new.

**Comment by baldhead69** [comment]
@ESP-YJM 

I did two tests.

1. First test: open and close connection without user(i) send a websocket close frame.

![Jmeter_open_close](https://user-images.githubusercontent.com/17574492/131614450-87a02a3e-1d51-4e25-a1be-abf699e75c2c.png)

The server are not sending a websocket close frame(ie, not a clean websocket close protocol).
![Wireshark open_close](https://user-images.githubusercontent.com/17574492/131615371-d1108150-2234-4940-807e-e375ecbfe674.png)

2. Second test: open and close connection with user(i) send a websocket close frame.

![Jmeter_open_send_close](https://user-images.githubusercontent.com/17574492/131615410-86090897-1fac-4ef2-9a25-f4b7d3287388.png)

The server send a websocket close frame(ie, a clean websocket close protocol).
![Wireshark open_send_close](https://user-images.githubusercontent.com/17574492/131615435-b5c5c4ee-111d-40cb-b578-68b52f1fc595.png)

**Comment by baldhead69** [comment]
@ESP-YJM 

I use visual studio code with esp-idf.
The code compile ok, but visual studio code show that not encounter some data structs.

I include "#include <lwip/sockets.h>", but inside this file appear in line 44 that "LWIP_SOCKET" is not enabled.

Do you know how/where i can enable "LWIP_SOCKET"  ???

Thank's.

![lwip_socket](https://user-images.githubusercontent.com/17574492/132742960-27c67b40-f328-4603-9f33-9db2de90d492.png)

![linger](https://user-images.githubusercontent.com/17574492/132742566-49c56dae-3ca9-411d-b2af-74692bf5cf2c.png)

**Comment by ESP-YJM** [comment]
@baldhead69 I think LWIP_SOCKET is enabled in opt.h https://github.com/espressif/esp-lwip/blob/2c9c531f0a7e0ee536db9de4f9dc54e453712087/src/include/lwip/opt.h#L1985

**Comment by baldhead69** [comment]
@ESP-YJM 

I think visual studio code are buggy, but i dont have assurance.

![lwipopts h](https://user-images.githubusercontent.com/17574492/133169115-cfe6d725-58c0-43a7-aded-c99c26bbd1b8.png)

![opt h](https://user-images.githubusercontent.com/17574492/133169117-3b8fb0ef-ec8d-404b-8d5d-4f8d9387349e.png)

**Comment by ESP-YJM** [comment]
@baldhead69 I think you no need care about the display in vscode. `C:\esp-idf\components\coap\libcoap\examples\lwip\lwipopts.h` we don't use it. If you want to know whether `LWIP_SOCKET` defined, you can do some build test.

**Comment by baldhead69** [comment]
> @baldhead69 I think you no need care about the display in vscode. `C:\esp-idf\components\coap\libcoap\examples\lwip\lwipopts.h` we don't use it. If you want to know whether `LWIP_SOCKET` defined, you can do some build test.

Yes, but it's annoying to see the failure in the code if you use this feature to find errors in the program.

**Comment by ESP-YJM** [comment]
> 
> 
> > @baldhead69 I think you no need care about the display in vscode. `C:\esp-idf\components\coap\libcoap\examples\lwip\lwipopts.h` we don't use it. If you want to know whether `LWIP_SOCKET` defined, you can do some build test.
> 
> Yes, but it's annoying to see the failure in the code if you use this feature to find errors in the program.

I agree that but it is difficult to make vscode identify which macro is defined, due to some macro generated when make build. I think this topic is not related to the title issue. Do you have any doubt or comments about title issue? If no, i think we can close it and open other topic issue to disscuss vscode display.

**Comment by baldhead69** [comment]
@ESP-YJM 

The close frame issue remains to be resolved.

May be you can close here and you can continue here with the close frame:
https://github.com/espressif/esp-idf/issues/7493#issuecomment-912203846

The uri handler are not called when client close frame and the "background websocket layer" do not send a close message to do a clean close. 

Thank's.

**Comment by ESP-YJM** [comment]
@baldhead69 Yes, current version not support do a clean close. I will keep #7493 open and fixed in this issue tickets. And #7486 maybe can be closed. You can help close #7486.

**Comment by sxsx2yzyz** [comment]
> > I enabled "Enable SO_LINGER processing" in menuconfig "Component config->LWIP", but not solved.
> > I think i need set SO_LINGER = true and/or TIME_WAIT = 0, but i don't know where or how.
> 
> @baldhead69 You can refer to https://esp32.com/viewtopic.php?f=13&t=20705

After I upgraded my idf version from 4.2 to 5.0, I encountered the same problem.This post helped me.Thanks
