### ISSUE TITLE
esp_partition_find_first() is not returning flash_chip details  (IDFGH-5782)

### ISSUE THREAD

**Issue by Aadya76** [espressif/esp-idf#7490]
## Environment

- Development Kit:      ESP32_MINI-1
- Kit version :
- Module or chip used:  ESP32
- IDF version : v4.2.1
- Build System:         [Make|CMake|idf.py]
- Compiler version : xtensa-esp32-elf-gcc( crosstool-NG esp-2020r3 ) 8.4.0
- Operating System:    Windows
- (Windows only) environment type: ESP Command Prompt
- Using an IDE?: Eclipse
- Power Supply:        USB

## Problem Description
![image](https://user-images.githubusercontent.com/89783687/131346977-68b96dd8-bba6-4986-ac84-86c4c17b48e7.png)

**esp_partition_find_first()** does not return **flash_chip** details but it is required by next function call i.e **esp_partition_mmap()**  to validate the partition before memory mapping.
We required this while updating the esp_ota_set_boot_partition( ) function. 
esp_ota_set_boot_partition() is calling esp_rewrite_ota_data() inside its function which is then calling read_otadata( ) function.

**esp_partition_mmap()**  is returning error( flash_chip is returning value 0x00 ) at highlighted line as shown in the below image 
![image](https://user-images.githubusercontent.com/89783687/131351642-c43eabf3-a92c-4842-8b84-07507308a0d2.png)

### Expected Behavior
![image](https://user-images.githubusercontent.com/89783687/131339852-55974c5a-1c7c-40ae-9601-50aeea18d59a.png)
After calling **esp_partition_find_first()** flash_chip should return values which can be used by **esp_partition_mmap()**

### Actual Behavior
![image](https://user-images.githubusercontent.com/89783687/131340227-ff2ec847-4a0c-4d73-96ca-85fd5353f854.png)
But after calling **esp_partition_find_first()** flash_chip is returning 0x00 as shown in above image.
### Steps to reproduce

1. We are fetching the partition table 
2. calling the esp_ota_set_boot_partition() function 

// If possible, attach a picture of your setup/wiring here.

### Code to reproduce this issue

```cpp
// the code should be wrapped in the ```cpp tag so that it will be displayed better.
#include "esp_log.h"

void app_main()
{
      const esp_partition_t *next_partition = NULL;
      next_partition = esp_ota_get_next_partition( NULL );
      esp_err_t err =  esp_ota_set_boot_partition( next_partition );
}

```
// If your code is longer than 30 lines, [GIST](https://gist.github.com) is preferred.

## Debug Logs

```
Debug log goes here, should contain the backtrace, as well as the reset source if it is a crash.
Please copy the plain text here for us to search the error log. Or attach the complete logs but leave the main part here if the log is *too* long.
```

## Other items if possible

- [ ] sdkconfig file (attach the sdkconfig file from your project folder)
- [ ] elf file in the ``build`` folder (**note this may contain all the code details and symbols of your project.**)
- [ ] coredump (This provides stacks of tasks.)

**Comment by hmalpani** [comment]
@Aadya76 I am using this code to reproduce the issue and it seems to be working fine for me. 

```
#include "esp_log.h"
#include "esp_partition.h"
#include "esp_ota_ops.h"
void app_main()
{
      const esp_partition_t *next_partition = esp_ota_get_next_update_partition( NULL );
      if(next_partition != NULL)
      {
            printf("next_partition \t esp_partition_t* : %p\n
                    flash_chip \t esp_flash_t* : %p\n
                    host \t spi_flash_host_driver_t* : %p\n
                    chip_drv \t spi_flash_chip_t* : %p\n
                    os_func \t esp_flash_os_functions_t* : %p\n
                    os_func_data \t void* : %p\n
                    size \t uint32_t : %u\n",
                    next_partition, next_partition->flash_chip, next_partition->flash_chip->host, 
                    next_partition->flash_chip->chip_drv, next_partition->flash_chip->os_func, 
                    next_partition->flash_chip->os_func_data,next_partition->flash_chip->size);
      }
      //esp_err_t err =  esp_ota_set_boot_partition( next_partition );
}
```

I got this output:

```
next_partition	esp_partition_t*          : 0x3ffb63a4
flash_chip	esp_flash_t*              : 0x3ffb1264
host	        spi_flash_host_driver_t*  : 0x3ffb1280
chip_drv	spi_flash_chip_t*         : 0x3ffb1f24
os_func	        esp_flash_os_functions_t* : 0x3ffb12dc
os_func_data	void*                     : 0x3ffb12f0
size	        uint32_t                  : 4194304
```

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to short of feedback, feel free to reopen.
