### ISSUE TITLE
can't definition 2 function with diferent parameters (IDFGH-5784)

### ISSUE THREAD

**Issue by hdpklm** [espressif/esp-idf#7492]
```
void intit() {}
void intit(int x) {}
```

```
../main/hello_world_main.c:17:6: error: redefinition of 'intit'
 void intit(int x) {}
      ^~~~~
../main/hello_world_main.c:16:6: note: previous definition of 'intit' was here
 void intit() {}
```

**Comment by hdpklm** [comment]
and can't define a function with default parameters 

```
../main/hello_world_main.c:16:18: error: expected ';', ',' or ')' before '=' token
 void intit(int x = 0) {}
```

**Comment by igrr** [comment]
Function overloading and default arguments are both features of C++, while your source file has `.c` extension.

Please rename your file to `hello_world_main.cpp` (and change the name in CMakeLists.txt accordingly), then these features will be working.

**Comment by hdpklm** [comment]
Ok thank you so mutch

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, feel free to reopen.
