### ISSUE TITLE
Missed extern "C" directive in the dhcpserver.h (IDFGH-5786)

### ISSUE THREAD

**Issue by a1exande** [espressif/esp-idf#7494]
Please, add the 'extern "C" directive to the "dhcpserver.h" header.
Due to its absence, a project builds successfully, but a link error "undefined reference to `dhcps_set_option_info(unsigned char, void*, unsigned int)..." occurs.
I had such error in [mmMikeKn/ESP32-WiFi-tool](https://github.com/mmMikeKn/ESP32-WiFi-tool.git) with esp-idf, but according to [link ](https://github.com/espressif/arduino-esp32/issues/5117) similar error occurred on Arduino IDE with Platform.io as well.

**Comment by ESP-YJM** [comment]
@a1exande Thanks for reporting it. We will fix it.
