### ISSUE TITLE
Clash on definition of O_NONBLOCK

### ISSUE THREAD

**Issue by nkolban** [espressif/esp-idf#75]
If we have a C source file that includes both `sockets.h` and `sys/fcntl.h` we have a macro re-definition error on the macro symbol `O_NONBLOCK`.

If we look in sockets.h, we find:

```
#define O_NONBLOCK  1 /* nonblocking I/O */
```

and if we look in `sys/fcntl.h` we find it includes `_default_fcntl.h` which defines

```
#define	O_NONBLOCK	_FNONBLOCK
```

**Comment by igrr** [comment]
I suppose we can fix this by adding `#include <sys/fcntl.h>` near the top of `lwipopts.h`.

**Comment by igrr** [comment]
Fixed in master
