### ISSUE TITLE
What is time information for SPI FLASH (External Flash) Read/Write/Erase Operation in ESP32. (IDFGH-5809)

### ISSUE THREAD

**Issue by VardhamanJain** [espressif/esp-idf#7516]
Hello All,
I want to know from where we can able find the SPI FLASH (Embedded External Flash) Read/Write/Erase operation timing details ?? ..
What is chip part number of Embedded External Flash ???

BOARD: ESP32-mini-1, ESP32-Wrover-E.

Kindly help us, We require urgent this information for our project completion.

Thank you in advance.

**Comment by ginkgm** [comment]
Hi @VardhamanJain ,

This is relative HW question, not totally belongs to IDF framework.

If you are using ESP32-Wrover-E, you may have different kinds of embedded main SPI Flash. Please contact our support team (sales@espressif.com) to get more accurate information.

Michael

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, feel free to reopen.
