### ISSUE TITLE
USB CDC setting in sdk configuration doesnt do anything (gets overwritten with default on compilation) (IDFGH-5828)

### ISSUE THREAD

**Issue by xBiohazardx** [espressif/esp-idf#7532]
## Environment

- Development Kit:     ESP32-DevKitC
- Kit version v3
- Module or chip used:  ESP32-WROOM-32
- IDF version (run ``git describe --tags`` to find it): v4.3
- Build System:         idf.py
- Operating System: Ubuntu
- Using an IDE?: VS-Code with esp idf extension

## Problem Description

USB CDC option gets overwritten by default value when recompiling

### Expected Behavior

USB CDC option to stay in sdkconfig file for compilation

**Comment by dobairoland** [comment]
Hi @xBiohazardx. If you have an ESP32 then this is expected behavior. ESP32 doesn't have a native USB. It has serial port which is connect with an UART-to-USB bridge to an USB connector. Look for "serial" connection in the documentation/datasheet for whatever you want to achieve.

**Comment by xBiohazardx** [comment]
I have got an ESP32-c3-wroom-02. It has builtin usb and i get the bootloader output to the acm port. Its just the (usb-cdc) sdk setting (to pipe the standard output to the builtin usb instead of uart) which gets overwritten.

**Comment by igrr** [comment]
For ESP32-C3, you need to enable `CONFIG_ESP_CONSOLE_USB_SERIAL_JTAG ` option in sdkconfig (see https://docs.espressif.com/projects/esp-idf/en/latest/esp32c3/api-guides/usb-serial-jtag-console.html#software-configuration).

`CONFIG_ESP_CONSOLE_USB_CDC` is only valid for chips with a USB_OTG peripheral (i.e. a fully programmable USB Device/Host controller). This option is mentioned in ESP32-S2 documentation, for example: https://docs.espressif.com/projects/esp-idf/en/latest/esp32s2/api-guides/usb-otg-console.html#software-configuration.

The reason why these are different is that `CONFIG_ESP_CONSOLE_USB_CDC` relies on software CDC implementation, while `CONFIG_ESP_CONSOLE_USB_SERIAL_JTAG` uses the hardware one.

**Comment by xBiohazardx** [comment]
The CONFIG_ESP_CONSOLE_USB_SERIAL_JTAG options seems to be correct. However this option is not available in menuconfig. (I tried it with version 4.3.1 and the latest one)

**Comment by igrr** [comment]
@xBiohazardx have you done `idf.py set-target esp32c3` before running `idf.py menuconfig`?

If yes, you can find it under Component config > ESP System Settings > Channel for console output. You can use the search feature — press `/` and then start typing the option name (or part of it) — this will bring up this option in the list.


<img width="891" alt="Screenshot 2021-09-10 at 09 51 47" src="https://user-images.githubusercontent.com/4349050/132819848-e6f02dfa-0ddf-4ffd-9949-bb96b4730916.png">
<img width="891" alt="Screenshot 2021-09-10 at 09 52 53" src="https://user-images.githubusercontent.com/4349050/132819857-c26cd0e3-4825-427c-82bf-b5cd23374e7c.png">

**Comment by xBiohazardx** [comment]
Thank you for your reply and sorry for my bad english. I have already set the target to esp32c3.

There is no setting "Channel for console output" in ESP System Settings.
![image](https://user-images.githubusercontent.com/36756950/132822428-dd17ff3a-11bc-43ac-8bdd-be2efb4ca8f8.png)

The setting is in "Common ESP-related"
![image](https://user-images.githubusercontent.com/36756950/132822521-565294d9-50ec-42b4-9710-6f23c0185d48.png)

However there is no "USB Serial/JTAG Controller" option:
![image](https://user-images.githubusercontent.com/36756950/132822703-925b8cce-fbaf-466e-b3e4-6227a842b4d0.png)

**Comment by igrr** [comment]
@xBiohazardx I'm sorry I missed the fact that you are using v4.3.1. You are right, v4.3.1 doesn't include "usb serial JTAG" feature. It is only available in latest master branch.

**Comment by xBiohazardx** [comment]
Switched to the master branch and now its working properly. Thank you for your help.
