### ISSUE TITLE
MQTT library build error if CONFIG_WS_TRANSPORT is not set (IDFGH-5833)

### ISSUE THREAD

**Issue by AxelLin** [espressif/esp-idf#7535]
## Environment

Module or chip used: ESP32-WROOM-32E
IDF version: v4.4-dev-2977-gdd491ee85136
Build System: idf.py
Compiler version: xtensa-esp32-elf-gcc (crosstool-NG esp-2021r1) 8.4.0
Operating System: Linux
Power Supply: USB

## Problem Description

Got below build error when CONFIG_WS_TRANSPORT=n:

/home/axel/.espressif/tools/xtensa-esp32-elf/esp-2021r1-8.4.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: esp-idf/mqtt/libmqtt.a(mqtt_client.c.obj):(.literal.esp_mqtt_client_set_uri+0x1c): undefined reference to `esp_transport_ws_set_path'
/home/axel/.espressif/tools/xtensa-esp32-elf/esp-2021r1-8.4.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: esp-idf/mqtt/libmqtt.a(mqtt_client.c.obj): in function `esp_mqtt_client_set_uri':
/home/axel/esp/esp-idf/components/mqtt/esp-mqtt/mqtt_client.c:854: undefined reference to `esp_transport_ws_set_path'
/home/axel/.espressif/tools/xtensa-esp32-elf/esp-2021r1-8.4.0/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: /home/axel/esp/esp-idf/components/mqtt/esp-mqtt/mqtt_client.c:856: undefined reference to `esp_transport_ws_set_path'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
ninja failed with exit code 1

**Comment by david-cermak** [comment]
@AxelLin Thanks for the report and sorry for the regression, will fix.

Linking the fixing PR in `esp-mqtt` https://github.com/espressif/esp-mqtt/pull/198

**Comment by AxelLin** [comment]
Hi @david-cermak 

The PR is not related to this issue.
mqtt_client.c:854: undefined reference to esp_transport_ws_set_path'.
So esp_transport_ws_set_path needs propler #ifdef guard if MQTT_TRANSPORT_WEBSOCKET=n / MQTT_TRANSPORT_WEBSOCKET_SECURE=n.
