### ISSUE TITLE
Cannot compile header in C++ (mcpwm_struct.h) (IDFGH-5840)

### ISSUE THREAD

**Issue by pawel-soja** [espressif/esp-idf#7542]
The name `operator` for the variable is not valid for C++.

https://github.com/espressif/esp-idf/blob/dd491ee8513689191421943b737a31c159c91d17/components/soc/esp32/include/soc/mcpwm_struct.h#L1443

Compile error:
```
idf/master/components/soc/esp32/include/soc/mcpwm_struct.h:1443:43: error: expected type-specifier before '[' token
     volatile mcpwm_operator_reg_t operator[3];
```

**Comment by SalimTerryLi** [comment]
Hi @pawel-soja Thanks for reporting that, and the fix is coming in soon :)
