### ISSUE TITLE
When LM Inquiry status is set to Idle, but still receives an Inquiry Response again, a PANIC WDT is produced from lm_task (IDFGH-5850)

### ISSUE THREAD

**Issue by andurbal** [espressif/esp-idf#7551]
Development Kit: m5stack grey and m5stackcore2 used with ESPIDF
Module or chip used: ESP32 chip revision: 3
IDF version: V4.2
Build System: CMake
Compiler version : xtensa-esp32-elf-gcc (crosstool-NG esp-2020r3) 8.4.0
Operating System: WINDOWS
Using an IDE?: YES VISUAL CODE WITH ESPRESSIF EXTENSION
Power Supply: USB

## Problem Description

// ASSERT_ERR(0), in lm_task.c at line 3997
// Guru Meditation Error: Core 0 panic'ed (Interrupt wdt timeout on CPU0).

This error is produced when BT Controller has done the inquiry procedure and set the LM Inquiry status to Idle, but still receives an Inquiry Response again

All is explained in this old thread
https://github.com/espressif/esp-idf/issues/6759

Partially solved in 4.2, replacing libbtdm_app.a by a patched one.
(see : https://github.com/espressif/esp-idf/issues/6759)

Upgrading to ESP IDF 4.3, has still this BUG. 
Replacing libbtdm_app.a (as done in 4.2) gives then a Bluetooth Init Error.

esp_bt_controller_config_t cfg = BT_CONTROLLER_INIT_CONFIG_DEFAULT();
BT_result = esp_bt_controller_init(&cfg));
Gives a BT_result of ESP_ERR_INVALID_ARG

### Expected Behavior

BT Controller must not cause an unexpected reset in lm_task.c at line 3997, when set the LM Inquiry status to Idle, but still receives an Inquiry Response.

### Actual Behavior

Causes an unexpected reset in lm_task.c at line 3997
ASSERT_ERR(0), in lm_task.c at line 3997
Guru Meditation Error: Core 0 panic'ed (Interrupt wdt timeout on CPU0).

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, sorry for slow turnaround, fix on release/4.2 is available at https://github.com/espressif/esp-idf/commit/5a4d4a01db99c3ca66e9cbe2fabfb6029a51a4b4 and on master branch is https://github.com/espressif/esp-idf/commit/23dd7a4a29555a8ba2609f6c4b2ce9ae525dd45d, feel free to reopen.
