### ISSUE TITLE
When classic Bluetooth is turned on at the same time, the number of ble scan results is greatly reduced (IDFGH-5860)

### ISSUE THREAD

**Issue by wgcod** [espressif/esp-idf#7560]
- Module or chip used: ESP32-WROVER-B
- IDF version: v4.2-dev-1126-gd85d3d969
- Build System:        Make
- Compiler version : xtensa-esp32-elf-gcc (crosstool-NG esp-2020r2) 8.2.0
- Operating System:    Linux
- Using an IDE?: No
- Power Supply:         USB

## Problem Description

When in btdm mode, classic Bluetooth and ble turn on scanning at the same time. Very little ble adv data was scanned.

If only ble is turned on, there are about 150 scan results in 1 second. However, if you also turn on classic Bluetooth, the number is only 10.

Is it a configuration problem?

Now I just need to scan the surrounding Bluetooth devices without connecting. Is there a way to search more data in btdm mode?

**Comment by BetterJincheng** [comment]
Hi, @wgcod,

We are handling this issue and have some problems to reproduce the scenario. It will do great help if you attach your demo here.

Many thanks

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to short of feedback, feel free to reopen with more updates. Thanks.
