### ISSUE TITLE
esp_http_client_open() causes huge memory consumption (IDFGH-5864)

### ISSUE THREAD

**Issue by ac-frg** [espressif/esp-idf#7563]
`
// Free heap after calling esp_http_client_open() (reading 512 bytes once)
D (57423) SYSTEM_MNGR: (55) free heap: internal 25136 - external 4122820
// Free heap after calling esp_http_client_cleanup()
D (58425) SYSTEM_MNGR: (56) free heap: internal 98268 - external 4124496

`
I am running esp-idf version 4.2.2
Is this a bug? If no, is there a possibility to use external SPIRAM instead for this?

**Comment by ESP-YJM** [comment]
@ac-frg Please help check
1. Before esp_http_client_open, how much free heap is there?
2. Do this http connection is over TLS, if yes, is it two-way authentication?
3. For how to use SPIRAM, you can refer to https://docs.espressif.com/projects/esp-idf/en/v4.2.2/esp32/api-guides/external-ram.html

**Comment by ac-frg** [comment]
1) Free heap: internal 98268 - external 4124496
2) Yes
