### ISSUE TITLE
controller_hci_uart_esp32c3 demo bug (IDFGH-5869)

### ISSUE THREAD

**Issue by donny681** [espressif/esp-idf#7568]
## Environment
- Module or chip used: ESP32C3
- IDF version (run ``git describe --tags`` to find it):
    //master 220590d599e134d7a5e7f1e683cc4550349ffbf8
- Build System:         |idf.py
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it):
    // esp-2021r1-8.4.0
- Operating System:    Linux
- Using an IDE?:No
- Power Supply: USB

## Problem Description

I want the linux computer  to connect the esp32c3 hci as bluebooth by h4. device .I test controller_hci_uart_esp32c3 demo.But the linux cannot recognise the  esp32 hci0.

### Actual Behavior

The computer  cannot recognize the esp32c3 as the ble device.

### Steps to reproduce

1. flash the demo for esp32c3
2. esp32c3 connect to computer by h4
3. input `sudo btattach -B /dev/ttyUSB1 -P h4 -S 921600`  in the linux shell （I sure the h4 serial port is ttyUSB1）
4. input `hciconfig -a` in the linux shell and check whether hci is ok. 
5. input 'sudo hcitool lescan' in the shell and begin to scan the ble device.

## Debug Logs

Linux shell result:
> yates@yates-virtual-machine:~/esp/esp-idf$ hciconfig -a
hci0:	Type: Primary  Bus: UART
	BD Address: 7C:DF:A1:B5:4F:6E  ACL MTU: 251:12  SCO MTU: 0:0
	UP RUNNING 
	RX bytes:296 acl:0 sco:0 events:25 errors:0
	TX bytes:198 acl:0 sco:0 commands:25 errors:0
	Features: 0x00 0x00 0x00 0x00 0x60 0x00 0x00 0x00
	Packet type: DM1 DH1 HV1 
	Link policy: 
	Link mode: SLAVE ACCEPT 
Can't read local name on hci0: Input/output error (5)

esp32 ouput
> Leaving...
Hard resetting via RTS pin...
Executing action: monitor
Running idf_monitor in directory /home/yates/esp/ESP8266_project/bluetooth/hci/controller_hci_uart_esp32c3
Executing "/usr/bin/python /home/yates/esp/esp-idf/tools/idf_monitor.py -p /dev/ttyUSB0 -b 115200 --toolchain-prefix riscv32-esp-elf- --target esp32c3 --decode-panic backtrace /home/yates/esp/ESP8266_project/bluetooth/hci/controller_hci_uart_esp32c3/build/controller_hci_uart_demo.elf -m '/usr/bin/python' '/home/yates/esp/esp-idf/tools/idf.py' '-p' '/dev/ttyUSB0'"...
--- idf_monitor on /dev/ttyUSB0 115200 ---
--- Quit: Ctrl+] | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---
�ESP-ROM:esp32c3-api1-20210207
Build:Feb  7 2021
rst:0x1 (POWERON),boot:0xc (SPI_FAST_FLASH_BOOT)
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fcd6100,len:0x1730
load:0x403ce000,len:0x930
load:0x403d0000,len:0x2d68
entry 0x403ce000
I (30) boot: ESP-IDF v4.4-dev-3042-g220590d599-dirty 2nd stage bootloader
I (30) boot: compile time 11:29:53
I (30) boot: chip revision: 3
I (34) boot.esp32c3: SPI Speed      : 80MHz
I (39) boot.esp32c3: SPI Mode       : DIO
I (43) boot.esp32c3: SPI Flash Size : 2MB
I (48) boot: Enabling RNG early entropy source...
I (54) boot: Partition Table:
I (57) boot: ## Label            Usage          Type ST Offset   Length
I (65) boot:  0 nvs              WiFi data        01 02 00009000 00006000
I (72) boot:  1 phy_init         RF data          01 01 0000f000 00001000
I (79) boot:  2 factory          factory app      00 00 00010000 00100000
I (87) boot: End of partition table
I (91) esp_image: segment 0: paddr=00010020 vaddr=3c040020 size=0b598h ( 46488) map
I (107) esp_image: segment 1: paddr=0001b5c0 vaddr=3fc8d000 size=0223ch (  8764) load
I (109) esp_image: segment 2: paddr=0001d804 vaddr=40380000 size=02814h ( 10260) load
I (118) esp_image: segment 3: paddr=00020020 vaddr=42000020 size=350e4h (217316) map
I (159) esp_image: segment 4: paddr=0005510c vaddr=40382814 size=0a6e4h ( 42724) load
I (167) esp_image: segment 5: paddr=0005f7f8 vaddr=50000000 size=00010h (    16) load
I (171) boot: Loaded app from partition at offset 0x10000
I (171) boot: Disabling RNG early entropy source...
I (187) cpu_start: Pro cpu up.
I (196) cpu_start: Pro cpu start user code
I (196) cpu_start: cpu freq: 160000000
I (196) cpu_start: Application information:
I (199) cpu_start: Project name:     controller_hci_uart_demo
I (206) cpu_start: App version:      1
I (210) cpu_start: Compile time:     Sep 16 2021 13:09:09
I (216) cpu_start: ELF file SHA256:  21af81fcd605d935...
I (222) cpu_start: ESP-IDF:          v4.4-dev-3042-g220590d599-dirty
I (229) heap_init: Initializing. RAM available for dynamic allocation:
I (236) heap_init: At 3FC903D0 len 0002FC30 (191 KiB): DRAM
I (243) heap_init: At 3FCC0000 len 0001F060 (124 KiB): STACK/DRAM
I (249) heap_init: At 50000010 len 00001FF0 (7 KiB): RTCRAM
I (256) spi_flash: detected chip: generic
I (260) spi_flash: flash io: dio
I (265) sleep: Configure to isolate all GPIO pins in sleep state
I (271) sleep: Enable automatic switching of GPIO sleep configuration
I (278) cpu_start: Starting scheduler.
I (283) gpio: GPIO[4]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 
I (283) gpio: GPIO[6]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 
I (293) gpio: GPIO[5]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 
I (303) gpio: GPIO[7]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 
I (313) BTDM_INIT: BT controller compile version [72463e1]
I (323) coexist: coexist rom version 9387209
I (323) phy_init: phy_version 500,985899c,Apr 19 2021,16:05:08
E (333) phy_init: esp_phy_load_cal_data_from_nvs: NVS has not been initialized. Call nvs_flash_init before starting WiFi/BT.
W (343) phy_init: failed to load RF calibration data (0x1101), falling back to full calibration
I (463) system_api: Base MAC address is not set
I (463) system_api: read default base MAC address from EFUSE
I (463) BTDM_INIT: Bluetooth MAC: 7c:df:a1:b5:4f:6e

I (473) UHCI: HCI messages can be communicated over UART1: 
--PINs: TxD 4, RxD 5, RTS 6, CTS 7
--Baudrate: 921600

**Comment by xulongzhuang** [comment]
Hi, @donny681 ,I can run it with the following commands: 
```
hciattach -s 921600 /dev/ttyUSBx any 921600 flow nosleep
hciconfig
sudo hciconfig hcix up
```
I think your problem may be caused by the omission of the command `sudo hciconfig hcix up` , hcix is the device number seen using the `hciconfig` command

**Comment by Alvin1Zhang** [comment]
@donny681 Thanks for reporting, would you please help share if any updates for the issue? Thanks.

**Comment by Alvin1Zhang** [comment]
@donny681 Thanks for reporting, will close due to short of feedback, feel free to reopen with more updates. Thanks.
