### ISSUE TITLE
Store BLE Mesh Node configuration persistently leads to an error (IDFGH-5875)

### ISSUE THREAD

**Issue by bodyanych** [espressif/esp-idf#7574]
Hello,

I want an ESP32 to be able to store provisioning data after power loss, so a device could be connected and not provisioned after power on.
When **Component config --> Ble mesh Support --> Store BLE Mesh Node configuration persistently** in ON -> **device could not be provisioned** (seen by nRF mesh app) anymore (esp boot log with the error attached).
When **Component config --> Ble mesh Support --> Store BLE Mesh Node configuration persistently** in OFF -> **device could be provisioned**, but should be provisioned again after reboot/power loss.

SDK config files are attached.

**What could be the problem? 
How could I keep the ability to provision the device once, and then reconnect to it?**

I am working in VS code / Platformio.
**platformio.ini file**:
```
[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = espidf
board_build.partitions = partitions.csv
build_flags = -std=c++17
build_unflags = -std=c++11
monitor_speed = 115200
lib_ldf_mode = chain
monitor_flags = 
	--raw
upload_protocol = esptool
```

This is from **c_pp_propertioe.json** file:
```
            "defines": [
                "_GNU_SOURCE",
                "IDF_VER=\"4.3.0\"",
                "ESP_PLATFORM",
                "PLATFORMIO=50200",
                "ARDUINO_ESP32_DEV",
                ""
            ],
            "cStandard": "c99",
            "cppStandard": "c++11",
            "compilerPath": "C:/Users/xxx/.platformio/packages/toolchain-xtensa32/bin/xtensa-esp32-elf-gcc.exe",
            "compilerArgs": [
                "-mlongcalls",
                ""
            ]
```

**
[sdkconfig.zip](https://github.com/espressif/esp-idf/files/7178569/sdkconfig.zip)
![Componet config -- Ble mesh Support ](https://user-images.githubusercontent.com/29886479/133631652-1399030f-065c-4d5d-8478-94a7fe7a6aa5.png)
![ESP_boot](https://user-images.githubusercontent.com/29886479/133631656-a49989c0-b891-4374-8c45-615b47131cbd.png)
--> Store BLE Mesh Node configuration persistently**

**Comment by InfiniteYuan** [comment]
This is the expected behavior

You can call `esp_err_t esp_ble_mesh_node_local_reset(void);` api to reset the ble mesh node, to re-provision the device, when Store BLE Mesh Node configuration persistently in ON.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, feel free to reopen.
