### ISSUE TITLE
Braktooth vulnerability (IDFGH-5908)

### ISSUE THREAD

**Issue by justintconroy** [espressif/esp-idf#7600]
https://hackaday.com/2021/09/23/bluetooth-vulnerability-arbitrary-code-execution-on-the-esp32-among-others/

Just want to make sure this is on your radar and ask what you're doing to address it. I've only read the hackaday article so far. I haven't looked into it any further than that yet.

**Comment by chegewara** [comment]
https://www.esp32.com/viewtopic.php?t=23174
https://esp32.com/viewtopic.php?t=23094
https://www.espressif.com/sites/default/files/advisory_downloads/AR2021-004%20Bluetooth%20Security%20Advisory.pdf
