### ISSUE TITLE
Can esp32c3 be used for PDM? (IDFGH-5912)

### ISSUE THREAD

**Issue by xpdrycry** [espressif/esp-idf#7604]
Can esp32c3 be used for PDM? We can’t get the output using SPH0644, don’t know why? The program runs normally, but there is no sound。。by using example: https://github.com/espressif/esp-idf/tree/master/examples/peripherals/i2s/i2s_audio_recorder_sdcard,this example.

**Comment by L-KAYA** [comment]
Sorry, ESP32-C3 only support PDM ouput, not support PDM input. This example should not not able to run on C3. 
Thanks for reporting this issue, we will add warning in driver and list the target chip in example `README.md` later.

**Comment by xpdrycry** [comment]
Can s3 be used for PDM?

**Comment by L-KAYA** [comment]
S3 have both PDM TX and RX, so it should be. But I tried to run this example on exp32s3 just now, and find it has no output. There should be something wrong with the example or driver. If any clues found, I'll post here.

**Comment by L-KAYA** [comment]
This example will support S3 soon and it will also get some bugfix.

**Comment by dzanis** [comment]
Can esp32c3 be used for i2s adc mode input ?

**Comment by 4rthurmonteiro** [comment]
Yes .

> Can esp32c3 be used for i2s adc mode input ?
