### ISSUE TITLE
ESP32 Modbus Slave example testing.  (IDFGH-5931)

### ISSUE THREAD

**Issue by dimpalsharm** [espressif/esp-idf#7619]
Hi Team,

As per given document for ESP32 IDF  example "esp-idf/examples/protocol/modbus/serial/mb_slave" to test this how we can get that which UART is getting used in modbus example.
Can not find any define port only MACRO is there.

Thanks!!

**Comment by laukik-hase** [comment]
Hello, @dimpalsharm
After the command `idf.py menuconfig`, you can change the UART port here -
 `(Top) → Modbus Example Configuration → UART port number`

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, feel free to reopen or you could create a post on our forum at https://esp32.com.
