### ISSUE TITLE
Getting error for esp-idf modbus  slave example testing (IDFGH-5939)

### ISSUE THREAD

**Issue by dimpalsharm** [espressif/esp-idf#7627]
Hello,

I am trying to run the esp-idf modbus slave examplewith modbus master/poll tool
![image](https://user-images.githubusercontent.com/89241509/135567227-2a4c3a65-55d6-4a17-bbf8-bda5184e33db.png)
getting read/write error in poll tool like above.

**Comment by alisitsyn** [comment]
Hello @dimpalsharm,

The Break condition means that the transmitter is holding the line in zero state when transmittion is done for a long time. This often heppens when RS485 line drivers do not work correctly. 
1. Please use the [rs485 echo example](https://github.com/espressif/esp-idf/tree/master/examples/peripherals/uart/uart_echo_rs485) to check interface connection first.
2. Flash the Modbus slave example `idf.py -p PORT flash monitor'.
3. Start modbus communication then use "Display communication traffic" option in the tool bar or menu of your "Modbus Master Poll" software. This will show communication log which will allow to recognize the problem. Please include the log here.
4. Include the [mb_slave example](https://github.com/espressif/esp-idf/tree/master/examples/protocols/modbus/serial/mb_slave) log here.

Thanks.

**Comment by alisitsyn** [comment]
@dimpalsharm,

Could you give the update for this issue? 
Also, you are creating several test issues for Modbus that are related to each other that prevents to track them appropriately.

**Comment by Alvin1Zhang** [comment]
@dimpalsharm Thanks for reporting, would you please help share if any updates for the issue? Thanks.

**Comment by Alvin1Zhang** [comment]
@dimpalsharm Thanks for reporting, would you please help share if any updates for the issue? Thanks.

**Comment by Alvin1Zhang** [comment]
@dimpalsharm Thanks for reporting, will close due to short of feedback, feel free to reopen with more updates.
