### ISSUE TITLE
[TW#13710] BLE: Scan result response contains "unknown" value for ble_evt_type field

### ISSUE THREAD

**Issue by nkolban** [espressif/esp-idf#763]
When we are performing a scan as a BLE client, we receive ESP_GAP_BLE_SCAN_RESULT_EVT type events.  This contains a structure field called "scan_rst".  One of the fields in this structure is called "ble_evt_type" and is defined to have one of the following values:

* ESP_BLE_EVT_CONN_ADV
* ESP_BLE_EVT_CONN_DIR_ADV
* ESP_BLE_EVT_DISC_ADV
* ESP_BLE_EVT_NON_CONN_ADV
* ESP_BLE_EVT_SCAN_RSP

Unfortunately, I am getting a numeric value for this field of (decimal) 160.  This does not correspond to any of the above definitions.

**Comment by Yulong-espressif** [comment]
@nkolban The type of ble_evt_type is used to set the scan param, and the scan_rst  structure field should used the esp_ble_adv_data_type to resolve the advertising data. Hope this answer can help you, thanks.
