### ISSUE TITLE
Unable to setup ESP-IDF extension (Certificate has exprired) (IDFGH-5946)

### ISSUE THREAD

**Issue by Typoception** [espressif/esp-idf#7634]
Just reinstalled esp-idf extension. have done it before without problems but now there's an error stating certificate has expired.

Error: certificate has expired
	at TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)
	at TLSSocket.emit (events.js:315:20)
	at TLSSocket._finishInit (_tls_wrap.js:932:8)
	at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12)
Error opening esp-idf version list file. HTTP/HTTPS Request error https://dl.espressif.com/dl/esp-idf/idf_versions.txt
Downloading C:\Users\yahsa\esp\.espressif\dist\idf-git-2.30.1-win64.zip...
Error: certificate has expired
	at TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)
	at TLSSocket.emit (events.js:315:20)
	at TLSSocket._finishInit (_tls_wrap.js:932:8)
	at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12)
Failed download. Retrying...
Error: Error: HTTP/HTTPS Request error https://dl.espressif.com/dl/idf-git/idf-git-2.30.1-win64.zip
Waiting 8 seconds...
Error: certificate has expired
	at TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)
	at TLSSocket.emit (events.js:315:20)
	at TLSSocket._finishInit (_tls_wrap.js:932:8)
	at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12)
Failed download. Retrying...
Error: Error: HTTP/HTTPS Request error https://dl.espressif.com/dl/idf-git/idf-git-2.30.1-win64.zip
Waiting 16 seconds...
Error: certificate has expired
	at TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)
	at TLSSocket.emit (events.js:315:20)
	at TLSSocket._finishInit (_tls_wrap.js:932:8)
	at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12)
Failed download. Retrying...
Error: Error: HTTP/HTTPS Request error https://dl.espressif.com/dl/idf-git/idf-git-2.30.1-win64.zip
Installing C:\Users\yahsa\esp\.espressif\tools\idf-git\2.30.1 ...
Error during ESP-IDF setup

**Comment by chegewara** [comment]
I believe you may have this error, because its not first report, but it is very strange. Certificate is valid for 6 more weeks.
![Screenshot from 2021-10-02 17-52-08](https://user-images.githubusercontent.com/1406020/135723705-851191ef-7117-49a2-8505-f8c389cfcefe.png)

**Comment by Typoception** [comment]
@chegewara what do you mean not first report? is it because i uninstall and reinstall?

I even reset my pc just to try again but same issue.

**Comment by italocjs** [comment]
Same as #7624 .
A workaround is also there.

I'm not 100% sure its the same , but a similar issue is happening all over internet, as the letsencript certificate expired in 30/sep.  s

**Comment by chegewara** [comment]
I mean that ive seen some issue about certificate expired recently from other people, i think.

**Comment by italocjs** [comment]
> I mean that ive seen some issue about certificate expired recently from other people, i think.

What i've read is that the Letsencrypt certificate expired (which is "one authority level above" the website certificate, if one cant be authenticated, the other also cant).  But as i said, i'm not 100% sure is the same issue.

**Comment by Typoception** [comment]
@italocjs thanks man. managed to finally get it working. I didn't know esp-idf can be installed separately, thought only through vscode extension :)
