### ISSUE TITLE
ESP32 reset after disconnect event with reason 12 (IDFGH-5956)

### ISSUE THREAD

**Issue by JonasAxelsson** [espressif/esp-idf#7644]
## Environment

Development Kit: none
Module or chip used: ESP32-WROVER
IDF version (run git describe --tags to find it):
C:\repo\ble_test\dicm\esp32>git describe --tags
HMI_Rubicon_v1.4.0-12-g0d53d8d4
Build System: CMake
Compiler version (run xtensa-esp32-elf-gcc --version to find it):
xtensa-esp32-elf-gcc (crosstool-NG esp-2020r3) 8.4.0
Operating System: Windows
(Windows only) environment type: Plain Command Prompt
Using an IDE?: No
Power Supply: USB

## Problem Description

ESP32 reset after disconnect event with reason 12 (0x0C BLE_HS_ECONTROLLER , Event from controller is invalid).

The six slave devices disconnect with start at timestamp 103220, probably due to problems in stack.

ESP-IDF version used: 4.2.2

### Expected Behavior
ESP-32 should not reset

### Actual Behavior
ESP-32 reset

### Steps to reproduce

Use ESP-32 as both central and peripheral. Connect six devices to central and keep them connected.
Connect a device to the peripheral and disconnect 4 seconds late.
Repeat 2. forever, within a couple of minutes the ESP-32 reset.
The reset occurs around 400 ms after the the device connected to peripheral is disconnected.

## Other items if possible
![nimble_crash 211005_7](https://user-images.githubusercontent.com/80249811/136022620-20a7b880-e68f-4cff-bc03-66982f75c223.png)

**Comment by Alvin1Zhang** [comment]
Thanks for reporting and sharing the updates, sorry for slow turnaround, feel free to reopen.
