### ISSUE TITLE
MODBUS TCP 长时间连接异常 (IDFGH-5962)

### ISSUE THREAD

**Issue by Cedar-Magic** [espressif/esp-idf#7650]
**问题描述**
其中一个ESP32模块作为AP，其余三个ESP32模块作为STA，电脑连接至该AP上，通过MODBUS TCP读取四个模块中采集到的数据，超过5分钟后，模块返回数据的速度明显下降，10分钟后数据返回经常超过1s，上位机重新连接、重启模块均可以恢复该异常，使用node、C#开发的上位机软件均遇到了这个问题，使用MODBUS POLL工具也会遇到这个问题，基本可以确认问题出在IDF上，IDF版本为v4.4-dev-1254-g639e7ad49

**Comment by alisitsyn** [comment]
Hi @Cedar-Magic,

Did you try to change WiFi power save type for Modbus TCP modules and also for AP?

[change power save mode of wifi](https://github.com/espressif/esp-idf/blob/master/examples/protocols/modbus/tcp/mb_tcp_master/main/tcp_master.c#L535)

**Comment by Cedar-Magic** [comment]
Thank you for your attention, I tried to change my IDF to v4.3.1 and flash my ESP32 again, the problem has been solved.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "espressif/esp-idf"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月8日(星期五) 晚上7:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [espressif/esp-idf] MODBUS TCP 长时间连接异常 (IDFGH-5962) (#7650)



 Hi @Cedar-Magic,
 Did you try to change WiFi power save type for Modbus TCP modules and also for AP?
 change power save mode of wifi
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting and sharing the updates, and glad the issue has been resolved, feel free to reopen.
