### ISSUE TITLE
ov2640 causes esp32s2 restart (IDFGH-5969)

### ISSUE THREAD

**Issue by achao1104** [espressif/esp-idf#7657]
hello,

we are using esp32s2 and ov2640, when taking jpeg pic, it will cause panic. the log is as below

I (74193) cam_hal: cam config ok
I (75373) camera: Camera Init Done
I (75433) camera: Camera start takeing...
I (75843) gpio: GPIO[6]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:1
I (78843) gpio: GPIO[6]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:1
W (79433) cam_hal: NO-EOI
Guru Meditation Error: Core  0 panic'ed (Memory protection fault).

abort() was called at PC 0x400274ef on core 0
0x400274ef: lock_acquire_generic at D:/project/esp32/es-idf-v4.3-release/components/newlib/locks.c:138

Backtrace:0x4002e09e:0x3ffda280 0x4002e871:0x3ffda2a0 0x4003810e:0x3ffda2c0 0x400274ef:0x3ffda330 0x4002760d:0x3ffda360 0x400fd1be:0x3ffda380 0x4010021d:0x3ffda690 0x4010b71a:0x3ffda6c0 0x40034131:0x3ffda6f0 0x40026958:0x3ffda740 0x4002e439:0x3ffda760 0x4002e0ea:0x3ffda790 0x4002e789:0x3ffda800 0x4002e7d9:0x3ffda850 0x400259ee:0x3ffda870 0x00040022:0x3ffda900 |<-CORRUPTED
0x4002e09e: panic_abort at D:/project/esp32/es-idf-v4.3-release/components/esp_system/panic.c:367

0x4002e871: esp_system_abort at D:/project/esp32/es-idf-v4.3-release/components/esp_system/system_api.c:112

0x4003810e: abort at D:/project/esp32/es-idf-v4.3-release/components/newlib/abort.c:46

0x400274ef: lock_acquire_generic at D:/project/esp32/es-idf-v4.3-release/components/newlib/locks.c:138

0x4002760d: _lock_acquire_recursive at D:/project/esp32/es-idf-v4.3-release/components/newlib/locks.c:166

0x400fd1be: _vfprintf_r at /builds/idf/crosstool-NG/.build/HOST-x86_64-w64-mingw32/xtensa-esp32s2-elf/src/newlib/newlib/libc/stdio/vfprintf.c:853 (discriminator 2)

0x4010021d: vprintf at /builds/idf/crosstool-NG/.build/HOST-x86_64-w64-mingw32/xtensa-esp32s2-elf/src/newlib/newlib/libc/stdio/vprintf.c:34 (discriminator 5)

0x4010b71a: esp_log_writev at D:/project/esp32/es-idf-v4.3-release/components/log/log.c:189

0x40034131: esp_log_write at D:/project/esp32/es-idf-v4.3-release/components/log/log.c:199

0x40026958: esp_memprot_get_fault_status at D:/project/esp32/es-idf-v4.3-release/components/esp32s2/memprot.c:356 (discriminator 3)

0x4002e439: print_memprot_err_details at D:/project/esp32/es-idf-v4.3-release/components/esp_system/port/arch/xtensa/panic_arch.c:274

0x4002e0ea: esp_panic_handler at D:/project/esp32/es-idf-v4.3-release/components/esp_system/panic.c:232 (discriminator 1)

0x4002e789: panic_handler at D:/project/esp32/es-idf-v4.3-release/components/esp_system/port/panic_handler.c:200

0x4002e7d9: panicHandler at D:/project/esp32/es-idf-v4.3-release/components/esp_system/port/panic_handler.c:209

0x400259ee: xt_highint4 at D:/project/esp32/es-idf-v4.3-release/components/esp_system/port/soc/esp32s2/dport_panic_highint_hdl.S:91

ELF file SHA256: dc492b645f2a042d

**Comment by 0xjakob** [comment]
Hi @achao1104! Do you have a piece of application code which reproduces the issue? This would be quite helpful as we can solve the issue most reliably if we have the application code.

We also need the IDF version and the buildsystem you are using (make or cmake).

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to short of feedback, feel free to reopen with more updates.
