### ISSUE TITLE
Adjust the bandwidth of the chip (IDFGH-5975)

### ISSUE THREAD

**Issue by zhangyang428** [espressif/esp-idf#7662]
Can ESP32S2 adjust the working bandwidth? It currently operates in a 2.4Ghz carrier frequency with 40Mhz bandwidth. Is there any specific way I can reduce it to 20Mhz?

**Comment by MaxwellAlan** [comment]
hi @zhangyang428 , you can use below api to modify: 
[esp_wifi_set_bandwidth](https://github.com/espressif/esp-idf/blob/a18cb7090511d235ebe3c8b833180630f4f8bb33/components/esp_wifi/include/esp_wifi.h#L545)
or you can just modify your router configurations to only work in HT20 mode.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, feel free to reopen.
