### ISSUE TITLE
[Bug Report]: Configuration for CONFIG_ESP_SYSTEM_SINGLE_CORE_MODE is missing?  (VSC-763) (IDFGH-5978)

### ISSUE THREAD

**Issue by bradcb212** [espressif/esp-idf#7665]
**Describe the bug**

Hardware: DevkitC with ESP32-SOLO-1
Able to build and flash blinky example.
Application code never runs.
Device target set to ESP32
ESP-IDF 4.3.1

Code gets stuck in an infinite loop: cpu_start.c

#if !CONFIG_ESP_SYSTEM_SINGLE_CORE_MODE
    s_cpu_inited[0] = true;

    volatile bool cpus_inited = false;

    while (!cpus_inited) {
        cpus_inited = true;
        for (int i = 0; i < SOC_CPU_CORES_NUM; i++) {
            cpus_inited &= s_cpu_inited[i];
        }
        esp_rom_delay_us(100);
    }
#endif
ESP-32-SOLO-1 is single core. SOC_CPU_CORES_NUM is set to two.

Cannot find any option in menuconfig to enable CONFIG_ESP_SYSTEM_SINGLE_CORE_MODE.

Can I manually add this to the configuration editor window? It appears that vscode-esp-idf-extension has no support for ESP32-SOLO-1

**Comment by Alvin1Zhang** [comment]
@bradcb212 Thanks for reporting, would you please help share if any updates for the issue? Thanks.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting @bradcb212 , will close due to short of feedback, feel free to reopen with more updates. Thanks.
