### ISSUE TITLE
Eclipse : cannot launch GDB Hardware debugging  (IDFGH-5980)

### ISSUE THREAD

**Issue by rohiniramegowda** [espressif/esp-idf#7667]
## Environment

- Development Kit:      [ESP32S2 Kaluga 1
- Module or chip used:  [ESP32S2-WROOM-32
- IDF version  ;esp-idf-v4.3.1
- Build System:         [Make|CMake|idf.py]
- Compiler version :8.4.0
- Operating System:    macOS
- (Windows only) environment type: Eclipse
- Using an IDE?:  Yes (Eclipse 2021 /06)]
- Power Supply:         [USB]

## Problem Description Cannot Launch GDB hardware Debugging . But everything works fine in command line 

//Detailed problem description 

I am trying to setup GDB Hardware debugging on my ESP32S2 Kaluga using Eclipse . The GDB debugging works fine in command line . But when I launch it through eclipse I get the below error. I have attached the snapshots of my gdb configuration and the error. 

<img width="391" alt="Screen Shot 2021-10-08 at 3 41 16 PM" src="https://user-images.githubusercontent.com/80291478/136627746-62da8425-c5d2-4fad-8644-64a555f215b8.png">

<img width="1078" alt="Screen Shot 2021-10-08 at 3 40 03 PM" src="https://user-images.githubusercontent
<img width="637" alt="Screen Shot 2021-10-08 at 3 40 43
<img width="599" alt="Screen Shot 2021-10-08 at 3 40 57 PM" src="https://user-images.githubusercontent.com/80291478/136627726-46f5b282-d26d-444b-ac41-82f1425df0b1.png">
 PM" src="https://user-images.githubusercontent.com/80291478/136627709-91ab9af5-24b8-4115-aa0a-6c477b8c7e57.png">
.com/80291478/136627660-646da4c4-a67d-47b5-b8e4-3236a1d11381.png">

<img width="641" alt="Screen Shot 2021-10-08 at 3 40 31 PM" src="https://user-images.githubusercontent.com/80291478/136627684-b5fc9d2c-2a92-43a7-8cb4-a6dbc7cb54ae.png">

Is there any recommendation for the version of Eclipse I need to use . I am running out of ideas.

**Comment by gerekon** [comment]
@rohiniramegowda 

Could you collect OpenOCD verbose log for your problem by adding `-d3 -l oocd.log` to its command line and post it here?
Along with action above you'd better set `Remote timeout` to 20 in your `Debugger` config page.

**Comment by rohiniramegowda** [comment]
@gerekon apologize for the delayed response . I had this issue just with openocd version which version v0.10.0-esp32-20210902 . When I switched back to 202104 I stopped seeing this .
