### ISSUE TITLE
Arduino compiler error with esp_vfs.h (IDFGH-5992)

### ISSUE THREAD

**Issue by sreekants** [espressif/esp-idf#7678]
## Environment

- Development Kit:      ESP32-Dev-Module
- Kit version (for WroverKit/PicoKit/DevKitC): [v1|v2|v3|v4]
- Module or chip used:  Not applicable
- IDF version (run ``git describe --tags`` to find it):
- Build System:         Arduino IDE (1.8.16)
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it):
- Operating System:     Windows
- (Windows only) environment type: Arduino IDE.
- Using an IDE?: Yes (Standard 1.8.16 distribution)
- Power Supply:         USB

## Problem Description

I get a strange compiler error when including the header file (esp_vfs.h). The two values B110 and B011 seems to conflict in a switch-case block.

### Expected Behavior
The definitions B110 & B011 are human-readable alternatives to binary values. In principle they cannot be defined as anything but 6 and 3 respectively. I believe this is done so in:
C:\Users\blue_\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.6\cores\esp32\binary.h.

For some reason including esp_vfs.h redefines the value. I am not sure why.

The expected normal behavior is that the inclusion of the header file should in no way cause a compiler error.

### Actual Behavior
Compilation of the sample code fails when the file esp_vfs.h is included. The following output is displayed on the build pane.

F:\users\sreekants\arduino\e22bug\e22bug.ino: In function 'int GetErrorCode(int)':
e22bug:8:5: error: duplicate case value
     case B110: return 6;
     ^
e22bug:7:5: error: previously used here
     case B011: return 3;
     ^
exit status 1
duplicate case value

### Steps to reproduce
If you comment out the header file, the following code compiles fine. If you include the header file, the compile fails in the Arduino IDE. 

### Code to reproduce this issue

```cpp
#include <esp_vfs.h>

int GetErrorCode(int val)
{
  switch( val )
  {
    case B011: return 3;
    case B110: return 6;
  }
}

void setup() {}
void loop() {}

```

**Comment by xreef** [comment]
Hi all,
I think the problem It isn't in my LoRa library, because It's termios.h that use a global system define that have a specified value.

I can use a work around by use a decimal value instead a readable binary one, but as I just say It's a workaround to fix another problem.

What do you think about that?

Bye Renzo

**Comment by igrr** [comment]
B110 definition in termios.h is part of [posix specification](https://pubs.opengroup.org/onlinepubs/007904975/basedefs/termios.h.html) for this header, so it is unlikely that it will be changed.

There are a few things we can consider:

* Avoid including `esp_vfs.h` into Arduino library code; If this is unavoidable, add `#undef B110` before including esp_vfs.h, after including Arduino.h.
* In IDF, we could make `#include <sys/termios.h>` in esp_vfs.h conditional on `CONFIG_VFS_SUPPORT_TERMIOS`. Then in Arduino, the default sdkconfig could be changed to disable termios support.

**Comment by VojtechBartoska** [comment]
Hi @sreekants, is this still valid or you already solve your issue?

**Comment by VojtechBartoska** [comment]
Thanks for quick reply. I'm closing this issue as solved.

**Comment by xreef** [comment]
Also for me closed, the notation 
B1000000 
become deprecated in the latest Arduino SAMD core, now suggest the use of
0b1000000 
notation.
Bye Renzo
