### ISSUE TITLE
idf.py menuconfig hangs on mesh examples (IDFGH-5994)

### ISSUE THREAD

**Issue by AustP** [espressif/esp-idf#7679]
## Environment

- Development Kit: ESP32-Wrover-Kit
- Module or chip used:  ESP32-WROOM-32
- IDF version (run ``git describe --tags`` to find it): v4.3.1
- Build System: idf.py
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it): 8.4.0
- Operating System: Linux
- Using an IDE?: No
- Power Supply: USB

## Problem Description

When running `idf.py menuconfig`, the menu opens up but it just hangs. I have tried on master, v4.2, v4.1, v4.0, and v3.3, and they all have the same issue.

### Expected Behavior

Should be able to navigate through the menu and make config changes.

### Actual Behavior

Hangs upon opening.

### Steps to reproduce

1. `git checkout v4.3.1`
2. `cd examples/mesh/internal_communication`
3. `idf.py menuconfig`

**Comment by dobairoland** [comment]
Could you please try to run `idf.py fullclean` before `idf.py menuconfig`. Please share also the full intput of `idf.py menuconfig` (before CTRL+C and the trace).
