### ISSUE TITLE
UNITY_SUPPORT_64 (IDFGH-5998)

### ISSUE THREAD

**Issue by franz-ms-muc** [espressif/esp-idf#7683]
Hello, 

one can Activate "Float" Support in sdkconfig, 
CONFIG_UNITY_ENABLE_FLOAT --> 
one can Activate "Double" Support in sdkconfig, 
CONFIG_UNITY_ENABLE_DOUBLE --> 

but one cannot activate int_64 Support in sdkconfig. 

UNITY_SUPPORT_64

would be nice to have it. ...

**Comment by diplfranzhoepfinger** [comment]
confirm: is working well !
