### ISSUE TITLE
Bluetooth packet drop when Wifi reconnection got WiFi-Router. (IDFGH-6006)

### ISSUE THREAD

**Issue by iloop2020** [espressif/esp-idf#7686]
Hi,

We are facing bluetooth A2DP packet drop issue when WiFi try to reconnect to WIFI router.

Info:
1. Internet access via WiFi is required.
2. Bluetooth A2DP streaming is requried.

How to reproduce
1. WiFi connect to Route noramlly.
2. Use a smooth phone connect to ESP32 for A2DP streaming.
3. Power Off the WiFI router, then ESP32 WiFi will try reconnect to the Router.
4. Then the bluetooth A2DP audio become unstable and the conosle keep "reassemble_and_dispatch found unfinished packet for handle with start packet. Dropping old.".
5. Power On the WiFI router again and Let ESP32 reconnect. Then A2DP back to the normal and the error message is gone.

I expect the root cause is the WiFi take most of the resources to try to reconnect to WiFi router.
How can I fix it ?

Thank you.

**Comment by iloop2020** [comment]
Hi @Alvin1Zhang ,


Any good news from you side ?

Thank you.

**Comment by iloop2020** [comment]
Hi @Alvin1Zhang ,

We have difficuitly to upgrade IDF to v4.1 at the moment.

But we found that, the BT packet drop issue happen when we calls esp_wifi_connect() API, there are 1 ~ 2 sec dropping. 
I assume the esp_wifi_connect() take too much CPU time or RF interference cause the issue ?

Question:
1. If it is CPU time related, Is there any options to reduce esp_wifi_connect() CPU time or lower the task priority ?
2. If it is RF interference issue, any suggestion for workaround ?

Thank you.

**Comment by xiongweichao** [comment]
Hi @iloop2020 ,

In the process of WI-FI connection, a2dp may lose packets, because at this time WI-FI uses RF, you can suspend the A2DP data stream while wifi is connecting.

Thanks

**Comment by iloop2020** [comment]
Hi @xiongweichao ,

Thank you for support.

Actually, we are doing bluetooth stream as a bluetooth music speacker, so we cannot stop the A2DP data stream.

So we need to keep A2DP and try WiFi reconnection.

Any suggestion ?

Thank you

**Comment by xiongweichao** [comment]
Hi, @iloop2020 

First, pause the a2dp data steam, and then, when the wifi is connecting, you can add a notification sound.

Thanks

**Comment by iloop2020** [comment]
Hi @xiongweichao ,

Thank you for your support.

Our design allow user to keep bluetooth streaming without any interruption, including wifi reconnect in background.

For example:
When user is streaming bluetooth, but with some reason the WiFi router is not available. 
We allow user to keep Bluetooth and let ESP32 to try to recoonection in background.

Please advice how can we achieve the requrimment.

Thank you.

**Comment by xiongweichao** [comment]
Hi @iloop2020 

Please try to use RingBuf to cache more audio data at the application layer.

Thanks

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to short of feedback, feel free to reopen.
