### ISSUE TITLE
 idf-eclipse-plugin`s "SDK Configuration" does not display some Kconfig menu !!!! (IDFGH-6010)

### ISSUE THREAD

**Issue by ShenRen** [espressif/esp-idf#7697]
SDK Configuration 不会显示Kconfig 菜单项目，如果它是用 depends on 来控制菜单是否可见。
The SDK Configuration does not display Kconfig menu items if it uses "depends on" to control whether the menu is visible.

![menu _use_depends_on](https://user-images.githubusercontent.com/6782951/137431072-054eefdd-b8a2-4165-a2dd-26c2570b43b8.png)

将菜单的可见性控制改成"visible if"就会正常显示菜单。
Changing the menu visibility control to "visible if" will display the menu normally.

![menu _use_visible_if](https://user-images.githubusercontent.com/6782951/137431945-4d64bac0-97c0-4d63-8957-bf2d8905fa9e.png)

这个问题从一直存在，即使是最新版本的插件。但是它可以通过将KConfig中的脚本更改后得到修复。
This problem has always existed, even with the latest versions of plug-ins. But it can be fixed by changing the script in KConfig.

I also submitted the same Issue in [idf-eclipse-plugin](https://github.com/espressif/idf-eclipse-plugin)
https://github.com/espressif/idf-eclipse-plugin/issues/375

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close this ticket and keep tracking in https://github.com/espressif/idf-eclipse-plugin/issues/375.
