### ISSUE TITLE
Request the sample code of S3 peripheral USB HID keyboard and mouse (IDFGH-6013)

### ISSUE THREAD

**Issue by M-W-H-185** [espressif/esp-idf#7700]
Development Kit : ESP32-S3-DevKitC-1
IDF version : [v4.4-dev-3235-g3e370c4296]

**Comment by M-W-H-185** [comment]
> @M-W-H-185 Do you mean ESP32-S3 as a USB Host communicating with a HID Keyboard and Mouse? Or the S3 as a USB Device acting as a HID Keyboard and Mouse?

Yes, I want to use S3 as a MUC to communicate with the host

**Comment by westdd** [comment]
usb costom hid, 能不能更新一下这个

**Comment by ada19911201** [comment]
usb costom hid ，update

**Comment by lukedukeus** [comment]
Does anyone have a working example of the USBHIDKeyboard class working in idf?
