### ISSUE TITLE
ESP32-S2 USB CDC not recognized from another device (IDFGH-6014)

### ISSUE THREAD

**Issue by filgra96** [espressif/esp-idf#7701]
Hello,

Development Kit: ESP32-S2-Saola
Module or chip used: ESP32-S2-WROOM
Build System: idf.py
Compiler version: xtensa-esp32s2-elf-gcc
Operating System: Windows 10
Using an IDE?: Yes (VS Code with ESP-IDF plugin)
Power Supply: USB

My _ESP32-S2_ has an USB connector attached to pin 19 (D-), pin 20 (D+) and to the power supply. I use the _TinyUSB_ drivers. I tested the USB connection through a terminal with the examples tusb_console, tusb_sample_descriptor, tusb_serial_device and they work.

I'm working in a project on MPLAB where there is a USB communication between the _ESP32_ and a _PIC32MX250F256H_.
In particular, the _ESP32_ is configured as **CDC USB** device and must be plugged into the USB port of the PIC32 to start the communication.
On the other hand the PIC32 should recognize it before communicate.

I'm encountering some problems due to the recognition of my **ESP32-S2** as CDC device when I plug it into a USB port of the **PIC32**.

I think that the problem is due to the **Class, Subclass and Protocol** settings.

In fact I noticed when I plug the ESP's USB into my PC it's recognized as USB Serial Port with the values:
- Class = 0x02
- Subclass = 0x02
- Protocol= 0x00

When I connect the ESP to the Microchip microcontroller, it detects the ESP with the following values:
- Class = 0x0A
- Subclass = 0x00
- Protocol= 0x00

After that the _PIC32MX_ quits the communication because it doesn't recognize it in the right way.
However I have another CDC device (**it's not an ESP32**) that works perfectly with this MCU, it has Class = 0x02, Subclass = 0x02, Protocol= 0x01.

Where could be the problem?
Is there a way to change the CDC parameters (class, etc...) of my ESP32-S2?

Regards,
Filippo

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, you could raise a post on our forum at https://esp32.com
