### ISSUE TITLE
Error from including hal/gpio_ll.h in c++ (IDFGH-6026)

### ISSUE THREAD

**Issue by 203Null** [espressif/esp-idf#7712]
## Environment

- Development Kit:      esp32-s3-devkitc-1
- Kit version (for WroverKit/PicoKit/DevKitC): v1.0
- Module or chip used:  ESP32-S3-WROOM-1
- IDF version: v4.4-dev-3235-g3e370c4296
- Build System:         idf.py
- Compiler version: xtensa-esp32-elf-gcc (crosstool-NG esp-2021r1) 8.4.0
- Operating System:    Windows 10
- (Windows only) environment type: ESP Command Prompt
- Using an IDE?: No
- Power Supply:         USB

### Expected Behavior
 It should just compile with no problem

### Actual Behavior
invalid conversion from 'uint32_t' {aka 'unsigned int'} to 'gpio_drive_cap_t' is thrown

### Steps to reproduce

0. Make a copy of the sample_project
1. Rename sample_project/main/main.c to main.cpp
2. Change sample_project/main/CMakeLists.txt's SRCS "main.c" to SRCS "main.cpp"
3. Paste the code below to main.cpp
4. idf.py build

### Code to reproduce this issue

```cpp
// the code should be wrapped in the ```cpp tag so that it will be displayed better.
#include "hal/gpio_ll.h"

extern "C" void app_main(void){}
```
// If your code is longer than 30 lines, [GIST](https://gist.github.com) is preferred.

## Debug Logs
> on file included from c:\esp-idf\components\hal\esp32\include\hal\gpio_ll.h:26,
                 from ../main/main.cpp:2:
c:\esp-idf\components\hal\esp32\include\hal\gpio_ll.h: In function 'void gpio_ll_get_drive_capability(gpio_dev_t*, gpio_num_t, gpio_drive_cap_t*)':
c:\esp-idf\components\soc\esp32\include\soc\soc.h:212:51: error: invalid conversion from 'uint32_t' {aka 'unsigned int'} to 'gpio_drive_cap_t' [-fpermissive]
             ((READ_PERI_REG(reg)>>(shift))&(mask));                                                                    \
                                                   ^
c:\esp-idf\components\hal\esp32\include\hal\gpio_ll.h:514:17: note: in expansion of macro 'GET_PERI_REG_BITS2'
     *strength = GET_PERI_REG_BITS2(GPIO_PIN_MUX_REG[gpio_num], FUN_DRV_V, FUN_DRV_S);
                 ^~~~~~~~~~~~~~~~~~
ninja: build stopped: subcommand failed.
ninja failed with exit code 1

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, fix is available at https://github.com/espressif/esp-idf/commit/a631765333acc74ff484f7d693d609bc2a861585, feel free to reopen.
