### ISSUE TITLE
esp32c3 uart0 no use rx  , only use tx (IDFGH-6028)

### ISSUE THREAD

**Issue by shun-dgut** [espressif/esp-idf#7714]
How to release the rx of the serial  0 port？

**Comment by shun-dgut** [comment]
I want to use serial 0 port rx as gpio

**Comment by chegewara** [comment]
https://docs.espressif.com/projects/esp-idf/en/latest/esp32c3/api-reference/peripherals/gpio.html#_CPPv414gpio_reset_pin10gpio_num_t

**Comment by shun-dgut** [comment]
> https://docs.espressif.com/projects/esp-idf/en/latest/esp32c3/api-reference/peripherals/gpio.html#_CPPv414gpio_reset_pin10gpio_num_t

I want to output tx to a low level, call gpio_reset_pin function before gpio configuration, and then initialize tx to output low level, but the function captured by the logic analyzer is still high level 1 and cannot be set to 0

**Comment by Alvin1Zhang** [comment]
@shun-dgut Thanks for reporting, would you please help share if any updates for the issue? Thanks.

**Comment by Alvin1Zhang** [comment]
@shun-dgut Thanks for reporting, would you please help share if any updates for the issue? Thanks.

**Comment by o-marshmallow** [comment]
Closing this issue, please re-open if you still encounter this problem
