### ISSUE TITLE
Bluetooth HCI example fails to do l2ping after a couple of hours ("Unknown Connection Identifier"). (IDFGH-6038)

### ISSUE THREAD

**Issue by danergo** [espressif/esp-idf#7723]
## Environment

Development Kit: NodeMCU-ESP-32S
Module or chip used: ESP-WROOM-32
IDF version (run git describe --tags to find it): v4.4-dev-2533-g83956ebbae
Build System: idf.py
Compiler version (run xtensa-esp32-elf-gcc --version to find it): xtensa-esp32-elf-gcc (crosstool-NG esp-2021r1) 8.4.0
Operating System: Linux
Using an IDE?: No
Power Supply: external 5V

## Problem Description

I'm using ESP32 as a Bluetooth controller (controller only! No host functionality!), with the ESP-IDF provided hciuart sample: https://github.com/espressif/esp-idf/tree/master/examples/bluetooth/hci/controller_hci_uart_esp32.

Controller is attached to a host running BlueZ via hciattach.

I'm using l2ping on the host to ping my phone in every 5mins. After about half day, l2ping stops working by reporting:

> Can't connect: Operation now in progress

### Expected Behavior

Don't stop working after half day. Other controller (RPi4's Cypress-based one) ran for more than a year constantly.

### Actual Behavior

Stops after half day.

## Debug Logs

During the problematic l2ping operation, nothing is printed onto the debug port of ESP32. However there is an interesting line in `btmon`:

```
> HCI Event: Command Complete (0x0e) plen 10 
      Create Connection Cancel (0x01|0x0008) ncmd 5
        Status: Unknown Connection Identifier (0x02)
        Address: aa:bb:cc:dd:ee:ff (Samsung Electronics Co.,Ltd)
```

The interesting line is "Unknown Connection Identifier".

**Comment by xiewenxiang** [comment]
@danergo 

Such as the All of the log.

**Comment by danergo** [comment]
Binary anyway is from controller_hci_uart configured to use uart1. Nothing special, no mods are added.

**Comment by xiewenxiang** [comment]
Hi @danergo 

Does this issue is the same as https://github.com/espressif/esp-idf/issues/7763?

**Comment by danergo** [comment]
Hi @xiewenxiang,

This was my original issue, and after I dug myself into this, I found the root cause which is #7763 Indeed.

So after #7763 is resolved, this can be also closed automatically.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, feel free to reopen.
