### ISSUE TITLE
Bluetooth related example projects do not compile (IDFGH-6042)

### ISSUE THREAD

**Issue by ravargash** [espressif/esp-idf#7727]
## Environment

- Development Kit:      ESP32-DevKitC
- Kit version (for WroverKit/PicoKit/DevKitC): v4
- Module or chip used:  ESP32-WROOM-02
- IDF version 4.3.1
- Build System:         CMake
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it):
    // 1.22.0-80-g6c4433a
- Operating System:     Windows 10
- (Windows only) environment type: MSYS2 mingw32
- Using an IDE?: Default preconfigured Eclipse provided with esp-idf
- Power Supply:         USB

## Problem Description

Example project bt_spp_acceptor does not compile by default

### Expected Behavior

A compiled project

### Actual Behavior

Compilation fails 

### Steps to reproduce

Download ESP-IDF
Choose to include Eclipse
Create a new Espressif-IDF project
Use bt_spp_aceptor as a template
Build/run

## Debug Logs

C:/Users/ravar/Desktop/esp-idf-2/components/bt/host/bluedroid/hci/hci_layer.c:184:5: error: implicit declaration of function 'btsnd_hcic_ble_sync_sem_init'; did you mean 'btsnd_hcic_ble_set_phy'? [-Werror=implicit-function-declaration]
     btsnd_hcic_ble_sync_sem_init();
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
     btsnd_hcic_ble_set_phy
C:/Users/ravar/Desktop/esp-idf-2/components/bt/host/bluedroid/hci/hci_layer.c: In function 'hci_layer_deinit_env':
C:/Users/ravar/Desktop/esp-idf-2/components/bt/host/bluedroid/hci/hci_layer.c:207:5: error: implicit declaration of function 'btsnd_hcic_ble_sync_sem_deinit'; did you mean 'btsnd_hcic_ble_clear_adv_set'? [-Werror=implicit-function-declaration]
     btsnd_hcic_ble_sync_sem_deinit();
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     btsnd_hcic_ble_clear_adv_set
C:/Users/ravar/Desktop/esp-idf-2/components/bt/host/bluedroid/hci/hci_layer.c: In function 'filter_incoming_event':
C:/Users/ravar/Desktop/esp-idf-2/components/bt/host/bluedroid/hci/hci_layer.c:443:36: error: implicit declaration of function 'btsnd_hcic_ble_get_sync_info'; did you mean 'btsnd_hcic_ble_ext_scan_enable'? [-Werror=implicit-function-declaration]
             BlE_SYNC *sync_info =  btsnd_hcic_ble_get_sync_info();
                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                    btsnd_hcic_ble_ext_scan_enable
C:/Users/ravar/Desktop/esp-idf-2/components/bt/host/bluedroid/hci/hci_layer.c:443:36: warning: initialization of 'BlE_SYNC *' {aka 'struct <anonymous> *'} from 'int' makes pointer from integer without a cast [-Wint-conversion]
cc1.exe: some warnings being treated as errors

Regards!

**Comment by BetterJincheng** [comment]
Hi @ravargash,
 
I just built and run the demo `bt_spp_acceptor` successfully with idf_v4.3.1. Could you please try some other examples to make sure where the problem is, the `bt_spp_acceptor` example or your compiling environment.

Thanks!

**Comment by BetterJincheng** [comment]
Hi @ravargash,

I checked the attached sdkconfig and found some information:

1. You reported this issue on a module: ESP32-WROOM-02.
2. You set the target to ESP32C3 showed from the sdkconfig.
3. ESP32C3 do not support Classic Bluetooth (SPP).

So the errors occurred. Here are some of my suggestions:

1. Set the target to ESP32 in CLI (`idf.py set-target esp32`) and try demo `bt_spp_acceptor` again. (SUGGESTED)
2. Or, set the target to ESP32C3 in CLI (`idf.py set-target esp32c3`) and try demo `examples/bluetooth/bluedroid/ble/ble_spp_server` and `examples/bluetooth/bluedroid/ble/ble_spp_client`. (MAY NOT WORK)

Hope to helpful. Thanks!

**Comment by ravargash** [comment]
Hi @BetterJincheng 

You're right. I wrongly reported this issue as a ESP32 issue. instead of ESP32-C3. I'm currently testing in a ESP32-C3-DevKitC-02.

> ESP32C3 do not support Classic Bluetooth (SPP).

Didn't knew that.

Both examples/bluetooth/bluedroid/ble/ble_spp_server and examples/bluetooth/bluedroid/ble/ble_spp_client compiled fine and will begin development based on them.

Thank you. I'll close this issue now.

**Comment by ravargash** [comment]
PD @BetterJincheng, I'm looking a way to use any kind of method to comunicate between the ESP32-C3 and a bluetooth serial terminal app on my cellphone. I haven't found any straightforward example on how to do this. Would you kindly recomend me somewhere to start?

Regards!
