### ISSUE TITLE
使用esp32c3做一个开关产品，测试产品过程中出现重启，错误见下图 (IDFGH-6043)

### ISSUE THREAD

**Issue by LiuWenPeng666** [espressif/esp-idf#7728]
![D 6E`~0NE$9ROMJ_$SPOE9K](https://user-images.githubusercontent.com/44110991/137861276-0e128ecc-b848-4f8f-814d-ba76ed20b229.png)

**Comment by LiuWenPeng666** [comment]
使用的esp-idf是4.3.1版本

**Comment by Alvin1Zhang** [comment]
@LiuWenPeng666 Thanks for reporting. Would you please help provide more details as suggested in the [issue template](https://github.com/espressif/esp-idf/issues/new?assignees=&labels=&template=bug_report.md&title=)? Information like elf, sdk configuration, backtrace, log outputs, commit ID, hardware and etc. would help us debug further. Thanks.
