### ISSUE TITLE
Not able to re-enable the bluetooth (IDFGH-6045)

### ISSUE THREAD

**Issue by arjaanda** [espressif/esp-idf#7729]
Hello,

In my project I need to disable Bluetooth momentarily and re-enable it.

I am using esp_bt_controller_disable API to disable the bluetooth which seems to work. But when use esp_bt_controller_enable API to re-enable it I do not see bluetooth enabled.

How can I solve this or achieve my use case?

Best Regards,
Arjun

**Comment by xiewenxiang** [comment]
[gatt_server_service_table.zip](https://github.com/espressif/esp-idf/files/7381849/gatt_server_service_table.zip)

**Comment by Alvin1Zhang** [comment]
@arjaanda Thanks for reporting, would you please help share if any updates for the issue? Thanks.

**Comment by zhp0406** [comment]
Thank you for reporting the issue. We have addressed the issue in the latest branch, and the fix is included in the following commits: 91bd2c85412fad0d6bf6b7dd9061364fbb038af3 and 1ddcca6dcdf2a42fe64470721e4518d7e2d87f02.
