### ISSUE TITLE
print unicode unity test name in terminal (IDFGH-6047)

### ISSUE THREAD

**Issue by terryding77** [espressif/esp-idf#7730]
**Is your feature request related to a problem? Please describe.**

I use the esp-idf v4.3, and use unity test to check my program.
Now, I find in unity test, I can not get readable test name output in console, if I use the unicode test name, as I said in ThrowTheSwitch/Unity#582. 

for code https://github.com/espressif/esp-idf/blob/b86fe0c66ca17d5907ae26ecdffc9d4eb79cec07/components/unity/unity_runner.c#L111-L115

the ```unityPrint``` can not print unicode in readable format.
for example:
test name: 常规测试 (which means normal test)
unity print: \xE5\xB8\xB8\xE8\xA7\x84\xE6\xB5\x8B\xE8\xAF\x95 (which is unreadable)

**Describe the solution you'd like**

Can we change the test name print solution.
At least, can we support the flag to use ```Printf``` to replace the ```unityPrint``` function, if we prefer printing readable unicode test name.

**Comment by o-marshmallow** [comment]
Hi @terryding77 ,

Thanks for reporting this, the fact is `Unity` framework was not written by Espressif at first, it is part of this Github project: https://github.com/ThrowTheSwitch/Unity

So maybe it would be more valuable/convenient to first post this feature request to that project.

Anyway, for ESP-IDF, what you can do is to let the linker replace all calls to `UnityPrint` to another function. This wrapper would simply call `esp_rom_printf`. Here is how you can do:
In your main file:
```
/* Wrapper that will be called instead of UnityPrint */
void __wrap_UnityPrint(const char* str) {
    esp_rom_printf("%s", str);
}
```

Modify your `CMakeLists.txt` file to add a linker option (between `include` and `project`):
```
include($ENV{IDF_PATH}/tools/cmake/project.cmake)
[...]

/* Tell the linker to replace all calls to UnityPrint by calls to __wrap_UnityPrint */
idf_build_set_property(LINK_OPTIONS "-Wl,--wrap=UnityPrint" APPEND)

[...]
project(your_project_name)
```

Then rebuild, flash and execute, you should see UTF-8 characters showing properly.

**Comment by o-marshmallow** [comment]
@0xjakob `unity_run_single_test` is part of IDF, but `UnityPrint` comes from the Unity project I linked above. Two possibilities then:
* Replace all the calls to `UnityPrint` in ESP-IDF-owned Unity files
* Fix `UnityPrint`
* Wrap all calls to `UnityPrint` from the user project

**Comment by Alvin1Zhang** [comment]
@terryding77 Thanks for reporting, would you please help share if any updates for the issue? Thanks.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to short of feedback, feel free to reopen with more updates. Thanks.

**Comment by zikalino** [comment]
closing the issue as no further response
