### ISSUE TITLE
ESP32 Debug manager print getting stuck (IDFGH-6053)

### ISSUE THREAD

**Issue by dimpalsharm** [espressif/esp-idf#7735]
We are testing Debug manager with UHCI interrupt and getting expected print but after sometimes print is getting stuck.
But same we are printing through IO terminal then its not getting stuck there.

Could you please tell me the reason for this it is because of interrupt or other reason.

Thank You!!

**Comment by Alvin1Zhang** [comment]
@dimpalsharm Thanks for reporting, would you please help share more details? Thanks.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to short of feedback, feel free to reopen with more updates.
