### ISSUE TITLE
ESP32S2 Board scans 0 WiFi access point (IDFGH-6062)

### ISSUE THREAD

**Issue by sapanshah-eaton** [espressif/esp-idf#7744]
I am running esp-idf 4.2 version and few of the board started showing wifi issues. The board does not detect any wifi access point. The console log is here:

7104) map
I (399) esp_image: segment 5: paddr=0x000d91c8 vaddr=0x40029fc8 size=0x0d8f0 ( 5 5536) load
I (429) boot: Loaded app from partition at offset 0x10000
I (429) boot: Disabling RNG early entropy source...
Number of access points found: 0
================================================================================ ===
SSID | RSSI | CHANNEL | AUTH
================================================================================ ===

Initialized CR Task functionality
3 PROD_SPEC_WIFI_Init Inside Wifi init
3 WIFI_Station_Init Inside Wifi Station init
3 IOT_Net IoT initializing
3 Do_Onetime_Initialization SSL_Context Key Loading of CA Successful
4 IOT_Group_Handler Group 0 count = 16 cadence = 10000 ms for SeeMe,
4 IOT_Group_Handler Group 0 will publish all channels on connect
4 IOT_Group_Handler Group 1 count = 16 cadence = 60000 ms for , StoreMeOnInterv al
4 IOT_Group_Handler Group 1 will publish all channels on connect
4 IOT_Group_Handler Group 2 count = 16 cadence = 1000 ms for SeeMe,
4 IOT_Group_Handler Group 2 will publish all channels on connect
4 IOT_Group_Handler Group 3 count = 16 cadence = 1000 ms for ,
4 IOT_Group_Handler Group 3 will publish all channels on connect
3 Validate_Extract_Header_Handler Firmware_version : 1.1.1
3 Init_Handler Init validation of all image completed
1 Connection_Check_Timer_Task Network down
1 Connection_Check_Timer_Task Network down
1 Connection_Check_Timer_Task Network down

The same code is working okay on other board. 

Could you please help me debug this issue further?

**Comment by Alvin1Zhang** [comment]
Thanks for sharing the updates, which S2 board do you use ? Would you try to erase the SPI flash and download firmware again , then the S2 will redo RF self-calibration. Thanks.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to short of feedback, feel free to reopen with more updates.
