### ISSUE TITLE
USB CDC detect dis-/connect Events (IDFGH-6065)

### ISSUE THREAD

**Issue by moefear85** [espressif/esp-idf#7747]
Currently, there are are no dis-/connect events for usb cdc. Checking DTR/RTS is not a reliable way to detect usb dis-/connects, since many tools, including esptool.py, make non-standard use of them. This means there is no definite, unambiguous way to differentiate a dtr/rts toggle from a dis-/connect. Hence any call to tinyusb_cdcacm_write_flush(...) while the USB is disconnected, silently hangs. Using a timeout isn't a reliable solution, because it still causes hangs until the timeout is triggered, which would require very small values for it, but there are cases where larger timeouts are necessary under the assumption that the usb is still connected. Hence timeouts are also not a reliable/unambiguous way to detect USB disconnects.

Optionally, an additional esp-idf function that when called, returns a value that indicates USB connection status, would be a good idea.

**Comment by igrr** [comment]
Linking the related upstream issue: https://github.com/hathach/tinyusb/issues/482

**Comment by moefear85** [comment]
TinyUSB does provide disconnect events for USB... the issue is simply that esp additions to CDC-ACM don't pass these on. One can manually register for those events though, look into components/tinyusb/tinyusb/usbd.c.

**Comment by dreamtrek** [comment]
got the same issue. I found unplugging event in usbd.c, but it never trigged.

**Comment by moefear85** [comment]
Upon closer inspection of usbd.c, and seeing the line 583:

> if (tud_suspend_cb) tud_suspend_cb(...);

I realize why defining tud_suspend_cb works as a solution. Further testing also revealed DCD_EVENT_UNPLUGGED is never triggered because of reasons you mentioned above. The first time I looked at the code in the past, I just assumed since they are there, they get triggered. I see now this assumption was false. thx for the tip. Still, recieving DCD_EVENT_SUSPEND and DCD_EVENT_BUS_RESET are close and useful enough. But there is no assignable callback for it, so something like:

> if (tud_reset_cb) tud_suspend_cb(...);

would also be useful. Also, as a suggestion for the future when unifying the callback system, wouldn't the default event loop be ideal for this purpose? thx anyways. I'll close this for now since it contains enough information for others to move forward and prevent unwanted blocking when the usb cable is unplugged.

**Comment by wuyuanyi135** [comment]
I was investigating the same thing these days. I found checking `tud_cdc_n_connected` reflects the correct state of whether the CDC port has been opened or not.
