### ISSUE TITLE
BluFi with Nimble: Dummy informations in advertising packet, less space for usefull informations (IDFGH-6066)

### ISSUE THREAD

**Issue by caipiblack** [espressif/esp-idf#7748]
## Environment

- Development Kit:     none
- Module or chip used:  ESP32
- IDF version: Release 4.3.1
- Build System:         idf.py
- Compiler version: /
- Operating System:     Linux
- Using an IDE?: Yes (Eclipse)
- Power Supply:         USB

## Problem Description

The BLE advertising packet created from BluFi component has a different behavour with Nimble and Bluedroid:

With the Nimble port, BluFi implements optionnal informations in the advertising packet that was not present in Bluedroid port. The problem is that now (if we want to use NimBLE) we have less space to store the `Device Name (type=0x09)` in the advertising packet because of these (dummy) informations.

The informations that has been added:
- `TX Power Level (type=0x0a)`
- `16 bit Service Class UUID (type=0x03)` (value = `BLUFI_APP_UUID` = `0xffff`)

So with the Nimble port we just have 19 bytes available for the `Device Name` instead of 26 (maximum packet length: 31 bytes). 

![image](https://user-images.githubusercontent.com/29680146/138305758-aecd0e6f-74d8-49b2-ac36-1d1f89e1bcf4.png)

### Expected Behavior

The advertising packet should contains only `Device Name` informations.

### Actual Behavior

The advertising packet contains `Device Name`, `TX Power Level` and `16 Bit Service Class UUID` informations.

### Steps to reproduce

1. Use the example from this folder: `examples/bluetooth/blufi/main`
2. Build it with NimBLE

## Possible fix

The function `esp_blufi_adv_start()` in `esp_blufi.c` :

![image](https://user-images.githubusercontent.com/29680146/138306881-645f1d78-cb4d-4abd-9484-734211a987ce.png)

- Remove the dummy informations from `esp_blufi_adv_start()` in `esp_blufi.c`.
- Add variables to the function `esp_blufi_adv_start()` in order to enable/disable the transmission of the dummy informations in the advertising packet (if someone need it)

**Comment by rahult-github** [comment]
Hi @caipiblack ,

 Thanks for reporting this issue. Please note that the blufi example provided as part of release is an example to showcase the functionality. The existing application is sufficient to get the needed end to end functionality.  Nimble being open source stack, we put the fields in the adv packets by referring to existing applications to be in sync with upstream code  ( not blufi but other similar app like bleprph).

However, if for your usage, those fields are not to be used, you can remove them and add proprietory information as per need. 
  
Thanks,
 Rahul

**Comment by rahult-github** [comment]
Closing this issue. Please feel free to re-open in case of any further requests.
