### ISSUE TITLE
Incorrect CS hold time in ENC28J60 example using ESP32S2 (IDFGH-6077)

### ISSUE THREAD

**Issue by NorbertoNorbs** [espressif/esp-idf#7758]
## Environment

- Development Kit:   ESP32-S2-Saola-1
- Kit version (for WroverKit/PicoKit/DevKitC): N/A
- Module or chip used:  ESP32S2-WROVER
- IDF version : v4.4-dev-2875-g5f38b766a8
- Build System:  CMake
- Compiler version: xtensa-esp32s2-elf-gcc.exe (crosstool-NG esp-2021r1) 8.4.0
- Operating System:  Windows
- (Windows only) environment type: ESP Command Prompt
- Using an IDE?:  Yes Eclipse with IDF Plugin
- Power Supply: external 5V

## Problem Description

When using the ENC28J60  example the CS hold time is not enough and causes failure reading/write phy registers.
This is issue is related to https://github.com/espressif/esp-idf/issues/7156. The fix provided don't seems to work for ESP32S2 (I don't have a ESP32 to test).

I'm using the following config:

SPI Host: 2
SCLK GPIO: 12
MOSI GPIO: 11
MISO GPIO: 13
CS GPIO: 10
Clock: 8Mhz
Interrupt GPIO: 14

### Expected Behavior

The value for **cs_ena_posttrans** calculated by the function **enc28j60_cal_spi_cs_hold_time** for 8Mhz is 2 but the hardware seems not to hold the CS for 2 cycles (I would expect 2 cycles to be 250ns) but only 1.

### Actual Behavior

A value of 1 in **cs_ena_posttrans** generates a CS hold of ~13ns, 2 generates ~134ns and 3 ~263ns

Attached is the scope capture of the communication (showing clock and CS only).

cs_ena_posttrans = 2:
![cs_ena_posttrans_with_2](https://user-images.githubusercontent.com/84803097/138560944-03bde853-2f8b-4020-8aed-292e32cdce97.png)

cs_ena_posttrans = 3:
![cs_ena_posttrans_with_3](https://user-images.githubusercontent.com/84803097/138560942-952586bd-9b74-4665-8680-b5b3d7474f67.png)

## Possible fix

Since cs_ena_posttrans seems to start with 2 I changed enc28j60_cal_spi_cs_hold_time to account for that:

```
static inline uint8_t enc28j60_cal_spi_cs_hold_time(int clock_speed_mhz)
{
    if (clock_speed_mhz <= 0 || clock_speed_mhz > 20) {
        return 0;
    }
    int temp = clock_speed_mhz * CS_HOLD_TIME_MIN_NS;
    uint8_t cs_posttrans = temp / 1000;
    if (temp % 1000) {
        cs_posttrans += 1;
    }

    return cs_posttrans+1;  //<< 
}
```

## Debug Logs

I (288) gpio: GPIO[14]| InputEn: 0| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 
I (298) enc28j60: revision: 6
E (308) enc28j60: enc28j60_init(307): wrong chip ID
E (308) esp_eth: esp_eth_driver_install(222): init phy failed
ESP_ERROR_CHECK failed: esp_err_t 0xffffffff (ESP_FAIL) at 0x40027644

**Comment by kostaond** [comment]
@NorbertoNorbs just FYI, the SPI driver fix is currently in internal review...

**Comment by NorbertoNorbs** [comment]
@kostaond Thanks for the update, when ready I will test again with the same setup.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, the fix on master is https://github.com/espressif/esp-idf/commit/d500c8205ea4a00ca5ed79c0d0230361f71e6d4c, we are back porting the fix until release/4.2, will update further when the fixes sync to GitHub.

**Comment by AxelLin** [comment]
v4.4: 114003642445f8bc737f51c78b799c11299072e0
v4.3: b3c51e74c821aca1a69b97e6e68e4b9bd6dc9e8b
v4.2: ca6636c33e409e3a4e5e187d980ab05d05656a1d
This can be closed.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting and sharing the updates, feel free to reopen if the issue still happens, thanks.
