### ISSUE TITLE
[TW#13853] 蓝牙 调用osi_alarm_set 失败

### ISSUE THREAD

**Issue by bingbingbian** [espressif/esp-idf#776]
我用FreeRTOS Timer 做了个led闪烁的驱动，每次调用xTimerCreate,就会导致 蓝牙固件中osi_alarm_set() 失败，从而导致蓝牙工作不正常。

后来测试中，menuconfig 中配置FreeRTOS 只在第一个core上工作，然后就不会出现上述的问题。此问题该如何解决？

**Comment by igrr** [comment]
Can you please post a link to the code you are running?

**Comment by bingbingbian** [comment]
This is my code:  https://github.com/bingbingbian/esp32_blufi.git
see README ，ThankYou。

**Comment by bingbingbian** [comment]
what‘s the problem？

**Comment by blueMoods** [comment]
@bingbingbian  该问题的原因为：在双核模式下，BLE 和应用层代码同时在不同核上调用计时器 ，导致队列满了并在限定时间内无法获得资源，就会导致蓝牙固件中 osi_alarm_set() 失败。我们将会在未来几天更新代码解决此问题。谢谢。

**Comment by Yulong-espressif** [comment]
@bingbingbian We have resolved the problem, please update the Master, thanks.
