### ISSUE TITLE
[TW#13854] extern "C" protection missing in esp-idf/components/soc/esp32/include/soc/timer_group_struct.h

### ISSUE THREAD

**Issue by HubbyGitter** [espressif/esp-idf#777]
The subject says it all; see [here](https://github.com/espressif/esp-idf/blob/e173dd400ddeff6caf94498a9353abe8e759ccfa/components/soc/esp32/include/soc/timer_group_struct.h#L16).

Relevant since it seems that this header must be included separately when using timer goups; see e.g. [here](https://github.com/espressif/esp-idf/blob/e173dd400ddeff6caf94498a9353abe8e759ccfa/examples/peripherals/timer_group/main/timer_group_example_main.c#L15).

**Comment by igrr** [comment]
Fixed in https://github.com/espressif/esp-idf/commit/c7173e0d08feeb58f4a8451051ec740e336fa6ab.
