### ISSUE TITLE
esp32c3外挂两种不同型号的flash芯片，一种运行正常，一种运行异常 (IDFGH-6092)

### ISSUE THREAD

**Issue by LiuWenPeng666** [espressif/esp-idf#7771]
# 使用官方例程 Blufi

# SDK配置如下：

1、配置工程为esp32c3，
2、分区表采用自定义，配置成如下：

###### #Name,   Type, SubType, Offset,   Size, Flags

nvs,      data, nvs,     0x9000,        0x4000,
otadata,  data, ota,     0xd000,        0x2000,
phy_init, data, phy,     0xf000,        0x1000,
ota_0,    app,  ota_0,   0x10000,        1920k,
3、esp32c3-specific中配置版本支持为 Rev3
4、使用4.3.1版本 commit:：
2e74914051d14ec2290fc751a8486fb51d73a31e

# 运行异常的log如下：

Compressed 8192 bytes to 31...
Writing at 0x0000d000... (100 %)
Wrote 8192 bytes (31 compressed) at 0x0000d000 in 0.2 seconds (effective 385.5 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting via RTS pin...
Executing action: monitor
Running idf_monitor in directory /mnt/e/ESP32/workspace/esp-idf/examples/bluetooth/blufi-c3
Executing "/home/liuwenpeng/.espressif/python_env/idf4.4_py3.8_env/bin/python /mnt/e/myworkspace/esp-idf/tools/idf_monitor.py -p /dev/ttyS12 -b 115200 --toolchain-prefix riscv32-esp-elf- --target esp32c3 --decode-panic backtrace /mnt/e/ESP32/workspace/esp-idf/examples/bluetooth/blufi-c3/build/blufi_demo.elf -m '/home/liuwenpeng/.espressif/python_env/idf4.4_py3.8_env/bin/python' '/mnt/e/myworkspace/esp-idf/tools/idf.py' '-p' '/dev/ttyS12' '-b' '921600'"...
--- idf_monitor on /dev/ttyS12 115200 ---
--- Quit: Ctrl+] | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---
ESP-ROM:esp32c3-api1-20210207
Build:Feb  7 2021
rst:0x1 (POWERON),boot:0xd (SPI_FAST_FLASH_BOOT)
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fcd6100,len:0x1f94
ets_loader.c 78 
ESP-ROM:esp32c3-api1-20210207
Build:Feb  7 2021
rst:0x7 (TG0WDT_SYS_RST),boot:0xd (SPI_FAST_FLASH_BOOT)
Saved PC:0x40049a42
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fcd6100,len:0x1f94
ets_loader.c 78 
ESP-ROM:esp32c3-api1-20210207
Build:Feb  7 2021
rst:0x7 (TG0WDT_SYS_RST),boot:0xd (SPI_FAST_FLASH_BOOT)
Saved PC:0x40049a42
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fcd6100,len:0x1f94
ets_loader.c 78 
ESP-ROM:esp32c3-api1-20210207
Build:Feb  7 2021
rst:0x10 (RTCWDT_RTC_RST),boot:0xd (SPI_FAST_FLASH_BOOT)
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fcd6100,len:0x1f94
ets_loader.c 78 
ESP-ROM:esp32c3-api1-20210207
Build:Feb  7 2021
rst:0x7 (TG0WDT_SYS_RST),boot:0xd (SPI_FAST_FLASH_BOOT)
Saved PC:0x40049a42
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fcd6100,len:0x1f94
ets_loader.c 78 
ESP-ROM:esp32c3-api1-20210207
Build:Feb  7 2021
rst:0x7 (TG0WDT_SYS_RST),boot:0xd (SPI_FAST_FLASH_BOOT)
Saved PC:0x40049a42
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fcd6100,len:0x1f94
ets_loader.c 78 
ESP-ROM:esp32c3-api1-20210207
Build:Feb  7 2021
...

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, feel free to reopen.
