### ISSUE TITLE
I2S signals from HFP-AG and HFP-HF (IDFGH-6095)

### ISSUE THREAD

**Issue by skateskate** [espressif/esp-idf#7774]
## Environment

- Development Kit: two LyraTs v4.3
- IDF version: v4.3.1-245-gba15ac8634 installed from "esp-idf-tools-setup-online-2.11" , release/v4.3
- Build System: idf.py
- Compiler version: xtensa-esp32-elf-gcc --version
- Operating System: Windows
- environment type: ESP Command Prompt
- Using an IDE?: Yes, ESP-IDF Eclipse
- Power Supply:  USB

## Problem Description
I have two LyraT v4.3, one flashed with `examples\bluetooth\bluedroid\classic_bt\hfp_ag` and the other one with `examples\bluetooth\bluedroid\classic_bt\hfp_hf`. I am trying to measure the I2S audio signals from the I2S pin header present on the boards. I need to establish a wide band connection (16 kHz sample rate) between the two boards. These are the main settings I changed in the sdkconfigs:
- `BR/EDR Sync(SCO/eSCO) max connections --> 1`
- `BR/EDR Sync(SCO/eSCO) default data path --> PCM`
- `audio(SCO) data path --> HCI` in order to unlock the wide band speech setting
- `Wide band speech --> ON`

Are these settings right? Could someone please explain in simple words the meaning of `BR/EDR Sync(SCO/eSCO) default data path`, `audio(SCO) data path` and when to use `PCM/HCI`? I could not find any explanations in the docs. Sorry but this is my first time with ESP32 programming.

### Expected Behavior
Measure the I2S signals from the LyraT I2S header.

### Actual Behavior
No signals can be measured from the I2S header. If `audio(SCO) data path` is set to `PCM` I can measure the 8 kHz clock but for my application I would need the 16 kHz one. Is it doable?
I also tried to change `BR/EDR Sync(SCO/eSCO) default data path` to `HCI` with no success.

## Debug Logs
Logs from AG:
```
hfp_ag> W (2374) BT_APPL: new conn_srvc id:5, app_id:0
I (2384) BT_APP_HF: APP HFP event: CONNECTION_STATE_EVT
I (2384) BT_APP_HF: --connection state CONNECTED, peer feats 0x0, chld_feats 0x0
E (2444) BT_BTC: btc_hf_cb_handler: Invalid index 23568
I (2464) BT_APP_HF: APP HFP event: CIND_RESPONSE_EVT
I (2464) BT_APP_HF: --CIND Start.
I (2504) BT_APP_HF: APP HFP event: CONNECTION_STATE_EVT
I (2504) BT_APP_HF: --connection state SLC_CONNECTED, peer feats 0xff, chld_feat                                   s 0x4010
hfp_ag>
hfp_ag> cona
Connect Audio
I (9994) BT_APP_HF: APP HFP event: AUDIO_STATE_EVT
I (9994) BT_APP_HF: --Audio State connecting
hfp_ag> I (10754) BT_APP_HF: APP HFP event: BCS_EVT
I (10764) BT_APP_HF: --Consequence of codec negotiation: Use MSBC
E (10784) BT_BTM: btm_sco_connected, handle 180
I (10794) BT_APP_HF: APP HFP event: AUDIO_STATE_EVT
I (10794) BT_APP_HF: --Audio State connected_msbc
W (10814) BT_APPL: bta_ag_sco_read_cback: status(2)
W (10824) BT_APPL: bta_ag_sco_read_cback: status(2)
W (11794) BT_APPL: bta_ag_sco_read_cback: status(2)
W (11864) BT_APPL: bta_ag_sco_read_cback: status(2)
W (11904) BT_APPL: bta_ag_sco_read_cback: status(2)
W (11994) BT_APPL: bta_ag_sco_read_cback: status(2)
W (12024) BT_APPL: bta_ag_sco_read_cback: status(2)
W (13394) BT_APPL: bta_ag_sco_read_cback: status(2)
W (13424) BT_APPL: bta_ag_sco_read_cback: status(2)
W (13544) BT_APPL: bta_ag_sco_read_cback: status(2)
W (13554) BT_APPL: bta_ag_sco_read_cback: status(2)
W (13644) BT_APPL: bta_ag_sco_read_cback: status(2)
I (13794) BT_APP_HF: speed(10.343962s ~ 13.348135s): 253.087952 kbit/s
```
Logs from HF:
```
hfp_hf> I (4743) BT_HF: Found a target device address:
I (4743) BT_HF: (mac addess here)
I (4743) BT_HF: Found a target device name: ESP_HFP_AG
Connect.
I (4763) BT_HF: ESP_BT_GAP_DISC_STATE_CHANGED_EVT
W (5843) BT_APPL: new conn_srvc id:27, app_id:1
I (5853) BT_HF: APP HFP event: CONNECTION_STATE_EVT
I (5863) BT_HF: --connection state connected, peer feats 0x0, chld_feats 0x0
I (5943) BT_HF: APP HFP event: CALL_IND_EVT
I (5943) BT_HF: --Call indicator NO call in progress
I (5943) BT_HF: APP HFP event: CALL_SETUP_IND_EVT
I (5943) BT_HF: --Call setup indicator NONE
I (5963) BT_HF: APP HFP event: NETWORK_STATE_EVT
I (5963) BT_HF: --NETWORK STATE available
I (5973) BT_HF: APP HFP event: SIGNAL_STRENGTH_IND_EVT
I (5973) BT_HF: -- signal strength: 4
I (5973) BT_HF: APP HFP event: ROAMING_STATUS_IND_EVT
I (5983) BT_HF: --ROAMING: inactive
I (5983) BT_HF: APP HFP event: BATTERY_LEVEL_IND_EVT
I (5993) BT_HF: --battery level 3
I (5993) BT_HF: APP HFP event: CALL_HELD_IND_EVT
I (5993) BT_HF: --Call held indicator NONE held
I (6013) BT_HF: APP HFP event: CONNECTION_STATE_EVT
I (6013) BT_HF: --connection state slc_connected, peer feats 0x36e, chld_feats 0x0
I (6023) BT_HF: APP HFP event: INBAND_RING_TONE_EVT
I (6023) BT_HF: --inband ring state Provided
I (13053) BT_HF: ESP_BT_GAP_MODE_CHG_EVT mode:2
I (14193) BT_HF: ESP_BT_GAP_MODE_CHG_EVT mode:0
E (14233) BT_BTM: btm_sco_connected, handle 181
I (14233) BT_HF: APP HFP event: AUDIO_STATE_EVT
I (14233) BT_HF: --audio state connected_msbc
I (21513) BT_HF: ESP_BT_GAP_MODE_CHG_EVT mode:2
```

## Other items if possible
[sdkconfigs.zip](https://github.com/espressif/esp-idf/files/7412559/sdkconfigs.zip)

**Comment by zhou88mang** [comment]
Hi， @skateskate Have you solved the problem? I have the same problem as you, I can't hear any sound from AG with i2s, if you have any ideas, please let me know, thank you!
