### ISSUE TITLE
Http websocket server should be able to distinguish clients (IDFGH-6100)

### ISSUE THREAD

**Issue by udaik** [espressif/esp-idf#7779]
The HTTP server component provides the Websocket server functionality, but when the client is connected, the HTTPd server data structures should provide a way to find which fd is connected to what client (URI), so that the server can decide what data to be pushed which fd.

**Comment by Alvin1Zhang** [comment]
@udaik Thanks for your contribution again, will close due to short of feedback, feel free to reopen with more updates.
