### ISSUE TITLE
ESP32S3 compile example a2dp_sink failed (IDFGH-6105)

### ISSUE THREAD

**Issue by Kevincoooool** [espressif/esp-idf#7783]
Hi,when i compiled the example a2dp_sink,the log was:
`nused-const-variable -MD -MT esp-idf/bt/CMakeFiles/__idf_bt.dir/host/bluedroid/hci/hci_layer.c.obj -MF esp-idf\bt\CMakeFiles\__idf_bt.dir\host\bluedroid\hci\hci_layer.c.obj.d -o esp-idf/bt/CMakeFiles/__idf_bt.dir/host/bluedroid/hci/hci_layer.c.obj -c F:/myesp/master/esp-idf/components/bt/host/bluedroid/hci/hci_layer.c
F:/myesp/master/esp-idf/components/bt/host/bluedroid/hci/hci_layer.c: In function 'hci_layer_init_env':
F:/myesp/master/esp-idf/components/bt/host/bluedroid/hci/hci_layer.c:184:5: error: implicit declaration of function 'btsnd_hcic_ble_sync_sem_init'; did you mean 'btsnd_hcic_ble_set_phy'? [-Werror=implicit-function-declaration]
     btsnd_hcic_ble_sync_sem_init();
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
     btsnd_hcic_ble_set_phy
F:/myesp/master/esp-idf/components/bt/host/bluedroid/hci/hci_layer.c: In function 'hci_layer_deinit_env':
F:/myesp/master/esp-idf/components/bt/host/bluedroid/hci/hci_layer.c:207:5: error: implicit declaration of function 'btsnd_hcic_ble_sync_sem_deinit'; did you mean 'btsnd_hcic_ble_clear_adv_set'? [-Werror=implicit-function-declaration]
     btsnd_hcic_ble_sync_sem_deinit();
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     btsnd_hcic_ble_clear_adv_set
F:/myesp/master/esp-idf/components/bt/host/bluedroid/hci/hci_layer.c: In function 'filter_incoming_event':
F:/myesp/master/esp-idf/components/bt/host/bluedroid/hci/hci_layer.c:443:36: error: implicit declaration of function 'btsnd_hcic_ble_get_sync_info'; did you mean 'btsnd_hcic_ble_ext_scan_enable'? [-Werror=implicit-function-declaration]
             BlE_SYNC *sync_info =  btsnd_hcic_ble_get_sync_info();
                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                    btsnd_hcic_ble_ext_scan_enable
F:/myesp/master/esp-idf/components/bt/host/bluedroid/hci/hci_layer.c:443:36: warning: initialization of 'BlE_SYNC *' {aka 'struct <anonymous> *'} from 'int' makes pointer from integer without a cast [-Wint-conversion]
cc1.exe: some warnings being treated as errors
[871/1279] Building C object esp-idf/bt/CMakeFiles/__idf_bt.dir/host/bluedroid/stack/avdt/avdt_scb_act.c.obj
ninja: build stopped: subcommand failed.
ninja failed with exit code 1`

I had changed the target as esp32s3.

**Comment by expresspotato** [comment]
> @Kevincoooool
> 
> The ESP32S3 doesn't support Classic Bluetooth.

Hi @xiewenxiang can you elaborate a little bit more? I'm struggling to create a cohesive product with what's provided by Espressif there is no Goldilocks zone version, everything's always one version too old and now one version too new of both the hardware and more importantly IDF. The versions are nearly always broken.

Are you saying there is no long going to be the ability to create an audio sink or hands free with the ESP32-S3?

**Comment by chegewara** [comment]
https://www.espressif.com/en/news/ESP32_S3

> Are you saying there is no long going to be the ability to create an audio sink or hands free with the ESP32-S3?

Yes, thats correct.

**Comment by expresspotato** [comment]
Okay and what about Bluetooth LE audio?

**Comment by xiongweichao** [comment]
@expresspotato ESP32S3 does not support LE audio.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, feel free to reopen.
