### ISSUE TITLE
NVS KEYS doesnt allow custom size (IDFGH-6111)

### ISSUE THREAD

**Issue by filzek** [espressif/esp-idf#7788]
In SDK Release V4.3.1 its doesnt allow a custom size partition of nvs_keys:
a partition that is made of like this
nvs_keys,       data,   nvs_keys,          ,    0x6300

always give a error: 
Failed to generate keys: [0x104] "(ESP_ERR_INVALID_SIZE)"

So, if a partition must have a valid ou fixed size it must be a mandatory in the docs, nowhere was telling it to be like that.

**Comment by mahavirj** [comment]
@filzek 

There is no check for NVS key partition size as such, please see code below:

https://github.com/espressif/esp-idf/blob/bcbef9a8db54d2deef83402f6e4403ccf298803a/components/nvs_flash/src/nvs_api.cpp#L578-L640

> if you try hex: 6300 (24k) it doesnt work return an error and doesnt let the nvs flash init to run okay and return error.

Do you mean size **0x6000** here (it must be sector aligned)? Can you please share your partition table here?

**Comment by igrr** [comment]
`ESP_ERR_INVALID_SIZE` is returned by `esp_partition_erase_range` when the size is not aligned for flash sector size (this behavior hasn't changed in 4.3).

We have added a check (warning) for unaligned partition sizes recently: https://github.com/espressif/esp-idf/commit/b56c9aafe46b00456c12b6979ee0c711575a5697 to detect incorrect partition sizes, like 0x6300

**Comment by mahavirj** [comment]
Closing based on above replies. Please feel free to let us know if problem still persist.
