### ISSUE TITLE
Enabling flash encryption causes "flash read err, 1000" (IDFGH-6113)

### ISSUE THREAD

**Issue by tobyloki** [espressif/esp-idf#7791]
## Environment

- Module or chip used: ESP32-WROOM-32D
- IDF version: 4.2.2
- Build System: idf.py
- Compiler version: xtensa-esp32-elf-gcc (crosstool-NG esp-2021r1) 8.4.0
- Operating System: Windows
- (Windows only) environment type: Plain Command Prompt
- Using an IDE?: No
- Power Supply: USB

## Problem Description
I've enabled flash encryption in my program which includes several of the example projects such as provisioning, nv, aws, gpio, timer, etc. After running `idf.py flash monitor`, it gives me the repeating below output. How do I fix this problem?

```
rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
flash read err, 1000
ets_main.c 371
```

partitions.csv
```
# Name,   Type, SubType, Offset,  Size,   Flags
nvs,      data, nvs,     0x11000, 0x6000
phy_init, data, phy,     0x17000, 0x1000, encrypted
factory,  app,  factory, 0x20000, 1600K,  encrypted
```

sdkconfig.defaults
```
# Serial flasher config
CONFIG_ESPTOOLPY_FLASHSIZE_2MB=y
CONFIG_ESPTOOLPY_FLASHSIZE="2MB"

# Security features
CONFIG_SECURE_FLASH_ENC_ENABLED=y
CONFIG_SECURE_FLASH_ENCRYPTION_MODE_RELEASE=y
```

**Comment by tobyloki** [comment]
How can I enable flash encryption in release mode, but still be able to update the device's firmware without OTA & also read the monitor logs?

**Comment by negativekelvin** [comment]
You have to burn the encryption key first before flashing and save it so you can encrypt the bin files

**Comment by tobyloki** [comment]
I'm trying to run `espsecure.py generate_flash_encryption_key my_flash_encryption_key.bin`, but I keep getting the below error. Do you know how to fix it?

```
'espsecure' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by mahavirj** [comment]
@tobyloki 

Please refer to https://docs.espressif.com/projects/esp-idf/en/latest/esp32/security/flash-encryption.html#flash-encryption-configuration, this should provide all information regarding "Release" and "Development" mode. 

To keep UART download mode enabled, please ensure that you have not selected `SECURE_DISABLE_ROM_DL_MODE` in `sdkconfig`.

> 'espsecure' is not recognized as an internal or external command,

- Please ensure that you have run IDF installation commands, i.e. `install.sh` followed by `. ./export.sh`. This shall export correct path to find espsecure.py script. 
- FWIW, This script is present at `./components/esptool_py/esptool/espsecure.py` within IDF

**Comment by Alvin1Zhang** [comment]
@tobyloki Thanks for reporting, would you please help share if any updates for the issue? Thanks.

**Comment by mahavirj** [comment]
Closing due lack of update, please feel free to re-open if you are still facing any issue.
