### ISSUE TITLE
HFP-AG example not working as intended (IDFGH-6114)

### ISSUE THREAD

**Issue by MarcosHWconfig** [espressif/esp-idf#7792]
## Environment

- Development Kit: ESP32-LyraT v4.3
- Module or chip used: ESP32-WROVER-E
- IDF version: v4.3.1-245-gba15ac8634
- Build System: idf.py
- Compiler version: xtensa-esp32-elf-gcc --version
- Operating System: Windows
- (Windows only) environment type: ESP Command Prompt
- Using an IDE?: No
- Power Supply: USB

## Problem Description
I flashed the `esp-idf\examples\bluetooth\bluedroid\classic_bt\hfp_ag` example in my LyraT after modifying the following parameters from the menuconfig:

- `BR/EDR Sync(SCO/eSCO) max connections --> 1`
- `BR/EDR Sync(SCO/eSCO) default data path --> HCI`
- `audio(SCO) data path --> HCI`
- `Wide band speech --> ON`

From the example code I see that the AG sends a sinusoid to the connected client. I used several pairs of bluetooth headphones (fully functional) as clients but the only thing I hear is noise, definitely not a sinusoid. I have recorded the received signal, here is the plot:
<img width="407" alt="out" src="https://user-images.githubusercontent.com/91611724/139255410-9a50d663-eb28-4272-a97c-2efbf0584198.png">

### Expected Behavior
Hear the sinusoid correctly from the client side.

### Actual Behavior
I hear a strange noise from the client side, not a sinusoid.

### Steps to reproduce

1. Get the code `esp-idf\examples\bluetooth\bluedroid\classic_bt\hfp_ag`
2. Change `BR/EDR Sync(SCO/eSCO) max connections --> 1`, `BR/EDR Sync(SCO/eSCO) default data path --> HCI`, `audio(SCO) data path --> HCI`, `Wide band speech --> ON`
3. Edit `app_hf_msg_set.c` and set the MAC address of the client
4. Open serial console, type `con` and after connection type `cona`
5. Hear the noise from the client

**Comment by skateskate** [comment]
I am testing the same configuration as @MarcosHWconfig and I also have the same problem with the sinusoid. 
Can someone look into it? Maybe @Wth-Esp can help us?

**Comment by Wth-Esp** [comment]
hi all,

my colleague is handling this issue, could you  @BetterJincheng please provide a patch here?

Thanks!

**Comment by BetterJincheng** [comment]
[patch.zip](https://github.com/espressif/esp-idf/files/7465215/patch.zip)[Uploading patch.zip…]()

Hi all, 

This is the patch for this issue towards IDF_V4.3. 
Try to use it by : 
`unzip patch.zip`
`git apply [patch_name]`

Turn to us if any problems.

**Comment by skateskate** [comment]
Hello @BetterJincheng and @Wth-Esp, thanks for the patch. 
On my system the sinusoid is now ok, but I can still hear some spikes now and then (let's say 3-4 spikes every 10 seconds). Is it normal?
If you don't mind I have another question: what is the purpose of the timer that runs out every 4000 microseconds (`PCM_GENERATOR_TICK_US`)? If I understand correctly, it is used to release the semaphore to the function that generates `frame_data_num` samples of the sinusoid, but why 4000 microseconds precisely? Could the spikes be related to this?

**Comment by BetterJincheng** [comment]
Hi @skateskate,

Codec (code & decode) for HFP is mSBC with specific parameters. It transfers 240 Bytes every 7.5 ms. So in the demo we need to `create` 240 Bytes every 7.5ms. `PCM_GENERATOR_TICK_US` is just the periodic duration we `create` the input audio data in the purpose of simulating a role of microphone. You can set it to any value as you want.
