### ISSUE TITLE
【Issue Confirmation】 Can ESP-IDF support scan and adv simultaneously? (IDFGH-6115)

### ISSUE THREAD

**Issue by xiaolongba** [espressif/esp-idf#7793]
Hi Espressif Experts,

this question may be a bit stupid, that is the current esp-idf can support scan and adv simultaneously? the  reason why I asked this is that I looked into the [ibeacon example project](https://github.com/espressif/esp-idf/blob/bcbef9a8db54d2deef83402f6e4403ccf298803a/examples/bluetooth/bluedroid/ble/ble_ibeacon/main/esp_ibeacon_api.h#L30), it showed me the following comment, as below:

```
/* Because current ESP IDF version doesn't support scan and adv simultaneously,
 * so iBeacon sender and receiver should not run simultaneously */

```

is that true? I checked from other tickets, it told me that it supported this feature already, so could you help me double check?

thanks in advance.

**Comment by xiaolongba** [comment]
any updates about it?

**Comment by xulongzhuang** [comment]
@xiaolongba Are you talking about BLE broadcasting and scanning at the same time? [gattc_gatts_coex](https://github.com/espressif/esp-idf/tree/master/examples/bluetooth/bluedroid/coex/gattc_gatts_coex) is a good example

**Comment by xiaolongba** [comment]
> Are you talking about BLE broadcasting and scanning at the same time? [gattc_gatts_coex](https://github.com/espressif/esp-idf/tree/master/examples/bluetooth/bluedroid/coex/gattc_gatts_coex) is a good example

Exactly, Bro.  so the current esp-idf can support this feature? if yes, pls close this ticket, I just to confirm this feature if it is present.

**Comment by xulongzhuang** [comment]
yes，esp-idf can support scan and adv simultaneously，Our engineers will revise this comment in the follow-up, thank you for your report

**Comment by xiaolongba** [comment]
Perfect 👌 , you can close this ticket now
