### ISSUE TITLE
MQTT event->data value is keeping old values (IDFGH-6116)

### ISSUE THREAD

**Issue by edouardreg** [espressif/esp-idf#7794]
Hello,

Last esp-idf master :

When using event->data in MQTT (suscribe to a topic and the topic if modified by an other client)  if the lenght of data of the new event is shorter than the older event, the event->data string still have the lenght of the older event and characters after the lenght of the new event are characters from the older event.

Perhaps it's me ? But regarding a lot and don't see any way to solve on my side.....

**Comment by Alvin1Zhang** [comment]
@edouardreg Thanks for reporting. Would you please help share if any updates or details for this issue? Thanks.

**Comment by Alvin1Zhang** [comment]
@edouardreg Thanks for reporting. Would you please help share if any updates or details for this issue? Thanks.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to short of feedback, feel free to reopen with more updates.
