### ISSUE TITLE
hid host reconnection issue (IDFGH-6117)

### ISSUE THREAD

**Issue by brilliantWorks** [espressif/esp-idf#7795]
IDF version: v4.3

Using the esp_hid_host example, I want to automatically reconnect after bonding the **ble hid device**.

after **bt hid** mouse is bonded, bt hid mouse is reconnected automatically when power reset.

```
I (7945) BT_HIDH: Device Not Found? It's probably a reconnect.
I (7955) ESP_HIDH_DEMO: f0:65:dd:c3:e1:aa OPEN: 
BDA:f0:65:dd:c3:e1:aa, Status: OK, Connected: YES, Handle: 0, Usage: MOUSE
Name: , Manufacturer: , Serial Number: 
PID: 0xa004, VID: 0x04e8, VERSION: 0x0216
Report Map Length: 172
  CCONTROL   INPUT REPORT, ID:   3, Length:   7
  CCONTROL   INPUT REPORT, ID:   5, Length:   1
   GENERIC   INPUT REPORT, ID:   4, Length:   1
     MOUSE   INPUT   BOOT, ID:   2, Length:   4
     MOUSE   INPUT REPORT, ID:   2, Length:   5
```

When using the **ble** hid mouse,
There is no response from the hid host, and automatic reconnection is not working.

Any help would be much appreciated.
Thanks

**Comment by xiongweichao** [comment]
Hi @brilliantWorks ，

Sorry for the late reply. May I ask if this problem still exists?

Thanks

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, feel free to reopen with more updates.
