### ISSUE TITLE
`realpath` libc defined but not implemented (IDFGH-6119)

### ISSUE THREAD

**Issue by ivmarkov** [espressif/esp-idf#7798]
Currently, the Rust STD equivalent of `realpath` ([fs::canonicalize]()) is implemented to call into `realpath`, and as a result, usage of `fs::realpath` results in a linkage error. This is not so ideal.

How do we feel about implementing `realpath` in ESP-IDF itself? Basically "Option A" as documented here:
https://github.com/ivmarkov/rust-esp32-std-demo/blob/6611e765441d8cc3a6d018ece935f521b4fe7e79/src/main.rs#L975

**Comment by igrr** [comment]
@ivmarkov Thanks for the suggestion, we can implement `realpath` in IDF. We can't use the newlib code you've linked because it is released under LGPL, i think. However given the absence of symlinks the implementation shouldn't be difficult.

**Comment by ivmarkov** [comment]
Sure - the linked code was just an example that the function can be trivially implemented in terms of parsing the path and handling the `..`s and skipping the `.`s (that is - in the absence of symlinks on FAT and no current directory).

If you decide to implement this one, perhaps it makes sense to also implement:
* `getcwd` - to always return `/`, as `realpath` would be expanding relative directories as if cwd is `/`
* `chdir` - to fail with `ENOSYS`

**Comment by ivmarkov** [comment]
@igrr `realpath` implementation works great. Tested:
- Usage of `realpath` via Rust's `fs::canonicalize` API
- Crate `panic_abort` now works without the `panic_immediate_abort` option, which allows Rust code to print nice panic / assertion messages before giving control to ESP-IDF's panic handler. 

Please merge into v4.4
I'll probably backport this code into v4.3.1 in the form of a patch that is applied (as usu.) when compiling the ESP-IDF for Rust.

**Comment by igrr** [comment]
Backported to release/v4.4 in https://github.com/espressif/esp-idf/commit/f158a0d538ea53c7346c2c3188e027f6f81bea04, will be part of v4.4-rc1.
