### ISSUE TITLE
The esp_ota_write function causes an error: Guru Meditation Error: Core 0 panic'ed (Cache disabled but cached memory region accessed)

### ISSUE THREAD

**Issue by NewYaroslav** [espressif/esp-idf#780]
Hi. I'm trying to implement the firmware update by air.
While the firmware is being downloaded through the air, the same error always occurs:

>  Guru Meditation Error: Core  0 panic'ed (Cache disabled but cached memory region accessed)

The error occurs randomly, no matter how many data packets have already been downloaded.
The error occurs when the esp_ota_write function is called. How can I fix this problem?

**Comment by NewYaroslav** [comment]
This was a hardware problem related to the power supply of the esp32 module

**Comment by HubbyGitter** [comment]
Brownout?
