### ISSUE TITLE
Hardware description needed for PPPOS Client using BG96 (IDFGH-6128)

### ISSUE THREAD

**Issue by Vaishnavibhavaa** [espressif/esp-idf#7807]
## Environment

- Development Kit:      [ESP32-DevKitC]
- Kit version (for WroverKit/PicoKit/DevKitC): [v1]
- Module or chip used:  [ESP32-WROOM-32D]
- IDF version (run ``git describe --tags`` to find it):
    // v4.3
- Build System:         [idf.py]
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it):
    // 1.22.0-80-g6c4433a
- Operating System:     [Windows]
- (Windows only) environment type: [|ESP Command Prompt|powerShell].
- Using an IDE?: [Yes]
- Power Supply:         [USB]

## Problem Description

Not able to get hardware connection details for PPPOS client example. Pin mapping for RX,TX, RTS,CTS is not available.

Error:
E (970) esp-modem: esp_modem_dte_send_cmd(305): process command timeout
E (970) dce_service: esp_modem_dce_sync(48): send command failed
E (970) bg96: bg96_init(461): sync failed

Not able to send AT commands to BG 96
![WhatsApp Image 2021-11-01 at 9 56 56 AM](https://user-images.githubusercontent.com/91455466/139663168-e9e6c2e0-4390-45fa-9670-f06779ff4fd6.jpeg)
![WhatsApp Image 2021-11-01 at 9 56 26 AM](https://user-images.githubusercontent.com/91455466/139663181-88663872-d2ef-4bbf-aeec-2e430c0250d3.jpeg)

**Comment by david-cermak** [comment]
Hi @Vaishnavibhavaa 

My guess is that your modem device needs an external power, so the red wire from your `ESP32-WROOM` kit is not enough to provide sufficient power supply to your `BG96`.
Connecting is described in the [example README](https://github.com/espressif/esp-idf/tree/master/examples/protocols/pppos_client#pin-assignment) and could be changed in the menuconfig. If you leave the UART configuration unset, the default connection is simply:

| gpio | function |
|-- | --|
| GPIO25 | RX |
 |GPIO26 | TX |
| GND | GND |

(no need to configure and connect `RTS` and `CTS` if flow-control disabled)

**Comment by AxelLin** [comment]
> BTW i didnt test too much with recent modem pppos, but it works better to me with code from before last update

What issue did you hit with last update?

**Comment by Alvin1Zhang** [comment]
@Vaishnavibhavaa Thanks for reporting, would you please help share if any updates for the issue? Thanks.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, feel free to reopen. Thanks.
