### ISSUE TITLE
const string used in inline/IRAM function end up in DRAM .data section (IDFGH-6139)

### ISSUE THREAD

**Issue by philippe44** [espressif/esp-idf#7818]
While investigating https://github.com/espressif/esp-idf/issues/7813, I found that libheap.a had an important increase of DRAM .data usage between IDF 4.0 and 4.3. It turned out that all the heap_tlsf functions are inline and use a lot of strings in the assert(). Unfortunately, as a result, the linker put all these function in IRAM but the strings that are used also seems to be put in DRAM .data section, leading to lose more than 1.5kB of data because there is a fair amount of these strings in heap_tlsf (was not in 4.0)

**Comment by sle118** [comment]
that is definitely an interesting find!
