### ISSUE TITLE
BLE Python test tools for examples don't support ESP32-C3 (IDFGH-6155)

### ISSUE THREAD

**Issue by dazzalicious** [espressif/esp-idf#7832]
I'm trying to run the BLE nimble examples and they flash onto the ESP32-C3 chip no worries and I can use other devices to connect so I believe they are working fine. It is just when I try to use the python scripts for testing such as blecent_test.py in the blecent example I get the error report below which I guess means that the script doesn't support the C3 chip. It would be great if these could be updated.

![Screenshot from 2021-11-04 17-00-11](https://user-images.githubusercontent.com/82013892/140265719-7cde0384-0d69-4332-b69a-656d57bcddc6.png)

**Comment by krzychb** [comment]
Hi @dazzalicious, "blecent_test.py" (and other "_test.py" scripts in the [examples](https://github.com/espressif/esp-idf/tree/master/examples) directory) are intended primarily for continuous integration (CI), not for using locally. See some background information in https://esp32.com/viewtopic.php?t=22552.

**Comment by dobairoland** [comment]
I'm not entirely familiar with the BLE examples but they don't seem to support any chip beside ESP32. Please notice the first line of the examples' READMEs. They state that the supported target is ESP32 (only).

**Comment by dazzalicious** [comment]
> I'm not entirely familiar with the BLE examples but they don't seem to support any chip beside ESP32. Please notice the first line of the examples' READMEs. They state that the supported target is ESP32 (only).

I've been able to get them to flash and function on the ESP32-C3 chip. I'm a noob with this though.
