### ISSUE TITLE
no explanation ESP_APP_ID define in gatt_server_service_table example (IDFGH-6161)

### ISSUE THREAD

**Issue by Szymono** [espressif/esp-idf#7838]
Hello , 

I try to understand what mean 
```*.c
#define ESP_APP_ID                  0x55
```
I can't find any explanation what exactly the value do and also why it's set to 0x55. 

I hope u can easy explain and maybe it's good idea to update [DS](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/bluetooth/esp_gatts.html?highlight=esp_ble_gatts_app_register#_CPPv426esp_ble_gatts_app_register8uint16_t) or [Gatt_Server_Service_Table_Example_Walkthrough.md](https://github.com/espressif/esp-idf/tree/master/examples/bluetooth/bluedroid/ble/gatt_server_service_table/tutorial/Gatt_Server_Service_Table_Example_Walkthrough.md)

**Comment by xiewenxiang** [comment]
The `ESP_APP_ID ` is application ID. It is used to distinguish between application layer callbacks. We will fill in more details in doc later.

**Comment by zhp0406** [comment]
see:
a5a7e60ad0bd0b00839310b6d28a87ae80fd0e94
