### ISSUE TITLE
How to define   image_size, base_dir, output_file for spiffsgen.main() (IDFGH-6174)

### ISSUE THREAD

**Issue by dustralia** [espressif/esp-idf#7851]
How to define   image_size, base_dir, output_file for spiffsgen.main()

spiffsgen.main('0x170000', 'data', 'data.bin') ---- TypeError: main() takes 0 positional arguments but 3 were given

spiffsgen.main() ---- error: the following arguments are required: image_size, base_dir, output_file

**Comment by igrr** [comment]
Hi @dustralia, I'm sorry that it took a long time to reply. `main` function of spiffsgen.py uses `argparse` module to parse the arguments supplied on the command line. The arguments are taken from `sys.argv` array (implicitly, in the call to parser.parse_args()): https://github.com/espressif/esp-idf/blob/ef98a363e35dbc6bfd1caadfab8706874930f278/components/spiffs/spiffsgen.py#L511-L578.

You can do something like this to call spiffsgen.py main function from another script:

```
import sys
import spiffsgen

sys_argv_saved = sys.argv
spiffsgen_args = ['spiffsgen.py', '0x170000', 'data', 'data.bin']
try:
    sys.argv = spiffsgen_args
    spiffsgen.main()
finally:
    sys.argv = sys_argv_saved
```

the first argument in argv array (argv[0]) is the program name (as passed to the program itself), subsequent arguments are parsed by the program.

**Comment by dustralia** [comment]
OK，thank you&nbsp;



---Original---
From: "Ivan ***@***.***&gt;
Date: Mon, Nov 29, 2021 05:12 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [espressif/esp-idf] How to define   image_size, base_dir,output_file for spiffsgen.main() (IDFGH-6174) (Issue #7851)




 
Hi @dustralia, I'm sorry that it took a long time to reply. main function of spiffsgen.py uses argparse module to parse the arguments supplied on the command line. The arguments are taken from sys.argv array (implicitly, in the call to parser.parse_args()): https://github.com/espressif/esp-idf/blob/ef98a363e35dbc6bfd1caadfab8706874930f278/components/spiffs/spiffsgen.py#L511-L578.
 
You can do something like this to call spiffsgen.py main function from another script:
 import sys import spiffsgen sys_argv_saved = sys.argv spiffsgen_args = ['spiffsgen.py', '0x170000', 'data', 'data.bin'] try:     sys.argv = spiffsgen_args     spiffsgen.main() finally:     sys.argv = sys_argv_saved  
the first argument in argv array (argv[0]) is the program name (as passed to the program itself), subsequent arguments are parsed by the program.
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
