### ISSUE TITLE
Firmware image being automatically set to valid after OTA update, rollback not being possible. (IDFGH-6182)

### ISSUE THREAD

**Issue by GKFernandes** [espressif/esp-idf#7859]
## Environment

- Development Kit:|ESP32-DevKitC|
- Kit version DevKitC):v2
- Module or chip used: ESP32-WROOM-32E
- IDF version: 4.2.1
- Build System: CMake through platformio
- Compiler version:  toolchain-xtensa32 2.80400.210211 (8.4.0)
- Operating System: Windows
- (Windows only) environment type: Git Bash/PlatformIO Terminal
- Using an IDE?: Yes, using VSCode
- Power Supply: USB 5V

## Problem Description

Hi everyone,

So, after reading some documentation over here (Over The Air Updates (https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/ota.html) I was able to perform the OTA update using the advanced_https_ota example code.

At the rollback process part (https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/ota.html#rollback-process) it is mentioned that when you perform OTA, the first boot with the new partition is monitored, therefore it receives the ESP_OTA_IMG_PENDING_VERIFY flag and in case of reboot before calling the esp_ota_mark_app_valid_cancel_rollback() function the application would rollback to the previous working version.

Unfortunately, that is not what is happening, instead, after the OTA update, both images are shown as valid, so the rollback never occurs.

Did somebody encounter the same problem?

Thanks!

### Actual Behavior

/* Advanced HTTPS OTA example

   This example code is in the Public Domain (or CC0 licensed, at your option.)

   Unless required by applicable law or agreed to in writing, this
   software is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
   CONDITIONS OF ANY KIND, either express or implied.
*/
#include <string.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "freertos/event_groups.h"
#include "esp_system.h"
#include "esp_event.h"
#include "esp_log.h"
#include "esp_ota_ops.h"
#include "esp_http_client.h"
#include "esp_https_ota.h"
#include "nvs.h"
#include "nvs_flash.h"
#include "protocol_examples_common.h"

#if CONFIG_EXAMPLE_CONNECT_WIFI
#include "esp_wifi.h"
#endif

static const char *TAG = "advanced_https_ota_example";
extern const uint8_t server_cert_pem_start[] asm("_binary_ca_cert_pem_start");
extern const uint8_t server_cert_pem_end[] asm("_binary_ca_cert_pem_end");

#define OTA_URL_SIZE 256

static esp_err_t validate_image_header(esp_app_desc_t *new_app_info)
{
    if (new_app_info == NULL) 
    {
        return ESP_ERR_INVALID_ARG;
    }

    const esp_partition_t *running = esp_ota_get_running_partition();
    esp_app_desc_t running_app_info;
    if (esp_ota_get_partition_description(running, &running_app_info) == ESP_OK) 
    {
        ESP_LOGI(TAG, "Running firmware version: %s", running_app_info.version);
    }

#ifndef CONFIG_EXAMPLE_SKIP_VERSION_CHECK
    if (memcmp(new_app_info->version, running_app_info.version, sizeof(new_app_info->version)) == 0) 
    {
        ESP_LOGW(TAG, "Current running version is the same as a new. We will not continue the update.");
        return ESP_FAIL;
    }
#endif

    return ESP_OK;
}

void advanced_ota_example_task(void *pvParameter)
{
    ESP_LOGI(TAG, "Starting Advanced OTA example");

    esp_err_t ota_finish_err = ESP_OK;
    esp_http_client_config_t config = 
    {
        .url = CONFIG_EXAMPLE_FIRMWARE_UPGRADE_URL,
        .cert_pem = (char *)server_cert_pem_start,
        .timeout_ms = CONFIG_EXAMPLE_OTA_RECV_TIMEOUT,
        .keep_alive_enable = true,
    };

#ifdef CONFIG_EXAMPLE_SKIP_COMMON_NAME_CHECK
    config.skip_cert_common_name_check = true;
#endif

    esp_https_ota_config_t ota_config = 
    {
        .http_config = &config,
    };

    esp_https_ota_handle_t https_ota_handle = NULL;
    esp_err_t err = esp_https_ota_begin(&ota_config, &https_ota_handle);
    if (err != ESP_OK) 
    {
        ESP_LOGE(TAG, "ESP HTTPS OTA Begin failed");
        vTaskDelete(NULL);
    }

    esp_app_desc_t app_desc;
    err = esp_https_ota_get_img_desc(https_ota_handle, &app_desc);
    if (err != ESP_OK) 
    {
        ESP_LOGE(TAG, "esp_https_ota_read_img_desc failed");
        goto ota_end;
    }
    err = validate_image_header(&app_desc);
    if (err != ESP_OK) 
    {
        ESP_LOGE(TAG, "image header verification failed");
        goto ota_end;
    }

    while (1) 
    {
        err = esp_https_ota_perform(https_ota_handle);
        if (err != ESP_ERR_HTTPS_OTA_IN_PROGRESS) 
        {
            break;
        }
        // esp_https_ota_perform returns after every read operation which gives user the ability to
        // monitor the status of OTA upgrade by calling esp_https_ota_get_image_len_read, which gives length of image
        // data read so far.
        ESP_LOGD(TAG, "Image bytes read: %d", esp_https_ota_get_image_len_read(https_ota_handle));
    }

    if (esp_https_ota_is_complete_data_received(https_ota_handle) != true) 
    {
        // the OTA image was not completely received and user can customise the response to this situation.
        ESP_LOGE(TAG, "Complete data was not received.");
    }

ota_end:
    ota_finish_err = esp_https_ota_finish(https_ota_handle);
    if ((err == ESP_OK) && (ota_finish_err == ESP_OK)) 
    {
        ESP_LOGI(TAG, "ESP_HTTPS_OTA upgrade successful. Rebooting ...");
        vTaskDelay(1000 / portTICK_PERIOD_MS);
        esp_restart();
    } 
    else 
    {
        if (ota_finish_err == ESP_ERR_OTA_VALIDATE_FAILED) 
        {
            ESP_LOGE(TAG, "Image validation failed, image is corrupted");
        }
        ESP_LOGE(TAG, "ESP_HTTPS_OTA upgrade failed %d", ota_finish_err);
        vTaskDelete(NULL);
    }
}

void app_main(void)
{
    // Initialize NVS.
    esp_err_t err = nvs_flash_init();
    if (err == ESP_ERR_NVS_NO_FREE_PAGES || err == ESP_ERR_NVS_NEW_VERSION_FOUND) {
        // 1.OTA app partition table has a smaller NVS partition size than the non-OTA
        // partition table. This size mismatch may cause NVS initialization to fail.
        // 2.NVS partition contains data in new format and cannot be recognized by this version of code.
        // If this happens, we erase NVS partition and initialize NVS again.
        ESP_ERROR_CHECK(nvs_flash_erase());
        err = nvs_flash_init();
    }
    ESP_ERROR_CHECK( err );

    ESP_ERROR_CHECK(esp_netif_init());
    ESP_ERROR_CHECK(esp_event_loop_create_default());

    /* This helper function configures Wi-Fi or Ethernet, as selected in menuconfig.
     * Read "Establishing Wi-Fi or Ethernet Connection" section in
     * examples/protocols/README.md for more information about this function.
    */
    ESP_ERROR_CHECK(example_connect());

#if CONFIG_EXAMPLE_CONNECT_WIFI
    /* Ensure to disable any WiFi power save mode, this allows best throughput
     * and hence timings for overall OTA operation.
     */
    esp_wifi_set_ps(WIFI_PS_NONE);
#endif // CONFIG_EXAMPLE_CONNECT_WIFI

    xTaskCreate(&advanced_ota_example_task, "advanced_ota_example_task", 1024 * 8, NULL, 5, NULL);
}

// If your code is longer than 30 lines, [GIST](https://gist.github.com) is preferred.

## Debug Logs
The debug log is very long, but OTA itself is working normally, I'll place it below as well:

I (41723) OTA: Iniciando OTA
I (41723) esp_https_ota: IMAGE HEADER SIZE 289
D (41733) HTTP_CLIENT: Begin connect to: https://mybucket.s3.amazonaws.com:443
D (41733) esp-tls: host:mybucket.s3.amazonaws.com: strlen 31
D (41763) esp-tls: Enable TCP keep alive. idle: 5, interval: 5, count: 3
D (42143) esp-tls: handshake in progress...
D (44593) HTTP_CLIENT: Write header[3]: GET /firmware_1_0_07.bin HTTP/1.1
User-Agent: ESP32 HTTP Client/1.0
Host: gkzinotabucket.s3.amazonaws.com
Content-Length: 0

D (44903) HTTP_CLIENT: on_message_begin
D (44903) HTTP_CLIENT: HEADER=x-amz-id-2:7cbAkdG4tXwFwYl3swElOzkomudJ+OLBXNh9gKFZxRknyf/5a0g3cTsE9KptN0g1ZZ6RkYydnis=
D (44913) HTTP_CLIENT: HEADER=x-amz-request-id:VFRQ483KZHZG2CDG
D (44913) HTTP_CLIENT: HEADER=Date:Thu, 04 Nov 2021 20:07:53 GMT
D (44923) HTTP_CLIENT: HEADER=Last-Modified:Tue, 31 Aug 2021 15:16:23 GMT
D (44933) HTTP_CLIENT: HEADER=ETag:"d7e2d1e286862db7251234ffe548147d"
D (44933) HTTP_CLIENT: HEADER=x-amz-version-id:okvWFIuhTSn4ZJiFLypGIlPqXP2iSTlP
D (44943) HTTP_CLIENT: HEADER=Accept-Ranges:bytes
D (44943) HTTP_CLIENT: HEADER=Content-Type:application/octet-stream
D (44953) HTTP_CLIENT: HEADER=Server:AmazonS3
D (44963) HTTP_CLIENT: HEADER=Content-Length:1270288
D (44963) HTTP_CLIENT: http_on_headers_complete, status=200, offset=427, nread=427
D (44973) HTTP_CLIENT: content_length = 1270288
I (44973) esp_https_ota: Starting OTA...
I (44983) esp_https_ota: Writing to partition subtype 17 at offset 0x160000
D (44983) HTTP_CLIENT: Data processed 0 != Data specified in content length 1270288
D (44993) HTTP_CLIENT: is_data_remain=1, is_chunked=0, content_length=1270288
D (45003) HTTP_CLIENT: need_read=289, byte_to_read=289, rlen=85, ridx=0
D (45013) HTTP_CLIENT: http_on_body 85
D (45013) HTTP_CLIENT: is_data_remain=1, is_chunked=0, content_length=1270288
Current time: Thursday, 04-Nov-2021 21:07:52 UTC

[sdkconfig.txt](https://github.com/espressif/esp-idf/files/7504793/sdkconfig.txt)

**Comment by KaeLL** [comment]
> when CONFIG_BOOTLOADER_APP_ROLLBACK_ENABLE option is enabled

**Comment by GKFernandes** [comment]
@KaeLL Thanks for reminding me to upload my sdkconfig file, I've attached it in the bottom part of the issue.

**Comment by laukik-hase** [comment]
Hello, @GKFernandes 

I tried reproducing this issue on tag `v4.2.1` but was unable to do it. The `advanced_https_ota` example (with your configurations) ran just fine.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, sorry that we could not reproduce the issue locally, you could also raise a post on our forum https://esp32.com, feel free to reopen, thanks.
