### ISSUE TITLE
[TW#13917] Wrong return code type for esp_ble_gattc_register_for_notify()

### ISSUE THREAD

**Issue by nkolban** [espressif/esp-idf#786]
The API for the function called esp_ble_gattc_register_for_notify() and also for esp_ble_gattc_unregister_for_notify() is declared as returning an esp_gatt_status_t.  However, what I believe it actually returns (and should return) is an esp_err_t.

**Comment by Weijian-Espressif** [comment]
thanks for your reminder , we will correct in version 3.0 .

**Comment by FayeY** [comment]
Hi @nkolban , this issue has already fixed in the latest IDF. Thanks for your reporting!
