### ISSUE TITLE
Rollback with Arduino as ESP-IDF Component (IDFGH-6193)

### ISSUE THREAD

**Issue by GKFernandes** [espressif/esp-idf#7871]
Hello everyone,

I ran into the same issue as stated in: https://github.com/espressif/arduino-esp32/issues/3318 and also in https://github.com/espressif/arduino-esp32/issues/3749

I think this issue about the weakly defined verify0ta() should be fixed and made in such a way that the user can perform the verification later in the code instead of inside the initArduino() function.

**Comment by atanisoft** [comment]
This should be moved to https://github.com/espressif/arduino-esp32 since `verifyOta` and `initArduino` are implemented over there.

**Comment by GKFernandes** [comment]
Thank you @atanisoft , I've moved the issue over there.

**Comment by Alvin1Zhang** [comment]
@GKFernandes Thanks for reporting, see the issue is tracked in https://github.com/espressif/arduino-esp32/issues/5871, so will close this one, thanks.
