### ISSUE TITLE
esp_ble_tx_power_set实测rssi没有变化 (IDFGH-6204)

### ISSUE THREAD

**Issue by fzboffice** [espressif/esp-idf#7879]
分别以
esp_ble_tx_power_set(ESP_BLE_PWR_TYPE_DEFAULT, ESP_PWR_LVL_N27)
esp_ble_tx_power_set(ESP_BLE_PWR_TYPE_DEFAULT, ESP_PWR_LVL_P18)
启动广播
同样距离的情况下，测得rssi大致相同
请问这个是在很远的地方才体现吗

**Comment by xiewenxiang** [comment]
使用的是ESP32 还是 C3 还是 S3？ type 可以设置为 ADV，不要设置为 default。

**Comment by zhp0406** [comment]
请问你的问题解决了吗?

**Comment by fzboffice** [comment]
@zhp0406 已解决

**Comment by Alvin1Zhang** [comment]
Thanks for sharing the updates, feel free to reopen.
