### ISSUE TITLE
Is it possible to make ESP32 emulate an SD card?

### ISSUE THREAD

**Issue by leopck** [espressif/esp-idf#788]
I'm not well-verse in SD protocols but this is just a question I was wondering if it's possible.

Since ESP32 has SDIO capabilities, is it possible to make it not only read SD cards but to emulate an SD card? It has variety of use cases such as SD card over WiFi or OTA over WiFi SD card.

**Comment by igrr** [comment]
Unfortunately, SDIO slave peripheral in the ESP32 does not support many of the commands required for SD memory cards.

In SDIO specification, IO_RW_EXTENDED command is used for data transfer. SD memory cards operate using different data transfer commands (READ_BLOCK_SINGLE, READ_BLOCK_MULTIPLE, WRITE_BLOCK_SINGLE, WRITE_BLOCK_MULTIPLE), plus there are a few other auxiliary commands which SD memory cards need to support.

**Comment by danielkucera** [comment]
@igrr but aren't this commands implemented in software?

**Comment by igrr** [comment]
SDIO slave interface of the ESP32 handles all commands in hardware. Software only gets an interrupts when the host sends data transfer commands. Probing/initialization commands do not reach the software.

**Comment by fk1000iq** [comment]
那用ESP32来实现模拟SD卡，从硬件直接支持是不行的喽？
