### ISSUE TITLE
Launch binary not found in Eclipse (IDFGH-65)

### ISSUE THREAD

**Issue by Nakul93** [espressif/esp-idf#789]
Getting a Launch binary not found error while trying to run the project in eclipse.
How to add the binaries?

**Comment by Alvin1Zhang** [comment]
@Nakul93 Hi, could you help update if the issue you reported still exists? Thanks.

**Comment by Alvin1Zhang** [comment]
@Nakul93  Thanks for reporting, feel free to reopen if more details could be provided, thanks.
