### ISSUE TITLE
Setting Bluetooth Manufacturer ID (IDFGH-6218)

### ISSUE THREAD

**Issue by johndoesenior** [espressif/esp-idf#7891]
Hi all! 

I am trying to track where HCI Manufacturer ID is set, I suspect it is CHIP level, 
Any way of changing it? this is for testing purposes, 

(Found only one reference in the code for struct bt_version_t)

Thanks
John

**Comment by Wth-Esp** [comment]
hi @johndoesenior 
What do you mean by `HCI MAnufacturer ID`? Does it has some other name in the spec of some other BT related documentations? Is that this (red box in the picture)?
![image](https://user-images.githubusercontent.com/64878943/141719031-50b9cd8e-ef42-41e8-ac25-743b31083c27.png)

**Comment by Alvin1Zhang** [comment]
@johndoesenior Thanks for reporting, would you please help share if any updates for the issue? Thanks.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to short of feedback, feel free to reopen with more updates.
