### ISSUE TITLE
Project does not compile after installing esp-idf v4.4-dev-3657-gdf0929009a (IDFGH-6221)

### ISSUE THREAD

**Issue by baldhead69** [espressif/esp-idf#7894]
Hi,

I installed esp-idf version v4.4-dev-3657-gdf0929009a following this link:
https://docs.espressif.com/projects/esp-idf/en/release-v4.4/esp32/get-started/windows-setup.html

When i compile the esp-idf project this error appear:
Cannot parse CMake requirements line: __component_set_property(__idf.global_conf REQUIRES "lvgl;cxx;newlib;freertos;esp_hw_support;heap;log;lwip;soc;hal;esp_rom;esp_common;esp_system;esp32")

i tried to follow this:
https://github.com/espressif/vscode-esp-idf-extension/issues/388

but when i put "ESP-IDF: Open ESP-IDF Terminal" in cmd or esp-idf cmd

'ESP-IDF:' is not recognized as an internal command
or external, an operable program or a batch file.

How to solve this problem ???

Thank's

**Comment by baldhead69** [comment]
I tried this, but not solved the problem.

![Sem título](https://user-images.githubusercontent.com/17574492/141667949-92949df2-c76d-4f1a-8db2-477a24a4faa3.png)

**Comment by baldhead69** [comment]
Some suggestion on how to solve this ?

Thank's.

**Comment by baldhead69** [comment]
@brianignacio5 and @0xjakob and @igrr

**Comment by baldhead69** [comment]
I am trying in 2 computers this installation and same problem on 2 computers.
I am stuck in this problem.
Whenever i go to install a new idf is this annoyance.
Ever.
For this reason i go months without updating esp idf (6 months or more).

Espressif should choose a single ide and focus all efforts on it.

**Comment by brianignacio5** [comment]
@baldhead69 The command `ESP-IDF: Open ESP-IDF Terminal` is for the esp-idf extension in vscode. In terminal this doesn't work because it is not part of it.

If you are using the terminal itself, after updating `idd-component-manager`, delete your project's build folder and try again. Check if there is an environment variable `IDF_COMPONENT_MANAGER` enabled in your terminal. Delete it, delete the build folder and try to build again.

**Comment by baldhead69** [comment]
@brianignacio5 

How to update idd-component-manager ?

I understand very little about the esp-idf build tools.

**Comment by baldhead69** [comment]
@brianignacio5 

Did you mean idf-component-manager ?

If so, i already have installed.

[code]
IDF_TOOLS_PATH not set. Setting to C:\.espressif\
Setting PYTHONNOUSERSITE, was not set
Using Python in C:\.espressif\python_env\idf4.4_py3.8_env\Scripts\
Python 3.8.7
Using Git in C:\.espressif\tools\idf-git\2.30.1\cmd\
git version 2.30.1.windows.1
Setting IDF_PATH: C:\esp-idf

Adding ESP-IDF tools to PATH...
    C:\.espressif\tools\xtensa-esp32-elf\esp-2021r2-8.4.0\xtensa-esp32-elf\bin
    C:\.espressif\tools\xtensa-esp32s3-elf\esp-2021r2-8.4.0\xtensa-esp32s3-elf\bin
    C:\.espressif\tools\riscv32-esp-elf\esp-2021r2-8.4.0\riscv32-esp-elf\bin
    C:\.espressif\tools\esp32ulp-elf\2.28.51-esp-20191205\esp32ulp-elf-binutils\bin
    C:\.espressif\tools\esp32s2ulp-elf\2.28.51-esp-20191205\esp32s2ulp-elf-binutils\bin
    C:\.espressif\tools\cmake\3.20.3\bin
    C:\.espressif\tools\openocd-esp32\v0.10.0-esp32-20210902\openocd-esp32\bin
    C:\.espressif\tools\ninja\1.10.2\
    C:\.espressif\tools\idf-exe\1.0.2\
    C:\.espressif\tools\ccache\4.3\ccache-4.3-windows-64
    C:\.espressif\tools\dfu-util\0.9\dfu-util-0.9-win64
    C:\esp-idf\tools

Checking if Python packages are up to date...
Python requirements from C:\esp-idf\requirements.txt are satisfied.

Done! You can now compile ESP-IDF projects.
Go to the project directory and run:

  idf.py build


C:\esp-idf>pip

Usage:
  pip <command> [options]

Commands:
  install                     Install packages.
  download                    Download packages.
  uninstall                   Uninstall packages.
  freeze                      Output installed packages in requirements format.
  list                        List installed packages.
  show                        Show information about installed packages.
  check                       Verify installed packages have compatible dependencies.
  config                      Manage local and global configuration.
  search                      Search PyPI for packages.
  cache                       Inspect and manage pip's wheel cache.
  index                       Inspect information available from package indexes.
  wheel                       Build wheels from your requirements.
  hash                        Compute hashes of package archives.
  completion                  A helper command used for command completion.
  debug                       Show information useful for debugging.
  help                        Show help for commands.

General Options:
  -h, --help                  Show help.
  --debug                     Let unhandled exceptions propagate outside the main subroutine, instead of logging them
                              to stderr.
  --isolated                  Run pip in an isolated mode, ignoring environment variables and user configuration.
  -v, --verbose               Give more output. Option is additive, and can be used up to 3 times.
  -V, --version               Show version and exit.
  -q, --quiet                 Give less output. Option is additive, and can be used up to 3 times (corresponding to
                              WARNING, ERROR, and CRITICAL logging levels).
  --log <path>                Path to a verbose appending log.
  --no-input                  Disable prompting for input.
  --proxy <proxy>             Specify a proxy in the form [user:passwd@]proxy.server:port.
  --retries <retries>         Maximum number of retries each connection should attempt (default 5 times).
  --timeout <sec>             Set the socket timeout (default 15 seconds).
  --exists-action <action>    Default action when a path already exists: (s)witch, (i)gnore, (w)ipe, (b)ackup,
                              (a)bort.
  --trusted-host <hostname>   Mark this host or host:port pair as trusted, even though it does not have valid or any
                              HTTPS.
  --cert <path>               Path to PEM-encoded CA certificate bundle. If provided, overrides the default. See 'SSL
                              Certificate Verification' in pip documentation for more information.
  --client-cert <path>        Path to SSL client certificate, a single file containing the private key and the
                              certificate in PEM format.
  --cache-dir <dir>           Store the cache data in <dir>.
  --no-cache-dir              Disable the cache.
  --disable-pip-version-check
                              Don't periodically check PyPI to determine whether a new version of pip is available for
                              download. Implied with --no-index.
  --no-color                  Suppress colored output.
  --no-python-version-warning
                              Silence deprecation warnings for upcoming unsupported Pythons.
  --use-feature <feature>     Enable new functionality, that may be backward incompatible.
  --use-deprecated <feature>  Enable deprecated functionality, that will be removed in the future.

C:\esp-idf>pip install
ERROR: You must give at least one requirement to install (see "pip help install")

C:\esp-idf>pip install idf-component-manager
Requirement already satisfied: idf-component-manager in c:\.espressif\python_env\idf4.4_py3.8_env\lib\site-packages (0.3.2b0)
Requirement already satisfied: pyyaml in c:\.espressif\python_env\idf4.4_py3.8_env\lib\site-packages (from idf-component-manager) (6.0)
Requirement already satisfied: schema in c:\.espressif\python_env\idf4.4_py3.8_env\lib\site-packages (from idf-component-manager) (0.7.4)
Requirement already satisfied: tqdm in c:\.espressif\python_env\idf4.4_py3.8_env\lib\site-packages (from idf-component-manager) (4.62.3)
Requirement already satisfied: requests-toolbelt in c:\.espressif\python_env\idf4.4_py3.8_env\lib\site-packages (from idf-component-manager) (0.9.1)
Requirement already satisfied: six in c:\.espressif\python_env\idf4.4_py3.8_env\lib\site-packages (from idf-component-manager) (1.16.0)
Requirement already satisfied: requests in c:\.espressif\python_env\idf4.4_py3.8_env\lib\site-packages (from idf-component-manager) (2.26.0)
Requirement already satisfied: future in c:\.espressif\python_env\idf4.4_py3.8_env\lib\site-packages (from idf-component-manager) (0.18.2)
Requirement already satisfied: semantic-version>="2.8" in c:\.espressif\python_env\idf4.4_py3.8_env\lib\site-packages (from idf-component-manager) (2.8.5)
Requirement already satisfied: certifi>=2017.4.17 in c:\.espressif\python_env\idf4.4_py3.8_env\lib\site-packages (from requests->idf-component-manager) (2021.10.8)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\.espressif\python_env\idf4.4_py3.8_env\lib\site-packages (from requests->idf-component-manager) (2.0.7)
Requirement already satisfied: idna<4,>=2.5 in c:\.espressif\python_env\idf4.4_py3.8_env\lib\site-packages (from requests->idf-component-manager) (3.3)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\.espressif\python_env\idf4.4_py3.8_env\lib\site-packages (from requests->idf-component-manager) (1.26.7)
Requirement already satisfied: contextlib2>=0.5.5 in c:\.espressif\python_env\idf4.4_py3.8_env\lib\site-packages (from schema->idf-component-manager) (21.6.0)
Requirement already satisfied: colorama in c:\.espressif\python_env\idf4.4_py3.8_env\lib\site-packages (from tqdm->idf-component-manager) (0.4.4)

C:\esp-idf>%IDF_COMPONENT_MANAGER%
'%IDF_COMPONENT_MANAGER%' não é reconhecido como um comando interno
ou externo, um programa operável ou um arquivo em lotes.

C:\esp-idf>set | more
ALLUSERSPROFILE=C:\ProgramData
APPDATA=C:\Users\Rangel\AppData\Roaming
CommonProgramFiles=C:\Program Files\Common Files
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
CommonProgramW6432=C:\Program Files\Common Files
COMPUTERNAME=BALDHEAD
ComSpec=C:\WINDOWS\system32\cmd.exe
DriverData=C:\Windows\System32\Drivers\DriverData
FPS_BROWSER_APP_PROFILE_STRING=Internet Explorer
FPS_BROWSER_USER_PROFILE_STRING=Default
HOMEDRIVE=C:
HOMEPATH=\Users\Rangel
IDF_CCACHE_ENABLE=1
IDF_GIT=C:/.espressif/tools/idf-git/2.30.1/cmd/git.exe
IDF_GIT_DIR=C:\.espressif\tools\idf-git\2.30.1\cmd\
IDF_PATH=C:\esp-idf
IDF_PYTHON=C:/.espressif/python_env/idf4.4_py3.8_env/Scripts/python.exe
IDF_PYTHON_DIR=C:\.espressif\python_env\idf4.4_py3.8_env\Scripts\
IDF_PYTHON_ENV_PATH=C:\.espressif\python_env\idf4.4_py3.8_env
IDF_TOOLS_PATH=C:\.espressif\
JAVA_HOME=C:\Program Files\Android\Android Studio\jre
LOCALAPPDATA=C:\Users\Rangel\AppData\Local
LOGONSERVER=\\BALDHEAD
MOZ_PLUGIN_PATH=C:\Program Files (x86)\Foxit Software\Foxit Reader\plugins\
NUMBER_OF_PROCESSORS=12
OneDrive=D:\OneDrive - UDESC Universidade do Estado de Santa Catarina
OneDriveCommercial=D:\OneDrive - UDESC Universidade do Estado de Santa Catarina
OPENOCD_SCRIPTS=C:\.espressif\tools\openocd-esp32\v0.10.0-esp32-20210902\openocd-esp32\share\openocd\scripts
OS=Windows_NT
PARAM=esp-idf-603734d526b91e4aff20573199812fef
Path=C:\.espressif\tools\xtensa-esp32-elf\esp-2021r2-8.4.0\xtensa-esp32-elf\bin;C:\.espressif\tools\xtensa-esp32s3-elf\esp-2021r2-8.4.0\xtensa-esp32s3-elf\bin;C:\.espressif\tools\riscv32-esp-elf\esp-2021r2-8.4.0\riscv32-esp-elf\bin;C:\.espressif\tools\esp32ulp-elf\2.28.51-esp-20191205\esp32ulp-elf-binutils\bin;C:\.espressif\tools\esp32s2ulp-elf\2.28.51-esp-20191205\esp32s2ulp-elf-binutils\bin;C:\.espressif\tools\cmake\3.20.3\bin;C:\.espressif\tools\openocd-esp32\v0.10.0-esp32-20210902\openocd-esp32\bin;C:\.espressif\tools\ninja\1.10.2\;C:\.espressif\tools\idf-exe\1.0.2\;C:\.espressif\tools\ccache\4.3\ccache-4.3-windows-64;C:\.espressif\tools\dfu-util\0.9\dfu-util-0.9-win64;C:\esp-idf\tools;C:\.espressif\python_env\idf4.4_py3.8_env\Scripts\;C:\.espressif\tools\idf-git\2.30.1\cmd\;C:\.espressif\;C:\Program Files\Microsoft Network Monitor 3\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\WINDOWS\System32\OpenSSH\;C:\Windows\System32\OpenSSH\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\PuTTY\;C:\Program Files\nodejs\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\system32;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS;C:\Users\Rangel\AppData\Local\Microsoft\WindowsApps;C:\Users\Rangel\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\Rangel\AppData\Roaming\npm;C:\Users\Rangel\.dotnet\tools;
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
PREFIX=C:/.espressif/python_env/idf4.4_py3.8_env/Scripts/python.exe C:/esp-idf/
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=9e0a
PROG27B48B2C054=1
ProgramData=C:\ProgramData
ProgramFiles=C:\Program Files
ProgramFiles(x86)=C:\Program Files (x86)
ProgramW6432=C:\Program Files
PROMPT=$P$G
PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
PUBLIC=C:\Users\Public
PYTHONNOUSERSITE=True
SESSIONNAME=Console
SystemDrive=C:
SystemRoot=C:\WINDOWS
TEMP=C:\Users\Rangel\AppData\Local\Temp
TEMP_IDF_GIT_PATH="C:\Users\Rangel\AppData\Local\Temp\idf-git-path.txt"
TEMP_IDF_PATH=C:\Users\Rangel\AppData\Local\Temp\idf-path.txt
TEMP_IDF_PYTHON_PATH="C:\Users\Rangel\AppData\Local\Temp\idf-python-path.txt"
TMP=C:\Users\Rangel\AppData\Local\Temp
USERDOMAIN=BALDHEAD
USERDOMAIN_ROAMINGPROFILE=BALDHEAD
USERNAME=Rangel
USERPROFILE=C:\Users\Rangel
windir=C:\WINDOWS
ZES_ENABLE_SYSMAN=1


C:\esp-idf>cd c:\esp32Projects\wss_server_and_ui_integration

c:\esp32Projects\WSS_SERVER_AND_UI_INTEGRATION>idf.py build
Executing action: all (aliases: build)
Running cmake in directory c:\esp32projects\wss_server_and_ui_integration\build
Executing "cmake -G Ninja -DPYTHON_DEPS_CHECKED=1 -DESP_PLATFORM=1 -DIDF_TARGET=esp32 -DCCACHE_ENABLE=1 c:\esp32projects\wss_server_and_ui_integration"...
-- Found Git: C:/.espressif/tools/idf-git/2.30.1/cmd/git.exe (found version "2.30.1.windows.1")
-- Component directory C:/esp32Projects/WSS_SERVER_AND_UI_INTEGRATION/components/communication does not contain a CMakeLists.txt file. No component will be added
-- Component directory C:/esp32Projects/WSS_SERVER_AND_UI_INTEGRATION/components/ui does not contain a CMakeLists.txt file. No component will be added
-- ccache will be used for faster recompilation
-- The C compiler identification is GNU 8.4.0
-- The CXX compiler identification is GNU 8.4.0
-- The ASM compiler identification is GNU
-- Found assembler: C:/.espressif/tools/xtensa-esp32-elf/esp-2021r2-8.4.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc.exe
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/.espressif/tools/xtensa-esp32-elf/esp-2021r2-8.4.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/.espressif/tools/xtensa-esp32-elf/esp-2021r2-8.4.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-g++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Project is not inside a git repository, or git repository has no commits; will not use 'git describe' to determine PROJECT_VER.
-- Building ESP-IDF components for target esp32
Cannot parse CMake requirements line: __component_set_property(___idf_.global_conf REQUIRES "lvgl;cxx;newlib;freertos;esp_hw_support;heap;log;lwip;soc;hal;esp_rom;esp_common;esp_system;esp32")

CMake Error at C:/esp-idf/tools/cmake/component.cmake:238 (message):
Call Stack (most recent call first):
  C:/esp-idf/tools/cmake/build.cmake:491 (__component_get_requirements)
  C:/esp-idf/tools/cmake/project.cmake:378 (idf_build_process)
  CMakeLists.txt:15 (project)


-- Configuring incomplete, errors occurred!
See also "C:/esp32Projects/WSS_SERVER_AND_UI_INTEGRATION/build/CMakeFiles/CMakeOutput.log".
cmake failed with exit code 1

c:\esp32Projects\WSS_SERVER_AND_UI_INTEGRATION>
[/code]

**Comment by baldhead69** [comment]
![esp-idf_4 4_cmd](https://user-images.githubusercontent.com/17574492/141727969-609cd4d9-c945-4123-a1ae-529354dc9c95.png)
![Sem título](https://user-images.githubusercontent.com/17574492/141727979-67c81053-214a-4b81-8944-fa240bf2a09d.png)

**Comment by baldhead69** [comment]
> If you are using the terminal itself, after updating idd-component-manager, delete your project's build folder and try again. Check if there is an environment variable IDF_COMPONENT_MANAGER enabled in your terminal. Delete it, delete the build folder and try to build again.

This not solve.

**Comment by 0xjakob** [comment]
@baldhead69 Have you tried to delete the build folder as @brianignacio5 suggested [above](https://github.com/espressif/esp-idf/issues/7894#issuecomment-968516243)?

**Comment by baldhead69** [comment]
> @baldhead69 Have you tried to delete the build folder as @brianignacio5 suggested [above](https://github.com/espressif/esp-idf/issues/7894#issuecomment-968516243)?
> 

Yes.
In all attempts.

**Comment by igrr** [comment]
@baldhead69 do you happen to have a component directory named `.global_conf` inside your project? If yes, what is the contents of that directory? It looks like idf-component-manager considers it to be a component and fails because of the `.` symbol in the directory name.

**Comment by baldhead69** [comment]
in esp-idf version "v4.4-dev-2359-g58022f859" the program compiled ok.
And anothers versions compiled ok too.

**Comment by igrr** [comment]
I understand that, it's entirely possible that the same project worked before. — the error is related to the component manager, which is a new feature recently enabled in the master branch. I'm asking about that directory to try to identify the root cause of the issue. Once we know the cause, we can fix it.or give you a workaround so that you can move on with your project.

**Comment by baldhead69** [comment]
The ".global_conf" is only a folder that i put lvgl component configurations like lv_conf.h, lv_conf_checker.h, lv_version.h and lvgl.h and a CMakeLists.txt file.

CMakeLists.txt file:
idf_component_register( INCLUDE_DIRS .							
						REQUIRES lvgl						
					  )

**Comment by baldhead69** [comment]
@igrr 

I took the dot from the folder and the respective CMakeLists.txt files that referenced this folder and worked.

Will espressif guys try to fix this ?

Thank you very much.


Example:
CMakeLists.txt
```
file(GLOB littlevgl_srcs 	src/lv_core/*.c 
							src/lv_draw/*.c 
							src/lv_font/*.c 
							src/lv_hal/*.c 
							src/lv_misc/*.c
							src/lv_objx/*.c
							src/lv_themes/*.c
	)


idf_component_register(	SRCS ${littlevgl_srcs}
						INCLUDE_DIRS 	src/lv_core/include
										src/lv_draw/include
										src/lv_font/include
										src/lv_hal/include
										src/lv_misc/include
										src/lv_objx/include
										src/lv_themes/include
														
						REQUIRES global_conf				
						#REQUIRES fatfs sdmmc						
					  )
```

**Comment by baldhead69** [comment]
Taking the opportunity to talk to you, what is the difference between these two files ?
I noticed that both esp32 and esp32-s3 have these 2 files.

xtensa-esp32-elf-gcc.exe
xtensa-esp32-elf-gcc-8.4.0.exe

**Comment by baldhead69** [comment]
Hi,

Now i installed "ESP-IDF VS Code Extension" and all is working.

Nice work guys.

Thank's all.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting and sharing the updates, good to hear all is working now, feel free to reopen.

**Comment by baldhead69** [comment]
> Taking the opportunity to talk to you, what is the difference between these two files ?
> I noticed that both esp32 and esp32-s3 have these 2 files.
> 
> xtensa-esp32-elf-gcc.exe
> xtensa-esp32-elf-gcc-8.4.0.exe

I only would like to know this because i use this configuration for configure intellisense on visual studio code.

**Comment by baldhead69** [comment]
A strange thing happened.

I started a installation from scratch on another computer and the dot folder problem go away.

Did you guys update anything already ?

**Comment by kumekay** [comment]
> Did you guys update anything already?

No, support for `.` in component names is not published yet, 
but if the component manager is disabled, it shouldn't be a problem. Or, for example the issue won't appear if some CMake-based IDE is used, like Jetbrains CLion

**Comment by kumekay** [comment]
@baldhead69  Just a quick question, did you ever have your project compiled successfully with `.global_conf` component (started with the leading dot)? Components with leading dots in the name were always ignored in the IDF: https://github.com/espressif/esp-idf/blob/master/tools/cmake/component.cmake#L112

**Comment by baldhead69** [comment]
@kumekay 

yes, always compiled with esp32(i believe that the chip does not influence).

"Root" CMakeLists.txt
```c
# The following lines of boilerplate have to be in your project's CMakeLists
# in this exact order for cmake to work correctly
cmake_minimum_required(VERSION 3.5)

# (Not part of the boilerplate)
set(EXTRA_COMPONENT_DIRS "${CMAKE_SOURCE_DIR}/components/ui" "${CMAKE_SOURCE_DIR}/components/ui/global_conf" "${CMAKE_SOURCE_DIR}/components/communication")   # add components "drv" "lvgl" and ".global_conf". ".global_conf" only *.h global files. 
#  ${CMAKE_SOURCE_DIR} -> project root folder.						 

include($ENV{IDF_PATH}/tools/cmake/project.cmake)
project(wss_server)
```

The .global_conf folder was inside the ui folder

**Comment by kumekay** [comment]
Thank you for the quick reply, I thought you had `components/.global_conf` and wondered why it ever worked.

At the same time, the [CMake error](https://github.com/espressif/esp-idf/issues/7894#issuecomment-968546559) in the component manager you mentioned is fixed now and will be included in the next release of it.  But the support of components with leading dots like  `components/.global_conf` won't be enabled in IDF (at the same time  `components/ui/.global_conf` should be fine)
