### ISSUE TITLE
[TW#13913] gatts_demo.c compiling error  'ESP_GAP_BLE_UPDATE_CONN_PARAMS_EVT' was not declared in this scope

### ISSUE THREAD

**Issue by zgkgl** [espressif/esp-idf#790]

**Comment by Weijian-Espressif** [comment]
@zgkgl  ESP_GAP_BLE_UPDATE_CONN_PARAMS_EVT is defined in esp_gap_api.h , please update the lasted idf , and retry. please make clean then make all.

**Comment by FayeY** [comment]
Hi @zgkgl , did the above suggestion help you resolve the issue?
