### ISSUE TITLE
Where is v4.4? (IDFGH-6228)

### ISSUE THREAD

**Issue by olsonap** [espressif/esp-idf#7901]
I see lots of references to a v4.4 of the idf, but I don't see it on the release page. Arduino as a component requires v4.4 or greater for use, yet it's apparently not available.

**Comment by igrr** [comment]
Hi @olsonap, apologies for the confusion. Arduino-esp32 project is currently using *release/v4.4 branch* of ESP-IDF. v4.4 release hasn't been made yet. At this time we are working on fixing the issues found by QA in release/v4.4 branch and preparing v4.4-beta1 pre-release. That will be followed by -rc and eventually the final release.
We'll look into making Arduino-esp32 documentation more clear about this.

**Comment by olsonap** [comment]
That was an incredibly fast response at this hour. Thanks!
