### ISSUE TITLE
esp-WROOM-32D used smartconfig connected with 5G wifi6 AP failed，what should i do？ (IDFGH-6242)

### ISSUE THREAD

**Issue by qpmc1s** [espressif/esp-idf#7914]
I want esp-WROOM-32D to use smartconfig connected with 5G wifi6 AP， but it has not worked。
when I used esp-WROOM-32D  smartconfig connected with 2.4G wifi AP， it worked。 
what should I do？
does esp-WROOM-32D support 5G wifi6 AP？

**Comment by TianaESP** [comment]
Hi @qpmc1s 
does esp-WROOM-32D support 5G wifi6 AP？----> No.
https://www.espressif.com/en/products/modules

**Comment by qpmc1s** [comment]
Thank，@TianaESP

**Comment by sumer274** [comment]
> Hi   你好[@qpmc1s](https://github.com/qpmc1s) does esp-WROOM-32D support 5G wifi6 AP？----> No.esp-wroom-32D 支持 5G WIFI6 接入点吗?---->不支持。 https://www.espressif.com/en/products/modules

请问，目前ESP32-c5支持使用smartconfig连接到5G AP吗
