### ISSUE TITLE
Why sleep() and usleep() are int when it always return 0 ? (IDFGH-6253)

### ISSUE THREAD

**Issue by hassandraga** [espressif/esp-idf#7922]
Just a quick question, why `int usleep(useconds_t us)` and `unsigned int sleep(unsigned int seconds)` are integer, when return is always 0 ? probably we should change datatype to a void, I'm not sure.

https://github.com/espressif/esp-idf/blob/7af719e426952995b2a205e821e7471a0b995125/components/newlib/time.c#L206
https://github.com/espressif/esp-idf/blob/7af719e426952995b2a205e821e7471a0b995125/components/newlib/time.c#L220

**Comment by negativekelvin** [comment]
For compatibility with glibc, bsd, posix, etc...

**Comment by hassandraga** [comment]
I see, Thank you.
