### ISSUE TITLE
change log should be updated for new feature. (IDFGH-6255)

### ISSUE THREAD

**Issue by merlot-joshua-kwon** [espressif/esp-idf#7924]
# Changelog > Breaking Changes mentioned in v4.3.1 should also be included in v4.1.2 to avoid confusion among other developers.

Our project is being distributed as a commercial version from IDF-v3.3.2.
There was an issue when project upgraded from v3.3.2 to v4.1.2.
 - MD5 check error.
It was mentioned in v4.3.1 but not in v4.1.2, causing an issue with that content.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting and apologize for the very slow turnaround, the entry about MD5 check "Partition Table: The partition table MD5 checksum is now checked when the partition table is loaded by the app, in addition to the existing check in the bootloader" are mentioned in bothhttps://github.com/espressif/esp-idf/releases/tag/v4.1.2 and https://github.com/espressif/esp-idf/releases/tag/v4.3.1, and IDF v4.1 and IDF v4.3 are both End of Life. 

Feel free to reopen, thanks.
