### ISSUE TITLE
Flash integrity Check  (IDFGH-6269)

### ISSUE THREAD

**Issue by 99003662** [espressif/esp-idf#7938]
Hi team, 
              we are working on Flash integrity check on ESP32 controller. So basically we have to check whether the memory is corrupted or not. And if it is corrupted Erase the specific sector or if it's required erase the whole memory. Is there any support available for this purpose, Or any inputs on this task....... it will be helpful.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, you could raise a post on our forum https://esp32.com, feel free to reopen.
