### ISSUE TITLE
ESP32S2 with PSRAM "Integrate RAM into memory map" mbedtls SHA1 give incorrect results (IDFGH-6275)

### ISSUE THREAD

**Issue by mishafarms** [espressif/esp-idf#7944]
I am using Micropython with the esp32s2 chip with PSRAM enabled using Integrate RAM into memory map. 
SDK version 4.4

The issue exists because Micropython is doing it's own memory allocation. 

In file components/mbedtls/port/sha/dma/sha.c there is a test to see if the external PSRAM needs to have the cache written out.
but the code is protected with 
#if (CONFIG_SPIRAM_USE_CAPS_ALLOC || CONFIG_SPIRAM_USE_MALLOC)
and neither of these is true, CONFIG_SPIRAM_USE_MEMMAP is set and adding that to the test fixes the issue.

Since the PSRAM can be be used in all these cases wouldn't CONFIG_SPIRAM be a more appropriate test? (I tested using this and it
worked).

**Comment by ESP-Marius** [comment]
Thanks for reporting this. 

You are right, need to account for the `CONFIG_SPIRAM_USE_MEMMAP` case as well. Will update.
