### ISSUE TITLE
ESP32S3 Target error Building ULP ADC Assembler (IDFGH-6299)

### ISSUE THREAD

**Issue by ArturG16** [espressif/esp-idf#7963]
Hi all, I'm having trouble to build a ulp adc example with ESP32S3 Target.. 
[632/1041] Performing configure step for 'ulp_main'
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- The C compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Building ULP app ulp_main
-- ULP assembler version: 
CMake Warning at CMakeLists.txt:37 (message):
  WARNING: ULP assembler version is not supported.  Expected to see version:
  2.28.51-esp-20191205.  Please check ESP-IDF ULP setup instructions and
  update the toolchain, or proceed at your own risk.

The setup of ULP assembler version is empty... I think the ${as_version} is the same as the ESP32S2...

How can I fix that?? 

Thanks

**Comment by krzychb** [comment]
Related: #7724 and https://esp32.com/viewtopic.php?t=21906

Hi @ArturG16, unfortunately, this feature has not been implemented yet. We will post an update once the schedule is defined.
