### ISSUE TITLE
[TW#14023] Conflict between Blufi and WiFi promiscuous mode

### ISSUE THREAD

**Issue by nouveauz8957** [espressif/esp-idf#797]
Hello ! I have been using Blufi mode and WiFi promiscuous mode to scan the peer devices. Blufi mode and WiFi promiscuous mode each other can work properly. However when I put them together(start firstly WiFi and secondly Blufi ), I got this trace of crash :
 
ets Jun  8 2016 00:22:57
 
rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
ets Jun  8 2016 00:22:57
 
rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0008,len:8
load:0x3fff0010,len:4420
load:0x40078000,len:10196
load:0x40080000,len:252
entry 0x40080034
I (47) boot: ESP-IDF v3.0-dev-80-g9b30f66-dirty 2nd stage bootloader
I (48) boot: compile time 10:05:11
I (48) boot: Enabling RNG early entropy source...
I (105) boot: SPI Speed      : 40MHz
I (144) boot: SPI Mode       : DIO
I (182) boot: SPI Flash Size : 4MB
I (220) boot: Partition Table:
I (254) boot: ## Label            Usage          Type ST Offset   Length
I (322) boot:  0 nvs              WiFi data        01 02 00009000 00006000
I (392) boot:  1 phy_init         RF data          01 01 0000f000 00001000
I (461) boot:  2 factory          factory app      00 00 00010000 00100000
I (531) boot: End of partition table
I (570) boot: Disabling RNG early entropy source...
I (622) boot: Loading app partition at offset 00010000
I (2662) boot: segment 0: paddr=0x00010018 vaddr=0x00000000 size=0x0ffe8 ( 65512)
I (2663) boot: segment 1: paddr=0x00020008 vaddr=0x3f400010 size=0x30490 (197776) map
I (2713) boot: segment 2: paddr=0x000504a0 vaddr=0x3ffc0000 size=0x02ce0 ( 11488) load
I (2806) boot: segment 3: paddr=0x00053188 vaddr=0x40080000 size=0x00400 (  1024) load
I (2873) boot: segment 4: paddr=0x00053590 vaddr=0x40080400 size=0x1400c ( 81932) load
I (3051) boot: segment 5: paddr=0x000675a4 vaddr=0x400c0000 size=0x00000 (     0) load
I (3052) boot: segment 6: paddr=0x000675ac vaddr=0x00000000 size=0x08a5c ( 35420)
I (3107) boot: segment 7: paddr=0x00070010 vaddr=0x400d0018 size=0x903a4 (590756) map
I (3186) cpu_start: Pro cpu up.
I (3220) cpu_start: Starting app cpu, entry point is 0x40080f2c
I (0) cpu_start: App cpu up.
I (3315) heap_alloc_caps: Initializing. RAM available for dynamic allocation:
I (3386) heap_alloc_caps: At 3FFAFF10 len 000000F0 (0 KiB): DRAM
I (3447) heap_alloc_caps: At 3FFE0440 len 00003BC0 (14 KiB): D/IRAM
I (3512) heap_alloc_caps: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
I (3576) heap_alloc_caps: At 4009440C len 0000BBF4 (46 KiB): IRAM
I (3639) cpu_start: Pro cpu start user code
I (3798) cpu_start: Starting scheduler on PRO CPU.
Guru Meditation Error of type LoadProhibited occurred on core  0. Exception was unhandled.
Register dump:
PC      : 0x40078e6b  PS      : 0x00060730  A0      : 0x800800f9  A1      : 0x3ffe3ce0
A2      : 0x000008e6  A3      : 0x3ff0005c  A4      : 0x40080f98  A5      : 0x000008ef
A6      : 0x000903ac  A7      : 0x00000004  A8      : 0x80078e68  A9      : 0x3ffe3cc0
A10     : 0x3f401395  A11     : 0x00000001  A12     : 0x3ffc36f9  A13     : 0x000008ef
A14     : 0x0000000a  A15     : 0x0000000a  SAR     : 0x00000004  EXCCAUSE: 0x0000001c
EXCVADDR: 0x80080129  LBEG    : 0x4000c46c  LEND    : 0x4000c477  LCOUNT  : 0xffffffff
 
Backtrace: 0x40078e6b:0x3ffe3ce0 0x400800f6:0x3ffe3e70 0x40007c31:0x3ffe3eb0 0x4000073d:0x3ffe3f20
 
CPU halted.
 
I have also changed the configTIMER_TASK_STACK_DEPTH ( in the file ~/build/include/sdkconfig.h ) to 4096 (default 2048). But it doesn’t work.
 
Any suggestions ? Thanks in advance !

**Comment by TianHao-Espressif** [comment]
@nouveauz8957 , could you provide your test code?
