### ISSUE TITLE
ESP-IDF 4.4 zsh Tab autocomplete for serial port in idf.py command is blocked (IDFGH-6307)

### ISSUE THREAD

**Issue by georgik** [espressif/esp-idf#7970]
## Environment

- Development Kit:     none
- IDF version: v4.4-dev-3401-gb86fe0c66c
- Build System:   idf.py
- Operating System:    Linux, macOS
- Using an IDE?: No

## Problem Description

Autocompletion generated by idf.py(click) blocks option to autocomplete port like /dev/tty.usbserial1301. Tab key does not work here.

### Expected Behavior

Tab key in terminal autocompletes /dev/tty.usb....

### Actual Behavior

Tab key in terminal does not autocomplete path to device

### Steps to reproduce

- activate ESP-IDF in zsh
- type: idf.py --port /dev/tt and press TAB, nothing happens

### Workaround

- use other shell e.g. Bash 3.x or PowerShell

**Comment by peica** [comment]
same issue for zsh on idf.py v4.3.2
