### ISSUE TITLE
How to compute the total size of RAM and the usage size  for ESP32? (IDFGH-6313)

### ISSUE THREAD

**Issue by lilygeorge** [espressif/esp-idf#7976]
Hi, I'm need to execute some programs on esp32 and I want to know the total size of RAM and how much the program usage from memory of esp32 ram ?

**Comment by igrr** [comment]
Hi @lilygeorge, please check this section of IDF programming guide, see the parts about measuring static and dynamic RAM usage: https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/performance/ram-usage.html.
