### ISSUE TITLE
[TW#14024] mbed tls Malloc fails when BT is enabled 

### ISSUE THREAD

**Issue by llewellynnu** [espressif/esp-idf#798]
Hi , 
I am working on a product which involves . UART1 , UART2 , I2C , Wifi , BTLE , AWSIoT , PPPoS .
Everything works perfectly if BT is disabled . 
If i enable BT stack malloc in mbedtls for AWSIoT fails. 

Regards

**Comment by negativekelvin** [comment]
https://github.com/espressif/esp-idf/issues/346

Check menuconfig for other memory saving options

**Comment by FayeY** [comment]
Hi @llewellynnu , did the above suggestion help you resolve the issue?

**Comment by llewellynnu** [comment]
Hi
I couldn't get everything running at the same time . Cause I couldn't free
up enough memory.

On Jul 17, 2017 09:10, "FayeY" <notifications@github.com> wrote:

Hi @llewellynnu <https://github.com/llewellynnu> , did the above suggestion
help you resolve the issue?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/espressif/esp-idf/issues/798#issuecomment-315662708>,
or mute the thread

**Comment by FHFS** [comment]
How big is your CONFIG_MBEDTLS_SSL_MAX_CONTENT_LEN? Decreasing this can free up a lot of memory.

**Comment by llewellynnu** [comment]
Hi ,
I have reduced it to 5000
