### ISSUE TITLE
esp32s2 will fail on external PSRAM access for size > 4m (IDFGH-6320)

### ISSUE THREAD

**Issue by pavlohamov** [espressif/esp-idf#7982]
- Development Kit:  esp32s2 custom board
- Module or chip used:  esp32s2 r0 ESP-ROM:esp32s2-rc4-20191025
- IDF version v5.0-dev-518-g6ff72be660
- Build System:        idf.py
- Compiler version: xtensa-esp32s2-elf-gcc (crosstool-NG esp-2021r2) 8.4.0
- Operating System:     Linux
- Using an IDE?: No
- Power Supply:     external 5V

## Problem Description

Device uses external PS-RAM that supposed to be used as heap. New batch of devices is shipped with 8 meg (APS6404) PS-RAM. That leads to loadStoreProhibited exception on boot

### Expected Behavior
System works with whole memory region available as external mem. 

### Actual Behavior
System fails due to exception and reboots

### Steps to reproduce
1. Solder 8 meg psram to esp32s2Wrower kit
2. build and execute app that writes to external RAM

Proposed solution:
limit mmaped size 4 megs

**Comment by ESP-Marius** [comment]
Hi, 

Could you describe a bit more in detail what goes wrong? (Log output, sdkconfig, etc).

The ESP32-S2 should be able to use 8MB just fine, I've got a S2 with ESP-PSRAM64H booting without issues.

**Comment by pavlohamov** [comment]
> Hi,
> 
> Could you describe a bit more in detail what goes wrong? (Log output, sdkconfig, etc).
> 
> The ESP32-S2 should be able to use 8MB just fine, I've got a S2 with ESP-PSRAM64H booting without issues.

It was failing with load/store prohibited exception. On latest IDF it is working fine. Really odd. Closing issue and PR
