### ISSUE TITLE
NimBLE - bond is sometimes not saved in case of re-pairing (IDFGH-6328)

### ISSUE THREAD

**Issue by jspngh** [espressif/esp-idf#7990]
## Environment

- Development Kit: none
- Module or chip used: ESP32-WROVER-E
- IDF version: v4.4-dev-3703-gddc44956bf
- Build System: idf.py
- Compiler version: 8.4.0
- Operating System: Linux
- Using an IDE?: No
- Power Supply: external 5V

## Problem Description

I am using the `bleprph` example and use 2 Android (11) phones to connect and pair to the esp32.
I use I/O capability *DISPLAY YESNO* and have enabled *Use bonding*, *MITM security* and *Use secure connection feature*.
I attached the sdkconfig file for reference.
I made 2 slight modifications to the example code, described in the appropriate section.
The problem I am seeing is the following: bond information is not correctly saved if previously a `BLE_GAP_EVENT_REPEAT_PAIRING` event occurred that was declined by the peripheral (esp32).

In more detail:
Start by bonding 2 phones to the peripheral. It is important to use 2 phones,
since the issue does not seem to occur when using only 1 phone.
Now delete the bond information on one phone and connect again.
This will cause a `BLE_GAP_EVENT_REPEAT_PAIRING` event, since the esp32 already knows this phone.
Decline the pairing (with `key N`), this will cause a disconnect.
Try to connect again with the phone and now accept the pairing (`key Y`).
The phone is now bonded to the esp32. When I now disconnect and connect again, I observe the issue.

### Expected Behavior
The phone can successfully setup an encrypted connection to the esp32 without pairing again.

### Actual Behavior
The phone cannot use the existing bond to securely connect to the esp32. A connection is established, but no security.
The phone then deletes the bond info automatically, since it could not be used.

I think this is related to the changes made in #5530.
If I revert the function `ble_hs_resolv_list_rmv` to what is was before these changes, the issue does not seem to appear.

```cpp
int
ble_hs_resolv_list_rmv(uint8_t addr_type, uint8_t *ident_addr)
{
    int position;

    /* Remove from IRK records */
    position = ble_hs_is_on_resolv_list(ident_addr, addr_type);
    if (position) {

        memmove(&g_ble_hs_resolv_list[position],
                &g_ble_hs_resolv_list[position + 1],
                (g_ble_hs_resolv_data.rl_cnt - position) * sizeof (struct
                        ble_hs_resolv_entry));
        --g_ble_hs_resolv_data.rl_cnt;

        return 0;
    }

    return BLE_HS_ENOENT;
}
```
My guess is that because of the added call to  `ble_rpa_replace_id_with_rand_addr(&addr_type, ident_addr);`
certain info is kept, while is should be removed when the re-pairing of the phone "fails" / is declined.
When accepting the pairing at the `BLE_GAP_EVENT_REPEAT_PAIRING` event, this issue does not occur.

### Steps to reproduce

1. connect phone 1 to the esp32 and successfully pair (`key Y`) + disconnect again
2. connect phone 2 to the esp32 and successfully pair (`key Y`) + disconnect again
3. delete bond info on phone 1
4. connect phone 1 to the esp32 and decline pair on esp32 (`key N`), disconnect will happen
5. connect phone 1 to the esp32 and successfully pair (`key Y`) + disconnect again
6. try to connect phone 1 to the esp32, issue will occur

### Code to reproduce this issue

Use the `nimble/bleprph` example with the following modifications. 
Change key distribution:
```cpp
    ble_hs_cfg.sm_our_key_dist = BLE_SM_PAIR_KEY_DIST_ENC | BLE_SM_PAIR_KEY_DIST_ID;
    ble_hs_cfg.sm_their_key_dist = BLE_SM_PAIR_KEY_DIST_ENC | BLE_SM_PAIR_KEY_DIST_ID;
```
Add `ble_gap_security_initiate(event->connect.conn_handle);` to `BLE_GAP_EVENT_CONNECT`:
```cpp
    case BLE_GAP_EVENT_CONNECT:
        /* A new connection was established or a connection attempt failed. */
        MODLOG_DFLT(INFO, "connection %s; status=%d ",
                    event->connect.status == 0 ? "established" : "failed",
                    event->connect.status);
        if (event->connect.status == 0) {
            rc = ble_gap_conn_find(event->connect.conn_handle, &desc);
            assert(rc == 0);
            bleprph_print_conn_desc(&desc);
            ble_gap_security_initiate(event->connect.conn_handle);
        }
        MODLOG_DFLT(INFO, "\n");

        if (event->connect.status != 0) {
            /* Connection failed; resume advertising. */
            bleprph_advertise();
        }
        return 0;
```

## Debug Logs

<details>
    <summary>Log at the moment issue occurs</summary>

    I (154951) NimBLE: GAP procedure initiated: advertise; 
    I (154951) NimBLE: disc_mode=2
    I (154951) NimBLE:  adv_channel_map=0 own_addr_type=0 adv_filter_policy=0 adv_itvl_min=0 adv_itvl_max=0

    I (158351) NimBLE: connection established; status=0 
    I (158351) NimBLE: handle=0 our_ota_addr_type=0 our_ota_addr=
    I (158351) NimBLE: e0:e2:e6:47:90:de
    I (158361) NimBLE:  our_id_addr_type=0 our_id_addr=
    I (158361) NimBLE: e0:e2:e6:47:90:de
    I (158361) NimBLE:  peer_ota_addr_type=1 peer_ota_addr=
    I (158371) NimBLE: 40:a1:ed:de:45:ed
    I (158371) NimBLE:  peer_id_addr_type=1 peer_id_addr=
    I (158381) NimBLE: 40:a1:ed:de:45:ed
    I (158381) NimBLE:  conn_itvl=36 conn_latency=0 supervision_timeout=500 encrypted=0 authenticated=0 bonded=0

    I (159341) NimBLE: connection updated; status=0 
    I (159341) NimBLE: handle=0 our_ota_addr_type=0 our_ota_addr=
    I (159341) NimBLE: e0:e2:e6:47:90:de
    I (159341) NimBLE:  our_id_addr_type=0 our_id_addr=
    I (159351) NimBLE: e0:e2:e6:47:90:de
    I (159351) NimBLE:  peer_ota_addr_type=1 peer_ota_addr=
    I (159361) NimBLE: 40:a1:ed:de:45:ed
    I (159361) NimBLE:  peer_id_addr_type=1 peer_id_addr=
    I (159371) NimBLE: 40:a1:ed:de:45:ed
    I (159371) NimBLE:  conn_itvl=6 conn_latency=0 supervision_timeout=500 encrypted=0 authenticated=0 bonded=0

    I (159581) NimBLE: connection updated; status=0 
    I (159591) NimBLE: handle=0 our_ota_addr_type=0 our_ota_addr=
    I (159591) NimBLE: e0:e2:e6:47:90:de
    I (159591) NimBLE:  our_id_addr_type=0 our_id_addr=
    I (159601) NimBLE: e0:e2:e6:47:90:de
    I (159601) NimBLE:  peer_ota_addr_type=1 peer_ota_addr=
    I (159611) NimBLE: 40:a1:ed:de:45:ed
    I (159611) NimBLE:  peer_id_addr_type=1 peer_id_addr=
    I (159621) NimBLE: 40:a1:ed:de:45:ed
    I (159621) NimBLE:  conn_itvl=36 conn_latency=0 supervision_timeout=500 encrypted=0 authenticated=0 bonded=0

    I (202311) NimBLE: disconnect; reason=531 
    I (202311) NimBLE: handle=0 our_ota_addr_type=0 our_ota_addr=
    I (202311) NimBLE: e0:e2:e6:47:90:de
    I (202321) NimBLE:  our_id_addr_type=0 our_id_addr=
    I (202321) NimBLE: e0:e2:e6:47:90:de
    I (202331) NimBLE:  peer_ota_addr_type=1 peer_ota_addr=
    I (202331) NimBLE: 40:a1:ed:de:45:ed
    I (202341) NimBLE:  peer_id_addr_type=1 peer_id_addr=
    I (202341) NimBLE: 40:a1:ed:de:45:ed
    I (202351) NimBLE:  conn_itvl=36 conn_latency=0 supervision_timeout=500 encrypted=0 authenticated=0 bonded=0
</details>

<details>
<summary>Expected log</summary>

    I (202371) NimBLE: GAP procedure initiated: advertise; 
    I (202371) NimBLE: disc_mode=2
    I (202371) NimBLE:  adv_channel_map=0 own_addr_type=0 adv_filter_policy=0 adv_itvl_min=0 adv_itvl_max=0

    I (205681) NimBLE: connection established; status=0 
    I (205681) NimBLE: handle=0 our_ota_addr_type=0 our_ota_addr=
    I (205681) NimBLE: e0:e2:e6:47:90:de
    I (205681) NimBLE:  our_id_addr_type=0 our_id_addr=
    I (205691) NimBLE: e0:e2:e6:47:90:de
    I (205691) NimBLE:  peer_ota_addr_type=0 peer_ota_addr=
    I (205701) NimBLE: 9c:6b:72:ae:68:44
    I (205701) NimBLE:  peer_id_addr_type=0 peer_id_addr=
    I (205711) NimBLE: 9c:6b:72:ae:68:44
    I (205711) NimBLE:  conn_itvl=38 conn_latency=0 supervision_timeout=500 encrypted=0 authenticated=0 bonded=0

    I (206181) NimBLE: encryption change event; status=0 
    I (206181) NimBLE: handle=0 our_ota_addr_type=0 our_ota_addr=
    I (206181) NimBLE: e0:e2:e6:47:90:de
    I (206191) NimBLE:  our_id_addr_type=0 our_id_addr=
    I (206191) NimBLE: e0:e2:e6:47:90:de
    I (206191) NimBLE:  peer_ota_addr_type=0 peer_ota_addr=
    I (206201) NimBLE: 9c:6b:72:ae:68:44
    I (206211) NimBLE:  peer_id_addr_type=0 peer_id_addr=
    I (206211) NimBLE: 9c:6b:72:ae:68:44
    I (206221) NimBLE:  conn_itvl=38 conn_latency=0 supervision_timeout=500 encrypted=1 authenticated=1 bonded=1

    I (206231) NimBLE: subscribe event; conn_handle=0 attr_handle=8 reason=3 prevn=0 curn=0 previ=0 curi=1

    I (206751) NimBLE: connection updated; status=0 
    I (206751) NimBLE: handle=0 our_ota_addr_type=0 our_ota_addr=
    I (206751) NimBLE: e0:e2:e6:47:90:de
    I (206751) NimBLE:  our_id_addr_type=0 our_id_addr=
    I (206761) NimBLE: e0:e2:e6:47:90:de
    I (206761) NimBLE:  peer_ota_addr_type=0 peer_ota_addr=
    I (206771) NimBLE: 9c:6b:72:ae:68:44
    I (206771) NimBLE:  peer_id_addr_type=0 peer_id_addr=
    I (206781) NimBLE: 9c:6b:72:ae:68:44
    I (206781) NimBLE:  conn_itvl=6 conn_latency=0 supervision_timeout=500 encrypted=1 authenticated=1 bonded=1

    I (207081) NimBLE: connection updated; status=0 
    I (207081) NimBLE: handle=0 our_ota_addr_type=0 our_ota_addr=
    I (207081) NimBLE: e0:e2:e6:47:90:de
    I (207081) NimBLE:  our_id_addr_type=0 our_id_addr=
    I (207091) NimBLE: e0:e2:e6:47:90:de
    I (207091) NimBLE:  peer_ota_addr_type=0 peer_ota_addr=
    I (207101) NimBLE: 9c:6b:72:ae:68:44
    I (207101) NimBLE:  peer_id_addr_type=0 peer_id_addr=
    I (207111) NimBLE: 9c:6b:72:ae:68:44
    I (207111) NimBLE:  conn_itvl=38 conn_latency=0 supervision_timeout=500 encrypted=1 authenticated=1 bonded=1
</details>

## Other items if possible

- [x] [sdkconfig file](https://github.com/espressif/esp-idf/files/7632238/sdkconfig.zip)

**Comment by flonas955** [comment]
I have opened a very similar issue [here](https://github.com/espressif/esp-idf/issues/7937). It looks just like the problem @jspngh is facing.

**Comment by rahult-github** [comment]
@flonas955  @jspngh  , the changes put by [this](https://github.com/espressif/esp-nimble/commit/f322e780aadfcfdc4a21e1418f22db3216e46d97) commit and already part of release/v5.0 . Closing this issue . Please feel free to open, if issue still seen.
