### ISSUE TITLE
How to correctly init SPI on ESP32? 

### ISSUE THREAD

**Issue by vowstar** [espressif/esp-idf#8]
I'm trying to play a SPI LCD using ESP32. On ESP31B, I use these code below. But on ESP32, the spi_register.h is different form ESP31B, for example ``SPI_USR_MOSI_BITLEN_S`` is disappeared.
```C
#define HSPI 2
void spi_init()
{
	//SPI clk = 40MHz
	WRITE_PERI_REG(SPI_CLOCK(HSPI), (0<<SPI_CLKDIV_PRE_S) |
		(1<<SPI_CLKCNT_N_S)|(1<<SPI_CLKCNT_L_S)|(0<<SPI_CLKCNT_H_S));
	WRITE_PERI_REG(SPI_CTRL(HSPI), 0);//SPI_WR_BIT_ORDER);
	WRITE_PERI_REG(SPI_USER(HSPI), SPI_CS_SETUP|SPI_CS_HOLD|SPI_USR_MOSI|SPI_WR_BYTE_ORDER);
	WRITE_PERI_REG(SPI_USER1(HSPI), (9<<SPI_USR_MOSI_BITLEN_S));
}
```

Is ``SPI_USR_MOSI_BITLEN_S``  in ESP31B equivalent to ``SPI_USR_MOSI_DBITLEN_S`` in ESP32 ?  How to correctly init SPI on ESP32? 

Thanks.

**Comment by costaud** [comment]
yes, SPI_USR_MOSI_DBITLEN_S is the same as SPI_USR_MOSI_BITLEN_S.
