### ISSUE TITLE
Compiling last esp-idf with "Bootloader log verbosity" set to "Verbose" causes an exception on boot

### ISSUE THREAD

**Issue by jolivepetrus** [espressif/esp-idf#80]
Compiling last esp-idf with "Bootloader log verbosity" set to "Verbose" causes an exception on boot.

Boot log:

load:0x3ffc0000,len:3028
ho 0 tail 12 room 4
load:0x40078000,len:4576
load:0x40080000,len:472
entry 0x40080060
I (30) boot: Espressif ESP32 2nd stage bootloader v. V0.1
I (38) boot: compile time 15:20:29
D (61) boot: mmu set paddr=00000000 count=1
D (61) boot: magic e9
D (61) boot: blocks 04
D (62) boot: spi_mode 02
D (62) boot: spi_speed 00
D (66) boot: spi_size 01
I (70) boot: SPI Speed      : 40MHz
I (77) boot: SPI Mode       : DIO
I (83) boot: SPI Flash Size : 2MB
I (89) boot: Partition Table:
I (94) boot: ## Label            Usage          Type ST Offset   Length
D (106) boot: load partition table entry from 4000(3f404000)
D (114) boot: type=0 subtype=0
I (119) boot:  0 factory          factory app      00 00 00010000 00100000
D (131) boot: load partition table entry from 4020(3f404020)
D (139) boot: type=1 subtype=1
I (144) boot:  1 rfdata           RF data          01 01 00110000 00040000
D (156) boot: load partition table entry from 4040(3f404040)
D (164) boot: type=1 subtype=2
I (169) boot:  2 wifidata         WiFi data        01 02 00150000 00040000
D (180) boot: load partition table entry from 4060(3f404060)
D (189) boot: type=ff subtype=ff
I (194) boot: End of partition table
I (201) boot: Loading app partition at offset 00010000
D (210) boot: mmu set paddr=00010000 count=16
D (216) boot: bin_header: 233 9 2 1 4008090c
I (223) boot: section 0: paddr=0x00000020 vaddr=0x00000000 size=0x0ffe8 ( 65512) 
D (235) boot: found drom section, map from 00010010 to 3f400010
I (244) boot: section 1: paddr=0x00010010 vaddr=0x3f400010 size=0x03008 ( 12296) map
I (257) boot: section 2: paddr=0x00013020 vaddr=0x3ffb2bf0 size=0x020b4 (  8372) load
I (274) boot: section 3: paddr=0x000150dc vaddr=0x40080000 size=0x00400 (  1024) load
Fatal exception (28): LoadProhibited
epc1=0x4008014f, epc2=0x00000000, epc3=0x00000000, excvaddr=0x00000000, depc=0x00000000

**Comment by igrr** [comment]
Issue is caused by placement of esp_log_timestamp and esp_log_early_timestamp functions into IRAM. When compiling in bootloader mode, these functions shouldn't be attributed to IRAM section.
