### ISSUE TITLE
Distribute code in OTA (IDFGH-6338)

### ISSUE THREAD

**Issue by hdpklm** [espressif/esp-idf#8000]
Hello All

I have a lots of librarys and I want to distribute in different ota partition, so wen I want to update any library only update one partition, not the full code, and not need to repeat all library in all partition and consume a lot of internet for update the code.

example of partitions:
factory: boot code and initialize the sensors
OTA_0: has the library of bluetooth
OTA_1: has library of sensors
OTA_2: has some equation and diferent functions.
OTA_3: reserve for download and update specific OTA number

So I need a way to call function in other partition from the main OTA or Factory partition.

is this available and how can I do that

thank you a lot

**Comment by mahavirj** [comment]
@hdpklm 

> So I need a way to call function in other partition from the main OTA or Factory partition.

There is no provision for this as now. IDF bootloader only deals with selected active OTA partition, copying its code/data section to IRAM/DRAM and setting up flash cache mappings etc.

> consume a lot of internet for update the code

For this you may consider "delta" OTA update, we had done preliminary analysis and you may find discussion at https://github.com/espressif/esp-idf/issues/7543 useful in this context.

Hope this helps.

**Comment by hdpklm** [comment]
Hello @mahavirj 

Thanks for answering
Can I download a binary code to the storage partition and run it from the main function, or copy to memory and call it address

**Comment by mahavirj** [comment]
@hdpklm

No, this is not supported feature. I recommend that you go through https://esp32.com forum thread, there are some relevant topics on supporting such feature (mostly exploratory work around ELF loading). I will go ahead and close this issue.
