### ISSUE TITLE
Use websocket to crash during regular execution of http tasks (IDFGH-6343)

### ISSUE THREAD

**Issue by jiaxieya** [espressif/esp-idf#8005]
Operating System: Windows
Using an IDE?: VS Code
Power Supply: USB
I (48) boot: ESP-IDF v4.3.1-dirty 2nd stage bootloader
I (49) boot: compile time 16:03:22
I (49) boot: chip revision: 3
I (51) boot.esp32c3: SPI Speed : 80MHz
I (56) boot.esp32c3: SPI Mode : DIO
I (60) boot.esp32c3: SPI Flash Size : 4MB

## Problem Description
The regular execution of the http task is used to obtain the necessary parameters to change the link used by the websocket, but the execution of the websocket connection after the second run of the http task causes a crash. Part of the parameter part is in privacy. I have deleted it in the code. The websocket link can be replaced with any link for testing.

### Code to reproduce this issue

static void http_test_task(void *pvParameters)
{
    char local_response_buffer[MAX_HTTP_OUTPUT_BUFFER] = {0};
    /**
     * NOTE: All the configuration parameters for http_client must be spefied either in URL or as host and path parameters.
     * If host and path parameters are not set, query parameter will be ignored. In such cases,
     * query parameter should be specified in URL.
     *
     * If URL as well as host and path parameters are specified, values of host and path will be considered.
     */
    esp_http_client_config_t config = {
        .host = "api.m.taobao.com",
        .path = "/rest/api3.do?api=mtop.common.getTimestamp",
        .query = "esp",
        .event_handler = _http_event_handler,
        .user_data = local_response_buffer, // Pass address of local buffer to get response
        .disable_auto_redirect = true,
    };
    esp_http_client_handle_t client = esp_http_client_init(&config);

    cJSON *root = NULL;
    cJSON *item = NULL;
    cJSON *number = NULL;

   
    char timestamp[] = "";
    char *out;

    while (1)
    {

        // GET
        client = esp_http_client_init(&config);

        esp_err_t err = esp_http_client_perform(client);
        if (err == ESP_OK)
        {
            // ESP_LOGI(TAG, "HTTP GET Status = %d, content_length = %d",
            //          esp_http_client_get_status_code(client),
            //          esp_http_client_get_content_length(client));
        }
        else
        {
            ESP_LOGE(TAG, "HTTP GET request failed: %s", esp_err_to_name(err));
        }
        // ESP_LOGI(TAG, "local_response_buffer: %s", local_response_buffer);
        /**************************************************************************************/
        root = cJSON_Parse(local_response_buffer);
        if (!root)
        {
            printf("Error before: [%s]\n", cJSON_GetErrorPtr());
        }
        else
        {
            item = cJSON_GetObjectItem(root, "data");
            number = cJSON_GetObjectItem(item, "t");

            expeed_timestamp = 0;
            out = cJSON_Print(number);

            expeed_timestamp = strtoll(out + 1, NULL, 0) / 1000;

            cJSON_free(out);

            // cJSON_free(number);
            // cJSON_free(item);
            // expeed_timestamp = cJSON_GetNumberValue(number);

            printf("timestamp --> %lld\n\n", expeed_timestamp);
        }

        cJSON_Delete(root);

        esp_http_client_close(client);
        esp_http_client_cleanup(client);
        memset(local_response_buffer, 0, 2048);
        vTaskDelay(100 / portTICK_PERIOD_MS);

        ESP_LOGI(TAG, "Finish http example");

        if (post_param == NULL)
        {
            post_param = malloc(360 * sizeof(char));
        }
        else
        {
            memset(post_param, 0, 360);
        }
        snprintf((char *)post_param, 360, "%s%lld%s", apikey, expeed_timestamp, param);

        mbedtls_md5_context md5_ctx;
        mbedtls_md5_init(&md5_ctx);
        mbedtls_md5_starts_ret(&md5_ctx);
        mbedtls_md5_update_ret(&md5_ctx, post_param, strlen((char *)post_param));
        mbedtls_md5_finish_ret(&md5_ctx, decrypt);
        // ESP_LOGI(TAG, "Md5加密前:[%s] \n md5加密后(32位):", post_param);

        for (int i = 0; i < 16; i++)
        {
            printf("%02x", decrypt[i]);
        }

        memset(post_param, 0, 360);
        snprintf((char *)post_param, 360, "%s%s%lld%s%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%02x%s%s", wsurl, "&curtime=", expeed_timestamp, "&checksum=", decrypt[0], decrypt[1], decrypt[2], decrypt[3], decrypt[4], decrypt[5], decrypt[6], decrypt[7], decrypt[8], decrypt[9], decrypt[10], decrypt[11], decrypt[12], decrypt[13], decrypt[14], decrypt[15], "&param=", param);

        mbedtls_md5_free(&md5_ctx);

        printf("\n");
        ESP_LOGI(TAG, "最终结果: %s ", post_param);

        if (websocket_cfg.uri == NULL)
        {
            websocket_cfg.uri = malloc(360 * sizeof(char));
            ESP_LOGI(TAG, "malloc  ok");
        }
        else
        {
            memset(websocket_cfg.uri, 0, 360);
            free(websocket_cfg.uri);

            esp_websocket_client_destroy(ws_client);
            ESP_LOGI(TAG, "memset  ok");

            websocket_cfg.uri = malloc(360 * sizeof(char));
            ESP_LOGI(TAG, "malloc  ok");
        }

        snprintf((char *)websocket_cfg.uri, 360, "%s", (char *)post_param);

        int free_heap_size = 0;
        free_heap_size = esp_get_free_heap_size();
        ESP_LOGI(TAG, "esp_get_free_heap_size %d", free_heap_size);

if(temp==0)
{
        xTaskCreate(websocket_app_start, "websocket_app_start", 10240, NULL, 5, NULL);
        temp=1;

}

        http_temp++;
        vTaskDelay(10 * 1000 / portTICK_PERIOD_MS);

               vTaskList((char *) &InfoBuffer);
                printf("任务名      任务状态 优先级   剩余栈 任务序号\r\n");
                printf("\r\n%s\r\n", InfoBuffer);

    }
    //todo 此时为每次都加密一次，可能造成延迟，可三分钟调用一次任务，用于更新 ws url
}

static void websocket_app_start(void)
{

    int free_heap_size = 0;
  
    while (1)
    {
 
        ws_client = esp_websocket_client_init(&websocket_cfg);
        // ESP_LOGI(TAG, "esp_websocket_client_init  ok");

        esp_websocket_register_events(ws_client, WEBSOCKET_EVENT_ANY, websocket_event_handler, (void *)ws_client);
        ESP_LOGI(TAG, "esp_websocket_register_events  ok");
        vTaskDelay(1 * 1000 / portTICK_RATE_MS);

        esp_websocket_client_start(ws_client);
        char data[32];
 
        vTaskDelay(2 * 1000 / portTICK_RATE_MS);
        
            int len = sprintf(data, "hello");
            ESP_LOGI(TAG, "Sending %s", data);
            esp_websocket_client_send_bin(ws_client, (const char *)data, 5, portMAX_DELAY);
        vTaskDelay(3 * 1000 / portTICK_RATE_MS);

        esp_websocket_client_destroy(ws_client);
        ws_client = NULL;
        ESP_LOGI(TAG, "Websocket destroy");

    }
}

## Debug Logs

Guru Meditation Error: Core  0 panic'ed (Load access fault). Exception was unhandled.

Stack dump detected
Core  0 register dump:
MEPC    : 0x40388e44  RA      : 0x40388e44  SP      : 0x3fca9c50  GP      : 0x3fc8e800  
0x40388e44: xEventGroupWaitBits at D:/esp/esp-idf-4.3.1/components/freertos/event_groups.c:338

0x40388e44: xEventGroupWaitBits at D:/esp/esp-idf-4.3.1/components/freertos/event_groups.c:338

TP      : 0x3fc8d028  T0      : 0x4005890e  T1      : 0x3fcac09c  T2      : 0x3fc68a28
S0/FP   : 0x00000000  S1      : 0x3fc95000  A0      : 0x00000001  A1      : 0x00000001  
A2      : 0x00000000  A3      : 0x00000004  A4      : 0x00000001  A5      : 0x3fc95000  
A6      : 0x00000005  A7      : 0x00002710  S2      : 0x00000001  S3      : 0x003c0000
S4      : 0xffffffff  S5      : 0x00000001  S6      : 0x00000000  S7      : 0x00000000
S8      : 0x00000000  S9      : 0x00000000  S10     : 0x00000000  S11     : 0x00000000
T3      : 0x3fcac080  T4      : 0x00000002  T5      : 0x00000000  T6      : 0x3fd34413
MSTATUS : 0x00001881  MTVEC   : 0x40380001  MCAUSE  : 0x00000005  MTVAL   : 0x003c0000
0x40380001: _vector_table at ??:?

MHARTID : 0x00000000

Failed to run gdb_panic_server.py script: Command '['riscv32-esp-elf-gdb', '--batch', '-n', 'c:\\users\\user\\desktop\\temp\\websocket\\build\\websocket_example.elf', '-ex', 'target remote | "C:\\Users\\user\\.espressif\\python_env\\idf4.3_py3.8_env\\Scripts\\python.exe" "d:\\esp\\esp-idf-4.3.1\\tools\\..\\tools\\gdb_panic_server.py" --target esp32c3 "C:\\Users\\user\\AppData\\Local\\Temp\\tmphezy6lwm"', '-ex', 'bt']' returned non-zero exit status 3221225781.
b''

Core  0 register dump:
MEPC    : 0x40388e44  RA      : 0x40388e44  SP      : 0x3fca9c50  GP      : 0x3fc8e800
TP      : 0x3fc8d028  T0      : 0x4005890e  T1      : 0x3fcac09c  T2      : 0x3fc68a28
S0/FP   : 0x00000000  S1      : 0x3fc95000  A0      : 0x00000001  A1      : 0x00000001
A2      : 0x00000000  A3      : 0x00000004  A4      : 0x00000001  A5      : 0x3fc95000
A6      : 0x00000005  A7      : 0x00002710  S2      : 0x00000001  S3      : 0x003c0000
S4      : 0xffffffff  S5      : 0x00000001  S6      : 0x00000000  S7      : 0x00000000
S8      : 0x00000000  S9      : 0x00000000  S10     : 0x00000000  S11     : 0x00000000
T3      : 0x3fcac080  T4      : 0x00000002  T5      : 0x00000000  T6      : 0x3fd34413
MSTATUS : 0x00001881  MTVEC   : 0x40380001  MCAUSE  : 0x00000005  MTVAL   : 0x003c0000
MHARTID : 0x00000000

Stack memory:
3fca9c50: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x3fc95000 0x3fca7494 0x42007c58
3fca9c70: 0x00000000 0x3fc95000 0x3fca7494 0x42007d50 0x3c0b4548 0x3fca9c90 0x3c0b4000 0x420063de
3fca9c90: 0x6c6c6568 0x0000006f 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
3fca9cb0: 0x00000000 0x00000000 0x00000000 0x40389776 0x00000000 0x00000000 0x00000000 0x00000000
3fca9cd0: 0x00000000 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0x27146414 0x01010107 0x00000001 0x000000ff
00000000 0x40000000
3fca9d10: 0x94a03595 0x3fdfffff 0x35afe535 0x3fe00000 0x94a03595 0x3fcfffff 0x00000000 0x3fc00000
3fca9d30: 0x00000000 0x40300000 0x00000000 0x3ff80000 0x636f4361 0x3fd287a7 0x8b60c8b3 0x3fc68a28
3fca9d50: 0x509f79fb 0x3fd34413 0x00000000 0x40240000 0x00000000 0x401c0000 0x00000000 0x40140000
3fca9d70: 0x00000000 0x43500000 0x00000000 0x7ff80000 0x7fc00000 0x3fc8e000 0x00003194 0x3c0c84e4
3fca9d90: 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0x00001969 0x3fc95684 0x3fc95684 0x72223a22 0x6c757365
3fca9db0: 0x222c2274 0x61746164 0x227b3a22 0x22627573 0x7474223a 0x222c2273 0x68747561 0x2264695f
3fca9dd0: 0x3032223a 0x31613934 0x64663262 0x65616465 0x62333535 0x63333064 0x34663665 0x61303238
3fca9df0: 0x2c223463 0x6e6f6322 0x746e6574 0x61223a22 0x63305248 0x4c364d48 0x61683979 0x4c705658
3fca9e10: 0x5a77396d 0x637a3557 0x596c5647 0x59756732 0x64763432 0x4c7a5248 0x64765232 0x62733532
3fca9e30: 0x4c6b4632 0x51596c31 0x5668646e 0x54354531 0x4d5a5230 0x54453130 0x564e706d 0x597a4645
3fca9e50: 0x61734a7a 0x52584231 0x565a4e6a 0x57334645 0x65524a54 0x57363145 0x52526c6d 0x54304931
3fca9e70: 0x64425255 0x52553130 0x524e4654 0x57704a46 0x4d56646b 0x52556c56 0x52504654 0x54334645
3fca9e90: 0x634b6845 0x4d457046 0x62756748 0x227a4158 0x6572222c 0x746c7573 0x2264695f 0x222c313a
3fca9eb0: 0x6c5f7369 0x22747361 0x7572743a 0x69222c65 0x69665f73 0x6873696e 0x72743a22 0x222c6575
3fca9ed0: 0x6e6f736a 0x6772615f 0x7b3a2273 0x6e616322 0x226c6563 0x2230223a 0x7464222c 0x223a2265
3fca9ef0: 0x22776172 0x7464222c 0x323a2273 0x7266222c 0x5f656d61 0x3a226469 0x75222c31 0x3a226c72
3fca9f10: 0x7d223122 0x73222c7d 0x3a226469 0x61776122 0x64633030 0x62363331 0x30786440 0x31313030
3fca9f30: 0x62343035 0x61356564 0x30383531 0x222c2230 0x65646f63 0x30223a22 0x64222c22 0x22637365
3fca9f50: 0x7573223a 0x73656363 0x767d2273 0x222c2265 0x22646973 0x7761223a 0x63303061 0x36333164
3fca9f70: 0x78644062 0x31303030 0x34303531 0x35656462 0x38353161 0x2c223030 0x78657422 0x223a2274
3fca9f90: 0x6c6c6568 0x222c226f 0x64697575 0x61223a22 0x30306177 0x33316463 0x64406236 0x30303078
3fca9fb0: 0x30353131 0x65646234 0x35316135 0x22303038 0x6f76222c 0x5f656369 0x77736e61 0x3a227265
3fca9fd0: 0x63227b5b 0x65746e6f 0x3a22746e 0xa0bde422 0xefbda5e5 0xa7e88cbc 0xb088e581 0xe6a0bde4
3fca9ff0: 0xbee59188 0xa38de888 0xefb8b9e5 0x2c2281bc 0x70797422 0x223a2265 0x22535454 0x2c7d5d7d
3fcaa010: 0x73657222 0x5f746c75 0x3a226469 0x69222c31 0x616c5f73 0x3a227473 0x65757274 0x7369222c
3fcaa030: 0x6e69665f 0x22687369 0x6c61663a 0x2c7d6573 0x64697322 0x61223a22 0x30306177 0x33316463

## Other items if possible

- [ ] sdkconfig file (attach the sdkconfig file from your project folder)
- [ ] elf file in the ``build`` folder (**note this may contain all the code details and symbols of your project.**)
- [ ] coredump (This provides stacks of tasks.)

**Comment by ESP-YJM** [comment]
@jiaxieya It seems that the pointer used to access the data was either not initialized or was corrupted. Could you provide a concise code to reproduce the problem so that I can reproduce it locally. I can’t combine the code you pasted to reproduce the problem.

**Comment by Alvin1Zhang** [comment]
@jiaxieya Thanks for reporting, would you please help share if any updates for the issue? Thanks.

**Comment by jiaxieya** [comment]
> @jiaxieya Thanks for reporting, would you please help share if any updates for the issue? Thanks.
I have not figured out the specific problem. The method I currently take is to adjust the priority of freertos tasks so that they are the same, and I set up two websocket clients to switch between them in turn (to ensure that there is sufficient time for each release) , This problem seems to be solved
