### ISSUE TITLE
xTimerIsTimerActive incorrectly returns pdTRUE when called from the timer callback. (IDFGH-6353)

### ISSUE THREAD

**Issue by h2zero** [espressif/esp-idf#8014]
- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

## Environment

- Development Kit:      [ESP32-DevKitC]
- Kit version (for WroverKit/PicoKit/DevKitC): [|v3]
- Module or chip used:  [ESP32-WROVER]
- IDF version (run ``git describe --tags`` to find it): v4.4-dev-2030-gd93887f9f0
- Build System:         [idf.py]
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it):
    // 1.22.0-80-g6c4433a
- Operating System:     [Linux]
- Using an IDE?: [No]
- Power Supply:         [USB]

## Problem Description

xTimerIsTimerActive returns pdTRUE even though the timer has expired if checked in the callback function. 
This causes the NimBLE scan timer to fail to stop the scan when using FreeRTOS timers instead of esp-timer.

### Expected Behavior

xTimerIsTimerActive should return pdFALSE when the timer is no longer active.

### Actual Behavior

xTimerIsTimerActive returns pdTRUE when the timer is not active.

### Steps to reproduce

1. Using NimBLE blecent example, set a time for the scanner to stop (I used 5000ms). 
2. Restart the scanner.
3. Eventually the scan stop timer will fail and just continue scanning.

The error occurs due to this line https://github.com/espressif/esp-idf/blob/98ad01e5fc0779d11209350d8ec31fe3d2137ed5/components/freertos/FreeRTOS-Kernel/timers.c#L846

As it sets the active flag and then calls the callback at this line https://github.com/espressif/esp-idf/blob/98ad01e5fc0779d11209350d8ec31fe3d2137ed5/components/freertos/FreeRTOS-Kernel/timers.c#L852

This has been fixed upstream with this PR: https://github.com/FreeRTOS/FreeRTOS-Kernel/pull/305

**Comment by AxelLin** [comment]
@Dazza0 Any update?
