### ISSUE TITLE
OpenThread : init issue (IDFGH-6365)

### ISSUE THREAD

**Issue by ncohen17** [espressif/esp-idf#8025]
We have tried the example setup for openthread shown in ESP-IDF openthread git repo.

We see the ESP32 BR Host gets connected to configured WiFi and also starts talking with RCP (ESP32 H2) but then we get some error which i have attached in the log files.

Here is our setup
1. ESP32_DevKitC_V4 (BR) + ESP32_H2-DevKitC-1 (RCP) connected over UART
2. Using ESP-IDF release branch  "release/v4.4"
3. Windows 10PC

Please see the ESP32_OTBR_LOG file for the error. I have also attached the RCP log for further clarifications.

[ESP32_OTBR_LOG.txt](https://github.com/espressif/esp-idf/files/7667592/ESP32_OTBR_LOG.txt)
[ESP32H2_RCP_LOG.txt](https://github.com/espressif/esp-idf/files/7667593/ESP32H2_RCP_LOG.txt)

**Comment by chshu** [comment]
It was a legacy issue has not been fixed on v4.4, could you try out with the latest master? Both ESP32-H2 and OpenThread related features are move forward on master quickly.
