### ISSUE TITLE
dIsable_auto_redirect on http client results in error (IDFGH-6371)

### ISSUE THREAD

**Issue by mbbender** [espressif/esp-idf#8029]
https://github.com/espressif/esp-idf/blob/4143a3f572f6060258ffac91f110a095a8478966/components/esp_http_client/esp_http_client.c#L790

I would expect that adding the disable auto redirect flag on the http client would allow one to manually intercept the redirect and continue processing it. Current behavior throws the same error as if you've passed MAX_REDIRECTS. If this is intended behavior, how is one suppose to to process 301/302's manually? I need to modify the headers between redirects to remove authorization headers.

**Comment by laukik-hase** [comment]
Hello, @mbbender!

Thank you for submitting the issue.

Could you please try this patch [http_disable_auto_redirect_fix.zip](https://github.com/espressif/esp-idf/files/7853313/http_disable_auto_redirect_fix.zip) and let me know does it work as you expected?

You can take a look at the `esp_http_client` example after applying the patch, especially the `_http_event_handler` for the redirect event and the `http_absolute_redirect_manual()` function for execution.
