### ISSUE TITLE
Log Output level for PMKSA Cache not right (IDFGH-6370)

### ISSUE THREAD

**Issue by wiwild** [espressif/esp-idf#8030]
Why is this line reported as an error ? Is this wanted ? If yes how to prevent it ? 

Right now this triggers an error on each wifi connection. Shouldn't this be MSG_DEBUG instead ?

https://github.com/espressif/esp-idf/blob/master/components/wpa_supplicant/src/rsn_supp/pmksa_cache.c#L438

**Comment by sagb2015** [comment]
@wiwild - Thanks for pointing out. We will fix this.

**Comment by AxelLin** [comment]
Similar mistake here:
https://github.com/espressif/esp-idf/blob/master/components/wpa_supplicant/src/common/dpp.c#L6114
