### ISSUE TITLE
[TW#12474] time() rollover

### ISSUE THREAD

**Issue by GarageGadget** [espressif/esp-idf#804]
Hi,

I am evaluating the Esp32 for a application with a potential +20 year life expectancy:-

- The 32 bit time() function will overflow in (2038-01-19 03:14:08 UTC, ignoring leap seconds).

I would suggest it would be better to implement time() using the 64 bit Unix time.

Any chance of this happening or is their any other suggestions?

BR,
Garage Gadget

**Comment by negativekelvin** [comment]
https://github.com/espressif/esp-idf/issues/584

**Comment by igrr** [comment]
Closing this as duplicate of #584.
