### ISSUE TITLE
【ESP32-C3/IO mapping for radio TX and RX】Is it possible to implement the IO mapping for radio tx/rx monitoring? (IDFGH-6388)

### ISSUE THREAD

**Issue by xiaolongba** [espressif/esp-idf#8047]
**Is your feature request related to a problem? Please describe.**
> actually, It is not really related to a problem, instead, it is a new feature for radio Tx or Rx debugging when doing radio-related cases, such as the multi-connection, etc.

**Describe the solution you'd like**

> I would like to monitor the Radio Tx or Rx with GPIOs. In my past experience, there are some BLE suppliers can support this feature, such as Nordic, ST, Telink, NXP, etc.

**Describe alternatives you've considered**

> could you provide the corresponding APIs for GPIO configuration for Radio Tx or Rx monitoring, or disclose the radio Tx or Rx interrupt and users can implement the GPIO toggling there.

**Additional context**

> as heard from others online, Espressif may support this feature, but it is not open for users.

so the requirements above, can espressif open for users? 

thanks in advance.

**Comment by xiewenxiang** [comment]
@xiaolongba Sorry ，there is no such API for customer to use.

**Comment by xiaolongba** [comment]
All right, does espressif have similar ways to monitor the radio status?

**Comment by xiewenxiang** [comment]
There are ways to monitor it, but it's not open to the public now.

**Comment by xiaolongba** [comment]
@xiewenxiang 

> There are ways to monitor it, but it's not open to the public now.

got it. as you know, other competitors such as ST, Nordic, NXP, etc. can open for users for using. this feature is very useful for radio debugging especially the multi-connection cases.

so could you help me confirm if it can open for users now? if not, pls close this ticket,

thanks a lot.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, feel free to reopen.
