### ISSUE TITLE
A stable problem, when used PSRAM, and the uart buffer size larger than SPIRAM_MALLOC_ALWAYSINTERNAL. (IDFGH-6390)

### ISSUE THREAD

**Issue by Zmmfly** [espressif/esp-idf#8049]
## Environment
- Development Kit: ESP32-WROVER-E
- IDF version: v4.3.1

## Description
crash: `Guru Meditation Error: Core 0 panic'ed (Cache disabled but cached memory region accessed)`
The problem appear on cache disabled, and uart ESP_INTR_FLAG_IRAM flag set, and access PSRAM in interrupt at same time.

### When will the cache be closed?
Access flash via spi_flash api.

### Why the uart buffer size larger than SPIRAM_MALLOC_ALWAYSINTERNAL?
- The smallest SPIRAM_MALLOC_ALWAYSINTERNAL brings higher usage of PSRAM.
- The large uart buffer used communication in high baud rate for LTE.cat1 module.

### How it happened?
Set uart buffer size larger than SPIRAM_MALLOC_ALWAYSINTERNAL.
`xQueueGenericCreate` and `xRingbufferCreate` call `pvPortMalloc` and `malloc` and `calloc`, they are get memory in PSRAM.
Access to flash via spi flash api, and uart interrupt triggered in same time, and accessing to PSRAM memory in uart interrupt (`xQueueSendFromISR`, `xRingbufferSendFromISR`).
If access to flash and uart interrupt not in same time, it will not appear.
So, it had random possibility to appear, maybe in one day or just one minute after boot, and check difficult.

for queue:
https://github.com/espressif/esp-idf/blob/2e74914051d14ec2290fc751a8486fb51d73a31e/components/driver/uart.c#L1368-L1373
https://github.com/espressif/esp-idf/blob/2e74914051d14ec2290fc751a8486fb51d73a31e/components/driver/uart.c#L1385
https://github.com/espressif/esp-idf/blob/2e74914051d14ec2290fc751a8486fb51d73a31e/components/freertos/queue.c#L413
https://github.com/espressif/esp-idf/blob/2e74914051d14ec2290fc751a8486fb51d73a31e/components/driver/uart.c#L912
https://github.com/espressif/esp-idf/blob/2e74914051d14ec2290fc751a8486fb51d73a31e/components/driver/uart.c#L1033

for ringbuffer:
https://github.com/espressif/esp-idf/blob/2e74914051d14ec2290fc751a8486fb51d73a31e/components/driver/uart.c#L1396-L1398
https://github.com/espressif/esp-idf/blob/2e74914051d14ec2290fc751a8486fb51d73a31e/components/esp_ringbuf/ringbuf.c#L854-L864
https://github.com/espressif/esp-idf/blob/2e74914051d14ec2290fc751a8486fb51d73a31e/components/driver/uart.c#L777
https://github.com/espressif/esp-idf/blob/2e74914051d14ec2290fc751a8486fb51d73a31e/components/driver/uart.c#L893

### How to fix?
For temporary:
1:
Make duplicate for 'freertos', and 'driver' , and 'esp_ringbuf' from ESP IDF components directory.
Change the `malloc` and `calloc` and `pvPortMalloc` to `heap_caps_*` api, fixed memory into internal SRAM.
Put them into components in project directory.
2:
Enable SPIRAM_USE_CAPS_ALLOC, disable SPIRAM_USE_MALLOC.

For long:
Need break the API, add argument to select memory position

**Comment by the0ne** [comment]
Could be solved by allocating the freertos resources from internal memory.
No need to increase SPIRAM_MALLOC_ALWAYSINTERNAL.

```
diff --git a/components/freertos/include/freertos/portable.h b/components/freertos/include/freertos/portable.h
index ce189f31cd..5744c2db27 100644
--- a/components/freertos/include/freertos/portable.h
+++ b/components/freertos/include/freertos/portable.h
@@ -144,7 +144,8 @@ extern "C" {
  * non-FreeRTOS-specific code, and behave the same as
  * pvPortMalloc()/vPortFree().
  */
-#define pvPortMalloc malloc
+//#define pvPortMalloc malloc
+#define pvPortMalloc(size) heap_caps_malloc( size, MALLOC_CAP_DEFAULT | MALLOC_CAP_INTERNAL)
 #define vPortFree free
 #define xPortGetFreeHeapSize esp_get_free_heap_size
 #define xPortGetMinimumEverFreeHeapSize esp_get_minimum_free_heap_size
```

Hope this works for you, it solved the issue for me 😎
As I'm not using your exact version you may need to adapt the patch or simply change your file manually.
