### ISSUE TITLE
Download link for ESP-IDF v4.4 beta1 does not work (IDFGH-6403)

### ISSUE THREAD

**Issue by iamdavidcz** [espressif/esp-idf#8062]
https://dl.espressif.com/dl/esp-idf/releases/esp-idf-v4.4-beta1.zip
returns 404

**Comment by Alvin1Zhang** [comment]
@iamdavidcz Thanks for reporting, we have observed the issue and will fix soon.

**Comment by kumekay** [comment]
@iamdavidcz  Thanks for the issue, the link works now

**Comment by iamdavidcz** [comment]
@Alvin1Zhang I can confirm that the link works now, thank you
