### ISSUE TITLE
mcpwm_ll_timer_get_count_mode() return type is wrong (IDFGH-6407)

### ISSUE THREAD

**Issue by INOUETAICHI** [espressif/esp-idf#8066]
https://github.com/espressif/esp-idf/blob/23a03a3bdbaab1fe0ba427dcfcc82ef391cc06f4/components/hal/esp32/include/hal/mcpwm_ll.h#L352

I'm using "ESP32 Arduino 2.0.1 based on ESP-IDF 4.4"
I found this error.
```
mcpwm_ll.h: In function 'mcpwm_timer_count_mode_t mcpwm_ll_timer_get_count_mode(mcpwm_dev_t*, int)':
mcpwm_ll.h:352:50: error: invalid conversion from 'unsigned int' to 'mcpwm_timer_count_mode_t' [-fpermissive]
```

If you specify the type, the error will disappear.
`return (mcpwm_timer_count_mode_t) mcpwm-> timer [timer_id] .timer_cfg1.timer_mod;`

**Comment by suda-morris** [comment]
Thank you for reporting, we will fix it ASAP and backport to 4.4 release branch.
