### ISSUE TITLE
[TW#14029] JTAG docs not reference correct location/place for esp32.cfg

### ISSUE THREAD

**Issue by nkolban** [espressif/esp-idf#807]
On page 8 bullet 3 of the jtag_debugging_for_esp32_en.pdf, there is a statement that reads:

```
Copy esp32.cfg in esp-idf/docs to the openocd-esp32 directory;
```
Unfortunately, this files does **not** exist there.  It does seem to exist at:

`esp-idf/docs/api-guides`

I'm not sure if the doc is in error or the project path.

**Comment by igrr** [comment]
JTAG debugging document has been updated and moved to http://esp-idf.readthedocs.io/en/latest/api-guides/jtag-debugging/index.html.
