### ISSUE TITLE
Can't change BluFi device name (IDFGH-6411)

### ISSUE THREAD

**Issue by htomer5** [espressif/esp-idf#8071]
Hello ! 

**Is your feature request related to a problem? Please describe.**

We use BluFi  to config WiFi settings via Bluetooth, but I can't set custom device name because it is defined inside esp_idf. 

**Describe the solution you'd like**

I opened a pull request with my solution. see #8070.

Thanks.

**Comment by xiewenxiang** [comment]
@htomer5 

If we put the blufi name in menuconfig, does it  meet your needs?

**Comment by htomer5** [comment]
> 

Yes, it'll be perfect. I just need a way to change the device name in my project.

Thanks for all your help!

**Comment by asypost** [comment]
@xiewenxiang I think it's better to make **esp_bt_dev_set_device_name** work

**Comment by rtheil-growlink** [comment]
It would be much better if the value were not hard-coded as a config option. If a person has 5 of these devices they are trying to set up, how are they to know which one is which when the value is hard coded?

I agree with @asypost that setting the name with esp_bt_dev_set_device_name is a better way to make this happen. This way the app can match a serial number labeled on the device.

**Comment by asypost** [comment]
Is there any progress since six month passed away? @xiewenxiang

**Comment by rtheil-growlink** [comment]
Since Espressif has not improved this process, we established a way to get around it. We use the custom data callback of blufi. The mobile device sends a command and we respond to that command with the name/serial of the device. Then we're able to properly configure and display that name/serial to the end user.

esp_blufi_cb_event_t has ESP_BLUFI_EVENT_RECV_CUSTOM_DATA

**Comment by asypost** [comment]
> Since Espressif has not improved this process, we established a way to get around it. We use the custom data callback of blufi. The mobile device sends a command and we respond to that command with the name/serial of the device. Then we're able to properly configure and display that name/serial to the end user.
> 
> esp_blufi_cb_event_t has ESP_BLUFI_EVENT_RECV_CUSTOM_DATA

I found a way to change the device name of the blufi device when bluedroid is used.
You can change you device name via `esp_blufi_register_callbacks(&esp_blufi_callbacks);`
The code below shows how you should do:
`static esp_blufi_callbacks_t esp_blufi_callbacks = {
    .event_cb = esp_blufi_event_handle,
    .negotiate_data_handler = blufi_dh_negotiate_data_handler,
    .encrypt_func = blufi_aes_encrypt,
    .decrypt_func = blufi_aes_decrypt,
    .checksum_func = blufi_crc_checksum};
static void esp_blufi_event_handle(esp_blufi_cb_event_t event, esp_blufi_cb_param_t *param)
{
    /* actually, should post to blufi_task handle the procedure,
     * now, as a example, we do it more simply */
    switch (event)
    {
    case ESP_BLUFI_EVENT_INIT_FINISH:
        ESP_LOGI(TAG, "BLUFI init finish\n");

        esp_ble_gap_set_device_name(BLUFI_DEV_NAME);
        esp_ble_gap_config_adv_data(&blufi_adv_data);
        break;
    case ESP_BLUFI_EVENT_DEINIT_FINISH:
        ESP_LOGI(TAG, "BLUFI deinit finish\n");
        break;
    case ESP_BLUFI_EVENT_BLE_CONNECT:
        ESP_LOGI(TAG, "BLUFI ble connect\n");
        ble_is_connected = true;
        esp_blufi_adv_stop();
        blufi_security_init();
        break;
    case ESP_BLUFI_EVENT_BLE_DISCONNECT:
        ESP_LOGI(TAG, "BLUFI ble disconnect\n");
        ble_is_connected = false;
        blufi_security_deinit();
        **esp_ble_gap_set_device_name(BLUFI_DEV_NAME);
        esp_ble_gap_config_adv_data(&blufi_adv_data);**
        break;
    case ESP_BLUFI_EVENT_SET_WIFI_OPMODE:
        ESP_LOGI(TAG, "BLUFI Set WIFI opmode %d\n", param->wifi_mode.op_mode);
        ESP_ERROR_CHECK(esp_wifi_set_mode(param->wifi_mode.op_mode));
        break;
    case ESP_BLUFI_EVENT_REQ_CONNECT_TO_AP:
        ESP_LOGI(TAG, "BLUFI requset wifi connect to AP\n");
        /* there is no wifi callback when the device has already connected to this wifi
        so disconnect wifi before connection.
        */
        esp_wifi_disconnect();
        esp_wifi_connect();
        break;
    case ESP_BLUFI_EVENT_REQ_DISCONNECT_FROM_AP:
        ESP_LOGI(TAG, "BLUFI requset wifi disconnect from AP\n");
        esp_wifi_disconnect();
        break;
    case ESP_BLUFI_EVENT_REPORT_ERROR:
        ESP_LOGE(TAG, "BLUFI report error, error code %d\n", param->report_error.state);
        esp_blufi_send_error_info(param->report_error.state);
        break;
    case ESP_BLUFI_EVENT_GET_WIFI_STATUS:
    {
        wifi_mode_t mode;
        esp_blufi_extra_info_t info;

        esp_wifi_get_mode(&mode);

        if (gl_sta_connected)
        {
            memset(&info, 0, sizeof(esp_blufi_extra_info_t));
            memcpy(info.sta_bssid, gl_sta_bssid, 6);
            info.sta_bssid_set = true;
            info.sta_ssid = gl_sta_ssid;
            info.sta_ssid_len = gl_sta_ssid_len;
            esp_blufi_send_wifi_conn_report(mode, ESP_BLUFI_STA_CONN_SUCCESS, 0, &info);
        }
        else
        {
            esp_blufi_send_wifi_conn_report(mode, ESP_BLUFI_STA_CONN_FAIL, 0, NULL);
        }
        char buffer[512] = {0};
        vTaskGetRunTimeStats(buffer);
        ESP_LOGI("FreeRTOS", "runtime stats:\n%s", buffer);
        ESP_LOGI(TAG, "BLUFI get wifi status from AP\n");

        break;
    }
    case ESP_BLUFI_EVENT_RECV_SLAVE_DISCONNECT_BLE:
        ESP_LOGI(TAG, "blufi close a gatt connection");
        esp_blufi_disconnect();
        break;
    case ESP_BLUFI_EVENT_DEAUTHENTICATE_STA:
        /* TODO */
        break;
    case ESP_BLUFI_EVENT_RECV_STA_BSSID:
        memcpy(sta_config.sta.bssid, param->sta_bssid.bssid, 6);
        sta_config.sta.bssid_set = 1;
        esp_wifi_set_config(WIFI_IF_STA, &sta_config);
        ESP_LOGI(TAG, "Recv STA BSSID %s\n", sta_config.sta.ssid);
        break;
    case ESP_BLUFI_EVENT_RECV_STA_SSID:
        strncpy((char *)sta_config.sta.ssid, (char *)param->sta_ssid.ssid, param->sta_ssid.ssid_len);
        sta_config.sta.ssid[param->sta_ssid.ssid_len] = '\0';
        esp_wifi_set_config(WIFI_IF_STA, &sta_config);
        ESP_LOGI(TAG, "Recv STA SSID %s\n", sta_config.sta.ssid);
        break;
    case ESP_BLUFI_EVENT_RECV_STA_PASSWD:
        strncpy((char *)sta_config.sta.password, (char *)param->sta_passwd.passwd, param->sta_passwd.passwd_len);
        sta_config.sta.password[param->sta_passwd.passwd_len] = '\0';
        esp_wifi_set_config(WIFI_IF_STA, &sta_config);
        ESP_LOGI(TAG, "Recv STA PASSWORD %s\n", sta_config.sta.password);
        break;
    case ESP_BLUFI_EVENT_RECV_SOFTAP_SSID:
        strncpy((char *)ap_config.ap.ssid, (char *)param->softap_ssid.ssid, param->softap_ssid.ssid_len);
        ap_config.ap.ssid[param->softap_ssid.ssid_len] = '\0';
        ap_config.ap.ssid_len = param->softap_ssid.ssid_len;
        esp_wifi_set_config(WIFI_IF_AP, &ap_config);
        ESP_LOGI(TAG, "Recv SOFTAP SSID %s, ssid len %d\n", ap_config.ap.ssid, ap_config.ap.ssid_len);
        break;
    case ESP_BLUFI_EVENT_RECV_SOFTAP_PASSWD:
        strncpy((char *)ap_config.ap.password, (char *)param->softap_passwd.passwd, param->softap_passwd.passwd_len);
        ap_config.ap.password[param->softap_passwd.passwd_len] = '\0';
        esp_wifi_set_config(WIFI_IF_AP, &ap_config);
        ESP_LOGI(TAG, "Recv SOFTAP PASSWORD %s len = %d\n", ap_config.ap.password, param->softap_passwd.passwd_len);
        break;
    case ESP_BLUFI_EVENT_RECV_SOFTAP_MAX_CONN_NUM:
        if (param->softap_max_conn_num.max_conn_num > 4)
        {
            return;
        }
        ap_config.ap.max_connection = param->softap_max_conn_num.max_conn_num;
        esp_wifi_set_config(WIFI_IF_AP, &ap_config);
        ESP_LOGI(TAG, "Recv SOFTAP MAX CONN NUM %d\n", ap_config.ap.max_connection);
        break;
    case ESP_BLUFI_EVENT_RECV_SOFTAP_AUTH_MODE:
        if (param->softap_auth_mode.auth_mode >= WIFI_AUTH_MAX)
        {
            return;
        }
        ap_config.ap.authmode = param->softap_auth_mode.auth_mode;
        esp_wifi_set_config(WIFI_IF_AP, &ap_config);
        ESP_LOGI(TAG, "Recv SOFTAP AUTH MODE %d\n", ap_config.ap.authmode);
        break;
    case ESP_BLUFI_EVENT_RECV_SOFTAP_CHANNEL:
        if (param->softap_channel.channel > 13)
        {
            return;
        }
        ap_config.ap.channel = param->softap_channel.channel;
        esp_wifi_set_config(WIFI_IF_AP, &ap_config);
        ESP_LOGI(TAG, "Recv SOFTAP CHANNEL %d\n", ap_config.ap.channel);
        break;
    case ESP_BLUFI_EVENT_GET_WIFI_LIST:
    {
        wifi_scan_config_t scanConf = {
            .ssid = NULL,
            .bssid = NULL,
            .channel = 0,
            .show_hidden = false};
        esp_wifi_scan_start(&scanConf, true);
        break;
    }
    case ESP_BLUFI_EVENT_RECV_CUSTOM_DATA:
        ESP_LOGI(TAG, "Recv Custom Data %d\n", param->custom_data.data_len);
        esp_log_buffer_hex("Custom Data", param->custom_data.data, param->custom_data.data_len);
        break;
    case ESP_BLUFI_EVENT_RECV_USERNAME:
        /* Not handle currently */
        break;
    case ESP_BLUFI_EVENT_RECV_CA_CERT:
        /* Not handle currently */
        break;
    case ESP_BLUFI_EVENT_RECV_CLIENT_CERT:
        /* Not handle currently */
        break;
    case ESP_BLUFI_EVENT_RECV_SERVER_CERT:
        /* Not handle currently */
        break;
    case ESP_BLUFI_EVENT_RECV_CLIENT_PRIV_KEY:
        /* Not handle currently */
        break;
        ;
    case ESP_BLUFI_EVENT_RECV_SERVER_PRIV_KEY:
        /* Not handle currently */
        break;
    default:
        break;
    }
}
`
`esp_ble_gap_set_device_name(BLUFI_DEV_NAME); esp_ble_gap_config_adv_data(&blufi_adv_data);` is the key.

**Comment by jatibayuworo** [comment]
maybe the problem in setting apps use by phone.
apps name: EspBlufi
1. change name #define BLUFI_DEVICE_NAME   "BLUEFI_soBLUEz"
2. build then flash
3. open apps
4. taps icon beside title "EspBlufi" (like rectangle and arrow)
5. on "BLE device filtering" change it blank or same with the name of device name
6. restart apps

i did that and device name show in phone is same like i set in esp.

sorry if the problem mentions above not like i assume

**Comment by zhp0406** [comment]
I am conducting tests on my end, and the new name is displayed after manual refresh. If there are still issues, please contact me again.

**Comment by martmalo** [comment]
Cannot get it working by just changing `#define BLUFI_DEVICE_NAME "BLUEFI_soBLUEz"`
What do you mean by _manual refresh_ @zhp0406?

**Comment by zhp0406** [comment]
@jatibayuworo 
Have you tried refreshing it by swiping down in your phone?

**Comment by jatibayuworo** [comment]
i didn't found the problem. i only mention that it work in mine. and i tried to summarize what i've done.
