### ISSUE TITLE
Use libstdc++ in a linker.lf file with a scheme (IDFGH-6414)

### ISSUE THREAD

**Issue by philippe44** [espressif/esp-idf#8073]
It's a funny problem: I want to move the .bss section of libstdc++ to extram. My linker.lf works with *any* other library, but it fails with libstdc++ saying there is "illegal nesting". I suspect that the "+" symbol is the culprit but I've tried different escape options and none worked...

**Comment by philippe44** [comment]
It's here in fragments.py
```
class Fragment():
    __metaclass__ = abc.ABCMeta
    """
    Encapsulates a fragment as defined in the generator syntax. Sets values common to all fragment and performs processing
    such as checking the validity of the fragment name and getting the entry values.
    """

    IDENTIFIER = Word(alphas + '_', alphanums + '_')
    ENTITY = Word(alphanums + '.-_$**+**')

    @abc.abstractmethod
    def set_key_value(self, key, parse_results):
        pass

    @abc.abstractmethod
    def get_key_grammars(self):
        pass
```
Add the '+' in bold

**Comment by dobairoland** [comment]
Thank you @philippe44 for the report and suggestion for the fix. We will fix this soon in all affected branches. The fixes will be linked here.

**Comment by philippe44** [comment]
Thanks!

**Comment by philippe44** [comment]
oh ok, I thought you'd prefer me to close that :smile:

**Comment by igrr** [comment]
No worries! This issue should get closed automatically when the commit with the fix lands on Github.
