### ISSUE TITLE
http_server simple (IDFGH-6418)

### ISSUE THREAD

**Issue by Carol-001** [espressif/esp-idf#8077]
接收buffer大小设置的是4096，有时候接收到的少于4096时，很容易出现报 httpd_txrx: httpd_sock_err: error in recv : 11的错误，然后文件就传输失败了，http就死掉了，wifi连接还是正常的
![Uploading 企业微信截图_16393819592071.png…]()

**Comment by Alvin1Zhang** [comment]
@Carol-001 感谢反馈，您能按照 [issue template](https://github.com/espressif/esp-idf/issues/new?assignees=&labels=&template=bug_report.md&title=) 提供包括 elf, sdk configuration, backtrace, log outputs, commit ID, hardware 等更多信息么？这些信息将有助于我们 debug；另外，您链接中的截图没有显示出来，烦请修复，谢谢。

**Comment by Carol-001** [comment]
![企业微信截图_16393817586156](https://user-images.githubusercontent.com/78124220/145963016-7d40dda0-67af-439b-831b-7693f8a12d88.png)
![企业微信截图_16393819592071](https://user-images.githubusercontent.com/78124220/145963040-61355d61-81a3-475c-b32a-877204ad212e.png)

**Comment by ESP-YJM** [comment]
@Carol-001 请问这个也是你们提问的吗？https://github.com/espressif/esp-idf/issues/8079 是否可以按照这个 issue 来跟进？

**Comment by Carol-001** [comment]
YES

**Comment by ESP-YJM** [comment]
@Carol-001 麻烦关闭这个 issue，保留 https://github.com/espressif/esp-idf/issues/8079 来跟进。
