### ISSUE TITLE
esp32s2 idf4.3.1 hanging there  (IDFGH-6419)

### ISSUE THREAD

**Issue by achao1104** [espressif/esp-idf#8078]
Hello,

My project is in production phase now, as observed, sometimes, some devices might be hanging there, no execution and no rebooting and also no core dump, just hanging there.
1) could you please provide some clues? 
2) shall we use another independent watch dog chip? any recommendations?

Peter

**Comment by Alvin1Zhang** [comment]
@achao1104 Thanks for reporting. Would you please help provide more details as suggested in the [issue template](https://github.com/espressif/esp-idf/issues/new?assignees=&labels=&template=bug_report.md&title=)? Information like elf, sdk configuration, backtrace, log outputs, commit ID, hardware and etc. would help us debug further. Thanks.

**Comment by achao1104** [comment]
sorry, there is no more info since it is placed in a very high position.
I just wondering that if you have the similar issues (hanging).




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "espressif/esp-idf"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月14日(星期二) 上午10:50
***@***.***&gt;;
抄送:&nbsp;"Peter ***@***.******@***.***&gt;;
主题:&nbsp;Re: [espressif/esp-idf] esp32s2 idf4.3.1 hanging there  (IDFGH-6419) (Issue #8078)





 
@achao1104 Thanks for reporting. Would you please help provide more details as suggested in the issue template? Information like elf, sdk configuration, backtrace, log outputs, commit ID, hardware and etc. would help us debug further. Thanks.
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Alvin1Zhang** [comment]
Thanks for sharing the updates, would you please help share any details about use scenario, temperature, altitude etc? Thanks.

**Comment by Alvin1Zhang** [comment]
@achao1104 Thanks for reporting, will close due to short of feedback, feel free to reopen with more details, thanks.
