### ISSUE TITLE
i2s (IDFGH-6431)

### ISSUE THREAD

**Issue by Kingwulin** [espressif/esp-idf#8090]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

Please give as many details as you can. Include suggestions for useful APIs or interfaces if relevant.

**Additional context**

**Comment by Alvin1Zhang** [comment]
@Kingwulin Thanks for reporting. Would you please help provide more details as suggested in the [feature template](https://github.com/espressif/esp-idf/issues/new?assignees=&labels=Type%3A+Feature+Request&template=feature_request.md&title=)? Thanks.

**Comment by Alvin1Zhang** [comment]
@Kingwulin Thanks for reporting, will close due to short of feedback, feel free to reopen with more updates.
