### ISSUE TITLE
UART0 receive wrong data at light-sleep with external 32.768kHz XTAL (IDFGH-6438)

### ISSUE THREAD

**Issue by Rita858** [espressif/esp-idf#8098]
## Environment
- module used:  ESP32-WROOM-32D
- IDF version:           release/v4.3(e493a4c30e1b2f) 
- Build System:         [CMake|idf.py]
- Refer Demo:           BLE power save demo

## Problem
module works fine in BLE power save demo until I added uart events function on(referring to [uart_events.](https://github.com/espressif/esp-idf/tree/master/examples/peripherals/uart/uart_events))
it would receive wrong data unexpected.
it would be alleviated when calling "gpio_hold_en" to keep specific pin enable. But the problem still not be solved.

![lALPJxf-vLUeEgLNAibNBZg_1432_550](https://user-images.githubusercontent.com/53596746/146418718-598c8eea-b812-4120-a21c-597195575c0e.png)

So, I wonder if there are other solution can fix it?
Looking forward to your reply, thank you.

**Comment by esp-lis** [comment]
When the system is in light sleep, the uart will be suspended (the clock is gated). In the latest esp-idf version ([c1b3049](https://github.com/espressif/esp-idf/commit/c1b30491ddedd6f572dc6324eb322b639b3de029)), an example of the light sleep uart wakeup has been added. The path is as follows:
`$IDF_PATH/examples/system/light_sleep/`

**Comment by jack0c** [comment]
Another problem is, compared with 32.768 KHz XTAL, 115200 baud rate is too high. Suggest send valid data after wake up from light sleep(need more wake up bytes).

**Comment by jack0c** [comment]
@Rita858 any update?

**Comment by jack0c** [comment]
I will close this issue for no response. Feel free to reopen if necessary.
