### ISSUE TITLE
DAC (Wave_Gen) example won't compile for ESP32-S3 (IDFGH-6462)

### ISSUE THREAD

**Issue by eyewy** [espressif/esp-idf#8119]
Is there a DAC in S3? Is it planned to be supported? There is no dac.h for S3.

**Comment by suda-morris** [comment]
ESP32-S3 doesn't have a regular DAC as ESP32 does. There might be two ways to have a DAC functionality for ESP32-S3:
1. Using SPI interfaced external DAC chip
2. Try the sigma-delta + external LPF

**Comment by eyewy** [comment]
Ok, fair. Can I have independent Delta-Sigma running simultaneously on several GPIOs, like three of them?

**Comment by suda-morris** [comment]
@eyewy Yes, sure, ESP32-S3 has 8 sigma-delta channels
