### ISSUE TITLE
esp idf Ethernet basic Example with PHY8061 - Not Getting IP on DHCP  (IDFGH-6469)

### ISSUE THREAD

**Issue by nikunjbambhroliya** [espressif/esp-idf#8126]
Working on Esp32 Ethernet Basic Example and esp idf Configure with PHY80xx Module and PHY Attached With Default EMAC Default GPIO's of ESP32.

PHY Address Set to 0(Broadcast).
Not Getting IP on DHCP as well as Also Try to static ip but not getting ping.
getting Ethernet link up and ethernet link down status during attachment and detachment of lan cable on rj45 connector.

Please See Below Debug Log and suggest solution to start DHCP.
-----------------------
Debug log :
-----------------------
hcp_fine_tmr(): request timeout
dhcp_timeout()
dhcp_timeout(): restarting discovery
dhcp_discover()
dhcp_discover(): dhcp state is DISCOVER
dhcp_select: could not allocate DHCP request
transaction id xid(98f7137b)
dhcp_discover: making request
dhcp_discover: sendto(DISCOVER, IP_ADDR_BROADCAST, LWIP_IANA_PORT_DHCP_SERVER)
ip4_output_if: en1
IP header:
+-------------------------------+
| 4 | 5 |  0x00 |       336     | (v, hl, tos, len)
+-------------------------------+
|        7      |000|       0   | (id, flags, offset)
+-------------------------------+
|  255  |   17  |    0xba96     | (ttl, proto, chksum)
+-------------------------------+
|    0  |    0  |    0  |    0  | (src)
+-------------------------------+
|  255  |  255  |  255  |  255  | (dest)
+-------------------------------+
ip4_output_if: call netif->output()
dhcp_discover: deleting()ing
dhcp_discover: SELECTING
dhcp_discover(): set request timeout 15000 msecs
dhcp_coarse_tmr()
dhcp_coarse_tmr()
dhcp_coarse_tmr()
d
hcp_coarse_tmr()
dhcp_coarse_tmr()
dhcp_coarse_tmr()
dhcp_coarse_tmr()
dhcp_coarse_tmr()
ets Jul 29 2019 12:21:46

rst:0x1 (POWERON_RESET),boot:0x12 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:6760
load:0x40078000,len:14808
load:0x40080400,len:3792
entry 0x40080694
I (27) boot: ESP-IDF v5.0-dev-810-gb886dc6998-dirty 2nd stage bootloader
I (27) boot: compile time 12:31:28
I (29) boot: chip revision: 3
I (32) boot_comm: chip revision: 3, min. bootloader chip revision: 0
I (39) boot.esp32: SPI Speed      : 40MHz
I (44) boot.esp32: SPI Mode       : DIO
I (48) boot.esp32: SPI Flash Size : 2MB
I (53) boot: Enabling RNG early entropy source...
I (58) boot: Partition Table:
I (62) boot: ## Label            Usage          Type ST Offset   Length
I (69) boot:  0 nvs              WiFi data        01 02 00009000 00006000
I (77) boot:  1 phy_init         RF data          01 01 0000f000 00001000
I (84) boot:  2 factory          factory app      00 00 00010000 00100000
I (92) boot: End of partition table
I (96) boot_comm: chip revision: 3, min. application chip revision: 0
I (103) esp_image: segment 0: paddr=00010020 vaddr=3f400020 size=19588h (103816) map
I (149) esp_image: segment 1: paddr=000295b0 vaddr=3ffb0000 size=02b18h ( 11032) load
I (154) esp_image: segment 2: paddr=0002c0d0 vaddr=40080000 size=03f48h ( 16200) load
I (162) esp_image: segment 3: paddr=00030020 vaddr=400d0020 size=48988h (297352) map
I (271) esp_image: segment 4: paddr=000789b0 vaddr=40083f48 size=0e488h ( 58504) load
I (295) esp_image: segment 5: paddr=00086e40 vaddr=50000000 size=00010h (    16) load
I (304) boot: Loaded app from partition at offset 0x10000
I (304) boot: Disabling RNG early entropy source...
I (318) cpu_start: Pro cpu up.
D (318) efuse: In EFUSE_BLK0__DATA3_REG is used 1 bits starting with 15 bit
D (318) efuse: In EFUSE_BLK0__DATA5_REG is used 1 bits starting with 20 bit
D (324) efuse: In EFUSE_BLK0__DATA3_REG is used 3 bits starting with 9 bit
D (331) efuse: In EFUSE_BLK0__DATA3_REG is used 1 bits starting with 2 bit
I (338) cpu_start: Starting app cpu, entry point is 0x4008117c
I (0) cpu_start: App cpu up.
D (352) clk: RTC_SLOW_CLK calibration value: 3066880
I (365) cpu_start: Pro cpu start user code
I (365) cpu_start: cpu freq: 160000000 Hz
I (365) cpu_start: Application information:
I (370) cpu_start: Project name:     ethernet_basic
I (375) cpu_start: App version:      v5.0-dev-810-gb886dc6998-dirty
I (382) cpu_start: Compile time:     Dec 21 2021 13:03:27
I (388) cpu_start: ELF file SHA256:  888b9022d7b68e22...
I (394) cpu_start: ESP-IDF:          v5.0-dev-810-gb886dc6998-dirty
D (401) memory_layout: Checking 7 reserved memory ranges:
D (407) memory_layout: Reserved memory range 0x3ffae000 - 0x3ffae6e0
D (413) memory_layout: Reserved memory range 0x3ffb0000 - 0x3ffb4378
D (420) memory_layout: Reserved memory range 0x3ffe0000 - 0x3ffe0440
D (426) memory_layout: Reserved memory range 0x3ffe3f20 - 0x3ffe4350
D (432) memory_layout: Reserved memory range 0x40070000 - 0x40078000
D (439) memory_layout: Reserved memory range 0x40078000 - 0x40080000
D (445) memory_layout: Reserved memory range 0x40080000 - 0x400923d0
D (452) memory_layout: Building list of available memory regions:
D (458) memory_layout: Available memory region 0x3ffae6e0 - 0x3ffb0000
D (464) memory_layout: Available memory region 0x3ffb4378 - 0x3ffb8000
D (471) memory_layout: Available memory region 0x3ffb8000 - 0x3ffc0000
D (478) memory_layout: Available memory region 0x3ffc0000 - 0x3ffc2000
D (484) memory_layout: Available memory region 0x3ffc2000 - 0x3ffc4000
D (491) memory_layout: Available memory region 0x3ffc4000 - 0x3ffc6000
D (497) memory_layout: Available memory region 0x3ffc6000 - 0x3ffc8000
D (504) memory_layout: Available memory region 0x3ffc8000 - 0x3ffca000
D (511) memory_layout: Available memory region 0x3ffca000 - 0x3ffcc000
D (517) memory_layout: Available memory region 0x3ffcc000 - 0x3ffce000
D (524) memory_layout: Available memory region 0x3ffce000 - 0x3ffd0000
D (530) memory_layout: Available memory region 0x3ffd0000 - 0x3ffd2000
D (537) memory_layout: Available memory region 0x3ffd2000 - 0x3ffd4000
D (544) memory_layout: Available memory region 0x3ffd4000 - 0x3ffd6000
D (550) memory_layout: Available memory region 0x3ffd6000 - 0x3ffd8000
D (557) memory_layout: Available memory region 0x3ffd8000 - 0x3ffda000
D (563) memory_layout: Available memory region 0x3ffda000 - 0x3ffdc000
D (570) memory_layout: Available memory region 0x3ffdc000 - 0x3ffde000
D (577) memory_layout: Available memory region 0x3ffde000 - 0x3ffe0000
D (583) memory_layout: Available memory region 0x3ffe0440 - 0x3ffe3f20
D (590) memory_layout: Available memory region 0x3ffe4350 - 0x3ffe8000
D (596) memory_layout: Available memory region 0x3ffe8000 - 0x3fff0000
D (603) memory_layout: Available memory region 0x3fff0000 - 0x3fff8000
D (610) memory_layout: Available memory region 0x3fff8000 - 0x3fffc000
D (616) memory_layout: Available memory region 0x3fffc000 - 0x40000000
D (623) memory_layout: Available memory region 0x400923d0 - 0x40094000
D (629) memory_layout: Available memory region 0x40094000 - 0x40096000
D (636) memory_layout: Available memory region 0x40096000 - 0x40098000
D (643) memory_layout: Available memory region 0x40098000 - 0x4009a000
D (649) memory_layout: Available memory region 0x4009a000 - 0x4009c000
D (656) memory_layout: Available memory region 0x4009c000 - 0x4009e000
D (662) memory_layout: Available memory region 0x4009e000 - 0x400a0000
I (669) heap_init: Initializing. RAM available for dynamic allocation:
D (676) heap_init: New heap initialised at 0x3ffae6e0
I (681) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM
D (687) heap_init: New heap initialised at 0x3ffb4378
I (692) heap_init: At 3FFB4378 len 0002BC88 (175 KiB): DRAM
I (699) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM
I (705) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
D (712) heap_init: New heap initialised at 0x400923d0
I (717) heap_init: At 400923D0 len 0000DC30 (55 KiB): IRAM
D (724) intr_alloc: Connected src 46 to int 2 (cpu 0)
D (729) FLASH_HAL: extra_dummy: 1
D (731) spi_flash: trying chip: issi
D (735) spi_flash: trying chip: gd
D (739) spi_flash: trying chip: mxic
D (742) spi_flash: trying chip: winbond
D (746) spi_flash: trying chip: generic
I (750) spi_flash: detected chip: generic
I (755) spi_flash: flash io: dio
W (759) spi_flash: Detected size(16384k) larger than the size in the binary image header(2048k). Using the size in the binary image header.
D (772) cpu_start: calling init function: 0x4010785c
D (777) cpu_start: calling init function: 0x400e32d4
D (782) cpu_start: calling init function: 0x400dc19c
D (788) cpu_start: calling init function: 0x400d34b8
D (792) cpu_start: calling init function: 0x400d2294
D (797) intr_alloc: Connected src 17 to int 3 (cpu 0)
D (802) intr_alloc: Connected src 24 to int 9 (cpu 0)
I (807) cpu_start: Starting scheduler on PRO CPU.
D (0) intr_alloc: Connected src 25 to int 2 (cpu 1)
I (0) cpu_start: Starting scheduler on APP CPU.
D (823) heap_init: New heap initialised at 0x3ffe0440
D (833) heap_init: New heap initialised at 0x3ffe4350
D (843) intr_alloc: Connected src 16 to int 12 (cpu 0)
netif: netmask of interface  set to 255.0.0.0
netif: GW address of interface  set to 127.0.0.1
netif_set_ipaddr: netif address being changed
netif: added interface lo IP addr 127.0.0.1 netmask 255.0.0.0 gw 127.0.0.1
D (863) esp_netif_lwip: LwIP stack has been initialized
D (873) esp_netif_lwip: esp-netif has been successfully initialized
D (873) event: running task for loop 0x3ffaff58
D (883) event: created task for loop 0x3ffaff58
D (883) event: created event loop 0x3ffaff58
D (893) esp_netif_objects: esp_netif_add_to_list 0x3ffba588
D (893) esp_netif_objects: esp_netif_add_to_list netif added successfully (total netifs: 1)
D (903) intr_alloc: Connected src 38 to int 13 (cpu 0)
I (913) system_api: Base MAC address is not set
I (913) system_api: read default base MAC address from EFUSE
D (923) efuse: In EFUSE_BLK0__DATA2_REG is used 8 bits starting with 8 bit
D (923) efuse: In EFUSE_BLK0__DATA2_REG is used 8 bits starting with 0 bit
D (933) efuse: In EFUSE_BLK0__DATA1_REG is used 8 bits starting with 24 bit
D (943) efuse: In EFUSE_BLK0__DATA1_REG is used 8 bits starting with 16 bit
D (943) efuse: In EFUSE_BLK0__DATA1_REG is used 8 bits starting with 8 bit
D (953) efuse: In EFUSE_BLK0__DATA1_REG is used 8 bits starting with 0 bit
D (963) efuse: In EFUSE_BLK0__DATA2_REG is used 8 bits starting with 16 bit
I (993) ksz80xx: PHY AD1 = 22,PHY AD2 = 1573

I (993) ksz80xx: auto detected phy KSZ8061
D (993) esp_eth: new ethernet driver @0x3ffbdd28
I (993) esp_eth.netif.netif_glue: 7c:9e:bd:2a:3f:1b
I (1003) esp_eth.netif.netif_glue: ethernet attached to netif
dhcp_coarse_tmr()
dhcp_coarse_tmr()
D (3803) event: running post ETH_EVENT:0 with handler 0x400de300 and context 0x3ffaf4bc on loop 0x3ffaff58
D (3803) esp_eth.netif.netif_glue: eth_action_start: 0x3ffaf464, 0x3f40775c, 0, 0x3ffaf604, 0x3ffbdd28
D (3803) esp_netif_handlers: esp_netif action has started with netif0x3ffba588 from event_id=0
D (3813) esp_netif_lwip: check: remote, if=0x3ffba588 fn=0x400e2314

D (3823) esp_netif_lwip: esp_netif_start_api 0x3ffba588
D (3823) esp.emac: working in 100Mbps
netif: netmask of interface  set to 255.255.255.0
netif: GW address of interface  set to 192.168.1.1
netif_set_ipaddr: netif address being changed
D (3843) esp_netif_lwip: esp_netif_get_hostname esp_netif:0x3ffba588
netif: added interface en IP addr 192.168.1.201 netmask 255.255.255.0 gw 192.168.1.1
D (3863) esp_netif_lwip: check: local, if=0x3ffba588 fn=0x400e1998

D (3863) esp_netif_lwip: esp_netif_update_default_netif_lwip 0x3ffba588
D (3873) esp_netif_lwip: call api in lwip: ret=0x0, give sem
D (3873) event: running post ETH_EVENT:0 with handler 0x400d8f54 and context 0x3ffaf5c4 on loop 0x3ffaff58
dhcp_coarse_tmr()
I (3883) eth_example: Ethernet Started
D (3883) esp.emac: working in full duplex
D (3893) esp.emac: Flow control not enabled for the link
D (3903) event: running post ETH_EVENT:2 with handler 0x400de3d0 and context 0x3ffaf51c on loop 0x3ffaff58
D (3913) esp_eth.netif.netif_glue: eth_action_connected: 0x3ffaf464, 0x3f40775c, 2, 0x3ffaf604, 0x3ffbdd28
D (3923) esp_netif_handlers: esp_netif action connected with netif0x3ffba588 from event_id=2
D (3933) esp_netif_lwip: check: remote, if=0x3ffba588 fn=0x400e2ca8

D (3933) esp_netif_lwip: esp_netif_up_api esp_netif:0x3ffba588
D (3943) esp_netif_lwip: check: local, if=0x3ffba588 fn=0x400e1998

D (3953) esp_netif_lwip: esp_netif_update_default_netif_lwip 0x3ffba588
netif: setting default interface en
D (3963) esp_netif_lwip: call api in lwip: ret=0x0, give sem
D (3963) esp_netif_lwip: check: remote, if=0x3ffba588 fn=0x400e2a44

D (3973) esp_netif_lwip: esp_netif_dhcpc_start_api esp_netif:0x3ffba588
D (3983) esp_netif_lwip: esp_netif_start_ip_lost_timer esp_netif:0x3ffba588
D (3983) esp_netif_lwip: if0x3ffba588 start ip lost tmr: no need start because netif=0x3ffba5e8 interval=120 ip=0
D (3993) esp_netif_lwip: starting dhcp client
dhcp_start(netif=0x3ffba5e8) en1
dhcp_start(): restarting DHCP configuration
dhcp_start(): starting DHCP configuration
dhcp_discover()
dhcp_discover(): dhcp state is DISCOVER
dhcp_select: could not allocate DHCP request
transaction id xid(17556994)
dhcp_discover: making request
dhcp_discover: sendto(DISCOVER, IP_ADDR_BROADCAST, LWIP_IANA_PORT_DHCP_SERVER)
ip4_output_if: en1
IP header:
+-------------------------------+
| 4 | 5 |  0x00 |       336     | (v, hl, tos, len)
+-------------------------------+
|        0      |000|       0   | (id, flags, offset)
+-------------------------------+
|  255  |   17  |    0xba9d     | (ttl, proto, chksum)
+-------------------------------+
|    0  |    0  |    0  |    0  | (src)
+-------------------------------+
|  255  |  255  |  255  |  255  | (dest)
+-------------------------------+
ip4_output_if: call netif->output()
dhcp_discover: deleting()ing
dhcp_discover: SELECTING
dhcp_discover(): set request timeout 500 msecs
D (4083) esp_netif_lwip: call api in lwip: ret=0x0, give sem
D (4093) event: running post ETH_EVENT:2 with handler 0x400d8f54 and context 0x3ffaf5c4 on loop 0x3ffaff58
I (4103) eth_example: Ethernet Link Up
I (4103) eth_example: Ethernet HW Addr 7c:9e:bd:2a:3f:1b
dhcp_fine_tmr(): request timeout
dhcp_timeout()
dhcp_timeout(): restarting discovery
dhcp_discover()
dhcp_discover(): dhcp state is DISCOVER
dhcp_select: could not allocate DHCP request
transaction id xid(17556994)
dhcp_discover: making request
dhcp_discover: sendto(DISCOVER, IP_ADDR_BROADCAST, LWIP_IANA_PORT_DHCP_SERVER)
ip4_output_if: en1
IP header:
+-------------------------------+
| 4 | 5 |  0x00 |       336     | (v, hl, tos, len)
+-------------------------------+
|        1      |000|       0   | (id, flags, offset)
+-------------------------------+
|  255  |   17  |    0xba9c     | (ttl, proto, chksum)
+-------------------------------+
|    0  |    0  |    0  |    0  | (src)
+-------------------------------+
|  255  |  255  |  255  |  255  | (dest)
+-------------------------------+
ip4_output_if: call netif->output()
dhcp_discover: deleting()ing
dhcp_discover: SELECTING
dhcp_discover(): set request timeout 1000 msecs
dhcp_coarse_tmr()
dhcp_fine_tmr(): request timeout
dhcp_timeout()
dhcp_timeout(): restarting discovery
dhcp_discover()
dhcp_discover(): dhcp state is DISCOVER
dhcp_select: could not allocate DHCP request
transaction id xid(17556994)
dhcp_discover: making request
dhcp_discover: sendto(DISCOVER, IP_ADDR_BROADCAST, LWIP_IANA_PORT_DHCP_SERVER)
ip4_output_if: en1
IP header:
+-------------------------------+
| 4 | 5 |  0x00 |       336     | (v, hl, tos, len)
+-------------------------------+
|        2      |000|       0   | (id, flags, offset)
+-------------------------------+
|  255  |   17  |    0xba9b     | (ttl, proto, chksum)
+-------------------------------+
|    0  |    0  |    0  |    0  | (src)
+-------------------------------+
|  255  |  255  |  255  |  255  | (dest)
+-------------------------------+
ip4_output_if: call netif->output()
dhcp_discover: deleting()ing
dhcp_discover: SELECTING
dhcp_discover(): set request timeout 2000 msecs
dhcp_coarse_tmr()
dhcp_coarse_tmr()
dhcp_fine_tmr(): request timeout
dhcp_timeout()
dhcp_timeout(): restarting discovery
dhcp_discover()
dhcp_discover(): dhcp state is DISCOVER
dhcp_select: could not allocate DHCP request
transaction id xid(17556994)
dhcp_discover: making request
dhcp_discover: sendto(DISCOVER, IP_ADDR_BROADCAST, LWIP_IANA_PORT_DHCP_SERVER)
ip4_output_if: en1
IP header:
+-------------------------------+
| 4 | 5 |  0x00 |       336     | (v, hl, tos, len)
+-------------------------------+
|        3      |000|       0   | (id, flags, offset)
+-------------------------------+
|  255  |   17  |    0xba9a     | (ttl, proto, chksum)
+-------------------------------+
|    0  |    0  |    0  |    0  | (src)
+-------------------------------+
|  255  |  255  |  255  |  255  | (dest)
+-------------------------------+
ip4_output_if: call netif->output()
dhcp_discover: deleting()ing
dhcp_discover: SELECTING
dhcp_discover(): set request timeout 4000 msecs
dhcp_coarse_tmr()
dhcp_coarse_tmr()
dhcp_coarse_tmr()

**Comment by suda-morris** [comment]
Seems like the data panel is not working properly. Which GPIO is used by the RMII clock? This clock is important as it's used to synch MAC and PHY. https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/network/esp_eth.html#configure-mac-and-phy

**Comment by nikunjbambhroliya** [comment]
Thanks @suda-morris 

I have Go Through RMII Clock Setting but it seems configuration is properly done.

Please Find Attached screenshot of Example Configuration that Implemented using menuconfig
![image](https://user-images.githubusercontent.com/95736720/147439575-e643d572-2c36-42a2-8e54-a29869633d8a.png)

Please Find Attached Screenshot Ethernet Configuration inside Component Config
![image](https://user-images.githubusercontent.com/95736720/147439855-eff70231-cebd-49c3-8acf-863590d9a7bc.png)

In our Hardware Refclk pin connected with Esp32 GPIO0 with External Pullup.

please find attached kconfig file.
[kconfig file.txt](https://github.com/espressif/esp-idf/files/7778657/kconfig.file.txt)

**Comment by kostaond** [comment]
@nikunjbambhroliya, do see any traffic between your ESP32 board and your host when you capture it by Wireshark (ESP should send DHCP Discover at least)?

It seems you use custom HW, please double check that all RMII connections are correctly routed and connected (Data, CLK, etc.). For example, I was recently bringing up custom Ethernet board and it worked only in one direction. It turned out that one of RMII TX data path zero resistors felt out during manufacturing/shipping processes...

**Comment by nikunjbambhroliya** [comment]
Thanks @kostaond 
There is External Crystal Clock Issue. Now It's Working.

**Comment by kostaond** [comment]
@nikunjbambhroliya I'm happy to hear you found the issue and it's work!
