### ISSUE TITLE
About UART RS485 Echo Example using MAX485 (IDFGH-6475)

### ISSUE THREAD

**Issue by nopnop2002** [espressif/esp-idf#8132]
[Here](https://github.com/espressif/esp-idf/tree/master/examples/peripherals/uart/uart_echo_rs485) is an example of the UART RS485 Echo Example.

Readme has the following schematic:

```
         VCC ---------------+                               +--------------- VCC
                            |                               |
                    +-------x-------+               +-------x-------+
         RXD <------| RO            |               |             RO|-----> RXD
                    |              B|---------------|B              |
         TXD ------>| DI  MAX485    |    \  /       |    MAX485   DI|<----- TXD
ESP dev kit         |               |   RS-485 side |               |  SERIAL ADAPTER SIDE
         RTS --+--->| DE            |    /  \       |             DE|---+
               |    |              A|---------------|A              |   |
               +----| /RE           |               |            /RE|---+-- RTS
                    +-------x-------+               +-------x-------+
                            |                               |
                           ---                             ---
```

MAX485 is a single 5V power supply.
MAX485 data sheet has the following description:

```
Receiver Output Voltage max=Vcc+0.5[v]
```

Therefore, I think that 5V is input to the RXD of ESP32.

ESP32 does not support 5V input.

MAX3485 is a single 3.3V power supply.
Shouldn't we use MAX3845 instead of MAX485?

**Comment by alisitsyn** [comment]
@nopnop2002,

Thank you for your issue. The MAX485 is able to work normally either at VCC=3.3V or at 5V and it is provided as an example of a very commonly used line driver. I agree, the standard operating voltage of MAX485 as per its datasheet is 5V. With 3.3V it can work normally but the differential output voltage may be lower which will affect the operation with longer cables. So, it is better to change the recommended driver in the example to MAX3845 or ADM483, (MAX483) as appears in the documentation.
I can confirm this issue as minor and this misleading information has to be corrected in the example. Let me know if you have any other comments.
