### ISSUE TITLE
mesh和lcd屏驱动同时使用 (IDFGH-6482)

### ISSUE THREAD

**Issue by JustQY** [espressif/esp-idf#8137]
项目是一个4寸lcd显示屏，采用s2模块，lcd单独运行没问题，mesh部分是原先32e模块使用的代码，直接移植到s2 屏幕产品上。
移植后关闭lcd部分可正常运行，激活lcd部分后出现如下日志，请问这个如何解决

![image](https://user-images.githubusercontent.com/9473678/147179313-3dbd3e8c-c6f4-4f3e-bcfc-4b3d8a327c00.png)

**Comment by shenjun7** [comment]
log显示是在调esp_mesh_stop(), 后续需要调esp_mesh_init()->esp_mesh_set_config()->esp_mesh_start() restart mesh 再进行通信.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, feel free to reopen.
