### ISSUE TITLE
else misplaced compile error when BT_MULTI_CONNECTION_ENBALE != FALSE in smp_act.c (IDFGH-6486)

### ISSUE THREAD

**Issue by norventa** [espressif/esp-idf#8140]
## Problem Description
When BT_MULTI_CONNECTION_ENBALE != FALSE and SMP_SLAVE_CON_PARAMS_UPD_ENABLE == TRUE the following code produces an else misplaced compile error.
A possible solution is shown below.

Also could correct spelling error for BT_MULTI_CONNECTION_ENBALE ?

## Environment
- framework-espidf 3.40301.0 (4.3.1)

### Steps to reproduce
Set BT_MULTI_CONNECTION_ENBALE to TRUE and SMP_SLAVE_CON_PARAMS_UPD_ENABLE to TRUE in menu config and compile any BLE example.

### Code to reproduce this issue
```cpp
void smp_fast_conn_param(tSMP_CB *p_cb, tSMP_INT_DATA *p_data)
{
#if (BT_MULTI_CONNECTION_ENBALE == FALSE)
    if(p_cb->role == BTM_ROLE_MASTER) {
        L2CA_EnableUpdateBleConnParams(p_cb->pairing_bda, FALSE);
    }
#endif
#if (SMP_SLAVE_CON_PARAMS_UPD_ENABLE == TRUE)
    else {
        tBTM_SEC_DEV_REC    *p_rec = btm_find_dev (p_cb->pairing_bda);
        if(p_rec && p_rec->ble.skip_update_conn_param) {
            //do nothing
            return;
        }
        /* Disable L2CAP connection parameter updates while bonding since
        some peripherals are not able to revert to fast connection parameters
        during the start of service discovery. Connection paramter updates
        get enabled again once service discovery completes. */
        #if (BT_MULTI_CONNECTION_ENBALE == FALSE)
        L2CA_EnableUpdateBleConnParams(p_cb->pairing_bda, FALSE);
        #endif
    }
#endif
}
`

Possible fix shown below:
`
void smp_fast_conn_param(tSMP_CB *p_cb, tSMP_INT_DATA *p_data)
{
#if (BT_MULTI_CONNECTION_ENBALE == FALSE)
    if(p_cb->role == BTM_ROLE_MASTER) {
        L2CA_EnableUpdateBleConnParams(p_cb->pairing_bda, FALSE);
    }
#if (SMP_SLAVE_CON_PARAMS_UPD_ENABLE == TRUE)
    else {
        tBTM_SEC_DEV_REC    *p_rec = btm_find_dev (p_cb->pairing_bda);
        if(p_rec && p_rec->ble.skip_update_conn_param) {
            //do nothing
            return;
        }
        /* Disable L2CAP connection parameter updates while bonding since
        some peripherals are not able to revert to fast connection parameters
        during the start of service discovery. Connection paramter updates
        get enabled again once service discovery completes. */
        L2CA_EnableUpdateBleConnParams(p_cb->pairing_bda, FALSE);
    }
#endif
#endif
}
`

**Comment by egi1965** [comment]
Encountered the same problem today. I recommend a file search throughout all source code for "Enbale" because such error appears in multiple files. If one uses idf.py menuconfig that seems to write "enable" but the sources contain several times "enbale" what results in compile errors.

**Comment by norventa** [comment]
When I change BT_MULTI_CONNECTION_ENBALE using menuconfig everything compiles and sdkconfig.h contains "#define CONFIG_BT_MULTI_CONNECTION_ENBALE 1". For me, it is just a spelling mistake that has propogated throughout the various bluetooth libraries.

My issue is with the "else" in the first code block above. By refactoring that code, as shown in the second code block, everything works fine.

**Comment by zikalino** [comment]
@norventa would you like to create a pull request or should we do it?

**Comment by norventa** [comment]
I really don't know git at all so could you do it please.

**Comment by xiewenxiang** [comment]
@norventa 

Thank you very much for your report issue and we will fix it as soon as possible.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, fix on master is available https://github.com/espressif/esp-idf/commit/6cb6087dd0170cd534d8ad68ee2f8740a33368f9, we are back porting the fix to release/4.4 and release/4.3, will update once they are available, thanks.

**Comment by AxelLin** [comment]
v4.4: 2fe53759c968e2467d39c6ae24f370719c1b9ce0
v4.3: abacbb1d12a91bf6b9afdb9a358701d82dce78f6
This can be closed.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting and sharing the updates, feel free to reopen if the issue still happens, thanks.
