### ISSUE TITLE
ESP32C3 advertsing issue with iPhone bluetooth scanning. (IDFGH-6493)

### ISSUE THREAD

**Issue by jigneshpatel47** [espressif/esp-idf#8147]
Hi,

We are using ESP32C3 with ESP-IDF v4.3.2. 
I have built the BLE server example using [gatt server example](https://github.com/espressif/esp-idf/tree/master/examples/bluetooth/bluedroid/ble/gatt_server) for esp32c3.

My issue is that ESP32C3 is not showing in the Bluetooth scanning list on iPhone. 
I am using iPhone12 with software version 15.0.

The same thing, It works in android. I can able show esp32c3 in the android mobile Bluetooth scanning list.

What may be the issue ESP32c3 and iPhone are facing for advertising?

Thank you in advance.
Jignesh Patel

**Comment by xiewenxiang** [comment]
I have retested the problem you mentioned on iPhone 12, and the name can be displayed normally.

**Comment by xiewenxiang** [comment]
![phone](https://user-images.githubusercontent.com/26754847/147642959-b5478465-4c18-4867-b253-825285301a29.jpg)
![capture](https://user-images.githubusercontent.com/26754847/147642971-a22f77a7-d220-4620-8b06-9e8fdd0ad512.png)

**Comment by jigneshpatel47** [comment]
Thank you @xiewenxiang  for your reply,

I can able to see ESP32C3 in the NRF BLE Application, But I can not discover in Bluetooth scanning that comes under Setting -> Bluetooth in iPhone.

What is the method is used by Bluetooth native and NRF scanning mechanisms?

Best Regards,
Jignesh Patel

**Comment by xiewenxiang** [comment]
From the perspective of Bluetooth, the device name has been included in the broadcast, but why not in the system Settings of the mobile phone? You may need to consult Apple.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to short of feedback, feel free to reopen with more updates.

**Comment by skv6631** [comment]
Got any resolution for this issue?? @jigneshpatel47  @xiewenxiang
