### ISSUE TITLE
ESP_NETIF_TCPIP_ADAPTER_COMPATIBLE_LAYER cause build issue with time (IDFGH-6502)

### ISSUE THREAD

**Issue by chegewara** [espressif/esp-idf#8155]
Why disabling `ESP_NETIF_TCPIP_ADAPTER_COMPATIBLE_LAYER` in menuconfig is causing problems with standard time functions?
`error: 'tm' does not name a type; did you mean 'tms'?`
`strftime(buffer, 80, "%d-%m-%Y %H:%M:%S GMT", timeinfo);`

With option enabled all works fine.

Thanks

**Comment by AxelLin** [comment]
Which esp-idf version?

**Comment by chegewara** [comment]
master branch, sorry

**Comment by ESP-YJM** [comment]
@chegewara Which example you used?

**Comment by chegewara** [comment]
Sorry, it is not espressif example, it is from my library test code. It is based on sntp example.

**Comment by chegewara** [comment]
I checked SNTP example now and its working. Looks like with this config enabled some headers are auto-magically included and with disabled i have to add:
```
#include <time.h>
#include <sys/time.h>
```

Sorry for confusion
