### ISSUE TITLE
Linker script parser does not work on '+' sign (IDFGH-6513)

### ISSUE THREAD

**Issue by feelfreelinux** [espressif/esp-idf#8165]
## Environment

- IDF version (run ``git describe --tags`` to find it):
    // v4.3.2-114-g7467c68a17
- Build System:         [CMake]
- Operating System:     [macOS]
- Using an IDE?: [No]
- Power Supply:         [USB]

## Problem Description

The linker script parser does not parse the `+` characters properly.

### Expected Behavior

The linker script parses LD_SYMBOLS properly for names with `+` character in them (like `libstd++` for example).

### Actual Behavior

Linker fails, error message "illegal nesting at line x" during build through cmake / idf.py build.

### Steps to reproduce

1. Create a linker script and make a mapping for a library without '+' in the name, for example one that moves .bss to .extram_bss for the `libc.a` library.
2. Try to build it. Linking works fine.
3. Change the library in step 1. to one containing '+'. `libstd++` for example.
4. Linking fails.

### Code to reproduce this issue

linker.lf
```
[mapping:cpp]
archive: libstd++.a
entries:
    * (extram_bss)
```

include it in CMakeLists.
`LDFRAGMENTS "linker.lf"`

## Working fix

After a while of debugging, I have found out that the issue is caused by invalid `pyparsing` `Word` definition in https://github.com/espressif/esp-idf/blob/release/v4.3/tools/ldgen/fragments.py#L197 . By adding the `+` symbol in that line, I can make the linker script parse `libstd++` just fine. The following URL was provided for version 4.3 of esp-idf, but I have also noticed it on versions 4.4 and the newest master (as of https://github.com/espressif/esp-idf/commit/5624dffc52271389376352974ba5911963ee207b). I currently use a forked version of esp-idf in my project because of this issue, but I can provide a pull request with this fix.

**Comment by igrr** [comment]
Hi @feelfreelinux, this was recently reported in https://github.com/espressif/esp-idf/issues/8073 and fixed on master (https://github.com/espressif/esp-idf/commit/52fb8624ccf02c4aae04a9ca0ff74a30e918b24d), release/v4.4 (fbdb781fcba149b5bf271a4aef1a7c437747253a), release/v4.3 (f976bb0ef8914ef46b354b3a4a078b51e8a5acf0).

This fix will be included into the next releases on the respective branches - v5.0, v4.4-rc1, v4.3.3.
