### ISSUE TITLE
esp_https_ota_begin returns ESP_OK when http server returns 404 (IDFGH-6548)

### ISSUE THREAD

**Issue by bschick** [espressif/esp-idf#8195]
## Environment

- Module or chip used:  ESP32-C3-MINI-1-N4
- IDF version v4.4-beta1-275-g214d62b9ad
- Build System:        idf.py
- Operating System:    macO
- Using an IDE?: No
- Power Supply:    USB

## Problem Description

When calling esp_https_ota_begin with a URL that has a valid http server but an invalid resource (path), esp_https_ota_begin return ESP_OK despite the call actually failing and cleaning up. This happens because esp_http_client_perform return ESP_OK, but the HTTP status code is not 200. Simple fix is to set err to ESP_FAIL when the error is from a status code 

### Expected Behavior

esp_https_ota_begin does not return ESP_OK upon failure

### Steps to reproduce

1. Use a URL that contains a valid HTTP server but an invalid path so that the HTTP server returns a 404 status
2. Check return code of esp_https_ota_begin

## Potential Patch

```
diff --git a/components/esp_https_ota/src/esp_https_ota.c b/components/esp_https_ota/src/esp_https_ota.c
index ddbf73a565..45626b0276 100644
--- a/components/esp_https_ota/src/esp_https_ota.c
+++ b/components/esp_https_ota/src/esp_https_ota.c
@@ -216,6 +216,9 @@ esp_err_t esp_https_ota_begin(esp_https_ota_config_t *ota_config, esp_https_ota_
         err = esp_http_client_perform(https_ota_handle->http_client);
         if (err != ESP_OK || esp_http_client_get_status_code(https_ota_handle->http_client) != HttpStatus_Ok) {
             ESP_LOGE(TAG, "Failed to get image length");
+            if (err == ESP_OK) {
+               err = ESP_FAIL;
+            }
             goto http_cleanup;
         }
         https_ota_handle->image_length = esp_http_client_get_content_length(https_ota_handle->http_client);
```

**Comment by ESP-YJM** [comment]
@bschick Thanks for pointing out the bug. We will fix it.
