### ISSUE TITLE
ADF环境安装完成后编译出现问题 (IDFGH-6582)

### ISSUE THREAD

**Issue by CYCHEN97** [espressif/esp-idf#8226]
@ESP-YJM![图片](https://user-images.githubusercontent.com/61934856/149056885-00e1ae59-c4b8-4de7-b036-48fd55842fa0.png)
ADF安装好后进行编译自动语音识别demo时，提示python版本问题，还没安装ADF之前linux中只有python3，安装好ADF后多了几个python版本
![图片](https://user-images.githubusercontent.com/61934856/149057182-2fd014f2-298e-4521-b1b9-61fcd5891306.png)

**Comment by CYCHEN97** [comment]
![图片](https://user-images.githubusercontent.com/61934856/149058986-6c97c3a9-296f-4ab4-8d85-a21e72aeb307.png)
ADF安装成功可以在VSCODE显示example
![图片](https://user-images.githubusercontent.com/61934856/149058894-2d70b668-bd9c-48dd-84a5-a1229714a07b.png)
但是点这个配置后提示错误

**Comment by CYCHEN97** [comment]
@ESP-YJM
麻烦帮忙看一下

**Comment by ESP-YJM** [comment]
@CYCHEN97 非常抱歉，我对 ADF 和环境配置不是很熟悉，建议你去 https://github.com/espressif/esp-adf/issues 这个下面提问。我们会有负责该工程的同事帮你解答问题。

**Comment by CYCHEN97** [comment]
@ESP-YJM
好的，谢谢
