### ISSUE TITLE
Confused about BT GATT indicate judgement (IDFGH-6586)

### ISSUE THREAD

**Issue by briliant-ben** [espressif/esp-idf#8230]
## Environment

None

## Problem Description

Sorry to bother, I am learning ESP BT code, but I dont have a platform for now, but the code here really makes me confused:

https://github.com/espressif/esp-idf/blob/dae8bdb60bed819094137a52c2f86a1e49195a34/components/bt/host/bluedroid/bta/gatt/bta_gatts_act.c#L670-L682

https://github.com/espressif/esp-idf/blob/dae8bdb60bed819094137a52c2f86a1e49195a34/components/bt/host/bluedroid/bta/gatt/bta_gatts_act.c#L694-L695

as we can see in function **bta_gatts_indicate_handle**,  I think, here it use **need_confirm** to represent **GATT Indicate** which needs a "Confirm" as a response. 

The first section code fits this logic very well, but the second section is not. In second section, it will enter this **if logic** only when **GATT Indicate** result is not **GATT_SUCCESS **, because **!p_msg->api_indicate.need_confirm** is false.
 
However,  all **GATT Indicate** need a "Confirm"? am I wrong?

## Other items if possible

None

**Comment by zhp0406** [comment]
@briliant-ben 
Your understanding is incorrect. The code here is intended to report events to the application layer. For example, when the status is not GATT_SUCCESS, it's necessary to report the reasons to the application layer.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to short of feedback, feel free to reopen with more updates.
