### ISSUE TITLE
Test cases for Digital Signature (DS) peripheral to not match output of configure_ds.py for  ESP32C3 (IDFGH-6601)

### ISSUE THREAD

**Issue by bschick** [espressif/esp-idf#8243]
## Environment

- Module or chip used:  ESP32-C3-MINI-1-N4
- IDF version v4.4-beta1-275-g214d62b9ad
- Build System:        idf.py
- Operating System:    macO
- Using an IDE?: No
- Power Supply:    USB

## Problem Description

While troubleshooting DS on an ESP32C3 I used this file
https://github.com/espressif/esp-idf/blob/d5f58ab13551cd883e8d8478ba367b6e4543ffec/components/esp_hw_support/test/gen_digital_signature_tests.py to generate a test case from data used in configure_ds.py (I did that by temporarily hard coding a message, hmac, and IV in gen_digital_signature_tests.py). But the results still did not match the signature and c value produced by configure_ds.py

The problem was that gen_digital_signature_tests.py hard codes the padding/max_len values for md_in and p as 4096, which shou;d be 3072 on the ESP32C3.

### Expected Behavior

While using hard code 4096 is valid, it would be nice if gen_digital_signature_tests.py produced results that match those of configure_ds.py (and therefore the ESP32C3 when configure_ps.py data is used on the device). This can be done by using the padding approach used in configure_ds.py https://github.com/espressif/esp-idf/blob/d5f58ab13551cd883e8d8478ba367b6e4543ffec/examples/protocols/mqtt/ssl_ds/configure_ds.py  If I edit gen_digital_signature_tests.py  to lookup the max length from a dict like `supported_key_size = {'esp32s2':[1024, 2048, 3072, 4096], 'esp32c3':[1024, 2048, 3072]}`, the results match the output of configure_ds.py

Fixing this would have saved me time during troubleshooting

**Comment by 0xjakob** [comment]
@bschick Sorry for the inconvenience! In fact, we (me, actually) adopted the tests from S2 and modified the header file itself, instead of python script. We never fixed the python script afterwards. We'll do that now for this issue.
