### ISSUE TITLE
blufi设置蓝牙名称无效 (IDFGH-6603)

### ISSUE THREAD

**Issue by CYCHEN97** [espressif/esp-idf#8245]
@ESP-YJM
esp32s3使用blufi例程，在开始广播前设置了蓝牙名称，但是没有生效，手机APP端还是搜索到BLUFI_DEVICE这个名称
![图片](https://user-images.githubusercontent.com/61934856/149703608-28358938-2bf8-49a7-8265-0969ed143cea.png)
![图片](https://user-images.githubusercontent.com/61934856/149703640-790e3d60-8ffc-454c-9cf6-1a186392ad7b.png)

**Comment by CYCHEN97** [comment]
@ESP-YJM
大佬，帮忙看一下

**Comment by CYCHEN97** [comment]
@0xjakob
@esp-lis
@ESP-YJM
@negativekelvin
@alisitsyn
请问使用BLUFI时怎么设置自定义的蓝牙名称？

**Comment by CYCHEN97** [comment]
解决了，修改了esp_blufi.h中的宏定义就可以了
![图片](https://user-images.githubusercontent.com/61934856/149730297-fa9f29a0-99ae-4a9e-967d-2db3fea89e2a.png)

**Comment by fanxiangqing** [comment]
我修改了为什么还是不生效啊
