### ISSUE TITLE
Unused tag variables breaking compilation (IDFGH-6608)

### ISSUE THREAD

**Issue by KaeLL** [espressif/esp-idf#8250]
- IDF version: release/v4.4

### Actual Behavior
```
/esp-idf/components/esp_adc_cal/esp_adc_cal_esp32.c:86:19: error: 'LOG_TAG' defined but not used [-Werror=unused-const-variable=]
 const static char LOG_TAG[] = "ADC_CALI";
                   ^~~~~~~
cc1: some warnings being treated as errors
```

### Steps to reproduce

hello-world with `COMPILER_OPTIMIZATION_CHECKS_SILENT` set

**Comment by suda-morris** [comment]
Good catch, we also noticed this issue recently and already have a fix for that. Will sync the fix to master and 4.4 soon.
