### ISSUE TITLE
Upgrade the ASIO component to the latest version  (IDFGH-6613)

### ISSUE THREAD

**Issue by wuyuanyi135** [espressif/esp-idf#8255]
**Is your feature request related to a problem? Please describe.**

The embedded asio component's version is 1.14.1, which misses some features like handler cancellation.

**Describe the solution you'd like**

Upgrade the asio component to the latest release 1.20.0

**Describe alternatives you've considered**

**Additional context**

**Comment by euripedesrocha** [comment]
Asio is now available from the [component manager](https://components.espressif.com/components/espressif/asio) and updated to 1.28.0
