### ISSUE TITLE
How to judge whether SPI works in full duplex or half duplex mode? (IDFGH-6617)

### ISSUE THREAD

**Issue by LanFly** [espressif/esp-idf#8259]
ESP-IDF: v4.3.1

I can't find any description of it in https://docs.espressif.com/projects/esp-idf/zh_CN/v4.3.1/esp32/api-reference/peripherals/spi_master.html#

**Comment by KaeLL** [comment]
Did you pass `SPI_DEVICE_HALFDUPLEX` to `spi_device_interface_config_t::flags`?

**Comment by LanFly** [comment]
> Did you pass `SPI_DEVICE_HALFDUPLEX` to `spi_device_interface_config_t::flags`?

Not pass. I didn't find it on the document. Now i found it on the `spi_master.h`, thanks you!
