### ISSUE TITLE
靠近连接开启AP模式怎么进行http通信？ (IDFGH-6621)

### ISSUE THREAD

**Issue by CYCHEN97** [espressif/esp-idf#8264]
使用靠近连接例程blufi，在手机APP中设置开启AP模式，电脑连接esp32s3的wifi，APP中点击状态查看状态，一直显示SoftAP current connection：0，然后没法进行域名访问http通信；使用STA模式的时候就可以进行域名访问http通信
![Screenshot_2022-01-20-11-07-28-232_com espressif espblufi(1)](https://user-images.githubusercontent.com/61934856/150265707-482843c9-e347-43be-9373-72ec3153b980.jpg)

**Comment by CYCHEN97** [comment]
@0xjakob
@esp-lis
@ESP-YJM
@negativekelvin
@alisitsyn

**Comment by mhdong** [comment]
hi @CYCHEN97  在wifi init之前添加esp_netif_create_default_wifi_ap();
这样softap可为连接的sta分配ip地址，即可进行http通信。对于SoftAP current connection一直显示为0的原因在于esp_blufi_send_wifi_conn_report（）函数没有将softap连接个数更新。

**Comment by CYCHEN97** [comment]
@mhdong 
有没有PC端基于Qt的蓝牙配网上位机？

**Comment by mhdong** [comment]
hi @CYCHEN97  暂时没有支持基于Qt的蓝牙配网上位机。
