### ISSUE TITLE
Implement ftruncate function (IDFGH-6641)

### ISSUE THREAD

**Issue by igrr** [espressif/esp-idf#8279]
**Is your feature request related to a problem? Please describe.**

`truncate` function was requested in https://github.com/espressif/esp-idf/issues/1980 and implemented in https://github.com/espressif/esp-idf/commit/c77f84e788819a5070a9ea63b9a73fb0aea6df15, however the related `ftruncate` function was not implemented.

**Describe the solution you'd like**

* Implement `ftruncate` function in VFS
* Implement `ftruncate` in FAT VFS

**Describe alternatives you've considered**

Instead of having both `truncate` and `ftruncate` functions in VFS interface, VFS layer could supply a `truncate` implementation and only require `ftruncate` to be implemented by the VFS driver. The VFS layer could implement `truncate` using driver's `open`, `ftruncate`, `close` methods. This, however, would be a breaking change since we would have to replace `truncate` with `ftruncate` in the VFS interface.

**Additional context**

Requested in a comment to the closed issue: https://github.com/espressif/esp-idf/issues/1980#issuecomment-990092159
Issues that would be solved by implementing this:

* https://github.com/joltwallet/esp_littlefs/issues/57
* https://github.com/kuba--/zip/issues/231

**Comment by Rajssss** [comment]
@igrr any update on this?

**Comment by MabezDev** [comment]
FYI the Rust standard library relies on `ftruncate` being available, first reported here: https://github.com/esp-rs/rust/issues/100.
