### ISSUE TITLE
ESP-HIDH: free is called on uninitialized data (IDFGH-6643)

### ISSUE THREAD

**Issue by jgeudens** [espressif/esp-idf#8280]
## Environment
- Custom HW
- ESP32-WROVER
- Module or chip used: ESP32-WROVER-I
- IDF version (run ``git describe --tags`` to find it): v4.3
- Build System: CMake
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it): xtensa-esp32-elf-gcc (crosstool-NG esp-2020r3) 8.4.0
- Operating System: Windows
- (Windows only) environment type: MSYS2 mingw32

## Problem Description

https://github.com/espressif/esp-idf/blob/faf0f61cdba67fa5f7e680f2f5b0966c8d69ce9a/components/esp_hid/src/ble_hidh.c#L110

I ran into codepaths where the device, was freed by calling: esp_hidh_dev_resources_free(), without report_maps ever being initialized.

https://github.com/espressif/esp-idf/blob/release/v4.3/components/esp_hid/src/esp_hidh.c#L372

This function will free() report_maps[x].data which may be uninitialized

Solution: initialize report_maps to 0. free(NULL) is allowed.

**Comment by xiongweichao** [comment]
Hi @jgeudens 

I don't quite understand what you mean. Will a crash happen?

Thanks

**Comment by jgeudens** [comment]
Issue seems to be resolved with https://github.com/espressif/esp-idf/commit/453ecbe9f249c9578b37f58f2820b888551f1452
