### ISSUE TITLE
I couldn't find the file name is "esp_rom_tjpgd.h", Pls help me  (IDFGH-6646)

### ISSUE THREAD

**Issue by Alvinwang64** [espressif/esp-idf#8283]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

Please give as many details as you can. Include suggestions for useful APIs or interfaces if relevant.

**Additional context**

**Comment by AxelLin** [comment]
https://github.com/espressif/esp-idf/blob/master/components/esp_rom/include/esp_rom_tjpgd.h

**Comment by Alvinwang64** [comment]
I found it!! Thanks!



王兴文
联系电话：18600890991


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "espressif/esp-idf"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月25日(星期二) 中午11:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [espressif/esp-idf] I couldn't find the file name is "esp_rom_tjpgd.h", Pls help me  (IDFGH-6646) (Issue #8283)





 
https://github.com/espressif/esp-idf/blob/master/components/esp_rom/include/esp_rom_tjpgd.h
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Alvin1Zhang** [comment]
@AxelLin Many thanks to the notes. @Alvinwang64 Thanks for reporting, feel free to reopen.
