### ISSUE TITLE
setsockopt() with flag SO_REUSEADDR returns "Protocol not available"

### ISSUE THREAD

**Issue by valioiv** [espressif/esp-idf#830]
I've tried to use SO_REUSEADDR on a UDP socket and returns ENOPROTOOPT - "Protocol not available" error:

```c
int reuse = 1;
ret = setsockopt(sock, SOL_SOCKET, SO_REUSEADDR, &reuse, sizeof(reuse));
if (ret < 0) {
	ESP_LOGI(TAG, "setsockopt err");
	perror("");
	goto exit;
}
```

Any feedback on this?

**Comment by igrr** [comment]
Could you please check if you have enabled `CONFIG_LWIP_SO_REUSE` in menuconfig (Component config > LwIP > Enable SO_REUSEADDR option)?

**Comment by valioiv** [comment]
I tried enabled that from menuconfig and now it works! Thanks for bringing my attention to that part and sorry for disturbance!
