### ISSUE TITLE
Can I use ESP32S2 as Server and Client at the same time? (IDFGH-6692)

### ISSUE THREAD

**Issue by subhash-coder** [espressif/esp-idf#8322]
Hello,
       my project is a camera web server, ESP32S2 is connected to an OV5640 camera sensor, here ESP32S2 works both as server and client, in server mode, one can access the server and get still image and stream video and in client mode, ESP32S2 sends data to a node server.
So my question is this possible for ESP32S2 to work in server and client mode simultaneously?

**Comment by me-no-dev** [comment]
There is nothing to prevent you to run client and server at the same time. If you are talking about sending the same image to some other server and streaming it to a browser at the same time, you will need think of how you will manage the frames and also consider that the time it's needed to service both requests will be more.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, feel free to reopen.
