### ISSUE TITLE
I2S wrong bclk for internal DAC (IDFGH-6697)

### ISSUE THREAD

**Issue by s-hadinger** [espressif/esp-idf#8326]
## Environment

- Development Kit:      [M5StickC]
- Module or chip used:  [ESP32-PICO-D4]
- IDF version [4.4]
- Build System:         [Pio]
- Compiler version toolchain-xtensa-esp32 8.4.0+2021r2-patch2
- Operating System:     [macOS]
- Using an IDE?: [PlatformIO]
- Power Supply:         [USB]

## Problem Description

When using I2S with internal DAC, 2 channels, 16000 frames/sec, the sound emitted is a short swaks and DMA buffers are emptied far too fast compared to regular I2S audio with external chip.

Problem is largely described in https://github.com/espressif/arduino-esp32/issues/5938

### Expected Behavior

The original PCM sound is the following and lasts over 660ms:

![151602386-8ca194e2-ea6a-466b-8a92-b9760f4d027e](https://user-images.githubusercontent.com/49731213/151852816-ced01491-8066-44df-9b1d-8770202435ea.jpg)

### Actual Behavior

Recording the output with a scope shows a correct waveform but played 11x faster than normal speed.
![151602460-e7997b68-d8c1-40fb-9442-6978bf8e68c0](https://user-images.githubusercontent.com/49731213/151852929-fb7d2c93-80f2-450b-a7c1-50df72e8282b.jpg)

I did a detour on `i2s_hal_tx_clock_config()` to check what clock values were calculated, and force-injected some different clock values until the sound was good again.

With the previous setting: 16KHz, 2 channels, internal DAC. IDF calculates the following clock:
`sclk=160000000 mclk=128000 bclk=64000 mclk_div=1250 bclk_div=2`

Although the number seem correct, `mclk_div` hardware is only 8 bits, so 1250 is overflowing.

Injecting my own calculated value, I made it work at correct speed with:
`sclk=160000000 mclk=1024000 bclk=32000 mclk_div=156 bclk_div=32`

Having a combined `mclk_div=156 bclk_div=32` achieves a divider of ~5000 over sclk.

I suppose that an easy patch would be to set `bclk_div=32` instead of `bclk_div=2` and it should allow for all audio frequencies.

## Other items if possible

- [ ] sdkconfig file (attach the sdkconfig file from your project folder)
- [ ] elf file in the ``build`` folder (**note this may contain all the code details and symbols of your project.**)
- [ ] coredump (This provides stacks of tasks.)

**Comment by Alvin1Zhang** [comment]
Thanks for reporting and sharing the updates, fix is available at https://github.com/espressif/esp-idf/commit/19f4eca4b94300c4943bd9b1043856644435d09c, feel free to reopen.
