### ISSUE TITLE
Problem with "esp-idf/main/CMakeFiles/__idf_main.dir/report.cpp.obj" (IDFGH-6702)

### ISSUE THREAD

**Issue by farhanjaa** [espressif/esp-idf#8331]
I'm trying to run the esp32 opencv test program via this github link https://github.com/joachimBurket/esp32-opencv, but I found the problem, that is
$ idf.py -p /dev/ttyUSB0 flash
Executing action: flash
Running ninja in directory /home/farhan/Desktop/esp32-opencv/esp32/examples/esp_opencv_tests/build
Executing "ninja flash"...
[1/11] Performing build step for 'bootloader'
[1/1] cd /home/farhan/Desktop/esp32-opencv/esp32/examples/esp_opencv_tests/build/bootloader/esp-idf/esptool_py && /home/farhan/.espressif/python_env/idf5.0_py3.8_env/bin/python /home/farhan/esp/esp-idf/components/partition_table/check_sizes.py --offset 0x8000 bootloader 0x1000 /home/farhan/Desktop/esp32-opencv/esp32/examples/esp_opencv_tests/build/bootloader/bootloader.bin
Bootloader binary size 0x6360 bytes. 0xca0 bytes (11%) free.
[2/9] Building CXX object esp-idf/main/CMakeFiles/__idf_main.dir/report.cpp.obj
FAILED: esp-idf/main/CMakeFiles/__idf_main.dir/report.cpp.obj 
/home/farhan/.espressif/tools/xtensa-esp32-elf/esp-2021r2-8.4.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-g++  -DMBEDTLS_CONFIG_FILE=\"mbedtls/esp_config.h\" -DUNITY_INCLUDE_CONFIG_H -DWITH_POSIX -Iconfig -I../main -I../main/opencv -I/home/farhan/esp/esp-idf/components/newlib/platform_include -I/home/farhan/esp/esp-idf/components/freertos/FreeRTOS-Kernel/include -I/home/farhan/esp/esp-idf/components/freertos/esp_additions/include/freertos -I/home/farhan/esp/esp-idf/components/freertos/FreeRTOS-Kernel/portable/xtensa/include -I/home/farhan/esp/esp-idf/components/freertos/esp_additions/include -I/home/farhan/esp/esp-idf/components/esp_hw_support/include -I/home/farhan/esp/esp-idf/components/esp_hw_support/include/soc -I/home/farhan/esp/esp-idf/components/esp_hw_support/include/soc/esp32 -I/home/farhan/esp/esp-idf/components/esp_hw_support/port/esp32/. -I/home/farhan/esp/esp-idf/components/heap/include -I/home/farhan/esp/esp-idf/components/log/include -I/home/farhan/esp/esp-idf/components/lwip/include/apps -I/home/farhan/esp/esp-idf/components/lwip/include/apps/sntp -I/home/farhan/esp/esp-idf/components/lwip/lwip/src/include -I/home/farhan/esp/esp-idf/components/lwip/port/esp32/include -I/home/farhan/esp/esp-idf/components/lwip/port/esp32/include/arch -I/home/farhan/esp/esp-idf/components/soc/include -I/home/farhan/esp/esp-idf/components/soc/esp32/. -I/home/farhan/esp/esp-idf/components/soc/esp32/include -I/home/farhan/esp/esp-idf/components/hal/esp32/include -I/home/farhan/esp/esp-idf/components/hal/include -I/home/farhan/esp/esp-idf/components/hal/platform_port/include -I/home/farhan/esp/esp-idf/components/esp_rom/include -I/home/farhan/esp/esp-idf/components/esp_rom/include/esp32 -I/home/farhan/esp/esp-idf/components/esp_rom/esp32 -I/home/farhan/esp/esp-idf/components/esp_common/include -I/home/farhan/esp/esp-idf/components/esp_system/include -I/home/farhan/esp/esp-idf/components/esp_system/port/soc -I/home/farhan/esp/esp-idf/components/esp_system/port/include/private -I/home/farhan/esp/esp-idf/components/xtensa/include -I/home/farhan/esp/esp-idf/components/xtensa/esp32/include -I/home/farhan/esp/esp-idf/components/driver/include -I/home/farhan/esp/esp-idf/components/driver/esp32/include -I/home/farhan/esp/esp-idf/components/driver/deprecated -I/home/farhan/esp/esp-idf/components/esp_pm/include -I/home/farhan/esp/esp-idf/components/esp_ringbuf/include -I/home/farhan/esp/esp-idf/components/efuse/include -I/home/farhan/esp/esp-idf/components/efuse/esp32/include -I/home/farhan/esp/esp-idf/components/vfs/include -I/home/farhan/esp/esp-idf/components/esp_wifi/include -I/home/farhan/esp/esp-idf/components/esp_event/include -I/home/farhan/esp/esp-idf/components/esp_netif/include -I/home/farhan/esp/esp-idf/components/esp_eth/include -I/home/farhan/esp/esp-idf/components/tcpip_adapter/include -I/home/farhan/esp/esp-idf/components/esp_phy/include -I/home/farhan/esp/esp-idf/components/esp_phy/esp32/include -I/home/farhan/esp/esp-idf/components/esp_timer/include -I/home/farhan/esp/esp-idf/components/mbedtls/port/include -I/home/farhan/esp/esp-idf/components/mbedtls/mbedtls/include -I/home/farhan/esp/esp-idf/components/mbedtls/esp_crt_bundle/include -I/home/farhan/esp/esp-idf/components/app_update/include -I/home/farhan/esp/esp-idf/components/spi_flash/include -I/home/farhan/esp/esp-idf/components/bootloader_support/include -I/home/farhan/esp/esp-idf/components/bootloader_support/bootloader_flash/include -I/home/farhan/esp/esp-idf/components/nvs_flash/include -I/home/farhan/esp/esp-idf/components/pthread/include -I/home/farhan/esp/esp-idf/components/wpa_supplicant/include -I/home/farhan/esp/esp-idf/components/wpa_supplicant/port/include -I/home/farhan/esp/esp-idf/components/wpa_supplicant/esp_supplicant/include -I/home/farhan/esp/esp-idf/components/app_trace/include -I/home/farhan/esp/esp-idf/components/asio/asio/asio/include -I/home/farhan/esp/esp-idf/components/asio/port/include -I/home/farhan/esp/esp-idf/components/bt/common/osi/include -I/home/farhan/esp/esp-idf/components/bt/include/esp32/include -I/home/farhan/esp/esp-idf/components/bt/common/api/include/api -I/home/farhan/esp/esp-idf/components/bt/common/btc/profile/esp/blufi/include -I/home/farhan/esp/esp-idf/components/bt/common/btc/profile/esp/include -I/home/farhan/esp/esp-idf/components/bt/host/bluedroid/api/include/api -I/home/farhan/esp/esp-idf/components/unity/include -I/home/farhan/esp/esp-idf/components/unity/unity/src -I/home/farhan/esp/esp-idf/components/cmock/CMock/src -I/home/farhan/esp/esp-idf/components/coap/port/include -I/home/farhan/esp/esp-idf/components/coap/libcoap/include -I/home/farhan/esp/esp-idf/components/console -I/home/farhan/esp/esp-idf/components/http_parser -I/home/farhan/esp/esp-idf/components/esp-tls -I/home/farhan/esp/esp-idf/components/esp-tls/esp-tls-crypto -I/home/farhan/esp/esp-idf/components/esp_adc_cal/include -I/home/farhan/esp/esp-idf/components/esp_gdbstub/include -I/home/farhan/esp/esp-idf/components/esp_gdbstub/xtensa -I/home/farhan/esp/esp-idf/components/esp_gdbstub/esp32 -I/home/farhan/esp/esp-idf/components/esp_hid/include -I/home/farhan/esp/esp-idf/components/tcp_transport/include -I/home/farhan/esp/esp-idf/components/esp_http_client/include -I/home/farhan/esp/esp-idf/components/esp_http_server/include -I/home/farhan/esp/esp-idf/components/esp_https_ota/include -I/home/farhan/esp/esp-idf/components/esp_lcd/include -I/home/farhan/esp/esp-idf/components/esp_lcd/interface -I/home/farhan/esp/esp-idf/components/protobuf-c/protobuf-c -I/home/farhan/esp/esp-idf/components/protocomm/include/common -I/home/farhan/esp/esp-idf/components/protocomm/include/security -I/home/farhan/esp/esp-idf/components/protocomm/include/transports -I/home/farhan/esp/esp-idf/components/mdns/include -I/home/farhan/esp/esp-idf/components/esp_local_ctrl/include -I/home/farhan/esp/esp-idf/components/sdmmc/include -I/home/farhan/esp/esp-idf/components/esp_serial_slave_link/include -I/home/farhan/esp/esp-idf/components/esp_websocket_client/include -I/home/farhan/esp/esp-idf/components/espcoredump/include -I/home/farhan/esp/esp-idf/components/espcoredump/include/port/xtensa -I/home/farhan/esp/esp-idf/components/wear_levelling/include -I/home/farhan/esp/esp-idf/components/fatfs/diskio -I/home/farhan/esp/esp-idf/components/fatfs/vfs -I/home/farhan/esp/esp-idf/components/fatfs/src -I/home/farhan/esp/esp-idf/components/freemodbus/common/include -I/home/farhan/esp/esp-idf/components/idf_test/include -I/home/farhan/esp/esp-idf/components/idf_test/include/esp32 -I/home/farhan/esp/esp-idf/components/ieee802154/include -I/home/farhan/esp/esp-idf/components/json/cJSON -I/home/farhan/esp/esp-idf/components/mqtt/esp-mqtt/include -I/home/farhan/esp/esp-idf/components/openssl/include -I/home/farhan/esp/esp-idf/components/perfmon/include -I/home/farhan/esp/esp-idf/components/spiffs/include -I/home/farhan/esp/esp-idf/components/ulp/ulp_common/include -I/home/farhan/esp/esp-idf/components/ulp/ulp_common/include/esp32 -I/home/farhan/esp/esp-idf/components/wifi_provisioning/include -mlongcalls -Wno-frame-address    -ffunction-sections -fdata-sections -Wall -Werror=all -Wno-error=unused-function -Wno-error=unused-variable -Wno-error=deprecated-declarations -Wextra -Wno-unused-parameter -Wno-sign-compare -ggdb -Og -fmacro-prefix-map=/home/farhan/Desktop/esp32-opencv/esp32/examples/esp_opencv_tests=. -fmacro-prefix-map=/home/farhan/esp/esp-idf=/IDF -fstrict-volatile-bitfields -Wno-error=unused-but-set-variable -fno-jump-tables -fno-tree-switch-conversion -std=gnu++11 -fno-exceptions -fno-rtti -D_GNU_SOURCE -DIDF_VER=\"v5.0-dev-1426-ge899edd793-dirty\" -DESP_PLATFORM -D_POSIX_READER_WRITER_LOCKS -MD -MT esp-idf/main/CMakeFiles/__idf_main.dir/report.cpp.obj -MF esp-idf/main/CMakeFiles/__idf_main.dir/report.cpp.obj.d -o esp-idf/main/CMakeFiles/__idf_main.dir/report.cpp.obj -c ../main/report.cpp
../main/report.cpp: In member function 'void TestCase::executeOn(const imagesList&)':
../main/report.cpp:23:32: error: exception handling disabled, use -fexceptions to enable
         } catch(cv::Exception& e) {
                                ^
../main/report.cpp:24:119: error: 'e' was not declared in this scope
             cout << "Exception while trying to execute function " << name << " on image " << get<0>(img) << " :\n" << e.msg;
                                                                                                                       ^
ninja: build stopped: subcommand failed.
ninja failed with exit code 1
Is there an error when I build the program? or other internal error. 
When I search for report.cpp.obb it is not found in the file "/home/farhan/Desktop/esp32-opencv/esp32/examples/esp_opencv_tests/build/esp-idf/main/CMakeFiles/__idf_main.dir"

Thanks for the help I'm very new to this.

**Comment by ESP-Marius** [comment]
Hi,

This would typically happen if `CONFIG_COMPILER_CXX_EXCEPTIONS` is not enabled, but I see that in the sdkconfig file in the example this should already have been set.

Did you by any chance change anything there?

**Comment by Alvin1Zhang** [comment]
@farhanjaa Thanks for reporting, would you please help share if any updates for the issue? Thanks.

**Comment by ESP-Marius** [comment]
Marking this as resolved, feel free to reopen the issue if the proposed solution did not solve your issue.
