### ISSUE TITLE
Boot from Test Firmware Custom GPIO Level (IDFGH-6703)

### ISSUE THREAD

**Issue by azeater** [espressif/esp-idf#8332]
Currently you must hold the configured GPIO pin low in order to boot into the TEST partition. It would be good if it were similar to the factory reset and allowed to choose the reset level to be either high or low.

**Comment by KonstantinKondrashov** [comment]
Hi @azeater!
Thanks for the suggestion. I have added these changes, they will be soon on the master in v5.0.
