### ISSUE TITLE
ESP32-S2 RMT driver bug (IDFGH-6725)

### ISSUE THREAD

**Issue by naffej** [espressif/esp-idf#8354]
## Environment

- Module or chip used:  ESP32-S2
- IDF version: from v4.3

## Problem Description
https://github.com/espressif/esp-idf/blob/3441dd1e9832a99dbd823e7dc73700169815772f/components/soc/esp32s2/include/soc/soc_caps.h#L206
The file above has a wrong define. According to esp32-s2 technical reference manual, esp32-s2 doesn't have RMT RX wrap mode aka Ping-Pong mode. So this define triggers false behavior when receiving with RMT. If I manually unset the define, receiving works as intended.

And

According to the formers, the following function in  https://github.com/espressif/esp-idf/blob/3441dd1e9832a99dbd823e7dc73700169815772f/components/hal/esp32s2/include/hal/rmt_ll.h#L469

```c
static inline void rmt_ll_rx_enable_pingpong(rmt_dev_t *dev, uint32_t channel, bool enable)
{
    dev->conf_ch[channel].conf1.chk_rx_carrier_en = enable;
}
```
has no sense in esp32-s2. In fact it enables a complete wrong register value.

**Comment by suda-morris** [comment]
@naffej  Thank you very much for your valuable report! We will fix it ASAP.
