### ISSUE TITLE
Windows Flash Download Tool don't support erase flash and other..

### ISSUE THREAD

**Issue by ESP32DE** [espressif/esp-idf#836]
missings things in 

![grafik](https://user-images.githubusercontent.com/16070445/28562653-67f7369c-7123-11e7-9507-7a2488212bd5.png)

- erase flash ( very helpfull future in multiDownload too ) 
- backup flash

**Comment by igrr** [comment]
Thanks for the report, i have forwarded it to the relevant team members. Closing this as the flash download tools are not part of ESP-IDF.
