### ISSUE TITLE
Windows Flash Download Tool chkBox "DoNotChgBin" no effect if FW File is combined 

### ISSUE THREAD

**Issue by ESP32DE** [espressif/esp-idf#837]
in 

![grafik](https://user-images.githubusercontent.com/16070445/28562839-1b984ee8-7124-11e7-995a-2ba5b80aea79.png)

we can't use ( have no effect ) 

![grafik](https://user-images.githubusercontent.com/16070445/28562874-40673478-7124-11e7-8948-8bc5ecaf00c7.png)

if the firmware is a "combine file" to flash at 0x0
and the firmware is example for 8MB Flash QIO
and the HW is 4MB DIO
the FW File is not change if we unselect the Box "DoNotChgBin"

reqeust
- support "DoNotChgBin" checkbox for combine files too

**Comment by igrr** [comment]
Thanks for the report, i have forwarded it to the relevant team members. Closing this as the flash download tools are not part of ESP-IDF.
