### ISSUE TITLE
wss_example error in handshake - 0x7780 (IDFGH-6746)

### ISSUE THREAD

**Issue by diazmanuel** [espressif/esp-idf#8375]
## Environment

- Development Kit:      [ESP32-DevKitC]
- Kit version (DevKitC): [v4]
- Module or chip used:  [ESP32-WROOM-32D]
- IDF version: [4.3.2]
- Build System: [CMake]
- Compiler version:8.4.0+2021r2-patch2 
- Operating System:     [Linux]
- Using an IDE?: PlataformIo visual studio code
- Power Supply:         [USB]

## Problem Description

Unable to connect to local web socket secure server based on example idf (protocols/https_server/wss_simple), Error in handshake  - 0x7780

I try using diferents wss clients, the only one that i made it "wotk" is pieSocket webSocket Tester but the handshake fails the first try and later they connect without retrying, also i try with my own wss client in android kotlin (checked with a public wss server) and they didnt work too (see plots in the debug Logs section).
Ones the pieSocket webSocket Tester connect with my esp32 local server wss works fine, but idk why the first attend fails and why they only works with this public client.

The proyect iam working also contain mqtt client (already working without wss server parallel), the logs and this issue are made dissabling te mqtt client but the sdkconfig still the same as showed in sdkconfig section.

the self signed certificate are made as suggested in the example wss_simple and also approve a security exception in google crome

if its needed i also can config MBEDTLS_DEBUG and link the plot debug (its really huge)

## Settup
conection via Ethernet as explained in ethernet/basic with LAN8720 using GPIO17 to provide 50Mhz Clock (already chequed)

Using mDNS as explained in protocols/mdns (already chequed)

### Code to reproduce this issue
gist link:

https://gist.github.com/diazmanuel/deea8f1cde30a06ea1fc97cd0145c92f

the start and stop wss server is called on ip_event_handler and eth_event_handler (eventID =ETHERNET_EVENT_DISCONNECTED) respectively.

## Debug Logs

plot using public client wss https://www.piesocket.com/websocket-tester

␛[0;32mI (3083) esp_https_server: Server listening on port 443␛[0m
␛[0;32mI (3086) WSS: Registering URI handlers␛[0m
␛[0;32mI (24697) esp_https_server: performing session handshake␛[0m
␛[0;31mE (26276) esp-tls-mbedtls: mbedtls_ssl_handshake returned -30592␛[0m
␛[0;31mE (26277) esp_https_server: esp_tls_create_server_session failed␛[0m
␛[0;32mI (26280) WSS: Client disconnected 57␛[0m
␛[0;33mW (26283) httpd: httpd_accept_conn: session creation failed␛[0m
␛[0;31mE (26283) wss_keep_alive: Cannot remove client fd:57␛[0m
␛[0;33mW (26291) httpd: httpd_server: error accepting new connection␛[0m
␛[0;32mI (26303) esp_https_server: performing session handshake␛[0m
␛[0;32mI (28515) WSS: New client connected 57␛[0m

plot using own client android kotlin:

␛[0;32mI (3083) esp_https_server: Server listening on port 443␛[0m
␛[0;32mI (3086) WSS: Registering URI handlers␛[0m
␛[0;32mI (24697) esp_https_server: performing session handshake␛[0m
␛[0;31mE (26276) esp-tls-mbedtls: mbedtls_ssl_handshake returned -30592␛[0m
␛[0;31mE (26277) esp_https_server: esp_tls_create_server_session failed␛[0m
␛[0;32mI (26280) WSS: Client disconnected 57␛[0m
␛[0;33mW (26283) httpd: httpd_accept_conn: session creation failed␛[0m
␛[0;31mE (26283) wss_keep_alive: Cannot remove client fd:57␛[0m
␛[0;33mW (26291) httpd: httpd_server: error accepting new connection␛[0m

## sdkconfig.defaults

#----------------ETH---------------#
CONFIG_ESP_NETIF_TCPIP_ADAPTER_COMPATIBLE_LAYER=n
CONFIG_ETH_RMII_CLK_OUTPUT=y
CONFIG_ETH_RMII_CLK_OUT_GPIO=17

#--------------END ETH-------------#

#----------------MQTT--------------#
CONFIG_MQTT_USE_CUSTOM_CONFIG=y
CONFIG_MQTT_TCP_DEFAULT_PORT=1883
CONFIG_MQTT_SSL_DEFAULT_PORT=8883
CONFIG_MQTT_WS_DEFAULT_PORT=80
CONFIG_MQTT_WSS_DEFAULT_PORT=443
CONFIG_MQTT_BUFFER_SIZE=16384
CONFIG_MQTT_TASK_STACK_SIZE=6144
CONFIG_MBEDTLS_ASYMMETRIC_CONTENT_LEN=y
CONFIG_MBEDTLS_SSL_IN_CONTENT_LEN=16384
CONFIG_MBEDTLS_SSL_OUT_CONTENT_LEN=4096
CONFIG_ESP_NETIF_TCPIP_ADAPTER_COMPATIBLE_LAYER=n

#--------------END MQTT------------#

#-------------FREERTOS-------------#
CONFIG_FREERTOS_HZ=1000

#---------END FREERTOS-------------#

#----------------mDNS--------------#
CONFIG_MDNS_RESOLVE_TEST_SERVICES=y
CONFIG_MDNS_ADD_MAC_TO_HOSTNAME=y
CONFIG_MDNS_PUBLISH_DELEGATE_HOST=y
CONFIG_LWIP_DNS_SUPPORT_MDNS_QUERIES=y
#------------END mDNS--------------#

#----------------HTTPS--------------#
CONFIG_HTTPD_WS_SUPPORT=y
CONFIG_ESP_HTTPS_SERVER_ENABLE=y
CONFIG_HTTPD_MAX_REQ_HDR_LEN=2048
CONFIG_HTTPD_MAX_URI_LEN=512
CONFIG_HTTPD_ERR_RESP_NO_DELAY=y
CONFIG_HTTPD_PURGE_BUF_LEN=32
#-----------END HTTPS--------------#

#CONFIG_MBEDTLS_DEBUG=y

**Comment by ESP-YJM** [comment]
@diazmanuel It seems your server CA cert not a trusted self-signed cert. So some clients may not allow this unsafe connection and send alert message to server.

**Comment by diazmanuel** [comment]
> @diazmanuel It seems your server CA cert not a trusted self-signed cert. So some clients may not allow this unsafe connection and send alert message to server.

Thanks you, it was that, so i change the config of the client to allow not trusted certs and it works.
