### ISSUE TITLE
vfs.c "LOG_LOCAL_LEVEL" redefined (IDFGH-6750)

### ISSUE THREAD

**Issue by mrengineer7777** [espressif/esp-idf#8378]
## Environment
- Development Kit:      [Adafruit Huzzah32: ESP32 Feather]
- Kit version [1]
- Module or chip used:  [ESP32-WROOM-32E]
- IDF version (run ``git describe --tags`` to find it):  framework-espressif 3.40400.0 (4.4.0)
- Build System:         [CMake]
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it):
    // 8.4.0+2021r2-patch2
- Operating System:     [Windows]
- (Windows only) environment type: [PowerShell].
- Using an IDE?: VSCode with Platformio: PIO Core 5.2.4, PIO Home 3.4.1
- Power Supply:         [USB 5V]

## Problem Description
When compiling my code under IDF4.4, I get the warning ["LOG_LOCAL_LEVEL" redefined].

Originally my project was on espressif32/arduino platform, but I switched to IDF and added Arduino libraries as necessary.  Unfortunately "Arduino as IDF component" is too broken to fix right now, but that's a different issue.
Note I define LOG_LOCAL_LEVEL in platformio.ini.

### Expected Behavior
IDF compiles without warnings

### Actual Behavior
Warning about LOG_LOCAL_LEVEL redefined

### Side effects
UNKNOWN

### Steps to reproduce
1. Download the Github project provided below
2. Open in VSCode with PIO extension
3. Select PIO build: checkmark on bottom bar

### Code to reproduce this issue
https://github.com/mrengineer7777/D4500idf2
This project reproduces the issue.  I have stripped out all sensitive code.  Note this includes lightly modified copies of Arduino libraries. The issue occurs in IDF.

## Debug Logs
```
Compiling .pio\build\featheresp32dev\vfs\vfs_uart.o
Archiving .pio\build\featheresp32dev\esp-idf\unity\libunity.a
Compiling .pio\build\featheresp32dev\vfs\vfs_semihost.o
C:\Users\David\.platformio\packages\framework-espidf\components\vfs\vfs.c:25: warning: "LOG_LOCAL_LEVEL" redefined
 #define LOG_LOCAL_LEVEL ESP_LOG_NONE

<command-line>: note: this is the location of the previous definition
Compiling .pio\build\featheresp32dev\vfs\vfs_console.o
Compiling .pio\build\featheresp32dev\wear_levelling\Partition.o
```

## Other items if possible
- [ X] sdkconfig file (attach the sdkconfig file from your project folder) - See code in Github project
- [ ] elf file in the ``build`` folder (**note this may contain all the code details and symbols of your project.**)
- [ ] coredump (This provides stacks of tasks.)

**Comment by o-marshmallow** [comment]
Hi @mrengineer7777 ,
I would like to note that you are not using ESP-IDF directly but platformio, which is **not** a project of Espressif.
Anyway, the issue you are encountering seems to come from your `platform.ini` file:
```
build_flags = 
	-DLOG_LOCAL_LEVEL=2																;Suppress startup messages
	-DCORE_DEBUG_LEVEL=4															;Additional debug info
```
These macros shall not be (re)defined here. Instead, you should modify the `sdkconfig` to set the log level to what you want:
```
# CONFIG_LOG_DEFAULT_LEVEL_NONE is not set
# CONFIG_LOG_DEFAULT_LEVEL_ERROR is not set
CONFIG_LOG_DEFAULT_LEVEL_WARN=y
# CONFIG_LOG_DEFAULT_LEVEL_INFO is not set
# CONFIG_LOG_DEFAULT_LEVEL_DEBUG is not set
# CONFIG_LOG_DEFAULT_LEVEL_VERBOSE is not set
CONFIG_LOG_DEFAULT_LEVEL=2
```

(When using ESP-IDF, this can be configured by using the menuconfig UI (`idf.py menuconfig`). I am not sure if platformio lets you have this menu config UI)

**Comment by mrengineer7777** [comment]
Searching through the IDF files, I see that LOG_LOCAL_LEVEL should only be defined/overriden at the file level.  I have removed it from build_flags and set ```CONFIG_BOOTLOADER_LOG_LEVEL=2``` using menuconfig.
esp_log.h sets the default log level: ```#define LOG_LOCAL_LEVEL  CONFIG_BOOTLOADER_LOG_LEVEL```

CORE_DEBUG_LEVEL is an Arduino macro, and I can't find an equivalent in menuconfig, so I'll leave that in platformio.ini.

Project compiles without the warning ["LOG_LOCAL_LEVEL" redefined].  Thank you for your assistance.

**Comment by o-marshmallow** [comment]
@mrengineer7777 Thanks for coming back with the complete solution!
