### ISSUE TITLE
I modify the demo esp-idf/examples/peripherals/lcd/rgb_panel according the demo /esp-idf/examples/peripherals/lcd/i80_controller and the chart is always drift, How can I sovle it  (IDFGH-6753)

### ISSUE THREAD

**Issue by Kingwulin** [espressif/esp-idf#8381]
I modify the demo esp-idf/examples/peripherals/lcd/rgb_panel according the demo /esp-idf/examples/peripherals/lcd/i80_controller
and the chart is always drift, How can I sovle it 
![mmexport1644555318861](https://user-images.githubusercontent.com/16952072/153539636-98cbdf1f-3426-4d9a-a523-abfd957fc77f.png)

**Comment by suda-morris** [comment]
If this is related to your last post in https://github.com/espressif/esp-idf/issues/8380 Please continue the conversation there, instead of opening a new one. Thanks. 

If this is a new issue you met, could you clarify it a little bit?  I'm not sure what kind of LCD you're using, and how you initialize your driver. Any code to reproduce?

**Comment by Kingwulin** [comment]
两个是不同的问题
这个问题是这样的：
1、如果用原本 [demo ](https://github.com/espressif/esp-idf/tree/master/examples/peripherals/lcd/rgb_panel) 是可以正常显示的
2、如果我仿照 [i80_controller](https://github.com/espressif/esp-idf/tree/master/examples/peripherals/lcd/i80_controller) 这个例子添加 logo 显示，是现实坐标图回一直漂移，但是显示图片不断刷新输出也是一样会漂移
3、我所使用的屏幕是[这个](https://m.tb.cn/h.fPKESjy?sm=6bc1f2?tk=RWqN2c6lxzC)

**Comment by Kingwulin** [comment]
你好
两个是不同的问题
这个问题是这样的：
1、如果用原本 [demo ](https://github.com/espressif/esp-idf/tree/master/examples/peripherals/lcd/rgb_panel)是可以正常显示的
2、如果我仿照 [i80_controller](https://github.com/espressif/esp-idf/tree/master/examples/peripherals/lcd/i80_controller) [这个](https://m.tb.cn/h.fPKESjy?sm=6bc1f2?tk=RWqN2c6lxzC)例子添加 logo 显示，显示的实坐标图回一直漂移，如果是只显示图片不断刷新输出也是一样会漂移
3、我所使用的屏幕是[这个](https://m.tb.cn/h.fPKESjy?sm=6bc1f2?tk=RWqN2c6lxzC)
![微信图片_20220211135428](https://user-images.githubusercontent.com/16952072/153543997-8eb3ed3a-6e5c-4f83-b3cb-b5000a9a486e.jpg)
![微信图片_20220211135434](https://user-images.githubusercontent.com/16952072/153544006-c0139ac2-4157-4e5b-91b6-b4c04cf56f57.jpg)

**Comment by suda-morris** [comment]
seems like this is a timing issue, you can try setting proper parameters in `panel_config.timings` according to your LCD spec.

**Comment by Kingwulin** [comment]
I change the panel_config.timings according the datasheet below ,but the question is still exit
[2021923171633414.pdf](https://github.com/espressif/esp-idf/files/8046357/2021923171633414.pdf)
![微信图片_20220211143309](https://user-images.githubusercontent.com/16952072/153547092-dca5cdf5-26a3-466c-a016-4e99c8d07600.png)

**Comment by Kingwulin** [comment]
![微信图片_20220211143648](https://user-images.githubusercontent.com/16952072/153547295-e534174a-804d-4d2f-a6a8-df443619a695.png)
also I set the dclk freq to 9M/s

**Comment by Kingwulin** [comment]
would you please share me anohter rgbpanel demo that display a dynamic image

**Comment by suda-morris** [comment]
We found some hardware bug in the LCD_CAM peripheral, and we're working on a workaround on it. Will let you know when the fix is available on the master branch. Thanks.
