### ISSUE TITLE
unable to clone the master and stable repos (IDFGH-6761)

### ISSUE THREAD

**Issue by rhr407** [espressif/esp-idf#8389]
~/esp$ git clone -b v4.4 --recursive https://github.com/espressif/esp-idf.git
Cloning into 'esp-idf'...
remote: Enumerating objects: 307129, done.
remote: Counting objects: 100% (190/190), done.
remote: Compressing objects: 100% (92/92), done.
error: RPC failed; curl 56 GnuTLS recv error (-9): Error decoding the received TLS packet.
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

**Comment by o-marshmallow** [comment]
Hi @rhr407 ,

Can you try cloning with SSH instead?
```
git clone -b v4.4 --recursive git@github.com:espressif/esp-idf.git
```

**Comment by dobairoland** [comment]
Another workaround is to download a ZIP from the [releases](https://github.com/espressif/esp-idf/releases) page.

I'd like to point out that this is not an issue with ESP-IDF. The error is related to your Internet connection (instability can cause this), git and or Github. Often repeating the operation helps.
