### ISSUE TITLE
[TW#14355] Establishing direct connection

### ISSUE THREAD

**Issue by hoonkai** [espressif/esp-idf#839]
I'm trying to connect the LAN PHY directly to a laptop. Can a static IP be assigned to the peripheral? I've been able to assign a static IP to the ESP32, but what needs to be done to assign a static IP to the attached device?

**Comment by FHFS** [comment]
https://esp32.com/viewtopic.php?f=17&t=1149&p=8257&hilit=ethernet+dhcp#p8205

**Comment by FayeY** [comment]
Hi @hoonkai , did the above suggestion help you resolve the issue?

**Comment by hoonkai** [comment]
Well, not straight away. I'm still working on it. I'll keep you posted! :)

**Comment by hoonkai** [comment]
I've sorted it out now! Thanks.
