### ISSUE TITLE
Add a example of hid keyboard (IDFGH-6770)

### ISSUE THREAD

**Issue by FanhuaCloud** [espressif/esp-idf#8398]
**Is your feature request related to a problem? Please describe.**

No.

**Describe the solution you'd like**
https://github.com/espressif/esp-idf/tree/master/examples/bluetooth/esp_hid_device
When I use the esp_hid_device example, I found that there is only a mouse demo, I hope the official can add a keyboard demo

**Comment by leeebo** [comment]
@FanhuaCloud  There is a nice keyboard example in https://github.com/espressif/esp-iot-solution/tree/master/examples/keyboard, which support both USB HID and BLE HID and RGB features
