### ISSUE TITLE
Allow using CMAKE Variables in Kconfig.projbuild files (IDFGH-6797)

### ISSUE THREAD

**Issue by daltonv** [espressif/esp-idf#8424]
My team has a bit of an unusual setup for a Kconfig.projbuild file in our project we have a main `Kconfig.projbuild` config file that idf.py detects and several other `kconfig.comp` that we purposefully name so idf.py doesn't detect them. In our main `Kconfig.projbuild` we source each of these `kconfig.comp` mainly so we can group these components in the menu for the `idf.py menuconfig` command.

Here is a layout of our directory structure
```
.
└── Project
    ├── CMakeLists.txt
    ├── main
    │   └── Kconfig.projbuild
    └── components
        ├── component_1
        │   └── kconfig.comp
        └── component_2
            └── kconfig.comp
```
And here is a rough idea of what our main `Kconfig.projbuild` looks like:
```
menu "Our Project configuration"
        source "$PROJECT_DIR/components/component_1/kconfig.comp"
	source "$PROJECT_DIR/components/component_2/kconfig.comp"
endmenu
```

Now all this works but we need to set the `PROJECT_DIR` as an OS ENV var. This is not very portable. 

If we could use something like the CMAKE [PROJECT_SOURCE_DIR](https://cmake.org/cmake/help/v3.0/variable/PROJECT_SOURCE_DIR.html) inside the `Kconfig.projbuild` that would save us from the manual OS ENV var setting step. Would that be possible to add?

Maybe there is a better way of going about this though?

**Comment by daltonv** [comment]
Thanks @dobairoland! That's exactly what I need. I didn't realize there was a separate Kconfig command source a file with a relative path.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, feel free to reopen.
