### ISSUE TITLE
No Audio in HFP-HF example (IDFGH-6802)

### ISSUE THREAD

**Issue by ferorted** [espressif/esp-idf#8429]
- Development Kit:      Lolin ESP32 board
- Module or chip used:  ESP32-WROOM-32
- Using an IDE?: Platformio
- Power Supply:  USB

## Problem Description
I'm doing tests using the hfp-hf example in https://github.com/espressif/esp-idf/tree/master/examples/bluetooth/bluedroid/classic_bt/hfp_hf

My montage is: smartphone (AG) -> Bluetooth link-> SP32 board -> MAX98357A (I2S) -> Speaker.
Pin 25 ESP -> LRC (MAX98357)
Pin 26 ESP -> BCLK (MAX98357)
Pin 5 ESP -> DIN (MAX98357)

I didn't any change in the code.

I can pair my phone (AG), receive and answer calls, etc. it works ok but no Audio on speaker.

When datapath is set to PCM and codec is CVSD I get a continuous loud noise on speaker.

When datapath is set to HCI (CVSD or mSBC codec) no audio on speaker neither noise.

So, I think the problem is I2S config but no there is way to do this in the code example. 

### Expected Behavior
Getting audio on speaker

### Actual Behavior
No audio (or only noise) on speaker.

### Steps to reproduce
Follow example instructions

**Comment by xiongweichao** [comment]
Hi, @ferorted 

When datapath is set to **CVSD**, audio data will be output via i2s.
When datapath is set to **HCI**, you need to process audio data in **bt_app_hf_client_incoming_cb** function.

Thanks

**Comment by ferorted** [comment]
Thank you,
Audio on speaker works now.

**Comment by ferorted** [comment]
Hi, Did you run  and configure "menuconfig"? mainly Bluetooth options.

**Comment by zhou88mang** [comment]
> Thank you, Audio on speaker works now.

I'm also working on an example. Can you tell me how you handle this data in bt_app_hf_client_incoming_cb? Or can you post your code for bt_app_hf_client_incoming_cb? thank you

**Comment by NathanApps** [comment]
> Thank you, Audio on speaker works now.

Im having the same issue as you how did you resolve this?

**Comment by xiongweichao** [comment]
> Hi, @ferorted
> 
> When datapath is set to **CVSD**, audio data will be output via i2s. When datapath is set to **HCI**, you need to process audio data in **bt_app_hf_client_incoming_cb** function.
> 
> Thanks

@NathanApps I'm not sure what problem you are having, but I think you need to check these two configuration options ([BT_HFP_AUDIO_DATA_PATH](https://github.com/espressif/esp-idf/blob/5454d37d496a8c58542eb450467471404c606501/components/bt/host/bluedroid/Kconfig.in#L104C8-L104C30) and [BTDM_CTRL_BR_EDR_SCO_DATA_PATH](https://github.com/espressif/esp-idf/blob/5454d37d496a8c58542eb450467471404c606501/components/bt/controller/esp32/Kconfig.in#L46)).

**Comment by NathanApps** [comment]
> > Hi, @ferorted
> > When datapath is set to **CVSD**, audio data will be output via i2s. When datapath is set to **HCI**, you need to process audio data in **bt_app_hf_client_incoming_cb** function.
> > Thanks
> 
> @NathanApps I'm not sure what problem you are having, but I think you need to check these two configuration options ([BT_HFP_AUDIO_DATA_PATH](https://github.com/espressif/esp-idf/blob/5454d37d496a8c58542eb450467471404c606501/components/bt/host/bluedroid/Kconfig.in#L104C8-L104C30) and [BTDM_CTRL_BR_EDR_SCO_DATA_PATH](https://github.com/espressif/esp-idf/blob/5454d37d496a8c58542eb450467471404c606501/components/bt/controller/esp32/Kconfig.in#L46)).

Currently have the same issue I am using MAX98357A (I2S) -> Speaker. with same pin out 
Pin 25 ESP -> LRC (MAX98357)
Pin 26 ESP -> BCLK (MAX98357)
Pin 5 ESP -> DIN (MAX98357)

The audio I getting out I can only describe as the old modem dial up.  I have used another example to check my speaker and the MAX98357A are all working fine which there our only seems to be with this example Im not getting audio when I try ringing the connected smart phone. Any ideas I have checked the setup and looks all correct

**Comment by xiongweichao** [comment]
> I have used another example to check my speaker and the MAX98357A are all working fine which there our only seems to be with this example Im not getting audio when I try ringing the connected smart phone. Any ideas I have checked the setup and looks all correct

@NathanApps   Could you please tell me which example you used?

**Comment by NathanApps** [comment]
> > I have used another example to check my speaker and the MAX98357A are all working fine which there our only seems to be with this example Im not getting audio when I try ringing the connected smart phone. Any ideas I have checked the setup and looks all correct
> 
> @NathanApps Could you please tell me which example you used?

This example https://github.com/espressif/esp-idf/tree/master/examples/bluetooth/bluedroid/classic_bt/hfp_hf

**Comment by HarMala** [comment]
Hi, Im also having trouble setting up a speaker with MAX98357A. Like OP, pairing the phone (AG) works and answering calls etc. has no trouble. However, I dont get any audio from the speaker at all, not even noise. 

Im using the same pins:
Pin 25 ESP -> LRC (MAX98357)
Pin 26 ESP -> BCLK (MAX98357)
Pin 5 ESP -> DIN (MAX98357)

I have tried setting the datapath to PCM and HCI, nothing seems to work.

I tested these same pins and speaker setup with the [A2DP sink example](https://github.com/espressif/esp-idf/tree/master/examples/bluetooth/bluedroid/classic_bt/a2dp_sink) and audio comes through fine. 

Any help? Running esp-idf v5.2.1.

**Comment by xiongweichao** [comment]
Hi @HarMala , Could you please tell me whether these two options are configured(([BT_HFP_AUDIO_DATA_PATH](https://github.com/espressif/esp-idf/blob/5454d37d496a8c58542eb450467471404c606501/components/bt/host/bluedroid/Kconfig.in#L104C8-L104C30) and [BTDM_CTRL_BR_EDR_SCO_DATA_PATH](https://github.com/espressif/esp-idf/blob/5454d37d496a8c58542eb450467471404c606501/components/bt/controller/esp32/Kconfig.in#L46)).)?

**Comment by HarMala** [comment]
> Hi @HarMala , Could you please tell me whether these two options are configured(([BT_HFP_AUDIO_DATA_PATH](https://github.com/espressif/esp-idf/blob/5454d37d496a8c58542eb450467471404c606501/components/bt/host/bluedroid/Kconfig.in#L104C8-L104C30) and [BTDM_CTRL_BR_EDR_SCO_DATA_PATH](https://github.com/espressif/esp-idf/blob/5454d37d496a8c58542eb450467471404c606501/components/bt/controller/esp32/Kconfig.in#L46)).)?

Hi @xiongweichao,

Here they are, taken as excerpts from sdkconfig:
```
...
CONFIG_BT_HFP_AUDIO_DATA_PATH_PCM=y
# CONFIG_BT_HFP_AUDIO_DATA_PATH_HCI is not set
...
# CONFIG_BTDM_CTRL_BR_EDR_SCO_DATA_PATH_HCI is not set
CONFIG_BTDM_CTRL_BR_EDR_SCO_DATA_PATH_PCM=y
CONFIG_BTDM_CTRL_BR_EDR_SCO_DATA_PATH_EFF=1

```

Full sdkconfig: [sdkconfig.txt](https://github.com/espressif/esp-idf/files/15152308/sdkconfig.txt)
