### ISSUE TITLE
BLE_SPP_Server_Demo (IDFGH-6806)

### ISSUE THREAD

**Issue by peterg0313210** [espressif/esp-idf#8433]
Hello, 

So I have been using the ble_spp_server_demo for a firmware application for work on my esp32 based hardware and so far it has worked great without any issues. However, I want to add a functionality that essentially keeps sending the UART data that was just sent from ble in a while loop if UART data is not received by the com port within 5ms of the data having been sent. Further more, I want to add a timeout counter into the while loop so once it has expired after 20 iterations it'll publish a byte array to the notify characteristic allowing our app to know there has been some failure in the whole system. 

In my application on the hardware serial side every uart tx transmission from ble has to be immediately followed by an acknowledgement rx transmission by the system that the board is communicating to. This functionality I want to add is essentially a fail safe in case there is some failure on the side of the other board where the other board is not sending any data for whatever reason. 

My attempted solution was to go into the gatts profile even handler and after the line where it writes data from ble to uart put a uart_read_bytes function that reads the incoming data with a 5ms timeout and if the length of that data  is 0 go into a while loop where I iteratively write the data again and read uart again with the same 5ms timeout with the break condition being that as soon as the data is read with length>0 or not 0 then break out of the while loop. 

This is close to working. If I write uart data from my ble app it surely will loop if there is no response after 5ms until there is a response. However, once there is a response and the uart data is read that read data does not show up in the notify characteristic. Once I write another group of data from the com port without having written data from ble first it'll notify but then if I send another uart byte without a response from uart it wont loop any more. I am trying to figure out the most efficient way to carry this out in a working way without these bugs. I'll post my code as well in just a bit. Thank you.

**Comment by Weijian-Espressif** [comment]
Any questions now ?
