### ISSUE TITLE
conflict annotation in miniz.h (IDFGH-6808)

### ISSUE THREAD

**Issue by BaaBaaGoat** [espressif/esp-idf#8435]
[https://github.com/espressif/esp-idf/blob/bf8d4d55d0c004a5c52b7721d6ae0484565e74fa/components/esp_rom/include/esp32c2/rom/miniz.h](url)
`// pBut_buf_func: If NULL, output data will be supplied to the specified callback. In this case, the user should call the tdefl_compress_buffer() API for compression.`
If NULL,there are no callback.
it seems to be:
`// pBut_buf_func: If **not** NULL, output data will be supplied to the specified callback. In this case, the user should call the tdefl_compress_buffer() API for compression.`

**Comment by zikalino** [comment]
@BaaBaaGoat thank you for catching this! We will fix it!
