### ISSUE TITLE
cannot read all PGN(ID) being sent via CAN (IDFGH-6816)

### ISSUE THREAD

**Issue by MatheusCaltran** [espressif/esp-idf#8443]
1 ESP32 send + TJA1050
2 ESP32 receiver , get only the PGN(ID) I want and assign it to the variables  + TJA1050

I'm using an ESP32 to simulate 6 PGN(ID) with random values ​​and send via can, everything working fine for now 
when (2)esp32 receives the information, esp32 can only read that it has received 2 or 3 PGN(ID)

![image](https://user-images.githubusercontent.com/88856093/154864518-62ec83ac-3650-41d2-ac57-05b09d5047b6.png)

![image](https://user-images.githubusercontent.com/88856093/154865604-f5c9c64b-3332-4aa6-b7a8-f53d90bcd489.png)

**Comment by Dazza0** [comment]
@MatheusCaltran What driver is this? It doesn't look like the TWAI driver in ESP-IDF.

**Comment by MatheusCaltran** [comment]
so i changed the library and it worked

**Comment by Dazza0** [comment]
@MatheusCaltran Again, I can't tell from your code snippet what library/driver you were using before, and what library/driver you are currently using. Judging from your code snippet you were/are using an Arduino library?

**Comment by Dazza0** [comment]
@MatheusCaltran Closing this issue as it's unrelated to ESP-IDF.
