### ISSUE TITLE
compiled went error on "cdc_acm_host" demo (IDFGH-6817)

### ISSUE THREAD

**Issue by Rita858** [espressif/esp-idf#8444]
Hi all,
    I have face some trouble on compiling "[cdc_acm_host](https://github.com/espressif/esp-idf/tree/master/examples/peripherals/usb/host/cdc/cdc_acm_host)" demo.
    branch of my sdk is master with commit f02169bc049.
    The error message after the compilation is completed is as follows：
    
![image](https://user-images.githubusercontent.com/53596746/154908226-82e4742f-29c6-4745-aead-197bea0fe08c.png)

   Looking forward to your reply. Thank you.
   Best regard.

**Comment by Dazza0** [comment]
@Rita858 Did you call `idf.py set-target esp32s2/s3` before building?

**Comment by Rita858** [comment]
I set esp32c3

> @Rita858 Did you call `idf.py set-target esp32s2/s3` before building?

**Comment by Dazza0** [comment]
@Rita858 Are you still facing a compilation error after setting the target to ESP32-S2 or ESP32-S3?

**Comment by Dazza0** [comment]
@Rita858 Closing this issue. Please feel free to reopen if necessary.
