### ISSUE TITLE
eth phy DP83TD510E (IDFGH-6823)

### ISSUE THREAD

**Issue by antoinnneee** [espressif/esp-idf#8449]
**Is your feature request related to a problem? Please describe.**

Hi, I'm working on a board that require ethernet, the board is already designed, and I have the phy "DP83TD510E" I don't know how to use it. I couldn't find low levels sources for other phy chip (like LAN8720). 

**Describe the solution you'd like**

If someone have an idea to help me. I just need some tips to understand how ESP32 work with ethernet. All example that I found are high level configuration. The best solution is a fully functional library, but a few tricks about how phy lib work in esp  are enough for me.

DP83TD510E chip datasheet :
https://www.ti.com/lit/ds/symlink/dp83td510e.pdf?ts=1645526103353&ref_url=https%253A%252F%252Fwww.google.com%252F

Thanks
Antoine

**Comment by KaeLL** [comment]
Does [this](https://github.com/espressif/esp-idf/tree/master/components/esp_eth/src) help?

**Comment by kostaond** [comment]
Here's my tips:
1) Prepare header with registers map. Something similar to `eth_phy_regs_struct.h`. Unfortunately, it seems DP83TD510E does not use standard PHY register mapping so you need to start from scratch.
2) Make copy of one of `esp_eth_phy_*.c` files (I would recommend the one which follows standard - lan87xx or KSZ...).
3) Find datasheet for the baseline PHY from step 2.
4) Go over the PHY functions in `esp_eth_phy_*.c` file, identify the registers with the same functionality and replace it with DP83TD510E registers read/writes.

If you need any further help, please don't hesitate to ask. However, we are not planning to support this DP83TD510E PHY chip. I hope you understand that we cannot support all PHY's on market. We don't have resources to do so. Therefore, I will propose to close this feature request.

**Comment by antoinnneee** [comment]
> Here's my tips:
> 
> 1. Prepare header with registers map. Something similar to `eth_phy_regs_struct.h`. Unfortunately, it seems DP83TD510E does not use standard PHY register mapping so you need to start from scratch.
> 2. Make copy of one of `esp_eth_phy_*.c` files (I would recommend the one which follows standard - lan87xx or KSZ...).
> 3. Find datasheet for the baseline PHY from step 2.
> 4. Go over the PHY functions in `esp_eth_phy_*.c` file, identify the registers with the same functionality and replace it with DP83TD510E registers read/writes.
> 
> If you need any further help, please don't hesitate to ask. However, we are not planning to support this DP83TD510E PHY chip. I hope you understand that we cannot support all PHY's on market. We don't have resources to do so. Therefore, I will propose to close this feature request. However, I would like to discuss it internally first. BTW: what is your use case of this PHY? It seems to be intended for quite specific use cases.

Hi kostaond,

Thanks for these tips, I have begin the driver, but it's hard to understand a ton of new knowledge, I think I had all that i need to start with esp and phy. I'm pretty familiar with register (working with a ton of différent uC: cypress, microchip, st, nxp...).  
I just need some time and I have a ton of work more urgent.

My project is basically a communication card that bridge some protocol (bluetooth / uart / ethernet (udp)). 

When my project will be done and board are built, I think I'll post my driver. (Keeping a little advance for me, doesn't want an dp83TD510E shotage before I start the first production) 

Thanks for the helping hand, I came back here if I have some trouble
Antoine

**Comment by kostaond** [comment]
Hi @antoinnneee, I believe once you get familiar with esp_eth drivers structure, it should not be a problem to quickly create the driver. Once you finish the driver and would like to share it with other users, you can do so via [ESP-IDF components manager](https://components.espressif.com/).

The reason why I asked about your use case is the dp83TD510E is quite specific since it supports 802.3cg. Based on what I've read it seems to be targeting to industrial environment. Therefore, I was thinking about opening internal discussion if we would to support this chip officially by Espressif if there was a market for it.

**Comment by kostaond** [comment]
I see an opportunity of using 802.3cg in an industrial environment where one can reuse already placed wiring and it is needed to deal with longer distances as discussed [here](https://e2e.ti.com/blogs_/b/analogwire/posts/how-10base-t1lsingle-pair-ethernet-phys-help-bring-more-data-farther-in-long-distance-applications). Or it could be utilized in older big buildings and again to reuse current single twisted pair of wires. For example, I come from Czech Republic and there is a lot of old buildings from 70's/80's with single twisted pair of wiring originally used for home telephones which is still there but not used for anything now. Hence there might be some room to use it for new purpose.

Anyway, we are not planning to support this PHY by IDF any soon. I am giving it the lowest priority. If there was more interest from community, we can consider implementing it. Please let us know if anybody else interested in usage of this PHY.

**Comment by antoinnneee** [comment]
Kostaond help me to find a design flow, 802.3cg is not compatible with classic ethernet. I close this feature request.
Thanks @KaeLL & @kostaond for helping me

**Comment by escherstair** [comment]
@kostaond I'm interested in using DP83TD510E for the same reason (reuse existing twister cables).
But datasheet for DP83TD510E from TI is a mess and it's really difficult to understand how to setup the several registers.
Not much help from TI side, unfortunately.
It seems there is a linux driver, but I don't know if it works or not.

**Comment by kostaond** [comment]
@escherstair do you have any specific question in mind? Or have you just expressed your interest to Espressif support this chip?

**Comment by escherstair** [comment]
@kostaond  just express my interest

**Comment by kostaond** [comment]
I wrote an [article](https://blog.espressif.com/esp-idf-custom-ethernet-phy-driver-quick-guide-45f9d23de0ad) of how to create a custom PHY driver in ESP-IDF recently. You can check it out if it could be used even in case of DP83TD510E.

**Comment by escherstair** [comment]
Thanks.

**Comment by escherstair** [comment]
Hi @kostaond 
thank you very much, but 10BASE-T1S ("Automotive Ethernet") is not what I'm interested in.
Even if the names are quite similar, I use 10BASE-T1L ("Long distance Industrial Ethernet")
![immagine](https://github.com/espressif/esp-idf/assets/22594460/2e0610c4-ea84-4205-aa83-116ec3a225bc)
[10Base-T1S Automotive Ethernet vs. 10Base-T1L Industrial Ethernet ](https://blog.teledynelecroy.com/2022/08/10base-t1s-automotive-ethernet-vs.html)
