### ISSUE TITLE
not found function esp_wifi_get_pmf_config_internal in esp-idf (IDFGH-6839)

### ISSUE THREAD

**Issue by greentd** [espressif/esp-idf#8463]
not found function esp_wifi_get_pmf_config_internal in esp-idf 

esp_hostap.c

#ifdef CONFIG_IEEE80211W

    esp_wifi_get_pmf_config_internal(&pmf_cfg, WIFI_IF_AP);

    if (pmf_cfg.required) {
	pairwise_cipher = WIFI_CIPHER_TYPE_CCMP;
    }
#endif /* CONFIG_IEEE80211W */

**Comment by MaxwellAlan** [comment]
Hi @greentd 
Can you share more detail about idf commit and which example or uploading your demo code to reproduce this issue.
And maybe you should using this command : git submodule update -f to update your submodule components.
Looking forward your reply.
Thanks.

**Comment by AxelLin** [comment]
@greentd 
It's in closed source library libnet80211.a, implementation source code is not available.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, feel free to reopen.
