### ISSUE TITLE
./install.sh fails to install, error "Can not create virtual environment" (IDFGH-6846)

### ISSUE THREAD

**Issue by kylemallory** [espressif/esp-idf#8470]
Installing latest clone of 'esp-idf', running ./install.sh fails with error:

```
Extracting /home/kylemallory/.espressif/dist/openocd-esp32-linux-amd64-0.11.0-esp32-20211220.tar.gz to /home/kylemallory/.espressif/tools/openocd-esp32/v0.11.0-esp32-20211220
Installing Python environment and packages
ERROR: This script was called from a virtual environment, can not create a virtual environment again
```

This is on a fairly fresh install of Pop_OS (basically Ubuntu).  Looking into the code for ./tools/idf_tools.py, at approx line 1577 (inside "action_install_python_env()") the test to determine if a virtual-environment is installed is bad logic.

Changed the "or" from:

`is_virtualenv = hasattr(sys, 'real_prefix') or (hasattr(sys, 'base_prefix') and sys.base_prefix != sys.prefix)`

to an "and":

`is_virtualenv = hasattr(sys, 'real_prefix') and (hasattr(sys, 'base_prefix') and sys.base_prefix != sys.prefix)`

fixes the problem.

**Comment by dobairoland** [comment]
Hi @kylemallory,

```
ERROR: This script was called from a virtual environment, can not create a virtual environment again
```
The error means that you've opened the terminal and run `. export.sh` which activated the virtual environment. And now you have run `install.sh` and it cannot install a new virtual environment if one is already activated.

The real solution to this problem is to open a new terminal window (clean shell) and run the `install.sh` there.

Please note that if you've added the `. export.sh` into one of the scripts processed by every shell (for example `.bashrc`) then you can get the same error. The solution for it is the same.

**Comment by 0xjakob** [comment]
@kylemallory Do you think it would be helpful do have a note about this problem in the [IDF setup instructions]( https://docs.espressif.com/projects/esp-idf/en/latest/esp32/get-started/linux-macos-setup.html#step-3-set-up-the-tools)? Or did you look at any other place?

**Comment by QGB** [comment]
ERROR: This script was called from a virtual environment, can not create a virtual environment again

**Comment by jcwren** [comment]
> Hi @kylemallory,
> 
> ```
> ERROR: This script was called from a virtual environment, can not create a virtual environment again
> ```
> 
> The error means that you've opened the terminal and run `. export.sh` which activated the virtual environment. And now you have run `install.sh` and it cannot install a new virtual environment if one is already activated.
> 
> The real solution to this problem is to open a new terminal window (clean shell) and run the `install.sh` there.
> 
> Please note that if you've added the `. export.sh` into one of the scripts processed by every shell (for example `.bashrc`) then you can get the same error. The solution for it is the same.

I don't believe this is entirely correct. I don't speak Python, but the script appears to find ANY virtual environment that's in the path, regardless if it's esp-idf or not. I ran into this exact problem, had a completely clean environment as far as esp-idf goes, and it blew it's brains out as above due to finding a virtual environment for a statistics package that someone at work wrote that was in my path.

**Comment by AshUK** [comment]
Removing the following from my .bash_profile fixed this on macOS 13

```
export IDF_PYTHON_ENV_PATH=$HOME/.espressif/python_env/idf4.3_py3.9_env

export PATH=$HOME/.espressif/python_env/idf4.4_py3.9_env/bin:$PATH
```

**Comment by AkashJohnSubash** [comment]
> > Hi @kylemallory,
> > ```
> > ERROR: This script was called from a virtual environment, can not create a virtual environment again
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The error means that you've opened the terminal and run `. export.sh` which activated the virtual environment. And now you have run `install.sh` and it cannot install a new virtual environment if one is already activated.
> > The real solution to this problem is to open a new terminal window (clean shell) and run the `install.sh` there.
> > Please note that if you've added the `. export.sh` into one of the scripts processed by every shell (for example `.bashrc`) then you can get the same error. The solution for it is the same.
> 
> I don't believe this is entirely correct. I don't speak Python, but the script appears to find ANY virtual environment that's in the path, regardless if it's esp-idf or not. I ran into this exact problem, had a completely clean environment as far as esp-idf goes, and it blew it's brains out as above due to finding a virtual environment for a statistics package that someone at work wrote that was in my path.

Faced the same issue as @jcwren . Had to remove another unrelated virtual environment from my `zsh` profile before I got  `install.sh` to work. Steps are below:

1. `nano ~/.zshrc`
2.  removed exported virtual environment paths from $PATH
3.  start fresh terminal , re-run `install.sh`

**Comment by joshua-beck-0908** [comment]
> > > Hi @kylemallory,
> > > ```
> > > ERROR: This script was called from a virtual environment, can not create a virtual environment again
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > The error means that you've opened the terminal and run `. export.sh` which activated the virtual environment. And now you have run `install.sh` and it cannot install a new virtual environment if one is already activated.
> > > The real solution to this problem is to open a new terminal window (clean shell) and run the `install.sh` there.
> > > Please note that if you've added the `. export.sh` into one of the scripts processed by every shell (for example `.bashrc`) then you can get the same error. The solution for it is the same.
> > 
> > 
> > I don't believe this is entirely correct. I don't speak Python, but the script appears to find ANY virtual environment that's in the path, regardless if it's esp-idf or not. I ran into this exact problem, had a completely clean environment as far as esp-idf goes, and it blew it's brains out as above due to finding a virtual environment for a statistics package that someone at work wrote that was in my path.
> 
> Faced the same issue as @jcwren, on a mac m1 . Had to remove another unrelated virtual environment from my `zsh` profile before I got `install.sh` to work. Steps are below:
> 
>     1. `nano ~/.zshrc`
> 
>     2. removed exported virtual environment paths from $PATH
> 
>     3. start fresh terminal , re-run `install.sh`

Yeah, I had the same issue here from an unrelated PlatformIO virtual environment in the path. Removed it and it worked.
Thanks, this helps a lot.

**Comment by 14790897** [comment]
same, because platform's python env in system path

**Comment by hpsaturn** [comment]
I have a Debian 12 that was upgraded from Debian 11, and I had this issue. In Debian 12 you should set a global venv because you will to have this error: 'error: externally-managed-environment'. I don't know if that was the reason, but I fixed the issue editing the `tools/idf_tools.py` file, and removing the next lines:

```
2791⋮    │    if is_virtualenv and (not os.path.exists(idf_python_env_path) or reinstall):
2792⋮    │        fatal('This script was called from a virtual environment, can not create a virtual environment again')
2793⋮    │        raise SystemExit(1)
``` 

after that the ./install script leave to show this error.
