### ISSUE TITLE
[TW#14414] after a new install: fatal: 'git status --porcelain=2'  

### ISSUE THREAD

**Issue by ESP32DE** [espressif/esp-idf#849]
was there a change in anything?
did i forget one step?

> fatal: 'git status --porcelain=2' failed in submodule components/aws_iot/aws-iot-device-sdk-embedded-C

does one know what this shell line mean - which command is not found?

best wishes
rudi ;-)

edit: search for this 
https://stackoverflow.com/questions/5456683/why-do-i-get-fatal-git-status-porcelain-failed

mhm -[ i search further](https://www.google.de/search?site=&source=hp&q=fatal%3A+%27git+status+--porcelain%3D2%27&oq=fatal%3A+%27git+status+--porcelain%3D2%27&gs_l=psy-ab.3...3924.3924.0.4663.1.1.0.0.0.0.62.62.1.1.0....0...1.2.64.psy-ab..0.0.0.bqdssadjuv4)

edit: which cmd/tools handle the versions conroll in the components and is missing now in the new install?

**Comment by FHFS** [comment]
remove the submodule then "git submodule update --init --force --remote --recursive"?

**Comment by FayeY** [comment]
Hi @ESP32DE , did the above suggestion help you resolve the issue?

**Comment by ESP32DE** [comment]
@FHFS 

txs i will try your suggestion. 
btw it is the [aws-iot-device-sdk-embedded-C](https://github.com/espressif/esp-idf/tree/master/components/aws_iot)
after `git clone --recursive https://github.com/espressif/esp-idf.git` 
and `git submodule update --init`
there is still `.git file`  in the folder
if i remove this file this solve the problem ( too ) 
but can't then update later cause .git file then is missing.

@FayeY 
i will check again my steps and will response here 
cause we have more extern repos in the esp-idf 
but only aws makes a problem, perhabs there is still a cmd missing
i will follow the update steps in detail now, what is missing.
thank you!

best wishes
rudi ;-)

**Comment by ESP32DE** [comment]
@FHFS 
txs - the .git file is again then in the supmodule and disturb
( after delete this .git file - then there is no error ) 

btw we have more .git files in the submodule that are forked
but only this AWS makes a problem

example ( no problem with it ) 
![grafik](https://user-images.githubusercontent.com/16070445/28771189-33c77b0c-75e2-11e7-8d0c-4744e228c8df.png)


best wishes
rudi ;-)

**Comment by igrr** [comment]
Hi rudi, can you give the steps to reproduce this (once you are back from your vacation)?
Which tool do you use to clone? Tortoisegit, command line git in mingw, command line git in cygwin, git in virtual machine using shared folder, etc.
What steps do you do after cloning?
Thanks.

**Comment by FayeY** [comment]
Any update about this issue?

**Comment by pglen** [comment]
On MSYS2 the /etc/profile.d/esp_env* has an extra slash and quote. Editing them out fixes the issue.
