### ISSUE TITLE
Separate GATTS and GATTC events (IDFGH-6897)

### ISSUE THREAD

**Issue by SamyRICHET** [espressif/esp-idf#8517]
Hi Espressif,

I have un suggestion about the event's management in Bluedroid.

**Context:**

I'm using the IDF 4.4 with bluedroid enable.
In my application, I'm using the ESP32 (in client mode) to connect to another iot device in BLE and also a smartphone can be connected to the ESP32 (in server mode).
Can be tested with gattc_gatts_coex example.

**Problem:**

When an event appears (like CONNECTED or DISCONNECTED), I received it in gattc event handler and in gatts event handler without taking into account where the event come from.

**Idea:**

Received the right event only in the right handler.

Thank you and best regards,

**Comment by esp-cjh** [comment]
@SamyRICHET Thanks for your suggestions. We have no plans to separate the GATTS and GATTC events at this time. You can process these events according to remote address.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, feel free to reopen.
