### ISSUE TITLE
SPI driver ST95 missing/shift 1 bit on reception line (IDFGH-6914)

### ISSUE THREAD

**Issue by ElieSKickMaker** [espressif/esp-idf#8534]
----------------------------- Delete below -----------------------------

**Reminder: If your issue is a general question, starts similar to "How do I..", or is related to 3rd party development kits/libs, please discuss this on our community forum at https://esp32.com instead.**

INSTRUCTIONS
============

Before submitting a new issue, please follow the checklist and try to find the answer.

- [ ] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [ ] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [ ] I have searched the issue tracker for a similar issue and not found a similar issue.

If the issue cannot be solved after the steps before, please follow these instructions so we can get the needed information to help you in a quick and effective fashion.

1. Fill in all the fields under **Environment** marked with [ ] by picking the correct option for you in each case and deleting the others.
2. Describe your problem.
3. Include [debug logs from the "monitor" tool](https://docs.espressif.com/projects/esp-idf/en/latest/api-guides/tools/idf-monitor.html), or [coredumps](https://docs.espressif.com/projects/esp-idf/en/latest/api-guides/core_dump.html).
4. Providing as much information as possible under **Other items if possible** will help us locate and fix the problem.
5. Use [Markdown](https://guides.github.com/features/mastering-markdown/) (see formatting buttons above) and the Preview tab to check what the issue will look like.
6. Delete these instructions from the above to the below marker lines before submitting this issue.

**IMPORTANT: If you do not follow these instructions and provide the necessary details, your issue may not be resolved.**

----------------------------- Delete above -----------------------------

## Environment

- Development Kit:      ESP32S2 DevKitC1-1

- Module or chip used:  ESP32S2FH4
- IDF version (run ``git describe --tags`` to find it):
    v4.3.2
- Build System:         idf.py
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it):
    xtensa-esp32-elf-gcc (crosstool-NG esp-2021r2) 8.4.0
- Operating System:     Windows
- (Windows only) environment type: [MSYS2 mingw32|ESP Command Prompt|Plain Command Prompt|PowerShell].
- Using an IDE?: [No|Yes (please give details)] VS Code
- Power Supply:         [USB|external 5V|external 3.3V|Battery]

## Problem Description
I'm coding a driver ESP32 for the nfc reader ST95HF by spi. It's SPI mode 3 (CPOL=1, CPHA =1). 

The problem is when I received data, it's shifted by 1 like it's missing one clock edge. 
For exemple, the echo command is sending 0x55 and I should received 0x55 by the slave. But the esp32 is reading 0xAA.  
Here is the logic analyzer view and the code for initialize spi bus, add the device and do the spi transmission. 

** Initialize spi bus **

```
spi_bus_config_t buscfg={
            .mosi_io_num=35,
            .miso_io_num = 37,
            .sclk_io_num=CONFIG_EINK_SPI_CLK,
            .quadwp_io_num=-1,
            .quadhd_io_num=-1,
            .max_transfer_sz= 4094
        };

        //Initialize the SPI bus
       //ret=spi_bus_initialize(SPI_HOST, &buscfg, SPI_HOST);
        ret=spi_bus_initialize(SPI_HOST, &buscfg, 0); /* try to disable dma */
        ESP_ERROR_CHECK(ret);
```

** Configure the spi device **

```
//Config Frequency and SS GPIO
    spi_device_interface_config_t devcfg={
        .mode=3,  //SPI mode 0
        .clock_speed_hz=NFC_SPI_BAUDRATE,  // DEBUG: 50000 - No debug usually 4 Mhz
        .input_delay_ns=0,
        //.cs_ena_pretrans=1,
        .spics_io_num=-1,
        .queue_size=1
        
    };
  
    esp_err_t ret=spi_bus_add_device(RFTRANS_95HF_SPI, &devcfg, &my_hspi);
    ESP_ERROR_CHECK(ret);
    flag_spi_init=true;
```

**Transmit/receive spi **

```
/**  
 *	@brief  Sends one byte over SPI and recovers a response
 *  @param  data : data to send
 *  @retval data response from SPIx 
 */
uint8_t SPI_SendReceiveByte(uint8_t data) 
{	
  
  uint8_t ret_value=0x0;	
  uint8_t ret_value_cpy=0;	
	#if 1
  //ESP_LOGI("SPI_SendReceiveByte","data send :%0x",data);

  esp_err_t ret=0;
  spi_transaction_t t;          
  memset(&t, 0, sizeof(t));       //Zero out the transaction
  
  if(ret==ESP_OK){ /* Wait to receive data*/
   
    t.flags = SPI_TRANS_USE_TXDATA;
    t.length = 8;
    t.tx_data[0]=data;              //The data is the cmd itself
    t.rxlength = 8;
    t.rx_buffer = &ret_value;
    ret=spi_device_polling_transmit(my_hspi, &t);  //Transmit!
    
    if (ret !=ESP_OK){
      ESP_LOGE("SPI_SendReceiveByte","ret receive data:%d",ret);
      return ret_value;
    }
    #if 1
     //ret_value=t.rx_data[0];
    ESP_LOGI("SPI_Recv"," data send : %0x data recv[0]:%0x  data shift:%0x",data,ret_value,ret_value>>1);
    //ret_value_cpy=(ret_value >> 1) ;
    //ret_value=ret_value_cpy;
    #else 
    //ESP_LOGI("SPI_SendReceiveByte","data:%0x",ret_value);
    #endif
    
  }           //Should have had no issues.
  else {
    ret_value=0;
  }

  
  return ret_value;
}
```

**Log Error :**

```
I (21) boot: ESP-IDF v4.3.2-dirty 2nd stage bootloader
I (21) boot: compile time 11:13:24
I (21) boot: chip revision: 0
I (24) boot.esp32s2: SPI Speed      : 80MHz
I (29) boot.esp32s2: SPI Mode       : DIO
I (34) boot.esp32s2: SPI Flash Size : 4MB
I (39) boot: Enabling RNG early entropy source...
I (44) boot: Partition Table:
I (48) boot: ## Label            Usage          Type ST Offset   Length
I (55) boot:  0 nvs              WiFi data        01 02 00009000 00004000
I (62) boot:  1 otadata          OTA data         01 00 0000d000 00002000
I (70) boot:  2 phy_init         RF data          01 01 0000f000 00001000
I (77) boot:  3 ota_0            OTA app          00 10 00010000 00100000
I (85) boot:  4 ota_1            OTA app          00 11 00110000 00100000
I (92) boot:  5 storage          WiFi data        01 02 00210000 00008000
I (100) boot:  6 storage2         Unknown data     01 82 00218000 00010000
I (107) boot: End of partition table
I (111) boot: No factory image, trying OTA 0
I (116) esp_image: segment 0: paddr=00010020 vaddr=3f000020 size=0bf5ch ( 48988) map
I (135) esp_image: segment 1: paddr=0001bf84 vaddr=3ffbfdf0 size=0291ch ( 10524) load
I (137) esp_image: segment 2: paddr=0001e8a8 vaddr=40024000 size=01770h (  6000) load
I (143) esp_image: segment 3: paddr=00020020 vaddr=40080020 size=1d264h (119396) map
I (174) esp_image: segment 4: paddr=0003d28c vaddr=40025770 size=0a67ch ( 42620) load
I (185) esp_image: segment 5: paddr=00047910 vaddr=50000000 size=00010h (    16) load
I (191) boot: Loaded app from partition at offset 0x10000
I (243) boot: Set actual ota_seq=1 in otadata[0]
I (243) boot: Disabling RNG early entropy source...
I (253) cache: Instruction cache        : size 8KB, 4Ways, cache line size 32Byte
I (254) cpu_start: Pro cpu up.
I (265) cpu_start: Pro cpu start user code
I (265) cpu_start: cpu freq: 240000000
I (265) cpu_start: Application information:
I (270) cpu_start: Project name:     titibike_firmware
I (276) cpu_start: App version:      1f4d9ae-dirty
I (281) cpu_start: Compile time:     Mar  9 2022 11:12:39
I (287) cpu_start: ELF file SHA256:  bfb67e5a5ee20523...
I (293) cpu_start: ESP-IDF:          v4.3.2-dirty
I (299) heap_init: Initializing. RAM available for dynamic allocation:
I (306) heap_init: At 3FF9E000 len 00002000 (8 KiB): RTCRAM
I (312) heap_init: At 3FFC60E8 len 00035F18 (215 KiB): DRAM
I (318) heap_init: At 3FFFC000 len 00003A10 (14 KiB): DRAM
I (325) spi_flash: detected chip: generic
I (329) spi_flash: flash io: dio
CalEPD component version 1.0.6
EcoSE2266() constructor injects IO and extends Adafruit_GFX(152,296) Pix Buffer[5624]

Available heap after Epd bootstrap:223896
I (348) cpu_start: Starting scheduler on PRO CPU.
Hello world!
I (354) gpio: GPIO[6]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 
I (364) gpio: GPIO[11]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 
I (364) gpio: GPIO[18]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 
I (374) gpio: GPIO[19]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 
I (384) gpio: GPIO[33]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 
I (394) gpio: GPIO[34]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 
I (404) gpio: GPIO[12]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:3 
I (414) SPIFFS: Partition size: total: 52961, used: 0
I (4424) NFC_APP: Start app NFC
I (4434) SPI_Recv:  data send : 1 data recv[0]:18  data shift:c
I (4454) SPI_Recv:  data send : 0 data recv[0]:c  data shift:6
I (4454) SPI_Recv:  data send : 55 data recv[0]:c  data shift:6
I (4454) drv95HF_ReceiveSPI: cs low
I (4454) SPI_Recv:  data send : 2 data recv[0]:1c  data shift:e
I (4464) SPI_Recv:  data send : ff data recv[0]:aa  data shift:55
I (4464) SPI_Recv:  data send : ff data recv[0]:0  data shift:0
I (4474) SPI_Recv:  data send : 1 data recv[0]:c  data shift:6
I (4504) SPI_Recv:  data send : 0 data recv[0]:c  data shift:6
I (4504) SPI_Recv:  data send : 55 data recv[0]:c  data shift:6
I (4504) drv95HF_ReceiveSPI: cs low
I (4504) SPI_Recv:  data send : 2 data recv[0]:1c  data shift:e
I (4514) SPI_Recv:  data send : ff data recv[0]:aa  data shift:55
I (4514) SPI_Recv:  data send : ff data recv[0]:0  data shift:0
I (4524) SPI_Recv:  data send : 1 data recv[0]:c  data shift:6
I (4554) SPI_Recv:  data send : 0 data recv[0]:c  data shift:6
I (4554) SPI_Recv:  data send : 55 data recv[0]:c  data shift:6
I (4554) drv95HF_ReceiveSPI: cs low
I (4554) SPI_Recv:  data send : 2 data recv[0]:1c  data shift:e
I (4564) SPI_Recv:  data send : ff data recv[0]:aa  data shift:55
I (4564) SPI_Recv:  data send : ff data recv[0]:0  data shift:0
I (4574) SPI_Recv:  data send : 1 data recv[0]:c  data shift:6
I (4604) SPI_Recv:  data send : 0 data recv[0]:c  data shift:6
I (4604) SPI_Recv:  data send : 55 data recv[0]:c  data shift:6
I (4604) drv95HF_ReceiveSPI: cs low
I (4604) SPI_Recv:  data send : 2 data recv[0]:1c  data shift:e
I (4614) SPI_Recv:  data send : ff data recv[0]:aa  data shift:55
I (4614) SPI_Recv:  data send : ff data recv[0]:0  data shift:0
I (4624) SPI_Recv:  data send : 1 data recv[0]:c  data shift:6
I (4654) SPI_Recv:  data send : 0 data recv[0]:c  data shift:6
I (4654) SPI_Recv:  data send : 55 data recv[0]:c  data shift:6
I (4654) drv95HF_ReceiveSPI: cs low
I (4654) SPI_Recv:  data send : 2 data recv[0]:1c  data shift:e
I (4664) SPI_Recv:  data send : ff data recv[0]:aa  data shift:55
I (4664) SPI_Recv:  data send : ff data recv[0]:0  data shift:0
I (4674) SPI_Recv:  data send : 1 data recv[0]:c  data shift:6
I (4704) SPI_Recv:  data send : 0 data recv[0]:c  data shift:6
I (4704) SPI_Recv:  data send : 55 data recv[0]:c  data shift:6
I (4704) drv95HF_ReceiveSPI: cs low
I (4704) SPI_Recv:  data send : 2 data recv[0]:1c  data shift:e
I (4714) SPI_Recv:  data send : ff data recv[0]:aa  data shift:55
I (4714) SPI_Recv:  data send : ff data recv[0]:0  data shift:0
I (4724) SPI_Recv:  data send : 1 data recv[0]:c  data shift:6
E (4754) ConfigManager_PORsequence: PORERROR
E (4754) ConfigManager_HWInit: error PORsequence
E (4754) NFC_APP: Start NFC ERROR
```

![master send 0x55](https://user-images.githubusercontent.com/92736346/157482907-7c71cd08-b876-4f97-a13b-7561565cb069.PNG)
![master receive 0x55](https://user-images.githubusercontent.com/92736346/157482913-334ef0e2-67bf-48a0-894c-263226dfd0d6.PNG)

**Comment by KaeLL** [comment]
Any particular reason to use mode 3 over 0? Legitimately curious.
Try setting `spi_device_interface_config_t::cs_ena_pretrans` to 1 and see if it works.

**Comment by ElieSKickMaker** [comment]
@KaeLL  I'm using mode 3 because I have a stm32 example working on mode 3 but it's also working on mode 0 due to the datasheet. I've also tried mode 0 (and 1 and 2 ..) ,same issue. 
No it's not working because I'm not in half duplex 

 " 
cs_ena_pretrans;        ///< Amount of SPI bit-cycles the cs should be activated before the transmission (0-16). This only works on half-duplex transactions.
"

**Comment by KaeLL** [comment]
> No it's not working because I'm not in half duplex

What I said verbatim when I ported the TRF7970A driver, yet testing on the logic analyzer showed it worked.

**Comment by KaeLL** [comment]
If by "falsed" you mean invalid, then yes. Mode 1, btw. The behavior seems to make sense if CPOL were to be 1, but that's not the case.
![Screenshot from 2022-03-09 15-04-29](https://user-images.githubusercontent.com/4423144/157504120-7d17c55c-98f4-4176-a7c0-8f4cb65d85e4.png)
Making the cs line active 1 cycle earlier generates the correct result
![Screenshot from 2022-03-09 15-02-21](https://user-images.githubusercontent.com/4423144/157504154-4d786d7c-821f-43e7-86d6-81ee4c065f25.png)

**Comment by KaeLL** [comment]
I don't know why setting `cs_ena_pretrans` works in full-duplex;
I'm not sure why the MISO line is idle high;
I'm don't know why `cs_ena_pretrans=0` causes all the oddities at transaction start in the first image.
The SPI code in IDF is still very confusing to me, which put me off of trying to look for answers. At this point, I'm not leaning towards my mental model of SPI being significantly wrong.

**Comment by ginkgm** [comment]
Hi @ElieSKickMaker , 
I guess it's possible that @KaeLL 's opinion is quite close to the reason - ESP32's CS active edge is at the same moment as the first clock edge when cs_setup (cs_ena_pretrans) is kept 0. I guess ST95 detect mode 0 or 3 by the timing sequence of CS and clock edge. 

![image](https://user-images.githubusercontent.com/18559742/157581727-c1378cab-458f-4034-8ff0-0254e0df4ece.png)

If the CS is pulled low when clock is high, it will give bit 6 at the second falling edge ; however if CS is pulled low when clock is low, it will give bit 6 at the first falling edge. 

Solutions: 
1. If you still want to use mode 3, we should give ST95 a determined clock state when CS is pulled low, so could you please also provide the waveform of CS (in total 4 wires) so that we can check it?

And btw, cs_ena_pretrans is the easiest way to solve this problem, and the limitation is a bit looser than 'only in half duplex mode'. See https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/peripherals/spi_master.html#known-issues. If the driver doesn't check it strictly, you may still set it to non-0 value and see what happen.

2. Or you may use mode 0. This may also directly solve the problem.

**Comment by ElieSKickMaker** [comment]
Thanks for your response. 

So, I've tried to play  on cs_ena_pretrans (even on mode 0 also). I've still the same issue, it's receiving 0x6 but it's reading 0xC  
![cs ena pretrans postrans 1](https://user-images.githubusercontent.com/92736346/157653085-1fa07bba-7105-43c3-8ec3-d4b9ba2a6486.PNG)

**Comment by KaeLL** [comment]
Could that be due to the [MISO lag](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/peripherals/spi_master.html#timing-considerations)?

**Comment by ginkgm** [comment]
Hi @ElieSKickMaker @KaeLL ,

1. the `0x06` (`0x0c`) is sent by ST95HF, right? But according to its spec, it always launch the data at the falling edge, no matter mode 0 or 3. Do you know what cause the difference between its spec and what we see? Actually it's half a clock ahead of spec.

2. According to SPI spec, in mode 3 both sides should latch (read) data at the rising edge. But we see there is transition on MISO at that edge, so the read data is undetermined. Both 0x06 or 0x0c are understandable. 

   To tolerate higher input delay, ESP32 hardware and driver latch the data a bit later (at the falling edge). This is usually OK if the slave launch the data according to the spec. But ST95HF also sends data half a clock ahead of spec, together they make one bit shift. You may try to force enable this block to delay the input by half an SPI clock to workaround it: https://github.com/espressif/esp-idf/blob/master/components/hal/spi_hal_iram.c#L76

**Comment by ginkgm** [comment]
Issue closed. If any more found, feel free to re-open

**Comment by ManuelHuf** [comment]
I have the same problem using an esp32c3 with the ST CR95HF. Are there any updates regarding this issue? I tried SPI mode 0 as well as mode 3. Also the `.cs_ena_pretrans = 1` didn't help.
