### ISSUE TITLE
I2S ADC Mode ESP32-S3 (IDFGH-6916)

### ISSUE THREAD

**Issue by matti122** [espressif/esp-idf#8536]
I want to connect a analog microphone to the ESP32-S3.
But the functions to bring ESP32-S3 in I2S ADC Mode are not available, at ESP32 the functions are available.
Will ESP32-S3 support this feature in future or are there any Hardware restrictions?
Thanks for your help

**Comment by L-KAYA** [comment]
Hi @matti122,
Only the hardware of ESP32 can support reading ADC data via I2S. Theoretically, ADC on ESP32 borrows the DMA channel of I2S, it's not a main mode of I2S. So ADC won't supported by I2S in the future.

If you want to reading ADC data like I2S ADC on ESP32-S3, you can use the dedicated ADC driver, there is an ADC DMA under the path `examples/peripherals/adc/dma_read`, hope it can help~

Best regards
