### ISSUE TITLE
I2S channel selection issue? (IDFGH-6918)

### ISSUE THREAD

**Issue by fpgamaster** [espressif/esp-idf#8538]
- Development Kit: none
- Module or chip used: ESP32-WROOM-32U
- IDF version: v5.0-dev-1426-ge899edd793
- Build System: idf.py
- Compiler version: xtensa-esp32-elf-gcc (crosstool-NG esp-2020r1) 8.2.0
- Operating System: Linux
- Using an IDE?: No
- Power Supply: external 5V

## Problem Description
I have a single I2S microphone configured as LEFT but can receive data from it in case when the I2S master is configured as LEFT and in case when the master is configured as RIGHT. (channel_format: I2S_CHANNEL_FMT_ONLY_RIGHT, channel_format: I2S_CHANNEL_FMT_ONLY_RIGHT)

The code I use is based on https://github.com/ikostoski/esp32-i2s-slm and is slightly modified.
The microphone used is TDK/InvenSense ICS-43432. According to its datasheet when LR pin is connected to GND, data output is on WS low. The GPIOs used are 12 (CLK), 13 (DATA), 14 (WS).
It looks like the WS pin is not changed on channel selection. Also, it is not a hardware issue because it is same on all boards I have.

Best regards

**Comment by L-KAYA** [comment]
@fpgamaster Actrually, it's a naming issue. The enum names in `i2s_channel_fmt_t` is not accurate, there are only three real format in it.
- `I2S_CHANNEL_FMT_RIGHT_LEFT`, `I2S_CHANNEL_FMT_ALL_RIGHT` and `I2S_CHANNEL_FMT_ALL_LEFT` stands for stereo mode, which means two channels will transport different data.
- `I2S_CHANNEL_FMT_ONLY_RIGHT` and `I2S_CHANNEL_FMT_ONLY_LEFT` they are mono mode, both channels will only transport same data.
- `I2S_CHANNEL_FMT_MULTIPLE` means TDM channels, up to 16 channel will available, and they are stereo as default.
So, in your case, you want to receive two channels, one is the actual data from microphone and another channel is suppose to receive `0`, it's different data in two channels, you need to choose `I2S_CHANNEL_FMT_RIGHT_LEFT` in this case.
