### ISSUE TITLE
Not having recent Python versions installed leads to unclear error in `detect_python.sh` (IDFGH-6929)

### ISSUE THREAD

**Issue by fabianpedd** [espressif/esp-idf#8549]
## Environment

- Development Kit: n.a.
- IDF version: v5.0-dev-1959-g4cdf2459f0
- Build System: idf.py
- Operating System: Linux, Ubuntu 18.04
- Python 3.6

## Problem Description

When only having Python versions "older" than 3.7 installed the `tools/detect_python.sh` script throws some very cryptic error message. 

### Expected Behavior

Some meaningful error message about outdated Python version.

### Actual Behavior

`esp-idf/tools/detect_python.sh: line 24: ESP_PYTHON: unbound variable`

### Steps to reproduce

1. Clone the latest master
2. Only have Python 3.6 installed
3. Try to install IDF with `install.sh`

### Cause and suggested fix

I believe this is caused by the recent changes in addd647f41f7972f154b5367ffbe601f2c3388fa to the file. Reintroducing [`ESP_PYTHON=python`](https://github.com/espressif/esp-idf/blob/47f67f8b81b14dddc3a75e13cc41e11216639e7d/tools/detect_python.sh#L10) at the top of the file should fix the issue. It will print the expected error message `RuntimeError: ESP-IDF supports Python 3.7 or newer but you are using Python 2.7.17. Please upgrade your installation as described in the documentation.`

**Comment by dobairoland** [comment]
@fabianpedd  Thank you for letting us know about this. We will fix it soon.
