### ISSUE TITLE
flash_download_tool  Error: Unable to set default locale: 'unsupported locale setting' (IDFGH-6932)

### ISSUE THREAD

**Issue by CAIJUN111** [espressif/esp-idf#8552]
The tool I downloaded doesn't work 
![K92XVGR1){K{U{N}9W3QCJE](https://user-images.githubusercontent.com/96687945/157812797-22b1d91a-7fcf-4f85-ac35-b8b3d8bcabc0.png)
Can anyone help me？
I have never come across such a problem
The flash tool version is flash_download_tool_3.9.2

**Comment by arosyc** [comment]
Maybe config file is broken.
Could you delete config folder and try again?

**Comment by CAIJUN111** [comment]
I tried, but it didn't work. I can use the same file on another computer&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月11日(星期五) 下午5:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [espressif/esp-idf] flash_download_tool  Error: Unable to set default locale: &#39;unsupported locale setting&#39; (IDFGH-6932) (Issue #8552)





 
Maybe config file is broken.
 Could you delete config folder and try again?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by arosyc** [comment]
okey, Could you download and try again. If it does not work, I will try to reproduce your issure.

**Comment by CAIJUN111** [comment]
I tried, but it didn't work




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月11日(星期五) 晚上7:08
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [espressif/esp-idf] flash_download_tool  Error: Unable to set default locale: &#39;unsupported locale setting&#39; (IDFGH-6932) (Issue #8552)





 
okey, Could you download and try again. If it does not work, I will try to reproduce your issure.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by arosyc** [comment]
It looks like the problem is caused by the version of the UI library the tool depends on. However, this problem should not affect the normal use of the download tool, and we will fix this problem in the next version.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting and sharing the updates, sorry for the very slow turnaround, the issue has been fixed, feel free to reopen if the issue still happens. Thanks.
