### ISSUE TITLE
TWAI API is slow and changing TWAI API is like playing with shards of glass (IDFGH-6941)

### ISSUE THREAD

**Issue by esphelp** [espressif/esp-idf#8561]
Environment:

Boards: ESP32C3, ESP32
ESP-IDF versions used: 4.23, 4.4, 4.5 master
Eclipse Plugin: latest
Operating System: windows 10
Java Runtime Version: 16.0.2+7-67
Eclipse Version: 4.21.0.v20210906-0500
Eclipse CDT Version: 10.4.0.202106130052
IDF Eclipse Plugin Version: 2.4.2.202203081345
ESP-IDF v4.2.3-dirty
Python set for IDF_PYTHON_ENV: Python 3.8.0
Python declared in PATH variable: Python 3.8.0

Problem:

I am using the TWAI peripheral to receive data from a busy 1Mhz CAN bus. The default API receive was able to pickup on average 1200 frames for rx_missing 40k frames. I was able to change the ISR callback function in twai.c twai_handle_rx_buffer_frames to send data to a large fifo buffer instead of using the slow freertos queue and was able to achieve adequate throughput. I was having endless problems with unresolved inclusions before I started changing the API files, but now that I have I will have to clean, rebuild, freshen files, and rely on what only seems like chance for it to build properly. 

So modifying and sometimes even opening twai.c and twai.h leads to endless problems. 
Resolution:

I would appreciate a solution in the form of:
-versions and tips to use to end my indexing problems in this dev environment
-new version of the twai_handle_rx_buffer_frames function with _weak so it can be replaced in the main folder
-faster TWAI function
-could just be that I don't understand cmake enough

Misc problems:

-neither GDB or openOCD work in eclipse (I did follow the guide)
-VS code extension doesn't work unless it is set to 4.23, but doesn't flash due to openOCD not working.

Code:

added to twai.h

//#pragma once
#define rxBufferSize 13000
#define rxMessageBufferSize 1000
#define rxBytesPerMessage 13
typedef struct {
	volatile unsigned int rxTail;
	volatile unsigned int rxHead;
	char *buffer;
} bufferFifo;
extern bufferFifo rxBufferFifo;

replaced function with this in twai.c

char rxBuffer[rxBufferSize]; //13 byte message size * 1000 messages
bufferFifo rxBufferFifo = {0, rxMessageBufferSize - 1, rxBuffer};
static inline void twai_handle_rx_buffer_frames(BaseType_t *task_woken, int *alert_req)
{
	uint32_t msg_count = twai_hal_get_rx_msg_count(&twai_context);
	bool overrun = false;
	twai_hal_frame_t frame;
	//Clear all valid RX frames
	for (int i = 0; i < msg_count; i++) {
		if(rxBufferFifo.rxHead != rxBufferFifo.rxTail) {
			if (twai_hal_read_rx_buffer_and_clear(&twai_context,
					(twai_hal_frame_t *)&rxBufferFifo.buffer[rxBufferFifo.rxHead * rxBytesPerMessage])) {
				rxBufferFifo.rxHead = (rxBufferFifo.rxHead + 1) % (rxMessageBufferSize);
				p_twai_obj->rx_msg_count++;
				twai_alert_handler(TWAI_ALERT_RX_DATA, alert_req);
			} else {
				overrun = true;
				break;
			}
		}
		else {
			twai_hal_read_rx_buffer_and_clear(&twai_context, &frame); //need to read to clear
			p_twai_obj->rx_missed_count++;
			twai_alert_handler(TWAI_ALERT_RX_QUEUE_FULL, alert_req);
		}
	}
	//All remaining frames are treated as overrun. Clear them all
	if (overrun) {
		//p_twai_obj->rx_overrun_count += twai_hal_clear_rx_fifo_overrun(&twai_context);
		twai_alert_handler(TWAI_ALERT_RX_FIFO_OVERRUN, alert_req);
	}
}

**Comment by Dazza0** [comment]
> The default API receive was able to pickup on average 1200 frames for rx_missing 40k frames. I was able to change the ISR callback function in twai.c twai_handle_rx_buffer_frames to send data to a large fifo buffer instead of using the slow freertos queue and was able to achieve adequate throughput.

Before you start changing the driver, have you actually profiled the code to confirm that the bottleneck is in the FreeRTOS queue? I just did a simple test and the `twai_handle_rx_buffer_frames()` taks about 1300 to 1400 CPU clock cycles. At at 160MHz CPU, that should be less than < 9ns.

Usually the bottleneck is in ISR latency. The TWAI controller has a HW FIFO (can usually store a couple of frames), so it'll only drop frames if the HW FIFO isn't cleared fast enough. However, in that is the case, the driver should report a FIFO overrun alert.

Before you start changing the functions, I suggest you diagnose where the cause of the frame drops are first.

> -versions and tips to use to end my indexing problems in this dev environment
> -neither GDB or openOCD work in eclipse (I did follow the guide)

Suggest you open an issue at the [idf-eclipse-plugin](https://github.com/espressif/idf-eclipse-plugin) repo. Usually, Eclipse will just index based off the compile_commands.json created in your project's build folder. However, if you're trying to index directly in the ESP-IDF directory itself, then that might be a separate issue.

> -VS code extension doesn't work unless it is set to 4.23, but doesn't flash due to openOCD not working.

Likewise, please open an issue at the [vscode-esp-idf-extension](https://github.com/espressif/vscode-esp-idf-extension)
