### ISSUE TITLE
ESP32S3 artifacts on LCD after wifi enabled (IDFGH-6953)

### ISSUE THREAD

**Issue by daniInfi7** [espressif/esp-idf#8573]
* Development Kit: ESP32-S3-MINI-1
* IDF version v4.4 stable version
* Build System: CMake invoked by espressif-IDE
* Compiler version xtensa-esp32s3-elf-gcc (crosstool-NG esp-2021r2-patch2) 8.4.0
* Operating System: macOS/Windows
* Using an IDE?: espressif-IDE
* Power Supply: external 3.3V
* CPU frequncy: 240 MHz / 160 MHz (problem at both values)
# Problem Description #

First the official lcd driver was sucesfully implemented with a 16 bit paralel interface, where a double buffer was used to send the data alternately to the LCD. Before a new write occurs the LCD write function waits for a transmitt done event. Until this point the driver has worked as expected and the problems started occuring after the wifi module was enabled.

At this point at random time artifacts started occuring on the display which happens pretty frequent. After some investigation we can for sure confirm that this behavior is connected with the wifi. From the behaviour it looks like the region is not set correctly because  the pixels apear in random positions and have random region shapes.

# What we have tried #
* Running wifi as default on CPU0 and all other tasks on CPU1.
* changing the default wifi CPU from 0 to 1 and having the LCD task running on CPU0 and also

**Comment by suda-morris** [comment]
Hi @daniInfi7 could you check the solution in https://github.com/espressif/esp-idf/issues/8212 to see whether it can help?

**Comment by daniInfi7** [comment]
@suda-morris this has solved the problem, thank you!
