### ISSUE TITLE
How to save pictures from camera to SD card  in the esp32s3 The program below will freeze (IDFGH-6965)

### ISSUE THREAD

**Issue by 13149036365** [espressif/esp-idf#8585]
void Cam_To_SD(int width, int height)
{
        static uint8_t Byte[1024];
	int index = 0;
	uint16_t bmpheadsize;			//bmp头大小	   	
 	BITMAPINFO hbmp;			//bmp头	 

	bmpheadsize=sizeof(hbmp);//得到bmp文件头的大小   
	memset((uint8_t*)&hbmp,0,sizeof(hbmp));//置零空申请到的内存.	    
	hbmp.bmiHeader.biSize=sizeof(BITMAPINFOHEADER);//信息头大小
	hbmp.bmiHeader.biWidth=width;	 	//bmp的宽度
	hbmp.bmiHeader.biHeight=height; 	//bmp的高度
	hbmp.bmiHeader.biPlanes=1;	 		//恒为1
	hbmp.bmiHeader.biBitCount=16;	 	//bmp为16位色bmp
	hbmp.bmiHeader.biCompression=BI_BITFIELDS;//每个象素的比特由指定的掩码决定。
 	hbmp.bmiHeader.biSizeImage=hbmp.bmiHeader.biHeight*hbmp.bmiHeader.biWidth*hbmp.bmiHeader.biBitCount/8;//bmp数据区大小
 				   
	hbmp.bmfHeader.bfType=((uint16_t)'M'<<8)+'B';//BM格式标志
	hbmp.bmfHeader.bfSize=bmpheadsize+hbmp.bmiHeader.biSizeImage;//整个bmp的大小
   	hbmp.bmfHeader.bfOffBits=bmpheadsize;//到数据区的偏移

	hbmp.RGB_MASK[0]=0X00F800;	 		//红色掩码
	hbmp.RGB_MASK[1]=0X0007E0;	 		//绿色掩码
	hbmp.RGB_MASK[2]=0X00001F;	 		//蓝色掩码

    const char *file_hello = MOUNT_POINT"/shot_188.jpg";
    FILE *SDfile = fopen(file_hello, "w");
  if(SDfile!=NULL)
  {
      ESP_LOGI(TAG, "Fileinto ok");
      camfb = esp_camera_fb_get();
    size_t err_0 = fwrite(&hbmp, 1, bmpheadsize, SDfile);
        memcpy(SDcolors, camfb->buf + 1 + (row * pixel_size1 * camera_width1), pixel_size1 * screen_width1);
        ESP_LOGI(TAG, "write File prepare");
    for (int row = 0; row < 10; row++)
    {
	 for (int i = 0; i < screen_width1; i++)
	 {
		Byte[index++] = LCD_BGR2RGB(SDcolors[i]);
	 }
    }
        size_t err_1 = fwrite(&Byte, 1, sizeof(Byte), f);
        ESP_LOGI(TAG, "writing File ");

    fclose(SDfile);
    
    ESP_LOGI(TAG, "closed File ");
    esp_camera_fb_return(camfb);
    camfb = NULL;
  }
}

**Comment by Alvin1Zhang** [comment]
Thanks for reporting. Would you please help provide more details as suggested in the [issue template](https://github.com/espressif/esp-idf/issues/new?assignees=&labels=&template=bug_report.md&title=)? Information like elf, sdk configuration, backtrace, log outputs, commit ID, hardware and etc. would help us debug further. Thanks.
