### ISSUE TITLE
BLE wifi provisioning example not working, cannot discover device from phone app. (IDFGH-6971)

### ISSUE THREAD

**Issue by listout** [espressif/esp-idf#8591]
## Environment

- Development Kit: ESP32-DevKitC
- Kit version (for WroverKit/PicoKit/DevKitC): v1
- Module or chip used: ESP32-WROOM-32
- IDF version (run ``git describe --tags`` to find it): v5.0-dev-2046-g5963de1caf
- Build System: idf.py
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it): 8.4.0
- Operating System: Linux
- (Windows only) environment type: [MSYS2 mingw32|ESP Command Prompt|Plain Command Prompt|PowerShell].
- Using an IDE?: No
- Power Supply: USB

## Problem Description

Wifi Provisioning example is not working when using BLE scheme. The QR code appears on my terminal but when I scan the QR code from the espressif app it says device not found. Manually scanning doesn't show the device either.

### Expected Behavior

Device is visible on the scan or can connect upon scanning the QR code

### Actual Behavior

Device is not visible on the scan and neither can I connect upon scanning the QR code.

### Steps to reproduce

1. Flash the `wifi_prov_mgr` example (choose the BLE scheme, default most cases).
2. Try scanning manually or the QR code from the **ESP BLE Prov** android/iphone app.

### Code to reproduce this issue

Code of the `wifi_prov_mgr` example.

## Debug Logs

N/A

## Other items if possible

N/A

**Comment by rahult-github** [comment]
Hi @listout ,

 I tried the commit id you mentioned and it is working as expected at my end. So, seems may be some setup issue at your end. Can you please:

1. Please confirm BT is turned ON when you attempt to provision from mobile ?
2. Once the device boots up and QR code is displayed, can you use a 3rd party scanner application on mobile ( e.g. nrfconnect)  that scans LE devices and see if ESP32 shows up in the list ?
3. Please share the monitor log to check further. 

Thanks,
 Rahul

**Comment by listout** [comment]
You're correct, working here too after a quick git pull.
