### ISSUE TITLE
Enable POSIX Thread Priority Scheduling API (IDFGH-6976)

### ISSUE THREAD

**Issue by ghost** [espressif/esp-idf#8594]
Hi, I'm working on a multi-platform project which has to set thread priority.
I would like to use C++ STL threads to stay platform-independent. 

I looked on [esp-idf/examples/cxx/pthread/main/cpp_pthread.cpp](https://github.com/espressif/esp-idf/blob/master/examples/cxx/pthread/main/cpp_pthread.cpp) example. I understand  that I should use `esp_pthread_set_cfg()` to set the thread priority just before creating the thread.

Unfortunately, this approach has 2 problems:

- I have to use a ESP-IDF specific API in my platform-independent code.
- `esp_pthread_set_cfg()` uses the global static `s_pthread_cfg_key` variable to communicate with `pthread_create()` which is not thread safe.

**Proposed solution**
In order to remain platform-independent, I would like to use POSIX Thread Priority Scheduling API declared in `pthread.h`.
```c
#if defined(_POSIX_THREAD_PRIORITY_SCHEDULING)
/* Dynamic Thread Scheduling Parameters Access, P1003.1c/Draft 10, p. 124 */
int	pthread_getschedparam (pthread_t __pthread, int *__policy,
			       struct sched_param *__param);
int	pthread_setschedparam (pthread_t __pthread, int __policy,
			       struct sched_param *__param);

/* Set Scheduling Priority of a Thread */
int	pthread_setschedprio (pthread_t thread, int prio);
#endif /* defined(_POSIX_THREAD_PRIORITY_SCHEDULING) */
```

It would require to define `_POSIX_THREAD_PRIORITY_SCHEDULING` which may be added to
[newlib-esp32/newlib/libc/include/sys/features.h](https://github.com/espressif/newlib-esp32/tree/esp_based_on_3_0_0/newlib/libc/include/sys/features.h):
```diff

/* ESP-specific */
#ifdef __XTENSA__

#define _POSIX_THREADS                          1
#define _POSIX_TIMEOUTS                         1
#define _POSIX_TIMERS                           1
#define _POSIX_MONOTONIC_CLOCK                  200112L
#define _POSIX_CLOCK_SELECTION                  200112L
+#define _POSIX_THREAD_PRIORITY_SCHEDULING       1
#define _UNIX98_THREAD_MUTEX_ATTRIBUTES         1

#endif /* __XTENSA__ */
```

And rebuild the xtensa toolchain.

The implementation is quite simple, see below:
```c
int pthread_getschedparam (pthread_t thread, int *policy, struct sched_param *param) {
    int ret;

    TaskHandle_t handle = pthread_find_handle(thread);
    if (!handle) {
        ret = ESRCH;
    } else {
#if configUSE_PREEMPTION
#if configUSE_TIME_SLICING
        *policy = SCHED_RR;
#else  /* configUSE_TIME_SLICING */
        *policy = SCHED_FIFO;
#endif /* configUSE_TIME_SLICING */
#else  /* configUSE_PREEMPTION */
        *policy = SCHED_OTHER;
#endif /* configUSE_PREEMPTION */
        param->sched_priority = uxTaskPriorityGet(handle);
        ret = 0;
    }

    return ret;
}

int pthread_setschedparam (pthread_t thread, int policy, struct sched_param *param) {
    int ret;

    TaskHandle_t handle = pthread_find_handle(thread);
    if (!handle) {
        ret = ESRCH;
    } else if ((configUSE_PREEMPTION  &&  configUSE_TIME_SLICING && (policy != SCHED_RR))
            || (configUSE_PREEMPTION  && !configUSE_TIME_SLICING && (policy != SCHED_FIFO))
            || (!configUSE_PREEMPTION && (policy != SCHED_OTHER)) ) {
        return EINVAL;
    } else {
        vTaskPrioritySet(handle, param->sched_priority);
        ret = 0;
    }

    return ret;
}

int pthread_setschedprio (pthread_t thread, int prio) {
    int ret;

    TaskHandle_t handle = pthread_find_handle(thread);
    if (!handle) {
        ret = ESRCH;
    } else {
        vTaskPrioritySet(handle, prio);
        ret = 0;
    }

    return ret;
}
```

What do you think about this approach? Would you have a better solution to stay platform-independent?

**Comment by 0xjakob** [comment]
@acrucifix-fluidra Thanks for the input! We'll take a look. But I want the OS people to take a look at this, too. It will require some time. Furthermore, we're thinking about integrating the [FreeRTOS POSIX](https://github.com/FreeRTOS/Lab-Project-FreeRTOS-POSIX) partial implementation, which has the `pthread_getschedparam` and `pthread_setschedparam` functions already; policy is ignored, though.

For the moment, I'm afraid the only workaround is to use defines, e.g. `#ifdef ESP_PLATFORM` or `#ifdef CONFIG_IDF_TARGET_ESP32`, etc. around the platform specific priority setting code.
