### ISSUE TITLE
Flash embedded data position (IDFGH-6980)

### ISSUE THREAD

**Issue by romocitto88** [espressif/esp-idf#8595]
Hi everyone,
I’ve added my binary file in that way:
[https://docs.platformio.org/en/latest/platforms/espressif32.html#embedding-binary-data](url)
I need to understand if there’s a way to set a priority of position in the “.rodata.embedded” section where automatically files go to with docs modality, so I can read the firmware.bin file and found everytime at the same address my binary file.

**Comment by o-marshmallow** [comment]
Hi @romocitto88 ,

Can you please provide us more details, the link you gave points to platform IO, are you using platform IO?
Which ESP-IDF version are you using?
Which module/board?


I am not aware of any way to prioritize or force the order of binaries in `.rodata.embedded` section, You cannot predict the address of your binary. However, you can retrieve its address at runtime thanks to the symbols generated, as shown in the doc:
```
extern const uint8_t private_pem_key_start[] asm("_binary_src_private_pem_key_start");
extern const uint8_t private_pem_key_end[] asm("_binary_src_private_pem_key_end");
```

What are you trying to achieve that needs you to have the code always at the same address?

**Comment by romocitto88** [comment]
Hi @ o-marshmallow,
Yes, I am using platformIO with version 4.2.1 esp-idf on a Wroom32 (size 8Mb) in a custom tab.
I need to store a binary file with a fixed size in my project.
The data in this file will be added later, by a third party, as needed (each time they will be blocks of the same size, until they fill the expected file size).
Therefore I would like to have the possibility to act directly on the .bin file without having to recompile the entire project every time, and therefore I have to know in advance the location of the file.
However it might happen that the logic of the project needs to be modified but with the current method (linked before), the location of the binary file is not guaranteed.

**Comment by igrr** [comment]
It sounds like defining a separate partition will be better suited for such customization. Partitions have a fixed address in Flash memory. You can read, write or erase partitions without modifying the application. This can be done either from PC (using `esptool.py` or `parttool.py`) or from the application itself.

You can read more about [partitions and partition tables in ESP-IDF](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/partition-tables.html) and about [partition APIs](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/storage/spi_flash.html#partition-table-api).
If you need to flash the partition with some predefined data at build time, you can check [this example](https://github.com/espressif/esp-idf/blob/1cb31e50943bb757966ca91ed7f4852692a5b0ed/examples/protocols/mqtt/ssl_ds/CMakeLists.txt#L13-L20).

**Comment by romocitto88** [comment]
Hi @igrr,
I forgot to mention that the fact that it wants to act directly on the .bin file is because this would allow you to make an OTA update with the latest data entered and possibly update those already present if necessary. Considering also that the hypothetical modified .bin file must then be inserted in a series of thousands of products.
Creating a dedicated partition for data would make it difficult to upgrade the partition itself, rather than being done by upgrading all with a single file.

**Comment by igrr** [comment]
Indeed, if you need to update an additional partition by OTA, the logic becomes a bit more complicated. You can try the combination of the two approaches:
* Embed the "initial" version of .bin file into the application.
* On startup, check if this is the first boot with this version of the application. If yes, copy the embedded data into a separate partition.
* Then, read and write from the separate partition.
* If an in-field customization is required, perform it on that separate partition.
* After an OTA update is complete, decide if the contents of the separate partition should be updated with the new .bin contents embedded into the updated application. If yes, overwrite that partition.

As @o-marshmallow has pointed out, there is no functionality for reserving some space in the application binary and modifying it later.
Besides, when the bootloader is loading the application it also verifies the application hash, comparing it to the hash appended to the application binary. If you modify the application binary image, the hash will no longer match.

**Comment by romocitto88** [comment]
The application hash may be recalculated based on the changes made, is it appendend at the end of the application binary?
In any case, if I understand, with this approach, I have to recompile the application binary image with new data every time. 

Before writing here, I also saw this page:
[https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/linker-script-generation.html#ldgen-linker-script-templatereste(url)
Is it possible to insert a new section with a fixed address with this script? So I could declare a byte array in a specific section.

**Comment by igrr** [comment]
> Is it possible to insert a new section with a fixed address with this script? So I could declare a byte array in a specific section.

No, there is no functionality in ESP-IDF to set specific section addresses in ldgen.

You can try to put your data into `.rodata_custom_desc` section using ldgen, this in practice will place it near the beginning of the binary at some offset. The offset _may_ change depending on IDF version, but it will be constant for different versions of your application.

**Comment by romocitto88** [comment]
Yes, I had thought about it, but for what I would like to do I would need at least 100kbyte of space, and I didn't think it was a good idea to put everything there. 
Last question before I finally give up: is there a way to tell the linker to use a custom file instead of [https://github.com/espressif/esp-idf/blob/5963de1caf/components/esp_system/ld/esp32/ sections.ld.in](url)?

Obviously by project, without modifying the ESP-IDF.

**Comment by igrr** [comment]
You can add another linked script by adding a `-T` linker flag from your component CMakeLists.txt. However I don't think this is going to help for the following reason.
If you want to reserve a chunk of space inside the application .rodata, you can put this chunk either in the beginning, somewhere in the middle, or in the end of .rodata.
Putting the reserved space in the beginning basically means using .rodata_custom_desc as I suggested above. Frankly I don't see a reason why 100kB there would be an issue, but anyway...
Putting the reserved space in the middle _and_ at a fixed address is not possible with the GNU linker. It doesn't know how to "punch holes" in sections.
Putting the reserved space at the end of .rodata is possible, but it's not going to be located at a fixed address. The address will depend on the size of .rodata.

**Comment by o-marshmallow** [comment]
> Hi @o-marshmallow , Yes, I am using platformIO with version 4.2.1 esp-idf on a Wroom32 (size 8Mb) in a custom board. I need to store a binary file with a fixed size in my project. The data in this file will be added later, by a third party, as needed (each time they will be blocks of the same size, until they fill the expected file size). Therefore I would like to have the possibility to act directly on the .bin file without having to recompile the entire project every time, and therefore I have to know the location of the file in advance. In this way the third party, with a customized tool, can be autonomous in entering the data. However it might happen that the logic of the project needs to be modified but with the current method (linked before), the location of the binary file is not guaranteed.

Side questions in case I missed anything. When you say  `I have to know the location of the file in advance`, do you mean the location in memory (e.g. `0x3fxxxxxx`) or the location in the flash?
In the first case, even if your binary is at the same address/location, you cannot write to these addresses, they are read-only. So, you (or third-party program) would still need to know the address of your binary file in SPI flash if you want to overwrite/update it.


What about using a named partiiton, as @igrr said, but for storing the absolute address of your binary file? (in SPI flash and/or in memory)
The third-party program would then be able to retrieve the address of your binary file by reading the named partition's data. When updating your program with OTA, as your binary file would still be part of your app partition, you will be able to overwrite any previous change on your binary file. However, you may need to adjust the named partition's content if the binary file's address changed.

**Comment by romocitto88** [comment]
@o-marshmallow I mean the location in memory, and I know that are read-only data. 
What I would like to do is open the compiled.bin file and permit to add block of data in a predefined section (e.g. from 0x3fxx0000 to 0x3fxx186A0, recalculating hash of the file) and then reuse the same compiled.bin modified.

Anyway I will try for now to put all in .rodata_custom_desc, but in the future it will be nice if user can add custom section in memory.

**Comment by negativekelvin** [comment]
Could you add a section to the bin image when converting from elf that would get mmapped to a fixed address?

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, feel free to reopen.
