### ISSUE TITLE
The IDF websocket server does not handle multiple simultaneous connections (at least the example doesn't) (IDFGH-7162)

### ISSUE THREAD

**Issue by pjsg** [espressif/esp-idf#8596]
## Environment

- Development Kit:      Random ESP32 board
- Module or chip used:  ESP32-DOWDQ6
- IDF version (run ``git describe --tags`` to find it):
    v4.4-beta1-284-gd83021a6e8
- Build System:         idf.py
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it):
    xtensa-esp32-elf-gcc (crosstool-NG esp-2021r2) 8.4.0
- Operating System:     Linux
- (Windows only) environment type: [MSYS2 mingw32|ESP Command Prompt|Plain Command Prompt|PowerShell].
- Using an IDE?: No
- Power Supply:         USB
## Problem Description

I'm running the IDF4.4 (commit d83021a6e8) and running the unmodified example `examples/protocols/http_server/ws_echo_server`.

To test it, I'm using `websocat` (from https://github.com/vi/websocat ) to make a connection to the websocket server and interact with it. In particular, I have this script (called `dosend` -- and this particular board is at 192.168.1.131)

```
#!/bin/bash

(echo foo; sleep 1; echo bardsfsdkfsdflskf; sleep 1; echo djfsldkjfskljfslkjfsdlkjfsldkjfklsjfslkf) | websocat ws://192.168.1.131/ws 
```

This script works fine *provided* that I only run one copy at a time. If I run four copies at the same time, then I get log messages from the ESP32 like:

```
W (34089) httpd_ws: httpd_ws_recv_frame: WS frame is not properly masked.
E (34089) ws_echo_server: httpd_ws_recv_frame failed to get frame len with 259
```
I launch four copies with the command (on my linux laptop)
```
./dosend & ./dosend & ./dosend & ./dosend &
```
I originally found this in an application that I was building, but the issue reproduces in the provided echo example.

## Other items if possible

Since this is just your sample code, I'm not providing any other information here

**Comment by Alvin1Zhang** [comment]
Thanks for reporting.

**Comment by pjsg** [comment]
Just to be clear, are you saying that the example is broken and that the IDF core code is correct?

**Comment by chegewara** [comment]
As far as i know it works perfectly fine, just example is simplified and does not show how to use multi connection.Similar ble examples does not show all use cases etc. Of course i may be wrong. 

My suggestion is to add log after this line to see value of `resp_arg->fd`:
https://github.com/espressif/esp-idf/blob/master/examples/protocols/http_server/ws_echo_server/main/ws_echo_server.c#L59

**Comment by ESP-YJM** [comment]
@pjsg Could you please try this patch. I test it with your tool and it is ok.
[ws_server.zip](https://github.com/espressif/esp-idf/files/8494889/ws_server.zip)

**Comment by pjsg** [comment]
Thanks for this. I'll try and test it over the next couple of days.

**Comment by pjsg** [comment]
I'm sorry that it took me so long -- but that patch works great and fixes my problem (the Lua nodemcu firmware). 

When will it get merged?

**Comment by Alvin1Zhang** [comment]
Thanks for sharing the updates, we have a fix under internal reviewing, and the issue will close automatically once the fix is available on GitHub, thanks.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting and sorry for slow turnaround, fix is available at https://github.com/espressif/esp-idf/commit/b3ab2c64d42483d4d8cda2684f62b482d4108f3d. Feel free to reopen.

**Comment by AnkDhage** [comment]
Even I am trying to handle diff channels thru idf ws server, it does not work

**Comment by ESP-YJM** [comment]
@AnkDhage Do your problem is the same as the issue mentioned? Could you give a detailed description about it?
