### ISSUE TITLE
How does the Bluetooth server determine whether the connected client is an Android device or an apple device？ (IDFGH-6985)

### ISSUE THREAD

**Issue by fan183579** [espressif/esp-idf#8604]
When using "gatt_service" to connect the client, I have to judge whether the client is an Android device or an apple device because of some needs, but I can't find the relevant fields. How can I know?

**Comment by moefear85** [comment]
this question belongs on the [esp forum](https://www.esp32.com/)

**Comment by fan183579** [comment]
使用的ESP32-C3芯片，IDF是4.4的，参考的是gatt_service例程

**Comment by fan183579** [comment]
在使用8080驱动显示屏的时候，过一段时间就会出现显示错位的情况出现，使用的ESP32-S3-DevKitC-1开发板，LCD驱动IC为hx8369a，使用LCD下LVGL例程，按照现有驱动自行改写的驱动代码，没有找到出现这个情况的原因

**Comment by esp-cjh** [comment]
We have no way to get the device type of the master. But you can use custom GATT service to achieve this after connected.
Such as a characteristic which is writable and Client write the characteristic value to tell server it's device type.

**Comment by fan183579** [comment]
ESP论坛并没有人回复




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "espressif/esp-idf"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月20日(星期天) 凌晨4:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [espressif/esp-idf] How does the Bluetooth server determine whether the connected client is an Android device or an apple device？ (IDFGH-6985) (Issue #8604)





 
this question belongs on the esp forum
  
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, feel free to reopen.
