### ISSUE TITLE
idf.py broken on v4.4 (IDFGH-7010)

### ISSUE THREAD

**Issue by readmodifywrite** [espressif/esp-idf#8627]
ESP-IDF v4.4

Linux

On the hello world example:
idf.py set-target esp32

Adding "set-target"'s dependency "fullclean" to list of commands with default set of options.
Executing action: fullclean
Build directory '/home/jeremy/JEREMY/SAPPHIRE/chromatron/src/hal/esp-idf/examples/get-started/hello_world/build' not found. Nothing to clean.
Executing action: set-target
Set Target to: esp32, new sdkconfig created. Existing sdkconfig renamed to sdkconfig.old.
Running cmake in directory /home/jeremy/JEREMY/SAPPHIRE/chromatron/src/hal/esp-idf/examples/get-started/hello_world/build
Executing "cmake -G 'Unix Makefiles' -DPYTHON_DEPS_CHECKED=1 -DESP_PLATFORM=1 -DIDF_TARGET=esp32 -DCCACHE_ENABLE=0 /home/jeremy/JEREMY/SAPPHIRE/chromatron/src/hal/esp-idf/examples/get-started/hello_world"...
-- Found Git: /usr/bin/git (found version "2.25.1") 
-- Component directory /home/jeremy/JEREMY/SAPPHIRE/chromatron/src/hal/esp-idf/components/aws_iot does not contain a CMakeLists.txt file. No component will be added
-- Component directory /home/jeremy/JEREMY/SAPPHIRE/chromatron/src/hal/esp-idf/components/micro-ecc does not contain a CMakeLists.txt file. No component will be added
-- Component directory /home/jeremy/JEREMY/SAPPHIRE/chromatron/src/hal/esp-idf/components/smartconfig_ack does not contain a CMakeLists.txt file. No component will be added
-- The C compiler identification is GNU 8.4.0
-- The CXX compiler identification is GNU 8.4.0
-- The ASM compiler identification is GNU
-- Found assembler: /home/jeremy/.espressif/tools/xtensa-esp32-elf/esp-2021r2-8.4.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc
-- Check for working C compiler: /home/jeremy/.espressif/tools/xtensa-esp32-elf/esp-2021r2-8.4.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc
-- Check for working C compiler: /home/jeremy/.espressif/tools/xtensa-esp32-elf/esp-2021r2-8.4.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /home/jeremy/.espressif/tools/xtensa-esp32-elf/esp-2021r2-8.4.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-g++
-- Check for working CXX compiler: /home/jeremy/.espressif/tools/xtensa-esp32-elf/esp-2021r2-8.4.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Building ESP-IDF components for target esp32
-- Project sdkconfig file /home/jeremy/JEREMY/SAPPHIRE/chromatron/src/hal/esp-idf/examples/get-started/hello_world/sdkconfig
Traceback (most recent call last):
  File "/home/jeremy/JEREMY/SAPPHIRE/chromatron/src/hal/esp-idf/tools/kconfig_new/confgen.py", line 640, in <module>
    main()
  File "/home/jeremy/JEREMY/SAPPHIRE/chromatron/src/hal/esp-idf/tools/kconfig_new/confgen.py", line 260, in main
    config = kconfiglib.Kconfig(args.kconfig)
  File "/home/jeremy/JEREMY/SAPPHIRE/chromatron/src/hal/esp-idf/tools/kconfig_new/kconfiglib.py", line 653, in __init__
    self._parse_block(None,           # end_token
  File "/home/jeremy/JEREMY/SAPPHIRE/chromatron/src/hal/esp-idf/tools/kconfig_new/kconfiglib.py", line 1632, in _parse_block
    self._parse_block(_T_ENDMENU,
  File "/home/jeremy/JEREMY/SAPPHIRE/chromatron/src/hal/esp-idf/tools/kconfig_new/kconfiglib.py", line 1584, in _parse_block
    prev_node = self._parse_block(None,            # end_token
  File "/home/jeremy/JEREMY/SAPPHIRE/chromatron/src/hal/esp-idf/tools/kconfig_new/kconfiglib.py", line 1584, in _parse_block
    prev_node = self._parse_block(None,            # end_token
  File "/home/jeremy/JEREMY/SAPPHIRE/chromatron/src/hal/esp-idf/tools/kconfig_new/kconfiglib.py", line 1632, in _parse_block
    self._parse_block(_T_ENDMENU,
  File "/home/jeremy/JEREMY/SAPPHIRE/chromatron/src/hal/esp-idf/tools/kconfig_new/kconfiglib.py", line 1632, in _parse_block
    self._parse_block(_T_ENDMENU,
  File "/home/jeremy/JEREMY/SAPPHIRE/chromatron/src/hal/esp-idf/tools/kconfig_new/kconfiglib.py", line 1571, in _parse_block
    self._parse_properties(node, visible_if_deps)
  File "/home/jeremy/JEREMY/SAPPHIRE/chromatron/src/hal/esp-idf/tools/kconfig_new/kconfiglib.py", line 1744, in _parse_properties
    while self._next_line():
  File "/home/jeremy/JEREMY/SAPPHIRE/chromatron/src/hal/esp-idf/tools/kconfig_new/kconfiglib.py", line 1199, in _next_line
    self._tokenize()
  File "/home/jeremy/JEREMY/SAPPHIRE/chromatron/src/hal/esp-idf/tools/kconfig_new/kconfiglib.py", line 1287, in _tokenize
    self._parse_error("expected keyword as first token")
  File "/home/jeremy/JEREMY/SAPPHIRE/chromatron/src/hal/esp-idf/tools/kconfig_new/kconfiglib.py", line 2165, in _parse_error
    raise KconfigSyntaxError(
kconfiglib.KconfigSyntaxError: /home/jeremy/JEREMY/SAPPHIRE/chromatron/src/hal/esp-idf/components/esp_hw_support/Kconfig:16: Couldn't parse '            resource "./port/$IDF_TARGET/Kconfig.mac"': expected keyword as first token
CMake Error at /home/jeremy/JEREMY/SAPPHIRE/chromatron/src/hal/esp-idf/tools/cmake/kconfig.cmake:266 (message):
  Failed to run confgen.py
  (/home/jeremy/.espressif/python_env/idf4.4_py3.8_env/bin/python;/home/jeremy/JEREMY/SAPPHIRE/chromatron/src/hal/esp-idf/tools/kconfig_new/confgen.py;--kconfig;/home/jeremy/JEREMY/SAPPHIRE/chromatron/src/hal/esp-idf/Kconfig;--sdkconfig-rename;/home/jeremy/JEREMY/SAPPHIRE/chromatron/src/hal/esp-idf/sdkconfig.rename;--config;/home/jeremy/JEREMY/SAPPHIRE/chromatron/src/hal/esp-idf/examples/get-started/hello_world/sdkconfig;--env-file;/home/jeremy/JEREMY/SAPPHIRE/chromatron/src/hal/esp-idf/examples/get-started/hello_world/build/config.env).
  Error 1
Call Stack (most recent call first):
  /home/jeremy/JEREMY/SAPPHIRE/chromatron/src/hal/esp-idf/tools/cmake/build.cmake:528 (__kconfig_generate_config)
  /home/jeremy/JEREMY/SAPPHIRE/chromatron/src/hal/esp-idf/tools/cmake/project.cmake:378 (idf_build_process)
  CMakeLists.txt:6 (project)

-- Configuring incomplete, errors occurred!
See also "/home/jeremy/JEREMY/SAPPHIRE/chromatron/src/hal/esp-idf/examples/get-started/hello_world/build/CMakeFiles/CMakeOutput.log".
cmake failed with exit code 1

I am also getting failures running idf.py menuconfig on the idf_as_lib project - the generated makefile doesn't contain the menuconfig option.

All of this works great on 3.3.5.

**Comment by readmodifywrite** [comment]
Re-cloned (I guess just going a pull/submodule update won't cut it from 3.3.5).  hello world builds now, but idf_as_lib still won't generate a makefile target for menuconfig.

**Comment by readmodifywrite** [comment]
Now it is broken on 3.3.5 as well: 

Note: You are using Python 3.8.10. Python 3 support is new, please report any problems you encounter. Search for 'Setting the Python Interpreter' in the ESP-IDF docs if you want to use Python 2.7.
Checking Python dependencies...
Python requirements from /home/jeremy/JEREMY/SAPPHIRE/chromatron/src/hal/esp-idf/requirements.txt are satisfied.
Running cmake in directory /home/jeremy/JEREMY/SAPPHIRE/chromatron/src/hal/esp-idf/examples/build_system/cmake/idf_as_lib/build
Executing "cmake -G 'Unix Makefiles' -DPYTHON_DEPS_CHECKED=1 -DESP_PLATFORM=1 --warn-uninitialized /home/jeremy/JEREMY/SAPPHIRE/chromatron/src/hal/esp-idf/examples/build_system/cmake/idf_as_lib"...
Warn about uninitialized values.
-- The C compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found Git: /usr/bin/git (found version "2.25.1") 
-- IDF_TARGET not set, using default target: esp32
-- Building for target esp32
-- Component names: soc log heap xtensa-debug-module app_trace freertos vfs newlib esp_ringbuf driver esp_event ethernet mbedtls micro-ecc efuse bootloader_support partition_table app_update spi_flash nvs_flash lwip tcpip_adapter pthread smartconfig_ack wpa_supplicant espcoredump esp32 cxx bootloader esptool_py
-- Component paths: /home/jeremy/JEREMY/SAPPHIRE/chromatron/src/hal/esp-idf/components/soc;/home/jeremy/JEREMY/SAPPHIRE/chromatron/src/hal/esp-idf/components/log;/home/jeremy/JEREMY/SAPPHIRE/chromatron/src/hal/esp-idf/components/heap;/home/jeremy/JEREMY/SAPPHIRE/chromatron/src/hal/esp-idf/components/xtensa-debug-module;/home/jeremy/JEREMY/SAPPHIRE/chromatron/src/hal/esp-idf/components/app_trace;/home/jeremy/JEREMY/SAPPHIRE/chromatron/src/hal/esp-idf/components/freertos;/home/jeremy/JEREMY/SAPPHIRE/chromatron/src/hal/esp-idf/components/vfs;/home/jeremy/JEREMY/SAPPHIRE/chromatron/src/hal/esp-idf/components/newlib;/home/jeremy/JEREMY/SAPPHIRE/chromatron/src/hal/esp-idf/components/esp_ringbuf;/home/jeremy/JEREMY/SAPPHIRE/chromatron/src/hal/esp-idf/components/driver;/home/jeremy/JEREMY/SAPPHIRE/chromatron/src/hal/esp-idf/components/esp_event;/home/jeremy/JEREMY/SAPPHIRE/chromatron/src/hal/esp-idf/components/ethernet;/home/jeremy/JEREMY/SAPPHIRE/chromatron/src/hal/esp-idf/components/mbedtls;/home/jeremy/JEREMY/SAPPHIRE/chromatron/src/hal/esp-idf/components/micro-ecc;/home/jeremy/JEREMY/SAPPHIRE/chromatron/src/hal/esp-idf/components/efuse;/home/jeremy/JEREMY/SAPPHIRE/chromatron/src/hal/esp-idf/components/bootloader_support;/home/jeremy/JEREMY/SAPPHIRE/chromatron/src/hal/esp-idf/components/partition_table;/home/jeremy/JEREMY/SAPPHIRE/chromatron/src/hal/esp-idf/components/app_update;/home/jeremy/JEREMY/SAPPHIRE/chromatron/src/hal/esp-idf/components/spi_flash;/home/jeremy/JEREMY/SAPPHIRE/chromatron/src/hal/esp-idf/components/nvs_flash;/home/jeremy/JEREMY/SAPPHIRE/chromatron/src/hal/esp-idf/components/lwip;/home/jeremy/JEREMY/SAPPHIRE/chromatron/src/hal/esp-idf/components/tcpip_adapter;/home/jeremy/JEREMY/SAPPHIRE/chromatron/src/hal/esp-idf/components/pthread;/home/jeremy/JEREMY/SAPPHIRE/chromatron/src/hal/esp-idf/components/smartconfig_ack;/home/jeremy/JEREMY/SAPPHIRE/chromatron/src/hal/esp-idf/components/wpa_supplicant;/home/jeremy/JEREMY/SAPPHIRE/chromatron/src/hal/esp-idf/components/espcoredump;/home/jeremy/JEREMY/SAPPHIRE/chromatron/src/hal/esp-idf/components/esp32;/home/jeremy/JEREMY/SAPPHIRE/chromatron/src/hal/esp-idf/components/cxx;/home/jeremy/JEREMY/SAPPHIRE/chromatron/src/hal/esp-idf/components/bootloader;/home/jeremy/JEREMY/SAPPHIRE/chromatron/src/hal/esp-idf/components/esptool_py
CMake Error at /home/jeremy/JEREMY/SAPPHIRE/chromatron/src/hal/esp-idf/tools/cmake/idf_functions.cmake:205 (message):
  Internal error, toolchain has not been set correctly by project (or an
  invalid CMakeCache.txt file has been generated somehow)
Call Stack (most recent call first):
  /home/jeremy/JEREMY/SAPPHIRE/chromatron/src/hal/esp-idf/tools/cmake/idf_functions.cmake:374 (idf_verify_environment)
  CMakeLists.txt:21 (idf_import_components)


-- Configuring incomplete, errors occurred!
See also "/home/jeremy/JEREMY/SAPPHIRE/chromatron/src/hal/esp-idf/examples/build_system/cmake/idf_as_lib/build/CMakeFiles/CMakeOutput.log".
cmake failed with exit code 1



So, the update to 4.4 somehow also broke things for 3.3.5.  Also tried 4.2.3, same story.

Not sure what happened here, the ESP-IDF used to be pretty solid.

**Comment by igrr** [comment]
Just to check, are you cleaning the build directory (`idf.py fullclean`) and re-running `. $IDF_PATH/export.sh` when switching between different IDF versions?

To troubleshoot `hello_world` in v4.4 first, could you please run:
```
/home/jeremy/.espressif/python_env/idf4.4_py3.8_env/bin/python -m pip freeze | grep kconfiglib
```
and post the output here?

Regarding idf_as_lib and menuconfig, my understanding is that idf.py only works for ESP-IDF projects, not for custom CMake projects. You can invoke menuconfig target, just not via idf.py. The following works of me in idf_as_lib example on v4.4:
```
cmake -B build -DCMAKE_TOOLCHAIN_FILE=$IDF_PATH/tools/cmake/toolchain-esp32.cmake -DTARGET=esp32 -GNinja
cmake -B build --target menuconfig
```

**Comment by readmodifywrite** [comment]
I have not only tried from a clean directory, but also from a fresh clone on a fresh shell and deleted .espressif from my home dir.

Let's focus on idf_as_lib, since that's what I'm actually trying to accomplish.  Hello world does work on a fresh clone (no idea why it can't handle switching, but I can live with a fresh clone, I don't need to change SDKs often).

idf.py menuconfig works fine on idf_as_lib in 3.3.5.  Is this change documented somewhere?

re:
cmake -B build -DCMAKE_TOOLCHAIN_FILE=$IDF_PATH/tools/cmake/toolchain-esp32.cmake -DTARGET=esp32 -GNinja

This fails: 
Make Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
-- Configuring incomplete, errors occurred!

Was the standard make support dropped?  I am aware of Ninja's existence however I would really prefer not to add another build tool on top of what is already a pretty brittle stack.

**Comment by igrr** [comment]
> idf.py menuconfig works fine on idf_as_lib in 3.3.5. Is this change documented somewhere?

I'm sorry that I don't remember all the details, but my understanding is that using idf.py with custom CMake projects was never officially supported, it just so happened to work in 3.3.x release. I found these comments from a colleague who had been working on the CMake build system at that time: https://github.com/espressif/esp-idf/issues/3573#issuecomment-499405688

> Was the standard make support dropped? I am aware of Ninja's existence however I would really prefer not to add another build tool on top of what is already a pretty brittle stack. If I remove the -GNinja, I get the same error.

Make (as a build system CMake generates makefiles for) is supported. I tried it with -G "Unix Makefiles" as generator and it worked:
```
cmake -B build -DCMAKE_TOOLCHAIN_FILE=$IDF_PATH/tools/cmake/toolchain-esp32.cmake -DTARGET=esp32 -G "Unix Makefiles"
make -C build menuconfig
(or)
cmake --build build --target menuconfig
```

**Comment by readmodifywrite** [comment]
Ok, those commands work.

However, the new IDF apparently has a dependency on sdkconfig.h, which is not generated in the idf_as_lib build.  Is there some command which generates this file?

**Comment by readmodifywrite** [comment]
Ok, I found sdkconfig.h.  It is created by menuconfig.  When you run build.sh, it deletes it (because it deletes the enclosing folder) and does not generate a new copy.

How are we supposed to be using idf_as_lib?

**Comment by igrr** [comment]
Could you please check the following readme sections? Do any of the steps fail in your environment?

* Building: https://github.com/espressif/esp-idf/blob/master/examples/build_system/cmake/idf_as_lib/README.md#building-this-example

* Flashing: https://github.com/espressif/esp-idf/blob/master/examples/build_system/cmake/idf_as_lib/README.md#flashing-and-running-this-example

* Configuring: https://github.com/espressif/esp-idf/blob/master/examples/build_system/cmake/idf_as_lib/README.md#configuring-this-example

> I found sdkconfig.h. It is created by menuconfig. When you run build.sh, it deletes it (because it deletes the enclosing folder) and does not generate a new copy.

Do you mean that the build doesn't finish successfully when you run build-esp32.sh script? If yes, could you please copy the full build log and attach it here?

**Comment by readmodifywrite** [comment]
Ok, tried this, from a fresh clone.
build-esp32.sh does not work, as I do not have Ninja (and do not want it).
build.sh does work - in that it builds something (but not the thing it used to build in 3.3.x).

The issue is in the generated output.  In 3.3.x, idf_as_lib generated a series of .a library files that, combined with the headers, can be linked into another project.  What I am getting in 4.4 is a single .elf binary and no libraries.

I can get the headers from the component folders, however, most of them have a dependency on sdkconfig.h which is only generated by menuconfig and is deleted by build.sh.  This is inconvenient, but I can work around it.  This is a new feature - 3.3.x does not have this issue either.

Overall, it looks like the idf_as_lib example has completely changed and is  no longer intended to be used to generate .a libraries.  What is it supposed to be for, if not to build a library?  Is there another (supported) way to build the ESP-IDF into a library for inclusion with another project (that already has its own build system)?

**Comment by igrr** [comment]
> build-esp32.sh does not work, as I do not have Ninja (and do not want it).

Alright, understood that you don't want to use Ninja. We list it as a prerequisite in the [getting started guide](https://docs.espressif.com/projects/esp-idf/en/v4.4/esp32/get-started/linux-setup.html#install-prerequisites), therefore this script uses Ninja. If you'd like to use Make, please modify the script as follows:
<details>
<summary>build-esp32.sh.diff</summary>

```diff
diff --git a/examples/build_system/cmake/idf_as_lib/build-esp32.sh b/examples/build_system/cmake/idf_as_lib/build-esp32.sh
index c30f83226d6..b4145cb3727 100755
--- a/examples/build_system/cmake/idf_as_lib/build-esp32.sh
+++ b/examples/build_system/cmake/idf_as_lib/build-esp32.sh
@@ -1,4 +1,4 @@
 #!/usr/bin/env bash
 rm -rf build && mkdir build && cd build
-cmake .. -DCMAKE_TOOLCHAIN_FILE=$IDF_PATH/tools/cmake/toolchain-esp32.cmake -DTARGET=esp32 -GNinja
+cmake .. -DCMAKE_TOOLCHAIN_FILE=$IDF_PATH/tools/cmake/toolchain-esp32.cmake -DTARGET=esp32
 cmake --build .
```
</details>

After this change I think build-esp32.sh should work. You can also see that after running build-esp32.sh, sdkconfig.h file will be generated after the build (even if you don't invoke `menuconfig` target):
```
$ find build -name sdkconfig.h
build/config/sdkconfig.h
```
Of course, build-esp32.sh is only provided as an example to show the list of commands you can invoke to build the project. You don't need to delete the build directory every time, you can use CMake generator you prefer, and so on.

> Overall, it looks like the idf_as_lib example has completely changed and is no longer intended to be used to generate .a libraries. What is it supposed to be for, if not to build a library? Is there another (supported) way to build the ESP-IDF into a library for inclusion with another project (that already has its own build system)?

idf_as_lib is intended to demonstrate how to include ESP-IDF as a CMake library into another (custom) CMake project. It shows to use ESP-IDF build system API described in [this docs section](https://docs.espressif.com/projects/esp-idf/en/v4.4/esp32/api-guides/build-system.html#using-esp-idf-in-custom-cmake-projects).

If you take a look at examples/build_system/cmake/idf_as_lib/CMakeLists.txt and ignore the non-essential parts related to "host build", you'll see the following steps:

```cmake
# This is your usual CMake project boilerplate...
cmake_minimum_required(VERSION 3.5)
project(idf_as_lib C)

# IDF-specific: Include for ESP-IDF build system functions
include($ENV{IDF_PATH}/tools/cmake/idf.cmake)

# IDF-specific: Call ESP-IDF build system API to define IDF library targets
idf_build_process(esp32
                COMPONENTS esp32 freertos esptool_py
                SDKCONFIG ${CMAKE_CURRENT_LIST_DIR}/sdkconfig
                BUILD_DIR ${CMAKE_BINARY_DIR})

# This is your usual CMake project boilerplate...
set(elf_file ${CMAKE_PROJECT_NAME}.elf)
add_executable(${elf_file} main.c)

# Here we tell CMake that your executable target depends on these three IDF libraries.
# target_link_libraries CMake function propagates dependencies, so your executable target
# will get the public include directories and linker flags from these IDF libraries.
target_link_libraries(${elf_file} idf::esp32 idf::freertos idf::spi_flash)

# IDF-specific. If you want to run the program on an ESP32, you probably need to generate a .bin file
# out of the program .elf file:
idf_build_executable(${elf_file})
```

This is very similar to how you would include any other CMake library into your CMake project:
```cmake
# This is your usual CMake project boilerplate...
cmake_minimum_required(VERSION 3.5)
project(my_project C)

# Let CMake know there is a library you want to use:
add_subdirectory(another_lib)

# This is your usual CMake project boilerplate...
set(elf_file ${CMAKE_PROJECT_NAME}.elf)
add_executable(${elf_file} main.c)

# This is where we add a dependency from executable target to the library
target_link_libraries(${elf_file} another_lib)
```

Basically, instead of `add_subdirectory` (or `include` for CMake modules) you need to include `idf.cmake` and then call `idf_build_process` to define the library targets. After that, `target_link_libraries` works just as  it would work in a standard CMake project, propagating public include directories and linker flags from library target to the executable.

This example demonstrates the standard approach in modern CMake — adding self-contained library targets to the project and adding dependencies between targets using target_link_libraries.

If you are interested in the static libraries, they are still built by this example. If you run `find build -name '*.a'` after the build is done, you can see the list. The static library for each `component` ends up being built in `build/esp-idf/${component}/lib${component}.a`. However, as long as you use `target_link_libraries` to attach the IDF library targets to your CMake executable or library target, you don't need to care about the locations of static libraries. CMake will propagate the dependencies automatically.

**Comment by readmodifywrite** [comment]
Ok, that was very helpful, thanks!

I got the libraries and such straightened out, and can build and sort of run my project.  I'm sad to say though that I probably will have a lot more bug reports incoming.  4.x is frankly a mess, I might have to stay on 3.3.5.  It's unfortunate support has been dropped.
