### ISSUE TITLE
Core dump not saving to flash (IDF 3.3.5) (IDFGH-7011)

### ISSUE THREAD

**Issue by readmodifywrite** [espressif/esp-idf#8628]
I've enabled core dump to flash on ESP-IDF 3.3.5 and tested it by forcing a kernel panic (null pointer access and also tried an integer divide by 0).  I'm getting the appropriate Guru Meditation Error on the UART console.  However, when I run esp_partition_find_first on the core dump partition, it returns null.

I need to be able to access the partition via wifi to debug devices in the field - I can't plug in to the UART.  The UART core dump mode does work however, it's just not useful since I will not have access to the UART in the field.

**Comment by igrr** [comment]
Hi @readmodifywrite, could you please attach your sdkconfig file, the partition table (if you are using a custom one) and the code snippet where you are calling `esp_partition_find_first`?

Another note, according to ESP-IDF support period policy, release/v3.3 maintenance period has expired at the beginning of March and this version is now End of Life. We do not plan to provide support for release/v3.3 branch anymore.

**Comment by readmodifywrite** [comment]
See attached.  I renamed sdk_config to a .txt file so github would accept it.

`const esp_partition_t *pt = esp_partition_find_first( ESP_PARTITION_TYPE_DATA, ESP_PARTITION_SUBTYPE_DATA_COREDUMP, "coredump" );

    if( pt == NULL ){

        trace_printf( "wow no core dump, ok.\r\n" );

        return 0;
    }`

I am aware 3.3 is no longer supported, however, I was unable to update to 4.x as the menuconfig option is broken on the idf_as_lib project on 4.x.

[partitions_singleapp_coredump.csv](https://github.com/espressif/esp-idf/files/8326408/partitions_singleapp_coredump.csv)
[sdkconfig.txt](https://github.com/espressif/esp-idf/files/8326409/sdkconfig.txt)

**Comment by igrr** [comment]
Thanks for the information, the config looks correct. Could you check if the partition table in flash is up to date? The 2nd stage bootloader logs the partition list on startup:
```
I (57) boot: Partition Table:
I (61) boot: ## Label            Usage          Type ST Offset   Length
I (68) boot:  0 nvs              WiFi data        01 02 00009000 00006000
I (76) boot:  1 phy_init         RF data          01 01 0000f000 00001000
I (83) boot:  2 factory          factory app      00 00 00010000 00100000
I (91) boot:  3 coredump         Unknown data     01 03 00110000 00010000
I (98) boot: End of partition table
```

You can also add this code snippet to the app to debug where the issue is:
```
    esp_partition_iterator_t it = esp_partition_find(ESP_PARTITION_TYPE_DATA, ESP_PARTITION_SUBTYPE_ANY, NULL);
    for (; it != NULL; it = esp_partition_next(it)) {
        const esp_partition_t *part = esp_partition_get(it);
        printf("- partition '%s' (%d:%d) at offset 0x%x with size 0x%x\n", part->label, part->type, part->subtype, part->address, part->size);
    }
    esp_partition_iterator_release(it);
```

Here's the output with IDF v3.3.5 and hello_world example, modified as above and with `CONFIG_ESP32_ENABLE_COREDUMP_TO_FLASH=y` enabled.
```
- partition 'nvs' (1:2) at offset 0x9000 with size 0x6000
- partition 'phy_init' (1:1) at offset 0xf000 with size 0x1000
- partition 'coredump' (1:3) at offset 0x110000 with size 0x10000
```

**Comment by readmodifywrite** [comment]
Ah, that was it: I wasn't updating the binary partition table itself.

Thanks!
