### ISSUE TITLE
[TW#14487] volatile' qualifier from pointer target type

### ISSUE THREAD

**Issue by ESP32DE** [espressif/esp-idf#864]
```
void vPortReleaseTaskMPUSettings( xMPU_SETTINGS *xMPUSettings )
{
	/* If task has live floating point registers somewhere, release them */
	_xt_coproc_release( xMPUSettings->coproc_area );
}

```

[passing argument 1 of '_xt_coproc_release' discards '
volatile' qualifier from pointer target type [-Wdiscarded-qualifiers]](https://github.com/espressif/esp-idf/blob/master/components/freertos/port.c#L271)

suggestion:
**Typecast** or make `coproc_area` a **volatile field** as well

best wishes
rudi ;-)

**Comment by projectgus** [comment]
Hi @ESP32DE,

Thanks for reporting this. Sorry it's taken us a while to look into it.

[coproc_area is a volatile pointer type](https://github.com/espressif/esp-idf/blob/master/components/freertos/include/freertos/portmacro.h#L321) and compatible with `volatile void *` so I'm not sure why you were seeing this warning. We're not able to reproduce on the current IDF & toolchain, maybe this was in an older version?

Feel free to reopen if there are steps to reproduce that we are not setting.

Thanks,

Angus
