### ISSUE TITLE
SPI master example bug (LCD) (IDFGH-7034)

### ISSUE THREAD

**Issue by martaaay** [espressif/esp-idf#8652]
## Environment

- Development Kit:      ESP_WROVER_KIT_v4.1
- Kit version: 4.1
- Module or chip used:  ESP32-WROVER-E
- IDF version: v5.0-dev-2169-gc1bcb8756b
- Build System:        idf.py
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it):
xtensa-esp32-elf-gcc (crosstool-NG esp-2021r2-patch3) 8.4.0
- Operating System:   macOS
- Using an IDE?: No
- Power Supply:  USB

## Problem Description

This is a "right answer but for the wrong reason" kind of bug.

In the examples/peripherals/spi_master/lcd/main/spi_master_example_main.c file, in lcd_get_id two spi_device_polling_transmits are called (one is in lcd_cmd), but because these are two separate calls to polling transmits, the SPI CS line is pulled high in between the command send to SPI and the data receive (as viewed with a logic analyzer). On a ILI9341 LCD chip, pulling CS high between command write and response read apparently causes the read to lose connection with the write, and thus to return 0 (nothing on the MISO line). Now, it turns out the ID on the ILI9341 chip does happen to be 0, but this call isn't actually receiving 0 for that reason. So, if you were to adapt this call to read from other registers (as I did), you'll always receive 0 and sit scratching your head for 3 days :). I wrote a function called lcd_get_register (see below) that does the correct thing by using the SPI_TRANS_CS_KEEP_ACTIVE flag to keep CS low which requires the SPI bus to be acquired (I adjusted the lcd_cmd function to help out):

```
void lcd_cmd(spi_device_handle_t spi, const uint8_t cmd, bool keep_cs_active)
{   
    esp_err_t ret;
    spi_transaction_t t;
    memset(&t, 0, sizeof(t));       //Zero out the transaction
    t.length=8;                     //Command is 8 bits
    t.tx_buffer=&cmd;               //The data is the cmd itself
    t.user=(void*)0;                //D/C needs to be set to 0
    if (keep_cs_active) {
      t.flags = SPI_TRANS_CS_KEEP_ACTIVE;
    }
    ret=spi_device_polling_transmit(spi, &t);  //Transmit!
    assert(ret==ESP_OK);            //Should have had no issues.
} 

uint32_t lcd_get_register(spi_device_handle_t spi, const uint8_t cmd, const uint8_t num_bytes)
{
    spi_device_acquire_bus(spi, portMAX_DELAY);
    lcd_cmd(spi, cmd, true);
    
    spi_transaction_t t;
    memset(&t, 0, sizeof(t));
    t.length=8*num_bytes;
    t.flags = SPI_TRANS_USE_RXDATA;
    t.user = (void*)1;
    
    esp_err_t ret = spi_device_polling_transmit(spi, &t);
    assert( ret == ESP_OK );

    spi_device_release_bus(spi);

    return *(uint32_t*)t.rx_data;
}   

uint32_t lcd_get_id(spi_device_handle_t spi)
{
    return lcd_get_register(spi, 0x04, 3);
}
```

### Steps to reproduce

You can reproduce this by trying to use the get_lcd_id function to get a different register, like 0x0a, and you'll only get back 0, but after reboot you should get back 0x08 (per the documentation: https://cdn-shop.adafruit.com/datasheets/ILI9341.pdf page 94).

### Code to reproduce this issue

This function is from a direct and simple adaptation of lcd_get_id, just changing the command and receive length. This will confusingly not work.

```
uint32_t lcd_get_display_power_mode(spi_device_handle_t spi)
{
    //get_id cmd
    lcd_cmd(spi, 0x0a);

    spi_transaction_t t;
    memset(&t, 0, sizeof(t));
    t.length=8*1;
    t.flags = SPI_TRANS_USE_RXDATA;
    t.user = (void*)1;

    esp_err_t ret = spi_device_polling_transmit(spi, &t);
    assert( ret == ESP_OK );

    return *(uint32_t*)t.rx_data;
}

```

## Debug Logs

n/a

## Other items if possible

- [ ] sdkconfig file (attach the sdkconfig file from your project folder)
- [ ] elf file in the ``build`` folder (**note this may contain all the code details and symbols of your project.**)
- [ ] coredump (This provides stacks of tasks.)

**Comment by suda-morris** [comment]
@martaaay just noticed that we don't have a good example to show the usage of "SPI_TRANS_CS_KEEP_ACTIVE", it's clever of you to make it work!
