### ISSUE TITLE
identifier "CONFIG_LOG_MAXIMUM_LEVEL" is undefined C/C++(20) (IDFGH-7058)

### ISSUE THREAD

**Issue by chipweinberger** [espressif/esp-idf#8675]
branch: release/v4.4
commit: c29343eb94d2f2ca17b3a5b38c82452e556147f2
device: esp32-s3

I keep seeing this intellisense error in VSC. Very annoying. Code compiles fine.

<img width="827" alt="Screen Shot 2022-03-28 at 6 58 57 PM" src="https://user-images.githubusercontent.com/1863934/160517278-d7bbc6e3-5655-4d62-91e0-f818f89dfd35.png">

Looking at the code, it seems this is only used in the linker? I don't get how this is supposed to work.
https://github.com/espressif/esp-idf/search?q=LOG_MAXIMUM_LEVEL

c_cpp_properties.json looks like this:
<img width="814" alt="Screen Shot 2022-03-28 at 7 01 31 PM" src="https://user-images.githubusercontent.com/1863934/160517554-a8c49098-29af-4ea9-b3cd-e77acdbeb029.png">

**Comment by chipweinberger** [comment]
I've edited the includePath to include `${workspaceFolder}/build/config/`, and that seems to have fixed it.

**Comment by 0xjakob** [comment]
@chipweinberger I'm afraid we can't help you here because this repository is about IDF problems. You'll probably receive more help if you move the issue over to the [vscode-esp-idf-extension](https://github.com/espressif/vscode-esp-idf-extension) repository.

Not everyone using IDF is also using VSCode (e.g. me).

**Comment by chipweinberger** [comment]
Right. But there is still a possibility it is caused by an esp-idf build system issue.

**Comment by chipweinberger** [comment]
I think you are right that this is not an ESP-IDF issue though. 

VSC seems to be picking up `/Volumes/User/MBP-Google-Drive/jamcorder/firmware/esp-idf/components/wear_levelling/test_wl_host/sdkconfig/sdkconfig.h ` as the sdkconfig.h to use for intellisense, so I think I need to change the order or includes.

**Comment by chipweinberger** [comment]
https://esp32.com/viewtopic.php?t=23943

**Comment by yinj19431-blip** [comment]
我也不知道咋解决的，我把${workspaceFolder}/build/config/改完后还是失败。然后我又重建了相同的项目，其中
      "includePath": [
        "${config:idf.espIdfPath}/components/**",
        "${config:idf.espIdfPathWin}/components/**",
        "${workspaceFolder}/**"
和默认一样，然后就解决了问题。
