### ISSUE TITLE
ESP32S3 - ULP RISCV example ds18b20_onewire does not build (IDFGH-7075)

### ISSUE THREAD

**Issue by andrew-elder** [espressif/esp-idf#8691]
## Environment

- Development Kit:      ESP32-S3-DevKitM-1
- Module or chip used:  ESP32-S3-MINI-1
- IDF version: "master"   v5.0-dev-2046-g5963de1caf
- Build System:  idf.py
- Compiler version: xtensa-esp32-elf-gcc (crosstool-NG esp-2021r2-patch3) 8.4.0
- Operating System: Linux
- Using an IDE?: No

## Problem Description

ESP32S3 ULP compile for RISCV does not work.

I'm trying to get RISCV ULP code to compile and run on an ESP32S3. My own code gave include file errors, so I looped back to try a reference example. I used this example [ds18b20_onewire](https://github.com/espressif/esp-idf/tree/master/examples/system/ulp_riscv/ds18b20_onewire). It compiles correctly for ESP32S2, but not ESP32S3.

### Expected Behavior

Compilation without errors for ESP32S3.

### Actual Behavior

Observe
```
/home/logix/projects/krado/sw/ds18b20_onewire/main/ulp/main.c:18:10: fatal error: ulp_riscv/ulp_riscv.h: No such file or directory
 #include "ulp_riscv/ulp_riscv.h"
          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

### Steps to reproduce

Copy the ds18b20_onewire example.

Edit sdkconfig.defaults so that it contains
```
CONFIG_IDF_TARGET="esp32s3"
# Enable ULP
CONFIG_ESP32S3_ULP_COPROC_ENABLED=y
CONFIG_ESP32S3_ULP_COPROC_RISCV=y
CONFIG_ESP32S3_ULP_COPROC_RESERVE_MEM=4096
# Set log level to Warning to produce clean output
CONFIG_BOOTLOADER_LOG_LEVEL_WARN=y
CONFIG_BOOTLOADER_LOG_LEVEL=2
CONFIG_LOG_DEFAULT_LEVEL_WARN=y
CONFIG_LOG_DEFAULT_LEVEL=2
```
then

1. idf.py fullclean
2. idf.py set-target esp32s3
3. idf.py build

Observe the compilation error.

**Comment by andrew-elder** [comment]
And then there is this code in the ["gpio"](https://github.com/espressif/esp-idf/blob/master/examples/system/ulp_riscv/gpio/CMakeLists.txt#L5) example

```
if(NOT IDF_TARGET STREQUAL "esp32s2")
    #IDF-4514
    message(FATAL_ERROR "DO NOT BUILD THIS APP FOR ANY TARGET OTHER THAN ESP32-S2 OTHERWISE YOU MAY BRICK YOUR DEVICE")
    return()
endif()
```

**Comment by andrew-elder** [comment]
I see https://esp32.com/viewtopic.php?t=21906 that ULP is not supported yet. See related https://github.com/espressif/esp-idf/issues/7963, Any updates on when it will be supported?

**Comment by ESP-Marius** [comment]
Hi @andrew-elder ,

As you've noticed the ULP examples are currently not supported on S3, even the ULP API is currently disabled (see https://github.com/espressif/esp-idf/commit/2efd009dfb1352d5f9a0189bf4219e11eb0a454f for context)

There is a fix in review for the bug mentioned above, as soon as that is merged then we'll add S3 support to these examples. If we dont encounter any issues with the proposed fix then I would estimate that we should be able to add support pretty quickly (as in sometime in April)

For reference: you can see which targets an example supports by looking at the table at the top of the examples `readme.md`.

**Comment by andrew-elder** [comment]
@ESP-Marius - it's been a couple of months. Any updates?

**Comment by wuyuanyi135** [comment]
I am also designing a product that requires ulp support. Can I have the estimated release date of the fix?

**Comment by ESP-Marius** [comment]
Sorry for the long wait guys. We've been unable to go back to our office in Shanghai for the last few months due to Covid restrictions, which unfortunately slowed down things a lot. But now we are finally back, and the MR for the above mentioned bug is ready to merge, and an MR for re-enable ULP is under review.

Should be able to get these two merged before the end of the week.

**Comment by ESP-Marius** [comment]
> If I am using the ulp without sleep. Is it safe to bypass the error check and continue to use the feature?

Unfortunately not, as it could damage the chip permanently.

**Comment by wuyuanyi135** [comment]
@ESP-Marius Very pleased to hear that things are going back to normal and the problem will finally get fixed. Stay safe!
