### ISSUE TITLE
How to send an audio file from ESP32 as HFP-HF  (IDFGH-7077)

### ISSUE THREAD

**Issue by ferorted** [espressif/esp-idf#8693]
## Environment
Development Kit: Lolin ESP32 board
Module or chip used: ESP32-WROOM-32
Using an IDE?: Platformio
Power Supply: USB

## Problem Description

Hi,
I'm trying to send an audio file from ESP32 acting as HFP-HF and i need some help.
I'm using the HFP-HF example https://github.com/espressif/esp-idf/tree/4a553510b7aa0aef254aabf798e37dcd62388b7b/examples/bluetooth/bluedroid/classic_bt/hfp_hf with modified bt_app_hf.c and menuconfig files attached.

This example should send an audio sine wave but in the "caller" mobile phone no audio is played.
Actually I want to send an audio file, but I use this example for understand how it works.

What is wrong in my code? or how can I send an audio recorded from a file?
Thank you

### Code to reproduce this issue

Please, see enclosed files
[bt_app_hf.c.txt](https://github.com/espressif/esp-idf/files/8381994/bt_app_hf.c.txt)
[sdkconfig.lolin32_lite.txt](https://github.com/espressif/esp-idf/files/8381997/sdkconfig.lolin32_lite.txt)

**Comment by BetterJincheng** [comment]
@ferorted 
Sorry, I just can not understand what you want...
If you want to get some suggestions on your own code, please list the changes to your code.
If you want to send some audio data, just write your audio data into `bt_app_hf_create_audio_data`.
Thanks

**Comment by ferorted** [comment]
Hi, 
My goal is to send stored audio in this way:  hfp-HF device (Esp32+stored audio) -> bluetooth link -> AG (mobile phone) -> caller mobile phone.

To do this I used the espressif hfp-hf example, but modified.

Please see my code above (enclosed in my first message).

This code runs without errors but it doesn't work because sine audio is NOT played in "caller" mobile phone.
So, I need help because my code has something wrong or missing.

Of course I will appreciate other code example that can send an audio file stored into the Esp32

**Comment by BetterJincheng** [comment]
@ferorted I tested your code and there is nothing wrong. I ensure that the HF has sent the sine audio out.
Maybe you can add some print in `bt_app_hf_client_incoming_cb` to see whether whther HF received data from AG.
In this demo, only when HF receives data from Ag will HF send data to Ag.
Turn to us anytime.

**Comment by ferorted** [comment]
Thanks, but I remember "speed ..." is printed on terminal.  print_speed() function is called in bt_app_hf_client_incoming_cb , then it is received data from AG, is it right?

**Comment by BetterJincheng** [comment]
You can test your tailored HF with AG demo (`examples/bluetooth/bluedroid/classic_bt/hfp_ag`) and you will find AG did receive the data from HF.

**Comment by BetterJincheng** [comment]
@ferorted Have you solved your problem? Oh any new ones?

**Comment by ferorted** [comment]
Dear @BetterJincheng, I’m not sure it is working fine.
I added the following in the code:
static uint32_t bt_app_hf_outgoing_cb(uint8_t *p_buf, uint32_t sz)
{
    size_t item_size = 0;
    uint8_t *data;
    if (!s_m_rb) {
        return 0;
    }
    vRingbufferGetInfo(s_m_rb, NULL, NULL, NULL, NULL, &item_size);
    if (item_size >= sz) {
        data = xRingbufferReceiveUpTo(s_m_rb, &item_size, 0, sz);
                      printf("data outgoing ================= ");	//added to monitoring
                      printf("%" PRIu8 "\n", *(data));                                          //added to monitoring
        memcpy(p_buf, data, item_size);
        vRingbufferReturnItem(s_m_rb, data);
        return sz;
    } else {
        // data not enough, do not read\n
        return 0;
    }
    return 0;
}

And the output I get is:
cona
Connect Audio
hfp_ag>
hfp_ag> ␛[0;32mI (4449638) BT_APP_HF: APP HFP event: AUDIO_STATE_EVT␛[0m
␛[0;32mI (4449648) BT_APP_HF: --Audio State connecting␛[0m
␛[0;32mI (4450348) BT_APP_HF: APP HFP event: BCS_EVT␛[0m
␛[0;32mI (4450358) BT_APP_HF: --Consequence of codec negotiation: Use MSBC␛[0m
␛[0;31mE (4450388) BT_BTM: btm_sco_connected, handle 180␛[0m
␛[0;32mI (4450388) BT_APP_HF: APP HFP event: AUDIO_STATE_EVT␛[0m
␛[0;32mI (4450388) BT_APP_HF: --Audio State connected_msbc␛[0m
data outgoing ================= 0
␛[0;33mW (4450408) BT_APPL: bta_ag_sco_read_cback: status(2)␛[0m
data outgoing ================= 187
data outgoing ================= 60
data outgoing ================= 196
data outgoing ================= 69
␛[0;33mW (4450448) BT_APPL: bta_ag_sco_read_cback: status(2)␛[0m
data outgoing ================= 0
data outgoing ================= 187
␛[0;33mW (4450458) BT_APPL: bta_ag_sco_read_cback: status(2)␛[0m
data outgoing ================= 60
data outgoing ================= 196
data outgoing ================= 69
data outgoing ================= 0
data outgoing ================= 187
data outgoing ================= 60
data outgoing ================= 196
data outgoing ================= 69
␛[0;33mW (4450518) BT_APPL: bta_ag_sco_read_cback: status(2)␛[0m
data outgoing ================= 0
data outgoing ================= 187
data outgoing ================= 60
data outgoing ================= 196
data outgoing ================= 69
data outgoing ================= 0
␛[0;33mW (4450568) BT_APPL: bta_ag_sco_read_cback: status(2)␛[0m
data outgoing ================= 187
data outgoing ================= 60
␛[0;33mW (4450578) BT_APPL: bta_ag_sco_read_cback: status(2)␛[0m
data outgoing ================= 196
␛[0;33mW (4450588) BT_APPL: bta_ag_sco_read_cback: status(2)␛[0m
data outgoing ================= 69
␛[0;33mW (4450588) BT_APPL: bta_ag_sco_read_cback: status(2)␛[0m
data outgoing ================= 0
␛[0;33mW (4450598) BT_APPL: bta_ag_sco_read_cback: status(2)␛[0m
data outgoing ================= 187
␛[0;33mW (4450608) BT_APPL: bta_ag_sco_read_cback: status(2)␛[0m
data outgoing ================= 60
data outgoing ================= 196
data outgoing ================= 69
...

so, is it right?
Are there any way I can send a previously recorded short .wav file? could you show me an example?
Thank you.

**Comment by BetterJincheng** [comment]
@ferorted It seems just right. The HF sent the data out. If you want to send a .wav file, you just need to replace the sine audio with the .wav data. 

As for how to get .wav files, you can save the .wav in SD card and then refer to demo `examples/storage/sd_card/sdmmc/main/sd_card_example_main.c`. Use `fopen` and `fread` to get data from .wav file. To do this you need a ESP32-LyraT (https://www.espressif.com/zh-hans/products/devkits/esp-audio-devkits). 

Turn to us anytime.

**Comment by BetterJincheng** [comment]
@ferorted bt_app_hf_create_audio_data is just used to simulate the production of audio data. In your situation, the audio data is a .wav file, so you do not need any creation for the data but just read from the file.

**Comment by ferorted** [comment]
Using fread (read_wav = fread (...)), I can read properly the wav file and get its header and PCM data.

but I have some doubts:
1 - What is need in bt_app_hf_outgoing_cb ? header + PCM data or only the PCM data
2 - PCM data have to be sent taken 2 bytes by 2 bytes, or the whole string I get with fread?

**Comment by BetterJincheng** [comment]
1. PCM data only
2. bt_app_hf_outgoing_cb has a function paramter `sz`, treat the data obtained with fread as uint8 array, and every call for bt_app_ hf_ outgoing_cb should send sz bytes of data.

**Comment by ferorted** [comment]
Done, but in a "dirty" way. I have to find a elegant way.
Thanks for your support

**Comment by Alvin1Zhang** [comment]
Thanks for reporting and sharing updates, feel free to reopen. Thanks.

**Comment by ferorted** [comment]
Hi again,
I can't play the audio file more than 10 sec aprox, then I get the following errors:

(90978) BT_BTM: SCO xmit Q overflow, pkt dropped
(90978) BT_BTM: stat 10
(90978) BT_BTM: SCO xmit Q overflow, pkt dropped
(90978) BT_BTM: stat 10
(90978) BT_BTM: SCO xmit Q overflow, pkt dropped
(90978) BT_BTM: stat 10

**Comment by BetterJincheng** [comment]
@ferorted  Please attach your bt_app_hf.c here

**Comment by ferorted** [comment]
[sdkconfig.lolin32_lite.txt](https://github.com/espressif/esp-idf/files/8754147/sdkconfig.lolin32_lite.txt)
[bt_app_hf.c.txt](https://github.com/espressif/esp-idf/files/8754150/bt_app_hf.c.txt)
Here you can find the bt_app_hf.c and sdkconfig files.

**Comment by BetterJincheng** [comment]
@ferorted We have improve the hfp_ag demo two month ago. It seems that you did not use the esp-idf of latest version. 
Well, I will provide you with the key modifications in function `bt_app_send_data_task`:

Original
```c
            if(s_audio_code == ESP_HF_AUDIO_STATE_CONNECTED_MSBC) {
            // time of a frame is 7.5ms, sample is 120, data is 2 (byte/sample), so a frame is 240 byte (HF_SBC_ENC_RAW_DATA_SIZE)
                frame_data_num = s_us_duration / (PCM_BLOCK_DURATION_US / WBS_PCM_INPUT_DATA_SIZE);
                s_last_enter_time += frame_data_num * (PCM_BLOCK_DURATION_US / WBS_PCM_INPUT_DATA_SIZE);
            } else {
                frame_data_num = s_us_duration / (PCM_BLOCK_DURATION_US / PCM_INPUT_DATA_SIZE);
                s_last_enter_time += frame_data_num * (PCM_BLOCK_DURATION_US / PCM_INPUT_DATA_SIZE);
            }
```

Modified
```c
            if(s_audio_code == ESP_HF_AUDIO_STATE_CONNECTED_MSBC) {
            // time of a frame is 7.5ms, sample is 120, data is 2 (byte/sample), so a frame is 240 byte (HF_SBC_ENC_RAW_DATA_SIZE)
                frame_data_num = s_us_duration / PCM_BLOCK_DURATION_US * WBS_PCM_INPUT_DATA_SIZE;
                s_last_enter_time += frame_data_num / WBS_PCM_INPUT_DATA_SIZE * PCM_BLOCK_DURATION_US;
            } else {
                frame_data_num = s_us_duration / PCM_BLOCK_DURATION_US * PCM_INPUT_DATA_SIZE;
                s_last_enter_time += frame_data_num / PCM_INPUT_DATA_SIZE * PCM_BLOCK_DURATION_US;
            }
```

Wish it helps~

**Comment by BetterJincheng** [comment]
@ferorted It seems that there is no problem with hfp_ag now. Maybe you can check your hf side.

**Comment by ferorted** [comment]
This problem occurs after 7-8 sec after audio starts.
When sine wave table is used instead of audio file nothing SCO packets are lost.

**Comment by ferorted** [comment]
no idea?
