### ISSUE TITLE
esp_mqtt_client_subscribe sends same SUBSCRIBE packet 16 times. (IDFGH-7081)

### ISSUE THREAD

**Issue by nopnop2002** [espressif/esp-idf#8697]
## Environment
```
$ idf.py --version
ESP-IDF v4.4-dev-2825-gb63ec47238-dirty
```

## Problem Description
esp_mqtt_client_subscribe sends SUBSCRIBE packet 16 times.
This is server side logging.
The server receives SUBSCRIBE packets for the same topic 16 times.
```
I (1766966) BROKER: CONNECT
I (1766966) BROKER: cid=[SUB001] willFlag=0
I (1766996) BROKER: MQTT_CMD_SUBSCRIBE
I (1766996) BROKER: SUB ADD 0x38 [/topic/test/#]
I (1768076) BROKER: MQTT_CMD_SUBSCRIBE
I (1768076) BROKER: SUB ADD 0x38 [/topic/test/#]
I (1770116) BROKER: MQTT_CMD_SUBSCRIBE
I (1770116) BROKER: SUB ADD 0x38 [/topic/test/#]
I (1772066) BROKER: MQTT_CMD_SUBSCRIBE
I (1772066) BROKER: SUB ADD 0x38 [/topic/test/#]
I (1774006) BROKER: MQTT_CMD_SUBSCRIBE
I (1774006) BROKER: SUB ADD 0x38 [/topic/test/#]
I (1776056) BROKER: MQTT_CMD_SUBSCRIBE
I (1776056) BROKER: SUB ADD 0x38 [/topic/test/#]
I (1778106) BROKER: MQTT_CMD_SUBSCRIBE
I (1778106) BROKER: SUB ADD 0x38 [/topic/test/#]
I (1780056) BROKER: MQTT_CMD_SUBSCRIBE
I (1780056) BROKER: SUB ADD 0x38 [/topic/test/#]
I (1782106) BROKER: MQTT_CMD_SUBSCRIBE
I (1782106) BROKER: SUB ADD 0x38 [/topic/test/#]
I (1784046) BROKER: MQTT_CMD_SUBSCRIBE
I (1784046) BROKER: SUB ADD 0x38 [/topic/test/#]
I (1786096) BROKER: MQTT_CMD_SUBSCRIBE
I (1786096) BROKER: SUB ADD 0x38 [/topic/test/#]
I (1788036) BROKER: MQTT_CMD_SUBSCRIBE
I (1788036) BROKER: SUB ADD 0x38 [/topic/test/#]
I (1790086) BROKER: MQTT_CMD_SUBSCRIBE
I (1790086) BROKER: SUB ADD 0x38 [/topic/test/#]
I (1792036) BROKER: MQTT_CMD_SUBSCRIBE
I (1792036) BROKER: SUB ADD 0x38 [/topic/test/#]
I (1794086) BROKER: MQTT_CMD_SUBSCRIBE
I (1794086) BROKER: SUB ADD 0x38 [/topic/test/#]
I (1796026) BROKER: MQTT_CMD_SUBSCRIBE
I (1796026) BROKER: SUB ADD 0x38 [/topic/test/#]
```

This is server-side logging when mosquitto_sub is started.
The server receives SUBSCRIBE packet only 1 times.
```
I (2065166) BROKER: CONNECT
I (2065166) BROKER: cid=[mosq-Gn10bDZOv47iD655AV] willFlag=0
I (2065186) BROKER: MQTT_CMD_SUBSCRIBE
I (2065186) BROKER: SUB ADD 0x37 [#]
```

**Comment by nopnop2002** [comment]
esp_mqtt_task is resending here.
I don't know the reason.

https://github.com/espressif/esp-mqtt/blob/4874bab35659bd2301e65fd849f6559d7380d4f1/mqtt_client.c#L1481

**Comment by nopnop2002** [comment]
QOS of subscribe is set to 0.

```
esp_mqtt_client_subscribe(mqtt_client, CONFIG_MQTT_SUB_TOPIC, 0);
```

**Comment by nopnop2002** [comment]
I delete this block:
It's fixed.

https://github.com/espressif/esp-mqtt/blob/4874bab35659bd2301e65fd849f6559d7380d4f1/mqtt_client.c#L1699

**Comment by euripedesrocha** [comment]
Hi @nopnop2002, thanks for reporting.
Our MQTT client expects a `SUBACK` message from the broker to stop sending the subscribe message. Could you give us a log with log level DEBUG?

Regarding the QoS flag, it's not related to the subscribe message, but to the max QoS level for messages in that topic filter. You can refer to the non-normative examples in [this session of MQTT specification](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718067)

**Comment by nopnop2002** [comment]
Hello @euripedesrocha 

I am using a custom MQTT broker built with ESP-IDF.

At your point, I found that this custom MQTT broker is not responding to PUBACK.

I added SUBACK response.

The problem has been fixed.

Thank you.
