### ISSUE TITLE
ESPmDNS: support for subtypes (IDFGH-7086)

### ISSUE THREAD

**Issue by guestisp** [espressif/esp-idf#8700]
As per subject, please add support for subtypes in ESPmDNS. Currently, only the primary type is supported.

**Comment by david-cermak** [comment]
Hi @guestisp 

Could you make the feature request a little bit more specific, please?
As you can see, the subtypes for the advertized services are already supported, from the main sample application:

https://github.com/espressif/esp-idf/blob/36b83fcb9811437102a5b6b156221eeffe1e8fd7/examples/protocols/mdns/main/mdns_example_main.c#L56

**Comment by david-cermak** [comment]
@guestisp Could you please close the issue then? This was added to IDF in `v4.4` so I believe some version of Arduino already has it.

**Comment by guestisp** [comment]
closed. It was also opened in your esp32 arduino repository
