### ISSUE TITLE
wss client support Http authentication (IDFGH-7090)

### ISSUE THREAD

**Issue by diazmanuel** [espressif/esp-idf#8701]
hello, I was doing a job with websocket and I see the need to use basic authentication in the handshake, when reviewing the documentation I found that it is not supported at the moment, I would like to know if they will add this feature (which should not be difficult ) or if using the header field of esp_websocket_client_config_t the same result can be obtained

**Comment by david-cermak** [comment]
Hi @diazmanuel 

Yes, you can use additional header for that.
Here's an example of generating the basic http authentication header:
```cpp
    #define USER "user"
    #define PASSWORD "password"   
    ....
    unsigned char user_auth[] = USER ":" PASSWORD;
    char add_header[]="Authorization: Basic ";
    size_t outlen = 0;
    size_t encoded_len = sizeof(user_auth)*4/3 + sizeof(user_auth)/96 + 6 + sizeof(add_header);
    unsigned char * encoded = calloc(1, encoded_len);
    memcpy(encoded, add_header, sizeof(add_header));
    esp_crypto_base64_encode(encoded + sizeof(add_header) - 1, encoded_len - sizeof(add_header), &outlen, user_auth, sizeof(user_auth) - 1);
    esp_websocket_client_config_t websocket_cfg = { .headers = (char *)encoded, ... };
    ... // after starting the client
    free(encoded);
```

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to short of feedback, feel free to reopen with more updates. Thanks.

**Comment by lokeshwrn** [comment]
Hello @david-cermak,

I tried using the headers for a token-based authorization, but couldn't make it work. 

Here is my code

```
esp_websocket_client_config_t websocket_cfg = {};

websocket_cfg.uri = "ws://localhost:5000/testing";
websocket_cfg.port = 80;
websocket_cfg.headers = "authorization: token"
websocket_cfg.user_agent = "my-custom-user-agent"

esp_websocket_client_handle_t client = esp_websocket_client_init(&websocket_cfg);
```

Any help would be highly appreciated.

**Comment by ParameswaranAP** [comment]
Hi, This issue can be resolved by placing the newline character at end of the auth token string in the headers parameter.

For example,
`websocket_cfg.headers = "Authorization: token\n`

This will work definitely we have tried from our end.

**Comment by Guitton-S** [comment]
Hi all,

I am trying the basic Auth for websocket just like @david-cermak suggested. It seems to work as I get an answer though the response I get gives me an error:

E (652021) TRANSPORT_WS: Error read response for Upgrade header GET /xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Connection: Upgrade
Host: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
User-Agent: ESP32 Websocket Client
Upgrade: websocket
Sec-WebSocket-Version: 13
Sec-WebSocket-Key: xxxxxxxxxxxxxxxxxxxxxxxxxxxx
Sec-WebSocket-Protocol: ocpp1.6
Authorization: Basic xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Do you have an idea on how to solve this?
