### ISSUE TITLE
Document very well known things that are broken in the current release. (IDFGH-7098)

### ISSUE THREAD

**Issue by mianos** [espressif/esp-idf#8707]
I just spent some time getting everything up with the plan to use ESPNow in the idf instead of the arduino toolchain and their web based config and eventually discovered it does not work anymore and will maybe be in the next stable release.

This was not in an open bug, but a closed one because the bug is fixed. The IDF VSCode addon is not supported for anything but the stable release branches. (Menuconfig does not even seem to be supported on those).

Or, some other way to know the state of the examples, maybe a table somewhere? I already see a lot of them are broken in open bugs, that is probably OK.

**Comment by MaxwellAlan** [comment]
Hi @mianos 
> I just spent some time getting everything up with the plan to use ESPNow in the idf instead of the arduino toolchain and their web based config and eventually discovered it does not work anymore and will maybe be in the next stable release.
Can you give more details about ESPNOW issue:

- IDF commit id
- Error logs
- Issue description
- etc
Thanks.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, feel free to reopen.
