### ISSUE TITLE
When will esp idf4.4.1 be released？ (IDFGH-7105)

### ISSUE THREAD

**Issue by dreamcmi** [espressif/esp-idf#8713]
I see that the release/v4.4 branch has fixed a lot of problems, when will  esp-idf 4.4.1  be released? Is there a planned timetable?

**Comment by dobairoland** [comment]
Hi @dreamcmi. There is no fixed timeline for the release. There are a couple of outstanding blocking issues which need to be fixed. The release will be done when those get resolved. Thanks for the patience!

More information: https://github.com/espressif/esp-idf/blob/master/SUPPORT_POLICY.md

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, sorry for slow turnaround, v4.4.1 released https://github.com/espressif/esp-idf/releases/tag/v4.4.1. Thanks
