### ISSUE TITLE
ESP32 C3 DR_REG_I2S_BASE definition missing (IDFGH-7113)

### ISSUE THREAD

**Issue by snorman35** [espressif/esp-idf#8721]
## Environment

- Module or chip used:  ESP32C3
- IDF version:  v4.4 and latest master branch
- Build System:         idf.py

## Problem Description

Cannot compile for esp32c3 when calling I2S_TX_CONF_REG(). Works for the ESP32 and the ESP32S3.

In the macro expansion DR_REG_I2S_BASE does not resolve because it is not defined for the C3.

### Steps to reproduce

1. idf.py set-target esp32c3
2. add the line `REG_SET_BIT(I2S_TX_CONF_REG(I2S_NUM0) I2S_RX_MSB_SHIFT);` into the i2s_basic example.
3. compile

### Code to reproduce this issue

https://gist.github.com/snorman35/f089324df9714245cc1b1a226816248d

### Fix

Rename the macro that is used to reference the I2S register base address from `DR_REG_I2S_BASE` to `DR_REG_I2S0_BASE`
in the master branch this is at: `components/soc/esp32c3/include/soc/soc.h: 23`
in the 4.4 release this is at: `components/soc/esp32c3/include/soc/soc.h: 75`

**Comment by L-KAYA** [comment]
Actually, C3 only has I2S1 in hardware, but it is remapped to I2S0 in software for easier usage.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, feel free to reopen.
