### ISSUE TITLE
undefined reference to esp_netif_dhcps_stop (IDFGH-7123)

### ISSUE THREAD

**Issue by tlaritz** [espressif/esp-idf#8729]
At the linking stage, in Espressif IDE, I get an error:

undefined reference to esp_netif_dhcps_stop

I have version 2.4.2 of Espressif IDE.

BTW, my near-term objective is to set the gateway address of my WiFi AP.  I believe that I need to stop dhcp on the server to set the gateway address.  If there is a work around, I'd like to know please.

I'm not sure why others are not getting this linking error.

Thanks.

Tom LaRitz

**Comment by david-cermak** [comment]
Hi Tom LaRitz

Please enable DHCP server in the component configuration of lwIP:
```
(Top) → Component config → LWIP → DHCP server
```

> BTW, my near-term objective is to set the gateway address of my WiFi AP.

One option is to start the default AP, stop the DHCP server, update the addresses, masks and start the server again.
Another options is to adjust the settings of the AP netif, i.e. create a struct like this:

https://github.com/espressif/esp-idf/blob/4350e6fef859b94f3efae6ceced751911c9d2cbc/components/esp_netif/esp_netif_defaults.c#L38-L42

in your code and add it to your netif configuration when creating the handle.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to short of feedback, feel free to reopen with more updates. Thanks.
