### ISSUE TITLE
[TW#14556] Is lwip netconn api supported?

### ISSUE THREAD

**Issue by nilp0inter** [espressif/esp-idf#874]
Hi,

I am trying to use lwip's netconn api without any luck, I didn't see any examples either... Is the API supported/tested on the esp32?

Best regards,
Roberto

**Comment by jmattsson** [comment]
The [net module](https://github.com/nodemcu/nodemcu-firmware/blob/dev-esp32/components/modules/net.c) in the ESP32 version of NodeMCU uses the netconn API these days, you might find some useful ideas/examples there.

**Comment by nilp0inter** [comment]
Thank you, that was very helpful!
