### ISSUE TITLE
twai_ll_prase_frame_buffer --> twai_ll_parse_frame_buffer (IDFGH-7140)

### ISSUE THREAD

**Issue by f-hoepfinger-hr-agrartechnik** [espressif/esp-idf#8743]
I guess it is a Typo there: 

twai_ll_prase_frame_buffer --> twai_ll_parse_frame_buffer

right ? 
https://github.com/espressif/esp-idf/blob/master/components/hal/esp32/include/hal/twai_ll.h

**Comment by Alvin1Zhang** [comment]
Thanks for pointing out, we have a fix under internal reviewing. The issue will close automatically once the fix is available on GitHub. Thanks.
