### ISSUE TITLE
mbedtls_ssl_setup returned -0x7f00 in SMTP client 

### ISSUE THREAD

**Issue by MaazSk** [espressif/esp-idf#8765]
## Environment

- Development Kit:      [ESP32-DevKit]
- Kit version (for WroverKit/PicoKit/DevKitC): [v1]
- Module or chip used:  [ESP32-WROOM-32|]
- IDF version (run ``git describe --tags`` to find it): v4.3
   
- Compiler version : xtensa-esp32-elf-gcc (crosstool-NG esp-2021r1) 8.4.0
  
- Operating System:     [Linux]

- Using an IDE?: [VS Code]
- Power Supply:         [USB]

## Problem Description

I am trying to send mail, again and again, using the smtp_client example but after sending mail for 3 or 4 times the code crashes with the following error ```mbedtls_ssl_setup returned -0x7f00```. Any help related to it would be grateful.

Thanks and Regards,
Maaz Shaikh

**Comment by laukik-hase** [comment]
Duplicates #8768
