### ISSUE TITLE
"usb/usb_host.h: No such file or directory" for ESP32S2 USB MSC example (IDFGH-7172)

### ISSUE THREAD

**Issue by Maldus512** [espressif/esp-idf#8773]
## Environment

- Development Kit:      [none]
- Module or chip used:  [ESP32S2]
- IDF version (run ``git describe --tags`` to find it):
    v4.4-367-gc29343eb94
- Build System:         [idf.py]
- Compiler version 
    xtensa-esp32-elf-gcc (crosstool-NG esp-2021r2-patch3) 8.4.0
- Operating System:     [Linux]
- Using an IDE?: [No]
- Power Supply:         [external 3.3V]

## Problem Description

I am trying to work with the msc USB driver on an ESP32S2 powered custom board. I have seen that the example has made its way into the release/v4.4 branch and I wanted to try it. Unfortunately the example on the release/v4.4 does not compile, failing with the following error:

```
/home/maldus/Source/esp-idf-v4.4/examples/peripherals/usb/host/msc/components/msc/src/msc_host.c:18:10: fatal error: usb/usb_host.h: No such file or directory
 #include "usb/usb_host.h"
          ^~~~~~~~~~~~~~~~
compilation terminated.
[11/21] Performing build step for 'bootloader'
[1/1] cd /home/maldus/Source/esp-idf-v4.4/examples/peripherals/usb/host/msc/build/bootloader/esp-idf/esptool_py && /home/maldus/.espressif/python_env/idf5.0_py3.9_env/bin/python /home/maldus/Source/esp-idf-master/components/partition_table/check_sizes.py --offset 0x8000 bootloader 0x1000 /home/maldus/Source/esp-idf-v4.4/examples/peripherals/usb/host/msc/build/bootloader/bootloader.bin
Bootloader binary size 0x6350 bytes. 0xcb0 bytes (11%) free.
ninja: build stopped: subcommand failed.
ninja failed with exit code 1
```

The `usb/usb_host.h` header file is actually present in the clone repository. Interestingly the same example works if the branch `master` is used.

### Expected Behavior

A successful compilation

### Actual Behavior

The compilation error above

### Steps to reproduce

1. clone and install ESP-IDF release/v4.4
2. try to compile the example under `examples/peripherals/usb/host/msc`

**Comment by tore-espressif** [comment]
Hello @Maldus512 , 
From the log you shared it is not clear whether you are compiling for correct target? Have you run `idf.py set-target esp32s2` ?

**Comment by Maldus512** [comment]
> Hello @Maldus512 , From the log you shared it is not clear whether you are compiling for correct target. Have you run `idf.py set-target esp32s2` ?

This is quite embarassing. Indeed I had not set esp32-s2 as the target, it now works as expected. Thank you for the assistance!

**Comment by tore-espressif** [comment]
It is still valuable feedback :) we have quite a few issues like this, the error message should be more indicative.

**Comment by juddvinet** [comment]
![1666430005305](https://user-images.githubusercontent.com/72131837/197331485-1c08d5f1-87d7-481d-9b00-0e4d407d3aeb.jpg)
