### ISSUE TITLE
ble_spp_server and ble_spp_client examples do not build on master (due to component coap) (IDFGH-7173)

### ISSUE THREAD

**Issue by ashesman** [espressif/esp-idf#8774]
## Environment

- Development Kit:      Windows 10, ESP32-C3-MINI

## Problem Description

ble_spp_server and ble_spp_client examples do not build on master.  Please disregard this issue if it is irrelevant or not expected to work on master branch.  It is not a show stopper for me, I just thought I should report it.

### Expected Behavior

build without error

### Actual Behavior

Fails to compile component CoAP.  Due to the CMakeList for this component listing source files (e.g. coap_asn1.c) that are not in the sources directory.  Compiles fine on V4.3 release build

### Steps to reproducegit checkout 

1. copy examples\bluetooth\bluedroid\ble\ble_spp_server to working dir
2. idf.py set-target esp32c3
3. Fails while running cmake during the above command

// If possible, attach a picture of your setup/wiring here.

## Debug Logs

-- Configuring done
CMake Error at D:/espressif/esp-idf/tools/cmake/component.cmake:475 (add_library):
  Cannot find source file:

    D:/espressif/esp-idf/components/coap/libcoap/src/coap_asn1.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .h .hh .h++
  .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .ispc
Call Stack (most recent call first):
  D:/espressif/esp-idf/components/coap/CMakeLists.txt:37 (idf_component_register)

CMake Error at D:/espressif/esp-idf/tools/cmake/component.cmake:475 (add_library):
  No SOURCES given to target: __idf_coap
Call Stack (most recent call first):
  D:/espressif/esp-idf/components/coap/CMakeLists.txt:37 (idf_component_register)

CMake Generate step failed.  Build files cannot be regenerated correctly.
cmake failed with exit code 1

## Other items if possible

From Master branch
![image](https://user-images.githubusercontent.com/22144425/163279669-2077515f-2de8-44f5-a7df-cc97a229e545.png)
![image](https://user-images.githubusercontent.com/22144425/163279737-73a2b1d9-d875-443b-8655-79699adb64a3.png)

From Release 4.3 branch

![image](https://user-images.githubusercontent.com/22144425/163279866-50315de5-5465-4ee8-a119-23c630f38ace.png)

**Comment by mahavirj** [comment]
@ashesman 

`coap` is moved to ESP-IDF component manager on `master` branch. Please refer to: https://docs.espressif.com/projects/esp-idf/en/latest/esp32/migration-guides/removed-components.html#removed-or-deprecated-components

`coap` is now hosted at https://github.com/espressif/idf-extra-components/tree/master/coap and it will be fetched through ESP-IDF component manager for `coap` specific examples only. It should not ideally affect build for `BLE` specific examples.

Can you please check why you still see `D:/espressif/esp-idf/components/coap/libcoap/src/coap_asn1.c` locally?

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to short of feedback, feel free to reopen with more updates.
