### ISSUE TITLE
ESP32 【esp_wifi_config_espnow_rate】doesn't work  (IDFGH-7183)

### ISSUE THREAD

**Issue by LCreamStarter** [espressif/esp-idf#8782]
如何配置固定的PHY速率和MCS，esp_wifi_config_espnow_rate不起作用

How to configure PHY rate in WIFI_PHY_RATE_MCS0_LGI, 【esp_wifi_config_espnow_rate 】doesn't work

**Comment by MaxwellAlan** [comment]
Hi @LCreamStarter 
Can you share your code here? And do you have wireless sniffer to check the rate?

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to short of feedback, feel free to reopen with more updates. Thanks.
