### ISSUE TITLE
No explicit conversion to esp_tls_error_handle_t in esp_http_client example (IDFGH-7196)

### ISSUE THREAD

**Issue by dmitrij9992905** [espressif/esp-idf#8795]
No explicit conversion to esp_tls_error_handle_t in esp_http_client example
`esp_err_t err = esp_tls_get_and_clear_last_error(evt->data, &mbedtls_err, NULL);`

As a result, the example cannot be compiled

As a solution, I propose to add explicit data conversion:
`esp_err_t err = esp_tls_get_and_clear_last_error((esp_tls_error_handle_t)evt->data, &mbedtls_err, NULL);`

**Comment by laukik-hase** [comment]
Hello, @dmitrij9992905!

The change proposed by you makes sense. But, could you please mention the ESP-IDF version you are using? The example compiles fine on the `master` branch.

**Comment by dmitrij9992905** [comment]
The ESP-IDF version was 4.3.1

**Comment by laukik-hase** [comment]
Hello, @dmitrij9992905!

The example compiles fine on ESP-IDF `v4.3.1`. Are you building the example with some custom `CFLAGS`?
