### ISSUE TITLE
Different type of error in logs  (IDFGH-7208)

### ISSUE THREAD

**Issue by ashwanix1997** [espressif/esp-idf#8802]
W (894808) BT_HCI: DiscCmpl evt: hdl=3, rsn=0x3e
W (914808) BT_APPL: gattc_conn_cb: if=3 st=0 id=3 rsn=0x100
I (914808) BLE-SCAN-MGR: EVENT :: ESP_GATTC_DISCONNECT_EVT, reason = 256
E (914808) BLE-SCAN-MGR: open failed, status 133
I (914818) BLE-SCAN-MGR: Scanning started
I (914908) COMM_CONTR_MGR: Time sync command found in BLE write queue
I (914908) BLE-SCAN-MGR: Connecting to the remote device.
I (914918) BLE-SCAN-MGR: f3 fe f1 bb 73 ae
I (914928) BLE-SCAN-MGR: stop scan successfully
W (944928) BT_APPL: gattc_conn_cb: if=3 st=0 id=3 rsn=0x100
I (944928) BLE-SCAN-MGR: EVENT :: ESP_GATTC_DISCONNECT_EVT, reason = 256
E (944928) BLE-SCAN-MGR: open failed, status 133

anyone help me to resolve this issue.

**Comment by Alvin1Zhang** [comment]
@ashwanix1997 Thanks for reporting. Would you please help provide more details as suggested in the [issue template](https://github.com/espressif/esp-idf/issues/new?assignees=&labels=&template=bug_report.md&title=)? Information like elf, sdk configuration, backtrace, log outputs, commit ID, hardware and etc. would help us debug further. Thanks.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to short of feedback, feel free to reopen with more updates, thanks.
