### ISSUE TITLE
SIM800L ESP32-S3 (IDFGH-7211)

### ISSUE THREAD

**Issue by TGiles1998** [espressif/esp-idf#8805]
Hi,

Ive been struggling to communicate with the Sim800L using ESP32S3. 

I am currently connecting a SIM800L to an ESP32 s3 using pins rx: 18, tx: 17
and running this code on micropython.

from machine import UART
id = 1
gsm = UART(id, 115200)

This then returns the error for both id=1 and id=2:

Guru Meditation Error: Core  1 panic'ed (LoadStoreAlignment). Exception was unhandled.

Ive noticed the examples for ESP Modem.

https://github.com/espressif/esp-idf/blob/master/examples/cxx/experimental/esp_modem_cxx/README.md

Is it possible to communicate using the series 3 chips?

many thanks,

Thomas

**Comment by david-cermak** [comment]
Hi @TGiles1998 

I'm sorry, this issue has somehow got forgotten.

> Is it possible to communicate using the series 3 chips?

Yes, it's possible to use ESP-MODEM with ESP32s3. 

> Ive noticed the examples for ESP Modem.

Those examples have been migrated to https://github.com/espressif/esp-protocols/tree/master/components/esp_modem/examples In the meantime. Could you please try them and report back?

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to short of feedback, feel free to reopen with more updates. Thanks.
