### ISSUE TITLE
IEEE 802.1Q VLAN Support (IDFGH-7213)

### ISSUE THREAD

**Issue by franz-ms-muc** [espressif/esp-idf#8807]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when Customers want to use IEEE 802.1Q VLAN Supported Networks (most Wifi, but sometimes Ethernet) with VLAN Support, and i have to use others than ESP32 Family Microcontrollers. Because we love ESP32, we would like to use them here as well. 

**Describe the solution you'd like**

IEEE 802.1Q VLAN Support to be added to ESP-IDF. 
https://de.wikipedia.org/wiki/IEEE_802.1Q

**Describe alternatives you've considered**

https://zephyrproject.org/ has VLAN Support on ESP32. but i never tested this on ESP32, and i am unsure about the maturity it has, especially on the newest Chip: ESP32-S3

**Comment by david-cermak** [comment]
Hi @franz-ms-muc 

lwIP supports basic VLAN functionality, as described here:

https://github.com/espressif/esp-lwip/blob/fb1f3552349bfa53d2977409f204d385ed0aa217/src/include/lwip/opt.h#L670-L675

It just checks the VLAN header (` 0x8100  /* 802.1Q VLAN tag */`) and if enabled the packet could be processed or dropped based on user definition.

The easiest option is to
* enable VLAN: `ETHARP_SUPPORT_VLAN=1`
* define our VLAN header: `ETHARP_VLAN_CHECK=*our_id*`

It's also possible to define a function that receives the vlan header and decides what we want to do with the packet.
Here's the example:

### Project Makefile:
```cmake
idf_component_get_property(lwip lwip COMPONENT_LIB)
target_compile_options(${lwip} PRIVATE "-I${PROJECT_DIR}/main")
target_compile_definitions(${lwip} PRIVATE "-DETHARP_SUPPORT_VLAN=1" "-DLWIP_HOOK_VLAN_CHECK=vlan_hook" "-DESP_IDF_LWIP_HOOK_FILENAME=\"vlan_hook.h\"")
```

### Hook header
```cpp
#pragma once

struct netif;
struct eth_hdr;
struct eth_vlan_hdr;

int vlan_hook(struct netif *netif, struct eth_hdr *eth_hdr, struct eth_vlan_hdr *vlan_hdr);
```

### Definition
```cpp
#include "lwip/netif.h"
#include "lwip/etharp.h"

int vlan_hook(struct netif *netif, struct eth_hdr *eth_hdr, struct eth_vlan_hdr *vlan_hdr)
{
    // Processing (return 1 if for us)
    return 0;
}
```
