### ISSUE TITLE
[TW#14562] WROVER ESP-IDF back-level on BLE

### ISSUE THREAD

**Issue by nkolban** [espressif/esp-idf#881]
I am working with the recommended/required ESP-IDF for building WROVER applications.  I am porting applications that worked on WROOM to WROVER and have run into a problem with BLE.  In the current ESP-IDF there are events/function in BLE relating to client connects and disconnects.  Specifically, we have:

* ESP_GATTC_CONNECT_EVT
* ESP_GATTC_DISCONNECT_EVT

Unfortunately, these are not present in the WROVER snapshot of the ESP-IDF.  It seems that these functions were added to the master ESP-IDF on June 7th.

So that I may set my expectations, do we have a loose time frame on when we might anticipate the next "synch up" between WROVER ESP-IDF and WROOM ESP-IDF?

**Comment by igrr** [comment]
Closing, since psram branch is now integrated into master.
