### ISSUE TITLE
https://docs.espressif.com/projects/esp-idf/en/release-v4.4/esp32s3/api-guides/usb-serial-jtag-console.html incorrectly describes USB pins as 18//19 and the should be 19/20 (IDFGH-7217)

### ISSUE THREAD

**Issue by davidbuzz** [espressif/esp-idf#8811]
## Problem Description

this is only a docs issue. 
release/v4.4 docs for -S3 chip incorrectly describe usb pins as 18/19 when in fact they are 19/20, please backport the corrected pin info to correct the v4.4 docs.

incorrect url:  https://docs.espressif.com/projects/esp-idf/en/release-v4.4/esp32s3/api-guides/usb-serial-jtag-console.html
connect pinout at this url: https://docs.espressif.com/projects/esp-idf/en/latest/esp32s3/api-guides/usb-serial-jtag-console.html

### Expected Behavior

earlier release docs should be accurately updated when blatently incorrect information is in them, not just 'fix master'.

### Actual Behavior

stable release doc don't match hardware reality, can't change reality, must change docs.

**Comment by igrr** [comment]
The issue has been fixed in https://github.com/espressif/esp-idf/commit/70c336963b787e0d797156330bab328fe2613f89, new documentation is available at https://docs.espressif.com/projects/esp-idf/en/release-v4.4/esp32s3/api-guides/usb-serial-jtag-console.html#hardware-requirements.

**Comment by davidbuzz** [comment]
thx
