### ISSUE TITLE
Some packets cannot be captured in sniffer mode (IDFGH-7229)

### ISSUE THREAD

**Issue by wgcod** [espressif/esp-idf#8823]
I'm very sorry to reply to the issue submitted before, https://github.com/espressif/esp-idf/issues/5375.
I repeated the problem and tested some results as follows:
![image](https://user-images.githubusercontent.com/48508117/164959747-099dfb49-2e3b-438c-9ed4-f334e1bead27.png)
![image](https://user-images.githubusercontent.com/48508117/164959775-56d5db8b-70be-47cd-848f-1677a8eb5acc.png)
![image](https://user-images.githubusercontent.com/48508117/164959796-2c3864a1-aba6-4edc-8ae8-5a853dd4db93.png)
now reset
![image](https://user-images.githubusercontent.com/48508117/164959823-8191ffa9-211e-4838-8b21-ac92a80323d0.png)
![image](https://user-images.githubusercontent.com/48508117/164959832-15dfb5b7-e1a4-4a32-ba98-b88ebf30273d.png)
reset again
![image](https://user-images.githubusercontent.com/48508117/164959881-e3dd303f-bf4b-4241-92b8-610277cf12ec.png)
![image](https://user-images.githubusercontent.com/48508117/164959888-a4205727-fb6e-429e-b965-26f6437cf653.png)
![image](https://user-images.githubusercontent.com/48508117/164959911-f7c3f37b-e548-41a1-b320-514a2c55895f.png)

It seems that 'rx state' is incremented, and the others are 0.
Data type packets cannot be captured in the process. They are displayed as QoS data (2:8) with other packet capture tools (rtl8812 or mt7612). However, with the transmission of QoS packets, esp32 returns a large number of misc type packets. Possible reasons?

**Comment by jack0c** [comment]
@wgcod to summarize, ESP32 in your side can't receive packets from AP6212A, but from @zhangyanjiaoesp side, it can.
However, with the transmission of QoS packets, esp32 returns a large number of misc type packets.
I think the reasons may be:
1. FCS error, hardware will treat them as misc type packets
2. length error(from the signal part), hardware will treat them as misc type packets

If you have many AP6212A modules, I suggest test every one. And if you can send the bad AP6212A to @zhangyanjiaoesp , it will be the best.

**Comment by wgcod** [comment]
However, packets that cannot be received by esp32 can be received by other packet capturing tools. Screenshots of some packets are in the https://github.com/espressif/esp-idf/issues/5375. There are no length errors and FCS errors. And several ap6212a have been tested for the same problem.Can I send you an AP6212A?@zhangyanjiaoesp

**Comment by zhangyanjiaoesp** [comment]
> However, packets that cannot be received by esp32 can be received by other packet capturing tools. Screenshots of some packets are in the #5375. There are no length errors and FCS errors. And several ap6212a have been tested for the same problem.Can I send you an AP6212A?@zhangyanjiaoesp

Yes, you can send me an AP6212A, and I will try to reproduce the issue on my side. You can send email to sales@espressif.com, in the email, please describe this issue briefly and provide the github issue link, then my colleague will tell you how to mail the AP6212A ?

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to short of feedback, feel free to reopen with more updates. Thanks.
