### ISSUE TITLE
How can I change the boot UART's baud rate? (IDFGH-7234)

### ISSUE THREAD

**Issue by Eran125** [espressif/esp-idf#8828]
Hi,
My project use UART with baud rate 921600, but the boot use UART with baud 115200.
Every powerup or reset or wakeup see garbage in PC terminal for the boot outputs until my app config the UART to the terminal baud 921600.
Is there a way to config the boot to use 921600 baud as my app?

**Comment by igrr** [comment]
ROM bootloader output baud rate cannot be changed, but there are eFuse bits available to disable ROM bootloader output. The baud rate of the 2nd stage bootloader and the application can be configured in menuconfig.

For details about eFuse, please check the technical reference manual of the chip you are using.

(I would provide more specific instructions, but you didn't specify which chip you are using. Kind request, please do fill in the issue template next time you open an issue!)
