### ISSUE TITLE
Guru Meditation Error: Core  0 panic'ed (InstrFetchProhibited). Exception was unhandled. when using EXT_RAM_ATTR (IDFGH-7238)

### ISSUE THREAD

**Issue by franz-ms-muc** [espressif/esp-idf#8832]
Working Code:

```c
#include <stdio.h>
#include "sdkconfig.h"
#include "esp_attr.h"

typedef void(*func_t)(void);

static void func(void)
{
    printf("func\n");
}

func_t  func_ext = &func;

void app_main(void)
{
    printf("Hello world!\n");
    (*func_ext)();
}
```

Failing Code:

```c
#include <stdio.h>
#include "sdkconfig.h"
#include "esp_attr.h"

typedef void(*func_t)(void);

static void func(void)
{
    printf("func\n");
}

func_t EXT_RAM_ATTR func_ext = &func;

void app_main(void)
{
    printf("Hello world!\n");
    (*func_ext)();
}
```

the failing code brings:

```shellsession
Guru Meditation Error: Core  0 panic'ed (InstrFetchProhibited). Exception was unhandled.
```

testing:

```c
    ESP_LOGI(TAG, "func_ext = %p", func_ext);
```

give:

```shellsession
Hello world!
I (1276) func_ext: func_ext = 0x0
```

```shellsession
Hello world!
I (1275) func_ext: func_ext = 0x400d577c
```

adding another `func_ext = &func;` before the call 

```c
    func_ext = &func;
    (*func_ext)();
```

then it works.

while the 0x0 happens when the `EXT_RAM_ATTR` is in place.

**Comment by igrr** [comment]
I think the reason is that EXT_RAM_ATTR is supposed to be applied to zero-initialized variables (.bss segment) only. The macro name isn't clear about this, and for that reason we have deprecated EXT_RAM_ATTR in favour of EXT_RAM_BSS_ATTR in v5.0 (https://docs.espressif.com/projects/esp-idf/en/latest/esp32/migration-guides/system.html#esp-common).

**Comment by f-hoepfinger-hr-agrartechnik** [comment]
https://en.wikipedia.org/wiki/.bss

**Comment by f-hoepfinger-hr-agrartechnik** [comment]
does BSS really mean zero-initialized variables in General, or only at Espressif ?

**Comment by igrr** [comment]
Yes, .bss is used for zero-initialized variables in general. If you compile a program with a zero-initialized global variables on the PC (e.g. on Linux) and run objdump on it, the variable will also be in the .bss section.

**Comment by franz-ms-muc** [comment]
Thanks.

Any idea of an Release Date for 5.0?

Holen Sie sich Outlook für Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by AxelLin** [comment]
> Thanks. Any idea of an Release Date for 5.0? 

https://github.com/espressif/esp-idf/releases/tag/v5.0

**Comment by franz-ms-muc** [comment]
Problem solved so far.
