### ISSUE TITLE
[v4.4][ESP32-S3] esp_restart() does not let bootloader regain control of GPIO outputs (IDFGH-7242)

### ISSUE THREAD

**Issue by chipweinberger** [espressif/esp-idf#8836]
Using v4.4.1

I use a custom booloader that uses GPIOs outputs.

bootloader_start.c
```
static int select_partition_number(bootloader_state_t *bs)
{
    // turn on Red & Blue LED 
    esp_rom_gpio_pad_select_gpio(15);
    esp_rom_gpio_pad_select_gpio(16);
    gpio_ll_output_enable(&GPIO, 15);
    gpio_ll_output_enable(&GPIO, 16);
    gpio_ll_set_level(&GPIO, 15, 1);
    gpio_ll_set_level(&GPIO, 16, 1);
    ....
}
```

It works as expected after a power reset (unplug VCC).

However, when doing esp_restart(), the bootloader is unable to change the LED color. 

The GPIOs stay the same value as whatever the app last set them to. 

**Note, when running, the app uses LEDC (i.e ledc_timer_config) to control these GPIOs.**

**Comment by chipweinberger** [comment]
I've tried calling this but no success.

```
ledc_timer_rst(LEDC_LOW_SPEED_MODE, LEDC_TIMER_1);
ledc_timer_rst(LEDC_LOW_SPEED_MODE, LEDC_TIMER_2);
esp_restart();
```

**Comment by negativekelvin** [comment]
Did you try esp_rom_gpio_connect_out_signal

**Comment by chipweinberger** [comment]
No. How do I use that? Not familiar with the arguments.

**Comment by chipweinberger** [comment]
That worked!
