### ISSUE TITLE
ESP32-C3: ESP_CONSOLE_USB_SERIAL_JTAG does not work if terminal program does not support escape sequences (IDFGH-7248)

### ISSUE THREAD

**Issue by dimka-rs** [espressif/esp-idf#8839]
## Environment

- Development Kit:      ESP32-C3-DevKitC-02
- Kit version: v1.1
- Module or chip used:  ESP32-C3-WROOM-02
- IDF version: v4.4
- Build System:         idf.py
- Compiler version: riscv32-esp-elf-gcc.exe (crosstool-NG esp-2021r2-patch2) 8.4.0
- Operating System:     Windows 11
- (Windows only) environment type: PowerShell
- Using an IDE?: Yes, VS Code
- Power Supply:         USB

## Problem Description
I'm trying to write a python script to send commands to ESP32-C3 over USB console (Not USB-UART chip) and read responses. Putty works fine with the terminal, but simple python ```serial.readline()``` does not. Figured out the reasons:

1. ```linenoiseProbe()``` blocks on ```read()``` even though non-blocking mode is set. Console will not start until you send at least 4 bytes in response to ```fprintf(stdout, "\x1b[5n");```

2. ```linenoiseProbe()``` does not check if respose is correct (```ESC[0n``` or ```ESC[3n```) so any incoming bytes are treated as correct response and terminal program is treated as if it supports escape sequences and colors.

Terminal program response may be verified this way:
components\console\linenoise\linenoise.c:1066

    +   if (read_bytes == 0 && c != 0x1b)
    +   {
    +       break;
    +   }
        read_bytes += cb;

### Expected Behavior
- ```read()``` should not block
- ```linenoiseProbe()``` should correctly detect terminal program capabilities

### Actual Behavior
- ```read()``` blocks even though non-blocking mode is set
- ```linenoiseProbe()``` always reports escape sequences are supported

**Comment by igrr** [comment]
Thanks for raising the issue @dimka-rs! Indeed the non-blocking reads are not implemented in the VFS driver for usb_serial_jtag: https://github.com/espressif/esp-idf/blob/9663a282b35d4533a81d18e201f6895611fb2643/components/vfs/vfs_usb_serial_jtag.c#L74-L76. It seems that the underlying usb_serial_jtag driver actually supports that, so we need to modify `usbjtag_rx_char_via_driver` function in the same file to check the `non_blocking` flag.

Linking https://github.com/espressif/esp-idf/issues/8789 which is probably related (although is for S3, not C3).
