### ISSUE TITLE
about example : ble_mesh_provisioner  --The mobile phone cannot query the bluetooth signal (IDFGH-7257)

### ISSUE THREAD

**Issue by 335980889** [espressif/esp-idf#8846]
Hi there, I'm using a ESP32-C3. and ESP32-S

IDF version v4.3.1
Build System: vscode+espidf
Yesterday afternoon at the company, using this ble_mesh_provisioner  example, the phone can scan to a bluetooth called ESP-BLE-MESH(I should remember correctly)
Using the onoff_server example, you can build your own network

IDF version v4.4
Build System: vscode+espidf
But at night I compile and burn the ble_mesh_provisioner example on another computer, and there is no bluetooth signal, no matter ESP32-C3 or ESP32-S

The next day, I re-used the company's environment, but it didn't work. The sample code has not changed
(IDF version v4.3.1  ;    Build System: vscode+espidf)

Replenish ： The onoff_server example can see the ESP-BLE-MESH bluetooth signal every time

I don't have a normal log, the following is the last test log

### ble_mesh_provisioner -------LOG
ESP-ROM:esp32c3-api1-20210207
Build:Feb  7 2021
rst:0x1 (POWERON),boot:0xe (SPI_FAST_FLASH_BOOT)
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fcd6100,len:0x1794
load:0x403ce000,len:0x8dc
load:0x403d0000,len:0x2984
SHA-256 comparison failed:
Calculated: 6f36735d5ccf6d87a541c43f37b21cd2370de42be27b169bc121d856f33f524d
Expected: 12dfbeb494194612a23581a5e45b1cbe659b7a7da21124311e9edfe7a46b524d
Attempting to boot anyway...
entry 0x403ce000
I (48) boot: ESP-IDF v4.3.1-dirty 2nd stage bootloader
I (49) boot: compile time 10:25:34
I (49) boot: chip revision: 3
I (51) boot.esp32c3: SPI Speed      : 80MHz
I (56) boot.esp32c3: SPI Mode       : DIO
I (60) boot.esp32c3: SPI Flash Size : 4MB
I (65) boot: Enabling RNG early entropy source...
I (70) boot: Partition Table:
I (74) boot: ## Label            Usage          Type ST Offset   Length
I (81) boot:  0 nvs              WiFi data        01 02 00009000 00006000
I (89) boot:  1 phy_init         RF data          01 01 0000f000 00001000
I (96) boot:  2 factory          factory app      00 00 00010000 00100000
I (104) boot: End of partition table
I (108) esp_image: segment 0: paddr=00010020 vaddr=3c0d0020 size=2e3c0h (189376) map
I (145) esp_image: segment 1: paddr=0003e3e8 vaddr=3fc8da00 size=01c30h (  7216) load
I (146) esp_image: segment 2: paddr=00040020 vaddr=42000020 size=c00e8h (786664) map
I (269) esp_image: segment 3: paddr=00100110 vaddr=3fc8f630 size=01720h (  5920) load
I (270) esp_image: segment 4: paddr=00101838 vaddr=40380000 size=0d888h ( 55432) load
I (284) esp_image: segment 5: paddr=0010f0c8 vaddr=50000000 size=00010h (    16) load
I (289) boot: Loaded app from partition at offset 0x10000
I (289) boot: Disabling RNG early entropy source...
I (306) cpu_start: Pro cpu up.
I (318) cpu_start: Pro cpu start user code
I (318) cpu_start: cpu freq: 160000000
I (318) cpu_start: Application information:
I (321) cpu_start: Project name:     ble_mesh_provisioner
I (327) cpu_start: App version:      1
I (331) cpu_start: Compile time:     Apr 27 2022 10:24:09
I (338) cpu_start: ELF file SHA256:  115b7fb303032f71...
I (344) cpu_start: ESP-IDF:          v4.3.1-dirty
I (349) heap_init: Initializing. RAM available for dynamic allocation:
I (356) heap_init: At 3FC98210 len 00027DF0 (159 KiB): DRAM
I (362) heap_init: At 3FCC0000 len 0001F060 (124 KiB): STACK/DRAM
I (369) heap_init: At 50000010 len 00001FF0 (7 KiB): RTCRAM
I (376) spi_flash: detected chip: generic
I (380) spi_flash: flash io: dio
I (385) sleep: Configure to isolate all GPIO pins in sleep state
I (391) sleep: Enable automatic switching of GPIO sleep configuration
I (398) cpu_start: Starting scheduler.
I (403) EXAMPLE: Initializing...
W (403) BTDM_INIT: esp_bt_controller_mem_release not implemented, return OK
I (413) BTDM_INIT: BT controller compile version [9c99115]
I (413) coexist: coexist rom version 9387209
I (423) phy_init: phy_version 500,985899c,Apr 19 2021,16:05:08
I (533) system_api: Base MAC address is not set
I (533) system_api: read default base MAC address from EFUSE
I (543) BTDM_INIT: Bluetooth MAC: a0:76:4e:4f:e7:9e

I (613) EXAMPLE: ESP_BLE_MESH_PROVISIONER_SET_DEV_UUID_MATCH_COMP_EVT, err_code 0
I (623) EXAMPLE: ESP_BLE_MESH_PROVISIONER_PROV_ENABLE_COMP_EVT, err_code 0
I (623) EXAMPLE: ESP_BLE_MESH_PROVISIONER_ADD_LOCAL_APP_KEY_COMP_EVT, err_code 0
I (633) EXAMPLE: ESP_BLE_MESH_PROVISIONER_BIND_APP_KEY_TO_MODEL_COMP_EVT, err_code 0
I (643) EXAMPLE: BLE Mesh Provisioner initialized

### onoff_server-------LOG
ESP-ROM:esp32c3-api1-20210207
Build:Feb  7 2021
rst:0x1 (POWERON),boot:0xc (SPI_FAST_FLASH_BOOT)
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fcd6100,len:0x1794
load:0x403ce000,len:0x8dc
load:0x403d0000,len:0x2984
entry 0x403ce000
I (30) boot: ESP-IDF v4.3.1-dirty 2nd stage bootloader
I (30) boot: compile time 18:18:34
I (30) boot: chip revision: 3
I (32) boot.esp32c3: SPI Speed      : 80MHz
I (37) boot.esp32c3: SPI Mode       : DIO
I (42) boot.esp32c3: SPI Flash Size : 2MB
I (47) boot: Enabling RNG early entropy source...
I (52) boot: Partition Table:
I (56) boot: ## Label            Usage          Type ST Offset   Length
I (63) boot:  0 nvs              WiFi data        01 02 00009000 00006000
I (70) boot:  1 phy_init         RF data          01 01 0000f000 00001000
I (78) boot:  2 factory          factory app      00 00 00010000 00100000
I (85) boot: End of partition table
I (89) esp_image: segment 0: paddr=00010020 vaddr=3c0c0020 size=2bf10h (179984) map
I (125) esp_image: segment 1: paddr=0003bf38 vaddr=3fc8da00 size=036a8h ( 13992) load
I (128) esp_image: segment 2: paddr=0003f5e8 vaddr=40380000 size=00a30h (  2608) load
I (131) esp_image: segment 3: paddr=00040020 vaddr=42000020 size=b6914h (747796) map
I (251) esp_image: segment 4: paddr=000f693c vaddr=40380a30 size=0cf2ch ( 53036) load
I (261) esp_image: segment 5: paddr=00103870 vaddr=50000000 size=00010h (    16) load
I (266) boot: Loaded app from partition at offset 0x10000
I (266) boot: Disabling RNG early entropy source...
I (281) cpu_start: Pro cpu up.
I (294) cpu_start: Pro cpu start user code
I (294) cpu_start: cpu freq: 160000000
I (294) cpu_start: Application information:
I (297) cpu_start: Project name:     onoff_server
I (302) cpu_start: App version:      1
I (306) cpu_start: Compile time:     Apr 26 2022 18:17:14
I (313) cpu_start: ELF file SHA256:  eec3bab95319cd47...
I (318) cpu_start: ESP-IDF:          v4.3.1-dirty
I (324) heap_init: Initializing. RAM available for dynamic allocation:
I (331) heap_init: At 3FC98260 len 00027DA0 (159 KiB): DRAM
I (337) heap_init: At 3FCC0000 len 0001F060 (124 KiB): STACK/DRAM
I (344) heap_init: At 50000010 len 00001FF0 (7 KiB): RTCRAM
I (351) spi_flash: detected chip: generic
I (355) spi_flash: flash io: dio
I (360) sleep: Configure to isolate all GPIO pins in sleep state
I (366) sleep: Enable automatic switching of GPIO sleep configuration
I (373) cpu_start: Starting scheduler.
I (378) EXAMPLE: Initializing...
I (378) gpio: GPIO[8]| InputEn: 0| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0
I (388) gpio: GPIO[8]| InputEn: 0| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0
I (398) gpio: GPIO[8]| InputEn: 0| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0
W (408) BTDM_INIT: esp_bt_controller_mem_release not implemented, return OK
I (408) BTDM_INIT: BT controller compile version [9c99115]
I (418) coexist: coexist rom version 9387209
I (428) phy_init: phy_version 500,985899c,Apr 19 2021,16:05:08
I (538) system_api: Base MAC address is not set
I (538) system_api: read default base MAC address from EFUSE
I (548) BTDM_INIT: Bluetooth MAC: 7c:df:a1:b4:28:a6

I (628) EXAMPLE: ESP_BLE_MESH_PROV_REGISTER_COMP_EVT, err_code 0
I (628) EXAMPLE: ESP_BLE_MESH_NODE_PROV_ENABLE_COMP_EVT, err_code 0
I (628) EXAMPLE: BLE Mesh Node initialized

Thanks

**Comment by JiaLWang** [comment]
Hi,

For the `ble_mesh_provisioner` example, the role of the device is Provisioner, it will not send `unprovisioned device beacon` message. For the `onoff_server` example, the role of the device is Node, it will send `unprovisioned device beacon` message. Therefore, you can scan to a bluetooth signal named ESP-BLE-MESH .

But what you said above, `yesterday afternoon at the company, using this ble_mesh_provisioner example, the phone can scan to a bluetooth called ESP-BLE-MESH(I should remember correctly).` 
May be a signal from another device. If you saved the log, you can compare whether the MAC address of the device matches the Bluetooth MAC address in the log.

Hope it can help you.
