### ISSUE TITLE
'RTC_WDT_STG_SEL_OFF' was not declared in this scope in file rtc_wdt.h (IDFGH-7266)

### ISSUE THREAD

**Issue by nikidimitrow** [espressif/esp-idf#8855]
Before submitting a new issue, please follow the checklist and try to find the answer.

- [ x] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [x ] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [ x] I have searched the issue tracker for a similar issue and not found a similar issue.

If the issue cannot be solved after the steps before, please follow these instructions so we can get the needed information to help you in a quick and effective fashion.

1. Fill in all the fields under **Environment** marked with [ ] by picking the correct option for you in each case and deleting the others.
2. Describe your problem.
3. Include [debug logs from the "monitor" tool](https://docs.espressif.com/projects/esp-idf/en/latest/api-guides/tools/idf-monitor.html), or [coredumps](https://docs.espressif.com/projects/esp-idf/en/latest/api-guides/core_dump.html).
4. Providing as much information as possible under **Other items if possible** will help us locate and fix the problem.
5. Use [Markdown](https://guides.github.com/features/mastering-markdown/) (see formatting buttons above) and the Preview tab to check what the issue will look like.
6. Delete these instructions from the above to the below marker lines before submitting this issue.

**IMPORTANT: If you do not follow these instructions and provide the necessary details, your issue may not be resolved.**

----------------------------- Delete above -----------------------------

## Environment

- Development Kit:      ESP32-DevKitC
- Kit version (for WroverKit/PicoKit/DevKitC): v4
- Module or chip used:  ESP32-WROVER
- IDF version (run ``git describe --tags`` to find it): v4.4
- Build System:    idf.py
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it): xtensa-esp32-elf-gcc.exe (crosstool-NG esp-2021r2-patch2) 8.4.0
- Operating System:     [Windows|
- (Windows only) environment type: ESP Command Prompt
- Using an IDE?: No
- Power Supply:         USB

## Problem Description
1. Activated option "Allows RTC watchdog disable in user code"
2.  in file main.cpp in function app_main add #include "soc/rtc_wdt.h", also try with #include "spinlock.h" (remove soc/")
3. Run idf.py build in  ESP Command Prompt
4. Got compilation error in rtc_wdt.h

//Detailed problem description goes here.
In file included from ../main/main.cpp:1:

C:/Users/uie49957/esp/Espressif/frameworks/esp-idf-v4.4/components/esp_hw_support/include/soc/rtc_wdt.h:63:43: error: 'RTC_WDT_STG_SEL_OFF' was not declared in this scope
     RTC_WDT_STAGE_ACTION_OFF            = RTC_WDT_STG_SEL_OFF,          /*!< Disabled. This stage will have no effects on the system. */
                             
C:/Users/uie49957/esp/Espressif/frameworks/esp-idf-v4.4/components/esp_hw_support/include/soc/rtc_wdt.h:63:43: note: suggested alternative: 'RTC_WDT_STAGE3'
     RTC_WDT_STAGE_ACTION_OFF            = RTC_WDT_STG_SEL_OFF,          /*!< Disabled. This stage will have no effects on the system. */
                                           ^~~~~~~~~~~~~~~~~~~
                                           RTC_WDT_STAGE3
In file included from ../main/main.cpp:1:
C:/Users/uie49957/esp/Espressif/frameworks/esp-idf-v4.4/components/esp_hw_support/include/soc/rtc_wdt.h:64:43: error: 'RTC_WDT_STG_SEL_INT' was not declared in this scope
     RTC_WDT_STAGE_ACTION_INTERRUPT      = RTC_WDT_STG_SEL_INT,          /*!< Trigger an interrupt. When the stage expires an interrupt is triggered. */
                                           ^~~~~~~~~~~~~~~~~~~
C:/Users/uie49957/esp/Espressif/frameworks/esp-idf-v4.4/components/esp_hw_support/include/soc/rtc_wdt.h:64:43: note: suggested alternative: 'RTC_WDT_STAGE3'
     RTC_WDT_STAGE_ACTION_INTERRUPT      = RTC_WDT_STG_SEL_INT,          /*!< Trigger an interrupt. When the stage expires an interrupt is triggered. */
                                           ^~~~~~~~~~~~~~~~~~~
                                           RTC_WDT_STAGE3
C:/Users/uie49957/esp/Espressif/frameworks/esp-idf-v4.4/components/esp_hw_support/include/soc/rtc_wdt.h:65:43: error: 'RTC_WDT_STG_SEL_RESET_CPU' was not declared in this scope
     RTC_WDT_STAGE_ACTION_RESET_CPU      = RTC_WDT_STG_SEL_RESET_CPU,    /*!< Reset a CPU core. */
                                           ^~~~~~~~~~~~~~~~~~~~~~~~~
C:/Users/uie49957/esp/Espressif/frameworks/esp-idf-v4.4/components/esp_hw_support/include/soc/rtc_wdt.h:65:43: note: suggested alternative: 'RTC_CNTL_SW_SYS_RST_M'
     RTC_WDT_STAGE_ACTION_RESET_CPU      = RTC_WDT_STG_SEL_RESET_CPU,    /*!< Reset a CPU core. */
                                           ^~~~~~~~~~~~~~~~~~~~~~~~~
                                           RTC_CNTL_SW_SYS_RST_M
C:/Users/uie49957/esp/Espressif/frameworks/esp-idf-v4.4/components/esp_hw_support/include/soc/rtc_wdt.h:66:43: error: 'RTC_WDT_STG_SEL_RESET_SYSTEM' was not declared in this scope
     RTC_WDT_STAGE_ACTION_RESET_SYSTEM   = RTC_WDT_STG_SEL_RESET_SYSTEM, /*!< Reset the main system includes the CPU and all peripherals. The RTC is an exception to this, and it will not be reset. */
                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/Users/uie49957/esp/Espressif/frameworks/esp-idf-v4.4/components/esp_hw_support/include/soc/rtc_wdt.h:66:43: note: suggested alternative: 'RTC_CNTL_SWD_RESET_FLAG_M'
     RTC_WDT_STAGE_ACTION_RESET_SYSTEM   = RTC_WDT_STG_SEL_RESET_SYSTEM, /*!< Reset the main system includes the CPU and all peripherals. The RTC is an exception to this, and it will not be reset. */
                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                           RTC_CNTL_SWD_RESET_FLAG_M
C:/Users/uie49957/esp/Espressif/frameworks/esp-idf-v4.4/components/esp_hw_support/include/soc/rtc_wdt.h:67:43: error: 'RTC_WDT_STG_SEL_RESET_RTC' was not declared in this scope
     RTC_WDT_STAGE_ACTION_RESET_RTC      = RTC_WDT_STG_SEL_RESET_RTC     /*!< Reset the main system and the RTC. */
                                           ^~~~~~~~~~~~~~~~~~~~~~~~~
C:/Users/uie49957/esp/Espressif/frameworks/esp-idf-v4.4/components/esp_hw_support/include/soc/rtc_wdt.h:67:43: note: suggested alternative: 'RTC_WDT_STAGE_ACTION_RESET_CPU'
     RTC_WDT_STAGE_ACTION_RESET_RTC      = RTC_WDT_STG_SEL_RESET_RTC     /*!< Reset the main system and the RTC. */
                                           ^~~~~~~~~~~~~~~~~~~~~~~~~
                                           RTC_WDT_STAGE_ACTION_RESET_CPU
### Expected Behavior

Source code from Espressif to be compile

### Actual Behavior
Compilation error with not declared defines in the scope of this united

### Steps to reproduce

see Problem Description 

// If possible, attach a picture of your setup/wiring here.

![image](https://user-images.githubusercontent.com/10328871/165818666-084fc28a-b53f-4536-b939-0f53006ae749.png)

![image](https://user-images.githubusercontent.com/10328871/165818591-f6e2d62d-37e0-4ab5-9221-e92f152b4d85.png)

### Code to reproduce this issue

```cpp
// the code should be wrapped in the ```cpp tag so that it will be displayed better.
#include "esp_log.h"

#include "soc/rtc_wdt.h"

extern "C" void app_main(void)
{
	initServices();
	startOSTasks();
}

```
// If your code is longer than 30 lines, [GIST](https://gist.github.com) is preferred.

## Debug Logs

```
Debug log goes here, should contain the backtrace, as well as the reset source if it is a crash.
Please copy the plain text here for us to search the error log. Or attach the complete logs but leave the main part here if the log is *too* long.
```

## Other items if possible

- [ x] sdkconfig file (attach the sdkconfig file from your project folder)
- [ ] elf file in the ``build`` folder (**note this may contain all the code details and symbols of your project.**)
- [ ] coredump (This provides stacks of tasks.)

**Comment by nikidimitrow** [comment]
I believe this issue is related to [8038](https://github.com/espressif/esp-idf/issues/8038)

@igrr is still to use components/hal/include/hal/wdt_hal.h instead of rtc_wdt.h?

**Comment by igrr** [comment]
@nikidimitrow that's right, it is the same issue. Please use `#include "hal/wdt_hal.h"` instead of `soc/rtc_wdt.h`.
