### ISSUE TITLE
FatFS corruptions problem even in SDK v4.4.1 (IDFGH-7269)

### ISSUE THREAD

**Issue by filzek** [espressif/esp-idf#8858]
Even on released sdv 4.4.1 while the FatFS with wearleaveling is doing a write operation and a ESP32 is powered off the partition  corrupt the files.

This still a catastrophic scenario.

Please advise if the devs are willing to change behavior to make it true secure storage.

**Comment by igrr** [comment]
Hi @filzek, this issue is tracked in https://github.com/espressif/esp-idf/issues/8197, you have already commented there. There is no solution yet, but we will update that issue when this feature is available.
I'll close this issue as duplicate, please use the linked issue for discussion.
