### ISSUE TITLE
I wanted to play with an esp32... (IDFGH-7270)

### ISSUE THREAD

**Issue by Dan9678** [espressif/esp-idf#8859]
Just starting out here and so far this code has blue screened my machine once and it appears to have trouble with Windows paths.

**Comment by zikalino** [comment]
Hi @Dan9678 , could you please provide some more details?

**Comment by 0xjakob** [comment]
@Dan9678

Did you follow the [Getting Started Guide](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/get-started/index.html)?

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to short of feedback and details, feel free to reopen with more details. Thanks.
