### ISSUE TITLE
Moving Nimble example in to existing project is failing to find MYNEWT (I think) (IDFGH-7272)

### ISSUE THREAD

**Issue by teekaytk** [espressif/esp-idf#8861]
## Environment

- Development Kit:     ESP32 DEV KIT C
- Kit version: v4
- Module or chip used:  ESP32-WROOM-32|
- IDF version (run ``git describe --tags`` to find it):
    ESP-IDF v4.3-dev-472-gcf056a7d0b-dirty
- Build System:         idf.py
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it):
    // 1.22.0-80-g6c4433a
- Operating System:     docker

- Using an IDE?: no
- Power Supply:        USB

## Problem Description

I have existing project that is made up of a lot of copied in code from exiting examples from the examples directory. I just normally copy files from examples in to my project, change the main function, kconfig and copy in any dependencies if any and it usually works really well.

I am trying to now enable BLE and have gone into menu config and enabled Nimble stack. Then copied over the Nimble blecent example and changed the main function so that it is now being called by the original main.

However when I am building it seems to be failing on

```
In file included from ../main/include/app_blecent.h:23,
                 from ../main/app_misc.c:20:
/opt/esp/idf/components/bt/host/nimble/nimble/porting/nimble/include/modlog/modlog.h:35:16: error: missing binary operator before token "("
 #if (MYNEWT_VAL(LOG_LEVEL) > 0)
                ^
In file included from ../main/app_misc.c:20:
../main/include/app_blecent.h:44:34: warning: 'struct os_mbuf' declared inside parameter list will not be visible outside of this definition or declaration
     void print_mbuf(const struct os_mbuf *om);
                                  ^~~~~~~
../main/include/app_blecent.h:46:27: error: unknown type name 'ble_uuid_t'
     void print_uuid(const ble_uuid_t *uuid);
                           ^~~~~~~~~~
../main/include/app_blecent.h:54:9: error: expected specifier-qualifier-list before 'SLIST_ENTRY'
         SLIST_ENTRY(peer_dsc)
         ^~~~~~~~~~~
```
and it goes on.
I am quite sure I have followed all the steps but still cannot seem to get this to build.
 
### Expected Behavior
That it will build flawlessly
### Actual Behavior
fails to build
### Steps to reproduce

Thats a difficult one, but you could try and copy in file by file the 4x files realted to Nimble example including main.c, misc.c , peer.c and blecent.h

then try and build

**Comment by teekaytk** [comment]
My bad, I had any "auto-syntaxer" running that was rearranging the .h file includes causing the issues I was seeing

**Comment by garin-marlow** [comment]
@teekaytk what file did the order of .h includes matter? I'm seeing this same issue.

**Comment by garin-marlow** [comment]
ah, I found the root cause, esp_central.h and esp_peripheral.h rely on ble_hs.h to already be included, the robust approach is to modify esp_central.h and esp_peripheral.h to include "ble_hs.h"

**Comment by meowchine1** [comment]
i have the same thing

**Comment by rahult-github** [comment]
> i have the same thing

Hi @Meowchine1  , have you ensured the header files also are correctly placed when you attempt to copy the contents ? 

if yes, then request you to share more information as to what steps you have done and what issue is being observed 

Also the original issue is on release/v4.3 which is EOL. Suggest to move to newer release branches
