### ISSUE TITLE
使用esp32的wifi下的例子的station_example_main.c显示连接不上 (IDFGH-7277)

### ISSUE THREAD

**Issue by amarelo-t** [espressif/esp-idf#8866]
你好，我在使用实例项目的时，一直显示wifi station: Failed to connect to SSID:amarelo, password:amarelo@12，整篇实例文档我只修改了SSID ，PASS还有一个MAXIMUM_RETRY，如下
![wifi2](https://user-images.githubusercontent.com/64177825/166097541-01cc0ebf-0e6f-4cce-b744-41325171a362.png)
下面是我一直连接不上的提示
![wifi](https://user-images.githubusercontent.com/64177825/166097480-2e55fd42-d5bd-43f9-ba60-d2a7b7654cf8.png)
那个我想请问一下这个问题一般是什么问题，该如何解决呢，谢谢

**Comment by MaxwellAlan** [comment]
Hi @amarelo-t 
从log上看，没有发现 SSID: amarelo 的路由器，需要检查一下路由器的设置：

- 路由器是否开启 2.4 G 频段，ESP32 目前只支持2.4G频段；
- 路由器 SSID 是否正确
- 如果上述都正确的情况下，建议更新 esp-idf 到 最新的 release/v4.4 上进行测试

**Comment by amarelo-t** [comment]
谢谢你，问题已经解决了，感谢！

**Comment by Alvin1Zhang** [comment]
感谢反馈。
