### ISSUE TITLE
uart_set_hw_flow_ctrl while already connected (IDFGH-7290)

### ISSUE THREAD

**Issue by diplfranzhoepfinger** [espressif/esp-idf#8878]
uart_set_hw_flow_ctrl while already connected

this is somehow releated to : https://github.com/espressif/esp-protocols/issues/31

so Question, 
(not considering esp_modem) but for a pure UART: 

1. i am connected to a UART Partner, with UART_HW_FLOWCTRL_DISABLE.
2. I tell my Partner to enable HW Flowcontrol. 
3. I want to switch from UART_HW_FLOWCTRL_DISABLE --> UART_HW_FLOWCTRL_CTS_RTS

do i need to Disconnect and call uart_driver_delete and another uart_driver_install, or can this work on the Fly ? 

same Story about changing Baudrate while connected ? 

Thanks, 
Franz

**Comment by Alvin1Zhang** [comment]
Thanks for reporting. Would you please help provide more details as suggested in the [issue template](https://github.com/espressif/esp-idf/issues/new?assignees=&labels=&template=bug_report.md&title=)? Information like elf, sdk configuration, backtrace, log outputs, commit ID, hardware and etc. would help us debug further. Thanks.

**Comment by diplfranzhoepfinger** [comment]
we tested, and it does work.
