### ISSUE TITLE
https://dl.espressif.com/dl/esp32s3_rom.elf 404 Not Found  (IDFGH-7304)

### ISSUE THREAD

**Issue by hardyacht** [espressif/esp-idf#8892]
On https://docs.espressif.com/projects/esp-idf/en/release-v4.4/esp32s3/api-guides/core_dump.html#rom-functions-in-backtraces the link to the esp32s3 is 404 NOt Found:  https://dl.espressif.com/dl/esp32s3_rom.elf

**Comment by hardyacht** [comment]
Sended to me via email

**Comment by igrr** [comment]
Let's keep the issue open until the file is provided.

**Comment by igrr** [comment]
ROM ELF files are now provided at https://github.com/espressif/esp-rom-elfs/releases, and the docs have been updated in 8abef173a1cd234cd72305d234472b548eeb331b.
