### ISSUE TITLE
Bluetooth mode classic bt or ble? (IDFGH-7314)

### ISSUE THREAD

**Issue by hcanak** [espressif/esp-idf#8902]
https://github.com/espressif/esp-idf/blob/1329b19fe494500aeb79d19b27cfd99b40c37aec/examples/bluetooth/bluedroid/ble/gatt_client/main/gattc_demo.c#L449

ESP_BT_MODE_CLASSIC_BT should change to ESP_BT_MODE_BLE.  Can you verify?

**Comment by igrr** [comment]
The code looks correct, memory related to BT Classic is released, then the controller is initialized in BLE only mode.

**Comment by hcanak** [comment]
Ok friend.
