### ISSUE TITLE
Partition missaligment for SDK 4.4.1 and future, Partition Update on the Fly needed  (IDFGH-7322)

### ISSUE THREAD

**Issue by filzek** [espressif/esp-idf#8909]
We have found out a problem while trying to move to new SDK that is the partition missaligment for the NVS type.
It must be in a position to be 4096 bytes in offset .

We need one tool inside the esp-idf that would allow us to change the partition on the fly, so, like 
nvs,              data,   nvs,         0xA000,     0x6000
otadata,       data,   ota,               ,    0x2000
phy_init,       data,   phy,               ,    0x1000
keys1,          data,   nvs_keys,       ,    0x6300
keys2,             data,   nvs,                ,    0x6D00

as off in SDK 4.4.1 or future the partitions must be aligned, and the size must be a divisible by 4096, so, the keys1 and fact arent the correct division, so in the field devices this should complete make the two partitions LOCKED to write, as it cant match the sector to write on it and result in failure.

We need to find one way to be able to realign the in production devices to allow it to be rewrite on the fly.

So by this example we need to reduce the size of keys1 to 0x6000
and also we will need to change the initial offset by minur 0x300 of keys2 and its size to 0x6000.

This is extreme important to solve this situation and the SDK has change and a lot of users will need this solution. 

If any problem happen to the partition it become useless.
nvs_err = nvs_flash_erase_partition(key2);
will return a error 258 that we think is realted to non 4096 aligment.

Two things shall be count on this, firmware upgrades will need a fix for this changes and the simple is allow us to change the partitions dada on the fly.

A function that fills an array of partitions with that information and a  function to save the partition to the flash. Simple and easy to do by your side and that allow everyone to fix this problem.

**Comment by igrr** [comment]
Hi @filzek,

For the devices in the field, you don't need to change the partition layout as long as the partitions are read only. These misaligned partitions can still be read normally. As I understand, that is the case for nvs_keys partition.

Updating the partition table in the field isn't safe and we don't recommend doing this.

For new devices you can adjust the partition table to use 4k-aligned partitions.

**Comment by filzek** [comment]
Yes we know, but this will make all the devices impossible to update as partition keys2 is updateable and depends on lot fo things to happen, so, some solution should be able to do on it. we know security is the reason to everything, but if this makes things impossible to use or update the security ended flawless.

**Comment by igrr** [comment]
Could you please explain the situation when you would require to update the nvs_keys partition?

Another thing, is there some space left in flash after all the partitions? It would be safer to define new partitions at the end, instead of trying to redefine the existing ones.

**Comment by filzek** [comment]
the keys are used then user iniate using google or apple voice assistant, it creates a bound of new keys inside the nvs besides fat or spiffs as it could loose data, those keys are saved in an encrypted format so no worry about this being read, but it is not fixed, so imagine the user that will be using apple (homekit) or google (gooogle home) and with cant use it anymore when add new devices to their home as upon it being installed it will upgrade to the latest firmware, and the nvskeys will be readonly.

In the case we show it is quite simple to solve with a partition fix and porpouse, so extreme minor changes. 
Also we can use the final flash to add new partition to it as well we only need to learn how to do it, we have about 50k left in the end of the flash, so its not problem, but we need to add this partition information to the partition table, is that possible?

**Comment by igrr** [comment]
If you have some space left at the end, then creating a partition there would be the best option. (To be clear for anyone else who might read this later: it is still not recommended as there are no safety checks; be sure to test this well before rolling out such and update to your devices!)

You can do this by registering a new partition at run time. Please see this answer: https://github.com/espressif/esp-idf/issues/8018#issuecomment-986737479.

**Comment by filzek** [comment]
We are writing a code right now, we have been able do to realtime replace partition, even if it is encrypted or not, so, its quite simple, but need to sign the partition to work correct, so, the best way is to have a build partition to full replace it on the running devices. 

This should be the idea for the update in field, as its quite simple running to do it, off course need to be a shadow copy of another device signed with the same certificate and with the new partition, it is quite simple the process and the devices could use the extracted partition to update, so no worry for any ota update in future.

We will do some new debugs prior to tell its perfect running, but so far we did it quite well.

**Comment by filzek** [comment]
In the test device the routine can work flawless and running good so far, tomorrow we will take from 5 batches from sfk 2.0, to 4.2,  and test it.

**Comment by igrr** [comment]
@filzek have you managed to solve the issue? If yes, can it be closed?

**Comment by filzek** [comment]
We used one solution that worked perfect.  Thanks.
