### ISSUE TITLE
Connection error with Windows Server WPA2-Enterprise MS-CHAPv2 (IDFGH-7327)

### ISSUE THREAD

**Issue by vdm97** [espressif/esp-idf#8914]
## Environment

- Development Kit: none
- Module or chip used:  ESP32-WROOM-32
- IDF version: v4.4.1
- Build System: CMake
- Compiler version: xtensa-esp32-elf-gcc.exe (crosstool-NG esp-2021r2-patch3) 8.4.0
- Operating System: Windows
- (Windows only) environment type: PowerShell
- Using an IDE?: VS Code with Espressif IDF v.1.4.0
- Power Supply: USB

## Problem Description

I have been trying to implement WPA2-Enterprise functionality on my ESP32. For that i have created a testing environment with an Ubuntu/FreeRADIUS. This environment works great with TTLS/PEAP MS-CHAPv2 with and without a certificate. Then i created a testing environment with Windows Server 2019/2022 with an AD/NPS which is configured to use Protected EAP (PEAP) or Secured Password (EAP-MSCHAP v2). I assume that the second option (EAP-MSCHAP v2) is equivalent to PEAP MS-CHAPv2 on FreeRADIUS. Sadly this setup does not work because i get an `wpa: Method private structure allocated failure` error.

I have searched the internet for answers and found some discussion like [here](https://github.com/espressif/esp-idf/issues/8453) and [here](https://github.com/espressif/esp-idf/issues/7422) which talk about fixed problems. Because of that i updated to v4.4.1 but the error is still present.

There is also [this](https://github.com/espressif/esp-idf/issues/1297) discussion which recommends to disable `Use MbedTLS crypto APIs` but this does not help in my case. But it also does not change the debug output, so does it get ignored in my setup?

After that i started digging in the ESP-IDF code and found that if i comment the check for stage 2 in [line 101 and 102](https://github.com/espressif/esp-idf/blob/v4.4.1/components/wpa_supplicant/src/eap_peer/eap_mschapv2.c#L101:L102) it starts working. This is strange because the rest of the method assumes the second stage and i think it should not work if this method would be called while in the first stage. Or this introduces a security bug as i do not understand the whole code..

NOTE: Strangely i have to set the `identity` to the same value as the `username` for Windows. Otherwise i get an error in the Windows log that an unknown user wants to connect with an username that i set in the `identity` (e.g. 'anonymous'). But if i set `identity` and `username` to the same value, FreeRADIUS flags it as an unsecure configuration which is understandable because i tell everyone the username not only in the second stage but in the first stage too.

## Code to reproduce this issue

```cpp
...
if (strlen(ssid) <= MAX_WIFI_SSID_LENGTH)
    strcpy((char*)config->sta.ssid, ssid);
const char* identity = "anonymous";
// esp_wifi_sta_wpa2_ent_set_identity((uint8_t*)identity, strlen(identity));
esp_wifi_sta_wpa2_ent_set_identity((uint8_t*)username, strlen(username));
if (strlen(username) <= MAX_WIFI_WPA2_ENTERPRISE_USERNAME_LENGTH)
    esp_wifi_sta_wpa2_ent_set_username((uint8_t*)username, strlen(username));
if (strlen(password) <= MAX_WIFI_PASSWORD_LENGTH)
    esp_wifi_sta_wpa2_ent_set_password((uint8_t*)password, strlen(password));
esp_wifi_sta_wpa2_ent_enable();
...
```

## Debug Logs

[Line 101 and 102 commented and MbedTLS enabled](https://gist.github.com/vdm97/4aaf7ca0d815d8fbf648121c005beb13)
[Line 101 and 102 commented and MbedTLS disabled](https://gist.github.com/vdm97/b99a9fa23753e09ff221c2d313e30127)
[Line 101 and 102 uncommented and MbedTLS enabled](https://gist.github.com/vdm97/09095bc5f85c7737a02bf62442e4ce2b)
[Line 101 and 102 uncommented and MbedTLS disabled](https://gist.github.com/vdm97/e677b855ebfc7c8939a505ccff9b9882)

**Comment by nishanth-radja** [comment]
@vdm97 can you also paste the error msg from the windows server...
Also can you paste the commit ID of the IDF you are using

**Comment by vdm97** [comment]
It is working now. I created the Windows Server testing environment after testing v4.3.1 on a production Windows Server and did not look at the specific error code the production environment was giving me. So after creating the testing environment and updating to v4.4.1 i had the above errors because the testing environment was configured wrong (and giving me a different error code as the production environment). The testing environment was configured to use Secured Password (EAP-MSCHAP v2) which seems to be just MS-CHAPv2 which the ESP32 rightfully did not like. With the changes i made (commenting 2 lines) i have probably shot a hole in the security logic of the ESP32 which is why it started working. After creating a self-signed certificate in my testing environment and configuring it to use Protected EAP (PEAP) with Secured Password (EAP-MSCHAP v2) inside it (the real equivalent to PEAP MS-CHAPv2 on FreeRADIUS) it started working with and without the public key of the self-signed certificate. If i do not report back, it is also working on the production environment. Thank you for your time.

NOTE: Strangely i still have to set the `identity` to the same value as the `username`. But i can live with that even if FreeRADIUS reports it as a security breach because the outer and inner identities are the same.. Setting the `username` to the string anonymous and the `identity` to the username does not work even though the Windows logs show the correct username but still give a credentials error. Probably a Windows feature i do not fully understand...

PS: It works with MbedTLS enabled 👍
