### ISSUE TITLE
RTL8201 - 10Mbps speed and PHY status (IDFGH-7337)

### ISSUE THREAD

**Issue by Simonefardella** [espressif/esp-idf#8923]
Hi guys, i've designed two boards with ESP32-WROOM and the ETH Phy chip RTL8201, i've received them today and flashed with the standard esp32 client using ESP32 Arduino.

I’m using the internal GPIO17 in order to generate the 50Mhz clock signal.

The sketch works, but i’m experiencing two main issues:

The speed of the RTL8201F-VB-CG is only working 10Megabits, why?
The RTL8201F-VB-CG becomes really hot without doing nothing and i don't know why this is happening!

Also, before the RTL8201 connects at 10M, this is the log that i see in arduino console and one of the two led flashes a couple of time.

![image](https://user-images.githubusercontent.com/5062855/167474317-04409487-4793-490b-992e-f977096d7065.png)

Nevermind, was a fault of my PCB, please close the issue and mark as solved.

**Comment by Simonefardella** [comment]
@suda-morris, as you developed these eth class, you have some info?

**Comment by kostaond** [comment]
Closed with no action since user reported the problem was caused by PCB issue.
