### ISSUE TITLE
Allow Port 0 in mdns

### ISSUE THREAD

**Issue by johsely1234** [espressif/esp-idf#893]
Currently it is not possible to set Port 0 in 
`esp_err_t mdns_service_add(mdns_server_t * server, const char * service, const char * proto, uint16_t port)`
because of the check 
if (!server || !service || !proto || **!port**) {

in the file mdns/mdns.c

Could you please just remove the !port so that I can use Port 0.
Best regards

**Comment by me-no-dev** [comment]
Port 0? What is the use case here?

**Comment by me-no-dev** [comment]
https://www.lifewire.com/port-0-in-tcp-and-udp-818145

**Comment by johsely1234** [comment]
The Mdns advertising should show port 0. I don't think the connection then really uses this port.

But this is defined by someone else, I can't change it.

**Comment by johsely1234** [comment]
But if it really makes no sense then I have to use another port anyway.

**Comment by negativekelvin** [comment]
Which "someone else" looks for a service advertised on port 0?

**Comment by johsely1234** [comment]
The client part of the connection is made by another person. In their old system they use port 0, so they want to use port 0 also in the new system. But I'll try to convince them not to use port 0.
