### ISSUE TITLE
Bug: ".../nimble/host/include/host/ble_uuid.h:97:9: error: expected primary-expression before '.' token" (IDFGH-7358)

### ISSUE THREAD

**Issue by Kampi** [espressif/esp-idf#8940]
## Environment

- IDF version (run ``git describe --tags`` to find it): 4.4.1

## Problem Description

Using `static const ble_uuid128_t gatt_svr_svc_sec_test_uuid = BLE_UUID128_INIT(0x2d, 0x71, 0xa2, 0x59, 0xb4, 0x58, 0xc8, 0x12, 0x99, 0x99, 0x43, 0x95, 0x12, 0x2f, 0x46, 0x59);` from the NimBLE `bleprph` example will produce the error:

```
In file included from C:/.platformio/packages/framework-espidf/components/bt/host/nimble/nimble/nimble/host/include/host/ble_hs_adv.h:24,
                 from C:/.platformio/packages/framework-espidf/components/bt/host/nimble/nimble/nimble/host/include/host/ble_gap.h:32,
                 from C:/.platformio/packages/framework-espidf/components/bt/host/nimble/nimble/nimble/host/include/host/ble_hs.h:33,
                 from src/Bluetooth/bluetooth.cpp:9:
C:/.platformio/packages/framework-espidf/components/bt/host/nimble/nimble/nimble/host/include/host/ble_uuid.h:97:9: error: expected primary-expression before '.' token
         .u.type = BLE_UUID_TYPE_128,    \
         ^
```

The problem can be solved by fixing the macro in `ble_uuid.h`:

```
#define BLE_UUID128_INIT(uuid128...)    \
    {                                   \
        .u = {                          \
            .type = BLE_UUID_TYPE_128,  \
        },                              \
        .value = { uuid128 },           \
    }
```

------------------------------------

### **Edit: Created a ticket in the [Nimble Repo](https://github.com/espressif/esp-nimble/issues/42),**

------------------------------

**Comment by rahult-github** [comment]
Change is part of upstream mynewt-nimble and committed in current master and release/v5.0  .
