### ISSUE TITLE
Unified Provisioning via HTTP REST server? (IDFGH-7367)

### ISSUE THREAD

**Issue by twlawrenceko** [espressif/esp-idf#8948]
Hello,

We would like to know if we set up a REST server on ESP, what is the mechanism built inside ESPSoftAPProvisioning app that we can migrate into REST server? So user can visit webpage created by ESP and enter WiFi credentials for provisoning.

Thank you.

**Comment by laukik-hase** [comment]
Hello, @twlawrenceko!

WiFi Provisioning in ESP-IDF uses a custom protocol based on `protobuf` ([Protocol Buffers](https://github.com/protocolbuffers/protobuf)) for secure session establishment and sharing of credentials. You can read about the implementation [here](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/provisioning/provisioning.html).

If security is not an issue in your case, please check out [tonyp7/esp32-wifi-manager](https://github.com/tonyp7/esp32-wifi-manager) as a reference.

**Comment by mahavirj** [comment]
Hope reply in earlier comment is helpful here. Please use esp32.com forum for further questions.
