### ISSUE TITLE
aws_s3_ota_update path error

### ISSUE THREAD

**Issue by jaggi** [espressif/esp-idf#895]
hii when i run aws_s3_ota_update i am facing folowing error,could anyone help me to solve this error

Arduino: 1.8.1 (Windows 10), Board: "SparkFun ESP32 Thing, 80MHz, 921600"

Invalid library found in C:\Program Files (x86)\Arduino\libraries\MAX30100-Heart-Beat-Monitor-master: C:\Program Files (x86)\Arduino\libraries\MAX30100-Heart-Beat-Monitor-master
In file included from C:\Program Files (x86)\Arduino\hardware\espressif\esp32/tools/sdk/include/soc/soc/soc.h:20:0,

                 from C:\Program Files (x86)\Arduino\hardware\espressif\esp32/tools/sdk/include/esp32/rom/ets_sys.h:21,

                 from C:\Program Files (x86)\Arduino\hardware\espressif\esp32/tools/sdk/include/freertos/freertos/FreeRTOSConfig.h:108,

                 from C:\Program Files (x86)\Arduino\hardware\espressif\esp32/tools/sdk/include/freertos/freertos/FreeRTOS.h:99,

                 from C:\Program Files (x86)\Arduino\hardware\espressif\esp32\cores\esp32\esp32-hal-timer.h:28,

                 from C:\Program Files (x86)\Arduino\hardware\espressif\esp32\cores\esp32\esp32-hal.h:60,

                 from C:\Program Files (x86)\Arduino\hardware\espressif\esp32\cores\esp32\esp32-hal-adc.h:27,

                 from C:\Program Files (x86)\Arduino\hardware\espressif\esp32\cores\esp32\esp32-hal-adc.c:15:

C:\Program Files (x86)\Arduino\hardware\espressif\esp32/tools/sdk/include/soc/soc/io_mux_reg.h: In function 'PIN_PULLUP_DIS':

C:\Program Files (x86)\Arduino\hardware\espressif\esp32/tools/sdk/include/esp32/esp_assert.h:23:28: error: first argument to '__builtin_choose_expr' not a constant

             _Static_assert(__builtin_choose_expr(__builtin_constant_p(CONDITION), (CONDITION), 1), #MSG);   \

                            ^

C:\Program Files (x86)\Arduino\hardware\espressif\esp32/tools/sdk/include/soc/soc/soc.h:138:38: note: in expansion of macro 'TRY_STATIC_ASSERT'

 #define ASSERT_IF_DPORT_REG(_r, OP)  TRY_STATIC_ASSERT(!IS_DPORT_REG(_r), (Cannot use OP for DPORT registers use DPORT_##OP));

                                      ^

C:\Program Files (x86)\Arduino\hardware\espressif\esp32/tools/sdk/include/soc/soc/soc.h:169:13: note: in expansion of macro 'ASSERT_IF_DPORT_REG'

             ASSERT_IF_DPORT_REG((_r), REG_CLR_BIT);                                                                    \

             ^

C:\Program Files (x86)\Arduino\hardware\espressif\esp32/tools/sdk/include/soc/soc/io_mux_reg.h:96:5: note: in expansion of macro 'REG_CLR_BIT'

     REG_CLR_BIT(PIN_NAME, FUN_PU);

     ^

C:\Program Files (x86)\Arduino\hardware\espressif\esp32/tools/sdk/include/esp32/esp_assert.h:23:28: error: expression in static assertion is not constant

             _Static_assert(__builtin_choose_expr(__builtin_constant_p(CONDITION), (CONDITION), 1), #MSG);   \

                            ^

C:\Program Files (x86)\Arduino\hardware\espressif\esp32/tools/sdk/include/soc/soc/soc.h:138:38: note: in expansion of macro 'TRY_STATIC_ASSERT'

 #define ASSERT_IF_DPORT_REG(_r, OP)  TRY_STATIC_ASSERT(!IS_DPORT_REG(_r), (Cannot use OP for DPORT registers use DPORT_##OP));

                                      ^

C:\Program Files (x86)\Arduino\hardware\espressif\esp32/tools/sdk/include/soc/soc/soc.h:169:13: note: in expansion of macro 'ASSERT_IF_DPORT_REG'

             ASSERT_IF_DPORT_REG((_r), REG_CLR_BIT);                                                                    \

             ^

C:\Program Files (x86)\Arduino\hardware\espressif\esp32/tools/sdk/include/soc/soc/io_mux_reg.h:96:5: note: in expansion of macro 'REG_CLR_BIT'

     REG_CLR_BIT(PIN_NAME, FUN_PU);

     ^

C:\Program Files (x86)\Arduino\hardware\espressif\esp32/tools/sdk/include/soc/soc/io_mux_reg.h: In function 'PIN_PULLUP_EN':

C:\Program Files (x86)\Arduino\hardware\espressif\esp32/tools/sdk/include/esp32/esp_assert.h:23:28: error: first argument to '__builtin_choose_expr' not a constant

             _Static_assert(__builtin_choose_expr(__builtin_constant_p(CONDITION), (CONDITION), 1), #MSG);   \

                            ^

C:\Program Files (x86)\Arduino\hardware\espressif\esp32/tools/sdk/include/soc/soc/soc.h:138:38: note: in expansion of macro 'TRY_STATIC_ASSERT'

 #define ASSERT_IF_DPORT_REG(_r, OP)  TRY_STATIC_ASSERT(!IS_DPORT_REG(_r), (Cannot use OP for DPORT registers use DPORT_##OP));

                                      ^

C:\Program Files (x86)\Arduino\hardware\espressif\esp32/tools/sdk/include/soc/soc/soc.h:163:13: note: in expansion of macro 'ASSERT_IF_DPORT_REG'

             ASSERT_IF_DPORT_REG((_r), REG_SET_BIT);                                                                    \

             ^

C:\Program Files (x86)\Arduino\hardware\espressif\esp32/tools/sdk/include/soc/soc/io_mux_reg.h:101:5: note: in expansion of macro 'REG_SET_BIT'

     REG_SET_BIT(PIN_NAME, FUN_PU);

     ^

C:\Program Files (x86)\Arduino\hardware\espressif\esp32/tools/sdk/include/esp32/esp_assert.h:23:28: error: expression in static assertion is not constant

             _Static_assert(__builtin_choose_expr(__builtin_constant_p(CONDITION), (CONDITION), 1), #MSG);   \

                            ^

C:\Program Files (x86)\Arduino\hardware\espressif\esp32/tools/sdk/include/soc/soc/soc.h:138:38: note: in expansion of macro 'TRY_STATIC_ASSERT'

 #define ASSERT_IF_DPORT_REG(_r, OP)  TRY_STATIC_ASSERT(!IS_DPORT_REG(_r), (Cannot use OP for DPORT registers use DPORT_##OP));

                                      ^

C:\Program Files (x86)\Arduino\hardware\espressif\esp32/tools/sdk/include/soc/soc/soc.h:163:13: note: in expansion of macro 'ASSERT_IF_DPORT_REG'

             ASSERT_IF_DPORT_REG((_r), REG_SET_BIT);                                                                    \

             ^

C:\Program Files (x86)\Arduino\hardware\espressif\esp32/tools/sdk/include/soc/soc/io_mux_reg.h:101:5: note: in expansion of macro 'REG_SET_BIT'

     REG_SET_BIT(PIN_NAME, FUN_PU);

     ^

C:\Program Files (x86)\Arduino\hardware\espressif\esp32/tools/sdk/include/soc/soc/io_mux_reg.h: In function 'PIN_PULLDWN_DIS':

C:\Program Files (x86)\Arduino\hardware\espressif\esp32/tools/sdk/include/esp32/esp_assert.h:23:28: error: first argument to '__builtin_choose_expr' not a constant

             _Static_assert(__builtin_choose_expr(__builtin_constant_p(CONDITION), (CONDITION), 1), #MSG);   \

                            ^

C:\Program Files (x86)\Arduino\hardware\espressif\esp32/tools/sdk/include/soc/soc/soc.h:138:38: note: in expansion of macro 'TRY_STATIC_ASSERT'

 #define ASSERT_IF_DPORT_REG(_r, OP)  TRY_STATIC_ASSERT(!IS_DPORT_REG(_r), (Cannot use OP for DPORT registers use DPORT_##OP));

                                      ^

C:\Program Files (x86)\Arduino\hardware\espressif\esp32/tools/sdk/include/soc/soc/soc.h:169:13: note: in expansion of macro 'ASSERT_IF_DPORT_REG'

             ASSERT_IF_DPORT_REG((_r), REG_CLR_BIT);                                                                    \

             ^

C:\Program Files (x86)\Arduino\hardware\espressif\esp32/tools/sdk/include/soc/soc/io_mux_reg.h:106:5: note: in expansion of macro 'REG_CLR_BIT'

     REG_CLR_BIT(PIN_NAME, FUN_PD);

     ^

C:\Program Files (x86)\Arduino\hardware\espressif\esp32/tools/sdk/include/esp32/esp_assert.h:23:28: error: expression in static assertion is not constant

             _Static_assert(__builtin_choose_expr(__builtin_constant_p(CONDITION), (CONDITION), 1), #MSG);   \

                            ^

C:\Program Files (x86)\Arduino\hardware\espressif\esp32/tools/sdk/include/soc/soc/soc.h:138:38: note: in expansion of macro 'TRY_STATIC_ASSERT'

 #define ASSERT_IF_DPORT_REG(_r, OP)  TRY_STATIC_ASSERT(!IS_DPORT_REG(_r), (Cannot use OP for DPORT registers use DPORT_##OP));

                                      ^

C:\Program Files (x86)\Arduino\hardware\espressif\esp32/tools/sdk/include/soc/soc/soc.h:169:13: note: in expansion of macro 'ASSERT_IF_DPORT_REG'

             ASSERT_IF_DPORT_REG((_r), REG_CLR_BIT);                                                                    \

             ^

C:\Program Files (x86)\Arduino\hardware\espressif\esp32/tools/sdk/include/soc/soc/io_mux_reg.h:106:5: note: in expansion of macro 'REG_CLR_BIT'

     REG_CLR_BIT(PIN_NAME, FUN_PD);

     ^

C:\Program Files (x86)\Arduino\hardware\espressif\esp32/tools/sdk/include/soc/soc/io_mux_reg.h: In function 'PIN_PULLDWN_EN':

C:\Program Files (x86)\Arduino\hardware\espressif\esp32/tools/sdk/include/esp32/esp_assert.h:23:28: error: first argument to '__builtin_choose_expr' not a constant

             _Static_assert(__builtin_choose_expr(__builtin_constant_p(CONDITION), (CONDITION), 1), #MSG);   \

                            ^

C:\Program Files (x86)\Arduino\hardware\espressif\esp32/tools/sdk/include/soc/soc/soc.h:138:38: note: in expansion of macro 'TRY_STATIC_ASSERT'

 #define ASSERT_IF_DPORT_REG(_r, OP)  TRY_STATIC_ASSERT(!IS_DPORT_REG(_r), (Cannot use OP for DPORT registers use DPORT_##OP));

                                      ^

C:\Program Files (x86)\Arduino\hardware\espressif\esp32/tools/sdk/include/soc/soc/soc.h:163:13: note: in expansion of macro 'ASSERT_IF_DPORT_REG'

             ASSERT_IF_DPORT_REG((_r), REG_SET_BIT);                                                                    \

             ^

C:\Program Files (x86)\Arduino\hardware\espressif\esp32/tools/sdk/include/soc/soc/io_mux_reg.h:111:5: note: in expansion of macro 'REG_SET_BIT'

     REG_SET_BIT(PIN_NAME, FUN_PD);

     ^

C:\Program Files (x86)\Arduino\hardware\espressif\esp32/tools/sdk/include/esp32/esp_assert.h:23:28: error: expression in static assertion is not constant

             _Static_assert(__builtin_choose_expr(__builtin_constant_p(CONDITION), (CONDITION), 1), #MSG);   \

                            ^

C:\Program Files (x86)\Arduino\hardware\espressif\esp32/tools/sdk/include/soc/soc/soc.h:138:38: note: in expansion of macro 'TRY_STATIC_ASSERT'

 #define ASSERT_IF_DPORT_REG(_r, OP)  TRY_STATIC_ASSERT(!IS_DPORT_REG(_r), (Cannot use OP for DPORT registers use DPORT_##OP));

                                      ^

C:\Program Files (x86)\Arduino\hardware\espressif\esp32/tools/sdk/include/soc/soc/soc.h:163:13: note: in expansion of macro 'ASSERT_IF_DPORT_REG'

             ASSERT_IF_DPORT_REG((_r), REG_SET_BIT);                                                                    \

             ^

C:\Program Files (x86)\Arduino\hardware\espressif\esp32/tools/sdk/include/soc/soc/io_mux_reg.h:111:5: note: in expansion of macro 'REG_SET_BIT'

     REG_SET_BIT(PIN_NAME, FUN_PD);

     ^

Multiple libraries were found for "WiFi.h"
 Used: C:\Program Files (x86)\Arduino\hardware\espressif\esp32\libraries\WiFi
 Not used: C:\Program Files (x86)\Arduino\libraries\WiFi
exit status 1
Error compiling for board SparkFun ESP32 Thing.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by copercini** [comment]
One of the problems is: MAX30100-Heart-Beat-Monitor-master is not a library, just some examples, so putting it into libraries folder cause some errors

**Comment by FayeY** [comment]
Hi @jaggi , did the above suggestion help you resolve the issue?
