### ISSUE TITLE
Connecting esp with mertik maxitrol fireapp (IDFGH-7374)

### ISSUE THREAD

**Issue by revolutiongit** [espressif/esp-idf#8954]
I have the mertik maxitrol wifimodule, receiver. I wanted to establish connection between app and esp32 instead of wifimodule of mertik maxitrol. How to approach this. There is a protocol for the app. I have the protocol, but i dont know how to proceed. Please help.

**Comment by jack0c** [comment]
@revolutiongit I suggest you run some examples first. Steps you may need:
1. provision(SSID+password), you may use bluetooth, smartconfig, DPP and so on
2. scan and connect to AP
3. get IP, usually automatic done by DHCP client
4. raw API or socket for TCP or UDP
5. TLS/DTLS if necessary
6. application protocol over TCP or UDP

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, feel free to reopen.
