### ISSUE TITLE
[TW#14719] Cannot set up multiple GATTC connections to the same device

### ISSUE THREAD

**Issue by rojer** [espressif/esp-idf#896]
documentation seems to imply that multiple virtual connections to the same physical device should be possible, but in practice subsequent calls to `esp_ble_gattc_open(same_if, same_addr)` produce no effect whatsoever - return value is 0 (`ESP_OK`), but nothing happens - no events, no nothing.

**Comment by Weijian-Espressif** [comment]
hi @rojer ,you can open  multiple virtual connections to the same physical device. I will give you a example, please update the latest IDF and try.
[gatts_demo.c.zip](https://github.com/espressif/esp-idf/files/1343015/gatts_demo.c.zip)
[gattc_demo.c.zip](https://github.com/espressif/esp-idf/files/1343016/gattc_demo.c.zip)
