### ISSUE TITLE
ESP32 PPPOS support EC20  (IDFGH-7381)

### ISSUE THREAD

**Issue by smartmos** [espressif/esp-idf#8961]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

Please give as many details as you can. Include suggestions for useful APIs or interfaces if relevant.

**Additional context**

**Comment by david-cermak** [comment]
Hi @smartmos 

Could you please raise this feature request in [esp-protocols](https://github.com/espressif/esp-protocols/issues) repository? The PPPoS example was removed from IDF on latest branches; while it is still supported, new features would only be added to `esp_modem` component.

Have you tried to run the PPPoS example with Quectel's EC20 already? After checking the docs, it seems to me that it should still work and provide the basic connection functionally that the IDF example demonstrates. It supports traditional set of AT commands and PPP mode, as well. Which interface you're using? It supports UART, but also USB. Please note that the [USB-DTE](https://github.com/espressif/esp-protocols/tree/master/components/esp_modem/examples/modem_console#usb-dte-support) support has been recently added to `esp_modem`

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, feel free to reopen with more updates.
