### ISSUE TITLE
Interrupt wdt timeout in long-term HFP/SPP test (IDFGH-7386)

### ISSUE THREAD

**Issue by TVD-Contributor** [espressif/esp-idf#8966]
## Environment

- Development Kit: none
- Module or chip used:  ESP32-WROVER-IE
- IDF version v4.4.1
- Build System: CMake
- Compiler version xtensa-esp32-elf-gcc (crosstool-NG esp-2021r2-patch2) 8.4.0
- Operating System:     Windows
- (Windows only) environment type: VSCode
- Using an IDE?: VSCode
- Power Supply:         external 3.3V

## Problem Description

Running a long-term test (10 hrs) with active HFP-HF audio and active SPP serial port may result in Interrupt wdt timeout, leading to reboot.

### Expected Behavior
No Interrupt WDT timeout

### Actual Behavior
Experienced Interrupt WDT timeout during long-term test

### Steps to reproduce

1. Our application uses Bluekitchen BTStack component, with the ESP-IDF BT Controller
2. BTStack is configured with HFP-HF profile and SPP profile
3. Windows PC has an active connection HFP connection, with the SCO audio data being streamed in/out of I2S
4. Windows PC has an active SPP RFCOMM connection, which is routed to the ESP32's UART at 9600 baud. Traffic is around 11B every second, in both directions.
5. Leave running

### Code to reproduce this issue

```cpp

```

## Debug Logs

```
Guru Meditation Error: Core  0 panic'ed (Interrupt wdt timeout on CPU0). 

Core  0 register dump:
PC      : 0x401b7e1e  PS      : 0x00060035  A0      : 0x800d390d  A1      : 0x3ffd1b70  
A2      : 0x00000000  A3      : 0x00000000  A4      : 0x800974a8  A5      : 0x3ffbc080  
A6      : 0x00000003  A7      : 0x00060023  A8      : 0x8012f9ae  A9      : 0x3ffd1b40  
A10     : 0x00000000  A11     : 0x00000000  A12     : 0x800974a8  A13     : 0x3ffbc080  
A14     : 0x00000003  A15     : 0x00060023  SAR     : 0x00000000  EXCCAUSE: 0x00000005  
EXCVADDR: 0x00000000  LBEG    : 0x00000000  LEND    : 0x00000000  LCOUNT  : 0x00000000  


Backtrace:0x401b7e1b:0x3ffd1b700x400d390a:0x3ffd1b90 0x401c3c61:0x3ffd1bb0 0x40097281:0x3ffd1bd0 

0x401b7e1b: cpu_ll_waiti at C:/Users/tim.bedford/esp/esp-idf/components/hal/esp32/include/hal/cpu_ll.h:183
 (inlined by) esp_pm_impl_waiti at C:/Users/tim.bedford/esp/esp-idf/components/esp_pm/pm_impl.c:837
0x401c3c61: prvIdleTask at C:/Users/tim.bedford/esp/esp-idf/components/freertos/tasks.c:3973 (discriminator 1)
0x40097281: vPortTaskWrapper at C:/Users/tim.bedford/esp/esp-idf/components/freertos/port/xtensa/port.c:131
```

## Other items if possible

- [x] sdkconfig file (attach the sdkconfig file from your project folder)
[sdkconfig .txt](https://github.com/espressif/esp-idf/files/8704811/sdkconfig.txt)
- -- elf file in the ``build`` folder **commercially sensitive - I'll try get a minimal project running on Lyra **
- -- coredump ** I'll try capture on tonight **

**Comment by BetterJincheng** [comment]
@TVD-Contributor Based on the information you have provided, we judged this may be an issue that we have resolved. Please refer to https://github.com/espressif/esp-idf/commit/422cf3cf3772130b8bade8c34fef088a41ea9b8e . This is an issue introduced with "High Level Interrupt (HLI)" enabled and we have resolved this issue on the host.
 
- You can config "CONFIG_APP_BUILD_USE_FLASH_SECTIONS=n" to disable HLI.
- You may refer to https://github.com/espressif/esp-idf/commit/422cf3cf3772130b8bade8c34fef088a41ea9b8e to do a fix on your host side.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to short of feedback, feel free to reopen with more updates. Thanks.
