### ISSUE TITLE
[TW#14720] Fixed rate of wifi on ESP32

### ISSUE THREAD

**Issue by liulingliuf** [espressif/esp-idf#897]
@liuzfesp 你好，上次您做了一个固定ESP32发送速率的版本。经过这一段时间的使用，我们发现，当速率固定后与ESP32链接会不稳定。原因是发送beacon的速率也变为我设定的速率，不能够自适应调节会正常速率。所以，能不能帮我们做一个函数，功能为将固定速率模式设置回正常的模式。谢谢！

**Comment by liuzfesp** [comment]
@liulingliuf 这个是可以做的，之前给你的版本是临时版本，由于内部改动有些大，要改到完全没有问题，还需要些时间。最近项目排满了，如果不是特别急的话，2周之内给一个版本到你，你看行不？

**Comment by liulingliuf** [comment]
多谢！调整的时候可否把包长也增大一下。目前在esp32上最大包长是4000，可否延长到8000以上？

**Comment by liulingliuf** [comment]
@liuzfesp 现在固定速率发包能不能在AP和station模式下都可以使用？

**Comment by liuzfesp** [comment]
@liulingliuf 我提交了一个commit, 用于取消fix rate: [https://github.com/liuzfesp/esp-idf/blob/customer/fix_rate_for_github_customer_request/readme](url)

**Comment by liuzfesp** [comment]
不要忘记了做下面这步：将idf/componenets/esp32/wifi_lib_fix_rate中的.a copy到lib下面

**Comment by liulingliuf** [comment]
@liuzfesp 多谢！
