### ISSUE TITLE
Crash in rwbt.c (libbtdm_app.a) when using SPP and HFP (IDFGH-7395)

### ISSUE THREAD

**Issue by TVD-Contributor** [espressif/esp-idf#8975]
## Environment

- Development Kit: none
- Module or chip used:  ESP32-WROVER-IE
- IDF version v4.4.1
- Build System: CMake
- Compiler version (user code) xtensa-esp32-elf-gcc (crosstool-NG esp-2021r2-patch2) 8.4.0
- Compiler version (libbtdm_app.a) according to text embedded in libbtdm_app.a appears to be GCC: (crosstool-NG crosstool-ng-1.22.0-78-g4b87650) 5.2.0 
- Operating System:     Windows
- (Windows only) environment type: VSCode
- Using an IDE?: VSCode
- Power Supply:         external 3.3V

## Problem Description

Running a long-term test (45 minutes) with active HFP-HF audio and active SPP serial port may result in Interrupt wdt timeout, leading to reboot.

### Expected Behavior
No crash - invalid param is detected and ignored, or never passed to rwbt.c in the first place.

### Actual Behavior
Crash and reboot

### Steps to reproduce

1. Our application uses Bluekitchen BTStack component, with the ESP-IDF BT Controller
2. BTStack is configured with HFP-HF profile and SPP profile
3. Windows PC has an active connection HFP connection, with the SCO audio data being streamed in/out of I2S
4. Windows PC has an active SPP RFCOMM connection, which is routed to the ESP32's UART at 9600 baud. Traffic is around 11B every second, in both directions.
5. Leave running

### Code to reproduce this issue

Reference to rwbt.c is found only in libbtdm_app.a which is not visible to public.

## Debug Logs

```
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x40092f1c: f01d020c 00004136 f01d0000
Core  1 register dump:
PC      : 0x40092f23  PS      : 0x00060634  A0      : 0x80086d9d  A1      : 0x3ffc2228  
A2      : 0x00000000  A3      : 0x00000400  A4      : 0x00000000  A5      : 0x3f41362c  
A6      : 0x0000017d  A7      : 0xfffffffc  A8      : 0x8000814b  A9      : 0x3ffc2198  
A10     : 0x00000000  A11     : 0x3ffc21bb  A12     : 0x3ffc2167  A13     : 0x00000031  
A14     : 0x00000000  A15     : 0x3ffc216c  SAR     : 0x00000004  EXCCAUSE: 0x00000000  
EXCVADDR: 0x00000000  LBEG    : 0x40086ca5  LEND    : 0x40086cad  LCOUNT  : 0x00000000  


Backtrace:0x40092f20:0x3ffc2228 |<-CORRUPTED

0x40092f20: r_assert at C:/Users/tim.bedford/esp/esp-idf/components/bt/controller/esp32/bt.c:2018
```

## Other items if possible

- [x] sdkconfig file (attach the sdkconfig file from your project folder)
[sdkconfig .txt](https://github.com/espressif/esp-idf/files/8711843/sdkconfig.txt)
- -- elf file in the ``build`` folder **commercially sensitive - I'll try get a minimal project running on Lyra **
- -- coredump ** I'll try capture on tonight **

**Comment by BetterJincheng** [comment]
@TVD-Contributor Could you please provide some more information? a mininal project or the full log text ？

**Comment by Sherry616** [comment]
Thanks for reporting, will close due to short of feedback, feel free to reopen with more updates. 
Thanks for using our Espressif product!
