### ISSUE TITLE
module 'esptool' has no attribute '_main' (IDFGH-7400)

### ISSUE THREAD

**Issue by xiaguangbo** [espressif/esp-idf#8979]
## Environment

- Development Kit: nodemcu-32-s2
- Kit version (for WroverKit/PicoKit/DevKitC): master
- Module or chip used:  esp32s2
- IDF version (run ``git describe --tags`` to find it): v5.0-dev-2959-g31b7694551
- Build System: vscode 'Espressif IDF' plugin the 'ESP-IDF Build Project' button
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it): xtensa-esp32s2-elf-gcc.exe (crosstool-NG esp-2021r2-patch3) 8.4.0
- Operating System: Windows
- (Windows only) environment type: vscode 'Espressif IDF' plugin the PowerShell terminal
- Using an IDE?: vscode 'Espressif IDF' plugin
- Power Supply: USB

## Problem Description

vscode 'Espressif IDF' plugin the 'ESP-IDF Flash device' button：
```
> Executing task in folder esp32s2: d:\software\esp\.espressif\python_env\idf5.0_py3.8_env\Scripts\python.exe d:\software\esp\esp-idf\components\esptool_py\esptool\esptool.py -p COM6 -b 460800 --before default_reset --after hard_reset --chip esp32s2 write_flash --flash_mode dio --flash_freq 80m --flash_size detect 0x10000 main.bin 0x1000 bootloader/bootloader.bin 0x8000 partition_table/partition-table.bin <

Traceback (most recent call last):
  File "d:\software\esp\esp-idf\components\esptool_py\esptool\esptool.py", line 22, in <module>
    esptool._main()  # type: ignore
AttributeError: module 'esptool' has no attribute '_main'
终端进程“d:\software\esp\.espressif\python_env\idf5.0_py3.8_env\Scripts\python.exe 'd:\software\esp\esp-idf\components\esptool_py\esptool\esptool.py', '-p', 'COM6', '-b', '460800', '--before', 'default_reset', '--after', 'hard_reset', '--chip', 'esp32s2', 'write_flash', '--flash_mode', 'dio', '--flash_freq', '80m', '--flash_size', 'detect', '0x10000', 'main.bin', '0x1000', 'bootloader/bootloader.bin', '0x8000', 'partition_table/partition-table.bin'”已终止，退出代码: 1。
```

do it manually：
can see that the 'esptool' module exists
```
PS D:\xiaguangbo\project\dap\project\esp32s2> d:\software\esp\.espressif\python_env\idf5.0_py3.8_env\Scripts\python.exe
Python 3.8.7 (tags/v3.8.7:6503f05, Dec 21 2020, 17:59:51) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import esptool
>>> esptool._main()
esptool.py v3.3.1
usage: esptool [-h] [--chip {auto,esp8266,esp32,esp32s2,esp32s3beta2,esp32s3,esp32c3,esp32c6beta,esp32h2beta1,esp32h2beta2,esp32c2}] [--port PORT] [--baud BAUD]
               [--before {default_...
...
```

I tried adding 'peintf('\n aaa \n')' to 'D:\software\esp\.espressif\python_env\idf5.0_py3.8_env\Scripts\esptool.py' and 'D:\software\esp\.espressif\python_env\idf5.0_py3.8_env\Lib\site-packages\esptool.py', but I don't see the output, but I can see two outputs when I add it to 'd:\software\esp\esp-idf\components\esptool_py\esptool\esptool.py', apparently 'd:\software\esp\esp-idf\components\esptool_py\esptool\esptool.py' is importing itself

If 'idf.py' is used, it is normal

I renamed 'esptool.py' to 'esptool2.py' and executed it manually, the result is correct：
Although there is a 'No such file or directory: 'main.bin'' error in the middle, it is simply solved
```
PS D:\xiaguangbo\project\dap\project\esp32s2> d:\software\esp\.espressif\python_env\idf5.0_py3.8_env\Scripts\python.exe d:\software\esp\esp-idf\components\esptool_py\esptool\esptool2.py -p COM6 -b 460800 --before default_reset --after hard_reset --chip esp32s2 write_flash --flash_mode dio --flash_freq 80m --flash_size detect 0x10000 main.bin 0x1000 bootloader/bootloader.bin 0x8000 partition_table/partition-table.bin
usage: esptool write_flash [-h] [--erase-all] [--flash_freq {keep,80m,60m,48m,40m,30m,26m,24m,20m,16m,15m,12m}] [--flash_mode {keep,qio,qout,dio,dout}] [--flash_size FLASH_SIZE]
                           [--spi-connection SPI_CONNECTION] [--no-progress] [--verify] [--encrypt] [--encrypt-files <address> <filename> [<address> <filename> ...]]
                           [--ignore-flash-encryption-efuse-setting] [--compress | --no-compress]
                           <address> <filename> [<address> <filename> ...]
esptool write_flash: error: argument <address> <filename>: [Errno 2] No such file or directory: 'main.bin'
PS D:\xiaguangbo\project\dap\project\esp32s2> d:\software\esp\.espressif\python_env\idf5.0_py3.8_env\Scripts\python.exe d:\software\esp\esp-idf\components\esptool_py\esptool\esptool2.py -p COM6 -b 460800 --before default_reset --after hard_reset --chip esp32s2 write_flash --flash_mode dio --flash_freq 80m --flash_size detect 0x10000 build/main.bin 0x1000 build/bootloader/bootloader.bin 0x8000 build/partition_table/partition-table.bin
esptool.py v3.3.1
Serial port COM6
Connecting....
Chip is ESP32-S2
Features: WiFi, No Embedded Flash, No Embedded PSRAM, ADC and temperature sensor calibration in BLK2 of efuse V1
Crystal is 40MHz
MAC: 7c:df:a1:04:a5:86
Uploading stub...
Running stub...
Stub running...
Changing baud rate to 460800
Changed.
Wrote 161936 bytes (89867 compressed) at 0x00010000 in 2.2 seconds (effective 593.8 kbit/s)...
Hash of data verified.
Flash params set to 0x022f
Compressed 21872 bytes to 13748...
Wrote 21872 bytes (13748 compressed) at 0x00001000 in 0.5 seconds (effective 330.2 kbit/s)...
Hash of data verified.
Compressed 3072 bytes to 103...
Wrote 3072 bytes (103 compressed) at 0x00008000 in 0.1 seconds (effective 442.9 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting via RTS pin...
```

**Comment by radimkarnis** [comment]
Hello @xiaguangbo,
thank you for the detailed report, this will help us a lot!
There are reports of this issue in the esptool repository: https://github.com/espressif/esptool/issues/740
We will fix this ASAP.

**Comment by radimkarnis** [comment]
@dotlambda This issue seems to be a result of [this wrapper script](https://github.com/espressif/esp-idf/blob/master/components/esptool_py/esptool/esptool.py) importing itself. This wrapper is a part of ESP-IDF and serves as a compatibility layer. You can see that in this one, we try to remove the path to the script itself:

```python
    sys.path.remove(os.path.dirname(os.path.realpath(__file__)))  # do not import this script
```

https://github.com/espressif/esptool/pull/742 concerns a wrapper script, which is directly in the esptool repository. The issue is similar, but I don't think both of these can be solved in the same place.

**Comment by RavioliSauce** [comment]
@dotlambda I was getting the same "module 'esptool' has no attribute '_main'" error. Your fix worked for me! I am now able to communicate with my ESP8266!

**Comment by xiaguangbo** [comment]
@radimkarnis Today I reinstalled the whole environment and it works fine, I don't know if this is a code fix or something is wrong with my previous environment

**Comment by wreyford** [comment]
I used ESP-IDF setup in Visual Studio Code insiders, and installed Master and tools using the interface, on a Windows10 PC, and got the same issue now. I cannot flash my cod to ESP32-S3-DevKitC-1

> Traceback (most recent call last):
  File "c:\esp\esp-idf-master\esp-idf\components\esptool_py\esptool\esptool.py", line 22, in <module>
    esptool._main()  # type: ignore
AttributeError: module 'esptool' has no attribute '_main'

**Comment by xiaguangbo** [comment]
@wreyford Delete the `esptool_py` folder and use `git pull`, delete `./espressif/python_env` and reinstall using the `install` script, try

**Comment by LAestafa** [comment]
hola cuando intento flashear un esp32 me sale este error 
Traceback (most recent call last):
  File "C:\Users\Osniel\AppData\Local\Programs\Python\Python312\Scripts\esptool.py", line 37, in <module>
    esptool._main()
    ^^^^^^^^^^^^^
AttributeError: module 'esptool' has no attribute '_main'

como pudiera solucionar esto

**Comment by LAestafa** [comment]
porque me sale este error 

Traceback (most recent call last):
  File "C:\Users\Osniel\AppData\Local\Programs\Python\Python312\Scripts\esptool.py", line 37, in <module>
    esptool._main()
    ^^^^^^^^^^^^^
AttributeError: module 'esptool' has no attribute '_main'

si alguien pudiera ayudar

**Comment by invictus-anic3tus** [comment]
I have the exact same problem! I don't know what to do
