### ISSUE TITLE
ota data partition invalid and no factory, can't boot

### ISSUE THREAD

**Issue by hhcc2017** [espressif/esp-idf#898]

**Comment by igrr** [comment]
You need to flash the partition table again. You can do this by running
'make flash'.

On Thu, Aug 10, 2017 at 12:19 PM, 北京花花草草科技有限公司-丁建旺 <notifications@github.com

**Comment by FayeY** [comment]
Hi @hhcc2017 , did the above suggestion help you resolve the issue?

**Comment by projectgus** [comment]
In addition to @igrr 's suggestion, a proper fix for this problem is coming in IDF V3.0 (it will be merged to master shortly), meaning that invalid OTA data will no longer halt the boot (the bootloader will fall back to a sensible choice, in this case it will search starting from OTA 0.)

**Comment by projectgus** [comment]
This fix is now in the IDF master branch, as of 969f1bb9be1.
