### ISSUE TITLE
wifi速率低，udp测试才900k (IDFGH-7401)

### ISSUE THREAD

**Issue by llx4186041** [espressif/esp-idf#8980]
----------------------------- Delete below -----------------------------

udp发送测试速率才900k左右，再快就报errno 12. 
按照指导配置wifi没有左右。
[测试代码：
static void udp_server_task(void *pvParameters)
{
    char addr_str[1032];
    int addr_family = (int)pvParameters;
    int ip_protocol = 0;
	
    struct sockaddr_in destAddr;
	bzero(&destAddr,sizeof(struct sockaddr_in));
    //destAddr.sin_addr.s_addr = htonl(INADDR_BROADCAST);
    destAddr.sin_addr.s_addr = inet_addr("192.168.120.49");
    destAddr.sin_family = AF_INET;
    destAddr.sin_port = htons(PORT);

	int addr_len = sizeof(destAddr);
	
    while (1) {

        int sock = socket(addr_family, SOCK_DGRAM, ip_protocol);
        if (sock < 0) {
            ESP_LOGE(TAG, "Unable to create socket: errno %d", errno);
            break;
        }
        ESP_LOGI(TAG, "Socket created");

		int val = 1;
		int rv;
		rv = setsockopt(sock, SOL_SOCKET, SO_BROADCAST, &val, (socklen_t)sizeof(val));
		if (rv == -1) {
			ESP_LOGE(TAG,"setsockopt error: %d", errno);
		}

        while (1) {
			vTaskDelay(4/portTICK_PERIOD_MS);
			//ESP_LOGI(TAG,"mem %d",esp_get_free_heap_size());
            int err = sendto(sock, addr_str, 1032, 0, (struct sockaddr *)&destAddr,addr_len);
            if (err < 0) {
                ESP_LOGE(TAG, "Error occurred during sending: errno %d", errno);
                //break;
            }
          
        }

        if (sock != -1) {
            ESP_LOGE(TAG, "Shutting down socket and restarting...");
            shutdown(sock, 0);
            close(sock);
        }
    }
    vTaskDelete(NULL);
}
[]([url](url))](url)

esp_wifi_internal_tx 一直返回ERR_MEM。

**Comment by llx4186041** [comment]
[
[udp_server.txt](https://github.com/espressif/esp-idf/files/8716009/udp_server.txt)
](url)

**Comment by Alvin1Zhang** [comment]
@llx4186041 Thanks for reporting. Would you please help provide more details as suggested in the [issue template](https://github.com/espressif/esp-idf/issues/new?assignees=&labels=&template=bug_report.md&title=)? Information like elf, sdk configuration, backtrace, log outputs, commit ID, hardware and etc. would help us debug further. Thanks.
