### ISSUE TITLE
 When using the "esp_http_client" request to obtain the "http_server" created by "esp32", the value of the "client - > response - > buffer - > raw_len" field is always 0 (IDFGH-7405)

### ISSUE THREAD

**Issue by fan183579** [espressif/esp-idf#8983]
The IDF version used is 4.4. For some reasons, it is necessary to use "esp32" to create the client and server respectively and conduct data interaction. When using it, it is found that when the client obtains the data sent by the server in the "http_get" mode, the client serial port output is always empty. After troubleshooting, it is found that the value of the "raw_len" field is always 0, resulting in the failure to read the obtained message. The code fragment is attached below
![image](https://user-images.githubusercontent.com/89377999/169261233-4d919593-aed7-411e-9c45-38b50c7eac0d.png)
![image](https://user-images.githubusercontent.com/89377999/169261291-7f389a31-c446-438f-8eca-9fdb7b17acbe.png)
The following is the current temporary solution
![image](https://user-images.githubusercontent.com/89377999/169261445-8b6eabdf-b0a3-4896-b469-b800bcdb8d3c.png)

**Comment by ESP-YJM** [comment]
@fan183579 when you ues `esp_http_client_perform` to connect and get data, you couldn't get buffer after `esp_http_client_perform` return. You need get the buffer in `_http_event_handler` function and event https://github.com/espressif/esp-idf/blob/master/examples/protocols/esp_http_client/main/esp_http_client_example.c#L65.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to short of feedback, feel free to reopen with more updates. Thanks.
