### ISSUE TITLE
One-Shot pulse from the MCPWM modul with carrier modulation cannot be disabled (IDFGH-7406)

### ISSUE THREAD

**Issue by rob-bits** [espressif/esp-idf#8984]
If I call the function **mcpwm_carrier_init**() with MCPWM_ONESHOT_MODE_DIS parameter in the **mcpwm_carrier_config_t** the one shot pulse is not disabled.

Se this:
https://github.com/espressif/esp-idf/blob/58283e385a7cbd04b8f628af15b5acf633aac2f3/components/driver/mcpwm.c#L555

It calls the  **mcpwm_carrier_oneshot_mode_disable**() function:
https://github.com/espressif/esp-idf/blob/58283e385a7cbd04b8f628af15b5acf633aac2f3/components/driver/mcpwm.c#L524

And it sets the width with 0 value. But the datasheet states, if we set the 0 value, still the one shot pulse width will be equal to the pulse with of the subsequent pulses.

> The width of the first pulse is configurable. It may assume one of 16 possible values and is described by the
> formula below:
> T1stpulse = TPWM_clk ×8×(PWM_CARRIERx_PRESCALE +1)×(PWM_CARRIERx_OSHTW T H +1)

So if I the function sets PWM_CARRIERx_OSHTWTH to 0, still the pulse width will be equal to the period of the subsequent pulses.

I would like to implement the example waveform from the technical reference manual in the MCPWM section, PWM Carrier Submodule, where the generated signal does not have One-Shot pulse in the beginning (Figure 120: Example of Waveforms Showing PWM Carrier Action), but with the current MCPWM functions it is not possible.

![image](https://user-images.githubusercontent.com/40227041/169271823-488e3ca2-72a4-4b86-9d18-1490496f1762.png)

I was able to generate the signal which has a different first pulse as the subsequent pulses (Figure 121: Example of the First Pulse and the Subsequent Sustaining Pulses of the PWM Carrier Submodule) however I cannot disable the first pulse.

Is there any extra configuration needed to disable the one-shot pulse?  e.g. dead time configuration...

I think the current implementation of **mcpwm_carrier_oneshot_mode_disable**() is wrong. Or the naming missleading.

Here is how it looks like, if the **mcpwm_carrier_oneshot_mode_disable**() funciton is called.
![image](https://user-images.githubusercontent.com/40227041/169271402-70cf896d-dd96-4e69-a6b3-216f77272a84.png)

**Comment by suda-morris** [comment]
Hi @rob-bits That Figure has an assumption:
![image](https://user-images.githubusercontent.com/8869469/169439155-5b3884c9-5151-4042-9aaf-6af3864a559d.png)

And the deadtime module can' be used to eliminate the ontshot pulse, because the carrier module is after the deadtime module.

![image](https://user-images.githubusercontent.com/8869469/169439383-0324c780-0ec0-4bef-8142-46dbeecf39a7.png)
