### ISSUE TITLE
esp_ble_gap_disconnect 引起卡死 直至看门狗触发重启 (IDFGH-7416)

### ISSUE THREAD

**Issue by fzboffice** [espressif/esp-idf#8994]
idf commit fe1cf490b9e26689ce6d4b8268c97685e6e73c27

**Comment by Alvin1Zhang** [comment]
@fzboffice Thanks for reporting. Would you please help provide more details as suggested in the [issue template](https://github.com/espressif/esp-idf/issues/new?assignees=&labels=&template=bug_report.md&title=)? Information like elf, sdk configuration, backtrace, log outputs, commit ID, hardware and etc. would help us debug further. Thanks.

**Comment by fzboffice** [comment]
@Alvin1Zhang My description is wrong, esp_ ble_ gatts_ Close and ESP_ ble_ gap_ Disconnect will not cause jamming, it just will not cause a disconnect event, but the remote device will disconnect.
My device is esp32 and idf commit is c5deb7a9713887263b63549a891282f51a65d167

**Comment by fzboffice** [comment]
When I called it many times, the problem was solved
