### ISSUE TITLE
usbh_print_intf_desc prints wrong value for tbInterfaceClass (IDFGH-7422)

### ISSUE THREAD

**Issue by nickbits1024** [espressif/esp-idf#9000]
usbh_print_intf_desc in components\usb\usb_helpers.c prints the value of bInterfaceProtocol for its output of bInterfaceClass.  It is also does not print the values of bInterfaceSubClass or bInterfaceProtocol.

**Comment by Alvin1Zhang** [comment]
@nickbits1024 Thanks for reporting. Would you please help provide more details as suggested in the [issue template](https://github.com/espressif/esp-idf/issues/new?assignees=&labels=&template=bug_report.md&title=)? Information like elf, sdk configuration, backtrace, log outputs, commit ID, hardware and etc. would help us debug further. Thanks.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting and your contribution at https://github.com/espressif/esp-idf/pull/9001, we have put it under internal review queue, will update once there are progress, thanks.

**Comment by Alvin1Zhang** [comment]
PR https://github.com/espressif/esp-idf/pull/9001 has been accepted and merged, thanks for reporting and contribution again, feel free to reopen.
