### ISSUE TITLE
Ble mode with Bluedroid not support class of device set (IDFGH-7425)

### ISSUE THREAD

**Issue by hellolxhlinux** [espressif/esp-idf#9004]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

Please give as many details as you can. Include suggestions for useful APIs or interfaces if relevant.

**Additional context**

**Comment by hellolxhlinux** [comment]
I need to filter device with peripheral in host ,but device with bluedroid in esp32c3  not support class of device at ble mode ,I dont know why ?

**Comment by seaskycjh** [comment]
BLE does not have the concept of cod (class of device), cod can only be used in classic bt. You can set the appearace in advertise data to filter devices more precisely.
