### ISSUE TITLE
Hi @david-cermak (IDFGH-7430)

### ISSUE THREAD

**Issue by supradeeplohith** [espressif/esp-idf#9007]
Hi @david-cermak 

With the same network i am able to get data using http_mbedtls component, please help me in can i get only data when update is occurred, please help me with this.

*in the case of previous comment from your end if that would be a network issue i could  face isuue with using http_mbedtls also right? 

*now i would like u to request to tell me the changes in code, only if update occurs the updated data ( json)  with respect to node I should need to get the data

please refer all screenshot I've attached 

![1](https://user-images.githubusercontent.com/42844966/169797418-039ec822-d796-4fcf-84ab-b7695f471339.PNG)
![1](https://user-images.githubusercontent.com/42844966/169797435-ed3203d0-b91c-483c-a015-0b0684d96838.PNG)
![5](https://user-images.githubusercontent.com/42844966/169797449-36541ccd-4649-40af-8609-63064cbb2c90.PNG)
![4](https://user-images.githubusercontent.com/42844966/169797458-c66a3b48-11cd-4229-aa1f-38a12cbbf10b.PNG)
[htps_mbedtls.txt](https://github.com/espressif/esp-idf/files/8753671/htps_mbedtls.txt)

_Originally posted by @supradeeplohith in https://github.com/espressif/esp-idf/issues/8995#issuecomment-1134481645_

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, have replied in the linked issue. Feel free to reopen or create a post on forum https://esp32.com, thanks.
