### ISSUE TITLE
build bt_hid_mouse_hid err : undefined reference to 'esp_bt_gap_set_pin ,and so esp_bt_gap_set_xxx' (IDFGH-7434)

### ISSUE THREAD

**Issue by hellolxhlinux** [espressif/esp-idf#9010]
target : esp32c3
build demo : bt_hid_mouse_hid
conifg : CONFIG_BT_BLUEDROID_ENABLED=y

idf.py build

**Comment by Wth-Esp** [comment]
Hi，@hellowlxhlinux

Please note that ESP32-C3 support only Low Energy Bluetooth, not support Classic Bluetooth.
And in IDF, there is no demo named `bt_hid_mouse_hid`, please check again the demo you have tried.

Thanks.

**Comment by hellolxhlinux** [comment]
Thinks ,I know.
