### ISSUE TITLE
Wifi power_save example is broken on ESP32S3 (IDFGH-7437)

### ISSUE THREAD

**Issue by idea--list** [espressif/esp-idf#9013]
## Environment

- Development Kit:      Adafruit ESP32S3 Feather
- IDF version: V4.4.1
- Build System: idf.py
- Compiler version: xtensa-esp32-elf-gcc V8.4.0
- Operating System: Windows 10 x64
- (Windows only) environment type: ESP Command Prompt
- Using an IDE?: No
- Power Supply: USB

## Problem Description

On my old ESP32 board the wifi power_save example shipped with esp-idf works as expected.
Compiling the same code to my ESP32S3 board and looking at the terminal i find the board never gets an IP address and also the power consumption remains always high, ca 95mA. Meaning the board can not connect to the AP for some reason and as a consequence the board will never go to modem sleep for the defined number of listen intervals.

My impression so far is that the ESP32S3 is not ready yet to be used in hardware designed for production.

### Expected Behavior
Board should connect to the defined AP and then lower power consumption

### Actual Behavior
Board fails to connect to the AP and thus consumption remains high

### Steps to reproduce
Compile&run wifi power_save example shipped with esp-idf on an ESP32S3 board.

### Code to reproduce this issue
power_save example among the wifi specific examples shipped with esp-idf

## Debug Logs

```
I (0) cpu_start: App cpu up.
I (251) cpu_start: Pro cpu start user code
I (251) cpu_start: cpu freq: 80000000
I (252) cpu_start: Application information:
I (254) cpu_start: Project name:     wifi_low_power
I (260) cpu_start: App version:      1
I (264) cpu_start: Compile time:     May 24 2022 14:17:28
I (270) cpu_start: ELF file SHA256:  f8d5fb7fe0a34cae...
I (276) cpu_start: ESP-IDF:          v4.4.1
I (281) heap_init: Initializing. RAM available for dynamic allocation:
I (288) heap_init: At 3FC9F8F8 len 00040708 (257 KiB): D/IRAM
I (295) heap_init: At 3FCE0000 len 0000EE34 (59 KiB): STACK/DRAM
I (301) heap_init: At 3FCF0000 len 00008000 (32 KiB): DRAM
I (307) heap_init: At 600FE020 len 00001FE0 (7 KiB): RTCRAM
I (314) spi_flash: detected chip: gd
I (318) spi_flash: flash io: dio
W (322) spi_flash: Detected size(8192k) larger than the size in the binary image header(2048k). Using the size in the binary image header.
I (346) sleep: Configure to isolate all GPIO pins in sleep state
I (348) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.
I (469) pm: Frequency switching config: CPU_MAX: 80, APB_MAX: 80, APB_MIN: 10, Light sleep: ENABLED
I (469) sleep: Enable automatic switching of GPIO sleep configuration
I (479) sleep: Code start at 42000020, total 419.83 KiB, data start at 3c070020, total 79.04 KiB
I (489) pp: pp rom version: e7ae62f
I (489) net80211: net80211 rom version: e7ae62f
I (509) wifi:wifi driver task: 3fce908c, prio:23, stack:6656, core=0
I (509) system_api: Base MAC address is not set
I (509) system_api: read default base MAC address from EFUSE
I (539) wifi:wifi firmware version: 63017e0
I (539) wifi:wifi certification version: v7.0
I (539) wifi:config NVS flash: enabled
I (539) wifi:config nano formating: disabled
I (549) wifi:Init data frame dynamic rx buffer num: 32
I (549) wifi:Init management frame dynamic rx buffer num: 32
I (559) wifi:Init management short buffer num: 32
I (559) wifi:Init dynamic tx buffer num: 32
I (569) wifi:Init static tx FG buffer num: 2
I (569) wifi:Init static rx buffer size: 1600
I (569) wifi:Init static rx buffer num: 10
I (579) wifi:Init dynamic rx buffer num: 32
I (579) wifi_init: rx ba win: 6
I (589) wifi_init: tcpip mbox: 32
I (589) wifi_init: udp mbox: 6
I (589) wifi_init: tcp mbox: 6
I (599) wifi_init: tcp tx win: 5744
I (599) wifi_init: tcp rx win: 5744
I (599) wifi_init: tcp mss: 1440
I (609) wifi_init: WiFi IRAM OP enabled
I (609) wifi_init: WiFi RX IRAM OP enabled
I (619) wifi_init: WiFi SLP IRAM OP enabled
I (629) phy_init: phy_version 501,94697a2,Apr  7 2022,20:49:08
I (909) wifi:mode : sta (60:55:f9:f5:6d:54)
I (909) wifi:enable tsf
I (909) power_save: esp_wifi_set_ps().
I (909) wifi:Set ps type: 1
```

## Other items if possible

- [ ] sdkconfig file (attach the sdkconfig file from your project folder)
- [ ] elf file in the ``build`` folder (**note this may contain all the code details and symbols of your project.**)
- [ ] coredump (This provides stacks of tasks.)

**Comment by igrr** [comment]
@idea--list One thing to check, are you able to connect to the same AP if you comment out the part related to enabling power management in this example?

**Comment by idea--list** [comment]
@igrr 
Oh my bad, turns out to be a newbie issue: after changing the target it turns out the system replaces the whole sdkonfig file with a default one including the example specific part of it. Was not expecting that. After retyping the credentials in the menuconfig, also the ESP32S3 board can connect to the AP and consumption drops to expected levels.

However also this example allows light sleep by default and the ESP32S3 board will not output a part of the log because of #6612 but that is a different story.
