### ISSUE TITLE
Guru Meditation Error: Core  0 panic'ed (StoreProhibited). Exception was unhandled. (IDFGH-7443)

### ISSUE THREAD

**Issue by cyberumut** [espressif/esp-idf#9019]

**Comment by igrr** [comment]
Please check https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/fatal-errors.html#loadprohibited-storeprohibited, it seems that the `self` pointer is NULL, and the code is attempting to write to address 0x00000008 (`EXCVADDR` in the panic handler output.)

**Comment by cyberumut** [comment]
> Please check https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/fatal-errors.html#loadprohibited-storeprohibited, it seems that the `self` pointer is NULL, and the code is attempting to write to address 0x00000008 (`EXCVADDR` in the panic handler output.)

thank u for answer 
this function how to fix ?

**Comment by igrr** [comment]
I think you need to make sure you don't call this function with `self` being a NULL pointer.

**Comment by Dazza0** [comment]
Closing this issue as it seems like the error is caused by a NULL pointer. Please feel free to reopen if necessary.
