### ISSUE TITLE
a2dp_sink: Unable to connect from iOS disabling SSP (IDFGH-7446)

### ISSUE THREAD

**Issue by pad52** [espressif/esp-idf#9022]
## Environment

- Development Kit:      [ESP32-DevKitC]
- Module or chip used:  [ESP32-WROOM-32]
- IDF version (run ``git describe --tags`` to find it): v4.4.1-185-gc5deb7a971
- Build System:         [idf.py]
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it): 8.4.0
- Operating System:     [Linux]
- Using an IDE?: [No]
- Power Supply:         [USB]

## Problem Description

Using a2dp_sink example, disabling CONFIG_BT_SSP in order to obtain Fixed PIN makes the ESP not connectable from iPhone 13

### Steps to reproduce

1. copy esp-idf/examples/bluetooth/bluedroid/classic_bt/a2dp_sink
2. idf.py menuconfig --> Disable Secure Simple Pairing
3. compile & Flash.
4. Try to connect with an iPhone with iOS

**Comment by BetterJincheng** [comment]
@pad52 We have tested iPhone13 and iPhone8p and it just worked fine. Input "1234" and connect -> ok. Please check it again. 
<img width="305" alt="image" src="https://user-images.githubusercontent.com/88189261/170408700-c5a014b5-a8b0-4f6f-8d00-7c9f0aca924b.png">

**Comment by pad52** [comment]
It was clearly a problem of my iPhone, I tested with another one and it works as expected. Thank you very much for your time and sorry for bothering.

**Comment by BetterJincheng** [comment]
@pad52 You are welcome. Turn to us any time.
