### ISSUE TITLE
When will ESP32C2's WiFi and BLE library be supported (IDFGH-7451)

### ISSUE THREAD

**Issue by dreamcmi** [espressif/esp-idf#9026]
When will ESP32C2's WiFi and BLE library be supported?
I'm going to test it with esp8684H4.

**Comment by MaxwellAlan** [comment]
Hi @dreamcmi 
We have already support now!
Thanks.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, feel free to reopen.
