### ISSUE TITLE
How to check wifi connection every 30s, If it is not connected, then it should reconnect automatically  (IDFGH-7452)

### ISSUE THREAD

**Issue by vinothkrstatiq** [espressif/esp-idf#9027]
I have been making an application in such a way that it must check internet connection every 30 seconds and if it not connected then it should reconnect automatically. Kindly help me with the code.

i want to make sure that ESP32 is always connected to the internet when it is available.

**Comment by DheeranYuvaraj** [comment]
@vinothkrstatiq Try the attached code. It should work. 
[Station_reconnect.txt](https://github.com/espressif/esp-idf/files/8777741/Station_reconnect.txt)

**Comment by vinothkrstatiq** [comment]
@DheeranYuvaraj ,

Immense pleasure Thank you so much it is working. 
I appreciate your quick help

**Comment by typetrade** [comment]
but how to check wifi connection anywhere?
