### ISSUE TITLE
i2c semaphore error (IDFGH-7453)

### ISSUE THREAD

**Issue by jrHernandezSio** [espressif/esp-idf#9028]
Hi,

**ENVIRONMENT**:
espressif32@3.3.2 
ESP-IDF 4.3

I am using multitasking with FreeRTOS and sometimes I have the following error:

```
␛[0;31mE (624852) i2c: i2c semaphore error␛[0m
ESP_ERROR_CHECK failed: esp_err_t 0xffffffff (ESP_FAIL) at 0x4008ff3c
file: "lib/I2C/i2c_master.c" line 74
func: i2c_init
expression: i2c_driver_install(i2c_master_port, conf.mode,0, 0, 0)

abort() was called at PC 0x4008ff3f on core 0

Backtrace:0x4009235f:0x3ffbac80 0x40092ab1:0x3ffbaca0 0x40098a36:0x3ffbacc0 0x4008ff3f:0x3ffbad30 0x400d9f69:0x3ffbad50 0x400da001:0x3ffbad90 0x400da11e:0x3ffbadc0 0x400da2ce:0x3ffbadf0 0x400da31c:0x3ffbae10 0x400dc73a:0x3ffbae30 0x400d646f:0x3ffbae50 0x400d7057:0x3ffbae70 0x400d72cd:0x3ffbaea0 0x401c3f9f:0x3ffbafd0 0x40095bb5:0x3ffbaff0


ELF file SHA256: 1ee7208cdbf31733

Rebooting...

Boot!...
```

I have I2C funtions protected with semaphores (see pic below). But message shown is internal to SDK.

![image](https://user-images.githubusercontent.com/92985413/170446495-46921c90-95dd-4e69-88ed-cdde6e387495.png)

I find this trouble mainly when one of the tasks running is using BLE. The rest of them uses I2C actively, but the task running BLE is not supposed to interact with I2C.

All tasks are running in core 0. It did not work otherwise.

Any clue what is going on?

Regards, Ramon.

**Comment by igrr** [comment]
It looks like you might be running out of RAM? Could you please check how much free heap you have before calling i2c_driver_install?

**Comment by jrHernandezSio** [comment]
It might be. I am actually quite in the limit:

![image](https://user-images.githubusercontent.com/92985413/170460888-a25ef415-e6c0-4c18-ae90-c60ec6954d52.png)

I will trace the heap and come back to you.

Thanks.

**Comment by jrHernandezSio** [comment]
Adding heap_info in the i2c part makes the system very slow. 

I have added when tasks (those with no BLE interaction) are created.

![image](https://user-images.githubusercontent.com/92985413/170464895-0d234ebf-03de-4c10-9fb5-b3de856e554c.png)

```
Heap summary for capabilities 0x00000004:
  At 0x3ff80518 len 6872 free 144 allocated 5104 min_free 144
    largest_free_block 0 alloc_blocks 35 free_blocks 0 total_blocks 35    
  At 0x3ffb6388 len 7288 free 88 allocated 5576 min_free 64
    largest_free_block 0 alloc_blocks 21 free_blocks 0 total_blocks 21    
  At 0x3ffb9a20 len 16648 free 292 allocated 14732 min_free 292
    largest_free_block 0 alloc_blocks 72 free_blocks 0 total_blocks 72    
  At 0x3ffcfd48 len 66232 free 1536 allocated 63072 min_free 1404
    largest_free_block 32 alloc_blocks 349 free_blocks 5 total_blocks 354 
  At 0x3ffe0440 len 129984 free 18844 allocated 109516 min_free 18148     
    largest_free_block 16384 alloc_blocks 23 free_blocks 2 total_blocks 25
  Totals:
    free 20904 allocated 198000 min_free 20052 largest_free_block 16384   
Heap summary for capabilities 0x00000004:
  At 0x3ff80518 len 6872 free 144 allocated 5104 min_free 144
    largest_free_block 0 alloc_blocks 35 free_blocks 0 total_blocks 35   
  At 0x3ffb6388 len 7288 free 88 allocated 5576 min_free 64
    largest_free_block 0 alloc_blocks 21 free_blocks 0 total_blocks 21
  At 0x3ffb9a20 len 16648 free 548 allocated 14476 min_free 292
    largest_free_block 256 alloc_blocks 70 free_blocks 1 total_blocks 71
  At 0x3ffcfd48 len 66232 free 1512 allocated 63096 min_free 1404
    largest_free_block 32 alloc_blocks 350 free_blocks 4 total_blocks 354
  At 0x3ffe0440 len 129984 free 15692 allocated 112668 min_free 2704
    largest_free_block 4096 alloc_blocks 36 free_blocks 4 total_blocks 40
  Totals:
    free 17984 allocated 200920 min_free 4608 largest_free_block 4096
assertion "pxRingbuffer" failed: file "C:\Users\jr.hernandez\.platformio\packages\framework-espidf\components\esp_ringbuf\ringbuf.c", line 1306, function: xRingbufferGetMaxItemSize

abort() was called at PC 0x401a1b8b on core 0

Backtrace:0x4009235f:0x3fffbcc0 0x40092ab1:0x3fffbce0 0x40098a36:0x3fffbd00 0x401a1b8b:0x3fffbd70 0x40092155:0x3fffbda0 0x4012cfbe:0x3fffbdc0 0x4012d97a:0x3fffbe00 0x400db344:0x3fffbe30 0x400ddad7:0x3fffbe50 0x400ddbd9:0x3fffbe90 0x400ddc11:0x3fffbeb0 0x400ddc33:0x3fffbee0 0x400dd843:0x3fffbf00 0x400d4f15:0x3fffbf20 0x400d5075:0x3fffbf40 0x40095bb5:0x3fffbf60


ELF file SHA256: 52c2e222c5b26b1b

Rebooting...
```

**Comment by igrr** [comment]
To check if you are running out of heap you can also register an allocation fail callback via [`heap_caps_register_failed_alloc_callback` function](https://docs.espressif.com/projects/esp-idf/en/v4.3.2/esp32/api-reference/system/mem_alloc.html#_CPPv440heap_caps_register_failed_alloc_callback23esp_alloc_failed_hook_t). The callback will be called if any allocation fails. From the callback you can print some debug information.

Given that you only have 17984 bytes before starting the task, if the task also allocates some memory it is pretty likely that you run out of memory somewhere in the process.

**Comment by jrHernandezSio** [comment]
Yes, there is big difference when BLE is not running, see free heap values: 70512 / 202484.

BTW, BLE is set to allocate dynamically.

**Comment by jrHernandezSio** [comment]
Ok, I need to optimize my RAM.
