### ISSUE TITLE
How to add drivers and functions provided by other components in the bootloader code (IDFGH-7464)

### ISSUE THREAD

**Issue by unit-c** [espressif/esp-idf#9038]
I operated it once according to the ESP-IDF programming guide, just like adding ordinary components, add it in the bootloader_components directory But it prompts that the function or header file cannot be found.

![image](https://user-images.githubusercontent.com/60456075/170646264-738df79d-3bba-43fb-bfda-c5ae4e8f59fc.png)

Suppose the esp-idf\examples\custom_bootloader\bootloader_hooks project is taken as an example Can you demonstrate how to add drivers and functions provided by other components? 

thank

**Comment by ESP-Marius** [comment]
Sorry for the late reply @unit-c , seems like we missed this issue.

> Can you demonstrate how to add drivers and functions provided by other components?

Most drivers wont be usable in the bootloader as they depend on  FreeRTOS or other system features. 

Linking are done the same way as in other IDF projects, e.g for the `bootloader_hooks` example you would add  `REQURIES component` to `examples/custom_bootloader/bootloader_hooks/bootloader_components/my_boot_hooks/CMakeLists.txt`

Was there anything specific you were thinking of?
