### ISSUE TITLE
如何将s2的i2s代码改成s3的 (IDFGH-7473)

### ISSUE THREAD

**Issue by JustQY** [espressif/esp-idf#9043]
有如下几个函数需要修改，红色表示在s3里，对应结构体里的成员已经不是那个了，并且还增加了一些，完全不知道怎么改了
![snap_screen_20220528092914](https://user-images.githubusercontent.com/9473678/170804485-e2add287-ab3a-47f0-b832-fe675d7d7299.png)

![snap_screen_20220528092844](https://user-images.githubusercontent.com/9473678/170804473-435e213b-e610-4002-9779-f0b8e8899c27.png)

**Comment by suda-morris** [comment]
@JustQY  Start from ESP32-S3, the I2S peripheral won't support a "LCD Mode". The LCD controller has been split into a stand-alone peripheral -- LCD_CAM. You can refer to the LCD driver from [here](https://github.com/espressif/esp-idf/blob/master/components/esp_lcd/src/esp_lcd_panel_io_i80.c) if you want to drive a i80 interface LCD. The LCD_CAM chapter is release as well in the [TRM](https://www.espressif.com/sites/default/files/documentation/esp32-s3_technical_reference_manual_en.pdf#lcd_cam)
