### ISSUE TITLE
[TW#14794] When an additional task calls void esp_task_wdt_feed() only once it never triggers

### ISSUE THREAD

**Issue by TomIowaSoft** [espressif/esp-idf#906]
When there is only one task in wdt_task_list, and that task only called esp_task_wdt_feed() once, the watchdog triggers but no task name is displayed.

When there is more than one task in wdt_task_list, and an additional task calls  esp_task_wdt_feed() once, no watchdog is triggered.

The reason turned out to be that when a task is added to the list in void esp_task_wdt_feed(), it initializes  newtask->fed_watchdog=true; This is not correct, it should be false. The reason is because it did not participate in the decision to feed.

**Comment by Dazza0** [comment]
@TomIowaSoft task watchdog timer has been overhauled, please refer to commit 9d63e1da4a233f8b3043157f58894fb9b2c2668d
