### ISSUE TITLE
Connect MQTT with client certificate without URL x509 certificate (IDFGH-7498)

### ISSUE THREAD

**Issue by Eran125** [espressif/esp-idf#9066]
Develop kit: ESP32-CAM
IDE: VScode IDF v4.4
OS: windows 

## Problem Description

Hi,
I like to reduce the time establish connection to Azure.
I have the URL x509 certificate, client certificate and key.
I configure the structure "esp_mqtt_client_config_t" for setup the connection.
Can I ignore the URL certificate and use only the client certificate? if yes, how I do it?

Azure have also a shared key instead of the certification, how I can use it?

Can you please explain to me what is the key use for?

**Comment by euripedesrocha** [comment]
Hi @Eran125,
The certificate from the broker is necessary for security verification of the broker you are connecting to. If you don't configure it, your application can't verify the connection and your system will be vulnerable. 

Regarding client credentials, you can use the password field with the shared key, if I remember correctly, please refer to AWS security documentation. 

The client key is to be used together with client certificate for mutual authentication using TLS.
