### ISSUE TITLE
Enable/Disable BLE memory leak (IDFGH-7510)

### ISSUE THREAD

**Issue by Alextrimux** [espressif/esp-idf#9077]
## Environment

- Development Kit: custom PCB
- Module or chip used:  ESP32-WROOM-32UE
- IDF version: v4.4.1
- Build System: CMake 3.20.3
- Compiler version: 8.4.0
- Operating System: Windows
- (Windows only) environment type: ESP Command Prompt
- Using an IDE?: Yes - ESP-IDF Eclipse
- Power Supply: external 3.3V

## Problem Description

Potential memory leak detected when enabling/disabling BLE. The leak was detected by using esp_get_free_heap_size. According to the logs, the leak is 16 bytes.

### Expected Behavior

The same amount of free space before and after BLE.

### Actual Behavior

The number of free space increases by 16 bytes for every reinitialization of BLE.

### Steps to reproduce

1. esp_get_free_heap_size()
2. esp_bt_controller_enable()
3. esp_bluedroid_init()
4. esp_bluedroid_enable()
5. esp_ble_gatts_register_callback()
6. esp_ble_gap_register_callback()
7. esp_ble_gatts_app_register()
8. esp_get_free_heap_size()
9. esp_bluedroid_disable()
10. esp_bluedroid_deinit()
11. esp_bt_controller_disable()
12. esp_get_free_heap_size()

### Code to reproduce this issue

[GIST](https://gist.github.com/Alextrimux/b809509b75a9a6885e48926db504a6f3)

## Debug Logs

```
I (9763) TEST: --------------START------------------
I (9773) TEST: free_heap_size 218248
I (9773) BTDM_INIT: BT controller compile version [5688ed5]
I (10083) GATTS_DEMO: REGISTER_APP_EVT, status 0, app_id 0
I (10093) TEST: after start_ble_func 194212
I (10103) GATTS_DEMO: CREATE_SERVICE_EVT, status 0,  service_handle 40
I (10103) GATTS_DEMO: REGISTER_APP_EVT, status 0, app_id 1
I (10123) GATTS_DEMO: SERVICE_START_EVT, status 0, service_handle 40
I (10123) GATTS_DEMO: ADD_CHAR_EVT, status 0,  attr_handle 42, service_handle 40
I (10123) GATTS_DEMO: the gatts demo char length = 3
I (10133) GATTS_DEMO: prf_char[0] =11
I (10133) GATTS_DEMO: prf_char[1] =22
I (10133) GATTS_DEMO: prf_char[2] =33
I (10143) GATTS_DEMO: CREATE_SERVICE_EVT, status 0,  service_handle 44
I (10153) GATTS_DEMO: ADD_DESCR_EVT, status 0, attr_handle 43, service_handle 40
I (10153) GATTS_DEMO: SERVICE_START_EVT, status 0, service_handle 44
I (10163) GATTS_DEMO: ADD_CHAR_EVT, status 0,  attr_handle 46, service_handle 44
I (10173) GATTS_DEMO: ADD_DESCR_EVT, status 0, attr_handle 47, service_handle 44
W (11103) BT_APPL: bta_dm_disable BTA_DISABLE_DELAY set to 200 ms
I (11313) TEST: after stop_ble_func 218232
I (11313) TEST: --------------END----------------
I (11313) TEST: --------------START------------------
I (11313) TEST: free_heap_size 218232
I (11323) BTDM_INIT: BT controller compile version [5688ed5]
I (11633) GATTS_DEMO: REGISTER_APP_EVT, status 0, app_id 0
I (11643) TEST: after start_ble_func 194180
I (11643) GATTS_DEMO: CREATE_SERVICE_EVT, status 0,  service_handle 40
I (11643) GATTS_DEMO: REGISTER_APP_EVT, status 0, app_id 1
I (11663) GATTS_DEMO: SERVICE_START_EVT, status 0, service_handle 40
I (11663) GATTS_DEMO: ADD_CHAR_EVT, status 0,  attr_handle 42, service_handle 40
I (11673) GATTS_DEMO: the gatts demo char length = 3
I (11673) GATTS_DEMO: prf_char[0] =11
I (11683) GATTS_DEMO: prf_char[1] =22
I (11683) GATTS_DEMO: prf_char[2] =33
I (11693) GATTS_DEMO: CREATE_SERVICE_EVT, status 0,  service_handle 44
I (11693) GATTS_DEMO: ADD_DESCR_EVT, status 0, attr_handle 43, service_handle 40
I (11703) GATTS_DEMO: SERVICE_START_EVT, status 0, service_handle 44
I (11713) GATTS_DEMO: ADD_CHAR_EVT, status 0,  attr_handle 46, service_handle 44
I (11723) GATTS_DEMO: ADD_DESCR_EVT, status 0, attr_handle 47, service_handle 44
W (12643) BT_APPL: bta_dm_disable BTA_DISABLE_DELAY set to 200 ms
I (12853) TEST: after stop_ble_func 218216
I (12853) TEST: --------------END----------------
```

## Other items if possible

The default sdkconfig file from the gatts_demo example was used.

**Comment by CaptivatingCat** [comment]
@xiewenxiang can you take a look into my findings?

**Comment by esp-cjh** [comment]
@CaptivatingCat Thanks for your report. This issue has been fixed and the merge request was merged. The commit is 32290b247596a8505ae4db35d1ca3b5926f6921e. Please check whether this issue can be closed.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, sorry for slow turnaround, feel free to reopen.
