### ISSUE TITLE
mbedtls_ssl_handshake returned -0x7F00 (IDFGH-7511)

### ISSUE THREAD

**Issue by wilsonnggp** [espressif/esp-idf#9078]
## Environment

- Development Kit: ESP32-Wrover-Kit
- Kit version WroverKit v3
- Module or chip used:  ESP32-WROVER-B
- IDF version 4.0
- Build System:        CMake|idf.py
- Operating System:   macOS]
- Using an IDE: VS
- Power Supply:  external 5V

## Problem Description

Trying to run an OTA program with other tasks in the background. I have a simple OTA program that works but upon integration of other tasks in my main project code it produces the following error "esp-tls-mbedtls: mbedtls_ssl_setup returned -0x7F00" and follows up with not creating a successful SSL handle. In a simple OTA program it would continue to download packets "W (93276) wifi:<ba-add>idx:0 (ifx:0, 0c:0e:76:78:39:f6), tid:6, ssn:2, winSize:64" < - one example and begin to load it onto the OTA partition till finished. Looks like it got two packages before loading this error.

//Detailed problem description goes here.

### Expected Behavior
Should trigger OTA and update accordingly, It receives two packets but then fails to create an SSL handle . Get a reply on the given link. 
"
W (93276) wifi:<ba-add>idx:0 (ifx:0, 0c:0e:76:78:39:f6), tid:6, ssn:2, winSize:64
W (93316) wifi:<ba-add>idx:1 (ifx:0, 0c:0e:76:78:39:f6), tid:0, ssn:0, winSize:64
"

"I (14331) esp_https_ota: Starting OTA...
I (14331) esp_https_ota: Writing to partition subtype 16 at offset 0x410000"
I (47811) esp_https_ota: data read .... x however many packets the bin is" 

Then trigger the BOOT partition 
"
esp_https_ota: OTA FINISH CALL
esp_https_ota: Finish -> Success 3
I (78351) esp_image: segment 0: paddr=00410020 vaddr=3f400020 size=bb928h (768296) map
I (78631) esp_image: segment 1: paddr=004cb950 vaddr=3ffbdb60 size=046c8h ( 18120) 
I (78631) esp_image: segment 2: paddr=004d0020 vaddr=400d0020 size=ec128h (966952) map
I (78961) esp_image: segment 3: paddr=005bc150 vaddr=3ffc2228 size=014e0h (  5344) 
I (78971) esp_image: segment 4: paddr=005bd638 vaddr=40080000 size=1f650h (128592) 
I (79011) esp_image: segment 5: paddr=005dcc90 vaddr=50000000 size=00010h (    16) 
esp_ota_ops: In Cleanup
esp_https_ota: Finish -> ota_end 0
esp_https_ota: OTA Begin
I (79041) esp_image: segment 0: paddr=00410020 vaddr=3f400020 size=bb928h (768296) map
I (79301) esp_image: segment 1: paddr=004cb950 vaddr=3ffbdb60 size=046c8h ( 18120) 
I (79311) esp_image: segment 2: paddr=004d0020 vaddr=400d0020 size=ec128h (966952) map
I (79641) esp_image: segment 3: paddr=005bc150 vaddr=3ffc2228 size=014e0h (  5344) 
I (79641) esp_image: segment 4: paddr=005bd638 vaddr=40080000 size=1f650h (128592) 
I (79691) esp_image: segment 5: paddr=005dcc90 vaddr=50000000 size=00010h (    16)
"

^ This was tested on the same code just before my other tasks were initialized. I know that theres most likely something blocking wifi from " mbedtls_ssl_setup returned -0x7F00" but not sure exactly what this error means. I have a 16MB flash WROVER and havent ran into any memory issues. I'm using an embedded TXTfile CERT as well as a const char* CERT to validate its not memory corruption or CERT parsing for the OTA. Any guidance as to what error is causing this would help hugely! 

I've seen an ESP-IDF forum regarding this issue "https://www.esp32.com/viewtopic.php?t=12231" but I'm using ESP-IDF 4.4 and MAC. My SSL is mbedTLS and I'm not using WolfSSL as an SSL library.

### Actual Behavior
Receives two packets but then fails to create an SSL handle 
"
W (93276) wifi:<ba-add>idx:0 (ifx:0, 0c:0e:76:78:39:f6), tid:6, ssn:2, winSize:64
W (93316) wifi:<ba-add>idx:1 (ifx:0, 0c:0e:76:78:39:f6), tid:0, ssn:0, winSize:64
"
into 
"
esp-tls-mbedtls: mbedtls_ssl_setup returned -0x7F00
E (202136) esp-tls: create_ssl_handle failed
E (202136) esp-tls: Failed to open new connection
E (202146) TRANSPORT_BASE: Failed to open a new connection
E (202146) HTTP_CLIENT: Connection failed, sock < 0
E (202156) esp_https_ota: Failed to open HTTP connection: ESP_ERR_HTTP_CONNECT
E (202156) esp_https_ota: Failed to establish HTTP connection
E (202166) esp_https_ota: Handle is NULL
E (202176) FreeRTOS: FreeRTOS Task "run_ota" should not return, Aborting now!
"

### Steps to reproduce

1.
 calling a function as follows, this task is "xTaskCreate(OTA, "run_ota", 1024 * 8, &otadone, 0, NULL);"
"    esp_http_client_config_t clientConfig = {
      .url = "---a public github RAW link", // our ota location
      .event_handler = client_event_handler,
      .cert_pem = cacertpem
      //.cert_pem = (char *)server_cert_pem_start
    };

    if(esp_https_ota(&clientConfig) == ESP_OK)
    {
      ESP_LOGI(TAG1,"OTA flash succsessfull .");
      printf("restarting in 5 seconds\n");
      vTaskDelay(pdMS_TO_TICKS(5000));
      esp_restart();
    }
"

// If possible, attach a picture of your setup/wiring here.

A typical ESP PROG - ESP Wrover connection with 5V internal supplied via PSU

xTaskCreate(OTA, "run_ota", 1024 * 8, &otadone, 0, NULL);"

esp_http_client_config_t clientConfig = {
      .url = "---a public github link", // our ota location
      .event_handler = client_event_handler,
      .cert_pem = cacertpem
      //.cert_pem = (char *)server_cert_pem_start
    };

    if(esp_https_ota(&clientConfig) == ESP_OK)
    {
      ESP_LOGI(TAG1,"OTA flash succsessfull .");
      printf("restarting in 5 seconds\n");
      vTaskDelay(pdMS_TO_TICKS(5000));
      esp_restart();
    }

## Debug Logs

```
Final Values, x: -1   y: -1   z: 1023
I (87166) gpio: GPIO[19]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 
I (87166) gpio: GPIO[33]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 
RawX b4 invert: -1 adcX2 -1
TouchGetRawY before invert: -1
OTA TRIGGERED,suspended GUItimer stoppedwifi reset is falseI (87216) wifi:wifi driver task: 3ffe3d70, prio:23, stack:6656, core=1
I (87216) wifi:wifi firmware version: 7679c42
I (87216) wifi:wifi certification version: v7.0
I (87226) wifi:config NVS flash: enabled
I (87226) wifi:config nano formating: disabled
I (87236) gpio: GPIO[5]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 
I (87236) wifi:Init data frame dynamic rx buffer num: 32
I (87246) gpio: GPIO[32]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 
I (87246) wifi:Init management frame dynamic rx buffer num: 32
I (87266) wifi:Init management short buffer num: 32
I (87266) wifi:Init dynamic tx buffer num: 32
I (87276) wifi:Init static rx buffer size: 1600
I (87276) wifi:Init static rx buffer num: 10
I (87276) wifi:Init dynamic rx buffer num: 32
I (87286) wifi_init: rx ba win: 6
I (87286) wifi_init: tcpip mbox: 32
I (87296) wifi_init: udp mbox: 6
I (87296) wifi_init: tcp mbox: 6
I (87306) wifi_init: tcp tx win: 5744
I (87306) wifi_init: tcp rx win: 5744
I (87306) wifi_init: tcp mss: 1440
I (87316) wifi_init: WiFi IRAM OP enabled
I (87326) wifi_init: WiFi RX IRAM OP enabled
I (87326) example_connect: Connecting to SSID123..password..
I (87346) wifi:mode : sta (34:94:54:4f:e8:c8)
I (87346) wifi:enable tsf
I (87366) example_connect: Waiting for IP(s)
I (90506) wifi:new:<10,0>, old:<1,0>, ap:<255,255>, sta:<10,0>, prof:1
I (91276) wifi:state: init -> auth (b0)
I (91296) wifi:state: auth -> assoc (0)
I (91306) wifi:state: assoc -> run (10)
I (91346) wifi:connected with SSID123, aid = 2, channel 10, BW20, bssid = 0c:0e:76:78:39:f6
I (91346) wifi:security: WPA2-PSK, phy: bgn, rssi: -31
I (91346) wifi:pm start, type: 1

I (91436) wifi:AP's beacon interval = 102400 us, DTIM period = 2
I (92186) esp_netif_handlers: example_connect: sta ip: 10.200.25.71, mask: 255.255.255.0, gw: 10.200.25.254
I (92186) example_connect: Got IPv4 event: Interface "example_connect: sta" address: 10.200.25.71
I (93186) example_connect: Got IPv6 event: Interface "example_connect: sta" address: fe80:0000:0000:0000:3694:54ff:fe4f:e8c8, type: ESP_IP6_ADDR_IS_LINK_LOCAL
I (93196) example_connect: Connected to example_connect: sta
I (93196) example_connect: - IPv4 address: 10.200.25.71
I (93196) example_connect: - IPv6 address: fe80:0000:0000:0000:3694:54ff:fe4f:e8c8, type: ESP_IP6_ADDR_IS_LINK_LOCAL
W (93276) wifi:<ba-add>idx:0 (ifx:0, 0c:0e:76:78:39:f6), tid:6, ssn:2, winSize:64
W (93316) wifi:<ba-add>idx:1 (ifx:0, 0c:0e:76:78:39:f6), tid:0, ssn:0, winSize:64
E (94736) esp-tls-mbedtls: mbedtls_ssl_setup returned -0x7F00
E (94736) esp-tls: create_ssl_handle failed
E (94736) esp-tls: Failed to open new connection
E (94746) TRANSPORT_BASE: Failed to open a new connection
E (94756) HTTP_CLIENT: Connection failed, sock < 0
E (94756) esp_https_ota: Failed to open HTTP connection: ESP_ERR_HTTP_CONNECT
E (94766) esp_https_ota: Failed to establish HTTP connection
E (94766) esp_https_ota: Handle is NULL
```

**Comment by wilsonnggp** [comment]
Issue fixed, enabled SPIRAM and did a bunch of memory management. Works as intended!

**Comment by xuanchibkd14** [comment]
hi, can i fix without spiram?

**Comment by Nhanhandsome** [comment]
> Issue fixed, enabled SPIRAM and did a bunch of memory management. Works as intended!

could you please show more details steps to fix this. I also face the same problem

**Comment by mahavirj** [comment]
We have some memory optimization related guides, please refer them at [1](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/performance/ram-usage.html#minimizing-ram-usage) and [2](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/protocols/mbedtls.html#reducing-ram-usage-mbedtls). Please check them out, they should help in this scenario.
