### ISSUE TITLE
Compile errors from freertos/timers.h in ESP-IDF 4.4.1 (IDFGH-7515)

### ISSUE THREAD

**Issue by mbratch** [espressif/esp-idf#9082]
## Environment

- Development Kit:   ESP32-PICO-Kit
- Module or chip used:  ESP32-PICO-D4
- IDF version (run ``git describe --tags`` to find it): 4.4.1
    // v3.2-dev-1148-g96cd3b75c
- Build System:     CMake or idf.py
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it): 8.4.0
- Operating System:     Windows 11
- (Windows only) environment type: PowerShell
- Using an IDE?: Yes - VS Code with ESP-IDF plugin
- Power Supply:         USB

## Problem Description

I am unable to compile a source file that includes `freertos/timers.h` unless, before that header, I also include `driver/i2c.h`

### Expected Behavior

`freertos/timers.h` should not depend upon `driver/i2c.h` to successfully compile

### Actual Behavior

I get the following compile errors attempting to compile with `freertos/timers.h` without first including `driver/i2c.h`:

`
> Executing task: ninja  <

[2/10] Performing build step for 'bootloader'
[1/1] cmd.exe /C "cd /D C:\Users\mdbra\Documents\Projects\ESP32\BD-OTB\build\bootloader\esp-idf\esptool_py && C:\Users\mdbra\.espressif\python_env\idf4.4_py3.8_env\Scripts\python.exe C:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/partition_table/check_sizes.py --offset 0x8000 bootloader 0x1000 C:/Users/mdbra/Documents/Projects/ESP32/BD-OTB/build/bootloader/bootloader.bin"
Bootloader binary size 0x62c0 bytes. 0xd40 bytes (12%) free.
[3/8] Building CXX object esp-idf/main/CMakeFiles/__idf_main.dir/OutIns.cpp.obj
FAILED: esp-idf/main/CMakeFiles/__idf_main.dir/OutIns.cpp.obj
C:\Users\mdbra\.espressif\tools\xtensa-esp32-elf\esp-2021r2-patch3-8.4.0\xtensa-esp32-elf\bin\xtensa-esp32-elf-g++.exe -DHAVE_CONFIG_H -DMBEDTLS_CONFIG_FILE=\"mbedtls/esp_config.h\" -DUNITY_INCLUDE_CONFIG_H -DWITH_POSIX -I../include -Iconfig -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/newlib/platform_include -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/freertos/include -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/freertos/include/esp_additions/freertos -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/freertos/port/xtensa/include -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/freertos/include/esp_additions -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/esp_hw_support/include -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/esp_hw_support/include/soc -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/esp_hw_support/include/soc/esp32 -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/esp_hw_support/port/esp32/. -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/esp_hw_support/port/esp32/private_include -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/heap/include -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/log/include -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/lwip/include/apps -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/lwip/include/apps/sntp -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/lwip/lwip/src/include -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/lwip/port/esp32/include -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/lwip/port/esp32/include/arch -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/soc/include -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/soc/esp32/. -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/soc/esp32/include -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/hal/esp32/include -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/hal/include -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/hal/platform_port/include -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/esp_rom/include -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/esp_rom/include/esp32 -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/esp_rom/esp32 -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/esp_common/include -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/esp_system/include -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/esp_system/port/soc -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/esp_system/port/public_compat -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/esp32/include -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/xtensa/include -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/xtensa/esp32/include -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/driver/include -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/driver/esp32/include -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/esp_pm/include -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/esp_ringbuf/include -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/efuse/include -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/efuse/esp32/include -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/vfs/include -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/esp_wifi/include -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/esp_event/include -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/esp_netif/include -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/esp_eth/include -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/tcpip_adapter/include -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/esp_phy/include -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/esp_phy/esp32/include -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/esp_ipc/include -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/app_trace/include -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/esp_timer/include -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/mbedtls/port/include -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/mbedtls/mbedtls/include -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/mbedtls/esp_crt_bundle/include -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/app_update/include -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/spi_flash/include -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/bootloader_support/include -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/nvs_flash/include -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/pthread/include -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/esp_gdbstub/include -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/esp_gdbstub/xtensa -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/esp_gdbstub/esp32 -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/espcoredump/include -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/espcoredump/include/port/xtensa -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/wpa_supplicant/include -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/wpa_supplicant/port/include -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/wpa_supplicant/esp_supplicant/include -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/ieee802154/include -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/console -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/asio/asio/asio/include -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/asio/port/include -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/cbor/port/include -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/unity/include -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/unity/unity/src -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/cmock/CMock/src -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/coap/port/include -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/coap/libcoap/include -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/nghttp/port/include -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/nghttp/nghttp2/lib/includes -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/esp-tls -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/esp-tls/esp-tls-crypto -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/esp_adc_cal/include -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/esp_hid/include -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/tcp_transport/include -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/esp_http_client/include -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/esp_http_server/include -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/esp_https_ota/include -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/esp_lcd/include -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/esp_lcd/interface -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/protobuf-c/protobuf-c -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/protocomm/include/common -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/protocomm/include/security -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/protocomm/include/transports -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/mdns/include -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/esp_local_ctrl/include -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/sdmmc/include -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/esp_serial_slave_link/include -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/esp_websocket_client/include -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/expat/expat/expat/lib -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/expat/port/include -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/wear_levelling/include -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/fatfs/diskio -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/fatfs/vfs -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/fatfs/src -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/freemodbus/common/include -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/idf_test/include -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/idf_test/include/esp32 -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/jsmn/include -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/json/cJSON -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/libsodium/libsodium/src/libsodium/include -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/libsodium/port_include -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/mqtt/esp-mqtt/include -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/openssl/include -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/perfmon/include -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/spiffs/include -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/ulp/include -IC:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/wifi_provisioning/include -mlongcalls -Wno-frame-address -ffunction-sections -fdata-sections -Wall -Werror=all -Wno-error=unused-function -Wno-error=unused-variable -Wno-error=deprecated-declarations -Wextra -Wno-unused-parameter -Wno-sign-compare -ggdb -Og -fmacro-prefix-map=C:/Users/mdbra/Documents/Projects/ESP32/BD-OTB=. -fmacro-prefix-map=C:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1=IDF -fstrict-volatile-bitfields -Wno-error=unused-but-set-variable -fno-jump-tables -fno-tree-switch-conversion -std=gnu++11 -fno-exceptions -fno-rtti -D_GNU_SOURCE -DIDF_VER=\"v4.4.1-dirty\" -DESP_PLATFORM -D_POSIX_READER_WRITER_LOCKS -std=gnu++17 -MD -MT esp-idf/main/CMakeFiles/__idf_main.dir/OutIns.cpp.obj -MF esp-idf\main\CMakeFiles\__idf_main.dir\OutIns.cpp.obj.d -o esp-idf/main/CMakeFiles/__idf_main.dir/OutIns.cpp.obj -c ../main/OutIns.cpp
In file included from ../main/OutIns.cpp:1:
C:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/freertos/include/freertos/timers.h:32:6: error: #error "include FreeRTOS.h must appear in source files before include timers.h"
     #error "include FreeRTOS.h must appear in source files before include timers.h"
      ^~~~~
In file included from C:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/freertos/include/freertos/timers.h:37,
                 from ../main/OutIns.cpp:1:
C:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/freertos/include/freertos/task.h:32:6: error: #error "include FreeRTOS.h must appear in source files before include task.h"
     #error "include FreeRTOS.h must appear in source files before include task.h"
      ^~~~~
In file included from C:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/freertos/include/freertos/task.h:35,
                 from C:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/freertos/include/freertos/timers.h:37,
                 from ../main/OutIns.cpp:1:
C:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/freertos/include/freertos/list.h:56:6: error: #error "FreeRTOS.h must be included before list.h"
     #error "FreeRTOS.h must be included before list.h"
      ^~~~~
In file included from C:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/freertos/include/freertos/FreeRTOS.h:57,
                 from C:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/freertos/include/esp_additions/freertos/task_snapshot.h:17,
                 from C:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/freertos/include/freertos/task.h:3503,
                 from C:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/freertos/include/freertos/timers.h:37,
                 from ../main/OutIns.cpp:1:
C:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/freertos/include/esp_additions/freertos/FreeRTOSConfig.h:93: warning: "portUSING_MPU_WRAPPERS" redefined
 #define portUSING_MPU_WRAPPERS                          0

In file included from C:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/freertos/include/freertos/task.h:37,
                 from C:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/freertos/include/freertos/timers.h:37,
                 from ../main/OutIns.cpp:1:
C:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/freertos/port/xtensa/include/freertos/portmacro.h:677: note: this is the location of the previous definition
 #define portUSING_MPU_WRAPPERS 1   // Enable it to allocate coproc area

In file included from C:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/freertos/include/freertos/task.h:35,
                 from C:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/freertos/include/freertos/timers.h:37,
                 from ../main/OutIns.cpp:1:
C:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/freertos/include/freertos/list.h:144:25: error: 'TickType_t' does not name a type; did you mean 'portTickType'?
     configLIST_VOLATILE TickType_t xItemValue;              /*< The value being listed.  In most cases this is used to sort the list in descending order. */
                         ^~~~~~~~~~
                         portTickType
C:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/freertos/include/freertos/list.h:156:25: error: 'TickType_t' does not name a type; did you mean 'portTickType'?
     configLIST_VOLATILE TickType_t xItemValue;
                         ^~~~~~~~~~
                         portTickType
C:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/freertos/include/freertos/list.h:168:14: error: 'UBaseType_t' does not name a type
     volatile UBaseType_t uxNumberOfItems;
              ^~~~~~~~~~~
C:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/freertos/include/freertos/list.h:346:47: error: expected initializer before 'PRIVILEGED_FUNCTION'
 void vListInitialise( List_t * const pxList ) PRIVILEGED_FUNCTION;
                                               ^~~~~~~~~~~~~~~~~~~
C:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/freertos/include/freertos/list.h:357:55: error: expected initializer before 'PRIVILEGED_FUNCTION'
 void vListInitialiseItem( ListItem_t * const pxItem ) PRIVILEGED_FUNCTION;
                                                       ^~~~~~~~~~~~~~~~~~~
C:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/freertos/include/freertos/list.h:371:54: error: expected initializer before 'PRIVILEGED_FUNCTION'
                   ListItem_t * const pxNewListItem ) PRIVILEGED_FUNCTION;
                                                      ^~~~~~~~~~~~~~~~~~~
C:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/freertos/include/freertos/list.h:393:57: error: expected initializer before 'PRIVILEGED_FUNCTION'
                      ListItem_t * const pxNewListItem ) PRIVILEGED_FUNCTION;
                                                         ^~~~~~~~~~~~~~~~~~~
C:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/freertos/include/freertos/list.h:408:1: error: 'UBaseType_t' does not name a type
 UBaseType_t uxListRemove( ListItem_t * const pxItemToRemove ) PRIVILEGED_FUNCTION;
 ^~~~~~~~~~~
In file included from C:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/freertos/include/freertos/timers.h:37,
                 from ../main/OutIns.cpp:1:
C:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/freertos/include/freertos/task.h:142:5: error: 'TaskFunction_t' does not name a type; did you mean 'TaskHookFunction_t'?
     TaskFunction_t pvTaskCode;
     ^~~~~~~~~~~~~~
     TaskHookFunction_t
C:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/freertos/include/freertos/task.h:144:5: error: 'configSTACK_DEPTH_TYPE' does not name a type
     configSTACK_DEPTH_TYPE usStackDepth;
     ^~~~~~~~~~~~~~~~~~~~~~
C:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/freertos/include/freertos/task.h:144:5: note: the macro 'configSTACK_DEPTH_TYPE' had not yet been defined
In file included from C:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/freertos/include/esp_additions/freertos/task_snapshot.h:17,
                 from C:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/freertos/include/freertos/task.h:3503,
                 from C:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/freertos/include/freertos/timers.h:37,
                 from ../main/OutIns.cpp:1:
C:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/freertos/include/freertos/FreeRTOS.h:938: note: it was later defined here
     #define configSTACK_DEPTH_TYPE    uint16_t

In file included from C:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/freertos/include/freertos/timers.h:37,
                 from ../main/OutIns.cpp:1:
C:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/freertos/include/freertos/task.h:148:30: error: 'portNUM_CONFIGURABLE_REGIONS' was not declared in this scope
     MemoryRegion_t xRegions[ portNUM_CONFIGURABLE_REGIONS ];
                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/freertos/include/freertos/task.h:148:30: note: the macro 'portNUM_CONFIGURABLE_REGIONS' had not yet been defined
In file included from C:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/freertos/include/freertos/FreeRTOS.h:63,
                 from C:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/freertos/include/esp_additions/freertos/task_snapshot.h:17,
                 from C:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/freertos/include/freertos/task.h:3503,
                 from C:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/freertos/include/freertos/timers.h:37,
                 from ../main/OutIns.cpp:1:
C:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/freertos/include/freertos/portable.h:83: note: it was later defined here 
     #define portNUM_CONFIGURABLE_REGIONS    1

In file included from C:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/freertos/include/freertos/timers.h:37,
                 from ../main/OutIns.cpp:1:
C:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/freertos/include/freertos/task.h:166:5: error: 'configSTACK_DEPTH_TYPE' does not name a type
     configSTACK_DEPTH_TYPE usStackHighWaterMark;     /* The minimum amount of stack space that has remained for the task since the task was created.  The closer this value is to zero the closer the task has come to overflowing its stack. */
     ^~~~~~~~~~~~~~~~~~~~~~
C:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/freertos/include/freertos/task.h:166:5: note: the macro 'configSTACK_DEPTH_TYPE' had not yet been defined
In file included from C:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/freertos/include/esp_additions/freertos/task_snapshot.h:17,
                 from C:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/freertos/include/freertos/task.h:3503,
                 from C:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/freertos/include/freertos/timers.h:37,
                 from ../main/OutIns.cpp:1:
C:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/freertos/include/freertos/FreeRTOS.h:938: note: it was later defined here
     #define configSTACK_DEPTH_TYPE    uint16_t

In file included from C:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/freertos/include/freertos/timers.h:37,
                 from ../main/OutIns.cpp:1:
C:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/freertos/include/freertos/task.h:1804:1: error: 'configSTACK_DEPTH_TYPE' does not name a type
 configSTACK_DEPTH_TYPE uxTaskGetStackHighWaterMark2( TaskHandle_t xTask ) PRIVILEGED_FUNCTION;
 ^~~~~~~~~~~~~~~~~~~~~~
C:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/freertos/include/freertos/task.h:1804:1: note: the macro 'configSTACK_DEPTH_TYPE' had not yet been defined
In file included from C:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/freertos/include/esp_additions/freertos/task_snapshot.h:17,
                 from C:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/freertos/include/freertos/task.h:3503,
                 from C:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/freertos/include/freertos/timers.h:37,
                 from ../main/OutIns.cpp:1:
C:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/freertos/include/freertos/FreeRTOS.h:938: note: it was later defined here
     #define configSTACK_DEPTH_TYPE    uint16_t

In file included from C:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/freertos/include/freertos/timers.h:37,
                 from ../main/OutIns.cpp:1:
C:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/freertos/include/freertos/task.h:3403:1: error: 'portDONT_DISCARD' does not name a type
 portDONT_DISCARD void vTaskSwitchContext( void ) PRIVILEGED_FUNCTION;
 ^~~~~~~~~~~~~~~~
C:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/freertos/include/freertos/task.h:3403:1: note: the macro 'portDONT_DISCARD' had not yet been defined
In file included from C:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/freertos/include/esp_additions/freertos/task_snapshot.h:17,
                 from C:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/freertos/include/freertos/task.h:3503,
                 from C:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/freertos/include/freertos/timers.h:37,
                 from ../main/OutIns.cpp:1:
C:/Users/mdbra/.espressif/frameworks/esp-idf-v4.4.1/components/freertos/include/freertos/FreeRTOS.h:856: note: it was later defined here
     #define portDONT_DISCARD

ninja: build stopped: subcommand failed.
The terminal process "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -Command ninja " terminated with exit code: 1.
`
### Steps to reproduce

1.  Compile file
2.  Observe errors

### Code to reproduce this issue

```cpp
#include <freertos/timers.h>    // The source file with just this in it will result in the error
```

### Work-around

My current work around is just to include `driver/i2c.h` even though I am not needing it. If I use another include, such as `driver/adc.h`, which I do need, I still get the errors:

```cpp
#include <driver/i2c.h>        // Must include this before the following include to avoid the compile errors
#include <freertos/timers.h>    // The source file with just this in it will result in the error
```

**Comment by KaeLL** [comment]
> "include FreeRTOS.h must appear in source files before include timers.h"

**Comment by mbratch** [comment]
Thanks @KaeLL. What threw me here was that I was getting away without doing that for quite some time, I assume because the ESP-IDF headers I was including before timers just happened to already include FreeRTOS.h. Then recently, the header I was using from ESP-IDF just so happened not to include it.

But all good now. Again, thanks.
