### ISSUE TITLE
[Bug][SPI RAM] heap_caps_malloc_prefer() should not abort on allocation failure if there is available SPI RAM (IDFGH-7521)

### ISSUE THREAD

**Issue by chipweinberger** [espressif/esp-idf#9086]
This is very similar to https://github.com/espressif/esp-idf/pull/7569.

ESP-IDF: v4.4.1
ESP32-S3

In functions that attempt allocation multiple times, we should only abort if *all* attempts fail.

**These 3 functions all need to be fixed in the same way:**
heap_caps_malloc_prefer
heap_caps_realloc_prefer
heap_caps_calloc_prefer (for calloc we also need to implement heap_caps_calloc_base)

**As currently implemented:**
```
IRAM_ATTR void *heap_caps_malloc_prefer( size_t size, size_t num, ... )
{
    va_list argp;
    va_start( argp, num );
    void *r = NULL;
    while (num--) {
        uint32_t caps = va_arg( argp, uint32_t );
        r = heap_caps_malloc( size, caps );
        if (r != NULL) {
            break;
        }
    }
    va_end( argp );
    return r;
}
```

**What it should be:**
```
IRAM_ATTR void *heap_caps_malloc_prefer( size_t size, size_t num, ... )
{
    va_list argp;
    va_start( argp, num );
    void *r = NULL;
    while (num--) {
        uint32_t caps = va_arg( argp, uint32_t );
        r = heap_caps_malloc_base( size, caps );
        if (r != NULL) {
            break;
        }
    }
    if (r==NULL){
        heap_caps_alloc_failed(size, caps, __func__);
    }
    va_end( argp );
    return r;
}
```

**Comment by chipweinberger** [comment]
Here are the full changes:

[heap_caps.c.txt](https://github.com/espressif/esp-idf/files/8823468/heap_caps.c.txt)

**Comment by chipweinberger** [comment]
@o-marshmallow

Maybe you cant take this again? Very simple change.

**Comment by o-marshmallow** [comment]
Hi @chipweinberger ,

I am going to check this, thanks for linking the change

**Comment by chipweinberger** [comment]
Thanks Omar =)

**Comment by chipweinberger** [comment]
Yay =)

**Comment by chipweinberger** [comment]
@o-marshmallow, can this be back ported to v4.4? 

I'd love for v4.4 to be as bug free as possible for those that aren't ready to switch to 5.0.

**Comment by chipweinberger** [comment]
Bump. Would still really love to get this in v4.4. It is a *bugfix*, and causes crashes in my code.

**Comment by o-marshmallow** [comment]
Hi @chipweinberger ,

Sorry for the delay, thanks for remainding me, I have creating an internal merge request to backport this change to v4.4
