### ISSUE TITLE
nimBLE txpwr_set (IDFGH-7526)

### ISSUE THREAD

**Issue by DGuimaras** [espressif/esp-idf#9089]
The original apache mynewt-nimble defines ( in nimble/controller/include/controller/ble_phy.h ) the functions

int ble_phy_txpwr_set(int dbm);
and 
int ble_phy_txpwr_get(void);

I can not find these functions or similar in the Esp32 nimBLE component.

**Comment by chipweinberger** [comment]
#include "esp_bt.h"

esp_ble_tx_power_set(ESP_BLE_PWR_TYPE_DEFAULT, ESP_PWR_LVL_P9);

**Comment by rahult-github** [comment]
Hi @chipweinberger , thanks for pointing to the API used in ESP 

Hi @DGuimaras , please confirm if the above resolves your query.

**Comment by rahult-github** [comment]
Am closing this issue. please feel free to reopen in case of any query.

**Comment by veneno-529** [comment]
Hi @rahult-github I am trying to limit range of BLE and am using the same API but on NRF connect it seems to be showing 
Tx power level 3dbm irrespective of whether I change the tx power or not. The range of ble in remaining the same too.

`// GAP - device connectivity definition
    struct ble_gap_adv_params adv_params;
    memset(&adv_params, 0, sizeof(adv_params));
    adv_params.conn_mode = BLE_GAP_CONN_MODE_UND; // connectable or non-connectable
    adv_params.disc_mode = BLE_GAP_DISC_MODE_GEN; // discoverable or non-discoverable
    adv_params.itvl_min = BLE_GAP_ADV_FAST_INTERVAL1_MIN;
    adv_params.itvl_max = BLE_GAP_ADV_FAST_INTERVAL1_MAX;
    esp_ble_tx_power_set(ESP_BLE_PWR_TYPE_ADV, ESP_PWR_LVL_N12);
    rc = ble_gap_adv_start(ble_addr_type, NULL, BLE_ADV_DURATION, &adv_params, ble_gap_event, NULL);
    if (rc != 0) {
        MODLOG_DFLT(ERROR, "error enabling advertisement; rc=%d\n", rc);
        return;
    }
`
Please point me out if I'm doing something wrong

**Comment by rahult-github** [comment]
Hi @veneno-529 

As per [documentation](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/bluetooth/controller_vhci.html#_CPPv420esp_ble_tx_power_set20esp_ble_power_type_t17esp_power_level_t), this command can be used  AFTER connection is created.

**Comment by veneno-529** [comment]
Hi @rahult-github 
True, but the parameter I have passed for limiting the range is for advertising mode. I want my ble device to be discoverable within a short range only. Also I forgot to mention I'm using Nimble. 
Post connection I'm passing "ESP_BLE_PWR_TYPE_CONN_HDL0" as parameter to the function.

**Comment by listout** [comment]
@chipweinberge it's not working with NimBLE stack

**Comment by rahult-github** [comment]
Hi @veneno-529 ,   Please check if [this](https://github.com/espressif/esp-idf/issues/11001#issuecomment-1473265688) helps.  

nrfconnect shows the power level which is passed as data in the adv data. If esp_ble_tx_power_set is being externally used, then the field data need to updated by the application .

**Comment by listout** [comment]
For anyone coming later on. This what I changed in the bleprph example to make it work

```diff
diff --git a/main/main.c b/main/main.c
index 35770ff..d66dde7 100644
--- a/main/main.c
+++ b/main/main.c
@@ -20,6 +20,7 @@
 #include "esp_log.h"
 #include "nvs_flash.h"
 /* BLE */
+#include "esp_bt.h"
 #include "esp_nimble_hci.h"
 #include "nimble/nimble_port.h"
 #include "nimble/nimble_port_freertos.h"
@@ -97,7 +98,36 @@ bleprph_advertise(void)
      * special value BLE_HS_ADV_TX_PWR_LVL_AUTO.
      */
     fields.tx_pwr_lvl_is_present = 1;
-    fields.tx_pwr_lvl = BLE_HS_ADV_TX_PWR_LVL_AUTO;
+	int power_level_t = esp_ble_tx_power_get(ESP_BLE_PWR_TYPE_ADV);
+	switch(power_level_t) {
+		case ESP_PWR_LVL_N12:
+			fields.tx_pwr_lvl = -12;
+			break;
+		case ESP_PWR_LVL_N9:
+			fields.tx_pwr_lvl = -9;
+			break;
+		case ESP_PWR_LVL_N6:
+			fields.tx_pwr_lvl = -6;
+			break;
+		case ESP_PWR_LVL_N3:
+			fields.tx_pwr_lvl = -3;
+			break;
+		case ESP_PWR_LVL_N0:
+			fields.tx_pwr_lvl = 0;
+			break;
+		case ESP_PWR_LVL_P9:
+			fields.tx_pwr_lvl = 9;
+			break;
+		case ESP_PWR_LVL_P6:
+			fields.tx_pwr_lvl = 6;
+			break;
+		case ESP_PWR_LVL_P3:
+			fields.tx_pwr_lvl = 3;
+			break;
+		default:
+			fields.tx_pwr_lvl = BLE_HS_ADV_TX_PWR_LVL_AUTO;
+			break;
+	}
 
     name = ble_svc_gap_device_name();
     fields.name = (uint8_t *)name;
@@ -151,7 +181,11 @@ bleprph_gap_event(struct ble_gap_event *event, void *arg)
 
     switch (event->type) {
     case BLE_GAP_EVENT_CONNECT:
+        esp_ble_tx_power_set(ESP_BLE_PWR_TYPE_DEFAULT, ESP_PWR_LVL_P9);
+        esp_ble_tx_power_set(ESP_BLE_PWR_TYPE_ADV, ESP_PWR_LVL_P9);
+        esp_ble_tx_power_set(ESP_BLE_PWR_TYPE_SCAN ,ESP_PWR_LVL_P9);
         /* A new connection was established or a connection attempt failed. */
+        MODLOG_DFLT(INFO, "connected");
         MODLOG_DFLT(INFO, "connection %s; status=%d ",
                     event->connect.status == 0 ? "established" : "failed",
                     event->connect.status);
@@ -159,6 +193,7 @@ bleprph_gap_event(struct ble_gap_event *event, void *arg)
             rc = ble_gap_conn_find(event->connect.conn_handle, &desc);
             assert(rc == 0);
             bleprph_print_conn_desc(&desc);
+        MODLOG_DFLT(INFO, "connected");
         }
         MODLOG_DFLT(INFO, "\n");
 
@@ -374,6 +409,9 @@ app_main(void)
     /* Set the default device name. */
     rc = ble_svc_gap_device_name_set("nimble-bleprph");
     assert(rc == 0);
+    esp_ble_tx_power_set(ESP_BLE_PWR_TYPE_DEFAULT, ESP_PWR_LVL_P9);
+    esp_ble_tx_power_set(ESP_BLE_PWR_TYPE_ADV, ESP_PWR_LVL_P9);
+    esp_ble_tx_power_set(ESP_BLE_PWR_TYPE_SCAN ,ESP_PWR_LVL_P9);
 
     /* XXX Need to have template for store */
     ble_store_config_init();
```

**Comment by veneno-529** [comment]
Hi @listout in the NRF android app the db has reduced to -12dm thanks to your patch. But I'm not able to observe reduction in range. It is remaining same. Is there any other parameter that needs to be configured?

**Comment by listout** [comment]
I'm not sure about that @veneno-529. Maybe some Espressif devs can give a better result.

**Comment by veneno-529** [comment]
@listout Okay thanks for the patch though it helps to some extent 👍
