### ISSUE TITLE
[TW#14796] spi_master: spi_bus_add_device() does not allow GPIO_NUM_0 to be used as select pin

### ISSUE THREAD

**Issue by pitschu** [espressif/esp-idf#909]
in spi_bus_add_device() function the dev_config->spics_io_num is checked for valid GPIO numbers including 0, but the code only accepts dev_config->spics_io_num > 0. If spics_io_num is 0, nothing is done. This should be possible.

**Comment by ginkgm** [comment]
thanks for reporting this issue, we will fix this.
