### ISSUE TITLE
ULP support for esp32-s3 (IDFGH-7531)

### ISSUE THREAD

**Issue by OrtelWork** [espressif/esp-idf#9094]
**Is your feature request related to a problem? Please describe.**

I want to use the RiskV ULP on a esp32-s3 chip. I tried to run the [ulp_riscv/ds18b20_onewire](https://github.com/espressif/esp-idf/tree/01d014c42def8d0c19e1ce55c07de6761e092ffa/examples/system/ulp_riscv/ds18b20_onewire) example, but it failes with the following error: `"ULP temporarily unsupported on ESP32-S3, running sleep + ULP risks causing permanent damage to chip"` 

**Describe the solution you'd like**

Please implement ULP support for esp32-s3. Do you have a time estimation on when support will be available?

**Describe alternatives you've considered**

None.

**Please give as many details as you can. Include suggestions for useful APIs or interfaces if relevant.**

[**This commit**](https://github.com/espressif/esp-idf/commit/2efd009dfb1352d5f9a0189bf4219e11eb0a454f) is referencing `Fix in-progress: DIG-160`.
I don't know what that means, though.

**Comment by ESP-Marius** [comment]
Hi,

The fix for the digital issue mentioned was merged yesterday, and we have a MR in-review for re-enabling ULP support on S3. If everything goes smoothly it should be merged by the end of the week.
