### ISSUE TITLE
VSCode hangs when hovering local variable named 'data' (IDFGH-7535)

### ISSUE THREAD

**Issue by brand17** [espressif/esp-idf#9098]
## Environment

- Development Kit:      [none]
- Kit version (for WroverKit/PicoKit/DevKitC): []
- Module or chip used:  [ESP32]
- IDF version (run ``git describe --tags`` to find it): v4.4.1
- Build System:         [idf.py]
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it): 8.4.0
- Operating System:     [Windows]
- (Windows only) environment type: [Plain Command Prompt].
- Using an IDE?: [Yes (VSCode 1.67.2)]
- Power Supply:         [USB]

## Problem Description

I think `C/C++ extension` working wrong with `esp-idf extension` when determining the variable scope.

There are no similar errors when 'C/C++ extension' works on console `c/c++` projects (not `esp-idf`).

### Expected Behavior

When hovering a local variable named `data` - there should be no delay and its result should be a definition of the local variable. Renaming this variable using `F2` should be limited by the current file only.

### Actual Behavior

If you have a local variable named 'data' - VSCode hangs for a few seconds when you hover over this variable. And then it gives a huge list of all variables with this name from other libraries.

If you try to refactor (rename the variable with `F2`) - it takes a couple of minutes with a huge list of files offered.

### Steps to reproduce

1. create a file with c extension
2. copy the code below
3. hover a mouse cursor over `data` variable

### Code to reproduce this issue

```cpp
void app_main()
{
    int data;
}

**Comment by chipweinberger** [comment]
This issue should be ask here: https://github.com/espressif/vscode-esp-idf-extension
