### ISSUE TITLE
 ESP32S2 SDSPI conflicts with WIFI (IDFGH-7542)

### ISSUE THREAD

**Issue by ShenRen** [espressif/esp-idf#9105]
## Environment

- Development Kit:      ESP32S2
- Module or chip used:  ESP32S2
- IDF version :  v4.4.1-dirty
- Build System: CMake
- Compiler version: xtensa-esp32s2-elf-gcc (crosstool-NG esp-2021r2-patch3) 8.4.0
- Operating System: Windows
- (Windows only) environment type: ESP Command Prompt
- Using an IDE?: Yes
- Power Supply: USB

## Problem Description

When SDSPI is used alone on ESP32S2 chip, file data reads and writes are normal at 20MHz, but when WIFI is turned on, SD card reads and writes fail. An error:
```
E (58198924) sdmmc_cmd: sdmmc_read_sectors_dma: sdmmc_send_cmd returned 0x108
E (58198924) diskio_sdmmc: sdmmc_read_blocks failed (264)
```
or
```
E (143838) sdmmc_cmd: sdmmc_write_sectors_dma: sdmmc_send_cmd returned 0x108
E (143838) diskio_sdmmc: sdmmc_write_blocks failed (264)
```

**Comment by martinzsiga** [comment]
If you use, LVGL or other lib, check your memory usage.

**Comment by RathiSonika** [comment]
Hello,  based on the information provided, it's challenging to pinpoint the cause of the failure. However, one observation is that you are using  ESP32S2 which is a single core microcontroller. When both WiFi and SDSPI are running concurrently, it's worth checking if the WiFi task is utilising the CPU, preventing the SD operations from executing efficiently. Could you please share your piece of code which will help in debugging and identify the issue more accurately.

**Comment by RathiSonika** [comment]
This issue is being closed. Please feel free to reopen or report a new issue if you encounter a similar problem.
