### ISSUE TITLE
MQTT seems to be blocking API (IDFGH-7543)

### ISSUE THREAD

**Issue by diplfranzhoepfinger** [espressif/esp-idf#9106]
## Environment

- Development Kit:      [ESP32-DevKitC]
- Kit version (for WroverKit/PicoKit/DevKitC): [v4]
- Module or chip used:  [ESP32-WROVER]
- IDF version (run ``git describe --tags`` to find it):
v4.4
- Build System:         [CMake|idf.py]
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it):
xtensa-esp32-elf-gcc (crosstool-NG esp-2021r2) 8.4.0
- Operating System:     [Linux]
- Using an IDE?: [Yes (please give details)] Eclipse
- Power Supply:         [USB]

## Problem Description

It seems that the MQTT API is blocking. 

### Actual Behavior

we have duration_min/max 1000/1000 microseconds before MQTT run

we have duration_min/max 34/364679 microseconds while connecting, this might be worse if using ESP-Modem or slower Internet connections. This Means that the Task-Scheduler is totally blocked at least once for about 400ms. in Best conditions. 

we have duration_min/max 649/1351 microseconds after the run of the sample, which is acceptable. 

### Steps to reproduce

run the Project

### Code to reproduce this issue

https://github.com/DiplomInformatikerFranzHoepfinger/mqtt_and_watchdog

## Debug Logs

```
Executing action: monitor
Running idf_monitor in directory /home/franz/git/franz/mqtt_and_watchdog/mqtt_ssl
Executing "/home/franz/.espressif/python_env/idf4.4_py3.8_env/bin/python /home/franz/esp-idf-v4.4/tools/idf_monitor.py -p /dev/ttyUSB0 -b 115200 --toolchain-prefix xtensa-esp32-elf- --target esp32 --revision 3 --print_filter  /home/franz/git/franz/mqtt_and_watchdog/mqtt_ssl/build/mqtt_ssl.elf -m '/home/franz/.espressif/python_env/idf4.4_py3.8_env/bin/python' '/home/franz/esp-idf-v4.4/tools/idf.py'"...
--- idf_monitor on /dev/ttyUSB0 115200 ---
--- Quit: Ctrl+] | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---
ets Jul 29 2019 12:21:46

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:6932
load:0x40078000,len:15516
load:0x40080400,len:4284
0x40080400: _init at ??:?

entry 0x40080680
I (27) boot: ESP-IDF v4.4-dirty 2nd stage bootloader
I (27) boot: compile time 17:31:46
I (27) boot: chip revision: 3
I (30) qio_mode: Enabling default flash chip QIO
I (36) boot.esp32: SPI Speed      : 80MHz
I (40) boot.esp32: SPI Mode       : QIO
I (45) boot.esp32: SPI Flash Size : 8MB
I (50) boot: Enabling RNG early entropy source...
I (55) boot: Partition Table:
I (58) boot: ## Label            Usage          Type ST Offset   Length
I (66) boot:  0 nvs              WiFi data        01 02 00009000 00006000
I (73) boot:  1 phy_init         RF data          01 01 0000f000 00001000
I (81) boot:  2 factory          factory app      00 00 00010000 00177000
I (88) boot: End of partition table
I (92) esp_image: segment 0: paddr=00010020 vaddr=3f400020 size=1b2a4h (111268) map
I (132) esp_image: segment 1: paddr=0002b2cc vaddr=3ffb0000 size=02f2ch ( 12076) load
I (135) esp_image: segment 2: paddr=0002e200 vaddr=40080000 size=01e18h (  7704) load
I (140) esp_image: segment 3: paddr=00030020 vaddr=400d0020 size=8b864h (571492) map
I (303) esp_image: segment 4: paddr=000bb88c vaddr=40081e18 size=118e4h ( 71908) load
I (327) esp_image: segment 5: paddr=000cd178 vaddr=50000000 size=00010h (    16) load
I (336) boot: Loaded app from partition at offset 0x10000
I (337) boot: Disabling RNG early entropy source...
I (349) cpu_start: Pro cpu up.
I (349) cpu_start: Single core mode
I (357) cpu_start: Pro cpu start user code
I (357) cpu_start: cpu freq: 240000000
I (357) cpu_start: Application information:
I (362) cpu_start: Project name:     mqtt_ssl
I (367) cpu_start: App version:      v0.1-19-g06a2a91-dirty
I (373) cpu_start: Compile time:     Jun  5 2022 17:43:18
I (379) cpu_start: ELF file SHA256:  52871ca846916717...
I (385) cpu_start: ESP-IDF:          v4.4-dirty
I (391) heap_init: Initializing. RAM available for dynamic allocation:
I (398) heap_init: At 3FF80000 len 00002000 (8 KiB): RTCRAM
I (404) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM
I (410) heap_init: At 3FFB6C08 len 000293F8 (164 KiB): DRAM
I (416) heap_init: At 3FFE0440 len 0001FBC0 (126 KiB): D/IRAM
I (423) heap_init: At 40078000 len 00008000 (32 KiB): IRAM
I (429) heap_init: At 400936FC len 0000C904 (50 KiB): IRAM
I (436) spi_flash: detected chip: generic
I (440) spi_flash: flash io: qio
I (444) cpu_start: Starting scheduler on PRO CPU.
I (449) example: Example configured to blink GPIO LED!
I (454) gpio: GPIO[5]| InputEn: 0| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 
I (5464) example: duration_min/max 957/1000 microseconds
I (10464) example: duration_min/max 1000/1000 microseconds
I (15464) example: duration_min/max 1000/1000 microseconds
I (20464) example: duration_min/max 1000/1000 microseconds
I (20464) MQTTS_EXAMPLE: [APP] Startup..
I (20464) MQTTS_EXAMPLE: [APP] Free memory: 292072 bytes
I (20469) MQTTS_EXAMPLE: [APP] IDF version: v4.4-dirty
I (20489) wifi:wifi driver task: 3ffbcf68, prio:23, stack:6656, core=0
I (20489) system_api: Base MAC address is not set
I (20489) system_api: read default base MAC address from EFUSE
I (20500) wifi:wifi firmware version: 7679c42
I (20500) wifi:wifi certification version: v7.0
I (20504) wifi:config NVS flash: enabled
I (20508) wifi:config nano formating: disabled
I (20512) wifi:Init data frame dynamic rx buffer num: 32
I (20517) wifi:Init management frame dynamic rx buffer num: 32
I (20523) wifi:Init management short buffer num: 32
I (20527) wifi:Init dynamic tx buffer num: 32
I (20531) wifi:Init static rx buffer size: 1600
I (20536) wifi:Init static rx buffer num: 10
I (20539) wifi:Init dynamic rx buffer num: 32
I (20544) wifi_init: rx ba win: 6
I (20548) wifi_init: tcpip mbox: 32
I (20552) wifi_init: udp mbox: 6
I (20556) wifi_init: tcp mbox: 6
I (20560) wifi_init: tcp tx win: 5744
I (20564) wifi_init: tcp rx win: 5744
I (20568) wifi_init: tcp mss: 1440
I (20572) wifi_init: WiFi IRAM OP enabled
I (20577) wifi_init: WiFi RX IRAM OP enabled
I (20582) example_connect: Connecting to devolo-guest-644...
I (20589) phy_init: phy_version 4670,719f9f6,Feb 18 2021,17:07:07
I (20671) wifi:mode : sta (58:bf:25:e0:71:30)
I (20672) wifi:enable tsf
I (20673) example_connect: Waiting for IP(s)
I (22717) wifi:new:<11,0>, old:<1,0>, ap:<255,255>, sta:<11,0>, prof:1
I (23080) wifi:state: init -> auth (b0)
I (23093) wifi:state: auth -> assoc (0)
I (23101) wifi:state: assoc -> run (10)
I (23124) wifi:connected with devolo-guest-644, aid = 2, channel 11, BW20, bssid = be:be:f4:a6:be:f4
I (23124) wifi:security: WPA2-PSK, phy: bgn, rssi: -43
I (23127) wifi:pm start, type: 1

W (23135) wifi:<ba-add>idx:0 (ifx:0, be:be:f4:a6:be:f4), tid:6, ssn:2, winSize:64
I (23168) wifi:AP's beacon interval = 102400 us, DTIM period = 1
I (23987) esp_netif_handlers: example_connect: sta ip: 192.168.178.98, mask: 255.255.255.0, gw: 192.168.178.1
I (23988) example_connect: Got IPv4 event: Interface "example_connect: sta" address: 192.168.178.98
I (24487) example_connect: Got IPv6 event: Interface "example_connect: sta" address: fe80:0000:0000:0000:5abf:25ff:fee0:7130, type: ESP_IP6_ADDR_IS_LINK_LOCAL
I (24492) example_connect: Connected to example_connect: sta
I (24498) example_connect: - IPv4 address: 192.168.178.98
I (24504) example_connect: - IPv6 address: fe80:0000:0000:0000:5abf:25ff:fee0:7130, type: ESP_IP6_ADDR_IS_LINK_LOCAL
I (24515) MQTTS_EXAMPLE: [APP] Free memory: 249020 bytes
I (24522) MQTTS_EXAMPLE: Other event id:7
W (24535) wifi:<ba-add>idx:1 (ifx:0, be:be:f4:a6:be:f4), tid:0, ssn:0, winSize:64
I (25732) MQTTS_EXAMPLE: MQTT_EVENT_CONNECTED
I (25733) MQTTS_EXAMPLE: sent subscribe successful, msg_id=37197
I (25735) MQTTS_EXAMPLE: sent subscribe successful, msg_id=48076
I (25740) MQTTS_EXAMPLE: sent unsubscribe successful, msg_id=5989
I (25936) MQTTS_EXAMPLE: MQTT_EVENT_SUBSCRIBED, msg_id=37197
I (25938) MQTTS_EXAMPLE: sent publish successful, msg_id=0
I (25990) example: duration_min/max 34/364679 microseconds
I (26142) MQTTS_EXAMPLE: MQTT_EVENT_SUBSCRIBED, msg_id=48076
I (26143) MQTTS_EXAMPLE: sent publish successful, msg_id=0
I (26346) MQTTS_EXAMPLE: MQTT_EVENT_UNSUBSCRIBED, msg_id=5989
I (26490) MQTTS_EXAMPLE: MQTT_EVENT_DATA
TOPIC=/topic/qos0
DATA=data
I (26755) MQTTS_EXAMPLE: MQTT_EVENT_DATA
TOPIC=/topic/qos0
DATA=data
I (30990) example: duration_min/max 31/1970 microseconds
I (35990) example: duration_min/max 576/1424 microseconds
I (40990) example: duration_min/max 623/1377 microseconds
I (45990) example: duration_min/max 567/1433 microseconds
I (50990) example: duration_min/max 726/1274 microseconds
I (55990) example: duration_min/max 649/1351 microseconds
```

## Other items if possible

- [X ] sdkconfig file see github linked above.

**Comment by diplfranzhoepfinger** [comment]
\### Actual Behavior

we have duration\_min/max 1000/1000 microseconds before MQTT run

we have duration\_min/max 34/364679 microseconds while connecting, this might be worse if using ESP-Modem or slower Internet connections. This Means that the Task-Scheduler is totally blocked at least once for about 400ms. in Best conditions.

we have duration\_min/max 649/1351 microseconds after the run of the sample, which is acceptable.

\### Steps to reproduce

run the Project

\### Code to reproduce this issue

https://github.com/DiplomInformatikerFranzHoepfinger/mqtt_and_watchdog

\## Debug Logs

\`\`\`  
Executing action: monitor  
Running idf\_monitor in directory /home/franz/git/franz/mqtt\_and\_watchdog/mqtt\_ssl  
Executing "/home/franz/.espressif/python\_env/idf4.4\_py3.8\_env/bin/python /home/franz/esp-idf-v4.4/tools/idf\_monitor.py -p /dev/ttyUSB0 -b 115200 --toolchain-prefix xtensa-esp32-elf- --target esp32 --revision 3 --print\_filter  /home/franz/git/franz/mqtt\_and\_watchdog/mqtt\_ssl/build/mqtt\_ssl.elf -m '/home/franz/.espressif/python\_env/idf4.4\_py3.8\_env/bin/python' '/home/franz/esp-idf-v4.4/tools/idf.py'"...  
\--- idf\_monitor on /dev/ttyUSB0 115200 ---  
\--- Quit: Ctrl+\] | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---  
ets Jul 29 2019 12:21:46

rst:0x1 (POWERON\_RESET),boot:0x13 (SPI\_FAST\_FLASH\_BOOT)  
configsip: 0, SPIWP:0xee  
clk\_drv:0x00,q\_drv:0x00,d\_drv:0x00,cs0\_drv:0x00,hd\_drv:0x00,wp\_drv:0x00  
mode:DIO, clock div:1  
load:0x3fff0030,len:6932  
load:0x40078000,len:15516  
load:0x40080400,len:4284  
0x40080400: \_init at ??:?

entry 0x40080680  
I (27) boot: ESP-IDF v4.4-dirty 2nd stage bootloader  
I (27) boot: compile time 17:31:46  
I (27) boot: chip revision: 3  
I (30) qio\_mode: Enabling default flash chip QIO  
I (36) boot.esp32: SPI Speed      : 80MHz  
I (40) boot.esp32: SPI Mode       : QIO  
I (45) boot.esp32: SPI Flash Size : 8MB  
I (50) boot: Enabling RNG early entropy source...  
I (55) boot: Partition Table:  
I (58) boot: ## Label            Usage          Type ST Offset   Length  
I (66) boot:  0 nvs              WiFi data        01 02 00009000 00006000  
I (73) boot:  1 phy\_init         RF data          01 01 0000f000 00001000  
I (81) boot:  2 factory          factory app      00 00 00010000 00177000  
I (88) boot: End of partition table  
I (92) esp\_image: segment 0: paddr=00010020 vaddr=3f400020 size=1b2a4h (111268) map  
I (132) esp\_image: segment 1: paddr=0002b2cc vaddr=3ffb0000 size=02f2ch ( 12076) load  
I (135) esp\_image: segment 2: paddr=0002e200 vaddr=40080000 size=01e18h (  7704) load  
I (140) esp\_image: segment 3: paddr=00030020 vaddr=400d0020 size=8b864h (571492) map  
I (303) esp\_image: segment 4: paddr=000bb88c vaddr=40081e18 size=118e4h ( 71908) load  
I (327) esp\_image: segment 5: paddr=000cd178 vaddr=50000000 size=00010h (    16) load  
I (336) boot: Loaded app from partition at offset 0x10000  
I (337) boot: Disabling RNG early entropy source...  
I (349) cpu\_start: Pro cpu up.  
I (349) cpu\_start: Single core mode  
I (357) cpu\_start: Pro cpu start user code  
I (357) cpu\_start: cpu freq: 240000000  
I (357) cpu\_start: Application information:  
I (362) cpu\_start: Project name:     mqtt\_ssl  
I (367) cpu\_start: App version:      v0.1-19-g06a2a91-dirty  
I (373) cpu\_start: Compile time:     Jun  5 2022 17:43:18  
I (379) cpu\_start: ELF file SHA256:  52871ca846916717...  
I (385) cpu\_start: ESP-IDF:          v4.4-dirty  
I (391) heap\_init: Initializing. RAM available for dynamic allocation:  
I (398) heap\_init: At 3FF80000 len 00002000 (8 KiB): RTCRAM  
I (404) heap\_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM  
I (410) heap\_init: At 3FFB6C08 len 000293F8 (164 KiB): DRAM  
I (416) heap\_init: At 3FFE0440 len 0001FBC0 (126 KiB): D/IRAM  
I (423) heap\_init: At 40078000 len 00008000 (32 KiB): IRAM  
I (429) heap\_init: At 400936FC len 0000C904 (50 KiB): IRAM  
I (436) spi\_flash: detected chip: generic  
I (440) spi\_flash: flash io: qio  
I (444) cpu\_start: Starting scheduler on PRO CPU.  
I (449) example: Example configured to blink GPIO LED!  
I (454) gpio: GPIO\[5\]| InputEn: 0| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0   
I (5464) example: duration\_min/max 957/1000 microseconds  
I (10464) example: duration\_min/max 1000/1000 microseconds  
I (15464) example: duration\_min/max 1000/1000 microseconds  
I (20464) example: duration\_min/max 1000/1000 microseconds  
I (20464) MQTTS\_EXAMPLE: \[APP\] Startup..  
I (20464) MQTTS\_EXAMPLE: \[APP\] Free memory: 292072 bytes  
I (20469) MQTTS\_EXAMPLE: \[APP\] IDF version: v4.4-dirty  
I (20489) wifi:wifi driver task: 3ffbcf68, prio:23, stack:6656, core=0  
I (20489) system\_api: Base MAC address is not set  
I (20489) system\_api: read default base MAC address from EFUSE  
I (20500) wifi:wifi firmware version: 7679c42  
I (20500) wifi:wifi certification version: v7.0  
I (20504) wifi:config NVS flash: enabled  
I (20508) wifi:config nano formating: disabled  
I (20512) wifi:Init data frame dynamic rx buffer num: 32  
I (20517) wifi:Init management frame dynamic rx buffer num: 32  
I (20523) wifi:Init management short buffer num: 32  
I (20527) wifi:Init dynamic tx buffer num: 32  
I (20531) wifi:Init static rx buffer size: 1600  
I (20536) wifi:Init static rx buffer num: 10  
I (20539) wifi:Init dynamic rx buffer num: 32  
I (20544) wifi\_init: rx ba win: 6  
I (20548) wifi\_init: tcpip mbox: 32  
I (20552) wifi\_init: udp mbox: 6  
I (20556) wifi\_init: tcp mbox: 6  
I (20560) wifi\_init: tcp tx win: 5744  
I (20564) wifi\_init: tcp rx win: 5744  
I (20568) wifi\_init: tcp mss: 1440  
I (20572) wifi\_init: WiFi IRAM OP enabled  
I (20577) wifi\_init: WiFi RX IRAM OP enabled  
I (20582) example\_connect: Connecting to devolo-guest-644...  
I (20589) phy\_init: phy\_version 4670,719f9f6,Feb 18 2021,17:07:07  
I (20671) wifi:mode : sta (58:bf:25:e0:71:30)  
I (20672) wifi:enable tsf  
I (20673) example\_connect: Waiting for IP(s)  
I (22717) wifi:new:\<11,0>, old:\<1,0>, ap:\<255,255>, sta:\<11,0>, prof:1  
I (23080) wifi:state: init -> auth (b0)  
I (23093) wifi:state: auth -> assoc (0)  
I (23101) wifi:state: assoc -> run (10)  
I (23124) wifi:connected with devolo-guest-644, aid = 2, channel 11, BW20, bssid = be:be:f4:a6:be:f4  
I (23124) wifi:security: WPA2-PSK, phy: bgn, rssi: -43  
I (23127) wifi:pm start, type: 1

W (23135) wifi:\<ba-add>idx:0 (ifx:0, be:be:f4:a6:be:f4), tid:6, ssn:2, winSize:64  
I (23168) wifi:AP's beacon interval = 102400 us, DTIM period = 1  
I (23987) esp\_netif\_handlers: example\_connect: sta ip: 192.168.178.98, mask: 255.255.255.0, gw: 192.168.178.1  
I (23988) example\_connect: Got IPv4 event: Interface "example\_connect: sta" address: 192.168.178.98  
I (24487) example\_connect: Got IPv6 event: Interface "example\_connect: sta" address: fe80:0000:0000:0000:5abf:25ff:fee0:7130, type: ESP\_IP6\_ADDR\_IS\_LINK\_LOCAL  
I (24492) example\_connect: Connected to example\_connect: sta  
I (24498) example\_connect: - IPv4 address: 192.168.178.98  
I (24504) example\_connect: - IPv6 address: fe80:0000:0000:0000:5abf:25ff:fee0:7130, type: ESP\_IP6\_ADDR\_IS\_LINK\_LOCAL  
I (24515) MQTTS\_EXAMPLE: \[APP\] Free memory: 249020 bytes  
I (24522) MQTTS\_EXAMPLE: Other event id:7  
W (24535) wifi:\<ba-add>idx:1 (ifx:0, be:be:f4:a6:be:f4), tid:0, ssn:0, winSize:64  
I (25732) MQTTS\_EXAMPLE: MQTT\_EVENT\_CONNECTED  
I (25733) MQTTS\_EXAMPLE: sent subscribe successful, msg\_id=37197  
I (25735) MQTTS\_EXAMPLE: sent subscribe successful, msg\_id=48076  
I (25740) MQTTS\_EXAMPLE: sent unsubscribe successful, msg\_id=5989  
I (25936) MQTTS\_EXAMPLE: MQTT\_EVENT\_SUBSCRIBED, msg\_id=37197  
I (25938) MQTTS\_EXAMPLE: sent publish successful, msg\_id=0  
I (25990) example: duration\_min/max 34/364679 microseconds  
I (26142) MQTTS\_EXAMPLE: MQTT\_EVENT\_SUBSCRIBED, msg\_id=48076  
I (26143) MQTTS\_EXAMPLE: sent publish successful, msg\_id=0  
I (26346) MQTTS\_EXAMPLE: MQTT\_EVENT\_UNSUBSCRIBED, msg\_id=5989  
I (26490) MQTTS\_EXAMPLE: MQTT\_EVENT\_DATA  
TOPIC=/topic/qos0  
DATA=data  
I (26755) MQTTS\_EXAMPLE: MQTT\_EVENT\_DATA  
TOPIC=/topic/qos0  
DATA=data  
I (30990) example: duration\_min/max 31/1970 microseconds  
I (35990) example: duration\_min/max 576/1424 microseconds  
I (40990) example: duration\_min/max 623/1377 microseconds  
I (45990) example: duration\_min/max 567/1433 microseconds  
I (50990) example: duration\_min/max 726/1274 microseconds  
I (55990) example: duration\_min/max 649/1351 microseconds  
\`\`\`

\## Other items if possible

\- \[X \] sdkconfig file see github linked above.

**Comment by david-cermak** [comment]
@diplfranzhoepfinger Yes most of the mqtt API is blocking, but for publishing you can use `esp_mqtt_client_enqueue()`

https://github.com/espressif/esp-mqtt/blob/684843a3096fea77346fd7f6994dcf984d65308b/include/mqtt_client.h#L354-L373

Which would just enqueue the message to be sent later in the mqtt thread context.

About connection: It's also happening in the mqtt task, so shouldn't block user threads. The default timeout is 10s, but it's configurable:

https://github.com/espressif/esp-mqtt/blob/master/include/mqtt_client.h#L221

**Comment by franz-ms-muc** [comment]
Hello, 

any news about this ? 
Vasil from [www.rilabs.io](http://www.rilabs.io/) need non-Blocking API.

**Comment by david-cermak** [comment]
Hi all,

If I understand correctly, there are two problems from the threading point of view:
1) mqtt task taking too much computing resources, that you're getting hit by the task WDT
2) other APIs, e.g. publish where you're not only waiting for the actual data to be sent out to the network, but also wait for the confirmation.

While, I cannot help much with the `1)`, as the TLS handshake is happening in the context of mqtt task (Here I'd suggest just adjusting the task watchdog timeout based on your needs, usually key/cert size), the second one could be easily handled by our [mqtt cxx wrapper](https://github.com/espressif/esp-idf/tree/master/examples/cxx/experimental/esp_mqtt_cxx), that helps creating your own actions after an asynchronous event happened, for example:

https://github.com/espressif/esp-idf/blob/c2ccc383dae2a47c2c2dc8c7ad78175a3fd11361/examples/cxx/experimental/esp_mqtt_cxx/ssl/main/mqtt_ssl_example.cpp#L26-L44
