### ISSUE TITLE
NimBLE equivalents to esp_ble_gatt_set_local_mtu()  and esp_ble_gattc_send_mtu_req() ? (IDFGH-7550)

### ISSUE THREAD

**Issue by DGuimaras** [espressif/esp-idf#9110]
Hi,
what functions can be used in nimBLE component of esp-idf to set the local mtu and send an mtu request ?

For bluedroid there is esp_ble_gatt_set_local_mtu()  and esp_ble_gattc_send_mtu_req().
What is the equivalent in nimBLE ?

**Comment by rahult-github** [comment]
Hi @DGuimaras ,

Can you please check if the [ble_att_set_preferred_mtu](https://github.com/espressif/esp-nimble/blob/3c2e1d4b5b9066db5c227c669012fd0568daee12/nimble/host/include/host/ble_att.h#L184)  and  [ble_gattc_exchange_mtu](https://github.com/espressif/esp-nimble/blob/3c2e1d4b5b9066db5c227c669012fd0568daee12/nimble/host/include/host/ble_gatt.h#L162 )  is what you looking for ? 

Thanks,
 Rahul

**Comment by DGuimaras** [comment]
Yes, it is!
Thanks
