### ISSUE TITLE
Issue with CMake includes for component/driver (IDFGH-7551)

### ISSUE THREAD

**Issue by AndruePeters** [espressif/esp-idf#9111]
## Environment

- Development Kit:      [ESP32-Wrover-Kit]
- Kit version (DevKitC): [|v2]
- Module or chip used:  [ESP32]
- IDF version (run ``git describe --tags`` to find it): latest
- Build System:         [CMake]
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it): 8.4.0
- Operating System:     [Linux]
- Using an IDE?: [No]

## Problem Description

I'm developing for the esp32. I wrote my own GPIO driver for C++ since the components/cxx branch is experimental.
My program links and runs correctly. 

However, there's an issue with how CMake is exporting the compile_commands.json file. It's not exporting the path to "driver/gpio.h"
to compile_commands.json.

The `"include/driver"` line is explicitly marked as private when `idf_component_register` is called. 
``` cmake
    idf_component_register(SRCS "${srcs}"
                        INCLUDE_DIRS ${includes} 
                        PRIV_INCLUDE_DIRS "include/driver"
                        PRIV_REQUIRES efuse esp_timer
                        REQUIRES esp_pm esp_ringbuf freertos soc hal esp_hw_support
                        LDFRAGMENTS linker.lf)
```

This is my CMakeLists.txt:
``` cmake
add_library(hal_gpio "src/gpio.cpp")
target_include_directories(hal_gpio PUBLIC "include/")
target_link_libraries(hal_gpio PUBLIC idf::driver containers)
```

As you can see, I'm properly linking against `idf::driver`. My project compiles, links, and runs properly. But,
`components/driver/include/` is not being added to the PUBLIC include directories of `idf::driver`, so it doesn't
get properly exported to my wrapper library. 

I believe the source of the problem is that the `includes` variable is being set incorrectly.
`${includes}` does have `esp-idf/components/driver/esp32/driver/include`. However, this directory does not include
`gpio.h`, so `gpio.h` is never exported to the compile commands.

Should `components/driver/include` actually be private? Or, should `components/driver/esp32/include/driver/` contains a `gpio.h` file?

**Comment by o-marshmallow** [comment]
Hi @AndruePeters ,

What you see in driver's `CMakeList.txt` file is correct, `include/driver` is private, **but** `include` is public. This means that C files within driver component don't need to prefix header files with `driver/` whereas external components must do it. For example, any C file within `driver` can  include `gpio.h` by using:
```
#include "gpio.h`
```
Whereas C files outside of `driver` component must use:
```
#include "driver/gpio.h"
```
Of course, the file is in fact the same, only the way GCC will handle the path of inclusion changes.


Thus, in your case, you should be able to include any header file from driver component as long as you prefix the name with `driver/`. One thing that puzzles me is that you don't seem to be using `idf_component_register` in your CMake file.
Where did you place your `CMakeList.txt` file?

If you take a look at the one in `examples/cxx/experimental/experimental_cpp_component`, you will see that it does make the use of `idf_component_register` function. In fact, I would expect that if you used the following, you wouldn't have any problem:
```
idf_component_register(SRCS "src/gpio.cpp"
                    INCLUDE_DIRS "include/"
                    REQUIRES driver)
```

**Comment by AndruePeters** [comment]
Okay. So, the CMake choice there is appropriate. It just makes no sense that the directory isn't being exported to the compile_commands.json. So, I still believe there's an issue. It's obviously being included on some level as it's compiling. But, why isn't it being exported to compile_commands.json? 

It *should* be a property of `idf::driver`. Also, this doesn't happen with other Espressif libraries I do use such as `idf::http_server`. So, I think it is a CMake bug. 


And to answer your followup question: I do use that for the actual application, but I don't for the libraries.
  1. I found it wasn't needed for the libraries -- I can just make normal CMake libraries and it works fine.
  2. A lot of libraries I was writing didn't rely on Espressif's code, and it felt wrong to register those, so using the 'raw' CMake made the style more consistent.
  3. I'm not sure how `idf_component_register` works with header only libraries, and because the normal method works (CMake interface libraries), I just never tried. 
  4. The build system should work regardless of using idf_component_register or not since it's a simple wrapper.

**Comment by AndruePeters** [comment]
I'm rechecking this morning. You're completely right in that adding "include" should allow me to write `#include <driver/gpio.h>`. It's just weird it's not being exported to `compile_commands.json`.

**Comment by o-marshmallow** [comment]
Hi @AndruePeters ,

I just had a try writing a small library which depends on `idf::driver` component using pure CMake functions: `add_library`, `target_include_directories`, `target_link_libraries`. My main application is still using `idf_component_register`.
The resulted `compile_commands.json` mainly contains the following entries:
```
{
    "command": "xtensa-esp32-elf-gcc -I/home/esp/esp-idf/components/driver/include [...] -c /home/esp/esp-idf/examples/cxx/experimental/simple_i2c_rw_example/my_gpio.c",
    "file": "/home/esp/esp-idf/examples/cxx/experimental/simple_i2c_rw_example/my_gpio.c"
},
{
    "command": "xtensa-esp32-elf-gcc -I../../../../../components/driver/include -I../../../../../components/driver/include/driver [...] -c /home/esp/esp-idf/components/driver/gpio/gpio.c",
    "file": "/home/esp/esp-idf/components/driver/gpio/gpio.c"
}
```

This seems consistent with what we said before: the command for driver's `gpio.c` contains both private and public headers directory whereas my own GPIO lib, `my_gpio.c` only contains the public one.

**Comment by AndruePeters** [comment]
Hmm. Let me delete and then reinstall the latest esp idf. I'll respond
within a couple days.

**Comment by AndruePeters** [comment]
Definitely seems to be a vscode intellisense issue. Not sure what it is. The compile_commands.json is correct like you mentioned.

**Comment by o-marshmallow** [comment]
@AndruePeters Should I close the issue then?

**Comment by AndruePeters** [comment]
Sorry. Thought this was already closed. 

Closing because the issue is a bug with VSCode.

**Comment by AndruePeters** [comment]
It's disappointing, but I imagine so. I'm still trying to figure out how
VSCodes Intellisense engine is messing this up. But that's not related to
the problem I reported.
