### ISSUE TITLE
Expose CONFIG option to deal with dont-append-digest (IDFGH-7566)

### ISSUE THREAD

**Issue by josesimoes** [espressif/esp-idf#9126]
**Is your feature request related to a problem? Please describe.**

Following [this](https://github.com/espressif/esptool/commit/4e56df519613b24874e3555c37d5df43be85b5af) recent change in esptool, I believe it would be advisable to expose a new CONFIG option to control appending (or not) that `--dont-append-digest` option when calling elf2image. Otherwise, if one requires a image without digest has to run elf2image again after the build.

**Describe the solution you'd like**

Having a CONFIG option to control this. (unless I'm missing a better way of accomplishing this with the existing ones).

**Describe alternatives you've considered**

None that I could find.

**Additional context**

**Comment by dobairoland** [comment]
For future reference, I'll close this issue after both 9c46c98b4c81699209fc9f44e3a3b1d94c5bf5b7 and 7dc0a1db1814ceb36d2e4d1ef33590b899dfde9a are available here.
