### ISSUE TITLE
Sketch not working without Serial Monitor? (IDFGH-7568)

### ISSUE THREAD

**Issue by neckerblue** [espressif/esp-idf#9128]
## Environment

- Development Kit:      [[ESP32-DevKitS](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/hw-reference/esp32/user-guide-devkits-r-v1.1.html) | [ESP32­WROOM­32E](https://www.espressif.com/sites/default/files/documentation/esp32-wroom-32e_esp32-wroom-32ue_datasheet_en.pdf) ]
![image](https://user-images.githubusercontent.com/18232141/172706553-e1d48dfc-a202-4f17-a3cf-e71cbf8ca0eb.png) ![image](https://user-images.githubusercontent.com/18232141/172706614-d5cf7aaa-176f-41ad-8678-bce89194b299.png)
- Kit version : [not sure, bought month ago, both are black/gold in color]
- Module or chip used:  [ESP32-WROOM-32 : ESP32-D0WD-V3]
- Operating System:     [Windows]
- Using an IDE?: [Yes : Arduino IDE 1.8.19]
- Power Supply:         [USB from PC (500mA) | External 5V from lab power supply (5A max)| PowerBank(3A max)]

## Problem Description

I do apologise if this is incorrect place to ask such question - I stumbled upon a similar issues here:
[Hang on post-reset boot? (IDFGH-3516) #59](https://github.com/espressif/esp-idf/issues/59), thus decided to give it a try and describe what happens with my small IoT project the best I can.

**Usage:**
I am using a "module" version of ESP32(just the small square with antennae) and program it using a "fixture" dev board (click-in) if I am using the names correctly.
WiFi enabled using [ElegantOTA](https://github.com/ayushsharma82/ElegantOTA) - for over-the-air sketch uploads.
Bluetooth enabled using [ESP32 BLE Keyboard](https://github.com/T-vK/ESP32-BLE-Keyboard) library - for HID BLE Keyboard functionality.
Serial - for Serial Monitors & USB uploads when connected to PC, when module is soldered to custom PCB this Serial is not connected
Serial1 - for incoming data transmissions (simple strings from External Device), only Rx used
Serial2 - for incoming Range measurements data from Range Finder sensor type, only Rx used

Device is supposed to turn on, connect to WiFi(for OTA), advertise itself as BT HID Keyboard, listen to input from RangeFinder, if range is within threshold, then trigger External Device and listen for incoming data, if data received send it as BT HID Keyboard keys.

The problem arises when moving the programmed and otherwise working fine "module" to a custom piece of PCB.

**GPIO:**
![image](https://user-images.githubusercontent.com/18232141/172711443-956a5d7a-6f3c-485c-92e3-83f8f8c721c9.png)
NC - not connected
This is used across ESP32-DevKitS and custom PCB.
All backplate pins connected to GND.
Anything without red arrow and label is not connected.

**The Issue:**
When using ESP32-DevKitS click-in dev board connected through USB to a PC with open Arduino IDE and Serial Monitor, the device works exactly as expected and described above at Usage section.
However, when "clicking-out" of ESP32-DevKitS and soldering the module to the custom PCB, the device seems to run only once. At first power on, I can briefly see it connect to WiFi (I have IP from DHCP and can open it in a browser), I can briefly see it advertise itself as Bluetooth Keyboard and it even briefly reacts to RangeFinder (toggles ExternalDevice on and off).
After reboot (EN button or power cycle) the module seems to never work again (does not connect to WiFi, does not advertise BT, does not react to Range Finder, does not trigger External Device) unless desoldered, plugged back in and then back out of ESP32-DevKitS "click-in" dev board (and connecting it to PC via USB).

- [Does not work] When using ESP32­WROOM­32E Module on custom PCB connected to PowerBank through PCB's power supply
- [Does not work] When using ESP32­WROOM­32E Module on custom PCB connected to External Power Source (lab power suppy) through PCB's power supply
- [Works as supposed] When using ESP32-DevKitS connected via USB to PC with Arduino IDE and Serial Monitor connected
- [Works as supposed] When using ESP32-DevKitS connected via USB to External Power Source (lab power supply)
- [Works as supposed] When using ESP32-DevKitS connected via USB to regular PowerBank
**and best of all:**
- [Works as supposed] When using **empty** ESP32-DevKitS connected via USB to PC with Arduino IDE and Serial Monitor connected and custom PCB with soldered-in ESP32 "module", PCB is powered by PowerBank and both ESP32-DevKitS and PCB are connected to each other's GPIO pins and common-grounded.
For example: PowerBank -> custom PCB (with ESP32 soldered in) -> jumper GPIO cables + common GND -> ESP32-DevKitS (empty) -> PC (USB)

I do realize it might seem like the custom PCB issue, but I have tested for continuity and appropriate voltages all over it and it seem to be in accordance to all the datasheets. It was also a paid custom design from a professional company - I don't think I would be able to design it myself.

The biggest indicator _"that it is not the custom PCB at fault here"_ is the fact the PCB **was working fine** [as supposed] up untill I added the WiFi functionality together with OTA.

I feel like I am missing something obvious here...
Maybe some obscure requirement when using both WiFi and Bluetooth?
Maybe some error with configuration/profile (please see screenshot below)?
I did find a thread, at Arduino Forums, claiming that I cannot do "Serial.begin()" if there is no Serial Monitor connected because that's blocking and will hang my project because... no Serial Monitor is connected - is that even ture? I did try and remove all "Serial" calls with no change in results, though.

Any insight would be highly appreciated.

**Arduino IDE Configuration:**
![image](https://user-images.githubusercontent.com/18232141/172706817-17e83ca8-6915-4536-bb54-6973149257b8.png)

### Code to reproduce this issue

[my_iot.ino](https://gist.github.com/neckerblue/cd4f72c6173bbbebe92823f1cd7114fe)
Please ignore line 95: millis_start = millis(); , it was supposed to be removed as any other millis();

**Comment by chipweinberger** [comment]
Does your PCB expose the UART Rx & Tx Lines? 

If so, It would be useful to look at the logs while the device is running in the PCB.

**Comment by neckerblue** [comment]
> Does your PCB expose the UART Rx & Tx Lines?
> 
> If so, It would be useful to look at the logs while the device is running in the PCB.

Do you mean those:
![image](https://user-images.githubusercontent.com/18232141/172929902-dbb50181-70a2-4676-9566-92a2d1b74797.png)
If yes, then no - the PCB does not expose those GPIOs, unfortunately :(

I could try to solder some thin wires to the module and connect to some TTL/USB converter, though?

**Comment by danomation** [comment]
If this doesn't fix your problem I recommend commenting out anything that says serial
