### ISSUE TITLE
Is there any demo that using UPNP protocol via esp32 (IDFGH-7582)

### ISSUE THREAD

**Issue by Kingwulin** [espressif/esp-idf#9139]
I want to achive PC on the same LAN to be able to access the esp32 device through the router
is there any lib or demo for me to achive it
Thanks alot

**Comment by kostaond** [comment]
>  to be able to access the esp32 device through the router

It's too generic request. Could you please elaborate deeper your use case? Just give me an example

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to short of feedback, feel free to reopen with more updates.
