### ISSUE TITLE
Max interrupt masking duration (IDFGH-72)

### ISSUE THREAD

**Issue by devsaurus** [espressif/esp-idf#915]
I've been searching for a guideline but couldn't find any hints. Can you please clarify:
- Maximum duration to disable interrupts globally
- Maximum runtime of an ISR
  Interrupting a task or nested ISRs.

Both as constraints for developing an application and for a picture of what I can expect from the IDF drivers etc.

**Comment by Dazza0** [comment]
@devsaurus A lot of these guidelines will depend on your application requirements and configuration. Here are a few general pointers

> Maximum duration to disable interrupts globally

The absolute maximum amount of time that Interrupts should be disabled should be less than the interrupt watchdog timer's timeout. By default the [INT WDT's timeout](ESP_INT_WDT_TIMEOUT_MS) is set to 300ms (or 800ms if SPI RAM is supported). If the INT WDT triggers, it will just do a system reset

> Maximum runtime of an ISR

Given an ISR at a particular priority will prevent other ISRs of the same level and lower priority ISRs from running, ISRs should be kept short where possible. The FreeRTOS Tick interrupt is a low priority (level 1) interrupt that by default needs to run every 10ms ([configurable](https://docs.espressif.com/projects/esp-idf/en/release-v4.3/esp32/api-reference/kconfig.html#config-freertos-hz)).

Given the 10ms period this, we want to avoid any delay which causes the tick interrupt to miss a tick period (e.g., a 20ms long delay will cause the tick interrupt to miss a tick). Therefore, try to keep anything that stops the tick interrupt to within a couple of milliseconds at most. This includes:

- Disabling interrupts
- Other higher priority ISRs
- Critical sections

> Interrupting a task or nested ISRs.

- When interrupts are disable using `portDISABLE_INTERRUPTS()` or a critical section, it will disable interrupts up to a predfined level (level 3 on the ESP32). This level is the highest level where user registerable C ISRs can run.  This effectively prevents any user registered C ISRs from running (but high level assembly ISRs can still run, [docs here](https://docs.espressif.com/projects/esp-idf/en/release-v4.3/esp32/api-guides/hlinterrupts.html))
- ISR nesting is supported. For example, when inside a level 1 ISR, a level 2 ISR can occur.  You can use a critical section or `portSET_INTERRUPT_MASK_FROM_ISR()` to prevent nesting when inside an ISR
- Likewise, tasks can be interrupted by an ISR. Use a critical section or `portDISABLE_INTERRUPTS()` to prevent this.

I'm closing this issue. Please feel free to reopen if you have any more inquires.
