### ISSUE TITLE
Application fails to boot in v4.3 when SPI flash freq differs between bootloader and application (IDFGH-7601)

### ISSUE THREAD

**Issue by zevv** [espressif/esp-idf#9156]
## Envionment

Custom PCB, ESP32-WROOM-32D on IDF.4.3, 

## Problem Description

we have a problem where our application is not started by the bootloader when there is a 
mismatch in ESPTOOLPY_FLASHFREQ setting between the boot loader and the app.

- bootloader configured for 40MHz, app for 80MHz: does not boot
- bootloader configured fro 80MHz, app for 40MHz, does not boot

This problem started for us when upgrading from idf 4.2 to 4.3, I have bisected this to commit 2373f115fc6db20a0159ccab11e1db0feb4c0bfa

### Expected Behavior

SPI frequency setting difference between app and bootloader code should not prevent the app from booting.

### Actual Behavior

App does not boot when SPI frequency mismatch between bootloader and app.

### Steps to reproduce

I can not reproduce this with the minimal hello_world application, as the result seems to depend on the total binary size; the test we have now is compiling our current application (which ends up at approx 450KB), and putting this code in the top of `main()`

```
printf("started");
volatile int stop = true;
if(stop) for(;;);
```

This message `started` gets printed on idf v4.2, but not on idf v4.2

## Debug Logs

Bootloader boots up to the following lines
```
I (185) esp_image: segment 4: paddr=0x00030020 vaddr=0x400d0020 size=0x4a744 (304964) map
I (283) esp_image: segment 5: paddr=0x0007a76c vaddr=0x4008cbf4 size=0x03648 ( 13896) load
I (289) esp_image: segment 6: paddr=0x0007ddbc vaddr=0x400c0000 size=0x00088 (   136) load
I (299) boot: Loaded app from partition at offset 0x10000
I (299) boot: Disabling RNG early entropy source...
```

After a few seconds pause the ESP reboots:

```
ets Jun  8 2016 00:22:57

rst:0x10 (RTCWDT_RTC_RESET),boot:0x12 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:7160
load:0x40078000,len:13212
ho 0 tail 12 room 4
load:0x40080400,len:4568
entry 0x400806f4
I (29) boot: ESP-IDF v4.2.2-dirty 2nd stage bootloader
I (29) boot: compile time 14:07:12
I (29) boot: chip revision: 1
I (33) boot_comm: chip revision: 1, min. bootloader chip revision: 0
I (40) boot.esp32: SPI Speed      : 80MHz
I (44) boot.esp32: SPI Mode       : DIO
I (49) boot.esp32: SPI Flash Size : 16MB
I (54) boot: Enabling RNG early entropy source...
...
```

## Other items if possible

The problem seems to be introduced by commit 2373f115fc6db20a0159ccab11e1db0feb4c0bfa

**Comment by KonstantinKondrashov** [comment]
Hi @zevv!
Regarding commit 2373f11, it should not affect on any things because the max value in pkg field up to nowday still less or equal 7 . You can run **esptool.py chip_id** to make sure what exactly chip inside it. ESP32-WROOM-32D can be build on any chips, see https://espressif.com/en/products/socs.

Based on the log, probably the app is booted but stucked some where in the startup of app. I would suggest to set the verbos log for app to make sure in it. The next logs after "Disabling RNG ...." would be as below from app. 
I (189) cpu_start: Pro cpu up.
I (189) cpu_start: Starting app cpu, entry point is 0x4008111c
I will check it how to fix it.

**Comment by zevv** [comment]
Hi, output of `chip_id` below.

```
$ esptool.py chip_id
esptool.py v3.1-dev
Found 1 serial ports
Serial port /dev/ttyUSB0
Connecting....
Detecting chip type... ESP32
Chip is ESP32-D0WD (revision 1)
Features: WiFi, BT, Dual Core, 240MHz, VRef calibration in efuse, Coding Scheme None
Crystal is 40MHz
MAC: 10:52:1c:52:2c:d4
Uploading stub...
Running stub...
Stub running...
Warning: ESP32 has no Chip ID. Reading MAC instead.
MAC: 10:52:1c:52:2c:d4
Hard resetting via RTS pin...
```

**Comment by zevv** [comment]
App log at verbose gets me to here, after this nothing happens until the reboot:

```
I (0) cpu_start: App cpu up.
D (306) clk: RTC_SLOW_CLK calibration value: 3068954
```

My application at this time is only one `printf()`, the rest is essentially all unreachable code; I must admit I do not understand at all how 2373f11 can be related to my code not starting up, but still it's happening.

**Comment by KonstantinKondrashov** [comment]
I tried hello_world on master. bootloader with 40Mhz and app with 80Mhz (ESPTOOLPY_FLASHFREQ), App is stucked looks like at the same place. 
@zevv could you try this fix for app?
```diff
diff --git a/components/bootloader_support/src/bootloader_efuse.c b/components/bootloader_support/src/bootloader_efuse.c
index ac5f9f7..9b1556a 100644
--- a/components/bootloader_support/src/bootloader_efuse.c
+++ b/components/bootloader_support/src/bootloader_efuse.c
@@ -9,13 +9,14 @@
 #include "bootloader_common.h"
 #include "hal/efuse_ll.h"
 #include "hal/efuse_hal.h"
+#include "esp_attr.h"
 
-uint8_t bootloader_common_get_chip_revision(void)
+IRAM_ATTR uint8_t bootloader_common_get_chip_revision(void)
 {
     return efuse_hal_get_chip_revision();
 }
 
-uint32_t bootloader_common_get_chip_ver_pkg(void)
+IRAM_ATTR uint32_t bootloader_common_get_chip_ver_pkg(void)
 {
     return efuse_ll_get_chip_ver_pkg();
 }
```

**Comment by zevv** [comment]
Right, you hit the spot, that's some excellent quality support there!

I was already printf()ing my way through the boot processes and ended up in the same place, but I hadn't realized it was related to IRAM execution.

Is there a chance this will get backported to 4.3 as well?

Thanks!

**Comment by KonstantinKondrashov** [comment]
@zevv Thanks a lot for confirmation! Yes, I will create backport for 4.4 and 4.3 as well.
