### ISSUE TITLE
TWAI Listen mode causes BUS error in wrong baud rate (IDFGH-7602)

### ISSUE THREAD

**Issue by dev-techshlok** [espressif/esp-idf#9157]
Hello,

## Environment
- Module or chip used:  [ESP32-WROOM-32|ESP32-WROOM-32D
- IDF version:
    // v5.0-dev-3290-g01d014c42d
- Build System:         [idf.py]
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it):
    // (crosstool-NG esp-2021r2-patch3) 8.4.0
- Operating System:     Linux
- Using an IDE?: [No|
- Power Supply:         [USB]

## Problem Description
I was working with the example in the TWAI example section - [listen-only-mode](https://github.com/espressif/esp-idf/tree/master/examples/peripherals/twai/twai_network/twai_network_listen_only)

When i used the wrong baud rate 

`static const twai_timing_config_t t_config = TWAI_TIMING_CONFIG_25KBITS();`
The bus network gives error Bus error on attaching to my CAR .

Only at `TWAI_TIMING_CONFIG_500KBITS` the data comes. But according to theory listen-only mode must not interfere with the bus at any baud rate.

I am using the Trasnreceiver IC TJA1042 [link](https://www.nxp.com/docs/en/data-sheet/TJA1042.pdf) , The hardware side there are no errors. I checked by removing the TX (GPIO4) and the BUS error was gone from the network.

Please take a look.

**Comment by nopnop2002** [comment]
Even in the listen-only mode, if a CRC error in the received data is detected, the reception error counter (REC) will be incremented.


When the REC reaches 127, the node goes into error passive mode.




When the REC reaches 255, the node goes into bus-off mode.
