### ISSUE TITLE
esp-lwip weird ref 2e7efc4 (IDFGH-7608)

### ISSUE THREAD

**Issue by imchangchang** [espressif/esp-idf#9162]
## Environment

- Development Kit:      [none]
- Kit version (for WroverKit/PicoKit/DevKitC):
- Module or chip used: 
- IDF version (run ``git describe --tags`` to find it):
    **v5.0-dev-3485-g20f5e180ee**
- Build System:         [idf.py]
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it):
- Operating System:     [Windows]
- (Windows only) environment type: .
- Using an IDE?: [No]
- Power Supply:   

## Problem Description

Hi, I notice that the commit of the submodule 'lwip' seems like not on the espressif/esp-lwip repository. 
But it can be checked out.

```
git.exe submodule update --progress --init --recursive --force -- "components/lwip/lwip"
Cloning into 'C:/Users/imcha/Desktop/esp-idf/components/lwip/lwip'...
remote: Enumerating objects: 50277, done.
remote: Counting objects: 100% (309/309), done.
remote: Compressing objects: 100% (139/139), done.
remote: Total 50277 (delta 192), reused 255 (delta 168), pack-reused 49968
Receiving objects: 100% (50277/50277), 10.07 MiB | 11.95 MiB/s, done.
Resolving deltas: 100% (37935/37935), done.
From https://github.com/espressif/esp-lwip
* branch              2e7efc486e6d90dfe8a6f058682375870c05071f -> FETCH_HEAD
Submodule path 'components/lwip/lwip': checked out '2e7efc486e6d90dfe8a6f058682375870c05071f'
```

![image](https://user-images.githubusercontent.com/9031922/173768552-bab83985-bde0-41d6-97e7-ef459682fa2e.png)

![image](https://user-images.githubusercontent.com/9031922/173768562-acb1da76-307b-463d-bf81-aa56bf4c42c3.png)

## Question:
1. Is this meet exceptation? I mean it works but the commit not 'exist' on the espressif/esp-lwip repo. 
2. I wonder why it works OK. It would be great thanks if you can explain this to me.

**Comment by david-cermak** [comment]
Hi @imchangchang 

Thank you for reporting this problem, I forgot to post the new lwip changes to a branch, as it currently contains some `WIP` commits.
The branch has just been pushed as [2.1.3-esp-temp](https://github.com/espressif/esp-lwip/tree/2.1.3-esp-temp)

> Is this meet exceptation? I mean it works but the commit not 'exist' on the espressif/esp-lwip repo.

We're still planing on updating the branch content, but this should still be an official branch in `esp-lwip`, so this is an issue, not expected.

> I wonder why it works OK. It would be great thanks if you can explain this to me.

The commit is available in `esp-lwip` but didn't belong to any official branch. That's why it worked okay.

**Comment by imchangchang** [comment]
Thanks.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, feel free to reopen.
