### ISSUE TITLE
Wss_server example no longer accepts new connections after several reconnects (IDFGH-7609)

### ISSUE THREAD

**Issue by EN20M** [espressif/esp-idf#9163]
## Environment

- Development Kit: none
- Module or chip used:  ESP32-WROOM-32E
- IDF version: v4.4.1
- Build System: idf.py
- Compiler version: xtensa-esp32-elf-gcc (crosstool-NG esp-2021r2-patch3) 8.4.0
- Operating System: Windows
- (Windows only) environment type: Plain Command Prompt
- Using an IDE?: No
- Power Supply: external 3.3V

## Problem Description

When running the wss_server example after connecting a client, disconnecting and reconnecting it ~10 times the next reconnect fails. It seams as if every connection uses a new socket and once the default `max_clients` are reached no new connections are possible.

### Expected Behavior

1. The sockets' storage would be marked as unused after it got closed/disconnected so it can be reused.
2. Since `lru_purge_enable` is true in the example I thought the least recently used socket would be reused anyway.

### Actual Behavior

```
W (129257) httpd: httpd_accept_conn: error in accept (23)
```
indicates that all possible storage for 10 simultanious clients is used up even though no client is connected and only one tryes to connect

### Steps to reproduce

1. Run the wss_server example
2. connect a client
4. disconnet the client
5. reconnect the client
6. repet 3. and 4. untill the reconnect fails (around 10 connects in total)

I attatched an html file that I run in my browser to connect to the wss_server in the broser you can type in the IP the esp gets from your router.

### Code to reproduce this issue

wss_server example

## Debug Logs

```
...
I (115957) wss_echo_server: New client connected 62
I (115967) wss_echo_server: Handshake done, the new connection was opened
I (118987) wss_echo_server: frame len is 0
I (118997) wss_echo_server: Client disconnected 62
I (123417) wss_echo_server: New client connected 63
I (123437) wss_echo_server: Handshake done, the new connection was opened
I (125647) wss_echo_server: Active client (fd=63) -> sending async message
I (125787) wss_echo_server: frame len is 0
I (125787) wss_echo_server: Client disconnected 63
W (129257) httpd: httpd_accept_conn: error in accept (23)
W (129257) httpd: httpd_server: error accepting new connection
```

Note: I removed my credentials from the sdkconfig
[test_client.zip](https://github.com/espressif/esp-idf/files/8907526/test_client.zip)
[sdkconfig.zip](https://github.com/espressif/esp-idf/files/8907569/sdkconfig.zip)

**Comment by ESP-YJM** [comment]
@EN20M Thanks for reporting this bug. I think you can add 
`
close(sockfd);
`
in https://github.com/espressif/esp-idf/blob/master/examples/protocols/https_server/wss_server/main/wss_server_example.c#L103

**Comment by EN20M** [comment]
Thanks for this incredibly fast response. Works absolutly fine.

**Comment by ESP-YJM** [comment]
@EN20M I think enable `lru_purge_enable ` which indeed will close the least recently used one. But in userspace, we have defined close callback function and in here https://github.com/espressif/esp-idf/blob/master/components/esp_http_server/src/httpd_sess.c#L359 will call userspace close function `wss_close_fd`. And you will find no place to close this socket.
