### ISSUE TITLE
The "mdns" example build failed (IDFGH-7612)

### ISSUE THREAD

**Issue by yangwc** [espressif/esp-idf#9166]
## Environment

- Development Kit:      [ESP32-Wrover-Kit]
- Kit version (for WroverKit/PicoKit/DevKitC): [v1]
- Module or chip used:  [ESP32-WROOM-32]
- IDF version (run ``git describe --tags`` to find it):
    // ESP-IDF v4.4.1
- Build System:         [idf.py]
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it):
    // (crosstool-NG esp-2021r2-patch3) 8.4.0
- Operating System:     [Windows|]
- (Windows only) environment type: [PowerShell].
- Using an IDE?: [No]
- Power Supply:         [USB]

## Problem Description

The "mdns" example in ./example/protocols build failed.

### Expected Behavior
Build success.

### Actual Behavior
Build failed, the errors like this:
![R8M{$F_L740G32)M)G@30Q8](https://user-images.githubusercontent.com/10265618/173978302-67e47170-1a3a-4ca9-801d-f7e6136f86cb.jpg)

### Steps to reproduce

1. cd ./examples/protocols/mdns
2. idf.py build
3. Build failed

**Comment by ESP-YJM** [comment]
I think in v4.4.1 not support API `mdns_service_subtype_add_for_host` and your example version not match with your ESP-IDF version.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to short of feedback, feel free to reopen with more updates.
