### ISSUE TITLE
ESP32: A Bout CPU0 and CPU1 (IDFGH-7613)

### ISSUE THREAD

**Issue by KOOKOKOK** [espressif/esp-idf#9167]
Esp32 has two CPUs. Does one of them always detect idle things and will not handle other things, such as WiFi connection, udp/tcp, GPIO control and other tasks, or do both CPUs handle all tasks alternately

**Comment by negativekelvin** [comment]
When a task is created it has a parameter that determines if it is pinned to a core or can run on both cores.  For system tasks like WiFi and lwip you can set this in menuconfig.
