### ISSUE TITLE
The 'cpu_start' log has a line that is always garbled (IDFGH-7615)

### ISSUE THREAD

**Issue by xiaguangbo** [espressif/esp-idf#9168]
I (168) ca〞f�~���~Սѥ���cache       : size 8KB, 4Ways, cache line size 32Byte

<img width="579" alt="image" src="https://user-images.githubusercontent.com/102402151/174076229-f596c8ce-b666-4a55-89b4-6e92409cfcee.png">

**Comment by igrr** [comment]
@xiaguangbo thank you for noticing this issue. We will have the fix merged soon.
