### ISSUE TITLE
Highint Build error (IDFGH-7619)

### ISSUE THREAD

**Issue by matti122** [espressif/esp-idf#9172]
## Environment

- Development Kit:     Custom Board
- Kit version (for WroverKit/PicoKit/DevKitC): [v1|v2|v3|v4]
- Module or chip used:  ESP32-WROVER
- IDF version (run ``git describe --tags`` to find it): v5.0-dev-3424-gbb23d783c0
- Build System: Idf.py
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it):
(crosstool-NG esp-2022r1-RC1) 11.2.0
- Operating System:  Windows
- (Windows only) environment type: Plain Command Promp
- Using an IDE?: Yes (Eclipse)
- Power Supply: USB

## Problem Description

If I try to compile my project with IDF.py in command promt, I get a error message. The issue is not traceable for me.

### Steps to reproduce

My project is in a late development stage and there are a lot of dependence. I'm not able to track this issue to a Dependency.

## Debug Logs
*/esp-idf/components/esp_system/port/soc/esp32/highint_hdl.S: Assembler messages:
*/esp-idf/components/esp_system/port/soc/esp32/highint_hdl.S:384: Error: invalid symbolic operand
[232/843] Performing configure step for 'bootloader'

**Comment by igrr** [comment]
Hi @matti122, Please see https://github.com/espressif/esp-idf/issues/9160#issuecomment-1156225532. I'll close this issue as duplicate, please subscribe to the linked issue to get notified when the fix is available on Github.
