### ISSUE TITLE
rst:0x1 (POWERON_RESET),boot:0x17 (SPI_FAST_FLASH_BOOT) Happens every hour (+/- 3591861 ticks) (IDFGH-7670)

### ISSUE THREAD

**Issue by Coffeeye** [espressif/esp-idf#9218]
- [ y ] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [ y ] I have updated my IDF to ESP-IDF v4.4-4-gf0628ea2db
- [ y ] I have searched the issue tracker for a similar issue and not found correct answear for my issue.

![image](https://user-images.githubusercontent.com/83951742/175285485-98006c37-debe-4424-8fe4-6cb1804066ae.png)

I cant find an answear but exact 3 600 000 ticks with 1000 hz resolution seems suspicious. Any ideas where to look?

* Just to clarify a little, Iam using self-made custom board.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting. Would you please help provide more details as suggested in the [issue template](https://github.com/espressif/esp-idf/issues/new?assignees=&labels=&template=bug_report.md&title=)? Information like elf, sdk configuration, backtrace, log outputs, commit ID, hardware and etc. would help us debug further. Thanks.
