### ISSUE TITLE
Unable to import project (IDFGH-7675)

### ISSUE THREAD

**Issue by KOOKOKOK** [espressif/esp-idf#9220]
env: vscode + esp-idf v4.4.1

![image](https://user-images.githubusercontent.com/50746384/175331043-4127eea4-8c9e-4f09-a42f-fb7f0d534983.png)

**Comment by Alvin1Zhang** [comment]
Thanks for reporting. Would you please help provide more details as suggested in the [issue template](https://github.com/espressif/esp-idf/issues/new?assignees=&labels=&template=bug_report.md&title=)? Information like elf, sdk configuration, backtrace, log outputs, commit ID, hardware and etc. would help us debug further. Thanks.
