### ISSUE TITLE
websocket client not able to receive data after some interval  (IDFGH-7677)

### ISSUE THREAD

**Issue by vinothkrstatiq** [espressif/esp-idf#9223]
I am using Espressif-IDE Version: 2.5.0
Operating System: windows 10
Java Runtime Version: 11.0.14.1+10-LTS
Eclipse Version: 4.22.0.v20211124-1800
Eclipse CDT Version: 10.5.0.202109270023
IDF Eclipse Plugin Version: 2.5.0.202206080313
ESP-IDF v4.4-dirty
Python set for IDF_PYTHON_ENV: Python 3.8.7
Python declared in PATH variable: Python 3.10.4

I am using websocket client 
without closing the websocket connection I am trying to continuously read JSON message sent from cloud 
it is able to read the data from cloud ,but after some interval it is not able receive the data.

if I close the websocket connection and again reconnect, it is able to receive data .

without closing the websocket connection, I want to continuously read the json data which is coming from cloud.
can anyone help me here ?

**Comment by vinothkrstatiq** [comment]
@gabsuren  
hi gabsuren could you treat this issue as priority ?
our project get stuck here because of this issue .
immediate help would be highly appreciated 
Thanks in advance

**Comment by gabsuren** [comment]
@vinothkrstatiq sure, we are looking into this and will come back to you soon!

**Comment by gabsuren** [comment]
@vinothkrstatiq could you please also provide the logs, it can help us more easily to  reproduce the issue?

**Comment by vinothkrstatiq** [comment]
ets Jun  8 2016 00:22:57

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:6612
load:0x40078000,len:14780
load:0x40080400,len:3792
0x40080400: _init at ??:?

entry 0x40080694
I (27) boot: ESP-IDF v4.4-dirty 2nd stage bootloader
I (27) boot: compile time 18:03:42
I (27) boot: chip revision: 1
I (30) boot_comm: chip revision: 1, min. bootloader chip revision: 0
I (37) boot.esp32: SPI Speed      : 40MHz
I (42) boot.esp32: SPI Mode       : DIO
I (46) boot.esp32: SPI Flash Size : 4MB
I (51) boot: Enabling RNG early entropy source...
I (56) boot: Partition Table:
I (60) boot: ## Label            Usage          Type ST Offset   Length
I (67) boot:  0 nvs              WiFi data        01 02 00009000 00006000
I (74) boot:  1 phy_init         RF data          01 01 0000f000 00001000
I (82) boot:  2 factory          factory app      00 00 00010000 002f0000
I (89) boot:  3 storage          Unknown data     01 82 00300000 00100000
I (97) boot: End of partition table
I (101) boot_comm: chip revision: 1, min. application chip revision: 0
I (108) esp_image: segment 0: paddr=00010020 vaddr=3f400020 size=219dch (137692) map
I (167) esp_image: segment 1: paddr=00031a04 vaddr=3ffbdb60 size=05890h ( 22672) load
I (176) esp_image: segment 2: paddr=0003729c vaddr=40080000 size=08d7ch ( 36220) load
I (191) esp_image: segment 3: paddr=00040020 vaddr=400d0020 size=c2880h (796800) map
I (479) esp_image: segment 4: paddr=001028a8 vaddr=40088d7c size=15b5ch ( 88924) load
I (516) esp_image: segment 5: paddr=0011840c vaddr=50000000 size=00010h (    16) load
I (531) boot: Loaded app from partition at offset 0x10000
I (531) boot: Disabling RNG early entropy source...
I (543) cpu_start: Pro cpu up.
I (543) cpu_start: Starting app cpu, entry point is 0x4008131c
0x4008131c: call_start_cpu1 at C:/Espressif/frameworks/esp-idf-v4.4/components/esp_system/port/cpu_start.c:156

I (0) cpu_start: App cpu up.
I (559) cpu_start: Pro cpu start user code
I (560) cpu_start: cpu freq: 160000000
I (560) cpu_start: Application information:
I (564) cpu_start: Project name:     blemesh
I (569) cpu_start: App version:      1
I (573) cpu_start: Compile time:     Jul  6 2022 18:03:23
I (580) cpu_start: ELF file SHA256:  d263bf47420ed6fd...
I (585) cpu_start: ESP-IDF:          v4.4-dirty
I (591) heap_init: Initializing. RAM available for dynamic allocation:
I (598) heap_init: At 3FFAFF10 len 000000F0 (0 KiB): DRAM
I (604) heap_init: At 3FFB6388 len 00001C78 (7 KiB): DRAM
I (610) heap_init: At 3FFB9A20 len 00004108 (16 KiB): DRAM
I (616) heap_init: At 3FFC95B0 len 00016A50 (90 KiB): DRAM
I (622) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM
I (629) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
I (635) heap_init: At 4009E8D8 len 00001728 (5 KiB): IRAM
I (643) spi_flash: detected chip: generic
I (646) spi_flash: flash io: dio
I (651) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.
I (721) gpio: GPIO[15]| InputEn: 0| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 
I (721) wifi station: Initializing SPIFFS
I (851) wifi station: Partition size: total: 956561, used: 1004
I (851) wifi station: Reading file
I (851) wifi station: Read from file: 'Tree'
data Tree
I (851) wifi station: Reading file
I (861) wifi station: Read from file: 'qqqqqqqq'
data qqqqqqqq
....................................ssid stored  Tree
password stored  qqqqqqqq
I (1371) BTDM_INIT: BT controller compile version [6a07b06]
I (1371) system_api: Base MAC address is not set
I (1371) system_api: read default base MAC address from EFUSE
I (1381) phy_init: phy_version 4670,719f9f6,Feb 18 2021,17:07:07
I (1751) NimBLE: GAP procedure initiated: advertise; 
I (1751) NimBLE: disc_mode=2
I (1751) NimBLE:  adv_channel_map=0 own_addr_type=0 adv_filter_policy=0 adv_itvl_min=0 adv_itvl_max=0
I (1761) NimBLE: 

I (2211) wifi station: Initializing SPIFFS
E (2211) wifi station: Failed to initialize SPIFFS (ESP_ERR_INVALID_STATE)
ssid stored  Tree
password stored  qqqqqqqq
I (2721) wifi:wifi driver task: 3ffd46c4, prio:23, stack:6656, core=0
I (2731) wifi:wifi firmware version: 7679c42
I (2731) wifi:wifi certification version: v7.0
I (2731) wifi:config NVS flash: enabled
I (2731) wifi:config nano formating: disabled
I (2741) wifi:Init data frame dynamic rx buffer num: 32
I (2741) wifi:Init management frame dynamic rx buffer num: 32
I (2751) wifi:Init management short buffer num: 32
I (2751) wifi:Init dynamic tx buffer num: 32
I (2761) wifi:Init static rx buffer size: 1600
I (2761) wifi:Init static rx buffer num: 10
I (2761) wifi:Init dynamic rx buffer num: 32
I (2771) wifi_init: rx ba win: 6
I (2771) wifi_init: tcpip mbox: 32
I (2771) wifi_init: udp mbox: 6
I (2781) wifi_init: tcp mbox: 6
I (2781) wifi_init: tcp tx win: 5744
I (2791) wifi_init: tcp rx win: 5744
I (2791) wifi_init: tcp mss: 1440
I (2801) wifi_init: WiFi IRAM OP enabled
I (2801) wifi_init: WiFi RX IRAM OP enabled
I (2811) wifi:mode : sta (7c:9e:bd:f4:ce:08)
I (2811) wifi:enable tsf
I (2811) wifi station: wifi_init_sta finished.
I (2821) wifi:new:<11,0>, old:<1,0>, ap:<255,255>, sta:<11,0>, prof:1
I (2821) wifi:state: init -> auth (b0)
I (2831) wifi:state: auth -> assoc (0)
I (2851) wifi:state: assoc -> run (10)
I (2931) wifi:connected with Tree, aid = 7, channel 11, BW20, bssid = c2:ea:f7:10:8b:19
I (2931) wifi:security: WPA2-PSK, phy: bgn, rssi: -52
I (2931) wifi:pm start, type: 1

I (2981) wifi:AP's beacon interval = 102400 us, DTIM period = 2
I (3711) esp_netif_handlers: sta ip: 192.168.158.161, mask: 255.255.255.0, gw: 192.168.158.97
I (3711) wifi station: got ip:192.168.158.161
I (3711) wifi station: connected to ap SSID:Tree password:qqqqqqqq
I (3721) wifi station: Time is not set yet. Connecting to WiFi and getting time over NTP.
I (3731) wifi station: Initializing SNTP
I (3731) wifi station: Waiting for system time to be set... (1/10)
W (4221) wifi:<ba-add>idx:0 (ifx:0, c2:ea:f7:10:8b:19), tid:0, ssn:3, winSize:64
I (4521) wifi station: Notification of a time synchronization event
I (6241) wifi station: Connecting to ws://sitmicro.statiq.in:80/circleesp3...
I (6241) wifi station: CLIENT CONNECTING.....
I (6481) wifi station: WEBSOCKET_EVENT_CONNECTED
I (7241) wifi station: CLIENT CONNECTING.....
I (7241) wifi station: CLIENT CONNECTED
I (7241) wifi station: The current date/time in Delhi is: Wed Jul  6 18:18:33 2022
current date and time is = Wed Jul  6 18:18:33 2022
Could not open file /spiffs/mode.txt
idtag_size =0 meterstart_size = 0 start_timestamp_size =0
Could not open file /spiffs/idtag.txt
Could not open file /spiffs/idtag.txt
Could not open file /spiffs/idtag.txt
idtag total line =0 meterstart total line = 0  total start_timestamp_line =0
meterstop_size =0 stop_timestamp_size = 0
Could not open file /spiffs/meterstop.txt
Could not open file /spiffs/stop_timestamp.txt
meterstop total line =0 stop_timestamp total line = 0
Could not open file /spiffs/transaction_id.txt
transaction id size = 0 transaction id total line = 0
after data adjustment
meterstop total line =0 stop_timestamp total line = 0
All offline data
total_line_mode1 = 0
total_line_mode2 = 0
Offline transactions not available
Send offline transactions completed
idtag_size =0 meterstart_size = 0 start_timestamp_size =0
meterstop_size =0 stop_timestamp_size = 0
file not available = /spiffs/idtag.txt
file not available = /spiffs/meterstart.txt
file not available = /spiffs/start_timestamp.txt
file not available = /spiffs/meterstop.txt
file not available = /spiffs/stop_timestamp.txt
file not available = /spiffs/transaction_id.txt
file not available = /spiffs/mode.txt
Serialize.....I (12141) wifi station: my_json_string
[2, "531531531", "BootNotification", {
                "chargePointModel":     "smartplug",
                "chargePointVendor":    "statiq"
        }]
 sending boot notification
 rec boot notification
 rec boot notification
 rec boot notification
 rec boot notification
 rec boot notification
W (12811) wifi station: Received=[3,"531531531",{"currentTime":"2022-07-06T12:48:39.040040","interval":20,"status":"Accepted"}]

variable stored data = [3,"531531531",{"currentTime":"2022-07-06T12:48:39.040040","interval":20,"status":"Accepted"}]
 rec boot notification [3,"531531531",{"currentTime":"2022-07-06T12:48:39.040040","interval":20,"status":"Accepted"}]
 id 3
 bootnotification status Accepted
  boot notification received
I (12851) wifi station: The current date/time in Delhi is: Wed Jul  6 18:18:39 2022
sending status notification
I (12861) wifi station: Serialize.....
I (12871) wifi station: my_json_string
[2, "531531532", "StatusNotification", {
                "connectorId":  1,
                "errorCode":    "NoError",
                "status":       "Available",
                "info": "230.00",
                "timestamp":    "Wed Jul  6 18:18:39 2022"
        }]
receiving status notification

 a1 value 0
W (13141) wifi station: Received=[3,"531531532",{}]

variable stored data = [3,"531531532",{}]
receiving status notification
[3,"531531532",{}]
sn id 3
 sn rec number 531531532
 a1 value 3
  sn notification received
sending heartbeat
Serialize.....I (13421) wifi station: my_json_string
[2, "531531533", "Heartbeat", {
        }]
 sending boot notification
 rec heartbeat data
 rec heartbeat
W (13631) wifi station: Received=[3,"531531533",{"currentTime":"2022-07-06T12:48:39.973407"}]

variable stored data = [3,"531531533",{"currentTime":"2022-07-06T12:48:39.973407"}]
 rec heartbeat data [3,"531531533",{"currentTime":"2022-07-06T12:48:39.973407"}]
 rec heartbeat
 HBnumber 3
currentTime 2022-07-06T12:48:39.973407
  heartbeat received
waiting for  RemoteStartTransaction

waiting for  RemoteStartTransaction

waiting for  RemoteStartTransaction

waiting for  RemoteStartTransaction

waiting for  RemoteStartTransaction

waiting for  RemoteStartTransaction

waiting for  RemoteStartTransaction

waiting for  RemoteStartTransaction

waiting for  RemoteStartTransaction

waiting for  RemoteStartTransaction

waiting for  RemoteStartTransaction

waiting for  RemoteStartTransaction

waiting for  RemoteStartTransaction

waiting for  RemoteStartTransaction

waiting for  RemoteStartTransaction

waiting for  RemoteStartTransaction

waiting for  RemoteStartTransaction

waiting for  RemoteStartTransaction

waiting for  RemoteStartTransaction

waiting for  RemoteStartTransaction

W (19881) wifi station: Received=[2,"19f56fcd-34bd-4c77-8fbb-1df4c40b2116","RemoteStartTransaction",{"idTag":"c17747","connectorId":1}]

variable stored data = [2,"19f56fcd-34bd-4c77-8fbb-1df4c40b2116","RemoteStartTransaction",{"idTag":"c17747","connectorId":1}]
waiting for  RemoteStartTransaction
[2,"19f56fcd-34bd-4c77-8fbb-1df4c40b2116","RemoteStartTransaction",{"idTag":"c17747","connectorId":1}]
 id RemoteStartTransaction
 RemoteStartTransaction idtag c17747
 RemoteStartTransaction ConnectorId 1
  RemoteStartTransaction received
sending RemoteStartTransaction accepted
I (20141) wifi station: The current date/time in Delhi is: Wed Jul  6 18:18:46 2022
sending StartTransaction
Serialize.....I (20141) wifi station: my_json_string
[2, "531531534", "StartTransaction", {
                "connectorId":  1,
                "meterStart":   93,
                "timestamp":    "Wed Jul  6 18:18:46 2022",
                "idTag":        "c17747"
        }]
Opening file
File written
Opening file
W (20391) wifi station: Received=[3,"531531534",{"transactionId":10002834,"idTagInfo":{"status":"Accepted"}}]

variable stored data = [3,"531531534",{"transactionId":10002834,"idTagInfo":{"status":"Accepted"}}]
File written
waiting for  StartTransaction Accepted by central system
[3,"531531534",{"transactionId":10002834,"idTagInfo":{"status":"Accepted"}}]
 id 10002834
 id Accepted
  StartTransaction Accepted
Opening file
File written
Opening file
File written
file not available = /spiffs/idtag.txt
file not available = /spiffs/meterstart.txt
file not available = /spiffs/start_timestamp.txt
sending status notification 2
sending status notification
I (21121) wifi station: The current date/time in Delhi is: Wed Jul  6 18:18:47 2022
sending status notification
I (21131) wifi station: Serialize.....
I (21131) wifi station: my_json_string
[2, "531531532", "StatusNotification", {
                "connectorId":  1,
                "errorCode":    "NoError",
                "status":       "Charging",
                "info": "230.00",
                "timestamp":    "Wed Jul  6 18:18:47 2022"
        }]
receiving status notification

W (21431) wifi station: Received=[3,"531531532",{}]

variable stored data = [3,"531531532",{}]
receiving status notification
[3,"531531532",{}]
sn id 3
 sn rec number 531531532
  status notification2 received
I (21661) wifi station: The current date/time in Delhi is: Wed Jul  6 18:18:47 2022
sending meter values
I (21661) wifi station: Serialize.....
I (21661) wifi station: my_json_string
[2, "531531538", "MeterValues", {
                "connectorId":  1,
                "meterValue":   [{
                                "timestamp":    "Wed Jul  6 18:18:47 2022",
                                "sampledValue": [{
                                                "context":      "Sample.Periodic",
                                                "location":     "Outlet",
                                                "measurand":    "Energy.Active.Import.Register",
                                                "unit": "Wh",
                                                "value":        "140.09"
                                        }, {
                                                "context":      "Sample.Periodic",
                                                "location":     "Outlet",
                                                "measurand":    "Energy.Active.Import.Register",
                                                "unit": "Wh",
                                                "value":        "140.09"
                                        }, {
                                                "context":      "Sample.Periodic",
                                                "location":     "Outlet",
                                                "measurand":    "Energy.Active.Import.Register",
                                                "unit": "Wh",
                                                "value":        "140.09"
                                        }]
                        }],
                "transactionId":        10002834
        }]
waiting for  metervalue rec
 data
W (22021) wifi station: Received=[3,"531531538",{}]

variable stored data = [3,"531531538",{}]
waiting for  metervalue rec
 data [3,"531531538",{}]
a2 value 3
 sn rec number 531531538
  metre values  received
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
W (32261) wifi station: Received=

variable stored data =
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data
waiting for  RemoteStopTransaction
 data

**Comment by vinothkrstatiq** [comment]
@gabsuren 
from above log after waiting for RemoteStopTransaction
I suppose to receive JSON data 
I highlighted that in bold above, but it is showing nothing 
**W (32261) wifi station: Received=
variable stored data =**

in Arduino same project working fine
in ESP-IDF this problem happening ?
I am continually sending and receiving JSON message from WebSocket

**Comment by vinothkrstatiq** [comment]
@gabsuren 
i would suggest you to try send and receive JSON data in websocket client. keep it in infinite loop and check after some interval weather we are able to receive any data from cloud.
example JSON data :
["abc", 123, true, false, null, {
                "version":      "v5.0-dev-3202-ga2d5041492-dirty",
                "cores":        2
        }]

**Comment by gabsuren** [comment]
@vinothkrstatiq thank you for the attached info. 
I tried to use internal [esp_websocket_client/examples](https://github.com/espressif/esp-protocols/tree/master/components/esp_websocket_client/examples) as client and [ws_echo_server](https://github.com/espressif/esp-idf/tree/master/examples/protocols/http_server/ws_echo_server) as server, I tried to run it for an hour but connection wasn't drop during that time. 
In order test it you need to configure _esp_websocket_client_  to use _ws_echo_server_ server, please run both of them in separate boards and set 

> CONFIG_WEBSOCKET_URI_FROM_STRING = ws://IP_address_of_esp_board:80/ws

One of my guess it can be related with cloud server, as it drops the connection if there is no data for some time and server waits PONG data when it sends PING request, similar to https://github.com/espressif/esp-idf/issues/8557

You can try the solution which user described, make _esp_websocket_client_send_with_opcode_ public and send PONG message when there is PING, meanwhile we are adding new API to have it public.

If both of suggestions didn't work or you have any questions please let us know.

Thank you

**Comment by vinothkrstatiq** [comment]
@gabsuren ,

Thanks for detailed explanation 
as you mentioned problem was from server side 
I found the solution
highly appreciated for your immidiate help

**Comment by hitecSmartHome** [comment]
I'm experiencing a similar issue. 
Websocket client just stops.
Sometimes it is after half a day sometimes it is after 5 days!
The rest of the app is working fine but the websocket does not receive any data.
