### ISSUE TITLE
FRIENDSHIP AND LPN Implementation in ESP-BLE-MESH (IDFGH-7680)

### ISSUE THREAD

**Issue by sriha99** [espressif/esp-idf#9226]
Hi,

I am trying to see if I can implement the friendship and lpn feature in esp ble mesh. Can someone guide me on how to implement this feature and how I can test it? If someone can get me started with the procedure, it would be really great. Thanks

**Comment by JiaLWang** [comment]
Hi @sriha99,
please refer to https://docs.espressif.com/projects/esp-idf/zh_CN/latest/esp32/api-reference/bluetooth/esp-ble-mesh.html

In addition, Friend feature and Low Power feature in menuconfig need to be opened separately.

Hope it can help you.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, feel free to reopen.
