### ISSUE TITLE
build fails for example i2c_simple (IDFGH-7688)

### ISSUE THREAD

**Issue by AirWind001** [espressif/esp-idf#9232]
## Environment

- Development Kit:      ESP32-Wrover-Kit
- Kit version v2
- Module or chip used:  ESP32-WROOM-32
- IDF version v4.3.2
- Build System:         idf.py
- Compiler version  8.4.0
- Operating System:     Windows
- (Windows only) environment type: ESP Command Prompt
- Using an IDE?: No
- Power Supply:   USB

## Problem Description

When running the "idf.py build" command, it gives the following error:

../main/i2c_simple_main.c: In function 'mpu9250_register_read':
../main/i2c_simple_main.c:44:12: error: implicit declaration of function 'i2c_master_write_read_device'; did you mean 'i2c_master_write_byte'? [-Werror=implicit-function-declaration]
     return i2c_master_write_read_device(I2C_MASTER_NUM, MPU9250_SENSOR_ADDR, &reg_addr, 1, data, len, I2C_MASTER_TIMEOUT_MS / portTICK_PERIOD_MS);
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
            i2c_master_write_byte
../main/i2c_simple_main.c: In function 'mpu9250_register_write_byte':
../main/i2c_simple_main.c:55:11: error: implicit declaration of function 'i2c_master_write_to_device'; did you mean 'i2c_master_write_byte'? [-Werror=implicit-function-declaration]
     ret = i2c_master_write_to_device(I2C_MASTER_NUM, MPU9250_SENSOR_ADDR, write_buf, sizeof(write_buf), I2C_MASTER_TIMEOUT_MS / portTICK_PERIOD_MS);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~
           i2c_master_write_byte
cc1.exe: some warnings being treated as errors

## Debug Logs
[build log i2c_simple.txt](https://github.com/espressif/esp-idf/files/8984947/build.log.i2c_simple.txt)

complete console logs are attached in a file.

Any idea on how to fix this would be helpful.

**Comment by nopnop2002** [comment]
Something is wrong with the version of esp-idf.

>IDF version v4.3.2

In build.log.i2c_simple.txt

>-- App "i2c-simple" version: v5.0-dev-3654-gc2ccc383da

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, feel free to reopen.
