### ISSUE TITLE
ESP32-S3: `assert sch_arb.c 890, param 00000000 00000000` when using `ble_mesh_wifi_coexist` (IDFGH-7694)

### ISSUE THREAD

**Issue by mrninhvn** [espressif/esp-idf#9238]
## Environment

- Development Kit:      [none]
- Module or chip used:  [ESP32-S3-WROOM-1]
- IDF version (run ``git describe --tags`` to find it): v4.4.1
- Build System:         [idf.py]
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it): 8.4.0
- Operating System:     [Linux]
- Using an IDE?: [No]
- Power Supply:         [USB]

## Problem Description
`assert sch_arb.c 890, param 00000000 00000000` when using `ble_mesh_wifi_coexist`.

### Steps to reproduce

Using `ble_mesh_wifi_coexist` example.

**Comment by JiaLWang** [comment]
Hi @mrninhvn ，

Could you please provide the detailed error log?
And steps to reproduce it.

**Comment by mrninhvn** [comment]
> 



> Hi @mrninhvn ，
> 
> Could you please provide the detailed error log? And steps to reproduce it.

I'm using `[ble_mesh_wifi_coexist](https://github.com/espressif/esp-idf/tree/master/examples/bluetooth/esp_ble_mesh/ble_mesh_wifi_coexist)` example with ESP32-S3-WROOM-1, I didn't edit anything, just changed the target, the above error appeared randomly.

**Comment by Cleidiana** [comment]
I have the same problem.

**Comment by JiaLWang** [comment]
Thanks for your information.
We have located the problem, and we will fix and update it ASAP.

**Comment by Weijian-Espressif** [comment]
[esp32s3_lib.zip](https://github.com/espressif/esp-idf/files/9089321/esp32s3_lib.zip)
Please test the attached S3 lib and provide the log file if you still have problems.

**Comment by Weijian-Espressif** [comment]
@mrninhvn @Cleidiana

**Comment by mrninhvn** [comment]
Thank you @Weijian-Espressif.
Can you tell me where to use this file?

**Comment by mrninhvn** [comment]
Thank you @Weijian-Espressif, It's ok now (y)

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, sorry for slow turnaround, fix on release/4.4 is available at https://github.com/espressif/esp-idf/commit/41839b69bda176cc29a2467b8d759f53cc31f77a, feel free to reopen.
