### ISSUE TITLE
is httpd_ws_send_frame() sync or async ? (IDFGH-7708)

### ISSUE THREAD

**Issue by hyansuper** [espressif/esp-idf#9250]
I was reading the [websocket server example](https://github.com/espressif/esp-idf/blob/master/examples/protocols/http_server/ws_echo_server/main/ws_echo_server.c), 
then I notice that function [httpd_ws_send_frame](https://github.com/espressif/esp-idf/blob/master/components/esp_http_server/src/httpd_ws.c#L366) calls function httpd_ws_send_frame_async(), so they are both either synchronous or asynchronous, right? and I read through the body of [httpd_ws_send_frame_async()](https://github.com/espressif/esp-idf/blob/master/components/esp_http_server/src/httpd_ws.c#L375), it looks like it's not async.

I just want to confirm that when httpd_ws_send_frame(..., frame) returns ESP_OK, does it mean the package is sent already so I can safely delete/change frame->payload? or it's not already sent but waiting in a message queue or something (thus "async")

This is probably not a bug but the function name is confusing. sorry if I post it in the wrong place.

**Comment by chipweinberger** [comment]
In my code, I treat it as "having already been sent" and change the payload. It seems to work.

I'm not sure whats going on under the hood.
