### ISSUE TITLE
Could not allocate DHCP request (IDFGH-7715)

### ISSUE THREAD

**Issue by helaagardabbou** [espressif/esp-idf#9257]
I have a problem with the mesh level: in fact I have two devices (one as  root and the other as node),  at the beginning
when I open the access point everything was fine and the mesh network was established and each device
obtained an ip address, However, after turning OFF the AP, I pressed the reset button of the node device so the node couldn't have an IP address even after opening the AP, So here I have a root (THE DHCP server) with an IP address and a node without IP address displaying
this message on the pc terminal side: "dhcp_select: could not allocate DHCP request". 
PS: when I press on the reset button of the root the problem is solved(The node is able to have an IP address)

**Comment by shenjun7** [comment]
Closed by https://github.com/espressif/esp-idf/issues/9282.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, feel free to reopen.
