### ISSUE TITLE
I am not able to build the simple blink example!  (IDFGH-7717)

### ISSUE THREAD

**Issue by ASabovic** [espressif/esp-idf#9258]
Hello,

I just installed and set up esp-idf in VS Code on Windows. I followed the tutorial on your website but when I tried to build the example I faces this issue: 
-- Configuring incomplete, errors occurred!
See also "C:/xyz/xyz/esp/esp-idf/examples/get-started/blink/build/CMakeFiles/CMakeOutput.log".
cmake failed with exit code 1

Does anyone know how to fix it and enable my device to work?

**Comment by ASabovic** [comment]
I checked it, but it's quite large so it's hard to say, but it collapsed with dir related to GCC. I created the example from scratch and located it in the folder on my Desktop if you meant that but the story is the same.

**Comment by chegewara** [comment]
No. I meant the whole esp-idf, because there is many subfolders and some files eventually my exceed windows path length. Thats why it is sugested to install esp-idf in top/root folder on disk.

**Comment by ASabovic** [comment]
I understand you but my top/root folder is this one: "C:\Users\User1\..." and here the esp-idf folder is saved. Should I remove it and save in "C:\" if this is what you meant?

**Comment by ASabovic** [comment]
I cloned the master branch from git and now I am facing another issue:

Executing task: C:\User\User1\.espressif\python_env\idf5.0_py3.8_env\Scripts\python.exe C:\User\User1\esp\esp-idf\tools\idf_size.py c:\User\User1\esp\esp-idf\examples\get-started\blink\build\blink.map <

C:\User\User1: The term 'C:\User\User1' is not recognized as the name of a cmdlet, 
function, script file, or operable program. Check the spelling of the name, or if a path was    
included, verify that the path is correct and try again.
At line:1 char:1
+ C:\User\User1\.espressif\python_env\idf5.0_py3.8_env\Scripts\p ...
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\IDLab:String) [], CommandNotFoundExcep  
   tion
    + FullyQualifiedErrorId : CommandNotFoundException
 
The terminal process "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -Command C:\User\User1\.espressif\python_env\idf5.0_py3.8_env\Scripts\python.exe C:\User\User1\esp\esp-idf\tools\idf_size.py c:\User\User1\esp\esp-idf\examples\get-started\blink\build\blink.map" terminated with exit code: 1.

**Comment by brianignacio5** [comment]
Could be related to spaces in the `.espressif` directory when executing the idf_size task.

Please take a look at the troubleshooting information
https://github.com/espressif/vscode-esp-idf-extension#troubleshooting

**Comment by brianignacio5** [comment]
Could you share the troubleshooting information ? It would help us to understand your setup and what is happening

**Comment by moefear85** [comment]
how are you installing? through the esp-idf vscode extension, through an installer, or manually at the command line? either way the problem isn't a general one, meaning there is something specific to your setup that is making it fail, so more details are needed. are you sure the setup process completed successfully, and that all tool dependencies were installed?

**Comment by ASabovic** [comment]
I installed it through the ESP-IDF VS Code extension on my Windows. After the extension was installed, I chose EXPRESS option to install all the necessary dependencies, which resulted successfully in the end. After that, I just chose the simple example (Hello World), selected device and port, and tried to build it. This is the result from that command: 

`> Executing task: cmake -G Ninja -DPYTHON_DEPS_CHECKED=1 -DESP_PLATFORM=1 .. <

-- Found Git: C:/Users/Adnan Sabovic/.espressif/tools/idf-git/2.30.1/cmd/git.exe (found version "2.30.1.windows.1") .1")
-- The C compiler identification is GNU 8.4.0
-- The CXX compiler identification is GNU 8.4.0
-- The ASM compiler identification is GNU
-- Found assembler: C:/Users/Adnan Sabovic/.espressif/tools/xtensa-esp32-elf/esp-2021r2-patch3-8.4.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc.exe
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Users/Adnan Sabovic/.espressif/tools/xtensa-esp32-elf/esp-2021r2-patch3-8.4.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Users/Adnan Sabovic/.espressif/tools/xtensa-esp32-elf/esp-2021r2-patch3-8.4.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-g++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Project is not inside a git repository, or git repository has no commits; will not use 'git describe' to determine PROJECT_VER.
-- Building ESP-IDF components for target esp32
-- Project sdkconfig file C:/Users/Adnan Sabovic/Desktop/esp-hello/hello_world/sdkconfig
Traceback (most recent call last):
  File "C:/Users/Adnan Sabovic/esp/esp-idf/tools/kconfig_new/confgen.py", line 640, in <module>
    main()
  File "C:/Users/Adnan Sabovic/esp/esp-idf/tools/kconfig_new/confgen.py", line 260, in main
    config = kconfiglib.Kconfig(args.kconfig)
  File "C:\Users\Adnan Sabovic\.espressif\python_env\idf4.4_py3.8_env\lib\site-packages\kconfiglib.py", line 947, in __init__
    self._init(filename, warn, warn_to_stderr, encoding)
  File "C:\Users\Adnan Sabovic\.espressif\python_env\idf4.4_py3.8_env\lib\site-packages\kconfiglib.py", line 1085, in _init
    self._parse_block(None, self.top_node, self.top_node).next = None
  File "C:\Users\Adnan Sabovic\.espressif\python_env\idf4.4_py3.8_env\lib\site-packages\kconfiglib.py", line 2982, in _parse_block
    prev = self._parse_block(None, parent, prev)
  File "C:\Users\Adnan Sabovic\.espressif\python_env\idf4.4_py3.8_env\lib\site-packages\kconfiglib.py", line 2970, in _parse_block
    raise KconfigError(
kconfiglib.KconfigError: C:/Users/Adnan Sabovic/Desktop/esp-hello/hello_world/build/kconfigs_projbuild.in:1: 'C:/Users/Adnan' not found (in 'source "C:/Users/Adnan"'). Check that environment variables are set correctly (e.g. $srctree, which is unset or blank). Also note that unset environment variables expand to the empty string.  
CMake Error at C:/Users/Adnan Sabovic/esp/esp-idf/tools/cmake/kconfig.cmake:266 (message):
  Failed to run confgen.py (C:/Users/Adnan
  Sabovic/.espressif/python_env/idf4.4_py3.8_env/Scripts/python.exe;C:/Users/Adnan
  Sabovic/esp/esp-idf/tools/kconfig_new/confgen.py;--kconfig;C:/Users/Adnan
  Sabovic/esp/esp-idf/Kconfig;--sdkconfig-rename;C:/Users/Adnan
  Sabovic/esp/esp-idf/sdkconfig.rename;--config;C:/Users/Adnan
  Sabovic/Desktop/esp-hello/hello_world/sdkconfig;--env-file;C:/Users/Adnan
  Sabovic/Desktop/esp-hello/hello_world/build/config.env).  Error 1
Call Stack (most recent call first):
  C:/Users/Adnan Sabovic/esp/esp-idf/tools/cmake/build.cmake:528 (__kconfig_generate_config)
  C:/Users/Adnan Sabovic/esp/esp-idf/tools/cmake/project.cmake:378 (idf_build_process)
  CMakeLists.txt:6 (project)


-- Configuring incomplete, errors occurred!
See also "C:/Users/Adnan Sabovic/Desktop/esp-hello/hello_world/build/CMakeFiles/CMakeOutput.log".
The terminal process "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -Command cmake -G Ninja -DPYTHON_DEPS_CHECKED=1 -DESP_PLATFORM=1 .." terminated with exit code: 1.
`

**Comment by igrr** [comment]
>  C:/Users/Adnan Sabovic/Desktop/esp-hello/hello_world

Please note that ESP-IDF v4.4 and below [do not support spaces in path](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/get-started/windows-setup.html#start-a-project) to the project or to ESP-IDF. Seems like your project is in a directory with a space in the name.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, feel free to reopen with more updates. Thanks.
