### ISSUE TITLE
How to integrate two ESP-IDF projects? (IDFGH-7730)

### ISSUE THREAD

**Issue by francis2tm** [espressif/esp-idf#9270]
## Environment
- IDF version v4.3.3
- Build System: CMake

## Problem Description

Hello,
I have two projects: project1 and project2. Each is a normal esp-idf project with a folder `main`. However, I want to include project2 as a git submodule of project1. In ESP-IDF terms, I want project2 to become a *component* of project1. I've come up with this structure:
```
project1
    - main
    - components
        - project2
            - project2
                - main
                   - adc.c
                   - adc.h
                   - project2.c
                   - project2.h
                   - main.c (it has app_main())
                   - CMakeLists.txt
            - CMakeLists.txt

```
And then on `components/project2/CMakeLists.txt`:
```
include("project2/main/CMakeLists.txt")
```

Currently, I'm facing two errors:

### Error 1)
```
include could not find requested file:
      project2/main/CMakeLists.txt
```
And as a workaround, I manually included all source files (except the one that has app_main()) of project2:

```
idf_component_register(SRCS "project2/main/project2.c" "project2/main/adc.c"
                    INCLUDE_DIRS "project2/main/")
```

But, this is leads to error 2):

### Error 2)
```
fatal error: nvs.h: No such file or directory
 #include "nvs.h"
```
Meaning that the required ESP-IDF components of project2 are not being linked. This is probably because I didn't put the `REQUIRE` varaiable in the component registration in `components/project2/CMakeLists.txt`. But project2 is actually mega big and it has a tone of ESP-IDF component dependencies and I'd like that the dependencies would be done automatically, just like if they were in project1/main.

In fact, that's what I want. To make the ESP-IDF building system behave like if the sources of project2 were inside project1/main. But, I don't want to copy paste because I want to maintain the modularity that git submodules offer, since project2 is a completely independent standalone project.

How can I achieve this?

Thanks

**Comment by o-marshmallow** [comment]
Hi @francis2tm ,

You guessed right, you will need to add the dependencies in `project2`'s `CMakeLists.txt` file. Dependencies are not automatically imported, even for the `main` project (project1 in your case). What happens is the base components, such as `soc`, or `esp32*`, are always included, if these also depend on another component, they will also be imported, and so on.

Thus, if `project1`/`main` depends on a component that is also a dependency of a base component, you don't need to specify it again, it's transaprent.

This also means that for `project2`, you may not need to explicitely specify **all** the required components. Start by adding `REQUIRES nvs_flash` and see if it's enough, if not, add them one by one.
