### ISSUE TITLE
ESP32S2 特定条件下固件升级会使得nvs读取不到数据 (IDFGH-7738)

### ISSUE THREAD

**Issue by fzboffice** [espressif/esp-idf#9280]
idf commit :6c5fb29c2c513936ecefa7cdf49fb324e316546e
当老固件menuconfig中 flash mode是dio 升级到新的固件 menuconfig flash mode是qio 新的固件将读取不到任何老固件写入nvs的数据，但可以读取到新固件自己写入nvs的数据 同时 如果发生版本回滚 原来的nvs数据还在，从qio升级到dio无影响。
同样的操作在esp32上不会发生任何错误。

**Comment by igrr** [comment]
I'm sorry we did not reply to this issue in time. It is not supported to change the flash mode (DIO to QIO) via an OTA update, which is the cause of the problem here.
