### ISSUE TITLE
Node device could not get IP address from Root when closing The Access Point (IDFGH-7741)

### ISSUE THREAD

**Issue by helaagardabbou** [espressif/esp-idf#9282]
## Environment

- Development Kit:      ESP32-C3-DevKitM-1
- IDF version:  framework-espidf @ 3.40302.0 (4.3.2)
- Build System:         [Make|CMake|idf.py]
- Compiler version : xtensa-esp32s2 @ 8.4.0+2021r2-patch2
- Operating System:     Windows
- Environment type: MSYS2 mingw32
- Using an IDE: Platformio on VS code
- Power Supply:         USB

## Problem Description

Using The source code of Mesh IP Internal Networking example  the Node device in Mesh network couldn't get IP address from the root (DHCP server) after closing the Access point.

### Expected Behavior
After closing the AP and press the reset button of the Node device, The root which is the DHCP server forward an IP address to the Node.

### Actual Behavior
The node couldn't have an IP address even after opening the AP and this message on the pc terminal side of The node is diplayed : "dhcp_select: could not allocate DHCP request".

### Steps to reproduce

1. Power up  two dev kits 
2. Open an Acess point
3. Mesh network established and each device obtained an IP address 5 one device is elected as node and the other one as node)
4. Turn OFF the AP
5. Press the Reset button of the NODE device
### Code to reproduce this issue

https://github.com/espressif/esp-idf/blob/master/examples/mesh/ip_internal_network/main/mesh_main.c

Ps:  When we comment these lines in the source code below the problem is solved:
![image](https://user-images.githubusercontent.com/61280527/177164884-62b70fcb-6cf3-4c96-b954-62c65d8d14e5.png)

## Debug Logs
![image](https://user-images.githubusercontent.com/61280527/177163492-ea87792e-2541-49b5-93db-0a41694d4740.png)
```

**Comment by shenjun7** [comment]
We will describe this situation in the documentation. Thank you for your contribution.

**Comment by helaagardabbou** [comment]
I found the solution, when The AP is closed, we must stop the DHCP server on root node  using **esp_netif_dhcps_stop** function and start it when the AP reported

**Comment by helaagardabbou** [comment]
I found the solution, when The AP is closed, we must stop the DHCP server on root node using esp_netif_dhcps_stop function and start it when the AP reported
