### ISSUE TITLE
Phy is not calibrating as often as it should (IDFGH-7743)

### ISSUE THREAD

**Issue by floitsch** [espressif/esp-idf#9284]
## Environment

- Development Kit:     ESP32-DevKitC
- Kit version (for WroverKit/PicoKit/DevKitC): v4
- Module or chip used:  ESP32-WROOM-32
- IDF version (run ``git describe --tags`` to find it): patched v4.4 (but verified on master).
- Build System:         Make
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it): xtensa-esp32-elf-gcc (crosstool-NG esp-2021r2-patch3) 8.4.0
- Operating System:    Linux
- Using an IDE?: No
- Power Supply:         USB

## Problem Description

The `register_chipv7_phy` call in `phy_init.c` may be called with `PHY_RF_CAL_NONE` even though it should use `PHY_RF_CAL_PARTIAL`.

The code in `phy_init.c` only checks if the current reset reason was deep sleep. However, that doesn't guarantee that the stored calibration data is recent. There could have been many power downs since the last calibration.

See https://github.com/espressif/esp-idf/blob/c2ccc383dae2a47c2c2dc8c7ad78175a3fd11361/components/esp_phy/src/phy_init.c#L715-L719

### Expected Behavior

`register_chipv7_phy` is called with `PHY_RF_CAL_PARTIAL` if the device was completely powered down since the last initialization.

### Actual Behavior

`register_chipv7_phy` is called with `PHY_RF_CAL_NONE` if the device was woken from deep sleep. However, it does *not* verify that the calibration was from a previous deep-sleep run.

### Steps to reproduce

1. Write a program that connects to the network when pin 32 is high. (Pin number is arbitrary).
2. Set pin 32 to high. The network connects.
3. Disconnect the board from power.
4. Connect pin 32 to GND.
5. Connect the board to power.
6. Go to sleep.
7. Connect pin 32 to 3V3.
8. Wake up from sleep
9. The `registery_chipv7_phy` is called with `PHY_RF_CAL_NONE`, even though the board was completely disconnected.

### Code to reproduce this issue

Only did it in Toit:
```toit
import esp32
import gpio
import net

main:
  pin := gpio.Pin 32 --input

  if pin.get == 1:
    print "opening network"
    net.open 
 
  esp32.deep_sleep (Duration --s=3)
```

**Comment by moefear85** [comment]
If you connect the board to power at step 5 before going to sleep at step 6, then I think the chip will already perform a full calibration at step 5. So since step 8 is the first wake up after the first sleep at step 6, then the chip according to my knowledge is behaving exactly according to the documentation, in that it doesn't recalibrate after a deep sleep (which is the only one that occured in this case after power-on).

**Comment by floitsch** [comment]
From what I can see, step 5 would only do a calibration if I use WiFi (or Bluetooth). Since calibration is costly and slow there is no reason to do it otherwise.

**Comment by mhdong** [comment]
Hi @floitsch 
`    if (esp_rom_get_reset_reason(0) == RESET_REASON_CORE_DEEP_SLEEP) {
        calibration_mode = PHY_RF_CAL_NONE;
    }
    esp_err_t err = esp_phy_load_cal_data_from_nvs(cal_data);
    if (err != ESP_OK) {
        ESP_LOGW(TAG, "failed to load RF calibration data (0x%x), falling back to full calibration", err);
        calibration_mode = PHY_RF_CAL_FULL;
    }`
Regardless of whether step 5 is calibration or not, step 9 will ensure that there is calibration data available.

**Comment by floitsch** [comment]
interesting. I thought I had tried it and didn't see the "falling back to full calibration", but I can't fully remember anymore.

If it's falling back to a full calibration I'm fine with closing. (and I don't think it's super critical anyway).

**Comment by Alvin1Zhang** [comment]
Thanks for reporting and sharing the updates, feel free to reopen.
