### ISSUE TITLE
Failed to wakeup from deepsleep (IDFGH-7750)

### ISSUE THREAD

**Issue by Mr-Techtron** [espressif/esp-idf#9291]
## Environment

- Development Kit : ESP32-Wrover-Kit
- Kit version : DevKitv1
- Module:  ESP32-WROOM-32
- IDF version : v4.4.1-1329b19fe4945
- Build System : idf.py
- Compiler version : esp-2021r2-patch3-8.4.0
- Operating System : Windows
- Environment type : Eclipse plugin
- IDE : Eclipse
- Power Supply : USB

## Problem Description
The device failed to wake-up from the deep sleep if the RTC clock source is set to Internal 8.5MHz oscillator.

### Steps to reproduce

1. Use the example code of deepsleep.
2. Change the RTC clock source to Internal 8.5MHz oscillator.

**Comment by moefear85** [comment]
i believe this is the same as Issue-[8899](https://github.com/espressif/esp-idf/issues/8899)

**Comment by AxelLin** [comment]
@Mr-Techtron 
This is duplicated of #8007, the v4.4 branch should already include the fix. Please update your esp-idf to verify.

**Comment by Mr-Techtron** [comment]
@AxelLin 
I will check, and let you know.

**Comment by cssword** [comment]
#9455 
Did you wait more time?  Waked up after more than 3 minutes when I set sleep time is 10s in my case. 
Must something missing ......

**Comment by Mr-Techtron** [comment]
I have used the tag v4.4.2, and it works perfectly. Thank you
