### ISSUE TITLE
ESP-IDF crashes when i2c_param_config is called with gpio ports 6 and 11 (IDFGH-7753)

### ISSUE THREAD

**Issue by slmrojo** [espressif/esp-idf#9294]
## Environment

- Development Kit:      none
- Module or chip used:  ESP32
- IDF version: v4.4.1
- Build System:         CMake
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it):
    // 1.22.0-80-g6c4433a
- Operating System:     Windows
- (Windows only) environment type: PowerShell
- Using an IDE?: Visual Studio
- Power Supply:         USB

## Problem Description

Program crashes when i2c_param_config is called with gpio port 6 as scl and gpio port 11 as sda. When other ports are used, it works.

### Expected Behavior

i2c_param_config sets up an i2c port with gpio ports 6 and 11

### Actual Behavior
the program crashes during i2c_param_config
It also doesn't pass any kind of error

### Steps to reproduce

Run the code below, attempting to setup an i2c port on gpio ports 6 and 11.
### Code to reproduce this issue

[GIST](https://gist.github.com/slmrojo/eae114f036d2d5539055807003db8e23)

## Debug Logs

```
I (310) i2c-simple-example: Program started
I (320) i2c-simple-example: debug 1
I (320) i2c-simple-example: debug 1.a
I (320) i2c-simple-example: debug 1.b
I (330) i2c-simple-example: debug 2
```
[debug logs.txt](https://github.com/espressif/esp-idf/files/9048733/debug.logs.txt)

**Comment by chegewara** [comment]
Flash pins conflict:
https://raw.githubusercontent.com/gojimmypi/ESP32/master/images/myESP32%20DevKitC%20pinout.png

**Comment by slmrojo** [comment]
Can the flash pins not be used for any gpio? or just i2c?

**Comment by negativekelvin** [comment]
Those are the default flash pins.  You have to know that the app runs from flash so those pins are always in use reloading the cache and can't be used for anything.

**Comment by slmrojo** [comment]
Thank you
