### ISSUE TITLE
Update bundled llvm in tools.json (IDFGH-7756)

### ISSUE THREAD

**Issue by jounathaen** [espressif/esp-idf#9298]
Hi,
idf.py is currently bundling the llvm tools in version 12.0.1. However, the most recent one is [esp-14.0.0](https://github.com/espressif/llvm-project/releases/tag/esp-14.0.0-20220415). Would be cool to include a more recent version.
This would then fix #6721

**Comment by antmak** [comment]
@jounathaen thanks for the letting us know! A fix is already in master and is passing the internal test routines. Will be on GH soon

**Comment by igrr** [comment]
clang distribution in tools.json has been upgraded to:
* in IDF release/v5.0 branch: to release 14
* in IDF `master` branch (will be part of the upcoming v5.1 release): to release 15
