### ISSUE TITLE
New Features (IDFGH-7759)

### ISSUE THREAD

**Issue by I-AM-Tushar-chauhan** [espressif/esp-idf#9301]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

Please give as many details as you can. Include suggestions for useful APIs or interfaces if relevant.

**Additional context**

**Comment by I-AM-Tushar-chauhan** [comment]
Hello sir,
can you please send me the documentation of changes between version esp-idf-4.0 and version  esp-idf-4.4? because sometimes my data will erase automatically. Mainly I need to know the changes between NVS, spiffs and flash memory.

**Comment by Dazza0** [comment]
@I-AM-Tushar-chauhan Please see our [release notes](https://github.com/espressif/esp-idf/releases) for changes made by each iterative release. If there's something missing from the release notes, please feel free to reopen this issue.
