### ISSUE TITLE
WIFI_PROV_MGR code "qrcode.h" file directory error (IDFGH-7774)

### ISSUE THREAD

**Issue by Noumeer** [espressif/esp-idf#9310]
fatal error: qrcode.h: No such file or directory
#include "qrcode.h"
Unable to compile the code.

**Comment by mahavirj** [comment]
@Noumeer 

`qrcode` is now moved to component manager, please see [here](https://components.espressif.com/component/espressif/qrcode). It is used in example through following configuration:

https://github.com/espressif/esp-idf/blob/495d35949d50033ebcb89def98f107aa267388c0/examples/provisioning/wifi_prov_mgr/main/idf_component.yml#L2

Which example you are using? Please share your environment details.

**Comment by Noumeer** [comment]
I am using "wifi_prov_magr" example in vscode esp idf.

**Comment by brianignacio5** [comment]
Are you using the ESP-IDF extension ? Did you enable the component manager?

**Comment by Noumeer** [comment]
Its working now

**Comment by Alvin1Zhang** [comment]
Glad to hear that it is working, feel free to reopen.
