### ISSUE TITLE
ESP32-S3 JTAG unexpected GDB output (errno 138)

### ISSUE THREAD

**Issue by krupis** [espressif/esp-idf#9325]
Hello. I have ESP32-S3 but I cannot manage to use the built in JTAG for debugging. I also have ESP32 ethernet development board and was able to debug via the JTAG without any issues on that board.

I am trying this out on a blink example project.

My issue:

When I plug in the usb cable to USB or UART port on the device and start the OpenOCD
2.  My launch.json is as following:
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "ESP32 OpenOCD",
            "type": "cppdbg",
            "request": "launch",
            "cwd": "${workspaceFolder}/build",
            "program": "${workspaceFolder}/build/blink.elf",
            "miDebuggerPath": "C:/Users/petrikas.lu/.espressif/tools/xtensa-esp32s3-elf/esp-2021r2-patch3-8.4.0/xtensa-esp32s3-elf/bin/xtensa-esp32s3-elf-gdb.exe",
            "setupCommands":[
            { "text": "target remote 127.0.0.1:3333"},
            { "text": "set remote hardware-watchpoint-limit 2"},
            { "text": "monitor reset halt"},  
            { "text": "flushregs"}, 
            ]
        }
    ]
}
```

When I select my debugging configuration (https://ibb.co/V9LYR7q) I get the following error:

![image](https://user-images.githubusercontent.com/22237034/178228676-50a2c026-50e4-4f35-b4af-102e0ea0c43b.png)

Can someone clarify to me how can I set this up on ESP32-S3 and whether I need to use USB or UART port?

When I try to flash the device using JTAG, I get the following error (USB cable plugged in to UART port)
```
Open On-Chip Debugger  v0.11.0-esp32-20211220 (2021-12-20-15:43)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
debug_level: 2

Info : only one transport option; autoselect 'jtag'
Info : esp_usb_jtag: VID set to 0x303a and PID to 0x1001
Info : esp_usb_jtag: capabilities descriptor set to 0x2000
Warn : Transport "jtag" was already selected
Info : Listening on port 6666 for tcl connections
Info : Listening on port 4444 for telnet connections
❌ Error: esp_usb_jtag: could not find or open device!

Assertion failed!

Program: C:\Users\petrikas.lu\.espressif\tools\openocd-esp32\v0.11.0-esp32-20211220\openocd-esp32\bin\openocd.exe
File: ../src/jtag/core.c, Line 343

Expression: jtag_trst == 0
[Stopped] : OpenOCD Server

```

When I try to flash the device using JTAG, I get the following error (USB cable plugged in to USB port)
```
Open On-Chip Debugger  v0.11.0-esp32-20211220 (2021-12-20-15:43)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
debug_level: 2

Info : only one transport option; autoselect 'jtag'
Info : esp_usb_jtag: VID set to 0x303a and PID to 0x1001
Info : esp_usb_jtag: capabilities descriptor set to 0x2000
Warn : Transport "jtag" was already selected
Info : Listening on port 6666 for tcl connections
Info : Listening on port 4444 for telnet connections
❌ Error: libusb_open() failed with LIBUSB_ERROR_NOT_FOUND
❌ Error: esp_usb_jtag: could not find or open device!

Assertion failed!

Program: C:\Users\petrikas.lu\.espressif\tools\openocd-esp32\v0.11.0-esp32-20211220\openocd-esp32\bin\openocd.exe
File: ../src/jtag/core.c, Line 343

Expression: jtag_trst == 0
[Stopped] : OpenOCD Server
```

**Comment by FanhuaCloud** [comment]
You may need to modify the jtag configuration to the built-in USB

**Comment by krupis** [comment]
> You may need to modify the jtag configuration to the built-in USB

When I select  the target device, I select the ESP32-S3 with built in JTAG. Is that what you mean or is it something else?

**Comment by FanhuaCloud** [comment]
Check here first:
![Snipaste_2022-07-11_18-15-49](https://user-images.githubusercontent.com/19590243/178242752-a64765ff-85c9-4bd6-b886-426f40d99659.jpg)
Then try to install the JTAG driver:
https://docs.espressif.com/projects/esp-idf/zh_CN/latest/esp32s3/api-guides/jtag-debugging/configure-builtin-jtag.html
If it still doesn't work, please wait for the official reply

**Comment by krupis** [comment]
> Check here first: ![Snipaste_2022-07-11_18-15-49](https://user-images.githubusercontent.com/19590243/178242752-a64765ff-85c9-4bd6-b886-426f40d99659.jpg) Then try to install the JTAG driver: https://docs.espressif.com/projects/esp-idf/zh_CN/latest/esp32s3/api-guides/jtag-debugging/configure-builtin-jtag.html If it still doesn't work, please wait for the official reply

Thanks for the reply!

My settings.json are as following:

![image](https://user-images.githubusercontent.com/22237034/178244914-640e9579-beba-46ef-b9a6-71d51bdad4ba.png)

I believe that is correct since I use built in jtag. 


I have also followed the link that you have suggested and installed the driver:
```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.
                                                                                                                        Try the new cross-platform PowerShell https://aka.ms/pscore6                                                                                                                                                                                    PS C:\Windows\system32> Invoke-WebRequest 'https://dl.espressif.com/dl/idf-env/idf-env.exe' -OutFile .\idf-env.exe; .\idf-env.exe driver install --espressif
Downloading https://dl.espressif.com/dl/idf-driver/idf-driver-esp32-usb-jtag-2021-07-15.zip to idf-driver-esp32-usb-jtag-2021-07-15.zip
Installing driver with INF C:\Users\petrikas.lu\.espressif\tools\idf-driver\idf-driver-esp32-usb-jtag-2021-07-15\usb_jtag_debug_unit.inf -> C:\Windows\INF\oem74.inf ... Already installed
PS C:\Windows\system32>
```
Unfortunately, the issue still seem to persist.

**Comment by krupis** [comment]
> Could you please also check the list of devices in the Device Manager? There should be a `USB JTAG/serial debug unit` device listed once the driver has been installed.

In the device manager under the Universal serial bus devices I can see the USB JTAG/serial debug unit:
![image](https://user-images.githubusercontent.com/22237034/178246187-b1932817-d740-4497-b6aa-c8bd55dcf6c5.png)

**Comment by krupis** [comment]
I have borrowed ESP32-S3 device from a colleague and I can confirm that it works without any issues with another ESP32-S3 development board! Perhaps it is just a faulty board that I have or I have managed to break something.

Good news is that it works with the other device!
![image](https://user-images.githubusercontent.com/22237034/178248757-d9f6dab2-43a2-4b83-a2c5-d39abe20e60c.png)

**Comment by FanhuaCloud** [comment]
Please try plugging in the unusable device and update the driver in the device manager
![Snipaste_2022-07-11_18-53-51](https://user-images.githubusercontent.com/19590243/178249124-7a93df51-4717-4c2c-9c1f-3bb7c7c1a3fd.jpg)
![Snipaste_2022-07-11_18-54-01](https://user-images.githubusercontent.com/19590243/178249133-e8975882-b83e-4ee7-b439-886e75cfb06f.jpg)
After the update is complete, you should be able to see the Espressif text.
![Snipaste_2022-07-11_18-54-22](https://user-images.githubusercontent.com/19590243/178249207-b7ec8c13-4212-432b-9748-621366ff12bb.jpg)
