### ISSUE TITLE
Create virtual network interface like in LINUX, 1 static, 1 DHCP (IDFGH-7826)

### ISSUE THREAD

**Issue by franz-ms-muc** [espressif/esp-idf#9326]
**Is your feature request related to a problem? Please describe.**

So, when you use a ESP32 device e.g. with Ethernet. 
it would be nice to have a Interface eth0 which is DHCP Enabled, 
so the DHCP Server gives the ESP32 a Address and Gateway. 
this is most easy on most Networks to get Internet Acces. 

then it would be nice to have a Second, Alias Interface eth0:0 with a STATIC IP Address. 
so when the Service Techican comes and want to connect to the Device he does not need to find out the DHCP Assigned IP, but he can use the fixed one. 

**Describe the solution you'd like**

make Alias Interfaces working, prefferrably for Wifi and Ethernet, 
but at least for Ehternet.

**Describe alternatives you've considered**

not yet done a lot research on it. 
a Google on "virtual network interfaces in ESP32" did not bring up any solution. 

**Additional context**

none.

**Comment by NathanJPhillips** [comment]
This is probably a request that should be directed towards the LWIP repository. The ESP port of LWIP shouldn't be diverging from the main branch in ways this significant.

**Comment by franz-ms-muc** [comment]
Do you know their issue Tracker?

Holen Sie sich Outlook für Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, fix is available at https://github.com/espressif/esp-idf/commit/88525d1ec6cc69e22f61f32868910ff7bb817d08, feel free to reopen.
