### ISSUE TITLE
Add CMock dependencies to Docker image (IDFGH-7808)

### ISSUE THREAD

**Issue by robbawebba** [espressif/esp-idf#9342]
**Is your feature request related to a problem? Please describe.**

I recently added mocking to my project's unit tests using the guide in the [ESP-IDF documentation](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/unit-tests.html#mocks). Everything works well when building/testing locally for the esp32s3 target, and I'm very satisfied with CMock and its integration with the rest of the IDF build infrastructure.

The only downside is that the unit test build does not work when building in a Docker container using the `espressif/idf` docker image. My team uses the Docker image for both development and CI testing. This is due to ruby, a dependency of CMock, not being included in the Docker image by default, causing the mock generation build step to fail.

**Describe the solution you'd like**

I propose that ruby, and any other CMock dependencies, should be included in the `espressif/idf` Docker image by default. The [ESP-IDF unit test documentation](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/unit-tests.html#requirements) lists both `ruby` and `libbsd-dev` as requirements. So far I have not needed `libbsd-dev`, but if it is required for mocking in some scenarios, this dependency should also be included.

I enjoy using the unit testing and mocking system provided by ESP-IDF, and it seems like the developers are adopting CMock as the mocking framework of Choice. I believe adding the CMock dependencies to the Docker image will make it easier for more developers to start using mocking in their unit tests if they choose to do so.   

**Describe alternatives you've considered**

In the meantime, I've worked around this issue by creating my own Docker image based on `espressif/idf`. My Dockerfile is as follows:

```
ARG IDF_VERSION=v4.4.1
FROM espressif/idf:${IDF_VERSION}

RUN apt-get update \
  && apt-get install -y --no-install-recommends \
    ruby \
  && apt-get autoremove -y \
  && rm -rf /var/lib/apt/lists/*
```

**Comment by 0xjakob** [comment]
@robbawebba Thanks for letting us know! I'll check but I think it should be straight-forward to add ruby and libbsd-dev.

**Comment by robbawebba** [comment]
@0xjakob Great, thank you for your work and for the fast response!

**Comment by 0xjakob** [comment]
@robbawebba The image `espressif/idf` should contain ruby and libbsd now. Please give it a try.
