### ISSUE TITLE
例子 i2s_adc_dac   输出声音有爆破音, 输出日志与例子不同 (IDFGH-7841)

### ISSUE THREAD

**Issue by sywxf** [espressif/esp-idf#9370]
APLL expected frequency is 5632000 Hz, real frequency is 5631999 Hz

为什么不是Req RATE: 16000,

`entry 0x40080694
I (27) boot: ESP-IDF v4.4.1-dirty 2nd stage bootloader
I (27) boot: compile time 09:37:49
I (27) boot: chip revision: 1
I (30) boot_comm: chip revision: 1, min. bootloader chip revision: 0
I (37) boot.esp32: SPI Speed      : 40MHz
I (42) boot.esp32: SPI Mode       : DIO
I (47) boot.esp32: SPI Flash Size : 4MB
I (51) boot: Enabling RNG early entropy source...
I (57) boot: Partition Table:
I (60) boot: ## Label            Usage          Type ST Offset   Length
I (67) boot:  0 nvs              WiFi data        01 02 00009000 00006000
I (75) boot:  1 phy_init         RF data          01 01 0000f000 00001000
I (82) boot:  2 factory          factory app      00 00 00010000 00100000
I (90) boot:  3 storage          Unknown data     01 81 00110000 00200000
I (97) boot: End of partition table
I (101) boot_comm: chip revision: 1, min. application chip revision: 0
I (109) esp_image: segment 0: paddr=00010020 vaddr=3f400020 size=1cd24h (118052) map
I (160) esp_image: segment 1: paddr=0002cd4c vaddr=3ffb0000 size=02368h (  9064) load
I (164) esp_image: segment 2: paddr=0002f0bc vaddr=40080000 size=00f5ch (  3932) load
I (167) esp_image: segment 3: paddr=00030020 vaddr=400d0020 size=19058h (102488) map
I (211) esp_image: segment 4: paddr=00049080 vaddr=40080f5c size=0af90h ( 44944) load
I (230) esp_image: segment 5: paddr=00054018 vaddr=50000000 size=00010h (    16) load
I (236) boot: Loaded app from partition at offset 0x10000
I (236) boot: Disabling RNG early entropy source...
I (250) cpu_start: Pro cpu up.
I (250) cpu_start: Starting app cpu, entry point is 0x40081050
0x40081050: call_start_cpu1 at /Users/sywxf/esp/esp-idf/components/esp_system/port/cpu_start.c:160

I (0) cpu_start: App cpu up.
I (264) cpu_start: Pro cpu start user code
I (264) cpu_start: cpu freq: 160000000
I (265) cpu_start: Application information:
I (269) cpu_start: Project name:     i2s_adc_dac
I (274) cpu_start: App version:      1
I (279) cpu_start: Compile time:     Jul 17 2022 09:37:17
I (285) cpu_start: ELF file SHA256:  4d450fd24746cddb...
I (291) cpu_start: ESP-IDF:          v4.4.1-dirty
I (296) heap_init: Initializing. RAM available for dynamic allocation:
I (303) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM
I (310) heap_init: At 3FFB2C60 len 0002D3A0 (180 KiB): DRAM
I (316) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM
I (322) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
I (329) heap_init: At 4008BEEC len 00014114 (80 KiB): IRAM
I (336) spi_flash: detected chip: generic
I (339) spi_flash: flash io: dio
I (344) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.
I (355) I2S: APLL expected frequency is 5632000 Hz, real frequency is 5631999 Hz
I (365) I2S: DMA Malloc info, datalen=blocksize=4092, dma_buf_count=2
I (375) I2S: DMA Malloc info, datalen=blocksize=4092, dma_buf_count=2
partiton addr: 0x00110000; size: 2097152; label: storage
Erasing flash 
partiton addr: 0x00110000; size: 2097152; label: storage
Erase size: 323584 Bytes
I (1705) I2S: APLL expected frequency is 5632000 Hz, real frequency is 5631999 Hz`

**Comment by L-KAYA** [comment]
你好，
A1: APLL的频率和采样频率不是一个概念，采样频率是DAC或者ADC转换数模信号的频率，而APLL是驱动I2S模块的模块时钟，而模块时钟频率是由采样频率计算得到。APLL需求频率的计算方法为：`16000Hz（采样频率）* 16（位宽）*2（通道数）* 2（bclk固定分频） * x（mclk自适应分频）`
A2:爆破音问题需要进一步确认，若是驱动问题，将会有对应的修复
A3:实际日志与README中日志不同是README中日志没有及时更新，以实际日志为准即可

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to short of feedback, feel free to reopen with more updates. Thanks.
