### ISSUE TITLE
i2s_ad_dac example has gaps in playback (IDFGH-7862)

### ISSUE THREAD

**Issue by PilnyTomas** [espressif/esp-idf#9389]
## Environment

- Development Kit: [ESP32-DevKitC]
- Kit version (for WroverKit/PicoKit/DevKitC): [v4]
- Module or chip used: [ESP32-WROOM-32D]
- IDF version: Tried on `v4.4.1-581-gee2029c38a` and `v5.0-dev-4257-g508661b03e`
- Build System: [idf.py]
- Compiler version: 8.4.0
- Operating System: [Linux]
- Using an IDE?: [No]
- Power Supply: [USB, directly from computer - no hubs inbetween]

## Problem Description

Audio playback is laggy.
There seems to be approx 64.4ms period of playback followed by approx the same length (64.4ms) period of silence - this pattern repeats and the resulting audio is horribly unusable, laggy / chopped.

### Expected Behavior
Clear audio without pauses, lags, gaps,...

### Actual Behavior
Gaps in playback

### Steps to reproduce

1. Setup example https://github.com/espressif/esp-idf/tree/release/v4.4/examples/peripherals/i2s/i2s_adc_dac
2. Listen
3. Record on an oscilloscope

In the pictures, channel 2 is ADC output, and channel 3 is amplifier output

![playback period](https://user-images.githubusercontent.com/34927466/179755894-fad2ff46-5f47-46da-9fe8-56c70fdcbe99.jpg)
![lag period](https://user-images.githubusercontent.com/34927466/179755888-5755be67-0812-40a6-8d6f-44a373c67842.jpg)

Relates to Arduino-ESP32 issue https://github.com/espressif/arduino-esp32/issues/5938

**Comment by PilnyTomas** [comment]
Uploading some more pictures - audio file playback - both DAC channels

Overview
![audio file playback](https://user-images.githubusercontent.com/34927466/182105251-f496156d-e7f4-44af-9a12-596644b1df8a.png)

Closeup - gap period
![both DAC channels pic 1](https://user-images.githubusercontent.com/34927466/182105434-f6dfa482-95c6-4fb2-8854-02a1668615ce.png)

Closeup - playback period
![both DAC channels pic 2](https://user-images.githubusercontent.com/34927466/182105489-81a72d55-3fac-4d6a-acfa-3e4f95c729b2.png)

**Comment by L-KAYA** [comment]
The issue can be fixed by changing the I2S configuration from
```c
        .dma_buf_count = 2,
        .dma_buf_len = 1024,

```
to
```
        .dma_buf_count = 6,
        .dma_buf_len = 256,
```

The fix is on the way.

**Comment by PilnyTomas** [comment]
Hi @L-KAYA, I just tested the example with the new settings and can confirm that the resulting audio is clear and without gaps.
