### ISSUE TITLE
mqtt `select` calls' timeouts cluttering debug level logs (IDFGH-7893)

### ISSUE THREAD

**Issue by KaeLL** [espressif/esp-idf#9415]
- IDF version: 36f49f3

## Problem Description

Do these really need to be DEBUG rather than VERBOSE?
```
D (16:26:43.753) TRANSPORT_BASE: poll_read: select - Timeout before any socket was ready!
D (16:26:43.754) TRANSPORT_BASE: poll_read: select - Timeout before any socket was ready!
D (16:26:43.754) mqtt_client: esp_mqtt_handle_transport_read_error: transport_read(): call timed out before data was ready!
```
Setting these components' log level to INFO would hide other relevant DEBUG level logs.

**Comment by moefear85** [comment]
the timeouts are logged using the "TRANSPORT_BASE" tag, not mqtt, so just use:

> esp_log_level_set("TRANSPORT_BASE",ESP_LOG_NONE");

but place it after all setup so it doesn't get changed back.

**Comment by KaeLL** [comment]
@moefear85 🤔
![image](https://github.com/espressif/esp-idf/assets/4423144/a9d7d100-67d6-40eb-87ec-070c5dabfa74)
Again I ask: do these really need to be DEBUG rather than VERBOSE?

**Comment by moefear85** [comment]
I'm neither a contributor nor maintainer... but you can search for the error message in vscode (or use grep) , then simply replace ESP_LOGD with ESP_LOGV. most likely it would be a one-liner edit.

**Comment by KaeLL** [comment]
@euripedesrocha

**Comment by euripedesrocha** [comment]
@KaeLL this was already changed in IDF 5.2.

**Comment by AxelLin** [comment]
@euripedesrocha 
IDF 5.0 and 5.1 still need fix.

**Comment by AxelLin** [comment]
> @euripedesrocha IDF 5.0 and 5.1 still need fix.

@euripedesrocha
There is no update for IDF 5.0 and 5.1.
Now I'm wondering if you stop maintaining esp-mqtt for older release branches?

**Comment by euripedesrocha** [comment]
@AxelLin we didn't stop maintaining 5.0 and 5.1 branches. We just decided to not backport this at the moment. I'll reassess and maybe start the backport process.  Sorry for let you request without an answer.
