### ISSUE TITLE
Custom board StartUp problem (IDFGH-7908)

### ISSUE THREAD

**Issue by Zeni241** [espressif/esp-idf#9427]
I am facing startup problem with my custom board. If the supply voltage is more than 3.3V then the board ‎always boot in download mode and I get following lines in terminal:‎
_**rst:0x1 (POWERON_RESET),boot:0x3 (DOWNLOAD_BOOT(UART0/UART1/SDIO_REI_REO_V2))‎
waiting for download**_
If the supply voltage is 3.3v than the board will boot in normal mode and the message in terminal is:‎
**_rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)‎
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00‎
mode:DIO, clock div:2‎_**
I am following ESP32_DevKitC_SCH_20180607A for my custom board.‎
I want the board to boot in normal mode till I keep pressing button which connects IO_0 to GND.‎
I am using ESP32EU module on my board

**Comment by moefear85** [comment]
this is not an issue with esp-idf. please open this on esp32.com instead. also: try adding a pullup to IO0. generally the board shouldn't be run at a higher voltage than 3.3V even if that is within the absolute maximum ratings.

**Comment by Zeni241** [comment]
Thanks for commenting. This board is supposed to run on lipo battery which can vary from 4.2v to 3.5v. The module is getting 3.3v after LDO ME6217.

**Comment by moefear85** [comment]
here's how to use your ldo [ME6217](https://datasheet.lcsc.com/lcsc/1912111437_MICRONE-Nanjing-Micro-One-Elec-ME6217C33M5G_C427602.pdf)

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, and sharing the notes, will close. Feel free to open a post on our forum https://esp32.com, thanks.
