### ISSUE TITLE
spi_bus_free doesn't disable pins properly ie. leaks power on SPI pins (IDFGH-7926)

### ISSUE THREAD

**Issue by Yardie-** [espressif/esp-idf#9444]
## Environment

- Development Kit:      [none]
- Module or chip used:  [ESP32-S3-WROOM-16|]
- IDF version :v4.4.1
- Build System:         [idf.py]
- Compiler version :xtensa-esp32-elf-gcc (crosstool-NG esp-2021r2-patch3) 8.4.0
- Operating System:     [Linux|]
- Using an IDE?: [No]
- Power Supply:     [USB]

## Problem Description
spi_bus_free leaves all SPI pins pulled up. 
This is enough to visibly illuminate an LED 
### Expected Behavior
Pins should be dissabled and floating
### Actual Behavior
As above
### Steps to reproduce
After setting up spi as per example in peripherals 
with 
spi_device_handle_t spi = NULL;

void spi_end()
{
  if(spi != NULL)
    spi_bus_remove_device(spi);
  spi_bus_free(EPD_HOST);
  spi = NULL;
}
I have an LED connected on each pin as a test device this is where I noticed the issue.

The wiring is simple 
Attach an led and appropriate resistor between each SPI pin and ground.

### Code to reproduce this issue

```cpp
void gpio_set(uint8_t pin, uint8_t to)
{
    gpio_set_direction(pin, GPIO_MODE_OUTPUT);
    gpio_set_level(pin, to);
}

void epd_spi_end()
{
  if(spi != NULL)
    spi_bus_remove_device(spi);
  spi_bus_free(EPD_HOST);
  spi = NULL;
// without the following 4 lines LEDs remain slightly iluminated. Thus a power leak.
  gpio_set(CS_PIN, 0);
  gpio_set(MOSI_PIN, 0);
 gpio_set(MISO_PIN, 0);
  gpio_set(SCK_PIN, 0);  
}

This is simple to reproduce and totally repeatable. It doesn't create errors.

**Comment by kriegste** [comment]
Isn't pullup the default GPIO state?
https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/peripherals/gpio.html#_CPPv414gpio_reset_pin10gpio_num_t

**Comment by Yardie-** [comment]
@kriegste  Thank you. That is true I missed that part in the documentation. That explains this completely.
