### ISSUE TITLE
`rtc_brownout_isr_handler` works incorrectly for single core CPUs (IDFGH-7939)

### ISSUE THREAD

**Issue by ermacv** [espressif/esp-idf#9456]
## Environment

- Development Kit:      none
- Kit version (for WroverKit/PicoKit/DevKitC): none
- Module or chip used:  ESP32-C3
- IDF version (run ``git describe --tags`` to find it): v5.0-dev-3954-g271f4e4c40
- Build System:         CMake
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it): 11.2.0
- Operating System:    Ubuntu 22.04
- Using an IDE?: No
- Power Supply:        USB and Battery

## Problem Description
`rtc_brownout_isr_handler` function that is called when brownout ISR is triggered uses internally the following code to stall the CPU:
```c
// Stop the other core.
esp_cpu_stall(!cpu_hal_get_core_id());
```
If you go through all nested functions starting from `esp_cpu_stall` then you find out the following code:
```c
FORCE_INLINE_ATTR __attribute__((pure)) uint32_t rv_utils_get_core_id(void)
{
#if SOC_CPU_CORES_NUM == 1
    return 0; // No need to check core ID on single core hardware
#else
    uint32_t cpuid;
    cpuid = RV_READ_CSR(mhartid);
    return cpuid;
#endif
}
```
So for ESP32-C3 function `cpu_hal_get_core_id` should always return 0. And applying `!` not logical operator makes it non 0 and then assertion is triggered because only 0 is expected.

It seems that you need to use a check for amount of cores MCU has. Something like this (from file `components/esp_system/port/soc/esp32c3/system_internal.c`):
```c
#if !CONFIG_FREERTOS_UNICORE
    const uint32_t other_core_id = (core_id == 0) ? 1 : 0;
    esp_cpu_stall(other_core_id);
#endif
```

### Expected Behavior
Calling brownout ISR print functions.

### Actual Behavior
Assertion is triggered when ISR is triggered:
`assert failed: esp_cpu_stall cpu.c:40 (core_id >= 0 && core_id < SOC_CPU_CORES_NUM)`

### Steps to reproduce
For example: use discharged batteries and enable BLE. Or set current limitation for power adapter.

## Debug Logs

```
assert failed: esp_cpu_stall cpu.c:40 (core_id >= 0 && core_id < SOC_CPU_CORES_NUM)
Core  0 register dump:
MEPC    : 0x40384d7c  RA      : 0x4038bea2  SP      : 0x3fc98b10  GP      : 0x3fc94e00  
TP      : 0x3fc7769c  T0      : 0x37363534  T1      : 0x7271706f  T2      : 0x33323130  
S0/FP   : 0x00000074  S1      : 0x00000001  A0      : 0x3fc98b4c  A1      : 0x3fc95251  
A2      : 0x00000001  A3      : 0x00000029  A4      : 0x00000001  A5      : 0x3fc9a000  
A6      : 0x7a797877  A7      : 0x76757473  S2      : 0x00000009  S3      : 0x3fc98c73  
S4      : 0x3fc95250  S5      : 0x00000000  S6      : 0x00000000  S7      : 0x00000000  
S8      : 0x00000000  S9      : 0x00000000  S10     : 0x00000000  S11     : 0x00000000  
T3      : 0x6e6d6c6b  T4      : 0x6a696867  T5      : 0x66656463  T6      : 0x62613938  
MSTATUS : 0x00001881  MTVEC   : 0x40380001  MCAUSE  : 0x00000007  MTVAL   : 0x00000000  
MHARTID : 0x00000000  
```

**Comment by ESP-Marius** [comment]
@ermacv you are right. Thanks for reporting this.

Your suggested fix LGTM, i'll make an internal MR and apply it.
