### ISSUE TITLE
[Feature Request] sdkconfig: "Print registers and reboot after delay" would be useful (IDFGH-7947)

### ISSUE THREAD

**Issue by chipweinberger** [espressif/esp-idf#9462]
A `CONFIG_ESP_SYSTEM_PANIC_PRINT_DELAY_REBOOT` option would be usable for both development & production, and would be most ideal for Beta testing phase.

1. "print & reboot" is annoying for development. A Boot Loop will log to serial too much, forever.
2. "print registers and halt" is not good for users.

We need a middle approach,  "print & delay & reboot, with a configurable delay. e.g. 6 seconds.

Thanks for your consideration.

**Comment by chipweinberger** [comment]
Bump. 

A `CONFIG_ESP_SYSTEM_PANIC_PRINT_DELAY_REBOOT` option would let me keep it the same between development and production, and it just generally more useful IMO. 20htz boot loops are annoying =)

**Comment by chipweinberger** [comment]
@ESP-Marius, @igrr, @Alvin1Zhang 

Just want to make sure 1 person sees this.

**Comment by igrr** [comment]
Hi @chipweinberger,
All issues posted on Github are synced to our internal issue tracker, categorized and land on of of the teams' backlog. We've seen this feature request but currently consider it relatively low priority. Most efforts right now are focused on v5.0 release and various bug fixes.

Have you checked this example demonstrating how to set up builds for multiple configurations (development/production)? https://github.com/espressif/esp-idf/blob/master/examples/build_system/cmake/multi_config/README.md
I hope it can satisfy your requirement for now.

**Comment by chipweinberger** [comment]
Thanks for your input Ivan, as always. 

That is a useful page, for now =)

**Use case:** For Beta testing, reboot after delay is most ideal. A beta device may need to be debugged "live", but must still reboot automatically.

**Comment by chipweinberger** [comment]
Pull Request: https://github.com/espressif/esp-idf/pull/9962

@igrr, hope you consider it!

**Comment by chipweinberger** [comment]
merged into master.
