### ISSUE TITLE
Clarify documentation about maximum number of supported encrypted peers for ESP-NOW (IDFGH-7960)

### ISSUE THREAD

**Issue by chenlijun99** [espressif/esp-idf#9473]
## Problem Description

In the master branch documentation https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/network/esp_now.html#add-paired-device it is written

> The maximum number of paired devices is 20, and the paired encryption devices are no more than 16, the default is 6.

However, it is unclear how to modify the number of paired encryption devices from the default of 6 to a higher number. AFAIK ESPNOW is shipped as a precompiled library `libespnow.a`, so it can't be a compile time switch. OTOH, I see no API to change this number either.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, fix is available at https://github.com/espressif/esp-idf/commit/d89a51299d54b3a8793872051a95d230e6818ee1, feel free to reopen.
