### ISSUE TITLE
How do I reference esp_wpa2.h in esp-idf v4.4+ (IDFGH-7971)

### ISSUE THREAD

**Issue by MATTYGILO** [espressif/esp-idf#9484]
In esp-idf v4.1 you can use `#include "esp_wpa2.h"` to reference this file

When I try it in esp-idf v4.4 I get this error:
```
fatal error: esp_wpa2.h: No such file or directory
 #include "esp_wpa2.h"
```

**Comment by MATTYGILO** [comment]
I am using esp32s3
esp-idf v4.4
I am trying to build with `#include "esp_wpa2.h"`
and I get this error
```
fatal error: esp_wpa2.h: No such file or directory
 #include "esp_wpa2.h"
```

What sdkconfig flags do I need to change to enable this?
All help is much appreciated

**Comment by kapilkedawat** [comment]
Hi @MATTYGILO , Can you please share whether you are trying to do this in a component or in an example?

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to short of feedback, feel free to reopen with more updates, thanks.
