### ISSUE TITLE
Blufi Check Sum Error in IDF 5.0 (IDFGH-7977)

### ISSUE THREAD

**Issue by Nick-tecpal** [espressif/esp-idf#9488]
## Environment

- Development Kit: ESP32-S3-DevKitC-1
- Kit version:v1
- Module or chip used:  ESP32-S3
- IDF version :master/v5.0-dev-4547-gfde4afc67a
- Build System:         [Make|CMake|idf.py]
- Compiler version:xtensa-esp32-elf-gcc (crosstool-NG esp-2020r3) 8.4.0
- Operating System:Linux
- Using an IDE?:No
- Power Supply: USB

## Problem Description

We’re using the IDF4.4, and we plan to upgrade to 5.0. But we get a check sum error when use the Blufi example to test the IDF 5.0

https://github.com/espressif/esp-idf/tree/release/v5.0/examples/bluetooth/blufi

### Expected Behavior

Pass the test with Blufi example

### Actual Behavior

Check sum error with Blufi example

### Steps to reproduce

Download and run the Blufi example.

## Debug Logs
![WechatIMG130](https://user-images.githubusercontent.com/110455793/182553429-7b5db612-7f18-429c-a1d7-d51343602daf.png)

## Other items if possible

**Comment by esp-cjh** [comment]
Hi, @Nick-tecpal 
In IDF 5.0, we enable hardware AES acceleration(CONFIG_MBEDTLS_HARDWARE_AES=y) which caused error in blufi ase decrypt. You can disable hardware AES acceleration temporarily by menuconfig. We'll fix this asap.

**Comment by esp-cjh** [comment]
Hi, @Nick-tecpal. 
We have found the reason of this problem. API usage for `mbedtls_dhm_calc_secret` was incorrect in IDF 5.0. We will fix it ASAP.
