### ISSUE TITLE
BLE failed to set new device name after reconnection (IDFGH-7995)

### ISSUE THREAD

**Issue by jrHernandezSio** [espressif/esp-idf#9505]
**ENVIRONMENT:**

espressif32@3.3.2 -> framework-espidf @ 3.40300.0 (4.3.0)
BLE driver: Bluedroid (loaded dynamically)

**DESCRIPTION**
I need to change device name when advertising BLE and it is giving an error if the device was already advertising with other name. See full details below.

![image](https://user-images.githubusercontent.com/92985413/183075062-ef4ba7ce-761f-4b40-a2b7-c4ea1553817c.png)

I have tried unregister `esp_ble_gatts_app_unregister(gl_profile_tab[PROFILE_A_APP_ID].gatts_if);` before registering again and no success

Disconection process before reconnection in same boot cylce:

```
    esp_ble_gap_stop_advertising();
    
    esp_bluedroid_disable();
    esp_bluedroid_deinit();

    esp_bt_controller_disable();
    esp_bt_controller_deinit();
 
    esp_ble_gatts_app_unregister(gl_profile_tab[PROFILE_A_APP_ID].gatts_if);
```

Instead of setting my new name, the "ESP32" name is set.

The name set is done inside handler:
![image](https://user-images.githubusercontent.com/92985413/183074947-27e0c618-5b1d-47a9-bf24-0e06ab860fc0.png)

Am I missing sth ?

Regards, Ramon.

**Comment by esp-cjh** [comment]
The error code means that your argument is invalid, please check your argument not NULL and the length of argument no more than `CONFIG_BT_MAX_DEVICE_NAME_LEN`.

The device name in advertising is included in advertising data or scan response data. So if you want to change the device name when advertising, you don't need to reboot or stop advertising. Just follow the steps below:
```
/* set device name */
esp_ble_gap_set_device_name("device name");
/* if adv data include name */
esp_ble_gap_config_adv_data(&adv_data);
/* or if scan rsp data include name */
esp_ble_gap_config_adv_data(&scan_rsp_data);
```

**Comment by jrHernandezSio** [comment]
Hi,

Thanks for your helpful answer.

You were right, I was passing a longer device name (37 bytes) due to a non-initialized buffer in my side.

Regards, Ramon.
