### ISSUE TITLE
ESP-IDF v4.4.2 release not available, VSCode extension can't install ESP-IDF, Online installer fails (IDFGH-7999)

### ISSUE THREAD

**Issue by grzegorzniemirowski** [espressif/esp-idf#9509]
It seems that latest ESP-IDF v.4.4 version is 4.4.2. This information is here:
https://docs.espressif.com/projects/esp-idf/en/stable/esp32/
![obraz](https://user-images.githubusercontent.com/68647264/183242018-378318eb-a797-42fa-94f6-e62a30aee607.png)

Unfortunately it can't be downloaded. The release is not available at
https://github.com/espressif/esp-idf/releases/tag/v4.4.2
There is just the source code. You can't also download v4.4.2 from
https://dl.espressif.com/dl/esp-idf/
There is an online installer which fails when v4.4.2 is selected.
![obraz](https://user-images.githubusercontent.com/68647264/183242157-17a368e1-ec46-4279-8819-f9bae11e0b4f.png)

The same applies to VSCode Extension. It fails when it tries to install ESP-IDF.
![obraz](https://user-images.githubusercontent.com/68647264/183242290-b964e6fe-1742-42ba-b9f1-1ac72259f828.png)

Please make release 4.4.2 available or don't pretend it's the latest version so the installer won't try to download something which doesn't exist.

**Comment by tongclement** [comment]
Same issue here:
Error message:
```Waiting 8 seconds...
File download response error: Failed web connection with error code: 404
https://github.com/espressif/esp-idf/releases/download/v4.4.2/esp-idf-v4.4.2.zip
Failed download. Retrying...
Error: Error: HTTP/HTTPS Response Error
Waiting 16 seconds...
File download response error: Failed web connection with error code: 404
https://github.com/espressif/esp-idf/releases/download/v4.4.2/esp-idf-v4.4.2.zip
Failed download. Retrying...
Error: Error: HTTP/HTTPS Response Error
Downloaded release/v4.4 (release branch). Extracting..```

**Comment by tongclement** [comment]
[https://drive.google.com/file/d/1K1mtP5ifr1B3jY-AOdW8TTc5_YkGKHT4/view?usp=sharing](url)

**Comment by aokrasavin** [comment]
Same here

**Comment by klandreth-cardinal** [comment]
They tagged a release without doing a release...

**Comment by moefear85** [comment]
yep, i can confirm, esp-idf is broken again.

**Comment by igrr** [comment]
Sorry for the issue everyone! The release is now available (https://github.com/espressif/esp-idf/releases/tag/v4.4.2) and the release archive will be available on the [mirror site](https://dl.espressif.com/github_assets/espressif/esp-idf/releases/download/v4.4.2/esp-idf-v4.4.2.zip) in a couple of hours.

We've taken a note not to update the release list used by VS Code extension until the release archive is published, in the future!
