### ISSUE TITLE
Don't use "operator" as variable name (IDFGH-8000)

### ISSUE THREAD

**Issue by higaski** [espressif/esp-idf#9510]
The new MCPWM driver uses the C++ keyword operator as variable name.

https://github.com/espressif/esp-idf/blob/30e8f19f5ac158fc57e80ff97c62b6cc315aa337/components/driver/include/driver/mcpwm_types.h#L89

Is this really necessary?
It's already really painful enough to include esp-idf C code into any kind of C++ file because of all the nested structs with designated initializers which isn't supported by C++ the same way.

**Comment by 0xjakob** [comment]
Hi @higaski, sorry for the inconvenience. Sometimes these things slip through because most developers don't use C++, but only C.

> Is this really necessary?

I don't think so. We'll check this and probably change the variable name.
