### ISSUE TITLE
Add .component_hash to gitignore (IDFGH-8005)

### ISSUE THREAD

**Issue by dizcza** [espressif/esp-idf#9515]
I have the "espressif/esp_websocket_client" in the dependencies (managed components). The sources already contain the gitignore but `.component_hash` is missing there.

I cannot build the project on my two machines that have different versions of cmake without removing the `.component_hash` each time.

And of course, I could add it to the project gitignore. It just pisses off the user... a bit.

**Comment by igrr** [comment]
@dizcza just a question, do you have `managed_components` in your project's .gitignore file? I think adding that should cover both the components themselves and the .component_hash files created therein.

**Comment by kumekay** [comment]
@dizcza What kind of issue do you have with different CMake versions? Content of `.component_hash` should not depend on CMake version.

We suggest to gitignore whole `managed_components` directory for projects and only store `dependencies.lock` in the repo.

**Comment by dizcza** [comment]
>  Content of .component_hash should not depend on CMake version.

Perhaps, I misunderstood how the hash is generated.

> We suggest to gitignore whole managed_components directory for projects and only store dependencies.lock in the repo.

I see. All right, I'll add the directory to gitignore. Didn't find this in the docs.
