### ISSUE TITLE
esp_efuse_mac_get_default  (IDFGH-8022)

### ISSUE THREAD

**Issue by Rafinha29** [espressif/esp-idf#9531]
Return base MAC address which is factory-programmed by Espressif in EFUSE. 

base MAC address, length: 6 bytes/8 bytes. length: 6 bytes for MAC-48 8 bytes for EUI-64(used for IEEE 802.15.4).

since the examples i've seen use 6 bytes Mac,I wonder in what case should I receive a 8 byte MAC or should I always check the lenght of the MAC address, can this function also return the type of MAC address?

**Comment by KonstantinKondrashov** [comment]
Hi!
You are right that `esp_efuse_mac_get_default()` returns 6 bytes and 8 bytes for ESP32-H4 chip because it has IEEE802154.
We can not break this API (one more). For a certain chip, you will receive a constant len of mac.
I can add an API to get len of MAC which is used in the system.
