### ISSUE TITLE
esp32 和micropython的fat文件系统冲突 (IDFGH-8026)

### ISSUE THREAD

**Issue by Zhengqinze05** [espressif/esp-idf#9535]
我想使用esp32和micropython文件系统，但是esp32和micropython的文件系统存在冲突，无法同时使用。我需要使用fat文件格式的文件系统。
当我启用了fatfs组件之后，发现存在函数重定义的问题。然后我就发现了esp32和micropython的都有自己的文件系统，且不能共存。但是micropython的文件系统我必须启动，并且在micropython启动前先使用esp32的文件系统读取文件，可是因为有冲突问题，我无法使用esp32自带的fatfs文件系统，请问有什么方法可以同时使用两个系统的fat文件系统功能吗。

**Comment by adokitkat** [comment]
Hello, I am not quite sure if I understand what you want to do and if you're using ESP-IDF or Micropython (with Micropython I don't think we can help much here). However if I download Micropython from official website, setup it and follow the documentation on VFS and FATFS (you can format the flash to FATFS in REPL), it just works.  Closing this issue for now, if you have any other questions you can reopen it.
