### ISSUE TITLE
ESP-NOW does not prevent replay attacks (IDFGH-8037)

### ISSUE THREAD

**Issue by ceribus** [espressif/esp-idf#9544]
## Environment

- Module or chip used:  ESP32 & ESP32-C3
- IDF version: v4.4.1 & v4.4.2
- Operating System: Linux

## Problem Description

The ESP-NOW protocol does not prevent message replay with encrypted messages.

### Expected Behavior

Replayed messages should be ignored.

### Steps to reproduce

Use two devices to reproduce the replay attack using the firmware and script from https://github.com/ceribu/esp-now-replay
This was only tested on ESP32 and ESP32-C3 using IDF v4.4.1 and v4.4.2.

**Comment by zhangyanjiaoesp** [comment]
> While testing some other stuff on ESP-NOW i discovered that you can't replay frames when the retry bit is set. So the replay protection does seem to work but only on retransmitted frames?

Yes, you are right.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to short of feedback, feel free to reopen with more updates.

**Comment by zhangyanjiaoesp** [comment]
@ceribus Since we have explained in the [last comment](https://github.com/espressif/esp-idf/issues/9544#issuecomment-1219249517) what kind of replay attacks are currently supported to prevent, and the issue hasn't been updated for a long time, we closed it. If your request is to support all replay attacks for ESPNOW, we'll reopen the issue and then we'll consider to add this feature as soon as possible.

**Comment by zhangyanjiaoesp** [comment]
@ceribus Thanks for your explanation. We will  fix the problem scenario you described and update the docs.

**Comment by zhangyanjiaoesp** [comment]
@ceribus I have changed the espnow code based on the IDF v4.4.2 (commit 1b16ef6cfc2479a08136782f9dc57effefa86f66), please use the attched wifi lib to test if it can solve your problem, thanks.

replace the wifi lib in the `idf/components/esp_wifi/lib` folder.
[wifi_lib_0629.zip](https://github.com/espressif/esp-idf/files/11904567/wifi_lib_0629.zip)
wifi firmware version: c1a7486

**Comment by AmirHmZz** [comment]
@zhangyanjiaoesp can you please explain how did you try to fix that? I mean techninal details...

**Comment by zhangyanjiaoesp** [comment]
> Thank you very much for the fix! I am currently quite busy and will have a closer look at the changes some time next week.

@ceribus Have you tested the fix?

**Comment by zhangyanjiaoesp** [comment]
@ceribus Yes, you are right. Since ESP-NOW  is not connected, the security is not as perfect as wifi connection, we implement the buffer to save random values in order to ensure as much security as possible, but it can't cover all situations, maybe we need to find a better solution.

**Comment by zhangyanjiaoesp** [comment]
@ceribus 
> You could include a warning about the susceptibility to replay attacks to the documentation.

yes, we will update the documentation.

> Perhaps the handshake from the ESP-NOW Component (https://github.com/espressif/esp-now) could be used by default for encrypted communication with ESP-NOW protocol. This would make it much easier, as you can simply use sequence numbers to prevent replay attacks after the handshake.

Do you mean the handshake in the [security example](https://github.com/espressif/esp-now/tree/master/examples/security) ?

**Comment by Sherry616** [comment]
Thanks for reporting, will close due to short of feedback, feel free to reopen with more updates. 
Thanks for using our Espressif product!
