### ISSUE TITLE
ESP-NOW: encrypted messages from unknown peers are ignored but acknowledged (IDFGH-8040)

### ISSUE THREAD

**Issue by ceribus** [espressif/esp-idf#9545]
## Environment

- Module or chip used: ESP32 & ESP32-C3
- IDF version: v4.4.1 & v4.4.2
- Operating System: Linux

## Problem Description

If a device receives an encrypted ESP-NOW message from another device that is not on the peer list, the message will be acknowledged but is ignored.
The device that sent the message does not know that the message was ignored.

### Expected Behavior

If a device receives an encrypted ESP-NOW message from another device that is not on the peer list, the message should not be acknowledged.

### Actual Behavior

Device A (left side) has Device B (right side) on its peer list and sends encrypted messages to Device B.
Device B does not have Device A on its peer list and does not receive the messages but still sends an ACK.
Device A does not know that the messages are ignored.
![image](https://user-images.githubusercontent.com/20140455/184118377-dbfcc815-7aea-4b20-9b4c-232271753875.png)

Wireshark Capture:  
![image](https://user-images.githubusercontent.com/20140455/184118451-952914cf-9787-49a6-a55d-bb7212c0a6e1.png)

**Comment by zhangyanjiaoesp** [comment]
@ceribu Can you provide your test code? I have tested locally, Device A returned error when sending espnow data to Device B in the scenario you described.

**Comment by zhangyanjiaoesp** [comment]
@ceribu

> Device A (left side) has Device B (right side) on its peer list and sends encrypted messages to Device B.
Device B does not have Device A on its peer list and does not receive the messages but still sends an ACK.

The ACK message is answered by the hardware, it means Device B receives a packets whose DA is same to B's mac address, the hardware won't send the packets to the software.

**Comment by zhangyanjiaoesp** [comment]
> However, with my code example, the sender does not receive an error message.
you can handle it in your APP layer, when you don't receive packets, send error message to the sender.

**Comment by wuyuanyi135** [comment]
@zhangyanjiaoesp if the APP rx callback is not triggered, how can it know a packet was dropped?
