### ISSUE TITLE
Errors not showing in v4.4.2 but do in v4.4.1 (IDFGH-8046)

### ISSUE THREAD

**Issue by versamodule** [espressif/esp-idf#9550]
Moved to a new PC and installed VSC and added ESP-IDF VS Code Extension.
Everything works fine but it no longer shows errors.  No squiggles, and on the file/folder tree the file with the issue does not turn red. 
Uninstalling v4.4.2 and installing v4.4.1 everything works fine.  Going back to 4.4.2 again, same problem comes back. Same thing happens using the master branch.  
Using blink example. 

Here is v4.4.1 with blink examples and error placed. 
![v4 4 1](https://user-images.githubusercontent.com/6456652/184511072-51691688-0c86-4136-a640-ae87aeca7583.png)

Here is v4.4.2 with blink examples and error placed. 
![v4 4 2](https://user-images.githubusercontent.com/6456652/184511077-0890d169-bd7c-431f-b673-c6f60cf85c86.png)

**Comment by versamodule** [comment]
No change, same problem.

**Comment by brianignacio5** [comment]
We've made some fixes in [this PR](https://github.com/espressif/vscode-esp-idf-extension/pull/779) ! Could you try this [vsix installer](https://nightly.link/espressif/vscode-esp-idf-extension/actions/artifacts/331310595.zip)

Related link: [how to Install extension from vsix](https://code.visualstudio.com/docs/editor/extension-marketplace#_install-from-a-vsix)

**Comment by versamodule** [comment]
ESP-IDF VS Code Extension was updated to version 1.5.0. 
Now its showing the errors again.
