### ISSUE TITLE
ESP32-C3 returns wakeup cause that is for light sleep when leaving deep sleep? (IDFGH-8064)

### ISSUE THREAD

**Issue by Kampi** [espressif/esp-idf#9567]
## Environment

- Development Kit:      esp32-c3-devkitm-1
- Module or chip used:  ESP32-C3
- IDF version (run ``git describe --tags`` to find it): 4.4.1
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it): 8.4.0+2021r2-patch3

## Problem Description

ESP32-C3 wakes up from deep sleep by using a GPIO. `esp_sleep_get_wakeup_cause` returns `7` which stands for `ESP_SLEEP_WAKEUP_GPIO` which is documented as "light sleep only".

Is this a documentation issue or is this the wrong wakeup cause?

**Comment by ESP-Marius** [comment]
Hi,

You are right, the docs are wrong here. C3/C2 do support `ESP_SLEEP_WAKEUP_GPIO` from deep sleep (see `SOC_GPIO_SUPPORT_DEEPSLEEP_WAKEUP`)

I'll update the docs to reflect this.
