### ISSUE TITLE
Android/iOS doesnt want to connect to ESP32 SoftAP, after ESP32 made cloud connection when ESP32 was in Station mode.. (IDFGH-8065)

### ISSUE THREAD

**Issue by Irfan93** [espressif/esp-idf#9568]
## Environment

- Development Kit: Custom 
- Kit version 
- Module or chip used:  ESP32-WROOM-32D
- IDF version (run ``git describe --tags`` to find it): v4.3.2 release
- Build System:        CMake | IDF.PY
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it): xtensa-esp32-elf-gcc (crosstool-NG esp-2021r1) 8.4.0
- Operating System:     Linux Kubuntu 22.04
- (Windows only) environment type: 
- Using an IDE?: No
- Power Supply:         External

## Problem Description

ESP32 works well as in AP mode for both android/iOS devices without issues. Successful connection to AP without internet access.
ESP32 in Station Mode, gets internet access and later cloud access through MQTT. The device was assigned to a user on cloud requiring custom certification.
Once disconnected from internet/cloud, ESP32 back in AP mode but the android/iOS devices no longer are able to connect to it.

I guess my main question is, it seems like my android/iOS devices are initializing the disconnection to the ESP32 AP but when I tried connecting to the AP from my Linux, Kubuntu, it is successfully connecting. These may completely be an android/iOS mobile devices behavior. Do anyone know what is the issue here? 

This is definitely doesn't seem like a software issue as I am flashing these ESP32 after an erase all, and right out of the boot up, the android/iOS doesn't want to connect to it even though this worked before this device ever made a cloud connection. The cloud connection seem to have changed something, I just am hoping someone could point me in the right direction.

### Expected Behavior
ESP32 in AP mode should connect successfully to the clients like android and iOS. 

### Actual Behavior
ESP32 in AP mode. Android/iOS tries to reconnect again and again, occasionally manages to get IP address before disconnecting. These devices even when esptool.py erase flash is applied and the software is flashed again, it never works in AP again.

## Debug Logs
Successful connection to the AP:
```
Connected to device. Can't provide internet. / f =2412
98:f4:ab:80:d8:d1 standard =4
rssi = -33 score = 60 tx=1.3,
0.4,0.0 rx=0.6 isValidated:false,
isDefaultNetwork:true,
isLowQuality:false[(1)
{98:f4:ab:80:d8:d1*=2412,-33,0s};;;]
(NETWORK_SELECTION_PERMENANTLY_DISABLED)

Previous WiFiNetwork(2): 08-16 10:46:08.960,onCapabilitiesChanged: network=208,networkCapabilities=[ Transports: WIFI Capabilities: NOT_METERED&INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN&NOT_ROAMING&FOREGROUND&NOT_CONGESTED&NOT_SUSPENDED&NOT_VCN_MANAGED LinkUpBandwidth>=12000Kbps LinkDnBandwidth>=30000Kbps TransportInfo: <SSID: "CLM-tstat-2810", BSSID: 98:f4:ab:80:d8:d1, MAC: 02:00:00:00:00:00, Security type: 0, Supplicant state: COMPLETED, Wi-Fi standard: 4, RSSI: -34, Link speed: 52Mbps, Tx Link speed: 52Mbps, Max Supported Tx Link speed: 150Mbps, Rx Link speed: 65Mbps, Max Supported Rx Link speed: 150Mbps, Frequency: 2412MHz, Net ID: 66, Metered hint: false, score: 60, isUsable: true, CarrierMerged: false, SubscriptionId: -1, IsPrimary: 1> SignalStrength: -34 SSID: "CLM-tstat-2810" UnderlyingNetworks: Null]
```

Unsuccessful connection to the AP:
```
Saved/No internet access /[(1)
{8c:ce:4e:87:af:b5=2412,-39,0s}:::]
(NETWORK_SELECTION_TEMPORARY_DISABLED 461239:41:34)
NETWORK_SELECTION_DISABLED_NO_INTERNET_TEMPORARY=1

Previous WiFiNetwork(3): 08-16 09:35:56.041,onCapabilitiesChanged: network=198,networkCapabilities=[ Transports: WIFI Capabilities: NOT_METERED&INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN&NOT_ROAMING&FOREGROUND&NOT_CONGESTED&NOT_SUSPENDED&NOT_VCN_MANAGED LinkUpBandwidth>=12000Kbps LinkDnBandwidth>=30000Kbps TransportInfo: <SSID: "CLM-tstat-6043", BSSID: 8c:ce:4e:87:af:b5, MAC: 02:00:00:00:00:00, Security type: 0, Supplicant state: COMPLETED, Wi-Fi standard: 4, RSSI: -30, Link speed: 72Mbps, Tx Link speed: 72Mbps, Max Supported Tx Link speed: 150Mbps, Rx Link speed: 72Mbps, Max Supported Rx Link speed: 150Mbps, Frequency: 2412MHz, Net ID: 65, Metered hint: false, score: 0, isUsable: true, CarrierMerged: false, SubscriptionId: -1, IsPrimary: 1> SignalStrength: -30 SSID: "CLM-tstat-6043" UnderlyingNetworks: Null]
```

**Comment by nishanth-radja** [comment]
@Irfan93 can we get a wireless sniffer capture when the android device is not associating to the soft AP.Also console logs on the esp32 will be helpful

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to short of feedback, feel free to reopen with more updates. Thanks.
