### ISSUE TITLE
ESP_BLE_GAP_SET_EXT_ADV_PROP_ANON_ADV (IDFGH-8068)

### ISSUE THREAD

**Issue by chegewara** [espressif/esp-idf#9571]
Cant set scan response with `ESP_BLE_GAP_SET_EXT_ADV_PROP_ANON_ADV` type:
```
E (843) BT_BTM: LE EA SetScanRspData: cmd err=0x12
```
Comment in header says:
`// Omit advertiser's address from all PDUs ("anonymous advertising")`

- idf v4.4 (arduino)
- board: S3 devkit

PS the same error i am getting with type `ESP_BLE_GAP_SET_EXT_ADV_PROP_CONNECTABLE`

Thanks

BTW one more question
is it possible to set advertising data with `esp_ble_gap_config_ext_adv_data_raw` when type is scannable, or is it only possible with legacy type?

**Comment by esp-cjh** [comment]
Hi @chegewara ，
Refer to Core Spec 5.2 Vol4 PartE 7.8.54 and 7.8.55.
The ext adv is non-scannable when type set to ESP_BLE_GAP_SET_EXT_ADV_PROP_ANON_ADV or ESP_BLE_GAP_SET_EXT_ADV_PROP_CONNECTABLE. You can't set scan response data but you can set adv data with `esp_ble_gap_config_ext_adv_data_raw()`.
When type is scannable, you can't set advertising data but you can set scan response data with `esp_ble_gap_config_ext_scan_rsp_data_raw()`.
