### ISSUE TITLE
ESP32S2 ADC DMA IRQ buffer size half the size of expected (IDFGH-8070)

### ISSUE THREAD

**Issue by jwasys** [espressif/esp-idf#9573]
In the driver, the SPI3 dma is configured for a block size half of what is expected

Due to:
components\driver\adc.c: 283:
        .eof_num = init_config->conv_num_each_intr / ADC_HAL_DATA_LEN_PER_CONV

Where ADC_HAL_DATA_LEN_PER_CONV euqals 4 which is the case for ESP32 but not for ESP32 S2

Fix would be to #define ADC_HAL_DATA_LEN_PER_CONV 2 for at least S2 but I think also for C3, S3 and H2.

**Comment by Icarus113** [comment]
@jwasys  Hi, this is fixed on v4.4, see [this](https://github.com/espressif/esp-idf/blob/release/v4.4/components/driver/adc.c#L283)

**Comment by jwasys** [comment]
Thanks !
