### ISSUE TITLE
ESP-NOW: invalid length causes the message buffer to be dumped into receive callback (IDFGH-8073)

### ISSUE THREAD

**Issue by ceribus** [espressif/esp-idf#9576]
## Environment

- Chip used: ESP32-C3
- IDF version: v4.4.2

## Problem Description

If the length in the vendor specific ie used by esp now is lower than 5 (which is the length of the oui, type and version), the whole content of the message buffer is dumped into the receive callback

![image](https://user-images.githubusercontent.com/20140455/185242359-e0b41ebc-3a0d-4d72-b3e3-0cc9fc802e35.png)
![image](https://user-images.githubusercontent.com/20140455/185242082-896d6f76-feaa-48f9-af5a-55f3f7fb10dd.png)

### Steps to reproduce
Use the firmware and scripts from https://github.com/ceribu/esp-now-header-validation/blob/main/invalid-length.py

**Comment by zhangyanjiaoesp** [comment]
https://github.com/espressif/esp-idf/commit/5a354837a83fb0aba4261d6d2aaeb20725abc49f can solve this issue
