### ISSUE TITLE
Can't send Thread messages using CoAP from OpenThread border router (IDFGH-8083)

### ISSUE THREAD

**Issue by ShawnDSP** [espressif/esp-idf#9584]
## Environment

- Development Kit:      ESP32-DevKitC
- Kit version (for WroverKit/PicoKit/DevKitC): v4
- Module or chip used:  ESP32-WROOM-32UE
- IDF version (run ``git describe --tags`` to find it): v5.0-dev-2443-g047903c612
- Build System:         idf.py
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it):  xtensa-esp32-elf-gcc (crosstool-NG esp-2021r2-patch3) 8.4.0
- Operating System:     Windows
- (Windows only) environment type: Plain Command Prompt
- Using an IDE?: Yes (used IDE to create project, everything else done at command prompt)
- Power Supply:         USB

I am using a Nordic nRF52840-Dongle as the radio coprocessor for the otbr (ESP32 H2 is not available to me). The nRF part is connected via UART to the ESP32. And I am using another Nordic nRF52840-dongle as a Thread device to communicate with (programmed with the Thread CLI sample program). I am using Nordic nRF Connect SDK version 1.9.1.

## Problem Description

When using the ESP32 as an OpenThread border router and communicating to another device in the Thread network, it is not possible to send CoAP packets from the ESP32 to the other device using the other device's IP address.

### Expected Behavior

A CoAP GET message is sent and a reply is received.

### Actual Behavior

When a CoAP message is sent from the ESP32 border router, no reply is received and eventually a timeout occurs. 

Using a 802.15.4 packet sniffer (with Wireshark) shows that no packet is sent over the air from the ESP32 otbr.

It is possible to send CoAP messages from another Thread device to the ESP32 without problems. It is also possible to send CoAP messages from the ESP32 otbr if a multicast address is used (ff02::1). Furthermore, pinging between the two devices works fine.

Note that the behaviour is not specific to CoAP, but is also a problem if "UDP" commands are used at the CLI to send a packet.

### Steps to reproduce

1. Program the nRF52 dongle as an RCP and connect via UART to ESP32 DevKitC (see photo below)
2. Create a new project using the openthread/ot_br example as a template (I did this using Eclipse plug-in)
3. Run idf.py menuconfig and set the WiFi SSID and password, plus select "Enable the automatic start mode in Thread Border Router"
4. Build, flash and run the program.
5. Commission the nRF52 Thread device following the instructions from the otbr example (running ot-commissioner program in Linux)
6. On the nRF52 get the available IP addresses and make note for later: ot ipaddr
7. Start CoAP: ot coap start
8. Create a resource to get: ot coap resource test
9. On the ESP32 otbr start CoAP: coap start
10. Attempt to get the resource: coap get <ip_addr> test
11. The GET attempt times out.

![image](https://user-images.githubusercontent.com/66505741/185473539-e83ec603-9a01-4b22-90b9-e9d22e4caafb.png)

### Code to reproduce this issue

Example code has not been modified.

## Debug Logs

rst:0x1 (POWERON_RESET),boot:0x17 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:6984
load:0x40078000,len:15184
load:0x40080400,len:3820
0x40080400: _init at ??:?

entry 0x40080698
I (27) boot: ESP-IDF v5.0-dev-2443-g047903c612 2nd stage bootloader
I (27) boot: compile time 08:52:06
I (27) boot: chip revision: 3
I (32) boot_comm: chip revision: 3, min. bootloader chip revision: 0
I (39) boot.esp32: SPI Speed      : 40MHz
I (43) boot.esp32: SPI Mode       : DIO
I (48) boot.esp32: SPI Flash Size : 2MB
I (53) boot: Enabling RNG early entropy source...
I (58) boot: Partition Table:
I (62) boot: ## Label            Usage          Type ST Offset   Length
I (69) boot:  0 nvs              WiFi data        01 02 00009000 00006000
I (76) boot:  1 phy_init         RF data          01 01 0000f000 00001000
I (84) boot:  2 factory          factory app      00 00 00010000 0015e000
I (91) boot:  3 ot_storage       Unknown data     01 3a 0016e000 00002000
I (99) boot: End of partition table
I (103) boot_comm: chip revision: 3, min. application chip revision: 0
I (110) esp_image: segment 0: paddr=00010020 vaddr=3f400020 size=2f200h (193024) map
I (189) esp_image: segment 1: paddr=0003f228 vaddr=3ffb0000 size=00df0h (  3568) load
I (190) esp_image: segment 2: paddr=00040020 vaddr=400d0020 size=e3a14h (932372) map
I (532) esp_image: segment 3: paddr=00123a3c vaddr=3ffb0df0 size=02ddch ( 11740) load
I (536) esp_image: segment 4: paddr=00126820 vaddr=40080000 size=15528h ( 87336) load
I (573) esp_image: segment 5: paddr=0013bd50 vaddr=50000000 size=00010h (    16) load
I (584) boot: Loaded app from partition at offset 0x10000
I (584) boot: Disabling RNG early entropy source...
I (596) cpu_start: Pro cpu up.
I (596) cpu_start: Starting app cpu, entry point is 0x400812a8
0x400812a8: call_start_cpu1 at E:/Projects/139/esp-idf/components/esp_system/port/cpu_start.c:152

I (0) cpu_start: App cpu up.
I (612) cpu_start: Pro cpu start user code
I (612) cpu_start: cpu freq: 160000000 Hz
I (612) cpu_start: Application information:
I (617) cpu_start: Project name:     otbr
I (622) cpu_start: App version:      4ecd1d6-dirty
I (627) cpu_start: Compile time:     Aug 18 2022 09:06:58
I (633) cpu_start: ELF file SHA256:  510c386cbc25e2bd...
I (639) cpu_start: ESP-IDF:          v5.0-dev-2443-g047903c612
I (646) heap_init: Initializing. RAM available for dynamic allocation:
I (653) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM
I (659) heap_init: At 3FFC0E68 len 0001F198 (124 KiB): DRAM
I (665) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM
I (672) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
I (678) heap_init: At 40095528 len 0000AAD8 (42 KiB): IRAM
I (685) spi_flash: detected chip: generic
I (689) spi_flash: flash io: dio
W (693) spi_flash: Detected size(4096k) larger than the size in the binary image header(2048k). Using the size in the binary image header.
I (707) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.
I (766) wifi:wifi driver task: 3ffc971c, prio:23, stack:6656, core=0
I (766) system_api: Base MAC address is not set
I (766) system_api: read default base MAC address from EFUSE
I (776) wifi:wifi firmware version: 0a41108
I (776) wifi:wifi certification version: v7.0
I (776) wifi:config NVS flash: enabled
I (776) wifi:config nano formating: disabled
I (786) wifi:Init data frame dynamic rx buffer num: 32
I (786) wifi:Init management frame dynamic rx buffer num: 32
I (796) wifi:Init management short buffer num: 32
I (796) wifi:Init dynamic tx buffer num: 32
I (806) wifi:Init static rx buffer num: 10600
I (806) wifi:Init dynamic rx buffer num: 32
I (816) wifi_init: rx ba win: 6
I (816) wifi_init: tcpip mbox: 32
I (826) wifi_init: udp mbox: 6
I (826) wifi_init: tcp mbox: 6
I (826) wifi_init: tcp tx win: 5744
I (836) wifi_init: tcp rx win: 5744
I (836) wifi_init: tcp mss: 1440
I (846) wifi_init: WiFi IRAM OP enabled
I (846) wifi_init: WiFi RX IRAM OP enabled
I (856) example_connect: Connecting to SSID...
I (856) phy_init: phy_version 4670,719f9f6,Feb 18 2021,17:07:07
I (956) wifi:mode : sta (e0:e2:e6:b2:f6:d8)
I (966) wifi:enable tsf
I (966) example_connect: Waiting for IP(s)
I (3016) wifi:new:<6,0>, old:<1,0>, ap:<255,255>, sta:<6,0>, prof:1
I (3756) wifi:state: init -> auth (b0)
I (3766) wifi:state: auth -> assoc (0)
I (3766) wifi:state: assoc -> run (10)
I (3776) wifi:connected with APD Burnaby, aid = 7, channel 6, BW20, bssid = 7c:5a:1c:86:0d:40
I (3776) wifi:security: WPA2-PSK, phy: bgn, rssi: -48
I (3776) wifi:pm start, type: 1

W (3786) wifi:<ba-add>idx:0 (ifx:0, 7c:5a:1c:86:0d:40), tid:0, ssn:0, winSize:64
I (3846) wifi:AP's beacon interval = 102400 us, DTIM period = 1
I (4756) esp_netif_handlers: example_connect: sta ip: 192.168.1.175, mask: 255.255.255.0, gw: 192.168.1.1
I (4756) example_connect: Got IPv4 event: Interface "example_connect: sta" address: 192.168.1.175
I (5756) example_connect: Got IPv6 event: Interface "example_connect: sta" address: fe80:0000:0000:0000:e2e2:e6ff:feb2:f6d8, type: ESP_IP6_ADDR_IS_LINK_LOCAL
I (5756) example_connect: Connected to example_connect: sta
I (5766) example_connect: - IPv4 address: 192.168.1.175
I (5766) example_connect: - IPv6 address: fe80:0000:0000:0000:e2e2:e6ff:feb2:f6d8, type: ESI(5796) OPENTHREAD:[I] Platform------: RCP reset: RESET_POWER_ON
I(5826) OPENTHREAD:[N] Platform------: RCP API Version: 5
I(6236) OPENTHREAD:[I] Settings------: Read NetworkInfo {rloc:0xa400, extaddr:663ee82c24b365ed, role:leader, mode:0x0f, version:3, keyseq:0x0, ...
I(6246) OPENTHREAD:[I] Settings------: ... pid:0x44393eba, mlecntr:0xfab, maccntr:0xfa0, mliid:1f35c510596ff02c}
I (6266) OPENTHREAD: OpenThread attached to netif
> I(6276) OPENTHREAD:[N] BorderRouter--: Local OMR prefix: fda4:b8f7:f09f:fbb5::/64 (loaded)
I(6286) OPENTHREAD:[N] BorderRouter--: Local on-link prefix: fd71:e416:17cd:0::/64 (loaded)
I (6296) esp_ot_br: Already has network, skip configuring OpenThread network.
W (6306) example_connect: Got IPv6 from another netif: ignored
I (6316) OPENTHREAD: Platform UDP bound to port 49153
I(6316) OPENTHREAD:[N] Mle-----------: Role disabled -> detached
W (6406) example_connect: Got IPv6 from another netif: ignored
W (6406) example_connect: Got IPv6 from another netif: ignored
I (6406) OPENTHREAD: Platform UDP bound to port 61631
I (6416) OPENTHREAD: netif up
> I(6656) OPENTHREAD:[N] Mle-----------: Role detached -> leader
I(6666) OPENTHREAD:[N] Mle-----------: Leader partition id 0x44393eba
I (6686) OPENTHREAD: Platform UDP bound to port 49154
W (6686) example_connect: Got IPv6 from another netif: ignored
W (6756) example_connect: Got IPv6 from another netif: ignored
W (6766) example_connect: Got IPv6 from another netif: ignored
W (6926) OPENTHREAD: Dropping unsupported mldv2 record of type 2
W (6926) OPENTHREAD: Dropping unsupported mldv2 record of type 2
W (6926) OPENTHREAD: Dropping unsupported mldv2 record of type 2
W (6936) OPENTHREAD: Dropping unsupported mldv2 record of type 2
W (6956) OPENTHREAD: Dropping unsupported mldv2 record of type 2
W (6956) OPENTHREAD: Dropping unsupported mldv2 record of type 2
W (6966) OPENTHREAD: Dropping unsupported mldv2 record of type 2
W (7136) OPENTHREAD: Dropping unsupported mldv2 record of type 2
W (7136) OPENTHREAD: Dropping unsupported mldv2 record of type 2
W (7136) OPENTHREAD: Dropping unsupported mldv2 record of type 2
W (7166) example_connect: Got IPv6 from another netif: ignored
W (7336) OPENTHREAD: Dropping unsupported mldv2 record of type 2
W (7356) OPENTHREAD: Dropping unsupported mldv2 record of type 2
W (7356) OPENTHREAD: Dropping unsupported mldv2 record of type 2
W (7356) OPENTHREAD: Dropping unsupported mldv2 record of type 2
W (7436) OPENTHREAD: Dropping unsupported mldv2 record of type 2
W (7436) OPENTHREAD: Dropping unsupported mldv2 record of type 2
W (7436) OPENTHREAD: Dropping unsupported mldv2 record of type 2
W (7446) OPENTHREAD: Dropping unsupported mldv2 record of type 2
W (7536) OPENTHREAD: Dropping unsupported mldv2 record of type 2
W (7536) OPENTHREAD: Dropping unsupported mldv2 record of type 2
W (7546) OPENTHREAD: Dropping unsupported mldv2 record of type 2
W (7746) OPENTHREAD: Dropping unsupported mldv2 record of type 2
W (7746) OPENTHREAD: Dropping unsupported mldv2 record of type 2
W (7746) OPENTHREAD: Dropping unsupported mldv2 record of type 2
W (7766) OPENTHREAD: Dropping unsupported mldv2 record of type 2
W (7766) OPENTHREAD: Dropping unsupported mldv2 record of type 2
W (7776) OPENTHREAD: Dropping unsupported mldv2 record of type 2
W (7846) OPENTHREAD: Dropping unsupported mldv2 record of type 2
W (7846) OPENTHREAD: Dropping unsupported mldv2 record of type 2
W (7846) OPENTHREAD: Dropping unsupported mldv2 record of type 2
W (7866) OPENTHREAD: Dropping unsupported mldv2 record of type 2
W (7866) OPENTHREAD: Dropping unsupported mldv2 record of type 2
W (7876) OPENTHREAD: Dropping unsupported mldv2 record of type 2
W (7876) OPENTHREAD: Dropping unsupported mldv2 record of type 2
W (7886) OPENTHREAD: Dropping unsupported mldv2 record of type 2
W (7886) OPENTHREAD: Dropping unsupported mldv2 record of type 2
W (7896) OPENTHREAD: Dropping unsupported mldv2 record of type 2
W (7916) OPENTHREAD: Dropping unsupported mldv2 record of type 2
W (7916) OPENTHREAD: Dropping unsupported mldv2 record of type 2
I (10166) OPENTHREAD: Platform UDP bound to port 53535
W (10176) example_connect: Got IPv6 from another netif: ignored
I (16356) OPENTHREAD: Received PIO
I (16416) OPENTHREAD: Received PIO
coap start
I (28596) OPENTHREAD: Platform UDP bound to port 5683
Done
> coap get fda4:b8f7:f09f:fbb5:5e36:f1d9:ac58:4972 test
Done
> coap receive response error 28: ResponseTimeout
coap get ff02::1 test
Done
> coap response from fe80:0:0:0:f4da:e484:bb88:db5a with payload: 30

## Other items if possible

[sdkconfig.txt](https://github.com/espressif/esp-idf/files/9376910/sdkconfig.txt)

**Comment by zwx1995esp** [comment]
Hi, @ShawnDSP your esp-idf code base commit ID is a little old.  Since April, we have already updated the lib of Openthread stack for several times. So could you please update the esp-idf branch and try if there is the same issue with the newest code?

**Comment by ShawnDSP** [comment]
Hi. I just tried the latest on the master branch (version v5.1-dev-303-g2b1bee166d) and I can't get the ot_br example to build. I get the following error:

```
CMake Error at E:/Projects/139/coap_problem_idf/esp-idf/tools/cmake/project.cmake:243 (message):
  Directory specified in EXTRA_COMPONENT_DIRS doesn't exist:
  E:/Projects/139/coap_problem_idf/esp-idf/examples/openthread/extension_command
```

I am missing the "extension_command" folder in esp-idf for the openthread examples.

**Comment by ShawnDSP** [comment]
Please ignore the last comment. I used the project generator in the Eclipse plug-in and the example code was not up to date. I have directly copied the ot_br example from esp-idf and it is building fine. I will report on my findings once I have done some testing.

**Comment by ShawnDSP** [comment]
The CoAP GET problem is not there with the newest code. I am closing this issue.
