### ISSUE TITLE
make monitor outputs gibberish characters (like wrong buad rate) 

### ISSUE THREAD

**Issue by pkramer509** [espressif/esp-idf#959]
This happens on both Linux and Windows; baud rate is set in makemenu to the default 115200.

I compiled and flashed an unmodified version of esp-idf-template.

I connected a FT231X onto the external UART0 pins and typed some characters into the monitor app all of which showed up fine. 

![make monitor output](https://user-images.githubusercontent.com/6434845/30063847-9a235160-9215-11e7-9617-76558a2de907.png)

**Comment by igrr** [comment]
If your board is equipped with a 26MHz crystal, you need to modify your sdkconfig (by running `make menuconfig`). By default, XTAL frequency is set to 40MHz.

**Comment by pkramer509** [comment]
Yep, that was it; thanks!
