### ISSUE TITLE
esp.emac: no mem for receive buffer (IDFGH-8093)

### ISSUE THREAD

**Issue by SERIDJ** [espressif/esp-idf#9594]

**Comment by king1688** [comment]
I have the same problem when I complie and run the example under /ethernet/eth2ap examples code. if you got a solution, please let me know, thank you

**Comment by kostaond** [comment]
Duplicate of #9308

**Comment by thiagohd** [comment]
Same problem here.

**Comment by kostaond** [comment]
Could you please check if [this WIP update](https://github.com/kostaond/esp-idf/tree/feature/emac_buff_optimization) helped to resolve your issue?
