### ISSUE TITLE
Method to know if the radio has stopped transmitting (IDFGH-8105)

### ISSUE THREAD

**Issue by doragasu** [espressif/esp-idf#9605]
### Is your feature request related to a problem?

We have an application that does an extensive use of the `esp_wifi_80211_tx()` function. And we have to accurately synchronize the end of the WiFi transmission with other actions. We have observed that when the `esp_wifi_80211_tx()` returns, transmission usually has not yet finished (we suppose when you call this function, data to transmit is enqueued for transmission, but not necessarily sent when the function returns), and we would like to know exactly when the transmission ends, to synchronize the end of transmission with other actions the application has to take.

### Describe the solution you'd like.

It would be enough having a function like `bool esp_wifi_80211_tx_is_active()` that will tell you if the radio is active or has pending data queued for transmission (return `true`) or is idle and no data for transmission is queued (return `false`). By polling this function the application could know if all the data has been sent.

### Describe alternatives you've considered.

An alternative mechanism could be setting a callback that will be run when the `esp_wifi_80211_tx()` function has finished sending the data and the radio is idle.

Another alternative could be having an option for the `esp_wifi_80211_tx()` not to return until all data has been transmitted.

**Comment by MaxwellAlan** [comment]
Hi @doragasu 

Thanks for the feature request. 

Could you provide some more details about the usage scenario ? And did you enable station or softap or sniffer mode ? etc.
It's helpful for us to optimize our esp_wifi_80211_tx api.


Thanks.

**Comment by doragasu** [comment]
Hi @MaxwellAlan,

Thanks a lot for support.

We are developing an application in which we use Espressif devices to talk to some in-house developed smart tags. We configure an ESP32 in AP mode, but we do not associate any station to it, and use the `esp_wifi_80211_tx()` function to send some specific frames of our own proprietary protocol, that is interpreted by the smart tag.

In some scenarios, the protocol data we send using the `esp_wifi_80211_tx()` must be synchronized with some specific charge pulses we send in other RF band (e.g. 800/900 MHz like RFID equipment typically does). Due to some limitations in the smart tag HW, we cannot send simultaneously the WiFi data and the charge signal, they have to take turns. So, in order to optimize the switching between WiFi data and charge signal (to optimize throughput and minimize latency), we need to accurately detect when the ESP32 has finished sending data, to quickly switch to the charge signal.

Again, thanks for support. Hope this helps understanding the use case for this feature.

**Comment by negativekelvin** [comment]
https://github.com/espressif/esp-idf/issues/7904

**Comment by doragasu** [comment]
Oh, there's already a `esp_wifi_set_tx_done_cb()`, this might be what I need, I'll give it a try and come back, thanks!

**Comment by MaxwellAlan** [comment]
Hi @doragasu 

Yes, you can try this callback, this callback will trigger when your pkts tx success.

**Comment by doragasu** [comment]
Thanks, I was going to test now but I have a question. If my program registers a tx_done_cb and then in a loop calls 5 times the `esp_wifi_80211_tx()` function, one call just after another, will the tx_done_cb be called 5 times, or just once when the data transmission ends?

**Comment by doragasu** [comment]
Did some tests assuming the `tx_done_cb()` is invoked once for each `esp_wifi_80211_tx()` call, and that internal WiFi functions (like sending beacons) do not trigger the callback, and it is working as expected.

Thanks!
