### ISSUE TITLE
ESP-IDF 5 release date? (IDFGH-8108)

### ISSUE THREAD

**Issue by noahp** [espressif/esp-idf#9608]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Hello-

I was wondering if there's a release date planned for esp-idf v5?

Thanks!
Noah

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, IDF v5.0-beta1 has released a while ago at https://github.com/espressif/esp-idf/releases/tag/v5.0-beta1, will keep you updated on further release. Thanks.
