### ISSUE TITLE
24-bit support for esp_lcd_rgb_panel_config_t::data_width (IDFGH-8125)

### ISSUE THREAD

**Issue by dmartauz** [espressif/esp-idf#9623]
### Describe the solution you'd like.

Ability to drive RGB displays with 24-bit data bus, According to documentation, only 8 and 16-bit buses are supported currently.

Example of such display: https://www.waveshare.com/10.1inch-Capacitive-Touch-LCD-D.htm

**Comment by suda-morris** [comment]
Hi @dmartauz The ESP32S3 RGB LCD controller doesn't support 24bit data lines. It's not a software limitation. 

You can choose an LCD that supports the** SRGB(Serial RGB)** interface if you have to use the RGB888 color format.

There might be an ESP chip that supports up to 24 color data lines in the future.

**Comment by dmartauz** [comment]
@suda-morris Thank you for clarification. I will stay with 16-bit displays for now :)
