### ISSUE TITLE
vfs_fat_spiflash: Failed to find FATFS partition (IDFGH-8142)

### ISSUE THREAD

**Issue by preetjhotavoni** [espressif/esp-idf#9640]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

I am using a custom partition table. After flashing it shows the following error:
vfs_fat_spiflash: Failed to find FATFS partition (type='data', subtype='fat', partition_label='storage'). Check the partition table

My partition table:

nvs,data,nvs,,0x4000,
otadata,data,ota,,0x2000,
phy_init,data,phy,,0x1000,
storage,data,fat,,0x100000,
ota_0,app,ota_0,,0x150000,
ota_1,app,ota_1,,0x150000,

Can anyone please let me know what the error is?

**Comment by igrr** [comment]
@preetjhotavoni The partition table looks okay, it should work with the line of code you have shown. Could you please describe how you build and flash your project? Are you using the command line or an IDE, and what is the process, in detail? Could you also please attach your sdkconfig file and mention the version of IDF (`git describe`) you are using?

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to short of feedback, feel free to reopen with more updates.
