### ISSUE TITLE
MCPWM ESP32-S3 Function: mcpwm_set_duty_in_us (IDFGH-8151)

### ISSUE THREAD

**Issue by misiek1994** [espressif/esp-idf#9648]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

4.4.2

### Operating System used.

Linux

### How did you build your project?

Eclipse IDE

### What is the expected behavior?

Function: mcpwm_set_duty_in_us should set pwm duty to specific value in us.

### What is the actual behavior?

mcpwm_set_duty_in_us is not setting properly pwm.

### Steps to reproduce.

    mcpwm_gpio_init(MCPWM_UNIT_0, MCPWM0A, SERVO_PULSE_GPIO_1);
    mcpwm_config_t pwm_config = {
        .frequency = 50, // frequency = 50Hz, i.e. for every servo motor time period should be 20ms
        .cmpr_a = 0,     // duty cycle of PWMxA = 0
        .counter_mode = MCPWM_UP_COUNTER,
        .duty_mode = MCPWM_DUTY_MODE_1,
    };
    mcpwm_init(MCPWM_UNIT_0, MCPWM_TIMER_0, &pwm_config);

    //doesnt work
    ESP_ERROR_CHECK(mcpwm_set_duty_in_us(MCPWM_UNIT_0, MCPWM_TIMER_0, MCPWM_OPR_A, 10000));
    //works!
    ESP_ERROR_CHECK(mcpwm_set_duty(MCPWM_UNIT_0, MCPWM_TIMER_0, MCPWM_OPR_A, 50.0));

### More Information.

In function:

    esp_err_t mcpwm_set_duty_in_us(mcpwm_unit_t mcpwm_num, mcpwm_timer_t timer_num, mcpwm_generator_t gen,                 uint32_t duty_in_us)
    {
        //the driver currently always use the timer x for operator x
        const int op = timer_num;
        //the driver currently always use the comparator A for PWMxA output, and comparator B for PWMxB output
        const int cmp = gen;
        MCPWM_GEN_CHECK(mcpwm_num, timer_num, gen);
        mcpwm_hal_context_t *hal = &context[mcpwm_num].hal;
    
        mcpwm_critical_enter(mcpwm_num);
        int real_group_prescale = mcpwm_ll_group_get_clock_prescale(hal->dev);
        unsigned long int real_timer_clk_hz =
                SOC_MCPWM_BASE_CLK_HZ / real_group_prescale / mcpwm_ll_timer_get_clock_prescale(hal->dev, timer_num);
        mcpwm_ll_operator_set_compare_value(hal->dev, op, cmp, duty_in_us * real_timer_clk_hz / 1000000);
        mcpwm_ll_operator_enable_update_compare_on_tez(hal->dev, op, cmp, true);
        mcpwm_critical_exit(mcpwm_num);
        return ESP_OK;
    }

Probably overflow in line:     mcpwm_ll_operator_set_compare_value(hal->dev, op, cmp, duty_in_us * real_timer_clk_hz / 1000000);

Changing to: mcpwm_ll_operator_set_compare_value(hal->dev, op, cmp, real_timer_clk_hz / 1000000 * duty_in_us); fixed the problem, but there might be another when real_timer_clk_hz is not multiplication of 1MHz.

**Comment by suda-morris** [comment]
@misiek1994 Nice catch, I can also confirm this is a multiplication overflow. We should use `uint64_t` when converting us to compare ticks.
