### ISSUE TITLE
Private Key verification failed while connecting to AWS (IDFGH-8158)

### ISSUE THREAD

**Issue by Ketan1993** [espressif/esp-idf#9654]
Hi, 
I am using ESP32 device and trying to connecting the AWS cloud with MQTT. I have hardcoded the AWS root , client and client key certificate. When I am doing connection using the hard-core certificate, The connection is fine I am able to connect and publish the data over the MQTT. But hardcoded will work for the particular device only. here I have many ESP32 device with different client and client key certificate. So I have installed all three certificate to the spiffs partition in device, well reading and writing from the file-system is fine. I am able to read and write certificate to file-system but when I use the stored certificate I was not able to connect the AWS MQTT. I found some error. Please have a look.

`<27>[0;32mI (9934) mqtt_inte: Partition size: total: 37901, used: 0<27>[0m<\r><\n>
<27>[0;32mI (9954) mqtt_inte: amazon root file is not avilable<27>[0m<\r><\n>
<27>[0;32mI (9954) mqtt_inte: client cert file is not avilable<27>[0m<\r><\n>
<27>[0;32mI (9954) mqtt_inte: client key file is not avilable<27>[0m<\r><\n>
<27>[0;31mE (9954) mqtt_inte: failed to check the file status<27>[0m<\r><\n>
<27>[0;32mI (9964) mqtt_inte: Partition size: total: 37901, used: 0<27>[0m<\r><\n>
<27>[0;32mI (9964) mqtt_inte: Opening file /spiffs/amazonroot.pem for write<27>[0m<\r><\n>
<27>[0;32mI (9994) mqtt_inte: File written 1188, and file size 1188<27>[0m<\r><\n>
<27>[0;32mI (10004) mqtt_inte: Partition size: total: 37901, used: 1506<27>[0m<\r><\n>
<27>[0;32mI (10004) mqtt_inte: Opening file /spiffs/device.pem for write<27>[0m<\r><\n>
<27>[0;32mI (10074) mqtt_inte: File written 1224, and file size 1224<27>[0m<\r><\n>
<27>[0;32mI (10084) mqtt_inte: Partition size: total: 37901, used: 3012<27>[0m<\r><\n>
<27>[0;32mI (10084) mqtt_inte: Opening file /spiffs/private.pem for write<27>[0m<\r><\n>
<27>[0;32mI (10124) mqtt_inte: File written 1678, and file size 1678<27>[0m<\r><\n>
<27>[0;32mI (10144) mqtt_inte: Opening file /spiffs/amazonroot.pem for read<27>[0m<\r><\n>
<27>[0;32mI (10144) mqtt_inte: file is availbe with size 1188<27>[0m<\r><\n>
<27>[0;32mI (10194) mqtt_inte: Opening file /spiffs/device.pem for read<27>[0m<\r><\n>
<27>[0;32mI (10194) mqtt_inte: file is availbe with size 1224<27>[0m<\r><\n>
<27>[0;32mI (10204) mqtt_inte: Opening file /spiffs/private.pem for read<27>[0m<\r><\n>
<27>[0;32mI (10204) mqtt_inte: file is availbe with size 1678<27>[0m<\r><\n>
<27>[0;32mI (10214) mqtt_inte: compare result for hardcoded root and fs root 0<27>[0m<\r><\n>
<27>[0;32mI (10214) mqtt_inte: compare result for hardcoded client cert and fs cert 0<27>[0m<\r><\n>
<27>[0;32mI (10224) mqtt_inte: compare result for hardcoded client key and fs key 0<27>[0m<\r><\n>
<27>[0;32mI (10224) mqtt_inte: [APP] Free memory: 216088 bytes<27>[0m<\r><\n>
D (10234) MQTT_CLIENT: MQTT client_id=ESP32_180DB8<27>[0m<\r><\n>
D (10244) event: created event loop 0x3ffca530<27>[0m<\r><\n>
D (10244) MQTT_CLIENT: Core selection disabled<27>[0m<\r><\n>
<27>[0;32mI (10244) mqtt_inte: mqtt application is running up<27>[0m<\r><\n>
D (10244) event: running post MQTT_EVENTS:7 with handler 0x400d7f78 and context 0x3ffca668 on loop 0x3ffca530<27>[0m<\r><\n>
D (10264) mqtt_inte: Event dispatched from event loop base=MQTT_EVENTS, event_id=7<27>[0m<\r><\n>
<27>[0;32mI (10274) mqtt_inte: Other event id:7<27>[0m<\r><\n>
D (10274) esp-tls: host:a102luijkrvjy9-ats.iot.ap-south-1.amazonaws.com: strlen 47<27>[0m<\r><\n>
D (10374) esp-tls: [sock=55] Resolved IPv4 address: 65.1.201.136<27>[0m<\r><\n>
D (10374) esp-tls: [sock=55] Connecting to server. HOST: a102luijkrvjy9-ats.iot.ap-south-1.amazonaws.com, Port: 8883<27>[0m<\r><\n>
<27>[0;31mE (10424) esp-tls-mbedtls: mbedtls_pk_parse_keyfile returned -0x3D00<27>[0m<\r><\n>
<27>[0;32mI (10424) esp-tls-mbedtls: (FFFFC300): PK - Invalid key tag or value<27>[0m<\r><\n>
<27>[0;31mE (10424) esp-tls-mbedtls: Failed to set client pki context<27>[0m<\r><\n>
<27>[0;31mE (10434) esp-tls-mbedtls: Failed to set client configurations, returned [0x8019] (ESP_ERR_MBEDTLS_PK_PARSE_KEY_FAILED)<27>[0m<\r><\n>
<27>[0;31mE (10444) esp-tls: create_ssl_handle failed<27>[0m<\r><\n>
<27>[0;31mE (10444) esp-tls: Failed to open new connection<27>[0m<\r><\n>
<27>[0;31mE (10454) TRANSPORT_BASE: Failed to open a new connection<27>[0m<\r><\n>
<27>[0;31mE (10464) MQTT_CLIENT: Error transport connect<27>[0m<\r><\n>
D (10464) event: running post MQTT_EVENTS:0 with handler 0x400d7f78 and context 0x3ffca668 on loop 0x3ffca530<27>[0m<\r><\n>
D (10474) mqtt_inte: Event dispatched from event loop base=MQTT_EVENTS, event_id=0<27>[0m<\r><\n>
<27>[0;32mI (10484) mqtt_inte: MQTT_EVENT_ERROR<27>[0m<\r><\n>
<27>[0;32mI (10484) mqtt_inte: Last error code reported from esp-tls: 0x8019<27>[0m<\r><\n>
<27>[0;32mI (10494) mqtt_inte: Last tls stack error number: 0x3d00<27>[0m<\r><\n>
<27>[0;32mI (10494) mqtt_inte: Last captured errno : 0 (Success)<27>[0m<\r><\n>
D (10504) MQTT_CLIENT: Reconnect after 10000 ms<27>[0m<\r><\n>
D (10504) event: running post MQTT_EVENTS:2 with handler 0x400d7f78 and context 0x3ffca668 on loop 0x3ffca530<27>[0m<\r><\n>
D (10514) mqtt_inte: Event dispatched from event loop base=MQTT_EVENTS, event_id=2<27>[0m<\r><\n>
<27>[0;32mI (10524) mqtt_inte: MQTT_EVENT_DISCONNECTED<27>[0m<\r><\n>
D (10534) MQTT_CLIENT: MQTT client disconnected.<27>[0m<\r><\n>
<27>[0;32mI (11264) mqtt_inte: mqtt application is running up<27>[0m<\r><\n>

`

**Comment by euripedesrocha** [comment]
Hi @Ketan1993, from the error message you have your key saved in an invalid format:
```
<27>[0;31mE (10424) esp-tls-mbedtls: mbedtls_pk_parse_keyfile returned -0x3D00<27>[0m<\r><\n>
<27>[0;32mI (10424) esp-tls-mbedtls: (FFFFC300): PK - Invalid key tag or value<27>[0m<\r><\n>
```

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to short of feedback, feel free to reopen with more updates.
