### ISSUE TITLE
Secure boot check fail  / enabled secure boot v1 without flash encryption  (IDFGH-8159)

### ISSUE THREAD

**Issue by ABHITHLALC** [espressif/esp-idf#9655]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [x] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

esp-idf -release-v4.2 esp32-version

### Operating System used.

Windows

### How did you build your project?

Command line with idf.py

### If you are using Windows, please specify command line type.

PowerShell

### Development Kit.

ESP32-WROOM-32D

### Power Supply used.

USB

### What is the expected behavior?

I expected to flash the code in secure boot enabled chip using same secure boot key.

### What is the actual behavior?

PS C:\Users\LENOVO\OneDrive\Desktop\abhith\template-app> idf.py flash
Executing action: flash
Serial port COM5
Connecting....
Detecting chip type... Unsupported detection protocol, switching and trying again...
Connecting....
Detecting chip type... ESP32
Running ninja in directory c:\users\lenovo\onedrive\desktop\abhith\template-app\build
Executing "ninja flash"...
[1/5] cmd.exe /C "cd /D C:\Users\LENOVO\OneDrive\Desktop\abhith\templ...s/LENOVO/OneDrive/Desktop/abhith/template-app/build/template-app.bin" 
template-app.bin binary size 0x2fff4 bytes. Smallest app partition is 0x100000 bytes. 0xd000c bytes (81%) free.
[2/5] Performing build step for 'bootloader'
[1/1] cmd.exe /C "cd /D C:\Users\LENOVO\OneDrive\Desktop\abhith\template-app\build\bootloader\esp-idf\esptool_py && C:\Users\LENOVO\.espressif\python_env\idf4.4_py3.8_env\Scripts\python.exe C:/Users/LENOVO/esp/esp-idf/components/partition_table/check_sizes.py --offset 0x10000 bootloader 0x1000 C:/Users/LENOVO/OneDrive/Desktop/abhith/template-app/build/bootloader/bootloader.bin"
Bootloader binary size 0xab90 bytes. 0x4470 bytes (29%) free.
[2/3] cmd.exe /C "cd /D C:\Users\LENOVO\esp\esp-idf\components\esptoo...Users/LENOVO/esp/esp-idf/components/esptool_py/run_serial_tool.cmake" 
esptool.py esp32 -p COM5 -b 460800 --before=default_reset --after=no_reset write_flash --flash_mode dio --flash_freq 40m --flash_size 2MB 0x20000 template-app.bin 0x10000 partition_table/partition-table.bin
esptool.py v3.3.2-dev
Serial port COM5
Connecting.....
Chip is ESP32-D0WDQ6 (revision 1)
Features: WiFi, BT, Dual Core, 240MHz, VRef calibration in efuse, Coding Scheme None
Crystal is 40MHz
MAC: 0c:b8:15:c4:49:90
Uploading stub...
Running stub...
Stub running...
Changing baud rate to 460800
Changed.
Configuring flash size...
Flash will be erased from 0x00020000 to 0x0004ffff...
Flash will be erased from 0x00010000 to 0x00010fff...
Compressed 196596 bytes to 92754...
Writing at 0x00020000... (16 %)
Writing at 0x00030f63... (50 %)
Writing at 0x00036758... (66 %)
Writing at 0x0003ed7e... (83 %)
Writing at 0x00046f82... (100 %)
Wrote 196596 bytes (92754 compressed) at 0x00020000 in 2.4 seconds (effective 657.8 kbit/s)...
Hash of data verified.
Compressed 3140 bytes to 175...
Writing at 0x00010000... (100 %)
Wrote 3140 bytes (175 compressed) at 0x00010000 in 0.1 seconds (effective 322.3 kbit/s)...
Hash of data verified.

Leaving...
Staying in bootloader.
Done

PS C:\Users\LENOVO\OneDrive\Desktop\abhith\template-app> C:\Users\LENOVO\.espressif\python_env\idf4.4_py3.8_env\Scripts\python.exe C:\Users\LENOVO\esp\esp-idf\tools\idf.py -p COM5 monitor
Executing action: monitor
Running idf_monitor in directory c:\users\lenovo\onedrive\desktop\abhith\template-app
Executing "C:\Users\LENOVO\.espressif\python_env\idf4.4_py3.8_env\Scripts\python.exe C:\Users\LENOVO\esp\esp-idf\tools/idf_monitor.py -p COM5 
-b 115200 --toolchain-prefix xtensa-esp32-elf- --target esp32 --revision 1 c:\users\lenovo\onedrive\desktop\abhith\template-app\build\template-app.elf -m 'C:\Users\LENOVO\.espressif\python_env\idf4.4_py3.8_env\Scripts\python.exe' 'C:\Users\LENOVO\esp\esp-idf\tools\idf.py' '-p' 'COM5'"...
--- WARNING: GDB cannot open serial ports accessed as COMx
--- Using \\.\COM5 instead...
--- idf_monitor on \\.\COM5 115200 ---
--- Quit: Ctrl+] | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---
ets Jun  8 2016 00:22:57

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:6664
load:0x40078000,len:14848
load:0x40080400,len:3792
0x40080400: _init at ??:?

secure boot check fail
ets_main.c 371
ets Jun  8 2016 00:22:57

rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:6664
load:0x40078000,len:14848
load:0x40080400,len:3792
0x40080400: _init at ??:?

secure boot check fail
ets_main.c 371

> (REPEATING )

### Steps to reproduce.

Hi,

The secure boot check is fail. I followed this documents [ESP-IDF PROGRAMMING GUIDE](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/security/secure-boot-v1.html) for enabling secure boot v1 (one time flash) without flash encryption.

**STEPS FOLLOWED**

- Step 1: Project Configuration Menu --> **(a)** changed revision 0 to 1( I am using ESP32-WROOM-32D it is revision  1)

**(b)** Security features --> Enable hardware Secure Boot in bootloader-->Enable secure boot version1 
**(c)** Secure bootloader mode --> One-Time flash
**(d)** Partion Table --> Single factory app, no OTA -->Offset of partition table (0x10000)
**All other configurations are in default mode**
saved and exit from the config menu

- Step 2:  Build command using  _idf.py build_
an error message showed as-  _ninja: error: '../secure_boot_signing_key.pem', needed by 'signature_verification_key.bin', missing and no known rule to make it_

- Step 3: Generated secure boot key using command :  _espsecure  generate_signing_key --version 1 secure_boot_signing_key.pem_
key generated succesfully.

- Step 4:  run command - idf.py bootloader 
Terminal output :
Bootloader built. Secure boot enabled, so bootloader not flashed automatically.
One-time flash command is:
        C:/Users/LENOVO/.espressif/python_env/idf4.4_py3.8_env/Scripts/python.exe  C:/Users/LENOVO/esp/esp-idf/components/esptool_py/esptool/esptool.py --chip esp32 --port=(PORT) --baud=(BAUD) --before=default_reset --after=no_reset write_flash --flash_mode dio --flash_freq 40m --flash_size 2MB 0x1000 C:/Users/LENOVO/OneDrive/Desktop/esp-idf-v4.4.2/examples/get-started/hello_world/build/bootloader/bootloader.bin

- Step 5: Using above command, flashed bootloader in chip.

- Step 6:  Flashed the code using - idf.py flash 

### Debug Logs.

```plain
Project build complete. To flash, run this command: 
C:\Users\LENOVO\.espressif\python_env\idf4.4_py3.8_env\Scripts\python.exe ..\..\..\..\esp esp-idf\components esptool_py esptool esptool.py -p (PORT) -b 460880
--before default_reset --after no_reset --chip esp32 write_flash --flash_mode dio --flash_size detect --flash_freq 40m @x10000 build partiti
on_table\partiti on-table.bin 8x20000 build template-app.bin 
PS C:\Users\LENOVO\OneDrive\Desktop\abhith\template-app> C:/Users/LENOVO/.espressif/python_env/idf4.4_py3.8_env/Scripts/python.exe C:/Users/LENOVO/esp/esp-id 
f/components/esptool_py/esptool/esptool.py --chip esp32 --port=COMS --baud=115200 --before=default_reset --after=no_reset write_flash --flash_mode dio --flash 
_freq 40m --flash_size 2MB @x1000 C:/Users/LENOVO/OneDrive/Desktop/abhith/template-app/build/bootloader/bootloader.bin 
esptool.py V3.3.2-dev 
Serial port COMS 
Connecting.... 
Chip is ESP32-DOWDQ6 (revision 1) 
Features: WiFi, BT, Dual Core, 240MHz, VRef calibration in efuse, Coding Scheme None 
Crystal is 40MHz 
MAC: Oc:b8:15:04:49:90 Uploading stub... 
Running stub... 
Stub running... 
Configuring flash size... 
Flash will be erased from @x60001000 to 8x8000afff... 
Compressed 39248 bytes to 24710... 
Wrote 39248 bytes (24710 compressed) at Ox00001000 in 2.8 seconds (effective 114.0 kbit/s)... 
Hash of data verified.

Leaving... 
Staying in bootloader. 
PS C:\Users\LENOVO\OneDrive\Desktop\abhith\template-app> C:\Users\LENOVO\.espressif\python_env\idf4.4_py3.8_env\Scripts\python.exe ..\..\..\..\esp esp-idf.com ponents\esptool_pylesptool\esptool.py -P COMS -b 460800 --before default_reset --after no_reset --chip esp32 write_flash --flash_mode dio --flash_size detect
--flash_freq 40m 0x10000 build\partition_table partition-table.bin x20000 build\template-app.bin esptool.py V3.3.2-dev Serial port COMS Connecting........ Chip is ESP32-DOWDQ6 (revision 1) Features: WiFi, BT, Dual Core, 240MHz, VRef calibration in efuse, Coding Scheme None Crystal is 48MHz MAC: c:b8:15:04:49:90 Uploading stub... Running stub... Stub running... Changing baud rate to 460880 Changed. Configuring flash size... Auto-detected Flash size: 4MB Flash will be erased from Ox00010000 to Ox00010fff... Flash will be erased from Ox00020000 to 8x0084ffff... Compressed 3140 bytes to 175... Wrote 3140 bytes (175 compressed) at Ox00010080 in 0.0 seconds (effective 523.7 kbit/s)... Hash of data verified. Compressed 196596 bytes to 92752... Wrote 196596 bytes (92752 compressed) at Ox00020000 in 2.4 seconds (effective 647.3 kbit/s)... 
Hash of data verified.

Leaving... 
Staying in bootloader. 
PS C:\Users\LENOVO OneDrive\Desktop\abhith\template-app> C:\Users\LENOVO\.espressif\python_env\idf4.4_py3.8_env\Scripts\python.exe C:\Users\LENOVO esplesp-idf \tools\idf.py -p COMS monitor 
Executing action: monitor 
Running idf_monitor in directory c:\users\lenovo\onedrive\desktop\abhith\template-app 
Executing "C:\Users\LENOVO\.espressif\python_env\idf4.4_py3.8_env\Scripts\python.exe C:\Users\LENOVO\esp\esp-idf\tools/idf_monitor.py -P COMS - 115200 --tool 
chain-prefix xtensa-esp32-elf- --target esp32 --revision 1 c:\users\lenovo \onedrive desktop abhith\template-app build\template-app.elf -m 'C:\Users\LENOVO\.es 
pressif\python_env\idf4.4_py3.8_env\Scripts\python.exe' 'C:\Users\LENOVO esp esp-idf tools\idf.py' '-p' 'COMS""... 
--- WARNING: GDB cannot open serial ports accessed as COMX 
--- Using \\. \COMS instead... --- idf_monitor on \\. \COMS 115200 --- 
--- Quit: Ctrl+] | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---
ets Jun 8 2016 00:22:57
rst: 8x1 (POWERON_RESET), boot:x13 (SPI_FAST_FLASH_BOOT)
configsip: , SPIWP: Oxee 
clk_drv: 0x00,q_drv: 0x00,d_drv: 0x00,cs0 drv: 0x00, hd drv: 0x00,wp_drv: Ox00 
mode:DIO, clock div:2
load: Ox3fffoeb8, len: 10768 
load: Ox40078000, len: 24604 
load: 0x40080400, len:3792 
@x40088400: _init at ??:?

entry @x48080694
I (29) boot: ESP-IDF GIT-NOTFOUND 2nd stage bootloader 
I (29) boot: compile time 03:56:45 
I (29) boot: chip revision: 1 
I (33) boot.esp32: SPI Speed : 48MHz 
I (37) boot.esp32: SPI Mode : DIO 
I (42) boot.esp32: SPI Flash Size : 2MB 
I (46) boot: Enabling RNG early entropy source... 
I (52) boot: Partition Table: 
I (55) boot: ## Label          Usage         Type ST Offset Length 
I (63) boot: nvs              WiFi data      01 02 00011000 00006000 
I (70) boot: 1 phy_init       RF data        01 01 00017000 60001000 
I (78) boot: 2 factory        factory app    00 00 88020000 60100000 
I (85) boot: End of partition table 
I (89) esp_image: segment @: paddr=88020020 vaddr=3f408020 size=88298h ( 33424) map 
I (110) esp_image: segment 1: paddr=880282b8 vaddr=3ffb0000 size=82368h (9064) load 
I (114) esp_image: segment 2: paddr=8802a628 vaddr=40080000 size=859f6h ( 23024) load 
I (126) esp_image: segment 3: paddr=88030020 vaddr-400d0020 size=15558h ( 87384) map 
I (158) esp_image: segment 4: paddr=00045580 vaddr=400859f0 size=6588ch ( 22668) load 
I (168) esp_image: segment 5: paddr=0004ae14 vaddr=50000000 size=60010h 16) load 
I (168) esp_image: segment 6: paddr=0004ae2c vaddr=00000000 size-05154h ( 20820) 
I (182) esp_image: Verifying image signature 
I (521) boot: Loaded app from partition at offset @x20000 
I (521) esp_image: segment 6: paddr=88001020 vaddr=3fff0b8 size=82a10h ( 10768) 
I (521) esp_image: segment &: paddr=00007028 vaddr=37978003 size=oza16h ( 28508) 
I (526) esp_image: segment 1: paddr=88003a38 vaddr=40078000 size=8601ch ( 24684) 
I (537) esp_image: segment 2: paddr=88009a5c vaddr=40088400 size=b0edoh (3792) 
I (541) secure_boot_v1: Generating new secure boot key... 
I (547) efuse: BURN BLOCK2 
I (561) efuse: BURN BLOCK2 - OK (write block == read block) 
I (561) secure_boot_v1: Generating secure boot digest... 
I (602) secure_boot_v1: Digest generation complete. 
I (602) boot: Checking secure boot.... 
I (602) efuse: Batch mode of writing fields is enabled 
I (606) secure_boot_v1: blowing secure boot efuse... 
I (612) secure_boot: Read & write protecting new key... 
I (618) secure_boot: Disable JTAG... 
I (622) secure_boot: Disable ROM BASIC interpreter fallback... 
I (629) efuse: BURN BLOCKO 
I (643) efuse: BURN BLOCKO - OK (all write block bits are set) 
I (643) efuse: Batch mode. Prepared fields are committed 
I (647) secure_boot_v1: secure boot is now enabled for bootloader image 
I (654) boot: Disabling RNG early entropy source... 
I (671) cpu start: Pro cpu up. 
I (671) cpu_start: Starting app cpu, entry point is @x40080ffo
8x48080ffo: call_start_cpul at C:/Users/LENOVO/esp/esp-idf/components/esp_system/port/cpu_start.c:160

I (0) cpu_start: App cpu up. 
I (685) cpu_start: Pro cpu start user code 
I (685) cpu_start: cpu freq: 160000000 
I (685) cpu_start: Application information: 
I (690) cpu_start: Project name: template-app 
I (695) cpu_start: App version: 1 
I (699) cpu_start: Compile time: Aug 23 2022 03:56:41 
I (705) cpu_start: ELF file SHA256: 12fa547789889536... 
I (711) cpu_start: ESP-IDF: GIT-NOTFOUND 
I (717) heap_init: Initializing. RAM available for dynamic allocation: 
I (724) heap_init: At 3FFAE6E0 len 30001920 (6 KiB): DRAM 
I (730) heap_init: At 3FFB2CDO len 8002D330 (180 KiB): DRAM 
I (736) heap_init: At 3FFE0440 len 30003AED (14 KiB): D/IRAM 
I (743) heap_init: At 3FFE4350 len 8001BCBO (111 KiB): D/IRAM 
I (749) heap_init: At 4008B27C len 80014D84 (83 KiB): IRAM 
I (756) spi_flash: detected chip: generic 
I (760) spi_flash: flash io: dio 
W (764) spi_flash: Detected size(4096k) larger than the size in the binary image header (2048k). Using the size in the binary image header. 
I (778) cpu_start: Starting scheduler on PRO CPU. 
I (0) cpu_start: Starting scheduler on APP CPU. 
Hello world! 
This is esp32 chip with 2 CPU core(s), WiFi/BT/BLE, silicon revision 1, 2MB external flash Minimum free heap size: 295072 bytes 
Restarting in 10 seconds... 
Restarting in 9 seconds... 
Restarting in 8 seconds... 
Restarting in 7 seconds... 
Restarting in 6 seconds... 
Restarting in 5 seconds... 
Restarting in 4 seconds... 
Restarting in 3 seconds... 
Restarting in 3 seconds... 
Restarting in 2 seconds... 
Restarting in 1 seconds... 
Restarting in 6 seconds... 
Restarting now.
ets Jun 8 2016 00:22:57

rst:Oxc (SW_CPU_RESET), boot:0x13 (SPI_FAST_FLASH_BOOT) 
configsip: 0, SPIWP: Oxee 
clk_drv: 0x00,q_drv: 0x0,d_drv: Oxe, cs@_drv: 0x00, hd_drv: 0x00, wp_drv: 0x00 
mode:DIO, clock div:2 
load: Ox3fff0eb8, len: 10768 
load: 0x40078000, len:24604 
load: 0x48080400, len:3792 
0x40088400: init at ??:?

entry @x40080694 
I (29) boot: ESP-IDF GIT-NOTFOUND 2nd stage bootloader 
I (29) boot: compile time 03:56:45 
I (29) boot: chip revision: 1 
I (33) boot.esp32: SPI Speed : 48MHz 
I (37) boot.esp32: SPI Mode : DIO 
I (42) boot.esp32: SPI Flash Size : 2MB 
I (46) boot: Enabling RNG early entropy source... 
I (52) boot: Partition Table: 
I (55) boot: ## Label          Usage         Type ST Offset Length 
I (63) boot: nvs              WiFi data      01 02 00011000 00006000 
I (70) boot: 1 phy_init       RF data        01 01 00017000 60001000 
I (78) boot: 2 factory        factory app    00 00 88020000 60100000 
I (85) boot: End of partition table 
I (89) esp_image: segment @: paddr=88020020 vaddr=3f408020 size=88298h ( 33424) map 
I (110) esp_image: segment 1: paddr=880282b8 vaddr=3ffb0000 size=82368h (9064) load 
I (114) esp_image: segment 2: paddr=8802a628 vaddr=40080000 size=859f6h ( 23024) load 
I (126) esp_image: segment 3: paddr=88030020 vaddr-400d0020 size=15558h ( 87384) map 
I (158) esp_image: segment 4: paddr=00045580 vaddr=400859f0 size=6588ch ( 22668) load 
I (168) esp_image: segment 5: paddr=0004ae14 vaddr=50000000 size=60010h 16) load 
I (168) esp_image: segment 6: paddr=0004ae2c vaddr=00000000 size-05154h ( 20820) 
I (182) esp_image: Verifying image signature 
I (521) boot: Loaded app from partition at offset @x20000

I (528) secure_boot_v1: bootloader secure boot is already enabled. No need to generate digest. continu 
I (533) boot: Checking secure boot... 
I (538) secure_boot_v1: bootloader secure boot is already enabled, continuing.. 
I (546) boot: Disabling RNG early entropy source... 
I (562) cpu_start: Pro cpu up. 
I (563) cpu_start: Starting app cpu, entry point is 0x40080ffo 
0x40080ffo: call_start_cpul at C:/Users/LENOVO/esp/esp-idf/components/esp_system/port/cpu_start.c:160

I (545) cpu_start: App cpu up. 
I (543) cpu_start: App cpu apont -- endo 
I (577) cpu_start: Pro cpu start user code 
I (577) cpu_start: cpu freq: 160000000 
I (577) cpu_start: Application information: 
I (581) cpu_start: Project name: template-app 
I (587) cpu_start: App version: 1 
I (591) cpu_start: Compile time: Aug 23 2022 03:56:41 
I (597) cpu_start: ELF file SHA256: 12fa547789889536... 
I (603) cpu_start: ESP-IDF:                GIT-NOTFOUND 
I (609) heap_init: Initializing. RAM available for dynamic allocation: 
I (616) heap_init: At 3FFAE6E0 len 80001920 (6 KiB): DRAM 
I (622) heap_init: At 3FFB2CDO len 8802D330 (180 KiB): DRAM 
I (628) heap_init: At 3FFE6440 len 60003AED (14 KiB): D/IRAM 
I (635) heap_init: At 3FFE4350 len 8001BCBO (111 KiB): D/IRAM 
I (641) heap_init: At 4008B27C len 80014084 (83 KiB): IRAM 
I (648) spi_flash: detected chip: generic 
I (652) spi_flash: flash io: dio 
W (656) spi_flash: Detected size(4096k) larger than the size in the binary image header (2048k). Using 
I (670) cpu_start: Starting scheduler on PRO CPU. 
I (0) cpu_start: Starting scheduler on APP CPU. 
Hello world! 
This is esp32 chip with 2 CPU core(s), WiFi/BT/BLE, silicon revision 1, 2MB external flash Minimum free heap size: 295072 bytes 
Restarting in 10 seconds... 
Restarting in 9 seconds... 
Restarting in 8 seconds... 
Restarting in 7 seconds... 
Restarting in 6 seconds... 
Restarting in 5 seconds... 
ets Jun 8 2016 00:22:57
```

### More Information.

**I try to flash the chip again  using this command :**  _PS C:\Users\LENOVO\OneDrive\Desktop\abhith\template-app> C:\Users\LENOVO\.espressif\python_env\idf4.4_py3.8_env\Scripts\python.exe ..\..\..\..\esp\esp-idf\components\esptool_py\esptool\esptool.py -p COM5 -b 460800 --before default_reset --after no_reset --chip esp32  write_flash --flash_mode dio --flash_size detect --flash_freq 40m 0x10000 build\partition_table\partition-table.bin 0x20000 build\template-app.bin_

but it shows an error as:
ets Jun  8 2016 00:22:57

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:6664
load:0x40078000,len:14848
load:0x40080400,len:3792
0x40080400: _init at ??:?

secure boot check fail
ets_main.c 371
ets Jun  8 2016 00:22:57

rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:6664
load:0x40078000,len:14848
load:0x40080400,len:3792
0x40080400: _init at ??:?

secure boot check fail
ets_main.c 371 
**repeating**

**EFUSE SUMMARY**
![CHIP_SMMARY](https://user-images.githubusercontent.com/108787781/187026633-acf96d30-b5d2-4be8-823c-6db418601b6f.png)

Can anyone help me with this? What went wrong.

**Comment by negativekelvin** [comment]
```
rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:6664
load:0x40078000,len:14848
load:0x40080400,len:3792
0x40080400: _init at ??:?
```

```
rst:Oxc (SW_CPU_RESET), boot:0x13 (SPI_FAST_FLASH_BOOT) 
configsip: 0, SPIWP: Oxee 
clk_drv: 0x00,q_drv: 0x0,d_drv: Oxe, cs@_drv: 0x00, hd_drv: 0x00, wp_drv: 0x00 
mode:DIO, clock div:2 
load: Ox3fff0eb8, len: 10768 
load: 0x40078000, len:24604 
load: 0x48080400, len:3792 
0x40088400: init at ??:?
```

You must have accidentally reflashed the bootloader because the logs show two different bootloader sizes

**Comment by ABHITHLALC** [comment]
Thank you for the detailed and sudden helpful response @negativekelvin .
I think I made a mistake by tried to confim if the secure boot enabled properly by flashing another code without using secure key. 

If you don't mind ,Some doubts which I want to clear.

1. Is it possible to reflash the bootloader after enabling secureboot ?
**Below  commad is shown after build**
```
One-time flash command is:
        C:/Users/LENOVO/.espressif/python_env/idf4.4_py3.8_env/Scripts/python.exe  C:/Users/LENOVO/esp/esp-idf/components/esptool_py/esptool/esptool.py --chip esp32 --port=(PORT) --baud=(BAUD) --before=default_reset --after=no_reset write_flash --flash_mode dio --flash_freq 40m --flash_size 2MB 0x1000 C:/Users/LENOVO/OneDrive/Desktop/abhith/template-app/build/bootloader/bootloader.bin
* IMPORTANT: After first boot, BOOTLOADER CANNOT BE RE-FLASHED on same device*
```

2. As the steps mentioned above(from the documment), I did not burn the key manually. Is it really necessary to burn the key with burn key command? If it is necessary to burn key manually then it should be after build project,right? 
3. What is the main diffrence between One-time flash and reflashable in secure boot v1.
4. After enabling secure boot can we flash any code with signing with our private key?

**Comment by sachin0x18** [comment]
Hi @ABHITHLALC,

I can help clear your doubts,

1. It is possible to reflash the bootloader but for that you need to select the "Reflashable" option for "Secure bootloader mode". I would suggest you to go through the [Re-Flashable Software Bootloader](https://docs.espressif.com/projects/esp-idf/en/release-v4.2/esp32/security/secure-boot-v1.html#re-flashable-software-bootloader) section from the documentation. It has all the required details
2. If you decide to use the Reflashable option then you need to burn the key manually after the build
3. In one-time flash, you won't be able to flash any other bootloader as the secure bootloader key is generated on the device. Whereas, in reflashable mode, you provide the secure bootloader key and hence you can flash any bootloader as long as you generate the digest using the same secure bootloader key. All these details are provided in the documentation linked above.
4. Yes, you can flash any application as long as you sign it with the same secure boot signing key.

**Comment by ABHITHLALC** [comment]
Hello @sachin0x18 
Thanks for the reply and thank you for the information.


> 3. In one-time flash, you won't be able to flash any other bootloader as the secure bootloader key is generated on the device. Whereas, in reflashable mode, you provide the secure bootloader key and hence you can flash any bootloader as long as you generate the digest using the same secure bootloader key. All these details are provided in the documentation linked above.



In this case I used One-time flash mode. Can you please tell me which step went wrong.

**Comment by sachin0x18** [comment]
Like negativekelvin pointed out, did you reflash some other bootloader ?

**Comment by ABHITHLALC** [comment]
I think may be I did. But if I try to reflash the other bootloader on a system with secure boot enabled, will it damage the chip? Is there any option to recover this module?

**Comment by sachin0x18** [comment]
If you flash any other bootloader then it simply won't boot up because it doesn't have the same digest. If you still have the same bootloader that you flashed when enabling secure boot then you can flash it again and the device should boot fine

**Comment by ABHITHLALC** [comment]
Which files should be kept safe after enabling secure boot?

**Comment by sachin0x18** [comment]
Only the signing key should be kept safe. You need to ensure that you don't erase/reflash the bootloader.

**Comment by ABHITHLALC** [comment]
Thank you for all the informations.  It's really helpful. I will it out on new chip.

**Comment by ABHITHLALC** [comment]
You were right about bootloader @sachin0x18 @negativekelvin , I accidentally flashed another bootloader. Now I have the old bootloader file that flashed earlier. And I reflashed it as you said

> If you flash any other bootloader then it simply won't boot up because it doesn't have the same digest. If you still have the same bootloader that you flashed when enabling secure boot then you can flash it again and the device should boot fine

But the output is same secure boot check fail, but except the logs shows old bootloader logs.
But the problem is same.

```
ets Jun  8 2016 00:22:57

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff00b8,len:10768
load:0x40078000,len:24604
load:0x40080400,len:3792
0x40080400: _init at ??:?

secure boot check fail   
ets_main.c 371
ets Jun  8 2016 00:22:57

rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff00b8,len:10768
load:0x40078000,len:24604
load:0x40080400,len:3792
0x40080400: _init at ??:?

secure boot check fail
ets_main.c 371
```

**Comment by sachin0x18** [comment]
Hi @ABHITHLALC,

Sorry for the delayed response.

Just want to check few things,

Did you re-build the old bootloader file, if so then its digest would change as well.

If you did not rebuild, did you change the digest that is flashed at 0x0 ?

**Comment by ABHITHLALC** [comment]
> Did you re-build the old bootloader file, if so then its digest would change as well.

Yes I rebuild the file. So maybe that will be the reson.

**Comment by sachin0x18** [comment]
Yeah. Unfortunately, there is no way to recover this module now. You will have to try on a new chip.

Feel free to reopen or submit a new issue if you ever come across any other problem

**Comment by ABHITHLALC** [comment]
Thank you for the support, really appreciated
