### ISSUE TITLE
Running console example alongside Homekit causes error (IDFGH-8167)

### ISSUE THREAD

**Issue by tobyloki** [espressif/esp-idf#9663]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

I am trying to run the advanced console example from https://github.com/espressif/esp-idf/tree/master/examples/system/console/advanced alongside the Homekit sdk. I initialized the console application first and then Homekit. After calling `hap_start()`, I get the error `HAP mDNS Init failed`. How can I fix this problem?

**Comment by igrr** [comment]
Since you have already received reply in https://github.com/espressif/esp-homekit-sdk/issues/94, I will close this issue as duplicate.
