### ISSUE TITLE
freertos

### ISSUE THREAD

**Issue by huyrua291996** [espressif/esp-idf#967]
I have app with mqtt
I got the data from the broker in the wifi_event_handler
How can I send this data to a task in freertos to process the data
I used vQueueSend and vQueueReceive but it didnt work
Can anyone help me

**Comment by klapligehesten** [comment]
I have done something similar. Look in https://github.com/klapligehesten/esp32_mg_web gpio_relay and mg.

**Comment by huyrua291996** [comment]
thanks

**Comment by projectgus** [comment]
Hi @huyrua291996 ,

If you have further questions of this kind, the best place to post them is the ESP32 forum: https://esp32.com/

Angus
