### ISSUE TITLE
I have to restart root to make node get right esp_mesh_get_tsf_time() value sometimes (IDFGH-8179)

### ISSUE THREAD

**Issue by fzboffice** [espressif/esp-idf#9676]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v4.4.2-171-g5927bc2227

### Operating System used.

Windows

### How did you build your project?

Command line with idf.py

### If you are using Windows, please specify command line type.

CMD

### Development Kit.

Custom Board

### Power Supply used.

USB

### What is the expected behavior?

right tsf time

### What is the actual behavior?

wrong tsf time

### Steps to reproduce.

.

**Comment by zhangyanjiaoesp** [comment]
@fzboffice do you still have this issue?
