### ISSUE TITLE
user-guide-devkitc-1 clarification (IDFGH-8190)

### ISSUE THREAD

**Issue by diplfranzhoepfinger** [espressif/esp-idf#9685]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

https://github.com/espressif/esp-idf/blob/5c1044d84d/docs/en/hw-reference/esp32s3/user-guide-devkitc-1.rst

is it correct that some modules have OCTAL Ram but QUAD Flash ?

**Comment by murphymomo** [comment]
Hi @diplfranzhoepfinger 
Yes. For ESP32-S3-DevKitC-1 board integrated with ESP32-S3-WROOM-1/1U module, you may find there are ordering codes ending with “N8R2” and “N8R8”. The “N8R2” indicates that the module integrated has Quad flash + Quad PARAM, while “N8R8” indicates Quad flash + Octal PARAM.
Please refer to [ESP32­S3­-WROOM-­1/­1U Datasheet](https://www.espressif.com/sites/default/files/documentation/esp32-s3-wroom-1_wroom-1u_datasheet_en.pdf) if you want to find out more detailed information about this module.
