### ISSUE TITLE
ADC2 support

### ISSUE THREAD

**Issue by bmetman** [espressif/esp-idf#969]
I was wondering when the ADC2 will be supported. As of now, only ADC1 channels 0 to 9 are supported. Is there any timeline for ADC2 and its channels?

**Comment by krzychb** [comment]
https://github.com/espressif/esp-idf/issues/461#issuecomment-300794116

**Comment by igrr** [comment]
Closing as duplicate of #461. If you wish to receive updates, follow the link to that issue and click "Subscribe" button.

**Comment by bmetman** [comment]
Thank you!
