### ISSUE TITLE
ESP-IDF 5.1 ADC Oneshot missing channel setting (IDFGH-8218)

### ISSUE THREAD

**Issue by remyhx** [espressif/esp-idf#9711]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

ESP-IDF v5.1-dev-537-g91e8312f03

### Operating System used.

macOS

### How did you build your project?

VS Code IDE

### What is the expected behavior?

Like mentioned in the help files: [https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/peripherals/adc_oneshot.html?highlight=oneshot](url), after creating the ADC instance the ADC IO should be specified. (adc_oneshot_chan_cfg_t). The Atten and Bitwidth options are accessible, but Channel is not. Checking the definition in the header file [https://github.com/espressif/esp-idf/blob/master/components/esp_adc/include/esp_adc/adc_oneshot.h](url) looks like a forgotten Channel:

```
 * @brief ADC channel configurations
 */
typedef struct {
    adc_atten_t atten;              ///< ADC attenuation
    adc_bitwidth_t bitwidth;        ///< ADC conversion result bits
} adc_oneshot_chan_cfg_t;
```

### What is the actual behavior?

It doesn't compile

### Steps to reproduce.

Changing the legacy adc driver to the new one by help instructions

**Comment by Icarus113** [comment]
@remyhx  Hi, thanks for this report. The doc is a little bit outdated. As shown in [example](https://github.com/espressif/esp-idf/blob/master/examples/peripherals/adc/oneshot_read/main/oneshot_read_main.c#L60), you'll need to specify the channel, when configuring it, multiple channels can be configured before reading.

The programming guide will be updated later.
