### ISSUE TITLE
[TW#15299] Any time-based job schedulers available in ESP-IDF?

### ISSUE THREAD

**Issue by huming2207** [espressif/esp-idf#972]
Hi all,

I would like to ask that is there any time-based job timer libraries available (similar to cron in Linux) in ESP-IDF and/or FreeRTOS? Or is there any good idea for implementing these functions?

By the way, sorry if I asked dumb question...

Thanks and regards,
Jackson

**Comment by DVSUHZ-g** [comment]
Also curious.

**Comment by Spritetm** [comment]
It depends on what you want exactly... you could say the FreeRTOS timer API can be abused as a barebones cron replacement, for example. If you want anything more complex, you may have to build it yourself (or see if someone else already did).

**Comment by huming2207** [comment]
@Spritetm Thanks for your reply. Now I will plan making a wrapper library for the cron stuff.

**Comment by leoribg** [comment]
Any update?
