### ISSUE TITLE
Incorrect calculation of color data size using bits_per_pixel for ST7789 LCD driver (IDFGH-8241)

### ISSUE THREAD

**Issue by MulattoKid** [espressif/esp-idf#9729]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v4.4.2 1b16ef6cfc2479a08136782f9dc57effefa86f66

### Operating System used.

Linux

### How did you build your project?

VS Code IDE

### Development Kit.

Custom Board

### Power Supply used.

External 5V

### What is the expected behavior?

When calling https://github.com/espressif/esp-idf/blob/1b16ef6cfc2479a08136782f9dc57effefa86f66/components/esp_lcd/src/esp_lcd_panel_st7789.c#L164 to write pixel data to the ST7789 display controller configured in 18bpp mode, 3 bytes should be written per pixel, both in SPI and 8-bit parallel interface mode.

### What is the actual behavior?

I believe the way that the size of the color data to be transferred to the display is calculated in `panel_st7789_draw_bitmap` https://github.com/espressif/esp-idf/blob/1b16ef6cfc2479a08136782f9dc57effefa86f66/components/esp_lcd/src/esp_lcd_panel_st7789.c#L189 is incorrect.

The ST7789 controller (and other similar ones) support both R5G6B5 (16bpp) and R6G6B6 (18bpp). In the case of 16bpp the calculation works fine as `16 / 8 = 2`. However, for 18bpp, we still get `18 / 8 = 2`, which is wrong; it should be `3`. The specification states that each color component should occupy the 6 high bits of a byte, which means 3 full bytes are required.

### Steps to reproduce.

1. Configure the ST7789 driver to 18bpp mode
2. Call `panel_st7789_draw_bitmap`
3. Check the value of `len` in `panel_st7789_draw_bitmap` and see that it's not equal to `pixel_count * 3bpp`

**Comment by suda-morris** [comment]
@MulattoKid Nice catch! We will fix it ASAP.
