### ISSUE TITLE
I2S Microphone

### ISSUE THREAD

**Issue by NicolaRusso** [espressif/esp-idf#973]
Hi guys,

I'm trying to use the ESP32 board (+ I2S mic: https://www.adafruit.com/product/3421) to record a small audio (8 seconds max) and send it through a HTTP POST to my server in order to do a speech-to-text translation.  
Is there an example code that I can follow?

Many thanks for your help!

**Comment by negativekelvin** [comment]
https://github.com/MrBuddyCasino/ESP32_Alexa

**Comment by NicolaRusso** [comment]
@negativekelvin thanks! However the project is very complex, I'm super beginner in this world. Is there a more simple code that show just how to send a buffer array recorded from the mic over a HTTP POST?

Many thanks
