### ISSUE TITLE
Touch Pad read not working properly on esp32s3 (IDFGH-8252)

### ISSUE THREAD

**Issue by nikhil-robinson** [espressif/esp-idf#9740]
I have been testing the touchpad read example from the ESP_IDF examples. I am trying to read touchpad 10,11,12,13 but the values are getting stuck on  these set of numbers no change.

IDF version 4.4.2
using vscode extension

![image](https://user-images.githubusercontent.com/57759123/188839947-06d6fc8b-e78b-43e9-9a78-9c7ad255cc2a.png)

**Comment by FloHomi** [comment]
I discovered the same issue IDF5.0

**Comment by 5ami** [comment]
It might get stuck if the capacitance you are trying to read is to big. If you have bigger capacitors try to reduce number of charge and discharge cycles

**Comment by brainstorm** [comment]
Be mindful of transient issues and re-init (or delay the init in the worst case) if the initial values are clearly out of range, see: https://github.com/micropython/micropython/issues/13178#issuecomment-2254331069
