### ISSUE TITLE
How can I scan all BLE Devices getting UUID data? (IDFGH-8257)

### ISSUE THREAD

**Issue by luanduartefab** [espressif/esp-idf#9745]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [ ] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

I wanna read all BLE Devices around the ESP32 like Arduino IDE allows to do it.
I am new within esp-idf and I need help.
Can someone help me?

An arduino scan read example:

![image](https://user-images.githubusercontent.com/110850655/188934592-0492bac6-8a71-40e9-a438-cea5502a0f30.png)

I need to read same information at the esp-idf!

**Comment by esp-cjh** [comment]
Hi, @luanduartefab 
You can refer to `examples/bluetooth/bluedroid/ble/gatt_security_client`.
In `ESP_GAP_BLE_SCAN_RESULT_EVT` handle (example_ble_sec_gattc_demo.c line 437), 
you can call `esp_ble_resolve_adv_data(&uuid, ESP_BLE_AD_TYPE_128SRV_CMPL, uuid_len)` to get uuid data.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, feel free to reopen.
