### ISSUE TITLE
After TWAI start transmitting data all other FreeRTOS task slowdown, Ethernet W5500 SPI stop responding (IDFGH-8272)

### ISSUE THREAD

**Issue by MacWyznawca** [espressif/esp-idf#9758]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v5.0-beta1-dirty and v5.1-dev-644-g867745a05c-dirty

### Operating System used.

macOS

### How did you build your project?

Command line with idf.py

### Development Kit.

ESP32S3 and ESP32 Custom boards

### Power Supply used.

External 3.3V

### What is the expected behavior?

Run task (SPI Ethernet, RMT WS2812 LED, netif, IP connection, ESP-NOW with normal speed, during TWAI (ESP32S3 or ESP32) is conected with last one TWAI node (ESP32).
TWAI speed 100 or 125 Kbps, 1 meter of CAN bus correctly terminated.

### What is the actual behavior?

All task (especially SPI W5500 Ethernet, netif, ESP-NOW) slow down very much after last one TWAI node initialized TWAI interface (even without transmitting data).

TWAI speed 100 or 125 Kbps, 1 meter of CAN bus correctly terminated.

### Steps to reproduce.

Compile some project with task ESP-NOW, IP connection and other (ESP32S3 or ESP32 board with TWAI interface).
Connect last one active TWAI node (ESP32 or other).

**Comment by MacWyznawca** [comment]
Same code (without any changes accept change target) have same problems with ESP32 (SPI Ethernet W5500)

**Comment by MacWyznawca** [comment]
Which last IDF (v5.1-dev-644-g867745a05c-dirty) same problem

**Comment by abhi-ratnman** [comment]
@team any update on the issue?

**Comment by Dazza0** [comment]
@MacWyznawca Could you provide more details such as:

- Which core the TWAI task is running on
- Which core the TWAI interrupt is installed on (i.e., which core `twai_driver_install()` was called)
- What the are core affinity and priorities of all the other tasks in your application?
- What is the status of the TWAI driver? (Any alerts, error counters etc).
