### ISSUE TITLE
NVS

### ISSUE THREAD

**Issue by huyrua291996** [espressif/esp-idf#976]
Have NVS store data like this
{ "items" : 
      [{"name": "huy"},
       {"age": 15}]
}

**Comment by Spritetm** [comment]
Okay, congratulations! What is your issue precisely?

**Comment by huyrua291996** [comment]
you mean it can store. Pls show me how to store this

**Comment by igrr** [comment]
No, NVS is not designed to store structured data. It is a flat key-value storage. You may construct JSON out of this data and store it in FATFS filesystem (see storage/wear_levelling example).

**Comment by huyrua291996** [comment]
key-value one by one, not key- (key- value), right?

**Comment by lws-team** [comment]
You can either do it one-by-one, or "flatten" the JSON and treat the whole thing like a single unparsed string / blob and use the nvs apis for those.

**Comment by huyrua291996** [comment]
thanks you
