### ISSUE TITLE
TWAI Transmit hang the code (IDFGH-8278)

### ISSUE THREAD

**Issue by abhi-ratnman** [espressif/esp-idf#9763]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v4.4.1

### Operating System used.

Windows

### How did you build your project?

Command line with idf.py

### If you are using Windows, please specify command line type.

CMD

### Development Kit.

ESP32 WROOM 32

### Power Supply used.

USB

### What is the expected behavior?

I am running the [https://github.com/espressif/esp-idf/tree/master/examples/peripherals/twai/twai_network/twai_network_master](url) example trying to read data from vehicle controller. 

`#define ID_MASTER_STOP_CMD      0x0A0
#define ID_MASTER_START_CMD     0x0A1
#define ID_MASTER_PING          0x18DA10F2
#define ID_SLAVE_STOP_RESP      0x0B0
#define ID_SLAVE_DATA           0x0B1
#define ID_SLAVE_PING_RESP      0x18DAF210

typedef enum {
    TX_SEND_PINGS,
    TX_SEND_START_CMD,
    TX_SEND_STOP_CMD,
    TX_TASK_EXIT,
} tx_task_action_t;

typedef enum {
    RX_RECEIVE_PING_RESP,
    RX_RECEIVE_DATA,
    RX_RECEIVE_STOP_RESP,
    RX_TASK_EXIT,
} rx_task_action_t;

static const twai_timing_config_t t_config = TWAI_TIMING_CONFIG_500KBITS();
static const twai_filter_config_t f_config = TWAI_FILTER_CONFIG_ACCEPT_ALL();
static const twai_general_config_t g_config = TWAI_GENERAL_CONFIG_DEFAULT(TX_GPIO_NUM, RX_GPIO_NUM, TWAI_MODE_NORMAL);

static const twai_message_t ping_message = {.identifier = ID_MASTER_PING, .data_length_code = 0,
                                           .ss = 1,.extd=1, .data = {0x03, 0x22 , 0xF4 , 0x7F ,0x00 ,0x00 ,0x00 ,0x00}};
static const twai_message_t start_message = {.identifier = ID_MASTER_START_CMD, .data_length_code = 0,
                                            .data = {0, 0 , 0 , 0 ,0 ,0 ,0 ,0}};
static const twai_message_t stop_message = {.identifier = ID_MASTER_STOP_CMD, .data_length_code = 0,
                                           .data = {0, 0 , 0 , 0 ,0 ,0 ,0 ,0}};`

Above are the changes in code that I did in the Ping message and slave ping repsonse.

The expected behaviour is that when I send the above mentioned ping message a response should come with the above mentioned slave reponse ID. But when I connect the same to ECU of vehicle and test the code hangs after sending. But the same code works when ESP32 is used as a slave. 

Also observed that the same setup is able to receive messages from the ECU without any issue. But in case we want to transmit data it hangs

CAN Transceiver used : TJA1050 with VCC -5v

### What is the actual behavior?

The expected response should be received. 

### Steps to reproduce.

Change the above mentioned code in master example and try running it.

**Comment by Dazza0** [comment]
@abhi-ratnman The TWAI network example demonstrates how to build a simple TWAI network, and is not designed to be work with real ECUs. Most ECUs run some form of network layer protocol on top of the base CAN/TWAI protocol, and the network layer protocol used depends on the type of vehicle/machine  (e.g., CANOpen, SAE J1939, ISO 15765-2). Thus the PING messages in the example are self defined and don't comply to any standard network protocol.

If you need to send messages on your vehicle's CAN bus, please check what network layer protocol it is using. Chances are there may already be a library already written for the well known network protocols, but may require some porting to the ESP32.
