### ISSUE TITLE
Currency: cJSON library

### ISSUE THREAD

**Issue by nkolban** [espressif/esp-idf#978]
The ESP-IDF includes the cJSON library which is excellent.  However, it appears that the version supplied by ESP-IDF is quite far behind the current master found here https://github.com/DaveGamble/cJSON

For example, I wished to use `cJSON_HasObjectItem` and it wasn't present in ESP-IDF.

This issue requests a review of the cJSON library supplied by ESP-IDF and determine if we have an opportunity to replace with a more current release.

**Comment by igrr** [comment]
cJSON has been updated to 1.6.0 in a3da93d834b2adba72e3e62a38c640404c392f07.
