### ISSUE TITLE
Option for Delay after asserting CS in SPI Master (IDFGH-8301)

### ISSUE THREAD

**Issue by Archy404** [espressif/esp-idf#9783]
I'm facing an issue where the addressed slave (ATM90E36 Measurement Chip by Microchip) needs a delay after assertion of CS (ChipSelect) and before the Serial Clock Line (SCLK) is activated. However the provided Driver does not have an Option to insert a delay after asserting CS. (Or i didn't understand how).

The cs_ena_pretrans option does not seem to change the duration between the CS assert and the first edge.

**Comment by nopnop2002** [comment]
The SPI driver has a function to assert CS (Low/High) before data transmission.
If you don't use this feature, will it work?

**Comment by Archy404** [comment]
Thanks for the answer!
The cs_ena_pretrans option did work, there was an error while compiling i think. It did only work after the second recompile.
