### ISSUE TITLE
[TW#15301] Missing signature definitions for lwip_ntohs (and similar)

### ISSUE THREAD

**Issue by nkolban** [espressif/esp-idf#979]
There is a macro definition that maps ntohs(x) to lwip_ntohs(x).  Unfortunately, there is no signature definition for lwip_noths().  This results in warnings in the C/C++ editors.  This issue asks for examination and, if warranted, the declaration of the signatures for lwip_ntohs() and related.

A workaround is to include the following in your code:

```
extern "C" {
	extern uint16_t lwip_ntohs(uint16_t);
	extern uint32_t lwip_ntohl(uint32_t);
	extern uint16_t lwip_htons(uint16_t);
	extern uint32_t lwip_htonl(uint32_t);
}
```

**Comment by zhangyanjiaoesp** [comment]
@nkolban I'm sorry. Could you show me how to reproduce your problem ?

**Comment by zhangyanjiaoesp** [comment]
@nkolban I run an cpp demo which call lwip_ntohs(), but it didn't result in warnings. 
And I found the definition for lwip_ntohs() is in the def.h file, and the definition has already included by "extern "C"". So I don't know why you will result in warning.
