### ISSUE TITLE
how to remove a node was provisioner by esp ble mesh (IDFGH-8333)

### ISSUE THREAD

**Issue by xuanchibkd14** [espressif/esp-idf#9809]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

hi, im trying to know remove a node from my provisioner, but i cant find how to do it,
like that:
~~~
I (576) BLE_MESH: Restored Primary Address 0x0001, next address alloc 0x0006
I (584) BLE_MESH: Restored next NetKeyIndex alloc 0x001
I (589) BLE_MESH: Restored next AppKeyIndex alloc 0x000
I (596) BLE_MESH: Restored NetKeyIndex 0x000
I (600) BLE_MESH: Restored NetKey d4b89072ca3945b78555c498ceab9784
I (609) BLE_MESH: Restored AppKeyIndex 0x000, NetKeyIndex 0x000
I (614) BLE_MESH: Restored AppKey d7e55176d0c14de9a6c3648ce84de1bc
I (622) BLE_MESH: Restored Node 0x0005, UUID 246f2875efe2414e3232303832333032
I (629) BLE_MESH: Restored Node 0x0005, Name NODE-00
I (634) BLE_MESH: Restored Node 0x0005, Composition Data e502000000000a000200000001010000e5020115
~~~
how to remove node `0x0005, Name NODE00`?
thank for helps

**Comment by JiaLWang** [comment]
Hi @xuanchibkd14 
You can use `esp_ble_mesh_config_client_set_state`function to send `config node reset` message to reset a node(other than a provisioner) and remove it from the network.
Hope it can help you.

**Comment by xuanchibkd14** [comment]
> 

Can you explain in more detail?

**Comment by forx157** [comment]
the `esp_ble_mesh_config_client_set_state` has been used  in many examples such as  " ble_mesh_sensor_model" and "ble_mesh_vendor_model"  , you can refer to these examples to get more information, and the opcode named `ESP_BLE_MESH_MODEL_OP_NODE_RESET` was defined in the `esp_ble_mesh_defs.h` is used to reset a node.

**Comment by xuanchibkd14** [comment]
i founded ```esp_ble_mesh_provisioner_delete_node_with_uuid(node->dev_uuid);``` , it is exactly i need, tks for help

**Comment by xd3011** [comment]
Hello. I also have the same problem. Using esp_ble_mesh_provisioner_delete_node_with_uuid(node->dev_uuid) from provisioner to reset the node with uuid as node->dev_uuid. Does it work?
