### ISSUE TITLE
Error while init SD(SDIO) card in SPI mode (IDFGH-8348)

### ISSUE THREAD

**Issue by zanzaradinord** [espressif/esp-idf#9822]
Hi all, im trying to init unnamed SD card in SPI mode (I have some dozens that cards - i need to use it). This card works normally with Win and Linux on PC. I use ESP32-WROOM-32. This card was detected as SDIO card (see log on bottom). With an another good card the mcu works correct.

Environment:
>  source code: esp-idf/examples/storage/sd_card/sdspi
> SPI: MISO - 14, MOSI - 23, SCK - 13, CS - 5,
> ESP32-WROOM-32,
>  ESP-IDF v4.4.2, 
> ubuntu
>  spi speed is low (use SDMMC_FREQ_PROBING);

Anyone with any ideas?
Thanks in advance

`
rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:6660
load:0x40078000,len:14848
ho 0 tail 12 room 4
load:0x40080400,len:3792
entry 0x40080694
I (29) boot: ESP-IDF v4.4.2 2nd stage bootloader
I (29) boot: compile time 22:20:00
I (29) boot: chip revision: 1
I (32) boot_comm: chip revision: 1, min. bootloader chip revision: 0
I (39) boot.esp32: SPI Speed      : 40MHz
I (43) boot.esp32: SPI Mode       : DIO
I (48) boot.esp32: SPI Flash Size : 2MB
I (52) boot: Enabling RNG early entropy source...
I (58) boot: Partition Table:
I (61) boot: ## Label            Usage          Type ST Offset   Length
I (69) boot:  0 nvs              WiFi data        01 02 00009000 00006000
I (76) boot:  1 phy_init         RF data          01 01 0000f000 00001000
I (84) boot:  2 factory          factory app      00 00 00010000 00100000
I (91) boot: End of partition table
I (95) boot_comm: chip revision: 1, min. application chip revision: 0
I (102) esp_image: segment 0: paddr=00010020 vaddr=3f400020 size=0da4ch ( 55884) map
I (131) esp_image: segment 1: paddr=0001da74 vaddr=3ffb0000 size=025a4h (  9636) load
I (135) esp_image: segment 2: paddr=00020020 vaddr=400d0020 size=214e4h (136420) map
I (186) esp_image: segment 3: paddr=0004150c vaddr=3ffb25a4 size=00014h (    20) load
I (187) esp_image: segment 4: paddr=00041528 vaddr=40080000 size=0d174h ( 53620) load
I (214) esp_image: segment 5: paddr=0004e6a4 vaddr=50000000 size=00010h (    16) load
I (221) boot: Loaded app from partition at offset 0x10000
I (221) boot: Disabling RNG early entropy source...
I (234) cpu_start: Pro cpu up.
D (235) efuse: In EFUSE_BLK0__DATA3_REG is used 1 bits starting with 15 bit
D (235) efuse: In EFUSE_BLK0__DATA5_REG is used 1 bits starting with 20 bit
D (241) efuse: In EFUSE_BLK0__DATA3_REG is used 3 bits starting with 9 bit
D (248) efuse: In EFUSE_BLK0__DATA3_REG is used 1 bits starting with 2 bit
I (255) cpu_start: Starting app cpu, entry point is 0x40081168
I (0) cpu_start: App cpu up.
D (269) clk: RTC_SLOW_CLK calibration value: 3289792
I (282) cpu_start: Pro cpu start user code
I (282) cpu_start: cpu freq: 160000000
I (282) cpu_start: Application information:
I (286) cpu_start: Project name:     sd_card
I (291) cpu_start: App version:      1
I (296) cpu_start: Compile time:     Sep 20 2022 22:20:11
I (302) cpu_start: ELF file SHA256:  4950e16078f00a1f...
I (308) cpu_start: ESP-IDF:          v4.4.2
V (313) memory_layout: reserved range is 0x3f40da34 - 0x3f40da6c
D (319) memory_layout: Checking 7 reserved memory ranges:
D (324) memory_layout: Reserved memory range 0x3ffae000 - 0x3ffae6e0
D (331) memory_layout: Reserved memory range 0x3ffb0000 - 0x3ffb2f18
D (337) memory_layout: Reserved memory range 0x3ffe0000 - 0x3ffe0440
D (343) memory_layout: Reserved memory range 0x3ffe3f20 - 0x3ffe4350
D (350) memory_layout: Reserved memory range 0x40070000 - 0x40078000
D (356) memory_layout: Reserved memory range 0x40078000 - 0x40080000
D (363) memory_layout: Reserved memory range 0x40080000 - 0x4008d174
D (369) memory_layout: Building list of available memory regions:
V (375) memory_layout: Examining memory region 0x3ffae000 - 0x3ffb0000
V (382) memory_layout: Start of region 0x3ffae000 - 0x3ffb0000 overlaps reserved 0x3ffae000 - 0x3ffae6e0
D (391) memory_layout: Available memory region 0x3ffae6e0 - 0x3ffb0000
V (398) memory_layout: Examining memory region 0x3ffb0000 - 0x3ffb8000
V (405) memory_layout: Start of region 0x3ffb0000 - 0x3ffb8000 overlaps reserved 0x3ffb0000 - 0x3ffb2f18
D (414) memory_layout: Available memory region 0x3ffb2f18 - 0x3ffb8000
V (421) memory_layout: Examining memory region 0x3ffb8000 - 0x3ffc0000
D (427) memory_layout: Available memory region 0x3ffb8000 - 0x3ffc0000
V (434) memory_layout: Examining memory region 0x3ffc0000 - 0x3ffc2000
D (441) memory_layout: Available memory region 0x3ffc0000 - 0x3ffc2000
V (447) memory_layout: Examining memory region 0x3ffc2000 - 0x3ffc4000
D (454) memory_layout: Available memory region 0x3ffc2000 - 0x3ffc4000
V (460) memory_layout: Examining memory region 0x3ffc4000 - 0x3ffc6000
D (467) memory_layout: Available memory region 0x3ffc4000 - 0x3ffc6000
V (474) memory_layout: Examining memory region 0x3ffc6000 - 0x3ffc8000
D (480) memory_layout: Available memory region 0x3ffc6000 - 0x3ffc8000
V (487) memory_layout: Examining memory region 0x3ffc8000 - 0x3ffca000
D (493) memory_layout: Available memory region 0x3ffc8000 - 0x3ffca000
V (500) memory_layout: Examining memory region 0x3ffca000 - 0x3ffcc000
D (506) memory_layout: Available memory region 0x3ffca000 - 0x3ffcc000
V (513) memory_layout: Examining memory region 0x3ffcc000 - 0x3ffce000
D (520) memory_layout: Available memory region 0x3ffcc000 - 0x3ffce000
V (526) memory_layout: Examining memory region 0x3ffce000 - 0x3ffd0000
D (533) memory_layout: Available memory region 0x3ffce000 - 0x3ffd0000
V (539) memory_layout: Examining memory region 0x3ffd0000 - 0x3ffd2000
D (546) memory_layout: Available memory region 0x3ffd0000 - 0x3ffd2000
V (553) memory_layout: Examining memory region 0x3ffd2000 - 0x3ffd4000
D (559) memory_layout: Available memory region 0x3ffd2000 - 0x3ffd4000
V (566) memory_layout: Examining memory region 0x3ffd4000 - 0x3ffd6000
D (572) memory_layout: Available memory region 0x3ffd4000 - 0x3ffd6000
V (579) memory_layout: Examining memory region 0x3ffd6000 - 0x3ffd8000
D (586) memory_layout: Available memory region 0x3ffd6000 - 0x3ffd8000
V (592) memory_layout: Examining memory region 0x3ffd8000 - 0x3ffda000
D (599) memory_layout: Available memory region 0x3ffd8000 - 0x3ffda000
V (605) memory_layout: Examining memory region 0x3ffda000 - 0x3ffdc000
D (612) memory_layout: Available memory region 0x3ffda000 - 0x3ffdc000
V (619) memory_layout: Examining memory region 0x3ffdc000 - 0x3ffde000
D (625) memory_layout: Available memory region 0x3ffdc000 - 0x3ffde000
V (632) memory_layout: Examining memory region 0x3ffde000 - 0x3ffe0000
D (638) memory_layout: Available memory region 0x3ffde000 - 0x3ffe0000
V (645) memory_layout: Examining memory region 0x3ffe0000 - 0x3ffe4000
V (652) memory_layout: Start of region 0x3ffe0000 - 0x3ffe4000 overlaps reserved 0x3ffe0000 - 0x3ffe0440
V (661) memory_layout: End of region 0x3ffe0440 - 0x3ffe4000 overlaps reserved 0x3ffe3f20 - 0x3ffe4350
D (671) memory_layout: Available memory region 0x3ffe0440 - 0x3ffe3f20
V (677) memory_layout: Examining memory region 0x3ffe4000 - 0x3ffe8000
V (684) memory_layout: Start of region 0x3ffe4000 - 0x3ffe8000 overlaps reserved 0x3ffe3f20 - 0x3ffe4350
D (693) memory_layout: Available memory region 0x3ffe4350 - 0x3ffe8000
V (700) memory_layout: Examining memory region 0x3ffe8000 - 0x3fff0000
D (706) memory_layout: Available memory region 0x3ffe8000 - 0x3fff0000
V (713) memory_layout: Examining memory region 0x3fff0000 - 0x3fff8000
D (720) memory_layout: Available memory region 0x3fff0000 - 0x3fff8000
V (726) memory_layout: Examining memory region 0x3fff8000 - 0x3fffc000
D (733) memory_layout: Available memory region 0x3fff8000 - 0x3fffc000
V (739) memory_layout: Examining memory region 0x3fffc000 - 0x40000000
D (746) memory_layout: Available memory region 0x3fffc000 - 0x40000000
V (753) memory_layout: Examining memory region 0x40070000 - 0x40078000
V (759) memory_layout: Region 0x40070000 - 0x40078000 inside of reserved 0x40070000 - 0x40078000
V (768) memory_layout: Examining memory region 0x40078000 - 0x40080000
V (775) memory_layout: Region 0x40078000 - 0x40080000 inside of reserved 0x40078000 - 0x40080000
V (784) memory_layout: Examining memory region 0x40080000 - 0x40082000
V (790) memory_layout: Region 0x40080000 - 0x40082000 inside of reserved 0x40080000 - 0x4008d174
V (799) memory_layout: Examining memory region 0x40082000 - 0x40084000
V (806) memory_layout: Region 0x40082000 - 0x40084000 inside of reserved 0x40080000 - 0x4008d174
V (814) memory_layout: Examining memory region 0x40084000 - 0x40086000
V (821) memory_layout: Region 0x40084000 - 0x40086000 inside of reserved 0x40080000 - 0x4008d174
V (830) memory_layout: Examining memory region 0x40086000 - 0x40088000
V (837) memory_layout: Region 0x40086000 - 0x40088000 inside of reserved 0x40080000 - 0x4008d174
V (845) memory_layout: Examining memory region 0x40088000 - 0x4008a000
V (852) memory_layout: Region 0x40088000 - 0x4008a000 inside of reserved 0x40080000 - 0x4008d174
V (861) memory_layout: Examining memory region 0x4008a000 - 0x4008c000
V (867) memory_layout: Region 0x4008a000 - 0x4008c000 inside of reserved 0x40080000 - 0x4008d174
V (876) memory_layout: Examining memory region 0x4008c000 - 0x4008e000
V (883) memory_layout: Start of region 0x4008c000 - 0x4008e000 overlaps reserved 0x40080000 - 0x4008d174
D (892) memory_layout: Available memory region 0x4008d174 - 0x4008e000
V (899) memory_layout: Examining memory region 0x4008e000 - 0x40090000
D (906) memory_layout: Available memory region 0x4008e000 - 0x40090000
V (912) memory_layout: Examining memory region 0x40090000 - 0x40092000
D (919) memory_layout: Available memory region 0x40090000 - 0x40092000
V (925) memory_layout: Examining memory region 0x40092000 - 0x40094000
D (932) memory_layout: Available memory region 0x40092000 - 0x40094000
V (939) memory_layout: Examining memory region 0x40094000 - 0x40096000
D (945) memory_layout: Available memory region 0x40094000 - 0x40096000
V (952) memory_layout: Examining memory region 0x40096000 - 0x40098000
D (958) memory_layout: Available memory region 0x40096000 - 0x40098000
V (965) memory_layout: Examining memory region 0x40098000 - 0x4009a000
D (972) memory_layout: Available memory region 0x40098000 - 0x4009a000
V (978) memory_layout: Examining memory region 0x4009a000 - 0x4009c000
D (985) memory_layout: Available memory region 0x4009a000 - 0x4009c000
V (991) memory_layout: Examining memory region 0x4009c000 - 0x4009e000
D (998) memory_layout: Available memory region 0x4009c000 - 0x4009e000
V (1005) memory_layout: Examining memory region 0x4009e000 - 0x400a0000
D (1011) memory_layout: Available memory region 0x4009e000 - 0x400a0000
I (1018) heap_init: Initializing. RAM available for dynamic allocation:
D (1025) heap_init: New heap initialised at 0x3ffae6e0
I (1030) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM
D (1037) heap_init: New heap initialised at 0x3ffb2f18
I (1042) heap_init: At 3FFB2F18 len 0002D0E8 (180 KiB): DRAM
I (1048) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM
I (1055) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
D (1061) heap_init: New heap initialised at 0x4008d174
I (1066) heap_init: At 4008D174 len 00012E8C (75 KiB): IRAM
V (1073) intr_alloc: esp_intr_alloc_intrstatus (cpu 0): checking args
V (1079) intr_alloc: esp_intr_alloc_intrstatus (cpu 0): Args okay. Resulting flags 0xE
D (1087) intr_alloc: Connected src 46 to int 2 (cpu 0)
D (1093) FLASH_HAL: extra_dummy: 1
V (1096) memspi: raw_chip_id: 164020

V (1100) memspi: chip_id: 204016

V (1103) memspi: raw_chip_id: 164020

V (1107) memspi: chip_id: 204016

D (1110) spi_flash: trying chip: issi
D (1114) spi_flash: trying chip: gd
D (1118) spi_flash: trying chip: mxic
D (1121) spi_flash: trying chip: winbond
D (1125) spi_flash: trying chip: generic
I (1129) spi_flash: detected chip: generic
I (1134) spi_flash: flash io: dio
W (1138) spi_flash: Detected size(4096k) larger than the size in the binary image header(2048k). Using the size in the binary image header.
D (1151) cpu_start: calling init function: 0x400da3d0
D (1157) cpu_start: calling init function: 0x400d2068
D (1162) cpu_start: calling init function: 0x400d15cc
V (1167) intr_alloc: esp_intr_alloc_intrstatus (cpu 0): checking args
V (1173) intr_alloc: esp_intr_alloc_intrstatus (cpu 0): Args okay. Resulting flags 0xC02
D (1181) intr_alloc: Connected src 17 to int 3 (cpu 0)
V (1187) intr_alloc: esp_intr_alloc_intrstatus (cpu 0): checking args
V (1193) intr_alloc: esp_intr_alloc_intrstatus (cpu 0): Args okay. Resulting flags 0x40E
D (1201) intr_alloc: Connected src 24 to int 9 (cpu 0)
I (1206) cpu_start: Starting scheduler on PRO CPU.
V (0) intr_alloc: esp_intr_alloc_intrstatus (cpu 1): checking args
V (0) intr_alloc: esp_intr_alloc_intrstatus (cpu 1): Args okay. Resulting flags 0x40E
D (10) intr_alloc: Connected src 25 to int 2 (cpu 1)
I (10) cpu_start: Starting scheduler on APP CPU.
D (1256) heap_init: New heap initialised at 0x3ffe0440
D (1256) heap_init: New heap initialised at 0x3ffe4350
V (1266) intr_alloc: esp_intr_alloc_intrstatus (cpu 0): checking args
V (1266) intr_alloc: esp_intr_alloc_intrstatus (cpu 0): Args okay. Resulting flags 0xE
D (1266) intr_alloc: Connected src 16 to int 12 (cpu 0)
I (1286) example: Initializing SD card
I (1286) example: Using SPI peripheral
D (1296) spi: SPI2 use gpio matrix.
I (1296) example: Mounting filesystem
D (1306) sdspi_host: sdspi_host_init_device: SPI2 cs=5 cd=-1 wp=-1
V (1306) intr_alloc: esp_intr_alloc_intrstatus (cpu 0): checking args
V (1316) intr_alloc: esp_intr_alloc_intrstatus (cpu 0): Args okay. Resulting flags 0x80E
D (1326) intr_alloc: Connected src 30 to int 13 (cpu 0)
V (1326) bus_lock: device registered on bus 1 slot 5.
D (1336) spi_hal: eff: 400, limit: 26666k(/2), 0 dummy, -1 delay
D (1336) spi_master: SPI2: New device added to CS5, effective clock: 400kHz
I (1346) gpio: GPIO[5]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 
V (1356) sdmmc_cmd: sending cmd slot=1 op=52 arg=80000c08 flags=1c00 data=0x0 blklen=0 datalen=0 timeout=1000
V (1366) sdspi_host: sdspi_host_start_command: slot=1, CMD52, arg=0x80000c08 flags=0x40, data=0x0, data_size=0 crc=0x4f
V bus_lock: dev 5 acquired.
D (1376) spi_master: device5 locked the bus
V bus_lock: SPI dev changed from -1 to 5
V (1386) spi_master: polling trans
V (1396) spi_master: polling trans done
V (1396) spi_master: polling trans
V (1396) spi_master: polling trans done
D (1406) spi_master: device5 release bus
V (1406) bus_lock: dev 5 released.
V (1406) sdspi_transaction: r1 = 0x01 hw_cmd.r[0]=0xffffffff
V (1416) sdmmc_cmd: cmd response ffffffff 00000000 00000000 00000000 err=0x0 state=15
V (1426) sdmmc_cmd: sending cmd slot=1 op=0 arg=0 flags=20 data=0x0 blklen=0 datalen=0 timeout=1000
V (1436) sdspi_host: sdspi_host_start_command: slot=1, CMD0, arg=0x00000000 flags=0x100, data=0x0, data_size=0 crc=0x4a
V bus_lock: dev 5 acquired.
V (1446) spi_master: polling trans
V (1446) spi_master: polling trans done
V (1456) bus_lock: dev 5 released.
V bus_lock: dev 5 acquired.
D (1456) spi_master: device5 locked the bus
V (1466) spi_master: polling trans
V (1466) spi_master: polling trans done
V (1466) sdspi_host: start_command_default: ignoring response byte
V (1476) spi_master: polling trans
V (1476) spi_master: polling trans done
D (1486) spi_master: device5 release bus
V (1486) bus_lock: dev 5 released.
V (1496) sdspi_transaction: r1 = 0x00 hw_cmd.r[0]=0xffffffff
V (1496) sdmmc_cmd: cmd response 00000000 00000000 00000000 00000000 err=0x0 state=0
V (1526) sdmmc_cmd: sending cmd slot=1 op=0 arg=0 flags=1c20 data=0x0 blklen=0 datalen=0 timeout=1000
V (1526) sdspi_host: sdspi_host_start_command: slot=1, CMD0, arg=0x00000000 flags=0x4, data=0x0, data_size=0 crc=0x4a
V bus_lock: dev 5 acquired.
V (1536) spi_master: polling trans
V (1536) spi_master: polling trans done
V (1536) bus_lock: dev 5 released.
V bus_lock: dev 5 acquired.
D (1546) spi_master: device5 locked the bus
V (1546) spi_master: polling trans
V (1556) spi_master: polling trans done
V (1556) spi_master: polling trans
V (1566) spi_master: polling trans done
D (1566) spi_master: device5 release bus
V (1566) bus_lock: dev 5 released.
V (1576) sdspi_transaction: r1 = 0x01 hw_cmd.r[0]=0xffffffff
V (1576) sdmmc_cmd: cmd response 00000001 00000000 00000000 00000000 err=0x0 state=0
V (1606) sdmmc_cmd: sending cmd slot=1 op=8 arg=1aa flags=1c30 data=0x0 blklen=0 datalen=0 timeout=1000
V (1606) sdspi_host: sdspi_host_start_command: slot=1, CMD8, arg=0x000001aa flags=0x80, data=0x0, data_size=0 crc=0x43
V bus_lock: dev 5 acquired.
D (1616) spi_master: device5 locked the bus
V (1616) spi_master: polling trans
V (1616) spi_master: polling trans done
V (1626) spi_master: polling trans
V (1626) spi_master: polling trans done
D (1636) spi_master: device5 release bus
V (1636) bus_lock: dev 5 released.
V (1636) sdspi_transaction: r1 = 0x01 hw_cmd.r[0]=0xaa010000
V (1646) sdmmc_cmd: cmd response 000001aa 00000000 00000000 00000000 err=0x0 state=0
D (1656) sdmmc_sd: SDHC/SDXC card
V (1656) sdmmc_cmd: sending cmd slot=1 op=5 arg=0 flags=1030 data=0x0 blklen=0 datalen=0 timeout=1000
V (1666) sdspi_host: sdspi_host_start_command: slot=1, CMD5, arg=0x00000000 flags=0x20, data=0x0, data_size=0 crc=0x2d
V bus_lock: dev 5 acquired.
D (1676) spi_master: device5 locked the bus
V (1686) spi_master: polling trans
V (1686) spi_master: polling trans done
V (1686) spi_master: polling trans
V (1696) spi_master: polling trans done
D (1696) spi_master: device5 release bus
V (1706) bus_lock: dev 5 released.
V (1706) sdspi_transaction: r1 = 0x01 hw_cmd.r[0]=0xffffffff
V (1706) sdmmc_cmd: cmd response ffffffff 00000000 00000000 00000000 err=0x0 state=15
D (1716) sdmmc_io: sdmmc_init_io: IO-only card
D (1726) sdmmc_io: sdmmc_init_io: number of IO functions: 7
V (1726) sdmmc_cmd: sending cmd slot=1 op=5 arg=ff8000 flags=1030 data=0x0 blklen=0 datalen=0 timeout=1000
V (1736) sdspi_host: sdspi_host_start_command: slot=1, CMD5, arg=0x00ff8000 flags=0x20, data=0x0, data_size=0 crc=0x1d
V bus_lock: dev 5 acquired.
D (1756) spi_master: device5 locked the bus
V (1756) spi_master: polling trans
V (1756) spi_master: polling trans done
V (1766) spi_master: polling trans
V (1766) spi_master: polling trans done
D (1776) spi_master: device5 release bus
V (1776) bus_lock: dev 5 released.
V (1776) sdspi_transaction: r1 = 0x01 hw_cmd.r[0]=0xffffffff
V (1786) sdmmc_cmd: cmd response ffffffff 00000000 00000000 00000000 err=0x0 state=15
V (1796) sdmmc_cmd: sending cmd slot=1 op=59 arg=1 flags=1c00 data=0x0 blklen=0 datalen=0 timeout=1000
V (1806) sdspi_host: sdspi_host_start_command: slot=1, CMD59, arg=0x00000001 flags=0x4, data=0x0, data_size=0 crc=0x41
V bus_lock: dev 5 acquired.
D (1816) spi_master: device5 locked the bus
V (1816) spi_master: polling trans
V (1826) spi_master: polling trans done
V (1826) spi_master: polling trans
V (1826) spi_master: polling trans done
D (1836) spi_master: device5 release bus
V (1836) bus_lock: dev 5 released.
D (1846) sdspi_host: data CRC set=1
V (1846) sdspi_transaction: r1 = 0x01 hw_cmd.r[0]=0xffffffff
V (1846) sdmmc_cmd: cmd response 00000001 00000000 00000000 00000000 err=0x0 state=0
D (1856) sdmmc_init: sdmmc_card_init: card type is SDIO
D (1866) sdmmc_common: sdmmc_init_host_frequency: using 400 kHz bus frequency
D (1866) vfs_fat_sdmmc: using pdrv=0
V (1876) sdmmc_cmd: sending cmd slot=1 op=13 arg=0 flags=1c00 data=0x0 blklen=0 datalen=0 timeout=1000
V (1886) sdspi_host: sdspi_host_start_command: slot=1, CMD13, arg=0x00000000 flags=0x8, data=0x0, data_size=0 crc=0x06
V bus_lock: dev 5 acquired.
D (1896) spi_master: device5 locked the bus
V (1906) spi_master: polling trans
V (1906) spi_master: polling trans done
V (1906) spi_master: polling trans
V (1916) spi_master: polling trans done
D (1916) spi_master: device5 release bus
V (1916) bus_lock: dev 5 released.
V (1926) sdspi_transaction: r1 = 0x01 hw_cmd.r[0]=0xffffff00
V (1926) sdmmc_cmd: cmd response 000001ff 00000000 00000000 00000000 err=0x0 state=0
W (1936) vfs_fat_sdmmc: failed to mount card (1)
E (1946) vfs_fat_sdmmc: mount_to_vfs failed (0xffffffff).
I (1946) gpio: GPIO[5]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 
E (1956) example: Failed to mount filesystem. If you want the card to be formatted, set the CONFIG_EXAMPLE_FORMAT_IF_MOUNT_FAILED menuconfig option.`

[1gb-sd-card.txt](https://github.com/espressif/esp-idf/files/9611120/1gb-sd-card.txt)

**Comment by adokitkat** [comment]
Hello. It is possible a SD card from an unknown brand does not fully comply with the SD standard and does not implement SPI mode at all. Maybe you can try 1-line (1-bit) SDMMC mode?

**Comment by adokitkat** [comment]
Thank you for pointing out the fix tip! I will look into it.
