### ISSUE TITLE
Built-in calibration routines for ESP32 (IDFGH-8364)

### ISSUE THREAD

**Issue by elmaghba** [espressif/esp-idf#9834]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

The ESP32's datasheet says that they have built-in calibration routines to cancel any radio imperfections such as:
• Carrier leakage.
• I/Q phase matching.
• Baseband nonlinearities.
• RF nonlinearities.
• Antenna matching.

Is there any way to see what are these calibration routines or to get access these radio imperfection values over time?
This feature is very essential to my work and any help or guidance is very appreciated!

Thank you so much!
Abdu

**Comment by krzychb** [comment]
Hi @elmaghba, I am sorry for missing this issue. Unfortunately, the RF firmware used in the ESP32 is closed source and its related documentation is not publicly available.
