### ISSUE TITLE
[TW#15316] Failure to perform stat() system call on mount point of VFS file system.

### ISSUE THREAD

**Issue by nkolban** [espressif/esp-idf#984]
I have a FATFS file system mounted at "/spiflash".  When I execute the system call:

```
struct stat buf;
int rc = stat("/spiflash", &buf);
```
The return code from stat is `-1` indicating an error.  See:

https://linux.die.net/man/2/stat

My belief is that executing `stat()` on the file system at a mount point should succeed and indicate that it is a directory.

**Comment by mill1000** [comment]
Also seeing this behavior. Errno is set to 22 indicating an invalid argument. Opendir does appear to work if that's an acceptable work around.

Digging deeper it appears to be a ~~bug~~ "feature" of FatFS.
f_stat returns an error of FR_INVALID_NAME for the origin directory. See ff.c @ line 4582 

```
if (dj.fn[NSFLAG] & NS_NONAME) { /* It is origin directory */
    res = FR_INVALID_NAME;
} else { /* Found an object */
    if (fno) get_fileinfo(&dj, fno);
}
```
