### ISSUE TITLE
esp_wifi_stop then esp_wifi_start won't keep WiFi channel configuration (IDFGH-8386)

### ISSUE THREAD

**Issue by wuyuanyi135** [espressif/esp-idf#9855]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

ESP-IDF v5.1-dev-436-g5c1044d84d

### Operating System used.

Windows

### How did you build your project?

Command line with idf.py

### If you are using Windows, please specify command line type.

PowerShell

### Development Kit.

ESP32-S3-WROOM-1-N16R2

### Power Supply used.

USB

### What is the expected behavior?

Executing `esp_wifi_stop`, then `esp_wifi_start`, the previous WiFi configuration should preserved. 

### What is the actual behavior?

If WiFi is not using channel 1, stop-start cycle will not keep the channel configuration, but will restore it back to channel 1, causing `esp_now_send` returning error about inconsistent channel of the peer.

### Steps to reproduce.

```c
#include <esp_now.h>
#include <esp_sleep.h>
#include <esp_wifi.h>
#include <nvs.h>
#include <nvs_flash.h>
#include <string.h>


#define ESPNOW_CHANNEL 1  // <---------------- 2
const static uint8_t broadcast_mac[ESP_NOW_ETH_ALEN] = {0xff, 0xff, 0xff,
                                                        0xff, 0xff, 0xff};

static void nvs_init() {
  esp_err_t ret = nvs_flash_init();
  if (ret == ESP_ERR_NVS_NO_FREE_PAGES ||
      ret == ESP_ERR_NVS_NEW_VERSION_FOUND) {
    ESP_ERROR_CHECK(nvs_flash_erase());
    ret = nvs_flash_init();
  }
  ESP_ERROR_CHECK(ret);
}

static void wifi_init(void) {
  ESP_ERROR_CHECK(esp_netif_init());
  ESP_ERROR_CHECK(esp_event_loop_create_default());
  wifi_init_config_t cfg = WIFI_INIT_CONFIG_DEFAULT();
  ESP_ERROR_CHECK(esp_wifi_init(&cfg));
  ESP_ERROR_CHECK(esp_wifi_set_storage(WIFI_STORAGE_RAM));
  ESP_ERROR_CHECK(esp_wifi_set_mode(WIFI_MODE_STA));
  ESP_ERROR_CHECK(esp_wifi_start());
  ESP_ERROR_CHECK(esp_wifi_set_channel(ESPNOW_CHANNEL, WIFI_SECOND_CHAN_NONE));

  ESP_ERROR_CHECK(esp_wifi_set_protocol(
      WIFI_IF_STA, WIFI_PROTOCOL_11B | WIFI_PROTOCOL_11G | WIFI_PROTOCOL_11N |
                       WIFI_PROTOCOL_LR));
}

static void espnow_init(void) {
  /* Initialize ESPNOW and register sending and receiving callback function. */
  ESP_ERROR_CHECK(esp_now_init());
  ESP_ERROR_CHECK(esp_now_set_wake_window(65535));

  /* Add broadcast peer information to peer list. */
  esp_now_peer_info_t *peer = malloc(sizeof(esp_now_peer_info_t));
  assert(peer != NULL);

  memset(peer, 0, sizeof(esp_now_peer_info_t));
  peer->channel = ESPNOW_CHANNEL;
  peer->ifidx = WIFI_IF_STA;
  peer->encrypt = false;
  memcpy(peer->peer_addr, broadcast_mac, ESP_NOW_ETH_ALEN);
  ESP_ERROR_CHECK(esp_now_add_peer(peer));
  free(peer);
}

_Noreturn void app_main(void) {

  nvs_init();
  wifi_init();
  espnow_init();

  ESP_ERROR_CHECK(esp_sleep_enable_timer_wakeup(3000000));

  while (1) {
    // ESP NOW should work at this point
    uint8_t arbitrary_data[2] = {0x00, 0x01};
    esp_err_t err = esp_now_send(broadcast_mac, arbitrary_data, 2);
    ESP_ERROR_CHECK(err);    // <--------------- 1
    vTaskDelay(pdMS_TO_TICKS(1000));
    ESP_ERROR_CHECK(esp_wifi_stop());
//    ESP_ERROR_CHECK(esp_light_sleep_start());
    ESP_ERROR_CHECK(esp_wifi_start());
//    ESP_ERROR_CHECK(esp_wifi_set_channel(ESPNOW_CHANNEL, WIFI_SECOND_CHAN_NONE));    // <---------- 3
  }
}

```

When running the above code, there are a few scenarios:
* When (2) is channel 1, (3) is not necessary, `esp_now_send` does not crash (1).
* When (2) is not channel 1, without (3) (commented out), (1) will crash with `ESP_ERR_ESPNOW_ARG` error.
*  When (2) is not channel 1, and (3) is enabled, (1) will not crash.

### More Information.

In the documentation (both [sleep mode](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/sleep_modes.html) & [WiFi](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/network/index.html#wi-fi)), I only saw the requirement of stopping WiFi and BT before entering sleep, then use `*_start` to bring it back. I could not find any information of what should be re-configured after stop-start the peripheral. So, I assume re-configuration is not necessary and this behavior is a bug.

**Comment by nachiketkukade** [comment]
@wuyuanyi135 , we do not retain channel information after wifi_stop. If you check the [ESPNOW Documentation](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/network/esp_now.html#initialization-and-de-initialization) on this, it recommends esp_wifi_stop after esp_now_deinit. And esp_now_deinit will delete all the information for paired device including channel.
