### ISSUE TITLE
How to increase espnow encrypted peer list more than 6 (IDFGH-8431)

### ISSUE THREAD

**Issue by rmshub** [espressif/esp-idf#9897]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

By default maximum number of encrypted peer can be added is 6. How to increase this number and maximum possible encrypted devices

**Comment by rmshub** [comment]
Any update on this request ?

**Comment by rmshub** [comment]
Any info on this request ?

**Comment by nachiketkukade** [comment]
@rmshub , espnow uses hardware encryption and since Station / SoftAP also use hardware encryption, sometimes even simultaneously, increasing this limit will affect other interfaces. Therefore there is no plan to increase this limit as of now. Thanks.

**Comment by rmshub** [comment]
could you please update same information in documentation? In documentation mentioned that `The maximum number of paired devices is 20, and the paired encryption devices are no more than 16, the default is 6.`

**Comment by nachiketkukade** [comment]
@rmshub , yes, we will make sure the documentation is updated to match the configurations with the new change. Thanks for bringing this to our attention!

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, fix is available at https://github.com/espressif/esp-idf/commit/d89a51299d54b3a8793872051a95d230e6818ee1, feel free to reopen.
