### ISSUE TITLE
missing spiffs.h

### ISSUE THREAD

**Issue by eyaleb** [espressif/esp-idf#990]
Did a pull followed by a clean build:

```
CC build/spiffs/esp_spiffs.o
/data/esp32/esp-idf-master/components/spiffs/./esp_spiffs.c:16:20: fatal error: spiffs.h: No such file or directory
compilation terminated.
```

**Comment by igrr** [comment]
Please run `git submodule update --init` and try building again. New submodule has been added, and it looks like you don't have it locally.

**Comment by eyaleb** [comment]
I always do `git submodule update` but adding `--init` fixed the problem. Thanks.

**Comment by kabilramar** [comment]
fatal error: spiffs.h: No such file or directory
compilation terminated.

after updating the module from git. what is the reason

**Comment by BrianRamesh** [comment]
F
