### ISSUE TITLE
pre_encrypted_ota ESP-IDF v.4.4.2 (IDFGH-8440)

### ISSUE THREAD

**Issue by ohitsderrick** [espressif/esp-idf#9905]
> Hi @bobbygz ,
> I tried to replicate what you did (clone a v4.4.2 release and then cherry pick the 2 commits), however I wasnt able to do it.
> I am running into the following:
> 
> _ShacharLimor@DESKTOP_SHACHAR MINGW64 ~/esp/esp-idf-v4.4.2_pre_encrypted_ota (pre_encrypted_ota)
> $ git status
> On branch pre_encrypted_ota
> nothing to commit, working tree clean
> 
> ShacharLimor@DESKTOP_SHACHAR MINGW64 ~/esp/esp-idf-v4.4.2_pre_encrypted_ota (pre_encrypted_ota)
> $ git cherry-pick -x 61c68b7
> error: commit 61c68b7f4d1fb6b97fe26844737ee60ea9bb564b is a merge but no -m option was given.
> fatal: cherry-pick failed
> 
> ShacharLimor@DESKTOP_SHACHAR MINGW64 ~/esp/esp-idf-v4.4.2_pre_encrypted_ota (pre_encrypted_ota)
> $ git cherry-pick -x 69f51a9
> error: commit 69f51a989c8a9eaf8f559bb5f4f080146b464c44 is a merge but no -m option was given.
> fatal: cherry-pick failed_
> 
> @bobbygz - can you share your experience and let me whether you run into the same issue? How did you go forward with the cherry picking?
> 
> Eventually I did made some progress by just taking the master but I am sure there is some learning here for me..
> Thanks,
> Shachar

_Originally posted by @shachar-limor in https://github.com/espressif/esp-idf/issues/8776#issuecomment-1251334664_
      
Hi. Our team is looking to integrate the pre_encrypted_ota demo into our project which is using the latest stable ESP-IDF release (v4.4.2). The question above references the same issue, but it was already closed without explaining these specific details to cherry pick correctly. What are the exact commands we're expected to run?

I also posted the same question here: [https://esp32.com/viewtopic.php?f=13&t=29917](url)

**Comment by mahavirj** [comment]
I have replied on the forum thread [here](https://esp32.com/viewtopic.php?f=13&t=29917). Closing this issue.
