### ISSUE TITLE
Erasing STA or AP config with esp_wifi_set_config (IDFGH-8447)

### ISSUE THREAD

**Issue by NoNullptr** [espressif/esp-idf#9910]
### Is your feature request related to a problem?

esp_wifi_restore() resets all config related to WiFi and esp_wifi_set_config does not currently accept a NULL pointer to request that AP- or STA-related config is erased. This leaves only verbose methods to erase a configuration (stopping wifi and erasing all relevant keys from NVS manually)

### Describe the solution you'd like.

esp_wifi_set_config should accept a NULL pointer to delete the configuration. It is currently not documented that it doesn't accept a NULL pointer, only a minor addition to the documentation is required and the case handled by esp_wifi_set_config.

**Comment by mhdong** [comment]
Hi @NoNullptr  esp_wifi_set_config does not accept a NULL pointer to delete the configuration. We use esp_wifi_set_config to set the configuration of the ESP32 STA or AP. If config is NULL, it will return ESP_ERR_INVALID_ARG.

**Comment by NoNullptr** [comment]
@mhdong, it's not productive to repeat what is already in the original description. This is a feature request, so I expect either a rationale for why it should not be possible to erase existing configuration, or an alternative proposal for how the API should look like, or an effort to implement it – I would submit a change myself, but it's part of the internal, closed code.

**Comment by mhdong** [comment]
Hi @NoNullptr We use config fields to transfer some config values to esp_wifi_set_config. If config is NULL, internal code cannot complete configuration. If you want to config it to default value, just assign the default value to config, than call esp_wifi_set_config.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to short of feedback, feel free to reopen with more updates.
