### ISSUE TITLE
esp_wifi_get_config() return wrong channel (IDFGH-8449)

### ISSUE THREAD

**Issue by NoNullptr** [espressif/esp-idf#9912]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v4.4.2

### Operating System used.

macOS

### How did you build your project?

Command line with idf.py

### Development Kit.

ESP32-S3-MINI-1

### Power Supply used.

USB

### What is the expected behavior?

esp_wifi_get_config is expected to return the configuration that was previously set using esp_wifi_set_config

### What is the actual behavior?

NVS stores the current channel ("sta.chan" is 11) and it also connects to the AP, however, esp_wifi_get_config returns invalid channel data (e.g. channel 96, 130, ...)

### Steps to reproduce.

1. Step: set configuration with esp_wifi_set_config()
2. Step: get configuration with esp_wifi_get_config()

**Comment by mhdong** [comment]
Hi @NoNullptr  Thanks for reporting, sorry for slow turnaround, fix on master branch is available at https://github.com/espressif/esp-idf/commit/804bdc1721eb8cbb24be6ab7bd585b1a83c38b97, release v4.4 is available at 9269a536ac123677b165ff531369dfd1338ef103. Thanks.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, feel free to reopen.
