### ISSUE TITLE
ISSUE REGARDING BLUETOOTH RECONNECTION (IDFGH-8454)

### ISSUE THREAD

**Issue by beginner140BB** [espressif/esp-idf#9916]
### Answers checklist.

- [x] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [x] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [ ] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

- 1. connect to esp32 via bluetooth from android phone.
- 2. Checking sending and receiving data.
- 3. diconnected using android phone.
- 4.then again  try to connect to the android phone but not able to connect.

...
![image](https://user-images.githubusercontent.com/83206454/194059780-89139546-379d-4dc2-8ad1-1af06541209b.png)

don't know what is happenning with the events
need to also know what are the basic sdk configuration during bluetooth connection in when using espressif ide
@nkolban @igrr @Lapshin 

code [referred:](https://github.com/espressif/esp-idf/tree/master/examples/bluetooth/bluedroid/classic_bt/bt_spp_acceptor)

Debug Logs.

```
W (24451) BT_RFCOMM: port_rfc_closed RFCOMM connection in server:1 state 2 closed: Closed (res: 19)
I (24451) SPP_ACCEPTOR_DEMO: ESP_SPP_CLOSE_EVT
W (24481) BT_RFCOMM: rfc_find_lcid_mcb LCID reused LCID:0x41 current:0x0
W (24491) BT_RFCOMM: RFCOMM_DisconnectInd LCID:0x41
```

**Comment by vik-gokhale** [comment]
hi @beginner140BB,
We were thinking of looking at the issue in a detailed way...what is the reason you closed the issue?

**Comment by beginner140BB** [comment]
> hi @beginner140BB, We were thinking of looking at the issue in a detailed way...what is the reason you closed the issue? Just curious.
> 
> Regards, Vikram
Hey @vik-gokhale 

Currently the issue has been solved on **example code** by updating to latest verion of ESP-IDF v4.4.2.
There are some bug fixes reported on ESP-IDF v4.4.2 so i think that solves the issue of bluetooth reconnection.

Need to check will there be any issues when integrating to project.

**Comment by vik-gokhale** [comment]
hi @beginner140BB,
busy with more important things and looking at custom code is not something we do.
If we get enough time, we may help. But that is less probable.
If example solves the problem with custom code, please use the code from examples.

**Comment by beginner140BB** [comment]
> If example solves the problem with custom code, please use the code from examples.

actually need to know what is happening in technical point of view when changing this to 1 connection after disconnection it is not reconnecting but able to pair and unpair the bluetooth.

need to know how we can configure the sdkconfig for this by enabling one device should be connected to bluetooth

![image](https://user-images.githubusercontent.com/83206454/194548103-66f66047-000d-48bf-a411-e0037a531967.png)

does anyone expertise in playing with sdkconfig 😊🤷‍♀️

**Comment by alighorbani69** [comment]
Hi 
I had the same issue, the same error:
BT_APPL: bta_jv_add_rfc_port failed to create new listen port

it was not reconnected, but after changing the CONFIG_BT_ACL_CONNECTIONS from 1 to 2 the issue fixed
