### ISSUE TITLE
ESP32 I2C: gaps (about 19 ms) between transactions at 100hz Freertos tickrate (IDFGH-8457)

### ISSUE THREAD

**Issue by mitchellcairns** [espressif/esp-idf#9919]
### Answers checklist.

- [x] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

For my setup, I'm using an official ESP-32 WROOM devkit. 240Mhz set for the clock speed, though changing this setting did not have any impact.

I'm on branch 4.4 release (which supposedly has a fix listed in this commit https://github.com/espressif/esp-idf/commit/cb411a81a2029d7b68926520d6e1ea0590b04988 )

I do not believe that patch properly addressed the issue and more inspection is necessary. 

Changing the 100hz tickrate for Freertos to 1000hz is a band-aid on the issue in my estimation. If this is the expected route to go, let me know and I can close the issue. 

Here's the gaps at 100hz
![Logic_j4F4soIRBM](https://user-images.githubusercontent.com/17264919/194154817-2d6a02c7-cf7e-4d4d-8a59-fd0c411678fa.png)

Gaps at 1000hz tickrate
![image](https://user-images.githubusercontent.com/17264919/194155228-be1cf624-7411-4f82-87fc-60598c6568e7.png)

**Comment by mitchellcairns** [comment]
Furthermore, this is the relevant code minus the driver setup which has the I2C line running at 400kHz

![image](https://user-images.githubusercontent.com/17264919/194155833-1e9d2ccd-cfca-4cb8-9a28-ba85c58b6989.png)

I perform two I2C transactions one right after the other to demonstrate that the gap is intrinsically linked to the Freertos tick rate.

**Comment by o-marshmallow** [comment]
Hi @mitchellcairns ,

I just tested on my side, with `release/v4.4` branch, commit 9269a536ac123677b165ff531369dfd1338ef103, and I cannot reproduce your issue. I am also writing 8 bytes to a device in a `while(1)` loop, here is what I get:
![Screenshot from 2022-10-08 12-49-53](https://user-images.githubusercontent.com/17182820/194689489-9124005e-8db3-4023-9657-0e76ed651474.png)

![Screenshot from 2022-10-08 12-55-26](https://user-images.githubusercontent.com/17182820/194689238-8cbae077-41ad-4e4d-91a3-13b8189d22b8.png)

I kept the default FreeRTOS configuration of 100Hz, and set the CPU clock to 240MHz. My I2C bus is set to 400KHz with 2kOhm pull-up resistors (internal pull-up disabled).

I tested with the approach you showed (`i2c_master_start`, `i2c_master_write`, etc...) and the simplest approach using `i2c_write_to_device`. In both cases, the delay between transactions is less than 50us.

**Comment by mitchellcairns** [comment]
> Hi @mitchellcairns ,
> 
> I just tested on my side on an ESP32-WROOM-32UE, with `release/v4.4` branch, commit [9269a53](https://github.com/espressif/esp-idf/commit/9269a536ac123677b165ff531369dfd1338ef103), and I cannot reproduce your issue. I am also writing 8 bytes to a device in a `while(1)` loop, here is what I get: ![Screenshot from 2022-10-08 12-49-53](https://user-images.githubusercontent.com/17182820/194689489-9124005e-8db3-4023-9657-0e76ed651474.png)
> 
> ![Screenshot from 2022-10-08 12-55-26](https://user-images.githubusercontent.com/17182820/194689238-8cbae077-41ad-4e4d-91a3-13b8189d22b8.png)
> 
> I kept the default FreeRTOS configuration of 100Hz, and set the CPU clock to 240MHz. My I2C bus is set to 400KHz with 2kOhm pull-up resistors (internal pull-up disabled).
> 
> I tested with the approach you showed (`i2c_master_start`, `i2c_master_write`, etc...) and the simplest approach using `i2c_write_to_device`. In both cases, the delay between transactions is less than 50us.
> 
> Can you have a try with the following:
> 
> ```
>     while (1) {
>         i2c_master_write_to_device(I2C_NUM_0, USB_I2C_ADDR, output_buffer, 8, 1000/portTICK_PERIOD_MS);
>     }
> ```
> 
> What about your I2C bus setup? Are you using internal pull-ups or external ones? If external ones, which value?

Thanks for the attempt to replicate. I'm using external pull-ups with internal disabled. Using 1k pull-ups. I don't think that's related as the actual signal is getting through just fine and the clock speed is accurate to what I'm setting; just getting that large delay between commands.

**Comment by o-marshmallow** [comment]
@mitchellcairns I have just tried with an ESP32-WROOM-32, same result.

Can you have a try on master to check whether you also encounter this issue? Can you try with another device?

**Comment by mitchellcairns** [comment]
> @mitchellcairns I have just tried with an ESP32-WROOM-32, same result, it's a success with less than 30us between transactions
> 
> Can you have a try on master to check whether you also encounter this issue? Can you try with another device?

I redownloaded everything once more and now I'm getting 500us timings between commands. This is much more reasonable. I'm not sure what changed, but it seems that the issue is resolved for now.
