### ISSUE TITLE
Support option to resolve hostname as IPv6 with esp_tls_conn_new_xxxx() (IDFGH-8458)

### ISSUE THREAD

**Issue by hideakitai** [espressif/esp-idf#9920]
### Is your feature request related to a problem?

`esp_tls_conn_new_xxxx()` cannot resolve hostname as IPv6 now. Because `esp_tls_hostname_to_fd()` that is called inside of it calls `getaddrinfo()` with fixed option: `hints.ai_family = AF_UNSPEC`. `getaddrinfo()` with `AF_UNSPEC` try to resolve hostname as IPv4 even when IPv4 address is not acquired (e.g. even on IPv6 only network).

https://github.com/espressif/esp-idf/blob/495d35949d50033ebcb89def98f107aa267388c0/components/esp-tls/esp_tls.c#L142-L156

### Describe the solution you'd like.

Could you support an option to `esp_tls_conn_new_xxxx()` to set how to resolve hostname (e.g. AF_UNSPEC, AF_INET, AF_INET6, etc.) ? 

### Additional context.

- IPv6 SLAAC is enabled
- DHCPv6 is disabled

```
CONFIG_LWIP_IPV6=y
CONFIG_LWIP_IPV6_AUTOCONFIG=y
CONFIG_LWIP_IPV6_RDNSS_MAX_DNS_SERVERS=16
```

**Comment by Harshal5** [comment]
Hello, @hideakitai!

Thank you for the issue report. Could you please provide the following info -

- Target chip or module (ESP32, ESP32-S2, ESP32-S3, etc.)
- ESP-IDF version (run git describe --tags) / commit ID
- Example to reproduce the issue (or a minimal code snippet)
- Debug logs
- build sdkconfig

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to short of feedback, feel free to reopen with more updates. Thanks.
