### ISSUE TITLE
BLE advertising name getting corrupted (IDFGH-8465)

### ISSUE THREAD

**Issue by kovid-dozee** [espressif/esp-idf#9927]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

I am using the custom designed esp32 board as our product. In our product we configure the device WiFi (which is working in the sta mode) by the BLE app with some commands.
Its BLE adversting name is getting corrupted whenever we try to connect to a WiFi whose SSID contains characters more then 30. Also the device shows worng password entred whenever the WiFi's password length is more then 20.
I am using the stable toolchain v4.3 for this project.

**Comment by esp-cjh** [comment]
The max length of adv data is 31 bytes. So the length of name in adv data is less than 29 bytes. If the length of adv name more than 29 bytes, it will be truncated.

**Comment by kovid-dozee** [comment]
Will it happen the same with the WiFi SSID? If the device is in STA mode and tries to connect with an AP wifi with more then 30 character, will it get truncated and adds in the Adverstising name?

**Comment by esp-cjh** [comment]
Yes, it's a limitation on the length of the advertising data, not the content.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, feel free to reopen.
