### ISSUE TITLE
Bluetooth example:esp_hid_host trigger watchdog (IDFGH-8481)

### ISSUE THREAD

**Issue by HZBWZ** [espressif/esp-idf#9940]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report
Hi,everybody
I burned the esp_hid_host example to the development esp32_devkit_V4 board, turned on the PS4 handle, and made a Bluetooth connection. After the connection was successful for dozens of seconds, the watchdog was triggered. I could not find the corresponding triggering reason, and I hope to get help
<img width="755" alt="1665238722566" src="https://user-images.githubusercontent.com/67083380/194712877-02a72cf0-a649-4f51-9030-2ac329f66ab7.png">

**Comment by boblane1** [comment]
Hi @iron-LONG1,

Thanks for reporting! Have you ever modified the code in esp_hid_host example, especially the function `hidh_callback`? The delay in `hidh_callback` may cause task watch dog(e.g. Printing too much data). Would you mind providing more logs?

**Comment by iron-LONG1** [comment]
Thank you for your suggestion. It should be that the source program printed too much data to trigger the task watchdog. After commenting out the program in the picture, it did not trigger it again.
![image](https://user-images.githubusercontent.com/67083380/194755126-1379075b-8f5d-487d-8ef8-e13d954c289f.png)

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, feel free to reopen.
