### ISSUE TITLE
const pointer esp_netif_create_wifi (IDFGH-8500)

### ISSUE THREAD

**Issue by NoNullptr** [espressif/esp-idf#9956]
### Is your feature request related to a problem?

The custom wifi init function esp_netif_create_wifi currently takes two parameters (wifi_if and esp_netif_config). The second parameter is not declared as a const pointer

### Describe the solution you'd like.

I would like the interface to be changed to:

esp_netif_t* esp_netif_create_wifi(wifi_interface_t wifi_if, const esp_netif_inherent_config_t *esp_netif_config)

**Comment by david-cermak** [comment]
@NoNullptr Thanks for the suggestion on the const correctness. Yes, I agree we should and will update the API.

Also, please feel free to post the suggested change as a PR, this is just a simple update and would be accepted relatively quickly.

**Comment by NoNullptr** [comment]
Fixed by https://github.com/espressif/esp-idf/commit/d038a35e9667d82b018cc1498b4cc1a6f2901cc7
