### ISSUE TITLE
i80_controller LCD example does not work. (IDFGH-8508)

### ISSUE THREAD

**Issue by BrandonStudio** [espressif/esp-idf#9963]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

**My LCD is constantly white** while serial output is correct.
Please help me to try figuring out the problem.

My LCD display is called ZSX024-B2441, a component in SiPEED Maix Dock. The display is not broken because it works on that board. The display uses 8-bit MCU parallel interface with ST7789V controller.

Here is my connection:
```
   ESP Board                      LCD Screen
┌─────────────┐              ┌────────────────┐
│             │              │                │
│         3V3 ├─────────────►│ VCC            │
│             │              │                │
│         GND ├──────────────┤ GND            │
│             │              │                │
│      GPIO12 ├─────────────►│ D0             │
│             │              │                │
│      GPIO16 ├─────────────►│ D1             │
│             │              │                │
│      GPIO17 ├─────────────►│ D2             │
│             │              │                │
│      GPIO18 ├─────────────►│ D3             │
│             │              │                │
│      GPIO19 ├─────────────►│ D4             │
│             │              │                │
│      GPIO21 ├─────────────►│ D5             │
│             │              │                │
│       GPIO5 ├─────────────►│ D6             │
│             │              │                │
│      GPIO15 ├─────────────►│ D7             │
│             │              │                │
│      GPIO32 ├─────────────►│ PCLK           │
│             │              │                │
│      GPIO27 ├─────────────►│ CS             │
│             │              │                │
│      GPIO33 ├─────────────►│ D/C            │
│             │              │                │
│       GPIO0 ├─────────────►│ RST            │
│             │              │                │
│         3V3 ├─────5R1─────►│ LEDA           │
│             │              │                │
│         GND ├──────────────┤ LEDK           │
│             │              │                │
└─────────────┘              └────────────────┘
```
This is rather urgent for me, could someone please give me some suggestions or a guide to solve the problem?
Please note that I'm using one single PCB board with an FPC connector to the lcd instead of devkit and wire connections, thus it is hard for me to change the pin connections as well as to test signals with oscilloscope.

**Comment by suda-morris** [comment]
which ESP chip? What IDF version? Have you pull-up the `RD` line in your LCD? (this won't be used by the driver, but leaving it to float or low level will interfere with the writing timing). And are you sure you're not using any GPIO that is occupied by the nor flash? You can check [this table](https://docs.espressif.com/projects/esp-idf/en/latest/esp32s3/api-reference/peripherals/gpio.html#overview) for example if you're referring to esp32s3.

**Comment by suda-morris** [comment]
initialization code? we checked the i80_controller example on the master branch, with the following GPIO assignment:
```c
#define TEST_LCD_BK_LIGHT_GPIO (2)
#define TEST_LCD_RST_GPIO      (-1)
#define TEST_LCD_CS_GPIO       (4)
#define TEST_LCD_DC_GPIO       (5)
#define TEST_LCD_PCLK_GPIO     (18)
#define TEST_LCD_DATA0_GPIO    (19)
#define TEST_LCD_DATA1_GPIO    (21)
#define TEST_LCD_DATA2_GPIO    (0)
#define TEST_LCD_DATA3_GPIO    (22)
#define TEST_LCD_DATA4_GPIO    (23)
#define TEST_LCD_DATA5_GPIO    (33)
#define TEST_LCD_DATA6_GPIO    (32)
#define TEST_LCD_DATA7_GPIO    (27)
```
And the LCD screen does show normally.

**Comment by suda-morris** [comment]
> @suda-morris Where do you use `TEST_LCD_*` macro? I didn't see it in `i80_controller_example_main.c`.

We have internal testing boards, the GPIO connections used are defined in [this file](https://github.com/espressif/esp-idf/blob/master/components/esp_lcd/test_apps/i80_lcd/main/test_i80_board.h)

**Comment by suda-morris** [comment]
> testing bus-width=16bit, cmd/param bit-width=8bit

You've commented out LCD_DATA8~15, so running test cases with bus-width=16bits obviously will fail. You can run "lcd_panel_with_i80_interface_(st7789, 8bits)" only, don't have to run them all if you want to test your LCD's connection.

**Comment by suda-morris** [comment]
Yes, it's case 5. The case has configured the bus width to 8:
```c
esp_lcd_i80_bus_config_t bus_config = {
        .dc_gpio_num = TEST_LCD_DC_GPIO,
        .wr_gpio_num = TEST_LCD_PCLK_GPIO,
        .clk_src = LCD_CLK_SRC_DEFAULT,
        .data_gpio_nums = {
            TEST_LCD_DATA0_GPIO,
            TEST_LCD_DATA1_GPIO,
            TEST_LCD_DATA2_GPIO,
            TEST_LCD_DATA3_GPIO,
            TEST_LCD_DATA4_GPIO,
            TEST_LCD_DATA5_GPIO,
            TEST_LCD_DATA6_GPIO,
            TEST_LCD_DATA7_GPIO,
        },
        .bus_width = 8, // HERE
        .max_transfer_bytes = TEST_IMG_SIZE + 10,
    };
```

**Comment by suda-morris** [comment]
> what should I do not to specify the backlight pin while the LCD displays things correctly?

Backlight GPIO is not necessary if you want your LCD to be constantly lit up. Backlight control is not part of the esp_lcd driver, it's simply a GPIO set high/low function. You can drop it if you don't need that.

> there is a bar on the top of the display

I think this is caused by `esp_lcd_panel_set_gap(panel_handle, 0, 20);`, you can remove that function call.

**Comment by Alvin1Zhang** [comment]
Thanks for reporting, will close due to short of feedback, feel free to reopen with more updates.
