### ISSUE TITLE
BLE does not restart after calling esp_restart() (IDFGH-8517)

### ISSUE THREAD

**Issue by rbruneau-altyor** [espressif/esp-idf#9971]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v4.4

### Operating System used.

Windows

### How did you build your project?

Eclipse IDE

### Development Kit.

ESP32-S3

### Power Supply used.

USB

### What is the expected behavior?

BLE successfully restart after calling esp_restart()

### What is the actual behavior?

The BLE logs seem correct, but I cannot see my ESP32-S3 when scanning for BLE devices. The only way to make it work again is to hard reset the board

### Steps to reproduce.

1. init BLE stack
2. call esp_restart()
3. init BLE stack after reset
4. check for ESP32-S3 via BLE scan

### More Information.

I found ideas to restart the BLE peripheral (like calling periph_module_reset before soft restart), but I would like to hear from Espressif developper about the correct way to restart BLE properly after calling esp_restart()

**Comment by esp-cjh** [comment]
Cound you please provide the source code? I call `esp_restart()` and it advertising successfully after reset.

**Comment by rbruneau-altyor** [comment]
To test the issue, I created a simple program where I initialize my BLE interface and call esp_restart() after 10 seconds. Here is the code, which is based on NimBLE examples:
```
void blehr_host_task(void *param)
{
    ESP_LOGI(TAG, "BLE Host Task Started");
    nimble_port_run();
    nimble_port_freertos_deinit();
}
void app_main(void)
{
    int rc;

    esp_err_t ret = nvs_flash_init();
    if (ret == ESP_ERR_NVS_NO_FREE_PAGES || ret == ESP_ERR_NVS_NEW_VERSION_FOUND)
    {
        ESP_ERROR_CHECK(nvs_flash_erase());
        ret = nvs_flash_init();
    }
    ESP_ERROR_CHECK(ret);

    ESP_ERROR_CHECK(esp_nimble_hci_and_controller_init());

    nimble_port_init();

    ble_hs_cfg.sync_cb = BLE_GAP_onSync;
    ble_hs_cfg.reset_cb = BLE_GAP_onReset;
    ble_hs_cfg.gatts_register_cb = BLE_GATTS_SVR_register_cb;

    rc = BLE_GATTS_SVR_init();
    assert(rc == 0);

    rc = ble_svc_gap_device_name_set(BLE_GAP_device_name);
    assert(rc == 0);

    nimble_port_freertos_init(blehr_host_task);

    vTaskDelay(pdMS_TO_TICKS(10000));
    esp_restart();
}
```

The first time I do this power cycle, I get these messages during boot, and the ESP32 cannot be scanned anymore:
![image](https://user-images.githubusercontent.com/114241841/196626109-3d19ecca-469d-4fec-9e53-e08f3f977386.png)

**Comment by RoshanESP** [comment]
Hi @rbruneau-altyor, 
I tried the esp_restart() in blehr example. It works fine for me. I used the latest release/v4.4 branch for my setup. I have attached the success log of the run on  my setup. 
[success_log.txt](https://github.com/espressif/esp-idf/files/9818913/success_log.txt)
I made a connection with the device before esp_restart() as well as after restart. (Just to confirm the device is advertising. can be checked on line number 67 and 154 in the log). 
I am also attaching the patch that I used to make my setup. 
[patch.txt](https://github.com/espressif/esp-idf/files/9818945/patch.txt)
Can you please do the following things :  
1. Check if the git submodule is updated properly
2. Share the commit id on your setup and let me know. 
3. Is your intention only to restart the ble stack or the whole device?

**Comment by rbruneau-altyor** [comment]
Still same behavior after updating...

First commit (by date) I get is the following: 
![image](https://user-images.githubusercontent.com/114241841/196659362-c73c628a-3387-48c1-942e-4ec141be54d6.png)

**Comment by RoshanESP** [comment]
I suspect incorrect code version. https://github.com/espressif/esp-idf/commits/release/v4.4 .. this is pointed to Oct 18 as latest commit. But your code points to Aug 17. It might happen that some other code component too may be pointing to older commit.
I suggest to have a clean clone to ensure codebase is correct

**Comment by AxelLin** [comment]
> the first commit when you do "git log"

Maybe just misunderstanding...
I think you want to know the latest commit rather than the first commit.

**Comment by rbruneau-altyor** [comment]
@AxelLin I did misunderstand at first, but checked with -n 5 and I was missing a whole year of commit. I checkout on release/v4.4 branch and got it fixed as @RoshanESP told me to do.

As I'm building through Eclipse IDE, I have to get my setup fixed before I can try again and check if the problem disappeared. I will give you updates ASAP !

**Comment by rbruneau-altyor** [comment]
@RoshanESP It seems like the problem disappeared with _release/v4.4_
I can't see the `pll_cap_ext 10` log anymore, and now I can scan my BLE device after every `esp_restart()` call.

Thank you very much for your help! Closing the issue
