### ISSUE TITLE
UART : uart_driver_delete does not cares on deleting FreeRTOS Queue.  (IDFGH-8527)

### ISSUE THREAD

**Issue by filimonic** [espressif/esp-idf#9981]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

esp_err_t **uart_driver_delete**(uart_port_t **uart_num**) does not cares on deleting FreeRTOS Queue. 
Neither in code [uart.c](https://github.com/espressif/esp-idf/blob/master/components/driver/uart.c) nor in in documentation.

**Comment by suda-morris** [comment]
Is [this](https://github.com/espressif/esp-idf/blob/master/components/driver/uart.c#L1649) what you're looking for?
