### ISSUE TITLE
[Console] 🚀🚀 Proposal: Console Needs More Flexibility 🚀🚀 (IDFGH-8532)

### ISSUE THREAD

**Issue by chipweinberger** [espressif/esp-idf#9986]
# Console Refactor & Use Case #

Hi, I wanted to share my vision for the Console. These are pretty big changes, so it's not worth starting a PR without discussion first. Let me know your thoughts!

**Features**
- Support all outputs simultaneously (uart, serial jtag, cdc, etc)
- Support multiple Console Inputs simultaneously (_most important_)
- Support enabling & disabling inputs & outputs dynamically (_less importance, but useful for perf_)

I have slowly working towards this with with a couple PRs so far:

**PRs:**
- fix init/deinit: https://github.com/espressif/esp-idf/pull/9983
- add more secondary outputs: https://github.com/espressif/esp-idf/pull/9979

**Edit:** (new PR)
- linenoise2: https://github.com/espressif/esp-idf/pull/9998

However, it is still not flexible enough for my use case.

**Use case:** My product has a _sometimes occupied_ **USB** port, and an _always available but physically internal_ **UART** port.  **I want to choose _at runtime_ which port I will use for the Console input** based on if the usb port is already occupied by a device. Ideally, I'd wouldn't have to choose at all and I could just keep both ports enabled for input all the time (i.e. multiple Console Inputs) unless a usb device is already present. Preferably, it should also be possible to toggle off unused outputs at runtime to improve perf. 😊

 ## Possible Changes ##

### KConfig: ###

A possibility: move away from Primary/Secondary and instead replace with Input/Output.

**Edit: This sort of change would need to go into ESP-IDF 6.0, and it is no longer my preferred solution, due to the large changes required.** See https://github.com/espressif/esp-idf/issues/9986#issuecomment-1281584561 for my prefered solution.

✅ == my use case

> **CONSOLE INPUT (STDIN):**
> (choice) NONE  
> (choice) UART0 ✅  
> (choice) UART1
> (choice) USB CDC
> (choice) USB Serial JTAG ✅
> 
> **CONSOLE OUTPUT (STDOUT):**
> (bool) UART0 ✅
> (bool) UART1
> (bool) USB CDC
> (bool) USB Serial JTAG ✅

 ### Changes to ESP-IDF: ###
- **kConfig** - needs booleans for console output
- **panic.c** - needs to print to all console outputs, not just the primary one
- **linenoise.c** - should support multiple instances, each with their own  FDs
- **esp_console.h** new functions for adding and removing stdin & stdout ports from the console 

# Multiple Console Inputs #

But how do we support input from either the **USB Serial JTAG** *or* the **UART port** simultaneously?

### Option 1: Multiple Threads / Multiple linenoise ### 

**Edit: https://github.com/espressif/esp-idf/pull/9998 PR is now available**

The simplest approach is to instantiate multiple linenoise's, each with their own repl thread. 

e.g.

```
void start_consoles() {
     xTaskCreate(usb_serial_jtag_console_loop...)
     xTaskCreate(uart0_console_loop...)
}

void usb_serial_jtag_console_loop() {
   linenoise_handle_t lnHandle = linenoiseCreateWithInput("/dev/usbserjtag");

    while(!should_stop){
        char* line = linenoise(lnHandle)
    }
}

void stdin_console_loop() {
   linenoise_handle_t lnHandle = linenoiseCreateWithInput("/dev/console");

    while(!should_stop){
        char* line = linenoise(lnHandle)
    }
}
```

- **Advantage:** simple, obvious, how it works
- **Advantage:** easily isolate input from different ports 
- **Disadvantage:** need a thread per input, that can be a lot of memory. Console threads often want bigger stacks
- **Disadvantage:** requires more code and consideration by the user
- **Disadvantage:** Lots of projects today are already set up for a single console and won't immediately benefit from this extra flexibility

### Option 2: Auto Interleave STDIN ### 

Periodically switch which port is acting as STDIN, using a simple heuristic.

 1. Give priority to the first port to send data. 
 2. That port will be given STDIN exclusively until some timeout (5-ish seconds, configurable...)
 3. After 5 seconds of no input, go back to step 1

**KConfig:**

> **CONSOLE INPUT (STDIN):**
> (bool) UART0 ✅  
> (bool) UART1 
> (bool) USB CDC
> (bool) USB Serial JTAG ✅
> 
> If multiple are selected, (bool) **CONFIG_ESP_AUTO_INTERLEAVE_STDIN** will be enabled 
> & (int) **CONFIG_ESP_AUTO_INTERLEAVE_PRIORITY_TIMEOUT_MS** will be available

**How:**
- `vfs_console.h` would expose a single "RX Available" semaphore
-  the RX drivers would "give" to that semaphore whenever input becomes available. 
- `console_read()` would start by taking that semaphore
-  give exclusivity to the first port we see with data pending
- only read from the port with exclusivity
- after 5 seconds of no input from the port with exclusivity, relinquish exclusivity

- **Advantage**: users only need to use a single console thread, simpler user code
- **Advantage**: simpler user code
- **Advantage**: backwards compatible with Option 1 by selecting a single option

**Comment by chipweinberger** [comment]
Or perhaps it would be better to keep the Primary and Secondary theme.

We would support up to , say, 3 consoles ports, which should hopefully be enough for anybody.

Something like this:

> 
> PRIMARY CONSOLE:
> (choice) NONE
> (choice) UART0
> (choice) UART1
> (choice) USB CDC
> (choice) USB Serial JTAG
> 
> (bool) Use Custom UART Settings
> depends on PRIMARY CONSOLE UART0/UART1
> 
> SECONDARY CONSOLE:
> (choice) NONE
> (choice) UART0
> (choice) UART1
> (choice) USB CDC
> (choice) USB Serial JTAG
> 
> (bool) Support Secondary Console Input (stdin)
> 
> (bool) Use Custom UART Settings
> depends on SECONDARY CONSOLE UART0/UART1
> 
> TERTIARY CONSOLE:
> (choice) NONE
> (choice) UART0
> (choice) UART1
> (choice) USB CDC
> (choice) USB Serial JTAG
> 
> (bool) Use Custom UART Settings
> depends on TERTIARY CONSOLE UART0/UART1
> 
> (bool) Support Tertiary Console Input (stdin)

**Comment by chipweinberger** [comment]
I have basic "runtime console choice" working in my project, using a GPIO to determine which console to use after boot. 

The minimal configuration for me is:

- kconfig: primary: UART, secondary: USB Serial/JTAG
- linenoise 2 https://github.com/espressif/esp-idf/pull/9998 to swap stdin/stdout for /dev/usbserjtag after boot)
- `esp_vfs_usb_serial_jtag_use_driver_for_rx()` https://github.com/espressif/esp-idf/pull/9983 to prevent the app from hanging after the terminal is unplugged

**Comment by chipweinberger** [comment]
I have my basic use case running now. (i.e. "bootime console choice"), using this kConfig and my 3 PRs.

> **kconfig:** 
> primary: UART
> secondary: USB Serial/JTAG

With my basic use case is now running, I wanted to comment on the proposed features again:

## Proposed Features

### Support all outputs simultaneously 

I've mostly covered with with https://github.com/espressif/esp-idf/pull/9979. 
It would be great if enabling all outputs was trivial, but it is kind of an annoying code change.
Having good 1st, 2nd, (3rd...), etc consoles, should be good enough for most people.

### Support multiple Console Inputs simultaneously

In my code, I went with **Option 1** (multiple threads). The required changes were:

https://github.com/espressif/esp-idf/pull/9998 : linenoise2
in order to choose the vfs to use for input. i.e. fopen("/dev/usbserjtag")

https://github.com/espressif/esp-idf/pull/9983  : `esp_vfs_usb_serial_jtag_use_driver_for_rx()` 
to prevent the app from hanging after the terminal is unplugged

It would be great if **Option 2** was made a kConfig option for the user, IMO.

### Support enabling & disabling inputs & outputs dynamically

I chose not to support this in my code. Instead, I have both outputs always enabled. For input, I choose the linenoise2 input based on if a USB Terminal is detected at boot time. The required changes were:

https://github.com/espressif/esp-idf/pull/9998 : linenoise2
in order to choose the vfs to use for input. i.e. fopen("/dev/usbserjtag")

https://github.com/espressif/esp-idf/pull/9983  : `esp_vfs_usb_serial_jtag_use_driver_for_rx()` 
to prevent the app from hanging after the terminal is unplugged

**Comment by chipweinberger** [comment]
@igrr Not sure if you saw this, but it helps give context into what I have been working on.

In short, I'd like `USB Serial/JTAG'  w/ Console to be usable by default, without needing to disable UART Console.

**Comment by chipweinberger** [comment]
I will close this issue when 

https://github.com/espressif/esp-idf/pull/10526 & https://github.com/espressif/esp-idf/pull/10132 

land

**Comment by SoucheSouche** [comment]
hi @chipweinberger,

I am working on refactoring the existing console component in ESP-IDF at the moment.

The new design will handle multiple instances that should allow the user to use all available IO simultaneously. It will allow to use other IOs than the one already provided (UART, USB Serial JTAG and USB CDC).

The concept of "console" component will disappear and will be replaced by a more modular approach consisting of a series of standalone components available from the [component registry](https://components.espressif.com/). Mainly, you will be able to find:
- an updated version of linenoise supporting instantiation.
- a component handling command registration and execution
- a component providing the REPL implementation 

I see that you closed this ticket a while ago but since you contributed to the component with your ideas, reported bugs and fixes, I wanted to let you know that the work continues :)

**Comment by chipweinberger** [comment]
I appreciate you updating me on this! Cool to see work is being done on it!

The idea of allowing any IO is a great feature!
