### ISSUE TITLE
[TW#15437] I2C slave mode inform request from master

### ISSUE THREAD

**Issue by hiik3n** [espressif/esp-idf#999]
Hi,

I am setting esp32 as a i2c slave device (i2c_example_main.c from esp-idf example).

However I do not know how to detect request from i2c master, in order to get the data and response to this request.

Does anyone have any idea?
Thank you.

**Comment by hiik3n** [comment]
The trick I tried is listening to the buffer of i2c-received-buffer to get data or request from master.
Hope some one can suggest the better solution.

**Comment by koobest** [comment]
Hi@hiik3n,
Under slave mode, the situation is more complicated. so the driver provides only read and write API currently.
