### ISSUE TITLE
How can device in BLE MESH change role between Provisioner and Node (IDFGH-8545)

### ISSUE THREAD

**Issue by jiabuda** [espressif/esp-idf#9997]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Hi,

Module or chip used: ESP32-WROVER
IDF version: v4.4.3

recently I am building a game between two device with BLE MESH, either one could press Button HOST
first to be a Game Host, so this device would be Provisioner, and the other one could press Button JOIN to be a Node, so the node will be provisioned and they could communicate with each other.

I use the example ble_mesh_provisioner and ble_mesh_node/onoff_server, i try to combine the code into one project, menuconfig then enable these two 
CONFIG_BLE_MESH_NODE=y
CONFIG_BLE_MESH_PROVISIONER=y

two board flashed one start as the provisioner role and the other one start as node, yet the log shows that the node is always waiting but not provisioned.

I trace the code to bt_mesh_init() in esp_ble_mesh/mesh_core/main.c, so if I enable both role in menuconfig, the board which choose to be a node will run bt_mesh_provisioner_prov_init(), line 395, this is not correct, but this process is control by CONFIG macro.

so is there any example to help me to do this? how can i power up a device to be a offline toy, enable or disable to be a provisioner anytime, and enable or disable to be a node anytime? Thanks.

**Comment by forx157** [comment]
hi,@jiabuda, there are two functions named `esp_ble_mesh_provisioner_prov_enable` and `esp_ble_mesh_node_prov_enable`, you can reference how to use them in the example named `onoff_server` and `ble_mesh_provisioner `.
